### ISSUE TITLE
Can't download Virtual Products in a Pack of Virtual Products

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#24850]
#### Describe the bug

When I create a Pack of Virtual Products, I can't download any of them. They are considered "normal" products.

#### Expected behavior

As a customer I should be able to Download my Virtual products

#### Steps to Reproduce

1. Create a Pack of product
2. Add 2 (or more) Virtual Products
3. Add to cart
4. In the customer account and email, customer never receive his Virtual Products

**Screenshots**

**_PS develop_**
<img width="1153" alt="Capture d’écran 2021-06-07 à 16 51 31" src="https://user-images.githubusercontent.com/16019289/121038891-ed0a9f80-c7b0-11eb-9fda-e25829a095cb.png">

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by Progi1984** [comment]
@matks @MatShir Shouldn't it be fixed in Product v2 page ?

**Comment by matks** [comment]
> @matks @MatShir Shouldn't it be fixed in Product v2 page ?

This is not related to the Back Office Product page.

**Comment by Progi1984** [comment]
@matks Are you sure wit `Can't add Virtual products like a vector in PS 1.7.7.X & PS 1.7.8.X` ?

**Comment by matks** [comment]
I am sure.

> Expected behavior: As a customer I should be able to Download my Virtual products

This happens outside of Back Office product page.

Else, this issue story must be reworked to

> > Expected behavior: As a merchant I should not be able to add virtual products to a pack

If the issue is reworked and new scope is only related to Back office Product page we can take it.

**Comment by Progi1984** [comment]
OK. I check it.

**Comment by Progi1984** [comment]
@florine2623 & @PrestaShop/qa-functional It seems there are two problems : shipping on front (duplicate of #18215) and a regression in 178x.

Isn't it ?

**Comment by hibatallahAouadni** [comment]
@Progi1984 you're right! So I edit the issue description :wink: 
This issue is related to #25582

**Comment by Progi1984** [comment]
@hibatallahAouadni @florine2623  Sorry : I retry.

In front office, where must I find my downloads ?
In which email, where must I find my download link or virtual product attachments ?

Have you got some screenshot in previous versions ?

**Comment by hibatallahAouadni** [comment]
Hello @Progi1984 

Really sorry for my late check in :disappointed: it seems this issue is not regression and it's well detailed in this new issue #25581 created by @SD1982 
Check my screen record:

https://drive.google.com/file/d/1Z5ggcp8MGszc7ueXwDHxilHwCXWuXgFL/view

I will close this issue as a duplicate of #25581 and I will add my screen record to it.
Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #25581
