### ISSUE TITLE
Como quitar recuadro al botón?

### ISSUE THREAD

**Issue by markoss01** [PrestaShop/PrestaShop#24858]
Hola,

quería una ayuda.

tengo el prestashop versión 1.7.4.2 tengo este problema, quiero quitar este recuadro en negro al darle clic al boton

![IMG20210608011200](https://user-images.githubusercontent.com/85529317/121099743-b2c4f080-c7f8-11eb-9f86-f1c476dd4186.jpg)

espero que me ayuden gracias

**Comment by hibatallahAouadni** [comment]
Hello @markoss01 

Please send your request in English. English is the norm on GitHub.

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thank you
