### ISSUE TITLE
Dodatkowe pola

### ISSUE THREAD

**Issue by karolgurgul** [PrestaShop/PrestaShop#24874]
Witam,
Chciałbym aby na karcie produktu znalazły się dodatkowe pola:
1. **data ważności** produktu z check box'em "_**widoczne na stronie produktu**_"(chodzi o front office.)
2. pole "**numer faktury zakupowej**" widoczne tylko na karcie produktu back office,
3. pole "**numer katalogowy produktu**" widoczny na karcie produktu back i front office.
4. jeżeli to możliwe sygnalizowanie terminu przydatności produktu (adnotacja do punktu 1)
To tyle.
Pozdrawiam Karol Gurgul

**Comment by hibatallahAouadni** [comment]
Hello @karolgurgul 

Please send your request in English. English is the norm on GitHub.
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the provided template to submit a complete bug report (1) or a feature request (2)**.

![image](https://user-images.githubusercontent.com/23308427/121222990-5826a580-c887-11eb-87c0-4cffb5c3f7a0.png)

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thank you
