### ISSUE TITLE
BO - Currencies page - Cannot create an alternative currency after an upgrade from PS1744 and PS16124

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24871]
#### Describe the bug
In the BO > International > Localization > Currencies page, we cannot create an alternative currency, an error is displayed
![image](https://user-images.githubusercontent.com/16067358/121209256-feb87980-c87a-11eb-8342-e50e598605fc.png)
We reproduced the issue me and @Robin-Fischer-PS with those versions:

- 1775build1 after an upgrade from PS16124, PS1744
- 1774 after an upgrade from PS1744
- 1773 after an upgrade from PS1744

I checked 1775build1 after an upgrade from 1765 => ok

#### Steps to Reproduce

1. Install old version PS1744 or PS16124
2. Install the 1-click upgrade 
3. Make the upgrade to 1775build1 or 1773 or 1774
4. Go to BO > International > Localization > Currencies page
5. Create an alternative currency
6. Click on Save 
7. See error

With PS1769, we cannot create an alternative currency, so after upgrade from PS1744 to PS1769, we don't have this option
![image](https://user-images.githubusercontent.com/16067358/121210205-c5343e00-c87b-11eb-9e11-7969b147b8a5.png)

#### Additional information

* PrestaShop version: 1775, 1774, 1773
* PHP version: 7.2

**Comment by atomiix** [comment]
Fixed by #24908
