### ISSUE TITLE
Rollback to old versions is NOK with MySQL8

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24872]
#### Describe the bug

When we try to make a rollback from PS177 to old versions, we have errors
![image](https://user-images.githubusercontent.com/16067358/121210781-3ecc2c00-c87c-11eb-9edb-dfdceb7bdae8.png)
We reproduced the issue me and @Robin-Fischer-PS with those versions:

- Rollback from PS1775build1 tp PS1744
- Rollback from PS1755build1 to PS1765
- Rollback from PS1755build1 to PS1769
- Rollback from PS1775build1 to PS1752
- Rollback from PS1755build1 to PS16124
- Rollback from PS1774 to PS1744
- Rollback from PS1773 to PS1744

I checked Rollback from PS1769 to PS1744 => ok
![image](https://user-images.githubusercontent.com/16067358/121211342-b1d5a280-c87c-11eb-8a5e-395abc0f43a7.png)

#### Steps to Reproduce

Install Old version (PS1765, 1769, 1744, 16124, 1752
Install the 1-click upgrade module
Make the upgrade
Make a rollback
See error

#### Additional information

* PrestaShop version: 1773, 1774, 1775build1
* PHP version: 7.2

**Comment by Progi1984** [comment]
Just tested this process : 
* Install 1765 from website
* Install the 1-click upgrade module
* Make the upgrade to the archive `prestashop_1.7.7.5+build.1.zip`
* Make a rollback
* No error

Ping @khouloudbelguith & @Robin-Fischer-PS

**Comment by Robin-Fischer-PS** [comment]
I tested following the same steps, I had the error : 

https://drive.google.com/file/d/1g8Nhz4mIznu3V3mSoFALSFkFHRYeS2FV/view?usp=sharing

It's probably due to a specific configuration : I have PHP 7.2.34-21, and MySQL 8.0.25.

**Comment by Progi1984** [comment]
@Robin-Fischer-PS Thanks. I'm going to test it.

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

My configuration:

- PHP 7.2.34-8
- mysql  Ver 8.0.22 for Linux on x86_64 (MySQL Community Server - GPL)

Thank you!

**Comment by Progi1984** [comment]
For PHP, I have the same version. But not MySQL.

![image](https://user-images.githubusercontent.com/1533248/121542700-a57e5080-ca08-11eb-82ee-a78ced555423.png)

@Robin-Fischer-PS Tested once anymore with PHP 7.2 and not the problem.

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

After a discussion with @Robin-Fischer-PS, I manage to reproduce the issue after a rollback from PS1769 to PS1752.
https://drive.google.com/file/d/1EO8g5W-jxJYieOnVSVFKQKJe3z-tsOOC/view?usp=sharing

Thank you!

**Comment by Progi1984** [comment]
We found the problem with @atomiix. It is linked to MySQL 8.0 and the `DROP VIEW`.

**Comment by khouloudbelguith** [comment]
Hi @PrestaShop/prestashop-core-developers,

I checked with @Robin-Fischer-PS, we will change the severity of this issue to critical.
Because this bug affects critical data, as commented [here](https://github.com/PrestaShop/PrestaShop/issues/26346#issuecomment-948473881) => `It can lead to data loss,`

Ping @PrestaShop/prestashop-core-developers @PrestaShop/product-team, we need a new release for the 1-click upgrade module.

What do you think?

Thanks!
