### ISSUE TITLE
Upgrade script of PS 1.7.8.0 beta 1 throws exception

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#24886]
#### Describe the bug

I installed the new files on the server (from `1.7.8.0-beta.1` tag in git).
I try to upgrade according to https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/. When navigating to 
`https://<shop_domain>/install-dev/upgrade/upgrade.php` throws an error

> Fatal error: Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Notice: Array to string conversion in /.../src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php on line 77
> Symfony\Component\Debug\Exception\ContextErrorException: Notice: Array to string conversion in /.../src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php on line 77

#### Expected behavior

I expected the upgrade scripts to run und update my database schema to the new version

#### Steps to Reproduce

1. Install 1.7.7.4 from git
2. Update to 1.7.8.0-beta.1 from git
3. Run `make assets` => I can connect to BO, but the dashboard is empty
4. Navigate to `https://<shop_domain>/install-dev/upgrade/upgrade.php` => The error displays.

#### Additional information

* PrestaShop version: 1.7.7.4 / 1.7.8.0 beta.1
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

> 3. Run `make assets` => I can connect to BO, but the dashboard is empty

I think you should run `make install` and not `make assets` :sweat_smile: 
Please check and feedback.

PS: @NeOMakinG could you please correct me if I'm wrong :pray: 

Thanks!

**Comment by lmeyer1** [comment]
@hibatallahAouadni 

The dashboard was empty, because I didn't yet run the script `install-dev/upgrade/sql/1.7.8.0.sql`.
Once I applied the SQL queries (manually, because `/install-dev/upgrade/upgrade.php` doesn't work), the BO worked again.

The problem that remains is the Exception that is thrown.

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

When you upgrade your shop from 1.7.7.4 to 1.7.8.0, did you use the module autoupgrade?
Please check and feedback.

Thanks!

**Comment by lmeyer1** [comment]
I did it like explained in https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/
>Database upgrade
>
>Once the files have been copied, your shop database is ready to be upgraded.
>
>Some web hosting providers gives you two user accounts to access your database. One with full privileges the other for using in scripts with limited rights. To be able to use this Database upgrade script you have to use the account with full privileges.
All the changes to apply have been defined in the install folder, running them can be done with a specific PHP script.
>
>When you’re ready, run the file install/upgrade/upgrade.php.

Running that file throws the error.

**Comment by NeOMakinG** [comment]
> Hello @lmeyer1
> 
> > 1. Run `make assets` => I can connect to BO, but the dashboard is empty
> 
> I think you should run `make install` and not `make assets` 😅
> Please check and feedback.
> 
> PS: @NeOMakinG could you please correct me if I'm wrong 🙏
> 
> Thanks!

Hey, it's probably not related at all as @lmeyer1 specified, looks like an upgrade issue

**Comment by lmeyer1** [comment]
@hibatallahAouadni 
`make install` is ***not*** referenced by Google on devdocs.prestashop.com. Certainly it should launch the install ? Thus it is unrelated to my issue (as @NeOMakinG points out too), which is a failing ***Upgrade*** of 1.7.7.4 to 1.7.8.0 beta.1. 

Maybe it is expected that an upgrade does not work for the moment. In #23010 `Available for upgrade` is not checked yet.

**Comment by sowbiba** [comment]
I made a fresh install of 1.7.7.4

Download of 1.7.8-beta1
Disable caching
Remove the vendor directory of my shop
copy all files of 1.7.8 into my shop folder
Execute `make`
And execute /install-dev/upgrade/upgrade.php in the browser

Here is the result
![Capture d’écran de 2021-06-15 11-40-38](https://user-images.githubusercontent.com/7426640/122047027-2b1a4b80-cdcf-11eb-9fef-35f653d2412f.png)

**Comment by hibatallahAouadni** [comment]
Thanks @sowbiba so it's a bug and a regression!

**Comment by matks** [comment]
Thank you again @lmeyer1 for the report 😊

**Comment by atomiix** [comment]
I think there are multiple issues here.

I've not been able to reproduce the [first one reported](https://github.com/PrestaShop/PrestaShop/issues/24886#issue-916132043) but that error is probably the reason why the database hadn't been upgraded.

I can reproduce [the error reported by @sowbiba](https://github.com/PrestaShop/PrestaShop/issues/24886#issuecomment-861428728) though, but I'm not sure that it's a regression as this **specific** way of upgrading (calling `install/upgrade/upgrade.php` from a web browser) is never tested (AFAIK). I won't be surprised if this error happens when migrating to the whole 1.7.x branch.

Also, this second error doesn't seem to have any impact on the upgrade process, everything seems to be working fine.

**Comment by lmeyer1** [comment]
I found the root of the exception I reported. It is due to a custom configuration and thus is not an issue of original Prestashop.

Nevertheless, there are still other issues with the manual upgrade process. `install/upgrade/upgrade.php` still does not work.

Now I get 

>Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to PrestaShop\PrestaShop\Adapter\EntityTranslation\DataLangFactory::__construct() must be an instance of PrestaShopBundle\Translation\TranslatorInterface, instance of PrestaShopBundle\Translation\DataCollectorTranslator given, called in (...)/classes/Language.php on line 1572 in (...)/src/Adapter/EntityTranslation/DataLangFactory.php on line 55

**Comment by hibatallahAouadni** [comment]
@lmeyer1 so should I close the issue?

**Comment by lmeyer1** [comment]
@hibatallahAouadni 
I don't know, up to you. This specific issue can be closed. The larger issue "Manual upgrade as in the docs does not work" has to remain open. So maybe you close this one and open a less specific one?

**Comment by hibatallahAouadni** [comment]
@lmeyer1 I think it will be better if you edit the original issue explaining the remaining issue :sweat_smile: 
Thanks in advance :pray:

**Comment by lmeyer1** [comment]
This exception was related to a specificity in my configuration.
Sorry.
