### ISSUE TITLE
additional groups for discount doesn’t work

### ISSUE THREAD

**Issue by nossanhendel** [PrestaShop/PrestaShop#24884]
I am struggling for a few hours on this problem I will be very happy if you can help me out with this..
I need to make another group besides customers that they will get 10% off on all the store
The problem is when I add the new group and I put a discount the new group don’t show any discount in front office..
When I put discount for the all customers group it’s working but any additional group doesn’t work.

Please let me know 
thank you very much

#### Additional information

* PrestaShop version: 1.7.7.4

**Comment by hibatallahAouadni** [comment]
Hello @nossanhendel 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have
questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

PS: Just select the customer group that you want benefit from the discount: 
![image](https://user-images.githubusercontent.com/23308427/121323841-74225980-c910-11eb-8185-156d2d455282.png)

Thank you

**Comment by nossanhendel** [comment]
Hi
Thank you very much for all the information.
I know this is not a place for helping using prestashop but this is a bug..
I know how to make discount for a different group and it works perfectly fine, The problems start with additional groups with a catalog discount.
Because in the functionality of prestashop add groups, after I add a group with catalog discount for this specific group.
When the customer from this group will log in it doesn’t display the discount.

So I thought that Here it’s a good place to write about it because it’s  Problem In prestashop functionality

Please let me know 
thank you very much
Sorry to disturb if it’s not the right place.

**Comment by nossanhendel** [comment]
Hi again
I would like to send you the screenshot so you understand what I mean.. thank you very much

https://screencast-o-matic.com/watch/cr1Q6hVhJJF

**Comment by hibatallahAouadni** [comment]
It seems your issue related to this one #20185

**Comment by nossanhendel** [comment]
Thank you very much 
Even if I do one of any category, when I open it again it will show home category, I have only Hebrew language on this site.. maybe it’s making  the problem?
