### ISSUE TITLE
Database upgrade script incomplete in PS 1.7.8.0-beta.1

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#24891]
#### Describe the bug

I ran the sql script `install-dev/upgrade/sql/1.7.8.0.sql` and expected the database schema to be up to date. But I find that some columns are missing:

    ALTER TABLE `ps_shop_group` ADD `color` VARCHAR(32) NULL AFTER `name`;
    ALTER TABLE `ps_shop` ADD `color` VARCHAR(32) NULL AFTER `name`;

When clicking in the BO on `Modules - Module Manager` I get an exception about the missing columns.

#### Expected behavior

The upgrade script should convert the database schema 1.7.7.4 into 1.7.8.0.

#### Steps to Reproduce

1. On a installation of PS 1.7.7.4, install the files for 1.7.8.0 and run the migration script.
2. Log into the BO. The dashboard displays correctly.
3. Click on any menu entry (that displays the shop selector).

#### Additional information

* PrestaShop version: Upgraded 1.7.74 to 1.7.8.0-beta.1
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

> 1. On a installation of PS 1.7.7.4, install the files for 1.7.8.0 and run the migration script.

Did you upgrade your shop manually or did you use the module autoupgrade?
What migration script? :sweat_smile: 

Thanks!

**Comment by lmeyer1** [comment]
I started out like explained in https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/
>Database upgrade
>
>Once the files have been copied, your shop database is ready to be upgraded.
>
>Some web hosting providers gives you two user accounts to access your database. One with full privileges the other for using in scripts with limited rights. To be able to use this Database upgrade script you have to use the account with full privileges.
All the changes to apply have been defined in the install folder, running them can be done with a specific PHP script.
>
>When you’re ready, run the file install/upgrade/upgrade.php.

Since running that file failed (see #24886), I applied the database schema changes manually from `install-dev/upgrade/sql/1.7.8.0.sql`. 

Sorry that I was not explicit and comlpete enough, I thought I was.

**Comment by lmeyer1** [comment]
This issue is only due to #24886. I'm closing it.

**Comment by hibatallahAouadni** [comment]
@lmeyer1 Thanks!
