### ISSUE TITLE
Add option to automatically load accessories from products in pack

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#24906]
### Situation to imagine

Merchant is offering lot of product packs, let's say a desktop PC sets. A computer, display, keyboard and a mouse. He offers some accessories to products in pack - cleaning stuff for the display, mouse pad for mouse, wrist pad for a keyboard.

We can agree, that it's good to also show these accessories for the pack. But, if you want to do it, you need to add all of these products again to the pack.

### What can make merchant's life easier?

Prestashop can automatically get accessories from all product in the pack, merge them (no duplicates) and show them on the pack product.
So the desktop set will automatically show cleaning stuff and mouse pad in "related products/accessories" section.
If the pack has some extra accessories, it will be added to this.

This option can be disabled in Backoffice >Shop settings  > Products.

### Technical implementation
- $accessories = []
- if "automatically add pack accessories" is enabled
- for each product from pack
- get accessories for the product
- add it to $accessories, if not already present

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thanks for the detailed report :clap: (nailed it like usually) :rocket: 
Well, the Product Team will take it into consideration for future developments. 

Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by Hlavtox** [comment]
Closing, can be integrated by a module just fine.
