### ISSUE TITLE
Missing orders in Google analytics Module

### ISSUE THREAD

**Issue by kdegenkamp** [PrestaShop/PrestaShop#24916]
#### Describe the bug

I am getting constant incorrect google analytics transaction data issue from version 1.7.5 to till now. I used hotjar also to check it out that is also not receiving most number of orders confirmation page. 

#### Expected behavior

All orders must be in google analytics. 

#### Steps to Reproduce

**Screenshots**

![Screenshot 2021-06-11 124545](https://user-images.githubusercontent.com/62239467/121646578-18440600-cab3-11eb-84e0-e755aef129eb.png)
![Screenshot 2021-06-11 124356](https://user-images.githubusercontent.com/62239467/121646594-1d08ba00-cab3-11eb-88c6-41af454cf8c7.png)

#### Additional information

* PrestaShop version: 1.7.5 -1.7.7
* PHP version: 7.2, [7.3]

**Comment by florine2623** [comment]
Hello @kdegenkamp ,

What version of Google Analytics are you using ,

Thanks!

**Comment by kdegenkamp** [comment]
Google analytics module version is 4.0.0 and Google analytics version 3.

**Comment by kdegenkamp** [comment]
with other client i tried hotjar and sometimes customers visit orderconfirmation page but orderconfirmation hook is not called.

**Comment by hibatallahAouadni** [comment]
Hello @kdegenkamp 

Thanks for your patience :pray: 
So your issue is that the Google Analytics interface is showing the wrong number of orders, is that so?
Did you encounter any other problems besides the wrong number of orders?
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @kdegenkamp 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
