### ISSUE TITLE
BO - Logs - No way to know if an error persist after registered for the first time

### ISSUE THREAD

**Issue by prestaalba** [PrestaShop/PrestaShop#24912]
#### Describe the bug

When an error occurred it is registered on backoffice Logs list. But if the same error occur again, there is no way to notice it, because there is no data in the error register that indicates it.

#### Expected behavior

When an error occurred and this error is already registered on Log list, it should register a new record or update the update date from the exist one.

#### Steps to Reproduce

1. Go to backoffice menu Advanced Parameters -> Logs
2. Trigger a common error, for example deleting a required template file (tpl) from shop theme (/themes/classic/templates/catalog/_partials/category-header.tpl) and then browsing any category page in FO.
3. Check Logs list again for the error: No template found for catalog/_partials/category-header
4. Browse again a category page in FO. You will see no difference on the log register anymore.

**Screenshots**

![Captura](https://user-images.githubusercontent.com/18466848/121579770-a22b9a80-c9f1-11eb-92ee-c3779d877cab.JPG)

#### Additional information

This issue came from an incomplete validation before add a new error on class https://github.com/PrestaShop/PrestaShop/blob/develop/classes/PrestaShopLogger.php#L175. If log register is present, at least update date of that register should be updated.
Again, on https://github.com/PrestaShop/PrestaShop/blob/develop/classes/PrestaShopLogger.php#L231 there is another probable bug while the index checked on self::$is_present should be $this->getHash() instead of md5($this->message).

* PrestaShop version: develop
* PHP version: N/A

**Comment by florine2623** [comment]
Hello @prestaalba ,

I think this is an Improvement for PS future versions.

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 

Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know!

Thank you!

**Comment by hibatallahAouadni** [comment]
Hello @prestaalba 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #24706. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #24706
