### ISSUE TITLE
Wrong placement of currency symbol in RTL layout

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/PrestaShop#24917]
#### Describe the bug

The currency symbol in Persian (ریال) is placed without a space and to the right side of the price value.
This is related to the CLDR (localization/CLDR/core/common/main/fa.xml). 

![Screenshot-120703](https://user-images.githubusercontent.com/85633460/121654942-7b359d00-cab3-11eb-9fd7-b8d3a6a86788.png)

![Screenshot-120704](https://user-images.githubusercontent.com/85633460/121654978-7f61ba80-cab3-11eb-9f4d-e2aceb2aeacc.png)

#### Expected behavior

The currency symbol in RTL must be in the left side of price value with a space between them.

#### Steps to Reproduce

BO: Admin > Catalog
FO: Product page, Category page

#### Additional information

* PrestaShop version: 1.7.7.*
* PHP version: 7.3

**Comment by florine2623** [comment]
Hello @mparvazi ,

Your issue is related to : https://github.com/PrestaShop/PrestaShop/issues/22541
Please check !

Thanks !

**Comment by mparvazi** [comment]
Hello @florine2623 ,
Ty for response,

I watched the video in #22541 and that was very useful.

Btw i could not find settings for currency symbol to change the pattern of currency.

![Screenshot 2021-06-11 192057](https://user-images.githubusercontent.com/85633460/121705903-5dcff580-caea-11eb-8dc0-c635c4b680a7.png)

I changed the pattern manually from database, and that works (ps_currency_lang)

![Screenshot 2021-06-11 192449](https://user-images.githubusercontent.com/85633460/121707389-bf449400-caeb-11eb-9414-320c32e26c80.png)
