### ISSUE TITLE
[BO] - Multistore page is not responsive

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#24914]
#### Describe the bug

Multistore page is not responsive.

#### Expected behavior
 
Multistore page should be responsive

#### Steps to Reproduce

1. **BO** > **CONFIGURE** > **Advanced Parameters** > **Multistore**
2. Try to minumise th screen size
3. See error (see screenshot n°1)
4. On **mobile** device 
5. check the multistore table
6. See error > the **Main url of this shop** label and the **url** are overlapped (see screenshot n°2)

**Screenshots**

- screenshot n°1

![image](https://user-images.githubusercontent.com/23308427/121606057-c5843300-ca4d-11eb-858c-e1081903dd86.png)

- screenshot n°2

![image](https://user-images.githubusercontent.com/23308427/121606033-bd2bf800-ca4d-11eb-979f-78ff32fe61bf.png)

#### Additional information

* PrestaShop version: 1.7.8.x & develop
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by @NeOMakinG in #24918
