### ISSUE TITLE
Product Wrong location in PDF delivery

### ISSUE THREAD

**Issue by maestrobo** [PrestaShop/PrestaShop#24935]
If you display the location value when using OrderInvoice (when printing a PDF), the location got a wrong value.

To reproduce the issue, just set a location value to a product then click the PDF delivery, the location value is either wrong or missing.

Version : PS 1.7.7.4

In the class Order, it seems that there is already a fix with the code product['location']=.....
But in "Order Invoice" class (classes/order/OrderInvoice.php), it is missing. It is called by the PDF generator.

To do that, around line 92:

```
    $this->setProductImageInformations($row);
				
   $row['location'] = StockAvailable::getLocation($row['product_id'], $row['product_attribute_id'], (int) $order->id_shop); //fix
			
    $this->setProductCurrentStock($row);
 

```

#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @maestrobo 


Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
