### ISSUE TITLE
HTTP ERROR 500 clear cache

### ISSUE THREAD

**Issue by eveneme** [PrestaShop/PrestaShop#24930]
1. Go to 'Admin Panel clear cache'
2. Click on 'clear cache and error 500'
the problem shows up on every version of php 7.1 7.2 7.3

* PrestaShop version: 1.7.7.4
* PHP version: 7.2.26

**Comment by hibatallahAouadni** [comment]
Hello @eveneme 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a module problem.

We will close this issue.

Thanks!
