### ISSUE TITLE
 ContextErrorException mass of bugs 

### ISSUE THREAD

**Issue by eveneme** [PrestaShop/PrestaShop#24934]
1. a lot of errors with the debug mode on after entering various products and using the admin panel. 

screenshoot pdf
https://www119.zippyshare.com/v/AA5Xrsqi/file.html
https://www119.zippyshare.com/v/fwkD566P/file.html
https://www119.zippyshare.com/v/hBo6OC0c/file.html

* PrestaShop version: 1.7.7.4
* PHP version: 7.1 7.2. 7.3
* Apache

**Comment by hibatallahAouadni** [comment]
Hello @eveneme 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have
questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
