### ISSUE TITLE
? symbols are being shown in generated invoices for Armenian language

### ISSUE THREAD

**Issue by mrAKAR** [PrestaShop/PrestaShop#24937]
#### Describe the bug

When you use Armenian language in BO and generate an invoice for order you get '?' in place of letters.

#### Expected behavior

There must be correct letters used in invoice during generation process.

#### Steps to Reproduce

1. Add Armenia language
2. Switch BO language to Armenian
3. Open orders page and generate an invoice for any order
4. You will see all Armenian letters are replaced with '?' symbol

#### Additional information

* PrestaShop version: 1.7.*

**Comment by Gipielle** [comment]
This bug is also present with Russian and Greek, with backoffice in Italian or english

**Comment by hibatallahAouadni** [comment]
Hello @mrAKAR 

It's seem your issue related to this one #12308
Could you please check if you have the same problem when you change the currency?
Please check and feedback.

Thanks!
