### ISSUE TITLE
Error in upgrade queries PS 1.7.8.0 beta.1

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#24943]
#### Describe the bug

The table definition of `PREFIX_feature_flag` does not fit the data inserted.

#### Expected behavior

I expect the queries to run without error.

#### Steps to Reproduce

1. Following `https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/`run `http://<shop_domain>/install/upgrade/upgrade.php`. Run the script `install-dev/upgrade/sql/1.7.8.0.sql` manually (because of #24886 `/install-dev/upgrade/upgrade.php` won't run)
2. Run the second last query.
3. run the last query
You get error 
> Error 1406 - Data too long for column 'description_wording' at row 1

#### Additional information

```
CREATE TABLE IF NOT EXISTS `PREFIX_feature_flag` (
  `id_feature_flag` INT(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(191) COLLATE utf8mb4_general_ci NOT NULL,
  `state` TINYINT(1) NOT NULL DEFAULT '0',
  `label_wording` VARCHAR(191) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `label_domain` VARCHAR(255) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `description_wording` VARCHAR(191) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `description_domain` VARCHAR(255) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`id_feature_flag`),
  UNIQUE KEY `UNIQ_91700F175E237E06` (`name`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `PREFIX_feature_flag` (`name`, `state`, `label_wording`, `label_domain`, `description_wording`, `description_domain`)
VALUES
	('product_page_v2', 0, 'Experimental product page', 'Admin.Advparameters.Feature', 'This page benefits from increased performance and includes new features such as a new combination management system. Please note this is a work in progress and some features are not available yet.', 'Admin.Advparameters.Help');
```
`label_wording` and `description_wording` are `varchar(191)`, while the inserted text has 196 chars. The size of the columns should probably be 255.
Additionally, the unique key should not have an automatic name 

      UNIQUE KEY `name` (`name`)

would probably be a better choice.

* PrestaShop version: 1.7.8.0 beta.1
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Thanks for your issue and your PR :rocket: 
Ping @PrestaShop/prestashop-core-developers could someone please reproduce the issue :pray: (it's too technical for me :sweat_smile: )

Thanks in advance :pray:

**Comment by lmeyer1** [comment]
This issue was about 1.7.8.0 *beta*.
Therefore I'm closing it.

**Comment by hibatallahAouadni** [comment]
Thanks @lmeyer1 for your feedback!
