### ISSUE TITLE
[SHARE YOUR THOUGHTS, SURVEY INSIDE] Rename "product combinations" to "product variants"

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#24954]
### Is your feature request related to a problem?

The term **product combination** is used only in Prestashop, nowhere else. Most of new merchants are very confused by this term and I have to explain that these are product variations. On all other ecommerce systems, different variants of product are called **product variants**.

**Websites using "variant terminology:**
- https://www.facebook.com/business/help/2256580051262113?id=725943027795860
- https://help.shopify.com/en/manual/products/variants
- https://docs.woocommerce.com/document/variable-product/
- https://support.ecwid.com/hc/en-us/articles/207100299-Product-variations

**Websites using "combination" terminology:**
- None, only PrestaShop

### Describe the solution you'd like

Rename **combination** to **variant** everywhere.

__________________________

In order to get merchants' thoughts on this topic, I (@Julievrz) created a quick survey that is available here: **https://forms-prestashop.typeform.com/to/lgX5aZea**

This survey will help us know how the word "combination" is understood by merchants, and what is their opinion regarding the idea of replacing "combination" with "variation".

If you are reading this and you are a merchant using PrestaShop, feel free to complete this survey and share it with merchants in your network. 🙏

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by Julievrz** [comment]
Good afternoon @Hlavtox and thank you for your suggestion. 

I personally agree that at first, "combination" can be unclear. However, this wording has been used in the back office for some time now and I wouldn't want users to be confused by this change in wording. 

**In order to get merchants' thoughts on this topic, I created a quick survey that is available here: https://forms-prestashop.typeform.com/to/lgX5aZea**

This survey will help us know how the word "combination" is understood by merchants, and what is their opinion regarding the idea of replacing "combination" with "variation".

If you are reading this and you are a merchant using PrestaShop, feel free to complete this survey and share it with merchants in your network. 🙏

**Comment by Julievrz** [comment]
Thank you for your patience!

Based on the survey and some discussions within the Product Team, it was decided to keep the current wording for now. The word "combinations" is widely used in the PrestaShop ecosystem: a change could have confused merchants, or been interpreted as a new feature. However, the survey revealed that the user documentation was not very clear in explaining how the combinations work. So, for the time being, we plan to improve the user documentation, as well as the help texts/tooltips around this feature. However, it is not excluded to change the name of the feature if the way it works evolves in a future version.

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thanks @Julievrz for your hard working :rocket: 
So, I close the issue but we can reopen it in the future.

Thanks for understanding :pray:
