### ISSUE TITLE
BO Order "print order" layout broken

### ISSUE THREAD

**Issue by tswfi** [PrestaShop/PrestaShop#24955]
#### Describe the bug

In BO printing and order produces document that is basically unusable.

The layout should be styled to better suite printing.

#### Expected behavior

Nice readable order information from "print order" button

#### Steps to Reproduce

1. Go to BO orders, open one order
2. Click on 'Print order'
3. Look at the print preview

![image](https://user-images.githubusercontent.com/1352132/121886665-57c25a80-cd1e-11eb-9e55-c2ff8de4678c.png)

![image](https://user-images.githubusercontent.com/1352132/121886685-614bc280-cd1e-11eb-9db5-6909ed1c55ad.png)

#### Additional information

Other option (and perhaps a very valid one) is to remove the button completely...

* PrestaShop version: 1.7.7.2
* PHP version: N/A

**Comment by tswfi** [comment]
should probably be added to https://github.com/PrestaShop/PrestaShop/issues/13822

**Comment by hibatallahAouadni** [comment]
Hello @tswfi 

The product table has been fixed on develop, see the attached pdf below:

[Order #8 DMCVQPZKZ.pdf](https://github.com/PrestaShop/PrestaShop/files/6648072/Order.8.DMCVQPZKZ.pdf)

If you have proposition how we can improve the layout, please share it :pray: 
Please check the **print order** layout on develop branch and feedback.

Thanks!

**Comment by florine2623** [comment]
Hello @tswfi ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
