### ISSUE TITLE
BO - Categories - A new category created is not displayed in the list

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#24964]
#### Describe the bug

In the BO > Catalog > Categories page, when we create a new category, it is not displayed in the list

#### Steps to Reproduce

1. Go to BO > Catalog > Categories page
2. Create a new category
3. Set required fields and save
4. See the error, the number of categories is NOK, and the new category created is not displayed in the list

This regression is detected by [nightly](https://nightly.prestashop.com/report/1692)

**Screenshots**
In the list of categories, we have only demo categories
![image](https://user-images.githubusercontent.com/16067358/122011546-7ecf6980-cdbc-11eb-9693-222a8e76aaca.png)
But we have all these categories
![image](https://user-images.githubusercontent.com/16067358/122011629-973f8400-cdbc-11eb-8c49-d83f80889a17.png)

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by kpodemski** [comment]
Regression is coming from this PR: https://github.com/PrestaShop/PrestaShop/pull/23515

It's all right only when we have categories with products, not newly created.

I'll ping @PululuK - first thought is a wrong joining `category_product` to `category`
