### ISSUE TITLE
Status messages can be confusing

### ISSUE THREAD

**Issue by threed-factory-store** [PrestaShop/PrestaShop#24967]
#### Describe the bug

Status messages use a "conf" parameter on the url.  Using inter-page communication in this way leads to confusing scenarios:

- If a user saves a new item and goes back to a list page, the list page will display a green "success" message because of the conf= parameter on the url.  If the user closes the message then refreshes the page, the message appears again.  

- If a user saves a new item and goes back to a list page then chooses to add a new item but cancels that page instead of saving the new item, they will again see the "success" message because the default cancel button on a HelperForm does a window.history.back().  The message re-appears even if they had closed it on the list page before going to the edit page.

#### Expected behavior
- Different status messages should have different lifetimes.
    - An error or fatal message should exist until I close it.  I asked you to do something and you couldn't do it, I need to see that message even if I walk away from the keyboard and come back tomorrow.  Or even if I was fast and navigated to another PrestaShop page before I could read the error message.
    - Warning messages can disappear by themselves after a short time.  I have no idea what these messages would be, but I thought I should allow for them.
    - Success messages should not exist at all.  They're just noise.  If I told you to do something, I'll assume you did it unless you tell me otherwise.  That's a good bot.
- Once closed, messages should not reappear.

#### Steps to Reproduce

I think I described the bug pretty well.

#### Additional information

One possibility to fix this would be to use cookies (or session variables, etc) with various lifetimes.  Each status message would get its own cookie value with a certain lifetime.  All PrestaShop web pages would show messages based on the existence of these cookies.   The lifetime of a message would correspond to the lifetime of the cookie associated with it.  If the user manually closes a message, the app could also delete that message's cookie so if the user refreshes a page after a message has been closed, the message won't reappear.

* PrestaShop version: 1.7
* PHP version: 7.3?  7.4?

**Comment by hibatallahAouadni** [comment]
Hello @threed-factory-store 

I didn't manage to reproduce the issue with PS1.7.7.4. Could you please provide a screen record and your PrestaShop version?
Please check and feedback.

Thanks!

**Comment by threed-factory-store** [comment]
Did you use a HelperForm?   Maybe this only applies to the example code I started from.

Edit:  Although the conf= parameter I think comes from HelperForm.

**Comment by hibatallahAouadni** [comment]
Hello @threed-factory-store 

I really need clear and concise steps to reproduce, and your PrestaShop version to help reproducing the issue.
So, please provide all these infos :pray: 

Thanks!

**Comment by threed-factory-store** [comment]
Chalk this one up to a PrestaShop noob using poor quality code from the Internet.

**Comment by matks** [comment]
Thread locked because it does not respect the Code of Conduct https://github.com/PrestaShop/PrestaShop/blob/178f65ce831608ac929ffc5cb6edc699d748115a/CODE_OF_CONDUCT.md
