### ISSUE TITLE
support for the process manager

### ISSUE THREAD

**Issue by eveneme** [PrestaShop/PrestaShop#24976]
support for the process manager PHP FPM.

**Comment by matks** [comment]
Hello @eveneme as far as we know PrestaShop works correctly whether you run it using PHP-FPM or mod_php (for Apache). Nginx is also supported.

If you want to submit a bug when using PrestaShop and PHP-FPM please use the template https://github.com/PrestaShop/PrestaShop/issues/new?assignees=&labels=&template=1_bug_report.md and provide accurate reproducible steps
