### ISSUE TITLE
not supported  process manager PHP FPM

### ISSUE THREAD

**Issue by eveneme** [PrestaShop/PrestaShop#24977]
**Describe the bug**

prestashop not supported  process manager PHP FPM.. crashes error 500. i need to refresh the page several times to make it work. This happens when installing the auto update plugin, cleaning the cache, etc.  Please take a look at this problem and fix it! 

**Steps to reproduce**

1. Go to PA -> PERFORMANCE 
2. Click on CLEAR CACHE
3. See error 505

Another bug:

1. Go to PA -> AUTO UPDATE 
2. Click on CONFIGURATION 
3. See error 505

**Screenshot:**
https://zapodaj.net/images/2110b79c9f21c.png
https://zapodaj.net/images/49f06b5d09ad3.png

**Additionnal infos**
* PrestaShop version: 1.7.7.5
* PHP version: 7.2, 7.3

**Comment by eveneme** [comment]
Screen https://zapodaj.net/images/49f06b5d09ad3.png

**Comment by matks** [comment]
Hello again @eveneme we really need you to provide a series of accurate reproducible steps like

Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

Without this, your bug report cannot be explored. PrestaShop works with PHP FPM. It does not work for your environment and shop, so we need the steps to reproduce your environment.

If you need help with your shop or third-party modules, you can have a look at PrestaShop Company’s support plans https://www.prestashop.com/support

**Comment by eveneme** [comment]
done

**Comment by Hlavtox** [comment]
Hi @eveneme, the error 500 does not explain anything. Open config/defines.inc.php and change define('_PS_MODE_DEV_', false); to define('_PS_MODE_DEV_', true);.

Then go to these pages in backoffice again and it will display more meaningful messages. Post them here.

**Comment by kpodemski** [comment]
No change required, I talked to @eveneme error is on 1.7.7, but it's not on 1.7.8, it was related to cache clearing from the Performance tab, it has been fixed in 1.7.8 👍

**Comment by hibatallahAouadni** [comment]
Hello @eveneme 

> This happens when installing the auto update plugin

You mean the autoupgrade module ?

![image](https://user-images.githubusercontent.com/23308427/122189037-ddfeae00-ce90-11eb-8112-53fb9f8ff823.png)

Well, I cleared my cache and there's no problem, see the attached screen record below:

https://drive.google.com/file/d/1HQytPMGRgaC1mFZzBpkUKde4bm-rVV9d/view

PS: Thanks guys for your quick replies :rocket: 

So, I close the issue :wink: 
Thanks!
