### ISSUE TITLE
In dev mode, an Exception in a hook must not be ignored silently

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#24984]
#### Describe the bug

While developing a module, I noticed, that Exceptions thrown in certain hooks are completely ignored. In this cas the hook configuration just has no effect. `displayProductExtraContent` is one of the hooks that swallows exceptions.

#### Expected behavior

I expect in dev mode to be notified when Exceptions occur. Otherwise, debugging is very difficult.
In production mode, exceptions in hook must be swallowed though to keep backwards compatibility, because we can expect existing modules with bugs in hook, that were hidden due to hook swallowing exceptions.

#### Steps to Reproduce

1. Add `throw new Exception('Test');` in the `displayProductExtraContent` hook of a module.
2. Notice, that this Exception has no effect in dev mode when displaying a product page.

#### Additional information

I discussed this issue on slack with @tswfi and @jolelievre.

* PrestaShop version: 1.7.7.x, 1.7.8.x
* PHP version: any

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Could you please check the attached screen record below:

https://drive.google.com/file/d/1A5xcLVWt9S0p43YlHTPZr5lUHcQTPYxo/view

Please check and feedback.
Thanks!

**Comment by lmeyer1** [comment]
@hibatallahAouadni
Thanks. I'm impressed by the means you employ to examine the issues 👍 

I see that the Exception is echoed in your case. I suppose that the QA module you are using is responsible for displaying and that this is not the case when executing the code directly from the module.

Unfortunately I can only speculate on the difference between the two, since I have no access to your power module. 

I know for sure that 1.7.7.4 in dev mode is not behaving like yours. @tswfi noticed too, that exceptions are swallowed in hooks, at least in certain cases.

**Comment by hibatallahAouadni** [comment]
@lmeyer1 here's the module https://github.com/PrestaShop/ps_qualityassurance
It's a native module to test the hooks, you can try it :wink:

**Comment by lmeyer1** [comment]
Thanks @hibatallahAouadni
As I suspected, the module is responsible to display the error message.

In `ps_qualityassurance/ps_qualityassurance.php` lines 114 to 124:

    try {
        $output = eval($payload['content']);
        $this->recordHookCall($hookName, $params, $output);
    
        return $output;
    } catch (Throwable $e) {
        $output = $e->getMessage();
        $this->recordHookCall($hookName, $params, $output, true);
    
        echo $output;
    }

The exception is `catch`ed and the error message is `echo`ed by the module ps_qualityassurance.
When executing the hook directly from a module, eventual exceptions are catched and logged to ps_log, but they are never displayed as symfony exceptions (see `src/Adapter/HookManager.php` lines 78 to 83.

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

As discussed with you on Slack, let's wait for @jolelievre approval. In the meantime, if you could provide a test module, it will be perfect :pray: 

Thanks for being so humble.
