### ISSUE TITLE
PS 1.7.7.4 Suddenly the web site stopped working in the creation of clients and orders.

### ISSUE THREAD

**Issue by lilianamc** [PrestaShop/PrestaShop#24992]
#### Describe the bug

I have my new store https://dulceencanto.com/ in PS 1.7.7.4, I received some orders without problems and suddenly the web site stopped working in the creation of clients and orders.

#### Steps to Reproduce

Please watch the following videos

https://www.awesomescreenshot.com/video/4156853?key=63d59274b32ca4695e2bc5cd22065789

https://www.awesomescreenshot.com/video/4157997?key=0718168f8eaa202ca6321a4664608690

#### Additional information

You need to clean the cookies after the issue to see the website again

* PrestaShop version: 1.7.7.4
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @lilianamc 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have
questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
