### ISSUE TITLE
Improve my account links in footer

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#24999]
### Is your feature request related to a problem?

Links are the same for logged in customer and a guest. The guest should could have a nice link to track his order, log in or register instead.

### Before

![current](https://user-images.githubusercontent.com/6097524/122390978-d31c4a00-cf72-11eb-8c85-0f31ee8b73d0.JPG)

### After, logged in

![after_logged](https://user-images.githubusercontent.com/6097524/122390984-d57ea400-cf72-11eb-92f2-d4b72e6dd493.JPG)

### After, logged out

![after_notlogged](https://user-images.githubusercontent.com/6097524/122390993-d7e0fe00-cf72-11eb-9e30-fcdba9bd875a.JPG)

### PRs
Module - https://github.com/PrestaShop/ps_customeraccountlinks/pull/34
Theme - https://github.com/PrestaShop/PrestaShop/pull/25064

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

PS: I like the idea, cause if I'm logged out and I can't access to these links, why we need it?

Thank you
