### ISSUE TITLE
Login to Addons from Modules Manager BO page: cannot login if I signed on addons.prestashop.com using SSO

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#25009]
#### Is your feature request related to a problem?

In Modules Manager BO page, there is a button to login using Addons account.

![Capture d’écran 2021-06-17 à 18 08 15](https://user-images.githubusercontent.com/3830050/122434038-0a045700-cf97-11eb-8c4f-ca0a3624f1fd.png)

If you click on it you can sign-in your Addons account if you input your login and password

![Capture d’écran 2021-06-17 à 18 08 19](https://user-images.githubusercontent.com/3830050/122434289-40da6d00-cf97-11eb-9524-bc3c6d9e0797.png)

However I signed on addons.prestashop.com using Google SSO. I have no password, when I login on addons.prestashop.com I choose "Connect with Google" login system

![Capture d’écran 2021-06-17 à 18 09 25](https://user-images.githubusercontent.com/3830050/122434222-31f3ba80-cf97-11eb-8e9a-454a7c729d20.png)

So I cannot login on my BO.

#### Describe the solution you'd like

Add the option to connect using Google SSO from BO

**Comment by florine2623** [comment]
Hello @matks ,

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 

Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know!

Thank you

**Comment by marionf** [comment]
With the split, the feature to connect to the marketplace will be removed from the BO, so I close this issue.
