### ISSUE TITLE
Prestashop Official Stripe Module - iphone payment error

### ISSUE THREAD

**Issue by akscell** [PrestaShop/PrestaShop#25005]
#### Describe the bug

I recently observed that a number of my customers who are using iphones and paying via stripe, are either getting error messages or blank screens. I've contacted Stripe whom told me to contact Prestashop instead as the module was programmed on Prestashop's end?  

#### Expected behavior

I would like the Stripe module to function well without hiccups in future. I've customers who accidentally paid twice as they resubmitted the entire order again due to the error message seen or the blank screen with no confirmation.

#### Steps to Reproduce

Error message: https://www.screencast.com/t/Z15XpCng5rt 

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @akscell 

It seems everything right to me, I didn't have any blank screen nor error message, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/122431697-f952e180-cf94-11eb-9515-524704b3b9d6.png)

May be it's your theme, did you try to switch to classic theme?
Please check and feedback.

Thanks!

**Comment by akscell** [comment]
> Hello @akscell
> 
> It seems everything right to me, I didn't have any blank screen nor error message, see the attached screenshot below:
> 
> ![image](https://user-images.githubusercontent.com/23308427/122431697-f952e180-cf94-11eb-9515-524704b3b9d6.png)
> 
> May be it's your theme, did you try to switch to classic theme?
> Please check and feedback.
> 
> Thanks!

Hi Hibattallah, 

many thanks for your reply! Was this done on www.norskenskincare.com ? The issue I am facing is on this page itself unfortunately.

**Comment by florine2623** [comment]
Hello @akscell ,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by akscell** [comment]
Hi there,

Thank you but I was referred to this page via Maissa from Prestashop support.
Is there no way to contact the developers of the Stripe payment module?

Thank you.

**Comment by matks** [comment]
> I recently observed that a number of my customers who are using iphones and paying via stripe, are either getting error messages or blank screens. I've contacted Stripe whom told me to contact Prestashop instead as the module was programmed on Prestashop's end?
There might have been a little mistake in how this bug from PrestaShop company support 😅  .

When you use a payment module for PrestaShop, there are 3 entities involved:
- the company that provides the payment system - Stripe
- the entity that handles the open source project - us the PrestaShop project
- the company that builds the module which connects PrestaShop to Stripe: it can be a freelancer, a PrestaShop agency, sometimes it's PrestaShop company modules team

Depending on the source of the issue you are likely to contact one of the three. In this situation as far as we know you need to reach out to the company that builds the module which connects PrestaShop to Stripe.

**You should be able to contact the people who build the module via your addons.prestashop.com account.**

**Comment by akscell** [comment]
Thank you so much Mathieu!
