### ISSUE TITLE
Product comments [ERROR 500]

### ISSUE THREAD

**Issue by jwojda** [PrestaShop/PrestaShop#25000]
#### Describe the bug

I install Product Comments 4.0.0 on Prestashop 1.7.6.5 but when i tried to configure the module : Error 500.

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.3.19-1

**Comment by hibatallahAouadni** [comment]
Hello @jwojda 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
