### ISSUE TITLE
Links to prestashop.com and addons.prestashop.com in BO profile window

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#25008]
#### Is your feature request related to a problem?

If you click on top right user profile icon it opens a window. In this window are many links to www.prestashop.com and addons.prestashop.com that must be removed in the Open source Split project.

![Capture d’écran 2021-06-17 à 17 59 55](https://user-images.githubusercontent.com/3830050/122433034-1fc54c80-cf96-11eb-92d8-17c11798c24b.png)

#### Describe the solution you'd like

Open source distribution should have no links to prestashop.com and addons.prestashop.com . Maybe a link to prestashop project website instead ❤️ 

The Core should provide a way for custom distributions to inject such links, to enable Corporate distribution to have the links.

**Comment by eternoendless** [comment]
@PierreRambaud we'll probably need to make sure that modules can add links there

**Comment by Progi1984** [comment]
@PierreRambaud Can I take it ?

**Comment by PierreRambaud** [comment]
Yes, hooks have to be added :+1:
