### ISSUE TITLE
Improper use of `defined` to check for a constant 

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#25002]
#### Describe the bug

`defined(_CONSTANT_)` is wrong. Quotes are not optional.

    var_dump(defined('_CONSTANT_'));  // false
    var_dump(defined(_CONSTANT_));  // false
    define('_CONSTANT_', true);
    var_dump(defined('_CONSTANT_'));  // true
    var_dump(defined(_CONSTANT_));  // false (INCORRECT)
    // Warning:  Use of undefined constant _CONSTANT_ - assumed '_CONSTANT_' (this will throw an Error in a future version of PHP)

#### Expected behavior

The PHP function `defined()` should always be used with quotes when testing for a literal constant.

#### Additional information

This error occurs 6 times in `Prestashop/Prestashop`, and once in `Prestashop/pagesnotfound`.
Two occurrences in `Prestashop/Prestashop` fixed in #24985
Four occurrences in `Prestashop/Prestashop` fixed in #25003 
Occurrence in `Prestashop/pagesnotfound` fixed in https://github.com/PrestaShop/pagesnotfound/pull/15#issue-672656650

* PrestaShop version: develop
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

I think you forget the steps to reproduce the issue :sweat_smile: or we need a developer to confirm the issue?
If so, @PrestaShop/prestashop-core-developers wdyt?

**Comment by lmeyer1** [comment]
No, I didn't forget the steps. I intentionally left them out.
Yes, have @PrestaShop/prestashop-core-developers take a look.
