### ISSUE TITLE
DbQueryCore does not support subquery in from function

### ISSUE THREAD

**Issue by shogo54** [PrestaShop/PrestaShop#25010]
#### Is your feature request related to a problem?

PHP version: 7.3.28 
Server: Linux CentOS 8
Engine: Apache/2.4.37 
Prestashop version: 1.7.7.3 

When creating a query using DbQueryCore, it does not allow to have a subquery in from clauses. Of course, it is possible to write a complicated query without a query builder, but it is better to write with a builder for readability and reusability. 

Or is there any better way to achieve this? If so I'd like to know! 

here is a simplified example:
```
$child_query = new DbQuery();
$child_query->select('*');
$child_query->from('product', 'p');
$child_query->where('p.active = 1');

$main_query = new DbQuery();
$main_query->select('*');
$main_query->from($child_query->build(), 'p');
$main_query->where('p.visibility in ("both", "search")');
```
when running this query, I got a sql error because the from() function always add _DB_PREFIX_ (by default, ps_ ) in front of the table name. Also, the query needs a starting and ending parenthesis to wrap the value in the from clause.

#### Describe the solution you'd like

add a new function (nestedFrom() or something) that can take a subquery as a parameter. 

#### Alternatives you've considered

Not using a DbQuery. Or is there any better way to do this? 

#### Additional context

If any more details are needed, please let me know.

**Comment by florine2623** [comment]
ping @PrestaShop/prestashop-core-developers 

Could you take a look at @shogo54 's question ?

Thanks!

**Comment by PierreRambaud** [comment]
You are right, it's not possible right now, but will be if #25037 is merged :)

**Comment by shogo54** [comment]
Fantastic! Thank you for such a quick response!
