### ISSUE TITLE
Translation bug

### ISSUE THREAD

**Issue by AlionaxAlionax** [PrestaShop/PrestaShop#25018]
#### Describe the bug

In prestashop 1.7.7.2, translation seems not working properly. When we put our text in translation fonction : l s='   ', he is not sended for translation in Backoffice. 

#### Expected behavior

We would like to be able to translate the text from our new code from the backoffice, like in 1.6. 

#### Additional information

* PrestaShop version: 1.7.7.2

Thanks

**Comment by matks** [comment]
@AlionaxAlionax hello, I think you will need to provide a lot more details 😉  because this is too broad. I have an example working right here with `l s=' '`

The best would be a sample module or PHP file.

**Comment by AlionaxAlionax** [comment]
Hi, 

We send you an attached file who discibes the problem more clearly. 

Thank you for your help
[Here what we have in red.docx](https://github.com/PrestaShop/PrestaShop/files/6676199/Here.what.we.have.in.red.docx)

**Comment by florine2623** [comment]
Hello @AlionaxAlionax ,
Could you follow the bug template + share the steps to reproduce, so we can reproduce it on our end ?
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @florine2623 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
