### ISSUE TITLE
bogue in the section product

### ISSUE THREAD

**Issue by derick930** [PrestaShop/PrestaShop#25022]
#### Describe the bug

it is about a bug which mixes and superimposes the texts and displays all the selections in the drop-down menus. We also noticed a display bug.

#### Expected behavior

1. Go to category
2. Click on product
3. Scroll down and see error

![Capture d’écran 2021-06-18 135335](https://user-images.githubusercontent.com/86100614/122543293-ae8ca480-d03c-11eb-9853-f9b1e3df46d4.png)
![Capture d’écran 2021-06-18 135200](https://user-images.githubusercontent.com/86100614/122543302-b0eefe80-d03c-11eb-9cf4-60db220ac214.png)

* PrestaShop version: N/A
* PHP version: N/A

**Comment by florine2623** [comment]
Hello @derick930 ,

Can you make sure you are using the right version of PHP for your PrestaShop version ?
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

PHP 7.2 max for 1.7.6.8.

Thanks!

**Comment by derick930** [comment]
Hello @florine2623,

 

Thank you for your answer , the version of my prestashop page is 1.7.6.8 but don’t know what is the PHP version but we have many bug in my back officce , i send you in attachment the screenshot for more details. Thank you for your attention.

 

 

 

De : florine2623 ***@***.*** 
Envoyé : vendredi 18 juin 2021 16:07
À : PrestaShop/PrestaShop ***@***.***>
Cc : derick930 ***@***.***>; Mention ***@***.***>
Objet : Re: [PrestaShop/PrestaShop] bogue in the section product (#25022)

 

Hello @derick930 <https://github.com/derick930>  ,

Can you make sure you are using the right version of PHP for your PrestaShop version ?
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

PHP 7.2 max for 1.7.6.8.

Thanks!
