### ISSUE TITLE
Multistore : orders created on one store end up in the other one BO/FO

### ISSUE THREAD

**Issue by agnesdennetiere** [PrestaShop/PrestaShop#25020]
Hello, 

this bug appears on a prestashop 1.7.7.1 with 2 stores, in the same group, with "share customers" and "share orders" disabled. Only "share quantities" is enabled.

The merchant has had a problem for some weeks: when they create an order in one shop, sometimes the prices of products added to cart are prices of the other store. If they create the order anyway : the order is created in the wrong store. So an order is created for one shop with a customer from another shop...

But yesterday they realized that an order from the front office, created on the store 2, was created in the store 1 (with a customer from store 2).
The payment module was "payement by check".

I could not reproduce this bug myself...

Do you have any idea where this could come from?

Thanks a lot

**Comment by agnesdennetiere** [comment]
I forgot to mention that this website is a migration from a prestashop 1.6, where there was only one store.
We migrated the customer data, and then for customers in 1.6 which were in a specific group, we changed the id of the shop in the database of the prestashop 1.7.

**Comment by agnesdennetiere** [comment]
We also changed the id_shop of the orders of theses customers, but not the id_shop of the carts of these customers... Maybe this is the problem.
I just did the request in the database, we will see if the problem happens again

**Comment by florine2623** [comment]
Hello @agnesdennetiere ,

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
