### ISSUE TITLE
Remove marketplace links and ads in the installer

### ISSUE THREAD

**Issue by PierreRambaud** [PrestaShop/PrestaShop#25028]
#### Is your feature request related to a problem?

We have to remove these elements for the open source project.

![image](https://user-images.githubusercontent.com/1462701/122564627-e0563900-d045-11eb-9b20-97a186aa1003.png)
![image](https://user-images.githubusercontent.com/1462701/122564733-fa901700-d045-11eb-9378-0a5b585ce07f.png)
![image](https://user-images.githubusercontent.com/1462701/122564762-04b21580-d046-11eb-839c-d5ab628a9875.png)

#### Describe the solution you'd like

We have to make it configurable, by adding templates loaders if they are defined.

**Comment by MatShir** [comment]
Hi @ttoine, 
Could you help us to identify what's need to be removed exactly?

**Comment by ttoine** [comment]
The copyright does not change until there is an other organisation that ship this distribution of PrestaShop.

However, elements that are linked to prestashop.com or its APIs will be removed in the open source version available on GitHub (marketing, module suggestions, Addons, paid plans, ...) They must be replaces by links to content like Build, DevDocs and user doc, GitHub, etc. And something like "PrestaShop is open source, your contributions are welcome would be great in the footer, with a link to some resources.

The question is who is in charge, inside the company, to build the distribution for prestashop.com, that will put back the elements in place?

**Comment by MatShir** [comment]
I guess ! When the company will be ready, they could customize the installer. @PierreRambaud what are your thoughts ?

**Comment by MatShir** [comment]
Thanks for the input @ttoine, I suggest:
- replacing "Forum" and "Support" for "I need help" with the link from the devdoc (https://devdocs.prestashop.com/1.7/faq/i-need-help/).
- Adding, "Project's Blog" with the link of the build blog.

We need to make sure to use the official link of the user documentation of the project and replace prestashop.com by the official website of the project.

Maybe @Julievrz have others ideas ? :)
@ttoine @PierreRambaud? WDYT?

**Comment by Julievrz** [comment]
> Thanks for the input @ttoine, I suggest:
> 
> * replacing "Forum" and "Support" for "I need help" with the link from the devdoc (https://devdocs.prestashop.com/1.7/faq/i-need-help/).
> * Adding, "Project's Blog" with the link of the build blog.
> 
> We need to make sure to use the official link of the user documentation of the project and replace prestashop.com by the official website of the project.
> 
> Maybe @Julievrz have others ideas ? :)
> @ttoine @PierreRambaud? WDYT?

Hi @MatShir 
I suggest keeping only "Help", to avoid using the personal pronoun "I". Also, I wonder whether the link should redirect to the dev docs or the user docs? (http://doc.prestashop.com/display/PS17/Installing+PrestaShop) 

For the second wording, maybe we could only keep "Blog" as it will necessarily be the project's blog since all mentions of the company will have been removed.

Let me know what you think ☺️

**Comment by Progi1984** [comment]
@PierreRambaud Is it implemented in the PrestaShop Corp Distribution ?

**Comment by PierreRambaud** [comment]
> @PierreRambaud Is it implemented in the PrestaShop Corp Distribution ?

A zip is available in the original PR to retrieve previous behavior.
