### ISSUE TITLE
Improvement of customer links in header

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#25024]
#### Is your feature request related to a problem?

When the customer is logged in, we can improve the links in the header. Change a link to a dropdown (like in currency selector) and enable the user to go directly where he wants to. And save space due to moving logout link inside the dropdown.

![before](https://user-images.githubusercontent.com/6097524/122550456-f78c2b00-d033-11eb-8e57-84012d97996a.jpg)

#### Describe the solution you'd like
I have done it on my shops, PR can be ready in minutes.

![after](https://user-images.githubusercontent.com/6097524/122550459-f824c180-d033-11eb-8df9-de80b68fae25.jpg)

Ping @prestascott

**Comment by florine2623** [comment]
Hello @Hlavtox ,

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 

Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know!

Thank you

**Comment by prestascott** [comment]
Hello @Hlavtox,

Thanks for your suggestion. This is a really interesting improvement, merchant's customers will be able to access quickly to their different account pages. 

Wdyt @marionf ? 🤔

**Comment by matks** [comment]
(I like it)

**Comment by marionf** [comment]
Hello @Hlavtox 

It's really good idea :+1: 
We should just define the wording of each menu entry with @Julievrz 
And do not forget to add an entry in the drop-dow for the options that are enabled in the back-office (ex: merchandise returns, credit slips, vouchers) and for the installed modules (ex: gdpr, wishlist, ps_emailalerts)

**Comment by Julievrz** [comment]
Hi @Hlavtox @marionf 

For more consistency, maybe the best option is to keep the labels that appear in the FO? Wdyt?

- Information
- Addresses
- Order history and details
- Credit slips
- My wishlists
- GDPR - Personal data

**Comment by Hlavtox** [comment]
@marionf @Julievrz Good to hear :-) I kept the strings that are used in "My account" zone in FO. I think we should keep them the same, the customer does not see the BO... 😉

**Comment by Julievrz** [comment]
> @marionf @Julievrz Good to hear :-) I kept the strings that are used in "My account" zone in FO. I think we should keep them the same, the customer does not see the BO... 😉

I meant the FO, sorry ! 😄

**Comment by Hlavtox** [comment]
@Julievrz Now I understand 😄 

I used the same strings as in **ps_customeraccountlinks** in footer, so no new stuff.
I prepared something here: https://github.com/PrestaShop/ps_customersignin/pull/38

It's working for returns and vouchers. If I adapt the syntax to be the same as in footer, we can use the same hook **displayMyAccountBlock** to display module's links.

**Comment by Hlavtox** [comment]
I have it ready, but there is a small catch. 

![122799188-b741dc80-d2c1-11eb-9eb2-772f8f6a9c00](https://user-images.githubusercontent.com/6097524/122830626-e3bd1f00-d2e8-11eb-93a1-47908020c106.jpg)

The bottom list uses
`<li><a href="#" title="My wishlists" rel="nofollow">Wishlist</a></li>`
But dropdown syntax needs
`<li><a href="#" title="My wishlists" rel="nofollow" class="dropdown-item">Wishlist</a></li>`
             
**Solutions:**
- Omit this hook in the top list       
- Somehow style every item that comes there to behave properly
- Make a second hook called displayMyAccountHeader
- Somehow inject dropdown-item class in the template

Ping @matks @NeOMakinG HELP

**Comment by matks** [comment]
@Hlavtox in current implementation, items of this list come from `getWidgetVariables()` of module Customers Signin ?

**Comment by Hlavtox** [comment]
@matks Yes, I copied the functionality from ps_customeraccountlinks.

**See module PR:** https://github.com/PrestaShop/ps_customersignin/pull/38.
**My classic theme implementation currently looks like this:** [ps_customersignin.tpl.txt](https://github.com/PrestaShop/PrestaShop/files/6692209/ps_customersignin.tpl.txt)

**Comment by matks** [comment]
OK I finally found out that `displayMyAccountBlock` (current hook being used) aims to display a 'My Account' block (Classic Theme displays it in footer)

I see that `renderWidget($hookName, array $configuration)` accepts a `$hookName` argument so maybe we could reuse the hook `displayMyAccountBlock` BUT style it differently as you mention, so we have the needed class on items being rendered?

That being said 😅  I'm confused by something. You say

> The bottom list uses
> `<li><a href="#" title="My wishlists" rel="nofollow">Wishlist</a></li>`
> But dropdown syntax needs
> `<li><a href="#" title="My wishlists" rel="nofollow" class="dropdown-item">Wishlist</a></li>`

So I quite think the issue is with the items in the bottom list. So what do you suggest to omit the hook in the top list? Why modify the top list would fix the bottom list?

**Comment by Hlavtox** [comment]
@matks OK I will try to clarify. 😄

In **ps_customeraccountlinks** module (hooked in the footer) there is a hook called **displayMyAccountBlock**. Other modules (Wishlist, Mailalerts, GDPR) can hook into it and display additional links in the list. They output code in following format `<li><a href="#" title="My wishlists" rel="nofollow">Wishlist</a></li>`.

Now, if I wanted to add the same hook to my header dropdown list in **ps_customersignin** module, I have a problem, because I need to have `class="dropdown-item"` in the link.

### So, what do we do:

- Do not put any hook to the dropdown.
- Somehow style every item that comes there to behave properly, even without `class="dropdown-item"`.
- Make a second hook called for example **displayMyAccountHeader**.
- Somehow automatically insert dropdown-item class in the link that comes there.

**Comment by matks** [comment]
> @matks OK I will try to clarify. 😄
> 
> In **ps_customeraccountlinks** module (hooked in the footer) there is a hook called **displayMyAccountBlock**. Other modules (Wishlist, Mailalerts, GDPR) can hook into it and display additional links in the list. They output code in following format `<li><a href="#" title="My wishlists" rel="nofollow">Wishlist</a></li>`.

Haha 😄  that is tricky because this template is then being rendered inside `renderWidget()` which is, if I am not wrong, hooked as a widget to `displayFooter` in Classic Theme
```
      displayFooter:
        - ps_linklist
        - ps_customeraccountlinks
        - ps_contactinfo
```

So it means we have a hook triggered in a hook

<img width=50% src="https://w7.pngwing.com/pngs/783/577/png-transparent-leonardo-dicaprio-inception-meme-shrek-film-series-cover-version-leonardo-dicaprio-celebrities-face-head.png">

**Comment by matks** [comment]
> ### So, what do we do:
> 1. Do not put any hook to the dropdown.
> 2. Somehow style every item that comes there to behave properly, even without `class="dropdown-item"`.
> 3. Make a second hook called for example **displayMyAccountHeader**.
> 4. Somehow automatically insert dropdown-item class in the link that comes there.

Option 1 => we lost links to wishlist or GDPR 😭  let's avoid it if we can
Option 2 => if we can find some smart CSS that can do the job, it's great ! using JavaScript we could force to add the class but it sounds a bit tricky => code smell
Option 3 => good solution but when we release next version as it will be a new hook no module will use it, so impact limited (then we'll need to do a GDPR release and a Wishlist release to start using it and we'll hope people follow the example)
Option 4 => can be done using regexp but sounds like a dirty workaround

Haha 😅  many options, none seems "the best". Wdyt @kpodemski ?

**Comment by kpodemski** [comment]
@matks 

In my opinion, if it's an improvement, Option 3 seems like the best idea, other solutions are just dirty workarounds like you said.

**Comment by Hlavtox** [comment]
@matks @kpodemski What if we make a completely new hook called something like hookMyAccount.

This single hook would accept array with link, name and icon. We could use this hook in footer, header, my account section, jist everywhere.

**Comment by kpodemski** [comment]
@Hlavtox 

yeah that makes a lot of sense because we then have all the control over the front-office part

**Comment by Hlavtox** [comment]
@kpodemski @matks This is being implemented in theme refacto. Try to think about the myaccount hook, maybe we can implement it into 8.0. 

https://github.com/Hlavtox/theme-refacto/blob/header/modules/ps_customersignin/ps_customersignin.tpl

**Comment by NeOMakinG** [comment]
@Hlavtox We did it on hummingbird, I guess we can close this issue as we will avoid to add BC to classic
