### ISSUE TITLE
Sanity tests randomly failing because unable to download modules from addons

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#25031]
#### Describe the bug

We have multiple CI 'sanity' runs failing because it is unable to download modules from Addons

```
  1) Install Prestashop
       should installation step 'Install addons modules' be finished:

      Fail to finish the step Install addons modules
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (campaigns/sanity/01_installShop/01_installShop.js:205:89)
```

![Capture d’écran 2021-06-18 à 15 26 27](https://user-images.githubusercontent.com/3830050/122568198-cd456800-d049-11eb-9c29-383db4064fb6.png)

#### Expected behavior

CI should be fixed so we don't hinder the pull request process. Also it's not acceptable that our CI fails because of a dependency external to PrestaShop project

#### Steps to Reproduce

See Continuous Integration report from PR https://github.com/PrestaShop/PrestaShop/pull/24983/checks?check_run_id=2858604962

**Comment by matks** [comment]
Issue happening a bit less but still regularly making CI fail for bad reason (1.7.8.x and 1.7.7.x like https://github.com/PrestaShop/PrestaShop/pull/25102)

**Comment by marionf** [comment]
This issue isn't related to the open-source project and the maintainer's team can't fix it

**Comment by matks** [comment]
FYI
- ps_facebook removed from API Push
- Travis timeout increased https://github.com/PrestaShop/PrestaShop/pull/25281
