### ISSUE TITLE
it is not possible to change the title of a pdf

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#25036]
Hi

#### Describe the bug
It is not possible to change the text of "INVOICE" at the top of a invoice pdf
into pdf/header.tpl
it is presente
`{if isset($header)}{$header|escape:'html':'UTF-8'|upper}{/if}`

I need to replace "Invoice" with "Product list" because the pdf it is used just to show the product list and not like an invoice

I try to replace it with this code, to have the possibility to translate it from the normal translation system

`{l s='Maofree Method' d='Shop.Pdf' pdf='true'}`

but this text doesn't appear from the translation page

#### Expected behavior
it is only necessary to get the possibility to translate the voice

#### Steps to Reproduce
try to replace into pdf/header.tpl
`{if isset($header)}{$header|escape:'html':'UTF-8'|upper}{/if}`
with
`{l s='Maofree Method' d='Shop.Pdf' pdf='true'}`

bye

**Screenshots**
![1](https://user-images.githubusercontent.com/653230/122576918-827c1e00-d052-11eb-8688-d2f739632b38.png)

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: 7.3

**Comment by florine2623** [comment]
Hello @maofree ,

This is more an improvement - add the possibility to translate PDF title "INVOICE".
Thank you for your suggestion. The Product Team will take it into consideration for future developments. 

Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know!

Thank you

**Comment by Maofree** [comment]
Hi
I've seen that it is possible to do that from the classic theme into PDF section
https://www.prestashop.com/forums/topic/985429-solved-pdf-invoice-field-translation/

but the changes made on the Shop.Pdf text are not get from translation system

**Comment by Maofree** [comment]
to fix this last point, it is necessary to change the text from the english language

I close this ticket
thanks for the support

bye
