### ISSUE TITLE
Remove code related to Gamification module

### ISSUE THREAD

**Issue by PierreRambaud** [PrestaShop/PrestaShop#25033]
#### Is your feature request related to a problem?

![image](https://user-images.githubusercontent.com/1462701/122570715-4e056380-d04c-11eb-9fb9-80a0b693469a.png)

#### Describe the solution you'd like

Just remove code related to it :sweat_smile:

**Comment by matks** [comment]
For context: https://github.com/PrestaShop/gamification

**Comment by Progi1984** [comment]
@matks :warning: The project is managed by PrestaShopCorp teams : https://github.com/PrestaShopCorp/gamification

**Comment by Progi1984** [comment]
Issue created in the repo : PrestaShopCorp/gamification#92
