### ISSUE TITLE
1.7.5 - Category tree links bug

### ISSUE THREAD

**Issue by thbl** [PrestaShop/PrestaShop#25043]
after updating to 1.7.5 {$currentCategory} always returns 2 in 
modules/ps_categorytree/views/templates/hook/ps_categorytree.tpl

**Comment by hibatallahAouadni** [comment]
Hello @thbl 


Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
