### ISSUE TITLE
[BO - responsive] - Create an Order page

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#25040]
#### Describe the bug

This page is not responsive

#### Expected behavior

The page should be responsive

#### Steps to Reproduce

1. On mobile
2. **BO** > **SELL** > **Orders** > **Orders**
3. Click on **Add new Order**
4. See errors => all columns are squized

**Screenshots**

![image](https://user-images.githubusercontent.com/23308427/122567805-5dcf7880-d049-11eb-8b59-1784e989473e.png)

![image](https://user-images.githubusercontent.com/23308427/122569987-9a03d880-d04b-11eb-807c-b84194694557.png)

![image](https://user-images.githubusercontent.com/23308427/122609586-87ef5d80-d07e-11eb-985e-2b471320d557.png)

![image](https://user-images.githubusercontent.com/23308427/122609609-92115c00-d07e-11eb-8a76-fa202db8520b.png)

#### Additional information

* PrestaShop version: 1.7.8.x
* PHP version: 7.2

**Comment by Hlavtox** [comment]
Will be fixed by https://github.com/PrestaShop/PrestaShop/pull/25056
