### ISSUE TITLE
Missing deleteds attributes names in product stats module 

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#25049]
## Describe the bug

Missing deleteds attributes names in product stats module 

![Capture d’écran de 2021-06-21 10-27-33](https://user-images.githubusercontent.com/16455155/122731488-a66e7800-d27b-11eb-895a-177e6ab13c98.png)

## Expected behavior

Attribute names should still be displayed in stats even when they have been deleted.

![Capture d’écran de 2021-06-21 10-31-28](https://user-images.githubusercontent.com/16455155/122731947-0cf39600-d27c-11eb-9d1e-e955698bbf81.png)

## Steps to Reproduce

1. Create a product **X** with combinations
2. Order the product
3. Delete the combinations previously created, and generate others.
4. Go to *Bo > Stats > Product stats*
5. Select the product **X**.
6. See the error : Combination name is null in dashboard graph (see the screen in description)

## Proposition

Use the product name present in the order details. See https://github.com/PrestaShop/statsproduct/pull/23

## Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by florine2623** [comment]
Hello @PululuK ,

I was able to reproduce the issue with PrestaShop version 1.7.7.x, so I can confirm that this behavior is indeed a bug.

Thank you

**Comment by hibatallahAouadni** [comment]
Ping @florine2623 could you please check if it's a regression or not?

**Comment by PululuK** [comment]
Fixed by https://github.com/PrestaShop/statsproduct/pull/23
