### ISSUE TITLE
Order feature by position then id_feature_value in productForm V2

### ISSUE THREAD

**Issue by e-gaulue** [PrestaShop/PrestaShop#25053]
#### Describe the bug

In Prestashop we can order feature for displaying. But when we set those features on the product form, we don't get this order.

#### Expected behavior

Display and edit feature in the order define for the feature. When a feature is set several times, order in the same order they were created (ie. in the id_feature_value order).

#### Steps to Reproduce

1. Go to a product with features form
2. Take a screenshot
3. Go to the feature form
4. Change the order of your features
5. Go back to your product form
6. Check if feature order has changed

#### Additional information

* PrestaShop version: 1.7.8.0-beta.1
* PHP version: 7.3

**Comment by florine2623** [comment]
Hello @e-gaulue ,

I think this is more an improvement than a bug. You want the features to change order in the product page when they're modified in Attributes pages, is that right ?

I changed the Paper Type Attributes in alphabetical order :
![Screenshot 2021-06-22 at 10 35 34](https://user-images.githubusercontent.com/16019289/122893025-38db4e00-d346-11eb-9e39-7980358120f5.png)

**I went back to my Product Page, Combination tab** :
![Screenshot 2021-06-22 at 10 41 45](https://user-images.githubusercontent.com/16019289/122893300-8061da00-d346-11eb-8f52-40354ce0be7e.png)

**Product Page, Combination tab V2** : 
![Screenshot 2021-06-22 at 10 41 34](https://user-images.githubusercontent.com/16019289/122893312-82c43400-d346-11eb-9437-b2b081b6cb34.png)

In both cases the order hasn't changed.
Please check and feedback
Thanks!

**Comment by e-gaulue** [comment]
It's about the same but concerning features.

You can order them on this screen:
![Capture d’écran 2021-06-23 à 15 15 27](https://user-images.githubusercontent.com/4291874/123103000-e1b4a680-d435-11eb-89a5-2acc5ba69e0b.png)

But this order is not respected if you go to the product form in the feature section.
![Capture d’écran 2021-06-23 à 15 13 43](https://user-images.githubusercontent.com/4291874/123102836-bdf16080-d435-11eb-91a4-2d2e042ee10d.png)

Of course it can't be rendered this way while creating them, but once created, we hope to see them in this order.

Note that the PR improve this on product form V2 form only.

**Comment by florine2623** [comment]
Thank you for your suggestion. The Product Team will take it into consideration for future developments. 

Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know!

Thank you
