### ISSUE TITLE
No slug rewrite when category or CMS rename

### ISSUE THREAD

**Issue by PierM80** [PrestaShop/PrestaShop#25065]
#### Is your feature request related to a problem?

In SEO, it is essential to never change URLs. On Prestashop, the category name or CMS page name is linked with the slug. This is a very big problem in SEO because many merchants can change the name of their categories/CMS, without knowing the impact on the URL. During my audits, in the history of the site, I regularly see URL changes, mostly on categories but also on CMS pages, only because of this feature. Sometimes even merchants who are aware of this issue do not pay attention. This has important negative impacts on search engine rankings.

Currently, after a category rename-CMS page/URL rewrite, a 301 redirect is set up automatically, but this is also impactful. It is important that the URL is never modified (or modified only if considered). And some merchants will repeatedly change the name of certain categories/CMS pages, which will result in multiple redirects.

#### Describe the solution you'd like

No link at all between category name/CMS page name and category rewrite, or after the rewrite was first written.

**Comment by matks** [comment]
I am very bad in SEO but I think this is being adressed by some workarounds 🤔 

ping @marionf @kpodemski @jf-viguier @prestarocket who I think have SEO advanced skills :)

**Comment by jf-viguier** [comment]
I must have guys

**Comment by jf-viguier** [comment]
No need for workaround @matks : prestashop should't force change the slug on category name change, just like product page.
Il the marchant wants to change the slug, it still can manually.

**Comment by matks** [comment]
> No need for workaround @matks : prestashop should't force change the slug on category name change, just like product page.

That, I agree.

One thing might be useful, when the slug changes, add a warning for merchant "Warning! you are modifying the category slug which means the URL will change and this has SEO impact. Are you sure?"

or would it be overkill ?

**Comment by jf-viguier** [comment]
IMO it's overkill for most merchant because it's actually a minor impact but @PierM80 could tell you more on this.

**Comment by PierM80** [comment]
The message will be a first step/an improvement. The ideal would be to reproduce the behavior of the product page like @jf-viguier write. When the category/CMS page is created, the slug is created, then it does not change afterwards when the name is changed. If you add a message, it should be under the category/CMS name field. 

But this means that the merchant, when he wants to change the name of the category/CMS page, must save the slug on the side, change the name of the category/CMS page, then put the slug back. This is what the merchants I work with do, but it's not so obvious in the heat of the moment or depending on who is doing the editing.

**Comment by PierM80** [comment]
Also, many merchants use third party catalog management tools (Store Commander...). The message will not be present on these tools.

**Comment by jf-viguier** [comment]
@PierM80 the issue is also in CMS page, could you update your issue to include it ?

**Comment by hibatallahAouadni** [comment]
Hello @PierM80 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by jf-viguier** [comment]
done here https://github.com/PrestaShop/PrestaShop/pull/25075
