### ISSUE TITLE
Canada Eco-Tax Need Improvements - Each Provinces have their own Eco-Tax Rates

### ISSUE THREAD

**Issue by 8ternity** [PrestaShop/PrestaShop#25061]
In Canada, each province have their own Eco-Tax amount. Like Provinces taxes "CA Standard Rate", eco-tax need to have their own amount for each provinces. Since the version 1.7, no solution has been discuss regarding that problem.

The eco-tax must be displayed has shop by default, but when a order is process, the amount of the eco-tax need to be updated for the one match the province (for Guess user).

If its a register user, the eco-tax must be diplayed has the default delivery address.

See the program recycling here
[https://www.recyclemyelectronics.ca/]

**Comment by florine2623** [comment]
Hello @8ternity ,

Could you follow the template for 'Feature Request' please ?
The product team will take a look at your suggestion.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @8ternity 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by 8ternity** [comment]
@florine2623 Any template somewhere for Feature Request?

**Comment by matks** [comment]
@8ternity here we go :) https://github.com/PrestaShop/PrestaShop/issues/new?assignees=&labels=&template=2_feature_request.md
