### ISSUE TITLE
Prestashop forms are using incorrent syntax and overflow out of containers

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#25063]
#### Describe the bug

Syntax of forms must be corrected. See provided screenshots.

- On mobile, forms are leaking from their containers due to extra css class.
- Two rows without column between them.
- Extra card-text producing extra level of render. If padding is to be set to forms, it should be done via card-block.
- Form labels have wrong class, and due to that, they are not aligned to center. They should have `col-form-label`.
- Prestashop switches are not aligned vertically to center, margin-top must be adjusted. They are wrongly wrapped in `input-group` class.

**Screenshots**
![forms](https://user-images.githubusercontent.com/6097524/122774906-e5b3bd80-d2a9-11eb-9d98-8e3d85ff1fad.png)
![Výstřižek](https://user-images.githubusercontent.com/6097524/122775932-ed279680-d2aa-11eb-8c56-1a91d37e3c62.JPG)

#### Additional information
* PrestaShop version: develop
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

I reproduced the issue with PS1767, PS1775 and PS178x but I think it's kind of an improvement.
Let's check with the developer Team :wink: 

Ping @PrestaShop/prestashop-core-developers or @NeOMakinG should we treat this issue as an improvement or as a bug?

**Comment by NeOMakinG** [comment]
I think as it's working without any fix, we should consider it as an improvement

**Comment by hibatallahAouadni** [comment]
Thanks @NeOMakinG 

@Hlavtox could you please create a PR to fix the issue :pray: 
Waiting for your PR :wink:

**Comment by Progi1984** [comment]
@Hlavtox Is this issue completly fixed ?

**Comment by Hlavtox** [comment]
@Progi1984 nearly, one small issue left, but I will open separate issue for this ;)

**Comment by Progi1984** [comment]
Thanks @Hlavtox ;)
