### ISSUE TITLE
Error when proceed to checkout

### ISSUE THREAD

**Issue by nancyfsdesign** [PrestaShop/PrestaShop#25070]
#### About the problem

I have the version 1.7.7.0 of prestashop and I tried this in the last versions too. When I add one product to the basket and then I try to proceed to checkout it give's to me the next error:

`Uncaught Error: Call to undefined method Cart::checkAllProductsAreStillAvailableInThisState() in /public_html/classes/checkout/CheckoutPaymentStep.php:48`

#### Steps to Reproduce

1. Version PS 1.7.7.0 
2. One product with quantity and minimum of 1 to be sell.
3. Add to the basket
4. Proceed to checkout
5. Blank page

#### Log of the error

```
[21-Jun-2021 23:22:10 Europe/Madrid] PHP Fatal error:  Uncaught Error: Call to undefined method Cart::checkAllProductsAreStillAvailableInThisState() in /public_html/classes/checkout/CheckoutPaymentStep.php:48
Stack trace:
#0 /public_html/classes/checkout/CheckoutProcess.php(59): CheckoutPaymentStepCore->handleRequest(Array)
#1 /public_html/controllers/front/OrderController.php(278): CheckoutProcessCore->handleRequest(Array)
#2 /public_html/classes/controller/Controller.php(306): OrderControllerCore->initContent()
#3 /public_html/classes/Dispatcher.php(518): ControllerCore->run()
#4 /public_html/index.php(28): DispatcherCore->dispatch()
#5 {main}
  thrown in /public_html/classes/checkout/CheckoutPaymentStep.php on line 48
```

**Comment by florine2623** [comment]
Hello @nancyfsdesign ,

I can't reproduce your issue. It seems like it is a support request. please check my screen record :
https://drive.google.com/file/d/1CFkbC2hQAEfSQodpplJRp5ClbfnR3Em2/view

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by nancyfsdesign** [comment]
Hello @florine2623 ,

thanks for your answer and video. The solution has been to comment certain lines of code that did some verification at cart.

In case it was useful to other users, I leave the solution below:
Classes > Checkout > CheckoutPaymentStep.php

```
public function handleRequest(array $requestParams = [])
    {
        $cart = $this->getCheckoutSession()->getCart();
        $allProductsInStock = $cart->isAllProductsInStock();
        //$allProductsExist = $cart->checkAllProductsAreStillAvailableInThisState(); /* Comment this line */
        //$allProductsHaveMinimalQuantity = $cart->checkAllProductsHaveMinimalQuantities(); /* Comment this line */

        // if ($allProductsInStock !== true || $allProductsExist !== true || $allProductsHaveMinimalQuantity !== true) /* Comment this line */
        if ($allProductsInStock !== true){
            $cartShowUrl = $this->context->link->getPageLink(
                'cart',
                null,
                $this->context->language->id,
                [
                    'action' => 'show',
                ],
                false,
                null,
                false
            );
            Tools::redirect($cartShowUrl);
        }

        if (isset($requestParams['select_payment_option'])) {
            $this->selected_payment_option = $requestParams['select_payment_option'];
        }

        $this->setTitle(
            $this->getTranslator()->trans(
                'Payment',
                [],
                'Shop.Theme.Checkout'
            )
        );
    }

```

Not sure why happens this to my install or prestashop project... But this solution it works.
