### ISSUE TITLE
Image Gallery

### ISSUE THREAD

**Issue by harryajc** [PrestaShop/PrestaShop#25076]
#### Is your feature request related to a problem?

To save space allow pictures used within one item to be reused without having to reupload the same image multiple times.

#### Describe the solution you'd like

A media section within the admin dashboard that allows a admin to see all images uploaded to the platform.

These can then be selected within the product pages rather than reuploading to each product.

**Comment by florine2623** [comment]
Hello @Goldshop ,

Your improvement request is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/12773
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Goldshop 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #12773. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #12773
