### ISSUE TITLE
PDF invoice download in guest account not possible

### ISSUE THREAD

**Issue by miba65** [PrestaShop/PrestaShop#25086]
#### Describe the bug

If the customer orders a guest, they will receive a confirmation email. in this email it has a link to a guest account
The PDF invoice is available for download in this guest account.
when click for download it don't donload the PDF invoice. therefor there is a redirect to customer account login.

#### Expected behavior

when in the guest account click the link to download the PDF invoice, just download the PDF invoice.

#### Steps to Reproduce

1. Make an order as a guest, and go to confirmation email
2. Scroll down, click on the 'guest_tracking_url'
3. login in guest account with order number and email address
4. Click on the donload link for PDF invoice and See error

**Screenshots**

![PDF Rechnung Gastkonto](https://user-images.githubusercontent.com/59774189/122953005-ab682000-d37e-11eb-91b5-9b05263cb8d4.jpg)

#### Additional information

* PrestaShop version: 1.7.7.4 and 1.7.7.5
* PHP version: 7.3 FCGI

**Comment by florine2623** [comment]
Hello,
In my guest tracking page, I don't have the same info as you :
![Screenshot 2021-06-22 at 17 53 25](https://user-images.githubusercontent.com/16019289/122958026-c6d52a00-d382-11eb-92d9-fb70fbe70d80.png)

Am I missing something ?
Please check and feedback.
Thanks!

**Comment by miba65** [comment]
I can see the status of the order "awaiting bank wire payment" in your screenshot. 
You have to enable "Allow a customer to download and view PDF versions of his/her invoices." for this status
in the settings under settings / order / status.

**Comment by florine2623** [comment]
Thank you !
It has been fixed for PrestaShop 1.7.8.0, as you can see from this issue : https://github.com/PrestaShop/PrestaShop/issues/9650

So I close your issue !
Thanks!

**Comment by miba65** [comment]
Hello and thanks
I have reinstalled version 1.7.7.5. Version 1.7.8.0 is not available. how can I fix this bug in my instalation which file do I have to change or replace.
and where can I get this file from?
best regards

**Comment by florine2623** [comment]
Duplicate of #9650

**Comment by florine2623** [comment]
@miba65 
This is the file that has been changed : https://github.com/PrestaShop/PrestaShop/pull/20616/files

**Comment by miba65** [comment]
@florine2623 Thank you very much for your help, I was able to fix it
