### ISSUE TITLE
Provide new order buttons to customer page

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#25093]
#### What can we do
We can provide additional links for merchants to create manual order from customer detail page, and speed up their work a bit.
The plus icon is already used on address section on the page.

We can link to the page normally for the beginning, and possibly improve it in the future by preselecting the customer on order screen.

#### If the customer does not have any orders
![orders_empty](https://user-images.githubusercontent.com/6097524/122992817-d9615a80-d3a6-11eb-8e70-63f605bd62f5.JPG)

#### If customer already has some orders
![orders_some](https://user-images.githubusercontent.com/6097524/122992831-dc5c4b00-d3a6-11eb-9f03-31382d9bbeca.JPG)

**Comment by florine2623** [comment]
Hello @Hlavtox ,

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 

Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know!

Thank you
