### ISSUE TITLE
Product type menu drop down doesn´t work

### ISSUE THREAD

**Issue by leo1altamirano** [PrestaShop/PrestaShop#25099]
#### Describe the bug

The problem persists in the back end when I´m trying to modify or update my products. The drop down doesn´t function anymore, it´s just text display on the page. 

#### Expected behavior

Catalog > Products > Product drop down > select between: Pack, Virtual or Physical Product
Each click would take you to the relevant product

Explain what you expected to happen instead.

Nothing happens, when trying to click, no drop down exists, just text, it´s broken

#### Steps to Reproduce

Catalog > Products > Product drop down > select between: Pack, Virtual or Physical Product
Each click would take you to the relevant product

1. Go to 'Catalog'
2. Click on 'products.'
3. Top right hand drop down to choose products doesn´t drop down and just shows plain text
4. 1. Troubleshooting 
Tried google chrome and safari both on mac and PC 
Inspected page and checked:

Checked elements 
#form > div.product-header.col-md-12

value was 0 - the drop down element doesn´t exist, error in prestashop code for this value

Checked network to see if response exists when clicking on the drop dowm and 0 resposnse,
Tested other elements of the page and elicited response 

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7
<img width="1363" alt="screenshot google chrome mac inspect elements" src="https://user-images.githubusercontent.com/86357967/123096206-22f58800-d42f-11eb-8efc-2d76c09308cc.png">
<img width="1373" alt="screenshot google chrome mac inspect elements 2" src="https://user-images.githubusercontent.com/86357967/123096210-2426b500-d42f-11eb-8c99-3eb8c72200b2.png">

* PHP version: 1.7.6.4
![google chrome screenshot inspect elements](https://user-images.githubusercontent.com/86357967/123096633-98f9ef00-d42f-11eb-8e61-2f468fce4f0f.png)

**Comment by florine2623** [comment]
Hello @leo1altamirano ,

Please make sure you are using the right version of PHP for your PrestaShop version :
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

I can't reproduce your issue :
<img width="929" alt="Screenshot 2021-06-23 at 15 15 35" src="https://user-images.githubusercontent.com/16019289/123103107-fbee8480-d435-11eb-9fa0-02d35e24a593.png">
Thanks!
