### ISSUE TITLE
Backoffice left side navigation Menu not getting displayed

### ISSUE THREAD

**Issue by amol-beast** [PrestaShop/PrestaShop#25090]
![image](https://user-images.githubusercontent.com/3284767/122980404-37496e80-d3b6-11eb-88bd-1ed50ca22c09.png)
Hi,
After upgrading to 1.7.7.5, the back office navigation menu is not showing.
I tried searching for this issue, couldn't found the solution to it.
Any pointers will be greatly appreciated

PHP version is php 7.3

**Comment by amol-beast** [comment]
Workaround:- I was able to fix the issue by doing a code edit

I had to add code in file  classes/Tab.php
304 if (is_array($result)) {
305                 foreach ($result as &$row) {
306                     if (!isset(self::$_cache_tabs[$idLang][$row['id_parent']])) {
307                         self::$_cache_tabs[$idLang][$row['id_parent']] = [];
308                     }
309 ++                    $row["enabled"] = $row["active"];
310                     self::$_cache_tabs[$idLang][$row['id_parent']][] = $row;
311                 }
312             }
?
Any idea why this issue is being triggered in the first place?

**Comment by florine2623** [comment]
Hello @amol-beast ,

Please refer to this comment : https://github.com/PrestaShop/PrestaShop/issues/23166#issuecomment-783184675

Thanks!
