### ISSUE TITLE
Predefined messages in order not in correct language?

### ISSUE THREAD

**Issue by Catharinaboer** [PrestaShop/PrestaShop#25094]
Dear sirs,
I recently updated my prestashop to the 1.7.7.3 version. In my order page I always use the predefined order messages. Since the update, the correct language is not showing. See a screenshot of a Belgium customer. The predefined message language should be Dutch. I can only see english. See screenshot. I have fully configured all languages so this cannot be any issue. I hope you have a solution for this?

<img width="1792" alt="Schermafbeelding 2021-06-22 om 22 36 48" src="https://user-images.githubusercontent.com/60729070/122996142-ca7ca700-d3aa-11eb-96b2-f17190ecd382.png">

**Comment by florine2623** [comment]
Hello @Catharinaboer ,

Please check your BO language.
Click on the top right icon > Click on "Your Profile" > Scroll down to change your language to Dutch

Thanks!
