### ISSUE TITLE
Provide new voucher buttons to customer page

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#25092]
#### What can we do
We can provide additional links for merchants to create voucher from customer detail page, and speed up their work a bit.
The plus icon is already used on address section on the page.

We can link to the page normally for the beginning, and possibly improve it in the future by preselecting the customer on voucher screen.

#### If the customer does not have any vouchers
![vouchers](https://user-images.githubusercontent.com/6097524/122992559-88e9fd00-d3a6-11eb-8d04-a2ceb4327514.JPG)

#### If customer already has some vouchers
![vouchers_some](https://user-images.githubusercontent.com/6097524/122992584-90110b00-d3a6-11eb-918f-7191d1d1718d.JPG)

**Comment by florine2623** [comment]
Hello @Hlavtox ,

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 

Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know!

Thank you
