### ISSUE TITLE
[FO -RTL] - the arrows direction are wrong (in the opposite way)

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#25097]
#### Describe the bug

In FO with RTL, the arrows direction are wrong (in the opposite way)

#### Expected behavior

Should be in the right way like 1.7.7.5

#### Steps to Reproduce

1. Go to FO
2. See error > the banner's arrows are in the opposite was => regression
3. Scroll down to **All products**
4. See error > the arrow in the opposite way => regression
5. the wishlist icon should be in the left (this is a bug and not regression)

**Screenshots**

![image](https://user-images.githubusercontent.com/23308427/123088718-60a1e300-d426-11eb-8774-2f3d6db15be4.png)

#### Additional information

* PrestaShop version: 1.7.8.x
* PHP version: 7.2

**Comment by NeOMakinG** [comment]
second PR for blockwishlist problem

https://github.com/PrestaShop/blockwishlist/pull/124

**Comment by Progi1984** [comment]
Fixed by @NeOMakinG in #25101
