### ISSUE TITLE
Add placeholders in product settings page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#25105]
#### Is your feature request related to a problem?

To help the users better fill the stock labels and the delivery times fields, we should add a placeholder for each field of the product settings page

#### Describe the solution you'd like

Add the following placeholders:

- Label of in-stock products: "In stock" in Admin.Shopparameters.Help
- Label of out-of-stock products with allowed backorders: "On backorder" in Admin.Shopparameters.Help
- Label of out-of-stock products with denied backorders: "Out of stock"  in Admin.Shopparameters.Help
- Delivery time of in-stock products: "Delivered within 3-4 days"  in Admin.Shopparameters.Help
- Delivery time of out-of-stock products with allowed backorders: "Delivered within 5-7 days"  in Admin.Shopparameters.Help

**Comment by Gauravkain** [comment]
Hello, I want to contribute.

**Comment by marionf** [comment]
Hello @Gauravkain 

That's great to hear :+1: 
You can make your pull request on the develop branch: https://github.com/PrestaShop/PrestaShop/tree/develop
Let me know if you have any question :)

Thank you!

**Comment by Gauravkain** [comment]
@marionf okay 👍

**Comment by Gauravkain** [comment]
Hi @marionf 
where i can find this error #25105 ?

**Comment by marionf** [comment]
Sorry @Gauravkain I don't understand your question :thinking:

**Comment by Gauravkain** [comment]
> Sorry @Gauravkain I don't understand your question :thinking: 

In which file I have to add placeholder

**Comment by marionf** [comment]
I don't know I am not a developer :sweat_smile: 
Let's ask to @PrestaShop/prestashop-core-developers
