### ISSUE TITLE
UX-FE : Menu bar on dashboard covers text so fields become unreadable or uneditable

### ISSUE THREAD

**Issue by leo1altamirano** [PrestaShop/PrestaShop#25100]
#### Describe the bug
 On the main dashboard and product page, even when the dark grey menu bar is collapsed, the text in main grey space is unreadable on the left hand side and uneditable

#### Expected behavior
 When collapsing the grey menu bar, or having it open, you should be able to see all the text on the main page

#### Steps to Reproduce

1. Go to 'Catalog'
2. Click on 'Products.' - Click on any product
3. Text is not visible on left hand side (screenshots highlighted)
4. Troubleshooted on Mac and PC and chrome and safari 
5. Also changed page size from 100 percent to 75 and also 50% problem still persists, so not page size issue
![google chrome zoomed out](https://user-images.githubusercontent.com/86357967/123097409-6a304880-d430-11eb-8ddb-10101d40e5c1.png)
![screenshot google chrome](https://user-images.githubusercontent.com/86357967/123097412-6b617580-d430-11eb-86a9-a7169574a1da.png)
![screenshot google chrome text unreadable](https://user-images.githubusercontent.com/86357967/123097800-c4310e00-d430-11eb-8707-bb3496c7b9e0.png)

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by leo1altamirano** [comment]
Prestashop version 1.7
1.7.6.4. PHP

**Comment by florine2623** [comment]
Hello @leo1altamirano ,

Please check your PHP version :
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
<img width="721" alt="Screenshot 2021-06-23 at 15 17 57" src="https://user-images.githubusercontent.com/16019289/123103352-32c49a80-d436-11eb-8113-86cefe82d3eb.png">
You need to use PHP 7.2.

Thanks!
