### ISSUE TITLE
Error in comment limit for the description of a product

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#25103]
#### Describe the bug

The limit comment for the description of a product is bad the charset is utf8mb4 not utf8 and type text

https://dev.mysql.com/doc/refman/8.0/en/storage-requirements.html

#### Expected behavior

Change the limit ? Remove / Change the comment ? 

#### Steps to Reproduce

Generate a text with 64k characters increases the limit and try to update the description

See the line 

https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Form/Admin/Type/FormattedTextareaType.php#L41-L44

#### Additional information

* PrestaShop version: 178 / Dev
* PHP version: 7.4

**Comment by florine2623** [comment]
Hello @okom3pom ,

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 

Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know!

Thank you

**Comment by ghost** [comment]
Hello @florine2623 when the Dev and the PM answer I will make a PR

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers wdyt? Should we remove the comment or change the limit?

**Comment by okom3pom** [comment]
i say a mistake :)

**Comment by kpodemski** [comment]
I'm closing this issue in favor of https://github.com/PrestaShop/PrestaShop/issues/27782
