### ISSUE TITLE
Services in front container are not available once the container is cached

### ISSUE THREAD

**Issue by atomiix** [PrestaShop/PrestaShop#25112]
#### Describe the bug

If you try to access one of the following service:
- `configuration`
- `context`
- `db`
- `shop`
- `employee`
from the front container when the cache is empty, the first time you try to access it, it will work, but not the second time when the cache is created.

#### Expected behavior

Services should be always available

#### Steps to Reproduce

1. Clear the cache `rm -rf var/cache/*`
2. Open `controllers/front/IndexController.php` and add the following lines in the `initContent()` function:
```php
$container = ContainerBuilder::getContainer('front', true);
$entityManager = $container->get('shop');
```
3. Open your browser and try to access the front office of your shop
4. No error
5. Refresh
6. See error

#### Additional information

* PrestaShop version: 1.7.6.9, 1.7.7.x, 1.7.8.x, develop
* PHP version: N/A

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/25111 it seems
