### ISSUE TITLE
Module install fail if there is only 1 position available

### ISSUE THREAD

**Issue by Jeremy-FT** [PrestaShop/PrestaShop#25113]
#### Describe the bug

Module install fail if there is only 1 position available

#### Expected behavior

Module install work even if there is only 1 position available

#### Steps to Reproduce

1. Make a clean install
2. Remove all modules
3. Install a new one 
4. Module doesn't install

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.3

PR : https://github.com/PrestaShop/PrestaShop/pull/25110

**Comment by florine2623** [comment]
Hello @Jeremy-FT ,

I couldn't reproduce your issue using PS 1.7.7.5.

I installed a new shop in 1.7.7.5
went to _modules_ folder and deleted everything
went to BO and installed a module
Here's my result :
<img width="670" alt="Screenshot 2021-06-24 at 10 48 53" src="https://user-images.githubusercontent.com/16019289/123233013-ff3b4c00-d4d9-11eb-844d-568bcb673462.png">

Am I missing something ?
Thanks!

**Comment by Jeremy-FT** [comment]
Well, sorry, I thought it will make no difference but I didn't remove all module.
Here is the exact steps. I kept these modules :

```
contactform
graphnvd3
gridhtml
gsitemap
ps_banner
ps_checkpayment
ps_contactinfo
ps_crossselling
ps_currencyselector
ps_customeraccountlinks
ps_customersignin
ps_customtext
ps_dataprivacy
ps_emailsubscription
ps_imageslider
ps_languageselector
ps_linklist
ps_mainmenu
ps_shoppingcart
ps_wirepayment
statssearch
psgdpr
ps_accounts
blockreassurance
ps_featuredproducts
ps_socialfollow
ps_categorytree
ps_facetedsearch
ps_sharebuttons
```

I removed classic theme, installed classic-rocket theme and the module ps_searchbarjqauto provided by classic-rocket.
I did a mistake with the version presta, it's with presta 1.7.7.4.

The point is that this condition (see PR) should not return false. 

```
if (count($sqlResult) === 1) {
                // if there is only 1 position available, it cannot be updated
                return false;
 }
```

**Comment by Jeremy-FT** [comment]
The problem occur with the 1-click upgrade module

**Comment by florine2623** [comment]
Okay thanks for the details.

You used 1-click upgrade to upgrade from which PS version ?
The steps you shared need to be before or after the upgrade ?

**Comment by Jeremy-FT** [comment]
I didn't do an upgrade. It's a clean 1.7.7.4 install. I wanted to install 1-click upgrade to upgrade to 1.7.7.5 but the install of 1-click upgrade failed.

**Comment by khouloudbelguith** [comment]
Hi @Jeremy-FT,

Thank for these clarifications.
In my case, I followed these steps with PS1774
1. Install the module `ps_searchbarjqauto`
2. Install the [classic_rocket](https://github.com/prestarocket-agence/classic-rocket) theme and use it.
3. Remove the classic theme
4. I have the list of these modules
`autoupgrade
contactform
graphnvd3
gridhtml
gsitemap
index.php
ps_banner
ps_checkpayment
ps_contactinfo
ps_crossselling
ps_currencyselector
ps_customeraccountlinks
ps_customersignin
ps_customtext
ps_dataprivacy
ps_featuredproducts
psgdpr
ps_imageslider
ps_languageselector
ps_linklist
ps_mainmenu
ps_searchbarjqauto
ps_shoppingcart`

I installed the 1-click upgrade => ok

I attached a screen record
https://drive.google.com/file/d/1hytZhKA0ggAieYCRsM8R7xeu8Y_5g57n/view?usp=sharing

Thanks to check and feedback.

**Comment by Jeremy-FT** [comment]
Well, I don't see anything to add to help you reproduce the bug.
The point is still that this condition should not return false. The module install should not fail if there is only 1 position available
```
if (count($sqlResult) === 1) {
                // if there is only 1 position available, it cannot be updated
                return false;
 }
```

**Comment by florine2623** [comment]
Hello @Jeremy-FT 

We can reproduce the issue, so I'll ping the dev team to share their point of view.

Thank you

**Comment by florine2623** [comment]
Ping @PrestaShop/prestashop-core-developers ,

Should this condition return false ?
```
if (count($sqlResult) === 1) {
                // if there is only 1 position available, it cannot be updated
                return false;
 }
```

Thanks!

**Comment by PierreRambaud** [comment]
> Hello @Jeremy-FT
> 
> We can reproduce the issue, so I'll ping the dev team to share their point of view.
> 
> Thank you

Hey @florine2623 are you sure you're able to reproduce the issue, regarding @khouloudbelguith 's comment, I see no valid scenario :thinking:

**Comment by MatShir** [comment]
Despite our several trials, we could not reproduce your issue with the provided information. If we can't reproduce the issue, we can test the fix. So, I will close this issue. Feel free to open it again if you have more insights, we would be happy to review them :)
