### ISSUE TITLE
When using toggle in Customers listing, whole page is refreshed although only row could be refreshed

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#25114]
#### Describe the bug

When using toggle in Customers listing (3 fields can be toggled: "enabled", "newsletter" and "partner offers"), whole page is refreshed. We could refresh only the row being updated, this makes the user experience better and saves computing resources.

#### Expected behavior

When using toggle in Customers listing (3 fields can be toggled: "enabled", "newsletter" and "partner offers", only the modified row is modified.

This is the behavior implemented on Category listing.

#### Steps to Reproduce

1. Go to BO Customers list
2. Click on one of the fields that can be toggled (see screenshot below)
3. See that after the action has been done, the whole page is refreshed
4. You can compare with BO Category list: go to Category list, click on the field that can be toggled, no full page refresh

**Screenshots**

![Capture d’écran 2021-06-24 à 10 46 40](https://user-images.githubusercontent.com/3830050/123232470-7c19f600-d4d9-11eb-95a3-cb4f9b62ccf6.png)

#### Additional information

* PrestaShop version: develop
* PHP version: N/A

**Comment by florine2623** [comment]
Hello @matks ,

I was able to reproduce the issue with PrestaShop develop, so I can confirm that this behaviour is indeed a bug.

Thank you
