### ISSUE TITLE
Product Page Not Responsive -- Front Office

### ISSUE THREAD

**Issue by diksha-cedcoss** [PrestaShop/PrestaShop#25132]
#### Describe the bug

Once you'll check the responsiveness of the product page is does not work as expected. There is so much extra space, the product should be displayed 2 columns in a row but it is showing only one with lots of spaces, the category is not recognizable

#### Expected behavior

As in previous versions, it displays the category name along with its description & then products in 2 rows with less space in between

#### Steps to Reproduce

1. Go to the 'PS 1.7.8 shop/website'
2. Click on 'Inspect' to enable mobile view
3. Set it to 'Surface Duo' at 100% fit
4. Scroll down to 'Product Lists'

**Screenshots**

[
![product_page_is_not_responsive_1](https://user-images.githubusercontent.com/40261082/123509868-a0223680-d695-11eb-9160-7461a6742ca5.png)
](url)

[
![product_page_not_responsive_2](https://user-images.githubusercontent.com/40261082/123509891-c8119a00-d695-11eb-947c-59aa076aae46.png)
](url)

[
![product_page_not_responsive_3](https://user-images.githubusercontent.com/40261082/123509897-d2cc2f00-d695-11eb-993f-672988a0e58f.png)
](url)

#### Additional information

* PrestaShop version: 1.7.8.0 beta version
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @diksha-cedcoss 

Are you talking about this part:

![image](https://user-images.githubusercontent.com/23308427/123612662-09738800-d803-11eb-83c8-e13417180716.png)

Cause it has been changed since PS1775:

![image](https://user-images.githubusercontent.com/23308427/123613089-6ec77900-d803-11eb-8125-702a0ce67e32.png)

Is that so? Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @diksha-cedcoss 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
