### ISSUE TITLE
FO - classic theme - stores.tpl - business hours name of the days are truncated in other languages

### ISSUE THREAD

**Issue by LyoNick** [PrestaShop/PrestaShop#25138]
#### Describe the bug

FO - classic theme - `our company => stores page` -  business hours name of the days are truncated in other languages
i.e: in HEBREW the name of the days contain two words (has a space)
the 1st part is the translation for the word day, 2nd part is the particular day name like so:

Sunday = `יום ראשון`
Monday = `יום שני`
...
Friday = `יום שלישי`

But in the `our company => stores` page it is truncated showing only the 1st word like so:
Sunday = `יום.`
Monday = `יום.`
...
Friday = `יום.`

#### Expected behavior

show the full translated string
Sunday = `יום ראשון`
Monday = `יום שני`
...
Friday = `יום שלישי`

Explain what you expected to happen instead.

Showing only the 1st part of the string

Sunday = `יום.`
Monday = `יום.`
...
Friday = `יום.`

#### Steps to Reproduce

1. Enable Hebrew language
1. Go to 'BO'
2. set some business hours for the shop
3. Go to FO our store page, in ENG it is fine, in HEBREW it is NOT

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: 7.3
*
### easy fix:
go to PrestaShop/themes/classic/templates/cms/stores.tpl

edit line 59
from:
```
<th>{$day.day|truncate:4:'.'}</th>
```
to:
```
<th>{$day.day}</th>
```

recompile the template
reload the FO `our company => stores`
et walla
you will need to check it dose not break anything - i do not know why the truncate is there anyway

**Comment by NeOMakinG** [comment]
Hey @LyoNick, thanks for the issue reporting.

I wonder why we truncated it, I think it's only because of design, wdyt of having full day name on this part @PrestaShop/ux-team?

**Comment by prestascott** [comment]
Hello everyone,

Thank you for your suggestion @LyoNick!
If the word is truncated and can't be understood, then we need to write the full day name. It's good to me 👍 

Wdyt @Julievrz @marionf? 🤔

**Comment by NeOMakinG** [comment]
It's understable on some languages, but not on others, and we can't condition it as it makes it harder to maintain and could add buggy behaviors, so I would suggest as @LyoNick to display the full day name everywhere

**Comment by Julievrz** [comment]
If it's possible in terms of design, I agree that we should spell out the days of the week. 👍

**Comment by Hlavtox** [comment]
Legit change, made PRs right away:
- https://github.com/PrestaShop/classic-theme/pull/121
- https://github.com/PrestaShop/hummingbird/pull/532
