### ISSUE TITLE
Tax calculation issue when using discount

### ISSUE THREAD

**Issue by Seb33300** [PrestaShop/PrestaShop#25145]
#### Describe the bug

The total tax amount can be incorrect on order with dicount.

![image](https://user-images.githubusercontent.com/915273/123640798-b96ce380-d84b-11eb-9951-f318b7aacc91.png)

#### Expected behavior

On the previous screenshot, total without taxes is `204,98 €` and tax total is `40,99 €`
Tax rate is `20%`

The tax total should be `204,98 * 0.2 = 40,996 = 41,00 €`

Or exact calculation: 
```
(Product 1 price * discount * qty + Product 2 price * discount * qty) * tax rate
```
```
(2.74 * 0.92 * 20 + 3.36 * 0.92 * 50) * 0.2 = 40.9952 = 41,00 €
```

#### Steps to Reproduce

1. Create 2 products : 

- Product 1 : `2,74 €` with tax 20% 
- Product 2 : `3.36 €` with tax 20% 

2. Create a catalog discount : 8% discount on all products

3. Setup the general settings of the shop (see below screenshot): default rounding rule + rounding type on total

4. Order `20 Product 1` and `50 Product 2`

**Screenshots**

![image](https://user-images.githubusercontent.com/915273/123642174-30ef4280-d84d-11eb-87d0-fbf873c34f74.png)

#### Additional information

* PrestaShop version:  1.7.7.4
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @Seb33300 

Could you please check this issue #11492 cause it seems similar to yours.
Please check and feedback.

Thanks!

**Comment by Seb33300** [comment]
Hello @hibatallahAouadni

it looks to be a different issue.
The other issue is related to the display of discount amount.

My issue is related to the calculation of the tax when order has a discount.

Thank you

**Comment by florine2623** [comment]
Hello @Seb33300 ,

We have a lot of issues about Rouding.
So could you check if your issue is in this list, please ? 
https://github.com/PrestaShop/PrestaShop/issues/19445

Thanks!

**Comment by Seb33300** [comment]
None of the issues in this ticket are related to rounding issue when using discount.

Some of them are related to ta rounding that might be related but I cannot be sure.

**Comment by khouloudbelguith** [comment]
Hi @Seb33300,

Thanks for your feedback.
Could you please check my comment: https://github.com/PrestaShop/PrestaShop/issues/9779#issuecomment-415125166
It is a rounding issue related to discounts.

Thanks to check and feedback.

**Comment by florine2623** [comment]
Hello @Seb33300 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
