### ISSUE TITLE
ps_mainmenu Cannot access protected property HelperForm::$fields_form

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#25142]
#### Describe the bug

Cannot access protected property HelperForm::$fields_form

#### Expected behavior

Remove lines

#### Steps to Reproduce

1. Uninstall and Remove the module 
2. Clone the repo use dev branch
3. Launch composer installl
4. Install in you BO
5. Click to configure

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop 177 178
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

You didn't reproduce the issue with the latest version of ps_mainmenu, is that so?
You only reproduce it with dev branch?

Thanks!

**Comment by ghost** [comment]
Yes it's only for the dev branch of the module

**Comment by okom3pom** [comment]
http://okom3pom.com/Pr!vaTe/helper_errors.webm

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

That's weird :confused: I didn't manage to reproduce the issue on **178x** with **dev** branch on **ps_mainmenu**.
Everytime, I clone **ps_mainmenu** project under **modules**, then **checkout** to **dev** branch and launch `composer install`.
Without any error. Did you forget to mention a step?

Please check and feedback.
Thanks!

**Comment by ghost** [comment]
After composer install go to back office and try to install.

Don't forgot to uninstall and remove  the module before clone otherwise it will be cloned in ps_mainmenu_1

PS : i update step to reproduce.

**Comment by hibatallahAouadni** [comment]
> After composer install go to back office and try to install.
Don't forgot to uninstall and remove the module before clone otherwise it will be cloned in ps_mainmenu_1

Yes, I know I already did that :confused:

**Comment by okom3pom** [comment]
I hope this video see you the way 

http://www.okom3pom.com/Pr!vaTe/helpermenu.webm

**Comment by florine2623** [comment]
Hello @okom3pom ,

Thanks for the issue, I managed to reproduce the issue in PS 1.7.8.x and module ps_mainmenu with dev branch.

<img width="1140" alt="Screenshot 2021-06-29 at 10 59 28" src="https://user-images.githubusercontent.com/16019289/123769071-32f6e700-d8c9-11eb-99b3-729f91ff67c6.png">

It is a regression because i didn't reproduce it with ps_mainmenu v2.2.0.

Thanks!

**Comment by ghost** [comment]
Hello @florine2623 && @hibatallahAouadni 

close by https://github.com/PrestaShop/ps_mainmenu/pull/49

Regards Thomas

**Comment by hibatallahAouadni** [comment]
Great to know :tada:
