### ISSUE TITLE
BUG upgrade prestashop

### ISSUE THREAD

**Issue by Tomtomytom** [PrestaShop/PrestaShop#25148]
#### Describe the bug
When I want to upgrade prestashop to 1.7.7.2 to 1.7.7.5 I have an error... 
They said **[INTERNAL] /****/****/www/modules/autoupgrade/classes/ZipAction.php line 111 - ZipArchive::close(): Write error: File too large** 
I changed the folder's permission on 775 and file's permission on 664 but nothing... 
How to fix it and do my upgrade... 
Thanks a lot for helping me
#### Expected behavior

I wanted to upgrade prestashop.

**Comment by florine2623** [comment]
Hello @Tomtomytom ,

Write error: File too large : This error means that you might not have enough space on your server. Please check.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
