### ISSUE TITLE
Merchandise return not work

### ISSUE THREAD

**Issue by abcreationIT** [PrestaShop/PrestaShop#25154]
#### Describe the bug

Customers cannot return merchandise because there is no option

#### Expected behavior

See checkbox in client order product page to return a product

#### Steps to Reproduce

Make an order, check as "Sent" and after check as "Delivered"
Checking the order on front-end as a client I can't see section to return a product.

Documentation says:

> When is it possible to return an order?
> Returns have to be enabled ("Enable returns" option).
> The order has to be in the time of validity (= it is still time to return a product).
> The orders need to have had at least the following statuses:
> At least two statuses: one with the condition "Set the order as paid" enabled and the second one with the option "Set the order as shipped" enabled.
> Or
> One status which has both conditions ("Set the order as paid" and "Set the order as shipped") enabled.
> Statuses can be edited on the "Statuses" tab under the "Orders setting" page of the "Shop parameters" menu.

I'll attach screenshot of my Order Statuses so you can see that I've one status with "Set the order as paid" checked and another one with "Set the order as shipped" checked.

**Screenshots**

<img width="1139" alt="Schermata 2021-06-29 alle 11 49 21" src="https://user-images.githubusercontent.com/33608547/123778125-165ead00-d8d1-11eb-961e-d979c22776ad.png">
<img width="598" alt="Schermata 2021-06-29 alle 11 57 58" src="https://user-images.githubusercontent.com/33608547/123778405-5a51b200-d8d1-11eb-9891-81ab598c9370.png">
<img width="1040" alt="Schermata 2021-06-29 alle 11 51 42" src="https://user-images.githubusercontent.com/33608547/123778144-19599d80-d8d1-11eb-9e48-53156069ccd0.png">
<img width="749" alt="Schermata 2021-06-29 alle 11 51 55" src="https://user-images.githubusercontent.com/33608547/123778159-1c548e00-d8d1-11eb-9a7f-86ef49e99b29.png">
<img width="879" alt="Schermata 2021-06-29 alle 11 52 01" src="https://user-images.githubusercontent.com/33608547/123778168-1f4f7e80-d8d1-11eb-9987-a5292b2454a4.png">
<img width="756" alt="Schermata 2021-06-29 alle 11 52 10" src="https://user-images.githubusercontent.com/33608547/123778177-21194200-d8d1-11eb-8c0b-20f13ca97031.png">
<img width="815" alt="Schermata 2021-06-29 alle 11 52 17" src="https://user-images.githubusercontent.com/33608547/123778351-4d34c300-d8d1-11eb-8cbb-b195f63914dc.png">

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.3.28

**Comment by florine2623** [comment]
Hello @abcreationIT ,

I can't reproduce your issue in PS 1.7.7.4.

<img width="1103" alt="Screenshot 2021-06-29 at 14 16 56" src="https://user-images.githubusercontent.com/16019289/123795843-bb36b580-d8e4-11eb-8a3c-8a9b88978304.png">

So I close your issue.
Thanks!

**Comment by abcreationIT** [comment]
@florine2623 If I'll update, for example, the latest status ("Delivered") checking "Set the order as paid" besides the already present "Set the order as shipped", it work... 

Do you know why?
It's not normal I guess

It seems that in my case PrestaShop wants both ticks in the last state rather than, as written in the documentation:

> At least two statuses: one with the condition "Set the order as paid" enabled and the second one with the option "Set the order as shipped" enabled.


Did you set up the order statuses as I set them? (screenshots)

Thanks

**Comment by abcreationIT** [comment]
@florine2623 or someone else can answer me?
