### ISSUE TITLE
BO / Cart rule category selection : display categories in a hierarchical way

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#25168]
#### Is your feature request related to a problem?

In cart rule page, in product restriction, the categories are displayed in alphabetical order. It can be confusing if 2 categories have the same name but with différents parents. By example Wines > White and Biers > White. Actually you have 2 White categories and no way to figure it out.

#### Describe the solution you'd like

display categories in a hierarchical way :
Wines > White
Biers > White

#### Additional context

![image](https://user-images.githubusercontent.com/16720275/123934814-f17f3e00-d993-11eb-8fc4-1f430bdba648.png)

**Comment by hibatallahAouadni** [comment]
Hello @jf-viguier 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
And thanks for the PR :rocket: 

Thank you

**Comment by jf-viguier** [comment]
@hibatallahAouadni can you remove the TBS label please ?

**Comment by hibatallahAouadni** [comment]
@jf-viguier Done 😉 thanks for the ping 🙏
