### ISSUE TITLE
Logo .svg support

### ISSUE THREAD

**Issue by eveneme** [PrestaShop/PrestaShop#25162]
Please logo svg format support.

**Comment by hibatallahAouadni** [comment]
Hello @eveneme 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have
questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by matks** [comment]
Have a look at https://github.com/PrestaShop/PrestaShop/issues/17673 and https://github.com/PrestaShop/PrestaShop/pull/23959
