### ISSUE TITLE
Cannot search for a product when creating an order manually

### ISSUE THREAD

**Issue by eurya** [PrestaShop/PrestaShop#25166]
#### Describe the bug

In Prestashop BO, I manually create a new order.
When I search for a product, there is an error 500 during the AJAX request.
It happens for specific products only, I don't know the reason.

`GET /shop/admin/index.php/sell/orders/products/search?_token=CtsgdPdI1uvwqj_-MuCbFC-JN93qKzQET9LeEqfgFXo&search_phrase=shirt HTTP/1.1`

```
Oops... looks like an unexpected error occurred.

Type error: Argument 7 passed to PrestaShop\PrestaShop\Core\Domain\Product\QueryResult\ProductCombination::__construct() must be of the type string, null given, called in /home/shop/src/Adapter/Product/QueryHandler/SearchProductsHandler.php on line 282

[Symfony\Component\Debug\Exception\FatalThrowableError 0]
```

#### Expected behavior

The BO should list the product related to the searched term 

**Screenshots**

![prestashop_issue_create_order_ajax_product_search](https://user-images.githubusercontent.com/557322/123926618-56cf3100-d98c-11eb-8fc1-2d15795d428e.png)

-> the search never ends due to the "error 500" during the AJAX request

**How to fix it**

I fixed this issue with the following patch in this file:
**File: ./src/Adapter/Product/QueryHandler/SearchProductsHandler.php**

```
$priceTaxExcluded = $this->getProductPriceForOrder((int) $product->id, $productAttributeId, false, $computingPrecision, $order);
                $priceTaxIncluded = $this->getProductPriceForOrder((int) $product->id, $productAttributeId, true, $computingPrecision, $order);

// patch 
if (is_null($combination['location']))
{ 
         $combination['location'] = "";
}
// end patch

                $productCombination = new ProductCombination(
                    $productAttributeId,
                    $attribute,
                    $combination['quantity'],
                    $this->contextLocale->formatPrice($priceTaxExcluded, $currencyIsoCode),
                    $priceTaxExcluded,
                    $priceTaxIncluded,
                    $combination['location'],
                    $combination['reference']
                );

                $productCombinations[$productCombination->getAttributeCombinationId()] = $productCombination;
```

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @eurya 

I didn't manage to reproduce your issue :confused: 

![image](https://user-images.githubusercontent.com/23308427/123984928-5737ee00-d9c5-11eb-9fa2-3e7d45ccba85.png)

How many products do you have in your store? may be your issue related to some performance issue?
Please check and feedback.

Thanks!

**Comment by eurya** [comment]
We have less than 50 products, that's definitely not a performance issue.
It's probably related to the data migration from PS 1.6 to PS 1.7. 
From the patch I  had to applied, it seems that some products have been imported with their field $combination['location'] set to null.

**Comment by hibatallahAouadni** [comment]
Hello @eurya 

Could you please cite the steps of upgrading your shop? did you encounter any issue while upgrading your shop?
Please check and feedback.

Thanks!

**Comment by eurya** [comment]
Absolutely no issues were encountered, we used this migration module: 
https://addons.prestashop.com/en/data-migration-backup/32298-migration-40-better-upgrade-and-migrate-tool.html

**Comment by khouloudbelguith** [comment]
Hi @eurya,

Thanks for your feedback.
I did not manage to reproduce the issue with PS1775 after an upgrade from PS16124 using the 1-click upgrade module v4.12.0.
I attached a screen record
https://drive.google.com/file/d/1w95xMEIa-zYpCYt50Y0CwiOuAkasJpyl/view?usp=sharing

Thanks to check and feedback.

**Comment by eurya** [comment]
Hi, thanks for taking the time to check this issue.
From my understanding, it comes from the "Migration Module" (from ETS Soft) which set some fields to null instead of an empty string "".

**Comment by hibatallahAouadni** [comment]
Hello @eurya 

> From my understanding, it comes from the "Migration Module" (from ETS Soft) which set some fields to null instead of an empty string "".

It seems that your issue is not a PrestaShop core bug. Please contact your module developer to fix the issue.
We will close this issue.

Thanks!

**Comment by vzlatev** [comment]
I also encountered the problem and can share some feedback in case someone else hit it. Error is slightly different but use case may be similar:

`Type error: Argument 2 passed to PrestaShop\PrestaShop\Core\Domain\Product\QueryResult\ProductCombination::__construct() must be of the type string, null given`

In product_attribute_combination table there were some references to non-existing id_attribute. Solution was simply to check all tables for such non-existing references and clean them. 

```attribute
attribute_impact
attribute_lang
attribute_shop
layered_indexable_attribute_lang_value
layered_product_attribute	
product_attribute_combination 
```
My wild guess is that attribute was used at some point but then it was deleted while there are active product combinations using it. Not sure if this should be possible or it happened in more complex scenario.

**Comment by dorutrip** [comment]
Hi, this saved my day,,,, I was having the exact same problem, this worked like a charm. Thanks!
