### ISSUE TITLE
View order with missing orderstate makes the site crash

### ISSUE THREAD

**Issue by nea-tingstroem-dk** [PrestaShop/PrestaShop#25172]
#### Describe the bug

If a module that has some special orderstates remove these from the database when the module is uninstalled the system will crash with a fatal error.

#### Expected behavior

The module should not remove the states that has been used as it will make the system unstable. 
But as there are modules that actually does this the system should be able to handle this.

One way to fix it is to modify GetOrderForViewingHandler.php / getOrderHistory function like this:

    private function getOrderHistory(Order $order): OrderHistoryForViewing
    {
        $history = $order->getHistory($this->contextLanguageId);

        $statuses = [];

        foreach ($history as $item) {
            $statuses[] = new OrderStatusForViewing(
                (int) $item['id_order_history'],
                (int) $item['id_order_state'],
                $item['ostate_name'] ?? 'Unknown',
                $item['color'] ?? '#E74C3C',
                new DateTimeImmutable($item['date_add']),
                (bool) $item['send_email'],
                $item['employee_firstname'],
                $item['employee_lastname']
            );
        }

This will show the status as 'Unknown' in red

#### Steps to Reproduce

1. BO > DESIGN > Modules > Module Manager
2. Import the test module
[issue25172.zip](https://github.com/PrestaShop/PrestaShop/files/6759097/issue25172.zip)
3. Assign state 'Issue 25172 Order State' to an order
4. Try to uninstall the module
5. Open details of the order that had the state changed in step 3

**Comment by ytilotti** [comment]
I reproduce this error. The problems is in history.
If an order_state is deleted (uninstall module, ...) and the ID of order_state deleted is still used in table order_history, this error appear.

**Comment by hibatallahAouadni** [comment]
Hello @ytilotti 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by jf-viguier** [comment]
@hibatallahAouadni to reproduce it, remove an order state and try to display an order on this state I guess (not tested)

**Comment by ytilotti** [comment]
**Additional information**

- PrestaShop version: 1.7.7.5
- PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @ytilotti & @jf-viguier & @nea-tingstroem-dk 

I just edit the issue, could you please confirm the steps to reproduce and provide a test module (that has some special orderstates) to reproduce the issue.
Please check and feedback.

Thanks!

**Comment by florine2623** [comment]
Hello all,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
