### ISSUE TITLE
Incorrect display on address block in BO > Customers > View customer

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#25174]
#### Describe the bug

In 1.7.8, the address block is displayed at the bottom of the page on right column, even is there is space above (see screenshot).

#### Expected behavior

2 possible display : 
- As in 1.7.7 : Address block takes the whole width of the page at the bottom of the page
- Address block is on the right column with no blank space above

#### Steps to Reproduce

1. Go to BO > Customers > Customers > View a Customer (John DOE)
2. Scroll down : See Address Block display

**Screenshots**

![address block in customer view ko](https://user-images.githubusercontent.com/55688534/123956155-a6bcf080-d9aa-11eb-9da3-7d20625f7c1d.png)

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by @Progi1984 in #25205
