### ISSUE TITLE
In module socialfollow, the links should be localized

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#25181]
#### Is your feature request related to a problem?

We have a shop with more than one language. The social media accounts are different for each language, but the module ps_socialfollow does not allow to enter a link for each language

#### Describe the solution you'd like

The links in the backoffice shoud have a language selector like other translateable configurations.

#### Alternatives you've considered

I don't see any alternatives.

#### Additional context

PS 1.7.7.5

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by Progi1984** [comment]
Fixed by @lmeyer1 in PrestaShop/ps_socialfollow#26

**Comment by matks** [comment]
Fixed in ps_socialfollow 2.2.0
