### ISSUE TITLE
BO - View Order - An exception is displayed when changing the order status to payment accepted

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25195]
#### Describe the bug
Related to: https://github.com/PrestaShop/PrestaShop/issues/25177, https://github.com/PrestaShop/PrestaShop/issues/25194
We create a product with customization:
- Type: **text**
- Lable: Must contain special expression: **Type your text < here>**
- 
 when we try to change the order status to payment accepted an error is displayed

#### Steps to Reproduce

1. create a product with customization:
- Type: **text**
- Lable: Must contain special expression: **Type your text < here>**
- product price > 0
2. Go to FO > Product page > Save customization and add the product to the cart 
![image](https://user-images.githubusercontent.com/16067358/123961872-1c2bbf80-d9b1-11eb-91ef-eda1fca94d8b.png)
3. Proceed to checkout and Place the order
4. Go to BO > Orders > View last order 
5. Change order status to payment accepted 
6. See error (1769 no error displayed) => **regression**
![image](https://user-images.githubusercontent.com/16067358/123962702-079bf700-d9b2-11eb-96b2-607ee1b641ea.png)

1769 > ok: https://drive.google.com/file/d/1bU6lmjaFsDq8YBzzX8XElUL00S3Jv1BT/view?usp=sharing
#### Additional information

* PrestaShop version: 1.7.7.x, 178_rc1
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed in #25200 by @Progi1984
