### ISSUE TITLE
BO - Add new Order - An exception is displayed when ordering a product with text customization - the label contains special expression

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25194]
#### Describe the bug

Related to: https://github.com/PrestaShop/PrestaShop/issues/25195, https://github.com/PrestaShop/PrestaShop/issues/25177
We create a product with customization:
- Type: **text**
- Lable: Must contain special expression: **Type your text < here>**

When we create an order from the BO with this product, we have an exception.

#### Steps to Reproduce

1. Create a product with customization:
- Type: **text**
- Lable: Must contain special expression: **Type your text < here>**
- product price > 0
2. Go to BO > Orders> Add new Order > Choose a customer
3. Add the last product with a customization
4. Choose order status = payment accepted 
![image](https://user-images.githubusercontent.com/16067358/123977139-0624fb80-d9bf-11eb-865a-a5fc43b22b18.png)
5. Create order
6. See error 
![image](https://user-images.githubusercontent.com/16067358/123977784-96634080-d9bf-11eb-93a9-a88041136e57.png)

With PS1769 => no error displayed: https://drive.google.com/file/d/1l_UotsG5YifOSeTnC9UFpeIlyGfRTK0E/view?usp=sharing

#### Additional information

* PrestaShop version: 177x, 178_rc1
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed in #25200 by @Progi1984
