### ISSUE TITLE
[BO - Responsive] - bad footer display on experimental product page

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#25198]
#### Describe the bug

In the new product page, the footer is not well displayed on mobile device. And there's button **Edit on experimental page**, I think it should be **Edit on standard page** cause we're already in the experimental page.

#### Expected behavior

A neat display of the footer like in the old Product page

![image](https://user-images.githubusercontent.com/23308427/124115695-66bf4180-da6e-11eb-9764-2f8a841c7767.png)

#### Steps to Reproduce

1. BO > SELL > Catalog > Products
2. Click on **New product on experimental page** button
3. Enable the **Toggle device toolbar** on your browser

**Screenshots**
- Edit Product
![image](https://user-images.githubusercontent.com/23308427/124114005-5f973400-da6c-11eb-9d6f-7c544dbb3382.png)

- New Product
![image](https://user-images.githubusercontent.com/23308427/124114301-b4d34580-da6c-11eb-82ab-1d00ada0d420.png)

#### Additional information

* PrestaShop version: develop & 1.7.8.x
* PHP version: 7.2

**Comment by Hlavtox** [comment]
@prestascott @hibatallahAouadni I think that:
- **Preview**, **Duplicate**, **Delete** and **Edit on experimental page** can all go to a single dropdown button called **Actions** or **Other tasks**.
- **Go to catalog** can go, if it does not fit. This button is on no other page, they have menu and breadcrumbs for this...
- And **Online/Offline switch** could well go on the product page itself. It's a product setting, why it should be on a footer instead in the content? :-)

And we are left with 1 dropdown button and a **Save** button, which will fit even the smallest phones. 😉

![Výstřižek](https://user-images.githubusercontent.com/6097524/124122607-8f4b3980-da76-11eb-991c-8e2bc1609d5d.JPG)

**Comment by prestascott** [comment]
Hello everyone,

Thank you @hibatallahAouadni for this issue!

@Hlavtox Can you provide us a full screen with your design suggestion for the footer please? Thanks!

**Comment by ElodieOS** [comment]
Hello everyone, 

We are working on the product page, so this issue is work in progress. 

I will keep you informed :)

**Comment by hibatallahAouadni** [comment]
This issue has been fixed with 8.1.x, see the attached screenshot below:

![image](https://github.com/PrestaShop/PrestaShop/assets/23308427/f6dd96ac-95f1-420c-9e1b-ae36404b9263)

Closing the issue :tada:
