### ISSUE TITLE
FO - 'Total available for each user' in cart rule not considered if the customer is signed in from the checkout page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25203]
#### Describe the bug

The 'Total available for each user' in cart rule not considered if the customer is signed in from the checkout page.

#### Steps to Reproduce

1. Create cart rule Check Total available for each User = 1 Set these fields:
1.1. Information:
- Name
- Description
- **Code**

1.2. Conditions:
- Total available = 2
- **Total available for each user =1**

1.3. Actions:
- Discount = 1 euro and click on Save
2. Go to FO > Sign in with john doe > apply the discount > Place the order
3. If you try to apply the cart again impossible
4. Sign out
5. Add a product to cart > In the shopping cart > apply the discount: ok
6. On the checkout page: sign in with john doe: the cart rule should be removed => it is not removed and the order is created with a discount again

178: https://drive.google.com/file/d/1b81nVyBM2bFjXFFbKPYy550uMesG4Tx4/view?usp=sharing
177x: https://drive.google.com/file/d/1FKI9EXBBbqhE6NIJu5H5pTfWZMEy5OKa/view?usp=sharing
1769 => ok: https://drive.google.com/file/d/1eZS5WXun-XeoO_tXoM-kqk15iTNO7yJM/view?usp=sharing

#### Additional information

* PrestaShop version: 177x(PS1776), 178_rc1
* PHP version: 7.2

**Comment by matks** [comment]
Pull Request https://github.com/PrestaShop/PrestaShop/pull/25286

**Comment by atomiix** [comment]
Fixed by #25286
