### ISSUE TITLE
Customer can't download virtual product if order contain a normal product

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#25206]
#### Describe the bug

Customer can't download virtual product if order contain also a normal product

#### Steps to Reproduce

1. Enable SAV 14 days 
2. Make an order with a virtual product + dowload file and with a normal product
3. Set order delivered
4. Go to order history an check if the download link is present 

**Screenshots**

**Possible regession ?** 

Acutaly 

![Capture d’écran de 2021-07-01 16-54-43](https://user-images.githubusercontent.com/5064590/124145834-713d0380-da8d-11eb-8bf6-ab9628f96f69.png)

Needed

![Capture d’écran de 2021-07-01 16-55-46](https://user-images.githubusercontent.com/5064590/124145881-7c902f00-da8d-11eb-953d-43d2fba6e018.png)

#### Additional information

* PrestaShop version: 178
* PHP version: 7..3

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

I manage to reproduce the issue with PS1.7.7.5 and PS1.7.6.5 with a virtual product only also.
1. Two products
- Marchandise return enabled => **NOK**
![image](https://user-images.githubusercontent.com/16067358/124277304-2da5d080-db45-11eb-9255-9e44c133bf88.png)
- Marchandise return disabled => **OK**
![image](https://user-images.githubusercontent.com/16067358/124277469-5c23ab80-db45-11eb-9636-5401ff5ade5d.png)
2. One virtual product
- Marchandise return enabled => **NOK**  => related to this issue: https://github.com/PrestaShop/PrestaShop/issues/16275
![image](https://user-images.githubusercontent.com/16067358/124277845-cf2d2200-db45-11eb-8f35-e665a150c130.png)

- Marchandise return disabled => **OK**
![image](https://user-images.githubusercontent.com/16067358/124277584-7a89a700-db45-11eb-9625-78779bba4926.png)

I'll add this to the debug backlog.
Thanks for the PR :tada: 

Thank you!

**Comment by ghost** [comment]
thank you @khouloudbelguith
