### ISSUE TITLE
problem with my prestashop when a customer orders

### ISSUE THREAD

**Issue by egoodswiss** [PrestaShop/PrestaShop#25226]
I have a problem with my prestashop when a customer orders the payment goes through I do receive the payment on my bank account but from the back office nothing no order can help me
* PrestaShop version: 1.7.7.5
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @egoodswiss 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
