### ISSUE TITLE
 Different active products by multi-store store  #multistore

### ISSUE THREAD

**Issue by superteixeira** [PrestaShop/PrestaShop#25227]
Hello,
We use the multi-store function as we have an online supermarket and also an online coffee shop. At supermarket online, we sell all items from the catalogue, while at the online coffee shop, we only sell coffee and chocolates.

Is there any function, or is there planned to exist in a future version to hide the products of a certain category in one of the stores (online coffee shop)? Currently, if we don't associate certain categories with one of the multi-store stores, even though that category is hidden, the products normally remain visible, both by visitors and by search engines. 

The only solution that currently exists is every time we edit a product, we manually disable that product in stores that we don't want to be visible.

I think that if this function doesn't exist yet, Prestashop should bet on its development. Certainly there will be other merchants who could benefit from it, for example, to hide certain products, of a category, depending on the country of the multi-store store.

There is a module on the marketplace, which serves to hide products, taking into account several factors, and which solves this problem, however, it causes an excessive slowness in loading the product category pages.

Waiting feedback,
Thanks,
Marco Teixeira

**Comment by d33x** [comment]
Hi @superteixeira 

Unfortunately this is a bug that I also encounter and is very problematic.

There is already an issue #13468 and a pull request #21877 linked but not yet validated. I hope that this will be fixed for 1.7.8 as it prevents the use of multistore for me

**Comment by hibatallahAouadni** [comment]
Hello @superteixeira 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #13468. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: Thanks @d33x for your quick reply :rocket: 

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #13468

**Comment by matks** [comment]
Hello @d33x PR #21877 was closed due to inactivity. If this topic is important for you, you might want to continue the work started in PR #21877 .
