### ISSUE TITLE
Updates can't be installed

### ISSUE THREAD

**Issue by dvision6** [PrestaShop/PrestaShop#25225]
4 modules can't be updated. Each module gets the error.

Info:
Prestashop 1.7.7.5
Server information Linux #1 SMP Tue Jun 9 12:58:54 MSK 2020 x86_64
Server software version: Apache
PHP version: 7.3.28
Memory limit: 1024M
Max execution time: 30
Upload Max File size: 16M

**Comment by matks** [comment]
Hello @dvision6 can you tell us which 4 modules you talk about? Are they developed by PrestaShop or by another developer ?

**Comment by hibatallahAouadni** [comment]
Hello @dvision6 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
