### ISSUE TITLE
illegal length modifier specified 'f' in s(np)printf call

### ISSUE THREAD

**Issue by smithikakart** [PrestaShop/PrestaShop#25228]
#### Describe the bug

while in debug mode getting fatal error illegal length modifier specified 'f' in s(np)printf call without debug mode getting internal 500 error/blank page...

#### Expected behavior

cash on delivery validation after order succeed customers are facing this error 

#### Steps to Reproduce

1. Go to 'https://smithikakart.in/'
2. Click on 'add to cart https://smithikakart.in/powerbank/815-858-syska-5000-mah-power-bank-p0511-lithium-polymer.html#/10-color-red'
3. Scroll down to 'complete order by using COD payment option'

![cod validation error](https://user-images.githubusercontent.com/67721911/124407802-6cfd3880-dd62-11eb-81cf-78c5294cb489.png)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2

**Comment by matks** [comment]
Hi @smithikakart what a strange error 😮 

I googled this issue a bit and it seems to happen in a lot of different php projects: Drupal (https://www.drupal.org/project/drupal/issues/3152749), Laravel (https://stackoverflow.com/questions/66281360/error-illegal-length-modifier-specified-f-in-snpprintf-laravel) and PrestaShop (https://www.prestashop.com/forums/topic/1031039-illegal-length-modifier-specified-f-in-snpprintf-call-in-smarty_template_compiledphp-line-178/)

Unfortunately when we read the answers provided it seems people were able to fix the issue by clearing the cache or changing settings in php settings, so it seems not related to PrestaShop.

**Comment by hibatallahAouadni** [comment]
Hello @smithikakart 

I didn't manage to reproduce the issue with a fresh install and with Classic theme, it seems your issue related to Cache issue as @matks mentioned above.

Sorry but I have to close the issue cause we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

PS: thanks @matks for your quick reply :rocket: 

Thank you
