### ISSUE TITLE
ps_facetedsearch result order not good

### ISSUE THREAD

**Issue by ad1rie1** [PrestaShop/PrestaShop#25223]
#### Describe the bug

When you do query for have the most recent created product : 

https://XXXX.fr/2-CATEGORIE?order=product.id_product.desc

The product order returned is not good I have 11 product 

the order returned is : 2,1,11,9,8,7,6,5,4,3

#### Expected behavior
Have product listed in the order 11,10,9,8,7,6,5,4,3,2,1

#### Steps to Reproduce

1. Go to Catégorie with product , more than 11 product is needed
2. Add ?order=product.id_product.desc      at the end of categorie URL
3. Show the product order

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @ad1rie1 

It seems your issue is kind of related to these #19810 & #16735
Did you encounter this issue with another Facted search version? and what's your module version?
Please check and feedback.

Thanks!

**Comment by ad1rie1** [comment]
Hello, The module version is : v3.7.1 and prestashop : 1.7.7.5

**Comment by ad1rie1** [comment]
The Two issues is unrelated. Because i am targeting Product ID not price or some range value

**Comment by hibatallahAouadni** [comment]
Hello @ad1rie1 

I didn't manage to reproduce the issue with PS1775 and FactedSearch v3.7.1, see the attached screen record below:

https://drive.google.com/file/d/1vtMT0kcLDIlrfLAjlUz5e4KTnn4Mm0qY/view

Please check and feedback.
Thanks!

**Comment by ad1rie1** [comment]
Ok , very strange but ok ! i will search on my install so ;)

**Comment by hibatallahAouadni** [comment]
@ad1rie1 don't forget to feedback even the issue is closed :wink:
