### ISSUE TITLE
Every time I updated the carrier, new entry is made in the database

### ISSUE THREAD

**Issue by datshay3292** [PrestaShop/PrestaShop#25230]
I am using prestashop 1.7.7.5

When I update my carrier details and click on Finish button, it makes a new entry in the database instead of updating. 

Before editing the carrier, the id of my carrier was 21, after I update the carrier it becomes 22 and on my next update it becomes 23 and continues. This is making duplicate entries in the database.

Please check this.

**Comment by hibatallahAouadni** [comment]
Hello @datshay3292 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by datshay3292** [comment]
Hello,

Thank you for quick check. Please once create a new carrier here Shipping>>carrier
Then save it.  

New carrier will be created with some id_carrier, lets say 10

Now edit that carrier and save it. It will create a new id_carrier for that carrier.
Again edit and save. New id_carrier is again created. 

That means, every time I update any carrier, it will create a whole new entry for that particular carrier with the updated data instead of just updating previous entry.

I tried this on PS 1.7.75 , PS 1.7.6.0  and 1.7.5.0

**Comment by kpodemski** [comment]
Hello. It's not a bug. You need to have an old carrier for historical data. If you want to do something based on this carrier, you should use the `id_reference` field.

**Comment by datshay3292** [comment]
Actually you are not getting the point here.

Every time I make any changes to my carrier and save it, the id_carrier is also changed from 10, 11, 12 , 13 and continues. 

That means it is making new entry in the database for the tables : ps_carrier,  ps_carrier_lang, ps_delivery, ps_weight_range

You can once check this by creating a new carrier and update that carrier. You will see the new id for that carrier everytime you update it.

Let me know if this is still not a bug.

**Comment by matks** [comment]
@datshay3292 Just like @kpodemski said, it is not a bug. This is done on purpose.

`ps_carrier` SQL table contains records. Every time you update a carrier settings, a new record is created (with new data) and the old record is kept for history as it might be needed for old orders.

> That means, every time I update any carrier, it will create a whole new entry for that particular carrier with the updated data instead of just updating previous entry.

It's working as expected.

If you update one thousand times a carrier, you will have one thousand entries in ps_carrier because they are records, not "only active carriers".
