### ISSUE TITLE
How to get category id in hookdisplayBackOfficeCategory($params) in prestashop 1.7.8.0

### ISSUE THREAD

**Issue by web23421** [PrestaShop/PrestaShop#25247]

**Comment by florine2623** [comment]
Hello @web23421 ,

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
