### ISSUE TITLE
BO - Translations - An error "There are no translation file available." is displayed 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25240]
#### Describe the bug
An error is displayed when we try to translate the Front office + core.
Shop > Theme > Catgory => an error is displayed.

#### Steps to Reproduce

1. Go to BO > International > Translations page
2. Choose FO translations + core + English
3. Click on Shop > Theme > Category

In the PS177x, we don't have the tree: Shop > Theme > Category
![image](https://user-images.githubusercontent.com/16067358/124486580-09006180-ddae-11eb-9340-46c5a9008775.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/124486032-79f34980-ddad-11eb-9d6d-7f77117c8c93.png)

#### Additional information

* PrestaShop version: 178_rc1
* PHP version: 7.2

**Comment by sowbiba** [comment]
Cannot reproduce it

![Capture d’écran de 2021-07-26 16-57-04](https://user-images.githubusercontent.com/7426640/127028840-006f7451-a917-41af-833a-0ea9b3b01ce2.png)

can you try it again @khouloudbelguith ? 
Maybe linked to the translation packs not up to date

**Comment by khouloudbelguith** [comment]
Hi @sowbiba,

Yes, you are right.
I did not manage to reproduce the issue with branch 1.7.8.x
![image](https://user-images.githubusercontent.com/16067358/127135043-75dcd5f2-08d6-4afa-b0b8-06b43c94770b.png)

I will close the issue.

Thanks!
