### ISSUE TITLE
BO - Localization Page - There is no confirmation modal when changing the currency by default

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25264]
#### Describe the bug

In the BO > International > Localization page, when we try to change the currency by default, there is no confirmation modal displayed as in the PS177

#### Expected behavior
A modal is displayed when selecting another currency
![image](https://user-images.githubusercontent.com/16067358/124629132-716c4300-de81-11eb-99c5-37a919f083b0.png)

#### Steps to Reproduce

1. Create a new currency
2. Go to BO > International > Localization page
3. Try to change the currency by default
4. See error: the confirmation modal is not displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/124629420-b7290b80-de81-11eb-84c4-59ef1a3154d6.png)

#### Additional information

* PrestaShop version: 1.7.8.0_rc1
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @PrestaShop/product-team!

This issue should be fixed in the PS178_rc1_build2?

Thanks!

**Comment by Progi1984** [comment]
Fixed by @Progi1984 in #25386
