### ISSUE TITLE
Error sent by Addons. You may need to be logged.

### ISSUE THREAD

**Issue by TianaRiantsoa** [PrestaShop/PrestaShop#25274]
#### Describe the bug
Error sent by Addons. You may need to be logged.

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: 7.3.12

**Comment by matks** [comment]
Hello @TianaRiantsoa I am sorry but we can nothing with this kind of github issue. There is no question, no explanation, no context.

Please follow one of the templates https://github.com/PrestaShop/PrestaShop/issues/new/choose
