### ISSUE TITLE
Add .php-cs-fixer.dist.php for PHP-CS-Fixer version 3

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#25278]
#### Is your feature request related to a problem?
.php_cs.dist is renamed .php-cs-fixer.dist.php in version 3 :
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.0.0/UPGRADE-v3.md

#### Describe the solution you'd like

Support both version with both .php_cs.dist & .php-cs-fixer.dist.php files

**Comment by matks** [comment]
Hello @jf-viguier I'm not sure to understand.

1. We don't have to follow PHP-CS-Fixer naming. This is just a default name. If I am not wrong, we can name the PHP CS Fixer configuration file `presta-php-cs.php` and use `--config` option to simply target this file?
2. Why would we support both versions? We use php-cs-fixer v2.19 so right now we use the right convention. If we upgrade to php-cs-fixer v3 we can change the filename, if we don't want to require the use of `--config`. Why should we keep both? We will never use php-cs-fixer v2 and php-cs-fixer v3 concurrently?

**Comment by atomiix** [comment]
@jf-viguier I've done it in this PR: https://github.com/PrestaShop/PrestaShop/pull/25052/files#diff-8ec5bae185dc9af5b5bfdcd5f1dcbee62f18525ee488996d52b22729f4076ef0 ;)

**Comment by jf-viguier** [comment]
@matks my VS Code cs fixer plugins seems to use CS Fixer version 3 and not the one used in prestashop, that' the reason why.
Thanks @atomiix but my pr is maybe needed before SF 4 ?
If not, feel free to close my pr.

**Comment by atomiix** [comment]
@jf-viguier for now, we're not using php-cs-fixer 3 so no need to rush, the config file is only deprecated.
I think you should use the version set in the composer.json rather than the version packaged with the VS code plugin you're using though, it will be less prone to error as the CI is using the version set in composer.json.

**Comment by jf-viguier** [comment]
@atomiix thanks, but look at PHP CS Fixer depot : they support both, it could be useful for some people I guess ?

**Comment by matks** [comment]
Hello @jf-viguier and @atomiix do you have
- motivations for upgrading php-cs-fixer to v3
- or doubts against upgrading php-cs-fixer to v3

Now that work on v8 is really started, we can consider to bump php-cs-fixer version but we have to make sure it brings benefits.
