### ISSUE TITLE
Autoupgrade - Error during upgrade to develop

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#25276]
#### Describe the bug

After creating a release on develop, and upgrading to this zip with autoupgrade module, there is an error during the upgrade.

Need to stop make auto test from 1.6 to 8.0
Find an alternative to test the upgrade from 1.6 to 8.0 without the fails of PHP env

#### Expected behavior

No error during upgrade

#### Steps to Reproduce

1. Install a develop version
2. Using the Create Release Tool (`php tools/build/CreateRelease.php`), create a release
3. On a 1.6.1.24 or a 1.7.7.5 (or probably with any other version), upgrade to the zip created at previous step
4. See error during upgrade

**Screenshots**

Error on upgrade : 
![error upgrade 179](https://user-images.githubusercontent.com/55688534/124773188-02ecbb00-df3d-11eb-8192-992ec9b1449f.png)

#### Additional information

* PrestaShop version: develop
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @Robin-Fischer-PS 

I reproduce the issue with PS1774, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/124788916-1b170700-df4a-11eb-909c-3a780d015533.png)

Thanks!

**Comment by atomiix** [comment]
Fixed by #408
