### ISSUE TITLE
Unable to add Embed Video in Product Description

### ISSUE THREAD

**Issue by rhariskumar3** [PrestaShop/PrestaShop#25270]
#### Embed Video

I can't able to add embed video in the Product description. It showing "The description field (English (English)) is invalid."

#### Steps to Reproduce

1. Add or Edit Product
2. In Description, Insert embed video [Youtube Embed Code]
3. Click Save

**Screenshots**

<img src="https://i.ibb.co/yFWMRLR/Annotation-2021-07-07-092514.png" alt="Annotation-2021-07-07-092514" border="0">
<img src="https://i.ibb.co/p3x28B4/Annotation-2021-07-07-092514.png" alt="Annotation-2021-07-07-092514" border="0">

#### Additional information

- Server: Ubuntu 18.04.2
- PHP: 7.2.24
- MySQL: 14.14
- PrestaShop: 1.7.7.4

**Comment by Hlavtox** [comment]
@rhariskumar3 Hi, try to go to Shop parameters > General and enable **Allow iframes on HTML fields**. Try it and let me know. ;-)

**Comment by rhariskumar3** [comment]
Yeah. It's working fine now. Thanks for your support.

**Comment by hibatallahAouadni** [comment]
Thanks @Hlavtox for your quick reply :superhero:
