### ISSUE TITLE
FO - the product-flags must be on the same row but with spaces

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#25272]
#### Describe the bug

The product-flags are displayed in the same row with no space

#### Expected behavior

The product-flags must be on the same row but with spaces

@prestascott notes:

- the out of stock label will be changed, so it won't be like that anymore
- the spacing between the 2 labels is 8 px

#### Steps to Reproduce

1. **BO** > **SELL** > **Catalog** > **Products**
2. Create a new product with a **specific price** (discount of 10% starting at 1 unit) and **qty**=0
3. **Save** and click on **preview** button
4. See error > the product-flags are displayed in the same row without spaces between them

**Screenshots**

### 1.7.8.x

![image](https://user-images.githubusercontent.com/23308427/124726229-db322e80-df0d-11eb-9cdc-b820c84694b6.png)

![image](https://user-images.githubusercontent.com/23308427/124726254-e08f7900-df0d-11eb-80d8-6178c6b13cd9.png)

#### Additional information

* PrestaShop version: 1.7.8.x & develop
* PHP version: 7.2

**Comment by Hlavtox** [comment]
@hibatallahAouadni @NeOMakinG

```
.product-flags {
  flex-direction: column;
}
```

**Comment by hibatallahAouadni** [comment]
@Hlavtox Go ahead and create a PR :wink:

**Comment by hibatallahAouadni** [comment]
@Hlavtox could you please check @prestascott notes in the Expected behavior bloc before creating your PR :pray: 
Thanks in advance.

**Comment by prestascott** [comment]
@hibatallahAouadni yep, it's good to me :) thanks!

**Comment by Progi1984** [comment]
Fixed by @Progi1984 in #25387
