### ISSUE TITLE
Condition isCatalogueMode reversed + Price drop link related to the PS_DISPLAY_BEST_SELLERS condition

### ISSUE THREAD

**Issue by Sinepel** [PrestaShop/PrestaShop#25277]
#### Describe the bug

- On the sitemap page, until now, the condition isCatalogueMode was reversed. 
So if you were not in catalogue mode, the best sellers + price drops page was not displayed. 
- Also, if the PS_DISPLAY_BEST_SELLERS condition is false, you cannot display the price drop page. 
Indeed, on the PricesDropController, there is no init() method which, like for the BestSalesController, checks the PS_DISPLAY_BEST_SELLERS condition.
So to standardize, they should be dissociated here

#### Expected behavior

These two links should appaar when the catalog mode is disable + price drop link must be not linked with PS_DISPLAY_BEST_SELLERS condition

#### Steps to Reproduce

1. Go to /index.php?controller=sitemap with cataloge mode disable
2. You can't see price drop + best sellers page
3. If you enable the catalog mode, go back to the sitemap, you can see the prices drop + best sellers link
4. Same if you enable or disable `PS_DISPLAY_BEST_SELLERS`configuration, prices drop link depends on it

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.x / 1.7.7.x
* PHP version: Any

**Comment by hibatallahAouadni** [comment]
Hello @Sinepel 

I reproduce the issue but I think it will be better if we check with PM if this is the wanted behavior or not :wink: 

Ping @PrestaShop/product-team 

1. When we disable cataloge mode option in BO>Shop Parameters>Product Settings
2. FO>Sitemap
3. the two links **price drop** + **best sellers** should be displayed or not?

Thanks in advance :pray:

**Comment by Sinepel** [comment]
Hello @hibatallahAouadni 

No problem.
However, as the 2 controllers are not linked, as the PS_DISPLAY_BEST_SELLERS condition is checked in the best sellers controller but not in the price drops controller, I won't understand that they should be linked here, if you know what I mean :)

Thanks !

**Comment by marionf** [comment]
@hibatallahAouadni Yes, the price drop and best sellers pages should be displayed if the catalog mode is disabled.

**Comment by hibatallahAouadni** [comment]
Thanks @marionf :relaxed:
