### ISSUE TITLE
Duplicated "firstname" in ps_address

### ISSUE THREAD

**Issue by dwitassek** [PrestaShop/PrestaShop#25273]
We have a total of 10 Prestashop stores running for different customers in different versions and we are observing a strange behaviour in all of them. 

Although the customer enters his correct details in the address field when ordering, the first name is found twice in the order. 

In the database it looks like this:
ps_customer - firstname: XXX
ps_customer - lastname: YYY

ps_address - firstname: XXX
ps_address - lastname: XXX

The problem occurs at irregular intervals and we have tried desperately to reproduce it ourselves without success. If only we knew what the problem is, then we could fix it ourselves maybe. But so far we have not been able to find a common denominator between the faulty orders.

Any one else with the same problem?

PS-Versions: 1.7.x to 1.7.7.4
PHP-Versions: 7.2.34

**Comment by hibatallahAouadni** [comment]
Hello @dwitassek 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have
questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

PS: Could you please post your issue on Public Slack, maybe one of the contributors has already encountered this issue and can help you :wink: 

Thank you

**Comment by dwitassek** [comment]
Sorry, but in my opinion this is a bug: reproducable in 10 different installations.

**Comment by hibatallahAouadni** [comment]
Hello @dwitassek 

But you said: 
> The problem occurs at irregular intervals and we have tried desperately to reproduce it ourselves without success.

So, if you can't reproduce it and can't provide clear and concise steps to reproduce, how can I reproduce it?
And that's why I asked to post the issue on Public Slack, so Contributors can help you to solve the issue :slightly_smiling_face: 

Thanks!
