### ISSUE TITLE
Breadcrumbs hidden on mobile

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#25284]
#### Is your feature request related to a problem?

Breadcrumbs are hidden on lower resolutions. Why? Their purpose is to ease the navigation on our store, even more on mobile devices.

#### Describe the solution you'd like

Stop hiding breadcrumbs on mobile

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by prestascott** [comment]
Hey @Hlavtox,

Thank you for your request. I don't understand why it has been removed on mobile, we should keep the breadcrumb to inform customers where they are in the website.

Wdyt @PrestaShop/product-team ?

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

We have a GO from UX-team and Product Team :tada: changing the label to **`To Do`**.

Thanks everyone :pray:
