### ISSUE TITLE
Native module ps_linklist custom link url validation

### ISSUE THREAD

**Issue by Oksydan** [PrestaShop/PrestaShop#25299]
#### Describe the bug

When we try to add custom link with url like this `/my-category`, validation error occurs. We are force to use full link `domain.com/my-category`. To easier maintain our multiple test environment we are migration some database tables to multiple prestashop installations. To make sure links will work on every installation we can't use links with domains.

#### Expected behavior

Validation should be removed. 

#### Steps to Reproduce

1. Go to ps_linklist.
2. Edit links block.
3. Add new custom link with url: `/my-link`.
4. Validation error occurs.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @Oksydan,

Thanks for your issue.
I think it is not a bug but normal behavior.
![image](https://user-images.githubusercontent.com/16067358/125068719-1707f800-e0b6-11eb-9fae-e29dc5c755d2.png)

But it could new improvement: when we add an URL `/my-link` it should be ok and it is rewritten to `Shop.com/my-link`

Ping @PrestaShop/product-team what do you think?

Thank you!

**Comment by kpodemski** [comment]
Good idea, especially when we want to keep URLs working between a few environments 👍

**Comment by lmeyer1** [comment]
@PrestaShop/product-team 
This is very important in multi-shop context. In fact, different shops have a different domain, thus using URLs without domain is a must.

**Comment by florine2623** [comment]
ping @PrestaShop/product-team ,

Could I get a PM ✅  label before testing the related PR : https://github.com/PrestaShop/ps_linklist/pull/134 ?
Thanks !

**Comment by marionf** [comment]
@florine2623 Done ✔️
