### ISSUE TITLE
Rounding problem on specific prices for products

### ISSUE THREAD

**Issue by d33x** [PrestaShop/PrestaShop#25290]
#### Describe the bug

This is a minor bug but it may have repercussions elsewhere (?).

In the price (cost, VAT, ...) of a product, put "65.13" and see the result. The amount is automatically changed to "65.129999". This is not the case for many other numbers.

#### Expected behavior

The amount should remain in "65.13" and should not be changed.

#### Steps to Reproduce

1. Go to 'Catalog -> Products'
2. Click on 'Edit'
3. Go to 'Pricing'
4. Put '65.13'
5. See error

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: 7.3.28

**Comment by khouloudbelguith** [comment]
Hi @d33x,

We manage to reproduce the issue, it is added to our debug roadmap.
Your ticket is a duplicate of #12078
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #12078
