### ISSUE TITLE
BO - Products with combinations - Adding a quantity and imapct with comma does not work

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25308]
#### Describe the bug
In the BO > Product page > Combination tab, when we try to add an impact on price or quantity with a comma, an error is displayed

#### Expected behavior
When user type inside an NumberType input, add a transformer to replace all characters 
for example 1,000,2 => 10002

#### Steps to Reproduce

1. Go to BO > Catalog > Products > EDit a product with combinations
2. In the combinations Tab, set the impact on price = 1,000,2 and quantity = 1,000,2 
![image](https://user-images.githubusercontent.com/16067358/125104075-48e08500-e0dd-11eb-83b4-e9cc55259243.png)
3. Save
![image](https://user-images.githubusercontent.com/16067358/125104209-67468080-e0dd-11eb-9aa6-86894f95ea21.png)

Related to this PR: https://github.com/PrestaShop/PrestaShop/pull/24339 (reproduced with this PR also)

#### Additional information

* PrestaShop version: 1.7.6.9, 1.7.7.x
* PHP version: 7.2

**Comment by florine2623** [comment]
Can't use double commas on quantity.
Commas are deleted when more than 1 is used.
