### ISSUE TITLE
Problem with pagination in New Product after sort by price PrestaShop 1.7.8

### ISSUE THREAD

**Issue by rzuf666** [PrestaShop/PrestaShop#25310]
in file /classes/Product in function getNewProducts() sorting by price has been fixed, but in the line of code responsible for splitting into pagination when this sort is active, the order of variables has been mixed up:

**Instead:**

if ($order_by === 'price') {
            Tools::orderbyPrice($result, $order_way);
            $result = array_slice($result, (int) (($nb_products - 1) * $page_number), (int) $page_number);    // Line 3065
}

**should be:**

if ($order_by === 'price') {
            Tools::orderbyPrice($result, $order_way);
            $result = array_slice($result, (int) (($page_number - 1) * $nb_products), (int) $nb_products);   // changes
}

Otherwise, the paging does not work and only one product is shown in the news when you select sort by price. Paging works fine after this change.

* PrestaShop version: 1.7.8

I write before about this not working sort by price in new product and prices drop pages in relation to Prestashop 1.7.7.5 - https://github.com/PrestaShop/PrestaShop/issues/25309 

It looks like this will be fixed in PS 1.7.8 :)

**Comment by hibatallahAouadni** [comment]
Hello @rzuf666 

I think it will be better if you add these infos in your #25309 issue and close this one :wink: 
IMO it's the same issue. If you think not, so please follow the provided template to submit a complete bug report.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @rzuf666 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
