### ISSUE TITLE
BO - Orders page - an exception is displayed when deleting a customer or a guest

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25319]
#### Describe the bug

In the BO > Orders > Order view page, an exception is displayed when deleting the customer who created this order

#### Expected behavior

No exception displayed

#### Steps to Reproduce

1. Create order from BO  or FO with a new customer or a guest
2. View the last order created => ok
3. Go to BO > Customers > Customers page and delete the new customer or the guest
4. Go back to the last Order created
5. See error 
![image](https://user-images.githubusercontent.com/16067358/125266312-0221a380-e306-11eb-8eb6-19ac1756736f.png)

This error is detected by nightly: https://nightly.prestashop.com/report/1908
Related to this PR: https://github.com/PrestaShop/PrestaShop/pull/25059

#### Additional information

* PrestaShop version: 177x, 178x, develop
* PHP version: 7.2

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/25326
