### ISSUE TITLE
Develop branch seems not php 7.1 compliant

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#25324]
#### Describe the bug

Compile Error: Declaration of Symfony\Component\DependencyInjection\ServiceLocator::get($id) must be compatible with Psr\Container\ContainerInterface::get(string $id)

#### Expected behavior

No compile error

#### Steps to Reproduce

Install develop branch on php 7.1, composer install, launch install and see error.

#### Additional information

* PrestaShop version: develop
* PHP version: 7.1

**Comment by kpodemski** [comment]
Next major will not be compatible with 7.1, minimum compat. has been set to 7.2.5

**Comment by jf-viguier** [comment]
@kpodemski thanks, develop is on next major ?

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers any idea?

**Comment by matks** [comment]
No, `develop` branch is scheduled to become 1.7.9.0
⏩  milestone https://github.com/PrestaShop/PrestaShop/milestone/64
⏩  kanban https://github.com/PrestaShop/PrestaShop/projects/12

I close as this is not a bug, it is expected 😉

**Comment by matks** [comment]
I close the issue as it's expected that php7.1 is not compatible with PS on branch `develop`

The PHP ecosystem is now focused on php8.0 and php8.1 it becomes impossible to maintain a php compatibility range large enough to contain php7.1 and php8.0

**Comment by jf-viguier** [comment]
Thanks @matks.
How will be managed upgrades from 1.6 and 1.7.4 (and less) that are not php 7.2 compatible ?

**Comment by matks** [comment]
> Thanks @matks.
> How will be managed upgrades from 1.6 and 1.7.4 (and less) that are not php 7.2 compatible ?

Two ways to achieve it:

1. Just like people who upgrade from PS 1.3, 1.4 or 1.5 to 1.7 : do it in many steps. Upgrade 1.3 to 1.4 then 1.4 to 1.5 then 1.5 to 1.6 then 1.6 to 1.7.4 then 1.7.4 to latest. It requires the right autoupgrade version (not the latest).

This is already being done by PrestaShop specialists.

2. Future way: we aim to deliver an improved version of the autoupgrade module that can work with old php5 versions and php8.

This is not done for now, it's still being explored.

**Comment by jf-viguier** [comment]
@matks I've done a PR to the doc https://github.com/PrestaShop/docs/pull/1080
Not sure for recommanded

**Comment by jf-viguier** [comment]
@matks I'm doing a lots of 1.6 upgrades, I don't use the autoupgrade module at all. I have my own process sql based.
