### ISSUE TITLE
FO - Product details page is not well displayed when changing the layout of the product to another layout than the default one

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25332]
#### Describe the bug

In the BO > Design > Theme & Logo, when we change the layout of the product to another layout than the default one, in the FO > The product details page is not well displayed

#### Steps to Reproduce

1. Go to BO > Design > Theme & Logo page
2. Click on Choose layout
3. Scroll down to 'Product' and change the layout to another one than the default
4. Go to FO > Product details page
4. See error > not well displayed

----------------------------------------------------------------------------------

1. case 1:
178x + `Three Columns - One large central column and 2 side columns.`
![image](https://user-images.githubusercontent.com/16067358/125418943-698a753c-359c-4014-801f-7e9ac1752a86.png)
177x + `Three Columns - One large central column and 2 side columns.`
![image](https://user-images.githubusercontent.com/16067358/125419022-d5d54f27-90e0-464b-8bf7-bc75810fe879.png)

2. Case2:
178x + `Two Columns, small left column - Two columns with a small left column`
![image](https://user-images.githubusercontent.com/16067358/125419151-bccb9192-8986-44e8-974d-a64cf5f46484.png)
177x + `Two Columns, small left column - Two columns with a small left column`
![image](https://user-images.githubusercontent.com/16067358/125419233-8dce467b-813d-4cdb-9d3f-486d604bc9c2.png)

3. Case3:
178x + `Two Columns, small right column - Two columns with a small right column` 
![image](https://user-images.githubusercontent.com/16067358/125419466-1dfc12b3-66fa-44d3-9dd7-8f4558f966c2.png)

177x + `Two Columns, small right column - Two columns with a small right column`
![image](https://user-images.githubusercontent.com/16067358/125419395-cc73152e-083b-4479-8d71-d12f3e1453ea.png)

#### Additional information

* PrestaShop version: 178x, develop
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by @matthieu-rolland in #25343
