### ISSUE TITLE
Error on installation - ps_eventbus not found on Addons

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#25331]
#### Describe the bug

When installing the 178x branch, I systematically encounter an error on the "Install Addons modules" step : 

The following error is displayed "The module ps_eventbus could not be found on Addons."

It's OK on 1.7.7.x branch and on develop branch.

#### Expected behavior

No error and smooth upgrade :)

#### Steps to Reproduce

1. Install 1.7.8.x
2. On step "Install Addons modules", see error

**Screenshots**

![error ps eventbus install](https://user-images.githubusercontent.com/55688534/125418360-8a2eb2aa-b6f3-4a31-a5e5-3a979998572c.png)

#### Additional information

* PrestaShop version: 1.7.8.x
* PHP version: N/A

**Comment by matks** [comment]
FYI this is also crashing the CI on 1.7.8.x branch

![Capture d’écran 2021-07-13 à 11 49 10](https://user-images.githubusercontent.com/3830050/125431108-aa0f41f5-2671-4b4f-86d8-347942a2b18f.png)

**Comment by matks** [comment]
Fixed by PSX team that provide ps_eventbus

**Comment by illtellyoulater** [comment]
> Fixed by PSX team that provide ps_eventbus

@matks sorry but could you be a little more detailed ? How did you fix this ? Who's this PSX team you mentioned and where is the "ps_eventbus" they would provide ?

If anyone else happens to know what he's talking about, please let me know! Thanks!

**Comment by matks** [comment]
AFAIK ps_eventbus is a module built by PrestaShop extension (a.k.a modules) team

the module was being pushed during install process into new shops and was faulty, breaking shop installs

the team fixed the module so install issue disappeared

note: in next prestashop version no modules will be pushed during install, so such issues will never happen again
