### ISSUE TITLE
BO order - No way to echo tracking information

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#25337]
#### Is your feature request related to a problem?

When creating order in backoffice, there is no information sent to tracking scripts like Google Analytics, due to not being able to output it.

#### Describe the solution you'd like

Simmilar hook like displayOrderConfirmation should be made in backoffice header, with a parameter of new order ID.

#### Alternatives you've considered

Other hooks cannot be used for this as it's not safe to detect if it's BO or FO order.

**Comment by florine2623** [comment]
Hello @Hlavtox ,

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 

Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know!

Thank you

**Comment by florine2623** [comment]
Ping @PrestaShop/product-team ,

What do you think about @Hlavtox 's feature idea ?

Thanks!
