### ISSUE TITLE
BO - Orders - Cannot add a product  with combinations to an old order

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25347]
#### Describe the bug

In the BO > Orders > Old order page, an error is displayed when we try to add a demo product associated with the Fashion supplier.
This issue is due to the merge: https://github.com/PrestaShop/PrestaShop/pull/25297
It is detected by Nightly: https://nightly.prestashop.com/report/1912
Thanks @nesrineabdmouleh 

#### Steps to Reproduce

1. Go to BO > Orders > View old order
2. Try to add a product with combinations
![image](https://user-images.githubusercontent.com/16067358/125600272-721ad621-0ae3-4309-937c-be513622ec4c.png)

#### Additional information

* PrestaShop version: 1.7.8.x
* PHP version: 7.2

**Comment by matks** [comment]
The error message makes me think it could be linked to https://github.com/PrestaShop/PrestaShop/pull/24339 ping @PierreRambaud

**Comment by khouloudbelguith** [comment]
Hi @matks,

This PR: #24339 is merged into 177x 12 July 2021
But this error is detected in nightly 1.7.8.x Report - 10/07/2021
 https://nightly.prestashop.com/report/1912

Thanks!

**Comment by matks** [comment]
@khouloudbelguith rather than "demo product associated with fashion supplier", what about simply "product with a combination" ?

1. Create a new product _with combinations_
2. Open an existing order
3. Try to "add a product", select the new product
4. See that "price tax incl." and "price tax excl." fields are filled with "object" and not prices

**Comment by khouloudbelguith** [comment]
@matks, thanks a lot
Yes, It was due to a product with combinations
https://drive.google.com/file/d/1mQQjqeSBalIuLm4Bkce2JTPRUSZG6zQ3/view?usp=sharing

I will update my issue.
Thank you!

**Comment by Progi1984** [comment]
Fixed in #25364 by @jolelievre
