### ISSUE TITLE
Problems with Chrome Browser: pull photos in product is not more possible

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/PrestaShop#25348]
#### Describe the bug

Use Chrome Browser to work with Prestashop. Go to catalog -> products and add a new one ord open a excisting one. Pull photos from PC folder into product and it does not work any more. 

#### Expected behavior

Pulling photos in products by using Chrome Browser it should work as expected. 

#### Steps to Reproduce

1. use Chrome Browser to work with Prestashop
2. Go to 'catalog -> products'
3. add a new product or open a excisting one
4. pull photos from PC folder into the product
4. See error that photos can not be pulled anymore to add them

**Screenshots**

#### Additional information

* PrestaShop version: 1.7.6.9 in my case
* Chrome Browser version: Version 91.0.4472.123 (Offizieller Build) (64-Bit)
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @didi-2018 

I didn't manage to reproduce the issue with PS1767 and PS1775, see the attached screen record below:

https://drive.google.com/file/d/1O5eko9LiDGLtKeda3o45EiowoAyXBC8h/view

As you can see I tried both methods to add a photo and it works.
Please check and feedback.

Thanks!

**Comment by didi-2018** [comment]
@hibatallahAouadni Hello! As you can see you use a different build number of Chrome Browser not that one I wrote und you do not use PS 1.7.6.9

And I can see too that you click on the photo tab in photo section. I said "to pull" photos from your PC folder. 

Please check with that versions above and pull method NOT open method. Thank you!

**Comment by hibatallahAouadni** [comment]
Hello @didi-2018 

If I haven't reproduced the problem with PS1767 and PS1775, it means there is no problem with PS1769 or if it exists it was fixed with PS177x.
About the browser, I have updated to the latest version and this is the version I got.

So, could you please check if you have any errors on your Chrome console.
And please provide a screen recording or screenshot to better understand the problem.

> I said "to pull" photos from your PC folder.

And as I mentioned "I tried both methods to add a photo and it works" it means I tried **"to pull" photos from your PC folder** and **click on the photo tab in photo section**.

Thanks!

**Comment by didi-2018** [comment]
@hibatallahAouadni 

https://drive.google.com/file/d/187jmV2pGH_4gWvsHDwYzOEcCuNPA1Ddh/view

this is recorded from Prestashop Demoshop Version 1.7.7.5

**Comment by hibatallahAouadni** [comment]
Hello @didi-2018 

> this is recorded from Prestashop Demoshop Version 1.7.7.5

Yep I can see that :wink: 
Well, I tried to reproduce the issue on Windows 10, Chrome Version 91.0.4472.124 (Build officiel) (64 bits) with Demo Shop 1.7.7.5 and yet I didn't reproduce it, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/125646366-3937cde4-9227-4018-85a6-849da6d3400f.png)

Could you please try another photo (for exmple this one):

![image](https://user-images.githubusercontent.com/23308427/125646547-c74cfc17-74fa-4544-867d-cceaac04b83c.png)

Please check and feedback.
Thanks!

**Comment by didi-2018** [comment]
@hibatallahAouadni I made a Windows Update and it is working again.

**Comment by hibatallahAouadni** [comment]
Hooray :woman_dancing: :tada: 
So, I close the issue :wink:
