### ISSUE TITLE
Custom field is not updating using order webservice

### ISSUE THREAD

**Issue by PrajapatiDhara1510** [PrestaShop/PrestaShop#25349]
#### Describe the bug

I have added one custom field in ps_orders table 'total_seat_price'. I have overridden the Order.php from the `classes/order/Order.php` and added it to `override/classes/order/Order.php`.

```
class Order extends OrderCore
{
  /**
     * @var int Round type method used for this order
     */
    public $total_seat_price;

   [...]
            'total_seat_price' =>array('type' => self::TYPE_FLOAT),                                  
   [...]
}
```

When I print the XML object I get the total_seat_price into it but when I create an order and passing `total_seat_price`, the value is not updating. 

```
$xmlSchema = Prestashop::getSchema('orders');
print_r($xmlSchema);
```

#### Expected behavior

It should update the value which is passed in the webservice object. 

**Screenshots**

![image](https://user-images.githubusercontent.com/14217908/125620322-1a6bac16-cdda-40f6-96cb-8e19ca3985c4.png)
![image](https://user-images.githubusercontent.com/14217908/125620417-bb839b13-eb38-480c-9040-151afa315136.png)

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @dhara15101991 

Could you please provide a clear and concise steps or a test module to reproduce the issue.
Please check and feedback.

Thanks!

**Comment by PrajapatiDhara1510** [comment]
Hello @hibatallahAouadni 

As I mentioned I added custom field to the ps_orders table. I am creating order using webservice, I overridden the Order file as mention above and added custom field. When I am passing field it is not updating to the table. I want to update that custom field via webservice when order created. But it is not working at all.

**Comment by khouloudbelguith** [comment]
Hi @dhara15101991,

Thanks for your feedback.
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have
questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).
I will close the issue, feel free to create a new one when needed.

Thanks!
