### ISSUE TITLE
Error on Installation 1.7.7.5 ps_metrics1: Cannot install module "ps_metrics"

### ISSUE THREAD

**Issue by noobookbig** [PrestaShop/PrestaShop#25345]
#### Describe the bug

An error occurred during installation...
You can use the links on the left column to go back to the previous steps, or restart the installation process by clicking here.

ps_metrics1: Cannot install module "ps_metrics"

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1.Start installation
2. See error on Install Add on module 

An error occurred during installation...
You can use the links on the left column to go back to the previous steps, or restart the installation process by clicking here.

ps_metrics1: Cannot install module "ps_metrics"

**Screenshots**

![Capture](https://user-images.githubusercontent.com/12130745/125553254-2ddb5597-2804-4c40-b00f-6bd7484416c3.JPG)

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: 7.3.27

**Comment by hibatallahAouadni** [comment]
Hello @noobookbig 

That issue has been fixed and it's not related to the PS Core, it's related to Addons API (see the issue #25191).
Well, I try to install PS1775, and I didn't manage to reproduce your issue, see the attached screen record below:

https://drive.google.com/file/d/1maFTK98tK68Fi1MBeI14F1QFGY_uxMvw/view

Please check and feedback.
Thanks!

**Comment by ghost** [comment]
I reproduce this day it's random

**Comment by matks** [comment]
We believe in certain conditions (network condition, process length time condition) the install can fail. A huge improvement to lighten the install process of ps_metrics is scheduled to happen by the Extension team (and will be applied to ps_facebook additionnally), this should fix the situation for good.

**Comment by khouloudbelguith** [comment]
Hi @noobookbig,

Sorry to tell you that this issue is not related to the Core but to Addons.
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project.

Thanks for your understanding!
I close the issue, feel free to create a new one when needed.

Thanks!
