### ISSUE TITLE
BO - Actions (Install - Uninstall - Disable - Enable - Reset) are NOK - You have requested a non-existent service "templating

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25340]
#### Describe the bug

In the Module Catalog / Module manager page, when we try to Install - Uninstall - Disable - Enable - Reset a module, an error 500 is displayed and an alert "Could not perform action xxx for module undefined" is displayed

#### Steps to Reproduce

1. Go to BO > Modules > Module Catalog > Try to install a module
2. See error 
![image](https://user-images.githubusercontent.com/16067358/125462710-684b5ef9-0dc9-4704-8cf5-b1caf2099f00.png)
3. Go to BO > Modules > Module Manager page 
4. search the module just installed => well installed
5. Try Uninstall - Disable - Enable - Reset any module
6. See error

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by CanManftw** [comment]
Has this issue been solved? I'm actually having a similar issue right now with the Professional Invoice Payment module by buy-addons. Let me know how you fixed this.
