### ISSUE TITLE
Cannot edit email on guest accounts

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#25355]
✔️ PR available: https://github.com/PrestaShop/PrestaShop/pull/25356 ✔️

#### Describe the bug

There is a customer with an email **john.doe@email.com**.
There can be thousands of guest accounts with the same email.
There can be only one registered customer with the same email.

You go edit one of the guest accounts.
You add a letter to the end of the email and save it.
You go edit it again, remove that letter, but cannot save it, because there exists a registed customer with that email - WRONG.
You cannot set it to that email, even if other thousand guest accounts can exist just fine.

#### Expected behavior

**If the customer is a guest** (important), you should set the email to whatever you want to.
It should only raise this error, if you edit a registered customer. There cannot be two registered customers with the same email.

#### Steps to Reproduce

1. Make a guest account.
2. Make a registered account with the same email.
3. Edit the guest account and change the email to something.
4. Go edit the guest account again and try to change it back to what it was.

#### Additional information

* PrestaShop version: develop

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

I reproduce the issue with PS1767, PS1775 and develop. 
I think this issue will be fixed/gone when this issue #14414 is fixed.

Ping @marionf wdyt?

**Comment by Hlavtox** [comment]
@hibatallahAouadni Well I fixed it, so I guess it has nothing to do with that issue... 🤣🤣

And that issue deals with converting guest in FO, in BO the converting works.
