### ISSUE TITLE
The /usr/sbin/sendmail library does not work

### ISSUE THREAD

**Issue by ewonta** [PrestaShop/PrestaShop#25359]
#### Describe the bug

Sending mail via the /usr/sbin/sendmail library does not work with the configuration flag in the
/vendor/swiftmailer/swiftmailer/lib/classes/Swift/SendmailTransport.php file:23
'/usr/sbin/sendmail -bs'

If you change the flag to '/usr/sbin/sendmail -t'

Then the mail is sent without an error.

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @dmitrij1988 

Could you please provide steps to reproduce and some screenshots or a screen reocrd.
Please feedback.

Thanks!

**Comment by dmitrij1988** [comment]
The result is a 504 error after a long download.

Try to register on our demo store 
http://ewonta.ru/demo/themes/01PS24Theme/

I have set the default flag.

Write how to try it I will put a working configuration

**Comment by matks** [comment]
Hello @dmitrij1988 the class SendmailTransport is inside vendor https://github.com/swiftmailer/swiftmailer

We rely on Swiftmailer for mail sending, but we cannot modify their code. You might want to report the issue upstream to https://github.com/swiftmailer/swiftmailer to get it patched
