### ISSUE TITLE
CAN'T place new order as guest if You already placed order in the same shop as guest/registered customer

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#25351]
Dear PrestaShop team.

Many of Customers don't want to register, but want to place orders as Guests.
In current version and a several previous versions on the past, we cant place new order as guest if previously orders was placed on the same store https://github.com/PrestaShop/PrestaShop/issues/10306

Its been THREE years and issue is marginalized. 

Please rise priority for this and let's team found solution for this issue.

Thanks

**Comment by hibatallahAouadni** [comment]
Dear @PrestaShark 

As you know we only accept the issue respecting and following the provided template to submit a complete bug report.
As I can see, you create this issue to remind our Teams about this issue #10306
But I already answered you https://github.com/PrestaShop/PrestaShop/issues/10122#issuecomment-874669663

So, please next time just ping the Developer Team in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Sorry but I have to close this issue :pray: 

Thanks for understanding :relaxed:
