### ISSUE TITLE
Can not accept terms and conditions

### ISSUE THREAD

**Issue by Celeanmode** [PrestaShop/PrestaShop#25368]
#### Describe the bug

Hi, i am installing prestashop and when i accept the terms and conditions, the next button appear but when i click on next it just stays on the page and i need to click on the accept button again every single time. So i am kind of stuck in the installation right now.

#### Expected behavior

Normally when you accept and click on next you go to the next step what would be checking compatibility. So as said before i can click next but it just doesn't go to the next step.

#### Additional information

* PrestaShop version: 1.7.7.5

**Comment by hibatallahAouadni** [comment]
Hello @Celeanmode 

Could you please provide some screenshots or a screen record 🙏 
Waiting for your feedback.

Thanks!

**Comment by Celeanmode** [comment]
Hello, Attached to this mail a screenshot, so when i click on next it just stays on this page and i need to click on accept again but it just doesn’t go to the next step. Kind regards, Sarah CarluBaron de Gieylaan 45/0019840 De Pinte 0468 59 63 40 Openingsuren:Maandag – woensdag: 10u – 18uVrijdag – zaterdag: 10u – 18uDonderdag en zondag: Gesloten Van: Hibatallah AouadniVerzonden: maandag 19 juli 2021 7:57Aan: PrestaShop/PrestaShopCC: Celeanmode; MentionOnderwerp: Re: [PrestaShop/PrestaShop] Can not accept terms and conditions (#25368) Hello @CeleanmodeCould you please provide some screenshots or a screen record 🙏Waiting for your feedback.Thanks!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.  
	
      
		Virusvrij. www.avast.com

**Comment by florine2623** [comment]
Hello @Celeanmode ,

Please answer directly via GitHub or else we can't read your messages properly.

Thanks

**Comment by Celeanmode** [comment]
> Hello @Celeanmode
> 
> Could you please provide some screenshots or a screen record 🙏
> Waiting for your feedback.
> 
> Thanks!

Here the printscreens of the problem
![2021-07-19 (2)](https://user-images.githubusercontent.com/87571387/126293663-0e355139-ac56-42d7-b958-6fa85d566a86.png)
![2021-07-19 (3)](https://user-images.githubusercontent.com/87571387/126293707-6a43e6b2-9f8d-406e-ac40-08761a9b14ff.png)

**Comment by florine2623** [comment]
Hello @Celeanmode ,

In your 2nd screen, you already accepted the terms & conditions.

You need to click Volgende to go to next step.
Please check my screen record :
https://drive.google.com/file/d/1Cxrj3iuF3DWMyEiASrmPfRVMw93BQifT/view

**Comment by Celeanmode** [comment]
> Hello @Celeanmode ,
> 
> In your 2nd screen, you already accepted the terms & conditions.
> 
> You need to click Volgende to go to next step.
> Please check my screen record :
> https://drive.google.com/file/d/1Cxrj3iuF3DWMyEiASrmPfRVMw93BQifT/view

Hello FLorine2623,
I know but that is the problem when I click on Volgende it just blanks the page it does not go to the next step. If i click on Volgende it gives me again the same page

**Comment by florine2623** [comment]
Can you add this [file](https://github.com/PrestaShop/php-ps-info/) to the root of your FTP and see if your server config is compatible.
More info on server system requirements here : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Let me know the result.

**Comment by Celeanmode** [comment]
> Can you add this [file](https://github.com/PrestaShop/php-ps-info/) to the root of your FTP and see if your server config is compatible.
> More info on server system requirements here : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
> 
> Let me know the result.

Hi,

Just tried but it is still the same

**Comment by florine2623** [comment]
Have you checked the config of your server ? is it compatible ?
can you send a screenshot of the result ?

**Comment by Celeanmode** [comment]
> Have you checked the config of your server ? is it compatible ?
> can you send a screenshot of the result ?

Hi,

I have a PHP 7.4 so that should be good.
It just seems to get stuck, I tried installing it again, tried on different browsers like Chrome, Avast security browser, Microsoft edge... But every time the same problem :(

**Comment by florine2623** [comment]
You need to use PHP 7.3 with PS 1.7.7.5 :
<img width="756" alt="Screenshot 2021-07-23 at 14 32 57" src="https://user-images.githubusercontent.com/16019289/126782130-c90cebd6-46b6-4c99-971e-78bf2e3c5aa6.png">

**Comment by Celeanmode** [comment]
> You need to use PHP 7.3 with PS 1.7.7.5 :
> <img alt="Screenshot 2021-07-23 at 14 32 57" width="756" src="https://user-images.githubusercontent.com/16019289/126782130-c90cebd6-46b6-4c99-971e-78bf2e3c5aa6.png">

Hi,

I adjusted the PHP to 7.3. But still face the same problem

**Comment by florine2623** [comment]
Hello @Celeanmode ,

Please go [here](https://www.prestashop.com/en/versions), download a stable version and reinstall your store.
Make sure to delete all files and content of your databse before.

If you still can't do it, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

I'll close your issue as I can't reproduce it.
Thank you
