### ISSUE TITLE
BO - View an order - Search endpoint returns HTTP 500 when 

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#25360]
#### Describe the bug

When Search endpoint `/admin-dev/index.php/sell/orders/products/search?search_phrase=&currency_id=YYY&order_id=ZZZ&_token=AAA` is hit with empty GET parameter `search_phrase` it returns an HTTP response whose status is 500, and the response contains error message "Product search phrase must be a not empty string"

This is a trivial issue with no impact for merchant. It just does not look good.

#### Expected behavior

Search endpoint should return something different than 500, this is not a server error. Maybe a 400.

#### Steps to Reproduce

1. Go to Back Office, open an Order to view it
2. Open Chrome developer tools, open Network tab
3. Click 'Add a product'
4. Start typing something in the product field: you can see in the Network tab that a HTTP query is sent to `/admin-dev/index.php/sell/orders/products/search?search_phrase=XXX&currency_id=YYY&order_id=ZZZ&_token=AAA` and you get a HTTP 200 response
5. Clear the search product field: you can see in the Network tab that a HTTP query is sent to `/admin-dev/index.php/sell/orders/products/search?search_phrase=&currency_id=YYY&order_id=ZZZ&_token=AAA` and you get a HTTP 500 response (`search_phrase` GET parameter is empty)
6. You can also simply browse the URL `/admin-dev/index.php/sell/orders/products/search?search_phrase=&currency_id=YYY&order_id=ZZZ&_token=AAA` and see HTTP status 500, and the response contains error message "Product search phrase must be a not empty string"

#### Additional information

* PrestaShop version: 1.7.8.x
* PHP version: 7.4

**Comment by matks** [comment]
![Capture d’écran 2021-07-15 à 15 42 14](https://user-images.githubusercontent.com/3830050/125799151-abd31c4c-3178-440d-8b09-5bc0479d2856.png)
![Capture d’écran 2021-07-15 à 15 42 16](https://user-images.githubusercontent.com/3830050/125799164-6748dee1-5a48-42f2-9c04-92fabcf2dfc1.png)

**Comment by khouloudbelguith** [comment]
Hi @matks,

I manage to reproduce the issue with PS1775 and 1.7.8.x branch.
In the PS1769 => OK
https://drive.google.com/file/d/1qTTnaJ4YjwQCykrBsRtzJqyBkPM5zvnD/view?usp=sharing
I'll add this to the debug backlog so that it's fixed.

Thanks!

**Comment by Progi1984** [comment]
Fixed in this PR #25378

**Comment by Progi1984** [comment]
Fixed in #25378 by @Progi1984
