### ISSUE TITLE
BO - Order message not in order language

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#25362]
#### Describe the bug

In BO > Order details, the language of the order messages are in the last language used by the customer, not in the language of the order.
For example, if User make an order in French, then another one in English, on both orders, the messages will be in English.

In 1.7.6, the first order was in French, the second one in English.

#### Expected behavior

Order messages should be in order language.

#### Steps to Reproduce

1. Go to FO > Change language to French
2. Make an order (Order n°1)
3. Go to BO > Order n°1 Details > Check order message language : It's in French :heavy_check_mark: 
4. Go to FO > Change language to English
5. Make an order (Order n°2)
6. Go to BO > Order n°2 Details > Check order message language : It's in English :heavy_check_mark: 
7. Go to BO > Order n°1 Details > Check order message language : It's in English :red_circle: : It should be in French. 

**Screenshots**

See screenrecord (at 00:45 : The order message is in English even if the order was made in French)
https://drive.google.com/file/d/1GmimwejOHJY9RiFOEgJakiT6d88WrvlT/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

**Comment by Progi1984** [comment]
Fixed by @Progi1984 in #25375
