### ISSUE TITLE
Orders products in order

### ISSUE THREAD

**Issue by facuzapata** [PrestaShop/PrestaShop#25366]
Hello everybody!

I need to sort the products by categories in the order section, but I can't find a hook that performs such an action.

I have found a for in product_list.html.twig with the orderForViewing parameter but it does not include their categories in the products.

Can you add?

![image](https://user-images.githubusercontent.com/42452536/125869342-9ec51091-7f95-40a8-bd62-c6d4dea7d6ec.png)
![image](https://user-images.githubusercontent.com/42452536/125869363-feef4a34-f4ca-4469-a97f-ebced8a5a9c6.png)

**Comment by khouloudbelguith** [comment]
Hi @facuzapata,

Thanks for the issue.
On this github repository there is no software support. This is an open-source project.
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have
questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you!
