### ISSUE TITLE
FO: Product image size doesn't match the size in the product object 

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#25363]
#### Describe the bug

In the front office, the small / medium / large product image size doesn't match the sizes we get from the product object

Large => 458  => `/3-large_default/affiche-encadree-the-best-is-yet-to-come.jpg`
Medium => 125 => `/3-medium_default/affiche-encadree-the-best-is-yet-to-come.jpg`

Large => 800  => `{$product.large_image.bySize.large_default.width}`
Medium => 452 => `{$product.medium_image.bySize.medium_default.width}`

Small size seems to be 98 in both case.

#### Expected behavior

Sizes should match

#### Steps to Reproduce
A dev can display a product page in the front office, then play with sizes in `themes/classic/templates/catalog/_partials/product-cover-thumbnails.tpl` and see that medium or large sizes won't give the same size on the image or on the value taken from `$product.default_image.bySize` 

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.8

**Comment by Hlavtox** [comment]
@matthieu-rolland @hibatallahAouadni I think it's the correct behavior. Look at the code: https://github.com/PrestaShop/PrestaShop/blob/32742483dba196af69e589b878cdf3c534a737f1/src/Adapter/Image/ImageRetriever.php#L228

- In **bySize**, you have all the resolutions and sizes.
- When getting the **small**, **medium** and **large** images. _(I don't know where they are used though, I always use bySize.large_default etc.)_ It takes the list of all sizes, sorts them by resolution and then:
  - Takes the smallest for small.
  - Takes the largest for large.
  - Divides them in half, rounds it and takes the middle image. It does not have to necessarily be **medium_default**.
  - If you for example delete **small_default**, then the smallest size will be **cart_default**.

**Comment by MatShir** [comment]
Hi @matthieu-rolland,
Can you explicit the issue here please ? I'm not sure to understand it

**Comment by hibatallahAouadni** [comment]
Hello @matthieu-rolland 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
