### ISSUE TITLE
BO visual issue on list of products filter by id too wide

### ISSUE THREAD

**Issue by RubenMartins** [PrestaShop/PrestaShop#25361]
#### Describe the bug

Visual bug on showing to the filter of ids too wide taking a lot of width space in the list of products.

#### Expected behaviour

The fields should be the same restricted width of Price or Quantity that still allows to search between X numbers/values but taking just enough space

#### Steps to Reproduce

1. Go to the Backoffice -> Catalog -> Products
2. See visual bug error on the list

This can be reproduced on a new store or on the online demo at: https://demo.prestashop.com/#/en/back

**Screenshots**

![image](https://user-images.githubusercontent.com/5765731/125798898-cc85290a-bcca-48cd-b541-e5ada5ef35b7.png)

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: 7.4

**Comment by hibatallahAouadni** [comment]
Hello @RubenMartins 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #24915. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #24915

**Comment by RubenMartins** [comment]
@hibatallahAouadni thank you 😃
