### ISSUE TITLE
Getting Error in Prestashop 1.7.7.1 Order page after upgraded from 1.7.5.1

### ISSUE THREAD

**Issue by Jeevachezhiyan** [PrestaShop/PrestaShop#25369]
#### Describe the bug

I did upgrade from 1.7.5  to 1.7.7. Upgrade is done. But getting error while opening the order page.

#### Expected behavior

Error: 

```
(1/1) FatalThrowableErrorUndefined class constant 'Doctrine\Common\Collections\Expr\Comparison::STARTS_WITH'
--
in UnitOfWork.php line 3114
at UnitOfWork->getEntityPersister('PrestaShopBundle\\Entity\\AdminFilter')in EntityRepository.php line 191
at EntityRepository->findOneBy(array('employee' => 1, 'shop' => 1, 'filterId' => 'order'))in AdminFilterRepository.php line 69
at AdminFilterRepository->findByEmployeeAndFilterId(1, 1, 'order')in RepositoryFiltersBuilder.php line 74
at RepositoryFiltersBuilder->getParametersFromRepository('order')in RepositoryFiltersBuilder.php line 49
at RepositoryFiltersBuilder->buildFilters(object(OrderFilters))in ChainedFiltersBuilder.php line 80
at ChainedFiltersBuilder->buildFilters()in FiltersBuilderResolver.php line 70
at FiltersBuilderResolver->resolve(object(Request), object(ArgumentMetadata))in ArgumentResolver.php line 62
at ArgumentResolver->getArguments(object(Request), array(object(OrderController), 'indexAction'))in TraceableArgumentResolver.php line 38
at TraceableArgumentResolver->getArguments(object(Request), array(object(OrderController), 'indexAction'))in HttpKernel.php line 143
at HttpKernel->handleRaw(object(Request), 1)in HttpKernel.php line 68
at HttpKernel->handle(object(Request), 1, false)in Kernel.php line 200
at Kernel->handle(object(Request), 1, false)in index.php line 88

```

#### Steps to Reproduce

Order page must open without any errors.

1. Go to 'Orders'
2. Click on 'Click orders'

Screenshot:
![Screenshot](https://user-images.githubusercontent.com/17176348/126057159-0554bbe1-1b73-4ec2-86c4-0c39c785768f.png)

https://prnt.sc/1cio5e7

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @Jeevachezhiyan 

Could you please try to rebuild all your index and clear cache.
Please check and feedback.

Thanks!

**Comment by Jeevachezhiyan** [comment]
@hibatallahAouadni I tried to rebuild the index and cache clean. Still the issue is there.

**Comment by florine2623** [comment]
Hello @Jeevachezhiyan ,

Can you check your PHP version ?
It needs to be 7.1 to 7.3 for PS 1.7.7.1

More info on the system requirements here : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Jeevachezhiyan 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by Jeevachezhiyan** [comment]
Hi Team,

I fixed this issue by deleting the auto-upgrade module. 

Thanks

**Comment by hibatallahAouadni** [comment]
Thanks for the tip :wink: 
I hope it helps someone :relaxed:
