### ISSUE TITLE
Bug in module ps_facetedsearch (_mobile_search_filters_clear_all)

### ISSUE THREAD

**Issue by SLIVERPOOLS** [PrestaShop/PrestaShop#25376]
Can someone help?
I found bug in the module ps_facetedsearch (it appears exclusively - on the mobile version)
Prestashop 1.7.7.4
ps_facetedsearch v3.7.1

Details:
On desktop version of site, when you mark some characteristic in the filter, the page is reloaded and the (clear all) button appears: http://joxi.net/bmoRJYdC7ljwGr . With this button you can clear ALL filter marks.
When you click this button: http://joxi.net/Dr8aP31cJDplpm , the page reloaded, ALL filter uncheck, and button disappear: http://joxi.net/1A5LGZ1tzwZEV2
All works well

But in module version of site, when you mark some characteristic in the filter, the page is reloaded and the (clear all) button WILL NOT APPEARS: http://joxi.net/52aXBnyHg0WnBm

If I watch code of the place — where must be button:
I will see the id="_mobile_search_filters_clear_all"
But with no code of the button itself:
http://joxi.net/RmzBoY5CjVdlym

Further, if I refresh the page (Сtrl+R) — the button WILL APPEARS!
http://joxi.net/vAWWOlMFBRyLxA
And in the opposite direction,
When you click this button on mobile: http://joxi.net/Y2LlQe4UMv8oz2 , the page reloaded, ALL filter uncheck, but button WILL NOT DISAPPEAR.
To make her disappear, you need to refresh the page manually (Сtrl+R):

Maybe it's a cache problem or something like that?
Thanks for any help

**Comment by hibatallahAouadni** [comment]
Hello @SLIVERPOOLS 

Yes, apparently it's a cache problem.
Sorry but I have to close the issue cause we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

PS: next time when you encounter some weird behavior like this one ask on public Slack, the contributors or one of us will answer your questions 😉 

Thank you
