### ISSUE TITLE
Product structured data json-ld problem when price is not displayed

### ISSUE THREAD

**Issue by Oksydan** [PrestaShop/PrestaShop#25371]
#### Describe the bug

If product price is not displayed json format is wrong due to trailing comma at the end of list.

#### Expected behavior

Json format should be always valid. 
I think we should move that data into associative array and just use `json_encode` in smarty to make sure that data will contain proper json format. 
Second solution could be to move whole structured data into frontController/productController and just output associative array to template.

#### Steps to Reproduce

1. Go to product page for example **Hummingbird printed sweater**.
2. Check in browser product structured data find in browser dev tools `"@type": "Product"`.
3. You can copy it and check in https://search.google.com/structured-data/testing-tool data should be valid.
4. Go to BO and disable show price for that product.
5. Go back to product page refresh and check product structure data again. It should contain trailing comma and check in google structured data testing tool should fail. 

#### Additional information

* PrestaShop version: 1.7.8 beta
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @Oksydan 

Could you please check these issues #22416 & #21927 cause it seems similar to yours.
Please check and feedback.

Thanks!

**Comment by Oksydan** [comment]
Hi @hibatallahAouadni 

Issue is not related to issues listed above. 
Since json-ld structured data was implemented in prestashop 1.7.8, issue is related to latest new feature.

**Comment by florine2623** [comment]
Hello @Oksydan ,

I managed to reproduce the issue in PS 1.7.8.X and develop :

In product page - no error just warnings :
<img width="1420" alt="Screenshot 2021-07-20 at 12 24 57" src="https://user-images.githubusercontent.com/16019289/126308832-58775b20-b618-49ed-9aac-253ab18d9bcc.png">


With these options - 1 error :
<img width="598" alt="Screenshot 2021-07-20 at 12 25 38" src="https://user-images.githubusercontent.com/16019289/126308796-80e6ec01-0870-4924-ab6e-2cd5e2eddb78.png">

<img width="1433" alt="Screenshot 2021-07-20 at 12 25 04" src="https://user-images.githubusercontent.com/16019289/126308734-2565f33f-cdf6-4d4c-8f5b-a8c615c5c0aa.png">

Can you confirm this is the bug ?

**Comment by Oksydan** [comment]
Hi @florine2623,
Yes, it is exactly what I reported.

**Comment by hibatallahAouadni** [comment]
FYI: as this data is a new feature, so it's a bug and not a regression!

**Comment by Progi1984** [comment]
Fixed by @Progi1984 in #25524
