### ISSUE TITLE
Page display problem after installing developer version 1.7.8.0

### ISSUE THREAD

**Issue by DrVallo** [PrestaShop/PrestaShop#25370]
#### Describe the bug

After completing the local installation of the development version of Prestashop (version 1.7.8.0) following the guide in the [official documentation]( https://devdocs.prestashop.com/1.7/themes/getting-started/setting-up-your-local-environment/) of PS, it seems that the .css files are missing. This is causing problems with the display of the BO and an error in the FO. I'm not very sure, but it looks like the "assets" folder containing the css and js files is missing, which is causing the problem.

#### Steps to Reproduce

1. Cerate new folder on VS Code and open terminal
2. Run `git clone https://github.com/PrestaShop/PrestaShop.git`
3. Run `composer install`
4. Run the PS installation (example: http://localhost/PrestaShop )
5. See error

**Screenshots**

FO:
![screen 1a](https://user-images.githubusercontent.com/50541389/126080501-45d15d69-3c64-466e-b2b6-7932e0ec610d.png)

BO:
![screen 1](https://user-images.githubusercontent.com/50541389/126080502-34646e2a-7914-44a6-aed8-d83d74abb52b.png)

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.4.21

**Comment by hibatallahAouadni** [comment]
Hello @DrVallo 

You need to execute this command just after `composer install`:

`make install`

To install all your assets 😉 

Closing this issue cause it's not a PS Core issue.

Thanks!

**Comment by DrVallo** [comment]
Hi @hibatallahAouadni ,
thanks for your reply.
I tried to follow your suggestion, but the `make install` command seems not to be recognized.

```
make : Termine 'make' non riconosciuto come nome di cmdlet, funzione, programma eseguibile o file script. Controllare l'ortografia del nome o verificare che il percorso sia incluso e corretto, quindi riprovare.
In riga:1 car:1
+ make install
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (make:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Can you tell me why? Am I doing something wrong in the installation, or is there a problem in the development version 1.7.8.0 of PS?

**Comment by hibatallahAouadni** [comment]
Hello @DrVallo 

Could you please try this command under your project, to know in which branch you are:
`git branch`
Then:
`git status`
To know if there's modifications. If you found some modif, try this command:
`git stash`
Or:
`git checkout .`
Now, try again:
```
git pull origin develop
git status
composer install
make install
```

Please check and feedback.
Thanks!

**Comment by DrVallo** [comment]
Hi, @hibatallahAouadni ,
this is a result, but `make` still not working:
```
PS C:\laragon\www\negozio\PrestaShop> git branch      
* develop
PS C:\laragon\www\negozio\PrestaShop> git status
On branch develop
Your branch is up to date with 'origin/develop'.

nothing to commit, working tree clean
PS C:\laragon\www\negozio\PrestaShop> git stash
No local changes to save


PS C:\laragon\www\negozio\PrestaShop> composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
63 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
PS C:\laragon\www\negozio\PrestaShop> make install
make : Termine 'make' non riconosciuto come nome di cmdlet, funzione, programma eseguibile o file script. Controllare l'ortografia del nome o verificare che il percorso sia incluso e corretto, quindi riprovare.
In riga:1 car:1
+ make install
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (make:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Thanks again for your support!

**Comment by DrVallo** [comment]
> Hello @DrVallo
> 
> Could you please try this command under your project, to know in which branch you are:
> `git branch`
> Then:
> `git status`
> To know if there's modifications. If you found some modif, try this command:
> `git stash`
> Or:
> `git checkout .`
> Now, try again:
> 
> ```
> git pull origin develop
> git status
> composer install
> make install
> ```
> 
> Please check and feedback.
> Thanks!

Hi @hibatallahAouadni  ,
sorry for posting again in this closed report, but unfortunately I still have not been able to solve my problem.
I would like to understand if I am doing something wrong, or if there is a bug in the latest developer version of PS.

**Comment by DrVallo** [comment]
> Hello @DrVallo
> 
> Could you please try this command under your project, to know in which branch you are:
> `git branch`
> Then:
> `git status`
> To know if there's modifications. If you found some modif, try this command:
> `git stash`
> Or:
> `git checkout .`
> Now, try again:
> 
> ```
> git pull origin develop
> git status
> composer install
> make install
> ```
> 
> Please check and feedback.
> Thanks!

Hi @hibatallahAouadni  ,
sorry for posting again in this closed report, but unfortunately I still have not been able to solve my problem.
I would like to understand if I am doing something wrong, or if there is a bug in the latest developer version of PS.

**Comment by hibatallahAouadni** [comment]
Hello @DrVallo 

There's no problem with develop branch! Everyone can execute the `make install` command successfully.

Could you please post your issue in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
