### ISSUE TITLE
Add a new Hook "BeforePayment"

### ISSUE THREAD

**Issue by abramofranchetti** [PrestaShop/PrestaShop#25382]
#### Problem:
As a prestashop developer I often find myself having to make procedure to checks on the products in the cart (ex stock) immediately before the customer starts the payment procedure (click on the pay button with paypal or bank transfer ..). 
These checks typically make instant checks on item availability using custom external API calls, and in case the item is no longer available redirects the user to an error page (ex: "we apologize but the item you have chosen is no longer  available") ecc.

Since there is no hooks like "just before payment" or "before payment", I am forced to make expensive customizations to each payment  module that the customer want to install on his Prestashop to intercept the event. 

#### Describe the solution you'd like

I would like a new standard hook "before payment" to be set up to intercept the click event before any of the payment buttons in the checkout, like for example "**actionCartUpdateQuantityBefore**".

#### Additional context

For example this feature is very important in the Fashion sector, where for example the last available dress of a collection can also be sold in the physical store, outside the context of prestashop, and therefore it is not enough to align the warehouse stocks with tasks scheduled but a "real-time" check is required at the time of purchase to ensure that the dress is still available at that precise moment of order payment.

**Comment by florine2623** [comment]
Hello @abramofranchetti ,

When you don't have any stock left of a product, you can choose **option Deny order** :
<img width="292" alt="Screenshot 2021-07-20 at 12 02 43" src="https://user-images.githubusercontent.com/16019289/126305210-b09c9462-73af-47e9-afdb-df8210884dfa.png">

As well as **not allowing out-of-stock products** :
<img width="393" alt="Screenshot 2021-07-20 at 12 03 09" src="https://user-images.githubusercontent.com/16019289/126305269-67958a46-4c05-49a0-9a71-d12b0d375948.png">

in the cart if the product is not available anymore, there will be a warning like so in the cart page :
<img width="396" alt="Screenshot 2021-07-20 at 12 05 16" src="https://user-images.githubusercontent.com/16019289/126305631-07be55c1-f8cd-46f5-9c12-f5c231e90702.png">

If the addition of the hook adds anything to these already existing features, could you specify them please ?

Thanks!

**Comment by abramofranchetti** [comment]
Hi, 
the problem is that typically the warehouse is managed in a management software (ERP) external to prestashop, and the stocks are synchronized daily (ex in a task during the nigth).What you need to do is check the actual availability in the external warehouse just before paying, i.e. by clicking on the card button credit in checkout.


But that's only an example. In general if you need to do something else "just before payment", at the current state of Prestashop there is not an hook that permit to implement your code in that point, because there is not hook "before payment".

In general it would be useful to have an hook "before payment" that "fire" in the moment the final customer click on the payment in the checkout.

**Comment by Matt75** [comment]
If you want to add event onclick on payment button, you can do it with JavaScript, make an Ajax call to a module controller to check your stock then dispatch standard payment button action

Add a hook will be difficult because it need to be implemented on each PaymentModule because many of them don't use the standard payment button. (Modules based on binaries or JavaScript components)

So it will be more reliable to add a custom event on your side with JavaScript on all button needed

**Comment by abramofranchetti** [comment]
@Matt75 yeah, it is what i'm doing now, but i was hoping that there was a chance to get a standard way to do that in the future version of prestashop.

**Comment by florine2623** [comment]
Hello @abramofranchetti ,
I'll ping Dev and Product Team to get the approval or not on your suggestion !

**Comment by florine2623** [comment]
ping @PrestaShop/prestashop-core-developers and @PrestaShop/product-team 

What do you think about @abramofranchetti 's suggestion ?

Thanks!

**Comment by tswfi** [comment]
https://github.com/PrestaShop/PrestaShop/pull/26048 somewhat related

**Comment by abramofranchetti** [comment]
> #26048 somewhat related

yeah definitely related.

**Comment by kpodemski** [comment]
It is something that has been added to PrestaShop 8.0
https://github.com/PrestaShop/PrestaShop/pull/26048
