### ISSUE TITLE
warning: proc_open() has been disabled for security reasons - prestashop 1.7.7.5

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#25380]
Hi
I get this problem in two websites with different hosting, both with prestashop 1.7.7.5 and both with php 7.3
with prestashop 1.7.6 with php 7.3 the problem is not present.

"warning: proc_open() has been disabled for security reasons"

#### Describe the bug

this error appears when I complete the order

#### Expected behavior

to finish the order normally like usual

#### Steps to Reproduce

create a normal order, the problem is a compatibility issue between 1.7.75 and some server security system

**Screenshots**
![image_2021_07_19T19_14_55_378Z](https://user-images.githubusercontent.com/653230/126216507-fb44159f-c091-434e-a6ff-426e3df4ac32.png)

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: 7.3

**Comment by Maofree** [comment]
the problem is solved from the hosting by activating the function
I think many guys will have this problem

**Comment by matks** [comment]
> the problem is solved from the hosting by activating the function
> I think many guys will have this problem

We could add a helpful warning message, "The email could not be sent because the function proc_open is disabled on your hosting environment" ?

Also, did you create an order from Front Office or Back Office ?

**Comment by Maofree** [comment]
Hi @matks 
the order was created in the front-office by a customer

**Comment by florine2623** [comment]
Hello @matks ,

Could you try to reproduce @maofree 's issue with proc_open function please ?
I can't do it on my server.

If that's reproducible, I'll ping PS product-team to have their approval for this warning message !

Thanks!

**Comment by Maofree** [comment]
hi
the problem appears when the proc_open is disabled into php.ini
in some hosting it is disabled by default in others no

**Comment by khouloudbelguith** [comment]
Hi @maofree,

I think this issue is similar to this ticket: https://github.com/PrestaShop/PrestaShop/issues/22262#issuecomment-795599209

What do you think?

Thanks!

**Comment by Maofree** [comment]
Hi
I think it is a different issue
however it is not a real bug, to fix it, it is necessary to remove from disabled functions of php.ini, it is not necessary to change other things

bye

**Comment by khouloudbelguith** [comment]
Hi @maofree,

Thanks for your feedback.
So it is a server issue?

Can I close this ticket?

Thanks!

**Comment by Maofree** [comment]
Hi
yes it is a server issue when that function is disabled from php.ini
this tpic can be useful to know how to fix this issue, asking to own hosting to active it

you can close

bye

**Comment by khouloudbelguith** [comment]
@maofree, thanks a lot.
I close the issue, feel free to open a new one when needed.

Thanks!

**Comment by 2zalab** [comment]
I also encountered the same problems. I'm trying to find a solution but I can't.
<img width="947" alt="Capture d’écran 2022-07-15 110714" src="https://user-images.githubusercontent.com/62522441/179202580-f23a4ce1-aa4d-401f-9858-b617288bb7d8.png">

**Comment by Ettalebmed** [comment]
@Touza-Isaac  did you resolve the problem ?

**Comment by kpodemski** [comment]
You can contact your hosting provider or configure sending emails via SMTP
