### ISSUE TITLE
Changing the URL after selecting the combination for the PrestaShop product 1.7.5.5

### ISSUE THREAD

**Issue by farzadaaa** [PrestaShop/PrestaShop#25385]
Hello, on my site, which is version 1.7.5.5, when I add a combination for the product, the product URL changes and the combination URL is added to it, for example:
https://iran-memory.ir/product/1613-internal-ssd-adata-su800-512gb.html
How can this problem be solved?
[خرید هارد اکسترنال](https://iran-memory.ir/category/16-external-hard-drive)
for example:
https://iran-memory.ir/brand/21-western-digital

**Comment by florine2623** [comment]
Hello @farzadaaa ,

Please edit your issue to follow the issue template.
<img width="602" alt="Screenshot 2021-07-20 at 15 33 36" src="https://user-images.githubusercontent.com/16019289/126333072-76504822-c5cb-49ca-ab5b-52559aeaaa59.png">

Do you mean 1.7.7.5 ?
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @farzadaaa 


Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
