### ISSUE TITLE
Invalid $number parameter: ... cannot be interpreted as a number (when i generate invoice pdf)

### ISSUE THREAD

**Issue by ShaimyWinda** [PrestaShop/PrestaShop#25383]
#### Describe the bug

Hello,

When I generate an invoice for an order with many products, I get this error

![image](https://user-images.githubusercontent.com/25744417/126297164-6f769a46-0938-4818-b141-5087e30f22f3.png)

can you help me ?

Thanks

* PrestaShop version: 1.7.7.2
* PHP version: 7.2

**Comment by florine2623** [comment]
Hello @ShaimyWinda ,

Please share the steps of reproduction so we can try to reproduce the error.

Thanks!

**Comment by ShaimyWinda** [comment]
Hello @florine2623 

I think I understand. In fact on our site, we have a feature that has been developed, so it's related to the products that we have developed.

**Comment by florine2623** [comment]
Ok, thanks for updating the issue.
I'll close it as it is regarding a specific development.
Thanks!
