### ISSUE TITLE
Dashboard display issues after 1 click upgrade

### ISSUE THREAD

**Issue by danpetrean** [PrestaShop/PrestaShop#25390]
I made an update with 1 click upgrade from version 1732 to 1775 and when logging in it apears like this 

![printscreen1](https://user-images.githubusercontent.com/87751543/126449719-962fe809-a986-4a47-9b33-
6e18e1521693.png)
![printscreen2](https://user-images.githubusercontent.com/87751543/126449859-836aec20-07b2-4bf8-bbef-405a99f961d1.png)

![printscreen1](https://user-images.githubusercontent.com/87751543/126449719-962fe809-a986-4a47-9b33-
6e18e1521693.png)
****************************
DO NOT disclose security issues here, contact security@prestashop.com instead!
****************************
-->

#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by florine2623** [comment]
Hello @danpetrean ,

What version of PHP are you using ?
Make sure your config is compatible with your newest version of PrestaShop. You will find more info here : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
Thanks!

**Comment by danpetrean** [comment]
7.1.33

**Comment by danpetrean** [comment]
Hello florine,

 

Dashboard dos not display correctcly, but the ordrer module work.

printing an order is not formatted correctly.

thanks

**Comment by florine2623** [comment]
Hello @danpetrean ,

Please answer directly via GitHub. If not the messages are not clear.

I used the module 1-click upgrade from PS 1.7.3.2 to PS 1.7.7.5. **The menu is correct** :
Upgrade ongoing :
<img width="1230" alt="Screenshot 2021-07-21 at 14 07 40" src="https://user-images.githubusercontent.com/16019289/126486920-def66f9e-7a70-4ca8-9de6-ee494660a247.png">
Upgrade done :
<img width="1197" alt="Screenshot 2021-07-21 at 14 11 48" src="https://user-images.githubusercontent.com/16019289/126486931-0ad317c9-37e4-4d83-b2e9-7b9602e26120.png">
Result after refreshing and logging into the BO :
<img width="1435" alt="Screenshot 2021-07-21 at 14 12 18" src="https://user-images.githubusercontent.com/16019289/126486936-d8233900-6c4e-4e9b-862a-d06560835e30.png">

Please check if you have any errors in the log file.

**Comment by danpetrean** [comment]
my dashboard its look like a string of words.
![printscreen1](https://user-images.githubusercontent.com/87751543/126530333-f34777d2-51a5-48ef-9dc8-6a07b87b733a.png)
![PRINTSCRREN2](https://user-images.githubusercontent.com/87751543/126530377-672105df-1dfa-41c5-80e4-cbedbbe566a9.png)
![printscreen3](https://user-images.githubusercontent.com/87751543/126530395-10318226-f8a7-4e0f-b9e8-a4222d877012.png)
![printscreen4](https://user-images.githubusercontent.com/87751543/126530407-38e62d55-9069-49ae-91ba-30ae33ee07b1.png)
![printscreen5](https://user-images.githubusercontent.com/87751543/126530418-5cc29d86-c5ef-449e-822b-c706eb26001d.png)
[Comanda #1920 LAVLIDYFR.pdf](https://github.com/PrestaShop/PrestaShop/files/6857616/Comanda.1920.LAVLIDYFR.pdf)

**Comment by danpetrean** [comment]
this is what the listing of an order looks like
[Comanda #1920 LAVLIDYFR.pdf](https://github.com/PrestaShop/PrestaShop/files/6857672/Comanda.1920.LAVLIDYFR.pdf)
tell me what information to give you so I can solve the problem

**Comment by danpetrean** [comment]
before the update i had md5 error and i proceeded as in the tutorial

**Comment by florine2623** [comment]
Hello @danpetrean ,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

We will close this issue.

Thank you

**Comment by danpetrean** [comment]
in the admin123 directory the index.php file is generated properly which means that the css files are called properly, but there is a file that overwrites their access rules. This is manifested only at this level of director.
in the lower directories for example: admin123 \ sell \ orders \ .... works properly.
can you help me to identify the file that generates the error in the admin123 directory?

**Comment by florine2623** [comment]
You need to contact the support team for that or check on the forum.
As I sent before, I couldn't reproduce the issue on my end.
