### ISSUE TITLE
Unable to delete combinations

### ISSUE THREAD

**Issue by lennertvhoy** [PrestaShop/PrestaShop#25399]
#### Describe the bug

Once combinations are entered they cannot be deleted. 

#### Expected behavior

I would expect the combinations to be deleted when I press the little trash can icon.

#### Steps to Reproduce

Go to: Products -> New product -> Product with combinations -> Add some combinations -> Try to delete them with the trash can icon

**Comment by florine2623** [comment]
Hello @lennertvhoy ,

I tested with PS 1.7.7.5 and I cannot reproduce your issue.
Please check my screen record :
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

You will find [here](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/) the system requirements of PrestaShop, make sure your config is compatible with PrestaShop.

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

I'll close you issue.
Thanks!
