### ISSUE TITLE
BO ORDERS - Purchased products are not displayed in the orders section

### ISSUE THREAD

**Issue by evoprint** [PrestaShop/PrestaShop#25397]
#### Describe the bug

Problem in the BO - order part: the products purchased by the customer are not listed in the summary order, nor in the invoice, nor in the database.

#### Steps to Reproduce

1. Go to 'Orders'
2. Click on one of your customer orders
3. Scroll down to 'Products purchased' / 'Produits achetés'

**Screenshots**

<img width="599" alt="Capture d’écran 2021-07-22 à 11 03 16" src="https://user-images.githubusercontent.com/87802307/126614655-d0640223-7434-4857-81aa-de0320ad482c.png">

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: 7.4.21

**Comment by florine2623** [comment]
Hello @evoprint ,

In PS 1.7.7.5, this option does not exist :
![Information-about-customer-J-DOE-•-ps1775](https://user-images.githubusercontent.com/16019289/126622782-94d0535f-9f33-4b83-96e1-9055fed76018.png)

It seems like this info comes from an external module.

Also, the PHP version you should use is 7.3, not 7.4.
Please check and feedback.
Thanks!

**Comment by evoprint** [comment]
Hi @florine2623

Thanks for your answer !

As for me, I got a little confused in the different parts of Prestashop, however, the PHP version is the right one, 7.4, and the information of the products purchased by the customer are well present in the version 1.7.7.5 of Prestashop. 

I attach other photos with more precision. 

Thank you for your help !

![Capture d’écran 2021-07-22 à 13 58 36](https://user-images.githubusercontent.com/87802307/126636822-d6a640d4-69e7-4916-93a9-f653685766bd.png)


![Capture d’écran 2021-07-22 à 13 59 07](https://user-images.githubusercontent.com/87802307/126636824-ccac59ce-03e7-4847-8313-6b8d67fae684.png)


![Capture d’écran 2021-07-22 à 14 04 37](https://user-images.githubusercontent.com/87802307/126636828-8a75708a-2cdd-4d01-91a6-bce119d29af9.png)

**Comment by florine2623** [comment]
Hello @evoprint ,

You need to use PHP 7.3, not 7.4. 7.4 is not compatible with PS 1.7.7.5
<img width="741" alt="Screenshot 2021-07-22 at 14 24 59" src="https://user-images.githubusercontent.com/16019289/126638602-9ebd5c96-c83c-4cb3-8d02-48fc89474fe2.png">

In the order section, the products are well displayed :
<img width="1428" alt="Screenshot 2021-07-22 at 14 21 12" src="https://user-images.githubusercontent.com/16019289/126638327-e6dcef66-cae9-419a-991f-a9dfa7ee8af3.png">

In the customer page, I don't have a block "Produits achetés", only "Viewed products" :
<img width="580" alt="Screenshot 2021-07-22 at 14 23 25" src="https://user-images.githubusercontent.com/16019289/126638402-d152c75c-5102-481c-a623-77fa623809d1.png">

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

I'll close your issue.
Thanks!
