### ISSUE TITLE
If 2 products are in the cart, and one of them cannot be ordered but the other can, you can pay.

### ISSUE THREAD

**Issue by justeen35** [PrestaShop/PrestaShop#25405]
#### Describe the bug

If 2 products are in the cart, and one of them cannot be ordered but the other can, you can pay.

#### Expected behavior

A message should tell customer that one of the item cannot be shipped, or no carriers should be displayed for customer when customer wants to checkout.

#### Steps to Reproduce

1.  Create two products
2. Associate one of the products with a disabled carrier. Also works with a carrier not available in the country where you want to be delivered.
3. Associate other product you associate with an available carrier.
4. Add both products to the basket
5. Go to checkout process : you can complete the order. However 1st product should not be available!

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: php7.3

**Comment by florine2623** [comment]
Hello @justeen35 ,

Your issue is a duplicate of : https://github.com/PrestaShop/PrestaShop/issues/15304
Please check and feedback.

Thanks!

**Comment by justeen35** [comment]
> Hello @justeen35 ,
> 
> Your issue is a duplicate of : #15304
> Please check and feedback.
> 
> Thanks!

Correct. I close my issue.
