### ISSUE TITLE
if module in prestashop 1.7.5.* do not uninstall or reset in BO: solution server side

### ISSUE THREAD

**Issue by Xzave** [PrestaShop/PrestaShop#25408]
#### Describe the bug

i meet always the same error in red in BO: the module do not to uninstall or reset. 
In error.log file of the site i have some errors.

other idea is to install a module but it doesn't work unfortunatly or when you reinstall it anything help even with remove all trace of the module in the database.

#### Steps to Reproduce

1. install or uninstall module in >module manager when you have in performance memcached actived
2. deactive memecached in >performance
3. clear cache of the server, on debian server: https://www.tecmint.com/clear-ram-memory-cache-buffer-and-swap-space-on-linux/
4. flush the cache of memcached: with netcat (preinstall it)
`echo "flush_all" | nc -q 2 localhost 11211 `

#### Additional information

* PrestaShop version: 1.7.5.2
* PHP version: 7.2
* Debian 9 server with multiple php version
* php-fpm 7.2

**Comment by florine2623** [comment]
Hello @Xzave ,

Please follow the issue template :
<img width="622" alt="Screenshot 2021-07-23 at 09 31 34" src="https://user-images.githubusercontent.com/16019289/126750562-3faddfc7-f4dd-42ba-82f2-20ef6634d0ef.png">

Thanks!

**Comment by florine2623** [comment]
Hello @Xzave ,
Thanks for updating your issue.

The module you can't install is a native module from PrestaShop ?
Which one is it ?

I tested with a few native modules and didn't encounter the error "the module do not to uninstall or reset."

**Comment by Xzave** [comment]
Hello @florine2623,

have you memcached active on you own server, since some week ago?

it is not a native module of Presttashop,

but i pay for it,

i meet this error twice time for module come from addons of PS.

i search many time on internet and found solutions that i try, but only this solution that explain work for me.

the module is https://addons.prestashop.com/fr/boutons-login-connect/41014-social-login-connexions-40-en-1-coupons-statistiques.html

same the developper  try to install or to remove and that was not possible.

**Comment by hibatallahAouadni** [comment]
Hello @Xzave 

> it is not a native module of Presttashop,
but i pay for it,

So, you need to contact the module developer to fix your issue. As @florine2623 mentioned we didn't encounter this issue, so it's not a Core bug, this bug is related to the module.
Please contact support team on Addons

We will close this issue.

Thanks!
