### ISSUE TITLE
1.7.5 php7.3 no access to front office

### ISSUE THREAD

**Issue by toyser** [PrestaShop/PrestaShop#25404]
#### Describe the bug

The front office is all white page

#### Expected behavior

If i make a backup the FO works but when i clean the cache, the issue back again.
I clean the cache by prestashop and manually, the issue persists....

![bug1](https://user-images.githubusercontent.com/53787145/126668418-c956a04f-cf0f-4c09-96e3-87255271c14d.png)

My site is accessible here : https://vertchez-soi.com

Thank's for your help

* PrestaShop version: 1.7.5.2
* PHP version: 7.3

**Comment by florine2623** [comment]
Hello @toyser ,

Please use PHP 7.2.
Here's the compatibility chart of PrestaShop : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Thanks!
