### ISSUE TITLE
Product carrier limitation ignored if more products are added on the cart

### ISSUE THREAD

**Issue by polrue** [PrestaShop/PrestaShop#25401]
#### Describe the bug

Product A: 
Has carrier limitations, the only carriers available are the ones that ship to country X

Product B: Has no limitations

Client registers from country Y.

If the product A is added to the cart the right message appears: "no carriers are available for this order"
If then, you add the product B, the order can be completed.

#### Expected behavior

The impossibility to complete the order, something like a message notifying about the limitation of the product A, as theoretically you can't send the product A to the country Y

#### Additional information

* PrestaShop version: 1.7 all tested
* PHP version: N/A

**Comment by florine2623** [comment]
Hello @polrue ,

Yous issue is a duplicate of : https://github.com/PrestaShop/PrestaShop/issues/15304
Please check and feedback.

Thanks!

**Comment by polrue** [comment]
Yes, it seems so. 

I did search before but I couldn't find it. 

Now I see there are lots of duplicates of it and it has been there for more than 2 years

**Comment by florine2623** [comment]
Duplicate of #15304
