### ISSUE TITLE
issue on total when change courier on admin

### ISSUE THREAD

**Issue by centoasa** [PrestaShop/PrestaShop#25414]
prestashop 1.7.7.5 on litespeed webserver
I have set up a free shipping when an order is over € 50.
When I am on an order and I change the courier with another paid one, the total of the order (only the total) changes and the value of the shipment is still added even if this flag is off
https://nimb.ws/JrHXi4
Thank you

**Comment by florine2623** [comment]
Hello @centoasa ,

Please edit your request with the issue template provided :
<img width="921" alt="Screenshot 2021-07-23 at 16 00 46" src="https://user-images.githubusercontent.com/16019289/126793060-fac39338-421c-4237-8abc-3d3868a3fc16.png">

Thanks

**Comment by hibatallahAouadni** [comment]
Hello @centoasa 


Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
