### ISSUE TITLE
PS 1.7.4 The new functionality of change of carrier in the orders already made does not work

### ISSUE THREAD

**Issue by Hsalehm** [PrestaShop/PrestaShop#25412]
#### Describe the bug

In an order already made, sometimes we have to change the delivery address, after changing the delivery address, the carrier does not change to the new address (which of course is covered by a carrier and the old carrier does not cover the new address), but that's okay, let's go to the section of "carrier" and we click "modify", this activates the drop-down of the carriers and we select the appropriate carrier, it even gives us the option to change the cost (but in principle we are not going to touch that value), the case is that to make the new selection and we give it to "update" it keeps going round and round and the change is not executed.

#### Expected behavior

You should let change the carrier to the new address, because the carrier of the other address does not cover the new address that we have put.

#### Steps to Reproduce

1. Enter an already confirmed order.
2. Change the delivery address to another address covered by another carrier and not by the one already in the previous address.
3. In the carrier tab we click "modify" and choose the carrier that covers this new address.
4. We give "update"

#### Additional information

* PrestaShop version: 1.7.73
* PHP version: 7.3.29

**Comment by florine2623** [comment]
Hello @Hsalehm ,

I can't reproduce your issue in PS 1.7.7.3 nor PS 1.7.7.5 as you can see per my screenrecord :
https://drive.google.com/file/d/1u0HD6CoOTQrEx4eaS0Zvzdw-uYcsNV9g/view

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
