### ISSUE TITLE
Disable Empty Categories

### ISSUE THREAD

**Issue by Gaja-A** [PrestaShop/PrestaShop#25415]
Hi,

I want to hide the empty categories (without products) in the category page. I tried some solutions in the forums but nothing helped me.
I use **ps_categorytree** module.

PS version: 1.7.6.1

Does anyone have a solution ?

Regards,
Gaja

**Comment by florine2623** [comment]
Hello @Gaja-A ,

You need to uncheck the display option in your category :
<img width="1170" alt="Screenshot 2021-07-23 at 16 03 04" src="https://user-images.githubusercontent.com/16019289/126793546-0fefe712-9555-41a9-bc3d-e6d9d25f6db7.png">

Thanks!

**Comment by Gaja-A** [comment]
Hi @florine2623 ,

Thanks for your reply.
Is there any way to achieve this effect in code? 
Because there are more than 100 categories that I want to hide so it will be better to do it in code.

Thanks in advance for your help.

Regards,
Gaja
