### ISSUE TITLE
Invalid Stock Count on Admin Catalog List View

### ISSUE THREAD

**Issue by vdigitalize** [PrestaShop/PrestaShop#25420]
![1](https://user-images.githubusercontent.com/87258693/126893353-5ffe3c4f-b251-4bd1-94ea-b56286cb857b.PNG)
In this above image, if you can see the Product ID number 1166 is having multiple combinations, and also check the Stock available count. Now check the below image where you can see only 4 combinations are actually present in the system.
![2](https://user-images.githubusercontent.com/87258693/126893504-dff0955d-3a5f-462c-9b58-aed561bd4f6d.PNG)
![3](https://user-images.githubusercontent.com/87258693/126893561-40df926b-f979-493a-8a9a-26bc2960ad2b.PNG)
So what i feel is that the problem in the stock query when user updates the stock even then also this doesn't reset the Available stock. 

Please help

**Comment by vdigitalize** [comment]
To reproduce the issue, i think you can create new product and save the product without combinations and set any stock say 10 or 20 in Quantity field under basic information tab. 
And then after the product is created successfully, then set the combinations and add combination from the combinations tab.
I think then the stock quantity gets confused and show random number.

**Comment by hibatallahAouadni** [comment]
Hello @vdigitalize 

I didn't manage to reproduce your issue with PS1775, see the attached screen record below:

https://drive.google.com/file/d/1GAgmuZC3iSHnXzrkxyMwC8PNgpfayyTK/view

Unfortunately, I have to close it, cause you didn't respect the provided template. So, when you open a new issue, **you must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
