### ISSUE TITLE
Problem when trying to select pictures for specific combinations: "The CSRF token is invalid. Please try to resubmit the form."

### ISSUE THREAD

**Issue by lennertvhoy** [PrestaShop/PrestaShop#25431]
#### Describe the bug

I'm trying to create a product with 51 pictures and 54 possible combinations. Almost every combination needs to display a different picture except for 4 which have to display the same picture. Once I upload all of the pictures a warning appears: "The value of the PHP.ini setting "max_input_vars" must be increased to 2000 in order to be able to submit the product form." but the product behaves completely normal for the rest. I can assign a single picture to  41 products and everything keeps working fine. But after that when I try to save the product I get another warning: "The CSRF token is invalid. Please try to resubmit the form." and my product won't save anymore.

#### Expected behavior

I would expect the product to display and update properly regardless of the amount of combinations I create.

#### Steps to Reproduce

**Screenshots**

#### Additional information

* PrestaShop version: 1.7.6.9
* PHP version: N/A

**Comment by florine2623** [comment]
Hello @lennertvhoy ,

It seems like your issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/9809
Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @lennertvhoy 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
