### ISSUE TITLE
PHP Fatal error - Kernel Container is not available in /var/www/html/www/src/Adapter/ContainerFinder.php:77

### ISSUE THREAD

**Issue by Alpescol** [PrestaShop/PrestaShop#25438]
#### Describe the bug

I can't delete or create new client in BO
I can't create or change an order in BO 

When we check the logs during going to customers or orders menu, there is this message : 

PHP Fatal error:  Uncaught PrestaShop\PrestaShop\Core\Exception\ContainerNotFoundException: Kernel Container is not available in /var/www/html/www/src/Adapter/ContainerFinder.php:77
Stack trace:
#0 /var/www/html/www/classes/Tools.php(786): PrestaShop\PrestaShop\Adapter\ContainerFinder->getContainer()
#1 /var/www/html/www/classes/Notification.php(133): ToolsCore::getContextLocale(Object(Context))
#2 /var/www/html/www/classes/Notification.php(57): NotificationCore::getLastElementsIdsByType('order', '985')
#3 /var/www/html/www/admin224l20wmu/ajax.php(78): NotificationCore->getLastElements()
#4 {main} thrown in /var/www/html/www/src/Adapter/ContainerFinder.php on line 77

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: 7.3.23

**Comment by florine2623** [comment]
Hello @Alpescol ,

I can't reproduce both of your issues in PS 1.7.7.5.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
