### ISSUE TITLE
Can't add a carrier to the shipping details information

### ISSUE THREAD

**Issue by ubergenki** [PrestaShop/PrestaShop#25436]
#### Describe the bug

Hello,

I've upgraded my prestashop to version 1.7.7.5, and now when I try to enter the tracking information on the order details screen, I can't because no options appear in the Carrier field.

#### Expected behavior

I have several carriers enabled and I can enter the tracking number, but I can't choose a carrier and so can't share tracking information with customers. All of the carrier options also appear just fine during checkout. I tried creating a new test carrier, but it only shows up when set to free shipping.

#### Steps to Reproduce

1. Go to any order details page
2. Click on "Edit" beside Tracking Number under the Carriers tab.
3. The "Edit shipping details" window pops up

**Screenshots: 2**

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: 7.1.33
![carriers](https://user-images.githubusercontent.com/88030505/127132227-ea944913-14b2-44f1-a1b0-2ed634e24d4e.png)
![carriers2](https://user-images.githubusercontent.com/88030505/127132233-cb9ef63b-8edc-4d29-8527-088b1ec7f68e.png)

**Comment by florine2623** [comment]
Hello @ubergenki ,

I can't reproduce your issue in PS 1.7.7.5 :
<img width="648" alt="Screenshot 2021-07-27 at 14 56 14" src="https://user-images.githubusercontent.com/16019289/127157246-c7f29382-e822-469f-afce-919c0ca6d794.png">


You need to make sure this option is activated :
<img width="650" alt="Screenshot 2021-07-27 at 14 36 05" src="https://user-images.githubusercontent.com/16019289/127154640-8c36a9dd-76d3-485f-89a2-43a917eb9e4b.png">
You will find it in Shop Parameters > Order Settings 

As well as make sure that a carrier exist for this specific address.

Thanks!

**Comment by ubergenki** [comment]
@florine2623 Thank you for the quick response!
I have the recalculate option set to on and the carriers all cover the customer’s address.
I’m not sure why no other carrier option is being shown, so please let me know if you have any other setting suggestions.
