### ISSUE TITLE
force_id not working with lang table in Object Model

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#25432]
#### Describe the bug

In `objectModel`, `force_id` is useful if you wants to set your id, by example if you have a primary as `id_product` in an extra table.
When you call `add()` method, it works well for base table but not for `_lang` table.

#### Expected behavior
The provided id should be used correctly in `_lang` tables

#### Steps to Reproduce

1. Create an object model class : `MyClass`
```
'table' => 'mytable',
'primary' => 'id_product',
'multilang' => true,
```
2. Create the corresponding SQL tables `mytable` and `mytable_lang`.
Make sure `id_product` is NOT an autoincrement.

2. Add a row with the forced id:
```
$myRow = new MyClass(124);
$myRow->id = 124;
$myRow->force_id = true;
$myRow->add();
```

3. Go to database
4. See error : the inserted row in `mytable` has `id_product` set to 0 instead of 124

#### Additional information

* PrestaShop version: all 1.7
* PHP version: 7.1

**Comment by florine2623** [comment]
ping @PrestaShop/prestashop-core-developers 

Could you take a look at this issue in order to reproduce it ?

Thanks!

**Comment by matks** [comment]
I confirm the reported faulty behavior.
