### ISSUE TITLE
Contextual Help issues on legacy pages

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#25443]
#### Describe the bug

On legacy pages (example: Dashboard or Configure > Shop parameters > Search), contextual Help has 2 issues.

![Capture d’écran 2021-07-27 à 18 37 39](https://user-images.githubusercontent.com/3830050/127193425-4c77076d-277b-473d-b39c-c9ce072c8431.png)

1. If we click the "Home" button we see the Homepage, it prints "PrestaShop 1.6 User Guide" although this is PS 1.7

2. If we click the "Arrow" button, it opens a new window but it stays blank. There is an error in console.

#### Expected behavior

No issues: doc should say "PrestaShop 1.7 User guide" and there should be content in the new window.

#### Steps to Reproduce

1. Go to Configure > Shop parameters > Search
2. Open contextual help by clicking "Help" button on the right
3. Help window opens.
4. Click on "Home" button or "Arrow" button

**Screenshots**

![Capture d’écran 2021-07-27 à 18 37 39](https://user-images.githubusercontent.com/3830050/127193425-4c77076d-277b-473d-b39c-c9ce072c8431.png)

#### Additional information

* PrestaShop version: 1.7.8.x

**Comment by hibatallahAouadni** [comment]
Hello @matks 

Thanks for reporting this issue!
I reproduce the issue with 1767, 1775, 178x and develop. I’ll add this to the debug backlog so that it’s fixed.

Thank you

**Comment by florine2623** [comment]
These buttons do not exist anymore ^^

![Image](https://github.com/user-attachments/assets/eaf328ee-2864-44f6-beba-ef5f6da8f425)
