### ISSUE TITLE
When duplicating product, out of stock ordering behavior is not copied

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#25448]
#### Describe the bug

When duplicating product, out of stock ordering behavior is not copied

#### Expected behavior

out of stock ordering behavior is copied too

#### Steps to Reproduce

1. Create a product, set quantity to zero, disable ordering when out of stock.
2. Duplicate product, open it.
3. See that ordering out of stock got reset to "Default".

#### Additional information

* PrestaShop version: 1.7.8 beta
* PHP version: 7.2

**Comment by gennaris** [comment]
@Hlavtox I noticed this problem too and made a fix a few days ago , see the PR it will solve the issue

**Comment by Hlavtox** [comment]
@gennaris Awesome man!

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/25787
