### ISSUE TITLE
Remove marketplace widget in blockreassurance

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#25457]
#### Is your feature request related to a problem?

We have to remove this elements for the open source project for https://github.com/PrestaShop/blockreassurance/

![Capture d’écran 2021-07-29 à 09 22 23](https://user-images.githubusercontent.com/3830050/127449442-d49fadd8-9eb1-4ad1-8a09-86d15e0da721.png)

#### Describe the solution you'd like

Remove marketplace widget in blockreassurance

**Comment by atomiix** [comment]
I think this one has been made already? https://github.com/PrestaShop/blockreassurance/pull/219

**Comment by Progi1984** [comment]
@PrestaShop/product-team Do we need to add in `blockreassurance` hooks for adding this elements from `MBO` ?

**Comment by Progi1984** [comment]
> @PrestaShop/product-team Do we need to add in `blockreassurance` hooks for adding this elements from `MBO` ?

@marionf confirms that hook for adding elements is required.

**Comment by Progi1984** [comment]
PR Done : PrestaShop/blockreassurance#280

**Comment by Progi1984** [comment]
@PrestaShop/product-team No need to new hooks for MBO. MBO can rewrite templates of modules. Thanks @jolelievre & @PierreRambaud for the help.

**Comment by alfonsolr09** [comment]
Why is everything related to addons removed?

**Comment by matks** [comment]
@alfonsolr09 Details about it there https://github.com/PrestaShop/PrestaShop/issues/24639

To make it short: we're removing all links to PrestaShop company from inside the Core. The project will become fully neutral. The PrestaShop company will build its own flavor of PrestaShop and embed their products and services in it, but the PrestaShop project will and must be neutral.

**Comment by alfonsolr09** [comment]
> The PrestaShop company will build its own flavor of PrestaShop and embed their products and services in it, but the PrestaShop project will and must be neutral.

It is what there is right now, isn't it?

**Comment by matks** [comment]
@alfonsolr09 Yes.

Today's latest version, PrestaShop 1.7.8.2 contains:
- direct links to PrestaShop company websites
- allow connection to addons.prestashop.com to download modules
- push some modules during install to be pre-installed

PrestaShop 8.0.0 open source will have nothing of the above. But it is likely that PrestaShop company will build their own 8.0.0 flavor which will contain all of the above and maybe more.

**Comment by alfonsolr09** [comment]
I don't understand what you mean by the PrestaShop company itself build your own project.

**Comment by alfonsolr09** [comment]
Do you mean that there are probably several PrestaShop distributions? A version without any addons and another that includes links to the web?

**Comment by matks** [comment]
> Do you mean that there are probably several PrestaShop distributions? A version without any addons and another that includes links to the web?

Yes. In 2022 there will be 2 PrestaShop distributions, one without any of PrestaShop company links, services, modules, and one with all of them.

**Comment by alfonsolr09** [comment]
Don't you think that the time that PrestaShop will spend customizing the project could be used to solve many other problems?

I don't really understand why this decision to have the same project with PrestaShop or without it.

are we facing a close abandonment of the open source project and a development of the "payment" project?

🤔🤔🤔🤔🤔

**Comment by matks** [comment]
> I don't really understand why this decision to have the same project with PrestaShop or without it.

Point acknowledged, I will carry this feedback to the people responsible for this. You will find the answers in the OSS demo of November https://www.youtube.com/watch?v=jwOy3gx-MNs

> are we facing a close abandonment of the open source project and a development of the "payment" project?

No, actually we're doing more and more for the project. But we are not working on the topics you consider more important.

As I said before if you find that a topic is important for you, then you should _invest_ into having it done. Don't wait for us to do all the work.

PrestaShop is an open source, community project.

You can hire a developer to fix the problems you mention, or if you are a developer yourself, you can try doing it on your own. The most important thing is to share that fix with everyone by submitting a Pull Request -- that's what the open source spirit is all about.

If you want someone to do something for you -> you need to pay this person 😄  . We will work on the things we think the more important for the project, and if you think there are other topics more important for you, _invest_ into having these done in the project. We fuse all of this together and everybody can get all the benefits at the end of the day.

**Comment by alfonsolr09** [comment]
I know that you solve many problems. 
I am not complaining about any problem since there is no critical one for me, and if there is one, you will solve it quickly. 
But I do not understand the need to fork the project to create one in parallel to the other with exactly the same functions only varying whether to add things from prestashop or not
