### ISSUE TITLE
After merged, welcome module doesn't work anymore

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#25463]
#### Describe the bug

After the merge https://github.com/PrestaShop/welcome/pull/120, welcome module doesn't work anymore

#### Expected behavior

I should be able to see all the steps of the on boarding

#### Steps to Reproduce

1. Install PR https://github.com/PrestaShop/welcome/pull/120 on PS 1.7.8.x
2. Install shop as usual
3. Go to BO - no onBoarding is available -> **NOK**
4. Go to Modules > search Welcome module > Reset - still no onBoarding is available -> **NOK**

**Screenshots**

I should have :
<img width="1436" alt="Screenshot 2021-07-29 at 15 49 44" src="https://user-images.githubusercontent.com/16019289/127503787-b47fc07a-aeba-48c7-8a9a-12c40adfaf0d.png">

But I have no on boarding in my BO.

#### Additional information

* PrestaShop version: 1.7.7.x, 1.7.8.x, develop
* PHP version: 7.3

**Comment by marionf** [comment]
Hello, 

The welcome module will be archived with the V8.0.0, so I close this issue.
