### ISSUE TITLE
[BO] - An exception thrown when you try to access "edit your profile"

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#25468]
#### Describe the bug

When you try to edit your profile as an admin, an exception will be thrown

#### Expected behavior

No exception

#### Steps to Reproduce

1. **BO** > **CONFIGURE** > **Advanced Parameters** > **Team**
2. Try to edit your profile (employee)
3. See error => an exception is thrown
4. Try to edit another admin profile or any employee profile => no error
5. Try to edit your profile from **employee-dropdown** in the header (see attached screenshot n°1)
6. See error => an exception is thrown (see attached screenshot n°2)

**Screenshot n°1**

![image](https://user-images.githubusercontent.com/23308427/127628304-85564ea9-9f7a-4564-a2a3-5e5fa8a45c06.png)

**Screenshot n°2**

![image](https://user-images.githubusercontent.com/23308427/127628326-b70f2147-04c9-454d-9e75-fc549fd9b692.png)

#### Additional information

* PrestaShop version: (only on) develop
* PHP version: 7.2

**Comment by kpodemski** [comment]
Yes, can confirm. It's coming from code related to Addons Marketplace, I think @PierreRambaud started working on this.
