### ISSUE TITLE
ps_emailalerts - always sending alert alert-info

### ISSUE THREAD

**Issue by mrabsinthe** [PrestaShop/PrestaShop#25474]
#### Is your feature request related to a problem?

On a product page when a customer trying to register an email address to be notified when a product is back in stock, module always displays a message in alert-info box instead of using alert-info just for already registered message.

#### Describe the solution you'd like

The color of an alert box should correspond to the message, green for success, blue for information (already registered) and red for a wrong email address.

**Comment by kpodemski** [comment]
Hello @mrabsinthe 

In progress :)

https://github.com/PrestaShop/ps_emailalerts/pull/86

**Comment by hibatallahAouadni** [comment]
Hello @mrabsinthe 


Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

PS: thanks @kpodemski for your PR 🎉 

Thank you

**Comment by lmeyer1** [comment]
@hibatallahAouadni This issue has been solved last year with https://github.com/PrestaShop/ps_emailalerts/pull/86.
Now there is another issue with the display of these alerts (#28216).
Could you close this issue in favor of #28216 ? Thank you.

**Comment by lmeyer1** [comment]
@marionf I see that you added the `Feature` tag, after a PR that fixed the issue has been merged (https://github.com/PrestaShop/ps_emailalerts/pull/86).
Am I missing something?

**Comment by hibatallahAouadni** [comment]
@lmeyer1 We change our Issue Management Workflow, so we use/have only bugs to fix and features to implement :wink: 
No improvement :smile:

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Thanks for the reminder :pray: 
Indeed this issue has been fixed, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/162700943-3a8523ca-1bcc-475e-9180-82991c1054e3.mp4

Closing this issue :tada: 
Thanks @kpodemski for your PR :rocket: 

Thanks!
