### ISSUE TITLE
BO - Ordr View page - Product Block - when we try to add a product, the total displayed is tax exlcluded and not included

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25479]
#### Describe the bug

In the BO > Orders > Order details page > when we try to add a product, the total is displayed with tax excluded, but it should be tax included.

#### Steps to Reproduce

1. Create a new Order from BO/FO
2. Go to BO > Orders > View last Order created
3. Try to add a product
4. See error: in the addProductTableRow: the total is displayed with tax excluded
5. change the price => the same bug
6. change quantity => the same bug

![image](https://user-images.githubusercontent.com/16067358/127853499-5cb4b5be-1847-46b4-89cd-84ee1872d4c2.png)

When we try to edit a product => ok 

**Screenshots**

https://drive.google.com/file/d/1MCdwnD3ykmPSMcvjQtckMPk8OnOp841L/view?usp=sharing

PS1775 => ok

#### Additional information

* PrestaShop version: 1.7.7.6build1
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed by @Progi1984 in #25489
