### ISSUE TITLE
BO - Welcome - Th pop up onboarding is not displayed in the step4/6 "step2" because ps_checkout module is not instaled

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25477]
#### Describe the bug
After a fresh install, the popup onboarding is not displayed at step 4/6 "Get your shop ready for Payment" step2 ps_checkout module is not instaled
![image](https://user-images.githubusercontent.com/16067358/127833420-11d38df3-7f70-4a14-a057-e3a8185eba64.png)

If we install the ps_checkout module manually => ok
![image](https://user-images.githubusercontent.com/16067358/127833493-9768024a-754e-4583-8f34-78d6de5f00cc.png)

#### Steps to Reproduce

- Fresh install 1776build1 with English language & France country
- Go to BO
- Follow the welcome instructions
- See error at step4/6

Old installation PS1775 => ok 
![image](https://user-images.githubusercontent.com/16067358/127833633-c9d1e543-8fed-47df-a227-2f3f2d2e7cb4.png)

New installation PS1775 => NOK
![image](https://user-images.githubusercontent.com/16067358/127833676-e58baa54-421c-434f-aa83-eb1a9d63e2a8.png)

#### Additional information

* PrestaShop version: 1776build1 / welcome module v6.0.6
* PHP version: 7.2

**Comment by Progi1984** [comment]
@khouloudbelguith Could you test it again ? Because I just tried and I haven't got the problem.

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

It is a temporary issue.
Ps_checkout is pushed after fresh install PS1776build1 and 177x branch.
I will close the issue.
https://drive.google.com/file/d/11S3t3NhnoofYNkPam91z6yf266f9DY68/view?usp=sharing

Thanks!
