### ISSUE TITLE
Chrome/Microsoft Edge - Disappearing Free Text Boxes, Unable to Edit Free Text

### ISSUE THREAD

**Issue by Jeggiesaur** [PrestaShop/PrestaShop#25475]
#### Describe the bug

Free text boxes aren't showing up for editing text. Examples include: product page (summary/description), pages configuration (text block), Pages (page content)

#### Expected behavior

Free text box showing for editing free text.

#### Steps to Reproduce

1. Go to 'Pages'
2. Click on 'Edit (on any page)'
3. Scroll down to 'Page Content'

**Screenshots**
![image](https://user-images.githubusercontent.com/88282657/127777239-90338f6b-3d00-4e76-ae1d-b1e0353c8a34.png)

![image](https://user-images.githubusercontent.com/88282657/127777231-9708aab5-709e-4c10-8c11-4fbe46068b65.png)

![image](https://user-images.githubusercontent.com/88282657/127777182-febdf806-8907-4077-925f-fff043ae3918.png)

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @Jeggiesaur 

I didn't manage to reproduce it with Chrome v91.
Please provide your Chrome & Edge version 🙏 
Please check and feedback.

Thanks!

**Comment by Jeggiesaur** [comment]
hi @hibatallahAouadni i'm using Chrome Version 92.0.4515.107 (Official Build) (64-bit) and Edge Version 91.0.864.64 (Official build) (64-bit)

**Comment by Jeggiesaur** [comment]
hi @hibatallahAouadni the issue has now been resolved by upgrading to 1.7.7.5

**Comment by hibatallahAouadni** [comment]
@Jeggiesaur Glad to hear 🎉
