### ISSUE TITLE
FO - An exception is displayed when we click on sign out two times

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25483]
#### Describe the bug

In the FO > When a customer tries to logout with clicking multiple times on "Sign out" => an exception is displayed
![image](https://user-images.githubusercontent.com/16067358/127974757-9b87f65b-7d16-4aae-8aef-795bfe72d56d.png)

#### Steps to Reproduce

1- Enable debug mode
2- Go to FO and sign in
3- Click on Sign out 2 times ( URL: shop.com/en/?mylogout=)
4- See error: exception: https://drive.google.com/file/d/1D9TwKgFv2ENsiuPwuvPwUToEYCLhJzuI/view?usp=sharing

I tried with PS1769 => ok (no exception displayed)
https://drive.google.com/file/d/1nOWxP5xcqtCp0P3NS-iipbFIxYNRGOEH/view?usp=sharing

#### Additional information

* PrestaShop version: 1776build1, 1775
* PHP version: 7.2

**Comment by Progi1984** [comment]
@marionf I just discussed with @sarahdib : with the scope of this PR (just a check of variable), it can be embedded in 1.7.7.6.

**Comment by marionf** [comment]
if it does not delay the release of the version ok

**Comment by Progi1984** [comment]
Fixed in #25495 by @Progi1984
