### ISSUE TITLE
Add ProductExtraContent hook to Product Comments module to support tabs display

### ISSUE THREAD

**Issue by rtvt** [PrestaShop/PrestaShop#25487]
Any plans to add ProductExtraContent hook widget interface to Product Comments module to call it as tab content on product page?
So we don't need to duplicate module to show it as tab and just use default one.

**Comment by hibatallahAouadni** [comment]
Hello @rtvt 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
