### ISSUE TITLE
1.7.7.4 & 1.7.7.5 Text edits in back office not showing on store front

### ISSUE THREAD

**Issue by Jeggiesaur** [PrestaShop/PrestaShop#25482]
#### Describe the bug

Text updates in Back Office not showing on Store Front on browser (Chrome v92), happens with all editable text. No issues showing up on mobile.

#### Expected behavior

Text updates in Back Office to show on Store Front

#### Steps to Reproduce

1. Go to 'Custom Text Blocks' in Modules
2. Enter text in text box
3. Click 'Save'
4. Click 'View my shop'

**Screenshots**
Back Office
![image](https://user-images.githubusercontent.com/88282657/127911517-f7ff7f98-96d7-4c85-8fdc-e20563beead5.png)
Store Front
![image](https://user-images.githubusercontent.com/88282657/127911555-2d9c80c4-0ac3-4187-a3f0-79c148c6cbfc.png)

#### Additional information

* PrestaShop version: 1.7.7.4 and 1.7.7.5
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @Jeggiesaur 

I didn't reproduce your issue with PS1775 and Chrome v92, see the attached screen reocrd below:

https://drive.google.com/file/d/1s_e60GOokZ7T0o8BEPbLrohdfnuk7hI6/view

Please check and feedback.
Thanks!

**Comment by Jeggiesaur** [comment]
Hi @hibatallahAouadni I'm still getting the issue even on Firefox v90 unfortunately. No issues with mobile version.

**Comment by Jeggiesaur** [comment]
If it helps it's not even updating the maintenance message.
![image](https://user-images.githubusercontent.com/88282657/128022677-3f1a520f-eb83-4030-9c5f-5b03ad0989cc.png)
![image](https://user-images.githubusercontent.com/88282657/128022705-b6182470-2b4f-4bd0-9fae-c22d72ce491f.png)

**Comment by hibatallahAouadni** [comment]
Hello @Jeggiesaur 

Could you please provide a screen record :pray: 
And please set your performance like the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/128035351-5edf3046-0d65-42fb-a2b0-7b6d2a69d9ce.png)

Please check and feeback.
Thanks!

**Comment by Jeggiesaur** [comment]
Hi @hibatallahAouadni 

Please find below the link to the screen record
https://drive.google.com/file/d/1MQmBVsPmIMDknJJ7Je6LV2aE5mbtwrMd/view?usp=sharing

**Comment by khouloudbelguith** [comment]
Hi @Jeggiesaur,

In fact, your default language is English 
BO selected 
![image](https://user-images.githubusercontent.com/16067358/128500290-889d67ac-d5f0-4546-80d7-919e9e74322d.png)

In the FO, the language selected is Gb
![image](https://user-images.githubusercontent.com/16067358/128500402-e74b56b0-5a49-4d4e-875a-bb3b865a6882.png)

You need to change the language selected in the FO => It will be ok
If you need to update the text in Gb also, in the BO, you need to select the exact language.

I will close the issue.
Feel free to open a new one when needed.

Thanks!
