### ISSUE TITLE
Error downgrading from Prestashop version 1.7.7.5 to 1.7.6.9

### ISSUE THREAD

**Issue by ekomot** [PrestaShop/PrestaShop#25499]
I tried to upgrade from verion 1.7.6.9 to 1.7.7.5. After the upgrade the left Admin panel Menu disappeared. Rolled back to the  1.7.6.9 After finishing this is the error screen:
![image](https://user-images.githubusercontent.com/55546136/128060090-598bc142-5c7b-43c9-9abd-01ea80544a5f.png)

* PrestaShop version: 1.7.67.5 to 1.7.6.9
* PHP version: 7.3.28

**Comment by matks** [comment]
@ekomot according to your screenshot, a database table pscb_shop_url is missing. You might want to look at the backup.

**Comment by ekomot** [comment]
> @ekomot according to your screenshot, a database table pscb_shop_url is missing. You might want to look at the backup.

Thank you :) Actually more than half of my database was missing. Issue was solved by importing the back-up file, but primarily erasing a large part of the DB during a downgrade by 1 Click module is not normal.

**Comment by ekomot** [comment]
Thank you Mathieu, I solved the issue by importing the back-up file, but still not clear why this happened. Upgrading from 1.7.6.9 to 1.7.7.5 made the left menu disappear, downgrading again via the 1 Click module crashed my database…Has not happened before.

Thanks and regards,

mugur

**Comment by kpodemski** [comment]
@ekomot as you can imagine module needs to delete the updated version of the database, to import the old one, unfortunately, rollback it's very problematic and it's something that PrestaShop Maintainers is already discussing 👍 

Good that you did a backup! :D

**Comment by hibatallahAouadni** [comment]
Hello @ekomot 

The issue of left menu in BO disappeared after upgrade #22250 has been fixed.
And as @matks mentioned in this [comment](https://github.com/PrestaShop/PrestaShop/issues/23166#issuecomment-783184675), your issue may be related to **APC Cache**.

> Thank you Mathieu, I solved the issue by importing the back-up file

Glad to hear :tada: that your problem has been solved.
Closing the issue :wink: 

PS: @matks @kpodemski  thanks guys for your quick replies :rocket: 

Thanks!
