### ISSUE TITLE
Credit Slip - Ecotax is displayed in the Credit slip  - Tax details

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25493]
#### Describe the bug

In the Credit slip, the Ecotax is displayed in the Tax details 
![image](https://user-images.githubusercontent.com/16067358/128033075-af9b881c-c168-48e4-b139-ddc1146d1ad4.png)

#### Steps to Reproduce

1. Check that Ecotax is disabled in the BO > International > Taxes page
2. If it is enabled Create an order with any demo product that it hasn't any ecotax
3. Change status of the order to shipped
4. Click on partial refund => credit slip is generated
5. download the credit slip (in the Tax detail => there is an ecotax = 0.00% )

It shouldn't be displayed (check the invoice)

This regression is due to this line: https://github.com/PrestaShop/PrestaShop/pull/24991/files#diff-a159f240339a18f95988d321ffcb68667373535b09addbf84355af67b72e2c58L50

#### Additional information

* PrestaShop version: 1776build1
* PHP version: 7.2

**Comment by Progi1984** [comment]
@marionf Finally, this bug is not a bug anymore.

Our discussion concluded with that : https://github.com/PrestaShop/PrestaShop/pull/25497#issuecomment-896888412

**Comment by Progi1984** [comment]
Fixed in #25497 by @Progi1984
