### ISSUE TITLE
hook actionAdminOrdersTrackingNumberUpdate not working correctly

### ISSUE THREAD

**Issue by ytilotti** [PrestaShop/PrestaShop#25490]
#### Describe the bug

There is a problem with the hook actionAdminOrdersTrackingNumberUpdate.
In the following code, the hook is never called because I have an TransistEmailSendingException but the trackingNumber is updated. The hook should be before email exception.

```
if (!empty($trackingNumber) && $oldTrackingNumber != $trackingNumber) {
            if (!$orderCarrier->sendInTransitEmail($order)) {
                throw new TransistEmailSendingException('An error occurred while sending an email to the customer.');
            }
            $customer = new Customer((int) $order->id_customer);
            $carrier = new Carrier((int) $order->id_carrier, (int) $order->getAssociatedLanguage()->getId());
            Hook::exec('actionAdminOrdersTrackingNumberUpdate', [
                'order' => $order,
                'customer' => $customer,
                'carrier' => $carrier,
            ], null, false, true, false, $order->id_shop);
        }
```

#### Expected behavior

If there is an error on updating the tracking number should not be updated. But in our case it is updated.
The hook need to be fire before the emailing error.

#### Steps to Reproduce

1. Install the module ps_qualityassurance
2. Create an hook actionAdminOrdersTrackingNumberUpdate
3. Disable emailing on your server or local environnement
4. The hook is not called

#### Additional information

* PrestaShop version: 1.7.7.5

**Comment by hibatallahAouadni** [comment]
Hello @ytilotti 

When I try to use this hook **actionAdminOrdersTrackingNumberUpdate** with module **ps_qualityassurance**, I can't find it, see the attached screen record below:

https://drive.google.com/file/d/1M8vF2u1ycZJow9v58iakwX0X7XWn9ToX/view

Please check and feedback.
Thanks!

**Comment by kpodemski** [comment]
Hello @hibatallahAouadni 

It's probably not registered on the installation process, can you type the hook manually to force the module to hook into it?

**Comment by hibatallahAouadni** [comment]
Hello @ytilotti 

After discussing on Slack, I didn't manage to reproduce the issue with PS1775, see the attached screen record below:

https://www.awesomescreenshot.com/video/4738273?key=08dd9c2438a5012921f2053f79e6c447

Even the emailing is disabled, the tracking number is updated.
Please check and feedback.

PS: thanks @kpodemski for the tip :wink: 

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello again!

Thanks @ytilotti for the clarification on Slack!
Yes, the tracking number has been updated but the hook is not called:

![image](https://user-images.githubusercontent.com/23308427/128349565-1cf69316-e485-4c18-b8f8-b35e2e8e98f6.png)

It should display a blank page with the word "test". So, I reproduce the issue with PS1775, PS1767 and develop.
I’ll add this to the debug backlog so that it’s fixed.

Thanks for your PR :rocket: 

PS: related/duplicate to #20105

Thank you
