### ISSUE TITLE
New module errors with 1.7.7.5 with LegacyHelperLinkBuilder.php [70]

### ISSUE THREAD

**Issue by dadashali61** [PrestaShop/PrestaShop#25492]
Hi,
I have a module that seems does not to match with PS 1.7.7.5. While Debug is turned on I will face this error below:

in src\Adapter\Routing\LegacyHelperLinkBuilder.php (line 70)
     * @throws InvalidArgumentException
     */
    public function getEditLink($entity, array $parameters)
    {
        if (!isset($parameters['current_index'])) {
            throw new InvalidArgumentException('Missing parameter current_index to build legacy link');
        }
        $currentIndex = $parameters['current_index'];
        $parameters = $this->buildActionParameters('update', $entity, $parameters);

As I test with the older PS version, this matter exists on PS 1.7.6.9 too but it works perfectly on PS 1.7.5.2.
Please help me to solve this problem.

Regards

**Comment by hibatallahAouadni** [comment]
Hello @dadashali61 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!
