### ISSUE TITLE
Cant redirect to Admin panel 

### ISSUE THREAD

**Issue by kairnejeff** [PrestaShop/PrestaShop#25498]
* PrestaShop version: 1.7.7.3
* PHP version: 7.2.34

when i log to my admin panel, it just cant redirect even all the username and password are correct. So i clear le cache in my navigator, and then it can redirect to my admin panel ! the problem is that I need to do it all the times when i connect. 
it's really weird. I clear the cache in var/cache too, it's always the same thing.

**Comment by hibatallahAouadni** [comment]
Hello @kairnejeff 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
