### ISSUE TITLE
Orders are not created when there is no confirmation from webhooks

### ISSUE THREAD

**Issue by adamus007p** [PrestaShop/PrestaShop#25496]
TL;DR When customer make a payment using non card method (Sofort, P24) and will not click back to shop there is no order on Prestashop side.

I had from time to time customers who paid me money.
I can see it on Stripe dashboard but there was no order on Prestashop side.
No order, no error, nothing.

Some customers are too fast and will not wait or click back to shop and there is problem that there will be no orders on Prestashop.

I think that this is important problem.

To reproduce the order

    start any order (not using a card)
    after successful order do not click back to shop or do not wait, just close the window
    result: on stripe side you will get a money, but there will be no order on prestashop side

I had a many customers like that as I finally figure out that is the problem.

The thing is not only with Stripe, I have issue with Paypal too.
Is it works as designed? or you can change how the Prestashop create orders? Maybe it would safe fron such problems.

I year I wanted to found what it the problem as finally I have figure it out.

You can reproduce the problem on any of prestashop versions. any 1.7

**Comment by hibatallahAouadni** [comment]
Hello @adamus007p 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by adamus007p** [comment]
I am 12 years report bugs for Prestashop. In top of 20 bug reportes few years ago. Bugs reporting via forge.

It is joke what you are talking as you can easy reproduce it.

@hibatallahAouadni  Have you tried do reproduce it? I am sure that NO.

But easier it to just clost the bug and have better stats ;)

All what you need has been written.
Don't be ignorant and check it :)

**Comment by matks** [comment]
@adamus007p the above comment is against our [Code of Conduct](https://github.com/PrestaShop/PrestaShop/blob/1e992bdfd57762fa83624314e57940a39d550690/CONTRIBUTING.md).

There is a process to report bugs, if you dont follow it, we will not analyze your usecase. This is our rules.
