### ISSUE TITLE
Wrong client delivery address sent by Prestashop to Paypal API

### ISSUE THREAD

**Issue by spriale** [PrestaShop/PrestaShop#25507]
#### Describe the bug

There is an issue with the data that Prestashop is sending to the payment modules from the DB. 

Prestashop is fetching the wrong address from the DB. The address sent by Prestashop to the Paypal API is already the wrong one. So the problem is not coming from Paypal API because Prestashop is sending already the wrong information.

#### Expected behavior

Prestashop should fetch the correct user information (delivery address and username) from the DB.

#### Steps to reproduce

The payment process looks as following:

1) Client enter their delivery address.
2) Client proceed to  pay by choosing payment method e.g Paypal
3) Paypal ask for their credentials.
4) Client pays.
5) Client get their invoice with the wrong name and delivery address.

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.4.20

**Comment by hibatallahAouadni** [comment]
Hello @spriale 

I just edited your problem, could you please provide your PrestaShop version and your PHP version. 
And if you could provide some screenshots as well, that would be helpful :wink: 
Please check and feedback.

Thanks!

**Comment by spriale** [comment]
- I updated the information that you required above.
- Also added this screenshots, where I had to change the names of the customers due to data protection reasons.
- You can see in the first screenshot that Paypal takes the correct user A name provided by Paypal. However it takes the address of the user B. In the invoice (seconde screenshot) it can be seen the user B name and address, which is wrong. It should take the user A name and address.

<img width="464" alt="0_Invoice_Paypal_correct_username_A_wrong_address" src="https://user-images.githubusercontent.com/62157773/128238671-cce3567d-020b-4e47-9f2f-7e9494cd542a.png">


![0_Invoice_Wrong_User_B_name_and_address](https://user-images.githubusercontent.com/62157773/128239068-5064be8c-2ff2-4169-825a-553e40dfb770.jpeg)

**Comment by khouloudbelguith** [comment]
Hi @spriale,

Thanks for your feedback.
I did not manage to reproduce the issue with PS1775 and the Paypal module v5.4.3 - by 202 e-commerce.
I attached a screen record
https://drive.google.com/file/d/1sV6P7EAnbVe2D8KjHIJd29ofSYkJm3sW/view?usp=sharing

Have you tried to contact the module developer?
Thanks to check with them and feedback.

**Comment by spriale** [comment]
Thank you for trying to reproduce the issue. Since the wrong data is sent already by Prestashop, the PayPal module is doing the correct action. So there is no an issue with the PayPal module. From your experience, could it be that there is some issue on the format of the DB or something similar? Pretashop is basically taking the data but it’s not the correct cell from the DB.

**Comment by matks** [comment]
> Since the wrong data is sent already by Prestashop

I don't understand how you are so sure that the data is wrongly fetched by PrestaShop Core, not the module, without providing the code.

**Comment by spriale** [comment]
Because Prestashop is the middleware. Paypal module doesn't fetch data from the DB. Prestashop fetches the data from the DB and then sends it to the Paypal API. The input is the problem and in this case, Prestashop is delivering the input. Plus I can see in my Prestashop order tab that the data stored in the invoice is the wrong one.

**Comment by matks** [comment]
> Because Prestashop is the middleware. Paypal module doesn't fetch data from the DB. Prestashop fetches the data from the DB and then sends it to the Paypal API.

The PrestaShop Core (this repository https://github.com/prestashop/prestashop) does not send data to Paypal API. It has to be sent by the Paypal module, that is installed on the Core.

Nothing in this repository https://github.com/prestashop/prestashop sends data to any payment gateway. The middleware is a module that is installed inside PrestaShop and that is not in the scope of this project.

Maybe the module relies on a function inside the Core, but you have to be sure of that.

**Comment by spriale** [comment]
There is no extra module inside Prestashop installed. It has to be from the Prestashop Core. I am not a developer of your code but looking into it I can see a Checkout Module for example that handles the addresses. There should be a module that handles the invoices as well.

**Comment by hibatallahAouadni** [comment]
Hello @spriale 

Unfortunately as @khouloudbelguith said, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a module problem.

Even thought, you're 100% sure that the issue is not a module problem, but have you tried to contact the module developer?
Please contact the module developer, check and feedback :pray: 

We will close this issue, but we can reopen it if you provide more details that could help us to reproduce the issue.
Waiting for your feedback :wink: 

Thanks!
