### ISSUE TITLE
Restore Category Tree Link Module

### ISSUE THREAD

**Issue by liloubio** [PrestaShop/PrestaShop#25511]
Hi, I would like to know where to get the Zip file for the **Category Tree Link module** as it doesn't appear on the Prestashop addons platform. 

It was bugging so I uninstalled it thinking I could get it back from the **Prestashop Addons Platform**. Well, I was wrong. Since it's a native module, I would want to restore it. 

Can anybody help?

**Comment by hibatallahAouadni** [comment]
Hello @liloubio 

Please follow my steps in the attached screen record below:

https://drive.google.com/file/d/1BQuizDjKTPRq4YmUQBH4SQ0UTD7U6L-X/view

As you can see after uninstalling the module, I search for the module on **Module Catalog**, then I installed.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have
questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
