### ISSUE TITLE
BO - Order details page - an exception is displayed when status of the "merchandise return" is deleted

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25510]
#### Describe the bug

In the BO > Orders > Order details page, an exception is displayed when the status of the "merchandise return" is deleted 
![image](https://user-images.githubusercontent.com/16067358/128215387-7f709bb6-5fb3-44c4-8860-9768fbddf605.png)

#### Steps to Reproduce

1. Go to BO > Shop Parameters > Order Settings > Statuses page and create a new order return status
2. Go to BO > Customer Service > Merchandise Returns page and Enable returns
3. Create an order and change status to Shipped
4. Go to FO > Log into Customer account > Go to Order history and details > Choose Order and make **return**
5. Go to the BO > Customer Service > Merchandise Returns page and change the last return to the new order return status
6. Go to BO > Shop Parameters > Order Settings > Statuses page and delete the new order return status
7. Go to BO > Orders > View last order created
8. See error

In the PS1769 => ok
![image](https://user-images.githubusercontent.com/16067358/128216610-fb491945-a793-4056-b2ef-56e17db000ef.png)

#### Additional information

* PrestaShop version: 1776build2, 1775
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed in #25523 by @Progi1984
