### ISSUE TITLE
Split orders (multishipping) issues

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#25518]
I just tested multishipping scenario and there are several issues with it.

## How to reproduce
A) Make two carriers.
B) Make two products, limit product 1 to carrier 1, limit product 2 to carrier 2
C) Go order it.

## Problems
**Order confirmation**
There is only one order displayed on the confirmation. If there are multiple orders for this cart, we should display a message: `We split your cart into multiple orders (ABCDFG and HIJKLMN), so we can work on them independently. - or something like this` and display all orders.

**Display of carriers** 
Carriers in cart are displayed wrongly. What if there are multiple carriers available for both products? How do I select them for both orders that will be created? https://github.com/PrestaShop/PrestaShop/issues/15369

**Cart detail in BO**
If you open the cart details in backoffice, there is only the first order displayed on the right.

**Duplicate reference**
Order references should be unique. The orders are split for them to be dealed as separate cases. If a customer calls or writes something about that order, you will immediately see which order he is talking about. Duplicate reference will only create problems in ERP systems. Also, when tracking the order, you can only track one order.

## Related issues
https://github.com/PrestaShop/PrestaShop/issues/9594
https://github.com/PrestaShop/PrestaShop/issues/11115

## Additional information

* PrestaShop version: develop

**Comment by jf-viguier** [comment]
Why did you close this one ? A good issue description there.

**Comment by Hlavtox** [comment]
@jf-viguier Because I found an EPIC with basically everything I wrote here... 😄

https://github.com/PrestaShop/PrestaShop/issues/15491
