### ISSUE TITLE
Discounts per client per brand (other than specific prices)

### ISSUE THREAD

**Issue by davidcylke** [PrestaShop/PrestaShop#25513]
Hi guys. It would be great if we could have an option to add percentage discount to use account and each brand. It would remove need of additional modules to do it. Many other ecommerce softwares have it. It would be very useful for B2B. There are specific prices, but those are not suitable if we have 200 b2b clients. We want to add additional discount off the specific price to client who makes big turnovers on one or few brands.

For example:
Client One - group B2B EU
Brand 1 - 0% discount
Brand 2 - 3% discount
Brand 3 - 5% discount

Client Two - Group B2B EU
Brand 1 - 3% discount
Brand 2 - 0% discount
Brand 3 - 8% discount

etc.

**Comment by hibatallahAouadni** [comment]
Hello @davidcylke 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
