### ISSUE TITLE
The method Db::numRows() is unreliable

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#25515]
#### Describe the bug

I used the method `Db::numRows()` instead of `Db:Affected_Rows()` (with `DBO` and Db Caching enabled) already since a long time. A just got bitten by a bug difficult to reproduce.
This is when I noticed, that `Db::numRows()` isn't used anymore in the whole codebase, and that in fact it cannot work reliably.
- It is meant to be used with `executeS` and `getRow`, but is not reliable for this with DBO
- With DBO it works with insert, update and delete queries, but the caching logic is wrong for those and thus is not reliable neither.

#### Steps to Reproduce

**Screenshots**

#### Additional information

* PrestaShop version: any
* PHP version: PHP 7.x

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

As you know I need clear and consice steps to reproduce the issue and then to valdiate it :sweat_smile: 
Could you please provide steps to reproduce :pray: Unless you think it should be treated by developer :wink: 
Please check and feedback.

Thanks!

**Comment by lmeyer1** [comment]
@hibatallahAouadni 
Sure, it should be treated by a developer.
@Progi1984 already approved my PR. There is still a little issue with it that I'll fix later today.

**Comment by hibatallahAouadni** [comment]
FYI: even when a developer or a QA analyst has approved your PR, the PR cannot be merged without validating the issue :wink: 

Ping @PrestaShop/prestashop-core-developers could you please reproduce the issue, this is quite technical for me :sweat_smile: 
Thanks in advance :pray:
