### ISSUE TITLE
BO - Welcome module - the text of the pop up is not well displayed

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25527]
#### Describe the bug

In the BO, in some steps, the text of the pop up is not well displayed

#### Expected behavior
Text should be well displayed

#### Steps to Reproduce

1. Install PS1776
2. Follow the welcome module
3. See the error in the product details page (Pricing) 
![image](https://user-images.githubusercontent.com/16067358/128386161-8bc356d2-7970-4820-9094-a116d7e00934.png)

4. See error in the Product list page
![image](https://user-images.githubusercontent.com/16067358/128386192-d00a8061-8b3f-48d0-bec5-55d443b008b3.png)

Me and @hibatallahAouadni 
we checked PHP7.2:
PS1776build2 + welcome v6.0.6 => NOK
PS1775 + welcome v6.0.6 => NOK

@hibatallahAouadni in the PS1774 + welcome v6.0.6 => OK

Me: 1775 + welcome v6.0.6 + PHP 7.1 => OK

**Comment by Progi1984** [comment]
Ping @NeOMakinG ;)
