### ISSUE TITLE
Error when selecting „non existent” combination

### ISSUE THREAD

**Issue by j-rutkowski** [PrestaShop/PrestaShop#25525]
#### Describe the bug

Let's say a product has colours A and B, and colour A is available in sizes S, M, L, and colour B is available in sizes M, L. When combination in colour A and size S is selected on the product page, and then a customer tries to select colour B, Prestashop throws an error `An error occurred while processing your request`, because combination colour B size S doesn't exist.
#### Expected behavior

The first available size for colour B should be applied instead, in this case size M.

#### Additional information

* PrestaShop version: 1.7.4.4
* PHP version: 7.1.1.3

**Comment by hibatallahAouadni** [comment]
Hello @JaqubR 

I didn't manage to reproduce the issue with PS1767 and PS1775, see the attached screen record below:

https://drive.google.com/file/d/14JL-8saoNGnHwgmtGKlUEW8gPrQ4o8Xf/view

It seems the issue has been fixed :tada:  I close the issue.
Thanks!

**Comment by j-rutkowski** [comment]
Hello @hibatallahAouadni

sorry for the late reply. I know that the issue seems to be solved since 1.7.6.4, but I can't really update from 1.7.4.4, so I'd like to know how to fix this issue on 1.7.4.4
