### ISSUE TITLE
prestashop/ps_googleanalytics is no longer installable with composer

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#25521]
#### Describe the bug

prestashop/ps_googleanalytics is not installable with composer. It is missing in the package catalog at packagist.org.

#### Expected behavior

I expect `prestashop/ps_googleanalytics` to be installable using composer.

#### Steps to Reproduce

1. Checkout Prestashop/Prestashop
2. Try to add the package `prestashop/ps_googleanalytics` using

        composer require prestashop/ps_googleanalytics` 

#### Additional information

Adding the following to composer.json, is a possible workaround.

    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/PrestaShop/ps_googleanalytics"
        },

* PrestaShop version: any
* PHP version: any

**Comment by matks** [comment]
Indeed I cannot find it in https://packagist.org/?query=prestashop

You say "no longer", so it was on packagist before?

**Comment by lmeyer1** [comment]
I thought it was, but I didn't go up the whole history of `composer.json`.
In fact I was wrong, I added it directly with the `repositories` entry.

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Thanks for reporting this issue!
So, @matks wdyt? shall we validate the issue?

**Comment by matks** [comment]
@hibatallahAouadni I'd prefer we do not work on this for now because the module ps_googleanalytics might change soon, and go out of the scope of the prestashop project. If this happens, it'll make things harder if it's published on Packagist.

It will be better to enable the Packagist distribution when the module is "in the right hands".
