### ISSUE TITLE
1.7.7.5 - Error checkout - The property Address->City is not valid at line 1045 in file classes/ObjectModel.php

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#25536]
Hello,

From times to times I'm getting orders without any state. The customers tell me that on the front office they can't finish the order.

I couldn't reproduce any of these but asked customers.

So basically:

1 - They are logged in;
2 - They try to finish the order;
3 - When they click to finish nothing happens.
4 - This can happen with any payment method.
5 - This happened on iOS and Android but I'm not sure if it can happen on desktops.

On my server I've no PHP Errors. 

The only error I can see is in prestashop /var/log directory where it says:

The property Address->City is not valid at line 1045 in file classes/ObjectModel.php

I double checked the customer address and there's no problem with the address and everything is filled.

My server info:

Server information Linux #160-Ubuntu SMP Thu Jul 29 06:54:29 UTC 2021 x86_64
Server software version: Apache
PHP version: 7.2.24-0ubuntu0.18.04.8
Memory limit: 1024M
Max execution time: 600
Upload Max File size: 128M

Database information
MySQL version: 5.7.35-0ubuntu0.18.04.1
MySQL server: 127.0.0.1
Tables prefix: ps_
MySQL engine: InnoDB
MySQL driver: DbPDO

**Comment by khouloudbelguith** [comment]
Hi @seederp2p,

Thanks for your report.
In the FO >  Your account  Addresses  Update your address page
What is the exact data in the field **City** saved?
I think you have incorrect data
In my case, I did not manage to reproduce the issue
![image](https://user-images.githubusercontent.com/16067358/128533322-51c56e03-e461-4cdc-aa7f-267cabba3629.png)

Thanks to check and feedback.

**Comment by seederp2p** [comment]
Hi there!

Well, it has the city name. Which is correct and I don't see any specific issue on that.

As far as the fact that you can reproduce, It doesn't happen all the times. So I suggest that some engineer might give us some input on what might cause this.

Might be related to something very specific...

**Comment by khouloudbelguith** [comment]
@seederp2p,

Could you please provide a screenshot from your database table ps_address to check the city field?

Thanks!

**Comment by seederp2p** [comment]
Please close the ticket. It had to do with cache.

**Comment by hibatallahAouadni** [comment]
@seederp2p thanks for your feedback.
