### ISSUE TITLE
Update Product Image Folder structure ?

### ISSUE THREAD

**Issue by goyetus** [PrestaShop/PrestaShop#25539]
#### Is your feature request related to a problem?

I see a product image  with ID 101  are located at:
images/p/1/0/1/101-image.jpg

If we are setting the image as unique with the "101" ID  attached to the image filename...... (101-image.jpg)
Why the hell we put the images under a folder structure like /1/0/1  for this image in particular ?

Im only seeing disadvantage  from getting  "1 folder for 3 images"    equals to   1500 products = 1500 folders...... why?

#### Describe the solution you'd like

Modify Prestashop to get all product images under directory /p/ 

#### Alternatives you've considered

None....

#### Additional context

Why ?

**Comment by matks** [comment]
Hi @goyetus unfortunately I'm not sure there is a trace of why the people who chose this storing convention decided to adopt this.

> Modify Prestashop to get all product images under directory /p/

Storing all images in a single folder would be a bad idea. Shops can have thousand, sometimes even millions of products and images. I am not sure all systems work well with a directory that contain millions of files. This is probably why the use of subdirectories was decided: avoid the hard limit of systems.

My guess would be that the current system allows to find "where is the right folder" from product ID, without having to rely on a database query to find the match between location and ID. Maybe @Matt75 or @kpodemski have better insights?

But I see no major issues with the current way of storing images, and modifying would be a massive change that would make upgrading from one version to another version harder, so I don't think we'll modify it (unless we find a major flaw in this convention).

**Comment by goyetus** [comment]
Thanks for your answer!  

I was thinking in download all images,   use an online zip tool  like TinyPng  or TinyJPG to decrease the size of images,  and re-upload them.

Having all of them in this estructure,  makes impossible to do this action without making some PHP  to move each image to his folder.   

In Opencart I set my image data as one simply folder,   so was wondering why Prestashop was using this extrange folder model......

PD:  I dont want also a "ID IMAGE"  in the database,   Opencart uses the Product ID  and i think is enough  to identify the product image and the  correlative images from the product........  (without making a double query in database  for getting Product ID and Image ID)....

Thanks again!

**Comment by musicpanda** [comment]
Prestashop used to have such a flat structure. If I remember well it was deserted in version 1.4 for performance reasons.

**Comment by goyetus** [comment]
Thanks for the info,  I will search it !    Regards!

**Comment by musicpanda** [comment]
For a long time Prestashop kept a flat structure as an option. I think that option was only removed in 1.7.

**Comment by PululuK** [comment]
FYI  [Deep directory structure vs. flat directory structure](https://medium.com/@hartator/benchmark-deep-directory-structure-vs-flat-directory-structure-to-store-millions-of-files-on-ext4-cac1000ca28)

**Comment by goyetus** [comment]
OHHH THANKS!!!!!  

So,  after deep reading the 1 millon test  and two millon test files from this web,  and after reading the "post"  ,   it seems that in EXT4  seems very similar all data in 1 folder or all data in 1 millon folders...

Seems faster all in one folder like before they changed it ..........   

Thanks a lot for the link!

**Comment by kpodemski** [comment]
I think we can close this issue as everything has been clearly explained :)
