### ISSUE TITLE
HomeSlider not showing

### ISSUE THREAD

**Issue by JosueDuran08z** [PrestaShop/PrestaShop#25537]
When I updated the Prestashop version from 1.7.5.1 to 1.7.7.5, my HomeSlider is not showing. I checked the files between the two versions and they are the same. I am using AN Theme.

* PrestaShop version: 1.7.7.5 
* PHP version:  7.1.33

**Comment by hibatallahAouadni** [comment]
Hello @JosueDuran08z 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: for this kind of problem, you don't need to open a new issue on GitHub :wink: just ask your question on the public Slack, and the contributors will help you. Here's the link of [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
