### ISSUE TITLE
why auto delete product?

### ISSUE THREAD

**Issue by langziyang** [PrestaShop/PrestaShop#25544]
prestashop 1.7.6.3

in `src/PrestaShopBundle/Controller/Admin/ProductController.php`

function:  `public function listAction`

i find this code:
`
$this->get('prestashop.service.product')->cleanupOldTempProducts();
`

then in   file `src/PrestaShopBundle/Service/ProductService.php`

i find 

`public function cleanupOldTempProducts()
    {
        $oldProducts = Product::getOldTempProducts();

        foreach ($oldProducts as $oldProduct) {
            $id_product = $oldProduct['id_product'];
            $product = $this->dataProvider->getProduct($id_product);
            if ($product) {
                $product->delete();
            }
        }
    }`

then in  file `classes/Product.php`

`
/**
     * Return the list of old temp products.
     *
     * @return array
     */
    public static function getOldTempProducts()
    {
        $sql = 'SELECT id_product FROM `' . _DB_PREFIX_ . 'product` WHERE state=' . \Product::STATE_TEMP . ' AND date_upd < NOW() - INTERVAL 1 DAY';

        return Db::getInstance(_PS_USE_SQL_SLAVE_)->executeS($sql, true, false);
    }
`

so , why auto delete product?

**Comment by hibatallahAouadni** [comment]
Hello @langziyang 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have
questions about PrestaShop Core, you can ask in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Closing the issue :wink: 

Thank you

**Comment by langziyang** [comment]
> Hello @langziyang
> 
> We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have
> questions about PrestaShop Core, you can ask in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).
> 
> Closing the issue 😉
> 
> Thank you

yes,i want say this is bug or not,why auto delete product

**Comment by hibatallahAouadni** [comment]
@langziyang posts your question in Public Slack, in ** dev-core ** channel. The developers or maintainers will answer you :wink:
