### ISSUE TITLE
Show applied discount in cart widget

### ISSUE THREAD

**Issue by jedzura** [PrestaShop/PrestaShop#25546]
I have a small problem with default prestashop cart widget - I just added some promo with automatic discount depends on count of items added to cart (more items = bigger percentage discount, customer doesn't have to type any code), but this discount is not showing in cart widget, only on cart page, so I have no option to show my customers that they will pay less for their order until they go to the cart page. Is there any chance to add info about applied discount to the cart widget?
The second problem I have is assigned with free delivery plugin, which shows in cart widget information how much more customer should spend to have free delivery - it calculates it using total price after discount, so then I have some disinformation - we offer free shipping for order bigger than $100 - cart widgets shows total amount $120, but delivery widget shows that for free delivery need $10 more - it is because of the 25% discount which is not showed by cart widget, so client doesn't know that until he go to the cart page.

**Comment by hibatallahAouadni** [comment]
Hello @jedzura 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by jedzura** [comment]
What? I wrote step by step what is wrong and you don't understand? Can't you add automatic promotion and see it wouldn't show discount in cart widget? Is it too hard for you? Maybe you shouldn't close this ticket and leave it for someone how know anything about prestashop?

**Comment by matks** [comment]
@jedzura Please remember everybody must follow our Code of Conduct https://github.com/PrestaShop/PrestaShop/blob/259222999174f34ada6125793cf26b84c8a4af0e/CODE_OF_CONDUCT.md

We have a template for issues. If you don't follow it, it will not be explored. https://github.com/PrestaShop/PrestaShop/issues/new?assignees=&labels=&template=1_bug_report.md
