### ISSUE TITLE
[BO] Can't save a variation product with negative quantity 

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#25545]
#### Describe the bug

On the develop branch, when you save a product variant with a negative quantity (ex: -10) then reload the page, the quantity becomes positive (ex: 10).

#### Expected behavior

The variant quantity should be negative

#### Steps to Reproduce

1. Create new product
2. Add 2 new variations:
A variation with quantity -10
B variation with quantity 10
3. Save product and reload page
4. See error => A variation with quantity 10 => NOK
5. Back to the list
6. See error => the product quantity is 20, it should be 0

**Screenshots**

https://drive.google.com/file/d/1uetwWtXEH314PMDMYYI7kjtR3C3KWv9K/view

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

---
Originally posted by @tswfi in this [comment](https://github.com/PrestaShop/PrestaShop/issues/14913#issuecomment-891091122)

**Comment by jolelievre** [comment]
I have a question, since we are finishing the new product page for the next version, is it worth investing time to fix bugs from the old page that is gonna be removed anyway?

@hibatallahAouadni is there the same problem in the new experimental page? If yes then it would be better to fix the new page instead of the old one. If not we could, maybe, close this issue.

**Comment by hibatallahAouadni** [comment]
Hello @jolelievre 

> @hibatallahAouadni is there the same problem in the new experimental page?

No, I didn't manage to reproduce the issue with the **experimental product page** on **develop**.

> I have a question, since we are finishing the new product page for the next version, is it worth investing time to fix bugs from the old page that is gonna be removed anyway?

Ping @PrestaShop/product-team could you please answer @jolelievre question :pray: 
PS: we have a PR to fix the issue :wink: 

Thanks!

**Comment by hibatallahAouadni** [comment]
@MatShir I didn't manage to reproduce the issue with PS178x, I only reproduced it with develop

**Comment by Progi1984** [comment]
@MatShir Can you explain why this issue is closed ? I didn't see any merged and linked PR. Thanks

**Comment by hibatallahAouadni** [comment]
@Progi1984 cause it has been fixed with the new Product page :wink: 

![image](https://user-images.githubusercontent.com/23308427/157073193-6d857776-b8d1-4bff-b5c9-a0a26a7a4d09.png)

---
![image](https://user-images.githubusercontent.com/23308427/157073211-842372fd-bb19-458b-a8ae-ecbc183ba686.png)

**Comment by Progi1984** [comment]
Thanks @hibatallahAouadni

**Comment by MatShir** [comment]
We did not manage to finish the product page for version 8.0. We will reopen the issue, I am sorry for the inconvenience generated

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/30512
