### ISSUE TITLE
Update bootstrap 4.6 & 5

### ISSUE THREAD

**Issue by eveneme** [PrestaShop/PrestaShop#25550]
Upgrading the bootstrap to a newer version 4.6 & 5

**Comment by matks** [comment]
Hello @eveneme you need to write more 😄 . Please be more specific about what you talk about, and provide references.

**Comment by kpodemski** [comment]
Actually, I think there's no need for the additional discussion, we know about Bootstrap, but this requires us to create the new version of the theme, and that is a more complex task :)

**Comment by hibatallahAouadni** [comment]
Hello @eveneme 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: Thanks guys for your quick replies :rocket: 

Thanks!

**Comment by eveneme** [comment]
Rewriting the template in accordance with today's standards. or making a new one. If not in this version, then in the next.

**Comment by matks** [comment]
Hi @eveneme I think this is already included in https://github.com/PrestaShop/PrestaShop/issues/14533 item. "Classic theme should promote code quality and best practices - upgrade and rework" implies to use, as much as possible, up-to-date dependencies.

But the answer is the same as for https://github.com/PrestaShop/PrestaShop/issues/25540

Such changes would break hundred of children themes being used.

Details in https://build.prestashop.com/news/prestashop-in-2019-and-beyond-part-2-pain-points

In next major version we'll do our best to upgrade bootstrap versions to a stable, standard, up-to-date version, but we'll maybe not pick the latest if it's too much changes for child themes. We must consider the upgrade process and make sure **it is as easy as possible for people to upgrade**. Dependencies update can be a big issue.
