### ISSUE TITLE
Multiple orders for single shopping cart

### ISSUE THREAD

**Issue by matiasturunen2** [PrestaShop/PrestaShop#25554]
#### Describe the bug

Calling payment return url multiple times within same second may generate multiple orders from single shopping cart.

#### Expected behavior

Only one order is generated

#### Steps to Reproduce

1. Create a demo order
2. Pay for order, inspect the return url and block the request from going into prestashop
3. Call return url you just obtained multiple times really fast. I used nodejs script for this
4. See orders page and shopping carts page that multiple orders have been created for single shopping cart

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: 7.2
* Cache disabled

**Comment by hibatallahAouadni** [comment]
Hello @matiasturunen2 

> Pay for order, inspect the return url and block the request from going into prestashop

I really don't understand why you're trying manipulating the functionality, could you please explain to me why you need to call the URL multiple times with nodejs script?
Waiting for your feedback.

Thanks!

**Comment by matiasturunen2** [comment]
In some cases payment service provider generates multiple simultaneous returns to prestashop return url. To reliably simulate this behavior I had to do the steps described above. Default behavior would be that the return url is called only once and then user is redirected to payment success/fail page. But in this case where multiple returns happen at same exact time (or very close each other) there should also be only one order created. Method used to call the return url many times within same second can be whatever you can think of, bash/nodejs/php/python etc, but the point still remains the same. There should only be one order created per cart.

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers @PrestaShop/prestashop-maintainers could someone please try to reproduce the issue, cause it's logic that **should only be one order created per cart**.

Thanks in advance :pray:

**Comment by matks** [comment]
> But in this case where multiple returns happen at same exact time (or very close each other) there should also be only one order created. Method used to call the return url many times within same second can be whatever you can think of, bash/nodejs/php/python etc, but the point still remains the same. There should only be one order created per cart.

Hi, maybe there is a concurrency issue that allows someone to generate multiple orders if the return URL is called multiple times in a very short timespan.

I did not check the code, but I guess that: in the process that happens after return URL has been called once successfully,  it persists something in database that prevents return URL future calls.

But this process takes time, maybe a few microseconds, so if you call the return URL multiple times during these few microseconds you might be able to trick prestashop.

Maybe related issues: https://github.com/PrestaShop/PrestaShop/issues/18700, https://github.com/PrestaShop/PrestaShop/issues/16490 and https://github.com/PrestaShop/PrestaShop/issues/11115

However please note the situation described above is very unlikely to happen in real life so we're talking about an exotic usecase here.

Unfortunately the environments usually used for PrestaShop are not well suited to counter such issues. Concurrency issues are well handled by environments where you can queue incoming requests, or use a mutual exclusion lock like a semaphore. PrestaShop is a php application that runs behind a web server, and such capabilities are not offered widely and easily by such environments.

We could rely on a SQL semaphore to lock the payment return URL process to be processed by only one thread, but even this I'm not sure it would be 100% reliable (for example for MyISAM usage).

So ... I'm afraid that the technical solution might be a unreliable over-engineered system to handle an exotic usecase very unlikely to happen 😅 

wdyt @PierreRambaud
