### ISSUE TITLE
ps_metrics image not loading in sub directory installation

### ISSUE THREAD

**Issue by jameswill** [PrestaShop/PrestaShop#25555]
I have installed Prestashop 1.7.7.6 on one of my test servers with PHP 7.1 and Mysql 5.6

However I am facing an issue post logging into the admin panel. There is a widget sort of thing called **"PrestaShop Metrics"** which fails to load it's image.(please refer image) On debugging I found it's loading image from **"/modules/ps_metrics/views/assets/logo-ps-metrics.7e5c2dc7.png"** which is present at the location. However when you install prestashop in a sub directory this still searches the image in "/modules/ps_metrics/views/assets/logo-ps-metrics.7e5c2dc7.png" which is I guess wrong. It should search in **"/[[subdirectory]]/modules/ps_metrics/views/assets/logo-ps-metrics.7e5c2dc7.png"**

![prestashop](https://user-images.githubusercontent.com/6368036/128824146-056c44b5-d23d-4aea-aba2-6dc55662cca9.png)

What could be the solution for this ?

**Comment by hibatallahAouadni** [comment]
Hello @jameswill 


This issue is not a PrestaShop core bug.It's related to PS Metrics.
We will contact the Addons Team to fix it as soon as possible.

We will close this issue.

Thanks for your understanding!

**Comment by jameswill** [comment]
Hi,

Is there any ETA for the same ? How much time it will take to solve this ? Do I expect new release from Prestashop soon for this ?
