### ISSUE TITLE
Bug summary cart with vouchers

### ISSUE THREAD

**Issue by Vitamixlife** [PrestaShop/PrestaShop#25552]
Dears, 
I've test this situation on a old installation (ver 1.6.6.9.) without any solutions in p.s. 1.7.7.5: the bug persist.

- Cart Rule: free shipping from 60€ otherwise you pay 7€ of shipping cost.
- Voucher: 15€ discount and "free shipping" switch of "Actions" B.O. is on.
- I've a cart with 38€ (2 items), when I apply the voucher, the cart shows: -22€ discount, shipping free, that's ok!
- 38€ - 22€ (discount+free shipping) subtotal: 23€ ??? wait: 16€ of course, not 23€.
- something is wrong, seems it to re-calculate the shipping cost, when its shows "free"
- site: bruttosito.com

![immagine](https://user-images.githubusercontent.com/87757765/128541251-e7dd8460-383a-42dc-880d-d3661342a9fd.png)

![immagine](https://user-images.githubusercontent.com/87757765/128541321-55cdc616-8070-4607-abdf-5ecfda5bb728.png)

Reference #11506

**Comment by hibatallahAouadni** [comment]
Hello @Vitamixlife 

Could you please edit your issue **following the provided template to submit a complete bug report**.
I think your issue is similar to this one #11506.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Vitamixlife 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
