### ISSUE TITLE
[Feature Request] Update Ghanaian Cedi Symbol

### ISSUE THREAD

**Issue by Mikomil** [PrestaShop/PrestaShop#25575]
Kindly update the Ghanaian Cedi symbol on Prestashop. This is the cedi symbol (¢)
 Thank You

**Comment by hibatallahAouadni** [comment]
Hello @Mikomil 

Thanks for bringing up this issue we will need to study! Could you please add it to the [User Voice](http://feedback.prestashop.com/forums/387864-prestashop-1-7-x) so that the community can vote for it.

Ping @Julievrz could you please take a look :pray: 

Thanks!

**Comment by Julievrz** [comment]
Hi @Mikomil @hibatallahAouadni 

I checked on Wikipedia and the symbol written is the same as the one used in the BO:  GH₵

 @Mikomil Do you have any official document?

**Comment by Mikomil** [comment]
> 
> I checked on Wikipedia and the symbol written is the same as the one used in the BO: GH₵
> 
> @Mikomil Do you have any official document?

Hello @Julievrz The Ghanaian Cedi Symbol is exactly what you stated but the symbol does not appear at the BO.
Thank you.
              
![Screenshot (7)](https://user-images.githubusercontent.com/86637707/129338711-8ec9f0d6-9499-4b99-afc8-0ab0528c5b72.png)

**Comment by Julievrz** [comment]
Hi @Mikomil 
What version of PrestaShop are you using?

@hibatallahAouadni maybe you can double-check but I checked on my side, in 1.7.7.5, le symbol displayed is "GHS" 

![image](https://user-images.githubusercontent.com/70583503/129342114-c0b1ae1d-0b35-4cd7-8998-dfbd07ac8cf9.png)

and in 1.7.8 the symbol displayed is GH₵

![image](https://user-images.githubusercontent.com/70583503/129342163-54c30f63-6326-4641-a0e5-ca4367905f98.png)

**Comment by Mikomil** [comment]
Hello @ Julie Varisellaz

*             Please am using the 1.7.6.7 version*

**Comment by hibatallahAouadni** [comment]
Hello @Mikomil & @Julievrz 

On 1.7.8.0, the symbol is well displayed :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/23308427/129362951-cab345c1-c7ef-4bc8-a066-0dc976753921.png)

On 1.7.7.6, the symbol is the same as ISO code :x: 

![image](https://user-images.githubusercontent.com/23308427/129363408-1f2bfd99-80de-40c0-98dc-4673763877cc.png)

On 1.7.6.7, same as 1.7.7.6 :x: 

![image](https://user-images.githubusercontent.com/23308427/129363465-947c850f-3ff3-4e79-92d2-5df35c6ea82c.png)

Please check and feedback.
Thanks!

**Comment by Mikomil** [comment]
Thank you for your prompt response. I am still not getting the symbol on
both my Website and BO. I have attached a picture of  of the exact problem.
Thank You. Regards

**Comment by hibatallahAouadni** [comment]
@Mikomil when you respond on the issue with your mail, we're not able to see the attached picture.
So please answer on Github :pray:

**Comment by Mikomil** [comment]
Thank you for your prompt response. I am still not getting the symbol on  both my Website and BO. I have attached a picture of  of the exact problem. 
Thank You. Regards
![Capture](https://user-images.githubusercontent.com/86637707/129367318-78bfe3a4-37c3-4bee-b9a3-8c8cbd11435e.JPG)

**Comment by hibatallahAouadni** [comment]
Ping @Mikomil could you please delete the currencie and that add it again, please follow my steps in the screen record below:

https://www.awesomescreenshot.com/video/4836705?key=eee3bab14c174c3a32512ed8015a567a

Thanks!

**Comment by Mikomil** [comment]
Thank you so much. Its working now🙌🙌🙌🙌🙌🙌🙌
God bless you.
Regards
Michael

**Comment by Mikomil** [comment]
Thank you so much. Its working now🙌🙌🙌🙌🙌🙌🙌
God bless you.
Regards
Michael

**Comment by hibatallahAouadni** [comment]
Glad to hear :tada: 
You're welcome :relaxed: 

Closing the issue. Thanks!
