### ISSUE TITLE
Faceted search cache needs to be invalidated when changing stock management settings

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#25587]
#### Is your feature request related to a problem?

1. Make two products, disable out of stock ordering on one of them.
2. Set up faceted search with quantity filter. Check that it works.
3. Disable stock management in Prestashop settings.
4. Go to FO, see that availability filter disappeared.
5. Enable stock management again, see that the filter does not reappear.
6. Go to faceted search config and click Clear cache. Filter will reappear. **- we need to automate this**

#### Describe the solution you'd like

Hook to any action called when updating `PS_STOCK_MANAGEMENT` and call `invalidateLayeredFilterBlockCache()` in faceted search.

#### Additional context

* PrestaShop version: develop
* Faceted search version: 3.7.1
* PHP version: 7.2

Ping @PierreRambaud

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you
