### ISSUE TITLE
Cards inside forms are using improper markup

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#25586]
#### Is your feature request related to a problem?

Cards in nearly all Prestashop forms are using improper markup. It only makes it harder to debug and increases render depth.

```
<div class="card">
  <h3 class="card-header">... form header ...</h3>
  <div class="card-block row">
    <div class="card-text">
      ... form inputs and general content ...
    </div>
  </div>
  <div class="card-footer">... save buttons etc. ...</div>
</div>
```

#### Describe the solution you'd like

- `row` without `col-` is improper markup and should be removed
- `card-block` is obsolete class used only in early boostrap 4 alpha versions
- `card-text` is a class solely for inserting text like paragraphs

There should be only be a class of `card-body`. Ideally with our own modifier to make the paddings bigger like now, like `card-body--spacious`.

```
<div class="card">
  <h3 class="card-header">... form header ...</h3>
  <div class="card-body">
      ... form inputs and general content ...
  </div>
  <div class="card-footer">... save buttons etc. ...</div>
</div
```

#### Additional context

* PrestaShop version: develop

Ping @NeOMakinG 

---
### Wishlist module => Fixed by https://github.com/PrestaShop/blockwishlist/pull/156
This block is so messy :confused: 
![image](https://user-images.githubusercontent.com/23308427/150238632-8a5c2560-7d65-4b17-9feb-da6e4167baa9.png)
### Linklist module
You should change this class `card-block row` by `card-body` and `card-text` by `form-wrapper`:
![image](https://user-images.githubusercontent.com/23308427/152352696-059683dd-d286-498a-b136-49e78924c43b.png)

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thank you for your suggestion. The Developer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

PS: @NeOMakinG do we have a GO?

Thank you

**Comment by NeOMakinG** [comment]
Yes we've a go, but it's really mandatory, there are no urgency to fix this to me

**Comment by hibatallahAouadni** [comment]
Well then, let's change it to **`To Do`** but with **`Trivial`** priority :wink:

**Comment by Hlavtox** [comment]
@hibatallahAouadni BO issue, wrong epic 😉

**Comment by hibatallahAouadni** [comment]
@Hlavtox it's not :wink: 

![image](https://user-images.githubusercontent.com/23308427/129331977-58b26649-9d51-4487-9269-b0e863e4fb03.png)

This EPIC contain the BO & FO issues :slightly_smiling_face:
