### ISSUE TITLE
Please provide a dd() (“dump and die”) helper function

### ISSUE THREAD

**Issue by gadnis** [PrestaShop/PrestaShop#25585]
#### Is your feature request related to a problem?
NO

#### Describe the solution you'd like

Thanks to symfony we already can use `dump()` helper function in prestashop. 
But symfony VarDumper component provides dd() helper function as well, which is very handy.
Why not to add it to prestashop?

**Comment by hibatallahAouadni** [comment]
Hello @gadnis 

Thank you for your suggestion. The Developer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by matks** [comment]
@gadnis Hi!

I just tried using `dd()` on FO homepage in IndexController and on BO dashboard in AdminDashboardController

```
        dd(new Product(1));
        die("it works");
```

and it works 😄

**Comment by gadnis** [comment]
@matks which PS version?

**Comment by matks** [comment]
`develop`

I think that, as long as Symfony is loaded, `dd()` is available everywhere.

**Comment by gadnis** [comment]
@matks I'm using `1.7.6.9`
Maybe develop version has it, but in production version `dd()` function is not found. 

At the moment I'm using my own helper.php where I defined `dd()` function my self.

**Comment by matks** [comment]
It's might be that because of https://github.com/PrestaShop/PrestaShop/issues/14995 we have `dd()` available everywhere from 1.7.8

As it's implemented in future versions of PrestaShop and we only ship bug fixes for past versions, I think we can close this issue 😊 . It's already "fixed" for `develop` as far as we know.

**Comment by gadnis** [comment]
Sure. Thanks ;)
