### ISSUE TITLE
Dangerous JS selectors should be removed

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#25583]
There is a lot of potentially dangerous JS selectors. We shouldn't be scared of breaking stuff when redoing the markup.

Selectors using `.row`, `.col-XXX`, `.container`, hardcoded boostrap markup into JS.

### Example
this.productsGrid = `${this.contentDiv} > div.row > div > div.row:nth-of-type(2)`;

### File list
**Admin**
https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/default/js/bundle/product/form.js
https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/default/js/bundle/product/form.js
https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/new-theme/js/pages/product/product-map.js
https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/new-theme/js/pages/order/view/order-product-renderer.ts

**Tests**
https://github.com/PrestaShop/PrestaShop/blob/develop/tests/UI/pages/BO/catalog/brands/view.js
https://github.com/PrestaShop/PrestaShop/blob/develop/tests/UI/pages/BO/catalog/products/index.js
https://github.com/PrestaShop/PrestaShop/blob/develop/tests/UI/pages/BO/catalog/suppliers/view.js

**Theme**
https://github.com/PrestaShop/PrestaShop/blob/develop/themes/_core/js/selectors.js
https://github.com/PrestaShop/PrestaShop/blob/develop/themes/_core/js/product.js
https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/_dev/js/cart.js

#### Additional information
* PrestaShop version: develop

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thank you for your suggestion. The Developer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by NeOMakinG** [comment]
> There is a lot of potentially dangerous JS selectors. We shouldn't be scared of breaking stuff when redoing the markup.
> 
> Selectors using `.row`, `.container`, hardcoded boostrap markup into JS.
> 
> ### Example
> this.productsGrid = `${this.contentDiv} > div.row > div > div.row:nth-of-type(2)`;
> 
> ### File list
> **Admin**
> https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/default/js/bundle/product/form.js
> https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/new-theme/js/pages/product/edit/product-seo-manager.js
> https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/default/js/bundle/product/form.js
> https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/new-theme/js/pages/product/product-map.js
> https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/new-theme/js/pages/order/view/order-product-renderer.ts
> 
> **Tests**
> https://github.com/PrestaShop/PrestaShop/blob/develop/tests/UI/pages/BO/catalog/brands/view.js
> https://github.com/PrestaShop/PrestaShop/blob/develop/tests/UI/pages/BO/catalog/products/index.js
> https://github.com/PrestaShop/PrestaShop/blob/develop/tests/UI/pages/BO/catalog/suppliers/view.js
> 
> **Theme**
> https://github.com/PrestaShop/PrestaShop/blob/develop/themes/_core/js/selectors.js
> https://github.com/PrestaShop/PrestaShop/blob/develop/themes/_core/js/product.js
> https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/_dev/js/cart.js
> 
> #### Additional information
> * PrestaShop version: develop

Nice work providing the list, gonna change all of these 👍

**Comment by hibatallahAouadni** [comment]
@NeOMakinG all right, we have a GO :tada: 
Gonna change the status to **`To Do`** :wink:
