### ISSUE TITLE
BO - Create product - Can't add a virtual product to a pack if the virtual product have associated file

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#25582]
#### Describe the bug
If you want to create a product pack with virtual products it is not possible to add a virtual product that has an associated file

Maybe related with : #25581 

#### Expected behavior

It should be possible to add to a pack a virtual product that has a file associated with it

#### Steps to Reproduce

1. Go to BO
2. Create a virtual product with a associated file
3. Try to create a pack with the virtual product

**Screenshots**

https://drive.google.com/file/d/1iJiPahxWX-yC65USudIqsg9wJulHjmB3/view

#### Additional information

* PrestaShop version: 1.7.7.x && 1.7.8.x
* PHP version: 7.4

**Comment by MatShir** [comment]
Fixed 8.1 new product page :)
But this bug is still present https://github.com/PrestaShop/PrestaShop/issues/25581
