### ISSUE TITLE
BO - Product V2 - An exception is displayed when creating a product with ecotax enabled

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25589]
#### Describe the bug
In the BO > Catalog > Products > when we try to add a product V2 with ecotax enabled => an exception displayed
![image](https://user-images.githubusercontent.com/16067358/129224266-2a132a15-c914-491e-82a0-2691f476f822.png)

#### Steps to Reproduce

1. Go to BO > International > Taxes page > enable ecotax
2. Go to BO > Advanced Parameters > Experimental Features page
3. Enable Experimental product page
4. Go to BO > Catalog > Products page and add a product V2
5. Set the name and save
6. See error

#### Additional information

* PrestaShop version: 1780rc1build2
* PHP version: 7.2

**Comment by MatShir** [comment]
It seems to be fixed now ! 🥳  I'm closing the issue
