### ISSUE TITLE
BO - Product V2 - Options Tab - References cannot be saved 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25590]
#### Describe the bug

In the BO > Catalog > Add/Edit product V2, in the Options Tab > the data in the References section cannot be saved.

#### Steps to Reproduce

1. Go to BO > Advanced Parameters > Experimental Features page
2. Enable Experimental product page
3. Go to BO > Catalog > Products page and add/Edit a product V2
4. In the Options Tab > References section, set all fields and save
5. Refresh the page
6. see error => data not saved

![image](https://user-images.githubusercontent.com/16067358/129231385-72a2bd12-3404-4252-9737-781a856929f6.png)

#### Additional information

* PrestaShop version: 1780rc1build2
* PHP version: 7.2

**Comment by MatShir** [comment]
It is fixed now ! :)
