### ISSUE TITLE
FO - After an upgrade to PS178, the search_bar module is not well displayed

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25594]
#### Describe the bug

After an upgrade from the previous version to PS178rc1build2, in the FO, the search_bar module is not well displayed

![image](https://user-images.githubusercontent.com/16067358/129363494-42954d44-c2bd-483a-aa93-315d88fabd9d.png)

In my case, I tried with an upgrade from PS1744 to PS1780rc1build2 + php7.1
@SD1982 reproduced the issue with an upgrade from PS1776 to PS1780rc1build2 + php7.4 

#### Steps to Reproduce

1. Install a previous version for example PS1744
2. Install the autoupgrade module v4.12.0
3. Make an upgrade to PS1780rc1build2
4. Enable the shop
5. Go to FO > see error

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 178rc1build2
* PHP version: 7.1/7.4
* Search bar version: 2.1.0

**Comment by MatShir** [comment]
We need to investigate first the issue before considering the severity. @NeOMakinG Could you take a look?

**Comment by NeOMakinG** [comment]
I investigated on this one and here is what I found:

- ps_searchbar is overridden in classic theme on 1.7.7.x branch but not on 1.78.
- When you upgrade to 1.7.8, it keep the old file, but on 1.7.8 branch the file is not existing and so the markup is wrong

**Comment by PierreRambaud** [comment]
> I investigated on this one and here is what I found:
> 
> * ps_searchbar is overridden in classic theme on 1.7.7.x branch but not on 1.78.
> * When you upgrade to 1.7.8, it keep the old file, but on 1.7.8 branch the file is not existing and so the markup is wrong

It's normal behavior if you don't update the theme.

**Comment by eternoendless** [comment]
But if you did update the theme?

**Comment by NeOMakinG** [comment]
I did choice to update the theme

**Comment by PierreRambaud** [comment]
Oh, I understand, during the update process, we never remove files. We can do nothing against that, can have a lot of side effects if we decide to do it

**Comment by eternoendless** [comment]
Even if we choose to update the default theme?

**Comment by eternoendless** [comment]
We decided that this is not a blocker for 1.7.8.0 as other themes will suffer from the same problem. In the meantime, this issue must be put forward in the release notes.

**Comment by MatShir** [comment]
Add in the search bar module at the upgrade to check if the fill exists to delete it (only if it is the classic theme)

**Comment by atomiix** [comment]
This issue should be solved by itself once the XML file containing the md5 of every files of the core will be published for version 1.7.8.0, as the autoupgrade module delete core files that don't exist anymore

**Comment by raidnet-ms** [comment]
> I did choice to update the theme

me too. same happened and I have also problem finding classic theme in frontend translations.
