### ISSUE TITLE
BO - Product V2 - Brand cannot be associated to a product

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25591]
#### Describe the bug
In the BO > Catalog > Add/Edit product V2 > it is not possible to associate or change a brand to a product V2
#### Steps to Reproduce

1. Go to BO > Advanced Parameters > Experimental Features page
2. Enable Experimental product page
3. Go to BO > Catalog > Products page and add/Edit a product V2
4. Try to select a brand
5. Save
6. Refresh the page
7. see error => data not saved

**Screenshots**
![image](https://user-images.githubusercontent.com/16067358/129232486-cde20b73-4808-46a5-951f-bc128033cbec.png)

#### Additional information

* PrestaShop version: 1.7.8.0rc1
* PHP version: 7.2

**Comment by MatShir** [comment]
It is fixed ! :)
