### ISSUE TITLE
Error when viewing a supplier

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#25593]
#### Describe the bug

An error is shown when I try to view a supplier: 

> An unexpected error occurred. [Symfony\Component\Debug\Exception\ContextErrorException code 0]: Notice: Trying to access array offset on value of type null

<img width="1792" alt="Screenshot 2021-08-13 at 11 53 18" src="https://user-images.githubusercontent.com/1009343/129339595-d55a5636-80cb-4d60-aabc-a59677eb1c9b.png">

Here's the stack trace (to see it yourself, edit line 386 in \PrestaShopBundle\Controller\Admin\Sell\Catalog\SupplierController and add `throw $e`);

<img width="1049" alt="Screenshot 2021-08-13 at 11 55 27" src="https://user-images.githubusercontent.com/1009343/129339971-0c037345-d045-4d42-9d15-948f276e20f4.png">

The method call above will execute the following query:

```sql
select product_supplier_reference, product_supplier_price_te, id_currency from ps_product_supplier where id_supplier = 2 and id_product = 3 and id_product_attribute = 0
```

It looks like there's no data for `id_product_attribute = 0`, which makes it fail. Not sure if this is a fixture error or a logic error though.

In addition, perhaps we should change `getErorMessageForException()` in FrameworkBundleAdminController so that unexpected exceptions are rethrown when in debug mode. Or at least Error exceptions (/cc @matks & @PierreRambaud)

#### Expected behavior

I would expect to be able to see the supplier or get more information about the error.

#### Steps to Reproduce

1. On a fresh install of 1.7.8.x, go to Catalog > Bands & Suppliers > Suppliers
2. Click on the "view" icon of the first supplier (Accessories supplier)
3. See error

#### Additional information

* PrestaShop version: 1.7.8.x
* PHP version: 7.4

**Comment by hibatallahAouadni** [comment]
Hello @eternoendless 

I reproduce the issue with PS1.7.8.x and (only with) PHP 7.4, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/129364724-1bb8f5de-47a8-4ded-878c-c0b136f34591.png)

So it's a kind of **regression**! Thanks @eternoendless :wink: 
I’ll add this to the debug backlog so that it’s fixed.

Thanks!

**Comment by Progi1984** [comment]
Fixed by @atomiix in #25777

**Comment by hibatallahAouadni** [comment]
Ping @Progi1984 if the PR is merged why you did reopen the issue?

**Comment by khouloudbelguith** [comment]
Upgrade issue fixed with this Pr https://github.com/PrestaShop/autoupgrade/pull/402
