### ISSUE TITLE
Support for SVG files

### ISSUE THREAD

**Issue by DracoBluee** [PrestaShop/PrestaShop#25600]
Prestashop 8.0.0 must have svg support adding a logo, favicon etc.

**Comment by eveneme** [comment]
yes, please supported SVG files

**Comment by matks** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/10600 and https://github.com/PrestaShop/PrestaShop/issues/17673 😉 

Please do a quick search before creating a new issue, someone might have already created something before 😄
