### ISSUE TITLE
Support for Node.js

### ISSUE THREAD

**Issue by eveneme** [PrestaShop/PrestaShop#25606]
Support for Node.js

**Comment by hibatallahAouadni** [comment]
Hello @eveneme 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by matks** [comment]
Hi @eveneme PrestaShop is a PHP project and this will not change.
