### ISSUE TITLE
BO - 1.7.7.6 TextWithUnitType bug

### ISSUE THREAD

**Issue by thbl** [PrestaShop/PrestaShop#25604]
In 1.7.7.6 the TextWithUnitType dosen't work properly anymore, caused by #24339 

[DOC](https://devdocs.prestashop.com/1.7/development/components/form/types-reference/text-with-unit/)

example
```
<?php

use Symfony\Component\Form\AbstractType;
use PrestaShopBundle\Form\Admin\Type\TextWithUnitType;

class SomeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('bgColor', TextWithUnitType::class, [
                'unit' => 'hex',
                'required' => false,
                'empty_data' => '#FFFFFF',
            ])
        ;
    }
}
```
In 1.7.7.6 this will return an 'TransformationFailedException' error 

> Unable to transform value for property path "bgColor": Expected a numeric.

Cause this was changed from text to number in 1.7.7.6 for some reason ? maby a mistake in https://github.com/PrestaShop/PrestaShop/commit/11e4f3429ae17101c3e38c25a6cc29e128a58f96
?

or how should one make a class like in this example after v 1.7.7.6 ?

**Comment by thbl** [comment]
@PierreRambaud

**Comment by hibatallahAouadni** [comment]
Hello @thbl 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: we ask you to follow the provided template cause we nees the steps to reproduce, your PHP version to investigate the issue, so please edit your issue then ping me to reopen it :wink: 

THanks for understanding.

**Comment by thbl** [comment]
@hibatallahAouadni this example is based on the doc provied by prestashop https://devdocs.prestashop.com/1.7/development/components/form/types-reference/text-with-unit/
so to reproduced simply use the code i have provided in my bug report, php version dosent matter it will fail on all with ps 1.7.7.6

**Comment by thbl** [comment]
@PierreRambaud @matks
Can you confirm if this is a bug or not ?
