### ISSUE TITLE
[BO] - Bad display of help-box in Virtual product tab

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#25610]
#### Describe the bug

the help-box and the label are not aligned (see the attached screenshot N°1 below)

#### Expected behavior

the label and the help-box should be aligned as 1776 (see the attached screenshot N°2 below)

#### Steps to Reproduce

1. **BO** > **SELL** > **Catalog** > **Products**
2. Click on **New product** button
3. Choose **Virtual produuct**
4. Click on **Virtual product** tab
5. Check **Yes** for **Does this product have an associated file?**
6. See error

**Screenshots**

### N°1:
![image](https://user-images.githubusercontent.com/23308427/129492128-4bc602f0-c734-4678-8fa4-7bdf36baf40f.png)

### N°2:
![image](https://user-images.githubusercontent.com/23308427/129492114-42e67f3e-eb4d-4c2e-82fa-b6df0bd89009.png)

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.2

**Comment by Hlavtox** [comment]
@NeOMakinG Move all span.help-box into form-control-label and it will be fine ;-)

**Comment by NeOMakinG** [comment]
> @NeOMakinG Move all span.help-box into form-control-label and it will be fine ;-)

Thought about something like this yeah
