### ISSUE TITLE
Initialization after AJAX loading of the ps_checkout module

### ISSUE THREAD

**Issue by ewonta** [PrestaShop/PrestaShop#25615]
Hello!
Please help, on the checkout page, the payment block is the ps_checkout module.

All payment steps are uploaded via AJAX.
After everything is loaded, the ps_checkout payment module is not initialized as on yes.

How can I reinitialize the ps_checkout module after loading the payment block via AJAX?

Thanks!

**Comment by Matt75** [comment]
Hello

You can read this : https://github.com/PrestaShopCorp/ps_checkout/blob/master/_dev/js/front/README.md

**Comment by dmitrij1988** [comment]
I read this, I lost 3 days with this problem. I am writing to you from no source, there is no information anywhere, please help.

**Comment by hibatallahAouadni** [comment]
Hello @dmitrij1988 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: thanks @Matt75 for your quick reply :superhero: 

Thanks!
