### ISSUE TITLE
Translation not showing in the Backoffice

### ISSUE THREAD

**Issue by hadran9** [PrestaShop/PrestaShop#25628]
#### Describe the bug

Hello everyone,
I'm encountering an issue when I want to translate an input which will be generated using PHP, and to be specific I'm speaking about customerForm. So my situation is that I've added an input inside the `CustomerForm.php` and I want to be able to translate this input from the BackOffice.

And I want to add that all the `Shop.Notifications.Error` doesn't show in the translation section.

And the same case apply for the `Shop.Notifications.Warning`, success and information.

#### Expected behavior

I'm expecting to see the translatable element(The added input) in the translation section of the BackOffice.

#### Steps to Reproduce

1. Go to the file **`classes > form > CustomerFormatter.php`**
2. Add the following property `private $ask_for_conf_password = true;`
3. Adding the **setter** for the property : 
```php
    public function setAskForConfPassword($ask_for_conf_password)
    {
        $this->ask_for_conf_password = $ask_for_conf_password;

        return $this;
    }
```
4. Adding the following block inside the function `getFormat()`:
```php
        if ($this->ask_for_conf_password) {
            $format['conf_password'] = (new FormField())
                ->setName('conf_password')
                ->setType('password')
                ->setLabel(
                    $this->translator->trans(
                        'Confirmation password',
                        [],
                        'Shop.Forms.Labels'
                    )
                )
                ->setRequired($this->password_is_required);
        }
```
5. Go the file `classes > form > CustomerForm.php`
6. Add the following block inside the function `validate()`: 
```php
        // Password confirmation- check if it's the same
		$passwField = $this->getField('password');
		$confPasswField = $this->getField('conf_password');
		$passwordValue = $passwField->getValue();
		$confPasswValue = $confPasswField->getValue();
		if ($passwordValue != $confPasswValue) {
            $confPasswField->addError($this->translator->trans(
                'The password and the confirmation password don\'t match', [], 'Shop.Notifications.Error'
            ));
        }
```
7. After this I'm expecting to see the input to be a translatable object in the Backoffice but I don't see it.

**Screenshots**

Here's what I can see in the backoffice : **https://jmp.sh/RMdlDrn**

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @hadran9 

Could you please check this issue #25500 seems related to yours.
Please check and feedback.

Thanks!

**Comment by hadran9** [comment]
Hello @hibatallahAouadni, First of all thank you for your quick reply.
I've already saw this issue and I didn't find anything in it that could help me, FYI I'm using the default theme of PrestaShop.

**Comment by khouloudbelguith** [comment]
Hello @hadran9,

I tried to add those lines

```
  <file original="classes/form/CustomerForm.php" source-language="en-US" target-language="en" datatype="plaintext">
    <body>
      <trans-unit id="eefb581d7c421334e62a68223c7a242a">
        <source>The password and the confirmation password don\'t match</source>
        <target>The password and the confirmation password don\'t match</target>
        <note>Line: 128</note>
      </trans-unit>
    </body>
  </file>
```

In the file `PrestaShop/app/Resources/translations/default/ShopNotificationsError.xlf`

It is ok :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/16067358/130225140-0e9b015a-6a41-4f23-9396-2491ebc60eb2.png)

Thanks to check and feedback.

**Comment by hadran9** [comment]
Hi @khouloudbelguith, thank you for your reply.

That actually worked but I don't know what to do in the id section for each new input I'll add.

I was thinking that the trans-unit will be generated automatically like the case for the TPL files but I guess I was mistaken.

So could you please give me the exact steps to follow in order to be able translate the new inputs in the future.

**Comment by khouloudbelguith** [comment]
Hi @hadran9,

I will ping our developer.
Ping @sowbiba what do you think of this issue?

Thanks!

**Comment by hadran9** [comment]
Hello @khouloudbelguith, @hibatallahAouadni, @sowbiba.
Is there anything new ?

**Comment by hibatallahAouadni** [comment]
Friendly reminder @PrestaShop/prestashop-core-developers :pray:

**Comment by hadran9** [comment]
Hello everyone @khouloudbelguith @hibatallahAouadni @sowbiba, is there anything new concerning this issue ?

**Comment by sowbiba** [comment]
Hello
The translations in the Core are extracted when we build a version and committed 
https://github.com/PrestaShop/PrestaShop/tree/1.7.7.x/app/Resources/translations/default
If you modify them, it will work but you will probably loose the modifications on the next upgrade

The fact is you don't have to modify Core files like this. You should use a hook, if there is one, or create a module to override the class you want. In the 2 cases you should use your module's domain. Module.MODULENAME.DOMAIN and embed your translation files (in php for 1.7.7 or less, in XLF or PHP in 1.7.8+)

You'll find some of the explanations in https://devdocs.prestashop.com/1.7/development/internationalization/translation/

**Comment by matks** [comment]
> The translations in the Core are extracted when we build a version and committed
https://github.com/PrestaShop/PrestaShop/tree/1.7.7.x/app/Resources/translations/default
If you modify them, it will work but you will probably loose the modifications on the next upgrade

@hadran9 When we build a new release, we launch a **scan** of all php files of PrestaShop and we look for `trans()` calls. This is how we collect all wordings we need to translate. Then we save this, and this is the list of items you can translate.

So if I am not wrong it's normal your usecase does not work. You modified a file that has already been scanned, so your modifications are not acknowledged. You need to relaunch the scan somehow, or update the files manually.

For modules it works AFAIK because we re-scan each module files every time. But not for Core. @eternoendless please tell me if I said something wrong.

**Comment by hadran9** [comment]
@matks Thank you for your answer.
Is there's a way to relaunch the scan ?

**Comment by eternoendless** [comment]
We really need to add this use case into the docs. The solution is as @khouloudbelguith and @sowbiba  said, you need to add your new wording to the default catalogue so that it shows up in the translation interface. This only needs to be done when you are adding wordings to the core translation domains, if you were doing this in a module it would be picked up automatically.

> That actually worked but I don't know what to do in the id section for each new input I'll add.

The trans-unit id is part of the XLIFF spec and you can put anything there. By convention, we use the md5sum of the original phrase. Let me do that for you:

```shell
$ md5 -s "The password and the confirmation password don\'t match"
MD5 ("The password and the confirmation password don\'t match") = 5c770f09a8e8eae4e0f3a3c8a122c548
```

The id is `5c770f09a8e8eae4e0f3a3c8a122c548`.

**Comment by hadran9** [comment]
@eternoendless Okey, Thank you for your answer.
I'll try that and I'll get back to you.

**Comment by hadran9** [comment]
Hello everyone,
I've tried the solution suggested by [@khouloudbelguith ](https://github.com/PrestaShop/PrestaShop/issue/25628#issuecomment-902619934) and @eternoendless : 
>$ md5 -s "The password and the confirmation password don\'t match"
MD5 ("The password and the confirmation password don\'t match") = 5c770f09a8e8eae4e0f3a3c8a122c548

And it's working.

I suggest to add this part in the docs like @eternoendless suggested:
> We really need to add this use case into the docs. 

Because when I was searching in the docs I didn't find any part mentioning this.

And thank you all for your time and efforts.

**Comment by hibatallahAouadni** [comment]
Glad to hear :tada: 
You're welcome :relaxed:
