### ISSUE TITLE
Problem with entering the category from the main menu on Mozilla Firefox 91.0 in Incognito mode

### ISSUE THREAD

**Issue by Cheeckk** [PrestaShop/PrestaShop#25623]
Hi 

On the website of the store placed on PrestaShop 1.7.6.1 after updating the browser Mozilla Firefox up to version 91.0 in Incognito Mode 
I cannot enter to category or any tab in main menu of the store by left-clicking as if left clicking the mouse did not cause any action.
The shopping cart in the main menu, as well as the rest of the home page, "click" correctly. Right-clicking and opening a link / tab / category in a new tab opens correctly.
On Mozilla Firefox 90.0 and other browsers (Google Chrome, Opera, Microsoft Edge) the problem does not occur at all.
Same on the other websites like for example facebook, google, pinterest, left-clicking works on Mozilla Firefox 91.0.

Has anyone had the same problem and was it somehow solved? 
What can cause this problem?

**Comment by hibatallahAouadni** [comment]
Hello @Cheeckk 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
