### ISSUE TITLE
Employee permissions to access ModuleAdminController

### ISSUE THREAD

**Issue by musaffar-patel** [PrestaShop/PrestaShop#25625]
Hi

Steps to reproduce:

Create an admin controller in a module, below is a sample controller I created:

class AdminAjaxMyModuleController extends ModuleAdminController
{
    public function ajaxProcessGetBar()
    {
        die(''success');        
    }
}

Now I login into the admin under a Super Admin account: and access the controller url with the correct security token:

http://mytest.dev/adminps/index.php?controller=AdminAjaxMyModule&token=ef8950bc6b4b3ae2e356cc48c3491916&action=getBar&ajax=true

This works as expected.

Now log into admin via non Super Admin account - e.g Logistician.  Accessing the same url (with the correct security token) will result in the following error:

Access denied.

Logistician profile has been given full rights to the module.

I can see in the database, the authorisation that for Logisitican profile, it is missing entry for "ROLE_MOD_TAB_ADMINAJAXMYMODULE_READ"

Kind Regards
Musaffar

**Comment by hibatallahAouadni** [comment]
Hello @musaffar-patel 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by musaffar-patel** [comment]
Hi

This is not a question, it is a bug report.   Prestashop Access controller only allows access to module admin controller for Super Admin and not other admin profiles, even when they have been granted access to the the module.
