### ISSUE TITLE
Updating an order's status through API, does not send the associated e-mail.

### ISSUE THREAD

**Issue by tjerry** [PrestaShop/PrestaShop#25639]
#### Describe the bug

When updating an order's status through API's /order_histories, the associated e-mail is not sent.

#### Expected behavior

If a status has an e-mail template set, it should be sent, when the status is added to an order through API.

#### Steps to Reproduce

1. Go to Statuses.
2. Set an e-mail template in any status.
3. Add that status through API to any order.

a) Get a blank XML template.

curl -X GET -d @data.xml https://(your API key)@(shop address)/api/order_histories?schema=blank >data.xml

b) Fill in the XML file.

c) Send the XML.

curl -X POST -d @data.xml https://(your API key)@(shop address)/api/order_histories

4. Confirm in Advanced->E-mail or in your inbox, that no e-mail was sent.

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.3

**Comment by tjerry** [comment]
Scratch this.
E-mail are sent by adding ?sendemail=1.

**Comment by hibatallahAouadni** [comment]
@tjerry Glad to hear :tada:
