### ISSUE TITLE
BO - Order page - Debug mode enabled - an exception is displayed when ordering a deleted product with a file customization

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25644]
#### Describe the bug

In the BO > Orders > Order details page, an exception is displayed when ordering a deleted product with a file customization

#### Steps to Reproduce

1. Create a product with a customization
- Type: file
- Label: valid label
- Required (yes/No) => Same issue
2. Go to FO > Product details page
3. Choose a file and save a customization
4. add to cart
5. Continue checkout & Place Order
6. Go to BO > Catalog > Products page
7. Delete the product created
8. Go o BO > Orders > View last order created
9. See error 

![image](https://user-images.githubusercontent.com/16067358/129935449-96776523-9679-46f4-8e5b-9fd8fc219510.png)

In the PS1769 => ok

#### Additional information

* PrestaShop version: 1775, 1776, 1777build1
* PHP version: 7.1, 7.2

**Comment by Progi1984** [comment]
Fixed in #25704 by @Progi1984
