### ISSUE TITLE
[EPIC] Upgrade batch 1

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#25647]
# Scope for the rework of the Auto-upgrade module batch 1

### Must-have
- [x] #25657
- [x] #25659
- [x] #25649
- [x] #25894
- [x] #25893

### Nice-to-have
- [x] #12435
- [x] #20097
- [x] #9564

### No priority
- [x] #27087 
- [x] #27184

--------

### Must-have
- [x] #25656
- [x] #15194
- [x] #25642
- [x] #14784 
- [x] #14781
- [x] #25654

### Nice-to-have
- [x] #21558
- [x] #25655
- [x] #23147
- [x] #26034
- [x] #26035
- [x] #25276

**Comment by gericfo** [comment]
I close this issue as we will open a new one dedicated to Autoupgrade improvments.
