### ISSUE TITLE
BO - Dashboard - Dashproducts - An exception is displayed in the console when deleting a customer that have some orders

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25646]
#### Describe the bug
In the BO > Dashboard page, an exception is displayed in the console after deleting a customer that has some orders and the table `Products and Sales` is empty

The module `dashproducts` v2.0.4 => ok
![image](https://user-images.githubusercontent.com/16067358/130040189-9e1ff301-9e1d-4b10-a6d2-ae15a6d6992f.png)

The module `dashproducts` v2.1.1  => nok
![image](https://user-images.githubusercontent.com/16067358/130040511-b62959f6-582c-408d-888e-4b9d123d70fe.png)

An exception is displayed in the console 
![image](https://user-images.githubusercontent.com/16067358/130040417-6d7dcc42-99bc-4161-8752-0d87ff31877c.png)

#### Steps to Reproduce

1. Go to BO > Modules > Module manager page & check that the `dashproducts`'s version is 2.1.1
2. Create an order with a customer
3. Go to BO > check the table `Products and Sales` > The order is displayed in the Recent Orders
3. Delete this customer
4. Go to BO > check the table `Products and Sales` 
5. See exception in the console

#### Additional information

* PrestaShop version: 1769, 1777
* PHP version: 7.1, 7.2
* The module `dashproducts` version: 2.1.1

**Comment by Progi1984** [comment]
Fixed in PrestaShop/dashproducts#33 by @Progi1984
