### ISSUE TITLE
Check the maintenance mode activation

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#25642]
### Describe the bug

It says that the store is in maintenance mode while it's not. 

### Steps to Reproduce

1. Go to Shop parameters > General > Maintenance
2. Put the "enable shop" toggle on "yes"
3. Go to the auto-upgrade module
4. See error: the "Your store is in maintenance mode" line is ✅ while the shop is not in maintenance mode

<img width="309" alt="Capture d’écran 2021-08-19 à 14 14 57" src="https://user-images.githubusercontent.com/13449658/130066723-9cc374df-5116-4a90-9cb5-d78fb715b1d0.png">

<img width="1201" alt="Capture d’écran 2021-08-19 à 14 14 32" src="https://user-images.githubusercontent.com/13449658/130066708-86e7edad-6df5-4125-bdba-3cd7dc78ae7e.png">

### Wanted behavior

**As a user, I want to know if my store is well in maintenance mode before starting the upgrade**

1. Rename "Your store is in maintenance mode" by "Enable maintenance mode and add your maintenance IP in Shop parameters > General > Maintenance"

2. We should add a link on "Shop parameters > General > Maintenace" redirecting to the page where there is the option to disable the shop and add a maintenance IP address

3. We should check that the store is well in maintenance mode and if an IP address has well been added. If it's not the case, this step should not be ✅ but rather ❌ and don't allow to start the upgrade

4. If the multistore is enabled and if there are many stores, we should verify that all the shops are well in maintenance mode.

5. In local environment, it's not necessary to verify if the shop is in maintenance mode or not.

Mockups: https://www.figma.com/file/GpRsUUCHcdhJPAaz7Eqzes/Autoupgrade?node-id=497%3A11710

**Comment by Hlavtox** [comment]
@marionf It works fine in my case (v4.12, 1.7.8 beta). If you click the button, it enables the maintenance right away.

![Výstřižek](https://user-images.githubusercontent.com/6097524/131109420-e8493165-7553-4386-8a28-303153e678dd.JPG)

**Comment by ghost** [comment]
@marionf 

I agree with @Hlavtox this option works but if you are on a local environment there is a hack that says we are in maintenance

```
    /**
     * @return bool
     */
    private function checkShopIsDeactivated()
    {
        return
            !Configuration::get('PS_SHOP_ENABLE')
            || (isset($_SERVER['HTTP_HOST']) && in_array($_SERVER['HTTP_HOST'], array('127.0.0.1', 'localhost', '[::1]')));
    }
```
    
This method say your are always in maintenance mode if your url is 127.0.0.1 or localhost.

Can you clarify the issue.

Regards

**Comment by marionf** [comment]
Hello @okom3pom 

Thank you, I didn't know there was a hack for local environments, and I don't see the goal of this 🤔 
I think we can remove it, unless if you see an interest to keep it ?

**Comment by PrestaEdit** [comment]
Fact is that the "Is in maintenance mode" doesn't need to be shown, in this specific user case.

As you are on local instance, there is no real need to enable a maintenance mode when you do an upgrade.

**Comment by atomiix** [comment]
I agree with @PrestaEdit, we could remove the line in case we are in local. It's quite useful to not have to put the shop in maintenance mode to test the autoupgrade process.

**Comment by marionf** [comment]
Thank you for your feedbacks, I just edited the "wanted behavior" part of the issue
