### ISSUE TITLE
Deactivation of non-native modules

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#25649]
### Describe the bug

The feature to Disable non-native modules in the auto-upgrade module is not working.
⚠️ [The feature to disable non native-in modules](https://github.com/PrestaShop/PrestaShop/issues/9965) in the Advanced parameters > Performance page is also not working and should be fixed before.

According to @Progi1984 it's because it's looking for information in the install folder which must be renamed or deleted after installing PS.
@eternoendless said that we should rather use the composer.json to disable all non native-in modules

### Expected behavior

**As a user making an upgrade, I want to be able to disable my non native-in modules before the upgrade to ensure its success.**

When the option is enabled, we should identify native modules in the destination version, then disable all modules in the current version that aren't found on that list to prevent them to crash the upgrade or the store once the upgrade has been done.

Mockups: https://www.figma.com/file/GpRsUUCHcdhJPAaz7Eqzes/Autoupgrade?node-id=497%3A11710

### Steps to Reproduce

1. Install & configure the auto-upgrade module
2. Put "Disable non-native modules" on "Yes"
3. Go in Modules > Modules manager
4. See that non-native modules are not disabled
5. Lunch the upgrade
6. Go in Modules > Modules manager in your upgraded store
7. See that non-native modules are not disabled

**Comment by eternoendless** [comment]
To go a little further on what @marionf said, ideally we should identify native modules in the _destination_ version, then disable all modules in the _current_ version that aren't found on that list.

**Comment by Progi1984** [comment]
@matthieu-rolland You are now unlocked :unlock:
