### ISSUE TITLE
DevTools failed to load source map

### ISSUE THREAD

**Issue by eveneme** [PrestaShop/PrestaShop#25643]
#### Describe the bug

DevTools failed to load source map: Could not load content for https://three-veil.demo.prestashop.com/modules/blockreassurance/views/dist/front.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://three-veil.demo.prestashop.com/modules/blockreassurance/views/dist/front.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://three-veil.demo.prestashop.com/themes/core.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

This is your demo site so the problem is prestashop.

Screens: https://ibb.co/CQP6td4

**Comment by hibatallahAouadni** [comment]
Hello @eveneme 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: we need those steps to reproduce the issue.

Thanks!
