### ISSUE TITLE
Check if the module is up to date

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#25641]
**As a user, I want to know if my module is up to date to be able to move to the next step to start the upgrade and ensure its success.**

1. In the welcome step, we should check that the module is well up to date (if it's not the case, the user should not be able to go to the next step). 

2. We should add a link redirecting to the Module Manager page > Updates tab to let the user upgrade his module

**Comment by Quetzacoalt91** [comment]
@gericfo & @MatShir is this issue still relevant? The module version check exists since Feb 2022 https://github.com/PrestaShop/autoupgrade/pull/451

**Comment by gericfo** [comment]
You are right @Quetzacoalt91  
The autoupgrade module version is checked. This is an old topic from 2019. We can close it!
