### ISSUE TITLE
Display the compatibility between PS versions and PHP versions

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#25659]
**As a user making an upgrade, I want to know which PS version is compatible with which PHP version to know if I need to upgrade my PHP version to upgrade my store to a PS version**

In the "Expert mode" block, under the "changelog" we should display the table of compatibility between PS versions & PHP versions

Mockups: https://www.figma.com/file/GpRsUUCHcdhJPAaz7Eqzes/Autoupgrade?node-id=497%3A11710

**Comment by ghost** [comment]
Hello @marionf i am ok to work on this issue but i don't know the way when the prestashop version is not compatible with the php version i don't see on https://www.figma.com/file/GpRsUUCHcdhJPAaz7Eqzes/Autoupgrade?node-id=497%3A11710

An other question for the devs but i can ask the dev team.

I put all the informations in an array or the informations come from another way ? 

If you can ask for me the devs

And why not just say your php version is not compatible with the new PrestaShop Version ? it's more readble ?

PS : A lots of prestashop 1.6 works on php 7.3 or 7.4 
Regards

**Comment by marionf** [comment]
Hello @okom3pom 

I added the mockup directly in the issue.

FYI, the table is static and given as an example: it does not change depending on the version of php or on the targeted version of PS selected for the upgrade.
As you can see there is a text just above to explain it: "Your PHP version must be compatible with both your current PrestaShop version and the one you want to upgrade to.
For example, if your current version is 1.6.1.x and you want to upgrade to 1.7.8, only the PHP 7.1 would be with both."

About your other question, I let @matthieu-rolland answer ;)

**Comment by marionf** [comment]
Hello @okom3pom 

Following your feedback, we updated the table as you can see below:

<img width="889" alt="Capture d’écran 2021-10-08 à 14 47 37" src="https://user-images.githubusercontent.com/13449658/136560409-defea228-1c9f-4f7b-9be0-af17519efb46.png">

We don't know the minimum and maximum versions of php compatible with the versions lower than 1.6.1.18, so we don't indicate them in the table.

**Comment by gericfo** [comment]
We are currently working ont this topic with our Autoupgrade improvment task.
