### ISSUE TITLE
Display the details of errors if PrestaShop requirements are not satisfied

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#25654]
#### Is your feature request related to a problem?

The line "PrestaShop requirements are not satisfied." ❌  is not really helpful and don't allow to know what's wrong.

#### Describe the solution you'd like

**As a user making an upgrade, I want to be able to upgrade my store only if all PrestaShop requirements are satisfied to ensure the success of the upgrade**

The user should not be able to upgrade if there is an error:
- The error "PrestaShop requirements are not satisfied." is displayed
- The button "upgrade PrestaShop now" should be disabled 
- The user should not be able to ignore the errors (the button "ignore" should be removed)

We should specify what are the errors according to the case by displaying a line for each error ❌  

The errors specified can be:
- Your current PHP version isn't compatible with your PrestaShop version.
- Apache mod_rewrite is disabled.
- The PHP extension pdo_mysql, intl, curl, json, simplexml, zip, fileinfo, mbstring, opensssl_encrypt is/are not installed (display only the one(s) that are not installed). 
- PHP memory_limit is inferior to 256 MB.
- PHP file_uploads configuration is disabled.
- The PHP function fopen, fclose, fread, fwrite, rename, file_exists, unlink, rmdir, mkdir, getcwd, chdir, chmod, imagecreatetruecolor is/are not installed. (display only the one(s) that are not installed)
- It's not possible to create a PHP session.
- The following files are missing (display only the one(s) that are missing):
/classes/log/index.php
/classes/cache/index.php
/config/index.php
/controllers/admin/AdminLoginController.php
/download/index.php
/js/tools.js
/js/jquery/plugins/fancybox/jquery.fancybox.js
/localization/fr.xml
/mails/index.php
/modules/index.php
/override/controllers/front/index.php
/pdf/order-return.tpl
/translations/export/index.php
/webservice/dispatcher.php
/index.php
/vendor/autoload.php
- It's not possible to write in the following folders: (display only the one(s) that are not writable):
var/cache/ (and all the subfolderss)
var/logs/
img/ (and all the subfolders)
modules/ (and all the subfolders)
themes/<currenttheme>/lang/ (and all the subfolders)
themes/<currenttheme>/pdf/lang/ (and all the subfolders)
themes/<currenttheme>/cache/ (and all the subfolders)
translations/ (and all the subfolders)
upload/
download/
app/config/ (and all the subfolders)
config/
mails/ (and all the subfolders)
app/Resources/translations/

Mockups: https://www.figma.com/file/GpRsUUCHcdhJPAaz7Eqzes/Autoupgrade?node-id=497%3A11710

![Capture d’écran 2021-09-15 à 18 18 13](https://user-images.githubusercontent.com/13449658/133470967-a60c6215-ae3b-4bcc-92b6-cf68f360eddf.png)

**Comment by thomas298** [comment]
Hello, i think the button "ignore" in the requirements should be reinstalled because, for example, my server has a memory limit of 192MB and for 2-3 years now i choose to ignore it, proceed with the upgrade and never had a problem. In the case i had a problem i could always fallback to a backup which i never had to do. Now it is impossible to upgrade unless i change the hosting server.
I am pretty sure that this will be a problem with other small sites like mine that otherwise could upgrade without any problem.
Thanks for considering my request.
