### ISSUE TITLE
Display a modal before lunching the upgrade to let the user verify the PHP compatibility

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#25657]
**As a user making an upgrade, I want to be sure that my PHP version is compatible with my current PS version and the one to which I want to upgrade**

- If the user clicks on "upgrade now" (no matter the channel selected), we should display a modal to remind him/her to verify the compatibility of his/her PHP version with PS:
- Modal title: “Are you sure you want to upgrade to %version% ?”
- Modal content: “Make sure that your PHP version is compatible with both your current PrestaShop version and the one you want to upgrade to.”
- Modal CTA: "Cancel" and "Upgrade"

Mockups: https://www.figma.com/file/GpRsUUCHcdhJPAaz7Eqzes/Autoupgrade?node-id=497%3A11710

**Comment by marionf** [comment]
Hello @okom3pom 

Following your feedback, we decided to not prevent the upgrade if the version of PHP is not compatible with the version of PS to which the user wishes to upgrade.
But rather to display a modal, in any case, to remind the user to check that his/her version of PHP is compatible with his/her PS version (current and the one he/she wants to upgrade)
I just update this issue and the mockups are also up to date ;)

**Comment by matthieu-rolland** [comment]
Done in this PR:  https://github.com/PrestaShop/autoupgrade/pull/412

**Comment by gericfo** [comment]
We are currently working on this improvment on Autoupgrade module.
