### ISSUE TITLE
Display the current PHP version

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#25656]
**As a user making an upgrade, I want to know what is my current PHP version before starting the upgrade to know to which version I can upgrade**

In the "Start yout upgrade" block, display "Your current PHP version: X.X" just before "Your current PrestaShop version"

Mockups: https://www.figma.com/file/GpRsUUCHcdhJPAaz7Eqzes/Autoupgrade?node-id=497%3A11710

**Comment by ghost** [comment]
https://github.com/PrestaShop/autoupgrade/pull/411
