### ISSUE TITLE
Theme layouts not preserved when changing theme

### ISSUE THREAD

**Issue by gray-b** [PrestaShop/PrestaShop#25660]
When changing from one theme to another, in my case from Transformer theme to Default theme, and then back again, all the layout and modules positions have been removed from the layouts.

You have to go back into every hook and rehook or alter the position, in fact nothing is preserved in the change over.

One would not have expected any thing to have been lost. This is a major flaw in Prestashop, and a big balls aching job to get all back again correct.

The 1st 3 images are the actual shop page, followed by the 4th image being after going from the Default theme back to Transformer theme.

![PS-theme-layouts1](https://user-images.githubusercontent.com/22105014/130133202-85ad9c01-7d3e-414f-b347-383ff966c8a2.jpg)
![PS-theme-layouts2](https://user-images.githubusercontent.com/22105014/130133195-80e347a4-8e9f-454e-9b22-712dcc240bbb.jpg)
![PS-theme-layouts3](https://user-images.githubusercontent.com/22105014/130133191-383fc255-c85e-471b-a234-55c49ad4ab86.jpg)

**4th image**

![PS-theme-layouts4](https://user-images.githubusercontent.com/22105014/130133533-86e97a9b-c87a-4381-bd94-69764061bddc.jpg)

* PrestaShop version: All
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hello @gray-b,

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you!
