### ISSUE TITLE
FO: Classic Theme: Wrong product image size loaded when clicking on thumbnail

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#25663]
### Describe the bug

On FO/Classic theme, in product page, when clicking on one of a product's thumbnails it loads the image in the `large_default` format instead of `medium_default` format.

### Expected behavior

It should load the `medium_default` image size, not the `large_default`

### Steps to Reproduce

1. In FO, go to a product page
2. In the browser's console, check that the main image's is at `medium_default` size (based on the name of the file, see capture)
3. Click on a thumbnail under the main image: the main image is now at `large_default` size (based on the name of the file, see capture), it should not

### Screenshots
<img width="585" alt="Capture d’écran 2021-08-20 à 10 10 37" src="https://user-images.githubusercontent.com/1784781/130202336-eb52d550-7de0-45e7-96a7-2917493f3496.png">

As you can see here, the image size is visible on the name of the file, in the console:

<img width="886" alt="Capture d’écran 2021-08-20 à 10 13 32" src="https://user-images.githubusercontent.com/1784781/130202866-d2e7e04f-1315-4f2b-8cab-eb025563fe24.png">
<img width="925" alt="Capture d’écran 2021-08-20 à 10 15 07" src="https://user-images.githubusercontent.com/1784781/130202882-d2e24469-9e1d-44fd-982d-f30fe80545ab.png">

#### Additional information

* PrestaShop version: 1.7.8.x

**Comment by khouloudbelguith** [comment]
Hi @matthieu-rolland,

Thanks for the issue.
I manage to reproduce the issue with PS1769 and PS1777
![image](https://user-images.githubusercontent.com/16067358/130211382-5ac4dd3a-bff2-4f02-8e83-70bfa395b5fc.png)

Thanks!

**Comment by eternoendless** [comment]
Fixed by #25665
