### ISSUE TITLE
Duplicate invoice generated for each order

### ISSUE THREAD

**Issue by skills-up** [PrestaShop/PrestaShop#25661]
#### Describe the bug

Hello,

On my development site with recent prestashop version (1.7.7.6) with default settings, a duplicate invoice is generated each time an order is paid. I get an invoice #IN000000 for the same amount as the actual invoice. This also results in a warning that 2x amount has been paid instead of x.

#### Expected behavior

Only a single invoice with the correct invoice number should be generated. The order shouldn't appear to have been paid twice.

**Screenshots**
![image](https://user-images.githubusercontent.com/27212393/130153466-463cb702-0c65-4bc5-8cd0-774c74f8e64b.png)

#### Additional information

* PrestaShop version: 1.7.7.6
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @skills-up,

Thanks for the issue.
I did not manage to reproduce the issue with PS1777 using the Payment by check module and Paypal module.
I attached a screen record
https://drive.google.com/file/d/1CU65NWIAdbSY4cZoBXnb_hxDxfX-xLhX/view?usp=sharing

Do you have the same issue when using another payment module?
Have you tried to contact the "AstroPay For Prestashop" author?

Thanks to check with them and feedback.

**Comment by skills-up** [comment]
Hello @khouloudbelguith 

The problem is not reproducible with *AstroPay for Prestashop* either, if I manually change the order status. It is the actual payment flow where the problem manifests.

I've found multiple similar issues during my search, and all recommended unchecking the "Set the order as paid." for Order Status *Payment accepted* in Order Settings. That does solve the problem of duplicate invoice and the warning. But then no invoice is generated, unless I do it manually.

Could you please check the issue with the actual payments instead of manually changing the order status?

Thanks!

**Comment by khouloudbelguith** [comment]
@skills-up, thanks for your feedback.


> Could you please check the issue with the actual payments instead of manually changing the order status?

I tried to create an order with COD module.
Thanks to check my record and feedback.
https://www.awesomescreenshot.com/video/4919098?key=7c61d1a75a2284557766afd8bf474b4d

Thanks!

**Comment by skills-up** [comment]
@khouloudbelguith 

In my opinion, COD module works entirely differently, in the way that the order doesn't go through PS_OS_PAYMENT state. 

For all the threads I've read so far pertaining to the similar issues, the issue specifically appears to be linked with PS_OS_PAYMENT state.

So, if you could please check with paypal module or some other payment method, where the payment happens before order confirmation, I believe you will be able to see the issue.

**Comment by khouloudbelguith** [comment]
@skills-up, yes, I tried with paypal module in my first comment => ok
Here's my screen record
https://drive.google.com/file/d/1D6AKNg_tqP_9P5DVSvTOAvD6-9xlrCDq/view?usp=sharing

Thanks!

**Comment by skills-up** [comment]
Thanks @khouloudbelguith 

I'll close this issue as it's not re-creatable at your end.
I'll keep looking for the reasons as to why it might be happening, as I've tried with another payment method, and the issue persists on my installation.

**Comment by skills-up** [comment]
BTW, forgot to mention: I didn't face this issue on version 1.7.7.1 (another test installation), only on 1.7.7.6.
