### ISSUE TITLE
Product taxes incorrect in the credit note

### ISSUE THREAD

**Issue by Innlog85** [PrestaShop/PrestaShop#25678]
#### Describe the bug

The total product tax calculated in the credit note differs from that calculated in the invoice

#### Expected behavior

The two taxes should be the same

#### Steps to Reproduce

Generate a credit note for an order in the backoffice
![image](https://user-images.githubusercontent.com/89395832/130455223-968b5dfb-fd66-4324-b576-c01e4fb62b37.png)

**Screenshots**

Credit note total : 7.69
![image](https://user-images.githubusercontent.com/89395832/130452793-50aa296f-b423-4df6-94ba-86ba8d70e8f6.png)

Invoice total : 7.73
![image](https://user-images.githubusercontent.com/89395832/130452939-36578ad8-a1ee-431f-a5fb-4d0d147102d2.png)

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @Innlog85 

Could you please check this issue #23821 cause it seems similar to yours.
Please check this [comment](https://github.com/PrestaShop/PrestaShop/issues/23821#issuecomment-810448287) and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Innlog85 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
