### ISSUE TITLE
BO - Employee page - the gravatar is NOK

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25677]
#### Describe the bug

The gravatar is not displayed on the employee page and in the dropdown-menu-right show 
![image](https://user-images.githubusercontent.com/16067358/130449937-7c024730-b42e-43de-a107-769a0c95c015.png)

#### Steps to Reproduce

1. Go to BO > Advanced Parameters > Employees page
2. Edit your profile
3. Enable gravatar and save

This is a new feature in PS178

#### Additional information

* PrestaShop version: 1780rc1build3
* PHP version: 7.1, 7.3

**Comment by Progi1984** [comment]
@khouloudbelguith It is normal. 

As mentionned in the documentation of Gravatar (https://fr.gravatar.com/site/implement/images/), if you are on a local server, the image can't be displayed.

![image](https://user-images.githubusercontent.com/1533248/131669931-0f42e067-75da-467c-99cf-8ba201adbeda.png)

So I will close this issue.
