### ISSUE TITLE
Context::getComputingPrecision currency not initialized (see also #18789)

### ISSUE THREAD

**Issue by ivordurham** [PrestaShop/PrestaShop#25670]
#### Describe the bug
```
Fatal error:  Uncaught TypeError: Argument 1 passed to PrestaShop\PrestaShop\Core\Localization\CLDR\ComputingPrecision::getPrecision() must be of the type int, null given, called in MYSHOP/override/classes/Context.php on line 467 and defined in MYSHOP/src/Core/Localization/CLDR/ComputingPrecision.php:41
```

#### Expected behavior

No Exception!

#### Steps to Reproduce

I'm using the Stamps.com "stamps.php" plugin to enumerate orders. See https://stamps.custhelp.com/app/answers/detail/a_id/3327/~/how-to-connect-to-prestashop

Requires a POST to MYSHOP/PATH_TO_PLUGIN/stamps.php with the following parameters:
action = getorders
username = (Prestashop employee email)
password = (Employee's password)
start = (Date in YYYY-MM-DD format)

It should return an XML document enumerating the PrestaShop orders received since the specified start date.

However, an additional fix to stamps.php is needed to correct a bug in authenticating the user in PS 1.7. (This is not a PrestaShop problem, but the fix is necessary to be able to test this). In stamps.php function checkAdminLogin, replace:

```
$sql = new DbQuery
...
if ($employeeId)
{
...
}
```

with:
```
$employee = new Employee();

if ($employee->getByEmail($username, $password)) {
    $loginOK = true;
}
```
#### Additional information

* PrestaShop version: 1.7.7.7
* PHP version: 7.4.22

I fixed this by overriding Context.php and inserting: 

`$this->currency = $this->currency ?? new Currency(Configuration::get('PS_CURRENCY_DEFAULT'));`

before line 467:

`$this->priceComputingPrecision = $computingPrecision->getPrecision($this->currency->precision);`

copying the fix for #18789. This may not be the most appropriate place to fix this; I just don't know enough of the design/implementation to know if there is a more appropriate place for this initialization  to be done.

**Comment by Matt75** [comment]
Hello

This script is outdated, it should be inside a module and called by a ModuleFrontController to access the service container in order to works with CLDR.

You can find documentation to create a module here: https://devdocs.prestashop.com/1.7/modules/

Advice: you should manage authentication inside ModuleFrontController::checkAccess()  then put your logic into ModuleFrontController::postProcess()

**Comment by ivordurham** [comment]
Thanks for the advice. 
I understood that my patch was probably not the right solution. Unfortunately, this script is provided to Stamps.com by interapptive.com/ShipWorks, so I'm trying to reach both about this and several other bugs that are manifest with more recent PS releases. 
At this time the standalone script is still being advertised to Stamps.com customers and I needed to get it working with PS 1.7. Stamps.com does have a PrestaShop module, but it currently doesn't do anything other than add a link to their site and the module is currently totally separate from their integration script, presumably because they get that from a third party.

**Comment by hibatallahAouadni** [comment]
Hello @ivordurham 

Could you please downgrade your PHP version to 7.3 cause PS1777 is not compatible with PHP7.4 (see our [sysem requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart)).
Please check and feedback.

PS: @Matt75 thanks for your quick reply :wink: 

Thanks!

**Comment by ivordurham** [comment]
I am conscious of the PHP version requirements; I'm working on the 1.7 re-design of our deployment in preparation for the release of 1.7.8. Although downgrading PHP is tricky in my development environment, I believe I can clone the deployment into a different environment where I can reproduce my tests with PHP 7.3. It may take a day or so though. 

I will note that none of the issues I've encountered with Stamps.com's stamps.php "plugin" *appear* related to the PHP language since it is supposed to be backwards compatible to PS 1.4 and all the problems I've had to resolve so far have been due to evolutionary, but backwards-incompatible PrestaShop changes. 

All this ignores the overarching need for that "plugin" to be repackaged to properly fit the PS architecture, of course, but it's a piece of third party software and my concern has just been getting it to work for our shop.

**Comment by hibatallahAouadni** [comment]
ok, waiting for your feedback!

**Comment by ivordurham** [comment]
I have repeated my tests as requested with PHP 7.3.29 with the same results: The "stamps.php" script from Stamps.com  (with some fixes to maintain compatibility with PS 1.4 through 1.7) fails with the original PrestaShop 1.7.7 classes/Context.php and works with my patched version of Context.php. The original Context.php generates the following error:


Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error:
Argument
1 passed to PrestaShop\PrestaShop\Core\Localization\CLDR\ComputingPrecision::getPrecision()
must be of the type int, null given, called in /home/cathouse/public_html/shop_v17/override/classes/Context.php
on line 467 in /home/cathouse/public_html/shop_v17/src/Core/Localization/CLDR/ComputingPrecision.php:41

Stack trace:
#0 /home/cathouse/public_html/shop_v17/override/classes/Context.php(467): PrestaShop\PrestaShop\Core\Localization\CLDR\ComputingPrecision-&gt;getPrecision(NULL)
#1 /home/cathouse/public_html/shop_v17/classes/order/Order.php(607): ContextCore-&gt;getComputingPrecision()
#2 /home/cathouse/public_html/shop_v17/classes/order/Order.php(660): OrderCore-&gt;setProductPrices(Array)
#3 /home/cathouse/public_html/shop_v17/stamps.php(486): OrderCore-&gt;getProducts()
#4 /home/cathouse/public_html/shop_v17/stamps.php(379): WriteOrder(Object(Order))
#5 /home/cathouse/public_html/shop_v17/stamps.php(150): Action_GetOrders()
#6 {main} in /home/cathouse/public_html/shop_v17/src/Core/Localization/CLDR/ComputingPrecision.php on line 41


With the following patch to Context.php, it works as expected with PHP 7.3.29: (and 7.4.22)

diff ../../classes/Context.php ../../override/classes/Context.php 466a467
$this->currency = $this->currency ?? new Currency(Configuration::get('PS_CURRENCY_DEFAULT'));
sum ../../classes/Context.php 45059    14

**Comment by khouloudbelguith** [comment]
Hi @ivordurham,

Thanks for your feedback.
So as I understand you are using `Stamps.com` to get the list of orders via API in XML.
I tried to use Postman following these steps:
1. Install PS1777
2. Go to BO > Advanced Parameters > Webservice page
3. Enable Webservice and create new Webservices key
4.  Use the postman with this link "Get": `http://prestashop.com/1777/api/orders?display=full&filter[date_add]=[2021-05-24,2021-08-28]&date=1&output_format=XML&ws_key=code`

I have the exact XML with no errors: 
![image](https://user-images.githubusercontent.com/16067358/131107285-db00c080-e404-4994-923d-7b785a6d63a1.png)

Could you please correct me?

Thanks!

**Comment by ivordurham** [comment]
First let me reiterate that we're talking about a piece of third party
software which I'm just trying to get working for our shop in preparation
for moving from an old PS 1.4 deployment to a PS 1.7 deployment. I've found
a number of "software rot" issues for which I've found an alternate
implementation which is compatible across the versions. The issue at hand
is the exception I (re-)documented with the PHP 7.3 test results.

The stamps.php plugin is NOT using the API to generate an XML order
description, it is generating its own XML. The cause of the fatal exception
is a call to $order->getProducts() (see the call stack I reported). This
works with PS 1.4. On PS 1.7 it generates the exception I reported because
the Context $currency field is not properly initialized. So I adapted a fix
for the same problem (uninitialized currency) from a similar bug report to
ensure that $this->currency is properly initialized before referencing
$this->currency->precision which is being passed to
ComputingPrecision->getPrecision(...). I've demonstrated that the exception
occurs with the released Context.php and that it works with my one-line
addition. If this problem should be fixed elsewhere, I'll need guidance on
where that should be; I'm not a PS developer.

There's an argument to be made that the stamps.php "plugin" needs to be
re-engineered to better fit into the PS architecture, but that's outside my
responsibility, which is solely to get PS 1.7 working for our shop.

So the net question is whether or not I've stumbled onto an actual bug and,
if so, is the proposed fix adequate? If it's not adequate, what would be a
better fix that I can apply instead?

**Comment by matks** [comment]
> First let me reiterate that we're talking about a piece of third party software which I'm just trying to get working for our shop in preparation for moving from an old PS 1.4 deployment to a PS 1.7 deployment. I've found a number of "software rot" issues for which I've found an alternate implementation which is compatible across the versions.

Indeed I think there might be quite a long list of things that changed between PS 1.4 and PS 1.7 . The 1. in front of version number means nothing, so actually 1.4 and 1.7 are 3 major versions apart.

It's like trying to find some 3rd party software compatible with Drupal 2 to 5.

> called in /home/cathouse/public_html/shop_v17/override/classes/Context.php

Warning: it seems you are not using the original Context class but a custom replacement -> see https://devdocs.prestashop.com/1.7/modules/concepts/overrides/

> With the following patch to Context.php, it works as expected with PHP 7.3.29: (and 7.4.22)

This fix seems fine, but I think it has 1 issue: you handle the "missing currency object" problem in Context. This Context class is a core piece of PrestaShop. So here you will impact not only the logic where a missing currency object happens during Stamps execution but any moment in your shop behavior where a missing currency object happens. This could create weird situations.

I would suggest maybe to use this logic only in a code line where you're sure it's only called during your runtime.

Moreover I'm afraid this is a fix that tries to patch the unwanted data state, but it's hiding the real issue which is "why is there no currency ?"

Currency is loaded when PrestaShop is given the information "what currency should be used". It can fetch this information from employee cookies, it can be set manually, it can be parsed from browser storage...

I'll be honest: adapting this 3rd party Stamps script from PS 1.4 to 1.7 might be a challenge 😅  as many years separate the two versions, so the number of behavior changes between the two versions can be probably counted in thousand.

**Comment by ivordurham** [comment]
Thank you. I'm now clear my naive patch is the wrong place to address the
missing currency issue. The reason it's missing is that the "plugin" is not
called via any user interface, so the normal route for setting it isn't
followed. Instead it is called asynchronously directly from a Stamps.com
server when it receives a request to pull orders from the shop (according
to our webserver logs). I have already found backwards-compatible
implementations for the other functionality that broke with PS 1.7.  So
I'll look for an example of how to set the currency in the plugin itself so
it is properly initialized before the $order->getProducts() call triggers
the problem.

**Comment by ivordurham** [comment]
I've replaced the incorrect Context override by copying a line from
webservice/dispatcher.php into the stamps.php plugin, conditioned on the
availability of the Context class. This works for 1.4 (no Context) and1.7
(and, I suspect, versions in between).

if (class_exists('Context')) {
    Context::getContext()->currency = Context::getContext()->currency ??
new Currency(Configuration::get('PS_CURRENCY_DEFAULT'));
}

I appreciate the guidance.

**Comment by khouloudbelguith** [comment]
Hi @ivordurham,

On this github repository there is no software support. This is an open source project.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have
questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com/).

I will close the issue.
Thanks for your understanding!

**Comment by softhightech** [comment]
Hello,
I fixed the issue by updating the class context
Go to classes/context.php line 498 
Look for  : $computingPrecision->getPrecision($this->currency->precision);
Replace it with : $computingPrecision->getPrecision(2);

Please spread the issue because lot of people suffer from this issue, i use Prestashop 1.7.8.7

Good luck

**Comment by partiid** [comment]
> Hello, I fixed the issue by updating the class context Go to classes/context.php line 498 Look for : $computingPrecision->getPrecision($this->currency->precision); Replace it with : $computingPrecision->getPrecision(2);
> 
> Please spread the issue because lot of people suffer from this issue, i use Prestashop 1.7.8.7
> 
> Good luck

Thanks for the fix but unfortunetly this is just temporary solution. When you have a currency that is computed with other precision, it will always be computed with only precision of 2. The real question is why $this->currency is null
