### ISSUE TITLE
Image upload doesn't work in Image Slider plugin

### ISSUE THREAD

**Issue by lhotakj** [PrestaShop/PrestaShop#25672]
#### Describe the bug

After an upload of image, this image does not show up. When I check the link, it looks in correct form like 
/modules/ps_imageslider/images/1e39f131ef4a8094542c70218d8b25d0fb3491ca_banner4-2021.png
but the file is actually missing on FTP. The workaround was obvious - I created such file and it works. 

This stoppe working about some update, but I can't recall of what. I was surely not updating the shop itself. I do regularly update plugins.

#### Expected behavior

I would expect that once I upload an image it shows up properly.

#### Steps to Reproduce

1. Go to `Modules | Image silder` 
2. Click on `edit` on one existing item
3. Click `upload`
4. Select a valid PNG file, hit `ok`
5. The image doesn't show up

**Screenshots**

1. upload
<img width="1158" alt="1" src="https://user-images.githubusercontent.com/614444/130357862-78cebdfa-d9a9-4199-a48a-e8dd29798bf9.PNG">
2. after upload
<img width="1188" alt="2-after-upload" src="https://user-images.githubusercontent.com/614444/130357878-6b8df836-7436-4ae9-802f-625ba6fa21c1.PNG">
3. missing file `8e942910c48b684dd83a6b67ebc88d3702deec47_banner4-2021.png`
<img width="404" alt="3-no-file" src="https://user-images.githubusercontent.com/614444/130357892-b83e5c61-db0a-4beb-9b08-0a97fb8ae073.PNG">
4. It got fixed after I manually uploaded file with the expected name
<img width="1086" alt="4-manually-created-file-works" src="https://user-images.githubusercontent.com/614444/130357943-4650fbfa-c1af-4db1-b823-005b8b701090.PNG">

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2.34
* Memory limit: 256M
* Max execution time: 90
* Upload Max File size: 128M
* Image Slider version: 3.1
* Server information: Linux 83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64
* Server software version: Apache

**Comment by hibatallahAouadni** [comment]
Hello @lhotakj 

I didn't manage to reproduce the issue with PS1777 and PS1767, see the attached screen record below:

https://drive.google.com/file/d/1akTXlHDpzoHJMCb0hIWyx19A2Id0ARW0/view

Please check and feedback.
Thanks!

**Comment by maiolif** [comment]
I have the same issue.

**Comment by khouloudbelguith** [comment]
Hi @lhotakj, @maiolif,

I did not manage to reproduce the issue with PS1777 and the module ps_imageslider v3.1.0.
I attached a screen record
https://drive.google.com/file/d/1b-nEXSa7jzX_puYf8unZ9vrVc2sOk1fS/view?usp=sharing

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @lhotakj 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by nathanl361** [comment]
I had the same problem today. After a few search and no solution .... I noticed I had a "%" character in image title. By removing it no more problem it worked ;)
so check if you have any special character in your image title before uploading it ;)
