### ISSUE TITLE
Customers Query slow with many orders

### ISSUE THREAD

**Issue by ocio87** [PrestaShop/PrestaShop#25683]
#### Describe the bug

Hello there,

When trying to view or edit the password of a customer with many orders, this generates slowness in seeing customer as edit (Change Password).

You should not delay in the edit client option (Change Password) since in this option there is only basic information, there is no detailed information about the client.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to 'Clients'
2. Click on 'Clients'
3. Find a customer who has thousands of orders

**Screenshots**

![image](https://user-images.githubusercontent.com/12537826/130511902-91466eeb-9c91-46ed-823d-5a008bce9c9e.png)

https://drive.google.com/file/d/1-yz5mDkFm9_yc-In4JJaxuVBc9qUsXOV/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.7
* PHP version: 7.3

**Comment by florine2623** [comment]
Hello @ocio87 ,

Following your video steps, I couldn't reproduce the issue.
Please check my screen record : https://drive.google.com/file/d/1V1nMG99SI91elxsxE0MHyKuu7z8Qof9D/view

Thanks!

**Comment by ocio87** [comment]
the bug occurs with customers who have many orders.  When the customer has few orders, his behavior is normal.  when you have many orders, hundreds of orders with thousands of products ordered, it blocks the entire site until it manages to load all the information.  While it is running, other computers cannot interact with the site.

**Comment by Hlavtox** [comment]
Just tested and even with a customer with one order, it makes hundreds of unnecessary queries.

**The customer**
![customer](https://user-images.githubusercontent.com/6097524/130588898-91294a57-8e7e-4181-89d1-1af37624303d.JPG)

**Queries on view page**
![queries](https://user-images.githubusercontent.com/6097524/130588980-476f80a4-64ce-4ddf-9676-e8541b4d585d.JPG)

**Queries on edit page - why?**
![queries edit](https://user-images.githubusercontent.com/6097524/130589004-317fb570-2482-4d42-bb3f-4667cc5afcdb.JPG)

**Comment by Hlavtox** [comment]
@ocio87 @florine2623 Edit page will be fixed by https://github.com/PrestaShop/PrestaShop/pull/25686. (Can you test?)
____________
The view must be optimized not to load these queries.

**Comment by florine2623** [comment]
Hello @ocio87 ,

Thank you for your suggestion. The Development Team will take it into consideration for future developments. 

Thanks for your PR @Hlavtox !

**Comment by ocio87** [comment]
@Hlavtox 

Hello there,

As I understand these changes are being made for version 8.0?

In case it can be applied to 1.7.7.7, what files do I need to update to proceed with the test?

Thanks,

**Comment by Hlavtox** [comment]
@ocio87 Hi, yes for 8.0.0. For the basic functionality you need only 3 lines.
**src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php**
Change:
`$customerInformation = $this->getQueryBus()->handle(new GetCustomerForViewing((int) $customerId));`
to
`$customerInformation = $this->getQueryBus()->handle(new GetCustomerForEditing((int) $customerId));`

**src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/edit.html.twig**
Change:
`{% set fullName = '%s. %s'|format(customerInformation.personalInformation.firstName[:1], customerInformation.personalInformation.lastName) %}`
to
`{% set fullName = '%s. %s'|format(customerInformation.firstName.getValue[:1], customerInformation.lastName.getValue) %}`
Change:
`{% include '@PrestaShop/Admin/Sell/Customer/Blocks/form.html.twig' with {'isGuest': customerInformation.personalInformation.guest} %}`
to
`{% include '@PrestaShop/Admin/Sell/Customer/Blocks/form.html.twig' with {'isGuest': false} %}`

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers this issue is waiting for your confirmation :pray: 
So, if you approve these changes proposed by @Hlavtox to improve Customers Query, please put the label **`To Do`**.

Thanks in advance!

**Comment by Hlavtox** [comment]
@hibatallahAouadni It still does not solve the insane numbers of queries on customer view page. I think that pagination should be introduced.

**Comment by matks** [comment]
I confirm @Hlavtox suggestion is a good idea.

> @hibatallahAouadni It still does not solve the insane numbers of queries on customer view page. I think that pagination should be introduced.

After loading has been optimized, if the page is still slow, we have many ways to fix it.
- display orders as a paginated table as you suggest
- display orders using an ajax query with a spinner
- only display a relevant number of orders (anyway, it's useless to show thousands of orders, nobody can use a page with thousand of rows), a simple maximum amount of items (and we add a "There is more orders not shown" information message)

**Comment by hibatallahAouadni** [comment]
Thanks @matks :tada:

**Comment by ocio87** [comment]
Thank you very much for all the support and interest in this bug.

I remain very pending if the changes that are going to be made will be able to be applied in version 1.7.7.x.

**Comment by Hlavtox** [comment]
Customer with 20 orders, 0 vouchers, 50 carts, 200 products bought... it takes **1 minute** to view him. :( On a fast server.

![1](https://user-images.githubusercontent.com/6097524/131971935-d2ea4045-7735-407f-8c07-d96660ba7c67.JPG)
![2](https://user-images.githubusercontent.com/6097524/131971934-cb7e8063-fc96-4dc9-a6ec-b7cd1c561fcb.JPG)

ping @matks

**Comment by Hlavtox** [comment]
@kpodemski Not fixed, reopen pls. I fixed only the editation screen. :-)

**Comment by ocio87** [comment]
Hello, do you know of any progress regarding this improvement?

**Comment by Hlavtox** [comment]
@ocio87 I fixed opening the edit screen, it is instant now. It will be in Prestashop 8. Customer detail page (with orders, adresses, mails etc) will be harder to fix. You can have a look into it.

**Comment by ocio87** [comment]
Thank you @Hlavtox

**Comment by Hlavtox** [comment]
@ocio87 You can apply it to your store right now by changing these two files. (https://github.com/PrestaShop/PrestaShop/pull/25686/files)

![Výstřižek](https://user-images.githubusercontent.com/6097524/142292634-23247163-8f7e-459d-8bdc-b9df2470d26d.JPG)

**Comment by hibatallahAouadni** [comment]
Ping @Progi1984 why did you reopen the issue while the PR is well merged?

**Comment by Hlavtox** [comment]
@hibatallahAouadni It's only partially solved, I reduced the time on customer view by approximately 15%.

**Comment by Progi1984** [comment]
@hibatallahAouadni : @Hlavtox has answered. Sorry, I forgot to leave you a comment

**Comment by Progi1984** [comment]
@Hlavtox Do you think you will be able to work on the 2nd part ?

**Comment by ocio87** [comment]
Hello everyone,

I think it can be a good solution. It definitively solves the problem of editing a client when they have many orders. If you consider that there are few stores that have this problem, it is not worth it. I will continue to make the change manually in the edit.html.twig and CustomerController.php files when I update the version of the store (1.7.8.5), for example with a client that has many orders it was taking me up to 4 minutes to show information about customer groups and be able to change the password. It only takes 2 seconds now.

I consider that there is a confusion, in the fix that @Hlavtox says that it improved by 15% is when you click on view the customer information when the client has many orders.

The one that I think has improved substantially is about the client edit that took into account a select of orders on a page that does not need that information. In this query to edit client, @Hlavtox  edited the files edit.html.twig and CustomerController.php, as you can see in the following video, clicking on edit does not delay with the change of the two files, but if I click on see, if there is a considerable delay.

https://drive.google.com/file/d/1bSU_3zrXqs4W3ddb5LOoLwnT_QCnlZ7L/view?usp=sharing

**Comment by zuk3975** [comment]
The problem is still relevant.
I think carts, orders and viewed products lists should be paginated
