### ISSUE TITLE
Volume discounts should not be available to unselected countries

### ISSUE THREAD

**Issue by mrabsinthe** [PrestaShop/PrestaShop#25688]
I think that this is rather a bug, not improvement... If you go to any product, pricing, specific prices and and a volume discount available for USA, Japan and Germany, the table on FO product's page should be shown only to customers from USA, Japan and Germany. It is however there all the time visible to visitors from any country. Quite confusing and should not be there.

#### Expected behavior

The volume discount table should be hidden to visitors from countries not selected in BO specific prices.

#### Additional information

* PrestaShop version: 1.7.7.7

**Comment by florine2623** [comment]
Hello @mrabsinthe ,

Can you follow the Bug Report Template and add screenshots so that we can reproduce it ?

Thanks!

**Comment by mrabsinthe** [comment]
My bad, it works fine on a vanilla 1.7.7.7 but not on my, two updated installations. Need to figure out where the bug is. Apologies.

**Comment by florine2623** [comment]
Thanks for the updates, I'll close your issue, if you come up with any new updates, feel free to open a new ticket.
