### ISSUE TITLE
BO - SEO and Webservice Parameters pages not saved in Multistore

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#25680]
#### Describe the bug

When in Multistore, in shop or group of shops context, the parameters are not saved on both SEO & URLS and Webservice pages.

#### Expected behavior

Parameters should be saved in every context in Multistore on these pages.

#### Steps to Reproduce

1. Go to Shop Parameters > Traffic & SEO > SEO & URLs or to Advanced Parameters > Webservice pages
2. Change any parameter (for example : "Accented URL" or "Route to products" / "Enable PrestaShop's webservice"), save
3. Click on the menu to to reload the page (without hitting F5 key)
4. Check the modified parameters : The changes were not saved.

**Screenshots**

https://drive.google.com/file/d/1seW68XZPCbuBoc9gnexE9SKOlwlAHvj2/view

#### Additional information

* PrestaShop version: 1.7.8.0 RC1 B3
* PHP version: N/A

**Comment by Robin-Fischer-PS** [comment]
Linked to #25674

**Comment by eternoendless** [comment]
According to what was discussed, it seems that the forms are being saved correctly but read incorrectly afterwards.

**Comment by atomiix** [comment]
Fixed by #25690

**Comment by khouloudbelguith** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/25690
