### ISSUE TITLE
Problem with refund voucher prestashop 1.7

### ISSUE THREAD

**Issue by Mulherbe** [PrestaShop/PrestaShop#25687]
Hi, i have an issue on prestashop 1.7.6.3.

    On my shop, if someone is ordering by using a discount code, and he wish to get a refund on a specific product.

It works fine when the order is made with only one product and the refund is done by taking account of the voucher.

In case there is more than one product, it's sligthly more difficult.
Presatshop refund the whole discount as well as the product.

Let me clarify this,

If a customer order 2 product who are both at 50€, it makes a total of 100€.
If the discount code gives a 10% promo, it is going to reduce the price to 90€. 
So, the discount code is worth of 10€ and both product are now worth of 45€ each.

In the case where that customer wish a refund of only one product,
prestashop is going to calculate 10% of one product and not the total price of the order.
The refund of one of them is going to be 40€ instead of 45€.

Exemple: https://ibb.co/S79s5fZ

thank you.

**Comment by florine2623** [comment]
Hello @Mulherbe ,

This is how the discount feature works. If you want to refund just 45 euro, you can add it in the following field - Amount : 
<img width="1195" alt="Screenshot 2021-08-24 at 14 32 43" src="https://user-images.githubusercontent.com/16019289/130616933-4590c85e-a97e-4653-a114-2cf9c8979ae8.png">

Thanks!

**Comment by Mulherbe** [comment]
![presta](https://user-images.githubusercontent.com/77394951/130617722-0ef39b69-fb2e-447f-9b8e-3318117cdb74.jpg)
No, look:
I have one command with this, i want to refund juste one item.
Look the block on red that price of my item 1: 34,80€ - 5,75€ so 29.05€ but that dont works because  the good calcul is 34,80€ - 3,48€.
5,75€ is voucher on all command not juste one item

**Comment by florine2623** [comment]
You apply the discount on the whole order and not on each product, as explained in the configuration board :
<img width="581" alt="Screenshot 2021-08-24 at 16 14 09" src="https://user-images.githubusercontent.com/16019289/130632724-5635ad50-d08d-470d-bfe2-663dde59f438.png">

This is how the system works. So I'll close the issue.
Thanks!
