### ISSUE TITLE
BO - SQL Manager - SQL query return exception

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#25684]
#### Describe the bug

SQL Manager throws Fatal Error when trying to run complex query

#### Expected behavior

No exception should be displayed

#### Steps to Reproduce

1 - Go to BO => discount
2 - Click on "export to sql manager" button
3 - In the SQL manager page, just click on "save" button
4- See error

**Screenshots**

https://drive.google.com/file/d/152rsnZDnxUPT38OesuWXL5pCuYDE9-1f/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.x // 1.7.8.x
* PHP version: 7.3 // 7.4

**Comment by hibatallahAouadni** [comment]
Hello @SD1982 

Thanks for your issue!
FYI (for Dev only :wink: ):
The Request is well saved, if you use one condition in the ON Clause:
```
SELECT SQL_CALC_FOUND_ROWS b.*, a.*

FROM `ps_cart_rule` a 
LEFT JOIN `ps_cart_rule_lang` b
                ON b.`id_cart_rule` = a.`id_cart_rule`

 WHERE 1 

 ORDER BY a.id_cart_rule DESC
```
But, if you add another condition in the ON Clause, an error is thrown:
```
SELECT SQL_CALC_FOUND_ROWS b.*, a.*

FROM `ps_cart_rule` a 
LEFT JOIN `ps_cart_rule_lang` b
                ON (b.`id_cart_rule` = a.`id_cart_rule` AND 1)

 WHERE 1 

 ORDER BY a.id_cart_rule DESC
```
Enjoy it and happy developing :rocket: 

PS: I didn't manage to reproduce the issue with PS1770, PS1774. It's a regression from 1775!

Thanks!
