### ISSUE TITLE
regla de catalogo con atributos

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#25696]
Prestashop 1.7.7.7.

reglas de precios de catalogo con atributos no se aplican
Si tengo 
articulo camisa
atributo1  x xl xxl 
atributo2 rojo verde azul 

al aplicar regla de catalogo por ejemplo con precio unico de 9.95 no aplica la regla a los articulos con atributos pero si lo aplica a los articulos sin atributo.

**Comment by hibatallahAouadni** [comment]
Hello @xecron21 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: Please send your request in English. English is the norm on GitHub.

Thank you
