### ISSUE TITLE
Editing deleted / inactive carrier shouldn't be possible

### ISSUE THREAD

**Issue by mehdi-ghezal** [PrestaShop/PrestaShop#25697]
#### Describe the bug

Carrier pricing disappear when edit the carrier with the wrong identifier.

#### Expected behavior

Shouldn't be able to edit carrier with the wrong identifier.

#### Steps to Reproduce

1. Create a **Carrier X** and setup a price grid per weight
2. List available carrier
3. Open the **Carrier X** in a new tab and keep the tab open in step 2 untouched
4. Change the carrier name to **Carrier Y**, save and close the tab
5. From the tab open at step 2 untouched, open again **Carrier X** in the new tab
6. Change the carrier name to **Carrier Z**, save and close the tab
7. Now refresh the tab open in step 2 and open **Carrier Z**, it doesn't have price anymore 

#### Additional information

At step step 5 we edit the carrier from an old ID and all the PriceRange has already been move to the a ID. 
Prestashop create anyway a new ID for the carrier but without the PriceRange.

When the user open the carrier from the old ID at step 5, he should have been redirect to the new ID automatically.

Please don't say to refresh windows or something like this as users tend to use multiple tabs and deal with multi tasking jobs, so this kind of error can easily happen and the consequences can be important as we talk about pricing.

I didn't have the time to check in a newer version of Prestashop but I do believe this still apply.

* PrestaShop version: 1.7.3
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @mehdi-ghezal 

Thanks for the well detailed bug report :clap: 
Well, I didn't manage to reproduce the issue with PS1777, see the attached screen record below:

https://drive.google.com/file/d/1rnOCwBY1tKsPPfh7SeWTu_iuFASa12xJ/view

Please check and feedback.
Thanks!

**Comment by Hlavtox** [comment]
Editing inactive carrier should be possible, so you can prepare it before you show it to customers.

**Comment by mehdi-ghezal** [comment]
Actually I was referring to the fact that when you edit a carrier, a new one is created and the previous one is flagged as deleted / inactive : in the database fields active is set to false and deleted set to true. 

But to be more specific, when we edit a carrier a new one is created and the old one is flag as inactive and deleted. At this point, it shouldn't be possible to edit the old one.

And even without reproducing the specific issue I mentioned, it didn't make sense to allow a user to edit a deleted carrier that is not supposed to be accessible. 

I don't think any core developper can easily explain the expected and real life behaviors in this case, so it simply shouldn't be allowed IMHO.

**Comment by mehdi-ghezal** [comment]
@hibatallahAouadni I don't think you follow exactly the step I mentioned.

Maybe try this steps that are maybe more explicit :

1. Open a new tab and go to Prestashop back office
2. List available carrier
3. Create a new carrier with the name "Carrier X" and setup a price grid per weight
4. Save the new carrier
5. Close your tab

---

1. Open a new tab and go to Prestashop back office
2. List available carrier and you will find "Carrier X"
3. Open "Carrier X" and you will see everything is fine
4. Close your tab

---

1. Open a new tab and go to Prestashop back office
2. List available carrier and again you will find "Carrier X"
3. This time, open "Carrier X" in **a new tab**
4. At this point you have **2 tabs** : the list of carrier and the edit form for "Carrier X"
5. In the tab of the edit form, change "Carrier X" name to "Carrier Y"
6. Save and close this tab when save is successful
7. At this point you have 1 tab left and it's the one previously open that show the list of carriers and this tab show "Carrier X" ; **DO NOT** refresh this tab
7. Edit "Carrier X" and change his name to "Carrier Z"
8. Close your tab

---

1. Open a new tab and go to Prestashop back office
2. List available carrier and you will find "Carrier Z"
3. Check the price grid, it should have disappear, at least it does in 1.7.3

**Comment by khouloudbelguith** [comment]
Hi @mehdi-ghezal,

Thanks for these clarifications but I did not manage to reproduce the issue with PS1777.
I attached a screen record
https://drive.google.com/file/d/1AjQqSJ6EpDva7kKfQ9sZs8OoDv8x0laZ/view?usp=sharing

Thanks to check and feedback.

**Comment by hibatallahAouadni** [comment]
Hello @mehdi-ghezal 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
