### ISSUE TITLE
BO - Add new SQL query & DB Backup page - An exception is displayed when multistore enabled

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25703]
#### Describe the bug

In the BO > Advnced Parameters > Database > Add new SQL query & DB Backup page or Experimental Features page, an exception is displayed when multistore enabled

#### Steps to Reproduce

1. Enable Multistore context
2. Create a new shop and configure it
3. Go to BO > Advanced Parameters > Database page
4. Click on "Add new SQL query"
5. See error 
![image](https://user-images.githubusercontent.com/16067358/130800363-751706e8-33fb-40e1-bd8c-4c34d4a2a7a1.png)

6. Go to BO > Advanced Parameters > DB Backup page
7. See error 
![image](https://user-images.githubusercontent.com/16067358/130800543-33c8b7b3-614c-4e13-a933-be7a46e0e5cd.png)

In the 1780rc1build3 => ok

#### Additional information

* PrestaShop version: develop
* PHP version: 7.4, 7.2

**Comment by marwachelly** [comment]
Hello,
 I have the same exception with the following steps:

1. Enable Multistore context
2. Create a new shop and configure it
3. Go to your profile > Profiles 
![image](https://user-images.githubusercontent.com/1533248/134168596-23404b40-0ef7-4102-b9eb-0eb85a70d7e1.png)
![image](https://user-images.githubusercontent.com/1533248/134168628-9b9aabeb-bb66-489c-a4af-a8e482b11ef4.png)

@Progi1984  Could you please verify if your PR fixe the problem.

**Comment by Progi1984** [comment]
@marwachelly Yes, it fixes the problem ;)
