### ISSUE TITLE
Address modification in B.O. - Inconsistency with F.O.

### ISSUE THREAD

**Issue by thalassa-web** [PrestaShop/PrestaShop#25710]
#### Describe the bug
In F.O., when a user changes his/her address and the updated one was already used in an order a new address is created and the other one is flagged as «deleted» (to keep address consistency in the order's addresses).
If I do the same in B.O., the address is simply updated and so my orders (and invoices …).

#### Expected behavior
In B.O., updating an used address must create a new one and flag the old one as «deleted». (Exactly the same behaviour of F.O.)

#### Steps to Reproduce

In front office :
1. Create a custoner
2. Add an address
3. Make an order with this address
In the back office
4. Go to the created used address
5. make some modification
6. Update
7. The address as the same ID
8. Go to the created order (see 3)
9. The address has changed …
In the front office :
10. Go to my account and change the used address
11. Change the address
In B.O. :
12. Go to the customer's addresses
13. The ID changed
14. Go to the order
15. The address is still the one one the step 9

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.1

**Comment by hibatallahAouadni** [comment]
Hello @thalassa-web 

I didn't manage to reproduce the issue with PS1777, these issue has been fixed with the 1770.
We are aware of these issues, both are already fixed with PS177. This issue is a duplicate of #12170 & #20238. 

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #20238
