### ISSUE TITLE
Prefix not valid for credit slips

### ISSUE THREAD

**Issue by abcreationIT** [PrestaShop/PrestaShop#25715]
#### Describe the bug

Adding certain symbols in the credit slip prefix textbox shows an error saying the prefix is invalid

#### Expected behavior

I expect to be able to insert symbols as well as in delivery slips (see second screenshot).

#### Steps to Reproduce

1. Go to 'Orders' -> 'Credit slips'
2. Put in Credit slips prefix textbox some text with a symbol (for example "N° DR")

**Screenshots**

<img width="1569" alt="Schermata 2021-08-26 alle 17 20 28" src="https://user-images.githubusercontent.com/33608547/130991113-37150849-0f4a-4340-a829-adb1e271547a.png">

<img width="1338" alt="Schermata 2021-08-26 alle 17 20 36" src="https://user-images.githubusercontent.com/33608547/130991548-4f724ff9-37d2-4dae-bf81-3215300874b6.png">

#### Additional information

* PrestaShop version: 1.7.7.6
* PHP version: 7.3.28

**Comment by hibatallahAouadni** [comment]
Hello @abcreationIT 

This is the wanted behavior! You shouldn't use symbols for Prefix.
But let's check it with Product Team :wink: 
Ping @Julievrz wdyt? is this the wanted behavior?

**Comment by Julievrz** [comment]
I think it's a wanted behavior yes, but I'll let @marionf or @MatShir confirm. :-)

**Comment by abcreationIT** [comment]
Hi @Julievrz,

I understood that it is a wanted behaviour but I don't understand the sense of not being able to put certain characters in the prefix (especially ° ).

Also, why can I put any character in the **delivery slips** including symbols but **NOT** on the **credit slips**?

Thanks

**Comment by MatShir** [comment]
Hi @Julievrz,
As said @abcreationIT, the invoices and the delivery slip can accept this symbol, but not the credit slips, weird 🤔. I don't see why the software would have some restriction on the prefix. It does make a lot of sense to have a symbol, many countries have their own way to display numbers, for example in France we use # or n°.

**Comment by defcon8** [comment]
This is also an urgent problem for us. Please port this fix back to the 1.7 line....

**Comment by MatShir** [comment]
I'm sorry @defcon8, but the 1.7.8 patch only addresses security issues. Now the new supported version is 8.0. You can either upgrade to 8.0 or apply the [hotfix](https://github.com/PrestaShop/PrestaShop/pull/26042) in the store. In both cases, I suggest you to be accompanied by an expert if you don't have the necessary skills. Here is a resource that could help you -> https://www.prestashop-project.org/support/.
