### ISSUE TITLE
Problem in Product view and product addition

### ISSUE THREAD

**Issue by hcsara** [PrestaShop/PrestaShop#25712]
I created an online shop using Prestashop v1.7.6.8, I've been using it for several months and everything was fine. Today I tried to add a new product, but I found out that the dashboard view in the product section is totally messed up: it reminds me of a missing div in html or something like that, but no one ever touched the code.
It gets worse if I try to add a product, for which the different pages are impossible to be used in order to add the data. I am attaching some screenshots highlighting the issue.

How is it possible that it happened? How could I solve this issue?

Thank you so much, Best Regards
![Cattura](https://user-images.githubusercontent.com/89588162/130969620-590ebc94-205e-46c7-9c4f-1a771a7d31d7.JPG)
![iss2](https://user-images.githubusercontent.com/89588162/130969637-c8cc761c-4060-4cac-9e06-c31d0cd1f114.JPG)
![iss3](https://user-images.githubusercontent.com/89588162/130969648-7df36e9c-e95a-42d3-955c-eff0b6fb2d5b.JPG)

* PrestaShop version: 1.7.6.8

**Comment by hibatallahAouadni** [comment]
Hello @hcsara 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
