### ISSUE TITLE
Create new order BO - search product engine search only by first letters

### ISSUE THREAD

**Issue by vitalita** [PrestaShop/PrestaShop#25723]
I have several products named:
Denon DCD600NE
Denon DCD800NE
Denon PMA600....etc

I can't add products because search engine search only by first letters...(I guess) I have a Product named "Denon PMA-800" and can't find it anyway.
![screenshoteasy (48)](https://user-images.githubusercontent.com/56353115/131138193-16e65359-9b40-4d6b-b853-1032cea5318f.png)

Please see image attached

My presta: 1.7.7.5

Thanks for the help

**Comment by khouloudbelguith** [comment]
Hi @vitalita,

Thanks for your issue, please next time you need to follow the template.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). 

I did not manage to reproduce the issue with PS1.7.7.
I attached a screen record
https://drive.google.com/file/d/1Sfpu5eiD0-zfS9AAM4tFtHgldD8uudu-/view?usp=sharing

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @vitalita 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
