### ISSUE TITLE
BO - Addresses in order page, better to be shown as tab layout

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/PrestaShop#25724]
#### Is your feature request related to a problem?

Column size of delivery address and invoice address in order page is too narrow.

#### Describe the solution you'd like

For more readability, it is better to show it as tab layout.

#### Additional context

BO > Orders > Select an order

![131103894-21f8661a-ee7e-461e-acc0-b30799698f89](https://user-images.githubusercontent.com/85633460/131138085-388b4aca-c6c6-4480-99e2-a107951a3067.png)

![131104976-9650fda0-5a47-4d2c-bc4c-f3d6a5fb0b52](https://user-images.githubusercontent.com/85633460/131138110-54d068e4-f319-47f5-b271-dd7b42a89fbf.png)

_The addresses shown in the images are generated by fakeaddressgenerator.com_

**Comment by Hlavtox** [comment]
I don't agree. There is a lot of wasted space and you cannot see both addresses at once.

**Comment by khouloudbelguith** [comment]
Hi @mparvazi,

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know!

Thank you!
