### ISSUE TITLE
No image changing

### ISSUE THREAD

**Issue by AdrievandeVreede** [PrestaShop/PrestaShop#25729]
#### Describe the bug

After uploading an image on a CMS page, rename it and upload a different image with the same name as the first image had, the image will not be different. Not in FO or in BO.

#### Expected behaviour

The new image should be the new image, not the old image.

#### Steps to Reproduce

1. Go to a CMS page
2. Upload an image
3. Rename the image
4. Upload another image with the same name as the first one had
5. They'll be the same 

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: N/A

**Comment by kpodemski** [comment]
There's probably some cache mechanism on your hosting that is preventing images from a refresh.

**Comment by hibatallahAouadni** [comment]
Hello @AdrievandeVreede 

I didn't manage to reproduce your issue with PS1773 & PS1777, see the attached screen records below:

https://drive.google.com/file/d/1AdqCHAHdxN5qGl_Y7jjLTCq2PKUtAyaV/view
https://drive.google.com/file/d/1WNqZ9DaRD8pnP-PArXrvtat_xctHGX7w/view

Please clear your cache, check and feedback.

PS: thanks @kpodemski for your quick reply :rocket: 

Thanks!

**Comment by AdrievandeVreede** [comment]
Hello,
Thanks for your reply. I've cleared my cache, and tried it again. Same result. 
On your video, I saw not what I said to do. I did the following:
1. Clear cache
2. Upload an image ...
3. View page
4. Edit page
5. Rename image to ...2
6. Upload another image with ...
7. See the difference (not)
https://user-images.githubusercontent.com/78849197/131317491-70b6152b-7c80-461d-aba1-135ff290aa98.MOV

**Comment by florine2623** [comment]
Hello @AdrievandeVreede ,

I can't reproduce your issue following your steps :
https://drive.google.com/file/d/1DHmvkkz3ckkRivNtgGEPFhAd5s9XqJuU/view

It seems like it is a cache issue as @kpodemski said. Please check with your hosting provider.

I'll close this issue as I can't reproduce it.
Thanks!
