### ISSUE TITLE
PrestaShop install ; error that the SQL Database 6.2 is not advanced enough ; cPanel installatron

### ISSUE THREAD

**Issue by Colm001** [PrestaShop/PrestaShop#25720]
That's basically the problem Every time I try to download PrestaShop I keep getting an error that the SQL Database 6.2 isnt advanced enough.   I get an error message in red saying to try downloading a less advanced version.  When I do that it won't download properly.  I've been trying to sort out this website for over a week now and I'm about at the end of my tether ( don't ask)  But when you need to learn about DNS and nameservers etc ......

**Comment by deepindersingh83** [comment]
Can you please share a screenshot or provide more information about your setup how you are installing or downloading 

I think this is something related to hosting configuration and has nothing to do with Prestashop

**Comment by Colm001** [comment]
And my hosting has said it's nothing to do with them and to contact Prestashop!  
![Prestashop error message](https://user-images.githubusercontent.com/89639063/131122104-71d4e381-fab1-4677-817e-9aec1259a87a.jpg)

**Comment by matks** [comment]
@Colm001 you are using a third party installer, not PrestaShop official installer. We cannot help you, you need to look for help with hosting provider.

That being said PS 1.7.7.7 is not compatible with php7.4 and your screnshots says your install uses PHP 7.4.21

**Comment by matks** [comment]
Did not see this part

> And my hosting has said it's nothing to do with them and to contact Prestashop!

PrestaShop is an open source project. That means you get the project for free, for zero dollars.

So the company that you pay - the hosting provider - says you should ask for help the project that you do not pay 😅  . Well... I don't know for you, but I think as a customer I expect a better service from a company I pay than for a project I use for free.

That being said, you can also hire a PrestaShop expert to find out what's happening, see https://devdocs.prestashop.com/1.7/faq/i-need-help/.

**Comment by deepindersingh83** [comment]
> And my hosting has said it's nothing to do with them and to contact Prestashop!
> ![Prestashop error message](https://user-images.githubusercontent.com/89639063/131122104-71d4e381-fab1-4677-817e-9aec1259a87a.jpg)

As mentioned by matks please change the version of php to 7.3 and mysql. 

If still need assistance please ping me
