### ISSUE TITLE
Adding Belarussian currency doesn't work

### ISSUE THREAD

**Issue by musicpanda** [PrestaShop/PrestaShop#25732]
#### Describe the bug

Adding Belarussian currency doesn't work

#### Expected behavior

Normally the other fields will be filled. That happens with a few other currencies that I tested. However, with the Belarussian Ruble you look forever to the "Loading currency data - Please wait while currency data is being loaded" popup.

#### Steps to Reproduce

1. Go in the menu to International -> Localization
2. Click the Currencies tab
3. Click the "Add new currency" button
4. Select the Belarussian Ruble in the first option (Select a currency).

**Screenshots**
When you check there is a javascript error and PHP error (see attached images)

![bela2](https://user-images.githubusercontent.com/13930107/131212717-d041ea31-135c-463c-90e4-5c79b57a9f7a.jpg)
![bela1](https://user-images.githubusercontent.com/13930107/131212718-5ceaad27-c7f8-46ce-9844-576d3bbfe5f1.jpg)

#### Additional information

* PrestaShop version: PS 1.7.7.4 and 1.7.7.5
* PHP version: PHP 7.3

**Comment by hibatallahAouadni** [comment]
Hello @musicpanda 

I encountered the same issue with PS1774, it keeps rolling for over 10 minutes without any result, see the attached screen record below:

https://drive.google.com/file/d/1rMe1KmVPgC1kyBWnWGykkbWYQ__g2uS7/view

And I get this error on my console:

![image](https://user-images.githubusercontent.com/23308427/131366392-3b6c0f00-716e-43c6-816f-b20beaa0485f.png)

Fortunately, I didn't manage to reproduce it on 1777, it seems fixed :tada:  see the attached screen record below:

https://drive.google.com/file/d/1LfuKz2H1cNZbh45LRtO8PZ9Qv94206Hp/view

Could you please check it and feedback.
Thanks!

**Comment by musicpanda** [comment]
Indeed. It worked in 1.7.7. Thank you.

**Comment by hibatallahAouadni** [comment]
Thanks for your feedback!
Glad to hear :tada: 

So, closing the isssue as it has been fixed :relaxed:
