### ISSUE TITLE
Healthcheck path should return 200

### ISSUE THREAD

**Issue by saikarthikp9** [PrestaShop/PrestaShop#25731]
#### Is your feature request related to a problem?
Yes. Unable to host PrestaShop on an instance behind AWS Load Balancer because it fails the healthcheck.

#### Describe the solution you'd like

A healthcheck path needs to be introduced if not existing. Ex: /healthcheck

#### Alternatives you've considered

I have tried to use / and /en/ as the healthcheck routes but the response status code is 302 which I don't understand. When I do curl -I IP/ or curl -I IP/en/ I get the 200 response.

Please advice.

**Comment by hibatallahAouadni** [comment]
Hello @saikarthikp9 

This module has been archived, it’s no longer maintained but you still can fork it if you need it for your shop.
Also let us know if you are voluntary to maintain this module.

PS: your issue is similar to this one #12982 :wink: 

Thanks!
