### ISSUE TITLE
Impact on price with or without taxes

### ISSUE THREAD

**Issue by AldeaG** [PrestaShop/PrestaShop#25733]
Hi, I have a doubt which I couln´t find a solution in the Prestashop forums

I use Prestashop 1.7.7.0

I am importing items with combinations (footwear) by CSV. Some sizes have a different price, so instead of putting a price on the item (product) and the impact on the combination, I am putting the price of the product "0" and in the impact I put the final price. With which I avoid having to calculate what is the price difference to add in the impact. I don't know if this is the right thing to do it.

The problem is that if I import the price from Product, I can choose Tax excluded or Tax included

But if I import the price from Combinations, "Impact in price" appears but it does not indicate whether or not it includes the tax. And it does not.

The fact is that I indicate in Combinations "Impact on price" and the final result is that VAT is added to a price that already includes VAT, that is, twice.

How do I import so that the final price is the one I want, including VAT, without having to calculate the price without VAT inversely? (Dividing by 1.21 as my VAT is 21%) Do I have to change something in the "core" of Prestashop?

I think that as well I have the option to choose if I want the price I set with or without taxes that option should be included as well in the impact on price. 
Thanls

**Comment by hibatallahAouadni** [comment]
Hello @AldeaG 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
