### ISSUE TITLE
[BO] - Buttons are not well displayed

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#25740]
#### Describe the bug

Order statuses are not well displayed on Order list

#### Expected behavior

Order statuses should be displayed on Order list as it use to be on 177x or 1780

#### Steps to Reproduce

1. BO > SELL > Orders 
2. See error => Order statuses are not well displayed

**Screenshots**

![image](https://user-images.githubusercontent.com/23308427/131363889-9ca75d0f-3186-4628-aa96-765fe969d6f7.png)

#### Additional information

* PrestaShop version: 1.7.8.x
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox

I have the same issue:

- In the BO > Catalog > Attributes page > Add new color value 
![image](https://user-images.githubusercontent.com/16067358/131499413-5d77c553-5008-49f4-a928-8d2eb293e8d0.png)
- In the BO > Module manager > configure Banner module 
![image](https://user-images.githubusercontent.com/16067358/131499512-22d8be00-7ef1-4750-968b-74794e93acb3.png)

- In the BO > Module manager > configure ps_imageslider module
![image](https://user-images.githubusercontent.com/16067358/131499726-29a49b1b-211e-494d-891f-f0c3c54e2f92.png)

- In the BO > Shop Parameters > Add new title
- In the BO > Carriers > Add new carrier page
- In the BO > Shop parameters > Contact > Stores page
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

I have an issue in the BO > Catalog > Discounts > Cart rule page
![image](https://user-images.githubusercontent.com/16067358/132205919-8bb83f67-c858-4fa0-b0ad-579b8c1082ba.png)

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

We have the same issue in some modules like `ps_banner`:

![image](https://user-images.githubusercontent.com/23308427/133229466-bd796e92-c4d4-4d0d-9a5a-5883a10124d4.png)

And in `ps_imageslider`: https://github.com/PrestaShop/PrestaShop/issues/25840#issuecomment-918044408

Thanks!

**Comment by Progi1984** [comment]
Fixed by @Hlavtox in #25741
