### ISSUE TITLE
API error codes documentation

### ISSUE THREAD

**Issue by cyrilchapon** [PrestaShop/PrestaShop#25758]
When accessing an URL like

https://API_KEY@the-store.com/api/products?output_format=JSON&display=full

I'm getting a PHP warning serialized, at the end of the JSON like so :

```
        {
            "code": 3,
            "message": "[PHP Warning #2] array_values() expects parameter 1 to be array, null given (/www/server/override/classes/Product.php, line 27)"
        },
        {
            "code": 3,
            "message": "[PHP Warning #2] array_combine(): Both parameters should have an equal number of elements (/www/server/override/classes/Product.php, line 25)"
        },
        {
            "code": 3,
            "message": "[PHP Warning #2] array_replace(): Expected parameter 2 to be an array, bool given (/www/server/override/classes/Product.php, line 26)"
        }
```

My topic here is not about resolving this error; but rather understanding where the `code: 3` comes from.
Mainly in order to be able to anticipate the future, and potentially ignore / trust errors based on their code.

So the question is : are those kind of API errors documented somewhere ?

**Comment by Hlavtox** [comment]
@cyrilchapon There is a problem in your overrides.

Open /override/classes/Product.php, find line 27 and find why there is a null instead of some array coming to **array_values()**.

**Comment by cyrilchapon** [comment]
@Hlavtox thank you.
This is not my question.

> My topic here is not about resolving this error; but rather understanding where the code: 3 comes from.

**Comment by Hlavtox** [comment]
@cyrilchapon I think that code 3 is a an exception type - https://www.php.net/manual/en/exception.getcode.php

**Comment by hibatallahAouadni** [comment]
Hello @cyrilchapon 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

PS: Thanks @Hlavtox for your quick replies :rocket: 

Thank you

**Comment by matks** [comment]
@cyrilchapon this information is not in https://devdocs.prestashop.com/1.7/webservice/ so I don't think it's documented

Unfortunately webservice documentation is far from complete. If you're motivated, consider contributing to the doc ;)
