### ISSUE TITLE
Add VAT ID field on customer level

### ISSUE THREAD

**Issue by bullmade** [PrestaShop/PrestaShop#25754]
Add a field for European VAT ID on the customer similiar to how there is a field for SIRET and APE code.
Although there is a VAT ID field on customer address, for practical reasons it can sometimes be easier to identify the customer through VAT ID directly on the customer account and not on the address.

![image](https://user-images.githubusercontent.com/16975198/131553635-b2d5ecf8-c973-4b1e-8ac7-b4241ae78bd7.png)

**Comment by hibatallahAouadni** [comment]
Hello @bulldesign 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by bullmade** [comment]
Its not a bug, its a feature request.
