### ISSUE TITLE
I can not docker compose up

### ISSUE THREAD

**Issue by khanhblue95** [PrestaShop/PrestaShop#25756]
I change https://deb.nodesource.com/setup_10.x  -> https://deb.nodesource.com/setup_12.x
after that I run docker-compose up 
----------------------------------------------------------------
Symfony\Component\Filesystem\Exception\IOException: Failed to create "/var/www/html/var/cache/dev/translations": mkdir(): Permission denied in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:105
prestashop-git_1  | Stack trace:
prestashop-git_1  | #0 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php(678): Symfony\Component\Filesystem\Filesystem->mkdir('/var/www/html/v...')
prestashop-git_1  | #1 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Config/ResourceCheckerConfigCache.php(124): Symfony\Component\Filesystem\Filesystem->dumpFile('/var/www/html/v...', '<?php\n\nuse Symf...')
prestashop-git_1  | #2 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Translation/Translator.php(383): Symfony\Component\Config\ResourceCheckerConfigCache->write('<?php\n\nuse Symf...', Array)
prestashop-git_1  | #3 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Translation/Translator.php(348): Symfony\Component\Translation\Translator->dumpCatalogue('en-US', Object(Symfony\Component\Config\ConfigCache))
prestashop-git_1  | #4 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Config/ConfigCacheFactory.php(46): Symfony\Component\Translation\Translator->Symfony\Component\Translation\{closure}(Object(Symfony\Component\Config\ConfigCache))
prestashop-git_1  | #5 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Translation/Translator.php(349): Symfony\Component\Config\ConfigCacheFactory->cache('/var/www/html/v...', Object(Closure))
prestashop-git_1  | #6 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Translation/Translator.php(317): Symfony\Component\Translation\Translator->initializeCacheCatalogue('en-US')
prestashop-git_1  | #7 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Translation/Translator.php(293): Symfony\Component\Translation\Translator->loadCatalogue('en-US')
prestashop-git_1  | #8 /var/www/html/classes/Context.php(424): Symfony\Component\Translation\Translator->getCatalogue('en-US')
prestashop-git_1  | #9 /var/www/html/classes/Context.php(399): ContextCore->getTranslatorFromLocale('en-US')
prestashop-git_1  | #10 /var/www/html/install-dev/classes/controllerConsole.php(129): ContextCore->getTranslator()
prestashop-git_1  | #11 /var/www/html/install-dev/classes/controllerConsole.php(108): InstallControllerConsole->__construct('process')
prestashop-git_1  | #12 /var/www/html/install-dev/index_cli.php(64): InstallControllerConsole::execute(17, Array)
prestashop-git_1  | #13 {main}prestashop_prestashop-git_1 exited with code 1

**Comment by hibatallahAouadni** [comment]
Hello @khanhblue95 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
