### ISSUE TITLE
When prestashop.com is down, the admin backoffice is slow

### ISSUE THREAD

**Issue by tajriba** [PrestaShop/PrestaShop#25759]
Version:

1.7.X 

Because it wants to load the profile picture (avatar) : 
<img width="559" alt="Schermafbeelding 2021-09-01 om 16 22 10" src="https://user-images.githubusercontent.com/68469531/131688457-58c6ab83-eb0b-46ce-86a8-db0cb253d057.png">

My solution: stop loading profile avatars in prestashop backoffice from external source like prestashop.com.
This slows down many backoffices if yu have a prestashop.com account linked.

**Comment by hibatallahAouadni** [comment]
Hello @tajriba 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by matks** [comment]
It’s already done in the 1.7.8.0 version which will be released soon :wink:

See details https://github.com/PrestaShop/PrestaShop/issues/18503
