### ISSUE TITLE
deleteSearchIndexes issues on Prestashop 1.7.7.2

### ISSUE THREAD

**Issue by Benoit1980** [PrestaShop/PrestaShop#25766]
Hello,

I would like to know if this bug has been fixed in future Prestashop releases please.

On the version 1.7.7.2 the deleteSearchIndexes() query has issues:
`DELETE sw FROM `ps_search_word` sw LEFT JOIN `ps_search_index` si ON (sw.id_word=si.id_word) WHERE si.id_word IS NULL;
`
The query runs non stop for days.

Causing this one to fail too:
`SELECT DISTINCT si.id_product FROM ps_search_word sw LEFT JOIN ps_search_index si ON sw.id_word = si
`
Both the ps_search_word and ps_search_index` tables were truncated and the entire product catalog reindexed, the the issue comes back when a product is deleted from the catalog.

Thank you.

**Comment by hibatallahAouadni** [comment]
Hello @Benoit1980 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
