### ISSUE TITLE
Error after update from 1.7.7.6 to 1.7.7.7 - Unable to update settings -

### ISSUE THREAD

**Issue by Rockabit** [PrestaShop/PrestaShop#25762]
#### Describe the bug

After updated from PS 1.7.7.6 to PS 1.7.7.7, I save the changes in product form and I receive "unable to update settings". 
In debug mode I see 

#### Expected behavior

I expect you to save the product changes.

#### Steps to Reproduce

1. Go to BO
2. Click on products
3. Click on a product
4. Click on 'add new image or save any change'
5. See error

![image](https://user-images.githubusercontent.com/67980604/131733480-7c0772c4-5417-4132-8145-b90b1e3f40d9.png)
![image](https://user-images.githubusercontent.com/67980604/131734307-c3519561-f758-44f0-9ced-47c1393c23a5.png)
![image](https://user-images.githubusercontent.com/67980604/131814235-81b30c2a-10c2-427c-ab35-07a78bea51ec.png)
![image](https://user-images.githubusercontent.com/67980604/131734472-b9bf7006-5df7-4e84-9bcc-57b9f05f37f9.png)

#### Additional information

* PrestaShop version: 1.7.7.7
* PHP version: 7.3.29

**Comment by khouloudbelguith** [comment]
Hi @Rockabit,

Thanks for your report.
>After updated from PS 1.7.7.6 to PS 1.7.7.7

did you use the module 1-click upgrade?
If yes, what is the exact version did you use?

What is the exact type of image did you upload? is it png, jpeg, gif,...?

Does this issue occur only when you try to edit old products or also new products created after the upgrade?

Thanks!

**Comment by Rockabit** [comment]
Hi @khouloudbelguith,
thanks for your reply!

Yes, I use 1-click upgrade v4.12.0.
The images are .jpg
The issue occur on both products, new and old.

Now I did the rollback to 1.7.7.5 but the issue now it remained.

PS: Sometimes, as soon as I log in to the BO, it lets me make some changes (for example choose the cover image), but when I try to generate the product variants the issue reoccurs

**Comment by Rockabit** [comment]
Do I try to revert to version 1.7.7.7 again?

**Comment by Rockabit** [comment]
Hi @khouloudbelguith,
The issue seams solved after the return to normality of the PS sites.
Thanks for your support!
