### ISSUE TITLE
[ErrorException] Undefined index: prestashop with composer

### ISSUE THREAD

**Issue by JasminAllForWeb** [PrestaShop/PrestaShop#25768]
On 1.7.7.x branch, when I run ``composer install``, I got this error : 
Undefined index: prestashop
I got php 7.4.23.

**Comment by hibatallahAouadni** [comment]
Hello @JasminAllForWeb 

Please next time respect the provided template to submit a complete bug report.
You need to donwgrade your PHP version to 7.3 (see our [system requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart)).
I didn't manage to reproduce your issue. Sorry but I have to close the issue.

Thanks!

**Comment by JasminAllForWeb** [comment]
Sorry, I will respect the provided template to submit a complete bug report next time.
Actually, I have the same issue with 1.7.8.x branch.

**Comment by hibatallahAouadni** [comment]
I think you may need help with your shop. If you want please consider one of our [support plans](https://www.prestashop.com/support).
Or, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

**Comment by JasminAllForWeb** [comment]
I got a 404 error with your slack link. Could you give me the good link ?

**Comment by hibatallahAouadni** [comment]
Sorry, here's the link https://prestashop.slack.com/
You have to create an account on Slack.
