### ISSUE TITLE
Translation module is not working  - Cant update translations

### ISSUE THREAD

**Issue by goyetus** [PrestaShop/PrestaShop#25779]
#### Describe the bug

Can´t SAVE Translations in Admin >>> Language/translations/module

#### Expected behavior

You cant save translations,  and dev.log is filled with lot of errors.

**Screenshots**

![translation](https://user-images.githubusercontent.com/24479700/131931127-10d03b4d-5b02-40f3-aea8-0ca3e4c482dc.PNG)

![error](https://user-images.githubusercontent.com/24479700/131931140-e922579a-7d08-464c-8af4-aa1d0dd9bca3.PNG)

I upload dev.log too. 
[dev.log](https://github.com/PrestaShop/PrestaShop/files/7102469/dev.log)

#### Additional information
* PrestaShop version: 1.7.7.5
* PHP version:  7.3

tryed to:
- Rise PHP_Vars  to 9999  
- Edit the file /web/modules/ps_metrics/translations/es.php  and ADD the line manually.   Not works.

**Comment by khouloudbelguith** [comment]
Hi @goyetus,

I did not manage to reproduce the issue with PS1777 using the gamification module and the ps_gdpr module.
https://drive.google.com/file/d/1ERkY1F4mpLIqQ3VGRIyE4zOj0TrAJGBL/view?usp=sharing

As it's not a module provided by Prestashop core, we can't do anything with this.
You should contact the module author via this mail `support-metrics@prestashop.com` they are the only ones to help you with it.

Thanks!

**Comment by goyetus** [comment]
@khouloudbelguith   - I upgrade today to 1.7.7  
Same problem.

I uninstalled "metrics"  and other modules,  but "all module" translation  are not working.

Here you have a video:
https://drive.google.com/file/d/1aC1U9sr7cG42iaBsD2eNayErfIsn2_jh/view?usp=sharing

1)  Enter any prestashop module 
2)  Enter the "module" section to see all the translated modules.
3)  Try to save something in any module.

Here you have the .log file also 
[dev.log](https://github.com/PrestaShop/PrestaShop/files/7108430/dev.log)
