### ISSUE TITLE
Module list is bugged 

### ISSUE THREAD

**Issue by sfroment** [PrestaShop/PrestaShop#25772]
#### Describe the bug
Following the addons tutorial on how to make a [modules](https://devdocs.prestashop.com/1.7/modules/creation/tutorial/#the-constructor-method) your module won't be in the list

#### Expected behavior

My module being listed

#### Steps to Reproduce

follow [addons tuto](https://devdocs.prestashop.com/1.7/modules/creation/tutorial/#the-constructor-method)

[this line is causing the error](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/src/Core/Addon/Module/ModuleRepository.php#L239) dunnow which comportment is really expected hopefully this will be helpfull

**Comment by hibatallahAouadni** [comment]
Hello @sfroment 

Could you please specify your Prestashop and PHP version :pray: 
And it will be helpful if you could provide a test module that you work on it.

Thanks in advance!

**Comment by tswfi** [comment]
@sfroment a module that is not yet installed will not be shown in the "Modules" -> "Module manager" list. It is only shown in "Modules" -> "Module catalog" page (Yes, I have tripped on this multiple times :)

**Comment by sfroment** [comment]
prestashop version 1.7.8.0
php version 7.4
@tswfi thanks ! maybe it isn't a good thing as the catalog isn't available when prestashop have down times
