### ISSUE TITLE
actionShippingPreferencesPageHandlingForm doesn't work

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#25773]
#### Describe the bug

**actionShippingPreferencesPageHandlingForm** is not called on **Shipping > Configuration** page, while according to documentation, it should since 1.7.4. https://devdocs.prestashop.com/1.7/modules/concepts/forms/admin-forms/

**actionShippingPreferencesPageHandlingSave** is called just fine.

#### Steps to Reproduce

1. Add hookActionShippingPreferencesPageHandlingForm to any module and put `die("CALLED");` there. Register it during install.
2. Check its hooked to the position.
3. Open **Shipping > Configuration** and see that nothing happens.

OR

Open classes/Hook.php and add `echo $hook_name . "  ";` to `exec` method. It will list all the called hooks to the page.

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

I didn't manage to reproduce the issue with PS1767, see the attached screen reocrd below:

https://drive.google.com/file/d/1J4vr8ihBrDLI5-YMkZWc-xuxDxG0bmQ_/view

Please check and feedback.
Thanks!

**Comment by Hlavtox** [comment]
@hibatallahAouadni You are testing a different hook. But good to know it works!

But actionShippingPreferencesPageHandlingForm should also work, see it's included in the code https://github.com/PrestaShop/PrestaShop/search?q=actionShippingPreferencesPageHandlingForm

So, either it should be removed or made working, WDYT?

**Comment by hibatallahAouadni** [comment]
PIng @PrestaShop/prestashop-core-developers any idea why the hook **`actionShippingPreferencesPageHandlingForm`** doesn't work while it's already listed in this [file](https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/data/xml/hook.xml)?

**Comment by Hlavtox** [comment]
Bump @PrestaShop/prestashop-core-developers

**Comment by atomiix** [comment]
@Hlavtox Maybe I'm missing something but the hook is fired on my side:

https://user-images.githubusercontent.com/2168836/176441683-7d1f6e34-a110-4099-a3b2-cb6720deb83b.mov

**Comment by Hlavtox** [comment]
Probably fixed, I trust @atomiix, I think I was doint something wrong :D
