### ISSUE TITLE
BO - Products page - an exception is displayed when combination feature is disabled

### ISSUE THREAD

**Issue by dmoibm** [PrestaShop/PrestaShop#25782]
#### Describe the bug

After the update from 1.7.7.5 to 1.7.7.7 the error 'Undefined index: attribute_price' appears.
#### Steps to Reproduce

1. Enable debug mode
2. Delete all products with combinations
3. Go to BO > Advanced Parameters > Performance page
4. Disable Combination
5. Go to BO > Catalog > Products page
6. See an error  
![image](https://user-images.githubusercontent.com/16067358/132003648-e7c55224-230a-4d5f-9d4e-6a21f6c26be5.png)

It is ok with PS1775

---------------------------------------------------------------------------

It fails on line 3418 (1.7.7.7) in Product.php. 
`'attribute_price' => $row['attribute_price'] ?: null, `

Bevore line 3408 (1.7.7.5) there was this code that works:
`'attribute_price' => (isset($row['attribute_price']) ? $row['attribute_price'] : null),`

**It fails only if the feature Combination is disabled.**

I don't understand because this code works in the same environment:
```
$array2 = [
    "foo" => "bar",
    "bar" => "foo",
];

echo $array2['foos'] ?: "gugus";
```

* PrestaShop version: 1.7.7.7
* PHP version: 7.2.24 on Ubuntu

**Comment by khouloudbelguith** [comment]
Hi @dmoibm,

Thanks for you report.
Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). 

Thanks to edit your first comment.

**Comment by kpodemski** [comment]
Thank you @dmoibm 

You're right, this check is invalid.

@khouloudbelguith it's more like a dev report but he's right and it's indeed a bug 👍 

Edit: also, it's a regression

**Comment by khouloudbelguith** [comment]
Thanks @kpodemski, I updated the first comment.
It is a regression from PS1776.

I’ll add this to the debug roadmap.

Thanks!

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/25784
