### ISSUE TITLE
Prestashop 1.7.6.4 work very slow - TTFB problem

### ISSUE THREAD

**Issue by nsakiotis** [PrestaShop/PrestaShop#25786]
Recently I have been facing following issue

My prestashop website https://www.rosepoupee.gr/ has a **huge TTFB, about 3-7 seconds**. 
After that time, the page is being displayed **immediately** with most of its content rendered. The issue appears in every kind of page: home, product, category, even on static ones, with varying TTFB.

I am not quite sure when it started to happen. I would guess that is due to some kind of config, which makes the cms "**fully preparing** the page", before delivering it to the web server. (sorry for the lame description).

I am listing some facts, which may help you identify the root cause:

**Hosting**
- Hosting resources fine. I am running on a pretty powerfull VPS, even before the issue appeared.
- I am running on cloudflare, but the issue appears, even if I disable cloudflare and hit my webserver directly.

**Addons**
My website is **not** fully packed with addons. It has just 5-6 essential ones that run on the front end, like Page Builder, Menu, Filter, Image gallery, Loyalty Points. 

I tried disabling the addons 1 by 1 but the high TTFB remains above 2000ms, where i would normally expect about 50ms.
For instance, disabling the menu addon drops the time by 1 sec, or adding an additional product carousel raises it accordingly. I would expect those action to affect the total loading time, but not the TTFB.

**Profiling**
I ran a profiler on the homepage and results are socking.
![Capture](https://user-images.githubusercontent.com/4609108/132032568-5dab99f8-0a5c-4e4f-9888-91befdfc6d04.JPG)

Huge Load Time, Query Time, Number of Queries. initContent and display in particular.
Probably a couple of addons are purely designed, causing that amount of queries, but it still can't be the root cause. 

I still believe that for some reason the full content is sort of being "**pre-loaded**". Any help would be appreciating.

**Comment by khouloudbelguith** [comment]
Hi @nsakiotis,

Unfortunately, it seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem. I invite you to contact the [support](https://www.prestashop.com/support) for further investigation.

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com/).

I close the issue.

Thanks for your understanding!

**Comment by CarlysG** [comment]
Hola @nsakiotis pudiste encontrar una solución??

**Comment by CarlysG** [comment]
Hola @nsakiotis  pudiste encontrar una solución?
