### ISSUE TITLE
Sort by price does not work in facetedsearch with big prices

### ISSUE THREAD

**Issue by itsvahid** [PrestaShop/PrestaShop#25789]
#### Describe the bug

When product prices are higher than 6 digits, price_min and price_max fields in layered_price_index table become 999999.99999.
This causes the sorting not work correctly as all the products have the same price index.

#### Expected behavior

Sort by price is expected to work with higher prices correctly.

#### Steps to Reproduce

1. Increase couple of products' prices to more than 999999.99999
2. Go to FO category page
3. Sort by price asc/desc

**Screenshots**
Database layered_price_index table:
![image](https://user-images.githubusercontent.com/48237049/132126325-b52ea5d3-6243-4687-9b3f-d9a8d1e4bebd.png)

Wrong sorting:
![image](https://user-images.githubusercontent.com/48237049/132126353-bf29df16-8eea-4bd4-bb5c-d11accc6d8cc.png)

**Proposed Solution**
Increase maximum number of digits for price_min and price_max columns in layered_price_index table. It should probably be same as price column in product table: decimal(20,6)

#### Additional information

* PrestaShop version: 1.7.6.9
* PHP version: 7.2

**Comment by Hlavtox** [comment]
@itsvahid Will be fixed by https://github.com/PrestaShop/ps_facetedsearch/pull/506

**Comment by itsvahid** [comment]
@Hlavtox
Exactly! this solves the issue.
Thanks

**Comment by hibatallahAouadni** [comment]
Hello @itsvahid 

Thanks for reporting the issue!
Could you please check this issue #19810 it seems similar to yours.
@Hlavtox Isn't it the same?
Please check and feedback.

Thanks!

**Comment by itsvahid** [comment]
@hibatallahAouadni Hi
The issue you've mentioned seems to be concerned with specific prices(discounts) which is different than this one.

**Comment by hibatallahAouadni** [comment]
Hello @itsvahid 

I didn't manage to reproduce the issue with PS1770, PS1780 and develop, see the attached screen record below:

https://drive.google.com/file/d/1WYrmTMIaLfvr3Xe0wxysSCgn_cKbo_gP/view

Please check and feedback.
PS: Faceted Search v3.6.0

Thanks!

**Comment by itsvahid** [comment]
Hello @hibatallahAouadni 
The problem will not occur with products that have the same price; If products have the same price the default sorting would be with id_product.
Please try setting prices exactly like below for exact products; otherwise, id_product sorting might accidentally sort products correctly!
The sorting should be out of order now.
**High to low:**
![image](https://user-images.githubusercontent.com/48237049/132289341-6bfdc5a1-07da-4de6-a16e-36d504f8e5b9.png)

**Low to high:**
![image](https://user-images.githubusercontent.com/48237049/132290324-dce5ac8e-3d72-4179-bec0-8c53c5c57786.png)

**Comment by florine2623** [comment]
Hello @itsvahid ,

Thanks for the report I managed to reproduce the issue with ps_facetedsearch v3.7.0. I can confirm that this behavior is indeed a bug.

**High to low : OK**
<img width="856" alt="Screenshot 2021-09-07 at 10 29 32" src="https://user-images.githubusercontent.com/16019289/132312381-cff0bced-6101-4a6d-9c7a-79c91ac9ec8c.png">
**Low to high : NOK**
<img width="839" alt="Screenshot 2021-09-07 at 10 32 01" src="https://user-images.githubusercontent.com/16019289/132312392-802a83db-11e2-4fe0-bfae-fd13a76bf5d3.png">

Thanks!
