### ISSUE TITLE
Deprecation of array_key_exists() generates multiple entries in error_log file

### ISSUE THREAD

**Issue by agroundworld** [PrestaShop/PrestaShop#25799]
#### Describe the bug
In doing routine maintenance on my website, I noticed that the error_log file was very large (over 4 GB).  The errors/warnings were being generated due to the use of array_key_exists() which has been deprecated.  The text of the error is as follows:

PHP Deprecated:  array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead

The error is being generated from several calls including:
pshop/src/Adapter/EntityMapper.php on line 85
pshop/src/Adapter/EntityMapper.php on line 99
pshop/classes/module/Module.php on line 343

A search for the function on the repository indicates that it is used 177 times.

#### Expected behavior

Remove deprecated function from code so that errors/warnings do not occur

#### Steps to Reproduce

Not sure  how to replicate since I don't what what actions are generating those calls.  I have been working on adding products

**Screenshots**
Attaching screenshot of some rows of log file:

![Decprecation error](https://user-images.githubusercontent.com/75636570/132269718-a8da489f-936a-4548-a35d-a937a9ea8aff.jpg)

#### Additional information

* PrestaShop version: 1.7.7.7
* PHP version: 7.4

**Comment by kpodemski** [comment]
PrestaShop 1.7.7.7 is not compatible with PHP 7.4, this is why you have an error log full of deprecations.

https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart

**Comment by florine2623** [comment]
Hello @agroundworld ,

Please downgrade your PHP version to 7.3 to make it compatible with PrestaShop 1.7.7.7.

I'll close the issue.
Thanks!
