### ISSUE TITLE
BO - Product with combination cannot be saved with french & Polish & German language in mode debug

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#25797]
#### Describe the bug

Product with combinaition cannot be saved with french language case of mode debug enabled

#### Expected behavior

Product with combinaition should  be succefully saved with french language case of mode debug enabled

#### Steps to Reproduce

1. The employee language is french or polish
2. Enable debug mode
3. Create new product with combination
4. Save
5. see the following attached error

![image](https://user-images.githubusercontent.com/89604350/132238579-cb7e2bf3-2050-48c0-81d7-3fa392af06dd.png)

It is OK when the employee language is english
It's OK with 1.7.7.5 as shown in the following attachement

![image](https://user-images.githubusercontent.com/89604350/132239093-805f6c5b-ee3a-4f18-9deb-603b48b7354f.png)

#### Additional information

* PrestaShop version: 1.7.7.6/1.7.7.7
* PHP version: 7.3

**Comment by SebBareyre** [comment]
Hi @marwachelly 
Could you try this fix: https://github.com/PrestaShop/PrestaShop/pull/25807

**Comment by Progi1984** [comment]
@marwachelly Could you check ? I didn't reproduce it.

**Comment by Progi1984** [comment]
@marwachelly has tested :
- It's fixed in Product Page V1 (french polish and german language) : https://watch.screencastify.com/v/cM41k7tMBjTbDfwpUq6P 
- No problem in Product Page V2 : https://watch.screencastify.com/v/XYcmzevak1kNZHZenxEV

Thanks to her for the test.

**Comment by zorrobiwan** [comment]
so it will not be fixed in 1.7.* ?
