### ISSUE TITLE
Language de-AT only available on i18n but not for translations

### ISSUE THREAD

**Issue by fuchsbart** [PrestaShop/PrestaShop#25812]
[available_languages.json](https://i18n.prestashop.com/translations/1.7.7.7/available_languages.json) hosted on i18n.prestashop.com contains

`"de-AT": "German (Austria)",`

But in the two files that are necessary for Translations

`app/Resources/legacy-to-standard-locales.json`
`app/Resources/all_languages.json`

**the entry is missing.**

**Comment by hibatallahAouadni** [comment]
Hello @fuchsbart 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
