### ISSUE TITLE
BO - Orders - An exception when deleting a discount after possibility to add an invalid discount name

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#25829]
#### Describe the bug

An exception when deleting a discount after possibility to add an invalid discount name.

#### Expected behavior

The cart rule name should accept all characters.

#### Steps to Reproduce

1. Go to BO > Orders > Orders page
2. Open an order
3. Click Add discount
4. Add Name = valid name, Type =Valid type,  Value =Valid value
5. Add Name = Invalid name (Exemple : <<), Type =Valid type,  Value =Valid value
6. Click delete discount
7. See error
**Screenshots**
![image](https://user-images.githubusercontent.com/1533248/133087603-23ce10d9-9154-4139-bb6f-0087515e487e.png)
![image](https://user-images.githubusercontent.com/1533248/133087623-c107de2e-1bb5-42d1-933b-e85552192437.png)

With  1.7.6.9 It is possible to add an invalid discount name and it is possible to delete with press on Delete voucher

#### Additional information

* PrestaShop version: 1.7.7.0, 1.7.7.7, develop
* PHP version: 7.3

**Comment by Progi1984** [comment]
@PrestaShop/product-team I have a question. What are authorized characters for cart rule name?

Actually, if we put an `<`, it considers it's an HTML tag so it removes it.

**Comment by MatShir** [comment]
The field should accept all characters. Most of the text field should accept all the characters with some exception like the text field on the Front Office.

**Comment by Progi1984** [comment]
@MatShir What are these exceptions ? Could you specify it, please ?

**Comment by MatShir** [comment]
I meant almost all text fields must accepted all characters, so this page has to accept all the characters.

**Comment by PierreRambaud** [comment]
@Progi1984 The default behavior for text fields is "Accept all characters" until there is a specification in the issue telling "this field has to exclude these characters"
I don't understand why they added this kind of useless checks :facepalm:

**Comment by Progi1984** [comment]
Fixed in #26514
