### ISSUE TITLE
Product page v2: handle duplicate attachments

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#25831]
#### Describe the bug

In the new product page, when selecting attachment files you can select the same file multiple times. On submit no error is displayed, and only one attachment is associated but it results in a useless long list and can be confusing as you don't understand only will be added after submit.

#### Expected behavior

Two possible solutions:
- prevent the search component from displaying already selected attachments
- display a growl error when selecting an attachment that is already in the list

#### Steps to Reproduce

1. Go to Produc page v2
2. In the Specifications tab search for an attachment
3. Select one attachment, then perform the same research and attach the same file
4. The attachment is added twice in the list

**Screenshots**

![image](https://user-images.githubusercontent.com/16067358/132549042-3191d22b-fbf8-4573-b9e7-f066071bc43e.png)

#### Additional information

* PrestaShop version: 8.0
* PHP version: N/A

**Comment by jolelievre** [comment]
I think this issue has been handled by this PR https://github.com/PrestaShop/PrestaShop/pull/25920
The bug is no longer present and this issue should be closable

**Comment by Progi1984** [comment]
@hibatallahAouadni Could you check if the issue is always present ?

**Comment by hibatallahAouadni** [comment]
@Progi1984 @jolelievre Indeed it should be closed as Fixed, but it seems the issue-bot is off :sweat_smile: 
No need to check on @khouloudbelguith QA, I trust her :grin: 

---
> EDIT

I thought the linked PR suppose to fix the issue :disappointed:

**Comment by hibatallahAouadni** [comment]
@jolelievre the search doesn't work :disappointed: see the attached screen record below:

https://watch.screencastify.com/v/iknTds3Rko0epG0lxyPe

**Comment by jolelievre** [comment]
Hi @hibatallahAouadni

I think it's what we want it depends on what other files you may have, if you already selected the two files that match with "file" then there is no other possibility left. The files already selected are filtered from the response to avoid selecting them twice.

**Comment by MatShir** [comment]
@hibatallahAouadni 
For the use case, it seems to be the right behavior. The user can't search a file that is already associated to the product.
Can we close this issue? WDYT?

**Comment by hibatallahAouadni** [comment]
@MatShir Closing the issue :wink:
