### ISSUE TITLE
Can not override DeliveryOptionsFinder class

### ISSUE THREAD

**Issue by dnkhack** [PrestaShop/PrestaShop#25841]
#### Describe the bug
Hello. I am try to override function  `getDeliveryOptions` in  class `DeliveryOptionsFinder`.
I'm using native method and do everthing as usually. But get the error.
If I use brute method when add full class as is in override folder with my code correction all work good.

This is part of code my overrided class:
```
//-----------------------------------------------------------------------------------
use PrestaShop\PrestaShop\Adapter\Presenter\Object\ObjectPresenter;
use PrestaShop\PrestaShop\Adapter\Product\PriceFormatter;
use Symfony\Component\Translation\TranslatorInterface;

class DeliveryOptionsFinder extends DeliveryOptionsFinderCore
{
    public function getDeliveryOptions()
    {
        $delivery_option_list = $this->context->cart->getDeliveryOptionList();
        $include_taxes = !Product::getTaxCalculationMethod((int) $this->context->cart->id_customer) && (int) Configuration::get('PS_TAX');
        $display_taxes_label = (Configuration::get('PS_TAX') && !Configuration::get('AEUC_LABEL_TAX_INC_EXC'));
........
.......
HERE CODE work ok 100%
........
........
        return $carriers_available;
    }
}
//---------------------------------------end of class file
```

#### Steps to reproduce:

1. Install fresh PS
2. Enable "Debug mode"
3. override any function in class DeliveryOptionsFinder 
4. Begin to checkout order. On step 3 "shipping method" you will see this error

**Screenshots**
![image](https://user-images.githubusercontent.com/35419462/132850701-f2b7da1d-888b-464a-9aeb-7a4b984ed67c.png)

#### Additional information

* PrestaShop version: 17.7.4-1.7.7.7
* PHP version: 7.2-7.3

**Full text version of issue**
```
<html>
<body>
<!--StartFragment-->

(1/1) ContextErrorExceptionNotice: Undefined property: DeliveryOptionsFinder::$context
--
in DeliveryOptionsFinder.php line 35
at DeliveryOptionsFinderCore->getDeliveryOptions()in CheckoutSession.php line 141
at CheckoutSessionCore->getDeliveryOptions()in CheckoutDeliveryStep.php line 175
at CheckoutDeliveryStepCore->render(array('identifier' => 'checkout-delivery-step', 'position' => 3, 'ui' => object(RenderableProxy)))in RenderableProxy.php line 52
at RenderableProxy->render(array('identifier' => 'checkout-delivery-step', 'position' => 3, 'ui' => object(RenderableProxy)))in smartyfront.config.inc.php line 98
at smartyRender(array('identifier' => 'checkout-delivery-step', 'position' => 3, 'ui' => object(RenderableProxy)), object(SmartyDevTemplate))in SmartyLazyRegister.php line 83
at SmartyLazyRegister->__call('smartyRender', array(array('identifier' => 'checkout-delivery-step', 'position' => 3, 'ui' => object(RenderableProxy)), object(SmartyDevTemplate)))in 1287078ccb27dd17977d032210925a7366dc8d41_2.file.checkout-process.tpl.php line 29
at content_613b4b1d41ae82_59269959(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render(false, 0)in smarty_internal_templatebase.php line 232
at Smarty_Internal_TemplateBase->_execute(object(SmartyDevTemplate), null, null, null, 0)in smarty_internal_templatebase.php line 116
at Smarty_Internal_TemplateBase->fetch(null, null, null, null, false, true, false)in SmartyDevTemplate.php line 40
at SmartyDevTemplateCore->fetch()in CheckoutProcess.php line 112
at CheckoutProcessCore->render(array('file' => 'checkout/checkout-process.tpl', 'ui' => object(RenderableProxy)))in RenderableProxy.php line 52
at RenderableProxy->render(array('file' => 'checkout/checkout-process.tpl', 'ui' => object(RenderableProxy)))in smartyfront.config.inc.php line 98
at smartyRender(array('file' => 'checkout/checkout-process.tpl', 'ui' => object(RenderableProxy)), object(SmartyDevTemplate))in SmartyLazyRegister.php line 83
at SmartyLazyRegister->__call('smartyRender', array(array('file' => 'checkout/checkout-process.tpl', 'ui' => object(RenderableProxy)), object(SmartyDevTemplate)))in 71a660837d6560700f40f56228d0a9c616687adb_2.file.checkout.tpl.php line 178
at Block_475358702613b4b1d373351_66962590->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 248
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_475358702613b4b1d373351_66962590), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 184
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_475358702613b4b1d373351_66962590))in smarty_internal_runtime_inheritance.php line 156
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_475358702613b4b1d373351_66962590', 'checkout_process', 3)in 71a660837d6560700f40f56228d0a9c616687adb_2.file.checkout.tpl.php line 220
at Block_1860726656613b4b1d372f99_51480425->callBlock(object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 248
at Smarty_Internal_Runtime_Inheritance->callBlock(object(Block_1860726656613b4b1d372f99_51480425), object(SmartyDevTemplate))in smarty_internal_runtime_inheritance.php line 184
at Smarty_Internal_Runtime_Inheritance->process(object(SmartyDevTemplate), object(Block_1860726656613b4b1d372f99_51480425))in smarty_internal_runtime_inheritance.php line 156
at Smarty_Internal_Runtime_Inheritance->instanceBlock(object(SmartyDevTemplate), 'Block_1860726656613b4b1d372f99_51480425', 'content')in 71a660837d6560700f40f56228d0a9c616687adb_2.file.checkout.tpl.php line 71
at content_613b4b1d377e72_31058943(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render(false, 0)in smarty_internal_templatebase.php line 232
at Smarty_Internal_TemplateBase->_execute(object(SmartyDevTemplate), null, 'classiclayouts/layout-full-width.tpl', null, 0)in smarty_internal_templatebase.php line 116
at Smarty_Internal_TemplateBase->fetch('checkout/checkout.tpl', null, 'classiclayouts/layout-full-width.tpl', null, false, true, false)in SmartyDev.php line 40
at SmartyDev->fetch('checkout/checkout.tpl', null, 'classiclayouts/layout-full-width.tpl')in FrontController.php line 704
at FrontControllerCore->smartyOutputContent('checkout/checkout.tpl')in FrontController.php line 686
at FrontControllerCore->display()in Controller.php line 326
at ControllerCore->run()in Dispatcher.php line 518
at DispatcherCore->dispatch()in index.php line 28

<!--EndFragment-->
</body>
</html>
```

**Comment by hibatallahAouadni** [comment]
Hello @dnkhack 

Could you please check this issue #13881 it seems similar to yours.
Please check and feedback.

Thanks!

**Comment by dnkhack** [comment]
> Hello @dnkhack
> 
> Could you please check this issue #13881 it seems similar to yours.
> Please check and feedback.
> 
> Thanks!

Hello. Thank you for tip. I to researched it. But this is not my case. For test this issue I am had used the fresh install of PS.

**Comment by khouloudbelguith** [comment]
Hi @dnkhack,

Could you please provide us the exact file overridden `DeliveryOptionsFinder.php` to test it?

Thank you!

**Comment by dnkhack** [comment]
Hello. Yes sure. My apologies. But You can to reproduce by yourself. Try to override getDeliveryOptions on fresh PS install.  But still I'm attach file just tested on 1.7.7.8. May be I did something wrong. Thank you in advance.
[DeliveryOptionsFinder.php.txt](https://github.com/PrestaShop/PrestaShop/files/7188592/DeliveryOptionsFinder.php.txt)

**Comment by khouloudbelguith** [comment]
Hello @dnkhack,

I manage to reproduce the issue with PS1771 and PS1780
![image](https://user-images.githubusercontent.com/16067358/134712986-6f4e3aab-773c-41ea-a9e8-8ee4dc95e99c.png)

With PS1763 + debug mode enabled => ok
I'll add this to the debug backlog so that it's fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks!

**Comment by dnkhack** [comment]
Hello. Thank you. 
Issue can wait and are not important to solve fast. 

I'll try to research PS1763 to find a way. I agree about "more people contribute".

Have a good day :)
Kind regards.

**Comment by Progi1984** [comment]
@dnkhack It's normal as the `context` property is a private attribute.

Please add it to the top of your class and I think it should fix the problem.

```
    protected $context;
    protected $objectPresenter;
    protected $translator;
    protected $priceFormatter;

    public function __construct(
        Context $context,
        TranslatorInterface $translator,
        ObjectPresenter $objectPresenter,
        PriceFormatter $priceFormatter
    ) {
        $this->context = $context;
        $this->objectPresenter = $objectPresenter;
        $this->translator = $translator;
        $this->priceFormatter = $priceFormatter;
    }

```

**Comment by Progi1984** [comment]
@PrestaShop/product-team This issue should be fixed in `8.0.0` as it's not a `1.7.8.x` regression. Isn't it ?

**Comment by dnkhack** [comment]
**Hi. Thank you for tips. I test - not work. Because - private method.** 

![image](https://user-images.githubusercontent.com/35419462/135170443-651d099c-67a5-45af-9aee-a61d1527b5b5.png)

 **It is will be work if private function isFreeShipping in parent class change to protected. But I got other issue** 

![image](https://user-images.githubusercontent.com/35419462/135171903-24481a66-cd38-4abc-822a-8dc4e0e6b533.png)

![image](https://user-images.githubusercontent.com/35419462/135172494-985a0852-c0ed-480c-9bfc-b1eed5df2c59.png)

**On weekend I'm try research with PS1763. On this version work.** 

>  This issue should be fixed in 8.0.0 as it's not a 1.7.8.x regression. Isn't it ?
Yes :) But interesting for me why it work on PS1763 :)

**Comment by Hlavtox** [comment]
@kpodemski I think this should be closed as it's not an issue with override, but basic PHP logic.

**Comment by dnkhack** [comment]
@kpodemski Hello. Yes.
