### ISSUE TITLE
Bug FrontController

### ISSUE THREAD

**Issue by Finallo** [PrestaShop/PrestaShop#25859]
Hello, I've a big problem.

I only try the email generate or something like that and now, I can't make anything..

I send you the screenshot of this error.
![image](https://user-images.githubusercontent.com/81552938/132953637-24870f29-2d44-4cc0-a80f-1ced4157d550.png)
 HELP ME PLEASE

**Comment by kpodemski** [comment]
You're using PrestaShop with incompatible PHP version.

Please check your version compatibility here:
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart

**Comment by hibatallahAouadni** [comment]
Hello @Finallo 

You need to change your PHP version as @kpodemski mentioned above.
Closing the issue as it's not Core bug.

Thanks!
