### ISSUE TITLE
How Can i replace "Invoice" with "tax invoice" so can comply with local legistration

### ISSUE THREAD

**Issue by yuxiayuzhou** [PrestaShop/PrestaShop#25865]
#### Describe the bug

Local customer requires to change the invoice header. Current is the default "invoice". I have tried to check classes/pdf and pdf files. cannot find the header name "invoice". I would like to replace "invoice" with "tax invoice" so can comply with local laws. 

#### Expected behavior

to replace "invoice" with "tax invoice" so can comply with local laws. 

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @yuxiayuzhou 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have
questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com/).

Thank you
