### ISSUE TITLE
Allow to use inky_to_html in twig emails templates

### ISSUE THREAD

**Issue by Oksydan** [PrestaShop/PrestaShop#25862]
#### Is your feature request related to a problem?

With prestashop v8 we are able to use https://twig.symfony.com/doc/3.x/filters/inky_to_html.html since we are using twig 3.x version. This might be huge for developers that are working on email templates. We will be able to simplify our twig files with ink templating language.

#### Describe the solution you'd like

I think we should add inky_to_html filter to twig. It might be really new cool feature in prestashop v8 with foundation emails allowing us to create themes with scss and simple ink template language. Adjusting emails to FO project might be just few lines of scss code with variables. Changes to email template will hurt less (right now eyes are bleeding when you are reading that output code in twig) and cost us less time.

**Comment by matks** [comment]
> I think we should add inky_to_html filter to twig

So basically we need to add twig/inky-extra and twig/extra-bundle in Composer dependencies to enable the above feature, right ?

**Comment by Oksydan** [comment]
@matks yes, I think is should be enough.

**Comment by hibatallahAouadni** [comment]
Hello @Oksydan 

Thank you for your suggestion. The Developer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by matks** [comment]
Sounds good to me, I'd like a 2nd opinion from my peers

ping @PrestaShop/prestashop-maintainers

**Comment by kpodemski** [comment]
Sounds good to me too. Would you like to work on this @Oksydan ?

**Comment by Oksydan** [comment]
@kpodemski I can work on this but not anytime soon
