### ISSUE TITLE
1.6 modules stay around in 1.7

### ISSUE THREAD

**Issue by musicpanda** [PrestaShop/PrestaShop#25864]
After upgrading from 1.6 to 1.7 I am told that several modules have been replaced: blocksearch by ps_search, blocktopmenu  by ps_mainmenu, etc.

Yet while these new modules are installed and enabled those old ones stay around too - enabled. 
This is puzzling and potentially error generating. How can you debug a shop when such potentially interfering modules are present?

**Comment by matks** [comment]
@musicpanda see https://github.com/PrestaShop/PrestaShop/issues/22668

**Comment by hibatallahAouadni** [comment]
Hello @musicpanda 

Thanks for reporting the issue!
As @matks mentioned, your issue is a duplicate to #22668.
> Yet while these new modules are installed and enabled those old ones stay around too - enabled.

And that's why it's better to uninstall / disable the modules before upgrading (espcially to Major patch).
> After upgrading from 1.6 to 1.7

Could you please specify the exact versions (like 1.6.1.20) :pray: 

Thanks in advance!

**Comment by musicpanda** [comment]
From version 1.6.23

I counted 34 modules that have been replaced. Is there any manual which should be deleted and which inactivated?

**Comment by hibatallahAouadni** [comment]
Hello @musicpanda 

Here's list of modules https://github.com/PrestaShop/PrestaShop/issues/22668#issue-778814304
This issue has been fixed with PS1772, did you upgrade to 1771? or another version?

Thanks!

**Comment by musicpanda** [comment]
I see a roadmap in the link you provide. But I don't see a list of modules with instructions how to handle them.

The upgrade is to 1775

**Comment by florine2623** [comment]
Hello @musicpanda ,

You can go to the GitHub page of each module and download latest version :
<img width="1419" alt="Screenshot 2021-09-14 at 15 13 30" src="https://user-images.githubusercontent.com/16019289/133264172-3c3b5bd6-1e08-4473-8bb0-1d2df768c5dd.png">

**Comment by hibatallahAouadni** [comment]
Hello @musicpanda 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
