### ISSUE TITLE
BO - Categories page - Invalid category vars - An exception is displayed when Adding a category

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25871]
#### Describe the bug

If we change the `Route to category` in the BO > Shop Parameters page from `{id}-{rewrite}` to `{id}-{rewrite}-{meta_title}`, we cannot add new category => an exception is displayed

#### Steps to Reproduce

1. Go to BO > Shop Parameters > SEO & URLs page
2. Enable `Friendly URL`
3. Change the `Route to category` from `{id}-{rewrite}` to `{id}-{rewrite}-{meta_title}`
4. Go to BO > Catalog > Categories page
5. Click button 'Add new category'
6. See error 
![image](https://user-images.githubusercontent.com/16067358/133219682-8b7b0344-7699-4568-8227-e7a0e20a1cad.png)

#### Additional information

* PrestaShop version: 1.7.6.9, 1.7.7.7, 1.7.8.x
* PHP version: 7.1, 7.2

**Comment by matks** [comment]
@FabienPapet takes it
