### ISSUE TITLE
Localisation pack distribution / installation

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#25888]
How do we handle the new translation from the distrib part (on the installer for example) ?
i18n (pack of localization) is hosted in the corp account. 
How are going to migrate the service?

- [x] Setup i18n.prestashop-project.org which is a mirror of i18n.prestashop.com
- [x] Replace use of i18n.prestashop.com inside the software by i18n.prestashop-project.org

**Comment by MatShir** [comment]
Should use this opportunity to implement 
- https://github.com/PrestaShop/PrestaShop/issues/10456

**Comment by MatShir** [comment]
@eternoendless could you share your report made with the IT of corp?

**Comment by eternoendless** [comment]
i18n.prestashop-project.org will be most likely a mirror of i18n.prestashop.com, at least initially.

**Comment by matks** [comment]
Thanks to @lfourreau and @djodjo3 i18n.prestashop-project.org is now up

**Comment by matks** [comment]
Next step: replace use of i18n.prestashop.com inside the software by i18n.prestashop-project.org

**Comment by MeKeyCool** [comment]
@Progi1984 and @eternoendless , does this mean i close my PR #28057 ?
