### ISSUE TITLE
Update the auto test to test the upgrade from 1.6 to 8.0

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#25893]
#### Is your feature request related to a problem?

Currently, we have auto test to test the upgrade from 1.6 to 8.0
With the new version of the auto-upgrade module, a modal has been added(see issue [25657](https://github.com/PrestaShop/PrestaShop/issues/25657))

#### Describe the solution you'd like

We should update the auto-test according to the issue [25657](https://github.com/PrestaShop/PrestaShop/issues/25657)

**Comment by Progi1984** [comment]
Blocked until #26557 is closed.

**Comment by matks** [comment]
In order for this issue to move forward, bug https://github.com/PrestaShop/PrestaShop/issues/26557 must be fixed on 1.7.8.x

**Comment by jolelievre** [comment]
Hi @boubkerbribri 

are you still assigned to this issue? I moved it to In progress just in case

**Comment by boubkerbribri** [comment]
I didn't see MatShir assignment, i'm not on it, this isn't possible using what we use now for automation. It needs a lot of automation stuff because 1.6 is a lot different from 1.7.
I don't think that this issue will progress any time soon.

**Comment by Hlavtox** [comment]
Upgrade from 1.6 is no longer supported. 👍
