### ISSUE TITLE
Bug column 'last visit' in customer grid (back office) 1.7.7.2

### ISSUE THREAD

**Issue by maxime18dev** [PrestaShop/PrestaShop#25895]
#### Describe the bug

The column 'last visit' in the client part of the admin does not work.

#### Expected behavior

it should indicate the date of the last visit of each customer on the site.

#### Steps to Reproduce

1. Go to customer
2. All columns of the client grid have their data displayed correctly except for 'last visit'.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
![bug_last_visit](https://user-images.githubusercontent.com/71233149/133449419-b70bd46f-fe89-4d5a-a3a1-67b8eaa4b9ae.png)#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.3.29
*

**Comment by florine2623** [comment]
Hello @maxime18dev ,

I can't reproduce your issue on PS 1.7.7.2 nor PS 1.7.7.8 :
<img width="1169" alt="Screenshot 2021-09-15 at 16 46 15" src="https://user-images.githubusercontent.com/16019289/133455878-ea24ef4c-ca53-444b-949b-7f7c54a07007.png">


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
