### ISSUE TITLE
FO - Product disabled - an exception is displayed when changing combination or increasing / decreasing a quantity

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25891]
#### Describe the bug

A product disabled, in the FO when increasing decreasing the quantity => an exception is dislayed
A product with combinations is disabled.
In the FO when we try to change the combinations => an exception is displayed

#### Steps to Reproduce

- [ ] Issue 1
1. Go to BO > Catalog > Products page and edit a product with combinations
2. Disable it
3. Click on Preview
4. FO page opens with a message in the header This product is not visible to your customers.
5. Change a combinations
6. See error 
![image](https://user-images.githubusercontent.com/16067358/133438164-a3084a14-2872-463f-aab0-cd02f7cb1760.png)

- [ ] Issue 2
1. Go to BO > Catalog > Products page and edit a product (any type of a product)
2. Disable it
3. Click on Preview
4. FO page opens with a message in the header This product is not visible to your customers.
5. Increase / Decrease the quantity
6. See error 
![image](https://user-images.githubusercontent.com/16067358/133583386-917ebb5c-28ec-4696-849e-9ef4599faef5.png)

In the PS1777 => ok
![image](https://user-images.githubusercontent.com/16067358/133438408-2c4836f7-b94a-46db-b952-6ca706afb495.png)
![image](https://user-images.githubusercontent.com/16067358/133583535-e7f806ab-696f-443e-90d9-933df8154e6e.png)

#### Additional information

* PrestaShop version: 1780rc1build4
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed in #25903 by @Progi1984
