### ISSUE TITLE
some problems after upgrade to 1.7.7.7

### ISSUE THREAD

**Issue by IranDec** [PrestaShop/PrestaShop#25902]
Hi
I had Prestashop 1.7.7.4 Persian language after the upgrade that I reach this error and didn't let the order detail page load completely 
PHP 7.2
https://ibb.co/KDgKPRx

but there is no problem in English language

**Comment by hibatallahAouadni** [comment]
Hello @IranDec 


Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
