### ISSUE TITLE
BO - Warning is empty when we try to delete all combinations

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25901]
#### Describe the bug

In the BO > Catalog > Products > Product details page combinations Tab, when we try to delete all combinations => the warning is empty
![image](https://user-images.githubusercontent.com/16067358/133466486-5a9d70a2-71b8-4045-92e0-43250217ea0e.png)

#### Expected behavior

It should be
![image](https://user-images.githubusercontent.com/16067358/133466625-2bbd2aed-f5a1-4653-a7aa-0020cb864c51.png)

#### Steps to Reproduce

1. Go to BO > Catalog > Products page
2. Edit a product with combinations
3. In the combinations Tab > select all combinations and click on `Delete combinations`
4. See an error

#### Additional information

* PrestaShop version: 1.7.8.0rc1build4
* PHP version: 7.2

**Comment by Progi1984** [comment]
Fixed in #25904 by @Progi1984
