### ISSUE TITLE
BO - Product V2 - The Impact price is not refreshed (Ajax issue)

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25907]
#### Describe the bug

In the BO > Catalog > Product page V2 > Combination details page,
The Impact on the price is not updated automatically. => it is an ajax issue.

#### Steps to Reproduce

1. Go to BO > Advanced Parameters > Experimental Features page
2. Enable Experimental product page
3. Go to BO > Catalog > Products page and edit a product with combinations V2
4. Edit a combination
5. Set the impact on price tax excluded and click outside
6. The impact on price tax included is not changed
7. Refresh the page => it will be ok
8. Set the impact on price tax included and click outside
9. The impact on price tax excluded is not changed
10. Refresh the page => it will be NOK => the impact on price tax included is **converted**

**Screenshots**
https://www.awesomescreenshot.com/video/5253538?key=cb77df6550b6a4e059f9b6bf1433d30d

#### Additional information

* PrestaShop version: 1.7.8.0rc1build4
* PHP version: 7.2

**Comment by jolelievre** [comment]
Indeed this is a known issue, we didn't have time to implement the synchronization in combination form
But there are already modifications planned for this part:
- handle multishop prices for combinations
- the display of the pricing has changed in the new wireframe (see screenshot)

So the bug will probably be fixed at the same time as one of these two features.

<img width="716" alt="Capture d’écran 2021-09-16 à 14 14 38" src="https://user-images.githubusercontent.com/13801017/133610273-8c15d050-bc72-4da2-ac4e-d7d42a3e7db2.png">
