### ISSUE TITLE
Faceted search fail in combinations

### ISSUE THREAD

**Issue by mack94** [PrestaShop/PrestaShop#25910]
#### Describe the bug

When using faceted search we got a problem - filters shows wrong results in products with combinations (especially prices). It shows only price of default combination, not the right one which fulfill the filter requirements.

#### Expected behavior

Output from filter, should be only the combination and it's prices which is expected by a customer (which fill right filter attributes)

#### Steps to Reproduce

1. Create product with 3 combinations 
2. Each combination has different price
3. Go to any page with products
4. Filter (look at price slider - its max value is max price of default combination)
5. In filter choose Attribute which is not default
6. Look - it shows the right product but the price is from default combination (which don't meet filter attribute value).

**Screenshots**

#### Additional information

To sum up: If you got X product with sizes S, M, L which has different price then you got a problem. If customers filter by size for example L, they will se WRONG: price range (slider), prices on products (they will see S prices).

* PrestaShop version: 1.7.7.8
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @mack94 

Thanks for reporting the issue!
I reproduce the issue wih PS1767, PS1770 and PS1778 with `FacetedSearch` `v3.7.1`, see the attached screen record below:

https://drive.google.com/file/d/1tBOxqabHX2ERdCvLkEe4WZlYpqAxTvkV/view

Related to #16952 (ping @PierreRambaud & @Hlavtox )
Ping @PrestaShop/product-team wdyt? what's the right behavior to fix the issue? :pray: 

Thanks!

**Comment by mack94** [comment]
Related also to #15164 and #15166 

Mentioned then it is not a priority but really, still not?

**Comment by mack94** [comment]
do you work on it maybe? Or you got some suggestion how to fix it?

@hibatallahAouadni @PierreRambaud @Hlavtox

**Comment by hibatallahAouadni** [comment]
Hello @mack94 

> Related also to #15164 and #15166

Well, your issue is not just related it's a duplicate of #15164
And as this issue is already in our debug backlog, I'm closing yours as a duplicate.
So, to be informed when it's fixed, please subscribe to the issue mentioned above.

PS: I just add your detailed report to #15164 description, so thank you very much :pray: 

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #15164
