### ISSUE TITLE
Banner config is not displayed well

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#25911]
#### Describe the bug

![image](https://user-images.githubusercontent.com/23308427/133643868-7218cf0e-98b1-4236-b3e7-f2efd9224829.png)

#### Expected behavior

![image](https://user-images.githubusercontent.com/23308427/133643827-123601e2-01ba-4b21-ba84-b398c7934018.png)

#### Steps to Reproduce

1. BO > Modules > Module Manager
2. Click on **Configure** button of `ps_banner` module
3. See error

**Screenshots**

![Výstřižek](https://user-images.githubusercontent.com/6097524/133637163-e564debc-930c-487c-b2f3-d6c5021734f4.JPG)

#### Additional information

* PrestaShop version: develop
* Banner module version: 2.1.1
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

I was able to reproduce the issue with PrestaShop version 1.7.8.x and develop. I’ll add this to the debug backlog.
And it's a regression!

Thanks for your PR :rocket: 

Thank you
