### ISSUE TITLE
Incorrect amount with wire payment (always at 0) 

### ISSUE THREAD

**Issue by jonathanromain** [PrestaShop/PrestaShop#25929]
A bug already reported in old versions but which probably came back in version 1.7.6.8 of Prestashop and 2.1.0 of the transfer module.

An amount 0.00 goes up in the field, and yet during the recap, Prestashop does display the price and in the mail "awaiting bank transfer" the price also goes up.

Has anyone ever encountered the error?

thank you for your comeback

![Capture-d’écran](https://user-images.githubusercontent.com/34910831/133985005-5b52e582-27f0-4a4f-910f-6f1a0cf2e179.png)

**Comment by hibatallahAouadni** [comment]
Hello @jonathanromain 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

![image](https://user-images.githubusercontent.com/23308427/133986569-f2a2d71b-f74d-41fb-9c85-c3523be56371.png)

We need these blocs to reproduce your issue!

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
