### ISSUE TITLE
[BO] - Add offline translation functionality

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#25926]
#### Is your feature request related to a problem?

When I add English traduction to translate product description on the Backoffice , the new translation should not be visible on the front office until I finish products translating

#### Describe the solution you'd like

Translate offline

Regards
PS1.7.7.8

**Comment by hibatallahAouadni** [comment]
Hello @go-sudo 

I just edit your issue description, could you please confirm these modifications.
Waiting for your feedback.

Thanks!

**Comment by go-sudo** [comment]
Hello @hibatallahAouadni  your are the best , I appreciate your help , that's definitely correct , I confirm

**Comment by hibatallahAouadni** [comment]
Hello @go-sudo 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by eternoendless** [comment]
Is this in the product page, right? You'd like to save a working draft while you translate content?

**Comment by go-sudo** [comment]
Hi @eternoendless , yes because when we disable the language from BO we can not select it on product page , it disappears

**Comment by Hlavtox** [comment]
@go-sudo Hi, this is now fixed on the new product page in Prestashop 8.1. :-)
