### ISSUE TITLE
Amount 0 in the order summary by bank transfer module and check bank

### ISSUE THREAD

**Issue by jonathanromain** [PrestaShop/PrestaShop#25930]
#### Describe the bug

A bug already reported in old versions but which probably came back in version 1.7.6.8 of Prestashop and 2.1.0 of the transfer module.  An amount 0.00 goes up in the field, and yet during the recap, Prestashop does display the price and in the mail "awaiting bank transfer" the price also goes up.  Has anyone ever encountered the error?  

#### Expected behavior
Get the right amount, just like before.

#### Steps to Reproduce

1. Make an order
2. Pay with wire payment
3. View the amount

**Screenshots**
![Capture-d’écran](https://user-images.githubusercontent.com/34910831/133989315-ec493cc5-3139-4dab-bfb2-1d2f1a7a1112.png)

#### Additional information

- PrestaShop version: 1.7.6.8
- PHP version: 7.2.34
- transferBank: v2.1.0

**Comment by hibatallahAouadni** [comment]
Hello @jonathanromain 

I didn't manage to reproduce your issue with PS1778, see the attached screenshots below:

![image](https://user-images.githubusercontent.com/23308427/134002681-b59ec93a-5fb0-4c10-a3cb-09e27f66e66f.png)

---
![image](https://user-images.githubusercontent.com/23308427/134002687-4b2f1104-14c3-42b0-a868-8a965ead47a8.png)

---
![image](https://user-images.githubusercontent.com/23308427/134002696-6599c677-ee5f-46aa-a8ed-ecb29e3ffb22.png)

---
![image](https://user-images.githubusercontent.com/23308427/134002713-c6aaa691-e172-4dfd-8c40-dda429269247.png)
 
Please check and feedback.
Thanks!

**Comment by jonathanromain** [comment]
I actually have the same thing as you
But when I choose "Pay by bank wire" and that I validate, on the order summary page ", I have the result indicated on the screenshot posted above

![test](https://user-images.githubusercontent.com/34910831/134003542-e7ac88af-ac1c-46be-877f-8bd5d5c7df61.png)

**Comment by hibatallahAouadni** [comment]
Hello @jonathanromain 

As you can in the attached screenshot below, the amount is well displayed:

![image](https://user-images.githubusercontent.com/23308427/134004132-b99fafbc-96c1-40a8-9504-debf8a8ee501.png)

Could you please check if you have some overrides or modules that impact the `ps_wirepayment` module functionality.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @jonathanromain 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by micka-fdz** [comment]
Hi @hibatallahAouadni,

Could you reopen this issue please? I've same issue with PS v1.7.7.4 and ps_wirepayment v2.1.0.

**Comment by hibatallahAouadni** [comment]
Hello @micka-fdz 

Could you please more details and steps to reprdouce the issue.
Cause with the provided infos, I coudn't reproduce the issue.

Thanks!

**Comment by micka-fdz** [comment]
@hibatallahAouadni, steps to follow:

1. Make an order
2. Pay with wire payment
3. View wrong amount on confirmation page

Have you tried with PS 1.7.6.8 and/or 1.7.7.4? In your previous comment, you said you tested in 1.7.7.8.

**Comment by jonathanromain** [comment]
Hello @micka-fdz 

modules / ps_wirepayment / ps_wirepayment.php on line 232

We must change the line

$ totalToPaid = $ params ['order'] -> getOrdersTotalPaid () - $ params ['order'] -> getTotalPaid ();
in
$ totalToPaid = $ params ['order'] -> getOrdersTotalPaid ();

**Comment by jf-viguier** [comment]
@jonathanromain check that this checkbox is not checked 
![image](https://user-images.githubusercontent.com/16720275/139265366-8909f334-c598-4883-8689-a6210c6de16c.png)

**Comment by jf-viguier** [comment]
Your siuggested change is not correct

**Comment by bfontaine** [comment]
@jf-viguier where is this checkbox in the admin area?

**Comment by bfontaine** [comment]
See also https://github.com/PrestaShop/PrestaShop/issues/20580.

**Comment by arLevi** [comment]
I experienced this issue when I wrote my own payment method following `ps_wirepayments`
and I put by accident a constant order status that is a "blue color" meaning = "already paid" so the amount was 0 as there's nothing left to pay ...
```
# shop -> order settings
| PS_OS_WS_PAYMENT        | 11 |
```
I used this constant variable here
```
# file: controllers/front/validation.php
...
$this->module->validateOrder($cart->id, (int) Configuration::get('PS_OS_WS_PAYMENT'), $total, $this->module->displayName, null, $mailVars, (int) $currency->id, false, $customer->secure_key);
                                                                       ^^^
```

So instead I created my own status ( or you can use existing "purple color" one such that requires processing) and placed its integer ID that was created by PS instead like so:
```
# file: controllers/front/validation.php
$this->module->validateOrder($cart->id, 14, $total, $ ...);
```
