### ISSUE TITLE
Bug Search in prestashop 1.7.7.8

### ISSUE THREAD

**Issue by clearisesp** [PrestaShop/PrestaShop#25941]
#### Describe the bug

An error has been found in the search where we can see that typing any word returns search results. There are no matching words.

#### Expected behavior

It should say no results found

#### Steps to Reproduce

All this has been done with a clean catalog.

1) Create a new product with just the name to make the test more efficient.
2) Try in the search bar to enter any word to search that is not referenced in any product.
3) It will be observed how it returns results despite the absence of coincidences of any kind.

**Screenshots**

(1) ![Captura de pantalla 2021-09-21 a las 11 08 08](https://user-images.githubusercontent.com/91121803/134144232-2d2c71d1-8d41-4c97-ae69-5a78b6784259.png)
(1) ![Captura de pantalla 2021-09-21 a las 11 08 15](https://user-images.githubusercontent.com/91121803/134144263-f7abb51a-9323-497c-be30-0a4e3ebd3467.png)
(2) ![Captura de pantalla 2021-09-21 a las 11 07 37](https://user-images.githubusercontent.com/91121803/134144332-c6cefef5-e890-4fd9-b996-eeb6e88d24ca.png)
(3) ![Captura de pantalla 2021-09-21 a las 11 07 14](https://user-images.githubusercontent.com/91121803/134144357-835cb3e6-1c59-4a09-8da8-b368f27451e4.png)

#### Additional information

* PrestaShop version: 1.7.7.8
* PHP version: 7.4

**Comment by clearisesp** [comment]
Solve, disable search difuse, it is enabled by default. It does not work well.
![Captura de pantalla 2021-09-21 a las 11 17 32](https://user-images.githubusercontent.com/91121803/134145498-833084e5-0fe3-4a26-a203-20cdd22414c1.png)

**Comment by florine2623** [comment]
Hello @clearisesp ,

First you need to downgrade your PHP version, please check the devdocs here : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Yes that's the configuration for fuzzy search that allow that to happen !

I'll close your issue !
Thanks

**Comment by clearisesp** [comment]
Hello @florine2623 ,

In the php 7.3 that is recommended in that document, it does not work well either, you can check it ..., the best thing for now that it is in beta phase is to deactivate it, otherwise it will always give results. thanks!

> Hello @clearisesp ,
> 
> First you need to downgrade your PHP version, please check the devdocs here : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
> 
> Yes that's the configuration for fuzzy search that allow that to happen !
> 
> I'll close your issue !
> Thanks
