### ISSUE TITLE
Shopping Cart view button display

### ISSUE THREAD

**Issue by deepindersingh83** [PrestaShop/PrestaShop#25947]
The view button display is not proper in the shopping carts menu. 

After Upgrading from 1.7.7.7 to 1.7.7.8

#### Expected behavior

All other menus and buttons are displayed properly 

#### Steps to Reproduce

BO>Orders > Shopping Carts

![Capture](https://user-images.githubusercontent.com/568596/134157779-6630f285-47b3-4996-a599-dcc01bea1fd4.JPG)

* PrestaShop version: 1.7.7.8
* PHP version: 7.3

**Comment by florine2623** [comment]
Hello @deepindersingh83 ,

I can't reproduce your issue after a successful upgrade from 1.7.7.7 to 1.7.7.8 :
<img width="1424" alt="Screenshot 2021-09-21 at 14 47 54" src="https://user-images.githubusercontent.com/16019289/134173806-4215f2b8-ec1d-4645-9538-76de389e16d5.png">
<img width="1202" alt="Screenshot 2021-09-21 at 14 52 08" src="https://user-images.githubusercontent.com/16019289/134173815-d7916c05-01f3-4bc6-9e79-98078917dbfc.png">

Did you have any errors on the upgrade process ?
Can you try to clear the cache from PS and from browser ?

Thanks!

**Comment by deepindersingh83** [comment]
Hello @florine2623 

No error or issue during upgrade was a smooth transition
- same issue after clearing cache cleared as suggested.

Multistore feature is turn on. Can you try with multistore

**Comment by khouloudbelguith** [comment]
Hi @deepindersingh83,

I did not manage to reproduce the issue with PS1778 after an upgrade from PS1777 using the 1-click upgrade v4.12.0.
I attached a screen record
https://drive.google.com/file/d/1slIMtMSqaM_MgyIonfqKGFE7GeEseQdK/view?usp=sharing
try to open your shop in an incognito browser.
You need to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.
Thanks to check and feedback.

**Comment by hibatallahAouadni** [comment]
Hello @deepindersingh83 

Since we had no news from you for days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
