### ISSUE TITLE
[Product Comment] FO - Read user reviews (1) link just refresh the page only with pack product

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#25948]
#### Describe the bug
In the FO > Product details page, when we click on "Read user reviews (1)" => the page is just refreshed.
Only with pack product

#### Steps to Reproduce

1. Install the `productcomments` module
2. In the BO > Design > Position page > check that the `productcomments` is transplanted to the `displayProductAdditionalInfo` hook 
![image](https://user-images.githubusercontent.com/16067358/134160565-c02ad67a-b0be-4bce-95bd-3c9603ebd6fb.png)
3. Go to FO > Pack product details page
4. Add a review
5. In the BO > Module manager page > Approve the review 
6. Go back to FO > Pack product details page
7. Click on `Read user reviews (1)`
8. See error

https://drive.google.com/file/d/1zGCWPzYuJEdbQomGoDBIK0ByWHLYqImE/view?usp=sharing

PS1778 + productcomments v4.2.2 => ok
https://drive.google.com/file/d/1b1FPAGw2qK31BqNTHS8Om6-bRPmy0CIF/view?usp=sharing
#### Additional information

* PrestaShop version: 1780rc1build5
* PHP version: 7.2
* productcomments v4.2.2

**Comment by florine2623** [comment]
Fixed in PS 1.7.8.1

See https://github.com/PrestaShop/PrestaShop/pull/26410#issuecomment-951853176
