### ISSUE TITLE
form.js seo is undefined

### ISSUE THREAD

**Issue by apropsi** [PrestaShop/PrestaShop#25943]
#### Describe the bug

I just update Prestashop to 1.7.7.8 version and now I cant save a product. If I check console it saids: seo is undefined

(line 626)
  var elem = $('#form');

  function send(redirect, target, callBack) {
    // target value by default
    if (typeof(target) == 'undefined') {
      target = false;
    }
    **seo.onSave();**
    updateMissingTranslatedNames();

#### Expected behavior

Save the producto correctly

#### Steps to Reproduce

edit any product and try to save

**Screenshots**

#### Additional information

* PrestaShop version: 1.7.7.8
* PHP version: 7.4

**Comment by florine2623** [comment]
Hello @apropsi ,

you upgraded from which version ?

PS 1.7.7.8 is not compatible with PHP 7.4, only up to 7.3. 
More info here : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

**Comment by apropsi** [comment]
Downgraded to 7.3 same error.
Upgraded from 1.7.6.7
Thanks

**Comment by florine2623** [comment]
Hello @apropsi ,

I can't reproduce your issue.
After a successful upgrade from 1.7.6.7 to 1.7.7.8 :
<img width="1433" alt="Screenshot 2021-09-21 at 14 22 58" src="https://user-images.githubusercontent.com/16019289/134170517-315d4876-dff2-41f7-afc0-479da15b18e2.png">

I can edit my product as you can see per the screenshot :
https://drive.google.com/file/d/1fM5Y_WeiBqKjintFXqOYuxmYP2iq2yCU/vie
<img width="1167" alt="Screenshot 2021-09-21 at 14 25 51" src="https://user-images.githubusercontent.com/16019289/134170669-9e46eb09-f2e0-4784-8258-bbd0b4fa3dc3.png">

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
