### ISSUE TITLE
Add a channel for all PS version to check the PHP compatibility

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#25951]
As a user making an upgrade, I want to be able to upgrade my store only to a PS version that is compatible with my current PHP version to ensure the upgrade success

#### Describe the solution you'd like

- Create a channel that contains the PHP compatibility for all PS versions.
- If the user selects **"private release"** or **"local archive"** or **"local directory"**, we must check that the version to which he wishes to upgrade is compatible with his version of PHP. If the PS version isn't compatible with his PHP version, we should display the following error message: "The version of PrestaShop you want to upgrade to (V X.X.X.X) is not compatible with your current PHP version (V X.X.X). Please check the compatibility chart and upgrade to the required PHP version." and don't allow the user to upgrade (the button "Upgrade PrestaShop now" is disabled)

**Comment by ghost** [comment]
Hello @marionf 

What do you think of this?  

![Capture d’écran de 2021-09-22 11-31-39](https://user-images.githubusercontent.com/5064590/134319586-d17c05fd-f4c5-489c-804b-ba6a8b5d5211.png)


![Capture d’écran de 2021-09-22 11-31-14](https://user-images.githubusercontent.com/5064590/134319526-d3f80075-cc8f-4113-a7ad-48726805be01.png)

**Comment by marionf** [comment]
Hello @okom3pom 

The [table to indicate all the compatibilit](https://github.com/PrestaShop/PrestaShop/issues/25659)y is required
By deleting the table, the user will not know which PHP version he needs to make more recent updates.
Let's take an example:
You are in PS 1.6.1.24 with PHP5.4 and you want to upgrade to PS 1.7.7. 
To upgrade to this version you need to have PHP 7.1, 7.2 or 7.3
The problem is that you can't upgrade to PHP 7.2 or 7.3 because it's not compatible with PS 1.6.1.24
With the table, you can easily see that you need PHP 7.1

Also, the PHP version in your screenshot is a little big too long. We should only indicate the PHP version, the whole system used is not useful.

**Comment by marionf** [comment]
Hello @okom3pom

Following your feedback, we decided to not prevent the upgrade if the version of PHP is not compatible with the version of PS to which the user wishes to upgrade.
But rather to display a modal, in any case, to remind the user to check that his/her version of PHP is compatible with his/her PS version (current and the one he/she wants to upgrade)
So, I close this issue ;)
