### ISSUE TITLE
Remove shop logo attached in email sent by prestashop

### ISSUE THREAD

**Issue by darkf3d3** [PrestaShop/PrestaShop#25960]
#### Describe the bug
The shop logo it's attached to each email sent by Prestashop.

#### Steps to Reproduce
1. Place an order or any other action that causes an email to be sent from Prestashop
2. Check the email received (you'll see the shop logo attached to the email

**Involved file:**
/httpdocs/classes/Mail.php (lines 504-507)
`/* don't attach the logo as */`
`if (isset($logo)) {`
 ` $templateVars['{shop_logo}'] = $message->embed(\Swift_Image::fromPath($logo));`
`}`

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: PHP7.3

**Comment by hibatallahAouadni** [comment]
Hello @darfk3d3 

I didn't manage to reproduce your issue with PS1778, see the attached screenshot blow:

![image](https://user-images.githubusercontent.com/23308427/134331923-c28ad788-12c0-4c38-af9d-1c35679caa45.png)

---
![image](https://user-images.githubusercontent.com/23308427/134331893-6cbc4f6b-9ce2-486e-b9d4-87b209731e24.png)

Please check and feedback.
Thanks!

**Comment by darkf3d3** [comment]
That's strange, on my installation the logo it's attached to the email. Maybe this happen when uploading a logo different from the prestashop default logo?

**Comment by khouloudbelguith** [comment]
Hi @darfk3d3,

What is the exact mail server did you use?
In the BO > Advanced Parameters > E-mail page, which case did you use, is it  ` Use /usr/sbin/sendmail` or `Set my own SMTP parameters`?

Thanks!

**Comment by darkf3d3** [comment]
I use "Set my own SMTP parameters" (SSL port 465)

**Comment by khouloudbelguith** [comment]
@darfk3d3, I did not manage to reproduce the issue with PS1.7.7.7.
I attached a screen record
https://drive.google.com/file/d/1RIh8vAjs4dFs0ukLCmIzVJGNB1Oqanqi/view?usp=sharing

Thanks to check and feedback.

**Comment by hibatallahAouadni** [comment]
Hello @darfk3d3 

Since we had no news from you for days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
