### ISSUE TITLE
Missing VAT 10% for Czech Republic

### ISSUE THREAD

**Issue by d33x** [PrestaShop/PrestaShop#25963]
#### Describe the bug

When we import the VAT rules via the localization pack, a rule for the Czech Republic is missing.

Only the 15% and 21% rules are added, whereas there is a 10% VAT rule.
See https://ec.europa.eu/taxation_customs/tedb/vatSearchForm.html

#### Expected behavior

The 10% VAT should also be added

#### Steps to Reproduce

1. Go to 'International > Localization'
2. Select 'Czech republic'
3. Selex 'Taxes'
4. Click on 'Import'
5. Go to 'International > Taxes'
6. See the issue, there is no 10% VAT

#### Additional information

* PrestaShop version: 1.7.7.8
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @d33x 

I reproduce the issue with PS1767 and PS1778, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/134382340-1bb09927-3b86-4e1f-b5fe-18bf909a249e.png)

The only taxes imported within the localisation pack are **DPH CZ 15%** & **DPH CZ 21%**.
Ping @PrestaShop/product-team any idea about this issue? :pray: 

Thanks in advance!

**Comment by Hlavtox** [comment]
I confirm that second reduced tax 10% should be added into the localization pack. 👍

**Comment by ShaiMagal** [comment]
@hibatallahAouadni 
This issue should be closed. Already fixed by #33976 
Btw, 10% Czech VAT will canceled 2024-01-01, so... :)

**Comment by hibatallahAouadni** [comment]
Hello @ShaiMagal 

Thanks for your feedback!
Closing the issue as it was fixed by the PR mentioned above.

Thanks!
