### ISSUE TITLE
Error whe saving a product in "debug mode"

### ISSUE THREAD

**Issue by Codencode** [PrestaShop/PrestaShop#25962]
#### Describe the bug
An error is shown when saving an article with combinations.
The problem occurs only in debug mode

#### Error log:
Notice: A non well formed numeric value encountered in src\Adapter\Product\AdminProductWrapper.php:152

**Screenshots**
https://user-images.githubusercontent.com/2463965/134326580-103134bd-6b3b-47e4-8996-04ad087d0199.mp4

#### Steps to Reproduce
Open a product article with combinations and save

#### Additional information

* PrestaShop version: >=1.7.7.6

#### How to fix
In src\Adapter\Product\AdminProductWrapper line 146 add:
`$combinationValues['attribute_ecotax'] = (float) $combinationValues['attribute_ecotax'];`

**Comment by hibatallahAouadni** [comment]
Hello @Codencode 

Could you please check this issue #25797 it seems similar to yours.
Please check and feedback.

Thanks!

**Comment by Codencode** [comment]
Hello @hibatallahAouadni 

Yes it is the same.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #25797
