### ISSUE TITLE
As a user, I should be able to easily install in 1 click the native modules uninstalled (keep module catalog page)

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#25978]
#### Is your feature request related to a problem?

As a user, I should be able to easily install in 1 click the native modules uninstalled

#### Describe the solution you'd like

We should keep the "module catalog" BO page of the core.
On this page will be displayed the modules present in the /modules folder and not installed.
This way, the user can easily install a native module that is uninstalled.

**Comment by PierreRambaud** [comment]
Done with #25245.
Modules present on disk are now in the Module Manager, with an uninstalled filter (as discussed weeks ago with @MatShir)

**Comment by marionf** [comment]
I put the PR on waiting for PM, we will discuss it with @MatShir 
If the Module catalog page is deleted there could be a problem for those who will use MBO: they will see the modules present on the disk and not installed both in Module Manager and in Module Catalog
