### ISSUE TITLE
Bad display in autoupgrade module with PrestaShop version 1.7.8.0 

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#25989]
#### Describe the bug

Bad display in autoupgrade module with PrestaShop version 1.7.8.0  see screenshot

#### Expected behavior

A good display like https://www.figma.com/file/GpRsUUCHcdhJPAaz7Eqzes/Autoupgrade?node-id=497%3A11710

#### Steps to Reproduce

1. Go to 'install the module'
2. Click on 'Click to  cinfigure'
3. Scroll down to 'Click Expert mod'
4. See display

**Screenshots**

![Capture d’écran de 2021-09-24 15-40-34](https://user-images.githubusercontent.com/5064590/134684389-b1b24007-8b5b-4ee6-9e5e-e044a3c68057.png)
![Capture d’écran de 2021-09-24 15-40-39](https://user-images.githubusercontent.com/5064590/134684393-a34adffc-9dcd-4833-bdc9-b446894b171e.png)

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: N/A

**Comment by deepindersingh83** [comment]
> #### Describe the bug
> Bad display in autoupgrade module with PrestaShop version 1.7.8.0 see screenshot
> 
> #### Expected behavior
> A good display
> 
> #### Steps to Reproduce
> Steps to reproduce the behavior:
> 
> 1. Go to 'install the module'
> 2. Click on 'Click to Configurer'
> 3. Scroll down to 'Click Expert mod'
> 4. See display
> 
> **Screenshots**
> 
> ![Screenshot of 2021-09-24 15-40-34](https://user-images.githubusercontent.com/5064590/134684389-b1b24007-8b5b-4ee6-9e5e-e044a3c68057.png)
> ![Screenshot of 2021-09-24 15-40-39](https://user-images.githubusercontent.com/5064590/134684393-a34adffc-9dcd-4833-bdc9-b446894b171e.png)
> 
> #### Additional information
> * PrestaShop version: 1.7.8.0
> * PHP version: N/A

Can you please clear cache and try again


![image](https://user-images.githubusercontent.com/568596/134686305-0dc0db47-fbac-46e7-97ba-57bb436ca75f.png)

**Comment by deepindersingh83** [comment]
Can you clear cache and try again

![image](https://user-images.githubusercontent.com/568596/134686475-7ba8241e-0948-4cf3-861c-01cddd526eef.png)

**Comment by okom3pom** [comment]
1.7.8.0 not 1.7.7.8 

Regards

**Comment by deepindersingh83** [comment]
![image](https://user-images.githubusercontent.com/568596/134689619-2ba3034e-21da-4b2d-9b17-f38baff0592f.png)

**Comment by ghost** [comment]
@deepindersingh83 thank you :) 

Regards

**Comment by khouloudbelguith** [comment]
Hi @okom3pom ,

I manage to reproduce the issue with PS1780rc
![image](https://user-images.githubusercontent.com/16067358/134707050-4c9ad948-5b95-421c-8184-344b16eb611e.png)
I'll add this to the debug backlog so that it's fixed.

Thanks for the PR!
