### ISSUE TITLE
ps_emailalerts - out-of-stock email is sent everytime the product is saved

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#25981]
#### Describe the bug

With combination products, if one of the combination is out-of-stock and I edit the product, everytime I save it, I'll receive an email.

#### Expected behavior

I should receive an out-of-stock email alert only once and not everytime I make a change on the product.

#### Steps to Reproduce

1. Install ps_emailalerts and Configure > Set threshold to 3
2. Edit a product with combination 
3. Set one combination quantity to 10, second combination to 1 > Save. You should receive email about low stock -> **OK**
3. Edit your product description > Save
4. You will receive again the out-of-stock alert -> **NOK**

**Screenshots**

Out-of-stock email sent for each combination :

<img width="638" alt="Screenshot 2021-09-24 at 11 55 31" src="https://user-images.githubusercontent.com/16019289/134656086-dcdf360b-55d3-4b5a-b675-e09a80b26ec0.png">

#### Additional information

* PrestaShop version: develop
* PHP version: 7.3

**Comment by Hlavtox** [comment]
Hi @florine2623, fixed, pls test. ;-)

**Comment by Hlavtox** [comment]
@matks Can you check my PRs if the solution is correct? Or we should not call the actionUpdateQuantity hook at all, if it did not change?

**Comment by arirangz** [comment]
Hello,

Any update on this one?

All stock email alerts (from module and core) should be sent only when a customer is ordering or if quantity changes from my point of view.

Thanks
