### ISSUE TITLE
[BO] Buttons are not well displayed (part 2)

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShop/PrestaShop#25980]
#### Describe the bug
After fixing #25740, `Search button` is still not well displayed
![image](https://user-images.githubusercontent.com/48441421/134642332-bb0445f3-f8d1-4386-88d6-260a1e1206a7.png)

#### Expected behavior

Button well displayed
![image](https://user-images.githubusercontent.com/48441421/134642550-c0b9168b-0916-4e52-a08b-0f471fd454be.png)

#### Steps to Reproduce

1. Go to BO > Orders
2. See The button

#### Additional information

* PrestaShop version: 1.7.8.x
* PHP version: 7.3

**Comment by boubkerbribri** [comment]
I don't know if it's related, the action buttons should be align=right
1.7.7.x : 
![image](https://user-images.githubusercontent.com/48441421/134643439-bc5bfd67-9dc7-4e6c-8f3f-34c63a3ff591.png)

1.7.8.x, develop : 
![image](https://user-images.githubusercontent.com/48441421/134643364-d8153bb0-3a29-4497-b1d9-f3d2611f4c28.png)

**Comment by Hlavtox** [comment]
@boubkerbribri I will fix it ;-)

**Comment by Progi1984** [comment]
Thanks @Hlavtox

**Comment by Progi1984** [comment]
Fixed by @hibatallahAouadni in #26026
