### ISSUE TITLE
Title case is forced by CSS in the blockreassurance module admin interface

### ISSUE THREAD

**Issue by the-ge** [PrestaShop/PrestaShop#25997]
#### Describe the bug

Many languages don't use title case, so forcing it by CSS makes the headings look unprofessional.

#### Expected behavior

Let every language decide its capitalization when doing the translation.
In my language, title case prepositions are a definite no-no. Actually, my language does not have title case, period. It only has lower, upper and sentence case. I blame the title case not looking completely off in some cases on the anglicization of all world's languages.

#### Steps to Reproduce

1. Go to Personnaliser > Modules > Gestionnaire de modules.
2. Search for the 'Réassurance' (blockreassurance) module.
3. Click on the 'Configurer' button.
4. You'll see the table title: 'Contenu Du Bloc' (or 'Blocuri De Continut' in my language). The text is actually 'Contenu du bloc' (or 'Blocuri de continut', but it is capitalized by the CSS of the module.

**Screenshots**
![Screenshot_20210924_234450](https://user-images.githubusercontent.com/6468893/134737651-863be40d-e8f8-46af-861a-829e373e0b71.png)
![Screenshot_20210924_234417](https://user-images.githubusercontent.com/6468893/134737661-af6f90c1-41d2-4bfc-98bd-4eac2bd71bbc.png)

#### Additional information

* PrestaShop version: 1.7.8.0 beta1
* PHP version: 7.4.23

**Comment by NeOMakinG** [comment]
ping @prestascott wdyt? I think it's relevant @PrestaShop/product-team

**Comment by hibatallahAouadni** [comment]
Hello @the-ge 

Thanks for your issue!
It seems as an improvement more than a bug :wink: 
As in the older version the whole sentence was uppercased, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/134883744-1bc0c6a0-978f-4045-9be4-6eb273b0739f.png)

So thank you for your suggestion and your PR! 
The Product Team will take it into consideration for future developments. 

PS: @NeOMakinG thanks for your quick reply :superhero: 

Thank you

**Comment by prestascott** [comment]
Hello everyone,

Thank you @the-ge for your request. Yep, the title case shouldn't be forced and only the first letter in the title should be in capital letter. 

LGTM

[Edit] Also, words written in capital letters are more difficult to read. So it's a bad practice for accessibility.

**Comment by matks** [comment]
Fixed in https://github.com/PrestaShop/blockreassurance/pull/267

Will be live with blockreassurance v5.1.0 release
