### ISSUE TITLE
Display of emails in Outlook (modern theme)

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#25990]
#### Describe the bug

The standard emails of the modern email theme do not display correctly in Outlook 2016. The logo is oversized.

#### Expected behavior

I expect the email to display correctly in Outlook 2016, because Outlook is a frequently used mail client.

#### Steps to Reproduce

1. In the BO, go to `Design - Email Theme`
2. Select the `modern` theme and click on `Generate emails` for any installed language.
3. In the FO send an email to yourself (doesn't matter what kind of email)
4. Open your inbox using Outlook 2016 on Windows 10
5. Notice the oversized logo.

**Screenshots**

![2021-09-24_090517](https://user-images.githubusercontent.com/7520695/134689801-79251650-9f69-45e2-91aa-2746ef75a5c3.png)

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: any
*  Mail client: Outlook 2016 on Windows 10 with default email viewer engine (Microsoft Word)

**Comment by khouloudbelguith** [comment]
Hi @lmeyer1,

Thanks for your report.
Does this issue occur only Outlook desktop version?
I used the Outlook web version, it is ok
I attached a screen record
https://drive.google.com/file/d/1RIh8vAjs4dFs0ukLCmIzVJGNB1Oqanqi/view?usp=sharing

Thanks to check and feedback.

**Comment by lmeyer1** [comment]
Yes, it occurs only on Outlook desktop version. I noticed it in version 2013 and 2016 on Windows 10.
As stated above: 
> Mail client: Outlook 2016 on Windows 10 with default email viewer engine (Microsoft Word)

**Comment by lmeyer1** [comment]
There is a second issue with the display of modern email template in Outlook desktop.
The footer is not centered as it is in all other email-clients.
![2021-09-29_135923](https://user-images.githubusercontent.com/7520695/135264159-f2fc6e71-ec43-4845-bab7-26536bcf9844.png)

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

I manage to reproduce the issue only with outlook (PS1767 and PS1778), see the attached screenshots below:

![image](https://user-images.githubusercontent.com/23308427/135466353-75dd38e3-5b16-42e0-8c41-0ddb11a32f02.png)

![image](https://user-images.githubusercontent.com/23308427/135467482-36124271-b1d8-4df0-8926-e7ac7036fc74.png)

I’ll add this to the debug backlog so that it’s fixed.
Thanks for your PR!

Thank you

**Comment by lmeyer1** [comment]
@hibatallahAouadni
Not so trivial to deserve a `Trivial` flag😊

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

You're right it's `Minor`, but the issue only occurs on Outlook Desktop App :wink: and IMHO I think that the number of users that use this app are so low :confused: for that it's `Trivial`.
But, let's ask the Product Team @PrestaShop/product-team wdyt? should it be `Minor` or `Trivial`?

**Comment by lmeyer1** [comment]
I quickly looked up mail client's marketing share, and according to https://www.litmus.com/blog/email-client-market-share-may-2021/, Outlook desktop has still a market share of 9%. Unfortunately, Outlook is a major hurdle when trying to get Emails right 😞

**Comment by marionf** [comment]
Yes, it's trivial
