### ISSUE TITLE
Customer review module: make rating mandatory

### ISSUE THREAD

**Issue by jak78** [PrestaShop/PrestaShop#26001]
#### Is your feature request related to a problem?

Customers that write a review tend to put 3/5, without noticing they have to choose a rating. So they put an 'average' rate without having the opportunity to choose an appropriate rating based on their experience with the product or the order.

#### Describe the solution you'd like

Add an option to make rating choice mandatory instead of 3/5 by default.

**Comment by hibatallahAouadni** [comment]
Hello @jak78 

I totally recommend this feature 👏 cause all the time I forget that the rating stars are just above the form. And by default, my review is always 3/5.


Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you
