### ISSUE TITLE
Problem using coupon in products with different VATs

### ISSUE THREAD

**Issue by PereDaurell** [PrestaShop/PrestaShop#26006]
#### Describe the bug

Discounts applied with coupons miscalculate the base prices when the coupon applies only to one of the items.

#### Expected behavior

The first item should have a base price with the total coupon discount applied. The second item should not carry any discount or amount addition (as it happens)

#### Steps to Reproduce

1.- Create a coupon of 70% discount for an article A with a VAT of 4%.
2.- Buy article A (with a discount) and another article B with a different VAT rate (VAT 21%) (without discount)
3.- Apply the coupon.
4.- Review the totals, discounts and base prices. Can you explain how it has been calculated?

**Screenshots**

![PrestaErroCupones](https://user-images.githubusercontent.com/91461607/134880946-b3ad999c-ad53-4d13-b780-cd51eb8b0467.png)

#### Additional information

* PrestaShop version: 1.7.7.8
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @PereDaurell 

Thanks for your issue!
This is a known rounding issue, you can find in this EPIC #19445 all issues related/duplicate to your issue.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @PereDaurell 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
