### ISSUE TITLE
ps_facetedsearch module bug: Search with Null quantity options, but there are still available products in the results.

### ISSUE THREAD

**Issue by tiedh** [PrestaShop/PrestaShop#26013]
#### Describe the bug

I found this problem after I try to search to find out of stock products using ps_facetedsearch module.
The product found that the problem is a Product with combinations. I think the module only searches only with quantity of Simple product.

#### Expected behavior

I think the module should able to find Simple products and the product with combinations whose sum of combinations is really zero. not mixed with combinations is available.

#### Steps to Reproduce

1. On the project should have Simple products and Product with combinations.
2. Go to Categories page on the frontend 
3. Click on the search filter as "Null quantity"  
4. See the result.

**Screenshots**
![Screen Shot 2564-09-28 at 13 58 55](https://user-images.githubusercontent.com/91517381/135038872-198eac7f-6964-4117-8996-ba6a35c625b0.png)

The product in red border has 2 combination items, Some of them is out of stock and other one is available. 

#### Additional information

* PrestaShop version: 1.7.7.8
* PHP version: 7.3.3
* ps_facetedsearch version: v3.7.1

**Comment by florine2623** [comment]
Hello @tiedh ,

I can't reproduce your issue with PS 1.7.7.8 and ps_facetedsearch v3.7.1.
<img width="1225" alt="Screenshot 2021-09-28 at 09 59 07" src="https://user-images.githubusercontent.com/16019289/135048211-3d0251b0-618e-476d-9e66-3d8fc07dbc19.png">
<img width="888" alt="Screenshot 2021-09-28 at 09 59 21" src="https://user-images.githubusercontent.com/16019289/135048219-22569550-f0b0-48b2-91b7-8e707dc20bc2.png">

As only one product is completed out-of-stock, only one product is display after selecting the filter :
<img width="1121" alt="Screenshot 2021-09-28 at 10 05 53" src="https://user-images.githubusercontent.com/16019289/135048320-ca1106fd-02ea-4286-9f72-cf474b3a400c.png">

I'll close your issue as I can't reproduce it.

**Comment by tiedh** [comment]
Hello @florine2623 ,

I can't also reproduce follow your product created by virtual product with combinations.

Because, Product with combinations is can be create with Standard product only.

How you can create the product?
