### ISSUE TITLE
PR checks fail with error

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#26011]
#### Describe the bug

Pull request scripts fail with error 
> Unable to resolve action `z3by/block-merge-commits-action@master`, repository not found

see https://github.com/PrestaShop/PrestaShop/pull/25992/checks?check_run_id=3729007871

This error is unrelated to PR.

#### Expected behavior

PR checks should not fail with this error

#### Steps to Reproduce

Create new PR

#### Additional information

* PrestaShop version: develop
* PHP version: N/A

**Comment by florine2623** [comment]
ping @matks @PrestaShop/prestashop-core-developers ,

Do you experience the same issue when creating a PR ? Could you check please ?
Thanks !

**Comment by kpodemski** [comment]
This has been fixed already on `1.7.8.x`, and the PR merging `1.7.8.x` to `develop` is waiting for approvals.

**Comment by kpodemski** [comment]
@lmeyer1 you can try close/open your PR or just rebase 👍

**Comment by florine2623** [comment]
Thanks @kpodemski !

@lmeyer1 could you try what @kpodemski suggested and feedback ?
Thanks!

**Comment by lmeyer1** [comment]
Everything is ok mow! Thanks.
