### ISSUE TITLE
Sometimes Order is Split in 2 /// Paypal Payment

### ISSUE THREAD

**Issue by thequickmick** [PrestaShop/PrestaShop#26029]
#### Describe the bug

Sometimes, an Order is Split in 2 Orders with different Numers. Only with Payment Paypal.
Can't see the Reason for that! Paypal log with no issue... Order Timecode almost the same, or with 1 Second diffence.

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @thequickmick 

Could you please check this issue #9594 seems duplicate to yours.
And could you please provide more details (steps to reproduce, screen record, screenshots, php version, ...).
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @thequickmick 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #9594. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #9594
