### ISSUE TITLE
1-Click Upgrade from 1.7.5.1 to 1.7.7.8 error 

### ISSUE THREAD

**Issue by tone87** [PrestaShop/PrestaShop#26023]
#### Describe the bug

I tried to upgrade version more times but fail on upgrate db.

`[INTERNAL] /var/www/vhosts/***********/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 168 - Symfony\Component\Config\Exception\FileLoaderLoadException: Expected to find class "PrestaShopBundle\Controller\Admin\Configure\index" in file "/var/www/vhosts/***********/src/PrestaShopBundle/Controller/Admin/Configure/index.php" while importing services from resource "/var/www/vhosts/***********/app/../src/PrestaShopBundle/Controller/*", but it was not found! Check the namespace prefix used with the resource in /var/www/vhosts/***********/app/config/config.yml (which is being imported from "/var/www/vhosts/***********/app/config/config_prod.yml"). #0 /var/www/vhosts/***********/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(90): Symfony\Component\Config\Loader\FileLoader->doImport('/var/www/vhosts...', NULL, false, '/var/www/vhosts...') #1 /var/www/vhosts/***********/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(195): Symfony\Component\Config\Loader\FileLoader->import('config.yml', NULL, false, '/var/www/vhosts...') #2 /var/www/vhosts/***********/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(127): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseImports(Array, '/var/www/vhosts...') #3 /var/www/vhosts/***********/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/DelegatingLoader.php(40): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('/var/www/vhosts...', NULL) #4 /var/www/vhosts/***********/app/AppKernel.php(151): Symfony\Component\Config\Loader\DelegatingLoader->load('/var/www/vhosts...') #5 /var/www/vhosts/***********/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(776): AppKernel->registerContainerConfiguration(Object(Symfony\Component\Config\Loader\DelegatingLoader)) #6 /var/www/vhosts/***********/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(642): Symfony\Component\HttpKernel\Kernel->buildContainer() #7 /var/www/vhosts/***********/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() #8 /var/www/vhosts/***********/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(74): Symfony\Component\HttpKernel\Kernel->boot() #9 /var/www/vhosts/***********/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(50): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #10 /var/www/vhosts/***********/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(85): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() #11 /var/www/vhosts/***********/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #12 /var/www/vhosts/***********/Backoffice/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #13 {main}
`

#### Additional information

* PrestaShop version: 1.7.5.1
* PHP version: 7.2.3.4
* 1 Click upgrade version 4.12.0

**Comment by hibatallahAouadni** [comment]
Hello @tone87 

I didn't manage to reproduce your issue with provided infos.
Could you please provide more details, like did you delete a customer with a lot orders or did you delete a language or a currency before the upgrade.
Please check and feedback.

Thanks!

**Comment by tone87** [comment]
Hi, no, i never delete language , currency or orders
i just installed 1 click upgrade module and try to start on staging site
i tried to switch php version but the problem are the same and i can't know where are the problem.

**Comment by hibatallahAouadni** [comment]
Hello @tone87 

Could you please provide more infos, cause with the provided infos I didn't reproduce the issue.
Please check and feedback.

Thanks!

**Comment by Maxtab** [comment]
Hello, I think I have the same issue (1click upgrade module V4.12.0 too), please find attached  below the result of the php-ps-info script.
**I was upgrading from 1.7.6.8 to 1.7.7.8.**

During the process, all files seems to be copied normally, then, I have an error message similar to @tone87 : 
`[INTERNAL] /var/www/html/*******/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 168 - Symfony\Component\Config\Exception\FileLoaderLoadException: Expected to find class "PrestaShopBundle\Controller\Admin\Configure\index" in file "/var/www/html/*******/src/PrestaShopBundle/Controller/Admin/Configure/index.php" while importing services from resource "/var/www/html/*******/app/../src/PrestaShopBundle/Controller/*", but it was not found! Check the namespace prefix used with the resource in /var/www/html/*******/app/config/config.yml (which is being imported from "/var/www/html/*******/app/config/config_prod.yml"). #0 /var/www/html/*******/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(90): Symfony\Component\Config\Loader\FileLoader->doImport('/var/www/html/d...', NULL, false, '/var/www/html/d...') #1 /var/www/html/*******/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(195): Symfony\Component\Config\Loader\FileLoader->import('config.yml', NULL, false, '/var/www/html/d...') #2 /var/www/html/*******/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(127): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseImports(Array, '/var/www/html/d...') #3 /var/www/html/*******/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/DelegatingLoader.php(40): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('/var/www/html/d...', NULL) #4 /var/www/html/*******/app/AppKernel.php(151): Symfony\Component\Config\Loader\DelegatingLoader->load('/var/www/html/d...') #5 /var/www/html/*******/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(776): AppKernel->registerContainerConfiguration(Object(Symfony\Component\Config\Loader\DelegatingLoader)) #6 /var/www/html/*******/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(642): Symfony\Component\HttpKernel\Kernel->buildContainer() #7 /var/www/html/*******/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() #8 /var/www/html/*******/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(74): Symfony\Component\HttpKernel\Kernel->boot() #9 /var/www/html/*******/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(50): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #10 /var/www/html/*******/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(86): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() #11 /var/www/html/*******/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #12 /var/www/html/*******/admin417tiydfd/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #13 {main}`

Then, I cannot access the website or B/O, I have an error 500.

The shop is a single shop, one language, one currency, very few products (Less than 30), no clients with a lot of orders (no more than 10 orders).

Let me know if you need more details.

![phppsinfo](https://user-images.githubusercontent.com/16206268/135886362-3de01492-0e33-45e0-a4c0-cd15de56124e.PNG)

**Comment by Maxtab** [comment]
I tried the solution suggested here [#22141](https://github.com/PrestaShop/PrestaShop/issues/22141) (To delete some index.php file), but I still have the same result, here is the error message after trying the solution : 
`[INTERNAL] /var/www/html/*******/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 168 - Symfony\Component\Config\Exception\FileLoaderLoadException: Expected to find class "PrestaShopBundle\Controller\Admin\Configure\index" in file "/var/www/html/*******/src/PrestaShopBundle/Controller/Admin/Configure/index.php" while importing services from resource "/var/www/html/*******/app/../src/PrestaShopBundle/Controller/*", but it was not found! Check the namespace prefix used with the resource in /var/www/html/*******/app/config/config.yml (which is being imported from "/var/www/html/*******/app/config/config_prod.yml"). #0 /var/www/html/*******/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(90): Symfony\Component\Config\Loader\FileLoader->doImport('/var/www/html/d...', NULL, false, '/var/www/html/d...') #1 /var/www/html/*******/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(195): Symfony\Component\Config\Loader\FileLoader->import('config.yml', NULL, false, '/var/www/html/d...') #2 /var/www/html/*******/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(127): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseImports(Array, '/var/www/html/d...') #3 /var/www/html/*******/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/DelegatingLoader.php(40): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('/var/www/html/d...', NULL) #4 /var/www/html/*******/app/AppKernel.php(151): Symfony\Component\Config\Loader\DelegatingLoader->load('/var/www/html/d...') #5 /var/www/html/*******/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(776): AppKernel->registerContainerConfiguration(Object(Symfony\Component\Config\Loader\DelegatingLoader)) #6 /var/www/html/*******/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(642): Symfony\Component\HttpKernel\Kernel->buildContainer() #7 /var/www/html/*******/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() #8 /var/www/html/*******/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(74): Symfony\Component\HttpKernel\Kernel->boot() #9 /var/www/html/*******/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(50): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #10 /var/www/html/*******/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(86): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() #11 /var/www/html/*******/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #12 /var/www/html/*******/admin417tiydfd/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #13 {main}`

**Comment by florine2623** [comment]
Hello @tone87 ,

On issue  #22141, a PR was created to fix the issue, have you tried implementing it #22146?

**Comment by tone87** [comment]
No, sorry but I needed to update urgent and I buyed a module from addons that it update fine. 
The module is 
https://addons.prestashop.com/it/data-migration-backup/31424-1-click-direct-upgrade-to-17-migliore-e-piu-veloce.html

**Comment by florine2623** [comment]
You can update your mySQL version, you are using 5.0, it is recommended to use 5.6. More info here : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

If your update doesn't work due to this module, please contact the developer of the module directly.

Sorry, but as we can't reproduce your issue, we cannot help.
It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!
