### ISSUE TITLE
Cannot install any module on 1.7.8.0 when the employee language is spanish

### ISSUE THREAD

**Issue by tenenick** [PrestaShop/PrestaShop#26028]
#### Describe the bug

It is no possible to install any module.zip with the upload function. when the employee language is spanish

#### Expected behavior

1. Drag&Drop should start the install process
2. The same should happen by using the "select the file" link

#### Steps to Reproduce

1. Change employee language to Spanish
1. Go to the Module manager
2. Click on the upload button
3. Drag&Drop the install.zip
4. The file will saved in the browser download folder instead of starting the install process
5. When using the "select the file" link instead of Drag&Drop nothing happens
6. Go to Module Catalog page => see error

#### Additional information

* PrestaShop version: 1.7.8.0 RC1
* PHP version: 7.4.23

**Comment by hibatallahAouadni** [comment]
Hello @tenenick 

I didn't manage to reproduce your issue with PS1780_rc1, see the attached screen record below:

https://watch.screencastify.com/v/OKwUgfGy7vBv3v3l1uFd

Please check and feedback.
Thanks!

**Comment by tenenick** [comment]
Hi hibatallahAouadni,

thanks for getting in touch so soon. It's really strange. I don't understand why, but it still does the same, see my screen record:

https://user-images.githubusercontent.com/38130270/135304050-c1686cf8-f20b-4580-941c-ca9b7ce92fae.mp4

Thanks for checking.

**Comment by tenenick** [comment]
Hi hibatallah again.
I tried the following to solve the problem, still without success:
1. Switched from PHP 7.4.23 to 7.2.34
2. Reinstall from the scratch
Some more hints:
The mentioned faulty install is on a subdomain. 
I have another test install on another subdomain with PS 1.7.7.5 running well
My production webshop is on the main domain with PS 1.7.7.3 running well

One question: The test you made to reproduce it is on an local install on PC or a hosted server?
My installs are all on a hosted VPS.

If you wish I can grant you access to see the failure. Please advice.
Thanks and have a nice day
Nick

**Comment by hibatallahAouadni** [comment]
Hello @tenenick 

> One question: The test you made to reproduce it is on an local install on PC or a hosted server?

On an local install on PC. Well right now, I can't access to Module Manager cause of this issue #26036.
Could you please provide your navigator version, and could you please try to reproduce the issue with another navigator.

Please check and feedback.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @tenenick,

Thanks for your feedback.
I did not manage to reproduce the issue with PS1780rc1.
I attached a screen record
https://www.awesomescreenshot.com/video/5460217?key=838fcde3e99d0aada379bb8530c74f1e

Thanks to check and feedback

**Comment by tenenick** [comment]
I tried with Chrome Versión 94.0.4606.71 (Build oficial) (64 bits) and also with MS Edge Versión 94.0.992.37 (Compilación oficial) (64 bits). Always the same behaviour.

As I mentioned before: both other Installs I have on this server does not show this behaviour. 
I even had another test-install with PS 1.7.7.5 on the same subdomain before deleting it completely and installing the new RC1.

Never seen this before.

Thanks to all trying to help.
Nick

**Comment by khouloudbelguith** [comment]
@tenenick,

Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by tenenick** [comment]
Ok. will do on Monday. Now it's Friday, day, day... Nice weekend to all

**Comment by tenenick** [comment]
Hi again nice Monday to all,

I will provide **first the javascript console** log because I guess it is the most suspicious hint:
```
Uncaught SyntaxError: Invalid or unexpected token
prestashop-ui-kit.js:1 jQuery.Deferred exception: Cannot read properties of undefined (reading 'moduleImport') TypeError: Cannot read properties of undefined (reading 'moduleImport')
    at e.value (https://bak.tecuidanatura.com/admin333kxvyjv/themes/new-theme/public/module.bundle.js?1.7.8.0:2:26036)
    at new e (https://bak.tecuidanatura.com/admin333kxvyjv/themes/new-theme/public/module.bundle.js?1.7.8.0:2:15995)
    at HTMLDocument.<anonymous> (https://bak.tecuidanatura.com/admin333kxvyjv/themes/new-theme/public/module.bundle.js?1.7.8.0:2:49644)
    at o (https://bak.tecuidanatura.com/admin333kxvyjv/themes/new-theme/public/main.bundle.js:2:841814)
    at d (https://bak.tecuidanatura.com/admin333kxvyjv/themes/new-theme/public/main.bundle.js:2:842138) undefined
M.Deferred.exceptionHook @ prestashop-ui-kit.js:1
prestashop-ui-kit.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'moduleImport')
    at e.value (controller.js:699)
    at new e (controller.js:158)
    at HTMLDocument.<anonymous> (index.js:35)
    at o (prestashop-ui-kit.js:1)
    at d (prestashop-ui-kit.js:1)

**The PHP and Apache error logs refer IMHO both to another problem with the Dashboard Page in the BO.**

**php error log:**
[04-Oct-2021 09:56:51] WARNING: [pool bak.tecuidanatura.com] child 8200 said into stderr: "PHP message: PHP Warning:  file_exists(): open_basedir restriction in effect. File(/views/templates/hook/HookDashboardZoneTwo.tpl) is not within the allowed path(s): (/var/www/vhosts/tecuidanatura.com/:/tmp/) in /var/www/vhosts/tecuidanatura.com/bakdocs/classes/module/Module.php on line 2509"
[04-Oct-2021 09:56:53] WARNING: [pool bak.tecuidanatura.com] child 8222 said into stderr: "PHP message: PHP Warning:  file_exists(): open_basedir restriction in effect. File(/views/templates/hook/HookDashboardZoneTwo.tpl) is not within the allowed path(s): (/var/www/vhosts/tecuidanatura.com/:/tmp/) in /var/www/vhosts/tecuidanatura.com/bakdocs/classes/module/Module.php on line 2509"
[04-Oct-2021 09:56:54] WARNING: [pool bak.tecuidanatura.com] child 8215 said into stderr: "PHP message: PHP Warning:  file_exists(): open_basedir restriction in effect. File(/views/templates/hook/HookDashboardZoneTwo.tpl) is not within the allowed path(s): (/var/www/vhosts/tecuidanatura.com/:/tmp/) in /var/www/vhosts/tecuidanatura.com/bakdocs/classes/module/Module.php on line 2509"

**Apache error log**:
[Mon Oct 04 09:56:51.445829 2021] [proxy_fcgi:error] [pid 8150] [client 81.32.223.234:55690] AH01071: Got error 'PHP message: PHP Warning:  file_exists(): open_basedir restriction in effect. File(/views/templates/hook/HookDashboardZoneTwo.tpl) is not within the allowed path(s): (/var/www/vhosts/tecuidanatura.com/:/tmp/) in /var/www/vhosts/tecuidanatura.com/bakdocs/classes/module/Module.php on line 2509', referer: https://bak.tecuidanatura.com/admin333kxvyjv/index.php?controller=AdminLogin&logout=1&token=6e6a457db16d6c109e09037aae596998
[Mon Oct 04 09:56:53.589700 2021] [proxy_fcgi:error] [pid 8123] [client 81.32.223.234:58861] AH01071: Got error 'PHP message: PHP Warning:  file_exists(): open_basedir restriction in effect. File(/views/templates/hook/HookDashboardZoneTwo.tpl) is not within the allowed path(s): (/var/www/vhosts/tecuidanatura.com/:/tmp/) in /var/www/vhosts/tecuidanatura.com/bakdocs/classes/module/Module.php on line 2509', referer: https://bak.tecuidanatura.com/admin333kxvyjv/index.php?controller=AdminDashboard&token=85193e667eff9257dc5d32ce9be137da
[Mon Oct 04 09:56:54.444590 2021] [proxy_fcgi:error] [pid 8206] [client 81.32.223.234:61642] AH01071: Got error 'PHP message: PHP Warning:  file_exists(): open_basedir restriction in effect. File(/views/templates/hook/HookDashboardZoneTwo.tpl) is not within the allowed path(s): (/var/www/vhosts/tecuidanatura.com/:/tmp/) in /var/www/vhosts/tecuidanatura.com/bakdocs/classes/module/Module.php on line 2509', referer: https://bak.tecuidanatura.com/admin333kxvyjv/index.php?controller=AdminDashboard&token=85193e667eff9257dc5d32ce9be137da

**debug mode report > Log Messages > Debug:**

11:46:55 | security | Read existing security token from the session.Hide context[▼   "key" => "_security_main"   "token_class" => "Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken" ]
-- | -- | --
11:46:55 | security | User was reloaded from a user provider.Hide context[▼   "provider" => "PrestaShopBundle\Security\Admin\EmployeeProvider"   "username" => "webmaster@tecuidanatura.com" ]
11:46:55 | doctrine | SELECT p0_.id AS id_0, p0_.id_employee AS id_employee_1, p0_.id_module AS id_module_2, p0_.date_add AS date_add_3, p0_.date_upd AS date_upd_4 FROM ps_module_history p0_ WHERE p0_.id_employee = ?Hide context[▼   1 ]
11:46:55 | security | Stored the security token in the session.Hide context[▼   "key" => "_security_main" ]



**debug mode report > Log Messages > PHP Notices:**


11:46:55 | php | Warning: realpath(): open_basedir restriction in effect. File(/opt/plesk/php/7.4/share/pear) is not within the allowed path(s): (/var/www/vhosts/tecuidanatura.com/:/tmp/)Hide context    Hide trace[▼   "exception" => SilencedErrorContext {#3524 ▶} ]{▼   /var/www/vhosts/tecuidanatura.com/bakdocs/modules/ps_checkout/vendor/sentry/sentry/lib/Raven/Client.php:324 {▶}   Raven_Client::_convertPath() {} }
-- | -- | --


**Also in debug mode** but only on the Dashboard page apears a litte error window with the following message (similar to php log entries):

Warning en línea 2509 en archivo /var/www/vhosts/tecuidanatura.com/bakdocs/classes/module/Module.php
[2] file_exists(): open_basedir restriction in effect. File(/views/templates/hook/HookDashboardZoneTwo.tpl) is not within the allowed path(s): (/var/www/vhosts/tecuidanatura.com/:/tmp/)


When I close this little Window it disappears together with the debug bar above. The appears again when I change to another part of the BO.

I hope that helps.
If you still need it please advice what you mean with this 2 points, sorry never made that before:
host?
server setup and configuration

Many thanks for your work and have a nice day.
Nick

**Comment by hibatallahAouadni** [comment]
Hello @tenenick 

It seems you have an issue with this module **moduleImport**.
Could you please disable it and check if you still encounter the same issue.
Please check and feedback.

Thanks!

**Comment by tenenick** [comment]
Sure, I will do so if you tell me how to do it, sorry but could not find out how.

**Comment by tenenick** [comment]
In the the javascript console log it referenced to /themes/new-theme/public/module.bundle.js
The are 44 hits in there, e.g. :
this.**moduleImport**SuccessConfigureBtnSelector,(function(e){e.stopPropagation(),e.preventDefault(),window.location=u(this).attr("href")})),t.on("click"

Are you sure that **moduleImport** is a module that could be disabled?
Sorry for my ignorance

**Comment by tenenick** [comment]
Don't know if it helps:
I just deleted the entire folder  /themes/new-theme/public and copied the same folder but from my other testinstall on the same server but with PS 1.7.7.5 with the same result as before.
Well much luck searching the bug I have to go now. Dinner is waiting. :-)
Thanks for all

**Comment by florine2623** [comment]
Hello @tenenick ,

Are you using the classic template ?
If you are not, you should contact the develop or the template, the issue might come from there.

Also, I suggest changing your admin folder name for security reason, as well as your employee username.

**Comment by tenenick** [comment]
Hi @florine2623,
the install is just for test reasons and it is made from the scratch. Just freshly installed and no changes made.
So it has the default classic template.
It will deleted all after finishing all the tests. So no worry about security issues.
Thanks for trying to help

**Comment by tenenick** [comment]
Just made a clear new install of PrestaShop 1.7.8.0 final version deleting before the RC1 install on the same subdomain, with exactly the same results.
Now wondering if it could be an issue with the installation on a subdomain, What do you think?
Have a nice day

**Comment by tenenick** [comment]
Hi to all,
I guess I have the solution. It depends on what Install-Zip I choose to install:
1. prestashop_1.7.8.0-rc.1.zip (78.7MB) downloaded from https://www.prestashop.com/en/versions: 
  --> The first I tried with the problems described
2. prestashop_1.7.8.0.zip  (78.7MB) downloaded from https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.8.0:
   --> Final Release but with the same problems !!
3. prestashop_1.7.8.0.zip  (66.8MB) downloaded from https://www.prestashop.com/es/descarga:
  --> Final Release but smaller than that one from github aaaand it work fine!!! Why? What is the difference? Both should be final release or not?

The only diffence I saw during install was that the last and working install-zip didn't had the new option to activate SSL and the corresponding part in BO is like before. The other two not working zip's did have this option during install and a different part in the BO SSL config.
Well so far. I hope this all helps. Bye and good night
Nick

**Comment by matks** [comment]
Hello @tenenick I cannot download a ZIP from https://www.prestashop.com/es/descargar-exito could you tell me where you found the link to download?

**Comment by tenenick** [comment]
Hi matks
The Link is https://www.prestashop.com/es/descarga and not https://www.prestashop.com/es/descargar-exito  ;-)

**Comment by hibatallahAouadni** [comment]
Hello @tenenick 

> 1. prestashop_1.7.8.0-rc.1.zip (78.7MB) downloaded from https://www.prestashop.com/en/versions:

--> no problem :heavy_check_mark: 
> 2. prestashop_1.7.8.0.zip (78.7MB) downloaded from https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.8.0:

--> no problem :heavy_check_mark: 
> 3. prestashop_1.7.8.0.zip (66.8MB) downloaded from https://www.prestashop.com/es/descarga:

--> it's **1.7.7.8** and not 1.7.8.0 that's why not the same size :wink: 
![image](https://user-images.githubusercontent.com/23308427/136185478-1180ca13-2ce0-4d16-8393-18765de501b8.png)

Please check and feedback.
Thanks!

**Comment by tenenick** [comment]
Oh my god sooo sorry my fault! 
Ok then the fault persists with 1.7.8.0
I try to do an install without the SSL option activated from the beginning

Thanks so much and really sorry to make you waste your time

**Comment by tenenick** [comment]
Ok. Just installed again the final release from here: https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.8.0

The result is the same. Not possible to install modules :-( and the same log errors. It is not possible for me to make a clean install without this bug. I don't know what else I can try?

Thanks to all

**Comment by tenenick** [comment]
Hi I was just wondering if it would possible, that the ICU version installed on the server could affect? I mean I am using a spanish install, did you test it with a spanish install, too?
I have installed ICU 57.1 and the newest is 69.1. I got in touch with my hoster to check this.
If anybody has any idea please comment. Thank you.

**Comment by hibatallahAouadni** [comment]
@tenenick I will try to reproduce the issue with spanish install :wink:

**Comment by tenenick** [comment]
That is amazing: 😉 !!!!
I got it.
When installing the english version it works perfectly!!!
Still waiting for an answer from my hoster.
Now its up to you to know why spanish version does not work properly ;-)
Thanks to all

**Comment by tenenick** [comment]
and yes there are no more errors shown in the js console.

**Comment by tenenick** [comment]
It is even switchable:
Enter in BO in you Profile settings
choose "Español(Spanish) as your language e voilá: no more modules instalable
if you switch back to English everything works
You can switch as many times as you want. It will be always the same result:
English works, Spanish sucks

**Comment by tenenick** [comment]
Even more strange:
1. Being in English version in the BO
2. Installing a module (e.g. eicaptcha) without a problem and is visible and accessible in the english module manager
3. Entering in Module config and copying the URL
3. Switching to Spanisch 
4. The module dissapears in the spanisch module manager, but is still accessible with the copied Config-URL 
Very weird

**Comment by tenenick** [comment]
And if I make the install on spanish from the beginning there is no option in the BO Profile to switch the language to english!!!
It could be a desaster when shops with spanish install upgrade to 1.7.8 !!!

The only workaround is to to install the english localization pack. Than you can change again your Profile language and can install modules which unfotunately will be invisible in spanish.
It even works with the english localization pack installed but deactivated. I wont be shown in the FO but in the BO it is still switchable to english to make it possible to install modules.

So much fun resolving this guys. Wish good luck. Thanks for your work.

**Comment by tenenick** [comment]
More tests:
I loaded also the **british English** and the **German** language packs and both when switching to the alternative Language in BO permit to install Modules. It seems to be only the spanish pack that produces this problem

**Comment by tenenick** [comment]
Final Test:
- Installed Mexican Language Pack, choose **Español MX** (Spanish) in my BO User profile
- No problem to install modules
- Installing one module (eicaptcha)
- Now I switch to **Español** (Spanish) which corresponds to the Spanish Language Pack in my BO user profile
- No possibilty to install modules and the module installed before with  **Español MX** (Spanish) Language in BO Profile is not visible

**Conclusion:**
there should be definetely are problem in the Spanish language Pack

This issue should be adressed to the translation team IMHO

I finished here, hope anybody will solve this issue.

Have a nice day all together

**Comment by drkbcn** [comment]
![image](https://user-images.githubusercontent.com/2090227/136585830-7f3e0981-f866-452e-b4f9-1565ad4ef8a4.png)

Facing the same problem here, with Spanish (ES-ES) Everything works like a charm if I switch back to English.

**Comment by khouloudbelguith** [comment]
Hi @drkbcn,

I manage to reproduce the issue with PS1780.
When the employee langue is Spanish, I could not install a module in the module manager 
![image](https://user-images.githubusercontent.com/16067358/136588211-fee4f37c-dac8-4dbb-8063-6b45ff49b8c9.png)
Also the Module Catalog page, => NOK
![image](https://user-images.githubusercontent.com/16067358/136588798-f3f19605-5edb-4576-a4a7-b670b7073918.png)

It is ok with PS1777 and PS1778.
I'll add this to the debug backlog so that it's fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks!

**Comment by drkbcn** [comment]
Hi @khouloudbelguith 

Pull request done. Tested and everything works fine now :)
See: https://github.com/PrestaShop/TranslationFiles/pull/21

**Comment by tenenick** [comment]
Hi @drkbcn Muchas Gracias crack!!
It would be nice to have an easy workaround howto for dummies like me.
I mean is it possible to simply make the changes in  the corresponding file "AdminModulesNotification.es-ES.xlf" in /app/Resources/translations/es-ES ?
I did it but without success. I also tried to delete cache in var/cache/prod.
Can you please advice what to do.
Thanks a lot.

**Comment by drkbcn** [comment]
Hi @tenenick 

1. Open /app/Resources/translations/es-ES/AdminModulesNotification.es-ES.xlf
2. Go to line number 882 (`</target>`)
3. Remove de breakline to bring back `</target>` tag to line number 881 with the rest of the message
4. Save the file
5. Clean PS cache
6. Enjoy

Tested and checked for almost 4 times before making the PR.

**Comment by tenenick** [comment]
Hi @drkbcn 
I did exactly the same, but it did not work.
Then after testing everything, deleting all types of caches etc. There was only one difference with yours:
I did a translation before which was still there. 
I did it with the normal BO translation over Internacional > Traducciones > Traducciones  de Backoffice -> Español. There I searched for the Key "We strongly advise you to upgrade the modules on maintenance mode to avoid any cache issues." and changed it. This corresponds to the faulty part in the xlf file you found.
So I guess this was in any way blocking it.
The final solution was to reset (Reinicializar) this Key to it's Default traduction.
Thank you very much again. Now it is really solved.

**Comment by matks** [comment]
> PrestaShop/TranslationFiles#21

Very nice debugging !

We'll have to mirror change https://github.com/PrestaShop/TranslationFiles/pull/21 on Crowdin too.

**Comment by aixos** [comment]
Hi @drkbcn 
works fine
thanks

**Comment by eternoendless** [comment]
Should be fixed now, can you confirm?

**Comment by marionf** [comment]
@hibatallahAouadni Could you tell us if this issue is fixed with a clean install ?

**Comment by hibatallahAouadni** [comment]
@marionf I didn't manage to reproduce the issue, it looks it has been fixed :tada: 
https://watch.screencastify.com/v/r8cHEtGuEH4KWYreYuvv
