### ISSUE TITLE
Warning module/Module.php

### ISSUE THREAD

**Issue by eveneme** [PrestaShop/PrestaShop#26031]
error after entering the admin panel 

Screenshot: https://i.ibb.co/6grMv5K/obraz-2021-09-29-222213.png

**Linux #1 SMP Fri Jul 23 07:07:00 EDT 2021 x86_64
LiteSpeed
php 7.4.23**

/home/draco94/domains/bimmerstore.pl/public_html/test/classes/module/Module.php
[2] file_exists(): open_basedir restriction in effect. File(/views/templates/hook/HookDashboardZoneTwo.tpl) is not within the allowed path(s): (/home/draco94/domains/bimmerstore.pl/:/tmp:/var/tmp:/usr/local/lib/php/:/usr/local/php/)

**Comment by hibatallahAouadni** [comment]
Hello @eveneme 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
