### ISSUE TITLE
upgrade to 1.7.7.5 from 1.6.1.24 : Fatal error: Uncaught Unknown column 'h.live_edit' in /var/www/html/classes/db/Db.php on line 769

### ISSUE THREAD

**Issue by theMost1ted** [PrestaShop/PrestaShop#26039]
#### Describe the bug

After upgrading to Prestashop 1.7.7.5 from 1.6.1.24 I now have this :
<html>
<body>

Fatal error: Uncaught Unknown column 'h.live_edit' in /var/www/html/classes/db/Db.php on line 769
--

1 | 0.0000 | 388184 | {main}( ) | .../index.php:0
2 | 0.0454 | 2101048 | DispatcherCore::getInstance( ) | .../index.php:28
3 | 0.0456 | 2192056 | Dispatcher->__construct( ) | .../Dispatcher.php:207
4 | 0.0482 | 2194608 | Dispatcher->loadRoutes( ) | .../Dispatcher.php:249
5 | 0.0489 | 2219200 | HookCore::exec( ) | .../Dispatcher.php:596
6 | 0.0490 | 2220280 | Hook::getHookModuleExecList( ) | .../Hook.php:798
7 | 0.0518 | 2267328 | DbPDO->executeS( ) | .../Hook.php:134
8 | 0.0518 | 2249216 | DbPDO->query( ) | .../Db.php:613
9 | 0.0521 | 2250592 | DbPDO->displayError( ) | .../Db.php:385

</body>
</html>

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. update from 1.6.1.24 to 1.7.7.5

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: 7.1.14

**Comment by hibatallahAouadni** [comment]
Hello @theMost1ted 

I didn't manage to reproduce your issue. It seems that your issue is not a PrestaShop core bug.
It's a module issue related to this column `live_edit`, please contact your module developer.

We will close this issue.

Thanks!
