### ISSUE TITLE
Compiling the blockreassurance module breaks the url of the files

### ISSUE THREAD

**Issue by ProteanCode** [PrestaShop/PrestaShop#26032]
#### Describe the bug

Since my customer requested me to make the blockreassurance description longer than default 100 chars, I do have to recompile

I simply cloned the https://github.com/PrestaShop/blockreassurance/tree/v5.0.0 and after some changes to index.js inside _dev/back directory I recompiled the dist directory.

For that I have switched to NodeJS `v10.16.2` and NPM `6.9.0` and ran `npm install` and  `npm run build`

This overall worked, but once I rebuilt the dist directory and totally replaced it inside a shop `modules/blockreassurance/views
dist` (yeah I know I ll have to override that in template later on) I got a lot of 404 errors related to paths like this one:

`http://localhost/home/redacted/Desktop/Projects/redacted/redacted/shop/modules/blockreassurance/views/dist5948b667fefc89492356.png`

I have no idea why the compiled module uses the full absolute path of my local machine directory instead of relative one that could work after recompilation.

#### Expected behavior

The module after rebuild would not direct me into 404 on clientside files (js, png, etc.)

#### Steps to Reproduce

Use NodeJS `v10.16.2` and NPM `6.9.0`
For that matter I work on Ubuntu 20.04 if that means anything, you can switch node versions by simply replacing the content of directory where node executable symlink leads to

1. git clone https://github.com/PrestaShop/blockreassurance/tree/v5.0.0
2. do some changes to index.js in _dev/back
3. npm install
4. npm run build
5. copy the dist directory to/as modules//blockreassurance/views/dist
6. Visit the blockreassurance config page in admin panel and see 404 goes wild

#### Additional information

* PrestaShop version: 1.7.7.6
* PHP version: 7.3

**Comment by ghost** [comment]
Hello,

I reproduce also  this issue with the dev branch.

`http://127.0.0.1/var/www/html/177/PrestaShop/modules/blockreassurance/views/dista855ff2d546377320dd5.woff `

And a slash is missing after dist 

![Capture d’écran de 2021-09-30 11-52-36](https://user-images.githubusercontent.com/5064590/135430687-17c7a1f8-7c55-4910-9ccc-fdc5a44eeaca.png)

If we test the 5.1.0 module don't work

**Comment by kpodemski** [comment]
I'm working on it. https://github.com/PrestaShop/blockreassurance/pull/209

**Comment by hibatallahAouadni** [comment]
Ping @kpodemski do you think it's duplicate of #22892? IMO I don't think it's the same :confused:

**Comment by kpodemski** [comment]
@hibatallahAouadni it's not a duplicate, while working on #22892 I've discovered more issues

**Comment by hibatallahAouadni** [comment]
@kpodemski I see :slightly_smiling_face: thanks for your PR :tada: 
Thanks @ProteanCode for reporting the issue!
And thanks @okom3pom for cyour quick reply :superhero:

**Comment by leemyongpakvn** [comment]
@hibatallahAouadni and @kpodemski 

There are two problems with this issue:
1. In **Steps to Reproduce**
>> 5.copy the dist directory to/as modules//blockreassurance/views/dist

As I know `npm run build` automatically made `dist` files from `src` files, so any manual copy/paste is considered as intended break ;)

2. In @okom3pom comment
>> I reproduce also this issue with the dev branch.
127.0.0.1/var/www/html/177/PrestaShop/modules/blockreassurance/views/dista855ff2d546377320dd5.woff 

The issue with icon fonts was solved after Release 5.1.3 by [PR 518](https://github.com/PrestaShop/blockreassurance/pull/518)

**Comment by kpodemski** [comment]
thanks @leemyongpakvn
