### ISSUE TITLE
Module Manage page ContextErrorException Critical on 1.7.7.8 when debug ON

### ISSUE THREAD

**Issue by mikmikmik** [PrestaShop/PrestaShop#26036]
#### Describe the bug

PHP Warning:  A non-numeric value encountered in /public_html/src/Adapter/Presenter/Module/ModulePresenter.php on line 66
It causes a 500 response with 2 Critical errors and can't load the page unless I disable debug.

#### Steps to Reproduce

1. Upgrade from 1.7.7.7 to 1.7.7.8
2. Turn Debug ON
3. Visit Module Manage admin page

#### Additional information

* PrestaShop version: 1.7.7.8
* PHP version: 7.3.31

**Comment by weihan00ae** [comment]
Same error.

**Comment by maldarol** [comment]
I have this problem too

**Comment by krekken** [comment]
yep, same issue here

**Comment by hibatallahAouadni** [comment]
Hello @mikmikmik 

We are aware of this issue, it caused by the Addons API :confounded: 
And the Addons Team are working to fix it ASAP.

Thanks for your patience :pray:

**Comment by hibatallahAouadni** [comment]
Hello everyone,

Like I said, this issue is an Addons API issue and the Addons team is working on it.
Since this is not a Core bug, I should close it :confused:
Don't worry, I'll let you know as soon as this issue is resolved (here by comment).

Thank you for your understanding :pray:

**Comment by hibatallahAouadni** [comment]
Thanks @jolelievre :tada:
