### ISSUE TITLE
reduction code error

### ISSUE THREAD

**Issue by milla-dev** [PrestaShop/PrestaShop#26033]
Hello,

I have found that if I delete the "reduction code" field value and if I leave it empty, then the reduction is applied automatically on all the new orders. The idea of deleting the Reduction Code field value was that I am using the reduction codes only for the ProFormas by selecting manually a "reduction name" and not by putting the code value into the proforma. I do not share the codes to my clients neighter. As I do not share the codes, I deleted the Reduction Code values. After that all the reductions were applied to all new orders ... 

I think this is a BUG.
![reduction code field empty](https://user-images.githubusercontent.com/61284384/135415552-cd911ad6-6aa8-45a7-b431-5eb63397c84b.JPG)

**Comment by hibatallahAouadni** [comment]
Hello @milla-dev 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
