### ISSUE TITLE
Campi select non funzionanti

### ISSUE THREAD

**Issue by Kadjar2016** [PrestaShop/PrestaShop#26045]
#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @Kadjar2016,

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you!

**Comment by Kadjar2016** [comment]
> Ciao @Kadjar2016 ,
> 
> Grazie per il tuo problema. Sfortunatamente, non ci sono abbastanza informazioni fornite per riprodurlo e lavorarci sopra. È necessario seguire il modello per inviare una segnalazione di bug completa. Leggi di più su come ci aspettiamo che vengano gestiti i problemi [qui](https://build.prestashop.com/news/how-bug-reports-are-handled/) . Sentiti libero di creare un nuovo problema se puoi fornire ulteriori informazioni, saremo lieti di esaminarlo.
> 
> Grazie!

Describe the bug
I menu select nella sezione inportazione non funzionano non danno la possibilità di scelta
Expected behavior
Mi aspetto di fare clic nel menu e scegliere una tra le voci:
Categorie, Prodotti, Combinazioni, Clienti, Indirizzi, Marchi, Fornitori, Alias, Contatti negozio
2021Steps to Reproduce
Steps to reproduce the behavior:
1.	Parametri avanzati
2.	Click on Import
Additional information
•	PrestaShop version: 1.7.6.1
•	PHP version: PHP 7.4.24

Describe the bug
I menu select nella sezione inportazione non funzionano non danno la possibilità di scelta
Expected behavior
Mi aspetto di fare clic nel menu e scegliere una tra le voci:
Categorie, Prodotti, Combinazioni, Clienti, Indirizzi, Marchi, Fornitori, Alias, Contatti negozio
2021Steps to Reproduce
Steps to reproduce the behavior:
1.	Parametri avanzati
2.	Click on Import
Additional information
•	PrestaShop version: 1.7.6.1
•	PHP version: PHP 7.4.24

![IMG_3752](https://user-images.githubusercontent.com/30106580/135606101-079aa480-2c66-4f3b-afee-a34ccc46693a.jpg)

**Comment by khouloudbelguith** [comment]
Hi @Kadjar2016,

Please, send your request in English.
English is the norm on the GitHub
This issue is currently closed, can you open a new one with more information about your configuration.

Thank you!
