### ISSUE TITLE
PS 1.7.7.8 Product price_amount value get formatted value instated of without formatted value On CART CartPresenter

### ISSUE THREAD

**Issue by nishithnesdiya** [PrestaShop/PrestaShop#26059]
Hi.

I use {$product.price_amount} variable in smarty template in product and product listing page and get price of without currency formatted this is working fine.

Problem is when i use same variable  {$product.price_amount} cart and checkout smarty template then get price of with currency formatted (see image attached).

can you help me with this fix ?

![Capture](https://user-images.githubusercontent.com/12066184/135741159-74bb0a3d-8728-458b-a710-d539fee0a1f0.PNG)

Thank you

**Comment by hibatallahAouadni** [comment]
Hello @nishithnesdiya 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
