### ISSUE TITLE
Clean code for PrestaShop 1.5.3.x in AutoUpgrade Module

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#26066]
#### Is your feature request related to a problem?

There are code snippets related to PrestShop 1.5.x, the module is compatible with versions 1.6.0.x +

#### Describe the solution you'd like

Remove this code snippets related to PrestShop 1.5.x

https://github.com/PrestaShop/autoupgrade/blob/dev/views/templates/block/checklist.twig#L18

https://github.com/PrestaShop/autoupgrade/blob/dev/classes/Twig/Block/UpgradeChecklist.php#L115

And more

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

Could you please provide the links to these parts (code snippets related to PrestShop 1.5.x) :pray: 
Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by ghost** [comment]
Oups i forgot the link i update the issue : 

https://github.com/PrestaShop/autoupgrade/blob/dev/views/templates/block/checklist.twig#L18

https://github.com/PrestaShop/autoupgrade/blob/dev/classes/Twig/Block/UpgradeChecklist.php#L115

**Comment by hibatallahAouadni** [comment]
Thanks @okom3pom

**Comment by matks** [comment]
Naturally this is a good thing 👍  I confirm the code for PS 1.5 should be removed.

**Comment by ghost** [comment]
This PR fix the issue : https://github.com/PrestaShop/autoupgrade/pull/451
