### ISSUE TITLE
Footer from next invoice shown on invoice when exporting multiple invoices (i.e. invoices by date range)

### ISSUE THREAD

**Issue by AshleyButcher** [PrestaShop/PrestaShop#26067]
#### Describe the bug

When exporting multiple invoices (i.e. invoices by date range), the footer of the following invoice is shown on the current invoice erroneously. This meant that in a multi-store environment, the wrong store details could be output on the invoice footer, which can create a compliance issue, especially if different tax information should be displayed. The issue resolves around the use of TCPDF, where the footer needs to be output after AddPage, otherwise the last page of a page group will end up having the footer of the next page group.

#### Expected behaviour

The footer should be output using the correct store details.

#### Steps to Reproduce

Steps to reproduce the behaviour:

1. In a multi-store environment -- set up multiple stores with different data, such that the footers on invoices would differ depending on which store items were ordered from
2. Place and invoice a mixture of orders - switch between stores when placing orders
3. Export orders using the invoices by date range functionality
4. Where invoices switch between stores, the footer belonging to the store of the next invoice will be shown on the current invoice

I will submit a pull request with a fix.

#### Additional information

* PrestaShop version: 1.7.7.8 (although also in previous versions)
* PHP version: 7.3.29

**Comment by hibatallahAouadni** [comment]
Hello @Ashley-Butcher 

> Where invoices switch between stores, the footer belonging to the store of the next invoice will be shown on the current invoice

I reproduce the issue with PS1767, PS1778 and PS1780, see the attached screen record below:

https://watch.screencastify.com/v/LIOtU18Gxntb2uFZFGUR

I’ll add this to the debug backlog so that it’s fixed.

Thanks for your PR :superhero:
