### ISSUE TITLE
Workaround email sending error (response code 220) after upgrade to 1.7.7

### ISSUE THREAD

**Issue by CTSol186** [PrestaShop/PrestaShop#26073]
@web-plus @Lukascisar @Stampa-Stampa @JeffreyDracoon

https://danielhlavacek.cz/files/177mailfix.zip
1. Download it, extract it. 
2. Drop these files into your PS installation.
3. Profit
(optional) Let me know if it works 😄

______
PS: @Lukascisar Ahoj, zprávu na fóru jsem viděl, necháme konverzaci tady. :-D

_Originally posted by @Hlavtox in https://github.com/PrestaShop/PrestaShop/issues/22262#issuecomment-754548289_

I tried this solution on v1.7.7.8 and it didn't work for me. I tried it with both - default `sendmail` and by using custom SMTP parameters as well

**Comment by hibatallahAouadni** [comment]
Hello @CTSol186 

Could you please change the title of the issue :pray: You need to describe your problem and not just ping contributors.
PS: @Hlavtox could you please check this :pray: 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
