### ISSUE TITLE
Dysfunctional order's management with different amounts with multiple tabs

### ISSUE THREAD

**Issue by ilajili** [PrestaShop/PrestaShop#26082]
#### Describe the bug

We encounter order problems when using different tabs:
If I get to the last checkout step, open a second tab and validate the order of my first tab, Prestashop validates the second tab's order.
#### Expected behavior

The expected result would be that Prestashop manages to differentiate the contents of each tab's cart at a given time.

#### Steps to Reproduce
Here is a detailed example in order to reproduce this dysfunction:

1. Add a product n°1 with the amount of 25 € in the cart
2. Go to the last step of checkout to pay
3. Open a new tab
4. Add a new product n°2  with the amount of 10 € in the cart
5. Validate the cart of the first tab with the value of 25 €

 Result: the cart  which is validated is the one with the value of 35 € 
 Expected result: the cart with the amount of 25 € which must be validated.

We suggest a fix as follows:
Add a ps_cart_state table when we add a row each time we modify the cart (add / remove product with the opening of a new tab)
so that Prestashop manages to recognize the different contents of the shopping cart according to the tabs.

**Comment by hibatallahAouadni** [comment]
Hello @ilajili 

Thanks for reporting the issue!
Your issue seems similar to this one #24619 Could you please provide your PrestaShop version :pray: 
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @ilajili 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
