### ISSUE TITLE
Exceptions in Positions for ps_categorytree doesn't work on PS 1.7.7.8

### ISSUE THREAD

**Issue by sirius82** [PrestaShop/PrestaShop#26080]
#### Describe the bug

I wish to not display category links in the left column when the page is not category. Normally, I have just to check pages where the module doesn't be displayed in Positions -> Modify (for the choosen module) and add pages in Exceptions.
It's ok for the smartblogcategory module. But not for ps_categorytree. I compare the code in their php files and see that smartblogcategory is hooked with the classic method (public function hookDisplayLeftColumn}. But ps_categorytree is now a widget, 

#### Expected behavior

I wish to be able to create exceptions on modules like it was possible to do before to display them on selected pages (for example the category list only on category pages and not on other page with both column template). Even if they're widgets, it should be interesting to keep the same system of exceptions

#### Steps to Reproduce

1. Go to Modules -> Category links
2. Click on -> Positions
3. Click on the button to modify it
4. In Exceptions, select all pages where the module doesn't be displayed, for example blog page
5. On the front -> blog page -> the category links module is always there

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.8
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @sirius82 

Thanks for reporting the issue and for respecting the provided template!
It seems your steps are a bit confusing :sweat_smile: should I access to the page of Category Tree links (screenshot n°1) or to the page Positions and then select the module (screenshot n°2)?
![image](https://user-images.githubusercontent.com/23308427/135885340-4b28d5ea-9074-44e5-998f-096b229de656.png)

---
![image](https://user-images.githubusercontent.com/23308427/135885363-69e849f4-766b-4b0c-9aa7-ab852661cbe1.png)

Please check and feedback.
Thanks!

**Comment by sirius82** [comment]
Thanks for your reply. You can access by the both ;-) In the module configuration , at the top right of the page, the link with the anchor wich will open the Positions page just for this module.
![image](https://user-images.githubusercontent.com/11886689/135887028-aea04631-a79a-46fa-a9fb-fb08d2ea3f0f.png)

Or directly by the Positions page

**Comment by hibatallahAouadni** [comment]
Hello @sirius82 

Thanks for your answer!
Could you please provide a screenshot for this step:
> 4. In Exceptions, select all pages where the module doesn't be displayed, for example blog page

Please check and feedback.
Thanks!

**Comment by sirius82** [comment]
Of course !

![image](https://user-images.githubusercontent.com/11886689/135933148-fbc28b67-c19c-4a15-a630-6dc4cf3c1cfe.png)

All is selected except "category"

**Comment by khouloudbelguith** [comment]
Hi @sirius82,

Here's the PR to fix the issue: https://github.com/PrestaShop/PrestaShop/pull/21168
It is fixed in PS1780.
Your ticket is a duplicate of #19226
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #19226

**Comment by sirius82** [comment]
Hello, I did changes in both files like fixed in #21168 but it doesn't work : ps_categorytree is always there on all page with 2 columns even all exceptions (I let just category in core list). Cache emptied.
I remember you that it's not for all module. 
Modules with public function hookLeftColumn($params) (the classic method) follow exceptions.
But modules with  public function renderWidget($hookName = null, array $configuration = []) don't follow exceptions (as ps_categorytree but also other)

Thanks

**Comment by sirius82** [comment]
I don't think it's a duplicate of #19226 because I don't think it's a problem with a dash. There is no dash in categorytree name or other modules
