### ISSUE TITLE
Presta 1.7.6.8 Changing order status in hookActionOrderStatusUpdate  ClassNotFoundException

### ISSUE THREAD

**Issue by PasLaurent** [PrestaShop/PrestaShop#26095]
#### Describe the bug

each time i change the status of an order i get ClassNotFoundException

#### Expected behavior

No error

#### Steps to Reproduce

**Screenshots**

```
Attempted to load class "HookActionOrderStatusPostUpdate" from namespace "PrestaShop\Module\Ps_Googleanalytics\Hooks".
Did you forget a "use" statement for another namespace?
```
[500 Internal Server Error.pdf](https://github.com/PrestaShop/ps_googleanalytics/files/6490211/Attempted.to.load.class._HookActionOrderStatusPostUpdate_.from.namespace._PrestaShop_Module_Ps_Googleanalytics_Hooks_.Did.you.forget.a._use_.statement.for.another.namespace_.500.Internal.Server.Error.pdf)

```
ClassNotFoundException
in modules/ps_googleanalytics/ps_googleanalytics.php (line 184)
/**     
* Hook called after order status change, used to "refund" order after cancelling it     
* */    
public function hookActionOrderStatusPostUpdate($params)    
{       
$hook = new PrestaShop\Module\Ps_Googleanalytics\Hooks\HookActionOrderStatusPostUpdate($this, $this->context);        $hook->setParams($params);        $
hook->run();    
}   
[Attempted to load class _HookActionOrderStatusPostUpdate_ from namespace _PrestaShop_Module_Ps_Googleanalytics_Hooks_. Did you forget a _use_ statement for another namespace_ (500 Internal Server Error).pdf](https://github.com/PrestaShop/ps_googleanalytics/files/6490206/Attempted.to.load.class._HookActionOrderStatusPostUpdate_.from.namespace._PrestaShop_Module_Ps_Googleanalytics_Hooks_.Did.you.forget.a._use_.statement.for.another.namespace_.500.Internal.Server.Error.pdf)

Ps_Googleanalytics->hookActionOrderStatusPostUpdate(array('newOrderStatus' => object(OrderState), 'id_order' => 6, 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 3))
in classes/Hook.php (line 970)
```

#### Additional information

* PrestaShop version: 1.7.6.8
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @PasLaurent 

I just edit your issue description, so could you please provide steps to reproduce.
Cause with the provided infos, I didn't manage to reproduce the issue.
Did you override the module?
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @PasLaurent 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
