### ISSUE TITLE
In some case GoogleAnalyticEnhancedECommerce is not defined

### ISSUE THREAD

**Issue by camlafit** [PrestaShop/PrestaShop#26093]
#### Describe the bug

On some case GoogleAnalyticEnhancedECommerce javascript variable is undefined. In this case we could get an 
Uncaught ReferenceError, this error once raised any javascript execution following can't be execute (as popin validation on add to cart).
This behavior occurs at least on category and product page 

#### Expected behavior

Could be nice to check this variable before to use.

#### Steps to Reproduce

1. Enable ps_googleanalytics module
2. Configure UA tracking code 
3. Go to public website (at least any product or category pages)
4. Open javascript debugger and see screenshot

**Screenshots**

![2021-09-01_11-33](https://user-images.githubusercontent.com/209915/131648801-92cf578e-bd99-4b8e-a6ff-b64618d77b23.png)

---
![2021-09-01_11-32](https://user-images.githubusercontent.com/209915/131648804-96290953-a0f9-448c-b6cc-77ecc962a241.png)

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: N/A
* Google Analytics: v4.1.0
* ZOne Theme: 2.5.7

**Comment by hibatallahAouadni** [comment]
Hello @camlafit 

I just edit your issue description, so could you please provide steps to reproduce the issue.
Cause with provided infos, I didn't manage to reproduce the issue with PS1778, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/136194853-7d73335d-831d-48ca-bff3-2a6d9dbfebaa.png)

Please check and feedback.
Thanks!

**Comment by camlafit** [comment]
Hello

In my case, steps look relative simple, enable googleanalytics module,  set UA value and go to public site.
![2021-10-07_08-39](https://user-images.githubusercontent.com/209915/136332616-28509e50-9273-4c6d-9940-bd8d118341ab.png)

Actually up to 1.7.7.8 version.

To prevent this behavior I've proposed a PR https://github.com/PrestaShop/ps_googleanalytics/pull/99

This error looks easy to fix, check before GoogleAnalyticEnhancedECommerce content in javascript.


Thanks

**Comment by khouloudbelguith** [comment]
Hi @camlafit,

In my case also, I did not manage to reproduce the issue with PS1780 and ps_googleanalytics v4.1.0
I attached a screen record
https://watch.screencastify.com/v/GaydVVOXNyNV34wgnXIf

Thanks to check and feedback.

**Comment by camlafit** [comment]
Hello

I'll try to reproduce on my production and do screencast.

**Comment by hibatallahAouadni** [comment]
@camlafit ok, waiting for your feedback.

**Comment by hibatallahAouadni** [comment]
Hello @camlafit 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by camlafit** [comment]
Hello

I confirm always this problem.
I don't understand why close this issue and its solution as we have any regression with this patch.

**Comment by SviniamociBR** [comment]
Salve, abbiamo un problema con google analytics non vediamo più gli aggiornamenti alle visite del nostro sito. 
Il problema e che abbiamo un ID "G-".
Vorremmo che la piattaforma supportasse le proprietà Google Analytics 4 tramite il più recente tag globale del sito di Google . https://developers.google.com/analytics/devguides/migration/ua/analyticsjs-to-gtagjs
Come possiamo risolvere il problema?

**Comment by camlafit** [comment]
Ciao @SviniamociBR 

Deve aprire un altra issue. Questo problema non è collegata a questa discussione.
Penso che sia direttamente ad aprire sul progetto https://github.com/PrestaShop/ps_googleanalytics/
