### ISSUE TITLE
Prestashop 1.7.6.3 stream Google A doesn't work after I put my Analytics ID

### ISSUE THREAD

**Issue by Speedy1010** [PrestaShop/PrestaShop#26091]
#### Describe the bug

stream doesn't work after i put my Analytics ID in Google Analytics free Prestashop module, I tried everything, can anyone help me?

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

![image](https://user-images.githubusercontent.com/23308427/136189682-e3fe7397-c264-4b65-9e6f-9755ff9f1dbe.png)

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: N/A

**Comment by alfonsolr09** [comment]
what do you mean? To me, works perfectly

**Comment by hibatallahAouadni** [comment]
Hello @Speedy1010 

I just edit your issue description, could you please complete the exepected behavior, steps to reproduce and provide your PHP version, GoogleAnalytics version.
Please check and feedback.

PS: thanks @alfonsolr09 for your quick reply :rocket: 

Thanks!

**Comment by Speedy1010** [comment]
hi, thanks for reply
I activated the plugin, insert analytics ID and google have 0 info about visitors
now, when i activate analytics module, i've got this error in my website

https://i.ibb.co/WpqQXvX/analyt-1.png

**Comment by alfonsolr09** [comment]
Have you try to delete and install the module?

**Comment by Speedy1010** [comment]
deleted and reinstalled
id analytics added as you can see
https://i.ibb.co/Qvrr4ds/analyt.png

but also in "real time" on analytics i can't see hits

**Comment by florine2623** [comment]
@Speedy1010 ,

Please answer @hibatallahAouadni  about :
> provide your PHP version, GoogleAnalytics version.

Please check and feedback

**Comment by Speedy1010** [comment]
PHP 7.3.31
Prestashop: 1.7.6.3

**Comment by Speedy1010** [comment]
v.4.1.0 google analytics module
downloaded from module catalog from prestashop

**Comment by florine2623** [comment]
PrestaShop 1.7.6.3 is not compatible with PHP 7.3. You should downgrade your PHP version to 7.2.
Please check the devdocs : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Please check and feedback

**Comment by Speedy1010** [comment]
ok i changed to 7.2.34
still analytics don't receive hits

**Comment by hibatallahAouadni** [comment]
Hello @Speedy1010 

I didn't manage to reproduce the issue with PS1764 and Google Analytics v4.1.0 :confused: 
Did you override the module cause we don't have the same Settings, check the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/137178568-02b132cd-7c69-4f58-b9d0-6bba00e96dd4.png)

Please check and feedback.
Thanks!

**Comment by Speedy1010** [comment]
![analy](https://user-images.githubusercontent.com/91664932/137263819-fe88cd37-56a9-4c63-be94-ca4b357c3c92.png)
Same settings and no hits on my analytics

**Comment by hibatallahAouadni** [comment]
Hello @Speedy1010 

Did you check your Google Analytics configuration? Could you please provide a screenshot of your analytics.google.com/analytics/web :pray: 
Please check and feedback.

Thanks!

**Comment by Speedy1010** [comment]
![11an](https://user-images.githubusercontent.com/91664932/137449376-679afe40-02e1-4a5a-8a19-901bab49364e.png)
![12an](https://user-images.githubusercontent.com/91664932/137449382-2aa044c8-e284-4b26-b8fa-f3abd7b94471.png)
here you are

**Comment by khouloudbelguith** [comment]
Hi @Speedy1010,

I did not manage to reproduce the issue with PS1777 using the ps_googleanalytics module v4.1.0.
![image](https://user-images.githubusercontent.com/16067358/137478723-dd95216e-5f19-4695-b72a-a94721400c4e.png)
I attached a screen record
https://watch.screencastify.com/v/ZAAA55sEYoMHBjMGgLem

Thanks to check and feedback.

**Comment by Speedy1010** [comment]
so how can i solve my problem?
your analytics ID starts with UA-XXX and ended with -1
My analytics ID is: G-FJXXXXXXXW

can it be wrong?

**Comment by khouloudbelguith** [comment]
@Speedy1010, I just followed this document: https://support.google.com/analytics/answer/1008015 to create ID.

Thanks!

**Comment by Speedy1010** [comment]
![analqwe](https://user-images.githubusercontent.com/91664932/137518941-0f9ba939-5c79-493f-bc23-9f0c666e2c66.png)
i followed the same guide
created now a new one but same problem

**Comment by khouloudbelguith** [comment]
@Speedy1010, I updated the information of my shop on this page
![image](https://user-images.githubusercontent.com/16067358/137519526-1161957c-cf22-484b-b177-59018757a7f9.png)

Thanks!

**Comment by Speedy1010** [comment]
![analyty](https://user-images.githubusercontent.com/91664932/137520102-233a7d98-cecf-4918-aae5-e8c79ba80316.png)
different settings
i can't add other info

**Comment by hibatallahAouadni** [comment]
Hello @Speedy1010 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a module problem.

We will close this issue.

Thanks!

**Comment by zorrobiwan** [comment]
@Speedy1010 you have generated a Google analytics 4 ID which is not compatible with the free Google Analytics PrestaShop module.
Choose a paid module compatible with GA4 or use a Google Universal Analytics ID or wait for a free compatible module.
