### ISSUE TITLE
is this module GA4 compatible?

### ISSUE THREAD

**Issue by KrzysztofWWW** [PrestaShop/PrestaShop#26096]
Hi,
I've tried using this module with Google Analytics 4. After few days I noticed no ecommerce events are registered. I see that module is still using analytics.js method.
So, is there a way I could use it for registering ecommerce events or should I just move to some paid modules?

**Comment by hibatallahAouadni** [comment]
Hello @KrzysztofWWW 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by matks** [comment]
@KrzysztofWWW Release 4.2.0 of module ps_googleanalytics should provide GA4 support

https://github.com/PrestaShop/ps_googleanalytics/pull/131
