### ISSUE TITLE
Error 1871 PS 1.7.7.7 PHP 7.3

### ISSUE THREAD

**Issue by RicRey1988** [PrestaShop/PrestaShop#26090]
#### Describe the bug

When trying to translate a Template other than the classic one, it causes error 1871

#### Expected behavior

That the selected template can be translated

#### Steps to Reproduce

1. Go to 'International'
2. Click on 'Translate'
3. Select Translate Template
4. Select template
5. select edit

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
![image](https://user-images.githubusercontent.com/44790517/135955232-593dcdef-0fcb-4494-9d87-731fb8ef60c5.png)
![image](https://user-images.githubusercontent.com/44790517/135955271-0972a9c9-8077-4781-a260-d745eb985839.png)

#### Additional information

* PrestaShop version: 1.7.7.7
* PHP version: 7.3

**Comment by florine2623** [comment]
Hello @RicRey1988 ,

I can't reproduce your issue with classic template on PS 1.7.7.7. 
Please check my screen record : https://watch.screencastify.com/v/4vkSSTDVvezEZGSF50zj
I suggest contacting the developer of your template directly, so they can fix the issue.

Thanks
