### ISSUE TITLE
Not tracking all orders

### ISSUE THREAD

**Issue by kdegenkamp** [PrestaShop/PrestaShop#26094]
I am getting issue that order confirmation page is not being visited by customer and analytics code is not being fired.

**Comment by hibatallahAouadni** [comment]
Hello @kdegenkamp 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
