### ISSUE TITLE
Uncaught ReferenceError: ArrayMBG is not defined - on shipping method checkout step

### ISSUE THREAD

**Issue by jaxtheking** [PrestaShop/PrestaShop#26097]
Hi, 
We're getting a JS error after progressing from the Addresses step to the Shipping Methods step in the checkout. All works before then and the error persists up to the Payment step.

The root of the issue seems to be line 74 of classes/Hook/HookDisplayFooter.php: `$gaScripts .= $gacart;`
Before the Shipping step, the $gacart variable contains a flat array:
```
Array
(
    [0] => MBG.addCheckoutOption(2,'International Shipping');
)
```

After moving to the Shipping step, the $gacart variable contains a multidimensional array:
```
Array
(
    [0] => Array
        (
            [0] => MBG.addCheckoutOption(2,'International Shipping');
        )
)
```
Which results in the following JS code being printed:
```
var MBG = GoogleAnalyticEnhancedECommerce;
MBG.setCurrency('EUR');
ArrayMBG.addCheckout('0');
```

Not sure if the problem originates from GanalyticsDataHandler... any thoughts?
Thanks,
Luca

**Comment by khouloudbelguith** [comment]
Hi @jaxtheking,

Sorry for the delay.
Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). 

Thanks to update you first comment.

**Comment by hibatallahAouadni** [comment]
Hello @jaxtheking 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
