### ISSUE TITLE
Same web property ID is tracked twice - in FO Checkout page

### ISSUE THREAD

**Issue by Daaaaad** [PrestaShop/PrestaShop#26099]
Hello, 

With the current version of ps_googleanalytics (v4.0.0) the "pageview" event is sent twice on the cart page, causing a "Same web property ID is tracked twice" error in Google Tag Assistant Chrome extension... and potentially inconsistent data in Google Analytics 😔

First event submission: https://github.com/PrestaShop/ps_googleanalytics/blob/d64569e80e1de4b579206b930490a8dcb020ed58/views/templates/hook/ps_googleanalytics.tpl#L50

Second submission: 
https://github.com/PrestaShop/ps_googleanalytics/blob/d64569e80e1de4b579206b930490a8dcb020ed58/views/js/GoogleAnalyticActionLib.js#L170

Regards,

David.

**Comment by khouloudbelguith** [comment]
Hi @Daaaaad,

Sorry for the delay.
What is the exact version PrestaShop did you use?

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Daaaaad 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
