### ISSUE TITLE
Stripe orders not tracking  

### ISSUE THREAD

**Issue by Thread10** [PrestaShop/PrestaShop#26092]
Hello there
For a few weeks now, all orders that are paid with stripe have not been registered by analytics in the e-commerce tab. This is a big problem, since google ads campaigns and their performance depend on this data.

**Comment by hibatallahAouadni** [comment]
Hello @Thread10 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: please open a new issue in PrestaShop repo not in GoogleAnalytics repo, and don't forget to follow the provided template to submit a complete bug report :wink: 

Thanks for your understanding :pray:
