### ISSUE TITLE
Prices hidden from visitors but visible in the source code of the page because of module

### ISSUE THREAD

**Issue by diegoparoni** [PrestaShop/PrestaShop#26107]
The module does not check if prices are hidden from visitors and publishes the price in the source code of the page:
<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', function() {
    var MBG = GoogleAnalyticEnhancedECommerce;
    MBG.setCurrency('EUR');
    MBG.add({"id":"20",.(...) "price":"2,95\u00a0\u20ac"},'',true);
  });
</script>

**Comment by hibatallahAouadni** [comment]
Hello @diegoparoni 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
