### ISSUE TITLE
In French, the Module Configuration page has bad text overlap with icon

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#26103]
#### Describe the bug

GoogleAnalytics configuration page has bad text overlap with icon (in French or any other language when the text is too long)

#### Expected behavior

No overlapping

#### Steps to Reproduce

1. BO > Modules > Module Manager
2. Click on **Configure** button of Google Analytics
3. See error => if the text is long, it will overlap the photo

**Screenshots**

![Capture d’écran 2020-08-27 à 16 09 25](https://user-images.githubusercontent.com/3830050/91453409-f826bb80-e87f-11ea-9b70-516efa25764b.png)

#### Additional information

* PrestaShop version: 1.7.7.8
* Google Analytics: v4.1.0
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @matks 

Thanks for reporting the issue!
I reproduce the issue with PS1767, PS1778, PS1780 and with GoogleAnalytics v4.1.0.
I’ll add this to the debug backlog so that it’s fixed.

Thank you
