### ISSUE TITLE
Missing product related data (price, etc) in GA if customer leaves before the end of order confirmation page

### ISSUE THREAD

**Issue by Daaaaad** [PrestaShop/PrestaShop#26101]
Hello,

I noticed something annoying : If the customer place an order but don't wait until the end of the loading of the confirmation page (this process can take up to 10-20 seconds if it waits for the async request of a payment processor) product data will be missing in GA.

In this case, that's the HookDisplayBackOfficeHeader that will in charge of sending information to GA but only the transaction (without products) will be sent.

Can you help?

Regards,

David.

**Comment by hibatallahAouadni** [comment]
Hello @Daaaaad 

Sorry for the late response :pray: 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
