### ISSUE TITLE
TVA sur la marge

### ISSUE THREAD

**Issue by www-ROUTE66-store** [PrestaShop/PrestaShop#26108]
#### Describe the bug
URGENT
Merci d'aller ergarder ce post
https://www.prestashop.com/forums/topic/1035690-tva-sur-marge-en-france/

#### Expected behavior

Explain what you expected to happen instead.
TVA sur marge à calculer

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information
Prestashop 1.7.... (last version)
* PrestaShop version: N/A
* PHP version: N/A

**Comment by florine2623** [comment]
Hello,

I will close your issue as it does not follow the bug report template.
Please create another another issue in English and fill all the required fields.

Thanks
