### ISSUE TITLE
Migrate to gtag.js

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#26100]
#### Is your feature request related to a problem?

It seems that google recommend now gtag.js instead of analytics.js :
https://developers.google.com/analytics/devguides/collection/gtagjs

#### Describe the solution you'd like

Migrate to gtag.js

#### Alternatives you've considered

- Basic code in header
https://developers.google.com/analytics/devguides/collection/ga4

- General events for our purposes - login, search, share, sign_up
https://support.google.com/analytics/answer/9267735

- Ecommerce events - all of them
https://developers.google.com/analytics/devguides/collection/ga4/ecommerce

**Comment by hibatallahAouadni** [comment]
Hello @jf-viguier 

Thank you for your suggestion. The Developer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by dlyr** [comment]
I'm also interested in this feature, and I may make a proposal in upcoming weeks
But it will be easier for me to do so for gtag only (keeping both type of data would rather add alot of code, and I'm really new to module dev).
Might be a fork/other module ? or could you guide how to manage ga and gtag compatibility without performance issue and big ifs everywhere ?

**Comment by jf-viguier** [comment]
@dlyr maybe a new module started from scratch should be good. Thnks for you future work.
