### ISSUE TITLE
The "coupon" field is not set for the GA event

### ISSUE THREAD

**Issue by GuillaumeLazar** [PrestaShop/PrestaShop#26105]
Hello, 
I guess that the "coupon" field of GA purchase event is not set.
I think that for a Prestashop v1.7.x, we should get the code string from "$order->getCartRules()[0].code".

**Comment by hibatallahAouadni** [comment]
Hello @GuillaumeLazar 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
