### ISSUE TITLE
v4.0.0 missing option to switch from net prices to gross prices

### ISSUE THREAD

**Issue by icemansparks** [PrestaShop/PrestaShop#26104]
Currently the submitted value to google analytics always contains the net price value for a product. 
Is there any possibility for a switch so that always the product gross price is submitted instead?

**Comment by hibatallahAouadni** [comment]
Hello @icemansparks 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

PS: thanks @matks & @Hlavtox for your quick replies :rocket: 

Thank you
