### ISSUE TITLE
Ghost cart and wrong quantities in front office if cart deleted in BO

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#26119]
I discovered an important issue with one of my big clients, when deleting abandoned carts. Users see wrong quantities in front office if going back to the store.

#### Steps to Reproduce

1. Create products A and B, assign quantity 10 to both of them, disable ordering when out of stock.
2. Add 10 of product A to cart.
3. Go to backoffice and delete your user's cart (imagine it has been abandoned for a month, so you delete it).
4. Go back to front office and browse the store and see, that you cannot order product A and it looks like it's not in stock. You cannot see it in your cart also.
5. Everything starts working when you add product B to cart.

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

I didn't manage to reproduce the issue with PS1778 and PS1767, see the attached screen record below:

https://watch.screencastify.com/v/3DL1AhhPnxv4safCkOfc

Please check and feedback.
Thanks!

**Comment by Hlavtox** [comment]
@hibatallahAouadni Sorry for wasting your time, I think it's shop specific. :(

**Comment by hibatallahAouadni** [comment]
@Hlavtox no problem :relaxed:
