### ISSUE TITLE
Replace a die() with an Exception on _PS_MODE_DEV_

### ISSUE THREAD

**Issue by SebSept** [PrestaShop/PrestaShop#26113]
Here : 
https://github.com/PrestaShop/PrestaShop/blob/c4e488fa51aff3c42cf0077e5ed34df5380b943e/classes/module/Module.php#L1170
We have a die() not very useful because it can happen when there $module_name is empty.
It's really more developer friendly to have a stack trace, using an exception.

**Comment by florine2623** [comment]
Hello @SebSept ,

Thank you for your suggestion. The Developer Team will take it into consideration for future developments. 
And thanks for the PR.

Thank you
