### ISSUE TITLE
Big problem with all addons themes with the addresses saved from checkout

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#26117]
Hi

there is a problem with all themes bought from addons from prestashop 1.7.7.8, and I think because these themes do not follow the updates made to the classic theme.
then there is to consider that many do not update the themes because the support period ends.
however I have seen that this error can really create problems in the purchase phase.

this bug is not present into classic theme, but I hope you can give me some infos to fix this problem, because I need to fix it into 30 websites, and other developers need to do the same thing.

the problem happens only in the checkout page not in the address page of customer account

#### Describe the bug

in the checkout page, push on the "edit" button to edit an existing address, the push on the "continue" button (it is not necessary to change something to reproduce this error), after return to the address tab and you will see two addresses.

if I do the tests using an addons theme with prestashop 1.7.6.x all is ok.

#### Expected behavior

the behavior should be the same on 1.7.6.x with a addons theme and on the classic theme also with 1.7.7.x
the address saved from the checkout page should have the same behavior present in the customer account of addresses block

#### Steps to Reproduce

1. use a different theme from classic theme, take one of addons theme
2. prestashop 1.7.7.x
3. add a product into the cart
4. go in the checkout page and do the loggin
5. add an address if not present one
6. edit an address
7. push on the "continue" or "save" button present at the end of this address form
8. at this moment you will be into the shipping step, so return into the previous step, so go into the address step
9. now you will see the presence of 2 addresses

**Video**
I made a video to show this error
https://watch.screencastify.com/v/dgvseBm4Mitj1AEpPfu2

#### Additional information

* PrestaShop version: 1.7.7.8
* PHP version: 7.3

the classic theme on prestashop 1.7.7.8 has no problems, so into the classic theme there is a fix, I think in the javascript code.

can you help me to understand how to fix all addons themes on 1.7.7.x?

thanks

**Comment by hibatallahAouadni** [comment]
Hello @maofree 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #23808. 
And it's already fixed by this PR #24920

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #23808

**Comment by Maofree** [comment]
thanks @hibatallahAouadni 

bye
