### ISSUE TITLE
Tax amount become zero while applied cart rule of amount equal to cart sub total amount

### ISSUE THREAD

**Issue by humanyu** [PrestaShop/PrestaShop#26125]
Hello Everyone,

for example- 

Cart sub total- $100.00
Tax- $18.00
Cart Total $118.00

if I am applied a coupon of amount $100 then 
Cart sub total- $100.00
Discount- $100.00
Tax- 0.00
Cart Total $0.00

so tax is going to zero while applied a coupon amount equal to cart sub total amount.
** tax is applying after coupon applied 

Thank you

**Comment by hibatallahAouadni** [comment]
Hello @humanyu 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **Please respect and  follow the provided template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
