### ISSUE TITLE
Module catalog doesn't work on PS 1.7.8

### ISSUE THREAD

**Issue by antonioNKT** [PrestaShop/PrestaShop#26123]
#### Describe the bug

In a fresh/new install, I can't access to "admin" site, so I take off the multiview module on .htaccess and I can login in the admin page / backoffice. But the module catalog doesn't work. Actually I can't even upload a module on my own.

Tried on 1.7.7 and works perfectly.

![Captura de pantalla de 2021-10-06 10-55-05](https://user-images.githubusercontent.com/72248688/136171783-1114082d-aa3e-4cf4-b0c1-0e38a1339c71.png)

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: 7.4

**Comment by hibatallahAouadni** [comment]
Hello @antonioNKT 

I didn't manage to reproduce your issue with PS1780_rc1.
Could you please provide a screenshot of your console :pray: 
Please check and feedback.

Thanks!

**Comment by antonioNKT** [comment]
Hello @hibatallahAouadni 

My console? You mean this? 

![Captura de pantalla de 2021-10-06 12-43-22](https://user-images.githubusercontent.com/72248688/136191846-509056e4-c8d8-469c-9882-3f8f33daf29a.png)

**Comment by khouloudbelguith** [comment]
Hi @antonioNKT,

We are awre of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #26028
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #26028
