### ISSUE TITLE
How to apply coupon on shipping fee?

### ISSUE THREAD

**Issue by humanyu** [PrestaShop/PrestaShop#26121]
I am trying to use wallet amount to purchase order, so I am creating a coupon code and applying on cart. but cart rule is not applied on shipping fee.

**Comment by okom3pom** [comment]
This is not a bug report.

For this question you can ask on :

https://www.prestashop.com/forums/
https://stackoverflow.com/questions/tagged/prestashop
https://www.prestashop-project.org/slack/

Regards

**Comment by hibatallahAouadni** [comment]
Hello @humanyu 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: thanks @okom3pom for your quick reply :superhero: 

Thanks!
