### ISSUE TITLE
Price rounding + vat still not correct

### ISSUE THREAD

**Issue by loetje88** [PrestaShop/PrestaShop#26127]
#### Describe the bug

Wrong total price is calculated if prices are ex. vat.

#### Expected behavior

Show the right prices.
For example :

Product of E 3.25 inc. vat = 2,6859 excl. vat -> this can be rounded to 2.69
60 x 2,69 = a total ex vat of E 161.40 , but prestashop calculates only 161.14 - where there is an income loss of almost 0.40ct!!!

#### Steps to Reproduce

1. Go to any product after shop is set to show excl. vat prices
2. Click on any product to see price in shopping cart and see that price is off

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: 7.3.31
![nl2](https://user-images.githubusercontent.com/31586907/136191525-26527257-15ca-4d39-963c-89f292b9076a.png)
![nl1](https://user-images.githubusercontent.com/31586907/136191529-808fe9ca-cf6f-4fe1-8228-7e4c9e2fbeb8.png)

**Comment by Hlavtox** [comment]
@loetje88 What is a precise tax excluded price of the product in backoffice?

**Comment by loetje88** [comment]
@Hlavtox , in reference with above example for the price of E 2.69 :

Nornaly customers buy incl VAT, but the error triggered me on an order from a belgium customer which is a reverse vat order (so ex vat, so i will start with incl. vat price first (this would be the field i fill in)

incl. vat (21%) : 3.25
excl vat : 2,685950

Again, 2,685950 could be round up to 2.69 (the price listed front office).

![nl3](https://user-images.githubusercontent.com/31586907/136192848-39423374-eb66-4a73-81f4-05c50f5937fb.png)

**Comment by Hlavtox** [comment]
2,685951 x 60 = 161,15706 = 161,16

**Comment by loetje88** [comment]
@Hlavtox  Yes,

But the price listed and shown is not 2.685951 , but 2.69 (see shopping cart and product page screenshot).
2.69 x 60 = 161.40

If i enter 2.69 as ex vat in backoffice, the price incl vat is wrong -> 3.26 in stead of 3.25 and too high, see below screenshot.

**Comment by loetje88** [comment]
@Hlavtox  see attached screenshot.

No matter is prices are entered in or ex vat - price calculation and rounding is still wrong.

3.25 x 60 (fro a price of 2.69 ex vat as it should be) = E 195 -> not E 195.29 in total
![nl5](https://user-images.githubusercontent.com/31586907/136193637-f73e9446-a348-4a2b-bbdc-ea41f9ef33a5.png)

**Comment by loetje88** [comment]
And just to be sure, a screenshot for the VAT settings 
- round up when above half (recommended)
- Round up on each rule 

* Also tried : Round up to closest value (causes product prices to be off , for example 3.26 in stead off 3.25 and still wrong calculation on ex vat prices for the product)
* Round each item (causes a wrong total vat)

![nl5](https://user-images.githubusercontent.com/31586907/136194346-98e4636d-264c-4646-a633-49c7e6e21347.png)

**Comment by loetje88** [comment]
Gathered from ps_currency :

![nl6](https://user-images.githubusercontent.com/31586907/136194375-c675b9c1-9d3d-417b-91c1-891356f16d98.png)

**Comment by Hlavtox** [comment]
@loetje88 So what would you want to happen? How would you like to enter and save the prices?

**Comment by loetje88** [comment]
@Hlavtox  preferably, in my case i would like to enter the prices vat inc. in the backoffice.
But in the end, i dont think one should exclude the other - prices are shown wrong either way.

I would go with saying it should just give the right price - so if the systems thinks 2.685951 should be dusplayed front office as 2.69 , it would need to calculate with that as well.
And at this moment, that is not the case :)

**Comment by Hlavtox** [comment]
@loetje88 Prices need to be saved with taxes excluded, this is how its done in all ecommerce systems.

You can display it with how many decimal places you want, but it won't be precise. In your usecase, maybe you can modify Prestashop so it rounds the tax_excl price before calculating, then you will get 2,69 x 60 = 161,4. 👍

**Comment by hibatallahAouadni** [comment]
Hello @loetje88 

We have an EPIC about all rounding issue #19445 could you please check it, you may find a duplicate of your issue.
Thanks @Hlavtox for your quick replies :superhero: 

Thanks!

**Comment by loetje88** [comment]
@hibatallahAouadni

Just checked, and i cant see any duplication of my error, just an error that can be added to that list.

**Comment by loetje88** [comment]
@Hlavtox

Putting that that is how it works in every ecommerce, it a bit overrated.
If i enter my prices inc vat in wordpress, i have no problem.

It has been a while, but i think i remeber that this was the same when we tested magento.

And, i have fairly tried almost every saas software before turning to CMS, and have had no problems entering prices in or ex vat and rounding.

Even here on github for previous version can be read that it was an issue and is NOT how it should work.

**Comment by raidnet-ms** [comment]
same problem here

**Comment by khouloudbelguith** [comment]
Hi @loetje88,

Thanks for your clarifications.
In fact, the problem of rounding is explained in this ticket: https://github.com/PrestaShop/PrestaShop/issues/17161#issue-549457949
Thanks to check the issue.

**Comment by hibatallahAouadni** [comment]
Hello @loetje88 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #17161. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #17161
