### ISSUE TITLE
Autoupgrade - Autoupgrade to develop is not possible

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#26136]
#### Describe the bug
There is an error during the autoupgrade to the 8.0.0.

#### Expected behavior

Autoupgrade to develop is possible with no error.

#### Steps to Reproduce

1. Create a release 8.0.0 using (php tools/build/CreateRelease.php) from develop branch
2. Install autoupgrade module in version 1.7.8.x 
3. upgrade the version 1.7.8.0RC/1.7.8.1/1.7.7.8  to 8.0.0 using local archive

**Screenshots**
![Capture d’écran de 2021-10-07 10-08-38](https://user-images.githubusercontent.com/89604350/136354945-67e4c77f-ec0a-40d6-9a19-b49481447147.png)

#### Additional information

* PrestaShop version: develop 
* PHP version: 7.3

**Comment by atomiix** [comment]
Hi @marwachelly, this issue is caused by the module `ps_facebook` which is not compatible with the develop branch yet. Also, `ps_checkout` & `ps_metrics` have issues with the develop branch too.
To try the upgrade, delete those 3 modules before starting the upgrade process and it should be ok.

**Comment by marwachelly** [comment]
Hi @atomiix ,
You are right, the upgrade to develop works fine when deleting those 3 modules. It is not a core issue. So i will close the issue .
Many thanks,

**Comment by Vinceveve** [comment]
Hi @atomiix do you know what are the issues for this three modules ? 
(or do you have bug report)

**Comment by atomiix** [comment]
Hey @Vinceveve, I think that for ps_facebook & ps_checkout the issue is that some services are not declared "public" but used without dependency injection which is something now required by symfony 4.4. For ps_metrics the problem comes from the fact that it uses guzzle 5 but develop is now using guzzle 7.

**Comment by Vinceveve** [comment]
Thank you @atomiix ! For `public` services it's gonna be an easy fix.

For Guzzle 7 the tough part will be to keep modules working on older PrestaShop's versions.
Do you have a plan to keep compatibility for modules using Guzzle ? 
API are close with Guzzle 5 but it's still risky to work with Guzzle 5 like it was Guzzle 7

**Comment by atomiix** [comment]
@Vinceveve as of today, there is no plan to keep compatibility for modules using Guzzle 5. Modules will have to check Guzzle/PrestaShop version and use the right method according to it.
