### ISSUE TITLE
BO invoice counters are wrongly displayed in "All shops" context

### ISSUE THREAD

**Issue by gennaris** [PrestaShop/PrestaShop#26137]
( Note: I am opening this issue as requested by @PierreRambaud - A fix for this had already been made in my PR #24120 )

#### Describe the bug
Backoffice invoices counters are displayed only for one shop when using multishop in "All shops" context

#### Expected behavior

I would expect to see counters considering invoices from all shops. 

#### Steps to Reproduce

1. Enable multishop with two shops (shop1 / shop2)
2. Complete two orders, one in shop1 - one in shop2 and change their order status to "Payment accepted" to trigger invoice generation
3. Switch to "All shops" context and go to Orders > Invoice
4. See only "1" invoice is displayed in "payment accepted" instead of 2 - PDF export routine is correctly export both invoices , though

**Screenshots**

![2021-10-07_12-13-33](https://user-images.githubusercontent.com/43071148/136365471-add07875-3787-43d5-8c5c-bd7e7df60924.png)

#### Additional information

* PrestaShop version: 1.7.7.8
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @gennaris 

I reproduce the issue with PS1767, PS1778 and PS1780 (even with develop).
The invoice page display only the invoices belong to the first (default) shop. I’ll add this to the debug backlog so that it’s fixed.

Thanks for your PR :rocket:
