### ISSUE TITLE
Update passwords in md5 to bcrypt

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#26134]
#### Is your feature request related to a problem?

Although customer passwords are normally encrypted using bcrypt, PrestaShop still supports passwords stored in md5 in previous releases.

#### Describe the solution you'd like

PrestaShop should upgrade the customer's password to bcrypt automatically when they successfully log in and their password is encrypted in md5.

**Comment by PierreRambaud** [comment]
My bad #6319 already does the job. I don't know how I thought it wasn't working. Maybe something I badly test :sweat_smile: 
Anyway, the password is automatically updated if the user sign in :) 

I'm closing the issue and remove it from the project.
