### ISSUE TITLE
Settings are shown twice in the BO

### ISSUE THREAD

**Issue by deepindersingh83** [PrestaShop/PrestaShop#26135]
#### Describe the bug

Some menu option are shown twice in the BO 

For example add new product and Help in Products section

![image](https://user-images.githubusercontent.com/568596/136354009-3082b766-5ba1-4536-ab36-84467e1e1236.png)
If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.3

**Comment by deepindersingh83** [comment]
Classes that produce the issue at BO products page 

class="btn btn-floating-item pointer"
class="btn btn-primary pointer"

**Comment by hibatallahAouadni** [comment]
Hello @deepindersingh83 

I didn't manage to reproduce your issue with PS1780 (fresh install), see the attached screenshot belowl:

![image](https://user-images.githubusercontent.com/23308427/136362416-80f7d7ff-9720-444a-9f88-d7eacdb3d8a3.png)

But it seems you need to clear your cache, could you please access to Performance page and follow these settings:

![image](https://user-images.githubusercontent.com/23308427/136362526-864720be-ddc0-4d0b-b91e-fdc47cbd9435.png)

Did you upgrade your shop to 1780 or it's fresh install? if you upgraded your shop, could you please provide your previous version :pray: 
Please check and feedback.

Thanks!

**Comment by deepindersingh83** [comment]
@hibatallahAouadn upgraded from 1.7.7.8.

Cache cleared but issue still persist

**Comment by khouloudbelguith** [comment]
Hi @deepindersingh83,

I did not manage also to reproduce the issue after an upgrade to PS1780 after an upgrade from PS1778 and after an upgrade from PS1777.
![image](https://user-images.githubusercontent.com/16067358/136555287-90a030be-1548-4db5-bc29-9d03c3312a23.png)
try to open your shop in an incognito browser.
You need to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.
Thanks to check and feedback.

**Comment by hibatallahAouadni** [comment]
Hello @deepindersingh83 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
