### ISSUE TITLE
Testing email + Mail:send function

### ISSUE THREAD

**Issue by pouzarm** [PrestaShop/PrestaShop#26130]
#### Describe the bug

- Testing email in administration not sending (response is 500).
- `Mail::send` function in custom module returns false (in xdebug - same error like in testing email)

#### Expected behavior

- Send an email (not return 500 in administration response and not returning false on `Mail::send` function).

#### Steps to Reproduce

1. Go to administration
2. Try to send testing email from email section

> index.php/configure/advanced/emails/

4. See error in network

**Screenshots**

![image](https://user-images.githubusercontent.com/68845670/136256165-740f8694-00b8-4528-84a0-c7defec82d00.png)
![image](https://user-images.githubusercontent.com/68845670/136256226-a31569a0-6d7a-435f-b040-5f30f0081060.png)

#### Additional information

* PrestaShop version: 1.7.7.8, 1.7.7.7 (not hapenning on 1.7.6)
* PHP version: 7.4, 7.3
* Language - Czech
* Tried on two Windows computers (Laragon server with Apache). Changing of PHP and Apache versions not changed anything (also toggling the PHP extensions )

Thank you

**Comment by matks** [comment]
@pouzarm from the error message I can see that this is not a 100% issue. The mail sending feature is having difficulties encoding correctly some characters, which result in throwing a NotEncodableValueException.

Could you share the examples of characters that cannot be sent? It could be in recipient, title, content... but if we cannot reuse them I dont think we can reproduce your bug report.

**Comment by pouzarm** [comment]
@matks Hi matks. Thanks for answer.
I understand the error, but it is shown on clean new installations of prestashop (**without any changes**). So theres only default text in **official testing email**.

1 Downloaded the zip from official page 1.7.7.8
2. Unziped
3. Installed in CZECH language (deleted install and renamed admin)
4. Clicked on "Send testing email".
5. Error

I also tried install Prestashop in english but didn't helped.

Shop also not sending any email .. even after order completion.

List of PHP extensions:
![image](https://user-images.githubusercontent.com/68845670/136329868-21019e6f-fb8a-4014-bcd2-41ab743467bd.png)

---

I know there can be error in my custom Mail function, thats why i focus on official emails.

**Comment by hibatallahAouadni** [comment]
Hello @pouzarm 

I didn't manage to reproduce the issue with PS1778 and CZECH language as admin language, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/136354502-0387b9ad-239f-4c03-9224-dc173824011e.png)

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @pouzarm 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
