### ISSUE TITLE
Search module for default classic template not compatible with 1.7.8

### ISSUE THREAD

**Issue by raidnet-ms** [PrestaShop/PrestaShop#26146]
#### Describe the bug

The frontend module is not rendering properly

#### Expected behavior

Properly rendering with correct width and without showing resize bars inside the search field.
But here are also font rendering problem as if some css is missing.

#### Steps to Reproduce

1. Go to 'homepage'
2. look on 'search field inside navbar'

**Screenshots**

<img width="604" alt="modeul" src="https://user-images.githubusercontent.com/22340972/136414533-88e96a51-9455-4e82-a690-57022e901c60.png">
If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: 7.4

**Comment by hibatallahAouadni** [comment]
Hello @raidnet-ms 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #25594. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #25594
