### ISSUE TITLE
URL rewriting : impossible to disable it

### ISSUE THREAD

**Issue by sirius82** [PrestaShop/PrestaShop#26143]
#### Describe the bug

After to have migrate the website on an other server, product and category images are not displayed. So I try to disable the url rewriting but after to have saved, the button is always on "ON". To test if it's due to the transfert, I tested also on the first server. And it's the same. 

#### Expected behavior

I wish to be able to disable the url rewriting 

#### Steps to Reproduce

1. Go to Shop Parameters
2. Click on Traffic & SEO
3. Scroll down to Set up URL
5. Click on NO at Friendly URL
6. Click on Save button
7. At Friendly URL, the button is always on ON

**Screenshots**

![image](https://user-images.githubusercontent.com/11886689/136406541-1f5e90e4-994d-4681-95d4-e733ea29ab0e.png)

#### Additional information

* PrestaShop version: 1.7.7.8
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @sirius82 

I didn't manage to reproduce the issue with PS1778, see the attached screen record below:

https://www.awesomescreenshot.com/video/5541027?key=c455cdb60feb1a0498ac31164435c1ad

Please check and feedback.
Thanks!

**Comment by sirius82** [comment]
hi!
I think it's solved. After to have activated debug mode, each time I tried to disabled rewriting, I receive a message about url rewriting of smartblog module. So I changed it in the mo dule configuration and it works now.
Thanks

**Comment by hibatallahAouadni** [comment]
Glad to hear :tada: 
Thanks for your feedback!
