### ISSUE TITLE
BO - Customer View page - Sort in the block voucher & the block addresses are NOK

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#26149]
#### Describe the bug

Related to https://github.com/PrestaShop/PrestaShop/issues/25588
In the BO > Customers > Customers view page if we have more than some vouchers and some addresses, the Sort with all fields is not working.

#### Steps to Reproduce

1. Create some vouchers for a customer John DOE
2. Go to BO > Customers page
3. View the customer John DOE
4. In the Voucher block, try to sort with all fields => NOK  ![image](https://user-images.githubusercontent.com/16067358/136423006-96d3ee96-aef2-4763-abb9-2deb1998175d.png)
6. In the Addresses block, try to sort with all fields => NOK 
![image](https://user-images.githubusercontent.com/16067358/136423096-fd416e91-bd8d-4717-ae1e-104fc643e1fe.png)

In the PS1777, we don't have this sort 
![image](https://user-images.githubusercontent.com/16067358/136423194-c193194f-cb5c-4b19-bc99-bb4707525b7f.png)

#### Additional information

* PrestaShop version: 1780, 178x
* PHP version: 7.2

**Comment by jolelievre** [comment]
So the arrows for sorting are visible, but not doing anything right?

**Comment by khouloudbelguith** [comment]
@jolelievre, yes exactly :+1:

**Comment by matks** [comment]
@PrestaShop/product-team We have analyzed this bug
- we can easily fix the sorting of adresses listing
- to fix the voucher listing, it's more work because the data fetching is not ready

As the sorting was not possible before 1.7.7 (so we 'accidentally' enabled it on 1.7.7) should we implement this sorting (even if it's more work) or should we simply disable the possibility to sort vouchers on this page?

**Comment by MatShir** [comment]
Nice work @tegbessou! Let's add the sorting if we can for the address. ID, Name and Country should filterable for the rest, it doesn't make sense :)
I don't see the need to sort on the voucher. Thanks for the exploration @matks

**Comment by khouloudbelguith** [comment]
Please don't close this issue after merging this PR: https://github.com/PrestaShop/PrestaShop/pull/26241.
The Sort for the addresses block is not fixed yet.

Thank you!
