### ISSUE TITLE
Fix module manager bugs

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#26144]
#### Describe the bug

**Following the PR #25245 there are some things to correct on the module manager page**

- [x] When I select "show all modules" and click to uninstall a module, the button to reinstall it isn't displayed until I refresh the page.
It should be displayed right after uninstalling the module.

![Capture d’écran 2021-10-07 à 16 47 24](https://user-images.githubusercontent.com/13449658/136411215-f6a35da4-4e9c-4e3f-96cd-3d07d6784641.png)

- [x] When I select "uninstalled modules" nothing is shown, while some modules are uninstalled.
All the uninstalled modules should be displayed.

![Capture d’écran 2021-10-07 à 16 54 42](https://user-images.githubusercontent.com/13449658/136410249-f0fd6905-ebd3-417a-bf79-4433f53449ff.png)

![Capture d’écran 2021-10-07 à 16 55 17](https://user-images.githubusercontent.com/13449658/136410194-ca314dbe-5649-49c7-8fd6-545fb4269a17.png)

- [x] When I select "uninstalled modules" and click on "Install" for a module, this module should not be displayed right after installing it.

- [x] When I select "disabled modules", I see the modules disabled and the module not installed.
Only the disabled module should be displayed, not the uninstalled.

- [x]  When I select "disabled modules" and click on "Enable" for a module, this module should not be displayed right after enabling it.

![Capture d’écran 2021-10-07 à 16 57 36](https://user-images.githubusercontent.com/13449658/136410631-77328f08-b110-4b30-9d79-e05392fd38bb.png)

- [x] When I select "enabled modules" and click on "Disable" for a module, this module stays displayed until I refresh the page. It should not be displayed right after disabling it.

- [x] We should add a status "installed modules" in the drop-down to display all the installed modules (enabled and disabled).

- [x] When I select "installed modules" and click on "Uninstall" for a module, this module should not be displayed right after uninstalling it.

#### Additional information

* PrestaShop version: 8.0
* PHP version: N/A

**Comment by NeOMakinG** [comment]
![image](https://user-images.githubusercontent.com/14963751/139860075-03d44146-c1a5-4d25-82f1-c43838204c17.png)

Can't reproduce the second point

Edit: Reproduced it, it happen only when you uninstall a module and don't refresh the page
