### ISSUE TITLE
Go to Cache clean, clean cache then error file_exists(): open_basedir restriction in effect

### ISSUE THREAD

**Issue by eveneme** [PrestaShop/PrestaShop#26151]
#### Describe the bug

After clearing the cache and entering the desktop it crashes an error 

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to Cache clean and clean cache
2. Click on Desktop
4. See error:
```
Warning w linii 2509 w pliku /home/platne/serwer97385/public_html/bimmertech/classes/module/Module.php
[2] file_exists(): open_basedir restriction in effect. File(/views/templates/hook/HookDashboardZoneTwo.tpl) is not within the allowed path(s): (/home/platne/serwer97385/public_html/bimmertech/:/home/platne/serwer97385/tmp/:/home/virtuals/bimmertech.pl/:/usr/local/php56-fpm/lib/php/:/tmp:/home/tmp:/var/lib/php5)
```

**Screenshots**

https://i.ibb.co/yS2RZLb/obraz-2021-10-07-230357.png

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: PHP: 7.4.23
* Apache
* Linux #1 SMP Debian 4.19.194-2 (2021-06-21) x86_64

**Comment by eveneme** [comment]
The error occurs all the time after entering the desktop in the administration panel. 
https://i.ibb.co/yS2RZLb/obraz-2021-10-07-230357.png

**Comment by khouloudbelguith** [comment]
Hi @eveneme,


Is this a fresh install shop 1780 or an upgrade from a previous version?
Did you install any module before this issue occurs?
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - PrestaShop version (source)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by eveneme** [comment]
This is new install shop 1.7.8.0. I did not install any modules, it is a clean installation. I get this error when debug mode is on. If you turn off debug, you won't get an error. I recorded a video see  https://youtu.be/Y97EFVtcLFY

Screenshoot: https://i.ibb.co/6RwqSvM/obraz-2021-10-08-143923.png

I tested on a different server and the problem also occurs so the problem is on the prestashop side.

**Comment by khouloudbelguith** [comment]
@eveneme, what is the exact language/country did you use during the install of your shop?

Thanks!

**Comment by eveneme** [comment]
> what is the exact language/country did you use during the install of your shop?
> 
> Thanks!

Polish - Poland

**Comment by florine2623** [comment]
Hello @eveneme ,

I can't reproduce your issue on fresh install PS 1.7.8.0 in Polish :
<img width="684" alt="Screenshot 2021-10-12 at 11 31 17" src="https://user-images.githubusercontent.com/16019289/136931298-22f4a95b-493d-4099-830e-8dfeba392845.png">

I deleted cache - went back to Dashboard, no Warning :
https://watch.screencastify.com/v/HIzBJ5sprtFPmbn8xq9E

I see that you have overrides on 3 files, please check them.

**Comment by eveneme** [comment]
please turn on debug mode. And go to the dashboard / desktop, look https://youtu.be/L5pmKpG41Jo

**Comment by kpodemski** [comment]
It's most likely related to your server configuration. I couldn't reproduce this issue either.

**Comment by eveneme** [comment]
This is done on two servers, one on litespeed the other on apache.

**Comment by hibatallahAouadni** [comment]
Hello @eveneme 

I didn't manage to reproduce the issue me either. Could you please provide more infos :pray: 
Please check and feedback.

Thanks!

**Comment by eveneme** [comment]
fresh installation:

-----------------
Please take a look

**Comment by hibatallahAouadni** [comment]
Hello @eveneme 

You shouldn't share these infos in public :wink: 
At first when I access to your shop, this error has been thrown:

![image](https://user-images.githubusercontent.com/23308427/137285106-89aa8692-0563-4fc2-b760-7ebdafe1f5c5.png)

And you have another issue when I change an order's status to **payment accepted**, I get this error:

![image](https://user-images.githubusercontent.com/23308427/137286373-1df77e37-6525-4605-ac61-91f570c335f2.png)

It seems your issue is not related to clear cache, you have an issue with the access right.
Please check and feedback.

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @eveneme,

Since we had no news from you for more than 20 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
