### ISSUE TITLE
Move procuct-combinations back to a separate tab

### ISSUE THREAD

**Issue by madsoliver** [PrestaShop/PrestaShop#26154]
#### Is your feature request related to a problem?

Before 1.7.8.0 Combinations (inside the edit product controller) was in a separate tab. It was better because:
When you have 10 colors, 3 styles and 5 sizes it means 150 combinations and a mile long page. 
When other essential content is below combinations (like stock behaviour), it might get overseen.

Also it's confusing that categories are directly over combinations.

#### Describe the solution you'd like
Move it back to it's ovn tab again.

#### Additional context
PS 1.7.8.0

**Comment by khouloudbelguith** [comment]
Hi @onklmaps,

Thanks for your report.
Are comparing Product version 1 and the Product version2?
- Product V2
![image](https://user-images.githubusercontent.com/16067358/136545607-b1497a04-8e55-46c8-9c86-c802a4ce87b9.png)
- Product V1
![image](https://user-images.githubusercontent.com/16067358/136545657-5e36366d-2eb9-4e75-8a2d-20f71fb67075.png)

Could you please provide me screenshots of your issue?

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @onklmaps 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
