### ISSUE TITLE
The menu in the management panel is not displayed properly. 

### ISSUE THREAD

**Issue by eveneme** [PrestaShop/PrestaShop#26161]
#### Describe the bug

The marketing link is displayed badly, but only in the dashboard.  on the screenshot you can see everything. 

#### Steps to Reproduce

1. Go to Dashboard
4. See error Link marketing displayed badly.

**Screenshots**

https://i.ibb.co/Ws2f0Zc/obraz-2021-10-08-144915.png

#### Additional information

* PrestaShop version: 1.7.8.0 but problem also in 1.7.7
* PHP version: 7.4

**Comment by kpodemski** [comment]
Hello @eveneme 

What is this module? A third-party module or a native one?

**Comment by eveneme** [comment]
native.

**Comment by khouloudbelguith** [comment]
Hi @eveneme,

I did not manage to reproduce the issue with PS1777 and PS1769
![image](https://user-images.githubusercontent.com/16067358/136573105-cd05ddca-59a1-48a4-bcbc-4f7260704417.png)
The Facebook module is not a core module.
As it's not a module provided by Prestashop Core, we can't do anything with this.
You should contact the module author via this address mail `support-facebook@prestashop.com`, they are the only ones to help you with it.

Thank you!

**Comment by eveneme** [comment]
> Hi @eveneme,
> 
> I did not manage to reproduce the issue with PS1777 and PS1769 ![image](https://user-images.githubusercontent.com/16067358/136573105-cd05ddca-59a1-48a4-bcbc-4f7260704417.png) The Facebook module is not a core module. As it's not a module provided by Prestashop Core, we can't do anything with this. You should contact the module author via this address mail `support-facebook@prestashop.com`, they are the only ones to help you with it.
> 
> Thank you!

t's about displaying the marketing link incorrectly. No facebook..

**Comment by RubenMartins** [comment]
I'm having the same issue on 1.7.8.0 on both the Dashboard and Stats Page as you can see on the image bellow:
![image](https://user-images.githubusercontent.com/5765731/138065459-d0547007-d9dd-41b2-a331-52c35f523e16.png)

This seems an issue with pages that are not yet migrate to Symfony. On the "Marketing" menu not related with Facebook module but anything that uses the Marketing menu displays this incorrectly even with Facebook Module disabled.

On 1.7.7.x I did not have this issue.


Looking a bit further seems that the icon with class ".material-icons.mi-campaign" isn't being loaded on not migrated pages to symfony.

**Comment by DracoBluee** [comment]
I too :)

**Comment by RubenMartins** [comment]
> I'm having the same issue on 1.7.8.0 on both the Dashboard and Stats Page as you can see on the image bellow: ![image](https://user-images.githubusercontent.com/5765731/138065459-d0547007-d9dd-41b2-a331-52c35f523e16.png)
> 
> This seems an issue with pages that are not yet migrate to Symfony. On the "Marketing" menu not related with Facebook module but anything that uses the Marketing menu displays this incorrectly even with Facebook Module disabled.
> 
> On 1.7.7.x I did not have this issue.
> 
> Looking a bit further seems that the icon with class ".material-icons.mi-campaign" isn't being loaded on not migrated pages to symfony.

@khouloudbelguith can you please review this again on 1.7.8.0 as is part of core issue I believe

**Comment by khouloudbelguith** [comment]
Hi @eveneme, @RubenMartins,

I installed fresh PS1780 with PH7.4.14 and I did not manage to reproduce the issue.
I attached a screen record
https://watch.screencastify.com/v/CqMZnunmMV6gFRkoq2x0

Thanks to check and feedback.

**Comment by RubenMartins** [comment]
@khouloudbelguith can you please test it on the latest chrome version? If you can't reproduce it just let me know to do a clean install.
This version I'm running now that this happens was upgraded from 1.7.7.x using the autoupgrade module if it helps debug it.

**Comment by DracoBluee** [comment]
i have clean install 1.7.8.0 and i have this bug on opera.

**Comment by florine2623** [comment]
Hello all, 

@RubenMartins , I can't reproduce the issue on Chrome Version 94.0.4606.81 and PS 1.7.8.0 :
<img width="223" alt="Screenshot 2021-10-26 at 15 04 56" src="https://user-images.githubusercontent.com/16019289/138884796-a0163e11-ad1e-4945-a76c-310c9e999521.png">

@DracoBluee , Can't reproduce the issue on opera either :
<img width="275" alt="Screenshot 2021-10-26 at 15 07 38" src="https://user-images.githubusercontent.com/16019289/138885241-5de3a6a2-6a7a-43e0-8df7-6ab86138f902.png">

**Comment by eveneme** [comment]
I Found the reason for the display problem. You have to go to modules and click clear next to the facebook module. And the problem disappears.

**Comment by RubenMartins** [comment]
Hi @eveneme this worked for me as well now.
@khouloudbelguith seems that could be something on upgrading an existing store from 1.7.7 to 1.7.8 that caused this cause when the facebook plugin is reset it fixed the visual glitch going forward.

**Comment by hibatallahAouadni** [comment]
Hello @RubenMartins & @eveneme 

Can you please reset the module and check if the issue still persist?
Please check and feedback.

Thanks!

**Comment by RubenMartins** [comment]
Hi @hibatallahAouadni yes reseting the plugin did the trick to fix it.

Thank you

**Comment by florine2623** [comment]
I will close the issue as it is fixed.
Thanks!
