### ISSUE TITLE
Email not being forwarded from Prestashop 1.7.7.8

### ISSUE THREAD

**Issue by CosimoPalermo** [PrestaShop/PrestaShop#26167]
#### Describe the bug

I recognized that when a customer is subscribing to my newsletter or is purchasing an item the my Prestahop 1.7.7.8 is not forwarding the confirmation email. 

#### Expected behavior

I noticed  that instead of forwarding the automatic emails to the correct address, the software is being forwarding them to my own address, as like somebody is contacting me directly from my "contact us" form. Anyone there is experiencing the same issue?

#### Steps to Reproduce

![fsadassda](https://user-images.githubusercontent.com/92171568/136582000-e1c34353-ead1-4516-b1a1-3062cf323f10.jpg)
![fsadassda](https://user-images.githubusercontent.com/92171568/136582033-e49270da-285f-431a-89b7-5d006bbb3e3e.jpg)

**Screenshots**

#### Additional information

* PrestaShop version: Prestashop 1.7.7.8
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @CosimoPalermo,

Could you please test the send email in the BO > Advanced Parameters > Emails page?
![image](https://user-images.githubusercontent.com/16067358/136584437-feb33400-47c7-4a23-bfb5-4bb3f264876e.png)

What is the exact option did you use to send an email? is it `Use /usr/sbin/sendmail ` or  `Set my own SMTP parameters`?

Thanks!

**Comment by CosimoPalermo** [comment]
Hi khouloudbelguith 

Yes, I receive THIS error message.

![fwsf](https://user-images.githubusercontent.com/92171568/136585573-1b9e9d4d-c21c-438d-8859-90e304d17840.JPG)

Regards

Cosimo Palermo

**Comment by khouloudbelguith** [comment]
@CosimoPalermo, It is a server issue.
You need to contact your host.
On this github repository there is no software support. This is an open source project.

You can find help

- on PrestaShop forums https://www.prestashop.com/forums/
- or by purchasing software support plan from https://www.prestashop.com/en/support

I will close the issue, feel free to create a new one.

Thanks!
