### ISSUE TITLE
Multishop - The Payment modules does not work after "I agree to the terms of service", "order with an obligation to pay" is disabled

### ISSUE THREAD

**Issue by VidarPc** [PrestaShop/PrestaShop#26171]
#### When ready to confirm the order and check out for payment either using "Pay by bank wire", "Pay using PaySera", "Cash On Delivery (COD)", "PayPal" any of these modules allows you to continue with the "Order with an obligation to pay". The only module that allows continuing the payment process is the "Prestashop Checkout" module.

When ready to click on the "Order with an obligation to pay" the mouse marker shows a red "forbidden" symbol and it is not possible to continue. This works and lets you continue only if choosing the "PrestaShop Checkout" module.

![image](https://user-images.githubusercontent.com/18537770/136588941-cf2939cc-f417-4178-88cd-59921c1f63d3.png)

#### Expected behavior

When clicking on the "Order with an obligation to pay" the process should continue and the order should be placed. It does not happen and it does not matter if I am using Microsoft Edge browser for Windows 11 or Google Chrome browser. Both behave in the same way.

#### Steps to Reproduce

1. Confirm the "I agree to the terms of service and will adhere to them unconditionally". Place your mouse pointer over the green line "Order with an obligation to pay" after you have chosen "Pay by bank wire", "Pay using PaySera", "Cash on Delivery (COD), or PayPal.
2. Click "Order with an obligation to pay".
4. See the "forbidden" symbol showed as the mouse pointer that does not allow clicking on "Order with an obligation to pay".
5. If you choose the payment option "Prestashop Checkout", and choosing either pay with a card or the integrated PayPal function in "PrestaShop Checkout", it works.

**Screenshots**
![image](https://user-images.githubusercontent.com/18537770/136645556-0afc7ac1-e361-4998-b53d-32a5b3e0e919.png)

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.4.24

**Comment by dainora** [comment]
I found a solution which worked for me, just replace core.js file from Prestashop 1.7.7.7 or other previous version. 
Themes ->core.js

**Comment by VidarPc** [comment]
Thank you for your solution. I used the core.js file from 1.7.7.8 and now my clients can check out their baskets again using Pay by bank-wire, PayPal, or PaySera, and Cash on delivery. The developers must have tested only their own payment module "PrestaShop checkout", with the option pay by a card or pay using Paysera. Thank you so much Dainora. You made my day today! :-)

**Comment by hibatallahAouadni** [comment]
Hello @VidarPc 

I didn't manage to reproduce the issue with PS1780 and Multishop, see the attached screen record below:

https://watch.screencastify.com/v/8QBHo9M5qLXGm4ZmKZli

Please check your Payment Preferences (BO) and feedback.
Thanks!

**Comment by theking81** [comment]
@dainora true after upgrade to the latest version 1.7.8.0 i had the same issue.
I did see the errors about the core.js in the console panel and saw your comment, and after replacing the file and clearing cache, everything was back to normal. This is a major bug as it affects many stores after upgrading or after fresh installation. This must be fixed asap.

**Comment by matks** [comment]
@VidarPc @dainora @theking81 QA analyst @hibatallahAouadni could not reproduce the issue following your indications.

> I didn't manage to reproduce the issue with PS1780 and Multishop, see the attached screen record below:

It is possible bug only happen in specific situation or with specific setup. Could you give us all the details you could ? We need to really understand how you use PrestaShop and which kind of hosting / environment / settings / configuration you have to be able to find out how we can reproduce the issue. If we cannot reproduce, we cannot solve the problem.

**Comment by Matt75** [comment]
It's theme related I think ;)
No problem with classic theme but some custom theme are not compliant with changes introduced in core.js for 1.7.8.0

**Comment by VidarPc** [comment]
I use SiteGround's server. The theme that I use is from AngarTheme Version 2.4.0. I am running PS as a Multishop. For the other of the shops, I am using default Classic Version 1.0.0 (Designed by PrestaShop Team). The problem with clicking on the green line "Order with an obligation to pay" fail for both shops, so in my opinion it is not directly related to the theme. My shop is running now, but it is because I am using the old core.js file from PS 1.7.7.8. I have been in contact with the developer of the Angar Theme and am in progress upgrading the theme to 2.4.4. At the moment, I have upgraded to 2.4.3 and will proceed with the upgrade to 2.4.4 tomorrow morning. The upgrade has to be done as a cumulative frequency, so it consumes some time. I will let you know tomorrow after the final upgrade of the theme how it works. If it does not work, I am willing to give you access to my account, both the admin panel and the credentials at the hosting provider.

**Comment by florine2623** [comment]
Hello @VidarPc ,

Waiting for your feedback then.

I have tried on my end, and I cannot reproduce the issue either :
<img width="726" alt="Screenshot 2021-10-12 at 14 22 15" src="https://user-images.githubusercontent.com/16019289/136955258-2f48b80b-ba77-4011-8872-d29f166cf825.png">

**Comment by VidarPc** [comment]
I have now installed all the versions of the theme "P17AT03 Bikes, sport and travels store" cumulative up to 2.4.4 and my PS 1.7.8.0 is now working in that way that clients can check out and pay for the ordered items. I tried to change the module "Social Media Follow Link (Configure)" and change the link for Instagram to https://www.instagram.com/racinghorses.eu/ . Unfortunately after doing "save", nothing changed. It is still the old link to https://www.instagram.com/eracinghorses/ , that appears on the configuration line for Instagram in this module. I have also cleared the cache in the back office. I tried to reconfigure the Instagram link via the module: "Configure AT - 1. Fast configuration of modules" and then choose "Social media follow links in the footer (Twitter, Facebook, Youtube, Google +, etc.)", "configure".  Default theme Classic Version 1.0.0
Designed by PrestaShop Team is also working now with the new core.js file delivered by the 1.7.8.0 release. However, I was not able to see any other failures with the 1.7.8.0 release at this moment.

**Comment by florine2623** [comment]
Hello @VidarPc ,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

We will close this issue.

Thank you

**Comment by dainora** [comment]
@florine2623 You were using cheque not bank transfer module to reproduce. it is definitely not server config issue as changing core.js file started to work. I guess it is a bug left in a condition.

**Comment by TouchCab** [comment]
I agree, this seems to be a core issue.

On upgrade from 1778 to 1780 I came across this issue too. I have classic theme yet changing to a previous version of themes/core.js has "fixed" the issue.

I say "fixed" as the look and feel of the theme is now wrong. Check boxes don't 'tick' for example, they just do a weird highlight.

Interestingly though, I do have "update theme" set to no on an one click upgrade when I upgrade, as I have customised the classic theme. (This is purely a find and replace of default colours to my own colours). So I wonder if this is where the bug is creeping in?

Also, I have tried with ALL payment types and the same issue.

Lastly, I tried to update some payment preferences in the BO to fix the issue. This caused some problems! For some reason, whatever table I change, the carrier restrictions table gets wiped and cannot be changed again. if I select a checkbox in this table and hit save, no errors, but the table is wiped again. The only way to get this back is to do it in the database itself. This has been a bug in my PS since at least 1777.

**Comment by thomas298** [comment]
I have the same problem with all payment types when i use the classic rocket theme. With the classic theme everythink works fine and replacing theme/core.js file with older version makes the classic rocket to also work fine.

**Comment by razarahil** [comment]
I'm also facing the same problem, final payment is disabled and the user is not able to complete the payment.

**Comment by hibatallahAouadni** [comment]
Hello everyone,

Sorry for the late response!
We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #26274. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #26274
