### ISSUE TITLE
1.7.8 Update

### ISSUE THREAD

**Issue by sir-kira** [PrestaShop/PrestaShop#26178]
Hello,

After update to 1.7.8 i can't edit description of product.  Field have text and are sown in the shop, but in back office is blank.
Atched picture.
 Regards,
![product after update](https://user-images.githubusercontent.com/77806205/136672267-90bd6b9e-7b8b-4d2d-8b56-5b68e25da43f.PNG)

**Comment by kpodemski** [comment]
Hello! Have you tried to clear the cache of your browser? Or try in the Incognito mode?

**Comment by sir-kira** [comment]
Solved. Tks kpodemski !
