### ISSUE TITLE
.htaccess in /img directory

### ISSUE THREAD

**Issue by musicpanda** [PrestaShop/PrestaShop#26174]
#### Is your feature request related to a problem?

Since version 1.7.2.0 Prestashop has an .htaccess file in the /img directory.
On some hosting providers you won't notice the difference and missing files still produce a 404.

However, on A2hosting it results in all missing files resulting in a 403 - forbidden. I have seen this on two A2 accounts and A2 says that the .htaccess is the problem and not them. 

#### Describe the solution you'd like
When you remove the .htaccess file you get normal 404 errors.

Does this happen with more providers?

**Comment by matks** [comment]
> Since version 1.7.0 Prestashop has an .htaccess file in the /img directory.

It seems to be since 1.7.2 https://github.com/PrestaShop/PrestaShop/pull/7678

**Comment by musicpanda** [comment]
#7678 is about executability of php files. But I see also a 403 for missing jpg files.

**Comment by matks** [comment]
If I look at the state of the repository for 1.7.1.0 https://github.com/PrestaShop/PrestaShop/tree/1.7.1.0 I see no .htaccess in img/ folder ?

https://github.com/PrestaShop/PrestaShop/tree/1.7.1.0/img

**Comment by musicpanda** [comment]
I looked at the test installation for 1.7.7.0 on my computer. But maybe that was polluted from some other source...

**Comment by hibatallahAouadni** [comment]
Hello @musicpanda 

I just edit your issue description, so **please next time respect and follow the provided template to submit a complete report**.

Thank you for your suggestion. The Developer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

PS: thanks @matks for your quick reply!

Thank you

**Comment by MatShir** [comment]
I think this PR https://github.com/PrestaShop/PrestaShop/pull/29304 fix your issue. Could you double-check @matks @musicpanda?
