### ISSUE TITLE
Product quantity change on Cart not change total value on cart on prestashop 1.7.8

### ISSUE THREAD

**Issue by ADM777** [PrestaShop/PrestaShop#26173]
#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by kpodemski** [comment]
Hello @ADM777 

Are you referring to the `prestashop` javascript object?

**Comment by hibatallahAouadni** [comment]
Hello @ADM777 


Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by ADM777** [comment]
> Hello @ADM777
> 
> Are you referring to the `prestashop` javascript object?

YES...If I change product quantity on Cart, total value is same  on cart (it's changed just on refresh the page)
Ajax not working for delete product from cart too....and on order last page PLACE ORDER BUTTON not activated (allways deactivated)
