### ISSUE TITLE
Column not found: 1054 Unknown column 'c.id_customer' in 'on clause'

### ISSUE THREAD

**Issue by lthienard** [PrestaShop/PrestaShop#26176]
Hi,

Since my Upgrade to 1.7.8 version i can't access to Customer on BO (_index.php/sell/customers/{ID}/view_)

With Debug Mode I can't find where it can come from.

See Error:

```
An exception occurred while executing 'SELECT a.'id_address', a.'firstname', a.'lastname', a.'address1', a.'address2', a.'postcode', a.'city', a.'company', a.'phone', a.'phone_mobile', cl.'name' as country_name FROM ps_address a LEFT JOIN ps_country c ON a.'id_country' = c.'id_country' LEFT JOIN ps_customer customer ON a.'id_customer' = customer.'id_customer' LEFT JOIN ps_country_lang cl ON c.'id_country' = cl.'id_country' AND cl.'id_lang' = ? LEFT JOIN ps_customer_group customer_group ON 'c'.'id_customer' = 'customer_group'.'id_customer' WHERE (a.'id_customer' != 0) AND (a.'deleted' = 0) AND (customer.id_shop IN (?)) AND (a.'id_customer' = ?) GROUP BY c.id_customer' with params [1, 1, "1073"]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c.id_customer' in 'on clause'
```

#### Screenshot

https://drive.google.com/file/d/1DjQWGVqKNJz6Q9XzrnGlrctSTXF0o5aX/view?usp=sharing
https://drive.google.com/file/d/1DfQ24QmcWV3LtnokE4GgQREXxNKWvgEp/view?usp=sharing
https://drive.google.com/file/d/1DjIg_zNkc9sos_Egm04AXI8qEjL4X9DX/view?usp=sharing

* PrestaShop version: 1.7.8
* PHP version: 7.3

Thank's for help

**Comment by kpodemski** [comment]
Hello 👋 

It looks like a problem with some third-party module that is modifying your list of customers.

Could you check: Design -> Positions, check the checkbox to show non-positionable hooks, and search for the `actionCustomerGridQueryBuilderModifier` -  you should see a module that is causing this issue here. Let me know in case this hook is empty for you.

**Comment by lthienard** [comment]
> 
> 
> Hello 👋
> 
> It looks like a problem with some third-party module that is modifying your list of customers.
> 
> Could you check: Design -> Positions, check the checkbox to show non-positionable hooks, and search for the `actionCustomerGridQueryBuilderModifier` - you should see a module that is causing this issue here. Let me know in case this hook is empty for you.

Hello,

You found the solution, it came from the "extracolumns" module
https://addons.prestashop.com/fr/outils-administration/46237-personnaliser-les-colonnes-des-listes-back-office.html

By disabling the hook it works correctly again and thank you very much.

The module was updated to be compatible with PS 1.7.8 but this latest version causes this bug, I send a message to the developer to inform him.

thanks again

**Comment by lthienard** [comment]
Module Updated: Thank's for all
