### ISSUE TITLE
Unable to send emails from PS v1.7.7.8

### ISSUE THREAD

**Issue by Zero-Room** [PrestaShop/PrestaShop#26175]
#### Describe the bug

I have been trying to send emails from my PS domain but haven't been able to do so

#### Expected behavior

I expect the shop to send the mails

#### Steps to Reproduce

- sending a test mail 
- sending any outgoing mail 

**Screenshots**
![image](https://user-images.githubusercontent.com/26248035/136658680-fcf91db5-fb61-4af8-8c61-fe1d1f5bfb3d.png)
![image](https://user-images.githubusercontent.com/26248035/136658692-36db2838-c7bc-499e-9695-370dcf15e7e2.png)

#### Additional information

* PrestaShop version: v1.7.7.8
* PHP version: 7.4.21

**Comment by kpodemski** [comment]
Hello 👋 

PrestaShop 1.7.7.8 is not compatible with PHP 7.4. https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart

I suggest downgrading to 7.3 and checking again. Secondly, I recommend using SMTP configuration.

**Comment by hibatallahAouadni** [comment]
Hello @Zero-Room 

Could you please follow the instructions mentioned by @kpodemski :pray: 
Please check and feedback.

PS: thanks @kpodemski for your quick reply :superhero: 

Thanks!

**Comment by Zero-Room** [comment]
PHP-Version 7.3 throws the same error.

**Comment by khouloudbelguith** [comment]
Hi @Zero-Room,

I did not manage to reproduce the issue with PS1778
![image](https://user-images.githubusercontent.com/16067358/137496490-b925c54d-c1c5-4f06-909e-2c45de76c346.png)

It is a server issue, thanks to check your host to fix the issue and feedback.
Thanks!

**Comment by Zero-Room** [comment]
I fixed it by upgrading to PS v1.7.8

**Comment by hibatallahAouadni** [comment]
@Zero-Room Glad to hear :tada:
