### ISSUE TITLE
[BO] Modern email theme isn't optimized for RTL languages

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/PrestaShop#26177]
#### Describe the bug

Email templates that is generated base on Modern theme, isn't configured for RTL languages.

#### Expected behavior

Text align in email templates for RTL languages must be from right to left.

#### Steps to Reproduce

1. BO language must be RTL
2. Go to BO > Themes > Email theme
2. At "Generate emails" section, select Modern theme
3. Select a RTL language
4. Generate emails
4. At bottom of the current page ("Email themes" section) check email templates for Modern theme

**Screenshots**

Generated email template:

<img src="https://user-images.githubusercontent.com/85633460/136664939-c1a22423-14a0-4a0b-9c5d-ea999fed05c3.png" width="600"/>

Expected email template:

<img src="https://user-images.githubusercontent.com/85633460/138106941-0ae75c86-23f1-49b5-8b02-876e2e91ff50.png" width="600"/>

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @mparvazi 

I reproduce the issue with PS 1.7.6.7, 1.7.7.8 and 1.7.8.0. I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by mparvazi** [comment]
Hello @hibatallahAouadni 

Which branch should I use for PR?
`1.7.8.x` or `develop`?

**Comment by hibatallahAouadni** [comment]
Hello @mparvazi 

I think `1.7.8.x` but let's check with the Developer Team :wink: 
> Which branch should I use for PR?
`1.7.8.x` or `develop`?

Ping @PrestaShop/prestashop-core-developers could someone please answer @mparvazi question :pray:

**Comment by atomiix** [comment]
@hibatallahAouadni I think it's a question for @PrestaShop/product-team

**Comment by hibatallahAouadni** [comment]
@atomiix you're right :wink: 
Ping @PrestaShop/product-team which branch should @mparvazi use to push his PR? `1.7.8.x` or `develop` ?

**Comment by mparvazi** [comment]
Hello @hibatallahAouadni 
Does this mention work? `@PrestaShop/product-team`
🤔

**Comment by hibatallahAouadni** [comment]
Hello @mparvazi 

Create your PR on `1.7.8.x`, and if the Product/Developer Team ask you to change your PR target branch, then change it :wink: 

Thanks!

**Comment by marionf** [comment]
Hello,
This issue isn't a regression of the 1.7.8.0, so the PR can be done on the develop branch

**Comment by mparvazi** [comment]
Hello @marionf 
Thanks for your feedback.
I made a PR base an `1.7.8.x` #26331
Changing the base branch from `1.7.8.x` to the `develop` will be enough or I have to rebuild the PR from scratch?

**Comment by hibatallahAouadni** [comment]
> Changing the base branch from `1.7.8.x` to the `develop` will be enough

Yes, it will be enough.

**Comment by hibatallahAouadni** [comment]
@mparvazi why you closed this issue?

**Comment by mparvazi** [comment]
Hello @hibatallahAouadni 

https://github.com/PrestaShop/PrestaShop/pull/26340#pullrequestreview-789173269

> Changes on the email theme should be made in https://github.com/PrestaShop/mjml-theme-converter, then using mjml-theme-converter you can generate the .twig files for the core.

I tried to test in [PrestaShop / mjml-theme-converter](https://github.com/PrestaShop/mjml-theme-converter), but i had problem with `{% if languageIsRTL|default(false) %} `

My solution just works fine by changing files in email theme inside [PrestaShop / PrestaShop](https://github.com/PrestaShop/PrestaShop).

But as @atomiix commented, this isn't a standard way to solve this problem.

**Comment by hibatallahAouadni** [comment]
Even so the problem exists and we must find another solution :wink:

**Comment by mparvazi** [comment]
@hibatallahAouadni I got it!

**Comment by samberrry** [comment]
@hibatallahAouadni @mparvazi
Hey guys,
could you please re-open this issue?
I don know if there is another issue with the same topic. 
You know `mjml-theme-converter` is a temporary solution, and the issue itself has not yet been resolved.

As the modern mail template is the default mail template, all Arabic and RTL shops, which newly created, will face this issue. So, this is critical to the product.
Thanks

**Comment by mparvazi** [comment]
Hello @samberrry 

First of all I'm very happy that you've subscribed to this issue, because most of developers thinks modern email theme isn't designed for RTL, and uses classic email theme or third-party email themes for their projects in RTL!

I tried to fix the problem in PS directly, but there is some exceptions for modern email theme.
The modern email theme must be created with mjml-theme-converter repo and then merge to PS.

The mjml-theme-converter is currently RTL adapted and ready to use but yet the last changes not merged to PS.

So there is some options:

1. Waiting to be merged (as like as me)
2. Using classic email theme for your projects (as like as other developers)
3. Creating a campaign to request Product Team to merge last changes ASAP

**Comment by MatShir** [comment]
The option 3 got my attention ;)
We are going to discuss next week how we can improve contribution to the email theme. I think we could add this improvement on the patches release since the email theme can be considered as an external component, but I need to discuss it with the maintainers. I will keep you updated ;)

**Comment by MatShir** [comment]
https://github.com/PrestaShop/PrestaShop/issues/27570 ;) It should be available on the next patch, that will be released on the next month. From now on, don't hesitate to propose a PR to merge the improvements of the theme into the core, they will be accepted even in for patches
