### ISSUE TITLE
Catalog Price Rules Issue

### ISSUE THREAD

**Issue by pablo9x** [PrestaShop/PrestaShop#26186]
**Describe the bug**

I have a problem with the pricing rules. Everything configured correctly, rules enabled in preferences but the module does not show discounts. The application of promotions on a single product card works correctly. For verification, I installed a custom shop with the selected template and everything is correct there.

Module: Specials block v1.0.1

#### Expected behavior

I expect the promotions module to be displayed on the homepage and added promotions in the product group to be displayed correctly.

#### Steps to Reproduce

1. Go to 'Catalog' -> 'Discount' -> 'Catalog Price Rules' -> 'Add new'
2. I set it as below
![1](https://user-images.githubusercontent.com/89137161/130030942-9136852a-2a3d-429c-a0c6-3ee44c4b77ad.png)
3. In properties, I activate the display of discounted products
![2](https://user-images.githubusercontent.com/89137161/130031338-6fb04808-9337-4c87-b734-e99a091fa39a.png)

4. The promotions section is not displayed on the main page of the shop, and products to which a promotion was assigned do not display the promotion

5. Doing analogous steps on a clean custom shop everything displays correctly

**Video**
I present the video. I previously had multistore running - currently inactive (not sure if this is relevant). https://watch.screencastify.com/v/SWyGszx1dMLFB7cPcb7X?fbclid=IwAR1hpjAExSCEGOBfOXIAVY7ZuaP9isLc_NbNvHYPmZsQFPMEXvojqvS19_g

#### Additional information
* PrestaShop version: 1.7.7.7
* PHP version: PHP 7.2
* Theme: Bentriz Version 1.0.6

**Comment by hibatallahAouadni** [comment]
Hello @pablo9x 

I didn't manage to reproduce your issue with PS1777 and PS1778, see the attached screenshots below:

![image](https://user-images.githubusercontent.com/23308427/136778214-88715648-08bc-4a12-a5cc-c8d130148cb0.png)

---
![image](https://user-images.githubusercontent.com/23308427/136778371-2101a838-e114-4e7e-a448-7c53eb73710b.png)

---
![image](https://user-images.githubusercontent.com/23308427/136778436-a75e08c1-a354-42b9-8f8c-4544be285f37.png)

---
![image](https://user-images.githubusercontent.com/23308427/136778674-a79dba6a-016c-412c-b931-a2044e6bbdc4.png)

Please check and feedback.
Thanks!

**Comment by pablo9x** [comment]
On my custom shop everything works too, so I would like to ask for help in explaining what might be wrong. 
Or would it be possible to replace some batch files ?

**Comment by hibatallahAouadni** [comment]
Hello @pablo9x 

> On my custom shop everything works too

What do you mean by custom? you mean your shop with **Classic** theme or with **Bentriz Version 1.0.6** theme?
Well, **Classic**  works perfectly cause I didn't encounter any issue. But if you encounter this issue only with the **Bentriz Version 1.0.6** theme, so you need to contact the theme Developer to fix the issue.
Please check and feedback.

Thanks!

**Comment by pablo9x** [comment]
I switch from bentriz to classic theme and the problem is the same as described above.I don't see promotions anywhere, neither on the product page nor on the shop homepage.

Yes, after installing a test clean shop on another server, everything works. However, I want to run promotions in an already configured shop because I have a huge product base and everything is properly configured. 

I would like to add that I have already disabled "non prestashop modules" in the settings.

**Comment by hibatallahAouadni** [comment]
Hello @pablo9x 

> I would like to add that I have already disabled "non prestashop modules" in the settings.

You mean this button (see the attached screenshot below), it doesn't work :sweat_smile: (check the issue #9965) 

![image](https://user-images.githubusercontent.com/23308427/137171082-47cdbe57-009d-4dab-9dd9-51ae38ada957.png)

So, you need to disable module by module till you catch the culprit :smile:
Please check and feedback.

Thanks!

**Comment by piotro9x** [comment]
All of the above are unsuccessful. Catalog price rules does not work. The promotion rules are not added on the main page and on the discounted product pages. What can be done more in this situation?

**Comment by florine2623** [comment]
Hello @pablo9x ,

I can't reproduce your issues in PS 1.7.7.7.
I created a Catalog Price Rule and in BO the discount are well displayed :
<img width="1150" alt="Screenshot 2021-11-02 at 12 02 00" src="https://user-images.githubusercontent.com/16019289/139834959-8634d3e0-42f0-439f-9fc6-ada2bbbee95f.png">

We use GitHub issues only to discuss about **bugs** and **new features** in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

I'll close your issue as it can't be reproduced.
Thank you
