### ISSUE TITLE
Console command for getting and setting config values

### ISSUE THREAD

**Issue by tswfi** [PrestaShop/PrestaShop#26182]
#### Is your feature request related to a problem?

As a developer and sysadmin I want to set config values with scripts and automate setting things up without having to open a browser and login to BO and try to find the correct place.

#### Describe the solution you'd like

Console command that can be used to get, set and delete configuration values.

#### Alternatives you've considered

Nope :)

#### Additional context

This was discussed briefly here: https://github.com/PrestaShop/docker/issues/254

**Comment by tswfi** [comment]
pr coming in a moment

**Comment by hibatallahAouadni** [comment]
Hello @tswfi 

Thank you for your suggestion. 
The Developer Team will take it into consideration for future developments. 
Ping @PrestaShop/prestashop-core-developers wdyt?

Thank you

**Comment by tswfi** [comment]
@hibatallahAouadni you might want to change the autoreply when there is already a pr available ;)

**Comment by hibatallahAouadni** [comment]
@tswfi I just edit my comment :wink:

**Comment by atomiix** [comment]
@hibatallahAouadni As @tswfi's PR has already started to be reviewed, I guess we can say that this is something we want :)

**Comment by hibatallahAouadni** [comment]
@atomiix Done :wink:

**Comment by ytilotti** [comment]
I think #26211 is a duplicate.

**Comment by tswfi** [comment]
> I think #26211 is a duplicate.

It looks like `debug mode` is saved differently from regular configuration values. The current PR uses https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Configuration.php which does not know about the debug mode.

Few options:
* another command for switching debug mode
* extend configuration adapter to have a special case for debug mode
* add special case to the config command for debug mode

each one has its pros and cons.. 

I'm kinda leaning towards a new command `prestashop:debugmode true/false` (and `get` to get the current status). easier to see from the command listing and no need to remember a configuration key and does not require special case for configuration adapter nor the command.

**Comment by kpodemski** [comment]
Hello @tswfi 

I think @ytilotti is writing about the maintenance mode, and it should be a different command, in my opinion.

The same goes for the debug mode as it doesn't support multi-store, etc.

**Comment by tswfi** [comment]
ah, true. for some reason I was thinking about debug mode :D

yeah, maintenance mode requires few more settings. list ips, add ip, remove ip etc...

agreed that these should be separate commands as they have different logic.

**Comment by tswfi** [comment]
hmm, actually checked a bit more and it looks like the `prestashop:config` can already do the maintenance mode stuff


```
mysql> select * from ps_configuration where name like '%MAINTENANCE%' or name like '%SHOP_ENABLE%';
+------------------+---------------+---------+---------------------+-------+---------------------+---------------------+
| id_configuration | id_shop_group | id_shop | name                | value | date_add            | date_upd            |
+------------------+---------------+---------+---------------------+-------+---------------------+---------------------+
|               27 |          NULL |    NULL | PS_SHOP_ENABLE      | 1     | 0000-00-00 00:00:00 | 2021-10-15 10:10:54 |
|              285 |          NULL |    NULL | PS_MAINTENANCE_TEXT |       | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 |
|              397 |          NULL |    NULL | PS_MAINTENANCE_IP   | NULL  | 2021-10-15 10:09:56 | 2021-10-15 10:09:56 |
+------------------+---------------+---------+---------------------+-------+---------------------+---------------------+
```

```
root@87ea6cfe86b8:/var/www/html# bin/console prestashop:config set PS_MAINTENANCE_TEXT --value "check back later fi" --lang fi
PS_MAINTENANCE_TEXT="check back later fi"
root@87ea6cfe86b8:/var/www/html# bin/console prestashop:config set PS_MAINTENANCE_TEXT --value "check back later en" --lang en
PS_MAINTENANCE_TEXT="check back later en"
root@87ea6cfe86b8:/var/www/html# bin/console prestashop:config set PS_SHOP_ENABLE --value 0
PS_SHOP_ENABLE="0"
```

```
mysql> select * from ps_configuration c left join ps_configuration_lang cl on cl.id_configuration = c.id_configuration where name like '%MAINTENANCE%' or name like '%SHOP_ENABLE%';
+------------------+---------------+---------+---------------------+-------+---------------------+---------------------+------------------+---------+---------------------+---------------------+
| id_configuration | id_shop_group | id_shop | name                | value | date_add            | date_upd            | id_configuration | id_lang | value               | date_upd            |
+------------------+---------------+---------+---------------------+-------+---------------------+---------------------+------------------+---------+---------------------+---------------------+
|               27 |          NULL |    NULL | PS_SHOP_ENABLE      | 0     | 0000-00-00 00:00:00 | 2021-10-15 10:11:46 |             NULL |    NULL | NULL                | NULL                |
|              285 |          NULL |    NULL | PS_MAINTENANCE_TEXT |       | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 |              285 |       1 | check back later en | 2021-10-15 08:13:28 |
|              285 |          NULL |    NULL | PS_MAINTENANCE_TEXT |       | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 |              285 |       2 | check back later fi | 2021-10-15 08:13:24 |
|              397 |          NULL |    NULL | PS_MAINTENANCE_IP   | NULL  | 2021-10-15 10:09:56 | 2021-10-15 10:09:56 |             NULL |    NULL | NULL                | NULL                |
+------------------+---------------+---------+---------------------+-------+---------------------+---------------------+------------------+---------+---------------------+---------------------+
```

so yes, #26211 is "duplicate" (actually a subset for this command).

The debug mode config still requires its own command. I will open a new issue for it in a moment.

**Comment by hibatallahAouadni** [comment]
Well, I need to close this one as duplicate of this #26211 :sweat_smile:

**Comment by hibatallahAouadni** [comment]
Duplicate of #26211

**Comment by ytilotti** [comment]
? It's an error @hibatallahAouadni. It's not really duplicate and the same functionality.
