### ISSUE TITLE
1.7.8 Main menu module not able to update links 

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#26193]
#### Describe the bug

With the latest Main menu module when you want to update a created link, in stead of saying update. It shows add

#### Expected behavior

I returned to a older version where this problem is solved, but returned back in the latest version of Main menu

#### Steps to Reproduce

1. Go to modules
2. Click on main menu
3. Add a link and then try to update this link later
4. The button will show add and not update

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.8.0 ( with multistore )
* PHP version: 7.4

**Comment by hibatallahAouadni** [comment]
Hello @01park 

Thanks for following the template :rocket: 
I didn't manage to reproduce the issue with PS1780, see the attached screen record below:

https://watch.screencastify.com/v/7q5X3oiVDgtOQvPranfi

Please check and feedback.
Thanks!

**Comment by 01park** [comment]
Hi,

Can you try to edit the created link. Then you will see ADD and not UPDATE

**Comment by florine2623** [comment]
I can't reproduce your issue either :
https://watch.screencastify.com/v/eev7GiPEtIoNIRYihSrK

Make sure your Main Menu module is updated to latest version v2.3.0.
https://github.com/PrestaShop/ps_mainmenu

I'm closing your issue as it can't be reproduced. It must be a specific problem on your shop.
