### ISSUE TITLE
FO: Changes to basket executed but not visible before going to different page

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#26191]
#### Describe the bug

When someone goes to the basket and changes the quantity of a product or removes it from the basket, the actions are executed in the backend but they are only visible after clicking on the basket icon or navigating to a different page.

#### Expected behavior

The changes should be displayed immediately.

#### Steps to Reproduce

1. Add an item to basket
2. Click on the basket
3. Change the quantity or remove that item
4. Nothing changes in GUI
5. Click on the basket and notice the changes

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
1. Adding a product to cart is not an issue:
![image](https://user-images.githubusercontent.com/92299973/136763192-436e4a09-984d-4859-9071-90f634b92e15.png)
2. Cart after the product has been added:
![image](https://user-images.githubusercontent.com/92299973/136763374-c21de14d-dfe4-4427-9929-674b4fd896f6.png)
3. Let us try to delete the item from the cart:
![image](https://user-images.githubusercontent.com/92299973/136763579-595e53bc-cae6-4542-8637-d1cec210cc86.png)
4. After clicking on the bin icon, the request has been executed but the cart is presented in the same way as before trying to remove it:
![image](https://user-images.githubusercontent.com/92299973/136763855-5cbbcd71-74b4-444a-88d2-9c5ad33027c2.png)
5. The jQuery exception is shown:
![image](https://user-images.githubusercontent.com/92299973/136763993-96592b0e-a705-46f3-a12f-5f6f5220c579.png)
6. The response from the backend to show that the basket has been updated:
![image](https://user-images.githubusercontent.com/92299973/136764070-c646d230-1d45-4fa2-9d1c-82d7c33309e5.png)
7. Let us now click on the basket again:
![image](https://user-images.githubusercontent.com/92299973/136764306-09b9a6c7-fd49-4034-be6a-9e7344def83c.png)
8. Now we can see the change:
![image](https://user-images.githubusercontent.com/92299973/136764379-f0a14843-318d-43f6-98aa-7c094815a3d5.png)

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.3.31
* Theme in use: alcoholic (https://addons.prestashop.com/en/drink-tobacco-themes/49585-alcoholic-drinks-tobacco-wine-coffee-drinks.html#specifications)
* Deleting the cache does not solve the issue
* This bug is browser-independent (tested with Firefox, Chrome and Opera on Android)
* The previously used PrestaShop Version was 1.7.7.7 and that issue was not there

**Comment by hibatallahAouadni** [comment]
Hello @awarszewski 

I didn't manage to reproduce the issue with PS1780, see the attached screen record below:

https://watch.screencastify.com/v/qjQW4FD3P6MyT5gGn8OT

Please check and feedback.
Thanks!

**Comment by ghost** [comment]
Hi @hibatallahAouadni ,
thanks for the attempt to reproduce the issue. I am going to see if an update to the theme solves this and get back to you.

**Comment by hibatallahAouadni** [comment]
Thanks @awarszewski 
Waiting for your feedback :wink:

**Comment by ghost** [comment]
Hello @hibatallahAouadni ,
I have switched to the standard theme in a development environment (on a copy of the live system) and can confirm that this is not an issue of PrestaShop itself but a problem with this specific theme. Unfortunately, also an upgrade to the newest version of the theme does not solve this issue, so I will be contacting the theme developer to get this fixed.

**Comment by hibatallahAouadni** [comment]
Thanks for your feedback :relaxed:
