### ISSUE TITLE
Wrong microdata brand item type

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#26195]
#### Describe the bug
We have wrong microdata item type in our structured data. Google started complaining since 1.10.2021.
`Supported types: [http://schema.org/Brand,http://schema.org/Organization]`

#### Expected behavior
Item type must be Brand or Organization.

#### PR to fix
https://github.com/PrestaShop/PrestaShop/pull/26194
https://github.com/PrestaShop/theme-refacto/pull/69

**Screenshots**

![thing](https://user-images.githubusercontent.com/6097524/136786708-1c812001-06bb-40a4-be62-c78fd7613e59.JPG)

#### Additional information

* PrestaShop version: develop

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thanks for reporting the issue and your PR :rocket: 
I reproduce the issue with PS1764, PS1778, PS1780, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/136822208-81ee8e7d-2018-4dfe-b29d-f80b928a61c8.png)

I’ll add this to the debug backlog.

Thank you
