### ISSUE TITLE
Can't translate overrided module template

### ISSUE THREAD

**Issue by momo1240** [PrestaShop/PrestaShop#26198]
**Describe the bug**

When a module template is overrided in theme or childtheme, it's impossible to translate it in the back office 
the translation is saved but a message is shown telling that it's missing ( please check the screenshot)
and nothing is updated on front office (tried to empty cache, etc..)
thank you

**Screenshots**
![Capture d’écran 2021-10-11 164418](https://user-images.githubusercontent.com/3137613/136810538-2281f7c9-0f19-45dd-972c-3f75b7a5a19d.png)

#### Additional information

* PrestaShop version: 1.7.7.8
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @momo1240 

Did you encounter this issue with any native module or with Classic theme?
If no, you need to contact your module developer.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @momo1240 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
