### ISSUE TITLE
Search bar modules backoffice 

### ISSUE THREAD

**Issue by jordi-art** [PrestaShop/PrestaShop#26197]
Prestashop 1.7.8.0 
PHP 7.4
Hi Prestashop team ,i don't is this problem was ready reported. We have a problem in our shop after upgrade from 1.7.7.8 to 1.7.8.0 with 1 click module last version.
We have notice that the search bar modules on backoffice no work when we write the name of one module and click to srarch it show emptied. 
Thank you for your job i
Best regards.

**Comment by hibatallahAouadni** [comment]
Hello @jordi-art 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
