### ISSUE TITLE
1.7.8.0 prestashop product id field backoffice to small - visual improvement needed

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#26192]
#### Is your feature request related to a problem?

The product id field in prestashop 1.7.8 is to small, its only displaying 2 digits

#### Describe the solution you'd like

I would like the fields to show at least 6 digits

#### Alternatives you've considered

n/a

#### Additional context

Example 

n/a
![Screenshot 2021-10-11 at 12 56 39](https://user-images.githubusercontent.com/46492443/136771614-33a636d6-1e2e-430e-b990-2f79b42e1e12.png)

**Comment by hibatallahAouadni** [comment]
Hello @01park 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

PS: @NeOMakinG wdyt?

Thank you

**Comment by NeOMakinG** [comment]
> Hello @01park
> 
> Thank you for your suggestion. The Product Team will take it into consideration for future developments. Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it.
> 
> If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know!
> 
> PS: @NeOMakinG wdyt?
> 
> Thank you

I would probably add a min-width to id filter inputs

**Comment by 01park** [comment]
This is something that was working perfect in previous version

Issue still available in 1.7.8.1
