### ISSUE TITLE
[-] BO : AdminTranslationsController::userParseFile() does not detect tpl translations using modifiers

### ISSUE THREAD

**Issue by TrogloGeek** [PrestaShop/PrestaShop#262]
###### Exemple:

`{l|strtoupper s='test'}`
Is not elected for translation
###### Resolution proposal:

Update all tpl regex by adding `(|\S+)*` right after `{l`.
Change return statement to `return $matches[($type_file == 'tpl') ? 2 : 1];`

I'll create a pull request when I'll have time to if needed, but I think it is useless for such a simple fix.

**Comment by marionf** [comment]
Hello, 
This issue is old, so I close it.
If you still have it on the last version (PrestaShop 1.7.4.2), please open a new one.
Regards
