### ISSUE TITLE
Taxes do not print on invoices with version 1.7.8.0

### ISSUE THREAD

**Issue by JacHOBBY** [PrestaShop/PrestaShop#26203]
[FA013966-3.pdf](https://github.com/PrestaShop/PrestaShop/files/7323853/FA013966-3.pdf)

#### Describe the bug

When printing invoices in command module the taxes are calculated correctly but do not print on the invoice, and the printed version of the invoice does not show the proper total since taxes are missing.

#### Expected behavior

The invoice when printed should show different taxes separately and they should be added to the invoice subtotal and the invoice total should include the taxes.

#### Steps to Reproduce

1. Go to command
2. Click on view invoices
3. Open the pdf
4. See error there is no taxes on the printed invoice

**Screenshots**
See attached invoice FA013966-3

#### Additional information

* PrestaShop version: 1.7.8.0
nformations du serveur : Linux #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64

Version du logiciel serveur : Apache

Version de PHP : 7.2.34

Limite de mémoire : 6096M

Temps maximal d'exécution : 2000

Taille max. pour envoi de fichiers : 2048M
info_outline Informations sur la base de données

Version de MySQL : 5.7.35

Serveur MySQL : localhost

Nom MySQL : jacho913_pres287

Utilisateur MySQL : jacho913_pres287

Préfixe des tables : pskw_

Moteur MySQL : InnoDB

Connecteur MySQL : DbPDO
info_outline Liste des surcharges

    modules/contactform/contactform.php
    classes/Cart.php
    classes/controller/ProductListingFrontController.php
    classes/controller/FrontController.php
    classes/stock/StockAvailable.php
    classes/pdf/HTMLTemplateInvoice.php
    classes/Currency.php
    classes/Media.php
    classes/jacques/Cart.php
    classes/Context.php
    classes/Language.php
    classes/Hook.php
    controllers/front/AuthController.php

info_outline Informations

Version de PrestaShop : 1.7.8.0

URL de la boutique : http://jachobby.com/

Chemin de la boutique : /home/jacho913/public_html

Thème actif : ZOneTheme
info_outline Informations sur la configuration mail

Méthode d'envoi d'e-mails : Vous utilisez /usr/sbin/sendmail
info_outline Vos informations

Votre navigateur : Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0
info_outline Vérifiez votre configuration

Paramètres requis : ok

Paramètres optionnels : ok

**Comment by florine2623** [comment]
Hello @JacHOBBY ,

You need to make sure the file exists : https://github.com/PrestaShop/PrestaShop/blob/develop/pdf/invoice.tax-tab.tpl

Please check and feedback.

**Comment by JacHOBBY** [comment]
Bonjour Florine,
The invoice.tax-tab.tpl is there. Find the code bellow;
It is dated at the time of the upgrade. I have attache the file.
[invoice.tax-tab.tpl.zip](https://github.com/PrestaShop/PrestaShop/files/7331365/invoice.tax-tab.tpl.zip)

**Comment by florine2623** [comment]
OK.

I see that you have an override in classes/pdf/HTMLTemplateInvoice.php
Can you check if it is the same as : https://github.com/PrestaShop/PrestaShop/blob/develop/classes/pdf/HTMLTemplateInvoice.php

**Comment by JacHOBBY** [comment]
This is the difference I found in between the to files.
My version is on the left side.
I have also attach my file version

[HTMLTemplateInvoice.zip](https://github.com/PrestaShop/PrestaShop/files/7332867/HTMLTemplateInvoice.zip)

![Difference TemplateInvoice_PHP](https://user-images.githubusercontent.com/92323282/137022199-b54701aa-125b-4304-acc4-e32395032c5d.jpg)

**Comment by hibatallahAouadni** [comment]
Hello @JacHOBBY 

I didn't manage to reproduce the issue with PS1780, see the attached screen record below:

https://watch.screencastify.com/v/Tm2XDc0BJbQ8GVazllAy

Please check and feedback.
Thanks!

**Comment by JacHOBBY** [comment]
Bonjour, Hibatallah

Are you using the same files (tpl and PHP) has I upload or you are using 
the Github files ?

Jacques

**Comment by khouloudbelguith** [comment]
Hi @JacHOBBY,

In my case also, I did not manage to reproduce the issue with fresh install PS1780.
![image](https://user-images.githubusercontent.com/16067358/137479163-a1eae69e-29b3-4de8-a296-53f5fc2ddd93.png)

I attached a screen record
https://watch.screencastify.com/v/EFfVk5oJDSqc5V0cai5g
In fact, you need to enable tax in the BO > International > Taxes page > Enable tax
![image](https://user-images.githubusercontent.com/16067358/137479353-281be924-0549-4dec-9462-04eb47401e5c.png)

because if it is disabled your invoice will be displayed with no taxes
![image](https://user-images.githubusercontent.com/16067358/137479436-1e9898df-2595-4444-a32b-3e16e9c330a6.png)

I will close the issue, feel free to create a new one when needed.

Thanks!
