### ISSUE TITLE
Wrong number of parameters in CheckoutSession class 

### ISSUE THREAD

**Issue by christophe-rouille** [PrestaShop/PrestaShop#26208]
In method getCustomerAddressesCount of class CheckoutSession,  the call of method getSimpleAddresseshas has a wrong number of parameters

#### Additional information

* PrestaShop version: at least since 1.7.0
* PHP version: all

**Comment by florine2623** [comment]
Hello @christophe-rouille ,

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
