### ISSUE TITLE
Module search and module manager does not work in 1.7.8.0

### ISSUE THREAD

**Issue by jordi-art** [PrestaShop/PrestaShop#26202]
#### Describe the bug
After upgrading from ps 1.7.7.8 to 1.7.8.0 with PHP 7.4 the module manager and module catalog does not work, it does not show any. This problem happens to more people than just us.
Any solution or should we wait for the next patch update 1.7.8.1
Greetings and thank you very much for the work you do.
**Screenshots**

![screenshoot backoffice module search](https://user-images.githubusercontent.com/82602687/136820724-5b777ea6-4c59-48ea-a0e5-6cee5d1785bc.JPG)

* PrestaShop version: 1.7.8.0
* PHP version: PHP 7.4

**Comment by florine2623** [comment]
Hello @jordi-art ,

PS 1.7.7.8 is compatible with PHP 7.3 not 7.4 : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

I upgraded a shop from 1.7.7.8 to 1.7.8.0, it went well :
<img width="1206" alt="Screenshot 2021-10-12 at 10 49 41" src="https://user-images.githubusercontent.com/16019289/136924009-7307b9ff-167c-439a-95f9-e40a9a5994da.png">

Module search works :
<img width="1030" alt="Screenshot 2021-10-12 at 10 51 24" src="https://user-images.githubusercontent.com/16019289/136924279-bb934ef7-c67c-48fb-9163-6d7fa96a727a.png">
I tried search for multiple modules :
<img width="1031" alt="Screenshot 2021-10-12 at 10 51 50" src="https://user-images.githubusercontent.com/16019289/136924349-fc993cae-8a3d-41f3-a38c-e986b0928bdc.png">

Did you encounter any error during the upgrade process ?
Please check and feedback.

**Comment by jordi-art** [comment]
Hello, i should to restore again the shop to ps 1.7.7.8 because a part of it problem with backoffice modules search, any payments methods was working. Including bank transfer.
My upgrade was with 1click upgrade module without problem i seen. May it be have this versión some problem with PHP 7.4?
Thank you for your reply

Enviado de Samsung Mobile
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by florine2623** [comment]
While upgrading from 1.7.7.8, I advise you to use PHP 7.3.

**Comment by jordi-art** [comment]
Sorry florine,
I don't understand what do you meant, when i upgrade to 1.7.8.0 i used PHP 7.4.  Are do you refeing that when i going to make the upgrade from 1.7.7.8 to 1.7.8.0 i should to keep in PHP 7.3 then after once actualized enable PHP 7.4?

Enviado de Samsung Mobile
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by florine2623** [comment]
> Are do you refeing that when i going to make the upgrade from 1.7.7.8 to 1.7.8.0 i should to keep in PHP 7.3 then after once actualized enable PHP 7.4?

Yes exactly.
PS 1.7.7.8 is NOT compatible with PHP 7.4, that's why you should upgrade using PHP 7.3. Once the upgrade done to 1.7.8.0, you can upgrade your PHP version to 7.4.

**Comment by jordi-art** [comment]
Ok then if like that will going to try to do like you
tell me. Will feedback.
Thank you!




Enviado de Samsung Mobile
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jordi-art** [comment]
Hello Florine, i made like you told me but there are a lot of problems. Please you can see screenshoots.
1- the update was correct according to module 1 click
2- module manager this time it worked fine but I don't know if a larger symbol at the top left is normal
3- Summary and product description does not appear, after a while it does, but the number of summary characters and text do not appear well.
4- If a customer chooses a product, fill in their data and check consent boxes, the buy button does not work, neither with redsys nor with bank transfer.
5- In debug mode, the problems reported are only for translation.
The theme we use is transformer and it shouldn't give problems we've talked to the developer. The modules we use are separate from the idnovate theme and we have also talked to them. We also see problems in module mismatches of the theme, and the color codes in buttons etc, are not seen. We hope you can fix these bugs and we can update to 1.7.8.0 soon. Thanks for your work.
![20211012_164452 1](https://user-images.githubusercontent.com/82602687/136988898-3dca732c-6339-4057-b8b2-51c1271b1a67.jpg)
![20211012_164806 1](https://user-images.githubusercontent.com/82602687/136989040-34676a44-fff2-48d0-9df1-6e1ee7ec8701.jpg)
![20211012_165128 1](https://user-images.githubusercontent.com/82602687/136989121-0252f002-5d10-45d4-b277-38fd69d08b05.jpg)
![20211012_165415 1](https://user-images.githubusercontent.com/82602687/136989183-950bfb56-66fe-4765-ada1-6b9fd1fe7b0c.jpg)
![20211012_170257 1](https://user-images.githubusercontent.com/82602687/136989263-2a845e8a-05fa-49ab-bba8-11a8e78314ee.jpg)
![20211012_171022 1](https://user-images.githubusercontent.com/82602687/136989336-acde8bc6-2293-4439-be29-4258360e04e3.jpg)

**Comment by caotico25** [comment]
> #### Describe the bug
> After upgrading from ps 1.7.7.8 to 1.7.8.0 with PHP 7.4 the module manager and module catalog does not work, it does not show any. This problem happens to more people than just us. Any solution or should we wait for the next patch update 1.7.8.1 Greetings and thank you very much for the work you do. **Screenshots**
> 
> ![screenshoot backoffice module search](https://user-images.githubusercontent.com/82602687/136820724-5b777ea6-4c59-48ea-a0e5-6cee5d1785bc.JPG)
> 
> * PrestaShop version: 1.7.8.0
> * PHP version: PHP 7.4

Hey! I found the error on file app/Resources/translations/es-ES/AdminModulesNotification.es-ES.xlf.

On line 881 exist a line break that cause js problems. Changing this:

        <source>We strongly advise you to upgrade the modules on maintenance mode to avoid any cache issues.</source>
        <target state="final">Le recomendamos encarecidamente que actualice los módulos en modo de mantenimiento para evitar problemas de caché.
</target>
        <note>Line: 45</note>

To this:

        <source>We strongly advise you to upgrade the modules on maintenance mode to avoid any cache issues.</source>
        <target state="final">Le recomendamos encarecidamente que actualice los módulos en modo de mantenimiento para evitar problemas de caché.</target>
        <note>Line: 45</note>

Solves the problem and the module manager and module catalog is working again.

**Comment by hibatallahAouadni** [comment]
Hello @jordi-art 

> 1- the update was correct according to module 1 click

Glad to hear :tada: 
> 2- module manager this time it worked fine but I don't know if a larger symbol at the top left is normal

You just need to clear the cache :wink: 
> 3- Summary and product description does not appear, after a while it does, but the number of summary characters and text do not appear well.

Again, it's a cache issue :sweat_smile: 
> 4- If a customer chooses a product, fill in their data and check consent boxes, the buy button does not work, neither with redsys nor with bank transfer.

Could you please provide a screen record or just explain it more :pray: 
> 5- In debug mode, the problems reported are only for translation.

Well, I think you just need to add your missing translations :slightly_smiling_face: 
Please check and feedback.

Thanks!

**Comment by jordi-art** [comment]
Hello @hibatallahAouadni 
Thank you for your reply.
2- I have been using prestashop for some time and I know that you have to clear cache if you mean that. Of course I have.
3- Again the cache was deleted
4- If you look, you will see that there is already an image showing this problem, when a client fills in all their data and clicks on the buy button, it does not work, see a forbidden symbol in the image. That image is when a client chooses payment by transfer, with redsys the same thing happens. Tried both methods to see if it was only redsys module problem, but no. The problem is loan 1.7.8.0
5-If it were this that you comment, then I would not have been able to update before with 1.7.7.8 either, it would also have given problems and I have been updating all the versions with the same translations. Very weird, wouldn't it?
Thanks!

**Comment by khouloudbelguith** [comment]
Hi @jordi-art,

Thanks for your feedback.
In fact, we manage to reproduce the issue previously with PS1.7.8.0.
This issue is reproduced only when the employee language is Spanish
This issue is fixed now in the Crowdin as commented [here](https://github.com/PrestaShop/PrestaShop/issues/26028#issuecomment-939352213).
Your ticket is a duplicate of #26028
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #26028

**Comment by jordi-art** [comment]
Hello ,
Then i can upgrade without any problems?
Best regards!!

Enviado de Samsung Mobile
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by khouloudbelguith** [comment]
Hello @jordi-art,

Yes the issue is fixed as commented [here](https://github.com/PrestaShop/PrestaShop/issues/26028#issuecomment-943512721)
As always, you can use the 1-click update to upgrade between minor versions without much trouble. In order to avoid problems, remember not to change core files, check the compatibility of your modules and theme beforehand, and test the upgrade on a separate machine from your production.

Thanks!

**Comment by jordi-art** [comment]
Hello dear, your answer tells me to wait for me then 😉😄. Thank you very much happy weekend.

Enviado de Samsung Mobile
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
