### ISSUE TITLE
After upgrading from ps 1.7.7.8 to 1.7.8.0 with PHP 7.4 

### ISSUE THREAD

**Issue by TGD001** [PrestaShop/PrestaShop#26206]
Unfortunately I repeated the upgrade to the new version twice but I encountered two big problems that forced me to restore the backup. As I previously wrote in another thread, the sizing of the search bar looked wrong; in addition to this I noticed that it is not possible to add items to the cart and payment by bank transfer is not possible. So I kindly ask you to make a new release, the current one is unusable as far as I'm concerned. For information I don't use the default theme but Z.One theme. Thanks for your attention and sorry for the inconvenience. Piero Terracina

**Comment by JacHOBBY** [comment]
Bonjour Piero,

I do have the same theme zone buT I run on PHP 7.2.34. all my transaction with my cart are ok including payment. I have the same error for the search bar but it still work.

Jachobby

**Comment by go-sudo** [comment]
Hello @TGD001 

i was facing the same issue and fixed after upgrading my theme 

Regards

**Comment by TGD001** [comment]
Hi guys
Z.One Theme that I use has been modified in some parts, I also use a landing page and other added modules but I have always performed the upgrades without encountering any operating problems. Unfortunately, I can't take the whole site down to make an update. I will keep the current one (1.7.7.8) waiting for a new release to be released that corrects all these errors.

**Comment by go-sudo** [comment]
Hi @TGD001 the theme Z.ONE is not yes compatible with 1.7.7.8 as you can see on addon marketplace or here https://best.aonetemplate.com/documentation/

**Comment by TGD001** [comment]
> 
> 
> Hi @TGD001 the theme Z.ONE is not yes compatible with 1.7.7.8 as you can see on addon marketplace or here https://best.aonetemplate.com/documentation/

Sure, but as I said, mine is heavily modified. It would mean having to start the whole project all over again. Also I would have to pay it again, I don't understand why I should be forced to pay more money to upgrade.

**Comment by go-sudo** [comment]
Hello @TGD001 

You should work on ovverides to save your work and avoid to be losted after upgrading otherwise you must contact the dev them 

I hop you will find a solution soon
regards

**Comment by florine2623** [comment]
Hello @TGD001 ,

I did an upgrade from PS 1.7.7.8 to PS 1.7.8.0, the upgrade went well :
<img width="1206" alt="Screenshot 2021-10-12 at 10 49 41" src="https://user-images.githubusercontent.com/16019289/136924985-903507da-e928-412a-955f-8ab02a0f94e7.png">

The search bar is functioning :
<img width="1035" alt="Screenshot 2021-10-12 at 10 57 35" src="https://user-images.githubusercontent.com/16019289/136925266-774f924d-0d3a-4e8f-960c-f0ec46683385.png">

I can add product to my cart :
https://watch.screencastify.com/v/9R1aaMmyYAosRc7eCdxE

As @go-sudo said, if you have many overrides on your template + it is not compatible with PS 1.7.7.8, you should use another template, or contact the developer so they can upgrade it according to latest version of PS.

Thanks!
