### ISSUE TITLE
Hide category from search results

### ISSUE THREAD

**Issue by Gaja-A** [PrestaShop/PrestaShop#26216]
Hi,

_Prestashop version: **1.7.7.3**_

Is there a way to hide certain category products in prestashop search results?

Thanks in advance for your help.

Regards,
Gaja

**Comment by florine2623** [comment]
Hello @Gaja-A ,

In BO > Shop Parameters > Search :
<img width="1225" alt="Screenshot 2021-10-12 at 15 55 02" src="https://user-images.githubusercontent.com/16019289/136969788-b311a76f-fd49-42fd-8f26-1e93c33eaeef.png">

Is this what you mean ?

**Comment by Gaja-A** [comment]
Hi @florine2623 ,

Thanks for your reply.

I tried your method. I changed to 0 and re-build the index. But still it doesn't work.

In fact, I need to hide the products from certain category.

Ex: I have a category "Already sold". So if I search for the product name that exists in this category, then it should not be displayed in the search results.

Regards,
Gaja

**Comment by florine2623** [comment]
It is not possible to choose a specific category and decide to not show the product in the search result.
But you can disable the products from your BO if you want them to not show in the FO :
<img width="1211" alt="Screenshot 2021-10-12 at 17 04 47" src="https://user-images.githubusercontent.com/16019289/136981566-d421fdba-3e35-480c-8c8b-081a466c3f3f.png">

**Comment by Gaja-A** [comment]
Yes, but the problem is that I have a "Already sold" category link to display in the footer. So I want to display the products in FO expect in the search results.

I have tried some conditions in TPL which removes the product but the alignment is not good.
![image](https://user-images.githubusercontent.com/51961329/136986761-f69365e5-3fac-4d38-92cb-74da2cb94dad.png)

PS. It displays the products from other categories after page 10 (in the pagination).

**Comment by florine2623** [comment]
I will check with product-team directly.
Please stay tuned

**Comment by florine2623** [comment]
ping @PrestaShop/product-team ,

Is it possible natively to hide all products from one category from the search, but not from the list of product in BO ?

**Comment by hibatallahAouadni** [comment]
Hello @Gaja-A 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by Gaja-A** [comment]
Hi @hibatallahAouadni ,

Ok but I tried to display the sold out products at the bottom of the search results.
In BO - Products - Pagination - I have sorted by Quantity and selected descending in the dropdown list. But it doesn't change anything in the front.

It works on category page but not on search results*

![image](https://user-images.githubusercontent.com/51961329/138675031-12aa748d-322d-48f7-a77a-7ff3b1429862.png)

How can I solve this problem ?

Regards,
Gaja

**Comment by Gaja-A** [comment]
Hi @hibatallahAouadni ,

I solved the problem by overriding the Search.php file. Please ignore my previous message.

Regards,
Gaja

**Comment by MatShir** [comment]
I guess you could also use the visibility feature on the option tab of the product page. 
<img width="701" alt="Capture d’écran 2021-10-27 à 11 55 08" src="https://user-images.githubusercontent.com/43613217/139043568-c241da13-4eb3-4a2e-8c49-eae139b45558.png">
