### ISSUE TITLE
Twig service unavailable in getContent() method of base class

### ISSUE THREAD

**Issue by MageParts** [PrestaShop/PrestaShop#26219]
#### Describe the bug

Got a module class which extends **PaymentModule**, tried the following within the **getContent** method:

$this->get('twig')->render('@Modules/.......whatever.twig')

Got an error that the service didn't exist. Fixed by using:

PrestaShop\PrestaShop\Adapter\SymfonyContainer::getInstance()->get('twig')->render('........');

instead.

Seems to me this is a bug, but maybe I'm not understanding how to use this properly? What documentation I found was very brief on the subject.

#### Expected behavior

Template should render.

#### Additional information

* PrestaShop version: 1.7.7.8
* PHP version: 7.3.31

**Comment by florine2623** [comment]
Hello @MageParts ,

What module is it about ?
Could you share the steps to reproduce the issue ?

Thanks

**Comment by florine2623** [comment]
Hello,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
