### ISSUE TITLE
Wrong number of parameters in method getSimpleAddresses from class Customer in class CheckoutSession

### ISSUE THREAD

**Issue by christophe-rouille** [PrestaShop/PrestaShop#26212]
#### Describe the bug

In method `getCustomerAddressesCount` of class `CheckoutSession`, the call of method `getSimpleAddresses` from class `Customer` has a wrong number of parameters

For info, I met this issue because for a specific need, I had to override method `getSimpleAddresses` in class `Customer` and i had to add an argument to it but it didn't work due to this wrong call

#### Expected behavior

Both methods need to have same number of parameters

#### Steps to Reproduce

1. Check the method `getSimpleAddresses` in class [Customer ](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/classes/Customer.php#L677) -> Only one argument
2. Compare with its call in method `getCustomerAddressesCount` of class [CheckoutSession](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/classes/checkout/CheckoutSession.php#L72) -> Two arguments
3. See error > not same number of parameters

**Screenshots**

![image](https://user-images.githubusercontent.com/23308427/137113634-b3f1076d-5a4e-4203-a5d5-1dc603f2e5e0.png)

![image](https://user-images.githubusercontent.com/23308427/137113759-09c8789f-95c1-45db-88c4-e2a7ab8abf61.png)

#### Additional information

* PrestaShop version: At least 1.7
* PHP version: All

**Comment by florine2623** [comment]
Hello @christophe-rouille ,

What are the steps to reproduce the issue ?

Thanks

**Comment by christophe-rouille** [comment]
look method getSimpleAddresses declaration in class [Customer](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/classes/Customer.php#L677)
-> Only one argument

and compare with its call in method getCustomerAddressesCount of class [CheckoutSession](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/classes/checkout/CheckoutSession.php#L72)
-> Two arguments

**Comment by florine2623** [comment]
ping @PrestaShop/prestashop-core-developers ,

Could you please help me answer this ?
Thanks!

**Comment by atomiix** [comment]
@florine2623 @christophe-rouille is right, there is an extra argument that should be removed ;)

**Comment by Progi1984** [comment]
@christophe-rouille will work on this bug (he want it as first contribution :+1:).
