### ISSUE TITLE
The natif cross selling module is not working on 1.7.7.2

### ISSUE THREAD

**Issue by sextoysunivers** [PrestaShop/PrestaShop#26226]
#### Describe the bug

The natif cross selling module is not working on 1.7.7.2

#### Expected behavior

To show cross selling products with or without prices

#### Steps to Reproduce

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @sextoysunivers 

Could you please create an order pushing Product A and Product B with payment accepted as status. Then, check again the Product A, you will see Product B is well displayed.
Please check and feedback.

Thanks!
