### ISSUE TITLE
How to add correctely external JS to 1.7.8.0

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#26224]
Hello 

I was using this code on PS 1.7.7.8 in the file httpdocs/override/classes/controller/FrontController.php
and after upgrading i can't see the files link in the head of website and I'm getting errors in console log, is there any change to make on PS 1.7.8.0 to make it work again 

```

**Comment by hibatallahAouadni** [comment]
Hello @go-sudo 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **YOU MUST FOLLOW AND RESPECT THE PROVIDED TEMPLATE TO SUBMIT A COMPLETE BUG REPORT**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
