### ISSUE TITLE
no link is working after upgrade to 1.7.8

### ISSUE THREAD

**Issue by DPStudioGR** [PrestaShop/PrestaShop#26229]
#### After upgrade to 1.7.8 no menu, link, product link is clickable/working.

Last night i upgraded my eshop (https://stampa-stampa.com) from 1.7.7 to 1.7.8 and today i got a call from a customer that my eshop is not working. After me checking i noticed that other than home page loading nothing else is working like menu, products and any link and button in general. 
I did check with PHP 7.3 and 7.4 and the problem stays the same..

To reproduce the issue just visit https://stampa-stampa.com and try to click on a product or link

1. Go to 'https://stampa-stampa.com'
2. Click on menu , product or any link.
3. No link is clickable or working

* PrestaShop version: 1.7.8
* PHP version: 7.4.24

**Comment by hibatallahAouadni** [comment]
Hello @Stampa-Stampa 

You have an issue with this module:

![image](https://user-images.githubusercontent.com/23308427/137111460-ef7afc50-b215-4679-94cf-378a19571397.png)

You need to check your log to figure out the problem occured while upgrading :wink: 

Sorry, but I have to close the issue cause we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
