### ISSUE TITLE
order_confirmation error display PS 1.7.7.7

### ISSUE THREAD

**Issue by Dan32b** [PrestaShop/PrestaShop#26222]
#### Order_confirmation template error display

If you open order_conf template in classic theme core email, you tried to change data  in HTML or <> source code. After saving process. Order Confirmation Email is sending with bug in display. Content of buying are anarchic displaying. ## you can see issue without modification of the HTML file, only just by clicking SAVE.
 
Has anyone encountered the issue and fix it?

1. Go to translations/body/classic/language/modify 
2. Click on Core emails/order_conf
3. Open it in HTML file and Save it without modification of the file !
4. See error: bug in display content 

**Screenshots**
1 - no modification = no bug
2 = only click on save button = bug on display

<img width="1597" alt="Translations" src="https://user-images.githubusercontent.com/92400511/137030489-ebfc4025-19f9-43d8-b6b1-fbfa55237c92.png">

<img width="530" alt="no modification = no bug" src="https://user-images.githubusercontent.com/92400511/137027557-abac2788-4ee1-4356-a53e-67331dd49ff0.png">

<img width="474" alt="save button push but no modification = bug" src="https://user-images.githubusercontent.com/92400511/137027125-f0207d27-85cc-4a11-a3e0-d06f0e0c4682.png">

#### Additional information
* PrestaShop version: 1.7.7.7 + 1.7.7.8
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @Dan32b 

Thanks for respecting the template :clap: 
We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #21630. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #21630
