### ISSUE TITLE
Accented characters are replaced with ? on invoices

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#26233]
#### Steps to Reproduce

1. Install develop in English.
2. Go to order statuses -> Waiting for check payment, enable invoice generation for this status.
3. Make an order, enter **Daniel Hlaváček** as a customer.
4. Go see generated invoice in BO.

**Screenshots**

![chars](https://user-images.githubusercontent.com/6097524/137129526-c35cfa51-5c30-43a0-835f-62c120763ed1.JPG)

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

I didn't manage to reproduce the issue with PS1780 and develop, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/137139711-c2e39b5f-3fd2-48b7-b987-41f8b166b628.png)

Is your develop branch updated?
Please check and feedback.

Thanks!

**Comment by Hlavtox** [comment]
@hibatallahAouadni Hi! Develop updated, still the same problem. :(

![localhost_prestashop_admin-dev_index php_improve_international_languages___token=1YPNws-6HUZ0x1caM5K1Q88xaK-qzzmciFiEyO8wzWE](https://user-images.githubusercontent.com/6097524/137141932-c7e0b4fd-97f0-4dd8-9a08-a13cda305499.png)

![localhost_prestashop_admin-dev_index php_improve_international_localization___token=1YPNws-6HUZ0x1caM5K1Q88xaK-qzzmciFiEyO8wzWE](https://user-images.githubusercontent.com/6097524/137141927-3881108e-82b0-46e3-be0b-ba81f6f130c8.png)

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

I update my develop and still can't manage to reproduce the issue :confused: 
Could you please check if you encounter this issue if you change the order status to **payment accepted**.
Please check and feedback.

THanks!

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Even when I install my develop with Čeština (Czech), I still didn't manage to reproduce the issue:

https://watch.screencastify.com/v/d1LIeYlHyHWCVBX0QBEJ

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a module problem.

We will close this issue.

Thanks!
