### ISSUE TITLE
Customer reassurance Module not working

### ISSUE THREAD

**Issue by suplies** [PrestaShop/PrestaShop#26232]
Customer reassurance Module not working i cant change the text details

**Comment by hibatallahAouadni** [comment]
Hello @suplies 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: it works perfectly (PS1.7.8.0), I just "toutou" and it's well displayed:

![image](https://user-images.githubusercontent.com/23308427/137115264-22d9ddd3-4abd-4d7f-a70a-07cd0c8f76f9.png)
![image](https://user-images.githubusercontent.com/23308427/137115276-4c4c065a-69cd-44c4-842f-4e1d66a4febe.png)

Thanks!

**Comment by suplies** [comment]
my dear 
![Untitled](https://user-images.githubusercontent.com/92435655/137304409-b67a1fac-d8d6-423d-b8e9-8a94e0c1c481.jpg)

**Comment by suplies** [comment]
there is no box for text something

**Comment by hibatallahAouadni** [comment]
What's your PS version and Customer reassurance module version?

**Comment by suplies** [comment]
Customer Reassurance
v5.0.0 - by

ps 1.7.8.0
