### ISSUE TITLE
PS 1.7.8.0 Error compiling classic theme assets with Windows 10

### ISSUE THREAD

**Issue by Codencode** [PrestaShop/PrestaShop#26248]
#### Describe the bug
When I try to compile the assets of the "classic" theme, the system gives an error.

If I run the command: 
**npm run build**

I get the following error:
**"NODE_ENV" non è riconosciuto come comando interno o esterno**
I solved it by replacing in the package.json file
`"build": "NODE_ENV=production webpack --progress --colors --debug --display-chunks",`
with
`"build": "webpack --progress --colors --debug --display-chunks --mode=production",`

But I still have problems, in fact executing the command:
**npm run build**
I get the following error:
**Can't resolve '. \ Tether.js' ...**

I attach the screenshot with the complete error

P.S.
I tried with ubuntu and it works

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/2463965/137300528-12ddfd36-d04c-4345-8c5a-c088e0454c26.png)

#### Additional information
* PrestaShop version: 1.7.8.0
* PHP: all
* SO: Windows 10

**Comment by hibatallahAouadni** [comment]
Hello @Codencode 

> I tried with ubuntu and it works

Indeed, it works :smile: 
Ping @NeOMakinG any idea about this issue? please :pray: 

Thanks in advance!

**Comment by Hlavtox** [comment]
@NeOMakinG Exactly what it does to me :-)

**Comment by NeOMakinG** [comment]
> @NeOMakinG Exactly what it does to me :-)

Yeah, I think I know, but I need to investigate it and I'm off tomorrow, gonna take a look on Monday @Codencode 🙏

**Comment by Codencode** [comment]
I tried to download the _dev folder of the classic theme again and I noticed that node modules have been updated.
The first error (the one related to **"NODE_ENV" non è riconosciuto come comando interno o esterno**) is always present, but the other one no longer occurs.
So fixes were made that fixed the second problem, while the first one remains, just replace in the package.json file
`"build": "NODE_ENV = production webpack --progress --colors --debug --display-chunks",`
with
`"build": "webpack --progress --colors --debug --display-chunks --mode = production",`

Thank you all

**Comment by Codencode** [comment]
I have compared the package.json file of versions **1.7.8.0** and **develop** and they are different

https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/themes/classic/_dev/package.json
https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/_dev/package.json

The theme.js file is also different
https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/themes/classic/_dev/js/theme.js
https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/_dev/js/theme.js

**Comment by templatin** [comment]
I solved it but not sure if its the correct method.

- Open this file: root/themes/YOUR_THEME/_dev/webpack.config.js
- Add below code after the closing of `output` brackets.

```
resolve: {
    preferRelative: true,
},
```

![Untitled-1](https://user-images.githubusercontent.com/3615808/137585851-e41a4120-f89f-4af7-b7b8-36212d5ff99b.jpg)

**Comment by NeOMakinG** [comment]
Basically, when we work on develop, we update packages and other things, while 1.7.8 doesn't get these updates, this is why these files can be different.

Don't use the package.json of the develop branch if your prestashop version is on 1.7.8, it can lead to a lot of problems

**Comment by NeOMakinG** [comment]
> I solved it but not sure if its the correct method.
> 
> * Open this file: root/themes/YOUR_THEME/_dev/webpack.config.js
> * Add below code after the closing of `output` brackets.
> 
> ```
> resolve: {
>     preferRelative: true,
> },
> ```
> 
> ![Untitled-1](https://user-images.githubusercontent.com/3615808/137585851-e41a4120-f89f-4af7-b7b8-36212d5ff99b.jpg)

Seems like it's a viable solution, I've nothing against it!

Would you mind creating a PR for this? :)

**Comment by templatin** [comment]
> Would you mind creating a PR for this? :)

Okay, btw which base branch (develop or 1.7.8.x) should I target for PR?

**Comment by NeOMakinG** [comment]
> > Would you mind creating a PR for this? :)
> 
> Okay, btw which base branch (develop or 1.7.8.x) should I target for PR?

1.7.8.x is fine to me, as it's blocking building this version on windows it should be inside the path version
