### ISSUE TITLE
Text fields set to "hidden" in GDPR module

### ISSUE THREAD

**Issue by Magnusvb** [PrestaShop/PrestaShop#26244]
#### Describe the bug

After updating to 1.7.8 (from 1.7.7) all the text fields in the settings for the GDPR module have a local style of "visibility: hidden".

`<textarea class="autoload_rte" name="psgdpr_customer_form_2" text="" rows="4" cols="80" id="psgdpr_customer_form_2" style="visibility: hidden;">I agree to the terms and conditions and the privacy policy</textarea>`

#### Expected behavior

To be able to add / change the text in the text fields

#### Steps to Reproduce

1. Go to 'GDPR module'
2. Click on 'Consent checkbox customization'
3. See error

**Screenshots**
![gdpr](https://user-images.githubusercontent.com/99280/137258348-5bd89abc-3580-476a-b011-f3a9339a7eef.png)

#### Additional information

* PrestaShop version: 1.7.8
* GDPR version: 1.2.1
* PHP version: 7.1.33

**Comment by hibatallahAouadni** [comment]
Hello @Magnusvb 

I didn't manage to reproduce the issue with PS1775 upgraded to PS1780 and PS1.7.8.0 (fresh install), see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/137275577-a8028b9d-d06e-4079-b3d4-ae7ca209ec2a.png)

Are you sure that your PS version is 1.7.8.0? cause we change the style of radio buttons :confused: 
Please check and feedback.

Thanks!

**Comment by Magnusvb** [comment]
Hey!
Yes, the PS version is 1.7.8.0. 

The first try to upgrade to 1.7.8 (using 1-click upgrade) failed with a "Maximum execution time of 30 seconds exceeded". So I rolled back from a backup of the database and the files (second attempt succeeded).

Strange that I still have the old style radio button? Is there a way to "force" a new upgrade to 1.7.8 (manuell upgrade is such a mess ;)?

/ Magnus

![Screenshot 2021-10-16 at 07 31 01](https://user-images.githubusercontent.com/99280/137575267-d4a866f6-59a0-4c17-b8ed-1460febd249d.png)
s?

**Comment by florine2623** [comment]
Hello @Magnusvb ,

I can't reproduce your issue either with PS 1.7.8.0.
<img width="1434" alt="Screenshot 2021-10-18 at 12 00 08" src="https://user-images.githubusercontent.com/16019289/137710237-eb0f1690-ce46-40cf-bdfa-5c11315deec8.png">
Could you uninstall and reinstall the GDPR module ?
Thanks!

**Comment by Magnusvb** [comment]
Hey @florine2623 
There must be a ghost in my machine. I did another upgrade (from backup files and db - 1.7.7.5). But still the same issue: hidden textfields and old style radio buttons. 

How do I reinstall only the GDPR module? If I download Prestashop, extract the zip, there are no "psgdpr" module. I tried by download the files from Github. But now I get an error when trying to configure it (see image).

Now I feel lost.

Side note: Switched to Classic theme and there are no longer any comments on the product page. I might have to stay on 1.7.7 for a while.
![Screenshot 2021-10-18 at 13 37 30](https://user-images.githubusercontent.com/99280/137723420-c106b717-dfb4-44b9-b54b-b542063ec7a6.png)
.

**Comment by florine2623** [comment]
To reinstall module GDPR :
<img width="1074" alt="Screenshot 2021-10-18 at 14 04 10" src="https://user-images.githubusercontent.com/16019289/137726944-2547a553-6d3e-44eb-9721-255479f54bfc.png">

Then, go to module catalog and install the GDPR module :
<img width="250" alt="Screenshot 2021-10-18 at 14 05 33" src="https://user-images.githubusercontent.com/16019289/137726963-62dc7cf1-0f2b-4103-accf-a4f690cacee4.png">

**Comment by Magnusvb** [comment]
Thanks @florine2623 
(sometimes the solution is too easy to see). But, sorry to say, still the same issue. I will reinstall a new, clean 1.7.8 and see if that works. The boring bit is to also update my custom theme to match the updated Classic theme.

**Comment by florine2623** [comment]
Okay, let me know how the fresh install of 1.7.8 goes and if GDPR module is OK.

Waiting for your feedback.

**Comment by starqus** [comment]
> Okay, let me know how the fresh install of 1.7.8 goes and if GDPR module is OK.
> 
> Waiting for your feedback.

I did a clean install but the problem persists. 
The problem was solved when I changed the php version to 7.1.

**Comment by hibatallahAouadni** [comment]
@LordIndustry Glad to hear :tada:

**Comment by d0niek** [comment]
I have the same issue. All textarea fields are hidden.

I've upgraded from `1.7.6.8` to `1.7.8` by cli autoupgrade and tested with php `7.1` and `7.3`.

Clear cache, Ctrl+r in browser didn't help.

**Comment by d0niek** [comment]
Resolved. Hard delete **var/cache/\*** and many `Ctrl+R` in browser to get working fields.

Prestashop **1.7.8**, php **7.3.24**

**Comment by Magnusvb** [comment]
Great @d0niek 
Solved the problem for me too.
For some reason, I had also a folder called "pro_" inside var/cache. Maybe some leftover from the update?

**Comment by florine2623** [comment]
Hello all,

As the issue is solved by clearing the cache, i will close this issue.

Thanks!
