### ISSUE TITLE
ps_customtext not visible Text block

### ISSUE THREAD

**Issue by jmm19** [PrestaShop/PrestaShop#26249]
#### Describe the bug

Text block in CMC modul ps_customtext is not visible in Admin

#### Expected behavior

What to change in code or CSS please?

#### Steps to Reproduce

**Screenshots**

![cms missing text block](https://user-images.githubusercontent.com/62876014/137315421-e63f47ef-94d8-4593-8468-0a361e72f807.jpg)

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.4

**Comment by kpodemski** [comment]
Have you tried in the incognito mode? or clear the browser cache?

**Comment by jmm19** [comment]
It is ok in icognito mode. Thank you.
