### ISSUE TITLE
1.7.8.0 Closing a cart does not work

### ISSUE THREAD

**Issue by JacHOBBY** [PrestaShop/PrestaShop#26257]
When closing the cart at the very last step where you normally press the green button ''buy whit obligation of payment'', this step does not work.
In order to have the cart process I put my cursor back into the credit card number box at the end of the number and press enter to have the process to complete.

#### Expected behavior
When pressing the button ''buy with obligation of  payment'' the transaction should go trough.

#### Steps to Reproduce

1. put an item in the cart
2. complete the process to buy
3. At the and try to press th button ''buy with obligation of payment'' 
4. See error nothing happen
5. put the cursor at the end of the credit card number and press enter.
6. The transaction go trough

#### Additional information

Tested whit different browser whit same results. I have also tried without any cache activated still not working.

* PrestaShop version: 1.7.8.0
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @JacHOBBY,

I did not manage to reproduce the issue with the PS1780 fresh install.
I attached a screen record
https://watch.screencastify.com/v/ClPGTs8Ei7wPSOLOksfm

Did you use a fresh install?
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:

 - server setup and configuration
 - PrestaShop version (source: a fresh install or an upgrade from a previous version?)
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/


Thanks!

**Comment by DanSilva926** [comment]
I have the same problem

**Comment by hibatallahAouadni** [comment]
@DanSilva926 could you please provide more infos :pray:

**Comment by hibatallahAouadni** [comment]
Hello @JacHOBBY 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by DanSilva926** [comment]
> @ DanSilva926 poderia fornecer mais informações🙏
@hibatallahAouadni 


I replaced the core.js file from version 1.7.7.8 and the checkout was working

**Comment by hibatallahAouadni** [comment]
Hello @DanSilva926 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #26274. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #26274
