### ISSUE TITLE
1.7.8.0 - WebService /products - Error 500

### ISSUE THREAD

**Issue by ruibarbosa711** [PrestaShop/PrestaShop#26258]
After upgrading to version 1.7.8.0, the webservice started returning error 500  in products.

Return message from request GET https://[API_KEY]@[url]/api/products?schema=blank :
`<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <errors>
        <error>
            <code>
                <![CDATA[5]]>
            </code>
            <message>
                <![CDATA[[PHP Notice #8] Trying to access array offset on value of type null ([...]/classes/webservice/WebserviceOutputBuilder.php, line 716)]]>
            </message>
        </error>
        <error>`

Return message from request POST https://[API_KEY]@[url]/api/products :
`<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <errors>
        <error>
            <code>
                <![CDATA[5]]>
            </code>
            <message>
                <![CDATA[[PHP Notice #8] Trying to access array offset on value of type bool ([...]/classes/Product.php, line 7170)]]>
            </message>
        </error>
    </errors>
</prestashop>`

* PrestaShop version: 1.7.8.0
* PHP version: 7.4

**Comment by khouloudbelguith** [comment]
Hi @ruibarbosa711,

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you!

**Comment by ruibarbosa711** [comment]
Hello,  @khouloudbelguith 

after your answer, I tried to execute the requests in Postman with the shop in "debug mode", and it worked fine. 
But when I disable the debug mode,  I get the responses:

GET https://[API_KEY]@[URL]/api/products?schema=blank
[products_get_response.txt](https://github.com/PrestaShop/PrestaShop/files/7353064/products_get_response.txt)

POST https://[API_KEY]@[URL]/api/products
Body Content: 
[product_boy_content.txt](https://github.com/PrestaShop/PrestaShop/files/7353074/product_boy_content.txt)
Response:
[products_post_response.txt](https://github.com/PrestaShop/PrestaShop/files/7353063/products_post_response.txt)

Error Log:
[WebService_API_Error.txt](https://github.com/PrestaShop/PrestaShop/files/7353091/WebService_API_Error.txt)

Upgrade Log to version 1.7.8.0:
[upgrade_log.txt](https://github.com/PrestaShop/PrestaShop/files/7353133/upgrade_log.txt)

I hope this information, can help finding this issue.

Best regards,

**Comment by khouloudbelguith** [comment]
@ruibarbosa711, 1780 fresh install 
![image](https://user-images.githubusercontent.com/16067358/137519900-7bb07bde-fc9e-4c48-adbf-a3632a8c5dba.png)

1780 after an upgrade from PS1778 using the 1-click upgrade v4.12.0
![image](https://user-images.githubusercontent.com/16067358/137520099-0947e6cd-3308-4545-9ad4-c2f23213742c.png)


The debug mode is disabled in all cases.

Thanks!
