### ISSUE TITLE
Upgrading to Prestashop 1.7.8 from 1.7.7, using custom theme, the theme was reset to classic

### ISSUE THREAD

**Issue by roja45** [PrestaShop/PrestaShop#26256]
#### Describe the bug

Upgraded to Prestashop 1.7.8 on an installation with a custom theme.  The theme was reset to the classic theme.  Reverting to the custom theme, all the hook positions had been reset.

#### Expected behavior

If upgrading, it shouldn't be resetting the theme, this leaves the installation unusable, and a big task to reattach all the hooks (and difficult if you don't know which hooks those modules should be using)

#### Steps to Reproduce

1. On an installtion with a custom theme, upgrade to 1.7.8
2. Theme will be reset to classic

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: 7.4

**Comment by hibatallahAouadni** [comment]
Hello @roja45 

Before upgrading, can you remember if this option is enabled or disabled?

![image](https://user-images.githubusercontent.com/23308427/137347044-bc669d54-cac9-4705-a584-8a9bab8fce67.png)

Cause if it was enabled, then it's normal that your theme was reset to the classic theme.
Please check and feedback.

Thanks!

**Comment by roja45** [comment]
![image](https://user-images.githubusercontent.com/19314911/137352333-232476a5-a4fe-451f-8997-1762d7083cff.png)

I hadn't changed this setting, and I assume No is the default.

**Comment by khouloudbelguith** [comment]
Hi @roja45,

I did not manage to reproduce the issue with PS1780 after an upgrade from PS1778 using the 1-click upgrade v4.12.0.
I attached a screen record
https://watch.screencastify.com/v/7pq6GhDmA6OUxror0NyY
Could you please retry the upgrade and recheck following these steps:
1. Install the 1-click upgrade
2. Click on configure
3. In the `UPGRADE OPTIONS` verify that `Switch to the default theme` is disabled and click on `Save` 
![image](https://user-images.githubusercontent.com/16067358/137478271-f9511b59-39b5-4b14-8d09-1d6f247fc460.png)
4. Do the upgrade

Thanks to check and feedback.

**Comment by hibatallahAouadni** [comment]
Hello @roja45 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
