### ISSUE TITLE
BO - the language dropdown is not well displayed when resizing the window 

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#26252]
#### Describe the bug

when we resize the window the language dropdown is not well displayed

#### Expected behavior

resize the window the language dropdown should be well displayed

#### Steps to Reproduce

1. Go to catalog >Attributes & Features > Add new attribute > resize window (the language dropdown is not ok)
2. Go to shop parameters> customer settibngs> Titles> add new social title

**Screenshots**
![image](https://user-images.githubusercontent.com/89604350/137318167-b3d65a21-d8ef-4466-b7a3-37381d489e12.png)
![image](https://user-images.githubusercontent.com/89604350/137318374-33f31432-e3cf-4311-af09-c69e8638023d.png)

The issue is not present in 1.7.8.0

#### Additional information

* PrestaShop version: develop/1.7.8.x
* PHP version: 7.3

**Comment by Progi1984** [comment]
Fixed in #26328 by @marwachelly
