### ISSUE TITLE
CLI command for changing debug mode on and off and getting the current state

### ISSUE THREAD

**Issue by tswfi** [PrestaShop/PrestaShop#26263]
#### Is your feature request related to a problem?

In #26182 @ytilotti noticed that #26211 is a duplicate and while double checking I read the issue wrong and for some reason thought about debug mode :)

Debug mode is saved differently from configuration values and it is not shop dependent so it should have its own command.

#### Describe the solution you'd like

Get the current state of debug mode

```
bin/console prestashop:debug 
```

set debug mode on

```
bin/console prestashop:debug true
```

set debug mode off

```
bin/console prestashop:debug false
```

the parameter should be evaluated with `FILTER_VALIDATE_BOOLEAN` so that it understands "truthiness"

#### Alternatives you've considered

Special case for the config command that knows how to handle debug setting.
+ one place to set them
- debug is not shop dependant
- requires special logic in the command
- if debug is its own command it is easier to find it from commands listing

**Comment by khouloudbelguith** [comment]
Hi @tswfi,

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thanks!

**Comment by ytilotti** [comment]
There is a CQRS @tswfi to switching debug mode [`PrestaShop\PrestaShop\Core\Domain\Configuration\Command\SwitchDebugModeCommand`](https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Domain/Configuration/Command/SwitchDebugModeCommand.php) and use Adapter [`PrestaShop\PrestaShop\Adapter\Debug\DebugMode`](https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Debug/DebugMode.php) via [`PrestaShop\PrestaShop\Adapter\Configuration\CommandHandler\SwitchDebugModeHandler`](https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Configuration/CommandHandler/SwitchDebugModeHandler.php).
We can use it to create a CLI command.

**Comment by tswfi** [comment]
@ytilotti yup, I saw that also.
