### ISSUE TITLE
webservice api do not trigger email/stock alerts on stock available

### ISSUE THREAD

**Issue by tropicaldev** [PrestaShop/PrestaShop#26260]
webservice api do not trigger email/stock alerts on stock available

Prestashop module "Mail Alerts" is installed and configured to send costumer notifications on "Product availability"
Email alerts are triggered when stocks are updated in the store interface (as expected)
Email alerts are not triggered when stocks are updated from the webservice api (not expected)

PrestaShop version: 1.7.6.5

**Comment by khouloudbelguith** [comment]
Hi @tropicaldev,

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you!
