### ISSUE TITLE
Unable to save a product with customization field

### ISSUE THREAD

**Issue by DPStudioGR** [PrestaShop/PrestaShop#26270]
![screen 1](https://user-images.githubusercontent.com/53015902/137531365-6f783ca6-2f12-405f-bc79-5e08d3c166d7.jpg)

#### Expected behavior

Normally the product would save its state and a customization field (file upload or text add) would be availbale for the customer.

I am using..

* PrestaShop version: 1.7.8
* PHP version: 7.4   but i have the same issue with 7.3 also
moreover i have enabled debuger and have added a 400 error i can find..

**Comment by DPStudioGR** [comment]
I must add that Products without customization field are saving just fine even with many combinations.

**Comment by florine2623** [comment]
Hello @Stampa-Stampa ,

I can't reproduce your issue, please check my screen record :
https://watch.screencastify.com/v/80QG1RMvzkudTHEDkaYU

Tested on PS 1.7.8, PHP 7.3 and PHP 7.4.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
