### ISSUE TITLE
little problem with saving the product with combinations

### ISSUE THREAD

**Issue by patrykcode** [PrestaShop/PrestaShop#26276]
https://github.com/PrestaShop/PrestaShop/blob/7207005c67452f82876a756df7cabd4a6ca58cab/src/Adapter/Product/AdminProductWrapper.php#L152

**Comment by patrykcode** [comment]
adding in front of a variable (float) solves the problem
`(float) $combinationValues['attribute_ecotax'] / (1 + Tax::getProductEcotaxRate() / 100),`

**Comment by florine2623** [comment]
Hello @patrykcode ,

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
