### ISSUE TITLE
Marketing >Facebook Error

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#26278]
#### Describe the bug

Wrong characters in Spanish lenguaje

#### Steps to Reproduce

1. Go to Marketing
2. Click on Facebook
3. See error

**Screenshots**

https://prnt.sc/1wfuxdh

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.3

**Comment by florine2623** [comment]
Hello @alfonsolr09 ,

Thanks for the report. You can contact the support directly from your BO.
<img width="1226" alt="Screenshot 2021-10-18 at 10 07 01" src="https://user-images.githubusercontent.com/16019289/137692529-13b244d5-47af-48e1-9bbb-3d76609232b8.png"> 
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. So I'll close your issue.
