### ISSUE TITLE
Viewed Products Module not showing add Cart button

### ISSUE THREAD

**Issue by Div2021** [PrestaShop/PrestaShop#26284]
#### Describe the bug

I installed the module and everything works fine except for the "Add Cart" button. It is only showed in the first product in the module.

#### Expected behavior

It would be great to have the Add to Cart button in all recently viewed products

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.3.29
* Theme: Warehouse

**Comment by florine2623** [comment]
Hello @Div2021 ,

This is a request for the developers of Warehouse template. Not PrestaShop.
So please contact directly the developers of your Warehouse Template.

Thanks
