### ISSUE TITLE
Prestashop 1.7.8 does not refresh the quantity in the cart

### ISSUE THREAD

**Issue by bsylwek** [PrestaShop/PrestaShop#26286]
#### Describe the bug

Prestashop 1.7.8 does not refresh the quantity in the cart. When I press refresh F5 it changes to the correct value. In previous version Prestashop 1.7.7.8, the quantity is updated correctly automatically. I have a Sonice template from Hiddentechies. What could be the reason? Is it related to the template? My page https://www.wholesale.jksweaters.com/

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Add the product to the cart https://www.wholesale.jksweaters.com
2. Click on show cart or preceded to checkout
3. Change the number of products in the cart. You will see that the total amount will not change. Only after clicking refresh or pressing F5 will the correct amount appear. What do you need to do to automatically appear without refreshing?

**Screenshots**

![obraz](https://user-images.githubusercontent.com/66308504/137720721-fff2f3bc-889f-47aa-ba79-72503d6a8113.png)

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: 7.4

**Comment by florine2623** [comment]
Hello @bsylwek ,

I can't reproduce your issue with PS 1.7.8.0. Please check my screen record :
https://watch.screencastify.com/v/kst4LIL7JBqnEny35dP0

Make sure your module Shopping Cart is configure like the following :
<img width="835" alt="Screenshot 2021-10-18 at 14 02 17" src="https://user-images.githubusercontent.com/16019289/137726528-5bbabf81-8a2b-47da-bda6-efe9971af5ab.png">

Thanks!

**Comment by bsylwek** [comment]
I have Ajax set to YES. Templates other than Classic are affected. See my description step by step. You can check it on my listed page above. What do I have to modify in the template to make it refresh automatically?
