### ISSUE TITLE
error with custom values ​​in product characteristics

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#26281]
#### Describe the bug

On product pagem.
When you add a custom value without selecting a feature, it is duplicated ad infinitum

#### Expected behavior

I think it should give an error when saving the product or not being able to write a value until you have selected a feature

#### Steps to Reproduce

1. Go to any product
2. Click on add feature
3. No select any in 'Select a feature' and no 'Select a value'.
4. Write a custom value (like 100)
5. Save product
6. Recharge the web.
7. See error, now there are two (duplicated)
8. If save again and recharge again, doubles again.

**Screenshots**

https://www.awesomescreenshot.com/video/5659628?key=5945c92cb7f7276df640d2f39615bc93

#### Additional information

* PrestaShop version: 1.7.7.8 and imagine in 1.7.8.0 too (i can't try it)
* PHP version: 7.3

**Comment by florine2623** [comment]
Hello @alfonsolr09 ,

Your issue is related to https://github.com/PrestaShop/PrestaShop/issues/16306
So I'll close it to avoid backlog.

Thanks !

**Comment by florine2623** [comment]
Duplicate of @https://github.com/PrestaShop/PrestaShop/issues/16306
