### ISSUE TITLE
Facet search by category doesn't display all products - it is fixed after refresh

### ISSUE THREAD

**Issue by Kamila-Piatkiewicz** [PrestaShop/PrestaShop#26280]
**Describe the bug**

I use facet search to enable filtering products by category. Recently I added new product to category "Orto" - it is configured the same way as others. When I use facet search to filter by category, the product is not on the list. When I refresh the page it is on the list. 

**Expected behavior**

Facet search finds all products from selected category without refresh.

**Steps to Reproduce**

- Open catalog with products
- Facet search displays (among other categories) Orto(6).
- When I select Orto checkbox, it changes to Orto(5) and display only 5 products, without the newest one, which also belongs to category. Order of the categories is mixed.
- After refreshing page I see again Orto(6) on facet search and all 6 products. Order of categories is correct again.
- I open catalog again and select category Begobano(4)
- Name changes to Begobano(5) and displays missing product from category Orto
- After refresh it is fixed.

I tried:

- change category of the product to Y and back to X
- clear cache in facet search module
- rebuild index in facet search module
- enable and disable cache in facet search module
- upgrade facet search module
- clear browser cache

**Screenshots**

![step1](https://user-images.githubusercontent.com/26796423/137644597-9d2b77fc-6d8d-4d37-bdc8-5dfc577e46b4.png)
![step2](https://user-images.githubusercontent.com/26796423/137644593-987822ad-6794-4243-8497-483852df6a6d.png)
![step3](https://user-images.githubusercontent.com/26796423/137644592-a5fe34b8-9f8f-4c7d-9fcf-3b8240efaff2.png)

**Additional information**

- facet search v3.7.1 
- Prestashop 1.7.4.4
- PHP 7.1.33
- [https://footmate.pl/sklep/23-katalog](url)

**Comment by florine2623** [comment]
Hello @Kamila-Piatkiewicz ,

I can't reproduce your issue in PS 1.7.8.0 and faceted_search v3.7.1 (refresh and no refresh give the same result) :
<img width="1101" alt="Screenshot 2021-10-18 at 11 19 16" src="https://user-images.githubusercontent.com/16019289/137704385-14ad4ffb-8447-4fac-966a-6300400996d5.png">
<img width="1097" alt="Screenshot 2021-10-18 at 11 21 14" src="https://user-images.githubusercontent.com/16019289/137704395-8e9515ab-e3be-4b74-aa60-c1991a8514f6.png">

Please check in faceted_search EPIC, if there's a bug that is similar to yours : https://github.com/PrestaShop/PrestaShop/issues/9684

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Kamila-Piatkiewicz 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
