### ISSUE TITLE
error with arrows on category tab (product)

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#26282]
#### Describe the bug

Arrows are bad when click on contract and expand

#### Steps to Reproduce

1. Go to any product on BO
2. Click on contract all or expand all
3. See error

**Screenshots**

https://www.awesomescreenshot.com/video/5659688?key=355be69bd29a4a929f7e0e30bb62c44d

#### Additional information

* PrestaShop version: 1.7.7.3; 1.7.7.8; 1.7.8.0
* PHP version: 7.3

**Comment by florine2623** [comment]
Hello @alfonsolr09 ,

I can't reproduce your issue with PS 1.7.8.0 :
<img width="275" alt="Screenshot 2021-10-18 at 09 42 45" src="https://user-images.githubusercontent.com/16019289/137688878-42845031-fd9d-4d24-8c47-9b3e037ae6bf.png">

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by alfonsolr09** [comment]
Try it on 1.7.7.8 please
