### ISSUE TITLE
I would like to hide subcategories from category block

### ISSUE THREAD

**Issue by murman001** [PrestaShop/PrestaShop#26283]
Helli Prestashop community,
I would like to know is there any way to hide subcategories from category block.
And is it possible to disable whole category block without dasabling categories, just block
![tempsnip](https://user-images.githubusercontent.com/92696974/137648753-2e362dfd-381e-4323-a2e3-ed17c7b97e4d.png)

**Comment by florine2623** [comment]
Hello @murman001 ,

This is how the Classic template is. I'll see with the Product Team if it can be improved.
In the meantime, you can use another template.

**Comment by florine2623** [comment]
ping @PrestaShop/product-team ,

What do you think of an improvement on Classic Template - add the possibility to hide the subcategories ?

**Comment by marionf** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/19895

**Comment by marionf** [comment]
Hello,

This issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/19895
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you!
