### ISSUE TITLE
Issue saving multiple checked categories in filters of Faceted Search Module

### ISSUE THREAD

**Issue by estudio-kintek** [PrestaShop/PrestaShop#26296]
Hi!

In the ps_facetedsearch module, editing a filter template, after checking multiple subcategories and save changes, not all of them are saved. I have to check again some subcategories and try to save them again.

There's no error displayed after that.

Is there anyone else having this issue?

**Expected behavior**:

- Check multiple categories and remain checked after saving the changes.

**Steps to reproduce the behavior**:

1. Go to 'ps_facetedsearch' module configuration.
2. Click on the "edit" option of a filter template.
3. Check multiple unchecked categories of the categories tree.
4. Scroll down and click de "save" button at the bottom of the page.
5. After saving process is complete, see the module configuration page.
6. Click on the "edit" option of a filter template again and confirm that not all the categories are still checked, so not all the changes have been saved.

**Video capture**: https://www.loom.com/share/45ebeccffb2f40d488b68e7e5b52f70d

**Additional information**

* PrestaShop version: 1.7.7.7
* ps_facetedsearch module version: 3.7.1
* PHP version: 7.2.34

**Comment by hibatallahAouadni** [comment]
Hello @estudio-kintek 

I didn't manage to reproduce the issue with PS1777, see the attached screen record below:

https://watch.screencastify.com/v/tZBNGZrY0ZegFUKyTImb

Please check and feedback.
Thanks!

**Comment by estudio-kintek** [comment]
Hello @hibatallahAouadni 

Thanks for your answer. As I see it works fine in your case.

We finnally found the reason of the problem and a solution that works great for us.

Here you are the post that gave us the answer: https://www.prestashop.com/forums/topic/1051753-facet-search-problem-fills-up-database-tables-ps_layered_filed_block-ps_guest-ps_connections/

**Comment by hibatallahAouadni** [comment]
Hello @estudio-kintek 

Glad to hear :tada: 
We will close this issue.

Thanks!
