### ISSUE TITLE
Product availability date bug

### ISSUE THREAD

**Issue by Renrhaf** [PrestaShop/PrestaShop#26298]
#### Describe the bug

The product availability date differs between product page and cart page.
It seems that the product availability date is not fetched from the product combination when it should be, in my opinion.

#### Expected behavior

To have the same availability date on the product page, and on the cart page.

#### Steps to Reproduce

1. Change "product-add-to-cart.tpl" and "cart-detailed-product-line.tpl" to display the product availability date variable.
```
{if $product.availability_date}
  {assign var="availability_date_formatted" value=$product.availability_date|date_format:"%e %B %Y"}
  <span class="product-availability-date">{$availability_date_formatted}</span>
{/if}
```

2. Edit a product, add a combination and set an availability date on this combination.
3. Go to this product page and check the availability date.
4. Add this product combination to the cart and and check the availability date.
5. You can see that the cart date is null, because the availability date is taken only from the product and not from the combination.

**Screenshots**

I have some custom templating but you can see that the date is not the right one on the cart page : 
![image](https://user-images.githubusercontent.com/690629/137794696-86f2bf3b-6707-442a-ba3f-467f57f61120.png)
![image](https://user-images.githubusercontent.com/690629/137794817-48d34640-0e91-4c24-b895-ead0ffd5f17a.png)

#### Additional information

* PrestaShop version: 1.7.7.8
* PHP version: 7.3.31

**Comment by hibatallahAouadni** [comment]
Hello @Renrhaf 

Sorry for the late response :pray: 
I didn't manage to reproduce the issue with PS1.7.7.8, see the attached screen record below:

https://watch.screencastify.com/v/8JRurWzbOR7zhW6leaTg

Please check and feedback.

Thanks!

**Comment by Renrhaf** [comment]
Hi @hibatallahAouadni, thank you for your message.
Sorry, but your use case is not the right one, as the bug is only present when you set the availability date on a product combination.

**Comment by hibatallahAouadni** [comment]
Hello @Renrhaf 

I tried with Product with combination, check the attached screenshots below:

![image](https://user-images.githubusercontent.com/23308427/138134218-8a6ffc76-28a2-4b41-bcaf-2bf253fc5381.png)

![image](https://user-images.githubusercontent.com/23308427/138134551-b99b6c79-d025-40f6-93f3-d0f4cf1c0a14.png)

![image](https://user-images.githubusercontent.com/23308427/138134586-367d0baf-278e-4b20-a90f-05230a3bd3c3.png)

Please check and feedback.
Thanks!

**Comment by Renrhaf** [comment]
Hi @hibatallahAouadni, I don't have the time to try to reproduce it with a fresh install, but as you did not I think it's related to our theme in some way maybe. I'm closing this and will reopen in the future if I manage to reproduce it.

**Comment by hibatallahAouadni** [comment]
Thanks for your feedback @Renrhaf :pray:
