### ISSUE TITLE
Change terms of use in project by OSL

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#26321]
Change terms of use during install to OSL license (as requested by @ttoine)

Distributions should be able to change this in the build process.

**Comment by matks** [comment]
@eternoendless I dont understand what it exactly means.
Can you provide an example of what should be possible when this issue is solved?

**Comment by eternoendless** [comment]
I thought there was a PrestaShop license agreement here:

<img width="1018" alt="Screenshot 2021-10-20 at 18 03 48" src="https://user-images.githubusercontent.com/1009343/138129637-3f198c67-0cac-4bca-8e3d-57bba85856e8.png">


...but it looks like it's been OSL since 2013 at least.

@ttoine were you thinking about something else?

**Comment by matks** [comment]
@eternoendless So your feature request would be

'As a PrestaShop agency/integrator, if I build my own distribution of PrestaShop and I want to use another license (that can embed OSL and AFL software), I should be able to easily achieve that. For example if I choose a MIT license, when I use [the feature that we have to build] users who install my distribution see the MIT license prompted instead of OSL.'

Is that correct ?

**Comment by eternoendless** [comment]
It's up to @ttoine to clarify it, I'm just a relay in this case.

**Comment by eternoendless** [comment]
That said, I'm not sure OSL allows you to redistribute PrestaShop in a different license.

**Comment by ttoine** [comment]
Mathieu: FYI, OSL is not allowing to change the license. This is a decision taken by the authors, so, to change the license of PrestaShop software, all the authors must agree. However, as described in the devdocs, it is possible to add dependencies in compatible licenses (mostly permissive licenses like MIT).

Pablo: When you install a software, the end user has to approve the "end user license" (e.g with Microsoft products it is the "EULA" and next step is then to enable the software with a product key, or with a Microsoft account). In the case of PrestaShop open source project, this "EULA" is the OSL. I remember that during the install, the user also had to approve the PrestaShop "terms of use" at some point. But if it is already the text of the OSL in the installer, and the step with the "terms of use" has been removed already, then it's fine.

The key is that the OSL is the license used to distribute (and redistribute) the PrestaShop open source project. We must just ensure that this is what the end user approves during the installation.

**Comment by eternoendless** [comment]
Ok, I double-checked and didn't find PrestaShop's terms of use in the install, so I think this can be closed.

**Comment by ttoine** [comment]
Did you check that the term of use have been removed from the entire software, and not only from the installer ?

**Comment by eternoendless** [comment]
I did

**Comment by ttoine** [comment]
great 👍
