### ISSUE TITLE
It is happening to me that after updating to version 1.7.8.0 it never lets you click on that button even if the conditions are accepted, solution?

### ISSUE THREAD

**Issue by rytaf** [PrestaShop/PrestaShop#26329]
It is happening to me that after updating to version 1.7.8.0 it never lets you click on that button even if the conditions are accepted, solution?

_Originally posted by @hostisoft in https://github.com/PrestaShop/PrestaShop/issues/19161#issuecomment-942481794_

**Comment by hibatallahAouadni** [comment]
Hello @LordIndustry 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
