### ISSUE TITLE
Discount is impossible to delete

### ISSUE THREAD

**Issue by kornwaikas** [PrestaShop/PrestaShop#26338]
#### Describe the bug

when you create a new order manually with discount in backoffice, is not possible to delete it. The delete button is not working.

#### Expected behavior

Delete the discount without problems

#### Steps to Reproduce

1) go to order
2) add manually
3) add the products
4) add a discount
5) try to delete it

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @kornwaikas 

I didn't manage to reproduce the issue with PS1780, see the attached screen record below:

https://watch.screencastify.com/v/WNZIjaYqYGSNMm0zXPbU

Please check and feedback.
Thanks!

**Comment by eopws** [comment]
Also not able to reproduce with PS1781

**Comment by hibatallahAouadni** [comment]
Hello @kornwaikas 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a module problem.

We will close this issue.

Thanks!

**Comment by juliendombret** [comment]
if the rules are automaticly add, after delete it that renew
https://user-images.githubusercontent.com/6337822/171184114-63a21488-bb2f-499c-808b-e190f08b2c93.mp4
