### ISSUE TITLE
Uniformize calls of font in BackOffice

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#26335]
#### Is your feature request related to a problem?

In theme in BackOffice & RTL, some fonts are loaded from CDN and another one from local.

#### Describe the solution you'd like

All fonts are loaded from local.

**Comment by mparvazi** [comment]
Hello @Progi1984 

I think using fonts with CDN is more useful:

1. Just will be download and cached once with browser (as like as local)
2. Upgrading of the fonts is easy, just by changing URL
3. It'll reduce size of PS

Thanks!

**Comment by NeOMakinG** [comment]
I guess this can be closed, we removed every CDN (in order to respect privacy data)
