### ISSUE TITLE
Unable to complete Purchase

### ISSUE THREAD

**Issue by enigma-support** [PrestaShop/PrestaShop#26334]
#### Describe the bug

When trying to to complete a purchase we are unable to purchase any items from our store with stripe or paypal

#### Expected behavior

TO be able to select push the button to complete a purchase or select paypal and complete purchase

#### Steps to Reproduce

It is still on going and we are unable to roll back...

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by PrestaEdit** [comment]
Hi @enigma-support ,

Your issue is maybe related to https://github.com/PrestaShop/PrestaShop/issues/26274 but as there is no much informations into your description, it's not sure.

Could you give more informations, like if you make an upgrade of your shop and/or if you have screenshots ?

**Comment by NeOMakinG** [comment]
Looks like a duplicate of https://github.com/PrestaShop/PrestaShop/issues/26274

If not, please add some precision to your issue :)

**Comment by hibatallahAouadni** [comment]
Duplicate of #26274
