### ISSUE TITLE
Dashboard calendar buttons don't work with JS error.

### ISSUE THREAD

**Issue by deadlyengineer** [PrestaShop/PrestaShop#26337]
#### Describe the bug

Dashboard calendar buttons don't work with JS error.

#### Expected behavior

Dashboard calendar buttons work without JS error like 1.7.7.8

#### Steps to Reproduce

1. BO > Dashboard
2. Open the navigator console
3. Click on any Calendar buttons (Day, Month, Year, Day-1, Month-1, Year-1)
4. See error > **`datepickerStart is not defined`**

**Screenshots**

![image](https://user-images.githubusercontent.com/60486296/138096842-281b0de2-02e5-4854-a8de-d533b7c11bef.png)

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @Timezone-design 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #25966. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #25966
