### ISSUE TITLE
Bug with type=color

### ISSUE THREAD

**Issue by anvanto** [PrestaShop/PrestaShop#26333]
#### Describe the bug

The Bug with type = color component is not working correctly.

#### Expected behavior

The Bug with type = color component is not working correctly. The color for all is duplicated from the first field.

#### Steps to Reproduce

You can check by opening any module where there are several mColorPicker.

**Screenshots**
![This is an image](http://dl3.joxi.net/drive/2021/10/19/0049/2754/3250882/82/74882cacfa.jpg)

#### Additional information

* PrestaShop version: PrestaShop 1.7.8.0

**Comment by hibatallahAouadni** [comment]
Hello @anvanto 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #25013. 
This issue has been fixed on develop branch with this PR #25012

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #25013
