### ISSUE TITLE
template @PrestaShop/Admin/Module/catalog.html.twig not found

### ISSUE THREAD

**Issue by arouiadib** [PrestaShop/PrestaShop#26343]
#### Describe the bug
When you click on Module Manager, you have 500, because the template `@PrestaShop/Admin/Module/catalog.html.twig` doesn't exist.

![image](https://user-images.githubusercontent.com/23559010/138136813-af007346-aef3-4900-89c9-5747db64eae9.png)

#### Expected behavior

Should show module catalog page. 

#### Additional information

* PrestaShop version: develop
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @arouiadib 

I didn't manage to reproduce the issue with develop, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/138273096-3e098a3e-4b61-4d67-a93d-684044a60a17.png)

Thanks!

**Comment by arouiadib** [comment]
Hi @hibatallahAouadni 

My bad, I did a mistake in initial post. I meant Module Catalog and not Modules manager. 

But I don't see it in your menu at all :thinking: 

I closed anyways this issue as I think it will be soon fixed by a an ongoing merge. (And because rolling back the template file is was not enough).

I will reopen if you agree with me.

Thanks for your time @hibatallahAouadni
