### ISSUE TITLE
Wrong price per unit on category page. Module - legalcompliance

### ISSUE THREAD

**Issue by pdkey** [PrestaShop/PrestaShop#26345]
#### Describe the bug

After the upgrade from PS 1.7.7.7 to 1.7.7.8. the product price was adjusted, also the price per unit.
The category page still shows the old basic price. On the product page, the price is displayed correctly.
- The Prestashop cache was cleaned, the browser cache as well.
- The own theme was also checked and this does not affect the price per unit.

Second problem.
The price per unit is not displayed at all for all products. Which is also a bug. The price per unit is entered in all products in this category.

#### Expected behavior

The correct price per unit is displayed for all products correct.

**Screenshots**

![Bildschirmfoto 2021-10-21 um 09 31 31](https://user-images.githubusercontent.com/46047238/138233530-f46e4b60-29cd-449a-9733-d22219532852.png)

![Bildschirmfoto-2021-10-21-um-09 32 35](https://user-images.githubusercontent.com/46047238/138233566-1f5fe800-6909-4628-8b0a-d02197b7166e.png)

![Bildschirmfoto-2021-10-21-um-09 32 15](https://user-images.githubusercontent.com/46047238/138233569-05e1c172-3779-4804-94f5-d8bdc5420a73.png)

![Bildschirmfoto-2021-10-21-um-09 33 00](https://user-images.githubusercontent.com/46047238/138233573-ef2593ef-1de8-40e5-92d1-8d003da02ec3.png)

#### Additional information

* PrestaShop version: 1.7.7.8
* PHP version: 7.3

**Comment by pdkey** [comment]
Solution ->  we fix this with a manual delete cache "..var/cache"
- Clean Cache in Admin doesn't fix our issue.

**Comment by hibatallahAouadni** [comment]
@pdkey Glad to hear :tada:
