### ISSUE TITLE
Autoupgrade module 4.12.0 rollback does not work with mysql8

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#26346]
#### Describe the bug

With mysql 8 we cannot roll back a backup.

With the release of 1.7.8.0 this will be a big problem for small shops that do not respect the process well. 

#### Expected behavior

Roll back a backup works

#### Additional information

This PR fix the issue : https://github.com/PrestaShop/autoupgrade/pull/396

**Comment by ghost** [comment]
ping @PierreRambaud @Progi1984

**Comment by matks** [comment]
Hello @okom3pom I changed a bit the title to make it clear what is the issue 😉

**Comment by matks** [comment]
Related to https://github.com/PrestaShop/PrestaShop/issues/24872

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #24872. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #24872

**Comment by ghost** [comment]
@hibatallahAouadni dev core asks me to open a new issue as it is a critical bug.

The initial request was to do a release, as many merchants are impacted. 

@matks has changed the title. 

I see that the problem is fixed by https://github.com/PrestaShop/autoupgrade/pull/396 but the problem is that there has been no update of the module since

The QA also need a new release ( @Robin-Fischer-PS ) 

Thank you :) 

PS : Sorry for my english

**Comment by matks** [comment]
We have planned to do a release soon, probably at the same moment we release PrestaShop 1.7.8.1 😉  . But this is put inside a list of planned tasks, and will be done following the priorities set by the @PrestaShop/product-team .

If you need a new version of the autoupgrade module for your own usage, you can build one from the `dev` branch following the [explanation in the README](https://github.com/PrestaShop/autoupgrade).

**Comment by ghost** [comment]
I can't agree with you.

Letting merchants believe that its backup can be restored without any problem since the problem was reported ( June 2021 ) is not good for the PrestaShop project.

There is also a small change that breaks the themes in 1.7.8.0

I think this fix should have been released.

It's not for me @matks but for the project and the community.

I think it's a negatively impact your reputation.

**Comment by matks** [comment]
Hi @okom3pom I dont get to decide alone when we release a new autoupgrade module version. Releasing a new version is something that requires some time/money as it involves multiple people's work. On the autoupgrade module, it involves a lot of QA validation as this is a critical topic, and QA time is a precious resource 😄  .

I hear you and I report to the team the reasons you mentioned to push for a new release soon.

The different pros and cons of releasing early versus releasing later will be weighed to find the best balance for the project, I am confident my peers will do the best for the project ;)

**Comment by ghost** [comment]
Thank you @matks if we follow this : https://build.prestashop.com/news/severity-classification/

It's a critical issue : _It can lead to data loss,_

So it's possible to re-open the issue and ask the PM team ?

**Comment by matks** [comment]
Better to do this on issue https://github.com/PrestaShop/PrestaShop/issues/24872 to make it easier to track the topic

You can ping @khouloudbelguith or @Robin-Fischer-PS to ask for re-evaluation of the severity of https://github.com/PrestaShop/PrestaShop/issues/24872

**Comment by matks** [comment]
@okom3pom I guess you saw https://github.com/PrestaShop/autoupgrade/releases/tag/v4.13.0 ? 😄
