### ISSUE TITLE
Add category discount and category discount listing misaligned when editing customer group

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#26348]
#### Describe the bug

The "Category discount" part is misaligned when you edit a customer group. I don't know if this is a regression or if it's always been this way.

<img width="1792" alt="Screenshot 2021-10-21 at 11 14 44" src="https://user-images.githubusercontent.com/1009343/138249169-dfd225ae-4838-445d-b919-87424fbfbe1d.png">

<img width="1791" alt="Screenshot 2021-10-21 at 11 15 44" src="https://user-images.githubusercontent.com/1009343/138249162-57a22a81-4b7f-42fd-8545-5c54d5db1774.png">

#### Expected behavior

Good question! Perhaps the UX team could help us on this one.

#### Steps to Reproduce

1. Go to _Shop parameters > Customer settings > Groups_
2. Click to edit an existing customer group

#### Additional information

* PrestaShop version: 1.7.8.1-dev
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @eternoendless 

Yes indeed it's a regression on 1.7.8.0!
I’ll add this to the debug backlog so that it’s fixed.

Thanks @marwachelly for your initiative to fix the issue :tada: waiting for your PR :rocket: 

Thank you

**Comment by Progi1984** [comment]
Fixed by @marwachelly in #26358
