### ISSUE TITLE
[Blockwishlist] Mismatch class naming between the Share.vue component and the share.tpl file

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#26349]
#### Describe the bug

The css class in the Share.vue component (line 117) does not match the class provided in the share.tpl file (line 21). If we modify the css in the vue file, all the changes will affect the display of the modal-create instead of the modal-share. 

#### Expected behavior

Replace &-create by &-share into the Share.vue file to match the class in the share.tpl which is "wishlist-share".

#### Steps to reproduce

1. In the Share.vue file (`blockwishlist/_dev/front/js/components/Share/Share.vue`), add a `background-color : #FFCC00;` like this 
```
  .wishlist {
    &-create {
      .wishlist-modal {
        background-color : #FFCC00;
        display: block;
        opacity: 0;
        pointer-events: none;
        z-index: 0;
        &.show {
          opacity: 1;
          pointer-events: all;
          z-index: 1053;
        }
      }
    }
  }
```
2. compile the module assets `npm install` then `npm run build`
3. In the FO, go to the My account's lists page.
4. Click on "Create a new list" : the background is changed by the color set in the Share.vue file. When you click on "Share the list", the background is not changed. 

**The changes set in the Share.vue file must target only the share modal and not the create modal.**

**Screenshots:**
- Add a new List => NOK, the background shouldn't be changed
![image](https://user-images.githubusercontent.com/23308427/139052577-2a6c3963-eda7-4733-a9d4-1465cf1f4f43.png)

- Share a list => NOK, the background-color should be yellow
![image](https://user-images.githubusercontent.com/23308427/139052597-83e47cfc-7896-4a4c-802c-4cbf6146d969.png)

### Additional context 

- Blockwishlist version : 2.0.1
- PrestaShop version : all PS supported by this module ( >= 1.7.6.x)

**Comment by hibatallahAouadni** [comment]
Hello @a-apare 

Could you please provide steps to reproduce the issue and your PS version.
Please check and feedback.

Thanks!

**Comment by ghost** [comment]
> Hello @a-apare
> 
> Could you please provide steps to reproduce the issue and your PS version. Please check and feedback.
> 
> Thanks!

I have updated the issue, is this OK for you ?

**Comment by NeOMakinG** [comment]
> #### Describe the bug
> The css class into the Share.vue component (line 117) does not match the class provided into the share.tpl file (line 21). If we modify the css in the vue file, all the changes will affect the display of the modal-create instead of the modal-share.
> 
> #### Expected behavior
> Replace &-create by &-share into the Share.vue file to match the class into the share.tpl which is "wishlist-share".
> 
> #### Steps to reproduce
> 1. In the Share.vue file (blockwishlist/_dev/front/js/components/Share/Share.vue), add a "background-color : #FFCC00;" like this
>    `  .wishlist { &-create { .wishlist-modal { background-color : #FFCC00; display: block; opacity: 0; pointer-events: none; z-index: 0; &.show { opacity: 1; pointer-events: all; z-index: 1053; } } }   }`
> 2. compile the module assets `npm run build`
> 3. In the FO, go to the My account's lists page.
> 4. Click on "Create a new list" : the background is changed by the color set into the Share.vue file. When you click on "Share the list", the background is not changed.
> 
> **The changes set into the Share.vue file must target only the share modal and not the create modal.**
> 
> ### Additional context
> * Blockwishlist version : 2.0.1
> * PrestaShop version : all PS supported by this module ( >= 1.7.6.x)

Nice catch! Looks legit to me

**Comment by khouloudbelguith** [comment]
Hi @a-pare,

I tried to run this command `npm run build `
But I have this error
![image](https://user-images.githubusercontent.com/16067358/138469392-fbd2b2f0-c5ec-4086-a91b-c916cf8a6754.png)

What do you think?

Thanks!

**Comment by apare-prolaser** [comment]
> Hi @a-pare,
> 
> I tried to run this command `npm run build ` But I have this error ![image](https://user-images.githubusercontent.com/16067358/138469392-fbd2b2f0-c5ec-4086-a91b-c916cf8a6754.png)
> 
> What do you think?
> 
> Thanks!

Sorry, I did not mention to execute `npm install` before building the assets :)

**Comment by khouloudbelguith** [comment]
@apare-prolaser,

I manage to reproduce the issue with PS1780 & PS1778 using the blockwishlist module v2.0.1
Add a new liste => ok
![image](https://user-images.githubusercontent.com/16067358/138492077-ae983575-81d4-4cb8-b87f-55232367d071.png)
Share a list => NOK
![image](https://user-images.githubusercontent.com/16067358/138492099-1086e987-3306-483d-a39a-4e17b0ec9de8.png)

Thanks for the PR :+1:

**Comment by florine2623** [comment]
Hello all,

I re-open this issue, as it can be reproduced in the Release : https://github.com/PrestaShop/blockwishlist/pull/143

Thanks @khouloudbelguith and @hibatallahAouadni for the tests ^^

**Comment by NeOMakinG** [comment]
Ok I know, it's only due to the fact that @ghost didn't push assets in his PR

**Comment by NeOMakinG** [comment]
It will be naturally fixed with others PR, no need to create a new PR for this, close it when you test another PR or the release

**Comment by Progi1984** [comment]
@florine2623 Could you check again with the latest version of `develop` branch ?

**Comment by Progi1984** [comment]
As discussed with @florine2623 & @NeOMakinG, the bug is fixed.
