### ISSUE TITLE
[BO] Improve virual product by adding upload progress for large files 

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/PrestaShop#26344]
#### Is your feature request related to a problem?

Uploading large files in product page may take too long. Without showing the upload progress user may think that the process has encountered a problem.

#### Describe the solution you'd like

Simply adding a progress bar before the submit button will be useful.

#### Screenshot

<img src="https://user-images.githubusercontent.com/85633460/138128488-36c13524-5f79-4b0b-9657-1b8cf403e75c.png" width="750"/>

https://watch.screencastify.com/v/IR6vJed1Cu0tgVMElCyD

**Comment by hibatallahAouadni** [comment]
Hello @mparvazi 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by hibatallahAouadni** [comment]
@mparvazi why you did close the issue? we're already have the PM approval :thinking:

**Comment by mparvazi** [comment]
@hibatallahAouadni The product page will be redesigned. When new design get introduced, I'll commit a PR based on new product page.
https://github.com/PrestaShop/PrestaShop/pull/26370#issuecomment-949577205
Thanks!
