### ISSUE TITLE
Fixtures text values are not surrounded with a p tag

### ISSUE THREAD

**Issue by sowbiba** [PrestaShop/PrestaShop#26341]
#### Describe the bug

I have a feature where I need to compare form values to say if they have changed and then display a modal before leave the page. In the fixtures, we have the raw values, for example `toto is here`. When you change the value, tinyMCE adds the p tags around the text, like `<p>toto is here updated</p>`. When you restore the field's value, you will have `<p>toto is here</p>` ... so the form changed, even if visually it does not 

#### Expected behavior

2 solutions IMHO :

- Update the fixtures to add p tags when it's a long text
- Automatically add p tags when there are not there when tinyMCE loads

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: 7.3

You can test the behaviour I expose here with the PR https://github.com/PrestaShop/PrestaShop/pull/25706

**Comment by matthieu-rolland** [comment]
Is it possible in your situation to compare the raw value from the fixture with the value from tinyMCE but without HTML tags, using `strip_tags` ?

**Comment by sowbiba** [comment]
> Is it possible in your situation to compare the raw value from the fixture with the value from tinyMCE but without HTML tags, using `strip_tags` ?

I did it with the opposite logic. I add P tag to the original textarea value and then compare the values

**Comment by matks** [comment]
And the `<p>` tags are then persisted into database?

**Comment by hibatallahAouadni** [comment]
Hello @sowbiba 

Is this issue still persist with 8.1.x?
Please check and feedback.

Thanks!

**Comment by sowbiba** [comment]
Wow, this issue is here for a while. I even don't remember the issue I was working on. I think you can quietly close it

**Comment by hibatallahAouadni** [comment]
Thank you @sowbiba 😁
