### ISSUE TITLE
BO - Address format in Countries page is badly displayed

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#26342]
#### Describe the bug

Address format is off centered

#### Expected behavior

Address format should be centered like the other elements.
Tabs and buttons should be on one line.

#### Steps to Reproduce

1. Go to BO > International > Locations > Edit Country of your choice
2. Scroll down to Address format

**Screenshots**

PS 1.7.8.X and develop :
<img width="1073" alt="Screenshot 2021-10-20 at 18 08 47" src="https://user-images.githubusercontent.com/16019289/138130554-3dff9ad9-345c-4ac1-90a8-0a6797422d4b.png">

PS 1.7.7.7 :
<img width="1056" alt="Screenshot 2021-10-20 at 18 08 07" src="https://user-images.githubusercontent.com/16019289/138130600-527a76ef-8d9f-4774-a8aa-3e43d338d607.png">

#### Additional information

* PrestaShop version: 1.7.8.x, develop
* PHP version: 7.3

**Comment by Progi1984** [comment]
@okom3pom Could you backport your PR on `1.7.8.x` branch ?

**Comment by ghost** [comment]
Yes

**Comment by Progi1984** [comment]
Fixed by @marwachelly in #26365
