### ISSUE TITLE
Core.js - Adding and removing faceted filters: slow response

### ISSUE THREAD

**Issue by 0dp** [PrestaShop/PrestaShop#26354]
#### Describe the bug

When adding and removing faceted filter options on product listing ie. a category. The response time is reported to be slow, `>1s`

https://github.com/PrestaShop/PrestaShop/blob/cead068f678598ad0a5df4f12013c2d95cdaa234/themes/_core/js/facets.js#L63-L69

#### Expected behavior

Firefox recommends a response time `<500ms`

I personally don't know if there is anything to do about it, just thought I'd report it here.

#### Steps to Reproduce

1. Go to a product listing ie. product category
2. Click on and add a faceted search filter
3. Inspect response time for XHR request and response
4. Clear all filters applied
5. Inspect response time for XHR request and response

**Screenshots**

<img width="499" alt="Screenshot 2021-10-21 at 12 52 38" src="https://user-images.githubusercontent.com/3642367/138263541-5ca65277-42bf-4f30-bffa-3bdc763fc491.png">

<img width="406" alt="Screenshot 2021-10-21 at 12 45 51" src="https://user-images.githubusercontent.com/3642367/138263104-9dac92f0-d93f-4f3a-bba8-bb1882d49741.png">

#### Additional information

* PrestaShop version: 1.7.7.4
* Firefox version: 93
* Chrome version: 94
* PHP version: 7.3

**Comment by khouloudbelguith** [comment]
Hi @0dp,

I did not manage to reproduce the issue with PS1780 and the ps_facetedsearch v3.7.1.
I attached a screen record
https://watch.screencastify.com/v/b1YqVqjw1QgMikJofP93

Thanks to check and feedback.

**Comment by 0dp** [comment]
I'd argue that you did manage to reproduce it to some extend. Timing is different, sure. But what is an expected and reasonable response/wait time? Firefox says it should below 500ms

**Comment by khouloudbelguith** [comment]
> Timing is different, sure. But what is an expected and reasonable response/wait time? Firefox says it should below 500ms

Can we have the expected wait time in the FO > category page when adding a filter or clear a filter?
Ping @PierreRambaud what do you think?

Thanks!

**Comment by matks** [comment]
> I'd argue that you did manage to reproduce it to some extend. Timing is different, sure. But what is an expected and reasonable response/wait time? Firefox says it should below 500ms

Very, very hard to tell because it depends on browser, browser cache load, server capacity, database content, server config...

It's a complex matter because [performance is very, very subjective](https://build.prestashop.com/news/performance-and-prestashop/).

I'm afraid we cannot set a clear definition of what should be expected here.

**Comment by 0dp** [comment]
I agree @matks with the subjectiveness of performance  and thanks for the link, I'll give it a read.

But what I think is a bit problematic, as you say yourself.
How to set a clear definition of what to expect.

I hope we all expect that the user does not feel like they are waiting for something, or that somehow their action was not registered (ie. Frustration)

How and why the response time is high is the real question. What are we waiting for and how we find out? That's why I'm here raising the question.

**Comment by kpodemski** [comment]
Plenty of work is now being done on the v9 branch to improve the performance, but it is a never-ending process. I'm closing this issue for the reasons mentioned in the discussion above.
