### ISSUE TITLE
Adding and removing faceted filters slow

### ISSUE THREAD

**Issue by 0dp** [PrestaShop/PrestaShop#26350]
https://github.com/PrestaShop/PrestaShop/blob/cead068f678598ad0a5df4f12013c2d95cdaa234/themes/_core/js/facets.js#L63

<img width="1989" alt="Screenshot 2021-10-21 at 11 41 20" src="https://user-images.githubusercontent.com/3642367/138252838-2c022e2a-a2b3-4666-ab02-b2bba542be8c.png">

Reported response time in Firefox 93 is between 1.5 and 2 seconds.

I don't know if there is much to do about it, but thought I'd report it 

Prestashop 1.7.7.4

**Comment by hibatallahAouadni** [comment]
Hello @0dp 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by 0dp** [comment]
Sure thing @hibatallahAouadni 

You see, if you report a line of code like i did directly, the template is not loaded 😅

**Comment by hibatallahAouadni** [comment]
@0dp yep you're right :slightly_smiling_face:
