### ISSUE TITLE
blockwishlist v2.0.1- error in Statistics page 

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#26355]
#### Describe the bug

I can't access Statistics page of module blockwishlist & on the FO the there's an error on display

#### Expected behavior

I should be able to access the Statistics page like it was in 1.7.8x :
<img width="1230" alt="Screenshot 2021-10-21 at 14 48 03" src="https://user-images.githubusercontent.com/16019289/138280497-f7a27b97-a37c-4e4f-9467-bf3a2f99b2d5.png">

#### Steps to Reproduce

1. Go to BO > Modules > Modules Manager > Search "wishlist"
2. Click on Statistics tab
3. See error

**Screenshots**
Error in BO :
<img width="1046" alt="Screenshot 2021-10-21 at 14 47 02" src="https://user-images.githubusercontent.com/16019289/138280338-53c87eb2-2773-4220-8ba7-ef88408d26e9.png">

#### Additional information

* PrestaShop version: develop
* PHP version: 7.3

**Comment by eopws** [comment]
Confirmed with PS1781
![image](https://user-images.githubusercontent.com/42320170/138328740-6d80e9d0-72ac-4391-8dee-77df21316a5c.png)

**Comment by eopws** [comment]
Please review https://github.com/PrestaShop/blockwishlist/pull/137

**Comment by alexandrebru83** [comment]
@florine2623 PR merged last week :)

**Comment by Progi1984** [comment]
Fixed by PrestaShop/blockwishlist#137
