### ISSUE TITLE
You don't have permission to access this resource (search options)

### ISSUE THREAD

**Issue by ilsanto55** [PrestaShop/PrestaShop#26357]
Hi,
I hope you can help me with this issue. I get the message "You don't have permission to access this resource" when I try to save changes in the search options on Shop parameters (back office). Any solution, please?
Thank you so much.
Regards,
Luis

**Comment by eopws** [comment]
Not able to reproduce with PS1781
![Untitled](https://user-images.githubusercontent.com/42320170/138322711-9f89cbcc-35df-41df-9757-44e8f2810192.png)


@ilsanto55 could you please provide your prestashop version and steps to reproduce the issue?

**Comment by ilsanto55** [comment]
Hi, thank you for your answer.
![screenshot search01](https://user-images.githubusercontent.com/92939304/138323243-aef8abd7-b2f7-4c74-a972-b4965619e956.jpg)
![screenshot search02](https://user-images.githubusercontent.com/92939304/138323264-82209324-c4a0-4302-94ba-49e31e89db7d.jpg)

Prestashop 1.7.7.4

**Comment by hibatallahAouadni** [comment]
Hello @ilsanto55 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
