### ISSUE TITLE
Upgrade font-awesome to newest version

### ISSUE THREAD

**Issue by AdrievandeVreede** [PrestaShop/PrestaShop#26356]
#### Is your feature request related to a problem?

There are a few icons I wish I could add them to my theme.

#### Describe the solution you'd like

I'd liked to have an updated version of font-awesome.

**Comment by hibatallahAouadni** [comment]
Hello @AdrievandeVreede 

Thank you for your suggestion. The UX Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by prestascott** [comment]
Hello @AdrievandeVreede,

What icons do you want to add to your theme?

If there's no issues about compatibility, then we can update font-awesome version.

**Comment by hibatallahAouadni** [comment]
Hello @AdrievandeVreede 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
