### ISSUE TITLE
To be able to filter within search results and brand pages

### ISSUE THREAD

**Issue by AdrievandeVreede** [PrestaShop/PrestaShop#26360]
#### Describe the solution you'd like

I'd like to be able to filter, not only in categories, but also on the search results page and the brand page, so that you can set it on and off in the back office.

**Comment by khouloudbelguith** [comment]
Hi @AdrievandeVreede,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #15137
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #15137
