### ISSUE TITLE
Your store is linked to the PrestaShop account - cannot unlink

### ISSUE THREAD

**Issue by WS-NL** [PrestaShop/PrestaShop#26369]
#### Describe the bug

The module PrestaShop account is linked to an email address/account the first time
It is not possible to unlink this account or email address and add another one after the first time.

#### Expected behavior

Unlink and add new email address / account

#### Steps to Reproduce

1. Go to PrestaShop account
2. Click on look up your stores'
3. See that we cannot unlink this email / account

**Screenshots /  forum links**

https://www.prestashop.com/forums/topic/1055764-prestashop-account-module-remove-account-email-address/?tab=comments#comment-3358778
https://www.prestashop.com/forums/topic/1049431-unlink-prestashop-shop-from-account/

#### Additional information

* PrestaShop version: 1.7
* PHP version: 7.2 / 7.3 / 7.4

**Comment by khouloudbelguith** [comment]
Hi @Def2019,

Thanks for your report.
This module is not provided by Prestashop Core, we can't do anything with this.
I transferred your issue to the specialist team, they are the only ones to help you with it.
I will keep you updated if I have more information.
I will close the issue, feel free t open a new one when needed.

Thanks!

**Comment by khouloudbelguith** [comment]
@Def2019 you need to contact the support from https://www.prestashop.com/en/support.

Thanks!
