### ISSUE TITLE
Can not create a product via webservice

### ISSUE THREAD

**Issue by Nikos22350** [PrestaShop/PrestaShop#26361]
**Describe the bug**

Hello,
I would like to contact you because we have a client who has migrated her site to version 1.7.8 and since the interaction with our interface no longer works. We go through the Prestashop Webservice. 

**Expected behavior**

We just want to be able to relaunch the interface with Prestashop as with the 1.7.7.x versions before. 

**Steps to Reproduce**

We noticed that, unlike 1.7.7.X, when retrieving an empty xml schema, the tags are valued with <!CDATA[]>.
We therefore created a function which, when retrieving a schema, removes this empty information. 

By testing with POSTMAN the POST requests of product on test sites in 1.7.8.0, we get an error message and a 500 return code : 

`<?xml version="1.0" encoding="UTF-8"?> <prestashop xmlns:xlink="http://www.w3.org/1999/xlink"> <errors> <error> <code> <![CDATA[134]]> </code> <message> <![CDATA[You cannot set 0 or a negative position, the minimum is 1 . ]]> </message> </error> </errors> </prestashop>`

We have exactly the same error with the xml containing empty CDATE values and with the one that is purged. You can only get around the problem by removing all empty tags. 

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

**Additional information**
PrestaShop version: 1.7.8
PHP version: 7.3.31

**Comment by khouloudbelguith** [comment]
Hi @Nikos22350,

Please, send your request in English.
English is the norm on the GitHub
Thank you!

**Comment by Nikos22350** [comment]
**Describe the bug**

Hello,
I would like to contact you because we have a client who has migrated her site to version 1.7.8 and since the interaction with our interface no longer works. We go through the Prestashop Webservice. 

**Expected behavior**

We just want to be able to relaunch the interface with Prestashop as with the 1.7.7.x versions before. 

**Steps to Reproduce**

Steps to reproduce the behavior:

We noticed that, unlike 1.7.7.X, when retrieving an empty xml schema, the tags are valued with <!CDATA[]>.
We therefore created a function which, when retrieving a schema, removes this empty information. 

By testing with POSTMAN the POST requests of product on test sites in 1.7.8.0, we get an error message and a 500 return code : 

`<?xml version="1.0" encoding="UTF-8"?> <prestashop xmlns:xlink="http://www.w3.org/1999/xlink"> <errors> <error> <code> <![CDATA[134]]> </code> <message> <![CDATA[You cannot set 0 or a negative position, the minimum is 1 . ]]> </message> </error> </errors> </prestashop>`

We have exactly the same error with the xml containing empty CDATE values and with the one that is purged. You can only get around the problem by removing all empty tags. 

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

**Additional information**
PrestaShop version: 1.7.8
PHP version: 7.3.31

**Comment by khouloudbelguith** [comment]
Hi @Nikos22350,

Thanks for your feedback.
I did not manage to reproduce the issue with PS1780 after an upgrade from PS1778 using the 1-click upgrade v4.12.0.
I tried to add addresses with Postman (POST)
I attached a screen record
https://watch.screencastify.com/v/IuMw2RCoLwFdBlmbYm6F

Thanks to check and feedback.

**Comment by Nikos22350** [comment]
thank-you for your prompt response
But the problem does not come from the addresses but when creating a product.
I tested on our test site with your code for the addresses and everything works. 

The xml file  :
`<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
  <product>
    <id><![CDATA[]]></id>
    <id_manufacturer><![CDATA[]]></id_manufacturer>
    <id_supplier>4</id_supplier>
    <id_category_default>9</id_category_default>
    <new><![CDATA[]]></new>
    <cache_default_attribute><![CDATA[]]></cache_default_attribute>
    <id_default_image><![CDATA[]]></id_default_image>
    <id_default_combination><![CDATA[]]></id_default_combination>
    <id_tax_rules_group>1</id_tax_rules_group>
    <position_in_category><![CDATA[]]></position_in_category>
    <type><![CDATA[]]></type>
    <id_shop_default><![CDATA[]]></id_shop_default>
    <reference>1002</reference>
    <supplier_reference>22092/443</supplier_reference>
    <location><![CDATA[]]></location>
    <width><![CDATA[]]></width>
    <height><![CDATA[]]></height>
    <depth><![CDATA[]]></depth>
    <weight><![CDATA[]]></weight>
    <quantity_discount><![CDATA[]]></quantity_discount>
    <ean13><![CDATA[]]></ean13>
    <isbn><![CDATA[]]></isbn>
    <upc><![CDATA[]]></upc>
    <mpn><![CDATA[]]></mpn>
    <cache_is_pack><![CDATA[]]></cache_is_pack>
    <cache_has_attachments><![CDATA[]]></cache_has_attachments>
    <is_virtual><![CDATA[]]></is_virtual>
    <state>1</state>
    <additional_delivery_times><![CDATA[]]></additional_delivery_times>
    <delivery_in_stock>
      <language id="1"><![CDATA[]]></language>
    </delivery_in_stock>
    <delivery_out_stock>
      <language id="1"><![CDATA[]]></language>
    </delivery_out_stock>
    <product_type><![CDATA[]]></product_type>
    <on_sale><![CDATA[]]></on_sale>
    <online_only><![CDATA[]]></online_only>
    <ecotax><![CDATA[]]></ecotax>
    <minimal_quantity><![CDATA[]]></minimal_quantity>
    <low_stock_threshold><![CDATA[]]></low_stock_threshold>
    <low_stock_alert><![CDATA[]]></low_stock_alert>
    <price>70.833</price>
    <wholesale_price><![CDATA[]]></wholesale_price>
    <unity><![CDATA[]]></unity>
    <unit_price_ratio><![CDATA[]]></unit_price_ratio>
    <additional_shipping_cost><![CDATA[]]></additional_shipping_cost>
    <customizable><![CDATA[]]></customizable>
    <text_fields><![CDATA[]]></text_fields>
    <uploadable_files><![CDATA[]]></uploadable_files>
    <active><![CDATA[]]></active>
    <redirect_type><![CDATA[]]></redirect_type>
    <id_type_redirected><![CDATA[]]></id_type_redirected>
    <available_for_order>1</available_for_order>
    <available_date><![CDATA[]]></available_date>
    <show_condition><![CDATA[]]></show_condition>
    <condition><![CDATA[]]></condition>
    <show_price>1</show_price>
    <indexed><![CDATA[]]></indexed>
    <visibility><![CDATA[]]></visibility>
    <advanced_stock_management><![CDATA[]]></advanced_stock_management>
    <date_add><![CDATA[]]></date_add>
    <date_upd><![CDATA[]]></date_upd>
    <pack_stock_type><![CDATA[]]></pack_stock_type>
    <meta_description>
      <language id="1"><![CDATA[]]></language>
    </meta_description>
    <meta_keywords>
      <language id="1"><![CDATA[]]></language>
    </meta_keywords>
    <meta_title>
      <language id="1"><![CDATA[]]></language>
    </meta_title>
    <link_rewrite>
      <language id="1">perox</language>
    </link_rewrite>
    <name>
      <language id="1">PEROX</language>
    </name>
    <description>
      <language id="1"/>
    </description>
    <description_short>
      <language id="1"/>
    </description_short>
    <available_now>
      <language id="1"><![CDATA[]]></language>
    </available_now>
    <available_later>
      <language id="1"><![CDATA[]]></language>
    </available_later>
    <associations>
      <categories>
        <category>
          <id>9</id>
        </category>
      </categories>
      <product_option_values>
        <product_option_value>
          <id><![CDATA[]]></id>
        </product_option_value>
      </product_option_values>
      <product_features>
        <product_feature>
          <id><![CDATA[]]></id>
          <id_feature_value><![CDATA[]]></id_feature_value>
        </product_feature>
      </product_features>
      <tags>
        <tag>
          <id><![CDATA[]]></id>
        </tag>
      </tags>
      <stock_availables>
        <stock_available>
          <id><![CDATA[]]></id>
          <id_product_attribute><![CDATA[]]></id_product_attribute>
        </stock_available>
      </stock_availables>
      <attachments>
        <attachment>
          <id><![CDATA[]]></id>
        </attachment>
      </attachments>
      <accessories>
        <product>
          <id><![CDATA[]]></id>
        </product>
      </accessories>
      <product_bundle>
        <product>
          <id><![CDATA[]]></id>
          <id_product_attribute><![CDATA[]]></id_product_attribute>
          <quantity><![CDATA[]]></quantity>
        </product>
      </product_bundle>
    </associations>
    <Active>0</Active>
  </product>
</prestashop>
`

![image](https://user-images.githubusercontent.com/77013220/138470860-2194c988-4179-42b1-94fb-3030393cdea5.png)

**Comment by khouloudbelguith** [comment]
@Nikos22350, I tried to add a product => ok
![image](https://user-images.githubusercontent.com/16067358/138490831-799a9e9e-60a4-44a2-b937-cfee2919ac64.png)

Thanks to check and feedback.

**Comment by Nikos22350** [comment]
I am no longer at my workplace. I'm watching all of this on Monday with my colleague from the development department.

**Comment by khouloudbelguith** [comment]
@Nikos22350, thanks, waiting for your feedback.

**Comment by Nikos22350** [comment]
Hello,

I made a point with my colleague.
Teh problem comes from the " position_in_category " tag.

He asked us to enter a value while on the synopsis it is not indicated as mandatory.
If we fill in a value, everything works.

Is this an error on the synopsis or on the webservice ?

Thanks in advance.

Regards.

Nicolas

![image](https://user-images.githubusercontent.com/77013220/138662207-25eae5e8-fb53-4f7d-bf8d-990ec696a5ed.png)

**Comment by Nikos22350** [comment]
Hello @khouloudbelguith 

Do you have an explanation for us ?

Thanks.

**Comment by hibatallahAouadni** [comment]
Hello @Nikos22350 

> Teh problem comes from the " position_in_category " tag.
He asked us to enter a value while on the synopsis it is not indicated as mandatory.
If we fill in a value, everything works.

Using this as body for my webservice request to create a product, it works well:

```
<prestashop>
<product>
	<id_category_default>2</id_category_default>
	<id_tax_rules_group >1</id_tax_rules_group>
	<id_shop_default>1</id_shop_default>
	<reference>pack_ws1</reference>
  	<price>35</price>
	<state>1</state>
	<minimal_quantity>1</minimal_quantity>
	<active>1</active>
  	<id_manufacturer/>
  	<id_supplier>1</id_supplier>
  	<link_rewrite>pack</link_rewrite>
	<available_for_order>1</available_for_order>
	<condition>new</condition>
	<show_price>1</show_price>
	<visibility>both</visibility>
	<pack_stock_type>3</pack_stock_type>
	<name><language id="1" >Pack Bundle WS 1</language></name>
	<description><language id="1">New Pack</language></description>
	<description_short><language id="1" >New Pack short</language></description_short>
	<associations>
		<categories nodeType="category" api="categories">
			<category>
				<id>2</id>
			</category>
		</categories>
		<stock_availables nodeType="stock_available" api="stock_availables">
			<stock_available>
				<id>53</id>
			</stock_available>
		</stock_availables>
		<accessories nodeType="product" api="products"/>
		<product_bundle nodeType="product" api="products">
		  <product>
			<id>71</id>
			<quantity>1</quantity>
		  </product>
		  <product>
			<id>73</id>
			<id_product_attribute>14</id_product_attribute>
			<quantity>1</quantity>
		  </product>
		  <product>
			<id>73</id>
			<id_product_attribute>16</id_product_attribute>
			<quantity>1</quantity>
		  </product>
		</product_bundle>
	</associations>
</product>
</prestashop>
```

It seems you override your webservice by adding this attribute `position_in_category` as required.
As your issue is not Core bug but within your overides, so I close the issue.

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thanks for understanding :pray:

**Comment by Nikos22350** [comment]
@hibatallahAouadni 
We use the webservice API provided by Prestashop and not an API set up by our services.
for me the bug comes from Prestashop and not from us because everything worked before the arrival of version 1.7.8.0.

**Comment by Nawakz** [comment]
Hi @Nikos22350,

We had a similar problem after upgrading to v1.7.8.

For solving it :
* You must set id_category_default with an ID AND position_in_category with a value > 1.
* OR you must unset id_category_default AND position_in_category.

**Comment by Nikos22350** [comment]
Hi @Nawakz,

we chose your second solution.

Thank you for your comment.

**Comment by pieerro** [comment]
Hello, I am a beginner in prestashop and I already have a same problem like the above, can someone give me some tips where to apply the corrections indicated by @Nawakz ?   PRESTA 1.7.8

**Comment by jszczypk** [comment]
Hi @hibatallahAouadni,

I think that problem comes from situation when you fetch blank XML for product and fill in values that you would like to set without removing XML nodes for fields that you omit.

In previous versions it worked, but in 1.7.8 when you leave `<position_in_category ><![CDATA[ ]]></position_in_category>` as it is, the empty value is cast to integer 0 in Product::setWsPositionInCategory causing error as it expects positive value.
Maybe you can for few particular setters like forementioned setWsPositionInCategory check if the value is not null and skip setter if it is.

Best regards,
Janusz

**Comment by hibatallahAouadni** [comment]
Duplicate of #14903

**Comment by daxitsolutions** [comment]
I think we should reopen this issue. 

Case : 
When the category is empty, is there is no other product in the category, we are unable to create a product from the API. 

Case 1 : Empty Category
Request payload : 
`XML SENT

<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<product>
	<id></id>
	<id_manufacturer/>
	<id_supplier></id_supplier>
	<id_category_default>3</id_category_default>
	<new></new>
	<cache_default_attribute></cache_default_attribute>
	<id_default_image></id_default_image>
	<id_default_combination></id_default_combination>
	<id_tax_rules_group>1</id_tax_rules_group>
	<position_in_category>1</position_in_category>
	<type></type>
	<id_shop_default></id_shop_default>
	<reference>0000000004382</reference>
	<supplier_reference></supplier_reference>
	<location></location>
	<width></width>
	<height></height>
	<depth></depth>
	<weight></weight>
	<quantity_discount></quantity_discount>
	<ean13></ean13>
	<isbn></isbn>
	<upc></upc>
	<mpn></mpn>
	<cache_is_pack></cache_is_pack>
	<cache_has_attachments></cache_has_attachments>
	<is_virtual></is_virtual>
	<state>1</state>
	<additional_delivery_times></additional_delivery_times>
	<delivery_in_stock><language id="1"></language><language id="2"></language><language id="3"></language></delivery_in_stock>
	<delivery_out_stock><language id="1"></language><language id="2"></language><language id="3"></language></delivery_out_stock>
	<product_type></product_type>
	<on_sale/>
	<online_only/>
	<ecotax></ecotax>
	<minimal_quantity></minimal_quantity>
	<low_stock_threshold></low_stock_threshold>
	<low_stock_alert></low_stock_alert>
	<price>0.82645000</price>
	<wholesale_price></wholesale_price>
	<unity></unity>
	<unit_price_ratio></unit_price_ratio>
	<additional_shipping_cost></additional_shipping_cost>
	<customizable></customizable>
	<text_fields></text_fields>
	<uploadable_files></uploadable_files>
	<active>1</active>
	<redirect_type></redirect_type>
	<id_type_redirected></id_type_redirected>
	<available_for_order>1</available_for_order>
	<available_date>2023-01-25</available_date>
	<show_condition/>
	<condition></condition>
	<show_price>1</show_price>
	<indexed>1</indexed>
	<visibility></visibility>
	<advanced_stock_management></advanced_stock_management>
	<date_add></date_add>
	<date_upd></date_upd>
	<pack_stock_type></pack_stock_type>
	<meta_description><language id="1"></language><language id="2"></language><language id="3"></language></meta_description>
	<meta_keywords><language id="1"></language><language id="2"></language><language id="3"></language></meta_keywords>
	<meta_title><language id="1"></language><language id="2"></language><language id="3"></language></meta_title>
	<link_rewrite><language id="1"></language><language id="2"></language><language id="3"></language></link_rewrite>
	<name><language id="1">super test daxit speed dede</language><language id="2">super test daxit speed dede</language><language id="3"></language></name>
	<description><language id="1"/><language id="2"/><language id="3"></language></description>
	<description_short><language id="1"></language><language id="2"></language><language id="3"></language></description_short>
	<available_now><language id="1"></language><language id="2"></language><language id="3"></language></available_now>
	<available_later><language id="1"></language><language id="2"></language><language id="3"></language></available_later>
<associations>
<categories>
	<category>
	<id/>
	</category>
</categories>
<images>
	<image>
	<id></id>
	</image>
</images>
<combinations>
	<combination>
	<id></id>
	</combination>
</combinations>
<product_option_values>
	<product_option_value>
	<id></id>
	</product_option_value>
</product_option_values>
<product_features>
	<product_feature>
	<id></id>
	<id_feature_value></id_feature_value>
	</product_feature>
</product_features>
<tags>
	<tag>
	<id></id>
	</tag>
</tags>
<stock_availables>
	<stock_available>
	<id></id>
	<id_product_attribute></id_product_attribute>
	</stock_available>
</stock_availables>
<attachments>
	<attachment>
	<id></id>
	</attachment>
</attachments>
<accessories>
	<product>
	<id></id>
	</product>
</accessories>
<product_bundle>
	<product>
	<id></id>
	<id_product_attribute></id_product_attribute>
	<quantity></quantity>
	</product>
</product_bundle>
</associations>
<force_id>0</force_id></product>
</prestashop>
`

The following error occurs
`RETURN HTTP BODY

<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<errors>
<error>
<code><![CDATA[135]]></code>
<message><![CDATA[Vous ne pouvez pas définir une position plus grande que le nombre total de produits dans la catégorie. La numérotation commence à 1. ]]></message>
</error>
</errors>
</prestashop>
`

But if there is a product on the category, everything's fine.
Still something messy here.

I ll reopen a new issue.

**Comment by ajpintos** [comment]
I´m trying to add a sample product trought INSOMNIA Rest API CLIENT.
I receive the following error but with this error i can´t identify what´s the field problem...
```
<?xml version="1.0" encoding="UTF-8"?>
<prestashop
	xmlns:xlink="http://www.w3.org/1999/xlink">
	<errors>
		<error>
			<code>
				<![CDATA[134]]>
			</code>
			<message>
				<![CDATA[You cannot set 0 or a negative position, the minimum is 1.]]>
			</message>
		</error>
	</errors>
</prestashop>
```

This is my xml code.... whats´wrong? I´m using PS 1.7.8.8 version... 

```
<?xml version="1.0" encoding="UTF-8"?>
<prestashop
xmlns:xlink="http://www.w3.org/1999/xlink">
    <product>
<id_manufacturer>
    
</id_manufacturer>
<id_supplier>
    
</id_supplier>
<id_category_default>

</id_category_default>
<new>
    
</new>
<cache_default_attribute>
    
</cache_default_attribute>
<id_default_image>
    
</id_default_image>
<id_default_combination>
    
</id_default_combination>
<id_tax_rules_group>
    
</id_tax_rules_group>
<position_in_category>
    
</position_in_category>
<type>
    
</type>
<id_shop_default>
    
</id_shop_default>
<reference>
    
</reference>
<supplier_reference>
    
</supplier_reference>
<location>
    
</location>
<width>
    
</width>
<height>
    
</height>
<depth>
    
</depth>
<weight>
    
</weight>
<quantity_discount>
    
</quantity_discount>
<ean13>
    
</ean13>
<isbn>
    
</isbn>
<upc>
    
</upc>
<mpn>
    
</mpn>
<cache_is_pack>
    
</cache_is_pack>
<cache_has_attachments>
    
</cache_has_attachments>
<is_virtual>
    
</is_virtual>
<state>
    1
</state>
<additional_delivery_times>
    
</additional_delivery_times>
<delivery_in_stock>
    <language id="1">
        
    </language>
    <language id="2">
        
    </language>
</delivery_in_stock>
<delivery_out_stock>
    <language id="1">
        
    </language>
    <language id="2">
        
    </language>
</delivery_out_stock>
<product_type>
    
</product_type>
<on_sale>
    
</on_sale>
<online_only>
    
</online_only>
<ecotax>
    
</ecotax>
<minimal_quantity>
    
</minimal_quantity>
<low_stock_threshold>
    
</low_stock_threshold>
<low_stock_alert>
    
</low_stock_alert>
<price>
    10.0
</price>
<wholesale_price>
    
</wholesale_price>
<unity>
    
</unity>
<unit_price_ratio>
    
</unit_price_ratio>
<additional_shipping_cost>
    
</additional_shipping_cost>
<customizable>
    
</customizable>
<text_fields>
    
</text_fields>
<uploadable_files>
    
</uploadable_files>
<active>
    
</active>
<redirect_type>
    
</redirect_type>
<id_type_redirected>
    
</id_type_redirected>
<available_for_order>
    
</available_for_order>
<available_date>
    
</available_date>
<show_condition>
    
</show_condition>
<condition>
    
</condition>
<show_price>
    
</show_price>
<indexed>
    
</indexed>
<visibility>
    
</visibility>
<advanced_stock_management>
    
</advanced_stock_management>
<date_add>
    
</date_add>
<date_upd>
    
</date_upd>
<pack_stock_type>
    
</pack_stock_type>
<meta_description>
    <language id="1">
        
    </language>
    <language id="2">
        
    </language>
</meta_description>
<meta_keywords>
    <language id="1">
        
    </language>
    <language id="2">
        
    </language>
</meta_keywords>
<meta_title>
    <language id="1">
        
    </language>
    <language id="2">
        
    </language>
</meta_title>
<link_rewrite>
    <language id="1">
        
    </language>
    <language id="2">
        
    </language>
</link_rewrite>
<name>
    <language id="1">
        Sample Product
    </language>
    <language id="2">
        Sample Product Lang 2
    </language>
</name>
<description>
    <language id="1">
        Sample description
    </language>
    <language id="2">
        Sample description Lang 2
    </language>
</description>
<description_short>
    <language id="1">
        
    </language>
    <language id="2">
        
    </language>
</description_short>
<available_now>
    <language id="1">
        
    </language>
    <language id="2">
        
    </language>
</available_now>
<available_later>
    <language id="1">
        
    </language>
    <language id="2">
        
    </language>
</available_later>
<associations>
    <categories>
        <category>
            <id>
                
            </id>
        </category>
    </categories>
    <images>
        <image>
            <id>
                
            </id>
        </image>
    </images>
    <combinations>
        <combination>
            <id>
                
            </id>
        </combination>
    </combinations>
    <product_option_values>
        <product_option_value>
            <id>
                
            </id>
        </product_option_value>
    </product_option_values>
    <product_features>
        <product_feature>
            <id>
                
            </id>
            <id_feature_value>
                
            </id_feature_value>
        </product_feature>
    </product_features>
    <tags>
        <tag>
            <id>
                
            </id>
        </tag>
    </tags>
    <stock_availables>
        <stock_available>
            <id>
                
            </id>
            <id_product_attribute>
                
            </id_product_attribute>
        </stock_available>
    </stock_availables>
    <attachments>
        <attachment>
            <id>
                
            </id>
        </attachment>
    </attachments>
    <accessories>
        <product>
            <id>
                
            </id>
        </product>
    </accessories>
    <product_bundle>
        <product>
            <id>
                
            </id>
            <id_product_attribute>
                
            </id_product_attribute>
            <quantity>
                
            </quantity>
        </product>
    </product_bundle>
</associations>
</product>
</prestashop>
```
