### ISSUE TITLE
Order address not updated under BO/Orders when discount applied and debug mode is on

### ISSUE THREAD

**Issue by SNor42** [PrestaShop/PrestaShop#26364]
#### Describe the bug

BO - Customer address not updated under order detail page, when debug mode is on, and order has promo code.

#### Expected behavior

Got error message: An unexpected error occurred. [Symfony\Component\Debug\Exception\ContextErrorException code 0]: Notice: Undefined index: reduction_applies

#### Steps to Reproduce

1. Create a discount (for example: 10%)
2. Make an order with discount applied. I made with a registered user.
3. Enable Debug mode!
4. Goto BO Orders, current order.
5. Edit Shipping address, popup opened
6. Change something, and save.
7. Got Error message.

**Screenshots**

![kép](https://user-images.githubusercontent.com/1334351/138427446-05557014-b5f6-41b9-a894-1584a385ba54.png)

#### Additional information

* PrestaShop version: 1.7.7.8
* PHP version: 7.2

**Comment by khouloudbelguith** [comment]
Hi @SNor42,

I did not manage to reproduce the issue with PS1780 and PS1778
I attached a screen record
1780: https://watch.screencastify.com/v/9KOY9zCBdLRNgc1gquog
1778: https://watch.screencastify.com/v/pgyTwN02pxHrMb1lszwy

Thanks to check and feedback.

**Comment by SNor42** [comment]
Also checked on a clean PS1780, and it's working.
The PS1778 is an upgraded version from PS1776. Try to figure out what could be go wrong.
Thanks:N

**Comment by SNor42** [comment]
Alright. I'm not sure why the error occurred, but here is a solution:
In the file: src\Core\Cart\CartRuleCalculator.php
Searched these (3 times): 
`!$product['reduction_applies']`
and replaced with these:
`!empty($product['reduction_applies'])`
And the notice is gone.

**Comment by khouloudbelguith** [comment]
@SNor42, so the issue is fixed in your case?
Can we close this ticket?

Thanks!

**Comment by SNor42** [comment]
@khouloudbelguith , yes and no. I needed to modify a core file to fix the problem. What you think? Add the solution to pull request?

**Comment by florine2623** [comment]
Hello @SNor42 ,

As the issue has not been reproduced on test shops, there's no need for a PR.
The issue was probably only on your shop specifically.

So I'll close your issue.
Thanks!
