### ISSUE TITLE
Your store is linked to the PrestaShop account

### ISSUE THREAD

**Issue by WS-NL** [PrestaShop/PrestaShop#26368]
Hello team

The module PrestaShop account is linked to an email address/account
It is not possible to unlink this account or email address and add another one
Please advise on this.

see forum

https://www.prestashop.com/forums/topic/1055764-prestashop-account-module-remove-account-email-address/?tab=comments#comment-3358778

https://www.prestashop.com/forums/topic/1049431-unlink-prestashop-shop-from-account/

**Comment by khouloudbelguith** [comment]
Hi @Def2019,

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. You must follow the template to submit a complete bug report. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you!
