### ISSUE TITLE
Allow to print order messages

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#26376]
## Is your feature request related to a problem?

Add order message in print.

## Describe the solution you'd like

Allow print order messages

## Additional context

- Go to order page in BO
- Add order message
- click on **print order**
- See is missing the message block

![image](https://user-images.githubusercontent.com/16455155/138461658-6e386142-afb3-4e2a-950d-053ca4013811.png)

**Comment by matks** [comment]
Hi @PululuK should we check with UX and Product team if this is a good improvement for BO ?

**Comment by PululuK** [comment]
> Hi @PululuK should we check with UX and Product team if this is a good improvement for BO ?

Yep @matks  !
ping @PrestaShop/product-team @PrestaShop/ux-team

**Comment by khouloudbelguith** [comment]
Hi @PululuK 

Thanks for your suggestion 
I checked the PS1.6.1.24
It was well displayed
![image](https://user-images.githubusercontent.com/16067358/138467266-f3b6933f-b907-4a77-a21a-7c1f00b6264e.png)


Thanks!

**Comment by PululuK** [comment]
Thanks @khouloudbelguith !
@matks still need UX and Product team ?

**Comment by MatShir** [comment]
Hi @PululuK, 
We didn't add the message panel, because we didn't think it was necessary. Did you have merchants feedback, saying the oppossite ? 
But I can understand that it can be frustrating not to have all the order page printable

**Comment by PululuK** [comment]
> Hi @PululuK, We didn't add the message panel, because we didn't think it was necessary. Did you have merchants feedback, saying the oppossite ? But I can understand that it can be frustrating not to have all the order page printable

Hi @MatShir 

Yes, it was the merchants who asked me this, he used this on PrestaShop 1.6, but after the migration they no longer lost the functionality. Why do you think it isn’t necessary?

**Comment by MatShir** [comment]
I didn't see the need behind it but if a merchant saw the needed then let's go !

**Comment by pphilipondollet** [comment]
Hi there, Any news on when this feature will be restored ? Still missing in 1.7.8.x and still absolutely critical for real life customers ;-)

**Comment by MatShir** [comment]
@pphilipondollet the feature would available on PrestaShop 8.0, we hope for a release this summer.
