### ISSUE TITLE
The brand image is squeezed in the Product description

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/PrestaShop#26373]
#### Describe the bug

These images should have `img-fluid` class and should not have fixed dimensions. Otherwise setting custom dimensions in Design -> Images in BO will break FO's visually

https://github.com/PrestaShop/PrestaShop/blob/f1a69009c39ab498145eccf2fdc70b0f92cd00b2/themes/classic/templates/catalog/_partials/product-details.tpl#L11

#### Expected behavior

![image](https://user-images.githubusercontent.com/23308427/139711258-f66e2bce-a942-41b1-b42d-d5a0a29fae0b.png)

#### Steps to Reproduce
1. FO > Product page
2. Scroll down to Product details and click on it
3. See error > the brand logo is not good/responsive

**Screenshots**

![image](https://user-images.githubusercontent.com/23308427/139711219-2069d311-7a13-4838-9b9b-900eda51c0db.png)

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.3

**Comment by Oksydan** [comment]
@SharakPL 
Some of them has been recently fixed.

https://github.com/PrestaShop/PrestaShop/issues/25850 
https://github.com/PrestaShop/PrestaShop/pull/25855

Other actually deserves separate issues tbh. I will be easier for QA team to test it. Btw follow issue template.

**Comment by SharakPL** [comment]
Added 2 more fixed dimensions in modules: ps_banner and ps_imageslider (including css). This basically prevents anyone from using images with different dimensions than forced by the theme.

>  
> Btw follow issue template.

Didn't I?

**Comment by khouloudbelguith** [comment]
Hi @SharakPL,

Thanks for your report.
as reported by @Oksydan,
https://github.com/PrestaShop/PrestaShop/issues/25850 fixes the `category_default` reproduced with PS1778 & PS1780
https://github.com/PrestaShop/PrestaShop/issues/25849 fixes the `home_default` reproduced 1780 (1778 => ok)

I made those changes
![image](https://user-images.githubusercontent.com/16067358/138487219-cdae4f3e-65fb-40ad-a29d-b5c5e110466e.png)

1. small_default => ok with PS1778 & PS1780 
**Supplier**
![image](https://user-images.githubusercontent.com/16067358/138487296-432d41f6-414e-4903-aaac-fb70fe05815a.png)
**Brands**
![image](https://user-images.githubusercontent.com/16067358/138487334-6a19b924-c258-48ea-9bee-dad759e17cdf.png)
2. medium_default => ok with PS1780 & PS1778
![image](https://user-images.githubusercontent.com/16067358/138488245-52435506-d304-437e-832b-389c4d4d38b7.png)
3. large_default => ok with PS1780 & PS1778

![image](https://user-images.githubusercontent.com/16067358/138488726-5455f524-3790-4473-877b-0a70f1843b58.png)


Thanks to check and feedback.

**Comment by SharakPL** [comment]
Fix for #25850 handles only subcategories in themes/classic/templates/catalog/_partials/subcategories.tpl. What about https://github.com/PrestaShop/PrestaShop/blob/92e000b99bf1e680d7eb72fba947385c01b9175b/themes/classic/templates/catalog/_partials/category-header.tpl#L35 which causes this:
![obraz](https://user-images.githubusercontent.com/5007456/138493282-9928c9b8-e065-4a63-87cd-e3dacaa8fa8b.png)
IMHO not the best place for category image and bad way of implementing it.
___
Product page also doesn't look good with this big gaps, even worse on hover:

![obraz](https://user-images.githubusercontent.com/5007456/138494207-23c27a21-d778-47f7-aeb7-6565fd88138c.png)
___
The same goes for brands. That's how it should look like:
![obraz](https://user-images.githubusercontent.com/5007456/138495248-44af8bb8-cc84-4c10-8e6f-7dde3a78fa08.png)

and that's how classic forces it to look like:
![obraz](https://user-images.githubusercontent.com/5007456/138495408-98db4d0d-04cb-4809-806b-c34b6fc0d341.png)

I bet the same goes for suppliers.
___
There's also slides of ps_imageslider:

![obraz](https://user-images.githubusercontent.com/5007456/138495911-fcae7eaf-d178-4a7e-8b8b-9b23308098d7.png)
___
Banner actually scales properly just because it has `class="img-fluid"`. Only its fixed width and height are completely irrelevant to the used image.

**Comment by hibatallahAouadni** [comment]
Hello @SharakPL 

I reproduce the issue of brand logo on description tab (FO>Product page) with PS1780 & develop, and it's a regression:

![image](https://user-images.githubusercontent.com/23308427/139708378-6bfa73d4-20f7-4e20-89d9-b4ca1f4529cb.png)

While with PS1778, it was ok :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/23308427/139708431-660559da-677e-4183-a81d-2e1a6b00bd48.png)

---
> Product page also doesn't look good with this big gaps, even worse on hover:

I didn't manage to reproduce this issue, LGTM:

![image](https://user-images.githubusercontent.com/23308427/139708777-45951128-a7f1-4d89-8d6b-1bb1114183f4.png)

---
> IMHO not the best place for category image and bad way of implementing it.

It seems good me, there's no issue!

![image](https://user-images.githubusercontent.com/23308427/139709963-caa44db8-4532-44d2-9a82-3d4928e1d92f.png)

---
> Banner actually scales properly just because it has class="img-fluid". Only its fixed width and height are completely irrelevant to the used image.

So, what you suggest? cause IMHO, it seems good to me.

![image](https://user-images.githubusercontent.com/23308427/139710385-5875eab8-b597-4ce1-9cb8-3779ade35697.png)

---

So, I'm going to edit the issue description to fix only the regression that I encountred about the brand logo.

Thanks!

**Comment by SharakPL** [comment]
@hibatallahAouadni I think you missed a lot from this issue. No wonder you couldn't reproduce it on the product page and category images since you've only used landscape image on default square miniatures instead of changing miniature's ratio to portrait or landscape. I specifically added a screen with image sizes used to reproduce the issue, so why did you remove it? Main problem is this theme simply can't handle different miniatures than a square. 

If cutting off portions of the slide (half in your example!) above fixed 350px height is good for you, then we have very different view on the quality of theme's components. Although you're right that it's trivial. Who uses classic theme in the long run anyway? 😜

Please, let me know, if any of this is worth fixing. I'll make a PR later.

**Comment by hibatallahAouadni** [comment]
Hello @SharakPL 

> No wonder you couldn't reproduce it on the product page and category images since you've only used landscape image on default square miniatures instead of changing miniature's ratio to portrait or landscape. I specifically added a screen with image sizes used to reproduce the issue, so why did you remove it? Main problem is this theme simply can't handle different miniatures than a square.

The issuse that you're talking about it's already in our Backlog Patch #25849 :wink: 

> Please, let me know, if any of this is worth fixing. I'll make a PR later.

Yeeeess please :tada: if you could solve the brand logo issue, that would be great :pray: 

Thanks in advance.

**Comment by Progi1984** [comment]
Fixed by @SharakPL in #26622
