### ISSUE TITLE
Delete order statuses

### ISSUE THREAD

**Issue by mati771** [PrestaShop/PrestaShop#26386]
Hello, how do I delete order statuses created by automatic payment? Prestashop 1.7.5.2

![image](https://user-images.githubusercontent.com/63502371/138551841-684e39da-6966-4beb-9bb5-452349159cdf.png)

**Comment by hibatallahAouadni** [comment]
Hello @mati771 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
