### ISSUE TITLE
Color picker min width issue BO/multistore

### ISSUE THREAD

**Issue by SNor42** [PrestaShop/PrestaShop#26384]
#### Describe the bug

BO multistore settings, when add new shop, the color text field is to small, cant' see the hex code. Screen res: 1920x1200

#### Expected behavior

I will set a min-width for these type of input, changed the parent div bootstrap from col-lg-2 to col-lg-4

```
<div class="form-group">
<label class="control-label col-lg-4">
<span class="label-tooltip" data-toggle="tooltip" data-html="true" title="" data-original-title="													Choose a color with the color picker, or enter an HTML color (e.g. &quot;lightblue&quot;, &quot;#CC6600&quot;).
">
Color
</span>
</label>
<div class="col-lg-8">
<div class="form-group">
<div class="col-lg-2"><!-- #### CHANGE TO: <div class="col-lg-4">  #### -->
<div class="row">
<div class="input-group">
<input type="text" data-hex="true" class="color mColorPickerInput mColorPicker" name="color" value="" id="color_0" style="color: black;"><span style="cursor:pointer;" id="icp_color_0" class="mColorPickerTrigger input-group-addon" data-mcolorpicker="true"><img src="/img/admin/color.png" style="border:0;margin:0 0 0 3px" align="absmiddle"></span>
</div>
</div>
</div>
</div>
<p class="help-block">
It will only be applied to the multistore header to highlight your shop context.<br>
</p>
</div>
</div>
```

#### Steps to Reproduce

1. Enable multistore
2. Add new shop

![kép](https://user-images.githubusercontent.com/1334351/138551122-6207775c-f374-4400-8063-88c2dfc3b994.png)

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @SNor42 

I reproduce the issue with PS1780, but it seems to me as an improvement more than a bug :sweat_smile: 
So, let's check with UX-team :wink: 

Ping @PrestaShop/ux-team shall we treat this issue as a bug or an improvement? wdyt?

PS: your fix looks legit, so could you please create a PR :pray: 

Thanks in advance!

**Comment by SNor42** [comment]
Hi!
Well, I've checked my suggestion. And it is not alright, because the form based on form helper. So when we change it, then everywhere it will be wider. For example a module settings page. Here the main problem is that the mentioned form is inside a col-lg-8 DIV, and not col-lg-12... Sooo, I suggest modify via CSS, and also via TPL. I will made a PR for it.

**Comment by prestascott** [comment]
Hello @SNor42 👋🏻

Thanks for your improvement suggestion! :)

I completely agree with you, the text field size is too small to read the full hex code. It needs to be larger.

Yes, IMO it's an improvement @hibatallahAouadni 

LGTM 👏🏻

**Comment by hibatallahAouadni** [comment]
Hello @prestascott 

My proposition is to remove these div `<div class="form-group">`, `<div class="col-lg-2">` and `<div class="row">`, move this div `<div class="input-group">` under `<div class="col-lg-8">`:

![image](https://user-images.githubusercontent.com/23308427/139234410-dfa52798-c912-45d6-9ed7-852f4e9d8034.png)

After my edit:

![image](https://user-images.githubusercontent.com/23308427/139234440-76140321-b0bc-4742-b08e-f8b51ce7b956.png)

Please check and feedback.
Thanks!

**Comment by prestascott** [comment]
Perfect, thank you very much @hibatallahAouadni !

**Comment by SNor42** [comment]
Hi, my variant would be this:
![kép](https://user-images.githubusercontent.com/1334351/139289173-8a107c0d-f6a0-414d-9144-692b946bd9b8.png)

Change `<div class="col-lg-2">` to `<div class="col-lg-8">` and add a custom class name to input group.
And from CSS side limit (only if screen larger than small screen) the max-widht of the above mentioned class.
