### ISSUE TITLE
Won't save product when changing attribution quantity

### ISSUE THREAD

**Issue by SNor42** [PrestaShop/PrestaShop#26389]
#### Describe the bug

If we have a product with variations, or made one. Then when we editing the quantity value, the first save doesn't give success. If we are lucky, the second save is alright. We found these bug after upgrade to PS1778. But finally I could reproduce it under PS1780.

#### Expected behavior

Save for the first time.

#### Steps to Reproduce

0. Please Note: it's hard to reproduce!
1. Clean install. Lang: English (first step), county: Hungary (4. step on install), no demo data.
2. Enable multistore
3. Under Default store group create 2 stores.
4. Enable share quantity!
5. Add some product attributes
6. Enable debug mode
7. Add a single product
8. Switch your profile language to Hungarian --> I'm not sure this is necessary.
9. Go back to product, and add change to variations, add variations
10. Save
11. Change variation quantity.
12. Save -> here goes the "Unable to update settings." (in Hungarian).
13. Save again, then fine.

**Screenshots**

https://www.awesomescreenshot.com/video/5743620?key=0855d87c5bfb92a67f4afe1eb93caa1a

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: N/A

**Comment by SNor42** [comment]
I've tried to trace back the error. I'm stucked at this point:
/src/Core/Stock/StockManager.php
~line 355:
` $stockMvtRepository = $sfContainer->get('prestashop.core.api.stock_movement.repository');`

Maybe it helps.

**Comment by matks** [comment]
I would have 1 hypothesis. It would be that after the upgrade,
- either some data was either corrupted and the 1st SAVE action 'cleaned' it (so next SAVE worked)
- either some data was in cache since before the upgrade, and 1st SAVE uses the data from cache so it fails, but cache is cleared, then next SAVE is successfull

**Comment by SNor42** [comment]
@matks : Yes something you described.  What I figured out. There is a for loop for each combinations in the save process. It checks if there is a stock movement. If not, next. If yes it updates, then fails when calls the above Symfony something.  After saving it again the stock is uptodate, so ignores the Symfony stuff. 
So, what the mentioned lines do? Is it mistyped , or?

**Comment by SNor42** [comment]
Duplicated, already mentioned: #10274

**Comment by hibatallahAouadni** [comment]
Hello @SNor42 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #10274. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: thanks for the tip :wink: and for the well detailed report :clap: 

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #10274
