### ISSUE TITLE
Install error with low MySQL wait_timeout

### ISSUE THREAD

**Issue by rodrigorega** [PrestaShop/PrestaShop#26381]
#### Describe the bug

I am getting this error in Prestashop installation while installing addon modules:

> 1: An exception occurred while executing 'SELECT t0.id_tab AS id_tab_1, t0.id_parent AS id_parent_2, t0.position AS position_3, t0.module AS module_4, t0.class_name AS class_name_5, t0.route_name AS route_name_6, t0.active AS active_7, t0.enabled AS enabled_8, t0.hide_host_mode AS hide_host_mode_9, t0.icon AS icon_10, t0.wording AS wording_11, t0.wording_domain AS wording_domain_12 FROM ps_tab t0 WHERE t0.class_name = ? LIMIT 1' with params ["AdminGamification"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

This issue started to happen recently, I have the same MySQL configuration since several years and in several servers.

In "my.cnf" I have "wait-timeout = 15". If I set "wait-timeout = 600" ,restart MySQL and launch the installation again, it ends without this issue. Maybe PrestaShop installation needs to set "SET SESSION wait_timeout=*" by himself to a higher value?

#### Expected behavior

Installation ends without errors.

#### Steps to Reproduce

1. Uncompress "prestashop_1.7.8.0.zip" in my shared hosting
2. Create a MySQL database and user for Prestashop from cPanel
3. Launch installation process from web browser
4. See error in "screenshots" section

**Screenshots**

![image](https://user-images.githubusercontent.com/3441785/138471240-27ad0647-d6b5-4d0a-be1c-83e1a739949e.png)

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.3 and 7.4

**Comment by khouloudbelguith** [comment]
Hi @rodrigorega,

Thanks for your report.
I tried with PS1778 & PS1780 and it is ok, I did not manage to reproduce the issue.
I attached a screen record
https://watch.screencastify.com/v/qcsbYolIdtBrCSafLzPA
Thanks to check and feedback.

**Comment by rodrigorega** [comment]
Thanks for your tests @khouloudbelguith.

I think that we used different variables, you set [innodb_lock_wait_timeout](https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_lock_wait_timeout) and I set [wait_timeout](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_wait_timeout).

I just tried to make another install in another user with more hosting resources, the issue still happened. In the first table you can see the MySQL connection in idle state during 14 seconds. In the next second the connection is killed because "wait_timeout" is setted to 15:

`mysqladmin pr -i1`

![image](https://user-images.githubusercontent.com/3441785/138681702-f0b7517e-27bf-4577-a7a5-7e8fd64f55b7.png)

**Comment by florine2623** [comment]
Hello @rodrigorega ,

Can you check if your system requirements are met when installing your shop :
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Please check and feedback.
Thanks!

**Comment by rodrigorega** [comment]
Thanks for your reply.

I attach screenshots of the requirements.

Did you tried setting wait_timeout instead innodb_lock_wait_timeout?

![image](https://user-images.githubusercontent.com/3441785/139878066-ed29fbcb-974c-42c7-8f6a-f3e5ffc5cba1.png)

![image](https://user-images.githubusercontent.com/3441785/139878137-8fe55d0e-43bf-4aa1-813d-7bd7c4548500.png)

Regards.

**Comment by khouloudbelguith** [comment]
Hi @rodrigorega,
I changed `wait_timeout = 15`
But, I have a different error.
I tried with PS1778 and the PS1780
![image](https://user-images.githubusercontent.com/16067358/140078010-35a2efb2-e786-4c57-8b55-43834f3cae7b.png)
I attached a screen record
https://watch.screencastify.com/v/I9Zp1EW3LW32PxZwMCzj

Thanks to check and feedback.

**Comment by rodrigorega** [comment]
I guess that Prestashop should [set wait_timeout by himself](https://stackoverflow.com/questions/14146131/is-there-a-way-to-change-wait-timeout-and-max-allowed-packet-through-php) to a higher value during installation.

If I install Prestashop from Installatron there is no issue, so I assume that they are doing this already.

**Comment by hibatallahAouadni** [comment]
Hello @rodrigorega 

> I guess that Prestashop should [set wait_timeout by himself](https://stackoverflow.com/questions/14146131/is-there-a-way-to-change-wait-timeout-and-max-allowed-packet-through-php) to a higher value during installation.

So this bug occurs only with specific setting (`wait_timeout=15`) 
And what you proposed it's an improvement and a good one :wink: 
How about changing this issue from bug to an improvement?

Thanks!

**Comment by rodrigorega** [comment]
Any ETA for this fix? I am still unable to install Prestashop 1.7.8.1.

Thank you.

**Comment by hibatallahAouadni** [comment]
Hello @rodrigorega 

Could you please set the `wait_timeout` to 30 :pray: 
Please check and feedback.

Thanks for your patience :pray:

**Comment by rodrigorega** [comment]
I just tried to make several installations with "wait_timeout = 300" in three different servers. In all of them I got a new error message. I am not sure if is related to this issue:

![image](https://user-images.githubusercontent.com/3441785/144437480-f6c5d33c-38c3-4eae-b1e7-cc865f413e66.png)

Is there a way to enable debug mode on installation?

Thank you.

**Comment by hibatallahAouadni** [comment]
@rodrigorega that's caused by this issue #26838 :disappointed:

**Comment by rodrigorega** [comment]
> Could you please set the `wait_timeout` to 30 pray Please check and feedback.

With "wait-timeout = 30" same issue. I tried with "60" too, with the same result. The installation ended correctly with "wait-timeout = 120".

**Comment by hibatallahAouadni** [comment]
Hello @rodrigorega 

GLad to hear that the installation was completed successfull :tada: 
But it seems the source of your issue is your server configuration, so you need to check it.
Closing this issue as it's not a Core bug.

Thanks for your understanding :pray:

**Comment by rodrigorega** [comment]
Hello,

If you think that leaving a database connection idle for more than 60 seconds is not a bad practice you are right, this is not a bug. 

Any idea why the PS installation was working ok until a few weeks ago? We have 100+ cPanel servers with this mysql configuration since a few years ago.

Regards.
