### ISSUE TITLE
Order total not correct when adding product with non initial price by back office / 1.7.7.8/17.8.0

### ISSUE THREAD

**Issue by Nathanpaternotte** [PrestaShop/PrestaShop#26396]
Hello,

Following an update to 1.7.7.8, I notice that the products with zero value added in an order via the back office are nevertheless recorded on the invoice. 

Has this been fixed on the new versions? I don't see anything in the new changelogs about this.

Thank you!

Screenshot : https://imgur.com/a/huX9klS

**Comment by Nathanpaternotte** [comment]
Additional info: If I create an order by indicating a product at 0 euros, the order displays 0 euros. However, if I add a product to an order already created with a zero amount, the price of the product is still added.

**Comment by Nathanpaternotte** [comment]
Same problem on 1.7.8.0 !

**Comment by Nathanpaternotte** [comment]
SCENARIO : 
- I Create an order with a product at 0 euros.
- I leave the order open to add products everyday (i close the order for some customers or for internal usage at the end of the month)
- I add another product with an amount of 0 euros or another amount smaller than the initial product price
- At this moment, the order total is the sum of transport costs and all initial products price. The invoice is not correct btw

Tested on a fresh install and same result ! Please fix this as soon as possible

**Comment by hibatallahAouadni** [comment]
Hello @Nathanpaternotte 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: you need to follow the provided template to submit a bug :wink: 

Thanks!
