### ISSUE TITLE
Carrier Virtual product

### ISSUE THREAD

**Issue by hadyman** [PrestaShop/PrestaShop#26397]
When you create a VIRTUAL PRODUCT there is no reason to propose any CARRIER as there is no shipping for VIRTUAL PRODUCT.

The solution will be to not apply at all any CARRIER for VIRTUAL PRODUCT

Alternative solution built a new Virtual CARRIER that will NOT display in FO mention DELIVERY to not confuse visitor when purchase VIRTUAL PRODUCT.

thanks

**Comment by hibatallahAouadni** [comment]
Hello @hadyman 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
