### ISSUE TITLE
Product pack search does not work

### ISSUE THREAD

**Issue by akbasferhat** [PrestaShop/PrestaShop#26390]
#### Describe the bug

To add a product to the product package, the product name is typed into the search, but the search does not work. Likewise, when adding similar products, I type the name of the product in the search section, it doesn't work.

#### Expected behavior

Product pack search works!

#### Steps to Reproduce

1. BO>SELL>Catalog>Products
2. Create a new Product
3. Choose Pack of products
4. Type a Product name in the search bar
5. See error > no product displayed

**Screenshots**
https://gyazo.com/745e87fee128405932acb4c4e0eda62d

#### Additional information

* PrestaShop version: 1.7.7.7
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @woxfer 

I didn't manage to reproduce the issue with PS1777, see the attached screen record below:

https://www.awesomescreenshot.com/video/5756601?key=882464b549d7b2ed3ba8b0d108d19d56

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @woxfer 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
