### ISSUE TITLE
[BO] Useless file (rtl.js) should be removed

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/PrestaShop#26399]
#### Describe the bug

There is a file [rtl.js](https://github.com/PrestaShop/PrestaShop/blob/develop/js/rtl.js) inside [PrestaShop/js/](https://github.com/PrestaShop/PrestaShop/tree/develop/js) folder. This file tries to fix all inline styles in a page using jQuery for RTL by searching inline styles like `text-align`, `float` and `background-position` and changing their values from `left` to `right`. 

I think it was useful for old theme and in new theme there is no inline styles. 

Old theme (Inline style)
`<div id="sample" style="float:left"></div>`

New theme (Clean CSS)
`<div id="sample" class="float-left"></div>`

#### Expected behavior

The `rtl.js` and calls to this file should be removed.

#### Steps to Reproduce

I removed this file and there was no problem for RTL mode.

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.4

**Comment by hibatallahAouadni** [comment]
Hello @mparvazi 

It looks like a good improvement :wink: 
Thank you for your suggestion. The Developer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by mparvazi** [comment]
@NeOMakinG 

classes\controller\AdminController.php (2297)

```
//RTL Support
//rtl.js overrides inline styles
//iso_code.css overrides default fonts for every language (optional)
if ($this->context->language->is_rtl) {
    $this->addJS(_PS_JS_DIR_ . 'rtl.js');
    $this->addCSS(__PS_BASE_URI__ . $this->admin_webpath . '/themes/' . $this->bo_theme . '/css/' . $this->context->language->iso_code . '.css', 'all', false);
}
```

`js\rtl.js`
`js\rtl.LICENSE`

**Comment by matks** [comment]
ping @NeOMakinG @kpodemski if you can help us explore this matter

**Comment by kpodemski** [comment]
LGTM
