### ISSUE TITLE
Search.php drops all terms after the first term

### ISSUE THREAD

**Issue by Wrenbjor** [PrestaShop/PrestaShop#26391]
#### Describe the bug

When searching for more than one item in search EX: abc, 123, JRT

Search.php logic in find() uses array_intersect instead of array merge which causes 123, JRT in the case above to be dropped and only abc is searched for.

#### Expected behavior

Expected SQL query should have "sw.word LIKE 'abc%' or sw.word LIKE '123%' or sw.word LIKE 'JRT%'"

#### Steps to Reproduce

Use the SearchBar default search controller and search for 2 or more items that should return results.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.4

**Comment by Wrenbjor** [comment]
simple to fix. Search.php line 337:
replace
`$eligibleProducts2 = array_intersect($eligibleProducts2, $productIds);`
with
`$eligibleProducts2 = array_unique(array_merge($eligibleProducts2, $productIds));`

**Comment by hibatallahAouadni** [comment]
Hello @Wrenbjor 

Could you please provide clear and concise steps to reproduce the issue.
Please check and feedback.

Thanks!

**Comment by Wrenbjor** [comment]
I thought I did, you literally have to search for more than 1 thing. If you search for red, blue then only red items will appear

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by florine2623** [comment]
Hello @Wrenbjor ,

The search bar is meant to search for an item in particular, or any item that are similar in name.
More info about fuzzy search here : https://build.prestashop.com/news/introduction-to-the-fuzzy-search/

With this issue, are you suggesting an improvement of the existing feature ?
Please check and feedback
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Wrenbjor 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by Wrenbjor** [comment]
I wasn't getting notifications. The search logic will only search for the first thing typed into the box. any other items typed in will get dropped. It's a logic flaw. 

If I search for "The blue fox" the logic will break this into a 3 item array. 

a foreach loop will start on line 291. 

`foreach ($expressions as $expression) {`

The code will use the fuzzy search and the DB to look for "The" as the first item in the array and put the results into $productIds.

then at line 328

`$productIds = array_column($result, 'id_product');
                if ($eligibleProducts2 === null) {
                    $eligibleProducts2 = $productIds;
                } else {
                    $eligibleProducts2 = array_intersect($eligibleProducts2, $productIds);
                }
`

will assign "The" as the fist item in the array into $elegibleProducs2 because it is null on the first iteration of the loop so only the first part of the if condition is reached. On the 2nd pass of the foreach for "blue" the DB and fuzzy search will now find a list of things that match "blue" and put that into $productIds.

now on line 328 the if fails because $elegibleProducts2 contains "the" at index 0. so the Else is triggered.

Array_intersect merges 2 arrays. It takes the first array and then adds anything that matches or 'Intersects' the second array and merges them together. so...

$elegibleProducts2[0] is "The"
and 
$productIds[0] is "blue" 

"The" <> "blue" so $elegibleProducts2 only keeps item [0], $productIds is dropped into Null and only 1 item is in $elegibleProducts2. This will happen for every item in a loop and will happen for all searches that dont use the same word over and over.

"The the the" would work for this logic.

"Red Pants", "Red Hats", "Red, Blue, and Green Cars"

for each of these searches the code will only look for "Red" and Pants, Hats, Blue, 'and', Green, and Cars are all dropped and never returned.
