### ISSUE TITLE
Error: invalid e-mail address after upgrading to 1.7.8 in backoffice 

### ISSUE THREAD

**Issue by partiid** [PrestaShop/PrestaShop#26402]
#### Describe the bug

After upgrading to prestashop 1.7.8 i encountered an error. 
When i try to access modules in back office i'm getting Error: invalid e-mail address with http 500 status code 

#### Expected behavior

I expect prestashop to allow me to enter "modules" tab without getting error 500 but instead i cannot access it because im getting the error 

#### Steps to Reproduce

1. Upgrade prestashop wiwth one click upgrade module 
2. Enter backoffice  
3. go to modules -> 1st tab of modules 

**Screenshots**

![image](https://user-images.githubusercontent.com/45274640/138665203-13301846-b454-4edb-a1d3-9a014dfa9301.png)
![image](https://user-images.githubusercontent.com/45274640/138665644-aa223c57-6928-4ac1-a4be-4ec7c2ff9575.png)

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: 7.1

**Comment by hibatallahAouadni** [comment]
Hello @partiid 

I didn't manage to reproduce your issue with PS1775 upgraded to 1780, see the attached screen record below:

https://watch.screencastify.com/v/ET4fZvyrH2vBrilEkqPv

Could you please provide your previous version, and 1-Click Upgrade version :pray: 
Before upgrading, were you logged in to Addons marketplace?

Please check and feedback.
Thanks!

**Comment by gerra14** [comment]
bonjour
j'ai le même problème aussi sur mon site lors de l'inscription du nouveau client après avoir changer la version PrestaShop en 1.7.8.0 mon PHP est 7.4 ca met : cette page ne fonctionne pas .Impossible de traiter cette information à l'heure actuelle .HTTP ERROR 500

**Comment by hibatallahAouadni** [comment]
Hello @gerra14 

Please send your comment in English. English is the norm on GitHub.

Thank you

**Comment by rsoulard-prolaser** [comment]
Hi @hibatallahAouadni,

You have to be in debug mode (https://github.com/PrestaShop/PrestaShop/issues/26680).

**Comment by hibatallahAouadni** [comment]
Hello @partiid 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

PS: @rsoulard-prolaser did you check the attached screen record above, the debug mode is enabled and I didn't manage to reproduce the issue :disappointed: (thanks to mention that #26680 is a duplicate of this one :wink: )

Thanks!
