### ISSUE TITLE
Category breadcrumb error

### ISSUE THREAD

**Issue by jacob-v-dam** [PrestaShop/PrestaShop#26406]
#### Describe the bug

When the breadcrumbs are loaded on a category page you get the following error:
```
Notice: Undefined variable: category
```

It has something to do with:
https://github.com/PrestaShop/PrestaShop/blob/develop/controllers/front/listing/CategoryController.php#L253

`$category` is called instead of `$this->category`.

#### Expected behavior

Load the category page without an error

#### Steps to Reproduce

1. Create a category who hasn't a parent and isn't a root category
2. Make the category active
3. Access the category page

![image](https://user-images.githubusercontent.com/310526/138677361-86d1110a-7815-49c5-8d6d-c7bc2b247d53.png)

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.2

**Comment by Hlavtox** [comment]
@hibatallahAouadni Regression introduced here -> https://github.com/PrestaShop/PrestaShop/pull/23528/files.
Tests didn't catch it because there was `$category` still existing from the foreach loop.

**Comment by jacob-v-dam** [comment]
Indeed but causes problems. Should I create a pr for this?

**Comment by hibatallahAouadni** [comment]
Hello @jacob-v-dam 

> $category is called instead of $this->category

Well, it looks legit to me :clap: nice catch :wink: 
But I need to reproduce the issue, cause technicaly I'm not able to create a category who hasn't a parent and isn't a root category :sweat_smile: see the attahced screen record below:

https://watch.screencastify.com/v/t7tiRwXjlM6weeLUQ323

With PS1780, I'm not allowed to disable a root category. But with develop, I can! and there's no issue risen.
Ping @PrestaShop/prestashop-core-developers wdyt?

PS: thanks @Hlavtox for your PR :superhero: 

Thanks!
