### ISSUE TITLE
Remove id from url

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#26401]
I know that PrestaShop has been for many years, and I have seen that PrestaShop is getting better and better. I am just confused for so many years why PrestaShop is not being a more user-friendly URL like other platforms and requires an additional expensive module to solve it. I browsed Google and forums, some people think it needs to be kept, and many people want to remove it. I think many individual users like me want to remove the ID from the URL unless you are a technical expert. I can’t think of a reason to keep it unless the technology can’t be realized, but many platforms don’t have this problem, so I hope this problem can be considered, Grateful!

**Comment by Hlavtox** [comment]
@chrislais Duplicate of https://github.com/PrestaShop/PrestaShop/issues/20677

**Comment by hibatallahAouadni** [comment]
Hello @chrislais 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #20677. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #20677
