### ISSUE TITLE
Improve code consistency - Remove Yoda expressions

### ISSUE THREAD

**Issue by 0dp** [PrestaShop/PrestaShop#26405]
#### Is your feature request related to a problem?

Would there be consensus to walk through code and remove yoda conditions so that only one kind is used across the board.

#### Describe the solution you'd like

Remove yoda coditions (standardization)

#### Additional context

Just to make it consistent across the code base

**Comment by hibatallahAouadni** [comment]
Hello @0dp 

Thank you for your suggestion. The Developer Team will take it into consideration for future developments. 
And thanks for your PR :rocket: 

Thank you

**Comment by matks** [comment]
Consistency is good but why against yoda expressions ?

Yoda expressions are supposed to be helpful

https://knowthecode.io/yoda-conditions-yoda-not-yoda

**Comment by 0dp** [comment]
Its not that I am against yoda conditions.

But are these yoda expressions there to protect against unwanted results and unexpected behavior. ie. 
> this programming style only serves one purpose and intent: to catch an assignment when you mean to do a comparison. 

```
if (true === $chain)
```

or just because of mixed styles?

If possible, I think consistent syntax improves readability and minimize mistakes.
# MYTH
## Bad Practice: When in Doubt, Yoda.
I advise you to resist this temptation. Yoda conditions may make code harder to read for some developers. Part of your job as a software professional is to write quality code. You want your code to be as readable as possible.

Take the time to learn when to apply any design pattern or methodology. It is another step towards deeply knowing the code and improving the quality of your code.
>Quality code alert: You want your code to be as readable as possible.


Sorry for all the quotes. I just thought it would be relevant now when you linked to the post.

**Comment by PierreRambaud** [comment]
> I advise you to resist this temptation. Yoda conditions may make code harder to read for some developers. Part of your job as a software professional is to write quality code. You want your code to be as readable as possible.

It is just a feeling.
I don't see how it's hard to read between:
`if (true === $chain)` and `if ($chain === true)`.

I'm against removing Yoda expressions without any "good" reason, the code is already here, some prefer using Yoda, others do not. 
If someone wants to change it, it has to be because of the behavior change and only because of a feeling.


When you quote someone, don't forget to link it: https://knowthecode.io/yoda-conditions-yoda-not-yoda

**Comment by 0dp** [comment]
I thought it was clear I was quoting the article posted by @matks 😄 

You are against removing yoda conditions without any "good" reason, but are you also saying that consistency is just a feeling and serves no purpose because the code works?

Maybe you don't find it harder to read and understand, maybe someone else does. I personally think they are annoying to look at especially if they are not used consistently. That is just my opinion.

Footnote: 
I think consistency and alignment is very valuable tools to improve not only prestahop but all software. Especially when you sit on a huge technical dept and have a hard time moving forward with the goals you set forth.
Nothing is too big and daunting if you start small. 🙏

**Comment by PierreRambaud** [comment]
> I thought it was clear I was quoting the article posted by @matks :smile: 

My bad about this one, too many issues opened I sometimes get lost :sweat_smile: 


As I said above, I really think we will have to change Yoda conditions only when we will have to work on it, otherwise it really brings no value right now.

**Comment by 0dp** [comment]
I can get behind that @PierreRambaud 🙏

**Comment by PrestaEdit** [comment]
You ask about a good reason to keep Yoda condition: Symfony code have it.
As we rely on this framework, it's - in my mind - quite usefull that we use them too, for this specific reason.

Also, I think that `null === $chain` is the same read as `is_null($chain)`. You firstly say what you wait/want (null), and about what ($chain) in the two calls.

**Comment by 0dp** [comment]
@PrestaEdit that's interesting. So you'd actually prefer more because it's the preferred way in symphony?

> Use Yoda conditions when checking a variable against an expression to avoid an accidental assignment inside the condition statement (this applies to ==, !=, ===, and !==);

Quoted from symphony docs

**Comment by matks** [comment]
Eyh everyone, so I think
- If I am not wrong, we all agree we should not submit PRs "just to remove Yoda conditions", but rather apply the [boy scout](https://biratkirat.medium.com/step-8-the-boy-scout-rule-robert-c-martin-uncle-bob-9ac839778385) rule: when working on a PHP class, if we find a bad Yoda condition, remove it
- I dont think we need to keep this issue open, what should rather be done is to keep this in mind. An issue is "something we can fix, implement or perform", an action in a todo-list. As the above does not match this criterion I think we can - if you are OK - close this.

**Comment by 0dp** [comment]
I am fine with closing this PR.

At least it sparked a little discussion, some thoughts and opinions have been waived.

**Comment by 0dp** [comment]
As a footnote: it's a very big project and it's hard to grasp everything right off the bat. But IMO start small ask questions and propose modest PR's.

I hope i haven't bothered you guys too much

**Comment by hibatallahAouadni** [comment]
@0dp no you didn't :relaxed: it's our pleasure to answer all your questions.

**Comment by saulaski** [comment]
In my humble opinion yoda style should only be a personal preference, not a constraint. The main purpose of yoda style is avoiding unwanted assignments. Such mistakes should be quickly detected by automated tests anyway.
I think yoda style might go too far because it's more about writer convenience than reader confort... and code style is mostly about easier understanding of the code.

Yoda style makes less sense in PHP than other languages. Java developers usually reverse the order to avoid Null Pointer Exception:
```
"Hello".equals(str); // will never throw a NPE
str.equals("Hello"); // can throw an NPE.
```
