### ISSUE TITLE
Debug mode activation fails for 1.7.8.0

### ISSUE THREAD

**Issue by pnucci** [PrestaShop/PrestaShop#26400]
#### Describe the bug

Enabling Debug mode via Back Office fails, resulting in the following error:

`Error: Could not find whether debug mode is enabled. Make sure that the correct permissions are set on the file /var/www/html/app/../config/defines.inc.php`

But the permissions on this file are set to the apache user. Downgrading to 1.7.7.8 solves the issue.

#### Expected behavior

Debug mode enabled successfully.

#### Steps to Reproduce

1. Fresh install Prestashop 1.7.8.0
2. Activate debug mode via back office

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.4
Using docker and ubuntu 20

**Comment by hibatallahAouadni** [comment]
Hello @pnucci 

With fresh install, I didn't manage to reproduce the issue with PS1780, see the attached screen record below:

https://watch.screencastify.com/v/imV8wWWasgkybOKpiFwS

Did you check your access rights (permissions) on these files? 
Please check and feedback.

Thanks!

**Comment by pnucci** [comment]
Hi @hibatallahAouadni 
thanks for replying. I double checked:

- the config files have the apache user as owner (www-data in my case)
- Applying chmod 777 also does not help.

The interesting fact is that when I use 1.7.7.8 or earlier **the issue is gone**.

I am using the official docker image 
https://hub.docker.com/layers/prestashop/prestashop/1.7.8.0/images/sha256-fda960eb618848857f7895bfae44364323f699d741ea64424f4ff7fd026eff75?context=explore

**Comment by hibatallahAouadni** [comment]
Hello @pnucci 

I think you should change the owner `www-data` by the command line `chown`.
Please check and feedback.

Thanks!

**Comment by pnucci** [comment]
Sure, I will try.
What should be the owner instead of `www-data`?

**Comment by hibatallahAouadni** [comment]
Hello @pnucci 

Sorry @pnucci I can't help you anymore :disappointed: closing this issue.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you

**Comment by medjabir** [comment]
The issue still persists, I am using `1.7.8.8` with docker (the official image)
I double checked the files/folders permissions, nothing works.

**Comment by TechhDan** [comment]
I also had this issue running running a PrestaShop docker container. I found the issue has to do with validating the defines.inc.php or defines_custom.inc.php files. I've explained it more here with a solution as well.

https://github.com/PrestaShop/docker/issues/330

**Comment by jimmy59400** [comment]
In your define.inc.php do not put a space char after the bool (true or false) like that 
define('_PS_MODE_DEV_', false ); <--- wrong 
but 
define('_PS_MODE_DEV_', false); <--- good

Thats happened to me with 1.7.6.7 version
