### ISSUE TITLE
Name validation / Multiple classes for the same purpose

### ISSUE THREAD

**Issue by thalassa-web** [PrestaShop/PrestaShop#26407]
Hi,

recently I had some problems about the override of name validation.
I would like to accept digits in customer name.
After some tests, I see it will mby be almost impossible to do it.

The name validation is made at least at 3 different places :

- PrestaShop\PrestaShop\Core\ConstraintValidator\Constraints\CustomerName
- Validate::isCustomerName (which use Constraints\CustomerName) but could be override
- PrestaShopBundle\Form\Admin\Sell\Customer\CustomerType (which use Constraints\CustomerName)
- PrestaShop\PrestaShop\Core\Domain\Customer\ValueObject\LastName (which use a specific rule)
- PrestaShop\PrestaShop\Core\Domain\Customer\ValueObject\FirstName (which use a specific rule)

Do you have any idea to accept digits in customer name without rewrite PrestaShop ???

I override Validate::isCustomerName to accept digits, but BO customer form throws an error, so I listen the hook «CustomerFormBuilderModifier» to change the validation rule on firstname and lastname to use the Validate::isCustomerName method (by creating another validator). But now I'm stuck with the validation in PrestaShop\PrestaShop\Core\Domain\Customer\ValueObject\LastName and PrestaShop\PrestaShop\Core\Domain\Customer\ValueObject\FirstName.

**Comment by hibatallahAouadni** [comment]
Hello @thalassa-web 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you
