### ISSUE TITLE
Specific price for qty wrong

### ISSUE THREAD

**Issue by AntonioTrudu** [PrestaShop/PrestaShop#26409]
#### Describe the bug

- created 6 customer groups
- for each item specific prices are created for quantity x each group with percentage discount (but even if I put the discount by value the problem is the same)
- in the front office I see the table with the correct quantity prices but when I add a quantity to the cart, PS does not apply the same prices, but performs the calculations using the standard price of the product.

#### Expected behavior

I expect PS to use the prices for quantity that it shows me

#### Steps to Reproduce

**Screenshots**

![Backoffice](https://user-images.githubusercontent.com/93132050/138694156-ffa4fffd-f678-4930-893e-ae4f4c83fd24.jpg)
![Frontoffice](https://user-images.githubusercontent.com/93132050/138694167-2b399d19-d9f5-4319-a0fd-613b99863876.jpg)

#### Additional information

* PrestaShop version: 1.7.6 / 1.7.7 / 1.7.8
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @AntonioTrudu 

It seems your issue related to #15933
Could you please check and feedback.

Thanks!

**Comment by AntonioTrudu** [comment]
Ciao @hibatallahAouadni 

il problema #15933 riguarda un problema di tasse.
il mio problema invece è un altro. PS calcola e visualizza correttamente in FO lo sconto per quantità usando il prezzo associato al gruppo cliente (foreach from=$product.quantity_discounts, {$quantity_discount.quantity}{$quantity_discount.discount}, ma quando raggiungo la prima quantità per applicare lo sconto, calcola lo sconto usando il prezzo standard

**Comment by florine2623** [comment]
Hello @AntonioTrudu ,

Can you send your response in English please ?
Thanks!

**Comment by AntonioTrudu** [comment]
Sorry @fiorino2623

issue # 15933 is about a tax issue.
my problem is another. PS correctly calculates and displays in FO the quantity discount using the price associated with the customer group (foreach from = $ product.quantity_discounts, {$ quantity_discount.quantity} {$ quantity_discount.discount}, but when I reach the first quantity to apply the discount , calculate the discount using the standard price

**Comment by AntonioTrudu** [comment]
Does anyone have any information to solve the problem?

**Comment by florine2623** [comment]
Hello @AntonioTrudu ,

I can't reproduce your issue.

I created my product with the same specific prices as you did :
<img width="1197" alt="Screenshot 2021-11-02 at 12 19 35" src="https://user-images.githubusercontent.com/16019289/139837255-84c6e67a-427c-4bc4-acd5-9a73a7580372.png">

Here's the table with the volume discounts :
<img width="488" alt="Screenshot 2021-11-02 at 12 21 33" src="https://user-images.githubusercontent.com/16019289/139837354-2c8e7c6c-34c5-4f97-9ce1-aaa3b4e36fd2.png">

It changes regarding the quantity I add in my cart :
https://watch.screencastify.com/v/CpaZvcZgxbDeIZkQIlXC

Am I missing something ?
Please check and feedback.
Thanks!

**Comment by AntonioTrudu** [comment]
Hello @florine2623 
in your example you created exactly the same error. The price for 1 pcs for the CUSTOMER group is 3.58 so for 5 pcs it should be 3.58-10% = 3.22 and not 12.07-10% = 10.86 (which I think is the standard price) and in your example there is also another error: 12.07-10.86 = you save 1.21 and not 2.15. In my example (check the image of the my first post)  instead of the YOU SAVE column, I used the discounted quantity price ($ quantity_discount.discount) and in FO I see the correct prices:
x 3 pcs (3.58-5% = 3.40)
x 5 pcs (3.58-10% = 3.22)
x 10 pcs (3.58-15% = 3.04)
but when I put 3 pcs in the cart PS it does not calculate on 3.58 but takes the standard price (10.06-5% = 9.56)

Please check and feedback.
Thanks!

**Comment by florine2623** [comment]
Yes, indeed sorry. I changed my configuration.

For the involved customer group, you should have a configuration like this :
<img width="1190" alt="Screenshot 2021-11-02 at 18 06 46" src="https://user-images.githubusercontent.com/16019289/139912322-b4e581cf-f0cf-49b7-91a0-bebfdf79e1f7.png">

<img width="454" alt="Screenshot 2021-11-02 at 18 15 48" src="https://user-images.githubusercontent.com/16019289/139913577-b16f266f-e9b6-4d58-bc3b-63bf41c58182.png">

In that case, I have :
x3 pcs (3.58-5% = 4.08)
x5 pcs (3.58-10% = 3.87)
x10 pcs (3.58-15% = 3.65)

In the FO :
<img width="508" alt="Screenshot 2021-11-02 at 18 17 04" src="https://user-images.githubusercontent.com/16019289/139913790-cfcea455-babe-4b93-9e4b-0e8c7e439036.png">

In my cart 
<img width="742" alt="Screenshot 2021-11-02 at 18 17 55" src="https://user-images.githubusercontent.com/16019289/139913903-274cc3e0-8ce0-4973-8f79-e348df8da569.png">
:

**Comment by AntonioTrudu** [comment]
Hello @florine2623 
Ok. problem solved. thanks but 3,58-5%=3,40 and not 4,08
