### ISSUE TITLE
Silent crash when saving Product Combinations in DEBUG mode for a french user

### ISSUE THREAD

**Issue by zorrobiwan** [PrestaShop/PrestaShop#26419]
#### Describe the bug

When a french user try to save a product combination in the BO with no ecotax (even without changing any field), BO says "Impossible de mettre à jour les paramètres."

#### Expected behavior

Save should work :)

#### Steps to Reproduce

1. Fresh install 1.7.7.7
2. BO admin in french language
3. Create an simple product
4. Create an attribute (for example : Color) with 2 values (red, blue)
5. Create combinations for the product based on this attribute
6. Without changing any field value, click on save
7. Error is there

**Screenshots**

![image](https://user-images.githubusercontent.com/2226019/138821755-9fbb05f0-677f-4e75-9e58-fe7d3c271cb5.png)

#### Additional information

* PrestaShop version: at least 1.7.7.7
* PHP version: 7.3.31-1~deb10u1
* DEBUG enabled
* BO admin in FR
![image](https://user-images.githubusercontent.com/2226019/138823030-6b156143-00d7-464e-b38f-869075ee5834.png)

* if BO admin is in EN, there is no error
* if DEBUG is disabled, there is no error

There is a 500 error when calling POST on Product controller, but no error in the log or profiler

![image](https://user-images.githubusercontent.com/2226019/138823960-834c35ee-3c4e-469e-a3e1-85682a03a7c6.png)

Thanks to my debug, found that error message:

```
#message: "Notice: A non well formed numeric value encountered"
  #code: 0
  #file: "/var/www/html/prod/src/Adapter/Product/AdminProductWrapper.php"
  #line: 152
  #severity: E_NOTICE
  trace: {
    /var/www/html/prod/src/Adapter/Product/AdminProductWrapper.php:152 {
      › $combinationValues['attribute_ecotax'] = Tools::ps_round(
      ›     $combinationValues['attribute_ecotax'] / (1 + Tax::getProductEcotaxRate() / 100),
      ›     $computingPrecision
    }
    /var/www/html/prod/src/PrestaShopBundle/Controller/Admin/ProductController.php:537 {}
    /var/www/html/prod/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151 {}
    /var/www/html/prod/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68 {}
    /var/www/html/prod/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200 {}
    /var/www/html/prod/admin515c52ki3/index.php:82 {}
  }
```

Here is the code involved
https://github.com/PrestaShop/PrestaShop/blob/40f5e393c65009338d14d25ae1f95339fee002a0/src/Adapter/Product/AdminProductWrapper.php#L152

 ```
       // This is VERY UGLY, but since ti ComputingPrecision can never return enough decimals for now we have no
        // choice but to hard code this one to make sure enough precision is saved in the DB or it results in errors
        // of 1 cent in the shop
        $computingPrecision = CustomMoneyType::PRESTASHOP_DECIMALS;
        if (!isset($combinationValues['attribute_ecotax'])) {
            $combinationValues['attribute_ecotax'] = 0;
        } else {
            // Value is displayed tax included but must be saved tax excluded
            $combinationValues['attribute_ecotax'] = Tools::ps_round(
                $combinationValues['attribute_ecotax'] / (1 + Tax::getProductEcotaxRate() / 100),
                $computingPrecision
            );
        }
```

When BO admin is in FR, values used are the following:

```
$combinationValues['attribute_ecotax'] = "0,000000"
Tax::getProductEcotaxRate() = 0.0

```

and 
"0,00000" / 1.0 throws an error
(see https://stackoverflow.com/questions/42220801/a-non-well-formed-numeric-value-encountered-what-does-this-mean/43258362#43258362)

$combinationValues['attribute_ecotax'] is coming from the form (POST) and is an hidden field (so there is no way to change it).
When BO admin is in EN, default value in this field is 0.00000 and there is no error.
When DEBUG is disable, BO admin in FR, there is no error neither.

Workaround:
* disable DEBUG
* change BO admin language to EN
* add float before $combinationValues['attribute_ecotax'] as discussed in #26276

**Comment by florine2623** [comment]
Hello @zorrobiwan ,

Your issue is similar to : https://github.com/PrestaShop/PrestaShop/issues/25797
A PR to fix the issue has been created : https://github.com/PrestaShop/PrestaShop/pull/25815
Please follow that issue directly to avoid any backlog.

Thanks!

**Comment by florine2623** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/25797

**Comment by zorrobiwan** [comment]
Thx @florine2623 did not found that ones.
Sorry for the duplicate
