### ISSUE TITLE
Module not found: Error: Can't resolve 'tablednd/dist/jquery.tablednd.min'

### ISSUE THREAD

**Issue by Jeremy-FT** [PrestaShop/PrestaShop#26412]
#### Describe the bug

Hi,

When you try to compile js for a new module there is this error :
Module not found: Error: Can't resolve 'tablednd/dist/jquery.tablednd.min'

#### Expected behavior

Js for a new module should compile ootb

#### Steps to Reproduce

1. Create a module
2. import PositionExtension from "@components/grid/extension/position-extension"; for an admin grid
3. Compile JS
4. See error: Module not found: Error: Can't resolve 'tablednd/dist/jquery.tablednd.min'

#### Additional information

* PrestaShop version: 1.7.7.7
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @Jeremy-FT 

Could you please provide a (test) module to reproduce the issue :pray: 
Thanks in advance!

**Comment by Jeremy-FT** [comment]
You can try to reproduce the issue with module ps_linklist

**Comment by templatin** [comment]
@Jeremy-FT Please try [this fix](https://github.com/PrestaShop/PrestaShop/issues/26248#issuecomment-944902368) and let me know whether it solves your error. Note that location of `webpack.config.js` file might be different based on your module.

**Comment by florine2623** [comment]
Hello @Jeremy-FT ,

I have ps_linklist installed on my PS  1.7.7.7 shop. 

Now, can you provide more info so I can reproduce steps 2 to 4 ?
> 2. import PositionExtension from "@components/grid/extension/position-extension"; for an admin grid
> 3. Compile JS
> 4. See error: Module not found: Error: Can't resolve 'tablednd/dist/jquery.tablednd.min'

Thanks!

**Comment by Jeremy-FT** [comment]
> @Jeremy-FT Please try [this fix](https://github.com/PrestaShop/PrestaShop/issues/26248#issuecomment-944902368) and let me know whether it solves your error. Note that location of `webpack.config.js` file might be different based on your module.

It doesn't seem to work

**Comment by Jeremy-FT** [comment]
> Now, can you provide more info so I can reproduce steps 2 to 4 ?

Hello @florine2623,

You can go to modules/ps_linklist/views/js and run yarn and yarn run build to reproduce the error

**Comment by Jeremy-FT** [comment]
Note that I have upgraded Presta to 1.7.8.0 and now I use this. It doesn't require to import components now. I don't know if the issue should be fixed.
https://devdocs.prestashop.com/1.7/development/components/global-components/

**Comment by florine2623** [comment]
Hello @Jeremy-FT ,

I'm using yarn v1.22.17, PS 1.7.7.7, PHP 7.3.
When I run `yarn build` ,
I have this error : `error Command "build" not found.`

Am I doing something wrong ?

**Comment by Jeremy-FT** [comment]
My mistake, try `yarn run build`

**Comment by khouloudbelguith** [comment]
Hi @Jeremy-FT,

Here's the PR: https://github.com/PrestaShop/ps_linklist/pull/137 to fix the issue.
Your ticket is a duplicate of #26291
So, I close it.
Thanks !

**Comment by khouloudbelguith** [comment]
Duplicate of #26291
