### ISSUE TITLE
"APC cache has been enabled, but the APC or APCu extension is not available" message, with cache DISABLED

### ISSUE THREAD

**Issue by elmanu13** [PrestaShop/PrestaShop#26428]
#### Describe the bug

Trying to import products after a server update and PHP version changed (from 7.2 to 7.4, without APC enabled) and got a server error 500:

> [PrestaShopException]
> 
> APC cache has been enabled, but the APC or APCu extension is not available
> at line 43 in file classes/cache/CacheApc.php
> 
> 38.      * CacheApcCore constructor.
> 39.      */
> 40.     public function __construct()
> 41.     {
> 42.         if (!extension_loaded('apc') && !extension_loaded('apcu')) {
> 43.             throw new PrestaShopException('APC cache has been enabled, but the APC or APCu extension is not available');
> 44.         }
> 45.         $this->apcu = extension_loaded('apcu');
> 46.     }
> 47. 
> 48.     /**
> 
>     CacheApcCore->__construct - [line 184 - classes/cache/Cache.php]
>     CacheCore::getInstance - [line 348 - classes/db/Db.php]
>     DbCore->enableCache - [line 4646 - controllers/admin/AdminImportController.php]
>     AdminImportControllerCore->postProcess - [line 295 - classes/controller/Controller.php]
>     ControllerCore->run - [line 518 - classes/Dispatcher.php]
>     DispatcherCore->dispatch - [line 93 - admin/index.php]
 
But when you go in the parameters, the cache is DISABLED (it was enabled a long time ago, disabled before the update)

<img width="783" alt="Capture d’écran 2021-10-26 à 14 31 12" src="https://user-images.githubusercontent.com/32092528/138879352-4011e190-f9a3-47af-a013-45cd128c4ef9.png">

I think there is the APC parameter still present somewhere in the system.

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.4

**Comment by florine2623** [comment]
Hello @elmanu13 ,

I changed my version of PHP from 7.2 to 7.4 using PS 1.7.8.0, I didn't encounter any error during import of products.

I followed these steps :
1. Go to BO > Advanced parameters > Informations > See PHP 7.2
2. Change version of PHP to 7.4
3. Restart server
4. Import products in BO > Advanced Parameters > Import > Choose Products and your import file
5. Import product went well, no error :
<img width="596" alt="Screenshot 2021-10-26 at 17 20 22" src="https://user-images.githubusercontent.com/16019289/138909835-4748e49c-57d6-4229-991f-ab644504e75f.png">

Cache is disabled :
<img width="548" alt="Screenshot 2021-10-26 at 17 20 54" src="https://user-images.githubusercontent.com/16019289/138909987-68a42d46-6d77-4f6e-adc0-66a285fb7859.png">


Please check and feedback.
Thanks!

**Comment by florine2623** [comment]
Hello @elmanu13 ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
