### ISSUE TITLE
Impossible to import more than 5 products in CSV

### ISSUE THREAD

**Issue by elmanu13** [PrestaShop/PrestaShop#26426]
#### Describe the bug

Using a small CSV file to import 50 products, each time the import system takes the 4 or 5 first lines then stop with the following error : 
product name in the CSV (ID: No ID) ne peut pas être enregistré

Only few lines have been imported, the others are with no product name and prices, and the end is simply not here.

#### Steps to Reproduce

1. Go to Catalog, products
2. Click on import
3. Select the CSV file and chose the good columns
4. Import and see error

**Screenshots**

My CSV file
<img width="880" alt="Capture d’écran 2021-10-26 à 13 37 59" src="https://user-images.githubusercontent.com/32092528/138870236-abff9025-92bc-4d85-a1c5-479785834a49.png">

Parameters used
<img width="1118" alt="Capture d’écran 2021-10-26 à 13 33 22" src="https://user-images.githubusercontent.com/32092528/138870398-dcaaf2da-2abd-4205-9d61-36ef320b8264.png">

Error message
<img width="612" alt="Capture d’écran 2021-10-26 à 13 33 53" src="https://user-images.githubusercontent.com/32092528/138870477-c0f2f845-0b6e-47f8-a186-3061daeeeb1e.png">

Catalog after import
<img width="1675" alt="Capture d’écran 2021-10-26 à 13 35 32" src="https://user-images.githubusercontent.com/32092528/138870530-6139f99d-b40c-47f0-b659-22c56b93e2df.png">

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.2

**Comment by florine2623** [comment]
Hello @elmanu13 ,

Could you share your csv file in .csv format ?
I will try on my end.

Thanks!

**Comment by elmanu13** [comment]
Here it is !
[KALAS_PRODUCTS_UPDATE.csv](https://github.com/PrestaShop/PrestaShop/files/7418029/KALAS_PRODUCTS_UPDATE.csv)

I just updated my server and PHP version to 7.4 to check if I still have the problem : not better but different message 
<img width="618" alt="Capture d’écran 2021-10-26 à 15 16 03" src="https://user-images.githubusercontent.com/32092528/138886624-d1068047-a5d7-4bf7-ac58-c0d17f4ce657.png">

**Comment by elmanu13** [comment]
Info : the ps_products_lang have a lot of lines with "friendly-url-autogeneration-failed" in the link_rewrite column

**Comment by elmanu13** [comment]
Problem solved by manually cleaning up the following tables : 
ps_category_product
ps_product
ps_product_lang
ps_product_shop

that all contained a lot of product ID numbers higher than the products I have.

Historically, this shop was configured in multistores under 1.7.5, then I removed the multistore option, removed all the productcs, updated to 1.7.8 then import the new products. 
We are missing a tool tha cleans the products database I guess ^^

**Comment by florine2623** [comment]
Thanks for the file !

I couldn't reproduce your issue on my shop in PS 1.7.8.0 :
<img width="599" alt="Screenshot 2021-10-26 at 16 14 51" src="https://user-images.githubusercontent.com/16019289/138897464-ebdfd5d9-8285-4d95-b112-090f7ec12096.png">

In the product list :
<img width="1193" alt="Screenshot 2021-10-26 at 16 15 09" src="https://user-images.githubusercontent.com/16019289/138897500-ca53f148-aaaf-4372-a2f4-7cb2c2601be6.png">

Maybe that module might help you : https://github.com/PrestaShop/pscleaner

Glad to hear that you fixed the issue !
I'll close this issue as it is fixed for you !
