### ISSUE TITLE
The generated CSS files for RTL didn't use in BackOffice theme

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/PrestaShop#26422]
#### Describe the bug

 In BackOffice for each CSS file, a RTL version of CSS created automatically after PS build.

PATH:  `prestashop\admin\themes\new-theme\public`

<img src="https://user-images.githubusercontent.com/85633460/138772733-ff104130-73f7-4b2b-b182-a7102adfd0bc.png" width="250"/>

BUT the RTL version doesn't call in BackOffice when employee's default language is RTL (Just theme_rtl.css used).

#### Expected behavior

When employee's language in BO changed to a RTL language, corresponding CSS files must be called.

LTR: `orders.css`
RTL: `orders_rtl.css`

#### Steps to Reproduce

1. Go to BO
2. Change employee's language to RTL
3. Go to Orders page
4. See the Browser's inspector for CSS files

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.4

**Comment by mparvazi** [comment]
A sub issue that have found from #26147

**Comment by NeOMakinG** [comment]
Some more explanations => We did split bundles between every pages, but didn't add RTL conditions to it on 1.7.8

**Comment by mparvazi** [comment]
@NeOMakinG 

The CSS files usages:

orders.css
```
src\PrestaShopBundle\Resources\views\Admin\Sell\Order\Order\create.html.twig
src\PrestaShopBundle\Resources\views\Admin\Sell\Order\Order\index.html.twig
src\PrestaShopBundle\Resources\views\Admin\Sell\Order\Order\view.html.twig
```

product.css
```
src\PrestaShopBundle\Resources\views\Admin\Product\ProductPage\product.html.twig
src\PrestaShopBundle\Resources\views\Admin\Sell\Catalog\Product\edit.html.twig
src\PrestaShopBundle\Resources\views\Admin\Sell\Catalog\Product\Combination\edit.html.twig
```

product_catalog.css
```
src\PrestaShopBundle\Resources\views\Admin\Product\CatalogPage\catalog.html.twig
```

stock_page.css
```
src\PrestaShopBundle\Resources\views\Admin\Stock\overview.html.twig
```

theme.css
```
src\PrestaShopBundle\Resources\views\Admin\Exception\error.html.twig
src\PrestaShopBundle\Resources\views\Admin\Exception\not_found.html.twig
src\PrestaShopBundle\Resources\views\Admin\Security\compromised.html.twig
```

#### Changes

prestashop\src\PrestaShopBundle\Twig\LayoutExtension.php
```
(+) Line 105:      'is_lang_rtl' => $this->context->getContext()->language->is_rtl,
```

For each twig files:
```
{% if not is_lang_rtl %}
   <link rel="stylesheet" href="{{ asset('themes/new-theme/public/product_catalog.css') }}" type="text/css" media="all">
{% else %}
   <link rel="stylesheet" href="{{ asset('themes/new-theme/public/product_catalog_rtl.css') }}" type="text/css" media="all">
{% endif %}
```


I tested this changes in PS and it works fine.

**Employee's language is RTL:**

![Screenshot 2021-10-26 161946](https://user-images.githubusercontent.com/85633460/138882083-ffd14df1-2330-494b-a7e3-023889c0ca0e.png)

**Employee's language is LTR:**

![Screenshot 2021-10-26 162659](https://user-images.githubusercontent.com/85633460/138883511-3cc6e5ce-8928-4707-bc8e-f506e44aa54d.png)

**Comment by NeOMakinG** [comment]
Thanks you @mparvazi 

If you want to provide a PR, don't hesitate, overwise I'll take it when I've some free time

**Comment by hibatallahAouadni** [comment]
Hello @mparvazi 

Thanks for your issue and your PR :rocket: 
I reproduce the issue issue with PS1780 and develop. I’ll add this to the debug backlog so that it’s fixed.

_PS: this bug is not regression, as it's a new feature on 1780._

Thank you

**Comment by NeOMakinG** [comment]
@hibatallahAouadni is it a new feature on 1.7.8.0? I think we support these rtl files since years
