### ISSUE TITLE
Customer Service (AdminCustomerThreads) creates customer_thread entries with every page load

### ISSUE THREAD

**Issue by 23b** [PrestaShop/PrestaShop#26432]
#### Describe the bug

Every invalid email (empty message, invalid sender, etc.) in the imap mailbox will continuously generate new invisible (orphan) customer threads.

#### Expected behavior

If a invalid email gets detected and added to the ps_customer_message_sync_imap just like valid emails

#### Steps to Reproduce

1) Send a email **without** text to the imap mailbox which is setup on AdminCustomerThreads with  "create new threads" option enabled
2) Reload/Sync AdminCustomerThreads 
3) You will read "The message is empty, cannot import it." and "Pending Discussion Threads" KPI will count up 🚀
4) repeat step 2-4

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: 7.4

**Comment by florine2623** [comment]
Hello @23b ,

I have a question about the first step.
Is the email sent from the FO as a customer (contact form for example), or from the BO as an employee ? Or any other way ?
Could you make a screen record so that it is clearer to understand ?

Please check and feedback.
Thanks!

**Comment by 23b** [comment]
I am not referring to a FO/BO web form.
Just a good old-fashioned email sent from any SMTP email client.

**Comment by 23b** [comment]
I added the requirement "create new threads" option has to be enabled. (One of the toggle switches in the IMAP Setup section)

**Comment by khouloudbelguith** [comment]
Hi @23b,

Thanks for your feedback.
It will help us if you can attach a screen record to understand how to reproduce the issue.

Thanks!

**Comment by 23b** [comment]
Here is a screen recording.
PS 1.7.8; PHP 7.4.25; Nginx 1.21.3; MacOs 11.6.1; 

https://youtu.be/-GBSobw_voA

**Comment by hibatallahAouadni** [comment]
Hello @23b 

Thanks for your screen record :pray: 
Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a configuration problem.

We will close this issue.

Thanks!
