### ISSUE TITLE
Id Reference for TaxRulesGroup

### ISSUE THREAD

**Issue by varoguitjab** [PrestaShop/PrestaShop#26438]
When I modify a tax rule group the id stored as a configuration in other places such as modules is deprecated.

Id like to have an id reference for TaxRulesGroup like the carriers have, so even if the id changes we can find the TaxRuleGroup by the id_reference

**Comment by hibatallahAouadni** [comment]
Hello @varoguitjab 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
