### ISSUE TITLE
Product sort ordering fails when dragging by name. Works OK dragging by position or click the checkbox manually

### ISSUE THREAD

**Issue by cloud-construct** [PrestaShop/PrestaShop#26431]
#### Describe the bug

Saving the desired sort order of products within categories does not save when dragging the products in the list by their name.

#### Expected behavior

Category product orders
Clicked Reorder.
Dragged each product up one by one using the NAME
Click [save & refresh] button at the top of the table
Save the sort order

#### Steps to Reproduce

1. Category product orders
2. Click Reorder.
3. Dragged each product by using the NAME
4. Click [save & refresh] button at the top of the table

Sort order will return to the original order before start of process
No errors in browser console.

**Screenshots**

https://www.loom.com/share/ec86b742e8284fe7bd519da9bf752acc

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by florine2623** [comment]
Hello @pbscreative ,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #15291
To be informed when it'll be fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by florine2623** [comment]
Duplicate of #15291
