### ISSUE TITLE
[Fix] change "Thing" to "Brand" for the brand JSON-LD

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#26440]
Hi

#### Describe the bug

From few days many websites get notifications from google search console about brand microdata not set in the right way. Google has changed something about the brand microdata
check here
https://developers.google.com/search/docs/advanced/structured-data/product#json-ld

#### Expected behavior

`      "brand": {
        "@type": "Thing",
        "name": "ACME"
      },`

should become

`      "brand": {
        "@type": "Brand",
        "name": "ACME"
      },`

#### How to fix

1. open the file classic/templates/_partials/microdata/product-jsonld.tpl
2. at line 37 change "@type": "Thing",   to "@type": "Brand",

**Screenshots**
![3](https://user-images.githubusercontent.com/653230/138969544-073a5dd7-571c-428e-b718-c7e4380b676e.png)
![7](https://user-images.githubusercontent.com/653230/138969548-e9c70f3c-b9a4-4af0-8a5b-59167d1e80d6.png)

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: 7.3

bye

**Comment by Hlavtox** [comment]
@maofree Already fixed in develop ;-)

**Comment by hibatallahAouadni** [comment]
Hello @maofree 

Nice bug report :clap: 
Well as @Hlavtox mentioned above we are aware of this issue, it is already fixed in develop. 
This issue is a duplicate of #26195. You can check the PR #26194

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #26194
