### ISSUE TITLE
BO - Admin order failed in multistore context

### ISSUE THREAD

**Issue by clopeau** [PrestaShop/PrestaShop#26442]
#### Describe the bug

In prestashop 1.7.8.0 with a new install, you turn on the multistore, create a group and a shop 2 (with customer shared, with or without stock order shared). 

In the BO i want to create an order for the shop 2, only "multishop" products can be added to the cart and then the stock of shop 1 is decreasing. 
If the product was created exclusively in shop 2 then it's impossible to add the product to the cart with a error message "not enough products in stock". 

#### Expected behavior

That the add to cart in the admin order takes into account the shop context and assign the right stock and product

#### Steps to Reproduce

With 2 shops in the same group shop 1 the default store and shop 2 a new shop.

1. Go to admin Order in context shop 2
2. Create a new Order, choose a customer
3. Add a product in the cart (only multistore product)
4. Validate the order
5. Look at the stock of shop1 and shop2

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.3

**Comment by hibatallahAouadni** [comment]
Hello @clopeau 

Thanks for respecting the template and well detailed bug report.
Could you please check this issue #13210 cause it seems similar to yours.
Please check and feedback.

Thanks!

**Comment by clopeau** [comment]
The problem is coming from the "id_shop" of the cart when you add an order and choose a customer in the admin order. If i change "on the fly" in the ps_cart the "id_shop" to the right value everything is back to normal.

I tried to modify controllers/admin/AdminCartsController.php -> ajaxPreProcess() without success...

**Comment by khouloudbelguith** [comment]
Hi @clopeau,

I did not manage to reproduce the issue with PS1780.
I attached a screen record
https://watch.screencastify.com/v/vZlmSxkAD7hmb2cP6vAI
Thanks to check and feedback.

**Comment by florine2623** [comment]
Hello @clopeau ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Comment by Cameros-agency** [comment]
Greetings everyone,
I managed to reproduce this issue with PrestaShop 1.7.8.5 and 1.7.7.8.
According to @khouloudbelguith's screen record, the product added to the cart seems shared between both shops since the product id is the same when you switch them.
As @clopeau mentioned, the product should be exclusive to shop2 to reproduce the issue.
Could you please try to reproduce the issue with a product exclusive to the second shop?
Regards!
