### ISSUE TITLE
you cannot combine prestashop with add-ons. 

### ISSUE THREAD

**Issue by eveneme** [PrestaShop/PrestaShop#26446]
#### Describe the bug

Unable to link account with addons to prestashop. 

**Screenshots**

Module Account PrestaShop.

https://i.ibb.co/HN1jTYN/obraz-2021-10-27-160142.png

* PrestaShop version: 1.7.8.0
* PHP version: 7.4

**Comment by hibatallahAouadni** [comment]
Hello @eveneme 

Please follow the provided template to submit a complete bug report.
I need steps to reproduce the issue (every detail matter).

If you check your screenshot, you can that your shop is already linked and verified:

![image](https://user-images.githubusercontent.com/23308427/139108516-24c5e17b-aac2-486e-9749-4378db4d0e22.png)

Sorry, but I have to close the issue cause this module is not native module. Please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thanks!
