### ISSUE TITLE
url size suffix useless and creating problems

### ISSUE THREAD

**Issue by roberto3211** [PrestaShop/PrestaShop#26452]
THE BUG
tested with  
prestashop 1.7.7.5 and 1.7.7.8
PHP version PHP 7.3 (ea-php73)
If the url of a product contains Clothing Size Attribute and Currency suffix, the currency is not changed in front office.

examples:
These URLs do not change currency in the front office
https://shop.ducatimilano.com/en/3-3-leather-jacket-by-donna-original-ducati-classic-c2-9810286.html#/3-size-42?SubmitCurrency=1&id_currency=13
https://shop.ducatimilano.com/en/3-829-leather-jacket-by-donna-original-ducati-classic-c2-9810286.html#/179-size-46?SubmitCurrency=1&id_currency=13
On the contrary, the following URLs can change currency and select right product, suffix #/3-size-42 or #/179-size-46 are useless.
https://shop.ducatimilano.com/en/3-3-leather-jacket-by-donna-original-ducati-classic-c2-9810286.html?SubmitCurrency=1&id_currency=13
https://shop.ducatimilano.com/en/3-829-leather-jacket-by-donna-original-ducati-classic-c2-9810286.html?SubmitCurrency=1&id_currency=13

SERIOUS PROBLEM
This issue is very important creating feeds for Google Shopping. It is not possible to make them working properly.

Any help will be welcome, we need to have a solution as soon as possible
Roberto

**Comment by hibatallahAouadni** [comment]
Hello @roberto3211 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

THanks!
