### ISSUE TITLE
[BO] Stock movements page don't show time

### ISSUE THREAD

**Issue by alexandrebrubeyonds** [PrestaShop/PrestaShop#26454]
## Describe the bug

Stock movements page show only date and not time
<img width="1450" alt="Capture d’écran 2021-10-27 à 18 24 06" src="https://user-images.githubusercontent.com/92941405/139107101-47f54d4e-1340-405a-96e6-8a5f8c01c450.png">

## Expected behavior

Display date & **time** of movements
<img width="1450" alt="Capture d’écran 2021-10-27 à 18 19 51" src="https://user-images.githubusercontent.com/92941405/139106665-5b13df21-a8c2-44cb-9abe-3cacb7dafd60.png">

## Steps to Reproduce

1. Go to 'Stock Movements pages'
2. See date without time

## Additional information

* PrestaShop version: 8.x
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @alexandrebrubeyonds 

I reproduce the issue only with develop, so it's a **regression**!
https://watch.screencastify.com/v/HhnQcE9tTyG2tjgqNPgT
Thanks for your PR :rocket: 

Thanks!

**Comment by matks** [comment]
Back to "Ready" state because PR https://github.com/PrestaShop/PrestaShop/pull/26455 stale
