### ISSUE TITLE
BO - Order page- Error when deleting cutomized product 

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#26450]
#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to FO> Create an order with the same customized product with different customization and different quantity  
2. Go to BO> Orders page > click on the order created
3.  try to delete all product one by one 

**Screenshots**
![image](https://user-images.githubusercontent.com/89604350/139095490-7d5b1d7d-49e7-4368-ac6e-9390578af647.png)

PS1.7.7.8
https://watch.screencastify.com/v/WiwuCS7H1q37FdxgQPRH

PS1.7.8.0
https://www.awesomescreenshot.com/video/5796468?key=9b882d13481300200092ddb369a16768

#### Additional information

* PrestaShop version: PS1.7.8.0 / PS1.7.7.8
* PHP version: 7.3

**Comment by florine2623** [comment]
It is fixed in PS 8.1.x.


https://github.com/PrestaShop/PrestaShop/assets/16019289/fd3091ed-a3b3-418a-9486-9f125df25e0e



So I'm closing the issue.
