### ISSUE TITLE
Password reset form don't check if user exists

### ISSUE THREAD

**Issue by Oksydan** [PrestaShop/PrestaShop#26457]
#### Describe the bug

When customer want to reset password they go to reset password page and type their password there. Form accepts every email that don't even exists into customer table with success alert `If this email address has been registered in our shop, you will receive a link to reset your password at %email%.`. If customer will make a typo they will wait for never coming email with password reset. Customer might get frustrated and never come back to that shop.

#### Expected behavior

We have to inform customer about not existing email address into database. So if they type by mistake wrong email, they will be notified about it. 

#### Steps to Reproduce

1. Go to password reset page.
2. Type for example `name@email.com`.
3. Success information should appear even if email don't exists into database.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

**Comment by kpodemski** [comment]
This is not a bug. You should not show to everyone that one email exists, or not, in your store.

Because of this you could check my  email and tell me that I have an account in store X. This should not be possible.

**Comment by Oksydan** [comment]
@kpodemski You are right about it but on the other hand we can for example limit it to 5 request per hour to don't allow to abuse it. 
What someone can do with information about your email existence into that shop database?

**Comment by kpodemski** [comment]
@Oksydan it is not really about what you can do about it, it's just a good practice to not leak any sensitive information, right? I can think of some phishing scenarios that would have been possible thanks to this knowledge.

**Comment by Oksydan** [comment]
@kpodemski You are right. I am closing this issue.
