### ISSUE TITLE
Combination::getIdByReference() returns wrong id

### ISSUE THREAD

**Issue by saiif** [PrestaShop/PrestaShop#26467]
#### Describe the bug

Combination::getIdByReference() returns wrong id 

#### Expected behavior

$id = Combination::getIdByReference(500);
return the same id 
$id = Combination::getIdByReference(5000);
cause like is used for the query 

#### Steps to Reproduce

$id = Combination::getIdByReference(500);
return the same id 
$id = Combination::getIdByReference(5000);

**Screenshots**

#### Additional information

* PrestaShop version: 1.7
* PHP version: N/A

**Comment by khouloudbelguith** [comment]
Hi @saiif,

Thanks for your issue.
Have you the same problem reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/20454?

Thanks!

**Comment by saiif** [comment]
Hi @khouloudbelguith 
Yes it's the same issue
thank you.

**Comment by khouloudbelguith** [comment]
@saiif, thanks for your feedback.
Your ticket is a duplicate of #20454
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #20454
