### ISSUE TITLE
Search query must be eq not Like

### ISSUE THREAD

**Issue by saiif** [PrestaShop/PrestaShop#26466]
https://github.com/PrestaShop/PrestaShop/blob/d95d637a1bc801749209a0f216923bc5d58932a1/classes/Combination.php#L507

return wrong product_attribute id when references is similaire  
exp : 500 , 5000

**Comment by hibatallahAouadni** [comment]
Hello @saiif 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: it seems that you create the issue from the code :sweat_smile: so you need to recreate it by clicking on this button:

![image](https://user-images.githubusercontent.com/23308427/139265727-b021eb2e-1a4c-4016-a41d-2eb351a7b0a8.png)

Then choose **Bug report** :wink: 

Thanks!
