### ISSUE TITLE
Re-usable Modules

### ISSUE THREAD

**Issue by tonypartridge** [PrestaShop/PrestaShop#26462]
It would be good if we can re-work how modules are handled. At the moment, we need to create a new module for every position you what that module in. 

Say you want to use a slideshow module or a custom HTML module you have to duplicate them for different content in different locations.

Joomla! for example, handles modules very differently, for instance, if you have your module base, then you create an instance of that base and the params etc are stored in a params column and the module is rendered of its ID. 

It would reduce the need for excess code, be more usable and versatile.

**Comment by kpodemski** [comment]
Hello @tonypartridge 

Have you read about https://devdocs.prestashop.com/1.7/modules/concepts/widgets/#widgets?

**Comment by tonypartridge** [comment]
Hey,

Yes, I have and this concept allows re-using the module but with the same content. It still has the major flaw that you cannot have different content. Whilst it solves the multiple position display, it still falls down on the basis that if you have say two category modules one for 'Sale Items' and one for 'Featured Items' you would need to build two modules to have different categories assigned to render. This doesn't make any sense in duplicating the modules codebase just to have different content for the same module?

**Comment by kpodemski** [comment]
You can use `{widget_block}` to defer the content, so you can pass all the variables into your view and use what you really need. The mechanism is not perfect but does the job well for many.

Of course, I understand your point because I would be happy to see a possibility to hook one module into the same place a couple of times. I suggested this feature too. But since widgets are available, I don't need changes anymore.

**Comment by hibatallahAouadni** [comment]
Hello @tonypartridge 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: thanks @kpodemski for your quick replies :rocket: 

Thanks!
