### ISSUE TITLE
BO - Profiles - Filters are NOK

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#26463]
#### Describe the bug

In the BO > Advanced Parameters > Team > Profiles page, when we try to filter by any field, the page is just refreshed.
This regression is detected by [nightly](https://nightly.prestashop.com/report/2870)
![image](https://user-images.githubusercontent.com/16067358/139217918-8ef7e3f4-b4e5-46de-b989-1747f7abd6d5.png)

#### Steps to Reproduce

 
1. Go to BO > Advanced Parameters > Team > Profiles page
2. try to filter by any field
4. See an error

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

**Comment by alexandrebrubeyonds** [comment]
I don't reproduce this issue, and you ?
