### ISSUE TITLE
what happens with PrestaShop / ps_reminder

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#26460]
What happens with PrestaShop/ps_reminder  ? "This repository has been archived by the owner. It is now read-only."

**Comment by matks** [comment]
Archived because we dont want to continue maintaining them anymore. It has been identified as not essential and we need to focus our efforts on other projects.

See full context https://build.prestashop.com/news/focusing-on-essential-modules/

**Comment by alfonsolr09** [comment]
neither is the security module or the image carousel essential. for that rule of three only the payment module and login are essential.
It is a shame to lose modules for not being considered essential. 
At least the Abandoned Cart Pro module is still being maintained, right?
