### ISSUE TITLE
Optin is enabled for the email anonymous@psrgpd.com

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#26476]
#### Describe the bug

The address anonymous@psgdpr.com is active for partner offers.

So if you export a list, you have anonymous@rpgd.com in your list.

#### Expected behavior

Disable optin for this address

#### Steps to Reproduce

1. Go to your database
2. Check the table customer for anonymous@psgdpr.com 

**Screenshots**

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

Thanks for your report.
Ping @PrestaShop/product-team what do you think? Is it possible to disable the partner offers for the `anonymous@psrgpd.com` customer?
![image](https://user-images.githubusercontent.com/16067358/139428052-11cec7fe-1bd4-4009-b712-234a1af657c0.png)

Thanks!

**Comment by marionf** [comment]
Hello @okom3pom 

The toggle partner offer lets you know if your customers wants to receive the ads of your partners via email or not.
I don't understand why there is a risk of spam: your customer doesn't receive emails sent to anonymous@psrgpd.com ?

**Comment by ghost** [comment]
Hi @marionf 

Many modules do not check if the client is disabled (ps_emailsubscription first). 

So if you export a list, you have anonymous@rpgd.com in your list.

By spam I meant that your list will not be of good quality, so there is a risk that your mails will delivery in spam mailbox

I update the issue

**Comment by marionf** [comment]
I see, thank you for the explanation

**Comment by sharkooon** [comment]
Why is there a customer with that emailaddress on first setup without demonstration data?

**Comment by ghost** [comment]
Hello @sharkooon 

Normaly this issue is closed but for your information it's the gdpr module who add this email

Fixed by : https://github.com/PrestaShop/psgdpr/pull/150

**Comment by MatShir** [comment]
thanks @okom3pom <3 keep going :)
