### ISSUE TITLE
[BO] Product page, Specific prices - Change currency don't change Symbol

### ISSUE THREAD

**Issue by alexandrebrubeyonds** [PrestaShop/PrestaShop#26482]
## Describe the bug

When we change the currency condition for specific price, the default currency doesn't change by the currency symbol selected.

<img width="1295" alt="Capture d’écran 2021-10-29 à 19 15 14" src="https://user-images.githubusercontent.com/92941405/139476935-bc8af49f-b484-4300-8c52-ff2b7ab19608.png">

## Expected behavior

When we change the currency condition for a specific price, the default currency should change by the currency symbol selected. Add Form + Modal Form + Initialization Modal Form

<img width="1297" alt="Capture d’écran 2021-10-29 à 19 16 32" src="https://user-images.githubusercontent.com/92941405/139476998-bc6d09b5-2474-4be5-abf2-05f5c8b9c2fc.png">

<img width="581" alt="Capture d’écran 2021-10-29 à 19 17 42" src="https://user-images.githubusercontent.com/92941405/139476952-e6c12df8-6729-4c8b-bf63-e5376a93e6cf.png">

## Steps to Reproduce

1. Configure more than 1 currency for the shop, for example USD and EUR
2. Go to Product Page
3. Click on 'Add specific price' or Edit one specific price
4. Select specific currency
5. The symbol after the field "Product price (tax excl.)" is still the default currency of shop
6. The symbol in select option between "amount" en "percentage" is still the default currency of shop

## Additional information

Maybe related to #19673 "Default currency symbol" 

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @alexandrebrubeyonds 

I reproduce the issue with PS1767, PS1778, PS1780. Thanks for your PR :rocket: 
The Product Team will take it into consideration for future developments. 

Ping @PrestaShop/product-team shall we change the euro signal by the chosen currency in these fields (`input-group-prepend` & option amount? wdyt?

![image](https://user-images.githubusercontent.com/23308427/139680593-fe133b9c-c957-4c5e-b096-5e3c7f6846ce.png)

![image](https://user-images.githubusercontent.com/23308427/139680613-d7bdf81d-e474-4289-9d04-6a7e795c3907.png)

Thank you
