### ISSUE TITLE
Add an instant search for the main menu in BO

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/PrestaShop#26497]
#### Describe the solution you'd like

Adding an instant search for main menu links in BO would be helpful for users that are new to PS.

#### Screenshot

<img src="https://user-images.githubusercontent.com/85633460/140098383-b84f735b-2645-4b8c-afca-00ebfe60e9b5.png" width="800"/>

#### Video

https://watch.screencastify.com/v/cK6inbhGct7aTQEPMqdo

**Comment by hibatallahAouadni** [comment]
Hello @mparvazi 

That will be very helpful :clap: and if you could provide a PR, it will be great :rocket: 
Thank you for your suggestion. The Product Team will take it into consideration for future developments. 

Thank you

**Comment by mparvazi** [comment]
@hibatallahAouadni @MatShir 

I tried to show what I expected. It isn't complete yet and needs more work.
Please send your feedback and tell me what features should be added to make it better.

Sample video:
https://watch.screencastify.com/v/s59uvhUvilLjXY1kMlie

**Default:**

<img src="https://user-images.githubusercontent.com/85633460/139862504-6078dbca-afa1-4e34-8856-000bc9c64edd.png" width="500"/>

**Filtered:**

<img src="https://user-images.githubusercontent.com/85633460/139862572-ad2a04db-b192-4482-a455-4630e3bdc2e9.png" width="500"/>

**Hide on collapsed menu:**

<img src="https://user-images.githubusercontent.com/85633460/139862739-b132f7bb-95fe-466e-8abe-769d0b0c3176.png" width="500"/>

**Comment by mparvazi** [comment]
`admin\themes\default\template\nav.tpl`

```
<script>
$(document).ready(function () {
    const $filterBox = $('.input-filter');
    const $clearButton = $('.clear-filter');
    const $mainMenu = $('.main-menu');

    $filterBox.keyup(function(){
      const filter = $(this).val().toUpperCase();
      if (filter.length === 0)
        $clearButton.hide();
      else
        $clearButton.show();
      if (filter.length > 1) {
        $mainMenu.addClass('filtered');
        $mainMenu.find('li.category-title').hide();
        $mainMenu.find('.link-levelone').each(function(){
          if($(this).find('ul').text().toUpperCase().match(filter)) {
            $(this).addClass('ul-open open');
            $(this).show();
          } else {
            $(this).hide();
          }
          $(this).find('.link-leveltwo').each(function(){
            if($(this).text().toUpperCase().match(filter)) {
              $(this).show();
              const text  = $(this).find('a').text().trim().replace(/ /g, '&nbsp;');
              const startIndex = text.toUpperCase().indexOf(filter);
              const html = text.substr(0, startIndex) + 
                '<em>' + text.substr(startIndex, filter.length) + '</em>' +
                text.substr(startIndex + filter.length);
              $(this).find('a').html(html);
            } else {
              $(this).hide();
            }
          });
          $mainMenu.find('li ul li:visible:last').css('padding-bottom', '0.75rem');
        });
      } else {
        resetMainMenu();
      }
    });

    $clearButton.click(function() {
      $filterBox.val('').focus();
      $clearButton.hide();
      resetMainMenu();
    });

    function resetMainMenu() {
      $mainMenu.find('li').removeClass('ul-open open');
      $mainMenu.find('li').show();
      $mainMenu.find('li a em').contents().unwrap();
      $mainMenu.removeClass('filtered');
    }
});
</script>
```

```
<div class="main-menu-filter">
    <input type="text" class="input-filter" placeholder="{l s='Search' d='Admin.Actions'}">
    <a href="#" class="clear-filter"><i class="material-icons">clear</i></a>
</div>
```

`admin\themes\default\public\theme.css`

```
.main-menu .filtered .link-levelone > .submenu > li:first-of-type,
.main-menu .filtered .link-leveltwo > .submenu > li:first-of-type {
    padding-top: 0px;
}
.main-menu .link em {
    color: #25b9d7;
    font-style: normal;
}
.page-sidebar-closed .main-menu-filter {
    display: none
}
.main-menu-filter {
    position: relative;
    padding: 0;
    border-radius: 4px;
    margin: 0 0.25rem 1rem 0.25rem;
}
.mobile-nav .main-menu-filter {
    margin: 1rem 0.5rem 0 0.25rem;
}
.main-menu-filter .input-filter {
    border-radius: 4px;
    background: #bebebe;
    border: none;
    padding: 6px;
    outline: none;
    width: calc(100% - 12px);
    font-size: 12px;
}
.mobile-nav .main-menu-filter .input-filter {
    padding: 6px 8px;
    width: calc(100% - 18px);
    font-size: 16px;
}
.main-menu-filter .input-filter:focus {
    background: #fff;
}
.main-menu-filter .clear-filter {
    position: absolute;
    top: 1px;
    right: 4px;
    display: none
}
.mobile-nav .main-menu-filter .clear-filter {
    top: 3px;
    right: 8px;
}
.main-menu-filter .clear-filter .clear {
    color: #363a41;
}
.main-menu-filter .clear-filter .clear:hover {
    color: #202226;
}
```

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/ux-team @NeOMakinG wdyt?

**Comment by prestascott** [comment]
Hello everyone,

Thank you @mparvazi for your suggestion :)

Why wouldn't you use the search input in the header to look for the specific page instead of creating a new one?

**Comment by mparvazi** [comment]
Hello @prestascott 

This is an **instant search** by focusing in the main menu items (filtering by jquery). 
It works just by searching DOM elements and looks like settings page search in Chrome and Firefox.

> Why wouldn't you use the search input in the header to look for the specific page instead of creating a new one?

I think the search input in the header just works with POST method and searches via database.

Thanks for feedback.

**Comment by NeOMakinG** [comment]
I like the feature, but I think we would love to have some small mockups from @prestascott if everyone agrees about adding it

**Comment by prestascott** [comment]
This is a really cool feature I admit it, but I'm not convinced that the search input belongs in the navigation drawer because this might be identified as a duplicate of the actual. Also, we must keep it simple and avoid overloading the back office with new components.

Imo, we should fix and improve the current search bar in the header which is buggy, by adding your feature to it. 

Are you willing to contribute even if there is more work to do? ✌️

**Comment by hibatallahAouadni** [comment]
Hello everyone,

As we discussed to rework the search bar. 
So, I have to close this issue as a duplicate of this one #14546 
Please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #14546

**Comment by hibatallahAouadni** [comment]
Sorry for closing the issue too early :sweat_smile:

**Comment by mparvazi** [comment]
The current search method in BO isn't helpful and kinda old!
It should be **instant** and **smart**.
There is a lot of information in database that can be used by search engine.

Updating the current search method requires more works and more analysis.
But I'm interested in it.

The most important feature that need to be added is the main menu items (Admin pages) in a smart way.
For example, the 'Languages' link isn't in the main menu, but when user searches for it, the 'Localization' page link must be displayed.

Something like this:

<img src="https://user-images.githubusercontent.com/85633460/140373113-c4ad53b5-ec50-413b-91e2-738dfc893b25.png" width="600"/>

**Comment by hibatallahAouadni** [comment]
Let's wait for @prestascott mock ups :wink:

**Comment by mparvazi** [comment]
Does adding instant search feature make too many connections?
Searching in Catalog, Orders, Customers, Settings, Invoices, Carts and Modules each time user enters a character.
Most users use shared hosting which has `max_user_connections` limit for database.
🤔

**Comment by mparvazi** [comment]
**My suggestion:**
1. The main menu search will be bind to the header search input.
2. The results doesn't affect main menu in sidebar and will be displayed as drop down.
3. Instant search will be enabled just for main menu search (Not for Catalog, Orders, Customers,...).
(I recommend this because of [performance issues](#issuecomment-961294983))
4. For back-end a new function for instant search will be added to the Admin Search Controller.
5. The instant search function works through sending SQL query to `ps_tab` table in database.
(The main menu items are stored in this table)
6. For front-end two templates must be implemented, one for default-theme and one for new-theme.
(These two templates are same in appearance but a little different in coding)

**Mock-up:**

<img src="https://user-images.githubusercontent.com/85633460/140494369-0965d98a-7ed6-430e-a0f5-1184f78f0135.png" width="550"/>

<img src="https://user-images.githubusercontent.com/85633460/140494716-5b7e95e8-be6b-4cb8-b1cf-a36436365a8f.png" width="550"/>

**Comment by mparvazi** [comment]
@hibatallahAouadni 

The Core Development Team must be checked [this](#issuecomment-961780886).

I didn't test this solution, I just dreamed about that last night 😉

**Comment by Hlavtox** [comment]
@mparvazi So good!!!

**Comment by prestascott** [comment]
@mparvazi Wow, you're really motivated and I love that!

Can you join the Slack Open source please so it will be easier for me to discuss with you 🙏

**Comment by mparvazi** [comment]
@prestascott 

What should i do for joining?

**Comment by hibatallahAouadni** [comment]
@mparvazi you should create an account https://prestashop.slack.com/

**Comment by mparvazi** [comment]
@hibatallahAouadni 

It seems I should get an invitation link.

Right?

**Comment by hibatallahAouadni** [comment]
> It seems I should get an invitation link.

No, you do not need an invitation link :wink: 

Please follow the attached screen record below to create a new account (via gmail or Apple ID):

https://watch.screencastify.com/v/XLvbuo1H8yB1eaEHn6rz

Then to connect:

https://watch.screencastify.com/v/c2FggEtMdKAiDfSFYaU1

**Comment by mparvazi** [comment]
@hibatallahAouadni 

https://prestashop.slack.com
Sign in with Google
Screenshot:
![Screenshot 2021-11-05 185720](https://user-images.githubusercontent.com/85633460/140535881-304a185c-322e-40ea-a5d7-5cbd9b7f9e10.png)

**Comment by marionf** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/27185

**Comment by Hlavtox** [comment]
How is that a duplicate of issue you created 7 minutes ago?

**Comment by prestascott** [comment]
@Hlavtox Because she created a new one, which is updated. :)

**Comment by Hlavtox** [comment]
Yeah but no way to tell @mparvazi was the original author of the idea. 👍

**Comment by mparvazi** [comment]
@Hlavtox 
Ty.
It's OK. I prefer this current annoying search bar change ASAP.
We were in contact at Slack.
