### ISSUE TITLE
BO - New tax rule page - the State field and the Zip/Postal are not aligned

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#26491]
#### Describe the bug

In the BO > Taxes > Tax rule page, in the "add new tax rule" section, the `State` field and the `Zip/Postal code range` filed are not aligned.

#### Steps to Reproduce

1. Go to BO > Taxes > Tax rule page
2. Edit a tax rule
3. Click on "Add tax rule"
4. Select a country with states (for example United states)
5. See error:  the State field and the Zip/Postal are not aligned
![image](https://user-images.githubusercontent.com/16067358/139525874-0b39ba8d-f967-4061-9a8a-ef7a43b9622e.png)

In the PS1778 => ok
![image](https://user-images.githubusercontent.com/16067358/139525917-815a8400-6294-4100-8fdc-e75ab9635701.png)

#### Additional information

* PrestaShop version: 1780
* PHP version: 7.1
* Google Chrome Version 79.0

**Comment by mparvazi** [comment]
Hello @khouloudbelguith 

This happens in pages that are using legacy theme.

BO > Attributes > Edit an attribute group

![ONE](https://user-images.githubusercontent.com/85633460/139596170-3f720eae-0805-4c67-a28f-c177f4dc3308.png)

Usually occurs in forms from table grids looks like this:

![ONE](https://user-images.githubusercontent.com/85633460/139590356-8a5724da-0c3f-48fd-af11-9c1070b43467.png)

Edit button has an icon with text label (legacy theme).

**Comment by mparvazi** [comment]
**Configure**
Shop Parameters > Order Settings > Statuses > Edit an item
Shop Parameters > Customer Settings > Groups > Edit an item
Shop Parameters > Contact > Stores > Edit an item
Shop Parameters > Search > Tags > Add new tag

**Improve**
International > Taxes > Tax Rules > Edit an item > Add a new tax rule

**Catalog** 
Attributes & Features > Attributes > Edit an item
Attributes & Features > Features > Edit an item

**Comment by khouloudbelguith** [comment]
Hi @mparvazi,

>**Catalog**
Attributes & Features > Attributes > Edit an item
Attributes & Features > Features > Edit an item

Fixed by:
https://github.com/PrestaShop/ps_facetedsearch/pull/433
https://github.com/PrestaShop/PrestaShop/pull/24580

**Comment by Progi1984** [comment]
A part has been fixed.

Remains :

**Configure**
Shop Parameters > Order Settings > Statuses > Edit an item
Shop Parameters > Customer Settings > Groups > Edit an item
Shop Parameters > Contact > Stores > Edit an item
Shop Parameters > Search > Tags > Add new tag

**Improve**
International > Taxes > Tax Rules > Edit an item > Add a new tax rule

**Comment by marionf** [comment]
We should create an issue for each page if there are several PRs
