### ISSUE TITLE
Autoupgrade - Error during upgrade to develop

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#26503]
#### Describe the bug

There is an error during the autoupgrade to the 8.0.0.

#### Expected behavior

Autoupgrade to develop is possible with no error.

#### Steps to Reproduce

1. Create a release 8.0.0 using (php tools/build/CreateRelease.php) from develop branch
2. Autoupgrade the version 1.7.8.0 to 8.0.0 using local archive 
3. See error.

**Screenshots**
![image](https://user-images.githubusercontent.com/89604350/139855445-f5e573eb-75d1-4a67-a758-f066ddd5d6d6.png)

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: develop
* PHP version: 7.3
* 1-click upgrade 4.13.0

**Comment by jolelievre** [comment]
This is due to the removal of the deprecated method in this PR https://github.com/PrestaShop/PrestaShop/pull/26309

The autoupgrade module needs to be updated so that it doesn't use this method anymore.

**Comment by jolelievre** [comment]
I proposed a fix in this PR https://github.com/PrestaShop/autoupgrade/pull/434 but I have questions regarding retro compatibility of the `autoupgrade` module I'd like some feedback from core developers @PrestaShop/prestashop-core-developers

**Comment by Progi1984** [comment]
Fixed by @jolelievre & @atomiix and tested by @khouloudbelguith
