### ISSUE TITLE
Move VueJS components outside of new-theme and make a reliable library

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#26510]
#### Is your feature request related to a problem?

As you know, somes pages of the Back Office are made with VueJS and there is somes components make inside the new-theme of the Back Office.

Somes modules, likely the PrestaShop Essentials, are based on VueJS and somes like the wishlist use it too.
Then, the RBM model need (for the moment) it's use in order to re-use the VueJS Accounts Component.

#### Describe the solution you'd like

Something that could be cool will to have an official supported package of this VueJS components (and others basic components as grid) with, in addition, the UI Kit transplant to Vue.

#### Alternatives you've considered

Nothing else, there. Only the possibility to make it on my own way and that, one day later maybe, PrestaShop take this project for itself.

#### Additional context

n/a

**Comment by NeOMakinG** [comment]
Completely agree with this

And as you told me, you want to start it by yourself right?

wdyt @PrestaShop/prestashop-maintainers ?

**Comment by PrestaEdit** [comment]
Yes, I could make this firstly on my side (and/or inside a GitHub repo maintains by PrestaShop) to start the project and having the community help us to achieve it as needed, for sure.

**Comment by matks** [comment]
Overall I agree this is a good idea. I will just provide some warnings:

1) if you move VueJS components outside of new-theme to reuse them in a module, it means that your module will not be able to use the version you want for these components.

If module is installed on PS 1.7.8, it will use the components of 1.7.8, if it is installed on PS 8.0.0, it will use the components of 8.0.0 . If the components are different (could be different versions), you will have to handle the range.

2) this makes the contribution process a little bit harder. If we do this idea, this means that tomorrow ; to change a VueJS component on PS 8.0.0 you need to
- submit a PR to the VueJS components repository
- release a new version of this repository
- update the version used in the Core
- and maybe add some more code in the Core as we probably wrap a bit the component, provide it some config

This is OK if our VueJS components are mature and stable in time. This is not good if we modify them every 3 days as we are exploring. So we'll have to be careful about what we put in the library and what stays in the Core.

3) we will have to state a public API promise. people will start using this library, and we will use it in the Core ; what can we change, what can we break, what should we preserve ?

**Comment by PrestaEdit** [comment]
Something that we can make is to make a VueJS libary and keep the core cloned version, as this there is no issue with the core/changes and the library could manage ranges/versions as needed, surely.

It's maybe possible to get a 0.0.1 version (or something as it) with the actual VueJS components, on which the core could rely. It's an idea, not maybe the things todo, of course :)

**Comment by NeOMakinG** [comment]
What about exporting these components to an npm module directly from the core ? We would have a folder dedicated to the npm module inside the core, with his own package.json, with an index.ts importing every vue components and exporting them, so it will be directly linked to the core itself without a secondary repository

And the core will rely on the components locally, while external works could rely on the npm module version-sticked to the core
