### ISSUE TITLE
BO - The tax Name field accept some invalid characters

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#26515]
#### Describe the bug

When adding a new Tax in the Name field, it is possible to accept `;` and `#` whereas these characters are mentioned as invalid characters according to the message displayed at the bottom of the field

#### Expected behavior

The field should accept every character.

#### Steps to Reproduce

1. BO>IMPROVE>International>Taxes
2. Click On Add new tax button
3. Enter Name of Tax with `; `and `#` 
4. Enter a Rate
4. Click On Save
5. See error > the tax is saved

**Screenshots**

![Tax](https://user-images.githubusercontent.com/92912932/140297399-71c66ab8-9ac8-4ead-b6e8-dc89d85ad6c6.png)

#### Additional information

* PrestaShop version: 1.7.8.0 & develop
* PHP version: 7.3

**Comment by MatShir** [comment]
@PierreRambaud another one 🤔, IMO this field needs should accept every character. What do you think ?

**Comment by PierreRambaud** [comment]
@MatShir I couldn't agree more with you!
