### ISSUE TITLE
Bad gateway installing ps_googleanalitycs V.4.1.0 on PS 1.7.8.0

### ISSUE THREAD

**Issue by santos0289** [PrestaShop/PrestaShop#26516]
#### Describe the bug

Error 502 (bad gateway) after installing `ps_googleanalytics`
HI! I dont't know if its a bug of the module, or my version of prestashop.I have troubles installing google analytics module.

#### Steps to Reproduce

1. BO>IMPROVE>Modules>Module Catalogue
2. Install  `ps_googleanalytics`
3. See error > 502 error (bad gateway). 
4. I delete the folder `ps_googleanalytics` from Modules under my project
5. Then, I try to reinstall it version 4.1.0
6. See error > error 502 (bad gateway).

**Screenshots**
![image](https://user-images.githubusercontent.com/23308427/140304352-79fbc0ec-d11d-496b-aac5-7dcba29176ce.png)

Sorry about my english im new here!

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.3.32

**Comment by hibatallahAouadni** [comment]
Hello @santos0289 

> Sorry about my english im new here!

Welcome :tada: and you did well (respecting the template and providing a screenshot) :clap: 
I edit your issue description and hide your shop URL (in the screenshot) :wink: 

I didn't manage to reprodcuce the issue with PS1780, see the attached screen record below:

https://watch.screencastify.com/v/DI6Vf0TL5GYtGDUPdGsb

Could you please enable the debug mode and check the displayed error.
Please check and feedback.

Thanks!

**Comment by santos0289** [comment]
Thank's for the answer but, i do the same thing with the debug mode enabled and when istall the analytics module (version 4.1.0 of github) same error...(page in blanc, and when I go to the back office it's appear error 502).se the screen recorder (attached)

https://user-images.githubusercontent.com/93709131/140314732-bfab0201-76cb-4c25-b80c-88a44cd85ad8.mp4



I have to say that I cant see the module in BO>IMPROVE modules>module catalogue. May be don't appear because i have to rename or delete the folder of the module ps_googleanalytics for work on it (otherwise if I not delete/rename that folder it occurs error 502).

**Comment by hibatallahAouadni** [comment]
Hello @santos0289 

Try to disable the cache following these settings, click on Save, then click on Clear Cache:

![image](https://user-images.githubusercontent.com/23308427/140382583-6e4c1852-4f24-4235-8800-b76343b9cf77.png)

Then check if you still encounter the issue.
Please check and feedback.

Thanks!

**Comment by santos0289** [comment]
Hi, same problem.I dissable cache, then save and then clear cache. 
I go to IMPROVE>modules>module catalogue and don't appears analitics module, so I install again github's ps_googleanalitycs V.4.1.0 and after install and go again to modules or other BO part, same error (502 bad gateway). Then i have to rename/delete the module for work on it.

Thanks for the support.
I will waitting for more info of this problem.

**Comment by hibatallahAouadni** [comment]
Hello @santos0289 

> so I install again github's ps_googleanalitycs V.4.1.0 and after install and go again to modules or other BO part, same error (502 bad gateway). 

No, you didn't need to install the module from Github :sweat_smile:
Please follow these steps to install ps_googleanalytics:

1. BO>IMPROVE>Modules>Module Catalog
2. Search for google
3. Click on Install button

See the screen record: https://watch.screencastify.com/v/DI6Vf0TL5GYtGDUPdGsb
Please check and feedback.

Thanks!

**Comment by santos0289** [comment]
> 
> 
> Hello @santos0289
> 
> > so I install again github's ps_googleanalitycs V.4.1.0 and after install and go again to modules or other BO part, same error (502 bad gateway).
> 
> No, you didn't need to install the module from Github 😅 Please follow these steps to install ps_googleanalytics:
> 
>     1. BO>IMPROVE>Modules>Module Catalog
> 
>     2. Search for google
> 
>     3. Click on Install button
> 
> 
> See the screen record: https://watch.screencastify.com/v/DI6Vf0TL5GYtGDUPdGsb Please check and feedback.
> 
> Thanks!

I do that(see the screen record)

https://user-images.githubusercontent.com/93709131/140510722-478ca899-8605-4968-b2d5-46ac7912c8a6.mp4

, but I install github one because it don't appear's in BO>IMPROVE>Modules>Module Catalog
I think there is a strange problem, because when I install for first time (I istalled from >Module Catalog), and appears the 502 error, i have to delete the folder ps_googleanalytics. So I think that there is samething that says "it is stalled" (because I delete the folder from archives, to work with the page (otherwise, it gives 502 error).

Thanks again!!!

**Comment by khouloudbelguith** [comment]
Hi @santos0289,

I did not manage to reproduce the issue with PS1780 and ps_googleanalytics v4.1.0.
https://watch.screencastify.com/v/P0Gwg6I4Znyo3Vg9h5r3

Could you please check that your module doesn't exist on the Module manager page before searching it in the BO > Module catalog page?.
Can you please search with the module name `ps_googleanalytics`.

Please check and feedback.

Thanks!

**Comment by ghost** [comment]
Hi @santos0289, maybe you should post your nginx configuration?

**Comment by santos0289** [comment]
> 
> Hi @santos0289,
> 
> I did not manage to reproduce the issue with PS1780 and ps_googleanalytics v4.1.0. https://watch.screencastify.com/v/P0Gwg6I4Znyo3Vg9h5r3
> 
> Could you please check that your module doesn't exist on the Module manager page before searching it in the BO > Module catalog page?. Can you please search with the module name `ps_googleanalytics`.
> 
> Please check and feedback.
> 
> Thanks!

Hi @khouloudbelguith !!!Yes I check if the module exists on module manager, and don't appear. The reason is than when I have the 502 error (bad gateway) when I install the analytics module, I have to delete the folder ps_googleanalytics to work on the page(because the error, I can't uninstall).
I think that if I delete the folder, for prestashop maybe its installed somewere (because really I can't uninstall, only delete the folder).That's why I think that don't appears in BO>IMPROVE>Modules>Module Catalogue and also in >Module Manager(in module manager don't appear because I delete the folder).

Thak you for the aswer!!!

**Comment by santos0289** [comment]
> 
> 
> Hi @santos0289, maybe you should post your nginx configuration?

Yes of course @chrislais .I don't Know  if I have to uncheck "the marked red arrow" thing. The traduction in english is this: 

"Intelligent processing of static files.  If this option is disabled, Apache will process all requests for static files. nginx will just pass requests and responses without modifying them. Disable this option for troubleshooting only."

![Screenshot 2021-11-06 at 12-04-42 Configuración de Apache y nginx para smsportnutrition com - Plesk Obsidian 18 0 38](https://user-images.githubusercontent.com/93709131/140607698-05ac1e3c-a624-4e57-8e1a-9fbf2218414c.png)

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers could someone please try to reproduce the issue :pray:

**Comment by santos0289** [comment]
At least I have SOLVE THE PROBLEM!!!:clap:
I have one issue with the cache because when I go to BO>IMPROVE>Modules>Module Catalog its appears the compile error" Failed opening required '/var/www/vhosts/..../httpdocs/modules/contactform/recaptcha.php'.

So I first rename contactform module (otherwise i can't go to Modules>Module Catalog). Then I go again to >Modules>Module Catalog and I Uninstall recaptcha because I think that there was an error. 
Then I put the correct name to Modules/contactform,
but when I go again to <Modues>module Catalog I see the same error!!!I can't beleive it because recaptcha was uninstalled, and yes, when i do this actions I allways delete the cache, from BO>CONFIG>advanced parameters and the navegator cache,  but not results. (i was in debug mode).

So I go to the archives and remane(for be cautious) all folders of  var/cache (/prod  /dev  and /pro_) and the problem was solved.So Install Recaptcha again.

Because of this, I think...what will be occurr if I rename with the correct name the ps_googleanalytics? (remember that I have to rename because of the error 502 (bad gateway) when I use this module). So I rename with the correct name and Works fine!!!!

So I deduct that it was a cache error that causes the error 500 (internal server error) of the contactform and de error 502 (bad gateway) of the ps_googleanalytics module.

**Comment by matks** [comment]
@hibatallahAouadni Thanks to reporter who told us the news, it looks like the root issue was cache and involved multiple modules installed. I remove the `waiting-for-dev` label.

**Comment by hibatallahAouadni** [comment]
Thanks @matks & @santos0289 for your feedback.
