### ISSUE TITLE
HTTP ERROR 500 after updating modules

### ISSUE THREAD

**Issue by eveneme** [PrestaShop/PrestaShop#26517]
#### Describe the bug

Update modules no matter what and ERROR 500

#### Steps to Reproduce

1. Go to Modules
2. Click on Update modules
3. Click no matter what dashboard etc.
4. See error ERROR 500
5. The same happens when installing a new module

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.8.0 in previous versions this was also the case. 
* Apache
* PHP version: 7.4

**Comment by kpodemski** [comment]
Hello again @eveneme,

It must be related to your installation / environment. "Error 500" says nothing, you should see a proper error message if you enable developer mode.

**Comment by hibatallahAouadni** [comment]
Hello @eveneme 

Could you please enable the debug mode and open your navigator console, then please make a screen record or screenshot of the displayed error :pray: 
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @eveneme 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
