### ISSUE TITLE
Problem with ToggleColumn in Admin Grid 

### ISSUE THREAD

**Issue by abramofranchetti** [PrestaShop/PrestaShop#26523]
#### Describe the bug

When adding a toggle column as in the dev-guide (https://devdocs.prestashop.com/1.7/modules/sample-modules/grid-and-identifiable-object-form-hooks-usage/) in a grid that does not have any togglecolum in standard configuration (ex Admin Address grid) the toggle column does not trigger the ajax call to the controller.

#### Expected behavior

toggle column must trigger an ajax call to the controller

#### Steps to Reproduce

Follow the guide at dev docs (https://devdocs.prestashop.com/1.7/modules/sample-modules/grid-and-identifiable-object-form-hooks-usage/) to create a module that add a column to a grid,

**but instead of add a column to the customers grid, add a toggle column to the customer addresses grid (in the prestashop admin->customer->addresses)**

yuo'll see that the toogle column does not trigger the ajax call to the controller.

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.1

**Comment by khouloudbelguith** [comment]
Hi @abramofranchetti,

Thanks for your report.
There is an example of Admin of Grid of the Orders page.
Thanks @atomiix https://github.com/PrestaShop/PrestaShop/issues/24911

--------------------------------------------------------------------------------------

Create new table `app_order_table` with `id_order`
![image](https://user-images.githubusercontent.com/16067358/138904529-f6c4d729-779d-4beb-85e3-427af06eaab3.png)

Install the module [ps_qualityassurance](https://github.com/PrestaShop/ps_qualityassurance), add two hooks:

`actionOrderGridQueryBuilderModifier` with this content:
```php
$searchQueryBuilder = $params['search_query_builder'];
$countQueryBuilder = $params['count_query_builder'];

    $searchCriteria = $params['search_criteria'];

    $searchQueryBuilder->addSelect(
        'app.`id_order` IS NOT NULL AS `from_app`'
    );

    $searchQueryBuilder->leftJoin(
        'o',
        '`app_order_table`',
        'app',
        'app.`id_order` = o.`id_order`'
    );
	$countQueryBuilder->leftJoin(
        'o',
        '`app_order_table`',
        'app',
        'app.`id_order` = o.`id_order`'
    );

    if ('from_app' === $searchCriteria->getOrderBy()) {
        $searchQueryBuilder->orderBy('app.`id_order`', $searchCriteria->getOrderWay());
    }

    foreach ($searchCriteria->getFilters() as $filterName => $filterValue) {
        if ('from_app' === $filterName) {
            $searchQueryBuilder
              ->andWhere('app.`id_order` IS ' . ($filterValue ? 'NOT' : '') . ' NULL');
          $countQueryBuilder
              ->andWhere('app.`id_order` IS ' . ($filterValue ? 'NOT' : '') . ' NULL');
        }
    }
```

and `actionOrderGridDefinitionModifier` with this content:
```php
$definition = $params['definition'];

    $definition->getColumns()->addAfter(
        'date_add',
        (new PrestaShop\PrestaShop\Core\Grid\Column\Type\BooleanColumn('from_app'))
            ->setName($this->l('App order'))
            ->setOptions([
                'field' => 'from_app',
                'true_name' => $this->trans('Yes', [], 'Admin.Global'),
                'false_name' => $this->trans('No', [], 'Admin.Global'),
                'clickable' => true,
            ])
    );

    $definition->getFilters()->add(
        (new PrestaShop\PrestaShop\Core\Grid\Filter\Filter('from_app', PrestaShopBundle\Form\Admin\Type\YesAndNoChoiceType::class))
        ->setTypeOptions([
            'required' => false,
        ])    
        ->setAssociatedColumn('from_app')
    );
```

Now, go on the page Order and find the new filter
![image](https://user-images.githubusercontent.com/16067358/140491754-cf4fb28d-fc28-4afd-8f78-ef0bde5f54ec.png)


I hope this helps you!
On this github repository there is no software support. This is an open-source project.

You can find help

- on PrestaShop forums https://www.prestashop.com/forums/
- or by purchasing software support plan from https://www.prestashop.com/en/support you!

Thank you!

**Comment by abramofranchetti** [comment]
i've found the problem.
The fact is that javascript grid extension is loaded in a compiled js, that in the standard load the required js grid extension (**ColumnTogglingExtension**) only in some pages. If you want to load in pages that does not have this estension loaded you have 2 ways: or add in the original js (in example for address admin page admin/themes/new-theme/js/pages/address/index.js) and then recompile the js... or in your module add a js and load the extension required.
In that case **prestashop 1.7.8 help us** because makes available the component in JS (https://devdocs.prestashop.com/1.7/development/components/global-components/) so you can now load the core component. But is pure luck because if i was using prestashop 1.7.6 80 I would not have been able to load the requested extension without big code turns.......


The **ugly ugly** thing is that this is not a clean way of making a standard. If you allow me to add, through the use of a module hook (in example **hookActionAddressGridDefinitionModifier**), a column to a grid that should trigger a javascript ajax call (in the example toggle column https://devdocs.prestashop.com/1.7/development/components/grid/columns-reference/toggle/) **the standard should automatically load the required extension for that component**. 

This issue take me a day of work to figure out and solve the problem, but this is not a clean way to operate.

**Comment by abramofranchetti** [comment]
@khouloudbelguith yeah i know, but if you do that in a grid that have not already at least a togglecolumn, the togglecolumn component does not fire the ajax call to the controller.. Try adding a togglecolumn in the address admin grid (hookActionAddressGridDefinitionModifier) and you can replicate the issue. It is a standard ugly flaw, because adding a column to a grid throwght a hook, does not automatically load the eventually required grid js extension (in example ColumnTogglingExtension)

**Comment by abramofranchetti** [comment]
@khouloudbelguith please do not close the issue, but first try to replicate the problem and report that to the core dev team ;)

**Comment by khouloudbelguith** [comment]
@abramofranchetti, thanks for your feedback.
I will re-open the issue.
Ping @PrestaShop/prestashop-maintainers what do you think?


Thanks!

**Comment by kpodemski** [comment]
Hello @abramofranchetti 

As you noticed, you need to import the JS Grid extension that you want to use. At this moment, PrestaShop is not loading any JS automatically, and I'm not sure that we will because desired behavior may differ from developer to developer.

https://devdocs.prestashop.com/1.7/development/components/global-components/#global-javascript-components

If you use PrestaShop < 1.7.8 situation is a bit more complicated, you can - for example, copy the extension and load it into your module or implement the wanted behavior yourself. 

We're still working to make Grid to be as useful for developers as it could be, we appreciate your feedback ❤️

**Comment by abramofranchetti** [comment]
@kpodemski Thank you for your reply!
the only observation I would like to make is that if you allow a component like **toggle column**, that should **automatically** launch an ajax call (as in doc), to be added through a hook, the js part of the component should also be loaded somehow automatically... otherwise the behavior is different depending on where I insert the component! Or at least **put a warning** here https://devdocs.prestashop.com/1.7/development/components/grid/columns-reference/toggle/ 
specifying that the ajax call is subordinated to manual loading of the js extension and it is **not always true** that the component triggers the ajax call automatically unless the relative js grid extension is aready loaded by default (ex. in customer grid).

Thanks again for your reply and I hope I have been helpful ;)
Ciao.

**Comment by kpodemski** [comment]
@abramofranchetti 

I think we can start with more detailed documentation. Thanks again for your feedback, and have a lovely weekend 👍

**Comment by abramofranchetti** [comment]
@kpodemski 
it would be nice there was a method similar to the old one "**$this->addJqueryUI('ui.datepicker');**" in the "**ControllerCore**" class. which was used in modules to load jquery components

**Comment by hibatallahAouadni** [comment]
Ping @PierreRambaud could you please transfer this issue to https://github.com/PrestaShop/docs :pray: 
Thanks in advance.

**Comment by abramofranchetti** [comment]
i've updated the doc related to this component
