### ISSUE TITLE
Importing CVS (excel) file is very slow

### ISSUE THREAD

**Issue by uabhuntera** [PrestaShop/PrestaShop#26521]
Hello,

Where is a problem if CVS files importing are very slow? Did I have to update the prestashop or it's a problem with photoshop? And how to fix it?
For example, I am importing a file 9kB, it has 200 rows and 4 columns (ID, qty, reference, EAN). It takes to load about 20 min or more. (I just want update the existing information)
In the beginning, it was much more faster.
PrestaShop version: 1.7.5.2.
The steps in my back prestashop: Advanced parameters->import-> 'choose file' and etc.
![for example](https://user-images.githubusercontent.com/93715998/140316451-a0396fcc-f5d6-434a-a76e-f38a15e420e1.jpg)

**Comment by hibatallahAouadni** [comment]
Hello @uabhuntera 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
