### ISSUE TITLE
blockreassurance - Can't edit a block / can't add a new block

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#26531]
#### Describe the bug

I can't edit of add a new block to my module blockreassurance

#### Expected behavior

I should be able to edit and add new block without error

#### Steps to Reproduce

1. Go to BO > Modules > Search for blockreassurance
2. Uninstall blockreassurance module
3. Go to your shop files : `cd /Prestashop_path/modules`
4. Run the following 
```
git clone git@github.com:PrestaShop/blockreassurance.git
cd blockreassurance
composer install
```
5. Install the module
6. Configure the module > Content Tab > Edit : See error
7. Back in Content Tab > Add a new block > Save : See error

**Screenshots**

1- Can't save a new block https://drive.google.com/file/d/1OHlpY5g-2TPriMwImpo-Qi6kbrUAB9h8/view
<img width="1222" alt="Screenshot 2021-11-05 at 14 31 07" src="https://user-images.githubusercontent.com/16019289/140518161-4cebd0fb-f30d-45fd-b5dc-9c7f56da656d.png">
2- Edit page is not displayed https://drive.google.com/file/d/15cCJbYxO4-eE_i8abnuKZWsqfOqJevw-/view
<img width="1164" alt="Screenshot 2021-11-05 at 14 30 39" src="https://user-images.githubusercontent.com/16019289/140518126-25f4d1ff-2edb-4b65-a263-e5dbc195a534.png">

#### Additional information

* module blockreassurance dev branch
* PrestaShop version: 1.7.8.X & develop branch
* PHP version: 7.3

**Comment by ghost** [comment]
https://github.com/PrestaShop/blockreassurance/pull/209

**Comment by Progi1984** [comment]
Fixed by @atomiix in PrestaShop/blockreassurance#336 & Tested by @HanaRebaiQA
