### ISSUE TITLE
BO - Add new Order page - Incorrect scroll is displayed when we try to add a customized product

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#26535]
#### Describe the bug

In the BO > Orders > Add new Order page, when we try to add a customized product, there is an incorrect scroll displayed
![image](https://user-images.githubusercontent.com/16067358/140541153-8657c179-072c-480b-aac0-221dc28f5209.png)

#### Expected behavior

It is ok with PS1778
![image](https://user-images.githubusercontent.com/16067358/140541349-6a50f689-3868-4b81-b957-da664fd4a15b.png)

#### Steps to Reproduce

1. Go to BO > Orders > Add new Order page
2. Search a customer and choose it
3. Search for a customized product
4. See an error

#### Additional information

* PrestaShop version: 1.7.8.0, 1.7.8.1build1, 1.7.8.x, develop
* PHP version: 7.2

**Comment by Hlavtox** [comment]
I will fix it

**Comment by Progi1984** [comment]
Fixed by @Hlavtox in #26607
