### ISSUE TITLE
Translate Jquery Sentences

### ISSUE THREAD

**Issue by lthienard** [PrestaShop/PrestaShop#26541]
Hi,

It's possible to translate **Jquery** message ?

Example: When I use the search module I have this result displayed just above "**4 results are available, use up and down arrow keys to navigate.**"

Thank's

**Comment by matks** [comment]
Hi, it depends whether the string was built by PrestaShop or the module, that provide a translation system, or if the string comes from jQuery itself.

I cannot find the sentence 'use up and down arrow keys to navigate.' in https://github.com/prestashop/ps_facetedsearch so I think you may not use the default search module. If you use another, it depends if module allows translation or not.

**Comment by lthienard** [comment]
Sentence stored on:

[root]/js/jquery/ui/jquery.ui.autocomplete.min.js
[root]/js/jquery/ui/jquery-ui.js line 7186
[root]/js/jquery/ui/jquery-ui.min.js

**Comment by hibatallahAouadni** [comment]
Hello @lthienard 


Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
