### ISSUE TITLE
BO - Order page - Incorrect alert message when adding a discount or removing it and when updating a carrier 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#26547]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When the employee language is different from the customer language, in the BO > Orders > Order details page > when we try to add a discount or remove it => the successful alert message is displayed in the language of the customer and not the employee language.

### Expected behavior

If the employee language is English, the successful alert message should be displayed in English

### Steps to reproduce

1. You must have at least two different languages (Install the shop with English country and frensh language)
2. Create an order with the French language
3. The employee language is English
4. Go to BO > Orders > Open the last order created
5. Try to add a valid discount
6. Se error: the message is in French 
![image](https://user-images.githubusercontent.com/16067358/140734073-b080da81-784b-4963-8bed-9572f193034f.png)
![image](https://user-images.githubusercontent.com/16067358/140734121-60fca9c0-d851-4c7b-aa32-c7817065f02a.png)
7. Try to remove the discount 
8. Se error: the message is in French
9. Try to update the carrier 
8. Se error: the message is in French

### PrestaShop version(s) where the bug happened

1.7.8.0, 1.7.8.1build1

### PHP version(s) where the bug happened

7.2

**Comment by Progi1984** [comment]
Fixed in #26590 by @Progi1984 & Tested by @HanaRebaiQA
