### ISSUE TITLE
This form should not contain extra fields.

### ISSUE THREAD

**Issue by grabelle** [PrestaShop/PrestaShop#26554]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I added 1 extra field under "Information complémentaire" "vm_valide", the database is OK, the Product override is OK, the template is OK (I think)

![image](https://user-images.githubusercontent.com/5048627/140885740-37f1c5af-175d-4ea6-998b-f933ae8c0d67.png)

![image](https://user-images.githubusercontent.com/5048627/140885923-2f04fb36-3647-4fd3-bf3d-90cf7baad124.png)

when I save the product it return a 400 error : {"step1":["This form should not contain extra fields."]}

### Expected behavior

The data should be updated without any error.

### Steps to reproduce

This is a personnal module (I can provide it if needed)

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @grabelle ,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
