### ISSUE TITLE
Textarea on product page is hidden

### ISSUE THREAD

**Issue by rmntavares** [PrestaShop/PrestaShop#26555]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I upgrade to version 1.7.8.0 and textarea on product page in administration mode not show

### Steps to reproduce

1. Go to products page on administration mode and you don't see the textarea to description

### PrestaShop version(s) where the bug happened

1.7.8.0

**Comment by florine2623** [comment]
Hello @rmntavares ,

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
