### ISSUE TITLE
FO -  Quick view - The type of the product's cover image is incorrect

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#26557]
#### Describe the bug

The type of the product's cover image is meduim in the quick view. It should be large. 

#### Expected behavior

The cover image in the quick view should be large instead of medium. => The image size should be fix when changing the image in Quick View of a product with many pictures.

#### Steps to Reproduce

1. Go to BO > catalog > product> New product> Drop many images for the same product
2. Go to FO > Quick view > change the image >the size of the image changed 

**Screen Recording**
https://www.awesomescreenshot.com/video/5942183?key=feee82d7ca0c7d5463a767856a13f725
![image](https://user-images.githubusercontent.com/89604350/140903321-fe33334e-b60b-4c71-9d15-886a94c3c56b.png)

Same behavior is observed for 1.7.8.0

For 1.7.7.8 The cover image in the quick view is large

![image](https://user-images.githubusercontent.com/89604350/140902797-dd430e12-e0f6-4019-9716-af2af1de45db.png)

https://www.awesomescreenshot.com/video/5942651?key=fb6634462679643809efa182e270c673

#### Additional information

* PrestaShop version: 1.7.8.1 build1 , 1.7.8.0
* PHP version: 7.3

**Comment by NeOMakinG** [comment]
@marwachelly should it be large on the product page as well? It's the same image used

**Comment by matks** [comment]
@NeOMakinG What is the status of this bug? Is there something blocking, some information is missing?

I un-assigned you for now (until answer) if you don't work on it anymore, so someone else can take it ;)

**Comment by NeOMakinG** [comment]
I was probably waiting for the improvement of the images, but It's a regression and should be fixed on 1.7.8.x so I will probably take a look

**Comment by MeKeyCool** [comment]
I don't understand the status of this ticket.
I see it at `ready` in the project kanban view but the but removed the `ready` tag and added `needs specs`.
There is a `PR available` tag but I don't see any that solves the issue.

@NeOMakinG did you take a look ? Have you implemented anything ? Do you want any help ?

**Comment by NeOMakinG** [comment]
> Change product image size from medium to large #26702

I did a PR but closed it because we needed to find a proper way to fix it

There are some tickets related to the image system which should definitely fix it on develop, but the problem remains on 1.7.8

I think I talked with @lramos-prolaser , but if he's not able to work on it, you can definitely get a look if you want

Overwise I can plan to find a proper way later in the week

**Comment by MeKeyCool** [comment]
Thanks for answers !
I take it then ^^

**Comment by MeKeyCool** [comment]
Hi all ! I have a question to @Hlavtox about a regression I would like to solve and a PR you did ^^

When I investigate about [current regression](https://github.com/PrestaShop/PrestaShop/issues/26557)
It looks that @NeOMakinG had a solution : https://github.com/PrestaShop/PrestaShop/pull/26702/files 
But he closed it cause of suspicions of "vision" conflict (see @matks  and @jolelievre comments)

With more investigations, I found those comments :
```php
src="{$product.default_image.bySize.medium_default.url}"
```
> One last question, why not keeping the large image (using the large size in the image attributes) but this should now display correctly thanks to the `img-fluid` no? This way it ensures us to have a good quality
>
> _Originally posted by @jolelievre (Jonathan LELIEVRE) in https://github.com/PrestaShop/PrestaShop/pull/25343#discussion_r671331522_

> @jolelievre (Jonathan LELIEVRE) Because then you are loading an image 4x bigger for nothing. It's selfish to load 200kB image instead of 50 kB only because it looks better on a Mac. All other users would only experience slow down in page load, lower score in Google pagespeed and worse SEO.
>
> To benefit of increased resolutions on scaled displays, you should use srcsets. On anything above 100%, the browser will choose the bigger photo. Or not, it can maybe even adjust it's behavior on low-data-consumption modes.
>
> `<img src="/photo.jpg" srcset="/photo_2timesbigger.jpg 2x">`
>
>_Originally posted by @Hlavtox in https://github.com/PrestaShop/PrestaShop/pull/25343#discussion_r671355642_


My first idea is that @NeOMakinG proposal is right according @marwachelly product vision. What do you think 
@PrestaShop/product-team ?
Maybe I don't have all elements. What do you think @Hlavtox ? Do you have any other element ?

**Comment by Hlavtox** [comment]
@MeKeyCool For now (and for classic theme) it should be fixed by loading one properly sized image. (Not larger than needed).

For the new theme:
- Everything will be done by srcsets.
- The javascript of the theme must not rely on any hardcoded image sizes. So we allow people to customize them completely.

**Comment by NeOMakinG** [comment]
> @MeKeyCool For now (and for classic theme) it should be fixed by loading one properly sized image. (Not larger than needed).
> 
> For the new theme:
> 
> * Everything will be done by srcsets.
> * The javascript of the theme must not rely on any hardcoded image sizes. So we allow people to customize them completely.

I guess there is something wrong with this because the image is shared between multiple views, we should be careful about every images sizes

**Comment by MeKeyCool** [comment]
As discussed with @NeOMakinG, we have to investigate why this regression was introduced (which implied the concerned image is shared) and to ensure everything alright with all concerned behavior.
I'll try to check this with @marwachelly ^^

**Comment by marwachelly** [comment]
@MeKeyCool ,
The issue is reproduced using the attached image:
![images](https://user-images.githubusercontent.com/89604350/162745608-2a848b65-5d4b-40b0-b7e6-cc2cce36811a.jpg)
But starting from certain image size the problem does not reoccur
![MV5BMTdiNDIyMGEtNWJjMi00ODlhLWJhM2EtYjJjMjFlMjNhNDEwXkEyXkFqcGdeQXVyODg3NDc1OTE@ _V1_FMjpg_UX1000_](https://user-images.githubusercontent.com/89604350/162747071-248001fb-b369-49c5-b092-e6a8c24643db.jpg)

Thanks,

**Comment by MeKeyCool** [comment]
After further investigations, problem comes from inconsistency between page template and some js that update image sizing dynamically. @NeOMakinG confirmed that specifications are not clear between product view, quick view and maybe other product pages.

@PrestaShop/product-team we need you !! :ambulance:
Please could you decide if you want medium or large image for product views ? 
> :point_up: As we have some dependencies, any change could impact other parts. It is important to have all cases to validate everything at the same time.

**Comment by matks** [comment]
I add the label then ;)

**Comment by MatShir** [comment]
The image format expected on the classic theme.

Element | Page | Image format
-- | -- | --
Product cover | Product Page | medium-default
Product modal | Product Page | large-default
Thumbnail | Product listing | home-default
Quick view | Product listing | large-default
Category image description | Category page | category-default
Subcategories | Category page | category-default

**Comment by Progi1984** [comment]
Fixed by @MeKeyCool in #28426

**Comment by MeKeyCool** [comment]
Fixed in v8 with https://github.com/PrestaShop/classic-theme/pull/29
