### ISSUE TITLE
the printify module passes in about out of stock items, but not acted upon

### ISSUE THREAD

**Issue by johnwayne4d** [PrestaShop/PrestaShop#26563]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

when a printify item goes out of stock, that data gets communicated to prestashop, but instead of prestashop marking it as out of stock, image color selections are misaligned for the out of stock item and the order allowed to progress.

### Describe the solution you'd like

would like the prestashop interface to acknowledge the out of stock data transmission by displaying the product as out of stock / back ordering. so the order can complete with the visitor knowing that that out of stock item will be a back order and may take longer.

**Comment by hibatallahAouadni** [comment]
Hello @johnwayne4d 

Your issue must be addressed to the module developer itself.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you
