### ISSUE TITLE
FO - The label of product is displayed in stock while it is out of stock

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#26576]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When displaying the product details in FO, the label is `in stock` while it is `out of stock` for an Out-Of-Stock behavior of an product (when quantity in stock is less than the minimum quantity for sale) 
And when we increase the quantity and then return to the default quantity, the label is correctly displayed

See video :
https://www.awesomescreenshot.com/video/5974048?key=677e2c1709627b0605d073a8cfa0779f 

### Expected behavior

The label must be Out-of-Stock in the detailed product

### Steps to reproduce

1. Create a product with (quantity = 5 && Minimum quantity for sale = 11)
2. Click on `Preview` 
3. In FO>Detailed Product
2. See the label below quantity (in stock)  ==> NOK 
3. See error > The label is incorrectly displayed
3. Increment quantity and then return to the initial one (the message is correctly displayed) ==> OK

### PrestaShop version(s) where the bug happened

1.7.7.8 & 1.7.8.0 & 1.7.8.1

### PHP version(s) where the bug happened

7.3

**Comment by khouloudbelguith** [comment]
Hi @HanaRebaiQA,

This issue is fixed with this PR: #24798
https://watch.screencastify.com/v/10PGB97p8xYO72kM6TAw

I will close the issue.

Thanks!

**Comment by HanaRebaiQA** [comment]
Hello @khouloudbelguith 

Well Done
Thanks
