### ISSUE TITLE
bounce rate error

### ISSUE THREAD

**Issue by Jara65** [PrestaShop/PrestaShop#26573]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello. I have a problem with the measurement in google analytics of the bounce rate of my store, because the general bounce rate is below 1.5%, and this is because some pages show me bounce rates of 0% and others of 100%.

I have prestashop is 1.6.1.14, the Analytics module is 2.3.4 and the template is warehouse.

### Expected behavior

I hope to know how to correct the error, so that I can measure the real bounce rate

### Steps to reproduce

1. Google Analytics > Behavior >Site content>All page

### PrestaShop version(s) where the bug happened

1.6.1.14

### PHP version(s) where the bug happened

5.6

### If your bug is related to a module, specify its name and its version

Analytics 2.3.4

**Comment by hibatallahAouadni** [comment]
Hello @Jara65 

PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).

Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

Thank you
