### ISSUE TITLE
BO - The content of help menu is displayed on entire page 

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#26579]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When clicking on `Help` button, the content is displayed on entire page and not in the pop-up of Help Menu. 
For example : 
- Design >Theme & Logo > Add new Theme
- SELL > Catalog > Category > Edit a category
See image : 
![image](https://user-images.githubusercontent.com/92912932/141283398-38c70ae2-8a4f-4aaf-ab9a-84d9f5026e06.png)

See video : 
https://www.awesomescreenshot.com/video/5975549?key=7a854cc0d40403079f27b3cb586e17f4

### Expected behavior

The text of help menu must be displayed in the pop-up of Help menu

### Steps to reproduce

1. In BO
2. Go to International > Localization > Currencies > Edit currencies > Click on Help Button > See Error
3. Go to Shop Parameters > Traffic & SEO > SEO & URLs > Add and Edit > Click on Help Button > See Error 
4. Go to Advanced Parameters > WebService > Add new webservice > Click on Help Button > See Error 

### PrestaShop version(s) where the bug happened

1.7.7.8 & 1.7.8.0 & 1.7.8.1

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment]
All of the above is fixed, so I'm closing the issue  on PS 9.0.0 :)
