### ISSUE TITLE
BO - No text is displayed in help menu when editing the Address of Brands

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#26577]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

There is no text displayed in the `Help` page of Addresses Category in Brands & Suppliers ==>loading in progress 

see video :
https://www.awesomescreenshot.com/video/5975196?key=1fe1017bcc76c859b1f9d1e56d865631

### Expected behavior

The content of the help menu must be displayed

### Steps to reproduce

1. BO >Catalog>Brands & Suppliers
2. Edit an address
3. Click on Help button
4. See error > The content is not displayed (loading in progress)

### PrestaShop version(s) where the bug happened

1.7.7.8 & 1.7.8.0 & 1.7.8.1

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment]
The button is not displayed anymore on the form page.

![Image](https://github.com/user-attachments/assets/6865e587-7bb7-40e6-a640-96f74b9ac3e8)
