### ISSUE TITLE
ERREUR HTTP 500 SUR PrestaShop 1.7.8.0 

### ISSUE THREAD

**Issue by gerra14** [PrestaShop/PrestaShop#26580]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

bonjour
j'ai un problème  sur mon site lors de l'inscription du nouveau client après avoir changé la version PrestaShop en 1.7.8.0 mon PHP est 7.4 ca met : cette  page ne fonctionne pas .Impossible de traiter cette information à l' heure actuelle .ERREUR HTTP 500

### Steps to reproduce

Mon compte 
Inscription

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @gerra14 

Please send your request in English. English is the norm on GitHub.

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must fill all the blocks in the template**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thank you

**Comment by gerra14** [comment]
Hello
I have a problem on my site when registering the new customer after changing the PrestaShop version to 1.7.8.0 my PHP is 7.4 it says: this page does not work. Cannot process this information at the moment. HTTP 500 ERROR

**Comment by gerra14** [comment]
Hello
I have a problem on my site when registering the new customer after changing the PrestaShop version to 1.7.8.0 my PHP is 7.4 it says: this page does not work. Cannot process this information at the moment. HTTP 500 ERROR

**Comment by gerra14** [comment]
thank you the problem is resolved
