### ISSUE TITLE
Notice: Undefined index: showPackProductsPrice

### ISSUE THREAD

**Issue by JMauclair** [PrestaShop/PrestaShop#26584]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In debug mode, when you create a pack, you add product(s) to this pack, you go to the pack product page, you have this message 
![image](https://user-images.githubusercontent.com/46693396/141361996-830aa972-af2d-4e3d-9b3b-af0a5c7362a2.png)

### Expected behavior

Display the product page as usual

### Steps to reproduce

1. Enable debug mode
2. Create a product
3. Choose pack product
4. Add products to this pack
5. Set required informations
6. Save
7. Go to the product pack page

### PrestaShop version(s) where the bug happened

1.7.7.2

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment]
Hello @OpiumCity 

I didn't manage to reproduce the issue with PS1772 and PS1780, see the attached screen record below:

https://watch.screencastify.com/v/cGPBu7k4Qi8PxUaGdv5R

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @OpiumCity 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by JMauclair** [comment]
I've just made a quick fix in the tpl
