### ISSUE TITLE
[1.7.8.1] Issue with linking Prestashop account using subdomain www. 

### ISSUE THREAD

**Issue by arafatx** [PrestaShop/PrestaShop#26595]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I have searched this issue and I think this has not been discussed. When I try to associate my site with Prestashop Metric I got errors (please see below)

 

### Expected behavior

Able to link my Prestashop domain with no issue

### Steps to reproduce

1) Go to dashboard open PrestaShop Metrics

2) Now I clicked the Associate button

3) I log in successfully using credentials that I had before

4) The website field www.domain.com is inserted (my shop domain). Now I clicked on accept and associate but then it said:

 
```
Error!

Your shop could not be associated with your PrestaShop account
```

5) Clicking problem details it said:

`["shops.0.Your shop is already linked and verified"]`

6) Well now I go ahead thinking maybe I should disassociate the website first. So I clicked on View my associated shops and click Dissociate and it asked the following message with two buttons

 

```
Are you sure you want to remove this shop from your account?

If you have ongoing subscriptions, it will be impossible to cancel them.

[Cancel]                              [Dissociate]
```

 
7) Of course I clicked on **Dissociate** and now the final issue is I got the following error:
 
```
Error message

We were unable to contact your shop, please contact support.

"Error while getting domain"

```

Screenshot:

![error_screenshot](https://user-images.githubusercontent.com/4420157/141672129-01a214ea-d33f-4137-8f41-04fe9d967460.png)

I think this error came from the Prestashop server. 

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

This might be related to ps_accounts module

Additional information:

The shop is not in maintenance mode when I reproduce this issue.

Funny thing is that it knows my login account is associated with the site (it has the data) but still doesn't want to link the site.

EDIT: I think this issue is related to logical error and it is a generic bug in how you handle the linking from the server. So, I just notice that this also happens with the other module like Facebook v1.14.0 when linking the site.

EDIT (Updated). The issue might be related to ps_accounts and it has a workaround here:  https://www.prestashop.com/forums/topic/1049431-unlink-prestashop-shop-from-account/

**Comment by hibatallahAouadni** [comment]
Hello @arafatx 

It seems that your issue is not a PrestaShop core bug.
If your module is Metrics Official, please contact support team on Addons.

We will close this issue.

Thanks!

**Comment by arafatx** [comment]
I knew it is not a PrestaShop core issue but this is related to the add ons developed by Prestashop **as stated in the first post.** The bug tracking template issue here even has an option to allow this to be reported (that is my first reason why I think it should be reported here). Right now I have found another medium to report this issue.  Thanks.

**Comment by arafatx** [comment]
I knew it is not a PrestaShop core issue but this is related to the add ons developed by Prestashop as stated in the first post. The bug tracking template issue here even has an option to allow this to be reported (that is my first reason why I think it should be reported here or what is the purpose of the field "If your bug is related to a module, specify its name and its version
"). Right now I have found another medium to report this issue. Thanks.

**Comment by arafatx** [comment]
@hibatallahAouadni  I̶ ̶k̶n̶e̶w̶ ̶i̶t̶ ̶i̶s̶ ̶n̶o̶t̶ ̶a̶ ̶P̶r̶e̶s̶t̶a̶S̶h̶o̶p̶ ̶c̶o̶r̶e̶ ̶i̶s̶s̶u̶e̶ ̶b̶u̶t̶ ̶t̶h̶i̶s̶ ̶i̶s̶ ̶r̶e̶l̶a̶t̶e̶d̶ ̶t̶o̶ ̶t̶h̶e̶ ̶a̶d̶d̶ ̶o̶n̶s̶ ̶d̶e̶v̶e̶l̶o̶p̶e̶d̶ ̶b̶y̶ ̶P̶r̶e̶s̶t̶a̶s̶h̶o̶p̶ ̶a̶s̶ ̶s̶t̶a̶t̶e̶d̶ ̶i̶n̶ ̶t̶h̶e̶ ̶f̶i̶r̶s̶t̶ ̶p̶o̶s̶t̶.̶ In addition to that, the bug tracking template issue here even has an option to allow this to be reported with the following field:

"If your bug is related to a module, specify its name and its version"  (For what purpose?)

Hence, that was my first reason why I think it should be reported here

Right now I have found another medium to report this issue. Thanks.

Updated:

Found the reason. Please refer to this latest comment: 

https://github.com/PrestaShop/PrestaShop/issues/26595#issuecomment-974049609

**Comment by hibatallahAouadni** [comment]
Hello @arafatx 

> "If your bug is related to a module, specify its name and its version" (For what purpose?)

This sentence concern only the native modules (like FacetedSearch, ps_banner, ...)

Thanks for understanding :pray:

**Comment by arafatx** [comment]
> Hello @arafatx
> 
> > "If your bug is related to a module, specify its name and its version" (For what purpose?)
> 
> This sentence concern only the native modules (like FacetedSearch, ps_banner, ...)
> 
> Thanks for understanding 🙏

Thanks @hibatallahAouadni

**Comment by arafatx** [comment]
Hai @hibatallahAouadni , I want to make a clarification here that the original of this issue is not related to Prestashop Metrics, because this also happens with the other addons Prestashop Facebook. Even though this issue does seems like it is related to the addons but I believe it is more related to the native module of **ps_accounts**.  This bug also mentioned in here and it has workaround by user @Jay Jay https://www.prestashop.com/forums/topic/1049431-unlink-prestashop-shop-from-account/

The main issue here is that PrestaShop could not link your account if your domain has a subdomain. For example:

```
www.domain.com (does not work)
domain.com (works)
```
It seems like this bug is preventing the usage of www subdomain which is required for hosting multiple sites.

I'm changing the title to exclude the addon issue as I believe this is not related to addons. So you may consider reopen this issue.

By the way, if you asked, I actually have sent a ticket for this and was given the FTP access to check the issue and it seems like I'm not getting a response for more than 3 days now. 

Please drop the invalid label and also this happens with the latest PrestaShop 1.7.8.1

**Comment by LaqueP** [comment]
Hi @arafatx I changed the domain on ps_configuration but the problem continues, how did you solved it? I have 2 sotres with subdomain, but i need it i can't delete them.
