### ISSUE TITLE
PrestaShop must be compatible with PHP 8.1

### ISSUE THREAD

**Issue by le-melon** [PrestaShop/PrestaShop#26602]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

PHP 8.1 will be out soon and PrestaShop should be compatible.

Before PHP 8.1 is is released, the beta builds and release candidates of PHP can be used for testing => https://www.php.net/archive/2021.php#2021-11-11-1

### Describe the solution you'd like

Make PrestaShop compatible with PHP 8.1

**Comment by florine2623** [comment]
Hello @le-melon ,

Please read this topic : https://github.com/PrestaShop/PrestaShop/issues/18547
More info on PHP 8.1 here : https://github.com/PrestaShop/PrestaShop/issues/18547#issuecomment-953681691

I'll close your issue as it is already discussed on https://github.com/PrestaShop/PrestaShop/issues/18547.
Thanks!
