### ISSUE TITLE
[BO] - Email themes - the dropdown-menu items are not aligned

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#26604]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The dropdown-menu items are aligned to the right:

![image](https://user-images.githubusercontent.com/23308427/141771604-6159d740-06b2-4f28-a043-943577ad6111.png)

### Expected behavior

As 1.7.7.8

![image](https://user-images.githubusercontent.com/23308427/141771540-d48f1529-8d01-4eda-9791-cd33d86fde33.png)

### Steps to reproduce

1. **BO**>**IMPROVE**>**Design**>**Email Theme**
2. Scroll down to **Email themes**
3. Click on **classic** or **modern** loop
4. Click on **Actions** (the three dots) button next to **HTTP**
5. See error > the dropdown-menu items are misaligned

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.2

**Comment by Progi1984** [comment]
Fixed by @NeOMakinG in #26714 & tested by @HanaRebaiQA
