### ISSUE TITLE
Combination supplier selection error

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#26610]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

when selecting a supplier - table with supplier list should appear, but instead it throws console error.
![Screenshot from 2021-11-15 15-17-29](https://user-images.githubusercontent.com/31609858/141790900-6f85193a-07dc-4774-9f1e-e246e37fc560.png)
### Expected behavior

table with supplier list should appear which allows modifying couple supplier fields before saving

### Steps to reproduce

1. Turn on experimental product page feature
2. Make sure you have suppliers created and enabled in sell -> catalog > brands & suppliers
3. Go to any experimental combinational product page and open combination edition form (by clicking the pencil icon on the left of combination list row).
4. Try to select any supplier while developer console is open. See the error.

------------------------------------------------------------

Enable Experimental Features

1. Go to Products list
2. Edit a product with combination using Experimental Features option that has already a supplier selected (demo product)
3. Go to Combinations tab > Edit one combination
4. Select a supplier > Save > Error : NOK
5. Refresh the page > Try to re-edit the same combination
6. Default supplier column disappeared : NOK

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment]
Hello @zuk3975 ,

Thanks for your report.

I've reproduced a similar bug but not exactly the same on PS develop branch.

Here are my steps to reproduce :
- Enable Experimental Features
- Go to Products list
- Edit a product with combination using Experimental Features option
- Go to Combinations tab > Edit one combination
- Select a supplier > Save > Error : **NOK**
- Refresh the page > Try to re-edit the same combination
- Default supplier column disappeared : **NOK**

Here's my screen record : https://watch.screencastify.com/v/tgkKtlsgBexpd5NRO8pX

Could you check and let me know if that is the issue ?
Thanks!

**Comment by zuk3975** [comment]
hi @florine2623,
Did you rebuild the assets?

**Comment by florine2623** [comment]
Hello @zuk3975 ,

I rebuilt the assets and couldn't reproduce my issue ! The Default Supplier column is now always displayed : **OK**

With these steps, I do have an error :
- Edit a product with combination using Experimental Features option
- Go to Combinations tab > Edit one combination
- Select a "Supplier associated with this product" > Save
- Updated Successful is displayed when the Supplier is not saved : **NOK**
- Error in console is displayed (different from yours) : **NOK**

<img width="505" alt="Screenshot 2021-11-18 at 14 41 22" src="https://user-images.githubusercontent.com/16019289/142426197-4f93e9a1-de29-4a63-8b65-2b00cf0477db.png">

Here's my screen record : https://watch.screencastify.com/v/JTz9ZmSLOUKgsLlw2VTS
Can you confirm you are experiencing the same issue ?

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @zuk3975,

I manage to reproduce the issue with develop branch
1. when we have a product with combination without any supplier selected 
=> NOK
![image](https://user-images.githubusercontent.com/16067358/142429294-a85c184b-ea47-4255-8749-b039b44da818.png)
2. If I edit a combination that has already a supplier selected => I have the same issue reproduced by @florine2623 
![image](https://user-images.githubusercontent.com/16067358/142430732-7f007723-f96e-4ba0-be77-2a5a3fe37121.png)

It is ok with PS1781.

Thank you!
