### ISSUE TITLE
Reopen of #26391: Search PHP dropping results and not searching for all terms.

### ISSUE THREAD

**Issue by Wrenbjor** [PrestaShop/PrestaShop#26614]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When searching for more than one item in search EX: abc, 123, JRT

Search.php logic in find() uses array_intersect instead of array merge which causes 123, JRT in the case above to be dropped and only abc is searched for.

The search logic will only search for the first thing typed into the box. any other items typed in will get dropped. It's a logic flaw.

If I search for "The blue fox" the logic will break this into a 3 item array.

a foreach loop will start on line 291.

foreach ($expressions as $expression) {

The code will use the fuzzy search and the DB to look for "The" as the first item in the array and put the results into $productIds.

then at line 328

$productIds = array_column($result, 'id_product'); if ($eligibleProducts2 === null) { $eligibleProducts2 = $productIds; } else { $eligibleProducts2 = array_intersect($eligibleProducts2, $productIds); }

will assign "The" as the fist item in the array into $elegibleProducs2 because it is null on the first iteration of the loop so only the first part of the if condition is reached. On the 2nd pass of the foreach for "blue" the DB and fuzzy search will now find a list of things that match "blue" and put that into $productIds.

now on line 328 the if fails because $elegibleProducts2 contains "the" at index 0. so the Else is triggered.

Array_intersect merges 2 arrays. It takes the first array and then adds anything that matches or 'Intersects' the second array and merges them together. so...

$elegibleProducts2[0] is "The"
and
$productIds[0] is "blue"

"The" <> "blue" so $elegibleProducts2 only keeps item [0], $productIds is dropped into Null and only 1 item is in $elegibleProducts2. This will happen for every item in a loop and will happen for all searches that dont use the same word over and over.

"The the the" would work for this logic.

"Red Pants", "Red Hats", "Red, Blue, and Green Cars"

for each of these searches the code will only look for "Red" and Pants, Hats, Blue, 'and', Green, and Cars are all dropped and never returned.

### Expected behavior

Expected SQL query should have "sw.word LIKE 'abc%' or sw.word LIKE '123%' or sw.word LIKE 'JRT%'"

### Steps to reproduce

Use the SearchBar default search controller and search for 2 or more items that should return results.

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.4

**Comment by Wrenbjor** [comment]
please also see comments on #26391

**Comment by florine2623** [comment]
Hello @Wrenbjor ,

I've searched for one product : OK

<img width="415" alt="Screenshot 2021-11-15 at 17 50 21" src="https://user-images.githubusercontent.com/16019289/141821766-9a93c307-3595-4b4c-aeef-736ea02dfd03.png">
<img width="1171" alt="Screenshot 2021-11-15 at 17 50 29" src="https://user-images.githubusercontent.com/16019289/141821785-e3129874-61a3-420d-ac70-b116c7dca9c4.png">

I've searched for one product with commas in the title : OK
<img width="423" alt="Screenshot 2021-11-15 at 17 50 42" src="https://user-images.githubusercontent.com/16019289/141821840-45d6405e-743c-43a1-b924-c8758c304dbd.png">
<img width="1140" alt="Screenshot 2021-11-15 at 17 50 48" src="https://user-images.githubusercontent.com/16019289/141821852-810abb52-2866-4e60-b951-95acff971262.png">

But again I don't understand how you want to search for multiple products at once. You should search for a product and multiple results that fit best will show up.

Maybe that's an improvement that you are asking for ? It is what I asked [here](https://github.com/PrestaShop/PrestaShop/issues/26391#issuecomment-951948752). What do you think ?

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Wrenbjor 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
