### ISSUE TITLE
BO - The lines of combinations are disordered when duplicate the product 

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#26611]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When adding a new product with combinations (3 combinations of same Size and different color) and then duplicate the product, the combinations change their orders.
The consequence also is that when adding a specific price, the lines of combinations are disordered in the list.

See screen-record : 
https://www.awesomescreenshot.com/video/6017658?key=6d5a107e662f65d072964ddb9bd68596

### Expected behavior

The line of combinations do not change their order.

### Steps to reproduce

1. BO> Product> Create New Product
2. Choose Product with combinations
3. Select `Size S` and `Color Beige, White and Off White`
4. Generate the several attributes > Save
5. Duplicate the product 
6. Enter to the Combinations of the duplicated product
5. See error > The first line of combination `Size - S, Color - Beige` became the last one

### PrestaShop version(s) where the bug happened

1.7.7.8 & 1.7.8.0 & 1.7.8.1

### PHP version(s) where the bug happened

7.3

**Comment by MatShir** [comment]
It seems to fixed on the new product page on PS 8.1 :)

**Comment by florine2623** [comment]
It is indeed fixed in 8.1.

https://github.com/PrestaShop/PrestaShop/assets/16019289/9e8a697f-19b0-4cf9-b706-b10aae89b856

I'm closing this issue ^^
