### ISSUE TITLE
Find a way to index faceted search filtered categories in search engines

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#26627]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

There is a huge potential in bringing more people into Prestashop stores if we could index category pages with enabled filters.

- We have a category cars.
- We have filters for `colors` - `red, yellow, blue, green`. We have filters for `size` - `small, medium, big`.
- We index only for "cars" category and nothing else. :(

### Describe the solution you'd like

If we could create something like landing pages and make google index "red small cars", "red big cars", "green big cars" etc. that would bring user to the category page with filtered selection, it would be awesome and we could occupy search engines positions for **A LOT MORE** search terms and bring a lot more traffic to our website, to precise product selections.

### Alternatives you've considered

I am currently using landing page module that shows manual product selection, but it's not optimal. I want the user to land in the category and allow him to start choosing another filters right away.

### Additional context

Adding pages to sitemap is "easy", but we would need to show different h1 and page title on load, so we get indexed properly and google won't consider it as duplicated content.

ping @tswfi @kpodemski @jf-viguier WDYT, is it possible?

**Comment by jf-viguier** [comment]
It's a killer feature, but it's an advanced SEO concern too: badly used, it can generate a lot's of duplicate content. I'm not sure if it should be in the core.

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon.

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by jf-viguier** [comment]
"hiring a specialist" is not relevant with @Hlavtox he is a specialist ;-)

**Comment by hibatallahAouadni** [comment]
@jf-viguier thanks to remind me :wink: it's just an auto reply :sweat_smile:

**Comment by jf-viguier** [comment]
The Product Team should consider hiring a specialist to write the auto reply (according to the author level : contributor, maintainer, Game of Thrones king) (joke) 🤣
