### ISSUE TITLE
Error al ordenar productos por precio

### ISSUE THREAD

**Issue by cepardov** [PrestaShop/PrestaShop#26621]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Al ir a la pagina de productos y ordenar por precio sea por ascendente descendente, se provoca un error 500
[2-todos-los-productos.pdf](https://github.com/PrestaShop/PrestaShop/files/7541821/2-todos-los-productos.pdf)

### Expected behavior

Se muestran los producto ordenados por precio asc

### Steps to reproduce

1. vaya a todos los productos
2. ordene los producto por precio ascendente

### PrestaShop version(s) where the bug happened

1.7.80, 1.7.8.1

### PHP version(s) where the bug happened

7.4.25

### If your bug is related to a module, specify its name and its version

ps_facetedsearch

**Comment by Hlavtox** [comment]
You are missing id_country in the query -  `AND psi.id_country = ) LEFT`, because `$this->getContext()->country->id` is empty.
Properly set your country, check if a default country is set, regenerate faceted search index, clear cookies and try again.

**Comment by hibatallahAouadni** [comment]
Hello @cepardov 

Please send your request in English. English is the norm on GitHub.

Thank you
