### ISSUE TITLE
BO - &times; symbol should hide when menu is not expanded on mobile

### ISSUE THREAD

**Issue by nikitasol** [PrestaShop/PrestaShop#26626]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Mobile menu for BO contains &times; symbol which is set to fixed and as such is still visible even when the menu is not in expanded state. Added background colour to header for better preview:

<img width="858" alt="Screenshot 2021-11-16 at 13 34 06" src="https://user-images.githubusercontent.com/25999449/141990033-f5c6a05b-87c3-4d9f-a3cb-0c373698e310.png">

### Expected behavior

Symbol should be set to display:none when it is not in expanded state.

### Steps to reproduce

1. Open BO
2. Shrink window to mobile size
3. Observe the slight overflow of the &times; symbol over the header

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Hello @nikitasol 

Thanks for reproting the issue!
I reproduce the issue with only PS1780 and PS1781, see the attached screen record below:

https://watch.screencastify.com/v/j2pTUgPppNXvoUolZKrR

But it seems the issue has been fixed on develop, check the screen record below:

https://watch.screencastify.com/v/PZLDF1CxTdgHSq5WZVlz

Thanks for your PR :rocket: unfortunately it seems that we need to close the issue and the PR :disappointed_relieved: 

Thanks for your understanding :pray:
