### ISSUE TITLE
Can't transplant modules (1.7.8.1)

### ISSUE THREAD

**Issue by Alaiin974** [PrestaShop/PrestaShop#26639]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

I upgraded two websites to 1.7.8.1 (one with PHP 7.3 & one PHP 7.4).

Both can't transplant modules.

With PHP 7.4, debug mode give this when i go to Design > Positions :
![image](https://user-images.githubusercontent.com/46953815/142077573-5f405f4a-71ca-4693-a900-b401b014bf2b.png)

Thanks for help :

### Steps to reproduce

1. Go to Design > Positions
2. Transplant a module
3. Select a module & Hook
4. Check if it transplants.

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.3 & 7.4

**Comment by Alaiin974** [comment]
Delete this issue please, no problem finally, i did a custom conf mistake...

**Comment by matks** [comment]
github does not allow us to delete issues but it's OK 👍  dont worry

happy to know you solved the problem 🎉
