### ISSUE TITLE
[Mobile] BO - the save and preview buttons in Design>Pages are bad displayed

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#26633]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you try to edit page, you can see that card-footer can not contain all buttons:
**PS1.7.8.0 and develop** :x: 

![image](https://user-images.githubusercontent.com/23308427/142014005-270089a2-faf6-4138-a5d9-b78e954906ee.png)

**PS1.7.7.8** :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/23308427/142017265-0262e83d-c635-4566-9381-1e7ff75b12ac.png)

### Expected behavior

Create dropdown-menu (like in Edit a Product page):

![image](https://user-images.githubusercontent.com/23308427/142015451-ca3de40b-d50e-4124-8eeb-68659f483d67.png)

### Steps to reproduce

1. **BO**>**IMPROVE**>**Design**>**Pages**
2. Click on **Edit** button of any page
3. Scroll down to the **card-footer**
4. See error > the `Save` and `Save and preview` buttons are bad displayed

### PrestaShop version(s) where the bug happened

1.7.8.0 & develop

### PHP version(s) where the bug happened

7.2

**Comment by Hlavtox** [comment]
@hibatallahAouadni We should check all cards where there is more than `Cancel` and `Save` buttons and apply the behavior.

@NeOMakinG Mission fix footers?

**Comment by marionf** [comment]
@prestascott Could you take a look at the suggestion of Hiba ?

**Comment by Hlavtox** [comment]
@hibatallahAouadni Let's fix it together with this. Just went through all BO and there is no other place where more buttons are used.

https://github.com/PrestaShop/PrestaShop/issues/25198

**Comment by Hlavtox** [comment]
@hibatallahAouadni @marionf Fixed!

**Comment by hibatallahAouadni** [comment]
Thanks for your PR :rocket:

**Comment by prestascott** [comment]
Perfect, thank you @hibatallahAouadni !!

**Comment by Progi1984** [comment]
Fixed by @Hlavtox in #27225 & tested by @hibatallahAouadni.
