### ISSUE TITLE
[FO] Product flags regression in 1.7.8.x

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/PrestaShop#26640]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Changing label `New` to `New product` was a mistake - it covers too much.

![obraz](https://user-images.githubusercontent.com/5007456/142080918-21d0bbdb-51ea-4781-9e1a-f5b6e44a5651.png)

### Expected behavior

It's obvious we're looking at a product. Isn't it?

### Steps to reproduce

1. Open homepage or category with new products available

### PrestaShop version(s) where the bug happened

1.7.8.0, 1.7.8.1

**Comment by hibatallahAouadni** [comment]
Hello @SharakPL 

Yep that's true! it use to be just `NEW` with PS1.7.7.8:

![image](https://user-images.githubusercontent.com/23308427/142184529-e26754dd-b25b-4cfa-8443-0c50cac6b638.png)

But let's check with Product Team, if it's a regression on 1.7.8.0 or just the expected behavior (as new feature) :wink: 
Ping @PrestaShop/product-team is it a regression or a new feature?

Thanks!

**Comment by hibatallahAouadni** [comment]
PS: I think the behavior changed while fixing this issue #21105 
As you can see in this [comment](https://github.com/PrestaShop/PrestaShop/issues/21105#issuecomment-697406263) the flag contain only the word `New`. While in this PR [description](https://github.com/PrestaShop/PrestaShop/pull/21751#issue-736140230) you can see that the flag contain two words `New Product`.

**Comment by Julievrz** [comment]
Hi, 

I don't think it was intentional. I agree that "New" is enough and perfectly clear. Furthermore, "New product" could be longer in other languages, and cover the product image even more.

**We can use the string 'New' in Shop.Theme.Catalog**

**Comment by Progi1984** [comment]
Fixed in #26798 by @WebHelpersPau & tested by @HanaRebaiQA
