### ISSUE TITLE
Multistore Header Not working - 1.7.8.x

### ISSUE THREAD

**Issue by davidcylke** [PrestaShop/PrestaShop#26657]
please remove

**Comment by khouloudbelguith** [comment]
Hi @davidcylke,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have
questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!
