### ISSUE TITLE
FO - An exception is displayed in the order-detail page after enabling merchandise return

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#26656]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the FO > order-history > order-detail page, an exception is displayed after enabling merchandise return.

This issue is detected by [Nightly](https://nightly.prestashop.com/report/2989)

There is no exception if we have an order with a vector product

### Expected behavior

Should be well displayed without any exception

### Steps to reproduce

1. Go to BO > Customer Service > Merchandise Returns page and enable returns
2. Go to BO > Orders > Orders page and change any order status to "Shipped"
3. Go to FO > order-history > Open the previous order-detail page
![image](https://user-images.githubusercontent.com/16067358/142248644-6b62575b-a742-4ed2-9d94-e56ff8793986.png)

There is no exception if we have an order with a vector product

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment]
Caused by #25204

**Comment by ghost** [comment]
I am working on it's after a rebase i will fix asap
