### ISSUE TITLE
PS 1.7.8 core.js.map Google map missing and pickup store map is not working / loading

### ISSUE THREAD

**Issue by TheEnglishGartner** [PrestaShop/PrestaShop#26661]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi all,

I have recently upgraded my prestashop to PS 1.7.8 but in the checkout section the Google map is not loading for my customers to select a pickup store. I can see that I have an error which have previously been adressed in the forum:

core.js.map missing - although Im not sure this is the cause. 

What I have done:

Troubleshooting with google - Google verified that the API is working
Troubleshooting with Shipmondo (distribution modul provider) - They say it is working on a clean install
Knowband Super checkout confirm to be working from their end
What I miss - I have a ThemeFortress Warehouse theme, which is also updated to newest version 4.5.0 - But I have not adressed it to them yet. 

Hence is there anyone who have seen this or now where I can download the above file for the PS 1.7.8 version?

My webshop url https://dem-engelske-gartner-shop.dk 

P.S. I know I have a double entry of the FB pixel, Im still fo figure this out. 

Hosted on Cloudways
DNS through Cloudflare
Mariadb 10.4

Thank you all in advance 

best,

DEGS

### Expected behavior

To secure that customers can choose a pickup store based on the map 

### Steps to reproduce

Put something in the basket

Go to the checkout 

NO map is loading

### PrestaShop version(s) where the bug happened

1.7.8

### PHP version(s) where the bug happened

7.4

**Comment by Hlavtox** [comment]
core.js.map is something completely different than google map. This is definitely not the cause.

There is no google map pickup by default, so this will be definitely closed.

However, I see that nothing is output in the checkout at all, I think there is some problem on PHP side. You need to investigate with your module's author.

**Comment by TheEnglishGartner** [comment]
Hi Hlavtox,

Thank you for the swift reply. Thank you for clariffying the above. Im using the Google API with my distribution / freight provider Shipmondo - Sorry if this was not clear. I think I will need to have a yet another round with either Shipmondo or Supercheckout Knowband. Could it be, this is just a question, due to some bugs in the warehouse theme?

Best,

DEGS

**Comment by khouloudbelguith** [comment]
Hi @TheEnglishGartner,

I did not manage to reproduce the issue with PS1781 fresh install and with PS1781 after an upgrade from PS1778.
I attached a screen record
[video5.zip](https://github.com/PrestaShop/PrestaShop/files/7561947/video5.zip)

Thanks to check and feedback.

**Comment by TheEnglishGartner** [comment]
Dear khouloudbelguith,
Thank you for the great video documentation. Maybe I should give it a go to upgrade the the 1.7.8.1 version and see the outcome of this.

Best,

DEGS

**Comment by khouloudbelguith** [comment]
@TheEnglishGartner,

As it's not a module provided by Prestashop, we can't do anything with this.
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.
Thanks!
