### ISSUE TITLE
You've cleaned prestashop 1.7.8.x and the version after upgrading from 1.7.7.7 to a different look

### ISSUE THREAD

**Issue by gs2k84** [PrestaShop/PrestaShop#26668]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I noticed that a clean prestashop 1.7.8.0 install looks like this:

![1 7 8](https://user-images.githubusercontent.com/93977076/142409596-92a35166-537c-4131-aacb-bdcf938c9131.png)

and version 1.7.8.1 after upgrading from 1.7.7.7 looks like this:

![1 7 8 1 update](https://user-images.githubusercontent.com/93977076/142409829-2e055f98-19fe-48a6-b9c6-1021dd4c7113.png)

It has other on / off icons and an extra plus sign in the top left corner.

### Steps to reproduce

Clean installation of 1.7.8.x and upgrade to this version.

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.3, 7.4

**Comment by khouloudbelguith** [comment]
Hi @gs2k84,


It is a browser cache issue.
Could you please try to configure your smarty by disabling the cache, set the option "Template compilation" to Force compilation and clear cache.

Also, try to open your shop in an incognito browser.
You need to force refresh the page, by pressing CTRL+F5 on Windows / Linux, Cmd+R on Mac OS while you are on this page.
Thanks to check and feedback.

**Comment by gs2k84** [comment]
Cool. It helped :)

Thank you for your help :)

**Comment by khouloudbelguith** [comment]
@gs2k84, great.
I will close the issue, feel free to open a new one when needed.

Thanks!
