### ISSUE TITLE
Logo should not be lazyloaded

### ISSUE THREAD

**Issue by iqit-commerce** [PrestaShop/PrestaShop#26666]
### Prerequisites
Related to #25853
- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Logo image file since it is above the fold should not be lazyloaded.
Expalanation why: https://web.dev/browser-level-image-lazy-loading/#avoid-lazy-loading-images-that-are-in-the-first-visible-viewport

### Steps to reproduce

1. check souruce code of frontoffice
2. you will see that there is   loading="lazy" added to logo img tag
3. logo image is above a fold so it should be not lazyloaded

### PrestaShop version(s) where the bug happened

1.7.8.1

**Comment by khouloudbelguith** [comment]
Hi @iqit-commerce,

Thanks for your report.
I manage to reproduce the issue with PS1780, PS1781 and develop branch.
It is a regression.
![image](https://user-images.githubusercontent.com/16067358/142411956-26678a5d-7f27-40fb-9e81-32e58b8680bd.png)
It is ok with PS1778 and PS1769 
![image](https://user-images.githubusercontent.com/16067358/142411994-16e58155-6243-46d7-96a5-80802ec4035c.png)

Related to https://github.com/PrestaShop/PrestaShop/issues/25853

Thanks for the PR :slightly_smiling_face:

**Comment by Progi1984** [comment]
Fixed in #26658 by @iqit-commerce

**Comment by matks** [comment]
Dear @PrestaShop/qa-team according to @leemyongpakvn this issue was fixed in PrestaShop 1.7.8.1 but has been introduced again in 1.7.8.5 (regression)

Could you check?

**Comment by AureRita** [comment]
Hi @matks, 

I check it and currently there is no lazy load on logo on 1.7.8.5 as you can see : 
![image](https://user-images.githubusercontent.com/100699445/168560429-74b2b4db-d0bd-4fcd-9279-a0feed341065.png)

I tested it also on a shop with the 1.7.8.6 version (update from 1.7.7.8) and there is no lazy load too 
![image](https://user-images.githubusercontent.com/100699445/168560777-d6c97c50-89c1-4367-945a-7d910dd2bbbb.png)

After checking the subject on the pr, I see that the product have the lazy load : 
![image](https://user-images.githubusercontent.com/100699445/168562523-f582d0d3-79a4-4ac5-8532-81dbac45e3be.png)

![image](https://user-images.githubusercontent.com/100699445/168562589-6aa368c6-2210-4123-940b-9cf03fb6d61d.png)
