### ISSUE TITLE
Error in the edit combination of "new experimental product page" editing a combination value 1.7.8.1

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#26675]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi
I've found a bug testing the new experimental product page
the error appear pushing on the pencil icon of a combination

![3](https://user-images.githubusercontent.com/653230/142595806-31d862b1-0afc-47f7-ada9-fb95b41cb435.png)

https://watch.screencastify.com/v/qMGVLv80AaDDhOt3PDHN

bye

### Steps to reproduce

active the new experimental product page

go to a product with combination

select the combination tab

push on the pencil icon

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.3

**Comment by khouloudbelguith** [comment]
Hi @maofree,

I did not manage to reproduce the issue with PS1781.
I attached a screen record
https://watch.screencastify.com/v/8U46zcKOi1e7VCv24BDQ

Thanks to check and feedback.

**Comment by Maofree** [comment]
ok but show this error to a developer to check that code to be sure that there are not errors

with the standard mode all is ok without errors, so I think that code can be improved. the demo data is basic so doesn't cover all possible examples

**Comment by khouloudbelguith** [comment]
@maofree, could you please provide me a screenshot of the Edit combination page product V1.
I tried with a new product > I edited a combination with all data set => ok 
I edit a combination just generated => ok

Have you any custom modules related to the combinations?

Thanks!

**Comment by Maofree** [comment]
in the first step there was an error on english language with too much text into the short description, fixed it I get this error

![6](https://user-images.githubusercontent.com/653230/142617070-1fd84654-b530-47cf-b92b-b2b55cf1353b.png)

but now the combination popup is without an error
I tried to add again some text in the short description from the DB, but now I can see the combination form

the new error is:

`An unexpected error occurred. [PrestaShop\PrestaShop\Core\Domain\Product\Exception\InvalidProductTypeException code 50]: Product #1 has combinations. Use PrestaShop\PrestaShop\Adapter\Product\Update\ProductSupplierUpdater::setCombinationSuppliers() to set product suppliers for specified combination`

**Comment by khouloudbelguith** [comment]
@maofree, could you please check this issue: https://github.com/PrestaShop/PrestaShop/issues/26610 but only reproduced with develop
Also this issue: https://github.com/PrestaShop/PrestaShop/issues/25905
and this ticket: https://github.com/PrestaShop/PrestaShop/issues/25589

Thanks!

**Comment by Maofree** [comment]
![2](https://user-images.githubusercontent.com/653230/142621304-d4b48a5a-cdb6-4688-8d0d-845f91870bce.png)

I reproduce the error of #26610  if I save from the popup of a combination
instead if I save from the main button I get the other error

it happens only with products with combinations

**Comment by khouloudbelguith** [comment]
@maofree,

>I reproduce the error of #26610 if I save from the popup of a combination

Did you use develop branch or PS1.7.8.1.
In my case, I reproduce the issue only with develop.

>instead if I save from the main button I get the other error

You need to close the Edit combination module to save, is it?

Thanks!

**Comment by Maofree** [comment]
I'm using the 1.7.8.1 stable

I've no problems to save the combination from the popup (the second error appears from the poup but I can save from it)

this error appears when I push on the main "save" button

`An unexpected error occurred. [PrestaShop\PrestaShop\Core\Domain\Product\Exception\InvalidProductTypeException code 50]: Product #1 has combinations. Use PrestaShop\PrestaShop\Adapter\Product\Update\ProductSupplierUpdater::setCombinationSuppliers() to set product suppliers for specified combination`

**Comment by khouloudbelguith** [comment]
@maofree,

It will help us if you can attach a screen record.
With PS1781, I have only those issues: #25905 & #25589


Thanks

**Comment by Maofree** [comment]
I tested again right now, at this time all was ok without any error
I've also cleaned the cache, now I cannot reproduce the previous errors

maybe i deleted all the html code that was in the long description. perhaps there are problems in the case of descriptions with very detailed html code

**Comment by khouloudbelguith** [comment]
@maofree, can we close this issue?

THanks!

**Comment by Maofree** [comment]
yes
