### ISSUE TITLE
Translations server is broken

### ISSUE THREAD

**Issue by zorrobiwan** [PrestaShop/PrestaShop#26674]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When opening translations tab, got 404 error on http://i18n.prestashop.com/translations/1.7.7.7/available_languages.json 

![image](https://user-images.githubusercontent.com/2226019/142584620-5eee7589-b31a-4e29-b4ac-6c3efe048715.png)

It seems that other URLs (found on the forum) give also a 404
http://i18n.prestashop.com/translations/1.7.3.3/en-US/en-US.zip

In brief, translations server seems to be broken (https://github.com/PrestaShop/TranslationFiles/)

### Expected behavior

Accessing to the translation feature without the 404 error :)

### Steps to reproduce

1. go to Translations

### PrestaShop version(s) where the bug happened

1.7.7.7

### PHP version(s) where the bug happened

7.3

**Comment by khouloudbelguith** [comment]
Hi @zorrobiwan,

Thank you for your report.
The problem is fixed
![image](https://user-images.githubusercontent.com/16067358/142588711-51d7d412-abf9-4b23-a75b-a9baa499c9ab.png)
http://i18n.prestashop.com/translations/1.7.8.1/available_languages.json is available now.

Thanks!

**Comment by zorrobiwan** [comment]
Thx for the quick fix
