### ISSUE TITLE
Payment error with currency without two decimal places 1.7.8.1

### ISSUE THREAD

**Issue by ocio87** [PrestaShop/PrestaShop#26671]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

It is identified that with the Colombian currency (Peso COP) it throws a payment error when there are no configured decimals or with a configured decimal.
When the two decimal places are configured in the COP currency, the order is created correctly with the Order status "Pending payment".
For the COP currency it is not necessary to have decimals. Is it possible to omit these decimals?

https://drive.google.com/file/d/17DRKRMeU3J3z1gHuOWOjODePW28Bxo8s/view

### Expected behavior

It must allow the correct generation of the order with decimals equal to zero in the mode configuration as is currently the case with version 1.7.7.x

### Steps to reproduce

1. Go to International - Location - Currency
2. Change Decimals to Zero

![image](https://user-images.githubusercontent.com/12537826/142475026-bfd935fe-13a3-4e07-be97-26c826f286dc.png)

3. From the front office place an order.
4. It generates an error in the payment.

---

1. Install 1781 / 1780
2. Install the module COD
3. add the currency DZD or Colombian currency ( units of thousands)
4. Change precision of the currency to 0
5. Create an order from FO with COD
6. In the BO > Order > the status of the order is payment error

I manage to reproduce the issue with PS1780 / PS1781 using COD only
It is ok with PS1778 and 1769 => it's a **regression** on **1.7.8.0**

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_wirepayment

**Comment by ocio87** [comment]
It happens with both the default Theme and the custom one.

**Comment by ocio87** [comment]
When it is left without decimals, in ordered orders it shows that there is no money to be paid, however the values are the same.

![image](https://user-images.githubusercontent.com/12537826/142498021-dae68abb-bdf1-4195-80d2-7e125013bf20.png)

**Comment by khouloudbelguith** [comment]
Hi @ocio87,
I did not manage to reproduce the issue with PS1781.
I used different payment methods.
I attached a screen record
https://watch.screencastify.com/v/f4W96N4yOsrwC9EcAeM3
![image](https://user-images.githubusercontent.com/16067358/142593244-ff2061ee-5cb8-4d51-acfa-ba36203313f6.png)

what is the exact payment method did you use?

Thanks!

**Comment by ocio87** [comment]
Please try with units of thousands and Colombian currency.

I ran unitless tests of thousands with cash payment and it worked fine.

The novelty is presented in units of thousands and without decimals.

**Comment by khouloudbelguith** [comment]
@ocio87, I tried with Colombian currency and it is ok :heavy_check_mark: 
https://watch.screencastify.com/v/uzttVqH6sppk0oRMfiPK

Thanks to check and feedback.

**Comment by ocio87** [comment]
Hello,

Thanks for your time. Two things.

I was wrong, it is not with cash but with bank transfer (Bank Wire).

And second, look at what you saw in the video payment error in the order status.

![image](https://user-images.githubusercontent.com/12537826/142626631-e1f9413a-f29e-4aa4-81a0-e70d973e002d.png)

**Comment by ocio87** [comment]
I did the test with the same product changing the price, one exceeding a thousand pesos and the other did not exceed a thousand pesos.

In the one that exceeds one thousand pesos, it shows a payment error and the one that does not exceed one thousand pesos is left with a successful order pending payment.

https://drive.google.com/file/d/1EU83A8ip7Dv4N-YlzuNG_F0OhC0p-CEr/view

All problems disappear when I put the two decimal places, I did tests with the same product exceeding a thousand pesos with two decimal places and the order is successful and the order status is correct.

https://drive.google.com/file/d/1-DbZ6uHBuMwGWcOu-HAAGoCQDY0xxr91/view

![image](https://user-images.githubusercontent.com/12537826/142637734-caafb890-c009-45ae-9083-d2aeea4d18ad.png)

I also see a difference in the way the units of a thousand are shown, it shows me with a dot and it appears to you with a comma and decimals it shows me with a comma and you with a dot. I do not know if it can affect. However I appreciate if you can test it by putting the price of the product in thousands and paying with BankWire.

I appreciate if you can do the test again as previously reported.

A product with a price greater than 1000 pesos, without decimals and with Bankwire as a means of payment.

Thanks,

**Comment by khouloudbelguith** [comment]
@ocio87, the only way to reproduce the issue:
1. Install 1781 / 1780
2. Install the module COD
3. add the currency DZD or Colombian currency ( units of thousands)
4. Change precision of the currency to 0
5. Create an order from FO with COD 
6. In the BO > Order > the status of the order is payment error

I manage to reproduce the issue with PS1780 / PS1781 using COD only

It is ok with PS1778 and 1769.

Can you please confirm the issue? I will update the first comment then.

>I also see a difference in the way the units of a thousand are shown, it shows me with a dot and it appears to you with a comma and decimals it shows me with a comma and you with a dot. I do not know if it can affect.

This is a configuration, go to BO > Internation > LOcalization > Currencies > Edit any currency, for each language, we have a format 
![image](https://user-images.githubusercontent.com/16067358/142647129-ba3a6fef-20de-4c8f-95e3-d00755ddeab8.png)

Thanks!

**Comment by ocio87** [comment]
I make some changes in the step by step

Install 1781 / 1780
Install the module ps_wirepayment
![image](https://user-images.githubusercontent.com/12537826/142649759-541b2c14-17f2-4d06-813a-1f31f55654a1.png)
add the currency DZD or Colombian currency (COP) ( units of thousands)
Change precision of the currency to 0
![image](https://user-images.githubusercontent.com/12537826/142650024-853fd2e4-e599-48e8-b470-25fc21076afc.png)
Create an order from FO with ps_wirepayment - The product must exceed 1001 pesos
In the BO > Order > the status of the order is payment error
![image](https://user-images.githubusercontent.com/12537826/142650300-2021b521-df86-453f-abb1-199c8c64897d.png)

**Comment by khouloudbelguith** [comment]
@ocio87, sorry but using the ban wire module=> I have no issue.
I attached a screen record
https://watch.screencastify.com/v/AuRxLQlLPekaCi2rQNGf
Did I miss something?

Thanks!

**Comment by ahmedbdrn** [comment]
@khouloudbelguith 

Hello, I'm currently facing the same issue but like you said only with COD.

Can I please have the solution for this problem?

PS: 1.7.8.1
PHP: 7.4

Thank you!

**Comment by ocio87** [comment]
Hello @khouloudbelguith 

 Apparently if it is a sectorized error, I would appreciate it if you can review it more thoroughly.

 The store is updated from 1.7.7.8 and I waited for this version because the same thing happened with 1.7.8.0.

 From my possibilities I will continue to review anyway.

**Comment by hibatallahAouadni** [comment]
Hello @ocio87 

I was able to reproduce the issue with PrestaShop version 1.7.8.0 and COD module. I’ll add this to the debug backlog so that it’s fixed. And it's a regression!

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by ocio87** [comment]
Hello,

Thank you @hibatallahAouadni  

In the meantime I will continue to test other ways to update and confirm if I find a solution or the module that causes the error.

**Comment by ahmedbdrn** [comment]
Hello @hibatallahAouadni 

Thank you for the update!

I've been trying to find a solution but haven't been able to, I guess I'll keep trying and will let you know if I figured it out.

**Comment by ocio87** [comment]
@hibatallahAouadni 

I have identified that the 1-Click Upgrade module does not do the process of updating modules from 1.7.7.8 to 1.7.8.1, it only updates core and database files, it does not show the remaining process of missing x modules to update .

How I configured the module before updating:

![image](https://user-images.githubusercontent.com/12537826/142909261-09e50194-c68f-49a8-baf1-5ec7c2cb8504.png)

![image](https://user-images.githubusercontent.com/12537826/142909266-4a553e36-6b55-4063-ba85-d79153ae6574.png)

![image](https://user-images.githubusercontent.com/12537826/142909274-4f32bf1b-a334-4bc9-966d-0df5ae86c909.png)

![image](https://user-images.githubusercontent.com/12537826/142909287-43489856-e8c1-44d7-a198-9b72f25b3bb4.png)

As it reports that it updated:

![image](https://user-images.githubusercontent.com/12537826/142909958-fe8bc113-513b-4696-b1a2-967d6baad778.png)

Normally after updating the database you should proceed with the module update.  The following image is from a clean update without products, without any changes from 1.7.7.8 to 1.7.8.1:

![image](https://user-images.githubusercontent.com/12537826/142910488-bce08b92-673a-466e-946a-f29eb1624d77.png)

**Comment by ocio87** [comment]
Hello,

Continuing with the Bug I have found the following.

Clean installation of prestashop 1.7.8.1 was done.
Product creation was done and was successful
User creation and it was successful.
Order creation and it was successful.
Import of customers, currency, shipping and products from store 1.7.7.8 to the new store, 1.7.8.1, was made, order was placed and it was successful.

**This next step is where it started to fail. I imported the orders from version 1.7.7.8 to the 1.7.8.1 installation and it is in this process that the following orders that are made from the front office began to fail.**

These orders are the sales history that has been in place since 2014 with version 1.5 and that has been updated between versions 1.5, 1.6, 1.6.1.24, 1.7.7.4, 1.7.7.8. In version 1.7.8.1 it is the only version that is presenting problems so that orders can be generated successfully.

As I see it, they made a change in version 1.7.8.x in the order logic that is affecting the registration of orders.

If I want to continue in the meantime with this new version, I can import everything except the order history so that it works correctly.

I reported that the store has about 55 thousand orders created.

**Comment by hibatallahAouadni** [comment]
@ocio87 Thanks for your feedback :clap: hope you can create a Pull Request to fix the issue :pray:

**Comment by ocio87** [comment]
Hi @Hlavtox 

I would appreciate if you have knowledge of this novelty that is presented in version 1.7.8.x.

In Colombia the currency is used without decimals and when the order is generated it always shows a status error with version 1.7.8.1. If I configure that the weight will have two tenths, the order is successful. This novelty was not presented to me with version 1.7.7.8.

I see that at the core level they have made changes, where before it said number they changed it to DecimalNumber, I think that's why but I have little knowledge of the prestashop core to manipulate it.

![image](https://user-images.githubusercontent.com/12537826/143468639-fd3afb1f-6473-4c95-a1e2-b9bd2e9d8ac7.png)

![image](https://user-images.githubusercontent.com/12537826/143468733-629072b0-77be-488b-bb57-1f5f1a5d6b16.png)

**Comment by ocio87** [comment]
Another person with a similar case, this time from Mexico.

https://www.prestashop.com/forums/topic/1057159-pago-exitoso-pedido-creado-pero-pedido-queda-en-estado-error-de-pago/#comment-3365538

![image](https://user-images.githubusercontent.com/12537826/143491062-a540a5d1-b5da-4943-9d23-42827496ce54.png)

**Comment by marionf** [comment]
@khouloudbelguith This issue is only with currency DZD and Colombian currency or also with other currencies?

**Comment by ahmedbdrn** [comment]
Hello @marionf ,

I currently have this issue with COD and Franc CFA currency, I temporarily switched to having 2 decimals as a workaround. (Thanks to @ocio87 )

@khouloudbelguith , could this issue be resolved in the next patch or module update?

Thank you.

**Comment by khouloudbelguith** [comment]
Hi @marionf,

This issue occurs with a currency that has units of thousands and precision = 0.
If we edit any currency except the default currency
![image](https://user-images.githubusercontent.com/16067358/143862114-6d65f15e-40b7-44f7-b94e-7cbc15037e64.png)

I will have the same issue
![image](https://user-images.githubusercontent.com/16067358/143862160-41ad9e17-a6be-4ccd-b2f4-11cc18a4ff06.png)

Thanks!

**Comment by vodd** [comment]
![image](https://user-images.githubusercontent.com/591515/143957310-1a3e27cc-4c57-4d2b-9a36-c2bc02bd78b2.png)
this value fixed my problem

thx @ocio87

**Comment by mpaolino** [comment]
Duplicate of #26553 . PR to fix it in #26824

**Comment by khouloudbelguith** [comment]
Hi,

I reproduced the issue following these steps

https://user-images.githubusercontent.com/16067358/151019787-9e4bad40-fade-484e-9833-814d61d380a9.mp4

Thanks!

**Comment by bogdan202** [comment]
Please pay attention to this condition
https://github.com/PrestaShop/PrestaShop/blob/1.7.8.3/classes/PaymentModule.php#L323
Compared strings are getting by using the different precisions.
Context::getContext()->getComputingPrecision()
_PS_PRICE_COMPUTE_PRECISION_

_PS_PRICE_COMPUTE_PRECISION_ is deprecated from the version 1.7.7
https://github.com/PrestaShop/PrestaShop/blob/1.7.8.3/config/config.inc.php#L151

In my opinion this is cause discussed problem

**Comment by atomiix** [comment]
Fixed by #26824
