### ISSUE TITLE
Invalid email address when loading modules page in debug mode presta 1.7.8

### ISSUE THREAD

**Issue by indusone** [PrestaShop/PrestaShop#26680]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Error: invalid e-mail address when opening modules page in debug mode, after upgrade 

### Expected behavior

open modules page

### Steps to reproduce

1. Open BO 1.7.7.3
2. Go to Logs page and change the minimum severity level to 2
3. Install this module: [logger.zip](https://github.com/PrestaShop/PrestaShop/files/7755961/logger.zip)
4. Complete 1 click upgrade to 1.7.8.2
5. Login
6. Enable debug
7. LOGOUT
8. Login => unable to login

https://watch.screencastify.com/v/0Sj2krEvYLqWB27WRS5J

### PrestaShop version(s) where the bug happened

1.7.8

### PHP version(s) where the bug happened

7.2.24-0ubuntu0.18.04.10

**Comment by khouloudbelguith** [comment]
Hi @indusone,

I did not manage to reproduce the issue with PS1781 after an upgrade from PS1778 using the 1-click upgrade v4.13.0.
I attached a screen record
https://watch.screencastify.com/v/u3wks2Dz6sP3EzBP975e
Thanks to check and feedback.

**Comment by indusone** [comment]
Hi,
I can give my BO credentials if you wish to test it. Our setups are obviously different.  Another thread exists on this same issue.

**Comment by florine2623** [comment]
Hello @indusone ,

Regarding your system requirements, can you check if it matches with this : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Please check and feeback!
Thanks!

**Comment by indusone** [comment]
[image: image.png]
*MySQL version:* 5.7.36-0ubuntu0.18.04.1


Here is my server information.

**Comment by florine2623** [comment]
Could you answer directly via GitHub ? I don't see the content of your email.

**Comment by rsoulard-prolaser** [comment]
Hi @khouloudbelguith,
I have the same problem (upgrade PrestaShop from 1.7.7.x).

The PS_LOGS_EMAIL_RECEIVERS variable does not exist in the ps_configuration table before version 1.7.8.
The function sendByMail of PrestaShopLogger class send a mail with an empty email address.

**Comment by rsoulard-prolaser** [comment]
Hi @indusone,

Open Logs page and add an email.

![logs](https://user-images.githubusercontent.com/78790947/143213502-76d9475c-abf0-468c-906e-c033879bca83.png)

**Comment by rsoulard-prolaser** [comment]
Hi @hibatallahAouadni,

I tried the update again and I no longer have the problem.

The first time I had a rights problem on the vendor folder of ps_accounts I don't know why.
A critical error has been added to PrestaShopLogger which triggers the sending of an email and we can see the error because PS_LOGS_EMAIL_RECEIVERS is not defined.

**Comment by hibatallahAouadni** [comment]
Hello @rsoulard-prolaser 

Thanks for your feedback :pray: 
Glad to hear you have no more issues with the upgrade :tada: 

Ping @indusone could you please check your access rights on the `vendor` folder :pray: 
Please check and feedback.

Thanks!

**Comment by rsoulard-prolaser** [comment]
If a critical error occurs for any reason, I think the error occurs.
It might be better to declare the PS_LOGS_EMAIL_RECEIVERS variable in the sql script as in my PR.
This variable is declared only in the installation of version 1.7.8.
What do you think?

**Comment by indusone** [comment]
Permissions are 775 for files inside vendor folder.
Also tried changing email address to another  , still same error.

**Comment by indusone** [comment]
Ok , tried resetting the module, it says hook id does not exist in database.

**Comment by hibatallahAouadni** [comment]
which hook?

**Comment by rsoulard-prolaser** [comment]
Hello @hibatallahAouadni,

The bug can be present in certain cases (if we use the PrestaShop addLog function and send emails).
Create a module with this hook (for example):
`
public function hookActionAdminLoginControllerLoginBefore($params) {
    PrestaShopLogger::addLog('actionAdminLoginControllerLoginBefore', 2);
}
`

**Steps to reproduce**
1. Open BO 1.7.7.x
2. Go to Logs page and change the minimum severity level to 2
3. Install the previous module
4. Complete 1 click upgrade
5. Login
6. Enable debug
7. Logout
8. Unable to login

**Comment by hibatallahAouadni** [comment]
Hello @indusone & @rsoulard-prolaser 

I didn't manage to reproduce the issue following your steps, see the attached screen record below:

https://www.awesomescreenshot.com/video/6472853?key=3be8f44316063881c0522a2b0e34c040

Please check and feedback.
Thanks!

**Comment by rsoulard-prolaser** [comment]
Hello @hibatallahAouadni 

You did not follow my steps, can you try again with a fresh install of PrestaShop 1.7.7.3 with my module.

**Steps to reproduce**
1. Open BO 1.7.7.x
2. Go to Logs page and change the minimum severity level to 2
3. Install this module: [logger.zip](https://github.com/PrestaShop/PrestaShop/files/7727490/logger.zip)
4. Complete 1 click upgrade
5. Login
6. Enable debug
7. **LOGOUT**
8. Login => unable to login

**Comment by marwachelly** [comment]
Hello @rsoulard-prolaser ,

I manage to reproduce your issue with an upgrade from 1.7.7.3 to 1.7.8.2 and following the steps bellow:

1. Open BO 1.7.7.3
2. Go to Logs page and change the minimum severity level to 2
3. Install this module: logger.zip
4. Complete 1 click upgrade to 1.7.8.2
5. Login
6. Enable debug
7. LOGOUT
8. Login => unable to login
https://watch.screencastify.com/v/0Sj2krEvYLqWB27WRS5J 

The issue is due to the new block "send email to " added starting from 1.7.8.0 :
![image](https://user-images.githubusercontent.com/89604350/146945523-2dfd9001-d2ac-417f-86d0-c5752b88413c.png)


The issue is not reproducible when upgrade from 1.7.7.3 to 1.7.7.8 => it is a regression 1.7.8.0 related to upgrade
Steps to reproduce the issue are updated.
Thanks,

**Comment by rsoulard-prolaser** [comment]
Hello @marwachelly,

I did a PR: https://github.com/PrestaShop/autoupgrade/pull/436

Thanks

**Comment by RecoX** [comment]
> Hello @rsoulard-prolaser ,
> 
> I manage to reproduce your issue with an upgrade from 1.7.7.3 to 1.7.8.2 and following the steps bellow:
> 
>     1. Open BO 1.7.7.3
> 
>     2. Go to Logs page and change the minimum severity level to 2
> 
>     3. Install this module: logger.zip
> 
>     4. Complete 1 click upgrade to 1.7.8.2
> 
>     5. Login
> 
>     6. Enable debug
> 
>     7. LOGOUT
> 
>     8. Login => unable to login
>        https://watch.screencastify.com/v/0Sj2krEvYLqWB27WRS5J
> 
> 
> The issue is due to the new block "send email to " added starting from 1.7.8.0 : ![image](https://user-images.githubusercontent.com/89604350/146945523-2dfd9001-d2ac-417f-86d0-c5752b88413c.png)
> 
> The issue is not reproducible when upgrade from 1.7.7.3 to 1.7.7.8 => it is a regression 1.7.8.0 related to upgrade Steps to reproduce the issue are updated. Thanks,

Thanks, it worked for me.
