### ISSUE TITLE
All orders have 0 totals in customer detail

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#26687]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

None of the payment I use are filling the payments table, they use their custom tables to store their data. And COD modules don't use it at all, because the payment arrives days/weeks after delivery.
For this reason, all order amounts o customer's detail page are 0.
![Výstřižek](https://user-images.githubusercontent.com/6097524/142663209-b163425d-f4d4-4996-a064-ad894dcce773.JPG)

### Describe the solution you'd like

Would it be a problem to show the total of the order, instead of the paid amount?
It would be more universal and I think the order total is more important value anyway. 🤔

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 


Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon.

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you
