### ISSUE TITLE
PS_checkout not working with website not being in full SSL

### ISSUE THREAD

**Issue by anthonylecot** [PrestaShop/PrestaShop#26693]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When loading new ps_checkout version, the payments are not showing up:
![image](https://user-images.githubusercontent.com/70704767/142708898-f4cf56b1-ef23-4fc2-9d8d-cf4259ec09e3.png)

There is also some errors in the console:
Mixed Content: The page at 'https://XXX/commande' was loaded over HTTPS, but requested an insecure resource 'http://XXX/module/ps_checkout/token'. This request has been blocked; the content must be served over HTTPS.
Uncaught (in promise) DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at A (https://www.paypal.com/sdk/js?components=buttons,marks,funding-eligibility,hosted-fields...

PS version: 1.7.8.1
PHP version

### Expected behavior

I expected that payments options are showing up properly, even if I'm not full SSL

### Steps to reproduce

Unfortunately I can't help you to reproduce this live in live, I don't want to jeopardize my website with that module update.

### PrestaShop version(s) where the bug happened

1.7.8.1

### If your bug is related to a module, specify its name and its version

ps_checkout > 2.0.9

**Comment by anthonylecot** [comment]
I migrated my shop to SSL, seems fine now but could be worse looking at that

**Comment by florine2623** [comment]
Hello @anthonylecot ,

If you have any issues with ps_checkout module, please contact the support directly through your BO.

Thanks!
