### ISSUE TITLE
SEO - Link Language and Currency 

### ISSUE THREAD

**Issue by rytaf** [PrestaShop/PrestaShop#26695]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Hello, I am using google merchant center and google shopping. When I upload an feed with defçfould language for example Turkish Language And Turkish Lira every thing ok but when I upload another language like English And Usd. Google bots came from United States. Language is English it is okey but Currency is Turkish Lira. And google sees the data incorrectly and removes the products from google. 

### Describe the solution you'd like

I need a feature where I can bind Language and Currency together. 
for example; Language change to Fr currency should be change to EURO same time 
But currently only default currency appears to be displayed.

**Comment by hibatallahAouadni** [comment]
Hello @LordIndustry 

> Google bots came from United States. Language is English it is okey but Currency is Turkish Lira. And google sees the data incorrectly and removes the products from google. 

What do you mean by that? Could you please provide screenshot or screen record 🙏 
Please check and feedback.

Thanks!

**Comment by florine2623** [comment]
Hello @LordIndustry ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
