### ISSUE TITLE
An extra request to the database on the front of the ps_emailsubscription module site

### ISSUE THREAD

**Issue by ewonta** [PrestaShop/PrestaShop#26696]
### Prerequisites

- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.
- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)

### Describe the bug and add screenshots

The ps_emailsubscription module creates a request to the database on the front of the site, and according to the logic of work, it should only be in the module settings when exporting.
![image](https://user-images.githubusercontent.com/13940741/142819762-334b6f91-9a08-4764-8ea3-85aa689f0c1a.png)

### Expected behavior

This request should be created only when the module is configured

### Steps to reproduce

1) Activate _PS_DEBUG_PROFILING_
2) 
![image](https://user-images.githubusercontent.com/13940741/142820142-086c406f-f812-409d-a506-7e53ec516405.png)

### PrestaShop version(s) where the bug happened

1.7.7.6

### If your bug is related to a module, specify its name and its version

ps_emailsubscription

**Comment by florine2623** [comment]
Hello @dmitrij1988 ,

Can you explain what step 2 represents ?
And what it should be instead ?

What version of the module ps_emailsubscription are you using ?

Thanks!

**Comment by ewonta** [comment]
PROFILING of the main page, SQL queries are displayed there, and in the first screenshot, the query should be executed only in the admin panel in the module setup, but it is also performed on the front of the online store.

This request should be executed only in the admin panel in the module settings, any version of the module.

**Comment by hibatallahAouadni** [comment]
Hello @dmitrij1988 

Thanks for your patience!
Ping @PrestaShop/prestashop-core-developers can someone please reproduce the issue :pray: 

Thanks in advance!

**Comment by atomiix** [comment]
Hey @hibatallahAouadni, I think @dmitrij1988 is right, code from line 123 to 129 seems useless and should be removed

**Comment by hibatallahAouadni** [comment]
@atomiix thanks for your confirmation
