### ISSUE TITLE
error when installing modules from "payment methods"

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#26709]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

https://www.awesomescreenshot.com/video/6120654?key=7c0d1aa9c563387173a05fa567683e5c

### Steps to reproduce

1. Go to payment methods
2.  Click install
3. See error

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @alfonsolr09 ,

I can't reproduce your issue on PS 1.7.8.x.
Please see my screen record : https://watch.screencastify.com/v/BCG5jLlISHdt7j5EMKmK

Can you check if you have any error on the console ?
Thanks!

**Comment by alfonsolr09** [comment]
Now works good...

**Comment by hibatallahAouadni** [comment]
Thanks :relaxed:
