### ISSUE TITLE
ps_crossselling - FO - products display is missing spaces

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#26705]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In ps_crossselling module v2.0.1 with PS 1.7.8.x, the display of the products isn't correct. There are no spaces between each product.
<img width="1064" alt="Screenshot 2021-11-22 at 15 43 54" src="https://user-images.githubusercontent.com/16019289/142881488-a1b50cd6-4c27-4733-8cf3-ca2fd750142d.png">

With PS 1.7.7.7, it was OK :
<img width="1150" alt="Screenshot 2021-11-22 at 16 10 48" src="https://user-images.githubusercontent.com/16019289/142885944-baf1c7bc-afbf-40e3-a7ca-66c56b7af758.png">

### Expected behavior

It should look like what we have in module featured products :
<img width="1162" alt="Screenshot 2021-11-22 at 15 44 15" src="https://user-images.githubusercontent.com/16019289/142881531-f1a5dc71-7977-44e0-85f3-f7bc00d4a744.png">

### Steps to reproduce

1. Make sure module cross selling is installed
2. Go to BO > Edit a product > Add Related Products
3. Go to FO > Product page > See display error

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_crossselling v2.0.1

**Comment by kickhatz** [comment]
Hello. Im newbie in github, sorry if here i shouldnt comment. I have already this bug too.
P.S. when i turn off ps_crosssell module, this module still working in product page, but in BO disabled. 
- have strange :ref: (3 image) but in product page it all chosen products by me.

![dis1](https://user-images.githubusercontent.com/95041373/143471160-e97fef72-9341-485c-8488-a925ac8904f4.JPG)
![dis2](https://user-images.githubusercontent.com/95041373/143471166-ab057421-6070-4d4d-b45d-f4f2a1bf4efc.JPG)
![dis3](https://user-images.githubusercontent.com/95041373/143471168-a4b7b554-d33d-4658-8b88-8298d5dbe1e3.JPG)

please, help us :)

**Comment by kickhatz** [comment]
@florine2623. Hi, i found where is bug, this is not ps_crossselling. It is public_html\themes\classic\templates\catalog\product.tpl > 228-241 line. But i dont know how to fix. i'll wait for answer here.

**Comment by kickhatz** [comment]
@florine2623 

I fixed it. You should edit 2 tpl files

public_html\themes\classic\templates\catalog\product.tpl
line 235: {include file='catalog/_partials/miniatures/product.tpl' product=$product_accessory productClass="col-xs-6 col-lg-4 col-xl-3" position=$position}

public_html\themes\classic\templates\catalog\_partials\miniatures\product.tpl
before starts {block name='product_miniature_item'} paste this into 
line 26: ​​​​​​​{capture assign="productClasses"}{if !empty($productClass)}{$productClass}{else}col-xs-6 col-xl-4{/if}{/capture}

**Comment by NeOMakinG** [comment]
Should be fixed by https://github.com/PrestaShop/PrestaShop/pull/26998

**Comment by Progi1984** [comment]
Fixed by @NeOMakinG in #26998 & tested by @florine2623
