### ISSUE TITLE
Blank Page After I moved my server files to locale

### ISSUE THREAD

**Issue by weihan00ae** [PrestaShop/PrestaShop#26707]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

I have this issue where I tried to move my server files to a local computer for testing purposes. But I encounted an issue, everywhere I go is blank page, I tried to enable debug mode and it still doens't show me anything not even a single error but it still blank.  I tried to see what was going and create product object on the dispatcher including the product.php file too but nothing it looked like it create the object but I didn't get the instance of the product with that specific id, instead, I got what it seemed an empty object. I tried to see if my db was the problem but it doens't seem so... I have no clue what to anymore to be honest, anyone can help?

Thank You!

### Steps to reproduce

1)copy the files and move it to another directory.

2)create a new db with exact data.

3) get a blank page.

### PrestaShop version(s) where the bug happened

1.7.6.4

### PHP version(s) where the bug happened

7.2.34

**Comment by florine2623** [comment]
Hello @weihan00ae ,

Can you make sure the info on your file `app/config/parameters.php` is matching with your current installation ?

Thanks!

**Comment by weihan00ae** [comment]
Hi @florine2623,

first of all thank you for answering! So I did some testing and I was wrong about the creation of an object. It actually creates the object and does everything. 

Today I looked at xampp logs and in the error file I got this.

`[Tue Nov 23 09:15:10.059804 2021] [php7:error] [pid 10256:tid 1860] [client 127.0.0.1:61880] PHP Fatal error:  ModuleCore::main(): Failed opening required 'C:\\xampp\\htdocs/modules/sociallogin/vendor/autoload.php' (include_path='C:\\xampp\\htdocs\\vendor/pear/pear_exception;C:\\xampp\\htdocs\\vendor/pear/console_getopt;C:\\xampp\\htdocs\\vendor/pear/pear-core-minimal/src;C:\\xampp\\htdocs\\vendor/pear/archive_tar;C:\\xampp\\php\\PEAR') in C:\\xampp\\htdocs\\modules\\sociallogin\\sociallogin.php on line 28`

Have you any idea?

Thank you very much for your help.

**Comment by florine2623** [comment]
It seems like there is an issue with the sociallogin module. In your files, `sociallogin` becomes `_sociallogin`
Can you try to disable it ? and refresh your page to see if the error is still present ?

Thanks!

**Comment by weihan00ae** [comment]
YES! It worked! Thank you very much @florine2623!

**Comment by florine2623** [comment]
Good news ! You are welcome ! :)
