### ISSUE TITLE
Errors in output of Profiling mode

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#26718]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The display of the profiling output contains errors:
- In Stopwatch SQL the times are labelled as milliseconds, but they are microseconds in reality
- In Stopwatch SQL, the display of the stacktrace does not work, because `<br>` is HTML-escaped
- In Doubles, the placeholders' HTML is also escaped

See screenshots:
![2021-11-23_165341](https://user-images.githubusercontent.com/7520695/143445824-f3ead5e9-55e3-40bc-90f9-9a8398a5e602.jpg)

![2021-11-23_165407](https://user-images.githubusercontent.com/7520695/143445686-cddf68ad-1660-4cbb-8940-2bf2642434f9.jpg)

### Expected behavior

The display should be corrected as follows:
- In Stopwatch SQL display the times as milliseconds and add digits after the comma to keep precision.
- In Stopwatch SQL, do not escape `<br>`
- In Doubles, do not escape the placeholders

Screenshots :
![2021-11-23_165831](https://user-images.githubusercontent.com/7520695/143445860-63f46611-9d2a-4050-b624-808db85e3575.jpg)
![2021-11-23_165757](https://user-images.githubusercontent.com/7520695/143445853-19d4fab0-6d99-442c-8997-5ffac7717065.jpg)

### Steps to reproduce

1. Enable Profiling mode
    - On your server, open the /config/defines.inc.php file.
    - Find this line (around line 43): define('_PS_DEBUG_PROFILING_', false);
    - In this line, change "false" to "true".
2. Examine the output and notice the errors stated above.

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Did you encounter these errors with PS1778 or any older version? and in which page (BO or FO)?
Please check and feedback.

Thanks!

**Comment by lmeyer1** [comment]
Hello Hiba,
I didn't try in an older version, only 1.7.8.0. The PR will be ready soon.
I noticed the problem in FO, but Profiling mode can be enabled in both. Thus the problems certainly appear on any page when Profiling mode is enabled.

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

I tried my best but I didn't manage to reproduce the issue in any page even with a product with specific price:

### BO > Product page with specific price:

![image](https://user-images.githubusercontent.com/23308427/143426404-9171ec0c-8f72-402a-96f7-0f6c6d09c7bc.png)

### FO > Product page with specific price:

![image](https://user-images.githubusercontent.com/23308427/143426452-2d40fffe-5f94-471c-9f5a-ac23efda2fbc.png)

---
![image](https://user-images.githubusercontent.com/23308427/143426988-fccc4104-b549-4693-ab50-ee7c28172ed9.png)

Please check and feedback.
Thanks!
