### ISSUE TITLE
FO - Shopping cart page - The checkout button is disabled after adding a product the POPULAR PRODUCTS list

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#26712]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the FO > Shopping cart page > The checkout button is disabled after adding a product the POPULAR PRODUCTS list
![image](https://user-images.githubusercontent.com/16067358/143004719-df1b0031-bd02-455e-b366-19afce6a8113.png)

### Expected behavior

Refresh the page => ok

### Steps to reproduce

1. Go to FO > Add a product to the cart > Go to shopping cart page
2. Remove the product
3. Refresh the page
4. In the `POPULAR PRODUCTS` section, click quick view for any product > Click Add to cart > Click Continue Shopping
5. The product is well added to the shopping  cart page, **but** the Checkout button is disabled
6. Refresh the page => ok

https://watch.screencastify.com/v/2eroGxqjnfbDb16PatCW

**Other steps to reproduce the issue**
1. Go to FO > Sign in 
2. Add a product to the cart > Go to shopping cart page
3. Sign out
4. In the `POPULAR PRODUCTS` section, click quick view for any product > Click Add to cart > Click Continue Shopping
5. The product is well added to the shopping  cart page, **but** the Checkout button is disabled
6. Refresh the page => ok

### PrestaShop version(s) where the bug happened

1.7.6.9, develop

### PHP version(s) where the bug happened

7.1, 7.3

**Comment by florine2623** [comment]
This is fixed on PS 8.1.x, I'm using v2.1.5


https://github.com/PrestaShop/PrestaShop/assets/16019289/c4a87456-3abb-4c93-a086-eefa347ef339
