### ISSUE TITLE
SEO & URLs - edit entry forgets initial page name

### ISSUE THREAD

**Issue by 0dp** [PrestaShop/PrestaShop#26725]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you edit a page under SEO & URLs it looks like the previously configured page name to which the rule is applied; is not inserted/remembered.

As a result, when clicking edit the page name is always reset to `attachment`
This to me looks like something that could create human errors due to oversight.

### Expected behavior

When editting a page under SEO & URLs the page name should not change unless user choose to.

### Steps to reproduce

1. Go to SEO & URLs
2. Edit a page that is not for attachment
3. observer page name defaults to `attachment`

https://user-images.githubusercontent.com/3642367/143218422-97efd0e9-e1d8-4f01-b818-38ca83efe597.mov

### PrestaShop version(s) where the bug happened

1.7.7.4

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Hello @0dp 

I didn't manage to reproduce the issue with PS1767 and PS1781, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/143281805-849c1feb-11fc-4c4b-a5b1-2bfd4c9146a3.png)

Please check and feedback.
THanks!

**Comment by 0dp** [comment]
I just tested on 1.7.5.2 here it works as expected

**Comment by hibatallahAouadni** [comment]
So, you only encounter the issue with PS1774?

**Comment by hibatallahAouadni** [comment]
@0dp could you please explain why you close the issue? Did you find a solution for your issue?
Thanks in advance :pray:

**Comment by 0dp** [comment]
Hi @hibatallahAouadni 
Since it was not reproducible on other versions i thought maybe it's not relevant.

I did not find a solution though.

**Comment by hibatallahAouadni** [comment]
Hello @0dp 

> Since it was not reproducible on other versions i thought maybe it's not relevant.

Indeed :wink: you just need to write this comment while closing this issue :pray: 

Thanks!
