### ISSUE TITLE
Wrong count of products on filters

### ISSUE THREAD

**Issue by yannicka** [PrestaShop/PrestaShop#26726]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The product counter of the filters is incorrect. It does not correctly take into account the prices in promotion.

Before filtering:

![image](https://user-images.githubusercontent.com/22885898/143222228-69b37a63-098c-45f4-867d-4c3f4d59544a.png)

After filtering:

![image](https://user-images.githubusercontent.com/22885898/143222389-6cae50a8-1e04-4bb4-8538-8330490fa1b8.png)

### Expected behavior

Promotional prices must be taken into account in the calculation of the number of products.

### Steps to reproduce

1. Install PrestaShop 1.7.8.0 with the module faceted version 3.7.1.
2. Create two products in the same category, with a common feature. One product must have a higher price than the other.
3. Put a promotion of 10 € on one of these products (the cheaper one in my case).
4. Create a faceted navigation that displays the feature for the category.
5. On the site, go to the category.
6. At this point, the feature counter should be correct (two).
7. Set a price filter higher than the promotional price.
8. Notice that the characteristic counter indicates that there are two products when there is only one.

### PrestaShop version(s) where the bug happened

1.7.8.0 (same on 1.7.7.1)

### PHP version(s) where the bug happened

7.4.25

### If your bug is related to a module, specify its name and its version

ps_facetedsearch v3.7.1

**Comment by hibatallahAouadni** [comment]
Hello @yannicka 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #25819. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #25819

**Comment by yannicka** [comment]
I'm not sure I understand your answer. I think you misunderstood, the ticket mentioned (#25819, that is from me) is about the product counter being incorrect while this ticket mentions the counter in the filters. The first problem has been solved, but not the second as far as I know.
