### ISSUE TITLE
CarrierModule::$definition undeclared

### ISSUE THREAD

**Issue by JoryHogeveen** [PrestaShop/PrestaShop#26732]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Since 1.7.8.0 we get an error `Access to undeclared static property: CustomShippingRate::$definition`
CustomShippingRate is a module extending the `CarrierModule` class.

The error occurs on line 2037.

Stacktrace:
```
Symfony\Component\Debug\Exception\FatalThrowableError:
Access to undeclared static property: CustomShippingRate::$definition

  at classes/ObjectModel.php:2037
  at ObjectModelCore::getDefinition()
     (classes/controller/AdminController.php:900)
  at AdminControllerCore->processFilter()
     (classes/controller/AdminController.php:1000)
  at AdminControllerCore->postProcess()
     (classes/controller/Controller.php:295)
  at ControllerCore->run()
     (classes/Dispatcher.php:518)
  at DispatcherCore->dispatch()
     (cms-login/index.php:93)
```

### Expected behavior

No error :)

### Steps to reproduce

Install CustomShippingRate module or create a simple custom module that extends the CarrierModule.
Go to a page where this module is used.

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

All

### If your bug is related to a module, specify its name and its version

CustomShippingRate v2.1.5

**Comment by JoryHogeveen** [comment]
Note to tester.
If you want to reproduce the issue using CustomShippingRate then you'll need to go to `Admin > Customers > Shipping quote` in order to see the error.

**Comment by hibatallahAouadni** [comment]
Hello @JoryHogeveen 

Is there possible way to reproduce the issue with BO? if there's, please list clear and concise steps to reproduce :pray: 
Otherwise, this module `CustomShippingRate` is not a native module. So, I think it will be better to contact the Module developer to fix the issue :wink: 

Thanks!

**Comment by JoryHogeveen** [comment]
I mentioned it here because the error involved the `CarrierModule` class, which is PS core.
But ok, nevermind then!
