### ISSUE TITLE
Pack item with Combination shows incorrect reference number.

### ISSUE THREAD

**Issue by jpgilberg** [PrestaShop/PrestaShop#26737]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Reference Number of items with "Combinations" that are part of a "Pack" default to the master reference number. The "Combination->Reference" number is not shown when the pack is selected or edited in the catalog ("list of products in this pack") once the pack is saved. See the attached image
![pack-item-screen-shot-2](https://user-images.githubusercontent.com/94985719/143285938-6fb503d4-6053-47a2-bdd4-b832fd3ef703.jpg)
.

### Expected behavior

The combination->reference number for the item in the pack is displayed instead of the master product reference number.

### Steps to reproduce

1. Go to Catalog->Products
2. Click on a Pack Item containing items with combinations
3. Edit the pack item
4. Scroll down to "List of products in this pack".
5. Items in the pack with combinations will display the items master reference number and not the combination->reference number.

### PrestaShop version(s) where the bug happened

1.7.5 - 1.7.8

### PHP version(s) where the bug happened

1.7.5 - 1.7.8

**Comment by hibatallahAouadni** [comment]
Hello @jpgilberg 

It seems your issue similar to this one #20443
Could you please check it and feedback.

Thanks!

**Comment by jpgilberg** [comment]
I understand the issue in #20443 as a search not finding a combination item when adding to a pack. I do not have this problem. In my issue, the search finds the correct combination item, and adds it to the pack. The correct combination reference number is displayed. However, once the pack item is saved and you go back to look at the pack item, the displayed reference number for this item reverts back to the main item reference number. (ex. Main Combination Reference # ABC-123-X, Item in Black Combination #ABC-123-BLK. ABC-123-BLK is added to the pack and displayed correctly. Pack item is saved. When you go back to look at the pack, reference #ABC-123-X is shown as the item in the pack.) I hope this makes sense.

Also, I noticed I didn't have the php version listed. We are using php 7.3.

**Comment by HanaRebaiQA** [comment]
Hello @jpgilberg 

I did manage to reproduce your issue On PS1752 & PS1778. But it fixed on PS178.

See screen-record below : 

PS1778 
https://watch.screencastify.com/v/Oo84GUVMO2kWF5hoyfwS

PS1781
https://watch.screencastify.com/v/Piz8sfEmJotJxRPOABb4

So, i will close this issue.

Thanks!
