### ISSUE TITLE
Problem with "allow_oosp" in Shop Group's on stock sync mode

### ISSUE THREAD

**Issue by 50l3r** [PrestaShop/PrestaShop#26736]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The problem appears on product list.

It doesn't get the allow_oosp property well if you have a shop group with stock synchronization mode.

When you try to change `out_of_stock` field it saves on ps_ stock_available table with id_shop 0 but in product list `ProductAssembler` try to get the current id_shop.

In the `AddMissingProductFields` function of `classes/ProductAssembler.php` it is necessary to check if it is a store with stock synchronization and execute the `LEFT JOIN` query with the correct `id_shop`:

```
private function addMissingProductFields(array $rawProduct)
{
    $shopGroup = $this->context->shop->getGroup();
    $idShop = (int) $this->searchContext->getIdShop();
    $idLang = (int) $this->searchContext->getIdLang();
    $idProduct = (int) $rawProduct['id_product'];
    $prefix = _DB_PREFIX_;

    if ($shopGroup->share_stock) {
        $stockShop = 0;
    }else{
        $stockShop = $idShop;
    }

    $nbDaysNewProduct = (int) Configuration::get('PS_NB_DAYS_NEW_PRODUCT');
    if (!Validate::isUnsignedInt($nbDaysNewProduct)) {
        $nbDaysNewProduct = 20;
    }

    $now = date('Y-m-d') . ' 00:00:00';

    $sql = "SELECT
                p.*,
                ps.*,
                pl.*,
                sa.out_of_stock,
                IFNULL(sa.quantity, 0) as quantity,
                (DATEDIFF(
                    p.`date_add`,
                    DATE_SUB(
                        '$now',
                        INTERVAL $nbDaysNewProduct DAY
                    )
                ) > 0) as new
            FROM {$prefix}product p
            LEFT JOIN {$prefix}product_lang pl
                ON pl.id_product = p.id_product
                AND pl.id_shop = $idShop
                AND pl.id_lang = $idLang
            LEFT JOIN {$prefix}stock_available sa
                ON sa.id_product = p.id_product
                AND sa.id_shop = $stockShop
            LEFT JOIN {$prefix}product_shop ps
                ON ps.id_product = p.id_product
                AND ps.id_shop = $idShop
            WHERE p.id_product = $idProduct
            LIMIT 1";

    $rows = Db::getInstance()->executeS($sql);
    if ($rows === false) {
        return $rawProduct;
    }

    return array_merge($rows[0], $rawProduct);
}
```

### Expected behavior

The "out_of_stock" field should take it or from  `id_shop 0` or save with its correct `id_shop` when you save product.

### Steps to reproduce

1. Enable Multistore
2. Create a Shop Group with stock sync
3. Change out_of_stock option ![](https://i.gyazo.com/85e5aefb9be2aafbd62db608eae64594.png)
4. Navigate to product list and see that allow_oosp/out_of_stock isnt correct

### PrestaShop version(s) where the bug happened

1.7.7.5

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment]
Hello @50l3r 

I don't seem to understand the issue :thinking: with multistore enabled, I have two shops:
- Presta_1
- Presta_2

Each has its own products, and each product has its own labels allow_oosp/out_of_stock:

![image](https://user-images.githubusercontent.com/23308427/143450573-7bd2d963-45c9-4807-9d06-68441ab54a21.png)

I see no issue in that :disappointed: could you please explain it further or provide a screen record :pray: 
Please check and feedback.

Thanks!

**Comment by 50l3r** [comment]
> Each has its own products, and each product has its own labels allow_oosp/out_of_stock:

Problem occurs when you have multistore and a group of shops with stock synchronization

![](https://i.gyazo.com/462aec85072f3ce311420de0883e6c75.png)

**Comment by hibatallahAouadni** [comment]
Hello @50l3r 

> > Each has its own products, and each product has its own labels allow_oosp/out_of_stock:
>
> Problem occurs when you have multistore and a group of shops with stock synchronization
>
> ![](https://i.gyazo.com/462aec85072f3ce311420de0883e6c75.png)

I have the same multistore configuration and yet I see no issue in that.
Could you please more details or a screen record.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @50l3r 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
