### ISSUE TITLE
Improve profiling mode

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#26745]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

When using Profiling mode,
- I'd like to know the order of execution of the queries
- I'd like a stacktrace that includes the functions called
- - I hate that the table is three screens wide because of a query that lacks line breaks

### Describe the solution you'd like

In Stopwatch SQL
- Add a column with execution order that allows to re-order the table
- Add the function name in the stacktrace
- Set a max-width for the queries column

### Alternatives you've considered

None

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Thank you for your suggestion. The Developer Team will take it into consideration for future developments. 
And thanks for your PR :rocket: 

Thank you

**Comment by matks** [comment]
What else is there to add 🤷‍♂️ @lmeyer1 is right all of this makes sense

**Comment by lmeyer1** [comment]
Just another improvement:
In table *ObjectModel instances* add the function name in stacktrace and display object id.

**Comment by hibatallahAouadni** [comment]
Thanks @matks for your approval :rocket:
