### ISSUE TITLE
API /customers endpoint inconsistent return format of JSON

### ISSUE THREAD

**Issue by Morph21** [PrestaShop/PrestaShop#26752]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Endpoint /customers have 2 different formats of json returned based on quantity of customers which will be fetched.

It's basically the same case as in #22760

### Expected behavior

I expect it to returns orders in same format, or different HTTP status code for empty list. The first one is a preffered

### Steps to reproduce

1. Call api /customers?output_format=JSON&display=full
2. It will be in format
{ "customers": [ { ... } ]}
3. Call api /customers?output_format=JSON&display=full&filter[id]=0
Response will be in format
[]

Why someone would need to fetch customer by id equals to "0" you would ask? That's because when there is no customer or it was deleted before instead of returning null or empty value while fetching orders the api returns 0 as the id

### PrestaShop version(s) where the bug happened

1.7.8.1

**Comment by Morph21** [comment]
Here is an example of returned id equals to 0

![image](https://user-images.githubusercontent.com/38075691/143442411-0073af64-5c3f-46d0-a93d-daa7f4f7d49d.png)

This bug also occures for /addresses.
I didn't test more endpoints but my rough guess is that it's an issue with every endpoint when it returns empty (It's good for xml but with json it's messed up

**Comment by HanaRebaiQA** [comment]
Hello @Morph21 

> Why someone would need to fetch customer by id equals to "0" you would ask? That's because when there is no customer or it was deleted before instead of returning null or empty value while fetching orders the api returns 0 as the id

I have deleted customers but none of them had a `0` as an `id`, check the screenshot below:

![image](https://user-images.githubusercontent.com/92912932/143568893-46b374ef-5b54-4c83-aa16-0b955f42e326.png)

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Morph21 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by Morph21** [comment]
I was trying to contact my client to get feedback about why he have there id "0" for a customer but sadly I didn't get any response. So I don't know why and how it is possible for situation like that to occur. But In general the problem here is about non consistent responses and not about that id equals to 0.

I just tested it in other way and you  still can get response like i said above.

1. Delete a customer (you want him to be able to register on same email if he want)
2. Fetch customers with filter[id]=x (where x is equal to deleted customer id)

That example is relevant and is not impossible especially with GDPR regulations in EU.
There is a possiblity that a client will want to delete his personal informations from system and when you fetch orders then fetch customers for that orders you will get an empty list like stated by me above, so please open that ticket and fix it like here #22760

**Comment by hibatallahAouadni** [comment]
Hello @Morph21 

You need to provide clear and concise steps to reproduce the issue :pray: 
Cause with the provided infos neither @HanaRebaiQA nor I have been able to reproduce the issue.
Then, I will reopen the issue :wink: 

Thanks!

**Comment by Morph21** [comment]
@hibatallahAouadni maybe when I describe my use case it will be easier to understand.

So basically I'm creating integrations with many ecommerce softwares for our clients to be able to fetch orders and create invoice with that data.

I need complete data which includes data from endpoint /customers

When i fetch orders then i try to fetch customer for each order I'm doing it with filter parameter so basically if i fetch 5 orders let's say that each of this orders have the same customer because it was last page so customer id for each will be let's say "13"
then I'm fetching customers with endpoint /customers/?output_format=JSON&display=full&filter[id]=13
And it's working perfectly if response for that request will not be empty
Results are in form:
```
{
  "customers" : [
     {... customer data ...}
   ]
}
```

What it means is basically that the root of response body is an object not a list of objects.
Now when you delete that customer you will still have id = 13 for those orders but you won't have a customer to fetch so for this request /customers/?output_format=JSON&display=full&filter[id]=13
response body will look like that:
```
[]
```

Which is different that before since root is no longer an object but now suddenly it becomes a list.

On the other hand if you do same steps but with results in xml so you need to remove "output_format=JSON" from request, the response body will look like that for results which are not empty:
```
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <customers>
       <customer>...customer data...</customer>
    </customers>
</prestashop>
```

And here is the result for empty response:

```
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <customers></customers>
</prestashop>
```

So basically when using xml api won't give back some data which is inside of "customers" tag
And in json api completly changes the structure of response body which is probably worst possible thing to do in API

If you want a list of steps then just do it like that
1. Create new presta server (without any orders, customers etc)
2. Make a new order
3. Fetch customers with filter id (/customers/?output_format=JSON&display=full&filter[id]=1) and check how structure of JSON looks like
4. Delete customer of that order
5. Fetch customers again and compare json structure with point 3

That's a huge problem with json because you need to explicitly tell your deserializer if you want to get list of objects or a single object. In xml you won't have that issue because you always assume that inside a tag you can have a list or a single object. There is no difference.

Also I'm not sure what you mean that you can't replicate this issue? 
Do you mean that it's impossible for you to get empty list with that endpoint or what exactly?

It would be ok to response for empty result with just empty response body but adding that 2 characters "[]" is the worst possible thing that you can do
