### ISSUE TITLE
Hide unavailable attributes option do not work properly on combinations with negative stock quantities

### ISSUE THREAD

**Issue by prestaalba** [PrestaShop/PrestaShop#26763]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When "Display unavailable attributes on the product page" option from Product Settings is set to No, if you have a product with some combinations with negative stock quantity, the attributes selectors showed in front office incorrectly hide some attributes that should be available for shopping.

### Expected behavior

Every attribute that has at least a combination with stock quantity greater that 0 should be displayed as a attribute selector in front office. Otherwise, clients cannot buy some available product combinations.

### Steps to reproduce

1. Go to "Product Settings" menu and set "Display unavailable attributes on the product page" option to "No" on the "Product page" panel.
2. Create a new product with combinations.
3. Generate some random combinations (for example with 2 colors and 2 sizes).
4. Set the combinations stock quantity so that the sum of the total quantity for an specific attribute is equal or less than 0. For example, in the image, color Naranja (Orange) combinations sum up 0.
![image](https://user-images.githubusercontent.com/18466848/143493324-843ecf63-1cb2-47b0-86cb-3227bec40b26.png)
Note that the "Behavior when out of stock" option is set to "Deny orders".
5. Go to check the product in front office. Naranja (Orange) color should be available on selectors at least for M size (with 1 as stock quantity), but is not displayed at all.
![image](https://user-images.githubusercontent.com/18466848/143493589-745da14d-d14c-4911-a6ac-2fc9c58aee87.png)

### PrestaShop version(s) where the bug happened

develop

**Comment by HanaRebaiQA** [comment]
Hello @prestaalba 

Thansk for reporting the issue!
I can reproduce the issue with PS1778, PS1780 and develop, see attached screen-records below : 

PS1778 : 
https://watch.screencastify.com/v/tmwvof9Bn7OJXXKGf6fy

develop : 
https://watch.screencastify.com/v/0jeVYcKPeAE0SSLmPnnH

I'll add this to the debug backlog so that it's fixed.

Thanks!

**Comment by prestaalba** [comment]
Hello @HanaRebaiQA I already made a PR with the solution https://github.com/PrestaShop/PrestaShop/pull/26764. Regards.
