### ISSUE TITLE
Exception on validateOrder

### ISSUE THREAD

**Issue by rodriciru** [PrestaShop/PrestaShop#26766]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If an exception occurs when validating a cart, and that exception occurs after having been inserted into the database as valid (in my case it was for having the debug mode enabled and trying to use sendmail with proc_open() disabled), the payment module will not be able to continue its function of returning to the bank the success of the transaction and it will be the case that the bank rejects the purchase, but prestashop will give it as paid, creating a great confusion and loss of money.
If possible exceptions are captured when sending the mail, there will be no problems, I suppose.

![imagen](https://user-images.githubusercontent.com/10741347/143557074-48f9a25b-3662-4271-90b1-33913d985465.png)

![UptnPTIBlAxnYf5B](https://user-images.githubusercontent.com/10741347/143556640-ced9808e-3e56-4e5a-b8aa-69a15f61fd28.png)

![wduCKpTvQwvYGcms](https://user-images.githubusercontent.com/10741347/143556643-6ccd8a86-3d01-4bfa-982f-fced5f9bb394.png)

### Steps to reproduce

1. Enable debug mode
2. use sendamail and disable proc_open() to raise a exception
3. try to validate a order
4. the order wil be vaild
5. but the paymen module cannot continue after this exception, such it wont sen de confirmation to the bank server

### PrestaShop version(s) where the bug happened

1.7.8.1

**Comment by HanaRebaiQA** [comment]
Hello @rodriciru 

Could you please check this  https://github.com/PrestaShop/PrestaShop/issues/22262#issuecomment-795599209 ?
I think its helpful.


Thanks!

**Comment by rodriciru** [comment]
Nop. the problem its not sending mails. Its order validation, that raises an exception when tries to send mail.
i think this should be controlled too avoid order errors.
I know that my config of mails its not correct, but now i dont care about that!

**Comment by pablomartin89** [comment]
Hi @rodriciru ,  if function proc_open() is not disabled, you get the same exception?
If not: why to disable that function? 

As I know, Prestashop (and Symfony) on the Mail Class , use Swiftmailer Library:
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Mail.php#L375

And SwiftMailer library requires proc_open() enable to work.
https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Transport/StreamBuffer.php#L291

So it seems like proc_open it's to be enabled to work with Swiftmailer Library.

**Comment by rodriciru** [comment]
yes, i know that.
Im not complaining about mail. My complai is exception catch in validation

**Comment by hibatallahAouadni** [comment]
Hello @rodriciru 

As @pmartin-webimpacto mentioned above: **SwiftMailer library requires proc_open() enable to work.**
So, please try to enable the **proc_open** and check if you still encounter the issue with the payment module.

I'm really sorry but despite our efforts, we were not able to reproduce your issue with the provided information.
We will close this issue.

Thanks!
