### ISSUE TITLE
Docker setup invalid for linux/WSL

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/PrestaShop#26768]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

WSL: 2
Distro: Ubuntu
Docker Desktop: 4.2.0 (70708)
Docker CLI: 20.10.10 (b485636)

Every time I try to setup Prestashop on docker in WSL I get:

> Error response from daemon: path /home/sharak/github/prestashop/PrestaShop is mounted on / but it is not a shared mount.

### Expected behavior

To work properly :)

### Steps to reproduce

1. clone repo into WSL 2
2. `docker-compose up` or using v.2 `docker compose up`

### PrestaShop version(s) where the bug happened

1.7.7x, 1.7.8.x, develop

**Comment by kpodemski** [comment]
Hey @SharakPL 

Just to be sure, which version of WSL? I recall there's more than one (I don't know the details)

**Comment by SharakPL** [comment]
WSL: 2
Distro: Ubuntu
Docker Desktop: 4.2.0 (70708)
Docker CLI: 20.10.10 (b485636)

**Comment by HanaRebaiQA** [comment]
Hi @SharakPL,

Thanks for ou report.
Do you have the same issue with this ticket: https://github.com/PrestaShop/PrestaShop/issues/17479 ?

Thank you!

**Comment by SharakPL** [comment]
@HanaRebaiQA no, the cause of that one is probably mixed PATH as WSL gets everything from windows PATH and adds whatever is in linux PATH. I get that error too sometimes.

This one is strictly about docker-compose file, which never works. #26769 fixes that for WSL. I'd appreciate if someone could check this change on Mac to be sure it doesn't break the setup for anyone
