### ISSUE TITLE
[BO - Mobile] Button "Download credit slip" is not well displayed

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#26779]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The button "Download credit slip" in the page Credit Slips is not well displayed, (Regression since 1.7.8.0)

![image](https://user-images.githubusercontent.com/23308427/143618309-5f34cddc-a042-4434-bc6a-fb55c4ddd16b.png)

PS: Following this #26040

### Expected behavior

we need to add the style (as it use to be with PS1.7.7.8)
`white-space: nowrap;`

![image](https://user-images.githubusercontent.com/23308427/143618249-ca34c72c-3e3f-4e34-b7da-4034c33075e8.png)

### Steps to reproduce

1. On mobile
2. BO>SELL>Orders>Credit Slips
3. See error > the button "Download credit slip" is not well displayed

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.2

**Comment by Hlavtox** [comment]
I think we can do a min-width on the button instead, so it can wrap to two lines at least. It eats too much space if it does not wrap at all I think.

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

I don't think so, see the attached screenshot below (it doesn't look good :sweat_smile: ):

![image](https://user-images.githubusercontent.com/23308427/143832158-de562b03-1a0f-4d5c-85fe-f4df9def4f75.png)

On mobile, we already have `overflow-x: auto;` in the table, so IMHO I think it will be better if we use the nowrap :wink: 

Thanks!

**Comment by Progi1984** [comment]
@NeOMakinG Could you check this issue ?

**Comment by Progi1984** [comment]
Fixed by @NeOMakinG in #27429 & validated by @HanaRebaiQA.
