### ISSUE TITLE
Get specific prices: let mysql optimize the query.

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#26772]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This is not really a bug. It's a performance enhancement. It is a valuable improvement in my environment, and I think it would improve on most other installations too, but to prove it would bee quite difficult...

Of all queries involving the table ps_specific_price, 
```
SELECT SQL_NO_CACHE COUNT(*) FROM (SELECT DISTINCT `id_product` FROM `ps_specific_price` WHERE `id_product` != 0 GROUP BY id_product ) AS counted LIMIT 1
```
in /classes/SpecificPrice.php:287 is consistently the one that is the slowest, between 100ms and more than a second.

The bug consists in the fact that this query is used to optimize a query that consistently takes less than 1ms. That is : spend 100 ms to get an improvement below the 1 ms level.

### Expected behavior

Do not try to optimize the query that already is faster than 1ms. It is useless to fine tune a query code for optimization. The datebase engine must do this work: based on the information about index statistics choose the best index available and optimize the query plan.

### Steps to reproduce

Prerequisites: 
use an environment with many specific prices. My setup:
- 25 shops
- 50k products
- 4M specific prices

1. Enable Profiling mode (https://doc.prestashop.com/pages/viewpage.action?pageId=51184700)
    - On your server, open the /config/defines.inc.php file.
    - Find this line (around line 43): define('PS_DEBUG_PROFILING', false);
    - In this line, change "false" to "true".
2. Display a product page
3. In the profiling output examine all the queries containing the specific_price table
   - Most queries are fast
   - The query cited above is manyfold slower.

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Thank you for your suggestion. The Developer Team will take it into consideration for future developments. 
Thanks for your PR :rocket: 

Thank you

**Comment by lvitale-webimpacto** [comment]
Hi. Didd you get any clue to optimize this sql?

**Comment by lmeyer1** [comment]
@lvitale-webimpacto 
Look at the PR #26773.

**Comment by lvitale-webimpacto** [comment]
thabks a lot

**Comment by frater1998** [comment]
still the same problem with 8.1.7 version  and 90k products in store

i receive error 503 when I add a specific price for each product.

any suggestions?
