### ISSUE TITLE
When increasing product purchase quantity, product image changes as well as the product

### ISSUE THREAD

**Issue by Rventura1989** [PrestaShop/PrestaShop#26777]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After updating the database to 1.7.8.1, at the front-office, when we add quantity to be purchased to a product, the product image changes to the image of another product as well as the address in the address bar.

https://user-images.githubusercontent.com/95083228/143579544-fbb0bf37-1b80-4052-92c5-cb6b75d605e7.mp4

### Expected behavior

It is expected that the selected product will remain, as well as its image, and that it will only increase the quantity to be purchased

### Steps to reproduce

1. select article 2. increase quantity from 1 to 2 3. observe the image to change to another product 4. observe in the address bar the change to the link of the other product

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.3

**Comment by alfonsolr09** [comment]
look at this
https://github.com/PrestaShop/PrestaShop/issues/21492
Similar problem but different....

**Comment by HanaRebaiQA** [comment]
Hello @Rventura1989 

Thanks for reporting the issue.
I did not manage to reproduce the issue with PS1781. See the attached screen-record : 

https://watch.screencastify.com/v/tpButFpjEn9YmKhTy0iA 

Please check and feedback.

Thanks!

**Comment by alfonsolr09** [comment]
@Rventura1989 Something similar happened to me, the error was caused by a module that included the theme. try disabling them one by one to see if it is solved

**Comment by Rventura1989** [comment]
Hello @HanaRebaiQA 
Thanks for reply.
Most probably the problem is related to some module, then.
Let's try the suggestion of @alfonsolr09.
We will give you feedback as soon as possible.

Thank you very much

**Comment by Rventura1989** [comment]
Olá @alfonsolr09 
thank you for responding.
We will try your suggestion to try to identify the problem.

Thank you very much

**Comment by alfonsolr09** [comment]
waiting for new news

**Comment by marwachelly** [comment]
Hello, 
Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a module or theme problem. We will close the issue. Feel free to create an issue when needed.
Thanks,
