### ISSUE TITLE
Error with dynamical form rendering in 1.7.8.1

### ISSUE THREAD

**Issue by krekken** [PrestaShop/PrestaShop#26786]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When i wan't to use a form, where my entity is dynamical from the database, with a form structure like this:
```twig
{{form_start(form)}}
{# form content #}
{{form_end(form)}}
```
I get this error message. 
![image](https://user-images.githubusercontent.com/58357424/143840105-c3ac1f7c-16a7-4cb0-b47b-d37385633bac.png)

If i use {{form(form)}} it actually works, but thats not good for me, cause i want to customize the template.

### Expected behavior

Expected behavior is to successfully display my form, instead of getting an error message

### Steps to reproduce

I made an example module, which can reproduce this bug.
https://github.com/krekken/formbugreproduce

if you install it on a 1.7.7.8 prestashop it will work, but it won't work if you install it on a 1.7.8.1 container. 

![image](https://user-images.githubusercontent.com/58357424/143933159-fa8e0810-bbca-47ec-9f04-f0792c51cf57.png)
the Form Bug Reproduce tab is the one, which contains the bugged form

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.4.25

**Comment by matks** [comment]
Wah 😮  that's very weird

-`form(form)` works but not `form_start(form)`
-  fine with 1.7.7 but not 1.7.8

**Comment by hibatallahAouadni** [comment]
Hello @krekken 

Following these steps, I had no issue:
1. Clone your module under /modules
2. Access to BO>IMPROVE>Modules>Module Catalog
3. Install the module
4. Click on Configure button
5. Save the configuration
6. Success => no error

![image](https://user-images.githubusercontent.com/23308427/143903637-c226c9f5-9bbf-48b9-83f3-af794ca152af.png)

Is there a missing step to reproduce the issue?
Please check and feedback.

Thanks!

**Comment by krekken** [comment]
> 

![image](https://user-images.githubusercontent.com/58357424/143933033-6b92025d-d379-4556-8fcd-4c7da05618fa.png)
i added a tab, and if you click on that you'll be able to see the bug. its either working if you're using 1.7.7.8, or not if you're using 1.7.8.1

i edited the issue, so it says so now

**Comment by krekken** [comment]
@hibatallahAouadni have u managed to reproduce the bug?

**Comment by hibatallahAouadni** [comment]
Hello @krekken 

With PS1.7.8.1 and PS1.7.7.8, I have the same behavior:

1. Clone your module under /modules
2. Access to BO>IMPROVE>Modules>Module Catalog
3. Install the module
4. Click on Configure button
5. Save the configuration
6. Success 
7. Click on **Form Bug Reproduce** in Main Menu
8. An exception was thrown

![image](https://user-images.githubusercontent.com/23308427/144993336-9372bd92-7e93-41c2-b3e4-04eb447cbe2c.png)

Please check and feedback.
Thanks!

**Comment by krekken** [comment]
> Hello @krekken
> 
> With PS1.7.8.1 and PS1.7.7.8, I have the same behavior:
> 
>     1. Clone your module under /modules
> 
>     2. Access to BO>IMPROVE>Modules>Module Catalog
> 
>     3. Install the module
> 
>     4. Click on Configure button
> 
>     5. Save the configuration
> 
>     6. Success
> 
>     7. Click on **Form Bug Reproduce** in Main Menu
> 
>     8. An exception was thrown
> 
> 
> ![image](https://user-images.githubusercontent.com/23308427/144993336-9372bd92-7e93-41c2-b3e4-04eb447cbe2c.png)
> 
> Please check and feedback. Thanks!

that is a different error. i updated the module, so if you re-download it, and install it again, it should now handle french, and show you the actual error.

**Comment by marwachelly** [comment]
Hello @krekken ,

With PS1.7.8.1 I still have another exception:

1. Clone your module under /modules
2. Access to BO>IMPROVE>Modules>Module Catalog
3. Install the module
4. Click on Configure button
5. Save the configuration
6. Success
7. Click on Form Bug Reproduce in Main Menu
8. An exception was thrown

![image](https://user-images.githubusercontent.com/89604350/145045999-93d2c947-ec79-40f3-827a-87493b60f8a0.png)

Could you please check?

Thanks,

**Comment by krekken** [comment]
> Hello @krekken ,
> 
> With PS1.7.8.1 I still have another exception:
> 
> 1. Clone your module under /modules
> 2. Access to BO>IMPROVE>Modules>Module Catalog
> 3. Install the module
> 4. Click on Configure button
> 5. Save the configuration
> 6. Success
> 7. Click on Form Bug Reproduce in Main Menu
> 8. An exception was thrown
> 
> ![image](https://user-images.githubusercontent.com/89604350/145045999-93d2c947-ec79-40f3-827a-87493b60f8a0.png)
> 
> Could you please check?
> 
> Thanks,

i replaced the language name with "placeholder" so if you download it again, and reinstall it, it should work, with every language name now

**Comment by HanaRebaiQA** [comment]
Hello @krekken 

I did to download the module again and reinstall it. But i have another exception : 

1. Clone the module under /modules
2. Go to BO>IMPROVE>Modules>Module Catalog
3. Install the module
4. Click on Configure button > Save
5. Click on `Form Bug Reproduce` under BO > SELL

Another exception was thrown

![image](https://user-images.githubusercontent.com/92912932/145593804-c09efa7e-b978-4793-a62b-25bdcc021f76.png)

Please check again and feedback!

Thanks!

**Comment by krekken** [comment]
> Hello @krekken
> 
> I did to download the module again and reinstall it. But i have another exception :
> 
> 1. Clone the module under /modules
> 2. Go to BO>IMPROVE>Modules>Module Catalog
> 3. Install the module
> 4. Click on Configure button > Save
> 5. Click on `Form Bug Reproduce` under BO > SELL
> 
> Another exception was thrown
> 
> ![image](https://user-images.githubusercontent.com/92912932/145593804-c09efa7e-b978-4793-a62b-25bdcc021f76.png)
> 
> Please check again and feedback!
> 
> Thanks!

thats the bug. try it on 1.7.7.8, it works there, but wont work in 1.7.8

**Comment by HanaRebaiQA** [comment]
Hello,

I did'nt manage to reporduce the issue on PS1778. So, **it's a regression.**
![image](https://user-images.githubusercontent.com/92912932/145778056-82c0c05e-74b2-4dc2-b7af-53912e77a221.png)

I'll add this to the debug backlog so that it's fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved.
If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you!

**Comment by krekken** [comment]
> Hello,
> 
> I did'nt manage to reporduce the issue on PS1778. So, **it's a regression.** ![image](https://user-images.githubusercontent.com/92912932/145778056-82c0c05e-74b2-4dc2-b7af-53912e77a221.png)
> 
> I'll add this to the debug backlog so that it's fixed.
> 
> Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.
> 
> Thank you!

i quote myself: if you install it on a 1.7.7.8 prestashop it will work, but it won't work if you install it on a 1.7.8.1 container.
so you had an error when u tried it on 1.7.8,
and it worked when you tried it on 1.7.7.8. you said u failed to reproduce the bug, but you literally did. what do you mean you didn't manage to reproduce the issue on 1778? of course you didn't cause it works on 1.7.7.8. the issue is that it doesn't work on 1.7.8.0+ ...
