### ISSUE TITLE
PS 1.7.8.1 Link Widget error

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#26781]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After updating PS  from 1.7.7.8 to 1.7.8.1 The linked widgets in page bottom disapeared.
When I try to linked them again the Errror ocure in the BO

### Expected behavior

Ii would like to see the linked winget in the bottom of the page as it was before

### Steps to reproduce

Go to my page https://te.com.ua
In the left side in the page bottom you will see the empty space instead the Linked Widget like in the 1.7.7.8
![image](https://user-images.githubusercontent.com/50954519/143723225-cf543706-5b3c-4423-a3e9-d96df7b5c416.png)

Now it look such
![image](https://user-images.githubusercontent.com/50954519/143723256-164288f8-42cf-411b-a0fd-80a64851116d.png)

Go to the BO
Try to Link Widget
You will see the next error

![image](https://user-images.githubusercontent.com/50954519/143723274-ba35f364-6248-46e9-847e-e1332683fd76.png)

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.1.33-37

**Comment by alfonsolr09** [comment]
![image](https://user-images.githubusercontent.com/62474824/143723535-d208f67c-0ceb-41b1-8844-c0ceaa048d5f.png)
i see it ok

**Comment by photinia73** [comment]
O sorry, you xisited the 1.7.7.8 
Please, visit the https://old.te.com.ua
I have the clone site for tests...

**Comment by kpodemski** [comment]
Hello,

It seems like you run an outdated database for this module, have you upgraded it in the back office? You definitely should have the `position` column in `link_block_shop` table.

**Comment by photinia73** [comment]
Yes you are right! After upgading all modules this problem disappeared. But appear the bad look of Search (with scroll bars)
![image](https://user-images.githubusercontent.com/50954519/143766761-c5c6e361-2822-49c9-968c-afc96fc52a8c.png)
in the 1.7.7.8 and before all was Ok

![image](https://user-images.githubusercontent.com/50954519/143766802-d16f35c8-b4ca-456d-83d2-a668e0c7df04.png)

**Comment by kpodemski** [comment]
Try to rename/remove `themes/yourtheme/modules/ps_searchbar/ps_searchbar.tpl`. That should do it.

**Comment by alfonsolr09** [comment]
> ¡Sí, tiene usted razón! Después de actualizar todos los módulos, este problema desapareció. Pero aparece el mal aspecto de Search (con barras de desplazamiento) en el 1.7.7.8 y antes todo estaba Ok ![imagen](https://user-images.githubusercontent.com/50954519/143766761-c5c6e361-2822-49c9-968c-afc96fc52a8c.png)
> 
> ![imagen](https://user-images.githubusercontent.com/50954519/143766802-d16f35c8-b4ca-456d-83d2-a668e0c7df04.png)

i see it ok

**Comment by photinia73** [comment]
Realy helped. Thank you very much!!! Other pages seems Ok )

**Comment by photinia73** [comment]
> Try to rename/remove `themes/yourtheme/modules/ps_searchbar/ps_searchbar.tpl`. That should do it.
Realy helped. Thank you very much!!! Other pages seems Ok )
