### ISSUE TITLE
margins (keyboard enter key) do not work in pages section

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#26784]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

margins (keyboard enter key) do not work in pages section

https://www.awesomescreenshot.com/video/6195369?key=87d696189a8d9a80f65dd07df532c8ef

### Expected behavior

intros should work fine

### Steps to reproduce

1. Go to design
2. Pages
3. See error

### PrestaShop version(s) where the bug happened

1.7.7.3, 1.7.8.0

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

No

**Comment by Hlavtox** [comment]
@alfonsolr09 Send the source code that tinyMCE created.

**Comment by alfonsolr09** [comment]
Who is tinyMCE? @Hlavtox 
I dont know what do you mean

**Comment by pablomartin89** [comment]
When break line (keyboard enter key),  TinyMCE source code has: 
`<p ></p >` (And that it's saved on database) 

But on the TinyMCE iframe it's printed:` <p> **<br/**> </p> `(That's it's the reason cause on the iframe the line break it's seen)

![image](https://user-images.githubusercontent.com/16488733/143789720-0b24976d-71ad-4efd-9a11-2ecde5118b22.png)

@alfonsolr09 i'm not pretty sure that this it's a Prestashop Bug. 
On TinyMCE (The editor), the Enter Key:  it's expected to create a new empty paragraph -> `<p> </p>`
If you just wanna a break lines,  type : SHIFT + ENTER --> `<br/>`

![image](https://user-images.githubusercontent.com/16488733/143790085-959bb66b-39ae-4ee2-9b84-33fb4573580c.png)

**Comment by alfonsolr09** [comment]
but what do you get by adding an empty paragraph if you dont write nothing?

**Comment by Hlavtox** [comment]
The solution is to press enter to make a new paragraph and the insert a single space. Should keep the paragraphs.

**Comment by alfonsolr09** [comment]
Okay, I'll test it later. But then, what is the use of introducing an empty paragraph?

**Comment by Hlavtox** [comment]
@alfonsolr09 I also don't know, but you created an issue about it, so why do you ask? 😁😁

**Comment by alfonsolr09** [comment]
I created an issue because I wanted to enter an intro as a margin, but it did not work. 😅
I did not know that to make it work I had to enter a space

**Comment by Hlavtox** [comment]
Man, ENTER is a new paragraph in Word since I was born :D

**Comment by alfonsolr09** [comment]
Yes, but i put an empty ENTER and no work.
In word, if you introsuce an ENTER and do not write anything, it works as an empty paragraph (margin).

**Comment by alfonsolr09** [comment]
I think I'm not explaining myself well ...

**Comment by HanaRebaiQA** [comment]
Hello @alfonsolr09 

Thanks for your report.
To resolve you problem, you can check this solution : 
Add this line of code : `<h1 style="margin-bottom: 100px;">` and its well worked. Hope it's helpful.

See the attached screen-record : 
https://watch.screencastify.com/v/LgkZVFsGWaUl4FuGdUQT

So, i will close this issue.

Thanks!

**Comment by alfonsolr09** [comment]
> Hello @alfonsolr09 
> 
> Thanks for your report.
> To resolve you problem, you can check this solution : 
> Add this line of code : `<h1 style="margin-bottom: 100px;">` and its well worked. Hope it's helpful.
> 
> See the attached screen-record : 
> https://watch.screencastify.com/v/LgkZVFsGWaUl4FuGdUQT
> 
> So, i will close this issue.
> 
> Thanks!

But its a bug? Or is it a function that only I want?

**Comment by Hlavtox** [comment]
@alfonsolr09 Empty space is not done by empty paragraph, if you did it on your university seminary work, you would lose points. You need to set proper margins as @HanaRebaiQA specified.

**Comment by danidomen** [comment]
@alfonsolr09 I understand you. The thing is that implementation of TinyMCE, better or not, is prepared to "not render" empty things like an empty paragraph maybe due considerations of the own browser interpretation of the "p" tag that doesn't have any size rendered if that tag is empty. As I know, also on wordpress plugins, TinyMCE by itself has the same "problems" that you can see something ligth differences between the editor and the final result.

For that, if you want really more space between contents you can:
- As @Hlavtox says, ENTER an then press Space to have an empty character on that paragraph then the browser can understand that the paragraph have something to render (but with this you can have also some headhaches)
- Or as @pmartin-webimpacto , to make a pure "break-line" (also less html tags), SHIFT + ENTER each time that you want to render a break-line to separate content with "white margin"

**Comment by alfonsolr09** [comment]
Ok, Thanks to both of you.
Here in Spain and from what I understand, if you want a blank space or a line break, press ENTER and add a "margin" or "white line"
The solution you propose is fine and it solves the problem for me, but I am not sure that the ENTER function is correctly defined...
