### ISSUE TITLE
ps_metrics absolute path on line 238 cause open_basedir warning

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#26783]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

As mentioned on the title trying to access a template file on ps_metrics Module causes a warning.

Shared hosting with open_basedir enabled, so PHP cannot access files outside the web root directory or specified path's.

Module ps_metrics, file ps_metrics.php, line 221 or 228, the template file that will not exists on that absolute path to the root directory:

`return $this->display(__FILE__, '/views/templates/hook/HookDashboardZoneTwo.tpl');`

`!file_exists($template)`

Easy to see the error.

Related issues.

https://github.com/search?q=HookDashboardZoneTwo&type=issues

I don't know how to make pull requests, hope you understand, thanks for you great job.

### Expected behavior

No warning message and a path related to the module views path and not to System Root dir.

### Steps to reproduce

Configure PHP with:

open_basedir = your directories, or whatever

Enable Debug Mode.

Go to Prestashop Dashboard.

See the warning:

Warning at line 2509 on file /www/classes/module/Module.php
[2] file_exists(): open_basedir restriction in effect. File(/views/templates/hook/HookDashboardZoneTwo.tpl) is not within the allowed path(s):

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.4.27

### If your bug is related to a module, specify its name and its version

ps_metrics v2.4.1

**Comment by hibatallahAouadni** [comment]
Hello @notyIssue 

It seems that your issue is not a PrestaShop core bug.
If your module is Metrics Official, please contact support team on Addons.

We will close this issue.

Thanks!

**Comment by ghost** [comment]
I'll not do that, since is a Prestashop Core Bug, solved it adding just a constant in Module Core class of Prestashop, since PrestaShop allows to pass all kind of paths, i saw that later, this error also occurs with ps_checkout.

For other users, i solved it just adding a `_PS_ROOT_DIR_ `at line 2509 of Module.php file, a Core Class, so i just override this method.

 


    protected function getCurrentSubTemplate($template, $cache_id = null, $compile_id = null)
    {

        if ($compile_id === null) {
            $compile_id = $this->getDefaultCompileId();
        }

        if (!isset($this->current_subtemplate[$template . '_' . $cache_id . '_' . $compile_id])) {
            if (false === strpos($template, 'module:') &&
                !file_exists(_PS_ROOT_DIR_ . '/' . $template) &&
                !file_exists(_PS_ROOT_DIR_ . $template)
            ) {
                $template = $this->getTemplatePath($template);
            }

            $this->current_subtemplate[$template . '_' . $cache_id . '_' . $compile_id] = $this->context->smarty->createTemplate(
                $template,
                $cache_id,
                $compile_id,
                $this->smarty
            );
        }

        return $this->current_subtemplate[$template . '_' . $cache_id . '_' . $compile_id];
    }`

**Comment by SharakPL** [comment]
Yeah, there are all kinds of errors with ps_metrics. I've just started getting another related to **ps_account** module. 

> PHP Notice:  Trying to get property 'version' of non-object in modules\ps_metrics\src\Presenter\Store\Context\ContextPresenter.php on line 169

##### line 169
```
'psAccountVersion' => $psAccountModule->version,
```
If it's required by **ps_metrics** then why isn't ps_account a dependency and why isn't it installed on new shops just like ps_metrics is? It should be obvious that when module uses information that is provided by another module then it should check first it that module even exists. Even I know that and I'm not very good at php.

It's the same with **ps_eventbus** module as it seems:

```
/** @var \Module $psAccountModule */
        $psAccountModule = \Module::getInstanceByName('ps_accounts');

        /** @var \Module $psEventBusModule */
        $psEventBusModule = \Module::getInstanceByName('ps_eventbus');
```
It just assumes these modules are there on the shop. Doesn't even try to check if they actually are 🤦‍♂️

**Comment by JuanjoSCu** [comment]
Hi,

Thanks, I did what you put by modifying module.php, but that causes other modules that are not developed by prestashop to fail and not with a warning, it fails with an err 500

The problem is in the modules developed by prestashop, I have detected the problem in 3 modules:

psgdpr, ps_facebook and ps_metrics 

psgdpr:
        return $this->display(dirname(__FILE__), '/views/templates/front/customerAccount.tpl');

ps_facebook:

$this->templateBuffer->add($this->module->display($this->module->getfilePath(), '/views/templates/hook/header.tpl'));

ps_metrics:

 return $this->display(__FILE__, '/views/templates/hook/HookDashboardZoneTwo.tpl');

**Comment by JuanjoSCu** [comment]
Looks like it's fixed!

removing / from path 

return $this->display(dirname(FILE), '/views/templates/front/customerAccount.tpl');

to:

return $this->display(dirname(FILE), 'views/templates/front/customerAccount.tpl');

Thanks @idnovate !!

**Comment by gdb721** [comment]
@JuanjoSCu on which file you did the change?

**Comment by oclavero** [comment]
In the case of ps_metrics, the equivalent change to @JuanjoSCu 's solution would be:
File: modules\ps_metrics\ps_metrics.php
Line 214
'/views/templates/hook/HookDashboardZoneTwo.tpl'
Change it to
'views/templates/hook/HookDashboardZoneTwo.tpl'

####################################################
  PSH 1.7.8.8
  PS METRICS 3.5.6
  open_basedir (PLESK DEFAULT) = {WEBSPACEROOT}{/}{:}{TMP}{/}
  PHP 7.4.33
####################################################

**Comment by HartLarsson** [comment]
seems this problem is present also in 1.7.8.8 and there is no official fix.

the prestashop team is aware?
