### ISSUE TITLE
[Wishlist - mobile] the block wishlist is not aligned in Customer View page

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#26780]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

the block wishlist is not aligned in Customer View page (caused by this PR #26064):

![image](https://user-images.githubusercontent.com/23308427/143620689-fca3b017-1334-4b41-b571-c328e86be5e7.png)

### Expected behavior

the block wishlist must be aligned with other blocks:

![image](https://user-images.githubusercontent.com/23308427/143620762-1fabedfc-ba6f-4443-ab7d-48686e92180e.png)

We need to add `<div class="row">` in this line:
https://github.com/PrestaShop/blockwishlist/blob/084e9306a4e905d759afe5d949437303c9840e7b/views/templates/hook/displayAdminCustomers.tpl#L20

### Steps to reproduce

1. After merging this PR #26064
2. On mobile
3. BO>SELL>Customers>Customers
4. Click on `View` of any Customer
5. Scroll down to Wishlist block
6. See error > the block is not aligned with the other blocks

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

Wishlist

**Comment by Hlavtox** [comment]
@hibatallahAouadni Solution is to remove the `col`, not add `row` ;-)
