### ISSUE TITLE
Category listing responsive

### ISSUE THREAD

**Issue by jmrftrs** [PrestaShop/PrestaShop#26794]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi, the listing in category in the responsive (mobile) with classic theme cuts the text, or maybe there's something too large that pulls text down.

<img width="183" alt="Captura de pantalla 2021-11-29 a las 13 01 05" src="https://user-images.githubusercontent.com/90832277/143864857-ac5f232d-3111-4d8e-88f2-2eecf2d2a82b.png">

### Steps to reproduce

navigate to a category

### PrestaShop version(s) where the bug happened

1.7.8

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

classic theme

**Comment by jmrftrs** [comment]
Update with image size

<img width="195" alt="Captura de pantalla 2021-11-29 a las 13 05 52" src="https://user-images.githubusercontent.com/90832277/143865217-00b1e715-071e-4109-9893-15f6483f538c.png">

**Comment by NeOMakinG** [comment]
Hey, what's the exact version? 1.7.8.1?

**Comment by NeOMakinG** [comment]
@jmrftrs I did try to reproduce it on the demo website => https://demo.prestashop.com/#/en/front

It looks like everything is fine :/

**Comment by jmrftrs** [comment]
1.7.8.1

> Hey, what's the exact version? 1.7.8.1?

**Comment by jmrftrs** [comment]
> @jmrftrs I did try to reproduce it on the demo website => https://demo.prestashop.com/#/en/front
> 
> It looks like everything is fine :/

Ok, then I'll try to research a little more :(
Thanks

**Comment by hibatallahAouadni** [comment]
Hello @jmrftrs 

I didn't manage to reproduce the issue with PS1781 as @NeOMakinG mentioned.
Waiting for your feedback.

PS: thanks @NeOMakinG for your quick replies :superhero: 

Thanks!

**Comment by jmrftrs** [comment]
Ok, I found it.

It's the module ps_legalcompliance. When you activate the option "label taxes included", it creates a news css code from aeuc_front.css:107

body.tax-display-enabled #products .thumbnail-container, body.tax-display-enabled .featured-products .thumbnail-container, body.tax-display-enabled .product-accessories .thumbnail-container {
    height: 358px;
}

And this 358px is what crashes the listing view.

This is where the class "thumbnail-container reviews-loaded" in the category listing.

**Comment by marwachelly** [comment]
Hello,
I didn't manage to reproduce the issue. Could you please check ?
https://watch.screencastify.com/v/KnrhXVfhFEUqqVtj0xZg
Thanks,

**Comment by hibatallahAouadni** [comment]
Hello @jmrftrs 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
