### ISSUE TITLE
BO - Products Block disappear when we need to add new product to the order

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#26797]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Orders page > View first order
When we need to add more products in the list, products block disappears !
![image (1)](https://user-images.githubusercontent.com/24647495/143883163-4138c721-0734-46c7-b60e-ad94d5191f39.png)

### Expected behavior

Products list and add product form should be displayed
![Capture d’écran de 2021-11-29 15-14-05](https://user-images.githubusercontent.com/24647495/143883360-4b92cd43-8fea-46fc-b6c4-7edddbea517a.png)

### Steps to reproduce

1. Go to Orders page > View first order
2. Click on 'Add a product' button
3. Check that 'Products list' is not visible

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Hello @nesrineabdmouleh 

I didn't manage to reproduce the issue after executing the `make install`.
So, I close the issue.

Thanks!
