### ISSUE TITLE
Prestashop 1.7.8.1 - AJAX product controller randomly returns an empty response with 200 status.

### ISSUE THREAD

**Issue by lim3ra** [PrestaShop/PrestaShop#26802]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

AJAX product controller randomly returns an empty response with 200 status.

### Expected behavior

There should be always a JSON in the response or an error log.

### Steps to reproduce

1. Go to the product with combinations
2. Change combination parameter
3. AJAX request to this URL is sent: APP_URL/index.php?controller=product&token=<token>&id_product=<product_id>&id_customization=0&group%5B10%5D=146&qty=1
4. Randomly in the response there is empty message with status code 200 (no error is generated even in Debug mode)
<img width="571" alt="Screenshot 2021-11-29 at 18 34 32" src="https://user-images.githubusercontent.com/26142543/143916204-f5891e3d-8122-4612-9b61-e90a63dae296.png">
5. Change combination parameters again - you will get JSON response
<img width="579" alt="Screenshot 2021-11-29 at 18 35 25" src="https://user-images.githubusercontent.com/26142543/143916156-9086a6d7-111f-48c5-b331-768b17273938.png">

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.4.24

**Comment by lim3ra** [comment]
I was able to get the error message:

`[PrestaShopObjectNotFoundException]
Can not retrieve the id_product_attribute
at line 7532 in file classes/Product.php

7527.                 );
7528.             }
7529.         }
7530. 
7531.         if (empty($idProductAttribute)) {
7532.             throw new PrestaShopObjectNotFoundException('Can not retrieve the id_product_attribute');
7533.         }
7534. 
7535.         return $idProductAttribute;
7536.     }
7537. 
ProductCore::getIdProductAttributeByIdAttributes - [line 1095 - controllers/front/ProductController.php] - [3 Arguments]
ProductControllerCore->getIdProductAttributeByGroup - [line 987 - controllers/front/ProductController.php]
ProductControllerCore->getIdProductAttributeByGroupOrRequestOrDefault - [line 537 - controllers/front/ProductController.php]
ProductControllerCore->assignPriceAndTax - [line 323 - controllers/front/ProductController.php]
ProductControllerCore->initContent - [line 306 - classes/controller/Controller.php]
ControllerCore->run - [line 518 - classes/Dispatcher.php]
DispatcherCore->dispatch - [line 28 - index.php]`

**Comment by hibatallahAouadni** [comment]
Hello @lim3ra 

I didn't manage to reproduce the issue with PS1781, see the attached screen record below:

https://watch.screencastify.com/v/BdnMgw0AT27l3k6Lepxc

Could you please provide more details or a screen record. 
Please check and feedback.

Thanks!

**Comment by lim3ra** [comment]
Seems it was not connected with Presta Core. 

Issue can be closed. Thanks.

**Comment by hibatallahAouadni** [comment]
@lim3ra Thanks for your feedback :wink:
