### ISSUE TITLE
1.6.0.9 admin dashboard stats error

### ISSUE THREAD

**Issue by aytekinazmi12** [PrestaShop/PrestaShop#26807]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

After the php version is 7.3 on my server, I cannot view the data in my admin statistics panel.
![Screenshot_1](https://user-images.githubusercontent.com/50143631/144048518-b5fe7e19-c472-4e18-a7a8-d73734739a34.png)

Thank you for help me :)

### Steps to reproduce

I dont know

### PrestaShop version(s) where the bug happened

1.6.0.9

### PHP version(s) where the bug happened

7.3.33

**Comment by pablomartin89** [comment]
Hi @aytekinazmi12 .

It's not a bug. 
Prestashop 1.6.x it's not compatible with PHP 7.3 

![image](https://user-images.githubusercontent.com/16488733/144051096-de5fc2d7-c594-4b2d-b271-5737437dfd62.png)

Regards.

**Comment by aytekinazmi12** [comment]
> Hi @aytekinazmi12 .
> 
> It's not a bug. Prestashop 1.6.x it's not compatible with PHP 7.3
> 
> ![image](https://user-images.githubusercontent.com/16488733/144051096-de5fc2d7-c594-4b2d-b271-5737437dfd62.png)
> 
> Regards.

Hi,

thank you for reply. 

I'm using version 1.6.1.6 on a different site and the php version is 7.1.33 but still the same problem. I think there is a problem here.

**Comment by hibatallahAouadni** [comment]
Hello @aytekinazmi12 

PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).

Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

PS: thanks @pmartin-webimpacto for your quick reply :rocket: 

Thanks!
