### ISSUE TITLE
Legal info is not displayed in contact module

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#26809]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

There is a field for legal info like registration number etc. in Prestashop settings.

![admin](https://user-images.githubusercontent.com/6097524/144063152-b632e413-6bd8-4a82-9383-a7cf112f1e2b.JPG)

### Describe the solution you'd like

This field should be displayed on contact page. Implementation already prepared in theme-refacto.

![v__st__i__ek](https://user-images.githubusercontent.com/6097524/144081521-2124df46-3995-4ba6-846d-03a8ad24a9b2.jpg)

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thank you for your suggestion and for the PR :rocket:  
The Product Team will take it into consideration for future developments. 

Thank you

**Comment by florine2623** [comment]
ping @PrestaShop/product-team ,

The PR is available and waiting for QA ? Can I have a PM ✅ on this issue ? :)

Thanks!

**Comment by marionf** [comment]
The registration number should be displayed in the contact page but also in the footer, under the email

<img width="279" alt="Capture d’écran 2021-12-01 à 11 04 10" src="https://user-images.githubusercontent.com/13449658/144214095-bf0fe8df-90a1-48b4-a5b5-02f1033d94a5.png">

**Comment by Hlavtox** [comment]
@marionf Ok! Should I do it in classic, or it's enough in theme-refacto?

**Comment by MatShir** [comment]
It should be on the new theme :)
The classic theme is now only for bug fix. @eternoendless @NeOMakinG, is there a doc explaining how the different themes will be maintained ? It's not the first we have the question.

**Comment by florine2623** [comment]
Hello @Hlavtox ,

Thanks for the PR !

I have a question about the test.
- I have installed the PR
- Commented all files in /themes/classic/modules/ps_contactinfo to avoid overrides
- I don't have the correct visual

Without PR :
<img width="289" alt="Screenshot 2021-12-01 at 14 08 24" src="https://user-images.githubusercontent.com/16019289/144258979-52abf0ad-96b2-4072-bca0-ca2ba6df04d5.png">

With PR :
<img width="284" alt="Screenshot 2021-12-01 at 14 07 15" src="https://user-images.githubusercontent.com/16019289/144259027-32308521-069e-43fb-ae7b-dff41ac8c72d.png">

Am I missing something ?
Thanks!

**Comment by NeOMakinG** [comment]
We didn't deprecate it, so I've a doubt about the fact that classic is only about bug fixes now? :/

**Comment by eternoendless** [comment]
We haven't officially deprecated classic yet

**Comment by Hlavtox** [comment]
Added it to classic also - https://github.com/PrestaShop/PrestaShop/pull/26832

**Comment by hibatallahAouadni** [comment]
@PrestaShop/prestashop-core-developers I think this issue should be reopened again cause we have another PR to merge, wdyt?

**Comment by fabiocranchi** [comment]
Solution:

Edit the file /modules/ps_contactinfo/ps_contactinfo.php
In array $contact_infos, add this line: 'regNumber' => Configuration::get('PS_SHOP_DETAILS'),
In the file just below the line 'company' => Configuration::get('PS_SHOP_NAME'),
Add: 'regNumber' => Configuration::get('PS_SHOP_DETAILS'),

Then, inside the theme, search for ps_contactinfo.tpl and add "
{$contact_infos.regNumber}" without quotes just below "{$contact_infos.address.formatted nofilter}"

tpl file location in classic theme:
themes/classic/modules/ps_contactinfo

Hope it helped =)

**Comment by laurentrousseau918** [comment]
Very good @fabiocranchi ! it works

**Comment by MatShir** [comment]
thanks @fabiocranchi
