### ISSUE TITLE
Add hook to display custom content in checkout

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#26800]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

I gathered some feedback from czech module developers regarding missing hooks they would like to add to v8.
Module developers cannot display their optional consent checkboxes and other data in checkout.

### Describe the solution you'd like

Add new display hook in checkout, before order confirmation checkboxes.

![141788833-3648536d-2eb3-4e31-a283-042ad77b25ea](https://user-images.githubusercontent.com/6097524/150674673-be32c69e-9f7c-40d9-ab82-ca73a8cf6a0d.jpg)

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thank you for your suggestion. The Developers Team will take it into consideration for future developments. 
Could you please provide more details about these hooks :pray: 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy :relaxed: 

Thank you

**Comment by matks** [comment]
Hello @Hlavtox isn't it a little bit what `additionalCustomerFormFields` hook is supposed to do? add checkboxes?

If we add display hooks, modules will be able to pass whatever they want to HTML. Good HTML that fits with current checkboxes... and garbage 😅 

If the need is "modules should be able to add checkboxes to 'create an account' step in checkout" I would think we whould rather have a list of configurable checkboxes that go through a hook (and `additionalCustomerFormFields` looks close).

**Comment by Hlavtox** [comment]
No they want to add it before order confirmation, I got this feedback from 2 independent teams. Both currently solve it by automatically/manually modifying the template.

> If we add display hooks, modules will be able to pass whatever they want to HTML. Good HTML that fits with current checkboxes... and garbage 😅

Like every other display hook, no? 🤷🏻‍♂️

**Comment by matks** [comment]
I have seen PR https://github.com/PrestaShop/PrestaShop/pull/27437 and now I understand the logic behind

**Comment by PululuK** [comment]
Fixed here https://github.com/PrestaShop/PrestaShop/pull/27437 by @ShaiMagal
