### ISSUE TITLE
2 files with same name in same folder !

### ISSUE THREAD

**Issue by cotiga** [PrestaShop/PrestaShop#26817]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

During an FTP sync, I end up with this error!
See capture ...
![capt-ecran 2021-11-29 à 11 36 55](https://user-images.githubusercontent.com/16390911/144214327-72584a4c-bd50-4c30-8934-98e117ce960a.jpg)

### Expected behavior

Whether these files are merged, or renamed !

### Steps to reproduce

Sync from live to local for dev.

### PrestaShop version(s) where the bug happened

1.7.8

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_emailsubscription

**Comment by hibatallahAouadni** [comment]
Hello @cotiga 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you

**Comment by cotiga** [comment]
Support plans... LOL
I think the module in question is provided by default and developed by you (prestashop team).
Therefore, you only reinforce my vision of this wobbly CMS.
Keep stewing, you'll be fine :p
