### ISSUE TITLE
Error installing PrestaShop: Module not installed : ps_accounts

### ISSUE THREAD

**Issue by danielcivit** [PrestaShop/PrestaShop#26838]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I am getting an error when try to install any 1.7.x version of PrestaShop. 

Error: "Module not installed : ps_accounts". 

It doesn' matter if I try to install this using a docker image, or download the package from the website and using the installer.

<img width="714" alt="Captura de pantalla 2021-12-02 a las 13 51 21" src="https://user-images.githubusercontent.com/64795062/144425696-e4efd945-7e45-4b45-b039-edcb1ead9de1.png">

<img width="1440" alt="Captura de pantalla 2021-12-02 a las 13 53 01" src="https://user-images.githubusercontent.com/64795062/144425756-e4b5105d-ecf9-4e71-8ade-6baf111c392c.png">

I always get the same error. 

### Expected behavior

Be able to install the application. 

### Steps to reproduce

1. Download PrestaShop. 
2. Install PrestaShop. 
3. Error on step "Install Addons modules".

### PrestaShop version(s) where the bug happened

1.7.7.4 or 1.7.8.1

### If your bug is related to a module, specify its name and its version

ps_accounts

**Comment by stickyrst** [comment]
This issue affects most (if not all) of Prestashop new installations of newer versions. I think it needs to be addressed ASAP

**Comment by salbatyku** [comment]
Confirming the issue

**Comment by DaLyRB** [comment]
Same issue on 1.7.8.1

**Comment by MatShir** [comment]
Thanks a lot for your feedback, we are doing everything to solve the problem as soon as possible. The issue is related to the PrestaShop company but until it’s not fixed we will keep the issue open.

**Comment by EdieLemoine** [comment]
Same here, tried on 1.7.8.0 and 1.7.8.1.

**Comment by fbobiano** [comment]
I've had the same problem for every 1.7.x versions but now it seems to work

**Comment by MatShir** [comment]
Hi everyone, 
Thanks again for the reports. The issue should be fixed now, we are back 💪 
I'm closing the issue. If the issue appears again, don't hesitate to comment or reopen the issue.
Thanks for your understanding,

**Comment by mstoluca** [comment]
¿lo resolvieron?  mismo error. [PrestaShop 8.1.7](https://github.com/PrestaShop/PrestaShop/releases/tag/8.1.7)

**Comment by ABODJI-Kondi-Kaled** [comment]
sorry I get the same issue

**Comment by presta-shopkeeper** [comment]
Same here,....version 8.1.7

**Comment by matks** [comment]
Hi everyone, just to be sure I just did an install of PS 8.1.7 downloaded from prestashop.com and it works for me
![Capture d’écran 2024-07-05 à 18 50 52](https://github.com/PrestaShop/PrestaShop/assets/3830050/d5d9dbb5-038d-4549-83d9-8f398553dfd3)


So the issue you encounter is not a problem that impacts everyone, but only some configurations

Could you provide me some informations?
- version of PHP used?
- operating system used?
- version of MysQL used?
- latest PHP error logs?

**Comment by Rudy1976Lympha** [comment]
Php 8.1.29
Ubuntu 22.04 LTS
MariaDB 10.6.18

I have the same issue on brand new server

**Comment by matks** [comment]
As the problem mentions ps_accounts, it could be useful to submit a github issue on the ps_accounts github account: https://github.com/PrestaShopCorp/ps_accounts/issues

But the message does not guarantee the problem comes from there. Issue could be totally unrelated, and this could be a visible symptom.

**Comment by JMauclair** [comment]
Same issue on 8.1.7.

Nginx log :
`2024/07/12 12:04:04 [error] 17089#17089: *4 FastCGI sent in stderr: "PHP message: PHP Warning:  Constant _PS_DO_NOT_LOAD_CONFIGURATION_ already defined in /sites/devpresta/install/controllers/http/smarty_compile.php on line 26" while reading response header from upstream, client: 192.168.2.124, server: dev.presta.local, request: "GET /install/index.php?compile_templates=1&bo=0 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "dev.presta.local", referrer: "http://dev.presta.local/install/index.php?restart=true"
2024/07/12 12:04:04 [error] 17088#17088: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  Constant _PS_DO_NOT_LOAD_CONFIGURATION_ already defined in /sites/devpresta/install/controllers/http/smarty_compile.php on line 26" while reading response header from upstream, client: 192.168.2.124, server: dev.presta.local, request: "GET /install/index.php?compile_templates=1&bo=1 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "dev.presta.local", referrer: "http://dev.presta.local/install/index.php?restart=true"
2024/07/12 12:04:05 [error] 17090#17090: *6 FastCGI sent in stderr: "PHP message: PHP Warning:  Attempt to read property "theme_name" on null in /sites/devpresta/var/cache/prod/Container6xboBxo/appAppKernelProdContainer.php on line 2910" while reading response header from upstream, client: 192.168.2.124, server: dev.presta.local, request: "GET /install/index.php?generateSettingsFile=true&_=1720785845767 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "dev.presta.local", referrer: "http://dev.presta.local/install/index.php?restart=true"
2024/07/12 12:04:22 [error] 17090#17090: *6 FastCGI sent in stderr: "PHP message: PHP Warning:  Attempt to read property "theme_name" on null in /sites/devpresta/var/cache/prod/ContainerXYKN0Om/appAppKernelProdContainer.php on line 3034" while reading response header from upstream, client: 192.168.2.124, server: dev.presta.local, request: "GET /install/index.php?installDatabase=true&_=1720785845768 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "dev.presta.local", referrer: "http://dev.presta.local/install/index.php?restart=true"
`
Presta log :
`*ERROR* 	v8.1.7	2024/07/12 - 14:04:53: PrestaShop\Module\Psshipping\Domain\Accounts\AccountsIsNotInstalledException: PrestaShop accounts (ps_accounts) module is not installed, please install it. in /sites/devpresta/modules/psshipping/src/Domain/Accounts/AccountsService.php:62
Stack trace:
#0 /sites/devpresta/modules/psshipping/src/Domain/Segment/Segment.php(60): PrestaShop\Module\Psshipping\Domain\Accounts\AccountsService->getAccountsContext()
#1 /sites/devpresta/modules/psshipping/psshipping.php(142): PrestaShop\Module\Psshipping\Domain\Segment\Segment->__construct()
#2 /sites/devpresta/src/Adapter/Module/Module.php(271): Psshipping->install()
#3 /sites/devpresta/src/Core/Module/ModuleManager.php(109): PrestaShop\PrestaShop\Adapter\Module\Module->onInstall()
#4 /sites/devpresta/src/PrestaShopBundle/Install/Install.php(1050): PrestaShop\PrestaShop\Core\Module\ModuleManager->install()
#5 /sites/devpresta/src/PrestaShopBundle/Install/Install.php(1000): PrestaShopBundle\Install\Install->executeAction()
#6 /sites/devpresta/install/controllers/http/process.php(243): PrestaShopBundle\Install\Install->installModules()
#7 /sites/devpresta/install/controllers/http/process.php(106): InstallControllerHttpProcess->processInstallModules()
#8 /sites/devpresta/install/classes/controllerHttp.php(277): InstallControllerHttpProcess->process()
#9 /sites/devpresta/install/index.php(53): InstallControllerHttp::execute()
#10 {main}`

**Comment by JMauclair** [comment]
➡ QUICK FIX ⬅

When Installing, in "Content of your shop",  switch from install all modules to the other option and disable Prestashop Shipping Module.
It seems that PSShipping is trying to be install before prestashop account

**Comment by addison74** [comment]
I confirm that @JMauclair solution solved this issue. I was able to install Prestashop 8.1.7 without any issues. 

I reported the same issue here https://github.com/PrestaShop/PrestaShop/issues/36541.

**Please note once you access the Backend you have to install the Shipping module.**

**Comment by mkvaghani** [comment]
Make sure, your database has no tables before installing prestashop.
Use empty database works.

**Comment by bpuig** [comment]
For me, what worked is going back, setting modules to manual install. Uncheck and check Prestashop Account.
