### ISSUE TITLE
FO - Productcomments module - an exception is displayed after adding a second comment

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#26835]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Related to #26834
n the FO > Product details page > If we try to add a second comment => an exception is displayed
![image](https://user-images.githubusercontent.com/16067358/144413410-b747c850-bedd-49c7-a500-dbfbe9c9753e.png)

### Steps to reproduce

1. Go to FO > sign in
2. Go to FO > Product details page and write a comment
3. Go to BO > Module manager > productcomments & upgrade it to v5.0.0
4. Approve the review
5. go to FO > See product details page
6. Click on write a review
7. see error: no grade displayed 
![image](https://user-images.githubusercontent.com/16067358/144413643-bbcec0d5-8b08-481b-9acc-9ebbb99b20eb.png)
8. set title & review and send 
9. See exception

it is a regression in the module productcomments

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

productcomments v5.0.0

**Comment by florine2623** [comment]
Tested on productcomments v6.0.2. This is fixed.


https://github.com/PrestaShop/PrestaShop/assets/16019289/dc733862-080a-4be6-86d6-7882dfc9403d



I'm closing the issue.
