### ISSUE TITLE
FO - Productcomments - The Grade and the comment are not displayed in the Product page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#26834]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After an upgrade of the module Productcomments, the grade & the comments are not displayed on the Product details page
![image](https://user-images.githubusercontent.com/16067358/144412282-8f79732a-31b1-45b7-ad0c-35c0e119b95a.png)

It should be
![image](https://user-images.githubusercontent.com/16067358/144412167-bbd861d9-680f-4b0c-9575-84e1c3e44dab.png)

### Steps to reproduce

1. Go to FO > sign in
2. Go to FO > Product details page and write a comment
3. Go to BO > Module manager > productcomments & upgrade it to v5.0.0
4. Approve the review
5. go to FO > See product details page
6. NO comment displayed + no grade displayed

### PrestaShop version(s) where the bug happened

1.7.8.1, 1.7.8.2build1

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

productscomments v5.0.0

**Comment by ghost** [comment]
Probably a linked bug to this issue:
After approving the comment, the number of comments awaiting review is not coming down:
![grafik](https://user-images.githubusercontent.com/92299973/144426232-2d21588e-c46d-4cbb-9916-4f0c20ae3028.png)
![grafik](https://user-images.githubusercontent.com/92299973/144426331-b619f91f-4b45-4f1b-9e83-3e507723e818.png)
If necessary, I can move it to a new bug report.

**Comment by photinia73** [comment]
In the module Productcomments disappeared the stars
https://te.com.ua/uk/av-resiveri-procesori/529-2-yamaha-rx-v385.html#/11-kolir-chornij

**Comment by okom3pom** [comment]
Already fixed by : https://github.com/PrestaShop/productcomments/pull/118#issuecomment-971620269
