### ISSUE TITLE
Email Template order_conf issue with Prestashop 1.7.8.1

### ISSUE THREAD

**Issue by Eric69400** [PrestaShop/PrestaShop#26845]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I have a problem with the email template order_conf in Prestashop version 1.7.8.1.

Does anyone reproduce this error?

When I go into the Prestashop email themes and try to interact with the order_conf template I get a systematic error:

![image](https://user-images.githubusercontent.com/95447750/144506571-15ef7447-ad2c-47df-b627-dd9e28f5328f.png)

![image](https://user-images.githubusercontent.com/95447750/144506670-2066c5bf-63ea-4b97-8a0c-82b99a5314e8.png)

![image](https://user-images.githubusercontent.com/95447750/144506755-459ff0ce-3ff4-486e-a364-26bc313cfb25.png)

![image](https://user-images.githubusercontent.com/95447750/144506805-418a250e-aa10-45a4-b7dd-61adc425ff59.png)

![image](https://user-images.githubusercontent.com/95447750/144506936-6c41839f-9925-41ea-95c1-b9ad4c8cc081.png)

I can't understand the problem.

Knowing that it only appears for this particular template, the other templates work

Thanks for your help

### Expected behavior

I expect the template to open normally, like this one for example: order_changed

### Steps to reproduce

1. Go to "Design" / "Email Theme"
2. On below, In the Email themes module click on the loupe on modern or classic.
3. Then find "order_conf" and click on http

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.4.24

**Comment by hibatallahAouadni** [comment]
Hello @Eric69400 

I didn't manage to reproduce the issue with PS1781, see the attached screen record below:

https://watch.screencastify.com/v/rv6ouMHZfZkJe22Qo9Rk

Please check and feedback.
Thanks!

**Comment by Eric69400** [comment]
Ok, thank you for your feedback, the issue is on my side. Sorry for the inconvenience.

**Comment by hibatallahAouadni** [comment]
Hello @Eric69400 

Glad to hear and thanks for your feedback.
Closing the issue!

Thanks!
