### ISSUE TITLE
DNI required but is not activated

### ISSUE THREAD

**Issue by daniel-lineaymedia** [PrestaShop/PrestaShop#26843]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello. 

I am having problems with the deactivation of the field for the DNI in shipments to Spain. 
As you can see in this image it is activated as mandatory in:

Customers > Addresses > Set required fields for this section.
![2748dd75-263b-40a9-adf7-b323d4db3d78](https://user-images.githubusercontent.com/11094154/144474440-be6d743b-24f4-43f5-87e9-a59f300b6c18.png)

 deactivate the dni field as mandatory and it looks like this.

![c26f7674-9a97-4be7-a0dd-961454d4a87f](https://user-images.githubusercontent.com/11094154/144474532-e38dddd4-4815-4006-83e6-2739fa8a60fa.png)

A few days ago I created a new country to be able to separate shipments to the Canary Islands from shipments to the peninsula Spain. Due to customs issues it is mandatory to have the DNI of the recipient to be able to send the goods to them. To avoid having to ask for the DNI by mail, I separated the Canary Islands in a new shipping zone and created a country called Spain - Canary Islands to be able to ask for a DNI field as mandatory. 

Personalise > International > Geographical locations > Countries
![2e4f70f1-d803-4862-99eb-b8219c6ccadb](https://user-images.githubusercontent.com/11094154/144474623-f1cbbe06-af99-456f-929a-2511c0f7391c.png)

We also mark the field "Do you need a tax identification number" as not necessary within the country.

![d4dc8490-cbab-4fb7-a25e-da0052d2d87d](https://user-images.githubusercontent.com/11094154/144474669-50aef014-8918-4848-bb80-bd7b484337fb.png)

After this creation Prestashop activated as mandatory the DNI again as shown in the first image for all customers regardless of whether they are from Spain peninsula, Canary Islands or any other country in Europe to which we make shipments.

After a lot of testing and revisions we were not able to make the DNI field not compulsory for all customers. 
We could detect that after disabling the DNI field as mandatory in the addresses when a customer registers in the shop and proceeds to fill in your shipping address Prestashop automatically reactivates the DNI field as mandatory for all and this is causing us many problems. 

![ddac9ec5-8bf1-4f2f-8250-6eb33ade11af](https://user-images.githubusercontent.com/11094154/144474742-483fd0a0-a862-4379-91d0-09e30c8e3d21.png)

Does anyone have the same problem or know how to fix this BUG? 

Thank you very much.

### Expected behavior

The problem for me is that if I deactivate the DNI field as compulsory, it is no longer compulsory.

Prestashop reactivates the DNI field automatically without me telling it to do, so this is a big problem.

### Steps to reproduce

1º Create a new Country whit DNI 
2º Add DNI field 
3º Select DNI as mandatory field
4º Register new user whit DNI 
5º Deactivate DNI as a mandatory field
6º Registering a new user without filling in the DNI field

### PrestaShop version(s) where the bug happened

1.7.7.2

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment]
Hello @daniel-lineaymedia 

Could you please check this issue #17647 it seems related to yours.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @daniel-lineaymedia 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by adarac** [comment]
Hi,

We had exactly the same issue described here.
It wasn't directly related to [#17647](https://github.com/PrestaShop/PrestaShop/issues/17647) but with a Spanish module called "Correos".

After a lot of debugging, we have verified that this bug is totally related to the "Correos" module (version 5.0.24) and they have fixed it in version 5.0.25. 
Well, they have fixed it partially because the DNI field doesn't appear as mandatory anymore but it still reappears as optional even if you remove it from the country's address format. They still need to fix this part but it is not that disruptive as the main problem described in this issue.

@daniel-lineaymedia do you have the "Correos" (version 5.0.24) module installed?

**PrestaShop version(s) where the bug happened**
1.7.8.2

**PHP version(s) where the bug happened**
7.4

**If your bug is related to a module, specify its name and its version**
Correos 5.0.24
It's been partially fixed in version 5.0.25

**Comment by etsmes** [comment]
I had a similar problem and it was solved with version 5.0.27 of the Correos module
