### ISSUE TITLE
Add hook in bulk edit combinations form

### ISSUE THREAD

**Issue by tom-combet** [PrestaShop/PrestaShop#26842]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

I'm developing a new module which add new fields to combinations/quantity legacy form (waiting for the new product page).
I used **`displayAdminProductsCombinationsStepBottom`** to add the field to combination form but there is no hook for bulk edit combinations form. The merchants might need my field here too, if they want to quickly edit the value for all the combinations.

### Describe the solution you'd like

Add a hook at the bottom of bulk edit combinations form, after native fields.

**Comment by hibatallahAouadni** [comment]
Hello @Kaudaj 

Thank you for your suggestion. The Developer Team will take it into consideration for future developments. 
Thanks for your PR :rocket: 

Thank you

**Comment by matks** [comment]
Thanks for the PR ! As said in https://github.com/PrestaShop/PrestaShop/pull/26841 I need @jolelievre opinion on this topic

**Comment by jolelievre** [comment]
Hi @Kaudaj we haven't finished migrating the combination completely, so I can't give you an exhaustive answer but it should rely on a Symfony form with an associated hook for form modifier so you should be able to add your custom fields.

We will also provide some documentation, tutorial, and example modules to indicate how to customize and/or extend each part of the product page. You can have a look at this pending PR for a preview https://github.com/PrestaShop/example-modules/pull/50 but it's not finished either.

So stay tuned for the coming PRs and new features in this migration, but the new product page should offer you such possibilities 😉

**Comment by tom-combet** [comment]
Ok, I'll wait for it then. Do you have any date goal for the new product page to go live?

**Comment by kpodemski** [comment]
@tom-combet the new product page is now live in PrestaShop 8.1, under the feature flag in upgraded installations, and will be default in PS 9 :)

I hope you can check how it works there :) If you still have an issue, make sure to let us know.
