### ISSUE TITLE
TinyMCE not visible with page CMS

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#26855]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello. I think it's a little bug with tinyMCE with page CMS.
In the page product, there is no problem.

**I have a message in the console (but no message in debug symphony) :**
`cms_page_form.bundle.js?1.7.8.1:25 Uncaught TypeError: Cannot read property 'textContent' of null
    at e.value (cms_page_form.bundle.js?1.7.8.1:25)
    at tN.<anonymous> (cms_page_form.bundle.js?1.7.8.1:25)
    at vp.c.fire (<anonymous>:2:197006)
    at tN.fire (<anonymous>:2:197532)
    at tN.load (<anonymous>:2:347090)
    at bw (<anonymous>:2:328168)
    at ww (<anonymous>:2:330246)
    at Aw (<anonymous>:2:332445)
    at tN.<anonymous> (<anonymous>:2:333551)
    at Array.<anonymous> (<anonymous>:2:96969)`

The tinyMCE (the area for text) is not available in French version ( I have two country selected)
In English version, "no problem" except i can register
In french version tinyMCE is not available ( textarea is in visibily: hidden due to a script ( cms_page_form.bundle.js )

An idea ??? Tanx !

![presta-tinyMCE-EN](https://user-images.githubusercontent.com/48174191/144595905-6691380a-0432-4f6d-a483-cf41db7597c4.jpg)
![presta-tinyMCE-FR](https://user-images.githubusercontent.com/48174191/144595916-6225c042-e794-4877-a06c-f50267cdbdbe.jpg)

### Steps to reproduce

No particular step. The problem is current...

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.4.26

**Comment by hibatallahAouadni** [comment]
Hello @Vizibl 

I didn't manage to reproduce the issue with PS1781, see the attached screen record below:

https://watch.screencastify.com/v/jWyHK7MarTHJciz4sVzA

Closing this issue as it's not a Core bug, it seems more related to your overrides.

Thank you

**Comment by ghost** [comment]
**I'm surprise. Are you sure ???**

From my side. I have 0 files in folder override/controler/admin or /front
When i switch to classic theme with only prestashop's modules, it's the same...

In the forum prestashop some people have the same problem : 
[](https://www.prestashop.com/forums/topic/1056035-probleme-bloc-de-texte-francais-page-cmsmentions-l%C3%A9gales-version-de-prestashop-1780)

**Comment by ghost** [comment]
and a other one :
https://www.prestashop.com/forums/topic/1057796-impossible-d%C3%A9crire-des-pages/

**Comment by hibatallahAouadni** [comment]
@Vizibl I see :thinking: could you please provide more infos :pray: 
Cause with the provided infos, I have not managed to reproduce the problem.

**Comment by ghost** [comment]
OK, sure. 

info_outline Informations sur votre serveur
Informations du serveur : Linux #1 SMP Wed Aug 14 08:29:59 EDT 2019 x86_64

Version du logiciel serveur : Apache
Version de PHP : 7.4.26
Limite de mémoire : 512M
Temps maximal d'exécution : 360
Taille max. pour envoi de fichiers : 512M

info_outline Informations sur la base de données
Version de MySQL : 10.5.13-MariaDB
Serveur MySQL : localhost

Préfixe des tables : 
Moteur MySQL : InnoDB
Connecteur MySQL : DbPDO

---

In the console i have this message (Chrome and Safari) : 

![buf-tiny-chrome](https://user-images.githubusercontent.com/48174191/144838746-ff698b6c-b381-4825-adbf-7eb548cf30ea.jpg)
![buf-tiny-safari](https://user-images.githubusercontent.com/48174191/144838752-b193f442-0fde-4a21-a965-2fafafde1788.jpg)

I try with classic theme, it's the same pblm
I try without module, it's the same pblm

TinyMCE seems to be different in CMS page, and in product page. 

If i'am looking in CSS:
`<div data-locale="en">` is display:block when is active
`and <div data-locale="fr">` stay display:none when is active
if i set `<div data-locale="fr">` in display: block, i can see TinyMCE

Its' the problem. 

the other problem that it's not possible to record the modifications.

**Comment by ghost** [comment]
Perfect ! After installation of 1.7.8.2 version, tinyMCE come back

**Comment by zenerry** [comment]
Hello folks,
do you know how to solve this issue without updating prestashop?
I'm in the same right spot as the example.
PS 1.7.8.1, php 7.4, 512Mb....
thanks.

**Comment by edzima** [comment]
Nope. In 1.7.8.6 the problem has returned ;(

**Comment by TomanDesign** [comment]
I have the same problem in 1.7.8.7. version in the case of the EN language. I am working on the UK store and the problem disappears when I change the 'locale' value from en-US to en-GB in the _lang table, but after saving the language changes, the problem returns.

**Comment by TomanDesign** [comment]
> I have the same problem in 1.7.8.7. version in the case of the EN language. I am working on the UK store and the problem disappears when I change the 'locale' value from en-US to en-GB in the _lang table, but after saving the language changes, the problem returns.

I had wrong language iso code set, it should be GB instead of EN.

**Comment by zenerry** [comment]
Hi @TomanDesign ,

this might be not the best technical answer, but as fas as I can tell is that after I updated something dd not when absolutely well, and I tryed just picking those JS bundles that where throwing errors (2 in my case) from the native installation package and overwriting them in my project.

After that, everything run smothly!

give me back your opinion if you try, please!

hope it helps!

PD: I can't remember if it was for the CMS page or ProductPage, that prestashop support made me activate, "experimental feature" option in "advanced parameters" so you can be able to use some of the Wysywyg text areas.

**Comment by TomanDesign** [comment]
Hi @zenerry, everything works for me after overwritten files js/admin/tinymce.inc.js and admin/themes/new-theme/public/cms_page_form.bundle.js by prestashop from clean install package files, (issue #27173 ) I don't know why 1-Click Update module doesn't udated them while upgadeing 1.7.7.8 to 1.7.8.7 version. In my case, I had also to correct the language iso code because the AP Page Builder module was crashing

**Comment by zenerry** [comment]
@TomanDesign Great news! then, we both think that "1-Click update" is missing some files to overwrite!

**Comment by HartLarsson** [comment]
i solved the problem after updating from 1.7.6.9 to 1.7.8.7 overwriting the 2 files too

**Comment by pollat** [comment]
I have same problem, I cannot see content field on CMS pages, how can I solve it (prestashop 1.7.8.8)?

p.s. I alredy tried to insert new "js/admin/tinymce.inc.js" and "admin/themes/new-theme/public/cms_page_form.bundle.js" file, but the problem remain.

**Comment by pollat** [comment]
Ok, solved. After inserted new "js/admin/tinymce.inc.js" and "admin/themes/new-theme/public/cms_page_form.bundle.js" file, delete pretsahop cache and try to connect to back-office from a anonymous windows.

**Comment by zenerry** [comment]
Are they the correct version?
Sis you get them from the right original folder?

**Comment by zenerry** [comment]
> Ok, solved. After inserted new "js/admin/tinymce.inc.js" and "admin/themes/new-theme/public/cms_page_form.bundle.js" file, delete pretsahop cache and try to connect to back-office from a anonymous windows.

Great!
