### ISSUE TITLE
PrestaShop marketing - An error has occured

### ISSUE THREAD

**Issue by samberrry** [PrestaShop/PrestaShop#26856]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I shared PrestaShop marketing module and someone faced this issue:
translation is: an error has occurred 

I did know where should I report it, so I created this issue. 
![262220516_1961529340693184_6240141919859484004_n](https://user-images.githubusercontent.com/20775532/144596426-afd42c29-c020-495f-a6d4-a905d5a6ddc3.jpg)

### Steps to reproduce

installing the module

### PrestaShop version(s) where the bug happened

i asked him

**Comment by samberrry** [comment]
PrestaShop version -> 1.7.6.9

**Comment by hibatallahAouadni** [comment]
Hello @samberrry 

It seems that your issue is not a PrestaShop core bug.
If your module is PrestaShop marketing Official, please contact support team on Addons

We will close this issue.

Thanks!

**Comment by samberrry** [comment]
yes it's not related to Ps Core. Okay Thanks
