### ISSUE TITLE
FO -Some exceptions in the FO after an uppgrade from PS16124 to PS1782build1

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#26862]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After an upgrade from PS16124 to PS1782build1
I have 3 different exception
In the FO > Category page 
![image](https://user-images.githubusercontent.com/16067358/144619076-88b44876-ec53-4b9c-b341-7e7986ddeccc.png)
In the FO > Click on All products > 2-home page 
![image](https://user-images.githubusercontent.com/16067358/144619212-40d19eb9-ac1b-45a2-9ed2-b3ac0b7535f3.png)
In the FO > best-sales Page
![image](https://user-images.githubusercontent.com/16067358/144619295-fb2418c0-d2d6-4a87-b4fd-e02c2dfa5f91.png)
In the FO > Brands page
![image](https://user-images.githubusercontent.com/16067358/144635774-9460feea-f68b-48d0-8eca-7800f0c9a3d3.png)

I attached a screen record
https://watch.screencastify.com/v/etoFb2S47TTaavLRPpiZ

This issue is reproduced by me & @marwachelly 

I checked an upgrade from PS16124 => 1781: ok (it is OK with @marwachelly ): https://watch.screencastify.com/v/R6MCgaVio5QUGVQkFH20 
I checked an upgrade from PS16124 => 1778 => ok: 

### Steps to reproduce

1. Install PS16124 with English language & France country
2. In the BO > International > Localization > Add the Algeria pack & United states pack
3. Create a new category 
4. Create a new product and associate it to the category created 
5. Upgrade to PS1782build1
6. Enable debug mode
7. Go to FO > Category page
8. Go to FO > All products 
9. Go to FO > best-sales Page

### PrestaShop version(s) where the bug happened

1.7.8.2BUILD1

### PHP version(s) where the bug happened

7.1

**Comment by atomiix** [comment]
@khouloudbelguith can you check if you have both file : `controllers/front/CategoryController.php` & `controllers/front/listing/CategoryController.php`. If so, can you delete the first one `controllers/front/CategoryController.php`, clear the cache, and see if it works?

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

Thank you!
yes, the category page is OK
If I click All products (2-home) => ok
But the FO > best sales page is NOK and BO > Brands page is NOK
I attached a screen record
https://watch.screencastify.com/v/MHYZD1CREOWXAMb9qwVT

Thank you!

**Comment by atomiix** [comment]
@khouloudbelguith can you try to make do the upgrade using 1.7.8.1 as `Number of the version you want to upgrade to: *` while still using the 1.7.8.2build1 archive?

![Capture d’écran 2021-12-03 à 17 43 20](https://user-images.githubusercontent.com/2168836/144639927-d66b9bf1-df9b-4360-b4d1-8d44047d4ca1.png)

**Comment by khouloudbelguith** [comment]
@atomiix, yes, it is ok :tada: 
https://watch.screencastify.com/v/yMboO03QLJ7mfed6dxMb

Thank you!

**Comment by khouloudbelguith** [comment]
Hi!

as discussed with @atomiix.
I will close the issue.

Thanks!
