### ISSUE TITLE
Multi-language feature mixes up languages on front-office

### ISSUE THREAD

**Issue by silverlayer** [PrestaShop/PrestaShop#26868]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

We had a PS with two languages, Portuguese and English. After we remove the English, the FO is blending these two languages. For instance:

![Screenshot_2021-12-03 lojademo](https://user-images.githubusercontent.com/52291477/144637836-26cfb4a7-b08a-432e-87af-50e37fb52a77.png)

### Expected behavior

The expected behavior is the whole FO in same language. In this case, Portuguese.

### Steps to reproduce

**given that** you have a 2-language PS **and** one of them is English
**when** you set the default language to anything other than English in _BO > International > Localization > Configuration_
**and** disable the English language in _BO > International > Localization > Languages_
**then** FO will mix these two languages

![default language](https://user-images.githubusercontent.com/52291477/144641872-2322869e-2a96-4ff2-8c33-7b081f55dc16.jpg)

![en-disabled](https://user-images.githubusercontent.com/52291477/144641926-e41729c7-4059-4691-a81e-8c574161ab97.jpg)

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Hello @klvnsa 

I didn't manage to reproduce the issue with PS1781, see the attached screen record below:

https://watch.screencastify.com/v/ybDgWikdjMIy6qGUUJJU

Please check and feedback.
Thanks!

**Comment by silverlayer** [comment]
Hi @hibatallahAouadni
Did you do the test with only one language enabled?

If you have 2 languages and disable one, you will only have one language enabled. So the language selector will not appear in FO, then languages mixture takes place.

Thank you so much.

**Comment by florine2623** [comment]
Hello @klvnsa ,

I can't reproduce your issue.
I have 2 languages :
<img width="1187" alt="Screenshot 2021-12-09 at 10 35 12" src="https://user-images.githubusercontent.com/16019289/145371192-b8baa40d-adf7-4aea-a6b0-df325201fef3.png">
All FR :
<img width="1107" alt="Screenshot 2021-12-09 at 10 37 54" src="https://user-images.githubusercontent.com/16019289/145371592-fca1c506-55cb-495a-822f-4eaabbaeff2e.png">

All EN : 
<img width="1143" alt="Screenshot 2021-12-09 at 10 35 27" src="https://user-images.githubusercontent.com/16019289/145371286-2295f62c-dc60-45c8-ae3a-9c3799563885.png">

Please make sure the module Link List is translated correctly. **Design > Link List**

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
