### ISSUE TITLE
CI is broken on autoupgrade - PHPStan with 1.6.1.18

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#26861]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

CI is broken on autoupgrade - PHPStan with 1.6.1.18 . The consequence is that all new submitted PRs are failing

https://github.com/PrestaShop/autoupgrade/pull/434
https://github.com/PrestaShop/autoupgrade/pull/435
https://github.com/PrestaShop/autoupgrade/pull/436
https://github.com/PrestaShop/autoupgrade/pull/437

### Expected behavior

CI should not fail unless there is a bug. If a bug is on branch we need to fix it.

### Steps to reproduce

See PR list

### PrestaShop version(s) where the bug happened

NA

### PHP version(s) where the bug happened

NA

### If your bug is related to a module, specify its name and its version

autoupgrade de

**Comment by atomiix** [comment]
Fixed by https://github.com/PrestaShop/autoupgrade/pull/438
