### ISSUE TITLE
Email new_order not sent with module email_alert

### ISSUE THREAD

**Issue by kiwrouge** [PrestaShop/PrestaShop#26863]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi,

I have a problem with the Mail Alert module : the new_order email isn't sent to the administrator.

All the other emails (test, order_conf to the client...) are sent.

I use the last version of the module (), tried to set a SMTP config (the mail are sent via PHP mail). Nothing change.

Module config : 
![This is an image](https://mesfichiers.info/sprt/ps-emailalerts.png)

All the email sent when a new order is created : 
![This is an image](https://mesfichiers.info/sprt/ps-email-sent.png)

### Steps to reproduce

1. Activate the Mail alert module, enable the new_order email and set an email
2. Create an order
3. No email received

### PrestaShop version(s) where the bug happened

1.7.6.4

### PHP version(s) where the bug happened

7.0.33

### If your bug is related to a module, specify its name and its version

ps_emailalerts v2.3.0

**Comment by hibatallahAouadni** [comment]
Hello @kiwrouge 

I didn't manage to reproduce the issue with PS1781 and ps_emailalerts v2.3.0, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/144869289-74d04bd0-70ba-4218-9b08-22967222bb15.png)

Could you please check your email configuration in BO:

![image](https://user-images.githubusercontent.com/23308427/144869734-60a1ff68-76dd-4cf2-b49b-50b0ee962fca.png)

Please check and feedback.
Thanks!

**Comment by kiwrouge** [comment]
Hi,

I checked the SMTP informations, the problem is still here if I use a correct SMTP or PHP mail.

**Comment by marwachelly** [comment]
Hello @kiwrouge ,
Could you please click on send a test mail and check that the test email has been sent to the email address you provided.
![image](https://user-images.githubusercontent.com/89604350/145042489-11df86cf-150c-439a-afbe-c31073c672ca.png)
![image](https://user-images.githubusercontent.com/89604350/145042758-1f668b6e-2dcb-4fde-9e88-13f82661d2f7.png)
Thanks,

**Comment by kiwrouge** [comment]
Yes the emails are sent well. All other emails are sent when an order is maid, just the new_order from Email Alert isn't sent at all (not even sent by prestashop because not in the logs)

**Comment by florine2623** [comment]
Hello @kiwrouge ,

I can't reproduce your issue, the email are all sent.

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

I'll close your issue as it cannot be reproduced.

Thank you

**Comment by kiwrouge** [comment]
The Prestashop support told me to ask here.
I ended disable the module email_alert and buy another one that works.
