### ISSUE TITLE
Customer reassurance text fields missing

### ISSUE THREAD

**Issue by CJH297** [PrestaShop/PrestaShop#26873]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I have an existing Prestashop 1.7.7.3 with an editable Customer Reassurance block operating as it should do. This is under php 7.3
![image](https://user-images.githubusercontent.com/74734570/144751072-7aa9633e-a99b-45e3-a4f3-9dc52cebabe6.png)

I have a new install of 1.7.8.1, but the text is not editable because the fields are missing

![image](https://user-images.githubusercontent.com/74734570/144751216-8f9e73aa-a0db-40db-849b-932a7fe33919.png)

Tested on two computers with identical results

### Expected behavior

Text fields should be present

### Steps to reproduce

1. Open reassurance module and attempt to edit to remove the 'edit with customer reassurance module' text
2. No ability to do so, as text fields are missing
3. Editing via 'translations' does not work either - text is present, but editing there does not update the front office or module (where text is visible before attempting the edit)

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

Customer reassurance

**Comment by CJH297** [comment]
Module version is 5.0.0 in both cases

**Comment by hibatallahAouadni** [comment]
Hello @CJH297 

I didn't manage to reproduce the issue with PS1781 and CustomerReassurance v5.0.0, see the attached screen record below:

https://watch.screencastify.com/v/yEeyiArxrImSQM54V3Yd

Please check and feedback.

_PS: by the way, I encounter this issue only once, fresh install, but when I choose language or refresh the page, the fields are well displayed. It seems load or cache problem._

Thanks!

**Comment by CJH297** [comment]
Thanks for checking. I still reproduce this behaviour here, but I now consider it must be a theme conflict - the theme is not compliant fully with 1.7.8 I suspect. It isn't a load or cache problem I think.

**Comment by hibatallahAouadni** [comment]
@CJH297 thanks for your feedback!
