### ISSUE TITLE
Aggiungere nuovo negozio in multistore

### ISSUE THREAD

**Issue by golianto** [PrestaShop/PrestaShop#26872]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Buongiorno,
ho un problema nell'aggiungere un nuovo negozio al multistore, quando clicco su salva viene indicato di indicare almeno una categoria principale, ma tutti i campi sono corretti.

qualcuno ha riscontrato lo stesso problema?

utilizzo l versione 1.7.8.1

<img width="2000" alt="Schermata 2021-12-04 alle 12 20 30" src="https://user-images.githubusercontent.com/95528485/144707636-82a43871-8ba4-48f3-bf06-d8362ac8858e.png">

### Expected behavior

Creazione nuovo negozio

### Steps to reproduce

1 . multinegozio
2. aggiungi nuovo negozio

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.3.33

**Comment by hibatallahAouadni** [comment]
Hello @golianto 

Please send your request in English. English is the norm on GitHub.
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thank you
