### ISSUE TITLE
Profiling not working wit PHP 7.4 and ¿Perfomance issue?

### ISSUE THREAD

**Issue by jmrftrs** [PrestaShop/PrestaShop#26871]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi,

I've been trying to use profiling, and changed to "true" in defines.inc.php, with PHP 7.4, 7.3 this didn't work.

Then I installed PHP 7.2.34 , and then profiling was working!

I also realized something else. With PHP 7.4 and 7.3, the TTFB was about 400-600ms. I tryed also APCu, Memcached and it was the same TTFB. Opcache was always on.

When I switched to PHP 7.2, without APCu or Memcached, TTFB was down to 190-250 ms. Really fast.

I don't know if this better performance with PHP 7.2 is an issue, but maybe deserves to be checked by the developers.

Thanks

### Steps to reproduce

With PHP 7.4 and 7.3 no profiling and high TTFB.

With PHP 7,2 profiling OK and fast TTFB.

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.4.26

**Comment by hibatallahAouadni** [comment]
Hello @jmrftrs 

Even with PHP7.3, the profiling is working perfectly, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/144875868-40fe2d57-6c25-4db3-93ae-3ea5f213cd0c.png)

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @jmrftrs 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
