### ISSUE TITLE
gdsgdsgs

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#26885]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

gdsgds

### Expected behavior

gsdg

### Steps to reproduce

gdsgdsg

### PrestaShop version(s) where the bug happened

8.0.0.0

### PHP version(s) where the bug happened

7.3

**Comment by jf-viguier** [comment]
gdsgdsgs too 😂

**Comment by NeOMakinG** [comment]
@matthieu-rolland You drunk too much beer again...

**Comment by NeOMakinG** [comment]
Is it a regression?

**Comment by kpodemski** [comment]
I agree. We should fix that!

**Comment by matks** [comment]
Any ETA?

**Comment by jolelievre** [comment]
No linked PR?

**Comment by jf-viguier** [comment]
@matthieu-rolland It's time for action, PR done.

**Comment by ghost** [comment]
I would like to know how to do: GDS spam without pressing the **F** key  

I can offer you a new keyboard with the **F** key for Christmas.

**Comment by jf-viguier** [comment]
@matthieu-rolland ?

**Comment by matthieu-rolland** [comment]
Sorry guys :D. I was using the PR to test something with the issueBot, I'm closing it now 👍
