### ISSUE TITLE
Deprecate HighDPI images

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#26886]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

I think that there is now a lot more to images - **srcsets**, than just a simple 2x resolution images. If 2x images are needed, they can be easily made by creating another image thumbnail size, but much better solution is to have several dimensions for usage on different resolutions.

### Describe the solution you'd like

Deprecate HighDPI images and all functionality joined together. We can make something much better in the new theme.

Ping @NeOMakinG

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thank you for your suggestion. The Developer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by matks** [comment]
It's not a decision to be made by developers, it's a choice for product team. It's about what prestashop merchant need.

I think for merchants that work in luxury and fashion, HighDPI images can be useful.

I move it to Waiting for PM.

**Comment by Hlavtox** [comment]
@matks By never means I want to remove this, but we can make it simplier, better and more controllable.

Imagine: I want to have better image for scaled displays for my products. Ok, I just make home_default_2x and slap an srcset in the template, done.

You can go further, for example as I do on my shops. I load a srcset with 6 different sizes, so the browser chooses the best depending on size, data saving plan and other variables. 👍
