### ISSUE TITLE
Problems js backoffice

### ISSUE THREAD

**Issue by golianto** [PrestaShop/PrestaShop#26888]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Good morning,
after updating to version 1.7.8.1, I have problems with loading js in the BO, many buttons no longer work, like it is not possible to enable and disable the modules or it is not possible to change the template, I don't know if it is a bug of the new one version,
how can i make the js libraries load before the scripts?

Graze

<img width="1046" alt="Schermata 2021-12-06 alle 12 56 13" src="https://user-images.githubusercontent.com/95528485/144841937-25f9f9f8-d6cb-49ed-aa45-f555c0e7feb0.png">

### Expected behavior

operation of the back office

### Steps to reproduce

access bo

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Hello @golianto 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must provide clear and concise steps to reproduce the issue**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
