### ISSUE TITLE
Post install fails when fixture installation is disabled

### ISSUE THREAD

**Issue by unlocomqx** [PrestaShop/PrestaShop#26892]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you disable the "Install demonstration data" option,
<img width="738" alt="2021-12-06 at 4 08 PM" src="https://user-images.githubusercontent.com/793712/144870393-0b2873b0-8013-4741-9d2f-96c282e9b17a.png">

the post install step fails
<img width="677" alt="2021-12-06 at 4 12 PM" src="https://user-images.githubusercontent.com/793712/144871050-7eb48312-98f9-4de3-8b78-7fe43cab0162.png">

The code validates the installation of the demo data, which didn't happen.
That's why the response comes unexpected and the error occurs.
I'll submit a PR to fix this.

### Steps to reproduce

1. try a new install
2. disable the "Install demonstration data" option
3. proceed with the install 
4. the post install step fails

### PrestaShop version(s) where the bug happened

8.0

**Comment by hibatallahAouadni** [comment]
Hello @unlocomqx 

I reproduce the issue with develop, see the attached screen record below:

https://watch.screencastify.com/v/kBm7ojld0NEEhjuCaT7H

On 178x branch it works without errors, so it's a **regression**!
I’ll add this to the debug backlog so that it’s fixed. Thanks for your PR :rocket: 

Thank you
