### ISSUE TITLE
Profiling navigation can be made easier with a fixed index

### ISSUE THREAD

**Issue by unlocomqx** [PrestaShop/PrestaShop#26896]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Navigating the profiling results can be difficult, because you have to scroll up to the index each time you want to navigate to a different section.
<img width="286" alt="2021-12-06 at 5 17 PM" src="https://user-images.githubusercontent.com/793712/144881992-42c1cb04-181d-401a-bfb7-8c973f81d083.png">

### Describe the solution you'd like

Make the index fixed on top of the page (i'll submit a PR for this)

<img width="367" alt="2021-12-06 at 5 18 PM" src="https://user-images.githubusercontent.com/793712/144882299-bc7cc7b1-e45e-4288-8e35-8cad2c189c78.png">

**Comment by hibatallahAouadni** [comment]
Hello @unlocomqx 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. 

Thanks for your PR :rocket: 

Thank you
