### ISSUE TITLE
BO - Multistore - migrated page with checkboxes

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#26904]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Configurations pages with checkboxes are: https://github.com/PrestaShop/prestashop-specs/blob/master/content/1.7/back-office/multistoregeneralspecs.md#checkboxes

when a shop is selected, The checkboxes are not aligned
![image](https://user-images.githubusercontent.com/16067358/145023319-53f4c2be-9254-4087-8583-b1e82155be91.png)

This is a new behavior in PS178
In the PS1778, we don't have checkboxes, so it is not a regression.

### Steps to reproduce

1. Enable multistore
2. Create a new shop
3. Go to BO > General > Maintenance page
4. Select a shop
5. See error: The checkboxes are not aligned

### PrestaShop version(s) where the bug happened

1.7.8.0, develop

### PHP version(s) where the bug happened

7.3

**Comment by khouloudbelguith** [comment]
This issue is reproduced while testing this PR: https://github.com/PrestaShop/PrestaShop/pull/26716#issuecomment-979931590
Ping @PrestaShop/product-team, this issue is not a regression because it is a new behavior in the PS178But it should be fixed in Project 1.7.8.x or 8.x.x?

Thank you!

**Comment by jolelievre** [comment]
Closed by #27430
