### ISSUE TITLE
Wholesale price must be synced with combination suppliers

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#26906]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

In new product page we handled the synchronization between the product's wholesale price and the price of its default supplier They must be equal and synced at all times

This is handled in the CQRS command and it also needs to be done in the FO with js to keep everything consistent. This part has already been handled for standard products but we need to do the same for combinations since their supplier's data are handled in combination form

### Describe the solution you'd like

The CQRS part should be similar to what was done in product command ds, however we need to think about how we handle the sync between the Combination form in a modal and the wholesale price which is in the "parent" product form (this part has to be defined/though of)

### Alternatives you've considered

This issue should also be the occasion to refactor the `ProductSuppliersManager` component which shouldn't be injected with the product form model The model should watch changes from the outside and call a public method on the suppliers manager to keep it synced

**Comment by marwachelly** [comment]
Hello @jolelievre ,

This issue is it ready or it should be waiting for PM ?

Thanks,

**Comment by jolelievre** [comment]
Hi @marwachelly,

It's ready it is to avoid forgetting a refactor and a feature
