### ISSUE TITLE
Searchbar

### ISSUE THREAD

**Issue by tecnoservicel** [PrestaShop/PrestaShop#26901]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The search bar changes the background color and I cannot modify it, and it disappears from the mobile version, if I deactivate it, the background color returns

![image](https://user-images.githubusercontent.com/23308427/145171957-1c01b655-118a-464a-9e18-c49b97ce128a.png)

### Expected behavior

no change color and no disappears mobile version.

### Steps to reproduce

1. version desktop, color change fff
2. version mobil disappears
3. disable search bar, return color header.

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_searchbar

**Comment by marwachelly** [comment]
Hello @tecnoservicel , 
Thanks for your issue. Unfortunately, there is not clear steps to reproduce the issue. So with the provided information I didn't see any problem as it is in the screen record.  Could you please clarify the step to reproduce. 
https://watch.screencastify.com/v/2R4M59IV5IrxVGQdRMKw

Many thanks,

**Comment by hibatallahAouadni** [comment]
Hello @tecnoservicel 

This issue is related to your theme, please contact your theme developer to fix the issue.
Closing this issue as it's not a Core bug.

Thanks!
