### ISSUE TITLE
Blockreassurance v5.0

### ISSUE THREAD

**Issue by lmaupate** [PrestaShop/PrestaShop#26905]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello, 
After I downloaded the module blockreassurance-5.0.0.zip, I tried to upload il on the back office but it doesn't work.
I have an error : Upload failed. This file seems not to be a valide .zip module.

Do you know what went wrong ?

### Steps to reproduce

Go to Upload a module
Select blockreassurance-5.0.0.zip
Validate
An error occured : Upload failed. This file seems not to be a valide .zip module.

### PrestaShop version(s) where the bug happened

1.7.1.2

### PHP version(s) where the bug happened

7.1.33

### If your bug is related to a module, specify its name and its version

blockreassurance-5.0.0.zip

**Comment by marwachelly** [comment]
Hello @lmaupate,
Could you please provide me with the exact link to download the blockreassurance module.
Thanks,

**Comment by lmaupate** [comment]
Here is the Link :

https://github.com/PrestaShop/blockreassurance/releases/tag/v5.0.0

It's in Asset, the file Source Code.zip

**Comment by matks** [comment]
@lmaupate the "Source Code" zip file is not a module you can simply upload in your BO and it works, it's the source code.

To convert the source code into a module ready to be used you must follow https://github.com/PrestaShop/blockreassurance/blob/dev/README.md instructions

**Comment by lmaupate** [comment]
Sorry, but to read the readme.md instruction didn't help me. 
Where can I find a detailed explanation to convert source code into a module ready to be used ?
