### ISSUE TITLE
BO - An exception is generated while clicking to preview the dropdown-menu of Email Theme with multistore when no order created

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#26919]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

While clicking to preview the dropdown-menu of Email Theme with a new shop created (not the default one) when no order is created ==> Exception
![image](https://user-images.githubusercontent.com/92912932/145220637-3212c744-dcec-4e53-a26c-0b81678a90ce.png)

See screen-record below : 
https://watch.screencastify.com/v/uH19Lz9O8tNh17XVyCOq

### Expected behavior

The content of all the dropdown-menu of Email Theme when choose the new shop created are well displayed. No exception is generated.

### Steps to reproduce

1. Enable multistore and create a new shop
2. Verify that there is no order created
2. BO>IMPROVE>Design>Email Theme
3. Change the shop of the new one created
2. Click on the loop of `classic` / `modern`
3. Click on Http  ==> See Error > Exception is generated
4. Click on the ropdown-menu and Preview ==> See Error > Exception is generated

### PrestaShop version(s) where the bug happened

1.7.7.8 & 1.7.8.1 & 1.7.8.x

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment]
This issue is fixed on PS 9.0.0

https://github.com/user-attachments/assets/c68a53c9-b494-441f-877d-6ec35951e85f

So I'm closing it !
