### ISSUE TITLE
Configuration Forms: labels not disabled for disabled field on page load

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#26916]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In multistore config forms, labels of disabled fields are not greyed out on page load:

https://watch.screencastify.com/v/iROFMEXfphEKloHrfMkY

Once we enable then disable the field the label is greyed out properly

### Expected behavior

When a field is disabled, its label should be disabled too on page load.

### Steps to reproduce

- Enable multistore
- Add at least one shop
- Go to the maintenance configuration page in single or group shop context
- Disabled fields (fields that are not checked) should have disabled labels on page load

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

irrelevant

**Comment by Progi1984** [comment]
@matthieu-rolland Should be fixed in #27339
