### ISSUE TITLE
Cache folders are duplicated

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/PrestaShop#26924]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Few last versions of prestashop has been creating both `prod` and `pro_` folders in _var/cache/_. It seems also `dev` and `de_` are being created. What is that all about?

### Expected behavior

It used to be just `prod` and `dev` folders in _var/cache/_

### Steps to reproduce

1. Move around several pages of backoffice and frontoffice
2. Check _var/cache/_

### PrestaShop version(s) where the bug happened

1.7.7.x, 1.7.8.x

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @SharakPL ,

I have the same behavior.
When in production mode, I have `prod` and `pro` folders. When in debug mode I have `dev` and `de` folders.
I'll ping dev team to have their insight.

Thanks!

**Comment by florine2623** [comment]
ping @PrestaShop/prestashop-core-developers ,

Is that the normal bahavior ?
Thanks!

**Comment by SharakPL** [comment]
Thanks @florine2623

**Comment by atomiix** [comment]
@florine2623 this is not the expected behavior, we need to fix that!

**Comment by SharakPL** [comment]
I think it comes from Modules section or directly from Addons Marketplace. Whenever I try to install new module a `pro_` folder is being created in *var/cache*. First file there is **annotations.map**
