### ISSUE TITLE
Mail Alert 2.2.1 duplicate mail for new order

### ISSUE THREAD

**Issue by bmwjoeytsang** [PrestaShop/PrestaShop#26928]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

we are using PS1.7.3 and just upgraded MailAlert to 2.2.1. Before upgraded to 2.2.1, there was no issue on this.

Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.0.33

After upgraded, we found that when have new order received, the new order notification will send duplicate email. I had tried to reset the mailalert module but still same. I checked in the advanced setting > mail, only new order will have duplicate problem. order_conf and payment mail only send one times per order without problem.

Can anyone help to solve this issues? Thanks!

 

Regards

### Steps to reproduce

1. upgrade mailalert module from 2.0.1 to 2.2.1
2. reset modules
3. customer make a new order
4. we will get duplicate new order notification mail on each order.

### PrestaShop version(s) where the bug happened

1.7.3

### PHP version(s) where the bug happened

7.0.33

### If your bug is related to a module, specify its name and its version

ps_mailalert 2.2.1

**Comment by florine2623** [comment]
Hello @bmwjoeytsang ,

I can't reproduce your issue.
I received only 2 emails when an order is created :
- order confirmation
- waiting for payment
<img width="368" alt="Screenshot 2021-12-09 at 09 51 59" src="https://user-images.githubusercontent.com/16019289/145364374-c38294bf-e40c-420b-9722-f5f6703f6aef.png">

Can you make sure you have no override ?
Thanks!

**Comment by bmwjoeytsang** [comment]
I mean merchant will receive duplicate notification, not customer side

I also tried edit the ps_mailalert and hard code the $merchant to ‘Joey@chungyuen.com.hk’, it still will send two new order notification to joey! It seem the program will run two times when have new order

**Comment by bmwjoeytsang** [comment]
Hi! I tried lot of thing to try found out the problem but still cannot solve this duplicate New Order notification to Merchant issue.

0. Clear server cache and changed the setting to force compilation, disable all cache function, not work
1. Tried uninstall the mail alert module and removed the whole folder and reinstall 2.01 / 2.2.1, not work
2. Tried hard code the $merchant_mail to $merchant_mail='xxx@xxxx.com' in ps_mailalerts.php, not work 
3. Tried removed the folder /themes/ZoneTheme/modules/ps_emailalert to ensure there is no override files, not work
4. Tried changed the theme back to Default theme, not work
5. Tried delete all language and only keep one chinese TW language, not work

**Comment by florine2623** [comment]
I can't reproduce your issue. For one order, I have only 1 email sent to the merchant and 3 emails sent to the customer.
<img width="376" alt="Screenshot 2021-12-13 at 10 29 31" src="https://user-images.githubusercontent.com/16019289/145786811-20d027e8-5f9a-43d3-a598-128a793ce7f5.png">
It doesn't duplicate the emails.

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

I'll close your issue as it is not reproducible.
Thank you
