### ISSUE TITLE
Information page is slow

### ISSUE THREAD

**Issue by unlocomqx** [PrestaShop/PrestaShop#26927]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The Information page takes more than 10 seconds to load

<img width="685" alt="2021-12-08 at 11 38 PM" src="https://user-images.githubusercontent.com/793712/145302630-a92faeb4-73d8-45e7-a71a-0ba32988eb76.png">

Can you check if you can reproduce?

As far as my checks go, the system requirements check is what's slowing things down.

<img width="513" alt="2021-12-08 at 11 39 PM" src="https://user-images.githubusercontent.com/793712/145302790-32c1531f-e288-4e71-a69a-863f31026043.png">

If you can repro, I can submit a PR to lazy load the requirements check (similar to the files check)

### Steps to reproduce

1. Visit the Advanced Parameters > Informations page
2. Check the timing in the devtools (Network tab)

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by florine2623** [comment]
Hello @unlocomqx ,

I can't reproduce your issue on branch develop. Please check my screen record : https://watch.screencastify.com/v/dzCAl11t7dM6Et8EMhnj 

Could you check this comment : https://github.com/PrestaShop/PrestaShop/issues/20202#issuecomment-662118500 ?

Thanks!

**Comment by matks** [comment]
@unlocomqx this is likely to depend on system settings :/

**Comment by unlocomqx** [comment]
@florine2623 Thank you for taking the time to check this
I also checked the PrestaShop demo and it works fast as well.

I do after-sales and connect to many customers BOs and noticed that the Information page is slow everytime.
I will make further checks and see what's causing it on my part.
I'll close this for now as it's not consistently reproducible.

Thanks again

**Comment by unlocomqx** [comment]
I figured out why it's not always reproducible. 
What's causing the slowdown is not server configuration but the amount of files in the shop (due to recursive file checks)
In this case, the modules and cache folder.

Time in seconds for each test:

<img width="503" alt="2021-12-09 at 10 22 AM" src="https://user-images.githubusercontent.com/793712/145369357-f6529bd6-77c3-4c59-9853-c0a078581ce9.png">

Here's a test with just the native modules
<img width="270" alt="2021-12-09 at 10 36 AM" src="https://user-images.githubusercontent.com/793712/145371396-beeda7b3-2ca4-4522-865d-52df899e6160.png">

That's why it works fast for a new shop but slow for a production shop that has many extra modules and many more files in cache.
It gets worse especially with modules that ship with a vendor folder which usually contains a huge number of files.

I can submit a PR to "lazy load" the requirements check if you can reproduce on another shop that has more modules

**Comment by hibatallahAouadni** [comment]
Hello @unlocomqx 

It seems what you proposed is a an improvement, wdyt? should we change this issue to an improvement?
Please check and feedback.

Thanks!

**Comment by unlocomqx** [comment]
Yes, in the issue creation, I had to pick between bug and feature.
Improvement works better for this one.
Thank you

**Comment by matks** [comment]
Thanks for exploring this matter @unlocomqx 

> I can submit a PR to "lazy load" the requirements check if you can reproduce on another shop that has more modules

What do you plan to do ? Only explore the modules and vendor folders on ajax query?

**Comment by unlocomqx** [comment]
It will be similar to how the modified file checks are made
<img width="379" alt="2021-12-10 at 10 28 AM" src="https://user-images.githubusercontent.com/793712/145550857-e7045200-3e69-44cb-b42f-342fe449b3ff.png">

My solution for now, is to defer the whole requirements check task not just the modules/cache folders.

I extracted the requirements check to another call 
```php
public function displayCheckRequirementsAction()
{
    return $this->render(
        '@PrestaShop/Admin/Configure/AdvancedParameters/SystemInformation/system_requirement.html.twig',
        [
            'requirements' => $this->getRequirementsChecker()->getSummary()
        ]
    );
}
```

**Comment by unlocomqx** [comment]
Hi, should I submit a PR and then you can validate it? Wdyt?
Thanks
