### ISSUE TITLE
Tabs missing translations after upgrade

### ISSUE THREAD

**Issue by Prestaworks** [PrestaShop/PrestaShop#26933]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After upgrading a shop to the new 1.7.8.0, the tabs (menu) is in english.
This is because wording and wording_domain is missing values for the old tabs.

### Expected behavior

Tabs should be in local language.

### Steps to reproduce

1. Install Prestashop 1.6
2. Upgrade to 1.7.8.0+

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

autoupgrade 4.13.0

**Comment by Prestaworks** [comment]
PR for this is located here
https://github.com/PrestaShop/autoupgrade/pull/439

**Comment by hibatallahAouadni** [comment]
Hello @Prestaworks 

Did you encounter an exception on the Dashboard page? Or just you have some missing translations?
Cause it seems your issue similar to this one #26891
Please check and feedback.

Thanks!

**Comment by Prestaworks** [comment]
> Hello @Prestaworks
> 
> Did you encounter an exception on the Dashboard page? Or just you have some missing translations? Cause it seems your issue similar to this one #26891 Please check and feedback.
> 
> Thanks!

I got missing translations only, all the menu options where in english, but other than that, it was all working fine.

**Comment by HanaRebaiQA** [comment]
Hello @Prestaworks 

Thanks for reporting this issue.
I did manage to reproduce the issue after doing the upgrade **1.6.1.24 to 1.7.8.2** and when updating the language on : 
`International > Add / Update a language > Click on Add or update a language `
![image](https://user-images.githubusercontent.com/92912932/145566965-3f75f292-9d5a-4d54-9a44-f2eac0e18059.png)

But, it works fine after upgrade **1.6.1.24 to 1.7.7.8**. So, **it's a regression**.
![image](https://user-images.githubusercontent.com/92912932/145567041-5c693499-d71c-4613-bd67-bef73251ba8a.png)

I’ll add this to the debug backlog so that it’s fixed. 

Thank you!

**Comment by HanaRebaiQA** [comment]
This issue is not fixed on the release 4.14.0

**Comment by eternoendless** [comment]
Note that Tabs are translatable entities. Like any other translatable content, the translated content is stored in the database in `ps_tab_lang`. We use wording and wordin_domain as basis for auto-translating the tabs whenever a new language is installed.

This means that if tabs are already stored untranslated in `ps_tab_lang`, no amount of upgrading will fix that: you need to trigger the auto-translation process, for example by removing/reinstalling the language. I think that updating the language or modifying one of the Admin.Navigation.Menu translations using the BO interface will also trigger the auto-translation process (I don't remember).

In the future, we should probably get rid of `ps_tab_lang` altogether and use wording and wording_domain exclusively.

**Comment by kpodemski** [comment]
@eternoendless it's good enough just to use add/update language option and select already installed language. It's a common practice to do it after every 1.6 to 1.7 update

**Comment by eternoendless** [comment]
Thanks for the confirmation Krystian

**Comment by hibatallahAouadni** [comment]
@eternoendless What's the status of this issue?

**Comment by eternoendless** [comment]
@hibatallahAouadni IMO it's been fixed.

**Comment by hibatallahAouadni** [comment]
Great then :tada: and I have checked with @khouloudbelguith that's the issue has been fixed with the new release 1.7.8.3
Closing the issue!
