### ISSUE TITLE
Missing behavior and wording on security page (Refacto of the grid)

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#26935]
### Is your feature request related to a problem?
On security page, it's not possible to change wordings for just one grid (in a proper way), a refactoring has to be done in order to allow that. 

### Describe the solution you'd like
Missing wording on the Security page

**Bulk delete:**

- **Title:** Delete selected sessions?
- **Body message:** Users will be signed out from all selected sessions.
- Exit buttons: Cancel/Delete

**Delete 1 session:**

- **Title:** Delete session?
- **Body message:** The user will be signed out from this session.
- Cancel/Delete

**Specs:**
https://github.com/PrestaShop/prestashop-specs/pull/264

_Originally posted by @PierreRambaud in https://github.com/PrestaShop/PrestaShop/issues/21120#issuecomment-989758340_

**Comment by hibatallahAouadni** [comment]
@MatShir is this issue realetd to this one #20084? if so, in which EPIC should I put it?

**Comment by MatShir** [comment]
No epic needed ;) The issue would be addressed when this PR will be merged #20084 ?

**Comment by Progi1984** [comment]
@MatShir I put the issue in the backlog as (the work of @PierreRambaud) #20084 has been merged.
