### ISSUE TITLE
Experimental page combination table row border styling issue

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#26937]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

first row of combination table in experimental product page seems misaligned. Probably due to some extra border on head column or so.. See screenshot
![Screenshot from 2021-12-09 16-52-40](https://user-images.githubusercontent.com/31609858/145419294-4657f9c6-e0d6-4343-8e9d-9a48e70b77e3.png)

### Expected behavior

row borders should be aligned in a straight line.

### Steps to reproduce

1. Turn on experimental product page.
2.  Go to any combinational product, combinations tab
3. See the issue in list

### PrestaShop version(s) where the bug happened

develop

**Comment by hibatallahAouadni** [comment]
Hello @zuk3975 

Thanks for reporting the issue!
I reproduce the issue with PS1782, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/145449607-615f9200-66c7-4750-bc9d-d75b800da087.png)

I’ll add this to the debug backlog so that it’s fixed.

Thank you
