### ISSUE TITLE
Error 500 with Tiktok for Business

### ISSUE THREAD

**Issue by jmrftrs** [PrestaShop/PrestaShop#26939]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After installing TikTok for Business I get this error while entering in an article. Not when entering in a category

```
AH01071: Got error 'PHP message: 
PHP Fatal error: Uncaught TypeError: Argument 3 passed to HookCore::callHookOn() must be of the type array, null given, called in ***/httpdocs/classes/Hook.php on line 934 and defined in ***/httpdocs/classes/Hook.php:412\nStack trace:\n
#0 ***/httpdocs/classes/Hook.php(934): HookCore::callHookOn(Object(Tiktokforbusiness), 'filterProductCo...', NULL)\n
#1 ***/httpdocs/controllers/front/ProductController.php(384): HookCore::exec('filterProductCo...', NULL, NULL, false, true, false, NULL, true)\n#2 ***/httpdocs/classes/controller/Controller.php(306): ProductControllerCore->initContent()\n
#3 ***/httpdocs/classes/Dispatcher.php(518): ControllerCore->run()\n
#4 ***/httpdocs/index.php(28): DispatcherCore->dispatch()\n#5 {main}\n thrown in ***/httpdocs/classes/Hook.php on line 412\n
```

What can I do?

### Expected behavior

Just work fine, or at least don't crash website

### Steps to reproduce

1. Install TikTok for Business
2. Activate
3. Navigate o configure and navigate
4. error 500

### PrestaShop version(s) where the bug happened

1.7.8

### PHP version(s) where the bug happened

7.2 and 7.3

### If your bug is related to a module, specify its name and its version

tiktokforbusiness

**Comment by hibatallahAouadni** [comment]
Hello @jmrftrs 

It seems that your issue is not a PrestaShop core bug.
If your module is Tiktok Official, please contact support team on [Addons](https://addons.prestashop.com/en/sea-paid-advertising-affiliation-platforms/85637-tiktok-for-business.html)

We will close this issue.

Thanks!
