### ISSUE TITLE
PS 1.7.8.2 broken link to images after upgrade to PHP 7.4

### ISSUE THREAD

**Issue by Peter4661** [PrestaShop/PrestaShop#26930]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

[PHP 74_ broken image links.pdf](https://github.com/PrestaShop/PrestaShop/files/7684057/PHP.74_.broken.image.links.pdf)

After upgrade to PS 1.7.8.2 we also upgrade to PHP 7.4. After this some, most recent published images, links to images were broken. Downgrading to PHP 7.3 solved the issue.

Observation:   Under PHP 7.4, the site ran over HTTP/2,   under PHP 7.3, site runs HTTP 1.1

### Expected behavior

Under PHP 7.4 images would show as under PHP 7.3

### Steps to reproduce

Under server settings, i.e. direct admin in our case, select PHP 7.4. 
Revert to PHP 7.3 to solve the issue

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @Peter4661 

Did you try to re-generate the images to solve the issue before downgrading to PHP7.4?
Please check and feedback.

Thanks!

**Comment by Peter4661** [comment]
Yes, we tried to regenerate images. The messages was, original images not found. 

Have a nice weekend.

**Comment by hibatallahAouadni** [comment]
Hello @Peter4661 

Could you please provide the previous version PS before upgrading.
Please check and feedback.

Thanks!

**Comment by Peter4661** [comment]
Heya @ Hibatallah Aouadni 

We upgraded from PS 1.7.8.1 / PHP build 7.3  ( no missing images) to 1.7.8.2 / PHP 7.4 (missing images)

We can reproduce the problem. 

- Re-tried to regenerate images under PS 1.7.8.2 / PHP 7.3 (no missing images)
- Switched to PHP 7.4  on the same refreshed page (missing images).   see results on attachments.

Site is now running under PHP 7.3 HTTP/1.1,  lacking HTTP/2 , HTTP/3 support

[images_PHP_73.pdf](https://github.com/PrestaShop/PrestaShop/files/7687370/images_PHP_73.pdf)
[images_PHP_74.pdf](https://github.com/PrestaShop/PrestaShop/files/7687375/images_PHP_74.pdf)

**Comment by hibatallahAouadni** [comment]
Hello @Peter4661 

I didn't manage to reproduce the issue following these steps:

1. Install 1.7.8.1 (PHP 7.3)
2. Create a product (upload an image)
3. Install 1-click upgrade v4.13.0
4. Upgrade to 1.7.8.2
5. Upgrade PHP version to 7.4
6. Check FO
7. No error > all images are well displayed (even the new created product)

Thanks to @SD1982 for helping in this issue :superhero: 
Please check and feedback.

Thanks!

**Comment by Peter4661** [comment]
Heya   @SD1982 and  @ Hibatallah Aouadni,

Thank you for testing the procedure which did not work on our server.  As shown in my previous note, we had multiple image errors under PS 1.7.8.2 after switching from PHP 7.3 to PHP 7.4. 

We ran other test, regenerate images under PHP 7.4. ( pagecache and smarty cache disabled) . Server took hours to complete the task. But...  all images are well displayed now.

Thank you for your help.

**Comment by Peter4661** [comment]
This looks wierd to me.

The regeneration of images was done with the shop in maintenance mode.  After we cleared cache, pagecache and activated the shop, all images are missing

**Comment by Peter4661** [comment]
Problem found, conflict with cache module which also supports lazy load images. 

Although the module reports, lazy load is being disabled, after uninstalling the module, all images are well displayed.

Thanks again for your help.

**Comment by hibatallahAouadni** [comment]
@Peter4661 Glad to hear that you solved your issue :tada:
