### ISSUE TITLE
After fresh install - some folders of archived modules referralprogram and  ps_reminder still exists

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#26943]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The modules `referralprogram` and  `ps_reminder` are archived from 1.7
After a fresh install => the folders of those modules are displayed and contain only the `mails` folder.

### Steps to reproduce

1. Fresh install
2. In the folder /PrestaShop_folder/modules/ check that the folders `referralprogram` and  `ps_reminder` are displayed 

![image](https://user-images.githubusercontent.com/16067358/145567209-73c0a276-a2ef-43ed-83d5-b0c624491e22.png)

### PrestaShop version(s) where the bug happened

1.7.7.8, 1.7.8.x, develop

### PHP version(s) where the bug happened

7.3

**Comment by Progi1984** [comment]
@khouloudbelguith Could you check this on a `develop` branch with an empy `modules` directory ?

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I tried again with the develop branch fresh install
I found that the folders `referralprogram` and `ps_reminder` are displayed.
![image](https://user-images.githubusercontent.com/16067358/152523363-4ba98a6a-9ab7-4e8c-bf3d-8686a8c50a71.png)

I attached a screen record

https://user-images.githubusercontent.com/16067358/152522919-2a82b764-013e-4152-bb82-50aba8dc9482.mp4

Thanks!

**Comment by florine2623** [comment]
This issue is fixed in PS 9.0.0.

Folders for modules `referralprogram` and `ps_reminder` are not there anymore.

<img width="590" alt="Image" src="https://github.com/user-attachments/assets/ed40ff8d-6356-423d-a76d-33685dc75335" />
