### ISSUE TITLE
 Remove the delay when hover out of the top_sub_menu on ps_mainmenu module

### ISSUE THREAD

**Issue by Keuta** [PrestaShop/PrestaShop#26941]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Hi everyone.
I'm a bit confused that I can't find why the mainmenu come's back when you hover out and quick come back in the zone where was the top_sub_menu div that just disapeared

### Describe the solution you'd like

I would like to know where i can't erase the delay of about half a second while the sub_menu comes back..
Thanks everybody for any help.

**Comment by HanaRebaiQA** [comment]
Hello 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you
