### ISSUE TITLE
Customer is able to see order detail page via link even order share is disabled in multishop

### ISSUE THREAD

**Issue by Amit-Kumar-Tiwari-Webkul** [PrestaShop/PrestaShop#26953]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

- Multishop is enabled, Suppose, there are two shops Shop A and Shop B with the same shop group SG-A
- Share customer enabled for shop group SG-A and order share is disabled.
- Now if a customer places an order from Shop A and login into Shop B then no order is visible because order share is disabled.
- But if customer open that order via the link then it is visible
- Order must not be visible on another shop if order share is disabled.
### Shop A
Orders page: https://nimb.ws/hPLHgV
Order Detail page https://nimb.ws/U9JVd6  (URL: http://localhost/ps1780/ShopA/en/index.php?controller=order-detail&id_order=20)
### Shop B
Orders page: https://nimb.ws/j85mZ6
Order Detail page https://nimb.ws/nSmuBp  (URL: http://localhost/ps1780/ShopB/en/index.php?controller=order-detail&id_order=20)
- Hence on ShopB Customer must not be able to see details.

### Steps to reproduce

- Multishop is enabled, Suppose, there are two shops Shop A and Shop B with the same shop group SG-A
- Share customer enabled for shop group SG-A and order share is disabled.
- Now if a customer places an order from Shop A and login into Shop B then no order is visible because order share is disabled.
- But if customer open that order via the link then it is visible
- Order must not be visible on another shop if order share is disabled.
### Shop A
Orders page: https://nimb.ws/hPLHgV
Order Detail page https://nimb.ws/U9JVd6  (URL: http://localhost/ps1780/ShopA/en/index.php?controller=order-detail&id_order=20)
### Shop B
Orders page: https://nimb.ws/j85mZ6
Order Detail page https://nimb.ws/nSmuBp  (URL: http://localhost/ps1780/ShopB/en/index.php?controller=order-detail&id_order=20)
- Hence on ShopB Customer must not be able to see details.

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.3.0

**Comment by matks** [comment]
> Now if a customer places an order from Shop A and login into Shop B then no order is visible because order share is disabled.

I understand why you consider this is wrong, but we need to verify exactly what is the expected behavior of "Order Share" feature.

Because it might be useful to access the order details with the URL for guests for example. So maybe this behavior is expected.

We'll need Product Team to tell us I guess.

**Comment by florine2623** [comment]
Hello @Amit-Kumar-Tiwari-Webkul ,

I have the same behavior in PS 1.7.8.x. 
I will ping product team to make sure this is the wanted behavior.

Please stay tuned !
