### ISSUE TITLE
Error on runing upgrade.php when upgrading form 1.7.7.3 to 1.7.8.1

### ISSUE THREAD

**Issue by babyewok** [PrestaShop/PrestaShop#26962]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I had issues with the 1-click upgrade just stopping at the unzipping stage, so decided to go for a manual upgrade.  

I currently run version 1.7.7.3 and the server has been upgraded to php 7.4 (7.3 is no longer available to me), so since the site is not yet live thought it best to upgrade to 1.7.8.1 which is compatible with php 7.4.

I turned off the cache and emptied it, put the site into maintenance mode and uploaded all the new version files.  The problem was when I went to run upgrade.php.  I initially got this error:

**error on line 215 at column 1: Extra content at the end of the document**

(unfortunately I didn't copy the rest of the info at the time before refreshing the page and getting a 500 error).  I cleared the cache and could get into the back office and it reported to be running version 1.7.8.1, but obviously I cannot be sure that all the updates were made to the database.

I really need to get this upgraded so I can be sure the site is compatible with php7.4 before going live.  I don't want to have to start from scratch with a clean install as I have done a fair bit of setting up already.  I posted on the forums, but pretty much just got a chorus of "don't bother upgrading, it always goes wrong!", which obviously isn't very helpful!

### Expected behavior

Upgrade to complete or at least give an error code so that I could identify the problem more easily.

### Steps to reproduce

1. Put shop into maintenance mode
2. Turn off cache
3. Clear cache
4. Upload new version files as expected
5. Run /install/upgrade/upgrade.php

### PrestaShop version(s) where the bug happened

1.7.7.3 and 1.7.8.1

### PHP version(s) where the bug happened

7.4

**Comment by babyewok** [comment]
OK, I have found the upgrade log that may help identify the issue

[20211203_upgrade.log](https://github.com/PrestaShop/PrestaShop/files/7703010/20211203_upgrade.log)

**Comment by hibatallahAouadni** [comment]
Hello @babyewok 

> I currently run version 1.7.7.3 and the server has been upgraded to php 7.4 (7.3 is no longer available to me), so since the site is not yet live thought it best to upgrade to 1.7.8.1 which is compatible with php 7.4.

Well, you should upgrade your shop before upgrading the PHP version :disappointed: 
Could you please check this issue #25671 it seems related to yours.
Please check and feedback.

Thanks!

**Comment by babyewok** [comment]
OK, well I set up the shop on a local test server where I have php7.3 in a last attempt to upgrade rathe than go with a fresh install.  This time I got a 500 error on running upgrade.php with this error in the error log:

`[Fri Dec 17 14:17:26.694681 2021] [php7:error] [pid 15928:tid 2100] [client ::1:50813] PHP Fatal error:  Uncaught Symfony\\Component\\Intl\\Exception\\MethodNotImplementedException: The Symfony\\Component\\Intl\\Locale\\Locale::setDefault() is not implemented. Please install the "intl" extension for full localization capabilities. in C:\\UniServerZ\\www\\localhost\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Intl\\Locale\\Locale.php:318\nStack trace:\n#0 C:\\UniServerZ\\www\\localhost\\classes\\Language.php(1789): Symfony\\Component\\Intl\\Locale\\Locale::setDefault('en-GB')\n#1 C:\\UniServerZ\\www\\localhost\\classes\\Language.php(1603): LanguageCore->getCountries('en-GB')\n#2 C:\\UniServerZ\\www\\localhost\\classes\\Language.php(1576): LanguageCore::updateMultilangFromCldr(Object(Language))\n#3 C:\\UniServerZ\\www\\localhost\\classes\\Language.php(1552): LanguageCore::updateMultilangTables(Object(Language), Array)\n#4 C:\\UniServerZ\\www\\localhost\\src\\PrestaShopBundle\\Install\\Upgrade.php(737): LanguageCore::updateMultilangTable('gb')\n#5 C:\\UniServerZ\\www\\localhost\\src\\PrestaShopBundle\\Install\\Upgrade.php(838): PrestaSho in C:\\UniServerZ\\www\\localhost\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Intl\\Locale\\Locale.php on line 318`


Any ideas what the problem is now?

**Comment by hibatallahAouadni** [comment]
Hello @babyewok 

It seems you have a missing extension not installed: `"intl" extension`
You need to install it and enable it in `php.ini`. Then, restart `apache` :wink: 

Please check and feedback. Closing this issue as it's not Core bug.

PS: even when the issue is closed, we can continue our discussion till you solve your issue :wink: 

Thanks!

**Comment by babyewok** [comment]
Hey, so I enabled the intl extension, reinstated the backed-up 1.7.7.3 database and now get this on running upgrade.php 

This page contains the following errors:
error on line 215 at column 1: Extra content at the end of the document
Below is a rendering of the page up to the first error.

I can't copy and paste the rest so have attached a screenshot

😢 😢 😢 😢 losing the will....
![wolf-localhost-install-upgrade-upgrade-php](https://user-images.githubusercontent.com/952225/148534999-9541254c-72fc-4072-84cc-fb02db6cfbc0.png)
.

**Comment by babyewok** [comment]
Well, with the shop set up on php 7.3 on my test server I decided to try the 1-click update again..... and it worked!  Yay!  Wish I had just tried that again first time round rather than assuming it was a lost cause.

**Comment by hibatallahAouadni** [comment]
@babyewok Glad that your problem is solved :tada:
