### ISSUE TITLE
The min compliancy could not be set as 8.0.0 for a module

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#26968]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The min compliancy of a module could not be set as 8.0.0 (regarding SemVer) or it will break the install.
Set is as "8" will be okay, as now.

### Expected behavior

Allow the use of 8.0.0 as min_compliancy.

### Steps to reproduce

1. Use develop branch
2. Set a new module with min_compliancy as 8.0.0
3. Try to install

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

Could you please provide a test module to help me reproducing the issue. And if you could provide a screenshot or a screen record, it will be perfect :pray: 
Waiting for your feedback.

Thanks!

**Comment by PrestaEdit** [comment]
Hi @hibatallahAouadni ,

And here is: [
[testmodule.zip](https://github.com/PrestaShop/PrestaShop/files/7705922/testmodule.zip)
](url)

**Comment by florine2623** [comment]
Hello @PrestaEdit ,

Thanks, but sorry I can't upload the module on develop branch, I have an error : 
<img width="675" alt="Screenshot 2021-12-14 at 16 35 05" src="https://user-images.githubusercontent.com/16019289/146029348-75815657-972d-4c99-b9af-cda109aef5fb.png">

Thanks!

**Comment by PrestaEdit** [comment]
It's the goal, to have an issue on the install, with this. :D

**Comment by PrestaEdit** [comment]
Check the "What happened" and see that it will say that the version doesn't match.

**Comment by florine2623** [comment]
Oh sorry ^^
Ok, the error is the following : 
<img width="616" alt="Screenshot 2021-12-14 at 17 41 10" src="https://user-images.githubusercontent.com/16019289/146040982-6ee76a79-089d-4fc8-8180-a12b0bb136c8.png">

Indeed it doesn't match. I will ping the dev team to have their insights on this :)
Please stay tuned!

**Comment by florine2623** [comment]
ping @PrestaShop/prestashop-core-developers ,

What should be done about the min compliancy of a module ?
Thanks!

**Comment by matks** [comment]
> ping @PrestaShop/prestashop-core-developers ,
> 
> What should be done about the min compliancy of a module ? Thanks!

It's a bug, it must be fixed so that's it's possible 👍

**Comment by atomiix** [comment]
By investigating a little, the issue comes from the fact that when we define a min (or max) version compliancy with less than 4 digits, we automatically add the "missing" ones. So, 8.0.0 becomes 8.0.0.0 which is > to 8.0.0.
I think we did that so we could set `7.0.0` as min version and it would be interpreted as `1.7.0.0`.

**Comment by atomiix** [comment]
@PrestaEdit I just made a PR that solves it. In the meanwhile you should be able to make it work by calling `parent::__construct()` right **before** declaring the `ps_versions_compliancy` property.
