### ISSUE TITLE
BO - An error message is displayed when configure a new shop with blockreassurance module v5.0.0 - Multistore

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#26979]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When chonfigure a new shop, in the Customer Reassurance module, an error message is displayed in every manipulation with multistore (Change the new shop, Add a new icon, add a new image)
![image](https://user-images.githubusercontent.com/92912932/146007381-b03b22c5-2ceb-4cbf-b8e7-d096c35c7e4f.png)

See the detailed screen-record below : 
https://watch.screencastify.com/v/RhJAETCnRon5gKiU2fgY

### Expected behavior

No error message is displayed when configuring the new shop.

### Steps to reproduce

1. Enable multistore>create a new shop
2. BO>Modules>Module manager>search for blockreassurance module
2. Click on configure of module
3. Change the new shop configured 
4. See Error > An error message is displayed
5. Add a new icon / a new image 
6. See Error > An error message is displayed

### PrestaShop version(s) where the bug happened

1.7.7.8 & 1.7.8.x

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

Customer reassurance module v5.0.0

**Comment by Progi1984** [comment]
Fixed by @atomiix in PrestaShop/blockreassurance#336 & Tested by @HanaRebaiQA
