### ISSUE TITLE
FO - The content block of Customer reassurance module v 5.1.0 is not displayed in the correct place with Above footer

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#26976]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When check `Above footer` for the Customer reassurance module when using Customer reassurance module v 5.1.0 (**dev branch**), the block content is displayed below the newsletter block.
See the different screen-record & screen-shot below : 
https://watch.screencastify.com/v/94y2KXALyNHCeb8HWabl
![image](https://user-images.githubusercontent.com/92912932/145982744-8dce9336-6d6b-42c5-9a98-efddb7eb9117.png)

### Expected behavior

The block content of Customer reassurance **v 5.1.0 (dev branch)** module must be displayed in the correct place (Under the newsletter block) when check `Above footer` like for Customer reassurance module v 5.0.0
![image](https://user-images.githubusercontent.com/92912932/145984116-fb762af1-f177-4bb9-bd5e-daa5cf375d2f.png)

### Steps to reproduce

1. BO > Modules > Search for Customer reassurance module (blockreassurance)
2. Uninstall the module v5.0.0
3. Install the blockreassurance module **v5.1.0** from git > **dev branch** (with git clone)
4. Under modules folder > Run the following 
```
git clone git@github.com:PrestaShop/blockreassurance.git
cd blockreassurance
composer install
```
5. BO > Modules > install blockreassurance v5.1.0
6. Click on Configure
7. Check Above footer 
8. Click on See my shop 
9. FO > scroll down in the page
10. See error > the content block is displayed below the newsletter block

### PrestaShop version(s) where the bug happened

1.7.8.x

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

Customer reassurance module v5.1.0 (dev branch)

**Comment by ghost** [comment]
This is not a regression but the normal functioning of PrestaShop.
You can change this in the module position section
You can try with all versions if you uninstall a module it loses its position

**Comment by HanaRebaiQA** [comment]
Hello @okom3pom,

Thank you!
My issue is duplicated of https://github.com/PrestaShop/PrestaShop/issues/20748

**Comment by HanaRebaiQA** [comment]
Duplicate of #20748
