### ISSUE TITLE
Native modules PS 1.7 should uninstall equivalent PS 1.6 module on register

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#26973]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

Some native modules of PS 1.6 were reconstructed for PS 1.7. But it can happen that, upon upgrade, a shop will have both the 1.6 and 1.7 versions of a same module (because their name are different). This can be a source of errors.

@Quetzacoalt91 started a large project of making sure all native modules PS 1.7 should uninstall equivalent PS 1.6 module on register. Most PRs were merged successfully but some did fail at QA point. QA team found issues that need to be explored and solved for this project to be complete.

The PRs from @Quetzacoalt91 have been waiting for more than a year now because it's not a priority anymore. In order to clean our open PRs backlog I will list all the PRs here so we do not lose the list.

## Pull Requests list

- https://github.com/PrestaShop/ps_brandlist/pull/5
- https://github.com/PrestaShop/ps_contactinfo/pull/12
- https://github.com/PrestaShop/ps_checkpayment/pull/22
- https://github.com/PrestaShop/ps_featuredproducts/pull/19
- https://github.com/PrestaShop/ps_imageslider/pull/43
- https://github.com/PrestaShop/ps_crossselling/pull/4
- https://github.com/PrestaShop/ps_bestsellers/pull/12
- https://github.com/PrestaShop/ps_cashondelivery/pull/30
- https://github.com/PrestaShop/ps_viewedproduct/pull/16
- https://github.com/PrestaShop/ps_wirepayment/pull/41
- https://github.com/PrestaShop/ps_categoryproducts/pull/20
- https://github.com/PrestaShop/ps_specials/pull/1
- https://github.com/PrestaShop/ps_newproducts/pull/1
- https://github.com/PrestaShop/ps_currencyselector/pull/10
- https://github.com/PrestaShop/ps_socialfollow/pull/14
- https://github.com/PrestaShop/ps_customeraccountlinks/pull/19

**Comment by Quetzacoalt91** [comment]
Sorry I couldn't find the time to go on these PRs :pray:

**Comment by matks** [comment]
> Sorry I couldn't find the time to go on these PRs 🙏

We know you're very very busy and you did an amazing job. Leave us this one 😄  .

If we cant do it, maybe we can ask @tomlev :trollface:
