### ISSUE TITLE
FO - An Exception is generated when adding a new image in Customer reassurance module with multistore

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#26980]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When configuring a new shop, then adding a new image as a block content, an exception is generated.
![image](https://user-images.githubusercontent.com/92912932/146009189-6ac4b644-3915-4349-93a3-401c58987c2d.png)

See the detailed screen-records below : 
https://watch.screencastify.com/v/Ru51LcoYrtybxx5SE2oc

The exception is thrown only with the new shop configured and when adding a new image : 
https://watch.screencastify.com/v/CuE0aLgJsVa4Nn8XuCNm
https://watch.screencastify.com/v/GWAQmIquWa0cYzmEFgVS

### Expected behavior

No exception is generated when configuring a new shop and when adding a new image as a block content in the Customer reassurance module.

### Steps to reproduce

1. Enable multistore>create a new shop
2. BO>Modules>Module manager>search for blockreassurance module v5.0.0
2. Click on configure of module
3. Change the new shop configured 
4. Click on the `+` icon to add a new Block content
5. Add a new image (.jpeg)
6. Click on Save
7. Click to preview the new shop in FO
8. See Error > An exception is generated

### PrestaShop version(s) where the bug happened

1.7.7.8 & 1.7.8.x

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

Customer reassurance module v5.0.0 and dev branch

**Comment by Progi1984** [comment]
Fixed by @atomiix in PrestaShop/blockreassurance#336 & Tested by @HanaRebaiQA
