### ISSUE TITLE
PrestaShop 1.7.8 is no longer compatible with the IE browser

### ISSUE THREAD

**Issue by Angar90** [PrestaShop/PrestaShop#26988]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

PrestaShop 1.7.7 working correctly in the IE browser and console is clear:
https://i.imgur.com/j6CFZxA.png

but in PrestaShop 1.7.8 the quick view doesn't work, I also can't add product to the cart and other thing related to .js code doesn't work.
In the console I see these js errors:
https://i.imgur.com/R6GQw23.png

Probably something is broken in the core.js file.

### Steps to reproduce

1.Open PrestaShop 1.7.7 in the IE browser to see that everything is ok.
2.Open PrestaShop 1.7.8 in the IE browser to see .js errors in the console and not working elements in the default frontoffice theme.

### PrestaShop version(s) where the bug happened

1.7.8.2

**Comment by mparvazi** [comment]
Hello @Angar90

The Internet Explorer 11 desktop application will be retired and go out of support on June 15, 2022.
https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge/

The Microsoft Edge is based on Chromium, and has similar behavior as like as Chrome and Firefox.

The web developers no longer care about testing web pages for IE!

**Comment by NeOMakinG** [comment]
I feel tired of supporting something that will go out of support in 6 months

I will make an effort on 1.7.8.3 to take a look, but be prepared that it will probably be the latest release supporting IE11

**Comment by hibatallahAouadni** [comment]
Hello @Angar90 

Ping @PrestaShop/product-team could you please check this issue :pray: 
It seems the IE11 will be retired on June 15, 2022 and following [our Guidelines and coding standards](https://devdocs.prestashop.com/1.7/themes/getting-started/guidelines/#html--css--javascript):

```
Your HTML/CSS/JS code should work with at least:
Edge
Firefox 45
Chrome 29.
```
Thanks!

**Comment by NeOMakinG** [comment]
> Hello @Angar90
> 
> Ping @PrestaShop/product-team could you please check this issue 🙏 It seems the IE11 will be retired on June 15, 2022 and following [our Guidelines and coding standards](https://devdocs.prestashop.com/1.7/themes/getting-started/guidelines/#html--css--javascript):
> 
> ```
> Your HTML/CSS/JS code should work with at least:
> Edge
> Firefox 45
> Chrome 29.
> ```
> 
> Thanks!

We need to update this I think so, some of these versions are really low and not really used anymore

As we use bootstrap 4 on both BO and FO, IE11 is in his scope we should probably make an effort until it's out of support!

**Comment by mparvazi** [comment]
@NeOMakinG 

I think the problem is related to using arrow functions in `core.js`.
IE11 doesn't support arrow functions.

https://caniuse.com/arrow-functions

**Comment by NeOMakinG** [comment]
> 

It's already fixed, added some browserslist compatibilities to babel-loader so it transpile the JS into an IE11 compatible one

**Comment by NeOMakinG** [comment]
But there is a problem with the backend, looks like the add-to-cart request is fine on both IE11 and Chrome, but the result comes with an empty product, we can't find the problem :/
