### ISSUE TITLE
Returning product quantities

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#26982]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In which automatic cases in a standard Prestashop store, is it possible to restore the quantity of products? One of my clients keeps reporting that the quantities of products sold long ago can return to the state of the store and be offered to customers.

The canceled order is one such case. Are there others?

NO custom php/mysql scripts
NO automatic imports/integrations
JUST plain Prestashop

### Steps to reproduce

Its Complex

### PrestaShop version(s) where the bug happened

1.7.6.5

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment]
Hello @PrestaShark ,

I'm not sure I understand this part :  "can return to the state of the store".
Do you mean you want the quantity of the products to be 0 ?
Thanks!

**Comment by ghost** [comment]
Hi, @florine2623 
From quite long time client reports that random products that been sold from a long time and its quantity goes to "0" keeps returning with their quantities... It is even possible? In what cases?

**Comment by florine2623** [comment]
Thanks for the details.

If the products is deleted, disabled and/or have quantity 0, it will not show up. even if your customer has the link to the product.

Example : 

The product is deleted : You will have the following message : This product is no longer available.
<img width="543" alt="Screenshot 2021-12-14 at 17 39 07" src="https://user-images.githubusercontent.com/16019289/146040714-86e34123-7025-4648-9a93-d97968946c4b.png">

The product is disabled : You will be redirect to the product's category

The product have quantity 0 and "Allow ordering of out-of-stock products" is disabled : You won't be able to add it to cart

**Comment by hibatallahAouadni** [comment]
Hello @PrestaShark 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
