### ISSUE TITLE
Install modules always to PrestaShop dir (when used/installed using composer as dependency)

### ISSUE THREAD

**Issue by mvorisek** [PrestaShop/PrestaShop#26989]
### Describe the solution you'd like

when PrestaShop  is installed using composer as dependency like:

```
composer require prestashop/prestashop
```

the modules are placed into the root project directory `/modues/` instead of the `/ vendor/prestashop/prestashop/modules/` directory

**Comment by hibatallahAouadni** [comment]
Hello @mvorisek 

Thank you for your suggestion. The Developer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by mvorisek** [comment]
the following needs to be added to root-project `composer.json`:

```
    "extra": {
        "installer-disable": [
            "prestashop"
        ]
    }
```

see https://github.com/composer/installers

**Comment by hibatallahAouadni** [comment]
@mvorisek why did you close the issue?

**Comment by mvorisek** [comment]
must be solved by the composer.json config in composer root project, it is otherwise not easy to say if the root-project require the modules to be "public" (eg. not in vendor directory) or not
