### ISSUE TITLE
FO - Checkout - Payment - Exception when checking Pay by Cash on Delivery 

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#26983]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Exception in the checkout step when checking Pay by Cash on Delivery with debug profilling in config/defines.ing enabled.

![image](https://user-images.githubusercontent.com/89604350/146024401-3f617fda-4be2-4267-be60-d40627e01624.png)

### Steps to reproduce

1. Enable debug profilling in config/defines.inc
2. Go to FO create an order 
3. In the step payment check pay by cash on Delivery
4. check " I agree to the terms of service and will adhere to them unconditionally."
5. Place order
6. See exception

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3/7.2

**Comment by florine2623** [comment]
I have a different error on PS 8.1.x : 
On the order page in FO :
`http://my_shop.com/en/module/ps_cashondelivery/validation
`
`Error: parameter "idShop" is corrupted`

<img width="270" alt="Screenshot 2023-12-27 at 11 45 32" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/6ded7119-254e-4f10-b640-0eee75464e86">

**Comment by LouisAUTHIE** [comment]
This is not a bug, It is because your are in Dev mode

**Comment by LouisAUTHIE** [comment]
This issue can be closed @florine2623

**Comment by florine2623** [comment]
I can't reproduce this issue anymore on PS 9.0.0 :

<img width="1439" alt="Image" src="https://github.com/user-attachments/assets/0c99fbdf-df84-43fb-ae59-f06bc71b027d" />
