### ISSUE TITLE
ps_viewedproduct blows up the cookie size

### ISSUE THREAD

**Issue by jorunkel** [PrestaShop/PrestaShop#26996]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The module `ps_viewedproducts` stores every single product (id) that the user visited in the cookie. After about 420 viewed products the cookie size gets larger than the allowed 4096 bytes which means the the cookie is no longer working. The result is either a `Bad Request` response or a failure of submitting any form.

### Expected behavior

The module should limit the count or viewed product ids to a reasonable number. Since the block shows only n products it would be sufficient to store only that many ids in the cookie.

Here is the affected function:
https://github.com/PrestaShop/ps_viewedproduct/blob/dev/ps_viewedproduct.php#L229

### Steps to reproduce

1. Install / activate the module and add it to a block location.
2. Go to the customer frontend and visit 500 products.

### PrestaShop version(s) where the bug happened

any

### PHP version(s) where the bug happened

any

### If your bug is related to a module, specify its name and its version

ps_viewedproduct

**Comment by Hlavtox** [comment]
Yes, this happened on 1.6 after a month of our employees using the store. I opened an issue about it but it was closed for not being able to reproduce.

**Comment by jorunkel** [comment]
Let me link your issue for reference which was related to the `blockviewed` module I guess.
https://github.com/PrestaShop/PrestaShop/issues/14751

This bug is still present in the current version of `ps_viewedproduct`.

**Comment by hibatallahAouadni** [comment]
Hello @jorunkel & @Hlavtox 

All **performance** issues are considered as improvements.
So, thanks for your issue! the Developer Team will take it into consideration for future developments. 

Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by jorunkel** [comment]
Thanks for your comment. Just to make this clear: the issue is not about **performance**. If the cookie size exceeds 4096 bytes they are no longer working, resulting in Bad Request headers or failures in authentication, cart handling and so on ...

**Comment by hibatallahAouadni** [comment]
After discussing this issue with @kpodemski I changed the label to a **`Bug`**, cause it seems that when the cookie is too big, it doesn't just slow down the site but it crashes everything

**Comment by Hlavtox** [comment]
@hibatallahAouadni Its not a performance issue. The whole store stops working and users can't add anything to cart.

**Comment by matks** [comment]
Will be fixed by ps_viewedproduct 1.2.3 https://github.com/PrestaShop/ps_viewedproduct/pull/25
