### ISSUE TITLE
Call on null object from the FrontController

### ISSUE THREAD

**Issue by teratux** [PrestaShop/PrestaShop#26999]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I'm trying to develop a module for enabling a payment option in prestashop 17.  So far I've managed to get it to work with no issue, however since I started using the 1.7.8.0 version I started to notice intermittent issues when calling a callback function in the module.  This is the endpoint I'm trying to access:

`https://presta.intellifoundry.com/index.php?fc=module&module=imaxpayin7&controller=callback` 

From what I understand it should call the **callback** controller in the **imaxpayin7** module.  I'm calling this as a POST operation with other body parameters and getting a 500 internal error:

```
[Wed Dec 15 16:23:15.419661 2021] [proxy_fcgi:error] [pid 79749] [client 152.207.144.1:6385] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /usr/share/web/presta17/classes/controller/Controller.php:791\nStack trace:\n#0 /usr/share/web/presta17/classes/controller/FrontController.php(575): ControllerCore->get('prestashop.core...')\n#1 /usr/share/web/presta17/classes/controller/FrontController.php(559): FrontControllerCore->buildFrontEndObject(Array)\n#2 /usr/share/web/presta17/classes/controller/FrontController.php(590): FrontControllerCore->assignGeneralPurposeVariables()\n#3 /usr/share/web/presta17/classes/controller/ModuleFrontController.php(77): FrontControllerCore->initContent()\n#4 /usr/share/web/presta17/classes/controller/Controller.php(306): ModuleFrontControllerCore->initContent()\n#5 /usr/share/web/presta17/classes/Dispatcher.php(518): ControllerCore->run()\n#6 /usr/share/web/presta17/index.php(28): DispatcherCore->dispatch()\n#7 {main}\n  thrown in /usr/share/web/presta17/classes/controller/Controller.php on line 791'
```

This log is being produced in the apache error log, not on the site's prod.log.  I have no clue as to what might be causing this, if you can help it would be great.  I already tried clearing the cache and checking for correct folder permissions.

Thanks

### Expected behavior

When calling the POST endpoint it should return a 200 all ok result.

### Steps to reproduce

1. call the callback endpoint in the site's module:
```bash
curl --location --request POST 'http://presta.intellifoundry.com/index.php?fc=module&module=imaxpayin7&controller=callback' \
--header 'Cookie: PHPSESSID=od6nb8vj7325m65iqbmk1qh5f7' \
--form 'id="12"' \
--form 'generated_at=""' \
--form 'order_id="8CD7B191-78A4-4907-B100-3F922EB5AB55-9B3407C1-2943-42EB-92A4-025437EFB9AE"' \
--form 'order_total_items="1"' \
--form 'order_total="35.09"' \
--form 'store_data="17"' \
--form 'error_code=""' \
--form 'description=""' \
--form 'order_state="paid"' \
--form 'signature="AAAAAAAAAAAABBBBBBBBBBBBBBB"' \
--form 'signature2
="CCCCCCCCCCCCCCDDDDDDDDDDDDDD"'
```

2. receive a 500 internal error

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.4.6

### If your bug is related to a module, specify its name and its version

imaxpayin7 v. 1.30 (not public)

**Comment by hibatallahAouadni** [comment]
Hello @teratux 

It seems that your issue is not a PrestaShop core bug.
Please contact your module developer or the support team on Addons.

We will close this issue.

Thanks!

**Comment by teratux** [comment]
> Hello @teratux
> 
> It seems that your issue is not a PrestaShop core bug. Please contact your module developer or the support team on Addons.
> 
> We will close this issue.
> 
> Thanks!

Hi, why would the issue be related specifically to that module? I'm not aware that the callback ever manages to get to the module and fails along the way.  The logs don't seem to point me in that direction

**Comment by teratux** [comment]
> Hello @teratux
> 
> It seems that your issue is not a PrestaShop core bug. Please contact your module developer or the support team on Addons.
> 
> We will close this issue.
> 
> Thanks!

even more, I installed the same module in another sandbox with the PS 1.6.1.16 version and all is working ok https://presta16.intellifoundry.com

**Comment by teratux** [comment]
@hibatallahAouadni looking further into this, the error occurs when trying to load the 'prestashop.core.filter.front_end_object.main' container.  From the cli console I tried looking it up and got nothing:
```bash
localhost:/usr/share/web/presta17 # ./bin/console debug:container prestashop.core.filter.front_end_object.main
23:34:04 ERROR     [console] Error thrown while running command "debug:container 'prestashop.core.filter.front_end_object.main'". Message: "No services found that match "prestashop.core.filter.front_end_object.main"." ["exception" => Symfony\Component\Console\Exception\InvalidArgumentException { …},"command" => "debug:container 'prestashop.core.filter.front_end_object.main'","message" => "No services found that match "prestashop.core.filter.front_end_object.main"."]
                                                                                
  No services found that match "prestashop.core.filter.front_end_object.main".  
                                                                               
debug:container [--show-private] [--show-arguments] [--tag TAG] [--tags] [--parameter PARAMETER] [--parameters] [--types] [--format FORMAT] [--raw] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--id_shop [ID_SHOP]] [--id_shop_group [ID_SHOP_GROUP]] [--] <command> [<name>]
```
I tried running the command also without the module installed, and same message, do you still believe this is an issue related to the module and not the core?
