### ISSUE TITLE
FO - A bad display when we hover on the product in the featured-products list

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#26992]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the FO > featured-products list, when we hover on a product => there is a bad display
![image](https://user-images.githubusercontent.com/16067358/146160171-ed7f3391-33df-47bb-bf58-7e1b24a4adcb.png)

It was ok with PS1.7.8.2

### Expected behavior

It should be 
![image](https://user-images.githubusercontent.com/16067358/146160602-3249b6da-b5a0-430b-ad88-e64d3bff2df3.png)

### Steps to reproduce

1. Go to FO > Home page
2. In the Popular product list
3. Hover on a product with the mouse
4. See an error 

### PrestaShop version(s) where the bug happened

1.7.8.x (1.7.8.3)

### PHP version(s) where the bug happened

7.3

**Comment by Progi1984** [comment]
Fixed by @NeOMakinG in #26998 & tested by @florine2623
