### ISSUE TITLE
BO - An exception (Error 500) is generated when adding a new image in Customer reassurance module 

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#26991]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An exception (Error 500) is generated when ading a new image in Customer reassurance module v5.1.0 & v5.0.0 in develop branch.
At the first add, the alert message is successful but the image is not added as a content block. 
From the second time, the image is not added with **an exception is generated**.
![image](https://user-images.githubusercontent.com/92912932/146145466-10ea0e6a-a897-4c23-97ea-95c7c5338fcc.png)

See screen-record below : 
Develop blockreassurance dev branch :x: 
https://watch.screencastify.com/v/IIn6peR9VAGI63HQwSA6

Develop blockreassurance v5.0.0 :x: 
https://watch.screencastify.com/v/KGqoKeN7Rz4oDCtOsPfO

With PS1778 OK :heavy_check_mark: 
https://watch.screencastify.com/v/DxBIUtjdGDhlLsmRY4gh
https://watch.screencastify.com/v/LKSLssNG5rRckY1nCfoy

With PS1782 OK :heavy_check_mark: 
https://watch.screencastify.com/v/wVafvmpHTRfyyRFZazxY

### Expected behavior

The image is added successfully as a reassurance block.

### Steps to reproduce

1. BO > Modules > Search for Customer reassurance module (blockreassurance)
**Test blockreassurance with dev branch**
2. Uninstall the module v5.0.0
3. Install the blockreassurance module v5.1.0 from git > dev branch (with git clone)
4. Under modules folder > Run the following

```
git clone git@github.com:PrestaShop/blockreassurance.git
cd blockreassurance
composer install
```
5. BO > Modules > install blockreassurance v5.1.0
6. Click on Configure
7. Click on the `+` icon to add a new Block content
8. Add a new image (.jpeg)
9. Click on Save > A success message is displayed but the Image is not added as reassuranec content 
10. Click on the `+` icon to add a new Block content for the second time
11. See error > The image is not added > Exception (error 500) is generated in the console

_PS: The same with **bloackreassurance v5.0.0**_

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

blockreassurrance module v5.1.0 (dev branch) et v5.0.0

**Comment by Progi1984** [comment]
Fixed by @atomiix in PrestaShop/blockreassurance#336 & Tested by @HanaRebaiQA
