### ISSUE TITLE
Indexing not working for 10 language and more then 50 store shop

### ISSUE THREAD

**Issue by subhanshu** [PrestaShop/PrestaShop#270]
I have a website with 89 stores and 10 languages most of the products available in most of the stores. eg product 'A' may have 89*10=890 records in ps_product_lang table.

Now whenever I run a full re-index it only indexes only one store and in only one language. I even updated it to the latest version.

to me the issue seems to be with the line : 

$limit = max(1, floor($limit / $max_possibilities) \* $max_possibilities);

which always makes $limit = 1

I did tried changing this limit to 900 but this took almost a day to index 1000 products on a dedicated server.

Any Suggestions?

**Comment by marionf** [comment]
Hello, 
This issue is old, so I close it.
If you still have it on the last version (PrestaShop 1.7.4.2), please open a new one.
Regards
