### ISSUE TITLE
gtin and mpn is not required if the product is not new or the manufacturer has not assigned it a gtin

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#27003]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

gtin and mpn is not required if the product is not new or the manufacturer has not assigned it a gtin

https://support.google.com/merchants/answer/7052112

![image](https://user-images.githubusercontent.com/62474824/146288811-1bbe7976-a482-4b2a-a38c-291a7605e101.png)
![image](https://user-images.githubusercontent.com/62474824/146288821-b7d4a012-f77d-44df-a98b-669f6d7784fe.png)

### Expected behavior

make gtin and mpn option optional

### Steps to reproduce

psxgooglemarketing
![image](https://user-images.githubusercontent.com/62474824/146288851-1714543f-3bb1-41a8-b67a-5b32417d946d.png)

### PrestaShop version(s) where the bug happened

1.7.7.3

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

psxgooglemarketing

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

It seems that your issue is not a PrestaShop core bug.
If your module is GoogleMarketing Official, please contact support team on Addons (or the developer module).

We will close this issue.

Thanks!
