### ISSUE TITLE
Productcomments material icons indexed to Google heading tags

### ISSUE THREAD

**Issue by SamiSiitonen** [PrestaShop/PrestaShop#27007]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Product comments module has material icons inside headings which are then indexed to Google:
![heading-tags](https://user-images.githubusercontent.com/41159177/146348927-f03f004c-2169-47f8-9fe4-487c1202add4.png)

A few examples how they are done currently:
```
<h2>
<i class="material-icons check_circle">check_circle</i>
Report sent
</h2>

<h2>
<i class="material-icons error">error</i>
Your report cannot be sent
</h2>
```

### Expected behavior

Material icon text shouldn't be indexed.

Here's one solution: https://stackoverflow.com/questions/37281861/how-to-use-google-material-icons-as-class-instead-of-i-tag/61659184#61659184

And a possible workaround but just for Google: https://developers.google.com/search/docs/advanced/crawling/special-tags#data-nosnippet

### Steps to reproduce

1. Install productcomments module
2. Go to FO products page and view page source

### PrestaShop version(s) where the bug happened

1.7.6.9, 1.7.7.2, 1.7.7.8

### If your bug is related to a module, specify its name and its version

productcomments 4.2.0 and 5.0.0

**Comment by Hlavtox** [comment]
One of the clean solutions:

```
<div class=“d-flex”>
<i class="material-icons check_circle me-2">check_circle</i>
<h2>Report sent</h2>
</div>
```

**Comment by hibatallahAouadni** [comment]
Hello @SamiSiitonen & @Hlavtox 

Are you talking about these heading? (with PS1782)

![image](https://user-images.githubusercontent.com/23308427/146405005-8ae06947-6103-4d6d-803e-287556f0d544.png)

Ping @PrestaShop/prestashop-core-developers could you please check this issue :pray: 
Thanks!

**Comment by SamiSiitonen** [comment]
Yea those are the ones + the others on the list from my screenshot.

**Comment by mparvazi** [comment]
In FO, the material icons should be implemented with unicodes.

```
<h2>
<i class="material-icons check_circle">&#xE86C;</i>
Report sent
</h2>
```

**Comment by tswfi** [comment]
@mparvazi that works but is not that readable. I do like this method from stackoverflow: https://stackoverflow.com/questions/37281861/how-to-use-google-material-icons-as-class-instead-of-i-tag/61659184#61659184

But with a minor change to css to only affect the ones that have the data-icon attribute

```html
<span class="material-icons" data-icon="check_circle"></span>
```

```css
.material-icons[data-icon]:before { // could also be :after, not sure which is better
    content: attr(data-icon);
}
```

Keeps it readable and is just a small css change (and of course change all the html)

**Comment by hibatallahAouadni** [comment]
> Ping @PrestaShop/prestashop-core-developers could you please check this issue :pray:

@PierreRambaud friendly reminder :relaxed:

**Comment by PierreRambaud** [comment]
Why me? :thinking:

**Comment by hibatallahAouadni** [comment]
@PierreRambaud Sorry :sweat_smile: 
I meant @PrestaShop/prestashop-core-developers friendly reminder :grin:

**Comment by matks** [comment]
- this issue is valid
- in my opinion all of the above solutions are valid
