### ISSUE TITLE
BO - Positions page - selectbox are not well displayed when resizing the page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27005]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Design > Positions page > selectbox are not well displayed when resizing the page.
![image](https://user-images.githubusercontent.com/16067358/146352436-4dfd0212-624d-4d30-9e3b-1d0c0b2634bb.png)

I checked with PS1778 & PS1782 & develop => same issue

### Steps to reproduce

1. Go to BO > Design > Positions page > Click on `Display non-positionable hooks`
2. Try to resize the window 
3. See error

### PrestaShop version(s) where the bug happened

1.7.7.8, 1.7.8.2, develop

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment]
Fixed on PS 9.0.0 :

https://github.com/user-attachments/assets/b54dab0d-8df1-48d3-b82c-af3048f974a9


So I'm closing the issue ^^
