### ISSUE TITLE
The price is not recalculated in the admin panel on the product page

### ISSUE THREAD

**Issue by askurashev** [PrestaShop/PrestaShop#27013]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The problem is as follows. Taxes, tax rules and the rest is set up. However, when the tax rule is applied on the product page in the price section, the price is not recalculated. Those. if I enter in the Price without tax field, then in the Price with tax the value is simply duplicated and vice versa.
The price in the front office is correct, tax included. We get an error only in the display in the admin panel.
In the admin panel, in the list of products, the price is also the same in the column Price with tax and Price without tax.
If enable Experimental edit product page, prices have true behavior. If disable Experimental edit product page, prices behavior is wrong

### Expected behavior

The price with the applied tax rule should change when entered into one of the fields (with or without tax), but it is simply duplicated, while everything is fine in the front office.

### Steps to reproduce

1. Go to Admin panel
2. Go to Catalog > Products
3. All prices (with tax or without tax) is same
4. Go to any product page
5. Enter price in field Price tax excl. (1000, example), price duplicate to field Price tax incl. (1000), tax rule active.

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @askurashev ,

I can't reproduce your issue on PS 1.7.8.x, the price is updated along the editing process :

https://user-images.githubusercontent.com/16019289/146514680-d1ee80ec-fa85-4a1d-97e7-291b5acc9e72.mov

Can you check the configuration of your Tax rule ? 
My tax config :  
<img width="791" alt="Screenshot 2021-12-17 at 09 40 20" src="https://user-images.githubusercontent.com/16019289/146515227-0b948d95-7038-41d1-bbb0-5e581ba77fe9.png">

Thanks!

**Comment by askurashev** [comment]
Tax active, tax rule created and active.
! If enable Experimental edit product page, prices have true behavior. If disable Experimental edit product page, prices behavior is wrong. 
I enable experimental feature early. Could enabling the feature affect the product page?

**Comment by florine2623** [comment]
Even when I test with Experimental Features enabled, I can't reproduce your issue.
The price update automatically.

https://user-images.githubusercontent.com/16019289/146525131-c37e0b19-34a0-43bd-b8c5-663dd72494ff.mov

Do you have any error on the console ?

**Comment by askurashev** [comment]
I repeat, all of a sudden there were some misunderstandings.
If I enable the experimental function, then the auto-recalculation works (is displayed), if the standard edit page is not displayed. But at the same time, if I edit in either way, the correct values go to the base.
Those. auto-recalculation is done correctly, but on the standard product editing page, this recalculation is not visible.

**Comment by askurashev** [comment]
Screencast:

https://user-images.githubusercontent.com/2631167/146535111-b72967e5-7beb-497b-b35f-1779533c715d.mp4

**Comment by florine2623** [comment]
@askurashev ,

On my end, with or without Experimental Features enabled, I can't reproduce your issue. 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

I will close your issue.

Thank you
