### ISSUE TITLE
1-Click Upgrade module 

### ISSUE THREAD

**Issue by alvolk** [PrestaShop/PrestaShop#27019]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

1. There are errors in UpgradePage.php file with using double quotes in  lines :
320 
'updateInProgress' => $translator->trans('An update is currently in progress... Click "OK" to abort.', array(), $translationDomain),
...
379 
6 => $translator->trans('Cannot write settings file, please create a file named settings.inc.php in the "config" directory.', array(), $translationDomain),

2.File upgrade.js line 13   maybe need quotes 

tab: input.tab, 

          

### Steps to reproduce

1.Go to 1-Click Upgrade setting page in BackOffice

### PrestaShop version(s) where the bug happened

1.7.6.4

### PHP version(s) where the bug happened

7.1.33

### If your bug is related to a module, specify its name and its version

1-Click Upgrade

**Comment by hibatallahAouadni** [comment]
Hello @alvolk 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
