### ISSUE TITLE
Blockwishlist Prestashop 1.7.8.2. Add a product 

### ISSUE THREAD

**Issue by Sinpery99** [PrestaShop/PrestaShop#27016]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

1) I have installed Prestashop 1.7.8.2, with default theme. PHP version 7.2

2) I have installed the wish list module (v. 2.0.1)

3) When adding a product to the list and consulting it, the same product appears three times

4) It is saved in the database well, but when it lists the products it lists the same product 3 times

5) Attached demo video here: https://streamable.com/taczs4

Thanks and best regards.

### Expected behavior

I hope that only one product is saved, not the same product three times.

Thanks.

### Steps to reproduce

1) Install Prestashop 1.7.8.2

2) Install BlockWishlist v.2.0.1 from module catalog

3) Add product and consult your account

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

blockwishlist version 2.0.1

**Comment by hibatallahAouadni** [comment]
Hello @Sinpery99 

I didn't manage to reproduce the issue with PS1782 and BlockWishlist v2.0.1, see the attached screen record below:

https://www.awesomescreenshot.com/video/6521077?key=e59f6259c035b15355af541100e3e19a

Please check and feedback.
Thanks!

**Comment by Sinpery99** [comment]
I have managed to fix the problem you mentioned. I do not know exactly why it is, since I have not had time to see it more calmly.  I hope it can help whoever happens the same.

Go to file blockwishlist > src > Search > WishListProductSearchProvider.php

Look for this function and in this code add the bold line:

**$querySearch->groupBy('p.id_product');**

public function getProductsOrCount {
.
.
.
.

$querySearch->from('product', 'p');
$querySearch->join(Shop::addSqlAssociation('product', 'p'));
$querySearch->innerJoin('wishlist_product', 'wp', 'wp.`id_product` = p.`id_product`');
$querySearch->leftJoin('category_product', 'cp', 'p.id_product = cp.id_product AND cp.id_category = product_shop.id_category_default');
**$querySearch->groupBy('p.id_product');**

}

**Comment by hibatallahAouadni** [comment]
Hello @Sinpery99 

Glad to hear :tada: But it seems more related to some overrides.
Closing this issue :wink: 

Thanks!

**Comment by LollipopAdmin** [comment]
Hey Guys, 

I had exactly the same problem on PS 1.7.8.0 with wishlist module 2.0.1: Same product displayed 2 or 3 times in the wishlist page. Shouldn't this piece of code (as suggested by @Sinpery99 ) corrected in an upgraded version of the wishlist module? 
By the way I also noticed that the Block ishlist module in the AddOns site is only supported until 1.7.6.0 so maybe that explains too... 

Block Wishlist module
Last update on - 28/05/2021
Supported Versions of PrestaShop - V1.4.0.1 - V1.7.6.0
Module Version - V 2.0.1

**Comment by LollipopAdmin** [comment]
> I have managed to fix the problem you mentioned. I do not know exactly why it is, since I have not had time to see it more calmly. I hope it can help whoever happens the same.
> 
> Go to file blockwishlist > src > Search > WishListProductSearchProvider.php
> 
> Look for this function and in this code add the bold line:
> 
> **$querySearch->groupBy('p.id_product');**
> 
> public function getProductsOrCount { . . . .
> 
> $querySearch->from('product', 'p'); $querySearch->join(Shop::addSqlAssociation('product', 'p')); $querySearch->innerJoin('wishlist_product', 'wp', 'wp.`id_product` = p.`id_product`'); $querySearch->leftJoin('category_product', 'cp', 'p.id_product = cp.id_product AND cp.id_category = product_shop.id_category_default'); **$querySearch->groupBy('p.id_product');**
> 
> }

It tried in my test environment and it indeed fixed the bug !!! Still what will happen at next upgrade of the environment or the module? 
Tks for follow up...

**Comment by Panniz** [comment]
> I have managed to fix the problem you mentioned. I do not know exactly why it is, since I have not had time to see it more calmly. I hope it can help whoever happens the same.
> 
> Go to file blockwishlist > src > Search > WishListProductSearchProvider.php
> 
> Look for this function and in this code add the bold line:
> 
> **$querySearch->groupBy('p.id_product');**
> 
> public function getProductsOrCount { . . . .
> 
> $querySearch->from('product', 'p'); $querySearch->join(Shop::addSqlAssociation('product', 'p')); $querySearch->innerJoin('wishlist_product', 'wp', 'wp.`id_product` = p.`id_product`'); $querySearch->leftJoin('category_product', 'cp', 'p.id_product = cp.id_product AND cp.id_category = product_shop.id_category_default'); **$querySearch->groupBy('p.id_product');**
> 
> }

I had the same problem, this fixed the issue. I overrode the Search class before, maybe that was causing the problem.

**Comment by HellYacht** [comment]
> I have managed to fix the problem you mentioned. I do not know exactly why it is, since I have not had time to see it more calmly. I hope it can help whoever happens the same.
> 
> Go to file blockwishlist > src > Search > WishListProductSearchProvider.php
> 
> Look for this function and in this code add the bold line:
> 
> **$querySearch->groupBy('p.id_product');**
> 
> public function getProductsOrCount { . . . .
> 
> $querySearch->from('product', 'p'); $querySearch->join(Shop::addSqlAssociation('product', 'p')); $querySearch->innerJoin('wishlist_product', 'wp', 'wp.`id_product` = p.`id_product`'); $querySearch->leftJoin('category_product', 'cp', 'p.id_product = cp.id_product AND cp.id_category = product_shop.id_category_default'); **$querySearch->groupBy('p.id_product');**
> 
> }

This fix work, but it will group 2 or more same products with different attributes(combination), and display only 1 of them. So instead of adding
**$querySearch->groupBy('p.id_product');**
i 've added 
**$querySearch->groupBy('id_product_attribute');** 
And now multiple same product with different attributes can be displayed.

**Comment by Mate0r** [comment]
Hi guys,

After investigating the issue, it seems it's related to the groups of the customer.

If the customer is associated to 2 groups then the product will appear twice, if 3 groups, 3 times ...

If you remove the line
$querySearch->leftJoin('category_group', 'cg', 'cp.`id_category` = cg.`id_category` AND cg.`id_group`' . $sqlGroups);

Then it returns only 1 product. Didn't test if there is side effects but it's do the trick for me.

I was not satisfied with your previous solutions cause the number of products displayed was wrong even if there was only 1 product for example, it keeps displaying 2 products.
