### ISSUE TITLE
FO - Bad display of quick view in some pages of products list for example Brand list page / Supplier list page / Search list page / Product page / Home page

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#27030]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

A bad display of quick view in products list in some pages. (ex : brands page)
PS178x :x: 
![image](https://user-images.githubusercontent.com/92912932/146753564-b90016b9-a0dc-40aa-a450-103bca51e90b.png)
![image](https://user-images.githubusercontent.com/92912932/146779704-6c1d013a-068e-49c1-92f5-f9cac37c0fb4.png)

https://watch.screencastify.com/v/ypmhCSwm5p0gxCrpEsGO

This issue is reproduced with
1. Brands list page: `shop.com/index.php?id_manufacturer=2&controller=manufacturer&id_lang=1`
2. Supplier list page: `shop.com/index.php?id_supplier=2&controller=supplier&id_lang=1`
3. Search list page: `shop.com/index.php?controller=search&s=mug`
4. Same issue in the FO > ps_specials module 
![image](https://user-images.githubusercontent.com/16067358/146906440-55d0baf2-6eaf-45ed-a216-d268732b0ee9.png)
5. FO > Product page > ps_crossselling module & ps_viewedproduct module 
![image](https://user-images.githubusercontent.com/16067358/146906488-585e441a-b325-4671-aa9d-9a7c6457e49d.png)
6. Also, in the featured product list => if we resize the window => display NOK and it became a major issue 
![image](https://user-images.githubusercontent.com/16067358/146918817-811d1f65-8f7b-4a0e-b0e2-85c8abef4df9.png)

PS1778 :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/92912932/146753650-e1cfd2dd-78c0-4f27-9b36-e38994c684b3.png)
![image](https://user-images.githubusercontent.com/92912932/146779863-35ef16ce-29d3-404f-8e6e-b5149a597d87.png)

https://watch.screencastify.com/v/JR9DiOFfEgSzjqeudkO5

### Expected behavior

The quick view form should be well displayed as on PS1778
![image](https://user-images.githubusercontent.com/92912932/146753650-e1cfd2dd-78c0-4f27-9b36-e38994c684b3.png)
![image](https://user-images.githubusercontent.com/92912932/146779871-032509db-2336-4a88-8826-d951809b6cef.png)

### Steps to reproduce

1. FO>Home>Click on a product
2. Click on Product Details
3. Click on a brand > run mouse over product to see quick view
4. See error > A bad display of quick view

### PrestaShop version(s) where the bug happened

1.7.8.x (before) & develop (now)

### PHP version(s) where the bug happened

7.3

**Comment by HanaRebaiQA** [comment]
related to #26992

**Comment by atomiix** [comment]
@HanaRebaiQA can you check again this issue? I was unable to reproduce it on 1.7.8.x

**Comment by HanaRebaiQA** [comment]
Hello @atomiix 

I think that the issue is fixed on PS178x branch. But, it appears on develop.
So, i will change the version of the issue.

178x : 
https://watch.screencastify.com/v/Zzz2obZVK5L06oUcmRqP
develop : 
https://watch.screencastify.com/v/8hwRnBer95FOgvrbg6hi

**Comment by Progi1984** [comment]
@NeOMakinG Could you check this issue ?

**Comment by NeOMakinG** [comment]
Didn't we fix this on 1.7.8.x? Maybe it's not merged yet on develop?

**Comment by HanaRebaiQA** [comment]
As the merge of 178x into develop is done yesterday [27537](https://github.com/PrestaShop/PrestaShop/pull/27537)
The behavior is therefore fixed in develop.

So, i close the issue!

**Comment by Progi1984** [comment]
:tada:
