### ISSUE TITLE
blockreassurance is not compatible with PS 8.0

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#27039]
There is a dependency conflict when installing blockreassuance in PS 8:

![Screenshot](https://user-images.githubusercontent.com/1533248/145216555-550d3504-eb30-4c7a-a81a-6bb88e17065a.png)

**Comment by atomiix** [comment]
This should be solved when blockreassurance 5.1.0 will be released!

**Comment by Progi1984** [comment]
I added the label "Blocked"

Why ? We need a new release of the module. And before that, we need to merge this PR PrestaShop/blockreassurance#359.
