### ISSUE TITLE
Maintenance mode does not show website after ip insertion

### ISSUE THREAD

**Issue by qualityangel** [PrestaShop/PrestaShop#27032]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When entering in Maintenance mode, you have to insert your IP to see the website in Maintenance mode. 
After entering the IP as usual, the website shows only the Maintenance notice for customers. 

Tried it in Google chrome Chrome incognito, MS Edge.

### Expected behavior

When entering IP adres save it and you can see your website when it is in Maintenance mode. Customers should see a Maintenance  sign what you have entered on the Maintenance config page.

### Steps to reproduce

1. Go to Settings->General->TAB Maintenance.
2. Click add my ip and set enable store on NO.

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4.26 - FPM Served by Nginx

**Comment by hibatallahAouadni** [comment]
Hello @qualityangel 

I didn't manage to reproduce the issue with PS1782, see the attached screen record below:

https://www.awesomescreenshot.com/video/6526110?key=8296ef5f649f2dae3617bbb84583f788

Please check and feedback.
Thanks!

**Comment by qualityangel** [comment]
You did make the screen of a local Prestashop. I have a clean install on my server. Never had it with Prestashop on my server.

**Comment by florine2623** [comment]
Hello @qualityangel ,

I cannot reproduce your issue in an online store. So I will close your issue.
I tested with multiple version of PHP and incognito mode.

https://user-images.githubusercontent.com/16019289/161721981-30ab544d-3037-4532-940d-129002927049.mov

Thanks!
