### ISSUE TITLE
Blockwishlist, when 'add to wish list' heart is clicked, if come back, there is an error in console

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#27038]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Blockwishlist module. If you add a combination to wishlist then go visit another combination then come back the console prints an error

### Expected behavior

No console error

### Steps to reproduce

1. Go to front office
2. Go to a product with combinations
3. Please verify zero of the combinations has been added to a wishlist, so all "heart" buttons (see below) are empty
4. Add one combination to a wishlist, the heart becomes filled
5. Select another combination. The heart is empty because it has not been added to a wishlist
6. Open browser console
7. Now go back to the first combination, the one added to wishlist.
8. See error in console

**Heart button**
![Capture d’écran 2021-12-20 à 17 39 11](https://user-images.githubusercontent.com/3830050/146801628-db33c4f4-aaba-4a71-974f-9993213dc0cc.png)

**Error in browser console**
![Capture d’écran 2021-12-20 à 17 28 57](https://user-images.githubusercontent.com/3830050/146801659-194c9696-9fae-42e1-b5f9-661ff9538c22.png)

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

N/A

### If your bug is related to a module, specify its name and its version

blockwishlist, dev branch

**Comment by marwachelly** [comment]
Hello,

I manage to reproduce the issue on develop and 1.7.7.8. 
https://watch.screencastify.com/v/EvU6G8KI9uaInY1QmMLU

Thanks,
