### ISSUE TITLE
productcomments is not compatible with PS 8.0

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#27040]
There is a dependency conflict when installing productcomments in PS 8:

![Screenshot](https://user-images.githubusercontent.com/1533248/145216608-b29d145a-9430-43a5-9d24-9844aee57438.png)

Do not forget to check to reproduce the [bug #27007](https://github.com/PrestaShop/PrestaShop/issues/27129) after the compatibility update

**Comment by atomiix** [comment]
Reopened, will be effectively done when the module will be released
