### ISSUE TITLE
BO - Cross icon is not working and freezed page while editing a specific price in pricing page

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#27047]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Cross icon is not working and freezed page while editing a specific price in pricing page
https://watch.screencastify.com/v/FUaSFpaX7udUKv4oVRsd

### Steps to reproduce

1. Go to BO> Catalog> products 
2. Add new product> Go to Pricing page 
3. Add a specific price
4. edit the specific price
5. click on the cross icon => The cross icon is not working 
6. click out of the popap => The page is freezed

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

**Comment by MatShir** [comment]
Might be fixed with v2

**Comment by MatShir** [comment]
It seems it is fixed on the experimental product page that is going to be the next product page ;)
