### ISSUE TITLE
Reminder issue. Update specific price modal view according to new specifications

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#27049]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Describe the solution you'd like

Reminder issue related to this PR #25742.
Specific price modal UI was redesigned while implementing commands.
The view should be adapted to new vision of UI in separate PR.
And a final wording review must be done when the 2nd PR is ready

**Comment by Julievrz** [comment]
I added a note about wording and put the "waiting for wording" label here so that I can put "Wording ✅" on your current PR. ☺️
