### ISSUE TITLE
As a merchant, I need to see quickly if the order was placed by a guest

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#27043]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

As a merchant, I need to see quickly if the order was placed by a guest
Groups are already displayed but this is not enough, especially if the guest group has been renamed.

### Describe the solution you'd like

If the order was placed by a guest, the following icon should be displayed in the order detail page:

**Comment by Hlavtox** [comment]
Hi @marionf, isn't that the responsibility of the merchant to know what he renamed the Guest group to? It's clearly stated in the group settings.
![Výstřižek](https://user-images.githubusercontent.com/6097524/146926996-06f0ff39-4540-49fd-83dc-4726744da5a9.JPG)

Also, you can distinguish a guest by not having this information:
![groups](https://user-images.githubusercontent.com/6097524/146927112-05e5b6a3-9566-4b30-babf-4d44a8a239fe.JPG)

**Comment by prestascott** [comment]
Since we can already identify if the customer is a guest or registered, we can close this issue.

**Comment by prestascott** [comment]
Since we can already identify if the customer is a guest or registered, we can close this issue.
