### ISSUE TITLE
Error when closing the site for maintenance

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#27050]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I turn on the maintenance mode, I see an error) Changed the php version, it did not help.

`href="/admin********/index.php/configure/shop/maintenance/?_token=***************"

`

![Symfony-Profiler (1)](https://user-images.githubusercontent.com/79253074/147001973-f577455d-deb0-4043-80af-f910d26b96c1.png)

![Снимок-экрана-126-](https://user-images.githubusercontent.com/79253074/147002427-74a7f292-91a4-4670-83be-a16d64cd3958.png)

### Expected behavior

I want to understand what is wrong

### Steps to reproduce

Enable Store - No

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4.3

**Comment by hibatallahAouadni** [comment]
Hello @DiamantG 

I see no error in your provided screenshots, could you please explain it more :pray: 
Please check and feedback.

Thanks!

**Comment by ghost** [comment]
> Hello @DiamantG
> 
> I see no error in your provided screenshots, could you please explain it more 🙏 Please check and feedback.
> 
> Thanks!

Due to this error, the layout of the admin panel looks wrong.

`href="/admin********/index.php/configure/shop/maintenance/?_token=***************"`

It should not be

**Comment by hibatallahAouadni** [comment]
Hello @DiamantG 

> Due to this error

Where's the error? what is this error??
Please explain the error that you encounter :pray: 

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello,

This issue is closed because the user has deleted their account and cannot respond.
