### ISSUE TITLE
[BO] The currency symbol in product page doesn't display for RTL

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/PrestaShop#27051]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In product edit page at pricing tab, the currency symbol in the price input group is empty for RTL languages.

**English:**

![ltr](https://user-images.githubusercontent.com/85633460/147068947-3ed71d44-45c4-409d-98d9-3b6e80d46317.png)

**Arabic:**

![ar](https://user-images.githubusercontent.com/85633460/147068988-3c3c5d99-5e85-451c-8c94-40949c1957df.png)

**Persian:**

![fa](https://user-images.githubusercontent.com/85633460/147069022-bff260ea-5ec7-4bb7-9315-fa1ab889837e.png)

### Expected behavior

The currency symbol must be displayed alongside the price amount.

### Steps to reproduce

1. Go to BO > Catalog
2. Select a product to edit
3. Go to Pricing tab

### PrestaShop version(s) where the bug happened

8.0

### PHP version(s) where the bug happened

8.0

**Comment by mparvazi** [comment]
This issue found by @marwachelly here: https://github.com/PrestaShop/PrestaShop/pull/26700#issuecomment-989911721

The currency symbol in HTML is empty, so I think it should be checked from Core. 

![code](https://user-images.githubusercontent.com/85633460/147070010-ff9caf52-2022-424a-a5a2-881df68463df.png)

**Comment by mparvazi** [comment]
Default product page:
src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_layout.html.twig

Product v2:
src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig

![Screenshot from 2021-12-22 13-17-25](https://user-images.githubusercontent.com/85633460/147072497-4bfec9ef-27b3-4eba-8317-5745d305f95d.png)

**Comment by hibatallahAouadni** [comment]
Hello @mparvazi 

I was able to reproduce the issue with PrestaShop version 1.7.6.7, 1.7.7.8 and 1.7.8.2. I’ll add this to the debug backlog so that it’s fixed.
Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved.

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by mparvazi** [comment]
Problem:

`vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/Type/MoneyType.php`

![symfony](https://user-images.githubusercontent.com/85633460/148698756-150eccb0-021c-4f78-ba96-ac5bdc9b05a7.png)

When shop language is RTL, the numerical digits for currency are in the form of Unicode: `۱۲۳ `

&#1777; => U+06F1
&#1778; => U+06F2
&#1779; => U+06F3

But preg_match pattern designed to find ASCII digits (i.e. `123`)

`/^([^\s\xc2\xa0]*)[\s\xc2\xa0]*123(?:[,.]0+)?[\s\xc2\xa0]*([^\s\xc2\xa0]*)$/u`

https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/Form/Extension/Core/Type/MoneyType.php

**Comment by mparvazi** [comment]
This issue originally is not related to PS.

**Comment by mparvazi** [comment]
This issue originally is not related to PS.

**Comment by hibatallahAouadni** [comment]
Oh I see, hope it will be fixed soon :relaxed:
