### ISSUE TITLE
Problem with contributing

### ISSUE THREAD

**Issue by monumatik** [PrestaShop/PrestaShop#27060]
I try to contribute with docker. I got Windows 10 with WSL2 and Docker WSL2 integration enabled.
I run containers by use docker-compose up - containers up but when i try to access FO i see empty page.
I try to generate assets by ./tools/assets/build.sh. - it hangs on:
![image](https://user-images.githubusercontent.com/40207400/147120947-66b1a8d4-3610-46d9-86a9-8741662c5cd5.png)

Now i can see BO but FO is still empty page.

### PrestaShop version(s) where the bug happened
develop

**Comment by hibatallahAouadni** [comment]
Hello @monumatik 


Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
