### ISSUE TITLE
error in comment ? 

### ISSUE THREAD

**Issue by mojinet** [PrestaShop/PrestaShop#27069]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi,

it seems to me that there is an error in the comment it is not the header but the footer

![image](https://user-images.githubusercontent.com/21148133/147154173-0e9dbe7b-3332-4652-8281-675f16bbffba.png)

### Steps to reproduce

go to classes/controller/Controller.php

### PrestaShop version(s) where the bug happened

latest

**Comment by hibatallahAouadni** [comment]
Hello @mojinet 

Could you please specify the error in the comment cause I see no error.
Please provide the expected behavior :pray: 

Thanks!

**Comment by PrestaEdit** [comment]
Hi @mojinet,
Hi @hibatallahAouadni,

It's right. A Pull Request to change it is now done.
