### ISSUE TITLE
400 Bad Request Context ALL Shop When Save product

### ISSUE THREAD

**Issue by openpresta** [PrestaShop/PrestaShop#27063]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Try to add a  product in multi shop and save 

![Capture d’écran 2021-12-22 à 17 46 16](https://user-images.githubusercontent.com/30599677/147126914-a89bb709-2637-4bab-886d-5a243f117f68.png)
An error apear in the console and a green alert at the first click with multistore enabled and when all shop is selected. But the settings are saved wih the second click on save.
https://watch.screencastify.com/v/LmyHYLG0Cpvkc3l5M4z0

### Steps to reproduce

in multi shop 
Go to Catalog->Product 
click add new product 
try to save 

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Hello @openpresta 

I didn't manage to reproduce the issue with PS1772 and PS1782.
Could you please provide a screen record or some other details like which kind of product you wanna create :pray: 

Thanks!

**Comment by openpresta** [comment]
hello, 

how much shop have you create ? 
in our case 5 shop 
thanks

**Comment by hibatallahAouadni** [comment]
Hello @openpresta 

And are these 5 shops in the same group shop or different groups?
What kind of product did you try to create? simple or pack or product with combinations?
Please check and feedback.

Thanks!

**Comment by openpresta** [comment]
hello, 

5 shop in the same shop group, 
2 others in others groups but are not active. 

Product simple , 

Duplication work fine 
Edition previous product work fine 
Add new product in just one shop work fine 

Solution like :  LimitRequestFieldSize 1000000  not work

**Comment by marwachelly** [comment]
Hello,

Thank you for your report I manage to reproduce the issue with 1.7.8.2 and 1.7.6.9. An error apear in the console and a green alert at the first click with multistore enabled and  when all shop is selected. But the settings are saved wih the second click on save. => Description is updated.
https://watch.screencastify.com/v/LmyHYLG0Cpvkc3l5M4z0

Thanks,

**Comment by matks** [comment]
Hello @openpresta in PrestaShop 8.1.0 the Product backoffice page has been reworked and multiple improvements have been added, including multistore fixes. Can you try on this new version if the bug is no longer present?

**Comment by hibatallahAouadni** [comment]
Hello @matks & @openpresta 

It seems the issue has been fixed with the new Product page on 8.1.x, see the attached screenshot below:

![image](https://github.com/PrestaShop/PrestaShop/assets/23308427/87776c34-25e2-462d-92a5-096d7ff79f59)

Closing the issue :tada:
