### ISSUE TITLE
Use front controller on all native modules

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#27061]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Modules implementing a simple PHP script as a cron task, as described in the documentation should migrate their scripts to front controllers or the following can happen:

- Cause memory issues because they load everything on Syphony, so all it can be loaded, especially the theme.
- Symphony creates a yaml subdirectory on each module directory when the Script is executed as a crontask thinking is the root directory.

It is descibed in the Prestashop Documentation:

> > Using a front controller as a cron task
> > 
> > Implementing a controller instead of a simple PHP script will allow you to **avoid some issues** such as a non-instanciated Context or Symfony Kernel, especially on the latest versions of PrestaShop (i.e display of prices from PS 1.7.6). That’s why, even for CLI calls triggered by a cron jobs, we recommend having a controller. The trick is to define it as an Ajax call to prevent the page template to be displayed.
> 
> [PrestaShop Dev Docs](https://devdocs.prestashop.com/1.7/modules/concepts/controllers/front-controllers/#using-a-front-controller-as-a-cron-task)

### Expected behavior

No yaml folder created an no memory leaks.

### Steps to reproduce

Install a clean PrestaShop on /var/www/html/.

1. Go to ps_facetedsearch Module configuration.

2. Copy the attribute crontask URL:

https://my.site/modules/ps_facetedsearch/ps_facetedsearch-attribute-indexer.php?token=4ef2ac0f1a

3. Paste it to a Web Browser and wait till the page is loaded so crontask is executed, keep it open.

4. then list module directory /var/www/html/modules/ps_facetedsearch to find a yaml subdirectory created by Symphony.

To know where the error resides we can just lock the yaml folder making the folder owned by root:

> sudo chown root:root /var/www/html/modules/ps_facetedsearch/yaml

Then we execute again the crontask using the same link, or just refresh the page if we kept it open, and we can see the following exception becasue it always tries to use or create it as expected by Symphony:

> Fatal error: Uncaught Symfony\Component\Filesystem\Exception\IOException: Unable to write to the "yaml" directory. in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:680 Stack trace: #0 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Config/ResourceCheckerConfigCache.php(124): Symfony\Component\Filesystem\Filesystem->dumpFile('yaml/76a40f46af...', '<?php return ar...') #1 /var/www/html/src/Core/Util/File/YamlParser.php(92): Symfony\Component\Config\ResourceCheckerConfigCache->write('<?php return ar...', Array) #2 /var/www/html/src/Core/Addon/Theme/Theme.php(43): PrestaShop\PrestaShop\Core\Util\File\YamlParser->parse('/var/www/html/t...') #3 /var/www/html/src/Core/Addon/Theme/ThemeRepository.php(93): PrestaShop\PrestaShop\Core\Addon\Theme\Theme->__construct(Array) #4 /var/www/html/classes/shop/Shop.php(495): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeRepository->getInstanceByName('child_classic') #5 /var/www/html/classes/shop/Shop.php(137): ShopCore->setTheme() #6 /var/www/h in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php on line 680

Solved adding editing all cron files, for ex;

```
sudo vi /var/www/html/modules/ps_facetedsearch/ps_facetedsearch-attribute-indexer.php

and then add: 

chdir('/../.../');

before

require_once __DIR__ . '/../../config/config.inc.php';
```

No yaml folder created.

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_facetedsearch 3.7.1

**Comment by hibatallahAouadni** [comment]
Hello,

This issue seems related to this one #25294 & #19849
Well, the contributor delete his Github account :confused: 
Ping @PrestaShop/prestashop-core-developers do you think that this issue is relevant to keep it open, or should I close it? Cause I have no error when I execute that cron.

Thanks!

**Comment by PierreRambaud** [comment]
I'm sorry but I'm not able to reproduce your issue with the `yaml` directory.
Isn't just a problem with your server configuration? Something like open_basedir?

**Comment by hibatallahAouadni** [comment]
Hello,

Closing this issue because the user has deleted their account and cannot respond.

Thanks!

**Comment by RebelliousSmile** [comment]
Sorry to reopen this ticket, but i'm trying to get a local copy of a prestashop 1.7.8.7 site, with two different hosts, and i'm stucked with this error : 
```php
Fatal error: Uncaught Symfony\Component\Filesystem\Exception\IOException: Unable to write to the "yaml" directory. in /home/tnn/Projets/Prestashop/epicime/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:680 Stack trace: #0 /home/tnn/Projets/Prestashop/epicime/vendor/symfony/symfony/src/Symfony/Component/Config/ResourceCheckerConfigCache.php(124): Symfony\Component\Filesystem\Filesystem->dumpFile() #1 /home/tnn/Projets/Prestashop/epicime/src/Core/Util/File/YamlParser.php(92): Symfony\Component\Config\ResourceCheckerConfigCache->write() #2 /home/tnn/Projets/Prestashop/epicime/src/Core/Addon/Theme/Theme.php(43): PrestaShop\PrestaShop\Core\Util\File\YamlParser->parse() #3 /home/tnn/Projets/Prestashop/epicime/src/Core/Addon/Theme/ThemeRepository.php(93): PrestaShop\PrestaShop\Core\Addon\Theme\Theme->__construct() #4 /home/tnn/Projets/Prestashop/epicime/classes/shop/Shop.php(495): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeRepository->getInstanceByName() #5 /home/tnn/Projets/Prestashop/epicime/classes/shop/Shop.php(137): ShopCore->setTheme() #6 /home/tnn/Projets/Prestashop/epicime/classes/shop/Shop.php(415): ShopCore->__construct() #7 /home/tnn/Projets/Prestashop/epicime/config/config.inc.php(128): ShopCore::initialize() #8 /home/tnn/Projets/Prestashop/epicime/admin1113/index.php(40): require('...') #9 {main} thrown in /home/tnn/Projets/Prestashop/epicime/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php on line 680
``` 

I'm using locally php 8.1, and i have no module called ps_facetedsearch. 
Thanks !
