### ISSUE TITLE
Remove the page "Referrers" after the upgrade

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#27064]
**Describe**
Since the module  linked to this page are archived, the page has no more use.
**Solution**
- Remove the page at the upgrade

- When the core removes a page, we should remove the quick access linked to this page.

- Remove SEO & URLs > Referrers for the BO
and on the user doc when the PR will be merged
remove the label

_Originally posted by @MatShir in https://github.com/PrestaShop/PrestaShop/issues/26662#issuecomment-999455634_

**Comment by alfonsolr09** [comment]
what is the page refferes? @MatShir

**Comment by Progi1984** [comment]
This issue is waiting for PrestaShop/autoupgrade#466 to be closed.

**Comment by MatShir** [comment]
@Julievrz I think we can start removing the page from the doc
