### ISSUE TITLE
Fill the tab property of natives modules

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#27075]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

A lot of natives modules don't have the `tab` property
In the V8 and without the addons API, all our modules are going to be classed in the **Other** category

### Describe the solution you'd like

Fill the the `tab` property for the following modules:

**Administration** `administration`
- [x] [Dashboard Trends](https://github.com/PrestaShop/dashtrends)
- [x] [Catalog evaluation](https://github.com/PrestaShop/statscheckup)
- [x] [Best-selling products](https://github.com/PrestaShop/statsbestproducts)
- [x] [Product details](https://github.com/PrestaShop/statsproduct)
- [x] [Sales and orders](https://github.com/PrestaShop/statssales)
- [x] [Dashboard Goals](https://github.com/PrestaShop/dashgoals)
- [x] [Available quantities](https://github.com/PrestaShop/statsstock)
- [x] [Best categories](https://github.com/PrestaShop/statsbestcategories)
- [x] [Customer data privacy block](https://github.com/PrestaShop/ps_dataprivacy)
- [x] [Best customers](https://github.com/PrestaShop/statsbestcustomers)
- [x] [Shop search](https://github.com/PrestaShop/statssearch)
- [x] [Best suppliers](https://github.com/PrestaShop/statsbestsuppliers)
- [x] [Pages not found](https://github.com/PrestaShop/pagesnotfound)
- [x] [Dashboard Activity](https://github.com/PrestaShop/dashactivity)
- [x] [Customer accounts](https://github.com/PrestaShop/statsregistrations)
- [x] [Stats Dashboard](https://github.com/PrestaShop/statsforecast)
- [x] [Newsletter](https://github.com/PrestaShop/statsnewsletter)
- [x] [Registered customer information](https://github.com/PrestaShop/statspersonalinfos)
- [x] [Dashboard Products](https://github.com/PrestaShop/dashproducts)
- [x] [Catalog statistics](https://github.com/PrestaShop/statscatalog)
- [x] [Best vouchers](https://github.com/PrestaShop/statsbestvouchers)
- [x] [Best manufacturers](https://github.com/PrestaShop/statsbestmanufacturers)
- [x] [Data mining for statistics](https://github.com/PrestaShop/statsdata)
- [x] [Top-sellers block](https://github.com/PrestaShop/ps_bestsellers)
- [x] [Carrier distribution](https://github.com/PrestaShop/statscarrier)

**Promotions & Marketing** `pricing_promotion`
- [x] [Products category](https://github.com/PrestaShop/ps_categoryproducts)
- [x] [Cross-selling](https://github.com/PrestaShop/ps_crossselling)
- [x] [E-mail subscription form](https://github.com/PrestaShop/ps_emailsubscription)

**Payment** `payments_gateways`
- [x] [Cash on delivery (COD)](https://github.com/PrestaShop/ps_cashondelivery)

**Design & Navigation** `front_office_features`
- [x] [Banner](https://github.com/PrestaShop/ps_banner)
- [x] [Language selector](https://github.com/PrestaShop/ps_languageselector)
- [x] [Customer "Sign in" link](https://github.com/PrestaShop/ps_customersignin)
- [x] [Customer account links](https://github.com/PrestaShop/ps_customeraccountlinks)
- [x] [Custom text](https://github.com/PrestaShop/ps_customtext)
- [x] [Currency selector](https://github.com/PrestaShop/ps_currencyselector)
- [x] [Search bar](https://github.com/PrestaShop/ps_searchbar)
- [x] [Theme Customization](https://github.com/PrestaShop/ps_themecusto)
- [x] [Specials block](https://github.com/PrestaShop/ps_specials)
- [x] [New products](https://github.com/PrestaShop/ps_newproducts)

**Traffic & Marketplace** `checkout`
- [x] [Google sitemap](https://github.com/PrestaShop/gsitemap)

**Facebook & Social networks** `advertising_marketing`
- [x] [Social media follow links](https://github.com/PrestaShop/ps_socialfollow)
- [x] [Social media share buttons](https://github.com/PrestaShop/ps_sharebuttons)

**Comment by PierreRambaud** [comment]
I identity these modules for the moment:

- Dashboard Trends
- Catalog evaluation
- Products category
- Best-selling products
- Cash on delivery (COD)
- Banner
- Language selector
- Product details
- Customer "Sign in" link
- Customer account links
- Sales and orders
- Google sitemap
- Social media follow links
- Dashboard Goals
- Available quantities
- Best categories
- Custom text
- Cross-selling
- Customer data privacy block
- Best customers
- Currency selector
- E-mail subscription form
- Shop search
- Best suppliers
- Pages not found
- Search bar
- Dashboard Activity
- Carrier distribution
- Theme Customization
- Customer accounts
- Specials block
- Stats Dashboard
- Newsletter
- New products
- Registered customer information
- Dashboard Products
- Catalog statistics
- Best vouchers
- Social media share buttons
- Best manufacturers
- Data mining for statistics
- Top-sellers block

**Comment by PrestaEdit** [comment]
Google Sitemap is set to `seo` at this moment, it's need to be updated to `checkout` ?

**Comment by PrestaEdit** [comment]
It's seems that I have forgotten one module, but I can't say wich right now :-/
