### ISSUE TITLE
Module not showing on dashboard

### ISSUE THREAD

**Issue by acVeli** [PrestaShop/PrestaShop#27074]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I'm on a PS 1.7.5.1

The problem i encounter is when i activate the module, i can't find him on my dashboard, even when
 i try to manually attach the module to the hook : displayAdminStatsModules
 I can't see him on the dashboard. So i can't even debug it to make it work ! :) 
 
 
![Capture4](https://user-images.githubusercontent.com/66263952/147263662-d2846269-bba8-48f9-af06-825d92648c9e.PNG)
![Capture3](https://user-images.githubusercontent.com/66263952/147263665-8c1eea76-5465-467d-bf2c-c46a5758fafe.PNG)
![Capture2](https://user-images.githubusercontent.com/66263952/147263667-f6d24391-a090-43f8-a65d-c8a31d186d4f.PNG)
![Capture1](https://user-images.githubusercontent.com/66263952/147263671-4873095b-093a-49c3-96c0-2e43cf8083a0.PNG)

### Expected behavior

I would like to make it to work, after it displays, even if there is still a bug i can try to debug it..

### Steps to reproduce

1. Go to module manager
2. Look for best customers module
3. activate it
4. go to the dashboard
5. nothing happens,
6. try to go in positions
7. attach the module on the displayAdminStatsModules hook
8. warning message come up and still nothing on dashboard

### PrestaShop version(s) where the bug happened

1.7.5.1

### PHP version(s) where the bug happened

7.2.34

### If your bug is related to a module, specify its name and its version

statsbestcustomers

**Comment by PrestaEdit** [comment]
Hi !

This hook is not the "Dashboard" controller, it's the "Statistics" controller.

It's why you don't see it here, so.

**Comment by HanaRebaiQA** [comment]
Hello @acVeli 

This `displayAdminStatsModules` is used for Stats and not Dshboard page.
You can see here the `statsbestcustomers` is well shown in stats 
![image](https://user-images.githubusercontent.com/92912932/147357772-db1b369f-ebd8-44be-b293-b1decc378530.png)

Please chack and feedback!

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @acVeli 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
