### ISSUE TITLE
BO - Dashboard - Dashproducts module is NOK

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27073]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Dashboard page > the module Dashproducts is Not working
![image](https://user-images.githubusercontent.com/16067358/147263624-88dbbb1f-6734-44cc-a9ea-006dc204acfc.png)

in the console error 500
![image](https://user-images.githubusercontent.com/16067358/147263601-5a84da55-d125-4db9-9a0e-02ea23d3c94a.png)

It should be 
![image](https://user-images.githubusercontent.com/16067358/147263023-bf60add2-181d-4c11-b956-9b78398aedac.png)

### Steps to reproduce

1. Go to BO > Module manager page
2. Install the dev branch of the module https://github.com/PrestaShop/dashproducts
3. Go to Dashboard 

### PrestaShop version(s) where the bug happened

1.7.7.8, 1.7.8.2, 1.7.8.x, develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

dashproducts v2.1.2

**Comment by florine2623** [comment]
Using dashproduct v2.1.4, there's no exception. I'm closing the issue.

<img width="919" alt="Screenshot 2023-12-27 at 15 09 55" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/cf1ca3c4-18ff-4ee6-92e8-71c06bd3de78">
