### ISSUE TITLE
Display issue for the polish language and the checkout button

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#27078]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Screenshot:

![image](https://user-images.githubusercontent.com/2137763/147277598-aeb0fac2-ae51-4c24-aae2-871edfcd12a0.png)

### Expected behavior

Properly displayed button with "Przejdź do realizacji zamówienia"

### Steps to reproduce

1. Install the PL language
2. Go to the cart

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by hibatallahAouadni** [comment]
Hello @kpodemski 

Thanks for reporting the issue!
This issue is not related to the language Polish, it's related to a long text :wink: 
Thanks for the PR :tada: I reproduce the issue with PS1778, PS1780 and develop.

Thanks!
