### ISSUE TITLE
[BO] The ps_reminder module archived but still exists in email theme folder

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/PrestaShop#27084]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The [ps_reminder](https://github.com/PrestaShop/ps_reminder) module has been archived but its twig layouts still exists in email theme folders:

```
PrestaShop/mails/themes/classic/modules/ps_reminder
PrestaShop/mails/themes/modern/modules/ps_reminder
```
After a fresh install of PS, the `ps_reminder` folder will be created in modules folder by email theme generator.

### Expected behavior

If this module is no longer available and cannot be used by other modules, then its items should be removed.

**Folders that should be deleted:** 
[PrestaShop/mails/themes/classic/modules/ps_reminder](https://github.com/PrestaShop/PrestaShop/tree/develop/mails/themes/classic/modules/ps_reminder)
[PrestaShop/mails/themes/modern/modules/ps_reminder](https://github.com/PrestaShop/PrestaShop/tree/develop/mails/themes/modern/modules/ps_reminder)

**Files that should be reviewed:**
[PrestaShop/.gitignore](https://github.com/PrestaShop/PrestaShop/blob/develop/.gitignore)
[PrestaShop/tests/Integration/Core/MailTemplate/MailTemplateGeneratorTest.php](https://github.com/PrestaShop/PrestaShop/blob/develop/tests/Integration/Core/MailTemplate/MailTemplateGeneratorTest.php)
[PrestaShop/tests/Unit/Core/MailTemplate/LayoutVariablesBuilderTest.php](https://github.com/PrestaShop/PrestaShop/blob/develop/tests/Unit/Core/MailTemplate/LayoutVariablesBuilderTest.php)

**Translation file that should be reviewed:**
[PrestaShop/translations/default/EmailsBody.xlf ](https://github.com/PrestaShop/PrestaShop/blob/develop/translations/default/EmailsBody.xlf)

**Translation file that should be deleted:**
[PrestaShop/translations/default/ModulesReminderAdmin.xlf](https://github.com/PrestaShop/PrestaShop/blob/develop/translations/default/ModulesReminderAdmin.xlf)

### Steps to reproduce

1. Go to BO > Design > Email Theme
2. Select a theme for preview
3. The `ps_reminder` exists in grid table

### PrestaShop version(s) where the bug happened

8.0

### If your bug is related to a module, specify its name and its version

ps_reminder

**Comment by HanaRebaiQA** [comment]
Hello @mparvazi 

Thanks for reporting this issue.
I did manage to reproduce the issue from PS1780, PS1781, PS178x & develop.
https://watch.screencastify.com/v/V7qQxRfRvjTm2tke78LO

**It's a regression**, because this issue is not reproduced on PS1778.
https://watch.screencastify.com/v/gy5oH4QRAB6Zvnfh3dZT

I’ll add this to the debug backlog so that it’s fixed.

Thank You!

**Comment by mparvazi** [comment]
Hello @HanaRebaiQA 

The `ps_reminder` folder that is inside email themes [renamed](https://github.com/PrestaShop/PrestaShop/commit/7ac50b6c069171464d266a7321ed11cf0b0cd02e#diff-06c6a559a260d4b0398f1960ea7032a22a32fddeef831bd4dd1a2af34e150f0b) from [followup](https://github.com/PrestaShop/followup) to [ps_reminder](https://github.com/PrestaShop/ps_reminder) with this [PR](https://github.com/PrestaShop/PrestaShop/pull/22211).

So that's why it's not exists in PS1778.

**Comment by mparvazi** [comment]
@hibatallahAouadni 
I think this issue also is related to translations.

**Comment by MatShir** [comment]
Nice catch @mparvazi, but here the cleaning code around the archived module is considered as an improvement. The code has no impact on the ecosystem, so this enhancement must be done on the development branch.

**Comment by mparvazi** [comment]
@MatShir
I definitely agree with you!

**Comment by boubkerbribri** [comment]
It's the same for followup module, there is a new folder added by this [PR](https://github.com/PrestaShop/PrestaShop/pull/25992) that should be deleted.
