### ISSUE TITLE
[BO] An unknown error in Stats page at Debug mode

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/PrestaShop#27086]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I want to open Stats page, an error will be displayed in debug mode.

![Screenshot from 2021-12-24 13-30-21](https://user-images.githubusercontent.com/85633460/147344584-5130c44c-13dc-47d1-a33f-26d397401382.png)
 

### Steps to reproduce

1. Enable debug mode
2. Go to BO > Stats

### PrestaShop version(s) where the bug happened

8.0

### PHP version(s) where the bug happened

8.0

**Comment by PrestaEdit** [comment]
Hi,

I confirm this.

**Comment by khouloudbelguith** [comment]
Hi @PrestaEdit, @mparvazi,

I manage to reproduce the issue with develop branch using the php version 8.0
![image](https://user-images.githubusercontent.com/16067358/147363195-18cf0309-3c84-466a-b323-14271a3e6fc6.png)

Thank you!
