### ISSUE TITLE
Link to the customer page if the author is a customer

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#27089]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

This feature request is related to the ProductComments module.

Original feature request from @vallka 

> Adding a link to the customer profile in BO - product comments lists (just like it was done recently in Orders list). This allows moderators to quickly navigate to comment author's profile - e.g. we use this feature to add royalty points to comments authors

### Describe the solution you'd like

Link to the profile page, if the author of the comment is a customer

**Comment by HanaRebaiQA** [comment]
Hello @kpodemski 

Thank you for your suggestion and for your PR. 
The Product Team will take it into consideration for future developments. 

Thank You!

**Comment by HanaRebaiQA** [comment]
Ping @PrestaShop/product-team ,

What do you think about @kpodemski 's suggestion ?

Thank You!
