### ISSUE TITLE
Autoupgrade from older 1.6 versions and PHP compatibility

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#27087]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The latest version of the autoupgrade module (v4.13.0) [reports itself as compatible since 1.6.0.0](https://github.com/PrestaShop/autoupgrade/blob/v4.13.0/autoupgrade.php#L53). The PHP compatibility range for 1.6.0.0 is unknown to me, but it's unlikely that it goes beyond 5.6.

According to that, the autoupgrade module should work with PHP 5.6, but as noted by @Prestaworks, this line fails in PHP < 7: https://github.com/PrestaShop/autoupgrade/blob/v4.13.0/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php#L195

As you can see [here](https://3v4l.org/3eDct), `dirname()` only accepts two parameters as of PHP 7.0, so it fails in PHP 5.6 and earlier.

### Expected behavior

Steps to fix the issue:

- [ ] Syntax check (`php -l`) the code with PHP 5.6, find all incompatible changes and find when the changes have been introduced. If the changes are easy to fix, issue a patch release. If not, identify the last version compatible with PHP 5.6, and mark all versions since as incompatible with PS < 1.6.1.18 in Addons marketplace
- [ ] Release a v5 dropping compatibility with PHP < 7.1 and PS < 1.6.1.18
- [ ] Add automated linter checks through github actions to ensure syntax is valid for all supported PHP versions

### Steps to reproduce

Explained above

### PrestaShop version(s) where the bug happened

1.6.0.9

### PHP version(s) where the bug happened

PHP < 7.0

### If your bug is related to a module, specify its name and its version

autoupgrade v4.13.0

**Comment by Prestaworks** [comment]
I did a run of the files with php -l
using 5.6.40

Parse error: syntax error, unexpected '?' in D:\Github\autoupgrade\.github\get_results.php on line 3
Errors parsing D:\Github\autoupgrade\.github\get_results.php

Parse error: syntax error, unexpected ':', expecting ';' or '{' in D:\Github\autoupgrade\upgrade\php\migrate_tabs_17.php on line 102
Errors parsing D:\Github\autoupgrade\upgrade\php\migrate_tabs_17.php

content of my bat file
`
 For /R D:\Github\autoupgrade %%G IN (*.php) do php -l "%%G" >> result.txt
`


This did however not detect the issue with the dirname extra parameter.

**Comment by khouloudbelguith** [comment]
Hello,

I tried to upgrade from 16120 to PS16124 using the php5.6, but I have an error
![image](https://user-images.githubusercontent.com/16067358/185869980-e7de7592-0683-42a1-8aad-88a5d3ca4a08.png)

Thanks!
