### ISSUE TITLE
[BO] Bad display of header toolbar in Product page and Stock page

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/PrestaShop#27085]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An unexpected horizontal line will be displayed at top of the Product edit page and the Stock page.

**Product page:**

![Screenshot 2021-12-24 at 13-35-57 Product • dev](https://user-images.githubusercontent.com/85633460/147343561-56db63da-aaa9-4079-ac90-6652cd66091f.png)

**Stock page:**

![Screenshot 2021-12-24 at 13-35-18 Stock • dev](https://user-images.githubusercontent.com/85633460/147343592-d98e52d5-7afd-4790-bc72-1d5dd1e9c780.png)

### Expected behavior

This horizontal line doesn't appear in other pages.

**Categories page:**

![Screenshot 2021-12-24 at 13-43-20 Edit Clothes • dev](https://user-images.githubusercontent.com/85633460/147343922-86c77eb3-eb53-418f-ab7b-771c2ca3ac51.png)

### Steps to reproduce

**Product:**
1. Go to BO > Catalog > Products
2. Select a product to edit

**Stock:**
1. Go to BO > Catalog > Stock

### PrestaShop version(s) where the bug happened

8.0

### PHP version(s) where the bug happened

8.0

**Comment by HanaRebaiQA** [comment]
Hello @mparvazi 
I did reproduce the issue on develop & PS1778 for product page, but this line was not displayed on PS1778 for stock page
Product :
![image](https://user-images.githubusercontent.com/92912932/147361458-1b39de95-809c-4547-a4cb-e92f0c6b06bc.png)

Stock : 
![image](https://user-images.githubusercontent.com/92912932/147361503-c33ed6d8-d655-4443-8c4b-1f36696da6ac.png)
![image](https://user-images.githubusercontent.com/92912932/147361525-8f22b16f-d256-432a-a9e2-bb6f9e6439be.png)


ping @NeOMakinG : What do You think ?

Thank You!

**Comment by NeOMakinG** [comment]
I don't know what's the needed behavior, @prestascott should respond on this

**Comment by prestascott** [comment]
Hello everyone,

Thank you @mparvazi for your suggestion.

@NeOMakinG The horizontal line should always be displayed, but without the shadow. This allows a better structure in the header. 
Also, I noticed a lack of margin-bottom on the search input, can you fix it please? ^^

**Comment by mparvazi** [comment]
@prestascott @NeOMakinG 

This line in these pages displayed because of wrong placement for header toolbar.
So first of all toolbar placement should be fixed for these pages and then can use CSS for adding border line for all pages.

**Comment by NeOMakinG** [comment]
Yeah was pretty sure that it was the background 😆 

Let's think about fixing it properly
