### ISSUE TITLE
Product comments 5.0.0 version error in console

### ISSUE THREAD

**Issue by web-burn** [PrestaShop/PrestaShop#27096]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The productcomments module version 5.0.0 has error on product page if current product has at least one comment:
 
![Screenshot_1](https://user-images.githubusercontent.com/22581200/147369691-1cc5f8e4-4fa1-4556-92f5-082e2df7c972.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/22581200/147369693-441fecbd-96c7-4fff-803d-b97082b4e0f4.jpg)

### Steps to reproduce

1. Go to product page that has at least one comment.
2. Open Console. 
3. See error.

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.3.31

### If your bug is related to a module, specify its name and its version

productcomments

**Comment by Maofree** [comment]
Hi
I get the same error, this error is present on the version 5.0.0, the 4.2.2 was ok

no one has participated in this ticket, but I think it is very important, because with the latest version it is no longer possible to manage comments as well as to send all the javascript codes of the product pages into a product page

**Comment by Maofree** [comment]
I did some tests and I confirm that with version 4.2.2 there are no errors

**Comment by web-burn** [comment]
Hi,

If you activate default theme "Classic" and then enable your theme again after these action the error will not occur.
It helped me.

**Comment by Maofree** [comment]
Hi
I cannot do this action with a real website, there is a problem with the hooks
I'm studing to solve it

**Comment by Maofree** [comment]
I did a lot of tests, but I did not understand why on version 4.2.2 everything works well while with 5.0.0 there is this error, if I put the tpl and js files of 4.2.2 it continues to give the same errors in the pages of the products where comments are present.
in my opinion this error should have a higher priority in the resolution.

**Comment by web-burn** [comment]
I don't know why Prestashop is ignoring the problem.

**Comment by Oksydan** [comment]
@maofree it's already has been fixed https://github.com/PrestaShop/productcomments/pull/121

**Comment by Maofree** [comment]
ok thanks
I'll wait the next update

bye

**Comment by hibatallahAouadni** [comment]
Hello @web-burn 

> I don't know why Prestashop is ignoring the problem.

We didn't ignore any issue, you just closed the issue without waiting to be treated :wink: 

> @maofree it's already has been fixed PrestaShop/productcomments#121

As @Oksydan mentioned above this issue has been fixed with this PR PrestaShop/productcomments#121
So, closing the issue as it has been fixed in next version of the module .

Thanks!

**Comment by hibatallahAouadni** [comment]
Fixed by PrestaShop/productcomments#121
