### ISSUE TITLE
Tools.php not stripslashes the input return same

### ISSUE THREAD

**Issue by developerarun** [PrestaShop/PrestaShop#27090]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I am using Tools::stripslashes() but it not provide desired result when i visited the function it was like below 
`public static function stripslashes($string)
    {
        return $string;
    }`
    
    it should be like this 
    
    `public static function stripslashes($string)
    {
        return stripslashes($string);
    }`

### Expected behavior

It should return string without slashes instead of the same 

### Steps to reproduce

Call Tools::stripslashes($input);
compare output 

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

1.7.3

### If your bug is related to a module, specify its name and its version

prestashop Tools.php class

**Comment by kpodemski** [comment]
Hi @developerarun 👋 

It is better to use `stripslashes` directly.

We probably need to deprecate and remove this method in the future. What do you think @PrestaShop/prestashop-maintainers ?

**Comment by developerarun** [comment]
> Hi @developerarun wave
> 
> It is better to use `stripslashes` directly.
> 
> We probably need to deprecate and remove this method in the future. What do you think @PrestaShop/prestashop-maintainers ?

Yes but the current validator shows a warning for that, if it was planned to remove in the future then ok but current version should have correct working function unless depreicated
thanks

**Comment by PierreRambaud** [comment]
The Tools::stripslashes will be removed in the next Major version I think, it's totally useless.
It originally has been added because of GPC: https://github.com/PrestaShop/PrestaShop/blame/d7663195cfc582e1f1285ff03c90eac9859fa9c1/classes/Tools.php#L1707

**Comment by PrestaEdit** [comment]
I had a look on this and wanted to make two PR:
* One to make it as deprecated ;
* One to remove it.

But I don't know on which branch I need to make it deprecated about the 1.7.9 version, there :-/

**Comment by PierreRambaud** [comment]
> I had a look on this and wanted to make two PR:
> 
> * One to make it as deprecated ;
> * One to remove it.
> 
> But I don't know on which branch I need to make it deprecated about the 1.7.9 version, there :-/

There will be 1.7.9 version ^^

**Comment by PrestaEdit** [comment]
Yes but there is only develp (8.0.0), 1.7.7.x and 1.7.8.x branches, no 1.7.9.x at this moment :)

**Comment by kpodemski** [comment]
I think @PierreRambaud wanted to say "There will be no 1.7.9" :D

**Comment by PrestaEdit** [comment]
So, no deprecation before remove, or deprecated into 8.0 (Snif) ? :D

**Comment by kpodemski** [comment]
I've sent a PR some time ago, 8.0 is the next major but this method wasn't deprecated, so we need to deprecate it in v8, and then remove in v9 :D

**Comment by PrestaEdit** [comment]
So bad :(
