### ISSUE TITLE
Translations (in French) of the wording "Key" set to "Clef".

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#27109]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Of course, key can be translated into clé, clef. As it's the same into french.
But I think it's better to keep the same wording for every translation. As key is more translated into clé than clef, it will be usefull to change it.
<img width="470" alt="Capture d’écran 2021-12-28 à 11 49 33" src="https://user-images.githubusercontent.com/2631425/147558879-7c1e3fe3-e6ff-4b6f-9cc5-36b1fccd8817.png">

### Expected behavior

Update the wording.

### Steps to reproduce

- Enable the webservice
- Add a key
- See the filters wording

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by PrestaEdit** [comment]
Hi everyone,
Hi @Julievrz,

FYI, it's still the same translations inside the 8.0.0 version.

**Comment by Julievrz** [comment]
Hi @PrestaEdit, and thank you!

Translations are managed on https://crowdin.com/project/prestashop-official. Feel free to join the project as a French translator. ☺️

**Comment by PrestaEdit** [comment]
If I've done it well, I have manage to propose the change there :)

**Comment by Julievrz** [comment]
Great! I validated your suggestion, thank you. Please note we're facing some issues with the synchronization of Crowdin and the back office right now. So, you might not be able to see the update on your store now. The developer team is working on it. :)
