### ISSUE TITLE
backoffice shops button  breaks

### ISSUE THREAD

**Issue by partnerscn** [PrestaShop/PrestaShop#27117]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![screencapture-caffefantino-it-fantinoadmin-index-php-sell-orders-2021-12-28-16_03_47](https://user-images.githubusercontent.com/47349081/147579582-43e53c75-0dd5-430f-bbc5-291548c96f66.jpg)

I upload prestashop 1.7.8.2 from 1.7.7.1. After the upload in the backoffice the button with the switch of the shops (multishop store actived) breaks just like in the image. Not in all pages but only in submenu pages (like orders > orders or catalogue>products, )

### Steps to reproduce

admin in backoffice

orders >orders

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

PHP 7.4 (ea-php74)

**Comment by marwachelly** [comment]
Hello,

Your issue is a browser cache. Could you please clear your cache from your browser

https://watch.screencastify.com/v/Fpx4n8jLLarnh1i0QACP 

The issue is fixed just when the browser cache is clear. 

Thanks,
