### ISSUE TITLE
BO - An exception is displayed in the BO > Customer view page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27119]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Customers > Customer details page > an exception is displayed
![image](https://user-images.githubusercontent.com/16067358/147589576-4439db40-4872-47ae-b311-89d78013aec4.png)

### Steps to reproduce

1. Go to BO > Customers > Customers page
2. View a customer 
3. See an error

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3, 7.4

**Comment by khouloudbelguith** [comment]
Ping @boubkerbribri

**Comment by PierreRambaud** [comment]
FYI, the issue is already fixed,  we are waiting for a new release: https://github.com/PrestaShop/blockwishlist/pull/143
