### ISSUE TITLE
BO - Wishlist - no green alert displayed when changing settings

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27128]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Blockwishlist module > Configuration page, there is no green alert when saving the settings
![image](https://user-images.githubusercontent.com/16067358/147651780-32f96b24-9089-446f-b62d-1c612add6d5c.png)

### Steps to reproduce

1. Login in the back-office. Go to the Blockwishlist module's settings page. Click on the Configuration" tab"
2. Change every wording for every language
3. Save
4. See an error: no green alert

### PrestaShop version(s) where the bug happened

1778, 1782, develop

### PHP version(s) where the bug happened

7.3, 7.4

### If your bug is related to a module, specify its name and its version

wishlist v2.0.1, v2.1.0

**Comment by NeOMakinG** [comment]
As it's not an ajax save, is the alert really showing on other similar pages?

Edit: Seems like I was thinking about toasts, but I was wrong
