### ISSUE TITLE
BO - An errors is displayed in the stats page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27120]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An error `Unknown error on line 821 in file /var/www/html/PrestaShop/classes/Hook.php
[16384] The hook "AdminStatsModules" is deprecated, please use "displayAdminStatsModules" instead in module "statsforecast".` is displayed in the BO > Stats page

### Steps to reproduce

1. Go to BO > Stats page
2. See error 
![image](https://user-images.githubusercontent.com/16067358/147589776-16c05175-0fa8-4892-8d0d-a8cd54086a3d.png)

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3, 7.4

**Comment by khouloudbelguith** [comment]
Ping @boubkerbribri

**Comment by PrestaEdit** [comment]
Due to this Pull request: https://github.com/PrestaShop/PrestaShop/pull/26267/files
This module need to be updated.
