### ISSUE TITLE
Instagram sharing

### ISSUE THREAD

**Issue by TGD001** [PrestaShop/PrestaShop#27123]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Hi there,
I' m trying to add to the PS_Sharebuttons.php (ver. 2.1.1) Instagram link but loading modified file it hangs.  (PS ver. 1.7.8.2)

Can someone expert upgrade it for me? 

Thank you very much

Piero

### Describe the solution you'd like

Adding Instagram share link to PS_Sharebuttons.php

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @TGD001 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon.

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Ping @PrestaShop/ux-team wdyt about something like that? 
### BO
![image](https://user-images.githubusercontent.com/23308427/147643023-3da2682a-6d4a-49a4-9b92-5ca4126cdfc6.png)
### FO
![image](https://user-images.githubusercontent.com/23308427/147643133-8f9f109e-53a5-47e5-9c97-65385e383ee0.png)

Thank you

**Comment by TGD001** [comment]
@hibatallahAouadni, thanks for answering.
Yes, this is exactly what I' ve in mind. Enclosed you'll find my ps_sharedbuttons.php modified, but it's doesent works and I' ve not idea how fix the issue.
Thanks again!

TGD
[PS_ShareB.zip](https://github.com/PrestaShop/PrestaShop/files/7788305/PS_ShareB.zip)

**Comment by pablomartin89** [comment]
Hi @TGD001  I see that you put this URL for instagram_sharing : 
'url' => 'https://www.instagram.com/share?url='.$sharing_url,

But, it seems that the link is not allowed for share content on Instagram.
I don't see this functionality on instagram or another website, so I don't know if that it's the correct way.

**Comment by TGD001** [comment]
hi @pmartin-webimpacto thank for answering.
I I wrote that url following the Instagram documentation, but I don't think that's the main problem, that string can obviously be modified at will. The problem is that if I try to load the modified module according to the PS procedure, it freezes and says that it cannot be loaded. Honestly this issue is beyond my knowledge so I have reported the issue here.

**Comment by pablomartin89** [comment]
@TGD001  I see in your code, you forgot a semicolon on line 68. 
For me it's working (I put the background on another color, because the instagram image it's white)
![image](https://user-images.githubusercontent.com/16488733/147871954-0e5b3bf1-dbea-4795-bc10-56feb172af21.png)

But, as I said, that link don't work, and it go to the 'share' instagram account.

If you make it work,  you can do a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/) . 
If not and it's important for you:  considere to hiring a specialist to hire you to develop the code and make it work.

Otherwise the Product Team will take it into consideration for future developments,  but as i said,  i don't know how to share a link on Instagram and I didn't see that functionality on any website.

**Comment by TGD001** [comment]
You are right @pmartin-webimpacto , I forgot a semicolon on line 68, thank you very much for reporting the bug. However, the instagram icon does not appear, can you suggest me how you did it? Furthermore, a consideration must be made on the use of instagram, I do not think it is possible to share products if you do not have an account. So we need to investigate the problem by trying to optimize sharing. Thanks again

**Comment by pablomartin89** [comment]
@TGD001  the image is loading, but the Instagram.svg it's white , so you can't see it with background: white.

You must to implement and load the SVG gray, and SVG blue for hover, like pinterest or facebook do at footer.scss:
![image](https://user-images.githubusercontent.com/16488733/147874067-4a1daf9d-a92e-4f27-9f04-706244be6097.png)

Instagram don't work like Twitter or Facebook,   and I don't see the utility or capability to share a link on Instagram stories or create a new posts on user account.
You can read more about that in this link: https://blog.hootsuite.com/how-to-create-social-media-buttons/#instagram 

So for me this feature request must to be closed.

**Comment by TGD001** [comment]
@pmartin-webimpacto ,
surely you are right. Thank you for support

**Comment by TGD001** [comment]
@pmartin-webimpacto  however, I was reflecting that it is not a bad idea to share the products of the catalog in the various Pinterest, Instagram etc. accounts. It would be enough to add a string field (as in the form follow us in social media) where to type the correct url of the account.

**Comment by prestascott** [comment]
Hello everyone,

Thank you @TGD001 for your request.

@hibatallahAouadni Your work is perfect as always, I have nothing to say! Let's make it simple and consistent and keep social media icons in the same color. :)

**Comment by prestascott** [comment]
Although, I don't think Instagram allows you to share articles, photos, or videos from other websites. I know that you can do it via the features in the app, but not with a sharing button.

The only way to share an article on Instagram is by copy/pasting the link to your Instagram story or your post. 

I'm sorry but I think your feature request won't really be useful except if what you want is to copy the link of the article from the sharing button and then paste it on Instagram?

**Comment by hibatallahAouadni** [comment]
Hello @TGD001 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
