### ISSUE TITLE
FO - Unable to add to cart of a product in FO when productcomments module installed

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#27129]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Add to cart button is blocked.
https://watch.screencastify.com/v/VxrDZ6O7zr2WBiwp2nGa

### Expected behavior

Add to cart must be functional

### Steps to reproduce

1. BO > Check `productcomments` module is installed in module manager
2. FO > select a product
3. Click on add to Cart
4. See error >> Unable to add to cart

### PrestaShop version(s) where the bug happened

develop

### If your bug is related to a module, specify its name and its version

productcomments

**Comment by PierreRambaud** [comment]
Be careful when you play with the develop branch, each modules you have in the modules directory will be installed, make it sure you properly clean this one before installing PrestaShop.
The productcomments module is not in our dependencies: https://github.com/PrestaShop/PrestaShop/blob/develop/composer.json

Afaik, this is not a major nor critical issue.
