### ISSUE TITLE
Wishlist default title will be changed in all languges not only the language selected

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27131]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Blockwishlist module configuration page, we change the "Wishlist default title" in English
If we create a new customer, in other languages, the wishlist default title will be displayed with the last change.
https://watch.screencastify.com/v/ewehqNSE3E2mVc7B3fgI

### Steps to reproduce

1. Login in the back-office. Go to the Blockwishlist module's settings page. Click on the Configuration" tab"
2. Change the "Wishlist default title"  in the English lanaguge
3. Save
4. Got to FO and select another language
5. create a new customer
6. Go to Home > Your account  > My wishlists list
7. See error

### PrestaShop version(s) where the bug happened

1.7.7.8, 1.7.8.2

### PHP version(s) where the bug happened

php7.2

### If your bug is related to a module, specify its name and its version

wishlist v2.0.1, v2.1.0

**Comment by NeOMakinG** [comment]
Backend issue, the API return only one name, should return multiple languages names so the JS can adapt it

**Comment by khouloudbelguith** [comment]
Hi,

I did not manage to reproduce the issue again with develop branch & blockwishlist v2.1.0.
I attached a screen record

https://user-images.githubusercontent.com/16067358/161525059-3f6c6708-6b26-4917-9c8c-a91526f7cc59.mp4

Thanks!
