### ISSUE TITLE
An error "There was an error while adding the product attributes" is displayed in the Product list page when adding a single product to wishlist after adding a product with combination

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27136]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the FO > Product list page > an error "There was an error while adding the product attributes" is displayed in the Product list page when adding a single product to the wishlist after adding a product with combination 
![image](https://user-images.githubusercontent.com/16067358/147659887-e42f0ffe-329f-46fb-8cea-874d4734ef0d.png)

### Expected behavior

No error displayed

### Steps to reproduce

1. Go to FO > Product list page (ps_featuredproduct / category) 
2. Click on the heart of a product with combination & add it to the list
3. Click on the heart of a single product (standard simple product / vector product / pack product)

https://watch.screencastify.com/v/7kJs8HT9ZVtobxticedr

### PrestaShop version(s) where the bug happened

1.7.7.8, 1.7.8.2, develop

### PHP version(s) where the bug happened

7.3, 7.4

### If your bug is related to a module, specify its name and its version

wishlist v2.0.1, v2.1.0

**Comment by NeOMakinG** [comment]
https://www.awesomescreenshot.com/video/6704875?key=1a7de790f217111f52ea17bd43b60222

Can't reproduce on the dev branch of the module

**Comment by khouloudbelguith** [comment]
Hi,

As discussed with @NeOMakinG,

This issue is reproduced only when the first product added to the wishlist has combinations, but the second one has no combinations, it could be a simple product, a vector or a pack.
![image](https://user-images.githubusercontent.com/16067358/148239780-0176e835-620c-4a73-9bfe-e40876e39356.png)

Thanks!
