### ISSUE TITLE
FO - An error message is displayed when add a comment in FO

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#27130]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An error message is displayed when add a comment in FO
![image](https://user-images.githubusercontent.com/92912932/147654130-367daca0-85ff-42a9-a146-67dbcb43f88e.png)
The comment is added in BO
![image](https://user-images.githubusercontent.com/92912932/147654215-9461e149-4d56-425e-8f59-a5ea858d0454.png)

### Expected behavior

No message error is displayed when add a new comment
PS1778, PS1782 & PS178x : OK
![image](https://user-images.githubusercontent.com/92912932/147654310-839ffefb-233c-482e-821c-2c732167fd4d.png)

### Steps to reproduce

1. FO > Select a product
2. Click on `Write you review` button
3. Put the `Title` and `Review`
4. Click on `Send`
5. See error >> An error message is displayed

### PrestaShop version(s) where the bug happened

develop

### If your bug is related to a module, specify its name and its version

productcomments

**Comment by atomiix** [comment]
@HanaRebaiQA this will be solved when the new version of productcomments & ps_shoppingcart will be released. In the meantime, if you disable the dev mode, this issue should not happen.

**Comment by Progi1984** [comment]
@HanaRebaiQA I suppose you are in the same page and you try to post two comments one after one.

Have you tried to post two comments in less of 30 seconds ?

If yes, the message is ok.
Because there is a configuration for not allowing two posts in less of a minimal time :

![image](https://user-images.githubusercontent.com/1533248/150768890-043b027f-fe4a-4c8e-9eed-d50e2e460878.png)

In :fr:, `Temps minimum entre 2 avis d'un même utilisateur`
In :gb:, `Minimum time between 2 reviews from the same user`

**Comment by HanaRebaiQA** [comment]
Hello @Progi1984 

It was a regression on the develop branch when adding the comment for the first time there is an error message in FO.
https://watch.screencastify.com/v/8ddeRWGdwAfsCE2Jjxpl

**Comment by Progi1984** [comment]
@HanaRebaiQA Are you connected ?

**Comment by HanaRebaiQA** [comment]
@Progi1984 Yes! The customer must be connected to can write his comment.

**Comment by Progi1984** [comment]
@HanaRebaiQA I try with the latest version of the `dev` branch of the module. 

My process :
* Connect as a customer on frontoffice
* FO > Select a product
* Click on Write you review button
* Put the Title and Review
* Click on Send
* No error

**Comment by HanaRebaiQA** [comment]
@Progi1984 So, maybe it was fixed in the new version of `productcomments` as mentioned by @atomiix in (https://github.com/PrestaShop/PrestaShop/issues/27130#issuecomment-1006440927)
!

**Comment by HanaRebaiQA** [comment]
Hello @atomiix  & @Progi1984 I checked again this issue with the new version of `productcomments` on dev branch. It's fixed!
![image](https://user-images.githubusercontent.com/92912932/153221168-9d47d1b2-ab64-44d7-8eeb-c670eebcf217.png)

https://user-images.githubusercontent.com/92912932/153221150-86433100-9944-4542-b040-4f4245ecdf00.mp4


So, i will close this issue.

Thank you!
