### ISSUE TITLE
FO - Product page - Wishlist - the heart is not automatically filled after increasing the product's quantity

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27135]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the FO > Product details page > after increasing the quantity and adding this product to the wishlist, the heart is not automatically filled
If we refresh the page, it will be ok
https://watch.screencastify.com/v/NRSjpJufZE6iNq0se9XX

PS1782 + wishlist v2.1.0 => NOK
Develop branch + wishlist v2.1.0 => NOK

PS1782 + wishlist v2.0.1 => ok
https://watch.screencastify.com/v/sOXGL7mPBFTjZMKOijWp

### Steps to reproduce

1. Browse through the catalog and open a product page. The product must be a single product with a lot of stock
2. Change the quantity to 5. Click on the heart
3. Select the default wishlist
4. The modal closes and the heart is **not** filled 

It is a regression module

### PrestaShop version(s) where the bug happened

1.7.8.2, develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

wishlist v2.1.0

**Comment by NeOMakinG** [comment]
https://www.awesomescreenshot.com/video/6704917?key=656d226d65ca03b02c9719d5861af93f

Not reproduced

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

I still reproduce the issue with develop branch & wishlist v2.1.0.
This issue is reproduced with a simple product or a pack product or a vector product

https://user-images.githubusercontent.com/16067358/161536423-6349e984-f847-4c0c-b369-c3ff4fdb8e1a.mp4

A product with combinations => OK

I will re-open the issue.

Thanks!
