### ISSUE TITLE
FO - Product page - an error is displayed "product.bundle.js:37 Error: GraphQL error:" when we try to remove a product with quantity > 1 from wishlist

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27140]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

FO - Product page - an error is displayed "product.bundle.js:37 Error: GraphQL error:" when we try to remove a product with quantity > 1 from the wishlist and cannot be rmoved

### Steps to reproduce

1. Browse through the catalog and open a product page. The product must be a single product with a lot of stock
2. Change the quantity to 5. Click on the heart
3. Select the default wishlist
4. Refresh the page
5. Increase the quantity to 5 
6. The heart is filled
7. Click on the heart again to remove the product from the wishlist
8. See error in the console & the product cannot be removed 
![image](https://user-images.githubusercontent.com/16067358/147681608-b450b91f-deb3-4637-a7f9-d14bc8f8e1e5.png)

### PrestaShop version(s) where the bug happened

1.7.7.8, 1.7.8.2, develop

### PHP version(s) where the bug happened

7.3, 7.4

### If your bug is related to a module, specify its name and its version

wishlist v2.0.1, v2.1.0

**Comment by NeOMakinG** [comment]
https://www.awesomescreenshot.com/video/6704847?key=7da2f27c8e3c45847e2540de52455a7b

Can't reproduce on the dev branch of the module

Closing the issue, if you reproduce in a way I don't know, don't hesitate to open

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

I still manage to reproduce the issue with the 178x branch & develop the branch using the wishlist v2.1.0
This issue is reproduced with a simple product, vector product, or pack product
I attached the screen record

https://user-images.githubusercontent.com/16067358/161574611-cacea66a-d73e-46c0-9d38-317ee4e52c61.mp4

Thanks!

**Comment by Progi1984** [comment]
@khouloudbelguith @PrestaShop/qa-functional  I just check now (with Chrome) with the `dev` branch and I haven't got the problem. Could you check it again, please ?

**Comment by AureRita** [comment]
Hi @Progi1984, 

I reproduced it on develop with Firefox and Google Chrome with private mode, on firefox and google without the private mode i didn't reproduce it

**Comment by hibatallahAouadni** [comment]
Hello @Progi1984 & @AureRita 

I didn't reproduce the issue with PS178x/develop and Chrome with/without, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/163197473-80a84449-aade-41c3-9275-628df74498ca.mp4

@khouloudbelguith could you please check if you still encounter the same issue? :pray: 
Thanks in advance!

**Comment by khouloudbelguith** [comment]
Hello :slightly_smiling_face: 

This issue is fixed with this PR: https://github.com/PrestaShop/blockwishlist/pull/169
It is ok with PS1785 & develop branch using this release: https://github.com/PrestaShop/blockwishlist/pull/143

https://user-images.githubusercontent.com/16067358/163399662-76d9bf46-a5ac-4580-8f41-7e4fa9031c2d.mp4


I will close the issue.

Thanks!
