### ISSUE TITLE
FO - New products page - Sort by Price is NOK

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27146]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the FO > New products page > when we try to sort with Price Asc or desc, we have incorrect results

### Steps to reproduce

1. Go to FO > New products page (we have more than 12 products)
2. Sort by price High to low or (low to high)
3. See error => only one product displayed 
![image](https://user-images.githubusercontent.com/16067358/147687246-ca985670-1e97-437f-b55f-250d6e1df7b8.png)
4. Click on Next
5. See error  
![image](https://user-images.githubusercontent.com/16067358/147687292-482fa209-a9c9-42df-b5e4-c288fc8026ee.png)

PS 1778 => ok

### PrestaShop version(s) where the bug happened

1.7.8.0, 1.7.8.2, develop

### PHP version(s) where the bug happened

7.3, 7.4

**Comment by Progi1984** [comment]
Fixed by @atomiix in #27374 and tested by @marwachelly
