### ISSUE TITLE
BO - ps_dataprivacy- Cannot uninstall dataprivacy module

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#27154]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Cannot uninstall dataprivacy module

Alert displayed with develop branch
![image](https://user-images.githubusercontent.com/89604350/147765091-4078dce6-1655-4f72-ad4a-3943c8c3d643.png)
 
Alert displayed with 1.7.8.2
![image](https://user-images.githubusercontent.com/89604350/147815767-0cb75b41-016d-4c23-8e26-2469d3ee792f.png)

### Screen record:
With PS 1.7.8.2 
https://watch.screencastify.com/v/2Uvgxf6uCFe77wT5EGah

with develop
https://watch.screencastify.com/v/Ij5CmL6dsypaL5hAbdBN

This issue can be caused by this PR 
 https://github.com/PrestaShop/ps_dataprivacy/pull/31

### Steps to reproduce

1- Go to back office -> Modules -> Module manger and search ps_dataprivacy
2- Click on uninstall" and confirm the deletion message by clicking on ok" 
3- see error 

The button configure still exist but the module is not any more installed. 

### PrestaShop version(s) where the bug happened

1.7.8.2 / develop

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

ps_dataprivacy v2.0.1

**Comment by PrestaEdit** [comment]
The PR you mention inside your issue is the solution, not the issue.
It's solve the error, due to misspelling on hooks name.

**Comment by marwachelly** [comment]
Hello @florine2623 ,

Could you please have a look ?

Many thanks,

**Comment by marwachelly** [comment]
Hello,

I didn't manage to reproduce the issue with 1.7.8.3. It seems that it was a permission issue.

Thanks,
