### ISSUE TITLE
Wrong usage of `actionDeliveryPriceByPrice` and `actionDeliveryPriceByWeight` in Carrier class

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#27158]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In Carrier class `checkDeliveryPriceByWeight` and `checkDeliveryPriceByPrice` should return a boolean.
`actionDeliveryPriceByPrice` or `actionDeliveryPriceByWeight` hooks returns shipping price.

If this hooks return 0 (free delivery) `checkDeliveryPriceByWeight` and `checkDeliveryPriceByPrice` return `false` (0) instead of `true`.
So carriers disapear front customer choice.

### Expected behavior

return true of false

### Steps to reproduce

1. Hook a module to actionDeliveryPriceByPrice 
2. Retun 0
3. See the carrier disapear ( the carrier has to be set like this : Out-of-range behavior : Disable carrier)

![image](https://user-images.githubusercontent.com/23308427/148362148-2cb4f28a-c986-4295-be7a-8a4d71c5af82.png)

### PrestaShop version(s) where the bug happened

1.7.x

### PHP version(s) where the bug happened

all

**Comment by hibatallahAouadni** [comment]
Hello @jf-viguier 

I didn't manage to reproduce the issue with PS1778, see the attached screen record below:

https://watch.screencastify.com/v/8gkJVY9fksMFDsJB1G0y

It seems that I missed a step, could you please check and feedback.
Thanks!

**Comment by jf-viguier** [comment]
The module has to return zero to the hook call

**Comment by hibatallahAouadni** [comment]
@jf-viguier did you check the attached screen record above? cause `ps_qualityassurance` returns zero to the hook call and yet in FO>checkout page, I didn't encounter any issues.

**Comment by jf-viguier** [comment]
@hibatallahAouadni hello

My bad, the carrier has to be set like this :
Out-of-range behavior : Disable carrier
![image](https://user-images.githubusercontent.com/16720275/147910862-4f95d2d3-64b2-4bca-9a2a-d84a65d20138.png)

**Comment by hibatallahAouadni** [comment]
Hello @jf-viguier 

Even when I disable carrier out-of-range, still can't reproduce the issue:

https://watch.screencastify.com/v/7q0Gr0F2xIqjc6RrnkEX

Please check and feedback.
Thanks!

**Comment by jf-viguier** [comment]
@hibatallahAouadni your carrier is set by weight and the hook by price : please hook to actionDeliveryPriceByWeight.
It seems that ranges has to be set to have the bug: it's ok in your test, I will had it in issue desc.

**Comment by hibatallahAouadni** [comment]
Hello @jf-viguier 

Thanks for the tip :rocket: 
I reproduce the issue with PS1782, see the attached screen record below:

https://watch.screencastify.com/v/rpvVAcB2ReYYFtB6ZmKl

I’ll add this to the debug backlog so that it’s fixed. Thanks for the PR :superhero: 

Thank you

**Comment by jf-viguier** [comment]
PR that added the hooks https://github.com/PrestaShop/PrestaShop/pull/2390
