### ISSUE TITLE
Improving sidebar menu UI

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/PrestaShop#27168]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

The sidebar menu in dashboard always has scrollbar even all sub menus are closed (screen height < 1080px)

![Screenshot 2022-01-02 at 18-36-17 Dashboard • develop](https://user-images.githubusercontent.com/85633460/147885894-0a4d9237-798f-4fd0-937e-dafc939a2ec6.png)

### Describe the solution you'd like

The category title can be redesigned to decrease the height of sidebar menu.

![Screenshot 2022-01-02 at 18-36-09 Dashboard • sidebar](https://user-images.githubusercontent.com/85633460/147885906-42b6e554-6888-4e7c-bbee-8213944c13a9.png)

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by matks** [comment]
Test

**Comment by matks** [comment]
Woups, sorry for the test message. GitHub behavior was weird for some time

**Comment by hibatallahAouadni** [comment]
Hello @mparvazi 

Thanks for the suggestion!
@NeOMakinG I think we can work on this improvement in this issue #23586 cause we already have UX approval, wdyt?

Thanks!

**Comment by NeOMakinG** [comment]
> Hello @mparvazi
> 
> Thanks for the suggestion! @NeOMakinG I think we can work on this improvement in this issue #23586 cause we already have UX approval, wdyt?
> 
> Thanks!

It's not UX approved, I think it's a misuse of the UX ✅  label

This issue is an improvement of the current menu implementation, while the other is a complete refactor which is not engaged atm

**Comment by mparvazi** [comment]
Hello @hibatallahAouadni 

I think this issue somehow can be considered as like as a bug for sidebar menu in legacy theme.
This issue is not a regression but it's really annoying!
So it can be fixed in next patch.

**Comment by NeOMakinG** [comment]
Yeah, I think @prestascott is the only one which can validate the change or not :)

**Comment by hibatallahAouadni** [comment]
Hello again,

Well then, the Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. 

Waiting for your PR :rocket: 

Thank you

**Comment by prestascott** [comment]
Hello everyone,

Thank you @mparvazi for your request. I know that the navigation drawer might seem a little bit old with its design, and it won't be bad if it gets a quick redesign haha.

What you've done is pretty nice and it saves space, but I think that we can do it more simply by removing the dividers.

Here is my design proposition:
![Navigation drawer](https://user-images.githubusercontent.com/54888056/148519230-007d6af4-0bb4-4863-8ad7-dd4ed1ab6a82.png)

Wdyt?

**Comment by mparvazi** [comment]
@prestascott Your design is much better and trendy!

I thought the divider line must be there.

**Comment by mparvazi** [comment]
@prestascott 

In RTL languages `text-transform: uppercase` doesn't make any effects for category titles, because there is not uppercase characters for RTL!

So if we remove divider lines, does it look good?

<img src="https://user-images.githubusercontent.com/85633460/148527118-5b6d89a3-d4a7-4eb7-841d-ba1650fb0ec2.png" width="200">

**Comment by prestascott** [comment]
Yep, it's fine to me :thumbsup:

**Comment by NeOMakinG** [comment]
@mparvazi do you want to take a look or should I take it right now? :)

**Comment by hibatallahAouadni** [comment]
@mparvazi I think it's not Great to have these Menu like that: 

![image](https://user-images.githubusercontent.com/23308427/148556789-3a29b399-8458-4065-b35a-55d5f3bbbeea.png)

I think it will be better if we make it **bold**, wdyt? cause like you said in RTL, `text-transform: uppercase` doesn't make any effects.

**Comment by mparvazi** [comment]
Hello @hibatallahAouadni 
I'm agree with you 👍
But in current font-face for RTL there is a mistake in Bold variant definition.
So using `font-weight: bold` doesn't work here!
Wait until this [PR](https://github.com/PrestaShop/PrestaShop/pull/26700) to merge.
I'll fix it.
Don't worry 😉
