### ISSUE TITLE
MX-Aguascalientes ISO 3166 code needs correction

### ISSUE THREAD

**Issue by rickygzz** [PrestaShop/PrestaShop#27165]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The current ISO 3166 code for Aguascalientes is AGU according to https://www.iso.org/obp/ui/#iso:code:3166:MX

But PrestaShops configures it as AGS.

### Expected behavior

Should show ISO Code AGU instead of AGS.

### Steps to reproduce

1. Optionally: freshly install PrestaShop
2. In BO, go to International / Locations / States tab
3. Filter by Country = Mexico

![image](https://user-images.githubusercontent.com/36200981/147864185-0a50f7c6-6f67-4567-907e-4dc5188ef4b5.png)

### PrestaShop version(s) where the bug happened

1.7.8.2 1.7.8.x develop

### PHP version(s) where the bug happened

N/A

### If your bug is related to a module, specify its name and its version

N/A

**Comment by hibatallahAouadni** [comment]
Hello @rickygzz 

I was able to reproduce the issue with PS1767, PS1778 and PS1782. I’ll add this to the debug backlog so that it’s fixed.
Thanks for your PR :rocket: 

PS: @Julievrz can you validate this issue :pray:  

Thank you

**Comment by Julievrz** [comment]
> Hello @rickygzz
> 
> I was able to reproduce the issue with PS1767, PS1778 and PS1782. I’ll add this to the debug backlog so that it’s fixed. Thanks for your PR 🚀
> 
> PS: @Julievrz can you validate this issue 🙏
> 
> Thank you

Yes,  I double-checked on iso.org and @rickygzz is right.
