### ISSUE TITLE
Move Classic theme to its own repository

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#27172]
The classic theme is AFL and therefore must be placed outside the core

####

- [ ] How are we going to integrate it back to the project (composer, git submodule...)
- [x] Create a dedicated repo

**Comment by mparvazi** [comment]
AFL
What does it stand for?

**Comment by matks** [comment]
https://opensource.org/licenses/AFL-3.0

**Comment by NeOMakinG** [comment]
@PierreRambaud let's do it soon? We will need to document the way to install the theme (with composer or any other solutions), it will be the exact same thing for the new theme

**Comment by eternoendless** [comment]
Composer already [provides support](https://github.com/composer/installers/blob/main/src/Composer/Installers/PrestashopInstaller.php) for PrestaShop themes. It's probably the best way to bundle the default theme IMO.

To avoid losing the theme's git history, I suggest we fork the PrestaShop repo, rename it to "classic", then delete & move files around as necessary.

On a side note, I have the feeling we're going to stumble upon some difficulties with development: 
* What best practices should we put in place to ensure that the nightly builds take the most recent version of the theme? 
* How do we test changes in the theme? 
* What will the QA have to do differently to perform manual tests? 
* How about functional tests, how will we keep them in sync?

**Comment by PierreRambaud** [comment]
> What best practices should we put in place to ensure that the nightly builds take the most recent version of the theme?

Do we really care about that with our modules? I don't think, we should do exactly the same thing and only play with Theme version.

> How do we test changes in the theme?

Same as for modules, we install a recent version by using Git & reinstall prestashop.

> How about functional tests, how will we keep them in sync?

Functional tests are not related to the theme, but sometimes we improve the theme to make it work, we do the same thing for modules.

**Comment by eternoendless** [comment]
I'm worried that we will be breaking the build more often. Currently, changes to the theme (at least some of them) are tested by CI when we send the pull request. After this, the changes will no longer be verified by CI until a new theme version has been released.

**Comment by kpodemski** [comment]
Can't we just change the license for the Classic? ;-) Work needed for the described situation has more cons than pros IMHO.

@PierreRambaud 

> Functional tests are not related to the theme, but sometimes we improve the theme to make it work, we do the same thing for modules.

how can functional tests not be related to the theme? 🤔  the theme is highly coupled to the PrestaShop core and its all core features, right? I think e2e campaigns tests adding to cart, etc. right? You even write:

> Functional tests are not related to the theme, **but sometimes we improve the theme to make it work**

**Comment by eternoendless** [comment]
> Can't we just change the license for the Classic? ;-)

Long story short: no.

We still need to move classic out regardless, because it's going to be replaced by another theme. The question perhaps should be more about whether it's practical to have the theme as an independent package just yet.

**Comment by Progi1984** [comment]
@eternoendless May be creating the repository should be a first step.

**Comment by eternoendless** [comment]
Repo moved: https://github.com/PrestaShop/classic-theme/
