### ISSUE TITLE
GDPR improve slow sql request

### ISSUE THREAD

**Issue by clotairer** [PrestaShop/PrestaShop#27178]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

[On this line of GDPRLog](https://github.com/PrestaShop/psgdpr/blob/7c79a99317f5be712f91933e753c60713fcc5fb5/classes/GDPRLog.php#L120) the module make a request without index. On our merchand we have more than 1.3M lines in this table. <br><br> Without index : 640ms ![image](https://user-images.githubusercontent.com/52157233/147964124-2746f1c3-9cd3-43d4-9c38-e2d747a99cc1.png)

### Expected behavior

With index : 2ms <br>![image](https://user-images.githubusercontent.com/52157233/147964254-ccfefccf-20e0-4369-899c-93ecd1b86254.png)

### Steps to reproduce

1. install the GDPR module
2. add lots of logs in the module
3. see the slow query

### PrestaShop version(s) where the bug happened

all

### PHP version(s) where the bug happened

all

### If your bug is related to a module, specify its name and its version

psgdpr

**Comment by marwachelly** [comment]
Hello,

With the provided steps I didn't manage to reproduce the issue. Could you please specifey how did you add a lot of logs? 
Did I miss some thing?
https://watch.screencastify.com/v/UtEv814EVobUylg9unjF

Many thanks,

**Comment by clotairer** [comment]
Several years on a big PrestaShop... with a flood of spam on ps_emailsubscription module form.
You need to have a command line to do this.
But if you see the PR, it's in progress.

**Comment by hibatallahAouadni** [comment]
Hello @clotairer 

Thanks for reporting this issue!
This issue is about improving GDPR performance, so I change it to a Feature :wink: 

Thanks for your PR :rocket: 
Ping @PrestaShop/prestashop-core-developers could you please check this issue :pray: 

Thanks!
