### ISSUE TITLE
Edit page console error. Uncaught TypeError: Cannot read properties of null (reading 'textContent')

### ISSUE THREAD

**Issue by ItchICen** [PrestaShop/PrestaShop#27173]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Error "Uncaught TypeError: Cannot read properties of null (reading 'textContent')" on cms_page_form.bundle.js?1.7.8.2:26 appears on console when edit a page. I try to modify the page text content, appears ok message but changes not saving.

### Expected behavior

I expected no error on console and that the modifications are saved as before.

### Steps to reproduce

1. Go to Design: Pages.
2. Click modify of any page.

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4.27

**Comment by hibatallahAouadni** [comment]
Hello @ItchICen 

I didn't manage to reproduce the issue with PS1782, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/147950116-d96b95af-ca1c-43ab-b3f8-c7c8ade90bef.png)

Did you override some files in the BO? Please check and feedback.
Thanks!

**Comment by ItchICen** [comment]
No, I didn't it, as far as i know. The last thing I did was a theme update (posted by its author on past December 20th).

In the back office information page, I have seen that "[admin-folder]/themes/new-theme/public/cms_page_form.bundle.js" appears on updated files list, but I don't see this file in the theme's changelog.

Thanks.

**Comment by ItchICen** [comment]
I have downloaded and replaced these two files:
- "[admin-folder]/themes/new-theme/public/cms_page_form.bundle.js"
- "js/admin/tinymce.inc.js"

And it works normal again. I still don't know why those files were modified, as I say according to the theme's changelog they weren't included on it. Apparently the source of the problem was on these files.

Sorry for the inconveniences.

**Comment by hibatallahAouadni** [comment]
@ItchICen Glad to hear 🎉 
Closing the issue!
