### ISSUE TITLE
Create 2 repositories for the V8 user documentation

### ISSUE THREAD

**Issue by Julievrz** [PrestaShop/PrestaShop#27189]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

As a contributor, I want to be able to contribute either via GitBook or via GitHub in order to adapt to my preferences and my technical level.

### Describe the solution you'd like

To synchronize the V8 user documentation on GitBook with GitHub, we need to:

- Create 2 repositories: 1 for the English documentation, and 1 for the French documentation. 
- Synchronize each repository with the corresponding space on GitBook.

Here is an example of a 1.7 user documentation repository:
https://github.com/PrestaShop/user-documentation-en

I suggest naming the new repositories as follow:

user-documentation-v8-en
user-documentation-v8-fr

If possible, it would be better to rename the 1.7 repositories to include the name of the version.

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by Progi1984** [comment]
Assigned to an admin : @eternoendless @matks or @PierreRambaud

**Comment by PierreRambaud** [comment]
Why we don't only have one repository with branches? Are we planning to create X repositories for X languages?

**Comment by Progi1984** [comment]
Affirmative. While we can't count contributions on different branches on Github, we must create a repository per language & version, as we discussed during the meeting about the User Documentation

**Comment by PierreRambaud** [comment]
https://github.com/PrestaShop/user-documentation-v8-en and https://github.com/PrestaShop/user-documentation-v8-fr
have been created

**Comment by PierreRambaud** [comment]
Just tell me if everything is ok for you.

**Comment by Julievrz** [comment]
It looks good to me. We'll just have to configure it and synchronize it with GitBook. Thanks.
