### ISSUE TITLE
setRoles() must be of the type array, null given

### ISSUE THREAD

**Issue by lthienard** [PrestaShop/PrestaShop#27181]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi All,

Why my Prod.log file is filled with the same error:

`CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to PrestaShopBundle\Security\Admin\Employee::setRoles() must be of the type array, null given, called in l/src/PrestaShopBundle/Security/Admin/EmployeeProvider.php on line 82" at l/src/PrestaShopBundle/Security/Admin/Employee.php line 155 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to PrestaShopBundle\\Security\\Admin\\Employee::setRoles() must be of the type array, null given, called in /src/PrestaShopBundle/Security/Admin/EmployeeProvider.php on line 82 at /src/PrestaShopBundle/Security/Admin/Employee.php:155)"} []`

### Steps to reproduce

1. Go to Order
2. Create Order
3. Add Product

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4

**Comment by marwachelly** [comment]
Hello,

Following the steps to reproduce the issue with a fresh install  and PS1.7.8.2 the Prod.log is not generated.
https://watch.screencastify.com/v/IzoN0hX2xntvQicZJSp5 

Could you please check and indicate the profile of the employee and check the permission granted? 
Is there any error in the Back office? 
Please add more info in the step to reproduce following this [link](https://build.prestashop.com/howtos/misc/how-to-create-bug-report/) .
Thanks,

**Comment by SharakPL** [comment]
I got this error when logged at the same time to both back & front office on the same e-mail address. Couldn't access translations on PS 1.7.8.6 because of that. I'll check later if it still happens on PS8...
