### ISSUE TITLE
www - non www multistore redirect to main store - htaccess file

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#27183]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

For multistore users it would be good if this code can be added to the htaccess file when this is generated by Prestashop.

RewriteEngine on
RewriteCond %{HTTP_HOST} !^www\.
RewriteRule ^(.*)$ http://www.%{HTTP_HOST}/$1 [R=301,L]

Since PS 1.6 every-time a new htaccess is created, store 2,3,4 etc will redirect to the mainstore when not entering www. in front of the url. This is confusing for customers and also for shop owners if they have not noticed the file was update.

### Expected behavior

I expect that when the htaccess file is updated, customer do not land on my mainstore domain. 

For example store 1 is www.prestashop.com
 
store 2 is www.prestashop2.com

when prestashop2.com ( so without the www ) you will be redirected to www.prestashop.com

What I would like is that when a new htaccess file is created, PS automatically adds this code:

RewriteEngine on
RewriteCond %{HTTP_HOST} !^www\.
RewriteRule ^(.*)$ http://www.%{HTTP_HOST}/$1 [R=301,L]

or 

solve it a different way.

### Steps to reproduce

create a new htaccess file

then go to the second store and visit the url without www 

You will be redirected to the main store.

### PrestaShop version(s) where the bug happened

all versions with multistore

### PHP version(s) where the bug happened

7.4

**Comment by pablomartin89** [comment]
@01park ,  I think this have to be done on server (apache/nginx) configuration manually, and not on Prestashop. 

For me it's not a bug,  and it's the expected behaviour. 

'www.domain.com'  it's a subdomain in the same way that you can have the Prestashop under the subdomain: 'shop.domain.com'

**Comment by marwachelly** [comment]
Hello,

This issue is similar to this [ticket](https://github.com/PrestaShop/PrestaShop/issues/20134) It wasn't reproducible as mentioned in the [comment](https://github.com/PrestaShop/PrestaShop/issues/20134#issuecomment-755210594). 
@PrestaShop/prestashop-core-developers Could you please check?

Many thanks,

**Comment by atomiix** [comment]
I agree with @pmartin-webimpacto, we should not force the `www` or at least not without a configuration

**Comment by Prestaworks** [comment]
It's possible to add the non www url to the second and third shop in shop urls in BO. If you do this, Prestashop will know what shop id to use and then there will be a correct redirect to the www url.
I don't think this is a bug, but a configuration issue.

**Comment by kpodemski** [comment]
I'm closing this issue since it is indeed a configuration error. You have to add URLs with and without www, you can also add URLs without www, it is all fully configurable.
