### ISSUE TITLE
autoupgrade, warning during db upgrade

### ISSUE THREAD

**Issue by Prestaworks** [PrestaShop/PrestaShop#27184]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

During the upgrade the following warning was displayed

```
INFO - === Step upgradeDb
WARNING -
            <div class="upgradeDbError">
            [WARNING] SQL 1.7.0.0
            1062 in INSERT INTO `ps_hook` (`name`, `title`, `description`, `position`) VALUES
  ('actionValidateCustomerAddressForm', 'Customer address form validation', 'This hook is called when a customer submit its address form', '1'),
  ('displayAfterCarrier', 'After carriers list', 'This hook is displayed after the carrier list in Front Office', '1'),
  ('displayCarrierExtraContent', 'Display additional content for a carrier (e.g pickup points)', 'This hook calls only the module related to the carrier, in order to add options when needed.', '1'),
  ('validateCustomerFormFields', 'Customer registration form validation', 'This hook is called to a module when it has sent additional fields with additionalCustomerFormFields', '1'),
  ('displayProductExtraContent', 'Display extra content on the product page', 'This hook expects ProductExtraContent instances, which will be properly displayed by the template on the product page.', '1'),
  ('displayNavFullWidth', 'Navigation', 'This hook displays full width navigation menu at the top of your pages', '1'),
  ('displayAfterBodyOpeningTag', 'Very top of pages', 'Use this hook for advertisement or modals you want to load first.', '1'),
  ('displayBeforeBodyClosingTag', 'Very bottom of pages', 'Use this hook for your modals or any content you want to load at the very end.', '1'): Duplicate entry 'actionValidateCustomerAddressForm' for key 'hook_name'</div>
```

It seemed like the hooks

* actionValidateCustomerAddressForm
* displayAfterBodyOpeningTag
* displayNavFullWidth

already exist

The SQL insert should probably be one by one or INSERT IGNORE. so that the ones that do not exist get created.

### Expected behavior

The upgrade should complete without warnings.

### Steps to reproduce

Install PS 1.6.0.9 
Install module "causesissues" to get the hooks created.
Upgrade to version 1.7.6.0 with php 5.6
[causeissuesmodule.zip](https://github.com/PrestaShop/PrestaShop/files/8861060/causeissuesmodule.zip)

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

autoupgrade 4.13.0

**Comment by marwachelly** [comment]
Hello,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of (https://github.com/PrestaShop/PrestaShop/issues/27087) 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks,

**Comment by marwachelly** [comment]
Duplicated to https://github.com/PrestaShop/PrestaShop/issues/27087.

**Comment by Prestaworks** [comment]
> Duplicated to #27087.

Did you link the wrong issue? 27087 is about php version and not SQL commands?

**Comment by eternoendless** [comment]
@marwachelly it's not the same issue

**Comment by eternoendless** [comment]
I agree that any hook can already be present in the database (added by a module for example), so changing the SQL statement to `INSERT IGNORE` should fix it.

@Prestaworks don't hesitate to send a PR to https://github.com/PrestaShop/autoupgrade/blob/dev/upgrade/sql/1.7.0.0.sql

**Comment by eternoendless** [comment]
Note that all subsequent sql upgrade files touching the hooks tables should be changed as well.

**Comment by Prestaworks** [comment]
@eternoendless How about adding "IGNORE" to the hook_alias inserts also?

**Comment by Prestaworks** [comment]
There are also some old ones, like 1.6.1.7.sql that has the same INSERT into hooks table. Should we leave it as is or change also?

**Comment by saulaski** [comment]
> I agree that any hook can already be present in the database (added by a module for example), so changing the SQL statement to `INSERT IGNORE` should fix it.

What about REPLACE to force changes from the upgrade, instead of keeping the previous obsolete values ?

**Comment by eternoendless** [comment]
> There are also some old ones, like 1.6.1.7.sql that has the same INSERT into hooks table. Should we leave it as is or change also?

Yes they should

> What about REPLACE to force changes from the upgrade, instead of keeping the previous obsolete values ?

Using `REPLACE` would change the auto_increment hook id, leaving any existing module hook subscription orphan. Not worth it since the only thing that would be updated is the hook description.

**Comment by sLorenzini** [comment]
hello @eternoendless, did you reproduce this issue? I see the "verified" label on this issue 😉 .
I can't reproduce it because I couldn't install the 1.6.0.9 version with different PHP versions (7.1 / 7.0 / 5.6 / 5.3).
I found this topic to try to resolve this installation: https://www.prestashop.com/forums/topic/338399-install-error-at-45-on-configure-shop-information-on-prestashop-1607/ but no success.

Thanks

**Comment by eternoendless** [comment]
Hi @sLorenzini 

I didn't need to reproduce it because I understand this can happen in a particular scenario. 

If a module subscribes to a nonexistent hook, PrestaShop will add it to the `ps_hook` table automatically. So you need a module that subscribes to a hook that doesn't exist yet in the core version you're testing, but that has been added in a more recent version.

Core upgrade scripts naïvely assume that new hooks added in a given version don't exist in the database at the moment of upgrade, and attempt to insert them without looking. When one of those hooks has been subscribed by a module before, it will be already present in DB. And since hooks are indexed by name, trying to INSERT a hook that already exists will result in failure.

All the `INSERT into ps_hook` statements in upgrade scripts must be transformed into `INSERT IGNORE` to avoid failure when any of the hooks exist already.

I hope this clarifies the scenario.

**Comment by florine2623** [comment]
Hello @Prestaworks & @eternoendless ,

I tried to reproduce the issue and I couldn't.
First, I installed PS 1.6.0.9, PHP 5.6, upgrade to 1.7.8.2 didn't go well. Here's the error :
<img width="1168" alt="Screenshot 2022-04-04 at 17 19 07" src="https://user-images.githubusercontent.com/16019289/161578976-d54d820c-ac4a-457a-88a4-6d3e33bdd7ca.png">
I cannot upgrade using the recommended version of PHP.

I tried to install PS 1.6.0.9 with PHP 7.1 as you did, and I have the following error :
<img width="698" alt="Screenshot 2022-04-04 at 17 32 38" src="https://user-images.githubusercontent.com/16019289/161579220-d38e51c8-59e7-4d1b-ab4f-28b195313cc1.png">

So I will take off the Verified label until someone reproduce the issue.
@PrestaShop/qa-functional , could someone try to reproduce the issue ?
Thanks !

**Comment by Prestaworks** [comment]
@florine2623 

![bild](https://user-images.githubusercontent.com/2902272/161695176-56a14ca2-5e25-43b5-a579-587cdb772b92.png)

You should be able to run the upgrade from 1.6.1.x to 1.7.1 on php 5.6 and be able to run the scripts involved. Remember that to get the issue, you need a module installed on 1.6.1 that creates on of the hooks before running the upgrade.

**Comment by sLorenzini** [comment]
hi @Prestaworks,

I can't reproduce this issue. I have got the same errors as @florine2623.
Here's are my tests:

- 1.6.0.9 version to 1.7.6.0 with php 5.6: shop installation is ok, upgrade success, I can't reproduce the bug
- 1.6.0.9 version to 1.7.8.2 with php 5.6: shop installation is ok, upgrade can't be done because of php version for 1.7.8.2
- 1.6.1.0 version to 1.7.6.0 with php 5.6: shop installation is ok, upgrade success, I can't reproduce the bug
- 1.6.0.9/1.6.1.0 to 1.7.8.2 or 1.7.8.6 with php 7.0/7.1: can't install the shop, same bug as @florine2623 

Can you give us more steps/details to test this issue please?

Thank you

**Comment by Prestaworks** [comment]
> hi @Prestaworks,
> 
> I can't reproduce this issue. I have got the same errors as @florine2623. Here's are my tests:
> 
>     * 1.6.0.9 version to 1.7.6.0 with php 5.6: shop installation is ok, upgrade success, I can't reproduce the bug
> 
>     * 1.6.0.9 version to 1.7.8.2 with php 5.6: shop installation is ok, upgrade can't be done because of php version for 1.7.8.2
> 
>     * 1.6.1.0 version to 1.7.6.0 with php 5.6: shop installation is ok, upgrade success, I can't reproduce the bug
> 
>     * 1.6.0.9/1.6.1.0 to 1.7.8.2 or 1.7.8.6 with php 7.0/7.1: can't install the shop, same bug as @florine2623
> 
> 
> Can you give us more steps/details to test this issue please?
> 
> Thank you

did you add a module also to create the hooks before upgrading?

**Comment by sLorenzini** [comment]
> > hi @Prestaworks,
> > I can't reproduce this issue. I have got the same errors as @florine2623. Here's are my tests:
> > ```
> > * 1.6.0.9 version to 1.7.6.0 with php 5.6: shop installation is ok, upgrade success, I can't reproduce the bug
> > 
> > * 1.6.0.9 version to 1.7.8.2 with php 5.6: shop installation is ok, upgrade can't be done because of php version for 1.7.8.2
> > 
> > * 1.6.1.0 version to 1.7.6.0 with php 5.6: shop installation is ok, upgrade success, I can't reproduce the bug
> > 
> > * 1.6.0.9/1.6.1.0 to 1.7.8.2 or 1.7.8.6 with php 7.0/7.1: can't install the shop, same bug as @florine2623
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can you give us more steps/details to test this issue please?
> > Thank you
> 
> did you add a module also to create the hooks before upgrading?

hello @Prestaworks,

No I didn't add a module to create the hooks.

In the issue's description, "Steps to reproduce" part, there's only one step:  Upgrade a 1.6.0.9 shop to 1.7.8.2.
I don't see in the issue an information about a module to add. We have tried to upgrade with different versions of PrestaShop without success.

Could you please: 
- describe us all of detailed steps to reproduce your issue?
- provide us a module to add or a name of this one?

Thank you 😃

**Comment by Prestaworks** [comment]
> > > hi @Prestaworks,
> > > I can't reproduce this issue. I have got the same errors as @florine2623. Here's are my tests:
> > > ```
> > > * 1.6.0.9 version to 1.7.6.0 with php 5.6: shop installation is ok, upgrade success, I can't reproduce the bug
> > > 
> > > * 1.6.0.9 version to 1.7.8.2 with php 5.6: shop installation is ok, upgrade can't be done because of php version for 1.7.8.2
> > > 
> > > * 1.6.1.0 version to 1.7.6.0 with php 5.6: shop installation is ok, upgrade success, I can't reproduce the bug
> > > 
> > > * 1.6.0.9/1.6.1.0 to 1.7.8.2 or 1.7.8.6 with php 7.0/7.1: can't install the shop, same bug as @florine2623
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Can you give us more steps/details to test this issue please?
> > > Thank you
> > 
> > 
> > did you add a module also to create the hooks before upgrading?
> 
> hello @Prestaworks,
> 
> No I didn't add a module to create the hooks.
> 
> In the issue's description, "Steps to reproduce" part, there's only one step: Upgrade a 1.6.0.9 shop to 1.7.8.2. I don't see in the issue an information about a module to add. We have tried to upgrade with different versions of PrestaShop without success.
> 
> Could you please:
> 
>     * describe us all of detailed steps to reproduce your issue?
> 
>     * provide us a module to add or a name of this one?
> 
> 
> Thank you 😃
[causeissuesmodule.zip](https://github.com/PrestaShop/PrestaShop/files/8861048/causeissuesmodule.zip)

Hi,

Sorry, I will update the steps.

Install PS 1.6.0.9 
Install module "causesissues" to get the hooks created.
Upgrade to version 1.7.6.0 with php 5.6

**Comment by sLorenzini** [comment]
hello @Prestaworks,

Thank you for the update of the steps.
I tried to reproduce with those steps, but without success again:

- install ps 1609 in php 5.6
- install "causesissues" module. only the displayNavFullWidth hook was displayed 
![Capture d’écran 2022-06-10 à 11 19 32](https://user-images.githubusercontent.com/2854834/173039256-052766d6-bec1-4032-b90e-9a4bd4078012.png)
- install "autoupgrade" module with 4.13.0 version (as in your description). tested also with the last version of the module, 4.14.1
- upgrade to 1.7.6.0 or 1.7.6.9
- no warning, upgrade ok but can't access to the BO after. FO is in maintenance mode.

@PrestaShop/qa-team, is someone can test please 🙏? 

Thank you

**Comment by Prestaworks** [comment]
> hello @Prestaworks,
> 
> Thank you for the update of the steps. I tried to reproduce with those steps, but without success again:
> 
>     * install ps 1609 in php 5.6
> 
>     * install "causesissues" module. only the displayNavFullWidth hook was displayed
>       ![Capture d’écran 2022-06-10 à 11 19 32](https://user-images.githubusercontent.com/2854834/173039256-052766d6-bec1-4032-b90e-9a4bd4078012.png)
> 
>     * install "autoupgrade" module with 4.13.0 version (as in your description). tested also with the last version of the module, 4.14.1
> 
>     * upgrade to 1.7.6.0 or 1.7.6.9
> 
>     * no warning, upgrade ok but can't access to the BO after. FO is in maintenance mode.
> 
> 
> @PrestaShop/qa-team, is someone can test please 🙏?
> 
> Thank you

Ddi you not get any warning in the upgrade logs?

**Comment by sLorenzini** [comment]
> > hello @Prestaworks,
> > Thank you for the update of the steps. I tried to reproduce with those steps, but without success again:
> > ```
> > * install ps 1609 in php 5.6
> > 
> > * install "causesissues" module. only the displayNavFullWidth hook was displayed
> >   ![Capture d’écran 2022-06-10 à 11 19 32](https://user-images.githubusercontent.com/2854834/173039256-052766d6-bec1-4032-b90e-9a4bd4078012.png)
> > 
> > * install "autoupgrade" module with 4.13.0 version (as in your description). tested also with the last version of the module, 4.14.1
> > 
> > * upgrade to 1.7.6.0 or 1.7.6.9
> > 
> > * no warning, upgrade ok but can't access to the BO after. FO is in maintenance mode.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @PrestaShop/qa-team, is someone can test please 🙏?
> > Thank you
> 
> Ddi you not get any warning in the upgrade logs?


No warning at all...

**Comment by Prestaworks** [comment]
it's also odd that the latest version 4.1.14 is working for you since it's not php5 compliant.
![bild](https://user-images.githubusercontent.com/2902272/173056486-982c5f71-7eed-49ec-bd68-de33ac850e5f.png)

**Comment by Prestaworks** [comment]
another way to verify the issue, would be to install 1.6.0.9
check that displayNavFullWidth and displayProductExtraContent is missing
`select * from ps_hook where name='displayNavFullWidth' OR name='displayProductExtraContent'`

then
install the "causesissue" module.
check that displayNavFullWidth is now created.
`select * from ps_hook where name='displayNavFullWidth' OR name='displayProductExtraContent'`

upgrade to 1.7.6.0 or later
then check that both hooks are created
`select * from ps_hook where name='displayNavFullWidth' OR name='displayProductExtraContent'`

you should see both hooks in your db since the insert that cause the issue inserts lots of hooks. 

also, are you upgrading using some kind of automatic upgrade test or manual upgrades from cli or BO?

**Comment by sLorenzini** [comment]
> another way to verify the issue, would be to install 1.6.0.9 check that displayNavFullWidth and displayProductExtraContent is missing `select * from ps_hook where name='displayNavFullWidth' OR name='displayProductExtraContent'`
> 
> then install the "causesissue" module. check that displayNavFullWidth is now created. `select * from ps_hook where name='displayNavFullWidth' OR name='displayProductExtraContent'`
> 
> upgrade to 1.7.6.0 or later then check that both hooks are created `select * from ps_hook where name='displayNavFullWidth' OR name='displayProductExtraContent'`
> 
> you should see both hooks in your db since the insert that cause the issue inserts lots of hooks.
> 
> also, are you upgrading using some kind of automatic upgrade test or manual upgrades from cli or BO?

Thank you for all the details.

I use manual upgrades from BO. Maybe also my environment is the problem 😉 
It is too technical for me with this method. @core-developers can someone please try to reproduce the issue 🙏?

Thanks

**Comment by eternoendless** [comment]
IMO this doesn't need to be reproduced because the theoretical cause is known: https://github.com/PrestaShop/PrestaShop/issues/27184#issuecomment-1080878621

1. A module running in PrestaShop version A subscribes to a hook that doesn't exist yet. The hook is automatically created and registered by PrestaShop in `ps_hook`.
2. PrestaShop is upgraded to version C. If either version C or any intermediate version B creates a hook in `ps_hook` with the same name as in step 1 via INSERT without adding the IGNORE clause, then the script will raise an error.

Solution: change INSERT to INSERT IGNORE for all upgrade scripts concerning hooks.
