### ISSUE TITLE
BO - Cannot edit specific combinations

### ISSUE THREAD

**Issue by Guisardo** [PrestaShop/PrestaShop#27180]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When try to edit a combination using the edition pen from the actions column, I see the url change the hash part but the BO dont show any of the combination forms do the editions:
![image](https://user-images.githubusercontent.com/11792675/147981468-2e6661aa-c4b6-422b-b66c-c3f84e154aa5.png)

### Expected behavior

When clicking at the pen to edit a combination, the fields of the combination should be displayed and the user should be allowed to edit the fields and save the changes.

### Steps to reproduce

(with the experimental features disabled)
1. Go to the products section of the BO
2. Go to the details page of a specific product with combinations
3. Go to the combinations section
4. Click on the pen icon of a combination
You will not be able to edit the combination

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.3.27

**Comment by Guisardo** [comment]
The issue seems to be related to the fact that a JS error is preventing the page to correctly load. The browser complains about  'rightSidebar' not being defined at this line:
https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/admin-dev/themes/default/js/bundle/product/form.js#L44

I'd fixed locally by adding this code at beginning of the forms.js:
```
if (typeof (rightSidebar) === 'undefined') {
  const rightSidebar = (function () {
    return {
      init() {
        $('.btn-sidebar').on('click', function initLoadQuickNav() {
          $('div.right-sidebar-flex').removeClass('col-lg-12').addClass('col-lg-9');

          /** Lazy load of sidebar */
          const url = $(this).data('url');
          const target = $(this).data('target');

          if (url) {
            rightSidebar.loadQuickNav(url, target);
          }
        });
        $(document).on('hide.bs.sidebar', () => {
          $('div.right-sidebar-flex').removeClass('col-lg-9').addClass('col-lg-12');
        });
      },
      loadQuickNav(url, target) {
        /** Loads inner HTML in the sidebar container */
        $(target).load(url, function () {
          $(this).removeAttr('data-url');
          $('ul.pagination > li > a[href]', this).on('click', (e) => {
            e.preventDefault();
            rightSidebar.navigationChange($(e.target).attr('href'), $(target));
          });
          $('ul.pagination > li > input[name="paginator_jump_page"]', this).on('keyup', function (e) {
            if (e.which === 13) { // ENTER
              e.preventDefault();
              const val = parseInt($(e.target).val(), 10);
              const limit = $(e.target).attr('pslimit');
              const newUrl = $(this).attr('psurl').replace(/999999/, (val - 1) * limit);
              rightSidebar.navigationChange(newUrl, $(target));
            }
          });
        });
      },
      navigationChange(url, sidebar) {
        rightSidebar.loadQuickNav(url, sidebar);
      },
    };
  }());
}
```

I didn't put that in a PR because the code looks like a hack and not a correct fix. I'm not sure way that is not defined before the forms.js is loaded.

**Comment by marwachelly** [comment]
Hello,

Thank you for your report. With the provided information I didn't manage to reproduce the issue:
PS1.7.8.2 and PHP7.3
https://watch.screencastify.com/v/ALXkqHFLEjefvQKqV3AP
Did I miss some thing?
Could you please add more details in the step to reproduce (language used, debug mode state, is it multistore case...)

Thanks,

**Comment by Guisardo** [comment]
Hi @marwachelly, thanks for the support!

I just fount out that the problem was caused by the PageSpeed mod on the server. PageSpeed bundles the javascript for delivery optimization but that is not compatible with the new versions of file https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/default/js/bundle/default.js
The incompatibility arises because an incorrect scope of a javascript declaration.
That file loads the global rightSidebar using "const" but, as explained here: https://www.freecodecamp.org/news/var-let-and-const-whats-the-difference/#const , "const" is block scoped. If rightSidebaris going to be globally used, "var" should be used instead (https://www.freecodecamp.org/news/var-let-and-const-whats-the-difference/#var). Although global variables are discouraged, the rightSidebar is designed as a global variables, changing that behavior will require a refactor of the code....
rightSidebar was declared using "var" a few months ago. The change was introduced at this huge eslint PR: https://github.com/PrestaShop/PrestaShop/pull/22999/files#diff-652322c22d05461f6ff2962e23cceb8958b2d7cabbc2e2cc0485aefdd827eb13L21
Please, consider a rollback to "var" until a refactor of that code is applied. I could create that PR if you agree.
Best,

**Comment by hibatallahAouadni** [comment]
Hello @Guisardo 

I see what you mean, but could you please answer these questions :pray:

- Did you use the multistore context? if so, check this issue #9664
- Did you override some files concern products or combinations?
- Did you use any third module that may have an impact on combinations?

Please check and feedback.

Thanks!

**Comment by Guisardo** [comment]
Hi @hibatallahAouadni
Sure, the answers for that are:
* No multistore is set on my store
* No overrides at the products nor at combinations files
* No modules installed that are related to the combinations (Although the PageSpeed is technically a Google module but for all that is under the Apache server https://developers.google.com/speed/pagespeed/module)

Thanks for the support!
Best

**Comment by hibatallahAouadni** [comment]
Hello @Guisardo 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server or configuration problem.

https://user-images.githubusercontent.com/23308427/149201130-f6fba9dd-01c5-49f8-b5f8-1fab9592f6c4.mp4

We will close this issue.

Thanks!

**Comment by Guisardo** [comment]
Thanks for the support @hibatallahAouadni , as I mention before, the problem is not visible within Prestashop itself, the problem arises by "the PageSpeed mod on the Apache server".
The problem is an invalid scope definition at a javascript variable. Modern browsers may ignore those imperfections but it causes issues when bundling Prestashop in more complex environments.

**Comment by hibatallahAouadni** [comment]
@Guisardo well, it's hard to reproduce the issue as it depends a lot of specifications on the server configuration side :confused:
