### ISSUE TITLE
[CORE] The redirect() function in Tools.php doesn't check PS_SSL_ENABLED

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/PrestaShop#27190]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The `redirect()` function in `Tools.php` doesn't check `PS_SSL_ENABLED` and redirecting link will be created with `http`
So it may cause two errors:
1. **ERR_TOO_MANY_REDIRECTS**
1.1. When SSL configuration on server changed or not set correctly (caching or htaccess). In this case redirect URL should be created with `https`
2. **500 Internal Server Error**
2.1. When a module try to send a request with `http` (to external site), but shop works with `https`. In this case the Security Controller should be display a message that the request is invalid and may cause a server error.

These errors originally doesn't related to PS and it's related to misconfiguration on server and wrong usage in third party modules.

### Expected behavior

Adding a condition for `PS_SSL_ENABLED` before redirecting.

### Steps to reproduce

classes/Tools.php

`public static function redirect()`

### PrestaShop version(s) where the bug happened

8.0

**Comment by marwachelly** [comment]
Hello,

Thanks for your report. Could you please provide more details and clarify steps to reproduce ?

Many thanks,

**Comment by mparvazi** [comment]
Hello @marwachelly 

It's hard to reproduce this problem, because it's not a problem inside PS!

It happens for some third-party modules (external calls) or sometimes like this [issue](https://github.com/PrestaShop/PrestaShop/issues/27177)

So I thought it would be fine if `Tools.php` controls wrong calls of link redirection.
Because most users thinks these problems (in some cases) are related to PS, but it's not true:
- ERR_TOO_MANY_REDIRECTS
- 500 Internal Server Error

Maybe I've selected wrong category, and this issue isn't a bug and can be considered as an improvement 🤔

**Comment by mparvazi** [comment]
<img src="https://user-images.githubusercontent.com/85633460/148111059-3f9326b4-5038-4f15-98ca-a795e32df6fb.png" width="550">
