### ISSUE TITLE
BO - An error is displayed in the Stats page - Best-selling products module

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#27196]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This error is displayed in the `Stats` page related to `statsbestproducts` module : 
![image](https://user-images.githubusercontent.com/92912932/148083634-b6b203b9-2ff0-49c4-b666-2f70b3bf19ea.png)

### Expected behavior

No error is displayed

### Steps to reproduce

1. BO > Stats
2. Click on `Best-selling products `

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

statsbestproducts

**Comment by PrestaEdit** [comment]
PR available and merged: https://github.com/PrestaShop/statsbestproducts/pull/12

**Comment by Progi1984** [comment]
@HanaRebaiQA  Have you got always the problem with the `dev` branch of the module ?

**Comment by HanaRebaiQA** [comment]
Hello @Progi1984 

I have verified the issue with the `dev` branch on `develop`. It's fixed!
https://watch.screencastify.com/v/8AyoIyikbuWqz5RtEMx0
![image](https://user-images.githubusercontent.com/92912932/151535682-68dd73b9-391c-4334-9b9e-474608bdf9b0.png)

Thank you @PrestaEdit & @Progi1984 !
