### ISSUE TITLE
BO - An error is displayed in the Stats page - Carrier distribution module

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#27197]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This error is displayed in the `Stats` page related to `statscarrier` module : 
![image](https://user-images.githubusercontent.com/92912932/148084198-6fd23a3b-cf62-44d0-bbbf-4caec548befd.png)

### Expected behavior

No error is displayed

### Steps to reproduce

1. BO > Stats
2. Click on `Carrier distribution`

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

statscarrier

**Comment by PrestaEdit** [comment]
PR available and merged: https://github.com/PrestaShop/statscarrier/pull/10

**Comment by Progi1984** [comment]
@HanaRebaiQA  Have you got always the problem with the `dev` branch of the module ?

**Comment by HanaRebaiQA** [comment]
Hello @Progi1984 

I have verified the issue with the `dev` branch on `develop`. It's fixed!
https://watch.screencastify.com/v/NrkxmfvkmsawXr1qZVw8
![image](https://user-images.githubusercontent.com/92912932/151536306-862712c9-ca2c-4b38-9daf-aa92796c9f68.png)

Thank you @PrestaEdit & @Progi1984 !
