### ISSUE TITLE
BO - An error is displayed in the Stats page - Best suppliers module

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#27194]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This error is displayed in the `Stats` page related to `statsbestsuppliers` module : 
![image](https://user-images.githubusercontent.com/92912932/148082313-439e5389-c70b-4caa-a525-b6241b37659f.png)

### Expected behavior

No error is displayed

### Steps to reproduce

1. BO > Stats
2. Click on `Best suppliers `

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

statsbestsuppliers

**Comment by PrestaEdit** [comment]
PR available and merged: https://github.com/PrestaShop/statsbestsuppliers/pull/11

**Comment by Progi1984** [comment]
@HanaRebaiQA  Have you got always the problem with the `dev` branch of the module ?

**Comment by HanaRebaiQA** [comment]
Hello @Progi1984 

I have verified the issue with the `dev` branch on `develop`. It's fixed!
https://watch.screencastify.com/v/SSnS06MGSTVibL4cwsrw
![image](https://user-images.githubusercontent.com/92912932/151534319-f012e481-1f56-45af-b54a-017ec3f917ec.png)

Thank you @PrestaEdit & @Progi1984 !
