### ISSUE TITLE
BO - An error is displayed in the Stats page - Catalog evaluation module

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#27198]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This error is displayed in the `Stats` page related to `statscheckup` module : 
![image](https://user-images.githubusercontent.com/92912932/148085368-820f4ddd-1e3e-4072-9118-944b85e9a101.png)

### Expected behavior

No error is displayed

### Steps to reproduce

1. BO > Stats
2. Click on `Catalog evaluation`

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

statscheckup

**Comment by PrestaEdit** [comment]
PR available and merged: https://github.com/PrestaShop/statscheckup/pull/19

**Comment by Progi1984** [comment]
@HanaRebaiQA Have you got always the problem with the `dev` branch of the module ?

**Comment by HanaRebaiQA** [comment]
Hello @Progi1984 

I have verified the issue with the `dev` branch on `develop`. It's fixed!
https://watch.screencastify.com/v/MXlbbLeFppKji61eItqB
![image](https://user-images.githubusercontent.com/92912932/151537113-01ed06c7-2960-4fed-9b96-7702ded740a5.png)

Thank you @PrestaEdit & @Progi1984 !
