### ISSUE TITLE
BO - An error is displayed in the Stats page - Best vouchers module

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#27195]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This error is displayed in the `Stats` page related to `statsbestvouchers` module : 
![image](https://user-images.githubusercontent.com/92912932/148083122-b2daf6ec-db38-48d6-8bb0-80450844f95a.png)

### Expected behavior

No error is displayed

### Steps to reproduce

1. BO > Stats
2. Click on `Best vouchers ` 

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

statsbestvouchers

**Comment by PrestaEdit** [comment]
PR available and merged; https://github.com/PrestaShop/statsbestvouchers/pull/12

**Comment by Progi1984** [comment]
@HanaRebaiQA  Have you got always the problem with the `dev` branch of the module ?

**Comment by HanaRebaiQA** [comment]
Hello @Progi1984 

I have verified the issue with the `dev` branch on `develop`. It's fixed!
https://watch.screencastify.com/v/x8WChwqWTmGdyUL6qftb
![image](https://user-images.githubusercontent.com/92912932/151532368-d1e58ff0-a3df-49f1-bd4f-c65e82d508ad.png)

Thank you @PrestaEdit & @Progi1984 !
