### ISSUE TITLE
BO - An error is displayed in the stats page - statsstock module

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27199]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Stats > the module statsstock is nok with develop branch
![image](https://user-images.githubusercontent.com/16067358/148096015-016abd03-d74f-4784-8b9c-caa24ead90a3.png)

We have an error `Unknown error on line 821 in file /var/www/html/develop/classes/Hook.php
[16384] The hook "AdminStatsModules" is deprecated, please use "displayAdminStatsModules" instead in module "statsstock".`

### Steps to reproduce

Go to BO > Stats page
Click on Available quantities
See error

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

Available quantities v2.0.0

**Comment by PrestaEdit** [comment]
PR available: https://github.com/PrestaShop/statsstock/pull/18

**Comment by Progi1984** [comment]
@khouloudbelguith   Have you got always the problem with the `dev` branch of the module ?

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

Sorry for the delay.
Yes, it is fixed with the `dev` branch (statsstock v2.0.1)

https://user-images.githubusercontent.com/16067358/152536165-1b008391-14f9-4297-9d95-08f82c11085d.mp4

Thanks!
