### ISSUE TITLE
FO - Order confirmation page - ps_checkpayment is NOK

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27204]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The ps_checkpayment module is NOK with the develop branch
![image](https://user-images.githubusercontent.com/16067358/148098415-4b01ad6a-4d2d-4e55-a3f3-b1242dc7caaa.png)

### Steps to reproduce

1. Go to FO > create an order using `ps_checkpayment` payment
2. see error

![image](https://user-images.githubusercontent.com/16067358/148098714-d9de34e1-f096-477e-a54c-326f2453f46a.png)

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

Payments by check v2.0.5

**Comment by Hlavtox** [comment]
@MatShir Hi Mateus, what would you think about deprecating this module? We could loose some maintanace burden. I have never seen any store accepting this method of payment in my life... :-)

Update: GF said they apparently still use it in US? 🧐

**Comment by MatShir** [comment]
> Update: GF said they apparently still use it in US? 🧐

And some small B2B business still use check also, 
but the module usually requires a low maintenance and helps to detect issue in the checkout process
