### ISSUE TITLE
BO - An error is displayed in the stats page - statsbestcustomers module

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27202]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > stats page, the module statsbestcustomers is NOK with develop branch
![image](https://user-images.githubusercontent.com/16067358/148097693-13ae4443-29cb-4c86-ad21-b1b50c1665f9.png)
An error is displayed
`Unknown error on line 821 in file /var/www/html/develop/classes/Hook.php
[16384] The hook "AdminStatsModules" is deprecated, please use "displayAdminStatsModules" instead in module "statsbestcustomers".`

### Steps to reproduce

1. Go to BO > Stats page
2. Click on Best customers
3. See error

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

Best customers v2.0.3

**Comment by PrestaEdit** [comment]
PR available: https://github.com/PrestaShop/statsbestcustomers/pull/23

**Comment by Progi1984** [comment]
@khouloudbelguith  Have you got always the problem with the `dev` branch of the module ?

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

Yes, It is fixed with the dev branch (statsbestcustomers v2.0.4)

https://user-images.githubusercontent.com/16067358/152534590-646d5933-1661-47e5-b086-c9ce9bf88865.mp4

Thanks!
