### ISSUE TITLE
BO - An error is displayed in the stats page - Newsletter module

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#27203]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Stats > the module statsnewsletter is NOK with develop branch

![image](https://user-images.githubusercontent.com/23308427/148097634-ed0bb0a2-d4e3-412b-af80-f195310abbf1.png)

An error is displayed:
```
Unknown error on line 821 in file /projects/PrestaShop/classes/Hook.php
[16384] The hook "AdminStatsModules" is deprecated, please use "displayAdminStatsModules" instead in module "statsnewsletter".
```

### Expected behavior

No error displayed

### Steps to reproduce

1. Go to BO > Stats page
2. Click on the "Newsletter"
3. See error

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

statsnewsletter

**Comment by PrestaEdit** [comment]
PR available and merged: https://github.com/PrestaShop/statsnewsletter/pull/11

**Comment by hibatallahAouadni** [comment]
@PrestaEdit thanks for the tip :wink: and the PR :rocket:
