### ISSUE TITLE
Refacto CountryId and CustomerId VOs

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#27205]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

As we noticed in this PR https://github.com/PrestaShop/PrestaShop/pull/25742 we should have a `NoCountryId` and a `NoCustomerId` VO to handle the fact that we unassociate them

It has been implement for many other VOs, however it was not doable in said PR because it was already very big and CountryId and CustomerId already accept 0 as input values, so it requires to refacto all their uses

### Describe the solution you'd like

- `CountryId` and `CustomerId` VOs don't accept 0 as input value anymore and trigger exception when such input is used in constructor
- we need a `NoCountryId` and `NoCustomerId` VO to handle the case for 0 value
- we need common interfaces for related VOs

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @jolelievre 

Is your issue related to this one #25946?
Please check and feedback.

Thanks!

**Comment by jolelievre** [comment]
Yes @hibatallahAouadni you're right, thanks.

Duplicate of #25946

**Comment by hibatallahAouadni** [comment]
Duplicate of #25946
