### ISSUE TITLE
BO - An error is displayed in the stats page - statsbestcategories module

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27201]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Stats page, the module statsbestcategories is NOK with the develop branch
![image](https://user-images.githubusercontent.com/16067358/148097168-28e3dea9-b0eb-45ff-bae9-a294c2c53e56.png)
An error is displayed
 `Unknown error on line 821 in file /var/www/html/develop/classes/Hook.php
[16384] The hook "AdminStatsModules" is deprecated, please use "displayAdminStatsModules" instead in module "statsbestcategories".`

### Steps to reproduce

1. Go to BO > Stats page
2. Click on Best categories
3. See an error

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

Best categories v2.0.0

**Comment by PrestaEdit** [comment]
PR available and merged: https://github.com/PrestaShop/statsbestcategories/pull/13

**Comment by Progi1984** [comment]
@khouloudbelguith  Have you got always the problem with the `dev` branch of the module ?

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

Sorry for the delay.
Yes, it is fixed with the `dev` branch.

https://user-images.githubusercontent.com/16067358/152535137-c1760a5b-3233-41ef-8de1-8f1fe5a30d4c.mp4

Thanks!
