### ISSUE TITLE
BO - An error is displayed in the stats page - `statspersonalinfos` module

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#27208]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Stats > the module `statspersonalinfos` is NOK with develop branch

An error is displayed:
```
Unknown error on line 821 in file /projects/PrestaShop/classes/Hook.php
[16384] The hook "AdminStatsModules" is deprecated, please use "displayAdminStatsModules" instead in module "statspersonalinfos".
```

### Expected behavior

No error is displayed

### Steps to reproduce

1. Go to BO > Stats page
2. Click on the "Registered customer information"
3. See error

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

statspersonalinfos

**Comment by PrestaEdit** [comment]
PR available and merged: https://github.com/PrestaShop/statspersonalinfos/pull/16

**Comment by hibatallahAouadni** [comment]
@PrestaEdit thanks for the tip :wink: 
@PierreRambaud thanks for the PR :rocket:
