### ISSUE TITLE
BO - An error is displayed in the stats page - statsbestmanufacturers module

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27200]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Stats > the module statsbestmanufacturers is NOK with develop branch
![image](https://user-images.githubusercontent.com/16067358/148096598-4d02932b-6bfb-4b0c-a9b7-965a49b8488a.png)
An error is displayed
`Unknown error on line 821 in file /var/www/html/develop/classes/Hook.php
[16384] The hook "AdminStatsModules" is deprecated, please use "displayAdminStatsModules" instead in module "statsbestmanufacturers".`

### Steps to reproduce

1. Go to BO > Stats page
2. Click on the "Best brands"
3. See error

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

Best brands v2.0.0

**Comment by PrestaEdit** [comment]
PR available and merged: https://github.com/PrestaShop/statsbestmanufacturers/pull/11

**Comment by Progi1984** [comment]
@khouloudbelguith  Have you got always the problem with the `dev` branch of the module ?

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

Sorry for the delay.
Yes, it is fixed with the `dev` branch. (statsbestmanufacturers v2.0.1)

https://user-images.githubusercontent.com/16067358/152535667-186887bd-33ec-4d92-9e7a-292cb87266cd.mp4

Thanks!
