### ISSUE TITLE
BO - An error is displayed in the stats page - Sales and orders module 

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#27212]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Stats > the module statssales is NOK with develop branch

![image](https://user-images.githubusercontent.com/89604350/148182604-6556d0cf-2a2d-4e29-b963-bf300ca6a01a.png)

The following error is displayed
`Unknown error on line 821 in file /project/new_clone/classes/Hook.php
[16384] The hook "AdminStatsModules" is deprecated, please use "displayAdminStatsModules" instead in module "statssales".`

### Expected behavior

No error is displayed

### Steps to reproduce

1. Go to BO > Stats page
2. Click on Sales and orders
3. See error

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

statssales

**Comment by PrestaEdit** [comment]
PR available and merged: https://github.com/PrestaShop/statssales/pull/26

**Comment by Progi1984** [comment]
@marwachelly Have you got always the problem with the `dev` branch of the module ?

**Comment by marwachelly** [comment]
> @marwachelly Have you got always the problem with the `dev` branch of the module ?

Hi @Progi1984,

The issue is fixed with the `dev` branch of the module.

Thanks,
