### ISSUE TITLE
BO - An error is displayed in the stats page - Shop search module

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#27213]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Stats > the module shop search is NOK with develop branch
![image](https://user-images.githubusercontent.com/89604350/148183519-25a26452-6e0d-4f4c-a5df-ebacb055d22e.png)

The following error is displayed
`Unknown error on line 821 in file /project/new_clone/classes/Hook.php
[16384] The hook "AdminStatsModules" is deprecated, please use "displayAdminStatsModules" instead in module "statssearch".`

### Expected behavior

No error is displayed.

### Steps to reproduce

1. Go to BO > Stats page
2. Click on Shop search
3. See error

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3/7.2

### If your bug is related to a module, specify its name and its version

statssearch

**Comment by PrestaEdit** [comment]
Pr available and merged: https://github.com/PrestaShop/statssearch/pull/13

**Comment by Progi1984** [comment]
@marwachelly Have you got always the problem with the `dev` branch of the module ?

**Comment by marwachelly** [comment]
> @marwachelly Have you got always the problem with the `dev` branch of the module ?

Hi @Progi1984,

The issue is fixed with the `dev` branch of the module.

Thanks,
