### ISSUE TITLE
BO - An error is displayed in the stats page - Customer accounts module

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#27211]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Stats > the module Customer accounts is NOK with develop branch
![image](https://user-images.githubusercontent.com/89604350/148182172-098a6fb8-557e-4c38-afcf-d1df79be476d.png)

An error is displayed:
Unknown error on line 821 in file /project/new_clone/classes/Hook.php
[16384] The hook "AdminStatsModules" is deprecated, please use "displayAdminStatsModules" instead in module "statsregistrations".

### Expected behavior

No error displayed

### Steps to reproduce

1. Go to BO > Stats page
2. Click on customer accounts
3. See error

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3/7.2

### If your bug is related to a module, specify its name and its version

statsregistrations

**Comment by PrestaEdit** [comment]
PR available and merged: https://github.com/PrestaShop/statsregistrations/pull/11

**Comment by Progi1984** [comment]
@marwachelly Have you got always the problem with the `dev` branch of the module ?

**Comment by marwachelly** [comment]
> @marwachelly Have you got always the problem with the `dev` branch of the module ?

Hi @Progi1984,

The issue is fixed with the `dev` branch of the module.

Thanks,
