### ISSUE TITLE
[Hook] Allow modules to modify delivery option list result

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#27222]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Allow modules to modify delivery option list result.

it will be interesting that the modules can modify the list of delivery options. For example :

- a module can decide to display or not a certain carrier depending on the customer group
- a module can decide to block a means of delivery for a specific customer or group of customers
- a module can decide to display or not a carrier according to the date? (for example this delivery method is only available in January?)
- we can imagine many other use cases.

###  Core

Add a new hook in `Cart::getDeliveryOptionList` just before return delivery option slist

```php

public function getDeliveryOptionList(Country $default_country = null, $flush = false)
{
   Hook::exec('actionFilterDeliveryOptionList',
            [
                'delivery_option_list' => &$delivery_option_list
            ]
    );
}

### Modules

public function hookActionCustomFilterDeliveryOptionList($params)
{
        $deliveryOptionList = $params['delivery_option_list'];
        // Check and unset an carrier here.
}
```

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @PululuK 

Thank you for your suggestion. The Developer Team will take it into consideration for future developments. 
Thanks for the PR :rocket: 
Ping @PrestaShop/prestashop-core-developers wdyt?

PS: welcome back :tada: 

Thank you

**Comment by Hlavtox** [comment]
OK I thought I didn't find it. This is a necessity! 🚀

**Comment by atomiix** [comment]
Looks like a good idea!

**Comment by jf-viguier** [comment]
Thanks
