### ISSUE TITLE
why pin code formate show invalid 

### ISSUE THREAD

**Issue by ersanjay5991** [PrestaShop/PrestaShop#27231]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Hi, steps new Prestashop store all working fine,

when I goes to checkout when I added the address with pin code it showed me an error

https://www.prestashop.com/forums/topic/1058715-invalid-postcode-should-look-like-nnn-nnn/?tab=comments#comment-3371208

here my community questions  

Prestashop 1.7.8.2

I done the basic store done. when i goes to cart to checkout i enter the correct pin code but it give me error's 

 

here my checkout page Error 

### Describe the solution you'd like

no idea

### Alternatives you've considered

no option

### Additional context

![image](https://user-images.githubusercontent.com/39982842/148273253-db813202-406d-4a50-a824-d2f40b075cf8.png)

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @ersanjay5991 

You need to add space between 380 015, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/148359672-d529987b-5406-4f6c-b272-9bbfe6a10428.png)

Closing this issue as it's not a Core bug.

Thanks!

**Comment by ersanjay5991** [comment]
@hibatallahAouadni   thanks for the answer.

I can't move to the next screen  see this error
![image](https://user-images.githubusercontent.com/39982842/148437721-38426e8c-c3da-4ddb-8661-50d14254cdde.png)
