### ISSUE TITLE
No visits are being recorded in back-office main page (Online Visitors)

### ISSUE THREAD

**Issue by TonySerpofski** [PrestaShop/PrestaShop#27239]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When i click on the Online Visitors link in the BO - i get 'Module not found'. Also, no visits are recorded in the main stats display in the back office.
 
![Untitled picture1](https://user-images.githubusercontent.com/49027006/148385679-7bb52977-96c2-4109-8aeb-b44ac45c406d.png)
![Untitled picture2](https://user-images.githubusercontent.com/49027006/148385689-9a308141-daba-44cd-a3f5-7379b8845044.png)

### Expected behavior

Im meant to see a count of online customers and be able to see their ip address etc

### Steps to reproduce

Go to back-office click Online Visitors

### PrestaShop version(s) where the bug happened

 1.7.8.2 after upgrade from 1.7.1

### PHP version(s) where the bug happened

7.4.25 

### If your bug is related to a module, specify its name and its version

stats module?

**Comment by hibatallahAouadni** [comment]
Hello @BettyNutz 

Could you please check this [comment](https://github.com/PrestaShop/PrestaShop/issues/15937#issuecomment-541790143) :pray: 
As you can see we didn't manage to reproduce the issue.

Thanks!

**Comment by TonySerpofski** [comment]
Thanks for the reply - I reset it 'dashactivity' and it made no difference. can i reinstall a module to sort it?

**Comment by TonySerpofski** [comment]
i have a new version of PS 1.7.8.2 loaded up on wamp. can anyone tell me what module is associated with login visits?

**statsdata** or **statscheckup** or **statspersonalinfos** 

here's the compare but ive no idea what im looking at. - something to do with composer not working or being out of date. im on a bitnami AWS stack


![Untitled picture](https://user-images.githubusercontent.com/49027006/148686465-3fb14038-7663-4cd9-8a3e-1f3420a72255.png)

**Comment by hibatallahAouadni** [comment]
Hello @BettyNutz 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you
