### ISSUE TITLE
Facing issue while deployment

### ISSUE THREAD

**Issue by devphoenix2404** [PrestaShop/PrestaShop#27238]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi Team,

I'm not able to deploy the PS v1.7.8.2.

```
Removing intermediate container d5f1face595d
 ---> 8c035bae1710
Step 17/23 : RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
 ---> Running in 66b6af7413d9
All settings correct for using Composer
Downloading...

Composer (version 2.2.3) successfully installed to: /usr/local/bin/composer
Use it: php /usr/local/bin/composer

Removing intermediate container 66b6af7413d9
 ---> e1db2154bda8
Step 18/23 : RUN pecl install -f xdebug-2.9.8     && docker-php-ext-enable xdebug
 ---> Running in 4ddb699b0731
downloading xdebug-2.9.8.tgz ...
Starting to download xdebug-2.9.8.tgz (245,293 bytes)
...................................................done: 245,293 bytes
91 source files, building
running: phpize
Configuring for:
PHP Api Version:         20190902
Zend Module Api No:      20190902
Zend Extension Api No:   320190902
building in /tmp/pear/temp/pear-build-defaultuser7AtHLM/xdebug-2.9.8
running: /tmp/pear/temp/xdebug/configure --with-php-config=/usr/local/bin/php-config
ls: cannot access '.': Operation not permitted
configure: error: working directory cannot be determined
ERROR: `/tmp/pear/temp/xdebug/configure --with-php-config=/usr/local/bin/php-config' failed
The command '/bin/sh -c pecl install -f xdebug-2.9.8     && docker-php-ext-enable xdebug' returned a non-zero code: 1
time="2022-01-06T10:58:32Z" level=fatal msg="exit status 1"`

> ERROR: `/tmp/pear/temp/xdebug/configure --with-php-config=/usr/local/bin/php-config' failed
```

I've tired with 3.1.2 xdebug version too.

Thanks

### Steps to reproduce

1. Use FROM prestashop/prestashop:1.7.8.2 
2. RUN `pecl install -f xdebug-3.1.2 \    && docker-php-ext-enable xdebug`

### PrestaShop version(s) where the bug happened

1.7.8.2

### If your bug is related to a module, specify its name and its version

Prestashop 1.7.8.2

**Comment by hibatallahAouadni** [comment]
Hello @devphoenix2404 

Thanks for reporting the issue!
Ping @PrestaShop/prestashop-core-developers can someone please reproduce the issue :pray: 

Thanks in advance!

**Comment by kpodemski** [comment]
It's been a while! If you'd like to discuss it further, feel free to create [a new discussion in Q&A section](https://github.com/PrestaShop/PrestaShop/discussions/new?category=q-a).
