### ISSUE TITLE
BO - The color picker by default is black 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27249]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The color picker by default is black 
![image](https://user-images.githubusercontent.com/16067358/148396296-c7536332-0c65-4e75-9b57-7ab2cba3397a.png)

In the PS1782 => ok
![image](https://user-images.githubusercontent.com/16067358/148396519-1f22af69-08f6-4bec-a934-a90f8cb83289.png)

Related to this PR: https://github.com/PrestaShop/PrestaShop/pull/27114

### Steps to reproduce

1. Go to BO > Catalog > Attributes & Features 
2. Click on "Add new value" to the Color "Attribute group"
3. See the color field by default is black

![image](https://user-images.githubusercontent.com/16067358/148397501-e0c02e1c-d5dd-4f03-950a-1dc34c4ae7bf.png)

1. Enable Multistore context
2. Create a new shop
3. See the color field by default is black

 ![image](https://user-images.githubusercontent.com/16067358/148396296-c7536332-0c65-4e75-9b57-7ab2cba3397a.png)

### PrestaShop version(s) where the bug happened

1.7.8.3build1

### PHP version(s) where the bug happened

7.3

**Comment by Progi1984** [comment]
Fixed by @sowbiba in #27330 and tested by @khouloudbelguith
