### ISSUE TITLE
BO - When the menu is resized, the header of migrated pages is not well displayed

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27243]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Migrated page > when the menu is resized
The header is NOK
**Multistore enabled**
![image](https://user-images.githubusercontent.com/16067358/148380930-7162b753-9d45-4fbb-87be-8d91432becbc.png)

**1782** => ok
![image](https://user-images.githubusercontent.com/16067358/148380961-8ce5eca0-663a-427b-9c9d-34a2bb123912.png)

**Multistore disabled**
![image](https://user-images.githubusercontent.com/16067358/148380995-0c5b334b-1831-43ad-9f41-470d47510e3a.png)

**1782** => ok
![image](https://user-images.githubusercontent.com/16067358/148381018-08c87dc3-dcea-403d-a0bc-89003e719225.png)

### Steps to reproduce

1. Go to BO > Migrated page
2. Resize the menu 
3. See an error in the header ![image](https://user-images.githubusercontent.com/16067358/148380995-0c5b334b-1831-43ad-9f41-470d47510e3a.png)
4. Enable multistore context & create a new shop
5. Go to BO > Migrated page
6. Resize the menu
7. See an error ![image](https://user-images.githubusercontent.com/16067358/148380930-7162b753-9d45-4fbb-87be-8d91432becbc.png)

### PrestaShop version(s) where the bug happened

1.7.8.3build1

### PHP version(s) where the bug happened

7.3

**Comment by Progi1984** [comment]
@MatShir 1783 or 1784 ?

**Comment by MatShir** [comment]
1.7.8.3 ! It needs to be included in the final release of the 1.7.8.3 patch :)
