### ISSUE TITLE
BO - Bad display in the list items of langages in Wording block of blockwishlist module with RTL enabled

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#27258]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Bad display in the list items of languages in Wording block of `blockwishlist` module with `RTL` enabled
![issue rtl](https://user-images.githubusercontent.com/92912932/148515119-f3fe217d-f50a-47c4-b31f-0fe140cff5e0.png)

https://watch.screencastify.com/v/3QeAyegpm7to09bToHrv

### Expected behavior

The items must not go beyond the language box like with RTL disabled
![image](https://user-images.githubusercontent.com/92912932/148515926-af31b263-cffa-414c-8c6c-9b02bc5af58e.png)

### Steps to reproduce

1. Choose an `RTL` language 
2. BO > International > Localization > Languages > Choose Arabic (for exalmple)
3. Click on the language > Enable RTL language
2. BO > Module Manager
2. Search for `blockwishlist` module

### PrestaShop version(s) where the bug happened

1.7.7.8 & 1.7.8.x

### PHP version(s) where the bug happened

7.3

**Comment by mparvazi** [comment]
I think it's related to BO theme.
Fixed by https://github.com/PrestaShop/PrestaShop/pull/26700

![Screenshot 2022-01-11 at 14-06-23 پیکربندی • ps](https://user-images.githubusercontent.com/85633460/148957810-a77a97fc-b75d-45af-952c-794e8dc88ef0.png)

**Comment by florine2623** [comment]
I can't reproduce the issue either : 

<img width="1422" alt="Image" src="https://github.com/user-attachments/assets/5d462fe1-e414-450b-9feb-5b545a173151" />
