### ISSUE TITLE
FO - Productcomments - Grade is not displayed in the Product list page 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27252]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the FO > Product list page > the Grade is not displayed
![image](https://user-images.githubusercontent.com/16067358/148419695-3e3752f3-765c-476d-ade2-6bcfd56364de.png)

- PS1780 +  Productcomments v4.2.2 => Not displayed
![image](https://user-images.githubusercontent.com/16067358/148420326-11ac14b1-e9c9-4c25-a44d-fe655320ce22.png)
- PS1783build1 +  Productcomments v5.0.0 => Not displayed

- PS1778 + Productcomments v4.2.2 => Ok
- PS1778 + Productcomments v5.0.0 => Ok

### Steps to reproduce

1. Go to FO > Sign in 
2. Add a review to the first product
3. Go to BO > Module manager page > Search for the Productcomments module and approve The review
4. Go to FO > Home page
5. See no Grade displayed as in the PS1778

### PrestaShop version(s) where the bug happened

1.7.8.0, 1.7.8.3build1

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

 Productcomments v5.0.0 , v4.2.2

**Comment by atomiix** [comment]
@NeOMakinG Can you have a look at this issue? From what I see it's only a css issue

**Comment by Progi1984** [comment]
@NeOMakinG Needs a release of `productcomments` and a bump in the Core.

**Comment by Progi1984** [comment]
Fixed by me in #27647 and tested by @boubkerbribri
