### ISSUE TITLE
Adding "getPriceStatic" download option to prestashop API

### ISSUE THREAD

**Issue by gs2k84** [PrestaShop/PrestaShop#27254]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Describe the solution you'd like

Hello,

please add the "getPriceStatic" download option to prestashop API

This will allow you to download the rounded price via API at the time of using the Prestashop Price Rounding Module.

Useful when external systems are used to post on ebay, for example.

Regards and thanks.
Gregory

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by HanaRebaiQA** [comment]
Hello @gs2k84 

Thanks for your suggestion.
Could you please provide us more infomations about this feature ? It's emplacement ? The impact ? screenshots ?

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @gs2k84 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
