### ISSUE TITLE
FO - RTL - Bad display after an upgrade from PS1778 to PS1.7.8.3build1

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27261]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After an upgrade from PS1778 to PS1783build1, we have a bad display using RTL language
![image](https://user-images.githubusercontent.com/16067358/148536808-1a73ad5b-61db-4b53-8f5a-51ea32f7b6eb.png)

![image](https://user-images.githubusercontent.com/16067358/148536928-5508d923-53dc-4e3b-ada7-e75f1ffcdd41.png)

Also bad display in The FO > Order confirmation page 
![image](https://user-images.githubusercontent.com/16067358/148549948-a3a4c86b-2354-40a0-a893-3682a6ca0482.png)

After an upgrade from PS1778 to PS1782 => ok
![image](https://user-images.githubusercontent.com/16067358/148537080-ca535ebd-100d-4857-9cbf-2b4abdd674ce.png)

Fresh install 1783build3 => ok

### Steps to reproduce

1. Install PS1778 & add the Arabic language
2. Upgrade to PS1783build 
3. Go to FO > Change Arabic language
4. See an error 

### PrestaShop version(s) where the bug happened

1.7.8.3build1

### PHP version(s) where the bug happened

7.2

**Comment by NeOMakinG** [comment]
If it's only on upgrade, it's probably not about front-end but Autoupgrade module

**Comment by matks** [comment]
Let's see what's inside

**Comment by matks** [comment]
So ... it is possible a bigger issue is hiding behind this bug report.

I compare 2 shops:
- one 1.7.8.x, so homepage looks fine
- one 1.7.7.8 => 1.7.8.3 upgrade, indeed homepage looks wrong with RTL

But on my 1.7.8.x shop, no RTL css is loaded.

If I follow these steps:
- install a branch using 1.7.8.x branch
- download language pack that contains Arabic language
- go to FO, switch language to Arabic
- my homepage is not RTL

So maybe an issue happens on 1.7.8.x that does not allow the RTL to function correctly.

**Comment by matks** [comment]
Confirmed:

- Switch to RTL language on FO is broken - see #27286
- I think also the RTL CSS is broken which is why we have the bad display above, but this cannot be verified before #27286 has been fixed

**Comment by tegbessou** [comment]
I have installed Prestashop 1.7.7.8 and configured the "Arabes" language (and generated RTL files). Then I have upgraded to the 1.7.8.3+build.1, so I have reproduced the problem described in the issue.
Otherwise, after I have analyzed the `theme_rtl.css`, I have noticed that it was in the same version as in 1.7.7.7.
By discussing with @matks, we have tried to delete this file and regenerate it. After the regenaration no more problem.
We, therefore, came to the conclusion that the problem is that during an update the `_rtl` files are not regenerated.
So we have two solutions: first, we leave it like that, and the user as to regenerate their `_rtl` files, or secondly, we fix the upgrade to regenerate `_rtl` files.
WDYT @PrestaShop/product-team ?

**Comment by MatShir** [comment]
Let's fix the issue on the module ! :)
https://github.com/PrestaShop/PrestaShop/issues/27307

**Comment by mparvazi** [comment]
All problems for RTL theming in FO and BO will be fixed by this issue: https://github.com/PrestaShop/PrestaShop/issues/27289

It's a pre-requirement for making themes to be Auto-RTL.

@NeOMakinG is working on Auto-RTL theming.

**Comment by matks** [comment]
@mparvazi Auto-RTL is not directly related to the upgrade issue.

It is a nice feature but it’s a parallel feature not a replacement.

Today we have a lot of themes which rely on the use of rtlfix file and CSS generation to handle RTL, and these will not be replaced anytime soon by Auto-RTL. So "all problems for RTL will be fixed" => not accurate

**Comment by mparvazi** [comment]
@matks Trust me!

It is not supposed to delete CSS generation.
Third party developers can use it.

But with new project that @NeOMakinG is working, problems for PS themes will be fixed (BO themes, classic and theme-refacto).

This is a smart solution, and third-party developers will try to use it.

**Comment by matks** [comment]
> https://github.com/PrestaShop/PrestaShop/issues/27289

I am happy you are so optimistic 😄  but Auto-RTL will be truly efficient when the majority of themes do implement it. In PrestaShop we can allow themes to be Auto-RTL or to rely on a generated CSS for RTL, but we cant force theme developers to change their themes.

Launching a new feature is great but until majority of users adopt it, it's just a little nice-to-have option and we still need to maintain the current system.

**Comment by mparvazi** [comment]
This solution doesn't force current themes to be adapted.
It's works for themes that has declared they are RTL adapted, and doesn't need to use CSS generation for RTL.

If theme has this setting:

![148933515-585fa69e-8017-4933-a22a-21cdd1c44e24](https://user-images.githubusercontent.com/85633460/148966407-b5a2b990-85f7-4ffb-bd7b-23c12bb2897b.png)

Then CSS generation for RTL will be disabled for theme.

But if has not this setting or its value is true then current CSS generation will be used.

**Comment by mparvazi** [comment]
I already implemented in my local PS an it's works fine.

![148931063-1682d1a1-e55f-41cd-8214-8e5eebc94294](https://user-images.githubusercontent.com/85633460/148967003-deea2b2e-7d99-431a-9517-7c64c43f92da.png)

![148930983-1b2808a2-a5a9-4bab-9a87-81159fc60dff](https://user-images.githubusercontent.com/85633460/148967068-bb278b0d-bf69-4846-9179-8b7da4700bed.png)

**Comment by mparvazi** [comment]
I just say there is a smart way to handling this problem.

Adding too many options to installer would be scary for new users.

**Comment by mparvazi** [comment]
@matks 

Seems adding new feature to patch version is not possible.
So dismiss my comments.
Sorry for interrupting this issue.

**Comment by Progi1984** [comment]
@tegbessou Is it good ?

**Comment by Progi1984** [comment]
After discussion with @Robin-Fischer-PS, we wait the release of `autoupgrade`

**Comment by matks** [comment]
https://github.com/PrestaShop/autoupgrade/releases/tag/v4.14.0 is released so I close this issue
