### ISSUE TITLE
Add product link in order preview

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#27267]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Be able to go to the product page from the order preview.

### Describe the solution you'd like

Add product link in order preview.

## Before

![image](https://user-images.githubusercontent.com/16455155/148564231-a6c78581-7d3f-450d-9047-91fa8596d995.png)

## After 

![image](https://user-images.githubusercontent.com/16455155/149517102-b50b8701-1ff8-46ff-b291-0fdda297baa7.png)

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @PululuK 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Thanks for your PR :rocket: 

Thank you
