### ISSUE TITLE
Add support for AVIF images

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#27264]
New image format even better than webP is starting to break through.
Prestashop missed the train with previous one by 10 years, but that does not mean we can't catch up with the world. :-)

### Don't know what is it? - READ
- https://web.dev/compress-images-avif/
- https://www.finally.agency/blog/what-is-avif-image-format
- https://en.wikipedia.org/wiki/AVIF
- https://caniuse.com/avif

### How to generate it?
`function imagecreatefromavif(string $filename): GdImage|false {}`

PHP 8.1+ supports generating AVIF images in GD library. On lower versions of PHP, it will be greyed out with an alert to upgrade.

We check by this:
```
if (function_exists('imagecreatefromavif')) {
    // AVIF support available.
}
```

### Implementation - The same as webP.
Does browser support AVIF? If not, does it support WEBP? If it does not support webP also, or doesn't know what `<picture>` tag is, it will use the classic `<img>` tag inside.
```
<picture>
<source srcset="images/example.avif" type="image/avif">
<source srcset="images/example.webp" type="image/webp">
<img src="images/example.jpg" alt="description of example image">
</picture>
```

### Comparsion with JPEG - speaks for itself
![Výstřižek](https://user-images.githubusercontent.com/6097524/148550016-1ba7d5be-3813-40ee-8359-affeaed90c62.JPG)
![Výstřižek2](https://user-images.githubusercontent.com/6097524/148550008-8d1c3e58-7aa4-4bde-aeed-b70bf8331f4b.JPG)

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by matks** [comment]
https://caniuse.com/avif

**Comment by NeOMakinG** [comment]
> https://caniuse.com/avif

Chromium support it, but the `picture` element will act as a callback for browsers not supporting it!

**Comment by NeOMakinG** [comment]
We waited for years to have the webp support, let's catch this one asap, picture element is here to deal with it, 100% agree here

**Comment by HanaRebaiQA** [comment]
Hello @Hlavtox 

Thanks for your suggestion. The Product Team will take it into consideration for future developments. 
Waiting for the linked PR. 
@matks , @NeOMakinG : Can we change it as Ready ?

Thank You!

**Comment by NeOMakinG** [comment]
https://php.watch/versions/8.1/gd-avif

Thanks @Progi1984

**Comment by nicosomb** [comment]
@Hlavtox @Progi1984 FYI, I had to add this file to check AVIF support https://github.com/PrestaShop/PrestaShop/pull/30045/files#diff-c6f293bac5cde5c22a68e5594a4a5cdc5bf4a53deeef2419f8f45933986f89b2 (related to this issue https://stackoverflow.com/questions/71739530/php-8-1-imageavif-avif-image-support-has-been-disabled)

**Comment by rwdsji** [comment]
I really need avif for my project guys. When will this be available for end users?

**Comment by NeOMakinG** [comment]
@rwdsji We have been really active on images for some weeks, expect it to be up for the 8.1

But if I didn't miss anything, you'll need to add some PHP extensions and probably use PHP 8.1, can you confirm @nicosomb ?

**Comment by nicosomb** [comment]
I confirm that PHP 8.1 will be mandatory (see https://php.watch/versions/8.1/gd-avif). 
This feature is planned for PrestaShop 8.1. 

Pull request will be available soon to be reviewed.
