### ISSUE TITLE
The Logo of PDFs are NOK with RTL lanaguage

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27265]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When downloading PDFs with RTL language => NOK
This issue occurs with an invoice & Delivery slip & the credit slip

**Credit slip**
![image](https://user-images.githubusercontent.com/16067358/148554398-b5c87c8f-5512-4875-a59e-b9731438cd13.png)
**Delivery slip**
![image](https://user-images.githubusercontent.com/16067358/148554444-abb42164-da2e-4ea3-9487-4aea5e7a928e.png)
**invoice**
![image](https://user-images.githubusercontent.com/16067358/148554524-04c56681-e605-4855-8100-789bea8e4f4d.png)

In the PS1778 => ok
![image](https://user-images.githubusercontent.com/16067358/148554659-570db608-b5b1-4b55-9329-415ac5679ca5.png)

### Steps to reproduce

1. Go to BO > Your profile & select the Arabic language
2. Go to BO > Order > Generate an invoice & download it
3. See an error
4. Generate a delivery slip & download it
5. See an error
6. Generate a credit slip & download it
7. See an error

### PrestaShop version(s) where the bug happened

1.7.8.0, 1.7.8.2, 1.7.8.3build1

### PHP version(s) where the bug happened

7.2

**Comment by atomiix** [comment]
This bug comes from the tcpdf library: https://github.com/tecnickcom/TCPDF/issues/303. I'm gonna revert to an older version were the bug isn't introduced.

**Comment by MeKeyCool** [comment]
I had some troubles to reproduce cause I needed data.

From a fresh install, to test :
- "*Generate an invoice*", I needed to pass some orders to "*Payment accepted*" status.
- "*Generate a credit slip*", I found this documentation : https://doc.prestashop.com/display/PS17/Credit+Slips
- "*Generate a delivery slip*", I needed to pass some orders to "*Shipped*" status.
