### ISSUE TITLE
Product description on large screens

### ISSUE THREAD

**Issue by rickygzz** [PrestaShop/PrestaShop#27278]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Product description block, on larger screens (more than 767px wide), is shown on half the screen as follows

![image](https://user-images.githubusercontent.com/36200981/148599558-6f7f3f4e-418f-4c46-b0e6-1c7a134f7b94.png)

### Expected behavior

The product description block should be screen wide on any size, as follows

![image](https://user-images.githubusercontent.com/36200981/148599865-4f081c5b-4028-4d87-843f-c81405537c45.png)

### Steps to reproduce

1. Go to the FO.
2. Select any given product.
3. Watch for product description block.

### PrestaShop version(s) where the bug happened

1.7.8.2 develop

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @rickygzz 

This issue seems a feature and a good one more than a bug.

Thank you for your suggestion. The Product Team will take it into consideration for future developments.
Thanks for your PR 🚀  

Thank you

**Comment by prestascott** [comment]
Hello everyone,

Thanks @rickygzz for your request!

Having the product description block on half of the screen and on the right side makes the left side really empty.
With your proposition, the product description block fills the screen and fixes the empty feeling issue on the left side.

This is a smart solution. But I think we can make it smarter by moving the product description block to the left and making the product information block (product name, color attributes, size attributes, "add to cart" button, etc) fixed. 
So when users scroll down, they can immediately add the product into their cart without scrolling back up.

Tell me wdyt?

**Comment by rickygzz** [comment]
Hello @prestascott ,

I think your proposed solution would be much better than mine.

I kind of played a little bit tweaking product.tpl (check this commit https://github.com/rickygzz/PrestaShop/commit/f88d153a014baf19cf56d34ed258f1920a779f5d)

I hope that is similar to what you were thinking (please don´t mind the style attributes all around, I did it to get a quick look and feel).

However I don´t feel confident enough to make that change without breaking something else :)

**Comment by prestascott** [comment]
@rickygzz Can you provide some screenshots in the comments please? Thank you 🙏

**Comment by rickygzz** [comment]
@prestascott  Sure, I made a small screen recording video

As I increased 1/12 of a column on the left side, we may need to reduce the `wishlist-button-product { margin-left: }` from `20px` to `10px` to avoid the ugly new line for the up and down control next to the quantity textbox (`Button.vue` file within blockwhishlist module)

Regards,

https://user-images.githubusercontent.com/36200981/152941887-e670c466-4478-4fe8-8380-78d2a4b2199b.mp4

**Comment by prestascott** [comment]
@rickygzz This is really awesome, great work!

Do you have to increase 1/12 of a column on the left side to make it work? 🤔 

If yes, can you decrease the `wishlist-button-product { margin-left: }` from `20px` to `12px`, or `8px` instead please?

Also, are you able to make the Customer reassurance block sticky like the product description block too?

Thanks a lot!

**Comment by TristanLDD** [comment]
Hi @rickygzz, do you have any news about the last suggestions we made about your contribution ? This is a nice improvement for the product page :)

**Comment by hibatallahAouadni** [comment]
Hello @rickygzz 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
