### ISSUE TITLE
Fetching addresses, customers returning only fetched attribute ID

### ISSUE THREAD

**Issue by LocalHeroPro** [PrestaShop/PrestaShop#27272]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Downloading customers by ID returning only ID
![image](https://user-images.githubusercontent.com/42643563/148573335-e3b49bf5-17f9-40ec-9150-2faf7a1073e7.png)
Even when use display => full.

### Expected behavior

Return full customer data.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/42643563/148573577-c9cd8c31-4ae2-4ea0-854a-4b229c107aa1.png)

### PrestaShop version(s) where the bug happened

1.7.6.9

### PHP version(s) where the bug happened

7.2.34

**Comment by hibatallahAouadni** [comment]
Hello @LocalHeroPro 

Could you please provide clear and concise steps to reproduce.
Waiting for your feedback.

Thanks!

**Comment by LocalHeroPro** [comment]
# Steps to reproduce
1. Create API access, grant all privileges, enable API access, here: /admin/index.php/configure/advanced/webservice-keys/
2. Add in .htaccess that line 
```
RewriteEngine on // that line is already present
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```
3. Try to fetch data associated with addresses or customers resource. Using display full parameter.
4. Get only ID of that resource, against full resource.

The same code working as expected in 1.7.8.2 v.

**Comment by hibatallahAouadni** [comment]
Hello @LocalHeroPro 

> The same code working as expected in 1.7.8.2

Do you mean that with PS1782 you didn't encounter the issue?
Waiting for your feedback.

Thanks!

**Comment by LocalHeroPro** [comment]
Yep.

**Comment by hibatallahAouadni** [comment]
Great :tada: 
Closing the issue as it has been fixed :wink: 

Thanks for your feedback!

**Comment by LocalHeroPro** [comment]
So I'm guessing: resolution is to update to the latest up two major versions?
Did you check anything?
