### ISSUE TITLE
Category description issue for multilanguage shop

### ISSUE THREAD

**Issue by Natalia919** [PrestaShop/PrestaShop#27280]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

There is not possible to add category description in a second or third language. During "Import", no mather the language, the description is full filed only for the first language and for selected one, in my case for FR.

I tried to add manually description for EN, for FR no allowed space and I tried the second method by importing a category in FR language de description were full filed for EN instead of FR.

![1](https://user-images.githubusercontent.com/97352678/148651070-a1be3f86-9b24-41cf-9082-3bc9882ef6f4.JPG)
![2](https://user-images.githubusercontent.com/97352678/148651071-a1f1a94a-3132-48f3-9597-2413be3a6bb7.JPG)

### Expected behavior

To have active area for each language and to add 2 differents texts. 

### Steps to reproduce

1. Have active languages at least on the shop
2. Sell
3. Catalog
4. Category
5. Description: description square.

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4.25

**Comment by hibatallahAouadni** [comment]
Hello @Natalia919 

I didn't understand the bug, cause in my case I can edit the description in many language:

https://user-images.githubusercontent.com/23308427/148774368-96bddbb7-71a9-4305-b8ee-216aec29c79f.mp4

> During "Import", no mather the language, the description is full filed only for the first language and for selected one, in my case for FR.

Did you try to import some categories than you encounter this issue? If so, please provide the file that you try to import, maybe it contains some errors :wink: 
Waiting for your feedback.

Thanks!

**Comment by Natalia919** [comment]
Hello @hibatallahAouadni ,

Thank you for your reply.

I don't know what happened, I reinstalled today the same version of Prestashop and that seems to work.

Thank you for your feedback !

**Comment by hibatallahAouadni** [comment]
@Natalia919 Glad to hear :tada:

**Comment by cbatista8a** [comment]
Im the same error and don't know what cause this Bug.

My Prestashop version is : 1.7.8.2
PHP version: 7.4.22
Server information: Linux
Server software version: Apache

Any idea?

**Comment by cbatista8a** [comment]
I answer myself, the problem in my case was caused by a theme that had modified certain assets concerning the creation of the tinymce editor. The solution in my case was to restore the folder "/ admin / themes / new-theme" with the original one of a new installation of the same version.
