### ISSUE TITLE
PrestaShopBundle\Entity\ShopGroup - PrestaShopBundle\Entity\Shop entities mapping error

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#27282]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On debug mode I am getting two invalid entities errors.

The field PrestaShopBundle\Entity\ShopGroup#shops is on the inverse side of a bi-directional relationship, but the specified mappedBy association on the target-entity PrestaShopBundle\Entity\Shop#shopGroup does not contain the required 'inversedBy="shops"' attribute.

The field PrestaShopBundle\Entity\Shop#shopUrls is on the inverse side of a bi-directional relationship, but the specified mappedBy association on the target-entity PrestaShopBundle\Entity\ShopUrl#shop does not contain the required 'inversedBy="shopUrls"' attribute.

![Screenshot 2022-01-09 at 17 06 01](https://user-images.githubusercontent.com/46492443/148688106-a3fb77cd-90d5-488d-8301-a4327e2c0b58.png)

### Expected behavior

Having no error

### Steps to reproduce

I dont know, how to reproduce this.

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @01park 


We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #27218. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #27218
