### ISSUE TITLE
Debug mode breaks frontend

### ISSUE THREAD

**Issue by dewced** [PrestaShop/PrestaShop#27284]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I enable debug mode, the frontend breaks? Is this normal? How can I debug frontend issues like this?

![image](https://user-images.githubusercontent.com/25767435/148692036-a5829668-f675-49c4-9083-e3c969f0bc79.png)

### Steps to reproduce

Enable debug mode

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.3 & 7.4

**Comment by kpodemski** [comment]
This notice is not related to the PrestaShop core, but to the module/theme you use. You should contact the theme author.

**Comment by dewced** [comment]
Oh ok. I'm sorry, will close this issue. Thanks for reply!
