### ISSUE TITLE
[FO - Responsive] - Bad display of "Forgot your password" in the checkout process

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#27290]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The link **"Forgot your password"** is bad displayed in the tab **`Personal Information>Sign`** in when your try to checkout:

![image](https://user-images.githubusercontent.com/23308427/148767336-28c682a7-4074-498d-9531-775ade0cde4b.png)

### Expected behavior

to change the style in theme.css from:
```
body#checkout section.checkout-step .forgot-password {
    margin-left: 14.38rem;
}
```
to: 
```
body#checkout section.checkout-step .forgot-password {
    margin-bottom: 10px;
}
```
![image](https://user-images.githubusercontent.com/23308427/148767669-569e10e6-1e8a-48ea-b8d1-3a10d30ad39f.png)

### Steps to reproduce

1. on mobile (width < **370px**, ex: `iPhone5s`)
2. **FO**>Click on any product
3. Click on **Add to cart** button
4. Modal will be displayed, click on **Proceed to checkout** button
5. Click on **Proceed to checkout** button again in the shopping cart page
6. Click on **Sign in** in the **PERSONAL INFORMATION** tab
7. See error

### PrestaShop version(s) where the bug happened

1.7.6.7 & 1.7.8.2

### PHP version(s) where the bug happened

7.2

**Comment by eliphazbouye** [comment]
Hi @hibatallahAouadni going to work on this issue

**Comment by hibatallahAouadni** [comment]
@eliiphaz can't wait for your PR :rocket: 
Thanks :muscle:

**Comment by eliphazbouye** [comment]
I just learned that the classic theme has been removed from the core : [classic-theme](https://github.com/PrestaShop/classic-theme)
because it will be operational in the future
while the issue is on the Prestashop core
in this case, my pull request should be on the theme repo, right?

**Comment by hibatallahAouadni** [comment]
@NeOMakinG you're the expert :sweat_smile: can you please answer him :pray:

**Comment by NeOMakinG** [comment]
> I just learned that the classic theme has been removed from the core : [classic-theme](https://github.com/PrestaShop/classic-theme) because it will be operational in the future while the issue is on the Prestashop core in this case, my pull request should be on the theme repo, right?

Yes, everything involved in classic should be on the classic repository! You're right

**Comment by eliphazbouye** [comment]
Okay, great, so I'm going to make my pull request on the classic-theme repo
