### ISSUE TITLE
ps_stock_available.out_of_stock changes from 2 to 1 automatically

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#27298]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

From times to times some of my products change the default behaviour when out of stock.

A took a look into ps_stock_available and ps_product and I could see that "out_of_stock" changes only in ps_stock_availabe table.

I don't have any module that changes this but I can't track a reason for this to change.

Is this some kind of known issue? I can't reproduce the issue... at least I don't know how to reproduce.

### Steps to reproduce

I don't know

### PrestaShop version(s) where the bug happened

1.7.7.8

### PHP version(s) where the bug happened

7.2

**Comment by florine2623** [comment]
Hello @seederp2p ,

I tried to reproduce your issue on PS 1.7.7.8, but I couldn't find a way to reproduce it.
Also, I couldn't find any issue similar to yours here : https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aopen+is%3Aissue+label%3AStocks

I suggest you try to find a way to reproduce it, so we can help.

Or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
