### ISSUE TITLE
Default order by price Issue when blocklayered is active

### ISSUE THREAD

**Issue by cippest** [PrestaShop/PrestaShop#273]
Hello,

I'm testing this issue on 1.5.3.1.

When "order by price" is active by default and blocklayered is working, it does not consider reduced price when browse category by pages. I have attached an image to to better explain the problem.

There is no issue when the blocklayered module is uninstalled/desactivated.

Best regards.
Massimo - Cippest.it
![shoot](https://f.cloud.github.com/assets/3628919/168319/c394dcac-79f7-11e2-8a6b-9e71d1f51c2f.jpg)

**Comment by marionf** [comment]
Hello, 
This issue is old, so I close it.
If you still have it on the last version (PrestaShop 1.7.4.2), please open a new one.
Regards
