### ISSUE TITLE
Add an option to regenerate RTL file during the upgrade

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#27307]
**Description**

When I upgrade a shop with a RTL language, the files are not regenerated, which can cause display errors on the Front Office after an upgrade

**Solution**
Add a toggle enabled by default in the Upgrade Options section, to regenerate RTL files

**Wording**
Regenerate RTL stylesheet - Yes/No
help text: If enabled, any RTL-specific files that you might have added to all your themes might be deleted by the created stylesheet.

**Test**
Check if it fixes this https://github.com/PrestaShop/PrestaShop/issues/27261

**Specs**
https://github.com/PrestaShop/prestashop-specs/pull/291/

_Originally posted by @tegbessou in https://github.com/PrestaShop/PrestaShop/issues/27261#issuecomment-1009153105_

**Comment by tegbessou** [comment]
I take this!

**Comment by mparvazi** [comment]
Please don't add this option :pray: 

It will be fixed soon with a smart way.

**Comment by NeOMakinG** [comment]
@mparvazi It won't be fixed with what we're doing, but this autoupgrade thing should verify that the theme enabled RTL generation with what we wants to add :)

**Comment by mparvazi** [comment]
PLEASE try to handle this issue first: https://github.com/PrestaShop/PrestaShop/issues/27289

Then problems will be solved easily!

**Comment by matks** [comment]
@mparvazi this issue is blocking the release 1.7.8.3 which is supposed to be released this week so it's our highest priority

We'll be happy to improve the future of PrestaShop of https://github.com/PrestaShop/PrestaShop/issues/27289 but we have to work on both the software of the future and the software of the present ;)

**Comment by NeOMakinG** [comment]
@mparvazi I won't fix the current problem, many themes rely on the RTL generation, it's a new feature, both should be available and RTL generation will adapt on the new configuration entry we wants to add 👍

**Comment by mparvazi** [comment]
@MatShir 

We have this option now in installer: Enable SSL
The "Maintenance mode" is going to be added.
And this new one.

So is it possible to consider these options as Advanced options, and gathering them inside a block?
Block can be collapsed by default.

I mean too many options in installer would be confusing for new users.

**Comment by MatShir** [comment]
This is for the autoupgrade module in the advanced setting.
But if we add more feature in the installer, we should have an advanced setting section as well
