### ISSUE TITLE
statscarrier - the name of the carrier ID 1 is not correct

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#27305]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

At the installation, the name of the carrier with ID 1 is `0` instead of the name given in Shipping > Carriers.
<img width="371" alt="Screenshot 2022-01-11 at 14 56 46" src="https://user-images.githubusercontent.com/16019289/148957006-dd6af279-f985-4dc2-8897-213380ed705d.png">

Once I modify the name of the carrier, I have the penultimate carrier name :
<img width="319" alt="Screenshot 2022-01-11 at 15 03 11" src="https://user-images.githubusercontent.com/16019289/148957021-38d0b075-bc4e-43a3-80a5-4b45dd67cace.png">

### Expected behavior

It should be the same name as what we have in Shipping > Carriers

### Steps to reproduce

1. Go to BO > Stats > Carrier distribution
2. See that one carrier is named 0
3. Go to Shipping > Carriers
4. Change name of carrier ID 1 with "hello world"
5. Go back to BO > Stats > Carrier distribution
6. See that name is updated with initial name instead of "hello world"

### PrestaShop version(s) where the bug happened

1.7.8.x, develop

### PHP version(s) where the bug happened

7.3, 7.4

### If your bug is related to a module, specify its name and its version

statscarrier v2.0.1

**Comment by ghost** [comment]
Hello @florine2623 

https://github.com/PrestaShop/PrestaShop/pull/26071

https://github.com/PrestaShop/PrestaShop/issues/25800

It's a duplicate i will open a new PR

**Comment by hibatallahAouadni** [comment]
@okom3pom I think it's related not a duplicate
