### ISSUE TITLE
Product combi delta bugs - Page V2

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#27313]
Hi @zuk3975,

I have some issues:

**First issue**

1. Enable Experimental product page
2. Go to BO > Catalog > Products page > Edit a product with combinations V2
3. In the combinations Tab > try to set the quantity field with this value = `2000000000000` or `2E12`
4. See error: `An unexpected error occurred. [PrestaShop\PrestaShop\Core\Domain\Product\Stock\Exception\ProductStockConstraintException code 20]: Invalid StockAvailable quantity. Got "2000000000002"`

![image](https://user-images.githubusercontent.com/16067358/148979207-aa743966-d4ad-465c-b522-d04b38226aa1.png)

**Second issue**
1. Enable Experimental product page
2. Go to BO > Catalog > Products page > Edit a product with combinations V2
3. In the combinations Tab > try to set the quantity field with this value = `2E5`
4. Save => the final quantity will be 2
5. Edit another combination
6. In the Quantity field > set the same quantity `2E5` and save 
7.  See the difference > the final quantity is `200000`
8. Click outside
9. See error > the quantity of the first combination is converted to `200000`
https://watch.screencastify.com/v/NSTMV9OXU7k0mhrr8KAJ

what is the exact value of 2E5?, if it should be `200000` => in the delta quantity => NOK 

![image](https://user-images.githubusercontent.com/16067358/148980581-3e22e627-8169-4def-b405-e49538dc2b11.png)

**Third issue**
1. Enable Experimental product page
2. Go to BO > Catalog > Products page > Edit a product with combinations V2
3. In the combinations Tab > set the quantity with the keyboard
4. See error the delta quantity is not displayed only if  click outside
https://watch.screencastify.com/v/TxCcE65kiY8Pp1Icr9Ey

Same issue in the Combination edit page 
![image](https://user-images.githubusercontent.com/16067358/148982588-2ef4b02a-bed7-4569-922b-b997a7a96c59.png)

PS: if you use the arrow to increase or decrease the quantity => well displayed

**Fourth issue**
1. Enable Experimental product page
2. Go to BO > Catalog > Products page > Edit a product with combinations V2
3. In the combinations Tab > try to set the quantity field with this value = `888008848` and save
4. try to set the same quantity field with this value = `4444444444` and save
5. See error 
![image](https://user-images.githubusercontent.com/16067358/148983275-ad6d2516-0e5a-4260-ba46-466b902761f0.png)

**Fifth issue**
1. Enable Experimental product page
2. Go to BO > Catalog > Products page > Edit a product with combinations V2
3. In the combinations Tab > try to set the quantity field with this value = `2.2`
4. Click on the check button without moving the mouse
5. just an error but the field quantity is not red 
![image](https://user-images.githubusercontent.com/16067358/148984338-354b8e9f-e934-47ec-a5c2-d32e29a236c8.png)

But if you click on the check button with moving the mouse 
![image](https://user-images.githubusercontent.com/16067358/148984621-e20e8141-03c4-4a66-92db-033139914594.png)

**Sixth issue**

I don't know if it is really a bug

1. Enable Experimental product page
2. Go to BO > Catalog > Products page > Edit a product with combinations V2
3. In the combinations Tab > try to move the mouse on the disabled check button
4. See the behavior 

https://watch.screencastify.com/v/0SYKgdVOLkDKm5xfooIT

**Seventh issue**

1. Add the Finnish language
2. Change employee language to Finnish
3. Go to BO > Edit a product V2 with combinations
4. In the Combinations tab, set quantity with a negative value and save
5. Edit this combination
6. In the quantity field,> try to increase or decrease
7. See error, the delta quantity is NOK

![image](https://user-images.githubusercontent.com/16067358/149148313-bd491bd1-ead5-447f-b885-14e2d258724d.png)
 => we have a related issue reported here: https://github.com/PrestaShop/PrestaShop/issues/26502

**Eighth issue**

1. Open Firefox browser
2. Edit product with combination V2
3. In the Tab combinations see the increase/decrease quantity can be clicked only one-time => NOK

https://watch.screencastify.com/v/PbZB4Qd7iDuDWv9DDMyb

=> related to this issue: https://github.com/PrestaShop/PrestaShop/issues/26796

Thanks!

_Originally posted by @khouloudbelguith in https://github.com/PrestaShop/PrestaShop/issues/26617#issuecomment-1010159453_

**Comment by khouloudbelguith** [comment]
Hi @MatShir,

As discussed with @jolelievre.
I added two other issues to the first comment.

Thanks!

**Comment by jolelievre** [comment]
Also some of the bugs mentioned here are common to some present in stock page:
#26796
#26502

Maybe the same fixes can be applied on stock page as well even if it's not exactly the same code

**Comment by saulaski** [comment]
IMHO items #1 #2 #4 and #5 are no bugs, but functional inconsistencies.
Quantities are supposed to be integers: 
- only numeric characters and any optional sign character at the right place (according to CLDR)
- max value = 2,147,483,647 (physical limit, otherwise technical impacts are gigantic)
- no decimal separator is allowed
- no alphabetic character allowed, not even exponential sign `E`

It only means that more validation rules are required to reject invalid inputs, and prevent server errors.
Item #5 is only the validation rule doing its job.

Item #6 looks ok in the video, what is the issue ?

**Comment by Progi1984** [comment]
Added in Blocked :

Why ? As discussed with @jolelievre, we have edge cases but not expected behavior on each bug.

**Comment by jolelievre** [comment]
Hi @MatShir 

I opened a dedicated issue for the fourth issue https://github.com/PrestaShop/PrestaShop/issues/29253 because it should probably be handled in a dedicated PR since it needs to change the database structure.
