### ISSUE TITLE
BO - Categories - Category image cannot be deleted 

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#27311]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Category image cannot be deleted on the branch develop
https://watch.screencastify.com/v/1i42raIdwyBaZLgSMVZG

This behavior is not observed with the branch 1.7.8.x
https://watch.screencastify.com/v/RYGVJZKU6uyLs3ZpGAkv

### Steps to reproduce

1. Go to BO > Catalog > Categories
2. Click on edit category
3. Delete image
=> The image is not deleted.

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3/7.2

**Comment by HanaRebaiQA** [comment]
Thank you @marwachelly for the issue.
It can be fixed in this PR [#27228](https://github.com/PrestaShop/PrestaShop/pull/27228)

**Comment by Progi1984** [comment]
Fixed by @atomiix  in #27228 (cf https://github.com/PrestaShop/PrestaShop/pull/27240#issuecomment-1012291160)
