### ISSUE TITLE
Update SEO preview in the style currently used by search engines 

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/PrestaShop#27310]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

The current SEO preview is kinda old and is only used by **Bing**:

<img src="https://user-images.githubusercontent.com/85633460/148982106-96fb3ca6-b093-46a7-8cb2-e2af16581901.png" width="650">

### Describe the solution you'd like

Update to a new style used by **Google**, **Yahoo** and **DuckDuckGo**:

<img src="https://user-images.githubusercontent.com/85633460/148983378-c6ae7158-72d8-41af-9830-0820a4939828.png" width="650">

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by florine2623** [comment]
Hello @mparvazi ,

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 

Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know!

Thank you

**Comment by MatShir** [comment]
Cool feature, the page V2 is being migrated. If you are willing to implement it, we will have to be synchronized with @jolelievre

**Comment by jolelievre** [comment]
Yep, good idea.

Actually, this is handled by an independent component https://github.com/PrestaShop/PrestaShop/blob/d29bb707816eda12744e14d308245314d7c502c6/admin-dev/themes/new-theme/js/app/utils/serp/index.js

Which is used by a few pages (product, category, cms) so the component can be improved and it will benefit all those pages. We don't have time for this improvement for now since we are focusing on finishing the product page but if someone wants to contribute we'll be happy to integrate this!!

It will need to include new features like price and image but why not

**Comment by Hlavtox** [comment]
@mparvazi If you include this extra data in the preview, we should add a note to the field, something like:

_Displaying of breadcrumbs, price and stock in search results is dependent on proper implementation by your theme and the search engine._

_There is no guarantee that the search result will look like this._

**Comment by mparvazi** [comment]
@Hlavtox 

I got your point!

No extra data will be added.
Just a placement swap for url and title as like as Google:
```
{{ url }}
{{ title }}
{{ description }}
```
And then some changes with CSS.

<img src="https://user-images.githubusercontent.com/85633460/149020798-9828a1ef-d9a7-4a4f-a5c9-b1723b99e162.png" width="550">
