### ISSUE TITLE
Add new image sizes to be used on any viewport size

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/PrestaShop#27319]
Epic: https://github.com/PrestaShop/PrestaShop/issues/27318

# Change the current API without adding BC

Currently we've something like this:
```
"bySize" => array:10 [▼
          "small_default" => array:3 [ …3]
          "cart_default" => array:3 [ …3]
          "pdt_180" => array:3 [ …3]
          "pdt_300" => array:3 [ …3]
          "home_default" => array:3 [ …3]
          "pdt_360" => array:3 [ …3]
          "medium_default" => array:3 [ …3]
          "pdt_540" => array:3 [ …3]
          "pdt_590" => array:3 [ …3]
          "large_default" => array:3 [ …3]
        ]
```

We would need to find out new best sizes, for example
```
  "small_default"
  "cart_default"
  "home_default"
  "medium_default"
  "large_default"
  200px
  400px
  800px
  400px
  800px
  1200px
  1600px
  ```
  
  and be able to select these sizes easily

**Comment by matks** [comment]
@MeKeyCool wants to try implementing this 👍

**Comment by MeKeyCool** [comment]
@NeOMakinG is the scope of this issue limited to product images or any type of image ?

**Comment by NeOMakinG** [comment]
> @NeOMakinG is the scope of this issue limited to product images or any type of image ?

I guess it's related to any images, category for example, in order to optimize everything

**Comment by MeKeyCool** [comment]
# [Add new image sizes](https://github.com/PrestaShop/PrestaShop/issues/27319)

What I understand from this issue.

Current theme object accessible in templates : 
```
"bySize" => array [
    "cart_default" => array:3 [ …3]
    "home_default" => array:3 [ …3]
    "small_default" => array:3 [ …3]
    "medium_default" => array:3 [ …3]
    "large_default" => array:3 [ …3]
    "pdt_180" => array:3 [ …3]
    "pdt_300" => array:3 [ …3]
    "pdt_360" => array:3 [ …3]
    "pdt_540" => array:3 [ …3]
    "pdt_590" => array:3 [ …3]
]
```

And the goal is to remove `"pdt_180"`, `"pdt_300"`, `"pdt_360"`, `"pdt_540"`, `"pdt_590"` options and to add
`"200px"`, `"400px"`, `"800px"`, `"1200px"`, `"1600px"` options.

But I didn't see anything about `"pdt_180"`, `"pdt_300"`, `"pdt_360"`, `"pdt_540"`, `"pdt_590"`, are those options from a module ? A theme ? Should those options be considered ?


:point_up: I add a huge comment to [parent epic issue](https://github.com/PrestaShop/PrestaShop/issues/27318) and I think I need some answers before starting this issue.

**Comment by NeOMakinG** [comment]
> # [Add new image sizes](https://github.com/PrestaShop/PrestaShop/issues/27319)
> What I understand from this issue.
> 
> Current theme object accessible in templates :
> 
> ```
> "bySize" => array [
>     "cart_default" => array:3 [ …3]
>     "home_default" => array:3 [ …3]
>     "small_default" => array:3 [ …3]
>     "medium_default" => array:3 [ …3]
>     "large_default" => array:3 [ …3]
>     "pdt_180" => array:3 [ …3]
>     "pdt_300" => array:3 [ …3]
>     "pdt_360" => array:3 [ …3]
>     "pdt_540" => array:3 [ …3]
>     "pdt_590" => array:3 [ …3]
> ]
> ```
> 
> And the goal is to remove `"pdt_180"`, `"pdt_300"`, `"pdt_360"`, `"pdt_540"`, `"pdt_590"` options and to add `"200px"`, `"400px"`, `"800px"`, `"1200px"`, `"1600px"` options.
> 
> But I didn't see anything about `"pdt_180"`, `"pdt_300"`, `"pdt_360"`, `"pdt_540"`, `"pdt_590"`, are those options from a module ? A theme ? Should those options be considered ?
> 
> ☝️ I add a huge comment to [parent epic issue](https://github.com/PrestaShop/PrestaShop/issues/27318) and I think I need some answers before starting this issue.

You probably don't want to remove anything, in order to avoid BCs

**Comment by Hlavtox** [comment]
pdt_ were my custom sizes, it was just an example 👍
