### ISSUE TITLE
BO - Product V2  - Some features are NOK

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27316]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the Product edit page V2, we have some issues NOK
- The block image is not displayed anymore
- The button save cannot be enabled
- Add categories button is not working
- The Related products is not working
- The tab Combinations is empty
- Errors in the console
- The modal to change the product type is not displayed 
![image](https://user-images.githubusercontent.com/16067358/149097573-88a23898-a996-4f8e-8703-7d8016d8d7a1.png)
- We cannot delete a product from the product edit page
- In the Specifications tab, we cannot add a feature, the modal add new file is not displayed, we cannot add a customization field
- The modal Add new product cannot be displayed
- In the Virtual product tab, the block  "Does this product have an associated file?" is always displayed despite the option is disabled
- In the Pricing Tab, the modal Add a specific price cannot be displayed
- The prices are not instantly converted 
![image](https://user-images.githubusercontent.com/16067358/149098485-893f74dc-4434-4e47-a258-cc38a3f7caa9.png)
- In the SEO tab, the Redirection page is nok  
![image](https://user-images.githubusercontent.com/16067358/149098629-d926c87e-2a12-4ae8-96a3-5f6edf59fc55.png)
=> it should be 
![image](https://user-images.githubusercontent.com/16067358/149098648-8c166f94-3847-4854-bf66-242aeffeae59.png)
- In the Options tab, The Suppliers table cannot be displayed 
![image](https://user-images.githubusercontent.com/16067358/149098783-8e47b05b-cc2a-4eae-be34-8dce2c3eb7af.png)
=> it should be 
![image](https://user-images.githubusercontent.com/16067358/149098816-ac209070-ec47-4cbd-9ca4-65168e8f0e2e.png)

### Steps to reproduce

1. Enable Experimental product page
2. Go to BO > Catalog > Products page > Add Edit a product
3. Try to check all fields in all tabs

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

**Comment by jolelievre** [comment]
Closed by a PR that only partially fixed this issue (one of the bug) I think some bugs are still to be corrected

**Comment by zuk3975** [comment]
can this be retested and updated so we know which ones are still left @khouloudbelguith ?

**Comment by zuk3975** [comment]
> Closed by a PR that only partially fixed this issue (one of the bug) I think some bugs are still to be corrected

can this be retested and updated so we know which ones are still left @khouloudbelguith ?

**Comment by jolelievre** [comment]
@zuk3975 I'll check myself it's possible that everything has been fixed with different PRs now

**Comment by MatShir** [comment]
Status: blocked, I will test and see if there are still issues and create a dedicated issue if so.
