### ISSUE TITLE
Add avif format to the core

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/PrestaShop#27321]
Epic: https://github.com/PrestaShop/PrestaShop/issues/27318

# Add avif format to the core

We need to be able to generate the avif format from the core, because it's lighter with great quality than other format

Currently we can't because @Progi1984 said that it's incompatible with PHP <= 8, but maybe we could activate it only if the current PHP version is supporting it.

**Comment by Progi1984** [comment]
@NeOMakinG PHP 8.1 : https://php.watch/versions/8.1/gd-avif

**Comment by NeOMakinG** [comment]
Duplicate of #27264

**Comment by NeOMakinG** [comment]
> @NeOMakinG PHP 8.1 : https://php.watch/versions/8.1/gd-avif

Linked it to the main issue
