### ISSUE TITLE
No icons in Safari 

### ISSUE THREAD

**Issue by Juiliard** [PrestaShop/PrestaShop#27338]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

No Order Notifications on the Favicon in Safari on Mac

### Expected behavior

"Order Notifications on the Favicon" are shown in Safari on Mac

### Steps to reproduce

- MacOS monterey v12.1
- Safari browser
- login to back office Prestashop 1.7.6.5
- install "Order Notifications on the Favicon"
- create dummy order
Result: NO Favicon in Safari on Mac
Check: YES favicon in Chrome on Mac, but we need Safari notifications 

### PrestaShop version(s) where the bug happened

1.7.6.5

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

Order Notifications on the Favicon v2.1.1

**Comment by Hlavtox** [comment]
@Juiliard You can talk to Apple about this 😄 - https://bugs.webkit.org/show_bug.cgi?id=95979#c18

We cannot do anything about it, unfortunately. 👍

**Comment by NeOMakinG** [comment]
Hello, sorry but as @Hlavtox said, this is a Safari problem, they don't support dynamic favicon change...
