### ISSUE TITLE
BO - An error is displayed in some legacy pages

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#27348]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An error is displayed in multistore page :
![image](https://user-images.githubusercontent.com/89604350/149366477-fb0eb299-5b8f-49ca-b4e7-90e9f3504858.png)

An error in these pages also:

- Add/Edit new attribute
- Add/Edit new carrier
- Add/Edit new country
- Add/Edit new tax rule
- Add/Edit new group customer
- Stores page
- Referrers page

### Steps to reproduce

1. Go to BO > Shop parameters > General 
2. Enable multistore
3. Go to Advanced parameters > Click on multistore
5. Add/Edit new attribute
1. Add/Edit new carrier
2. Add/Edit new country
3. Add/Edit new tax rule
4. Add/Edit new group customer
5. Stores page
6. Referrers page

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3/7.2

**Comment by Progi1984** [comment]
@marwachelly Could you test this issue on 1.7.8.3, please ?

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

In my case, I checked the branch 178x & I created this issue: https://github.com/PrestaShop/PrestaShop/issues/27616
The list of page with error smarty that I found in my case:
1. Bo > Advanced parameters > Click on multistore page => error
2. Add/Edit new shop group
3. Add/Edit a new shop
4. Add/Edit new URL
5. BO > Shop Parameters > Customer Settings > Add/Edit new Group
6. BO > Shop Parameters > Contact > Stores page
7. BO > Module manager > search ps_featuredproducts module & click on configure => error 
![image](https://user-images.githubusercontent.com/16067358/153223873-ab9dce10-a7ab-4e8a-adf7-6f1757c569d5.png)
8. BO > Module manager > search productcomments module > Click on configure > Add new criteria => error 
![image](https://user-images.githubusercontent.com/16067358/153224045-7aca0fc9-5ae1-4943-8dba-ea5a89cc7046.png)
9. BO > Module manager > search ps_facetedsearch > click on configure > Add new template => error


Thanks!
