### ISSUE TITLE
Fatal error when add product into cart in PS versions 1.7.8.0 and above.

### ISSUE THREAD

**Issue by devphoenix2404** [PrestaShop/PrestaShop#27345]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi Team,

Recently, we've encountered an issue when product is add to the cart. When we call `$cart->getProducts();` this leads to an fatal error and 500 response on the front-end. 
NO issue enounted for version below 1.7.8.0.

Recording : https://beta.claap.io/sendinblue/fatal-error-c-3YfMIiN6mG-AL7OcMGtoJMg

![error](https://user-images.githubusercontent.com/53808050/149353554-5fe5a0c6-b6cc-46da-aa1e-81b0499d3d8d.png)

Can you please have a look as the issue is coming after PS updated to 1.7.8.0.

Thanks in advance guys.

### Steps to reproduce

1. Login as customer
2. Add product to cart

### PrestaShop version(s) where the bug happened

1.7.8.2

### If your bug is related to a module, specify its name and its version

Sendinblue 4.0.5

**Comment by devphoenix2404** [comment]
here more details
![image](https://user-images.githubusercontent.com/53808050/149359273-c16da05a-9393-4411-a842-a790f82c38a8.png)

**Comment by hibatallahAouadni** [comment]
Hello @devphoenix2404 

I didn't manage to reproduce the issue with PS1782, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/149368175-db72212b-2b84-49ee-9099-e788f1f3657a.mp4

From which version did you upgrade? can you please provide your PHP version :pray: 
And please disable any third-module may be related to cart (I see that you mention this module Sendinblue), then try again and check if you still encounter the issue.

Please check and feedback.
Thanks!

**Comment by devphoenix2404** [comment]
Hi @hibatallahAouadni 

Thanks for the response. 

Actually, i'm using Sendinblue module, where we call `$cart->getProducts();` it leads to fatal error(above details).

Can you share the example to call getProducts() so that I can change in Sendinblue module.

Thanks

**Comment by khouloudbelguith** [comment]
Hi @devphoenix2404,

As it's not a module provided by Prestashop, we can't do anything with this. 
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.

I will close this issue, feel free to create a new one when needed.

Thanks!

**Comment by devphoenix2404** [comment]
Hi @khouloudbelguith 

Thanks for your response.

Yeah, I know that actually I'm working with the module, thing is that 

The call on `$cart->getProducts()` is working fine with version below 1.7.8.0 but in the above version, it's giving error like I've shown in the recording.

The error is only coming, for the clients using PS version 1.7.8.0 or above. Please help me with it.

Thanks

**Comment by hibatallahAouadni** [comment]
Ping @devphoenix2404  you can ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com) :wink:

**Comment by devphoenix2404** [comment]
@hibatallahAouadni doesn’t allow [the public Slack channel](https://prestashop.slack.com/) to login. The error is coming because of the version update that's why I've posted here 🙏🏻😅

**Comment by hibatallahAouadni** [comment]
> @hibatallahAouadni doesn’t allow [the public Slack channel](https://prestashop.slack.com/) to login. 

Cause you need to create a new account on this Slack and you have two options :wink: (try to connect with Google):

![image](https://user-images.githubusercontent.com/23308427/149741384-029a5d50-537e-47cd-8460-a6c8836fdcb7.png)

**Comment by devphoenix2404** [comment]
https://beta.claap.io/sendinblue/login-error-c-3YfMIiN6mG-3cIzRjONgTk0 No success 🙈

**Comment by hibatallahAouadni** [comment]
Weird :confused:  

https://user-images.githubusercontent.com/23308427/149766775-719dc7e6-1522-4107-a5f2-769c8f7ff540.mp4

**Comment by devphoenix2404** [comment]
Can anyone please help 🙏🏻

**Comment by MarcorOnline** [comment]
@devphoenix2404 hello, I have the same issue with Sendinblue module on PrestaShop 1.7.8.x

**Comment by hibatallahAouadni** [comment]
@MarcorOnline you need to contact the Sendinblue developers to solve your issue :pray:

**Comment by devphoenix2404** [comment]
The issue will be fixed in the next release v4.0.6

**Comment by abdullacm** [comment]
can anyone explain how this issue can be solved? $cart->getProducts() was working fine in previous versions. I have 3 modules to fix the same issue.

**Comment by bilelbelghith** [comment]
I think it's not the module fault, this error occurs in mailchimp, sending blue and on my custom module.

**Comment by abdullacm** [comment]
i was fixed the error by the below condition

```
if (!Validate::isLoadedObject($params['cart'])) {
            return false;
}

if (!isset($params['cart']) || !isset($params['cart']->id)) {
    return;
}
```

**Comment by bilelbelghith** [comment]
> i was fixed the error by the below condition
> 
> ```
> if (!Validate::isLoadedObject($params['cart'])) {
>             return false;
> }
> 
> if (!isset($params['cart']) || !isset($params['cart']->id)) {
>     return;
> }
> ```

it's working thanks
