### ISSUE TITLE
The header of the stock page is not well displayed

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27356]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The header of the stocks page is not well displayed

### Steps to reproduce

1. Go to The BO > Catalog > Stocks page 
2. Resize the menu
3. See error 

![image](https://user-images.githubusercontent.com/16067358/149546956-f7189d6a-3735-47fc-b733-b09dfd30b5c1.png)

2. Change the employee language to RTL
3. Go to The BO > Catalog > Stocks page 

![image](https://user-images.githubusercontent.com/16067358/149547057-3f82df0b-1e93-4db8-8762-939bd3628db0.png)

Related to this PR: https://github.com/PrestaShop/PrestaShop/pull/27259

### PrestaShop version(s) where the bug happened

1.7.8.x

### PHP version(s) where the bug happened

7.2, 7.3

**Comment by Progi1984** [comment]
Fixed by @atomiix in #27372 and tested by @marwachelly
