### ISSUE TITLE
`strip_tags()` expects parameter 1 to be string, array given in /prestashop/classes/db/Db.php on line 791

### ISSUE THREAD

**Issue by FongWan** [PrestaShop/PrestaShop#27357]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the server error log there are lots of errors with the content similar to:

~~~
strip_tags() expects parameter 1 to be string, array given in /path/to/prestashop/classes/db/Db.php on line 791
~~~

Investigating the fact, it has to do with the fact that the `str_replace` function found in `Tools::nl2br` can return as an array in case the subject is array.

### Expected behavior

No error reported in the log.

### Steps to reproduce

1. On `ps_facetedsearch` module configuration page, set "Show products from subcategories" to "No". ![error-screenshot-0](https://user-images.githubusercontent.com/1299769/150029008-1ef02caa-c7b3-43af-9770-651df34a85de.png)
2. Go to any category page in front office.
3. Use the `ps_facetedsearch` module to filter more than one categories or more than one brands at time. ![error-screenshot-1](https://user-images.githubusercontent.com/1299769/150028861-ad48c657-2aba-4c9e-bd6e-5f3b0bc572c7.png)
4. See Server/PHP error log. ![error-screenshot-2](https://user-images.githubusercontent.com/1299769/150028910-abe368f8-6ad3-4634-9fbc-bac4e25173c3.png)

Screen recording:

https://user-images.githubusercontent.com/1299769/150029441-82914e3f-5604-4a12-9579-07b4979d6cf2.mp4

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_facetedsearch v3.7.1

**Comment by hibatallahAouadni** [comment]
Hello @FongWan 

I didn't manage to reproduce the issue with the provided infos :disappointed: 
Could you please provide a screen record of the issue :pray: 

Thanks!

**Comment by FongWan** [comment]
Hello @hibatallahAouadni 

I have edited the issue description with screenshots and screen record, please take a look.

**Comment by FongWan** [comment]
Hello @hibatallahAouadni, were you able to reproduce the issue now?

**Comment by HanaRebaiQA** [comment]
Hello @FongWan 

Following the steps described above, i was able to reproduce your issue.
https://watch.screencastify.com/v/0Jmz9LCfmNoGxrYuNbRx

Thanks for your PR which is Waiting for QA. We will check it as soon.

Thanks!
