### ISSUE TITLE
Product instance in FO is filled mostly with useless information

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/PrestaShop#27363]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

`$product` variable on product page or `$cart.products` after you add product to the cart hold a lot of data. Feels like 99% of it is useless here: all shops's translations, including those related only to BO and much more...

### Expected behavior

`$product` and `$cart.products` should contain only relevant data.

### Steps to reproduce

1. Add product to the cart
2. Check `$cart.products` array eg. add this to the theme's top .tpl file `<pre>{$cart.products|print_r}</pre>`

or

1. Check `$product` variable on product page.

### PrestaShop version(s) where the bug happened

1.7.x.x

### PHP version(s) where the bug happened

7.4

**Comment by Hlavtox** [comment]
The translations are shown all the time when you dump the product, but I think they are not really **in** the variable. I don't know why is it like this. 🤔

The low performance is caused by the hundreds of duplicated DB queries man. :(

**Comment by SharakPL** [comment]
I'll take your word for it as I'm not good enough with PHP.
Still putting all this information inside Cart instance or maybe I should say Product instance seems pointless. All other variables used by the shop that I know of are clear and compact. Actually $cart is also clear when empty. Products make a mess of it.

**Comment by matks** [comment]
It maybe is done on purpose

Looks similar to https://github.com/PrestaShop/PrestaShop/issues/25633

Some data has been made available to "make available data that might be useful for modules in order to make building modules easier"

Not sure if that's the reason

**Comment by SharakPL** [comment]
Thanks @matks 
Maybe `print_r` isn't the best way to check this as it also shows private and protected properties. Still looks like whole shop's translation is attached to each product instance. What's the point of that?

**Comment by kpodemski** [comment]
If you do `{$product->jsonSerialize()}` you will see a more readable information about the product.

**Comment by SharakPL** [comment]
I know, already tried json_encode.
Is there a point to having translations attached to product instance in FO? They're not even a product related translations nor shop’s translations. I'm guessing it's inherited from parent classes but should it be like that, especially in the cart?

Wouldn't it be better to have simple compact instances of a product in the cart. There's not much needed there. It should be like CartProduct instance with just required properties to display basic information, image, stock and prices. Certainly doesn't need to inherit translations and the rest of useless data.

**Comment by SharakPL** [comment]
> {$product->jsonSerialize()}

@kpodemski I've just tried and it doesn't seem to work in product.tpl on PS 1.7.8.2. I'm using this instead:
```smarty
<pre>{json_encode($product, JSON_PRETTY_PRINT)}</pre>
```

BTW. `$product` seems to be missing **tags** array.

**Comment by kpodemski** [comment]
I forgot to put a `|dump` modifier after the variable

**Comment by SharakPL** [comment]
It causes fatal error when added after variable. I found this method being used like this:
```
{$product->jsonSerialize()|dump}
```

Any reason why product tags aren't included in $product array? I managed to get them in my last project using this:
https://github.com/PrestaShop/PrestaShop/blob/9137e46585a9b87813c5a4156d13075313d82953/classes/Tag.php#L223-L238
but they seem like great candidate to add to $product array.

**Comment by kpodemski** [comment]
@SharakPL 

Of course `after variable` meant the code you've written ;-)

> Any reason why product tags aren't included in $product array? I managed to get them in my last project using this:
> but they seem like great candidate to add to $product array.

Great candidate for a PR! 👍
