### ISSUE TITLE
Remove/Deprecate cleanNonUnicodeSupport function

### ISSUE THREAD

**Issue by davidglezz** [PrestaShop/PrestaShop#27362]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The function `Tools::cleanNonUnicodeSupport()`  does nothing because it uses a undefined constant: `PREG_BAD_UTF8_OFFSET`

```php
class CharacterCleaner
{
    /**
     * Delete unicode class from regular expression patterns.
     *
     * @param string $pattern
     *
     * @return string pattern
     */
    public function cleanNonUnicodeSupport($pattern)
    {
        if (!defined('PREG_BAD_UTF8_OFFSET')) {  // <-- ALWAYS TRUE
            return $pattern;
        }

        return preg_replace('/\\\[px]\{[a-z]{1,2}\}|(\/[a-z]*)u([a-z]*)$/i', '$1$2', $pattern);
    }
}
```
Looking at the PHP source code I see that the constant `PREG_BAD_UTF8_OFFSET` does not exist, the most similar is [PREG_BAD_UTF8_OFFSET_ERROR ](https://github.com/php/php-src/blame/2b1f8abd8778d14abeae6a83bc1205989f8bdece/ext/pcre/php_pcre.c#L453) which is always defined (in my case === 5). This hasn't changed in PHP for over 8 years.

Maybe @Progi1984 knows something about it, since he modified it not so long ago in https://github.com/PrestaShop/PrestaShop/pull/14838

Should we remove this wrapper from all validations and deprecate the function?

Additional info:
- I have only found one project that used it and stopped using it:
   - https://github.com/symphonycms/symphonycms/issues/692
   - https://github.com/symphonycms/symphonycms/pull/697/files#diff-bfe72a5ce47c188387989ec3c3e3896fe90fd64f59927fb9a1acf8a4d8867662L611
 - [stackoverflow thread](https://stackoverflow.com/questions/4509576/detect-if-pcre-was-built-without-the-enable-unicode-properties-or-enable-utf) (the only place on the internet where it is mentioned, a comment from someone)

### Expected behavior

Not to have this wrapper

### Steps to reproduce

Not available

### PrestaShop version(s) where the bug happened

All

### PHP version(s) where the bug happened

All

### If your bug is related to a module, specify its name and its version

Core

**Comment by hibatallahAouadni** [comment]
Hello @davidglezz 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must complete all template blocks to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by davidglezz** [comment]
@hibatallahAouadni  This bug comes from a code review I've done.
There is no unwanted behavior by the user or steps to reproduce from the UI, it's a code bug.
Please reopen

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers if you think this issue is valid please reopen it :slightly_smiling_face: 
Thanks in advance :pray:
