### ISSUE TITLE
Upgrade from 1.7.6.9 to 1.7.8 error

### ISSUE THREAD

**Issue by nrm83** [PrestaShop/PrestaShop#27370]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

during upgrade we have this error:

[INTERNAL] /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 168 - Symfony\Component\Config\Exception\FileLoaderLoadException: Expected to find class "PrestaShopBundle\Controller\Admin\Sell\index" in file "/var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/src/PrestaShopBundle/Controller/Admin/Sell/index.php" while importing services from resource "/var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/app/../src/PrestaShopBundle/Controller/*", but it was not found! Check the namespace prefix used with the resource in /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/app/config/config.yml (which is being imported from "/var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/app/config/config_prod.yml"). #0 /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(90): Symfony\Component\Config\Loader\FileLoader->doImport('/var/www/2241f4...', NULL, false, '/var/www/2241f4...') #1 /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(195): Symfony\Component\Config\Loader\FileLoader->import('config.yml', NULL, false, '/var/www/2241f4...') #2 /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(127): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseImports(Array, '/var/www/2241f4...') #3 /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/DelegatingLoader.php(40): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('/var/www/2241f4...', NULL) #4 /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/app/AppKernel.php(150): Symfony\Component\Config\Loader\DelegatingLoader->load('/var/www/2241f4...') #5 /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(776): AppKernel->registerContainerConfiguration(Object(Symfony\Component\Config\Loader\DelegatingLoader)) #6 /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(642): Symfony\Component\HttpKernel\Kernel->buildContainer() #7 /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() #8 /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(76): Symfony\Component\HttpKernel\Kernel->boot() #9 /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(50): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #10 /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(86): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() #11 /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #12 /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/administration/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #13 {main}

### Steps to reproduce

Just upgrade:

[INTERNAL] /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 168 - Symfony\Component\Config\Exception\FileLoaderLoadException: Expected to find class "PrestaShopBundle\Controller\Admin\Sell\index" in file "/var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/src/PrestaShopBundle/Controller/Admin/Sell/index.php" while importing services from resource "/var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/app/../src/PrestaShopBundle/Controller/*", but it was not found! Check the namespace prefix used with the resource in /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/app/config/config.yml (which is being imported from "/var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/app/config/config_prod.yml"). #0 /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(90): Symfony\Component\Config\Loader\FileLoader->doImport('/var/www/2241f4...', NULL, false, '/var/www/2241f4...') #1 /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(195): Symfony\Component\Config\Loader\FileLoader->import('config.yml', NULL, false, '/var/www/2241f4...') #2 /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(127): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseImports(Array, '/var/www/2241f4...') #3 /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/DelegatingLoader.php(40): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('/var/www/2241f4...', NULL) #4 /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/app/AppKernel.php(150): Symfony\Component\Config\Loader\DelegatingLoader->load('/var/www/2241f4...') #5 /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(776): AppKernel->registerContainerConfiguration(Object(Symfony\Component\Config\Loader\DelegatingLoader)) #6 /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(642): Symfony\Component\HttpKernel\Kernel->buildContainer() #7 /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() #8 /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(76): Symfony\Component\HttpKernel\Kernel->boot() #9 /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(50): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #10 /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(86): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() #11 /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #12 /var/www/2241f464-b5a1-46d9-b9ab-7b74b2310c7f.parachute.sh/administration/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #13 {main}

### PrestaShop version(s) where the bug happened

1.7.6.9

### PHP version(s) where the bug happened

7.2.34

**Comment by hibatallahAouadni** [comment]
Hello @nrm83 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must complete all template's blocks to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
