### ISSUE TITLE
Adding language mutation - very slow eshop

### ISSUE THREAD

**Issue by vvvamik** [PrestaShop/PrestaShop#27371]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi, lately we have a very slow Prestashop. We have two language versions (CS and SK). The redirection to https://www.smatab.cz/cs is very slow. You can see it well on adding a product to the cart. Admnistration is fast. We have tried everything. Any ideas on how to solve this? Thanks. 

https://www.smatab.cz

Prestashop 1.7.5.1

PHP version: 7.1.33

Memory limit: 1024M

Max Execution Time: 90

Max upload file size: 512M 

### Steps to reproduce

![sm](https://user-images.githubusercontent.com/22279127/149757216-c3f7045c-1a89-447b-b9d5-88c2ab5ef399.jpg)

### PrestaShop version(s) where the bug happened

1.7.5.1.

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment]
Hello @vvvamik 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must provide a clear and concise steps to reproduce the issue to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you

Thanks!
