### ISSUE TITLE
Cart Rules for categories

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#27379]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

No

### Describe the solution you'd like

When we create a Cart Rule, we can specify a list of products available for this Rule.

But we are not able to select Categories.
We are able to create a Cart Rule of "20%" for : 
- selected products;
- all products of the shop.

I would like to create a Cart Rule of "20%" which can be use for all products of the category "CAT_1".
Thanks to this, all products add to this category after created the Cart Rule, will be included too.

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by marwachelly** [comment]
Hello,

Thank you for your suggession and you report. It is possible in prestashop to add a cart rule with a specific category. 
Do you mean that ?
https://watch.screencastify.com/v/YUHWo7x1poxgdFRooaCM

Thanks,

**Comment by BenTen** [comment]
my bad, I never seen that m(_ _)m
