### ISSUE TITLE
FO - Order confirmation page - ps_cashondelivery is NOK

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#27375]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The ps_cashondelivery module is NOK with the develop branch
![image](https://user-images.githubusercontent.com/89604350/149792909-089901a2-ea5c-4b0d-a2af-627038871f80.png)

https://watch.screencastify.com/v/lmgJAl2A4YmcewAyTMGK

### Steps to reproduce

1. Go to FO > create an order using ps_cashondelivery payment
2. see error

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_cashondelivery

**Comment by matks** [comment]
I reopen because this issue is not fixed until we released the new COD module release 

Should be fixed by v2.0.0 of COD module https://github.com/PrestaShop/ps_cashondelivery/pull/44

**Comment by matks** [comment]
Fixed by COD 2.0.0 release

**Comment by Progi1984** [comment]
It's not totally fixed. The bump of the module is not done in the core.
