### ISSUE TITLE
No email sending after update to 1.7.8.2

### ISSUE THREAD

**Issue by pixmax** [PrestaShop/PrestaShop#27380]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Prestashop has gone silent after updating from 1.7.6.7 to 1.7.8.2. When an order is placed, neither the customer nor the seller receives an order confirmation or notification by email. When testing the email settings, one gets the error message: "Expected response code 220 but got an empty response"
I don't think it's because of the ps_emailalerts module, because the customer doesn't get a notification either. And the module is the same as before the update, but not Prestashop itself.
The attempt with the settings of the SMTP server to solve the problem, unfortunately, also brought nothing.

![Screenshot 2022-01-18 at 09-52-06 Module Manager • MedHerbs Schweiz](https://user-images.githubusercontent.com/22912788/149906107-25111a8a-ad53-48d4-ab4c-10518b912354.png)
![Screenshot 2022-01-18 at 09-55-58 E-Mail • MedHerbs Schweiz](https://user-images.githubusercontent.com/22912788/149906137-121eca96-2990-40d3-915c-c9bfda3fb3c7.png)
![Screenshot 2022-01-18 at 10-07-39 Log-Dateien • MedHerbs Schweiz](https://user-images.githubusercontent.com/22912788/149906166-417865c3-acce-4920-b9eb-df32ed6f6018.png)
.

### Expected behavior

Notifying the customer about his order by email is important. There have already been customer complaints. A solution to the problem should be done quickly. In the forum the problem could not be solved.

### Steps to reproduce

1. buy a product
2. invoice is created and order is made
3. neither to customer nor to seller an email is sent.

Important notice: The shop is only for customers in Swizerland. medherbs.ch
If you need to test the shop please contact me. Then I will open the shop for the country where you are and give you an test order address in Swizerland.

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4

**Comment by marwachelly** [comment]
Hello,

Thanks for your report. To reproduce the issue I need to upgrade from 1.7.6.7 to 1.7.8.2. But according to the  [PHP compatibility Chart](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart) the starting version is not compatible with PHP 7.4. To reproduce the issue could you please provide me with the correct PHP version? 

Many thanks,

**Comment by pixmax** [comment]
Many thanks for your reply. The Prestashop 1.7.6.7 initially ran with PHP 7.3. Then the store owner changed the PHP version to 7.4, which caused the back office to stop working correctly. I then performed the Prestashop update to version 1.7.8.2. Unfortunately, the problems described above now occur.
Best regards

**Comment by HanaRebaiQA** [comment]
Hello @pixmax 

I think it's an email-configuration problem. 

Could you please check your configuration ?

Waiting for your feedback!

Thanks!

**Comment by pixmax** [comment]
Hello Hana,

it would be nice if it was that simple. I checked the email configuration before posting the problem here. 
So that I can rule out the email configuration as the cause, I created a new email address. This has been tested and is working. The access data I have then entered in the back office and checked in the database whether they are stored correctly including the password. 
So that you can also exclude the e-mail configuration as a cause, I have attached some screenshots.
I would also like to point out that the problems only occurred with the update. An update can not change the email configuration. It can only possibly change the configuration in Prestashop. In the back office, I have exhausted my options. I think.

Any other idea?

Best regards
Michael

![Screenshot 2022-01-21 at 19-20-12 Kundenservice • MedHerbs Schweiz](https://user-images.githubusercontent.com/22912788/150581140-8af7bd1d-ffe5-40ca-bf99-bca64a80af01.png)

![Screenshot 2022-01-21 at 19-19-06 E-Mail IONOS](https://user-images.githubusercontent.com/22912788/150581173-0ee2eed9-b4e7-4657-a0bc-7087e75d5544.png)
)

**Comment by JBWModules** [comment]
Check the SMTP settings at "Erweiterte Einstellungen"->"Email"

**Comment by pixmax** [comment]
Hi, it seems that a wrong port was specified. I had taken the information from the provider IONOS. Possibly the port specification was only valid for TLS. I have now used the settings that Thunderbird automatically found with a different port for SMTP and now everything works fine.

Thank you for your effort and I'm sorry to bother you with this simple error that has nothing to do with Prestashop.

**Comment by hibatallahAouadni** [comment]
@pixmax Glad to hear :tada:
