### ISSUE TITLE
Modern backoffice assets do not build properly on Windows

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#27383]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Assets do not build properly inside admin\themes\new-theme on Windows. JS errors are present and menu is not working on modern pages.

- Node v14.17.3
- NPM 6.14.13
- Windows 10 Pro, 10.0.19044 Build 19044

![Výstřižek](https://user-images.githubusercontent.com/6097524/149927418-d980f46b-b35b-48dd-bdea-f5533d68e11d.JPG)

ping @NeOMakinG

### Expected behavior

Assets should build regardless of platform.

### Steps to reproduce

1. Go to windows PC, install recommended node and npm version.
2. Go to `admin\themes\new-theme`.
3. `npm install`, `npm run build`
4. Go to BO > Orders and see that menu is not working.

### PrestaShop version(s) where the bug happened

develop

**Comment by marwachelly** [comment]
Hello,

Thank you for your report. We are looking for a windows PC actually to reproduce the issue. Your ticket will be analysed as soon as we prepare the suitable environment.

Thanks for your understanding,

**Comment by Hlavtox** [comment]
Closing this, just install WSL. It's difficult enough to make it working on linux/mac.
