### ISSUE TITLE
BO - An exception is thrown on Pages configuration of Theme & Logo 

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#27384]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

 An exception is thrown on `Theme & Logo >> Pages configuration`
![image](https://user-images.githubusercontent.com/92912932/149933113-073d9258-02be-4b39-9b8c-dff9689d341e.png)

### Expected behavior

The `Pages configuration` is well displayed. 

### Steps to reproduce

1. BO > IMPROVE > Design > Theme & Logo
2. Click on Pages configuration
3. See error > An exception is thrown

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

**Comment by khouloudbelguith** [comment]
Could be related to this PR: https://github.com/PrestaShop/PrestaShop/pull/27359

**Comment by Progi1984** [comment]
@HanaRebaiQA It seems it is fixed in `dev` branch of the module (with this PR PrestaShop/ps_themecusto#47).

Could you check it ?

**Comment by PierreRambaud** [comment]
> Could be related to this PR: #27359

No, it's not related to this PR :)

**Comment by Progi1984** [comment]
@PrestaShop/qa-functional Could you check with `dev` branch of the module ?

**Comment by HanaRebaiQA** [comment]
Hello @Progi1984 

I checked again this issue on `develop` branch using this [PR](https://github.com/PrestaShop/ps_themecusto/pull/47) to test the module `ps_themecusto` of `dev branch`.
The issue is well fixed with the dev branch.

https://user-images.githubusercontent.com/92912932/153876465-bfa82cf4-9d2a-4040-a00b-33df698d47dd.mp4


So, i will close the issue.

Thank you!

**Comment by Progi1984** [comment]
Thanks @HanaRebaiQA
