### ISSUE TITLE
Error sent by Addons. You may be not allowed to download this module. [Exception 0]

### ISSUE THREAD

**Issue by michybetti** [PrestaShop/PrestaShop#27391]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello everyone, I have a problem that I cannot understand on my prestashop 1.7.8.2, I have installed the official modules prestashop metrics and PS Facebook v1.14.0 of PrestaShop and, logged into the marketplace from the prestashop administrative panel, but once installed by clicking on the configure button, keep giving me the same error below:

An unexpected error appears to have occurred
Error sent by Addons. You may be not allowed to download this module.
[Exception 0]

Can you help me solve?

### Steps to reproduce

Error sent by Addons. You may be not allowed to download this module.

[Exception 0]

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

PHP 7.3 (ea-php73)

### If your bug is related to a module, specify its name and its version

prestashop metrics e PS Facebook v1.14.0

**Comment by SharakPL** [comment]
I get this too lately. Looks like required dependencies aren't handled properly. Try installing **ps_account** and **ps_eventbus** modules if you don't have them yet and of course **psaddonsconnect**

**Comment by hibatallahAouadni** [comment]
Hello @michybetti 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must fill the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: thanks @SharakPL for your quick reply :rocket: 

Thanks!

**Comment by michybetti** [comment]
> Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must fill the template to submit a complete bug report**.
> 
> Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.
> 
> PS: thanks @SharakPL for your quick reply 🚀

Hi thanks for the reply

I did not understand what modules to install that you call

ps_account and ps_eventbus and psaddonsconnect

I searched the marketplace but it can't find them

**Comment by SharakPL** [comment]
I noticed this too. It's like this modules where never there. That's weird 🤔

**Comment by hibatallahAouadni** [comment]
> I noticed this too. It's like this modules where never there. That's weird

Ping @SharakPL are you talking about in **BO**>**Module Catalog**?

**Comment by SharakPL** [comment]
Yes, although now they are available. Don't know what happened.
Unstable modules, complete chaos with translations, messed up admin panel - I've only switched to 1.7 last summer and already think about going back to 1.6, because experience with 1.7 is just horrible on every step :/
