### ISSUE TITLE
can't enable mode debug or edit products

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#27392]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

When I try to activate debug mode on my PrestaShop, I get this error message

Error: Unable to know if debug mode is enabled. Make sure the /home/xxxxxx/public_html/app/../config/defines.inc.php file has the correct permissions.
I do not see any file defines.inc.php in in the path app/../config/ indicated by my PS

I emptied the cache also deleted the dev and prod files but it's still the same

![image](https://user-images.githubusercontent.com/11594433/150047476-1f6f2464-43a4-4693-9ad5-a09f86a4b6ec.png)

It is not possible to modify the products

![image](https://user-images.githubusercontent.com/11594433/150048590-08a67242-d1a1-4128-9258-8d0dccb9bdd6.png)

I activated the debug mode from the file /public_html/config/defines.inc.php but no error is displayed to locate the problem

Regards

### Expected behavior

Activation mode debug and edit products

### Steps to reproduce

1 go to **Paramètres avancés**
then **Performances** and enable **Mode debug**

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4.22

**Comment by hibatallahAouadni** [comment]
Hello @go-sudo 

I think you should check and change the access riht of this file `/your_shop/config/defines.inc.php`.
Cause in this file, you can enable the debug mode even manually :wink: 

![image](https://user-images.githubusercontent.com/23308427/150154469-12a1a127-21ec-4771-938a-cd1615dce30b.png)

Closing this issue :relaxed: 
Thanks!
