### ISSUE TITLE
PLACE ORDER button does not work as designed

### ISSUE THREAD

**Issue by Heinrich-Ffm** [PrestaShop/PrestaShop#27409]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

As soon as you disable 'Terms of service' under 'Order settings' and only one payment method is active, PLACE ORDER button in checkout doesn't work as designed (stays gray = inactive)

Problem can be reproduced in demo.prestashop.com.

### Expected behavior

PLACE ORDER Button should be blue / active

### Steps to reproduce

Backend
Configure
Shop parameters
Order Settings
Set 'Terms of Service' = No

Backend
Improve
Payments
Preferences
Set only 'wire payment' as active

Put an article in cart
checkout
PLACE ORDER Button is gray (inactive), mouse over shows forbidden sign (Nevertheless button works)

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.3.33

**Comment by hibatallahAouadni** [comment]
Hello @HeinrichKarl 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #9927. 
It's already fixed on develop with this PR #22389.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #9927

**Comment by Heinrich-Ffm** [comment]
Hi,
you are sure, it's the same? In my case you don't have a cart amount of 0.
It's the combination of only one payment method and deactivated 'Terms of service'.
Besides that, the problem is really old.

**Comment by hibatallahAouadni** [comment]
> Besides that, the problem is really old.

Exactly the problem is really old and you can check on develop, you will see that the issue is well fixed ;)

**Comment by cuatrolatas** [comment]
Hi,

Sorry, but the problem still continues (PrestaShop 1.7.8.3).

If you set up a **single payment method** (for example "Pay by bank wire") and disable the TOS option, the "Place order" button stays gray.

Thanks!

![single payment method](https://user-images.githubusercontent.com/100352263/155837549-857f876f-6b75-4340-b48d-88930351b1cf.png)
