### ISSUE TITLE
Issues with null values inside the Order::getCustomerOrders logic

### ISSUE THREAD

**Issue by bogdanbeniaminb** [PrestaShop/PrestaShop#27402]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The current (master branch) code has some issues with how it handles null values. There are 2 ways to trigger this:
- create a custom order state, apply it to an order, then delete it directly from the database (I know this is not the right way to do this, this is a bug in the code which does such a thing, because the order state should only be marked as "removed", but the Prestashop code should handle this situation gracefully, not fail completely)
- if `id_order_state` is set to null on an order (by another failing module, of course, but the Prestashop code should again handle this gracefully).

The result is that we are thrown a "Notice" ("Warning" in PHP 8) when accessing the customer in the backoffice or when accessing the customer order history on the frontoffice, because we are `Trying to access array offset on value of type null`.

### Expected behavior

The issue is due to how nulls are handled in the following block of code:
```php title="Order.php"
       foreach ($res as $key => $val) {
            // In case order creation crashed midway some data might be absent
            $orderState = !empty($val['id_order_state']) ? $indexedOrderStates[$val['id_order_state']] : null;
            $res[$key]['order_state'] = $orderState['name'] ?: null;
            $res[$key]['invoice'] = $orderState['invoice'] ?: null;
            $res[$key]['order_state_color'] = $orderState['color'] ?: null;
        }
```

In the case where `$val['id_order_state']` is empty (null or '', for example), `$orderState` becomes `null`. But right on the next lines it is accessed as if it weren't null. `$orderState['name'] ?: null` will throw a notice on PHP 7.4 and a warning on PHP 8.0 (perhaps this will change to an Exception in later versions of PHP, as it often happens these days).

The correct code should use the null coalescing operator, introduced in PHP 7.0:
```php
$res[$key]['order_state'] = $orderState['name'] ?? null ?: null;
```

The second issue is when $indexedOrderStates doesn't have the corresponding index (`$val['id_order_state']`) - e.g. when a badly-written module deletes it directly from the database. In this case, the assignment isn't correct again, because it's accessing an inexistent index. This should be corrected using the null coalescing operator again:
```php
            $orderState = !empty($val['id_order_state']) ? ($indexedOrderStates[$val['id_order_state']] ?? null) : null;
```

### Steps to reproduce

- create a custom order state, apply it to an order, then delete it directly from the database (I know this is not the right way to do this, this is a bug in the code which does such a thing, because the order state should only be marked as "removed", but the Prestashop code should handle this situation gracefully, not fail completely)
- if `id_order_state` is set to `null` on an order (by another failing module, of course, but the Prestashop code should again handle this gracefully).
- in both cases, try to access the customer in the backoffice, or the orders history in the "My account" area on the frontend.

### PrestaShop version(s) where the bug happened

1.7.7.0 - 1.7.8.2 - develop

### PHP version(s) where the bug happened

7.4

**Comment by bogdanbeniaminb** [comment]
![image](https://user-images.githubusercontent.com/45259752/150180682-8e15ebd9-3b02-45e8-bf33-6ed57024bcaf.png)

**Comment by bogdanbeniaminb** [comment]
This is NOT a duplicate of https://github.com/PrestaShop/PrestaShop/pull/19581, it just displays an issue that was not handled completely when https://github.com/PrestaShop/PrestaShop/pull/19581 was handled. The fix to that bug doesn't "gracefully fail" when modules misbehave and do things the wrong way (removing the order state from the database directly, for example).

**Comment by hibatallahAouadni** [comment]
Hello @bogdanbeniaminb 

Do you mean when we create an order_state and assigned it to an Order, then delete it, you encounter this exception?
In my case, following these steps, I didn't encounter any issue:

1. **BO>CONFIGURE>Shop Parameters>Order Settings**
2. Create a new `Order_state` (ex: **`Shake it off`** :grin: )
3. **BO>SELL>Orders>Orders**
4. Change an Order's state to Shake it off
5. Back to **Order Settings** page
6. Delete the `order_state` **`Shake it off`**
7. Back to **Orders** page
8. See no error
![image](https://user-images.githubusercontent.com/23308427/150328194-94b0f922-6c64-4b97-b124-139ca598ddce.png)
9. Go to **FO>Account>Order history and details**
10. No error
![image](https://user-images.githubusercontent.com/23308427/150328238-3cdf2990-dbb9-491a-bf26-e14812388e20.png)
11. Click on Order's **Details**
12. No error 
![image](https://user-images.githubusercontent.com/23308427/150328260-0a4d67f5-077f-4a52-a0ba-212dc321efc1.png)

Please check and feedback.
Thanks!

**Comment by bogdanbeniaminb** [comment]
> Hello @bogdanbeniaminb
> 
> Do you mean when we create an order_state and assigned it to an Order, then delete it, you encounter this exception? In my case, following these steps, I didn't encounter any issue:
> 
>     1. **BO>CONFIGURE>Shop Parameters>Order Settings**
> 
>     2. Create a new `Order_state` (ex: **`Shake it off`** grin )
> 
>     3. **BO>SELL>Orders>Orders**
> 
>     4. Change an Order's state to Shake it off
> 
>     5. Back to **Order Settings** page
> 
>     6. Delete the `order_state` **`Shake it off`**
> 
>     7. Back to **Orders** page
> 
>     8. See no error
>        ![image](https://user-images.githubusercontent.com/23308427/150328194-94b0f922-6c64-4b97-b124-139ca598ddce.png)
> 
>     9. Go to **FO>Account>Order history and details**
> 
>     10. No error
>         ![image](https://user-images.githubusercontent.com/23308427/150328238-3cdf2990-dbb9-491a-bf26-e14812388e20.png)
> 
>     11. Click on Order's **Details**
> 
>     12. No error
>         ![image](https://user-images.githubusercontent.com/23308427/150328260-0a4d67f5-077f-4a52-a0ba-212dc321efc1.png)
> 
> 
> Please check and feedback. Thanks!

Hello, @hibatallahAouadni .

As mentioned in the issue (and the attached PR) description, the "deletion" step is NOT done through the back-office. There was a previous PR that fixed the back-office by just adding a "deleted" attribute on order statuses, so that they still remain in the database. I'm not talking about that workflow. The deletion step in this PR's case is done by directly deleting the order status in the database. There are third-party module that directly delete their order statuses from the database and this creates this issue. Although the issue is the module itself (or the validation process for modules, which is not properly implemented, IMHO), the end result is that the users cannot access those orders any more (if they have debug mode enabled). Another way this happens (and it has happened to us) is that the order creation or update process has a bug and the order status becomes `0`. Again, this triggers the problem.

**If you look at the current (old) code and at the attached PR, you'll see that the issue is real. You cannot make a variable `null` and then try to access its properties.**

So, to replicate the bug, you need to delete the order status directly from the database, as some modules still do, or set the order status to `0` or `null`, as it sometimes happens when the update process fails. 

Also, you won't see the error on the "Order details" page, but on the customer details (the affected function is `Order::getCustomerOrders`), where you have a list of the customer's orders.

Thank you.

**Comment by hibatallahAouadni** [comment]
Hello @bogdanbeniaminb 

> There are third-party module that directly delete their order statuses from the database and this creates this issue.

As you know we do not fix a third-party module issue, so you need to contact the Module's Developer to fix the issue :wink: 

> Also, you won't see the error on the "Order details" page, but on the customer details (the affected function is Order::getCustomerOrders), where you have a list of the customer's orders.

I don't see any issue, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/150336236-173c7384-5dd9-4f10-b8c0-b172245e0c81.png)

Please check and feedback.
Thanks!

**Comment by bogdanbeniaminb** [comment]
Hello, @hibatallahAouadni . 

> I don't see any issue, see the attached screenshot below:

Did you actually delete the order status from the database, as mentioned in the issue description and my previous comment? Because I can still see the order status in your screenshot, which denotes it's still in the database.

> As you know we do not fix a third-party module issue, so you need to contact the Module's Developer to fix the issue.

Yes, I know. Still, you're selling those third-party modules on the Addons marketplace and take a large margin of the profit. Also, the way that they do this wrongly doesn't excuse the bug that is in Prestashop's code.

To be clear, this issue wasn't opened because I personally need help. I opened this because on 2 large store websites that the company I work for has built we have come across this same issue. We fixed Prestashop's code on these websites, but we also want to help the upstream. The issue report was created as a reference for the PR we also submitted (https://github.com/PrestaShop/PrestaShop/pull/27403). And, as mentioned before, you only need to see the code to realise the bug is there and that it's real. You have to decide whether to try and blame third-party developers or accept that Prestashop's own code has issues too. (And there's a long discussion to be had here as well... the Prestashop ecosystem is dying, actually, partly because of how third-party modules validation is done by the Prestashop Addons team. Many obvious bugs and issues are just ignored, while outdated "standards" are enforced. More than 90% of the third-party plugins our clients use in their website have very poorly written code, things that you will never see with open-source plugins like those for WordPress or Laravel. And the fact that Prestashop is taking high profit margins should have been an assurance that they don't allow bad code to be sold).

Thank you.

**Comment by hibatallahAouadni** [comment]
Hello @bogdanbeniaminb 

IMHO, it's so risky and highly not recommended to delete anything from the database and that 's why we fix this issue #19098 in this way. Let's check with the Developer Team.

> the Prestashop ecosystem is dying, actually, partly because of how third-party modules validation is done by the Prestashop Addons team. Many obvious bugs and issues are just ignored, while outdated "standards" are enforced. More than 90% of the third-party plugins our clients use in their website have very poorly written code, things that you will never see with open-source plugins like those for WordPress or Laravel. And the fact that Prestashop is taking high profit margins should have been an assurance that they don't allow bad code to be sold).

Ping @PrestaShop/prestashop-core-developers wdyt of this issue?
Thanks in advance :pray:

**Comment by bogdanbeniaminb** [comment]
@hibatallahAouadni The bug is specifically related to code, not to the clients using the back-office. I'm a developer. In code you do queries directly on the database. This is what Prestashop does, this is what modules do, this is what code does in general. You can also use existing Models that handle the database for you, but this doesn't mean they don't fail sometimes. And if an id_order_state value is incorrect, Prestashop should not simply fail with a "trying to access array index on null" error.

**Comment by matks** [comment]
> There are third-party module that directly delete their order statuses from the database and this creates this issue.

PrestaShop Core should not try to protect merchants against badly built modules. This is a fight we cannot win and we should not do it. It's module developers responsibility to write valid code, not our responsibility to correct their mistakes.

> Yes, I know. Still, you're selling those third-party modules on the Addons marketplace and take a large margin of the profit.

We are selling nothing. This repository is not affiliated with addons.prestashop.com. This GitHub repository is related to www.prestashop-project.org .

> To be clear, this issue wasn't opened because I personally need help. I opened this because on 2 large store websites that the company I work for has built we have come across this same issue. We fixed Prestashop's code on these websites, but we also want to help the upstream.

This is good 👍 helping upstream is a great way to improve the software for everybody

> You have to decide whether to try and blame third-party developers

I'm not going to "blame" third-party developers however I stand that it is module developers responsibility to write valid code, not our responsibility to correct their mistakes. If I write bad code using Symfony framework or Laravel framework, it's my mistake, it's not Symfony or Laravel or even PHP that should handle my bad code.

> or accept that Prestashop's own code has issues too

It's OK we know there is probably more than a thousand issues in PrestaShop code, just like any software, Symfony, Laravel, Wordpress, PHP even Linux. I suggest you read this great article https://m.signalvnoise.com/software-has-bugs-this-is-normal/

> the Prestashop ecosystem is dying

Last time I checked PrestaShop ecosystem was actually doing great

> partly because of how third-party modules validation is done by the Prestashop Addons team.

As said before you should reach out to addons.prestashop.com this is not this repository scope

@bogdanbeniaminb I agree PrestaShop code can be improved

- we can use the null coalescing operator as you mentioned
- or we can also add validation that will detect such bad cases and throw an exception to stop the processing

But this is an improvement, not a bug.

**Comment by bogdanbeniaminb** [comment]
Thank you, @matks. I did not know this repo is not affiliated with the add-ons marketplace. I would not suppose they should protect their customers if we hadn't gone through the validation process for a module and we were prevented from publishing it because they were enforcing obsolete or unnecessary standards. And then you see all these modules that passed their validation and the code is really terrible.. This makes you draw some conclusions.

Thank you for your detailed answers. I really appreciate it.

**Comment by hibatallahAouadni** [comment]
Ping @kpodemski or @PrestaShop/committers  can someone please transfer this issue to Discussion tab as it's a feature to improve the code :pray:
