### ISSUE TITLE
Support 410 status code for discontinued products

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#27413]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Describe the solution you'd like

Permanent discontinued products should return 410, temporary inactives products 404 status code just here
![image](https://user-images.githubusercontent.com/16720275/150373164-b2f617c3-7596-4cf6-a4fe-c6d202a5e8c0.png)

https://github.com/PrestaShop/prestashop-specs/pull/299

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by jf-viguier** [comment]
cf https://github.com/PrestaShop/PrestaShop/issues/19678#issuecomment-651141971

**Comment by hibatallahAouadni** [comment]
Hello @jf-viguier 


Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon.

We are waiting for your PR 🚀 

Thank you

**Comment by jf-viguier** [comment]
The spec is simple : add 410 status, just like 404 in the dropdown list.

**Comment by jf-viguier** [comment]
RFC is there https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.9

**Comment by jf-viguier** [comment]
> we strongly suggest you consider hiring a specialist to help you create it

I'll hire myself one day ;-)

**Comment by Tanguy-SALMON** [comment]
Well done!
Now, some shops will reduce there number of 404 dramatically.

**Comment by jf-viguier** [comment]
> I'll hire myself one day ;-)

Done. 
You can [hire me](https://twitter.com/jfviguier) if you search a terrible specialist ;-)

**Comment by Progi1984** [comment]
Fixed by @jf-viguier in #27467 & tested by @hibatallahAouadni
