### ISSUE TITLE
Webservice API error Undefined offset when enabling multilanguage

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#27411]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Try to run this API Call

API CALL TO:

`/api/cart_rules
`
METOD POST

BODY

```
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<cart_rule>
<date_from><![CDATA[{{formatDate(now; "YYYY-MM-DD HH:MM:SS")}}]]></date_from>
<date_to><![CDATA[{{formatDate(addDays(now; 1); "YYYY-MM-DD")}} 23:59:59]]></date_to>
<name><language id="1" xlink:href="https://www.vinove.it/api/languages/1"><![CDATA[SCONTO CARRELLO {{3.firstname}} {{3.lastname}}]]></language></name>
<code><![CDATA[{{upper(base64((3.id) + "*" + formatDate(now; "SS")))}}]]></code>
<reduction_percent><![CDATA[5.00]]></reduction_percent>
<active><![CDATA[1]]></active>
<id_customer><![CDATA[{{3.id}}]]></id_customer>
<quantity><![CDATA[1]]></quantity>
<description><![CDATA[ Sconto valido 24h sul tuo carrello ]]></description>
<quantity_per_user><![CDATA[1]]></quantity_per_user>
</cart_rule>
</prestashop>
```

Retunr this error
```
[500] [PHP Notice #8] Undefined offset: 2 (/var/www/html/vinove/classes/webservice/WebserviceOutputJSON.php, line 98)
[PHP Notice #8] Undefined offset: 3 (/var/www/html/vinove/classes/webservice/WebserviceOutputJSON.php, line 98)
[PHP Notice #8] Undefined offset: 4 (/var/www/html/vinove/classes/webservice/WebserviceOutputJSON.php, line 98)
```

### Expected behavior

Cart rule applied with only language 1 (default) and other language empty

### Steps to reproduce

1. Instal PS without data
2. Make an API CALL
3. Pass the language "1" field name
4. Check output JSON

### PrestaShop version(s) where the bug happened

1.7.6.9

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment]
Related to #26199

**Comment by hibatallahAouadni** [comment]
Hello @matteolavaggi 

Thanks for reporting the issue!
I reproduce the issue only with PS1780 and PS1782, it seems a regression on 1.7.8.0, cause I didn't reproduce it with PS1778.
See the attached screenshots below:

**PS1782** :x: 

![image](https://user-images.githubusercontent.com/23308427/150437598-e7575c5b-7a4b-4d3f-9a00-ef00a32c1e97.png)

**PS1778** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/23308427/150437631-5ba77cc2-bef9-4e64-ad0f-ac05450f0490.png)

I use same body for both versions:
```
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<cart_rule>
<date_from>2022-01-20 23:00:00</date_from>
<date_to>2022-02-20 23:59:59</date_to>
<name><language id="1">Cart Rule with -10% promotion</language></name>
<code>CART3DAN</code>
<reduction_percent>5</reduction_percent>
<active>1</active>
<id_customer>3</id_customer>
<quantity>1</quantity>
<description>sconto valido 24h sul tuo carrello</description>
<quantity_per_user>1</quantity_per_user>
</cart_rule>
</prestashop>
```

Ping @PrestaShop/prestashop-core-developers this issue I only manage to reproduce on `PS1780` and `PS1782`. 
:exclamation:  **I didn't reproduce it on `PS1778` and `develop`** :exclamation:
WDYT? should I close the issue?

Thanks in advance :pray:

**Comment by matteolavaggi** [comment]
Have you tested with ps 1.7.6.9 ? Response is different from the error you get on PS 1.7.8.2 .

the manaule part for api in the single language section is very sparse in information.  Specifically, it is indicated that the response in the case of a single language is different, but a different api call is used than those shown for the multilingual, and it is not clearly specified if the syntax to be used must be different!  this call was created starting from the response generated by prestashop in single language mode, which should be correct... Any idea ?

**Comment by matks** [comment]
> ❗ I didn't reproduce it on PS1778 and develop ❗

Maybe on `develop` a side-effect hides the code but I think this bug should be explored so that we know why it can be reproduced on 1.7.8.x and not on develop

**Comment by hibatallahAouadni** [comment]
Hello @matteolavaggi 

> Have you tested with ps 1.7.6.9 ? Response is different from the error you get on PS 1.7.8.2 .

I didn't manage to reproduce the issue with PS1769, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/150991549-a9173be7-73fb-4a0a-9627-5aeb6e6dc0fa.png)

Please check and feedback.
Thanks!

**Comment by hibatallahAouadni** [comment]
I'm closing this issue as it seems bi fixed on develop 8.0.0 :wink:

**Comment by jf-viguier** [comment]
@hibatallahAouadni I've fixed the bug in 8.0.0 here https://github.com/PrestaShop/PrestaShop/pull/24403 but it's a regression from 1.7.8 and should be fixed before this summer I guess.

**Comment by hibatallahAouadni** [comment]
Hello @jf-viguier 

Thanks for the note :rocket: 
Yep, you're right as this issue is a regression on 178x, it should be fixed on 178x.
So, we're waiting for your PR :rocket: 
As usual you're fascinating :clap: 

Thanks in adavance :pray:

**Comment by Progi1984** [comment]
Fixed by @jf-viguier in #27622 and tested by @khouloudbelguith

**Comment by matteolavaggi** [comment]
Hi to all, this fix can be applied to ps 1.7.6.9 directly without upgrading
all the code? It's quite impossible to upgrade a ps store without broking
almost all , so there is a way I can update and fix this bug only on
1.7.6.9? If someone can help me I will appreciate.

Il Lun 14 Feb 2022, 13:46 Progi1984 ***@***.***> ha scritto:

**Comment by gerdus** [comment]
@matteolavaggi 
You can just replace the existing file /webservice/dispatcher.php
with https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/webservice/dispatcher.php

**Comment by jolelievre** [comment]
This issue is reopened as the suggested (and merged) solution to integrate the Symfony kernel into the webservice dispatcher is not adapted Legacy environments such as webservices should NEVER integrate the symfony kernel

This PR introduces the revert of Symfony kernel along with an alternative solution that fixes the initial issue related to multilang entities:
https://github.com/PrestaShop/PrestaShop/pull/27766
