### ISSUE TITLE
PS 1.7.7.8 Webservice pointing to non existing carrier

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#27415]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If you do something like:

https://your_shop/api/orders?filter%5Bcurrent_state%5D=%5B3%7C6%5D

You'll get a list of orders.

Then you can do:

https://your_shop/api/orders/3

and it will tell you multiple info, namely, id_carrier

Problem: everytime you update a carrier the id changes, so you don't get correct info and you might end with an error 404 when doing for exempl:

https://your_shop/api/carriers/40

### Expected behavior

Webservice should act in a different way to keep track of carriers

### Steps to reproduce

Create an order.

Change the carrier settings on the backoffice so the ID also changes.

Procede as I said at bug description

### PrestaShop version(s) where the bug happened

1.7.7.8

### PHP version(s) where the bug happened

7.2

**Comment by HanaRebaiQA** [comment]
Hello @seederp2p 

Thanks for your report.
Could you please provide us more information and screen-shots about the steps to reproduce.

May this #11945 help you ?

Thanks!

**Comment by seederp2p** [comment]
@HanaRebaiQA if you follow the steps I provided you'll find this issue.

The ticket you provided has nothing to do with what I'm describing here. ;)

Here I'm just describing a "reading" behavior of the API.

Cheers.

**Comment by florine2623** [comment]
Hello @seederp2p ,

I have reproduced your issue on 1.7.7.x, 1.7.8 and develop.
I think it is related to : https://github.com/PrestaShop/PrestaShop/issues/18277
Could you check and confirm ?

Thanks!

**Comment by seederp2p** [comment]
> Hello @seederp2p ,
> 
> I have reproduced your issue on 1.7.7.x, 1.7.8 and develop. I think it is related to : #18277 Could you check and confirm ?
> 
> Thanks!

Yes, It's related.

**Comment by florine2623** [comment]
@seederp2p , if it is related, then I will close this issue. You can subscribe to this [issue](https://github.com/PrestaShop/PrestaShop/issues/18277) to be informed of when it will be fixed.

Thanks!
