### ISSUE TITLE
Undefined index: product blockwishlistviewstemplat.php line 28 with enabled debug mode

### ISSUE THREAD

**Issue by KoreLewi** [PrestaShop/PrestaShop#27419]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When the debug mode is enabled, I cannot access the shop front office because of a notice from the blockwishlist module.

ContextErrorException
Notice: Undefined index: product
.blockwishlistviewstemplat.php line 28

I have cache disabled.

### Steps to reproduce

Install and enable blockwishlist module on PrestaShop 1.7.8.2
Enable debug mode
Try to access the shop front office

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

blockwishlist v2.0.1

**Comment by HanaRebaiQA** [comment]
Hello @KoreLewi 

I was unable to reproduce your issue.
https://watch.screencastify.com/v/qMTUNjmfw1cxQgjB7fbh

Could you please check again ?

Thanks!

**Comment by KoreLewi** [comment]
Hi @HanaRebaiQA 

Thank you for your reply.

The error was caused by the theme used. It works with the classic theme.

Regards,
Levi
