### ISSUE TITLE
ps_imageslider - BO Configuration throws an exception

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#27423]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I have an exception when trying to configure the image slider module :
<img width="1086" alt="Screenshot 2022-01-20 at 11 53 04" src="https://user-images.githubusercontent.com/16019289/150516617-de9387cf-f7d4-48fd-a957-c08b42fcc039.png">

### Expected behavior

I should be able to configure the Image Slider module :
<img width="1212" alt="Screenshot 2022-01-21 at 12 17 56" src="https://user-images.githubusercontent.com/16019289/150518194-57116132-c953-4a8b-9596-c06017ecee5a.png">

### Steps to reproduce

1. Go to BO > Modules > Click Configure ps_imageslider
2. You will see an error ⛔ 

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_imageslider v3.0.1

**Comment by mparvazi** [comment]
Hello @florine2623 

https://github.com/PrestaShop/ps_imageslider/pull/67#issuecomment-1017592850

**Comment by kpodemski** [comment]
Hello @mparvazi 

In related PR, I've fixed this issue. There's no need to access `$something->fields_form` and have it inside PHPStan exceptions.
