### ISSUE TITLE
Improve order return controller

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#27420]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Add a button and sort the list by DESC

### Describe the solution you'd like

I would like to add an **add and stay button**, and sort the returns list correctly.

The **add and stay** button is useful because there is a link to the order

By default 1 2 3 4 would become 4 3 2 1 which is better for the merchant 

### Additional context

![Capture d’écran de 2022-01-21 11-33-34](https://user-images.githubusercontent.com/5064590/150512354-c4ac81c3-31c0-433b-bdf3-f5afbab430c0.png)
![Capture d’écran de 2022-01-21 11-33-29](https://user-images.githubusercontent.com/5064590/150512363-7cff262c-d5a8-4441-9f14-d8d52cd2e1f7.png)
### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [x] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by HanaRebaiQA** [comment]
Hello @okom3pom 

Thanks for your suggestion and for you PR.
The Product Team will take it into consideration for future developments.

Thanks!

**Comment by PululuK** [comment]
Fixed by #27421
