### ISSUE TITLE
Registration form in Confirmation order page not working

### ISSUE THREAD

**Issue by gadnis** [PrestaShop/PrestaShop#27431]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi, after placing an order as a guest in FOH I got the usual Confirmation order page with success message and so on. 
At the bottom of the page there's the registration form - "Save time on your next order, sign up now".

![Screenshot 2022-01-21 at 17 12 38](https://user-images.githubusercontent.com/10948341/150551276-b9211aba-9a95-4d77-88fd-d79a9d82e943.png)

After submit the form it brings me to the login page without any messages of success or failure. 
Then I try to login with email and password given before but authentication failed. 

There's also no new customer found in database `ps_customer` table. Only the old guest customer.

I should mention that the form submission still not work if I fill it with totally different credentials.

### Expected behavior

Guest customer should be converted to a registered customer.

### Steps to reproduce

1. Add to cart product with the cost greater than 0
2. Proceed to checkout
3. Checkout step 1 "Personal information" - choose "Order as a guest" and fill all required fields (except password)
4. Fill any address in "Addresses" step
5. Choose any shipping method in "Shipping method" step
6. Choose bank_wire in "Payment" step
7. Press "Order with obligation to pay"
8. Scroll down confirmation page until you see customer registration form with title "Save time on your next order, sign up now"
9. Fill the form with required credentials. Note: it does not matter if they match credentials that you filled before
10. Submit the form
11. Report a bug 😁 

### PrestaShop version(s) where the bug happened

1.7.6.8

### PHP version(s) where the bug happened

7.2

**Comment by Hlavtox** [comment]
I fixed it on develop a while ago, it's gonna be fine in next version. ;-)

**Comment by gadnis** [comment]
@Hlavtox could you write a link of pull request where I could check what was done?  Unfortunately our shop is stuck with 1.7.6.9 version because of some paid modules..

**Comment by Hlavtox** [comment]
https://github.com/PrestaShop/PrestaShop/pull/25395

**Comment by gadnis** [comment]
Thank you very much @Hlavtox

**Comment by florine2623** [comment]
Hello @gadnis ,

As it is fixed, I will close this issue.
Thanks!
