### ISSUE TITLE
[Improvement] The Statistics controller is generation noise at the server logs

### ISSUE THREAD

**Issue by Guisardo** [PrestaShop/PrestaShop#27449]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The Statistics controller should be mark as ajax to prevent the unnecessary code execution and unnecessary logging as the core tries to process smarty templates for the requests.

### Expected behavior

Navigating the frontend should collect the users information but shouldn't log errors nor warnings of invalid or unassigned templates on the server related to the statistics requests.

### Steps to reproduce

(with the php and server logs enabled)
1.- Navigate the front end
2.- Confirm that the user was tracked by PS
At the server logs you will notice errors about $template being missing. This is because the controller tries to parse a template that is not defined because is actually an ajax controller.

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4.3

**Comment by florine2623** [comment]
Hello @Guisardo ,

I can't reproduce your issue in PS 1.7.8.2, on my end, the logs are empty. Only things that are logged are in the BO > Advanced Parameters.
Is there a specific page that you visit to trigger the errors in the server log ?
Could you send an example of what you have ?

Thanks!

**Comment by matks** [comment]
I think this is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/20921

**Comment by Guisardo** [comment]
RIght on @matks , lets push that fix and it should fix this one too.
Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #20921
