### ISSUE TITLE
Fix php notices while loading subtotals in ps_shoppingcart

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/PrestaShop#27447]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

https://github.com/PrestaShop/ps_shoppingcart/blob/5ecb9ae77bf58ab2e3254ebda76404425d2ac643/ps_shoppingcart.tpl#L34-L39
This will throw PHP notices since `$cart.subtotals.discounts` and `$cart.subtotals.tax` [can be null](https://github.com/PrestaShop/PrestaShop/blob/db334ee2069e946be7703cbca4b1168681d5a86b/src/Adapter/Presenter/Cart/CartPresenter.php#L338-L394)

### Expected behavior

Fixed in https://github.com/PrestaShop/ps_shoppingcart/pull/83

### Steps to reproduce

1. Enable debug mode
1. Disable ps_shoppingcart's template overrides in the theme and load any FO page. Use debug mode or check php_error.log
Force your theme to load original files by removing/renaming /themes/classic/modules/ps_shoppingcart/ps_shoppingcart.tpl
2. Go to FO
3. See error  
![image](https://user-images.githubusercontent.com/16067358/151586333-0eb81188-01eb-49fa-944f-dd5ad9bfcc07.png)

### PrestaShop version(s) where the bug happened

1.7.8.0, 1.7.8.3

### PHP version(s) where the bug happened

PHP v7.4

### If your bug is related to a module, specify its name and its version

ps_shoppingcart v2.0.5

**Comment by florine2623** [comment]
Hello @SharakPL ,

I can't reproduce your issue.
Here are the steps I followed :
1. renamed  the file `/themes/classic/modules/ps_shoppingcart/ps_shoppingcart.tpl` to `_ps_shoppingcart.tpl`
2. Enabled debug module
3. Go to FO and navigate the site
4. Added product with discount to the cart > Check shopping cart : No error
5. Check php_error.log -> no specific error is thrown

What errors are you having ? Could you send an example ?
Thanks

**Comment by SharakPL** [comment]
Use `{$cart.subtotals|dump}` anywhere in the template. It seems `$cart.subtotals.discounts` and `$cart.subtotals.tax` are always **null**. Even when I add discounted products with tax > 0. So this might be yet another bug.
`/src/Adapter/Presenter/Cart/CartPresenter.php` clearly allows `discounts` and `tax` to be null so it will throw php notice.

![obraz](https://user-images.githubusercontent.com/5007456/150828031-5b3931d3-0752-4c26-98c0-6a94f7f03b7b.png)

**Comment by khouloudbelguith** [comment]
Hi @SharakPL,

I manage to reproduce the issue with PS1780 & PS1783 using PHP7.4.
![image](https://user-images.githubusercontent.com/16067358/151585660-6cff7899-3e45-44e8-ab2b-836cc0cb47c1.png)
I tried with PS1778 + php7.2 => ok
I tried with PS1780 + php7.2 => ok
![image](https://user-images.githubusercontent.com/16067358/151585797-0710f938-0de3-434c-a0a1-4dd73aaf8254.png)

PS1778 is not compatible with php7.4.

I’ll add this to the debug roadmap so that it’s fixed.

Thanks for the PR :slightly_smiling_face:

**Comment by SharakPL** [comment]
@khouloudbelguith are you sure it's ok on 1.7.7 and different PHP? Accessing array keys that don't exist should throw a notice even on PHP 5 🤔
