### ISSUE TITLE
Faceted Search - Price range slider sometimes doesn't appear and never come back after filter reset

### ISSUE THREAD

**Issue by thomasalzonne** [PrestaShop/PrestaShop#27458]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When i try to use filters, sometimes i can't use the price range slider because he doesn't appear, i have to refresh the page and it may appear.
![image](https://user-images.githubusercontent.com/52033043/151010835-3d8acbb0-00db-46b1-b2f8-493962c27d91.png)

Second thing, when i can finally use the price filter, i have to use it first and not others filters or it'll disappear. When i reset filters the range slider also disappear.

(second screenshot is when it is working fine, before i use filters)
![image](https://user-images.githubusercontent.com/52033043/151011966-72054f5a-183b-4767-b96a-f8ad910888c7.png)

### Expected behavior

I expect the range slider to appear everytime.

### Steps to reproduce

1. Create products with different price and categories
2. Configure faceted search to enable price filter
3. Go to front office and try to play with the price filter

### PrestaShop version(s) where the bug happened

1.7.7.8

### PHP version(s) where the bug happened

7.3.31

### If your bug is related to a module, specify its name and its version

ps_facetedsearch v3.7.1

**Comment by hibatallahAouadni** [comment]
Hello @thomasalzonne 

I didn't manage to reproduce the issue with PS1778, could you please open your navigator console and make a screenshot :pray: 
And please provide a screenshot from your BO>IMPROVE>Modules>Module Manager>FacetedSearch>Configure (like this one below):

![image](https://user-images.githubusercontent.com/23308427/151049006-676d68c2-91d0-4b7d-b0d4-122de940ad17.png)

Waiting for your feedback.
Thanks!

**Comment by thomasalzonne** [comment]
Hello,

Sorry for the delay, here are the screenshots.

<img width="688" alt="filters" src="https://user-images.githubusercontent.com/52033043/152188000-9117a6b1-045b-44c2-acac-e8fc6345c0f8.png">

<img width="960" alt="consolelogs" src="https://user-images.githubusercontent.com/52033043/152188004-5b0814a0-7b95-4e7d-ba2f-577e57cb4ec9.png">

I got those errors only when the price filter doesn't appear.

**Comment by hibatallahAouadni** [comment]
Hello @thomasalzonne 

Thanks for your feedback!
Could you please switch your theme to Classic, cause it seems the issue is related to your custom theme.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @thomasalzonne 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by bssdigitalmc** [comment]
Hello @thomasalzonne 
I am currently working on PS 1.7.8.10 and have the identical issue that you were describing. Did you end up finding a solution to this? Other than changing the theme back to classic.
I tried adding a price slider addon module but that did not solve the problem either.
Thanks!

Ben
