### ISSUE TITLE
Display out-of-stock label on product listing pages- 404 error

### ISSUE THREAD

**Issue by Peter4661** [PrestaShop/PrestaShop#27452]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Activation of “Display out-of-stock label on product listing pages” results in 404 error . Google indexing / Google webmaster console : url live test

### Steps to reproduce

1. activate Display out-of-stock label on product listing pages
2. test url with Google search console , live url test

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

 7.4.27

**Comment by hibatallahAouadni** [comment]
Hello @Peter4661 

Could you please explain this step more:
> test url with Google search console , live url test

Try to provide more details and a screen record :pray: 
Waiting for your feedback.

Thanks!

**Comment by Peter4661** [comment]
Hello Hibatallah Aouadni,

Thank you for coming back to me.   I will do the requested test later today
and see if it can be reproduced.

Let me give you some background on my observations.

We are in a business struggling to get stock due to world wide shortages.
Last year more and more products ran out of stock with very long delivery times. Up till then, we did not use the Prestashop option to flag 'out-of-stock' .  Mid december we decided to activate the 'out-of-stock label' option.

In the first week of January, we noticed some of our products dropped completely out of Google index, using Google search.
Google search console confirmed, the items were removed from Google index. 😰. Visiting subject pages using Google search console did give a clue, 404 error (page not found).  There were product pages and category listings. On request, Google refused reindex due to 404 error.

However, the real weird thing here, visiting the same pages with desktop or mobile , the page was showing normally, without 404 error 😳.

Wondering about the difference between indexed on non-index pages and categories, the 'out-of-stock' label.  After disabling the  'out-of-stock' label option, forced template and cleared cache, Google accepted the (re-)index requests and most of our URLs are back in the index (for now only 190 URLs to go).

As sayed, I will run the test and  come back to you with the results.

**Comment by Peter4661** [comment]
Ola Hibatallah Aouadni,

I'm coming back to you about the flagged issue with the "out-of-stock"
banner.

I reactivated the function in the back office, forced template and cleared
cache.
Then tested with help of Google search console functionality "test URL
live" if a URL with  "out-of-stock" banner would give 404 error.

NOP. Everything was oké.
So, errors can not be reproduced. I will close the bug report.

Met vriendelijke groet,

Peter Derks
Derks wielersport
Verduinsbos 29
4661NT Halsteren

telefoon +31 624 179 798

www.derks-wielersport.nl


Op di 25 jan. 2022 om 14:53 schreef peter derks <
***@***.***>:

**Comment by hibatallahAouadni** [comment]
@Peter4661 Glad to hear :tada: 
Thanks for your feedback!

**Comment by Peter4661** [comment]
Hello Hibatallah Aouadni,

I have a question about truncate product titles and don't know whom to turn
to. On the PS forum I did not find the answers
Up to version 1.7.8.2 , I know how to set the length of product titles on
product.tpl.

With version 1.7.8.3 there was a change and the previous method does not
work anymore.  Default length of product titles is way too short to make
the product title useful. Could you or one of the developers drop me a note
where to set truncation of product titles in v. 1.7.8.3?

Thank you.

Met vriendelijke groet,

Peter Derks
Derks wielersport
Verduinsbos 29
4661NT Halsteren

telefoon +31 624 179 798

www.derks-wielersport.nl


Op do 27 jan. 2022 om 10:08 schreef Hibatallah Aouadni <
***@***.***>:
