### ISSUE TITLE
BO - Shopping Carts - Some shoppingcarts are duplicated

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27450]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This issue is detected by [nightly](https://nightly.prestashop.com/report/3358) 
https://nightly.prestashop.com/report/3352
https://nightly.prestashop.com/report/3346
Ping @nesrineabdmouleh 
In the BO > Orders > Shopping Carts > some carts are duplicated
![image](https://user-images.githubusercontent.com/16067358/150823972-e7f51fe5-e60b-484f-98d5-a73c421188a3.png)

### Steps to reproduce

1. Go to BO > Orders > Shopping Carts 
2. Delete all `non ordered ` shopping carts
3. Go to FO > Sign in with John Doe
4. Go to BO > Orders > Create an order
5. Choose John Doe & add a product to the cart 
6. Complete the order
7. Go to BO > Orders > Shopping Carts 
8. See error > some duplicated carts

https://user-images.githubusercontent.com/16067358/150824853-bd14a03a-58f0-4095-9d1c-97e9850691c9.mp4

It is ok with PS1778

### PrestaShop version(s) where the bug happened

1.7.8.0, 1.7.8.x, develop

### PHP version(s) where the bug happened

7.3, 7.2

**Comment by Progi1984** [comment]
Fixed by @PierreRambaud in #27459 and tested by @khouloudbelguith
