### ISSUE TITLE
Credit slip prefix now required in all languages

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/PrestaShop#27451]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

_Issue detected by automated tests_

On develop branch, in BO > Orders > Credit slip page, the "Credit slip prefix" input is now required, in all languages.

It was previously not the case in 1.7.8 : The field was not mandatory and could be empty (when the prefix field is empty, there is just no prefix on credit slips and it works fine).

This leads to the following error being displayed : 
"This value should not be blank."

Since there is no default value on the field, it's also quite contradictory.

I checked with PM and dev, this change is apparently not intentional.

Screenshot : 
![credit slip error languages](https://user-images.githubusercontent.com/55688534/150827536-6d62babb-1e1d-4706-bda5-44f1c5ed32a4.png)

### Expected behavior

The filed should not be mandatory.
After a save, below the input, it displays a warning for the language with an empty value.

### Steps to reproduce

0. Have a develop install with at least two languages
1. Go to BO > Orders > Credit slip > Credit slip options block : "Credit slip prefix" is empty.
2. Try to save : The errors are displayed.
3. Fill the input in all languages, save : No error.

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

N/A

**Comment by boubkerbribri** [comment]
Passed the issue on critical since we have errors (on the delete side) every night on the nightly.

**Comment by PululuK** [comment]
Fixed by #27457
