### ISSUE TITLE
Exception in FO when trying to pay order after placing it from the BO

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27462]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An exception is displayed in the FO when trying to pay order after placing it from the BO.

https://user-images.githubusercontent.com/16067358/151031720-ca33daa4-ca7a-4d69-988e-1b764bd71c45.mp4

 

### Expected behavior

No error displayed

### Steps to reproduce

1. Go to BO > Orders > Create a new order
2. Choose a customer & products > check a status & payment order
3. Click on "Proceed to checkout in the FO" > redirection to the FO
4. Complete the order to the last step & before placing the order > go back to the previous tab of the BO 
5. Click on create order > order well created in the BO
6. Go back to the tab of the FO > Click on place order > See exception

![image](https://user-images.githubusercontent.com/16067358/151029303-38e5992f-ead8-4627-b772-e7a41eb06cb9.png)
In the PS1778, we have an exception but not similar to 178
![image](https://user-images.githubusercontent.com/16067358/151029615-6462e599-188a-4abd-b4d0-b3b8e4bcf910.png)

### PrestaShop version(s) where the bug happened

1.7.7.8, 1.7.8.0, 1.7.8.x

### PHP version(s) where the bug happened

7.2

**Comment by khouloudbelguith** [comment]
seems related to https://github.com/PrestaShop/PrestaShop/issues/21714

**Comment by florine2623** [comment]
This is fixed in PS 8.1.x and 9.0.x.

We now have the following message :
<img width="1229" alt="Screenshot 2023-12-27 at 11 38 58" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/27137c95-50a5-4c80-b949-6fcdf83c85af">
