### ISSUE TITLE
Bug of the events functions on the prestashop variable (in core.js)

### ISSUE THREAD

**Issue by tups** [PrestaShop/PrestaShop#27473]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If we want to access `prestashop.selectors` , the logic would be to wait for the `'selectorsInit'` event. So I naturally created a listener:

```jsx
prestashop.on('selectorsInit', () => {
...
});
```
Except that the event never triggers.

### Expected behavior

The event should fire on page load

### Steps to reproduce

Create an event JavaScript in a module or in the theme:
```jsx
prestashop.on('selectorsInit', () => {
...
});
```

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

ALL

**Comment by hibatallahAouadni** [comment]
Hello @tups 

Could you please provide a basic module contains this event to test the issue.
Waiting for your feedback.

Thanks!

**Comment by tups** [comment]
Hello @hibatallahAouadni,

In a simple way, we can do it with a child theme, and just a JS. I put a `console.log` to warn when the `'selectorsInit'` event fires.

Here is the finished child theme:
[classic-child.zip](https://github.com/PrestaShop/PrestaShop/files/7943531/classic-child.zip)

I created a PR #27475 so you can test when it works :)

**Comment by NeOMakinG** [comment]
The event is fired when the $(document).ready is executed right?

I don't really get why you're not able to listen to the event

PS: Gonna test with your child theme rn

**Comment by tups** [comment]
Here with the document ready: 
[classic-child.zip](https://github.com/PrestaShop/PrestaShop/files/7950824/classic-child.zip)

This does not correct the problem.

--
Sorry I just saw that I forgot to put you the anomalies that I found while looking for the bug:

I found three annoying anomalies:

- There are `$(document).ready(() => {` on many events and functions in core.js.
Which is strange given that the file is loaded at the bottom of the page and first in front of all other JS files. So the whole DOM is already accessible, so this event is useless.
- By removing the `$(document).ready(() => {` in the core.js (/themes/_dev/...), we realize that the `emit` functions added to the `prestashop variable ` starts too late (this generates errors in the core.js).
I fixed it, add the event functions on the `prestashop` variable first
- In the “Classic” theme, we see that the event functions are also added to the `prestashop` variable, which makes the events previously triggered in core.js inaccessible. By removing this code, all core and theme events are accessible.

You can see the changes in the PR

**Comment by NeOMakinG** [comment]
I did test with your child, but without your PR

and I see the console log => 
![image](https://user-images.githubusercontent.com/14963751/151371546-7446a386-e1f3-460a-86a7-bc088a7a2d97.png)

with this code:
![image](https://user-images.githubusercontent.com/14963751/151371586-78a0b58f-5c79-486d-99c9-a876f017e242.png)

but with `priority: 60` inside the `config.yml`

So your custom code comes after the `theme.js` asset

**Comment by NeOMakinG** [comment]
@tups 

I tested with your child theme and on your PR's branch, it seems that the child theme is unable to get the event too

Can you come on slack maybe? So we can speak together and update this issue if needed: https://www.prestashop-project.org/slack/

**Comment by NeOMakinG** [comment]
@hibatallahAouadni

I seen with @tups 

There is only one problem: `prestashop.on` et `prestashop.emit` methods are overridden by the theme, while it's not needed because it's already exposed by core. If we do this, the EventEmitter is not the same, so it's impossible to read events from the core!

Selectors are fine, document.ready are needed in order to make selectors overridables!

**Comment by NeOMakinG** [comment]
And I confirm this is not a regression

**Comment by hibatallahAouadni** [comment]
Thanks @NeOMakinG for your quick replies :pray: :rocket:

**Comment by khouloudbelguith** [comment]
Hi @tups,

I tried to install your theme with PS1783
[classic-child.zip](https://github.com/PrestaShop/PrestaShop/files/8117813/classic-child.zip)
But I don't have any errors in the console
I attached a screen record

https://user-images.githubusercontent.com/16067358/155162614-f21861ad-4a74-404f-87fd-f0ad0e844eaa.mp4

Could you please provide us with a demo module or a demo theme to reproduce the issue?

Thanks!

**Comment by tups** [comment]
Hello @khouloudbelguith,
If you take a closer look at your error, you can see that it's a plugin in your Chrome that is generating this.
You can see it because all file links start with ```chrome-extension```

**Comment by khouloudbelguith** [comment]
Hello @tups,
about those errors?
![image](https://user-images.githubusercontent.com/16067358/155168733-8aa3ea78-70d8-4d4a-b402-4e4be2f1e9b2.png)

Those errors occur because I use a chrome extension `screencastify` to record my video.
About the issue, I need to reproduce the problem, I tried to use your theme but I don't have any output in the console

>I put a console.log to warn when the 'selectorsInit' event fires.

So, should I have an output on the console in the FO when I use your theme?

Thanks!

**Comment by tups** [comment]
@khouloudbelguith , console.log messages are in console messages, not errors:
![image](https://user-images.githubusercontent.com/868611/155172853-d04e06af-73c3-45bb-8f3a-738043eef0cb.png)

**Comment by khouloudbelguith** [comment]
@tups, thanks a lot for your feedback.
I tried with PS1783, I don't have `selectorsInit lauch` in the console message.
I attached a screen record

https://user-images.githubusercontent.com/16067358/155176146-fab702d1-749e-4b8f-a27f-a6e204c221fc.mp4

This is the issue, isn't it? I should have a console message?

I tried with your PR, I have an error,
I attached a screen record

https://user-images.githubusercontent.com/16067358/155176411-656b4912-8bb3-4fa0-9788-33d87816a0f8.mp4

Thanks!

**Comment by tups** [comment]
@khouloudbelguith, I just saw that the classic-child file was not returned with @NeOMakinG's correction.

The javascript is triggered too early, here is the corrected theme:
[classic-child.zip](https://github.com/PrestaShop/PrestaShop/files/8118458/classic-child.zip)
 
Sorry for that

**Comment by khouloudbelguith** [comment]
@tups, thanks for your feedback.

I checked your theme ith PS1783
=> Now I have the output
I attached a screen record

https://user-images.githubusercontent.com/16067358/155181154-d8eab449-a994-4a45-803c-0876da037254.mp4

I tried with your PR, I have the exact output now
I attached a screen record

https://user-images.githubusercontent.com/16067358/155182655-49bde457-fe74-4106-92fb-f028e55669de.mp4



So, I have the same behavior with or without the PR. In my case, the event is wel trigged without PR (PS1783)
Did I miss something?

Thanks!

**Comment by tups** [comment]
I had a discussion with @NeOMakinG, because initially I contrasted two anomalies in my eyes:
1. Override of `prestashop.on` and `prestashop.emit` in `classic` theme
2. remove `document.ready` in core.js on some events, to be able to capture them directly.

After our discussion, we came to an agreement, and we just corrected point number one. Because the `document.ready`, you can override them or still listen to the events by adding a `document.ready` in your personal code (even if it's not too much in my practice).

**Comment by NeOMakinG** [comment]
> I had a discussion with @NeOMakinG, because initially I contrasted two anomalies in my eyes:
> 
> 1. Override of `prestashop.on` and `prestashop.emit` in `classic` theme
> 2. remove `document.ready` in core.js on some events, to be able to capture them directly.
> 
> After our discussion, we came to an agreement, and we just corrected point number one. Because the `document.ready`, you can override them or still listen to the events by adding a `document.ready` in your personal code (even if it's not too much in my practice).

To clarify, we need to launch every events from core.js on a loader/ready event, overwise you would be forced to add your asset before the core.js file, which is pretty hard because you need the `prestashop` object

So, events should be fired AFTER your custom script execution, but your custom script should be placed AFTER the corejs file, this is why document.ready is used

In your custom.js, you absolutely don't want to use the document.ready in that situation (`selectorsInit`) because your document.ready execution will be done after the core, so your event listener won't be registered yet
