### ISSUE TITLE
Improve wording tooltip Traffic & SEO > Schema of URLs

### ISSUE THREAD

**Issue by Julievrz** [PrestaShop/PrestaShop#27476]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Following [@MatShir's comment ](https://github.com/PrestaShop/PrestaShop/pull/27234#issuecomment-1011953702) I'd like to suggest a new wording for the tooltip in Traffic & SEO > Schema of URLs.

### Describe the solution you'd like

On Traffic & SEO > Schema of URLs, to add a fixed warning alert before the features (in Admin.Shopparameters.Notification):

'Before making any changes to the default pattern of your URLs, make sure to meet the following requirements:

- The Friendly URL feature must be enabled
- URL rewriting must be activated on your web server
- All mandatory keywords (*) must be included in the route

You should also comply with the syntax:

- Keywords must be in braces {keyword}
- All keywords must be separated
- As long as a keyword has an associated value, you can use the syntax {prepend:keyword:append} to add text before and after it'

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Thanks @Julievrz :wink: 
Please check the labels, if there's a missing label then please add it :pray:

**Comment by ghost** [comment]
@Julievrz && @MatShir if I understand correctly you need something like this?

![Capture d’écran de 2022-01-28 10-31-47](https://user-images.githubusercontent.com/5064590/151522495-ea7ee5ab-4147-44ca-99c2-8ab915ec0467.png)

**Comment by MatShir** [comment]
Yes exactly here but with `alert medium-alert alert-warning` :)

**Comment by ghost** [comment]
Done :) https://github.com/PrestaShop/PrestaShop/pull/27510
