### ISSUE TITLE
BO - Multilanguages - Wishlist - Empty fields when another language is selected

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27474]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > blockwishlist module configuration page, we can change all fields to empty in all languages only the default one.

### Expected behavior

Ping @PrestaShop/product-team, what do you think?
I think that if a field is empty => the default language is displayed
you can edit all fields without filling in all the languages
the default language is mandatory though
if a language has not been set then we must fall back to the default language
 similar behavior here: https://github.com/PrestaShop/PrestaShop/issues/22755

### Steps to reproduce

1. English is the default language
2. Login in the back office. Go to the Blockwishlist module's settings page. Click on the Configuration" tab"
3. select another language for example french 
4. Set all fields to empty and save
5. Go to FO > Select French & create another customer
6. Go to Home > Your account > My wishlists list 
7. See error => no text displayed & an error is displayed in the console 
![image](https://user-images.githubusercontent.com/16067358/151196448-1f4b8bae-30fb-4710-925a-b464939eabd4.png) 
![image](https://user-images.githubusercontent.com/16067358/151196593-2d1dbd82-efe6-4b9f-a0cd-06ac69454811.png)
8. Click on Mywishslit & try to create a new wishlist
9. Click on the list
10. See an error on the title 
![image](https://user-images.githubusercontent.com/16067358/151197019-216dea84-eadb-431a-ae42-6f2cb3783685.png)

### PrestaShop version(s) where the bug happened

1.7.7.8, develop

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

wishlist v2.0.1, v2.1.0

**Comment by NeOMakinG** [comment]
Mainly back-end things, you shouldn't be able to save fields if they are empty I think so
