### ISSUE TITLE
Blockwishlist doesn't work after changing theme

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#27478]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After changing my shop's template, if I try to add a product to my wishlist, it won't work. Only after a reset of the blockwishlist module, am I able to add items to my wishlist.

Child theme :

https://user-images.githubusercontent.com/16019289/151207410-92aa47ce-4b05-4498-a225-f14ebeac6402.mov

After switching back to Classic Theme :

https://user-images.githubusercontent.com/16019289/151207233-ae0583e0-3121-4b52-854b-4eb31035ef10.mov

[child_classic.zip](https://github.com/PrestaShop/PrestaShop/files/7943498/child_classic.zip)

Tested with 
PS 1.7.7.8 + wishlist v2.0.1 => ok
PS 1.7.8.3 + wishlist v2.0.1 => ok
develop + wishlist v2.0.1 => ok

PS 1.7.7.8 + wishlist v2.1.0 => nok
PS 1.7.8.3 + wishlist v2.1.0 => nok
=> So this is a regression from Release v2.1.0

### Expected behavior

Even after changing/switching my template, my customers should be able to add any products to their wishlist.
I should not have to reset my blockwishlist module and loose all configuration.

### Steps to reproduce

1. Go to BO > Design & Logo > Download your child_theme
2. Apply your child_theme
3. Go to FO > Try to add a product to your wishlist : NOK 🚫 
4. Go to BO > Design & Logo > Apply the Classic theme
5. Go to FO > Try to add a product to your wishlist : NOK 🚫 
6. In BO > Modules > Reset block wishlist module
7. Go to FO > Try to add a product to your wishlist OK ✔️ 

### PrestaShop version(s) where the bug happened

1.7.7.8, 1.7.8.3, develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

blockwishlist v2.1.0

**Comment by NeOMakinG** [comment]
Need a backend maintainer to investigate on this

**Comment by khouloudbelguith** [comment]
Hi!

I still have the same issue with PS1785 & 178x branch using the wishlist v2.1.0

https://user-images.githubusercontent.com/16067358/161579846-b9868475-6fcd-47cf-a581-9a8803121aa0.mp4

I checked PS1785 using the wishlist v2.0.1 => ok

https://user-images.githubusercontent.com/16067358/161579950-a9627838-c382-4177-b0dc-6f6c9fad8bc2.mp4

It is a regression in the module.
I will re-open the issue!

Thanks!

**Comment by Progi1984** [comment]
Fixed in #28240.
