### ISSUE TITLE
[BO] Bad display of filters in Faceted Search filters template

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#27472]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Since we change the buttons/switch styles, the filters in filter template of the module Faceted Search have been bad displayed, see the attahced screenshot below:

![image](https://user-images.githubusercontent.com/23308427/151174554-4d4e43ec-8fae-4180-bec8-7c9ad8f29e47.png)

### Expected behavior

That span contains YES/NO shouldn't be displayed:

![image](https://user-images.githubusercontent.com/23308427/151174768-4c0d97cd-5945-432c-a3e5-70983c3ad386.png)

### Steps to reproduce

1. **BO**>**IMPROVE**>**Modules**>**Modules Manager**
2. Serach for the module **Faceted Search**
3. Click on **Configure** button
4. Click on **Edit** button to edit the filters template
5. See error

https://user-images.githubusercontent.com/23308427/151175198-52996918-7206-43a3-9cd4-404eafcb80c3.mp4

### PrestaShop version(s) where the bug happened

1.7.8.0 & develop

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

ps_facetedsearch

**Comment by Progi1984** [comment]
@PierreRambaud `ps_facetedsearch` needs a release for the next patch version.
