### ISSUE TITLE
Unable to find template function 'renderLogo'

### ISSUE THREAD

**Issue by hugofintecture** [PrestaShop/PrestaShop#27477]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I'm working on the Fintecture payment plugin. In our test environnements we have some issues with some redirections.
While being redirected on our validation controller we have this error:

```
(1/1) SmartyException
Unable to find template function 'renderLogo'
in smarty_internal_runtime_tplfunction.php line 50
at Smarty_Internal_Runtime_TplFunction->callTemplateFunction(object(SmartyDevTemplate), 'renderLogo', array(), true)in 0e77c09dbfd3698ed6c027da928371f94a7ecaf6_2.file.header.tpl.php line 124
```

Here's the complete trace.
| Trace |
| ------ |
| <img src="https://user-images.githubusercontent.com/89129201/151204546-b1ec2184-463c-4d23-94db-37afef77dda1.png" width="300">|

Other people have the same problem:

- https://www.prestashop.com/forums/topic/1057050-commande-page-error-500-with-prestashop-checkout-v2155-and-prestashop-1781/
- https://www.prestashop.com/forums/topic/144654-smartycompilerexception/

### Expected behavior

Being redirected to our controller page: index.php?fc=module&module=fintecture&controller=validation

### Steps to reproduce

This does not seem to be systematic and occurs mainly in our environments at the moment.

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.3.32

**Comment by hibatallahAouadni** [comment]
Hello @hugofintecture 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you

**Comment by hugofintecture** [comment]
Hello @hibatallahAouadni I'm sorry but it seems to be an internal PrestaShop bug...

**Comment by hibatallahAouadni** [comment]
Hello @hugofintecture 

So could you please provide clear and concise steps to reproduce the issue :pray: 
Please provide as much as you can infos to help me reproduce the issue.
Waiting for your feedback.

Thanks!

**Comment by hugofintecture** [comment]
I've found the root of the issue. There was a change in the way to show logo in templates in October: https://github.com/PrestaShop/PrestaShop/commit/e0945fdd02d24a04159edb19208cfdcd80f89f0e

So instead of redefining the template we now use `{extends "$layout"}` and it works.

Thanks!

**Comment by myB0B** [comment]
Same problem here !

@hugofintecture how you do that ? > So instead of redefining the template we now use {extends "$layout"} and it works.

**Comment by hugofintecture** [comment]
Just like this:
```
{extends "$layout"}

{block name="content"}
	<section>
		<h2>Title</h2>
	</section>
{/block}
```

**Comment by myB0B** [comment]
thanks it works fine !

**Comment by JSSSX** [comment]
> Just like this:
> 
> ```
> {extends "$layout"}
> 
> {block name="content"}
> 	<section>
> 		<h2>Title</h2>
> 	</section>
> {/block}
> ```

@hugofintecture @myB0B

I am also confronted to this issue on 1.7.8.3 and Paypal 5.5.0 (fresh install with migration, no customer is able to pay with Paypal since this issue generating error 500 with PHP Fatal error:  Uncaught  --> Smarty: Unable to find template function 'renderLogo' <-- ).

May I know on which file / line I have to add this code ? 

Thanks in advance.
