### ISSUE TITLE
blockwishlist - FO - number of products in list is not updated

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#27488]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The number in parenthesis in `BO > My wishlist` and number in parenthesis in the `list` itself do not match.

### Expected behavior

Number in parenthesis should be updated even with deleted and deactivated products.

### Steps to reproduce

1. Add more than 3 different products to your wishlist
2. Go to BO > delete 1 product that is in wishlist
3. Deactivate another product that is in wishlist
4. Go to FO > my wishlist > see that the number in parenthesis doesnt match the real number of product
5. Number doesn't update with deleted and deactivated products

<img width="498" alt="Screenshot 2022-01-27 at 11 13 17" src="https://user-images.githubusercontent.com/16019289/151363905-c0402c57-ed83-4901-b28b-769aa11f0c69.png">
<img width="598" alt="Screenshot 2022-01-27 at 11 13 45" src="https://user-images.githubusercontent.com/16019289/151363913-6495d77c-732e-4c97-9c83-ef3bc82bd35a.png">

### PrestaShop version(s) where the bug happened

1.7.7.8, 1.7.8.3, develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

blockwishlist v2.0.1 and v2.1.0

**Comment by NeOMakinG** [comment]
Need a backend maintainer to investigate on this

**Comment by Progi1984** [comment]
@prestashop/qa-functional Could you check this issue ? I didn't reproduce in local with `dev` branch of the module.
