### ISSUE TITLE
Fix grid data CSV export encoding and allow more formats

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#27483]
### Is your feature request related to a problem?

When you use Prestashop export function, the data looks like this in latest Excel... It cannot properly recognize UTF-8 encoded CSVs. (unless you go through the data import process)
![export](https://user-images.githubusercontent.com/6097524/151335651-68f9f2e2-ccea-41b0-aacb-bc7906050e2c.png)

### Describe the solution you'd like

**Fix current format**
Excel does not recognize the CSV format properly because it's missing BOM in the header of the CSV file. You can test this by opening the file in VS code > click UTF-8 in the bottom > save with encoding > UTF-8 with BOM. Then open it in Excel and see it works fine.

We can add it either manually or use PHPspreadsheet instead of fputcsv and just call **$writer->setUseBOM(true);**.

**Add support for new formats - XLS and XLSX**
- Add new settings to prestashop configuration called "Data export format" / "Select which file format you want to receive when using the export function on listings".
- You could select CSV UTF-8, XLS or XLSX.
- We create another writer for the new formats.

### Additional context

**Legacy exports:**
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/controller/AdminController.php#L1055

**New exports:**
https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Component/CsvResponse.php

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. 

Waiting for your PR :rocket: 

Thank you

**Comment by MatShir** [comment]
Is it related to https://github.com/PrestaShop/PrestaShop/issues/19807 ?

**Comment by Hlavtox** [comment]
@MatShir Yes it's a duplicate, sorry, I didn't find it.

**Comment by hibatallahAouadni** [comment]
Duplicate of #19807
