### ISSUE TITLE
Batch insert does not accept a field with the name "type"

### ISSUE THREAD

**Issue by sefirosweb** [PrestaShop/PrestaShop#27491]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I have a module for insert a huge of values with function: $result = $db->insert('db_table',$arrayData')

https://devdocs.prestashop.com/1.7/development/components/database/db/#insert-multiple-rows-in-the-database-batch-insert

I saw on code if the first value have a "type" field name they convert to array,
This have a sense?

https://github.com/PrestaShop/PrestaShop/blob/880c1700e0bcabd780466c839ae8efc542ec0324/classes/db/Db.php#L429

```php
 if (!is_array($current) || isset($current['type'])) {
            $data = [$data];
        }
```
Maybe changint to:
```php
 if (!is_array($current)) {
            $data = [$data];
        }
```
Is enough?

### Expected behavior

Insert all data to DB

### Steps to reproduce

1.  Create a module or controller using insert batch
2.  Use:
```php
$now = date('Y-m-d H:i:s');
/** @var bool $result */
$result = $db->insert(
    'db_table',
    [
        [
            'name' => 'John Doe',
            'type' => 'random'
        ],
        [
            'name' => 'James',
            'type' => 'val'
        ],
    ]
);
```

### PrestaShop version(s) where the bug happened

1.7.X

### PHP version(s) where the bug happened

7.1

**Comment by hibatallahAouadni** [comment]
Hello @sefirosweb 

Could you please provide a basic module contains this hook, to help me reproducing the issue :pray: 
Waiting for your feedback.

Thanks in advance!

**Comment by sefirosweb** [comment]
Hi, try to make a little module for that,

But you can add these 4 lines anywhere in your code and they will return "false" because you can't insert the data

```php
$result = Db::getInstance()->insert(
    'db_table',
    [
        [
            'name' => 'John Doe',
            'type' => 'random'
        ],
        [
            'name' => 'James',
            'type' => 'val'
        ],
    ]
);
```

**Comment by khouloudbelguith** [comment]
Hi @sefirosweb,

Thanks for your report.
We are waiting for your demo to reproduce the issue.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @sefirosweb 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
