### ISSUE TITLE
Product page v2 Offset bug with tax selector because of multishop checkbox

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#27497]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This bug was found during the QA of this PR https://github.com/PrestaShop/PrestaShop/pull/25464
Here is the initial comment (issue 2) https://github.com/PrestaShop/PrestaShop/pull/25464#issuecomment-1017371158

When the multishop mode is enabled product page now has checkboxes associated to each multishop input
When you click on one of the inputs for price, the checkbox is displayed under
Then click on the tax selector
The panels open but it is lower that the select input, because the checkbox from the input was hidden and it changes the elements position

### Expected behavior

The checkboxes behaviour is correct!! We don't want them to be shown all the time And they should hide when we lose focus (until a modification is made in the input, at that moment it says visible)

We shouldn't have this offset between the selector input and its its selection panel
I guess the panel is placed in absolute positions on the click or something like that but the checkbox is then hidden which changes the display

Not sure how to fix this though, maybe a race condition of js events We can try and hide the checkbox sooner but I'm not sure it's doable

### Steps to reproduce

1. Go to BO > Advanced Parameters > Experimental Features page & Enable Experimental product page
2. Go to BO > Catalog > Products > Edit a product V2
3. In the pricing tab,> Click on the field `Retail price (tax excl.)`, then click on the field `Retail price (tax incl.)`, then click on the `Tax rule`

![image](https://user-images.githubusercontent.com/16067358/150322961-8cbfec3e-d880-41ad-a292-2accf3c190a3.png)

I attached a screen record

https://user-images.githubusercontent.com/16067358/150323081-72c34878-3609-44fc-8e4a-1e57ce18e54c.mp4

### PrestaShop version(s) where the bug happened

8.0

**Comment by lartist** [comment]
I know this Issue is relatively old but I tried to reproduce the bug but I didn't succeed. I can't see any checkbox appear. Do you think this Issue got useless?

**Comment by hibatallahAouadni** [comment]
Fixed on 8.0.0

**Comment by MatShir** [comment]
thanks @lartist for the investigation
