### ISSUE TITLE
Failed opening '/*/themes/classic/lang/lt.php'

### ISSUE THREAD

**Issue by modex9** [PrestaShop/PrestaShop#27508]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In our project, Sentry constantly registers the following error:
**include_once(): Failed opening '/*/themes/classic/lang/lt.php'**

Upon inspection, the error is bound to happen all the time, whenever the function **Tools::setCookieLanguage** is called, because it tries to include file from the folder which does not exist: **https://github.com/PrestaShop/PrestaShop/blob/0ee6f82c4145c84fb1347feef1c8af8839e9e984/classes/Tools.php#L621**

### Expected behavior

Expected behavior is that either the folder in question is created and included with Prestashop or buggy line should be removed.
Why would you suppress errors for piece of code with @, which can never be successful in the first place?

### Steps to reproduce

1. Switching language

### PrestaShop version(s) where the bug happened

1.7.6.7-1.7.8

### PHP version(s) where the bug happened

7.1-7.3

**Comment by khouloudbelguith** [comment]
Hi @modex9,

Thanks for your report.
Could you please provide me with the exact steps to reproduce the issue?
Is it an error in the console or an error displayed in the log file?
The `Friendly URL` is enabled or disabled in your case?

Thanks!

**Comment by modex9** [comment]
@khouloudbelguith thanks for response.

The warning happens on any front page, when this function is called (and it's always called):https://github.com/PrestaShop/PrestaShop/blob/e5f1187150fe0d12ada30f2a8801ad292fb6a1ef/classes/Dispatcher.php#L228-L230

Because ultimately it calls `Tools::setCookieLanguage`, which has file include with the warning suppressed with @:
https://github.com/PrestaShop/PrestaShop/blob/0ee6f82c4145c84fb1347feef1c8af8839e9e984/classes/Tools.php#L621
So you will never actually see it on the site, even with debug mode.

It's not like this is breaking a site or anything, but our Sentry (crash reporting system) for some reason registers this warning:

`Warning: include_once(/home/x/Public/presta1767.wip/www/themes/classic/lang/lt.php): failed to open stream: No such file or directory in /home/x/Public/presta1767.wip/www/classes/Tools.php on line 614`

I have never seen a case, where folder `themes/sometheme/lang/` exists in Prestashop 1.7 (it only exists in Prestashop 1.6).
Even if it can exist in same cases, I think it would be better to check if it does with `file_exists`, instead of suppressing the warning, as some crash reporting systems like Sentry still report it.

But if the file never exists in Prestashop 1.7 (which I think is the case, but this is based purely on my experience), then this line -
https://github.com/PrestaShop/PrestaShop/blob/0ee6f82c4145c84fb1347feef1c8af8839e9e984/classes/Tools.php#L621
should be removed altogether.

Also, this does not pertain just to Prestashop 1.7.6.7, same issue exists on the newest version.

**Comment by khouloudbelguith** [comment]
Hi @modex9,

I did not manage to reproduce the issue with PS1783.
I attached a screen record

https://user-images.githubusercontent.com/16067358/153590272-f5c1cf8a-b4a6-43d7-956a-5872c0f75f1f.mp4


Your shop, is it a fresh install or an upgrade from a previous version?
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @modex9 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
