### ISSUE TITLE
After upgrading to 1.7.8.x the maintanence page throws an error for user who is not on IP whitelist

### ISSUE THREAD

**Issue by ProteanCode** [PrestaShop/PrestaShop#27504]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After visiting the page as non-whitelisted user I see the following stacktrace:

![st2](https://user-images.githubusercontent.com/43477801/151453382-d3f67eb3-c771-4d0c-9cc4-400b01dbd5f8.png)
![st3](https://user-images.githubusercontent.com/43477801/151453385-04c664b6-a1a0-41b0-a0de-2c44878c8552.png)

This is strange as it generates the url for `classiclayouts/layout-full-width.tpl` instead of the layout for maintanence page

### Expected behavior

The maintenance page would show up

### Steps to reproduce

1. With a 1.7.7.0 version go export your classic theme to a zip directory
2. Perform upgrade to 1.7.8.2
3. Import classic theme from a zip

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.3

**Comment by khouloudbelguith** [comment]
Hi @ProteanCode,

Could you please provide more steps to reproduce the issue?
I followed these steps:
1. Install PS1770 with English language & France country
2. Go to BO > Design > Theme & Logo page > Export the current theme classic => a `classic.zip` will be created in the path `PrestaShop/themes/`
3. I tried to create a copy of this zip & rename it to `classic2.zip`
4. I upgraded to PS1783 using the 1-click upgrade v4.14.0
5. I tried to go to FO > The maintenance page is well displayed
6. Go to BO > Design > Theme & Logo page > Import the `classic.zip` => alert:` there is already a theme classic in your themes folder`
7. Import the copy of classic which is in my case `classic2.zip` => ok
8. Go to FO > Maintenance page well displayed


I attached a screen record


https://user-images.githubusercontent.com/16067358/151533239-5c9429d5-1002-4197-9a9f-21d9a6739ecc.mp4


Thanks to check and feedback

**Comment by ProteanCode** [comment]
@khouloudbelguith

Then its probably some faulty plugin.
I think it may be closed then as nonrelated to core prestashop code, but I will leave here info what happened in case of finding that out

**Comment by khouloudbelguith** [comment]
@ProteanCode, thanks for your feedback.
I will close the issue.
Feel free to create a new one when needed.

Thanks!

**Comment by ProteanCode** [comment]
I was using the $page variable in layout files, but that var is missing in maintenance page so the error occured
I placed isset check and everything works fine
