### ISSUE TITLE
Unknown column 'id_lang' in 'where clause'

### ISSUE THREAD

**Issue by PrestaSafe** [PrestaShop/PrestaShop#27506]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When i tried to delete an language. 
When a table finished by `_lang`

PrestaShop goes inside and try to remove the entry by the le key `id_lang`.

if this field doesn't exist, the error is triggered

<img width="1296" alt="Capture d’écran 2022-01-28 à 11 21 47" src="https://user-images.githubusercontent.com/4788787/151530160-da9ca8aa-cd81-400e-93d6-c27dc250ea7e.png">

### Expected behavior

Delete the language Any way

### Steps to reproduce

Go to your backoffice International > Translations. 
And a language. 

Create this table for testing: 
```sql
CREATE TABLE `ps_test_lang` (
  `id_test` int(10) unsigned NOT NULL,
  `lang` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id_test`,`lang`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

And try to delete the language added. 

### PrestaShop version(s) where the bug happened

1.7.8.3

**Comment by khouloudbelguith** [comment]
Hi @PrestaSafe,

I manage to reproduce the issue with PS1778 & PS1783, so I can confirm that this behavior is indeed a bug.
![image](https://user-images.githubusercontent.com/16067358/151537970-9d0e3d31-8b8c-445a-8cc0-dea965948a6a.png)

https://user-images.githubusercontent.com/16067358/151537734-44d8f70a-e35b-46fd-8459-336788255269.mp4

It could be related to this issue: https://github.com/PrestaShop/PrestaShop/issues/25631

Thank you for the PR :slightly_smiling_face:

**Comment by PrestaEdit** [comment]
Imho, creating a table like _lang without id_lang or _shop without id_shop is the bug itself.

**Comment by Hlavtox** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/33894
