### ISSUE TITLE
1.6 doc on the last PS version

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#27509]
I've try to add more replace  but there are 5 results that can't be changed, as it was 1.6 version and not available on the doc.

<img width="620" alt="Capture d’écran 2022-01-27 à 20 50 07" src="https://user-images.githubusercontent.com/2631425/151433066-59ce1fa6-4820-4a84-9519-b06eeb0de32e.png">
4

_Originally posted by @PrestaEdit in https://github.com/PrestaShop/PrestaShop/issues/27150#issuecomment-1023583677_

**Comment by Julievrz** [comment]
Here are the equivalents on GitBook, although I'm not quite sure everything should be in the User Doc. (Maybe the devdocs would be more adapted for some of them). 

https://docs.prestashop-project.org/1-6-documentation/english-documentation/system-administrator-guide
https://docs.prestashop-project.org/1-6-documentation/english-documentation/merchants-guide
https://docs.prestashop-project.org/1-6-documentation/english-documentation/troubleshooting
https://docs.prestashop-project.org/1-6-documentation/english-documentation/system-administrator-guide

**Comment by jolelievre** [comment]
Closed by #27691
