### ISSUE TITLE
Use the new url for orders list in the quick access links

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#27513]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Use the new url for orders list in the quick access links

### Describe the solution you'd like

Change the url by the good one

### Additional context

![Capture d’écran de 2022-01-28 12-32-56](https://user-images.githubusercontent.com/5064590/151539974-f78ca48a-3843-475e-8018-41c9df3461c0.png)

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

I manage to reproduce the issue with PS1778 & PS1783.
![image](https://user-images.githubusercontent.com/16067358/151545612-0460394b-e9e4-4db2-9bcc-0f2a8bdc9bd7.png)

I think, it is a bug & not a feature, I’ll add this to the debug roadmap so that it’s fixed.

Thanks for the PR :slightly_smiling_face:
