### ISSUE TITLE
compile error /modules/contactform/recaptcha.php

### ISSUE THREAD

**Issue by DahuProduction** [PrestaShop/PrestaShop#27524]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

I'm stuck since sometimes with a compile error when I restore my prestashop on an other server or when I uprade the version.

The problem only come on the module tab in the admin panel and I get this error when on debug mode
Compile Error: PrestaShop\PrestaShop\Adapter\Module\Module::instanciateLegacyModule(): Failed opening required '/home/clients/xxx.com/modules/contactform/recaptcha.php' (include_path='/home/clients/xxx.com/vendor/pear/pear_exception:/home/clients/xxx.com/vendor/pear/console_getopt:/home/clients/xxx.com/vendor/pear/pear-core-minimal/src:/home/clients/xxx.com/vendor/pear/archive_tar:.:/opt/php7.4/lib/php')

<img width="1025" alt="Capture d’écran 2022-01-29 à 09 27 19" src="https://user-images.githubusercontent.com/98638685/151653829-57c14db3-c0de-4737-afc0-9b33c20e94be.png">

I already try to clear the cache manually, but nothing better... It looks to be only a recaptcha module problem but I'm not as good as that to find the exact way to solve it !

### Steps to reproduce

1. update or move to another server
2. go to admin panel
3. go to module tab and get a blank page
4. after enabling debug mode, got the compile error HTTP 500

### PrestaShop version(s) where the bug happened

1.7.8.2 or 1.7.8.3

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

recaptcha

**Comment by PrestaEdit** [comment]
Hi @DahuProduction ,

Is you module modified ? I'm not able to find something about recaptcha inside the module.

Wich version of the contactform do you use ? Could you zip it here ?
Also, you mention the module is recaptcha but this module is not a PrestaShop core module.

**Comment by DahuProduction** [comment]
Hi PrestaEdit,

Thank you for your answer !

I didn't modified any module.

Here is a zip of the contactform module :
[contactform_29-01-2022_18 44 10.zip](https://github.com/PrestaShop/PrestaShop/files/7964244/contactform_29-01-2022_18.44.10.zip)

The recaptcha module is not a core module, it's maybe where come the problem !
It's this module https://addons.prestashop.com/fr/securite-access/18478-re-captcha-anti-spam-recaptcha-anti-faux-comptes.html

I will look in the way to remove this module and see what's next...

I will keep you in touch,

**Comment by PrestaEdit** [comment]
Hi,

Thanks. As I don't know how the reCaptcha module is made and not able to check it's code, as it's a third party module, I'm not able to say what it's the issue but t's see more an issue of this module than the PrestaShop Project, I'm afraid.

**Comment by DahuProduction** [comment]
So... after some research and test, it appear than the module make this compile error every time I want to upgrade or every time I transfer to another server !
After removing it, I can transfer to another server and upgrade without this Compile Error...
I will contact the developer to let him know my problem and hope he will solve the problem on his module.

Thank you for your answer and all the best !

**Comment by hibatallahAouadni** [comment]
Hello @DahuProduction 

Glad to hear that your issue is not PS Core issue 🎉 
Thanks @PrestaEdit for your helpful and quick replies 🚀 
Closing the issue as it's not Core bug.

Thanks!

**Comment by kordama1** [comment]
what I desperately need is an answer for 'what EXACTLY should I perform, to get the free Google reCAPTCHA module installed.. within the e-commerce ([motohaft.pl](http://motohaft.pl/)), that I gathered, from PRESTA pages: https://prestapros.com/en/blog/free-module-recaptcha-for-prestashop-registration-form. Thanks in advance for your prompt answer! The quuestion is just about to WHERE I should copy those 4 files into???for
