### ISSUE TITLE
Simpler and friendly URL of page with Registration form

### ISSUE THREAD

**Issue by Caleydon** [PrestaShop/PrestaShop#27526]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Is there any really good reason why the page with Registration form is calling by following Friendly URL?

`/authenticating?create_account=1`

Why is calling page with Login form with additional ?create_account=1 variable?

What about having nice and short URL instead?

`/sign-up`  or `/register` or `/new-account` or whatever merchant set in back office.

A few advantages:
* the merchant can choose to allow to indexing page with login form but not with registration form, and vice versa
* URL can have tracking or affiliate marketing parameters
* fully translatable friendly URL without english only parameter
* in some other languages we don't want use "authenticating" phrase anywhere in the eshop because in context it could meaning something quite different or is too formal in the particular country and culture. We want to use "register" or "new-account" in the URL. And now it is quite funny using friendy URL where URL to registration form include phrase "login".

### Describe the solution you'd like

Could you please implement this improvement if there is no reason to have ?create_account=1 in the URL?

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by Hlavtox** [comment]
It would be a BC break, but I think it's a good idea. :-)

**Comment by hibatallahAouadni** [comment]
Hello @Caleydon 


Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

PS: @Hlavtox thanks for your feedback 😉 waiting for your PR 🚀 

Thank you

**Comment by Hlavtox** [comment]
@Caleydon Done https://github.com/PrestaShop/PrestaShop/pull/27755

**Comment by Caleydon** [comment]
Awesome! Thank you.
