### ISSUE TITLE
Remove the prestashop.adapter.legacy_db service

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#27529]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

The prestashop.adapter.legacy_db service is flag as deprecated and to be removed in 8.0.

### Describe the solution you'd like

Removing it.

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by PrestaEdit** [comment]
I'd like to make it, but the prestashop.adapter.legacy_db is used twice and I need a tips on how to handle it.
Like making Db::getInstance() where it's used or use another service. :)

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

Thanks again for your suggestion!
The Developers Team will take it into consideration for future developments. 

Please be aware that there is no guarantee that this feature will be developed anytime soon.
So, we're waiting for your PR!

Thank you
