### ISSUE TITLE
Add console cmd to register|unregister a module to a specific hook

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#27528]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

With it, we will be able to quickly register|unregister the module to a specific hook|a list of hooks.

### Describe the solution you'd like

Adding an action to prestashop:module, maybe.

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by PrestaEdit** [comment]
I'm managing to implement the Pull Request but I'm not sure it's the best way to do it, to handle this inside the prestashop:module with the ModuleManager itself.

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

It seems a great idea 👏 and thanks for your PR 🚀 
Let's check with the Developer Team 😉 

Ping @PrestaShop/prestashop-core-developers wdyt of this feature, IMHO I think it's super useful for developers.
Waiting for your feedback.

Thanks!

**Comment by matks** [comment]
@PrestaEdit Could you provide some situations where this command would be very useful? You can do this from the web interface, what does the Command bring ?

**Comment by PrestaEdit** [comment]
You can do all with the inferface, like install PrestaShop, reset a module and so on.
It's just an extra command to handle, and it's usefull when you develop a module and want to add a specific hook for example, without making the reset and/or go to the interface.

**Comment by jf-viguier** [comment]
@matks I see some user cases :
- a script to install a widget module in several hooks for testing it
- hook a widget module to a hook in a deployment script without theme.yml nightmare.

Thanks @PrestaEdit for the improvement.

**Comment by matks** [comment]
I see it has value for module developers. The question is whether this should go into the Core or remain a script shared by contributors and users.

wdyt @PrestaShop/prestashop-maintainers ?

**Comment by atomiix** [comment]
I see no reason to not add those commands in the core, we can already install/uninstall modules, why not register/unregister hooks? :)
