### ISSUE TITLE
Contactform: missing /widget/contactform.tpl

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#27521]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you use the contactform module in standalone (without the Classic override) in a hook, it's use the Widget interface and call the /widget/contactform.tpl.

This tempate is missing in the module.

### Expected behavior

Widget render an existing template.

### Steps to reproduce

1. Remove override template of contactform module
2. Go to Contact us page
3. See that there is a missing template

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.0.14

### If your bug is related to a module, specify its name and its version

contactform

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

Thanks for reporting the issue and for your PR 🚀 
Did you encounter the same issue with PS1.7.8.3 or only on develop branch?
Waiting for your feedback.

Thanks!

**Comment by PrestaEdit** [comment]
Hi @hibatallahAouadni,

It's with the module itself. If you remove the template form the theme, it's missing from the module at the base.

**Comment by florine2623** [comment]
Hello @PrestaEdit ,

With contactform v4.1.1, the path is the following :
`your_shop/modules/contactform/views/templates/widget/contactform.tpl`

With contactform v4.3.0, it is like this :
`your_shop/modukes/contactform/views/templates/hook/contactform.tpl`

The folder has been changed.

I will ping dev team to see if that the wanted behavior.
Please stay tuned !

Thanks!

**Comment by florine2623** [comment]
ping @PrestaShop/prestashop-core-developers ,

As per my previous comment, could you confirm if that's the wanted behavior ?
Thanks!

**Comment by atomiix** [comment]
@florine2623 it seems that it's a wanted behavior: https://github.com/PrestaShop/contactform/pull/25/files#diff-a1a6b3954c542d2d1895d5bdcf83deb9175daac9e6e86434afc1d2660df72f0b

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

Thanks for your feedback.
@PrestaEdit, At it is the wanted behavior.
The file `modules/contactform/views/templates/widget/contactform.tpl`is moved to `modules/contactform/views/templates/hook/contactform.tpl`

I will close the issue.
Thanks!

**Comment by PrestaEdit** [comment]
There is still a bug, with that, but I will make an others PR to take care of this behavior.

**Comment by PrestaEdit** [comment]
@atomiix and @khouloudbelguith : the issue is that the file is never called, was moved but not the path where it's call.
If we merge my pull request, we have the validator not good ; if we change the path here, every theme based on this faulty path (widget instead of hook) will need a change... What we do, now ?
