### ISSUE TITLE
Property extended with appendArray not working in CartPresenter

### ISSUE THREAD

**Issue by gusxavi** [PrestaShop/PrestaShop#27532]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello community. I have been trying to understand a behavior that doesn't have sense for me.
I have a **CartPresenter** with products in **CartController** . I am using the **appendArray** to extend every **ProductListingLazyArray** with a new property to use it in a smarty file.
Inside initContent() method I can see my property printed properly.  Once the variable is assigned to smarty, my values are lost.
BUT If I assign my values as a different smarty property, it works fine.
Here is how my functions looks now:

![Screenshot from 2022-01-29 22-38-42](https://user-images.githubusercontent.com/3169080/151683396-300d6726-74b0-407d-9ad9-585089d3b602.png)

### Expected behavior

Assign the value as normal to smarty and in the tpl files access the values without creating new smarty variables. 

```
foreach ($presented_cart['products'] as $product) {
      $product->appendArray(['myDummyprop' => 'anyValueHere']);     
}
     
$this->context->smarty->assign([
    'cart' => $presented_cart, 
    'static_token' => Tools::getToken(false),
]);
```

Then in smarty access $cart.products[0].myDummyprop 

### Steps to reproduce

1- Search for a Cart Presenter.
2- Loop through products and assign a new property using appendArray
3- Assign cartPresenter to a smarty variable.
4- Create another smarty variable and assign a single modified product ( same modified using appendArray)
5- try to access new property into the $cart.products[0].property
6 - Try to access the property directly into the product variable $product.property 

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.4.27

**Comment by hibatallahAouadni** [comment]
Hello @gusxavi 

Thanks for reporting the issue!
Ping @PrestaShop/prestashop-core-developers could someone reproduce the issue :pray: (cause it's too technical for me).

Thanks in advance :relaxed:

**Comment by atomiix** [comment]
@gusxavi I think the smarty variable gets overrode [here](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/classes/controller/FrontController.php#L524) when `parent::initContent()` is called.
I don't know what you're trying to do but you should probably use the hook `actionPresentCart` [that is called by the presenter](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/src/Adapter/Presenter/Cart/CartPresenter.php#L491-L493).

**Comment by hibatallahAouadni** [comment]
Hello @gusxavi 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
