### ISSUE TITLE
Productcomments error 500 due to TypeError on addCommentGrades in case of empty request

### ISSUE THREAD

**Issue by clotairer** [PrestaShop/PrestaShop#27534]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you call https://www.your-shop.com/module/productcomments/PostComment?id_product=125 an error 500 occured.
<pre>Uncaught exception 'TypeError' with message 'Argument 2 passed to <br>ProductCommentsPostCommentModuleFrontController::addCommentGrades() must be of the type array, bool given, called <br>in modules/productcomments/controllers/front/PostComment.php on line 100' <br>in modules/productcomments/controllers/front/PostComment.php:135 <br>in ProductCommentsPostCommentModuleFrontController::addCommentGrades called at modules/productcomments/controllers/front/PostComment.php (100) <br>in ProductCommentsPostCommentModuleFrontController::display called at classes/controller/Controller.php (331) in ControllerCore::run called at /var/www/prod/classes/Dispatcher.php (518) <br>in DispatcherCore::dispatch called at index.php (28)</pre>

The main problem is that bot crawl all these URL of the website and return 500 error on logs files.

### Expected behavior

This call should return an error message.

### Steps to reproduce

1. Install the module
2. Sign in with a customer account
2. Call https://www.your-shop.com/module/productcomments/PostComment?id_product=125 (125 is an id_product available on the shop)
3. See the error 500 and an empty page. It should return an JSON error message.

### PrestaShop version(s) where the bug happened

all

### PHP version(s) where the bug happened

all

### If your bug is related to a module, specify its name and its version

productcomments

**Comment by hibatallahAouadni** [comment]
Hello @clotairer 

Could you please provide the module version :pray: 
Waiting for your feedback.

Thanks!

**Comment by clotairer** [comment]
5.0 but I've not check if the bug was in a previous version. Probably according the code...

**Comment by khouloudbelguith** [comment]
Hi @clotairer,

I manage to reproduce the issue with PS1783 using the `productComment` v5.0.0 & v4.2.2
![image](https://user-images.githubusercontent.com/16067358/153172141-3e8599c7-b210-41de-9695-aa1e6f861021.png)
![image](https://user-images.githubusercontent.com/16067358/153177329-2f521977-a126-4346-bf7c-eb4eeeeff509.png)

I tried with PS1778 + `productComment` v5.0.0 & v4.2.2 => ok
I have this result
![image](https://user-images.githubusercontent.com/16067358/153172289-63c83714-5609-4a90-8839-7ef7d857752c.png)

Thanks!

**Comment by khouloudbelguith** [comment]
Hi,

Sorry, it was not a regression, it was missing a step.
you should be connected as a customer to reproduce the exception :smile: 
It is not a regression, I reproduced the issue with PS1778 + comment module v5.0.0
![image](https://user-images.githubusercontent.com/16067358/153178133-995500cd-00ce-4d20-9918-81b4d2955e39.png)

Thanks!

**Comment by clotairer** [comment]
FYI the bug can be reproduce if the module accept anonymous comment and without user authenticated.
