### ISSUE TITLE
Maintenance mode is not safe to install / upgrade modules from command line

### ISSUE THREAD

**Issue by Seb33300** [PrestaShop/PrestaShop#27539]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When trying to install / upgrade a module using command line while the website is on maintenance mode, the command line can crash if someone is accessing the website at the same time:

```
php bin/console prestashop:module install module_name -q --no-debug;
php bin/console prestashop:module upgrade module_name  -q --no-debug;
```

can result in

```
PHP Fatal error:  Uncaught Symfony\Component\Filesystem\Exception\IOException: Failed to remove directory "/home/www-data/var/cache/prod/": rmdir(/home/www-data/var/cache/prod/): Directory not empty. in /home/www-data/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:180
Stack trace:
#0 /home/www-data/classes/Tools.php(3458): Symfony\Component\Filesystem\Filesystem->remove(Array)
#1 [internal function]: ToolsCore::{closure}()
#2 {main}
  thrown in /home/www-data/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php on line 180
```

It looks like a cache clear happens while running commands and the cache is instantly re create if someone try to access the website resulting in a crash of the command line.

### Expected behavior

Maintenance mode should be safe to use

### Steps to reproduce

1. Enable the maintenance mode
2. Run the module upgrade command on any module installed on your site
3. At the same time the command is running, try access the shop homepage (and refresh it many times)
4. The command line may crash randomly

### PrestaShop version(s) where the bug happened

1.7.7.7

**Comment by hibatallahAouadni** [comment]
Hello @Seb33300 

Do you mean that when your shop is on maintenance mode:

![image](https://user-images.githubusercontent.com/23308427/151886667-59c98c9b-4940-43e8-a97b-a3fd16a6e53d.png)

While upgrading/installing any module by command and you try to refresh the homepage many times:

![image](https://user-images.githubusercontent.com/23308427/151886679-77c2be48-b93d-4a7f-a68e-fc7683fb9da5.png)

Then, the command crashs?! randomly? cause I tried and I didn't encounter the issue :confused: 
IMO, I think it will be better if we change this issue to a feature request as it's related to improve the PS Performance.

Well, the Developer Team will take it into consideration for future developments. 
Waiting for your PR :rocket: 

Thank you

**Comment by Seb33300** [comment]
I am no more able to reproduce this issue after 1.7.8 upgrade

**Comment by hibatallahAouadni** [comment]
@Seb33300 Glad to hear :tada:
