### ISSUE TITLE
Remove dependency of Fonts CDNs in the PrestaShop open source project

### ISSUE THREAD

**Issue by ttoine** [PrestaShop/PrestaShop#27541]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Yes, this is related to a problem, as described below.

It appears that Google Fonts service has been judged as not compatible with GDPR and then should not be used in the PrestaShop open source service. TLDR: Google Fonts is a CDN, and it captures the IP of the website visitors (merchants, customers) before any consent or approval.

Legal documents:
- Original in German at [https://rewis.io/urteile/urteil/lhm-20-01-2022-3-o-1749320/](https://rewis.io/urteile/urteil/lhm-20-01-2022-3-o-1749320/)
- [Translation in English](https://rewis-io.translate.goog/urteile/urteil/lhm-20-01-2022-3-o-1749320/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en-US&_x_tr_pto=op,wapp) (sorry for using Google Translation, too long for Deepl...)

### Describe the solution you'd like

Google Fonts must be removed from the entire PrestaShop project (BO, and FO theme), and instead, a set of default fonts must be provided inside the installer so fonts are downloaded directly on the website's server.

I can provide assistance to select fonts that have a compatible license with OSL so it is possible to distribute them with the installer. (work to be done with PM and designers)

### Alternatives you've considered

Find a way to get the consent of end users before the website is actually displayed, but how?
(so, during installation, the first step would be to ask the user if they agree with Google Fonts, not wonderful for adoption. And for shop customers, this should be managed in the GDPR banner)

And, what happened if the end user disapprove?
Serving the default font in the operating system or browser? Can this generate display problems if the defauts fonts are not similar?

No easy solution. The best way to be sure to be legal compliant is to remove Google Font and include a set of open source fonts.

### Additional context

Some third party themes might also rely on Google Fonts, but this is not our problem: vendors will have to inform their customers/vendors, and provide a validation system regarding GDPR.

Also, we must show and promote best practices in term of legal compliance with the PrestaShop open source project.

**See the discussion, there are other CDNs used in the project instead of embedding fonts in the project. They must be removed too.**

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by Hlavtox** [comment]
IP address is a personal data only if its paired with other data that enables you to identify this person.
Based on that court decision (100 EUR btw), we should stop using all CDNs or Cloudflare?

**Comment by ttoine** [comment]
It's not a problem with all CDNs or Cloudflare, because they are not distributed with the project: you configure a CDN after the installation for a website, it's a choice you make, and you can use a CDN that complies with GDPR.

Even if a CloudFlare module would be shipped with the software, the merchant would have to create an account, enable it, configure the DNS, ... 

The problem here is:
- Google Fonts is a dependency of the PrestaShop software
- There is no way to avoid it without modifying the core (at least the CSS to use only default operating system or browser font)
- There is no need to create an account on Google to enable it, you just use Google Fonts in your style
- Website visitors (and maybe website owners) use it even without knowing it
- Google gather enough data to identify people and associate it to their UUID system

Last point: what happens if Google do like they did for other products like Maps, and decide that as a website owner, you must pay a monthly fee depending on how much visitor you have on your website?

**Comment by hibatallahAouadni** [comment]
Hello @ttoine 

Thank you for your suggestion. 
I’ll add this to the debug backlog so that it’s fixed.

Thank you

**Comment by matks** [comment]
I agree with @Hlavtox : following this decision we should stop using _any_ CDN in PrestaShop that are being used in the distribution.

So if you look at file https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/default/public/theme.rtlfix  the use of cdn.jsdelivr.net should be forbidden

Also I have one question: the ruling was done by a court in Germany

https://thehackernews.com/2022/01/german-court-rules-websites-embedding.html

What if another court says the contrary?

If one German court says "yes it's against GDPR" and a Spanish court says "it's OK with GDPR" who wins? Should we jump on the topic and immediately change something as big because one court said they are not happy, especially since our license basically protects us against any issue (it's the user responsibility to comply with his country laws)?

**Comment by ttoine** [comment]
@matks thanks for pointing this issue with an other CDN in the Core. If this is possible to list them all, that would help to study them and their possible impact for end users. Then I could change this issue title into something like "Remove embedded CDNs from the project".

cdn.jsdelivr.net has a basic [privacy policy](https://www.jsdelivr.com/terms/privacy-policy-jsdelivr-net) however they actually rely on other CDNs, that have more complex privacy policies. This is cascading and must be studied in details. I can see that this is used to include text fonts is a style/template, and this is not a good practice. Such files should be included in the installer and available on shops servers, by default, like any other artwork (icons, pictures, ...).

In general:
- the installer should not depend on, or embed, third party content via a CDN
- website owners (merchants, techs) should be aware of any third party service and accept their terms of use (maintainers can't accept for someone else)
- website visitors (shop customers) must be able to disable third party services that might spy them within the cookies/gdpr banner (I guess that this is not the case for font CDNs but please prove me wrong)

Then, as there is a real concern about performance, it is possible to add in the settings a way to enable the use of CDNs for this kind of files, with a disclaimer and links to their terms of use, etc.

Also, I ask the question: what happens if the CDN are not available when someone installs or use PrestaShop? (there has been big issues in the past with failure of our own APIs or delivery servers...)

In the case of Google Fonts, there is a known problem with 1/ the terms of use and 2/ the fact they have enough data to match an network IP with an actual person. You can also take in account many recent or current cases against Google (Analytics in Austria, GDPR exception request from Google in France and other countries, and in general, EU concerns about GDPR and Cloud Act compatibility)

The target is to improve the legal compliance for end users. And reduce the overall Intellectual Property risk of using the project in our main markets. It's about making PrestaShop a better open source project. I don't open this kind of issue to vent or to annoy developers.

**Comment by Hlavtox** [comment]
It's no problem to implement this, material icons are bundled, why not other fonts. But I don't want this issue to become something as a precedent for other cases in prestashop. 👍

I think it should be the responsibility of the merchant to be compliant with his local laws. I have to implement the most crucial thing for selling in europe = **EU VAT** for myself, but yet we will invest time for "insignificant" things like this?

**Comment by ttoine** [comment]
You nailed it, it's the reason why we include material icons and other artworks assets. Fonts are no different.

Developers and small business owners often don't see the importance of legal compliance and terms of use... I am used to it, but unfortunately this should not be optional. Improving the legal compliance of the projet is actually a key for its adoption and for growing its business ecosystem. It's the opposite of being "insignificant". At all. BTW it is a prerequisite in all serious open source projects.

Also, note that PrestaShop is used by more and more big companies that actually have a legal compliance department, so, they care. Same with big partners of the ecosystem. Same in some countries where software patents are a thing, like North America, there, providing a legal compliant software is critical. Because the legal evaluation is the first step, even before the technical evaluation.

Remember that the risk of using open source software is on the end user side so in theory we can even ship bad software and it would be up to the end user to fix it. But, who would actually use it, then? That's why to foster adoption, we must work on providing the lower risk possible, and that include legal compliance. Like security, it's a prerequisite.

**Comment by matks** [comment]
> Also, note that PrestaShop is used by more and more big companies that actually have a legal compliance department, so, they care. Same with big partners of the ecosystem. Same in some countries where software patents are a thing, like North America, there, providing a legal compliant software is critical. Because the legal evaluation is the first step, even before the technical evaluation.

I think @Hlavtox does not care: PrestaShop being used by big companies is your topic, not his topic @ttoine .

- @Hlavtox goal is to use PrestaShop for his needs, not the needs of other big companies
- @ttoine you invest in this topic because PrestaShop being adopted by big companies is what you aim for

It's an open source project: people contribute to the topics that are important to them so that the project match better their needs, not the needs of others.

**Comment by Hlavtox** [comment]
Thats not true @matks, all merchants, big or small need to follow the same rules. :-) All my clients have perfectly legal-valid websites that passed several state inspections without a single issue. 👍

> Remember that the risk of using open source software is on the end user side so in theory we can even ship bad software and it would be up to the end user to fix it.

Then we need to provide all the possible hooks needed, fast. Only thing that people talk about in czech prestashop facebook right now is how to implement a new cookie law from 2022. Two biggest czech module developers have the same issue - cookie modules and struggle with proper implementation and overrides. Yet we don't even have a consent system issue open. While wordpress has it implemented already for some time. :-(

So, is the main target audience EU merchants? If yes, lets dive into it, but I personally would start from completely different end - important things you can eventually get fined for. 💰
_______

BTW: Of course we need to ship legal compliant software, but its currently “not compliant” only to one single court in germany. I think a good lawyer would destroy that. Is Prestashop a dog that puts his tail between his legs? I think google fonts still provides some value, because it loads the fonts in more efficient way than when locally hosted, but maybe I am wrong. @NeOMakinG knows this.

**Comment by NeOMakinG** [comment]
> It's no problem to implement this, material icons are bundled, why not other fonts. But I don't want this issue to become something as a precedent for other cases in prestashop. 👍
> 
> I think it should be the responsibility of the merchant to be compliant with his local laws. I have to implement the most crucial thing for selling in europe = **EU VAT** for myself, but yet we will invest time for "insignificant" things like this?

Material icon is not forced to be bundled, we've a feature to use a CDN in the UIKit :trollface:

**Comment by NeOMakinG** [comment]
> BTW: Of course we need to ship legal compliant software, but its currently “not compliant” only to one single court in germany. I think a good lawyer would destroy that. Is Prestashop a dog that puts his tail between his legs? I think google fonts still provides some value, because it loads the fonts in more efficient way than when locally hosted, but maybe I am wrong. @NeOMakinG knows this.

AFAIK, CDN is mainly about loading time, for example, if your website is available worldwide, your end user will load the font from a closer server. 

But it exposes some potentiel issues: 
- If the CDN is down, but not your server, the font won't be loaded
- As @ttoine said, privacy

I wouldn't mind using local fonts everywhere, or make it configurable !

**Comment by Hlavtox** [comment]
Ok, let's do it! 👍

**Comment by ttoine** [comment]
I would say that first step is to make them local.
then add possibilities to use CDN, like for any kind of static files.

if you have to chose a few font to be embedded in the software, please don't forget to ask me to check the license of the fonts.

**Comment by NeOMakinG** [comment]
I did verify every fonts

`Theme`
Manrope => OFL

`Core and UIKit`
Open sans => Apache 2.0
Material icon => Apache 2.0
Font Awesome => OFL
Vazir (font RTL) (CDN) => OFL

I did provide a PR where we use Vazir font without a CDN: #27611

@ttoine Everything is in your hands, waiting for your feedback

**Comment by NeOMakinG** [comment]
I also added a `thirdPartyNotice.json` generator to webpack inside every folders, so we provide a list of every license on build

**Comment by ttoine** [comment]
Hello, I checked that using fonts distributed under OFL is ok with PrestaShop's OSL that we use to distribute the project.
We already know that Apache 2.0 is ok.

About licenses: Composer is usually doing that already in vendor folders for PHP packages. So, it's great that to add this feature to npm/webkit/js dependencies too.

I will add OFL in the devdocs.

**Comment by matks** [comment]
@NeOMakinG it seems https://github.com/PrestaShop/PrestaShop/pull/27611 does not fully fix this issue, is'nt it?

**Comment by NeOMakinG** [comment]
@matks I think it fixes it! Classic didn't have any CDNs

**Comment by matks** [comment]
🎉

**Comment by ricardopxlcl** [comment]
@hibatallahAouadni I can't find similarities in the code, from my Issue.

**Comment by matks** [comment]
Interesting related news: "The default Laravel installation welcome page has ditched Google Fonts and moved to Bunny Fonts. This is great because it raises awareness that you don't have to send your website visitors browsing habits to an advertising company." 😄 

https://twitter.com/JackEllis/status/1553818267294130176
