### ISSUE TITLE
It's impossible to uninstall the welcome module with cli command

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#27547]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If you try to uninstall the welcome module with this command: `php bin/console prestashop:module uninstall welcome`
You will have an error (`Call to a member function setCurrentStep() on null`).

It's due to the fact that onBoarding property is not populated when you are not in the admin directory (See https://github.com/PrestaShop/welcome/blob/dev/welcome.php#L76)

### Expected behavior

Let me uninstall this module with CLI command :D

### Steps to reproduce

1. Use the command.
2. See the red error.

### PrestaShop version(s) where the bug happened

1.7.8.3

### If your bug is related to a module, specify its name and its version

welcome

**Comment by marwachelly** [comment]
Hello @PrestaEdit ,

We are aware of this issue, it is a duplicate of #12552.
According to @PrestaShop/product-team the welcome module will be archived with the V8.0.0.

Thanks!

**Comment by PrestaEdit** [comment]
Hi @marwachelly,

A duplicate of a closed issue, that will be not fixed. Ouch.
