### ISSUE TITLE
Product url is added to browser's history on add to cart

### ISSUE THREAD

**Issue by ghtoo** [PrestaShop/PrestaShop#27542]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When in product's page and adding product to a cart, each time Prestashop is adding product's url to the browser's history, so, let's say if I add a product to a cart on a same product's page, I would have to press Back button twice in a browser in order to go back to a previous page, thrice, if I would add same product 2 times and so on...

The issue is present on a clean Prestashop installation without any modifications. Is this behavior intended? Older versions of PS (1.6x) did not had this issue. 

Here's what I mean:

![Peek 2022-01-31 13-43](https://user-images.githubusercontent.com/98745844/151790088-d3fb513b-fbac-49b1-bd31-7fbe8854642a.gif)

### Expected behavior

Prestashop shouldn't add new history record to browser when adding product to a cart.

### Steps to reproduce

1. Go to Product page
2. Add product to a cart
3. Try to go back with browser's back button to a previous page

### PrestaShop version(s) where the bug happened

1.7.8.2, 1.7.8.3

### PHP version(s) where the bug happened

7.4.27

**Comment by hibatallahAouadni** [comment]
Hello @ghtoo

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #26575. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #26575
