### ISSUE TITLE
Bug with the ps_facebook module on the account association

### ISSUE THREAD

**Issue by simobenso** [PrestaShop/PrestaShop#27569]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,  

There's a problem while trying to associate a prestashop store with a currency other than EUR on the PS Facebook module. On the previous versions of the module it was possible to associate it without any problems. Now the module generates the following error : 
The currency MAD currently associated with your website isn't supported on Facebook. Contact PrestaShop Social Media for support.

![image](https://user-images.githubusercontent.com/1257993/152176301-eff992ca-0de0-4acf-b63a-8d1e316e0b64.png)

When contacting the facebook support, they said it was a problem on the prestashop integration side.

By investigating a little I could detect that on the file: **modules/ps_facebook/vendor/facebook/php-business-sdk/src/FacebookAds/Object/Values/AdAccountCurrencyValues.php** the **MAD** currency (and several others) is not not listed among the file values. This could be the source of the problem.

Also, several other users seem to have the same problem according to this post on stackoverflow: https://stackoverflow.com/questions/70361572/how-to-make-currency-work-in-facebook- pixel-if-the-currency-not-supporting-by-f

### Steps to reproduce

1. Go to Ps_Facebook module configuration
2.  Click on the Connect to Facebook button

### PrestaShop version(s) where the bug happened

1.7.8.0

### If your bug is related to a module, specify its name and its version

ps_facebook v1.14.0

**Comment by simobenso** [comment]
@Quetzacoalt91 can you please take a look at this ?

**Comment by hibatallahAouadni** [comment]
Hello @simobenso 

It seems that your issue is not a PrestaShop core bug.
If your module is Facebook Official, please contact support team on Addons.

We will close this issue.

Thanks!

**Comment by simobenso** [comment]
I tried to report the bug on the ps_facebook repository but it's not possible. at least you can help get this reported to the dev team before closing it ?

**Comment by hibatallahAouadni** [comment]
> at least you can help get this reported to the dev team

Done :wink: they will work on it ASAP.
Thanks for your understanding :pray:
