### ISSUE TITLE
Error en el Pago por default

### ISSUE THREAD

**Issue by yfbetancourth** [PrestaShop/PrestaShop#27573]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Cada ves que se crea nuevo pedido, sea por en front o back end, los pedidos son creados con error en el pago por defecto. Estos sucede por los cualquiera de metodos de pago contra reembolso, efectivo, modulos nativos de prestashop., 

### Steps to reproduce

1. crear nueva orden
2. escribir direccion y datos de entrega
3. elejir metodo de pago
4. elejir pago contra reembolso
5. aceptar terminos y crear orden
6. buscar orden en back end
7. actualizar pago
8. cambiar error en pago (debe aparecer en espera)
9. seleccionar pago aceptado
10. actualizar estado. 

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4.27

**Comment by hibatallahAouadni** [comment]
Hello @yfbetancourth 

Please send your request in English. English is the norm on GitHub.

Thank you
