### ISSUE TITLE
Add hooks before and after FrontController country detection

### ISSUE THREAD

**Issue by madsoliver** [PrestaShop/PrestaShop#27577]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

There is alot of magic going on inside `FrontController::init()` and there are hooks before and after, but I have found a need to hook into the geolocation- and country-detection-part, in order to do some tweeks **before** the rest of the `init()`-method is executed.

Right now I need to override `FrontController::geolocationManagement()` in order to do what I want (change currency based on country), but I would much more like to see some hooks like proposed as follows.

### Describe the solution you'd like

        // FrontController.php line 350
        Hook::exec('actionFrontControllerCountryDetectionBefore');

        if (Configuration::get('PS_GEOLOCATION_ENABLED')) {
            // ...
        } elseif (Configuration::get('PS_DETECT_COUNTRY')) {
            // ...
        }

        Hook::exec('actionFrontControllerCountryDetectionAfter');

### Alternatives you've considered

Override. It works, but for how long?

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @onklmaps 

Thank you for your suggestion. The Developer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. 

So, we're waiting for your PR :rocket: 

Thank you

**Comment by kpodemski** [comment]
> Override. It works, but for how long?

I will give you my point of view. It's not the official statement of the team, etc. Overrides are ok for the cases where you need to do something specific. Having thousands of hooks is probably not the most performant way to handle software customizations. In your example, a use-case is very common. You want to change the language based on the language/location, so hooks make sense.

My only question is, are you sure you can't do it using `actionFrontControllerInitAfter`? You can change the value of the cookie and use `Tools::setCurrency`, correct?

**Comment by matks** [comment]
I agree with @kpodemski : hooks are not always the best solution.

Hooks are great if we expect
- multiple modules might want to plug themselves at a single point (payment flow for example)
- multiple usecases might benefit from a hook at a single place

If we added this hook I'm afraid it would only answer to a single need, the one presented.

So maybe a hook is not the best choice. But there is other extension mechanisms available: override is one, decoration is another ...

**Comment by matks** [comment]
Hi @onklmaps what do you think about our answer, although it might not be what you wanted to hear 😅 ? does it make sense ?

If it does maybe we can close this PR - although it's nice you suggested that

**Comment by madsoliver** [comment]
Hi. @matks and @kpodemski, I'm sorry I haven't replied sooner. I just haven't had time to test if I can use the hooks before or after, and also not decoration. However, overriding is an option that always bites me in the long run. Hijacking the core methods like that makes that prestashop so locked up so I dear not to upgrade it when updates are available. 

Anyway, the init() is a big method, and there is alot going on. My concern is exactly the opposite, that performance-vise it does not make sense to set context and cookies in the init() only to unset them again and redo the job in another way in the initafter-hook. But thats probably one of the disadvantages of building on top of an existing codebase.

**Comment by madsoliver** [comment]
Yeah, you can close it 😉

**Comment by hibatallahAouadni** [comment]
> Yeah, you can close it 😉

So, closing the issue :slightly_smiling_face:
