### ISSUE TITLE
Merge email twig file into the core

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#27570]
From the discussion https://github.com/PrestaShop/PrestaShop/issues/26177#issuecomment-1024055053
To allow developers and merchants to have the latest fixes from the modern theme, we need the twig files generated from https://github.com/PrestaShop/mjml-theme-converter into the core

**Comment by Progi1984** [comment]
Fixed by me in #27614 and tested by @HanaRebaiQA
