### ISSUE TITLE
Allow a module to add CTA in the toolbar for ALL the modules

### ISSUE THREAD

**Issue by sowbiba** [PrestaShop/PrestaShop#27578]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

The goal is to allow a module to add a button in the toolbar to allow performing an action on **any** module; like "Check for update", "optimize images", ...
This action can be called on any module configuration page

### Describe the solution you'd like

The solution I have in mind is a hook which adds a button, giving all the attributes : icon, href, help, title
When displaying toolbar of a module configuration page, we collect all the extra buttons added by modules and display them

The "adder" of the button must do all necessary checks to display the button in the right context : user permissions, module type, shop type, ...

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @sowbiba 

Thank you for your suggestion and for your PR :rocket:  
The Developer Team will take it into consideration for future developments. 

Thank you

**Comment by khouloudbelguith** [comment]
Hello,

As commented here: https://github.com/PrestaShop/PrestaShop/pull/27461#pullrequestreview-862809575
This issue is ready.

Thanks!
