### ISSUE TITLE
Prestashop customization value truncated at 255 characters

### ISSUE THREAD

**Issue by musaffar-patel** [PrestaShop/PrestaShop#27579]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When working with customized products, the customization value is stored in ps_customized_data::value.
However, if the length of the customization value is greater than 255 characters it is truncated which is a problem.

The problem seems to be in the table structure for ps_customized_data.  The value column seems to be limited in length to 255 chars.

### Expected behavior

Allow for more characters to be stored in this column (~1024 characters?)

### Steps to reproduce

Create Customized product with a text field
Enter any text which exceeds 255 character count

Now in cart / checkout and back office order details the text will be truncated at 255 characters

### PrestaShop version(s) where the bug happened

1.7.0 to 1.7.8.3

### PHP version(s) where the bug happened

All

**Comment by hibatallahAouadni** [comment]
Hello @musaffar-patel 

That's the expected behavior cause if the message exceed 255 characters we will encounter some issue like this one #26374
Ping @PrestaShop/product-team correct me if I'm wrong :pray: 

Thanks!

**Comment by musaffar-patel** [comment]
Hi

Then should the formatting of longer values (perhaps with css) not be fixed instead of limiting the value altogether?
