### ISSUE TITLE
Issue to display products with combination on mobile phone on the front-office using IOS 13 with Safari

### ISSUE THREAD

**Issue by LollipopAdmin** [PrestaShop/PrestaShop#27589]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When browsing the site (front-office) with a mobile device (any iPhone running IOS 13 with Safari), all products with combination fails to display while all simple products works. 

Working url with a simple product- https://lollipopcreations.be/fr/les-dorees-noires/100-adelaide.html
Non-working Url with a product with combination - https://lollipopcreations.be/fr/les-bronzes/173-411-louisa.html#/29-couleur-moutarde

Error displayed is the following: "Un problème récurrent est survenu sur: "https://lollipopcreations.be/fr/les-bronzes/173-411-louisa.html#/29-couleur-moutarde" on a white screen. 

![PHOTO-2022-02-04-13-53-24](https://user-images.githubusercontent.com/75253748/152533277-7331af72-3def-445b-a3cd-9ca0d62b206d.jpg)

### Expected behavior

The product with combination page should load properly as it is the case in Google Chrome or Firefox. 
This behaviour appeared when IOS 13 was released. Before that it used to work. 

### Steps to reproduce

Using a mobile phone with Safari (iphone preferrably - I did not test it with other phone brand), access our site front-office  
https://lollipopcreations.be/fr/

Test those 2 links 

1) Working URL for simple product - https://lollipopcreations.be/fr/les-dorees-noires/100-adelaide.html
2) Non-working-url for any product with combination  - https://lollipopcreations.be/fr/les-bronzes/173-411-louisa.html#/29-couleur-moutarde

Seee the issue with the second link... 

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.4.27 

### If your bug is related to a module, specify its name and its version

Core - Product with combination

**Comment by HanaRebaiQA** [comment]
Hello @LollipopAdmin 

Thanks for your report!
I was unable to reproduce your issue with `PS1778` and `PS1780` using` iPhone 13 `On `Safari` browser.
I checked with a Simple and with combinations products.
![image](https://user-images.githubusercontent.com/92912932/152557037-efa924de-9dbc-4bf0-b4ef-de94adc1878a.png)

https://user-images.githubusercontent.com/92912932/152558095-3b861b22-752f-476d-98fd-26fe744a6a7e.mp4


Could you please provide us more informations ?
Waiting for your feedback!

Thank you!

**Comment by LollipopAdmin** [comment]
Hey Hana, 

Thanks for your message. Can you try on our site with an iPhone, with the 2 urls I gave and send me a screenshot if you can. 
I would like to see what you see in that specific case. 
On my end, I will try to test the functionality on a test vanilla site to see if I can reproduce. 

Tks,

**Comment by florine2623** [comment]
Hello @LollipopAdmin ,

I can't reproduce your issue as you can see here :

https://user-images.githubusercontent.com/16019289/153191337-bcb33137-ab72-4019-aa52-a19d03f51e63.mov

As your issue cannot be reproduce, I will close your issue.

You can update your Safari app, delete your browser cache. You can check your Ip address, maybe it is blacklisted from your Internet provider.

Thanks!
