### ISSUE TITLE
Correct SMTP details not working. Test mails not sending using SMTP for 1.7.8.3

### ISSUE THREAD

**Issue by pks891618** [PrestaShop/PrestaShop#27582]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

" **Set my own SMTP parameters (for advanced users ONLY)** " 
Add correct SMTP setting for above setting in Prestashop backend

if using the correct SMTP setting for Prestashop 1.7.8.3, its gives" Error: Please check your configuration" 
1.7.8.3 screenshot ==> http://i.imgur.com/qyGQRRn.png

Same SMTP setting working fine on 1.6.1.23  ==> screenshot   http://i.imgur.com/pCAy8dI.png

In 1.6.1.23 test mail was successfully sent. But for 1.7.8.3 test mail was not sent. Both websites on the same server and the PHP version is 7.4

### Expected behavior

When sending test mail, mail should need to be sent to the mentioned email id.

All default Emails should need to work.

### Steps to reproduce

1. Open admin email setting in 1.7.8.3 
/configure/advanced/emails/
2. Select radio option "Set my own SMTP parameters (for advanced users ONLY)"
3. Add correct SMTP settings
4. Add test email id 
 Test your email configuration:
5. Click Send test email button

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

email

**Comment by hibatallahAouadni** [comment]
Hello @pks891618 

I didn't manage to reproduce your issue with PS1783, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/152381983-66a2f559-10e8-49b6-9795-192d4dfe9aa0.mp4

Please check and feedback.
Thanks!

**Comment by Triloworld** [comment]
By default you must enter correct email to send test message:
`"When sending test mail, mail should need to be sent to the mentioned email id."`

This need to be fixed to use user **currently logged user email address** and change to feature

That message is too generic and not provide hint on what stage user having problem - hundreds issues can be close or re-check if we get more detailed message on this screen about connection. 
Like on what stage is error: server (all required setting and modules are installed) connection (is connection close, maybe bounce)? header (not accepting)? php code (error in code is silent)? template (error in template or empty)? setting(not saved)?

This test just ensure is fully working, all other thinks are creating plenty issues on this repository.

**Comment by pks891618** [comment]
@Triloworld  thanks for  reply, i found the issue. The problem was that in admin mail was set as @gmail.com . Now as my SMTP host blocking this because of the from email id . As my host dont allow me to send  mail from  other domain name.

e.g if my host name is abc.com then i am using SMTP host setting for abc.com and when i was sending mails from address was @gmail.com
