### ISSUE TITLE
Bad display of mullti store checkboxes in webservice

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#27595]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Once you are on the webservice page with the multistore enabled, you have this display.
<img width="823" alt="Capture d’écran 2022-02-05 à 10 10 19" src="https://user-images.githubusercontent.com/2631425/152635830-db7f53bf-8a70-4986-b16d-c766aa152d2a.png">

### Expected behavior

Have the toggle with "multistore" selection and checkboxes seens as other part
<img width="823" alt="Capture d’écran 2022-02-05 à 10 15 18" src="https://user-images.githubusercontent.com/2631425/152635845-016c541e-07fb-478a-ab3a-c61105502875.png">
.

### Steps to reproduce

1. Enable the multistore
2. Go to Webservice page

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by ghost** [comment]
I can reproduce the bug, it's for all  new mullti shop checkboxes.

You can also test: Maintenance, Shipping Preferences.

Introduce by : https://github.com/PrestaShop/PrestaShop/pull/25879

**Comment by NeOMakinG** [comment]
Looking at it atm

**Comment by NeOMakinG** [comment]
I did test on develop

You need to build asset and clear your cache

![image](https://user-images.githubusercontent.com/14963751/152753832-e20e0484-ef38-4cb5-bf10-3dc4c1637d20.png)

I think you don't have the `.form-wrapper` style, I've the same result if I remove it !

**Comment by NeOMakinG** [comment]
Feel free to open it again if you reproduce it with cache cleared and asset built!

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

As @NeOMakinG mentioned above, all well displayed, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/152756126-270e4c07-347e-4c2e-b69b-fd8081032a7f.mp4

Thanks!

**Comment by PrestaEdit** [comment]
I can confirm ! Sorry for this false issue.
