### ISSUE TITLE
[Multistore] BO - New product created in all shops is not displayed in the list

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27599]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After configuring Multistore, create a new shop. So when selecting the All shops category, the products that are created in all shops are not displayed in the list of products in BO.

In Product V2, we cannot create a product in all shops.

### Steps to reproduce

1. Enable multistore
2. Create a new shop
3. Go to BO > Catalog > Products V1 > Select All shops
4. Create a product & enable it
5. Go to Product list page
6. See error > the product is not displayed

https://user-images.githubusercontent.com/16067358/152645316-d10f4ba8-56b2-4bf1-b1db-0686f0a06f78.mp4

With PS1783 => ok

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29195
