### ISSUE TITLE
BO - Customer cannot enter the email adress when the password is forgotten

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#27591]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Customer cannot enter the email adress when the password is forgotten

Issue is reproduced with 1.7.8.0/1.7.8.3 and develop

https://watch.screencastify.com/v/A9LiYEKi4YgZe7hIXayz
![image](https://user-images.githubusercontent.com/89604350/152550713-687b4089-afec-4ea0-b110-4a0360f69458.png)

With 1.7.7.8:
https://watch.screencastify.com/v/gNaGL5MHaGQysIuxVLv3

![image](https://user-images.githubusercontent.com/89604350/152550616-76809cb8-bef1-489b-a2da-8bd5198ac115.png)
![image](https://user-images.githubusercontent.com/89604350/152550653-18edd6f8-892a-46a2-aeed-5119f82bf6ab.png)

### Steps to reproduce

1- Go to BO 
2- Login
3- Click on I forget my password
4- See error

### PrestaShop version(s) where the bug happened

develop,1.7.8.0,1.7.8.3,1.7.8.x

### PHP version(s) where the bug happened

7.3/7.2

**Comment by hibatallahAouadni** [comment]
FYI: it's only reproducible on Chrome with Ubuntu

https://user-images.githubusercontent.com/23308427/152554156-a88ce6a8-b740-4c60-874e-32642f72947e.mp4

**Comment by khouloudbelguith** [comment]
Hello @marwachelly, @hibatallahAouadni,

I tried with 178x branch.
It is ok in my case

https://user-images.githubusercontent.com/16067358/152576441-7a84f720-cf25-442d-b93c-cb872740526a.mp4

**Information**
![image](https://user-images.githubusercontent.com/16067358/152576506-e2e4872a-5944-4f30-b221-8b7d4d5db7c2.png)

I used Chrome Version 94.0.4606.71

Thanks!

**Comment by marwachelly** [comment]
Hello @hibatallahAouadni ,@khouloudbelguith 

Thanks for the investigation. The bug is reproducible starting from PS 1.7.8.0 with Chrome version 96.0.4664.93.
![image](https://user-images.githubusercontent.com/89604350/152765091-18e58dbb-3860-49c9-a01e-dc96c6c30429.png)

Thanks,

**Comment by MatShir** [comment]
On Chrome 98, the issue seems to be fixed. I will close the issue. Thanks ! :)
