### ISSUE TITLE
Page number is not included in meta titles for new-products, best-sales, prices-drop

### ISSUE THREAD

**Issue by Amazzing** [PrestaShop/PrestaShop#27596]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

As the title says, page number is not included in meta_title of some product listing controllers. 

### Expected behavior

If page number is > 1, it should be included in meta_title for better SEO. 
For example, when user is on 2nd page of Best Sellers page, meta title should be "Best Sales (2)". 
Currently page number is added only on Category and manufacturer listing pages. 

### Steps to reproduce

1. Go to 2nd page of 'newproducts' or 'bestsales' or 'pricesdrop'

### PrestaShop version(s) where the bug happened

all

**Comment by matks** [comment]
Hi @Amazzing 

> If page number is > 1, it should be included in meta_title for better SEO.

Would it be possible to provide sources about this SEO best practice? Unfortunately SEO is not an exact science, so sometimes if you ask 4 people the same question about SEO you get ... 4 different answers 😅

**Comment by Amazzing** [comment]
Hi, @matks

Actually page number is already included in meta_title on **Category/Manufacturer** controllers. 
If you check meta_title of 2nd page of any Category on a clean PS installation, you will find page number **(2)**

[#27598](https://github.com/PrestaShop/PrestaShop/pull/27598) applies same behavior on **other product listing controllers**, that have multiple pages. 

I didn't find a reputable source saying that you should add page number in meta_title. 
But general idea is simple - duplicated meta_titles used on different pages are not good for SEO. 

In either case, I will try to find a reliable source later.

**Comment by Hlavtox** [comment]
@matks No science here, he is right. :-)
Page 2 = different products = different content = different meta = different canoncial.

**Comment by hibatallahAouadni** [comment]
Hello @Amazzing 

Your proposal seems an improvement more than a bug.
So, thank you for your suggestion and your PR :rocket: 
The Product Team will take it into consideration for future developments. 

Thank you

**Comment by matks** [comment]
> @matks No science here, he is right. :-) Page 2 = different products = different content = different meta = different canoncial.

You would be surprised how deep such topics go 😄 

The problem is exactly that there's no science here. SEO is reverse-engineering Google algorithm.
