### ISSUE TITLE
Associations are missing in the JSON output in webservice

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#27594]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Once the JSON output is choosen to see a specific ressource into the webservice, the associations are missing.

### Expected behavior

Associations are getted.

### Steps to reproduce

1. Enable the webservice
2. Fetch the /api/customers/1
3. See the associations in XML
4. Add the JSON output format
5. See that associations of groups is no more there

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

PHP 8 (It's working with PHP 7.4)

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

I didn't manage to reproduce the issue with develop, see the attached screen record below:

![image](https://user-images.githubusercontent.com/23308427/152758338-0d5a4e3a-6006-4696-95d2-f68ca5ae0ec1.png)

Closing the issue as there's no bug.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by PrestaEdit** [comment]
Hi @hibatallahAouadni ,

I've take the time to make a test about it: the issue is with PHP 8 ; once I use the 7.4, it's working as waiting.

`PHP Warning #2] Undefined array key 0 (/classes/webservice/WebserviceOutputBuilder.php, line 718)`
