### ISSUE TITLE
Webservice price for product seems incorrect

### ISSUE THREAD

**Issue by pleasure-progress-against-principle** [PrestaShop/PrestaShop#276]
Products have a base price that is adjusted based on the impact price of the variant product. But when calling api/products that price that gets returned seems to be the base price + the highest impact price. It would be much more logically consistent if it returned to base price found in the "price" column in the "ps_product" table.

**Comment by marionf** [comment]
Hello, 
This issue is old, so I close it.
If you still have it on the last version (PrestaShop 1.7.4.2), please open a new one.
Regards
