### ISSUE TITLE
impossibile caricare nuovo modulo

### ISSUE THREAD

**Issue by grafica3B** [PrestaShop/PrestaShop#27607]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![Cattura](https://user-images.githubusercontent.com/99173363/152756211-b358a269-7bc0-46e5-bb76-29467f4306ee.JPG)

Vorrei inserire un nuovo modulo, ma quando clicco su "Carica un modulo" non succede nulla.
Ho provato a cliccare più volte, a entrare ed uscire dall'account, a cambiare browser, ma il problema persiste.
Che devo fare?

### Steps to reproduce

Entro su prestashop
Clicco su "Moduli"
clicco su "Carica un modulo"

### PrestaShop version(s) where the bug happened

1.7.7.1.

**Comment by hibatallahAouadni** [comment]
Hello @grafica3B 

Please send your request in English. English is the norm on GitHub.

Thank you
