### ISSUE TITLE
BO - An exception is thrown when adding a Webp format image

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#27619]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An exception is thrown when adding a `Webp` format image in different pages : 
-BO > SELL > Catalog > Categories > Add new category > Add a `Webp` format image (for `Category cover image`, `Category thumbnail` and `Menu thumbnails`)
-BO > SELL > Catalog > Attributes & Features > Add new value > Add a `Webp` format image (for `Texture`)

![image](https://user-images.githubusercontent.com/92912932/152956348-df11c94c-0799-4192-93ce-46f597ee5deb.png)

https://user-images.githubusercontent.com/92912932/152956809-9cbb6c44-be1d-44fa-b857-e99ae0335b24.mp4

Webp format was functional and added in develop branch with this [PR](https://github.com/PrestaShop/PrestaShop/pull/24394).

### Expected behavior

The `Webp` image should be well added.

### Steps to reproduce

for Category page
1. BO > SELL > Catalog > Categories > Add new category > Add a `Webp` format image 
2. See error > An exception is thrown

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

**Comment by atomiix** [comment]
@HanaRebaiQA do you have the php-gd extension installed?

**Comment by HanaRebaiQA** [comment]
@atomiix Yes! the php-gd extension is installed on my web server
![image](https://user-images.githubusercontent.com/92912932/153168958-1134436a-801a-4680-a055-a370539ec350.png)

https://user-images.githubusercontent.com/92912932/153170250-67cd10d4-6964-40b3-ab64-2c289de88ac1.mp4

**Comment by atomiix** [comment]
@HanaRebaiQA it seems that you don't have the webp support in your php-gd extension. Here's what I have:
<img width="497" alt="Capture d’écran 2022-02-09 à 11 15 57" src="https://user-images.githubusercontent.com/2168836/153177855-2f543d29-1c5e-4db6-81c9-b48028f5d99e.png">

**Comment by HanaRebaiQA** [comment]
Thank You @atomiix for your response.
After configuring the `Webp Support `of the `php-gd extension` in the Dockerfile, the issue is fixed.
![image](https://user-images.githubusercontent.com/92912932/154287992-4787ef92-e86e-4586-90c0-9fd94e8b3cff.png)

https://user-images.githubusercontent.com/92912932/154288719-aed00f2d-5dba-4b9b-b2ea-b69b8368698f.mp4


So, i'll close the issue.
