### ISSUE TITLE
BO - An error is displayed in some legacy pages

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27616]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This issue is a regression in the branch 178x
PS1783 => ok
We have some errors in the BO > Advanced Parameters > Multistore page / BO > Shop Parameters > Customer Settings Add new Group / BO > Shop Parameters > Contact > Stores page
![image](https://user-images.githubusercontent.com/16067358/152837928-abf234df-5150-4ec4-bca8-71dc527b2bea.png)

This issue is reported previously in the develop branch
https://github.com/PrestaShop/PrestaShop/issues/27348

### Steps to reproduce

1. Enable debug mode
2. Go to BO > Shop parameters > General
3. Enable multistore
4. Go to Advanced parameters > Click on multistore
5. See an error

1. Go to BO > Shop Parameters > Customer Settings
2.  Add new Group 
3. See error

1. Go to BO > Shop Parameters > Contact > Stores page

### PrestaShop version(s) where the bug happened

1.7.8.x

### PHP version(s) where the bug happened

7.3

**Comment by Progi1984** [comment]
Fixed by me in #27648 and tested by @khouloudbelguith
