### ISSUE TITLE
FO - Checkout - When we order a pack product created with Product V2 , the Shipping method is not displayed

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27613]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

We create a pack product from Products page V2
In the FO, when we try to order this product, the shipping method is not displayed.

### Steps to reproduce

1. Enable Experimental product page
2. Go to BO > Catalog > Products V2
3. Create a new pack product > Edit the quantity, price & save
4. Go to FO > Search this product > add to cart > complete order
5. In the checkout page > See error: the Shipping method is not displayed
6. Place the order
7. Go to BO > Orders > View last order created
8. See an error in the Carrier Tab

https://user-images.githubusercontent.com/16067358/152786723-1880c803-e8bf-4d0d-80dc-1ae490c74dbc.mp4

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4

**Comment by atomiix** [comment]
I think this one is related to #27304.

**Comment by MatShir** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/27304.
