### ISSUE TITLE
Multistore - wrong BO language

### ISSUE THREAD

**Issue by cdb88** [PrestaShop/PrestaShop#27617]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Fresh installation of prestashop.
2 stores
2 domains
Store 1 domain.com: English language.
Shop 2 domain.es: Spanish language.

User profile language: Spanish

I always access the BO by domain.com

With these conditions the BO is almost all in English, some parts (few) in Spanish.

You can see the problem in the following video:

https://user-images.githubusercontent.com/97175145/152846321-1ea2f817-b5ab-4abd-85c3-d8a83baf16f7.mp4

This problem occurs with 1.7.8.3, 1.7.8.2, 1.7.8.1 and 1.7.8.0 with 1.7.7.8 and earlier I have no problem. 

### Expected behavior

The language of the BO must be the one selected by the user in his profile

### Steps to reproduce

1.- Make a fresh installation of prestashop with two languages, for example English and Spanish.
2.- configure the user's language in Spanish. All BO menus appear in Spanish.
3.- activate the multistore
4.- Set up a second store.
5.- configure English only for store 1
6.- configure Spanish only for store 2

Now the language of the BO is wrong.

### PrestaShop version(s) where the bug happened

1.7.8.0, 1.7.8.1, 1.7.8.2, 1.7.8.3

### PHP version(s) where the bug happened

7.4

**Comment by marwachelly** [comment]
Hello,
I was able to reproduce the issue with PrestaShop version 1.7.8.0 and 1.7.8.3 with PHP7.4 and 7.3
https://watch.screencastify.com/v/1ZPbRJoGFBsLFQaX2J9z

But the issue is not reproducible with 1.7.7.8 
https://watch.screencastify.com/v/DCfTetqT2HBdLxXOmxHm

 I'll add this to the debug backlog so that it's fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks,

**Comment by cdb88** [comment]
Thanks a lot.

I don't have enough knowledge to propose a solution to the problem, but I have traced the error to the config/config.inc.php file

PS 1.7.7.8 on line 202
if (!isset($language) || !Validate::isLoadedObject($language)) {
     $language = new Language(Configuration::get('PS_LANG_DEFAULT'));
}

PS 1.7.8.3 on line 224
if (!isset($language) || !Validate::isLoadedObject($language) || !$language->isAssociatedToShop()) {
     $language = new Language(Configuration::get('PS_LANG_DEFAULT'));
}

Added a validation that should not affect the BO:
"!$language->isAssociatedToShop()"

If I remove this validation everything works fine, but obviously this change will have been made for a good reason.

**Comment by Devloginout** [comment]
Hi everyone i don't recommended erase !$language->isAssociatedToShop()) this can cause errors in Front if you have a multistore(conflicts in lenguage), for solve this bug in BO without erase the verification only add another verification: !isset($context->employee) the results it looks like this:

if (!isset($language) || !Validate::isLoadedObject($language) || !$language->isAssociatedToShop() && !isset($context->employee) ) {
    $language = new Language(Configuration::get('PS_LANG_DEFAULT'));
}

See you! :)

**Comment by cdb88** [comment]
> Hi everyone i don't recommended erase !$language->isAssociatedToShop()) this can cause errors in Front if you have a multistore(conflicts in lenguage), for solve this bug in BO without erase the verification only add another verification: !isset($context->employee) the results it looks like this:
> 
> if (!isset($language) || !Validate::isLoadedObject($language) || !$language->isAssociatedToShop() && !isset($context->employee) ) { $language = new Language(Configuration::get('PS_LANG_DEFAULT')); }
> 
> See you! :)

This solution seems to be working fine for me.

**Comment by MeKeyCool** [comment]
@MatShir, I take this one ^^

**Comment by MeKeyCool** [comment]
Please take a look to this PR cause we found another problem and I offered to fix the behavior : [https://github.com/PrestaShop/PrestaShop/pull/28392#issuecomment-1119581385](https://github.com/PrestaShop/PrestaShop/pull/28392#issuecomment-1119581385)

> Thanks @AureRita  for finding [another issue](https://github.com/PrestaShop/PrestaShop/pull/28392#issuecomment-1119581385)
> 
> When you setup multishop, default Prestashop language is applied to every shop even if it is not available to those shops.
> As no "default language" attribute is defined for shops in multishop, I solved this inconsistency by taking the first language available I find for the shop. This way,
> - If you have only one language available, it will be used.
> - If you have several languages allowed,
>    - If default Prestashop language is one of them, it will be used.
>    - If default Prestashop language is not allowed for this shop, the first time you visit, it may be "random" language but once you select your language, it will be taken from your session.

@PrestaShop/product-team , are you Ok with this behavior ?

**Comment by Progi1984** [comment]
Fixed by @MeKeyCool in #28392 and tested by @AureRita
