### ISSUE TITLE
Mail templates could not be edited

### ISSUE THREAD

**Issue by vladikk007** [PrestaShop/PrestaShop#27624]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Email tamplates could not be edited in fresh shop installation (no orders)
![mail_tamplate_error](https://user-images.githubusercontent.com/9325324/153049949-b6373129-d01c-43de-a1d0-3c36c1dc5c53.JPG)

### Expected behavior

Template editor should be opened.

### Steps to reproduce

1. empty orders table
2. try to edit some email template

### PrestaShop version(s) where the bug happened

1.7.8.0-1.7.8.3

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @vladikk007 ,

I can't reproduce your issue with PS 1.7.8.2. 
<img width="900" alt="Screenshot 2022-02-09 at 09 48 45" src="https://user-images.githubusercontent.com/16019289/153159090-99aaf7c5-4ed2-4a04-8167-1b1dbafc8900.png">

https://user-images.githubusercontent.com/16019289/153159101-9b44ccdb-6881-4cf0-9ae7-93c817661a47.mov

Could you send a screen record please ?
Thanks!

**Comment by vladikk007** [comment]
Hello @florine2623,

the issue is related to email theme editor (not template). Sorry, my mistake...
![theme editor](https://user-images.githubusercontent.com/9325324/153160881-12f247ae-c5a8-4433-836d-dc88dde682d0.jpg)

**Comment by florine2623** [comment]
@vladikk007 ,

Please check my screen record, I don't have an exception either.

https://user-images.githubusercontent.com/16019289/153181506-5dd7bb11-0290-4634-bbf9-4fdd888e2e06.mov

Could you make a screen record of your bug ?
Thanks

**Comment by vladikk007** [comment]
Debug mode should be active:
https://user-images.githubusercontent.com/9325324/153187469-1d4751f3-00ca-4802-888c-7cfd325d2ae9.mp4

**Comment by florine2623** [comment]
I still can't reproduce the issue.

https://user-images.githubusercontent.com/16019289/153189521-70a631bb-721a-4ce9-ae3d-b6fa285bab17.mov

If you have any overrides in the file mentioned in the Exception, please delete them.
Also, if you have a fresh install, there might be something that did not go well during installation. So I suggest re-installing your shop. 
You can also check that your system requirements are met : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

I will close your issue as it cannot be reproduced.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thanks!

**Comment by vladikk007** [comment]
do you have any orders in your shop?
![image](https://user-images.githubusercontent.com/9325324/153202082-33c4e578-7a8c-4ef6-9bde-1cfbacad37b8.png)
