### ISSUE TITLE
Stock movement without order reference is created by undelivered new order

### ISSUE THREAD

**Issue by saulaski** [PrestaShop/PrestaShop#27627]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

New order created from BO always add a new stock movement:
- from any order status, not only "Delivered"
- without any reference to order (id_order = NULL)

Later when the order status is switched to a status with the flag "shipped" activated, the stock movement is duplicated with the correct order reference

### Expected behavior

- Stock movement should be created only from a new order with "delivered" status
- This order should be referenced in the newly created stock movement

Initial specifications: https://forge.prestashop.com/browse/FF-1

### Steps to reproduce

1. Create a new order from BO with "Waiting for payment" status:
2. Observe the new stock movement inserted in database table ps_stock_mvt with id_order = NULL

### PrestaShop version(s) where the bug happened

8.0, 1.7.8.x

### PHP version(s) where the bug happened

7.4.3

**Comment by florine2623** [comment]
Hello @saulaski ,

Thanks for the report, I manage to reproduce the issue in PS 1.7.6.x, PS 1.7.7.x, PS 1.7.8.x and develop, so I can confirm that this behavior is indeed a bug.

Here's what I have in the database, table `ps_stock_mvt`, I should have the `id_order` :
<img width="648" alt="Screenshot 2022-02-11 at 10 51 17" src="https://user-images.githubusercontent.com/16019289/153570637-e8de64e3-6a1b-4bc8-ad50-56caad6aca6a.png">


Thanks for your PR, it will be reviewed soon !

**Comment by saulaski** [comment]
Thank you @florine2623
Please note that this issue seems related to a bright new issue : https://github.com/PrestaShop/PrestaShop/issues/27631#issuecomment-1034152309

In any case, the current business rules look inconsistent with initial specifications: https://forge.prestashop.com/browse/FF-1
As currently discussed in my PR: https://github.com/PrestaShop/PrestaShop/pull/27626#discussion_r803050035

**Comment by saulaski** [comment]
PM approved, BO should behave like FO.
A new order should add a stock movement only if the product is physically "shipped", i.e. if the order status is "Shipped" or "Delivered".
