### ISSUE TITLE
BO - No confirmation pop-up or product removal notification from Merchandise Returns (Wrong notification is displayed)

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#27628]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

No confirmation pop-up or product removal notification from Merchandise Returns. 
There is an `INVALID SECURITY TOKEN `is diplayed, and when click on `I understand the risks...`, the product will be removed
![image](https://user-images.githubusercontent.com/92912932/153158040-124ccbbf-3364-4297-b595-2e6d5388c2c5.png)

https://user-images.githubusercontent.com/92912932/153157915-e5ff04d6-fcb1-4209-a90c-4ef2108bab37.mp4

### Expected behavior

A pop-up for the confirmation delete and to be redirected in the same page of the Merchandise Returns.

### Steps to reproduce

1. Create an order with min two products from BO/FO
2. BO > SELL > Orders > Orders > Change the status of the created order to `Delivred` or `Shipped` 
3. FO > Orders > Click on Details of Orders
4. Click for the product  for `Merchandise Retunrs`
5. Come back to BO > SELL > Customer Service > Merchandise Returns > Click on the created Merchandise returns
6. Click on Delete button of the product
7. See error > `I understand the risks ...`  is displayed !

### PrestaShop version(s) where the bug happened

1.7.7.8 & develop & 1.7.8.x

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment]
This issue is fixed but another one has raised
https://github.com/PrestaShop/PrestaShop/issues/34922
