### ISSUE TITLE
Webservice to create article

### ISSUE THREAD

**Issue by oliviermollier** [PrestaShop/PrestaShop#27629]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello, I plan to use Prestashop as from of my ERP. I try to initialize the article list via webservice but when the database is empty the webservice check for article position. but

0 can't be a valid value
1 is impossible because it can't be higher than the number of product in the database.

### Expected behavior

Accept the creation of article if category is empty

### Steps to reproduce

1) install fresh prestashop without data.
2) create 1 category
3) call webservice with the below content (error is raised by <position_in_category>1</position_in_category>)

"<prestashop xmlns:xlink=\"http://www.w3.org/1999/xlink\">
<product>
<id/>
<id_manufacturer>0</id_manufacturer>
<id_supplier>0</id_supplier>
<id_category_default><![CDATA["+"1"+"]]></id_category_default>
<new>1</new>
<cache_default_attribute/>
<id_default_image/>
<id_default_combination/>
<id_tax_rules_group>1</id_tax_rules_group>
<position_in_category>1</position_in_category>
<type/>
<id_shop_default/>
<reference>"+"1"+"</reference>
<supplier_reference/>
<location/>
<width>"+"1"+"</width>
<height>"+"1"+"</height>
<depth>"+"1"+"</depth>
<weight>"+"1"+"</weight>
<quantity_discount/>
<ean13>""</ean13>
<isbn/>
<upc/>
<mpn/>
<cache_is_pack/>
<cache_has_attachments/>
<is_virtual/>
<state>1</state>
<additional_delivery_times>1</additional_delivery_times>
<delivery_in_stock>
<language id=\"1\"/>
</delivery_in_stock>
<delivery_out_stock>
<language id=\"1\"/>
</delivery_out_stock>
<on_sale/>
<online_only/>
<ecotax/>
<minimal_quantity/>
<low_stock_threshold/>
<low_stock_alert/>
<price>"+"1"+"</price>
<wholesale_price/>
<unity/>
<unit_price_ratio/>
<additional_shipping_cost/>
<customizable/>
<text_fields/>
<uploadable_files/>
<active>1</active>
<redirect_type/>
<id_type_redirected/>
<available_for_order>1</available_for_order>
<available_date/>
<show_condition/>
<condition/>
<show_price/>
<indexed/>
<visibility/>
<advanced_stock_management/>
<date_add/>
<date_upd/>
<pack_stock_type/>
<meta_description>
<language id=\"1\"/>
</meta_description>
<meta_keywords>
<language id=\"1\"/>
</meta_keywords>
<meta_title>
<language id=\"1\"/>
</meta_title>
<link_rewrite>
<language id=\"1\"/>
</link_rewrite>
<name>
<language id=\"1\">"+"TEST"+"</language>
<language id=\"2\">"+"TEST"+"</language>
</name>
<description>
<language id=\"1\">"+"TEST"+"</language>
<language id=\"2\">"+"TEST"+"</language>
</description>
<description_short>
<language id=\"1\">"+"TEST"+"</language>
<language id=\"2\">"+"TEST"+"</language>
</description_short>
<available_now>
<language id=\"1\"/>
</available_now>
<available_later>
<language id=\"1\"/>
</available_later>
<associations>
<categories>
<category>
<id>
<![CDATA["+"1"+"]]>
</id>
</category>
</categories>
<images>
<image>
<id>
<![CDATA[ ]]>
</id>
</image>
</images>
<combinations>
<combination>
<id>
<![CDATA[ ]]>
</id>
</combination>
</combinations>
<product_option_values>
<product_option_value>
<id>
<![CDATA[ ]]>
</id>
</product_option_value>
</product_option_values>
<product_features>
<product_feature>
<id>
<![CDATA[ ]]>
</id>
<id_feature_value>
<![CDATA[ ]]>
</id_feature_value>
</product_feature>
</product_features>
<tags>
<tag>
<id>
<![CDATA[ ]]>
</id>
</tag>
</tags>
<stock_availables>
<stock_available>
<id>
<![CDATA[ ]]>
</id>
<id_product_attribute>
<![CDATA[ ]]>
</id_product_attribute>
</stock_available>
</stock_availables>
<accessories>
<product>
<id>
<![CDATA[ ]]>
</id>
</product>
</accessories>
<product_bundle>
<product>
<id>
<![CDATA[ ]]>
</id>
<id_product_attribute>
<![CDATA[ ]]>
</id_product_attribute>
<quantity>
<![CDATA[ ]]>
</quantity>
</product>
</product_bundle>
</associations>
</product>
</prestashop>

### PrestaShop version(s) where the bug happened

1.7.8.3

### If your bug is related to a module, specify its name and its version

webservice

**Comment by florine2623** [comment]
Hello @oliviermollier ,

Could you specify the Steps to reproduce please ? And fill in the Expected behavior ?
Thanks

**Comment by oliviermollier** [comment]
updated

**Comment by oliviermollier** [comment]
I finaly found a same article

the proposal was : 

For solving it :

You must set id_category_default with an ID AND position_in_category with a value > 1.
OR you must unset id_category_default AND position_in_category.
I will try and update it

**Comment by florine2623** [comment]
@oliviermollier ,

Let me know the outcome of your fix.
Waiting for your feedback !

**Comment by oliviermollier** [comment]
Hello, i tested the second option proposed ( unset id_category_default AND position_in_category) and still have the same error

You cannot set 0 or a negative position, the minimum is 1.  I made a quick fix in Product.php but still the standard version seems to have  this bug

**Comment by khouloudbelguith** [comment]
Hi @oliviermollier,

Thanks a lot for your feedback.
I manage to reproduce the issue with PS1783.

PS1778 => OK

https://user-images.githubusercontent.com/16067358/153580521-2bac5e0d-0c60-40e4-a5de-41c44111d6b7.mp4

1783 => NOK

https://user-images.githubusercontent.com/16067358/153580546-2ad736a8-34d9-4f32-bac5-1adfcc239c89.mp4

Here's the PR: https://github.com/PrestaShop/PrestaShop/pull/27622 to fix the issue.
Your ticket is a duplicate of #27411
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #27411

**Comment by Shoprunners** [comment]
Sorry, but I don't see this as an duplicate of #27411. The problem is in the classes/Product.php class, method setWsPositionInCategory

there is an if clause 
`if ($position > count($result) ) {` //line 7124

it should be 

`if ($position > count($result) &&  count($result) > 0 ) {` //line 7124


and in the following rows

```
if( count($result) > 0) {
			// result is indexed by recordset order and not position. positions start at index 1 so we need an empty element
			array_unshift($result, null);
			foreach ($result as &$value) {
				if($value != null) {
					$value = $value['id_product'];	
				}
			}
		}
```

**Comment by Shoprunners** [comment]
it is an duplicate of #14903 or vice verca
