### ISSUE TITLE
Fix - for ps_emailalerts module v. 2.3.2 into is product.tpl file

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#27625]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi
I've a website with this error, it happens when the product is without a quantity

![3](https://user-images.githubusercontent.com/653230/153063770-aad2c1e6-bf40-4e14-866a-14245e0c90b6.png)

![4](https://user-images.githubusercontent.com/653230/153063915-b5ec21b1-7d41-4012-8598-c1ab78514df0.png)

bye

### Expected behavior

it is a bug of this module

### Steps to reproduce

the problem is very simple to understand:
the problem is on the hook DisplayProductAdditionalInfo about the smarty variables passed to the product.tpl

`        $this->context->smarty->assign(
            [
                'id_product' => $id_product,
                'id_product_attribute' => $id_product_attribute,
                'id_module' => $this->id,
            ]
        );`

the variables are
id_product
id_product_attribute

instead in the product.tpl a variable that does not exist is expected $product

`{$product.id_product}
{$product.id_product_attribute}`

but they should be named so

`{$id_product}
{$id_product_attribute}`

![38](https://user-images.githubusercontent.com/653230/153063917-5cd63bb5-5ab5-4ae2-827a-008be89c2474.png)
![81](https://user-images.githubusercontent.com/653230/153063925-43ab0c15-972f-4967-b7c0-d1beb3bcc5ec.png)

**Screen record**
https://watch.screencastify.com/v/ICH8dPstR6HPizqZTUrf

### PrestaShop version(s) where the bug happened

1.7.6.5

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

ps_emailalerts v2.3.2

**Comment by Maofree** [comment]
Hi
Any news about this issue?

thanks

**Comment by florine2623** [comment]
Hello @maofree ,

I can't reproduce your issue on PS 1.7.6.5 nor 1.7.8.x and on develop.

Here are the steps I followed :
- Create shop
- Install ps_emailalerts v2.3.2
- Configure the module
- Change quantity of a product to 0 (tested with standard product & product with combinations)
- Receive email of out-of-stock product, no exception ✅ 
<img width="696" alt="Screenshot 2022-02-09 at 16 36 01" src="https://user-images.githubusercontent.com/16019289/153234685-22689d5c-e4b8-45d9-a33b-b2b8be509639.png">

Is there anything else that you didn't mention ?
Thanks!

**Comment by Maofree** [comment]
Hi
the error is shown on the product page
however ask to some developer and they will see that the smarty variables are not correct for the product.tpl file

**Comment by Maofree** [comment]
ask to a developer to check at line 573 of ps_emailalerts.php
then to check the views/templates/hook/product.tpl at line 38

the variables are not correct

it is not important the prestashop's version, it is an issue of the module

**Comment by florine2623** [comment]
ping @PrestaShop/prestashop-core-developers ,

Could you check the following and confirm that it is a bug ?
>ask to a developer to check at line 573 of ps_emailalerts.php
then to check the views/templates/hook/product.tpl at line 38
the variables are not correct

Thanks!

**Comment by Maofree** [comment]
Hi
I've another website with this error, at this time the hosting alert with an email about php errors in the log

![4](https://user-images.githubusercontent.com/653230/154142729-0a2265e6-b940-4561-af87-aec28265fdb4.png)
![11](https://user-images.githubusercontent.com/653230/154142741-ab51b1bd-f66f-4315-9570-4fd086724dab.png)

this problem is present on all website with mail alerts 2.4.2

can you increase the priority about this bug?

thanks

**Comment by ghost** [comment]
I can't reproduce with the default theme wich theme you use ?

**Comment by Maofree** [comment]
Hi
I've checked better the code of product.tpl and ps_emailalerts.php around hookDisplayProductAdditionalInfo
I think you cannot see this error because you use the last version of prestashop and last version of classic theme, but the addons theme are not updated and not all website use the last version of prestashop.

`        <button
            data-product="{$product.id_product}"
            data-product-attribute="{$product.id_product_attribute}"
            class="btn btn-primary js-mailalert-add mt-1"
            rel="nofollow">
            {l s='Notify me when available' d='Modules.Emailalerts.Shop'}
        </button>`

{$product.id_product}
{$product.id_product_attribute}

using this code to get the id_product and id_product_attribute is it possible only if $product is present in the theme, because the ps_emailalerts.php send 

`        $this->context->smarty->assign(
            [
                'id_product' => $id_product,
                'id_product_attribute' => $id_product_attribute,
                'id_module' => $this->id,
            ]
        );`

so if you get the Ids from the module the variables should be
{$id_product}
and
{$id_product_attribute}

30 minutes ago, I got another 500 error from a website with prestashop 1.7.7.5 with theme bought from addons

I think is much better to get the id values from the module to avoid these problems

**Comment by ghost** [comment]
What you have in this file of your theme : 

_/themes/MyTemplate/templates/catalog/_partials/product-additional-info.tpl_

**Comment by Maofree** [comment]
![5](https://user-images.githubusercontent.com/653230/154240162-191de898-b09b-4991-ace4-de8a569bab2e.png)

**Comment by Maofree** [comment]
Iooking in 6 different themes, all of them, have the same code.
ok I can see the variable product, it is missing the class js-product-additional-info

**Comment by ghost** [comment]
You have a folder in `/themes/MyTemplate/modules/ps_emailalerts/templates/hook/` with `product.tpl `

Can you copy past the content ?

**Comment by Maofree** [comment]
no there isn't any file product.tpl in all of these themes only
my-account.tpl
my-account-footer.tpl

so the code is get from the product.tpl of the module

I can give you the access to a website, the last one with this error that I fixed with my code

**Comment by ghost** [comment]
I made a PR  : https://github.com/PrestaShop/ps_emailalerts/pull/107

**Comment by Maofree** [comment]
ok thanks

**Comment by ghost** [comment]
Next time you can try to make a PR 

https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/

Thank for report

**Comment by matks** [comment]
thank you for the help @okom3pom

**Comment by florine2623** [comment]
Hello @maofree ,

Could you specify the exact steps to reproduce the bug ?
As well as provide a screen record of the bug please ?

As for now, it cannot be reproduce, so it cannot be tested.
Thanks!

**Comment by Maofree** [comment]
Hi
I get this problem on 5-7 websites, all of them manage the stock management enabled, and it happens when the "Product availability" is enabled
and only on products with combinations with quantity = 0.

I got 500 errors from google search console, with my fix the problem is solved in those sites, I'm sure that all websites with a theme bought from addons and the same stock management conditions have the same error

with the classic theme, there is not this error, I've checked.

the problem is due from the smarty variables used in product.tpl of the module. it use $product from the theme instead to use the variables passed from the main ps_emailalerts.php

to be sure to solve this error, you need to use
{$id_product}
and
{$id_product_attribute}

instead of
{$product.id_product}
{$product.id_product_attribute}

and you solve all possible theme compatibility

**Comment by ghost** [comment]
@maofree can you try a video

**Comment by Maofree** [comment]
Hi
here is the video
https://watch.screencastify.com/v/ICH8dPstR6HPizqZTUrf

I think it is due from prestashop's version
this video is done on a website with 1.7.6.7 and it has this error, instead on a site upgraded yesterday from 1.7.6.2 to 1.7.8.3 is without this error. I think it is not a problem of the theme, because the theme is the same used on 1.7.6

**Comment by ghost** [comment]
Tnak you can you put a screenshot like so the QA can be test

![Capture d’écran de 2022-02-23 15-50-52](https://user-images.githubusercontent.com/5064590/155343601-1989d19c-8482-4dd5-8e10-0fdf0f8b17ad.png)


Thank again

**Comment by Maofree** [comment]
![9](https://user-images.githubusercontent.com/653230/155344049-730a03b2-c682-4c2f-a20c-503dd6519e9f.png)

**Comment by Maofree** [comment]
Hi
right now I've upgraded a website from 1.7.7.5 to 1.7.8.3 and I get the same problem enabling the stock management

![7](https://user-images.githubusercontent.com/653230/155896395-7113cd0b-7c98-4d33-a182-3c4b7954b526.png)

**Comment by lmeyer1** [comment]
I can confirm the problem looking at the code:
> ask to a developer to check at line 573 of ps_emailalerts.php
then to check the views/templates/hook/product.tpl at line 38
> the variables are not correct
> it is not important the prestashop's version, it is an issue of the module

and

> the problem is due from the smarty variables used in product.tpl of the module. it use $product from the theme instead to use the variables passed from the main ps_emailalerts.php
> to be sure to solve this error, you need to use
`{$id_product}`
and
`{$id_product_attribute}`
> instead of
`{$product.id_product}` and 
`{$product.id_product_attribute}`
> and you solve all possible theme compatibility

While the bug happens only on 1.7.6.2, and no longer since 1.7.8.3, it would be good to clean up the code of the module.

**Comment by hibatallahAouadni** [comment]
Hello @maofree 

I didn't manage to reproduce the issue with: 

- PS**1767** and `ps_emailalert` **v2.3.2**
- PS**1778** and `ps_emailalert` v2.3.2
- PS**1785** and `ps_emailalert` v2.3.2
- PS**1778** and `ps_emailalert` **v2.3.3**
- PS**1785** and `ps_emailalert` v2.3.3

See the attached screen record below:

https://user-images.githubusercontent.com/23308427/162753284-58396f50-78a5-441a-95bb-5cba34a614cc.mp4

Please check if I miss something, or if there's a missing step :pray: 
Waiting for your feedback.

Thanks!

**Comment by Maofree** [comment]
Hi @hibatallahAouadni 
this problem is not present on "classic" theme, but on all (I think all because I got this problem on many themes) themes bought from Addons, so you cannot reproduce it on your demo website.
I've solved using an override inside the themes folder "modules" with my solution about the variables

bye

**Comment by hibatallahAouadni** [comment]
Hello @maofree 

So, should I close this issue as it's not related to PS Core?
Waiting for your feedback :pray: 

Thanks!

**Comment by Maofree** [comment]
Hi
Don't close this bug report.
Read all topic.
The problem is due from 2 variables.
From the module these 2 variables are sent in a mode but in the template tpl there are 2 different variables.
I understood this motive but without a fix many sites will have problems

**Comment by lmeyer1** [comment]
@hibatallahAouadni
There is a PR from @okom3pom that fixes this issue. We are waiting for the PR to be merged.
@maofree 
You could merge his fix into your source, while waiting for the PR.

**Comment by hibatallahAouadni** [comment]
@lmeyer1 The PR won't be merged till the issue will be validated :wink: 
That's why I asked for more infos to help me reproducing the issue :pray:

**Comment by lmeyer1** [comment]
:sob: Prestashop procedures :sob:
Look at the code. Problem is obvious. In https://github.com/PrestaShop/ps_emailalerts/blob/0caaf4b498e708038a69c61b72e79eb770e8d945/ps_emailalerts.php#L573 we define two variables that are not used here https://github.com/PrestaShop/ps_emailalerts/blob/0caaf4b498e708038a69c61b72e79eb770e8d945/views/templates/hook/product.tpl#L38.

I cannot reproduce @maofree's issue. It does not happen in my theme. But the problem at the source must be solved:
- either we must use the variables we defined (this will solve @maofree's issue)
- or the variables are defined by error, and we must not define them (@maofree will still have the issue and other themes might not work)

@okom3pom Do you think there is something we can do to get your PR merged ? Prestashop procedures are so rigid, they are a big obstacle to the open source project itself.

**Comment by Maofree** [comment]
Hi
It is not important to reproduce this error 500, it is simple to understand.
The module pass 2 variables
$id_product
$id_product_attribute
But in the theme the tpl get these 2 values from the global variable
$product
So only compatible theme can manage this new solution

**Comment by matks** [comment]
@lmeyer1 

> 😭 Prestashop procedures 😭

😄  for a while I thought indeed that "procedures" were heavy and counter-intuitive. But actually I was told some very nice reasons why it's important that we find a reproducible list of steps we can follow.

1. If we have the clear list of steps to reproduce the issue, anybody can reproduce the issue and anybody can test the bugfix submitted to fix it. So it's transparent and a mark of trust.
2. If we can reproduce the issue we can explore it to find maybe some more problems and, rather than fix the observable behavior, fix the root cause.
3. If we can reproduce the issue we can classify and then it will be easier in the future to link it to other issues, to have statistics about how many bugs solved in one area, it is even easier for people that encounter the same issue to search for it using labels and fix the solution.

So I know you think what's important here is to fix the issue rather than describe it perfectly, analyse it perfectly but _it makes sense_. It's for good. Having a clear, analyzed, well defined bug report is a great asset for a project.

QA team does not do this to annoy you, they do this to make the project better, better known, better organized, and make it easier to handle issues in the long term. It's a real work of quality and @hibatallahAouadni is doing her role with great skills ❤️

**Comment by Maofree** [comment]
Hi @matks 
in this case how is it possible to reproduce this error if the tests are done on the "classic" theme, but the errors are on addon's themes?

however I think it is not important to use $product variable to get id_product and id_product attribute, since they are supplied by the module and in that position they are updated when the combinations are changed

I solved it but maybe many have not even realized it, if google search console does not send them the emails with 5xx errors

**Comment by lmeyer1** [comment]
@matks Thanks for your explanations. @hibatallahAouadni also explained me on slack. I hope I can get enough information from @maofree to reproduce the issue and give steps to reproduce.

**Comment by MeKeyCool** [comment]
I don't think the problem is due to process. I think it is more a subject about "product" definition.

As prestashop offers an API for themes and plugins, we should be able  to test this API. In this case, the concerned prestashop user is the theme developer. I don't think that the QA team is organized to test the project this way :thinking: 

How could we enhance process / team / tools to integrate this kind of problem ?

But excluding this core organization question of the scope of this issue, it looks obvious that our process can't handle the QA easily, shouldn't we integrate a "default" process that ensure we are not stuck in a situation we didn't anticipate.
:thinking: Maybe simply a kind of super admin that could be invoked by core team (dev/qa/product) to find a common sens solution ?

**Comment by hibatallahAouadni** [comment]
Thanks @lmeyer1 :pray: 
Waiting for your steps :wink:

**Comment by MeKeyCool** [comment]
> I don't think the problem is due to process. I think it is more a subject about "product" definition.
> 
> As prestashop offers an API for themes and plugins, we should be able to test this API. In this case, the concerned prestashop user is the theme developer. I don't think that the QA team is organized to test the project this way thinking
> 
> How could we enhance process / team / tools to integrate this kind of problem ?
> 
> But excluding this core organization question of the scope of this issue, it looks obvious that our process can't handle the QA easily, shouldn't we integrate a "default" process that ensure we are not stuck in a situation we didn't anticipate. thinking Maybe simply a kind of super admin that could be invoked by core team (dev/qa/product) to find a common sens solution ?

I discussed a bit with @matks and I like his point of view. In a case like this, @maofree, you may share a basic template to reproduce the bug. Like this it helps a lot dev and QA that want to reproduce / solve the problem.
(and later we even can integrate it to automatic QA tests).

**Comment by lmeyer1** [comment]
This bug is not reproducible with @maofree's theme (PRS663 v.3) and ps_emailalerts (v.2.3.3) neither on PS 1.7.6.5 nor on PS 1.7.8.5

**Comment by Maofree** [comment]
![9](https://user-images.githubusercontent.com/653230/163145230-30a63fca-d1fd-4223-a901-33678c48d77c.png)
![6](https://user-images.githubusercontent.com/653230/163145233-c6e13781-23ef-4f98-8e01-84bcaa99bb87.png)
![5](https://user-images.githubusercontent.com/653230/163145249-0b398a2f-4b4a-4dd6-92c2-25dce7947300.png)

Hi
here is the error, also present on 1.7.8.3, so I guess also on 1.7.8.5
the error occurs when the first option of the ps_emailalerts module is active and when the quantities of a product are zero

**Comment by Maofree** [comment]
I've sent to @lmeyer1 the access to the real website. without that product.tpl the page get a 500 error

https://www.dangeloshop.it/volkswagen/603-mascherina-autoradio-2din-volkswagen-tiguan-touran-golf-passat-t5.html

![6](https://user-images.githubusercontent.com/653230/163147160-fda854dc-8d7c-4ccf-bf37-6219534aa86b.png)

I can reproduce this error with 10 addons themes, on different hosting

**Comment by lmeyer1** [comment]
@hibatallahAouadni
I tested on one of @maofree's websites. The issue is not related neither to prestashop core, nor to ps_emailalerts. On his website, there is a broken module (that I did not try to identify), that uses the hook `displayProductAdditionalInfo` and is called on this hook before `ps_emailalerts`.
Before calling `{include file='catalog/_partials/product-additional-info.tpl'}` in `themes/[theme-name]/templates/catalog/product.tpl`, the smarty variable `$product` is of class `PrestaShop\PrestaShop\Adapter\Presenter\Product\ProductLazyArray`.
Once in `modules/ps_emailalerts/views/templates/hook/product.tpl`, the varialbe `$product` has the wrong content.

I recommend you to close this issue as `out of scope`, since it is related to a third party module.

@maofree Please identify the module (by changing the order of the moudles in the `displayProductAdditionalInfo` hook. Then open an issue with the developer of that module.

**Comment by Maofree** [comment]
Hi
the problem is not due from a module, I've disabled all modules with the hook displayProductAdditionalInfo and the error continue to be present. if it were due to another module, the problem would also exist in normal conditions with quantity = 1

**Comment by lmeyer1** [comment]
Look at `/public_html/themes/PRS663/templates/catalog/_partials/product-additional-info.tpl`, I've added `<!--{get_class($product)}-->`. I added the same in `/public_html/themes/PRS663/modules/ps_emailalerts/views/templates/hook/product.tpl`.
Look at what we get:
![Capture d’écran 2022-04-13 150805](https://user-images.githubusercontent.com/7520695/163187042-51c6fee6-3747-4499-b3ba-ebb45cb8b6a3.png)
The content of the variable changed in between! I have no clue how this is possible. All I can say: this never happens on a clean install of PS.

**Comment by Maofree** [comment]
I might know why it is not possible to get the variables coming from the module instead of taking the generic theme variable $product?

**Comment by hibatallahAouadni** [comment]
Hello @maofree & @lmeyer1 

Thanks for your all feedbacks 🙏 
Closing the issue as it's not related to PS Core.

Thanks!
