### ISSUE TITLE
Autoload of modules are not charged in Legacy environment

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#27639]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

It's seems that /vendor/autoload.php is not loaded on Legacy environment, like a ModuleFrontController.
It's well loaded onto a FrontController as Product but no on the controller from the module itself.

### Expected behavior

File loaded in anytime.

### Steps to reproduce

Have a module that use Composer to make autoload
Add a ModuleFrontController in it and try to open it's URL if it's use a namespace class into it.

### PrestaShop version(s) where the bug happened

1.7.8.3

**Comment by HanaRebaiQA** [comment]
Hello @PrestaEdit 

Thanks for your report!
Could you please provide us the module that you use to make the autolaod to can reproduce your issue?

Thanks!

**Comment by matks** [comment]
➡️  a demo module would be very great ;)

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
