### ISSUE TITLE
SEO issue: No self-referencing hreflang and Conflicting hreflang and rel=canonical because of product attributes

### ISSUE THREAD

**Issue by rcoussy-16h33** [PrestaShop/PrestaShop#27638]
Hello, I'm using Semrush to enhance the SEO of my client's website. However I have many issues regarding hreflang and canonical URL: "No self-referencing hreflang" and "Conflicting hreflang and rel=canonical".

This is due to the fact that many products on the shop have attributes but the hreflang does not contains the id product attribute! This is really annoying...

For example see the screenshot below: 
<img width="1407" alt="Capture d’écran 2022-02-10 à 11 19 02" src="https://user-images.githubusercontent.com/81374618/153387346-e7ebf0ed-aecf-4bdd-ac74-2adc40a0e7d2.png">

You can test it with this tool: https://technicalseo.com/tools/hreflang/
Here is the result: 
<img width="1585" alt="Capture d’écran 2022-02-10 à 11 17 31" src="https://user-images.githubusercontent.com/81374618/153387372-fbcff3ca-5279-4ef6-a15f-52a51aeaae34.png">

How to get rid of this issue?

### Expected behavior

The hreflang and canonical URL should be configured well in order to prevent such issues.

### Steps to reproduce

1. Add multiple languages to your site.
2. Create a product with attributes.
3. Go to product page and select attributes in order to change the page URL.
4. Check the hreflang and canonical of the page, even if you reload the page.

### PrestaShop version(s) where the bug happened

1.7.7.7

**Comment by HanaRebaiQA** [comment]
Hello @rcoussy-16h33 

Thanks for your report!
It seems that your issue is related to this one [#26676](https://github.com/PrestaShop/PrestaShop/issues/26676) and as commented here https://github.com/PrestaShop/ps_rssfeed/issues/5#issuecomment-607298130 

Could you confirm that it's the same issue ?

Please check and feedback

Thanks!

**Comment by rcoussy-16h33** [comment]
Well yes, these issues are related.

A product with no attribute doesn't return any SEO issues because the hreflang and canonical are matching the product URL.

I think of two possible solutions:

1. remove the id_product_attribute from the product URL when attributes are selected.
2. add the id_product_attribute dynamically inside the hreflang and canonical <link> tags to match the product URL.

**Comment by HanaRebaiQA** [comment]
Thanks @rcoussy-16h33 for your feedback 

Seems it's a duplicate of https://github.com/PrestaShop/PrestaShop/issues/26676, this issue is closed.

**Comment by HanaRebaiQA** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/26676 !
