### ISSUE TITLE
When changing a theme , a "yaml" cache folder is created in wrong Prestashop folders

### ISSUE THREAD

**Issue by gennaris** [PrestaShop/PrestaShop#27635]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When using a child theme and launching a PHP script that is bootstrapping Prestashop core, 
a "yaml" folder with JSON/cache content is being created in the same directory of the script instead of the cache folder.

### Expected behavior

I'm expecting yaml folder is being kept in /var/cache/ folder

### Steps to reproduce

1. Install a child theme as described here  ( https://devdocs.prestashop.com/1.7/themes/reference/template-inheritance/parent-child-feature/ ) 

2/A. Open your website front office, you'll notice a "yaml" folder is being created in Prestashop root :
![2022-02-10_09-19-28](https://user-images.githubusercontent.com/43071148/153366142-491d1c87-9bb4-4271-9952-4c043cd9b288.png)

or : 

2/B. Launch a module cronjob (like gsitemap one) - You'll notice a "yaml" folder with cache content is being created into the module directory : 

![2022-02-10_09-22-15](https://user-images.githubusercontent.com/43071148/153366570-22e7ea56-cb83-4d74-bf7d-5bb8a999846c.png)

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4

**Comment by HanaRebaiQA** [comment]
Hello @gennaris 

Thanks for your report. 
ping @PrestaShop/prestashop-core-developers : Could you confirm if it's the expected behavior for this issue ?

Thanks!

**Comment by atomiix** [comment]
@HanaRebaiQA This doesn't seem to be the expected behavior. Those cache files should have been in `var/cache/{env}/yaml/` folder!

**Comment by gennaris** [comment]
Hello, I have checked a little and it looks like the issue was introduced here:  0481da4
For some reason path of the cache file is not correctly set

**Comment by HanaRebaiQA** [comment]
Thanks @atomiix  for your feedback!
I was unable to reproduce your issue using PS1783 version with php7.4
The `yaml` folder is not placed in Prestashop root. It's placed under the` admin-dev `folder!

https://user-images.githubusercontent.com/92912932/153443714-8481e11d-4c85-4854-9f46-bf2106ca1c41.mp4

Please check again and feedback!

Thanks!

**Comment by gennaris** [comment]
Hi @HanaRebaiQA,
just enabling the child theme will have no effect in reproducing the issue.

After that you'll have to visit the front office at least once and / or launch a script 
that is bootstrapping Prestashop core as described in my test cases 2A / 2B.

**Comment by khouloudbelguith** [comment]
Hi @gennaris,

I tried with PS1778., the `yaml` folder is well created when changing the theme & going to FO, but the path of this folder is different.
It is in the same path of the folder PrestaShop
I attached a screen record

https://user-images.githubusercontent.com/16067358/153584827-ebbb45ac-2499-4160-9e13-83bf3922c9ed.mp4


With PS1783, the `yaml` folder is well created when changing the theme & going to FO, but the path is under the PrestaShop folder.
I attached a screen record

https://user-images.githubusercontent.com/16067358/153584964-182169c7-25e6-4da7-819b-13efddeb97ea.mp4

so I can confirm that this behavior is indeed a bug.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks!

**Comment by micka-fdz** [comment]
Hi. Any news here?

This bug is really boring when `yaml` folder is permanently created inside module folder under git versioning...

**Comment by micka-fdz** [comment]
It seems that `yaml` folder is sometimes created inside `admin-dev` folder.

**Comment by micka-fdz** [comment]
Hi @Progi1984 @matks, any idea?

> Hello, I have checked a little and it looks like the issue was introduced here: https://github.com/PrestaShop/PrestaShop/commit/0481da45421a4f5d16025b451b8b4be5a3c65585
> For some reason path of the cache file is not correctly set

It seems you both worked on this PR.

**Comment by matks** [comment]
@micka-fdz If the issue was introduced by this commit, this is an unwanted side-effect. Looking at the code in https://github.com/PrestaShop/PrestaShop/pull/19231 I see nothing that could create that but maybe a behavior unknown to us has this side effect

**Comment by ComonSoft** [comment]
We reproduced this issue, with a cron module file. It seem that following code at the begining cause it:

```
include dirname(__FILE__).'/../../config/config.inc.php';
include dirname(__FILE__) . '/../../init.php';
```

**Comment by gennaris** [comment]
@ComonSoft the issue had already been explored and fixed, just apply the PR #28267

**Comment by ComonSoft** [comment]
Thanks @gennaris

**Comment by arafatx** [comment]
Since this issue has been fixed, can I delete the yaml folder at the root location?

**Comment by PrestaEdit** [comment]
Hi @khouloudbelguith ,

Could you say me why this issue was not added as a regression ? If I understand well, it's a bug introduce on a minor version, isn't it ?

**Comment by khouloudbelguith** [comment]
Hello @PrestaEdit,

Yes, it is not a regression.
The issue is reproduced with PS1778 and PS1783 as commented here: https://github.com/PrestaShop/PrestaShop/issues/27635#issuecomment-1036117142.
That's why it is not a regression.

Thanks!

**Comment by PrestaEdit** [comment]
Hi @khouloudbelguith,

And thanks for the answer.

So, if a bug is introduced inside a patch version (1.7.7.x) of the previous minor version (1.7.7), we need to wait until the next major and not the first minor, at least (not talking about patch version, there) ?
