### ISSUE TITLE
Tax surcharge not calculated if the zip code has a space before the number

### ISSUE THREAD

**Issue by kodarco** [PrestaShop/PrestaShop#27637]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If the zip code has a space before the number in the customer address, the surcharge won't be calculated, it falls back to only base tax.

See the invoice below, customer zip code was 33014 and that zip is defined by the tax rules, see below, but the number 33014 has a space before it and the surcharge is not combined with the base tax.

[IN045750.pdf](https://github.com/PrestaShop/PrestaShop/files/8040064/IN045750.pdf)
![Capture](https://user-images.githubusercontent.com/43558067/153384620-f1749ef5-9ba4-4d6e-99ad-a7ed3087ee53.JPG)

### Expected behavior

There should be a check for spaces and unknown characters either during the address addition or before the zip is used for tax calculation.

### Steps to reproduce
>Edited by Khouloud

1. Create a tax = 6% / create a tax =1%
2. Create a tax rule combine 6% & 1%
3. ![image](https://user-images.githubusercontent.com/16067358/153631470-6b4e2679-e597-4e39-a9e1-2d783dc98b04.png)
4. Create a product using this tax rule
5. Go to FO > Add this product to cart & process to checkout
6. In the address step: Add space in your zip code field before the number when adding or editing your address as a customer
7. Place order
8. generate an invoice for this order
9. See taxes 

------------------------

1. Add a tax rule for surcharge for your zip code
2. Add space in your zip code field before the number when adding or editing your address as a customer
3. Buy something, go through checkout, check your invoice for tax calculation

### PrestaShop version(s) where the bug happened

1.7.6.0

### PHP version(s) where the bug happened

7.2.34

**Comment by HanaRebaiQA** [comment]
Hello @kodarco 

Could you please provide us more information and clarification about the steps that you mentionned to reproduce your issue ?

Thank you!

**Comment by kodarco** [comment]
We have a tax rule for Florida at 6% - that's base tax, then we have rules for the tax surcharge for each zip code range, see attached.
The customer's zip code is 33014 which would trigger this rule and surcharge of 1% would be added to the 6% base tax. But the customer had a space before the number 33014 in his address so the tax rule for the surcharge didn't apply. System should not allow customer to enter space in the zip code field before the number.

You can reproduce the issue if you create a tax rule for a specific zip code, choose combine to have it added to a base tax (another tax rule), then create a customer account, enter the address with the space before the zip code, try to buy something and finish checkout. The space should prevent tax rule for the surcharge to be triggered.

![Capture](https://user-images.githubusercontent.com/43558067/153470798-8c317bf2-8e91-4fac-9f61-2c8cabf76d39.JPG)

**Comment by khouloudbelguith** [comment]
Hi @kodarco,

I have a red alert when creating a tax rule with this zip code: 33010 - 33018.
I attached a screen record

https://user-images.githubusercontent.com/16067358/153620681-9605db7b-5336-481c-b2d9-03f2b2644119.mp4

Thanks!

**Comment by kodarco** [comment]
> 

There should not be spaces between - when creating the rule. It needs to be 33010-33018.

**Comment by khouloudbelguith** [comment]
@kodarco, thanks for your feedback.
I did not manage to reproduce the issue with PS1783.
I used the same address in your invoice attached

https://user-images.githubusercontent.com/16067358/153631268-6509b3b8-be86-4179-908e-173eb7341769.mp4

Did I miss something?

Thanks!

**Comment by kodarco** [comment]
Then it must be fixed in newer versions. In 1.7.6.0. you can enter space before the zip code and save the address like that.
