### ISSUE TITLE
Product V2 - Images are not well displayed when we have more than 7 imags

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27640]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the Catalog > Products > Edit Product V2, when we try to add a lot of images, they are not well displayed
![image](https://user-images.githubusercontent.com/16067358/153407213-fa5cd6f0-420b-48dc-8865-06e5d464e3ed.png)

### Steps to reproduce

1. Enable Experimental product page
2. Go to Catalog > Products > Edit Product V2
3. Add a lot of images (8 images)
![image](https://user-images.githubusercontent.com/16067358/153407213-fa5cd6f0-420b-48dc-8865-06e5d464e3ed.png)
5. Try to resize the window
6. See error
![image](https://user-images.githubusercontent.com/16067358/153407271-91999d0a-a897-4c18-ac86-54c36502b04e.png)

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4

**Comment by Progi1984** [comment]
Ping @NeOMakinG :wave:

**Comment by margud** [comment]
This happens because display: flex is added. If i remove it then this is how it looks. Is this how it should look like?
![image](https://user-images.githubusercontent.com/51944825/188860484-96af20d0-1981-4fcc-bf33-4a02471982bf.png)

**Comment by NeOMakinG** [comment]
> This happens because display: flex is added. If i remove it then this is how it looks. Is this how it should look like? ![image](https://user-images.githubusercontent.com/51944825/188860484-96af20d0-1981-4fcc-bf33-4a02471982bf.png)

Yeah this is how it should look, but be careful about the behavior when you select an image

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29574
