### ISSUE TITLE
Subtotal of Shipping and Products in order-confirmation-table.tpl with and without tax

### ISSUE THREAD

**Issue by netzgestaltung** [PrestaShop/PrestaShop#27652]
Hi there,

today i inspected the variables of the template file `order-confirmation-table.tpl` from classic theme. 

The file is included twice:
1. From the payment step at the order page 
2. From the order-confirmation page after purchase

it gets the variables added for totals, subtotals and products but the variables differ from inside out. The Products Object is completely differtent and the keys are named differently (exept for those, classic theme uses default).

to get these prices side by side some simple adoptions would make them accessible.

is there a specific reason why not both values are available as variables for subtotals? including and excluding taxes?

Order-Page Payment Step:
**Current solution**
```
{if $subtotal.type === 'shipping'}
    {assign var='subtotal_value_exc' value=Context::getContext()->cart->getOrderTotal(false, Cart::ONLY_SHIPPING) }
{elseif $subtotal.type === 'products'}
    {assign var='subtotal_value_exc' value=Context::getContext()->cart->getOrderTotal(false, Cart::ONLY_PRODUCTS) }
{/if}
```

Order-Confirmation Page:
It would be a two-liner at https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Presenter/Order/OrderSubtotalLazyArray.php#L140

to add these values
```return [
                // is allready there
                'type' => 'shipping',
                'label' => $this->translator->trans('Shipping and handling', [], 'Shop.Theme.Checkout'),
                'amount' => $shippingCost,
                'value' => $shippingCost != 0 ? $this->priceFormatter->format(
                    $shippingCost,
                    Currency::getCurrencyInstance((int) $this->order->id_currency)
                )
                    : $this->translator->trans('Free', [], 'Shop.Theme.Checkout'),

                // is missing
                'amount_excl_tax' => $this->order->total_shipping_tax_excl,
                'amount_incl_tax' => $this->order->total_shipping_tax_incl,
            ];
```

Then it would be possible to write in [order-confirmation-table.tpl](https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/templates/checkout/_partials/order-confirmation-table.tpl#L110):
```
{assign var='subtotal_value_exc_format' value=Context::getContext()->currentLocale->formatPrice($subtotal.amount_excl_tax, Context::getContext()->currency->iso_code) }
{$subtotal_value_exc_format}
```
This also applies to products!

But it looks like impossible to get that variable out of the system. How can i override that file? is that possible for "/scr/Adapter" paths? (I tried allready but does not activate somehow)

Also i could imagine to get the variables like so:
```return [
                // is allready there
                'type' => 'shipping',
                'label' => $this->translator->trans('Shipping and handling', [], 'Shop.Theme.Checkout'),
                'amount' => $shippingCost,
                'value' => $shippingCost != 0 ? $this->priceFormatter->format(
                    $shippingCost,
                    Currency::getCurrencyInstance((int) $this->order->id_currency)
                )
                    : $this->translator->trans('Free', [], 'Shop.Theme.Checkout'),

                // handy variables for theme developers:
                'amount_excl_tax' => $this->order->total_shipping_tax_excl,
                'amount_incl_tax' => $this->order->total_shipping_tax_incl,
                'value_excl_tax' => $shippingCost != 0 ? $this->priceFormatter->format(
                    $this->order->total_shipping_tax_excl,
                    Currency::getCurrencyInstance((int) $this->order->id_currency)
                )
                    : $this->translator->trans('Free', [], 'Shop.Theme.Checkout'),
                'value_incl_tax' => $shippingCost != 0 ? $this->priceFormatter->format(
                    $this->order->total_shipping_tax_incl,
                    Currency::getCurrencyInstance((int) $this->order->id_currency)
                )
                    : $this->translator->trans('Free', [], 'Shop.Theme.Checkout'),
            ];
```

you also can comment my latest workaround:
```
            {if $subtotal.type === 'shipping'}
              {assign var='shipping_data' value=$order.details->getShipping() }
              {assign var='subtotal_value_exc' value=$shipping_data[0].shipping_cost_tax_excl }
            {/if}
```
now only the products subtotals are missing...

// some times later...
**Finaly i ended up overwriting** the original file it self so i can use that values.

_Originally posted by @netzgestaltung in https://github.com/PrestaShop/PrestaShop/issues/12743#issuecomment-1036408651_

**Comment by hibatallahAouadni** [comment]
Hello @netzgestaltung 

Thanks for detailed report and your PR :rocket: but could you please edit your issue description **following the template to submit a complete bug report**. Cause there is some missing informations that I need to reproduce the issue and work on it (like PrestaShop version, PHP version, steps to reproduce, ...).

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to ping me after updating your issue desciption, we will be glad to investigate it.

Thanks!
