### ISSUE TITLE
Gift is not removed from cart when changing customer group

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#27650]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When changing customer group and refreshing cart, gifts are added, but not removed.

### Steps to reproduce

**Preparation**
1. Create customer group ID 4.
2. Create a new customer, put him to group 4, set default group 4.
3. Create a cart rule that will apply automatically, cart rule will give a free gift, set group restriction only to 1, 2, 3.

**Actual bug**
1. Log in as the customer you created.
2. Add something to cart and go to cart.
3. Now, go edit that customer in BO, tick that he belongs to group 1.
4. Go back to cart, hit F5. Cart rule will be applied and gift added to cart.
5. Go back to edit customer, un-tick group 1, save.
6. Go back to cart, hit F5. Gift is not removed from cart.
_(7. It's removed when you +- the quantity on your product.)_

### PrestaShop version(s) where the bug happened

1.7.6.2

### PHP version(s) where the bug happened

7.2

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #19393
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #19393
