### ISSUE TITLE
No details in order confirmation email

### ISSUE THREAD

**Issue by Gozylatech** [PrestaShop/PrestaShop#27658]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello, I have an issue with the order confirmation email. The order details no longer appear. I tried to load the order_conf_cart_rules and order_conf_product_list txt and tpl files but nothing changes.
![erreuremail](https://user-images.githubusercontent.com/98805639/153758887-da569d10-281d-4bbc-a23d-57f3037ffbbd.jpg)

### Expected behavior

All data must be indicated

### Steps to reproduce

1. Create new order
2. Open order confirmation email
3. See error

### PrestaShop version(s) where the bug happened

1.6.1.24

### PHP version(s) where the bug happened

7.0

**Comment by Hlavtox** [comment]
Hello @Gozylatech, Prestashop 1.6 is looong gone and not supported anymore, but...

I think this bug is caused by email address having a capital letter in it, this is fixed in latest versions of Prestashop. Can you check?

**Comment by Gozylatech** [comment]
Hello, thank you for your answer. I just checked but the address doesn't have a capital letter.

**Comment by hibatallahAouadni** [comment]
Hello @Gozylatech 

PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).

Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

PS: thanks @Hlavtox for your quick reply :rocket: 

Thank you
