### ISSUE TITLE
ISBN validator should allow X as a last char

### ISSUE THREAD

**Issue by jkalke** [PrestaShop/PrestaShop#27659]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

PrestaShop do not allow ISBN to have X as last char.
Such ISBN's are valid (example: 83-88945-22-X)
https://www.isbn-check.de/checkisbn.pl?isbn=83-88945-22-X&submit=test&lang=en
In definition: https://en.wikipedia.org/wiki/International_Standard_Book_Number for ISBN-10 X is for 10 for checksum control.

Probably classes->Validate.php->isIsbn regexp to be adjusted only.

### Expected behavior

ISBN should allow X as last char

### Steps to reproduce

1. Go to Products -> Add new Product
2. Go to options, add a valid ISBN with X at the end, e.g. 83-88945-22-X
3. PrestaShop will not allow to create product with such a ISBN

### PrestaShop version(s) where the bug happened

1.7.8.3

**Comment by hibatallahAouadni** [comment]
Hello @jkalke 

That's the expected behvior cause in ISBN field only numbers are accepted as mentioned in the specs:

> - **ISBN:** Varchar field but only numbers are accepted. It should have maximum 32 characters. If you try to enter more than 32 chars, an error message should be displayed under the field: “This value is not valid.” If you enter anything other than numbers and save an error is displayed under the field “This value is not valid.”

See the the [specs](https://github.com/PrestaShop/prestashop-specs/blob/master/content/1.7/spec-templates/technical-characteristics-template.md#options-tab-).
Closing the issue as it's not a bug.

Thanks!

**Comment by jkalke** [comment]
@hibatallahAouadni should I then report bug to specs ? How to do so?
I've provided you an example that ISBN with X at the end is valid ISBN.
The issue is then with spec in first place and then with the implementation.

**Comment by ghost** [comment]
Hello @hibatallahAouadni the specifications are not good

I am woking on a new REGEX to allow X only at the end 

```
    /**
     * Check for ISBN.
     *
     * @param string $isbn validate
     *
     * @return bool Validity is ok or not
     */
    public static function isIsbn($isbn)
    {
        return !$isbn || preg_match('/^[0-9][0-9-]*?[0-9X]$/i', $isbn);
    }
```

X it's for the number 10 so we need to allow X at the end;  i think you can re open the issue.

It's in french but : 

_X est utilisé en remplacement de la valeur 10 lorsque le digit de contrôle vaux 10 et ceci afin de conserver le même nombre de chiffres dans tous les codes._

Thomas

**Comment by hibatallahAouadni** [comment]
Hello everyone,

Let's ping the Product Team to check with them if we could update the specs :wink: 
Ping @PrestaShop/product-team wdyt of @okom3pom [comment](https://github.com/PrestaShop/PrestaShop/issues/27659#issuecomment-1039006932) above?

Thanks in advance :pray:

**Comment by hibatallahAouadni** [comment]
Hello everyone,

As discusses with @MatShir if the specs don't match the bug report, it could mean that it's a functional change, therefore a feature. So, the Product Team will take it into consideration for future developments. 

Thank you
