### ISSUE TITLE
unable to remove thumbnail from menu

### ISSUE THREAD

**Issue by RicRey1988** [PrestaShop/PrestaShop#27661]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

when one enters a category, and modifies a category and wishes to eliminate the "menu thumbnail" it seems to be eliminated but if we click on "modify" again the menu thumbnail is still there.

![image](https://user-images.githubusercontent.com/44790517/153794035-11597624-9221-4de4-8f45-f3520b0fef5a.png)

### Expected behavior

I expected it to be removed as wanted.

### Steps to reproduce

1. We go to the backoffice and select "Catalogue"
2. We click on "Categories"
3. We click on modify category.

![image](https://user-images.githubusercontent.com/44790517/153794217-524e4fe5-f8d3-44e8-a2cc-12f20c0a90e4.png)

4. We look for "menu thumbnail" and we click on delete.

![image](https://user-images.githubusercontent.com/44790517/153794353-e6678e26-af74-4a08-9412-39d4d0f9dba8.png)

5. Let's confirm that it has been eliminated by entering "modify" the selected category again and verify that it has not been eliminated.

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Hello @RicRey1988 

It seems you're having an issue with the cache:

![image](https://user-images.githubusercontent.com/23308427/153832848-faae6b0d-2e30-4b12-b64d-3710deddd579.png)

So, could you please apply these modifications (in the attached screenshot below) to clear all smarty cache:

![image](https://user-images.githubusercontent.com/23308427/153832587-3851dda4-741b-461b-b6e6-b44b9cff9150.png)

Then, about your issue, I didn't manage to reproduce with PS1783, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/153832558-f5665a34-e9be-43bd-9612-debf871287a7.mp4

After clicking on delete the image, did you click on Save button?
If not try to click on it and then check if you still encounter the issue.
If you still encounter it, please enable the debug mode and open your console to see the displayed error :pray: 

Please check and feedback.
Thanks!

**Comment by RicRey1988** [comment]
in your video you are deleting the cover image and you delete everything, I want to only delete the menu image...

But apparently clearing the cache as you told me solved this problem, thank you very much.

**Comment by hibatallahAouadni** [comment]
Hello @RicRey1988 

> in your video you are deleting the cover image and you delete everything, I want to only delete the menu image...

Yep, you're right :sweat_smile: So, I tried to delete the menu thumbnail image and it was deleted successfully:

https://user-images.githubusercontent.com/23308427/153871532-c6b35801-c180-4b18-9f09-4dfdc59f6ed0.mp4

Please check and feedback.
Thanks!

**Comment by RicRey1988** [comment]
Thank you for your assistance, it was very useful, how can I close this case?

**Comment by hibatallahAouadni** [comment]
You already did :tada: and thanks for your feedback.
