### ISSUE TITLE
Add support for AMP pages in Ps 8.0.0

### ISSUE THREAD

**Issue by onlinedigitaltrade** [PrestaShop/PrestaShop#27672]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Currently, prestashop doesn't support AMP pages. Take a look at this snippet: "Google has said that “AMP is a natural fit for e-commerce because AMP makes webpages fast, and fast pages help with purchase conversions.” Today, more and more websites like eBay have been implementing AMP support, and in a world where more and more customers are using mobile devices to shop, it is imperative to give them the best shopping experience possible.

### Describe the solution you'd like

Prestashop should have support for AMP pages and other modern technologies as part of the core if it wants to become a serious base for new and existing e-commerce sites.

### Alternatives you've considered

There are AMP modules on Prestashop Addons, however I would consider support for AMP pages necessary in today's world, just like support for webp images. Prestashop is becoming better with each update, so let's keep modernizing it.

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [x] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by Hlavtox** [comment]
Hi @onlinedigitaltrade, this was already discussed in https://github.com/PrestaShop/PrestaShop/issues/10093.

AMP is a technology of a past. :-)

**Comment by kpodemski** [comment]
I agree with @Hlavtox

**Comment by florine2623** [comment]
Hello @onlinedigitaltrade ,

Thanks for the suggestion. But it won't be implemented. You can see the comment from @NeOMakinG https://github.com/PrestaShop/PrestaShop/issues/10093#issuecomment-957220052
> I think we can close it honestly, AMP was originally designed to be used for news things, not for an e-commerce solution, it's not a priority at all

If you have other suggestion, feel free to open a new issue ! 

Thanks!
