### ISSUE TITLE
Problem displaying prices on the shop

### ISSUE THREAD

**Issue by alabaeye** [PrestaShop/PrestaShop#27678]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When users visit the store and he had an account with particular prices, they did not appear, he saw the overall price

### Expected behavior

I would like that when a user who has an account see his prices and not those overall

### Steps to reproduce

For this I modified the file "ProductController.php" and its function "initContent()", I duplicated this file in my "override" folder, and I show you below my changes:

Code added to the function :

```
public function initContent() {
        // Recovers the TTC price of the product.
        $_dPrixTTC = $this->product->getPrice(true, null, 2);
        $_strPrixTTC = Tools::displayPrice($_dPrixTTC);

        // Recovers the tax-free price of the product.
        $_dPrixHT = $this->product->getPrice(false, null, 2);
        $_strPrixHT = Tools::displayPrice($_dPrixHT);
        
        // Assigns the variables in the "product.tpl" template.
        $this->context->smarty->assign(array('prix_ttc' => $_strPrixTTC));
        $this->context->smarty->assign(array('prix_ht' => $_strPrixHT)); 
        
        parent::initContent();
}
```

### PrestaShop version(s) where the bug happened

1.7.6.9

### PHP version(s) where the bug happened

7.2.24

**Comment by florine2623** [comment]
Hello @alabaeye ,

I can't reproduce your issue in PS 1.7.6.9 nor later versions.

I have created a Specific price for the "Kids" group :
<img width="1184" alt="Screenshot 2022-02-15 at 13 56 17" src="https://user-images.githubusercontent.com/16019289/154066544-e6f809c7-4a06-4f5c-bc8e-76c6e7b94c02.png">

The customer account has "Kids" as default group :
<img width="861" alt="Screenshot 2022-02-15 at 13 57 49" src="https://user-images.githubusercontent.com/16019289/154066738-18db8758-b071-4081-9323-527077a04db0.png">

The price displayed on the product is correct ✅ :
<img width="616" alt="Screenshot 2022-02-15 at 13 57 07" src="https://user-images.githubusercontent.com/16019289/154066791-ad2e0cc0-4778-4d4c-bd12-d6230fce5412.png">

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

I will close your issue as it cannot be reproduced.
Thank you
