### ISSUE TITLE
Random Type error: Argument 3 passed to HookCore::callHookOn()

### ISSUE THREAD

**Issue by qualityangel** [PrestaShop/PrestaShop#27675]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I get random Type error: Argument 3 passed to HookCore::callHookOn() when i click on a product.
sometimes it is gone for a view minutes.

Error reporting only shows:

Type error: Argument 3 passed to HookCore::callHookOn() must be of the type array, null given, called in /var/www/vhosts/dthomeshopping.nl/httpdocs/classes/Hook.php on line 934

What i have done:

- Enable debug modus
- Disable overides
- Disable non native modules

Searching for the error log but show only error 500 

### Expected behavior

Just display the product page

### Steps to reproduce

Go to website, https://www.heylampie.nlm, click on a product.

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4.27

**Comment by florine2623** [comment]
Hello @qualityangel ,

I can't reproduce your issue on PS 1.7.8.3. The product page is displayed correctly.

Also your site can't be reached :
<img width="1149" alt="Screenshot 2022-02-15 at 12 25 31" src="https://user-images.githubusercontent.com/16019289/154052923-d6cf59c8-9d54-4324-8da9-ba93621663b0.png">

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by qualityangel** [comment]
Yea it must me heylampie.nl ;)

**Comment by qualityangel** [comment]
I got this with a fresh install also

**Comment by luigimassa** [comment]
From line ~ 900, fix it with this:
```php

.....
                //fix this error!
                if(is_array($hook_args)===false){
                    $hook_args = [$hook_args];
                }
                //--------
                $display = Hook::callHookOn($moduleInstance, $registeredHookName, $hook_args);
     .....           
```
