### ISSUE TITLE
Unneeded checks in ps_checkpayment module

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#27688]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

There are unneeded checks in ps_checkpayment module.

There is no need to check for any order status, unless there was an error, this should never happen. Even if a module sneaked in some different order status, it's not a reason not to show payment information on confirmation screen. 

Also, every order has a reference, no need to check for it.

### Describe the solution you'd like

Remove these checks and simplify the code.

PR: https://github.com/PrestaShop/ps_checkpayment/pull/57

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thank you for your suggestion. The Developer Team will take it into consideration for future developments. 
Thanks for your PR :rocket: 

Thank you

**Comment by matks** [comment]
Approved by dev 👍
