### ISSUE TITLE
BO - Module manager- Exception is displayed when profiling is active

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#27684]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Exception when going to the page module manager when profiling is active with PS 1.7.8.3.
The problem is not present with PS1.7.8.2.

![image](https://user-images.githubusercontent.com/89604350/154072403-7070db70-3f71-4c5c-85c7-389ee719cf13.png)

https://watch.screencastify.com/v/GutQkeeQg9DBdfqoxSSO

### Steps to reproduce

1. Enable profiling mode 
2. Go to module manager page
3. see error

>Edited1 by Khouloud

I found a lot of pages BO => exception after an **upgrade**
Orders / Invoices / Products / Categories/ View Brand / Edit a brand / View supplier / Edit supplier / Stocks page / Customers page / addresses / Module Manager / Module Catalog page / Edit a page / View category page / Edit category page / Edit link list / Payment / Payment preferences / Localisation / Translations / Order Settings / Customer Settings / Traffic & SEO / Edit an employee / Edit a profile / Edit a webservice Key / Position page
=> I checked 1782 => OK: no exception

> Edited2 by Khouloud

**Other steps to reproduce the same exception in all migrated pages with Fresh install PS1783 & PS1784build1**

1. Install 1784build with Arabic language (Prefix = sk in my case)
2. edit the file 1784/config/defines.in.php and change it from define('_PS_MODE_DEV_', false); to define('_PS_MODE_DEV_', true);
3. go to BO > Dashboard (Welcome module displayed) 
4. Click on Next ( التالي en arabe)
5. See exception
6. All migrated page: exception 
![image](https://user-images.githubusercontent.com/16067358/156215954-1f1a951b-9100-4cf1-b3c2-03af36bdea53.png)
8. If I disable debug mode => 
![image](https://user-images.githubusercontent.com/16067358/156215975-00b65bf7-446d-457d-b687-c6d4da8d65d2.png)
9. If I disable the welcome module => OK

I checked 1784 + php7.2 => NOK / 1784 + PHP7.1 => NOK / 1783 + php 7.1 => NOK / 1782 + php7.1 => OK / 1784+php7.4 => ok
1784build1+ php7.2 => NOK

https://user-images.githubusercontent.com/16067358/156216044-56c2940b-c29b-4482-9d75-4aac11153086.mp4

1782 + php7.1 => OK

https://user-images.githubusercontent.com/16067358/156216144-5556a78a-226e-4d39-b1c5-b147cf0374f1.mp4

>Edited3 by Hana

1. Install 1752 with Spanich language and France Country
2. Add new languages (Arabic, Italian etc)
3. Change the BO language to Italian 
4. Set the parameter (`_PS_DEBUG_PROFILING_, 'false')
5. Use the upgrade  with 1-Click Upgrade v 4.14
6. Go to BO > Dashboard (Welcome module displayed)
7. Click on `later` 
8. Preview all migrated page
9. See error > Exception is thrown 
![image](https://user-images.githubusercontent.com/92912932/158624638-0165a508-7eb3-4fc0-81d4-ed4ea4aa2e42.png)

php 7.2

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.3

**Comment by PrestaEdit** [comment]
Good luck with this :)

It will be not simple to solve, imho.

**Comment by PrestaEdit** [comment]
Ping @PierreRambaud

**Comment by prestamodule** [comment]
Same issue as https://github.com/PrestaShop/PrestaShop/issues/27603 since update to 1.7.8.3 (related to security patch) that we have on some module injecting content on the Product page in BO.
All customers updating to this 1.7.8.3 version have the issue

**Comment by smartdatasoft** [comment]
Hello, You need to handle the addslash or something for the header injection code in your  module.  This code break https://github.com/PrestaShop/PrestaShop/commit/d2807b0560d5ca2835c6a4774e183c182d903f1a so you need to update your module code.

**Comment by prestamodule** [comment]
> Hello, You need to handle the addslash or something for the header injection code in your module. This code break [d2807b0](https://github.com/PrestaShop/PrestaShop/commit/d2807b0560d5ca2835c6a4774e183c182d903f1a) so you need to update your module code.

Well, the addslashes is done by PrestaShop core itself, this code is introducing a real breaking change as it was working fine on 1.7.8.2 and all prior 1.7.x versions.
The new generated template file is not correctly escaped/generated..

**Comment by matks** [comment]
Hello everyone thank you for all the informations provided here.

As mentioned by @prestamodule it's possible that the security fix https://github.com/PrestaShop/PrestaShop/commit/d2807b0560d5ca2835c6a4774e183c182d903f1a introduces a backward incompatible change and consequences would be that some module, that do work as expected with 1.7.8.2, would not work with 1.7.8.3 because we added some more safety.

Unfortunately backward incompatible changes are sometimes needed in order to ensure the project safety 🔓 there was a confirmed vulnerability (reported as https://github.com/PrestaShop/PrestaShop/security/advisories/GHSA-mrq4-7ch7-2465 that was present and 1.7.8.2) and these changes were needed to fix it.

@PrestaEdit reported a possible workaround in https://github.com/PrestaShop/PrestaShop/issues/27603

If there is a usecase where it is impossible to adapt a module behavior so that it works with both 1.7.8.2 and 1.7.8.3 please report it so that we can analyze it. However unless there is a major drawback, I think we will not revert https://github.com/PrestaShop/PrestaShop/commit/d2807b0560d5ca2835c6a4774e183c182d903f1a because security is more important that backward compatibility. The loss of money and reputation caused by a hack is much more expensive and damaging that a module update.

**Comment by PrestaEdit** [comment]
The {strip} is a quick fix but not working all the time ; also the profiling (native feature) is down in the same way as this issue mention it.

**Comment by prestamodule** [comment]
Hi @matks

Unfortunately and just FYI, {strip} does not fix the issue for all cases.
We must implement an alternative way to display content to the BO, using AJAX for example, in order to bypass the escape of smarty output by twig.
I still think that this is an issue anyway.

**Comment by mrports** [comment]
>.......... However unless there is a major drawback, I think we will not revert [d2807b0](https://github.com/PrestaShop/PrestaShop/commit/d2807b0560d5ca2835c6a4774e183c182d903f1a) because security is more important that backward compatibility. The loss of money and reputation caused by a hack is much more expensive and damaging that a module update.

hi @matks 
i have 54 3rd party modules installed. which one you think i should update first??
note: most of those module have their customer support expired which mean i need to pay more than 2000 Euro in renewals to **maybe** get this problem solved
I think its a very major drawback that need to be fixed and very soon

**Comment by matks** [comment]
@mrports 
If you want, you can use PS 1.7.8.2 and your modules will work fine. But then you're vulnerable to security issue https://github.com/PrestaShop/PrestaShop/security/advisories/GHSA-mrq4-7ch7-2465 . You have to choose what is more important to you.

Also the code on your shop is yours. If you don't like https://github.com/PrestaShop/PrestaShop/commit/d2807b0560d5ca2835c6a4774e183c182d903f1a you can simply remove it from your shop. The code on your server belongs to you.

What we are discussing here is about what happens on this github repository for the project only. If you disagree with what the software becomes you can use an older version or customize it to suit your needs. That is the strength of open source, and that is something proprietary software does not allow you to do.

If someone is able to submit a solution that does provide the same level of security that https://github.com/PrestaShop/PrestaShop/commit/d2807b0560d5ca2835c6a4774e183c182d903f1a while allowing modules to inject any content inside BO, we'll be happy to explore it obviously. But as maintainers if we are to choose between security and backward compatibility it will always be security. Security is our first and utmost priority. No open source project can pretend itself to be serious if it does not prioritize security first.

**Comment by matks** [comment]
If someone can please provide a module example or snippet of code that demonstrates what happens wrong, that would be great to help to understand exactly what's happening. There is maybe a 3rd path where https://github.com/PrestaShop/PrestaShop/commit/d2807b0560d5ca2835c6a4774e183c182d903f1a can be kept and improved. But in order to analyze that, a sample usecase is needed.

**Comment by mrports** [comment]
@matks  @prestamodule 
so this is what happen when i want to edit a category for example:
from symfony:
**Exception**: https://gist.github.com/mrports/4ce2a4d7d8c4b33613f085153d18bd9f
**Logs:** request :Matched route "admin_categories_edit".
**Stack Trace**: https://gist.github.com/mrports/54684c9ca46fd541dc29630e72f26777

similar problem happen when i want to edit a CMS page
**logs:** request: Matched route "admin_cms_pages_edit".

**Comment by khouloudbelguith** [comment]
Hi,

I found a lot of pages BO => exception when profiling is enabled. after an upgrade from PS16124.

Orders / Invoices / Products / Categories/ View Brand / Edit a brand / View supplier / Edit supplier / Stocks page / Customers page / addresses / Module Manager / Module Catalog page / Edit a page / View category page / Edit category page / Edit link list / Payment / Payment preferences / Localisation / Translations / Order Settings / Customer Settings / Traffic & SEO / Edit an employee / Edit a profile / Edit a webservice Key / Position page
=> I checked 1782 => OK: no exception

After an upgrade from PS16124 => PS1782: OK no exception
After an upgrade from PS16124 => PS1783=> exception in a lot of pages listed
After an upgrade from PS16124 => 178x (1784build1) => exception in a lot of pages listed
Fresh install 178x(1784build1) => exception only in the module manager
Fresh install PS1783 => exception only in the module manager
Fresh install PS1782 => OK

Thanks!

**Comment by jolelievre** [comment]
I tried to reproduce this bug last week but didn't encounter any issue on any of the pages you mentioned
I think we need more details for this issue, unless I missed something To enable the profiling I modified this line
https://github.com/PrestaShop/PrestaShop/blob/44991dde9227f1fa05fb6889a79559600e944df1/config/defines.inc.php#L47

And changed the value to `true` are there other steps I may have missed to reproduce the bug (I tested on both 178x branch AND the build for 1.7.8.3)

**Comment by khouloudbelguith** [comment]
Hi @jolelievre,

Thanks for your feedback.
I updated my comment

>Edit

After an upgrade from PS16124 => PS1782: OK no exception
After an upgrade from PS16124 => PS1783=> exception in a lot of pages listed
After an upgrade from PS16124 => 178x (1784build1) => exception in a lot of pages listed
Fresh install 178x(1784build1) => exception only in the module manager
Fresh install PS1783 => exception only in the module manager
Fresh install PS1782 => OK

Thanks!

**Comment by matks** [comment]
@mrports @PrestaEdit @prestamodule please have a look at https://github.com/PrestaShop/PrestaShop/pull/27806 ;)

**Comment by khouloudbelguith** [comment]
Hi,

Other steps to reproduce the same exception in all migrated pages with Fresh install PS1783 & PS1784build1

1. Install 1784build with Arabic language (Prefix = sk in my case)
2. edit the file 1784/config/defines.in.php and change it from define('_PS_MODE_DEV_', false); to define('_PS_MODE_DEV_', true);
3. go to BO > Dashboard (Welcome module displayed) 
4. Click on Next ( التالي en arabe)
5. See exception
6. All migrated page: exception 
![image](https://user-images.githubusercontent.com/16067358/156215954-1f1a951b-9100-4cf1-b3c2-03af36bdea53.png)
8. If I disable debug mode => 
![image](https://user-images.githubusercontent.com/16067358/156215975-00b65bf7-446d-457d-b687-c6d4da8d65d2.png)
9. If I disable the welcome module => OK

I checked 1784 + php7.2 => NOK / 1784 + PHP7.1 => NOK / 1783 + php 7.1 => NOK / 1782 + php7.1 => OK / 1784+php7.4 => ok
1784build1+ php7.2 => NOK

https://user-images.githubusercontent.com/16067358/156216044-56c2940b-c29b-4482-9d75-4aac11153086.mp4

1782 + php7.1 => OK

https://user-images.githubusercontent.com/16067358/156216144-5556a78a-226e-4d39-b1c5-b147cf0374f1.mp4

Thanks!

**Comment by HanaRebaiQA** [comment]
Hello,

I found the same exception using these steps after an upgrade from PS1752 to PS1785 : 

1. Install 1752 with Spanich language and France Country
2. Add new languages (Arabic, Italian etc)
3. Change the BO language to Italian 
4. Set the parameter (`_PS_DEBUG_PROFILING_, 'false')
5. Use the upgrade  with 1-Click Upgrade v 4.14
6. Go to BO > Dashboard (Welcome module displayed)
7. Click on `later` 
8. Preview all migrated page
9. See error > Exception is thrown 
![image](https://user-images.githubusercontent.com/92912932/158624638-0165a508-7eb3-4fc0-81d4-ed4ea4aa2e42.png)

Thanks!

**Comment by mrports** [comment]
the problem has been solved for some cases but there is many cases where the problem is still there take this as an example when i click to open a category in the back end then i get this error and i get the same error where i click on a product inside an order.
i get the same error aswell when i want to edit some products.
![category  error](https://user-images.githubusercontent.com/53506897/158798008-e69bf1bd-ef0d-4d0c-bed4-d0605ed41d66.png)

**Comment by matks** [comment]
As far as our knowledge goes, this problem is fixed by https://github.com/PrestaShop/PrestaShop/pull/27806 but I think the bug report might actually represent a global observable behavior that can be caused my multiple issues. So maybe not all issues are fixed. If someone finds an issue that is not fixed by https://github.com/PrestaShop/PrestaShop/pull/27806 please open another bug report it will be easier to track.
