### ISSUE TITLE
Order details issue

### ISSUE THREAD

**Issue by alabaeye** [PrestaShop/PrestaShop#27681]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On the details page of an order, the button "edit" in the category shipping costs, did not work at all, impossible to modify the carrier

### Expected behavior

I wanted to change the carrier of the command following a change of group and impossible that the modal appeared, the problem came from JavaScript

### Steps to reproduce

So I was seeing the JavaScript error and I realized that a variable in the "OrderList.js" file of the module was not defined, which blocked all execution of the code.

So I have redefined this variable as below:

`let employeeHasAccess = false;`

And all the code to work as well as the "edit" button

### PrestaShop version(s) where the bug happened

1.7.6.9

### PHP version(s) where the bug happened

7.2.24

### If your bug is related to a module, specify its name and its version

customorderreferencenumber v1.7.0

**Comment by florine2623** [comment]
Hello @alabaeye ,

I can't reproduce your bug in PS 1.7.6.9 :
https://user-images.githubusercontent.com/16019289/154067934-d042198a-2bdc-4288-a894-026211062638.mov

It seems like your issue comes from an external module. So I suggest contacting directly the author of the module to get it fixed.

I will close your issue.
Thanks!

**Comment by alabaeye** [comment]
> Hello @alabaeye ,
> 
> I can't reproduce your bug in PS 1.7.6.9 : https://user-images.githubusercontent.com/16019289/154067934-d042198a-2bdc-4288-a894-026211062638.mov
> 
> It seems like your issue comes from an external module. So I suggest contacting directly the author of the module to get it fixed.
> 
> I will close your issue. Thanks!

Hello @florine2623,

I’ll contact the module creator 

Thank you so much!
