### ISSUE TITLE
Show by position not working in category with child category

### ISSUE THREAD

**Issue by WS-NL** [PrestaShop/PrestaShop#27686]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On frontoffice category page (example: https://myshop.com/jackets) the product sort order is not working when a product is assigned to a child category inside the category (jackets) 

So show by position inside category" does not work. Products are not sorted by position in this category then

it affects existing categorys only

when you created a new category it is working

### Expected behavior

Show correct order by position inside category

### Steps to reproduce

Test it out

### PrestaShop version(s) where the bug happened

1.7.8.3 / 1.7.8.3

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @Def2019,

I can't reproduce your issue in PS 1.7.8.x nor develop branch.

The categories in my product :
<img width="291" alt="Screenshot 2022-02-15 at 15 18 58" src="https://user-images.githubusercontent.com/16019289/154081223-2f58a7bd-5f84-4454-8c31-d7014c51fa29.png">
The position in the default category :
<img width="1207" alt="Screenshot 2022-02-15 at 15 21 39" src="https://user-images.githubusercontent.com/16019289/154081278-7a9ee769-76df-4d71-8022-f365ec23d6a5.png">
The position in the FO :
<img width="1115" alt="Screenshot 2022-02-15 at 15 22 47" src="https://user-images.githubusercontent.com/16019289/154081309-82928633-05a9-4e80-aa66-37639da93a21.png">

Can you specify the steps to reproduce so we can test out is it really is a bug or not !
Thanks!

**Comment by WS-NL** [comment]
Will make a video with all steps
should follow shortly

**Comment by WS-NL** [comment]
Please check url below

[Video](https://drive.google.com/file/d/1tOq1IfWqBukYM6JX8Ywo0jL4rgVi3Bfx/view?usp=sharing)

**Comment by hibatallahAouadni** [comment]
Hello @WS-NL 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a module problem.

https://user-images.githubusercontent.com/23308427/154491627-443ccec5-6efd-4a53-9728-9abc6ef68cb7.mp4

We will close this issue.

Thanks!

**Comment by WS-NL** [comment]
Your categorie do not have the parent categorie with sub categories inside like my video.
We tested this on a few different live environments and its all there.
