### ISSUE TITLE
Bad log message

### ISSUE THREAD

**Issue by glv-soledis** [PrestaShop/PrestaShop#27695]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

A log message in FrontController.php send "Cart cannot be loaded..." while the tests made to get there do not test this possibility.

### Expected behavior

Change the text of the log or really do the test.

### Steps to reproduce

Redo an order with the same cart.

### PrestaShop version(s) where the bug happened

All

**Comment by hibatallahAouadni** [comment]
Hello @glv-soledis 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by tlgsoledis** [comment]
[](https://user-images.githubusercontent.com/99792614/156778253-267f0871-9292-41bd-98eb-23dbdf60facf.png)[](https://user-images.githubusercontent.com/99792614/156778412-6695980c-ca90-4541-9580-6268b0ce3b3f.png)[](https://user-images.githubusercontent.com/99792614/156778610-89571d13-87a4-45d4-9dc9-2459b3dd43fa.png)Hello,
You will find below the steps to display the error messages in the backoffice.

    Have 2 tabs open on the "shopping cart ?action=show" page (with items)
    image

    Launch and complete the order on one of the tabs
    image

    Refresh the other tab still active on the old cart

    Go to the back-office in "Advanced settings --> Logs" and the following error message should appear
    image

**Comment by ghost** [comment]
Hello,
You will find below the steps to display the error messages in the backoffice.

1. Have 2 tabs open on the "shopping cart ?action=show" page (with items)
![image](https://user-images.githubusercontent.com/99792614/156778253-267f0871-9292-41bd-98eb-23dbdf60facf.png)

1. Launch and complete the order on one of the tabs
![image](https://user-images.githubusercontent.com/99792614/156778412-6695980c-ca90-4541-9580-6268b0ce3b3f.png)

1. Refresh the other tab still active on the old cart 

1. Go to the back-office in "Advanced settings --> Logs" and the following error message should appear 
![image](https://user-images.githubusercontent.com/99792614/156778610-89571d13-87a4-45d4-9dc9-2459b3dd43fa.png)

**Comment by hibatallahAouadni** [comment]
Duplicate of #9866
