### ISSUE TITLE
Repeat order and gift

### ISSUE THREAD

**Issue by pnshurba** [PrestaShop/PrestaShop#27696]
![Снимок2](https://user-images.githubusercontent.com/39360984/154283059-7c359ed3-2b43-46df-af6d-1aafce9d34a5.JPG)
![Снимок](https://user-images.githubusercontent.com/39360984/154283068-444970d9-ca86-4512-8c5b-6f8518251417.JPG)
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If you create a free gift rule in discounts for each order, it will add it correctly. However, if you select the re-order button from your personal account, then in the new order there will already be a gift by 1 unit more, that is, there are already 2 gift units, then each time +1. How to make a limit of 1 gift per order? The user himself can also change the number of gifts in the basket from 1 to infinity 5, 10, as much as he wants. I believe this is a bug that needs to be fixed. Tell me how to fix?

### Expected behavior

1 gift 1 order

### Steps to reproduce

If you create a free gift rule in discounts for each order, it will add it correctly. However, if you select the re-order button from your personal account, then in the new order there will already be a gift by 1 unit more, that is, there are already 2 gift units, then each time +1. How to make a limit of 1 gift per order? The user himself can also change the number of gifts in the basket from 1 to infinity 5, 10, as much as he wants. I believe this is a bug that needs to be fixed. Tell me how to fix?

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4.27

**Comment by hibatallahAouadni** [comment]
Hello @pnshurba 

I think you mean how to limit each gift by customer :wink: and here's how:

![image](https://user-images.githubusercontent.com/23308427/154298894-bb659aa2-115e-4772-bdfa-9966c2a25d06.png)

Then, if your customer try to reorder, he will not receive the gift again :wink: 
Closing the issue as it's not a bug.

Thanks!

**Comment by pnshurba** [comment]
No, I need 
1 gift 1 order or 1 gift 1 cart

**Comment by pnshurba** [comment]
> Hello @pnshurba
> 
> I think you mean how to limit each gift by customer 😉 and here's how:
> 
> ![image](https://user-images.githubusercontent.com/23308427/154298894-bb659aa2-115e-4772-bdfa-9966c2a25d06.png)
> 
> Then, if your customer try to reorder, he will not receive the gift again 😉 Closing the issue as it's not a bug.
> 
> Thanks!

No, I need
1 gift 1 order or 1 gift 1 cart
