### ISSUE TITLE
How to add or change Attribute type ?

### ISSUE THREAD

**Issue by papich06** [PrestaShop/PrestaShop#27701]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

hello,
how can i optimize my product page like this https://certideal.com/iphone-11-reconditionnes/iphone-11-256-go-mauve-5997

### Describe the solution you'd like

by default we have 3 choices add attribute : "dropdown list", "radio buttons" and "color or texture" how can i add attribute type to have the same like for refurbished https://certideal.com/iphone-11-reconditionnes/iphone-11-256-go-mauve-5997 

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @papich06 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you

**Comment by papich06** [comment]
Hello @hibatallahAouadni ,
this is a new feature for combinations 
https://doc.prestashop.com/display/PS17/Managing+Product+Attributes

By default, Prestashop only provides 3 types of attributes. How to add new ones and format them?
