### ISSUE TITLE
Deactivated attributes create a hyphen after product name in the order confirmation

### ISSUE THREAD

**Issue by webpresso-ch** [PrestaShop/PrestaShop#27709]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If you have deactivated attributes in the order confirmation mail to the customer after the product name comes a blank hyphen. 
This happens because of the changes coming from here => https://github.com/PrestaShop/PrestaShop/pull/25961/files
https://github.com/PrestaShop/PrestaShop/blob/7a4e6eab7f5a9bab4f1168eccc66091b4bc504a3/classes/Cart.php#L998
In the class PaymentModule->validateOrder() in line 450 is only checked if the variable 'attributes' is valid and not checked if empty.  https://github.com/PrestaShop/PrestaShop/blob/7a4e6eab7f5a9bab4f1168eccc66091b4bc504a3/classes/PaymentModule.php#L450 

### Expected behavior

The hyphen should only be displayed if an attribute is present.

### Steps to reproduce

1. Disable Combinations in back office under Advanced Parameters => performance
2. Go to front office put products in cart
3. Order the products 
4. Take a look in order_conf mail

### PrestaShop version(s) where the bug happened

1.7.8.1,1.7.8.2

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @webpresso-ch 

Could you please provide a screen record or a screenshot :pray: 
Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @webpresso-ch 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
