### ISSUE TITLE
Webservice image management still expose the store_icon but this seems no more used

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#27708]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The /api/images/general/store_icon is still available but this specific image seems to be removed from project.

### Steps to reproduce

See description.

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must complete the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by PrestaEdit** [comment]
Please, let see a dev about this. I've taken the form as needed. Thanks.

Or you ask me to change the description, but never close an issue as it, please.

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

All right :sweat_smile: so could please provide steps to reproduce and describe the expected behavior :pray: 
Ping me when you're done and I will reopen it :wink: 

Thanks!
