### ISSUE TITLE
Improvement Features

### ISSUE THREAD

**Issue by papich06** [PrestaShop/PrestaShop#27702]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

hello,
why is it complicated to add an image to a feature or make a feature group?

### Expected behavior

For computer products, we need to format the data sheet by grouping and displaying the key features such as the video part, connectivity, memories

check for example this product page
https://www.sfr.fr/apple-iphone12

### Steps to reproduce

create product page with different element for your product like this https://www.sfr.fr/apple-iphone12

### PrestaShop version(s) where the bug happened

1.7.7.0

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

Attribute type, features group, image for features

**Comment by hibatallahAouadni** [comment]
Hello @papich06 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by papich06** [comment]
Hello @hibatallahAouadni ,

Here too it is a new functionality for do we have to buy a new module to group the characteristics and design the technical sheet of a product?

see this plugins
https://addons.prestashop.com/fr/declinaisons-personnalisation/48405-groupes-de-caracteristiques.html
