### ISSUE TITLE
Backoffice category validation errors are generalized to single exception

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#27715]
### Describe the bug and add screenshots

When editing a category in backoffice, all validation errors are merged into a single exception and the merchant does not have a single clue what went wrong.

When you add special characters into link rewrite, you get shown this:
![develop](https://user-images.githubusercontent.com/6097524/154520305-0f9d56be-df07-4fb1-be14-47810ea1bb57.png)

### Expected behavior

This works correctly in Prestashop 1.6:
![16](https://user-images.githubusercontent.com/6097524/154520389-3c1f71dd-c5f2-4c89-b1e8-af6ff6768fe8.png)

### Steps to reproduce

1. Edit any category.
2. Put **linkščěčšěč** into link rewrite.
3. See error that doesn't give you any information what is wrong.

### PrestaShop version(s) where the bug happened

develop

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #15490. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #15490

**Comment by Hlavtox** [comment]
@hibatallahAouadni That issue does not really specify what is happening. The category edit page is hiding all validation messages.

I was migrating a 1.6 store yesterday and I was unable to edit one of the categories. It was just throwing the exception with no further information.

When I investigated, the real validation message from ObjectModel was that `$category->date_upd is invalid` - it really was `0000-00-00 00:00:00` in the database.
