### ISSUE TITLE
BO - HelperList: notice if specificConfirmDelete is set to false

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#27717]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In an HelperList with specificConfirmDelete = false, a php notice is displayed in debug mode
![image](https://user-images.githubusercontent.com/16720275/154533363-72afb92f-d9af-4e1d-ad0f-779fc8a6d9ef.png)

### Expected behavior

No notice

### Steps to reproduce

1. Choose an HelperList
2. set $this->specificConfirmDelete = false;
3. Load the corresponding Admin Controller in debug mode
4. See the notice

### PrestaShop version(s) where the bug happened

1.7.x, 8.0

**Comment by florine2623** [comment]
ping @PrestaShop/prestashop-core-developers ,

Could someone try to reproduce the issue ? It is too technical for me !
Thanks!

**Comment by kpodemski** [comment]
I can reproduce this error by adding:

`$helper->specificConfirmDelete = false;` to `controllers/admin/AdminCartsController::renderList`

**Comment by kpodemski** [comment]
cc @florine2623 :)

**Comment by matks** [comment]
Thank you @kpodemski I put the bug to `Ready` then
