### ISSUE TITLE
Gsitemap PHP message: PHP Notice:  Trying to access array offset on value

### ISSUE THREAD

**Issue by duongductuan** [PrestaShop/PrestaShop#27721]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When Generate Sitemap I get the following error warning on apache server 

AH01071: Got error 'PHP message: PHP Notice:  Trying to access array offset on value of type bool in /prestashop/modules/gsitemap/gsitemap.php on line 425PHP message: PHP Stack trace:PHP message: PHP

### Steps to reproduce

1. Go to gsitemap
2. Click Generate Sitemap

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

Gsitemap 4.20

**Comment by HanaRebaiQA** [comment]
Hello @duongductuan 

Thanks for your report!
I tried to reproduce your issue using **PS1783** with **php7.3** and **php7.4**. But, i was unable to reproduce it 

https://user-images.githubusercontent.com/92912932/154694437-df1c66dc-4b60-4280-9ed1-c9fb4c4bb50a.mp4

https://user-images.githubusercontent.com/92912932/154694585-016883b4-2156-4ebe-a22e-a33bc6e49f3a.mp4

Could you please check again? Waiting for your feedback!

Thank you!

**Comment by duongductuan** [comment]
https://user-images.githubusercontent.com/87248592/154907235-89755ed6-fa37-4f57-aff8-188ae90cca93.mp4

Hi @HanaRebaiQA 
Pls check video.

**Comment by duongductuan** [comment]
https://user-images.githubusercontent.com/87248592/154909375-353cae78-35ad-48a7-a4d1-92b32c9c9f40.mp4

Hi @HanaRebaiQA 
pls check Video
Thank You

**Comment by hibatallahAouadni** [comment]
Hello @duongductuan 

Have you encountered this problem with older versions of PrestaShop?
Besides this PHP error notice, have you encountered any other issues on FO or on BO?
Please check and feedback.

Thanks!

**Comment by duongductuan** [comment]
The older version I used before also had the same problem 1.7.7.8, Currently I only have the problem with Gsitemap module

**Comment by hibatallahAouadni** [comment]
Hello @duongductuan 

I didn't manage to reproduce the issue with PS1783, check my attached dev.log below:

[dev.log](https://github.com/PrestaShop/PrestaShop/files/8126087/dev.log)

Waiting for your feedback.
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @duongductuan 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
