### ISSUE TITLE
head_hreflang and html lang fix

### ISSUE THREAD

**Issue by mark-app** [PrestaShop/PrestaShop#27724]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

As an example: If I install the language Dutch and French for a Belgian merchant and set the default language to Dutch (nl), the html lang becomes nl-NL instead of nl-BE and the hreflang then become :

`<html lang="nl-NL">`

`<link rel="alternate" href= "https://mydomain.be/nl/" hreflang="nl-NL">`
`<link rel="alternate" href="https://mydomain.be/fr/" hreflang="fr-FR">`

### Expected behavior

It should be : 

`<html lang="nl-BE">`

`<link rel="alternate" href= "https://mydomain.be/nl/" hreflang="nl-BE">`
`<link rel="alternate" href="https://mydomain.be/fr/" hreflang="fr-BE">`

### Steps to reproduce

1. Setup a new PrestaShop with the language Dutch (nl)
2. Set the shop counry on Belguim (BE)
3. Install the French language
4. In your BO go to International => Localization => Advanced
5. Set Language identifier to nl and  Country identifier to be and click on Save
6. Check your FO html code

### PrestaShop version(s) where the bug happened

1.7.8

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

FrontController

**Comment by mark-app** [comment]
It can by fixed in the Frontcontroler and the template files where <html lang= is set.

In classes/controller/FrontController.php function public function getTemplateVarShop()

After 'lat' => Configuration::get('PS_STORES_CENTER_LAT'), add :

'locale' => strtolower(Configuration::get('PS_LOCALE_LANGUAGE')).'-'.strtoupper(Configuration::get('PS_LOCALE_COUNTRY')),

In classes/controller/FrontController.php function public function getAlternativeLangsUrl()

Replace:

$alternativeLangs[$lang['language_code']] = $this->sanitizeUrl($langUrl);

For:

$isoLang = strtolower($lang['iso_code']).'-'.strtoupper(Configuration::get('PS_LOCALE_COUNTRY'));
$alternativeLangs[$isoLang] = $this->sanitizeUrl($langUrl);


In template files  (themes/classic/templates/layouts/layout-both-columns.tpl) 
Replace :

`<html lang="{$language.locale}">`

For: 

`<html lang="{$shop.locale}">`

**Comment by HanaRebaiQA** [comment]
Hello @mark-app 

Thanks for your report!
I tried to reproduce your issue using your mentionned steps. But i have a different result.

```
<html lang="nl">
<link rel="alternate" href= "https://mydomain/nl/" hreflang="nl-nl">
<link rel="alternate" href="https://mydomain/fr/" hreflang="fr">
```
instead of what you have : 

```
<html lang="nl-NL">

<link rel="alternate" href= "https://mydomain.be/nl/" hreflang="nl-NL">
<link rel="alternate" href="https://mydomain.be/fr/" hreflang="fr-FR">
```
![image](https://user-images.githubusercontent.com/92912932/154674709-c196cb87-6058-4aab-9f45-05f1c7821152.png)

https://user-images.githubusercontent.com/92912932/154674384-32604875-c7e1-4f3e-8f0a-fe5922a6bea3.mp4



What do you think ?

Thanks!

**Comment by mark-app** [comment]
@HanaRebaiQA 

Your version should have:

```
<html lang="nl-BE">

<link rel="alternate" href= "https://mydomain.be/nl/" hreflang="nl-BE">
<link rel="alternate" href="https://mydomain.be/fr/" hreflang="fr-BE">

```

See this [link](https://developers.google.com/search/docs/advanced/crawling/localized-versions) for more info.

Tool to check hreflang. 
[https://dejanmarketing.com/flang/](https://dejanmarketing.com/flang/ )

**Comment by florine2623** [comment]
Hello @mark-app ,

I can't reproduce your issue. Here's what I have with PS 1.7.8.3 - PHP 7.4:
<img width="808" alt="Screenshot 2022-02-18 at 16 45 34" src="https://user-images.githubusercontent.com/16019289/154715036-6aaeec62-f1ba-458c-a423-0838fccf9925.png">
<img width="560" alt="Screenshot 2022-02-18 at 16 46 08" src="https://user-images.githubusercontent.com/16019289/154715058-0203058f-7ece-4c45-b290-83e85a9339c6.png">

Could you share a screen record of your shop ? (don't forget to hide your admin url)
Thanks!

**Comment by matks** [comment]
⚠️

**Comment by matks** [comment]
🔴

**Comment by matks** [comment]
🟠

**Comment by mark-app** [comment]
@florine2623 I fixed it already with my fix above in my webshop. So my urls are fine at the moment.

```
<link rel="canonical" href="https://www.********.be/nl/">
<link rel="alternate" hreflang="nl-BE" href="https://www.********.be/nl/">
<link rel="alternate" hreflang="fr-BE" href="https://www.********.be/fr/">
<link rel="alternate" hreflang="x-default" href="https://www.********.be/nl/">
```

**Comment by HanaRebaiQA** [comment]
Hello @mark-app 

Glad to know that your problem is solved. 
So, i'll close the issue. Don't hesitate to open new tickets when needed.
Thank you!

**Comment by mark-app** [comment]
@HanaRebaiQA No it's not solved in PrestaShop itself. Only in my customised version.
