### ISSUE TITLE
Ean-13 is not visible in the product details.

### ISSUE THREAD

**Issue by MiguePapel** [PrestaShop/PrestaShop#27727]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Specific product references are not visible when it comes to an article without combinations.

### Expected behavior

That the specific references are shown just as a product with combinations does.

### Steps to reproduce

1 Select product
2 Product details

### PrestaShop version(s) where the bug happened

1.7.8.3

**Comment by BenTen** [comment]
#15783 ?

**Comment by HanaRebaiQA** [comment]
Hello @MiguePapel 

Thanks for your report!
Could you please provide us more information about the steps to reproduce and some screen-shots/screen-record ? 
In which part did you encounter the issue, Back Office or Front office ?

Thank you!

**Comment by hibatallahAouadni** [comment]
Hello @MiguePapel

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #15783. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #15783

**Comment by hibatallahAouadni** [comment]
PS: @MiguePapel this issue has been fixed with the new next major version 8.0.0 :wink:

**Comment by BenTen** [comment]
Not me, I just replied to the author of the issue.

**Comment by MiguePapel** [comment]
> #15783 ?

Gracias

**Comment by hibatallahAouadni** [comment]
Sorry @BenTen :sweat_smile:
