### ISSUE TITLE
[Autoupgrade to develop] An exception is displayed in the SEO & URLs page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27734]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After an upgrade from a previous version to develop branch.
An exception is displayed on the SEO & URLs page
![image](https://user-images.githubusercontent.com/16067358/154733797-c6da65dc-744e-479b-88a3-308980c15e20.png)

### Steps to reproduce

1. Install PS1783
2. Install the module autoupgrade dev branch
3. Create a release from develop branch
4. Upgrade to develop branch
5. Go to BO > Shop Parameters > SEO & URLs page
6. See error

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

autoupgrade v4.14.0

**Comment by atomiix** [comment]
@khouloudbelguith I just tried to reproduce this issue and I haven't been able to. Can you try again? I think it has been resolved already

**Comment by Progi1984** [comment]
(@atomiix May be in `dev` branch)

**Comment by atomiix** [comment]
@Progi1984 what to you mean? I used the `dev` branch of the autoupgrade module and created a fresh build of PrestaShop from the `develop` branch.

**Comment by Progi1984** [comment]
Yes and @khouloudbelguith has the bug with `autoupgrade v4.14.0`.

**Comment by khouloudbelguith** [comment]
Hi @Progi1984, @atomiix,

I tried again with an upgrade from PS1778 to develop branch using the autoupgrade **dev** branch.
![image](https://user-images.githubusercontent.com/16067358/156380225-6c6a861e-14d8-4f28-a4db-a7974ac884fe.png)
![image](https://user-images.githubusercontent.com/16067358/156380278-8aa53bcd-2983-4628-a053-fc964d7de7be.png)

I will close the issue.
Thanks!
