### ISSUE TITLE
Multishop Category Default

### ISSUE THREAD

**Issue by tups** [PrestaShop/PrestaShop#27731]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the case of a Prestashop Multishop, with shared products, it is impossible to define a default store category per store

In "All shops" mode, if we save, then we keep only one default category:
![image](https://user-images.githubusercontent.com/868611/154709963-9bc557f6-0a21-4ea7-9a63-549acb05ef70.png)

Other bugs, also related to this issue:
- the BreadCrumb on the Front Office side, returns the category of the wrong store
- If we click on the category link, we also realize that the category is displayed, whereas it is not supposed to be accessible on this shop.
 

### Expected behavior

We should be able to define a default category for each shop.

Categories assigned to a store should not be accessible.

### Steps to reproduce

1. Create a Prestashop with two stores with shared stock
2. Create a category for each store
3. Create a product, assign it to the two shops, and to the two categories.
4. Try to put a default category for each store
5. On the detail of the product sheet on the Front Office side, in the store that does not have a default category, check the category link in the breadcrumb

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @tups ,

Is your issue similar to https://github.com/PrestaShop/PrestaShop/issues/22610 ?

Thanks!

**Comment by tups** [comment]
Hello,

Actually, I hadn't found this one. It's over a year old and still not resolved.

I proposed an early PR: #27732

**Comment by hibatallahAouadni** [comment]
Hello @tups 

Thanks for your PR :rocket: 
Could you please change the Fixed ticket to #22610 in your PR :wink: 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #22610. 
Please subscribe to the issue mentioned above.

Thanks!
