### ISSUE TITLE
[Autoupgrade to develop] An exception is displayed in the Module Catalog page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27733]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After an upgrade from a previous version to develop branch.
An exception is displayed on the Module Catalog page
![image](https://user-images.githubusercontent.com/16067358/154733102-73b378af-b18a-4f55-bc74-012d3fdbe6a5.png)

### Expected behavior

The module catalog menu should not be displayed after an upgrade to develop

### Steps to reproduce

1. Install PS1783
2. Install the module autoupgrade dev branch
3. Create a release from develop branch
4. Upgrade to develop branch
5. Go to BO > Module > Module catalog page
6. See error

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

autoupgrade v4.14.0

**Comment by atomiix** [comment]
This issue come from `ps_mbo` that try to use a file that has been removed in develop. I think the fix should come from `ps_mbo` rather than from the core ;)

**Comment by Progi1984** [comment]
Ping @intraordinaire & @sowbiba

**Comment by intraordinaire** [comment]
The `ps_mbo` module is also currently under a huge refacto, and this issue does not exist when using the `develop` branch on `PrestaShop`, and the `3.x` branch on `ps_mbo`.
But good to know, as we will check that the `autoupgrade` works correctly.

**Comment by Progi1984** [comment]
Thanks @intraordinaire. In this case, I close this issue.
