### ISSUE TITLE
Module ps_facetedsearch Prestashop 1.7.7.8

### ISSUE THREAD

**Issue by kelta** [PrestaShop/PrestaShop#27730]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The module has a bug in the search on subcategory with the same name reports blank page.
Practical example.
Category A with sub-category from 12 to 15 inches
Category B with sub-category from 12 to 15 inches.
From the frontend I select category has I see the respective subcategory from 12 to 15 inches but clicking I do not see results because the GET request obtain carries out a generic textual search.

### Steps to reproduce

1) Create this categories: Category A with two sub categories -> form 11.0 to 12.0; from 13.0 to 14.0
2)Create this categories: Category B with two sub categories -> form 11.0 to 12.0; from 13.0 to 14.0
3) Activate module  and check.

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

v3.7.1

**Comment by HanaRebaiQA** [comment]
Hello @kelta 

Thanks for your report!
Could you please provide us more information and some screen-shots/screen-record to can reproduce your issue?

Thank you!

**Comment by hibatallahAouadni** [comment]
Hello @kelta 

> 1.7.8.8

AFAIK we didn't release this version yet :sweat_smile: 
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.
