### ISSUE TITLE
Category filter for recommended modules list

### ISSUE THREAD

**Issue by sowbiba** [PrestaShop/PrestaShop#27747]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Go to Admin > Modules > Modules catalog, you'll have a list of recommended modules in different categories. In the top right corner, try to filter with a category in the dropdown, the items in the list don't change

![Capture d’écran de 2022-02-21 09-07-50](https://user-images.githubusercontent.com/7426640/154923204-42aa14cb-bbf3-4b5e-b453-ed6269c0bb44.png)

### Expected behavior

The items list must change depending on the category selected

### Steps to reproduce

1 - Go to Admin > Modules > Modules catalog

2 - Click on a **Product Page** or any other category in the categories filter

3 - See error > the filter doesn't work! The modules not matching this category must be removed from the list

### PrestaShop version(s) where the bug happened

1.7.8.3

**Comment by Progi1984** [comment]
Fixed by @sowbiba in #27748 & tested by @marwachelly
