### ISSUE TITLE
Can not create new product, or get a product without image throught web service API

### ISSUE THREAD

**Issue by lephuongbg** [PrestaShop/PrestaShop#27746]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On 1.7.8.3, Prestashop still can not create or get a product through web service if it doesn't have image.

This issue persists since at least 1.7.5 but the original issue was closed without any PR fixing it.
https://github.com/PrestaShop/PrestaShop/issues/15701

The only workaround that I found is to disable `E_NOTICE` on production with `error_reporting = E_ALL & ~E_STRICT & ~E_DEPRECATED & ~E_NOTICE`. But for development, it is inconvenient since we want to work on resolving E_NOTICE errors.

This is the error response when getting a product without image:

```
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<errors>
<error>
<code><![CDATA[5]]></code>
<message><![CDATA[[PHP Notice #8] Trying to access array offset on value of type bool (/var/www/html/classes/Product.php, line 7170)]]></message>
</error>
</errors>
</prestashop>
```

This is the error response when trying to create a new product:

```
{"products":[...],"errors":[{"code":5,"message":"[PHP Notice #8] Trying to access array offset on value of type bool (\/var\/www\/html\/classes\/Product.php, line 7170)"}]}
```

### Expected behavior

Prestashop's web service can create new product, and get product without image.

### Steps to reproduce

*Already described above*

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @lephuongbg 

Could you please provide clear and concise steps to reproduce the issue :pray: 
Cause with the provided infos, I didn't manage to reproduce the issue.
Waiting for your feedback.

Thanks!

**Comment by lephuongbg** [comment]
Hi @hibatallahAouadni 

Have you tried with `error_reporting = E_ALL & ~E_STRICT & ~E_DEPRECATED` (without `E_NOTICE`)?

**Comment by florine2623** [comment]
Hello @lephuongbg ,

Could you send a screen record of what you are doing please ?
I will try to reproduce it as soon as the steps to reproduce are clearer !

Thanks!

**Comment by ceer** [comment]
I fixed the `GET api/products?display=full`  this way:

```
@@ -7167,7 +7167,7 @@
     {
         $result = $this->getCover($this->id);
 
-        return $result['id_image'];
+        return $result['id_image'] ?? '';

     }
```

**Comment by hibatallahAouadni** [comment]
Hello @lephuongbg 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

PS: Thanks @ceer your solution, hope it helps @lephuongbg 

Thanks!

**Comment by fk-inspirit-tech** [comment]
Same problem here.

**Comment by rost9999** [comment]
The problem is not solved.

**Comment by AhmedBenZid** [comment]
Hello, you can fix the problem with a simple change in the page `Classes/Product.php` line 7170
 ```
{
         $result = $this->getCover($this->id);
         return $result['id_image'];
}
```
It will be like that
```
{
         $result = $this->getCover($this->id);
         if($result){
             return $result['id_image'];
         }
}
```

**Comment by matteolavaggi** [comment]
The problem is that PS 1.7.8 is NOT compatible with php7.4 . There is a lot on error "Trying to access array offset on value of type bool"

I realy dont know why ps 178 was signed compatible with php 7.4, this is not right. 

![image](https://user-images.githubusercontent.com/24798703/235672257-71c8e2d9-b28c-4587-8dc6-bf80cde3c228.png)

Now with the release of prestashop 8 this has remained the usual mess. There are thousands of functions that block php 7.4 with an error warning and are no longer fixed because you have gone ahead with prestashop 8. This development is not healthy, it is a continuous rush for new releases that leave the old ones behind full of bugs and not are compatible with the previous ones. In prestashop 1.7.8 all the code that is blocked by a php warning (frontend in debug mode and webservice NOT in debug mode) is unusable.
