### ISSUE TITLE
Error when installing some modules from addons

### ISSUE THREAD

**Issue by sowbiba** [PrestaShop/PrestaShop#27749]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I'm in the carriers list, some recommended delivery modules are listed below the list of installed carriers
Some of these modules can't be installed : like Chronopost
An error is displayed in a flash message
![Capture d’écran de 2022-02-21 09-09-21](https://user-images.githubusercontent.com/7426640/154923651-dac8079a-e123-4007-bdae-cbe002203501.png)
![Uploading Capture d’écran de 2022-02-21 09-09-26.png…]()

### Expected behavior

The modules listed must be installable

### Steps to reproduce

1 - Connect to addons marketplace

2 - Go to Admin > Delivery > Carriers. You'll see the list of recommended modules

3 - Click on "Install" of the Chronopost module

4 - You'll see a flash growl saying that the module can't be installed

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.3.33

**Comment by sowbiba** [comment]
For the Chronopost module, the install fails because this module requires php-soap extension

Note that the module fills a warning to say that the extension is needed. But warnings are not used in the module listing nor in the install
I don't have in mnd any real fix but we can :
- warn the client that this module has some not matched requirements, in the modules list ( a warning icon and a tooltip with messages ?)
- enrich the flash message to help the client. "Installation fails but we have no informations about it. Maybe you can have a clue with these requirements : list the warnings

**Comment by hibatallahAouadni** [comment]
This issue is related to #11388 (and #12123)

**Comment by hibatallahAouadni** [comment]
I reproduce the issue with PS1778, PS1780 and PS1783 (even without connecting to addons), and with all proposed modules:

![image](https://user-images.githubusercontent.com/23308427/154942410-43d29497-2e43-4748-b55d-a8843fb487d8.png)

**Comment by sowbiba** [comment]
The module install process doesn't add the error message to the right array

We have 

```
// Check for SOAP
        if (!extension_loaded('soap')) {
            $this->context->controller->errors[] = $this->l('The SOAP extension is not available or configured on
             the server ; The module will not work without this extension ! Please contact your host to activate it
              in your PHP installation.');

            return false;
        }
```

But the errors must be added to the `errors` array of the module itself
Doing
```
// Check for SOAP
        if (!extension_loaded('soap')) {
            $this->_errors[] = $this->l('The SOAP extension is not available or configured on
             the server ; The module will not work without this extension ! Please contact your host to activate it
              in your PHP installation.');

            return false;
        }
```
I now have the errors displayed in the growl
![Capture d’écran de 2022-02-21 11-47-00](https://user-images.githubusercontent.com/7426640/154950471-c91f1393-b39b-471a-8478-6fe6e45fbec8.png)

So it's up to the module editor to fix this

**Comment by sowbiba** [comment]
Note for QA : I tried to install it through 
- Admin > Delivery > Carriers
- Modules catalog
The message is well displayed if errors are in _errors array of the module

I install php7.3-soap, install the module, go to Modules manager, uninstall the module
The module can't be automatically reinstalled because it disapears from the list
