### ISSUE TITLE
All images on shop stop working due to missing rewrites

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#27757]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If your products do not have link rewrite and a name, all product images stop working and their URL looks like this: `http://example.com/33-home_default/.jpg`.

### Expected behavior

There should be a fallback if there is no rewrite.

### Steps to reproduce
>Edited by Khouloud

Steps to reproduce the issue 
Install Ps with English language & France country 

1. Create a product > upload an image & enable it
2. Don't click on the preview button & don't click on save again
3. Go to FO > Search this product & select french language 
4. See an error 
5. Same issue in the list page 

I attached a screen record

https://user-images.githubusercontent.com/16067358/155131003-f649f167-149d-4c28-be8b-098e611cfe0b.mp4

---------------------------------------------------------------------------------------

**UDPATE: I cannot reproduce it this way for a second time. :(**

1. Install Prestashop.
2. Add new language, enable it.
3. Go to front office and switch to this language.
4. See no images.

### PrestaShop version(s) where the bug happened

develop

**Comment by florine2623** [comment]
Hello @Hlavtox ,

Thanks for the report and the PR !

I have tried reproducing it, I can't.
I tested with the provided steps, I changed PHP versions, I tested in multistore. I still don't have the same behavior as yours. images are well displayed.

Maybe @khouloudbelguith will be able to find a way to reproduce it.
@khouloudbelguith let us know what should be done with the issue ^^

Thanks!

**Comment by Hlavtox** [comment]
Hello @florine2623, the situation persists on my localhost dev install, I don't know how it happened, but maybe a language addition failed somehow... Anyway - this could happen with failed imports etc. I just fixed it. 😄

![1](https://user-images.githubusercontent.com/6097524/155109477-bf6224ff-6723-4983-a6fc-f2ae52da40ab.png)
![2](https://user-images.githubusercontent.com/6097524/155109486-db5c447f-0d27-443b-a213-b7bc044abd5e.png)

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox, @florine2623,

I manage to reproduce this issue with 1778 & 1783 following these steps:
Install Ps with English language & France country 

1. Create a product > upload an image & enable it
2. Don't click on the preview button & don't click on save again
3. Go to FO > Search this product & select french language 
4. See an error 
5. Same issue in the list page 

I attached a screen record

https://user-images.githubusercontent.com/16067358/155131003-f649f167-149d-4c28-be8b-098e611cfe0b.mp4


@Hlavtox, can you please confirm these steps?

Thanks!

**Comment by Hlavtox** [comment]
@khouloudbelguith I think I got my PS to this situation by a different way, but at least you reproduced by one scenario! 😄

**Comment by khouloudbelguith** [comment]
@Hlavtox, thanks, I will edit the first comment.
