### ISSUE TITLE
Customer groups are not assigned properly when converting customer through front office

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#27753]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Customer groups stay assigned to Guest after converting customer through front office.

Discovered while working on https://github.com/PrestaShop/PrestaShop/pull/25353, will be fixed by this.

### Expected behavior

Customer should have proper groups set.

### Steps to reproduce

1. Clear cookies. Add anything to cart. Go to checkout.
2. Enter name, surname, email and continue. (no password)
3. Go check your new guest customer to backoffice. See that his group is **"Guest"**.
4. Now, two options:
  - Go back to checkout first step and fill password.
  - OR go to Sign in > create new account. Enter the same email and a password.
5. Now your guest is converted to regular customer.
6. However, if you check your customer in backoffice, he will still have the **"Guest"** group assigned. He should have **"Customer"** group.

### PrestaShop version(s) where the bug happened

develop

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thanks for reporting the issue and for your PR :superhero: 
I reproduce the issue with PS1778 and PS1783. I’ll add this to the debug backlog so that it’s fixed.

Thank you
