### ISSUE TITLE
The help field is not displayed when integer type is used to a form

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#27761]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The help field is not displayed when integer type is used to a form.

![Screenshot (3)](https://user-images.githubusercontent.com/5064590/155086412-1aa929dd-45d3-491f-93e9-0de0252a8c6c.png)

### Expected behavior

Help field need to be display

![Screenshot (2)](https://user-images.githubusercontent.com/5064590/155085954-2997d2b0-b3f4-48ad-8333-f4fd4d5fa9bc.png)

### Steps to reproduce

1) Enable B2B

2) Edit a customer

3) See Maximum number of payment days field.

### PrestaShop version(s) where the bug happened

8.0

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @okom3pom ,

Thanks for the report and the PR !
I have reproduce the issue and it is a regression since PS 1.7.6.9, so I can confirm that this behavior is indeed a bug.

Thank you

**Comment by ghost** [comment]
@florine2623  I need to target 1.7.8.X branch ?

**Comment by florine2623** [comment]
Yes please ^^
