### ISSUE TITLE
Complete the italian translations to ps_checkout module

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#27764]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi
can you complete the Italian translations of the ps_checkout module ?

![3](https://user-images.githubusercontent.com/653230/155104683-1a9d68d7-4f10-4126-9d0b-b87c2852a59a.png)
![7](https://user-images.githubusercontent.com/653230/155104691-25abcf75-ffee-489b-99f2-63465ead0b53.png)

thanks

### Steps to reproduce

1. go to check the translations of this module

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_checkout v2.17.0

**Comment by florine2623** [comment]
Hello @maofree ,

This doesn't concern the OS project of PrestaShop.
You need to contact the develop of the module, directly in the Help section of the module :
<img width="1205" alt="Screenshot 2022-02-22 at 10 55 37" src="https://user-images.githubusercontent.com/16019289/155108016-4b34db62-41da-4878-b784-049f9e0452ab.png">

i will close this issue.
Thanks!
