### ISSUE TITLE
Disable browser autocomplete for datepicker

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#27765]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Autocomplete suggestions hide date picker
![image](https://user-images.githubusercontent.com/16720275/155111115-777471f6-4967-455e-b995-9458f70fed1c.png)

### Steps to reproduce

- activate autofill on your browser (on by default)
- fill a date or date time and save
- fill another date and see the suggestion hidding the date picker

> Edited by Khouloud

1. Go to BO > Catalog > Discounts > Catalog Price rule
2. Add a new catalog price rule & set the datepicker
3. See error 

![image](https://user-images.githubusercontent.com/16067358/155697062-c1bac461-8558-45b9-8991-00ac14ca707a.png)

### PrestaShop version(s) where the bug happened

1.7, 8

### PHP version(s) where the bug happened

all

**Comment by florine2623** [comment]
Hello @jf-viguier ,

I can't reproduce your issue in the following forms in PS 1.7.8x and in develop branch :
- Order > Payment > Date
- Invoices > By date
- Catalog > Products > Specific Prices

Is there a form in particular that you use ? ^^

Thanks!

**Comment by kpodemski** [comment]
Hello @florine2623 

you won't be able to reproduce this issue on the clean installation, I think as long as the form doesn't have `autocomplete="off"` the issue is there

**Comment by jf-viguier** [comment]
@florine2623 I have it on a helper form in a custom module. Please test it on a legacy helper form.

**Comment by hibatallahAouadni** [comment]
Hello @jf-viguier 

I know it's kind of stupid question :sweat_smile: 
But could help me to apply this step :sweat_smile: sorry :pray: 
> activate autofill on your browser (on by default)

Waiting for your feedback.
Thanks!

**Comment by jf-viguier** [comment]
autofill is activated by default in browsers,

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier,

I manage to reproduce the issue with PS1778 & PS1783
![image](https://user-images.githubusercontent.com/16067358/155696613-1c7b66f9-b614-448c-aa80-369ec645507d.png)
The browser autocomplete is displayed when I try to fill the date picker of a catalog price rule.
so I can confirm that this behavior is indeed a bug.

Thank you for the issue & the PR :slightly_smiling_face:
