### ISSUE TITLE
Manage Attribute type group

### ISSUE THREAD

**Issue by papich06** [PrestaShop/PrestaShop#27768]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

by default with Prestashop you can only create 3 Attribute group. From the drop-down list, select one of the available attributes.
https://doc.prestashop.com/display/PS17/Managing+Product+Attributes

### Describe the solution you'd like

this module corresponds but no update since the 15/03/2017
https://addons.prestashop.com/fr/declinaisons-personnalisation/26570-attribute-wizard-ps-17.html

### Alternatives you've considered

offer different layouts and colors to highlight the product.

when you select a state an explanation appears below as on this site
https://certideal.com/iphone-x-reconditionnes/iphone-x-64-go-gris-sideral-5254

### Additional context

For telephony and computer products, it is important to highlight the components

https://certideal.com/iphone-x-reconditionnes/iphone-x-64-go-gris-sideral-5254

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by florine2623** [comment]
Hello @papich06 ,

Are you saying that you want new Attribute Types to be added ?
<img width="385" alt="Screenshot 2022-02-22 at 14 33 01" src="https://user-images.githubusercontent.com/16019289/155142591-e440c1be-5db8-4ae0-a61c-7403dc0b2564.png">
If yes, could you specify which one ?

Thanks!

**Comment by papich06** [comment]
Hello, @florine2623 

yes how do you add spefic attribute like this module or certideal ?
-> to manage capacity for example or image

addons module https://addons.prestashop.com/fr/declinaisons-personnalisation/26570-attribute-wizard-ps-17.html

![attribute-wizard-ps-17](https://user-images.githubusercontent.com/4650270/155179925-2aea0bf4-f7b0-4793-b377-4195ab373011.jpg)

certideal https://certideal.com/iphone-x-reconditionnes/iphone-x-64-go-gris-sideral-5254
![attributes-types-certideal](https://user-images.githubusercontent.com/4650270/155179938-ff917ffa-4cac-4a47-8d47-0143d826cfe7.PNG)

**Comment by hibatallahAouadni** [comment]
Hello @papich06 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you

**Comment by papich06** [comment]
Hello @hibatallahAouadni 
it's not a new feature to design attributes with css?
add an image like the screenshots presented?
