### ISSUE TITLE
Errors occur when create a new slide in the default  module "ps_imageslider"

### ISSUE THREAD

**Issue by web-burn** [PrestaShop/PrestaShop#27777]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Errors occur when create a new slide in the default module "ps_imageslider":
![Screenshot_2](https://user-images.githubusercontent.com/22581200/155219451-aa3c14d6-cb36-4ed3-a4ea-9e696f3241a0.jpg)

### Expected behavior

No error expectedNo error expected

### Steps to reproduce

1. Enable the "Debug mode".
2. Go to settings of the module "ps_imageslider":
![image](https://user-images.githubusercontent.com/22581200/155219672-496773e6-54d6-4fdb-949c-bfc25ddafc8e.png)
2. Click on "Add new" 
![image](https://user-images.githubusercontent.com/22581200/155219774-3d0dd6ee-cb35-4586-8a41-3c89c75432cf.png)
3. Errors occur:
![Screenshot_2](https://user-images.githubusercontent.com/22581200/155219451-aa3c14d6-cb36-4ed3-a4ea-9e696f3241a0.jpg)

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_imageslider 3.1.0

**Comment by hibatallahAouadni** [comment]
Hello @web-burn 

Thanks for reporting the issue!
I reproduce the issue with PS1780 and PS1783 **only with PHP 7.4**! It's a **regression** as I can't reproduce it with PHP 7.2 on these versions. I’ll add this to the debug backlog so that it’s fixed.

PS: I **encounter** this issue **only** when I open the **create new image-slider**, with edit there's no issue!

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

If you manage to get the problem fixed, then please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by mparvazi** [comment]
Hello @hibatallahAouadni 

I've encountered with this error on https://github.com/PrestaShop/ps_imageslider/pull/70
So I tried to fix there.

**Comment by RiviereMarc** [comment]
Hello,

This issue occur also on Prestashop version 8.0.0 beta.1
PHP Version : 8.1.10 or version : 8.0.23

Regards
Marc.

![1](https://user-images.githubusercontent.com/114829824/193424104-f10373a4-339b-4333-9852-093846a13324.PNG)
![2](https://user-images.githubusercontent.com/114829824/193424106-0c13bd80-7e07-480d-ad18-f3f7586d77bc.PNG)
![3](https://user-images.githubusercontent.com/114829824/193424107-ed2ef40b-a497-4923-93c4-aef6f7dbc9f1.PNG)

**Comment by fdbckmedia** [comment]
Adds a check before executing getimagesize()
`		if(file_exists($_FILES['image_' . $language['id_lang']]['tmp_name']))
               	 	$imagesize = @getimagesize($_FILES['image_' . $language['id_lang']]['tmp_name']);
`

> Hello,
> 
> This issue occur also on Prestashop version 8.0.0 beta.1 PHP Version : 8.1.10 or version : 8.0.23
> 
> Regards Marc.
> 
> ![1](https://user-images.githubusercontent.com/114829824/193424104-f10373a4-339b-4333-9852-093846a13324.PNG) ![2](https://user-images.githubusercontent.com/114829824/193424106-0c13bd80-7e07-480d-ad18-f3f7586d77bc.PNG) ![3](https://user-images.githubusercontent.com/114829824/193424107-ed2ef40b-a497-4923-93c4-aef6f7dbc9f1.PNG)

**Comment by Shaste6440** [comment]
> Ajoute une vérification avant d'exécuter getimagesize() ` if(file_exists($_FILES['image_' . $language['id_lang']]['tmp_name'])) $imagesize = @getimagesize($_FILES['image_' . $language['id_lang']]['tmp_name']); `
> 
> > Bonjour,
> > Ce problème se produit également sur Prestashop version 8.0.0 beta.1 PHP Version : 8.1.10 ou version : 8.0.23
> > CordialementMarc.
> > ![1](https://user-images.githubusercontent.com/114829824/193424104-f10373a4-339b-4333-9852-093846a13324.PNG) ![2](https://user-images.githubusercontent.com/114829824/193424106-0c13bd80-7e07-480d-ad18-f3f7586d77bc.PNG) ![3](https://user-images.githubusercontent.com/114829824/193424107-ed2ef40b-a497-4923-93c4-aef6f7dbc9f1.PNG)

bonjour,
il faut insérer le message:
if(file_exists($_FILES['image_' . $language['id_lang']]['tmp_name'])) $imagesize = @getimagesize($_FILES['image_' . $language['id_lang']]['tmp_name']); 

comment s'il vous plait , entre quelle ligne ?
d'avance merci

**Comment by RiviereMarc** [comment]
Bonjour,
il suffit de remplacer la ligne 469 par le test indiqué plus haut.

Information complémentaire l'erreur se produit lorsqu'on oublie de préciser l'image pour les autres langues.

Marc.

**Comment by SharakPL** [comment]
@Shaste6440 & @RiviereMarc please use english only on PrestaShop repos. Thank you.

**Comment by adiacla** [comment]
Answer:  Only you have to update carrusel module to 3.12 version in the backoffice.

I have installed This issue occur also on Prestashop version 8.0.0 beta.1
PHP Version : 8.1.10

**Comment by hibatallahAouadni** [comment]
Closing the issue as fixed with PS811 and imageslider v3.1.3
