### ISSUE TITLE
Updating category using webservice resets its connection with customer groups

### ISSUE THREAD

**Issue by KminekMatej** [PrestaShop/PrestaShop#27778]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

During sending request to update Product Category, all its connected groups got reseted into default state (which means only groups 1,2,3 are connected).

Problem lies here: https://github.com/PrestaShop/PrestaShop/blob/0e15af762a6b158ba5442ee4a2950382161fec06/classes/Category.php#L247
Property Category->groupBox is not set properly, before calling update() method on the Category object.

Category::$webserviceParameters contains this field (groupBox) in its hidden_fields section, therefore there should be some logic serving it, but apparently its not. 

### Expected behavior

All the connections between the Category <-> Group stays untouched (api XML doesnt contain node to change groups)

### Steps to reproduce

1. Set group to some category, using UI
2. Call request PUT: https://prestashop/api/categories with some category data
3. Check category details on UI - categories should get resetted to state where only 1,2,3 are checked (system categories)

### PrestaShop version(s) where the bug happened

1.7.7.5

### PHP version(s) where the bug happened

8.0

**Comment by hibatallahAouadni** [comment]
Hello @KminekMatej 

Could you please explain these sentences:
> During sending request to update Product Category, all its connected groups got reseted into default state (which means only groups 1,2,3 are connected).

>All the connections between the Category <-> Group stays untouched (api XML doesnt contain node to change groups)

How customer groups are connected to Product Categories? 
and could you please provide some screenshots or a screen record :pray: 
Waiting for your feedback.

PS: please downgrade your PHP version to 7.3 cause PS1775 is not compatible with PHP8.0 (see our [system requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart)).

Thanks!

**Comment by KminekMatej** [comment]
My apologies, I found out Im just been using too old version of prestashop (1.7.7.5) and that problem has already been fixed in 1.7.8.0 version
