### ISSUE TITLE
Self configurator of module need a real path for the YML config file

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#27780]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

While you use the self configurator of module inside the console, without any file argument, the find of self_config.yml is done inside the module folder.

Now, if you'd like to use a dev_config.yml for example, you will need to pass the file as it: /var/www/<...>/dev_config.yml (a real path, so).

### Describe the solution you'd like

Be able to pass the file name and that the self configurator will handle it.

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 


Thank you for your suggestion. The Developers Team will take it into consideration for future developments.
 
Please be aware that there is no guarantee that this feature will be developed anytime soon.
Waiting for your PR 🚀 


Thank you
