### ISSUE TITLE
[BO - Outstanding ]An exception is displayed in the Oustanding page when the customer with valid orders is deleted

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27785]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Reported here: https://github.com/PrestaShop/PrestaShop/pull/27763#pullrequestreview-891354330
An exception is displayed in the Outstanding page when the customer with valid orders is deleted

With PS1778 => OK
![image](https://user-images.githubusercontent.com/16067358/155491334-560ccbea-4f9a-44a8-9892-a1985682ed79.png)
Oustanding

### Steps to reproduce

1. Enable B2B
2. Create a new customer & create an order
3. Go to BO > Orders > Orders > change the order status to accepted
4. Delete the customer created
5. Go to BO > Customers > Outstanding page
6. See error 

![image](https://user-images.githubusercontent.com/16067358/155363833-e93b2f2d-cc5f-4df7-b933-877c7a544684.png)

### PrestaShop version(s) where the bug happened

1.7.8.0, 1.7.8.3, 1.7.8.x

### PHP version(s) where the bug happened

7.4

**Comment by Progi1984** [comment]
Fixed by @atomiix in #28031 and tested by @marwachelly
