### ISSUE TITLE
Create NumberWithUnitType and IntegerWithUnitType

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#27787]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Currently there is only TextWithUnitType.

For the new forms we have to create IntegerWithUnitType and numberWithUnitType

Without this we cannot pass optionresolver with a good template.

It's an issue for the dev core Team https://github.com/PrestaShop/PrestaShop/pull/27608#discussion_r813746914

### Describe the solution you'd like

Create NumberWithUnitType and IntegerWithUnitType

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

Thank you for your suggestion. The Developer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. 

And it seems that @micka-fdz is working on it :muscle: 
So, we're waiting for your PR :rocket: 

Thank you
