### ISSUE TITLE
[Delivery pdf] Products Images are not well displayed with RTL lanaguage

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27794]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This issue is related to this issue: https://github.com/PrestaShop/PrestaShop/issues/27265
It could be fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/27405
In the delivery pdf, images of products are not well displayed with RTL
![image](https://user-images.githubusercontent.com/16067358/155700826-9f2e2a63-63dd-43fb-bf41-f4e8af6dbbf1.png)

### Expected behavior

PS1778 => OK
![Uploading image.png…]()

### Steps to reproduce

1. Go to BO > Your profile & select the Arabic language
2. Go to BO > Orders > Deliveryslip page > Enable product image
3. Generate a delivery slip & download it

### PrestaShop version(s) where the bug happened

1.7.8.0, 1.7.8.3

### PHP version(s) where the bug happened

7.4

**Comment by MatShir** [comment]
@mparvazi we need your RTL skills !

**Comment by mparvazi** [comment]
> @mparvazi we need your RTL skills !

Unfortunately the problem is related to:
`vendor/tecnickcom/tcpdf/tcpdf.php`
![Screenshot from 2022-02-28 23-56-46](https://user-images.githubusercontent.com/85633460/156053847-4803d474-0a0e-4bdb-90ec-a3ef39d14fb7.png)

I think this problem can not be solved by the PS.

**Comment by mparvazi** [comment]
@MatShir 

I just found a solution that can fix the problem, not so smart but it works!

## Fix the header logo position for RTL
Files that needs to be modified (for header logo https://github.com/PrestaShop/PrestaShop/issues/27265)
```
pdf/header.tpl
classes/pdf/HTMLTemplate.php
classes/pdf/PDFGenerator.php
```

![Screenshot 2022-03-02 at 10-41-47 IN000001-13 pdf](https://user-images.githubusercontent.com/85633460/156395619-8b2feb0a-4768-4677-8de8-c5611ecf773a.png)

1. Need to disable RTL behavior for header by tcpdf
<img src="https://user-images.githubusercontent.com/85633460/156398677-27d8c22f-f2e2-410b-9537-30f971e36fec.png" width="700">

2. As RTL disabled for header so need to manage RTL for header content
<img src="https://user-images.githubusercontent.com/85633460/156398695-7a923499-3cd6-4f93-a375-cb095f881e02.png" width="700">

3. Two templates for header will be: LTR and RTL
<img src="https://user-images.githubusercontent.com/85633460/156398710-efe5610f-d9ed-412b-8f73-4a1732660c50.png" width="700">


## Fix product image position for RTL
Need to add an empty column before image column for RTL:

![Screenshot 2022-03-03 at 10-15-05 DE000002-55 pdf](https://user-images.githubusercontent.com/85633460/156593636-bc5f9545-840a-4183-a50c-7f131940b88d.png)



## Some improvements for alignment
Need to change hard coded alignments (e.g `<td class="product left">`) to the variables:

<img src="https://user-images.githubusercontent.com/85633460/156583041-c59c8b12-025e-47d5-8caf-475ddb798e38.png" width="700">

<img src="https://user-images.githubusercontent.com/85633460/156583076-5967bba6-ef48-41ec-bc42-1b27c48263f5.png" width="700">

**Comment by MatShir** [comment]
> @MatShir
> 
> I just found a solution that can fix the problem, not so smart but it works!
> 
> ## Fix the header logo position for RTL
> Files that needs to be modified (for header logo #27265)
> 
> ```
> pdf/header.tpl
> classes/pdf/HTMLTemplate.php
> classes/pdf/PDFGenerator.php
> ```
> 
> ![Screenshot 2022-03-02 at 10-41-47 IN000001-13 pdf](https://user-images.githubusercontent.com/85633460/156395619-8b2feb0a-4768-4677-8de8-c5611ecf773a.png)
> 
> 1. Need to disable RTL behavior for header by tcpdf
> 
> <img alt="" width="700" src="https://user-images.githubusercontent.com/85633460/156398677-27d8c22f-f2e2-410b-9537-30f971e36fec.png">
> 
> 2. As RTL disabled for header so need to manage RTL for header content
> 
> <img alt="" width="700" src="https://user-images.githubusercontent.com/85633460/156398695-7a923499-3cd6-4f93-a375-cb095f881e02.png">
> 
> 3. Two templates for header will be: LTR and RTL
> 
> <img alt="" width="700" src="https://user-images.githubusercontent.com/85633460/156398710-efe5610f-d9ed-412b-8f73-4a1732660c50.png">
> 
> ## Fix product image position for RTL
> Need to add an empty column before image column for RTL:
> 
> ![Screenshot 2022-03-03 at 10-15-05 DE000002-55 pdf](https://user-images.githubusercontent.com/85633460/156593636-bc5f9545-840a-4183-a50c-7f131940b88d.png)
> 
> ## Some improvements for alignment
> Need to change hard coded alignments (e.g `<td class="product left">`) to the variables:
> 
> <img alt="" width="700" src="https://user-images.githubusercontent.com/85633460/156583041-c59c8b12-025e-47d5-8caf-475ddb798e38.png">
> 
> <img alt="" width="700" src="https://user-images.githubusercontent.com/85633460/156583076-5967bba6-ef48-41ec-bc42-1b27c48263f5.png">

@NeOMakinG do you think the fix is it legit ?

**Comment by atomiix** [comment]
I think we should either use this workaround or fork the lib and apply the fix because using the old version of the library makes it impossible to make PrestaShop compatible with PHP 8.1.
