### ISSUE TITLE
[Mobile] BO - Stocks page - The multistore header is NOK when using a mobile 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27799]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Catalog > Stocks page, the multistore header is not working when using a mobile
![image](https://user-images.githubusercontent.com/16067358/155757598-425a96ef-6618-42f9-af1d-ae94936c3754.png)

With PS1782, the header multistore is not displayed

https://user-images.githubusercontent.com/16067358/155758630-d79ee547-83a8-43c7-a738-042ed2f1ef92.mp4

### Steps to reproduce

1. Enable multistore
2. Create a new shop & configure an URL 
3. Select any shop & go to BO > Catalog > Stocks page
4. Try to click on the eye icon to view FO => NOK
5. Try to click on the header to change the selected shop => NOK

https://user-images.githubusercontent.com/16067358/155758325-a29c9f10-74d8-4143-8508-e66e042df507.mp4

### PrestaShop version(s) where the bug happened

1.7.8.3, 1.7.8.4build1

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
This issue has been fixed on 8.1.x, see the attached screenshot below:

![image](https://github.com/PrestaShop/PrestaShop/assets/23308427/7c290f5f-e3e4-45c2-af6e-df94d568e5fb)

Closing the issue :tada:
