### ISSUE TITLE
BO - Security - The help modal cannot be opened

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#27798]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In BO page Security the help modal cannot be opened.

If you look at Developer Tools "Network" tab you can see request fails with CORS problem
![Capture d’écran 2022-02-25 à 15 58 52](https://user-images.githubusercontent.com/3830050/155737517-f4592918-0c2a-42da-949c-64665a9fa76a.png)

### Expected behavior

In BO page Security the help modal can be opened. It can be blank but at least it must load

### Steps to reproduce

1. Go to BO > Advanced Parameters > Security
2. Click on 'Help'

Screenshot
![Capture d’écran 2022-02-25 à 15 58 57](https://user-images.githubusercontent.com/3830050/155737321-75398c66-dc78-4a36-8538-f91e8c26f81b.png)

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4

**Comment by matks** [comment]
@Julievrz Just like https://github.com/PrestaShop/PrestaShop/issues/23996 we need a new help page for the Security BO page because it is a new page (it does not exist in 1.7.8)

**Comment by khouloudbelguith** [comment]
Hi @matks,

I manage to reproduce the issue with develop branch
![image](https://user-images.githubusercontent.com/16067358/155738389-77eecff6-d7bb-497c-b347-6a169f5286aa.png)
so I can confirm that this behavior is indeed a bug.

Thank you
