### ISSUE TITLE
Increase CSS specificity for js-mobile-menu

### ISSUE THREAD

**Issue by amaury-hanser** [PrestaShop/PrestaShop#27805]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

If one loads _**material-icons**_ in a module, it might overwrite the style of the icon of the mobile menu.
When it happens, the menu icon will be shown even on desktop because the class `.material-icons` has a rule `display: inine-block;`.

![image](https://user-images.githubusercontent.com/25964813/155998782-0aec4678-fb73-4fd5-8210-fc4be36023d7.png)

### Describe the solution you'd like

The icon has the class: `js-mobile-menu`.
Surely we can increase the specificity to something like: `.main-header .js-mobile-menu`

### Additional context

![image](https://user-images.githubusercontent.com/25964813/155999229-073e4017-1592-4d0d-9e4d-39725659882b.png)

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by amaury-hanser** [comment]
The fix might be done in both files:
- `PrestaShop/admin-dev/themes/default/scss/partials/_nav.scss`
- `PrestaShop/admin-dev/themes/new-theme/scss/components/layout/_nav_bar.scss`

Should I make a PR with a change in `scss` files only or also with the compiled files ?

**Comment by hibatallahAouadni** [comment]
Hello @amaury-hanser 

I think what you reported is a purely bug and not a feature request.
We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #22892. 
Please subscribe to the issue mentioned above and we're waiting for your PR :muscle: :rocket: 

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #22892
