### ISSUE TITLE
CMS page : text added is not saved

### ISSUE THREAD

**Issue by sirius82** [PrestaShop/PrestaShop#27801]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,
I changed an existing website to multishop. CMS page are already created. The page about shipping need to be changed but I was surprised when I open it : the HTML code is displayed in the editor
![image](https://user-images.githubusercontent.com/11886689/155858713-171f90c4-f34b-482d-a22b-e011f71fea1d.png)
But the page is correctly displayed on the front.
I modify what I need and save => the page is now empty on the front.
I reopen the page in the admin, all the text has disappeared. Only stays that 
![image](https://user-images.githubusercontent.com/11886689/155858819-c25af9e3-6c0a-418e-a2e6-8c373eae5931.png)
I try to create a new CMS page and it's the same.
And it's the same thing for the text on maintenance page.

Thanks

### Expected behavior

Create or modify a CMS page

### Steps to reproduce

1. Go to CMS page Shipping
2. Save the page
3. The text is not saved

### PrestaShop version(s) where the bug happened

1.7.6.4

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @sirius82 

It seems your issue related to your PHP version, you need to downgrade your PHP version to 7.2 cause PS1764 is not compatible with PHP 7.4 (see our system requirements).
As you can see in my attached screen record below, I didn't reproduce the issue with PS1767:

https://user-images.githubusercontent.com/23308427/155956735-1f11d43c-ecd7-4029-b3df-f81f42d44565.mp4

Closing the issue as it's a not Core bug.
Thanks!

**Comment by sirius82** [comment]
A very big thanks ! I would never have thought of the php version ! After downgrading, it works fine now !
Sorry for this invalid post !

**Comment by hibatallahAouadni** [comment]
@sirius82 you're welcome :relaxed:
