### ISSUE TITLE
Some exceptions displayed after an upgrade from PS16124  when "Enable advanced stock management" is enabled

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27807]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I found an exception after an upgrade from PS16124 to PS1778/PS1780/PS1783/178x  when "Enable advanced stock management" is enabled.

Create order from BO with RTL
![image](https://user-images.githubusercontent.com/16067358/156018055-7f416bc0-559b-438b-a441-f345e3bc8f4e.png)

Create order from FO with RTL
![image](https://user-images.githubusercontent.com/16067358/156018421-64dc4de2-cfa9-4420-8c69-5a006c92cf55.png)

View Order_conf template
![image](https://user-images.githubusercontent.com/16067358/156018250-74381a2e-1893-4949-bf8c-851269d6941c.png)

### Steps to reproduce

1. Install PS16124 with English language & France country
2. Upload Arabic pack
3. Create a product with a customization file
4. Configure the Email
5. Go to BO > Preferences > Products > Enable **"Enable advanced stock management"** 
![image](https://user-images.githubusercontent.com/16067358/156018674-6aa584d7-671a-44aa-8361-80d4f1a5e184.png)
6. Upgrade to PS1778/PS1780/PS1783/178x(PS1784)
7. Enable **debug mode**
8. Install payment modules (ps_checkpayment)
9. Go to FO > select Arabic language & create an order with the customized product
10. Go to BO > Orders > Add new order > choose a customer & add the customized product > choose arabic lanaguage & create the order => see error
11. Change the employee lanaguage to Arabic & go to Design > Email theme > Modern/Classic > Preview order_conf template
12. See error

### PrestaShop version(s) where the bug happened

1.7.7.8, 1.7.8.0, 1.7.8.3, 1.7.8.4build1

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version
autoupgrade v4.14.0

**Comment by Hlavtox** [comment]
Advanced stock management can't have an effect since it's configuration is removed here - https://github.com/PrestaShop/autoupgrade/commits/dev/upgrade/sql/1.7.2.0.sql.

Also, all of it has been removed for develop.

Also, we don't cart about upgrades from 1.6 anymore. :-)
