### ISSUE TITLE
faceted search on new products not display

### ISSUE THREAD

**Issue by mickaelmarin** [PrestaShop/PrestaShop#27818]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On new product page the faceted search not display.

It work on category but on the new product page it does'nt display.

thanks

### Expected behavior

faceted search show on new products page.

### Steps to reproduce

add few products with characteristics

on home page hook the new products module

click on "all new products" link on home page

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_facetedsearch

**Comment by hibatallahAouadni** [comment]
Hello @mickaelmarin 

Could you please explain this step:
> on home page hook the new products module

Waiting for your feedback.
Thanks!

**Comment by mickaelmarin** [comment]
When you activate the new products module  in the  back office on the home page (this is the defaullt on classic theme if I remember). You have a link to all new products, and when you go to the all new products page with this link, the facetedsearch not show on the left sidebar (in my case I use left sidebar).

**Comment by HanaRebaiQA** [comment]
Hello @mickaelmarin 

Thanks for your report.
You ticket is a duplicate of [#15137](https://github.com/PrestaShop/PrestaShop/issues/15137)

So, i'll close the issue. Do not hesitate to open new tickets when needed.

Thanks!

**Comment by HanaRebaiQA** [comment]
Duplicate of [#15137](https://github.com/PrestaShop/PrestaShop/issues/15137)
