### ISSUE TITLE
V 1.7.8.3 unable to truncate product title 

### ISSUE THREAD

**Issue by Peter4661** [PrestaShop/PrestaShop#27821]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After update to V1.7.8.3 unable to truncate product title.

mytheme/template/catalog/partials/miniatures/product.tpl. Change in value  {$product.name|truncate:30:'...'} does not change lenght of the product title .
 
backoffice, clear cache,
backoffice: force template
FTP:  Clear smarty cache
does not give any change in front office.

### Expected behavior

Lenght of product title to te edited

### Steps to reproduce

mytheme/template/catalog/partials/miniatures/product.tpl. Change in value  {$product.name|truncate:30:'...'} does not change lenght of the product title .
 
backoffice, clear cache,
backoffice: force template
FTP:  Clear smarty cache
does not give any change in front office.

I installed fresh dev version 1.7.8.3 which shows the same behaviour.

Configuration information:
Serverinformatie: Linux #1 SMP Fri Oct 8 12:03:35 UTC 2021 x86_64
Server softwareversie: LiteSpeed
PHP-versie: 7.4.27
Memory limiet: 768M
Max execution time: 300
Max file size for  uploads: 768M

List  overrides
classes/ObjectModel.php
classes/order/Order.php
classes/Link.php
classes/module/Module.php
classes/Dispatcher.php
classes/Media.php
classes/controller/ProductListingFrontController.php
classes/controller/FrontController.php
classes/Validate.php
classes/Hook.php
classes/Context.php
classes/helper/HelperList.php
classes/pdf/HTMLTemplateInvoice.php
classes/pdf/PDFGenerator.php
classes/pdf/HTMLTemplateDeliverySlip.php
controllers/front/ProductController.php
controllers/front/listing/CategoryController.php
controllers/front/listing/ManufacturerController.php
controllers/front/listing/SupplierController.php
controllers/front/CmsController.php
controllers/front/ContactController.php
controllers/front/CartController.php
controllers/front/IndexController.php
controllers/admin/AdminProductsController.php

Changed file:
config/smartyfront.config.inc.php

All parameters: oké

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4.27

**Comment by hibatallahAouadni** [comment]
Hello @Peter4661 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you
