### ISSUE TITLE
Bump minimum PHP version for PrestaShop 8.x ?

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#27829]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

According to https://devdocs.prestashop.com/8/basics/installation/system-requirements/ PrestaShop 8.0 should be compatible with PHP 7.2 .

I think it might be the right moment to push this a little further 🤔  because PHP 7.2 and 7.3 are now EOL.

https://www.php.net/supported-versions.php

### Describe the solution you'd like

Bump minimum PHP version to 7.4

However this could make upgrades harder for merchants using hosting environments with old PHP versions

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by kpodemski** [comment]
100x yes! I've suggested that a long time ago. Most people will use PrestaShop 8 on the new installations. It is hard to imagine they won't have a server with PHP 7.4 available.

**Comment by HanaRebaiQA** [comment]
Hello @matks 

Thank you for your suggestion.
And we're waiting for your PR.

Thanks!

**Comment by saulaski** [comment]
Yes, absolutely:
- Best code quality requires PHP 7.4
- Support of PHP 7.2 has ended, serious users should have updated since
- Support of PHP 7.4 will end late 2022

**Comment by kpodemski** [comment]
One thing that might be important in this discussion is: `autoupgrade`. I think we shouldn't allow merchants to update directly to v8 from, for example, 1.7.4, maybe it should be like this:

- 1.7.2 -> 1.7.8
- Require PHP 7.4 minimum
- Allow the update to v8

**Comment by atomiix** [comment]
I agree too! Module and theme developers will have to make their projects compatible with php 8.0 anyway, so it would only be a bonus to have a 7.2 compatibility. And as @kpodemski said, it's quite easy to have a php 7.4 server.
In addition to that, 1.7.8.x is already compatible with php 7.4 so the upgrade process would still be the same.

**Comment by Amoifr** [comment]
At a time, when the stack is an important argument for developers in choosing their next mission, I think it's counterproductive to the objective of recruiting devs or encouraging devs to contribute to the project.
In addition, hosts (especially shared ones) force developers to update their distribution when a version of php is considered obsolete.
So I vote for at least the 7.4 ... and may be the 8.1 
But I know that I'm not too aware of side effect in the ecosystem.

**Comment by marsaldev** [comment]
Totally agree, but as @kpodemski said, we need to pay very attention on `autoupgrade` process

**Comment by saulaski** [comment]
To follow up last comment from @Amoifr, OS contributors might enjoy PHP 7.4 features as well. Not only professionals.
I don't mean contributors can't be professionals as well. Contributing on their free time should be an enjoyable experience thanks to modern engineering.

**Comment by AlexTechDev** [comment]
Totally agree, I think that have a server with php 7.4 won't be a problem. 

Great idea

**Comment by PrestaEdit** [comment]
I add my +1 on this.

**Comment by eternoendless** [comment]
Having PHP 7.2 minimum allows merchants to upgrade from 1.7.5 and higher. If we bump to 7.4 people will only be able to upgrade from 1.7.8, increasing the cost of upgrade.

This request is also assuming that current community modules work well with 7.4, which is not necessarily the case. Therefore, bumping the minimum PHP version risks increasing the cost of upgrading to v8.

**Comment by kpodemski** [comment]
@eternoendless it already is high because of a lot of depreciations in the core - module developers need to improve codebase of their modules and it might be a chance to make them compat with 7.4/8 too.

**Comment by kpodemski** [comment]
@PrestaShop/prestashop-maintainers shall we vote? :> I think it's better to have an answer earlier for this

**Comment by eternoendless** [comment]
As I said -- I don't think doing this artificially (i.e. without a good reason) is in the best interest of the community. But let's start by asking them what they think about it on Slack.

**Comment by matks** [comment]
Closing as decision was finally taken
