### ISSUE TITLE
cURL error 28: Operation timed out after 10001 milliseconds with 0 bytes received on prestashop checkout

### ISSUE THREAD

**Issue by weihan00ae** [PrestaShop/PrestaShop#27833]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi,

yesterday midnight I got a payment through paypal but I was looking for the order this morning and I couldn't find it. In the end I found this error in the customer's message section.

_This message is sent automatically by module PrestaShop Checkout

A customer encountered a processing payment error :
Customer identifier: ****
Cart identifier: ****
PayPal order identifier: **********
Exception identifier: 35
Exception detail: cURL error 28: Operation timed out after 10001 milliseconds with 0 bytes received

If you need assistance, please contact our Support Team on PrestaShop Checkout configuration page on Help subtab._

I don't know how to reproduce this error. Do you have any idea how to resolve it or what's the cause of this error?

Thank you!

### Expected behavior

I expected the payment to go through without any problems.

### Steps to reproduce

I have no idea

### PrestaShop version(s) where the bug happened

1.7.7.3

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

ps_checkout

**Comment by hibatallahAouadni** [comment]
Hello @weihan00ae 

It seems that your issue is not a PrestaShop core bug.
If your module is Checkout Official, please contact support team on Addons

We will close this issue.

Thanks!
