### ISSUE TITLE
Problems with the admin login with Chrome around: stay logged in and I forgot my password

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#27835]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi
I use Chromium 99.0.4844.51 (Build ufficiale) Arch Linux (a 64 bit), the same problem is present on windows with chrome.
instead with firefox all is ok.
the problem happens on all 1.7 versions

look at this video
https://watch.screencastify.com/v/GLHnVDE6m24Ob2wwS86P

![9](https://user-images.githubusercontent.com/653230/156741966-145daffd-9e70-476a-8c3b-aaa63e7392f7.png)

### Steps to reproduce

1. go at the admin login

### PrestaShop version(s) where the bug happened

1.7.8.4

### PHP version(s) where the bug happened

7.3

**Comment by NeOMakinG** [comment]
Wow, looks curious, I'm using it like 4 or 5 times a day and never faced that with Chrome, let's see if the QA is able to reproduce it!

Thanks for the issue anyway, appreciate it

PS: If it's not reproducible, suspicious chrome extension maybe?

**Comment by Maofree** [comment]
Hi
I get this error with 5-6 my customers that use different pc in different lan
yesterday I've upgraded chrome and today other people alert me about this problem
I have the same problem even in incognito mode

**Comment by NeOMakinG** [comment]
> Hi I get this error with 5-6 my customers that use different pc in different lan yesterday I've upgraded chrome and today other people alert me about this problem I have the same problem even in incognito mode

Thx for the precisions

**Comment by hibatallahAouadni** [comment]
Hello @maofree 

I think it's a regression on Chrome 99 cause I only reproduce this issue with Chrome 99 on Windows, Linux and MacOs.
See the attached screen record below:

https://user-images.githubusercontent.com/23308427/156796171-a9b16f6f-2284-48c1-9374-12051cd8bf20.mp4

Ping @NeOMakinG wdyt?
Thanks!

**Comment by hibatallahAouadni** [comment]
Reproduce it with PS1778 on Chrome 99 with MacOs

![image](https://user-images.githubusercontent.com/23308427/156817893-14e593d6-e4c0-4c38-86ae-4b9d4b9a315a.png)

@maofree I think it will be better if you downgrade your Chrome version.

**Comment by Maofree** [comment]
Hi
for me is it not a problem, it works if I push on the same position of past. I've alerted my customers to do the same.
I cannot do a downgrade to their browsers
I'll wait your fix :)

**Comment by NeOMakinG** [comment]
> Hello @maofree
> 
> I think it's a regression on Chrome 99 cause I only reproduce this issue with Chrome 99 on Windows, Linux and MacOs. See the attached screen record below:
> 
>  issue_27838.mp4 
> Ping @NeOMakinG wdyt? Thanks!

It should be fixable, this page is full of spaghetti anyway, we can still work on improving it :)

I'll work on it next week!

**Comment by Maofree** [comment]
ok thanks

**Comment by mparvazi** [comment]
@NeOMakinG 

Please consider migration of the Login page to the new-theme.

**Comment by itsvahid** [comment]
Here is a quick fix:
add position relative to the form-group containing "remind me" and "I forgot my password"
this should fix it
![image](https://user-images.githubusercontent.com/48237049/156915492-f7c3c4fa-b80f-4a96-ae46-dd556809f6d0.png)

**Comment by NeOMakinG** [comment]
I considered it as a regression, and it's the first page you see while using prestashop, it should be displayed correctly

So it will probably be fixed in 1.7.8.5 @PrestaShop/product-team if you've something against it, tell me

**Comment by Maofree** [comment]
Hi @NeOMakinG 
I've tested the fix but I think it is necessary to fix another thing
it is missing the "go back link"

![0](https://user-images.githubusercontent.com/653230/157254463-59a303b4-a7c2-4648-a698-2894a16dccc4.png)

**Comment by NeOMakinG** [comment]
@maofree This problem and some others should be fixed by https://github.com/PrestaShop/PrestaShop/pull/27812

**Comment by lmeyer1** [comment]
To fix the display issue of the BO login form in Chrome 99, it is sufficient to add these lines to the file `admin-dev/themes/default/css/overrides.css`:

    form#login_form {
      position: relative;
    }

**Comment by matks** [comment]
Nice tip @lmeyer1 big thanks !

**Comment by hibatallahAouadni** [comment]
This issue has been fixed by this PR #27843
