### ISSUE TITLE
Wrong wording on exit button with the bulk delete

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#27836]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On the BO,

When you do a "Delete selected" on "bulk actions" 
![image](https://user-images.githubusercontent.com/100699445/156765615-617bd605-0a78-477c-bb7a-aa572bb5733d.png)

on : 

(1)Catalog > Products and the button is bleu
![image](https://user-images.githubusercontent.com/100699445/156764694-8c367154-ed81-44a9-872e-27993ad3833d.png)

(2)Catalog > Categories
![image](https://user-images.githubusercontent.com/100699445/156764744-d654e10d-9540-4742-adea-8046c20222c1.png)

and (3)Customers > Customers 
![image](https://user-images.githubusercontent.com/100699445/156764851-d3ed8ba4-4b2d-470b-910e-ce3d10792aac.png)

we can see that the Exit Buttons is "Close/Delete" instead of "Cancel/Delete"

in the case of Catalog > Products, the button is blue instead of red, and it should be writted "Delete" instead of "Delete Now"

### Expected behavior

The Exit Buttons should be Cancel/Delete
The button "Delete" should be red

as we can see at this specs : https://github.com/PrestaShop/prestashop-specs/pull/264

### Steps to reproduce

For the case (1) : 
1. Clic on Catalog at the left to get the other option
2. Clic on Products
3. Cross some checkbox
4. Clic on Bulk actions ( like the first screen ) 
5. Clic on Delete selected 

For the case (2) : 
1. Clic on Catalog at the left to get the other option
2. Clic on Categories
3. Scroll down  
4. Cross some checkbox
5. Clic on Bulk actions ( like the first screen ) 
6. Clic on Delete selected 

For the case (3) : 
1. Clic on Customers at the left to get the other option
2. Clic on Products
3. Scroll down  
4. Cross some checkbox
5. Clic on Bulk actions ( like the first screen ) 
6. Clic on Delete selected 

### PrestaShop version(s) where the bug happened

develop

**Comment by Julievrz** [comment]
Thanks. As these buttons dismiss an action, it should be "Cancel". "Close" is for informative modals only.

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/product-team I looked in the specs but the `Delete` button color was not mentioned, so could you please specify the `Delete` button color :pray: 

Thanks in advance.

**Comment by Julievrz** [comment]
Maybe @prestascott or @TristanLDD can help. ☺️

**Comment by prestascott** [comment]
Hello everyone,

Yes the color for "Delete" button must be red. :)
