### ISSUE TITLE
Any Blog addon not work on PS 1.7.8.4

### ISSUE THREAD

**Issue by simonemessina** [PrestaShop/PrestaShop#27832]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Blank page in blog page i tried different addon no one work anymore.
I found this error "Attempted to load class "SmartBlogPost" from the global namespace. Did you forget a "use" statement? [Symfony\Component\Debug\Exception\ClassNotFoundException 0]"

Symfony new version maybe cause this issue. 

### Steps to reproduce

Go to any blog page 

### PrestaShop version(s) where the bug happened

1.7.8.4

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

Any blog module

**Comment by hibatallahAouadni** [comment]
Hello @simonemessina 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must fill the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
