### ISSUE TITLE
Db insert bugs out when the column is named type

### ISSUE THREAD

**Issue by krekken** [PrestaShop/PrestaShop#27847]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When i try to insert into a column with 

```php
Db::getInstance->insert()
```
I get an error message from DbCore, because of this if statement: 
![image](https://user-images.githubusercontent.com/58357424/157040999-221aa00f-a587-4706-abac-7ca65b16e7df.png)

I would think the column name "type" is used quite often so this might be an issue. In most cases the column could be renamed from type to something more specific, but i insert into a core table, so my workaround for this time was inserting by executing raw sql code in a foreach loop, which is bad practice, but no other workaround came to my mind.

Is there a chance this could be mitigated?

### Expected behavior

Insert the data into the database without a hitch

### Steps to reproduce

try to insert anything into a table where there is a column called "type". in my case it was ps_customization_field

### PrestaShop version(s) where the bug happened

1.7.8.3

**Comment by hibatallahAouadni** [comment]
Hello @krekken 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must provide clear and concise steps to reproduce**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you
