### ISSUE TITLE
Multistore does not delete cache of themes from id_shop different than 1

### ISSUE THREAD

**Issue by ocio87** [PrestaShop/PrestaShop#27846]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I identify that when cache deletion is performed in Multistore in `Advanced Parameters - Performance` and the button `Empty the cache` or permanent cookies is pressed, the store only manages to delete the cache of the default store in the route `/themes/default_theme/assets/cache`. If you try to delete the cache of store 2 or 3 that have another theme, it does not delete the files found in `/themes/default_theme_2/assets/cache and /themes/default_theme_3/assets/cache` for example.

This bug is generating file saturation in the mentioned paths.

### Steps to reproduce

1. Select **default store** in the backoffice.
2. Go to **Parameters - Performance** and the button `Empty the cache` or permanent cookies is pressed.
3. The store deletes files in `/themes/default_theme/assets/cache`
4. Select **store** in the backoffice.
5. Select **store 2** in the backoffice.
6. Go to **Parameters - Performance** and the button Empty the cache or permanent cookies is pressed.
7. The store cannot delete files in the other theme that is configured `/themes/default_theme_2/assets/cache`.

![image](https://user-images.githubusercontent.com/12537826/157034194-872a0ea1-43ef-46ae-a817-b4354afd3e52.png)

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @ocio87 

Could you please check this issue #21238, It seems related to yours.
Please check and feedback.

Thanks!

**Comment by ocio87** [comment]
Thanks @hibatallahAouadni

**Comment by ocio87** [comment]
Hello @hibatallahAouadni

I am reading the bug that you indicate https://github.com/PrestaShop/PrestaShop/issues/21238 but I see that the report is about a multi-store and then the multi-store was eliminated. In my case I still have a multistore with 3 stores. Does it apply the same way?

**Comment by hibatallahAouadni** [comment]
@ocio87 I think it will be better if we add your details to the original issue :wink:  
So when it will get fixed, the QA-Team test both cases, wdyt?

**Comment by hibatallahAouadni** [comment]
Duplicate of #21238
