### ISSUE TITLE
productcomments - rating is not displayed the second time in Quick view 

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#27845]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I don't see the rating of my product in the Quick view modal after I click on it a second time.
It will show again only after a refresh

https://user-images.githubusercontent.com/16019289/157011947-a180c214-b662-4221-b6ac-c3801468c0d3.mov

### Expected behavior

I should see the rating in quick view everytime I click on it.

### Steps to reproduce

1. Add a comment + rating to a product
2. Go to the homepage
3. Click quick view : OK
4. Click off modal
5. Click quick view again : NOK

### PrestaShop version(s) where the bug happened

1.7.8.4, develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

productcomments v5.0.1

**Comment by hibatallahAouadni** [comment]
Thanks @florine2623 
It's not a regression! I reproduced on 1.7.7.8 with Product Comments v4.2.2.

**Comment by leemyongpakvn** [comment]
@hibatallahAouadni I have made a PR for this issue. Please check.
