### ISSUE TITLE
Wrong attribute stats in statsforecast module

### ISSUE THREAD

**Issue by Shoprunners** [PrestaShop/PrestaShop#27852]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The last column values aren't calculated correctly:
Scroll down in the statsforecast module (main stats page) and see the lasts stats table about attributes.

"Group | Attribute | Quantity of products sold"

Now consider these 2 orders:

i.e.:
Order 1:
Shirt size: XL quantity 2
Order 2:
Trousers size: XL quantity 3

current behaviour:
Group | Attribute | Quantity of products sold
Size | XL | **2**

But Should be
Group | Attribute | Quantity of products sold
Size | XL | **5**

### Expected behavior

But Should be
Group | Attribute | Quantity of products sold
Size | XL | **5**

### Steps to reproduce

Scroll down in the statsforecast module (main stats page) and see the lasts stats table about attributes.

"Group | Attribute | Quantity of products sold"

Now consider these 2 orders:

i.e.:
Order 1:
Shirt size: XL quantity 2
Order 2:
Trousers size: XL quantity 3

current behaviour:
Group | Attribute | Quantity of products sold
Size | XL | **2**

### PrestaShop version(s) where the bug happened

1.7.0.0

### PHP version(s) where the bug happened

all

### If your bug is related to a module, specify its name and its version

statsforecast v2.04

**Comment by florine2623** [comment]
Hello @Shoprunners ,

Thanks for the report.
I have reproduced your issue with statsforecast v2.0.4, so I can confirm that this behavior is indeed a bug.

It seems like the column Quantity of product sold is based on the number of order (and not the number of attributes).

<img width="730" alt="Screenshot 2022-03-08 at 11 12 43" src="https://user-images.githubusercontent.com/16019289/157215709-170b12ed-2f43-4497-8e77-857e65b21634.png">

Thanks for your PR.
