### ISSUE TITLE
Hook getHookStatusByName was converted to case sensitive

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#27854]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Since this PR was merged https://github.com/PrestaShop/PrestaShop/pull/26748

The previous code was:
```php
    public static function getHookStatusByName($hook_name): bool
    {
        $sql = new DbQuery();
        $sql->select('active');
        $sql->from('hook', 'h');
        $sql->where('h.name = "' . pSQL($hook_name) . '"');

        return (bool) Db::getInstance()->getValue($sql);
    }
```

Now the code looks like this:

```php
    public static function getHookStatusByName($hook_name): bool
    {
        $hook_names = [];
        if (Cache::isStored('active_hooks')) {
            $hook_names = Cache::retrieve('active_hooks');
        } else {
            $sql = new DbQuery();
            $sql->select('name');
            $sql->from('hook', 'h');
            $sql->where('h.active = 1');
            $active_hooks = Db::getInstance()->executeS($sql);
            if (!empty($active_hooks)) {
                $hook_names = array_column($active_hooks, 'name');
                if (is_array($hook_names)) {
                    Cache::store('active_hooks', $hook_names);
                }
            }
        }

        return in_array($hook_name, $hook_names);
    }
```

The problem is that MySQL is not case sensitive, but `in_array` is.

So if for example in the BDD we have `ModuleRoutes` and in the code `moduleRoutes`
Or `displayOverrideTemplate` in the BDD but `DisplayOverrideTemplate` in the code

Then the hook doesn't trigger, before the modification it used to work.

### Expected behavior

I should be able to trigger hooks with case sensitive inputs and it always work.

### Steps to reproduce

Use the quality inssurance module and try to trigger a hook with different writings (upper/lower cases modifications).
Or identify a hook in the core on which some modules are registered, and modify the spelling of the hook in the core code.

### PrestaShop version(s) where the bug happened

1.7.8.4

### PHP version(s) where the bug happened

Not relevant

**Comment by JoshTheDerf** [comment]
Yep, we ran into this after updating. Several of our internal module hooks suddenly broke as they were stored fully lowercase in the database.

**Comment by lmeyer1** [comment]
@jolelievre Thanks for finding this bug

**Comment by usoldev** [comment]
displayOverrideTemplate hook doesn't work anymore, its a huge problem.

**Comment by matks** [comment]
Severity has been raised to CRITICAL 🔴  this means 1.7.8.5 release date will be pushed to deliver this ASAP

**Comment by jolelievre** [comment]
Hi @florine2623 and @hibatallahAouadni 

this bug was initially reported by @SebBareyre 

Maybe he can help you in reproducing the faulty behavior

**Comment by hibatallahAouadni** [comment]
Hello @SebBareyre 

Could you please provide clear and concise steps to reproduce the issue.
Waiting for your feedback.

Thanks!

**Comment by florine2623** [comment]
@Seb33300 ,

I tried to reproduce your issue in PS 1.7.8.4. I used all uppercase, all lowercase and a mix of both in the module [quality assurance](https://github.com/PrestaShop/ps_qualityassurance).  But I can't reproduce it :

https://user-images.githubusercontent.com/16019289/158234717-0cc033bd-c473-4f20-ac67-e615842ca848.mov

**Comment by marwachelly** [comment]
Hello @SebBareyre,

Following the steps to reproduce we wasn't able to reproduce the issue as shown in the screen record bellow with PS1.7.8.4 , PHP7.3 and Chrome version 96.0.4664.93 

![image](https://user-images.githubusercontent.com/89604350/158328139-96ff6519-5a9d-4a20-be9e-d771b5e34bfb.png)

https://watch.screencastify.com/v/o1LEGHdLnEYukwfWEy1g
Did we miss something?

Many thanks,

**Comment by matks** [comment]
@JoshTheDerf @usoldev we are trying to find a usecase to reproduce the issue. This would help us build the fix. Could you help us? A clear list of "how to observe the bug on your shop"

**Comment by kpodemski** [comment]
@PrestaShop/qa-team 

Please use the example module that I attach. Visit the product page and you should see this:
https://www.dropbox.com/s/yxpa47jivw9lnq5/Zrzut%20ekranu%202022-03-15%20o%2009.04.04.png?dl=0

This means that hook has been correctly executed. Scenario:
1.7.8.4: you won't see this `dump` which is a bug
After implementing the fix by @lmeyer1 (https://github.com/PrestaShop/PrestaShop/pull/27874) you should see it.

[hooksbug.zip](https://github.com/PrestaShop/PrestaShop/files/8251245/hooksbug.zip)

**Comment by marwachelly** [comment]
Hello,

I manage to reproduce the issue with the module provided with PS 1.7.8.4 following the steps bellow :+1: 

1. install a module
2. go to the product page in front office
3.  with PS1.7.8.4 the dump of the array doesn't exist 
4. with PS 1.7.8.0/ 1.7.8.3  a dump of the array exist in front office

https://watch.screencastify.com/v/3XmcnWT3LCkovkk6bdrz
https://watch.screencastify.com/v/J1nUx2atKZcnOm2KnPZv

Thank you @kpodemski !!

**Comment by matks** [comment]
Thank you everybody involved in this

https://github.com/PrestaShop/PrestaShop/pull/27874 was merged

1.7.8.5 release is in progress
