### ISSUE TITLE
Error translation not found slowing down product editing with lot of combinations 

### ISSUE THREAD

**Issue by intered84** [PrestaShop/PrestaShop#27858]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,
I'm having issue on a Prestashop 1.7.6.5 shop that is using a single language (French). 

There is thousand of warning reported in Symfony about missing translation : the translations are the product categories themselves.

The problem is, when a product have a lot of combination (200+), it take about 50 sec to load the edit page, then the page freeze, and is globally unusable.

![error1](https://user-images.githubusercontent.com/101193513/157256233-db96f5dd-6adc-44ef-bcf8-e834aea784cb.PNG)

![error2](https://user-images.githubusercontent.com/101193513/157253778-f938a479-1e50-41f3-acbd-d6ea4e17fdb0.PNG)

![error3](https://user-images.githubusercontent.com/101193513/157254383-d81a5088-64e5-4b78-b97f-c17aef5758b6.PNG)

![errorstat](https://user-images.githubusercontent.com/101193513/157255129-e022ff38-c114-4789-8ea9-47bfbfc7ee42.PNG)

Even the symfony debug page take ages to load (2 minutes), the shop have a lot of different categories and product combination, so there is thousand and thousand of errors generated, it think that is this what is slowing down/crashing the edition page. 

I've tried upgrading to 1.7.6.9, then 1.7.7.7 with no success, still the same warning in symfony and the huge slowdown.

Is it an expected behavior ? Why symfony is warning me that there is no translation even with 1 single language enabled ?
How to fix this slowdown ?

Thanks.

### Expected behavior

I expect that there is no translation error when using a single language. 
I expect that there the edit page does not hang after loading for 1 minute.

### Steps to reproduce

Have 1 language enabled.
Have approximatively 150 product categories
Have approximatively 150 product attribute
Create a product with 250 combination. 
Try to edit the product.

### PrestaShop version(s) where the bug happened

1.7.6.5 and 1.7.7.7

### PHP version(s) where the bug happened

PHP 7.2

**Comment by florine2623** [comment]
Hello @intered84 ,

Is your issue related to one of these issues : https://github.com/PrestaShop/PrestaShop/issues/12915 or https://github.com/PrestaShop/PrestaShop/issues/9809 ?

Could you check and feedback ?
Thanks!

**Comment by intered84** [comment]
> 

Hello,

It is related to #9809

The product are not in sale right now because we can't edit them, so I can't confirm if it's the same as the #12915

The behavior of the issue is similar, howewer, #9809 there is no mention of the warning/error displayed by symfony due to a missing translation.

I'm not a developper, but I think that the hundred repeated warning of the missing translation is causing the slowdown : it take 3 minutes to load the debug tool while all the error are loading 1 by 1.

Thanks,

Regards.

**Comment by florine2623** [comment]
@intered84 ,

As your issue is related to the other ones. I will close it !
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks !
