### ISSUE TITLE
BO - [Stock] An error message is displayed when editing by zero on quantity field 

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#27866]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An error message is displayed when editing by zero on quantity field (Bad request)
![image](https://user-images.githubusercontent.com/92912932/157257196-dfb51cc4-c332-410d-be59-dc9107ad3df8.png)

PS1784 :x: 

https://user-images.githubusercontent.com/92912932/157465036-d896d915-86ee-412a-83d4-ba2258e2d800.mp4

PS1778 :x:

https://user-images.githubusercontent.com/92912932/157465024-dde9383c-61a0-46c9-99e5-edefce675088.mp4

 

### Expected behavior

The zero is also a number. Make it possible to edit with zero on quantity field.

### Steps to reproduce

1. BO > SELL > Catalog > Stock
2. Click on field to edit quantity
3. Put a `zero` number
See error > An error message is displayed (Bad request)

### PrestaShop version(s) where the bug happened

1.7.7.8 & 1.7.8.4

### PHP version(s) where the bug happened

7.3

**Comment by Progi1984** [comment]
@PrestaShop/product-team What is the expected behavior ?

**Comment by Julievrz** [comment]
I'd go with something simple: "Value cannot be 0." in Admin.Notifications.Error

**Comment by Julievrz** [comment]
@MatShir The expected behavior is that the user cannot use the 0 value in the quantity field, right?

**Comment by Progi1984** [comment]
@MatShir It seems that the bug has been fixed in 8.1.0, not in 1.7.8.x. (I see your kanban change).
