### ISSUE TITLE
upgrate

### ISSUE THREAD

**Issue by enginteknoloji** [PrestaShop/PrestaShop#27869]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![Adsız](https://user-images.githubusercontent.com/78131343/157488405-5c39b180-e112-4020-86fc-7852540f8677.jpg)

### Expected behavior

[INTERNAL] /home/tkyawclg/domains/elektronikpazartr.com/public_html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php line 54 - Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation "@Doctrine\ORM\Mapping\I" in class PrestaShopBundle\Entity\Translation was never imported. Did you maybe forget to add a "use" statement for this annotation? #0 /home/tkyawclg/domains/elektronikpazartr.com/public_html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(726): Doctrine\Common\Annotations\AnnotationException::semanticalError('The annotation ...') #1 /home/tkyawclg/domains/elektronikpazartr.com/public_html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(1064): Doctrine\Common\Annotations\DocParser->Annotation() #2 /home/tkyawclg/domains/elektronikpazartr.com/public_html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(1047): Doctrine\Common\Annotations\DocParser->PlainValue() #3 /home/tkyawclg/domains/elektronikpazartr.com/public_html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(1194): Doctrine\Common\Annotations\DocParser->Value() #4 /home/tkyawclg/domains/elektronikpazartr.com/public_html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(1139): Doctrine\Common\Annotations\DocParser->ArrayEntry() #5 /home/tkyawclg/domains/elektronikpazartr.com/public_html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(1060): Doctrine\Common\Annotations\DocParser->Arrayx() #6 /home/tkyawclg/domains/elektronikpazartr.com/public_html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(1116): Doctrine\Common\Annotations\DocParser->PlainValue() #7 /home/tkyawclg/domains/elektronikpazartr.com/public_html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(1044): Doctrine\Common\Annotations\DocParser->FieldAssignment() #8 /home/tkyawclg/domains/elektronikpazartr.com/public_html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(875): Doctrine\Common\Annotations\DocParser->Value() #9 /home/tkyawclg/domains/elektronikpazartr.com/public_html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(859): Doctrine\Common\Annotations\DocParser->Values() #10 /home/tkyawclg/domains/elektronikpazartr.com/public_html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(769): Doctrine\Common\Annotations\DocParser->MethodCall() #11 /home/tkyawclg/domains/elektronikpazartr.com/public_html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(653): Doctrine\Common\Annotations\DocParser->Annotation() #12 /home/tkyawclg/domains/elektronikpazartr.com/public_html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(359): Doctrine\Common\Annotations\DocParser->Annotations() #13 /home/tkyawclg/domains/elektronikpazartr.com/public_html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php(221): Doctrine\Common\Annotations\DocParser->parse('/**\n * Translat...', 'class PrestaSho...') #14 /home/tkyawclg/domains/elektronikpazartr.com/public_html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/CachedReader.php(80): Doctrine\Common\Annotations\AnnotationReader->getClassAnnotations(Object(ReflectionClass)) #15 /home/tkyawclg/domains/elektronikpazartr.com/public_html/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/Driver/AnnotationDriver.php(177): Doctrine\Common\Annotations\CachedReader->getClassAnnotations(Object(ReflectionClass)) #16 /home/tkyawclg/domains/elektronikpazartr.com/public_html/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/Driver/AnnotationDriver.php(245): Doctrine\Persistence\Mapping\Driver\AnnotationDriver->isTransient('PrestaShopBundl...') #17 /home/tkyawclg/domains/elektronikpazartr.com/public_html/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/Driver/MappingDriverChain.php(107): Doctrine\Persistence\Mapping\Driver\AnnotationDriver->getAllClassNames() #18 /home/tkyawclg/domains/elektronikpazartr.com/public_html/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php(90): Doctrine\Persistence\Mapping\Driver\MappingDriverChain->getAllClassNames() #19 /home/tkyawclg/domains/elektronikpazartr.com/public_html/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/CacheWarmer/ProxyCacheWarmer.php(68): Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->getAllMetadata() #20 /home/tkyawclg/domains/elektronikpazartr.com/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/CacheWarmer/CacheWarmerAggregate.php(52): Symfony\Bridge\Doctrine\CacheWarmer\ProxyCacheWarmer->warmUp('/home/tkyawclg/...') #21 /home/tkyawclg/domains/elektronikpazartr.com/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(686): Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp('/home/tkyawclg/...') #22 /home/tkyawclg/domains/elektronikpazartr.com/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() #23 /home/tkyawclg/domains/elektronikpazartr.com/public_html/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(76): Symfony\Component\HttpKernel\Kernel->boot() #24 /home/tkyawclg/domains/elektronikpazartr.com/public_html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(56): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #25 /home/tkyawclg/domains/elektronikpazartr.com/public_html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(86): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() #26 /home/tkyawclg/domains/elektronikpazartr.com/public_html/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #27 /home/tkyawclg/domains/elektronikpazartr.com/public_html/ruya/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #28 {main}

### Steps to reproduce

![Adsız](https://user-images.githubusercontent.com/78131343/157488768-4706d789-6828-49f8-8d8b-5c8933ddf81e.jpg)

### PrestaShop version(s) where the bug happened

1781-82-83

### PHP version(s) where the bug happened

1.7.8.1-1.7.8.2-1.7.8.3

### If your bug is related to a module, specify its name and its version

yok

**Comment by hibatallahAouadni** [comment]
Hello @enginteknoloji 


Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
