### ISSUE TITLE
BO - [Stock] Impossible to put numbers in quantity field with RTL (There is only the possibility to increment and decrement numbers)

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#27864]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Impossible to put numbers in quantity field with RTL, we have only the possibility to increment and decrement numbers

PS 1784 :x: 

https://user-images.githubusercontent.com/92912932/157455173-f0e456d7-cef9-48d7-ad2a-536619d35137.mp4

PS1780  :x: 

https://user-images.githubusercontent.com/92912932/157455158-9a98e98f-c053-4ae4-96ab-38f072913eb9.mp4

PS1778 :heavy_check_mark:

https://user-images.githubusercontent.com/92912932/157455151-7ed8b8ec-3873-4eaa-b27c-1781fea93219.mp4

 

### Expected behavior

Make it possible to put numbers with RTL in quantity fields

### Steps to reproduce

1. BO > Enable RTL language (As Arabic)
2. Go to > SELL > Catalog > Stock
3. Click on field to edit quantity
4. See error > Cannot putting numbers

### PrestaShop version(s) where the bug happened

1.7.8.0 & 1.7.8.4

### PHP version(s) where the bug happened

7.3

**Comment by MeKeyCool** [comment]
From my tests, it looks that the RTL stock page style is Ok for 8.0.x so I don't have to backport my changes.

For information, I observed that in 1.7.8.x, *_rtl.css file is generated when I installed a RTL language and I didn't find any other way to regenerate it.

**Comment by florine2623** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29246
