### ISSUE TITLE
Allow to add content after themes list

### ISSUE THREAD

**Issue by sowbiba** [PrestaShop/PrestaShop#27865]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Describe the solution you'd like

There was a button after the themes list in Appearence > Theme and logo page

This block was removed in https://github.com/PrestaShop/PrestaShop/pull/26917

This request is about adding a hook in that place to allow modules to add content after the themes list (like a link to themes catalogue, as it was)

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @sowbiba 


Thank you for your suggestion. The Product Team will take it into consideration for future developments. 

Thanks for your PR 🚀 

Thank you
