### ISSUE TITLE
combinations_import.csv - update sample file so as shop owner I can have the same columns names and order as importer default

### ISSUE THREAD

**Issue by roktiw** [PrestaShop/PrestaShop#27861]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The order and name of the columns from the sample file does not match with the importer order. The official sample file from Presta is from Sep 1, 2017

I just made a new version of the file https://github.com/PrestaShop/PrestaShop/blob/develop/docs/csv_import/combinations_import.csv

here is how it works:
![Zrzut ekranu 2022-03-08 231345](https://user-images.githubusercontent.com/6304323/157336741-1178131d-6917-438d-91bc-f429f2881174.png)

### Expected behavior

Official sample file would have columns names and order the same as offical importer expects

### Steps to reproduce

1. Go to Advanced Parameters - Import
2. Download obsolete file "Sample Combinations file"
3. On "Match your data" step all the coumns headers will be messed up compared to sample file

### PrestaShop version(s) where the bug happened

1.7.8.4

**Comment by roktiw** [comment]
I've described it better here: https://github.com/roktiw/PrestaShop-docs-csv_import

**Comment by hibatallahAouadni** [comment]
Hello @roktiw 

Could you please check this issue #23083 cause it seems related to yours.
Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @roktiw 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
