### ISSUE TITLE
Site is not indexing in google

### ISSUE THREAD

**Issue by ricardovtav** [PrestaShop/PrestaShop#27878]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Good afternoon, I have a website procoral.com.br and it is already 1 year old. But so far it has not been indexed in google. On Yahoo it appears normal, I already created the site maps in the search console and it was processed, but it still doesn't appear on google. I would like some help.

Thanks

### Expected behavior

I would like it to be indexed in google.

### Steps to reproduce

Search procoral.com.br on google

### PrestaShop version(s) where the bug happened

1.7.6.4

### PHP version(s) where the bug happened

7.0

**Comment by Hlavtox** [comment]
I am trying to access your site from Czech republic and the website timeouts. Check your hosting.

Nothing we can do for you, not related to Prestashop.

**Comment by hibatallahAouadni** [comment]
Hello @ricardovtav 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
