### ISSUE TITLE
FO - Create an account - the alert is duplicated when we create a new account with invalid firstname and lastname

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27876]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the FO > when we create an account from the `Create an account` page or checkout page with invalid `firstname` and `lastname`, the alert is duplicated
**Create account page**
![image](https://user-images.githubusercontent.com/16067358/157643315-e1f0a9f0-cfc4-4de8-9b00-72af0abaeb62.png)
**Checkout page**
![image](https://user-images.githubusercontent.com/16067358/157643468-68afac3d-6489-4000-9da4-c82afeead93d.png)

In the PS1783 => OK

### Expected behavior

![image](https://user-images.githubusercontent.com/16067358/157645792-ee54f50b-1b29-41a1-bfdd-855414cf003d.png)

### Steps to reproduce

1. Go to FO > Create a new account
2. Set invalid firstname & lastname for example demo_
3. Set required fields and save 

-----------------------------------------

1. Go to FO > Add a product to cart & proceed to checkout
2. In the personal information step > Set invalid firstname & lastname for example demo_
3. Set required fields and save

### PrestaShop version(s) where the bug happened

1.7.8.4, develop

### PHP version(s) where the bug happened

7.4

**Comment by Progi1984** [comment]
Fixed by @atomiix in #28028 and tested by @AureRita. Thanks

**Comment by Progi1984** [comment]
Fixed by @atomiix in https://github.com/PrestaShop/PrestaShop/pull/28028 and tested by @AureRita. Thanks
