### ISSUE TITLE
The selection of modules to uninstall does not reset after uninstallation

### ISSUE THREAD

**Issue by jeckyl** [PrestaShop/PrestaShop#27877]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

When we try to uninstall several modules at the same time, the uninstallation goes well but the page remains in the same state and the selected modules are always selected, so if we decide to select new ones and to restart the uninstallation phase we have an error message for each already uninstalled module.

This is not a problem, but it can be a concern for the average user.

### Expected behavior

The uninstalled module should be deselected automatically, as its button already disappears.

### Steps to reproduce

1. Module manager
2. select some modules
3. uninstall it
4. select other module
5. uninstall it too

### PrestaShop version(s) where the bug happened

1.7.x

**Comment by hibatallahAouadni** [comment]
Hello @jeckyl 

Thanks for this well detailed bug report :clap: 
Clear and concise stesp to reproduce :ok_hand: BRAVO :rocket: 
Unfortunately, I didn't reproduce the issue with PS1778, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/157717129-2ef4c121-9b3c-4c0f-8132-bc41773d765b.mp4

As you can see, when the uninstall process finish, the module disappear from the list.
The only case where the module still selected is when we encounter an issue about uninstalling the module.

Please check and feedback.
Thanks!

**Comment by jeckyl** [comment]
I have not tested the case where we decide to delete the module and I have not tested all versions of PrestaShop.

In any case on the 1.7.8.4 when we decide just to uninstall modules we encounter the problem.

**Comment by khouloudbelguith** [comment]
Hi @jeckyl,

I tried with PS1784, but I did not manage to reproduce the issue with PS1784.
I attached a screen record

https://user-images.githubusercontent.com/16067358/157892878-a547ff83-eee3-4ddd-b6fb-c3143f08aad7.mp4

Thanks to check and feedback

**Comment by jeckyl** [comment]
Well, I will have to redo a basic installation of Prestashop to identify the case because trying to reproduce it I can not.
For the installation I went through softaculous then directly after the admin connection I went to the modules to uninstall the usual list of useless modules and I had the problem, without touching anything before so I'll have to retest this installation as well as a manual installation to know if I can reproduce the thing on both systems.

**Comment by khouloudbelguith** [comment]
@jeckyl,

Despite our several trials, we could not reproduce your issue with the provided information.
It seems that your issue is not a PrestaShop's core bug but most likely a server configuration or customization problem.
We will close this issue.
Feel free to open a new one when needed.

Thanks!

**Comment by jeckyl** [comment]
Closed directly without even giving me time to test again.
Well, I'll pass next time.

**Comment by NeOMakinG** [comment]
@jeckyl a closed issue doesn't mean that it can't be opened again...

**Comment by jeckyl** [comment]
> Feel free to open a new one when needed.

> @jeckyl a closed issue doesn't mean that it can't be opened again...

Then agree on the procedures.

In any case I personally do not have the means to reopen an issue so there is no evidence that if I add evidence here it will be taken into consideration.

As the case does not seem to be reproducible I move on to something more constructive.

**Comment by hibatallahAouadni** [comment]
Hello @jeckyl 

You can ping just right here in this issue when you provide a new evidence and I will try to reproduce the issue.
Ofc, if I reproduce the issue, I will reopen it.

> Feel free to open a new one when needed.

> @jeckyl a closed issue doesn't mean that it can't be opened again...

You're right! I think we may need to redo our automatique answers :wink: 

Thanks for your understanding :pray:

**Comment by jf-viguier** [comment]
If you will to add this bug in prestashop, I strongly suggest you consider [hiring a specialist](https://friendsofpresta.org/) to help you. It's not so easy to stay below the radar ;-)
