### ISSUE TITLE
Make PrestaShop compatible with PHP 8.1

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#27888]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Describe the solution you'd like

Make PrestaShop and its native modules compatible with PHP 8.1

- [x] Make Core compatible with PHP 8.1
  - [x] Upgrade phpstan >= 1.0 : #27723
  - [x] Upgrade phpunit 9.5
  - [x] Upgrade smarty 4* (incl TranslationToolsBundle)
  - [x] Remove deprecation messages
- [x] All native modules must be compatible with PHP 8.1
- [x] #28764

### Additional context

As stated by @atomiix in October 2021:

> To be fully compatible with PHP 8.1, we need:
>   - [tactician-bundle](https://github.com/thephpleague/tactician-bundle/pull/127)
>   - [smarty](https://github.com/smarty-php/smarty/pull/678)
>   - to check pelago/emogrifier
>   - to check phpspec/prophecy
>   - some other small changes in PrestaShop's code

**Comment by Progi1984** [comment]
Modules are compatible. I have installed the Github Action for each one.

**Comment by atomiix** [comment]
To make PrestaShop compatible with PHP 8.1, we need:
- phpstan >= 1.0
- phpunit 9.5
- smarty 4*, but we also need to update `prestashop/translationtools-bundle` to make it compatible with smarty 4 too
- other small deprecated messages to be removed in the core

*for smarty, the version 4 gives full support of PHP 8.1 but some deprecations are still displayed. We can either choose to keep them until it's fixed upstream or use the fork I already started until it's fixed upstream as well.

**Comment by Progi1984** [comment]
@atomiix I work on the bump of version of PHPStan (linked to this issue #16471).

**Comment by eternoendless** [comment]
Issue updated with information from @atomiix's message

**Comment by ObscenityIB** [comment]
Have to go with an alternate shop while I wait for this, presta looked so good!

**Comment by matks** [comment]
Congratulations @atomiix and everybody involved

**Comment by matks** [comment]
Reopening because a few remaining items are still there but not in the Core

**Comment by eternoendless** [comment]
You mean the docker image? or is there anything else?

**Comment by atomiix** [comment]
@eternoendless there's 3 PRs on 3 modules:
- https://github.com/PrestaShop/ps_linklist/pull/149
- https://github.com/PrestaShop/classic-theme/pull/34
- https://github.com/PrestaShop/autoupgrade/pull/488

And a PR related to the installer: https://github.com/PrestaShop/PrestaShop/pull/28647

**Comment by Mirko-Tebaldi** [comment]
so... the actual  (21 of October of 2022) version of Prestashop is compatible up to which php version?

I cannot find this info in no where

**Comment by MGDev-FR** [comment]
> so... the actual (21 of October of 2022) version of Prestashop is compatible up to which php version?
> 
> I cannot find this info in no where

For what I see... it's not compatible with 8.0 or 8.1 but with 7.4... sadly.

I was so happy to use Prestashop (for the first time)... now I am disappointed to have to downgrade my PHP version when I am currently working on the last PHP version for clients...

**Comment by kpodemski** [comment]
@MGDev-FR the upcoming PrestaShop 8.0 is compatible with PHP 8.1

**Comment by serhii-f8** [comment]
Is there any information on when PrestaShop 8 will be added to the https://www.prestashop.com/en/versions section?

**Comment by eternoendless** [comment]
To the best of my understanding newer versions will only be available through Github: https://github.com/PrestaShop/PrestaShop/releases

**Comment by MGDev-FR** [comment]
> @MGDev-FR the upcoming PrestaShop 8.0 is compatible with PHP 8.1

Thank you but I finally switched to do my own e-commerce website with Symfony 6 so I am totally free to do all what I want and it's fully compatible with PHP 8. And finally, with a nice e-commerce template for the frontend didn't take me so much time to do that e-commerce website.

Sorry... first experience with Prestashop, it results that I won't use it never I think.

Good luck with Prestashop.
