### ISSUE TITLE
POA select button in product catalogue

### ISSUE THREAD

**Issue by johannsnr** [PrestaShop/PrestaShop#27883]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Some larger suppliers of products and brands do not allow prices to be shown or advertised on the internet. As such there is a requirement to have the price shown or select to not show and replace wit POA (price upon application)

This will allow the user to select whether the price is shown in the front end or POA

Further to this some suppliers do not want a 'add to cart' button for products but the price can be shown
This is done because those suppliers want to actually get customers in store

### Describe the solution you'd like

a simple solution is to have a selector in the price tab of the catalogue in the back office, selecting between POA on or off
This can also be the solution for the add to cart button - show or faded out and replaced with 'available in store only' with a phone number or email link

The admin user should be able to see prices as normal in the back end

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by khouloudbelguith** [comment]
Hi @johannsnr,

Thanks for your suggestion.
>Further to this some suppliers do not want a 'add to cart' button for products but the price can be shown

In the BO > Catalog > Product > Edit product page > Options tab, we have the visibility option
1. If `Available for order` is **checked**: the price of the product is shown & we can add it to cart 
**BO**
![image](https://user-images.githubusercontent.com/16067358/157858166-67002cdf-e7f6-4893-8360-12fc0078d9c4.png)
**FO** 
![image](https://user-images.githubusercontent.com/16067358/157858369-cd007515-49aa-4945-8921-2851a5571e10.png)

2. If the `Available for order` is **not checked** + `Show price` is **checked**: the price is shown & we cannot add the product to cart
**BO** 
![image](https://user-images.githubusercontent.com/16067358/157858628-6775200c-fce7-42f0-b513-f4832b6492f3.png)
**FO** 
![image](https://user-images.githubusercontent.com/16067358/157858744-6b7e3966-ff09-4f80-80e7-2b9692fd04ea.png)
3. If the `Available for order` is **not checked** + `Show price` is **not checked**: the price is not shown & we cannot add the product  to cart 
**BO** 
![image](https://user-images.githubusercontent.com/16067358/157858962-82653455-d40d-4b84-9555-ab33bd86c09d.png)
**FO**
![image](https://user-images.githubusercontent.com/16067358/157858884-7544e3b1-d5f6-4518-8cf8-4b682284e4b2.png)
4. Also, we can check the option `Web only (not sold in your retail store)`

Is it similar to your suggetion?

Thanks!

**Comment by johannsnr** [comment]
Hi

Thank you did not know this

**Comment by hibatallahAouadni** [comment]
Hello @johannsnr 

Thanks for your feedback.
Closing the issue!

Thanks!
