### ISSUE TITLE
Issue click upgrade 1.7.7.5 to 1.7.8.4

### ISSUE THREAD

**Issue by xga91** [PrestaShop/PrestaShop#27894]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I am trying to upgrade to last version with click upgrade v4.14.0 latest version.

I tested with php 7.3 and 7.4 and same error message.

At the end of process there's red messaging = 

```
[INTERNAL] /home/herlib/public_html/perles-tahiti.org/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 168 - Symfony\Component\Config\Exception\FileLoaderLoadException: The file "/home/herlib/public_html/perles-tahiti.org/src/PrestaShopBundle/Resources/config/services/adapter/image.yml" does not contain valid YAML: The constant "_PS_PROFILE_IMG_DIR_" is not defined at line 27 (near "!php/const _PS_PROFILE_IMG_DIR_") in /home/herlib/public_html/perles-tahiti.org/src/PrestaShopBundle/Resources/config/services/adapter/image.yml (which is being imported from "/home/herlib/public_html/perles-tahiti.org/src/PrestaShopBundle/Resources/config/services.yml"). 
#0 /home/herlib/public_html/perles-tahiti.org/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(79): Symfony\Component\Config\Loader\FileLoader->doImport() 
#1 /home/herlib/public_html/perles-tahiti.org/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(195): Symfony\Component\Config\Loader\FileLoader->import() 
#2 /home/herlib/public_html/perles-tahiti.org/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(127): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseImports() 
#3 /home/herlib/public_html/perles-tahiti.org/src/PrestaShopBundle/DependencyInjection/PrestaShopExtension.php(48): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load() 
#4 /home/herlib/public_html/perles-tahiti.org/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php(71): PrestaShopBundle\DependencyInjection\PrestaShopExtension->load() 
#5 /home/herlib/public_html/perles-tahiti.org/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process() 
#6 /home/herlib/public_html/perles-tahiti.org/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(140): Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process() 
#7 /home/herlib/public_html/perles-tahiti.org/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(789): Symfony\Component\DependencyInjection\Compiler\Compiler->compile() 
#8 /home/herlib/public_html/perles-tahiti.org/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(643): Symfony\Component\DependencyInjection\ContainerBuilder->compile() 
#9 /home/herlib/public_html/perles-tahiti.org/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() 
#10 /home/herlib/public_html/perles-tahiti.org/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(76): Symfony\Component\HttpKernel\Kernel->boot() 
#11 /home/herlib/public_html/perles-tahiti.org/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(56): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel()
#12 /home/herlib/public_html/perles-tahiti.org/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(86): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() 
#13 /home/herlib/public_html/perles-tahiti.org/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() 
#14 /home/herlib/public_html/perles-tahiti.org/admin930dmtwi5/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() 
#15 {main}
```

### Steps to reproduce

1. just use the specific module to upgrade as always click upgrade lastest version 4.14.0

### PrestaShop version(s) where the bug happened

1.7.7.5

### PHP version(s) where the bug happened

php 7.3 and 7.4

**Comment by khouloudbelguith** [comment]
Hi @xga91,

I did not manage to reproduce the issue with PS1784 after an upgrade from PS1775 using the 1-click upgrade v4.14.0.
I attached a screen record

https://user-images.githubusercontent.com/16067358/157908715-8266ab91-5b87-4eb7-b1c6-476bc5287361.mp4

PS: 1778 is not compatible with PHP7.4: https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart

Thanks to check and feedback

**Comment by xga91** [comment]
I am doing a retry with php 7.3
![1](https://user-images.githubusercontent.com/101413251/157921905-7f03f854-df37-4f7a-bd33-55ae0f8059d3.jpg)
![2](https://user-images.githubusercontent.com/101413251/157922262-bff41716-831c-483a-b206-22f07d1feee2.jpg)
![3](https://user-images.githubusercontent.com/101413251/157925000-8b8525ff-0acb-45a9-be62-da1d1d398ea8.jpg)

**Comment by xga91** [comment]
ok same result error messages, @khouloudbelguith
![4](https://user-images.githubusercontent.com/101413251/157934824-6eaf461e-99b2-49e4-b7b5-d2e49310e932.jpg)
`
[INTERNAL] /home/herlib/public_html/perles-tahiti.org/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 168 - Symfony\Component\Config\Exception\FileLoaderLoadException: The file "/home/herlib/public_html/perles-tahiti.org/src/PrestaShopBundle/Resources/config/services/adapter/image.yml" does not contain valid YAML: The constant "_PS_PROFILE_IMG_DIR_" is not defined at line 27 (near "!php/const _PS_PROFILE_IMG_DIR_") in /home/herlib/public_html/perles-tahiti.org/src/PrestaShopBundle/Resources/config/services/adapter/image.yml (which is being imported from "/home/herlib/public_html/perles-tahiti.org/src/PrestaShopBundle/Resources/config/services.yml"). #0 /home/herlib/public_html/perles-tahiti.org/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(79): Symfony\Component\Config\Loader\FileLoader->doImport('/home/herlib/pu...', NULL, false, '/home/herlib/pu...') #1 /home/herlib/public_html/perles-tahiti.org/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(195): Symfony\Component\Config\Loader\FileLoader->import('services/adapte...', NULL, false, '/home/herlib/pu...') #2 /home/herlib/public_html/perles-tahiti.org/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(127): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseImports(Array, '/home/herlib/pu...') #3 /home/herlib/public_html/perles-tahiti.org/src/PrestaShopBundle/DependencyInjection/PrestaShopExtension.php(48): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('services.yml') #4 /home/herlib/public_html/perles-tahiti.org/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php(71): PrestaShopBundle\DependencyInjection\PrestaShopExtension->load(Array, Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder)) #5 /home/herlib/public_html/perles-tahiti.org/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #6 /home/herlib/public_html/perles-tahiti.org/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(140): Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #7 /home/herlib/public_html/perles-tahiti.org/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(789): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #8 /home/herlib/public_html/perles-tahiti.org/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(643): Symfony\Component\DependencyInjection\ContainerBuilder->compile() #9 /home/herlib/public_html/perles-tahiti.org/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() #10 /home/herlib/public_html/perles-tahiti.org/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(76): Symfony\Component\HttpKernel\Kernel->boot() #11 /home/herlib/public_html/perles-tahiti.org/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(56): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #12 /home/herlib/public_html/perles-tahiti.org/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(86): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() #13 /home/herlib/public_html/perles-tahiti.org/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #14 /home/herlib/public_html/perles-tahiti.org/admin930dmtwi5/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #15 {main}
`

**Comment by xga91** [comment]
after upgrade i looged to see inside admin dashboard, i get this message error to access products for example unusable like this.
![5](https://user-images.githubusercontent.com/101413251/158034029-26ea8b86-4efb-446b-9599-d114a1857ffe.jpg)

**Comment by hibatallahAouadni** [comment]
Hello @xga91 

I would like to share my shop configuration:

![image](https://user-images.githubusercontent.com/23308427/158178462-087c3779-fcae-4097-b59e-b3d4040c036d.png)

It seems that you encounter a problem while upgrading cause after upgrading to PS1784, your shop should have a `ps_feature_flag` table, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/158181312-95b5b854-9def-4fe9-806a-7b598b02f524.mp4

Please check and feedback.
Thanks!

**Comment by xga91** [comment]
News from today,

Ok i added this line on this file ===>    config/define.inc.php to line number 153

This line =
define('_PS_PROFILE_IMG_DIR_', _PS_IMG_DIR_.'pr/');

and the upgraded passed in whole green ok.

the question is why my define.inc.php is missing this line ?

**Comment by marwachelly** [comment]
Hello,

Nice! So the ticket is not valid anymore. It will be closed. Regarding your question as default this line define('PS_PROFILE_IMG_DIR', PS_IMG_DIR.'pr/') doesn't exist in config/define.inc.php. Did you added this line manually or it is added after a module installation? May this issue https://github.com/PrestaShop/PrestaShop/issues/26230 can help you.

Thanks,

**Comment by xga91** [comment]
I added it manually.

**Comment by hibatallahAouadni** [comment]
@xga91 so you need to remove it :wink:

**Comment by xga91** [comment]
no i added the line to correcting the problem !
