### ISSUE TITLE
BO - Customers / Wrong redirection after canceling the edition of an address from the customer detail page

### ISSUE THREAD

**Issue by MeKeyCool** [PrestaShop/PrestaShop#27898]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After canceling the edition of a new address from the customer detail page we are redirected to the addresses list instead of the customer detail page.

### Expected behavior

We should be redirected to the customer detail page.

### Steps to reproduce

1. Go to Customers => Customers
2. Select any customer and go to the customer detail page
3. Scroll down to the bottom of the page and in the address block click on the "edit" icon to edit an existing address (if your customer doesn't have any address, you'll need to create one first)
4. Click on Cancel button
5. See Error => redirected to the addresses list page instead of the customer detail page

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.4.28

**Comment by MeKeyCool** [comment]
A similar problem has been solved with [ Redirect to customer when canceling new customer address creation #20603 ](https://github.com/PrestaShop/PrestaShop/pull/20603)

**Comment by khouloudbelguith** [comment]
Hi @MeKeyCool,

I manage to reproduce the issue with PS1778 & PS1780 & PS1784.

https://user-images.githubusercontent.com/16067358/157907791-e93a4937-0607-47bd-bc09-40c2ea58b6cd.mp4

Seems related to this: https://github.com/PrestaShop/PrestaShop/issues/20595

I’ll add this to the debug roadmap so that it’s fixed. 

Thanks!
