### ISSUE TITLE
BO- An unnecessary comma is displayed in the location page

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#27897]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

A wrong position of a comma in the location page
PS 1.7.8.0
![image](https://user-images.githubusercontent.com/89604350/157902586-06dd63f1-0adf-4b62-ad99-e8a7533f88a2.png)

### Expected behavior

PS 1.7.7.8
![image](https://user-images.githubusercontent.com/89604350/158154128-23f3ea5f-3b31-4b3f-851d-e7e160aadcbf.png)

### Steps to reproduce

1. Go to International> Localization
2. An unnecessary comma is displayed in configuration section

### PrestaShop version(s) where the bug happened

develop, 1.7.8.0,1.7.8.4

### PHP version(s) where the bug happened

7.3

**Comment by Progi1984** [comment]
Fixed by @PierreRambaud in #28076
