### ISSUE TITLE
BO - Modules / UI for "module updates" not clear if no module to update

### ISSUE THREAD

**Issue by MeKeyCool** [PrestaShop/PrestaShop#27896]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In Module Manager, after fresh install, no updates are necessary for modules but an orange notification appears with a '0' value.
Looks weird behavior. 

![modules_updates_notif](https://user-images.githubusercontent.com/1133504/157900385-57719652-ec69-428e-8f35-980f36c59ccc.png)

### Expected behavior

i recommend to make the symbol green or to remove it if nothing to say (depends on notification global policy).
 

### Steps to reproduce

1. Improve > Modules > Module Manager

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.4.28

**Comment by khouloudbelguith** [comment]
Hi @MeKeyCool,

I have the same behavior with PS1784 and PS1778.
It is the same behavior for `Modules Alerts` and `Modules Updates`
![image](https://user-images.githubusercontent.com/16067358/157910428-674201a8-3bd1-4ff7-b9fb-6e3ab7aca3d6.png)
I did not find specs
https://github.com/PrestaShop/prestashop-specs/blob/master/content/1.7/back-office/modules/module-manager/alerts.md
https://github.com/PrestaShop/prestashop-specs/blob/master/content/1.7/back-office/modules/module-manager/updates.md

Ping  @prestascott what do you think?

Thanks!

**Comment by MeKeyCool** [comment]
> Hi @MeKeyCool,
> 
> I have the same behavior with PS1784 and PS1778. It is the same behavior for `Modules Alerts` and `Modules Updates` ![image](https://user-images.githubusercontent.com/16067358/157910428-674201a8-3bd1-4ff7-b9fb-6e3ab7aca3d6.png) I did not find specs https://github.com/PrestaShop/prestashop-specs/blob/master/content/1.7/back-office/modules/module-manager/alerts.md https://github.com/PrestaShop/prestashop-specs/blob/master/content/1.7/back-office/modules/module-manager/updates.md
> 
> Ping  @prestascott what do you think?
> 
> Thanks!

Sorry i don't know well the product yet but can we found this kind of "notifications" in other parts of PS ?
I think it should be interesting to define expected behavior and to list all places to update.

**Comment by TristanLDD** [comment]
Hello @MeKeyCool, thanks for your feedback! 

The behavior we want for the tabs notification alerts is indeed to hide them instead of showing "0" 
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello everyone,

It seems this issue has been fixed with PS811, see the attached screenshot below:

![image](https://github.com/PrestaShop/PrestaShop/assets/23308427/d49c14e5-2e55-488e-bd0a-91d59bfd342b)

Closing the issue :tada: 

Thanks!
