### ISSUE TITLE
Webservice Updating Product does not update Product Discount rules applied

### ISSUE THREAD

**Issue by RCallejo2** [PrestaShop/PrestaShop#27899]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Updating product categories using Webservices does not update product discount rules applied in product

### Expected behavior

Update product discounts for the product using rules applied

### Steps to reproduce

1. Create rule applied to Category
2. Create product with no Category
3. Add product category using webservices.
4. The poduct discount rules are not applied

### PrestaShop version(s) where the bug happened

1.7.8.4

### PHP version(s) where the bug happened

7.4.28

**Comment by hibatallahAouadni** [comment]
Hello @RCallejo2 

> 1.Create rule applied to Category

You mean "create a Catalog Price Rules"? Related to Category **C**, could you please provide a screenshot of the created Catalog Price Rule :pray: 

> 2.Create product with no Category

=> Create a product **P** and don't assign it to a Category **C**

> 3.Add product category using webservices.

Did you mean assign the created Product **P** to Category **C** via WebServices? If so, please provide the WebService that you used :pray: 
Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @RCallejo2 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
