### ISSUE TITLE
Non unique field name error in admin customer address

### ISSUE THREAD

**Issue by PseT** [PrestaShop/PrestaShop#27893]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I query a customer file in order in the admin, or if I click on the address menu

![Capture d’écran 2022-03-11 130739](https://user-images.githubusercontent.com/663883/157864111-14e313bd-bfc9-483c-862a-3dea3be624ba.jpg)

### Steps to reproduce

Go to admin clic on Customers -> Addresses

/index.php/sell/customers/1275/view?_token=PvqHMLiTNtpkBhbPaFCiracFGvzpYO-D4qsR6qRuH0A

### PrestaShop version(s) where the bug happened

1.7.8.4 after an upgrade from PS1751

### PHP version(s) where the bug happened

7.3

**Comment by khouloudbelguith** [comment]
Hi @PseT,

I did not manage to reproduce the issue with PS1784.
I attached a screen record

https://user-images.githubusercontent.com/16067358/157867952-b9db6e81-7c47-44ea-81be-020fa83e74db.mp4

Thanks to check and feedback.

**Comment by PseT** [comment]
Thanks, the error appeared after migrating from 1.7.5.1 to 1.7.8.3, so I updated to 1.7.8.4.
Could it be an error when updating ?

Regards,

**Comment by khouloudbelguith** [comment]
@PseT,

I tried an upgrade from PS1751 to PS1783 using the 1-click upgrade v4.14.0
It is ok :heavy_check_mark: 
I attached a screen record

https://user-images.githubusercontent.com/16067358/157898223-a835e86e-1268-4af1-b27f-5d4578510dda.mp4

After an upgrade to PS1783, I tried to re-upgrade to PS1784 => OK
I attached a screen record

https://user-images.githubusercontent.com/16067358/157899131-113d526c-d382-4baf-8512-839b33a9421b.mp4

Thanks to check and feedback

**Comment by PseT** [comment]
Thank you for your help, I don't understand where my problem can come from. I don't currently use any external modules.
Could be the cause of an old external module.

NOTE: I got a DB migration error at the end of the process.

I continue my research...

**Comment by khouloudbelguith** [comment]
@PseT, thanks!
Waiting for your feedback!

**Comment by PseT** [comment]
Do you know in which file this SQL query is located?
I think the following modification (add c. before date_add) solved my problem : ORDER BY c.date_add desc LIMIT 20

**Comment by hibatallahAouadni** [comment]
Hello @PseT 

Yes, that's exactly the problem! it should be `c.date_add`.
It seems that your issue is related to some overrides that you made or some third-modules.

We will close this issue as it is not a PrestaShop core bug.

Thanks!
