### ISSUE TITLE
Pixel FB events not being sent since v1.15.0 of ps_facebook module

### ISSUE THREAD

**Issue by Daaaaad** [PrestaShop/PrestaShop#27901]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

Since v1.15.0 of ps_facebook module (the official FB module for Prestashop, developed by PrestaShopCorp) browser events are no sent anymore.

When I look at the code the "printpixel.js" file that is supposed to send the addToCart event via the pixel is never included.

The result is a very bad "event match quality" between browser and server events having a huge impact on our campaigns.

I already tried multiple times to report the bug to support-facebook@prestashop.com but I'm always receiving the same automatic response with no real potential solution.

Could you please help 🙏 me report this problem to the dev team?

Regards,

David.

### Steps to reproduce

1. Upgrade ps_facebook module to v1.15.0 (or v1.16.0)
2. Add a product to the cart
3. No event is sent via the browser

### PrestaShop version(s) where the bug happened

1.7.6.8

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

ps_facebook

**Comment by hibatallahAouadni** [comment]
Hello @Daaaaad 

It seems that your issue is not a PrestaShop core bug.
If your module is `ps_facebook` Official, please contact support team on Addons

We will close this issue.

Thanks!

**Comment by Daaaaad** [comment]
Hi @hibatallahAouadni,

As I mentioned into the issue I already tried multiple times to contact the support team... without success.

The goal of this message is to raise some attention to this breaking change 😬

I any of you could transfer this info to the developers of the ps_facebook module before closing this ticket I would be very grateful ❤️

**Comment by Daaaaad** [comment]
@hibatallahAouadni Could you please transfer this bug to the ps_account's dev team? 🤔

**Comment by hibatallahAouadni** [comment]
Hello @Daaaaad 

I already transfer the problem to `ps_facebook` team :wink: 
They will contact you as soon as possible :pray:

Thank you for your patience and understanding.

**Comment by Daaaaad** [comment]
Than you very much @hibatallahAouadni 👍
