### ISSUE TITLE
Order created with "Payment error"

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#27902]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Order is created with `Payment error`:

![image](https://user-images.githubusercontent.com/15104724/153856665-ee78edcf-6c66-464b-8b37-f7e2eba59755.png)

### Expected behavior

Order created with a valid status

### Steps to reproduce

1. Set `0` decimals for a currency:

![image](https://user-images.githubusercontent.com/15104724/153855790-cb401d41-c5e6-4a33-a61c-5ccf49db01f0.png)

2. Set `Order status` as logable:

![image](https://user-images.githubusercontent.com/15104724/153856555-9ff31e3a-082f-458f-8e06-360a13fc6e7a.png)

3. Place an order with a product **above 999€**:

![image](https://user-images.githubusercontent.com/15104724/153856597-a61a1f00-6581-489a-85fc-23ce65b82c9c.png)

4. Order is created with `Payment error`:

![image](https://user-images.githubusercontent.com/15104724/153856665-ee78edcf-6c66-464b-8b37-f7e2eba59755.png)

### PrestaShop version(s) where the bug happened

1.7.8.4

**Comment by idnovate** [comment]
https://github.com/PrestaShop/PrestaShop/pull/27630

**Comment by hibatallahAouadni** [comment]
Hello @idnovate 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #26671. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #26671
