### ISSUE TITLE
Display of the login back-office page, conflict with chrome 99

### ISSUE THREAD

**Issue by dingedi** [PrestaShop/PrestaShop#27904]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![image](https://user-images.githubusercontent.com/64697405/158221581-61ac981b-93c0-45a4-9722-583a2fb60b24.png)

### Expected behavior

Display correctly

### Steps to reproduce

1. Use google chrome 99
2. Go to your back-office login page

### PrestaShop version(s) where the bug happened

1.7.8.3 (not tested others)

**Comment by matks** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/27835 😉

**Comment by dingedi** [comment]
whoops sorry.  I searched but I couldn't find
