### ISSUE TITLE
Login Page - Issue with lost password link on Chrome

### ISSUE THREAD

**Issue by tabularasadev** [PrestaShop/PrestaShop#27916]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello everyone.

Since several month, we encounter some strange issue on our Prestahop login page.

![bug_presta](https://user-images.githubusercontent.com/43845748/158390090-0747f360-fb3e-4188-8d2f-6dd48d092cf1.jpg)

As you can see, "Stay logged in" button and "Forgoten password" appear juste before connect button but they are unselectable.
This issue seams to appear on Chrome but no on Firefox.

Is this is just for me or is it a css issue for this news version ?

### Steps to reproduce

Acces to admin login form

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.3

**Comment by Hlavtox** [comment]
Already fixed on develop - you can implement fix to your install very easily, it's enough to change the TPL file. https://github.com/PrestaShop/PrestaShop/pull/27843/files

**Comment by tabularasadev** [comment]
Ok Thanks for this quick reply !

**Comment by marwachelly** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/27835
