### ISSUE TITLE
BO - An exception is displayed when editing a currency with a custom lanaguage

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27921]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An exception is displayed when editing a currency with a custom language.
This issue is reproduced only with PHP7.4
![image](https://user-images.githubusercontent.com/16067358/158412980-ab831d34-99cd-4e4f-93c3-df7e3d8ee06a.png)

I checked S1784 + php7.3 => ok
I checked develop + php7.3 => OK

I checked 1784 + php7.4 => NOK
I checked 1780 + php7.4 => NOK
I checked develop + php7.4 => NOK

Prestashop 1778 is not compatible with PHP7.4

### Steps to reproduce

1. Go to BO > International > Localization > Languages page
2. Create a new language like this 
![image](https://user-images.githubusercontent.com/16067358/158413193-d11c6a66-b89f-4fe8-98cc-4485859b53ed.png)
3. Change the employee language to this one created
4. Go to BO > International > Localization > currencies page
5. Edit a currency 
6. See error 

### PrestaShop version(s) where the bug happened

1.7.8.0, 1.7.8.4, develop

### PHP version(s) where the bug happened

7.4

**Comment by Progi1984** [comment]
Fixed by @jolelievre in #28821 and tested by @florine2623
