### ISSUE TITLE
"Disabled" modules are still displayed during the installation process

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#27930]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you change the name of the module directory, for example, from `autoupgrade` to `autoupgrade-off`, we shouldn't list it on the available modules to install.

### Expected behavior

We should only show the modules where the directory name matches the main module's file name.

### Steps to reproduce

1. before you install v8, change any module directory you want, from the original name to something else
2. go to the installer
3. see that the module is still displayed, but it shouldn't be

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

n/a

### If your bug is related to a module, specify its name and its version

n/a

**Comment by hibatallahAouadni** [comment]
Hello @kpodemski 

I changed the name of `ps_wirepayment` to `kp_wirepayment` and yet I can find the module in the list:

![image](https://user-images.githubusercontent.com/23308427/158571505-cfbd9fad-76e7-480a-92f8-2caccb87cd24.png)

And if I choose this option **Install all modules (recommended)**, the installation will be stopped in **Install modules** step:

![image](https://user-images.githubusercontent.com/23308427/158571807-2eabb2d5-f427-4642-87bc-8d023fdad483.png)

I’ll add this to the debug backlog.
Thanks for your PR :rocket:

**Comment by matks** [comment]
> When you change the name of the module directory, for example, from autoupgrade to autoupgrade-off, we shouldn't list it on the available modules to install.

@kpodemski ... why ? 😄 I'm not against this change but I wonder why we should exclude modules like this?

what if someone uses module directories like `mymodule_v2`?

**Comment by kpodemski** [comment]
@matks

1. module directory needs to match main module file name
2. very often devs change module name to, for example, -off to prevent using it

**Comment by matks** [comment]
@kpodemski As you've been using PrestaShop in production way longer than me, I'll trust you 😄 👍
