### ISSUE TITLE
Remove product from cart if customization and minimal quantity of 0 apply

### ISSUE THREAD

**Issue by Triloworld** [PrestaShop/PrestaShop#27939]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Adding customization on FO block from emptying cart. 
I like to clear cart with minimal quantity product and with customization

Commented code is where error occur:
<img width="782" alt="Zrzut ekranu 2022-03-16 o 14 52 56" src="https://user-images.githubusercontent.com/2671726/158605380-361f0e34-a338-46b9-abea-49f321f931c4.png">

Actual version of file on all Prestashop version is with same error: https://github.com/PrestaShop/PrestaShop/blob/5005657ed11f15e81c2d8cb5e4a855acd19213e1/controllers/front/CartController.php#L321

### Expected behavior

Clicking X/Trash on cart with customization remove product without warning

### Steps to reproduce

1. Add product "TEST" to prestashop BO with combination
2. Enable customization text on  "TEST" 
3. Require minimal quantity of 0 for  "TEST" in combination
4. In FO add custom text on  "TEST" and apply
5. Add to cart minimal quantity of  "TEST" 
6. Go to cart
7. Try to remove product from cart as you like to have empty cart
8. You get error of minimal quantity with block your cart from being empty

### PrestaShop version(s) where the bug happened

1.7.7.0

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

Core / No module involved

**Comment by hibatallahAouadni** [comment]
Hello @Triloworld 

I didn't manage to reproduce the issue with PS1778, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/158815959-2d921587-2019-49b2-a6e9-b49618cef18e.mp4

Please check and feedback.

Thanks!

**Comment by Triloworld** [comment]
Sorry. I use product with combinations. Maybe that is somehow connected to issue. I will update steps
PS. So much thank you for video. I don't know if that is enabled to be added

**Comment by Triloworld** [comment]
Yeah, I find why. I have "0" in minimal quantity. So not only I can add to cart but i get stuck in cart

**Comment by kpodemski** [comment]
@Triloworld minimal quantity should be 1 🤔

**Comment by Triloworld** [comment]
Panel won't block that and it isn't working after switching back.
I embed from my site video: https://youtu.be/6zVvxxyEQKc (hd quantity is in process to be added)
I show on first part isn't working and second part after empty basket it work for new one so setting can break basket and nothing from frontend and backend stop to setup 0 as minimal quantity 

What I suggest is to get option to remove product FULL in any scenario that way any option on minimum quantity won't block emptying cart

**Comment by HanaRebaiQA** [comment]
Hello @Triloworld 

Thanks for your report.
Your issue seems to be similar to this one [#18850](https://github.com/PrestaShop/PrestaShop/issues/18850). Do you confirm it ?

Thank you !

**Comment by Triloworld** [comment]
This one is about having customized product in cart and trying to remove It despite fact of changing quantity. Different place in code that block remove It from card and will stay even if #18850 will be fixed. I added screenshoot (line 304 is different from linked issue) where product is blocked from future processing

**Comment by Triloworld** [comment]
Example:
- you somehow have put 0 in this place
- some cart is created with more than 0 quantity (this is different place)
- you fix that 0 to proper number of 1 after update or after finding alone
- carts stuck as they aren't removed because of "product customization" have "if" added that have different logic and now client with cart between login must get removed

**Comment by florine2623** [comment]
Hello @Triloworld ,

I can't reproduce your issue following the steps you provided. Please check my screen record in PS 1.7.8.5 :

https://user-images.githubusercontent.com/16019289/159454571-d43bb439-dcb0-4023-8e9c-65d9f2a3d94d.mov
Deleting the product or putting quantity to 0 results in an empty cart 

I can't reproduce it on either 1.7.7.8 nor develop branch.
So I will close your issue.

**Comment by Triloworld** [comment]
Yeah, it was by ajax request (when send from Postman to test). You are right. Thats not the bug. Thank you @florine2623 and everybody involved
