### ISSUE TITLE
Importing products changes the default category

### ISSUE THREAD

**Issue by roskrzysztof** [PrestaShop/PrestaShop#27938]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When importing additional data into existing products, e.g. the ean code changes the default category to 2, i.e. the main

Use the product index as a key -> ON
File CSV -> index # | EAN
After importing, all products have default main category id 2

### Steps to reproduce

1. Import product 
2. Use the product index as a key -> ON 
3. File CSV: index | EAN

### PrestaShop version(s) where the bug happened

1.7.7.8

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @roskrzysztof 

You should downgrade your PHP version to 7.3, cause PS1778 is not compatible with PHP 7.4 (see our [system requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart)).
Could you please check this issue #22235 seems similar to yours.
Waiting for your feedback.

Thanks!

**Comment by roskrzysztof** [comment]
After changing the php version to 7.3, the problem still exists. 
The effect is as if it took a category column that is empty. And in csv there are only two columns INDEX # | EAN

**Comment by hibatallahAouadni** [comment]
Hello @roskrzysztof 

Could you please provide a screenshot or screenshots :pray: 
And did you verify the issue I mentioned in my comment above?
Waiting for your feedback.

Thanks!

**Comment by roskrzysztof** [comment]
File csv:
`index;ean
4932459097;4002395283101`

![Opera Zrzut ekranu_2022-03-16_170512_new2021 narzedziadlafachowca pl](https://user-images.githubusercontent.com/9614897/158634576-61962ede-e44f-4df5-8e6d-9a527b406586.png)
![Opera Zrzut ekranu_2022-03-16_170819_new2021 narzedziadlafachowca pl](https://user-images.githubusercontent.com/9614897/158635106-d9b56ac6-ffee-4e5c-9c1b-c325befe36ff.png)
![Opera Zrzut ekranu_2022-03-16_170938_new2021 narzedziadlafachowca pl](https://user-images.githubusercontent.com/9614897/158635421-03cbe088-8a87-4bf2-a768-7f85a4f084ae.png)
![Opera Zrzut ekranu_2022-03-16_171004_new2021 narzedziadlafachowca pl](https://user-images.githubusercontent.com/9614897/158635524-5ec6e7c1-37b2-4d2e-8e13-5a48c637a051.png)
![image](https://user-images.githubusercontent.com/9614897/158635875-d3cfe4b5-1ee7-4b48-b6c3-df017d7e1e0f.png)
![Opera Zrzut ekranu_2022-03-16_171811_new2021 narzedziadlafachowca pl](https://user-images.githubusercontent.com/9614897/158637278-71697299-ef0f-4948-bb17-34408cd03cb1.png)


And did you verify the issue I mentioned in my comment above? -> YES

**Comment by HanaRebaiQA** [comment]
Hello @roskrzysztof 

Thanks for your feedback!
First, I would know if the issue mentionned above is similar to yours ?
Then, could you please change your shop to English to can understand more your screenshots.

Thank you!

**Comment by roskrzysztof** [comment]
It is not similar, there the problem was with prices and tax id.

Before import
![image](https://user-images.githubusercontent.com/9614897/159029097-80b24942-9643-4ecb-8e38-b70fb175892b.png)
![image](https://user-images.githubusercontent.com/9614897/159029420-cc125dd2-34d8-4653-9276-cac3e0a881a5.png)

Imports from csv file
![image](https://user-images.githubusercontent.com/9614897/159029808-437ddf1c-3569-4306-8756-6ab0db7d2a4b.png)
![image](https://user-images.githubusercontent.com/9614897/159029946-9dacb650-d99e-468c-9270-53660537afda.png)
![image](https://user-images.githubusercontent.com/9614897/159030007-36b194cd-1fb6-4c15-8814-1b85aac04bac.png)

After import, it changes the default category to the main one
![image](https://user-images.githubusercontent.com/9614897/159030256-d8289cf6-775e-426e-8e38-e9f7676b9e51.png)
![image](https://user-images.githubusercontent.com/9614897/159030562-3ebfdaef-91e3-4b57-962f-4c0eedde6b05.png)

Only the EAN should change the product and the rest should remain unchanged.

**Comment by HanaRebaiQA** [comment]
Hello @roskrzysztof 

I was unable to reproduce your issue with PS1778 
-Create a new product with Category (`Stationery` in my case) 
-Import new data for Products with the same configuration that you used
-Check again the category of the created product : OK

https://user-images.githubusercontent.com/92912932/159037637-f649b33c-f627-4959-882a-7da3cf80c2b2.mp4


Could you please check again and feedback please ?

Thank you!

**Comment by roskrzysztof** [comment]
Please do this now on the basis of your product 'ref_hana'.
1. create a csv file with two columns: 'ref_hana';'4002395283101' and import as such
![image](https://user-images.githubusercontent.com/9614897/159042814-c92c1688-42b4-4dbf-b4fd-56f6ae966ee1.png)

2. and check if it has changed the default category

**Comment by hibatallahAouadni** [comment]
Hello @roskrzysztof 

Thanks for your patience :pray: 
We are aware of this issue, it is already fixed in our debug backlog (the next patch release 8.0.0). 
This issue is a duplicate of #22336. 

Thank you

**Comment by hibatallahAouadni** [comment]
Duplicate of #22336
