### ISSUE TITLE
Category controller should not hardcode a layout tpl

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#27946]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The front Category controller call 'layouts/layout-full-width.tpl' here:
https://github.com/PrestaShop/PrestaShop/blob/5005657ed11f15e81c2d8cb5e4a855acd19213e1/controllers/front/listing/CategoryController.php#L165

So, if the theme doesn't have this layout this line raise a SmartyException if the category is inactive or unauthorized

### Expected behavior

no exception

### Steps to reproduce

- Delete or rename layouts/layout-full-width.tpl in your theme
- Change the default layout un theme.yml to another layout (layout-left-column by example)
- Remove the full layout in available_layouts section of the theme.yml
- Reset the theme in the bo (in debug mode)
- Back Office : Choose a category
- Front Office : Go to this category page in front
- Back Office : Disable this category 
- Front Office : Reload this category page in front 
![image](https://user-images.githubusercontent.com/1533248/163177112-3a97e48e-8918-4434-8fd5-fbbcaf0a1f9e.png)

### PrestaShop version(s) where the bug happened

1.7.8

### PHP version(s) where the bug happened

all

**Comment by hibatallahAouadni** [comment]
Hello @jf-viguier 

Could you please provide a simple theme to reproduce this behavior :pray: 
Waiting for your feedback.

Thanks!

**Comment by jf-viguier** [comment]
@hibatallahAouadni hello,
You can use classic theme and remove the file : layouts/layout-full-width.tpl

**Comment by HanaRebaiQA** [comment]
Hello @jf-viguier 

Could you please provide us more information about the second step `call an inactive or unauthorized category page` ? 
We should use an api for that ? and could you please provide us a screen-shot or screen-record to can reproduce it clearly ?

Thank you!

**Comment by jf-viguier** [comment]
- choose a category
- go to this category page in front
- Desactivate this category 
- Reload this category page in front

Do the same with an inaccessible category (with customer groups)

**Comment by matks** [comment]
@jf-viguier I think I understand the issue.

In classic theme we have file layout-full-width.tpl

https://github.com/PrestaShop/classic-theme/blob/develop/templates/layouts/layout-full-width.tpl

What you mean is that, if someone uses another theme, and that other theme does not have a file `layout-full-width.tpl`, this code will not work is that right?

But is that a bug, or is it simply that a theme _has the obligation_ to provide this file to work? What would it be different for this file and not for another like page.tpl ?

**Comment by jf-viguier** [comment]
> What you mean is that, if someone uses another theme, and that other theme does not have a file layout-full-width.tpl, this code will not work is that right?

@matks yes
layout-full-width.tpl means that the theme has to implement a full width layout, it's a presentation concern that should not be in the controller (MVC concept).
BTW, this code has no effect, remove it and nothing change : see my PR.
BTW, there are tpl for errors.

**Comment by Progi1984** [comment]
@jf-viguier & @hibatallahAouadni I updated the `How to test ?`. Are you agree with this one ?

**Comment by hibatallahAouadni** [comment]
Thanks @Progi1984 :pray: I will try to reproduce the issue with these new steps :wink:

**Comment by HanaRebaiQA** [comment]
Hello @jf-viguier 

I did reproduce your issue on PS1785 when i renamed the `layout-full-width.tpl `file
Go to FO ==> An exception is thrown
![image](https://user-images.githubusercontent.com/92912932/163568548-05965a6e-ac3e-481a-a6c3-64ca6bdf2b5f.png)

**PS1785**

https://user-images.githubusercontent.com/92912932/163568519-37cde7bd-45c5-479b-8dc2-2e1cd2491c56.mp4

I could also reproduce the issue with PS1778, So it's not a regression!

**PS1778**

https://user-images.githubusercontent.com/92912932/163568724-86707400-372a-49d5-bc03-384d70a8ebd7.mp4

Thank you for your PR. We will come back to you with our QA feedback as soon.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @jf-viguier 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by jf-viguier** [comment]
@hibatallahAouadni hello,
Why have you closed this issue ? I've made a PR and updated the "how to test" after a dusscition with @HanaRebaiQA

**Comment by hibatallahAouadni** [comment]
Hello @jf-viguier 

As discussed on Slack, I will reopen the issue as `TBR` till you provide a screen record.

Thanks for your understanding :pray:

**Comment by jf-viguier** [comment]
I've updated the how to test to be more precise:
"- Change the default layout un theme.yml to another layout (layout-left-column by example) and reset the theme in the bo (in debug mode)"
![image](https://user-images.githubusercontent.com/16720275/169998760-b9c524d6-fb69-4d5f-9321-d5bc44ddd3b5.png)

**Comment by sLorenzini** [comment]
Hello @jf-viguier,

I reproduce the issue with PrestaShop:

- ps 8.0.0 (develop branch)
- ps 1.7.8.6 (1.7.8.x branch)
- ps 1.7.7.8

I'll add this to the backlog so it can be fixed.
Thanks again for your PR :rocket: 

Thank you

**Comment by jf-viguier** [comment]
@sLorenzini please check my pr that fix this bug 
https://github.com/PrestaShop/PrestaShop/pull/27947

**Comment by jf-viguier** [comment]
> Please be aware that some issues might take a very long time to be resolved.

thanks to the community ;-)
