### ISSUE TITLE
Missing translations on psgdpr module

### ISSUE THREAD

**Issue by micka-fdz** [PrestaShop/PrestaShop#27942]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Missing default translations on `psgdpr` module page in FO.
These translations can still be added to the BO.

### Steps to reproduce

1. Install `psgdpr` module
2. Change language (to French for example)
3. Go to module page on customer account
4. See missing default translations

### PrestaShop version(s) where the bug happened

1.7.x.x

### If your bug is related to a module, specify its name and its version

psgdpr (all versions)

https://user-images.githubusercontent.com/50865159/159035754-47f9f539-598f-4b4a-9915-8972b84f6a16.mov

**Comment by hibatallahAouadni** [comment]
Hello @micka-fdz 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #20526. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #20526

**Comment by micka-fdz** [comment]
Hi @hibatallahAouadni, my issue isn't related to https://github.com/PrestaShop/PrestaShop/issues/20526 at all.
Mine is about translations on customer account page of module.

**Comment by hibatallahAouadni** [comment]
@micka-fdz could you please provide some screenshots :pray:

**Comment by micka-fdz** [comment]
![image](https://user-images.githubusercontent.com/50865159/158783836-56288860-d093-49db-991e-a83844fe548c.png)

**Comment by hibatallahAouadni** [comment]
Indeed it's a duplicate of this one #22796

**Comment by hibatallahAouadni** [comment]
Duplicate of #22796

**Comment by hibatallahAouadni** [comment]
Thanks for all details @micka-fdz I reopen the issue :wink: 
@PrestaShop/prestashop-core-developers wdyt of this issue? isn't the expected behavior?

**Comment by hibatallahAouadni** [comment]
Hello @micka-fdz 

I was able to reproduce the issue with PS1767, PS1778 and PS1785 on Fresh install, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/159929890-d4e6475e-82dc-4c9d-8e8d-86bbbbe3ae7e.png)

I’ll add this to the debug backlog so that it’s fixed. Thanks for your PR :rocket: 

PS: this issue can be fixed by clearing cache and re-save the traslations on BO.

Thank you
