### ISSUE TITLE
BO - Add new order - the Description of the voucher is not correct

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#27951]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Orders > Add new order > the description of the voucher is not correct, the name is displayed  instead of the exact description
This issue is reported by @nesrineabdmouleh 
![image](https://user-images.githubusercontent.com/16067358/158851555-67de363c-ff31-4d7b-ab1e-e35e43e8d72a.png)

### Steps to reproduce

1. Go to BO > Catalog > Discounts > Cart rules page > Add new cart rule with a specific name & description 
![image](https://user-images.githubusercontent.com/16067358/158851728-dde7481b-1835-477f-8a27-3bacc53a7ac4.png)
2. Go to BO > Orders > Add new Order > choose a customer & search a product
3. In the Voucher block, apply the cart rule created 
4. See error: the description is NOK ![image](https://user-images.githubusercontent.com/16067358/158851555-67de363c-ff31-4d7b-ab1e-e35e43e8d72a.png)

### PrestaShop version(s) where the bug happened

1.7.7.8

### PHP version(s) where the bug happened

7.0

**Comment by buggyzap** [comment]
Hi, I found 2 solution for this, which is better @Progi1984 @matks ? I will create a new PR with best solution.

A problem is the retro-compatibility line that override the **description** field with **name** in Cart class line 538.
```
// Retro compatibility < 1.5.0.2
$row['id_discount'] = $row['id_cart_rule'];
$row['description'] = $row['name'];
```

We can add a PS_VERSION check on this and prevent the override, or also edit this line of 
/prestashop/src/Adapter/Cart/QueryHandler/GetCartForOrderCreationHandler.php from

```
foreach ($legacySummary['discounts'] as $discount) {
    $cartRuleId = (int) $discount['id_cart_rule'];
    $cartRules[$cartRuleId] = new CartForOrderCreation\CartRule(
        (int) $discount['id_cart_rule'],
        $discount['name'],
        $discount["description"],
        (new DecimalNumber((string) $discount['value_tax_exc']))->round($currency->precision)
    );
}
```
to 

```
foreach ($legacySummary['discounts'] as $discount) {
    $cartRuleId = (int) $discount['id_cart_rule'];
    $cartRules[$cartRuleId] = new CartForOrderCreation\CartRule(
        (int) $discount['id_cart_rule'],
        $discount['name'],
        $discount["obj"]->description,
        (new DecimalNumber((string) $discount['value_tax_exc']))->round($currency->precision)
    );
}
```

using object property instead of array.

**Comment by Progi1984** [comment]
@buggyzap You can remove the retrocompatibility with the version 8.0 so don't worry about that.

**Comment by matks** [comment]
> @buggyzap You can remove the retrocompatibility with the version 8.0 so don't worry about that.

Little disagreement here 😄  : yes we can introduce BC breaks in 8.0.0 but that does not mean we can break everything. Each not backward compatible change must be analyzed to understand the impact

**Comment by SharakPL** [comment]
@matks can I ask what's the reason for keeping compatibility with PS 1.5 in PS 1.7/8.x?

**Comment by kpodemski** [comment]
@SharakPL it's not what @matks said, he said: 

> we can introduce BC breaks in 8.0.0 but that does not mean we can break everything. Each not backward compatible change must be analyzed to understand the impact

:)
