### ISSUE TITLE
Customer Account / Order History ContextErrorException when it crashed during order creation

### ISSUE THREAD

**Issue by NicolasCador** [PrestaShop/PrestaShop#27967]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When an order is missing in table ps_order_history due to a crash during order creation, and when customer wants to see his/her order history, today, it gives a "ContextErrorException : Trying to access array offset on value of type null", because $orderState becomes null and so $orderState['name'], $orderState['invoice'], $orderState['color'] can't exist. By using Null Coalescing Operator instead of Ternary Operator, we avoid the error.

### Expected behavior

It should show the list of Orders

I proposed a new code here : [https://github.com/PrestaShop/PrestaShop/pull/27179](https://github.com/PrestaShop/PrestaShop/pull/27179)

### Steps to reproduce

1. Make an order in FO using customer ZJA
2. Remove its SQL lines from table ps_order_history table
3. Then browse customer account ZJA, click on order history.

### PrestaShop version(s) where the bug happened

1.7.8.4

### PHP version(s) where the bug happened

7.4

**Comment by HanaRebaiQA** [comment]
Hello @NicolasCador 

Thanks for your report.
Could you please specify what do you mean by `customer ZJA` ? And could you please provide us a screen-record / screenshots to can repoduce it ?

Thanks !

**Comment by NicolasCador** [comment]
Hello @HanaRebaiQA 

customer ZJA means any customer

There isn't any screenshot, it's internal, if you had a crash during order creation for any reasons, the data in the database (table ps_order_history) are not fully Ok, and when you go in Order History in your Account, there is a ContextErrorException.

To simulate a crash during order creation, you can create an order and remove its SQL lines from table ps_order_history.

**Comment by florine2623** [comment]
Hello @NicolasCador ,

I can't reproduce you issue on PS 1.7.8.5. Please check my screen record :

https://user-images.githubusercontent.com/16019289/159452389-1e341c59-cce2-4885-9939-31f1d1a902b7.mov

Is there another step I missed ?
Thanks!

**Comment by NicolasCador** [comment]
Hello @florine2623 ,

good idea the screen record, I should have done that. I understood screenshots, sorry.

in fact, the problem isn't in the BO, it's in the FO when the Customer wants to see his/her order history, today, it gives a "ContextErrorException : Trying to access array offset on value of type null".

in this configuration you did in the screen record, if you go in the FO, in your account, and click on history orders, you'll see the error.

**Comment by HanaRebaiQA** [comment]
Hello @NicolasCador 

I checked your issue with **PS1785** and **PS1784** and i was unable to reproduce it with php7.2 and php7.3
But, i'm able to reproduce it only with **php7.4**

1. Make an order in FO with my customer
2. Remove its SQL lines from table `order_history `table
3. Go to FO again and check the Orders page
4. See error 

![image](https://user-images.githubusercontent.com/92912932/159720718-7c02cb1e-9053-45cb-8fb6-bb034c4c2c14.png)

1784 with php 7.4 :NOK :x: 

https://user-images.githubusercontent.com/92912932/159720983-5c732e49-be58-462c-aa13-66ebd6c6e305.mp4

1785 with php 7.4 :NOK :x: 

https://user-images.githubusercontent.com/92912932/159721130-dcdb1799-f686-48ac-9059-3f0881900898.mp4


1784 with php 7.2 : OK 

https://user-images.githubusercontent.com/92912932/159721291-718d9459-7725-485d-b2e7-acb771537ade.mp4

1785 with php 7.3 : OK

https://user-images.githubusercontent.com/92912932/159723166-30874ff3-24a1-4619-9771-8e0b48f50e51.mp4

So, it's a regression cause it's only appearing with **php7.4** 

Good for the PR.

Thank you!

**Comment by NicolasCador** [comment]
Hello @HanaRebaiQA ,

ok, thank you, great job of investigation !

I thought it was a problem from PHP 7.3 to 7.4, but I was not sure.

So finally it appeared when I switched to PHP 7.4 after Prestashop 1.7.8 migration.

**Comment by NicolasCador** [comment]
Hello all, I created a new Pull Request in the right branch 1.7.8.x : https://github.com/PrestaShop/PrestaShop/pull/28117

**Comment by kpodemski** [comment]
@matks I think it was fixed in 1.7.8.6?
https://github.com/PrestaShop/PrestaShop/pull/28117
