### ISSUE TITLE
Add the possibility to load PHP resources files in modules

### ISSUE THREAD

**Issue by intraordinaire** [PrestaShop/PrestaShop#27968]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Today, we can't load a PHP service file.
They can be useful sometimes if we want to add some logic when registering services.

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/1721887/159026189-d43ffc40-8bad-442c-8f7a-312a3ff29f67.png">

This happens when i just add 
```yaml
imports:
    - { resource: services.php }
```
In `my_module/config/services.yml`

### Describe the solution you'd like

As I understand, in the [LoadServicesFromModulesPass.php](../blob/develop/src/PrestaShopBundle/DependencyInjection/Compiler/LoadServicesFromModulesPass.php#L70), the `YamlFileLoader` is built, but there is no other [FileLoader](https://symfony.com/doc/4.4/components/config/resources.html) in it.

Maybe we can add the `PhpFileLoader` and `XmlFileLoader` to be able to load "classics" Symfony resources files.

>Edited by Hana
[prestashopexamplemodule (1).zip](https://github.com/PrestaShop/PrestaShop/files/8306130/prestashopexamplemodule.1.zip)

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by HanaRebaiQA** [comment]
Hello @intraordinaire 

Thanks for your report.
I was able to reproduce the issue using the same module that you attached in the PR.
![image](https://user-images.githubusercontent.com/92912932/159040963-937ba4fe-98f3-45a0-b503-33e517c88012.png)

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

And, thank you for your PR.

Thank you!

**Comment by matks** [comment]
I think this is rather a topic to be validated by dev as it is a developer feature 😄  (and my opinion is: YES ! it's a great idea)

**Comment by matks** [comment]
I approve this idea
