### ISSUE TITLE
Problem on the quickview when quantity or selection are changed - show all modules of displayProductAdditionalInfo

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#27977]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi
today Iìve upgraded to 1.7.8.5 my demo site and I've seen this bug
opening the quickview and changing the quantity or the combination, all modules that use displayProductAdditionalInfo will be shown in the quickview

now I've seen another strange behavior, on the virtual products I get "undefined"

the good thing is that it only happens in the classic theme of this demo site, in real sites with themes taken from addons I don't see any problems.
I think they came out in the latest versions of prestashop, because I only realized it now

bye

https://watch.screencastify.com/v/Ji55nVCePjjXV5P43kD0

![2](https://user-images.githubusercontent.com/653230/159118276-f0a08c01-612b-4abe-8df5-caef7680691a.png)
![3](https://user-images.githubusercontent.com/653230/159118277-580d1ff2-8f45-4082-890c-b235d425e894.png)
![9](https://user-images.githubusercontent.com/653230/159118552-c2e236dd-44f3-47eb-aab7-a210264c9a75.png)

### Steps to reproduce

1. open a quickview of a product
2. change the quantity or a selection

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Hello @maofree 

I didn't manage to reproduce the issue with PS1785 and PHP7.3, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/159313053-f8fc12cc-7b9b-4a98-9827-1f307b8d4d06.mp4

Did you hook other modules in this hook?

![image](https://user-images.githubusercontent.com/23308427/159313942-7d7b2431-03a4-4dfb-acc0-f833cedb4c1d.png)

Waiting for your feedback.
Thanks!

**Comment by Maofree** [comment]
Hi
to be sure, I need to reinstall my demo website and check again

**Comment by hibatallahAouadni** [comment]
Ok waiting for your feedback :wink:

**Comment by Maofree** [comment]
Hi
I've installed a new 1.7.8.5 on my local server, I confirm the bug
it is necessary to use a different module because the social module is the default one and already managed by the quickview

https://watch.screencastify.com/v/qPVCTDZKFeKHNoqXrPhc

I pass my module from Slack, because I don't want to share it here

bye

**Comment by Maofree** [comment]
I've found the solution

https://devdocs.prestashop.com/1.7/modules/core-updates/1.7.7/#product---quick-view-mode

I close this topic

bye

**Comment by Maofree** [comment]
this code is also no more used from 1.7.7.0?

`Tools::getValue('action') == 'refresh'`

**Comment by Maofree** [comment]
![3](https://user-images.githubusercontent.com/653230/159360232-07335d8b-87f2-43f0-8558-39bc3d760339.png)
![11](https://user-images.githubusercontent.com/653230/159360242-a4e67758-a865-4735-807e-2837e12b713d.png)

I continue to get this errors from the quickview of demo virtual products and pack products

can you check if it is normal?

I need to create a new bug report?

**Comment by florine2623** [comment]
Hello @maofree ,

I can't reproduce your error on virtual product or pack.

https://user-images.githubusercontent.com/16019289/159450212-33272cda-3ea4-46d7-b929-643299b99662.mov

>this code is also no more used from 1.7.7.0?
Tools::getValue('action') == 'refresh'

You could create a new issue as a Feature Request.

Thanks!

**Comment by Maofree** [comment]
Hi
today I don't get that error "undefined"
