### ISSUE TITLE
Translation of theme does not load default translation catalogue

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#27970]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I added some new wording in my template. I want to translate the phrases.
When I select to translate the theme, it displays all translations as missing, even though most of them are already translated in the core.

### Expected behavior

I expect that all the wording that are already translated in the core are pre-filled. This allows me to concentrate on the few wording that are missing. 

### Steps to reproduce

1. In the BO go to `International - Translations`
2. Choose 
   - Type of translation : Front office translation
   - Select your theme : select an installed theme different from `classic`
   - Select your language
![Capture d’écran 2022-03-18 172329](https://user-images.githubusercontent.com/7520695/159043456-9bc66f5d-d693-4327-83e4-211bb8d923b8.png)
3. Note that all the texts of the theme are displayed as missing
![Capture d’écran 2022-03-18 172418](https://user-images.githubusercontent.com/7520695/159043551-c7211e32-cea6-4cb8-8a24-77b33c4c8f74.png)

### PrestaShop version(s) where the bug happened

1.7.8.4

### PHP version(s) where the bug happened

7.3

**Comment by lmeyer1** [comment]
I found the bug, PR is coming. With the fix, the expected is happening:
![Capture d’écran 2022-03-18 173445](https://user-images.githubusercontent.com/7520695/159044627-f2671d4b-4133-4d7a-8aca-9b197c19c286.png)

**Comment by lmeyer1** [comment]
Duplicate of #27410

**Comment by matks** [comment]
@lmeyer1 duplicate or not duplicate 😁 ?

**Comment by lmeyer1** [comment]
Yes, it's entirely a duplicate.

**Comment by hibatallahAouadni** [comment]
Duplicate of #27410

**Comment by hibatallahAouadni** [comment]
Thanks @lmeyer1 for your PR :rocket:
