### ISSUE TITLE
Bug affichage attribut

### ISSUE THREAD

**Issue by MEGA911** [PrestaShop/PrestaShop#27988]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

https://www.lecornerdesophie.com/kure-bazaar/845-1199-vernis-a-ongles-ecologiques-2#/133-couleur_2-b

Bonjour, j'ai un bug qur les fiches produits de mon site => Lorsque je change de couleur Rouge ou noir => L'attribut de couleur ne change pas => J'ai cette erreur d'affichage sur tous les produits à variation de mon site => Pouvez-vous m'aider à corriger ce bug.

### Expected behavior

Pouvez-vous m'aider à corriger ce bug.

### Steps to reproduce

https://www.lecornerdesophie.com/kure-bazaar/845-1199-vernis-a-ongles-ecologiques-2#/133-couleur_2-b
Cliquez sur la couleur Noir ou rouge et vous allez voir que le texte => Couleur 2 => Ne varie pas si vous cliquer sur l'autre couleur

J'ai cette erreur d'affichage sur tous les produits à variation de mon site
ex : https://www.lecornerdesophie.com/oceopin/624-924-huile-visage-repulpante-serum
l'attribut Contenance : => Ne varie pas => Il reste bloquer sur Contenance : 30ml (La variation par défaut )

### PrestaShop version(s) where the bug happened

1.7.6.3

### PHP version(s) where the bug happened

7.3.32

**Comment by hibatallahAouadni** [comment]
Hello @MEGA911 

Please send your request in English. English is the norm on GitHub.
Please downgrade your PHP version to 7.2, cause the PS1763 is not compatible with PHP7.3 (see our [system requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart)).

Thank you

**Comment by MEGA911** [comment]
Ok I test to downgrade to PHP 7.2

**Comment by MEGA911** [comment]
It's done => But i have the same bug

**Comment by MEGA911** [comment]
https://www.lecornerdesophie.com/kure-bazaar/845-1199-vernis-a-ongles-ecologiques-2#/133-couleur_2-b
Click on the color Black or red and you will see that the text => Color 2 => Does not vary if you click on the other color

I have this display error on all variation products on my site
ex: https://www.lecornerdesophie.com/oceopin/624-924-huile-visage-repulpante-serum
the Capacity attribute: => Does not vary => It remains blocked on Capacity: 30ml (The default variation)
