### ISSUE TITLE
When an Exception is thrown with a string code, there is a fatal error

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#27982]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Like DBPdo that will throw this error: 

- SQLSTATE[42S22]: Column not found: 1054 Unknown column '%s' in 'where clause'"
- Error code: 42S22

As you can see, the error code is not an integer but a string.
As we have a strict type and that Exception need an int as the $code paramterers, it's throw a fatal error.

<img width="746" alt="Capture d’écran 2022-03-20 à 22 29 39" src="https://user-images.githubusercontent.com/2631425/159186746-13642795-2466-4e30-9b9f-4db67fe830fc.png">

### Steps to reproduce

1. Make a select with a missing colum into the where clause (use DbQuery for that)
2. See the fatal error

---

1. Install this module [test.zip](https://github.com/PrestaShop/PrestaShop/files/8464689/test.zip)
2. Go to FO
3. See error

![image](https://user-images.githubusercontent.com/23308427/162754674-70124d66-6700-4462-8e77-052f7e8bde9f.png)

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

This issue is too technical for me :sweat_smile: 
So, ping @PrestaShop/prestashop-core-developers could someone please try to reproduce the issue :pray: 

Thanks in advance!

**Comment by PrestaEdit** [comment]
Hi @hibatallahAouadni ,

There is a quick module as example, you can install it and see the same error on the Front Office :)
[test.zip](https://github.com/PrestaShop/PrestaShop/files/8318302/test.zip)

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

Thanks for your test module :pray: :relaxed: 
I reproduce the issue with develop, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/162754674-70124d66-6700-4462-8e77-052f7e8bde9f.png)

But I need to check if this issue is a regression :wink: 
When I try to install your module, an exception is thrown:

![image](https://user-images.githubusercontent.com/23308427/162754828-54354833-5a01-49a2-bdf7-3cd34edd4bb1.png)

Could you please edit your module so it will be compliant with PS1778 and PS1785 :pray: 
Thanks in advance!

**Comment by PrestaEdit** [comment]
Hi @hibatallahAouadni ,

There is:
[test.zip](https://github.com/PrestaShop/PrestaShop/files/8464689/test.zip)

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

Thanks for your quick reply :rocket: 
But I encounter another issue:

![image](https://user-images.githubusercontent.com/23308427/162756397-a1f18b96-0eb0-44e2-ad0e-efe295ac22de.png)

Please check and feedback.
Thanks!

**Comment by PrestaEdit** [comment]
Hi @hibatallahAouadni , are you sure that it's not simple the same error ? Do you have enable the debug mode on this URL ?

**Comment by hibatallahAouadni** [comment]
@PrestaEdit Yes, I did! I enabled the debug mode and yet I get this error :disappointed:

**Comment by PrestaEdit** [comment]
It's strange. I've just tested it and the error is the same (issue with the query) here, for me.

**Comment by PrestaEdit** [comment]
I see, I update the module. I've make it stricts about code
[test.zip](https://github.com/PrestaShop/PrestaShop/files/8464820/test.zip)
.

**Comment by PrestaEdit** [comment]
But you can't use it, as the issue is the strict_types, use on PHP8. The issue is with PHP8.

**Comment by jolelievre** [comment]
Hi @PrestaEdit 

I'm sorry but your screenshots and stack traces don't match the problem you are mentioning
I kind of see that there is a code `42S22` but I don't understand where it comes from, it seems to be coming from PDT functions no?

**Comment by PierreRambaud** [comment]
The code ` 42S22`  comes from the Mysql database: https://stackoverflow.com/questions/32159465/error-1054-42s22-unknown-column-marks-in-field-list
`PDOException`  are handled by PHP itself, I see no issue related to PrestaShop here :thinking:

**Comment by PrestaEdit** [comment]
The issue is with PHP8, PrestaShop 8. The strict type will throw a Fatal error.

The issue is not the code itself, it's due to the fact that it's a string and that we're awaiting an int (so, it's not match the strict type).

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

Even @sLorenzini encountred another issue with the latest test module that you provide, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/162760882-fbb5ae8b-0f36-44b0-ba7c-b0e78902b247.png)

PS: @jolelievre & @PierreRambaud thanks guys for your quick replies :rocket: 

Thanks!

**Comment by PierreRambaud** [comment]
I'm using PHP8, I don't manage to reproduce the issue:
![image](https://user-images.githubusercontent.com/1462701/162763047-a4bf5862-b320-4732-9714-816c2d12d2d6.png)
![image](https://user-images.githubusercontent.com/1462701/162763290-40951ef0-2140-4800-ab08-eead55a17d90.png)

This kind of thing is fully manage by PHP itself: https://github.com/php/php-src/blob/master/ext/pdo/pdo_dbh.c#L38

**Comment by PrestaEdit** [comment]
Are you using it onto the actual develop branch and with my first zip (with the declare strict type enabled) ?
The issue, is the fatal error due to the string code, and Exception awaiting an int. (https://www.php.net/manual/fr/class.exception.php#exception.props.code)

**Comment by PierreRambaud** [comment]
Yes, I'm using the latest changes on the develop branch. Anyway, this is something which is handled by PDO itself, nothing related to the Core :thinking: 
ping @atomiix

**Comment by atomiix** [comment]
I think I've been able to reproduce the issue:
<img width="1081" alt="Capture d’écran 2022-04-12 à 10 24 21" src="https://user-images.githubusercontent.com/2168836/162916027-b51d0a35-0707-4ded-9774-d74527021c29.png">

**Comment by atomiix** [comment]
And a useful comment from 12 years ago: https://www.php.net/manual/fr/class.pdoexception.php#95812 😅
