### ISSUE TITLE
BUG Variations 

### ISSUE THREAD

**Issue by MEGA911** [PrestaShop/PrestaShop#27989]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

https://www.lecornerdesophie.com/kure-bazaar/845-1199-vernis-a-ongles-ecologiques-2#/133-couleur_2-b
Click on the color Black or red and you will see that the text => Color 2 => the text Does not vary if you click on the other color

I have this display error on all variation products on my site
ex: https://www.lecornerdesophie.com/oceopin/624-924-huile-visage-repulpante-serum
the Capacity attribute: => Does not vary => It remains blocked on Capacity: 30ml (The default variation)

### Expected behavior

Can you help me to debug ?

### Steps to reproduce

https://www.lecornerdesophie.com/kure-bazaar/845-1199-vernis-a-ongles-ecologiques-2#/133-couleur_2-b
Click on the color Black or red and you will see that the text => Color 2 => the text Does not vary if you click on the other color

I have this display error on all variation products on my site
ex: https://www.lecornerdesophie.com/oceopin/624-924-huile-visage-repulpante-serum
the Capacity attribute: => Does not vary => It remains blocked on Capacity: 30ml (The default variation)

### PrestaShop version(s) where the bug happened

1.7.6.3

### PHP version(s) where the bug happened

7.2.34

**Comment by hibatallahAouadni** [comment]
Hello @MEGA911 

I didn't manage to reproduce the issue with PS1763 and PS1785.
Sorry, but I have to close the issue cause we use GitHub issues only to discuss about bugs and new features in the PrestaShop project and it seems your issue related to your overrides/modules/theme that you use.

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you
