### ISSUE TITLE
Install crash because of addons modules again :/

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/PrestaShop#27980]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I'm trying to install PS 1.7.8.5 straight on the server and getting the same error again as couple versions ago, that **I'm not allowed to install addons modules**. Care to at least explain **why can't I install these modules**? _php_ps_info_ shows everything green on the server. I even increased execution time to 5 minutes, but installation still fails.
When installing the same version on localhost everything goes smoothly.

### Expected behavior

Why don't you drop this connection with addons during install if it's so problematic? Install the shop first with basic modules packed inside prestashop archive and only when it's finished setting up shop suggest to add modules from addons.

### Steps to reproduce

1. Send unpacked prestashop archive (index.php + prestashop.zip) to the server
2. Setup database (my server uses 10.2.13-MariaDB) with ut8mb4_unicode_ci
3. Start installation

### PrestaShop version(s) where the bug happened

1.7.8.4, 1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by buggyzap** [comment]
Can you share server information to reproduce it? Never happens to me, and i'm installed hundreds of prestashop in different servers.

**Comment by SharakPL** [comment]
@buggyzap what information do you need?
I think it would be faster if someone form @PrestaShop explained what checks are made during addons modules part of prestashop installation. Why do I get response I'm not allowed to install modules? Is server's IP blacklisted or something? Response from addons server should exactly point to the problem.

**Comment by hibatallahAouadni** [comment]
Hello @SharakPL 

Could you please provide a screen record or some screenshots of your issue.
Cause @SD1982 and I didn't manage to reproduce the issue neither with mariaDB10 nor MySQL, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/159311856-2c8c0b9c-02d0-4ee7-86b8-73f686eeb614.mp4

Please check and feedback.
Thanks!

**Comment by SharakPL** [comment]
Screen record would be useless because the error is too generic and tells nothing about the problem. Can you tell me what checks are made on addons modules installation or at least point me to a file that handles it?

**Comment by buggyzap** [comment]
@SharakPL It could also be a permissions issue, there isn't a firewall or IP blocking during this process.

You have to put us in a position to replicate the problem programmatically, sharing the entire work environment in which it occurred to you.

Server information, memory/cpu, OS, php version, php handler, if you use plesk or cPanel, SQL engine and configuration, etc..

**Comment by matks** [comment]
> Why don't you drop this connection with addons during install if it's so problematic

Actually it's done on `develop` branch 😆

**Comment by matks** [comment]
> Why do I get response I'm not allowed to install modules? Is server's IP blacklisted or something? Response from addons server should exactly point to the problem.

We have no idea 🤷‍♂️ nobody is from Addons team here. 

That being said I guess Addons servers are behind a few security layers, like Cloudflare and some firewalls. So maybe you got unlucky and a bot indeed used a range of IPs that contain yours so you're now banned :/

But again: in PrestaShop 8.0.0 there is no more Addons modules being pushed (ref https://github.com/PrestaShop/PrestaShop/issues/24638).

**Comment by SharakPL** [comment]
@buggyzap it's not about permissions. index.php and prestashop.zip have 644. Install goes smoothly, all files have 644, all folders 755, up to the point where it's supposed to install addons modules:
![obraz](https://user-images.githubusercontent.com/5007456/159378775-9c791bff-928b-4c8c-9f91-1bf46d1afe0c.png)

My guess is it's about **ps_metrics** again, because there are constant problems with this module or its dependencies. Could also be **ps_facebook** causing this.

Or maybe it's because I install it on secure domain with SSL enabled...

**Comment by SharakPL** [comment]
> That being said I guess Addons servers are behind a few security layers, like Cloudflare and some firewalls. So maybe you got unlucky and a bot indeed used a range of IPs that contain yours so you're now banned :/

So every shared server hosting many prestashop installations and thus making many connections to Addons servers is basically screwed 😫

> But again: in PrestaShop 8.0.0 there is no more Addons modules being pushed (ref #24638).

I'm very glad about that! :)

**Comment by florine2623** [comment]
Hello @SharakPL ,

I can't reproduce your issue on my end.
As it will be removed in PS 8.0.0, I will close your issue :)

Thank you for your understanding!
