### ISSUE TITLE
Quick view modal not horizontally centered

### ISSUE THREAD

**Issue by sLorenzini** [PrestaShop/PrestaShop#27991]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I click on the "quick view" button on a product, the modal is not horizontally centered.
2 different cases :

Product without image:

![Capture d’écran 2022-03-21 à 15 22 59](https://user-images.githubusercontent.com/2854834/159304027-a6603cba-03a7-4087-ad27-603b657fc650.png)

Product with small description:

![Capture d’écran 2022-03-21 à 15 24 15](https://user-images.githubusercontent.com/2854834/159304343-7aa58b43-ace3-45b4-91f9-5e6d30088ea7.png)

### Expected behavior

The modal should be horizontally centered like a product with long description:

![Capture d’écran 2022-03-21 à 15 23 47](https://user-images.githubusercontent.com/2854834/159304528-51498be6-ac71-43a4-be7a-fd78d88c7c88.png)

### Steps to reproduce

1. Go to the FO
2. Click on the "Quick view" button on a card product

### PrestaShop version(s) where the bug happened

develop / 1.7.8.x

### PHP version(s) where the bug happened

7.2.21

**Comment by mparvazi** [comment]
![Screenshot from 2022-03-21 23-06-56](https://user-images.githubusercontent.com/85633460/159350859-1e292624-ce17-4a64-b3cf-e83fb8d8aeba.png)

@NeOMakinG 
Sometimes the script wrongly adds inline style `padding-right: 10px` to the `.quickview` container.
So to prevent using `!important` we can add 10px padding horizontally.
Btw with these changes the modal has 15px padding from the corners (in small media).

**Comment by NeOMakinG** [comment]
> ![Screenshot from 2022-03-21 23-06-56](https://user-images.githubusercontent.com/85633460/159350859-1e292624-ce17-4a64-b3cf-e83fb8d8aeba.png)
> 
> @NeOMakinG Sometimes the script wrongly adds inline style `padding-right: 10px` to the `.quickview` container. So to prevent using `!important` we can add 10px padding horizontally. Btw with these changes the modal has 15px padding from the corners (in small media).

If you can reproduce this thing, feel free to open an issue about it and contribute if you want!
