### ISSUE TITLE
The database schema update step results in an error.

### ISSUE THREAD

**Issue by lucasvavon** [PrestaShop/PrestaShop#27999]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello everyone,
I have been trying for a few days to upgrade Prestashop 1.7.7.0 to the latest version. I tried with the manual way, following all the indications of "https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/", but during the execution step of the file "install/upgrade/upgrade.php", it returns me an error#43, that is to say an error of upgrading the database schema using doctrine.

However, having already tried to upgrade Prestashop with the 1-click upgrade module, I could see that it returned the same type of error with more details.

Here is the precise error: 

> Updating database schema...

> Executing: ALTER TABLE PB_stock_mvt CHANGE id_stock id_stock INT NOT NULL, CHANGE date_add date_add DATETIME NOT NULL DEFAULT 'current_timestamp()' , CHANGE sign sign SMALLINT DEFAULT '1'

> 18:04:20 ERROR [console] Error thrown while running command "prestashop:schema:update-without-foreign --env=prod". Message: "An exception occurred while executing 'ALTER TABLE PB_stock_mvt CHANGE id_stock id_stock INT NOT NULL, CHANGE date_add date_add DATETIME NOT NULL DEFAULT 'current_timestamp()' , CHANGE sign sign SMALLINT DEFAULT '1'

> SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'date_add'"

If I understand correctly, adding "current_timestamp()" as default value is not accepted, but my database system has a default configuration.

![image](https://user-images.githubusercontent.com/80855852/159446954-f85e6452-b69a-45ef-b497-27e952aaed93.png)

Moreover, when executing SQL queries, by the update system, it declares, at the beginning of the line, to execute the queries corresponding to the version 1.7.8.1 of Prestashop, while in the folder "/install/upgrade/sql", the last available file is "1.7.8.0", so it is impossible to find the query that causes the problem, either by the manual update or by the module.

I did the test to test the query manually in the database but it only accepts it if the default value "current_timestamp()" is called without quotes.

Unfortunately, I can't find any case similar to mine on any forum.

If someone has an idea how to solve this request problem I'm interested.
Thanks in advance! 
Lucas,
Piment Bleu Agency (FR)

### Steps to reproduce

This happens while running the 1-click upgrade module.

### PrestaShop version(s) where the bug happened

1.7.7.0

### PHP version(s) where the bug happened

7.2.34

### If your bug is related to a module, specify its name and its version

1-click upgrade v4.14.0

**Comment by florine2623** [comment]
Hello @lucasvavon ,

I can't reproduce your issue. On my end, I did an upgrade from PS 1.7.7.8 to 1.7.8.5 without any major error using 1-click upgrade module v4.14.0.
<img width="788" alt="Screenshot 2022-03-22 at 11 35 04" src="https://user-images.githubusercontent.com/16019289/159463051-66ed9ed8-cacf-4894-aaf5-e4640bb3db2f.png">
<img width="1176" alt="Screenshot 2022-03-22 at 11 47 19" src="https://user-images.githubusercontent.com/16019289/159465035-5672e236-a92f-421e-ba2a-e77e86be7a13.png">


Which version of MySQL are you using ?
Did you make any changes to your database previously ?

Thanks!

**Comment by lucasvavon** [comment]
hello @florine2623,

I use MariaDB v.10.3.34, not MySQL. No changes were made manually, at least not on the table concerned.

Thanks you !

**Comment by lucasvavon** [comment]
I close the problem: we solved the problem by changing the default value "current_timestamp()" of the field "date_add" of the table "prefix_stock_mvt" to "none".

**Comment by hibatallahAouadni** [comment]
@lucasvavon Glad to hear :tada:
