### ISSUE TITLE
Language selector (text fields flags menu) cannot be translated

### ISSUE THREAD

**Issue by AlexanderFedorenko** [PrestaShop/PrestaShop#280]
Language selector text "Choose language:" (text fields flags menu) cannot be translated

![123](https://f.cloud.github.com/assets/3668729/184504/eaac099e-7cdd-11e2-8d7f-5698d1c8a54a.png)

**Comment by marionf** [comment]
Hello, 
This issue is old, so I close it.
If you still have it on the last version (PrestaShop 1.7.4.2), please open a new one.
Regards
