### ISSUE TITLE
Some products on my store are being activated automatically

### ISSUE THREAD

**Issue by bnofao** [PrestaShop/PrestaShop#28008]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When product is set inactive, it's changed to active alone.
Category has other actives products.

### Expected behavior

Product should stay inactive until manual activation.

### Steps to reproduce

Random issues.

### PrestaShop version(s) where the bug happened

1.7.7.5

### PHP version(s) where the bug happened

7.3.33

**Comment by alfonsolr09** [comment]
can you send a video or pictures?

**Comment by HanaRebaiQA** [comment]
Hello @bnofao 

Thanks for your report.
I was unable to reproduce your issue with PS1785 

https://user-images.githubusercontent.com/92912932/159667738-8f951805-b123-46bc-b558-73e751a521ae.mp4



Could you provide us more information with a screen-record or screen-shots to can reproduce it clearly ?

Thank you!

**Comment by bnofao** [comment]
Thank you for your feedback. 
Unfortunately, the issue is random. I don't know how to reproduce it. It happen sometimes, several days after the product was set to inactive.
Do you know how to monitor and catch product status change with details about what change it?

**Comment by hibatallahAouadni** [comment]
Hello @bnofao 

> Unfortunately, the issue is random.

Despite our efforts, we were not able to reproduce your issue with the provided information. And as you said it's random! so it's hard to reproduce :disappointed: 

If you have questions about using PrestaShop, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

We will close this issue.

Thank you

**Comment by alfonsolr09** [comment]
> Thank you for your feedback. Unfortunately, the issue is random. I don't know how to reproduce it. It happen sometimes, several days after the product was set to inactive. Do you know how to monitor and catch product status change with details about what change it?

try to activate debug mode...
