### ISSUE TITLE
Wrong alert when configure google analytics module

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#28005]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Wrong alert when we configure google analytics module

https://user-images.githubusercontent.com/89604350/159647648-e7d58fc7-acbd-4f3c-934a-538632d75c5c.mp4

### Steps to reproduce

1. Install google analytics module
2. Configure module 
3. Click on save 

### PrestaShop version(s) where the bug happened

develop/1.7.8.5

### PHP version(s) where the bug happened

7.3/7.4

### If your bug is related to a module, specify its name and its version

ps_googleanalytics-

**Comment by alfonsolr09** [comment]
I think that Prestashop cannot verify that the google analytics id is correct, the only way to verify it is in the google panel, seeing if it receives data or not

**Comment by marwachelly** [comment]
> I think that Prestashop cannot verify that the google analytics id is correct, the only way to verify it is in the google panel, seeing if it receives data or not

The problem exist even when the ID is empty.

**Comment by alfonsolr09** [comment]
but I don't think it's a problem, it just informs you that the data has been saved correctly. if you misspelled your google id is your problem right?🤔

**Comment by marwachelly** [comment]
> but I don't think it's a problem, it just informs you that the data has been saved correctly. if you misspelled your google id is your problem right?thinking

@PrestaShop/product-team Could you please specify the exact expected behavior?

**Comment by leemyongpakvn** [comment]
@marwachelly I found a solution for this issue. Please check the new PR.
