### ISSUE TITLE
BO- Bad display of google analytic configure page 

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#28006]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

 Bad display of google analytic configure page 
![image](https://user-images.githubusercontent.com/89604350/159530587-ddd18d04-3c7e-4131-9383-f372ad8aa204.png)

### Steps to reproduce

1. Install google analytic module
2. Go to configure page
3. resize window

### PrestaShop version(s) where the bug happened

1.7.7.8/1.7.8.5/develop

### PHP version(s) where the bug happened

7.4/7.2/7.3

### If your bug is related to a module, specify its name and its version

Ps_googleanalytics

**Comment by leemyongpakvn** [comment]
@marwachelly It looks like [christophe-rouille](https://github.com/christophe-rouille)'s [PR 103](https://github.com/PrestaShop/ps_googleanalytics/pull/103) solved this issue in ps_googleanalytics version 4.1.1. I see no problem with version 4.1.2 in Prestashop 1.7.8.5

**Comment by hibatallahAouadni** [comment]
Good news :tada: so we can close the issue
