### ISSUE TITLE
FO - ps_googleanalytic - Code found outside of <head> tag

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#28004]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I added this extension `Tag Assistant Legacy (by Google)` to Chrome
I installed the module ps_googleanalytic and configure it with a valid ID 
In the FO, when we enable the tag, we have this alert 
![image](https://user-images.githubusercontent.com/16067358/159527146-acf69921-c399-4e4a-962e-85ec1ed5daeb.png)

With PS1785 => OK

### Steps to reproduce

1. Add this extension `Tag Assistant Legacy (by Google)` to Chrome
2. Install the module ps_googleanalytic and configure it with a valid ID 
3. Go to FO & enable the extension
4. Refresh the page
5. See the warning

https://user-images.githubusercontent.com/16067358/159527921-f76f6157-fee5-4101-bfe1-906bad83847d.mp4

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_googleanalytic v4.1.0, v4.1.1

**Comment by Progi1984** [comment]
@khouloudbelguith Could you check if the behavior is always present with the `dev` branch of the module ? I didn't reproduce it.

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I still have the same issue with develop branch and the `ps_googleanalytic` dev branch.
I attached a screen record

https://user-images.githubusercontent.com/16067358/161555412-94a14279-0641-44c6-93d6-dac525137336.mp4

Thanks!

**Comment by Progi1984** [comment]
@khouloudbelguith Thanks. I reproduce now. And it's fixed.
