### ISSUE TITLE
Specific prices for specific product combinations affects all combinations in cart

### ISSUE THREAD

**Issue by demperador** [PrestaShop/PrestaShop#28018]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The possible detected problem/issue is that when a product has more than one combination and there are specific prices for each combination starting at, for example, 4 units. Prestashop will set the discount for the sum of 4 units no matter what combinations are in the cart. This expected behaviour would be correct if the specific price was for all combinations. Also, within the cart, it will not show the applied discount unless the user matches the ordered quantity with starting amount.

![Captura de pantalla 2022-03-23 a las 13 16 30](https://user-images.githubusercontent.com/31283004/159708567-7294ccd1-2048-4ce2-9340-ac49f650e532.png)

![Captura de pantalla 2022-03-23 a las 13 19 41](https://user-images.githubusercontent.com/31283004/159709201-cf4e1690-11af-425e-9a19-6f8934c083b5.png)

![Captura de pantalla 2022-03-23 a las 13 22 58](https://user-images.githubusercontent.com/31283004/159710041-c3ea56a4-f853-4f2b-9896-4af674fbaef3.png)

### Expected behavior

The behaviour is expected if there is no specific combination set for the specific price. However, if the user sets a specific price for a specific combination, it is expected to apply that discount only to that specific combination.

### Steps to reproduce

1. Have a product with more than one combination with different prices
2. Create a specific price for combination 1 starting at 4 units with 25% discount
3. Create a specific price for combination 2 starting at 4 units with 25% discount
4. In fronted, add to cart 2 units for combination 1 and 2 units for combination 2
5. In cart, both combinations will have 25% discount applied but it will not be shown, price will be modified but no discount will be shown
6. Set 4 units to each combination in cart and prestashop will show applied discount.

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4.11

**Comment by HanaRebaiQA** [comment]
Hello @demperador 

Thanks for your report.
Your issue seems to be similar to theses ones ([#26332](https://github.com/PrestaShop/PrestaShop/issues/26332), [#22661](https://github.com/PrestaShop/PrestaShop/issues/22661))
Do you confirm it ?

Thank you!

**Comment by demperador** [comment]
Hello @HanaRebaiQA 

I have read both issues but I think it is not the same issues as in #26332 or #22661 

Regards.

**Comment by hibatallahAouadni** [comment]
Hello @demperador 

Do you encounter this issue only when you applied **no Tax** or even when you apply any tax?
Did you encounter this issue only with 1.7.8.4 or even with older versions?
Please check and feedback.

Thanks!

**Comment by demperador** [comment]
Hello @hibatallahAouadni 

Due that we operate in the Canary Islands and we are a retail store, VAT is not applied within this territory, our store has the taxes disabled. However, I activated taxes for testing the issue and the problem persists. We are currently on Prestashop 1.7.8.3.

Regards.

**Comment by marwachelly** [comment]
Hello,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of [this issue](https://github.com/PrestaShop/PrestaShop/issues/27226). 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks,

**Comment by marwachelly** [comment]
Duplicate of #27226

**Comment by qcol** [comment]
Bug still exists in 8.1
