### ISSUE TITLE
Default category doesn't update properly

### ISSUE THREAD

**Issue by dkarvounaris** [PrestaShop/PrestaShop#28016]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The default category of a product should be one of the associated categories. However, when editing them in the backend, they default category is not always set to one of the associated categories. As consequence, visiting the product page it also:

1. Redirects to the wrong SEO URL containing the wrong category in the URL
2. Shows the wrong breadcrumb on the product page

### Expected behavior

When a category is removed from a product as association, which was previously the default category too, the default category should be adjusted as necessary and set to one of the associated categories. So that redirects of the product url and displayed breadcrumb should be correct.

### Steps to reproduce

1. Edit a product
2. Notice the associated category and the default category ID in the database
3. Add the product to a new category
4. Remove the old category which was previously the default category too
5. Backend will update instantly category associations in database, without saving product - which is ok. But it won't check for default category.
6. Default Category ID still contains the old category in database now no longer associated with the product
7. Click "Preview" for the product
8. Product URL will be redirected with SEO URLs to an url containing the old category (the default category) instead of the new category
9. Breadcrumb on previewed product page will show the product as belonging to the category no longer associated with it

### PrestaShop version(s) where the bug happened

1.7.8

**Comment by HanaRebaiQA** [comment]
Hello @dkarvounaris 

Thanks for your report.

Is these issues cases [#13737](https://github.com/PrestaShop/PrestaShop/issues/13737) and [#18109](https://github.com/PrestaShop/PrestaShop/issues/18109 ) are similar to yours ?

Thank you!

**Comment by dkarvounaris** [comment]
> Is these issues cases [#13737](https://github.com/PrestaShop/PrestaShop/issues/13737) and [#18109](https://github.com/PrestaShop/PrestaShop/issues/18109) are similar to yours ?

No, these seem completely unrelated. I cannot see how they could be related in any way.

In simple words: it's about the _default_ category not reflecting accurately the current category selections and not displaying correctly on the breadcrumb of the product page and the URL showing a category no longer associated with a product. A "default" category is a special feature of PrestaShop, additionally to the categories. 

At first it may seem it may involve changes on many locations, but that's not the case. All that is required is for the code to update the default category too (an additional column in the product table in database), when it updates the categories, in case the product no longer belongs to the category indicated as "default category".

**Comment by emo99sus** [comment]
Any updates on the topic? I have noted that the problem also exist on my 1.7.8 version
