### ISSUE TITLE
Multistore - Advanced Parameters > Performance:media - use ShopConstraint as third argument

### ISSUE THREAD

**Issue by davidglezz** [PrestaShop/PrestaShop#28025]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

no

### Describe the solution you'd like

Simplifies the number of conditionals branches. This makes the code easier to maintain. Use ShopConstraint and added unit test.

It's about code refactoring over configuring media servers and code behind it. I took one part of the code and improved it.

https://github.com/PrestaShop/PrestaShop/pull/27660#discussion_r818547416

### Additional context

I have added unit test in the PR

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @davidglezz 

We need a detailed description about the work you have done it in your PR :wink: 
> this is an issue for the QA team to test a PR
I have added unit test in the PR

It's not a good description of the proposed solution nor for additional context :sweat_smile: 
So, please edit and notify me :wink: 

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @davidglezz 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by kpodemski** [comment]
@hibatallahAouadni, it's about code refactoring, @davidglezz took one part of the code and improved it

it's about configuring media servers and code behind it

**Comment by hibatallahAouadni** [comment]
Hello @kpodemski 

I see what you're saying but this kind of issue content is not acceptable: 
> this is an issue for the QA team to test a PR

So, the author need to edit the issue content, then I will reopen it and add these labels: `NeedsSpecs` + `Waiting for Dev` :wink: 

Thanks!
