### ISSUE TITLE
Call to `api.addons.prestashop.com` in module psgdr

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#28027]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

With the open source/company split, we should not have any call to prestashop.com.

In `psgdpr`, it remains a call : 

https://github.com/PrestaShop/psgdpr/blob/dev/classes/APIFAQClass.php#L35
```php
$url = 'http://api.addons.prestashop.com/request/faq/' . $module_key . '/' . $version . '/' . $iso_code;
```

Example : https://api.addons.prestashop.com/request/faq/1001fe84b4dede19725b8826e32165b7/1.4.0/en

### Expected behavior

The call must be removed or targeted to `prestashop-project.org`.

### Steps to reproduce

Check the description

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

PHP7.3

### If your bug is related to a module, specify its name and its version

psgdpr 1.4.0

**Comment by matks** [comment]
Nice catch 👍

**Comment by Progi1984** [comment]
As validated with @fabienvallon, I put all strings in local and remove remote call.
