### ISSUE TITLE
Automatic hotlinking of products by reference, MPN, EAN etc.

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#28026]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Imagine you have following text in your product description: 
`If you need to mount this to XY, you need to use a spacer Bestbrand ABCD12345.`

It would be good if the product could be a link to a product on your shop. 

### Describe the solution you'd like

I would like ABCD12345 to automatically become a link to a product on a shop, if found by reference, MPN, UPC, EAN or reference.

**Advantages**
- It would do everything automatically for every language.
- It would handle the most recent links, no need to care about changing IDs, URLs etc.
- It would not link if that product is disabled.
- **Basically - no 404 ever.**

**How it could work**
- We could wrap the text in something like `<span data-autolink-mpn>`, `<span data-autolink-reference>` or `<span data-autolink-ean13>`.
- So it would look like `If you need to mount this to XY, you need to use a spacer Bestbrand <span data-autolink-mpn>ABCD12345</span>.`
- When showing the product in front office or loading the description, prestashop would check for these tags and get the content. `SELECT id_product FROM ps_product WHERE mpn=xxxx;`
- It would try to find the product in database by the content and if it finds it, it will replace the span by `<a href="url">ABCD12345</a>`.

**How it could be managed**
- Either manually in the source code of the description.
- We can extend tinyMce with a new button called `Add internal link`
  - You select text the same as if you were to do it bold or italics.
  - Click the button.
  - Popup will come up asking `What is the link type?`
  - You click Reference, MPN, UPC, EAN, tag etc. and it will wrap the words with the span.

### Alternatives you've considered

Making this links manually is unreal to manage. Too much work, you need to do it for every language, then if the product linked is disabled and other problems.

_I also thought of completely automatic hotlinking. That would be maybe doable if one didn't use purely lettered references. Explode description by spaces, check every word containing numbers and longer than X characters for appeareance in DB. But it would be still too performance intensive for too small added value. This is a dead end. 🚧_

### Additional context

No BC breaks, no template changes needed.
Ping @kpodemski @MatShir

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. 
So, as usual we're waiting for your PR :muscle: :rocket: 

Thank you

**Comment by MatShir** [comment]
Extending the tinyMCE looks awesome (maybe a search bar to add a product/categories or find a cms page 🤔)
If the product is disabled, maybe we could use the redirection of the product offline? So the client can be redirected to a similar product or a category 🤷 
But we have to make really sure that it works when URL is changed
If you are motivated, we can write down the specs in this repo https://github.com/PrestaShop/prestashop-specs and see with one of the @PrestaShop/ux-team a cool design
