### ISSUE TITLE
PS 1.7.8.1 to 1.7.8.5 cart error 500 in BO

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#28030]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After updating PS from PS 1.7.8.1 to 1.7.8.5 I see the error 500 in the BO in the Order->Client`s Cart
When I turned on the Debugg mode I see the next errors
![image](https://user-images.githubusercontent.com/50954519/159939445-4cd28bf8-7978-4a3c-9164-c09163e9fc60.png)

### Expected behavior

I epect to see the cart page in the BO, but see only the error 500 page (
![image](https://user-images.githubusercontent.com/50954519/159939762-f2cbcc5d-f5cc-4c99-a244-365c43e2cebf.png)

### Steps to reproduce

Update PS from 1.7.8.1 to 1.7.8.5
Go to the BO
Select Clients Cart
See the errors
In my case I see only the error 500 and no cart page (

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.1.33-44

**Comment by photinia73** [comment]
When I delted the last 100+- orders from cart throw MySql the page Clents Carts start work... What was wrong I cant understand...

**Comment by hibatallahAouadni** [comment]
Thanks for closing the issue as I didn't reproduce it :sweat_smile: 
My shop was successfully updated and I can access to the Shopping Cart page in BO without any problem!

**Comment by ChineseNorris** [comment]
> When I delted the last 100+- orders from cart throw MySql the page Clents Carts start work... What was wrong I cant understand...

This happens when you have an error in one of the address that you are trying to show, usually by editing/removing the corrupted address would fix the issue.
