### ISSUE TITLE
Add CHANGELOG.md to repository

### ISSUE THREAD

**Issue by Grezor** [PrestaShop/PrestaShop#28045]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

My problem is that I would like to see the current releases at the root of the prestashop project.
I have to go to the repository and then to the releases tab.

I think a lot of developers would like to have a file directly at the root so they can just see the resolved issues.

File CHANGELOG.md

### Describe the solution you'd like

Why not create a file at the root of prestashop to announce all the corrections, or the problems. On each version 

or future improvements, front / back side improvements.

### Alternatives you've considered

https://github.com/PrestaShop/PrestaShop/releases

Instead of displaying the problems directly from a : 
https://build.prestashop.com/news/prestashop-1-7-8-5-maintenance-release/

Add directly a file in the PrestaShop project in order to have all information, update, fix, problem

EXEMPLE : 

CHANGELOG for 1.7.8.5
===================

* 1.7.8.* (date)
**category** [Changed/Fixed]
 * [bug/fix/front/admin]  #12345 problem 1 (autor 1)
 * [bug/fix/front/admin]  #12345 problem 2 (autor 1)

VIEWS

CHANGELOG for 1.7.8.5
===================

* 1.7.*.* (2022-03-27)
 **Fixed**
     * fix #12345 problem 1 (autor 1)
     * bug  #123456 problem 2 (autor 2)
**changed**
     * translate #12345 (autor 3)
   
Improvement:
    #PR add new colors admin

more exemple : 
[link infos](https://raw.githubusercontent.com/symfony/symfony/6.1/CHANGELOG-6.0.md)
[repository Symfony changelog](https://github.com/symfony/symfony/blob/6.1/CHANGELOG-6.0.md)
[repository Laravel changelog](https://github.com/laravel/framework/blob/9.x/CHANGELOG.md)

### Additional context

I am willing to contribute to this file. If you want to implement this feature on the github repository
I would like to have an opinion, or feedback.

Have a nice day
Grezor

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [x] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by matks** [comment]
> Why not create a file at the root of prestashop to announce all the corrections, or the problems. On each version

The file is here https://github.com/PrestaShop/PrestaShop/blob/develop/docs/CHANGELOG.txt 😄

**Comment by Grezor** [comment]
Hello @matks,

Thanks for the information, I thought it wasn't in the repository. I close the issue.
