### ISSUE TITLE
Wrong purchase date

### ISSUE THREAD

**Issue by SMULTI2022** [PrestaShop/PrestaShop#28049]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Good evening, I tried to make a purchase a little while ago as there were problems with prestashop checkout and also the form had just been updated, and as shown in the attached photo, the payment is dated 11/03/2022 but instead it was done today 25/03/2022, how can it be solved? or where does the problem arise? Thank you and good day.
![error](https://user-images.githubusercontent.com/102508158/160346742-947d18d0-6c2f-4fea-a5e9-c5fdeb076890.png)

### Steps to reproduce

I purchased a product to do a proof of purchase to make sure everything was working, but the purchase date does not match
![error](https://user-images.githubusercontent.com/102508158/160347573-80662059-ca38-47a5-94ed-06f56b1845e8.png)

### PrestaShop version(s) where the bug happened

1.7.8.4

### PHP version(s) where the bug happened

7.3

**Comment by SMULTI2022** [comment]
Sorry, the right version of Prestashop is 1.7.8.4 and PHP version is 7.3.33 thanks

**Comment by hibatallahAouadni** [comment]
Hello @SMULTI2022 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must provide clear and concise step to reproduce the issue**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
