### ISSUE TITLE
Error I can't fix

### ISSUE THREAD

**Issue by FireWtap** [PrestaShop/PrestaShop#28042]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

[Fri Mar 25 21:04:07.601595 2022] [php7:error] [pid 15662] [client 114.119.136.254:55720] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/avanza_api/intimointime.it/var/cache/prod/appParameters.php' (include_path='/var/www/html/avanza_api/intimointime.it/vendor/pear/pear_exception:/var/www/html/avanza_api/intimointime.it/vendor/pear/console_getopt:/var/www/html/avanza_api/intimointime.it/vendor/pear/pear-core-minimal/src:/var/www/html/avanza_api/intimointime.it/vendor/pear/archive_tar:.:/usr/share/php') in /var/www/html/avanza_api/intimointime.it/config/bootstrap.php on line 87

I can't fix this error no matter what i try :/
anyone has any suggestion on how to fix this?
It worked perfectly and then stopped for no reason 

### Steps to reproduce

-

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by matks** [comment]
Hi ! it seems you're looking for support. You will find places where to get help here => https://www.prestashop-project.org/support/
