### ISSUE TITLE
Prestashop multi store + litespeed - page 404

### ISSUE THREAD

**Issue by Varindien** [PrestaShop/PrestaShop#28051]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Once litepseed installed, everypage except CMS return 404 error.

### Expected behavior

display page like apache.

### Steps to reproduce

Install Prestashop with multistore and categories to each store.

### PrestaShop version(s) where the bug happened

1.7.7.8

### PHP version(s) where the bug happened

7.3

**Comment by Varindien** [comment]
Auto answer  : 

Prestashop 1.7 multistore with subfolder is not compatible with litespeed server.

Solution :  have to create multistore with subdomain.

[EDIT] : by the way multistore with /fr/ or /en/ issues still exists.. and there is no way to bypass subfolder of language

**Comment by hibatallahAouadni** [comment]
Hello @Varindien 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must provide clear and concise step to reproduce the issue**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
