### ISSUE TITLE
[PS Facebook] Won't synchronize new/edited products

### ISSUE THREAD

**Issue by d0niek** [PrestaShop/PrestaShop#28058]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Some time ago I have installed `ps_facebook` module. After success setup and configure (module and Facebook fanpage) it synchronize whole my catalog (all turned on products) in a few days. Now I'm adding new products and editing existing but they aren't synchronizing to Facebook any more. I have reconnect module with Facebook account, I have reinstall module but still it won't synchronize new products.

![obraz](https://user-images.githubusercontent.com/9316891/160598724-d0c299da-8fad-4a62-a674-b242d4cb37a5.png)

Does a module has a limit products to synchronize after first sync or Facebook has it?

I see that "Last synchronization" doesn't show a date but some info/warning. I have checked how module setup this variable and in `modules/ps_facebook/classes/Provider/ProductSyncReportProvider.php:63` throw an exception. I dump it and got a message:

```
Client error response [url] https://facebook-api.psessentials.net/account/{$businessId}/reporting [status code] 404 [reason phrase] Not Found
```

Response message has:

```
Reporting for this facebook account not found!
```

### Expected behavior

Products number "Products in Facebook catalog" should equals to "Ready to synchronize".

### Steps to reproduce

1. Install and setup `ps_facebook`.
2. Run first synchronization.
3. After whole catalog will synchronized new/edited products won't be synchronized.

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4.28

### If your bug is related to a module, specify its name and its version

ps_facebook:1.16.0

**Comment by marwachelly** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com/).

Thank you,
