### ISSUE TITLE
BO - Cannot delete specific price from product V2

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#28054]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Catalog > Products > product V2 > Pricing tab, we cannot delete a specific price
![image](https://user-images.githubusercontent.com/16067358/160457273-38cc262b-9db5-4def-9cdd-d9d995243628.png)

### Steps to reproduce

1. Go to BO > Catalog > Product V2
2. Edit a product V2 with a specific price for example `demo_1`
3. In the pricing tab > delete a specific price
4. See error: cannot be deleted

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.0

**Comment by Progi1984** [comment]
@matthieu-rolland is on this one.

**Comment by khouloudbelguith** [comment]
Hello,

This issue is fixed in the 8.0.x branch.
It could be fixed by this PR: https://github.com/PrestaShop/PrestaShop/pull/28390

Thanks!
