### ISSUE TITLE
Low contrast in notification-counter

### ISSUE THREAD

**Issue by tm8544** [PrestaShop/PrestaShop#28053]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Is your feature request related to a problem?

`.notification-counter` in files `admin\themes\new-theme\public\main.css` and `admin\themes\new-theme\public\theme.css` uses background `#f1b746` with white font color. This produces low conrast.

Darker color, e.g. orangered for background or black for text should be used to enhance readability.

See attached image with original bg and orangered as bg
![nimetön](https://user-images.githubusercontent.com/15167679/160419460-bcbeb3e9-5707-4941-94a5-3ec9a6597811.jpg)

Original bg with black text gives even better contrast.

### Describe the solution you'd like

Contrast should be better for readability.
In `admin\themes\new-theme\public\main.css`, search for
```
.notification-counter{
   position:absolute;
   top:0.25rem;
   right:0;
   display:inline-block;
   padding:0 0.1875rem;
   font-size:0.625rem;
   line-height:0.75rem;
   color:#fff;
   background:#f1b746;
   border:0.125rem solid #fff;
   border-radius:1rem;
   top:-1.75rem;
   right:-0.9375rem
}
```

1. Change to:

```
.notification-counter{
   position:absolute;
   top:0.25rem;
   right:0;
   display:inline-block;
   padding:0 0.1875rem;
   font-size:0.625rem;
   line-height:0.75rem;
   color:#fff;
   background:#f1b746;
   border:0.125rem solid #fff;
   border-radius:1rem;
   top:-1.75rem;
   right:-0.9375rem; 
   color:black;
}
```
2. Or to:

```
.notification-counter{
   position:absolute;
   top:0.25rem;
   right:0;
   display:inline-block;
   padding:0 0.1875rem;
   font-size:0.625rem;
   line-height:0.75rem;
   color:#fff;
   background:#f1b746;
   border:0.125rem solid #fff;
   border-radius:1rem;
   top:-1.75rem;
   right:-0.9375rem; 
   color:black;
   font-weight:bold;
}
```

3. or some other bg / color combination that produces good contrast.

### Do you plan to work on this feature?

- [] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @tm8544 

Could you please downgrade your PHP version to 7.4, cause PS1785 is not compatible with PHP 8.1 (see our [system requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart)).
Your issue seems a feature request more than a bug report. So, I'm changing the label :wink: 
Could you please propose a solution or a mock-up :pray: 
Waiting for your feedback.

Thanks!

**Comment by tm8544** [comment]
Ok with PHP version.

Proposed solution:
in `admin\themes\new-theme\public\main.css` and `admin\themes\new-theme\public\theme.css`, search for
```
.notification-counter{
   position:absolute;
   top:0.25rem;
   right:0;
   display:inline-block;
   padding:0 0.1875rem;
   font-size:0.625rem;
   line-height:0.75rem;
   color:#fff;
   background:#f1b746;
   border:0.125rem solid #fff;
   border-radius:1rem;
   top:-1.75rem;
   right:-0.9375rem
}
```

1. Change to:

```
.notification-counter{
   position:absolute;
   top:0.25rem;
   right:0;
   display:inline-block;
   padding:0 0.1875rem;
   font-size:0.625rem;
   line-height:0.75rem;
   color:#fff;
   background:#f1b746;
   border:0.125rem solid #fff;
   border-radius:1rem;
   top:-1.75rem;
   right:-0.9375rem; 
   color:black;
}
```
2. Or to:

```
.notification-counter{
   position:absolute;
   top:0.25rem;
   right:0;
   display:inline-block;
   padding:0 0.1875rem;
   font-size:0.625rem;
   line-height:0.75rem;
   color:#fff;
   background:#f1b746;
   border:0.125rem solid #fff;
   border-radius:1rem;
   top:-1.75rem;
   right:-0.9375rem; 
   color:black;
   font-weight:bold;
}
```

3. or some other bg / color combination that produces good contrast.

**Comment by hibatallahAouadni** [comment]
Hello @tm8544 

I just modifiy your issue/feature description, could you please check it :wink: 
Thank you for your suggestion. The Product Team will take it into consideration for future developments. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by tm8544** [comment]
Updated a bit, added 'themes.css' at the beginning.
Otherwise it's ok for me.

**Comment by florine2623** [comment]
@TristanLDD , what do you think about this color change ?

**Comment by TristanLDD** [comment]
Hi @tm854, thanks for your contribution! 

I agree with you, red background notification counters will have better contrast and readability 
Can you make the notification color `#f44336` so it matches the back-office UI kit colors?

**Comment by hibatallahAouadni** [comment]
Ping @NeOMakinG

**Comment by tm8544** [comment]
You can use any background color +  font color/weight combination that matches the back-office UI kit colors and provides good contrast and readability.
