### ISSUE TITLE
No records on table order_detail_tax

### ISSUE THREAD

**Issue by omar2886** [PrestaShop/PrestaShop#28056]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

orders are not saving any information on table `order_detail_tax`

### Steps to reproduce

1. placing an order from BO or FO, everything's fine, 
2. even after placing the order in FO a customer can see the order details with the taxes, 
3. but this taxing information is not being saved on table `order_detail_tax`, which it normally should :x: 
4. In table order details is fine, you have all prices with and without taxes, nothing wrong there :heavy_check_mark: 
5. Prestashop is well configured with all taxes, regions and invoicing options, the only issue is that it's not saving any information on table `order_detail_tax`

### PrestaShop version(s) where the bug happened

1.7.6

### PHP version(s) where the bug happened

7.2

**Comment by Hlavtox** [comment]
This table should be filled, I am also on 1.7.6, weird....

![Snímek obrazovky 2022-03-29 093101](https://user-images.githubusercontent.com/6097524/160557748-c594971c-68eb-4442-870b-daf35fc91669.png)

Try to investigate. Inserting seems to happen on 3 places. Find which function is used in the case of FO order. Then try to see why it fails to insert the required data. Put some good old `die('here1');` to places and see how far it goes. 😁
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/order/OrderDetail.php#L448
https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Order/OrderDetailUpdater.php#L205
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/order/Order.php#L2682

**Comment by marwachelly** [comment]
Hello, 

Could you please follow the steps bellow :

1. Go to International > Taxes 
2. Activate the option "Display tax in the shopping cart "
3. Taxes will be displayed in the order details in the FO.

https://user-images.githubusercontent.com/89604350/160579925-8f1461d7-64eb-479f-8930-829412003ad6.mp4

Thanks,

**Comment by omar2886** [comment]
> Hello,
> 
> Could you please follow the steps bellow :
> 
> 1. Go to International > Taxes
> 2. Activate the option "Display tax in the shopping cart "
> 3. Taxes will be displayed in the order details in the FO.
> 
>  Untitled_.Mar.29.2022.11_15.AM.mp4 
> Thanks,

thanks @marwachelly but this is already the configuration I have. There must be another config maybe that triggers the function to write on that table, do you know what exactly?

**Comment by marwachelly** [comment]
Hello,

Could you please send a screen shot or screen record from your configuration ? 

Thanks,

**Comment by omar2886** [comment]
Here are the screenshots of the config with also an exempla of a recent validated order as it's recorded in ps_orders
![capture](https://user-images.githubusercontent.com/12675798/160595413-ad266712-2183-46a4-9500-6b498c7484db.jpg)

**Comment by khouloudbelguith** [comment]
Hi @omar2886,

I did not manage to reproduce the issue with PS1785.
I attached a screen record

https://user-images.githubusercontent.com/16067358/161253297-610aa148-3930-4007-b747-bb00acd1e239.mp4

Could you please provide me a screenshot from the Order History page?

Thanks!

**Comment by omar2886** [comment]
> Hi @omar2886,
> 
> I did not manage to reproduce the issue with PS1785. I attached a screen record
> 
>  Untitled_.Apr.1.2022.12_16.PM.mp4 
> Could you please provide me a screenshot from the Order History page?
> 
> Thanks!

Thanks Khouloud for taking your time to analyze this. The issue is not in the FO, same as in your case, my customers can see properly taxes of each order accessing through their account in the order history section.
The problem is that this info is not being registered in table order_detail_tax.
I've been told that the function in charge of writing this tax info in that table is located in OrderDetail.php, so here is the code I have in that function, maybe is wrong? I've seen many changes in that code ever since 1.7.6
`    /**
     * Save the tax calculator.
     *
     * @since 1.5.0.1
     * @deprecated Functionality moved to Order::updateOrderDetailTax
     *             because we need the full order object to do a good job here.
     *             Will no longer be supported after 1.6.1
     *
     * @return bool
     */
    public function saveTaxCalculator(Order $order, $replace = false)
    {
        // Nothing to save
        if ($this->tax_calculator == null) {
            return true;
        }

        if (!($this->tax_calculator instanceof TaxCalculator)) {
            return false;
        }

        if (count($this->tax_calculator->taxes) == 0) {
            return true;
        }

        if ($order->total_products <= 0) {
            return true;
        }

        $shipping_tax_amount = 0;

        foreach ($order->getCartRules() as $cart_rule) {
            if ($cart_rule['free_shipping']) {
                $shipping_tax_amount = $order->total_shipping_tax_excl;

                break;
            }
        }

        $ratio = $this->unit_price_tax_excl / $order->total_products;
        $order_reduction_amount = ($order->total_discounts_tax_excl - $shipping_tax_amount) * $ratio;
        $discounted_price_tax_excl = $this->unit_price_tax_excl - $order_reduction_amount;

        $values = '';
        foreach ($this->tax_calculator->getTaxesAmount($discounted_price_tax_excl) as $id_tax => $amount) {
            switch (Configuration::get('PS_ROUND_TYPE')) {
                case Order::ROUND_ITEM:
                    $unit_amount = (float) Tools::ps_round($amount, _PS_PRICE_COMPUTE_PRECISION_);
                    $total_amount = $unit_amount * $this->product_quantity;

                    break;
                case Order::ROUND_LINE:
                    $unit_amount = $amount;
                    $total_amount = Tools::ps_round($unit_amount * $this->product_quantity, _PS_PRICE_COMPUTE_PRECISION_);

                    break;
                case Order::ROUND_TOTAL:
                    $unit_amount = $amount;
                    $total_amount = $unit_amount * $this->product_quantity;

                    break;
            }

            $values .= '(' . (int) $this->id . ',' . (int) $id_tax . ',' . (float) $unit_amount . ',' . (float) $total_amount . '),';
        }

        if ($replace) {
            Db::getInstance()->execute('DELETE FROM `' . _DB_PREFIX_ . 'order_detail_tax` WHERE id_order_detail=' . (int) $this->id);
        }

        $values = rtrim($values, ',');
        $sql = 'INSERT INTO `' . _DB_PREFIX_ . 'order_detail_tax` (id_order_detail, id_tax, unit_amount, total_amount)
                VALUES ' . $values;

        return Db::getInstance()->execute($sql);
    }`

**Comment by Hlavtox** [comment]
@omar2886 I send you instructions to functions you need to check, nothing else will help you. The code returns sometime before inserting the records, find where it is failing and we can move on. 👍

**Comment by omar2886** [comment]
> @omar2886 I send you instructions to functions you need to check, nothing else will help you. The code returns sometime before inserting the records, find where it is failing and we can move on. 👍

Thanks! I didn't understand at that moment your message, now I see. I understand the concept of what you're proposing, I'm just not sure how to proceed and how this could affect an installation that's live and running public

**Comment by Hlavtox** [comment]
@omar2886 Well, you could do it at night, I doubt they will notice :D

1. The function to update taxes is called here. Check that the payment module is not overriding validateOrder function.
https://github.com/PrestaShop/PrestaShop/blob/326a1f707bf4e3d1748114297c1b979f4766484c/classes/PaymentModule.php#L721

2. If the function here is called, check why it's failing. There is only one return, if there is no tax rows. Check that it actually returns some tax rows.
https://github.com/PrestaShop/PrestaShop/blob/326a1f707bf4e3d1748114297c1b979f4766484c/classes/order/Order.php#L2660

Contact me on Slack if you want, I will help you.

**Comment by khouloudbelguith** [comment]
@omar2886, In fact I checked PS1785 & PS1778
I have this structure
![image](https://user-images.githubusercontent.com/16067358/161278697-8d2073b5-beeb-4df7-85a5-7347bb450a4f.png)
Also, I checked an old version PS16124 => same structure of the table `PREFIX_order_detail_tax`
https://github.com/PrestaShop/PrestaShop/blob/1.6.1.24/install-dev/data/db_structure.sql#L1153_L1160

Could you please check?
Do you think it is a bug?

Thanks!

**Comment by omar2886** [comment]
> @omar2886, In fact I checked PS1785 & PS1778 I have this structure ![image](https://user-images.githubusercontent.com/16067358/161278697-8d2073b5-beeb-4df7-85a5-7347bb450a4f.png) Also, I checked an old version PS16124 => same structure of the table `PREFIX_order_detail_tax` https://github.com/PrestaShop/PrestaShop/blob/1.6.1.24/install-dev/data/db_structure.sql#L1153_L1160
> 
> Could you please check? Do you think it is a bug?
> 
> Thanks!

Seem to be same for me!
<img width="919" alt="Captura de Pantalla 2022-04-01 a las 15 51 41" src="https://user-images.githubusercontent.com/12675798/161298756-97434c40-9908-47a9-b23a-1912b252e55d.png">

**Comment by khouloudbelguith** [comment]
@omar2886, I tried with PS1785.
I checked the table `Prefix_order_detail`
`select id_order_detail, tax_name, tax_rate from Prefix_order_detail`
![image](https://user-images.githubusercontent.com/16067358/161308612-bf9e382a-159b-4f7a-9089-9299d3ee6f88.png)

I checked the table `Prefix_order_detail_tax`, the record is well saved
![image](https://user-images.githubusercontent.com/16067358/161308798-1724856e-0f50-43f8-80af-185db860309d.png)

In your case, it is empty?

Thanks!

**Comment by omar2886** [comment]
> @omar2886, I tried with PS1785. I checked the table `Prefix_order_detail` `select id_order_detail, tax_name, tax_rate from Prefix_order_detail` ![image](https://user-images.githubusercontent.com/16067358/161308612-bf9e382a-159b-4f7a-9089-9299d3ee6f88.png)
> 
> I checked the table `Prefix_order_detail_tax`, the record is well saved ![image](https://user-images.githubusercontent.com/16067358/161308798-1724856e-0f50-43f8-80af-185db860309d.png)
> 
> In your case, it is empty?
> 
> Thanks!

I think you've made a good point here, I think there are some discrepancies
<img width="487" alt="Captura de Pantalla 2022-04-01 a las 17 21 36" src="https://user-images.githubusercontent.com/12675798/161313931-b14ad333-7800-4b8b-b689-c40b913f536f.png">
<img width="343" alt="Captura de Pantalla 2022-04-01 a las 17 23 21" src="https://user-images.githubusercontent.com/12675798/161313947-05d02187-54e5-4324-8eba-532718277743.png">
![screen](https://user-images.githubusercontent.com/12675798/161314886-7183cb61-f3f3-4e30-bd8f-564ae0fa6a32.jpg)

**Comment by matthieu-rolland** [comment]
test comment for issuebot

**Comment by hibatallahAouadni** [comment]
Hello @omar2886 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is fixed on 1.7.8.5. Check the attached screen record below:

https://user-images.githubusercontent.com/23308427/161556765-006470df-911c-4b86-92ab-e96326c49755.mp4

We will close this issue.

Thanks!

**Comment by omar2886** [comment]
> Hello @omar2886
> 
> Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is fixed on 1.7.8.5. Check the attached screen record below:
> 
>  issue_28056.mp4 
> We will close this issue.
> 
> Thanks!

Thanks @hibatallahAouadni , then if there's a fix, can you please let me know where it is so I can fix it? if it's just changing a TPL for example, adding the one from 1.7.8.5 in substitution for the one I have from 1.7.6, or maybe only few lines of code. The problem seem to be somewhere where the function to write on ps_order_detail is triggered, right?

**Comment by hibatallahAouadni** [comment]
Hello @omar2886 

Why you don't want to upgrade your shop to 1.7.8.5?
Otherwise, you can ask your question in the [public Slack channel](https://prestashop.slack.com).

Thank you

**Comment by omar2886** [comment]
> Hello @omar2886
> 
> Why you don't want to upgrade your shop to 1.7.8.5? Otherwise, you can ask your question in the [public Slack channel](https://prestashop.slack.com).
> 
> Thank you

i took me 2 years to upgrade from 1.6 to 1.7 with various "Prestashop Partners", it was a nightmare, it's a very complex and risky thing to do for a Prestashop that has been running for many years already. Maybe after the release of 1.8, once it's totally stable I'd think of starting all over again
