### ISSUE TITLE
Don't reassign cart global vars in front controller

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#28067]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Don't reassign cart global vars in front controller.

### Steps to reproduce

Remove (smarty assign) cart presented in order or cart  front controller and see that it does not change anything in FO you can always access cart presented object in smarty. Because it has already been assigned in the front controller parent class

### PrestaShop version(s) where the bug happened

develop

**Comment by hibatallahAouadni** [comment]
Hello @PululuK 

As discussed in the related PR, this issue is too technical :sweat_smile: 
So, ping @PrestaShop/prestashop-core-developers can someone please reproduce the issue :pray: 

Thanks for your PR :rocket:

**Comment by kpodemski** [comment]
@hibatallahAouadni 

I wouldn't search for a reproducing of the issue. It's a refacto that makes code simpler. With these changes, it's worth checking if the default steps of ordering and managing products in the cart work as expected.

**Comment by matks** [comment]
I think @kpodemski message approves the PR and I also approve it
