### ISSUE TITLE
statsdata module is incompatible with latest jQuery and throws errors

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#28069]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Statsdata module is using .live method, which is incompatible with latest jQuery 3 and throws errors into browser console.

See: https://github.com/PrestaShop/statsdata/blob/dev/statsdata.php#L129

### Expected behavior

Module should not be using this method.

### Steps to reproduce

1. Rebuild core.js without a jQuery migrate.
2. Install statsdatamodule.
3. Go to FO and check console on any page.

---
1. Go to `themes` folder
2. Delete jquery-migrate from `package.json` and from `_core/js/theme.js`
4. Run `npm install` and `npm run build`
5. Install `statsdatamodule`
6. Enable options and save 
![image](https://user-images.githubusercontent.com/16067358/163404561-d061a1db-785f-4c53-8bb1-0b6b4f93334c.png)
7. Go to FO and check console on any page

### PrestaShop version(s) where the bug happened

develop

### If your bug is related to a module, specify its name and its version

statsdata

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

I manage to reproduce the issue with 177x, 178x and develop branch using the statsdata v2.1.0.
![image](https://user-images.githubusercontent.com/16067358/163404312-e9ab7251-6660-4d2b-8b79-0d2313875f34.png)

Thanks for the PR!
