### ISSUE TITLE
Introduce select2 in long select options

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#28065]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Add the select2 in the selectors with many options

![image](https://user-images.githubusercontent.com/16455155/160648940-06ac0c4c-7241-4cef-9922-1c1f1e93c4f5.png)

### Describe the solution you'd like

Use select2 in follow pages : 
![image](https://user-images.githubusercontent.com/16455155/160649405-4a6808af-9f6e-4075-9bfa-5d1d833c8b92.png)

# Catalog

### Product 

- [x] Default Category (old and new page) 

### Supplier 

- [x] Country and state selector

### Manufacturer address

- [x] Country and state selector

# Customer

### Customer

- [x]  Default customer group 

### Address

- [x] Country and state selector

# Shipping

### Preferences

- [x] Default carrier 

# Shop parameters

###  General

- [x] Main Shop Activity selector

###  Order settings 

- [x]  Page for terms and conditions 

# Order

### Order

- [x] update status
- [x] Add form : payment and status selector

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @PululuK 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Thanks for your PR :muscle: 

Thank you
