### ISSUE TITLE
BO - Cannot edit color in Apparence (Error message is displayed) of blockreassurance module v5.1.0 and the blocks icons are not visible in FO 

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#28063]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Cannot edit color in Apparence (colors are displayed in gray) of blockreassurance module v5.1.0 - dev branch 
when install the module in a selected shop ==> In this current shop : Apparence OK :heavy_check_mark: 
The other shops : Apparence NOK :x: 

![image](https://user-images.githubusercontent.com/92912932/160646817-cda21563-6879-4c41-be94-588aa32c8846.png)

This is a regression of the module and not related to PrestaShop version

Here the different attachments 
PS1778 :x: 

https://user-images.githubusercontent.com/92912932/160640300-f8cf3011-6050-41c0-a263-3f773b696af6.mp4

https://user-images.githubusercontent.com/92912932/160640399-7be612a0-40a7-4966-9a70-d4ae7510d191.mp4

develop :x: 

https://user-images.githubusercontent.com/92912932/160643920-e485e5ed-0970-4f5c-8859-5ee67baa9e98.mp4

**The impact of this issue is** : the blocks are not visible in FO because the background color is white
![image](https://user-images.githubusercontent.com/92912932/160642574-99e2eb06-69ce-457e-9519-d1f55746d593.png)

### Expected behavior

The default background color should be like this in all configured shops 
![image](https://user-images.githubusercontent.com/92912932/160643214-cc5a2456-2dc0-439c-9c28-cae0ea982d05.png)

### Steps to reproduce

1. Enable multistore and add new shops
2. Select a shop in module manager page (Default shop or any other shop)
3. BO > Modules > Search for Customer reassurance module (blockreassurance)
**Test blockreassurance with dev branch**
4. Uninstall the module v5.0.0
5. Install the blockreassurance module v5.1.0 from git > dev branch (with git clone)
6. Under modules folder > Run the following

```
git clone git@github.com:PrestaShop/blockreassurance.git
cd blockreassurance
git pull --rebase origin dev
composer install
```
7. BO > Modules > install blockreassurance v5.1.0
8. Check the Apparence color of the current selected Shop (Which the module have been installed) : OK
9. Change any other shop
10. Check the Apparence color of this new selected Shop : NOK
11. Click on view my shop in FO : the blocks icons are not displayed

### PrestaShop version(s) where the bug happened

1.7.7.8 & 1.7.8.x & develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

blockreassurance v5.0.1 (dev branch)

**Comment by florine2623** [comment]
This is fixed on module Customer Reassurance v5.1.4. So I'm closing the issue.


https://github.com/PrestaShop/PrestaShop/assets/16019289/63c8f767-68c9-4c29-8171-01bf8a8c0459
