### ISSUE TITLE
BO - Titles are not well displayed (overlap labels) with mobile of blockreassurance module

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#28064]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Titles are not well displayed (overlap labels) with mobile

PS 1778 blockreassurance v5.1.0  :x: 
![image](https://user-images.githubusercontent.com/92912932/160648923-3cf7c268-50c6-4b0c-9398-f73e83631412.png)

develop blockreassurance v5.1.0  :x: 
![image](https://user-images.githubusercontent.com/92912932/160649135-d2570afe-de2e-41c4-bf07-8fb22ea300d3.png)

blockreassurance v5.0.0 
![image](https://user-images.githubusercontent.com/92912932/160650080-3e844e9d-e664-4864-b7e6-2bdead8d393f.png)

So, this issue is not a regression module neither PrestaShop version.

### Expected behavior

The block titles are well displayed with mobile

### Steps to reproduce

Use a mobile to test this case : 

1. BO > Module manager page
2. Search for blockreassurance module
3. Click on Configure
4. See error >> The titles are not well displayed

### PrestaShop version(s) where the bug happened

1.7.7.8 & 1.7.8.x & develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

blockreassurance v5.0.0 and v5.0.1

**Comment by ghost** [comment]
Fixed by : https://github.com/PrestaShop/blockreassurance/pull/432
