### ISSUE TITLE
You should be able to skip the header row during csv export

### ISSUE THREAD

**Issue by Shoprunners** [PrestaShop/PrestaShop#28073]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

I want to use the buildt-in CSVResponse class to create a CSV file. This class is missing the functionality to skip export of header row, which limits the usage

### Describe the solution you'd like

Class should offer a parameter to set, if header row will be exported or not.

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @Shoprunners 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Thanks for your PR :rocket: 

Thank you

**Comment by fabienvallon** [comment]
LGTM
