### ISSUE TITLE
BO - Cannot install modules in module manager with Spanish language on develop

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#28084]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Cannot install modules (via drag and drog, upload module) in module manager with Spanish language on develop 

PS1785 : OK :heavy_check_mark: 

https://user-images.githubusercontent.com/92912932/161003377-54226534-0d01-41a8-a1dd-65a81bcfbd39.mp4

develop : NOK :x: 

https://user-images.githubusercontent.com/92912932/161003459-20644110-75d2-410f-82ad-833ffe1dc0b2.mp4

### Expected behavior

Modules are well installed with Spanish 

### Steps to reproduce

1. Change the Shop language in Spanish
2. Go to BO > IMPROVE > Module manager
3. Click on Upload module 
4. Click on Select file ==> See Error (Blocked and cannot install module)
5. Use drag and drop of the module ==> See Error (Blocked and cannot install module)

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

**Comment by Progi1984** [comment]
@Julievrz It seems we have a problem with spanish translation :

```xml
      <trans-unit id="8f7168b76e182d2c1dd8769fa23fbdbd" approved="yes">
        <source>We strongly advise you to upgrade the modules on maintenance mode to avoid any cache issues.</source>
        <target state="final">Le recomendamos encarecidamente que actualice los módulos en modo de mantenimiento para evitar problemas de caché. 
</target>
        <note>Line: 45</note>
      </trans-unit>
```

If I remove the break lin after `problemas de caché`, I haven't got anymore the problem.

**Comment by Julievrz** [comment]
Sorry for the late answer. On Crowdin, everything seems normal. There's no line break (see screenshot)
![image](https://user-images.githubusercontent.com/70583503/162744674-d0a454d8-d693-4ce3-b68d-3a095a362b40.png)
I've tried to delete all previous translations and validate the string again. Hope that helps.

**Comment by Progi1984** [comment]
`https://i18n.prestashop.com/translations/8.0.0/es-ES/es-ES.zip` : File `AdminModulesNotification.es-ES.xlf` > ID `8f7168b76e182d2c1dd8769fa23fbdbd` => break line is present :red_circle: 
`https://i18n.prestashop.com/translations/1.7.8.0/es-ES/es-ES.zip` : File `AdminModulesNotification.es-ES.xlf` > ID `8f7168b76e182d2c1dd8769fa23fbdbd`  => break line is not present :heavy_check_mark:

**Comment by matthieu-rolland** [comment]
fixed here: https://github.com/PrestaShop/TranslationFiles/pull/22
