### ISSUE TITLE
.browserslistrc file shouldn't be located in themes folder

### ISSUE THREAD

**Issue by micka-fdz** [PrestaShop/PrestaShop#28082]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When we use `autoprefixer` on a theme without `.browserslistrc` file, autoprefixer load `/themes/.browserslistrc` file.

This file shouldn't be located here to avoid being loaded by themes.

### Steps to reproduce

1. Compile a theme with `autoprefixer` and without `.browserslistrc` file
2. Note that compiled css file contains prefixes corresponding to browsers list defined in `/themes/.browserslistrc` file
3. Remove `/themes/.browserslistrc` file
4. Note that compiled css file contains prefixes corresponding to default browsers list as it should

### PrestaShop version(s) where the bug happened

1.7.8.3 and later

**Comment by micka-fdz** [comment]
Already discussed with @NeOMakinG.

**Comment by NeOMakinG** [comment]
Yeah, it's pretty hard to reproduce if you're not developing a new theme, looks legit to me and I'll try to get a look.

In case someone wants to work on it:
- The `.browserlistrc` files in the `themes` folder should be removed and this list should be added to where eslint or webpack needs it

**Comment by hibatallahAouadni** [comment]
@NeOMakinG I will trust you :sweat_smile:

**Comment by matks** [comment]
@NeOMakinG is right 👍

**Comment by Progi1984** [comment]
Fixed by @micka-fdz in #28101 and tested by @AureRita
