### ISSUE TITLE
Find a bug with Specific prices with: quantity discount - with fixed price - Tax

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#28092]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi
I think to have found a bug on Specific prices when the tax is enabled
when the tax is disabled all seem ok

I get this error when I create a discount by quantity and fixed price
in the front office the prices values of discounted table is not right, instead it is right in the discount shown near the product price and in the cart summary

I show you an example:
when the tax is not active all is ok

![2](https://user-images.githubusercontent.com/653230/161056295-c5bed2e7-c18d-48f0-9844-928b39e96d20.png)
![4](https://user-images.githubusercontent.com/653230/161056303-7fd99cd9-7086-4707-81c0-ca4268c04682.png)

instead when I set the tax = 22% the prices shown in the discount table are wrong

![5](https://user-images.githubusercontent.com/653230/161056434-a7f30563-5368-44e1-b4e5-f2f5ffbbdf10.png)
![7](https://user-images.githubusercontent.com/653230/161057258-25aae2c1-e757-4074-bffd-4ed480196136.png)

I set:
100€ as the basic price and 50€ the fixed price inside each specific price

I think the problem is when the "Apply a discount of" is a fixed amount

bye

### Expected behavior

the discount prices shown in the front table (product page) should be the same as those shown next to the product price as quantities vary

### Steps to reproduce

1. go in the back-office and add 2-3 specific like I show in the images
2. try with and without tax
3. check in the front-office the wrong prices of "Unit discount" and "You Save"

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Hello @maofree 

Did you encounter this issue only with PS1785 or even with older versions?
Waiting for your feedback.

Thanks!

**Comment by Maofree** [comment]
Hi
I think it is present on 1.7.8.x
I've upgraded a website from 1.7.6 and before was ok
in his site, the pricing errors are much greater, much wrong. I'm going to do some tests to see if the theme can affect, but I don't think so since they are variables that come from php files of the main prestashop files

**Comment by Maofree** [comment]
![2](https://user-images.githubusercontent.com/653230/161118132-9bdd6180-10bc-46b0-a201-7bf27a9d3a04.png)

with a var_dump I see that the reduction_with_tax is less than reduction

**Comment by khouloudbelguith** [comment]
Hi @maofree,

I think this issue is fixed with this PR: https://github.com/PrestaShop/PrestaShop/pull/16138 which fixes those issues: https://github.com/PrestaShop/PrestaShop/issues/15835 & https://github.com/PrestaShop/PrestaShop/issues/15866.

Could you please confirm?

Thanks!

**Comment by Maofree** [comment]
I see that the fix has been applied to prestashop 8 files, which do not exist on prestashop 1.7.8, so I cannot confirm

can you give me a link to download the zip of prestashop 8 to start to study it?
I know it hasn't been released yet, but what if there was a zip of the development stage

**Comment by khouloudbelguith** [comment]
@maofree, I tried with develop branch
**BO**
![image](https://user-images.githubusercontent.com/16067358/161272813-c3b020bc-fa5d-4a83-960b-28134d265aef.png)
**FO**
![image](https://user-images.githubusercontent.com/16067358/161272839-39849970-8cf1-4fdc-abba-4638f140268e.png)
I attached a screen record

https://user-images.githubusercontent.com/16067358/161273066-c030c25b-708d-4911-aaae-04796ddaff10.mp4

About the develop branch, you can download the develop branch from this link: https://nightly.prestashop.com/ as described here: https://build.prestashop.com/news/E2E-testing-from-the-trenches-our-new-approach/
![image](https://user-images.githubusercontent.com/16067358/161273417-3e8423ee-af4d-4807-81a7-9b3041e8def2.png)
This issue is fixed in the next release PS8.0.0
Your ticket is a duplicate of #15866
So, I close it.
Thanks!

Best regards, Khouloud

**Comment by khouloudbelguith** [comment]
Duplicate of #15866
