### ISSUE TITLE
Stats - swapped browsers

### ISSUE THREAD

**Issue by pewube** [PrestaShop/PrestaShop#28099]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Chrome and Safari statistics (browsers and operating systems) are swapped.
The number of Safari browser visits is the same as that of Android system, while Chrome corresponds to the number of MacOsX. 

![image](https://user-images.githubusercontent.com/58422606/161213372-86c21a12-9721-44e4-b335-b3455e224939.png)
![image](https://user-images.githubusercontent.com/58422606/161213554-2a6c2271-c020-4e13-ae39-915c47606416.png)

### Expected behavior

The number of Safari visits should match the number of Apple operating systems visits.

### Steps to reproduce

1. Go to Statistics -> Browsers and operating systems
2. Compare pie charts of browsers and operating systems visits 

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4.26

### If your bug is related to a module, specify its name and its version

Browsers and operating systems

**Comment by khouloudbelguith** [comment]
Hello @pewube,

This module: https://github.com/PrestaShop/statsequipment has been archived, it’s no longer maintained but you still can fork it if you need it for your shop.
Also, let us know if you are voluntary to maintain this module.
Thanks for your understanding!
