### ISSUE TITLE
XLF on theme export and theme translation export should have source-language="en"

### ISSUE THREAD

**Issue by rodriciru** [PrestaShop/PrestaShop#28091]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When export xlf of theme or the whole theme, source-languge values is my own locale, but i think it should be en as source is in english

![Captura de pantalla 2022-03-31 111702](https://user-images.githubusercontent.com/10741347/161022815-59d5be07-d185-4013-a618-e0cb8db41933.jpg)

### Expected behavior

  <file original="C:\XXX\XX\XX\adminXXX" **source-language="en"** target-language="es-ES" datatype="plaintext">

### Steps to reproduce

1. Login into BO
2. Go to translations page
3. Export theme translation in other language than English
4. You will see in XLF files the attribute source-language equals to target-language (in my case es-ES) but source its in english

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @rodriciru 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must provide clear and concise steps to reproduce the issue**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by rodriciru** [comment]
Hi. @hibatallahAouadni 
I update my desc to add more info.
Please open it if you think that is a bug
Thanks

**Comment by hibatallahAouadni** [comment]
Hello @rodriciru 

Thanks for the details :pray: 
Could you please check these issues #26549 & #14968 seems related to yours.
Waiting for your feedback.

Thanks!

**Comment by rodriciru** [comment]
I only complain about source-language attribute in <file> tag in .xlf.
This issues are related, but not the same
Also @atomiix have a PR wich maybe it fixed this issues, but not this one
