### ISSUE TITLE
ERROR BO PRESTASHOP 1.7.8.1 AFTER INSTALL UPDATE LAST MODULE PRESTASHOP CHECKOUT

### ISSUE THREAD

**Issue by MEGA911** [PrestaShop/PrestaShop#28109]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello, Can you help me?
I have an error in my prestashop Back-Office just after install the update module of Prestashop Checkout.
Now when i clic in my BO on "Modules" => "Gestionnaire de modules" 
I have this error :

Oups... une erreur inattendue semble s'être produite

Compile Error: require_once(): Failed opening required '/home/serumew/www/modules/contactform/recaptcha.php' (include_path='/home/serumew/www/vendor/pear/pear_exception:/home/serumew/www/vendor/pear/console_getopt:/home/serumew/www/vendor/pear/pear-core-minimal/src:/home/serumew/www/vendor/pear/archive_tar:.:/usr/local/php7.4/lib/php')

[Symfony\Component\Debug\Exception\FatalErrorException 0]

------------------------------------------

If i activate the debug mode => When I clic in my BO on "Modules" => "Gestionnaire de modules" I have this error :

FatalErrorException
HTTP 500 Internal Server Error
Compile Error: PrestaShop\PrestaShop\Adapter\Module\Module::instanciateLegacyModule(): Failed opening required '/home/serumew/www/modules/contactform/recaptcha.php' (include_path='/home/serumew/www/vendor/pear/pear_exception:/home/serumew/www/vendor/pear/console_getopt:/home/serumew/www/vendor/pear/pear-core-minimal/src:/home/serumew/www/vendor/pear/archive_tar:.:/usr/local/php7.4/lib/php')

	•	ExceptionLogs 2Stack Trace
Symfony\Component\Debug\Exception\
FatalErrorException

in src/Adapter/Module/Module.php (line 371)
	366.	        $path = $this->disk->get('path', ''); // Variable needed for empty() test
	367.	        if (empty($path)) {
	368.	            $this->disk->set('path', _PS_MODULE_DIR_ . DIRECTORY_SEPARATOR . $this->attributes->get('name'));
	369.	        }
	370.	        // End of temporary content
	371.	        require_once $this->disk->get('path') . DIRECTORY_SEPARATOR . $this->attributes->get('name') . '.php';
	372.	        $this->instance = LegacyModule::getInstanceByName($this->attributes->get('name'));
	373.	    }
	374.	
	375.	    /**
	376.	     * @param string $attribute

### Expected behavior

Can you help me to debug this problem?  Do you want an access to my BO Prestashop ?

### Steps to reproduce

In my BO on "Module" => Go to =>  "Gestionnaire de modules" => and clic => You can see the error :

Oups... une erreur inattendue semble s'être produite

Compile Error: require_once(): Failed opening required '/home/serumew/www/modules/contactform/recaptcha.php' (include_path='/home/serumew/www/vendor/pear/pear_exception:/home/serumew/www/vendor/pear/console_getopt:/home/serumew/www/vendor/pear/pear-core-minimal/src:/home/serumew/www/vendor/pear/archive_tar:.:/usr/local/php7.4/lib/php')

[Symfony\Component\Debug\Exception\FatalErrorException 0]

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.4.25

### If your bug is related to a module, specify its name and its version

Pestashop Checkout install last version

**Comment by khouloudbelguith** [comment]
Hi @MEGA911,

I see this error `'/home/serumew/www/modules/contactform/recaptcha.php'` in your log, did you use a module Recaptcha?
I tried to check the native module contactform https://github.com/PrestaShop/contactform, but there is no file `recaptcha.php`
In my case, I did not manage to reproduce the issue with PS1785.
![image](https://user-images.githubusercontent.com/16067358/161307112-a10e5c5b-0e24-4e2c-a4e2-2d43d36a7554.png)

Thanks!

**Comment by MEGA911** [comment]
Hello,
Tks for your quick reply
Yes I use Recaptcha module => But the bug appear just after install the last module of prestashop checkout => i don't why and i don’t understand the relation whith Recaptcha module ? Now i can't access to my "Gestionnaire de modules" => Do you have an issue to debug this big problem for me ?

**Comment by MEGA911** [comment]
Do you want access to my BO to see the bug in live?

**Comment by MEGA911** [comment]
FYI => I install the last update of Prestashop Checkout in maintenance mode for not to have a cache problem => And just after this install update module => Impossible to me to access at my  "modules manager" => I really regret to install this update => Now i don't know what can i do => Please help me => I am in panic

**Comment by khouloudbelguith** [comment]
@MEGA911, 

The checkout PrestaShop module is not a native module, you need to contact the module author using this link: `support-checkout-download@prestashop.com`

The Recaptcha module is not provided by PrestaShop, as it's not a module provided by Prestashop, we can't do anything with this.
You should contact the module author via your addons.prestashop.com account, they are the only ones to help you with it.


Thanks for your understanding!

**Comment by MEGA911** [comment]
Tks for your reply => I contact now the support on addons prestashop
