### ISSUE TITLE
Faceted search bug with results

### ISSUE THREAD

**Issue by thibaultNicolas** [PrestaShop/PrestaShop#28107]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When i click on a filter options, even if there is products with the declinaison, the results is 0... Some filters works fine, others dont...

![Screenshot (41)](https://user-images.githubusercontent.com/68305913/161294219-bdb2a91c-9d87-421d-95cf-ebcc74f30466.png)

### Expected behavior

supposed to have results higher than 0

### Steps to reproduce

1. go to https://groupenapert.com/
2. click on magasiner
3. select blanc in the faceted search
4. See the results

### PrestaShop version(s) where the bug happened

1.7.8

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

facetedsearch

**Comment by khouloudbelguith** [comment]
Hi @thibaultNicolas,

Could you please try to follow these steps:

1. Go to BO > Modules > Module Manager page and search the `ps_facetedsearch`
2. Click on configure page
3. Click on the buttons:

- Index all missing prices
- Rebuild entire price index
- Build attributes and features indexes
- Clear cache

4. Go to FO > check the filter

I attached a screen record

https://user-images.githubusercontent.com/16067358/161297403-ac316f17-6942-4a7d-a8d9-35da1390ef8f.mp4

Thanks to check and feedback.

**Comment by thibaultNicolas** [comment]
tried it, and same issue...
@khouloudbelguith

**Comment by khouloudbelguith** [comment]
@thibaultNicolas, could you please provide us with more info? We need more details to understand how we can reproduce your issue:

 - server setup and configuration
 - PrestaShop version (source), is it a fresh install or an upgrade from the previous version?
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by thibaultNicolas** [comment]
here is the url 
you can see the issue when clicking on the filter "blanc"

@khouloudbelguith 

https://napert.goimago.com/qc/82-tous-les-produits

**Comment by khouloudbelguith** [comment]
@thibaultNicolas, what is the exact version of the ps_facetedsearch module did you use?

Thanks:

**Comment by thibaultNicolas** [comment]
v3.7.1 - par PrestaShop

@khouloudbelguith

**Comment by khouloudbelguith** [comment]
@thibaultNicolas,

Did you try to reproduce the issue using the classic theme?

Thanks!

**Comment by thibaultNicolas** [comment]
yes, same thing @khouloudbelguith

**Comment by khouloudbelguith** [comment]
@thibaultNicolas, could you please provide me a screen record using the classic theme & the debug mode is enabled?
![image](https://user-images.githubusercontent.com/16067358/161307492-9ba73121-3e30-490e-939e-d9386b3f1ec9.png)

Thanks!

**Comment by Hlavtox** [comment]
Check that you don't have a feature and attribute with the same name.

Otherwise, this is probably caused by data incosistency. We need to find where in that case. :-)

**Comment by khouloudbelguith** [comment]
@Hlavtox, @thibaultNicolas, do you think it is the same issue: https://github.com/PrestaShop/PrestaShop/issues/15635?

Thanks!

**Comment by thibaultNicolas** [comment]
@khouloudbelguith seems similar yes

**Comment by thibaultNicolas** [comment]
@khouloudbelguith The issue is now ok! There was two attributes with the name white, even if they are not in the same attribute category...

**Comment by hibatallahAouadni** [comment]
Hello @thibaultNicolas 

> The issue is now ok!

How did you fix the issue? and do you only reproduce the issue when you have two attributes with the same name?
Please check and feedback.

Thanks!

**Comment by thibaultNicolas** [comment]
@khouloudbelguith  @Hlavtox 

The hero image of the product is not changing when i click on a different color filter. Only the thumnails are changing colors...

**Comment by hibatallahAouadni** [comment]
Hello @thibaultNicolas 

It seems that you doesn't encounter an issue with facetedSearch, so I close the issue!
Otherwise, if you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you
