### ISSUE TITLE
Allow delete modules from the "Modules catalog" tab

### ISSUE THREAD

**Issue by Caleydon** [PrestaShop/PrestaShop#28114]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

**Allow delete modules from the "Modules catalog" tab**

### Describe the solution you'd like

Please could make missing feature to allowing delete modules from the "Modules catalog" tab? This feature really missing and only way how to remove not installed modules are via FTP. The PrestaShop do not allow full module management that was available in all previous PrestaShop generations.

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by Hlavtox** [comment]
Module catalog page is gone on develop, all is done from the module manager like in 1.6. ;-)

**Comment by Caleydon** [comment]
Oh, great news. Thank you.

**Comment by hibatallahAouadni** [comment]
Hello @Caleydon 

As @Hlavtox said, the module catalog page is gone on the next patch 8.0.0 :tada: 
Closing the issue!

PS: thanks @Hlavtox for your quick replies :superhero: 

Thanks!
