### ISSUE TITLE
"See more" / "See less" links in the "Module manager" tab

### ISSUE THREAD

**Issue by Caleydon** [PrestaShop/PrestaShop#28116]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

**"See more" / "See less" links in the "Module manager" tab**

![See-more-less](https://user-images.githubusercontent.com/2806752/161434772-411dc7bf-5001-436e-8b56-8ac49137339f.png)

### Describe the solution you'd like

Please kill the annoying "See more" / "See less" links in the "Module manager" tab. The modules page is dedicated to list the modules and work with them. Why do you want to hiding the modules on this page and force merchants and developers to make a few more useless clicks in order to see all modules installed in his PrestaShop? What is the idea behind the feature showing only first 6 modules in each category? What is benefit of this feature?

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by Hlavtox** [comment]
+1 Absolutely agree, soooo anoying :-)

**Comment by hibatallahAouadni** [comment]
Hello @Caleydon 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by MatShir** [comment]
Completely agree 👍

**Comment by Caleydon** [comment]
I eliminate this "feature" by edit following file:

`/ADMIN-FOLDER/themes/new-theme/public/module.bundle.js`

and change the value from

`this.DEFAULT_MAX_PER_CATEGORIES=6`

to 

`this.DEFAULT_MAX_PER_CATEGORIES=100`

**Comment by hibatallahAouadni** [comment]
Hello @Caleydon 

I see you manage to get the problem fixed, so please contribute the fix back to the project as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Hlavtox** [comment]
@Caleydon I will remove it to 8.1 👍

**Comment by Caleydon** [comment]
@Hlavtox Thank you.

**Comment by Hlavtox** [comment]
@Caleydon Too lazy, v9 :D
