### ISSUE TITLE
"Upgrade" button overriding "Settings" button in the module list

### ISSUE THREAD

**Issue by Caleydon** [PrestaShop/PrestaShop#28115]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

**"Upgrade" button overriding "Settings" button in the module list**

Please, could you make module upgrade button available only in the "Updates" tab and not showing "Upgrade" button in the module list? As result, the merchant will be no disturbing by any upgrade buttons and this action leave for developer that have access into "Updates" tab.

### Describe the solution you'd like

Reasons: The merchants want to using their eshop for their business and selling the products. Most of them doesn't want to know how PrestaShop working and how to maintain CMS or update modules. They don't live in PrestaShop world and they using the CMS only as tool for their business. They contact/asking the developer to upgrade after period of a few years or when any problem occurs. The most annoying thing is "Upgrade" button forcing them to update modules in the module list when they want to change something in the particular module. The "Upgrade" button override "Settings" button. Without any knowledge what update brings, without change log that is always an empty (or in English only) for all build-in modules (also lot of merchants don't speak English). Also sometimes developer made code changes in build-in modules due merchant request to achieve needed functionality. The module upgrade that always force make upgrade action will delete these changes.

![button-upgrade](https://user-images.githubusercontent.com/2806752/161434787-76d73f19-4d3f-4b57-b5c8-32cd6deabfc0.png)

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by Hlavtox** [comment]
Already done, test develop

**Comment by hibatallahAouadni** [comment]
Hello @Caleydon 

As @Hlavtox mentioned the feature is well implemented on develop, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/161549710-9d0da61f-1863-430b-8963-121b5787f663.mp4

Closing the issue!
Thanks!
