### ISSUE TITLE
Prestashop docker no translation for backoffice menu

### ISSUE THREAD

**Issue by tdzierza** [PrestaShop/PrestaShop#28128]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Language options are set

PRESTASHOP_COUNTRY
PRESTASHOP_LANGUAGE

After installation back office menu is only in English
Roles and Permission also are not translated

Maybe it's depend when I use the latest version

Is it possible to update this translations ?

### Steps to reproduce

Logging into the Back office

### PrestaShop version(s) where the bug happened

1.7.8.4

**Comment by florine2623** [comment]
Hello @tdzierza ,

What PRESTASHOP_COUNTRY and PRESTASHOP_LANGUAGE did you choose ?

The defaults values are PRESTASHOP_COUNTRY=GB and PRESTASHOP_LANGUAGE=en

**Comment by tdzierza** [comment]
- PRESTASHOP_COUNTRY=pl 
- PRESTASHOP_LANGUAGE=pl

But almost everywhere (where are translations) is pl language but only: backoffice menu and permission/roles not.
I was searching translations but can't find. I checked db and there are english names. Is it possible to change menu language after installation ?

**Comment by rickygzz** [comment]
Hello,

I confirm the bug for the 1.7.8.5 version.

I imported the Polish language

![image](https://user-images.githubusercontent.com/36200981/161743128-021c42c0-c057-47ec-bcfa-0c16794e2b2a.png)

Then went to Configure / Advanced Parameters / Team / Employees

![image](https://user-images.githubusercontent.com/36200981/161743290-8f79388d-b2e4-41bf-a3cc-1c8d3de54001.png)

Edited the current (or desired) admin user. Selected Language = Polski (Polish). Clicked saved.

The BO language didn´t change. I repeated the steps for Spanish and as soon as I clicked save, the BO changes to spanish. I repeated again for English and it changed to english as soon as I clicked Save.

I checked Polish translations in Crowdin, and they are almost 100% done. I also downloaded the language pack https://i18n.prestashop.com/translations/1.7.8.5/pl-PL/pl-PL.zip and the translations are there.

So there may be a bug somewhere in the code.

![image](https://user-images.githubusercontent.com/36200981/161744600-02c78cf6-9f37-47b7-aabe-358d09210882.png)

**Comment by florine2623** [comment]
Hello @tdzierza & @rickygzz ,

I have followed this https://hub.docker.com/r/prestashop/prestashop/ and I can't reproduce your issue.
I have Installed my shop in EN, country FR, I downloaded languages : Polish and Arabic and edited my employee language. It looks good :

https://user-images.githubusercontent.com/16019289/161796500-aa776050-0b05-4da5-bbb4-a3a73aa11600.mov

@PrestaShop/qa-functional , could someone try to reproduce it please ?

**Comment by tdzierza** [comment]
But this is not exactly what I did.
I started docker with 
    PRESTASHOP_COUNTRY=pl
    PRESTASHOP_LANGUAGE=pl
at the very beginning.
So should be installed only one language: Polish.
For example is it possible ?

I know that  installation with default English and than changing to other language working. But try to do this first scenario.

And my question is. If it somehow possible to translate this beck-office menu ? Or maybe I should install English language change to English and than back to Polish ? Anybody know what is the best solution for this ?

**Comment by tdzierza** [comment]
I installed English language set as default. Next I switched back to Polish.
Now in ps_tab_lang I have two language - but unfortunately only English.

id_tab 	id_lang 	name 	
1 	1 	Dashboard
1 	2 	Dashboard
2 	1 	Sell
2 	2 	Sell
3 	1 	Orders
3 	2 	Orders
4 	1 	Orders
4 	2 	Orders
5 	1 	Invoices
5 	2 	Invoices

Maybe this issue is connected https://github.com/PrestaShop/PrestaShop/issues/22531

**Comment by khouloudbelguith** [comment]
Hi @tdzierza,

Thanks for your feedback.
We are aware of this issue, it is added to our debug roadmap.
Your ticket is a duplicate of #27029
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #27029
