### ISSUE TITLE
A 500 internal server error appears on 'Design>Link list > Add new block' page

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#28120]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The nightly report showed us a 500 internal server error on the page 'Design>Link list > Add new block'
-> Screen when debug mode desactivated
![Capture d’écran de 2022-04-04 10-08-55](https://user-images.githubusercontent.com/24647495/161519173-9e4fb29a-97e6-4c99-9fda-504d3dfb2fab.png)
-> Screen when debug mode activated
![Capture d’écran de 2022-04-04 10-06-28](https://user-images.githubusercontent.com/24647495/161518955-a3520dd0-820a-4c2f-9ca8-0bdf0f45d585.png)

### Expected behavior

Add new block form is displayed

### Steps to reproduce

1. Go to Design > Link list > Add new block
2. See the error 

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

Link List v5.0.4

**Comment by Progi1984** [comment]
@atomiix Isn't it relative to your PR ?
