### ISSUE TITLE
Unable to Raise Back Office Order Missing Add to Basket

### ISSUE THREAD

**Issue by shorrog** [PrestaShop/PrestaShop#28125]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If I create a back office order as SuperADMIN everything works fine.  If I use any other profile even if the profile has everything enabled then the CREATE Order page does not display the Basket and the Add to Basket button.
Instead it displays a Cart area where there is a search for a product button, but the search capability does not work. 

### Expected behavior

If I log in as SuperADMIN  and Create an Order  then I get the following screen and I am able to place the order.
![Back office order SUPER ADMIN](https://user-images.githubusercontent.com/16224215/161574257-55adf60f-d31f-445f-a579-f7f781d195f1.jpg)

However if I log in with any other user profile eg Salesman, the Basket is missing. and you are unable to add a product.
![Back office order](https://user-images.githubusercontent.com/16224215/161576985-ba85ef0c-1ef7-4076-8613-41c6dacabebe.jpg)

### Steps to reproduce

Log in to Prestashop admin with a user profile that is not Super Admin
Click on Add new order
search and select a customer
The create order page displays a Cart area but no add to basket button. Furthermore the search for a product fails to work, and displays No Products Found.
![Back office order](https://user-images.githubusercontent.com/16224215/161573271-cd023bd6-b927-42c9-92ac-46b19dd67775.jpg)

### PrestaShop version(s) where the bug happened

1.7.6.4

### PHP version(s) where the bug happened

7.3.11

**Comment by florine2623** [comment]
Hello @shorrog ,

I can't reproduce your issue. It is possible to create an order.
I tested with these profiles : SuperAdmin and Salesman without changeing their permissions, the order are well created.

I close your issue as it is not reproducible.
Thanks!

**Comment by shorrog** [comment]
I found the problem. It was caused by the wrong language being selected for the employee account.  I had selected "English" instead of "English GB (English"). If the former is selected then the shopping basket is not available.
Graham
