### ISSUE TITLE
Product page v2 category edit is annoying

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#28135]
### What is wrong

Just tested the new product page category edit, I think it needs some tweaks in order for merchant not to break their displays out of anger on 10th product. :-)))

- When adding categories, you cannot unselect Home category right away.
- After adding another categories, you still cannot unselect the Home category.
- This works differently on old product page. You can delete a default category and when you deleted it, a **different one gets automatically set as default**.

**Video**
https://drive.google.com/file/d/1ojtqsMvjVnnH7ZxgOktcb7DyhMtv_6Rj/view?usp=sharing

### What I would do

How I think it could work:

- Allow deleting the Home (or any other category) from the list, **if it's not the single one remaining**.
- Deleting a **default category** will make the **default category selectbox** automatically jump to:
  - A) The **next category in the list**
  - B) Or preferably to **the deepest category in the list**. Which is usually the default one anyway, will save some seconds. If two have the same level, just take the lower ID.
- (optional) If some other categories than Home is selected, but Home is still the default category, display a tip somewhere near this choice with a text like: `"We recommend to set the default category other than Home, so you have proper breadcrumbs displayed."`

ping @MatShir @jolelievre

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by florine2623** [comment]
Hello @Hlavtox ,

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 

Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you create it. 

If you or anyone else is willing to [contribute this feature](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/) to the PrestaShop Project, the teams will be happy to help by ensuring that it fits well within the project. Please let us know if that is the case!

Thank you

**Comment by ruchus** [comment]
Totally agree. It's annoying.

**Comment by MatShir** [comment]
Thanks for the feedback, we are looking for a solution :)

**Comment by Hlavtox** [comment]
Any news here?

**Comment by TristanLDD** [comment]
Hi @Hlavtox , thx for your feedback

First, I agree with your suggestion to allow deleting the home or any other category from the list if it's not the last one remaining.  


> Deleting a default category will make the default category selectbox automatically jump to:
A) The next category in the list
B) Or preferably to the deepest category in the list. Which is usually the default one anyway, will save some seconds. If two have the same level, just take the lower ID.

I also think this is relevant and should be integrated, I would go for B) as it would be correct in most of use cases. @MatShir WDYT? 

> (optional) If some other categories than Home is selected, but Home is still the default category, display a tip somewhere near this choice with a text like: "We recommend to set the default category other than Home, so you have proper breadcrumbs displayed."

As the product page isn't fully finished yet this part was't integrated in the beta version but in the mockups we actually display the breadcrumb in order to allow the merchant to have a better view of what the final user will see: 
<img width="1116" alt="Capture d’écran 2022-11-29 à 14 32 44" src="https://user-images.githubusercontent.com/27484094/204543064-f029f950-66cb-4f4f-9ce3-7d67f6031669.png">

Thank you

**Comment by Hlavtox** [comment]
@TristanLDD @MatShir @jolelievre @zuk3975 Guys it would be best if you didn't even have to click some button. Make it work like a tag input with autocomplete. Absolute perfection would be if it automatically added all parents (except the home category).😎

![categories](https://user-images.githubusercontent.com/6097524/205447847-cfdccf43-1b0d-4e8a-bb42-6a7ef0f921b8.png)

**Comment by MatShir** [comment]
🍬

**Comment by zuk3975** [comment]
Main pain point is addressed by this PR https://github.com/PrestaShop/PrestaShop/pull/30772
@MatShir you wanted some description on how it works after the above-mentioned PR. 
So if default category is unselected, then component searches whole tree of selected categories from beginning, and uses the first one found as the default one).
E.g. We have 
```
[ ]Home
    [ ] Accessories
        [✔️ ]Man
        [✔️ ]Woman
    [✔️ ]Clothes (default)

```
if we uncheck "Clothes", then the "Man" will become the default category
