### ISSUE TITLE
[bug collection] Cart rules are a nest of cockroaches

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#28134]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This is a fun bug report. A correct report for all individual bug will follow as investigation advances.

[edited by @matks: I removed the image not to hurt sensible eyes]

There are many problems with cart rules:
- Permission: In a multishop context, an employee with permissions limited to one shop can see all cart rules (#9848, #28139).
- Worse: an employee with access to shop A only can edit and delete cart rules valid in shop B only (#28139)
- Permission again(related to #23082): When selecting all available shop in `Shop selection`, nothing is saved to `ps_cart_rule_shop`, or if there are entries, they are deleted. This is correct if the employee has access to all shop. It is wrong if not. Two consequences:
    - Given a cart rule valid in shop 3 and 4 only, and an employee with access to these two shops. Once the employee edits the cart rule, it becomes corrupt and is now valid in all shops.
    - Given an employee with access to shop 20 only. If he creates a cart rule, the `Shop selection` is not displayed, and the voucher is valid in all shops.
- (#28154) A cart rule without any restriction is valid and applies to any order. A cart rule without restriction should be invalid. Or at lease there should be a red danger message.
- If a cart rule is labelled in currency A it should never be applied to an order labelled in another currency. A cart rule should always be restricted to orders that share the same currency.
- A cart rule is by default in `Tax excluded`. This is not logical. If a cart rule is an amount, it should not have any tax. It is like money and money does not have taxes, only products sold. Anyway, if a cart rule gives a reduction `tax excluded`, does this mean that it is increased by the amount of the tax? Thus the tax will be a surpris to the merchant ?! (see #28165)
- Example that really happened (even though it sounds like coming from a fairy tale):
    - Given a cart rule that offers a reduction of 25 EUR tax excluded on products only, applied to an order of 59.80 CHF of products and 10.50 CHF of shipping
    - Results in an order of 10.50 CHF tax included (A tax included reduction of 59.80 CHF was applied)
    - But in `ps_orders`, we can see, that (oh ultimate confusion), we had 25 CHF of discounts tax excl., 34.80 CHF of tax discounts, a order total of tax included of 10.50 CHF, tax excluded 43.90 CHF and a negative tax of -33.40 CHF
- In cart rule edit form, tab `Conditions`, customer search could be improved (#28156), and product selection is nearly impossible if the shop contains a huge number of products (#28167).

### Expected behavior

- An employee has the right to view, create, edit and delete only cart rules that belongs to the shops where he has permissions to access
- A cart rule that has a reduction amount can only apply to an order in the same currency
- A cart rule should give a `tax included` amount of reduction by default
- The tax offered should relate to the tax rate of the products for which the reduction was granted
- Negative tax should never be possible at all

### Steps to reproduce

1. Do not clean your kitchen (code) for five years (see #9848 Created at: Mon, 23 Oct 2017 15:07:32 +0200)
2. Get cockroaches at the neighbors kitchen
3. Feed well

### PrestaShop version(s) where the bug happened

1.7.8.5 and 1.6.1.1

### PHP version(s) where the bug happened

7.3

**Comment by matks** [comment]
Hi @lmeyer1 I agree with you that CartRule is a nightmare, and I think you forgot to mention one important point: the code that is responsible for the behavior you mention is even worse https://github.com/PrestaShop/PrestaShop/blob/develop/classes/CartRule.php and its sidekick [Product:getPriceStatic](https://github.com/PrestaShop/PrestaShop/blob/29423ec371cd3374c7522ff8b5019e621816e796/classes/Product.php#L3597), also related to overall cart computations.

Multiple attempts have been directed at clearing the mess above and the current code state is actually better than it used to be, and automated tests have been added but this is far from enough.

Unfortunately the level of complexity of the code makes it an extremely complex task to fix bugs within this logic, and it's even harder if multishop is involved.

This is one of the main cause why there are unfixed bugs related to cart rules after many years: the cost of fixing them is sky-high, and everytime we fix a bug somewhere we introduce another one somewhere else, in another cart rule scenario, because not only the code is complex it's only strongly coupled.

Example of such issues https://github.com/PrestaShop/PrestaShop/pull/15171 https://github.com/PrestaShop/PrestaShop/pull/12878 https://github.com/PrestaShop/PrestaShop/pull/16087

**Comment by lmeyer1** [comment]
@matks I will try. At least the permission problems must be resolved. It is just unacceptable that an employee for shop A with no access to shop B can mess up any cart rule in shop B. Also is it inacceptable, that an unaware employee restricted to 1 only shop can offer unrestricted reductions in any and all shops. 
I think the problem of unrelated currency should not be impossible to solve.
What pertains to the calculation of negative taxes, I fear that indeed the code is so convoluted, that there is no cure.

Oh and what are your thoughts about 
> A cart rule is by default in Tax excluded. This is not logical. If a cart rule is an amount, it should not have any tax. It is like money and money does not have taxes, only products sold. Anyway, if a cart rule gives a reduction tax excluded, does this mean that it is increased by the amount of the tax? Thus the tax will be a surprise to the merchant ?!

**Comment by matks** [comment]
About cart rules behavior I have absolutely no opinion 😅  I actually believe this is highly complex domain where "what is the expected behavior" should be a question answered by lawyers (to comply with the law) and product specialists (to find the best interface / flow).

I'm a developer, my favorite interface is a CRUD interface based on forms I'm afraid I should not be allowed to define user interface and workflows 😆

**Comment by matks** [comment]
@lmeyer1 Some people told me they had a jumpscare 😅 about the image so I removed it, I hope you understand we want people to discuss about a technical problem, not throw away their monitor

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

I just edit yoour issue title :wink: 
As we have an EPIC for all cart rules issues #13823 could you please try to clean this bug report and add your analyses and your notices/remarks to the original EPIC in a comment. 
Then we wil try to reproduce the issue :pray: 

Thanks in advance :pray:

**Comment by lmeyer1** [comment]
@hibatallahAouadni As I wrote, I will create narrower issues as I progress. See the first of them here #28139. Don't waste your time on this issue. Catching a dozen of bugs in one hit is unfortunately not possible with code bugs, only with cockroaches.
> As we have an EPIC for all cart rules issues https://github.com/PrestaShop/PrestaShop/issues/13823 could you please try to clean this bug report and add your analyses and your notices/remarks to the original EPIC in a comment

I'll do that.

**Comment by hibatallahAouadni** [comment]
> @hibatallahAouadni As I wrote, I will create narrower issues as I progress. See the first of them here https://github.com/PrestaShop/PrestaShop/issues/28139. Don't waste your time on this issue. Catching a dozen of bugs in one hit is unfortunately not possible with code bugs, only with cockroaches.

Great :relaxed: thanks :pray:

**Comment by lmeyer1** [comment]
> If a cart rule is labelled in currency A it should never be applied to an order labelled in another currency. A cart rule should always be restricted to orders that share the same currency.

This is not a problem, if we [update exchange](https://devdocs.prestashop.com/1.7/faq/pricing/#refresh-exchange-rates) rates regularly.

**Comment by lmeyer1** [comment]
> Example that really happened (even though it sounds like coming from a fairy tale)
...
But in ps_orders, we can see, that (oh ultimate confusion), we had 25 CHF of discounts tax excl., 34.80 CHF of tax discounts, a order total of tax included of 10.50 CHF, tax excluded 43.90 CHF and a negative tax of -33.40 CHF

I was not able to reproduce. A customer was able to, but I don't know how he managed it.

**Comment by lmeyer1** [comment]
Closing in favor of all the separate detailed bug reports and feature requests mentioned in the description
