### ISSUE TITLE
BO - A log error is displayed in Logs page when confirm an order with Cach on delivery payment (Cash on delivery - v1.0.6)

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#28147]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

A log error `Use Tools::redirect() instead` is displayed in Logs page when confirm an order with Cach on delivery (module) payment on develop

It's related to Cach on delivery module **on develop**

develop :x: 
![image](https://user-images.githubusercontent.com/92912932/161964409-460dd8a3-f82b-4760-8929-7a4c4cb12daf.png)

https://user-images.githubusercontent.com/92912932/161964557-bb174673-a5fb-46a6-bf93-7d95476dc70a.mp4

PS1785 :heavy_check_mark:  

https://user-images.githubusercontent.com/92912932/161966933-9472cba4-4c65-4512-b49e-2f93521268bd.mp4

### Expected behavior

No error is displayed

### Steps to reproduce

1. Go to FO > Add product to cart
2. In order confirmation process > Choose `Pay by Cash on Delivery` method for payment
3. Confirm Order
4. GO to BO > CONFIGURE > Logs 
5. See error > `Use Tools::redirect() instead `is displayed in Logs page

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3,7.4

### If your bug is related to a module, specify its name and its version

 ps_cashondelivery v1.0.6

**Comment by MeKeyCool** [comment]
I take this one ^^

**Comment by MeKeyCool** [comment]
Sorry @MatShir, it should already be fixed by https://github.com/PrestaShop/ps_cashondelivery/pull/42 and https://github.com/PrestaShop/ps_cashondelivery/pull/32 ^^'

Thanks @kpodemski ;)

**Comment by HanaRebaiQA** [comment]
Hello, 

Thank you @MatShir for your ping.
I have checked this issue with `ps_cashondelivery v2.0.1` module on develop. The issue is fixed with the new released version.

Here is my check : 

- Uninstall the `ps_cashondelivery v1.0.6` module
- DO 

```
 cd modules> git clone https://github.com/PrestaShop/ps_cashondelivery
 cd ps_cashondelivery
 git pull --rebase origin dev
 composer install
```

- Check in BO > Module manager > The module `ps_cashondelivery v2.0.1` is well added 
- Go to FO > Add product to cart
- In order confirmation process > Choose Pay by Cash on Delivery method for payment
- Confirm Order
- GO to BO > CONFIGURE > Logs
- The error is not displayed

https://user-images.githubusercontent.com/92912932/183959940-099e3cf3-5fc0-455c-afa9-4625ee9b2b31.mp4

So, i'll close the issue.

Thank You!
