### ISSUE TITLE
SEO error ItemList position product list is incorrect

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#28151]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/27725
It is fixed in the PS1785, but after the merge 178x in the develop this issue is here again as commented here: https://github.com/PrestaShop/PrestaShop/pull/27992#pullrequestreview-924855454

![image](https://user-images.githubusercontent.com/16067358/162012745-bd1f56ab-6b4b-43c1-97e6-a32fa33ae16f.png)

### Steps to reproduce

1. Go to FO to a category page with products.
2. Show the source code
3. Search for @type": "ItemList
4. the First item will have the "position": 0,

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.0

**Comment by hibatallahAouadni** [comment]
So we should cherry-pick this PR #27814
