### ISSUE TITLE
WebService image upload size is hardcoded instead of being loaded from settings

### ISSUE THREAD

**Issue by NikosTsiligaridis** [PrestaShop/PrestaShop#28157]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Uploading product image through WebService uses limit of 3MB hardcoded in WebserviceSpecificManagementImages.php Line 68.
Temporary fix in WebserviceSpecificManagementImages.php:
```$imgMaxUploadSize = 3000000;``` to desired size.

### Expected behavior

Should be loaded from config PS_LIMIT_UPLOAD_IMAGE_VALUE or from php config:
```
ini_get('upload_max_filesize');
ini_get('post_max_size');
```

Whichever is smaller.

### Steps to reproduce

1. Send upload product image request through webservice

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Hello @NikosTsiligaridis 

Could you please provide the code that you inserted it into your WS request's body :pray: 
Related to #23777
BTW, we have an EPIC to improve the image system, check it out #27318
Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @NikosTsiligaridis 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by zuk3975** [comment]
Reopening the issue for following PR
https://github.com/PrestaShop/PrestaShop/pull/29135

**Comment by balejk** [comment]
@hibatallahAouadni To reproduce this issue, set the maximum image upload file size to 15 MB in the back office settings. Then issue the following command
```bash
$ curl -s https://stsci-opo.org/STScI-01G8GX6MG9VC1BVR5NRK8C660A.png | curl -F image=@- https://<key>@<website>/api/images/products/<id>
```
where `key` is a webservice key with POST privileges for the `images` resource, `website` is a domain of a PrestaShop instance and `id` is an ID of an existing product to which the image should be uploaded. The server response is
```xml
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<errors>
<error>
<code><![CDATA[72]]></code>
<message><![CDATA[The image size is too large (maximum allowed is 3000 KB)]]></message>
</error>
</errors>
</prestashop>
```

**Comment by Ratnadeep-Dasgupta** [comment]
Can you please provide the XML feed that you are trying to post?

**Comment by Ratnadeep-Dasgupta** [comment]
Hi @khouloudbelguith @prestonBot @hibatallahAouadni @zuk3975 @NikosTsiligaridis ,

I am facing the below error while uploading the image for the product in version 1.7.8.8.
Can anyone let me know what is the actual issue regarding this or provide us the XML feed ?
![Screenshot 2023-03-20 110835](https://user-images.githubusercontent.com/128346308/226802183-f12cc853-3255-47e6-8a27-7959e93a4a01.png)

**Comment by balejk** [comment]
@Ratnadeep-Dasgupta You need to send the image as form-data, see my curl example above.

**Comment by Ratnadeep-Dasgupta** [comment]
@balejk , We need to upload it using XML feed  is there a way?
Also we have tried using form-data not working
![image](https://user-images.githubusercontent.com/128346308/227510624-0a469859-568b-486b-bd60-99d4c41b3789.png)

**Comment by balejk** [comment]
First of all, in either case, you cannot use your local path of the image - the *remote* server does not see what lives on your *local* disk, you must include the binary image data in the request (as the error message says). Again, I recommend to your attention the above curl example.

Regarding your question, I am not aware of a way to upload an image via XML, which does not mean that it is not possible, however [the documentation](https://devdocs.prestashop-project.org/1.7/webservice/tutorials/advanced-use/image-management/) does not mention it either.

**Comment by Ratnadeep-Dasgupta** [comment]
@balejk : Can you please provide the link to convert the binary image path?
I just to need to convert the path online into the above mentioned format mentioned by you.

The documentation does not help me in any way.
We need to use the XML feed for posting the image since or product works on XML feed of prestashop. So please let me know if you could get any help.

**Comment by balejk** [comment]
If you are unable to use curl, you should be able to achieve it as described [here](https://devdocs.prestashop-project.org/1.7/webservice/tutorials/advanced-use/image-management/#using-an-html-form).

**Comment by balejk** [comment]
Sorry, I'm afraid I'm unable to help you any further with what you are trying to achieve. You will either need to ask elsewhere (you can try the [forums](https://www.prestashop.com/forums/)) or dive into the relevant PrestaShop webservice code yourself, possibly having to change it to suit your needs.
