### ISSUE TITLE
In cart rules customer search display the shop name

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#28156]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

When editing a cart rule, one can search for customer. The results that display as you type show the name and the email of the customer 

In a multishop installation, a customer can register with the same email in more than one shop. 
When in `All shops` context, the display of the customer list is insufficient. In fact, it is not possible to see which customer belongs to which shop. 

### Describe the solution you'd like

In all shops context, the list of the customers should include the shop id. 

### Alternatives you've considered

When creating a cart rule associated with a customer, do it always in individual shop context. 

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

That's a great feature 👏 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. So, we're waiting for your PR 🚀 

 Thank you

**Comment by lmeyer1** [comment]
@hibatallahAouadni Here are the specs:
Concerning: search-as-you-type in cart rules form, tab `Conditions`.
When multishop is activated, and we are in `All shop`  (or `Shop group`) context, then the search results must include the name of the shop the customer is belonging to.
When multishop is not activated, or when in a specific shop context, keep the current display.

I hope this goes enough in details.
