### ISSUE TITLE
StatisticsController should not be part of the core

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#28158]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

There is a front controller called StatisticsController with some historic code. Not a single one of my clients is using prestashop statistic modules, and I think it will be case for many merchants.

### Describe the solution you'd like

No need to have this controller there if using third party solutions.
This should be part of statistic module, for example [statsdata](https://github.com/PrestaShop/statsdata).

### Additional context

Also, I think this can go 🤣🤣

```
$guest->javascript = true;
$guest->sun_java = (int) substr($_POST['sun_java'], 0, 1);
$guest->adobe_flash = (int) substr($_POST['adobe_flash'], 0, 1);
$guest->adobe_director = (int) substr($_POST['adobe_director'], 0, 1);
$guest->apple_quicktime = (int) substr($_POST['apple_quicktime'], 0, 1);
$guest->real_player = (int) substr($_POST['real_player'], 0, 1);
$guest->windows_media = (int) substr($_POST['windows_media'], 0, 1);
```
Ping @jolelievre

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 


Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon.

Question: why you won't create a PR to implement this feature? 😅 

Thank you

**Comment by Hlavtox** [comment]
Because I also need to make money sometimes. 😛😄
