### ISSUE TITLE
Cart rules should have their amount set to `Tax included` by default

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#28165]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

When creating a cart rule an selecting a reduction amount, this amount is by default `Tax excluded`. This is not logical. 
If a cart rule has a reduction amount, it should not have any tax. A reduction using a voucher is like money and money does not have taxes, only products sold.

Anyway, if a cart rule gives a reduction tax excluded, this means that it is increased by the amount of the tax. Thus the tax will be a surprise to the merchant. This is most of the time not the expected behavoir.

### Describe the solution you'd like

In the cart rules form, `Tax included` should be the default value.

### Alternatives you've considered

One must be very careful, and change `Tax excluded` into `Tax included` for every cart rule that gives a reduction amount.

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. 
So, thanks for your PR :rocket: 

Thank you

**Comment by hibatallahAouadni** [comment]
Ping @camilleganzin wdyt about making the `Tax included` the default value in the cart rules form? 
Thanks in advance :pray:

**Comment by camilleganzin** [comment]
@hibatallahAouadni This makes perfect sense. So it would be perfect if you could do a PR to solve this @lmeyer1!
Thanks!!
