### ISSUE TITLE
Blockwishlist: Number of products on wishlist page

### ISSUE THREAD

**Issue by denys202** [PrestaShop/PrestaShop#28164]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When we have a restriction by products shown on wishlist view page the number of products that shows is not corect

### Expected behavior

The confugred number of products per page should be displayed on each view wishlist page.
Pull request: https://github.com/PrestaShop/blockwishlist/pull/170

### Steps to reproduce

1. Go to the backoffice, 
2. configure the number of products to show in list, 
3. add more products in wishlist then that number, 
4. in list view you will see that the number of products in paginated in wrong way. 

See here https://drive.google.com/file/d/1lv2MVH6wTiH3reIKj-SHHHAMWMMvKViQ/view

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

blockwishlist 2.1.0

**Comment by hibatallahAouadni** [comment]
Hello @denys202 

I reproduce the issue with PS1785, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/162225103-b2a6a2ac-ac11-4898-a857-cf8d43a253f1.mp4

I’ll add this to the debug backlog so that it’s fixed. And thanks for your PR :rocket: 

Thank you
