### ISSUE TITLE
Scroll Bar when zooming at 200x and black Border line

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#28162]
## Bug description 

I have a scrollbar when I zoom to 200% or more on my browser :

https://user-images.githubusercontent.com/16019289/160616065-ccab1ceb-6a1b-4240-b4d1-24aa81dde042.mov

Also, I have a black border on that modal. I don't think it should be here as shown in this comment : https://github.com/PrestaShop/PrestaShop/pull/26024#issuecomment-998143843 :
<img width="1100" alt="Screenshot 2022-03-29 at 14 59 03" src="https://user-images.githubusercontent.com/16019289/160616697-affa2fb5-67e0-4bc6-8a4d-df18d9ee07ea.png">

Could you check ? 

Otherwise it looks good to me ! I checked on desktop as well as mobile. Files are well uploaded.

| <img width="860" alt="Screenshot 2022-03-29 at 14 53 33" src="https://user-images.githubusercontent.com/16019289/160617023-8e4e1786-8df4-469b-a7bb-f9d4f931b4f9.png"> | <img width="343" alt="Screenshot 2022-03-29 at 14 53 57" src="https://user-images.githubusercontent.com/16019289/160617101-23edf6b5-c360-4c9d-811e-ceab5a10fb6a.png"> |
| ------------- | ------------- |

Thanks!

_Originally posted by @florine2623 in https://github.com/PrestaShop/PrestaShop/pull/28050#pullrequestreview-924582217_

**Comment by TristanLDD** [comment]
Indeed, the scroll bar and black border should not appear on the modal, especially on a small one like this

**Comment by MatShir** [comment]
Should we really need to make PS work with 200x zoom ? @TristanLDD Maybe we should define an official zoom support, so we don't have random surprises during the test? 🤔

**Comment by Hlavtox** [comment]
@MatShir That's just a bug or some low quality code, not hard to fix. Even if you zoom million times, 99% pages look like they should. :-) I will check it with Valentin. 👍

**Comment by MatShir** [comment]
Cool! Thanks @Hlavtox I assign you to the issue then :)

**Comment by NeOMakinG** [comment]
Obviously, the scrollbar was caused by a wrong negative margin on specific modals that now doesn't exist at all if you can confirm @MatShir 

The border will be fixed in the next UIKit release by this PR: https://github.com/PrestaShop/prestashop-ui-kit/pull/195

**Comment by AureRita** [comment]
Hi, 

I reopen this issue because we always have the scrollbar when we zoom at x230

**Comment by MatShir** [comment]
Seems to be fixed :)

**Comment by florine2623** [comment]
It is fixed on `8.0.x, `8.1.x` and `develop`.

While testing this bug I have found a regression : https://github.com/PrestaShop/PrestaShop/issues/33036
