### ISSUE TITLE
'Add to cart' button disappeared on iOS devices.

### ISSUE THREAD

**Issue by kamel3c** [PrestaShop/PrestaShop#28180]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello, 
I have a problem with my shop www.enflowers.pl
On iOS devices, 'Add to cart' button disappears. When I try to add few products (more than available), then 'Add to cart' (inactive) button appears.
Please help me :(

Best Regards,
Kamil

### Expected behavior

Button should be visible.

### Steps to reproduce

Go to product page -> observe the fields with quantity and 'add to cart'.

### PrestaShop version(s) where the bug happened

1.7.7.8

### PHP version(s) where the bug happened

7.3

**Comment by khouloudbelguith** [comment]
Hi @kamel3c,

Thanks for your report.
I did not manage to reproduce the issue with PS1778 using `os=iOS&os_version=14.0&device_browser=safari`
I attached a screen record

https://user-images.githubusercontent.com/16067358/162410517-641a284d-ddd6-4a1c-aea6-c784fb1faa7d.mp4

As it's not the default theme, provided by Prestashop, we can't do anything with this.
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.

Thanks!
