### ISSUE TITLE
WebServices Features creation

### ISSUE THREAD

**Issue by QueeNFrisk** [PrestaShop/PrestaShop#28206]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I am trying to create features and their corresponding values with the web service using php but I get error: 

```
<![CDATA[Validation error: "Feature->name property is empty."]]>
```
y mi código es este:
```PHP
try {
      $ws = new PrestaShopWebservice('https://www.shop.com', 'key', 1);
      $bx = $ws->get(['url' => 'https://www.shop.com/api/product_features?schema=blank']);
      $cf = $bx->children()->children(); // Aslo i tried with "$bx->product_feature->children();"
      $cf->name = 'TestApiFeatureName';
      // I've tried with $cf->Feature->name = 'TestApifeatureName'; and throw the same error
      $cx = $ws->add([
        'resource' => 'product_features',
        'postXml' => $bx->asXML()
      ]);
      $ncpf = $cx->children()->children(); // Aslo i tried with "$bx->product_feature->children();"
      echo 'Product feature created succesfully'. $ncpf->id . PHP_EOL;
    } catch(PrestaShopWebserviceException $e) {
      $e->getMessage();
    }
```
I have read the documentation article that corresponds to the resource (https://devdocs.prestashop.com/1.7/webservice/resources/product_features/) but I have not found enough information to solve my error. I have also searched the official prestashop forum, stackoverflow and sites that google gives me with my search.

### Steps to reproduce

1.-Installed prestashop
2- Enabled the api
3- coded on it using other resources without problems (added images and products)
4- When I went to the features using the example in the documentation the error occurred

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @QueeNFrisk 

Please send your request in English. English is the norm on GitHub.
Could you please provide the whole PHP code that you used to reproduce the issue (ex: see this [comment](https://github.com/PrestaShop/PrestaShop/issues/14439#issuecomment-507237568)).
Waiting for your feedback.

Thanks!

**Comment by QueeNFrisk** [comment]
Im apolagize, the issue is translated now 👏🏻

**Comment by HanaRebaiQA** [comment]
Hello @QueeNFrisk 

Thank you for the translation.
It seems that your issue is similar to this one [#14439](https://github.com/PrestaShop/PrestaShop/issues/14439) 
Could you confirm it ?

Thanks!

**Comment by QueeNFrisk** [comment]
No, I see that the author of the last issue has a problem related to position,
In my case I have a problem with the name because it returns "Feature->Name property is empty".
In fact, I attach the response I get from it:

```
HTTP REQUEST HEADER
GET /api/product_features?schema=blank HTTP/2
Host: www.shop.com
authorization: Basic KEY
accept: */*

HTTP RESPONSE HEADER
HTTP/2 200
date: Sat, 16 Apr 2022 00:23:47 GMT
content-type: text/xml;charset=utf-8
access-time: 1650067803
x-powered-by: PrestaShop Webservice
psws-version: 1.7.8.5
execution-time: 0.045
content-sha1: 3215da7b49d911a6fcd726373e1ee6ac969b6ba8
vary: Accept-Encoding
host-header: <HOST_HEADER>
last-modified: Sat, 16 Apr 2022 00:10:03 GMT
cf-cache-status: HIT
age: 824
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 6fc8c63badfc9a48-MEXRETURN HTTP BODY
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<product_feature>
        <id><![CDATA[]]></id>
        <position><![CDATA[]]></position>
        <name><language id="1"><![CDATA[]]></language><language id="2"><![CDATA[]]></language></name>
</product_feature>
</prestashop>
```

```
HTTP RESPONSE HEADER
HTTP/2 400
date: Sat, 16 Apr 2022 00:23:48 GMT
content-type: text/xml;charset=utf-8
access-time: 1650068628
x-powered-by: PrestaShop Webservice
psws-version: 1.7.8.5
execution-time: 0.023
vary: Accept-Encoding
host-header: c2hhcmVkLmJsdWVob3N0LmNvbQ==
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 6fc8c63c9dd59a4e-MEXXML SENT
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<product_feature>
        <id></id>
        <position></position>
        <name>TestApiFeatureName</name>
<Feature><name>TestApiFeatureName</name></Feature></product_feature>
</prestashop>
RETURN HTTP BODY
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<errors>
<error>
<code><![CDATA[84]]></code>
<message><![CDATA[Validation error: "La propiedad Feature->name está vacía."]]></message>
</error>
</errors>
</prestashop>

```

**Comment by QueeNFrisk** [comment]
I tried with a code similar to @khouloudbelguith and the "insert by xml" method worked.
It works, it's less aesthetic but it works.
However I think the error arises from adding them to the object as it's stated with the code I mainly used to open this issue.


Solution:
```PHP
try {
      $ws = new PrestaShopWebservice('https://www.shop.com', 'KEY', 1);
      $bx = $ws->get(['url' => 'https://www.shop.com/api/product_features?schema=blank']);
      $xml = <<<XML
        <prestashop>
          <product_feature>
            <id />
            <position />
            <name>
              <language id="1">$featureName</language>
              <language id="2">$featureName</language>
            </name>
          </product_feature>
        </prestashop>
      XML;
      $xml = new SimpleXMLElement($xml);
      $cx = $ws->add([
        'resource' => 'product_features',
        'postXml' => $xml->asXML()
      ]);
      $ncpf = $cx->product_feature;
      return $ncpf->id;
    } catch(PrestaShopWebserviceException $e) {
      $e->getMessage();
    }
```

**Comment by hibatallahAouadni** [comment]
@QueeNFrisk Glad that you solve your issue :tada:
