### ISSUE TITLE
email_alerts Display an info on a product when a customer subscribed to be notified when available

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#28218]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

A customer subscribes to a product to be notified when available. Later he visits the site again. On the product detail, he will not be shown the form to subscribe to a notification again.

If the customer does not remember that he already subscribed, he will be frustrated, because he cannot subscribe.

### Describe the solution you'd like

If a customer is already subscribed to a notification for a product, I expect him to see an info alert that tells him that he is already subscribed.

### Additional context

ps_emailalerts v. 2.3.3

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. 
Waiting for your PR :rocket: 

Thank you

**Comment by matks** [comment]
@PrestaShop/product-team friendly reminder PR https://github.com/PrestaShop/ps_emailalerts/pull/113 is blocked by this issue

**Comment by fabienvallon** [comment]
LGTM
