### ISSUE TITLE
when i tried to import products i get an error

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#28215]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![Error Ps](https://user-images.githubusercontent.com/62474824/162644884-4502ce4c-b8dc-47ff-b99c-218684a4a1aa.PNG)

1. Go to Import
2. When i click here 
![image](https://user-images.githubusercontent.com/62474824/162644964-b670867e-f344-4ad1-942e-7343ecb0446e.png)
3. Error 500 internal server

I have tried on a completely new installation and this error does not occur, what could be the cause? in the new installation I don't have apcu cache either

[PrestaShopException]
APC cache has been enabled, but the APC or APCu extension is not available
at line 43 in file classes/cache/CacheApc.php
38. * CacheApcCore constructor.
39. */
40. public function __construct()
41. {
42. if (!extension_loaded('apc') && !extension_loaded('apcu')) {
43. throw new PrestaShopException('APC cache has been enabled, but the APC or APCu extension is not available');
44. }
45. $this->apcu = extension_loaded('apcu');
46. }
47.
48. /**
CacheApcCore->__construct - [line 184 - classes/cache/Cache.php]
CacheCore::getInstance - [line 348 - classes/db/Db.php]
DbCore->enableCache - [line 4646 - controllers/admin/AdminImportController.php]
AdminImportControllerCore->postProcess - [line 295 - classes/controller/Controller.php]
ControllerCore->run - [line 518 - classes/Dispatcher.php]
DispatcherCore->dispatch - [line 93 - admin/index.php]

### Steps to reproduce

1. Import
2. When i click here 
![image](https://user-images.githubusercontent.com/62474824/162644964-b670867e-f344-4ad1-942e-7343ecb0446e.png)
3. Error 500 internal server

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

I didn't manage to reproduce the issue with PS1785 and it seems your issue is not related to Import but to APCu extension.
Could you please check your **Caching** configuration under **Advanced Parameters>Performance** and provide a screenshot.
Waiting for your feedback.

PS: check this [comment](https://github.com/PrestaShop/PrestaShop/issues/21945#issuecomment-729048396), it may help :wink: 

Thanks!

**Comment by alfonsolr09** [comment]
@hibatallahAouadni ![20220411_155520.jpg](https://user-images.githubusercontent.com/62474824/162755060-3631e923-26f8-49ce-9275-bc705bea4131.jpg)

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

Could you please disable your cache and enable the debug mode, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/162757836-b0da2d83-80b7-4c28-9627-ae6a98d0c006.png)

Waiting for your feedback.
Thanks!

**Comment by alfonsolr09** [comment]
@hibatallahAouadni 
![20220411_162017.jpg](https://user-images.githubusercontent.com/62474824/162760043-aa7ee50c-fc3c-43d8-823b-d382b0936a02.jpg)

![20220411_161916.jpg](https://user-images.githubusercontent.com/62474824/162760121-a3c53ce3-ed9a-494f-9b89-835d83807f28.jpg) 
When i click on "siguiente paso" 


This error with debug mode. 
Error 500 with no debug mode.
![20220411_161951.jpg](https://user-images.githubusercontent.com/62474824/162760072-a1bc9308-14f9-4b41-99e6-be668d72f755.jpg)

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

That's totally weird :scream: 
Well then, could you please check your hosting server and enable/install APCu extension and check if you still encounter the same issue :pray: 
Waiting for your feedback.

Thanks!

**Comment by alfonsolr09** [comment]
But in two prestashop on the same server and same dir one of them httdocs/xxx and the other httdocs/xxx/dev 
In first one i have the problem and in the second one no problem (new install)

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

I think it will be better to check with your hosting server :disappointed: 
Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration problem.

We will close this issue.

Thanks!

**Comment by alfonsolr09** [comment]
I have the solution app/config/parameter.php

?php return array (
  'parameters' => 
  array (
    'database_host' => 'localhost',
    'database_port' => '',
    'database_name' => 'prestashop_3',
    'database_user' => 'prestashop_3',
    'database_password' => '00000',
    'database_prefix' => 'ps_',
    'database_engine' => 'InnoDB',
    'mailer_transport' => 'smtp',
    'mailer_host' => '127.0.0.1',
    'mailer_user' => NULL,
    'mailer_password' => NULL,
    'secret' => '0000000',
    'ps_caching' => **### 'CacheApc'**,
    'ps_cache_enable' => false,
    'ps_creation_date' => '2022-04-10',
    'locale' => 'es-ES',
    'use_debug_toolbar' => true,
    'cookie_key' => '00000000000000',
    'cookie_iv' => '000000000000000000',
    'new_cookie_key' => 000000000000000000000000000000000000000000000000000000',
  ),
);

**Comment by alfonsolr09** [comment]
PS_ CACHING change to CacheMemcache

**Comment by alfonsolr09** [comment]
thanks to @hibatallahAouadni

**Comment by hibatallahAouadni** [comment]
@alfonsolr09 you're welcome :relaxed: even it seems like I haven't really helped you properly :sweat_smile:
