### ISSUE TITLE
upgrade from 1.7.7.8 to 1.7.8.5

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#28214]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Once this update has been done, I have checked everything and it works perfectly, but in the information window I receive these errors, what is the reason? are important?
![image](https://user-images.githubusercontent.com/62474824/162644834-971023ae-ba6d-465f-9b19-992e059043fc.png)

### Steps to reproduce

xxx

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you

**Comment by alfonsolr09** [comment]
@hibatallahAouadni I'm wondering if it could be a bug?

**Comment by alfonsolr09** [comment]
@hibatallahAouadni I'm wondering if it could be a bug?

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

The whole QA team tested the upgrade from 1.7.7.8 to 1.7.8.5 and none of us encountered this issue.
So I'm quite sure it's not a PS Core bug.

Thanks!

**Comment by alfonsolr09** [comment]
and what is the vendor folder used for??

@hibatallahAouadni
