### ISSUE TITLE
ps_emailalerts display of product list is ugly

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#28217]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The display of the product list in the customer account is quite ugly. 
See on desktop:
![Capture d’écran 2022-04-11 093301](https://user-images.githubusercontent.com/7520695/162687058-3b33a30b-75ae-4145-a841-1dd96839bf44.png)
And on mobile:
![Capture d’écran 2022-04-11 093316](https://user-images.githubusercontent.com/7520695/162687064-67e9d9e8-02c7-4f0b-84f7-a978711ea104.png)
Especially, images, texts and icons are not aligned, the margin between the lines is incorrect and on mobile the lines should break inside the row

### Expected behavior

I expect the image, text and icons to be aligned on desktop and mobile, with consistent margins and line breaks inside the product name instead of the whole line.

> Edit by @TristanLDD 

I made new mockups for the alerts display,  you can find te design specs here: https://www.figma.com/file/aCBf2HlypjT0ZxP2XcsT68/Core-Github-issues?node-id=1503%3A11412
<img width="1035" alt="ps_emailalerts desktop" src="https://user-images.githubusercontent.com/27484094/163364330-0c85f7ca-8aee-4bc8-83c4-cf4dd1ce14a2.png">
<img width="404" alt="ps_emailalerts mobile" src="https://user-images.githubusercontent.com/27484094/163364346-6dfae8d1-03f4-4940-ac46-e98778c52b2f.png">

### Steps to reproduce

1. As a customer, subscribe to more than one products through the `Notify me when available` form.
2. Go to `My account - My alerts`
3. Notice the misalignment

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_emailalerts 2.3.3

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

I was able to reproduce the issue with PrestaShop PS1785 and PS1778, see the attached screenshot below:

On desktop: 

![image](https://user-images.githubusercontent.com/23308427/162697589-719655e4-5f34-4fc7-8e1c-571f35945940.png)

On mobile:

![image](https://user-images.githubusercontent.com/23308427/162697549-cedc66bf-7607-47d8-b82d-0b6693bbb45e.png)

I’ll add this to the debug backlog so that it’s fixed.
Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. 
As usual, we're waiting your PR :rocket: 

Thank you

**Comment by NeOMakinG** [comment]
@PrestaShop/ux-team We need your input in order to get mockups or example of how we integrate this

**Comment by lmeyer1** [comment]
@NeOMakinG A mockup will follow...

**Comment by Hlavtox** [comment]
![Snímek obrazovky 2022-04-11 161715](https://user-images.githubusercontent.com/6097524/162759415-813f1df8-b228-4a27-b389-e76969e8afae.jpg)
I think we can follow the same thing as on product packs

**Comment by lmeyer1** [comment]
@Hlavtox @NeOMakinG This one looks great. Unfortunately, I don't find the code where to copy form, and I'm using `classic-rocket` theme. So I cannot put more time in this. I will concentrate on updating `classic-rocket`.

**Comment by TristanLDD** [comment]
Hello @NeOMakinG , I made new mockups for the alerts display,  you can find te design specs here: https://www.figma.com/file/aCBf2HlypjT0ZxP2XcsT68/Core-Github-issues?node-id=1503%3A11412

<img width="1035" alt="ps_emailalerts desktop" src="https://user-images.githubusercontent.com/27484094/163364330-0c85f7ca-8aee-4bc8-83c4-cf4dd1ce14a2.png">
<img width="404" alt="ps_emailalerts mobile" src="https://user-images.githubusercontent.com/27484094/163364346-6dfae8d1-03f4-4940-ac46-e98778c52b2f.png">
