### ISSUE TITLE
ps_emailalerts, the subscription confirmation alert on the product page does not show

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#28216]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When subscribing to an email alert on a product out of stock, there is an alert `Request notification registered`.
Unfortunately, this notification is not visible.
The form before subscribing
![Capture d’écran 2022-04-11 083444](https://user-images.githubusercontent.com/7520695/162682296-a4d527a3-60fc-4946-a6ec-02cb083a2b66.png)
This form in devtools. You can notice the empty hidden alert `<div class="js-mailalert-alerts d-none"></div>`.
![Capture d’écran 2022-04-11 083512](https://user-images.githubusercontent.com/7520695/162682309-6356a437-8ace-441f-b22f-b18303d56c91.png)
After subscribing, the alert is supposed to be displayed, but it is not: `<div class="js-mailalert-alerts d-none" style="display: block;">`
![Capture d’écran 2022-04-11 084723](https://user-images.githubusercontent.com/7520695/162682313-b0902858-2d3c-458f-880d-65315be1c7b6.png)
The reason is that `class="d-none"` of Bootstrap takes precedence over `style="display: block;"` of jquery.
![Capture d’écran 2022-04-11 084753](https://user-images.githubusercontent.com/7520695/162682318-cb1cc1e2-1d62-4c77-ab79-2ef55eed1d5b.png)

### Expected behavior

After a subscription, the alert must be displayed to the customer.

### Steps to reproduce

Prerequisites:
- Install ps_emailalerts 2.3.3
- Install a theme using bootstrap >= 4.0. I'm using classic-rocket (https://github.com/prestarocket-agence/classic-rocket/releases/tag/3.1.0).

Steps to reproduce
1. As a customer navigate to a product that is out of stock.
2. Look a the `Notify me when available` form in dev console.
3. Notice the invisible alert div.
4. Subscribe to the notification
5. Notice, that the form gets hidden, but no notification is displayed
6. In dev console, notice that the notification is well there, but that it is hidden because of incorrect CSS (`display: non!important` overriding `display: block;`).

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_emailalerts 2.3.3, classic-rocket theme (or any theme using bootstrap >= 4.0)

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

I didn't manage to reproduce the issue with PS1785 and the Classic theme, see the attatched screen record below:

https://user-images.githubusercontent.com/23308427/162700943-3a8523ca-1bcc-475e-9180-82991c1054e3.mp4

I think your issue is related to your theme, could you please switch to the Classic theme and check if you still encounter the same issue.
Waiting for your feedback.

Thanks!

**Comment by lmeyer1** [comment]
@hibatallahAouadni 
You are right, my theme uses a newer version of Bootstrap than the default theme. On `classic` theme the display is correct. 
There is still a problem: `class="d-none"` does not exist in Bootstrap `v4 alpha 4` used in `classic` theme. Thus this class name is useless in `classic` theme, but breaks themes based on a newer Bootstrap version. 
Let me investigate how this class found it's way into the code.

**Comment by kpodemski** [comment]
@hibatallahAouadni 

I added it added in a recent refacto to replace `style="display: none;"` but from what you say we can safely remove it 🤔

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Closing the issue as it's not related to the PS Core.
Thanks for your feedback!

**Comment by lmeyer1** [comment]
@hibatallahAouadni As of @kpodemski's comment above, there is a real hidden issue, that IS related to PS core. I'll open a PR anyway.

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Could you please provide a screen record to help reproducing the issue.
Waiting for your feedback.

Thanks!

**Comment by lmeyer1** [comment]
Hello @hibatallahAouadni,
I updated the steps to reproduce above to include installation of specific theme. While the bug happens only in themes using bootstrap >=4.0, when using `classic` theme, the problem gets unnoticed (just an extraneous CSS-class). Thank you for trying to reproduce another time.

**Comment by HanaRebaiQA** [comment]
Hello @lmeyer1 

I tried to reproduce your issue using `ps_emailalerts 2.3.3` and i Installed a theme using bootstrap like mentionned in the Prerequisites above the [classic_rocket.zip](https://github.com/prestarocket-agence/classic-rocket/releases/tag/3.1.0)

I have an exception using this theme when i navigated to a product in FO.
![image](https://user-images.githubusercontent.com/92912932/163550496-c8886142-46b0-493a-a9f1-190bff591606.png)


https://user-images.githubusercontent.com/92912932/163550438-733861bb-4775-406e-9c27-0cdadd08a295.mp4

Could you please check on your side ?

Thank you!

**Comment by lmeyer1** [comment]
@HanaRebaiQA Hello Hana,
The error message you get is related to the module `productcomments`. It is out of scope of this contribution. Can you deactivate this module and try again ? Thank you.

I notice the error in the `classic-rocket` theme.

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

I reproduce the issue with PS1778 with classic-rocket and ps_mailalerts v2.3.2, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/164235296-4623ab60-9281-48e1-b988-472d22b7240d.mp4

![image](https://user-images.githubusercontent.com/23308427/164235509-09d3adad-af82-4b8e-bcbc-b77de0ca6c38.png)

Isn't related to the theme? are you sure is related to Bootstrap version?
Ping @NeOMakinG wdyt about the disappear of alert? should we fix it?

Thanks!

**Comment by lmeyer1** [comment]
> Isn't related to the theme? are you sure is related to Bootstrap version?

Yes I am. It is related to the Bootstrap version.
It's indirectly related to the theme, because `classic` uses Bootstrap 4.0alpha4, while `classic-rocket` uses Bootstrap 4.4.1

**Comment by matks** [comment]
@lmeyer1 thank you for the explanations the PR https://github.com/PrestaShop/ps_emailalerts/pull/111 is approved
