### ISSUE TITLE
New Customer Registration error "Could not update your information, please check your data."

### ISSUE THREAD

**Issue by quentic** [PrestaShop/PrestaShop#28210]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On new customer account creation, the customer get this error message:
`    Could not update your information, please check your data.`

This happened after migration PS from 1.7.8.2 to 1.7.8.5 

This shop started with a  PS 1.6.1.24

### Expected behavior

Should register the new customer account

### Steps to reproduce

1. Go to https://prototype.arbo-couteaux.com/authentification?create_account=1
2. Fill in the form
3. Click the save button

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @quentic 

I didn't manage to reproduce the issue with PS1785, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/162712096-71c38d62-6b0c-4258-b048-0fb2bb011ae0.mp4

By the way, your site is 404 page :disappointed: 
Closing the issue as we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you

**Comment by quentic** [comment]
Thanks for trying.

Sorry for the noise. It happened that:
"allow partner offers" was not displayed on the new customer form (as defined by customer settings) BUT the field was set as required in the customer section of BO 

I'm not sure how that happened but I'm still a bit surprised that you can set **allow partner offers** to be required AND at the same time be able to not display the field.

Thanks for your work on Prestashop

**Comment by hibatallahAouadni** [comment]
@quentic Glad that you solved your problem :tada: and you're welcome :relaxed:
