### ISSUE TITLE
Modify the TinyMCE configuration

### ISSUE THREAD

**Issue by tdzierza** [PrestaShop/PrestaShop#28212]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Modifying configuration since 1.7.8
https://devdocs.prestashop.com/1.7/development/components/tinymce/

`public function hookActionAdminControllerSetMedia($params)
    {
        $this->context->controller->addJs($this->getPathUri() . 'js/custom-tinymce.js?v=' . $this->version);
    }`

custom-tinymce.js

`var window.defaultTinyMceConfig = {
  valid_elements: '+*[*]',
  extended_valid_elements: '*[*]',
  height: 800
}`

Javascript loading successfully. But it not make affect on tinymce editor.
I'm afraid that tinymce loading earlier and this global variable definition it's not available during tinymce.inc.js processing.

### Steps to reproduce

Issues in code:

js/admin/tinymce.inc.js 

`if (typeof window.defaultTinyMceConfig !== 'undefined') {
    Object.assign(default_config, window.defaultTinyMceConfig);
  `}``

### PrestaShop version(s) where the bug happened

1.7.8.4

**Comment by hibatallahAouadni** [comment]
Hello @tdzierza 

Could you please provide clear and concise steps to reproduce the issue :pray: 
Waiting for your feedback.

Thanks!

**Comment by tdzierza** [comment]
You have this in developer documentation

https://devdocs.prestashop.com/1.7/development/components/tinymce/

Please show example in code because I'm afraid that it can't working.

Or maybe I'm wrong but in my opinion loading order of javascript import make difference.

When you are using 

`public function hookActionAdminControllerSetMedia($params) 
{ 
$this->context->controller->addJs($this->getPathUri() . 'js/custom-tinymce.js?v=' . $this->version); 
}`

you have no influence when this global variable will be defined.

In my case it's not working:
`var window.defaultTinyMceConfig = { }`

If you have one example from your experience or somewhere in web where it's working I'll be appreciate

**Comment by hibatallahAouadni** [comment]
Hello @tdzierza 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you

**Comment by tdzierza** [comment]
This feature https://devdocs.prestashop.com/1.7/development/components/tinymce/ not working

Why you add this to documentation when it not working ?

**Comment by NeOMakinG** [comment]
@hibatallahAouadni Tinymce is something included in the core of the project, and the configuration should be extendable, it's probably right 👍 

If one of the @PrestaShop/prestashop-maintainers wants to try it, don't hesitate, overwise I'll take a look when I get some time!

**Comment by tdzierza** [comment]
Important detail:
I tried to change tiny_mce configuration for:
BackOffice
Design - Pages - Edit page

I also change core file: js/admin/tinymce.inc.js (rename it)
And even after this change tinymce still working, but if it require this file shouldn't working

**Comment by Sasni** [comment]
> I also change core file: js/admin/tinymce.inc.js (rename it) And even after this change tinymce still working, but if it require this file shouldn't working

Renaming the file disables the editor. Did you refresh the page with CTRL+F5 ? 

![image](https://user-images.githubusercontent.com/3370929/164014631-131d3a2d-7e07-4ec4-94aa-90316c58fbb8.png)
![image](https://user-images.githubusercontent.com/3370929/164014877-39217b01-4545-4fb0-bab8-8913aa786a94.png)

**Comment by tdzierza** [comment]
I mentioned that I mean Design - Pages (not Products)

![presatshop-pages](https://user-images.githubusercontent.com/8463620/164054967-70e79370-3cfb-480c-a9f3-4ed5c8463fe1.png)

**Comment by tdzierza** [comment]
Pages tinymce is not imported from js/admin/ location but in default from js/tiny_mce
What is the most confusing thing for me that I try to allow html5 tags but nothing help.

I have also version 1.7.7.2 and in this case html5 tags working very well - we can use for example section tag.

In version 1.7.8.4 it's impossible. But probably not by tiny_mce issue. I turned off tinymce and html5 tags still not working. It means that somewhere in php verification before inserting to db it's clearing.

**Comment by NeOMakinG** [comment]
> Pages tinymce is not imported from js/admin/ location but in default from js/tiny_mce What is the most confusing thing for me that I try to allow html5 tags but nothing help.
> 
> I have also version 1.7.7.2 and in this case html5 tags working very well - we can use for example section tag.
> 
> In version 1.7.8.4 it's impossible. But probably not by tiny_mce issue. I turned off tinymce and html5 tags still not working. It means that somewhere in php verification before inserting to db it's clearing.

I think this is something I encountered already, It's probably a backend issue/feature

**Comment by NeOMakinG** [comment]
> This feature https://devdocs.prestashop.com/1.7/development/components/tinymce/ not working
> 
> Why you add this to documentation when it not working ?

Because it is working.

[testmodule.zip](https://github.com/PrestaShop/PrestaShop/files/9044760/testmodule.zip)

I managed to override the tinymce configuration as expected from the documentation, this is definitely not a problem on our side.

**Comment by hibatallahAouadni** [comment]
Thanks @NeOMakinG :rocket:
