### ISSUE TITLE
Links redirect to 404 pages and spaces missing in wording

### ISSUE THREAD

**Issue by sLorenzini** [PrestaShop/PrestaShop#28227]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Spaces are missing on "APC" and "Xcache" label in caching block:

![1780](https://user-images.githubusercontent.com/2854834/162771193-d720ba78-2651-4441-9797-0f72c72a8f7d.png)

This is a regression compared to PS1778

Furthermore, these two links, "[APC PECL extension](http://www.php.net/manual/en/apc.installation.php)" and "[Xcache extension](http://xcache.lighttpd.net/)" redirect to 404 pages:

https://user-images.githubusercontent.com/2854834/162772349-4d8463ab-0912-4866-b64f-640d50d86de3.mp4

### Expected behavior

On 1778 version, spaces were good: 

![1778](https://user-images.githubusercontent.com/2854834/162772546-ddc795fc-ba73-46aa-a998-33f288518b85.png)

But the links were not good too.
I've found the good one for APC link. It should be: https://www.php.net/manual/en/apcu.installation.php
For Xcache, couldn't find it.

### Steps to reproduce

1. Go to BO -> Advanced parameters -> performance -> caching block
2. Set "Use cache" to yes and the caching system list appears.

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.2

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/28829
