### ISSUE TITLE
PrestaShop Metrics

### ISSUE THREAD

**Issue by ryvenia** [PrestaShop/PrestaShop#28222]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

We installed modul Prestashop Metrics, but we cannot connect it with GA4, because there is no button. Do you know how can I solve this problem? 

### Steps to reproduce

1. Go to modules
2. Click on PrestaShop Metrics
3. Scroll down
4. Error-there is no button to connect module with Google Analytics 4 

### PrestaShop version(s) where the bug happened

1.7.8.1

**Comment by hibatallahAouadni** [comment]
Hello @ryvenia 

It seems that your issue is not a PrestaShop core bug.
If your module is Metrics Official, please contact support team on Addons.

We will close this issue.

Thanks!
