### ISSUE TITLE
Language in multistore

### ISSUE THREAD

**Issue by szykuc** [PrestaShop/PrestaShop#28221]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,
I don't know if it's a bug or feature, but for me it's very bothersome. I have a multistore and I would like 1 language in each of them. 
Polish shop - Polish language, 
French shop - French language. 
So I set in Polish as the default Polish and adequately in French. 
I switched off Polish in the French shop and French in the Polish shop. 
When adding a new product, I have a language switch in which I can add both Polish and French translation in both stores. 
This gives a total of 4 possible names for the same product in 2 stores. If I turn off French language in a Polish shop, shouldn't the possibility of translating the product be turned off? 
After all, I only have one language enabled for a given store.
I cant even add product in French shop when i not fill polish name of product.

### Steps to reproduce

1. Setup a multistore with 2 languages
2.  Disable one language in each shop 
3. Try to add product only with one language

### PrestaShop version(s) where the bug happened

1.7.8.4

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Hello @szykuc 

Could you please check this issue #27617 it seems duplicate or related to yours.
Please check and feedback.

Thanks!

**Comment by szykuc** [comment]
@hibatallahAouadni it's only related in some part but my main problem isn't mentioned there.

**Comment by hibatallahAouadni** [comment]
Hello @szykuc 

> @hibatallahAouadni it's only related in some part but my main problem isn't mentioned there.

Could you please explain your main problem, and provide a screen record :pray: 
Waiting for your feedback.

Thanks!

**Comment by szykuc** [comment]
I thought I had described the problem thoroughly enough.
The main problem is that i can see french product translation in polish multistore when only polish lang is enabled for polish multisotre and vice versa.
That allow me to fill 4 of total titles (end other info like description) in 1 product. Polish and French in polish multistore and same in french multistore

**Comment by hibatallahAouadni** [comment]
Hello @szykuc 

The main problem is that we can't configure a specific language for each shop, and that result the problem that you encounter 😞 
IMHO, I think if we fix the issue that I mentioned in my comment above, you will not encounter this problem.

Thanks!

**Comment by florine2623** [comment]
Hello @szykuc ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Comment by bullmade** [comment]
@hibatallahAouadni @florine2623  the author is not talking about backoffice language as you are reffering to in #27617, but rather about the individual field translations, such as descriptions in products etc.
In fact, the only place where it dosen't work is on the products. On all other content pages like categories, cms etc, it switches to the correct language.

The issue from @szykuc is still present and is not adressed in #27617, nor in this PR https://github.com/PrestaShop/PrestaShop/pull/28392
