### ISSUE TITLE
Random checkout addresses, even if I'm not logged in

### ISSUE THREAD

**Issue by serginio8989** [PrestaShop/PrestaShop#28220]
### Prerequisites
https://www.prestashop.com/forums/topic/1062843-random-checkout-addresses-even-if-im-not-logged-in/
![888](https://user-images.githubusercontent.com/103263983/162727721-e18e4bf5-7127-458e-86c4-b40c7819bc68.png)

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

PS Version 1.7.8.5

PHP 7.3

There are several installations on the same server in the same folder (public_html), on different domains that work like add-on domains.

I'm trying to see what the $ customer variable holds, and it seems to randomly assign a user id in checkout page:

Array ( [lastname] => aldkjalsjdlasjd [firstname] => alksdlasldlsa [email] => ajkdkasjdkajskd@iii.com [last_passwd_gen] => 2022-04-08 09:59:35 [birthday] => 0000-00-00 [newsletter] => 0 [newsletter_date_add] => 0000-00-00 00:00:00 [ip_registration_newsletter] => [optin] => 0 [website] => [company] => [siret] => [ape] => [outstanding_allow_amount] => 0.000000 [max_payment_days] => 0 [note] => [is_guest] => 0 [id_shop] => 1 [id_shop_group] => 1 [id_default_group] => 3 [date_add] => 2022-04-08 15:59:35 [date_upd] => 2022-04-08 15:59:35 [reset_password_token] => [reset_password_validity] => 0000-00-00 00:00:00 [id] => 8266 [is_logged] => 1 [gender] => Array ( [type] => 0 [name] => Array ( [1] => Mr. [2] => M [3] => Herr [4] => Dhr. [6] => Hr. [7] => Herra [8] => Mr. [9] => Mr. [10] => Herr. [11] => Pan [14] => Herr [15] => Pan [16] => Ponas [17] => Κος. ) [id] => 1 ) [risk] => Array ( [name] => [color] => [percent] => [id] => ) [addresses] => Array ( [324048] => Array ( [id] => 324048 [alias] => M***** [firstname] => jjj [lastname] => Jakobsen [company] => [address1] =>***** [address2] => [postcode] =>**** [city] => **** [id_state] => 0 [state] => [state_iso] => [id_country] => 20 [country] =>**** [country_iso] => ** [other] => [phone] =>  [phone_mobile] => [vat_number] => [dni] => [formatted] => *****
****
*****
****
**** ) [****] => Array ( [id] => ***** [alias] => M**** [firstname] => *****[lastname] => Jakobsen [company] => [address1] => Ahornvej 19 [address2] => [postcode] => *** [city] => *** [id_state] => 0 [state] => [state_iso] => [id_country] => 20 [country] => Denmark [country_iso] => DK [other] => [phone] => 8888888 [phone_mobile] => [vat_number] => [dni] => [formatted] =>*****
**

**

**
*555555 ) ) )

Any help is welcome ! Thank you

### Steps to reproduce

1.Go to checkout 

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Hello @serginio8989 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must provide clear and concise steps to reproduce the bug**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
