### ISSUE TITLE
Add delay variables in the invoice pdf

### ISSUE THREAD

**Issue by chambrin** [PrestaShop/PrestaShop#28236]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Add delay variables, like: {$product.delivery_in_stock}.
In the invoice.
After adding in invoice.tpl.
Look in the HTMLTemplateInvoice.
I can't find a solution.
Where can we add variables for the invoice?
Thank you

### Steps to reproduce

.../PDF/invoice.tpl
.../PDF/ HTMLTemplateInvoice.php

### PrestaShop version(s) where the bug happened

1.7.6.1

### PHP version(s) where the bug happened

7.1

**Comment by marwachelly** [comment]
Hello @chambrin 

Could you please provide us with more info ?
We need more details to understand how we can reproduce your issue:

- Clear steps to reproduce the issue
- Screen shot
- screen record...

 If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com/).

Thanks,

**Comment by chambrin** [comment]
https://devdocs.prestashop.com/1.7/modules/concepts/pdf/

The Smarty variables from the documentation are not displayed in the invoice.

The "Add or alter Smarty variables" step
does not clearly indicate the procedure to be followed.

Sorry for my English. Thanks

I just want to create variables, which I can use in invoices.

**Comment by marwachelly** [comment]
> https://devdocs.prestashop.com/1.7/modules/concepts/pdf/
> 
> The Smarty variables from the documentation are not displayed in the invoice.
> 
> The "Add or alter Smarty variables" step does not clearly indicate the procedure to be followed.
> 
> Sorry for my English. Thanks
> 
> I just want to create variables, which I can use in invoices.

So we are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #[19768](https://github.com/PrestaShop/PrestaShop/issues/19768). 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks,

**Comment by marwachelly** [comment]
Duplicate of #19768
