### ISSUE TITLE
ps_emailalerts Some texts are in the wrong translation domain

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#28238]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the module ps_emailalerts, some translations are in the domain `Modules.Emailalerts` (correct), and some are in the domain `Modules.Mailalerts` (wrong, this is the old module name).
As a consequence, many translations are also in double in crowdin, once in module Emailalerts and once in the old module Mailalerts.

Related to https://github.com/PrestaShop/PrestaShop/issues/27026#issuecomment-1004666063, where some translation domains were corrected, but not all.

### Expected behavior

- Translation domains in a module should correspond to the module name.
- In Crowdin, the same wording should not be unnecessarily duplicated.

### Steps to reproduce

Unfortunately, it is not possible to notice the issue as a user of the FO.
You can still notice the issues:

1. Wrong translation domains: 
    - Goto https://github.com/PrestaShop/ps_emailalerts/blob/0caaf4b498e708038a69c61b72e79eb770e8d945/controllers/front/actions.php#L103
    - Notice the wrong translation domain `'message' => $this->trans('Your e-mail address is invalid', [], 'Modules.Mailalerts.Shop'),`
2. Duplicate entries:
   - Login to crowdin
   - Go to French translation page
   - Download the translation pack and unzip it
   - Open the files `\1.7.8\Modules\Emailalerts\Admin.fr-FR.xlf` and `\1.7.8\Modules\Mailalerts\Admin.fr-FR.xlf`
   - Notice that many texts to translate are the same (e.g. `Mail alerts`).

### PrestaShop version(s) where the bug happened

1.7.8.5

### If your bug is related to a module, specify its name and its version

ps_emailalerts 2.3.3

**Comment by marwachelly** [comment]
Hello @lmeyer1,

I think the issue is the same as https://github.com/PrestaShop/PrestaShop/issues/17810. Could you please check? 

Many thanks,

**Comment by lmeyer1** [comment]
They are related.
As far as I can see #17810 is fixed in ps_emailalerts v.2.3.3. At least as far as the string `No mail alerts yet.` is concerned. It seem as #17810 is as narrow as that.

**Comment by marwachelly** [comment]
> They are related. As far as I can see #17810 is fixed in ps_emailalerts v.2.3.3. At least as far as the string `No mail alerts yet.` is concerned. It seem as #17810 is as narrow as that.

So https://github.com/PrestaShop/PrestaShop/issues/17810  is already in our debug backlog. To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks,

**Comment by marwachelly** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/17810
