### ISSUE TITLE
ps_emailalerts modules are not hooked at all on fresh install

### ISSUE THREAD

**Issue by sLorenzini** [PrestaShop/PrestaShop#28242]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

ps_emailalerts module is not hooked at all on the develop branch.

On 1.7.8x branch, tested with 2.3.3 version of the module and is hooked on "displayCustomerAccount", "displayMyAccountBlock", "displayProductAdditionalInfo" hooks, all is ok:

https://user-images.githubusercontent.com/2854834/162991327-2a4686cc-48b7-4fbb-a52c-ceca45904b96.mp4

In FO, on product page we have the block:

![178x-product-psemailalertsOK png](https://user-images.githubusercontent.com/2854834/162995416-9c7f697e-791c-4f67-8ff2-b5ad9e33fb85.png)

Also on my account page the block is displayed:

![178x-account-psemailalertsOK png](https://user-images.githubusercontent.com/2854834/162995480-6359081c-74e0-4843-84d9-1272ba331850.png)

On develop branch, tested with 2.3.3 version of the module and it's not hooked at all:

https://user-images.githubusercontent.com/2854834/162992481-4565c935-60e0-46fa-8b4f-d90c4e6c241f.mp4

In FO, on product page the block is not displayed:

![develop-product-psemailalertsNOK](https://user-images.githubusercontent.com/2854834/162995576-7c4ac2a4-b23a-43a6-afe3-e6c84e207756.png)

Also on my account page, the block is not displayed:

![develop-account-psemailalertsNOK png](https://user-images.githubusercontent.com/2854834/162995659-cce1721f-4867-48be-8705-810b2b8a7cd4.png)

Tested 2.3.4 version of the module on develop branch and again not hooked

### Expected behavior

ps_emailalerts module must be hooked automatically after the installation on: 

- "displayCustomerAccount" hook, 
- "displayMyAccountBlock" hook, 
- "displayProductAdditionalInfo" hook

### Steps to reproduce

1. Go to BO -> Install ps_emailalerts module
2. Click on configure button of the module
3. Click on "Manage hooks" button on top right of the screen
4. List of hook is displayed for the module but in this case the list is empty

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

ps_emailalerts v2.3.3/v.2.3.4

**Comment by hibatallahAouadni** [comment]
Hello @sLorenzini 

I reproduce the issue only on develop. On 1.7.8.x, the mail alert and PSGDPR module are both well displayed: 

![image](https://user-images.githubusercontent.com/23308427/162995128-f7af06a5-04f6-4b2c-8e6b-056de322341e.png)

While on develop, those two modules are not displayed in FO, till you reset them.
SO, indeed it's a regression! thanks @sLorenzini :relaxed: 

Similar to this issue: https://github.com/PrestaShop/PrestaShop/issues/26508

Thanks!

**Comment by florine2623** [comment]
For PSGDPR module, it is fixed in https://github.com/PrestaShop/psgdpr/pull/172

**Comment by atomiix** [comment]
@florine2623 I don't think this issue is fixed in PrestaShop/psgdpr#172 🤔
