### ISSUE TITLE
ecommscript-integrationapp.trustpilot.com refused to connect

### ISSUE THREAD

**Issue by Juiliard** [PrestaShop/PrestaShop#28257]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

copied from https://github.com/trustpilot/plugin-prestashop/issues/7

Trustpilot widgets are not appearing any more on my website https://juliard.club/ (they did worked for more then a year).
I cannot access Trustpilot Settings, errors: ecommscript-integrationapp.trustpilot.com refused to connect
I can only reinstall module, which I did, but this did not helped.

Any advises?

### Expected behavior

- Trustpilot module Settings can be opened in a back office 
- Trustpilot widgets appearing on home page, product pages and other selected pages

<img width="1058" alt="Screenshot 2022-04-13 at 17 31 54" src="https://user-images.githubusercontent.com/58143423/163216555-602b4d20-36e4-436d-b486-e9eb149328c1.png">
<img width="1143" alt="Screenshot 2022-04-13 at 17 33 27" src="https://user-images.githubusercontent.com/58143423/163216838-5812e625-85e2-46f5-b426-d2d5216fa14a.png">

### Steps to reproduce

Steps:
1. I have done a fresh install of Prestashop v 1.7.6.5 on Asustor NAS (fresh new NAS model used with all default settings: AS6602T)
2. successfully Installed Trustpilot v2.50.855 but when try to open module the following error received: Trustpilot extension is not supported on HTTP protocol Make sure you are running your website on HTTPS protocol.
3. after adding httpS to address (or activating option SSL on all pages) - another error message appears: ecommscript-integrationapp.trustpilot.com refused to connect
 - similar errors appear on Safari, Chrome, Mozilla, Edge and even IE; checked on both: Mac 12.3.1 and Windows 10 systems
the same errors on live site: https://juliard.club/

### PrestaShop version(s) where the bug happened

1.7.6.5

### PHP version(s) where the bug happened

7.3.12

### If your bug is related to a module, specify its name and its version

Trustpilot v2.50.855

**Comment by hibatallahAouadni** [comment]
Hello @Juiliard 


It seems that your issue is not a PrestaShop core bug.
If your module is trustpilot Official, please contact support team on Addons

We will close this issue.

Thanks!
