### ISSUE TITLE
Blockreinsuarence after update to 5.1.1 ikon error

### ISSUE THREAD

**Issue by photinia73** [PrestaShop/PrestaShop#28256]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After updating module Blockreinsuarence from 5.1.0 to 5.1.1  only first ikon is displayed in the list
![image](https://user-images.githubusercontent.com/50954519/163215672-76475dab-07c4-4e25-9ec8-f2d963563494.png)

In the v 5.1.0 all ikons were on their places

### Expected behavior

All ikons will be on their places like in the previous version
![image](https://user-images.githubusercontent.com/50954519/163216054-2eb27ea0-4181-4aeb-b2cd-5678d68f25cc.png)

### Steps to reproduce

Go to https://old.te.com.ua/uk/akustika-aktivna-portativna/3136-magnat-monitor-active-2000.html every product page

On the previous version you can see that all is Ok https://te.com.ua/uk/akustika-vbudovana/3298-monitor-audio-pro-80.html

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.1.33-44

### If your bug is related to a module, specify its name and its version

Blockreinsuarence

**Comment by hibatallahAouadni** [comment]
Hello @photinia73 

Your issue seems duplicate of this one #28188
Could you please check and feedback 🙏 

Thanks!

**Comment by photinia73** [comment]
Dear @hibatallahAouadni  I saw the post #28188 but there the problem between dafault and custom ikons. I have all ikons custom. And see that was displayed only the one first

**Comment by photinia73** [comment]
> 
I saw the post https://github.com/PrestaShop/PrestaShop/issues/28188 but there the problem between dafault and custom ikons. I have all ikons custom. And see that was displayed only the first

**Comment by khouloudbelguith** [comment]
Hi @photinia73,

Thanks for your report.
I did not manage to reproduce the issue with PS1785 & blockreassurance v5.1.1 after an upgrade from v5.1.0
I attached a screen record

https://user-images.githubusercontent.com/16067358/163391011-595e9090-cb50-4291-8a49-c073cbc761c3.mp4

Thanks to check and feedback

**Comment by photinia73** [comment]
Do you see this problem on the my site https://old.te.com.ua/uk/av-resiveri-procesori/2516-denon-avr-s650h.html ?

**Comment by khouloudbelguith** [comment]
@photinia73, could you please provide me the exact difference between the first block and the other blocks.

![image](https://user-images.githubusercontent.com/16067358/163405746-0ac5dfd6-e9d4-4e51-893b-b099cf35beaa.png)

All blocks are created manually?

Thanks!

**Comment by photinia73** [comment]
All blocks are similar and created myself. Work properly on the v 5.1.0 here https://te.com.ua/uk/akustika-vbudovana/3011-sonance-visual-performance-vp52r-utl.html

I can give you the credentials to the BO and FTP, just tell how to do this.

**Comment by khouloudbelguith** [comment]
@photinia73,

Sorry, on this github repository there is no software support. This is an open source project.

You can find help

on PrestaShop forums https://www.prestashop.com/forums/
or by purchasing software support plan from https://www.prestashop.com/en/support

Thanks!

**Comment by photinia73** [comment]
I am from Ukraine and have not possibily to pay money for the support (( thank you for your time

**Comment by photinia73** [comment]
To resolve this issue all who have the same problem must go to the Mysql and clean the field icon in the Table ps_reassurance  if you have custom icon. As I can understand you have to leave onle the field custom or default img to show them correct
If the both fields icon and custom_icon are full the img does,`t display
I replaced all my imgs to the field custom_icon and cleaned the field icon and all of them are displayed correct
![image](https://user-images.githubusercontent.com/50954519/163413456-2bacfbf8-7ae2-4b30-9784-6ef24f301a7d.png)
