### ISSUE TITLE
BO > Profile - Exception is displayed when adding invalid field and choosing avatar

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#28253]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I edit my Profile with an invalid last name and an avatar, I get an exception `An exception has been thrown during the rendering of a template`.

https://user-images.githubusercontent.com/16019289/163202458-698882e4-da2e-484b-8d13-27429b9a55c8.mov

<img width="1075" alt="Screenshot 2022-04-13 at 16 25 42" src="https://user-images.githubusercontent.com/16019289/163202786-673ecb28-abaa-4705-8893-b7283d7327fe.png">

Tested in local and prod env.

Only reproduced on develop branch. PS 1.7.8.x is OK

### Expected behavior

An exception shouldn't be displayed.
Only the message alert `The "Last name" field is invalid.`

### Steps to reproduce

1. edit last name with invalid string
2. add a profile picture
3. save
4. see error

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4

**Comment by MeKeyCool** [comment]
I take this one ^^

**Comment by AureRita** [comment]
fixes #28660
