### ISSUE TITLE
BO - Useless cross icon in the dashboard page

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#28254]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

 Useless cross icon in the dashboard page. 
PS1.7.7.8 => OK

https://user-images.githubusercontent.com/89604350/163210613-9126f870-4e11-49b6-b6e4-845cc4770ca4.mp4

PS1.7.8.0 => NOK

https://user-images.githubusercontent.com/89604350/163210768-5140f831-89f4-44cf-9313-83512c9348ff.mp4

### Steps to reproduce

1. Go to Dashboard page 
2. Resize window
3. see error

### PrestaShop version(s) where the bug happened

develop,1.7.8.0

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @marwachelly 

This is the expected behavior :wink: it's not a regression! Check this issue #22458
This is the new design made by @prestascott

![image](https://user-images.githubusercontent.com/23308427/163216777-71eb53b7-4227-41ca-b5f9-021987c8cdf8.png)

Closing the issue.
Thanks!
