### ISSUE TITLE
FO > Product with no image do not display default image

### ISSUE THREAD

**Issue by domross95** [PrestaShop/PrestaShop#28263]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If a product has no image, don't compare the default image in the front office part.
![NO IMAGE](https://user-images.githubusercontent.com/39332656/163376886-5184d34f-4139-4bc2-89f9-9d69df806a89.png)
![NO IMAGE 2](https://user-images.githubusercontent.com/39332656/163376888-c926a4c8-e5fa-4dbb-809d-d69d89c9a219.png)

### Steps to reproduce

1. Create product with no image
2. Go in fron office and you can not see default image

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.3.2

**Comment by khouloudbelguith** [comment]
Hi @domross95,

Thanks for your report.
I did not manage to reproduce the issue with PS1785.
I attached a screen record

https://user-images.githubusercontent.com/16067358/163376904-0a914df8-f654-48af-807d-b46020d825ce.mp4


Thanks to check and feedback.

**Comment by domross95** [comment]
> 

Yes, actually this problem is not evident with the classic theme. In the presence of a different theme, the error occurs.

**Comment by khouloudbelguith** [comment]
@domross95, As it's not the default theme, provided by Prestashop, we can't do anything with this.
You should contact the theme author via your addons.prestashop.com account, they are the only ones to help you with it.

Thanks for your understanding!

**Comment by domross95** [comment]
@khouloudbelguith Thanks for your patience. I will contact the developer for assistance.
