### ISSUE TITLE
Can't change order shipping address in back-office

### ISSUE THREAD

**Issue by rcoussy-16h33** [PrestaShop/PrestaShop#28260]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I want to change the shipping address of an order in back-office, but I have an issue: `[Symfony\Component\Debug\Exception\ContextErrorException code 0] : Notice: Undefined index: price_with_reduction_without_tax.`

<img width="2546" alt="Capture d’écran 2022-04-14 à 11 13 58" src="https://user-images.githubusercontent.com/81374618/163354147-5471fdb4-f59a-404b-b12d-fe183fcdbd75.png">

### Expected behavior

Being able to change an order shipping address.

### Steps to reproduce

1. In back-office, click on an order
2. Change the shipping address

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by khouloudbelguith** [comment]
Hi @rcoussy-16h33,

Thanks for your report.
I did not manage to reproduce the issue with PS1785 + php7.4.
I attached a screen record

https://user-images.githubusercontent.com/16067358/163358370-533785b4-9c10-4bd4-bcf0-d6730a9331bd.mp4


Does this issue occur only with this order?
Have you any cart rules created?
Did you change the country of your shipping address?

Thanks!

**Comment by rcoussy-16h33** [comment]
Hi @khouloudbelguith,

- This issue occur with every order.
- I do have a few cart rules, but none seems related to the order I want to change.
- I did not change the country of my shipping address.

What is `price_with_reduction_without_tax` related to?

Thanks

**Comment by khouloudbelguith** [comment]
@rcoussy-16h33, 

Did you use a fresh install or an upgrade from an old version?
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - host
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - javascript console log

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by rcoussy-16h33** [comment]
The problem come from [this module](https://addons.prestashop.com/fr/logiciel-de-caisse-pos/13654-rock-pos-point-de-vente-et-omnicanal.html) which is outdated. Disabling it resolved the issue.
I'll install the latest version and see if it works.

Thank you for your help!

**Comment by khouloudbelguith** [comment]
@rcoussy-16h33, thanks for your feedback!
