### ISSUE TITLE
Add to cart with max stock within a quickview modal in a product page causes a bug

### ISSUE THREAD

**Issue by jouino16** [PrestaShop/PrestaShop#28276]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In product page, when I open the quickview of another product and add to cart the whole stock, the main product (the one in the product page and not the quickview modal) is replaced by the one just added to cart: the page URL is also replaced.

Please find an example below: in this example, the available stock for the t-shirt is 296.
Please note that this bug sometimes do not happen systematically, so I had to clean the cart and try again. **I didn't encounter this bug when I add to cart small quantities like 1, 2 or 3 units at the beginning, but later I tried adding to cart 3 units repeatedly, and I ended up by having the issue**.

https://user-images.githubusercontent.com/12447492/163682234-848d207f-438e-4041-b478-ad20f692afd1.mp4

Another related issue in the same context: knowing that the available stock is 296, if try 297, I don't get a message saying that there is no enough stock, the modal is closed, and the cart is empty.

https://user-images.githubusercontent.com/12447492/163681096-059550bc-c82e-46be-b9e7-f680337f837e.mp4

### Expected behavior

The main product should never get replaced with the one in the quickview modal and when trying to add to cart more than the available stock, we should get a message telling that there is no enough stock (as it happens in product page with the main product).

### Steps to reproduce

1. Open a product page that has other products at the end of the page, like "you also like" section.
2. Open a quickview of a secondary product (like in "you also like" section)
3. Type the max stock units and click add to cart 
4. Check the main product image and URL, as the may change
5. Do step 1 and 2 from the start, then type the max stock + 1 and click add to cart => no warning message and the modal closes

### PrestaShop version(s) where the bug happened

1.7.7.8

### PHP version(s) where the bug happened

7.3.33

**Comment by hibatallahAouadni** [comment]
Hello @jouino16 

I didn't reproduce the issue with PS1780, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/163820329-f3e21440-6ae3-4267-94b6-6e00ef6f6a9d.mp4

Please check and feedback.
Thanks!

**Comment by jouino16** [comment]
Hello @hibatallahAouadni 

Thank you for the demo.

Please note that you are not testing on the same version that I have mentioned (1.7.7.8 and not PS1780). Also, the bug (rge replacement of the main product) may not happen from the first try, so please try again. Please take note of my previous comment : "Please note that this bug sometimes do not happen systematically, so I had to clean the cart and try again. **I didn't encounter this bug when I add to cart small quantities like 1, 2 or 3 units at the beginning, but later I tried adding to cart 3 units repeatedly, and I ended up by having the issue.**"

Regarding the out-of-stock indication in the quick view modal, please try the following steps:
1. ensure your cart is empty
2. knowing that you have 300 in stock, try adding to cart 301 : type 300, then increment by one and then add to cart.

My best regards,

**Comment by hibatallahAouadni** [comment]
Hello @jouino16 

Thanks for your reply :pray: 
Yet, I didn't manage to reproduce the issue even with PS1778. 
I tried to reproduce it with these steps to reproduce:
> 1. ensure your cart is empty
2. knowing that you have 300 in stock, try adding to cart 301 : type 300, then increment by one and then add to cart.

Yet, no succes! see the attached screen record below:

https://user-images.githubusercontent.com/23308427/165789241-24d7e797-8488-4a0b-b110-ea3be05aa251.mp4

> Please note that this bug sometimes do not happen systematically, so I had to clean the cart and try again.

If the issue happen randomly, and we can't reproduce, so we can't fix :disappointed: 
I'm really sorry but I have to close the issue :pray: 

Otherwise, if you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Thank you
