### ISSUE TITLE
PHP Notice Error while accessing API on /products

### ISSUE THREAD

**Issue by preoteasa** [PrestaShop/PrestaShop#28279]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This error has bee previously reported for version 1.7.7 beta. The resolution was then that version 1.7.7 is not compatible with php 7.4. However, Prestashop 1.7.8 should be compatible with php 7.4.

### Steps to reproduce

1. load page https://...webservice_address.../api/products?schema=blank
2. The result contains the error mentioned above, plus a similar error for line 719.
[products-response.txt](https://github.com/PrestaShop/PrestaShop/files/8506933/products-response.txt)
 

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4.3

**Comment by preoteasa** [comment]
I tried to follow the instructions to contribute a fix to this problem. However I got the message "No more forks can be created. [View existing forks.](https://github.com/PrestaShop/PrestaShop/network/members)"

Attached is the diff with the fix.

[presta-webservice-php-7.4-fix.txt](https://github.com/PrestaShop/PrestaShop/files/8507437/presta-webservice-php-7.4-fix.txt)

**Comment by florine2623** [comment]
Hello @preoteasa ,

PS 1.7.8.x is already compatible with PHP 7.4 : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

I'm using PHP 7.4 with PS 1.7.8.5.
I can't reproduce your issue, i do not have any error :
<img width="616" alt="Screenshot 2022-04-19 at 10 01 59" src="https://user-images.githubusercontent.com/16019289/163955098-4225b69d-20d6-47a6-8096-7cfe8b0fb7a4.png">

Can you give more info about your issue ?
Thanks!

**Comment by preoteasa** [comment]
Here is a link where you can test the erroneous behavior:

--deleted-- check the video later.

It is a new install of Prestashop 1.7.8.5 on Ubuntu 20.04 LTS, using apache and php 7.4.3, cgi. It is the default installation of php.

$php --version
PHP 7.4.3 (cli) (built: Mar  2 2022 15:36:52) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

The shop runs on AWS on an ARM processor.

**Comment by preoteasa** [comment]
By the way. If you enable debug mode, the error goes away and you get the output from your screen shot. I think that this is a serious problem too. The debug mode should not hide errors.

**Comment by florine2623** [comment]
@preoteasa ,

I have indeed reproduced your issue with PHP 7.4 on PS 1.7.8.5 (downloaded [here](https://www.prestashop.com/en/versions))

https://user-images.githubusercontent.com/16019289/163981260-4d4736ba-85e4-456a-b951-298454a4ffa2.mov

- With PS 1.7.8.x branch, there's no issue. I tested with PHP 7.3 and PHP 7.4.

- With PS 1.7.7.8 and PHP 7.4, the error is here too. But that's normal because PS 1.7.7.8 is not compatible with PHP 7.4. With PHP 7.3 it is OK.

- With develop branch, it works well with PHP 7.4 too.

https://user-images.githubusercontent.com/16019289/163984821-76aaa3a6-028b-421b-aa52-6f688bc0ea71.mov

**Comment by preoteasa** [comment]
So you can reproduce the error with 1.7.8.5. What is changed in 1.7.8.x branch? I checked the source code of development branch and it seems similar to 1.7.8.5 release. I could attempt to test the development branch as well. Are you sure the debug is off?

**Comment by matks** [comment]
> So you can reproduce the error with 1.7.8.5. What is changed in 1.7.8.x branch?

https://github.com/PrestaShop/PrestaShop/compare/1.7.8.5...1.7.8.x

https://github.com/PrestaShop/PrestaShop/pulls?q=is%3Apr+milestone%3A1.7.8.6+is%3Amerged

**Comment by preoteasa** [comment]
The error occurs also in the development branch of Prestashop. I just cloned the development branch. Here you can see the error:

--deleted-- check the video later

IN ORDER TO REPRODUCE THE ERROR, THE DEBUG MODE MUST BE OFF.

**Comment by preoteasa** [comment]
Here it is a recording that shows the error for the development branch.

https://user-images.githubusercontent.com/6583978/164058319-cd3d59bd-bcc4-41d3-9676-c40ecae69a56.mov

I will take down the test installation.

**Comment by hibatallahAouadni** [comment]
Hello @preoteasa 

Thanks for your whole feedback :pray: 
We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #26559. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: thanks for the screen record :pray: I added it to the original issue :relaxed: 

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #26559
