### ISSUE TITLE
Upgrade to 1.7.8.6 does not update the SQL schema (module 4.14.0)

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#28272]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Core Pull Request https://github.com/PrestaShop/PrestaShop/pull/27162 introduced a SQL structure change.
Autoupgrade Pull Request https://github.com/PrestaShop/autoupgrade/pull/455 was submitted to add SQL migration script inside autoupgrade module.

~BUT the autoupgrade module uses its own SQL files since v5, and v5 is not released yet.~

~If I am not wrong, if we use the current autoupgrade module 4.14.0 from 1.7.8.5 to 1.7.8.6 (branch `1.7.8.x`) the SQL schema is not updated~

I am wrong. The module uses its own SQL files since v4.13.0 https://github.com/PrestaShop/autoupgrade/pull/395

### Expected behavior

If I use the current autoupgrade module 4.14.0 from 1.7.8.5 to 1.7.8.6 the SQL schema should be updated. The `name` SQL column in SQL table `ps_name` should be correctly set to 80.

### Steps to reproduce

- Install 1.7.8.5
- Install module upgrade 4.14.0
- Build a 1.7.8.6 release from 1.7.8.x branch
- Try to upgrade from 1.7.8.5 to 1.7.8.6
- `ps_state` table > column `name` is 64 and not 80

### PrestaShop version(s) where the bug happened

1.7.8.x

**Comment by HanaRebaiQA** [comment]
Hello @matks 

Thanks for your report.
I was able to reproduce the issue using the described steps.


https://user-images.githubusercontent.com/92912932/163585065-f3906a0c-d214-4ec5-91bb-d72a67ded829.mp4

Thank you!

**Comment by matks** [comment]
Should be fixed by https://github.com/PrestaShop/PrestaShop/pull/28271

**Comment by kpodemski** [comment]
@matks 

This is the fix for this issue:
https://github.com/PrestaShop/autoupgrade/pull/474

Upgrade SQL files are part of the latest stable release of the module.
https://github.com/PrestaShop/autoupgrade/tree/master/upgrade/sql

- there's no plan for `autoupgrade` v5 from what I know
- there's a code in v4 of `autoupgrade`: https://github.com/PrestaShop/autoupgrade/blob/master/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php#L270

**Comment by matks** [comment]
@PrestaShop/qa-team It seems that, after https://github.com/PrestaShop/autoupgrade/pull/474 has been merged, this issue is fixed.Could you please retest this issue with
- using `dev` branch of the upgrade module
- doing an upgrade from 1.7.8.5 to 1.7.8.x

**Comment by matks** [comment]
If QA analyst confirms this bug is solved using `dev` branch of the upgrade module then we need to release a v4.14.1 version of the upgrade module to allow users to upgrade from 1.7.8.5 to 1.7.8.6

**Comment by HanaRebaiQA** [comment]
Hello @matks 

I can confirm that with an upgrade from 1785 to 1786 using [autoupgarde](https://github.com/PrestaShop/autoupgrade) from `dev` branch ==> OK :heavy_check_mark: 

https://user-images.githubusercontent.com/92912932/164247696-c215d38f-0914-43a2-bbe1-4487bcea9086.mp4

Thanks!

**Comment by hibatallahAouadni** [comment]
Ping @matks so what we should do? should we close this issue as Fixed?

**Comment by matks** [comment]
@hibatallahAouadni yes

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/autoupgrade/pull/474
