### ISSUE TITLE
Context CurrentLocale not initialised when running a module update.

### ISSUE THREAD

**Issue by roja45** [PrestaShop/PrestaShop#28275]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I am calling this line of code during a module upgrade:

`Context::getContext()->getCurrentLocale()->formatPrice($price, $currency->iso_code)`

The problem is that the `Context::getContext()->getCurrentLocale()` return `null`.

The only place I see this initialised in the Controller `init()` but this is not called during a module upgrade.  The `ModuleController` ultimately extends Controller, but it does not call the `init()` method at any point during the upgrade process.

### Expected behavior

`Context::getContext()->getCurrentLocale()` should always return the locale.

### Steps to reproduce

1. Bit convoluted. You would need to create a module, 
2. install it, 
3. then create an upgrade file for it, that calls the `Context::getContext()->getCurrentLocale()->formatPrice()` method, 
4. upgrade it 
5. and then it will fail.

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @roja45 

Could you please provide a module to reproduce the issue :pray: 
Waiting for your feedback.

PS: please check this issue #21688 seems similar to yours

Thanks!

**Comment by roja45** [comment]
Hello,
Yes, I will do this, just a bit busy at the moment, almost there, don't close ;-)
Thanks

**Comment by hibatallahAouadni** [comment]
Hello @roja45 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
