### ISSUE TITLE
[BO]: Discount is not visible on customer group form

### ISSUE THREAD

**Issue by Amit-Kumar-Tiwari-Webkul** [PrestaShop/PrestaShop#28285]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Discount is not visible on customer group when editing customer group from **Customer Settings  ->Groups**
![group issue](https://user-images.githubusercontent.com/42021740/163982998-73064bbd-190c-431c-9271-ee77bbea8492.png)

### Expected behavior

Entered Discount must be shownDiscounts

### Steps to reproduce

1- Go to **Customer Settings  ->Groups**
2- Edit group from
3- No entered discount is visible

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.1

**Comment by florine2623** [comment]
Hello @Amit-Kumar-Tiwari-Webkul ,

I was able to reproduce the issue with PrestaShop version 1.7.8.x and develop, so I can confirm that this behavior is indeed a bug.

Thank you for your PR ! It will be reviewed soon :)

**Comment by hibatallahAouadni** [comment]
I changed the status to `TBR` cause I need to check if it's a `regression` or no!
Thanks for your patience :pray:

**Comment by marwachelly** [comment]
Hello,

The issue doesn't exist in PS1.7.8.0. It is a regression on 1.7.8.1 :
**1.7.8.0:**
![image](https://user-images.githubusercontent.com/89604350/164438927-90dba95c-1d19-46fb-aabd-e50351a9a1ea.png)

**1.7.8.1:**
![image](https://user-images.githubusercontent.com/89604350/164415839-7e484857-76d8-409f-a3bf-bf8d8785c42c.png)

Thanks,

**Comment by Progi1984** [comment]
Fixed by @Amit-Kumar-Tiwari-Webkul in #28301
