### ISSUE TITLE
Add product property `manufacturer_name`

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#28289]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Add product propertie manufacturer_name, to access product manufacturer name in presented product object .

### Describe the solution you'd like

Add product propertie manufacturer_name, to access product manufacturer name in presented product object .

### Additional context

# How to test

- Go to BO product and assign a product to manufacturer
- Edit theme product miniature and dump `$product.manufacturer_name`
- Check that product manufacturer name is displayed wherever the miniature is called (product controller, listing controller, wishlist, related products)

### Do you plan to work on this feature?

- [x] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by florine2623** [comment]
Hello @PululuK ,

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 

Thanks for the PR !

**Comment by PululuK** [comment]
@florine2623  I think is a dev feature no need Product Team validation

**Comment by florine2623** [comment]
@PululuK Perfect I have changed the labels :)

**Comment by kpodemski** [comment]
@PululuK 

✅ It really is a small but helpful change. Go for it :)
