### ISSUE TITLE
Credit slip using all of the voucher

### ISSUE THREAD

**Issue by itis-mmi** [PrestaShop/PrestaShop#28284]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi everyone, 

My issue seems to be linked to issues #16826, #18319 & #19214.

I encounter an issue when I try to perform a standard refund on an order which has a voucher (which corresponds to 10% of the total price). 
When I try and perform the standard refund and select certain items, the voucher is totally refunded on these items, instead of just the part of the voucher corresponding to these items. 
I try and check the "exclude initial voucher amount" checkbox when possible, but if the price of the items I try to refund is the same or less than the total voucher price, this option is disabled. 

![image](https://user-images.githubusercontent.com/103992393/163958085-bec61244-b943-4430-a5a4-d2902804e41f.png)

### Expected behavior

I expect for the credit slip to display the correct price for every item returned : the original price of the item lessened by the part of the voucher corresponding to this item (e.g. 20% of the item price if the voucher is a -20% rule). 

### Steps to reproduce

1. create an order using a -X% voucher 
2. accept this order 
3. perform a standard refund on this order 
4. select the items to refund 
5. check "generate a credit slip" 
6. check "exclude initial voucher amount" when possible 
7. submit the refund

### PrestaShop version(s) where the bug happened

1.7.6.8

### PHP version(s) where the bug happened

7.2.34

**Comment by florine2623** [comment]
Hello @itis-mmi ,

Thanks for your report !
Indeed your issue is similar to https://github.com/PrestaShop/PrestaShop/issues/18319.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by itis-mmi** [comment]
Oh sorry, I indeed misread the #18319 post ... 
Thanks for your answer, I'll stay tuned to this post !
