### ISSUE TITLE
Unable to close modal after module installation

### ISSUE THREAD

**Issue by sowbiba** [PrestaShop/PrestaShop#28283]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In MBO we have a "Read more" modal and we can install the module through that modal

Because we rebuild the entire modules list after one module installation, the source of the modal is removed and the modal is not closable

### Expected behavior

Do not rebuild the modules list after installation if there is a read-more modal

### Steps to reproduce

1- Install MBO https://github.com/PrestaShopCorp/ps_mbo/suites/6134225629/artifacts/213809743
2 - Go to Modules catalog page, choose a module like "Email templates manager" and click on "Read more"
3 - Install the module
4 - If the installation succeed, the modal is not closable

### PrestaShop version(s) where the bug happened

develop

### If your bug is related to a module, specify its name and its version

MBO branch 3.x

**Comment by Progi1984** [comment]
Fixed by @sowbiba in #28281
