### ISSUE TITLE
BO - An exception is displayed when we create a block and a language is disabled

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#28292]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Previously reported here: https://github.com/PrestaShop/ps_linklist/pull/134#issuecomment-1064309314
Thanks, @lmeyer1, it is a regression in the ps_linklist dev branch

![image](https://user-images.githubusercontent.com/16067358/153905794-194a2915-adcb-4427-9333-d50950e34884.png)

https://user-images.githubusercontent.com/16067358/164039188-761d9f3b-0c16-4a34-ad58-a41fd3797390.mp4

It was ok with linklist v5.0.4 installed from a fresh install PS

https://user-images.githubusercontent.com/16067358/164040103-3a2606ac-b85a-4dcf-8b70-d3ddeab6cf2f.mp4

### Steps to reproduce

1. Install a shop 1785 with English language & France country
2. Enable **debug mode**
3. Uninstall the module ps_linklist by removing the folder 
4. Install the dev branch of the module ps_linklist https://github.com/PrestaShop/ps_linklist
5. Go to BO > International > localization > Languages page
6. Disable the French language
7. Go to BO > Design > link list page > Add new block
8. Set name & add Custom content
9. Click on Save
10. See an error

### PrestaShop version(s) where the bug happened

1.7.7.8, 1.7.8.1, 1.7.8.5

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

Link List v5.0.4 dev branch

**Comment by lmeyer1** [comment]
Thanks @khouloudbelguith

**Comment by lmeyer1** [comment]
@khouloudbelguith @kpodemski Shouldn't this be fixed by https://github.com/PrestaShop/ps_linklist/commit/0011b28115fa611a81ec7f9d762aff468f3e9883 ?

**Comment by kpodemski** [comment]
@lmeyer1 I think so! Did you reproduce the issue on the new version?

**Comment by lmeyer1** [comment]
@kpodemski No. My PR (https://github.com/PrestaShop/ps_linklist/pull/134) is blocked by this issue. And I believe it should no longer be blocked.

**Comment by kpodemski** [comment]
Thanks @lmeyer1
