### ISSUE TITLE
Product associated to a deleted tags are present in the search result in FO

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#28291]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Tags are deleted from the BO but still exist  with associated product in the FO.

https://user-images.githubusercontent.com/89604350/164035978-28e6bfbd-32e5-49e9-9850-1c84bfc8e626.mp4

### Expected behavior

Product associated to a deleted tags are not present in the search result in FO

### Steps to reproduce

1. Add a tag from Product V2 page
2. Go to BO > Shop parameters > Search > Tags page
3. Delete the created tag
4. Go to FO and search with this tag
5. See error > The product still displayed in the search result

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.0

**Comment by zuk3975** [comment]
related to https://github.com/PrestaShop/PrestaShop/issues/28294#issuecomment-1238060656.
