### ISSUE TITLE
Upgrade to 1.7.8.6 does not update the SQL schema (module 4.12.0)

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#28299]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### If we use an old 4.x version of the autoupgrade, 1.7.8.5 to 1.7.8.6 upgrade does not work correctly

Core Pull Request https://github.com/PrestaShop/PrestaShop/pull/27162 introduced a SQL structure change.
Autoupgrade Pull Request https://github.com/PrestaShop/autoupgrade/pull/455 was submitted to add SQL migration script inside autoupgrade module.

BUT the autoupgrade module uses its own SQL files since v4.14.0.

If I am not wrong, if we use the autoupgrade module 4.12.0 from 1.7.8.5 to 1.7.8.6 (branch `1.7.8.x`) the SQL schema is not updated

We say to everybody "please always use the latest version of the upgrade module" but this could be an improvement and is not very expensive.

### Expected behavior

If I use the **autoupgrade module 4.12.0** from 1.7.8.5 to 1.7.8.6 the SQL schema should be updated. The `name` SQL column in SQL table `ps_name` should be correctly set to 80.

### Steps to reproduce

- Install 1.7.8.5
- Install module upgrade 4.12.0
- Build a 1.7.8.6 release from 1.7.8.x branch
- Try to upgrade from 1.7.8.5 to 1.7.8.6
- `ps_state` table > column `name` is 64 and not 80

### PrestaShop version(s) 

1.7.8.x

**Comment by hibatallahAouadni** [comment]
Ping @MatShir As you know we don't use the label `improvement` anymore with the new workflow.
So, we need your confirmation about this issue :sweat_smile: is it a `Bug` or a `Feature`?

**Comment by matks** [comment]
@MatShir answer is:

> nice to add it, sound more like a really should add it

> for a patch version, it is very sad to fail the upgrade

I guess this means bug is confirmed for 1.7.8.6 scope

**Comment by khouloudbelguith** [comment]
Hi @matks,

I tried to follow these steps:

- Install 1.7.8.5
- Install module upgrade 4.12.0 
- Build a 1.7.8.6 release from 1.7.8.x branch
- Try to upgrade from 1.7.8.5 to 1.7.8.6

But at this step, I'm blocked, I cannot upgrade to PS1786, I need to download the last version of the autoupgrade module or upgrade it.

![image](https://user-images.githubusercontent.com/16067358/164419907-b85d7faf-8297-486a-a9bc-62bbc12d16b0.png)

What do you think? did I miss something?

Thanks!

**Comment by matks** [comment]
Thank you @khouloudbelguith I did not know about that. My bug report is not relevant anymore then.
