### ISSUE TITLE
A not installed module still impact the Backoffice

### ISSUE THREAD

**Issue by sowbiba** [PrestaShop/PrestaShop#28305]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

1 - Install MBO module
[ps_mbo (15).zip](https://github.com/PrestaShop/PrestaShop/files/8539338/ps_mbo.15.zip)

2 - Go to Modules > Modules catalog and search for "Gamiphy" in the list

OR 

Download Gamiphy from https://addons.prestashop.com/fr/fidelisation-parrainage/52050--gamiphy-fidelisation-avec-jeux-et-parrainages-.html

3 - Try to install the module => it fails

4 - Refresh the page, you have an error related to Gamiphy module
<img width="715" alt="image-2022-04-20-14-43-51-440" src="https://user-images.githubusercontent.com/7426640/164675089-044c4df9-9c89-44a2-a840-721d4914ea56.png">

### Expected behavior

If the installation fails, the module's files have to be deleted or at least not loaded

### Steps to reproduce

See issue description

### PrestaShop version(s) where the bug happened

develop

**Comment by AureRita** [comment]
Hi @sowbiba 

Thank you for the reporting Issue.
I reproduced it on develop and not on 1.7.8.5 as you can see on this video :

The video on 1.7.8.5 

https://user-images.githubusercontent.com/100699445/164725916-d03474e4-8627-4399-9409-f379a246db7a.mp4

The video on develop : 

https://user-images.githubusercontent.com/100699445/164725949-c8e986c6-f21a-43c7-8ee7-c41dc2d8e592.mp4



It's a regression ! I will add it to the Patch Backlog to be fixed 

Thanks

**Comment by Progi1984** [comment]
It's not a regression. `Tools::jsonDecode` has been removed in 8.0.0.

You can find them there : https://devdocs.prestashop.com/8/modules/core-updates/8.0/#removed-methods.

I think Gamify must update its module.

Ping @sowbiba & @AureRita.

**Comment by Progi1984** [comment]
Sorry, I misunderstood the module. I agree : the module bad and finally not installed shouldn't have impact in the core.

**Comment by sowbiba** [comment]
👍🏾 I only need to know what's your ideal solution so I can try to submit a contribution ;)

**Comment by kpodemski** [comment]
Unfortunately, there's no ideal solution for this problem. Developers should be more precise when defining a maximum compatibility version. It could be, for example: `1.7.99.99`, which would have been much safer and prevented this module from installing on v8 without an update.

**Comment by sowbiba** [comment]
Can't be more agree. However, even if the module's developper misconfigured his module, we must prevent exceptions caused by a failed installation

**Comment by kpodemski** [comment]
@sowbiba 

They're using `Tools::jsonDecode` inside the `__constructor`, and probably this is why Installation fails. I wouldn't delete the module, but it should definitely be disabled, and if I'm not mistaken, this should work this way 🤔 

This seems to be a regression compared to 1.7.8. To test it, we should create a module that is not possible to install because of the same problem (using a non-existing method inside the `__constructor` but after the `parent` call)
