### ISSUE TITLE
Cannot manipulate order products using hookActionPresentOrder

### ISSUE THREAD

**Issue by musaffar-patel** [PrestaShop/PrestaShop#28306]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

It seems the Prestashop hook actionPresentOrder exists to allow developers to access the information displayed on the order detail page, however, when one tries to manipulate the products array : 

`$params['presentedOrder']['products'] `

the following error is produced

`Indirect modification of overloaded element of PrestaShop\PrestaShop\Adapter\Presenter\Order\OrderLazyArray has no effect`

How does one manipulate the products array to add additional information?

### Expected behavior

It should be possible to modify the products array otherwise it defeats the purpose of this hook

### Steps to reproduce

Implement the hook ActionPresentOrder in  any module
manipulate the $params['presentedOrder']['products'] array

### PrestaShop version(s) where the bug happened

1.7.8

### PHP version(s) where the bug happened

All

**Comment by AureRita** [comment]
Hello @musaffar-patel ,

Could you please provide a module that use this hook to test and reproduce the issue.
Waiting for your feedback.

Thanks!

**Comment by musaffar-patel** [comment]
[mymodule.zip](https://github.com/PrestaShop/PrestaShop/files/8543259/mymodule.zip)

Sample module attached.  Steps to reproduce error are as follows:

1.  Install the module
2.  In the front end, login as a customer which has a order history
3.  Go into customer order history in the store front
4.  Open order detail for viewing and the error described earlier shall occur.

**Comment by AureRita** [comment]
Hi @musaffar-patel , 

Thank you for your module and the steps to reproduce, 
I reproduced it on 1.7.8.5, on 8.0.0 and not on 1.7.7.8 and 1.7.6.5, we can see the issue on video juste here : 

https://user-images.githubusercontent.com/100699445/165251750-a546f58c-86c2-45cf-bd63-8dd35846a6a7.mp4

It's a regression ! I will add it to the Patch Backlog to be fixed 

Thanks

**Comment by matks** [comment]
@musaffar-patel thank you for the report

**Comment by MatShir** [comment]
@PrestaShop/prestashop-maintainers we need to check why it used to work. Is it really a regression or an expected behavior?

**Comment by ghost** [comment]
Hi! I have the same problem with the hook ActionPresentCart. The error message is there:
Indirect modification of overloaded element of PrestaShop\PrestaShop\Adapter\Presenter\Product\ProductListingLazyArray 

Hope it's not expected behavior :)

**Comment by atomiix** [comment]
Hi everyone, this is definitely not a regression, the hook `actionPresentOrder` was introduced in 1.7.8.0.
Also, it's a little bit tricky and not straightforward but the good news is that this hook is very usable!

You should take advantage of [the methods `AbstractLazyArray::appendArray()` and/or `AbstractLazyArray::appendClosure()` in `AbstractLazyArray`](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/src/Adapter/Presenter/AbstractLazyArray.php#L129-L158) like so:

```php
$params['presentedOrder']->appendClosure('products', function() use ($params) {
  $products = $params['presentedOrder']->getProducts();
  foreach ($products as &$product) {
    $product['name'] = 'my new product name';
  }
  return $products;
});
```

I'm closing this issue, feel free to reopen if nevertheless something was not working as expected.

**Comment by musaffar-patel** [comment]
It would be very helpful for future developers who may wish to utilise this hook, if this was added to the online documentation for the hook.

> Hi everyone, this is definitely not a regression, the hook `actionPresentOrder` was introduced in 1.7.8.0. Also, it's a little bit tricky and not straightforward but the good news is that this hook is very usable!
> 
> You should take advantage of [the methods `AbstractLazyArray::appendArray()` and/or `AbstractLazyArray::appendClosure()` in `AbstractLazyArray`](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/src/Adapter/Presenter/AbstractLazyArray.php#L129-L158) like so:
> 
> ```
> $params['presentedOrder']->appendClosure('products', function() use ($params) {
>   $products = $params['presentedOrder']->getProducts();
>   foreach ($products as &$product) {
>     $product['name'] = 'my new product name';
>   }
>   return $products;
> });
> ```
> 
> I'm closing this issue, feel free to reopen if nevertheless something was not working as expected.

**Comment by mschiele** [comment]
@atomiix I am trying to use the hook "actionPresentCart" with PS 1.7.8.7 with the following code:
```
$params['presentedCart']->appendClosure('products', function () use ($params) {
            $products = $params['presentedCart']->getProducts();
            foreach ($products as &$product) {
                $product['name'] = 'my new product name';
            }

            return $products;
        });
```

I then receive the following error:
```
Call to a member function appendClosure() on array
```
$params['presentedCart']['products'] is definitely an array of inherited AbstractLazyArray. 

How else can I add the closure for each product in the presented cart?

**Comment by atomiix** [comment]
@mschiele looks like you don't need to use `appendClosure` here, you can simply do:
```php
foreach ($params['presentedCart']['products'] as $product) {
  $product['name'] = 'my new product name';
}
```

**Comment by mschiele** [comment]
@atomiix great! it works fine. what's important here - I debugged the foreach loop in visual studio code and the debugger preview listed each product with a property "product" of type array. I tried to modify $product['product']['name'] which was wrong ;-)

**Comment by LorenzoMinciotti** [comment]
Be careful if you access properties before adding Closure because `AbstractLazyArray` caches property value when accessed.
The example below will not modify `$params['presentedOrder']->subtotals->shipping` property, because is modified with closure after accessed in if statement: the closure will be ignored because the value is already cached.

```
public function hookActionPresentOrder($params) {
  if($params['presentedOrder']->subtotals->shipping['amount'] == 0) { //accessing variable, result will be cached
    $params['presentedOrder']->subtotals->appendClosure('shipping', function() use ($params) {
      $shipping = $params['presentedOrder']->subtotals->getShipping();
        $shipping['value'] = $this->l('To calculate');

        return $shipping;
    });
  }
}
```

Instead, in this example, the closure will work because is appended before property is accessed.

```
public function hookActionPresentOrder($params) {
  $params['presentedOrder']->subtotals->appendClosure('shipping', function() use ($params) {
    $shipping = $params['presentedOrder']->subtotals->getShipping();
      if($shipping['amount'] == 0) {
        $shipping['value'] = $this->l('To calculate');
      }

      return $shipping;
  });
}
```
