### ISSUE TITLE
[BO] Admin header search results do not have a valid link to modules

### ISSUE THREAD

**Issue by amirrzd** [PrestaShop/PrestaShop#28303]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In admin header search, when I search for a module name (e.g. Reassurance) the links are like this:
index.php?tab=AdminModules&tab_module=seo&module_name=blockreassurance&anchor=Blockreassurance&token=xxx

This does not show the searched module in the modules page.
(I guess after changing the modules page URL, this has not been modified.)

### Expected behavior

The link should redirect to the Module Manager page with the search bar prefilled, and the list should be filtered accordingly.

Alternatively, instead of prefilling the search bar, it should scroll to the appropriate module and highlight it.

### Steps to reproduce

1. Search for a module in admin header search.
2. Click on the links of the results

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.3.33

**Comment by AureRita** [comment]
Hi @amirrzd 

Thank you for the reporting Issue.
I reproduced it on 1.7.8.5,, 1.7.7.4 and 1.7.6.5 as you can see on this video :

On 1.7.8.5

https://user-images.githubusercontent.com/100699445/164736856-b3cfebdc-e20f-4440-a0f8-98250553d749.mp4

On 1.7.6.5

https://user-images.githubusercontent.com/100699445/164738568-346cfa03-1944-450a-84cc-bedbe8e70ee3.mp4

I will add it to the Patch Backlog to be fixed 

Thanks

**Comment by florine2623** [comment]
This is fixed in 9.0.x

https://github.com/user-attachments/assets/ae9cce02-b315-434b-8ffc-52b284da0cbe
