### ISSUE TITLE
An error 500 is throw when you try to add an attachment to a product with a name longer than 32 chars

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#28316]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

While you try to add an attachment to a product with a long long long name (more than 32) you have an error 500 and the file is added but with a name like "2".

### Steps to reproduce

1. Go to product edition
2. Add an attachement with a long name
3. See error

### PrestaShop version(s) where the bug happened

1.7.8.5

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

I reproduce the issue with PS1778 and PS1785, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/165080948-937a8ae8-7c1d-44f2-afae-21122c579f23.png)

Fortunally, this issue has been fixed on develop with the new Product Page V2, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/165081269-f85cb66c-f531-43db-a761-e5dc875b2f44.png)

So, closing the issue as we only fix regressions on 1.7.8.x and it works on develop :wink: 
Thanks!

**Comment by PrestaEdit** [comment]
There is no more support on this PrestaShop 1.7 version, so ?
