### ISSUE TITLE
The hook `actionGetMailThemeFolder` is added but never used/dispatch

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#28313]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

There is a hook, called `actionGetMailThemeFolder`, added with three others related hooks inside the 1.7.6 version.

But this hook is never called/dispatch. It's seems to be an useless hook.

### Steps to reproduce

Check code about `actionGetMailThemeFolder` and see that it's never call.

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

> But this hook is never called/dispatch. It's seems to be an useless hook.

I didn't think it's useless cause this hook has been created to:
`This hook allows to change the folder of an email theme (useful if you theme is in a module for example)`

But let's check with the Developer team :wink: 
Ping @PrestaShop/prestashop-core-developers do you think this hook `actionGetMailThemeFolder` is useless?

Thanks!

**Comment by jolelievre** [comment]
Just because a hook isn't called by the core doesn't mean it is useless. I'm sure there are many other similar use cases since hooks are meant for modules not the core.

So this issue is not relevant IMHO

**Comment by kpodemski** [comment]
@jolelievre IMO core shouldn't have hooks without specifying how to implement it :) it's not a dynamic-name hook
