### ISSUE TITLE
Module manager page, Allow to add message on empty categories

### ISSUE THREAD

**Issue by sowbiba** [PrestaShop/PrestaShop#28317]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

![module manager en savoir plus](https://user-images.githubusercontent.com/7426640/165066390-aa478ca4-8650-4d70-897f-23b3792ea62d.png)

In 1.7.8, we had a message below the text "You don't have any module in CATEGORY_NAME". That message included a link to discover modules in that category

### Describe the solution you'd like

I would like to allow modules like marketplace to add content after the generic message by creating a new hook `displayEmptyModuleCategoryExtraMessage`

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @sowbiba 

Thank you for your suggestion and your PR :rocket: 
The Developer Team will take it into consideration for future developments. 

Thank you
