### ISSUE TITLE
ProductId value must be really greater than zero

### ISSUE THREAD

**Issue by tom-combet** [PrestaShop/PrestaShop#28327]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![image](https://user-images.githubusercontent.com/48719560/165132896-92380c73-6a45-4632-979c-dbaf4b64e1fe.png)

It's currently greater than or equal to zero.

### Expected behavior

It should be greater than zero.

### Steps to reproduce

1. Create a new ProductId object with id equal to 0.
2. Assert than no exception is raised.

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

any

**Comment by tom-combet** [comment]
I just saw the same thing on half of identifier-related value objects (Order, Employee...). I must be missing something, some explanation please?

**Comment by marwachelly** [comment]
Hello @tom-combet,

Thank you for your report. Could you please provide as with the exact script that you are using to create a new ProductId object with id equal to 0. Also a screen record will be helpful to reproduce the issue. 

Waiting for your feedback.

Thanks,

**Comment by tom-combet** [comment]
I don't understand, how would it be related to  one of my script? Here is the script:

`$productId = new ProductId(0);` 😛


More seriously, it's just general: if tomorrow, someone create a ProductId with id equal to 0, exception should be raised, period.

**Comment by kpodemski** [comment]
@marwachelly It's an issue for the @PrestaShop/prestashop-maintainers team to comment on :)

**Comment by hibatallahAouadni** [comment]
@kpodemski indeed it's :relaxed: 
Ping @PrestaShop/prestashop-core-developers could someone please try to answer @tom-combet question :pray: 

Thanks in advance!

**Comment by matks** [comment]
@tom-combet I think it's an error ; you can submit a PR to replace the `>` by a `>=` 👍 

@zuk3975 As far as you know, is it OK to reject zero as ID for ProductId or OrderId ?

**Comment by zuk3975** [comment]
there might be cases where product id is used as a reference to hold "no relation" state (which in legacy is 0)
If such case exists, that would mean productId was intentionally made this way (some time ago..).
Though in all newer implementations we try to make it more explicit and create an IdInterface with Id and NoId classes. You can see in example of ManufacturerId:
https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Domain/Manufacturer/ValueObject/ManufacturerIdInterface.php
(there are more examples with ShopId, CombinationId, CurrencyId)
So for further actions it needs to be checked if such cases exists. If not, then we can fix the constraint as mentioned, but if its used, then it would probably require introducing ProductIdInterface and apply it everywhere.

**Comment by tom-combet** [comment]
Will "no relation" state will still be defined by 0 at the end of symfony migration or it's only legacy thing?

**Comment by zuk3975** [comment]
> Will "no relation" state will still be defined by 0 at the end of symfony migration or it's only legacy thing?

it came from legacy, but I think it will stay this way for a very long time. In theory we should replace it by null values, but lots of work to refactor it (+ it works this way too, just isn't semantically correct), so I don't think its gonna happen in 5 years or maybe ever :smile:. 
just to confirm Im not wrong ping @matks @jolelievre

**Comment by tom-combet** [comment]
Hmm yes I think it can change after full SF migration but yea, at least in some years.
Feel free to close this issue if it overloads to-do list.

**Comment by kpodemski** [comment]
Thanks for your input guys @zuk3975 @tom-combet 

I'm closing it for now.
