### ISSUE TITLE
The module actions order have been modified

### ISSUE THREAD

**Issue by sowbiba** [PrestaShop/PrestaShop#28331]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The modules' actions order have been modified in https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/src/Adapter/Module/AdminModuleDataProvider.php#L73

This update impacts the actions order in Module manager page
![Capture d’écran de 2022-04-25 23-37-09](https://user-images.githubusercontent.com/7426640/165191467-f70fe0a0-e75c-495c-b615-62a920ba1e0c.png)

### Steps to reproduce

Go to Modules > Modules manager

In 1.7.8, in the actions dropdown, for example uninstall came before disable

After the modification disable comes first

### PrestaShop version(s) where the bug happened

develop

**Comment by marwachelly** [comment]
Hello @sowbiba ,

I verified the behavior. Just I think it will be better if we have confirmation from @PrestaShop/product-team. Is it a bug or a wanted behavior?  

Thanks,

**Comment by eshraw** [comment]
Hello @sowbiba @marwachelly,

It seems the change was introduced through the issue #27632 . This [commit](https://github.com/PrestaShop/PrestaShop/commit/463903298d0878d4c45a04ebbe801b2a28ee2189) changed the order. Is there any doc related to this change @atomiix ?

Awaiting for answer before categorizing the issue.

**Comment by atomiix** [comment]
Hi there, it seems that you're right, uninstall & disable are inverted, it wasn't on purpose

**Comment by sowbiba** [comment]
I didnt search for the commit but Yes, the order was inverted between 1.7.8 and develop and because the array is iterated in that order, the buttons in the front appear like this too

**Comment by eshraw** [comment]
Thanks for you answers.

It's a bug then @marwachelly.
