### ISSUE TITLE
Muchos mails en mi casilla y página trabada

### ISSUE THREAD

**Issue by delfinamedina** [PrestaShop/PrestaShop#28353]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

hola! ayer me paso que me empezaron a llegar muchos mails en muy poco tiempo (dejó adjunto el aspecto de los mails)
![7CFDE62C-8969-45C3-BC9F-2F8482DC6923](https://user-images.githubusercontent.com/104506701/165523390-0d2484a5-aff5-4367-8550-ead221edfd29.jpeg)
Fueron como 2500 mails al cabo de minutos, por parte de todo el mundo (nosotros solo vendemos en Argentina). Luego de eso, ya no pude meterme más en prestashop. Hice el reclamo con Towebs, que es mi proovedor de hosting a lo q le dijeron que al producirse tantos mails al mismo tiempo podría hacer sido falta de memoria, por lo que amplíe el plan. Sin embargo sigo sin poder meterme y ellos me dicen que es problema de Prestashop.  Yo creo que es un virus, ¿alguno tiene idea que puede ser?
![93DAB4A8-F77A-46DF-BAD8-38D7B71D6962](https://user-images.githubusercontent.com/104506701/165531967-6b0568bd-4b41-4e9e-a114-ac896706e865.png)

### Steps to reproduce

1. entrar a www.electromedina.com.atr
2. verán el error cuando cargue la pagina

### PrestaShop version(s) where the bug happened

1.7

**Comment by hibatallahAouadni** [comment]
Hello @delfinamedina 

Please send your request in English. English is the norm on GitHub.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thank you
