### ISSUE TITLE
ConnectException on check Webservice Endpoint

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#28357]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

ConnectException on check Webservice Endpoint

![Capture d’écran du 2022-04-27 18-20-18](https://user-images.githubusercontent.com/16455155/165569320-87b53cb4-28c4-4eb0-a651-57d012dd261a.png)

### Expected behavior

Display connexion error message and webservice status

![image](https://user-images.githubusercontent.com/16455155/165570089-b569c556-58ba-4989-87e6-7fd7a5bce799.png)

### Steps to reproduce

1. Go to _**BO > Advanced Parameters > Webservice**_
2. Add a new Key
3.  Enable PrestaShop's webservice
4. See the exception

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

N/A

### If your bug is related to a module, specify its name and its version

N/A

**Comment by hibatallahAouadni** [comment]
Hello @PululuK 

I reproduce the issue with develop only while using docker (in local I didn't encounter any issues), and it's a regression cause I didn't reproduce on 1.7.8.x while using docker.
I’ll add this to the debug backlog so that it’s fixed, and thanks for your PR :rocket: 

Thank you
