### ISSUE TITLE
"Follow Up"-Cart-Rule with Shipping gets calculated the wrong

### ISSUE THREAD

**Issue by fabian-lange** [PrestaShop/PrestaShop#28355]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello fellow Presta-Devs

This one is a little Hard to explain so I'll use an example from the get go:

We got a Cart-Rule which has an amount of 100€ Tax included.
Also 'Free Shipping' and 'Partial Use' are enabled on the Cart-Rule.

Now I got a cart with a product-value of 50€ and shipping-costs of 5€.

If I then use the 100€ Cart-Rule the follow up which get generated, because 'Partial Use' is enable, is wrong.
The expected result would be a Cart-Rule which copies the settings of the original one but has a amount of 50€ tax included.
Instead we get a new Cart-Rule which has copied settings but **40€** amount.
This is because the shipping cost somehow gets subtracted twice while it should not be subtracted at all.

I already created a module which overrides the Mathod responsible for this issue:
[siwa_fixpartialcartruledelivery.zip](https://github.com/PrestaShop/PrestaShop/files/8572767/siwa_fixpartialcartruledelivery.zip)

Best Regards
Fabian

### Steps to reproduce

1. Create a Cart-Rule with a fixed amount, 'free-shipping' and 'partial use' enabled
2. Order a cart which is below the fixed amount and shipping-costs so a new Cart-Rule gets created
3. The 'Follow Up'-Cart-Rule has a wrong value.

### PrestaShop version(s) where the bug happened

1.7.7.5 and 1.7.8.2

### PHP version(s) where the bug happened

7.2 and 7.3

**Comment by hibatallahAouadni** [comment]
Hello @Fobba199l 

What do you mean by "Follow Up"? are you talking about the module "Follow Up" which known by ps_reminder?
Waiting for your feedback.

Thanks!

**Comment by fabian-lange** [comment]
Hello @hibatallahAouadni

I mean the cart-rule which get created if a rule is only used partially.
![Screenshot from 2022-04-28 14-08-06](https://user-images.githubusercontent.com/22368949/165748795-e10e09dc-7c58-417a-a373-dd7b3d02ff27.png)

Like the Cart-Rule with the ID 25 in the screenshot.

I hope this is a little bit more understandable.

Best Regards

**Comment by florine2623** [comment]
Hello @Fobba199l ,

Here's the result I have in my cart as a customer :
<img width="1132" alt="Screenshot 2022-05-03 at 12 00 42" src="https://user-images.githubusercontent.com/16019289/166435525-6c3cb0a1-596e-410e-b9ce-e43d07a3b7d8.png">

In my customer account > Vouchers :
<img width="1101" alt="Screenshot 2022-05-03 at 12 01 16" src="https://user-images.githubusercontent.com/16019289/166435536-60d031d7-20a8-4bc0-ab35-14657eef66f3.png">

I don't have the same result as you, but it seems like a bug indeed.
Can you show me what you have as a customer after using the voucher ?

Thanks!

**Comment by fabian-lange** [comment]
Hello @florine2623 

This is my Result:     (tested in PS 1.7.8.2)
![Screenshot from 2022-05-03 15-33-52](https://user-images.githubusercontent.com/22368949/166462749-31628176-b14c-44f3-8005-c935f105c066.png)
![Screenshot from 2022-05-03 15-34-47](https://user-images.githubusercontent.com/22368949/166462760-fd7dd8d8-7fc9-46e5-861a-0fee6fb7af11.png)

As you can see, the new voucher has a value which is reduced by twice the shipping cost.

(Of course this test happened with my "Fix-Module" deactivated.)

Best Regards

**Comment by hibatallahAouadni** [comment]
Hello @Fobba199l 

Did you only encounter this issue only with your custom module?
Did you try to reproduce the issue without overriding the method with a module? if so, please provide a screen record :pray: 
Waiting for your feedback.

Thanks!

**Comment by fabian-lange** [comment]
Hello @hibatallahAouadni

As mentioned above:
The custom module is there to **fix** the issue. So **without** the module the issue is as described, **with** the module the issue is fixed.
Here is a Screencast of the voucher test:
[Screencast from 2022-05-05 08:57:35.zip](https://github.com/PrestaShop/PrestaShop/files/8629286/Screencast.from.2022-05-05.08.57.35.zip)

As already said.
This test happens with my module **disabled**.

Best Regards

**Comment by hibatallahAouadni** [comment]
Hello @Fobba199l 

Thanks for the screen record :pray: 
Despite our efforts, we were not able to reproduce your issue :disappointed: . It seems that your issue is not a PrestaShop core bug but most likely a module problem.

We will close this issue.

Thanks!
