### ISSUE TITLE
Error on selected list in Firefox

### ISSUE THREAD

**Issue by sLorenzini** [PrestaShop/PrestaShop#28369]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Previously reported here: https://github.com/PrestaShop/PrestaShop/pull/27892#pullrequestreview-951989134

We have an issue on selected list in the product settings pages in Firefox on Mac OS:

On some selected list, when we click on it to change the option, we cannot choose the option on the first click:

https://user-images.githubusercontent.com/2854834/165782290-fa71ee9b-861a-482b-bc2f-4ab875329d7f.mp4

Other pages tested:

- Catalog > Products page
- Design > Pages page
- Shipping > Carriers
- Shop Parameters > General page

Selected lists not custom only are concerned

Tested on browserstack on Firefox in windows and linus OS and it is good.

### Steps to reproduce

1. Go to BO > Shop Parameters > Product Settings on Firefox
2. Click on "Page for terms and conditions" field 
3. See the error, we can't choose an option on the first click

### PrestaShop version(s) where the bug happened

develop, 1.7.8.x

### PHP version(s) where the bug happened

7.2.21

**Comment by mparvazi** [comment]
Hello @sLorenzini 

Try to clear cache `Command + Shift + R (Mac)` and test again.
If problem persists, maybe it is being caused by an extension, theme or hardware acceleration,
Start Firefox in Troubleshoot Mode:
Click the menu button ("3-bar" menu button), click **Help**, select **Troubleshoot Mode**… and click **Restart** in the Restart dialog. When the `Open Firefox in Troubleshoot Mode?` window appears, click the **Open** button.

**Comment by sLorenzini** [comment]
hello @mparvazi 

Thanks for your feedbacks.
Unfortunately, we can't ask those steps to a merchant with no technical background. 
We have to find another solution  to make it works.
@PrestaShop/product-team what do you think?

thank you

**Comment by NeOMakinG** [comment]
> hello @mparvazi
> 
> Thanks for your feedbacks. Unfortunately, we can't ask those steps to a merchant with no technical background. We have to find another solution to make it works. @PrestaShop/product-team what do you think?
> 
> thank you

I guess @mparvazi said this because he wasn't able to reproduce your problem, meaning that the problem is probably because something is wrong with your environment 😄

**Comment by laurentrousseau918** [comment]
Yes, this is a software project, we should not block the work because users without technical background cannot do something

**Comment by NeOMakinG** [comment]
> Yes, this is a software project, we should not block the work because users without technical background cannot do something

Yeah but this is probably not something caused by the software, I just tested it with Firefox and I can't reproduce it too

@sLorenzini which firefox version are you using? If you're not on the latest version, can you update and test again?

Overwise, can you disable your extensions and test again? Because unfortunately, it looks like something on your computer causes this, we should try to find it.

**Comment by sLorenzini** [comment]
> > Yes, this is a software project, we should not block the work because users without technical background cannot do something
> 
> Yeah but this is probably not something caused by the software, I just tested it with Firefox and I can't reproduce it too
> 
> @sLorenzini which firefox version are you using? If you're not on the latest version, can you update and test again?
> 
> Overwise, can you disable your extensions and test again? Because unfortunately, it looks like something on your computer causes this, we should try to find it.

@NeOMakinG:
tested with @mparvazi steps, always this bug
version 100.0 of Firefox (the latest)
tested without my extensions, always this bug


 If I am the only one to reproduce this issue, we can close the bug and re-open it if someone else encounters the bug.
 
 Thanks to all
