### ISSUE TITLE
Error when pagination (products per page) on category page set to 0

### ISSUE THREAD

**Issue by sLorenzini** [PrestaShop/PrestaShop#28367]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Previously reported here: https://github.com/PrestaShop/PrestaShop/pull/27892#pullrequestreview-951989134

When we set to 0, "Products per page" fiels in product settings page, errors are displayed on category page:

On top of the category page:

![165108496-3ae09b70-c16b-4a9f-846a-87ccfb769214](https://user-images.githubusercontent.com/2854834/165769743-6647c327-594a-48d3-9339-e4f6e8473311.png)

On bottom of the page:

![165108699-019653c6-61c5-48d6-8cca-9f44e6b5e1d2](https://user-images.githubusercontent.com/2854834/165769792-ce2183dc-51f1-429e-9b4b-e1997e2a03b0.png)

### Expected behavior

- The input can't validate if the value is equals to 0. The value allowed are strictly superior to 0.
- Wording: define an error message for value equals and inferior to 0.
- Change tooltips wording: 10 to 12 products
- Check placeholder 

**Wording:** 

'The field is invalid. Please enter a positive integer.' in Admin.Notifications.Error

+ update the tooltip: 'Number of products displayed per page. Default is 12' Admin.Shopparameters.Help

### Steps to reproduce

Go to BO > Shop parameters > Product settings page > Pagination Block
Set to 0 the "Products per page" field in product settings page
Go to FO > Home category
See errors > on top & bottom of the page

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.2.21

**Comment by Julievrz** [comment]
We can use the following existing wording: 'The field is invalid. Please enter a positive integer.' in Admin.Notifications.Error

and update the following tooltip:

'Number of products displayed per page. Default is 12' Admin.Shopparameters.Help
