### ISSUE TITLE
Bad display with selected lists on Product settings page on mobile

### ISSUE THREAD

**Issue by sLorenzini** [PrestaShop/PrestaShop#28368]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Previously reported here: https://github.com/PrestaShop/PrestaShop/pull/27892#pullrequestreview-951989134

Tested the Product Settings page in responsive mode and all the selected lists are broken on Mac OS :

With responsive mode in chrome debugger:

![165110748-0f071a49-a059-49e1-8e83-26af0b1136a7](https://user-images.githubusercontent.com/2854834/165778744-85f10c3c-32a8-4d6e-9e0f-47000c42ba49.png)

With iphone mode in chrome debugger:

![165110720-2783f788-0954-4351-b7dc-5e5ba807c754](https://user-images.githubusercontent.com/2854834/165778863-531e1cab-7e88-40d6-9227-aeba41132978.png)

With pixel mode in chrome debugger:

![165110680-bb03f60c-93d3-41c5-8a3f-48add29c4a52](https://user-images.githubusercontent.com/2854834/165779055-beb84097-3aca-460e-8ff5-ca03cd0ed265.png)

Other pages tested:

- Catalog > Products page
- Design > Pages page
- Shipping > Carriers
- Shop Parameters > General page

Selected lists not custom only are concerned

Tested on browserstack with iphone screen, linux and windows OS and it is good.

### Steps to reproduce

1. Go to BO > Shop Parameters > Product Settings
2. Display chrome debugger (F12, or inspector with right click)
3. Click on "Toogle device toolbar" on inspector (phone/tablet icon)
4. Set the responsive mode on top in "Dimensions"
5. Click on "Page for terms and conditions" field
6. See the error, options of selected list is reduced and not on the right place

### PrestaShop version(s) where the bug happened

develop, 1.7.8.x

### PHP version(s) where the bug happened

7.2.21

**Comment by MatShir** [comment]
@NeOMakinG Very weird behavior, what do you think?

**Comment by MatShir** [comment]
Seems to be an issue from the inspector mode rather from the MacOS system. We need to test the step on a proper Ipad to be sure.

**Comment by florine2623** [comment]
@MatShir indeed it seems like an issue from the inspector. When I check on a real phone, it looks good to me.


https://github.com/PrestaShop/PrestaShop/assets/16019289/e6d67187-05fd-4d47-bb9d-7c1ea3c43ad9



I'm closing the issue to avoid clogging the backlog.
