### ISSUE TITLE
Module manager - Remove empty categories and allow modules to use them

### ISSUE THREAD

**Issue by sowbiba** [PrestaShop/PrestaShop#28364]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

As I don't know where to start, I will tell the real story

Our module wants to add content when a module category is empty, like suggesting modules of each category to install
So I added a hook to empty category message

But some of the reviewers are not agree with the way to do it and think that the empty categories have no sense because for the OS project there is nothing but a message to say "Hey this category is empty"

So one of the solutions suggested is to remove the display of the empty categories in Module manager page, add a hook at the bottom of the page with empty categories list as parameter to allow modules to do what they want with that

### Describe the solution you'd like

N/A

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @sowbiba 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Ping @PrestaShop/product-team wdyt about https://github.com/PrestaShop/PrestaShop/pull/28318#issuecomment-1112013136?

Thank you

**Comment by Hlavtox** [comment]
Implemented on develop - empty categories removed and hook is provided https://github.com/PrestaShop/PrestaShop/pull/29421
