### ISSUE TITLE
Products page V2 - Summary description characters limit does not work

### ISSUE THREAD

**Issue by sLorenzini** [PrestaShop/PrestaShop#28363]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Previously reported here: https://github.com/PrestaShop/PrestaShop/pull/27892#pullrequestreview-951989134

The characters limit number does not work on products page V2 in summary description.

In Products page V1, limit is 20.
Also tested in 178X branch for this page and it's ok

![Capture d’écran 2022-04-28 à 11 48 11](https://user-images.githubusercontent.com/2854834/165727349-23b1e927-703e-49b5-a5f7-03e80c5e1f71.png)

In Products page V2, limit is 800, the default characters limit

![characters-limit-summary-pp-v2](https://user-images.githubusercontent.com/2854834/165727465-fbe83484-3c34-450f-8c8b-0fcdd4b259cd.png)

Set the summary to more than 20 characters and save

![characters-limit-summary-pp-v2-saved](https://user-images.githubusercontent.com/2854834/165727609-07f35cba-bc9c-4466-8f84-d545d63a9bbb.png)

### Expected behavior

See the old page Product V1:

![image](https://user-images.githubusercontent.com/23308427/165743402-e5c738d5-93c3-4f95-a04b-0707ef3668cd.png)

### Steps to reproduce

1. Go to BO > Shop Parameters > Product Settings page
2. Change the Max size of short description to 20 > save
3. Go to Catalog > Products V2 > Edit a product
4. See error > in the summary section, the max size is not updated

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.2.21

**Comment by zuk3975** [comment]
I don't see any issue in 8.0.x and develop branch.
The summary max length is set to 800 and constraints works as expected.
1. When too many symbols provided I see error as expected
![Screenshot from 2022-09-01 17-28-33](https://user-images.githubusercontent.com/31609858/187939435-779bd2c2-931b-4945-bae1-f3c86c01b372.png)
2. When symbols in allowed range It is saved and shown correctly as expected.
![Screenshot from 2022-09-01 17-28-15](https://user-images.githubusercontent.com/31609858/187939444-9488a0b4-dd06-4d9d-b1d4-5cf60b0ea318.png)
