### ISSUE TITLE
CI is failing on 1.7.8.x branch - BO login timeout

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#28372]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

CI is failing on 1.7.8.x branch as you can see on https://github.com/PrestaShop/PrestaShop/pull/28371

### Expected behavior

CI should not fail if the code is correct

### PrestaShop version(s) where the bug happened

1.7.8.x

**Comment by HanaRebaiQA** [comment]
Hello @matks 

Thanks for your report.
Regarding this, 
![image](https://user-images.githubusercontent.com/92912932/165915910-697b87c5-105e-40e8-b339-fe8dbbda47ba.png)

So, it's a regression in automated tests.

Thanks!

**Comment by matks** [comment]
I reproduce the issue on 1.7.8.5 release if the DEBUG mode is enabled.

Same for 1.7.8.x branch: issues can be observed when DEBUG mode is enabled, as found by @SD1982 and @nesrineabdmouleh

**Comment by nesrineabdmouleh** [comment]
Hello @HanaRebaiQA,

It's not a regression in automated tests but a regression in Metrics V3, reproduced when debug mode is enabled.

![Capture d’écran de 2022-04-28 17-41-12](https://user-images.githubusercontent.com/24647495/165953902-5aea3a24-f80b-4cac-abd4-0a9a4818756f.png)

**Comment by matks** [comment]
Fixed by a new release of ps_metrics (PR to verify https://github.com/PrestaShop/PrestaShop/pull/28386)
