### ISSUE TITLE
console command doesn't set Shop::CONTEXT_ALL properly

### ISSUE THREAD

**Issue by jocel1** [PrestaShop/PrestaShop#28378]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When launching console command, Shop::CONTEXT_ALL is not set.
Command such as /bin/console prestashop:module install .... are hence ran in CONTEXT_SHOP by default.
This could lead to the following issue:

php ./bin/console prestashop:module install tacartreminder --no-debug
L'action install est impossible pour le module tacartreminder. Please select the context All Shops before install the module

### Expected behavior

Properly set Shop::CONTEXT_ALL if no id_shop / id_shop_group is provided

### Steps to reproduce

Get a module doing this kind of test:

    public function install($delete_params = true)
    {
        $this->accesslog = $this->accessLogsDirectory();
        $this->log('************ INSTALLATION ****************');
        if (Shop::isFeatureActive() &&
            !(Context::getContext()->shop->getContext() == Shop::CONTEXT_ALL)) {
                $this->_errors[] = $this->l('Please select the context All Shops before install the module');
            return false;
        }

Run
./bin/console prestashop:module install mymodule

### PrestaShop version(s) where the bug happened

*

### PHP version(s) where the bug happened

*

**Comment by kpodemski** [comment]
Why not setting the Context in the  module install method instead?

**Comment by jocel1** [comment]
Hi @kpodemski the module install method offers the --id_shop and --id_shop_group which properly set the context.
However when no option are provided, the CONTEXT_ALL should be expected, and this is not the case (it always sets CONTEXT_SHOP even when no --id_shop or --id_shop_group are specified)

**Comment by HanaRebaiQA** [comment]
Hello @jocel1 

Thanks for your report.
It seems that your issue is similar to this one [#25016](https://github.com/PrestaShop/PrestaShop/issues/25016)
Could you confirm it ?

Thank you.

**Comment by jocel1** [comment]
hi @HanaRebaiQA no it's not the same issue, it's not related to the backoffice, but to the cli command

**Comment by HanaRebaiQA** [comment]
Thanks @jocel1 for your feedback!

So, could you please give us more info about which PrestaShop version, php ?  and please provide us a screen-record to can reproduce the issue clearly ?

Thank you!

**Comment by jocel1** [comment]
hi @HanaRebaiQA I've already provided the fix & test in the associated PR https://github.com/PrestaShop/PrestaShop/pull/28379
Without my fix, the test will fail.
I guess the issue is present on all php & prestashop version

**Comment by florine2623** [comment]
Hello @jocel1 ,

Would you mind providing the demo module so we can test it ?

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @jocel1 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by jocel1** [comment]
Hi @florine2623 it was not a demo module, in my case it was the module taremindercart which was affected by this issue

**Comment by matthieu-rolland** [comment]
@jocel1  hello ! we usually asks to provide a basic module that will reproduce the bug, so that the QA can test it easily (you can attach the zip to the issue here or in the PR)
