### ISSUE TITLE
FO > Page Product, Exceptions when you use latest classic-theme changes on 1.7.8.x

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#28387]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I Go to the FO, Click on See all product or a category of product, I've this exception : 
![image](https://user-images.githubusercontent.com/100699445/166208042-f7d3998d-1620-41c3-99a7-b24ed0224a58.png)

Just after an installation of a classic-theme to test it, it doesn't happen on develop

### Expected behavior

I want to see the product with the faceted search on the left

### Steps to reproduce

1. Install a classic-theme like this one : https://github.com/PrestaShop/classic-theme/pull/26 : so you use **the latest classic-theme changes**
2. Install your shop
3. Go on FO 
4. Clic on "All products" 
5. See the exception

### PrestaShop version(s) where the bug happened

1.7.8.x

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

https://github.com/PrestaShop/classic-theme/pull/26

**Comment by Hlavtox** [comment]
@matks How should I handle this? It's because of a new field I added.

When releasing a patch version of 1.7.8 branch, is the latest of classic built and included?

I can add a condition to the TPL. 🤷🏻‍♂️ Isn't this kind of a drawback of separating the repo? Previously, the theme on that branch stayed like it was and was not affected by things happening on develop.

**Comment by kpodemski** [comment]
@Hlavtox 

Classic is still part of the 1.7.8 branch, and `classic-theme` repository shouldn't be used with this version.

**Comment by matks** [comment]
> Isn't this kind of a drawback of separating the repo? Previously, the theme on that branch stayed like it was and was not affected by things happening on develop.

Yes it's a drawback. Separating repositories, like we do for modules, mean your project need to be compatible with multiple versions. But it also introduces benefits :)

**Comment by MatShir** [comment]
We should make the min version compatibility for the classic theme repo only for the v8.0
