### ISSUE TITLE
API is not working with the product page

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#28382]
**First issue** : An exception is thrown when putting a negative amount in Cost price field

There are two problems here: 

- The wholesale price is not updated when changing the Cost price in Supplier field
- An alert is missing to notify that the price should be positive or zero (as without PR)

1. BO > Catalog > Products (experimental) V2  > Create a product
2. In `Supplier references` section > Add a negative amount in Cost price field 
3. Click on Save
4. See error > Exception

![image](https://user-images.githubusercontent.com/92912932/165497563-a9a00281-8da5-4057-bfa5-02570ac23c99.png)

_With PR_

https://user-images.githubusercontent.com/92912932/165497632-d7d0c155-da1b-4979-9280-d43071b76fb3.mp4

_Without PR_ 

https://user-images.githubusercontent.com/92912932/165498455-098782ea-aed8-4ff5-918e-20aebd553dc0.mp4

==> This issue is verified when tested it again following it's fix. To be tested again in the next check.

**Second issue** : Webservices issues

There are two issues when create a product V2 with **API** 

**_Issue 1_ :** An exception is thrown when edit a product V2 which is created with API

1. Create a product with API
5. The product is displayed in the product page V2 
6. Click to edit the product 
7. See error > Exception

![image](https://user-images.githubusercontent.com/92912932/165502155-b8d003ed-63a2-41b1-a5ae-2ea3fe0b54a2.png)

https://user-images.githubusercontent.com/92912932/165502229-52d22f04-4831-4c7d-ba90-59dd87b11554.mp4

_Without PR :_ 

https://user-images.githubusercontent.com/92912932/165502298-72d87c09-c7c5-4342-8d26-126c42339c7a.mp4

**==> The issue 1 is not present without PR**

**_Issue 2_ :** 

1. Create a product with API
2. The product is displayed in the product page V2 
3. Change the XML object by adding the product type (**Only with this PR to can edit the product**)

`<product_type>combinations</product_type>
`

4. Click to edit the product 
5. Click on Save
6. See error > Exception

![image](https://user-images.githubusercontent.com/92912932/165503706-6950c76a-006d-4c29-a8fd-e3c2eb21b7d2.png)

https://user-images.githubusercontent.com/92912932/165503769-2b93ed53-a19c-44ed-b1cd-0edfccf52136.mp4

**==> The issue 2 is present without PR**

**The impact of this second issue** : The product images are not well displayed following this issue. 

![image](https://user-images.githubusercontent.com/92912932/165504381-c358a059-e7a6-44e6-a43d-50b731ee6a1e.png)

**Comment by matks** [comment]
Issue 1 ✅  bug confirmed, ready to be fixed
Issue 2 🤔  not sure this is something that should be allowed in webservice, need to ask @jolelievre his opinion

**Comment by khouloudbelguith** [comment]
Hello @MatShir, @HanaRebaiQA,

Those issues are fixed in 8.0.x

A supplier with negative amount => ok
![image](https://user-images.githubusercontent.com/16067358/184617677-8bd642d4-02b5-4728-827f-109621dce0a9.png)

We can add a product with API => OK

I will close the issue as fixed
