### ISSUE TITLE
Enable caching of addressExists method

### ISSUE THREAD

**Issue by ProteanCode** [PrestaShop/PrestaShop#28385]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Lately I have been checking on how I could optimize a prestashop instance and the results were unexpected as I saw in KCachegrind report something like 500-800 calls to PDO::query method

To diagnose it further I visited the following file **/classes/Address.php** and saw that the following code

```
    /**
     * Specify if an address is already in base.
     *
     * @param int $id_address Address id
     *
     * @return bool The address exists
     */
    public static function addressExists($id_address)
    {
        return (bool) Db::getInstance(_PS_USE_SQL_SLAVE_)->getValue(
            'SELECT `id_address` 
            FROM ' . _DB_PREFIX_ . 'address a 
            WHERE a.`id_address` = ' . (int) $id_address,
            false
        );
    }

```

Where the last parameter is set to false, and that last parameter is responsible for caching the query result.

Since I configured the shop for diehard caching with memcached, opcache preload, and whatever-else-i-could-do I really do not see a reason for this parameter to be set to false.

Setting it to true converted like 600 calls to PDO::query into 600 calls to Memcached::get which is fine, or at least better I suppose

### Describe the solution you'd like

Make calls to Address::addressExists cache'able on application layer rather than depending on database caching settings

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by ProteanCode** [comment]
Nevermind

Somebody posted about this here
https://github.com/PrestaShop/PrestaShop/pull/28232

**Comment by hibatallahAouadni** [comment]
Duplicate of #28321
