### ISSUE TITLE
Provide a way to delete the install folder from the admin interface

### ISSUE THREAD

**Issue by unlocomqx** [PrestaShop/PrestaShop#28384]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

The admin page display a warning about the install folder, it would be helpful to provide a button to delete it as well
![localhost_prestashop_1785_backoffice_index php_controller=AdminDashboard token=bf7f705f7b33b356d5f8d4f9f72fbf8e](https://user-images.githubusercontent.com/793712/166144888-4f4d0033-f3e6-4d28-9b32-dc481b893d61.png)

### Describe the solution you'd like

A button to delete the folder without having to open the ftp
![localhost_prestashop_1785_backoffice_index php_controller=AdminDashboard token=bf7f705f7b33b356d5f8d4f9f72fbf8e (1)](https://user-images.githubusercontent.com/793712/166144921-585e3b81-62c8-4a36-83d7-94439f279e10.png)

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by mparvazi** [comment]
Hello @unlocomqx 

So anyone except you (admin) can delete this folder, right?

**Comment by unlocomqx** [comment]
@mparvazi I didn't understand, please clarify

It's simply to provide an easy way to delete the install folder.
It's similar to how PrestaShop can create the database for you when you are installing a shop, it saves you a few clicks.
