### ISSUE TITLE
In the details of the order, the VAT tax of the product appears duplicated and the wrong price appears

### ISSUE THREAD

**Issue by Cantonata** [PrestaShop/PrestaShop#28393]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the details of the order, the VAT tax of the product appears duplicated and the wrong price appears

### Expected behavior

You should see the correct price including VAT that has already been entered on the product

### Steps to reproduce

https://cantonatagijon.com/cazadoras/22-cazadora-rockera-08220310.html
Click on "añadir al pedido"
Wrong price appears "54,33 €"

### PrestaShop version(s) where the bug happened

1.7.8

### If your bug is related to a module, specify its name and its version

PRS195 Versión 1.4.0

**Comment by florine2623** [comment]
Hello @Cantonata ,

This is an issue with your template.
Please make sure you don't have any overrides on t-your template or contact directly the developer of it.

This is not a Core related issue. So I will close it.
Thanks!
