### ISSUE TITLE
'updatedProduct' Javascript event not working in CCC mode + asset management

### ISSUE THREAD

**Issue by JulienNDKgroup** [PrestaShop/PrestaShop#28391]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

We tried to optimize our shop by deploying the asset management system following your documentation. It works all fine except in our product page: the "updatedProduct" javascript event is not triggered when the CCC mode is activated. When we disabled the CCC mode, the specific event is working fine. However, we changed the event to "updateProduct" and this one works in "normal" mode and also in CCC mode. The problem is, we need to launch different animations and events after the product is updated, not before. We added different console logs in our JS file and checked the content of the file in the "network" tabulation when inspecting the code: The console logs are inside the file, so it looks like the "updatedProduct" event is not known or not fired in the CCC mode for Prestashop. Our theme is minified with webpack.

We also tested the "updatedCart" event in the cart page, and all is working fine: in normal mode and in CCC mode.

We use a multistore mode and the 1.7.7.5 Prestashop version.

### Steps to reproduce

1. write a custom JS file with the "updatedProduct" javascript event.
2. call this file in the product page via the theme.yml.
3. enable the CCC mode.
4. switch attributes of a product in the product page.

### PrestaShop version(s) where the bug happened

1.7.7.5

### PHP version(s) where the bug happened

7.3.29

**Comment by florine2623** [comment]
Hello @JulienNDKgroup ,

Could you provide the JS file with the "updatedProduct" javascript event + provide an screen record example fo what you are trying to do please ?
It will be very helpful in reproducing your issue.

Thanks!

**Comment by JulienNDKgroup** [comment]
Hello Florine!

Finally all is working good. We had a line in our JS file that was blocking all the workflow only when we enabled the CCC system. But now it's OK :) Sorry for the inconvenience!

Best Regards

**Comment by hibatallahAouadni** [comment]
@JulienNDKgroup Glad to hear :tada:
