### ISSUE TITLE
when will the new version of cash on delivery be compiled??

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#28408]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

when will the new version of cash on delivery module be compiled with new logo etc...??

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_cashondelivery

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop,  you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you

**Comment by alfonsolr09** [comment]
this is an official open source PrestaShop module

**Comment by alfonsolr09** [comment]
this is an official open source PrestaShop module

**Comment by alfonsolr09** [comment]
@Progi1984 @matks

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

> this is an official open source PrestaShop module

I know :sweat_smile: 

> when will the new version of cash on delivery module be compiled with new logo etc...??

I meant you can ask your question on the public Slack :wink:

**Comment by kpodemski** [comment]
Hi @alfonsolr09 

Feel free to join our [Slack channel](https://www.prestashop-project.org/slack/)

**Comment by alfonsolr09** [comment]
I just asked. I didn't remember you also used slack.thank you
