### ISSUE TITLE
Exception raised on specific payment methods

### ISSUE THREAD

**Issue by SD1982** [PrestaShop/PrestaShop#28400]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On FO after an order if payment method is "check payment" or "cash on delivery" an exception is raised instead of displaying order confirmation page

### Expected behavior

No exception should be raised, the order confirmation page should be displayed correctly

### Steps to reproduce

1. Go to FO and add a product to cart
2. Complete all the checkout process
3. In payment method section select "check payment" or "cash on delivery" method
4. Proceed to checkout
5. See error
![image](https://user-images.githubusercontent.com/40635814/166428977-689889de-7e92-4aa2-bff4-9884eda5a208.png)

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_cashondelivery 1.0.6 ////  ps_checkpayment 2.0.5

**Comment by hibatallahAouadni** [comment]
Duplicate of #27204

**Comment by hibatallahAouadni** [comment]
Duplicate of #28147
