### ISSUE TITLE
After upgrade 1.7.8.5 Undefined index: category_rewrite in ****/override/classes/Dispatcher.php on line 982

### ISSUE THREAD

**Issue by v1per4llbl4ck** [PrestaShop/PrestaShop#28401]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

when the quantity of product is 0 i have this error or when the product dont exist

Undefined index: category_rewrite in ****/override/classes/Dispatcher.php on line 982

	if($controller == 'product' && $_GET["category_rewrite"] == "")
		{
			$var = explode('/', $this->request_uri);
			$cont = count($var);
			if ($cont <= 2 && $var[0] ==  "" && $var[1] == "" )
			{
				$controller = 'index';
			}
		}
		if ($controller == 'cms' || $controller == 'category')
			{
			$category_request = explode('/', $_SERVER['REQUEST_URI']);
			$category_request = end($category_request);
			$id = explode('-', $category_request);
			//var_dump($_SERVER['REQUEST_URI']); echo $controller;exit;
			if ( is_numeric($id[0]))
			{
				array_shift($id);
				$name = implode('-', $id);
				//var_dump($_GET); var_dump($name); echo $controller; exit;

				$cid = $this->getKeyExistanceCMS($name);
				if ($cid)
				{
					$controller = 'cms';
					$_POST['id_cms'] = $cid;
					$_GET['cms_rewrite'] = $name;
				}

			}
			else
			{
				$cid = $this->getKeyExistanceCMS($category_request);
				if ($cid)
				{
					$controller = 'cms';
					$_POST['id_cms'] = $cid;
					$_GET['cms_rewrite'] = $category_request;
					unset($_GET["category_rewrite"]);
					unset($_GET["cms_rewrite"]);
				}
			}
			$_GET['fc'] = 'front';
			//var_dump($_GET); var_dump($_POST); echo $controller; exit;
			}
		if ($controller=='category' || $controller == 'product' || $controller == 'pagenotfound')
		{
			$category_request = explode('/', $this->request_uri);
			if (empty(end($category_request)))
				array_pop($category_request);

			$categ = explode('.', end($category_request));
			
			$ppid = $this->getProductExistance($categ[0]);
			$cpid = $this->getCategoryId($categ[0]);

			
			$id = explode('-', $categ[0]);

			if ( empty($ppid) && empty($cpid) && is_numeric($id[0]))
			{
				//var_dump($ppid); var_dump($cpid); exit;
				array_shift($id);
				$name = implode('-', $id);
				//var_dump($_GET); var_dump($name); echo $controller; exit;

				$pid = $this->getProductExistance($name);
				if ($pid)
				{
					if($pid)
					{
						$controller = 'product';
						$_POST['id_product'] = $pid;
					}
					else
					{
						$controller = 'product';
						$_GET['product_rewrite'] = $name;
					}
					//$_GET['product_rewrite'] = $name;
				}
				else
				{
					$cid = $this->getCategoryId($name);
					if ($cid)
					{
						$controller = 'category';
						$_POST['id_category'] = $cid;
						unset($_GET['category_rewrite']); 
						//$_GET['category_rewrite'] = $name;
					}
					else
					{
						$controller = 'category';
						$_GET['category_rewrite'] = $name;
					}
				}

			}
			else
			{
				$pid = $this->getProductExistance($categ[0]);
				$cid = $this->getCategoryId($categ[0]);
				if ($pid)
				{
					$controller = 'product';
					$_POST['id_product'] = $pid;
				}
				else if ($cid)
				{
					$controller = 'category';
					$_POST['id_category'] = $cid;
					unset($_GET['category_rewrite']); 
				}
			}

			// var_dump($_GET); 
			// var_dump($_POST);
			// var_dump($pid); 
			// var_dump($cid); 
			// echo $controller; exit;
		}
		//var_dump($_GET); var_dump($_POST); echo $controller; exit;
		$this->controller = str_replace('-', '', $controller);
		$_GET['controller'] = $this->controller;
		return $this->controller;
	}
	/*
		    * module: prettyurls
		    * date: 2019-03-20 12:46:40
		    * version: 2.2.5

### Steps to reproduce

go to https://www.agworksolution.it/it/scheda-elettronica/scheda-bassa-tensione-mod-nfa1194.htm
![Schermata 2022-05-03 alle 10 27 06](https://user-images.githubusercontent.com/82314915/166440706-cd69d2ab-8ad1-4039-883c-9e752a670436.png)
l

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

prettyurls v2.2.5

**Comment by florine2623** [comment]
Hello @v1per4llbl4ck ,

It seems like you have an issue with your override file. Can you remove it and try again ?

Thanks!

**Comment by v1per4llbl4ck** [comment]
remove dipatcher.php?

Il giorno mar 3 mag 2022 alle ore 14:03 florine2623 <
***@***.***> ha scritto:

**Comment by hibatallahAouadni** [comment]
Hello @v1per4llbl4ck 

It seems your issue is related to this module prettyurls. 
So, could you please contact the module developer :pray: 

Closing this issue as it's not related to the PS Core cause we only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you
