### ISSUE TITLE
On the install process, a module with max compliancy under the actual version will return an error and block the process

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#28417]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

While you trying to install PrestaShop and doesn't unselect modules that having the max version of `ps_versions_compliancy` set to, e.g., 1.7 version, you will have a return false (the install of the module is not possible, but without real errors) and the process will not continue.

The error say that error occuring during install, but without more details.

<img width="943" alt="Capture d’écran 2022-05-05 à 08 38 39" src="https://user-images.githubusercontent.com/2631425/166873606-5ce82972-46bc-4552-8eda-921186a41fef.png">

### Expected behavior

We could continue the process and add the warnings (no errors !) details of theses modules that are not compliant to be installed on the actual PrestaShop version.

### Steps to reproduce

1. Get a module with `$this->ps_versions_compliancy = array('min' => '1.5.5.0', 'max' => '1.7.99.99'); `inside it.
2. Add this module into the /modules folder
3. Go to the install
4. Make the settings
5. Go (and wait)

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by MatShir** [comment]
I propose that module not compatible with the PS should not be displayed and not installed. 
For the theme, it should not be allowed to install a theme if one of the module is not compat. (or not install the module 🤔)

**Comment by HanaRebaiQA** [comment]
Hello @PrestaEdit 

Thanks for your report. 
Could you please provide us the module that you use to can reproduce the issue ?

@MatShir So, could you confirm that's the expected behavior if the module is not compatible with PrestaShop ?

Thank you!

**Comment by PrestaEdit** [comment]
Hi @HanaRebaiQA,

For example, the specific 1.6 module Bankwire (https://github.com/PrestaShop/bankwire/archive/refs/tags/v1.1.2.zip).
It will do the job, I presume.
