### ISSUE TITLE
Outdated IP whitelist in Geolocation BO page

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#28419]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

I notice a IP whitelist in the BO (`International - Localization - Geolocation`). This list has not been updated for five years now.

### Describe the solution you'd like

After discussion with @matks:

- It is not the scope of Prestashop software to provide this list. It would be better to leave empty this configuration. (see https://github.com/PrestaShop/PrestaShop/blob/9a1067a61fe2b34497419ead4bb4b170e5a25484/install-dev/data/xml/configuration.xml#L324)
- Update the [user documentation](https://doc.prestashop.com/display/PS17/Geolocation) to indicate possible sources of this list.

### Additional context

[#14550 Allow to add IP ranges](https://github.com/PrestaShop/PrestaShop/issues/14550) is related, and would help to create a comprehensive list.

Discussed here: https://prestashop.slack.com/archives/CTKHSPWPM/p1651738850652949

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by matks** [comment]
I 👍  this

**Comment by HanaRebaiQA** [comment]
Hello @lmeyer1 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon.

We're waiting for your PR.

Thank you!

**Comment by lmeyer1** [comment]
@HanaRebaiQA 
IMHO, the details provided on Slack are sufficient as spec. Does not need `Needs Spec` flag.

**Comment by lmeyer1** [comment]
Specs:
- No longer preconfigure a whitelist, except for the loopback addresses `127.0.0.1, ::1`
- In the user documentation, mention possible sources for an address list https://www.ip2location.com/free/robot-whitelist or https://udger.com/resources/ip-list

**Comment by eshraw** [comment]
LGTM from a product point of view.
Thank you for the issue + PR @lmeyer1
