### ISSUE TITLE
Allow to translate new wordings in core modules

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#28418]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

I forked a core modules. I added a feature that required a ne wording to translate.

When I tried to translate it in the BO `International - Translations - Installed Modules translations`, the new wordings did not appear.

This behavior is specific to core modules.

### Describe the solution you'd like

I'd like to be able to translate new wordings in a fork of a core module using the BO.

### Alternatives you've considered

I found a workaround: 

1. Delete (and backup) the files pertaining to the module in the folder `/app/Resources/translations/default`.
2. Translate the new wordings in the BO and export the translation files
3. Restore the files deleted above.

### Additional context

See https://github.com/PrestaShop/ps_emailalerts/pull/113#discussion_r864592776.
Discussed here: https://prestashop.slack.com/archives/CTKHSPWPM/p1651654441661609

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by HanaRebaiQA** [comment]
Hello @lmeyer1 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon.

We're waiting for your PR.

Thank you!

**Comment by HanaRebaiQA** [comment]
ping @Julievrz

**Comment by HanaRebaiQA** [comment]
Hello @jolelievre Could you confirm if your [PR](https://github.com/PrestaShop/PrestaShop/pull/28377) can fix this issue ?

**Comment by Julievrz** [comment]
I think that's more a question for @PrestaShop/product-team

**Comment by lmeyer1** [comment]
> Hello @jolelievre Could you confirm if your https://github.com/PrestaShop/PrestaShop/pull/28377 can fix this issue ?

@HanaRebaiQA No this problem is not related to that PR.

**Comment by eternoendless** [comment]
I think this can be quickfixed by simply performing step 1 from the workaround.

**Comment by Robin-Fischer-PS** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29497
