### ISSUE TITLE
Incremental numbering starting from zero each year also for delivery slips as is the case with invoices

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#28421]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi

a my customer said me that the number of delivery slips should be like the invoices, starting from zero each year

https://medium.com/@scriby.it/documento-di-trasporto-ddt-la-guida-completa-d09cee5fb187

the current solution, present in prestashop 1.7.8.5, is not right

bye

### Expected behavior

the same options present for invoices, need to add those 3 options

![0](https://user-images.githubusercontent.com/653230/166921915-28a35dae-3fee-4b61-9cb3-ac02f0c21b16.png)

### Steps to reproduce

![7](https://user-images.githubusercontent.com/653230/166922002-b5aac4a9-74f7-4ad7-80da-68fdebec1d00.png)

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.3

**Comment by HanaRebaiQA** [comment]
Hello @maofree 

Thanks for your report.

I think that your suggestion is an improvement and not a bug.

@MatShir : What do you think ?

Thank you!

**Comment by MatShir** [comment]
Seems like a duplicate https://github.com/PrestaShop/PrestaShop/issues/19707
Thanks for the feedback, don't hesitate to have a look on the other issue and show your interest. It will help us prioritize

**Comment by Maofree** [comment]
ok thanks

**Comment by HanaRebaiQA** [comment]
Hello,

Thanks @MatShir for your feedback!

So, i'll close this issue as it's a duplicate of [#19707](https://github.com/PrestaShop/PrestaShop/issues/19707) 

Thank you!

**Comment by HanaRebaiQA** [comment]
Duplicate of [#19707](https://github.com/PrestaShop/PrestaShop/issues/19707)
