### ISSUE TITLE
API filter active reversed

### ISSUE THREAD

**Issue by thomas-Ngr** [PrestaShop/PrestaShop#28424]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Working on the API of a 1.7.7.6 with multiple shops.
When requesting the API for products with parameter ?filter[active], the result is not coherent:

filter[active]=[1] returns a products set, in which we find products where active = 0 or  active = 1

filter[active]=[0]  returns a products set, in which we find products where active = 0 or  active = 1

As a consequence, one cannot use the API to know if a product is active on the requested shop.

### Expected behavior

filter[active]=[1] should return all products where active = 1 *for the requested shop* , same for value 0.

### Steps to reproduce

0. see issue #25456 and reproduce the bug
1. Go to [https://YOUR-URL/api/products?display=[id,active]&filter[active]=0&id_shop=1](https://your-url/api/products?display=%5Bid,active%5D&filter%5Bactive%5D=0&id_shop=1) and check the last product created **is** displayed => nok It should **not** be displayed
2. check the "active" value for this product : it is set to 1 although the request filtered on `[active]=0`

```
kept for memory
1. get a connection to an API
2. request /api/products/?filter[active]=[1]
3. look for one result,
4. see that the <active> field is 0
```

### PrestaShop version(s) where the bug happened

1.7.7.6

**Comment by HanaRebaiQA** [comment]
Hello @thomas-Ngr 

Thanks for your report.

It seems that your issue is similar to this one [#25456](https://github.com/PrestaShop/PrestaShop/issues/25456). 
Could you confirm it ?

Thank you!

**Comment by thomas-Ngr** [comment]
Hi, thanks for the quick answer !

I can reproduce issue #25456. Both issues may be related, and mine may help solving the first.

After reproducing the issue as reported in #25456, one can do the following:
- Go to [https://YOUR-URL/api/products?display=[id,active]&filter[active]=0&id_shop=1](https://your-url/api/products?display=%5Bid,active%5D&filter%5Bactive%5D=0&id_shop=1) and check the last product created **is** displayed => nok It should **not** be displayed
- check the "active" value for this product : it is set to 1 although the request filtered on `[active]=0`

I edit the first message to make it more accurate.

**Comment by Roxayl** [comment]
When a specific shop context is specified (via a `id_shop` parameter), the webservice keeps filtering on the "active" field of the product table, instead of using the "active" field from the product_shop table.

The webservice generates the following query (notice the last condition) :

```sql
SELECT DISTINCT main.`id_product` FROM `product` AS main
 INNER JOIN `product_shop`
AS `multi_shop_product`
ON (main.`id_product` = `multi_shop_product`.`id_product`) 
WHERE 1 AND `multi_shop_product`.id_shop = 11  AND `main`.`active` LIKE "0";
```

This quick fix seems to solve this specific issue. However, I don't really have much time to understand thoroughly PrestaShop's core and this "fix" is done in a quick and dirty way, and is very specific to this issue in order to avoid any side effects.

```diff
diff --git a/classes/webservice/WebserviceRequest.php b/classes/webservice/WebserviceRequest.php
index 0975f5759e..ba7073a55b 100644
--- a/classes/webservice/WebserviceRequest.php
+++ b/classes/webservice/WebserviceRequest.php
@@ -1227,7 +1227,12 @@ class WebserviceRequestCore
 
                                     return false;
                                 } else {
-                                    if (isset($this->resourceConfiguration['retrieveData']['tableAlias'])) {
+                                    if( $field === 'active'
+                                        && $this->resourceConfiguration['objectNodeName'] === 'product'
+                                        && isset($this->urlFragments['id_shop'])
+                                    ) {
+                                        $sql_filter .= $this->getSQLRetrieveFilter('active', $url_param, 'multi_shop_product');
+                                    } else if (isset($this->resourceConfiguration['retrieveData']['tableAlias'])) {
                                         $sql_filter .= $this->getSQLRetrieveFilter($this->resourceConfiguration['fields'][$field]['sqlId'], $url_param, $this->resourceConfiguration['retrieveData']['tableAlias'] . '.');
                                     } else {
                                         $sql_filter .= $this->getSQLRetrieveFilter($this->resourceConfiguration['fields'][$field]['sqlId'], $url_param);
```

The generated SQL query :

```sql
SELECT DISTINCT main.`id_product` FROM `product` AS main
 INNER JOIN `product_shop`
AS `multi_shop_product`
ON (main.`id_product` = `multi_shop_product`.`id_product`) 
WHERE 1 AND `multi_shop_product`.id_shop = 11  AND `multi_shop_product`.`active` LIKE "0";
```

**Comment by hibatallahAouadni** [comment]
Hello @Roxayl & @thomas-Ngr 

After reading all the provided infos, your issue is duplicate of #25456
I see no difference :thinking: 
Well I need to close this issue as we are aware of it and it is already in our debug backlog. 
This issue is a duplicate of #25456. To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #25456
