### ISSUE TITLE
[ERROR 500] Profiler : Key "widget" does not exist as the array is empty.

### ISSUE THREAD

**Issue by Codeskto** [PrestaShop/PrestaShop#28432]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![error_500_key_widget](https://user-images.githubusercontent.com/99411608/167080379-367d02dc-b727-4edc-a4c4-88560b94ad17.png)

### Expected behavior

Display Hooks tabs in the profiler

### Steps to reproduce

1. Enable debug mode
2. Go to a single product page in admin
3. Save the product
4. Profile the last POST request
![image](https://user-images.githubusercontent.com/99411608/167080988-5c2e8c62-64fa-45e3-a812-02db72051fa3.png)
5. Go to the hooks tab
![image](https://user-images.githubusercontent.com/99411608/167080577-dab762c0-d717-4bfa-9f1b-20590bdd770d.png)

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.3

**Comment by Codeskto** [comment]
A hook method in a module was in private instead of public
```
private function hookActionAdminProductsControllerSaveAfter
```
it made the profiler crash

**Comment by marwachelly** [comment]
Hello @Codeskto,

I didn't reproduce the issue on develop branch also.

Thanks,
