### ISSUE TITLE
BO - The upgrade button is not displayed after enabling or disabling a module

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#28433]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Modules > Module Manager page, when we try to disable or enable a module => the Upgrade button is not displayed

This issue is reproduced with

- Faceted search: v3.7.1 > v3.8.0
- Image slider: v3.1.0 > v3.1.1
- Sales and orders: v2.0.0 > v2.1.0
- Search bar: v2.1.2 > v2.1.3

https://user-images.githubusercontent.com/16067358/167093567-d66c994d-a563-4fc2-bb10-76118707e4e2.mp4

### Expected behavior

Only display the upgrade button on this page, hide the others buttons actions (disable, uninstall....) then displays a success message and all the buttons after the upgrade

### Steps to reproduce

1. Go to BO > Modules > Module manager page
2. Go to the Updates page or search for a module with an upgrade available in the Modules tab
3. Click on Disable/Enable a module
4. Check the list 
5. The upgrade button is not displayed

**Before**
![image](https://user-images.githubusercontent.com/16067358/167093863-d6a508d9-bf2a-41fb-a699-527bc7b2e615.png)

**After**
![image](https://user-images.githubusercontent.com/16067358/167093838-c6c42e94-194e-4318-b009-ea6f5241277b.png)

I tried with PS1785 & Image slider: v3.1.0 > v3.1.1 => OK

https://user-images.githubusercontent.com/16067358/167094294-b5e25af6-4d82-42f9-b386-e1742927ebab.mp4

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.0

**Comment by MeKeyCool** [comment]
I take this one :)

**Comment by MeKeyCool** [comment]
I noticed that if I upgrade a module, it is not removed from update list as well.

**Comment by MeKeyCool** [comment]
After few tests, I suspect that "upgrade all" button doesn't work but maybe it is from my setup :thinking: .

**Comment by matks** [comment]
Issue blocked because of latest findings on PR https://github.com/PrestaShop/PrestaShop/pull/28612

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29512
