### ISSUE TITLE
BO - Product page V2 & V1 - The alternative currency symbol is not displayed in the product V2 & V1

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#28430]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When we create an alternative currency, the symbol of this currency is not displayed on the Product page V2
![image](https://user-images.githubusercontent.com/16067358/166961624-0c77bc97-742f-4f2f-8fdf-c7d46b1fe6b1.png)

### Steps to reproduce

1. Go to BO > International > Localization > Currencies page
2. Add an alternative currency and enable it
![image](https://user-images.githubusercontent.com/16067358/166961922-5dacbf85-17e4-4497-b5d4-fd7436abe3f8.png)
3. Go to BO > International > Localization page
4. Se the new currency created as a default currency and save 
![image](https://user-images.githubusercontent.com/16067358/166962109-cef90a2a-3eb2-49a0-9cf2-0e4182a876a6.png)
5. Go to BO > Catalog > Products > Edit a product V2
6. In the pricing tab > the currency symbol is empty
6.1 Retail price (tax excl.) & (tax incl.)
6.2 Retail price per unit (tax excl.) & (tax incl.)
6.3 Cost price (tax excl.)
6.4 When adding a specific price: `Set specific price (tax excl.)` filed & `Reduction amount` field
6.5 Combinations tab > `Cost price (tax excl.)` & `Impact on price (tax excl.)` & `Impact on price (tax incl.)` & `Impact on price per unit (tax excl.)` & the `Cost price (tax excl.)` of a supplier
6.6 In the Options tab: the  `Cost price (tax excl.)` of a supplier

![image](https://user-images.githubusercontent.com/16067358/166963311-6b506e10-d9e0-4695-aa27-7a986de2ae9c.png)

I tried with PS1785 & PS1778 => Same issue

![image](https://user-images.githubusercontent.com/16067358/166965304-7f2d6857-6538-436a-a891-22f93a05253f.png)

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

1778, 1785, 8.0

**Comment by mparvazi** [comment]
dev-core

Please stop using this weirdo function:

![Screenshot from 2022-05-05 12-55-21](https://user-images.githubusercontent.com/85633460/166976761-b5b43bee-c31a-4c1b-be61-dc41588593a0.png)

It doesn't support custom currencies.
It doesn't support a currency when numerical symbols in locale are not ASCII (e.g. Persian)

I think it's better to design your own.

**Comment by mparvazi** [comment]
@PrestaShop/prestashop-core-developers 

Please don't use this function:

![Screenshot from 2022-05-05 12-55-21](https://user-images.githubusercontent.com/85633460/166976761-b5b43bee-c31a-4c1b-be61-dc41588593a0.png)

Ln 104: It doesn't support custom currencies.
Ln 112: It doesn't support a currency when digits in language's locale are not ASCII (e.g. Persian): https://github.com/PrestaShop/PrestaShop/issues/27051

I think it's better to define your own.

**Comment by matks** [comment]
@mparvazi Are you referring to MoneyType::getPattern() ?

https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/Form/Extension/Core/Type/MoneyType.php#L110

(if yes I think the great people from https://github.com/symfony might be interested in your feedback)

**Comment by mparvazi** [comment]
@matks 

> @mparvazi Are you referring to MoneyType::getPattern() ?

Yes!

I created an issue and suggest solution at there (related to languages that doesn't use ascii digits):
https://github.com/symfony/symfony/issues/44959

But it seems no one interested in this problem :|

**Comment by mparvazi** [comment]
IMO just need to override this function for currency sign position:

![Screenshot from 2022-05-09 12-11-07](https://user-images.githubusercontent.com/85633460/167452145-ddeec2a2-68f3-429e-8eb0-68141a3a2dcd.png)
