### ISSUE TITLE
Error translate install Prestashop

### ISSUE THREAD

**Issue by Grezor** [PrestaShop/PrestaShop#28442]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

 translation error: in the content of your store menu [Prestashop language FR]

![image](https://user-images.githubusercontent.com/38507456/167255316-04047d22-ae9d-4e1c-9f11-0e86c60e608d.png)

### Expected behavior

There is a bad translation on prestashop English, there is the sentence content of your store
![image](https://user-images.githubusercontent.com/38507456/167255443-95624ca7-a3e8-4e0f-852a-87a5b60641d4.png)

### Steps to reproduce

I forked the project, then I did a docker compose up -d --build then I went to the browser. 

I typed : http://localhost:8001/install-dev/
I put prestashop in FR language
In the 4th step => I see translation error "Content of your store". 

### PrestaShop version(s) where the bug happened

PrestaShop 8.0.0 branch actually develop

### PHP version(s) where the bug happened

PHP 7.1.9

**Comment by Grezor** [comment]
![image](https://user-images.githubusercontent.com/38507456/167255782-e68112db-bce6-44b0-b13d-f927103ae765.png)

**Comment by Grezor** [comment]
![image](https://user-images.githubusercontent.com/38507456/167261049-ff6ec1fb-e67a-4cf9-930f-54223e059f1a.png)

**Comment by matks** [comment]
Hi @Grezor I'm not sure it's an error 😉 

You see, PrestaShop is in English by default. Then all the sentences and words used in the software are exported inside the translation platform Crowdin (https://crowdin.com/project/prestashop-official). On this platform, translation contributors can translate the software in their language.

But ... what happens if, because there is so many words to translate, some words are not translated? So for example if on the install page you present, 70% of the English words have a French translation but for 30% of the words there is no French translation? Then the software displays the English version, as a fallback 😅 because it's better than nothing.

So if I'm not wrong "Content of your store" is displayed because, on Crowdin, the sentence "Content of your store" has not yet been provided a French translation. Something that, if you wish to, you will be able to help by contributing on the Crowdin project 😉 . But as PrestaShop 8.0.0 is not frozen yet I'm not sure it's possible to start translating it yet 🤔 .

**Comment by hibatallahAouadni** [comment]
Hello @Grezor 

As @matks said this page is a new page and the translation is not done yet:

![image](https://user-images.githubusercontent.com/23308427/167386529-ccdf151d-04c6-4d85-b741-0f36de8d940f.png)

As you can see some sentences are translated and some no!
And if you check the code, you will see that the developers use the translator method:

![image](https://user-images.githubusercontent.com/23308427/167387097-ba07a9d6-d17f-42ae-af52-1153338aa5ed.png)

> 70% of the English words have a French translation but for 30% of the words there is no French translation? Then the software displays the English version, as a fallback :sweat_smile:  because it's better than nothing.

Thanks for reproting the issue and we're waiting for your help to improve the translation on Crowdin :muscle: 

PS: @matks should I close the issue? or keep it open?

Thanks!

**Comment by matks** [comment]
I think we can close the issue as it's not a problem. This is the expected behavior as English is used when no translation is available.

**Comment by Grezor** [comment]
Hello @matks @hibatallahAouadni 
Should I add the French translation (contribution)
I will not hesitate to create other issues if I see other problems.

Geoffrey D

- But why put so many labels?
- However, one point I would like to add when creating an issue. By default it adds the label bug ? 
![image](https://user-images.githubusercontent.com/38507456/167634101-69071920-aab4-4a60-bbfe-95094ce0ddbd.png)

-

**Comment by hibatallahAouadni** [comment]
> one point I would like to add when creating an issue. By default it adds the label bug

@Grezor indeed :smile: cause you choose the **Bug Report**, so the bot will add auto these two labels: `Bug` and `New`
if you choose the **Feature Request**, the `Feature` and `New` labels will be added auto :wink: 

Don't hesitate if you have another question :relaxed:

**Comment by hibatallahAouadni** [comment]
> Should I add the French translation (contribution)

Yes, please :pray: here's the link of [Crowdin](https://crowdin.com/project/prestashop-official) :rocket: 

Thanks in advance!

**Comment by Grezor** [comment]
Hello @hibatallahAouadni, 

I would like to contribute to the issue I created to add the translation.
Searching on the internet, there is not much information on how to do...
Can you tell me the steps to follow?

Thanks in advance

**Comment by MatShir** [comment]
Hi @Grezor, 
We have an old documentation https://build.prestashop.com/howtos/translation/new-translator-guide-available-now/ about how to translate. We might need to update it, but it should do the job. There are also translator in the Friend of Presta group, that might help you as well

But, nice to see you motivated, so just to let you know. If you are looking for other kinds of contribution, we have the label [good first issue](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+first+issue%22) and [trivial](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aopen+is%3Aissue+label%3ATrivial) that are recommended to the beginner on the project.

**Comment by Grezor** [comment]
Hi @MatShir,

Thanks for your feedback, I'll look into it in detail in the next few days. I can see to try to update it. 
I'm in the friend of presta group :) .

**Comment by Grezor** [comment]
I have contributed to the translation, pending validation

**Comment by MatShir** [comment]
Nice ! don't hesitate to check the #[translation](https://join.slack.com/share/enQtNDA2NzA3MTY1MjE2Mi02ZDM3MTRmMDQ0OWZhYzYyZDlkNTkxNTkyZGZhYjVkZjE0ZmUyN2QxMGViZDFmZDg4MjQ1OTBlMjFjMzFjMmRj) channel in our slack for updates
