### ISSUE TITLE
Prestashop v1.7.3.1 : composer needs prestashop/smarty but it has disappeared 

### ISSUE THREAD

**Issue by estebanwoj** [PrestaShop/PrestaShop#28455]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

``` 
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading prestashop/smarty (dev-master c141c2a)
    Failed to download prestashop/smarty from dist: The "https://codeload.github.com/PrestaShop/smarty/legacy.zip/c141c2a15d5bffae23a45a791374fd0753749793" file could not be downloaded (HTTP/2 404 )
    Now trying to download from source
  - Syncing prestashop/smarty (dev-master c141c2a) into cache
  - Installing prestashop/smarty (dev-master c141c2a): Cloning c141c2a15d
    c141c2a15d5bffae23a45a791374fd0753749793 is gone (history was rewritten?)
    Install of prestashop/smarty failed


  [RuntimeException]
  Failed to execute git checkout 'c141c2a15d5bffae23a45a791374fd0753749793' -- && git reset --hard
   'c141c2a15d5bffae23a45a791374fd0753749793' --

  fatal: reference is not a tree: c141c2a15d5bffae23a45a791374fd0753749793

  It looks like the commit hash is not available in the repository, maybe the commit was removed f
  rom the branch? Run "composer update prestashop/smarty" to resolve this.
```

Sadly, the package (https://packagist.org/packages/prestashop/smarty) has been abandonned.
But is there a way to fix this on a ```composer install``` ?

Atm, there's no need to update the shop which is v1.7.3.1
I'm really surprised the branches have been deleted.
What's the workaround ? 

### Expected behavior

Modifying the composer json to maintain compatibility with older versions

Maintain compatibility with previous versions.

### Steps to reproduce

1. If you can, i'm always redirected by your site web now, download Prestashop 1.7.3.1
2. Try to install a fresh copy.
3. composer install say that package prestashop/smarty is missing and branch has been deleted

### PrestaShop version(s) where the bug happened

1.7.3.1

### PHP version(s) where the bug happened

7.1.33

**Comment by florine2623** [comment]
Hello @estebanwoj ,

I have installed my shop 1.7.3.1 with the zip provided [here](https://www.prestashop.com/en/versions).
I have access to both my BO and FO :
<img width="1424" alt="Screenshot 2022-05-10 at 17 10 08" src="https://user-images.githubusercontent.com/16019289/167661939-311e4001-371c-4003-9677-e7bb6a047a22.png">
<img width="1168" alt="Screenshot 2022-05-10 at 17 10 19" src="https://user-images.githubusercontent.com/16019289/167661956-ed3edc29-b402-4eef-a7f2-37231f2f47e4.png">

I did not encounter any issue with composer. I am using Composer version 1.10.5.

Is there something I am missing ?
Please check and feedback.

**Comment by matks** [comment]
@florine2623 the contributor is trying to install the sources ;) not uzing the ZIP

@estebanwoj PrestaShop 1.7.3.1 is old software from 2017 or 2018 😅  . But the tags are still there https://github.com/prestashop/prestashop/tree/1.7.3.1

I see no strange activity on https://github.com/prestashop/smarty and I see no rewrite.

I'm sorry but I joined the project in mid 2018 so I have no idea what happened to https://github.com/PrestaShop/smarty/

@Quetzacoalt91 do you remember what was the usage of the smarty fork in 2017 / 2018 ?

**Comment by estebanwoj** [comment]
Thank you for your reactivity.

Yes you aren't using the composer.json version so there's no problem for you.
vendor folder is here

try to use this file : 
https://github.com/PrestaShop/PrestaShop/blob/e32f7fdca91af6196781bd948cb9bd5b13bb4816/composer.json
by using ```composer install``` with composer 1.10, you'll get the error

**Comment by Quetzacoalt91** [comment]
> @Quetzacoalt91 do you remember what was the usage of the smarty fork in 2017 / 2018 ?

I don't remember exactly, but it could be different causes.
- We had an issue where if you used a bad root path, the "cache cleaner" of smarty started to clean every PHP file it can find from the filesystem **root**.
- There was some security issues we wanted to add in PrestaShop without waiting for a release on Smarty side.

**Comment by matks** [comment]
Thank you for answers @Quetzacoalt91 

@estebanwoj I think answers are the only thing we can provide.

If you need to be able to run a `composer install` for 1.7.3 I think you can do this:

1. Use the 1.7.3 build to extract `vendor/prestashop/smarty`
2. Host this folder as your own library on GitHub, for example call this estebanwoj/prestashop-smarty-fork
3. Modify composer.json to use your fork instead of prestashop/smarty (see https://www.mathieu-ferment.com/blog/post/2017-01-31/Use+github+fork+as+composer+dependency for example)
4. You should be able to run `composer install` and Composer will fetch YOUR library, your hosted package instead of looking on https://github.com/prestashop/smarty
