### ISSUE TITLE
Number of product to display field allows all characters (Products in the same category module)

### ISSUE THREAD

**Issue by Saimis777** [PrestaShop/PrestaShop#28454]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The field "Number of product to display" in the module "Products in the same category" accepts any sort of characters, when random characters, not numbers are entered, the module allows to save them.

![image](https://user-images.githubusercontent.com/75423142/167650944-9e213d11-d751-446c-b910-8f49d2434674.png)

### Expected behavior

Any characters apart from numbers should be not allowed, and when saving should show an error that the field input is incorrect. 

### Steps to reproduce

1. Go to module catalog
2. Install module "Products in the same category"
3. Enter the module configuration
4. In the field "Number of product to display" enter random letters, characters
5. Press "Save".

### PrestaShop version(s) where the bug happened

1.7.8.4

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

Products in the same category v1.0.4

**Comment by florine2623** [comment]
Hello @Saimis777 ,

I couldn't reproduce the same issue as you. Once I click on save the letters are gone, only the numbers before the letters are kept :

https://user-images.githubusercontent.com/16019289/167658797-3389083f-b4b8-4752-b630-c122f1585a38.mov

So I will close your issue.
Thanks !
