### ISSUE TITLE
{$product.delivery_in_stock} bug on related products on the product page

### ISSUE THREAD

**Issue by E-loou-JF** [PrestaShop/PrestaShop#28457]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

hi.
i'm using {$product.delivery_in_stock} to display the data on the product page and also on the miniatures on \templates\catalog\_partials\miniatures\product.tpl
both are working great except for the miniatures of the related products on the product page.
As i call it twice, once on the product and once on the associated product, is it a problem ?
on the homepage, featured products & the category pages, the display is ok, so the product.tpl works fine but not for the related products which use the same tpl.
Is there a solution 
![product-delai](https://user-images.githubusercontent.com/66671328/167660589-651ccfa0-9f38-4f01-b89b-03334d1541e6.png)
?

### Steps to reproduce

add {$product.delivery_in_stock} to \templates\catalog\_partials\miniatures\product.tpl

add {$product.delivery_in_stock} to \templates\catalog\product.tpl

add related product to a single product

### PrestaShop version(s) where the bug happened

1.7.8.4

**Comment by florine2623** [comment]
Hello @E-loou-JF ,

Are the following fields filled with your delivery information ?

In product page :
<img width="598" alt="Screenshot 2022-05-10 at 18 05 34" src="https://user-images.githubusercontent.com/16019289/167673325-ddbcac8f-66be-4fd3-a115-2a80844038d5.png">

In product settings page :
<img width="864" alt="Screenshot 2022-05-10 at 18 05 58" src="https://user-images.githubusercontent.com/16019289/167673340-7b818044-a6e0-445b-8dcc-de15396d4817.png">


Could you send the 3 files mentioned ? 

Thanks!

**Comment by E-loou-JF** [comment]
Hello @florine2623 
Yes those fields are filled as the delivery information is display on the homepage/featured products and on the category list page.

here the two files i mentionned, i don't know what is the third file ?
[catalog.zip](https://github.com/PrestaShop/PrestaShop/files/8663548/catalog.zip)
L 213 of the product.tpl (main one)
L 51 of the product.tpl in _partials/miniatures/

Thank you for your help!

**Comment by E-loou-JF** [comment]
@florine2623 do you know how to get  {$product_accessory.delivery_in_stock} 
as the minitaure call the product.tpl with  product=$product_accessory 
?

**Comment by hibatallahAouadni** [comment]
Hello @E-loou-JF 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a module problem.

We will close this issue cause we only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thanks!

**Comment by E-loou-JF** [comment]
@hibatallahAouadni 
it is a prestashop core issue !
there is no third party addons !
it's a bug regarding prestashop native modules.
How can {$product.delivery_in_stock} could be different in the same NATIVE tpl file ?
Native $product data, native miniatures/product.tpl file, doesn't work on native related products module.
i already ask on the commmunity forums and it's clearly a problem with the prestashop core.

**Comment by E-loou-JF** [comment]
sorry. problem not solve

**Comment by compsoul** [comment]
Same. {$product.delivery_in_stock} on product tpl shows empty string.
