### ISSUE TITLE
Bug in German Translation -  Variants

### ISSUE THREAD

**Issue by demeldoo** [PrestaShop/PrestaShop#28450]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi... in German translation. Reference and product reference is translated same as Artikel nr

### Steps to reproduce

Import and try to.import and map fields

### PrestaShop version(s) where the bug happened

1.75.5

### PHP version(s) where the bug happened

7.1

**Comment by hibatallahAouadni** [comment]
Hello @demeldoo 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
