### ISSUE TITLE
if "Terms of service" disabled and there's only one payment method, the button looks disabled and the add infos is missing

### ISSUE THREAD

**Issue by szavadskiy** [PrestaShop/PrestaShop#28466]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

"**PLACE ORDER**" button looks disbaled  and “**payment additional information**” missing

ISSUE checked on several PS 1.7.x versions and reproducing only with 1.7.8.x
1.7.8.5 - reproducing
1.7.8.6 - reproducing
1.7.7.4 - not reproducing
1.7.6.9 - not reproducing

If selected, only one payment in BO:
![scrnli_11_05_2022_15-35-46](https://user-images.githubusercontent.com/90208051/167863362-f1992a1d-0b75-4100-93ba-8e070ae53f94.png)

and "Terms of service" disabled in BO
![scrnli_11_05_2022_15-18-55](https://user-images.githubusercontent.com/90208051/167863276-5ba6eac8-b255-4d04-840b-2ce40068720f.png)

"PLACE ORDER" button is not available on checkout, yet you can click on it and the order will be created 
=> this issue is fixed on develop by this PR #22389 :heavy_check_mark: 
But, the **payment additional information** is hidden :x: 
![scrnli_11_05_2022_15-36-34](https://user-images.githubusercontent.com/90208051/167863639-6f80b00d-aef2-42c9-b3aa-916959ce26fa.png)

### Expected behavior

"PLACE ORDER" button and “payment-option-1-additional-information” line is available at checkout as in previous versions 1.7.7.x, 1.7.6.x
![Screenshot 2022-05-11 at 17 00 35](https://user-images.githubusercontent.com/90208051/167885666-45386a58-eed8-4b9a-ad26-48d523082959.png)

### Steps to reproduce

1. BO >CONFIGURE > Shop Parameters > Order settings
2. Disable: "Terms of service" and Save
3. IMPROVE > Payment > Preferences page
4. in "Country restrictions" disable all payment methods except one  (for ex.:Pay by bank wire)
5. go to FO and add a product to the cart
6. go to checkout > payment step
7. See error > the button **PLACE ORDER** looks disbaled
8. See error > the **payment additional information** is hidden
9. Click on the button > the order is well created

### PrestaShop version(s) where the bug happened

1.7.8.0 & develop

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment]
Hello @szavadskiy 

Thanks for the detailed bug report :clap: 
The button looks disabled but you can click on it :sweat_smile: and we already fix the issue on develop, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/167879109-cbec79f8-5b32-4630-9750-ccb6d015bc75.mp4

Closing the issue as it's fixed :pray: 
Thanks!

**Comment by hibatallahAouadni** [comment]
Related to #9927

**Comment by MatShir** [comment]
The bug is fixed in the 8.0, I'm going to close the issue. We won't have time to fix this bug for the last bug patch of the 1.7.8.

**Comment by ghost** [comment]
@MatShir no fixed a part only :)

**Comment by ghost** [comment]
https://github.com/PrestaShop/PrestaShop/issues/29371

**Comment by ghost** [comment]
Normaly broken checkout it's a critical issue if we look https://devdocs.prestashop.com/1.7/contribute/contribution-process/how-issues-are-sorted/

**Comment by matks** [comment]
@okom3pom It is different 😄 

"Checkout is broken, people cannot place orders"
is different from
"The checkout is broken when {...}"

It depends on what is "when".

**Comment by pallamandra** [comment]
Actually the issue is not corrected. Im having exactly the same and using the lates version of prestashop and everything updated. The button Place Order is clickable but not functional when i set up only paypal as a payment method. 


<img width="783" alt="Screenshot 2023-09-01 at 10 34 10 AM" src="https://github.com/PrestaShop/PrestaShop/assets/143792175/b820c07e-27b4-43c3-8ec0-66d918e1df6d">
<img width="780" alt="Screenshot 2023-09-01 at 10 34 22 AM" src="https://github.com/PrestaShop/PrestaShop/assets/143792175/edf62740-5dcd-4246-8693-e9167c06583a">

**Comment by MatShir** [comment]
Wrong configuration, maybe ? Have you checked with the module developer ?
