### ISSUE TITLE
BO - Category root cannot be modified when multistore is active

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#28478]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I try to edit my category root I have an error :
<img width="1423" alt="Screenshot 2022-05-12 at 16 26 31" src="https://user-images.githubusercontent.com/16019289/168111254-a92e5b06-030d-4cde-a60d-71308d92a6ee.png">

Without multistore, I can edit my category correctly.

### Expected behavior

I should be able to edit the name of my root category

### Steps to reproduce

1. Enable Multishop, create and configure a second shop
2. Go to Catalog > Categories
3. Edit Home category's name

This will happen with All shop context and with a specific shop. 

### PrestaShop version(s) where the bug happened

1.7.8.5, 1.7.8.6

### PHP version(s) where the bug happened

7.1

**Comment by MatShir** [comment]
Check the behavior in all shops

**Comment by AureRita** [comment]
Hello @MatShir, 

I tried to reproduce this issue but I currently can't as you can see : 

https://user-images.githubusercontent.com/100699445/191047483-6cd81f9e-f4d8-4474-b7b0-15dab864167e.mp4

Thank you

**Comment by florine2623** [comment]
Hello @MatShir @eshraw 

Tested again by @AureRita and myself.

Tested on `1.7.8.5`, `1.7.8.6`, `1.7.8.x`, `8.0.x`, `develop`.
PHP 7.1 and 7.4.

Tested on `All shops`, `Default group` and a `specific shop`.

For whatever reason, we can't reproduce the issue 😅 

So I will close the issue.
