### ISSUE TITLE
Blockwishlist can't be upgraded

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/PrestaShop#28472]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

There's [new release of blockwishlist v.2.1.0](https://github.com/PrestaShop/blockwishlist/releases/tag/v2.1.0) published almost 3 weeks ago, but none of the shops informs about this update, so they're stuck with v.2.0.1. Why is that?

### Expected behavior

Update should be available in Modules -> Updates tab

### Steps to reproduce

1. Confirm you have v.2.0.1 installed
2. Check Modules -> Updates tab

### PrestaShop version(s) where the bug happened

1.7.8.4

### PHP version(s) where the bug happened

7.3,7.4

### If your bug is related to a module, specify its name and its version

blockwishlist v.2.1.0

**Comment by matks** [comment]
In PrestaShop 1.7.x module updates are managed by PrestaShop SA Addons API. So if a module update is not available it could be because of an issue in Addons API

**Comment by hibatallahAouadni** [comment]
Hello @SharakPL 

I reproduce the issue with PS1777 and PS1785, see the attached screenshot below:

https://user-images.githubusercontent.com/23308427/168122277-238aa3de-4f8b-4729-9998-27702d46876d.mp4

This issue happen only with this module and as @matks said "if a module update is not available it could be because of an issue in Addons API".
@matks could you please verify the Addons API :pray: 

Thanks in advance!

**Comment by matks** [comment]
@hibatallahAouadni I am sorry but ... on my shop I am able to upgrade to v2.1.0 😅 

So I cannot verify an issue I cant reproduce.

Can you try again? Maybe it was a temporary issue?

**Comment by SharakPL** [comment]
> Can you try again? Maybe it was a temporary issue?

Nope. I still can't see any update. Logged into addons in admin panel, cleared cache, but no change.

**Comment by hibatallahAouadni** [comment]
Hello @matks 

I still reproduce the issue with PS1786, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/170533543-94b3f224-7a63-491b-8158-500739a5ae95.mp4

Thanks!

**Comment by leemyongpakvn** [comment]
@SharakPL It looks like the upgrade problem with PrestaShop SA Addons API is solved now. I have no problem on a fresh installation of PS 1.7.8.4 
![PS1784_wishlist201_upgrade](https://github.com/PrestaShop/PrestaShop/assets/3759923/5443262e-a09d-44d8-84db-90adf8f6f277)

**Comment by SharakPL** [comment]
Yes, seems to be fixed.
