### ISSUE TITLE
Date format does not have a strict format

### ISSUE THREAD

**Issue by Saimis777** [PrestaShop/PrestaShop#28471]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When editing a language, the field "date format" is marked as mandatory, has a help text by which the format should look like, but you can enter random symbols or letters, and successfully save the date format, though it should not do that, should show an error if the format is invalid, or random characters are being saved. 

Same with the field below "Date format (full)".

![image](https://user-images.githubusercontent.com/75423142/168036439-d07aeba5-6ae8-47de-bd8f-6c16dc5cd903.png)

### Expected behavior

Should show an error, and not allow to save random date formats. 

### Steps to reproduce

1. Go to International -> Localization -> Languages.
2. Edit an existing or create a new language.
3. In the field "Date format" or "Date format (full)" input some random symbols.
4. Press "Save".

### PrestaShop version(s) where the bug happened

1.7.8.4

### PHP version(s) where the bug happened

7.1

**Comment by hibatallahAouadni** [comment]
Hello @Saimis777 

Thanks for reporting the issue!
I reproduce the issue with PS1777, PS1785 and develop, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/168135405-1894b94b-138c-483e-9aa9-502378880b0f.mp4

I'll add to the Backlog to be fixed.

Thanks!

**Comment by florine2623** [comment]
Hello ,

As seen with @ibahloul-ps , this is not a bug.
You have the possibility to add date format to your liking. However this is the responsibility of the merchant to write a correct date format.

I am closing this issue to avoid clogging the backlog.

Thanks!
