### ISSUE TITLE
BO- The position of the green alerte is wrong in the product page case of multistore

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#28476]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The position of the green alerte is wrong in the product page case of multistore

https://user-images.githubusercontent.com/89604350/168086658-a1f67bb9-2eb7-4c6a-b574-fab852ae3a73.mp4

**PS 1.7.8.3:**
![image](https://user-images.githubusercontent.com/89604350/168087399-d3261982-de27-413c-b85e-6231a7a1bc42.png)

**PS1.7.8.2:**
![image](https://user-images.githubusercontent.com/89604350/168086822-48e06375-1bc5-4f2c-bf41-0674f1961da8.png)

### Expected behavior
The green alert is bellow the multistore bar.

### Steps to reproduce

1. Go to BO > Click on Products
2. Click on Actions to duplicate the product
3. see error

### PrestaShop version(s) where the bug happened

1.7.8.3/1.7.8.4/1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Fixed on 9.0.X

![Image](https://github.com/user-attachments/assets/322060d9-15e8-4895-ad18-cf6a9156c87b)
