### ISSUE TITLE
customer_qty.html

### ISSUE THREAD

**Issue by blawdi** [PrestaShop/PrestaShop#28475]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I no have the name of product in mail 

![c8YiIAZ](https://user-images.githubusercontent.com/27147133/168068189-19398ef2-97cc-4735-a6e1-3d4c93b946b3.png)

### Expected behavior

display product name in mail customer_qty.html

### Steps to reproduce

Not concerned

### PrestaShop version(s) where the bug happened

1.7.6.5

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment]
Hello @blawdi 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must provide steps to reproduce the bug**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
