### ISSUE TITLE
Install cannot run if there is no theme - improve error message

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#28480]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If there is no Theme in `themes/` folder you cannot install PrestaShop. When you visit `myshop/install-dev/` you see an error message (see below)

This is OK 👍  it does not make sense to install PrestaShop without a theme. But the error message does not tell you the root issue 😅  so you're stuck. We need to provide an error message that helps the user to understand what is the issue.

### Expected behavior

When there is no Theme in `themes/` folder, we display a message saying that PrestaShop cannot be installed without a valid theme.

### Steps to reproduce

1. Fetch the latest changes from `develop` branch
2. Then remove the `themes/classic` folder (delete it): now there is no valid theme on your shop
3. Try to start the standard web install interface: browse `myshop/install-dev/`
4. See below error

![Capture d’écran 2022-05-12 à 18 00 06](https://user-images.githubusercontent.com/3830050/168119038-5974bb7e-b6c3-4465-bf6a-93771ac4ea97.png)

### PrestaShop version(s) where the bug happened

develop

**Comment by hibatallahAouadni** [comment]
Reproduced on 178x too: 
`Fatal error: Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Notice: Undefined offset: 0 in /projects/presta178x/PrestaShop/install-dev/init.php:131 Stack trace: #0 /projects/presta178x/PrestaShop/install-dev/index.php(43): require_once('/projects/prest...') #1 {main} thrown in /projects/presta178x/PrestaShop/install-dev/init.php on line 131`
