### ISSUE TITLE
unable to create product using webservice 

### ISSUE THREAD

**Issue by Jordanmarjot** [PrestaShop/PrestaShop#28489]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello, 
I have a problem with post request using webservice, my post request return a 200 status and the list of my product but not create product. 
![image](https://user-images.githubusercontent.com/71250621/168267193-798ee3e6-2c48-470b-bba3-d79e399d781e.png)
i'm using the blank schema in the body

### Steps to reproduce

go to postman 
post this request : https://.email@email.com/api/products/

### PrestaShop version(s) where the bug happened

1.7.7.2

**Comment by hibatallahAouadni** [comment]
Hello @Jordanmarjot 

I didn't manage to reproduce the issue with PS1785 :disappointed: 
Could you please provide the xml body that you use to create the product, cause it may contain some errors :pray: 
Waiting for your feedback.

THanks!

**Comment by Jordanmarjot** [comment]
Hello, thanks for your answer, I test so much body, there is one : 
`
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">

    <product>
        <id></id>
        <id_manufacturer>10</id_manufacturer>
        <id_supplier></id_supplier>
        <id_category_default></id_category_default>
        <new></new>
        <cache_default_attribute></cache_default_attribute>
        <id_default_image></id_default_image>
        <id_default_combination></id_default_combination>
        <id_tax_rules_group></id_tax_rules_group>
        <position_in_category></position_in_category>
        <type></type>
        <id_shop_default></id_shop_default>
        <reference></reference>
        <supplier_reference></supplier_reference>
        <location></location>
        <width></width>
        <height></height>
        <depth></depth>
        <weight></weight>
        <quantity_discount></quantity_discount>
        <ean13></ean13>
        <isbn></isbn>
        <upc></upc>
        <cache_is_pack></cache_is_pack>
        <cache_has_attachments></cache_has_attachments>
        <is_virtual></is_virtual>
        <state></state>
        <on_sale></on_sale>
        <online_only></online_only>
        <ecotax></ecotax>
        <minimal_quantity></minimal_quantity>
        <price>20</price>
        <wholesale_price></wholesale_price>
        <unity></unity>
        <unit_price_ratio></unit_price_ratio>
        <additional_shipping_cost></additional_shipping_cost>
        <customizable></customizable>
        <text_fields></text_fields>
        <uploadable_files></uploadable_files>
        <active></active>
        <redirect_type></redirect_type>
        <id_product_redirected></id_product_redirected>
        <available_for_order></available_for_order>
        <available_date></available_date>
        <show_condition></show_condition>
        <condition></condition>
        <show_price></show_price>
        <indexed></indexed>
        <visibility></visibility>
        <advanced_stock_management></advanced_stock_management>
        <date_add></date_add>
        <date_upd></date_upd>
        <pack_stock_type></pack_stock_type>
        <meta_description>
            <language id="1">meta_description</language>
        </meta_description>
        <meta_keywords>
            <language id="1">meta_keywords</language>
        </meta_keywords>
        <meta_title>
            <language id="1">meta_title</language>
        </meta_title>
        <link_rewrite>
            <language id="1"></language>
        </link_rewrite>
        <name>
            <language id="1">testProductApi2</language>
        </name>
        <description>
            <language id="1">product description</language>
        </description>
        <description_short>
            <language id="1">product short description</language>
        </description_short>
        <available_now>
            <language id="1"></language>
        </available_now>
        <available_later>
            <language id="1"></language>
        </available_later>
        <associations>
            <categories>
                <category>
                    <id></id>
                </category>
            </categories>
            <images>
                <image>
                    <id></id>
                </image>
            </images>
            <combinations>
                <combination>
                    <id></id>
                </combination>
            </combinations>
            <product_option_values>
                <product_option_value>
                    <id></id>
                </product_option_value>
            </product_option_values>
            <product_features>
                <product_feature>
                    <id></id>
                    <id_feature_value></id_feature_value>
                </product_feature>
            </product_features>
            <tags>
                <tag>
                    <id></id>
                </tag>
            </tags>
            <stock_availables>
                <stock_available>
                    <id></id>
                    <id_product_attribute></id_product_attribute>
                </stock_available>
            </stock_availables>
            <accessories>
                <product>
                    <id></id>
                </product>
            </accessories>
            <product_bundle>
                <product>
                    <id></id>
                    <quantity></quantity>
                </product>
            </product_bundle>
        </associations>
    </product>
</prestashop>
`

**Comment by hibatallahAouadni** [comment]
Hello @Jordanmarjot 

The body that you provided it, it's contains only the id_manufacturer :disappointed: i'ts empty!!
Please try with this body, and feedback:

```
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <product>
        <id_category_default>
           <![CDATA[2]]>
        </id_category_default>
        <type>
            <![CDATA[simple]]>
        </type>
        <product_type>
            <![CDATA[standard]]>
        </product_type>
        <id_shop_default><![CDATA[1]]></id_shop_default>
        <reference>
            <![CDATA[ws_test]]>
        </reference>
        <price>
            <![CDATA[25]]>
        </price>
        <active>
            <![CDATA[1]]>
        </active>
        <condition>
            <![CDATA[New]]>
        </condition>
        <name>
            <language id="1">
                <![CDATA[test]]>
            </language>
            <language id="2">
                <![CDATA[test]]>
            </language>
            <language id="3">
               <![CDATA[test]]>
            </language>
            <language id="4">
                <![CDATA[test]]>
            </language>
        </name>
        <description>
            <language id="1">
                <![CDATA[test]]>
            </language>
            <language id="2">
               <![CDATA[test]]>
            </language>
            <language id="3">
                <![CDATA[test]]>
            </language>
            <language id="4">
                <![CDATA[test]]>
            </language>
        </description>
    </product>
</prestashop>
```

Waiting for your feedback.

Thanks!

**Comment by Jordanmarjot** [comment]
Hello, so I test with your body and get the same result 
![image](https://user-images.githubusercontent.com/71250621/168649232-a7fc1162-63b5-44f8-b9e5-e98c3dff5383.png)

**Comment by hibatallahAouadni** [comment]
Hello @Jordanmarjot 

Please try with this simple one: 

```
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <product>
        <id_category_default>2</id_category_default>
        <product_type>standard</product_type>
        <id_shop_default>1</id_shop_default>
        <reference>ws_test</reference>
        <price>25</price>
        <active>1</active>
        <condition>new</condition>
        <name>
            <language id="1">test</language>
        </name>
        <description>
            <language id="1">test</language>
        </description>
    </product>
</prestashop>
```

And here's my result:

![image](https://user-images.githubusercontent.com/23308427/168650427-53069eb6-5f95-435e-b016-2c8b1eabda90.png)

Waiting for your feedback.
Thanks!

**Comment by Jordanmarjot** [comment]
Thanks for the help, but again the same result, I don't understand why when I make the same request as everyone, I didn't get the same result 
![image](https://user-images.githubusercontent.com/71250621/168651450-c42b0e1a-e43d-4f76-aecc-6b45021ef8c9.png)

**Comment by hibatallahAouadni** [comment]
Hello @Jordanmarjot 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a module/configuration problem.

Alternatively, you can ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).
We will close this issue.

Thanks!
