### ISSUE TITLE
Product::getProductProperties tax excl ask for wrong Product::getPriceStatic

### ISSUE THREAD

**Issue by sandra2n** [PrestaShop/PrestaShop#28488]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In product class, function getProductProperties there is a if on self::$_taxCalculationMethod == PS_TAX_EXC that call Product::getPriceStatic, but the $usetax parameter is at true (like in the else of this if) instead of false. 
Because of that the price returned is the price tax incl. instead of tax excl.

### Expected behavior

The $usetax parameter should be false

### Steps to reproduce

1. Go to in classes/Product.php
2. Search function getProductProperties
3. Look for "if (self::$_taxCalculationMethod == PS_TAX_EXC)"
4. In the if, take a look at the call "$row['price'] = Product::getPriceStatic(...)"

### PrestaShop version(s) where the bug happened

1.7.8.5

**Comment by matks** [comment]
Hi ! thank you for the issue but I think I will clear the misunderstanding here 😄

We can see you are reporting a *defect* in class Product

But a defect is not a bug report. What is the impact of this line that is wrong according to you? Can you provide a usecase where, because of this code, the price should be X but is computed Y instead?

Without this information it will be hard to explore this topic

**Comment by sandra2n** [comment]
Hi,

Sorry, but I don't know where it is visible in Prestashop theme. In a theme I use, the search result display products with price, instead of juste the name.
The shop is displaying price tax excl., but in the search result the prices are tax incl..

And as said it come from the fact that the price is asked with tax despite the fact that it is the tax excl. part of the code.

Thanks

**Comment by AureRita** [comment]
Hello @sandra2n 

Thank you for your reporting ! 
Could you please provide a module that use a template of your theme's search to test and reproduce the issue ? 
Or maybe an other way that the parameter $usetax should be false. 
Waiting for your feedback.

Thanks!

**Comment by sandra2n** [comment]
I don't think I understand when $usetax should be true when we are in tax excl. mode?
If I'm wrong sorry, you can ignore the issue.
![screen](https://user-images.githubusercontent.com/24668239/168315776-e75832cf-20df-4fb0-b220-4387c632b7a8.jpg)

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers can someone please try to reproduce the issue, it's too technical for me :pray: 
Thanks in advance!

**Comment by atomiix** [comment]
@sandra2n I think that either case, `$row['price']` will contain the price with taxes and `$row['price_tax_exc']` will contain the price without tax. It seems that it's only a matter of how those prices are calculated.
What you should do if you want to display prices without taxes is to use `$row['price_tax_exc']` I guess.

**Comment by sandra2n** [comment]
@atomiix Thanks, but in that case why is $row['price_without_reduction'] = $row['price_without_reduction_without_tax'] in the case there is no taxes? It should be the same logic with and without reduction.

The price with reduction follow exactly the logic that is missing for price without reduction:
if $_taxCalculationMethod == PS_TAX_EXC, both are without taxes. If $_taxCalculationMethod != PS_TAX_EXC, $row['price_without_reduction'] is with tax and $row['price_without_reduction_without_tax'] is without.

So there seems to be something wrong here in one way or an other.
![screen](https://user-images.githubusercontent.com/24668239/175941600-bb6dc7b5-dad0-4d2a-bbe4-0c1e23905736.jpg)

**Comment by atomiix** [comment]
@sandra2n you've made a point here 😄
But like @matks said, without a proper usecase to be able to reproduce a calculation error, it will be hard to go further.
Do you have a step by step description for us to be able to see what's wrong?

**Comment by sandra2n** [comment]
@atomiix Sorry, I don't. I don't know where it is use on default theme.
