### ISSUE TITLE
No product name in mail (customer_qty.html)

### ISSUE THREAD

**Issue by blawdi** [PrestaShop/PrestaShop#28483]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I no have the name of product in mail 
![c8YiIAZ](https://user-images.githubusercontent.com/27147133/168150347-978a1eb2-b46c-412c-ada1-165aeabb06ac.png)

### Expected behavior

Normally in the mail received, the name of the product must be written. However here there is nothing written, in the Template mail I added "See this product" and in this case you can see the link. (Link that works perfectly) I do not understand why the product name does not appear.

The site is in French

### Steps to reproduce

1. Install module ps_emailalerts
2. activate Product availability
3. in produt out of stock, added ur mail and click on "notify me"
4. added stock for this product
5. wait to receive the email

### PrestaShop version(s) where the bug happened

1.7.6.5

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

ps_emailalerts 2.3.3

**Comment by hibatallahAouadni** [comment]
Hello @blawdi 

I didn't manage to reproduce the issue with PS1778, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/168279885-8bc89439-7ac9-45b4-ad03-e07b39b104fd.png)

It seems the issue has been fixed :tada: 
Closing the issue as it's fixed.

Thanks!
