### ISSUE TITLE
Impossibility to install 1-Click upgrade module

### ISSUE THREAD

**Issue by tiroiretcoton** [PrestaShop/PrestaShop#28497]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I tried to install the "1-Click upgrade" module. When i click on the install button, the install seems to start. But after around 2 seconds, the start stops and the module is not installed.
Can you see what is going on ? How can we have detailed logs on the errors that are occuring on the prestashop interface ?

### Expected behavior

Expected behvior :
- Install is done when install button is clicked

### Steps to reproduce

1. Go to the "module catalog" section
2. Search for "1-Click" in the searchbar and launch the search
3. The module "1-Click Upgrade" is shown
4. Click the install button
5. an error message "L'action install est impossible pour le module autoupgrade.  Impossible de créer le menu AdminSelfupgrade"

### PrestaShop version(s) where the bug happened

1.7.5.1

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

1-Click upgrade

**Comment by hibatallahAouadni** [comment]
Hello @tiroiretcoton 

Could you please provide the 1-Click autoupgrade module version 🙏 
Waiting for your feedback.

Thanks!

**Comment by AureRita** [comment]
Hi @tiroiretcoton ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thanks
