### ISSUE TITLE
FO - the search_bar module is not well displayed

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#28492]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I do an upgrade from the version 1.7.7.8 to the version 1.7.8.6 with the autoupgrade module v 4.14.0, after that, my searchbar have scrollbar on it, you can see it on this video

https://user-images.githubusercontent.com/100699445/168284621-3086ac54-6521-43a0-a53e-7ebb3c453a18.mp4

at the end of the video, we can see the search_bar module update fail on the autoupgrade, but the module is "correctly" update (from 2.0.2 to 2.1.3) 

----------------------

That's what we have on a mac, with an update from 1.7.4.2 to 1.7.8.6 with autoupgrade v 4.14.1 : 
![search-1786-upgradefrom-1742-mobile](https://user-images.githubusercontent.com/100699445/168286477-f2be575f-a1c3-4ebf-9420-7e989990a6b9.png)

--------------------
Tha are differences seen on the inspector 
![searchcss2-1786-noupgrade-mobile](https://user-images.githubusercontent.com/100699445/168286910-f998bc3c-f539-43f0-befd-579dfdd3d1a7.png)

![searchcss2-1786-upgradefrom-1742-mobile](https://user-images.githubusercontent.com/100699445/168286933-3dfe3079-e57a-45d8-951c-b836694fefad.png)

--------------------------
![searchcss-1786-noupgrade-desktop](https://user-images.githubusercontent.com/100699445/168286977-7ef676ee-4599-4949-8dd8-78e41914fa77.png)

![searchcss-1786-upgradefrom-1742-desktop](https://user-images.githubusercontent.com/100699445/168287015-36d06a9a-e4df-45a2-8e24-a1168d62ccdb.png)

---------------------------
![searchtpl-1786-notupgrade](https://user-images.githubusercontent.com/100699445/168287064-85f6f96e-f99b-470f-96b9-6e84fd5e0ce1.png)

![searchtpl-1786-upgradefrom-1742](https://user-images.githubusercontent.com/100699445/168287080-5630897d-3de7-42bf-9e45-fae7650ce69d.png)

----------------------
It's maybe because of this line on ps_searchbar v2.1.3 : 
https://github.com/PrestaShop/ps_searchbar/blob/dev/ps_searchbar.php#L59

it maybe check the previous version during the autoupgrade so it do some problem 

We had a similar issue before : https://github.com/PrestaShop/PrestaShop/issues/25594  

### Expected behavior

I expected a search bar like this : 
![search-1786-notupgrade-desktop](https://user-images.githubusercontent.com/100699445/168286003-b44b2390-abd1-45f9-bccc-eabf54a25923.png)

### Steps to reproduce

1. Do a fresh install of Prestashop 1.7.7.8 
2. Make an upgrade to 1.7.8.6 
3. Go to FO -> See error 

---------------
1. Do a fresh install of Prestashop 1.7.4.2
2. Go to Shop Parameters > General > Enable Multishop
3. Go to Advanced Parameters > Multishop > Create another shop
4. Install autoupgrade v 4.14.1 
5. Make an upgrade to 1.7.8.6 
6. Go to FO -> See error 

### PrestaShop version(s) where the bug happened

1.7.4.2 - 1.7.7.8 -> 1.7.8.6

### PHP version(s) where the bug happened

7.4 (for 1.7.7.8) - 7.2 (for 1.7.4.2)

### If your bug is related to a module, specify its name and its version

ps_searchbar 2.1.3 autoupgrade 4.14.0

**Comment by huyhoang8398** [comment]
Im still having this issue after upgrade to Prestashop version 1.7.8.8

**Comment by RosaBenouamer** [comment]
@AureRita : it's seems to be similar to https://github.com/PrestaShop/PrestaShop/issues/29090 even if not the same ps_*
