### ISSUE TITLE
An exception is thrown in Order page when the assigned status is deleted

### ISSUE THREAD

**Issue by fiorame** [PrestaShop/PrestaShop#28496]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello.
- I create a new Status.
- I assign the new Status to an order.
- I delete the new Status.
- Now the order is not available and return this error:

Type error: Argument 3 passed to PrestaShop\PrestaShop\Core\Domain\Order\QueryResult\OrderStatusForViewing::__construct() must be of the type string, null given, called in /home2/lfioramv/public_html/src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php on line 363
[Symfony\Component\Debug\Exception\FatalThrowableError 0]

- If I change in PHPMyAdmin >> order_history >> id_order_state the number of deleted Status with a existing status teh order became available.

Regards.

Antonio

### Steps to reproduce

- I create a new Status.
- I assign the new Status to an order.
- I delete the new Status.
- Now the order is not available and return this error:

Type error: Argument 3 passed to PrestaShop\PrestaShop\Core\Domain\Order\QueryResult\OrderStatusForViewing::__construct() must be of the type string, null given, called in /home2/lfioramv/public_html/src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php on line 363
[Symfony\Component\Debug\Exception\FatalThrowableError 0]

- If I change in PHPMyAdmin >> order_history >> id_order_state the number of deleted Status with a existing status teh order became available.

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.3.33

**Comment by hibatallahAouadni** [comment]
Hello @fiorame 

Could you please check this issue #23379 cause it seems similar to yours.
Please check and feedback.

Thanks!

**Comment by fiorame** [comment]
Hello,

I checked the issue 23379 but it is different.I can delete the Status without problems.

Best regards.

**Comment by florine2623** [comment]
Hello @fiorame ,

I can't reproduce your issue on branch 1.7.8.x as you can see from my screen record :

https://user-images.githubusercontent.com/16019289/168858309-a486ed88-bac5-4744-ab86-538cfa02e205.mov

The status becomes "status (deleted)" and my order is still displayed.
So I will close your issue.

**Comment by fiorame** [comment]
Hello.
I see your screenshot and it is the same I do that give me error. 
I will try again and if I find some other details I will open a new issue.

Thanks
