### ISSUE TITLE
Configure button leads to a 500 error

### ISSUE THREAD

**Issue by tiroiretcoton** [PrestaShop/PrestaShop#28498]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I'm trying to configure my prestshop website through the prestashop interface and I have a lot of strange behaviors : when i try to hit the "Configure" button on a module i have an error message whatever the module.

"
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
"

### Expected behavior

The configuration screen is opened

### Steps to reproduce

1. Go to the module management screen
2. Clic on Configure on the module "Menu principal"
3. the following message is shown :
"
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
"

### PrestaShop version(s) where the bug happened

1.7.5.1

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment]
Hello @tiroiretcoton 

I didn't manage to repduce the issue, see the attached screen record below:

![issue_28498](https://user-images.githubusercontent.com/23308427/168579302-7dd141d4-771d-4e2f-98cb-bcf55f2edfec.gif)

Could you please provide the mainmenu module version.
Please check and feedback.

Thanks!

**Comment by tiroiretcoton** [comment]
Hello,

the version of the main page module is 2.3.1.

the problem is still on going on my side

**Comment by PrestaEdit** [comment]
Hi @tiroiretcoton , 

Could you enable the debug more in order to have the details of the error 500, it will be usefull to see what happen.

**Comment by hibatallahAouadni** [comment]
Hello @tiroiretcoton 

As @PrestaEdit asked, could you please enable the debug mode and provide a screenshot :pray: 
Waiting for your feedback.

PS: @PrestaEdit thanks for your quick reply :superhero: 

Thanks!

**Comment by tiroiretcoton** [comment]
Hello,

I'm sorry too say tha the debug button doesnt work neither.
I have the same 500 error when clicking on it.

Is it possible to manage to share screens while i show you what happened ?

Johan

**Comment by HanaRebaiQA** [comment]
Hello @tiroiretcoton 

I was unable to reproduce your issue with PS1786. 
Maybe it's related to the PrestaSHop version that you used, it's not compatible with the modules versions OR with php versions (Specially that with debug mode, you have this error)



Despite our efforts, we were not able to reproduce your issue with the provided information. 
It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
We will close this issue.

Do not hesitate to open new tickets when needed.

https://user-images.githubusercontent.com/92912932/169838735-9441b4e8-36fa-42c7-b40b-efeca91de013.mp4


Thank you!

**Comment by tiroiretcoton** [comment]
Hello,

the problem is still pending on my side.
is it possible for you to check the logs of prestashop for my prestashop page ?

I need to understand what is going on when i click on the debug button.

Here is what i do on my page :

Opening of the screen of the performances to activate the debug mode :
![image](https://user-images.githubusercontent.com/105629313/179773290-791a2e9a-e9eb-4ef0-afff-9f5eebe53455.png)

Clic on the yes button of the debog property :
![image](https://user-images.githubusercontent.com/105629313/179773430-bce12cf0-551a-4f01-8996-b49961c55445.png)

Clic on the save button => 500 error
![image](https://user-images.githubusercontent.com/105629313/179773475-da5acfcb-0dc2-4a21-889d-8d6dd6e8a5b6.png)

Johan

**Comment by hrhmundra** [comment]
Hello 
I am also facing the same issue in prestashop 8.0.2

Could anyone please help ?

Thanks
