### ISSUE TITLE
BO - Order - Bad display of status in the order page 

### ISSUE THREAD

**Issue by marwachelly** [PrestaShop/PrestaShop#28494]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Bad display of status in the order page.
Develop:

https://user-images.githubusercontent.com/89604350/168549851-d3752216-6681-4b45-bab5-e9b7ebad5af6.mp4

### Expected behavior

1.7.8.6:

https://user-images.githubusercontent.com/89604350/168322936-d95149a9-f448-45fa-9ea3-2cf88334665d.mp4

_No response_

### Steps to reproduce

1. Go to BO > Order page 
2. View an order
3. Try to update status
4. see error

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.0

**Comment by marwachelly** [comment]
It could be related to https://github.com/PrestaShop/PrestaShop/pull/28066

**Comment by MeKeyCool** [comment]
I take this one ^^

If I understand well, it is just about display, isn't it ?

**Comment by marwachelly** [comment]
> I take this one ^^
> 
> If I understand well, it is just about display, isn't it ?

Yes it is about the display of the drop down of the order status.

**Comment by MeKeyCool** [comment]
@MatShir , I am not sure anymore. 
If I remember well last discussion we had, you said that the select2 box should have a `min-width` evaluated to some "standard text size" we use but I am not sure if you should come back with clear answer / specs or if I should notice what we said and implement it directly ^^'
Did we speak about a max-width as well ? :thinking: 

Sorry I shouldn't let time flow after our discussion without commenting and keeping track on discussion ^^'

**Comment by khouloudbelguith** [comment]
Duplicate of #28405
