### ISSUE TITLE
Discount cart rule not working

### ISSUE THREAD

**Issue by GladysBecerra** [PrestaShop/PrestaShop#28508]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I have setup a promo code compatible with all my shop's products, except two: Brunch, and Brunch + SPA. When one of these products is selected individually, the rule is correctly applied. But, if I add to the shopping cart this product + any product compatible with the promo code and enter the promo code, it is applied to the whole cart, including the Brunch or Brunch + SPA, which is not what is setup in the promo code rules. 
![Uploading promo code issue.jpg…]()

### Expected behavior

When combining Brunch or Brunch + SPA with any other products and applying the RESCAN promocode, the 15% of this code should only be applied to all the products **except** Brunch or Brunch + SPA.

### Steps to reproduce

1. Go to https://aquaplusspa.com/index.php?id_product=64&rewrite=brunch&controller=product&id_lang=2
2.  Click on "Add to cart"
3. Go to any other product (example: https://aquaplusspa.com/index.php?id_product=38&id_product_attribute=32&rewrite=masaje-descontracturante&controller=product&id_lang=2#/19-tiempo-25_min)
4. Click on "Add to cart"
5. Enter the promocode RESCAN. 

You will see that the 15% discount of this code is applied to the total amount of the cart, when it should exclude the amount of the "Brunch" or "Brunch + SPA" products.

### PrestaShop version(s) where the bug happened

1.7.6.2

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment]
Hello @GladysBecerra 

Could you please check this issue #17603 cause it seems similar to yours.
Waiting for your feedback.

Thanks!

**Comment by AureRita** [comment]
Hi @GladysBecerra  ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thanks
