### ISSUE TITLE
attributes-list does not show values.

### ISSUE THREAD

**Issue by qualityangel** [PrestaShop/PrestaShop#28501]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When i go to the combination page of a product, there is no list of attributes on the right and the ellement show up empty:

<div id="attributes-list" class="col-md-3">
      </div>

I'm in multistore mode

### Expected behavior

Showing a list for sellecting attributes on the combination page

### Steps to reproduce

1. Go to product and select combination tab
2. See on the right screen a empty space
3. You can add single combinations by type a color in the field on the right, so they exist.

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by qualityangel** [comment]
A screenshot of the combination page, Debbuging mode is not given anything.
![screen1](https://user-images.githubusercontent.com/47004184/168575571-67c6e98c-eb4a-44d5-84fc-f69ef44634ba.jpg)

**Comment by hibatallahAouadni** [comment]
Hello @qualityangel 

I didn't manage to reproduce the issue with PS1785, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/168602953-0928dc95-177c-4748-b63f-3e2943682883.mp4

Are you sure that you have some attributes saved in your shop?
Could you please provide a screenshot of BO>SELL>Catalog>Attributes&Features :pray: 

![image](https://user-images.githubusercontent.com/23308427/168603248-6343d91c-925d-46ec-974e-1ec3f3962547.png)

Waiting for your feedback.
Thanks!

**Comment by qualityangel** [comment]
Well, i  have the problem ;)
Yes as i sead, when you type a color in the combine serval attributes field then you kan select it. But only the attributes-list on the right is empty, also you can see that with inspecting on chrome, The div attributes-list is empty

![screen2](https://user-images.githubusercontent.com/47004184/168609161-7190c541-c117-40fb-b6c1-48585439ae54.jpg)

**Comment by qualityangel** [comment]
A found a old topic that is exacly what im on:
https://www.prestashop.com/forums/topic/599269-attributes-list-missing/

Solution is not working.

**Comment by hibatallahAouadni** [comment]
Hello @qualityangel 

Could you please check your browser console and see if there's any error displayed. 
If so, please provide a screenshot about it.

Thanks in advance!

**Comment by qualityangel** [comment]
I check it within 1 hour.

**Comment by qualityangel** [comment]
I have one Error in Google Console: 

Uncaught SyntaxError: Identifier 'moduleCardController' has already been declared (at module_card.js?1.7.8.5:1:1)

**Comment by qualityangel** [comment]
OK i see that the colorpicker is not available anymore in admin/themes/new-theme/ These is also not available in a fresh downloaded zip from the prestashop website:

https://dthomeshopping.nl/backoffice/themes/new-theme/public/bootstrap-colorpicker.min.css.map niet laden: HTTP-fout: statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Downloaded the file elseware, but is not solving the issue.

Got another deprication warning in console:

'Event.path' is deprecated and will be removed in M109, around January 2023. Please use 'Event.composedPath()' instead. See https://www.chromestatus.com/feature/5726124632965120 for more details.

**Comment by florine2623** [comment]
Is it the same issue as https://github.com/PrestaShop/PrestaShop/issues/9627 ?

**Comment by qualityangel** [comment]
Hi Florine,

Well i only have Dutch lang, no other lang installed.
The DIV object for the attributes is empty in product page as in the inspection from google.

Uninstalled all 3th party modules, cleared cache etc. no change.

I did a clean install on the same server with another domain, and can't reproduce it.

**Comment by hibatallahAouadni** [comment]
Hello @qualityangel 

> I did a clean install on the same server with another domain, and can't reproduce it.

Means that it's due to your overrides, so it's not related to PS Core!

Closing the issue as we only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you
