### ISSUE TITLE
Improvement Feature Flag: Product Page V2 for the 8.0

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#28505]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

As a merchant, I want to be able to switch to the new product page and switch back if I'm not satisfied.

### Describe the solution you'd like

Rename the page 'Experimental Features' to 'New & Experimental Features'.

#### New feature Form

WHEN the shop has Multistore feature enabled:
THEN the product page - Single store feature flag is disabled and the input is disabled. The user can't change the flag.

WHEN the product page - Single store feature flag is disabled:
THEN the product page V2 is hidden and the legacy product page is displayed.
All the button to access the product page V2 are removed:
- Remove the link in the catalog section in the menu
- Remove button to open 'List on experimental page' and 'New product on experimental page' from the product list
- Remove button to open 'New product on experimental page' and  'Edit on experimental page' from the product edition page
The New Product button opens the legacy product page.

WHEN the product page - Single store feature flag is enabled:
THEN the legacy product page is hidden and the product page V2 is displayed.
All the button to access the legacy product page are removed:
- Remove the link in the catalog section in the menu
- Remove button to open 'Back to standard page' and 'New product on experimental page' from the product list
- Remove button to open 'Back to standard page' and 'New product on experimental page' from the product edition page
- Remove the information message 'This is an experimental feature'
The New Product button opens the product page V2.

By default, the feature flag  the product page - Single store is disabled

When I upgrade my shop, 
The product page - Single store flag is disabled.
The product page - Multistore flag is disabled.

#### Experimental feature form

WHEN the shop has Multistore feature enabled:
THEN  the product page - Multistore feature flag's input is enabled. The user can change the flag.

By default, the product page - Multistore feature flag is disabled.

WHEN the product page - Multistore feature flag is disabled:
THEN the product page V2 is hidden and the legacy product page is displayed.
All the button to access the product page V2 are removed:
- Remove the link in the catalog section in the menu
- Remove button to open 'List on experimental page' and 'New product on experimental page' from the product list
- Remove the link option to edit 'Edit product on experimental page' in the action button in the product list 
- Remove button to open 'New product on experimental page' and  'Edit on experimental page' from the product edition page
The New Product button opens the legacy product page.

WHEN the product page - Multistore feature flag is enabled:
THEN the legacy product page is hidden and the product page V2 is displayed.
All the button to access the legacy product page are removed:
- Remove the link in the catalog section in the menu
- Remove button to open 'Back to standard page' and 'New product on experimental page' from the product list
- Remove the link option to edit 'Edit product on experimental page' in the action button in the product list 
- Remove button to open 'Back to standard page' and 'New product on experimental page' from the product edition page
- **Keep the information message 'This is an experimental feature'**
The New Product button opens the product page V2.

The confirmation modal is only displayed for Experimental Feature.

### Design

![image (4)](https://user-images.githubusercontent.com/43613217/169829399-d89bd8ad-7daa-4f17-80b3-322c2423a238.png)

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by MatShir** [comment]
Should we change the wording 'Experimental' ? 

See with @jolelievre, If we can use the product V2 as the default page in single shop only ? 🤔

**Comment by kpodemski** [comment]
I highly suggest keeping v2 behind the feature flag; otherwise, it will be a communication disaster for everyone involved in the project and unexpected behavior for the merchant. There's also a risk that the legacy page might work slightly different now with all the codebase changes.

And these warnings like...
> **if you enable multi-store, then you'll _this and that_**

> Should we change the wording 'Experimental' ?

"Feature previews"?

**Comment by matks** [comment]
> I highly suggest keeping v2 behind the feature flag; otherwise, it will be a communication disaster for everyone involved in the project and unexpected behavior for the merchant.

This project will be treated like any other project, meaning it will undergo the deep testing of the QA team 👀  and if the QA team considers this does not meet the quality criteria for launch it will not launch.

Is this enough to reassure you ? 😄

**Comment by Hlavtox** [comment]
I vote for launching it when it's ready and fully finished. 👍

**Comment by Julievrz** [comment]
> Should we change the wording 'Experimental' ?
> 
> See with @jolelievre, If we can use the product V2 as the default page in single shop only ? 🤔

IMO, if it's enabled from the Feature Flag page it is still considered an experimental feature, isn't it?

**Comment by Julievrz** [comment]
> I highly suggest keeping v2 behind the feature flag; otherwise, it will be a communication disaster for everyone involved in the project and unexpected behavior for the merchant. There's also a risk that the legacy page might work slightly different now with all the codebase changes.
> 
> And these warnings like...
> 
> > **if you enable multi-store, then you'll _this and that_**
> 
> > Should we change the wording 'Experimental' ?
> 
> "Feature previews"?

"Feature previews" sounds good in English but it's really hard to translate... I couldn't think of a good French translation.

I thought of "Beta features" but it's not really relevant.

But I'm wondering: why would the product page appear on the "Preview feature/Experimental feature/..." if it has been fully tested by QA and is stable? In this case, it's just a new feature... only available in a single-store context.
I'm not sure changing the wording will be the only answer to the issue here. 😅

**Comment by jolelievre** [comment]
I agree with @Julievrz if it's stable enough it shouldn't be handled via a feature flag which is dedicated to experimental features. Which is why I suggested using a configuration in the Product settings instead, this would look less experimental.

**Comment by Julievrz** [comment]
> I agree with @Julievrz if it's stable enough it shouldn't be handled via a feature flag which is dedicated to experimental features. Which is why I suggested using a configuration in the Product settings instead, this would look less experimental.

What could be nice is having a message on the legacy page saying something like "A new version of this page is available" redirecting to the right page to enable it, if it cannot be done on the same page.

**Comment by jolelievre** [comment]
> What could be nice is having a message on the legacy page saying something like "A new version of this page is available" redirecting to the right page to enable it, if it cannot be done on the same page.

yeah we thought about this as well

**Comment by MatShir** [comment]
The new wording are updated in the mockups.
Feature preview is very hard to translate, but a good idea.
The feature flag in the product setting can be quite tricky since it really concerns the product setup and not the configuration of your BO.
So, @Julievrz and I propose to keep in the Experimental Page but to distinguish the feature ready to use and the one that are still under dev or test.

**Comment by khouloudbelguith** [comment]
Hello :slightly_smiling_face: 

We can close this issue when this PR is merged https://github.com/PrestaShop/autoupgrade/pull/489#pullrequestreview-995243461

Thanks!
