### ISSUE TITLE
cannot register to metrics

### ISSUE THREAD

**Issue by jovh** [PrestaShop/PrestaShop#28518]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

after filling out all data in the registration form for metrics - i get a message saying : billing address is not valid - but the message doesn t say 'what' is invalid because i tried to change everything without succes :-(
<img width="814" alt="Screenshot 2022-05-17 at 20 29 50" src="https://user-images.githubusercontent.com/60877315/168885645-141bbca5-e119-46b7-83b3-3ad479e7288c.png">

### Expected behavior

i expect at least a message that says 'what' is wrong - not 'that' somethings is wrong that is sooo old school ;-)

### Steps to reproduce

go to dashboard
click on metrics and 'stats' and when you don t have an account register...

### PrestaShop version(s) where the bug happened

1.7.8.4

### PHP version(s) where the bug happened

oops don t know

**Comment by matks** [comment]
Hello ! ps_metrics is not a module provided by PrestaShop company, not PrestaShop open source project so we cannot help you

You can report it to the PS Metrics team using the "Help" tab in the module I believe

**Comment by jovh** [comment]
ok - is there a prestashop company module for stats ?

**Comment by hibatallahAouadni** [comment]
Hello @jovh 

It seems that your issue is not a PrestaShop core bug.
If your module is Metrics Official, please contact support team on Addons

We will close this issue.

PS: thanks @matks for your quick reply :rocket: 

Thanks!
