### ISSUE TITLE
 Invoice address reset when use "use different addresses for invoice"

### ISSUE THREAD

**Issue by kratekk** [PrestaShop/PrestaShop#28511]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Stepping on checkout process prestashop reset the invoice address and overwrites it by delivery address.

### Expected behavior

I'm expect to set invoice address in first worflow of checkout process, unchecking "use the same address for invoice"

### Steps to reproduce

The issue is in checkout.

    Fill personal information.
    Fill delivery addresses information ( you have to uncheck "use same addresses for invoice")
    Fill invoice addresses information.
    Now tou will be redirected to first step (this is the bug because I should go to delivery step)
    When I click "Continue" I go to second step (addresses) and Invoice address is the same as delivery address but I filled out different

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.2

**Comment by florine2623** [comment]
Hello @kratekk ,

I can't reproduce the issue.
I have tested on 1.7.8.6 and 8.0.0. I don't have the same result as you can see form my screen record :

https://user-images.githubusercontent.com/16019289/168765198-6be21721-a01d-4ce5-9f08-2c22370376fe.mov

I'm not redirect to the 1st step, but directly to the 3rd step shipping method.

I will close your issue as I can't reproduce it.
Thanks!
