### ISSUE TITLE
ps_shoppingcart.tpl : Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by dobra947** [PrestaShop/PrestaShop#28516]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Error in template on line 34:
````
   {foreach from=$cart.subtotals item="subtotal"}
          <div class="{$subtotal.type}">
            <span class="label">{$subtotal.label}</span>
            <span class="value">{$subtotal.amount}</span>
          </div>
        {/foreach}
````

### Steps to reproduce

1. Add product to cart with the module installed and registerred in hooktop

### PrestaShop version(s) where the bug happened

1.7.8.4

### If your bug is related to a module, specify its name and its version

2.0.5

**Comment by PrestaEdit** [comment]
Fixed here : https://github.com/PrestaShop/ps_shoppingcart/commit/5f509d300484a4c5af4488eaa34d503f3a628a71

**Comment by florine2623** [comment]
Fixed in this PR : https://github.com/PrestaShop/ps_shoppingcart/pull/83
