### ISSUE TITLE
Multiple product order with multiple carriers

### ISSUE THREAD

**Issue by zenerry** [PrestaShop/PrestaShop#28529]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi folks,
I've searched for an issue thnat I think it needs to be polished in the front office of the checkout page.

I've searched in all open issues, and there are a lot talking something similar but not exactly, as far as I can understand.

If you buy 2 products that have different carriers attached to the product, and go to the checkout page, the amount charged for the  transport is correct (the sum of those two carriers) but you can't see the details for each one. For exemple, if they have different delivery time.
It should be good to see them separetly, or delivery details for each one, at least.

Thanks.

### Expected behavior

It should be good to see them separetly, or delivery details for each one, at least.

### Steps to reproduce

Attach one product to 1 specific carrier (with cost, not free).
Attach another product to another specific carrier (with cost, not free).
Go and add them both to your cart and go to checkout.
As you are filling the adress info, you'll see the the box for the cost of the transport with sum of those two costs, but not any detail.

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Hello @zenerry 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #15369. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #15369
