### ISSUE TITLE
Attribute_wholesale_price is rounded when do multiple save

### ISSUE THREAD

**Issue by Lionel-dev** [PrestaShop/PrestaShop#28538]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I save a wholesale price on a combination, it is saved: 

![image](https://user-images.githubusercontent.com/48990561/169308872-50d0dde2-c4ac-4c69-86f5-c5a3ccc22f79.png)

If I decide to save on this page or on any other page of the product and I refresh this page, the wholesale price has no more decimals.

![image](https://user-images.githubusercontent.com/48990561/169309348-187ca5d1-42dc-46af-8dc3-f90166d3211e.png)

### Expected behavior

Normally, the wholesale  price should keep its decimal point no matter how many times I save this page.

### Steps to reproduce

1. Go to a product with combinations.
2. Modify a combination by inserting a wholesale price with decimals. Example : 3.96582
3. Save
4. Refresh (ctrl+f5)
5.  Go to the combination panel and/or to the combination 
6.  Re-save the product
7. Refresh (ctrl+f5)
8. The price has lost its decimals

### PrestaShop version(s) where the bug happened

1.7.7.8

### PHP version(s) where the bug happened

7.1

**Comment by hibatallahAouadni** [comment]
Hello @Lionel-dev 

I didn't manage to reproduce the issue with PS1777 and PS1786, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/169352969-dada7ffd-b39a-4911-b098-8039872cbb31.mp4

Please check and feedback.
Thanks!

**Comment by Lionel-dev** [comment]
Hi @hibatallahAouadni,

The problem refers to the wholesale_price, so it is the Cost price field in BO :) 

On closer inspection, I think it's because when defining the field, the format uses a "." for the decimals and after that, this number is formatted with a comma.

**Comment by hibatallahAouadni** [comment]
Hello @Lionel-dev 

Even with a comma or point, the cost price is always well saved, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/169499410-61f3f858-a0e1-48c2-b51e-140dd16ce8e1.mp4

Closing the issue as it's not a Core bug.

Thanks!

**Comment by Lionel-dev** [comment]
@hibatallahAouadni  Please pay more attention to my request before closing it, this is a core bug that is present on my basic shop.

Your PrestaShop is set on the English language, so all your prices are formatted with a dot... In my case, my store is set on France and so when I modify it, I have a dot to separate the decimals from the units, but after refreshing the dot turns into a comma and so PrestaShop will save the value.

I think you didn't see this problem because you are testing with an English version of PrestaShop, and so your prices always have a point to separate the decimals from the units. This is not the case for the French version.  As you can see on my screenshot, the commas were not put by me, but by the system.

**Comment by hibatallahAouadni** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/9972#issuecomment-415217177

**Comment by pardebits** [comment]
> [Lionel-dev](/Lionel-dev)

Hi! I have the same problema that [Lionel-dev].

Do you fix it?? I have spanish language/store and the version is: 1.7.8.5

**Comment by pardebits** [comment]
> Duplicate of [#9972 (comment)](https://github.com/PrestaShop/PrestaShop/issues/9972#issuecomment-415217177)

And is not a duplicate of this topic that you said... Is a complete different bug.

**Comment by Lionel-dev** [comment]
@pardebits yes, I did a quick fix that must not be the cleanest, but my customers needed it... 

I have a lot of maintenance to do this morning, but as soon as I can, I'll read my fix again and share it with you :)

**Comment by pardebits** [comment]
> @pardebits yes, I did a quick fix that must not be the cleanest, but my customers needed it...
> 
> I have a lot of maintenance to do this morning, but as soon as I can, I'll read my fix again and share it with you :)

Thaaaanks a lot!! Im waiting for your news. Thanks again.

**Comment by Lionel-dev** [comment]
So, my patch is a little dated, but here is what I did: 

I went into AdminModelAdapter.php

After the next part: 
```
$form_data['combinations'][$k]['attribute_unity'] = abs(
                $this->floatParser->fromString($combination['attribute_unity'])
            );
```

I added the following part:

```
$form_data['combinations'][$k]['attribute_wholesale_price'] = abs(
                $this->floatParser->fromString($combination['attribute_wholesale_price'])
);
```

@pardebits Hopefully this will solve your problem, if not, I can look into my other projects !
@hibatallahAouadni Does this patch seem relevant to you? If so, I can make a pull request.

**Comment by pardebits** [comment]
Hi thanks! Is not possible to add in a override file?

**Comment by Lionel-dev** [comment]
The problem is that the file is in the src/PrestaShopBundle, I don't know a way to override this...

I thought that since it's a PrestaShop core issue, and it was going to patch by PrestaShop, when upgrading, it was not a big deal to lose it, since it's supposed to be fixed :)

**Comment by pardebits** [comment]
Thanks again! The code works good I think! 
The problem is that they don't think that the problem is a core issue..

Anyway, thanks a lot!

**Comment by Lionel-dev** [comment]
@pardebits Ah! I'm glad this solves your problem :)!

I'll try to raise this point directly with one of their devs via the company I work for. I'll keep you posted

**Comment by pardebits** [comment]
Thanks! Will be good if they can fix this in the future. Thanks again for your time!

**Comment by idnovate** [comment]
I can not reproduce this issue in PS 8.0.1.
