### ISSUE TITLE
Impossible to regenerate images produced in high definition

### ISSUE THREAD

**Issue by w-jerome** [PrestaShop/PrestaShop#28534]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I want to regenerate my thumbnails, but it doesn't do it on the images created in `2x` (`PS_HIGHT_DPI`). Looking at the code, I could see that the `_regenerateNewImages` function does not regenerate them if they still exist. So I went to the `_deleteOldImages` function and I could see that the `Regex` does not take into account `2x` files.

### Expected behavior

I would like that when I click on `Regenerate Thumbnails`, it also does it for high DPI images.

### Steps to reproduce

1. Go to `BackOffice > Design > Images`
2. Scroll down to `Image generation options`
2. Click on `Generate high definition images`
2. Scroll down to `Regenerate thumbnails`
3. Click on `Regenerate thumbnails`
4. Notice in the `/img/p/` folders that the images named `…2x.jpg` are not regenerated

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment]
Hello @w-jerome 

I didn't manage to reproduce the issue with PS1786 and develop :disappointed: 
Could you please provide a screenshot of **Image Settings > Images generation options** or a screen record :pray: 
Waiting for your feedback.

Thanks!

**Comment by w-jerome** [comment]
Hello @hibatallahAouadni  ! And thanks for the quick response :)

And here is a video capture, you can see that when we add an image for the first time, it is well created in `32-home_default2x.jpg`, because of variable `PS_HIGHT_DPI`, but when we change the settings of the thumbnail and regenerate them, it doesn't delete the images in `32-home_default2x.jpg` and so it doesn't modify it.

https://user-images.githubusercontent.com/1685550/169491762-6eceb46b-9a45-4471-bd36-994e2842f98b.mp4

**Comment by hibatallahAouadni** [comment]
Hello @w-jerome 

Before re-generating the images, you need to disable this option to delete the images in `32-home_default2x.jpg`:

![image](https://user-images.githubusercontent.com/23308427/169503748-7eaef164-7109-4e17-9afb-b28878b97966.png)

Please try it again and feedback.
Thanks!

**Comment by w-jerome** [comment]
So I was able to do the procedure you indicated and it doesn't work.

https://user-images.githubusercontent.com/1685550/169529357-04d1fd7a-3f5a-475e-9a79-b29fcf3dcb13.mp4

If I ever proposed a pull request
https://github.com/PrestaShop/PrestaShop/pull/28535

**Comment by hibatallahAouadni** [comment]
Hello @w-jerome 

I see what you mean now, and I think your issue is related/similar to this one #18867
Could you please confirm :pray: Waiting for your feedback.

PS: Check the [specs](https://github.com/PrestaShop/prestashop-specs/blob/master/content/1.7/back-office/design/image-settings/generation-options.md).

Thanks!

**Comment by w-jerome** [comment]
Hello @hibatallahAouadni!

So no it's not the same thing. The problem with issue #18867 is that it has a problem in FO when it removes the `home_default` image type.

My problem is when I want to regenerate the `home_default` images in hight DPI.

Thanks!

**Comment by HanaRebaiQA** [comment]
Hello @w-jerome 

Is your issue similar to this one  [#19798](https://github.com/PrestaShop/PrestaShop/issues/19798) ?

Thanks!

**Comment by w-jerome** [comment]
Hello @HanaRebaiQA 

So it's not the same thing at all.

The problem with #19798 is that the `ImageRetriever` class regenerates the images dynamically in the folder, when you visit a product page in the front-office (this is an example) and they were not present.

My problem is that when I want to regenerate the `home_default` images in high definition from the back-office from the `Design > Images` page.

But you just pointed out another bug. If you go to the back-office of a product sheet and delete an image from the gallery (in ajax), the function does not delete the high definition images.

Example

https://user-images.githubusercontent.com/1685550/169834847-47cadf14-a910-4317-860d-39e9e9b2a334.mp4

I looked at the bug and I could propose a correction which is in this MR

https://user-images.githubusercontent.com/1685550/169835054-d6817904-e207-416d-b585-9e955a743dab.mp4

**Comment by HanaRebaiQA** [comment]
Hello @w-jerome 

I tried to reproduce your issue on PS1786 using the same steps and i was unable to reproduce it.
The image named with `…2x.jpg `is well regenerated in FO.


https://user-images.githubusercontent.com/92912932/169872777-dc65ad32-cd6c-4ee9-b8c1-82284167b475.mp4


Did i miss something ?

Thank you!

**Comment by w-jerome** [comment]
Hello @HanaRebaiQA 

You didn't follow the same procedure I did. You uploaded a `2x` image yourself, but it's up to Prestashop to create it in `2x`, not to the user.

Moreover you click on `Regenerate` the thumbnail without changing its size in `Design > Image types > home_default > Edit` so you can't see if the changes have been taken into account. And by the way you are not looking in the right place, you are regenerating the `home_default` thumbnails but in FO you are checking the `wide_default`.

I wrote how to reproduce the bug in the description of this `issue`, I also made a video capture, you can refer to what I said above ?

**Comment by hibatallahAouadni** [comment]
Hello @w-jerome 

I see what you mean, but unfortunally, there's nothing in the specs explaining the expected behavior while executing this option **Erase previous images**, the only info that I found is in the Help modal in this page:

> **Generate high-resolution images.** The most recent screens with high pixel density (Retina and similar technologies) require high-resolution images. You can enable this feature to make sure your images will display correctly on this kind of screens. It will generate a new file for each of your images, with a resolution twice higher. This will double your number of image files, so use it wisely if you have limited storage space.

Ping @PrestaShop/product-team if we enable this option **Erase previous images**, will the system delete all the images or only the ones that will be generated? and can someone please complete this [SPEC](https://github.com/PrestaShop/prestashop-specs/blob/master/content/1.7/back-office/design/image-settings/generation-options.md#regenerate-thumbnails) :pray: 

Thanks in advance!

**Comment by w-jerome** [comment]
In fact, the images in `...2x.jpg` are also generated. I have a doubt that it is a specification not to delete `...2x.jpg` images, I guess it's more a bug.

**Comment by eshraw** [comment]
Hello @w-jerome, thank you for opening this issue.

To provide follow-up on @hibatallahAouadni 's question : the spec mentions erasing selected images, so every image from a selected category should be deleted and re-generated. If images `...2x.jpg` are re-generated, they should also be deleted.
It indeed looks more like a bug than a need spec to me.

**Comment by w-jerome** [comment]
It's noted @eshraw , so I proposed a pull-request which should correct the problem.
