### ISSUE TITLE
New method Tools::getCurrentUrl() to replace FrontController::getCurrentURL

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#28539]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

`FrontController::getCurrentURL` cannot be used in a `hook` because it's `protected`.

### Describe the solution you'd like

This method should be `public`.

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @jf-viguier 

Thank you for your suggestion. The Dev Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon.
Waiting for your PR :rocket: 

Thank you

**Comment by PululuK** [comment]
Hi @jf-viguier 

I suggest to add a new method in `Tools::getCurrentURL`.

**Comment by jf-viguier** [comment]
@PululuK it's done, please review.

**Comment by matks** [comment]
Looks Good To Me (LGTM)

**Comment by jf-viguier** [comment]
I've updated the title to match the pr, thanks @okom3pom
