### ISSUE TITLE
'Trying to access array offset on value of type null' calling WS api categories blank schema

### ISSUE THREAD

**Issue by angelo983** [PrestaShop/PrestaShop#28543]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Call a blank schema of Categories in a shop with Categories tree level depth > 1

![image](https://user-images.githubusercontent.com/100699445/169777567-49a73fa8-1515-4af8-a2c6-627d69f0cd85.png)

### Expected behavior

Blank schema of a category as response

### Steps to reproduce
> Steps by @AureRita 

1. Have a fresh install of Prestashop 1.7.8.4
2. Be on php 7.4
3. Create a Main categories ( under the Home ) ( I called it Pants )
4. Create two subcategories of this one ( I named there Coton / Jean )
5. Go on Advenced Parameters > Webservice 
6. on Configuration, check "Enable PrestaShop's webservice" and save 
7. Clic on " Add new webservice key " 
8. On the key, clic on "Generate" and copy the key 
9. On permission tab, enable "View (GET)", "Modify (PUT)", "Add (POST)", "Delete (DELETE)", "Fast view (HEAD)"
10. Save it 
11. go on "(link of your shop)/api/categories?schema=blank" 
12. Put the key on the login and nothing in password 
13. You should see the same issue  

---
1. Create a categories tree with level depth > 1
2. Attempt to send HTTP request `[GET] /api/categories?schema=blank`
3. Error received: 'Trying to access array offset on value of type null'

### PrestaShop version(s) where the bug happened

1.7.8.4

### PHP version(s) where the bug happened

7.4.29

**Comment by hibatallahAouadni** [comment]
Hello @angelo983 

I didn't manage to reproduce the issue with PS1786, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/169354246-539d9e28-5a4b-4eef-87f3-fe74012b728e.png)

And here's the full result:

```
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <category>
        <id>
            <![CDATA[1]]>
        </id>
        <id_parent>
            <![CDATA[0]]>
        </id_parent>
        <level_depth>
            <![CDATA[0]]>
        </level_depth>
        <nb_products_recursive notFilterable="true">
            <![CDATA[20]]>
        </nb_products_recursive>
        <active>
            <![CDATA[1]]>
        </active>
        <id_shop_default>
            <![CDATA[1]]>
        </id_shop_default>
        <is_root_category>
            <![CDATA[0]]>
        </is_root_category>
        <position>
            <![CDATA[0]]>
        </position>
        <date_add>
            <![CDATA[2022-05-18 16:54:58]]>
        </date_add>
        <date_upd>
            <![CDATA[2022-05-18 16:54:58]]>
        </date_upd>
        <name>
            <language id="1" xlink:href="http://prestashop/prestashop_1.7.8.6/api/languages/1">
                <![CDATA[Root]]>
            </language>
            <language id="2" xlink:href="http://prestashop/prestashop_1.7.8.6/api/languages/2">
                <![CDATA[Racine]]>
            </language>
        </name>
        <link_rewrite>
            <language id="1" xlink:href="http://prestashop/prestashop_1.7.8.6/api/languages/1">
                <![CDATA[root]]>
            </language>
            <language id="2" xlink:href="http://prestashop/prestashop_1.7.8.6/api/languages/2">
                <![CDATA[racine]]>
            </language>
        </link_rewrite>
        <description>
            <language id="1" xlink:href="http://prestashop/prestashop_1.7.8.6/api/languages/1">
                <![CDATA[]]>
            </language>
            <language id="2" xlink:href="http://prestashop/prestashop_1.7.8.6/api/languages/2">
                <![CDATA[]]>
            </language>
        </description>
        <meta_title>
            <language id="1" xlink:href="http://prestashop/prestashop_1.7.8.6/api/languages/1">
                <![CDATA[]]>
            </language>
            <language id="2" xlink:href="http://prestashop/prestashop_1.7.8.6/api/languages/2">
                <![CDATA[]]>
            </language>
        </meta_title>
        <meta_description>
            <language id="1" xlink:href="http://prestashop/prestashop_1.7.8.6/api/languages/1">
                <![CDATA[]]>
            </language>
            <language id="2" xlink:href="http://prestashop/prestashop_1.7.8.6/api/languages/2">
                <![CDATA[]]>
            </language>
        </meta_description>
        <meta_keywords>
            <language id="1" xlink:href="http://prestashop/prestashop_1.7.8.6/api/languages/1">
                <![CDATA[]]>
            </language>
            <language id="2" xlink:href="http://prestashop/prestashop_1.7.8.6/api/languages/2">
                <![CDATA[]]>
            </language>
        </meta_keywords>
        <associations>
            <categories nodeType="category" api="categories">
                <category xlink:href="http://prestashop/prestashop_1.7.8.6/api/categories/2">
                    <id>
                        <![CDATA[2]]>
                    </id>
                </category>
            </categories>
            <products nodeType="product" api="products"/>
        </associations>
    </category>
</prestashop>
```

Please check and feedback.

Thanks!

**Comment by angelo983** [comment]
Hello @hibatallahAouadni,
from these informations I cannot determine your category tree level depth.

Have you followed the first step? (Create a categories tree with level depth > 1)

**Comment by hibatallahAouadni** [comment]
Hello @angelo983 

I created a new Category Pants, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/169500805-f6e90630-dd1a-4076-9be7-6f12030cfdfc.png)

Using this link: `/api/categories` I get this result:
```
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <categories>
        <category id="1" xlink:href="http://prestashop/prestashop_1.7.8.6/api/categories/1"/>
        <category id="2" xlink:href="http://prestashop/prestashop_1.7.8.6/api/categories/2"/>
        <category id="3" xlink:href="http://prestashop/prestashop_1.7.8.6/api/categories/3"/>
        <category id="4" xlink:href="http://prestashop/prestashop_1.7.8.6/api/categories/4"/>
        <category id="5" xlink:href="http://prestashop/prestashop_1.7.8.6/api/categories/5"/>
        <category id="6" xlink:href="http://prestashop/prestashop_1.7.8.6/api/categories/6"/>
        <category id="7" xlink:href="http://prestashop/prestashop_1.7.8.6/api/categories/7"/>
        <category id="8" xlink:href="http://prestashop/prestashop_1.7.8.6/api/categories/8"/>
        <category id="9" xlink:href="http://prestashop/prestashop_1.7.8.6/api/categories/9"/>
        <category id="10" xlink:href="http://prestashop/prestashop_1.7.8.6/api/categories/10"/>
    </categories>
</prestashop>
```
If I added the `?schema=blank`, I get this result: `/api/categories?schema=blank`:
```
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <category>
        <id>
            <![CDATA[]]>
        </id>
        <id_parent>
            <![CDATA[]]>
        </id_parent>
        <active>
            <![CDATA[]]>
        </active>
        <id_shop_default>
            <![CDATA[]]>
        </id_shop_default>
        <is_root_category>
            <![CDATA[]]>
        </is_root_category>
        <position>
            <![CDATA[]]>
        </position>
        <date_add>
            <![CDATA[]]>
        </date_add>
        <date_upd>
            <![CDATA[]]>
        </date_upd>
        <name>
            <language id="1">
                <![CDATA[]]>
            </language>
            <language id="2">
                <![CDATA[]]>
            </language>
        </name>
        <link_rewrite>
            <language id="1">
                <![CDATA[]]>
            </language>
            <language id="2">
                <![CDATA[]]>
            </language>
        </link_rewrite>
        <description>
            <language id="1">
                <![CDATA[]]>
            </language>
            <language id="2">
                <![CDATA[]]>
            </language>
        </description>
        <meta_title>
            <language id="1">
                <![CDATA[]]>
            </language>
            <language id="2">
                <![CDATA[]]>
            </language>
        </meta_title>
        <meta_description>
            <language id="1">
                <![CDATA[]]>
            </language>
            <language id="2">
                <![CDATA[]]>
            </language>
        </meta_description>
        <meta_keywords>
            <language id="1">
                <![CDATA[]]>
            </language>
            <language id="2">
                <![CDATA[]]>
            </language>
        </meta_keywords>
        <associations>
            <categories>
                <category>
                    <id>
                        <![CDATA[]]>
                    </id>
                </category>
            </categories>
            <products>
                <product>
                    <id>
                        <![CDATA[]]>
                    </id>
                </product>
            </products>
        </associations>
    </category>
</prestashop>
```
> Have you followed the first step? (Create a categories tree with level depth > 1)

BTW, can you explain it more :sweat_smile: maybe I didn't understand it :pray: 
Did you mean to create another root category? if so, could you list all steps to do :pray: 
Waiting for your feedback.

Thanks!

**Comment by angelo983** [comment]
Examples of Categories tree with level depth > 1

Example 1: level depth == 2

```
HOME
=> CATEGORY 1 (depth == 1)
      => CATEGORY 2 (depth == 2)
=> CATEGORY A (depth == 1)
      => CATEGORY B (depth == 2)
```


Example 2: level depth == 3

```
HOME
=> CATEGORY 1 (depth == 1)
      => CATEGORY 2 (depth == 2)
            => CATEGORY 3 (depth == 3)
=> CATEGORY A (depth == 1)
      => CATEGORY B (depth == 2)
            => CATEGORY C (depth == 3)
```

Have you associated products to these categories?

**Comment by hibatallahAouadni** [comment]
Hello @angelo983 

Thanks for the details :pray: 
Well, in my shop, I have these categories:
```
HOME
=> CATEGORY Clothes (depth == 1)
      => CATEGORY Men (depth == 2)
      => CATEGORY Women (depth == 2)
=> CATEGORY Accessories (depth == 1)
      => CATEGORY Stationery (depth == 2)
      => CATEGORY Home Accessories (depth == 2)
=> CATEGORY Art (depth == 1)
=> CATEGORY Pants (depth == 1)
```
All categories have associated products except Categpry Pants, did I miss something?
Waiting for your feedback.

Thanks!

**Comment by angelo983** [comment]
@hibatallahAouadni Have you tried with PHP 7.4.29 and PS 1.7.8.4?

**Comment by hibatallahAouadni** [comment]
Hello @angelo983 

I tried with PS1784 and PS1786 with PHP 7.2
Do you think it's related to PHP version?

Thanks!

**Comment by angelo983** [comment]
Sure! A lot of 'Trying to access array offset on value of type null' messages in various CMS are related to PHP 7.4 consistency checks.

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/qa-functional Can someone please try to reproduce the issue :pray: 
I have some technical issues, that I can't reproduce it with PHP 7.4 :disappointed: 

Thanks in advance!

**Comment by AureRita** [comment]
hi @hibatallahAouadni and @angelo983, 

I reproduced this bug as you can see on this screen : 
![image](https://user-images.githubusercontent.com/100699445/169777567-49a73fa8-1515-4af8-a2c6-627d69f0cd85.png)

Thank you for this issue @angelo983 

That was the step that I follow :
1. Have a fresh install of Prestashop 1.7.8.4
2. Be on php 7.4
3. Create a Main categories ( under the Home ) ( I called it Pants )
4. Create two subcategories of this one ( I named there Coton / Jean )
5. Go on Advenced Parameters > Webservice 
6. on Configuration, check "Enable PrestaShop's webservice" and save 
7. Clic on " Add new webservice key " 
8. On the key, clic on "Generate" and copy the key 
9. On permission tab, enable "View (GET)", "Modify (PUT)", "Add (POST)", "Delete (DELETE)", "Fast view (HEAD)"
10. Save it 
11. go on "(link of your shop)/api/categories?schema=blank" 
12. Put the key on the login and nothing in password 
13. You should see the same issue

**Comment by angelo983** [comment]
Hello @AureRita,
I have committed a PR #28540.
