### ISSUE TITLE
Can't create release with CreateRelease.php file

### ISSUE THREAD

**Issue by sLorenzini** [PrestaShop/PrestaShop#28555]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I try to upgrade my store on the develop version (8.0.0). I need .zip folder and .xml file of this version.
On my terminal when I launch the release creation, I have got this error:

<img width="757" alt="Capture d’écran 2022-05-20 à 14 54 59" src="https://user-images.githubusercontent.com/2854834/169545761-939b9000-395f-4d5f-bc31-1a632c46a6db.png">

@florine2623 tries to lauch the release too and got this error:

<img width="582" alt="Screenshot 2022-05-20 at 15 33 45" src="https://user-images.githubusercontent.com/2854834/169545916-6d46e0c3-9c0d-4f72-9e3f-408d3cc4ebfa.png">

### Expected behavior

Should be contain a .zip folder and .xml file on `mystore/tools/build/releases/myreleasefolder`
I have got an empty folder:

<img width="813" alt="Capture d’écran 2022-05-20 à 16 29 13" src="https://user-images.githubusercontent.com/2854834/169550064-6581a1ca-ed20-4e21-913b-74c92e58e7c7.png">

### Steps to reproduce

- Go to the terminal > your store repository on develop branch
- `cd tools/build/`
- `sudo php CreateRelease.php --version 8.0.0`
- see error

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.2.21

**Comment by atomiix** [comment]
@sLorenzini I don't reproduce this issue:
![Capture d’écran 2022-05-20 à 17 13 13](https://user-images.githubusercontent.com/2168836/169558661-db83e2d4-8a30-44c1-ba1e-e528b567f215.png)

I think it comes from you node/npm environment. Are you on a M1 mac? What happens if you run `make assets`?

**Comment by sLorenzini** [comment]
@atomiix, we found the issue with @khouloudbelguith.

Not an environment issue but the "sudo" part...
without the "sudo" cmd it works like your screen. sorry 🥲 
I close the issue.

Thanks
