### ISSUE TITLE
product update hooks don't contain updated values of product features

### ISSUE THREAD

**Issue by alisamie97** [PrestaShop/PrestaShop#28562]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After product update in BO some hooks are called like the list below:
- `actionObjectProductAddAfter`
- `actionObjectProductUpdateAfter`
- `actionProductAdd`
- `actionProductSave`
- `actionProductUpdate`
But some values are not updated yet while running these hooks. For example product features gets the new values after these.

1. Initial features of product
![image](https://user-images.githubusercontent.com/23106000/169700378-3ee346ff-1bce-4d89-be2e-5d97534e1d25.png)

2.  Add a new feature before updating product
![image](https://user-images.githubusercontent.com/23106000/169700421-ce78d434-93f7-4baf-9539-97a3a18cbd70.png)

3. Product features in hook contains old features only
![image](https://user-images.githubusercontent.com/23106000/169700573-248e5e9b-0739-4628-b9c4-b2affee16932.png)

### Expected behavior

I expect to have a really updated product with all new values but product features are NOT updated while running in the hooks.

### Steps to reproduce

1. Make a custom module
2. Register a hook from this list:
- `actionObjectProductAddAfter`
- `actionObjectProductUpdateAfter`
- `actionProductAdd`
- `actionProductSave`
- `actionProductUpdate`
3. Set a break point in the hook for debugger
4. Go to back office
5. Open product edit form
6. Add a new feature
7. Click on save
8. Watch the values in your debugger

### PrestaShop version(s) where the bug happened

1.7.7.8

### PHP version(s) where the bug happened

7.4

**Comment by HanaRebaiQA** [comment]
Hello @stifler97 

Thanks for your report.
I tried to reproduce your issue using this module [ps_qualityassurance.zip](https://github.com/PrestaShop/PrestaShop/files/8753195/ps_qualityassurance.zip) on PS1785 to handle the issue with the `actionObjectProductUpdateAfter` hook, but i did not  reproduce it.

Could you please provide us more information about the custom module that you used.

By the way, is this tickets similar to your issue [#23701](https://github.com/PrestaShop/PrestaShop/issues/23701) or [#20498](https://github.com/PrestaShop/PrestaShop/issues/20498) ?

https://user-images.githubusercontent.com/92912932/169785885-3b547558-19ca-4798-913d-4f0e950cc39e.mp4

 Thank you!

**Comment by alisamie97** [comment]
Hi @HanaRebaiQA .
Thanks for your fast response.
I thought about this more and discussed with my team lead @samberrry. There is no issue actually, because `product` and `feature` are two different models which are extended from `object model`.
For that reason, when we are updating a product, only product attributes get updated before these hooks:
-    `actionObjectProductAddAfter`
-    `actionObjectProductUpdateAfter`
-    `actionProductAdd`
-    `actionProductSave`
-    `actionProductUpdate`

And it does not make sense to update features before product update, Because that is another object model and needs its own process to update.

**Comment by HanaRebaiQA** [comment]
Thanks @stifler97 for your feedback!
