### ISSUE TITLE
Blockwshlist Create modal is hover of every other element

### ISSUE THREAD

**Issue by rodriciru** [PrestaShop/PrestaShop#28565]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Modal create new wishlist has inner .modal with CSS display:block. This is on top of page so in certain occasions, I can't click on buttons, open products...
Removing  display: block; on line 147 on https://github.com/PrestaShop/blockwishlist/blob/dev/_dev/front/js/components/Create/Create.vue should fix this problem, without affecting the functionality.
This style was in all the modals but commit https://github.com/PrestaShop/blockwishlist/commit/de3c7e57f4829ec47a64e2dafa0d14a9a18e6cff remove this style, but not on this file, because has a special style for it.

The problem is more visible on new hummingbird theme, but in some occasion I see it on classic theme as well.
This video was on the new hummingbird theme:
https://user-images.githubusercontent.com/10741347/169796350-40514200-3d98-48ec-bf43-c2b35c6989fd.mp4
This probes that removing display block, doesn't affect functionality

https://user-images.githubusercontent.com/10741347/169797671-ff11a85f-14bf-46c3-a84f-463408da7bc6.mp4

@NeOMakinG 

### Steps to reproduce

Install the module and you can see that this modal its always visible, but it shoulden as it may cause problems

### PrestaShop version(s) where the bug happened

1.7.x

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

blockwishlist

**Comment by HanaRebaiQA** [comment]
Hello @rodriciru 

Thanks for your report.
I tried to reproduce your issue with PS1786 using `blockwishlist module v2.1.0`. But, i could'nt.

Do yo mean, that the block shouldn't be displayed if we disable the `display : block ` of the `.wishlist.create .wishlist.modal `element like in the screenshot ?
![image](https://user-images.githubusercontent.com/92912932/169833778-9bb3507c-d29e-4e0b-9ffb-e8aa395e54fd.png)

Now, the behavior is that the modal of the blockwishlist is always displayed. If, you want to add the function of not displayed, it will be an improvement, am I right ?

Thank you!

**Comment by rodriciru** [comment]
By default, it should be display:none. When it's triggered, a .show class is added and this class has the display:block style.

What you show on the pic, has no sense for me. As i can see, you chrome has display:none as the style working in that moment.
And i can see on the left part of the image the **ADD TO MODAL** (its not the create modal) and on the right part the create modal code, so its not the same

**Comment by HanaRebaiQA** [comment]
Hello @rodriciru 

I tried to reproduce your issue with the same information that your mentioned above. And here is a screenshot to what I have : 

![image](https://user-images.githubusercontent.com/92912932/169872195-e9adf3f4-5f63-4fae-82c9-f894b02a99ef.png)


Is that the issue ?

Thank you!

**Comment by rodriciru** [comment]
No.
The problem is that is display block by default. It shouldn't be as by
default It won't be visible.
But because it's opacity it 0, you can't see it, but it's there. Sometimes
on mouse hover can notice it, because can't click on buttons
So display block in modal can't be there.
Only on show

**Comment by NeOMakinG** [comment]
@HanaRebaiQA The modal, when hidden, is blocking clicks to multiple locations on the theme, like if you click somewhere, it will click on the hidden modal, this is the real bug, try to hide the modal and click where it "is", you'll notice that the modal is annoying

**Comment by NeOMakinG** [comment]
> Hello @rodriciru
> 
> Thanks for your report. I tried to reproduce your issue with PS1786 using `blockwishlist module v2.1.0`. But, i could'nt.
> 
> Do yo mean, that the block shouldn't be displayed if we disable the `display : block ` of the `.wishlist.create .wishlist.modal `element like in the screenshot ? ![image](https://user-images.githubusercontent.com/92912932/169833778-9bb3507c-d29e-4e0b-9ffb-e8aa395e54fd.png)
> 
> Now, the behavior is that the modal of the blockwishlist is always displayed. If, you want to add the function of not displayed, it will be an improvement, am I right ?
> 
> Thank you!

On the same screen as this one, try to click on the "add to cart" button, you probably won't be able because the hidden modal is hover it
