### ISSUE TITLE
Bug during the loading of category page that block my site and the cpu of the server at 100%

### ISSUE THREAD

**Issue by alesspetio01** [PrestaShop/PrestaShop#28566]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Bug during the loading of category page that block my site and the cpu of the server at 100%

### Expected behavior

The page would appear soon

### Steps to reproduce

1. Go to https://mcgroup.store/it/2-home
2. Slow loading of the page
3. The CPU of the server at 100%

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by alesspetio01** [comment]
![Senza titolo](https://user-images.githubusercontent.com/103640419/169824888-23f0fdb3-b021-4ce4-a276-5d07623165f6.png)

**Comment by HanaRebaiQA** [comment]
Hello @alesspetio01 

Thanks for your report.
Do you mean the slowness of loading in front office page when clicking on a item (for example : next) like showing in video 1 ?
I tried to reproduce your issue using your url : 

https://user-images.githubusercontent.com/92912932/169827905-f1b81ef8-232c-4691-9e2e-0b07a31807be.mp4


Maybe it's related to your theme. Or, as i can see in the screen-shot here https://github.com/PrestaShop/PrestaShop/issues/28566#issuecomment-1134646444, you have a problem of memory storage which is full.

I was unable to reproduce your issue when tried on PS1785 and PS1786 with php 7.4 using the classic-theme of PrestaShop.

https://user-images.githubusercontent.com/92912932/169828208-6eb90f48-a69a-4344-a953-054554725c5c.mp4



Could you please check again and feedback?

Thank you!

**Comment by alesspetio01** [comment]
The problem is still present, both when loading that page and also in paging by clicking on a number or on the arrow

**Comment by alesspetio01** [comment]
The cpu goes to 100% and also meory at high percentages, when I loading that page and also in paging by clicking on a number or on the arrow. Before it is at normal levels

**Comment by alesspetio01** [comment]
The cpu goes to 100% and also memory goes at high percentages, when I loading that page and also in paging by clicking on a number or on the arrow. Before it is at normal levels

**Comment by HanaRebaiQA** [comment]
@alesspetio01 So, It's maybe related to your theme?

**Comment by alesspetio01** [comment]
It is a problem that I had also with an another theme on another site, then it resolved without doing anything.
But this time no

**Comment by alesspetio01** [comment]
I thought it was a cache issue and had auto-clearing the cache turned on. But nothing, indeed it seemed to slow down even more

**Comment by HanaRebaiQA** [comment]
@alesspetio01 So, maybe it's related to your environment. 

Despite our efforts, we were not able to reproduce your issue with the provided information. 
It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
We will close this issue.

Do not hesitate to open new tickets when needed.

Thank you!

**Comment by HanaRebaiQA** [comment]
@alesspetio01 Could you please clear your caches from : 

- BO > CONFIGURE > Advanced parameters > Select the Force Compilation and disable Cache and Save

Then click on `clear cache`

- Your PrestaShop folder : var > cache > delete the folders 

Maybe it can help you.

Thanks!

**Comment by alesspetio01** [comment]
@HanaRebaiQA I have just tried. The problem remains only on paginations. But before it worked correctly and I have not changed the server setting
