### ISSUE TITLE
@HanaRebaiQA I have just tried. The problem remains only on paginations. But before it worked correctly and I have not changed the server setting

### ISSUE THREAD

**Issue by alesspetio01** [PrestaShop/PrestaShop#28569]
@HanaRebaiQA I have just tried. The problem remains only on paginations. But before it worked correctly and I have not changed the server setting

_Originally posted by @alesspetio01 in https://github.com/PrestaShop/PrestaShop/issues/28566#issuecomment-1134721805_

**Comment by hibatallahAouadni** [comment]
Hello @alesspetio01 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
