### ISSUE TITLE
Problem with loading category page and paginator in category page

### ISSUE THREAD

**Issue by alesspetio01** [PrestaShop/PrestaShop#28570]
![Senza titolo](https://user-images.githubusercontent.com/103640419/169824888-23f0fdb3-b021-4ce4-a276-5d07623165f6.png)

_Originally posted by @alesspetio01 in https://github.com/PrestaShop/PrestaShop/issues/28566#issuecomment-1134646444_

**Comment by alesspetio01** [comment]
1. Go to https://mcgroup.store/it/2-home
2. Slow loading of the page
3. The CPU of the server at 100%

**Comment by alesspetio01** [comment]
The cpu goes to 100% and also memory goes at high percentages, when I loading that page and also in paging by clicking on a number or on the arrow. Before it is at normal levels

It is a problem that I had also with an another theme on another site, then it resolved without doing anything.
But this time no

But before it worked correctly and I have not changed the server setting

**Comment by alesspetio01** [comment]
![Uploading Home Mc.png…]()

**Comment by alesspetio01** [comment]
![Senza titolo](https://user-images.githubusercontent.com/103640419/169845268-a53081bc-63e9-4f57-a056-f1fa4b8a353e.png)

**Comment by alesspetio01** [comment]
When i Click on TUTTE LE CATEGORIE

**Comment by alesspetio01** [comment]
it is not a theme's problem

**Comment by alesspetio01** [comment]
it is a problem that I have for a few days. Everything worked fine before and I haven't changed anything.

**Comment by HanaRebaiQA** [comment]
This new issue is the following of [#28566](https://github.com/PrestaShop/PrestaShop/issues/28566)

@alesspetio01 Is the issue similar to this one [#28549 ](https://github.com/PrestaShop/PrestaShop/issues/28549) ?

Thank you!

**Comment by alesspetio01** [comment]
no, it is different

**Comment by alesspetio01** [comment]
The page loaded more slow

**Comment by alesspetio01** [comment]
And cpu goes to 100%

**Comment by alesspetio01** [comment]
I have only a hundred categories and about 3000 products

**Comment by alesspetio01** [comment]
the page after different seconds is correctly showed, but it takes too long to load. Same thing for pagination

**Comment by alesspetio01** [comment]
It is a problem that I have for a few days. Everything worked fine before and I haven't changed anything.

**Comment by HanaRebaiQA** [comment]
Hello @alesspetio01 

Thanks for your feedback.
Could you please provide us a screen-record of your issue ?

Thank you!

**Comment by alesspetio01** [comment]
https://calip.io/wYOxV7ej#cRfG3egu

**Comment by alesspetio01** [comment]
Click on the link for the recording

**Comment by florine2623** [comment]
Hello @alesspetio01 ,

Can you check if your site matches the system requirements : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Please check and feedback.
Thanks

**Comment by alesspetio01** [comment]
Yes, my site matches all the system requirements

**Comment by florine2623** [comment]
Can you add this file to your shop : https://github.com/PrestaShop/php-ps-info/releases
And screenshot it please.

**Comment by alesspetio01** [comment]
Where should I add this file?

**Comment by florine2623** [comment]
You can find the steps to add the file here : https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#how-to-verify-your-server-meets-prestashops-requirements

Let me know when you succeed.

**Comment by alesspetio01** [comment]
![Senza titolo](https://user-images.githubusercontent.com/103640419/170000768-55070d32-2113-4ef8-9de3-1b880d26b523.png)

**Comment by florine2623** [comment]
Please modify the data for `max_input_vars`, `memory_limit`, `post_max_size` and `upload_max_filesize` to match what is recommended.
And see if your shop works better.

**Comment by alesspetio01** [comment]
Values ​​changed and configured to recommended ones, but the problem remains

**Comment by florine2623** [comment]
Please empty your cache.

Check what modules you are using. If you don't use some one theme, delete them.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

As I can't reproduce your issue on my side, I will close it.

Thank you
