### ISSUE TITLE
blockwishlist on adminCustormer its not implemented

### ISSUE THREAD

**Issue by rodriciru** [PrestaShop/PrestaShop#28572]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Info show on admin customer regarding blockwishlist its always 0 list and only the name of the module.
![imagen](https://user-images.githubusercontent.com/10741347/169846120-c02ef9e9-5166-492f-a94b-eadbecb30db6.png)
i look in the code and its a plain tpl file. The 0 its harcoded and it has no loops fot showing lists...
Even on the hook method it only sends the module name and nothing more
https://github.com/PrestaShop/blockwishlist/blob/dev/blockwishlist.php#L271
https://github.com/PrestaShop/blockwishlist/blob/dev/views/templates/hook/displayAdminCustomers.tpl

### Expected behavior

Show how many and the name of the customer lists

### Steps to reproduce

Install module.
Login into FO
Create a few list
Go to BO client admin
Check wishlist section
0 list are shown

### PrestaShop version(s) where the bug happened

1.7.x

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

blockwishlist

**Comment by rodriciru** [comment]
I ping @Progi1984 as @NeOMakinG  told me that he know something about the module

**Comment by HanaRebaiQA** [comment]
Hello @rodriciru 

Thanks for your report.
I was able to reproduce your issue with 1786.

Your issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/27143
So, i'll close the issue.

Thank you!

**Comment by HanaRebaiQA** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/27143
