### ISSUE TITLE
Slow loading of category page and paginator in category page, the server's cpu goes to 100%

### ISSUE THREAD

**Issue by alesspetio01** [PrestaShop/PrestaShop#28585]
1. Go to https://mcgroup.store/it/2-home
2. Slow loading of the page
3. The CPU of the server at 100%

_Originally posted by @alesspetio01 in https://github.com/PrestaShop/PrestaShop/issues/28570#issuecomment-1134765677_

**Comment by alesspetio01** [comment]
The cpu goes to 100% and also memory goes at high percentages, when I loading that page and also in paging by clicking on a number or on the arrow. Before it is at normal levels

It is a problem that I had also with an another theme on another site, then it resolved without doing anything.
But this time no

But before it worked correctly and I have not changed the server setting

**Comment by alesspetio01** [comment]
When i Click on TUTTE LE CATEGORIE

it is not a theme's problem

it is a problem that I have for a few days. Everything worked fine before and I haven't changed anything.

**Comment by alesspetio01** [comment]
https://calip.io/wYOxV7ej#cRfG3egu

**Comment by alesspetio01** [comment]
https://calip.io/wYOxV7ej#cRfG3egu

Problem screen-recording

**Comment by alesspetio01** [comment]
My site matches all the system requirements

**Comment by alesspetio01** [comment]
"As I can't reproduce your issue on my side, I will close it."

if the problem exists (as it is reproduced on my site) it CANNOT be considered invalid

**Comment by alesspetio01** [comment]
THERE IS A BUG

**Comment by matks** [comment]
@alesspetio01 Please stop, you are spamming. You are writing multiple messages, not waiting for answers and reopening issues without following the QA team guidelines

**You must follow the template  and the process to submit a complete bug report.** Issues that do not fit with the process will be ignored or closed.

If you continue to spam we will have to block you.

If you need dedicated help, something we dont provide, please follow https://www.prestashop-project.org/support/

This GitHub project is not a Help Center it is a bug tracker.

**Comment by alesspetio01** [comment]
"This GitHub project is not a Help Center it is a bug tracker."

In fact, the my problem is a bug

**Comment by alesspetio01** [comment]
"You are writing multiple messages, not waiting for answers and reopening issues without following the QA team guidelines"

I always waiting answers, but my problem is not resolved

**Comment by alesspetio01** [comment]
@florine2623

**Comment by alesspetio01** [comment]
Completed? And the solution?

**Comment by matks** [comment]
@alesspetio01 We will not provide you a solution. A bug tracker is used to register bugs, not solve them.

If you want a solution please follow https://www.prestashop-project.org/support/
