### ISSUE TITLE
Add file management to backoffice

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#28587]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

There is no way to upload a simple PDF file to prestashop without using an FTP client to use on CMS pages. For example to add a link to "manuals" page or some legal stuff.

### Describe the solution you'd like

There is file manager client for uploading images or videos, we should allow it to work with other file types easily.

https://www.youtube.com/watch?v=X5CUUA8bAtM

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by florine2623** [comment]
@Hlavtox ,

Did you really want to close your issue ?
