### ISSUE TITLE
Credit Slips buggy

### ISSUE THREAD

**Issue by rolandvanille** [PrestaShop/PrestaShop#28583]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

the credit slips don't calculate correctly.
This is happening ever since the first version I had, 1.6.x and it has never been corrected.
The numbers don't add up correctly, especially when a voucher was included in the orignal bill.

Customer "support" of prestashop told me to tell you the problem here.

Not sure, why this problem exists for years now, but please fix it. 

### Expected behavior

calculate the numbers correcly.

### Steps to reproduce

produce an invoice (with voucher)
Then produce a credit slip.
Add up numbers and compare with invoice.
Doesn't match.

### PrestaShop version(s) where the bug happened

all

### PHP version(s) where the bug happened

doesn't matter

**Comment by sLorenzini** [comment]
hello @rolandvanille,

Thank you for this issue. 
Your issue is already reported here on this EPIC: https://github.com/PrestaShop/PrestaShop/issues/22015

I close the issue as duplicated

Thanks
