### ISSUE TITLE
BO - An exception is thrown when edit the carrier with a free shipping enabled

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#28588]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An exception is thrown when edit the carrier with a free shipping enabled

![image](https://user-images.githubusercontent.com/92912932/170073646-2773039b-8816-4514-a69c-c60a0fd63369.png)

https://user-images.githubusercontent.com/92912932/170075047-5637d45a-6ac2-4666-9a63-5cdab42ccbf1.mp4

### Expected behavior

The carrier is well displayed when edit it with the free shipping enabled

### Steps to reproduce

1. Go to BO > IMPROVE > Carriers 
2. Enable the `Free Shipping` of any carrier 
3. Click to edit the carrier
4. See error > Exception is thrown

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4

**Comment by ghost** [comment]
https://github.com/PrestaShop/PrestaShop/issues/28588

**Comment by Progi1984** [comment]
Fixed by @okom3pom in #28788 and tested by @sLorenzini
