### ISSUE TITLE
Harmonize http/https check

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#28580]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

http/https check is not consistent

Sometimes `Configuration::get('PS_SSL_ENABLED')` is used or `Tools::usingSecureMode()`

`Tools::usingSecureMode()` tests if we are in https at server config level while `Configuration::get('PS_SSL_ENABLED')` tests if prestashop is https enabled in its config.

So I guess there should be a usecase where the server is in http and the config in https or the opposite ? Please help on this.

Sometimes `$_SERVER['HTTPS']` is checked and no other server env variables like HTTP_X_FORWARDED_PROTO

### Describe the solution you'd like

Harmonize http/https check in the code

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by florine2623** [comment]
Hello @jf-viguier ,

Thank you for your suggestion. The Dev Team will take it into consideration for future developments. 

Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you create it. 

Thank you

**Comment by matks** [comment]
Hello @jf-viguier 

You are right, http/https check is a mess in the software.

> Please help on this.

I'm afraid I have no idea how I can help 🤷‍♂️
