### ISSUE TITLE
Module Faceted Search in PrestaShop 1.7.8.5 when enable brand is not more visible in category view list

### ISSUE THREAD

**Issue by alexchini** [PrestaShop/PrestaShop#28593]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

For this site i need to show in the category list page the brand for any product:
![Screenshot_2](https://user-images.githubusercontent.com/28784645/170220325-9a7ed7fe-959a-4404-a7bc-80af02a1ff3c.png)

but when the ps_facetedsearch module is enable the brand is not shown
![Screenshot_7](https://user-images.githubusercontent.com/28784645/170221039-f59da662-61b7-466b-9653-d7b5d709e9da.png)

### Expected behavior

The brand should be shown

### Steps to reproduce

1. enable faceted search module

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.2.24

### If your bug is related to a module, specify its name and its version

ps_facetsearch 3.8.0

**Comment by Hlavtox** [comment]
That's weird, faceted search should only provide product IDs, the core supplies the rest of the data. 🤔 There should be no difference in the presented product.

**Comment by hibatallahAouadni** [comment]
Hello @alexchini 

By default, in FO, there's no brand displayed on product item, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/170240067-9b6757d7-dc1c-406e-a2a5-0cfb28fb6721.png)

It seems that you applied some overrides, and when you enable the module FacetedSearch, your overrides are not shown.
So, closing the issue as it's not Core bug! you just need to edit your overrides :wink: 

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

PS: thanks @Hlavtox for your quick reply :rocket: 

Thanks!
