### ISSUE TITLE
URL Alternate with unwanted parameters 

### ISSUE THREAD

**Issue by tups** [PrestaShop/PrestaShop#28609]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

I have just discovered an embarrassing SEO bug, which multiplies the number of existing URLs for a page.

This bug concerns the ModuleFrontController (and function hookModuleRoutes) with several languages which are activated on the Prestashop. 

When there is a well-declared rewrite at the module level, such as for the SmartBlog module, the URL generates well with the URL rewrite. However, when Prestashop generates "alternate" URLs, it goes back to the "sanitizeUrl" function, which adds the parameters that are supposed to be hidden.

Here is an example :
```html
<link rel="alternate" hreflang="fr-fr" href="http://www.test.local/fr/blog/category/15_des-conseils.html?slug=des-conseils&module=smartblog">
```

### Expected behavior

We should have :
```html
<link rel="alternate" hreflang="fr-fr" href="http://www.test.local/fr/blog/category/15_des-conseils.html">
```

Checking the code:
https://github.com/PrestaShop/PrestaShop/blob/531c7407104c4d7cfc72c28808ea9fa80794ff7b/classes/controller/FrontController.php#L2004
We can see that the Sanitize is not useful, because the URL is already generated by Prestashop upstream:
https://github.com/PrestaShop/PrestaShop/blob/531c7407104c4d7cfc72c28808ea9fa80794ff7b/classes/controller/FrontController.php#L1995

I therefore propose that this sanitize be removed unless there are a few things that escape me.

For my part, I fixed it with an override from a module:
`override/classes/controller/FrontController.php`
```php
<?php

class FrontController extends FrontControllerCore
{
    /**
     * @return array containing the URLs of the same page but for different languages
     */
    protected function getAlternativeLangsUrl()
    {
        $alternativeLangs = [];
        $languages = Language::getLanguages(true, $this->context->shop->id);
        if (count($languages) < 2) {
            return $alternativeLangs;
        }
        foreach ($languages as $lang) {
            $langUrl = $this->context->link->getLanguageLink($lang['id_lang']);
            $alternativeLangs[$lang['language_code']] = $langUrl;
        }
        return $alternativeLangs;
    }
}
```

### Steps to reproduce

1. Add the SmartBlog module (I think this is a problem with all modules that use ModuleFrontController and the hookModuleRoutes hook)
2. Add at least two languages
3. Create a blog category
4. Check on the category page, Front side, the "alternate" tag

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

https://github.com/smartdatasoft/smartblog

**Comment by HanaRebaiQA** [comment]
Hello @tups 

Thanks for your report.
Could you please provide us a screenshot or a screen-record to can reproduce the issue clearly ?

Is this issue [#13737](https://github.com/PrestaShop/PrestaShop/issues/13737) similar to yours ?

Thank you!

**Comment by tups** [comment]
Hello @HanaRebaiQA ,

It's not similar to this ticket, because this ticket talks about "canonical" metas, in my case it's "alternate", with a meta specific function "alternate".

To illustrate the bug, as precisely as possible, I have just developed a specific module for this issue.
A simple module, with a Front Controller.

It is therefore sufficient:
- to set up at least two languages on the Prestashop, for example French and English
- To install the module:
[lowissuealternate.zip](https://github.com/PrestaShop/PrestaShop/files/8787141/lowissuealternate.zip)
- In the configuration of the module, a button allows access to the URL of the module on the Front side, you will see the "alternate" tags
- You will be able to see that it has nothing to do with the URL of the page in your web browser
- You can also check that it does not come from the module, but from the function that generates the "alternate"

Thank You !

**Comment by HanaRebaiQA** [comment]
Hello @tups 

Thanks for your feedback.
So, myabe this one can help you https://github.com/PrestaShop/PrestaShop/issues/24513#issuecomment-842207700? 

Waiting for your feedback 

Thank you!

**Comment by tups** [comment]
Hello @HanaRebaiQA,

Unfortunately, that's not it. The ticket you give me talks about retrieving Smarty values.

My issue is creating because the URL just returned by the getAlternativeLangsUrl function is not correct. It is actually then written from the Smarty variable $urls.alternative_langs

Can you seriously check with a developer please? If you wish, I can do the PR directly?

All the information necessary to correct its present in the first message of the issue

**Comment by Hlavtox** [comment]
@tups Hey, I didn't test it yet, but if hreflang alternates are different from canoncials and contain nonsense, go ahead and make a PR please! 🚀

Can you also please check default controllers, if it's OK there? Category, Manufacturer etc.

**Comment by tups** [comment]
@Hlavtox I juste created the PR : #28625

**Comment by AureRita** [comment]
Hi @tups, 

Did you enconter this issue with a native module, if so, can you please name it ?  
Waiting for your feedback 

Thanks

**Comment by tups** [comment]
Hi @AureRita ,

On a basic installation of Prestashop, there is no module that uses the hook: `moduleRoutes`.

The `moduleRoutes` hook is a native Prestashop hook, which allows to rewrite the URLs for the `ModuleFrontController` dynamically. It is often used on blog modules for example.

I just created a small module so that you can easily see the error : [lowissuealternate.zip](https://github.com/PrestaShop/PrestaShop/files/8787141/lowissuealternate.zip)

**Comment by marwachelly** [comment]
Hello @tups ,

Did you mean the attached behavior?

https://user-images.githubusercontent.com/89604350/171224579-43ffe45c-b8a8-4778-a59b-0d93491ff800.mp4

@PrestaShop/prestashop-core-developers What do you think? Is it a bug or a wanted behavior?

Thanks,

**Comment by matks** [comment]
> https://github.com/orgs/PrestaShop/teams/prestashop-core-developers What do you think? Is it a bug or a wanted behavior?

It's hard to say "yes it is a bug it does not work as expected" because SEO is a complex topic and the "expected" is so vague. If you ask ten people "what should be the best SEO behavior of [...]" you may get four different answers.

So I suggest to mark this as improvement although indeed the behavior seems weird. But I'm not 100% confident to label this as bug.

**Comment by tups** [comment]
Hello @matks

This is not an SEO bug but a URL generation bug.
The alternate URLs are not correct with respect to the original route URL. URL parameters have nothing to do with the URL since it is supposed to be rewritten.

There is double encoding, which generates a bad URL.

I made PR #28625 which corrects this double encoding and outputs the correct URLs.

I did several tests, on all core controllers, this does not impact any URL and corrects the one generated by the ModuleFrontController

**Comment by tups** [comment]
Thanks @marwachelly for the video and the test.

**Comment by tups** [comment]
Maybe @Quetzacoalt91 will understand the problem I'm trying to explain

**Comment by Hlavtox** [comment]
> It's hard to say "yes it is a bug it does not work as expected" because SEO is a complex topic and the "expected" is so vague. If you ask ten people "what should be the best SEO behavior of [...]" you may get four different answers.

That's not true. Web has rules and these rules are absolutely clear. The alternate href links MUST link to the canoncial of the pages.

@tups fixed it properly 👍

**Comment by tups** [comment]
Hello,

I see that the issue is still tagged "Needs Specs", what information do you want?

**Comment by matks** [comment]
I'm sorry @tups but I'm afraid on a topic like SEO we need every suggestion of change to be analyzed by an expert

And I'm not expert 😢 

ping @PrestaShop/product-team

**Comment by tups** [comment]
Thank you @matks, I await their return

To explain in a simple way, a page with content must have a unique URL. So a content = a URL. To avoid "Duplicate content".
So my case, from a module, I create a page, with several languages (FR + EN).

So I need to have two URLs, one for each language.
```http://www.test.local/fr/blog/category/15_des-conseils.html```
```http://www.test.local/en/blog/category/15_des-conseils.html```

But Prestashop, involuntarily adds parameters which are supposed to be hidden in the URLs of the alternates tags (to offer the other languages of this page)
Which gives us :
```http://www.test.local/fr/blog/category/15_des-conseils.html?slug=des-conseils&module=smartblog```
```http://www.test.local/en/blog/category/15_des-conseils.html?slug=des-conseils&module=smartblog```

So we end up with 4 URLs findable in the web page instead of two.

Fixing this bug will therefore be beneficial for everyone.

**Comment by MatShir** [comment]
Thanks guy for the testing and the issue ! It's a definitely a bug 👍

**Comment by Hlavtox** [comment]
@tups PR open, can you check? :-) https://github.com/PrestaShop/PrestaShop/pull/33885

**Comment by tups** [comment]
Hey @Hlavtox, you managed to get a PR validated for this 👍 well done

I just did a test with the little module I made for this issue, and your PR https://github.com/PrestaShop/PrestaShop/pull/33885 works well!

Without your PR:
![image](https://github.com/PrestaShop/PrestaShop/assets/868611/e21685aa-0bbb-4195-ae8d-04469a314c9f)

With your PR:
![image](https://github.com/PrestaShop/PrestaShop/assets/868611/b77be6db-ef54-4a41-b876-99be4bc965f2)

**Comment by MatShir** [comment]
It is not merge yet @tups !
Ne mettons pas la charrue avant les boeufs ;)

**Comment by tups** [comment]
Sorry ^^ I didn't believe it anymore, I was too fast

**Comment by MatShir** [comment]
Thanks everyone ! :)
Fixed by https://github.com/PrestaShop/PrestaShop/pull/33885
