### ISSUE TITLE
API Error when changing product price - Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#28600]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When trying to change product price via webservice, with all permissions given, we get the following error:

Trying to access array offset on value of type null ( Product.php, line 7141 )

### Expected behavior

Product should change price.

### Steps to reproduce

Use API to change product price.

I can share the API request **in private.**

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @seederp2p 

> I can share the API request in private.

Can you share the body request here, and try to change the submitted values :wink: 
Are you using Postman to change the product price via WS?

Waiting for your feedback.
Thanks!

**Comment by seederp2p** [comment]
After some testing the problem disapear if I set PHP with:

E_ALL & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT

Maybe related with:

https://github.com/PrestaShop/PrestaShop/issues/26559

?

**Comment by hibatallahAouadni** [comment]
Hello @seederp2p 

Indeed it's a duplicate of this one #26559 
And it's already fixed in the next major patch PS 8.0.0 with this PR #28280
Closing the issue :wink: 

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #26559

**Comment by seederp2p** [comment]
@hibatallahAouadni when you refer to 8.0.0 what PS version are you refering to?

**Comment by hibatallahAouadni** [comment]
@seederp2p this one https://github.com/PrestaShop/PrestaShop/milestone/64 and it's not released yet :sweat_smile: 
You can subscribe to this issue https://github.com/PrestaShop/PrestaShop/issues/26427 to be updated :wink:

**Comment by seederp2p** [comment]
Meaning, the versioning is going from 1.7 to 8.x ? :)

**Comment by hibatallahAouadni** [comment]
@seederp2p Yessss :smile:
