### ISSUE TITLE
Warning: Undefined array key "continue" in tools/profiling/templates/run.tpl

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#28606]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Once you enabling the profiling with PHP8 on PS8, there is a warning: Undefined array key "continue" in tools/profiling/templates/run.tpl

### Steps to reproduce

1. Install develop
2. Enable profiling
3. Use PHP8, if needed
4. See that $continue is not there

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.0.17

**Comment by PrestaEdit** [comment]
Due to this change: https://github.com/PrestaShop/PrestaShop/commit/5748549d5f8faba3c7e0ab2d56e52d81b75646e8#diff-50d2355ea4bd70a9dc265db7fce6e47cd20ec6964152d6ad8f4b6fa808c1c15fL489

Actually, the continue; instruction was modified by {$continue} use in Smarty.

**Comment by HanaRebaiQA** [comment]
Hello @PrestaEdit 

Thanks for your report.
I found this issue [#28061](https://github.com/PrestaShop/PrestaShop/issues/28061) on develop with php 8.0 when the profiling is enabling.
Is it similar to yours ? 

Thank you!

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
