### ISSUE TITLE
Not specifying the optional ShopConstraint parameter is deprecated since version 1.7.8.0

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#28607]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

For an unknow reason, the profiling making an error and I've thrown a PrestaShopException to see what happen.

And, finally, found this one (not maybe related, but an issue however): Not specifying the optional ShopConstraint parameter is deprecated since version 1.7.8.0.

The screen show the related error.

<img width="1069" alt="Capture d’écran 2022-05-27 à 00 27 03" src="https://user-images.githubusercontent.com/2631425/170590095-06de824d-3b00-400b-b0f9-78423c99df81.png">

### Steps to reproduce

n/d

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.0.17

**Comment by HanaRebaiQA** [comment]
Hello @PrestaEdit 

Thanks for your report.
Could you please provide us the steps to reproduce the issue ?

By the way, is this issue related to this one [#28606](https://github.com/PrestaShop/PrestaShop/issues/28606) ?

Thank you!

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by Vicvignesh** [comment]
in prestashop 8.1.7 place order cash on delivery after redirect to 504 - Gateway Timeout

**Comment by Vicvignesh** [comment]
https://prnt.sc/zjKLMXkRsQqD
