### ISSUE TITLE
The hook intercepter of Profiler doesn't manage widget call

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#28604]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Once you enable the profiling, having PHP 7.4 and PrestaShop 1.7.8.x, if you simply call a widget into your footer, for example, it will throw this exception.

<img width="1057" alt="Capture d’écran 2022-05-26 à 22 39 23" src="https://user-images.githubusercontent.com/2631425/170576263-906df173-8f89-49ea-b657-8429a6a5a226.png">

The widget is called simply like {widget name="yourmodule"}. You MUST not pass the hook params, simple use the renderWidget() as default.

As the hook name is empty, the strict type waiting a string, it fail.

### Steps to reproduce

1. Enable profiling
2. Add widget call into - for example - the footer of your theme
3. See error

### PrestaShop version(s) where the bug happened

1.7.8.x

### PHP version(s) where the bug happened

7.4

**Comment by PrestaEdit** [comment]
It's fixed on the develop branch (https://github.com/PrestaShop/PrestaShop/pull/26731/files#diff-e165881704b7f15fda6fd18c7f66a3ab6cda73652d1d642d30ac88855254543dR66) but not inside the 1.7.8.x

**Comment by HanaRebaiQA** [comment]
Hello @PrestaEdit 

Thanks for your report.
Could you please clarify more the Step 2 with s a screenshot or a screen-record to can reproduce it clearly ?

Thank you!

**Comment by kpodemski** [comment]
@HanaRebaiQA 

You can edit `footer.tpl` of the Classic theme and add:
`{widget name='contactform'}` and this should cause an error with profiler enabled

**Comment by florine2623** [comment]
Hello @kpodemski ,

Thanks for the tips.

I have reproduced the issue with your method in PS 1.7.8.x.

https://user-images.githubusercontent.com/16019289/174332561-4c276110-97a4-4dcb-aa49-d4cb49b8ab85.mov

Thanks for your PR @PrestaEdit !
