### ISSUE TITLE
Backoffice Product Page - Error loading associated categories and brand selection

### ISSUE THREAD

**Issue by superteixeira** [PrestaShop/PrestaShop#28616]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When accessing the products page in the backoffice, the associated categories no longer appear correctly in the blue rectangles. Now in this place, all the categories appear, in list format with radio button, in which the main category appears with the active radio button. Occasionally, when opening a product page for the first time in the backoffice, it appears correctly, however, if we then open another one, it appears again incorrectly as described above.
In addition to this error, the button to add the brand stopped working in the case of new articles or duplicate articles, because when clicking on it nothing happens, in the case of existing products, it is not possible to delete the brand, because when clicking on the delete button nothing happens.
I thought it was just an error in my current store, but I created a new store to test and the exact same thing happened.
In the error console, both in my store and in the new one I created to test, the errors appear, which you can check in the attached photo.
![console-error-3](https://user-images.githubusercontent.com/79605404/170832716-d33ed7bb-cd1e-4a68-86b0-020c0967d893.png)
![console-error-2](https://user-images.githubusercontent.com/79605404/170832720-def5b7d2-11e5-43d2-b152-7528ccb639eb.png)
![console-error](https://user-images.githubusercontent.com/79605404/170832721-c64a8054-6991-4ac0-8b4d-b0cf00a6c5ab.png)
![categories-radio](https://user-images.githubusercontent.com/79605404/170832722-110fa0d6-e670-41d8-8f17-ab7127e45b1b.png)

### Steps to reproduce

1. Access a product page in the backoffice for the first time.
2. Navigate to another page.
3. Re-access a product page in the backoffice.
4. You can verify that the indicated errors have arisen.

### PrestaShop version(s) where the bug happened

1.7.8.6.

### PHP version(s) where the bug happened

7.3.

**Comment by AureRita** [comment]
Hi @

Thank you for the reporting Issue.
Actually I can't reproduce your issues, as you can see when I tried to check on the first view of a product I've not the same error as yours.
Please check this video below : 

https://user-images.githubusercontent.com/100699445/171015044-f1ec111c-859c-4f45-92cf-6c71833605e8.mp4

For your other issue, on the modification of the product's brand, I didn't enconter your issue, 
as you can see on this video : 
 
https://user-images.githubusercontent.com/100699445/171015521-813460d5-14f4-4514-a7ea-aad81e32ff13.mp4

Please check and feedback 
Thanks,

**Comment by AureRita** [comment]
Hi @superteixeira  ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thanks
