### ISSUE TITLE
Property `PrestaShopLogger->object_type` is not valid 

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#28617]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Property `PrestaShopLogger->object_type` is not valid when object class name contains `_`

![image](https://user-images.githubusercontent.com/16455155/170834539-dcb62d79-a318-4fe9-8bed-68431433ab25.png)

### Expected behavior

Validate object class name according PHP doc https://www.php.net/manual/en/language.oop5.basic.php

### Steps to reproduce

Try this code 

```php
<?php

PrestaShopLogger::addLog(
     'My log message'
      1,
      null,
      'My_ClassName',
      666,
      true,
      1
 );
```

The log will not be saved and you will get an error. This is because the current `PrestaShopLogger->object_type` validate definition is `isName` so `My_ClassName` is not valid.

NOTE :  This logger is used in the admin controllers to record actions performed on model objects. So all controllers having a className with an underscore will display an error message when add objects.

```php
<?php

class AdminPbsShortCodeController extends ModuleAdminController {
    public function __construct()
    {
        $this->bootstrap = true;
        $this->table = 'my_table_name';
        $this->identifier = 'id_my_table_name';
        $this->className = 'My_ClassName';
        $this->lang = true;

        parent::__construct();
    }

}
```

See for example `AdminController::processAdd`, the ` $this->className` attr is used to log add action, and it will be considered invalid because is not name, according the `PrestaShopLogger` definition.

### PrestaShop version(s) where the bug happened

1.7.8.6

**Comment by matks** [comment]
🎯

**Comment by AureRita** [comment]
Hi @PululuK 

This issue is too technical for me, 
Ping @PrestaShop/prestashop-core-developers, can someone try to reproduce this issue ? :pray: 
Thanks for your PR :rocket: 

Thank you

**Comment by matks** [comment]
I validate the issue
