### ISSUE TITLE
Imagemanager.php timeout

### ISSUE THREAD

**Issue by Recif2** [PrestaShop/PrestaShop#28628]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

PS 1.7.8.6.
Pages take several minutes to display or end with a "FatalErrorException Error: Maximum execution time of 30 seconds exceeded in ImageManager.php line 361", and in general there is a big performance issue with image processing. I went through everything I knew (smarty cache, general cache under Prestashop, updated the GD of php 7.4 etc.). It is very present in category pages. I can't find anything and can't solve the problem... I think it is a bug.

### Expected behavior

Fast display pages

### Steps to reproduce

Go to any category with long list products and wait until page is displaying

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4

**Comment by AureRita** [comment]
Hi @Recif2  ,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Comment by Recif2** [comment]
hi, well, I have another shop running PS 1.6 on the same server and not having any issue with this... So I'm not sure this is a server configuration...
