### ISSUE TITLE
Backoffice order is allowing disabled products

### ISSUE THREAD

**Issue by arirangz** [PrestaShop/PrestaShop#28626]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When creating a backoffice order, we are able to add a disabled product. After sending the order to the customer, he won't be able to finalize the order as the product is disabled.

### Expected behavior

Hide disabled products when creating a backoffice order

### Steps to reproduce

1. Add a backoffice order
2. Add a disabled product
3. Send the link to the client
4. The client cannot finalize the order

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.3

**Comment by Hlavtox** [comment]
That is by design, we want to use backoffice orders to do things the customer can't. Regarding this issue, I already opened a thread for this - https://github.com/PrestaShop/PrestaShop/issues/25339.

There should be a notification for the merchant, not block him from doing things.

**Comment by arirangz** [comment]
Hi @Hlavtox 

Thanks for letting me know about your thread.

A quick alternative would be to display the word [disabled] in the product list so we know that the product we want to add is disable.

**Comment by AureRita** [comment]
HI @arirangz  ,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #25339 .
To be informed when it's fixed, please subscribe to the issue mentioned above.
Thanks @Hlavtox for your quick response 

Thank you

**Comment by AureRita** [comment]
Duplicate of #25339
