### ISSUE TITLE
BO - All orders always displayed in multi store context

### ISSUE THREAD

**Issue by Seb33300** [PrestaShop/PrestaShop#28629]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When using a shop with the multi store feature enabled, the BO order menu always display all the orders even if a shop has been selected.

### Expected behavior

If a shop is selected, only the orders made on this shop should be displayed.

### Steps to reproduce

1. Configure a multi store shop and setup at least 2 shops
2. Make an order on the Shop 1
3. Connect to BO and go to the orders page
4. See the order
5. Change the shop context to the Shop 2
6. See the order from shop 1 (should not be visible)

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by marwachelly** [comment]
Hello @Seb33300,

I didn'ta manage to reproduce your issue with PS 1.7.8.5. The issue appeared previously on develop branch and was already fixed and the [PR](https://github.com/PrestaShop/PrestaShop/pull/26954) is already merged. 

https://user-images.githubusercontent.com/89604350/171130887-c968b997-c2cb-4a11-aaf0-25d0d6ba6edd.mp4

Did I miss something? Could you please check.

Waiting for your feedback.

Thank you,

**Comment by Seb33300** [comment]
In my case, the order share is enabled.

**Comment by marwachelly** [comment]
> In my case, the order share is enabled.

So this is the expected behavior. Could you please disable the option and try. It will be ok. So I will close the issue.

Thanks,
