### ISSUE TITLE
[FO] : Blank message from customer end must not be allow from order detail page

### ISSUE THREAD

**Issue by Amit-Kumar-Tiwari-Webkul** [PrestaShop/PrestaShop#28638]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

1- Open the order details page from the customer side
2- Go to the customer message section
3- Select product 
4- In message box type space only as shown in video
5- Now submit
6- It submitted successfully with a blank message
https://nimb.ws/sT7qbr

### Expected behavior

Blank must not be allowed
https://nimb.ws/sT7qbr

### Steps to reproduce

1- Open the order details page from the customer side
2- Go to the customer message section
3- Select product 
4- In message box type space only as shown in video
5- Now submit
6- It submitted successfully with a blank message
https://nimb.ws/sT7qbr

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.1

**Comment by hibatallahAouadni** [comment]
Hello @Amit-Kumar-Tiwari-Webkul 

I reproduce the issue with PS1767, PS1778, PS1786 and develop. I’ll add this to the debug backlog so that it’s fixed.
Thanks for your PR :rocket: 

Thank you
