### ISSUE TITLE
Code duplicated in PaymentModule class

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#28645]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Is your feature request related to a problem?

Unuseful code duplicated that could be removed

https://github.com/PrestaShop/PrestaShop/blob/dd2aa84c0a8588beaa7df509604f88d5b25a043d/classes/PaymentModule.php#L234-L236

https://github.com/PrestaShop/PrestaShop/blob/dd2aa84c0a8588beaa7df509604f88d5b25a043d/classes/PaymentModule.php#L363-L365

### Describe the solution you'd like

the duplicated code should be removed

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @idnovate 

Thank you for your suggestion. The Developer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

PS: I changed your issue to a feature cause it seems as an improvement more than a bug :wink: 

Thank you

**Comment by kpodemski** [comment]
Hi @idnovate 

As discussed in the related pull request, it has been decided to keep this as the repercussions of improving this part may be unknown.
