### ISSUE TITLE
Duplicate Categories in Prestashop 1.7

### ISSUE THREAD

**Issue by stenovishal98** [PrestaShop/PrestaShop#28643]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I am trying to create a new category, the category is being created but it is being shown two or three times in the back office of Prestshop 1.7 . I have attached some images in which you can see

![image](https://user-images.githubusercontent.com/53423249/171358334-95b5882c-e253-43f9-ae8b-8a7efbe1003d.png)

Have not created any module, only I am creating category as I used to create category earlier. I have also checked in the database but there is only one entry showing the new category. I also checked in the logs that no error is coming and even after debugging there is no error. 

I also checked by doing in base theme of Prestashop but even that is not solving the issue. also checked by disabling those which are not prestashop's modules and also checked by disabling overrides but the issue is not getting resolved.

Plz help me to resolved the issue.

Thanks

### Steps to reproduce

I don't no how to resolved the issue

### PrestaShop version(s) where the bug happened

1.7

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment]
Hello @stenovishal98 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must fill all the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
