### ISSUE TITLE
ps_facetedsearch hide attributes for which don't have any products

### ISSUE THREAD

**Issue by gligorij** [PrestaShop/PrestaShop#28646]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

ps_facetedsearch have some issue I suppose. When I don't using stock filter, it suppose to be showing only size attributes for products for which there is some products in stock. Now is showing all size attributes even if there is no any products for some size attributes. How can be solved this issue?

### Steps to reproduce

On clean instalation prestashop and activate this module, after adding few products. When don't using stock filter, I would like to be visible size attributes (XS,S,M...) only if there is some products in stock for those size attributes.

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_facetedsearch 3.8.0

**Comment by Hlavtox** [comment]
@gligorij Can you please provide screenshots with what you think is wrong?

Faceted shows all products, not only those in stock. If you want to show only products with attributes in stock, check "In stock" filter.

**Comment by gligorij** [comment]
Without enabled additional filter “stock filter”, from the start when user is visiting some catalog, I want to see only available size when at least one product have in stock with that specific size. Product size attributes I want to be hidden if there is no products on stock. For example for size 40 there is no at the moment products in stock and that attribute needs to be hidden.

**Comment by gligorij** [comment]
@Hlavtox  also have written an email to you yesterday about this. Please check if you can

**Comment by hibatallahAouadni** [comment]
Hello @gligorij 

As @Hlavtox asked could you please provide screenshots or screen record about this issue :pray: 
And could you please list clear and concise steps to reproduce the issue.
Waiting for your feedback.

PS: thanks @Hlavtox for your quick reply :rocket: 

Thanks!

**Comment by gligorij** [comment]
The problem is solved, but thanks anyway. For my case in the location /modules/ps_facetedsearch/src/Filters/Block.php added following code:

```
$filteredSearchAdapter->addOperationsFilter(
Search::STOCK_MANAGEMENT_FILTER,
[
[
['out_of_stock', $this->psOrderOutOfStock ? [1, 2] : [1], '='],
],
[
['quantity', [0], '>'],
],
]
);
```

Now in filters without adding stock filter, in Filter for size products, is showing just available size attributes for products.

**Comment by hibatallahAouadni** [comment]
Hello @gligorij 

Thanks for your feedback.
Glad to hear that you solve your issue :tada: 

Closing the issue!
Thanks.
