### ISSUE TITLE
Tax is not working in v1.7.8.5

### ISSUE THREAD

**Issue by Gaja-A** [PrestaShop/PrestaShop#28656]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi,

I recently upgraded my store to version 1.7.8.5 where the tax is not applied to the products.

Any solution ?

Regards,
Gaja

### Steps to reproduce

![image](https://user-images.githubusercontent.com/51961329/171424679-de6776ce-c065-4a2a-886e-44b1106f684f.png)

![image](https://user-images.githubusercontent.com/51961329/171424750-5a0f0461-25f2-4021-ade4-16c2b744c245.png)

### PrestaShop version(s) where the bug happened

1.7.8.5

**Comment by hibatallahAouadni** [comment]
Hello @Gaja-A 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must fill all the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
