### ISSUE TITLE
gsitemap error

### ISSUE THREAD

**Issue by pkotala** [PrestaShop/PrestaShop#28655]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I run gsitemap both from administration or cron I can not find products and categories links. In fact sometimese there are soe few products, currently there is only one category link. See https://www.elektro-auticka.cz/1_cs_0_sitemap.xml, which is currently:

```
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
<url>
<loc>
<![CDATA[ https://www.elektro-auticka.cz/detska-elektricka-auticka-a-elektricke-motorky ]]>
</loc>
<changefreq>daily</changefreq>
<priority>1.0</priority>
</url>
</urlset>
```

### Expected behavior

I expect all categories and all product links would be in sitemap.

### Steps to reproduce

Go to https://www.elektro-auticka.cz/1_cs_0_sitemap.xml
View the content

### PrestaShop version(s) where the bug happened

1.7.7.4

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

gsitemap

**Comment by hibatallahAouadni** [comment]
Hello @pkotala 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #27517. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #27517
