### ISSUE TITLE
shows price when the product is configured not to show it

### ISSUE THREAD

**Issue by abismoar** [PrestaShop/PrestaShop#28667]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When a search is made and the product has a hidden price, it shows it

### Steps to reproduce

website: wecraft.ar

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.2

**Comment by kpodemski** [comment]
Hello. You are using a custom search module. The default module doesn't show prices by default.

**Comment by hibatallahAouadni** [comment]
Hello @abismoar 


Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must fill the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by abismoar** [comment]
Hello Krystian, it must be for the theme, do you know what is the file to
modify to correct it?
