### ISSUE TITLE
Cant change translation on COD module 2.0

### ISSUE THREAD

**Issue by andreicos1982** [PrestaShop/PrestaShop#28671]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello. On COD 2.0, cant change translation for BO on orders. The old bug is back
https://github.com/PrestaShop/PrestaShop/issues/16369

### Expected behavior

Translation not showing

### Steps to reproduce

 It always shows translation in english on orders from BO like in the link
https://github.com/PrestaShop/PrestaShop/issues/16369

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

2.0

**Comment by hibatallahAouadni** [comment]
Hello @andreicos1982 

I didn't manage to reproduce the issue with PS1786 and COD v2.0.0, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/171915052-a939ee08-19e2-40c6-98c0-dc723731d322.mp4

Please clear your cache and disbale it :wink: 
Closing the issue as it's not a bug.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #16369

**Comment by andreicos1982** [comment]
Yes, that part you can translate. 
To reproduce the bug, place an order and check the confirmation email. You will see that on email confirmation payment method is not translated also.
![IMG_20220604_084040](https://user-images.githubusercontent.com/106827127/171986346-189a5aa5-bd6c-457a-ba51-fdb56fa55cc3.jpg)

**Comment by javicisro** [comment]
[hibatallahAouadni](https://github.com/hibatallahAouadni) please change the status. It is a bug and can be reproduced. Next time place the order via front end as a regular customer, not via back office as an admin. The order confirmation (thank you) page, the user account > order history page and the email confirmation (sent to the user) has the default order status translation "Cash on delivery".

See screenshots.
![payment-method-01-grillmarket](https://user-images.githubusercontent.com/7247785/172194501-b4f04e43-0b79-4658-aca1-7b44c0163969.png)
![payment-method-01-zumont](https://user-images.githubusercontent.com/7247785/172194508-0a254a73-3e1b-46be-8a41-73cba3f1b201.png)
![payment-method-02-zumont](https://user-images.githubusercontent.com/7247785/172194511-d15876b0-7118-45ae-a63a-58eae08a7be8.png)
![payment-method-03-zumont](https://user-images.githubusercontent.com/7247785/172194513-03dfc5ad-c688-4603-a34d-be2a8
![payment-method-02-grillmarket](https://user-images.githubusercontent.com/7247785/172196499-1dbfdca5-40d1-4c94-aa04-a3ed6ee0571d.png)
![payment-method-03-grillmarket](https://user-images.githubusercontent.com/7247785/172196503-a9f2a4f3-22b1-4bdc-9629-6585907fd4d7.png)
1fd2a33.png)

**Comment by Matt75** [comment]
@andreicos1982 @javicisro Thanks for report this issue, I fixed it on https://github.com/PrestaShop/ps_cashondelivery/pull/46

@hibatallahAouadni Tell me if you need additional information to reproduce this regression bug introduced in version 2.0.0

**Comment by javicisro** [comment]
[Matt75](https://github.com/Matt75) Thank you for the fix. I've checked it ("It works").

**Comment by hibatallahAouadni** [comment]
Hello @andreicos1982 

Could you please check this comment https://github.com/PrestaShop/PrestaShop/issues/28674#issuecomment-1147230698
Is it similar to your issue?
Waiting for your feedback.

Thanks!

**Comment by andreicos1982** [comment]
It is the same bug as javivisro described. So i gues the module need to be updated
> [hibatallahAouadni](https://github.com/hibatallahAouadni) please change the status. It is a bug and can be reproduced. Next time place the order via front end as a regular customer, not via back office as an admin. The order confirmation (thank you) page, the user account > order history page and the email confirmation (sent to the user) has the default order status translation "Cash on delivery".
> 
> See screenshots. ![payment-method-01-grillmarket](https://user-images.githubusercontent.com/7247785/172194501-b4f04e43-0b79-4658-aca1-7b44c0163969.png) ![payment-method-01-zumont](https://user-images.githubusercontent.com/7247785/172194508-0a254a73-3e1b-46be-8a41-73cba3f1b201.png) ![payment-method-02-zumont](https://user-images.githubusercontent.com/7247785/172194511-d15876b0-7118-45ae-a63a-58eae08a7be8.png) ![payment-method-03-zumont](https://user-images.githubusercontent.com/7247785/172194513-03dfc5ad-c688-4603-a34d-be2a8 ![payment-method-02-grillmarket](https://user-images.githubusercontent.com/7247785/172196499-1dbfdca5-40d1-4c94-aa04-a3ed6ee0571d.png) ![payment-method-03-grillmarket](https://user-images.githubusercontent.com/7247785/172196503-a9f2a4f3-22b1-4bdc-9629-6585907fd4d7.png) 1fd2a33.png)

**Comment by javicisro** [comment]
[hibatallahAouadni](https://github.com/hibatallahAouadni) Yes it is the same as this comment https://github.com/PrestaShop/PrestaShop/issues/28674#issuecomment-1147230698

But again stop using the backoffice. The user/ the client is using the front office. When using back office the status is translated. When using front office the status "Cash on delivery" is only in english (default translation) for the "order confirmation page", "customer account > order history" and for the "classic email template > order confirmation".

**Comment by hibatallahAouadni** [comment]
Hello @javicisro 

Thanks for your feedback!
We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #28674. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #28674
