### ISSUE TITLE
problem with displaying multistore after aupgrading to 1.7.8.6

### ISSUE THREAD

**Issue by shikotak** [PrestaShop/PrestaShop#28678]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After upgrading to 1.7.8.6, multistore  display like the attached screenshot in back office except dashboard and some of the pages.
upgrading done without any error.
![0003](https://user-images.githubusercontent.com/25262144/172038992-f6ef5f9a-b2f7-4619-b359-89b0d4816420.jpg)

### Expected behavior

It should be like dashboard page
![0004](https://user-images.githubusercontent.com/25262144/172039096-9d3eb0f3-a38a-41f6-8cb0-466d47e1a30d.jpg)

### Steps to reproduce

1. install a shop 1.7.6.4
2. change the BO and default language to Persian
3. Upgrade your hsop to 1.7.8.6
4. BO > Go to orders page or customer page
5. See error > the page is not well displayed

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.2

**Comment by AureRita** [comment]
HI @shikotak 

Can you tell us what is your version before the autoupgrade process ? 

Do you think your issue is similar to this one : https://github.com/PrestaShop/PrestaShop/issues/25785

Waiting for your feedback,

Thanks

**Comment by shikotak** [comment]
@AureRita 
Hi,
No, it"s not related to font.
My ex Prestashop version was 1.7.6.4

**Comment by hibatallahAouadni** [comment]
Hello @shikotak 

Could you please try to reload the page, clear the cache and disbaled the PS cache:

![image](https://user-images.githubusercontent.com/23308427/172357074-eb3c2e43-4cd3-4fa5-a6f9-80eaf2a41249.png)

Waiting for your feedback.
Thanks!

**Comment by shikotak** [comment]
@hibatallahAouadni 
Thank you but it is not related to cache. I am not sure you get my issue or not.
It is just related to displaying multi store.As you can see in attachment image we should see multi store feature at the top of the page, not like this

![0005](https://user-images.githubusercontent.com/25262144/172391008-502c71ed-af12-4c7b-91b0-f76be0bff477.jpg)

**Comment by hibatallahAouadni** [comment]
Hello @shikotak 

Could you please provide a screenshot of your console, to check the displayed errors :pray: 
Waiting for your feedback.

Thanks!

**Comment by shikotak** [comment]
@hibatallahAouadni 
sure,

![0007](https://user-images.githubusercontent.com/25262144/172556716-a658c65c-332e-47ac-8195-16026ce2234f.jpg)

**Comment by hibatallahAouadni** [comment]
Hello @shikotak 

Thanks for the screenshot :pray: 
I just change the steps to reproduce in the issue description, could you please check and confirm :pray: 
Please provide the 1-Click upgrade module version, that you used to uograde your shop.
Waiting for your feedback.

Thanks!

**Comment by shikotak** [comment]
@hibatallahAouadni
Thank you for response.
The 1 click upgrade module version is v4.14.1
I ask a Prestashop developer to look at my site and he told me the problem was a css rtl file. All files has been changed after upgrading except this file.
1- At first I upgrade the site and I enable Regenerate RTL stylesheet option. there was lots of problem and site was left to right.
2- I restore the files and
3- I upgrade again and in this time I disable Regenerate RTL stylesheet option.
The problem has been solved by replacing that css file.

**Comment by florine2623** [comment]
Hello @shikotak ,

Thanks for the update, glad it works well now !
As it is fixed, I will close the issue.

Thanks!

**Comment by shikotak** [comment]
Hello @florine2623 
Yes, you can close the issue.
