### ISSUE TITLE
ps_cashondelivery 2.0.0 language issues

### ISSUE THREAD

**Issue by Szobi81** [PrestaShop/PrestaShop#28674]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

With 2.0.0 installed, the module uses english in some places instead of the translation. FYI: Fizetes utanvettel is Cash on delivery Only tested with hungarian language.  
![Screenshot_17](https://user-images.githubusercontent.com/37904125/171921993-4bf59656-feb3-436e-945a-6fa5169b8796.png)

![Screenshot_18](https://user-images.githubusercontent.com/37904125/171922138-e471c1bd-ee32-4e06-a7d6-303b2b426c80.png)

both in order details and in the confirmation mail wrods are english as seen in screenshots

### Expected behavior

Module should use the original translations, as did the previous version. Going to module translations shows everything is fine.

### Steps to reproduce

1. Install your shop with another languages than english (here hungarian)
2. install the module ps_cashondelivery v2.0.0
3. make an order with the type of payment : cash on delivery 
4. check the statuses of orders, see error 
5. put the status : "awaiting cash on delivery validation" 
6. update the status to " Delivered "
7. check the mail send for the confirmation 

### PrestaShop version(s) where the bug happened

1.7.8.6 and 1.7.7.7

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_cashondelivery 2.0.0

**Comment by AureRita** [comment]
Hi @Szobi81 

Thank you for the reporting Issue.
I partly reproduced it on 1.7.8.6, Indeed the description of the method of payment and the awaiting status is not translate in hungarian but the rest ( the confirmation mails ) it's in hungarian, we can see it on this video : 

https://user-images.githubusercontent.com/100699445/172130135-e97a22b3-9334-4b02-8b03-a9f07594fb1d.mp4

I tried also to do it in Spanish and in French, I didn't have the problem of the order status with them languages, but with the spanish version, I've the issue with the description, we can see it here : 

https://user-images.githubusercontent.com/100699445/172130580-4ecee06f-0b7b-47b7-a395-f9b1a6d27cca.mp4

I'll modify a little bit your steps to reproduce, can you notify me if this is not the real steps ? 

For the mail, it's maybe with the setup of the mail, could you check it ? 

Thanks

**Comment by Prestafan1234** [comment]
Hi,
This bug needs to be re-opened. I have recently upgraded my shop to 1.7.8.6 and the Cash on delivery module was updated to version 2.0.1. My translations are still shown in back office under translations - I use it to accept a payment method called EAN, but when an order is made, I have the exact same problems as posted in the beginning of this thread. In the order confirmation e-mail it says "Cash on delivery" as payment method. The order status shows that the payment is awaiting Cash on delivery and it is set to use a mail template "cashondelivery" under order statusses. This template does not exist when I check the mails folder. The order_conf email is sent to the client, but with the wrong translations.

![billede](https://user-images.githubusercontent.com/50907712/177561843-ae5e5fe6-ceae-424d-aa1f-2b812681acce.png)

![billede](https://user-images.githubusercontent.com/50907712/177560372-6b84a876-50e9-47e5-bce7-721269dedd14.png)
![billede](https://user-images.githubusercontent.com/50907712/177560731-f5fb0d69-f7fa-41c0-9dfc-87a74e75201e.png)
![billede](https://user-images.githubusercontent.com/50907712/177562321-299cdaaa-da0a-4a69-952f-a36030f87f00.png)

**Comment by Prestafan1234** [comment]
@HanaRebaiQA can someone look at this bug please?

**Comment by HanaRebaiQA** [comment]
Hello @Prestafan1234  

Did you check with the new `ps_cashondelivery v2.0.1 `? cause normally this [PR](https://github.com/PrestaShop/ps_cashondelivery/pull/46) fixed this origin issue.
Otherwise, if are able to reproduce it again, please feel free to open a new ticket to can treat it easly.

Thank You!
