### ISSUE TITLE
Decorating the same controller through different modules. decorate controller behaviour

### ISSUE THREAD

**Issue by abderraxim** [PrestaShop/PrestaShop#28672]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

PrestaShop
Symfony 3.4.49
PHP version 
PHP Extensions xdebug APCu OPcache
PHP SAPI fpm-fcgi

Installing 2 modules or making 2 modules that can decorate the same controller (in my case order controller) throws this error
Type error: Argument 1 passed to [xxxx]\Controller\Admin\OrderPrevController::__construct() must be an instance of PrestaShopBundle\Controller\Admin\Sell\Order\OrderController, instance of [yyyy]\Controller\Order[xxxx]Controller given, called in /home/bf/bf_dev/var/cache/dev/ContainerRnuiky4/getOrderPrevControllerService.php on line 8

[xxx and yyy reffers to the name of the modules]
the expected behaviour on the devdocs is that decoration should be done only on the desired methods , what i discovered is that you should proxy all other methods through the same method names and returns $this->decorateController->(method from the original controller) which at some points makes overriding a less time consuming solution. as for Private function you just need to raw copy them the original controllers as they are not accessible.

NB : the methods decorated on both modules do not conflicts 
ex : yyyy OrderController indexAction decorated
      xxxx OrderController indexAction proxied ( return $this->decoratedController->indexAction($request, $filters);)

Tried : 
- xxx proxied  AND yyy proxied = ERROR
- xxx decorated AND yyy Proxied = ERROR
- VICE VERSA
- deleted the proxied methods from both and kept only decorated gives a not callable method ..
- adding priority just inverts the result and did not solve the problem

### Steps to reproduce

1. install 2 modules that decorate the same controller
2. decorate 1 different method on each module controller decorator

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4.29

**Comment by hibatallahAouadni** [comment]
Hello @abderraxim 

Ping @PrestaShop/prestashop-core-developers or @PrestaShop/prestashop-maintainers could someone please try to reproduce the issue :pray: it's too technical for me :sweat_smile: 

Thanks in advance!

**Comment by abderraxim** [comment]
Any News ? that's blocking my development process

**Comment by atomiix** [comment]
Hi @abderraxim would you mind give us 2 sample modules so we can reproduce your issue easily? 🙏
