### ISSUE TITLE
Standard module LinkList throws ClassNotFoundException

### ISSUE THREAD

**Issue by stefanomarty** [PrestaShop/PrestaShop#28676]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Plain vanilla install on Debian 11, try to update or simply save the list of links in LinkList module v5.0.4

<img width="1440" alt="Schermata 2022-06-04 alle 11 25 08" src="https://user-images.githubusercontent.com/3297621/171993564-9da14638-d4c8-443f-97f3-e77e56f3e34b.png">

ClassNotFoundException is thrown:
```
Symfony\Component\Debug\Exception\ClassNotFoundException:
Attempted to load class "Tools" from namespace "PrestaShop\Module\LinkList\Repository".
Did you forget a "use" statement for "PrestaShop\PrestaShop\Adapter\Tools"?

  at modules/ps_linklist/src/Repository/LinkBlockRepository.php:179
  at PrestaShop\Module\LinkList\Repository\LinkBlockRepository->update()
     (modules/ps_linklist/src/Form/LinkBlockFormDataProvider.php:219)
  at PrestaShop\Module\LinkList\Form\LinkBlockFormDataProvider->setData()
     (src/Core/Form/FormHandler.php:127)
  at PrestaShop\PrestaShop\Core\Form\FormHandler->save()
     (modules/ps_linklist/src/Controller/Admin/Improve/Design/LinkBlockController.php:242)
  at PrestaShop\Module\LinkList\Controller\Admin\Improve\Design\LinkBlockController->processForm()
     (modules/ps_linklist/src/Controller/Admin/Improve/Design/LinkBlockController.php:154)
  at PrestaShop\Module\LinkList\Controller\Admin\Improve\Design\LinkBlockController->editProcessAction()
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (admin862m6kcqz/index.php:82)
```

### Expected behavior

No exception thrown.

### Steps to reproduce

Open the LinkList module and try to update/save the links.

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4.29

### If your bug is related to a module, specify its name and its version

LinkList v5.0.4

**Comment by kpodemski** [comment]
There's something wrong as this line is different in the official release:
https://github.com/PrestaShop/ps_linklist/blob/5cbfe0566d7273cb15e199915cdf2a7c912ebcda/src/Repository/LinkBlockRepository.php#L179

**Comment by stefanomarty** [comment]
That's interesting, I checked the official releases:
[prestashop_1.7.8.6.zip](https://github.com/PrestaShop/PrestaShop/releases/download/1.7.8.6/prestashop_1.7.8.6.zip)
[ps_linklist v5.0.4](https://github.com/PrestaShop/ps_linklist/releases/tag/v5.0.4)
and none of those has the Tools::jsonEncode() function.
I remember I uninstalled and reinstalled the LinkList module from Prestashop Addons marketplace, so maybe that line is coming from there.

I will try with a fresh install and see what happens.

**Comment by stefanomarty** [comment]
OK, I made a new fresh install and the issue is NOT present!
Something must have happened during the tests I made after the first installation, i.e. I remember trying a couple of different themes. Unfortunately i didn't keep trace of all the different configurations I tried, so I cannot tell when the `Tools::jsonEncode()` line was changed.

I'm closing the issue for now, I will reopen it as soon as I find out what's happening with the ps_linklist module.

**Comment by AureRita** [comment]
Hi @stefanomarty 

Thank for your Issue and waiting for your feedback.

**Comment by dertin** [comment]
Hello, I had the same error, and I don't know how that line was modified. Does anyone know why this can happen?

**Comment by stefanomarty** [comment]
I still need to complete my tests. Do you remember if you have loaded any different theme after the first install? At the moment it's the only cause I can think of.
