### ISSUE TITLE
Legacy hook vs New Hook dispatcher

### ISSUE THREAD

**Issue by luigimassa** [PrestaShop/PrestaShop#28680]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello, 
I found in `src/Adapter/Product/AdminProductDataProvider.php' 2 hooks: _actionAdminProductsListingFieldsModifier_ and _actionAdminProductsListingResultsModifier_.
These hooks are called with legacy: Hook::exec.....

### Expected behavior

Change the calls with new Hook dispatcher system
```php
 $this->hookDispatcher->dispatchWithParameters('actionAdminProductsListingResultsModifier',[
            '_ps_version' => AppKernel::VERSION,
            'products' => &$products,
            'total' => $total,
        ]);
```
```php
        $this->hookDispatcher->dispatchWithParameters('actionAdminProductsListingFieldsModifier',[
            '_ps_version' => AppKernel::VERSION,
            'sql_select' => &$sqlSelect,
            'sql_table' => &$sqlTable,
            'sql_where' => &$sqlWhere,
            'sql_group_by' => &$sqlGroupBy,
            'sql_order' => &$sqlOrder,
            'sql_limit' => &$sqlLimit,
        ]);
```

### Steps to reproduce

1. open file src/Adapter/Product/AdminProductDataProvider.php
2. search Hook::exec

### PrestaShop version(s) where the bug happened

1.7.7.0

### PHP version(s) where the bug happened

7.2

**Comment by AureRita** [comment]
Hi @luigimassa 

Thank for your report,
This issue is too technical for me, ping @PrestaShop/prestashop-core-developers, can someone please reproduce this issue ? 

Thanks

**Comment by luigimassa** [comment]
Check pull request **Change Legacy Hook with new Hook dispatche event: actionAdminProducts… #28681**
Regards
