### ISSUE TITLE
YamlLint Check reports notices on develop

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#28689]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

YamlLint Check reports notices on develop that need to be fixed

### Expected behavior

Develop branch should not contain known CI issues

### Steps to reproduce

1. Go to a PR like https://github.com/PrestaShop/PrestaShop/pull/28683
2. Open Diff tab https://github.com/PrestaShop/PrestaShop/pull/28683/files
3. See at the bottom the CI notices

<img width="887" alt="Capture d’écran 2022-06-06 à 22 54 16" src="https://user-images.githubusercontent.com/3830050/172247902-0a8937eb-fdb1-4591-bf3d-21b2085d0be3.png">

### PrestaShop version(s) where the bug happened

develop

**Comment by hibatallahAouadni** [comment]
Hello @matks 

Thanks for your issue and your PR :rocket: 
Indeed it's been awhile since some PRs contain these YAML notices.

Thanks!
