### ISSUE TITLE
Add default filter option to faceted search

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#28687]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Merchants forget to setup faceted search when they create new categories, that leads to categories without filters.

### Describe the solution you'd like

- Add a checkbox to faceted search filter called **"Set this filter template automatically to new categories"**.
- Hook to `actionCategoryAdd` and check, if some filter has this checkbox checked. If yes, assign the category to it.

Ping @kpodemski

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by AureRita** [comment]
Hi @Hlavtox 
Thank you for your suggestion. The Developer Team will take it into consideration for future developments.

Please be aware that there is no guarantee that this feature will be developed anytime soon.
Waiting for your PR :rocket: 

Thank you

**Comment by matks** [comment]
I validate this idea 👍

**Comment by etsmes** [comment]
I am interested too
Do you know the solution?
Thank you!
