### ISSUE TITLE
ps_emailalerts module distribution contains dev dependencies

### ISSUE THREAD

**Issue by savedario** [PrestaShop/PrestaShop#28685]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Version 2.3.3 gets installed with the full vendor folders which includes 3520 files in 615 subfolders.
I don't think this is the intended content of the distributed module.

### Expected behavior

I expect composer --dev dependencies NOT to be installed on my test / production enviroment.

### Steps to reproduce

Just install the module from Prestashop's Module upgrade page.

### PrestaShop version(s) where the bug happened

1.7.8

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_emailalerts 2.3.3

**Comment by kpodemski** [comment]
Hi @savedario 

I've just updated to `2.3.3`, and I don't see anything wrong inside the `/vendor` directory.

**Comment by hibatallahAouadni** [comment]
Hello @savedario 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
