### ISSUE TITLE
Random symbols are allowed in a field for numbers [Supplier list module]

### ISSUE THREAD

**Issue by Saimis777** [PrestaShop/PrestaShop#28684]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The module Supplier list has a field in the configuration called: " Number of elements to display ". Would make sense that it only should allow numbers, but instead all random symbols are accepted.
![Uploading image.png…]()

### Expected behavior

Should show an error that only numbers are allowed.

### Steps to reproduce

1. Install module "Supplier list"
2. Go to the configuration of the module
3. In the field: " Number of elements to display " enter anything random
4. Press "Save"

### PrestaShop version(s) where the bug happened

1.7.8.4

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

Supplier list v1.0.4

**Comment by AureRita** [comment]
Hi @Saimis777 

Thank you for the reporting Issue.
I reproduced it on 1.7.8.6, with the module version 1.0.3 and with the version 1.0.4
you can see a video that show the issue :

https://user-images.githubusercontent.com/100699445/172201377-2eaab303-4a8a-433d-b180-09b0932872b0.mp4

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks

**Comment by Progi1984** [comment]
Fixed in  PrestaShop/ps_supplierlist#13 by @okom3pom & tested by @florine2623
