### ISSUE TITLE
Refund buttons do not work for some orders

### ISSUE THREAD

**Issue by mefm247** [PrestaShop/PrestaShop#28698]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

For some orders, the "Return products" and "Partial refund" buttons do not work. Pressing on them does nothing.

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/548621/172568159-57dcf493-dcc1-4032-ac59-4a5323b2c46c.png">

So far we seem to have isolated the issue to Paypal orders outside of France (country of the shop). It does not happen for every foreign order, but has only happened with a few orders fitting the above description.

The issue is happening with the latest version of Prestashop 1.7.8.6

### Expected behavior

When pressing the "Return products" and/or "Partial refund", the screen below should appear to allow us to complete the refund.

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/548621/172568778-c1866542-2b8f-405e-9952-ae0c0a2ce843.png">

### Steps to reproduce

1. Go to "Orders", find one of the affected orders.
2. Select the order to go into the order detail.
3. Press "Return products" or "Partial refund"

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4.29

**Comment by mefm247** [comment]
We were able to resolve this issue by disabling "Rocket loader" from Cloudflare. That optimization was breaking the script but ONLY in certain orders...

**Comment by hibatallahAouadni** [comment]
@mefm247 Glad to hear :tada:
