### ISSUE TITLE
❄️ 8.0.0 feature freeze

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#28708]
### Current status

- [x] Create 8.0.x branch https://github.com/PrestaShop/PrestaShop/tree/8.0.x
- [x] Update GitHub template https://github.com/PrestaShop/PrestaShop/pull/28710
- [x] Publish Build article https://github.com/PrestaShop/prestashop.github.io/pull/1089
- [x] Update nightly builds to compute a ZIP for 8.0.x branch each night https://github.com/PrestaShop/PrestaShop/pull/28710
- [x] Update nightly board to allow selecting new version https://github.com/PrestaShop/nightly-board/pull/84
- [x] Update 8.0.0 release tracking issue https://github.com/PrestaShop/PrestaShop/issues/26427
- [x] Modify PRs for 8.0.0 to target `8.0.x` branch
- [x] Handle PRs targeting `develop` that contain BC break as `develop` is likely* to become 8.1.0 version
- [x] Update Presthubot to handle the new branch https://github.com/PrestaShop/presthubot/pull/51

### When this is done

- [ ] https://github.com/PrestaShop/open-source/issues/102

*To be decided with maintainers

**Comment by matks** [comment]
Following the merge of https://github.com/PrestaShop/PrestaShop/pull/28594 and https://github.com/PrestaShop/PrestaShop/pull/28127 we are able to freeze

**Comment by jolelievre** [comment]
Here is the PR that updates the github configuration https://github.com/PrestaShop/PrestaShop/pull/28710 (PR templates, github actions for nightly, ...)

**Comment by matks** [comment]
Documentation about what it means https://devdocs.prestashop.com/1.7/project/release/minor-release-lifecycle/#feature-freeze

**Comment by matks** [comment]
Only remaining item: https://github.com/PrestaShop/open-source/issues/102

I close this issue.
