### ISSUE TITLE
Generated microdata in head-jsonld.tpl is wrong if logo_details not available

### ISSUE THREAD

**Issue by drc0** [PrestaShop/PrestaShop#28709]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

if you have a condition at line 31 (that could be false) https://github.com/PrestaShop/classic-theme/blob/5632e4a90ce73ae529ceefbbf1f5f7eea0f755b4/templates/_partials/microdata/head-jsonld.tpl#L31

then you must take into account the resulting json, and that would be invalid if the condition is false because of the trailing comma, this patch simply puts the comma inside the condition so the resulting concatenation is well formed.

### Expected behavior

valid json if logo_detail missing

### Steps to reproduce

have logo_details missing

### PrestaShop version(s) where the bug happened

1.7.6.8

**Comment by kpodemski** [comment]
Hello @drc0 

`classic-theme` repository targets PrestaShop 8, also, JSON-LD changes are compatible only with PrestaShop 1.7.8.0+ and from what I see you're using 1.7.6.8

**Comment by NeOMakinG** [comment]
FYI I guess QA can test this using https://developers.google.com/search/docs/advanced/structured-data

**Comment by drc0** [comment]
> Hello @drc0
> 
> `classic-theme` repository targets PrestaShop 8, also, JSON-LD changes are compatible only with PrestaShop 1.7.8.0+ and from what I see you're using 1.7.6.8

the bug should be independent from prestashop version, it is dependent only on the code syntax, you can't have a trailing comma.

**Comment by sLorenzini** [comment]
hello @drc0,

Thank for your report,
This issue is too technical for me, ping @PrestaShop/prestashop-core-developers  can someone please reproduce this issue?

Thanks

**Comment by drc0** [comment]
Hi @sLorenzini ,
sure no problem, the link you gave me returns 404, is there some other way I can do what you are suggesting? Let me know if I can help giving you more information.

**Comment by matks** [comment]
Fixed in https://github.com/PrestaShop/classic-theme/pull/30
