### ISSUE TITLE
Expose smarty var to add reviews on productcomments

### ISSUE THREAD

**Issue by rodriciru** [PrestaShop/PrestaShop#28715]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Google Structured data testing tool complains about reviews not added to JSON+LD
I can't find any exposure of this values, so I added, and the themes can use it. 
An PR on new Hummingbird theme is done and waiting for this:
https://github.com/PrestaShop/hummingbird/pull/319

### Expected behavior

Reviews can be printed on the theme

### Steps to reproduce

There no info, so theres no way to reproduce them.Just install the module

### PrestaShop version(s) where the bug happened

1.7.x

### If your bug is related to a module, specify its name and its version

productscomments

**Comment by sLorenzini** [comment]
Hello @rodriciru,

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template and provide clear and concise steps to reproduce the bug**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by kpodemski** [comment]
Hello @rodriciru 

I think it's more like a feature request. Feel free to create one because I've seen you sent a PR already 💪🏻👍🏻

**Comment by rodriciru** [comment]
Thanks @kpodemski you are right.
I open a new issue:
https://github.com/PrestaShop/PrestaShop/issues/28719
