### ISSUE TITLE
Cart with wrong id_shop_group

### ISSUE THREAD

**Issue by cquintini** [PrestaShop/PrestaShop#28721]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Using a fresh install on a single store environment when you make an order from the BO the id_shop_group  is stored into the Cart table as 0.  This brings some issues in modules like stripe official when validating webhooks as id_shop_group in this case should be set to 1.

### Expected behavior

it is expected that the id_shop_group field to be stored with the correct value.

### Steps to reproduce

1. Login to BO
2. Go to Orders
3. Add New Order  
4. Search and pick a customer
5. Search and pick product
6. At this point a new cart entry should be added to the database and id_shop_group should not be 0.

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4.29

**Comment by florine2623** [comment]
Hi @cquintini ,

I reproduced the issue with PrestaShop version PS 1.7.7.8, 1.7.8.x and 8.0.x. I'll add this to the backlog so it can be fixed.

<img width="1188" alt="Screenshot 2022-06-10 at 10 13 45" src="https://user-images.githubusercontent.com/16019289/173060993-38db3743-4020-4226-a786-f34d14b16dcb.png">

Thank you for the PR !

**Comment by cquintini** [comment]
Hi @florine2623 thanks for checking this out.  As a matter of fact, I've already fixed this issue and introduced this pull request:  #28722 

Regards,
Cesar

**Comment by florine2623** [comment]
Related to https://github.com/PrestaShop/PrestaShop/issues/28515
