### ISSUE TITLE
Duplicate NT iso_code in state table

### ISSUE THREAD

**Issue by gilemon** [PrestaShop/PrestaShop#28737]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After installation, the state table contains 2 entries with **iso_code** NT.

- id_state 	id_country 	id_zone 	name 	iso_code Ascending 1 	tax_behavior 	active
- 99 	21 	2 	Northwest Territories 	NT 	0 	1
- 319 	21 	2 	Northern Territory 	NT 	0 	1

### Expected behavior

Northwest Territories is in Canada and Northern Territory is in Australia.
So for id_state = 99 id_country should be 4 (Canada).

### Steps to reproduce

1. Install PrestaShop
2. Go to the state table and search for entries with **NT** iso_code

### PrestaShop version(s) where the bug happened

1.7.8.3

**Comment by gilemon** [comment]
install-dev/data/xml/state.xml has correct id_country for both NT entries. Issue must come from somewhere else than the installation script.

**Comment by AureRita** [comment]
Thanks for your feedback
