### ISSUE TITLE
Auto Image Optimization 

### ISSUE THREAD

**Issue by DracoBluee** [PrestaShop/PrestaShop#28731]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

built-in into the prestashop engine or using the photo optimization module.  in my opinion, such a function should be offered for free by prestashop, not by means of paid modules.

### Describe the solution you'd like

Auto optimize image

### Do you plan to work on this feature?

- [x] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by abramofranchetti** [comment]
@DracoBluee could you provide some further explanation or some example?

**Comment by DracoBluee** [comment]
optimizing photos and compressing.  so that the image files weigh less.  optimization should run automatically as soon as the image is loaded.  this is very important because due to bad optimization of photos the page loads slower.

**Comment by Hlavtox** [comment]
Hi @DracoBluee, I am not exactly sure what you mean by photo optimization.

- Prestashop automatically optimizes image sizes by rendering proper thumbnails that you need.
- It will render multiple image formats for usage in srcsets in future version.
- You can set your own compression ratio for JPGs and PNGs to save space.

There is nothing more that can be done to optimize images.

**Comment by AureRita** [comment]
Hi @DracoBluee ,
As Hlavtox mentioned above "There is nothing more that can be done to optimize the images"
So closing the issue as your proposal is not clear enough.
Thanks!
