### ISSUE TITLE
Change product type and lost my product data

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#28738]
## Describe the bug

As merchant, when I do changes in my product and then change the product. I lost all my data because I didn't save the changes first.

## Expected solution

When the product has unsaved modification, the user can't change the type of the product.
When the product has unsaved modification
Then change type button is disabled.

When the product modification have been saved / There are no unsaved modification
Then change type button is enabled.

## Test

Test for each product type if I can't change the product if there is unsaved modification.

**Comment by margud** [comment]
Is it really a issue where changing product type to virtual the price is changed to old price + ecotax. i can see that this logic was added not so long ago. So maybe this is the correct way?
commit: [4700513](https://github.com/PrestaShop/PrestaShop/commit/4700513)

**Comment by zuk3975** [comment]
> Is it really a issue where changing product type to virtual the price is changed to old price + ecotax. i can see that this logic was added not so long ago. So maybe this is the correct way? commit: [4700513](https://github.com/PrestaShop/PrestaShop/commit/4700513)

ping @jolelievre I see it was your commit, should know better.
