### ISSUE TITLE
SQL Manager - Option to remove column headers

### ISSUE THREAD

**Issue by d33x** [PrestaShop/PrestaShop#28734]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Depending on the programs we use to import CSVs from PrestaShop, it is necessary to have a CSV file with or without header. Currently, the file created by the SQL manager is always headered.

### Describe the solution you'd like

An option to have the headers or not in the CSV file : "Export column header"

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by AureRita** [comment]
Hi @d33x , 

Thank you for your feature ! 
This feature seems to be the same of this feature #28073 
This feature is corrected by this PR #28072 
Can you say me if it's the same result wanted ? 

Thanks

**Comment by d33x** [comment]
@AureRita The wanted result seems to be the same but this RP only seems to introduce this possibility into the core. This option should now be added in the BO

**Comment by AureRita** [comment]
@d33x This feature is implemented in the next major version 8.0.0.
To be informed when it's released, please subscribe to this issue #26427 
Closing the issue as it's fixed! 

Thank you for your understanding and your patience

**Comment by AureRita** [comment]
Duplicate of #28073
