### ISSUE TITLE
SQL Manager - Automatically executes the query (via CRON) and sends the file to an FTP or available via a URL.

### ISSUE THREAD

**Issue by d33x** [PrestaShop/PrestaShop#28735]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

In some cases, it is interesting to be able to execute a SQL query every night and retrieve it for processing (statistics, etc.) without giving direct access to the database.

Currently this is impossible and all these actions have to be done manually.

### Describe the solution you'd like

- Be able to automatically execute the SQL query at a given time (or give the possibility to call it via an external CRON task)
- Send the previously called output file to an FTP server or make it available online for calling (e.g. fopen)

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by matks** [comment]
Hello @d33x that is an interesting idea but I think this is a usecase very specific that only a small number of prestashop users would find useful 😅 . It could be a nice idea for a module 😉 ?

**Comment by AureRita** [comment]
Hi @d33x 
Thank you for your suggestion. The Product Team will take it into consideration for future developments.

Please be aware that there is no guarantee that this feature will be developed anytime soon.
Waiting for your design/assets :rocket: 

Thank you

**Comment by Hlavtox** [comment]
Hi @d33x, this is very custom functionality and I think it should not be included in the core. You can easily program something like this yourself. cron.php:

```
require_once "config/settings.inc.php";
require_once "config/config.inc.php";
require_once "init.php";

file_put_contents('export.csv', 'Name;\r\n');
$data = Db::getInstance()->ExecuteS('SELECT * FROM ' . _DB_PREFIX_ . 'product;');
foreach ($data as $row) {
   file_put_contents('export.csv', $row['name] . ';\r\n', FILE_APPEND);
}
echo 'Export finished';
```

**Comment by matks** [comment]
Closing as @Hlavtox has the same opinion and provided a great answer
