### ISSUE TITLE
[WS] Handle PATCH requests for attachments

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#28748]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

> Originaly posted by @khouloudbelguith here https://github.com/PrestaShop/autoupgrade/pull/479#pullrequestreview-1004678171

Following the merge of https://github.com/PrestaShop/PrestaShop/pull/27952 it is now possible to use PATCH for API calls.
But when we try to update an attachment (= attached file) with PATCH method, the file is not updated.

PR https://github.com/PrestaShop/PrestaShop/pull/28747 fixes the problem

Attachments are files a user can upload to prestashop.

https://user-images.githubusercontent.com/16067358/173408235-586e989d-3fa5-4ac0-87b4-8456cc030f34.mp4

### Expected behavior

POST and PUT methods work as expected, so when using PATCH http method with the webservice to update an attachment, the file should be correctly updated.

### Steps to reproduce

1. Go to BO > Catalog > Files > Add a new file with type jpeg for example
2. Go to BO > Advanced Parameters > Webservice page & select Patch for the attachment
3. Using postman, I tried to update the attachment with the Patch method
4. See error > the file is not updated

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.2

**Comment by matks** [comment]
Note: when this topic is fixed, PR https://github.com/PrestaShop/autoupgrade/pull/479 can be tested again and hopefully validated

**Comment by matks** [comment]
After exploring with @khouloudbelguith the topic here are the usecases that are implemented (and work as expected on branch 8.0.x) and the ones that need to be fixed:

# API endpoint /api/attachments/file

Note: Attachments are a MySQL entity (= line in a SQL table) that is linked to a file on disk

This endpoint allows to modify the _file on the disk_ and the relation between the MySQL entity and the file.

## GET /api/attachments/file/{id} is working ✅  it returns the Attachment file

See Postman test

![Capture d’écran 2022-09-14 à 17 30 32](https://user-images.githubusercontent.com/3830050/190198216-d2dd85da-6baa-4a18-a82a-9407af0e5a2f.png)

## POST /api/attachments/file/ is working ✅ it creates a new Attachment file

See Postman test

![Capture d’écran 2022-09-14 à 17 29 54](https://user-images.githubusercontent.com/3830050/190198295-001babb3-7105-430d-b934-f819be123f8d.png)

## PUT /api/attachments/file/{id} is working ✅ it allows to update an Attachment file already existing

![Capture d’écran 2022-09-14 à 17 30 50](https://user-images.githubusercontent.com/3830050/190198340-4eef2a21-6095-4592-8165-b2f478bc6ff9.png)

## PATCH /api/attachments/file/{id} is NOT working 🔴  

The file is on updated. See Postman test

![Capture d’écran 2022-09-14 à 17 34 01](https://user-images.githubusercontent.com/3830050/190198834-a326073a-4550-4721-b627-7de2fb96426a.png)

# API endpoint /api/attachments/{id}

This endpoint allows to modify the _Attachment_, not the file on the disk.

## DELETE /api/attachments/{id} is working ✅ it allows to delete the Attachment

![Capture d’écran 2022-09-14 à 18 10 35](https://user-images.githubusercontent.com/3830050/190206737-567246c5-e957-4369-b832-c492dfd6bc45.png)

**Comment by matks** [comment]
There is another endpoint that allow Webservice to modify PrestaShop files on disk:

# API endpoint /api/images/products/{product_id}/{combination_id}

This endpoint allows to modify images linked to a product. On 8.0.x this endpoint supports GET and POST

## GET /api/images/products/{product_id}/{combination_id} is working ✅ it returns the product image for the given combination

![Capture d’écran 2022-09-14 à 17 38 54](https://user-images.githubusercontent.com/3830050/190200542-48c3b521-8f1f-440e-aa68-42dd98479722.png)

## POST /api/images/products/{product_id}/ is working ✅ it allows to upload and link another image to a given combination

![Capture d’écran 2022-09-14 à 17 41 25](https://user-images.githubusercontent.com/3830050/190200580-9756bc0f-90f6-4e12-97e2-5ddf87e252b9.png)

## PUT and PATCH are not supported for this endpoint

I checked the code and the class in charge of this endpoint as been implemented to rely only on $_FILES which does not work for PUT and PATCH.

Implementing PUT (and PATCH) for this endpoints would be a new feature.

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29638
