### ISSUE TITLE
Attempted to load class "Zxcvbn" from namespace "ZxcvbnPhp".

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#28744]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

<img width="1150" alt="Capture d’écran 2022-06-13 à 19 37 42" src="https://user-images.githubusercontent.com/2631425/173412041-31fd0ede-e9c7-4480-ab99-b9434a3deb1f.png">

### Steps to reproduce

1. Try to (re-)install your shop

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by hibatallahAouadni** [comment]
@PrestaEdit Related to your overrides?

**Comment by PrestaEdit** [comment]
@hibatallahAouadni Don't know exctly, I use the 8.0.x branch and maybe I wasn't up-to-date.
Composer update and trying to re-install was good for me, so I assume it's an invalid issue, yes ;-)

**Comment by hibatallahAouadni** [comment]
Thanks for your feedback!
