### ISSUE TITLE
Allow to translate placeholder in create account section ( DD/MM/YYYY )

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#28742]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Allow DD/MM/YY placeholder translation 

### Describe the solution you'd like

Allow DD/MM/YY placeholder translation for customer creation

### Additional context

![image](https://user-images.githubusercontent.com/23308427/173528839-1716dd75-9523-4a7b-8264-4349033e7f77.png)

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by ghost** [comment]
Like this : https://www.prestashop.com/forums/topic/1065067-besoin-daide-pour-modifier-ddmmyyyy-par-d%C3%A9faut-dans-le-champ-date-de-naissance-du-formulaire-dinscription/

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

I think you mean "JJ/MM/AAAA" :wink: cause "DD/MM/JJJJ" has no meaning :sweat_smile: 

![image](https://user-images.githubusercontent.com/23308427/173526526-96760dac-6996-4643-920d-0829fe223d5a.png)

Changing your screenshot by this one :wink: 

![image](https://user-images.githubusercontent.com/23308427/173528691-cff240c9-a4e9-42d2-afd6-94742bfa2537.png)

Thank you for your suggestion and your PR. 
The Product Team will take it into consideration for future developments. 

Thank you

**Comment by ghost** [comment]
Thank you @hibatallahAouadni  :) 

Are you ready i am back ! :baby_bottle: done !

**Comment by MatShir** [comment]
Thanks @okom3pom 👌
