### ISSUE TITLE
Pdf generator (print line with error)

### ISSUE THREAD

**Issue by Borgas** [PrestaShop/PrestaShop#28753]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Product with combinations, when pdf is generated (invoice or delivery note) the description shows "pdf" text in product line

![Capturar](https://user-images.githubusercontent.com/54105234/173695591-e31e9ff2-4e3b-4a0f-b588-47ed503ea481.PNG)

![Capturar](https://user-images.githubusercontent.com/54105234/173695701-aec98b19-7264-4fab-84dc-a7df3fa2b8db.PNG)

### Steps to reproduce

1. Language pt-PT only
2. Create product with combination
3. Create order
4. See product line in order
5. See Invoice pdf or Delivery Note pdf

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4.29

**Comment by Borgas** [comment]
I think is a translation issue, but after change translation from "Pdf" to ":" it didn´t solve the issue

![Capturar](https://user-images.githubusercontent.com/54105234/173696704-51447057-c71a-441d-9898-1f522ffb4000.PNG)

**Comment by hibatallahAouadni** [comment]
Hello @Borgas 

I didn't manage to reproduce the issue with PS1783, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/173816935-96b56b60-a17f-4015-b6b6-8352fb4d6808.mp4

Please check and feedback.

Thanks!

**Comment by Borgas** [comment]
![1](https://user-images.githubusercontent.com/54105234/173822017-61a980ec-453d-4448-9ba2-434c07abcb37.PNG)
![2](https://user-images.githubusercontent.com/54105234/173822021-cd770323-1492-4225-9933-4dc56c795c8d.PNG)


> Hello @Borgas
> 
> I didn't manage to reproduce the issue with PS1783, see the attached screen record below:
> issue_28753.mp4
> 
> Please check and feedback.
> 
> Thanks!

Product much have combinations, in your test seems it doesn´t have, i´m i correct?

Thank you

**Comment by hibatallahAouadni** [comment]
Hello @Borgas 

> Product much have combinations, in your test seems it doesn´t have, i´m i correct?

The product has combinations, check the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/173843040-430ec575-99b0-4d5b-ade6-e2ba658e1124.png)

Waiting for your feedback.

Thanks!

**Comment by Borgas** [comment]
Can you test with 2 attributes?

Size and color?

**Comment by hibatallahAouadni** [comment]
Hello @Borgas 

Even with 2 attributes, I didn't reproduce the issue, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/173886494-87034405-f172-409a-bbec-b91a38442211.mp4

Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Borgas 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
