### ISSUE TITLE
PaymentModule::validateOrder - Secure key does not match (no MailChimp)

### ISSUE THREAD

**Issue by nmacfarlane-montonio** [PrestaShop/PrestaShop#28754]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This is an occasional error that occurs when a customer pays for an order, but an error occurs in PrestaShop and it fails to register the payment and mark the order paid, although payment is received.

I have seen similar reports such as https://github.com/PrestaShop/PrestaShop/issues/21871 that have been closed with the reasoning "this is an addon problem", in regards to MailChimp, but this store isn't using MailChimp, so please consider looking into this as a core PrestaShop issue - I can google and find tons of references to this error, but no solutions from your team that I've been able to find except "don't use plugins", which to me reads more like "don't use PrestaShop, because we aren't going to fix this". Help me, help you. :smi

![cart errors aiakaup](https://user-images.githubusercontent.com/102951001/173756714-7d6e9938-868c-4768-98a8-5a0f51f26aab.png)

### Expected behavior

I expect PrestaShop to process the payment properly, and mark the order paid, when a customer successfully pays for an order.

This is happening most of the time, but shouldn't be randomly failing to happen, as it is at this time.

### Steps to reproduce

If you can tell me how to reproduce this, maybe I can figure out how to never reproduce it again, all I know is it looks random from my perspective.

### PrestaShop version(s) where the bug happened

1.7.8.2

**Comment by hibatallahAouadni** [comment]
Hello @nmacfarlane-montonio 

I can see you're frustrated, but how can I help you if you don't provide more infos :thinking: 
Well, could you please provide: 

- the payment module that I use to encounter this issue, 
- your PHP version,
- did you override the payment controller? 

> but an error occurs in PrestaShop and it fails to register the payment and mark the order paid, although payment is received.

You mean that in **BO**>**SELL**>**Orders**, the status of order is `payment accepted` and yet you didn't receive any payment in your banck account, is that so?
Waiting for your feedback.

Thanks!

**Comment by Hlavtox** [comment]
Never seen this error in 7 years of using prestashop. I think it's a module that's causing this.

**Comment by matks** [comment]
> I have seen similar reports such as #21871 that have been closed with the reasoning "this is an addon problem", in regards to MailChimp, but this store isn't using MailChimp, so please consider looking into this as a core PrestaShop issue - I can google and find tons of references to this error, but no solutions from your team that I've been able to find except "don't use plugins", which to me reads more like "don't use PrestaShop, because we aren't going to fix this". Help me, help you.

Even if this store is not using MailChimp, error can come from wrong server configuration, from wrong module or theme installed, or wrong usage.

I confirm we are not going to fix an error that we cannot understand. Nobody can. You can try to hire anybody - agency, freelance, big tech company, if they cannot understand the exact circumstances that allow the error to happen, they cannot fix it.

**Comment by nmacfarlane-montonio** [comment]
Apologies if my issue statement was not clear enough.

In my searching, I've found multiple modules mentioned as being the "cause" of this issue, which I shall try to describe more clearly:

Payment is received, in the bank, but the order is not completed because of this error occurring when the module is trying to notify prestashop that the payment is completed.

I assume this is possible with any plug-in that tries to send such a message to prestashop, so my question is, what can be done, from your side or ours, to help ensure the overall stability of this process, or that we have matching keys on both sides of the exchange?

**Comment by sLorenzini** [comment]
Hello @nmacfarlane-montonio ,

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template and provide clear and concise steps to reproduce the bug**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/).

We need more details on "Steps to reproduce" part. Could you also provide us a screen record to see on your shop this issue please?

Thank you

**Comment by hibatallahAouadni** [comment]
Hello @nmacfarlane-montonio 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by bibos** [comment]
Same problem here...

Customers are using "Prestashop Checkout" to pay with Paypal.
The payment is accepted with Paypal (they receive a confirmation by mail), but then it tries to reach back Prestashop, and there's just a blank page. (so the customer tries again... and again...)

In the PS logs, I have the "PaymentModule::validateOrder - Secure key does not match" error, and the order is not validated.

**Comment by Matt75** [comment]
It can happen when Cookie SameSite is not set to None.

Since the default value changes to Lax in recent web browsers, it can happen sometime when customer is redirected from payment gateway to the shop, the PrestaShop cookie cannot be used due to SameSite value so the Context cannot be initialized with values from cookie, so customer is considered as guest with a different SecureKey.

So it's recommended to set the Cookie SameSite to None instead of Lax when customers may be redirect from external services to your shop to avoid a wrong Context initialization.

Since PrestaShop 1.7.8, merchant can configure it from BO > Advanced settings > Administration > Cookie SameSite

Before an override is needed ; there also some modules on PrestaShop Addons to add this settings on oldest PrestaShop versions.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by bibos** [comment]
Thanks for you answer.
I'm on PS 1.7.6.7, so I would have to install a module for that...

Before I do this, would the problem also be solved if I uncheck "Check the cookies IP address" in the Administration section?
(not a good solution, but to be sure that's the reason of my problem...)

**Comment by Matt75** [comment]
> would the problem also be solved if I uncheck "Check the cookies IP address" in the Administration section?

No this settings is not linked to Cookie SameSite policy.

You can also try to add this line at the end of the .htaccess file at the root of PrestaShop:
```
Header always edit Set-Cookie (.*) "$1; SameSite=None; Secure"
```

**Comment by bibos** [comment]
Thanks, I try!

**Comment by bibos** [comment]
It seems this line didn't solve my problem. 
I'm gonna try to install this module: https://addons.prestashop.com/fr/legislation/50917-cookie-samesite.html#overview

**Comment by bibos** [comment]
Although when I test my website here: https://geekflare.com/tools/secure-cookie-test

It seems the "Samesite=None" configuration is well set...

**Comment by JanMikes** [comment]
Hi, i have faced exactly the same error while creating orders via API.

My problem was that i was creating cart without id_customer. When added id_customer field to the create cart request and the id matched id_customer of the order creating, the problem was gone. Hopefully this might be helpful info for you.

**Comment by matteolavaggi** [comment]
Maybe part of the problem is that the log recorded from prestashop is useless? There is no trace on what generate the error, when and why ^^
