### ISSUE TITLE
Hiding unknown accounts

### ISSUE THREAD

**Issue by Kaikina** [PrestaShop/PrestaShop#28758]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Upon trying to login to the backoffice with incorrect credentials, you get this error message : 

> The employee does not exist, or the password provided is incorrect.

Upon trying to reset the password for a non-existing frontoffice account email, you get this message :

> If this email address has been registered in our shop, you will receive a link to reset your password at %email%.

Both of these do not disclose information about whether the email or the password is incorrect. However, upon trying to recover the password of a non-existing backoffice account email, you get the following error message : 

> This account does not exist.

This error message reveals that this email is not registered in the database. Therefore, an existing email will show this message : 

> Please, check your mailbox. A link to reset your password has been sent to you.

Indicating that this time, the email exists. 

### Describe the solution you'd like

Showing or not that an email exists in the database is arguable. It is a constant fight between developers securities preocupations and UX preocupations. 
However, for the sake of homogeneity, as the other error messages hide this information, and that we are talking about backoffice accounts, I'd suggest to use an error message that, as the frontoffice recovery message does, hides the fact that the email is registered or not.

**Comment by matks** [comment]
Thank you @Kaikina this is a great bug report 👍

**Comment by hibatallahAouadni** [comment]
Hello @Kaikina 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by matks** [comment]
> Showing or not that an email exists in the database is arguable. It is a constant fight between developers securities preocupations and UX preocupations.

At PrestaShop, security matters are more important that UX subjects. As a CMS our top priority is security.

However @Kaikina I just tested on 1.7.8.6 and I have the same error message if I input a valid existing email and an email that do not exist: "If this email address has been registered in our shop, you will receive a link to reset your password at .... "

![Capture d’écran 2022-06-15 à 16 46 12](https://user-images.githubusercontent.com/3830050/173856547-03abcf2b-1e39-417b-970a-263eee154d03.png)

**Comment by ghost** [comment]
Hi, 

With 8.0.0  : 

![Screenshot (24)](https://user-images.githubusercontent.com/5064590/174009188-15e11cb7-95cf-4220-9a06-34087f1b0184.png)

With 1.7.8.3 : 

![Screenshot (25)](https://user-images.githubusercontent.com/5064590/174009444-5f78db40-db8b-403d-b0bf-aa8a67556913.png)

Nice catch

**Comment by matks** [comment]
@okom3pom I do not understand your report.

I just checked 8.0.0 : same behavior as I just saw. Are you sure you are using the latest version of the branch?

For me
- check on 1.7.8.6 : I have the same error message if I input a valid existing email and an email that do not exist: "If this email address has been registered in our shop, you will receive a link to reset your password at .... "
- check on 8.0.0 : I have the same error message if I input a valid existing email and an email that do not exist: "If this email address has been registered in our shop, you will receive a link to reset your password at .... "

Both are shops I just installed and I selected English language

**Comment by ghost** [comment]
I think @Kaikina is talking about the back office password request.

Otherwise I don't understand

**Comment by matks** [comment]
Haaaa 😄 got it

> However, for the sake of homogeneity, as the other error messages hide this information, and that we are talking about backoffice accounts, I'd suggest to use an error message that, as the frontoffice recovery message does, hides the fact that the email is registered or not.

For back-office, which is supposed to be a secure area (even the login page) the security matter is not as strong then. So i guess it's a question for @PrestaShop/product-team 👍

**Comment by ghost** [comment]
It adds a little more security.

**Comment by ghost** [comment]
There have been leaks from the admin directory in the past.

In PrestaShop or in modules

**Comment by Kaikina** [comment]
Yes exactly. I'm talking about the backoffice password recovery page.

**Comment by ghost** [comment]
You should be able to make a PR for it, it's just a text to change.

https://devdocs.prestashop.com/8/contribute/

If you can't do it, I can.
