### ISSUE TITLE
BO - An exception is thrown when import a file with non .csv extension and download the csv created file 

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#28761]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An exception is thrown when import a file with non .csv extension and download the csv created file 

![image](https://user-images.githubusercontent.com/92912932/173855473-29f89ad2-c1cf-4d65-b09c-15f8badaa263.png)
 1786 and 1778 

Uploading exception when download csv file .mp4…

### Expected behavior

Only the uploaded files by the user are listed in the 'Choose from history / FTP'. 
The files generated from the import system are not listed in the 'Choose from history / FTP' and can't be downloadable.

### Steps to reproduce

1. Go to CONFIGURE > Advanced Parameters > Import
2. Choose a **non .csv** (eg.odt, xsl, xlst, etc) file by clicking in select a file to import 
3. Click on Next step
4. Click on Cancel
5. See in Choose from history / FTP that a csv file is created
6. Click to download it 
7. See error > Exception

### PrestaShop version(s) where the bug happened

1.7.7.8 & develop & 1.7.8.6

### PHP version(s) where the bug happened

7.4 / 7.2

**Comment by MatShir** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29647
