### ISSUE TITLE
[PHP Unknown error #8192] array_key_exists() when using postman to access webservice api

### ISSUE THREAD

**Issue by Tashsub** [PrestaShop/PrestaShop#28765]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I am trying to get all my customers and their details such as first name, last name etc.. 

Using this in Postman

http://storename/api/customers?display=full&ws_key=APIKEY

However, I get the following error: 

`"errors": [
        {
            "code": 15,
            "message": "[PHP Unknown error #8192] array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead (/home/eamonnf/public_html/presta/src/Adapter/EntityMapper.php, line 99)"
        },`

When I run the following http://storename/api/customers, I get the below

`{
    "customers": [
        {
            "id": 1
        },
        {
            "id": 2
        },
        {
            "id": 4
        }
    ]
}`

The above seems to work 

I am authenticating to my store using ws_key = API Key in the Authorization tab in Postman.  

### Expected behavior

Display the customer details, I'd like to be able to get all customers and their relevant details such as name, address etc... 

### Steps to reproduce

Go to Postman 

Create request with http://storename/api/customers?display=full&ws_key=APIKey

### PrestaShop version(s) where the bug happened

1.7.74

### PHP version(s) where the bug happened

7.4.19

**Comment by sLorenzini** [comment]
Hello @Tashsub,

I can't reproduce your issue on ps 1.7.7.7 version.
Here's my screenshot:

on the BO:
![image (1)](https://user-images.githubusercontent.com/2854834/174082658-206db2aa-fc7d-45fe-9414-7006a60e0760.png)

on postman:
![image](https://user-images.githubusercontent.com/2854834/174082717-4eae94e8-68f7-411e-a4e6-5f027ddc0b78.png)


Can you provide us more details & a screen record  please?

Thanks

**Comment by Tashsub** [comment]
Hi, Thanks for the response @sLorenzini 

Sorry made a mistake in my original issue. I am using PrestaShop Version 1.7.7.4 if that helps.

I have gone into my backoffice and made sure the API key is allowed to access the right permissions. 
![Capture4](https://user-images.githubusercontent.com/44523844/174086387-77c5b3cc-b264-465a-ab9f-cbc4bf4fa766.PNG)

I then tested it using just the customers endpoint
![Capture3](https://user-images.githubusercontent.com/44523844/174086614-b1ea11a6-337b-4e22-9f18-75325f9c56bb.PNG)

But does not work with display=full

![Capture2](https://user-images.githubusercontent.com/44523844/174086675-bc8a71e9-b3b0-45be-82a5-a77cdd020de6.PNG)

Authentication is as follows: 
![au](https://user-images.githubusercontent.com/44523844/174087355-51d2a2a2-40a8-42fe-a03b-6d37c0a4d783.PNG)

**Comment by sLorenzini** [comment]
hello @Tashsub,

Thank you for your answer.
Could you please provide a screenshot of your Key in BO, and could you please use the Basic auth?

Here's my screenshots: 
![image](https://user-images.githubusercontent.com/2854834/174102823-6b691876-5c4c-4165-9dc3-ae1f068210a1.png)
![image (1)](https://user-images.githubusercontent.com/2854834/174102855-50c7bf35-198b-4e91-b221-1d360353ffcb.png)


Even when I use the output-format:JSON, I still haven't reproduced the issue.
![image (2)](https://user-images.githubusercontent.com/2854834/174102802-95e07d17-92ef-4502-b6a1-8d93ee9ab763.png)

Waiting for your feedbacks.

Thanks

**Comment by Tashsub** [comment]
Hi @sLorenzini , 

When I use basic auth it does not allow me to connect to my store. I get the following error. 

![BasicAuth-prop](https://user-images.githubusercontent.com/44523844/174106115-58162b1e-11c4-469a-8c39-16a64726675f.PNG)


![BasicAuth2Error](https://user-images.githubusercontent.com/44523844/174105359-3a816b64-2e78-4248-8a0d-039a4b3ad80a.PNG)

BO

![bo-key](https://user-images.githubusercontent.com/44523844/174105770-0eb24693-724b-48a4-92db-48369fb412e3.PNG)

**Comment by hibatallahAouadni** [comment]
Hello @Tashsub 

> When I use basic auth it does not allow me to connect to my store. I get the following error.

Because you need to put your **Key description** "Test Key" in the **Password** field.
Try again and check. Waiting for your feedback.

Thanks!

**Comment by Tashsub** [comment]
Hi @hibatallahAouadni , 

That does not work either? I am still getting 401 Unauthorized

![testkey](https://user-images.githubusercontent.com/44523844/174113437-9086d268-dcb5-4c0c-8b4e-40160e03ea5d.PNG)

**Comment by Sasni** [comment]
Hi, Prestashop 1.7.7.x does not support PHP 7.4 Look at -> https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-requirements
try to change PHP to 7.3 

notwithstanding the above I confirm the problem on (old) version 1.7.7.0 with PHP: 7.3.33
![image](https://user-images.githubusercontent.com/3370929/174404682-239b76c8-8db3-4d80-bf67-fad3c4755ac2.png)

i can't reproduce issue on ps 1.7.8.5 and 1.7.8.6
screen with JSON format
![image](https://user-images.githubusercontent.com/3370929/174403174-5d74d9f8-7913-4b83-b071-8f1ff6267047.png)
and whidout
![image](https://user-images.githubusercontent.com/3370929/174403497-f3a0350c-3b97-408c-8afd-ce3ad170cece.png)
All works fine... 

PS. No password required
Basic realm="Welcome to PrestaShop Webservice, please enter the authentication key as the login. **No password required.**"

in file /src/Adapter/EntityMapper.php i have this lines (ps 1.7.8.6): 
```
/**
 * Not used in PrestaShop core, only in tests.
 *
 * @deprecated since 1.7.5, to be removed in 1.8
 */
```
what does it mean? 
Not used in PrestaShop core, but i cant delete/rename this file 
I opened version 8 and there is still that file. Hmmm...

**Comment by Tashsub** [comment]
@Sasni 

Thanks for the reply. I will try your suggested advice. 👍

**Comment by Tashsub** [comment]
Hi @Sasni  @sLorenzini 

When installing PrestaShop as a new customer it appears that the PrestaShop version will be 1.7.8.6. 

But what will my PHP version be? Any Ideas?

**Comment by Sasni** [comment]
@Tashsub all requirements - including the current PHP version you can check with this tool:  [https://github.com/PrestaShop/php-ps-info](https://github.com/PrestaShop/php-ps-info)
You will change the PHP version on the server. You can do it yourself (as long as you have access to the hosting/VPS configuration) or ask the administrator to do it.

**Comment by AureRita** [comment]
Hi @Tashsub  ,

To see your php version on your terminal, you can write : php -v 
If you want to see your php version on prestashop, go to BO > Advanced Parameters > Information 
If you want to continue with PrestaShop 1.7.7.7 you need to downgrade your PHP version to 7.3 cause PHP 7.4 is not compatible with PS1777 (see our [system requirements](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-requirements))
Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you
