### ISSUE TITLE
In multistore mode, a product present in the two stores that have different combinations generates errors.

### ISSUE THREAD

**Issue by julien-23juin** [PrestaShop/PrestaShop#28773]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

_Context :_

_Shop A and Shop B.
Product 1 in shop A and B.
Combination 1 in product 1 in store A only
Combination 2 in product 1 in store B only_

**The first error:**
If we go to the product sheet in all stores mode, the list of combinations is not displayed and generates a 500 xhr error.
After research it tries to load the combination in the wrong shop, this does not return the combination and generates an error:

![image](https://user-images.githubusercontent.com/80478742/174127849-b4f04528-8bbe-498e-9bfc-dc7c8ed3d989.png)

**The second error:**
When saving the product, as the combinations are different between store A and B, it is possible to define the default combination. But this generates a 500 xhr error because it also tries to save the default_on in the product_attribute table instead of doing it only in product_attribute_shop so it generates an SQL error:

![image](https://user-images.githubusercontent.com/80478742/174128011-450bac27-3d4b-4977-9854-995fdc9db491.png)

Constraint in the product_attribute database :
![image](https://user-images.githubusercontent.com/80478742/174126736-edee1863-3a42-4b2a-8448-73a88e9fe43f.png)

### Steps to reproduce

1. Create two shops
2. Create a product available for both stores (same product ID)
3. Create a combination of this product on the first store and a second on the second store.
4. Save the product in both stores

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment]
Hello @julien-23juin ,

I can't reproduce your issue on PS 1.7.8.x.

In All shop context, I have both my combinations :
<img width="1231" alt="Screenshot 2022-06-17 at 10 04 40" src="https://user-images.githubusercontent.com/16019289/174255293-436670ed-8e5f-41e7-8e9b-0583a2739d6e.png">

In shop 1 :
<img width="1239" alt="Screenshot 2022-06-17 at 10 05 04" src="https://user-images.githubusercontent.com/16019289/174255348-e2198d36-810c-4520-8b24-b7de431c9915.png">

In shop 2 :
<img width="1237" alt="Screenshot 2022-06-17 at 10 05 14" src="https://user-images.githubusercontent.com/16019289/174255357-d450884d-b8d8-4cb0-acd9-ee121e798f37.png">

And in the default group :
<img width="1199" alt="Screenshot 2022-06-17 at 10 05 35" src="https://user-images.githubusercontent.com/16019289/174255400-39cd37ba-1d58-40fc-b498-cf809ca1023f.png">

I have no exception in BO nor in FO.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by julien-23juin** [comment]
Hello,

In shop2, can you select in Color - pink "default combination" and save?

On which version of prestashop 1.7.8 did you do the test please?
