### ISSUE TITLE
BO - The feature associated to one shop is displayed for all other shops 

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#28770]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When multistore is enabled, The feature which is associated to one shop is displayed for all other shops 

**8.0.x :** NOK :x: 

https://user-images.githubusercontent.com/92912932/174084766-5a293ebc-4f54-4de9-ada6-4cdd0439af2c.mp4

Impact of the issue : 

Case 1 : When delete the Feature which is associated to all shops, it still displayed in the list of the deleted shop (cause it's associated to the other shops)

Case 2 : When delete the Feature which is associated to one shop, it still displayed in the list (cause it's associated to the other shops)

https://user-images.githubusercontent.com/92912932/174084528-b1e1d915-aa5d-4443-b514-14ca1880aefd.mp4

**1786 :** OK :heavy_check_mark: 

https://user-images.githubusercontent.com/92912932/174085629-6a5f0633-99bf-4844-a3f1-4bf27235bf72.mp4

### Expected behavior

The same behavior of 1786 

### Steps to reproduce

1. Enable multistore
2. Create a new shop
3. Go to SELL > Catalog > Attributes & Features > Features
4. Create a feature for the new shop created and save
6. See error >> Check that this Feature is displayed on all other shops

**Impact :** 

_Case 1 :_ 
1. Enable multistore
2. Create a new shop
3. Go to SELL > Catalog > Attributes & Features > Features
5. Add a new feature and select one shop to associate it and Save
7. Click to delete the feature
8. See Error > The feature is still displayed in the list

_Case 2 :_ 
1. Enable multistore
2. Create a new shop
3. Go to SELL > Catalog > Attributes & Features > Features
5. Add a new feature and select all created shops and Save
6. Select any shop
7. Click to delete the feature
9. See Error > The feature is still displayed in the list 

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.4 & 7.2

**Comment by MeKeyCool** [comment]
@HanaRebaiQA , in found that Attributes tab works in the same way.

The delete problem is due to shop association. To be allowed to remove an item (Feature or Attributes), you need to unlink it with every shop.

Then the expected behavior would be : 
- See list of attributes/features associated to current observed shop/group
- When we try to delete a(n) attribute/feature, we should see an explicit error message if it is associated to a shop.

**Comment by HanaRebaiQA** [comment]
Hello @MeKeyCool 

I think everything is good now on your side following our discussion on slack ?

Thanks!

**Comment by MeKeyCool** [comment]
Yes @HanaRebaiQA , thanks for your time.

As explained in #28930 , I found the solution ^^

**Comment by HanaRebaiQA** [comment]
You are welcome @MeKeyCool :)
