### ISSUE TITLE
BO - Display error on modal "add new specific price" in product page V2

### ISSUE THREAD

**Issue by sLorenzini** [PrestaShop/PrestaShop#28778]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Two display errors on "Add new specific price" modal in BO on product page V2.

- The the loader block at the beginning of "Add new specific price" modal is a bit too long on the right:

![pp2-loader-specific-price-long](https://user-images.githubusercontent.com/2854834/174273198-5855978e-51f9-4a54-b362-a3c30046e03b.png)

- The succes alert when we save a specific price has no left/right margin:

![pp2-success-alert-modal-specific-price](https://user-images.githubusercontent.com/2854834/174273506-48d712b3-7822-4fec-b951-d6556213cde5.png)

It should be like  the error alert:

![pp2-error-alert-specificprice-modal](https://user-images.githubusercontent.com/2854834/174273535-fa1b2769-8d66-4320-93b0-5db79e403c97.png)

### Expected behavior

- Reduce the width loader block
- Add left/right margins on success alert

### Steps to reproduce

- Go to BO >  Advanced Parameters > New & Experimental Features
- Set to "Enabled" the "New product page - Single store" switch button > Save
- Go to Catalog > choose a product > Pricing tab 

**_Loader case_**
- Click on Add a specific price button in Pricing tab > Modal is displayed
- See error with the loader on the modal

**_Succes alert case_**
- Click on Add a specific price button in Pricing tab > Modal is displayed
- Go to "Impact on price" block at the bottom of the modal
- Set to yes the "Set specific price" switch button for example
- Add a number on the field below 
- Click on "Save and publish" button
- See the error of the alert success on the top

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.2

**Comment by florine2623** [comment]
This has been fixed on develop branch.

Loader :
<img width="835" alt="Screenshot 2023-03-09 at 14 11 54" src="https://user-images.githubusercontent.com/16019289/224033832-b766226f-0f55-4760-bb37-e3d9805b8d11.png">

Successful message :
<img width="821" alt="Screenshot 2023-03-09 at 14 11 46" src="https://user-images.githubusercontent.com/16019289/224033759-29a13d65-a86f-45b6-b46a-926cf15890f9.png">
