### ISSUE TITLE
Error with connection when running console command (docker)

### ISSUE THREAD

**Issue by bastien70** [PrestaShop/PrestaShop#28775]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I'm using docker mysql container to dev into a prestashop project.
No problem for initialize prestashop, the connection is OK.
But if I launch the terminal and use by example : `php bin/console doctrine:schema:update --dump-sql` (or just `php bin/console`), I've the following error :

```bash
PrestaShopException in /mnt/E2CA5E15CA5DE677/Prestashop/opera/prestashop/classes/db/DbPDO.php line 136
#0 /mnt/E2CA5E15CA5DE677/Prestashop/opera/prestashop/classes/db/Db.php(330): DbPDOCore->connect()
#1 /mnt/E2CA5E15CA5DE677/Prestashop/opera/prestashop/classes/db/Db.php(241): DbCore->__construct()
#2 /mnt/E2CA5E15CA5DE677/Prestashop/opera/prestashop/config/alias.php(47): DbCore::getInstance()
#3 /mnt/E2CA5E15CA5DE677/Prestashop/opera/prestashop/classes/shop/Shop.php(1345): pSQL()
#4 /mnt/E2CA5E15CA5DE677/Prestashop/opera/prestashop/classes/shop/Shop.php(341): ShopCore::findShopByHost()
#5 /mnt/E2CA5E15CA5DE677/Prestashop/opera/prestashop/config/config.inc.php(128): ShopCore::initialize()
#6 /mnt/E2CA5E15CA5DE677/Prestashop/opera/prestashop/bin/console(15): require_once('...')
#7 {main}
```

### Steps to reproduce

1. Create prestashop project with docker (prestashop, mysql, phpmyadmin)
2. Init the project
3. Run a php console command

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4.28

**Comment by florine2623** [comment]
Hello @bastien70 ,

I can't reproduce your issue.

Here are the steps I followed :
- create PrestaShop project with Docker
- install my shop
- open Terminal from Docker
- go into my shop folder
- launch `php bin/console doctrine:schema:update --dump-sql` and `php bin/console`
- here's the result :
<img width="1283" alt="Screenshot 2022-06-17 at 12 24 51" src="https://user-images.githubusercontent.com/16019289/174280270-feead811-98b7-4b0e-a314-8f67a80fe77f.png">

Can you send a screen record so we can see exactly what is happening ?

Thanks!

**Comment by bastien70** [comment]
Hello @florine2623 , for docker, do you installed the mysql container too ?

This is my screen records : 



https://user-images.githubusercontent.com/53140475/174285311-aa5e57ec-dc65-45a8-bcc1-788c061e79e8.mp4


Now if I run the command `php bin/console` I've this : 

```bash
PrestaShopException in /mnt/E2CA5E15CA5DE677/Prestashop/opera/prestashop/classes/db/DbPDO.php line 136
#0 /mnt/E2CA5E15CA5DE677/Prestashop/opera/prestashop/classes/db/Db.php(330): DbPDOCore->connect()
#1 /mnt/E2CA5E15CA5DE677/Prestashop/opera/prestashop/classes/db/Db.php(241): DbCore->__construct('mysql', 'root', 'prestashop', 'prestashop')
```

So it tries to connect to my docker mysql container database but it can't

**Comment by florine2623** [comment]
Thanks for the screen record.

On my end, I'm using mariadb ^^. Please take a look :

https://user-images.githubusercontent.com/16019289/174325172-5e9f31ac-5bb4-4091-af03-1bb6e48d1dbb.mov

The problem only comes with mysql ?

**Comment by bastien70** [comment]
> Thanks for the screen record.
> 
> On my end, I'm using mariadb ^^. Please take a look :
> 
>  Screen.Recording.2022-06-17.at.17.05.14.mov 
> The problem only comes with mysql ?

Oooh okay I've to execute the terminal from the prestashop container. I executed some command from standard terminal by going to the prestashop data folder.

Now it works, thank you !

**Comment by hibatallahAouadni** [comment]
Hello @bastien70 

Thanks for your feedback!
Closing the issue as your problem has been solved :tada: 

Thanks!
