### ISSUE TITLE
Add documentation or tutorial to add checkout step with 1.7.8.x version

### ISSUE THREAD

**Issue by bastien70** [PrestaShop/PrestaShop#28789]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Describe the solution you'd like

I couldn't find any documentation, article or video explaining how we can implement a new step during checkout, using the new way with a hook.

Would it be possible to create a resource explaining it? Whether it's a documentation page, a video, a reproducer with different use cases?

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by AureRita** [comment]
Hi @bastien70 
Thank you for your suggestion. The Product Team will take it into consideration for future developments.

Please be aware that there is no guarantee that this feature will be developed anytime soon.

If this one is important to you and you cannot wait for it to be released on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

Thanks you
