### ISSUE TITLE
Change the default branch for ps_supplierlist

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#28787]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Change the default branch for ps_supplierlist

### Expected behavior

It should be develop like all the other module

### Steps to reproduce

Go to the  [ps_supplierlist repo](https://github.com/PrestaShop/ps_supplierlist) and check the branch. 

### PrestaShop version(s) where the bug happened

no

### PHP version(s) where the bug happened

no

### If your bug is related to a module, specify its name and its version

ps_supplierlist

**Comment by AureRita** [comment]
Hi @okom3pom , 

Thank you for your reporting. At start I didn't know why it's a bug but I checked the other module and I noticed that you've right. I'll add a few details of your description. 
 I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. 

Thanks

**Comment by ghost** [comment]
Hello @AureRita 

It s for dev.

Fiendly ping @Progi1984

**Comment by Progi1984** [comment]
@okom3pom Sorry, I'm just a maintainer. We need contact from administrators of the organization. Ping @eternoendless or @matks.

**Comment by atomiix** [comment]
Default branch has been changed to `dev`. I close the issue, thanks everyone :)
