### ISSUE TITLE
[FO] - States field is not displayed anymore

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#28781]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In FO, during checkout process I can't choose the State.

In PS 1.7.8.x ✅ 
<img width="601" alt="Screenshot 2022-06-17 at 14 45 23" src="https://user-images.githubusercontent.com/16019289/174311032-3e588779-66ed-4d3e-80ce-f03c5dbaa295.png">

In 8.0.x ❌ 
<img width="588" alt="Screenshot 2022-06-17 at 14 46 31" src="https://user-images.githubusercontent.com/16019289/174311047-7eb9a10d-9514-4055-9f46-f15ccbc7fcba.png">

In the address, the configuration is correct : 
<img width="360" alt="Screenshot 2022-06-17 at 15 46 07" src="https://user-images.githubusercontent.com/16019289/174311076-feccd121-ea9d-4e0a-86b4-8ac19f140566.png">

### Expected behavior

I should be able to choose the State of my address

### Steps to reproduce

- Go to BO > International > Location > Countries > Enable United States
- Check in States if Unites States are all enabled
- Go to FO > Checkout > On Addresses Step > Choose Country : United States
- No State field. You should be able to choose your state

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.3

**Comment by ghost** [comment]
Hello @Amoifr as you can see: https://github.com/PrestaShop/PrestaShop/issues/29012#issuecomment-1190374764 I did not find your PR? This is to avoid duplicate work.

Thanks for the answer

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29122
