### ISSUE TITLE
Wrong value is_configurable for blockwishlist

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#28795]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Wrong value is_configurable for blockwishlist in config.xml

The good value is 1 and not 0 

U can't use the variable $module->is_configurable with legacy methode  to make a link directly in the configuration module for exemple.

### Expected behavior

Change the value

### Steps to reproduce

Install your shop in french and compare config.xml and config_fr.xml

### PrestaShop version(s) where the bug happened

8.0

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

blockwishlist

**Comment by AureRita** [comment]
Hi @okom3pom, 

Thank for your reporting and your PR, I tried to reproduce your steps to have a config_fr.xml but I can't have it so I never have a file config.xml with the variable is_configurable equal to 1, even if my shop is installed in french 

Can you give us another way to see if it's an expected behaviour to have the blockwishlist configurable ? 

Waiting for your feedbacks

**Comment by ghost** [comment]
Just make a search << list >> in admin bar to generate the file : 


https://user-images.githubusercontent.com/5064590/174632941-fe37b814-ef47-417d-85d1-0965d4b109d3.mp4

**Comment by AureRita** [comment]
Thank for your quick answer.
I tested this and Indeed, we have the second config with the good setup, as we can see on this picture : 
![image](https://user-images.githubusercontent.com/100699445/174636005-251e602a-7b34-4b3b-b91d-617772e285f6.png)

we also some details that are not the same, thank you for this reporting
