### ISSUE TITLE
Cart not updated with custom fields

### ISSUE THREAD

**Issue by bastien70** [PrestaShop/PrestaShop#28798]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I added a step during checkout with 1 field from custom module and I want to save the value in the Cart table.
After submitted the step form, the value is correctly inserted into the cart object, but not persisted into the database.
After my custom checkout step, I'm on the "delivery step", and if I dump the cart, my custom step value isn't here.

So, at final checkout, the custom step value is not persisted into the Cart table in database.

I overrided all needed files, and, I think, no made errors.

### Expected behavior

The value should be persisted into the database

### Steps to reproduce

1. SQL script to add field to Cart table : 

**mymodule/sql/install.php**
```php
$sql[] = "ALTER TABLE " . _DB_PREFIX_ . "cart "
    . "ADD id_spectacle int(11) DEFAULT NULL";
```

2. Custom checkout step handleRequest() method from : 

**mymodule/classes/checkout/OperaSpectacleCheckoutStep.php**
```php
   // other methods...

    /**
     * @param array $requestParameters
     * @return $this
     */
    public function handleRequest(array $requestParameters = array())
    {
        //Si les informations sont postées assignation des valeurs
        if (isset($requestParameters['submitSpectacleStep'])) {
            $this->spectacle_name = $requestParameters['spectacle_name'];
            $this->getCheckoutSession()->setIdSpectacle($requestParameters['spectacle_name']);
            //Passage à l'étape suivante
            $this->setComplete(true);
            $this->setNextStepAsCurrent();

        }

        return $this;
    }
```

3. Override Cart class : 
**mymodule/override/classes/Cart.php**

```php
<?php

class Cart extends CartCore
{
    public ?int $id_spectacle = null;

    public function __construct($id = null, $idLang = null)
    {
        parent::__construct($id, $idLang);

        self::$definition['fields']['id_spectacle'] = ['type' => self::TYPE_INT, 'validate' => 'isUnsignedId'];
    }
}
```

4. Override CheckoutSession class : 
**mymodule/override/classes/checkout/CheckoutSession.php**

```php
<?php

class CheckoutSession extends CheckoutSessionCore
{
    public function setIdSpectacle($id_spectacle)
    {
        $this->context->cart->id_spectacle = (int) $id_spectacle;
        $this->context->cart->save();

        return $this;
    }

    public function getIdSpectacle()
    {
        return $this->context->cart->id_spectacle;
    }
}
```

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by AureRita** [comment]
Hi @bastien70 

Thank for your report,
This issue is too technical for me, ping @PrestaShop/prestashop-core-developers, can someone please reproduce this issue ? 

Thanks

**Comment by bastien70** [comment]
I made a reproducer. So I added the '**something_id**' field to the **Cart** table. Just add the module to a fresh prestashop install, enable it, and add a product to cart.
In the checkout, there is a new step. 

![image](https://user-images.githubusercontent.com/53140475/174747591-ca82aada-461c-43e8-ba27-14141448e60e.png)


Type a random number to represent an ID. (like 1 or 2 ...)

The value will automatically be added to the **Cart**. In the **CustomCheckoutStep.ph**p file, you can uncomment the `die()` if you want to make sure.

```php
    /**
     * Traitement de la requête ( ie = Variables Posts du checkout
     * @param array $requestParameters
     * @return $this
     */
    public function handleRequest(array $requestParameters = array())
    {
        //Si les informations sont postées assignation des valeurs
        if (isset($requestParameters['submitCustomCheckoutStep'])) {
            $this->somethingName = $requestParameters['something_name'];

            $this->getCheckoutSession()->setIdSomething($this->somethingName);
            dump($this->getCheckoutSession()->getCart());
//            die() //if you want to see current 'something_id' value from cart
            //Passage à l'étape suivante
            $this->setComplete(true);

            //Code 1.7.6
            if (version_compare(_PS_VERSION_, '1.7.6') > 0) {
                $this->setNextStepAsCurrent();
            } else {
                $this->setCurrent(false);
            }
        }

        return $this;
    }
```
![image](https://user-images.githubusercontent.com/53140475/174747730-acd9e793-e1c0-4029-98d6-4af80f74ef8d.png)


After finalizing the payment, a hook connected to the **OrderStatutUpdate** should display the **Cart** object on the screen, and you will see that this time, the '**something_id**' value is null, and that in the database, it is not was also not taken into account.

![image](https://user-images.githubusercontent.com/53140475/174747846-a7d18b60-6db9-4c84-9f63-506c17388dac.png)
![image](https://user-images.githubusercontent.com/53140475/174747929-8cb50254-61d2-44b1-a255-2c4756061290.png)
![image](https://user-images.githubusercontent.com/53140475/174748085-c9bc3a18-d237-43fb-8ca6-a91a26845c59.png)

However, in the override of **CheckoutSession**, I save the cart : 

```php
class CheckoutSession extends CheckoutSessionCore
{
    /*
    * module: testmodulecheckout
    * date: 2022-06-21 09:50:27
    * version: 1.0.0
    */
    public function setIdSomething($id_something)
    {
        $this->context->cart->id_something = (int) $id_something;
        $this->context->cart->save(); // <= here, should save the cart in database no ?
        return $this;
    }
    /*
    * module: testmodulecheckout
    * date: 2022-06-21 09:50:27
    * version: 1.0.0
    */
    public function getIdSomething()
    {
        return $this->context->cart->id_something;
    }
}
```

[testmodulecheckout.zip](https://github.com/PrestaShop/PrestaShop/files/8946883/testmodulecheckout.zip)

**Comment by kpodemski** [comment]
Sorry for the very late reply. Altering the core tables is not recommended. It's not good that you have some errors, but on the other hand, given that it is clearly a bad practice, we won't fix anything on this. You could simply create:

yourtable
id_cart
your_value

and use it, instead of modifying core table.
