### ISSUE TITLE
Number Orders

### ISSUE THREAD

**Issue by Murat-06** [PrestaShop/PrestaShop#28808]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

1
10
100
2
20
200
3
Sorted as

1
2
3
4
5
It needs to be sorted as

 ve bir başka düzeltme isteği

by searching the search bar
For purposes such as (.-'?! () /) -, those that should not be eaten in the search, but these intended ones are not listed in the searches

### Describe the solution you'd like

Rankings of numbers
one
2
3
4
5
6
7
8
9
10
rank as 11

ve 

Search bar while searching
(.-'?! () /) - characters are ignored

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @Murat-06 

Thanks for your issue. Unfortunately, there is not enough information provided to understand your feature and work on it. **You must provide all infos and details to submit a complete feature report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
