### ISSUE TITLE
IN - Install a shop 1.7.8 using CLI NOK

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#28804]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Using an environment ~in docker~, we cannot install PS1786 with CLI
As discussed with @atomiix, it is not an issue not related to docker, @atomiix reproduced the issue in local

This issue is reproduced by @HanaRebaiQA @boubkerbribri, Philippe Huet, and me

We have this error `PrestaShop\PrestaShop\Core\Domain\Shop\Exception\ShopException: Shop id 0 is invalid. Shop id must be number that is greater than zero. in /var/www/html/cli1786/src/Core/Domain/Shop/ValueObject/ShopId.php:69`

### Steps to reproduce

1. Prepare a docker environment
2. Install PS178 with CLI : `php install-dev/index_cli.php --language=en --country=fr --base_uri=cli1786 --domain=localhost --db_server=127.0.0.1 --db_user=user --db_name=cli1786 --db_password=User@2022 --prefix=sktest --firstname=demo --lastname=demo --email=demo@prestashop.com --password=123456789 --db_create=1`
3. See error 

![image](https://user-images.githubusercontent.com/16067358/174649340-39cbb1c1-94b5-4f3b-aaff-ee6d3df310db.png)

With PS1778 => ok

~Installing PS1786 with cli in local => ok~
~![image](https://user-images.githubusercontent.com/16067358/174649452-e9fcde8b-b38b-4e28-b4b8-a21a5ccd1357.png)~
=> this issue is reproduced in local with @atomiix 

### PrestaShop version(s) where the bug happened

1.7.8.2, 1.7.8.5, 1.7.8.6, 1.7.8.x

### PHP version(s) where the bug happened

7.1, 7.4

**Comment by webaaz** [comment]
Same bug here

**Comment by arunas-stonis** [comment]
I have the same issue

**Comment by RichardPerdaan** [comment]
Same bug here

**Comment by atomiix** [comment]
Hi everyone, this issue should be fixed now!

**Comment by boubkerbribri** [comment]
Hi everyone, 
Just tested, it works.
Thanks @Matt75 and @atomiix for debug and fixing it.

**Comment by softhightech** [comment]
i added 1 to id_store in all table but the prob always exists.
to fix this issue you have to set ssl = 0 in configuration table.
