### ISSUE TITLE
BO - Translations page - Some warnings are displayed when translating some emails

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#28816]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When we try t translate the body of the email, some warnings are displayed
![image](https://user-images.githubusercontent.com/16067358/174852368-9772fc39-9224-4a4f-906a-6d27784743af.png)

### Steps to reproduce

1. Enable debug mode
1. Go to BO > International > Translations page
2. ` Type of translation` = Email translations
3. `Select the type of email content` = Body
4. ` Select your theme` = Core or Classic
5. `Select your language` and click on modify
6. See error

In the PS1786 => OK

### PrestaShop version(s) where the bug happened

8.0.x, develop

### PHP version(s) where the bug happened

8.0

**Comment by Progi1984** [comment]
Fixed by @okom3pom in #28817 and tested by @sLorenzini
