### ISSUE TITLE
BO - Carriers - The Billing by default is not selected when creating a new carrier

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#28810]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Shipping > Add new carrier, the billing is not selected by default
![image](https://user-images.githubusercontent.com/16067358/174786684-038a31c7-44e7-4743-9474-af46b1c1a8ef.png)
When we save this carrier without selecting the billing => all ranges will be 0
![image](https://user-images.githubusercontent.com/16067358/174786821-dd1f242a-1da4-4184-8759-dad86e1cb3ad.png)

### Steps to reproduce

1. Go to BO > Shipping > Carriers page
2. Add new carrier > Set a carrier name & Transit name & click on next
3. In the second step "Shipping locations and costs" >See error: The billing is not selected
4. Select "Will be applied when the price is | <" = 10 for example 
5. Set a price for all countries and save
6. Click on Finish
7. EDit again & check the ranges => they are converted to 0

https://user-images.githubusercontent.com/16067358/174788008-025eb9fe-4e62-4263-92c1-2a2ba0b716cb.mp4

### PrestaShop version(s) where the bug happened

8.0.x, develop

### PHP version(s) where the bug happened

7.4, 8.0

**Comment by ghost** [comment]
Fixed by : https://github.com/PrestaShop/PrestaShop/pull/28788

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

Thanks, I did not manage to reproduce the issue with 8.0.x.
The issue is fixed :tada: 

https://user-images.githubusercontent.com/16067358/174979284-cd443916-4ae7-4e37-8436-d0918aa44548.mp4

**Comment by hibatallahAouadni** [comment]
Duplicate of #28588
