### ISSUE TITLE
BO - Bad translation or bad behavior in admin search

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#28818]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When we do a targeted search on the invoices there is written invoice number, the search works only for the invoice reference ( #FA00001 ) it should also work with 1

### Expected behavior

Work with the number of invoice not only the invoice reference

![Screenshot (40)](https://user-images.githubusercontent.com/5064590/175026366-73115b78-7e16-40a7-867a-0d122f64d7b9.png)

![Screenshot (41)](https://user-images.githubusercontent.com/5064590/175237274-d7098f73-2c31-49fc-a9ad-8015851377d9.png)

### Steps to reproduce

1. Go to BO > Orders > Change status of an order to "Delivered" for example (to active order's invoice)
2. Go to this order details > click on "View invoice" > The file is downloaded on your computer
3. Open it > Copy the number of the invoice
4. Go to header and click in search bar > Select "Invoices" on the list
5. Paste your invoice number in the placeholder > click on search icon > the file is downloaded
6. Erase the "#" character in the placeholder > click on search icon > the file is downloaded
7. See error
8. Go to customers page for example > add the number "1" only for example in the placeholder of the search > Select "Invoices" on the list > click on search icon > the file is downloaded
9. See error

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.4

**Comment by sLorenzini** [comment]
Hello @okom3pom,

I reproduce the issue with PrestaShop version 8.0.0 / 1.7.8.6 / 1.7.7.8. I'll add this to the backlog so it can be fixed.

I have updated your steps to reproduce it. Don't hesitate to tell us if it's uncorrect.

I have another error only on ps8.0.0 version. See screenshot:

![Capture d’écran 2022-06-23 à 10 15 51](https://user-images.githubusercontent.com/2854834/175252946-7cfe711c-bd7b-4ff7-983f-f2c41f396a15.png)


Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

Thank you

**Comment by ghost** [comment]
The other error is fixed by : 
https://github.com/PrestaShop/PrestaShop/pull/28802
