### ISSUE TITLE
On the order detail page, the hook displayOrderDetail can't access to the general variables like $urls

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#28813]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you use a module with the `displayOrderDetail` hook, you can't use general purpose variables as `$urls`.
For example, you can use them inside the displayHome hook.

### Expected behavior

Be able to access to theses variables.

### Steps to reproduce

1. Add a module with `displayOrderDetail` hook, fetching a template calling this : {$urls.base_url}

---
1. Install the attached module below
2. Go to `/index.php?controller=order-detail&id_order=1`
3. See this kind of error :  `Warning: Undefined array key "urls" in /var/cache/dev/smarty/compile/37/8b/af/378baff2d7c3a63fa601973bb60e7f24d8df6e21_2.module.testviewstemplateshookdis.php on line 24`
4. Check the PR
5. See this is now an URL display instead of error.

[issue.zip](https://github.com/PrestaShop/PrestaShop/files/9070009/issue.zip)

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

Could you please provide a screenshot :pray: 
Waiting for your feedback.

Thanks!

**Comment by PrestaEdit** [comment]
Hi @hibatallahAouadni,

What kind of screenshot do you want ? The error one ?
Maybe you need a test module to be able to make a QA test, will it not be better ?

**Comment by HanaRebaiQA** [comment]
Hello @PrestaEdit 

Yes! Could you please provide us the tested module that you used and the clear steps to reproduce with a screen-shot or a screen-record of the fails?

Thank You!

**Comment by PrestaEdit** [comment]
Hi @HanaRebaiQA,

There is :
[issue.zip](https://github.com/PrestaShop/PrestaShop/files/9070009/issue.zip)

To reproduce :

1. Install the module
2. Go to /index.php?controller=order-detail&id_order=1
3. See this kind of error :  Warning: Undefined array key "urls" in /var/cache/dev/smarty/compile/37/8b/af/378baff2d7c3a63fa601973bb60e7f24d8df6e21_2.module.testviewstemplateshookdis.php on line 24
4. Check the PR
5. See this is now an URL display instead of error.

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

Thanks for your feedback!
I was able to reproduce the issue with PS1786 and PS800. 

- **PS 1.7.8.6:**
![image](https://user-images.githubusercontent.com/23308427/178027232-6540bffc-0018-4eac-b729-d554db8a69be.png)

- **PS 8.0.0:**
![image](https://user-images.githubusercontent.com/23308427/178027249-4e49bc91-8df4-4f6c-8546-077a8ff111de.png)


I’ll add this to the debug backlog so that it’s fixed.
Thanks again for your PR :rocket: 

Thank you
