### ISSUE TITLE
Classic theme should have a master branch following prestashop releases

### ISSUE THREAD

**Issue by davideapvd** [PrestaShop/PrestaShop#28823]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

When downloading classic theme is not clear is follows development PrestaShop branch and people don't know how to make things compatible

### Describe the solution you'd like

a more clear release, classic-theme releases should be tagged with core PrestaShop release versions

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by sLorenzini** [comment]
Hello @davideapvd,

Thank you for your suggestion.
The "Describe the solution you'd like" is not very clear. Could you provide us more details please 🙏?

@NeOMakinG, what do you think of this feature?

Thank you

**Comment by davideapvd** [comment]
> Hello @davideapvd,
> 
> Thank you for your suggestion. The "Describe the solution you'd like" is not very clear. Could you provide us more details please pray?
> 
> @NeOMakinG, what do you think of this feature?
> 
> Thank you

hello, sure, I've updated my request

**Comment by sLorenzini** [comment]
Thank you for your answer.

We are currently working on the Classic theme, and as soon as we release the first tag/version, we will improve the repository tree.

We are closing the issue as there's no real feature here.

Thanks
