### ISSUE TITLE
Avoid mail send with multiple hooks

### ISSUE THREAD

**Issue by chtipepere** [PrestaShop/PrestaShop#28839]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When multiple functions are hooked to `hookActionEmailSendBefore()` and one of them returns `null`, then `Mail::send() `still send the mail.

Right now, when there's one function hooked, the hook expects `null` to avoid mail send, when there's multiple function, the hook expects `false` to be return to avoid mail send.

### Expected behavior

When one of the functions hooked to `hookActionEmailSendBefore()` returns null then the mail should not be send.

### Steps to reproduce

1. Hook two functions to `hookActionEmailSendBefore()`

2. One of them returns `false`, the other one returns `null`.

3. The hook will set `$keepGoing` variable to `true`.

### PrestaShop version(s) where the bug happened

1.7.6.9

**Comment by florine2623** [comment]
Hello @chtipepere ,

Could you add a screen record of what you are explaining please ? It is not very clear for me.

Waiting for your answer ! 
Thansk!
