### ISSUE TITLE
Faceted search option 'Show the number of matching products' does not work

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#28833]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Even though checking the option `Show the number of matching products` in the back office, the filters do not show the number of products.
BO:
![Capture d’écran 2022-06-23 174158](https://user-images.githubusercontent.com/7520695/175339782-ff0620d5-f38c-42ba-a168-329f0cdeb198.png)

FO:
![Capture d’écran 2022-06-23 174211](https://user-images.githubusercontent.com/7520695/175339791-69a7fdd1-a096-4752-b7de-8084ccc0618a.png)

### Expected behavior

I'd expect to see the number of products behind each filter value

### Steps to reproduce

1. In the BO, go to `Manage Modules`, select `Faceted search`, click `Configure`
2. Define a filter model
4. Go to the FO, display the category for which a filter is configured
5. Notice that there are no quantities displayed for the filter options (default)
6. In the BO in the section `Parameters`, activate the option `Show the number of matching products`
5. Notice that there are still no quantities displayed for the filter options (they should now that we turned on the option)

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_facetedsearch 3.8.0

**Comment by lmeyer1** [comment]
This issue is related to classic-rocket. Once I know more I will update it either with details or close it.

**Comment by florine2623** [comment]
Hello @lmeyer1 ,

I am using ps_facetedsearch v3.8.0, PS 1.7.8.x, I can't reproduce your issue :

<img width="252" alt="Screenshot 2022-06-24 at 15 35 22" src="https://user-images.githubusercontent.com/16019289/175547067-8f8fbe28-07d4-4091-b43c-8a9836926ba7.png">
<img width="188" alt="Screenshot 2022-06-24 at 15 36 34" src="https://user-images.githubusercontent.com/16019289/175547111-2cd5dbb9-a5ed-4e1c-ba80-eae2fd9490d9.png">

I'll leave your issue with NMI label. Feel free to update and add details to it.
Thanks!

**Comment by lmeyer1** [comment]
This is related to theme classic-rocket. 
Closed in favor of https://github.com/prestarocket-agence/classic-rocket/issues/294
