### ISSUE TITLE
FO - A bad display in the Wishlist page when the customer is logged out 

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#28832]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

FO - A bad display in the Wishlist page when the customer is logged out

Thanks to @hibatallahAouadni for also finding the bug 

8.0.x : NOK :x: 

https://user-images.githubusercontent.com/92912932/175339419-c657959d-14d7-450f-8dd5-ef2c05fa9f4b.mp4

develop : NOK :x:

https://user-images.githubusercontent.com/92912932/175339285-11b9ec98-899b-481c-aecc-3bd6efc1dba6.mp4

![image](https://user-images.githubusercontent.com/92912932/175339483-b2b4ad3d-8ccd-4c22-9335-21a7b80dc088.png)

1786 : OK :heavy_check_mark: 

https://user-images.githubusercontent.com/92912932/175339343-7d2b55a7-dc5c-4144-8737-fd56601fab05.mp4

![image](https://user-images.githubusercontent.com/92912932/175339587-08e7a488-d850-40c8-af7d-3737d11c942f.png)

### Expected behavior

The behavior of 8.0.x should be like the 1786

![Image](https://user-images.githubusercontent.com/43613217/177164789-1be40841-f939-46a1-874e-8f28a2c89138.png)

### Steps to reproduce

1. Go to FO > Log in with a customer
2. Add a product to the wishlist
3. Click on the customer account
4. Go to the wishlist page by clicking on My wishlist list
5. Click on the wishlist which the product is added to
6. The product is well displayed in the wishlist list
7. Click to log out
8. See error > A bad display when the customer have no access to the wishlist

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.0, 7.3, 7.1, 7.2

### If your bug is related to a module, specify its name and its version

blockwishlist v2.1.0

**Comment by jolelievre** [comment]
I reopen this issue until we actually release a new version of the module
