### ISSUE TITLE
FO - Wishlist - An exception is displayed when we create a list with invalid 

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#28835]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An exception is displayed when creating a list with an invalid name
![image](https://user-images.githubusercontent.com/16067358/175349750-daca1592-d8fd-4ca8-8011-e4c04d2cc64f.png)

### Steps to reproduce

1. Go to FO > Sign in 
2. Go to product details page 
3. Click on the heart
4. Create a new list
5. Set an invalid name "test = test"
6. Click on Save
7. See error > the list cannot be created & error 500 in the console

![image](https://user-images.githubusercontent.com/16067358/175350229-62037434-f30b-4d31-9a2a-96d86ca452ef.png)

### PrestaShop version(s) where the bug happened

1.7.7.8, 1.7.8.6, 8.0.x

### PHP version(s) where the bug happened

7.2, 7.1, 8.1

### If your bug is related to a module, specify its name and its version

wishlist v2.0.1, v2.1.0

**Comment by jolelievre** [comment]
Thanks for the fix @okom3pom 
I leave the issue open until the module is released just to track the final state of this issue

**Comment by florine2623** [comment]
It is fixed. Now we have :

https://github.com/PrestaShop/PrestaShop/assets/16019289/b978fada-7244-420b-ad38-9306b32e04b4
