### ISSUE TITLE
PHP8.1 - FO - Wishlist - The Heart is not filled after reloading the page

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#28844]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Using PHP8.1, the heart is not filled after reloading the product details page

https://user-images.githubusercontent.com/16067358/175489267-cbca2ecc-7540-49f3-ae6a-c95f54184d4f.mp4

### Steps to reproduce

1. Go to FO > Sign in and go to the Product details page ( single product)
2. Increase the quantity to 3 for example
3. Add the product to the wishlist
4. Refresh the page
5. Increase the quantity to 3
6. See error > the heart is not empty

1. Go to FO > Sign in and go to the Product details page ( product with combinations)
2. change the combination to another one (not the default)
3. Add the product to the wishlist
4. Refresh the page
5. Select the default combination & then go back to the combination added to the wishlist
6. See error > the heart is not empty

**Your account > Wishlist page**
![image](https://user-images.githubusercontent.com/16067358/175488561-aaec3107-12fb-4c0c-82ef-2eeb7bd96cb4.png)

**Product details page**
![image](https://user-images.githubusercontent.com/16067358/175488761-faeedd43-c3e1-428a-8ccc-297330383687.png)
![image](https://user-images.githubusercontent.com/16067358/175488860-6a48a74e-73c6-4ff9-a5b3-5a4464851672.png)

This issue is reproduced only with php8.1

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

wishlist v2.1.0

**Comment by jolelievre** [comment]
Hi @atomiix 

the fix has been merged on the module, but I'm thinking maybe e should keep this issue open until a version of the module is released which includes your fix?
