### ISSUE TITLE
BO - Stats - Stats carrier is duplicated when a carrier is edited

### ISSUE THREAD

**Issue by borjagarciab** [PrestaShop/PrestaShop#28840]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you have a carrier used in orders , and you edit something of this carrier, the carrier is the same, but the stats separate this.
https://gyazo.com/a986b16b7fe4ff84985ca642be7bd31b

### Expected behavior

The carrier must be the same, because the id_carrier change, but not the id_reference.
https://gyazo.com/01b9e2946413c4f6407beb8df3e1dd67

### Steps to reproduce

1. Create a carrier
2. Create an order with this carrier.
3. Edit this carrier (prices or something)
4. Go to stats by carrier and check that there are 2 carriers with same name

### PrestaShop version(s) where the bug happened

1.7.6.8 (but happends in all)

### If your bug is related to a module, specify its name and its version

statscarrier

**Comment by borjagarciab** [comment]
The pull request i sent
https://github.com/PrestaShop/statscarrier/pull/14

**Comment by florine2623** [comment]
Hello @borjagarciab ,

I have reproduced your issue on develop, 8.0.x and 1.7.8.x branch, I'll add this to the backlog so it can be fixed.

Here are the steps I followed :
1. Create a carrier
2. Create an order from BO with this carrier
3. See in the order that the carrier is not correct (the default one is used)
4. Change it to the carrier you created
5. Edit the carrier you created (prices or something)
6. Go to stats by carrier and see that there are 2 carriers with same name ❌ 
<img width="237" alt="Screenshot 2022-06-24 at 11 49 25" src="https://user-images.githubusercontent.com/16019289/175510955-d3310650-1ca9-4aaa-be12-640218c55176.png">

Thank you for your PR ^^

**Comment by ghost** [comment]
Don't close your issue It will be closed when your PR is merged

**Comment by borjagarciab** [comment]
Sorry

**Comment by jolelievre** [comment]
Thanks @borjagarciab the fix has been merged it will be available in the next release of the module
