### ISSUE TITLE
BO > Customers > Addresses - Required fields are not used in back office 

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#28848]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When applying required fields for addresses they are not used in the BO

### Expected behavior

Use the required fields like : 

https://user-images.githubusercontent.com/5064590/175557925-ebfe5aa9-09ac-4232-affd-0765cf7f4a7e.mp4

### Steps to reproduce

1 ) Set required fields in back office for address
2 ) Edit an address from back office and see you can add or adit an adresse without required field

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @okom3pom ,

I reproduced the issue with PrestaShop version 1.7.7.8, 1.7.8.6 and 8.0.0, it is not a regression, I'll add this to the backlog so it can be fixed.

I have configured the Address format in International > Locations > Country :
<img width="425" alt="Screenshot 2022-06-24 at 17 05 00" src="https://user-images.githubusercontent.com/16019289/175563593-152a43eb-661e-45c2-9bd6-e91e7778d206.png">

I have selected all fields to be required :

<img width="1193" alt="Screenshot 2022-06-24 at 17 04 51" src="https://user-images.githubusercontent.com/16019289/175563674-8546e00a-2257-4604-a816-feec46796f7f.png">

In the BO > Customers > Addresses, I can edit and add an address without the required fields ❌ 

Thank you

**Comment by ghost** [comment]
Hello @florine2623 i have an PR for this issue but i wait for the new branch because it's an BC break
