### ISSUE TITLE
Parent categories in the breadcrumbs do not display

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#28841]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On my multishop installation, the parent categories are not displayed in the product detail.
![image](https://user-images.githubusercontent.com/7520695/175479486-367d94bb-db93-4bcf-8552-22aa445b3623.png)
When looking at the markup, the correct category is used, but the name is missing:
![image](https://user-images.githubusercontent.com/7520695/175482075-931628c0-4c38-4c15-8204-3716660f7471.png)
I verified in the database, the category 556 is active in `ps_category`, it has the entries in `ps_categroy_lang` for the current shop, and it also is present in `ps_category_shop` for the current shop.

I'm using the theme `classic-rocket`

### Expected behavior

The breadcrumbs should show completely

### Steps to reproduce

Open any product page of a product that is farther down in the category tree (i.e. at least two category levels above `Home` category).
Notice that the breadcrumbs are not displaying completely.

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.3

**Comment by kpodemski** [comment]
Most of the time it's related to the database structure. I'm pretty sure it would be impossible to reproduce on the clean installation.

The category might be available in the database, but there might be some issues related to the nleft, nright, or one of the categories has the parent id that doesn't exist anymore, etc.

**Comment by lmeyer1** [comment]
@kpodemski Thanks.
The database structure is correct as far as I can tell. I will look at `nleft` and `nright` and hope to find the issue.

**Comment by florine2623** [comment]
Hello @lmeyer1  ,

I can't reproduce your issue on my multistore :
<img width="635" alt="Screenshot 2022-06-24 at 11 22 41" src="https://user-images.githubusercontent.com/16019289/175506031-9864dde2-d101-4557-a5ac-973a5096b826.png">
The breadcrumb is displayed correctly.

Here are my categories that I just created for this issue :
<img width="1178" alt="Screenshot 2022-06-24 at 11 27 05" src="https://user-images.githubusercontent.com/16019289/175506919-444bff93-ece3-40e6-9d9f-1242c0b64033.png">

Waiting for your update regarding `nleft` and `nright`

Thanks!

**Comment by jf-viguier** [comment]
> Hello @jf-viguier ,

Wrong person @florine2623

**Comment by lmeyer1** [comment]
I introduced this bug in my code by fixing another bug :cry: by uncommenting this line https://github.com/PrestaShop/PrestaShop/blob/2b0a73f9ea15eb883c2d020df08bc3c7c60c5c77/classes/PrestaShopCollection.php#L339
