### ISSUE TITLE
Invalid addess ecception when accessing cart listing page in admin backend

### ISSUE THREAD

**Issue by davideapvd** [PrestaShop/PrestaShop#28847]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Sometimes when accessing the cart listing backend page I get the following exception

```
[PrestaShopException]

Invalid address #3091001
at line 536 in file classes/Address.php

531.             // if an id_address has been specified retrieve the address
532.             if ($id_address) {
533.                 $address = new Address((int) $id_address);
534. 
535.                 if (!Validate::isLoadedObject($address)) {
536.                     throw new PrestaShopException('Invalid address #' . (int) $id_address);
537.                 }
538.             } elseif ($with_geoloc && isset($context->customer->geoloc_id_country)) {
539.                 $address = new Address();
540.                 $address->id_country = (int) $context->customer->geoloc_id_country;
541.                 $address->id_state = (int) $context->customer->id_state;

    AddressCore::initialize - [line 3654 - classes/Product.php] - [2 Arguments]
    ProductCore::getPriceStatic - [line 54 - override/classes/Product.php] - [18 Arguments]
```

To 'fix' the page I need to do `delete from ps_cart where id_address_delivery = 3091001;`;

this is really strange because we can't figure out why this is happening

### Steps to reproduce

steps above

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7,3

**Comment by florine2623** [comment]
Hello @davideapvd ,

Your issue is similar to : https://github.com/PrestaShop/PrestaShop/issues/12617

So I close it.
