### ISSUE TITLE
Not used file in the productcomments module

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#28855]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

There is a filennamed "ProductCriterion.php"  that is not being used by the module productcomments. It's probably some relict of the past.

### Expected behavior

The module should work as expected after removing this file.

### Steps to reproduce

- Go to your prestashop folder 
- Go to module
- Go to productcomments
- Delete ProductCriterion.php

### PrestaShop version(s) where the bug happened

n/a

### PHP version(s) where the bug happened

n/a

### If your bug is related to a module, specify its name and its version

productcomments

**Comment by AureRita** [comment]
Hi @kpodemski , 

Thank for your reporting, I think this is more a feature than a bug, so I'll take it like that. I'll modify your description, to let the developer/product manager understant the feature here 

waiting for your feedback of the modification

**Comment by leemyongpakvn** [comment]
@AureRita FYI, **kpodemski** created this issue for my original [PR](https://github.com/PrestaShop/productcomments/pull/143) that I marked as an Improvement. The unused file is not harmful, it just useless.
