### ISSUE TITLE
Remove PS_SHOP_ACTIVITY and shop_activity only used by a removed controller

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#28851]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Remove SHOP_ACTIVITY only used by removed controllers

https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/src/PrestaShopBundle/Controller/Admin/Improve/Modules/AddonsStoreController.php#L85

### Describe the solution you'd like

Remove SHOP_ACTIVITY only used by removed controllers

https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/src/PrestaShopBundle/Controller/Admin/Improve/Modules/AddonsStoreController.php#L85

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by AureRita** [comment]
Hi @okom3pom 
Thank you for your suggestion. The Develop Team will take it into consideration for future developments.

Please be aware that there is no guarantee that this feature will be developed anytime soon.
Thanks for your PR :rocket: 

Thank you

**Comment by Hlavtox** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/33232
