### ISSUE TITLE
Fix deprecated CHARSET utf8 in native modules' install and upgrade

### ISSUE THREAD

**Issue by leemyongpakvn** [PrestaShop/PrestaShop#28857]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

mysql.com declared that utf8 was deprecated at https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8mb3.html
but some modules' install still `CREATE TABLE` with `CHARSET=utf8` while Prestashop Core / install / data / db_structure.sql use `CHARSET=utf8mb4`  for years. The result is tables created with `CHARSET=utf8` have Unknown COLLATION when check with tool like phpmyadmin. It is not critical but still need to fix somehow.
Maybe a bot can replace CHARSET utf8 by CHARSET utf8mb4 in other modules' install.sql more effective.

### Expected behavior

Tables created with modules install script inherit correct COLLATION from the Database

### Steps to reproduce

Check tables structure with phpmyadmin, you will see related tables have --- COLLATION
![ps_analytics_deprecated_charset_utf8](https://user-images.githubusercontent.com/3759923/175795267-07dc497a-39f3-476b-ae29-8b923be4acbb.png)
![ps_homeslider_info_layered_deprecated_chasert_utf8](https://user-images.githubusercontent.com/3759923/175845303-15d0eef5-78d2-4b02-82bf-6ca33716838d.png)

### PrestaShop version(s) where the bug happened

1.7.8.x

### PHP version(s) where the bug happened

7.x

### If your bug is related to a module, specify its name and its version

blockreassurance, blockwishlist, gsitemap, pagesnotfound, productcomments, ps_emailsubscription, ps_googleanalytics, ps_imageslider, ps_linklist, ps_mainmenu

- [ ] blockreassurance
- [ ] blockwishlist
- [ ] gsitemap
- [ ] pagesnotfound
- [ ] productcomments
https://github.com/PrestaShop/productcomments/pull/144
- [ ] ps_emailsubscription
- [ ] ps_facetedsearch
- [ ] ps_googleanalytics 
https://github.com/PrestaShop/ps_googleanalytics/pull/117
- [ ] ps_imageslider
- [ ] ps_linklist
- [ ] ps_mainmenu 
https://github.com/PrestaShop/ps_mainmenu/pull/63

**Comment by ghost** [comment]
I update your description to add missing module gsitemap.

I think we should also make this change via an upgrade file for already installed modules

**Comment by leemyongpakvn** [comment]
@okom3pom  :ok_hand: Certainly, core devs will make that upgrade, but it is not me, I'm going around modules and themes.

**Comment by ghost** [comment]
It's one upgrade file by module.

[Like this](https://github.com/PrestaShop/ps_googleanalytics/blob/dev/upgrade/upgrade-4.1.0.php) with the good SQL query   

For example : 

```
if (!defined('_PS_VERSION_')) {
    exit;
}

function upgrade_module_4_X_X($object)
{
    return Db::getInstance()->execute('ALTER TABLE `' . _DB_PREFIX_ . 'ganalytics` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci');
}
```

**Comment by leemyongpakvn** [comment]
@okom3pom Great, looks simple enough. I guess the module upgrade will looks like this

```
/* File: /upgrade/upgrade-4.1.4.php */ 

if (!defined('_PS_VERSION_')) {
    exit;
}

function upgrade_module_4_1_4($object)
{
    return Db::getInstance()->execute('ALTER TABLE `' . _DB_PREFIX_ . 'ganalytics` 
    CHARACTER SET = utf8mb4 COLLATE utf8mb4_general_ci;');
}
```
version changes in mainclass and config.xml are needed also.

**Comment by ghost** [comment]
Yes but you don't need to update config.xml and this line https://github.com/PrestaShop/ps_googleanalytics/blob/dev/ps_googleanalytics.php#L57 

This will be done at the version change of the module

**Comment by leemyongpakvn** [comment]
Thanks for your information. I will make a PR for this upgrade file in https://github.com/PrestaShop/ps_googleanalytics soon.

**Comment by AureRita** [comment]
Hi @leemyongpakvn , 

Thank for your reporting, I tried to reproduce your issue but I didn't see this on my phpmyadmin, as you can see on this picture : 
![image](https://user-images.githubusercontent.com/100699445/175941803-030fbc79-4750-4606-b1e5-9ae0d2e34a60.png)

this is on 1.7.8.6, did you use another version of 1.7.8.x ? 
Have you done something that give you the " --- COLLATION" 

Waiting for your feedback

**Comment by ghost** [comment]
Hello @AureRita i can't also reproduce the same in my phpmyadmin version, but the issue is for a depraceted charset ( utf8 ). 

I think the @PrestaShop/prestashop-core-developers can approve this issue

**Comment by leemyongpakvn** [comment]
I got the --- COLLATION problem with phpmyadmin 5.2.0  and MySQL 8.0.29. Maybe you use an older MySQL version that still support `utf8_general_ci`. As I described above, MySQL officially dropped support for utf8 (in fact utf8mb3) in 8.0 version and Prestashop core DB install switched to `utf8mb4_general_ci` for years. The devdocs also required using `utf8mb4_general_ci` at https://devdocs.prestashop.com/1.7/basics/installation/localhost/#creating-a-database-for-your-shop. 
It is the right time to fix this minor bug for related native modules, you can fix it later but I see no reason to postpone.

**Comment by kpodemski** [comment]
Hello @AureRita 

This issue is valid.
