### ISSUE TITLE
Simplify token getting of ps_googleanalytics module

### ISSUE THREAD

**Issue by leemyongpakvn** [PrestaShop/PrestaShop#28858]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

in [classes/Form/ConfigurationForm.php](https://github.com/PrestaShop/ps_googleanalytics/blob/dev/classes/Form/ConfigurationForm.php), there are 3 calls `Tools::getAdminTokenLite('AdminModules');` in a same function. 
There is no need to recalculate AdminTokenLite as it is already calculated and assigned to $helper->token at line 59.

### Expected behavior

Assign $helper->token = Tools::getAdminTokenLite('AdminModules'); in the first call, then use $helper->token in the other two.

### Steps to reproduce

Check `function generate()` in [classes/Form/ConfigurationForm.php](https://github.com/PrestaShop/ps_googleanalytics/blob/dev/classes/Form/ConfigurationForm.php#L46)

### PrestaShop version(s) where the bug happened

1.7.8.5 - 1.7.7.8 - 1.7.6.5

### PHP version(s) where the bug happened

7.x

### If your bug is related to a module, specify its name and its version

ps_googleanalytics

**Comment by AureRita** [comment]
Hi @leemyongpakvn ,

I reproduce the issue with PrestaShop version 1.7.6.5, as you can see on this picture. I'll add this to the backlog so it can be fixed.

![image](https://user-images.githubusercontent.com/100699445/175967924-cce2079f-3c39-49e7-afe8-5f06a7bd4eb8.png)


If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks

**Comment by leemyongpakvn** [comment]
@AureRita I already fixed this issue with the [related PR](https://github.com/PrestaShop/ps_googleanalytics/pull/118). This issue was created after that in fact, following a procedure introduced by **okom3pom** :satisfied:
