### ISSUE TITLE
Inefficient queries in PrestaShopCollection, incoherent display of category names in breadcrumbs.

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#28864]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

There is a bug in PrestaShopCollection is inefficient in a multishop context when a language file `*_lang` is involved, and there is one language entry per shop.

Verifiable example: 
If a category has not the same name in all shops, the name displayed in the breadcrumb is always the name of the category in the main shop.

The reason behind: the join generated selects all lines, and not the ones related to the current shop. 

e.g. The query generated for the category breadcrumbs in `ProductController::getBreadcrumbLinks()` (`$categoryDefault->getAllParents()`) returns too many lines:
```
SELECT * FROM `ps_category` a0 LEFT JOIN `ps_category_lang` `a1` ON (a0.`id_category` = a1.`id_category`) WHERE (a0.`nleft` < 2328) AND (a0.`nright` > 2337) AND (a1.`id_lang` = 1) ORDER BY a0.`nleft` asc
```
Given `nl` as category level depth, and `ns` the number of shops, the query returns `nl * ns` lines whereas it should return only `nl` lines, one for each category.

Note: this is related to #28841, which is not reproducible.

### Expected behavior

I expect 
1. the query to be efficient
2. `PrestaShopCollection` returning the objects pertaining to the current shop and not the main shop.

### Steps to reproduce

In a multishop environment:
1. In the BO, select a shop different from the main shop, `shop A`
2. Go to `Catalog - Categories`
3. Edit the name of a parent category that has a child category
4. In the FO, in `shop A`, navigate to a product being member of the child category
5. Notice that the name of the parent category displayed in the breadcrumb is the one of the main shop, and not the one of `shop A`

PS: We have a 26 shops in our multishop environment, so the performance is also a problem, but it would not be possible to observe it directly.

### PrestaShop version(s) where the bug happened

1.7.8.6 - 1.7.7.8

### PHP version(s) where the bug happened

7.3

**Comment by AureRita** [comment]
Hi @lmeyer1 ,

Thank you for your report,I reproduce the issue with PrestaShop version 1.7.7.8 as we can see on this picture, I'll add this to the backlog so it can be fixed.

![image](https://user-images.githubusercontent.com/100699445/175970352-c66463be-526b-464b-a333-48d1f01dcee9.png)

Thank you for your PR :rocket:
