### ISSUE TITLE
[Responsive - BO] Bad display of active menu item in Legacy pages

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#28863]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On Mobile/Tablet, try to access a Legacy page (ex: `Attributs & Features`, `Image Settings`, ..).
Then open the menu, the active menu item has a different background and the text's color is not white.

![image](https://user-images.githubusercontent.com/23308427/175900525-a46b45af-a27a-4ccb-9319-cdcec9b49ed6.png)

### Expected behavior

The background-color of the active menu item should be: `background-color: #22252a;`
And the text color should be white, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/175900748-cc974577-51a6-41cb-ba2b-16ede220cf56.png)

### Steps to reproduce

1. BO > SELL > Catalog > Attributes & Features
2. Open the menu and check the active menu-item
3. See error > the background-color is different and the text color is not white

### PrestaShop version(s) where the bug happened

8.0.x & develop

### PHP version(s) where the bug happened

7.2

**Comment by Amoifr** [comment]
Sorry I'm not able to reproduce it 

https://user-images.githubusercontent.com/31698966/175979244-71d07bf2-66ac-443b-81bc-dee627a717a3.mp4

**Comment by hibatallahAouadni** [comment]
Hello @Amoifr 

I think you manage to reproduce the issue now, isn't it?

Thanks!
