### ISSUE TITLE
Breadcrumbs bug in category pages

### ISSUE THREAD

**Issue by musaffar-patel** [PrestaShop/PrestaShop#28862]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The problem occurs only in the following situation:

When a category has multiple parent categories and at least one of those categories are not active.

This occurs in \controllers\front\listing\CategoryController.php
method: 
getBreadcrumbLinks

the following code:

```
        if ($this->category->id_parent != 0 && !$this->category->is_root_category && $category->active) {
            $breadcrumb['links'][] = [
                'title' => $this->category->name,
                'url' => $this->context->link->getCategoryLink($this->category),
            ];
        }


```
should be:

```
        if ($this->category->id_parent != 0 && !$this->category->is_root_category && $this->category->active) {
            $breadcrumb['links'][] = [
                'title' => $this->category->name,
                'url' => $this->context->link->getCategoryLink($this->category),
            ];
        }


```in other words, the first condition should use $this->category->active and not $category->active otherwise it takes the value for this from the previous loop iteration unrelated to the current category.

### Expected behavior

Current category should always be present in the breadcrumb when viewing the category page

### Steps to reproduce

The problem occurs only in the following situation:

When a category has multiple parent categories and at least one of those categories are not active.  In such a situation the current category is not added to the breadcrumb.

### PrestaShop version(s) where the bug happened

1.7.x

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

_No response_

**Comment by Hlavtox** [comment]
Hi @musaffar-patel, this is already fixed in the next version. :-)

https://github.com/PrestaShop/PrestaShop/blob/2b0a73f9ea15eb883c2d020df08bc3c7c60c5c77/controllers/front/listing/CategoryController.php#L241

**Comment by musaffar-patel** [comment]
@Hlavtox  That's great news, in which version is it fixed .. 1.7.8.7 ?

**Comment by Hlavtox** [comment]
@musaffar-patel It will be fixed in Prestashop 8, which will be released later this year.👍

**Comment by AureRita** [comment]
HI @musaffar-patel and @Hlavtox 

Thank you for your quick answer @Hlavtox. Indead, as it was say, it's already fixed in Prestashop 8 so I'll close this issue
