### ISSUE TITLE
Fix deprecated CHARSET utf8 via native modules' upgrade

### ISSUE THREAD

**Issue by leemyongpakvn** [PrestaShop/PrestaShop#28860]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

mysql.com declared that utf8 was deprecated at https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8mb3.html
but some modules' install still CREATE TABLE with CHARSET=utf8 while Prestashop Core / install / data / db_structure.sql use CHARSET=utf8mb4 for years. The result is tables created with CHARSET=utf8 have Unknown COLLATION when check with tool like phpmyadmin. 

This issue came from the same source of #28857, but this is for the **previous** installations, as recommended by @okom3pom. 

### Expected behavior

Tables fixed by modules upgrade script show correct COLLATION in database tool such as phpmyadmin

### Steps to reproduce

Check tables structure with phpmyadmin, you will see related tables have --- COLLATION
![ps_homeslider_info_layered_deprecated_chasert_utf8](https://user-images.githubusercontent.com/3759923/175845303-15d0eef5-78d2-4b02-82bf-6ca33716838d.png)

### PrestaShop version(s) where the bug happened

1.7.8.x

### PHP version(s) where the bug happened

7.x

### If your bug is related to a module, specify its name and its version

- [ ] blockreassurance
- [ ] blockwishlist
- [ ] gsitemap
- [ ] pagesnotfound
- [ ] productcomments
https://github.com/PrestaShop/productcomments/pull/144
- [ ] ps_emailsubscription
- [ ] ps_facetedsearch
- [ ] ps_googleanalytics
https://github.com/PrestaShop/ps_googleanalytics/pull/117
- [ ] ps_imageslider
- [ ] ps_linklist
- [ ] ps_mainmenu
https://github.com/PrestaShop/ps_mainmenu/pull/63

**Comment by AureRita** [comment]
Hi @leemyongpakvn, 

Thank you for this second report, but what is the difference between this issue and #28857 ? it's during the installation and during an upgrade ? Can they be corrected in a single PR ( per module ) ? 

Waiting for your feedback

**Comment by leemyongpakvn** [comment]
@AureRita The difference is the first is for new installation (CREATE TABLE) and the second is for old installation (ALTER TABLE). They can be really corrected in a single PR per module. But as **kpodemski** and **okom3pom** recommended yesterday, I still need create an issue for QA check each PR, so I still need to create at least 10 issues. Is it OK for you ?

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers could someone try to reproduce the issue cause it's too technical for me :pray: 
PS: related to this issue 28857

**Comment by leemyongpakvn** [comment]
@hibatallahAouadni To reprocedure the issue you need MySQL 8.x. Maybe it must be marked as Feature like Type casting issue. You can see a trimmed version of this issue for productcomments module at https://github.com/PrestaShop/productcomments/pull/144/files

**Comment by ghost** [comment]
Hello @hibatallahAouadni i can confirm the Improvement  we need to change the Charset because he is deprecated

**Comment by ghost** [comment]
Nous devons pouvoir grouper ces deux issues https://github.com/PrestaShop/PrestaShop/issues/28857

**Comment by ghost** [comment]
We must be able to group these two issues #28857

**Comment by leemyongpakvn** [comment]
@okom3pom So merge this issue to #28857 and use it as a generic issue for 10 PR in 10 modules is OK ?

**Comment by leemyongpakvn** [comment]
Merge to https://github.com/PrestaShop/PrestaShop/issues/28857 because they came from the same source - the install function of previous version.
