### ISSUE TITLE
[BO - Search] - Old links redirecting to ModuleCatalog appear and redirect to Page not found

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#28868]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

While searching in BO for Orders (for example), old links redirecting to ModuleCatalog appear and redirect to the Page not found: 

https://user-images.githubusercontent.com/23308427/175934309-7f7b4049-a12f-4a20-a722-2680af5364e3.mp4

### Expected behavior

These old links redirecting to ModuleCatalog shouldn't be displayed

### Steps to reproduce

1. BO > Click on the Search bar
2. Make a search for Orders (for exemple)
3. In the block modules, there are two links displayed
4. Try to click on one of them
5. See error > The page not found is displayed with the error message: `The controller AdminModulesCatalog is missing or invalid.`

### PrestaShop version(s) where the bug happened

8.0.x & develop

### PHP version(s) where the bug happened

7.2

**Comment by ghost** [comment]
Hello @hibatallahAouadni duplicate of https://github.com/PrestaShop/PrestaShop/issues/28303

Fixed by https://github.com/PrestaShop/PrestaShop/pull/28785

Regards

**Comment by hibatallahAouadni** [comment]
@okom3pom no it's not the same bug, why do you think it's a duplicate?

**Comment by ghost** [comment]
It's the same bug but tested one time in 1.7.8x and an other time in 8.0.x

We can keep the two issues but the PR fix the two issue :)

**Comment by ghost** [comment]
But it's possible i need to do a PR for 8.0 and not develop
