### ISSUE TITLE
BO - Products V1 - Error 500 when we add ad invalid image to a product

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#28875]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An error 500  is displayed when adding an invalid image to a product
![image](https://user-images.githubusercontent.com/16067358/175977261-80c547e5-6b6d-4e46-a635-b054e2c29f24.png)

### Expected behavior

We should have an alert
![image](https://user-images.githubusercontent.com/16067358/175977314-b2aea285-1993-4cf5-be7a-e619d1c590c2.png)

### Steps to reproduce

1. Go to BO > Catalog > Products V1
2. Edit a product > Add an invalid image for example .svg, .ico
3. See error: error 500 in the console

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1

**Comment by matks** [comment]
@PrestaEdit submitted a PR
