### ISSUE TITLE
Duplicate type casting in productcomments module

### ISSUE THREAD

**Issue by leemyongpakvn** [PrestaShop/PrestaShop#28879]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Is your feature request related to a problem?

In https://github.com/PrestaShop/productcomments/blob/dev/ProductComment.php and https://github.com/PrestaShop/productcomments/blob/dev/ProductCommentCriterion.php, there are two problems with type casting:
`(int) $id_xyz` is using throughout the function. Code can be simplified by Assign `$id_xyz = (int) $id_xyz` **Once** at top
`Validate::isUnsignedId($id_xyz )` is called at top of the function, then using type cast `(int) ($id_xyz) `**again** below, it is unnecessary.

1. Check https://github.com/PrestaShop/productcomments/blob/dev/ProductComment.php#L90 to L122 
2. Check https://github.com/PrestaShop/productcomments/blob/dev/ProductCommentCriterion.php#L102 and L108
3. Check https://github.com/PrestaShop/productcomments/pull/142/files for a whole view

### Describe the solution you'd like

1. Assign `$id_xyz = (int) $id_xyz` once at top, just use `$id_xyz` in the rest of function.
2. if `Validate::isUnsignedId($id_xyz )` at top, then just use `$id_xyz` in the rest of function.

### If your feature is related to a module, specify its name and its version

productcomments v5.0.1

**Comment by hibatallahAouadni** [comment]
Hello @leemyongpakvn 

Thanks for your issue and your PR!
Could you please simplify and detail the steps to reproduce :pray: 
Waiting for your feedback.

Thanks!

**Comment by leemyongpakvn** [comment]
@hibatallahAouadni Done, 3 steps as you wish. Because this issue is an improvement in PHP code, not a problem happens on FO or BO, you need to read code files for details. The related PR's File changed in Step 3 is the most intuitive way to check. :joy:

**Comment by hibatallahAouadni** [comment]
Hello @leemyongpakvn 

Thanks for your feedback!
> Because this issue is an improvement in PHP code, not a problem happens on FO or BO, you need to read code files for details.

Oh I see! then you have to choose the feature request template not the bug report :wink: 
Editing your issue description!

Thank you for your suggestion. The Developer Team will take it into consideration for future developments. 
Thanks again for your PR :rocket: 

Thank you

**Comment by hibatallahAouadni** [comment]
@PrestaShop/prestashop-core-developers friendly reminder :pray: we need your approval to test the PR :wink:

**Comment by kpodemski** [comment]
@hibatallahAouadni from what I see this PR has been approved by Thomas

**Comment by hibatallahAouadni** [comment]
@kpodemski I can see that but I need a Developer to approve this issue (delete the `NeedsSpecs` and `Waiting for Dev` labels, add the `Ready` label) :wink:

**Comment by kpodemski** [comment]
ok, thx @hibatallahAouadni :) Ready :)
