### ISSUE TITLE
BO - Migrated page - Some buttons are still  in focus state when click on them

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#28874]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On the migrated page, when we click on buttons (which do not refresh the page) => the buttons are still in a focus state
1. In the BO > Catalog > Product V1, the Save button is still in the focus state after saving a product
![image](https://user-images.githubusercontent.com/16067358/175971633-e789a602-fc43-458e-88e4-c877dee724c4.png)
2. In the BO > Orders > Orders list page > Click on refresh statistics 
![image](https://user-images.githubusercontent.com/16067358/177739219-c21aaae3-39f9-428f-ac7c-89850c9030dd.png)
3. In the BO > Orders > Credit slips page > Click on Download credit slip 
![image](https://user-images.githubusercontent.com/16067358/177739728-c0e17581-6821-4c90-a02e-4b029a9fbcda.png)
4. In the BO > Customers > Customers page > Click on `Set required fields for this section` 
![image](https://user-images.githubusercontent.com/16067358/177740102-e859f5b9-bb7a-4f8e-999b-432d6856b38f.png)

### Steps to reproduce

1. Go to BO > Catalog > Products V1
2. Resize the window to 1420px * 914px
3. Edit a product
4. Click on Save & don't click outside
5. See error: the button save is still in the focus state

https://user-images.githubusercontent.com/16067358/175972170-72397220-2532-4c03-8f54-2b095a1cb5b3.mp4

In the PS1786 => ok

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment]
That's normal browser behavior, why it should refocus on something else?

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thanks for your feedback!
But as you can see it's a regression cause we didn't reproduce the issue with PS1786 with the same browser:

https://user-images.githubusercontent.com/23308427/175982499-3d78b491-f191-4513-8e74-6b0a2c62a5ba.mp4

Thanks!

**Comment by NeOMakinG** [comment]
@hibatallahAouadni @khouloudbelguith @jolelievre 

This behavior is totally normal, having a different styling for focus and active states is a common a11y good practice

The old product page was disabling the button, this is why the shadow wasn't visible on the active state

Also, any buttons not disabled will keep the focus state until you click somewhere else on the page, this is normal behavior.

**Comment by jolelievre** [comment]
@NeOMakinG 

ok for the focus but it feels weird to keep the focus one while it's performing an action in ajax no? I would expect it to unfocus at this moment, but why not

**Comment by NeOMakinG** [comment]
> @NeOMakinG
> 
> ok for the focus but it feels weird to keep the focus one while it's performing an action in ajax no? I would expect it to unfocus at this moment, but why not

Most of the time you want to disable the button if it performs an action, or change it to a loader state, this is not a styling issue but more an implementation one to me

**Comment by jolelievre** [comment]
@NeOMakinG Ok, then I guess we can close this one?
