### ISSUE TITLE
[BO]: Class name must be allowed from controller in select render list column 

### ISSUE THREAD

**Issue by Amit-Kumar-Tiwari-Webkul** [PrestaShop/PrestaShop#28881]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Suppose, we have created a select filter from the controller and the list has 100 records. So there must be a possibility to add custom CSS on that field so that we can use the plugin provided by PS (Like chosen) 

![image](https://user-images.githubusercontent.com/23308427/176138706-a47e24a9-a834-4e44-8f9c-a4e586c7787c.png)

### Describe the solution you'd like

The class name must be allowed from the controller in the select render list column.

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @Amit-Kumar-Tiwari-Webkul 

Thanks for your issue and your PR!
But, could you please try to edit your issue description, try to make a change in the two blocks description :pray: 
BTW, I can't access to the screenshot, it seems removed.
Waiting for your feedback.

Thanks!

**Comment by Amit-Kumar-Tiwari-Webkul** [comment]
@hibatallahAouadni , I have updated description

**Comment by hibatallahAouadni** [comment]
Hello @Amit-Kumar-Tiwari-Webkul 

I just updated your issue description, this is what I was asking for :wink: 
Thank you for your suggestion. The Product Team will take it into consideration for future developments. 

Thank you
