### ISSUE TITLE
Updating Product using API overwrites field values

### ISSUE THREAD

**Issue by sebhanz** [PrestaShop/PrestaShop#28880]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

We are importing and updating products using the API using the following object products. However, the API is overwriting out requests for field cache_default_attribute 0 with 1 even when the request definitely specifies 0. 

Can you confirm which DB table product endpoint is using and how can this be fixed as its causing massive issues by deleting prices for us just because of that column being overwritten with '1'? it'

[Request.txt](https://github.com/PrestaShop/PrestaShop/files/8998351/Request.txt)
[Response.txt](https://github.com/PrestaShop/PrestaShop/files/8998357/Response.txt)
s

### Expected behavior

The expected behaviour is for the API to send and accept the value for this field as specified within the request. 

### Steps to reproduce

Please see the attached request and response 

1. Set you cache_default_attribute to 0 on an item 
2. Update that item using API (PUT Product) (body can be found in "Request.txt")
3. Check that product again in DB and see if cache_default_attribute was overwritten to 1 or blank

### PrestaShop version(s) where the bug happened

1.7.6.7

**Comment by hibatallahAouadni** [comment]
Hello @sebhanz 

Please provide clear and concise steps to reproduce the issue :pray: 
Waiting for your feedback.

Thanks!

**Comment by sebhanz** [comment]
Steps to reproduce
1. Set you cache_default_attribute to 0 on an item 
2. Update that item using API (PUT Product) (body can be found in "Request.txt")
3. Check that product again in DB and see if cache_default_attribute was overwritten to 1 or blank

**Comment by hibatallahAouadni** [comment]
Hello @sebhanz 

Thanks for your feedback!
> Set you cache_default_attribute to 0 on an item

What do you mean by this? :thinking: Could you please explain it more, or provide in which file should I set the cache configuration on 0 :pray: 
Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @sebhanz 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
