### ISSUE TITLE
[BO]: Unable to get correct class name on render list, due to this CSS is not applied

### ISSUE THREAD

**Issue by Amit-Kumar-Tiwari-Webkul** [PrestaShop/PrestaShop#28889]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the render list, when we select any value from the list header correct class is not applied https://prnt.sc/42-UBY4mt8Fw

### Expected behavior

there's should be space between filter and center

### Steps to reproduce

In the render list, when we select any value from the list header correct class is not applied 

![image](https://user-images.githubusercontent.com/23308427/176233412-b03debab-8b94-46b9-9b74-f3f94e1ef163.png)

### PrestaShop version(s) where the bug happened

1.7.8.6

**Comment by hibatallahAouadni** [comment]
Hello @Amit-Kumar-Tiwari-Webkul 

I was able to reproduce the issue with PrestaShop version 1.7.6.7 and 8.0.x. I’ll add this to the debug backlog so that it’s fixed.
Thanks for your PR :rocket: 

Thank you
