### ISSUE TITLE
BO - Product V1 - Shipping & Pricing tab - Units are not well displayed

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#28892]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Catalog > Product V1 > Shipping tab, the units are not displayed
![image](https://user-images.githubusercontent.com/16067358/176165218-c821afbc-321b-44ad-8b07-91bd6a52604d.png)

In the BO > Catalog > Product V1 > Pricing tab > Add new specific price >  the units are not displayed 
![image](https://user-images.githubusercontent.com/16067358/176168521-1c3429e1-0ef0-4a54-a913-485fc34d315d.png)

### Expected behavior

PS1786 => ok
![image](https://user-images.githubusercontent.com/16067358/176165349-cf4182cb-3e4a-4009-b891-d79e7a689064.png)
PS1786 => ok
![image](https://user-images.githubusercontent.com/16067358/176168612-62a54f37-9561-4a2c-b879-d1375f477d52.png)

### Steps to reproduce

1. Go to BO > Catalog > Products V1
2. Add/Edit a product
3. In the Shipping tab > See error: the units are not well displayed
4. In the Pricing tab > Add a specific  price > See error: the units are not well displayed

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1

**Comment by micka-fdz** [comment]
Hi @tom-combet, maybe related to your PR about unit refactoring?

**Comment by matks** [comment]
@FabienPapet takes it

**Comment by AureRita** [comment]
fixes #29054
