### ISSUE TITLE
BO - Mouvements page - Sorting by product name is NOK

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#28895]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Catalog > Mouvements > When we try to sort by product name > The sort is NOK
![image](https://user-images.githubusercontent.com/16067358/176215564-942dad42-d346-47ba-9b03-688ac2c5addf.png)

With PS1786 => we have this
![image](https://user-images.githubusercontent.com/16067358/176215739-d328a6d6-419d-4a24-82f9-2085338b2bd2.png)

Seems related: https://github.com/PrestaShop/PrestaShop/pull/28140

### Expected behavior

The product name should be replaced by Product ID 

### Steps to reproduce

1. Create some products with aaaa / bbbb / ccccc & edit the quantity for each product
2. Go to BO > Catalog > Stocks page > Mouvements tab
3. Try to sort by `Product name`
4. See error: The sort is not working with product name, but with the product ID

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1

**Comment by marsaldev** [comment]
Hi @khouloudbelguith, I'm almost sure that when I fixed the stock tab the PR affected also the movements tab, we need to update movements tab too, can I proceed to new PR with resolution?

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29047
