### ISSUE TITLE
BO - Customer view page - The status of the voucher is always disabled

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#28896]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Customers > Customer view page, the status of the voucher is always disabled
![image](https://user-images.githubusercontent.com/16067358/176227675-b321df9b-1c76-4a7e-b56d-ec21004f6807.png)
![image](https://user-images.githubusercontent.com/16067358/176227816-da658138-6360-4673-8c3e-a6dab84ec977.png)

### Steps to reproduce

1. Create cart rules with the enabled status
2. Go to BO > Customers > View customer
3. In the voucher section, see the error: all status are disabled

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/28898
