### ISSUE TITLE
Select product variation when  related products on the bottom product page 

### ISSUE THREAD

**Issue by linquant** [PrestaShop/PrestaShop#28891]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I select a product variation on product page, request return code 500.

![image](https://user-images.githubusercontent.com/6512186/176162412-6f11b3f6-bdde-41fb-9918-a53804fc30b0.png)

I think there are to many id-product in the paylaod.

![image](https://user-images.githubusercontent.com/6512186/176162947-cf670ec5-1d3f-4b44-8166-593d5f5b19f9.png)

Excess id_products correspond to the products in the sliders , that include a TPL block ( {include file='catalog/_partials/miniatures/product.tpl' product=$product_accessory})

![image](https://user-images.githubusercontent.com/6512186/176164270-17a7a5d0-9df6-4814-bc02-74178cf5b6d3.png)

I can fix to change file : themes/core.js. I add .first() after  u = s.find(o.default.selectors.quantityWanted), d = s.find("form:first")

![image](https://user-images.githubusercontent.com/6512186/176163724-f201ab79-7198-483d-93f5-91cc21daf085.png)

### Steps to reproduce

You need have a slider product on Product page with button to add card ans preview. 

Go Product page with variants

Click on variants button

You can try in chrome console these jquery : 

`$('.product-actions, .js-product-actions').find("form:first")
` ==> return to much result

`$('.product-actions, .js-product-actions').find("form:first").first()` ==> return the first result

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4

**Comment by Hlavtox** [comment]
The main problem is somebody using selectors like `form:first` in the first place. 🙄

@NeOMakinG Can you check this bro?

**Comment by hibatallahAouadni** [comment]
Hello @linquant 

Thanks for reporting the issue! 
Ping @PrestaShop/prestashop-core-developers someone please try to reproduce the issue, it's too technical for me 😅 

Thanks in advance!

**Comment by NeOMakinG** [comment]
> Hello @linquant
> 
> Thanks for reporting the issue! Ping @PrestaShop/prestashop-core-developers someone please try to reproduce the issue, it's too technical for me 😅
> 
> Thanks in advance!

I'm on it don't worry

**Comment by NeOMakinG** [comment]
@linquant 

I know there is a bug, obviously, but I need to reproduce it in order to test the fix and I'm unable to reproduce it, could you detail the way you reproduce this?

- I did add a form to `catalog/_partials/miniatures/product.tpl` :

```html
{if $product.add_to_cart_url}
<form action="{$urls.pages.cart}" method="post">
<input type="hidden" value="{$product.id_product}" name="id_product">
<input type="hidden" name="token" value="{$static_token}" />
<input type="number" name="qty" value="1" onclick="return false;">
<button data-button-action="add-to-cart">Buy</button>
</form>
{/if}
```

- I have some product list inside the product page, also added to a hook inside `.product-actions`

Impossible to reproduce 😄

**Comment by linquant** [comment]
This problem appear when they have many  id_product. When you add a slider containing product with callToAction. You have other id_product.

![image](https://user-images.githubusercontent.com/6512186/176435818-5f91fcff-c300-4aeb-850e-de892645d3b6.png)


Le jquery Selector return all Id_product. You must get only the first.

**Comment by NeOMakinG** [comment]
> This problem appear when they have many id_product. When you add a slider containing product with callToAction. You have other id_product.
> 
> ![image](https://user-images.githubusercontent.com/6512186/176435818-5f91fcff-c300-4aeb-850e-de892645d3b6.png)
> 
> Le jquery Selector return all Id_product. You must get only the first.

Yeah I know this, but I can't reproduce it myself, I can't find a way to reproduce it on the `classic` theme, seems like I miss something, where did you add the product carousel exactly?

**Comment by linquant** [comment]
In my theme, i have this code. I hope , this code help you to reproduce 

```
		<section class="product-accessories clearfix">
      <h2 class="h1 products-section-title text-uppercase">
		  {l s='You might also like' d='Shop.Theme.Catalog'}
		  </h2>
         <div class="products">
		 	{if $productCount >= $sliderFor}
				<ul id="accessories-carousel" class="tm-carousel product_list">
			{else}
				<ul id="accessories-grid" class="accessories_grid product_list grid row gridcount">
			{/if}
			{foreach from=$accessories item="product_accessory"}
              {block name='product_miniature'}
                <li class="{if $productCount >= $sliderFor}item{else}product_item col-xs-6 col-sm-6 col-md-4 col-lg-4{/if}">
				{include file='catalog/_partials/miniatures/product.tpl' product=$product_accessory}
				</li>
              {/block}
            {/foreach}
			</ul>

			{if $productCount >= $sliderFor}
				<div class="customNavigation">
					<a class="btn prev accessories_prev"></a>
					<a class="btn next accessories_next"></a>
				</div>
			{/if}

          </div>
        </section>
```

This is location of  this file 

![image](https://user-images.githubusercontent.com/6512186/176759899-49595e11-c74b-49d9-ad69-f0cc96f7db09.png)




if you want we can organize a webcall to show you code of website.

**Comment by NeOMakinG** [comment]
@linquant I'll try to reproduce it with your code, if I can't, let's organize it :)

**Comment by NeOMakinG** [comment]
@linquant https://www.prestashop-project.org/slack/

Come on slack when you want, I'll need you to reproduce :p

**Comment by hibatallahAouadni** [comment]
@linquant @NeOMakinG soo, should we close the issue? Cause it seems that you continue your discussion on Slack :sweat_smile:

**Comment by hibatallahAouadni** [comment]
Hello @linquant 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
