### ISSUE TITLE
BO - Module manager - The module to configure is not removed from the alerts tab after uninstalling it

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#28919]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After fresh install > In the BO > Modules > Module Manager page > Alerts tab,
Try to uninstall the module `ps_checkpayment` without removing the folder
The alert  `Uninstall action on module ps_checkpayment succeeded.` is well displayed, but the module is not removed from the alerts tab
![image](https://user-images.githubusercontent.com/16067358/176651762-1b24ea1e-a310-4a3e-bcc5-794e50a79923.png)
It should be removed as in the PS1786

https://user-images.githubusercontent.com/16067358/176652308-0cad0c82-099a-42fa-a52a-088e5a244f56.mp4

### Expected behavior

As discussed with @MatShir and @atomiix, the module should be removed from the alerts tab

### Steps to reproduce

1. Go to BO > Modules > Module manager > Alerts tab
2. Uninstall the module  `ps_checkpayment` without removing the folder
3. See error > The module is not removed from the alerts tab

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1

**Comment by ghost** [comment]
Hello @khouloudbelguith can you try with this PR 

https://github.com/PrestaShop/ps_checkpayment/pull/48

Normaly it's fixed

**Comment by atomiix** [comment]
@okom3pom I think we should fix it in the core as well, as an extra check.

**Comment by ghost** [comment]
@atomiix   Good idea! I assign it to myself

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/28936
