### ISSUE TITLE
BO - new product page bug v8.0

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#28912]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![image](https://user-images.githubusercontent.com/62474824/176545194-99e643fb-8296-4928-b501-55ad0bf0c10a.png)

### Steps to reproduce

1. new product page
2. specific prices

### PrestaShop version(s) where the bug happened

8.0

**Comment by sLorenzini** [comment]
hello @alfonsolr09,

What is exactly the bug you want to report on specific prices?
I have the same configuration on 1.7.8.6 version, you can change the current price of the product and add a discount:
![1786-product-page](https://user-images.githubusercontent.com/2854834/176636922-11337820-c990-4dfb-b5ac-e2e26894c749.png)


On 8.0.0, it is the same thing. On your screenshot, it is written "**At least** one of the following must be activated" and not "**Only** one of the following must be activated"

Waiting for your feedback

Thanks

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by alfonsolr09** [comment]
What is the point of applying a discount to a specific price? It is what I do not understand and that is why I said that I think it does not make much sense to be able to have both boxes active at the same time

ping @hibatallahAouadni @sLorenzini

**Comment by hibatallahAouadni** [comment]
Hello @alfonsolr09 

Well, your point of view is right! But, IMHO there's merchants needs both fields, let me explain:
As a merchant I need to attract customers but I can't afford to make discounts.
The solution is to change the product price and apply a discount, so that the customer is attracted by the discount ad and he purchases the product with its original price.
Well, this is my point of view, but I will check with the Product Team ASAP and keep you informed.

Thanks!

**Comment by alfonsolr09** [comment]
yes, but you can do that by raising the price of the product and applying the discount. the product price box (tax exc.) is the same as the product price box outside this menu. what's the point?
