### ISSUE TITLE
error with product description on new product page 

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#28914]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

https://watch.screencastify.com/v/AIPpQq6ImB0jNx8bWd5r

### Steps to reproduce

...

### PrestaShop version(s) where the bug happened

8.0

**Comment by sLorenzini** [comment]
Hello @alfonsolr09,

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template and provide clear and concise steps to reproduce the bug**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
