### ISSUE TITLE
BO - An unclear error is displayed when upgrading a too large module using the zip

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#28924]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Thanks, @PrestaShop/qa-functional team for your help in investigating this issue :heart: 
To test a release of any module, I need to upgrade the module using a zip
But, in the 80x branch, an error is displayed when we use a **too large** module (because we launched the `npm install`) 
To create a wishlist zip from Github, we follow these steps:

1.  git clone git@github.com:PrestaShop/blockwishlist.git
2. cd blockwishlist
3. `git prc origin [id_pr] dev `or you can use those commands `git fetch origin pull/IdPR/head:pr-IdPR && git checkout pr-IdPR && git reset --hard && git clean -fd && git rebase origin/dev && composer install`
4. **npm install**
5. Create a zip

Now, in the BO > Modules > Module manager, when we try to upgrade to this new zip by uploading it => an error is displayed
In some cases, we have this error
![image](https://user-images.githubusercontent.com/16067358/177360196-bc3a992d-49ab-44ed-a989-7fbd4d91ded0.png)
In other cases, we have this error
![image](https://user-images.githubusercontent.com/16067358/177360355-2db7cc39-b59a-4e0d-a42c-1c22d077f141.png)

https://user-images.githubusercontent.com/16067358/177360536-f4f64b12-34bc-46a0-b962-b5d8e6633ade.mp4

I checked my configuration

- phpinfo file 

![image](https://user-images.githubusercontent.com/16067358/177360721-bf874eb5-2894-499f-99e8-6beb2c23d310.png)

- BO > Advanced Parmeters > Administration page 

![image](https://user-images.githubusercontent.com/16067358/177360796-74f50043-72dd-426f-9b84-c1ac74a8d685.png)

### Expected behavior
In the PS1786 > we have this alert 
![image](https://user-images.githubusercontent.com/16067358/177360485-7cefdfb6-edc1-4673-bc5e-6dcd002d27e4.png)

### Steps to reproduce

1. Install 8.0.x
2. create a zip of any PR of the module [blockwishlist](https://github.com/PrestaShop/blockwishlist) following these steps:
1.  git clone git@github.com:PrestaShop/blockwishlist.git
2. cd blockwishlist
3. git prc origin [id_pr] dev
4. **npm install**
5. Create a zip
6. Go to BO > Modules > Module manager > Upload the new zip
7. See error

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1

**Comment by khouloudbelguith** [comment]
Hi @MatShir,

I updated the issue, it is reproduced with a too large module.
So, I think it is a minor issue.

Thanks!

**Comment by matks** [comment]
@jolelievre you assigned yourself to this topic in July, did you submit a PR? did you do something?

**Comment by matks** [comment]
@khouloudbelguith I am sorry but this issue description cannot be used by people who do not have a deep knowledge of the project 😞  .


> 3. git prc origin [id_pr] dev

This is a git alias used by QA team only


> But, in the 80x branch, an error is displayed when we use a **too large** module (because we launched the `npm install`) 

I think not all modules do use npm dependencies 😅 

> ### Expected behavior
_No response_

Without "expected behavior" developers cannot fix this problem. If the module is too large, should we display an information message? Then we need the wording ?

**Comment by khouloudbelguith** [comment]
Hi @matks,

Thanks for your feedback.
About the command `git prc origin [id_pr] dev`, I updated the issue

For the expected behavior, I added a screenshot about the error displayed in the PS1.7.8.7.

Thanks!

**Comment by matks** [comment]
@MeKeyCool starts it

**Comment by MeKeyCool** [comment]
From investigations, problem came from https://github.com/PrestaShop/PrestaShop/pull/25245

Can't test module upload in those commits :
- 6b61197ae2c36ad00eba529b7d02a6538e5d3f2c
- e6b8fcf68823c7bafdc19c574382f0305c9bedda
- 22a3e4fc65ab6ae43c2d7aadd969403fda4b23fc
- 626a59346f47c6cea6f2bae1384d824a7ef8d14a
- 9afa9b744cb73dd67516277f160d592b97c32801
- f0c4a6ad4045e0d72b9dd718fad43cba6ffc7ee4
- 8a6765299a1c586c774f130e43ce024ca8cc6dad
- f3cba85caf3e1983b839bcaded197b640ff7a89f
- da5a5de3ba6671cc1aa563700db7eaf7f5463900

But before them, it works well, after them it doesn't.

First responsible is probably this one : 8a6765299a1c586c774f130e43ce024ca8cc6dad
Last working commit : ea89268

**Comment by HanaRebaiQA** [comment]
Hello everybody,

@khouloudbelguith , @AureRita and me have checked again this issue. We did not reproduced it in our cases.

1. Create a .zip for **`blockwishlist v2.1.1`**
2. In PS 8.0.x > module manager > upload the module 
3. Check that the module is well uploaded with **v2.1.1**
4. Create a .zip for **`blockwishlist v2.1.2`**
5. In BO > Module manager > Upload the module v2.1.2
6. Check that the module is well uploaded and well upgraded

https://user-images.githubusercontent.com/92912932/198574759-79fe8cfe-92b2-4ef0-a48b-1017c70f9eca.mp4


So, we'll close the issue.

Thank You!
