### ISSUE TITLE
BO - Validation of positive integer field of the module configuration form - productcomments

### ISSUE THREAD

**Issue by leemyongpakvn** [PrestaShop/PrestaShop#28929]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

The module configuration form of productcomments has 2 fields that need Positive integer input.
In version 5.0.1, there is no validation so user can input any character there and get Setting updated without warning.
![validation_integer_positive_for_productcomments_needed](https://user-images.githubusercontent.com/3759923/176882148-86491668-27e6-4a03-810a-4d220409dc1f.png)

### Describe the solution you'd like

Add positive integer validations for these 2 fields and display warning if user input invalid character there.
![validation_integer_positive_for_productcomments_fixed](https://user-images.githubusercontent.com/3759923/176882158-3ebed308-c36e-4a4e-8b5e-fddf973dc7c6.png)

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by florine2623** [comment]
Hello @leemyongpakvn ,

Thanks for your report !
I reproduce the issue with PrestaShop version 1.7.8.x and 8.0.x, using productcomments v5.0.1, I'll add this to the backlog so it can be fixed.

https://user-images.githubusercontent.com/16019289/176891934-fb9ce2ed-5cf1-4ef6-8bf2-137baf24218b.mov

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
