### ISSUE TITLE
FO - jQuery event shorthand is deprecated warning - module Productcomments

### ISSUE THREAD

**Issue by leemyongpakvn** [PrestaShop/PrestaShop#28935]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

`change`, `hover`, and `submit` event shorthand are deprecated in jQuery 3. 
jquery-migrate keep warnings about them before fix automatically in classic-theme and some modules such as ps_searchbar and productcomments.
This issue is for module productcomments.
![ps178_jQuery_ChangeHoverSubmit_shorthand_deprecated_Modules_productcomments](https://user-images.githubusercontent.com/3759923/176988256-d4049d24-b47e-4f2d-afde-8b880a75e365.png)

### Expected behavior

Replace deprecated shorthand by its full version event to satisfy jquery-migrate check.

### Steps to reproduce

1. Need module productcomments installed and enabled.
2. Open Product page and check Web browser console.

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

productcomments 5.0.1

**Comment by hibatallahAouadni** [comment]
Hello @leemyongpakvn 

Thanks for reporting the issue and your PR :rocket: 
I reproduce the issue with PS_1.7.7.7, PS_1.7.8.5 and PS_8.0.0!
I’ll add this to the debug backlog so that it’s fixed.

Thank you
