### ISSUE TITLE
Payment by card is not displayed on the product page

### ISSUE THREAD

**Issue by ewonta** [PrestaShop/PrestaShop#28937]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Module PrestaShop Checkout

My theme executes the order directly from the product card, and the module does not activate the card payment method, but it activates it on the checkout page and everything works fine.

https://toystore-hooge.de/schulblocke/2597-brunnen_schulblock_a4__50_blatt__gelocht__lineatur_27-4003273163737.html
On this link you can see the work of the module, there is an error in the console

![image](https://user-images.githubusercontent.com/13940741/176995570-680e35ae-db58-4dc4-bcca-7712ea9be51b.png)

### Expected behavior

The ability to initialize all payment methods on any page

### Steps to reproduce

1) Go to the website
https://toystore-hooge.de/schulblocke/2597-brunnen_schulblock_a4__50_blatt__gelocht__lineatur_27-4003273163737.html

2) Click on the "Buy Now" button

3) In the payment methods there will only be "payment via PayPal"
![image](https://user-images.githubusercontent.com/13940741/176995676-5106841e-cbda-41b1-b1a0-b054513a774c.png)

4) Go to checkout

5) Card payment will be available in payment methods
![image](https://user-images.githubusercontent.com/13940741/176995690-ca60f31b-5f41-4876-a298-a6f9e5a8e83a.png)

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_checkout v2.20.1

**Comment by matks** [comment]
Hello @dmitrij1988  ,

This repository is a bug tracker for the prestashop project and ps_checkout module is a product of PrestaShop company, so we cannot help you with that.

I would suggest to contact the developer of the module, directly in the Help section of the module :
<img width="1205" alt="Screenshot 2022-02-22 at 10 55 37" src="https://user-images.githubusercontent.com/16019289/155108016-4b34db62-41da-4878-b784-049f9e0452ab.png">
