### ISSUE TITLE
Impossible d'ajouter et modifier du contenu de Réassurance après MàJ vers 1.7.8.6

### ISSUE THREAD

**Issue by bnofao** [PrestaShop/PrestaShop#28945]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Bonjour,
Après avoir faire une mise à jour vers la dernière version 1.7.8.6 de Prestashop avec le module 1-Click Upgrade, je rencontre un souci avec le module Réassurance. Il est impossible d'ajouter et modifier du contenu

### Expected behavior

Pouvoir ajouter des contenus de réassurance

### Steps to reproduce

Aucune idée de comment reproduire cela

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4

**Comment by NeOMakinG** [comment]
@bnofao 

Thanks for your report.

As PrestaShop users are international, can you please translate the issue?

**Comment by hibatallahAouadni** [comment]
Hello @bnofao 

Please send your request in English. English is the norm on GitHub.

Thank you
