### ISSUE TITLE
Missing translations on meta pages

### ISSUE THREAD

**Issue by micka-fdz** [PrestaShop/PrestaShop#28944]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On clean install of PrestaShop, several translations are missing on meta pages.

- "Brands" on `manufacturers` page title
- "Brands list" on `manufacturers` page description
- "brands" on `manufacturers` page url rewrite
- "Our special products" on `prices-drop` page description

### Expected behavior

No missing translations.

### Steps to reproduce

1. Make a clean install of PrestaShop in another language than English (e.g. French)
2. Go to `Paramètres de la boutique > Trafic et SEO`
3. See missing translations on `manufacturers` and `prices-drop` pages

### PrestaShop version(s) where the bug happened

1.7.x.x

**Comment by hibatallahAouadni** [comment]
Hello @micka-fdz 

Thanks for your PR :rocket: 
Could you please provide a screenshot of the problem, cause it seems that I didn't understand the issue :sweat: 
Waiting for your feedback.

Thanks!

**Comment by micka-fdz** [comment]
Hi @hibatallahAouadni,

It's just about missing translations when your install isn't in English... You just have to follow all "steps to reproduce" and see missing translations on `manufacturers` and `prices-drop` pages (on first table).

**Comment by okom3pom** [comment]
@hibatallahAouadni  As you can see 

![Screenshot (55)](https://user-images.githubusercontent.com/5064590/177191690-6a0d484a-c762-4bb5-ac4d-6024f7d34bc8.png)

**Comment by ghost** [comment]
@hibatallahAouadni as you can see 

![Screenshot (56)](https://user-images.githubusercontent.com/5064590/177192296-c5227791-1e47-4e4c-8549-9450fa5be710.png)

**Comment by micka-fdz** [comment]
e.g. in French:
- "Brands" should be "Marques"
- "Brands list" should be "Liste de marques"
- "brands" should be "marques"
- "Our special products" should be "Nos produits en promotion"

**Comment by hibatallahAouadni** [comment]
Hello @micka-fdz 

Thanks for your feedback!
@okom3pom thanks for the screenshot :pray: 
I reproduce the issue with PS1777, PS1786 and PS80x, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/177311541-88028159-bcdb-4377-9dd9-6c7da75400db.png)

I’ll add this to the debug backlog so that it’s fixed. Thanks again for your PR :rocket: 

Thank you
