### ISSUE TITLE
FO - Proceed to checkout is NOK when the product is allowed when out of stock and Allow ordering of out-of-stock products parameter is disabled with product V2

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#28958]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Proceed to checkout is NOK when the product is allowed when out of stock and Allow ordering of out-of-stock products parameter is disabled with product V2

https://user-images.githubusercontent.com/92912932/177306715-269046a6-8572-4572-aa4c-e95d480f942f.mp4

### Expected behavior

Proceed to checkout is OK

### Steps to reproduce

1. BO> CONFIGURE > Advanced parameters > New & Experimental Features > Enable the product V2 page 
2. Create a new product V2 with combinations 
3. Generate combinations
4. Select `Allow orders `in `When out of stock `section
5. BO > CONFIGURE > Shop Parameters > Product Settings > Disable `Allow ordering of out-of-stock products` parameter
6. Go to FO > Add the created product to cart
7. Increase the quantity when the error message for quantity is displayed
8. Click on Proceed to checkout 
9. See error > The page still in Shopping cart process and there is no possibility to continue the order
 

### PrestaShop version(s) where the bug happened

8.0.0 

### PHP version(s) where the bug happened

7.2

**Comment by kpodemski** [comment]
@HanaRebaiQA is it ok on a legacy product page? as some pull requests might have an impact on this feature:

https://github.com/PrestaShop/PrestaShop/pull/24798
https://github.com/PrestaShop/PrestaShop/pull/28315/

**Comment by HanaRebaiQA** [comment]
Hello @kpodemski 

It's OK with product V1. Here is a screen-record : 

https://user-images.githubusercontent.com/92912932/177311432-e1bf6b3b-805c-4947-8e2b-be25c8578772.mp4

Thanks!

**Comment by HanaRebaiQA** [comment]
Fixed in #29132
