### ISSUE TITLE
hook actionProductFormBuilderModifier not called

### ISSUE THREAD

**Issue by fc-mbouzidi** [PrestaShop/PrestaShop#28955]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi,

On Prestashop 1.7.8.5, I'm trying to modify the admin product form using the hook actionProductFormBuilderModifier (or actionProductInformationFormBuilderModifier) but it doesn't work.

I display the form name and it doesn't appear on the Product Form

### Expected behavior

Modify fields in the back-Office product form

### Steps to reproduce

1. On the fil /src/Core/Form/IdentifiableObject/Builder/Formbuilder.php, add 
`var_dump(Container::camelize($formBuilder->getName()));` on line 137.

2. Open the Customer back-office form, it display the name of the form

3. Open the Product back-office form and the name of the form is not displayed.

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.1

**Comment by hibatallahAouadni** [comment]
Hello @fc-mbouzidi 

Thanks for reporting the issue!
Ping @PrestaShop/prestashop-core-developers someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by kpodemski** [comment]
The way the product page has been created for PrestaShop 1.7 is different than some of the other Symfony-based pages. You can expect a more extendable product page after its second version is released.

More details:
https://github.com/PrestaShop/PrestaShop/pull/28752

**Comment by fc-mbouzidi** [comment]
Thanks for your feedback. 
So if I understand well, in v 1.7.8.5 if I want to add new fields in the product form I have to use hooks like displayAdminProductsMainStepRightColumnBottom() instead of actionProductFormBuilderModifier() ?

**Comment by kpodemski** [comment]
@fc-mbouzidi exactly, there's an example module from one of the project's maintainers, @PululuK showing how to do that:
https://github.com/PululuK/democustomfields17

**Comment by fc-mbouzidi** [comment]
Thanks a lot and sorry to thought that it was a bug
