### ISSUE TITLE
Slow speed in bo to open product

### ISSUE THREAD

**Issue by phanie44** [PrestaShop/PrestaShop#28951]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi,

Since  updated PS from 1.7.5.4 to 1.7.8.5 , I have slow speed to access to each product page details in the BO only (35 s to access to a product page)

The speed is fine in the Front.

How can I check all the data are correct in the DB ?

Thanks for your feedback.

Regards.

### Steps to reproduce

To look at the problem, I actived the debug mode.
Then the speed to access to the product details is correct with no issue.

When I active the profiling mode, then I have an error 503 to access to the product list (in BO).

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @phanie44 

Could you please check this issue #24975, cause it seems similar to your problem.
Waiting for your feedback.

Thanks!

**Comment by AureRita** [comment]
Hi @phanie44  ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thanks
