### ISSUE TITLE
Redundant function in ps_googleanalytics module - class Handler

### ISSUE THREAD

**Issue by leemyongpakvn** [PrestaShop/PrestaShop#28953]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

In https://github.com/PrestaShop/ps_googleanalytics/blob/dev/classes/Handler/ModuleHandler.php#L32-L49, we have a function named **isModuleEnabled** that reinvents `isEnabled` function and uses deprecated (since PS 1.7) `isInstalled` function of the core `Module` class.
Looking back to the release history, we can that see it was introduced by @apacios [in version 4.0.0 PR#50](https://github.com/PrestaShop/ps_googleanalytics/pull/50/files#diff-4799101e4485247b3085dcf0308eec19cc264509a07e348b8eb57bec7bbde5f0R34-R50) with hard code `$module->registerHook('displayHome');` inside. Then @matks improved it by adding a new function **isModuleEnabledAndHookedOn** with the second flexible parameter `$hookName` in [version 4.1.0 PR#73](https://github.com/PrestaShop/ps_googleanalytics/pull/73/files#diff-4799101e4485247b3085dcf0308eec19cc264509a07e348b8eb57bec7bbde5f0L50-R67)

### Describe the solution you'd like

In the next version, we can safely remove redundant (now) function **isModuleEnabled** and simplify function **isModuleEnabledAndHookedOn** like this
```
    public function isModuleEnabledAndHookedOn($moduleName, $hookName)
    {
        $module = Module::getInstanceByName($moduleName);
        return Module::isEnabled($moduleName) && $module->isRegisteredInHook($hookName);
    }
```

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @leemyongpakvn 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by leemyongpakvn** [comment]
Close due to Backward Compatibility concern as discussed in the PR.
