### ISSUE TITLE
[BO] Module Manager - When you click twice on upgrade/install button, you've a red notice

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#28965]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

1] When you have a module that is not installed, you can install it when you clic on the button install. If, after that, you clic again on the install button, you'll have a red notice "Unfortunately, the module did not return additional details." as you can see : 

https://user-images.githubusercontent.com/100699445/177347959-f5c60918-1fb0-4339-81c5-958bce5dbbf0.mp4

2] When you've a module already installed and you take a PR, it'll let you upgrade your module. After the upgrade, clic another time on upgrade, you'll have the red notice "Unfortunately, the module did not return additional details." As we'll see on this video : 

https://user-images.githubusercontent.com/100699445/177350117-3e10988e-1443-41d9-bb3e-a0e6bd2ed32b.mp4

### Expected behavior

1] We want a change on the display of the button 

2] We want a green notice " Upgrade action on module ps_checkpayment succeeded" 

### Steps to reproduce

1] 1. Go on BO > Modules > Modules manager 
2. Uninstall the module "Order Notifications on the Favicon" 
3. Reload the website
4. Search the module  "Order Notifications on the Favicon" 
5. Install it 
6. Wait for the end of the installation 
7. As you can do it, Clic another time on install 
8. You'll get the red notice 

2] 1. Uninstall your current version of the module checkpayement (clic on the checkbox to uninstall also the folder)
2. Install this version of [ps_checkpayment.zip](https://github.com/PrestaShop/PrestaShop/files/9047258/ps_checkpayment.zip)
3. Reload the website to see if it's the correct version 
4. Install this PR https://github.com/PrestaShop/ps_checkpayment/pull/40
5. Reload the website and you'll see that you've one module to upgrade 
6. Clic on update 
7. Wait until the end of the upgrade
8. As you can do it, Clic another time on update 
9. You'll get the red notice 

 

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1

**Comment by FabienPapet** [comment]
I'll take this one

**Comment by FabienPapet** [comment]
I'll take this one

**Comment by FabienPapet** [comment]
Non-reproductible, checked with @AureRita
