### ISSUE TITLE
Combinations feature disabled - Product V2 - We can create a product with combinations

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#28967]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Advanced Parameters > Performance page > when we disable the combinations feature, we can still add a product with combinations or change the type product to a product with combinations

This issue is reproduced with PS1786 / 8.0.x

### Expected behavior

The feature can't be disabled if the there is at least on combination in the product catalog. If the feature is disabled, the combination option on the creation form modal and the product changement modal is not displayed and can't be selected.

### Steps to reproduce

1. Delete all products with combinations
2. Go to BO > Advanced Parameters > Performance page
3. Disable combinations
4. Go to BO > Advanced Parameters > New & experimental features page
5. Enable a New product page
6. Go to BO > Catalog > Product V2
7. Add a product with combinations => NOK, the type combinations should be hidden: ping @MatShir what do you think?
8. Edit any product > Change the type of product with combinations => NOK: The type combinations should be hidden ping @MatShir, what do you think?

### PrestaShop version(s) where the bug happened

1.7.8.6, 8.0.x

### PHP version(s) where the bug happened

8.1

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29837
