### ISSUE TITLE
FO - ps_facetedsearch - A bad display afer clearing a filter of no result

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#28966]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the FO > When we create a filter with no result, then we clear it, the products are not displayed

PS1778 + ps_facetedsearch v3.7.1 => ok  / PS1778 + ps_facetedsearch 3.8.0 => OK
PS1786 + ps_facetedsearch 3.8.0 => NOK / PS1786 + ps_facetedsearch 3.7.1 => NOK / 8.0.x + ps_facetedsearch 3.8.0 => NOK

### Steps to reproduce

1. Go to FO > Click on the `All products` link
2. Try to filter by price 41€ ~ 42€ & size = S => no result
3. Click on clear all or remove any active filter
4. See error: the products are not well displayed: there is no space between products 

![image](https://user-images.githubusercontent.com/16067358/177351150-f60dd031-e9a7-4ade-8527-d9a103305b87.png)
Refresh the page => OK 
![image](https://user-images.githubusercontent.com/16067358/177351326-11748380-4bdb-4138-a48f-969edc6c7243.png)

### PrestaShop version(s) where the bug happened

1.7.8.6, 8.0.x

### PHP version(s) where the bug happened

8.1

**Comment by leemyongpakvn** [comment]
@khouloudbelguith I made a PR for this issue. Please check.

**Comment by MatShir** [comment]
NB: Keep the issue opened for the 1.7.8.x PR

**Comment by matks** [comment]
Fixed for 1.7.8.8 thanks to @leemyongpakvn in https://github.com/PrestaShop/PrestaShop/pull/29471
