### ISSUE TITLE
Use Symfony services which are used in modern controller in ModuleFrontController

### ISSUE THREAD

**Issue by alisamie97** [PrestaShop/PrestaShop#28960]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

I would like to know if it is possible or not. Because PrestaShop core has a lot of good and reusable classes which are unfortunately  only accessible in `FrameworkBundleAdminController`.

I found these links but i think they miss some data. I tried to use them and failed:
1. https://www.prestashop.com/forums/topic/664453-use-symfony-kernel-on-front-module/
2. https://blog.floriancourgey.com/2018/05/how-to-work-with-the-symfony-kernel-anywhere-in-prestashop-1-7/

For example in BO there is a page for import. I have found the controller which is  a modern one. This is the name of controller: `ImportController`.
I walked through the code and found this below. I wanted to reuse this part of the code and failed.
```
$importer = $this->get('prestashop.core.import.importer');
$importConfigFactory = $this->get('prestashop.core.import.config_factory');
$runtimeConfigFactory = $this->get('prestashop.core.import.runtime_config_factory');
$importHandlerFinder = $this->get('prestashop.adapter.import.handler_finder');

$importConfig = $importConfigFactory->buildFromRequest($request);
$runtimeConfig = $runtimeConfigFactory->buildFromRequest($request);

$importer->import(
    $importConfig,
    $runtimeConfig,
    $importHandlerFinder->find($importConfig->getEntityType())
);
```

### Describe the solution you'd like

1. I would like you to provide me with some documents related to the problem.
2. If it is possible please make a simple module which uses one symfony services in a module front controller.

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @stifler97 

Thank you for your suggestion. The Developer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by alisamie97** [comment]
I would like to help implement this feature. I do not know the rules and where to start. Please guide me through this. And I would like to do this if a developer from prestashop team show me a road map of the things that need to be done. Any guide will be much appreciated.

**Comment by hibatallahAouadni** [comment]
Hello @stifler97 

I already share with you a link: [How to contribute code changes](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/).
Alternatively, you can also ask for help in the [public Slack channel](https://prestashop.slack.com)

Thank you

**Comment by alisamie97** [comment]
@hibatallahAouadni 
I could not join the slack channel. I tried the link, entered my email, and then I see an error which says your email was not found in this channel.

**Comment by NeOMakinG** [comment]
> @hibatallahAouadni I could not join the slack channel. I tried the link, entered my email, and then I see an error which says your email was not found in this channel.

On the top right, you can register to slack

**Comment by hibatallahAouadni** [comment]
Hello @stifler97 

> I could not join the slack channel. I tried the link, entered my email, and then I see an error which says your email was not found in this channel.

Click on this link:
![image](https://user-images.githubusercontent.com/23308427/177726316-e93b7021-9003-4717-8899-379b34f45597.png)

Then, create your account via your google account or with your apple account:
![image](https://user-images.githubusercontent.com/23308427/177726467-959d39f2-9249-40c7-9338-2fc2a382bedf.png)

**Comment by alisamie97** [comment]
What am I doing wrong? Can you help me?
https://user-images.githubusercontent.com/23106000/177731052-7e5f1dd3-e2f4-492b-9455-fb4bc0c0593b.mp4

**Comment by hibatallahAouadni** [comment]
@stifler97 

How is it possible to access to a nonexistent account??! You need to create one at first then you can access it :wink: 
Click on this link at first:
![image](https://user-images.githubusercontent.com/23308427/177733238-fe83b0cf-d215-4655-ba38-c24492dddfeb.png)

**Comment by alisamie97** [comment]
As far as I know when it comes to a slack channel, some one else has to invite you, and if the channel is public you should be able to login with any email.
I tried stifler@binshops.com and alisamie97@gmail.com and none of them works because it tells me these emails do not have any account on this workspace. So I used the create account form and again it tells me there is no such account. And it asks me to use an email of this format only email@prestashop.com
