### ISSUE TITLE
BO - Poduct V2 - Priority management is not working as expected

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#28968]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The Priority management is not working as expected
The specific priority was fixed here: https://github.com/PrestaShop/PrestaShop/pull/26938#pullrequestreview-923518880

### Expected behavior

https://github.com/PrestaShop/PrestaShop/issues/19674

### Steps to reproduce

1. Go to BO > Advanced Parameters > New & Experimental features page
2. Enable the New product page
3. Go to BO > Catalog > Products V2 > Add a product
4. In the pricing tab > Priority management  section
5. See error > The specific list is not disabled 
![image](https://user-images.githubusercontent.com/16067358/177386752-3b1e6ac5-372a-4f4e-bb43-dcc2010423eb.png)
6. Select "Set a specific order for this product"
7. See error => The specific list is disabled, it shouldn't 
![image](https://user-images.githubusercontent.com/16067358/177386842-8c5261c3-2adf-438e-821a-6ab981123fb0.png)
8. Click on Save
9. See error 
![image](https://user-images.githubusercontent.com/16067358/177386878-0c6de5b7-1433-4acd-9938-65cca4363312.png)

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1

**Comment by ghost** [comment]
Fixed by : https://github.com/PrestaShop/PrestaShop/pull/28598
