### ISSUE TITLE
Install - The alerts are not well displayed with RTL language

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#28972]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the Install > `Store information` step, the alerts are not well displayed with RTL  language
![image](https://user-images.githubusercontent.com/16067358/177522886-37ee572e-f3b7-4043-a42e-bb24984e6f2f.png)

### Steps to reproduce

1. Install PrestaShop and choose the Arabic language
2. Click on Next > In the step `Store information` > Set invalid data
3. See error: the alerts are not well displayed

### PrestaShop version(s) where the bug happened

1.7.7.8, 1.7.8.6, 8.0.x

### PHP version(s) where the bug happened

7.2

**Comment by florine2623** [comment]
It is fixed in PS 9.0.0.

![Image](https://github.com/user-attachments/assets/7fa79a83-5c47-4b52-8a3e-52128170452f)

![Image](https://github.com/user-attachments/assets/d95d2f26-1e5b-42ed-b231-360156e56792)

I'm closing the issue.
