### ISSUE TITLE
Missing link between Prestashop and Google Analytics

### ISSUE THREAD

**Issue by StockRent** [PrestaShop/PrestaShop#28979]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![analytics1](https://user-images.githubusercontent.com/108802487/177564354-c745dfdd-e863-4662-be4a-d61eaf25c514.PNG)

Hello, I followed several tutorials on how to configure Google analytics on Prestashop, but I don't see any traffic volume yet.

I pasted the analytics code as shown in the snapshot almost a week ago but when I go check on Analytics I don't see incoming traffic.

Please help me understand what is the problem.

### Expected behavior

Website traffic should appear on reports on Google Analytics

### Steps to reproduce

1. open google analytics
2. click on real-time overview 

### PrestaShop version(s) where the bug happened

1.7.8.5

### If your bug is related to a module, specify its name and its version

 Google Analytics v4.1.2 di PrestaShop

**Comment by HanaRebaiQA** [comment]
Hello @StockRent 

Thanks for your report.
Is one of these issues are similar to yours [#26619](https://github.com/PrestaShop/PrestaShop/issues/26619), [#13911](https://github.com/PrestaShop/PrestaShop/issues/13911), [#20268](https://github.com/PrestaShop/PrestaShop/issues/20268) and https://github.com/PrestaShop/PrestaShop/issues/26091#issuecomment-948415026?

Could you please check and we are waiting for your feedback ?

Thank You!

**Comment by Hlavtox** [comment]
@StockRent Prestashop GA module only supports UA-XXX tracking codes. GA4 support is not implemented. Use some third party module. 👍

**Comment by HanaRebaiQA** [comment]
Hello, 

Thanks @Hlavtox for your feedback.
@StockRent What do you think ?

Thank You!

**Comment by StockRent** [comment]
> Hello,
> 
> Thanks @Hlavtox for your feedback. @StockRent What do you think ?
> 
> Thank You!



> @StockRent Prestashop GA module only supports UA-XXX tracking codes. GA4 support is not implemented. Use some third party module. 👍

What do you mean by third party module? Can you please give an example? I am a complete profane of the topic!
Thanks

**Comment by Hlavtox** [comment]
@StockRent Well, it's simple. For developers paid by Prestashop company, there are more important topics to handle, so this module was not developed very much.

Maybe some other people take the handles and implement this. I would help, but can't do it alone. :(

So for now, look on Addons on some other marketplace for a GA module of other author that will support the new Google Analytics 4 tracking. That's your only option now. Or you can use the older Universal Analytis (with UA-XXXXX tracking code), but it will end next July, so meeeeh, not a good option.

**Comment by HanaRebaiQA** [comment]
Hello, 

Thanks @Hlavtox for your feedback 
@StockRent We are waiting for your feedback 

ping @PrestaShop/prestashop-core-developers : What do you think about this issue ?

Thank You!

**Comment by matks** [comment]
I confirm what @Hlavtox said:

1. There is a free and open source Google Analytics module https://github.com/PrestaShop/ps_googleanalytics/
2. It does not support GA4 yet. Someone started it https://github.com/PrestaShop/ps_googleanalytics/pull/120 but it's a WIP.
3. If you need GA4 support now you must find another module: look at prestashop modules marketplaces (Addons Marketplace is one, there is other) or contact prestashop freelance developers to create one.

All answers have been provided so I close this topic.

**Comment by HanaRebaiQA** [comment]
Thanks @matks for your response.
