### ISSUE TITLE
Bug ajout caractéristique produit

### ISSUE THREAD

**Issue by wstudio-54** [PrestaShop/PrestaShop#28971]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Bug de la fonction "caractéristique" de produit.
A l'ajout d'une caractéristique d'un produit, si on ne sélectionne pas dans la liste déroulante la caractéristique et qu'on laisse sur " choisissez une caractéristique" et que l'on enregistre, cela bug.
Il est impossible de supprimer cette caractéristique.
En plus à chaque enregistrement d'une nouvelle caractéristique, cela double les lignes d'enregistrements.

Bug of the product "characteristic" function.
When adding a feature of a product, if you do not select the feature from the drop-down list and leave on "choose a feature" and save, this bugs.
It is not possible to remove this feature.
In addition to each recording of a new characteristic, this doubles the lines of recordings.

### Steps to reproduce

go to prestashop admin
produit
caractéristique de produit

### PrestaShop version(s) where the bug happened

1.7.7 and other

### PHP version(s) where the bug happened

7.4

**Comment by HanaRebaiQA** [comment]
Hello @wstudio-54 

Thanks for your report.
I was unable to reproduce your issue with PS1786. Here is a screen-record : 

https://user-images.githubusercontent.com/92912932/177507095-7824d67d-64bd-47b5-b85b-824660c55177.mp4

 Could you please check ? Waiting for your feedback !

Thank you!

**Comment by wstudio-54** [comment]
[](https://webmasterstudio.fr/bug.mp4)

I try to delete, I don't work

**Comment by wstudio-54** [comment]
https://webmasterstudio.fr/bug.mp4

**Comment by HanaRebaiQA** [comment]
Hello @wstudio-54 

Thanks for your feedback.

Yes! In fact, i was able to reproduce your issue when i put a customized value with Choose a value and Choose a Feature on 8.0.x 

Your issue is similar to this one [#16306](https://github.com/PrestaShop/PrestaShop/issues/16306)
I just have updated the issue with the different cases on Product V1 and the new product page V2.

So, i'll close this one.

Thank You!

**Comment by HanaRebaiQA** [comment]
Duplicate of [#16306](https://github.com/PrestaShop/PrestaShop/issues/16306)
