### ISSUE TITLE
COD module order status change after upgrade 2.0 and translation doesn't work

### ISSUE THREAD

**Issue by annadumi** [PrestaShop/PrestaShop#28978]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello everyone!

I have a problem with the COD module.  (https://addons.prestashop.com/en/point-of-sale-pos/24637-cash-on-delivery-cod.html#overview) Before the upgrade to 2.0, the order status for cash on delivery was "Pending". After the plugin was updated to 2.0, this status changed to "Awaiting COD validation". How can I set new orders to be "Pending" again?

Besides, the translations are in BO but in Front End are not showing at all.  This is a real problem for my store. 

Can you help me, please?

 ![store1](https://user-images.githubusercontent.com/108811543/177555926-713cd85c-207f-4207-b6ad-a9a9f92b9e84.PNG)
![store](https://user-images.githubusercontent.com/108811543/177555932-fff30674-7487-43ba-84cf-4c2e2b7fac4a.png)

![Capture-ed](https://user-images.githubusercontent.com/108811543/177559289-867ffa04-8a70-489d-9561-b7356e354cb6.png)

Thanks,
Anna 

### Expected behavior

The customer send an order, the order should have a "pending" status, and the payment method should be translated in BO.

### Steps to reproduce

1. Custom send order
2. The order enter in BO with the status "Awaiting Cash On Delivery validation" (Not "pending" as before)

### PrestaShop version(s) where the bug happened

1.7.7.8

### PHP version(s) where the bug happened

7.3.33

### If your bug is related to a module, specify its name and its version

ps_cashondelivery v2.0

**Comment by HanaRebaiQA** [comment]
Hello @annadumi 

Thanks for your report.
This issue seems to be fixed with the new released version `ps_cashondelivery` module with this [PR](https://github.com/PrestaShop/ps_cashondelivery/pull/46).
Please check these [comment1](https://github.com/PrestaShop/PrestaShop/issues/28674#issuecomment-1147230698) and [comment2](https://github.com/PrestaShop/PrestaShop/issues/28671#issuecomment-1147656457).

It's a duplication of this issue [#28674 ](https://github.com/PrestaShop/PrestaShop/issues/28674)
Could you confirm it please ?

Thank You!

**Comment by annadumi** [comment]
Hello @HanaRebaiQA ,

You are right about the translations, but my client says that the status of a new order was "pending" not "Awaiting COD validation". Is this the same thing or is it something new?

Thank you! 
Ana

![store4](https://user-images.githubusercontent.com/108811543/177565351-76167936-4498-429e-9d17-3795d43d5fd0.PNG)
![screencapture-egloromania-ro-admin01-index-php-sell-orders-12053-view-2022-07-06-16_43_34](https://user-images.githubusercontent.com/108811543/177565354-462df7f8-780e-4158-89bb-3d431af5036c.png)

**Comment by annadumi** [comment]
Hello,

I noticed another bug, maybe it's just in my case, I have no idea, but the payment field in the order is empty even if in the dashboard I can see that the customer has chosen the cash on delivery payment.

![screencapture-egloromania-ro-admin01-index-php-sell-orders-12124-view-2022-07-06-16_52_17](https://user-images.githubusercontent.com/108811543/177567348-093172c4-981e-4c51-ac94-ec655c1bceee.png)
![store4](https://user-images.githubusercontent.com/108811543/177567366-695df09a-a15d-456c-93bf-62c839acbf2a.PNG)


Thank you!
Ana

**Comment by HanaRebaiQA** [comment]
Hello @annadumi 

When we choose the cash on delivery method, the status is correct : `Awaiting Cash On delivery validation `
It's updated with the new module version `ps_cashondelivery v2.0.0`

https://user-images.githubusercontent.com/92912932/177592958-bd128a27-bdae-4d53-9259-929d36d2f673.mp4



For, the other bug, could you please use english in your shop to help us reproducing the issue ?
Waiting for your feedback.

Thank You!

**Comment by annadumi** [comment]
Hello, 
Thank you for your answer and sorry for the Romanian translation.
The bug is in BO, on the order page, at the section "Payment", which is empty now. In the past, here, was the payment method name.
![screencapture-egloromania-ro-admin01-index-php-sell-orders-12126-view-2022-07-07-09_17_02](https://user-images.githubusercontent.com/108811543/177705723-eed32001-afbd-47b1-8abe-5aec4eb0f2fb.png)


Thank you!
Ana

**Comment by HanaRebaiQA** [comment]
Hello @annadumi 

The payment method is well added when i have updated the status (eg: payment accepted) from the `Awaiting Cash On Delivery validation` status on **PS1778** 


![image](https://user-images.githubusercontent.com/92912932/177728981-1d26b0a4-11e7-41af-9400-5ece86164904.png)

Just a question, what's the `Comandâ procesatâ `english status ?
Could you please check again and feedback ? 

Thank You!

**Comment by annadumi** [comment]
Hello,

Comandâ procesatâ it's a custom status, they created this status and it means Processing in progress. I saw that Prestashop already has this status, so I will change it. 

Thank you!
Ana

**Comment by HanaRebaiQA** [comment]
Hello @annadumi 

Alright! 

So, closing this issue as it's not a Core bug.
Otherwise, if you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank You!
