### ISSUE TITLE
BO - Employees page - an exception is displayed when we try to add an invalid avatar

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#28985]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Related to https://github.com/PrestaShop/PrestaShop/issues/28253, https://github.com/PrestaShop/PrestaShop/issues/28484
In the BO > Team > Employees page, an exception is displayed when we add an invalid avatar (SVG, mp4,...)
![image](https://user-images.githubusercontent.com/16067358/177597936-98083b5f-93f5-47a6-b32a-74251655ae23.png)

### Expected behavior

When user hits "save" an error should be displayed to tell user that only some image files (list to be defined) are accepted as avatar. Trying to submit files such as SVG or MP4 should trigger a form invalidation error.

Error message should be something

### Steps to reproduce

1. Go to BO > Team > Employees page
2. Add/Edit an employee
3. Add an invalid avatar (SVG, ...)
4. Save
5. See an error

### PrestaShop version(s) where the bug happened

1.7.8.6, 8.0.x

### PHP version(s) where the bug happened

7.2

**Comment by florine2623** [comment]
Fixed in https://github.com/PrestaShop/PrestaShop/pull/29554
