### ISSUE TITLE
Combinations - The reference of each combination is not saved

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#28981]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Catalog > Products page V1, when we try to save a reference for a combination, this reference is not saved, it became empty

https://user-images.githubusercontent.com/16067358/177573015-ab8ca8b3-b588-45a5-a1ad-1941aaebb0f7.mp4

### Steps to reproduce

1. Go to BO > Catalog > Products V1
2. Create/Edit a product with combinations
3. For each combination,> Set a reference
4. Save: a blue alert is displayed
5. Refresh the page > check each combination
6. See error: the reference is not saved

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.2

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29523
