### ISSUE TITLE
BO - Documentation from help or learn more buttons is not updated (legacy & symfony pages)

### ISSUE THREAD

**Issue by sLorenzini** [PrestaShop/PrestaShop#28989]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On the 8.0.0 version, 1.7 and 1.6 documentations are still displayed when we click on "Help" or "Learn more" button.

Here's a list of some pages to update to 8.0.0 documentation when available:

- Legacy pages
	- For all legacy pages
		- home button still send to 1.6 documentation since 1.7.x versions: https://github.com/PrestaShop/PrestaShop/issues/25443
		- screenshots of the BO in this block are old
		- the "help" block is automatically displayed even if we go to another legacy pages
	- Dashboard > "Help" button, text from 1.7 version
	- Design > Theme & Logo > "Help" button, text from 1.7 version

- Symfony pages
	- Orders > Credit slips > "Learn More" button goes to https://docs.prestashop-project.org/1.7-documentation/user-guide/selling/managing-orders/credit-slips
	- Catalog > 
		- Categories > "Learn More" button goes to https://docs.prestashop-project.org/1.7-documentation/user-guide/selling/managing-catalog/managing-categories
		- Monitoring > "Learn More" button goes to https://docs.prestashop-project.org/1.7-documentation/user-guide/selling/managing-catalog/monitoring-catalog
		- File > "Learn More" button goes to https://docs.prestashop-project.org/1.7-documentation/user-guide/selling/managing-catalog/managing-files
	- Customers > Customers > "Learn More" button goes to https://docs.prestashop-project.org/1.7-documentation/user-guide/selling/managing-customers/your-customers
	- Modules > Module manager > "Help" button display 1.7 documentation
	- Design > 
		- Email Theme >  "Help" button display 1.7 documentation
		- Pages > "Learn More" button goes to https://docs.prestashop-project.org/1.7-documentation/user-guide/improving-shop/customizing-store-design/pages-managing-static-content
		- Link list >  "Help" button display 1.7 documentation
	- Payment > Payment Methods > "Help" button display french documentation. My shop is in English (screenshot)
	- International > 
		- Localization > Currencies tab, link to "developer documentation" goes to https://devdocs.prestashop.com/1.7/faq/pricing/#refresh-exchange-rates (screenshot)
		- Translations > Modify a translation > "Help" button display on all screen the help text (screenshot). Like this issue: https://github.com/PrestaShop/PrestaShop/issues/26579
	- Shop parameters > Traffic & SEO > "Learn More" button goes to https://docs.prestashop-project.org/1.7-documentation/user-guide/configuring-shop/shop-parameters/traffic/seo-and-urls
	- Advanced parameters > 
		- Performance > "Help" button display 1.7 documentation
		- Import > Link in the page goes to https://docs.prestashop-project.org/1.7-documentation/user-guide/configuring-shop/advanced-parameters/import (screenshot)
		- Employees > Employees Tab >  "Learn More" button goes to https://docs.prestashop-project.org/1.7-documentation/user-guide/configuring-shop/advanced-parameters/team (screenshot)
		- Security > 
			- Security Tab >  "Help" button display 1.7 documentation
			- Employee Sessions Tab >  "Help" button display 1.7 documentation
			- Customer Sessions Tab >  "Help" button display 1.7 documentation

Payment Methods
![doc-1 7-paymentmethods-french-alpha](https://user-images.githubusercontent.com/2854834/177734408-df35b91a-b25d-483d-8888-4e1c79a877d3.png)

Currencies tab
![doc-1 7-localizationcurrencies-alpha](https://user-images.githubusercontent.com/2854834/177734512-f9ba1312-2980-48fd-918e-ddbd42d6d7e3.png)

Modify a translation
![doc-1 7-modifytranslations-alpha](https://user-images.githubusercontent.com/2854834/177734634-feb64dfe-cca3-4cc3-8a66-dc69485f0b36.png)

Import
![doc-1 7-importpage-alpha](https://user-images.githubusercontent.com/2854834/177734699-420bb875-cb85-470c-8a24-1a5ce7c5b2a6.png)

Employees Tab
![doc-1 7-employeespage-alpha](https://user-images.githubusercontent.com/2854834/177734753-e769e5ab-05f2-4ab2-9835-13837e11cc76.png)

### Expected behavior

The documentation should be updated

### Steps to reproduce

Example

1. Go to BO > Dashboard page 
2. Click on help button
3. See error on documentation

Other pages listed on "Describe the bug and add screenshots" part

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.3

**Comment by FabienPapet** [comment]
Fixed by #29230

**Comment by fulldecent** [comment]
@FabienPapet Thank you for fixing this. This fix is merged into `develop` branch. But it was never released on the 8.1 branch.

For example, the latest release 8.1.5 does not include this change:

https://github.com/PrestaShop/PrestaShop/blob/8.1.5/src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Blocks/import_panel.html.twig#L40

---

Proof:

![Screenshot 2024-05-03 at 15 09 49](https://github.com/PrestaShop/PrestaShop/assets/382183/ebaf285e-60ae-4ff0-9b1e-7d58a4417957)

---

Could you please reopen this issue until it is properly merged into the project where the next release will go (or or close after it is release, depending on this project's policy)
