### ISSUE TITLE
BO - Wording "search" is displayed beside the icon on search bar

### ISSUE THREAD

**Issue by sLorenzini** [PrestaShop/PrestaShop#28980]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On the search bar in BO, when I want to choose the category where to search, a "search" wording is displayed beside the icon whatever the chosen category.

Here's my screen record:

https://user-images.githubusercontent.com/2854834/177571066-d95bb157-e71a-46e1-8a3d-aaa2bd5895e9.mp4

This search is on those pages for example:

- dashboard
- orders > shopping carts
- design > image settings
- shipping > carriers

The wording is displayed on 8.0.0 / 1.7.8.6 / 1.7.7.8 versions.

### Expected behavior

This wording should be removed.

### Steps to reproduce

1. Go to BO > Dashboard page
2. Click on the "search icon 🔍 " on the search bar
3. Choose a category to search, "Orders" for example
4. See error in the searchn bar

### PrestaShop version(s) where the bug happened

8.0.0 / 1.7.8.6 / 1.7.7.8

### PHP version(s) where the bug happened

7.3

**Comment by mparvazi** [comment]
I wanted to fix it months ago, but I don't remember what's happened!
https://github.com/PrestaShop/PrestaShop/issues/26624

I'll fix it.
