### ISSUE TITLE
Show price - Product page

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#28993]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

As a merchant, I want to be able to hide the price of my product when I want to.

### Describe the solution you'd like

Available for order - Switch button - by default, the switch is ON.
IF the user switches to OFF, THEN the add to cart button is disabled on the product page in the front office and the “Show price” switch input is enabled and set to ON.
IF the user switches to ON, THEN “Show price” switch input is disabled and set to ON.

Show price - Switch button
IF the user switches to OFF, THEN the product price isn’t displayed on the product page and product lists in the front office. For a pack, the price of the pack and the prices of the products contained in the pack are not displayed.

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by HanaRebaiQA** [comment]
Hello @MatShir

Thanks for your suggestion.
Which status we should put in this ticket please?

Thank you!

**Comment by AureRita** [comment]
Fixed by #28598
