### ISSUE TITLE
BO - Information alert on "Available fields" block on Import page got a height too small when data are loading

### ISSUE THREAD

**Issue by sLorenzini** [PrestaShop/PrestaShop#28990]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When we go to Import page, the information alert on "Available fields" block got a height too small when it's loading.

![import-page-800](https://user-images.githubusercontent.com/2854834/177737541-57975367-afb5-494f-ab0b-6999bd96d3a3.png)

https://user-images.githubusercontent.com/2854834/177737559-f048214d-af46-48b2-a6c7-20898af17260.mp4

Error is displayed on 8.0.0 and 1.7.8.6 version.

All good on 1.7.7.8 version. It's a regression.

https://user-images.githubusercontent.com/2854834/177737733-1779524d-80cc-4c27-ad77-c5be454226b0.mp4

### Expected behavior

The alert should have a bigger height by default. The display should be identical to 1.7.7.8 version (see 1.7.7.8 video).

### Steps to reproduce

1. Go to BO > Advanced Parameters > Import page
2. During the loading of the page, see error on available fields block on the right of the page

### PrestaShop version(s) where the bug happened

8.0.0 / 1.7.8.6

### PHP version(s) where the bug happened

7.3

**Comment by matks** [comment]
Assigned to @lartist
