### ISSUE TITLE
FO - On mobile screen bad display of the summary cart

### ISSUE THREAD

**Issue by sLorenzini** [PrestaShop/PrestaShop#28996]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On mobile screen (< 769px), I want to proceed to checkout but the cart summary  has bad displayed horizontally.
The list, total and button are not aligned and the spaces between Shipping and the gray border is very small.

Error on 8.0.0 ❌ 

Shopping cart page
![cart-800](https://user-images.githubusercontent.com/2854834/177776658-cfc448f4-6fd9-4c35-b5e8-68a37d26056c.png)

All steps pages for the total line
![Capture d’écran 2022-07-07 à 15 00 20](https://user-images.githubusercontent.com/2854834/177779840-8b383b4d-bf1a-4fcb-905c-c6d774b26c07.png)

Good on 1.7.8.6 ✅ 

Shopping carte page
![cart-1786](https://user-images.githubusercontent.com/2854834/177776682-7cc87ca4-3d7d-41eb-8b14-7f791e56df39.png)

All steps pages for the total line
![Capture d’écran 2022-07-07 à 15 02 25](https://user-images.githubusercontent.com/2854834/177780163-470970b4-ae2e-4434-9f36-fdad4c16af7b.png)

It's a regression

### Expected behavior

All items should be aligned and with good spaces.

### Steps to reproduce

1. Go to FO on mobile screen > Add a product to the cart
2. Click on "Proceed to checkout" button on the modal > Shopping cart page is displayed
3. Go down of the page > see error of the cart summary
4. Click on Proceed to checkout button > See error on steps page

### PrestaShop version(s) where the bug happened

8.0.0 / develop

### PHP version(s) where the bug happened

7.3

**Comment by matks** [comment]
Fixed on Classic theme
