### ISSUE TITLE
[Multistore] Combination product - Can't set up a specific delivery time on the Shipping tab with All Shops tab

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#28998]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you're on multishop, on "all shop" tab, when you want to turn up the specific delivery time with a combination product, it doesn't change anything, it let the default delivery time, you can see it on this video : 

https://user-images.githubusercontent.com/100699445/177803549-a5f13317-bd13-4d8b-9b4a-5b3eb070603b.mp4

### Expected behavior

I expect that I can change the specific delivery time with a combination product with all my shop at the same time 

### Steps to reproduce

1. Go to BO > Shop Parameters > General
2. Scroll down to enable Multistore 
3. Go to Advanced Parameters > Multistore
4. Clic on Add new shop 
5. Set up your new shop 
6. Set up its url
7. Go to Catalog > Product
8. Select a product with combination on it 
9. Go to Combinations tab 
10. Scroll Down, Clic on Allow orders
11. Set up the text of "Label when in stock" and "Label when out of stock (and back order allowed)"
12. Go to Shipping tab 
13. Clic on Specific delivery time to this product
14. set up the text of "Delivery time of in-stock products" and "Delivery time of out-of-stock products with allowed orders"
15. Save the product
16. Reload the current webpage 
17. See the error, Default delivery time is still selected

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1

**Comment by jolelievre** [comment]
Hi @AureRita the multishop feature is not finished on the product page, it will be done in 8.1 so I removed this issue from the 8.0 kanban

**Comment by jolelievre** [comment]
My bad this is on page v1 so it does need to be fixed.

**Comment by MeKeyCool** [comment]
I take this one ^^

**Comment by MeKeyCool** [comment]
Then after a more detailed study and some explanations from @AureRita , 

It looks that `additional_delivery_times` field of `ps_product` table isn't managed for multishop.

When multishop is setup, any change for a given shop will change settings for all shops and if we try to change for "All shops", change isn't applied.

It looks database behave the same way for `additional_shipping_cost` but Prestashop interface applies expected behavior so investigating how `additional_shipping_cost` works may help to find solution for `additional_delivery_times`

**Comment by MeKeyCool** [comment]
Then after further investigations, 

`additional_shipping_cost` works well for separate shop only. The value set under "All shops" scope isn't applied as well.
It looks that `additional_shipping_cost` is managed for independent shop thanks to `ps_product_shop` db.

> :point_up: Useful queries : 
> ```sql
> SELECT id_product, quantity, price, additional_delivery_times, additional_shipping_cost FROM ps_product WHERE id_product=19;
> ```
> 
> ```sql
> SELECT id_product, id_shop, price, additional_shipping_cost FROM ps_product_shop WHERE id_product=19;
> ```

> :point_up: Some related code can be found here : https://github.com/PrestaShop/PrestaShop/blob/83079ee0c30a7aebe58086c9aef2022ff43203a9/src/Adapter/EntityMapper.php#L71

We can see that `additional_shipping_cost` values are stored in  `ps_product_shop` for each shop.
Then we probably should add `additional_delivery_times` in this table as well. But I still need to understand the whole workflow to see all details I need to setup.

For example,  `additional_delivery_times` usage in `ProductCore::$definition['fields']`.

But even with this change, We still should find the proper way to change "All shops" for both  `ps_product_shop` and `additional_delivery_times`.

Furthermore, as we can see here : https://github.com/zuk3975/PrestaShop/blob/9887e7ece9810d847b8f31558ac2baabd1a91659/src/Adapter/Product/CommandHandler/UpdateProductShippingHandler.php#L118 some mapping as been made between `additional_delivery_times` and `DeliveryTimeNoteType` (and `DeliveryTimeNotesType`)

**Comment by MeKeyCool** [comment]
From last investigations, it seems that this code doesn't include fields to update properly : 
https://github.com/PrestaShop/PrestaShop/blob/8.0.x/controllers/admin/AdminProductsController.php#L1883-L1885

If I well understood, this problem should be solved by adding something like this 
```js
this.checkAllShipping = function()
{
	ProductMultishop.checkField($('input[name=\'multishop_check[additional_delivery_times]\']').prop('checked'), 'additional_delivery_times');
	ProductMultishop.checkField($('input[name=\'multishop_check[additional_shipping_cost]\']').prop('checked'), 'additional_shipping_cost');
};
```
here : https://github.com/PrestaShop/PrestaShop/blob/8.0.x/js/admin/products.js#L1864 and calling this function on the right place.

I probably still missed something but I have some troubles to test cause I don't understand how this js script is build / loaded.

Could I have a hint @PrestaShop/prestashop-maintainers ?

**Comment by MeKeyCool** [comment]
Finally, this "js" part looks deprecated.
I think I found the proper solution with https://github.com/PrestaShop/PrestaShop/blob/8.0.x/src/PrestaShopBundle/Model/Product/AdminModelAdapter.php#L87

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29417
