### ISSUE TITLE
Categories bug with level_deph

### ISSUE THREAD

**Issue by jorgevrgs** [PrestaShop/PrestaShop#290]
This is when editing some categories in www.espirometros.co:

[PrestaShopException]

Property Category->date_add is not valid
at line 837 in file classes/ObjectModel.php
1. 
2.            $message = $this->validateField($field, $this->$field);
3.            if ($message !== true)
4.            {
5.                if ($die)
6.                    throw new PrestaShopException($message);
7.                return $error_return ? $message : false;
8.            }
9.        }
10. 
11.        return true;
    ObjectModelCore->validateFields - [line 264 - classes/ObjectModel.php] - [0 Argument]
    ObjectModelCore->getFields - [line 598 - classes/ObjectModel.php] - [0 Argument]
    ObjectModelCore->update - [line 209 - classes/Category.php] - [1 Arguments]
    CategoryCore->update - [line 719 - classes/controller/AdminController.php] - [0 Argument]
    AdminControllerCore->processUpdate - [line 626 - classes/controller/AdminController.php] - [0 Argument]
    AdminControllerCore->processSave - [line 541 - classes/controller/AdminController.php] - [0 Argument]
    AdminControllerCore->postProcess - [line 521 - controllers/admin/AdminCategoriesController.php] - [0 Argument]
    AdminCategoriesControllerCore->postProcess - [line 158 - classes/controller/Controller.php] - [0 Argument]
    ControllerCore->run - [line 348 - classes/Dispatcher.php] - [0 Argument]
    DispatcherCore->dispatch - [line 50 - admin****/index.php] - [0 Argument]

**Comment by marionf** [comment]
Hello, 
This issue is old, so I close it.
If you still have it on the last version (PrestaShop 1.7.4.2), please open a new one.
Regards
