### ISSUE TITLE
BO - Trivial display issue on 2 different pages

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#29002]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

2 very trivial issues regarding display in BO.

- In Design > Theme & Logo > Pages configuration. Only "&" should be displayed.
<img width="211" alt="Screenshot 2022-07-07 at 18 19 29" src="https://user-images.githubusercontent.com/16019289/177822423-b3e0dfc0-3ee8-4e42-810c-041ab243841b.png">

- In International > Localization > Geolocation. Link is on the whole phrase, it should only be on "MaxMind"

https://user-images.githubusercontent.com/16019289/177822352-1b881c71-c1f0-4061-9334-a72cce56ddb1.mov

### Expected behavior

Described above

### Steps to reproduce

- Go to Design > Theme & Logo > Pages configuration, see diplay
- Go to BO > International > Localization > Geolocation, see display

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8

**Comment by ghost** [comment]
Hello @florine2623 i can fix only one issue in the first PR because the second come from a module.
