### ISSUE TITLE
BO > Permissions - Can't access certains pages with Profile with only View Permission

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#29001]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After creating a new Profile for an Employee with **ONLY** View permissions, there are some pages that I cannot access.
The pages reloads to Dashboard.

https://user-images.githubusercontent.com/16019289/177819614-3502c825-c954-49e5-8dc2-522b21bd5b68.mov

### Expected behavior

I should be able to access the pages like in version 1.7.8.6.
This is a regression.

### Steps to reproduce

1. Go to BO > Team > Profile
2. Create a new profile "stagiaire"
3. Go to Permissions > Choose "stagiaire" > click on "View" for everything
4. Go to Employees > Create new employee with profile "stagiaire"
5. Log out from your current account and Log Into your "stagiaire" account
6. Go to the following pages, see that only the Dashboard is displayed ❌ 
- orders > delivery slip
- catalog > Products
- Catalog > Categories
- Design > Positions

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8

**Comment by FabienPapet** [comment]
I'll have a look at it tomorrow
