### ISSUE TITLE
BO - Linklist - Multistore - Error when changing shop context

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#29005]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I change context shop while on linklist page, I have a redirection to the Module Page and an error.

"The module ps_linklist is inactive."

https://user-images.githubusercontent.com/16019289/177953372-2cce3830-4184-4ade-beba-320e6c4f947a.mov

### Expected behavior

I should be on my Linklist module page, with shop context changed.

### Steps to reproduce

1. enable multistore
2. create another shop
3. you are in shop1 context
4. change context to shop2 OK
5. try to change your context to “Default group” or “All shops” NOK
6. redirection to module page + error

### PrestaShop version(s) where the bug happened

develop, 8.0.x

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_linklist v5.0.4

**Comment by kpodemski** [comment]
It should work the same on 1.7.8, so it doesn't seem like a regression. It is expected behavior as the module needs to be activated for the Symfony controller to be available:
> @ModuleActivated(moduleName="ps_linklist", redirectRoute="admin_module_manage")

**Comment by MatShir** [comment]
@kpodemski Are you sure? I have test it and on a 1.7.8.7 shop, I don't have the issue 🤔

**Comment by Amoifr** [comment]
@florine2623  I reproduce the error, investigation in progress

**Comment by Amoifr** [comment]
@florine2623  the issue canbe reproduced by an simpler way .... 

1. Select default context
2. go to module menu
3. search link list by the search engine
4. click on configure

**Comment by kpodemski** [comment]
Hello everyone

I can confirm this issue. I've rechecked it, and it doesn't work correctly. Even if I have a module enabled in every store, it is impossible to configure it from the "All shops" context, which is a bug.

**Comment by kpodemski** [comment]
One more thing I forgot to mention. It might be related to what @matthieu-rolland is fixing in other PRs where he had to fix some things around putting an `active` flag to the database for the module.
