### ISSUE TITLE
blocknewsletter - In FO block is not centered anymore

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#29018]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In develop and 8.0.x ❌ 
<img width="1181" alt="Screenshot 2022-07-08 at 14 58 08" src="https://user-images.githubusercontent.com/16019289/178010805-8a9715aa-441d-41ee-ab8a-4c0701d19116.png">

In 1.7.8.x ✅ 
<img width="1132" alt="Screenshot 2022-07-08 at 14 59 12" src="https://user-images.githubusercontent.com/16019289/178010813-fab1b037-e609-45b0-81c5-9c3059b76350.png">

### Expected behavior

Block newsletter should be centered

### Steps to reproduce

- Go to FO
- scroll down
- see block not centered

### PrestaShop version(s) where the bug happened

8.0.x, develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

blocknewsletter v2.0.3

**Comment by LouisAUTHIE** [comment]
Version 2.0.3 doesn’t exist in the git of the module

**Comment by LouisAUTHIE** [comment]
Couldn’t reproduce the behaviors in the v2.3.0 too

**Comment by ghost** [comment]
It's 2.7.0 i can reproduce

![Screenshot (73)](https://user-images.githubusercontent.com/5064590/178098065-eee64017-a05b-474a-88ea-59e947429d8c.png)

**Comment by LouisAUTHIE** [comment]
Ok let me see

**Comment by LouisAUTHIE** [comment]
The PR is here https://github.com/PrestaShop/classic-theme/pull/44

**Comment by matks** [comment]
PR https://github.com/PrestaShop/classic-theme/pull/44 did not move for a month -> blocked

**Comment by MatShir** [comment]
We have no news from @LouisAUTHIE. Guys, do you think maybe you could @mparvazi or @NeOMakinG have a look to finish the work?

**Comment by matks** [comment]
@mflasquin continued the great work started in PR https://github.com/PrestaShop/classic-theme/pull/44 the new PR is https://github.com/PrestaShop/classic-theme/pull/73
