### ISSUE TITLE
Translation Pack contains ZIP in v8

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#29014]
### About this topic

This topic requires to explore and fix a piece of code on i18n.prestashop-project.org and consequently can only be done by someone who has access to this application, and also has (or is given) knowledge of how it's built.

<hr>

### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In v8, translations pack (for example, https://i18n.prestashop-project.org/translations/8.0.0/fr-FR/fr-FR.zip) contains ZIP which contains ZIP.

In previous versions (for example, https://i18n.prestashop-project.org/translations/1.7.8.6/fr-FR/fr-FR.zip), it wasn't.

### Expected behavior

The ZIP in v8 doesn't contains any other ZIP.

## Tech investigation

Old API from the team core, need to check how does it work, how can we update it. 

Dependent and block by the https://github.com/PrestaShop/PrestaShop/issues/29533

### Steps to reproduce

1. Download the translation pack : https://i18n.prestashop-project.org/translations/8.0.0/fr-FR/fr-FR.zip
2. Check if the ZIP doesn't contain a ZIP

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.0.0

**Comment by hibatallahAouadni** [comment]
Hello @Progi1984 

Thanks for reporting the issue :rocket: 
I was able to reproduce the issue. I’ll add this to the debug backlog so that it’s fixed.
Indeed it's a regression! So, we're waiting for your PR :rocket: 

Thank you

**Comment by MatShir** [comment]
Should be fixed by https://github.com/PrestaShop/PrestaShop/issues/29564

**Comment by atomiix** [comment]
I confirm this one is fixed!
