### ISSUE TITLE
V8 - the localization pack is not updated - BO - Cannot install modules in module manager with Spanish language on develop

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#29017]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This issue: https://github.com/PrestaShop/PrestaShop/issues/28084 is not fixed in the PS8.0.0 alpha.
As discussed with @eternoendless, it could be related to the localization pack which is not updated:

Even though PR https://github.com/PrestaShop/TranslationFiles/pull/22 was merged it is possible the localization pack downloadable on i18n.prestashop.com is not updated which would explain why this issue is observable. In order to fix this issue a developer needs to check whether i18n.prestashop.com is up-to-date or if its content is outdated with https://github.com/PrestaShop/TranslationFiles/

### Steps to reproduce

1. Change the Shop language in Spanish
2. Go to BO > IMPROVE > Module manager
3. Click on Upload module
4. Click on Select file ==> See Error (Blocked and cannot install module)
5. Use drag and drop of the module ==> See Error (Blocked and cannot install module)

https://user-images.githubusercontent.com/16067358/178010745-bb4e8878-10cb-4dd8-9b16-7a4bb11ce77d.mp4

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.2

**Comment by florine2623** [comment]
Hello @Julievrz ,

What do you think about this ?
Thanks!

**Comment by Julievrz** [comment]
> Hello @Julievrz ,
> 
> What do you think about this ? Thanks!

Hi @florine2623 
I'm not sure to know how I can help here. Do you need me to check something on Crowdin? Because the string mentioned in the initial issue has already been validated.

**Comment by eternoendless** [comment]
AFAIK translation packs for v8 aren't being built right now. We'll discuss this tomorrow with @Julievrz and @MatShir

**Comment by MatShir** [comment]
When https://github.com/PrestaShop/PrestaShop/issues/29533 is done, we will close this issue

**Comment by kpodemski** [comment]
@MatShir @jolelievre I think it's ready?

**Comment by MatShir** [comment]
Could @PrestaShop/qa-team check if the bug is still presents ? I couldn't reproduce the bug, since the translation part has been fixed.

**Comment by sallemiines** [comment]
Hello @MatShir 

I tested the issue with` PS800 `, and I can't manage to reproduce it , I think it's fixed 
you can see the attached screen record 

[Untitled_ Nov 8, 2022 2_57 PM.webm](https://user-images.githubusercontent.com/31663369/200584280-6c487b71-1568-4318-b4b9-9dcb75bff9c7.webm)


Thank you !

**Comment by hibatallahAouadni** [comment]
Glad to hear :tada: So closing the issue!
