### ISSUE TITLE
Hook method name doesn't match for hook actionTaxManager 

### ISSUE THREAD

**Issue by cquintini** [PrestaShop/PrestaShop#29027]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Class TaxManagerFactory calls for wrong method name when dispatching actionTaxManager hook.  Should call hookActionTaxManager instead of hookTaxManager.

`        foreach ($modules_infos as $module_infos) {
            $module_instance = Module::getInstanceByName($module_infos['name']);
            if (is_callable([$module_instance, 'hookTaxManager'])) {
                $tax_manager = $module_instance->hookTaxManager([
                    'address' => $address,
                    'params' => $type,
                ]);
            }
            if ($tax_manager) {
                break;
            }
        }`

### Expected behavior

In modules, it is expected to use the method hookActionTaxManager as the hook name is actionTaxManager

### Steps to reproduce

1) Add the hook actionTaxManager to a test module

2) As convention you will create the method hookActionTaxManager 

3) It will not call your method when the hook is executed

### PrestaShop version(s) where the bug happened

1.7

### PHP version(s) where the bug happened

7.4

**Comment by bfontaine** [comment]
Why was this closed? The bug is still there.
