### ISSUE TITLE
[docker-compose] Error when trying to build a shop with docker

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShop/PrestaShop#29037]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When running `docker-compose up --build` on `1.7.8.x`, 2 errors can be displayed.
1. Can't build assets because npm is not installed with NodeJs v10. 
2. Server can't run because the docker-compose uses the latest PHP version and it's 8.1.

FYI : it's working with 8.0.x and develop branches

### Expected behavior

No error when trying to build with docker

## Tech investigation 

To do change the base image in docker file
PR in progress, we need to find a team member as referent to help the PR to go through

https://github.com/PrestaShop/docker-ci

### Steps to reproduce

1. Clone Repo
2. Checkout 1.7.8.x branch
3. Update `1000` with your `$UID` and `$GID` [here](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/.docker/Dockerfile#L4-L5)
4. Run `docker-compose up --build`
5. See error on assets build

More steps for PHP:
6. Run `php -v` inside your PS container
7. Console will shop `8.1.something` => and this version is not compatible

### PrestaShop version(s) where the bug happened

1.7.8.x

**Comment by matks** [comment]
Hello @FabienPapet were you able to find a solution for this issue?

**Comment by boubkerbribri** [comment]
I think a backport of #29616 should do the trick

**Comment by FabienPapet** [comment]
Yes

**Comment by FabienPapet** [comment]
Yes, I'll start working on it

**Comment by mflasquin** [comment]
Hi @boubkerbribri, I think this issue is now resolved with the PR of @sefirosweb https://github.com/PrestaShop/PrestaShop/pull/30099

**Comment by mflasquin** [comment]
seems resolved
