### ISSUE TITLE
Customer address can't be saved after upgrade to 1.7.8.4

### ISSUE THREAD

**Issue by Danoosh** [PrestaShop/PrestaShop#29030]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Adding new address problem after upgrade.
No module had been assigned to related hooks.

### Steps to reproduce

1. Upgrade Prestashop from 1.6 to 1.7.8.4
2. Go to Addresses
3. Add a new address

### PrestaShop version(s) where the bug happened

1.7.8.4

### PHP version(s) where the bug happened

7.3.3

**Comment by sLorenzini** [comment]
Hello @Danoosh ,

Thank you for your issue and your PR 🚀 .

Unfortunately, I couldn't reproduce your issue.
I've got some errors after the upgrade and even if I "removed" those errors, the address is well added on my account.

Here's my errors screenshots (renaming module folders where errors happened and my store is "a bit" broken 😄 ):
![01-error-upgrade](https://user-images.githubusercontent.com/2854834/178234489-3198a62e-36ab-406f-8952-86a7b9bedea0.png)
![02-error-upgrade](https://user-images.githubusercontent.com/2854834/178234960-6c314c5c-0586-4a4d-ac9a-0cb173e78a70.png)
![03-error-upgrade](https://user-images.githubusercontent.com/2854834/178234974-a5f820dc-7ed3-4d4f-8c0b-d1416ae31a2c.png)
![04-error-upgrade](https://user-images.githubusercontent.com/2854834/178234995-55fa4703-1862-4c98-855e-4563883c4b7d.png)
![05-error-upgrade](https://user-images.githubusercontent.com/2854834/178235008-4040ce3f-051a-4040-b6be-7918b1106f78.png)


Here's my screenrecord:

https://user-images.githubusercontent.com/2854834/178235189-ef25347a-a21d-4813-a19a-c9975ac5f848.mp4

- Tested with PHP 7.1 & 7.3
- Upgrade from 1.6.1.20 to 1.7.8.4
- 4.14.1 version for Upgrade module

@PrestaShop/prestashop-core-developers, could you check please 🙏? 

Thank you

**Comment by matks** [comment]
Hi @Danoosh I am sorry, just like @sLorenzini I am not able to reproduce the issue you mention.

As I can't reproduce your issue, I will close it but feel free to open another one if more information pops up 😉 

Thanks!

**Comment by Danoosh** [comment]
Hi, Can you please check out adding an address in the front office?
