### ISSUE TITLE
Wishlist - Added products to the list are duplicated in  "My wishlists" page for customers who were created in BO 

### ISSUE THREAD

**Issue by szavadskiy** [PrestaShop/PrestaShop#29043]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![scrnli_7_12_2022_9-52-46 AM](https://user-images.githubusercontent.com/90208051/178438566-eba4e942-e843-4148-919e-369fc1b5fea6.png)
If a customer that was created through BO adds some product to wishlist, then this product will be displayed several times

Video:

https://user-images.githubusercontent.com/90208051/178441244-3afc0b23-a716-4266-beb4-d4c4b507e7ff.mp4

### Expected behavior

The product is not duplicated 

### Steps to reproduce

1. Create a new customer in BO
2. Log in this customer on FO
3. Add some product to wishlist
4. Check wishlist in Home / Your account / My wishlists page

### PrestaShop version(s) where the bug happened

1.7.7.x - 1.7.8.x

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

blockwishlist

**Comment by hibatallahAouadni** [comment]
Hello @szavadskiy 

I reproduce the issue with PS1786 and blockwishlist_2.1.1, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/178548375-7bccb752-6f4e-403c-90b3-99829dfd6673.mp4

**This issue only occurs when we create the customer from BO!**

Thanks!
