### ISSUE TITLE
Order page in BO, bad displaying of “Amount” input field + currency selector in “Payment” block

### ISSUE THREAD

**Issue by szavadskiy** [PrestaShop/PrestaShop#29051]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![Screenshot from 2022-07-12 12-03-04](https://user-images.githubusercontent.com/90208051/178485663-d2667c2b-31a2-44e9-a600-66ecdcc7c7f2.png)

### Expected behavior

As in previous versions
![Screenshot from 2022-07-12 14-04-10](https://user-images.githubusercontent.com/90208051/178485749-76f0d996-7fe2-44d7-9efc-edd40d860824.png)

### Steps to reproduce

1. Open some order page in BO
2. Scroll to "Payment" block
3. Check Amount input field with currency selector 

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Hello @szavadskiy 

Thanks for reporting the issue :rocket: 
I only reproduce the issue with PS8.0.x, so indeed it's a regression on 8.0.x!
I’ll add this to the debug backlog so that it’s fixed.

Thank you

**Comment by FabienPapet** [comment]
Looks like it's related to https://github.com/PrestaShop/PrestaShop/issues/28892 i'll have a look
