### ISSUE TITLE
The chosen theme is not validated while adding a new shop

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#29057]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

While you are in multishop and having a base theme but not valid (missing files or properties), you are able to choose it for the new created shop on the creation and there is not validation of it.

### Steps to reproduce

1. Create a base theme (folder, config file with name and version and it's all)
2. Create a new shop in multishop mode
3. Choose the newer theme
4. Valid the creation of the shop

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by florine2623** [comment]
Hello @PrestaEdit ,

Just to make sure, how do you create a base theme ? Are you able to provide one to test ?

Waiting for your answer, if that's too technical, I'll ping maintainers team for it :)
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by PrestaEdit** [comment]
Are you able to re-open this one ? I will make my best to provide it soon.

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

Don't worry 😉 when you provide new infos I will reopen it!

Thanks!

**Comment by PrestaEdit** [comment]
Hi @florine2623,

To have a valid theme, you can duplicate the Classic one and change it's name (folder name and inside the config/theme.yml).

With that,you have a valid theme. Now, you remove some files as the "preview.png" of this duplicate  theme. The theme is no more valid (you can enable it to be used on your shop).
