### ISSUE TITLE
Enabling a theme without hooks to handle throw an error

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#29058]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Create a valid theme and choose to enable it.

An exception is thrown : 
<img width="933" alt="Capture d’écran 2022-07-12 à 22 33 41" src="https://user-images.githubusercontent.com/2631425/178590122-9598013b-14ce-4bc1-b6d2-1fec0e6df972.png">

### Expected behavior

Set the g`lobal_settings.hooks.modules_to_hook `property as mandatory or handle that there is no array given.

### Steps to reproduce

1. Use this theme (it's a nice gift :D [eni.zip](https://github.com/PrestaShop/PrestaShop/files/9096655/eni.zip))
2. Enable it
3. See the error
 

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by matks** [comment]
> Create a valid theme and choose to enable it.

If I understand, it does not work with any valid theme 😅 you need a valid theme _with no hooks_, right?

**Comment by PrestaEdit** [comment]
With a valid theme having the property inside it (and, of course, it will be 99% of the time true), it's not an issue cause the parameter receive an array as wanted.

But if you does not add this settings into the theme configuration, and as it's not mandatory by the ThemeValidator, it's throw the error.

**Comment by florine2623** [comment]
Hello @PrestaEdit ,

I couldn't properly installed your theme. I tested it on shop version 8.0.0, tested with branch 8.0.0 and develop.
I have this error : `Missing configuration file`

https://user-images.githubusercontent.com/16019289/178676280-dea43d44-8016-4b8f-8073-62ac71f3f2dd.mov

Am I missing something ?
Thanks!

**Comment by PrestaEdit** [comment]
Hi @florine2623,

Sorry, it's my theme package that wasn't good. As it's not like a module, my zip file was wrong.

There is the reworked one :
[eni.zip](https://github.com/PrestaShop/PrestaShop/files/9100273/eni.zip)

**Comment by florine2623** [comment]
Thanks for the update !

Indeed I managed to reproduce the issue on 1.7.8.x, 8.0.x and develop branch. I'll add this to the backlog so it can be fixed.

https://user-images.githubusercontent.com/16019289/178707175-499609f3-5f8b-4c7c-b9b4-9d5301021e99.mov

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by FabienPapet** [comment]
I'll look for a fix

**Comment by hibatallahAouadni** [comment]
Ping @florine2623 is this issue a regression on 1780 or it's an old bug?
Thanks in advance!

**Comment by sLorenzini** [comment]
> Ping @florine2623 is this issue a regression on 1780 or it's an old bug? Thanks in advance!

@hibatallahAouadni, tested on 17.7.8 and the bug is reproduced. It's an old bug 😄

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29069
