### ISSUE TITLE
Export the current theme throw an error

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#29061]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I have an installed theme (that I can't drop there, because I was not able to export it) and once I try to export it with the "Export current theme" button inside the Theme management, I have an error displayed.

<img width="1047" alt="Capture d’écran 2022-07-13 à 09 45 30" src="https://user-images.githubusercontent.com/2631425/178679413-945ae637-48bb-4524-9889-ff88ff21dd44.png">

The reason could be cause I don't have any translations on it.

### Steps to reproduce

Exactly, I'm not sure but it could be the use case.

1. Add a newer theme without translations
2. Try to export it

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by florine2623** [comment]
Hello @PrestaEdit ,

I manage to reproduce your issue with child_classic theme in PS 8.0.x. I'll add this to the backlog so it can be fixed.
<img width="1088" alt="Screenshot 2022-07-13 at 15 23 56" src="https://user-images.githubusercontent.com/16019289/178746023-0d33ee6f-8bfe-4d0d-a026-a7513bb2f62e.png">

With classic theme, the export works as expected:
<img width="726" alt="Screenshot 2022-07-13 at 15 23 06" src="https://user-images.githubusercontent.com/16019289/178746148-8c656834-2014-4b1b-a3af-38885442cdaa.png">

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
