### ISSUE TITLE
ps_customtext: id_info is hard coded in `getWidgetVariables()`

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#29062]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In [`ps_customtext.php line 340`](https://github.com/PrestaShop/ps_customtext/blob/6c2324501131627d3bf02075bf21afe1f49a72a2/ps_customtext.php#L340), the id_info is hard coded in `getWidgetVariables()`.
As an effect, it is not possible to display any _info text_ other than the first.

Specifically in a multishop environment, if `info 1` is configured to display in shop 1 and `info 2` to display in shop 2, on shop 2, only the `<div id="custom-text">` is dispayed, but no content.

### Expected behavior

I expect to see any _info text_ that is configured in the BO.

### Steps to reproduce

A: In the BO, on a multishop environment:
1. Log into shop 1, go to `Modules - Module Manager`
2. Click `Configure` the module ps_customtext
3. Fill in some text to display, save. => This creates the info with `id_info =1`

Important: If we modify the `info text 1` in shop 2, the bug will not happen. We have to create a new `info text`.

B: in shop 2
1. Go back to the dashboard
6. Change context to shop 2, go to `Modules - Module Manager`
7. Click `Configure` the module ps_customtext
8. If the field `text` already contains something, then you are not on a new `info text`
9. Fill in some text to display, save. => This creates the info with `id_info =2`

C. In the FO:
1. Navigate to home page of shop 1 => The text for shop 1 displays.
2. Navigate to home page of shop 2 => The text for shop 2 does not display.

When following these steps exactly, the BO procedure in shop 2 (B.) should create a new `info text`.
I identified two scenarios, where the BO procedure in shop 2 will modify `info text 1` instead of create a new one:
- If between A. and B., while in context shop 1, we check shop 2 in the shop association.
- If we create shop as a copy from shop 1 AFTER installation of `ps_customtext`. ps_customtext has a `actionShopDataDuplication` hook, so the settings of shop 1 are copied into shop 2 when we create a new shop 2. As a workaround against this duplication, one can truncate the three `ps_info*` tables before the experiment above.

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_customtext 4.2.0

**Comment by florine2623** [comment]
Hello @lmeyer1 ,

I can't reproduce your issue using the same PS, module and PHP version.
Shop 1:
<img width="1154" alt="Screenshot 2022-07-13 at 11 48 22" src="https://user-images.githubusercontent.com/16019289/178704913-4f89bff9-46fa-4fd0-9acc-9ba27836d8e5.png">

Shop 2:
<img width="1168" alt="Screenshot 2022-07-13 at 11 48 28" src="https://user-images.githubusercontent.com/16019289/178704925-c59afe07-f8ec-4d3d-946d-c7b253522fe4.png">

Here is how I configured it :
<img width="808" alt="Screenshot 2022-07-13 at 11 49 29" src="https://user-images.githubusercontent.com/16019289/178705092-744d9896-36c9-422b-afc2-4061def1f5ec.png">

Am I missing something ?
Thanks!

**Comment by lmeyer1** [comment]
@florine2623 
Can you put also the screenshot of shop2, please?
Can you show the result of the query `select * from ps_info_lang` please?

Thank you.

**Comment by florine2623** [comment]
Here's a screenshot of config for shop2 :
<img width="1223" alt="Screenshot 2022-07-13 at 12 03 17" src="https://user-images.githubusercontent.com/16019289/178707981-4d6dbd98-2be0-47ea-923d-32d8fc975898.png">

Here the result of your query :

<img width="1202" alt="Screenshot 2022-07-13 at 14 17 16" src="https://user-images.githubusercontent.com/16019289/178731656-04a97880-a2e6-4b60-b786-9ecd480e8b7c.png">

**Comment by lmeyer1** [comment]
@florine2623 
Sorry, I don't understand what is going on.
1. The SQL query result does not show neither `Custom text block shop 1` nor `Custom shop text block 2`. Either the screenshot does not pertain to the experiment, or there are some lines missing.
2. I can't understand that you get to work this, but I don't. Can you send me the zip file of your module, so that I can check if there is something different? Maybe you have a fixed version ?

**Comment by florine2623** [comment]
Sorry, my query screenshot is wrong, I have modified it in my previous message. Here's the correct one : 
<img width="1202" alt="Screenshot 2022-07-13 at 14 17 16" src="https://user-images.githubusercontent.com/16019289/178731538-a8762ead-b83c-4afb-93af-2759384463b4.png">

I am using v4.2.0 in PS 1.7.8.6.

Here's the zip or the module, I have created the zip from my_shop/modules/ps_customtext.
I am using the one already present in the shop, I haven't modified anything on it.
[ps_customtext.zip](https://github.com/PrestaShop/PrestaShop/files/9101966/ps_customtext.zip)

Let me know if you need more info ^^

**Comment by lmeyer1** [comment]
@florine2623 
I now understand the difference between your case and mine:
- As you can see in your screenshot, all lines have `id_info = 1`. So you did not create a new `info text`, but you have two different translations in the two shops for the **SAME** `info text`.
- In my case, I created a new `info text` for shop 2, and then the bug happened. I have two lines with `id_info = 1` and two lines with `id_info = 2`, the rest is similar to your screenshots.

I think that the steps to reproduce are not detailed enough. I will try to find the difference between our procedures.

**Comment by florine2623** [comment]
Thanks for the update @lmeyer1.

Waiting for feedback :)

**Comment by lmeyer1** [comment]
@florine2623
I updated the steps to reproduce. I also found another bug 😢 #29070

**Comment by florine2623** [comment]
Thanks for the second issue. Indeed that is a bug.

Now, for this issue ^^
Before following your steps, I have emptied my 3 tables : `ps_info, ps_info_lang, ps_info_shop`.
Only when I empty these 3 table, can I reproduce the bug.

Here are my screenshots:
Config :
<img width="1436" alt="Screenshot 2022-07-13 at 18 15 02" src="https://user-images.githubusercontent.com/16019289/178782300-a827c212-9aab-48d7-97b5-ec820597c545.png">
<img width="1435" alt="Screenshot 2022-07-13 at 18 15 40" src="https://user-images.githubusercontent.com/16019289/178782315-f4189573-d3dc-4dde-8255-f246e91c12eb.png">

In FO:
<img width="1165" alt="Screenshot 2022-07-13 at 18 15 54" src="https://user-images.githubusercontent.com/16019289/178782329-5f65c56c-61e2-435f-83c7-e74d06864dce.png">
<img width="1157" alt="Screenshot 2022-07-13 at 18 15 59" src="https://user-images.githubusercontent.com/16019289/178782341-e11f77b0-78fd-4be2-8c81-f385cd7a0430.png">

Thanks for the details !

**Comment by lmeyer1** [comment]
@florine2623
The bug #29070 is interfering here. 
When the tables are not empty, and bug #29070 is happening ( = the info is associated to both shops, but the association not displayed, and it cannot be removed neither), then it is not possible to reproduce the issue.

Empty the tables is not required in all configurations, but it avoids #29070 for sure.

In short, depending on the initial configuration, we will observe either #29070 or this one, but never both of them at the same time.
