### ISSUE TITLE
PS 1.7.8.6 missing Bank Wire account detail when resent email

### ISSUE THREAD

**Issue by Betafer** [PrestaShop/PrestaShop#29063]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you click on resend email in order details, with order status waiting for bank payment, bank data detail are missing in email
<img width="546" alt="Schermata 2022-07-11 alle 11 04 19" src="https://user-images.githubusercontent.com/5024055/178708682-ffed1796-8266-4f29-842a-48a4c9513a69.png">

i think the issue is related to #16741
https://github.com/PrestaShop/PrestaShop/issues/16741

### Expected behavior

receive the compe email, from data and not with the prestashop variables

### Steps to reproduce

Go to backoffice, click on an order with waiting for bank wire payment
click on resend email

### PrestaShop version(s) where the bug happened

1.7.8.6

**Comment by florine2623** [comment]
Hello @Betafer ,

I can't reproduce your issue. I'm on PS 1.7.8.6, PHP 7.3, module Bank transfer v2.1.3.

Here's the result I have:
<img width="533" alt="Screenshot 2022-07-13 at 14 27 14" src="https://user-images.githubusercontent.com/16019289/178733456-5a5fc31c-8860-4f7a-bf8a-3567e061cbe6.png">
 
My module config:
<img width="842" alt="Screenshot 2022-07-13 at 14 28 24" src="https://user-images.githubusercontent.com/16019289/178733522-725a5c52-1c0c-4961-83fd-bf6d2e51be3e.png">

As I can't reproduce your issue, I will close it.
Feel free to open another one if more information pops up :)
Thanks!

**Comment by Betafer** [comment]
try to use: ' : or / in the details

**Comment by Betafer** [comment]
Works ?
