### ISSUE TITLE
BO - Create a new product - Exception is thrown: Invalid product type. Valid types are: [standard,pack,virtual,combinations] when enabling new product page Feature

### ISSUE THREAD

**Issue by szavadskiy** [PrestaShop/PrestaShop#29071]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![scrnli_7_13_2022_3-42-48 PM](https://user-images.githubusercontent.com/90208051/178749609-a331fae7-0331-4304-9699-9e74933f5871.png)

If I start create a new product with product page V1, then enable product page V2 and reload product page an error 500, see video:

https://user-images.githubusercontent.com/90208051/178752350-bde477d8-7fe1-4b44-88e1-bb9abb0895ed.mp4

### Expected behavior

No errors

### Steps to reproduce

1. Start creates a new product with product page V1
2. Enable product page V2
3. Reload page with new product 

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment]
Hello @szavadskiy ,

I reproduced the issue with PrestaShop version 8.0.x, I'll add this to the backlog so it can be fixed.

https://user-images.githubusercontent.com/16019289/178763598-6cd6907a-da00-4b18-9415-fc4333172fa2.mp4



Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by AureRita** [comment]
fixed #29158
