### ISSUE TITLE
Bad default value for "Product::pack_stock_type" - Inheritance issue when loading Pack class (that inherit Product)

### ISSUE THREAD

**Issue by abramofranchetti** [PrestaShop/PrestaShop#29077]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The default value of Product::pack_stock_type is set as "Pack::STOCK_TYPE_DEFAULT;" which in turn has a default value PackStockType::STOCK_TYPE_DEFAULT.

This is an inheritance issue because Pack class inherit product so when a Pack class is instantiated before the class loader attempt to load the Product class. Before of all the class loader assign valued to class field and the value from Product::pack_stock_type is a field of Pack ... that is the class i attempt to instantiate at the beginning..

In normal situation this issue pass unnoticed because in class_index.php the class is loaded by alphabetic order but is pure luck.
In certain specific situation this may conduce to an error of "ClassNotFoundException".
![image](https://user-images.githubusercontent.com/9608268/178926510-92a88007-89bf-44f3-9577-f2c56f1c8e5e.png)

The solution is to load directly the default value as "Product::pack_stock_type = PackStockType::STOCK_TYPE_DEFAULT;".

in fact all the other fields of products ha similar default value ex:
public $out_of_stock = OutOfStockType::OUT_OF_STOCK_DEFAULT;
public $redirect_type = RedirectType::TYPE_NOT_FOUND;

### Expected behavior

the default value for
Product::pack_stock_type 
should be set directly as Product::pack_stock_type =PackStockType::STOCK_TYPE_DEFAULT;

### Steps to reproduce

1. create an override of the product class : so in /override/classes create a file named Product.php and paste the code in the attached file ([Product.txt](https://github.com/PrestaShop/PrestaShop/files/9109613/Product.txt)
 or so:
```
class Product extends ProductCore
{
    public static function initStatic()
    {
        $test = self::$definition['fields'];
    }

}

if (method_exists('Product', 'initStatic')) {
    Product::initStatic();
}
```

2. clear the cache of prestashop to enable the override (so that the prestashop remake the class index including the new override). this can be done emptying the var/cache folder or going to BO->Advanced parameters->performance than "clear cache".

3. go in a page of the backoffice ex BO->Advanced parameters->performance (if you are already in this page refresh the page). or BO->modules->modules management. You will get the error. if you enable the debug mode the error detail will be shown

### PrestaShop version(s) where the bug happened

1.7.6, 1.7.8, 8.0.0

### PHP version(s) where the bug happened

7.1 and following

**Comment by AureRita** [comment]
Hi @abramofranchetti, 

Thank you for your report and the PR, I tried to reproduce your issue but I can't follow your step to reproduce. 
Can you be more precise about the files to modify, in wish folder, and after wish webpage we should verify to get your issue 

for example : 
1. Go to the files [name of your shop]/classes/Product.php 
2. Write the following lines : 
```
class Product extends ProductCore
{
    public static function initStatic()
    {
        $test = self::$definition['fields'];
    }

}

if (method_exists('Product', 'initStatic')) {
    Product::initStatic();
}
```
3. Go to BO>Catalog>Product

Waiting for your Feedback

**Comment by abramofranchetti** [comment]
hi @AureRita, the step are the following:
1) create an override of the product class : so in /override/classes create a file named Product.php and paste the code in the attached file (product class extend ProductCore ecc).
2) clear the cache of prestashop to enable the override (so that the prestashop remake the class index including the new override). this can be done emptying the var/cache folder or going to BO->Advanced parameters->performance than "clear cache".
3) go in a page of the backoffice ex BO->Advanced parameters->performance (if you are already in this page refresh the page). or BO->modules->modules management. You will get the error. if you enable the debug mode the error detail will be shown


I've attached a video tutorial.[12-08-33.zip](https://github.com/PrestaShop/PrestaShop/files/9120019/12-08-33.zip).

**Comment by AureRita** [comment]
Thank you for these steps ! 
I tested with them and I reproduce your issue as we can see on this video ! 

https://user-images.githubusercontent.com/100699445/179239688-12d69317-5666-4116-ba58-b01e36a354a0.mp4

I'll modify the steps to reproduce on your first message to catch directly the steps, 

Thank you for your reporting !

**Comment by jolelievre** [comment]
Cosed by https://github.com/PrestaShop/PrestaShop/pull/29079
