### ISSUE TITLE
Recaptcha bug create account

### ISSUE THREAD

**Issue by TFF1604** [PrestaShop/PrestaShop#29083]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,
the module appears and functions correctly on the contact page.
But it does not show on the account creation page and prevents the account creation
![recaptcha](https://user-images.githubusercontent.com/63454932/179172846-beb033e8-b82e-4d7e-b518-daa81e118735.png)
![Capture d’écran 2022-07-15 à 09 19 37](https://user-images.githubusercontent.com/63454932/179172881-14f792ae-dd67-4c57-99bd-e2e7b5f1771c.png)
.

### Steps to reproduce

1. connexion
2. creation a new account
3. Please complete the following
4. validate
5 after validation registration of the new customer impossibl
![recaptcha copie](https://user-images.githubusercontent.com/63454932/179173606-08c23529-fa0c-4e60-96a2-cce4604b7986.png)
e

### PrestaShop version(s) where the bug happened

1.7.3

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

(Re)Captcha par hhennes v2.3.1

**Comment by ghost** [comment]
Hello @TFF1604 

You have to open an issue on the repo of the module https://github.com/nenes25/eicaptcha

Here it's for PrestaShop issue and native module.

**Comment by matks** [comment]
Just like @okom3pom said, this module is outside of the prestashop organization 😉 we cannot help you with this.
