### ISSUE TITLE
Error PHP Fatal after upgrade PS 1.7.8.5 - PS 1.7.8.6

### ISSUE THREAD

**Issue by RicRey1988** [PrestaShop/PrestaShop#29088]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After updating prestashop 1.7.8.5 to 1.7.8.6 I get a "php fatal error" error in the "error_log" of the server

`[15-Jul-2022 07:07:56 America/Guayaquil] PHP Fatal error:  Uncaught InvalidArgumentException: "45?q=Precio" cannot be interpreted as a number in /home/sistegra/public_html/vendor/prestashop/decimal/src/Builder.php:40
Stack trace:
#0 /home/sistegra/public_html/vendor/prestashop/decimal/src/DecimalNumber.php(73): PrestaShop\Decimal\Builder::parseNumber('45?q=Precio')
#1 /home/sistegra/public_html/src/Core/Localization/Number/Formatter.php(147): PrestaShop\Decimal\DecimalNumber->__construct('45?q=Precio')
#2 /home/sistegra/public_html/src/Core/Localization/Number/Formatter.php(106): PrestaShop\PrestaShop\Core\Localization\Number\Formatter->prepareNumber('45?q=Precio')
#3 /home/sistegra/public_html/src/Core/Localization/Locale.php(154): PrestaShop\PrestaShop\Core\Localization\Number\Formatter->format('45?q=Precio', Object(PrestaShop\PrestaShop\Core\Localization\Specification\Price))
#4 /home/sistegra/public_html/modules/ps_facetedsearch/src/Product/SearchProvider.php(377): PrestaShop\PrestaShop\Core\Localization\Locale->formatPrice('45?q=Precio', 'USD')
#5 /home/sistegra in /home/sistegra/public_html/src/Core/Localization/Number/Formatter.php on line 108`

### Expected behavior

I expected everything to work normally.

### Steps to reproduce

the only step to follow is to use the official module to update from prestashop 1.7.8.5 - 1.7.8.6 the error only marks in the error_log file of the server, it is not visually visible in the store.

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4

**Comment by AureRita** [comment]
Hi @RicRey1988 , 

Thank for your reporting. Currently, I tried to reproduce your issue but I can't reproduce it with this steps, can you give me more information about your shop, for example the country of your shop, etc 

That what I get on video : 

https://user-images.githubusercontent.com/100699445/179248459-53882796-37c6-4dcc-85a1-294922c1dd0b.mp4

**Comment by RicRey1988** [comment]
I missed some details:

1) when using the upgrade module I got that everything was updated correctly, and I realized that error from the error_log file that was created in cpanel and that continues to grow.

2) My store is set to Ecuador

3) Use Currency United States dollars

4) language I use is Spanish

**Comment by AureRita** [comment]
Can you give us some screen shot to see the error ? 

I tried to reproduce with all your parameters but I haven't any error. 

Waiting for your feedback

**Comment by RicRey1988** [comment]
the error only appears internally, it is not displayed in the browser.

![Screenshot_358](https://user-images.githubusercontent.com/44790517/179254760-d254523f-4614-4998-8719-5937ab9dd72b.png)
![Screenshot_357](https://user-images.githubusercontent.com/44790517/179254764-b5b7fbc3-86bf-48f1-a527-258d807c7599.png)

**Comment by AureRita** [comment]
As you can see, I haven't some files with this name 
![image](https://user-images.githubusercontent.com/100699445/179256476-fa422bc7-5294-4783-aa2e-6d61f2d86e82.png)

I put this issue on To be reproduced, but if the team can reproduce it, we will unfortunately have to put this issue on invalid 

Thank you for all the details you give us

**Comment by PrestaEdit** [comment]
Hi @RicRey1988 ,

As I see inside the trace, the initial call coming from the module Faceted Search.
Could you say us wich version do you have ? And if there is an update available, make it in order to see if it's not related ?

**Comment by RicRey1988** [comment]
> Hi @RicRey1988 ,
> 
> As I see inside the trace, the initial call coming from the module Faceted Search. Could you say us wich version do you have ? And if there is an update available, make it in order to see if it's not related ?

In the faceted search module I have it in version 3.8.0 I think it is the latest since it does not come up to update, maybe it was updated when I updated the store

![image](https://user-images.githubusercontent.com/44790517/179354535-3cf67370-a052-4236-a81a-7f48a53329a8.png)

**Comment by RicRey1988** [comment]
> As you can see, I haven't some files with this name ![image](https://user-images.githubusercontent.com/100699445/179256476-fa422bc7-5294-4783-aa2e-6d61f2d86e82.png)
> 
> I put this issue on To be reproduced, but if the team can reproduce it, we will unfortunately have to put this issue on invalid
> 
> Thank you for all the details you give us

Does this error have something to do with the database? Look at the attached image and tell me if it is correct.

The one in the box is supposed to be the currency used by the store... and is Dollar USD

![image](https://user-images.githubusercontent.com/44790517/179355171-f7e3386b-2707-4623-bf7a-625b571b1b02.png)

in the information about prestashop of my installation it indicates that these files are missing, will they be important to determine the error?... can you check in your test if these files are missing?

![image](https://user-images.githubusercontent.com/44790517/179357406-4ce5e447-d32e-4dcb-a3d1-67690829088e.png)

**Comment by AureRita** [comment]
Hi @RicRey1988 ! 

About your Database, it's a little bit strange that you've twice the dollars parameters, 
as you can see on my screenshot : 
![image](https://user-images.githubusercontent.com/100699445/179480453-2c4d3f9a-985a-4868-a61d-92b351dd5aff.png)

For the missing files, I think they are important because I've all of them. The index of autoupgrade can be the most important

**Comment by sLorenzini** [comment]
Hello @RicRey1988,

I couldn't reproduce your issue with an upgrade from:

- 1.7.8.5 to 1.7.8.6, version 4.14.2 of upgrade module with your parameters
- 1.7.8.5 to 1.7.8.7, version 4.14.2 of upgrade module with your parameters

1.7.8.6

![Capture d’écran 2022-07-27 à 17 44 57](https://user-images.githubusercontent.com/2854834/181295968-486aac4a-b216-48aa-a84d-d78c730d630d.png)

1.7.8.7

![Capture d’écran 2022-07-27 à 18 16 59](https://user-images.githubusercontent.com/2854834/181297824-6ccec7a5-f5db-4163-9eff-1340fc529d42.png)


There is no error.
Could you try to upgrade from the last version of PrestaShop with the last version of module please 🙏? 

As sais @AureRita if the team couldn't reproduce it, we will unfortunately have to put this issue on invalid

Thank you

**Comment by hibatallahAouadni** [comment]
Hello @RicRey1988 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
