### ISSUE TITLE
500 error after upgrading via local archive from 1.6 to 1.7.8.x 

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#29090]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After upgrading via locale archive from 1.6 to 1.7.8.0 (for example), we have an error 500 in front office.

It is due to the module `blockbanner` not being uninstalled, it is supposed to be uninstalled when installing `ps_banner`, but this module is not installed when upgrading via local archive.

So the core issue seems to be that new modules like `ps_banner` are not installed when using local archive.  (it works fine when not installing via local archive).

I checked in the database, and indeed in `ps_module` the `blockbanner` module is present and activated, while `ps_banner` is absent.
Inside the module folder, `ps_banner` can be found, so the issue is not that it has not been copied.

### Expected behavior

There should be no 500 error in front office after upgrading from 1.6 to 1.7.8.x via local archive.

### Steps to reproduce

1. Clone PrestaShop 1.7.8.0, and generate a release
2. Install PrestaShop 1.6
3. Install the latest version of the autoupgrade module
4. Do an upgrade with the previously generated archive

See error in front office

### PrestaShop version(s) where the bug happened

1.6 - 1.7.8.0

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

autoupgrade, blockbanner, ps_banner

**Comment by Seb33300** [comment]
Can it be fixed by a SQL migration script that will disable the module and remove hooks in the database?

Or it's more complex than that? (also need to remove overridden files, or something else)

**Comment by hibatallahAouadni** [comment]
Hello,

I was able to reproduce the issue. I’ll add this to the debug backlog so that it’s fixed.
So, we're waiting for your PR :rocket: 

Thank you

**Comment by RosaBenouamer** [comment]
@hibatallahAouadni : why the label "Need spec " ?

**Comment by hibatallahAouadni** [comment]
@RosaBenouamer to be prioritized by a PM :wink:

**Comment by gericfo** [comment]
Hello,
Version 1.6 is no longer actively supported with the Autoupgrade module ([see this announcement](https://github.com/PrestaShop/autoupgrade/releases/tag/v4.14.3)). 
However, this behaviour has been clearly identified and will be taken into account in our future developments.
I therefore close this ticket.
Thanks!
