### ISSUE TITLE
The THEME_NAME constant define another theme name than the once in use

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#29095]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Firstly, it's a technical issue and I will try to explain it as I can do.
If you don't understand it, don't hesistate to ask me more on it and if you are able to provide more explains that could be usefull to let anothers understand, you are welcome !

There is the context : 
- Multishop enabled
- First and default shop (ID 1) have the Classic theme enabled on it
- Second shop (ID 2) have a dedicated new theme (Called Eni, here)
- Inside the Back Office, the context is set to Shop ID 2

The explain of the screen :
- On the orders settings, you are able to choose the invoice template.
- Invoice templates are found on two locations : the main pdf folder and the pdf folder of the theme used by the shop.

There is the issue :
- Actually, even if the context have my Shop ID 2 setted, it's seems that the _THEME_NAME_ define is another theme name. The one of the main shop (ID 1)
- The template finder will search the invoice template into this theme, instead of the one setted for the contextual shop.

### Expected behavior

Expected that the InvoiceModelFinder search inside the theme of the real context inside the admin and/or, and will be better and solve the first expected: _THEME_NAME_ set with the theme name by initialize the shop context as wanted.

### Steps to reproduce

1. Set the multishop
2. Add a shop
3. Set an another theme to this shop
4. Add a template called invoice-test.tpl inside the pdf folder of your theme (empty file, it's good)
5. Go to Orders > Invoices
6. See that it's not there inside the availables choices
7. Add the same file into the Classic theme
8. See that it's now available.
9. Go to an order related to your shop ID 2
10. Generate the invoice
11. See the "Source missing" error

<img width="964" alt="Capture d’écran 2022-07-17 à 14 14 49" src="https://user-images.githubusercontent.com/2631425/179397779-58090bef-88c8-4eeb-b152-f3b4e028496f.png">

<img width="964" alt="Capture d’écran 2022-07-17 à 14 16 45" src="https://user-images.githubusercontent.com/2631425/179397851-3c824160-5fcc-41b5-83eb-3cd1c33e9370.png">

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

> 4. Add a template called invoice-test.tpl inside the pdf folder of your theme (empty file, it's good)

Without overriding any another file? and did you encounter this issue only with 8.0.0 or you manage to reproduce even with older version?
Waiting for your feedback.

Thanks!

**Comment by PrestaEdit** [comment]
Hi @hibatallahAouadni,

Yes, just adding this file, empty, without problem.

Trying on the 1.7.8.5 version right now and the issue is there too.

**Comment by HanaRebaiQA** [comment]
Hello @PrestaEdit 

Thanks for your report.
I used the provided steps to reproduce your issue. 

Enable multistore
Create a new shop 
Set an another theme to this new shop
Set the classic theme for the default shop

But, im blocking on step 3 `Add a template called invoice-test.tpl inside the pdf folder of your theme (empty file, it's good)
`
In fact, i did not find the pdf folder under the theme. It's just under PrestaShop folder.

Here is a screen-record : 


https://user-images.githubusercontent.com/92912932/179962597-ad924096-d5ec-4c59-9fc4-b3658909bfc8.mp4



Did i missed something ? Please check and feedback!


Thank You!

**Comment by PrestaEdit** [comment]
You will need to create the folder, it's not by default but it's the good way to add it especially inside your theme.

**Comment by HanaRebaiQA** [comment]
Hello @PrestaEdit 

Thanks for your feedback.
I created a `pdf` folder under the theme and put the invoice-test.tpl inside it. 
When im in step 6, i couldn't find it inside the availables choices even with the classic theme. 

5. Go to Orders > Invoices
6. See that it's not there inside the availables choices

When i have generated the desired invoice for the specific theme, i couldn't reproduce the issue.
Here is my screen-record : 

https://user-images.githubusercontent.com/92912932/180023530-3d8b931f-3c18-4cc0-a119-f675fb4d17de.mp4



Could you please check again ?

Thanks!

**Comment by PrestaEdit** [comment]
On your screen record, we can see that the "invoice" choice is setted, so it's use the invoice.tpl template without issues.
You need to add the invoice-test.tpl file into the theme setted to the default shop (the ID 1) and you will be able to choose it.

**Comment by marwachelly** [comment]
Hello @PrestaEdit ,

Thank you for your response. Could you please provide a screen record with the full scenario to help us to understand more the issue and to identify exactly the missing step?

Waiting for your feedback.

Many thanks,

**Comment by Prestaworks** [comment]
Should not the shop->template that the order was placed in be used for the invoice regardless of what the admin context shop is set to?

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
