### ISSUE TITLE
Use somes blocks to allow extending PDF template easier, like the styles

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#29093]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

When you override a PDF template inside your theme, you surely want to adapt the styles and/or the colors made by variables assignations.

As now, you need to copy the entire file onto your theme.

### Describe the solution you'd like

Add somes Smarty block to be able to only adapt them as needed.

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 


Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments. 
Thanks for your PR 🚀 

Thank you

**Comment by fabienvallon** [comment]
LGTM
