### ISSUE TITLE
Making more details about the product available for the out-of-stock email

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#29111]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

This feature request is related to this feature:
https://capture.dropbox.com/JAMdbCPnhWLDWfsq

One of the Polish merchants reported that a built-in feature about sending alerts about products with low stock has a limited amount of data about the product - for instance, there is no product reference available.

### Describe the solution you'd like

We should have `product_reference` available by default. Additionally, the product ID and its combination ID should be available for the sake of `hookActionGetExtraMailTemplateVars`.

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @kpodemski 

Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments. 
And thanks again for your PR :rocket: 

Thank you

**Comment by kpodemski** [comment]
@PrestaShop/prestashop-maintainers, it's more or less a developer feature. Can I have your approval?

**Comment by florine2623** [comment]
Validated by @MatShir 
Thanks!
