### ISSUE TITLE
[Autoupgrade] - Files like AdminReferrers.php isn't deleted during the Autoupgrade 

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#29110]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When we do an Autoupgrade to the version 8.0.0, some files aren't delete, like the files AdminReferrers.php when they have to be deleted, that create some exceptions like on the page : 

`admin-dev/index.php?controller=AdminReferrers&addreferrer` 
![image](https://user-images.githubusercontent.com/16067358/173345500-380e7e20-b7de-498b-8f85-e2a7d3192873.png)
`admin-dev/index.php?controller=AdminReferrers`
![image](https://user-images.githubusercontent.com/16067358/173345548-17f4bcda-ae53-41db-8223-1fdcfe24353d.png)
`admin-dev/index.php?controller=AdminReferrers&updatereferrer=&id_referrer=1` 
![image](https://user-images.githubusercontent.com/16067358/173345589-0ca9f198-6832-4a83-9789-4d6eb0335779.png)
`admin-dev/index.php?controller=AdminReferrers&viewreferrer=&id_referrer=1`
![image](https://user-images.githubusercontent.com/16067358/173345646-bdd792aa-bef3-4d26-a23c-251988968b34.png)

you can see the log of the autoupgrade juste here : 
[log.txt](https://github.com/PrestaShop/PrestaShop/files/9139411/log.txt)

### Expected behavior

We want to delete the files during the autoupgrade so after that, we can have this type of notification : 
![image](https://user-images.githubusercontent.com/100699445/179717477-50ad6c16-bb29-4c7c-92da-3a61c297e897.png)

### Steps to reproduce

1. Have a fresh install of Prestashop 1.7.8.6 
2. Go to BO > Modules > Module Catalog
3. Download 1-Click Upgrade 
4. Uninstall modules : MBO - Metrics - Facebook - MarketfromGoogle - Welcome 
5. Do an autoupgrade from 1.7.8.6 to 8.0.0 where the adminrefferer page doesn't exist 
6.  Go to [your_domain]/admin-dev/index.php?controller=AdminReferrers&addreferrer
7. see exception

### PrestaShop version(s) where the bug happened

1.7.8.6 - 1.7.7.8 

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

Autoupgrade v4.15.0 - v4.14.1

**Comment by RosaBenouamer** [comment]
@jolelievre : why these file have to be deleted ? If not what are the consequences ?

**Comment by Hlavtox** [comment]
Fixed in autoupgrade 5.0.0
