### ISSUE TITLE
Cache is cleared for every module when you bulk remove modules instead of only once

### ISSUE THREAD

**Issue by atomiix** [PrestaShop/PrestaShop#29121]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] #29179

### Describe the bug and add screenshots

In the module manager, when you remove multiple modules through bulk action, the cache is cleared for each modules instead of being clearing only once at the end of the process.

### Expected behavior

The cache should be cleared only once at the end of the process.

### Steps to reproduce

As this bug is technical, I think only a dev can validate it:

1. Set a break point to [the clear cache method](https://github.com/PrestaShop/PrestaShop/blob/4a34c76eb9413ac760f37c75ba0dbe6213fd9824/src/Core/Module/EventSubscriber.php#L79)
2. Go to module manager
3. Select multiple modules
4. Click on the bulk action "uninstall"
5. See that the breakpoint is called multiple times

### PrestaShop version(s) where the bug happened

8.0.x

**Comment by marwachelly** [comment]
Hello @atomiix,

As discussed the issue is well an improvement. Thank you for your suggession.

Thanks,

**Comment by MatShir** [comment]
@hibatallahAouadni Have you reproduced the issue on 1.7.8.7 to flag as a regression?

**Comment by hibatallahAouadni** [comment]
@MatShir I didn't reproduce it on 1.7.8.6 and that's why I flag it as a regression :slightly_smiling_face:

**Comment by mflasquin** [comment]
As discussed with @atomiix, we have the same problem with all type of bulk action.
For bulk uninstall, install or upgrade module the system cache is cleared.
I will purpose a PR to fix that.

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29695
