### ISSUE TITLE
Show number of products after category names in block category tree in side panel

### ISSUE THREAD

**Issue by alisamie97** [PrestaShop/PrestaShop#29129]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Hi community.
I have opened this feature request as it was asked in community forums. Check it by this link: https://www.prestashop.com/forums/topic/1065522-display-number-of-products-near-category-name-in-ps-17-category-tree-module/#comment-3402388

### Describe the solution you'd like

I would like to help community members as much as I can, so I tried to add this feature to the module by myself. Check this link: https://github.com/PrestaShop/ps_categorytree/pull/60

Now, to follow the rules of prestashop, I opened this feature request to become accepted, and then the PR gets accepted too.
Thanks
Stifler

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by marwachelly** [comment]
Hello @stifler97 ,

Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments.
Thanks for your PR!

Thank you :blush:

**Comment by MatShir** [comment]
Thanks nice feature ! :)
