### ISSUE TITLE
The "An electronic version of this invoice is available in your account" phrase is shown on every PDF except the invoice one

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#29123]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you generate PDF file like the delivery slip or another one, you have this phrase displayed: "An electronic version of this invoice is available in your account. To access it, log in to our website using your e-mail address and password (which you created when placing your first order)".

This one is not shown on the invoice pdf itself. Where it's suppose to be.

As I know, this sentence was shown everywhere and since the 1.7.8.0, the invoice itself is not taken in consideration (https://github.com/PrestaShop/PrestaShop/pull/18220).

### Expected behavior

At least, shown the phrase on every PDF. Maybe better onto the invoice only.

### Steps to reproduce

1. Generate the PDF for an invoice
2. Generate the PDF for a delivery
3. See the footer

### PrestaShop version(s) where the bug happened

1.7.8.x

**Comment by marwachelly** [comment]
Hello @PrestaEdit,

I think your issue is a feature not a bug it is a new feature. Thank you for your suggession. And thank you for you PR.

Thanks,

**Comment by PrestaEdit** [comment]
Hi @marwachelly,

It's more a bug than a feature, as it was working great before 1.7.8.x, and now it's not as needed.

**Comment by matks** [comment]
@marwachelly Can you try to reproduce it on 1.7.7.0? @PrestaEdit says the behavior in versions before 1.7.8 was different

**Comment by PrestaEdit** [comment]
Hi,

Someone is here ?

**Comment by matks** [comment]
> Hi,
> 
> Someone is here ?

Just me

**Comment by PrestaEdit** [comment]
You are lost inside the the amazing maze of unanswered issues ? 😌

**Comment by matks** [comment]
> You are lost inside the the amazing maze of unanswered issues ? 😌

Just helping the project as I can with my limited time and energy (and obviously the work I'm doing right here is volunteer nobody's paying me to help the project at 10:30pm on Tuesday)

**Comment by PrestaEdit** [comment]
Nobody paying me at anytime of my help/work on this project, too. I really don't understand this sentence.

If you like, close this issue : it will help everyone to get free time to check anothers issues,  ¯\_(ツ)_/¯
