### ISSUE TITLE
Cryptical error message when no product image type has been defined

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#29145]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When no "product" image type has been defined, the home page on FO shows a cryptical error.

<img width="1792" alt="Screenshot 2022-07-22 at 18 04 49" src="https://user-images.githubusercontent.com/1009343/180479461-726113c1-d2aa-4da8-b6e0-55689a246804.png">

This has happened to me multiple times after failed installs and I couldn't tell what the problem was.

### Expected behavior

When in dev mode, I get a clear error message that helps me track down the problem.

### Steps to reproduce

On a clean install

1. Activate debug mode
2. Uncheck all the "product" image types in design > image settings 
<img width="1574" alt="Screenshot 2022-07-22 at 18 05 17" src="https://user-images.githubusercontent.com/1009343/180479389-db52d4a9-76f8-445d-9529-5d1850062022.png">

3. Load FO
4. See cryptical error

### PrestaShop version(s) where the bug happened

1.7.8.x, develop

### PHP version(s) where the bug happened

7.4

**Comment by khouloudbelguith** [comment]
Hello @eternoendless,

Reported previously here: https://github.com/PrestaShop/PrestaShop/issues/17725 also 

Thanks!
