### ISSUE TITLE
Error when using symfony routing for modules (back office) in Prestashop 1.7.8.6

### ISSUE THREAD

**Issue by musaffar-patel** [PrestaShop/PrestaShop#29147]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I am exploring the possibility of using as much symfony code as possible in my module,  However when routing to a module controller using symfony routing, the first load is ok, but loading the second time in the browser returns the following symfony error:

Warning: filemtime(): stat failed for E:\websites\prestashop\178\wwwpg\classes\PrestaShopAutoload.php(143) : eval()'d code

Example route:
http://localhost.test/adminps/index.php/modules/samplemodule/test

### Steps to reproduce

Please install the module attached and load the following route:

http://localhost.test/adminps/index.php/modules/samplemodule/test

First load is ok, but subsequent loads will produce the error described above until the var/cache/dev folder is cleared but after which the problem repeats.

[samplemodule.zip](https://github.com/PrestaShop/PrestaShop/files/9170194/samplemodule.zip)

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.2

**Comment by AureRita** [comment]
Hi @musaffar-patel 

Thank you for the reporting Issue.
I reproduced it on 1.7.8.6 and not on 1.7.7.8 as you can see on this video :

https://user-images.githubusercontent.com/100699445/180806827-cdfc53a6-93f2-4a02-85d2-cf9610629ede.mp4

It's a regression ! I will add it to the Patch Backlog to be fixed 

Thanks

**Comment by FabienPapet** [comment]
Hello, @musaffar-patel  I succesfully reproduced the issue you submitted with @jolelievre 's help , but I can see the controller you are using in your module extends `\Module` which is not a recommended way to create controllers (The Symfony controllers may extends `AbstractController` or nothing, but cannot extends PrestaShop core classes).

As this is not a recommended way to create controllers, I think we won't fix the issue and leave it as it is.

Thank you for understanding.

**Comment by musaffar-patel** [comment]
Hi @FabienPapet thanks for looking into this and providing the correct usage for the controllers
