### ISSUE TITLE
No CSS & JS in AdminDashboard and no Login page after upgrading to 1.7.8.6 from version 1.7.3.3

### ISSUE THREAD

**Issue by damian-bzd** [PrestaShop/PrestaShop#29144]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

As in the subject, I have upgraded from version 1.7.3.3

I repeated the updates many times, both using the 1-click upgrade module and manual upgrade.

The result is always the same, even though the update passed correctly, with no errors (not counting minor warnings when updating modules).

Both the AdminDashboard and the login page are devoid of CSS and JS, the others seem to be working properly.

In the source of the page I noticed that completely different headers are loaded for these pages.

Login page:
![Screenshot from 2022-07-22 17-58-03](https://user-images.githubusercontent.com/23173537/180478255-27bb8797-5db3-4aa4-a45c-dd25fb7bbe59.png)

Modules page:
![Screenshot from 2022-07-22 17-49-28](https://user-images.githubusercontent.com/23173537/180477848-8ed60110-ee8b-4322-891c-37ce6e4e1a79.png)

Dashboard:
![Screenshot from 2022-07-22 17-48-27](https://user-images.githubusercontent.com/23173537/180477869-6351ebef-0e9d-4ad0-b224-7a0e1f54547b.png)

### Steps to reproduce

upgrading to 1.7.8.6 from version 1.7.3.3

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.1

**Comment by Hlavtox** [comment]
Try to:
- Download latest zip - https://github.com/PrestaShop/PrestaShop/releases/download/1.7.8.6/prestashop_1.7.8.6.zip
- Extract the zip, open `admin` folder, copy `themes` folder and put it into your `admin123xxxxxx` folder of your shop.
- Delete everything from `var/cache` folder on your shop.

**Comment by AureRita** [comment]
Hi @damian-bzd, 

Thank for your reporting, unfortunately this is not a real issue, I tried to reproduce and you can see here : 

https://user-images.githubusercontent.com/100699445/180790727-6f259b92-086c-4054-b6f0-b5e26c55ce49.mp4

it's a problem with your cache, you can fix your problem with a hard refresh of your webpage ( CTRL + Shift + R ) 

Thank @Hlavtox for your quick answer 

Thanks
