### ISSUE TITLE
New hook in address `AddressFormatCore` class

### ISSUE THREAD

**Issue by alisamie97** [PrestaShop/PrestaShop#29149]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

This class has this method `generateAddress`
There is a parameter for `$patternRules` which lets you actually avoid some lines when generating a formatted address.
But there is no hook for this to alter this it when you need.
This is a related post that says they need to edit address format in some places and not all places.
https://www.prestashop.com/forums/topic/1066334-ps-177-mobile-phone-numbers-appears-on-delivery-address-but-should-not/
So a hook to alter `$patternRules` would be helpful.

### Describe the solution you'd like

I think we can add a hook after these two linse
```
$addressFields = AddressFormat::getOrderedAddressFields($address->id_country);
$addressFormatedValues = AddressFormat::getFormattedAddressFieldsValues($address, $addressFields);
```
like this:
```
Hook::exec('addressFormatGenerateAddressBefore', [
      'controller' => Context::getContext()->controller,
      'patternRules' => &$patternRules
]);
```
With this hook we can transplant a module like this:
```
    public function hookAddressFormatGenerateAddressBefore($params)
    {
        $desiredController = 'order';
        $desiredPage = 'checkout';
        
        if($params['controller']->php_self == $desiredController
            and $params['controller']->page_name == $desiredPage) {
            $params['patternRules'] = [
                'avoid' => [
                    'phone_mobile'
                ]
            ];
        }
    }
```

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by PululuK** [comment]
Hi @stifler97 
Look good for me :)
I suggest to add address Object in hook params, what do you thing ?

**Comment by alisamie97** [comment]
> Hi @stifler97 
> Look good for me :)
> I suggest to add address Object in hook params, what do you thing ?
> 

Actually you are right, for the reason that developer wants to avoid some fields, and these fileds are address specific. So it is better to provide all the fileds and the address to developer and let him avoid a filed  based on address too.

**Comment by alisamie97** [comment]
@PululuK Thanks for your suggestion.

If a developer wants to work on this and modify addresses, they need to have address fileds and address formatted values in order to dynamically modify them in runtime.
```
Hook::exec('addressFormatGenerateAddressBefore', [
      'controller' => Context::getContext()->controller,
      'address' => $address,
      'addreasFields' => $addressFields,
      'addressFormatedValues' => $addressFormatedValues,
      'patternRules' => &$patternRules
]);
```

**Comment by AureRita** [comment]
Hi @stifler97 
Thank you for your suggestion. The Developer Team will take it into consideration for future developments.

Please be aware that there is no guarantee that this feature will be developed anytime soon.
Thanks for your PR :rocket: 

Thank you
