### ISSUE TITLE
Deprecate/remove the bo_theme and bo_css properties of Employee

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#29148]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

It's more a code refactoring than a bugfix or a feature, there.

### Describe the solution you'd like

Since PrestaShop 1.7.4.0 (and this https://github.com/PrestaShop/PrestaShop/pull/8927/files), the bo_css and bo_theme are simply removed (not deprecated or anything, removed) from the Employee form.

But everything that is related to it (database structure and or code) are still present and not deprecated.

### Alternatives you've considered

We can keep this, of course, a third party module could manage to re-introduce this specific field option, but I'm not sure it's needed to keep this as an archive.

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by AureRita** [comment]
Hi @PrestaEdit 
Thank you for your suggestion. The Developer Team will take it into consideration for future developments.

Please be aware that there is no guarantee that this feature will be developed anytime soon.

Thank you
