### ISSUE TITLE
Prevent SQL injections by locking PDO to single statements

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#29157]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

For legacy reasons, SQL queries in PrestaShop are not handled via [prepared statements](https://www.php.net/manual/en/pdo.prepare.php) using named arguments, and instead they are made using string interpolation. This is how we can got SQL injection vulnerabilities, like the one that was fixed recently in the Wishlist module.

### Describe the solution you'd like

By [disabling multiple queries](https://www.php.net/manual/en/ref.pdo-mysql.php#pdo.constants.mysql-attr-multi-statements) in the PDO connection's configuration, we could mitigate the risk of data manipulation via SQL injection, because sequential queries won't be executed.

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by eternoendless** [comment]
ping @atomiix

**Comment by AureRita** [comment]
Hi @eternoendless 

Thank you for your suggestion. The Dev' Team will take it into consideration for future developments.

Thank you

**Comment by atomiix** [comment]
Fixed by #29586
