### ISSUE TITLE
New release of the blockwishlist to fix regressions

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#29155]
- https://github.com/PrestaShop/PrestaShop/issues/28832
- https://github.com/PrestaShop/PrestaShop/issues/28844
- update the file https://github.com/PrestaShop/PrestaShop/blob/develop/composer.lock in order to use blockwishlist 2.1.2

Creates regression on the V8 made, fix in the dev branch of the module.
To fix them before the final release of the V8, we need to release a new version of blockwishlist

**Comment by NeOMakinG** [comment]
https://github.com/PrestaShop/blockwishlist/pull/184

**Comment by hibatallahAouadni** [comment]
Ping @NeOMakinG should I close the issue as the release was merged?

**Comment by NeOMakinG** [comment]
@PrestaShop/prestashop-maintainers do we have something else to do on core side or somewhere else?

**Comment by matks** [comment]
Yes a PR must update the file https://github.com/PrestaShop/PrestaShop/blob/develop/composer.lock in order to use blockwishlist 2.1.2
