### ISSUE TITLE
Twig override does not work 

### ISSUE THREAD

**Issue by lucasvavon** [PrestaShop/PrestaShop#29156]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Following the documentation to override catalog.html.twig, I see that the "Hello World!" display does not work. 
I cleared the cache. 
I also tried to override view.html.twig with the following logic: 

file path :
/modules/foo/views/PrestaShop/Admin/Sell/Order/Cart/view.html.twig

and as content : 
`
{% extends 'PrestaShopBundle:Admin/Sell/Order/Cart:view.html.twig' %}

{% block cart_summary %}
  Hello world!
{% endblock %}
`

But unfortunately nothing works.

Do you have any ideas ? 

Thanks

### Expected behavior

I wanted to display "Hello World!" instead of the block `{% block cart_summary %}`

### Steps to reproduce

https://devdocs.prestashop.com/1.7/modules/concepts/templating/admin-views/

### PrestaShop version(s) where the bug happened

1.7.8.5

**Comment by AureRita** [comment]
Hi @lucasvavon , 

Thank you for your reporting, unfortunately, I think this one is maybe not an issue but a misunderstanding about the process. If this one is important to you, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

Thanks
