### ISSUE TITLE
Plug new User Documentation for contextual help in 8.0 beta

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#29169]
Following the development of the project [User Documentation](https://github.com/PrestaShop/PrestaShop/issues/24645) we need to complete it to be able to release PrestaShop 8.0.0 beta.

We need to make PrestaShop 8 fetch help content from help.prestashop-project.org instead of help.prestashop.com.

-> PR https://github.com/PrestaShop/PrestaShop/pull/29230

Output: the contextual help window (that can be opened on the right) can be blank* but does not inject errors

*Because new service is not ready yet

**Comment by matks** [comment]
Informative: the new documentation! https://docs.prestashop-project.org/welcome/

**Comment by MatShir** [comment]
Only the first step is mandatory for the beta release :)

**Comment by matks** [comment]
I moved the part not needed for beta release in #29216

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29230
