### ISSUE TITLE
Slow site after updating to 1.7.8.7 (updated from 1.7.8.5) when file system cache option is enabled

### ISSUE THREAD

**Issue by ismartfridge** [PrestaShop/PrestaShop#29167]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I updated from 1.7.8.5 to 1.7.8.7 and site became slow right away. Load time increased from 2s to 10s. The issue is mostly visible when having Cache > File System type enabled. Also, having smart cache for JS and CSS enabled makes things event worst.

I reverted to 1.7.8.5 for test and issue is gone. Isn't that a result of changes to cache system due to recent vulnerability?

### Expected behavior

Make our websites fast again

### Steps to reproduce

1. Update to 1.7.8.7
2. Enable cache > file system
3. Enable smart cache for CSS and JS
4. Enable apache rewrite rules under above two

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.2

**Comment by ghost** [comment]
Hello @ismartfridge 

Can you make a video on your test environment.
Normally the update should not change the page load time if you use the file system cache.

**Comment by kpodemski** [comment]
This release shouldn't affect your store performance if you don't use MySQL Cache for Smarty.

Could you provide us with the screenshots from the built-in profiler? You can enable the profiler in the `config/defines.inc.php` file my changing `false` to `true` for `_PS_DEBUG_PROFILING_`

**Comment by ismartfridge** [comment]
and where I can find profiling results thereafter?

**Comment by ismartfridge** [comment]
There you go:
https://ibb.co/m50Zc6B
https://ibb.co/gjBH5jT

FYI, as soon as I revert back to 1.7.8.5 all is back to normal

Hoping for some hot fix if possible

**Comment by florine2623** [comment]
Hello @ismartfridge ,

Multiple upgrades have been done, with different version of PS and PHP:
- 1.6.1.24
- 1.7.5.2
- 1.7.6.9
- 1.7.7.8
- 1.7.8.6
In all those versions, QA team hasn't encountered any slow downs.

I have done another upgrade from 1.7.8.5 to 1.7.8.7, with autoupgrade v4.14.2, PHP 7.4. On my end, it looks good.
<img width="1213" alt="Screenshot 2022-07-26 at 15 41 05" src="https://user-images.githubusercontent.com/16019289/181023834-d638eae8-a846-47dd-b039-751b15068491.png">

Profiling:
<img width="1196" alt="Screenshot 2022-07-26 at 15 58 07" src="https://user-images.githubusercontent.com/16019289/181024209-14289a0d-9fa7-4ea1-a57a-d45e9f5dd6ec.png">
<img width="1218" alt="Screenshot 2022-07-26 at 15 58 16" src="https://user-images.githubusercontent.com/16019289/181024223-bb2b4344-be93-4cfb-8fa6-aab0bdc321b2.png">


What are the pages that are slow ? BO or FO ? or all of them maybe ?

**Comment by ismartfridge** [comment]
All of them, BO and FO, sometimes they were becoming fast but most of time I need to wait the 10 seconds. Look at my performance results, the first two queries, one takes ~9+ seconds the other takes 7+. I guess after it executes the page starts loading.

**Comment by sLorenzini** [comment]
hello @ismartfridge,

I've made the upgrade  from 1.7.8.5 to 1.7.8.7 with autoupgrade v4.14.2, PHP 7.4. It looks good for me too (less than 2s) as @florine2623 said:

![Capture d’écran 2022-07-27 à 12 07 17](https://user-images.githubusercontent.com/2854834/181245526-2aa2ec39-f1af-41f2-853c-dbd46804de7b.png)

Profiling on BO:

![bo-profiling-1](https://user-images.githubusercontent.com/2854834/181245584-14571796-4b08-4062-9926-aa71790c1386.png)

![bo-profiling-2](https://user-images.githubusercontent.com/2854834/181245595-9e49738a-1af9-4ae8-9742-50ac5e1a6f81.png)

Profiling on FO:

![fo-profiling-1](https://user-images.githubusercontent.com/2854834/181245670-a0b1783c-5b87-4852-b674-0307e42c3e57.png)

![fo-profiling-2](https://user-images.githubusercontent.com/2854834/181245685-334aa1d5-235a-49fc-add0-5cf65d0c0c8f.png)


@PrestaShop/prestashop-core-developers, could you check on your side and try to reproduce this issue please? Maybe we missed something to test.

Thank you

**Comment by ghost** [comment]
Hello @sLorenzini && @florine2623 

It seems that yesterday some sites had connection problems with api.prestashop.com

@ismartfridge can you do a new test

**Comment by hibatallahAouadni** [comment]
Hello 

It seems the issue fixed and as we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
