### ISSUE TITLE
Product page in BO > Combination details page, "Impact on weight" Unit is not well displayed

### ISSUE THREAD

**Issue by szavadskiy** [PrestaShop/PrestaShop#29165]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![scrnli_7_26_2022_10-09-06 AM](https://user-images.githubusercontent.com/90208051/180957610-46aa68de-2b91-4b3e-8c78-93ec09c12227.png)

Ok with PS 1.7.8.6.
Looks like it's related to https://github.com/PrestaShop/PrestaShop/issues/28892

### Expected behavior

![scrnli_7_26_2022_10-13-47 AM](https://user-images.githubusercontent.com/90208051/180957756-6cde7434-3518-4e52-93c9-daa13ebc9917.png)

### Steps to reproduce

1. Open some product with combination page in BO
2. Open Combinations tab
3. Click edit for some combination
4. Check "Impact on weight" field 

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment]
Hello @szavadskiy ,

I reproduce the issue with PrestaShop version 8.0.x, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by HanaRebaiQA** [comment]
Hello,

**Comment by HanaRebaiQA** [comment]
Hello,

Thanks @szavadskiy for your issue.

It's related to this PR [#29054](https://github.com/PrestaShop/PrestaShop/pull/29054) as a known issue.

Thank You!
