### ISSUE TITLE
Make i18n translation possible to update 2 catalog

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#29178]
**Describe the pb**

At the moment, our services can only use one Crowdin catalog from the latest version of PrestaShop. 
Since, we want to maintain the Crowdin label from 1.7.8 AND the new catalog from the new version 8.0. 
The catalog export system must be updated to work with 2 catalogs.

**Solution**
Make the system work for 2 catalogs. Be aware, that the system, the PrestaShop version is hard code so to make it work for 2 versions, It would need a refacto. 

The doc -> https://www.notion.so/prestashopcorp/How-to-prepare-PrestaShop-s-translation-catalogue-for-a-new-release-daffea1f188945ea8aeea886e239dfd3#bd8c6f12ada54bc0b4a390ae6c1ac9a3
@eternoendless is available for any questions.

Should fix to issue https://github.com/PrestaShop/PrestaShop/issues/29017

**Comment by hibatallahAouadni** [comment]
@MatShir wdyt of this issue severity? is it `Major` or `Minor`?

**Comment by eternoendless** [comment]
This is not a bug but a CI task

**Comment by eternoendless** [comment]
Here's our current plan (cc @jolelievre):

1. Update wordings for v8 by running TranslationTool on Github actions (one action for running TranslationTool, one action in github.com/PrestaShop/TranslationFiles that will deploy artifacts to a GCP bucket served through i18n.prestashop-project.org
2. Either keep current CI for 1.7.8 until it's sunset, or move it to GH actions later

**Comment by MatShir** [comment]
Close this issue in favor of https://github.com/PrestaShop/PrestaShop/issues/29533
