### ISSUE TITLE
Show price field is not saved in product page v2

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#29175]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Product page V2 Pricing tab -> "show price" switch seems to always be negative, but it should be taken from database. (if you try to save it, nothing happens - after refresh it stay the same).

### Expected behavior

Show price switch should be saved & taken from database when saving product form in v2 page

### Steps to reproduce

1. Go to Product page v2 pricing tab
2. Locate the "show price" switch type button.
3. Try to switch it to different value than it is now and save.
4. See the switch didn't change after reload.

(additional checks)
 you can hardcode the different value in product_shop.show_price field in database and you will see that the value is still not changing (it is not handler neither when reading, nor when writing).

### PrestaShop version(s) where the bug happened

8.0.x

**Comment by florine2623** [comment]
Hello @zuk3975 ,

On branch 8.0.x, I can't reproduce your issue.
In Options Tab, I can choose to Show Price or not, it is well saved, even after refreshing the page.

https://user-images.githubusercontent.com/16019289/181051873-46584a13-d213-4213-9a94-6d15914ed062.mov

Am I missing something ?
Thanks!

**Comment by zuk3975** [comment]
Hmm sorry, my bad, I might have confused show_price in options with the unit price in pricing tab. Gonna double check it

**Comment by zuk3975** [comment]
I was talking about this part
![Screenshot from 2022-07-27 11-21-21](https://user-images.githubusercontent.com/31609858/181198630-4442e1f2-d9d2-4352-b232-573c1bbad9d9.png) ,
 but apparently I got mixed between behaviors. It is working as it should, all good.
Sorry for wasting your time, :bow:
