### ISSUE TITLE
Export Crowdin catalog for the v8.0

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#29176]
We need to export the catalog for the V8

The doc to export → https://www.notion.so/prestashopcorp/How-to-prepare-PrestaShop-s-translation-catalogue-for-a-new-release-daffea1f188945ea8aeea886e239dfd3#bd8c6f12ada54bc0b4a390ae6c1ac9a3 (the doc is still private until the server used for the Crowdin is not completely independent 

Don't forget to add the new native module in the export

**Comment by matks** [comment]
PR to extract catalog wordings: https://github.com/PrestaShop/PrestaShop/pull/29187

**Comment by matks** [comment]
Item to be validated by @Julievrz
