### ISSUE TITLE
I have this problem, can u help me ? Module `iqitsearch` is not a WidgetInterface.

### ISSUE THREAD

**Issue by deuub** [PrestaShop/PrestaShop#29183]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

It's a problem with WidgetInterface and Iqitsearch 
I delete the module, and now i have this .. 
I can't find the solution. 

### Describe the solution you'd like

Explain me how fix this 

### Alternatives you've considered

<img width="1157" alt="Capture d’écran 2022-07-27 à 15 05 23" src="https://user-images.githubusercontent.com/110106856/181254085-8a52f54c-c78e-414f-837a-ab9f7c0a1719.png">

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by deuub** [comment]
@iqit-commerce any idea ? 
Thank you

**Comment by ghost** [comment]
Hello,

Please contact the module developer. The problems here are for PrestaShop and native module

Sincerely

**Comment by sLorenzini** [comment]
hello @deuub, 

As @okom3pom said, this issue is not linked to PrestaShop or its native module.
We are closing this issue.

Thank you
