### ISSUE TITLE
Customization value lost after combination change, leading to customization mess

### ISSUE THREAD

**Issue by obelisk-services** [PrestaShop/PrestaShop#29185]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If our store has a product with customization and combination options and a customer, in the product page, first adds a customization and then changes the combination, the ID of the combination changes to "0" ("product_customization_id" input) and some weird stuff can be done, like having in the cart a product that has a mandatory combination without it, or having a product with two customizations. In the steps to reproduce, I show some examples of this behavior and if you read that section you will understand the problem.

### Expected behavior

When we add the same product twice but with two different customizations, two products should appear in the cart with one customization each, and when we delete one product, only one should remain with it's customization.

### Steps to reproduce

Create a customizable product and add some combinations (we used sample "Customizable mug" product, and added some size combinations). Product should look like this:
![image](https://user-images.githubusercontent.com/50045374/181243297-c8a3987c-4ea8-4a39-8570-fda75bb1c74e.png)
First, add a product customization (write some text and click "save customization") and then change the combination (order is the key).
![image](https://user-images.githubusercontent.com/50045374/181248736-b44e1cef-8bf0-4c13-8156-5b2b338a0aa5.png)

If you inspect the input id="product_customization_id" you will see that value after the combination change has changed to "0", but customization is still shown to the user in the form above. If you refresh the page, product_customization_id value will be back to normal. But it is not only that, we can manage to do some weird stuff:

Let's start again: Access the product page, add some customization, change the combination and add the product to cart. Everything should look fine. Then repeat the process again. Add to the cart the same product with other customization and size (remember, first we have to select the customization and then change the combination).

Now the cart looks weird. We have two mugs but with two customizations each:

![image](https://user-images.githubusercontent.com/50045374/181244635-2dc5f660-f27f-4fe7-abd9-c8d3b64efecb.png)

If we try to delete one mug from the cart, we see that customizations dissapear, or even we can't remove one mug (at least in the interface, if we refresh the page, the cart is empty). This way we can manage to buy a customizable mug that has a mandatory customization without it.

![image](https://user-images.githubusercontent.com/50045374/181246225-69fd13d9-cd45-4e35-9471-148b818a2c5b.png)

Probably, more weird things can be done this way.

### PrestaShop version(s) where the bug happened

1.7.8.7 and 8.0.0

### PHP version(s) where the bug happened

7.4.29 and 8.1.7

**Comment by sLorenzini** [comment]
Hello @obelisk-services,

I reproduce the issue with PrestaShop with develop branch. No error on 8.0.x branch 

![develop-custom-product-combinations](https://user-images.githubusercontent.com/2854834/181284805-736e9021-4672-49f6-89ee-c7bdfe36f9c7.png)

On 1.7.7.8 and 1.7.8.7 there is no error:

- 1.7.7.8

![1778-custom-product-combinations-1](https://user-images.githubusercontent.com/2854834/181285516-9435662a-7583-40ad-b2ec-05e573cb5708.png)

![1778-custom-product-combinations-2](https://user-images.githubusercontent.com/2854834/181285522-52df312a-e286-4795-bf19-11ea2d75f142.png)

- 1.7.8.7

![1787-custom-product-combinations-1](https://user-images.githubusercontent.com/2854834/181285568-8e78c3ac-6c06-4e40-804a-447eb18d46fa.png)

![1787-custom-product-combinations-2](https://user-images.githubusercontent.com/2854834/181285575-5c065765-f15a-4933-996b-b15aeeba79ab.png)


It's a regression.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

Well done and thank you for the PR 🚀 

Thank you

**Comment by obelisk-services** [comment]
Hi,

I have tried on a fresh Prestashop installation (1.7.8.7) on a new docker container and I was able to reproduce de issue. Even more, the line that causes the issue is in the version code (https://github.com/PrestaShop/PrestaShop/blob/1.7.8.7/themes/_core/js/product.js#L231). Maybe you miss one step? Can you please try again?

![image](https://user-images.githubusercontent.com/50045374/181301098-a1b0c2a8-9510-414a-a518-c7e41f9bfb19.png)

**Comment by matks** [comment]
PR https://github.com/PrestaShop/PrestaShop/pull/29635 on 1.7.8.x

**Comment by matks** [comment]
In order to fix this issue, we need to merge 1.7.8.x into 8.0.x

**Comment by matks** [comment]
Merge PR is here https://github.com/PrestaShop/PrestaShop/pull/29682

**Comment by hibatallahAouadni** [comment]
Closed as it has been fixed with this PR #29635

**Comment by jolelievre** [comment]
This issue initially targeted the 8.0 so we should check this issue on 8.0.x branch after https://github.com/PrestaShop/PrestaShop/pull/29682 has been merged

**Comment by matks** [comment]
Delivered in 8.0.x
