### ISSUE TITLE
hookDisplayProductButtons is deprecated - ps_sharebutton in PS 8.0.0

### ISSUE THREAD

**Issue by leemyongpakvn** [PrestaShop/PrestaShop#29189]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In PS 8.0.0, the product page with ps_sharebutton module installed displays this warning below Add to cart button
_Deprecated: The hook "displayProductButtons" is deprecated, please use "displayProductAdditionalInfo" instead in module "ps_sharebuttons"._ 

### Expected behavior

There should be no warnings because the module should not use a deprecated hook.

The module must use hook "displayProductAdditionalInfo".

### Steps to reproduce

1. Install a fresh PS 8.0.0 with sample data and all natives module.
2. Open the product page and see the warning there, under the Add to cart button.
![ps_sharbutton_hookDeprecated_DisplayProductButtons_PS800](https://user-images.githubusercontent.com/3759923/181457837-ea3d72ee-d89c-4779-8f88-b2e424348989.png)

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_sharebuttons 2.1.1

**Comment by HanaRebaiQA** [comment]
Hello @leemyongpakvn 

Thanks for your report.
I tried to reproduce your issue on **8.0.x branch** fresh install using **php7.2** and **php7.3** and **ps_sharebuttons 2.1.1 module** is configured. But, i was unable to reproduce it.

https://user-images.githubusercontent.com/92912932/181467919-199b772b-0a54-46cb-b689-9ce36661982e.mp4

Could you please check again ? Waiting for your feedback

Thank You!

**Comment by leemyongpakvn** [comment]
This issue is similar to PrestaShop/PrestaShop/issues/27986
Please check if ps_sharebutton is hooked to displayProductButtons or not 
![ps_sharebuttons_positions](https://user-images.githubusercontent.com/3759923/181477816-e180e164-d05d-4f36-81a8-894be1d14cd2.png)

**Comment by HanaRebaiQA** [comment]
Hello @leemyongpakvn 

Exactly! It's similar to `ps_emailalerts `issue.
By default and after a fresh install of 8.0.0, the `ps_sharebutton` module is associated to `displayProductAdditionalInfo` hook

![image](https://user-images.githubusercontent.com/92912932/181487383-0d582bdd-fd3c-4962-ab1f-5052c0292c54.png)


Thank You!

**Comment by leemyongpakvn** [comment]
Due to current code of [ps_sharebutton 2.1.1 line 72](https://github.com/PrestaShop/ps_sharebuttons/blob/dev/ps_sharebuttons.php#L72), it will be hooked to **displayProductButtons** by default. So I guess you applied a fix patch or transplanted module.
I tried to uninstall the module, delete the module folder and reinstall from [current version on github](https://github.com/PrestaShop/ps_sharebuttons/releases/download/v2.1.1/ps_sharebuttons.zip) and still see the error as default install.

**Comment by HanaRebaiQA** [comment]
Hello @leemyongpakvn 

Like mentioned in the steps to reproduce, when i used a fresh install 8.0.0 version with native modules and demo data. I couldn't reproduce the issue.

Did you used a fresh install ?

Thank You!

**Comment by leemyongpakvn** [comment]
@HanaRebaiQA I used a 2-day-old fresh install of PS 8.0.0, with neither additional theme nor additional module. If no one can reproduce this issue, I will create another issue more technical : just open [ps_sharebutton 2.1.1 line 72](https://github.com/PrestaShop/ps_sharebuttons/blob/dev/ps_sharebuttons.php#L72) and see the deprecated hook there.

**Comment by ghost** [comment]
Hello @HanaRebaiQA 

**How to test :** 

1) Uninstall the module et remove the foler.
2) Go to https://github.com/PrestaShop/ps_sharebuttons/releases/tag/v2.1.1
3) Donwload the last version 
4) Install it
5) Check depreceted message in FO

**Comment by okom3pom** [comment]
It's like issues [#27000](https://github.com/PrestaShop/PrestaShop/issues/27200) to https://github.com/PrestaShop/PrestaShop/issues/27213

**Comment by hibatallahAouadni** [comment]
Hello @leemyongpakvn & @okom3pom 

I didn't manage to reproduce the issue with PS8.0.0 and ps_sharebuttons v2.1.1, see the attached screenshots:

![image](https://user-images.githubusercontent.com/23308427/181808663-f62689da-9648-4d87-8ef5-d1e075f3f897.png)

![image](https://user-images.githubusercontent.com/23308427/181808842-0a34c254-74b4-41e8-ac74-40c5cd014723.png)

Please check and feedback.

PS: Related to #27986

Thanks!

**Comment by leemyongpakvn** [comment]
@hibatallahAouadni Did you try to **delete** the whole ps_sharbuttons module folder and install from the github 2.1.1 version follow @okom3pom 5 steps to reproduce?
FYI, Uninstall then install, or Reset in Back-office still keep the module folder and inner files.

**Comment by ghost** [comment]
https://user-images.githubusercontent.com/5064590/181887733-fe57a9d4-560f-4b6d-9fa2-e5a0ecc0b81d.mp4

**Comment by hibatallahAouadni** [comment]
Hello @leemyongpakvn 

I reproduce the issue with PS8.0.x and it's a regression on 8.0.0!
Thanks for your PR :rocket: I’ll add this to the debug backlog.

Thank you

**Comment by matks** [comment]
Thank you @leemyongpakvn for the bug report and thank you @okom3pom for helping exploring the steps needed to reproduce the bug
