### ISSUE TITLE
Remove all hardcoded widgets from theme

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#29198]
### Is your feature request related to a problem?

https://github.com/PrestaShop/hummingbird/blob/develop/templates/contact.tpl#L24

In hummingbird and classic theme, there is 
`{widget name="contactform"}`
`{widget name="ps_contactinfo" hook='displayLeftColumn'}`
`{widget name="ps_contactinfo" hook='displayRightColumn'}` 
on contact page.

When I want to use a different contact form module (with a spam protection for example), I need to hardcode modify the theme on all shops. And the modification will get lost after update.

### Describe the solution you'd like

Widgets should not be called from the template on default theme.

We should use normal hooks.

### Additional context

Ping @NeOMakinG @kpodemski @matks for specs on how we do it.

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 


Thank you for your suggestion. 
The Maintainer Team will take it into consideration for future developments. 

Thank you

**Comment by matks** [comment]
> Widgets should not be called from the template on default theme.
> We should use normal hooks.

I am not a module developer so from my point of view, a hook would indeed be better
- more flexible you can attach what you want (a widget or any other hook output)
- no hardcoded module

So for me it's a big YES. But I would like some more experienced module developers opinions: so I ping @Matt75 @PrestaEdit @kpodemski @Quetzacoalt91

**Comment by PrestaEdit** [comment]
Hi @matks ,

Thanks for the mention.

I agree with you two, there. It's true that it's a specific page and it could be handled in different way (like a "configurator" that allow you to choose the content in the main column, and in the left|right one).

The defaults themes needs to avoid the use of hardcoded module call (widgets or hooks), imho.

**Comment by matks** [comment]
For me this ticket is Ready as it is clear what should be done, and so far we all agree it's the right thing to do

**Comment by kpodemski** [comment]
I agree with the idea :)

**Comment by NeOMakinG** [comment]
@PrestaShop/prestashop-maintainers Which version should I aim?

**Comment by kpodemski** [comment]
I think v8.1 should be ok, as long as behavior and markup stays the same?

**Comment by NeOMakinG** [comment]
I guess we should introduce new specific hooks on every page where widgets are used then or am I missing something?

**Comment by kpodemski** [comment]
You're right, but this will be a new feature, with the release of a new module (because it will be needed), they could still be displayed as a widget and in the hook.
