### ISSUE TITLE
Catalog price rule condition by Category

### ISSUE THREAD

**Issue by erwanregnier** [PrestaShop/PrestaShop#29191]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi,
I would like to flag an issue with the Catalog Price rules conditions.
When the condition is based on the category, the rule applies only to the products which have this category as the main category.
It doesn't apply to all the products having this category as a secondary.

### Expected behavior

Should apply to all the products having this category, even if not as a main category

### Steps to reproduce

Create a product with 2 categories A and B, (A as the main category)
Go to Catalog > Discounts > Catalog price rules
Create a new rule, with a condition based on category B

The rule doesn't apply to this product

### PrestaShop version(s) where the bug happened

1.7.8.7

**Comment by HanaRebaiQA** [comment]
Hello @erwanregnier 

Thanks for your report.
Is one of these tickets are similar to yours [#14516](https://github.com/PrestaShop/PrestaShop/issues/14516), [#9977](https://github.com/PrestaShop/PrestaShop/issues/9977), [#9867](https://github.com/PrestaShop/PrestaShop/issues/9867)  and [#25698](https://github.com/PrestaShop/PrestaShop/issues/25698) ?

Please check and feedback

Thank You!

**Comment by erwanregnier** [comment]
Hi @HanaRebaiQA ,

no these are different issues

thanks !

**Comment by HanaRebaiQA** [comment]
Hello @erwanregnier 

Thanks for your feedback.
I was unable to reproduce your issue on **PS1787**.

Please check my screen-record : 

https://user-images.githubusercontent.com/92912932/181488760-d51e31e9-9f3e-4bc1-ba35-fdbab4ec07bd.mp4

Thank You!

**Comment by erwanregnier** [comment]
My bad, it was a problem with my installations (I tested on 2 versions but it still wasn't working, it works on a fresh install..)

**Comment by hibatallahAouadni** [comment]
@erwanregnier thanks for your feedback!
