### ISSUE TITLE
BO - Product V2 - New product created with quick access is not displayed in the list

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#29204]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After enabling the "New product page" in the BO > Advanced Parameters > New & Experimental Features page.
When we create a product from quick access => The product is not displayed in the list of products

https://user-images.githubusercontent.com/16067358/181798247-b00aa0de-965e-4ee7-9c16-b353c338dd4a.mp4

With Product V1 => OK

### Steps to reproduce

- [x] Case1

2. Go to BO > Advanced Parameters > New & Experimental Features page
3. Enable New product page - Single store and save
4. In the Quick access > click on New product 
5. Make some changes and save
6. Go to the Product list page
7. See error > the product is not displayed

- [x] Case2

1. Enable the multistore feature
2. Go to BO > Advanced Parameters > New & Experimental Features page
3. Enable New product page - Multi-store and save
4. In the Quick access > click on New product 
5. Make some changes and save
6. Go to the Product list page
7. See error > the product is not displayed

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1

**Comment by zuk3975** [comment]
should probably be solved by this
https://github.com/PrestaShop/PrestaShop/pull/29195

**Comment by mflasquin** [comment]
@MatShir maybe you can check if It's ok now ?

**Comment by MatShir** [comment]
Fixed 🥳
