### ISSUE TITLE
The module autoupgrade-dev you uploaded is not a module

### ISSUE THREAD

**Issue by ldetant** [PrestaShop/PrestaShop#29209]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![screenshot-module](https://user-images.githubusercontent.com/110394147/182139370-e018287a-0d0d-4298-a2e1-d67ae55dda14.png)
I downloaded the zip file autoupgrade-dev.zip from github and tried to add this module to my prestashop 1.5.3.1. The answer Prestashop is giving me is: "The module autoupgrade-dev you uploaded is not a module"

### Expected behavior

I expected this module to be added without any problems

### Steps to reproduce

1. Go to 'https://github.com/PrestaShop/autoupgrade'
2. Click the green button 'Code'
3. Click 'Download zip'
4. Go to prestashop back office
5. Go to the menu 'Modules > Modules'
6. Click 'Add a new module'
7. Browse to the downloaded file 'autoupgrade-dev.zip' and upload it
8. Then you see the error message in attachment

### PrestaShop version(s) where the bug happened

1.5.3.1

### PHP version(s) where the bug happened

5.3.29

### If your bug is related to a module, specify its name and its version

1-Click Upgrade Module (autoupgrade-dev.zip)

**Comment by ghost** [comment]
Hello @ldetant 

Please follow this steps

![Screenshot (98)](https://user-images.githubusercontent.com/5064590/182142714-a2b0f6af-2db6-43f8-a98e-eca1210c9fd6.png)
![Screenshot (99)](https://user-images.githubusercontent.com/5064590/182142742-9b0fbab8-9403-4cd4-ad2a-a3e7644df37d.png)

Your update is not easy since a 1.5 you should contact a professional 

Regards.

**Comment by hibatallahAouadni** [comment]
Hello @ldetant 

PrestaShop 1.5 is no longer supported.

PS: thanks @okom3pom for your quick reply :rocket: 

Thank you
