### ISSUE TITLE
FO / Blockwishlist - Translations are not take in account for "Wishlist default title" part

### ISSUE THREAD

**Issue by sLorenzini** [PrestaShop/PrestaShop#29212]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I want to change the "Wishlist default title" in English or French in BO, the translation is not updated on FO.

In the modal of "Add to wishlist":

https://user-images.githubusercontent.com/2854834/182158379-b99b1d62-6ab7-4e65-9b9a-fde7df0e2f59.mp4

In my account page, my wishlist tab:

https://user-images.githubusercontent.com/2854834/182158432-1efa9512-200e-4358-b447-52c0169ea678.mp4

Tested on 1.7.8.x / develop / 8.0.x branches and 1.7.7.8 version with 2.1.1 & 2.1.2 version of the module. It's not a regession but an old bug

### Expected behavior

The translations I've choosen on BO should take in account on FO

### Steps to reproduce

- Go to BO > Modules > Module manager > Search Wishlist" > Click on Configure
- Choose a language you want to change the default title of wishlist > update the wording by "My wishlist bis" for example > Click on "Save" button

**Case 1: Modal "Add to wishlist"**
- Go to FO > Should be logged
- On homepage, click on heart icon of the product > modal "Add to wishlist" is opened
- See error, in english "My wishlist" is still displayed instea of "My wishlist bis"

**Case 2: In my account page, my wishlist tab**
- Go to FO > Should be logged > go to "My wishlists" tab
- See error, in english "My wishlist" is still displayed instea of "My wishlist bis"

### PrestaShop version(s) where the bug happened

1.7.7.8 / 1.7.8.x / develop / 8.0.x

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

2.1.2

**Comment by paul-jolimoi** [comment]
Does it make sense to update translation from the configuration of the module ?
Appart of the default wishlist name maybe, but I think those configuration shall be removed and replaced by proper translation string managed by the translation system of prestashop ?

**Comment by matks** [comment]
> Does it make sense to update translation from the configuration of the module ?

I suppose it allow merchant to be able to customize this item from the "Configure" page of the module, and maybe it is easier than searching in the back-office translation page.

**Comment by paul-jolimoi** [comment]
Given the fact the module already gives translation for those items that seems a bit redundant, but I understand it is more visible in the module configuration.
