### ISSUE TITLE
Check whether or not upgrades from 1.7.x to 8.0 are possible

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#29217]
Before 8.0.0 beta is published, QA team wishes to check whether or not upgrades from 1.7.x to 8.0 are possible.

Tests will be performed using latest autoupgrade version, released in https://github.com/PrestaShop/PrestaShop/issues/29215

**Comment by Robin-Fischer-PS** [comment]
:warning: :red_circle: Since there is some trouble releasing the 4.15 autoupgrade version, the QA Team will check how the upgrade goes from 1.7.x to 8.0 with the 4.14.2 version. I change the status in "To be Tested" :red_circle: :warning: 

And ping @PrestaShop/qa-functional :)

**Comment by Robin-Fischer-PS** [comment]
Thanks to @AureRita , upgrade to 8.0 is tested : 

It has some issues, but not blocking the upgrade (see https://github.com/PrestaShop/PrestaShop/issues/29248). So it's OK for Beta.

Some notes that need to be added to the release note as "known issues" :

FYI : If you don't want to see the Error 500 when you do the update to 8.0.0, you have to uninstall this module :

Welcome
MBO (ps_mbo)
Metrics (ps_metrics)
Facebook (ps_facebook)
Marketing by google (psxmarketingwithgoogle)
