### ISSUE TITLE
Bug in Product controller, displayPackPrice smarty assign

### ISSUE THREAD

**Issue by abhi199424** [PrestaShop/PrestaShop#29222]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

when we assign displayPackPrice to smarty, its checking price less than product->getNoPackPrice(), but this finction returns a formatted price, if the price is begining with a symbol, we get error.
eg: €229.00
![Screenshot from 2022-08-02 13-03-59](https://user-images.githubusercontent.com/49970665/182318508-465501e5-8be8-44cb-9604-14af082dbddb.png)

### Expected behavior

for english language, pack price not showing

### Steps to reproduce

1 . create a pack product
2. check it with different language
3. currency euro is preffered
4. eg: format  €229.00

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

no

**Comment by hibatallahAouadni** [comment]
Hello @abhi199424 

Could you please provide a screen record about the issue or some screenshots :pray: 
Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @abhi199424 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
