### ISSUE TITLE
Cant make account on Firefox mobile Presta 1.7.8.7

### ISSUE THREAD

**Issue by Lerallo** [PrestaShop/PrestaShop#29221]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Cant make account on Firefox mobile Presta 1.7.8.7

www.Alkazam.pl

Not able to go step 2 about makin account

Geust and regular 

On Firefox mobile for android 

### Steps to reproduce

Not able to go step 2 about makin account

Geust and regular 

On Firefox mobile for android 

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.

### If your bug is related to a module, specify its name and its version

Eeeeeeee

**Comment by Lerallo** [comment]
In Polish there are 3 tick boxes insteed of 4 like in english.

**Comment by hibatallahAouadni** [comment]
Hello @Lerallo 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
