### ISSUE TITLE
Wrong stock movement when create new order BO

### ISSUE THREAD

**Issue by EhsanAllahyari** [PrestaShop/PrestaShop#29225]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi,
I found a bug on stock movement, I create a status and "set the order as shipped" is unchecked.
After that, I create an order and set the first status that status I created before.
But now the stock movement log create, and the reason is employee edition.
Actually, No logs should be created.

### Steps to reproduce

1. Create a status and "set the order as shipped" is unchecked
2. create an order
3. select first status that created before
4. check the stock log movement

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @EhsanAllahyari 

Could you please provide a screenshot about the created status (showing all details) and the stock page where you enocunter the issue :pray: 
Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @EhsanAllahyari 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
