### ISSUE TITLE
Error When try to update from 1.7.8.6 to 1.7.8.7

### ISSUE THREAD

**Issue by TecnoHands** [PrestaShop/PrestaShop#29220]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I try to update my store from 1.7.8.6 to 1.7.8.7 4 different ways and all times I get this error:
![image](https://user-images.githubusercontent.com/16818257/182249197-00f25b9b-a4d8-4f2b-aa51-c824a6c24106.png)

Information has
![image](https://user-images.githubusercontent.com/16818257/182249370-038168fe-e755-4564-afcf-958b91df6f3d.png)

I try without non prestashop modules, With theme warehouse, with classic theme, and all times give this error

In a wamp server Don't have this issue Prestashop Updating well. 

### Steps to reproduce

Update prestashop from 1.7.8.6 to 1.7.8.7

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

1.7.4

### If your bug is related to a module, specify its name and its version

autoupdate

**Comment by TecnoHands** [comment]
Manual update gives the error 32.
It's ok? then?

**Comment by medicalseeds** [comment]
After 30.0000 hours developing on this Bullsint i'ad enoug, PrestaAShop is the bigges pece of shit i've been seen,

And 8.0 is the same  bullshit, don't you realize?.

**Comment by ChillCode** [comment]
As you can read, the server response is service unavailable, so be sure to reconfigure everything, for example this great module fails if nginx it's configured with a timeout of 30"...every time I've to upgrade this great app called **PrestaShop** maybe takes  10min to 8h to reconfigure everything, also 1 click upgrade is a not production module...

Thanks for all!!!

**Comment by hibatallahAouadni** [comment]
Hello @TecnoHands 

First of all, it's not error! it's just warning :wink: 
Second, did you change this file `shop/autoupgrade/index.php` ? and why?
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @TecnoHands 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
