### ISSUE TITLE
retro-compat.js.php Arbitrary file view

### ISSUE THREAD

**Issue by onekingcc** [PrestaShop/PrestaShop#29237]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

retro-compat.js.php Existence of specific files to view
<img width="764" alt="image" src="https://user-images.githubusercontent.com/44469225/182585053-18d18b99-c3ef-4138-a36f-e275ca0835e1.png">

<img width="1318" alt="image" src="https://user-images.githubusercontent.com/44469225/182584689-0bec6aca-70ee-4dca-8efa-9f31a92b3809.png">

### Expected behavior

May trigger arbitrary file reads

### Steps to reproduce

As above

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.1

**Comment by matks** [comment]
@onekingcc I am sorry but your bug report is not clear enough. We can do nothing with "May trigger arbitrary file reads"

You need to provide more details

**Comment by kpodemski** [comment]
From what I see, this file allows us to read other .js files that are part of the array from this file.

**Comment by onekingcc** [comment]
> From what I see, this file allows us to read other .js files that are part of the array from this file.

yes，able to read  other .js files that are part of the array from this file ,But I think  retro-compat.js.php this file  does not need to be open to users，such as  [baseurl]/js/jquery.noConflict.php?version=123 , this is also the case.Of course, this is what I think, and the specifics still need to be evaluated by your side. Thank you

**Comment by AureRita** [comment]
Hi @onekingcc ,

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template and provide clear and concise steps to reproduce the bug**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
