### ISSUE TITLE
Extra FormFields validation does not work

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#29234]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Because of some changes required by PHPStan, the mechanism behind validating extra fields added from the modules doesn't work.

The BC Break was introduced there:
https://capture.dropbox.com/NJeqyMg1Py4i8BcZ

![image](https://user-images.githubusercontent.com/43613217/183430173-da543eeb-dc38-41ad-a6e1-58fcd061d610.png)

Error:

```
Uncaught Error: Call to a member function isRequired() on array in /Users/kpodemski/code/prestashop80/classes/form/AbstractForm.php:154 Stack trace: #0 /Users/kpodemski/code/prestashop80/classes/form/CustomerForm.php(203)
```

### Expected behavior

The extra field should be appropriately validated, as it was on 1.7.8 and below.

### Steps to reproduce

1. Use my test module.
2. Go to the registration page.
3. Try to register a new customer.
4. You'll notice a new field where it is required to type `test`.
5. Try to type something else. You should see an error.

It has to be tested on 1.7.8 and then on v8.0. No need to try on the older versions

Module to use:
[kpextracustomerfield.zip](https://github.com/PrestaShop/PrestaShop/files/9249866/kpextracustomerfield.zip)

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

n/a

**Comment by ghost** [comment]
The zip is empty :)

**Comment by kpodemski** [comment]
@okom3pom nice catch! thanks, I've uploaded symlink 😅

**Comment by AureRita** [comment]
Hi @kpodemski 

Thank you for the reporting Issue.
I reproduced it on 8.0.0 and not on 1.7.8.6 as you can see on this video :

https://user-images.githubusercontent.com/100699445/182576693-a72da7c8-95de-459b-bb8e-433f45a36beb.mp4

It's a regression ! I will add it to the Patch Backlog to be fixed 

Thanks

**Comment by kpodemski** [comment]
@AureRita IMHO, it's `Major` as it breaks the checkout flow :)

**Comment by matks** [comment]
Fixed by @zuk3975 https://github.com/PrestaShop/PrestaShop/pull/29416
