### ISSUE TITLE
Translations with special characters are not displayed properly

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#29236]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

1.7.8:
![image](https://user-images.githubusercontent.com/2137763/182582480-47fd46a9-ae46-42c8-b1a8-cf92f37684ea.png)

8.0.0:
![image](https://user-images.githubusercontent.com/2137763/182582798-cdfd9cb2-82ac-4de8-b994-92b3de1ba9d7.png)

### Expected behavior

Quotations marks should be properly displayed.

### Steps to reproduce

1. Install the example module.
2. Go to the configuration page.

Example module:
[kphelperformtranslations.zip](https://github.com/PrestaShop/PrestaShop/files/9250305/kphelperformtranslations.zip)

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

n/a

**Comment by AureRita** [comment]
Hi @kpodemski 

Thank you for the reporting Issue.
I reproduced it on 8.0.0 and not on 1.7.8.x as you can see on this video :

https://user-images.githubusercontent.com/100699445/182637381-f8c7da6d-7fdd-4b27-bb34-c099ab4483d8.mp4

It's a regression ! I will add it to the Patch Backlog to be fixed 

Thanks

**Comment by MeKeyCool** [comment]
I take this one.

**Comment by MeKeyCool** [comment]
From my first investigations I think the problem comes from this commit : https://github.com/PrestaShop/PrestaShop/commit/7e744697e0fb8ab1daa2e33d9bce6aaa1b765d8a

**Comment by MeKeyCool** [comment]
@kpodemski in your module, you used `AdminControllerCore::l(...)` function which isn't maintained anymore : https://github.com/PrestaShop/PrestaShop/blob/8.0.x/classes/controller/AdminController.php#L2708

Please use `AdminControllerCore::trans(...)` instead.

**Comment by MeKeyCool** [comment]
@kpodemski , I think @jolelievre is right, while `l(...)` function exists, even deprecated, we have to ensure it works as expected :)

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29441
