### ISSUE TITLE
CartRules calculation

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#29238]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello 

We have two cart rules types in cart :
- "Opération Made in France" in percentage : priority 2
- "Kit de bienvenue chien et chat" in amount (taxes excludes) priority 1

For percentage **(10%)** discount we applied discount only on "Made in France" products : 
- Pâtée pour chat Made in France - La Mousse Volaille & au foie
- Croquettes chat sans céréales au poulet - Made in France

For total amount discount we have 5,19 € and 13,99 € for percentage discount.
 
![Capture d’écran 2022-08-03 à 12 29 15](https://user-images.githubusercontent.com/110535069/182586991-706e473f-5f37-4e69-a810-ad0a1aa11837.png)
![Capture d’écran 2022-08-03 à 12 30 28](https://user-images.githubusercontent.com/110535069/182587196-820cd9ef-d007-4797-9925-02b7ef8bd1bd.png)
![Capture d’écran 2022-08-03 à 12 30 39](https://user-images.githubusercontent.com/110535069/182587212-69b743be-2791-485d-9e3c-ee538a30f4f6.png)

### Expected behavior

Then : 

Total discount should be 19,18 € but here we have 18,42 € (cf screenshots).

Total products : 95,26 €
Total discount : 19,18 €
Total : 76.08 €

We have 0.76 € difference and customer invoice is false.

### Steps to reproduce

1. Take two cart rules types
2. First in amount and add product condition with priority 1
3. Second in percentage and add products condition with priority 2  
4. add products in cart
5. See result

### PrestaShop version(s) where the bug happened

1.7.7.5/1.7.8.5

### PHP version(s) where the bug happened

7.2/7.3

**Comment by AureRita** [comment]
Hi @AtavikTech 

Just to know, why did you closed your issue ? You take the time to write this issue so I think it can be important for you that we take time to consider this one 

Waiting for your feedback
