### ISSUE TITLE
Use of class AdminProductWrapper

### ISSUE THREAD

**Issue by Lopez15-Hub** [PrestaShop/PrestaShop#29247]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello! Now i'm migrating my module to the latest pretashop version and i have problems creating the constructor of class AdminProductWrapper. 

In older versions the class AdminProductWrapper had two attributes. Now have four.

![image](https://user-images.githubusercontent.com/65269387/182762359-d589c3bc-e223-4162-ad3a-e401ec0719da.png)

I need an example about to how implement an instance of this class like this:

`$this->adminProductWrapper = new \PrestaShop\PrestaShop\Adapter\Product\AdminProductWrapper(Context::getContext()->getTranslator(),$this->localization);`

I use this class from get data from customTextField :

```
    private function processProductCustomization($product) {
        $default_lang = (int) Configuration::get('PS_LANG_DEFAULT');

        $fields = array();
        $customization_field = array();
        $customization_field["type"] = Product::CUSTOMIZE_TEXTFIELD;
        $customization_field["label"] = array();
        foreach (Language::getLanguages() as $language) {
            $customization_field["label"][$language['id_lang']] = $this->customizationFieldText;
        }
        $customization_field["require"] = false;
        $customization_field["id_product"] = $product->id;
        $customization_field["id_customization_field"] = null;
        $fields[] = $customization_field;

        $this->adminProductWrapper->processProductCustomization($product,$fields);
    }
```

### Steps to reproduce

Create an instance of adminProduct Wrapper like this:

`
`$this->adminProductWrapper = new \PrestaShop\PrestaShop\Adapter\Product\AdminProductWrapper(Context::getContext()->getTranslator());``

run the programan on php console

and you should can see the next error log:

[03-Aug-2022 00:05:01 America/Argentina/Buenos_Aires] PHP Fatal error:  Uncaught TypeError: Argument 2 passed to PrestaShop\PrestaShop\Adapter\Product\AdminProductWrapper::__construct() must be of the type array, object given, called in /home/test/public_html/modules/presta_zeus/PrestaZeusSync.php on line 53 and defined in /home/test/public_html/src/Adapter/Product/AdminProductWrapper.php:96
Stack trace:
#0 /home/test/public_html/modules/presta_zeus/PrestaZeusSync.php(53): PrestaShop\PrestaShop\Adapter\Product\AdminProductWrapper->__construct(Object(PrestaShopBundle\Translation\TranslatorComponent), Object(Context))
#1 /home/test/public_html/modules/presta_zeus/cron.php(29): PrestaZeusSync->__construct()
#2 {main}
  thrown in /home/test/public_html/src/Adapter/Product/AdminProductWrapper.php on line 96

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

src/Adapter/Product/AdminProductWrapper.php

**Comment by Matt75** [comment]
You have to retrieve the instance of AdminProductWrapper from service container:

1. https://devdocs.prestashop.com/1.7/modules/concepts/services/
2. https://github.com/PrestaShop/PrestaShop/blob/1.7.8.7/src/PrestaShopBundle/Resources/config/services/adapter/product.yml#L25

So

```
$adminProductWrapper = new \PrestaShop\PrestaShop\Adapter\Product\AdminProductWrapper(Context::getContext()->getTranslator(),$this->localization);
```

Should be 
```
        /** @var \PrestaShop\PrestaShop\Adapter\Product\AdminProductWrapper $adminProductWrapper */
        $adminProductWrapper = $this->get('prestashop.adapter.admin.wrapper.product');
```

**Comment by AureRita** [comment]
Hi @Lopez15-Hub ,

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Thank you
