### ISSUE TITLE
Release ps-linklist 5.0.5

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#29242]
This is a technical task needed to complete PrestaShop 8.0.0

- [x] Release https://github.com/PrestaShop/ps_linklist/milestone/8
- [x] Update the file https://github.com/PrestaShop/PrestaShop/blob/develop/composer.lock to embed ps_linklist 5.0.5 in PrestaShop 8

**Comment by matks** [comment]
PR for module release https://github.com/PrestaShop/ps_linklist/pull/153

**Comment by matks** [comment]
Module 5.0.5 released

**Comment by matks** [comment]
PR https://github.com/PrestaShop/PrestaShop/pull/29535 will update Composer in the Core software

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29535
