### ISSUE TITLE
progress bar not showing

### ISSUE THREAD

**Issue by studiosacchetti** [PrestaShop/PrestaShop#29245]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

i'm developing a module with frontend progress bar, it seem that colored bar it showed only with some characters in bar value

es

```
<div class="progress">
      <div class="progress-bar bg-primary" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
</div>
```

![immagine](https://user-images.githubusercontent.com/33520105/182652092-b90bff88-2b15-4ace-864c-895335793d60.png)

```
<div class="progress">
     <div class="progress-bar bg-primary" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">test</div>
</div>

```

![immagine](https://user-images.githubusercontent.com/33520105/182652507-bc9faf8d-3397-4879-99ff-09dfc8461def.png)

### Expected behavior

![immagine](https://user-images.githubusercontent.com/33520105/182653440-705a0a07-371f-4755-8945-f13e20161a8f.png)

### Steps to reproduce

it seems to happen without particular operation

### PrestaShop version(s) where the bug happened

1.7.8.6 

### PHP version(s) where the bug happened

7.2.34

**Comment by PrestaEdit** [comment]
Using the Classic theme, you could have this kind of issue, yes.

The progressbar component inside Bootstrap was remork/updated inside the alpha 6 of it. Classic use the alpha 5.

**Comment by studiosacchetti** [comment]
good to know!!

i used this workaround

```
<div class="progress">
   <div class="progress-bar bg-primary" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">&nbsp;</div>
</div>
```
