### ISSUE TITLE
[Autoupgrade] - Errors when upgrading from 1.7.8.6 to 8.0.0 

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#29248]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I want to update my version 1.7.8.6/1.7.8.7 to 8.0.0 I've this error at the end of the process of updating 

![image](https://user-images.githubusercontent.com/100699445/182815897-4a5e946d-cb21-4921-9844-61102de29bd7.png)

FYI - If you don't want to see the Error 500 when you do the update to 8.0.0, you have to uninstall the following modules: 

- Welcome
- MBO (ps_mbo)
- Metrics (ps_metrics)
- Facebook (ps_facebook)
- Marketing by google (psxmarketingwithgoogle)

### Expected behavior

I shouldn't get the errors messages 

### Steps to reproduce

1. Do a fresh install of prestashop 1.7.8.6/ 1.7.8.7
2. Go to Modules > Module Catalog
3. Install 1-Click Upgrade (autoupdate)
4. Put the zip of prestashop 8.0.0 and it xml on the folder [your domain] > admin[?] > autoupgrade > download 
5. Scroll down to go to the expert mode 
6. On channel, choose : local archive 
7. Select the files prestashop zip and the xml and name it "8.0.0"
8. Clic on Save and wait until the page was refresh 
9. Now launch the autoupgrade with the button "upgrade prestahshop now !"
10. wait the end of the process and see error 

### PrestaShop version(s) where the bug happened

1.7.8.6 to 8.0.0 - 1.7.8.7 to 8.0.0

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

autoupgrade 4.14.2

**Comment by TouchCab** [comment]
Step 4, where do I get the XML from?!

**Comment by matthieu-rolland** [comment]
Hi @TouchCab , thank you for your interest, this issue is being taken care of.

To answer your question, you get this XML when you create a release from a PrestaShop project, from the root of your prestashop project in CLI: `php tools/build/CreateRelease.php`

~~You will also find this file in the zip when you download a PrestaShop release~~

**Comment by TouchCab** [comment]
> Hi @TouchCab , thank you for your interest, this issue is being taken care of.
> 
> To answer your question, you get this XML when you create a release from a PrestaShop project, from the root of your prestashop project in CLI: `php tools/build/CreateRelease.php`
> 
> You will also find this file in the zip when you download a PrestaShop release

Unless I’m being particularly stupid, the xml isn’t in the zip…?

**Comment by matthieu-rolland** [comment]
> > Hi @TouchCab , thank you for your interest, this issue is being taken care of.
> > To answer your question, you get this XML when you create a release from a PrestaShop project, from the root of your prestashop project in CLI: `php tools/build/CreateRelease.php`
> > You will also find this file in the zip when you download a PrestaShop release
> 
> Unless I’m being particularly stupid, the xml isn’t in the zip…?

no you're not, it's my mistake :) 
Indeed you will only see this xml if you create a release from a local prestashop, when doing an upgrade from a local archive (the xml is not in the distrubuted archives)
