### ISSUE TITLE
Uploading the same version of a running module fails on 8.0

### ISSUE THREAD

**Issue by Quetzacoalt91** [PrestaShop/PrestaShop#29241]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello :wave: 

I found a change of behavior in the module manager when we upgrade a module.

On PrestaShop v8, reuploading the same version of a module fails. I encountered this issue while uploading changes to test on a module without bumping its version.
When an upgrade fails or triggers an exception, there is an automatic action that disables the module.

In consequence even if my module is valid, I get the most generic error and my module is disabled. As we are currently on the compliancy with PrestaShop v8, I was assuming that our module was still breaking the shop.

![image](https://user-images.githubusercontent.com/6768917/182605131-24c4c22b-1e8c-4fee-98ea-f59971c14628.png)

**The concerned code was like this on 1.7.x:**
https://github.com/PrestaShop/PrestaShop/blob/14cb6a4c6e72c55c16a95cfbe4aeb8e44fe73ab5/src/Adapter/Module/ModuleDataUpdater.php#L113-L117
(We could refacto this to always return `true`)

**And like this on 8.x :**
https://github.com/PrestaShop/PrestaShop/blob/79b15c0b0ad54e6eafc58841ecf3f889957b9384/src/Core/Module/ModuleManager.php#L348

Was this change of behavior expected?

### Expected behavior

The zip upload should succeed, even if there is upgrade scripts to run or version to upgrade in the database.

https://user-images.githubusercontent.com/100699445/182632061-958a90d3-4e7a-4de9-bf65-c096e23ed4af.mp4

### Steps to reproduce

1. Get a zip of a module
2. Upload it via your module manager: :heavy_check_mark: 
3. Upload it via your module manager a second time: :fire:

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.0

**Comment by AureRita** [comment]
Hi @Quetzacoalt91 

Thank you for the reporting Issue.
I reproduced it on 8.0.0. and not on 1.7.8.x as you can see on this video :

https://user-images.githubusercontent.com/100699445/182632061-958a90d3-4e7a-4de9-bf65-c096e23ed4af.mp4

It's a regression ! I will add it to the Patch Backlog to be fixed 

Thanks

**Comment by ghost** [comment]
For me it's the same : https://github.com/PrestaShop/PrestaShop/issues/28924 

The title is not the same but for me the bug it's the same. 

You can check @Quetzacoalt91 ?

**Comment by Quetzacoalt91** [comment]
I saw the other issue before posting and it seemed unrelated. On my side, files were uploaded and moved into the modules folder successfully, but because the module version remains the same, PrestaShop does not find upgrade to run, thinks there was an issue then disables my module.

**Comment by ghost** [comment]
I will check again on my side but the only way for me was to delete the module folder before sending the same version.

I confirm that this bug is not solved.
