### ISSUE TITLE
MPN field is missing in sample product CSV

### ISSUE THREAD

**Issue by Amit-Kumar-Tiwari-Webkul** [PrestaShop/PrestaShop#29254]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

MPN field is missing in sample product CSV
[screencast-nimbus-capture-2022.08.04-19_51_20.webm](https://user-images.githubusercontent.com/42021740/182871289-3433223a-8674-4760-aa76-9378409d4947.webm)

### Steps to reproduce

1. Go to the Advanced parameter->import section
2. Download sample product CSV file
3. Upload it as an import file
4.  Due to missing column MPN all fields orders displaying wrong 

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.1

**Comment by AureRita** [comment]
Hi @Amit-Kumar-Tiwari-Webkul ,

I understand that it can be a little uncomfortable. I reproduce the issue with PrestaShop version1.7.8.6, as you can see : 

https://user-images.githubusercontent.com/100699445/182886088-8741a0a2-735f-4b6c-9410-476eb567557d.mp4

I'll add this to the backlog so it can be fixed. 

Thank you for the PR :rocket:
and
Thank for your report

**Comment by PrestaEdit** [comment]
https://github.com/PrestaShop/PrestaShop/pull/32411

**Comment by kpodemski** [comment]
Fixed for v9
