### ISSUE TITLE
cannot enter info for product summary and description 1.7.8.7

### ISSUE THREAD

**Issue by USWine88** [PrestaShop/PrestaShop#29257]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![IMG_0995](https://user-images.githubusercontent.com/110627765/182917965-114923da-f6e9-4dfa-8750-c8d112579d90.jpg)

### Steps to reproduce

Product page.

### PrestaShop version(s) where the bug happened

1.7.8.7

**Comment by hibatallahAouadni** [comment]
Hello @USWine88 


Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: open the browser console, you will find that there's some JS errors, try to clear cache and reload the page.

Thanks!
