### ISSUE TITLE
StockMovement physical_quantity boundaries are not high enough

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#29253]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the `stock_mvt` table the comumn `physical_quantity` is defined as an `int(11)` which is slightly higher than the `StockaAvailable::quantity` field which is a `int(10)`. This is logical because stock movement values can be higher than the max boundaries of the stock itself Twice as high actually, since it can vary from the min value `-2147483648` to the max value `2147483647` So it's range should be from `-4294967296` to `4294967296`.

The problem is that in MySQL regardless of the int length value the maximum value for an int column will always be a 4bytes integer meaning `2147483647` max, this results in possible impossible values to be saved in the stock movement table.

### Expected behavior

The database structure should be modified so that `stock_mvt.physical_quantity` should be a BIGINT thus allowing to have appropriate boundaries.

### Steps to reproduce

In the stock page or in the product page v2:

1. Edit the stock of the product to `2147483647` and save the value
2. Edit the stock to a `-2147483648` value
3. The stock should be updated but a MySQL error should happen when trying to create the row of the stock movement
4. Thus the stock movement is never saved

### PrestaShop version(s) where the bug happened

8.0 and probably before

**Comment by AureRita** [comment]
Hi @jolelievre ,

I reproduce the issue with PrestaShop version 8.0.0, as we can see : 

https://user-images.githubusercontent.com/100699445/182889191-d589c1ed-9271-4de4-9c72-9ec196cecafe.mp4

I'll add this to the backlog so it can be fixed.

Thank you for the PR :rocket:

Thanks

**Comment by margud** [comment]
This [PR](https://github.com/PrestaShop/PrestaShop/pull/29081) fixes the issue where stock_mvt can have 2x the size. But i guess we can change it to BigInt so that the quantity can be bigger. But then we need to change it for stock_available table same as stock_mvt? @jolelievre
