### ISSUE TITLE
[PHP8.1]  - A warning is displayed ine the File manager

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#29268]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > When we try to insert an image in the TinyMCE (product page, category page), a warning is displayed in the fileManager
![V2_image_Tinymce](https://user-images.githubusercontent.com/16067358/183112224-9c9e60f3-27a7-49cc-ab86-477d3070cf59.png)

Ping @atomiix 

### Steps to reproduce

1. Use PHP8.1
2. Go to BO > Catalog > Categories page
3. Edit any category
4. In the description, try to insert an image
5. See error

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1

**Comment by atomiix** [comment]
Fixed by #29272
