### ISSUE TITLE
Wrong body class is set to module front controller

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#29265]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you create module front controller, it doesn't use proper body class in the controller. See steps to reproduce.

### Steps to reproduce

1. Install this module [tox_layouttest.zip](https://github.com/PrestaShop/PrestaShop/files/9293465/tox_layouttest.zip)
2. Go to backoffice > **Theme & logo** > bottom of the page **Choose layouts** and check that `category` and `layouttest` pages have both set the same left column layout.
3. Go to any category on your shop, check source code of the page, find `<body>` tag, and see that there is correct `layout-left-column` class on it.
4. Go to `/layouttest` in the front office of your shop, check source code of the page, find `<body>` tag, and see that there is `layout-full-width` instead of `layout-left-column`.

_This is important, because themes use it to style the page. For example to have proper product columns count._

### Cause

See FrontController here:
https://github.com/PrestaShop/PrestaShop/blob/d1e14ec7b1f959f370915ecb9b34afe28b098e88/classes/controller/FrontController.php#L1677

It tries to get the body class by `php_self`, which is not used by module front controllers and is empty.

It should use `page_name` like in `getLayout` function here:
https://github.com/PrestaShop/PrestaShop/blob/d1e14ec7b1f959f370915ecb9b34afe28b098e88/classes/controller/FrontController.php#L1299

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.0

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Could you please provide a test module to help me reproducing the issue.
Waiting for your feedback.

Thanks!

**Comment by Hlavtox** [comment]
Hi @hibatallahAouadni 

1. Install this module [tox_layouttest.zip](https://github.com/PrestaShop/PrestaShop/files/9293465/tox_layouttest.zip)
2. Go to backoffice > **Theme & logo** > bottom of the page **Choose layouts** and check that `category` and `layouttest` pages have both set the same left column layout.
3. Go to any category on your shop, check source code of the page, find `<body>` tag, and see that there is correct `layout-left-column` class on it.
4. Go to `/layouttest` in the front office of your shop, check source code of the page, find `<body>` tag, and see that there is `layout-full-width` instead of `layout-left-column`.

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

I encounter an issue while installing your module, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/183376051-3a7dcd85-a873-45f9-af1d-deb6ade50354.png)

Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thanks for all details :pray: 
I reproduce the issue with PS8.0.x, PS1.7.8.6 and PS1.7.7.0! I’ll add this to the debug backlog so that it’s fixed.
And thanks for your PR :rocket: 

Thank you
