### ISSUE TITLE
Add identifying classes to manufacturer and supplier

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#29263]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

ProductController, CategoryController, CmsController and others provide additional identifying classes in the html `<body>` tag, like `category-id-XXX` or `category-xxxxx`. 

It would be good if we standardize it and manufacturer+supplier controllers also provide it.

### Describe the solution you'd like

Add missing classes to manufacturer and supplier controller.

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. 
Thanks for your PR!

Thank you

**Comment by Hlavtox** [comment]
Ping @eshraw for validation

**Comment by eshraw** [comment]
Thanks @Hlavtox for the issue.

LGTM, it's always good to standardize such things 👍
