### ISSUE TITLE
Wrong body class is set to when using content_only parameter

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#29266]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you request content with `?content_only=1`, wrong body class is set. See steps to reproduce.

### Steps to reproduce

1. Get default prestashop installation. It should have CMS pages set with left column.
2. When you inspect source code of any CMS page and check `<body>` tag, it should have `layout-left-column` class.
3. Now add `?content_only=1` to the end of the URL to get only the content. Check source code again.
4. Prestashop will use correct layout `layouts/layout-content-only.tpl`, but the class in body tag will not change and still be `layout-left-column` - wrong :red. It should be `layout-content-only`.

### Cause

See that FrontController applies correct layout TPL file when using content_only here:
https://github.com/PrestaShop/PrestaShop/blob/d1e14ec7b1f959f370915ecb9b34afe28b098e88/classes/controller/FrontController.php#L1323

But completely ignores it while getting the body class:
https://github.com/PrestaShop/PrestaShop/blob/d1e14ec7b1f959f370915ecb9b34afe28b098e88/classes/controller/FrontController.php#L1677

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.0

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

I didn't manage to reproduce the issue :disappointed: could you please provide a screen record about the issue.
Waiting for your feedback.

Thanks!

**Comment by Hlavtox** [comment]
Hi @hibatallahAouadni, I don't know how to show it more...

1. Open any prestashop store.
2. Open any CMS page, for example **Delivery**
3. You should see normal page. When you right click > Show source code, you see in the `<body>` tag the current layout used - `layout-full-width` / `layout-left-column` and others.

![normal](https://user-images.githubusercontent.com/6097524/183263399-a7f8c237-d1ea-49f3-b21c-7e8cc41f44ec.jpg)

4. Now add `?content_only=1` to the URL, so it looks for example like `www.yourshop.com/en/content/1-delivery?content_only=1`. You should now see only the content, no header, no sidebar, no footer, no nothing, because layout `layouts/layout-content-only.tpl` gets used.
5. Now show source code again and you will see, that the body tag remained the original `layout-full-width` or `layout-left-column`, instead of `layout-content-only`.

![content](https://user-images.githubusercontent.com/6097524/183263495-dc10a5b3-2475-4ae4-bbf1-a6502a946729.jpg)

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

I was able to reproduce the issue with PrestaShop versions 1.7.6.7, 1.7.7.8, 1.7.8.6, 8.0.0 and develop. I’ll add this to the debug backlog so that it’s fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. 
So, we're waiting for your PR :rocket: 

PS: ping @PrestaShop/product-team should we use this class `layout-content-only` when accessing to CMS page in FO adding `?content_only=1` to the URL?

Thank you

**Comment by eshraw** [comment]
Hello @Hlavtox , thanks for the issue.

@hibatallahAouadni @Hlavtox LGTM 👍
