### ISSUE TITLE
Add a setting to configure `X-Frame-Options` / `Content-Security-Policy` headers

### ISSUE THREAD

**Issue by atomiix** [PrestaShop/PrestaShop#29260]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

As of today, there is no simple way to configure the behavior of a PrestaShop website when included in a iframe.
Also, setting correct `Content-Security-Policy` headers can help protect PrestaShop against XSS

### Describe the solution you'd like

I'd like a setting in the advanced parameters where I can configure those headers so they're send for each request then.

### Alternatives you've considered

Setting those header on Apache/Nginx directly

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @atomiix 

Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. 
So, we're waiting for your PR :rocket: 

Thank you

**Comment by atomiix** [comment]
Closing this one in favor of #12970
