### ISSUE TITLE
Product V2 - Cannot change the pagination in the "Edited combinations" modal

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#29267]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the "Edited combinations" modal, when we edit a combination with too long a name, the pagination is NOK

https://user-images.githubusercontent.com/16067358/183107644-cf532a4a-106d-4735-b9f1-d25fd8a26b6f.mp4

### Steps to reproduce

1. Go to BO > Advanced Parameters > New & Experimental Features page & Enable New product page - Single store
2. Go to BO > Catalog > Products V2
3. Create a product with combinations
4. Generate at least 15 combinations (try to create a combination using all the attributes: Size  - Color - Dimension - Paper Type)
5. Click to edit a combination & try to make changes for 15 combinations at least
6. In the "Edited combinations" modal > Try to use pagination => NOK

![image](https://user-images.githubusercontent.com/16067358/183108664-0635aa5c-d102-483c-9221-1a80aceacdb4.png)

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29281
