### ISSUE TITLE
Prestashop 1.7.x PHPSESSID cookie expiration Lifetime

### ISSUE THREAD

**Issue by 01Kuzma** [PrestaShop/PrestaShop#29285]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Prestashop PHPSESSID session cookie has an expiration time set to 2075y.

That's not a good solution for a GDPR policy.

It could be checked in the online [demo](https://demo.prestashop.com/#/en/front)

What are the motives for setting such a long period?

### Expected behavior

Able to set this cookie for a session lifetime

### Steps to reproduce

Check cookies in the online demo, or own 1.7.x installation 

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @01Kuzma 

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you

**Comment by 01Kuzma** [comment]
@hibatallahAouadni, but literally it's a bug. Session cookie must be set only for a session period, not for 53years

**Comment by hibatallahAouadni** [comment]
Hello @01Kuzma 

It looks like a good improvement :wink: 
Could you please create a new issue with the Feature template, so the developer team can study it :pray: 

Thanks in advance!

**Comment by ghost** [comment]
This one :) 

https://github.com/PrestaShop/PrestaShop/issues/new?assignees=&labels=Feature%2CNew&template=2_feature_request.yml

**Comment by 01Kuzma** [comment]
Done,
thanks to all of you!
