### ISSUE TITLE
Contextual help is not well displayed

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#29287]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The markdown used on help docs is not handled and you have somes emojis and/or block shown as it.

Also, I see the "Contribuer" and the "description: >- " on the beginning of the doc.

<img width="504" alt="Capture d’écran 2022-08-09 à 15 44 35" src="https://user-images.githubusercontent.com/2631425/183665311-a77c7f2e-34a2-4b14-8515-ec9f04f70cc5.png">

<img width="504" alt="Capture d’écran 2022-08-09 à 15 44 22" src="https://user-images.githubusercontent.com/2631425/183665297-d173813b-16fd-4ea2-8d26-ebd3ed78cbb9.png">

### Steps to reproduce

1. Go on orders
2. Check an order
3. Push the "Help" button

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

I didn't manage to reproduce the issue with PS800, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/183723007-52a67355-0ac4-46aa-8509-5b4a9c322a5e.mp4

Please check and feedback.

Thanks!

**Comment by PrestaEdit** [comment]
I've put my Back Office in english and having the same result.
Quite strange, this.

**Comment by PrestaEdit** [comment]
This is the link that I have, that is loaded : https://help.prestashop-project.org/gb/doc/AdminOrders?version=8.0.0&country=gb
Opening it show me the content as my screen capture.

**Comment by ghost** [comment]
I'm not sure?  Do you both have this PR @PrestaEdit && @hibatallahAouadni 

https://github.com/PrestaShop/PrestaShop/pull/29230

Unrelated surely?

**Comment by PrestaEdit** [comment]
Yes, @okom3pom ; it's included in the 8.0.0-beta.1 (and on my instance, so).

**Comment by ghost** [comment]
https://help.prestashop-project.org/en/doc/AdminOrders?version=8.0.0&country=en

https://help.prestashop.com/en/doc/AdminOrders?version=8.0.0&country=en

I see but i can't reproduce :o i'll try a new install

**Comment by ghost** [comment]
I can confirm on a new install the bug is present

![Screenshot - 2022-08-10T143331 700](https://user-images.githubusercontent.com/5064590/183902293-886b0423-8108-4438-a1cb-a5ad86b81007.png)

**Comment by ghost** [comment]
If you need screenrecord ask me @hibatallahAouadni

**Comment by AureRita** [comment]
Hi @PrestaEdit 

Unfortunately, this issue was mentionned when we tried the PR that add this part, we can see the answer by @matks 
https://github.com/PrestaShop/PrestaShop/pull/29230#issuecomment-1206799005

I'll close this issue

**Comment by PrestaEdit** [comment]
Hope that it will be not forgotten later as it's a comment of  merged pull request, so :)
