### ISSUE TITLE
Delivery address force as invoice address when use "use different addresses for invoice"

### ISSUE THREAD

**Issue by DelecroixQuentin** [PrestaShop/PrestaShop#29289]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi,

Firstly, this issue is similar to this [one](https://github.com/PrestaShop/PrestaShop/issues/28511).

When a new customer chooses to use two different addresses for shipping and billing, PrestaShop forces the billing address with the shipping address previously created.

https://user-images.githubusercontent.com/8830801/183665685-a0ec1569-282e-4637-8e23-f01a1b205120.mov

That the payload post by the billing address form :
![image](https://user-images.githubusercontent.com/8830801/183670512-f8b1d9a6-dfe4-4601-869b-fe89dfcf00a0.png)

If you check the code [here](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/classes/checkout/CheckoutAddressesStep.php#L161-L202), I think it cause by this condition `if (isset($requestParams['id_address_delivery'])) {` beeing valid. So these [lines (L168 to L176)](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/classes/checkout/CheckoutAddressesStep.php#L168-L176)  are executed BUT, at this time, the `$this->use_same_address` is set to `true` (dont know why), that means the billing address is override by the delivery address get from the `id_address_delivery` field from the payload (L163).

### Expected behavior

Set billing address with the last created address (step 3 in **Steps to reproduce**)

### Steps to reproduce

Add product to your cart and go to the checkout
Next :
1. Create new customer
2. Create new delivery address and uncheck "use different addresses for invoice" 
3. Create new billing address
4. You will be redirected to step 3 but return to step 2 and see billing address set with delivery address

### PrestaShop version(s) where the bug happened

1.7.8.7 - 8.0.0 - develop

### PHP version(s) where the bug happened

7.4

**Comment by AureRita** [comment]
Hi @DelecroixQuentin ,

I reproduce the issue with PrestaShop version 1.7.8.6 and not with the version 1.7.7.8. Nice catch ! It's a regression ! I'll add it to the patch backlog.

Please be aware that some issues might take a very long time to be resolved. 

If you want, you can [add your correction to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29632
