### ISSUE TITLE
Multistore - BO - Products V2 - Bad displaying of the list with combinations 

### ISSUE THREAD

**Issue by szavadskiy** [PrestaShop/PrestaShop#29282]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![ksnip_20220809-124038](https://user-images.githubusercontent.com/90208051/183631189-4d89924f-b700-4c7e-9e9b-94b06406f6e2.png)

### Steps to reproduce

1. open multistore environment 
2. enable "New product page - Multi store" in BO
3. open some product with combinations in BO
4. open "Combinations" tab
5. check combination list 

### PrestaShop version(s) where the bug happened

8.0.0 beta 1

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Hello @szavadskiy 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #28934. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #28934
