### ISSUE TITLE
BO - The images are not well displayed after adding it in file manager with php8.1

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#29291]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The images are not well displayed after adding it in file manager with php8.1

**8.0.x with php8.1 : NOK** :x: 
![image](https://user-images.githubusercontent.com/92912932/183697154-9f8b09b7-e6e0-4889-bc3f-246018dff1bf.png)

**8.0.x with php7.3 : OK** :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/92912932/183697313-24cd9998-3e7a-47b5-937c-5462d9f9de8a.png)

### Expected behavior

The images are well dispalyed

### Steps to reproduce

1. Check with php8.1
2. Go to BO > Catalog > Categories page OR Products page
3. Edit any Category/Product
4. Insert any type of image (jpeg, png, ..) in the file manager
5. Click on Return to files list to come back to the list of displayed images in the file manager
6. See error >> The images are not well displayed!

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29481
