### ISSUE TITLE
BO - A warnings are displayed in the file manager when add an SVG image extension with php8.1

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#29292]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

A warnings are displayed in the file manager when add an SVG image extension with php8.1

**8.0.x with php8.1 : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/183698895-abe11a88-c4e5-48a1-b45c-b000f2bb48ae.png)

https://user-images.githubusercontent.com/92912932/183698943-fb20f6ad-e3bb-48ea-b1eb-f78b48239ccd.mp4

**8.0.x with php7.3 : OK** :heavy_check_mark: 

https://user-images.githubusercontent.com/92912932/183698966-09de47ff-971f-450c-a1db-c806ca3334e9.mp4

### Expected behavior

No warning is displayed

### Steps to reproduce

1. Check with php8.1
2. Go to BO > Catalog > Categories page OR Products page
3. Edit any Category/Product
4. Insert an image with SVG extension in the file manager
5. Back to the list of displayed images in the file manager
6. See error >> A warnings are displayed

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29375
