### ISSUE TITLE
Price problem with two diffents discount together into the same group

### ISSUE THREAD

**Issue by MoschiMa** [PrestaShop/PrestaShop#293]
Hi i have find one bug about Discount and the final price of the product.
I'm into the latest version 1.5.3.1
I use the group for my customer.
Defaut for the basic customer and REV for my dealer
I made one product with this price 100euro TTC
I made this discount for the dealer section : less 50 % for this product.
into the FO : this product it's at:
100 for the defaut and 50 for the dealer.
It's ok at this time

Now i ADD one new discount for ANY groups
less 10 euro for this product, for made one action.
Now the price write it's
90 for the defaut group, but only 50.00 TTC for the dealer ... it's wrong
Normally the final price for the dealer group it's  : 
100 - 10 = 90 and now and made the 50%, total 45 euro
Thanks for the help
Regards Maurice

**Comment by marionf** [comment]
Hello, 
This issue is old, so I close it.
If you still have it on the last version (PrestaShop 1.7.4.2), please open a new one.
Regards
