### ISSUE TITLE
ProductAttribute getAttributeMinimalQty function incorrect

### ISSUE THREAD

**Issue by roja45** [PrestaShop/PrestaShop#29301]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This function is returning false when minimum quantity is 1.  Shouldn't if ($minimalQuantity > 1) be if ($minimalQuantity)?

```
public static function getAttributeMinimalQty($idProductAttribute)
    {
        $minimalQuantity = Db::getInstance()->getValue(
            '
			SELECT minimal_quantity
			FROM ' . _DB_PREFIX_ . 'product_attribute_shop pas
			WHERE id_shop = ' . (int) Context::getContext()->shop->id . '
			AND id_product_attribute = ' . (int) $idProductAttribute
        );
        if ($minimalQuantity > 1) {
            return (int) $minimalQuantity;
        }
        return false;
}
```

### Steps to reproduce

Look at the code

### PrestaShop version(s) where the bug happened

8.0.0 beta 1

### PHP version(s) where the bug happened

8.1

**Comment by AureRita** [comment]
Hi @roja45 

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template and provide clear and concise steps to reproduce the bug**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.
Can you create an issue to allow the QA team to follow all the steps to test your pr, without this, the QA team can't test your PR

Thank you

**Comment by roja45** [comment]
You just need to read the code, you return false when the minimal quantity is 1, and the last time I looked 1 was a valid number.

**Comment by AureRita** [comment]
If I follow strictly what you wrote in the steps to reproduce, I'll look at the code and that's all. If I don't know how to read code, how can I reproduce the issue ?
