### ISSUE TITLE
Using autoupgrade with direct upgrade is not working

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#29303]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Following this documentation, we could upgrade a shop as it, without checking the module autoupgrade inside the Back Office : https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/

If you try this, you will have a white screen and somes errors on the direct call of the upgrade.php script.

### Expected behavior

Working script.

### Steps to reproduce

See description.

### PrestaShop version(s) where the bug happened

8.0.x as the upgrade is no more part of the core and 1.7.x using the documentation related to the autoupgrade module in its latest version.

### PHP version(s) where the bug happened

All versions.

### If your bug is related to a module, specify its name and its version

autoupgrade

**Comment by PrestaEdit** [comment]
> PHP Warning:  require_once(/modules/autoupgrade/upgrade/../../vendor/autoload.php): failed to open stream: No such file or directory in /modules/autoupgrade/upgrade/upgrade.php on line 48
> PHP Stack trace:
> PHP   1. {main}() /modules/autoupgrade/upgrade/upgrade.php:0
> PHP Fatal error:  require_once(): Failed opening required '/modules/autoupgrade/upgrade/../../vendor/autoload.php' (include_path='.:/usr/share/php') in /modules/autoupgrade/upgrade/upgrade.php on line 48
> PHP Stack trace:
> PHP   1. {main}() /modules/autoupgrade/upgrade/upgrade.php:0

---

> Fatal error: Uncaught Error: Class 'PrestaShopBundle\Install\Upgrade' not found in /modules/autoupgrade/upgrade/upgrade.php on line 51

**Comment by PrestaEdit** [comment]
The class is missing since this Pull Request : https://github.com/PrestaShop/PrestaShop/pull/25794

**Comment by AureRita** [comment]
Hi @PrestaEdit , 

Thank you for your reporting issue. Unfortunately, If I follow strictly what you wrote in the steps to reproduce, I'll see your description and that's all. I didn't see white screen, or any error that it can be reported. Thank to let us some steps to reproduce. 

Waiting for your feedback

**Comment by PrestaEdit** [comment]
Do you have try on the 8 version, too ?
What do you see ?

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

Closing the issue as it doesn't contain any information that could help us to reproduce the issue.
Please open a new issue if you can provide all infos :pray: 

Thanks!

**Comment by PrestaEdit** [comment]
???!

**Comment by MatShir** [comment]
Maybe we can have @PrestaShop/prestashop-maintainers a second opinion about this bug

**Comment by PrestaEdit** [comment]
I've added the affected version, if it could help too.

**Comment by hibatallahAouadni** [comment]
@PrestaEdit could you please provide your autoupgrade module version :pray:

**Comment by PrestaEdit** [comment]
It's the 4.14.

**Comment by ckubitza** [comment]
I have the same problem, the manual upgrade as described in the current official documentation is not working (trying to update from 1.7.8.7 to 8.0.0-beta.1 with latest autoupgrade module from github):
https://devdocs.prestashop-project.org/1.7/basics/keeping-up-to-date/upgrade/ (showing even the old path to upgrade.php)
https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/upgrade/

The upgrade script was moved from the installer to the autoupgrade module but without needed modifications.

For example, this require path is now wrong: https://github.com/PrestaShop/autoupgrade/blob/d01a8242567294efd421a651cdb264b657f443c7/upgrade/upgrade.php#L47
Output when running `php modules/autoupgrade/upgrade/upgrade.php` with PHP 7.4 (stripped some paths):

```
PHP Warning:  require_once([...]\modules\autoupgrade\upgrade/../../vendor/autoload.php): failed to open stream: No such file or directory in [...]\modules\autoupgrade\upgrade\upgrade.php on line 47

Warning: require_once([...]\modules\autoupgrade\upgrade/../../vendor/autoload.php): failed to open stream: No such file or directory in [...]\autoupgrade\upgrade\upgrade.php on line 47
PHP Fatal error:  require_once(): Failed opening required '[...]\modules\autoupgrade\upgrade/../../vendor/autoload.php' (include_path='[...]\php\PEAR') in [...]\modules\autoupgrade\upgrade\upgrade.php on line 47

Fatal error: require_once(): Failed opening required '[...]\modules\autoupgrade\upgrade/../../vendor/autoload.php' (include_path='[...]\PEAR') in [...]\modules\autoupgrade\upgrade\upgrade.php on line 47
```

Some related commits (again):
https://github.com/PrestaShop/PrestaShop/commit/11195b88414330fe0ddbaec771a1318a06227147
https://github.com/PrestaShop/autoupgrade/commit/d309e2dcd02d68ee1f2ca7ca0e8a364b1cdae492
https://github.com/PrestaShop/docs/commit/163701f40f0c7b9e959050de3d612b1158d631a2

**Comment by tswfi** [comment]
Also tripped on this today.
1) 8.0 zip package does not contain autoupgrade module => so the docs point to a file that does not exist as it was moved into autoupgrade module
2) autoupgrade module paths are wrong

I did a quick test to fix the paths but didn't get them all and had to return to backup and didn't have time to retest today.

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

Do you still encounter the issue with PS8.1.1?
Please check and feedback.

Thanks!

**Comment by florine2623** [comment]
Hello,

Since we had no news from you for more than 30 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
