### ISSUE TITLE
Amount value is not displayed on payment block

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#29310]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After the merge of this [PR](https://github.com/PrestaShop/PrestaShop/pull/29180) the Amount value is not displayed on View order page > payment table
Before the merge =>  https://watch.screencastify.com/v/rNFjvPK8ZnoPHFyvsdax
After the merge => https://watch.screencastify.com/v/2q8D0nG2quV1UA5YsQWo
![Capture d’écran de 2022-08-11 15-33-58](https://user-images.githubusercontent.com/24647495/184146743-f1b92ca2-f05f-4566-8dfc-8a1c5ecc09a7.png)

### Expected behavior

When we click on 'Enter payment button' the amount value should be displayed on the first line of payment table
![Capture d’écran de 2022-08-11 15-34-12](https://user-images.githubusercontent.com/24647495/184146900-8b24fbee-e71b-4722-bac9-33b9c54b7da4.png)

### Steps to reproduce

1- Go to  orders > view order page
2- Go to documents tab
3- Click on create invoice
4- Click on enter payment
5- See the error
=> Amount value is not displayed on payment block also the ID of the input is deleted

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.3

**Comment by MatShir** [comment]
It will be done in priority since it breaks the test auto

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29324
