### ISSUE TITLE
Error upload module PrestaShop 8.0.0 Beta 1

### ISSUE THREAD

**Issue by clearisesp** [PrestaShop/PrestaShop#29317]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After installing the recently notified beta version prestashop 8.0, selecting the installation with the modules already pre-installed, I am about to test modules and I realize that visually with the interface no module can be uploaded.
Tested on chrome for mac version 104.0.5112.79 (Official build) (x86_64)

![Captura de pantalla 2022-08-12 a las 7 57 06](https://user-images.githubusercontent.com/91121803/184294389-64a47181-30a8-444a-bf8f-e0c17bfdad06.png)

### Expected behavior

It should allow to select file or upload directly in window. Neither one nor the other.

### Steps to reproduce

1. Install Prestashop beta1 8.0 with modules preinstall.
2. Access the Backmenu / modules menu and try to upload one.

### PrestaShop version(s) where the bug happened

PrestaShop 8.0.0 Beta 1

### PHP version(s) where the bug happened

8.0.22

**Comment by clearisesp** [comment]
Possible Fix,
src/PrestaShopBundle/Resources/views/Admin/Module/common.html.twig
![Captura de pantalla 2022-08-12 a las 8 27 48](https://user-images.githubusercontent.com/91121803/184297564-dde83bf7-69d2-4334-b084-d9fca7fd7bdb.png)


'moduleModalUpdateConfirmMessage': '{{ "We strongly advise you to upgrade the modules on maintenance mode to avoid any cache issues."|trans({}, 'Admin.Modules.Notification') }}'

Error in translate spanish, line break occurs in the translation and makes the single quote stick out.

Solved this, everything works ok.

**Comment by hibatallahAouadni** [comment]
Hello @clearisesp 

> Solved this, everything works ok.

Glad to hear :tada: and thanks for your feedback.
Well in my case, I didn't manage to reprduce the issue as you can see in the attached screen record below:

https://user-images.githubusercontent.com/23308427/184345806-6a0838f3-32ce-4877-88da-332fa52e2128.mp4

Closing the issue as it seems solved for you :wink: 

Thanks!

**Comment by clearisesp** [comment]
So that you can reproduce the error, you would have to put the backoffice in Spanish and as you can see in the js capture that I have indicated, when doing the translate that you have by default in that section, it gives an error, that is to say that for the version in Spanish will fail.
