### ISSUE TITLE
[WS] php error while calling product_option_values ws

### ISSUE THREAD

**Issue by Max84** [PrestaShop/PrestaShop#29313]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

A GET request onto some webservice method return a php error.
It is a Prestashop 8.0.0 regression, no problem with Prestashop 1.7.*

### Expected behavior

We must have a vlide XML output.

### Steps to reproduce

1. Enable webservice
2. Enbale Prestashop debug mode in order to see php error easily
3. Try to call this utl with your browser : your_url/api/product_option_values
4. You'll get this php error:

```
Fatal error: Uncaught Error: Call to undefined method Attribute::getWebserviceParameters() in /var/www/prestashop/classes/webservice/WebserviceRequest.php:564
Stack trace:
#0 /var/www/prestashop/webservice/dispatcher.php(90): WebserviceRequestCore->fetch('H2S2VE2V3UB3W2R...', 'GET', 'product_option_...', Array, false, NULL)
#1 {main}
  thrown in /var/www/prestashop/classes/webservice/WebserviceRequest.php on line 564
```

### PrestaShop version(s) where the bug happened

8.0.0 beta1

### PHP version(s) where the bug happened

7.2.34

**Comment by PrestaEdit** [comment]
Just tested and I validate this issue.

**Comment by hibatallahAouadni** [comment]
Hello @Max84 

I reproduce the issue only with PS8.0.0, it's a regression!

With PS1.7.8.6 :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/23308427/184364486-27fcb1a1-7cb2-4f39-8f5e-2b2f9afdc97c.png)

With PS8.0.0 :x: 

![image](https://user-images.githubusercontent.com/23308427/184364516-d37c17c0-a477-426d-a8a2-40e634e386be.png)

I'll add the Patch backlog to be fixed!
Thanks @PrestaEdit for your PR :rocket: 

Thanks!
