### ISSUE TITLE
Loading '_PS_CACHE_DIR_' from DB configuration instead from constant

### ISSUE THREAD

**Issue by artemevsin** [PrestaShop/PrestaShop#29328]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On several places in PrestaShop I've found, that `_PS_CACHE_DIR_` is loaded from database and not from PHP constant. But in configuration table in database there is no such record with the name `_PS_CACHE_DIR_`. So I assume that this is a typo.

https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Addon/Module/ModuleManagerBuilder.php#L162
https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Addon/Theme/Theme.php#L54
https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Addon/Theme/ThemeExporter.php#L74
https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Addon/Theme/ThemeManager.php#L511

### Expected behavior

The value of `_PS_CACHE_DIR_` is loaded from PHP constant and not from database

### Steps to reproduce

1. Install fresh PrestaShop
2. Check that in ps_configuration table there is no row with the name `_PS_CACHE_DIR_`
3. Check that in some places in code there is attempt to load this row from database - https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Addon/Module/ModuleManagerBuilder.php#L162

### PrestaShop version(s) where the bug happened

1.7.*

### PHP version(s) where the bug happened

all

**Comment by PrestaEdit** [comment]
When using the configuration adaptater like it's done inside the given examples, if the given name to `get()` method exist as a constant, it will be this value that it's loaded. Even it's exists inside the configurations table.

It's not a typo, neither an issue.

**Comment by hibatallahAouadni** [comment]
Hello @artemevsin 

Closing the issue as it's not valid (as @PrestaEdit mentioned above)!
We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

PS: thanks @PrestaEdit for your quick reply!

Thank you

**Comment by artemevsin** [comment]
Sorry, my bad, didn't check it has been fixed in 8.0.0
https://github.com/PrestaShop/PrestaShop/pull/28267/files

Thanks for your time
