### ISSUE TITLE
Suggestion : Move the PS_TOKEN_ENABLE setting into the security tab

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#29321]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Inside PrestaShop, there is the `PS_TOKEN_ENABLE` option.

The form to update it is located into the **Preferences** tab.
Now that we have a **security** (with the Back Office token option inside it), we could move this into this one maybe.

The related option is "_Increase front office security_".

### Describe the solution you'd like

Move the setting to security page.

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. 
So, we're waiting for your PR :rocket: 

Thank you
