### ISSUE TITLE
BO - Product V2 - The green alert after updating a combination is not well displayed

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#29329]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Reported previously here: https://github.com/PrestaShop/PrestaShop/pull/28482#pullrequestreview-974372319

In the BO > Catalog > Products with combinations > After updating a combination, the green alert is not well displayed
![image](https://user-images.githubusercontent.com/16067358/184602108-802e0db0-9609-47d3-a884-0803bba2921a.png)

Before merging the PR: https://github.com/PrestaShop/PrestaShop/pull/28482
![image](https://user-images.githubusercontent.com/16067358/184602233-002e0ca9-58b9-4f60-a39f-4605c2d33e5e.png)

### Expected behavior

The alert should be on the top of the Modal

### Steps to reproduce

1. Go to BO > Advanced Parameters > New and Experimental Features & Enable `New product page - Single store`
2. Go to BO > Catalog > Product V2
3. Create a product with combinations
4. Generate a combination & edit it
5. Save
6. See error : the alert Update successful is not well displayed

![image](https://user-images.githubusercontent.com/16067358/184602736-a7bb4f55-90e2-4d43-88a0-6ab08d233fc0.png)

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1

**Comment by ElodieOS** [comment]
Hi @khouloudbelguith , I’m taking the issu. Can I have more details about it please ? When I follow steps to reproduce the bug, I don’t find the same interface nor result. Maybe it has been modified since ?
![github-issu](https://user-images.githubusercontent.com/113457393/191913567-8ad7672f-4e80-4926-bb39-fce2ce58c914.png)

**Comment by NeOMakinG** [comment]
@ElodieOS You did test it using the product page v1

You have to activate the product page v2 inside the `Advanced Parameters > New and Experimental Features` and then go to a product page, test on a combination, you'll see the issue

**Comment by khouloudbelguith** [comment]
Hi @ElodieOS, @NeOMakinG,

I updated the description of the issue.

Thank you all!

**Comment by ElodieOS** [comment]
Hi everyone! This is my proposition for the green alert. 
I think it's in a good place here, we just need to add the same padding as the rest of the content. I saw that not all elements respect the same padding (as you can see in the screenshot), so it would be nice to respect the same padding for all elements (form, button etc).
<img width="745" alt="Green alert" src="https://user-images.githubusercontent.com/113457393/194822527-62104efc-cfc3-4687-a744-dfa8ab7b32c8.png">
