### ISSUE TITLE
Duplicated join in Hook.php leads to inefficient query

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#29339]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Quite a slow query is in `classes/Hook.php:1202` 

![Immagine 2022-08-15 154249](https://user-images.githubusercontent.com/7520695/184646838-18b7779b-063b-4620-b6e3-3dd7b2f1a5ef.png)

In the following query, `ps_module_shop` is joined twice, but only one join is needed.
``` 
SELECT SQL_NO_CACHE h.`name` as hook, m.`id_module`, h.`id_hook`, m.`name` as module
FROM `ps_module` m
INNER JOIN ps_module_shop module_shop
ON (module_shop.id_module = m.id_module AND module_shop.id_shop = 2 AND module_shop.enable_device & 1)
INNER JOIN `ps_module_shop` `ms` ON ms.`id_module` = m.`id_module`
INNER JOIN `ps_hook_module` `hm` ON hm.`id_module` = m.`id_module`
INNER JOIN `ps_hook` `h` ON hm.`id_hook` = h.`id_hook`
LEFT JOIN `ps_module_group` `mg` ON mg.`id_module` = m.`id_module`
WHERE (h.`name` != "paymentOptions") AND (hm.`id_shop` = 2) AND (mg.id_shop = 2 AND  mg.`id_group` IN (3))
GROUP BY hm.id_hook, hm.id_module
ORDER BY hm.`position`
```

### Expected behavior

I expect queries to be optimized. 

Removing the extraneous join, the query is faster (half the time, only 2 ms, that is not much, but it is a tiny improvement).
![Immagine 2022-08-15 155107](https://user-images.githubusercontent.com/7520695/184648092-8cd9baef-01b5-4c8b-97e0-51df70910c57.png)

### Steps to reproduce

1. Enable Debug profiler
2. Look for the query above on any page of the FO
3. Notice, that the table `ps_module_shop` is joined twice, and
    a. the extraneous (second) join is less restrictive than the first, but rows joined by the second query are a strict superset of those joined by the first query
    b. the alias `ms` is never used, neither in selected field, nor in conditions, nor elsewhere

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Isn't the same as yours #26747?? If not, could you please clearer steps to reproduce or a screen record :pray: 
Waiting for your feedback.

Thanks!

**Comment by lmeyer1** [comment]
@hibatallahAouadni 
No it isn't the same.

The matter is this query
```
SELECT SQL_NO_CACHE h.`name` as hook, m.`id_module`, h.`id_hook`, m.`name` as module
FROM `ps_module` m
INNER JOIN ps_module_shop module_shop
ON (module_shop.id_module = m.id_module AND module_shop.id_shop = 2 AND module_shop.enable_device & 1)
**doubled join, useless but uses resources** INNER JOIN `ps_module_shop` `ms` ON ms.`id_module` = m.`id_module`
INNER JOIN `ps_hook_module` `hm` ON hm.`id_module` = m.`id_module`
INNER JOIN `ps_hook` `h` ON hm.`id_hook` = h.`id_hook`
LEFT JOIN `ps_module_group` `mg` ON mg.`id_module` = m.`id_module`
WHERE (h.`name` != "paymentOptions") AND (hm.`id_shop` = 2) AND (mg.id_shop = 2 AND  mg.`id_group` IN (3))
GROUP BY hm.id_hook, hm.id_module
ORDER BY hm.`position`
```
The marked join is useless, it is a duplicated join on `ps_module_shop`. The extraneous  join `INNER JOIN ps_module_shop ms ON ms.id_module = m.id_module` is similar to `INNER JOIN ps_module_shop module_shop ON (module_shop.id_module = m.id_module AND module_shop.id_shop = 2 AND module_shop.enable_device & 1)`.
The first is more restrictive, but since the two are inner joins, they won't change the result, but the number of lines to examine is larger. I'm not able to quantify the impact. Also I ignore how mysql handles these types of redundancies internally, does it remove the useless join prior to execution or does it execute the join fully? Maybe something in between.

For the steps to reproduce:
*Remove the extraneous join* is probably not feasible, because it requires the modification in #29340. I hope that the updated version is better, though it requires familiarity with sql queries and joins in particular.

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Thanks for all details :pray: 
Ping @PrestaShop/prestashop-maintainers can someone please reproduce the issue and validated :pray: 

Thanks in advance!

**Comment by hibatallahAouadni** [comment]
Friendly reminder @PrestaShop/theme-maintainers can someone please reproduce the issue, cause the PR is blocked :pray:

**Comment by lmeyer1** [comment]
@hibatallahAouadni What is not reproducible ?
Don't you find this query with Debug profiler enabled? 
```
SELECT SQL_NO_CACHE h.`name` as hook, m.`id_module`, h.`id_hook`, m.`name` as module
FROM `ps_module` m
INNER JOIN ps_module_shop module_shop
ON (module_shop.id_module = m.id_module AND module_shop.id_shop = 2 AND module_shop.enable_device & 1)
INNER JOIN `ps_module_shop` `ms` ON ms.`id_module` = m.`id_module`
INNER JOIN `ps_hook_module` `hm` ON hm.`id_module` = m.`id_module`
INNER JOIN `ps_hook` `h` ON hm.`id_hook` = h.`id_hook`
LEFT JOIN `ps_module_group` `mg` ON mg.`id_module` = m.`id_module`
WHERE (h.`name` != "paymentOptions") AND (hm.`id_shop` = 2) AND (mg.id_shop = 2 AND  mg.`id_group` IN (3))
GROUP BY hm.id_hook, hm.id_module
ORDER BY hm.`position`
```
Don't you notice these things in the query when observing it ?
- there are two inner joins on `ps_module_shop`
- the join `ps_module_shop module_shop` is more restrictive than `ps_module_shop ms` and selects a strict subset of records
- the alias `ms` of the less restrictive join is never used elsewhere in the query

These three observations allow to conclude, that the less restrictive join is superfluous.

**Comment by lmeyer1** [comment]
I edited the steps to reproduce to clarify. This must be reproducible. The query must up show as it stands above.
If you are not sure if the duplicated join is really a duplicate, ask someone that speaks fluently SQL.

**Comment by matks** [comment]
Thank you @lmeyer1 

If needed maybe we can all discuss on the Slack open source channel to see how we could get this confirmed and validated, all together in a video-meeting online? 😊 

@kpodemski you might want to get involved 😝

**Comment by eternoendless** [comment]
I was able to reproduce the bug on the 8.0.x branch. Just enable the profiler and go to the home page:

<img width="1674" alt="Screenshot 2022-09-22 at 17 23 26" src="https://user-images.githubusercontent.com/1009343/191788153-1fd26fee-ff1e-40f1-8171-67d0179dc7a4.png">
