### ISSUE TITLE
BO - An exception is thrown when edit a combination with a product with specific prices when a new shop for a new group of shop is the context BO shop with product V2

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#29334]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An exception is thrown when edit a combination with a product with specific prices when a new shop for a new group of shop is the context BO shop with product V2

This issue is reported in this [comment](https://github.com/PrestaShop/PrestaShop/pull/28390#pullrequestreview-978938837) (Issue 26)

**8.0.x : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/184622890-9fcefe63-858c-4a81-b5a5-64fed5c94734.png)

https://user-images.githubusercontent.com/92912932/184623713-460d7bbc-f523-402d-bdc7-2e296af0d7a5.mp4

1778 : When change the context shop, the product type is not updated with Product V1 :OK :heavy_check_mark: 

https://user-images.githubusercontent.com/92912932/184623317-8d5ba727-bc0c-4cb7-b4e1-0193dbe5d55c.mp4

### Steps to reproduce

1. Enable multistore
2. Create a new group of shop
3. Create a new shop for this group of shop
4. Edit a product which contains specific prices already created
5. Change the product type in combinations
6. Select the new shop created in product page
7. Edit any combination
8. See error > An exception is thrown

### PrestaShop version(s) where the bug happened

8.0.x, develop

### PHP version(s) where the bug happened

7.3

**Comment by MatShir** [comment]
Seems to be fixed :)

**Comment by florine2623** [comment]
Tested on branch `8.0.x`, `8.1.x` and `develop`, I couldn't reproduce the issue.

So I will close it ^^
