### ISSUE TITLE
BO - A 500 error is thrown when edit the quantity of combinations with the new group of shops with product V2

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#29335]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Error 500 when edit the quantity of combinations and click to save the list with a product with specific prices when a new shop for a new group of shop is selected

This issue is reported in this [comment](https://github.com/PrestaShop/PrestaShop/pull/28390#pullrequestreview-978938837) (Issue 27)

**8.0.x : NOK** :x: 

https://user-images.githubusercontent.com/92912932/184624454-ebda6ab7-e94b-4eb5-89f1-d98f293b0845.mp4

1778 : When change the context shop, the product type is not updated with Product V1 :OK :heavy_check_mark: 

https://user-images.githubusercontent.com/92912932/184623317-8d5ba727-bc0c-4cb7-b4e1-0193dbe5d55c.mp4

### Steps to reproduce

1. Enable multistore
2. Create a new group of shop
3. Create a new shop for this group of shop
4. Edit a product which contains specific prices already created
5. Change the product type in combinations
6. Select the new shop created in product page
7. Edit the quantity of any combination
8. Click to edit and then click on Save list
9. See error > An exception 500 error

### PrestaShop version(s) where the bug happened

8.0.x, develop

### PHP version(s) where the bug happened

7.3

**Comment by MatShir** [comment]
Seems to be fixed :)

**Comment by florine2623** [comment]
Tested on branch `8.0.x`, following the steps, the page loads forever : :x: 
<img width="1425" alt="Screenshot 2023-03-09 at 17 49 24" src="https://user-images.githubusercontent.com/16019289/224095821-615e873f-642c-4e78-8f2e-d06cb48c39ee.png">

I have also found a weird bug that I've never seen before while testing this issue :
<img width="1433" alt="Screenshot 2023-03-10 at 14 50 12" src="https://user-images.githubusercontent.com/16019289/224333088-05d953a2-d62c-42a6-8512-6b1bdf2c4b2a.png">

https://user-images.githubusercontent.com/16019289/224333182-6fd23360-2d5d-40c5-8e6f-781a3333a8a9.mov

I got a hint of a bug reported previously, the might be related to this : https://github.com/PrestaShop/PrestaShop/issues/29334

This is only displayed for a fraction of a second.
<img width="1395" alt="Screenshot 2023-03-10 at 14 52 17" src="https://user-images.githubusercontent.com/16019289/224333684-6e0c2239-5b8d-4275-bc3c-a2dae85f6132.png">

**Comment by MatShir** [comment]
And on `8.1.x`? On 8.0.x the page is still experimental

**Comment by florine2623** [comment]
Tested again on 8.1.x, I can't reproduce the issue.
So it is fixed and I will close it ^^
