### ISSUE TITLE
FO - Discounts - The discount detail is NOK when we the product selected has an ecotax

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#29331]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Previously reported here: https://github.com/PrestaShop/PrestaShop/pull/28482#pullrequestreview-974372319
In the FO > Shopping cart page and checkout page, when we apply a cart rule "percent discount on a selected product that has an ecotax, the discount line s NOK.

Reproduced with PS1787 and 8.0.x

It is ok with PS1770

### Expected behavior

Display 6 Euro in the discount details in the step to reproduce. 

### Steps to reproduce

1. Go to BO > International > Taxes & Enable Ecotax & tax ecotax = 20%
2. Create a product with ecotax, in my case   
![image](https://user-images.githubusercontent.com/16067358/168655282-215517db-c3c3-498d-8e96-ebcafa541b32.png)
3. Go to BO > Catalog > Cart rules page and create a cart rule:
3.1 Product Selection: select the ecotax product 
![image](https://user-images.githubusercontent.com/16067358/168655072-1c7456a1-f9e8-4a0b-9eda-d3e091c2f867.png)
3.2 a percent discount, in my case 50% & Apply a discount to Selected Products 
![image](https://user-images.githubusercontent.com/16067358/168655104-c956f6d1-ed8d-44b0-b0c8-075cd9c4c03c.png)
4. Go to FO > Add the last product created to the cart
5. Apply the discount
6. See error: the discount line = 5.80 => NOK, it should be 6
![image](https://user-images.githubusercontent.com/16067358/168655420-28c90d29-0979-40b1-80f5-667f8407f94e.png)

### PrestaShop version(s) where the bug happened

1.7.8.7, 8.0.x

### PHP version(s) where the bug happened

7.2, 8.1

**Comment by jolelievre** [comment]
Closed by https://github.com/PrestaShop/PrestaShop/pull/29715
