### ISSUE TITLE
BO - The assign to a new zone item is missing in the bulk actions with the States' migrated page 

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#29345]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The `assign to a new zone` item is missing in the bulk actions with the States' migrated page 

Migrated page 
![image](https://user-images.githubusercontent.com/92912932/184666774-f429b46a-5747-4965-b040-f43164611516.png)

Non migrated page 
![image](https://user-images.githubusercontent.com/92912932/184666868-f12cdb5b-69a2-4f74-a9bb-61d1bc6577a0.png)

### Steps to reproduce

1. Use this URL `/admin-dev/index.php/improve/international/states/` to go to Sates's migrated page 
2. Check the bulk actions items
3. See error > The `Assign to a new zone `is not listed in the list

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

**Comment by Progi1984** [comment]
But this menu didn't work since 1.7.0.0 version (at least). I think we can remove this feature from the menu. 

What do you think @PrestaShop/product-team ?

**Comment by Progi1984** [comment]
@PrestaShop/qa-functional I just tested on a 1.7.0.6 version. And the menu didn't work.

**Comment by hibatallahAouadni** [comment]
Hello @Progi1984 

> https://github.com/orgs/PrestaShop/teams/qa-functional I just tested on a 1.7.0.6 version. And the menu didn't work.

I think you're talking about this #9971 :wink: 

Thanks!

**Comment by MatShir** [comment]
Then it is a duplicate ? @hibatallahAouadni

**Comment by hibatallahAouadni** [comment]
Hello @MatShir 

No this is not a duplicate.
Well let me explain, from 1.7.0.0 this option doesn't work! As you can in the issue #9971 😉 
Then, we encounter a regression on the migrated page where we notice that the option is not displayed at all 😕 

So, what we should do? Should we fix the old issue and then this regression or close both as not planned? 

Thanks!

**Comment by MatShir** [comment]
Let's flag it as a duplicate, and note in the first issue that the button was removed in the migration process since it was not working

**Comment by hibatallahAouadni** [comment]
Duplicate of #9971
