### ISSUE TITLE
BO - Product V2 with combinations - The impact on price is not automatically calculated in the bulk edit modal

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#29341]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Previously reported here: https://github.com/PrestaShop/PrestaShop/pull/28482#pullrequestreview-986520326
 The impact on price is not automatically calculated in the bulk edit modal 
![image](https://user-images.githubusercontent.com/16067358/184649991-39678e7b-9339-4b6c-8963-2c5ee85dd6df.png)

### Expected behavior
 
 The impact on price tax excl and impact on price tax incl is automatically calculated in the bulk edit modal when on field is edited.

### Steps to reproduce

1. Go to BO > Catalog > Product V2
2. Create a product with combinations > In the combinations list > select all combinations & edit with bulk action
3. Click on Price
4. Set the impact on price tax excluded
5. See error: the impact on price tax included is not automatically changed
![image](https://user-images.githubusercontent.com/16067358/184651225-3461e830-315e-4503-8222-a184dc517830.png)

Same issue if we edit the `the impact on price tax included`, `the impact on price tax excluded` is not automatically calculated
![image](https://user-images.githubusercontent.com/16067358/184651208-537b4915-e744-4699-b68c-9872cc695694.png)

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29846
