### ISSUE TITLE
BO - The quantity of stock is not updated when editing a product with combinations using a new shop

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#29349]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

 The quantity of stock is not updated when editing a product with combinations using a new shop

**8.0.x :  NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/184679442-b764818c-9c83-4f14-b3ad-6c16bbf9ac4d.png)

https://user-images.githubusercontent.com/92912932/184679493-68bade6d-2c48-45b4-914c-1f54c8f78b13.mp4

### Steps to reproduce

1. Go to BO > Catalog > Products V2
2. Create a product with Combinations, generate combinations for this product and with quantity <> 0
3. Enable multistore and create a new shop
4. Edit the created product with the new shop
5. Edit quantities for every combinations and Save
6. See error >> The total of stock is NOK

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.3

**Comment by zuk3975** [comment]
does it work on default shop? It seems to me it doesn't work at all (and actually quantity update doesn't work in list at all when in custom shop in 8.1.x, but thats an easy fix)
