### ISSUE TITLE
Simplify Average code in module productcomments

### ISSUE THREAD

**Issue by leemyongpakvn** [PrestaShop/PrestaShop#29357]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Average of Grade is calculated by `SUM(pc.`grade`) / COUNT(pc.`grade`)` at [ProductComment.php#L181](https://github.com/PrestaShop/productcomments/blob/dev/ProductComment.php#L181), [ProductComment.php#L197](https://github.com/PrestaShop/productcomments/blob/dev/ProductComment.php#L197), and [src/Repository/ProductCommentRepository.php#L156](https://github.com/PrestaShop/productcomments/blob/dev/src/Repository/ProductCommentRepository.php#L156).

### Describe the solution you'd like

We can simplify the code by using `AVG(pc.grade)` instead, as it is the same result and shorter

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by ghost** [comment]
Issue for dev @hibatallahAouadni ?

**Comment by hibatallahAouadni** [comment]
Hello @leemyongpakvn 

Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. 
Thanks for your PR :rocket: 

Thank you

**Comment by matks** [comment]
Thank you @leemyongpakvn this is a valid refactoring idea
