### ISSUE TITLE
Cannot modify translations of an installed module

### ISSUE THREAD

**Issue by sowbiba** [PrestaShop/PrestaShop#29359]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![Capture d’écran de 2022-08-16 14-10-08](https://user-images.githubusercontent.com/7426640/184901626-b52d8c56-2487-4f8a-afed-5337ef0f52b0.png)

### Steps to reproduce

Go to BO > International > Translations

In "Modify translations" block, select "Installed module", a module and a language

Click on "Modify"

You'll have an error saying "An error has occurred, this module does not exist: MODULE_NAME"

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.0

**Comment by sowbiba** [comment]
Already fixed by https://github.com/PrestaShop/PrestaShop/pull/29020

**Comment by hibatallahAouadni** [comment]
Duplicate of #28961
