### ISSUE TITLE
BO - Supplier block is not displayed in the edit combination page after importing them with csv file

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#29350]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

previously reported here: https://github.com/PrestaShop/PrestaShop/pull/27353#pullrequestreview-963560433
Supplier block is not displayed on the edit combination page after importing them with csv file

This is new behavior in the 8.0.x, In the Product V1: the supplier block is well updated after importing the combinations

### Steps to reproduce

1. Create a standard simple product
2. In the options tab > Choose a supplier and save
3. Go to BO > Advanced Parameters > Import page
4. Import combinations
I used this example
```php
Product ID*;Product_Reference;Attribute (Name:Type:Position)*;Value (Value:Position)*
48;reference1;Color:color:0;Blue:0
48;reference2;Color:color:0;Yellow:1
```
5. Go BO > Products page
6. Edit the last product & edit the combination
7. See error > no supplier displayed

I attached a screen record

https://user-images.githubusercontent.com/16067358/166956408-877417a3-68c1-4f08-b836-0bd1e78894e3.mp4

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29406
