### ISSUE TITLE
Webservice error with put stock_available in version 1.7.8.6 and 1.7.8.7

### ISSUE THREAD

**Issue by serpeal79** [PrestaShop/PrestaShop#29355]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

We have a PrestaShop connector to modify stocks using webservices and it works fine with many different PrestaShop websites and versions, but now we have to change stocks in a 1.7.8.6 version and the put opperation always returns status_code 500 and text: 
XML error : String could not be parsed as XML
XML length : 0

### Expected behavior

When sending a put to change stock_available, reply should have status_code 200 and the reply should be an XML with the content of the updated stock_available. 

### Steps to reproduce

Here there is a python script to reproduce the problem (change ws_key and url). I just get one random stock_available and put the same content: 

#!/usr/bin/python

import requests,re,sys

params={
    "ws_key":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "display":"full"
}
url="https://yoururl/api/"

#-----------------------------------------------------------------------------------
def main():

    # Get one stock_available
    jsonheaders={'content-type': 'application/json', "charset":"utf-8"}
    r=requests.get(f"{url}stock_availables?limit=1", headers=jsonheaders, params=params)
    
    # Extract the id number from the reply (r.text)
    id=re.sub("^CDATA\[","",re.search("CDATA\[[^\]]*",re.search("<id>.*</id>",r.text).group()).group())

    # Remove tags for stock_availables
    data=re.sub("</stock_availables>\n","",re.sub("<stock_availables>\n","",r.text))

    # Put without changes
    xmlheaders = {'Content-Type': 'application/xml', "charset":"utf-8"}    
    r=requests.put(f"{url}stock_availables/{id}",data=data.encode("utf-8"), headers=xmlheaders,params=params)

    print(f"status_code {r.status_code} text {r.text}")

    sys.exit(0)

#-----------------------------------------------------------------------------------
if __name__=="__main__":
    main()    

### PrestaShop version(s) where the bug happened

1.7.8.6, 1.7.8.7

### PHP version(s) where the bug happened

7.3.33, 7.4.30

**Comment by hibatallahAouadni** [comment]
Hello @serpeal79 

Thanks for your issue!
Ping @PrestaShop/prestashop-core-developers can someone please reproduce the issue :pray: 
It's too technical :sweat: 

Thanks!

**Comment by serpeal79** [comment]
Hi. We have tested the latest update, 1.7.8.7 and the error persists. It seems that it has been inherited. Maybe you want to add the label 1.7.8.7 in the task as well. Kind regards

**Comment by serpeal79** [comment]
I've realized that the customer slightly modified the URL (domain), so our code was not pointing to the right URL. Sorry for the inconvenience.

**Comment by hibatallahAouadni** [comment]
@serpeal79 thanks for your feedback :pray:
