### ISSUE TITLE
Bad upgrade files in ps_checkpayment

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#29352]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Bad upgrade files in ps_checkpayment

### Steps to reproduce

See versions of files in upgrade folder https://github.com/PrestaShop/ps_checkpayment/tree/dev/upgrade 

They are bigger than the current version of the module

### PrestaShop version(s) where the bug happened

8.0

### PHP version(s) where the bug happened

8.0

### If your bug is related to a module, specify its name and its version

ps_checkpayment

**Comment by PrestaEdit** [comment]
Issue valid. ✅ 

As the ps_checkpayment module was renamed from cheque, the version was changed (to lower version) and so the upgrade are not good anymore.

**Comment by kpodemski** [comment]
I confirm the issue
