### ISSUE TITLE
Stripe problem with Prestashop checkout

### ISSUE THREAD

**Issue by imCarlosmt** [PrestaShop/PrestaShop#29351]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi, 

Can someone help me pls, 
I installed the module "Stripe" in my store: fabriciosmagicstore.com but when we try to make a payment we can't put the info of the card. We have been talking with the support of Stripe but they say that the problem is with Prestashop. HELP PLS!

### Steps to reproduce

![Captura de Pantalla 2022-08-15 a la(s) 13 29 46](https://user-images.githubusercontent.com/111308276/184696162-b64bef84-4ec6-4e8c-9b43-39192c93c3c0.png)

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4.30

### If your bug is related to a module, specify its name and its version

Stripe

**Comment by hibatallahAouadni** [comment]
Hello @imCarlosmt 


It seems that your issue is not a PrestaShop core bug.
If your module is Stipe Official, please contact support team on Addons or Theme developer

We will close this issue.

Thanks!
