### ISSUE TITLE
Improvement : allow to choose wich shop need to be impacted by the prestashop:theme:enable command

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#29368]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

While using the `prestashop:theme:enable` command, only the default  - shop with ID as 1 - shop is modified.

If you want to enable a theme for another shop, you can't.

### Expected behavior

Be able to force the shop ID.

### Steps to reproduce

1. Get a multistore installation
2. Add at least two shops
3. Modify the used theme on each shop.
3. Execute this command into your console : `php bin/console prestashop:theme:enable classic`

See that only the first (with ID = 1) shop have now the classic theme enabled.

### PrestaShop version(s) where the bug happened

8.0.0-beta.1

### PHP version(s) where the bug happened

8.0.21

**Comment by AureRita** [comment]
Hi @PrestaEdit  ,

Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments. 

We're waiting for your PR :rocket: 

Thank you

**Comment by matks** [comment]
Sounds like a good idea :)
