### ISSUE TITLE
Classname modifier doesn't change the _ char by -

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#29365]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

According to the documentation, the classname modifier need to change the _ into -.

https://devdocs.prestashop.com/8/development/components/smarty-extensions/#classname

Even if there is a mistake (the exta -v have nothing to do inside the ouput, a pull request is done to update the doc), the real ouput is not this as wanted.

`{assign var=attr value='Hérè-Is_a-Clàssnåme--@#$$ˆ*(&-----'}
{$attr|classname} `

Ouput: ` here-is_a-classname `

### Expected behavior

Ouput: ` here-is-a-classname `

### Steps to reproduce

1. Add this inside a template : 
`{assign var=attr value='Hérè-Is_a-Clàssnåme--@#$$ˆ*(&-----'}
{$attr|classname} `

1. Open the page related to the  template

### PrestaShop version(s) where the bug happened

8.0.0-beta.1

### PHP version(s) where the bug happened

8.0.21

**Comment by AureRita** [comment]
Hi @PrestaEdit  ,

I reproduce the issue with PrestaShop version 8.0.0 and not with the version 1.7.8.x . Nice catch ! It's a regression ! I'll add it to the patch backlog.

We can see this issue on this screenshot : 
![image](https://user-images.githubusercontent.com/100699445/185138894-a068f238-21aa-49a7-9ff8-b92d2da1f5ea.png)

We’re waiting for your PR 🚀


Thank you

**Comment by PrestaEdit** [comment]
> We’re waiting for your PR 🚀

Don't wait so much, it's already there 😎

**Comment by PrestaEdit** [comment]
As it's a wanted behavior into the 8.0.0, it's no more an issue.
