### ISSUE TITLE
BO - The status of the voucher is always disabled in the customer details page

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#29361]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This issue is previously reported here : #[28896](https://github.com/PrestaShop/PrestaShop/issues/28896)

The status of the voucher is always disabled in the customer details page

![image](https://user-images.githubusercontent.com/92912932/184919195-71156c96-5de5-4629-9bbe-61ae619c890c.png)

![image](https://user-images.githubusercontent.com/92912932/184919212-7af5989f-4825-406d-8d9f-7406f307f655.png)

https://user-images.githubusercontent.com/92912932/184919170-cc58a5c5-abe9-439e-9644-1295e5e2bbb2.mp4

### Steps to reproduce

1. BO > Catalog > Discounts > Create a new cart rule with enabled status
2. Go to catalog > Customers > View the attached customer
3. See error > The status is disabled in the Voucher section

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.3

**Comment by ghost** [comment]
Hello @HanaRebaiQA i think you are on the dev branch?

**Comment by HanaRebaiQA** [comment]
Hello @okom3pom 

It's the 8.0.x branch.

**Comment by zuk3975** [comment]
sorry @okom3pom I didn't see you were assigned and I made a pr with a fix, hopefully you haven't spent much time on it yet :smile:
