### ISSUE TITLE
BO - Mobile phone can't be erased

### ISSUE THREAD

**Issue by tom-combet** [PrestaShop/PrestaShop#29379]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Mobile phone for a customer address can't be erased by the merchant in back-office.

### Expected behavior

Merchant should be able to erase a mobile phone, like the phone field above.

### Steps to reproduce

1. Go to a customer address edition form
2. Empty the mobile phone field
3. Save
4. Go again to the customer address edition form

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.4

**Comment by AureRita** [comment]
Hi @tom-combet ,

I reproduce the issue with PrestaShop version 1.7.7.8, I'll add this to the backlog so it can be fixed.

We can see this issue in this video 

https://user-images.githubusercontent.com/100699445/185185504-26769f84-2307-4259-a3ca-85f6d6152d4e.mp4

Thank for your PR :rocket: 


Thanks
