### ISSUE TITLE
Unable to generate a credit slip if order not paid

### ISSUE THREAD

**Issue by arirangz** [PrestaShop/PrestaShop#29374]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When an order is not paid (bank transfer), we don't have the ability to generate a credit note if the status "awaiting for bank transfer" has the option checked "Allow a customer to download and view PDF versions of his/her invoices.".
As the invoice is generated, we should be able to generate a credit note to cancel the invoice for the accountant.

### Expected behavior

As the invoice is generated, we should be able to generate a credit note to cancel the invoice for the accountant.

### Steps to reproduce

1. Configure the shop to allow invoice for the status Awaiting for bank transfer (Allow a customer to download and view PDF versions of his/her invoices)
2. Order paying with bank transfer
3. Go to the order in the admin  (do NOT add any payment nor change status) and try to generate a credit note
4. The partial refund button is not available

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.3

**Comment by AureRita** [comment]
Hi @arirangz  ,

Despite my efforts, I'm not able to reproduce your issue with the provided information as you can see 


https://user-images.githubusercontent.com/100699445/185155176-a49092c8-323f-4173-9938-7d14d975331b.mp4

Did I miss something ? 

Waiting for your feedback

**Comment by arirangz** [comment]
Hello @AureRita ,

Thanks for you fast reply.

As I am saying in the description, I am explaining that the issue is when the order is NOT paid. In you example you are paying the order.

So let me be more specific :
- The shop has to be configured to allow the invoice when awaiting for bank transfer
- When checking an order awaiting for bank transfer (with invoice available) the refund button is not availabe
- We are not able to generate a credit slip

Thanks

**Comment by AureRita** [comment]
I tried with your information and that what I obtained : 

https://user-images.githubusercontent.com/100699445/185176295-b9d0f82c-82fc-4be7-9827-f1c66c3d2258.mp4

I check it also if I put an invoice by myself and I still have no issue as you can see : 

https://user-images.githubusercontent.com/100699445/185176431-89e4c287-8eb5-4efa-a003-a74dc0efcd32.mp4

Did I miss something ? 

Waiting for your feedback

**Comment by arirangz** [comment]
Hello,

Your test is not correct.

1. You have to go to Order settings, edit the status Awaiting for bank transfer and check to box to allow invoice 
2. Create an order
3. Go to the order in the backoffice but do NOT add any payment and do not change the status
4. Try to generate a credit slip

But do not add a payment, you have to leave the order as it is. Do not add any payment and do not change the order status.
Thanks

**Comment by hibatallahAouadni** [comment]
Hello @arirangz 

> You have to go to Order settings, edit the status Awaiting for bank transfer and check to box to allow invoice

![image](https://user-images.githubusercontent.com/23308427/185670818-be1e63ac-9fca-44f5-8c60-57b6505ae444.png)

do you mean to check this option? os something else?
Cause checking that option won't make `return products` nor `partial return` buttons will be displayed :disappointed: 
Waiting for your feedback.

Thanks!

**Comment by arirangz** [comment]
Hello,
You need to check "Consider the associated order as validated" then you can order with bankwire and the order will show the invoice.
Thanks

**Comment by AureRita** [comment]
Hi @arirangz 

I tried to reproduce your issue and I didn't have your issue, look at this video : 

https://user-images.githubusercontent.com/100699445/186453556-1bfac845-4613-4e56-b790-5c991e883599.mp4

can you tell me if I didn't do something ? 

Waiting for your feedback

**Comment by arirangz** [comment]
Hello,

Thanks for your feed back.

Actually, you have to check this box in the order status:
Allow a customer to download and view PDF versions of his/her invoices.

Sorry, I will update the bug description

**Comment by AureRita** [comment]
Hi @arirangz, 

Thank for your feedback, I retried to reproduce your issue and I didn't have it, as you can see : 

https://user-images.githubusercontent.com/100699445/188171657-633ae048-ec5a-45d5-9907-cf655abc8193.mp4

If you've some way to reproduce your issue that we miss, can you say it ? 

Waiting for your feedback

**Comment by arirangz** [comment]
Hi @AureRita ,

Thanks again for your test.

So I don't know why I don't have the partial refund with the status Awaiting for bank transfer.

I guess you can close this issue.

Thanks again

**Comment by AureRita** [comment]
Thank you too @arirangz for all the time you give us to improved prestashop, 

maybe [contacting a professional](https://www.prestashop-project.org/support/) will help you. 

Have a great day
