### ISSUE TITLE
Do not authorize PHP direct call on themes directory

### ISSUE THREAD

**Issue by clotairer** [PrestaShop/PrestaShop#29380]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

If you push a php file on the "themes" directory (or sub directory) file you can call it.
This directory should not have PHP script. It can be used by a hacker to hide a backdoor.

### Describe the solution you'd like

The .htaccess of the directory could be the same as https://github.com/PrestaShop/PrestaShop/blob/develop/img/.htaccess

with CSS and JS file authorized

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by AureRita** [comment]
Hi @clotairer ,

Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments. 

Thank for your PR :rocket: 

Thank you

**Comment by matks** [comment]
Thank you @clotairer for the input. I ask @atomiix who is our security lead to tell us his opinion on this topic 😉

**Comment by matks** [comment]
@atomiix approved this PR https://github.com/PrestaShop/PrestaShop/pull/29382 so I think this means he agrees 😄 

So let's confirm this developer feature

**Comment by clotairer** [comment]
FYI, we already deployed this patch on seveal eShop without issue. The exhasutive list of files type looks OK.

Who take the "risk" to add it in a millestone ?

**Comment by matks** [comment]
https://github.com/PrestaShop/PrestaShop/pull/29382 is likely to be merged inside `develop` -> milestone will be added when merge is done

Depending on security risk we could backport it to 8.0.0 -> to be defined by @atomiix
