### ISSUE TITLE
Cupón de descuento se puede usar igual si está vencido o deshabilitado

### ISSUE THREAD

**Issue by matydominguez** [PrestaShop/PrestaShop#29386]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hemos creado un **cupón de descuento** válido entre XX/XX/2022 y XY/XY/2022.
El cupón se usó más de 70 veces y terminó la fecha de posibilidad de uso.

_Sin embargo desde su finalización hace 2 meses:_

1) Los usuarios que habían ingresado el cupón y no lo terminaron de usar/pagar --> Pudieron usarlo una vez vencido
2) Se deshabilitó el cupón para que no esté más disponible --> Se pudo usar nuevamente
3) Ahora además de estar deshabilitado se cambió la opción a `disponibilidad por usuario` cantidad 0 --> Esperando resultados

Es un comportamiento muy malo me parece para el correcto uso del sistema.

Gracias

### Steps to reproduce

1) Los usuarios que habían ingresado el cupón y no lo terminaron de usar/pagar --> Pudieron usarlo una vez vencido
2) Se deshabilitó el cupón para que no esté más disponible --> Se pudo usar nuevamente
3) Ahora además de estar deshabilitado se cambió la opción a `disponibilidad por usuario` cantidad 0 --> Esperando resultados

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.30

### If your bug is related to a module, specify its name and its version

Descuentos  Reglas del carrito

**Comment by hibatallahAouadni** [comment]
Hello @matydominguez 

Please send your request in English. English is the norm on GitHub.

Thank you
