### ISSUE TITLE
ID for additional category description is missing

### ISSUE THREAD

**Issue by JBWModules** [PrestaShop/PrestaShop#29383]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Is your feature request related to a problem?

New additonal category description is missing ID

1. Category page
2. Find additonal description
3. Check for ID

### Describe the solution you'd like

ID existing

### Additional context

- PS version : 8.0.0 Beta1
- PHP version(s) : 7.4

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by JBWModules** [comment]
[/classic-theme/pull/49](https://github.com/PrestaShop/classic-theme/pull/49)

**Comment by hibatallahAouadni** [comment]
Hello @JBWModules 

Changing the issue type to Feature as what you proposed it's not a bug but it's an improvement :pray: 
Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments. 
Thanks for your PR :rocket: 

Thanks!
