### ISSUE TITLE
BO - Bad display when access to employee's profile pop-up with symfony pages after an upgrade from 1.7 to 8.0.0 when the shop is with RTL language

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#29399]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Bad display in profile pop-up with symfony pages after an upgrade from 1.7 to 8.0.0 when the shop is with RTL language

https://user-images.githubusercontent.com/92912932/185637232-5cef0a6c-090f-409f-9079-d7906adc7d73.mp4

https://user-images.githubusercontent.com/92912932/190982043-d439baa5-a1a4-4b84-9437-0ccc98183885.mp4

![image](https://user-images.githubusercontent.com/92912932/190982076-8adcadda-6fc0-47a7-bc9c-2ec2b3349a98.png)

PS : the .rtlfix file doesn't exists

### Expected behavior

The pop-up of my profile is well displayed

### Tech investigation
The way of building RTL assets has changed between the 1.7.8.x and the 8.0.x, when upgrading assets maybe imcompatible with the new behavior.

### Steps to reproduce

1. Install PS1778 OR PS1786
2. Uninstall problematic modules (welcome, ps_mbo, pd_metrics, facebook, psxmarketingwithgoogle)
3. Add an RTL language (As Arabic)
4. Change the BO language in Arabic
5. Install the autoupgrade v4.15 module from dev branch
6. Install a new 8.0.x branch
7. Create a release from 8.0.0
8. Configure the autoupgrade module
9. Upgrade to 8.0.0 branch
10. Check the 8.0.0 is well upgraded
11. Access to a symphony page 
12. Click to display pop-up to access in the employee profile
13. See error > The pop-up is not well displayed

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

autoupgrade v4.15.0 from dev branch

**Comment by MatShir** [comment]
@NeOMakinG hey do you have ideas how the behavior changed?

**Comment by NeOMakinG** [comment]
Found the probem, RTL assets are not generated on upgrade, meaning that they are not updated while upgrading, you can fix it by removing every `*_rtl.css` files and activate/deactivate the language, as well as activate/deacivate the RTL feature of the language, it will regenerate the right rtl assets

As a fix from the core, we should regenerate _rtl assets on upgrade!

**Comment by matks** [comment]
@HanaRebaiQA On your video I did not see the pop-up badly displayed. Can you please provide a screenshot ?

**Comment by lartist** [comment]
> @HanaRebaiQA On your video I did not see the pop-up badly displayed. Can you please provide a screenshot ?

Up

**Comment by HanaRebaiQA** [comment]
Hello @matks 

Yes! You are right. The video in question is not attached.
I updated the description by adding the screen-record and a screen-shot.

Thank You!

**Comment by lartist** [comment]
Hello @HanaRebaiQA I didn't succeed to reproduce the bug. I did autoupgrade from 1.7 to 8 and that's what i get
<img width="1676" alt="Capture d’écran 2022-09-29 à 10 22 47" src="https://user-images.githubusercontent.com/10706307/192979693-bb890f95-1e38-4859-92f9-fe3105784866.png">

**Comment by HanaRebaiQA** [comment]
Hello @lartist 

Sorry for the late answer. If you want we can see together the issue. 
Or, ping @PrestaShop/qa-functional Could someone try to reproduce it please?

Thank You!

**Comment by lartist** [comment]
I'm not assigned on this issue anymore but if things change, I would ping you. Thx @HanaRebaiQA

**Comment by hibatallahAouadni** [comment]
Hello everyone,

I didn't manage to reproduce the issue with PS1787 upgraded to PS800 by 1-Click Upgrade v4.15.0, see the attached screen record below:

[issue_rtl-upgrade.webm](https://user-images.githubusercontent.com/23308427/210452495-61070f6f-1c2b-4b23-b99c-c718c6fb5bb7.webm)

<img width="1465" alt="Screenshot 2023-01-03 at 23 30 41" src="https://user-images.githubusercontent.com/23308427/210452647-575c4329-7fd5-4d0a-8af8-1ecdfb7d1a42.png">

<img width="1462" alt="Screenshot 2023-01-03 at 23 31 12" src="https://user-images.githubusercontent.com/23308427/210452561-5083e0a8-1f2e-448f-ac70-acb9a5ee3d14.png">

As you can see, I encounter another issue only with Symfony pages 😞 and it's not related to RTL language.
@NeOMakinG wdyt the cause of this new issue? Cause I tried multiple times to clear the cache and reload the page in vain.

Thanks!

**Comment by MatShir** [comment]
I'm closing the issue, the issue was not reproduced

**Comment by HanaRebaiQA** [comment]
Hello @hibatallahAouadni 

Thanks for your reproduction. But, the issue occurs only on the symphony page and not the legacy page. (see Step11)
For now, I have a cache problem. I will check again and come back to you. 
And if you can please try to reproduce it on a symphony page.

Thanks!
