### ISSUE TITLE
Autoupgrade - BO - Bad display in menu when access to legacy pages after an upgrade from 1.7 to 8.0.0 when the shop is with RTL language

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#29398]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Bad display in menu when access to legacy pages after an upgrade from 1.7.7.8 and 1.7.8.6 to 8.0.0 when the shop is with RTL language

![image](https://user-images.githubusercontent.com/92912932/185630168-fef2d620-3872-4321-b458-a4ce1ac98465.png)

https://user-images.githubusercontent.com/92912932/185633871-4906493a-1e7b-4a71-aad3-1c3341a51ff9.mp4

PS : the `.rtlfix `file doesn't exists

### Expected behavior

The menu is well displayed in all legacy pages after an upgrade with RTL language from 1.7 to 8.0.0 

### Steps to reproduce

1. Install PS1778 OR PS1786
2. Uninstall problematic modules (welcome, ps_mbo, pd_metrics, facebook, psxmarketingwithgoogle)
3. Add an RTL language (As Arabic)
4. Change the BO language in Arabic
5. Install the autoupgrade v4.15 module from dev branch
6. Install a new 8.0.x branch
7. Create a release from 8.0.0
8. Configure the autoupgrade module
9. Upgrade to 8.0.0 branch
10. Check the 8.0.0 is well upgraded
11. See error > The menu is not well displayed with RTL and a bad display in all page
12. Check any legacy page
13. See error > The menu is not well displayed with RTL and a bad display in all page

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

autoupgrade v4.15.0 from dev branch

**Comment by mparvazi** [comment]
Hello @HanaRebaiQA 

Has the browser cache cleared after the upgrade?

**Comment by HanaRebaiQA** [comment]
Hello @mparvazi 

Yes! and even i tested with a private navigation.

**Comment by mparvazi** [comment]
> Hello @mparvazi
> 
> Yes! and even i tested with a private navigation.

It seems the font-icon not loaded, so could you please check the browser Console (Network tab) to see the missing files?

**Comment by HanaRebaiQA** [comment]
Hello @mparvazi 

Here is a screenshot for what you asked

![image](https://user-images.githubusercontent.com/92912932/185655943-7c206720-8d4a-4a7c-89c4-684e818fb385.png)

**Comment by mparvazi** [comment]
@HanaRebaiQA 

As I saw in screenshot there are 3 errors on Console. please try to enable these options:

![185655943-7c206720-8d4a-4a7c-89c4-684e818fb385](https://user-images.githubusercontent.com/85633460/185657234-fe5917ed-c713-4efe-b991-d2cbea48cc43.png)

**Comment by HanaRebaiQA** [comment]
@mparvazi 

I did it : 

![image](https://user-images.githubusercontent.com/92912932/185658642-d5dcd09f-0be5-4415-ab86-4d600baaa3f2.png)

**Comment by mparvazi** [comment]
@NeOMakinG 

Is it related to preload font-icon script?

**Comment by MatShir** [comment]
@mparvazi Could you investigate the issue? We are quite busy on auto-upgrade and other regressions, we would appreciate your help 🥺

**Comment by mparvazi** [comment]
> @mparvazi Could you investigate the issue? We are quite busy on auto-upgrade and other regressions, we would appreciate your help 🥺

OK, I'm on it.

**Comment by NeOMakinG** [comment]
> @NeOMakinG
> 
> Is it related to preload font-icon script?

Maybe, if you need to talk about it feel free to send me a pm 🚀

**Comment by matthieu-rolland** [comment]
fixed in this PR https://github.com/PrestaShop/PrestaShop/pull/29534

Thanx @NeOMakinG for your input :+1:

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29534
