### ISSUE TITLE
Autoupgrade - BO - An error related to the controller is missing or invalid in Theme Catalog and Module Catalog after an upgrade from 1.7 to 8.0.0

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#29394]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An error related to the controller is missing or invalid in Theme Catalog and Module Catalog after an upgrade from 1.7.7.8 and 1.7.8.6 to 8.0.0

This issue is related to [#27733](https://github.com/PrestaShop/PrestaShop/issues/27733) 

**Module Catalog**
![image](https://user-images.githubusercontent.com/92912932/185605125-b84bf410-e83e-4eb8-a0d5-69ad105ba596.png)

**Theme Catalog**
![image](https://user-images.githubusercontent.com/92912932/185605177-0d52b179-2f5a-4a6a-a903-a417c685e107.png)

### Expected behavior

The Module Catalog and Theme Catalog pages should not be displayed in the BO menu after an upgrade to 8.0.0

# Tech investigation

SQL script in the auto-upgrade to do
Similar task to this PR https://github.com/PrestaShop/autoupgrade/blob/dev/upgrade/sql/8.0.0.sql#L8-L29 (it has the configuration)

### Steps to reproduce

1. Install PS1778 OR PS1786
2. Uninstall problematic modules (welcome, ps_mbo, pd_metrics, facebook, psxmarketingwithgoogle)
3. Install the `autoupgrade v4.15` module from dev branch
4. Install a new 8.0.x branch
5. Create a release from 8.0.0 
6. Configure the autoupgrade module
7. Upgrade to 8.0.0 branch 
8. Check the 8.0.0 is well upgraded
9. GO to BO > Module > Module Catalog page 
10. See error  ==>  related to the controller is missing or invalid of Module Catalog
11. GO to BO > Design > Theme Catalog page
12. See error ==>  related to the controller is missing or invalid of Theme Catalog

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

autoupgrade v4.15.0 from dev branch

**Comment by matks** [comment]
Fixed by @matthieu-rolland
