### ISSUE TITLE
Error in language structure

### ISSUE THREAD

**Issue by JaimeAlvarezMedina** [PrestaShop/PrestaShop#29408]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I encounter an error in the page import, the error is that the select is concatenated whit the id.
![image](https://user-images.githubusercontent.com/93598962/185893897-ca7c7709-acf9-4a79-b45e-9d592e368a69.png)
 

### Steps to reproduce

1.Go to Catalogue
2. Click on settings
3. Go to import
4. See the select

### PrestaShop version(s) where the bug happened

1.7.6.2

**Comment by hibatallahAouadni** [comment]
Hello @JaimeAlvarezMedina 

I didn't manage to reproduce the issue with PS1767, PS1778, PS1786 and PS800, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/185896142-c0cacd84-4564-438c-bbc1-d86ce2f2e62d.png)

Closing the issue as it seems the issue has been fixed :wink: 

PS: thanks for your great and well detailed bug report :clap: :pray: 

Thanks!
