### ISSUE TITLE
Wholesale Price of combinations lose their decimals

### ISSUE THREAD

**Issue by mathieuhen** [PrestaShop/PrestaShop#29415]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you have combiantions that have a wholesale price and you come back to the admin page after having already saved once, if you re-save then the purchase prices lose their decimals

### Expected behavior

I think the solution is to replace comma with point in the updateAttribute function in the product class as it is already done for price and weight

### Steps to reproduce

1. Create a product with combinations
2. Use the bulk edit to introduce wholesale_price : 15.15€ for example
3. Save the product
4. Refresh your page
5. Check wholesale_price in each combinations : good prices are here => 15,15€ (but with comma and not with point)
6. Re-save the product without change anything else
7. Refresh your page
8. Check wholesale_price : the prices are wrong => 15,00 €

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Hello @mathieuhen 

Thanks for the detailed steps :pray: 
Unfortunately, I didn't manage to reproduce the issue with the provided infos :disappointed: 
Could you please provide a screen record cause it seems there's a missing step :pray: 
Waiting for your feedback.

PS: could you please check this issue #14093 seems related to yours

Thanks!

**Comment by mathieuhen** [comment]
Yes, it's the same issue. I didn't find this bug report, sorry

**Comment by hibatallahAouadni** [comment]
Hello @mathieuhen 

Thanks for your feedback :pray: 
We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #14093. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #14093
