### ISSUE TITLE
 An unexpected error occurred when you try to modify any customer information after import by webservice

### ISSUE THREAD

**Issue by lionelJDN** [PrestaShop/PrestaShop#29412]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An unexpected error occurred. [PrestaShop\PrestaShop\Core\Domain\Customer\Exception\CustomerException code 0]: Customer contains invalid field values when modify and save customer information in BO.

On a new installation of Prestashop 1.7.8.6, when I import customers with Postman by using Webservice, it is impossible to save customer profile.

![image](https://user-images.githubusercontent.com/111759208/186101084-48364c27-d567-49e7-89bd-f5133d6c8144.png)

### Expected behavior

No error when save customer information.

### Steps to reproduce

- Go to Postman: Set a POST request like this:
https://yourdomain.com/api/customers/123456?ws_key=xXx&output_format=JSON
-  In the Body section, paste this XML code:
```
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
  <customer>
    <passwd>123456</passwd>
    <lastname>dupont</lastname>
    <firstname>dupont</firstname>
    <email>customermail@mail.com</email>
  </customer>
</prestashop>
```
- Click on Send button.
- You'll get a status 201 Created.
- Go to Customers page, open Edit customer page.
   Try to save customer information. Not necessary to modify something.
   See error An unexpected error occurred. [PrestaShop\PrestaShop\Core\Domain\Customer\Exception\CustomerException code 0]: Customer contains invalid field values.
   If customer is created directly in BO or FO, there is no such error.

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.2

**Comment by lionelJDN** [comment]
I try this tips but it doesn't work in my case: [https://github.com/PrestaShop/PrestaShop/pull/27781/files#diff-7d9a1a25c8bc7d5b8d5e6368443975f834a9cf26816836645223e49b8293f338R404](url)

**Comment by hibatallahAouadni** [comment]
Hello @lionelJDN 

I didn't manage to reproduce the issue with PS1786 following your steps to reproduce!

![image](https://user-images.githubusercontent.com/23308427/186123078-5a0b791e-e142-4726-8928-c61519e405a2.png)

The only error was dispalyed is: `A default customer group must be selected in group box.`
Cause we need to assign a customer group foreach newly created customer :wink: 
See the attached screenshot below: 

![image](https://user-images.githubusercontent.com/23308427/186122282-d18c2734-3573-422a-a3b5-e74819823586.png)

When I choose a default Customer group and then Save, the customer is well saved without errors: `Successful update.`
Please check and feedback.

Thanks!

**Comment by lionelJDN** [comment]
Hello @hibatallahAouadni, thank you very much for your answer.
It's exact. I got the same warning as you about customer group when I tried to save for the first time.
Then, i'll select a group and a default group and I got the error:
An unexpected error occurred. [PrestaShop\PrestaShop\Core\Domain\Customer\Exception\CustomerException code 0]: Customer contains invalid field values (with debug mode enabled).

But If I imported the customer with group on Postman, i got the error on the first save in the customer profile on BO.
`<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
  <customer>
    <passwd>123456</passwd>
    <lastname>dupont</lastname>
    <firstname>dupont</firstname>
    <email>customermail@mail.com</email>
    <id_default_group>2</id_default_group>
     <associations>
      <groups>
        <group>
          <id>1</id>
        </group>
        <group>
          <id>2</id>
        </group>
      </groups>
    </associations>
  </customer>
</prestashop>`

Thank you for your advices.

Best regards,
Lionel

**Comment by hibatallahAouadni** [comment]
Hello @lionelJDN 

Thanks for your feedback and all details :pray: 
I didn't manage to reproduce the issue as you can see the attached screen record below:

https://user-images.githubusercontent.com/23308427/186956173-59dc7841-d498-4053-8d17-9eb38559b379.mp4

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a module problem.

We will close this issue.

Thanks!

**Comment by jkulikowski** [comment]
For all the people who struggle with this error. 

Check in database _ps_customers_ table, date_upd can't be set to "0000-00-00 00:00:00" for customer. Assigning value from date_add to date_upd fixed problem for me. Probably missed that during sql import
