### ISSUE TITLE
BO - An exception is thrown when export the sql query of the employee after save it

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#29424]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

 An exception is thrown when export the sql query of the employee after save it

8.0.0 : NOK (`getWhereReferenceError()`) :x: 

![image](https://user-images.githubusercontent.com/92912932/186210417-b2eb4a03-9ece-47fa-a147-1461140f34c8.png)

https://user-images.githubusercontent.com/92912932/186211110-c4b17732-74e8-48fe-ba97-2a03aaec7ec8.mp4

1.7.8.7 : NOK => Same error :x: 

![image](https://user-images.githubusercontent.com/92912932/186210498-4ae68323-1506-48a7-b640-d67e086ae146.png)

1.7.7.8 => Another error (`getReferenceError()`)
![image](https://user-images.githubusercontent.com/92912932/186210757-5f0ba272-9298-4ff8-862a-b38b98163514.png)

### Expected behavior

No exception is thrown 

### Steps to reproduce

1. Go to Advanced parameters > Team > Employees tab > Click on Show SQL query
2. Click on Export to SQL Manager
3. In SQL Manager page > Click on Save
4. See error > An exception is thrown with getWhereKeywordError()

### PrestaShop version(s) where the bug happened

8.0.0 beta, 1.7.8.7

### PHP version(s) where the bug happened

7.3

**Comment by matks** [comment]
Fixed by @atomiix https://github.com/PrestaShop/PrestaShop/pull/29549
