### ISSUE TITLE
Do not authorize config.xml direct call on modules directory

### ISSUE THREAD

**Issue by clotairer** [PrestaShop/PrestaShop#29422]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If you call a shop with URL https://www.yourshop.com/modules/module_name/config.xml (or config_en.xml) you can know with version of the module is installed.

For instance :
- https://www.yourshop.com/modules/blockwishlist/config.xml

In case of security advisory on a module, a hacker can know if the PrestaShop has a module not up-to-date.

### Expected behavior

Return a forbidden access to this URL with the htaccess.

### Steps to reproduce

1. Install a new PrestaShop
2. Install the module blockwishlist (or an other)
3. Go to URL like https://www.yourshop.com/modules/blockwishlist/config.xml

### PrestaShop version(s) where the bug happened

all

### PHP version(s) where the bug happened

all

**Comment by hibatallahAouadni** [comment]
Hello @clotairer 

Thanks for reporting the issue and creating your PR :rocket: 
I reproduce the issue with PS1.7.7.0 and PS1.7.8.6 with various modules. 
I’ll add this to the debug backlog.

Thank you
