### ISSUE TITLE
Zip file not Recognized by Prestashop installer

### ISSUE THREAD

**Issue by JacHOBBY** [PrestaShop/PrestaShop#29425]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,
After downloding the ps_languageselector.zip file from GitHub the Prestashop installer does not recognized the file has a valid ZIP file.

Online support recommand to report the issue.

The link used to download is https://github.com/PrestaShop/ps_languageselector.

As recommanded by online support I have also tried to renamed the file to PS_Language selector.zip but still not working.

See error message detail;

![zip not recognized](https://user-images.githubusercontent.com/92323282/186212539-fafa4b1b-8adc-4a68-b2c3-676864c08c65.JPG)

Thank you for your help,

Jacques

### Expected behavior

Zip file should be good and installer should installed module.

### Steps to reproduce

Goto github link https://github.com/PrestaShop/ps_languageselector
Select code
download zip
from Prestashop module management choose install module
select the zip file from your download location.
install.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.30

### If your bug is related to a module, specify its name and its version

PS_languageselector

**Comment by kpodemski** [comment]
Hello @JacHOBBY 

You've probably downloaded sources of the module. You can download the valid .zip for the module from the "Releases" tab, there:
https://github.com/PrestaShop/ps_languageselector/releases

**Comment by JacHOBBY** [comment]
Hello Kpodemski,

It work fine with this link thank you!

Maybe will be good to informed the online support about refering the proper links. I have trust they where providing me with a valid link which obviously was not the case.

Have a great one !

Jacques

**Comment by AureRita** [comment]
Hello @JacHOBBY ,

I glad to know that your problem was corrected, 

thank you @kpodemski for the quick answer !
