### ISSUE TITLE
The override directory is deleted when overrides are uninstalled

### ISSUE THREAD

**Issue by jherry** [PrestaShop/PrestaShop#29436]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you disable a module that contains overrides, then the /override directory is deleted and so an error occurs when trying to install a new override.

### Expected behavior

Files .htaccess and index.php in /override directory should be preserved

### Steps to reproduce

1) Install a module that contains overrides
2) Disable the module
3) Enable the module, you will get the error "Unable to install override: Failed to copy "[...]/override/index.php" because file does not exist."

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment]
Hello @jherry 

I didn't manage to reproduce the issue with natives modules.
Could you please provide a test module to help me reproducing your issue 🙏 
Waiting for your feedback.

Thanks!

**Comment by jherry** [comment]
[modulewithoverride.zip](https://github.com/PrestaShop/PrestaShop/files/9430096/modulewithoverride.zip)
I was able to reproduce with this dummy module. I test on Windows.

**Comment by hibatallahAouadni** [comment]
Hello @jherry 

I didn't manage to reproduce the issue with the provided module, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/186959064-2757c51d-e35f-402f-8549-3ae498cf647d.mp4

Please check and feedback.

Thanks!

**Comment by jherry** [comment]
I still reproduce: https://www.loom.com/share/442ed7fc5cdc4846a7e2c1f4bcae783b

- Server information: Windows NT build 22000 (Windows 10) AMD64
- Server software version: Apache/2.4.35 (Win64) PHP/7.2.10
- PHP version: 7.2.10
- Memory limit: 512M
- Max execution time: 300
- Upload Max File size: 200M

**Comment by kpodemski** [comment]
Maybe it has something to do with the fact that it's Windows 🤔 

@Hlavtox do you think you could test it?

**Comment by Hlavtox** [comment]
@kpodemski @jherry 
![Snímek obrazovky 2022-08-29 144125](https://user-images.githubusercontent.com/6097524/187203388-f7fca96f-cf10-4dfb-8de2-97a5b5891b18.jpg)

```
Server Information: Windows NT build 22621 (Windows 10) AMD64
Server software version: Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/8.0.19
PHP version: 8.0.19
Memory limit: 512M
Max. execution time: 120
Max. uploaded file size: 40M
```

**Comment by kpodemski** [comment]
@hibatallahAouadni 

It is a valid issue then, but the problem occurs on Windows only.

**Comment by sLorenzini** [comment]
Hello @jherry,

Thank you for your report.

Thank you @Hlavtox for testing and @kpodemski for your help. I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by eshraw** [comment]
Impacted code could be located here : \ModuleCore::removeOverride

**Comment by idnovate** [comment]
It does not happen if there are other overrides in the folder. It only happens when the folder is empty.

**Comment by idnovate** [comment]
It seems related with this issue:

https://www.php.net/manual/en/splfileinfo.getpathname.php#102987
`In Windows, getPathname might return a path with a mix of backslashes and forward slashes ('C:/some/path/to\a\file.txt'). Observed in PHP 5.2.9. By contrast, getRealPath will return a consistent result (all backslashes).`

And the problem is with slashes:

`$directoryOverride` is `\override` while `$directoryPath` after some loops is `/override`, so condition `while ($splDir->getRealPath() !== $directoryOverride)` is always true.

https://github.com/PrestaShop/PrestaShop/blob/05bc61bf8f90ba7712009fe173fbce8c9955dfa8/classes/module/Module.php#L3260

**Comment by HanaRebaiQA** [comment]
Hello @jherry & @idnovate 

I tried to reproduce the issue before testing the PR. But, i could not reproduce it using the final **8.0.0 version** and the same provided module : [modulewithoverride.zip](https://github.com/PrestaShop/PrestaShop/files/9910352/modulewithoverride.zip)

I noticed that only the `index.php` file which is present under `/override` folder and it's always preserved.

Here the provided information about the tested environment :

- Server information: Windows 10
- Server software version: Apache/2.4.51 (Debian)
- PHP version: 7.3.33
- Memory limit: 1024M
- Max execution time: 30
- Upload Max File size: 10000M

![image](https://user-images.githubusercontent.com/92912932/199246328-fe170cdb-32ec-4c6d-9724-6836013254c6.png)


https://user-images.githubusercontent.com/92912932/199247010-f6a490e0-8b74-4d72-b609-5157323245b7.mp4

Could you please check again ?
Waiting for you feedback !

Thank You!

**Comment by jherry** [comment]
@HanaRebaiQA I still reproduce with release found here: https://github.com/PrestaShop/PrestaShop/releases/tag/8.0.0
On windows 11 and PHP 7.2.10

**Comment by idnovate** [comment]
I have been able to reproduce the issue with PS version 8.0.0.

I attach you the module that I used.

You just need to install (OK) and then uninstall (/override folder is removed).

[dummymodule.zip](https://github.com/PrestaShop/PrestaShop/files/9913942/dummymodule.zip)

**Comment by Liewebs** [comment]
I am using Windows to test module sin Wammp server and same issue. I know mates using Linux and no issue. Maybe it is only happening in windows.

**Comment by kpodemski** [comment]
@HanaRebaiQA I'm not sure if testing this way is testing on Windows 🤔 

I think we can trust @Hlavtox and others, then we could have QA by a developer with the help of @Hlavtox 

What do you think @HanaRebaiQA ?

**Comment by hibatallahAouadni** [comment]
Hello @kpodemski 

Trusting developers is quite risky :sweat_smile: but yeah I like the solution you propose.
May the odds be ever in our favor :crossed_fingers: :grin: 

Thanks!

**Comment by Hlavtox** [comment]
@hibatallahAouadni HEEEEEEEY 😄
