### ISSUE TITLE
Symfony module routes generate an error

### ISSUE THREAD

**Issue by musaffar-patel** [PrestaShop/PrestaShop#29437]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When making use of symfony routes for back office controllers in a module, the route only seems to work the first time it is loaded.  When the link used for a second time it causes the following error:

Warning: filemtime(): stat failed for E:\websites\mysite\classes\PrestaShopAutoload.php(143) : eval()'d code

### Steps to reproduce

Generate a symfony route to a module controller and load the link in the browser,.  The link only works the first time.

### PrestaShop version(s) where the bug happened

1.7.8.0

**Comment by hibatallahAouadni** [comment]
Hello @musaffar-patel 

Thanks for reporting the issue!
Ping @PrestaShop/prestashop-maintainers can someone please try to reproduce the issue :pray: 
It's too technical for me :sweat_smile: 

Thanks!

**Comment by atomiix** [comment]
Hi @musaffar-patel, I'm not sure to understand what you mean 🤔
Could you maybe add a screenshot, a screen record of the problem happening or even a sample module so we can reproduce the issue?
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @musaffar-patel 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
