### ISSUE TITLE
Duplicated product on Manuafcturer page (Order By quantity DESC)

### ISSUE THREAD

**Issue by augustomurri** [PrestaShop/PrestaShop#29439]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I'm having a duplicate product issue on the manufacturer page. After some investigation he identified the problem in the ordering system by quantity and i don't know how to solve. I have disabled all overrides and all thir part modules.

The following query reports the same product on different pages :/

`SELECT SQL_NO_CACHE p.*, product_shop.*, stock.out_of_stock, IFNULL(stock.quantity, 0) as quantity, product_attribute_shop.minimal_quantity AS product_attribute_minimal_quantity, IFNULL(product_attribute_shop.`id_product_attribute`,0) id_product_attribute
, pl.`description`, pl.`description_short`, pl.`link_rewrite`, pl.`meta_description`, pl.`meta_keywords`,
pl.`meta_title`, pl.`name`, pl.`available_now`, pl.`available_later`, image_shop.`id_image` id_image, il.`legend`, m.`name` AS manufacturer_name,
DATEDIFF(
product_shop.`date_add`,
DATE_SUB(
"2022-08-25 00:00:00",
INTERVAL 90 DAY
)
) &gt; 0 AS new FROM `ps_product` p
INNER JOIN ps_product_shop product_shop
ON (product_shop.id_product = p.id_product AND product_shop.id_shop = 1)LEFT JOIN `ps_product_attribute_shop` product_attribute_shop
ON (p.`id_product` = product_attribute_shop.`id_product` AND product_attribute_shop.`default_on` = 1 AND product_attribute_shop.id_shop=1)
LEFT JOIN `ps_product_lang` pl
ON (p.`id_product` = pl.`id_product` AND pl.`id_lang` = 1 AND pl.id_shop = 1 )
LEFT JOIN `ps_image_shop` image_shop
ON (image_shop.`id_product` = p.`id_product` AND image_shop.cover=1 AND image_shop.id_shop=1)
LEFT JOIN `ps_image_lang` il
ON (image_shop.`id_image` = il.`id_image` AND il.`id_lang` = 1)
LEFT JOIN `ps_manufacturer` m
ON (m.`id_manufacturer` = p.`id_manufacturer`)
LEFT JOIN ps_stock_available stock
ON (stock.id_product = `p`.id_product AND stock.id_product_attribute = 0 AND stock.id_shop = 1  AND stock.id_shop_group = 0  )JOIN `ps_category_product` cp ON (p.id_product = cp.id_product)JOIN `ps_category_group` cg ON (cp.`id_category` = cg.`id_category` AND cg.`id_group` =1)JOIN `ps_category` ca ON cp.`id_category` = ca.`id_category` AND ca.`active` = 1
WHERE p.`id_manufacturer` = 83
AND product_shop.`active` = 1
AND product_shop.`visibility` IN ("both", "catalog")
GROUP BY p.id_product
**ORDER BY stock.`quantity` desc**
LIMIT 0,12`

It can be viewed online on this page https://nuovo.tsunaminutrition.it/83_bpr-nutrition product **B-complex 90 caps** is shown on both page 1 and page 2

If i change the default sorting method on backend, for example i set "Sort Alapabetical" there are no issues.

### Expected behavior

No duplicated products should be showed

### Steps to reproduce

It can be viewed online on this page [https://nuovo.tsunaminutrition.it/83_bpr-nutrition](https://nuovo.tsunaminutrition.it/83_bpr-nutrition) product **B-complex 90 caps** is shown on both page 1 and page 2

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4.30

### If your bug is related to a module, specify its name and its version

facedsearch is not enabled

**Comment by hibatallahAouadni** [comment]
Hello @augustomurri 

Could you please provide your PHP version and clear concise steps to reproduce :pray: 
Waiting for your feedback.

Thanks!

**Comment by augustomurri** [comment]
@hibatallahAouadni PHP Version 7.4.30

To reproduce the issue i should try to create a fresh installation, how can i fill database with random products?

**Comment by hibatallahAouadni** [comment]
Hello @augustomurri 

> To reproduce the issue i should try to create a fresh installation, how can i fill database with random products?

When you install fresh shop check the option "installation of demo products" and choose **Classic** as a theme:
 
![image](https://user-images.githubusercontent.com/23308427/186958348-a0159f42-68a9-4c05-ac78-d4cd4f708ed4.png)

Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @augustomurri 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
