### ISSUE TITLE
Cannot decorate back office order controller

### ISSUE THREAD

**Issue by musaffar-patel** [PrestaShop/PrestaShop#29434]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When attempting to decorate a back office controller, such as the order detail controller, the following error is produced by Symfony:

Call to a member function getBoolean() on null

This is occurring in Prestashop 1.7.8 but could also be a problem in previous versions.

Attached is a sample module which demonstrates the problem.

### Steps to reproduce

Install fresh copy of Prestashop 1.7.8
Install module attached
Navigate to orders section in the back office

### PrestaShop version(s) where the bug happened

1.7.8.0

**Comment by musaffar-patel** [comment]
sample module attached.
[
[mymodule.zip](https://github.com/PrestaShop/PrestaShop/files/9423738/mymodule.zip)
](url)

**Comment by hibatallahAouadni** [comment]
Hello @musaffar-patel 

Could you please check this issue #29286 seems similar to yours.
Waiting for your feedback.

Thanks!

**Comment by musaffar-patel** [comment]
H, the error is different to mine

**Comment by hibatallahAouadni** [comment]
Hello @musaffar-patel 

After installing your module on PS1786, I click on Configure button and I encounter this exception:

![image](https://user-images.githubusercontent.com/23308427/186956729-9bf5cc94-45e1-4031-8c59-e48263df0e17.png)

And I didn't encounter any issue on Orders page, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/186957234-70d79ab8-45d4-4073-9fe4-8a4afb359a01.png)

Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @musaffar-patel 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by soulaimane-aattar** [comment]
hello i encountered the same bug on  the view order page
