### ISSUE TITLE
infinite scroll

### ISSUE THREAD

**Issue by kayaist** [PrestaShop/PrestaShop#29440]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

There is a problem with the infinite scrolling of the category page When we go to the 2nd page, when we open the product, when we say go back, it turns the top of the 1st page.
![3](https://user-images.githubusercontent.com/112088178/186667453-ebe23452-c12a-4910-8eda-326b61034372.png)
![2](https://user-images.githubusercontent.com/112088178/186667476-df669a6a-9d69-434b-9351-52d79b886c4f.png)
![1](https://user-images.githubusercontent.com/112088178/186667493-931b6d18-2f15-4889-964d-4e808ce67e4b.png)

https://user-images.githubusercontent.com/112088178/186668560-0b09d0da-9d0e-49ad-97b1-b16dbe1fd47c.mp4

### Expected behavior

must continue from the same product

### Steps to reproduce

![3](https://user-images.githubusercontent.com/112088178/186667453-ebe23452-c12a-4910-8eda-326b61034372.png)
![2](https://user-images.githubusercontent.com/112088178/186667476-df669a6a-9d69-434b-9351-52d79b886c4f.png)
![1](https://user-images.githubusercontent.com/112088178/186667493-931b6d18-2f15-4889-964d-4e808ce67e4b.png)
https://www.toptanucuzicgiyim.com/9-art

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @kayaist 

Could you please switch to Classic theme 🙏 
Cause it seems the issue is related to your theme 😉 
Please check and feedback.

Thanks!

**Comment by florine2623** [comment]
Hello @kayaist ,

The classic theme does not have an infinite scroll.
Please contact your theme provider directly.

I'll close your issue as it does not concern the PrestaShop project.
Thanks!
