### ISSUE TITLE
Free shipping in coupons doesn't work

### ISSUE THREAD

**Issue by galantematteo** [PrestaShop/PrestaShop#29445]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When there is a free shipping voucher, in the checkout page => cart details, the shipping line is incorrect, the shipping cost is displayed instead of FREE.

### Expected behavior

What should be done is to display FREE on the shipping line instead of the initial pricen when there is a free shipping voucher and reduce shipping cost 

### Steps to reproduce

1) Create a voucher with "Free shipping" selected
2) Go on the store, add a product that satisfy voucher rules and use in checkout
3) Nothing changes in total price

![rule](https://user-images.githubusercontent.com/87337971/186682761-1bfb571b-96a4-4029-959b-374633a7ae71.JPG)

![shipping](https://user-images.githubusercontent.com/87337971/186682623-26e32f40-8948-4724-85f6-b96d7f74b8d7.JPG)

### PrestaShop version(s) where the bug happened

1.7.6.5

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment]
Hello @galantematteo 

Closing the issue as I can't reproduce with PS1787, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/186954981-591fcf1c-9ab7-46c4-a613-f99454da11d4.png)

Thanks!

**Comment by galantematteo** [comment]
Yes, but the version is different... we're using 1.7.6.5

**Comment by galantematteo** [comment]
@hibatallahAouadni so? Invalid cause you're reproduce it whit a different version? The problem is here

**Comment by hibatallahAouadni** [comment]
@galantematteo cause it seems the problem fixed as I couldn't reproduce the issue with PS1787!

**Comment by galantematteo** [comment]
@hibatallahAouadni But the problem isn't fixed if PS1765 reproduce the error. We can't simply update to 1.7.X if we've linked modules working with this version.

**Comment by kpodemski** [comment]
@galantematteo you have to update if you want to have the fix available

**Comment by galantematteo** [comment]
So, there isn't fix for a core function?

**Comment by kpodemski** [comment]
@galantematteo there is, in a new version of the software :)

this is how it works, in order to get fixes and new features you need to keep your software up-to-date

**Comment by galantematteo** [comment]
Ye, know how it works, but the problem is related to modules and this a bit strange that there isn't fix for a core function of an existing version of ps. We're talking about a major bug

**Comment by kpodemski** [comment]
@galantematteo, how would you imagine fixing every bug in every PrestaShop version? that would be a huge time investment as sometimes the fix wouldn't work from version to version :)

**Comment by galantematteo** [comment]
I know, but we're talking about a major core bug of prestashop and it's impossible that there isn't a fix. I mean... when the 1.7.6 was the only version no one notice in entire world? Thats for sure something that makes me in safe for all other funcionalities in ps :)

**Comment by galantematteo** [comment]
@kpodemski @hibatallahAouadni  I've copied the store in a demo cloud, upgraded to the latest version but the result is the same. Now i can see the label changed to "free" but the total is wrong
![error](https://user-images.githubusercontent.com/87337971/187419802-f1ed1ef2-2ce9-40e9-9044-37a8fa9a2e28.JPG)
