### ISSUE TITLE
Make the $maintenance parameter of FrontController public

### ISSUE THREAD

**Issue by mostlypixels** [PrestaShop/PrestaShop#29450]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

I need to implement a conditional approach to the maintenance mode through a module. 

The `displayMaintenance()` method uses `$this->maintenance` in its initial condition, which would make changing the parameter value the easiest way to trigger the display of the maintenance page.

I would like to use the `actionFrontControllerInitBefore` hook, since it passes the controller as a parameter, but the parameter is protected.

### Describe the solution you'd like

Make the param public (See [PR](https://github.com/PrestaShop/PrestaShop/pull/29449) ).

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by mostlypixels** [comment]
The request is flawed, this would be better implemented as a new hook. Closing.

Edit: Using the ReflectionObject to set the property as accessible is sufficient for this use case.

**Comment by hibatallahAouadni** [comment]
@mostlypixels thanks for your feedback :sweat_smile:
