### ISSUE TITLE
Available now and later labels not validated properly

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#29454]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In product page v2 stock tab "available_now" and "available_later" labels are not validated as it should.
Product object model validates their length to be up to 255 chars and a "generic name" - meaning characters "<>={}" are not allowed.
![Screenshot from 2022-08-26 17-02-50](https://user-images.githubusercontent.com/31609858/186922637-dc7fe820-7f99-450e-80e2-a0db7aa715b2.png)
:

### Expected behavior

Instead of generic flash error, form errors should be displayed
![Screenshot from 2022-08-26 17-07-17](https://user-images.githubusercontent.com/31609858/186922722-7d77a646-2545-443e-ac91-bb4d309f5592.png)
![Screenshot from 2022-08-26 17-04-56](https://user-images.githubusercontent.com/31609858/186922725-154d1cad-8f59-4587-a218-a63fe4ecaac9.png)
.

### Steps to reproduce

1. Go to product page V2 stock tab (of non combinational product)
2. Scroll down to fields "Available now label" and "Available later label" (these fields should act the same).
3. case1 - input more characters than 255 and submit ; case2 input any of these characters "<>={}".
4. submit the form and see error.

### PrestaShop version(s) where the bug happened

8.0.x

**Comment by zuk3975** [comment]
note -  in same PR should add constants in ProductSettings class to be reused both in Product.php and in AvailabilityForm constraints.

**Comment by hibatallahAouadni** [comment]
Hello @zuk3975 

I reproduce the issue with PS1786 and PS800 only with Product V2. 
I’ll add this to the debug backlog so that it’s fixed. Waiting for your PR :rocket: 

Thank you
