### ISSUE TITLE
BO - Error after successful upgrade

### ISSUE THREAD

**Issue by costads** [PrestaShop/PrestaShop#29457]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After a successful upgrade from 1.7.7.2 to 1.7.8.7 I get this error when I want to check orders, customers, etc. in back office.

```
Type error: Return value of PrestaShopBundle\Entity\ShopGroup::getShops() must be an instance of Doctrine\Common\Collections\Collection, null returned

[Symfony\Component\Debug\Exception\FatalThrowableError 0]
```

I have to enable debug mode in order to see those pages.
I have cleared the cache as well.
Seems like it has to do with the fact that I have multistore enabled (2 stores in my case)

### Steps to reproduce

1. Upgrade your shop from 1.7.7.2 to 1.7.8.7
2. Click on orders
3. An error will occur

### PrestaShop version(s) where the bug happened

1.7.8.7

**Comment by sLorenzini** [comment]
Hello @costads,

I couldn't reproduce your issue with an upgrade from 1.7.7.2 version to 1.7.8.7. See my screenrecord:


https://user-images.githubusercontent.com/2854834/187175210-da92797d-58cc-4de0-9dfc-12062e2e0538.mp4


Could you please give us more info to try to reproduce your error (version of upgrade module, more steps with multistore or performance configuration of your store etc..) or maybe screenshots or screenrecords please 🙏?

Thank you

**Comment by costads** [comment]
I see, that was annoying :)
I had to roll back, so can't see the exact errors now. But I was using the latest 1-click upgrade. I also bought a 3rd party module to upgrade, but got the same errors.

When I enabled debug, this was the error I got, when I clicked on orders, customers, products, etc.

SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.color' in 'field list'").

So I guess it has to do with the new multishop color option. But that function appeared to work well under multistore setting.

But if the above error doesn't make it easier, I will try the upgrade again tonight and take some photos or something.

**Comment by sLorenzini** [comment]
@costads, thank you for your feedbacks.
It will be great if you can provide us screenshots or screenrecord of another upgrade of your store.

Waiting for it/them.

Thank you

**Comment by costads** [comment]
So I made the upgrade again so I could get the errors. The upgrade went without any errors:

I can load the Dashboard without any errors.

When I in the menu click on Orders, Customers, Modules, etc. I get this error:
```
Type error: Return value of PrestaShopBundle\Entity\ShopGroup::getShops() must be an instance of Doctrine\Common\Collections\Collection, null returned

[Symfony\Component\Debug\Exception\FatalThrowableError 0]
```

So I enable debug mode, and then I have these 2 errors in the Log:
```

CRITICAL01:17:11 | php | Uncaught Exception: An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT t0.id_shop_group AS id_shop_group_1, t0.name AS name_2, t0.color AS color_3, t0.share_customer AS share_customer_4, t0.share_order AS share_order_5, t0.share_stock AS share_stock_6, t0.active AS active_7, t0.deleted AS deleted_8 FROM ps_shop_group t0 WHERE t0.active = ?' with params [1]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.color' in 'field list'").
-- | -- | --
CRITICAL01:17:11 | request | Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT t0.id_shop_group AS id_shop_group_1, t0.name AS name_2, t0.color AS color_3, t0.share_customer AS share_customer_4, t0.share_order AS share_order_5, t0.share_stock AS share_stock_6, t0.active AS active_7, t0.deleted AS deleted_8 FROM ps_shop_group t0 WHERE t0.active = ?' with params [1]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.color' in 'field list'")." at /home/Domain.com/public_html/src/PrestaShopBundle/Resources/views/Admin/layout.html.twig line 37
```

And when I look further in the Exceptions log, I have this:

```
Twig\Error\
RuntimeError
in [src/PrestaShopBundle/Resources/views/Admin/layout.html.twig](https://Domain.com/admin1/index.php/_profiler/open?_token=lbmtmhZLIRyvqX7tiEkAqcIQxShHkIKxqna7a9ndLOU?file=src/PrestaShopBundle/Resources/views/Admin/layout.html.twig&line=37#line37) (line 37)
    headerTabContent is defined ? headerTabContent : '',    enableSidebar is defined ? enableSidebar : false,    help_link is defined ? help_link : '',    js_router_metadata(),    meta_title is defined ? meta_title : '',    use_regular_h1_structure is defined ? use_regular_h1_structure : true  )  )) %}{% import '@PrestaShop/Admin/macros.html.twig' as ps %}


EntityRepository->findBy(array('active' => true))
in [src/PrestaShopBundle/Controller/Admin/MultistoreController.php](https://Domain.com/admin1/index.php/_profiler/open?_token=lbmtmhZLIRyvqX7tiEkAqcIQxShHkIKxqna7a9ndLOU?file=src/PrestaShopBundle/Controller/Admin/MultistoreController.php&line=93#line93) (line 93)
            $currentContext->setColor('');        }        $groupList = [];        if (!$lockedToAllShopContext) {            $groupList = $this->entityManager->getRepository(ShopGroup::class)->findBy(['active' => true]);        }        $colorBrightnessCalculator = $this->get('prestashop.core.util.color_brightness_calculator');        return $this->render('@PrestaShop/Admin/Multistore/header.html.twig', [
```
             
I'm not sure if you need more info than that:)

**Comment by costads** [comment]
No news?
I had a guy quickly looking at it, and he said 
"In the shop_group table, there is a missing color field"

Do you have a 1.7.8.7 DB backup, so I can compare the tables?

**Comment by costads** [comment]
Another update:)

So I checked my DB for the column 'color' in `ps_shop_group` in PS running 1.7.7.2, and it was there.
After the upgrade to 1.7.8.7 it was not there anymore.

Also, wording, and wording_domain was missing from `ps_tab`.

Now I can load the BO in debug mode, but as soon as I disable debug mode, I get this error again

```
Type error: Return value of PrestaShopBundle\Entity\ShopGroup::getShops() must implement interface Doctrine\Common\Collections\Collection, null returned

[Symfony\Component\Debug\Exception\FatalThrowableError 0]
```


Any idea what is going on?

**Comment by HanaRebaiQA** [comment]
Hello @costads 

Thanks for your feedback. 
I tried to reproduce your issue using an upgrade from 1.7.7.2 to 1.7.8.7. But, i was unable to reproduce it.
I checked when : 

- debug mode = ON and Debug mode = OFF after an upgrade on PS1787 

https://user-images.githubusercontent.com/92912932/187963445-ac32bf4e-b017-4c67-8789-258e983a0d58.mp4

- debug mode = ON and Debug mode = OFF of PS1772 before and after upgrade

https://user-images.githubusercontent.com/92912932/187963519-2e8fd50a-0983-422b-83ec-78ff4967b779.mp4

Could you please check again? Did i miss something ?

Thank You!

**Comment by costads** [comment]
Well, I don't know what is going on.

I just did a manual update, and everything went fine.

In debug mode I can browse around in BO without problems, but as soon as I disable Debug mode, I get this error:

```
Type error: Return value of PrestaShopBundle\Entity\ShopGroup::getShops() must be an instance of Doctrine\Common\Collections\Collection, null returned
[Symfony\Component\Debug\Exception\FatalThrowableError 0]
```

But as debug is off, I can't see what is causing the error.

Do you have any idea how I can debug that error, with debug off?

**Comment by costads** [comment]
Just to add, I can upgrade to all versions up to 1.7.7.8 without any problems.
So something has changed radically somehow for multishop from 1.7.8.0 and up.

**Comment by sLorenzini** [comment]
Hello @costads,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely an issue in your shop.

Don't hesitate to contact our [support](https://www.prestashop-project.org/support/). 
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com/).

We will close this issue.

Thank you

**Comment by costads** [comment]
So I have tested a lot more, and what I found out is that it is running fine in a subfolder like this:
Domain.com/ps1787/

But as soon as it is moved to the root of the domain, I get that error i described from the beginning in this thread.

**Comment by samilmarekrygula** [comment]
> Just to add, I can upgrade to all versions up to 1.7.7.8 without any problems. So something has changed radically somehow for multishop from 1.7.8.0 and up.

I have exactly the same issue. Did someone find a solution ?
