### ISSUE TITLE
Duplicar este modulo con el nombre de billetera digital

### ISSUE THREAD

**Issue by yfbetancourth** [PrestaShop/PrestaShop#29461]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

este modulo funciona bien, de la misma manera se puede hacer funcionar con las propiedades de billetera digital.

### Describe the solution you'd like

este modulo funciona bien, de la misma manera se puede hacer funcionar con las propiedades de billetera digital., seria bueno que se puedan adicionar los logos para respectivas billeteras digital, que se puedan adicionar varias billeteras con su respectivo logo

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by sLorenzini** [comment]
Hello @yfbetancourth,

Please send your request in English. English is the norm on GitHub.
Furthermore, you need to be more specific on the description of your feature, with some screenshots/screenrecords added, version of the module, name of the module etc..

Thank you

**Comment by hibatallahAouadni** [comment]
Hello @yfbetancourth 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report and please send your request in English. English is the norm on GitHub.**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thank you
