### ISSUE TITLE
BO - "Combine several attribute" Input Box is cutting text 

### ISSUE THREAD

**Issue by slupostrupek** [PrestaShop/PrestaShop#29460]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

"Combine several attribute" Input Box is cutting text - Admin Back Office

See screenshot
![cutted](https://user-images.githubusercontent.com/9866119/187040562-303c35b2-8995-4860-bec6-484eab31cf91.jpg)

### Expected behavior

Text should not be truncated, see 1.7.7.8 display below

![1778-combinations](https://user-images.githubusercontent.com/2854834/187162424-bbc722de-c8f1-4e80-8697-366ef42e0a77.png)

### Steps to reproduce

1. Go to Back Office, go to page Product Catalog
2. Click on a Product, this will bring you to 'Edit a product' Back-office page
3. Go to Combinations tab
4. See the input contains the truncated text.

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.2

**Comment by sLorenzini** [comment]
Hello @slupostrupek ,

I reproduce the issue with PrestaShop version 1.7.8.0 & 1.7.8.7.

![1787-combinations](https://user-images.githubusercontent.com/2854834/187161985-6ace6333-25ce-487a-ac76-27cbf1a60a50.png)

However, it worked on 1.7.7.8 version. It's a regression. 

![1778-combinations](https://user-images.githubusercontent.com/2854834/187162424-bbc722de-c8f1-4e80-8697-366ef42e0a77.png)

I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by matks** [comment]
@lartist takes it
