### ISSUE TITLE
FO - An exception is displayed in the FO when the "Use Cache" & "debug mode" are enabled

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#29477]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The FO is totally broken after enabling  "Use Cache" & "debug mode" 
![image](https://user-images.githubusercontent.com/16067358/187434081-c71cf123-9050-493e-aab9-fe5ccb804774.png)

### Steps to reproduce

Install APC on your server
```php
>pecl install apcu
>nano /usr/local/etc/php/php.ini
>>extension=apcu.so
>>apc.enable_cli=1
>>apc.enable=1
```

1. Go to BO > Advanced Parameters > Performance > Enable debug mode
2. Enable "Use Cache"
3. Select "CacheApc"
4. Save
5. View my shop
6. See exception

I tried with PS1787 and PS1786 => ok

### PrestaShop version(s) where the bug happened

8.0.0 beta

### PHP version(s) where the bug happened

7.4, 8.1

**Comment by atomiix** [comment]
Fixed by #29484
