### ISSUE TITLE
Wrong assets loaded when server remote and CDN defined

### ISSUE THREAD

**Issue by Kandax86** [PrestaShop/PrestaShop#29478]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,
i noticed when i register external assets in yml and when i enable a CDN media server the file path becomes wrong and the resource loaded in page source is just the cdn domain.

I succeded to make it work with this code in an FrontController Override.

```php
class FrontController extends FrontControllerCore{
	public function registerStylesheet($id, $relativePath, $params = [])
    {
        if (!is_array($params)) {
            $params = [];
        }

        $default_params = [
            'media' => AbstractAssetManager::DEFAULT_MEDIA,
            'priority' => AbstractAssetManager::DEFAULT_PRIORITY,
            'inline' => false,
            'server' => 'local',
            'version' => null,
            'needRtl' => true,
        ];
        $params = array_merge($default_params, $params);

        if (Tools::hasMediaServer() && !Configuration::get('PS_CSS_THEME_CACHE') && $params['server']!='remote') {
			$file = ($this->stylesheetManager->getFullPath($relativePath) ?? $relativePath);
			if(!$file){
				return;
			}
            $relativePath = Tools::getCurrentUrlProtocolPrefix() . Tools::getMediaServer($relativePath)
                . $file;
            $params['server'] = 'remote';
        }

        $this->stylesheetManager->register($id, $relativePath, $params['media'], $params['priority'], $params['inline'], $params['server'], $params['needRtl'], $params['version']);
    }
}
```

- i added $params['server'] != 'remote' check to keep the external resources
- i added a check on the returned file (if empty or file not exists) to prevent display of empty <link> tag in source.

### Expected behavior

It should be the original external resource in the link source tag in html

### Steps to reproduce

1. Go to yml
2. insert and external css with server: remote option
3. Add a CDN domain in performances
4. Load the page and look at source
5. you will have number of fake <link> tags with only the cdn domain and external css are not in source

### PrestaShop version(s) where the bug happened

8.0

### PHP version(s) where the bug happened

8.0

**Comment by florine2623** [comment]
Hello @Kandax86 ,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by atomiix** [comment]
Hi @Kandax86, I'm not sure to understand steps 1 & 2. What do you mean by `insert and external css with server: remote option`?

**Comment by Kandax86** [comment]
I want to say in theme.yml, i want to add an external css from cdn or other with the option server: remote

```
assets:
  css:
    all:
      - id: custom-lib-style
        path: //link.to.my.externalresource/file.css
        server: remote

```

**Comment by atomiix** [comment]
@Kandax86 I'm not able to reproduce the issue, here's what I've done:

Setting a media server:
<img width="599" alt="Capture d’écran 2022-08-31 à 11 30 12" src="https://user-images.githubusercontent.com/2168836/187648130-801bf421-e192-46eb-8ff8-7850bbd129c6.png">

Adding an external asset for the theme:
<img width="736" alt="Capture d’écran 2022-08-31 à 11 30 31" src="https://user-images.githubusercontent.com/2168836/187648202-945c8ecb-a749-4087-9bdb-670b03199c54.png">

And here are the results:

The external css is well added:
<img width="978" alt="Capture d’écran 2022-08-31 à 11 31 12" src="https://user-images.githubusercontent.com/2168836/187648310-618a9170-70ec-4734-8a52-588b0298bb64.png">

I've got 58 occurences of `cdn.localhost`
<img width="1012" alt="Capture d’écran 2022-08-31 à 11 32 46" src="https://user-images.githubusercontent.com/2168836/187648401-ca927ea8-62ee-4624-8487-b6815fe7944c.png">

33 with `/prestashop-dev` following the domain
<img width="1014" alt="Capture d’écran 2022-08-31 à 11 33 20" src="https://user-images.githubusercontent.com/2168836/187648456-2ff75637-137a-4205-9db9-c0a4b55768b6.png">

25 with `\/prestashop-dev` following the domain (the `\` is for the json escape)
<img width="1016" alt="Capture d’écran 2022-08-31 à 11 33 43" src="https://user-images.githubusercontent.com/2168836/187648633-bb06b41b-9ecc-4792-95cb-1e8cded0477b.png">

33 + 25 = 58 so in my case I don't have only the cdn domain. Am I missing something?

**Comment by Kandax86** [comment]
By my side it's printing

```
    <link rel="stylesheet" href="https://cdn.mycdn.com/themes/classic/assets/css/theme.css" type="text/css" media="all">
  <link rel="stylesheet" href="https://cdn.mycdn.com/modules/blockreassurance/views/dist/front.css" type="text/css" media="all">
  <link rel="stylesheet" href="https://cdn.mycdn.com" type="text/css" media="all">
  <link rel="stylesheet" href="https://cdn.mycdn.com/modules/ps_searchbar/ps_searchbar.css" type="text/css" media="all">
  <link rel="stylesheet" href="https://cdn.mycdn.com/modules/productcomments/views/css/productcomments.css" type="text/css" media="all">
  <link rel="stylesheet" href="https://cdn.mycdn.com" type="text/css" media="all">
  <link rel="stylesheet" href="https://cdn.mycdn.com/js/jquery/ui/themes/base/minified/jquery-ui.min.css" type="text/css" media="all">
  <link rel="stylesheet" href="https://cdn.mycdn.com/js/jquery/ui/themes/base/minified/jquery.ui.theme.min.css" type="text/css" media="all">
  <link rel="stylesheet" href="https://cdn.mycdn.com/modules/blockwishlist/public/wishlist.css" type="text/css" media="all">
  <link rel="stylesheet" href="https://cdn.mycdn.com/modules/ps_imageslider/css/homeslider.css" type="text/css" media="all">
  <link rel="stylesheet" href="https://cdn.mycdn.com" type="text/css" media="all">

```

And as you can see, some are juste targetting the website root url if the resource file is empty or not found.
and for external css too....

you can try with this resource :  
`//fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300;400;700&family=Oswald:wght@200;400;600&display=swap`


The thing i don't understand is why you want to validate this condition for external resources since those resources are not hosted by our own server.

```
if (Tools::hasMediaServer() && !Configuration::get('PS_CSS_THEME_CACHE')) {
            $relativePath = Tools::getCurrentUrlProtocolPrefix() . Tools::getMediaServer($relativePath)
                . ($this->stylesheetManager->getFullPath($relativePath) ?? $relativePath);
            $params['server'] = 'remote';
}
```
In my point of view, the external resources do not need to be rewriten by cnd url.

**Comment by mihaimatei** [comment]
I've been able to replicate this issue also on PrestaShop 1.7.8.9.

Steps to reproduce:
1. edit `themes/classic/config/theme.yml` and add a remote css asset:
```
  css:
    all:
      - id: custom-lib-style
        path: //filesamples.com/samples/code/css/sample3.css
        server: remote
```
2. remove theme config so theme.yml is reparsed (removed `config/themes/classic/shop1.json`)
3. set Media Server 1 to a CDN
4. load homepage and observe rendered page source contains two links to defined media server 1 root, instead of a proper link to the remote asset:
```
  <link rel="stylesheet" href="https://mypresta.cdn.imgeng.in" type="text/css" media="all">
    <link rel="stylesheet" href="https://mypresta.cdn.imgeng.in" type="text/css" media="all">
```

5. remove Media Server 1 and reload homepage, notice the correct link to the remote asset is present:
```
  <link rel="stylesheet" href="//filesamples.com/samples/code/css/sample3.css" type="text/css" media="all">
```

**Comment by hibatallahAouadni** [comment]
Hello @Kandax86 

Do you still encounter the same issue with 8.1.x? Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Kandax86 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
