### ISSUE TITLE
[Cart Rules] - the discount isn't Highlighted 

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#29474]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you create a cart rule that should be higlighted on the checkout, it will not be display as you can see on this video : 

https://user-images.githubusercontent.com/100699445/187411344-a1214a76-9e5d-4455-854a-10605476fefd.mp4

### Expected behavior

The cart rule should be highlighted like this : 
![image](https://user-images.githubusercontent.com/100699445/187411484-5c033a70-8edb-49f0-aa0e-1ec5580072fa.png)

### Steps to reproduce

1. Go to BO > Catalog > Discounts 
2. Clic on  " + Add new cart rules "
3. Set the name
4. Generate a code 
5. Enable "Highlight"
6. Go to Actions Tab and Apply a discount "Amount"
7. Set the Amount and Save the Cart rule 
8. Go to Fo and add a product to the Cart 
9. Go to your Cart 
10. You didn't see the Highlighted Promo code  -> X

### PrestaShop version(s) where the bug happened

Beta 8.0.0

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment]
Hello @AureRita ,

I can't reproduce your bug using beta 8 version.
After following your steps, here's what I have.

<img width="914" alt="Screenshot 2022-08-30 at 13 44 26" src="https://user-images.githubusercontent.com/16019289/187428284-301d3325-a140-413b-b725-f172493650e9.png">

| In my cart  | After I used my discount |
| ------------- | ------------- |
| <img width="346" alt="Screenshot 2022-08-30 at 13 44 36" src="https://user-images.githubusercontent.com/16019289/187428295-8e33aa86-cd7c-403c-856c-6a800dd5da9b.png">  | <img width="347" alt="Screenshot 2022-08-30 at 13 44 44" src="https://user-images.githubusercontent.com/16019289/187428309-a7c1bddd-4e60-41ff-8079-734785edd149.png">  |

I also tested it with multistore enabled (with and without shop) and disabled.

**Comment by florine2623** [comment]
@PrestaShop/qa-functional can someone try to reproduce this issue on beta 8 ? ^^

Thanks !

**Comment by hibatallahAouadni** [comment]
Hello @AureRita 

I didn't manage to reproduce the issue with 8.0.0 Beta, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/187640539-c3eccd58-8e62-4a09-ac21-593f690186fc.mp4

Please check and feedback.

Thanks!

**Comment by AureRita** [comment]
Hi @hibatallahAouadni and @florine2623, 

After a retry with this new day, I see that it's a duplicate of https://github.com/PrestaShop/PrestaShop/issues/25199

Thank you for your time

**Comment by AureRita** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/25199

**Comment by pollat** [comment]
This problem happen because prestashop "Highlits" coupon feature follow GMT Universal time, so your coupon alert take some hours to be displayed on your website: to solve this problem, set coupon "start time" to yesterday.
