### ISSUE TITLE
Customer Reassurance 5.1.1 does not work correctly with multishop

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#29476]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

With the latest update for Customer Reassurance block I noticed that if you create a new reassurance this is not saved over all stores. In previous case this was the case.

Second issue:

After a reassurance is created and you want to update this, all data is erased and you need to enter all data again.

### Expected behavior

I expect that if a  reassurance is created in the ALL SHOPS tab, all stores are effected

I expect that when a reassurance is updated, previous data is not erased.

Previous version did not have these issues.

### Steps to reproduce

1 - Makes sure the customer reassurance block is.

2 - Create a new reassurance in ALL SHOPS, then check if this available in the other stores.

3 - Try to edit the reassurance, all fields should be blank.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

customer reassurance 5.1.1

**Comment by florine2623** [comment]
Hello @01park ,

I can't reproduce your issue using the same version as you on PS 1.7.8.7 and 8.0.x.
<img width="733" alt="Screenshot 2022-08-30 at 15 50 20" src="https://user-images.githubusercontent.com/16019289/187455662-e1412bbb-2350-4e47-9435-b2e90a678ffe.png">

On my multistore, in BO and FO, the new reassurance block is displayed.
<img width="409" alt="Screenshot 2022-08-30 at 15 51 09" src="https://user-images.githubusercontent.com/16019289/187455623-e80e3d09-2593-4a28-bd31-95bfa01addd7.png">
<img width="989" alt="Screenshot 2022-08-30 at 15 55 54" src="https://user-images.githubusercontent.com/16019289/187456003-c9c9cf16-8241-476e-aeb7-1d3e40f2500a.png">

And I can update it without the data being erased.

Did you check all languages ?
Can you send a screenshot of your issue ?
Thanks!

**Comment by 01park** [comment]
Hi,

I tested it again by removing all and reinstalling the module.

Things are working good now.

**Comment by AureRita** [comment]
Hi @01park ,

Because of non reproductibility, 

I close this issue
