### ISSUE TITLE
BO - Product V2 - No validation while uploading product image more than defined size limit.

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#29480]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In product V2, there is no validation while uploading product images more than the defined size limit.

### Expected behavior

With Product V1, we have an alert 
![image](https://user-images.githubusercontent.com/16067358/187472958-a4b56e08-ba16-46ea-a093-28e38ef99280.png)

### Steps to reproduce

1. Go to BO > Advanced parameters > Administration page
2. Change the product image upload size limit = 1M & save
![image](https://user-images.githubusercontent.com/16067358/187472411-044424b4-fc06-49e4-8f31-8a406e835bc9.png)
3. Go to BO > Advanced Parameters > Experimental features page(1.7.8.7) or New & Experimental Features page(8.0.0)
4. Enable product V2
5. Go to BO > Catalog > Product V2 > Upload an image with size > 1M
6. No validation is displayed

### Technical hints

- The image JS component is handled by a mini Vue app which code is mostly here https://github.com/PrestaShop/PrestaShop/tree/0a19547a532514f3b3c096f1e8a2ec87e379faf6/admin-dev/themes/new-theme/js/pages/product/components/dropzone for the interface
- It relies on TypeScript services which should all be located here https://github.com/PrestaShop/PrestaShop/blob/0a19547a532514f3b3c096f1e8a2ec87e379faf6/admin-dev/themes/new-theme/js/pages/product/services/images.ts
- For the server side you'll find the controller here https://github.com/PrestaShop/PrestaShop/blob/ff96226eae149d58b34ca6c5228b846595d05914/src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ImageController.php#L52
- It is based on [CQRS actions for images](https://github.com/PrestaShop/PrestaShop/tree/db03dbd7765a00b7fd5d892fff7891e796fdcaf7/src/Core/Domain/Product/Image) which [handlers are found here](https://github.com/PrestaShop/PrestaShop/tree/8.0.x/src/Adapter/Product/Image/CommandHandler)

### PrestaShop version(s) where the bug happened

1.7.8.7, 8.0.0beta

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @khouloudbelguith ,

I can confirm your issue.
I don't have any alert regarding the size of the picture when I try to upload a picture bigger than the Maximum size for a product's image on Product Page V2. 
I have an alert regarding my server:
<img width="803" alt="Screenshot 2022-08-30 at 18 07 58" src="https://user-images.githubusercontent.com/16019289/187490341-504e49a4-2534-41c0-af23-6c0f13cdfc66.png">

After switching the Experimental page to V1, I have the alert:
<img width="890" alt="Screenshot 2022-08-30 at 18 24 30" src="https://user-images.githubusercontent.com/16019289/187490042-42ca371e-ec72-450d-94b3-297ae4ee2b32.png">
