### ISSUE TITLE
Pass the field submitLogin inside the formFields instead of adding it inside template

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#29487]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

We can see that there is an hidden field (https://github.com/PrestaShop/classic-theme/blob/develop/templates/customer/_partials/login-form.tpl#L50) on the authentification step adding into a template and required by the core.

If the theme doesn't handle it, it will never log the customer.

### Describe the solution you'd like

As the form is generated with the `formFields` var, we could surely add this field into it.

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by AureRita** [comment]
Hi @PrestaEdit  ,

Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments. 

We're waiting for your PR :rocket: 

Thank you

**Comment by kpodemski** [comment]
@AureRita 

I can validate this suggestion. It makes sense. Could you add proper labels?
