### ISSUE TITLE
When uninstalling a module where a hook is deleted from the hook table (foreign key remains in different table), fatal errors occur.

### ISSUE THREAD

**Issue by dmg-leusden** [PrestaShop/PrestaShop#29483]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When running `php install/upgrade/upgrade.php` I got the following fatal error in my syslog:

```
[30-Aug-2022 17:26:21 Europe/Paris] PHP Fatal error:  Uncaught PrestaShopObjectNotFoundException: The hook id #1 does not exist in database in <root>\classes\Hook.php:242
Stack trace:
#0 <root>\classes\Hook.php(677): HookCore::getNameById(1)
#1 <root>\classes\module\Module.php(1029): HookCore::unregisterHook(Object(BankWire), 1, NULL)
#2 <root>\classes\module\Module.php(733): ModuleCore->unregisterHook(1)
#3 <root>\classes\PaymentModule.php(92): ModuleCore->uninstall()
#4 <root>\modules\bankwire\bankwire.php(91): PaymentModuleCore->uninstall()
#5 <root>\src\Adapter\Module\Module.php(269): BankWire->uninstall()
#6 <root>\src\PrestaShopBundle\Install\Upgrade.php(565): PrestaShop\PrestaShop\Adapter\Module\Module->onUninstall()
#7 <root>\src\PrestaShopBundle\Install\Upgrade.php(820): PrestaShopBundle\Install\Upgrade->disableIncompatibleModules()
#8 <root>\install\upgrade\upgrade.php(93): PrestaShopBundle\Install\Upgrade->run()
#9 {main}
  thrown in <root>\classes\Hook.php on line 242
```

Now obviously bankwire is a module that shouldn't be installed in 1.7.*. But for this instance, it was...

Bankwire is listed in the `module` table like: id_module:97, name:bankwire, active:1, version:1.1.2
When i query 97 in table `hook_module` I get 1 and 4. In the table `hook` I can find 4, but not 1. So that explains the exception. Hook with id_hook 1 is referenced in `module_hook`, but now the name of the hook can't be found.

But only id_hook 4 exists in table hook. So, yeah... Somehow (this prestashop db exists since 2012) hook with id 1 got deleted from the database and that's why the module couldn't be uninstalled. 

### Expected behavior

Uninstallation of the affected module, without any fatal errors.

### Steps to reproduce

Remove a row from the table `hook` for some module, and then try to uninstall that module.

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

bankwire

**Comment by dmg-leusden** [comment]
Possible fix, by wrapping unregisterHook with a try/catch in Module::uninstall:

```php
    public function uninstall()
    {
        // some code

        // Retrieve hooks used by the module
        $sql = 'SELECT DISTINCT(`id_hook`) FROM `' . _DB_PREFIX_ . 'hook_module` WHERE `id_module` = ' . (int) $this->id;
        $result = Db::getInstance()->executeS($sql);
        foreach ($result as $row) {
            try{
                $this->unregisterHook((int) $row['id_hook']);
            } catch (\PrestaShopObjectNotFoundException $e) {
                // hook does not exist and doesnt need to be unregistered.
            }
            $this->unregisterExceptions((int) $row['id_hook']);
        }

        // more code
    }
```
I don't know if there are any side effects however.

**Comment by AureRita** [comment]
Hi @dmg-leusden ,

I reproduce the issue with PrestaShop version 1.7.7.8, I'll add this to the backlog so it can be fixed.
You can see the issue on this video : 

https://user-images.githubusercontent.com/100699445/187690150-554950ab-6d9a-44db-8a56-8ac01a2ee193.mp4

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

I think with your resolution you can maybe push it to the PR :rocket: 

Thanks

**Comment by Hlavtox** [comment]
Real world easy scenario to reproduce. Imagine this is a blog module.
1. Install [gsitemap](https://github.com/PrestaShop/gsitemap) native module. It adds a new hook `gSitemapAppendUrls`.
2. Install this [tox_hooktest.zip](https://github.com/PrestaShop/PrestaShop/files/12498038/tox_hooktest.zip), it hooks itself to `gSitemapAppendUrls`.
3. Uninstall gsitemap - it removes `gSitemapAppendUrls`.
4. Try to uninstall the test module - `Cannot Uninstall module tox_hooktest. The hook id #405 does not exist in database.`

**Comment by Hlavtox** [comment]
@PrestaShop/qa-functional fixed
