### ISSUE TITLE
BO - credit-slips - An exception is displayed when downloading a credit slip with deleted product

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#29495]
## Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

## Describe the bug and add screenshots

In the BO > Orders > Credit slips page on PrestaShop 8.0.0, an exception is displayed when downloading a credit slip with a deleted product

![image](https://user-images.githubusercontent.com/16067358/187721189-7277cc31-3955-4f4a-813b-2ebc81261050.png)

_Important: I didn't reproduce the issue with php7.2, thanks @hibatallahAouadni_

## Expected behavior

The expected behavior is the behavior from PrestaShop 1.7.8.7

I checked with PrestaShop 1787 with php7.2 : behavior is correct.

### If the credit slip has only one product that has already been deleted from the order details, this is the display
![image](https://user-images.githubusercontent.com/16067358/187721921-1caec1b0-5c7b-442c-b6e2-aec94d3e38ad.png)

### If the credit has more than one product

####Before deleting the product
![image](https://user-images.githubusercontent.com/16067358/187723215-e18d0af1-ec78-4e57-afed-5b271b802ac7.png)

#### Then if you delete a product from the order details it now looks like this
![image](https://user-images.githubusercontent.com/16067358/187723303-b03f1770-3504-4b54-8302-210c01e39eaa.png)

## Steps to reproduce

1. Enable debug mode
2. Create an order from the BO or FO
3. Go to backoffice page BO > Orders > View to look at the order you just created
4. Change the order status to 'payment: accepted', this validates the order
5. Click on 'Partial refund' button and use the interface to 'return the product': this simulates an order where a user is not satisfied with product and returns the sold product, and prestashop creates a refund
6. From the order page, **remove the product** from the order details page 

![image](https://user-images.githubusercontent.com/16067358/187726147-170e1b65-c9bf-4102-b384-d3b523448bf1.png)

7. Go to backoffice page BO > Orders > Credit slips page
8. Click on "Download Credit slip" for the order
9. See error: exception message

![image](https://user-images.githubusercontent.com/16067358/187725640-ed07682f-e760-4c0c-a7cf-ecb4a51ab723.png)

10. Click on "Generate PDF file by date"
11. See exception 

## PrestaShop version(s) where the bug happened

8.0.0beta, 1787

### PHP version(s) where the bug happened

7.4, 8.0

**Comment by HanaRebaiQA** [comment]
Hello @khouloudbelguith 

Thanks for your report.

I did manage to reproduce your issue with **8.0.0 beta** using **php8.0** and **php7.4** versions and on **PS1787** with **php7.4**.
While, i didn't reproduce it with php7.3. Indeed, i confirm it's a regression.

**8.0.0 with php 8.0 : NOK** :x: 

https://user-images.githubusercontent.com/92912932/187887756-5b88b057-fdcb-405e-9769-e32fc8149060.mp4


**8.0.0 with php 7.4 : NOK** :x: 


https://user-images.githubusercontent.com/92912932/187887777-c23702dc-5313-4231-ad4f-e0a7a194aa94.mp4

**1787 with php 7.4 : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/187893402-adfbb10e-b2dd-4a68-a652-097c5182323e.png)


**8.0.0 with php 7.3 : OK** :heavy_check_mark: 


https://user-images.githubusercontent.com/92912932/187887829-4f3e5b05-0f79-474d-8c7e-ad356974b1b5.mp4

Thank You!

**Comment by matks** [comment]
Assigned to @nicosomb

**Comment by nicosomb** [comment]
I think that we can close this issue 😊
