### ISSUE TITLE
Front office breadcrumb trail does not display child of disabled parent

### ISSUE THREAD

**Issue by haveyougotanypets** [PrestaShop/PrestaShop#29496]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Take an example category hierarchy:

**Home** > **Type** > **Bags** > **Tote Bag**

1. If  all categories are enabled and the user browses to category **Tote Bag** the breadcrumb trail is shown as:
   * _Home / Type / Bags / Tote Bags_

2. If the category **Type** is disabled and the user browses again to the category **Tote Bag**  the breadcrumb trail is shown as :
   * _Home / Bags / Tote Bags_
   * The **Type** category removed as it is disabled, all other categories remain. This is expected.

3. If the category **Type** remains disabled and the user now browses to the category **Bags** the breadcrumb trail is shown as:
   * _Home_
   * This is unexpected as you would expect the breadcrumb to read:
   * _Home / Bags_
   * The child (**Bags**) of the disabled parent (**Type**) has also been removed from the breadcrumb even though it is still active. 

4. If all categories are re-enable and now the category **Bags** disabled. If the user browses to the  **Tote Bag** category the trail is shown as 
   * _Home / Type_
   * Again the child of the disabled parent has also been removed even though it is still active.

### Expected behavior

If a category is disabled, only that category should be removed from the breadcrumb hierarchy and not it's child.

* Note the child's child remains in point 2. It is not the entire branch that is cut, only the parents child.

### Steps to reproduce

Setup the category structure as shown above and follow the steps shown

Note: 
* MYSQL version: 8.0.30-0ubuntu0.20.04.2 
* Apache webserver

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.30

**Comment by HanaRebaiQA** [comment]
Hello @haveyougotanypets 

Thanks for your report. 
Is your issue similar to these ones : [#28864](https://github.com/PrestaShop/PrestaShop/issues/28864) , [#23530](https://github.com/PrestaShop/PrestaShop/issues/23530) , [#20946](https://github.com/PrestaShop/PrestaShop/issues/20946)  ?

We are waiting for your feedback!
Thank you!

**Comment by haveyougotanypets** [comment]
HI @HanaRebaiQA 

No it is not the same as any of these bugs.

**Comment by Hlavtox** [comment]
I am thinking if it's even correct to allow disabling a parent category with active children... 🤔

**Comment by haveyougotanypets** [comment]
I think it is valid to be able to disable parent categories with active children

The use case I have above is that the **Type** category is used purely for organisation purposes in the back end. This is very useful. By disabling it the end user does not see it but it allows us to organise our categories and products in a much more orderly fashion.

**Comment by hibatallahAouadni** [comment]
Hello @haveyougotanypets 

I reproduce the issue with PS1786 and I didn't reproduce the issue with PS1778 cause we use to encounter another behavior (see this issue #24370).
Thanks for reporting the issue! I’ll add this to the debug backlog so that it’s fixed :wink: 

https://user-images.githubusercontent.com/23308427/188489230-be012c52-7e4b-4b7d-8624-57bf84ba0bd6.mp4

Fortunately, it has been fixed with PS8.0.0_beta, see the atatched screenshot below:

![image](https://user-images.githubusercontent.com/23308427/188489812-32e8974d-b49c-4306-8a24-256ba25b1527.png)

Thank you
