### ISSUE TITLE
[Multistore] Combination product - Availability preferences is not saved correctly on all shops

### ISSUE THREAD

**Issue by sLorenzini** [PrestaShop/PrestaShop#29506]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you're on multistore, with "all shop" tab, if you want to modify the availability preferences with a combination product, it doesn't change anything on the other stores than the main one. 
The default behavior is always selected and in FO we don't have the change on all shops. See my screenrecord:

https://user-images.githubusercontent.com/2854834/187948332-17e1dcca-ed2c-4789-b440-a1727446d32d.mp4

Looks like this [issue](https://github.com/PrestaShop/PrestaShop/issues/28998) with specific delivery time.
Tested on 1.7.8.x & 8.0.x branches. Same error. No regression

### Expected behavior

The availability preference with a combination product should be changed with all my shop at the same time

### Steps to reproduce

1. Go to BO > Shop Parameters > General
2. Scroll down to enable Multistore
3. Go to Advanced Parameters > Multistore
4. Click on Add new shop
5. Set up your new shop
6. Set up its url
7. Go to Catalog > Product
8. Select a product with combinations on it
9. Go to Combinations tab
10. Scroll Down, Click on "Allow orders" radio for example
11. Set up the text of "Label when in stock" and "Label when out of stock (and back order allowed)"
12. Save the product
13. Change your store and go to the main one > No error, the choice is good
14. Change and choose the store you created > See the error, Default availability preferences is still selected
15. Go to FO of the two stores > Choose the product you have edited > on the main store you have the good selection, on the other nothing change

### PrestaShop version(s) where the bug happened

1.7.8.x / 8.0.x / 1.7.7.8

### PHP version(s) where the bug happened

7.3

**Comment by HanaRebaiQA** [comment]
Hello @sLorenzini 

Thanks for your report.
I was able to reproduce your issue with 8.0.0 beta with Product V1 and Product V2.

**8.0.0 beta with Product V1 : NOK** :x:  

https://user-images.githubusercontent.com/92912932/187971604-c96d28ff-08d2-461a-ad68-8376a3045fb6.mp4


**8.0.0 beta with Product V2 : NOK** :x: 

https://user-images.githubusercontent.com/92912932/187971597-ca25079b-5922-448e-bcf4-e4a684ea9af3.mp4



Also, i checked with PS1778, it's NOK. So, it's not a regression

https://user-images.githubusercontent.com/92912932/187971622-5d566e59-d11b-452c-aeba-3ae5338fd8a9.mp4


**PS1778 : NOK** :x:  


https://user-images.githubusercontent.com/92912932/187970862-c398f819-fe87-420e-9fe3-7ee97377bc47.mp4

Thank You!

**Comment by florine2623** [comment]
This issue is fixed in PS 9.0.0 :

https://github.com/user-attachments/assets/bbadf63c-26e9-45c9-8843-8fa000d477dd

I'm closing the issue to avoid clogging the backlog.
