### ISSUE TITLE
Install PrestaShop fail on module Step

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShop/PrestaShop#29501]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An error occurred if trying to install PrestaShop

1.7.8.x : 
![image](https://user-images.githubusercontent.com/48441421/187890448-c3ee0fe7-670b-4e98-b7d9-8ed7e5de0afb.png)
8.0.x : 
![image](https://user-images.githubusercontent.com/48441421/187890494-c9d8af13-b1a0-4127-9b5f-5b6e69c54db8.png)

### Expected behavior

No errors in this page

### Steps to reproduce

1. Clone the repo
2.  Checkout 1.7.8.x or 8.0.x
3. Disable Debug mode on `config/defines.inc.php` `define('_PS_MODE_DEV_', false);`
4. `make install`
5. Go to installation page and fill up all forms (lang = french)
6. Start installation
7. See error in description

### PrestaShop version(s) where the bug happened

1.7.8.x - 8.0.x

### PHP version(s) where the bug happened

All

### If your bug is related to a module, specify its name and its version

no module

**Comment by HanaRebaiQA** [comment]
Hello @boubkerbribri 

Thanks for reporting the issue.
I was unable to reproduce your issue using the same steps to install `8.0.x` and `1.7.8.x`

Here is the steps : 

1. Clone the repo PrestaShop using `git clone git@github.com:PrestaShop/PrestaShop.git`
2. Checkout 1.7.8.x (for install 1.7.8.x)
3. Checkout 8.0.x (for install 8.0.x)
4. Make install
5. Go to installation page and fill up all forms
6. Start installation

**For 8.0.x : OK** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/187940082-8ab09bcb-46b1-4120-a9d9-d3245023402e.png)


**For 1.7.8.x : OK** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/187940060-e426b84b-6779-440b-845d-5a1d61c801b4.png)


Could you please check again ?

Thank You!

**Comment by boubkerbribri** [comment]
I just updated the description to add 2 steps to reproduce : 
- debug mode = Off
- Install lang : FR

**Comment by HanaRebaiQA** [comment]
Hello @boubkerbribri 

Yes. As you mentioned, i have cleared all caches using `git clean -xfd` and delete cache under` var/cache` 
Also, i checked when `debug mode = False` and `Install Lang = FR`, but i couldn't reproduce it. 

![image](https://user-images.githubusercontent.com/92912932/187954883-74774197-5fd3-4857-8f55-6762a0476e97.png)


https://user-images.githubusercontent.com/92912932/187954927-95077ac9-f4cd-42e8-b075-32fddcf9e706.mp4

Did i miss something ?

Thank You!

**Comment by boubkerbribri** [comment]
Fixed with 2 pull request made by atomiix
