### ISSUE TITLE
[Module Manager] - In the update tab, the button "update all" didn't works 

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#29517]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I go to BO > Module Manager, Update tab, when I press on the Update all button, in the first time we have only one module that is updated and after that will not update any modules, 

You can see it on this video : 

https://user-images.githubusercontent.com/100699445/188165375-de86f893-9b9e-4c12-aacd-0fa9e671b76c.mp4

For your information, this issue was mentioned on this commentary : 
https://github.com/PrestaShop/ps_distributionapiclient/pull/6#pullrequestreview-1062265091

### Expected behavior

I wish I can update all module when I press this button.

### Technical precision

In the previous module manager in 178, this feature worked, but there is a "Cache clear" problem to keep in mind. By default after an action on a module the cache is always cleared. The problem is that when you perform upgrade (so partially install) on multiple modules, the cache will be cleared after each upgrade request.

This leads to a very slow process, so previous ly we had a parameter `cacheClearEnabled` that allows to disable this cache clear on the first calls, and enabled it only on the last call. This feature was removed from the ModuleManager in 8.0 and should be implemented.

Here's an example of the partial code that implemented this in 178 (it doesn't mean it must be implemented this way, it's just a lead, but the idea is that the clear cache should be optional - enabled by default):
https://github.com/PrestaShop/PrestaShop/blob/a21198c3d6a8e1a25d6de1a8e378a052906eeb0f/src/Core/Addon/Module/ModuleManager.php#L692-L697

## Tech investigation 
Only clear the cache for last the upgrade module

### Steps to reproduce

1. Go to BO
2. Go to Modules > Module Manager
3. Go to the update tab
4. Clic on "Update All" button 
5. There is no update 

### PrestaShop version(s) where the bug happened

8.0.0 Beta 

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Hello @AureRita 

I reproduce the issue only with PS800_beta, the stranger behavior is:

1. at first, I see in the list two modules to upgrade, **Customer "Sign in" link** and **Product Comments**. I click on the **upgrade all** button, then the **Customer "Sign in" link** has been upgraded but the other module doesn't :disappointed: 
2. I refresh the page, and I can't see the upgrade all button, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/188172879-21ea480f-15e9-4978-a2ef-2bb36aa60d4b.png)

It's a regression! I will add it to the Backlog to be fixed.

Thanks!

**Comment by AureRita** [comment]
Hi @hibatallahAouadni 

The button is maybe disabled because you've only one module to update, test with two modules ;)

**Comment by mflasquin** [comment]
Hi @AureRita do you still reproduce the issue ?

**Comment by AureRita** [comment]
Hi @mflasquin, 

I tried to reproduce this issue on the 8.0.x branch, as you can see, I can't reproduce it anymore. 

https://user-images.githubusercontent.com/100699445/190977777-365ffd68-53c4-480c-ae04-4ca3081d4d77.mp4

Thank for your question

**Comment by mflasquin** [comment]
Hi, @AureRita, this PR https://github.com/PrestaShop/PrestaShop/pull/29512 fix the upgrade all button issue.
I will check to find a solution to clear the cache after the last upgraded module.
