### ISSUE TITLE
GDPR module - If there is only one module using the GDPR hook, it is ignored

### ISSUE THREAD

**Issue by rsoulard-prolaser** [PrestaShop/PrestaShop#29513]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If there is only one module using the GDPR hook:
![Capture d’écran du 2022-09-02 11-17-05](https://user-images.githubusercontent.com/78790947/188107454-70444707-72e3-4602-bd3d-aae52a28ae42.png)

It is ignored
![Capture d’écran du 2022-09-02 11-23-09](https://user-images.githubusercontent.com/78790947/188108492-c75836e4-2a37-461c-a562-41c3b40a1c61.png)

### Steps to reproduce

1. Uninstall psgdpr module
2. Install only one module using the GDPR hook like contactform
3. Install psgdpr module

### PrestaShop version(s) where the bug happened

all

### If your bug is related to a module, specify its name and its version

psgdpr v1.4.0

**Comment by hibatallahAouadni** [comment]
Hello @rsoulard-prolaser 

I didn't manage to reproduce the issue with PS1786, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/188197251-95e3a049-78a9-47f9-84f2-f77259beb1c3.mp4

Please check and feedback.

Thanks!

**Comment by rsoulard-prolaser** [comment]
Hello @hibatallahAouadni,

You have 2 modules using GDPR hook **registerGDPRConsent** (not displayGDPRConsent).
You should to uninstall the Newsletter subscription module before all step.

Thanks.

**Comment by sLorenzini** [comment]
Hello @rsoulard-prolaser,

Thank you for your feedbacks.
Indeed by uninstalling all modules with GDPR consent and do your steps, I reproduce the issue with PrestaShop version 1.7.8.6 & 1.7.7.8, module version 1.4.2 and 1.4.0

1.7.7.8:

![1778-gdpr-hook](https://user-images.githubusercontent.com/2854834/188676601-a4a4fa91-b9bf-49db-8265-24db166798bc.png)

![1778-gdpr-data-management](https://user-images.githubusercontent.com/2854834/188676612-91d7d13a-9fd5-46ad-be97-64a6acef02d7.png)

1.7.8.6: 

https://user-images.githubusercontent.com/2854834/188676677-2aa6b7c7-f8e3-412d-a71e-adef5c644582.mp4

It is not a regression. I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
