### ISSUE TITLE
BO - The Order and the Customer Menu are incorrect after an upgrade from 1.7.7 to 1.7.7.8 and 1.7.8

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#29518]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

 The Order and the Customer Menu are incorrect after an upgrade from 1.7.7.2 to 1.7.7.8 and from 1.7.7.2 to 1.7.8.7

![image](https://user-images.githubusercontent.com/92912932/188167384-8be4a1a7-4448-4da0-9774-9ebed6e35e1e.png)

![image](https://user-images.githubusercontent.com/92912932/188167359-efec9a55-fed5-470b-9df6-56ad92ffb744.png)

https://user-images.githubusercontent.com/92912932/188167446-ffcccbdb-c618-4198-8cba-c7167370b3f8.mp4

### Expected behavior

The menu for the Order and Customer are correct : Order and Customer and not Order Settings & Customer Settings

### Steps to reproduce

1. Install PS1772 with frensh language
2. Install the `1_Click upgrade v4.14.2` module
3. Upgrade to PS1787 / PS1778
4. Connect to the BO of PS1778 / PS1787
5. Import `English` language
6. Go to Your profile : Team > Employee 
7. Change the BO language in `English` from and Save
8. See error 1 > The Menu for Order is : Order Settings for the top Orders Menu & Orders page
9. See error 2 > The Menu for Customer is : Customer Settings for the top Customers Menu & Customers page

### PrestaShop version(s) where the bug happened

1.7.7.8, 1.7.8.7

### PHP version(s) where the bug happened

10.3

### If your bug is related to a module, specify its name and its version

autoupgrade v4.14.2

**Comment by hibatallahAouadni** [comment]
Hello @HanaRebaiQA 

We encountered this issue with oldest versions #9762 and it's fixed!
Could you please check the issue if it's the same as yours 🙏 

Thanks!

**Comment by HanaRebaiQA** [comment]
Hello @hibatallahAouadni 

Thank you for your response. 
Indeed, it's related but not the same.

In fact, the [#9762](https://github.com/PrestaShop/PrestaShop/issues/9762) is reproduced with a fresh install and it's fixed. 
The current [issue](https://github.com/PrestaShop/PrestaShop/issues/29518) is reproduced following an upgrade. So, the original issue is not fixed after the upgrade.

Thank You!

**Comment by HanaRebaiQA** [comment]
It's related to [#9762](https://github.com/PrestaShop/PrestaShop/issues/9762)

**Comment by RosaBenouamer** [comment]
@hibatallahAouadni : What kind of specification is needed

**Comment by hibatallahAouadni** [comment]
Hello @RosaBenouamer 

Thanks for your patience :pray: 
Well, we use NeedsSpecs when the bug is an old bug (means not a regression) and needs to be prioritized by a PM :wink: 

Thanks!

**Comment by Hlavtox** [comment]
@PrestaShop/qa-functional Guys can you retest if this still happens after upgrade to 8.1.2?

- Install PS1772 with frensh language
- Upgrade to 8.1.2
- Import English language
- Go to Your profile : Team > Employee
- Change the BO language in English from and Save
- ❓ See error 1 > The Menu for Order is : Order Settings for the top Orders Menu & Orders page
- ❓ See error 2 > The Menu for Customer is : Customer Settings for the top Customers Menu & Customers page

**Comment by hibatallahAouadni** [comment]
Ping @florine2623 @paulnoelcholot @AureRita could you please test it 🙏

**Comment by Robin-Fischer-PS** [comment]
@hibatallahAouadni I'm pinging them already on Slack every hour :D (But we have a lot to do and a lot of meetings this week so there is some delay)

**Comment by paulnoelcholot** [comment]
Hello @Hlavtox 

I'm trying to reproduce the problem but I can't create a shop in 1.7.7.2 because of the bug linked to Addons :/

![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/d9237fef-9177-41c5-919d-bb729104c4aa)

**Comment by Hlavtox** [comment]
I think we can close it, because it must have been just a bug in translations. :-)

**Comment by florine2623** [comment]
Same as @paulnoelcholot ,

I can't install PS 1.7.7.2.

I did an upgrade from 1.7.7.5 to 1.7.8.10 to 8.1.2, I can't reproduce the issue. No issue with translation.

<img width="1440" alt="Screenshot 2023-12-04 at 11 19 24" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/89590fd2-2855-4972-b828-c4cf7704d1dd">

<img width="225" alt="Screenshot 2023-12-04 at 11 19 49" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/f3bfe749-1c31-4ddc-9f0b-6a2682778d11">

<img width="1413" alt="Screenshot 2023-12-04 at 11 28 18" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/0935478d-4c97-4286-a288-90ec3e25d729">

<img width="258" alt="Screenshot 2023-12-04 at 11 28 36" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/cc4a35f3-9245-426b-9bf4-c4a0ae2509e7">

This issue can be closed.
