### ISSUE TITLE
FO - Exception when trying to add a script in Checkout process > Shipping method

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#29529]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I have an exception when I add a script to the comment in Shipping method in the checkout process.

https://user-images.githubusercontent.com/16019289/188458173-e4455905-9556-4d60-a63c-cbba808cde47.mov

### Expected behavior

The comment should be escaped and no exception should be displayed.

### Steps to reproduce

1. Make sure that debug mode is activated
2. In FO > add product to cart
3. Start checkout process
4. In Step 3 > add `<script>alert(document.cookie)</script>` in the comment section
5. See Exception (without debug mode, there's an error 500)

### PrestaShop version(s) where the bug happened

1.7.7.8, 1.7.8.x, 8.0.x, develop

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @florine2623 


We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #9574. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #9574
