### ISSUE TITLE
Fix carrier name quote error in JS

### ISSUE THREAD

**Issue by websenso-team** [PrestaShop/PrestaShop#29522]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![image](https://user-images.githubusercontent.com/102657707/188401518-42725e03-0a63-4b13-a4bf-a5a6aa6d8d49.png)

Error JS in final order step, when a carrier name includes a quote, breaking JS interpretation

### Steps to reproduce

1. Set a carrier name with a quote
2. In FO, go to order' final step
3. Open the javascript console 

### PrestaShop version(s) where the bug happened

1.7.6.5

### If your bug is related to a module, specify its name and its version

ps_googleanalytics v4.1.2

**Comment by matks** [comment]
Nice feedback thank you @cedricWebsenso

**Comment by hibatallahAouadni** [comment]
Hello @cedricWebsenso 

I didn't manage to reproduce the issue PS1765 with/without GoogleAnalytics v4.1.2, see the attached screen record below:

PS1765 without GoogleAnalytics v4.1.2:

https://user-images.githubusercontent.com/23308427/188426720-82b62299-c35e-48cb-b421-80aa8b66d2e8.mp4

PS1765 with GoogleAnalytics v4.1.2:

https://user-images.githubusercontent.com/23308427/188427222-d7db7b2c-a65c-435d-b968-0137535c46aa.mp4

Please check and feedback.

Thanks!

**Comment by websenso-team** [comment]
Hello @hibatallahAouadni,
Thanks for your reply, i test it on a new PS1765 with GA v4.1.2 and i don't reproduce the js error on the final step.
I reproduce after choosing this carrier, and return to home the first time the ga_tag.tpl was injected.

**Carrier name :**
![image](https://user-images.githubusercontent.com/102657707/188474515-dfb0a067-f9b6-47a2-86de-7d855d632ca8.png)

**Order step :**
![image](https://user-images.githubusercontent.com/102657707/188474077-41d8270c-95f2-4e53-aab4-d28c42bee271.png)

**Return to Home (1st time only) and show the error in the js console  :** 
![image](https://user-images.githubusercontent.com/102657707/188474114-a9945efa-27ad-4f74-8102-c53dea89f56b.png)

With this steps did you reproduce the issue ?
Best regards,
Cédric

**Comment by florine2623** [comment]
Hello @cedricWebsenso ,

I can't reproduce your issue.
I'm using PS 1.7.6.5 and GA v4.1.2.

Here's a screen record:

https://user-images.githubusercontent.com/16019289/188884725-105187a3-9bf3-4258-8101-af7079996362.mov

If there's more info you would like to provide, please do so.
Thanks!

**Comment by florine2623** [comment]
@PrestaShop/qa-functional
Could someone try to reproduce the issue please ?
Thanks :)

**Comment by websenso-team** [comment]
Hello @florine2623,
Thanks for your reply.
After choosing carrier and validate it, in my test I don't validate the step4, i directly return to home and see the js error in the console.
Have a nice day.

**Comment by florine2623** [comment]
Could you provide a screenrecord ?
I still can't reproduce it following your advice.

**Comment by websenso-team** [comment]
Of course, the screenrecord :
https://user-images.githubusercontent.com/102657707/188908653-57fca4cc-26d0-400f-91b0-8d42144be326.mp4

**Comment by florine2623** [comment]
Tested by @khouloudbelguith and @paulnoelcholot. Both of them could not reproduce your issue.
The issue might come from your module, if you made a specific modification. Or from the Project itself if you used overrides.

I will close your issue as none of us could reproduce the issue ^^

If you have more info, do not hesitate to open a new issue if more info comes up.
Thanks!

**Comment by websenso-team** [comment]
Hello @florine2623, 
Thanks for the return, the issue is on https://github.com/PrestaShop/ps_googleanalytics/pull/125.
The issue was added to the next release of this module 4.1.3

For the context, i had installed a clean PrestaShop 1.7.6.5 without any theme, override, or anything else.
You can try it on https://ps1765.websenso.dev/

Best regards
