### ISSUE TITLE
Hidden CMS category is displayed in breadcrumb and gives error 404

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#29539]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In Prestashop, a CMS category can be hidden, and contain displayed CMS pages.
This makes sense. Maybe we want to show a link to a CMS page, but we don't want to display the list of all pages in the same CMS category. To achieve this, we can set `Display: Yes` for the page and `Display: No` for the CMS category.

But, in this case, the breadcrumb is not correct: In fact the Breadcrumb contains a link to the CMS category, and clicking on it gives a not found error.

### Expected behavior

If a CMS category is set to `Display: No` and the page to `Display: Yes`, the breadcrumb of that page should not show the hidden category. Instead of `Home > Hidden category > Page title`, it should simply read `Home > Page title`. 

### Steps to reproduce

1. Go to the BO, menu `Appearance - Pages`
2. Create a new category with name `Secret name` and select `Display: No`.
3. In that category, create a new page with title `New Page` and select `Display: Yes`.
4. In the FO, navigate to the new page
 => notice that the breadcrumb displays `Home > Secret name > New Page`
5. Click on `Secret name` 
 =>You get a 404 not found error

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.3

**Comment by sLorenzini** [comment]
Hello @lmeyer1 ,

I reproduce the issue with PrestaShop version 1.7.8.6 & 1.7.7.8.

1.7.7.8:

- my new category are not displayed on BO
![1778-breadcrumb-category-BO](https://user-images.githubusercontent.com/2854834/188599517-706e849a-1580-43ba-80f8-8c7d8697bd0b.png)

- my page of this category is displayed on BO
![1778-breadcrumb-category-page-BO](https://user-images.githubusercontent.com/2854834/188599544-58901d98-48cf-4786-973b-bda965b2e4c1.png)

- my page is well displayed but there is the category on the breadcrumb on FO
![1778-breadcrumb-FO](https://user-images.githubusercontent.com/2854834/188599596-3c409f11-8bce-4cd5-9ab2-6308e453cc6c.png)

- the category is a 404 after clinking on it on the breadcrumb on FO
![1778-category-not-displayed](https://user-images.githubusercontent.com/2854834/188599958-59c94491-17e7-4977-99fb-8096435c1d38.png)


1.7.8.6:

- my new category are not displayed on BO
![1786-breadcrumb-category-BO](https://user-images.githubusercontent.com/2854834/188599876-eb6371d9-217f-4481-99d3-2a6e76cf9705.png)

- my page of this category is displayed on BO
![1786-breadcrumb-category-page-BO](https://user-images.githubusercontent.com/2854834/188599892-75c06ae0-f1d8-493b-9e27-34e7a8b2497b.png)

- my page is well displayed but there is the category on the breadcrumb on FO
![1786-breadcrumb-FO](https://user-images.githubusercontent.com/2854834/188599906-efad8c21-ca83-4fb9-b783-6ce116eb2d91.png)

- the category is a 404 after clinking on it on the breadcrumb on FO
![1786-category-not-displayed](https://user-images.githubusercontent.com/2854834/188599926-8d7c42fd-1847-4c4d-b0a9-1a2cea8cc66a.png)

It is not a regression. I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved.

We’re waiting for your PR 🚀

Thank you

**Comment by lmeyer1** [comment]
@sLorenzini I think you chose the wrong tag `1.7.8.7`, not `1.7.7.8`.

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

> @sLorenzini I think you chose the wrong tag `1.7.8.7`, not `1.7.7.8`.

No, she didn't! As we reproduce the problem on an older version, so we only have to add this older version tag (meaning it always reproduces on the current version).
We only use the current version tag for regressions :wink: 

PS: if you have any questions about how we use labels or treat with issues, feel free to ask me or ping me on Slack:wink: 

Thanks!
