### ISSUE TITLE
State drop-down does not disappear in the checkout

### ISSUE THREAD

**Issue by Saimis777** [PrestaShop/PrestaShop#29541]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The default country in the shop is set as USA, in the checkout, when proceeding in the checkout from personal information, to the addresses, by default United States is shown, and the drop-down of the states. Selecting another country (in my case Lithuania) should automatically remove the states section, as there are no states in Lithuania, but it does not disappear, and I'm prompted to select a state nevertheless.
![image](https://user-images.githubusercontent.com/75423142/188580144-6b733e91-860b-420a-b59d-aa71a48e6304.png)

### Expected behavior

States drop-down should disappear

### Steps to reproduce

1. Select products, go to checkout
2. Make sure the default country is USA
3. Proceed until the addresses section
4. Select the country from United States to Lithuania or any other
5. Check if the states drop-down disappears

### PrestaShop version(s) where the bug happened

8.0

### PHP version(s) where the bug happened

7.4

**Comment by sLorenzini** [comment]
Hello @Saimis777,

Thank you for this report.
Is this issue is related to this merged [PR](https://github.com/PrestaShop/PrestaShop/pull/29122) which closed those issues https://github.com/PrestaShop/PrestaShop/issues/29012 & https://github.com/PrestaShop/PrestaShop/issues/28781?

Waiting for your feedback.

Thanks

**Comment by Saimis777** [comment]
Hi @sLorenzini ,

Seems like related, but both closed, were the fixes merged to the 8.0 branch? 

Though both of them are not exactly the same as this one, since the issue here is that the state doesn't disappear at all, when it should. 

Thanks

**Comment by florine2623** [comment]
Hello @Saimis777 ,

I confirm, this has been fixed on branch 8.0.x :)
So I close this issue!
Thanks!
