### ISSUE TITLE
[PHP8.1] - BO - A warning is displayed in the File manager after resetting the sort and the filter

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#29543]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > A warning is displayed in the File manager after resetting the sort and the filter 
![image](https://user-images.githubusercontent.com/16067358/188627450-7911e107-89f8-4481-91cb-301cce53beac.png)

It is ok with 8.0.x + PHP 8.0

### Expected behavior

No warning displayed

### Steps to reproduce

1. Use PHP8.1
2. Go to BO > Catalog > Categories page
3. Edit any category
4. In the description, try to insert some images
5. In the file manager, Try to insert a text in the input of the filter 
6. Click on the sort
7. Then reset it 
![image](https://user-images.githubusercontent.com/16067358/188627282-935ae356-dae9-4803-a65e-af89218ac855.png)
8. See error

https://user-images.githubusercontent.com/16067358/188629165-33f6f527-c4cb-4619-877f-c2b75df9ae77.mp4

### PrestaShop version(s) where the bug happened

8.0.x, 8.0.0beta

### PHP version(s) where the bug happened

8.1

**Comment by sLorenzini** [comment]
hello @khouloudbelguith,

I could reproduce your issue with php 8.1 on 8.0.0 PrestaShop version

![Capture d’écran 2022-09-06 à 15 23 21](https://user-images.githubusercontent.com/2854834/188646593-e267205b-1eb4-4ac6-9074-0710164f8083.png)

I'll add this to the backlog so it can be fixed.

Thank you

**Comment by HanaRebaiQA** [comment]
Fixed by [#29545](https://github.com/PrestaShop/PrestaShop/pull/29545)

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29545
