### ISSUE TITLE
Dockerize the TranslationTool app, with configurations editable via environment variables

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#29563]
Dockerize the TranslationTool app make the configurations editable via environment variables:
- crowdin_api_key (retrieve the key from repo)
- crowdin_project_identifier 
- GitHub credential (to be verified)

**Comment by MatShir** [comment]
Blocked until this PR is merged https://github.com/PrestaShopCorp/TranslationTool/pull/104

**Comment by jolelievre** [comment]
Actually, we skipped this part, the CI re cloning the project directly without using a docker so not needed anymore
The need may arise again later but it will require a new dedicated issue
