### ISSUE TITLE
Transfer the translation tool in the Open-Source Organization

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#29565]
Transfer https://github.com/PrestaShopCorp/TranslationTool in https://github.com/PrestaShop
- Create a new Crowdin key and archive/delete the old one
- Reset up the CI with the new repo

**Comment by MatShir** [comment]
To do when the all the other item of the [EPIC](https://github.com/PrestaShop/PrestaShop/issues/29533) are done

**Comment by mflasquin** [comment]
Hi @MatShir I think it's ok now ?
So we can cascade close https://github.com/PrestaShop/PrestaShop/issues/29533 and https://github.com/PrestaShop/PrestaShop/issues/29017 ?

**Comment by MatShir** [comment]
You're right ! For the bug, I will still double-check with the QA, but I seem to be fixed :)
