### ISSUE TITLE
BO - Bad display of error message while saving Low stock level

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#29583]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

While saving a wrong value for **Low stock level** like `upp`, the error message will be displayed badly, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/189105716-ebe8ae49-1f6d-43f0-bfe1-906529975476.png)

### Expected behavior

It should be displayed under the **Low stock level** input (like 1.7.8.6)

![image](https://user-images.githubusercontent.com/23308427/189105420-0c4fcca2-89ff-479a-bbb9-0146c7df366d.png)

### Steps to reproduce

1. **BO** > **SELL** > **Catalog** > **Products**
2. Edit a product with **Combinations**
3. Click on **Combinations** tab
4. Click on **pencil** icon to edit a combination
5. Type "upp" in **Low stock level** input
6. Save
7. See error > the error message displayed in the right side of the input, while it should be displayed below the input

### PrestaShop version(s) where the bug happened

8.0.0 beta

### PHP version(s) where the bug happened

7.2

**Comment by AureRita** [comment]
Hi @hibatallahAouadni  ,

I reproduce the issue with PrestaShop version 8.0.0 and not with the version 1.7.8.7.  You can see the issue on this video : 

https://user-images.githubusercontent.com/100699445/189316262-3857c8ae-cd0e-4b08-874b-f30c1741dfe7.mp4

Nice catch ! It's a regression ! I'll add it to the patch backlog.

Please be aware that some issues might take a very long time to be resolved. 

Thank you

**Comment by sallemiines** [comment]
i will check this PR

**Comment by sallemiines** [comment]
I will check this PR

**Comment by lartist** [comment]
Should we close this Issue ?
