### ISSUE TITLE
PS 1.7.8.7 Cart doesn't update

### ISSUE THREAD

**Issue by gouna15** [PrestaShop/PrestaShop#29597]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,
Following an update from prestashop 1.7.6.8 to 1.7.8.7, I noticed that the cart no longer updates automatically.
I replaced the /themes/core.js version 1.7.8.7 file with my old file from version 1.7.6.8, and now the shopping cart seems to work fine.

Warning error on google is : 
jQuery.Deferred exception: Cannot read properties of undefined (reading 'cart') TypeError: Cannot read properties of undefined (reading 'cart')

Is the problem known, is there a change to be made in core.js 1.7.8.7?

Thank's

### Steps to reproduce

1. Add item to cart
2. Modify the quantity
3. Cart does not update automatically
4. Replace /theme/core.js 1.7.8.7 with version 1.7.6.8 = shopping cart works fine

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.2

**Comment by gmourier** [comment]
I had the same problem with deleting an item from the cart on `1.7.8.7`.

I replaced the core.js file in the themes folder with this [one](https://raw.githubusercontent.com/PrestaShop/PrestaShop/1.7.7.x/themes/core.js) and cleared the cache; it solved the problem.

I come from a clean install and have a custom theme.

### Misc
Php version: `7.1`
Prestashop version: `1.7.8.7`

**Comment by hibatallahAouadni** [comment]
Hello @gmourier & @gouna15 

It seems that you didn't upgrade your theme while upgrading the shop :disappointed: 
Please check this [comment](https://github.com/PrestaShop/PrestaShop/issues/29466#issuecomment-1231580340) it seems solve the same isssue as yours.
Closing the issue as it's not related to PS Core.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #29466

**Comment by carletto0282** [comment]
Hi @gmourier where did you find that file?
I've tried with the core.js delivered with the package downloaded from prestashop.com but it's not working.
While using your file the issues is solved.

What has been changed in your file?
Thanks

**Comment by audebms** [comment]
Hello,
I think this issue must be reopened.

Indeed, I have a problem on price display on product view on a fresh PrestaShop install 1.7.8.8 and 1.7.8.9 with file `themes/core.js` which is included in zip downloaded on prestashop.com.

If I recompiled this files like this:
- Go to `themes/js/`
- Launch `npm install`
- Launch `npm run build`

`themes/core.js` is modified and prices display is fixed...

**Comment by Presta-learner** [comment]
> Hello, I think this issue must be reopened.
> 
> Indeed, I have a problem on price display on product view on a fresh PrestaShop install 1.7.8.8 and 1.7.8.9 with file `themes/core.js` which is included in zip downloaded on prestashop.com.
> 
> If I recompiled this files like this:
> 
> * Go to `themes/js/`
> * Launch `npm install`
> * Launch `npm run build`
> 
> `themes/core.js` is modified and prices display is fixed...

Hello,
same issue here with not refreshing cart, maybe you can contact me to check this together ?
thanks
