### ISSUE TITLE
Locked on a login redirect loop when upgrading to 1.7.8.x

### ISSUE THREAD

**Issue by itis-mmi** [PrestaShop/PrestaShop#29596]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I'm trying to upgrade a store under Prestashop 1.7.6.5 to the version 1.7.8.3 (not further because some modules don't seem to be compatible, I've tried with v1.7.8.7 before). 
I'm using the 1-Click Upgrade module with the ZIP file of Prestashop 1.7.8.3. 
The upgrade seems to work fine (except some modules unable to upgrade) and is declared successful. 
When I reload the page to login into the back-office, I'm unable to do it, as I'm constantly redirected to the same login page (instead of the back-office dashboard).

### Expected behavior

I'm expecting to successfully log into the back-office and to be redirected to the dashboard

### Steps to reproduce

1. Put the Prestashop 1.7.8.3 zip file into `admin/autoupgrade/download/` and create an empty XML file in the same directory
2. Use this file to upgrade the site via the **1-Click Upgrade** module
3. When upgrade is finished, reload the page
4. Try to log in the back-office

### PrestaShop version(s) where the bug happened

1.7.6.5 -> 1.7.8.x

### PHP version(s) where the bug happened

7.2, 7.3

**Comment by hibatallahAouadni** [comment]
Hello @itis-mmi 

I didn't manage to reproduce the issue, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/189636177-42eb59d3-0b01-4079-b4e8-0f44cd86fa49.mp4

As you can see, you made a mistake when you create an empty XML file in the same directory, you shouldn't!
Try again without adding the empty XML file :wink: 
Closing the issue as it's not PS Core bug!

Thanks!

**Comment by itis-mmi** [comment]
thank you for the answer @hibatallahAouadni. 
I tried again without the XML file, but the result stays the same... 

maybe the issue does come from some custom modules or themes, doesn't it ?
I'll try searching this way.

**Comment by hibatallahAouadni** [comment]
> maybe the issue does come from some custom modules or themes, doesn't it ?

@itis-mmi yes, you may need to disable all non-native modules and to switch your theme to default theme "CLASSIC" before upgrading.
