### ISSUE TITLE
Behat module tests mess with the core modules

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#29593]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I run this behat tests:

`./vendor/bin/behat -c tests/Integration/Behaviour/behat.yml -s module --tags module`

from this feature:

https://github.com/PrestaShop/PrestaShop/blob/8.0.x/tests/Integration/Behaviour/Features/Scenario/Module/module.feature

The core modules placed in `ROOT/modules` are modified, especially the `ps_emailsubscription` and `ps_featuredproducts` files get overridden with the content from the test modules: https://github.com/PrestaShop/PrestaShop/tree/8.0.x/tests/Resources/modules

This then results in unexpected behaviour since the modules don't have the right version anymore, it can also block the reinstallation or some pages because some hooks are in DB but the module doesn't implement the hook anymore.

### Expected behavior

Behat tests should have no impact on the core modules or event other contents EVER.
The tests are supposed to have their dedicated modules folder for that reason, but there are a few weird things with this bug that need investigation:
- create-test-db is initialized based on the ROOT/modules directory
- integration tests are based on ROOT/tests/Resources/modules directory
- since behat tests use the same bootstrap as Integration tests so it should be based on the test modules (first inconsistency we create test DB based on a different modules as the tests environment)
- and yet when the behat test are executed they seems to use some data from the test moules (hence the 1.0.0 version) but apply them in the core modules

So something is mixing both folders at some point, to fix this issue a few things should be figured out:
- why is the behat test modifying the core modules if it's supposed to use the test modules based on bootstrap (suspicious code here https://github.com/PrestaShop/PrestaShop/blob/47d2daba6e140c36d2894092d8c4a3de0c39ab3c/tests/Integration/Behaviour/Features/Context/ModuleFeatureContext.php#L41 but it's only a lead)
- once this is fixed maybe we should try and make the test data consistent as well, meaning create-test-db should be based on the test modules, not the core ones But maybe changing/fixing this will have impacts on some behat tests that will require some fixing/adaptation

### Steps to reproduce

1. Get a fresh install
2. You probably need to install a shop (build assets, ...)
3. Run `composer create-test-db`
4. Check the content of `modules/ ps_emailsubscription/config.xml` and `modules/ps_featuredproducts/config.xml` their version should be around 2.7.0 and 2.1.2 (specific versions may have evolved when the issue will be fixed but that's the idea)
5. Run this behat test `./vendor/bin/behat -c tests/Integration/Behaviour/behat.yml -s module --tags module`
6. Check the config file again they should both have `1.0.0` (matching the files in the test resource folder

### Expected solution

The problem probably comes from the `_MODULES_DIR_` configuration that is overridden in tests environment, so it should only look at the modules in the test resources folders, and most importantly only modify this folder There seems to be a problem on this override since the real modules folder is modified this should not happen
Fixing this configuration may raise some other bugs in related tests that will need to be adapted correctly

### PrestaShop version(s) where the bug happened

8.0

**Comment by AureRita** [comment]
Hi @jolelievre ,

I reproduce the issue with PrestaShop version 8.0.0, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved.

Waiting for your PR :rocket: 

Thanks

**Comment by matks** [comment]
PR started in https://github.com/PrestaShop/PrestaShop/pull/29708
