### ISSUE TITLE
"Place Order" button is disabled when only 1 payment option is available

### ISSUE THREAD

**Issue by AndreyOgleznev** [PrestaShop/PrestaShop#29608]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The "Place Order" button is disabled when only 1 payment option is available.
![2022-09-10_17-47-27](https://user-images.githubusercontent.com/11665990/189488809-a6a610d0-8c2e-4b49-a9f5-9ab94a3a667c.png)
![2022-09-10_17-57-27](https://user-images.githubusercontent.com/11665990/189489023-fd715917-e3cd-433b-95e7-2790f50fddc0.png)
![2022-09-10_17-49-52](https://user-images.githubusercontent.com/11665990/189488815-aba86be7-460c-486b-ab77-c03b754ea6cc.png)

### Expected behavior

The "Place Order" button is enabled when at least 1 payment option is available.

### Steps to reproduce

BO: Disable all the payment options in the shop except one
FO: Go to checkout and see that the payment option radiobutton is checked by default but the "Place Order" button is disabled.
BO: Enable one more payment option, 
FO: Go to checkout and see that when you select any of the options the "Place Order" button becomes enabled.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.3.31

**Comment by cernekj** [comment]
It is related to Classic Theme <https://github.com/PrestaShop/classic-theme>. I have fixed it for myself some time ago but have no time for PR.
Edit file `themes/classic/templates/checkout/_partials/steps/payment.tpl`
Line 131 should be:
```HTML
<button type="submit" class="btn btn-primary center-block{if !$selected_payment_option && ($payment_options|@count > 1 || $module_options|@count > 1)} disabled{/if}">
```

**Comment by Andre-N-73** [comment]
> ```
> <button type="submit" class="btn btn-primary center-block{if !$selected_payment_option && ($payment_options|@count > 1 || $module_options|@count > 1)} disabled{/if}">
> ```

Thank you for suggestion. What is the $module_options variable?

**Comment by hibatallahAouadni** [comment]
Hello @cernekj 

Your issue is related to #28466 and we are aware of this issue as it is already in our debug backlog. 
This issue is a duplicate of #29371. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #29371
