### ISSUE TITLE
Statslive module

### ISSUE THREAD

**Issue by avnet12** [PrestaShop/PrestaShop#29607]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

hello, 
I would like to know why the statslive module disappeared from 1.7.8?
I reinstalled the module that I recovered on a 1.7.7.8 version but at the update level, inevitably, there will not be any.
When will this module be back in service natively?
Thanks

### Steps to reproduce

Go to Backoffice
Clic on "Online visitors" link

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

 7.4.30

**Comment by hibatallahAouadni** [comment]
Hello @avnet12 

This module has been archived, it’s no longer maintained but you still can fork it if you need it for your shop.
Also let us know if you are voluntary to maintain this module.

Thanks!

**Comment by PrestaVision** [comment]
In PS 8.0.0.0 the administration link for 'Visitors Online' still points to that module, which is not included in PS 8.0.0.0
