### ISSUE TITLE
BO - Module upgrade is not functional when upgrading modules with php8.0 and php8.1 (An alert is displayed)

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#29613]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The issue is mentioned here in this [comment](https://github.com/PrestaShop/ps_distributionapiclient/pull/6#pullrequestreview-1062265091) (**Issue 2**)

The upgrade is not functional when upgrade modules with php8.1 (An alert is displayed)

![image](https://user-images.githubusercontent.com/92912932/189605676-56e4f6ad-86bf-441b-af95-cf040967a80d.png)

https://user-images.githubusercontent.com/92912932/189605406-3b3c83be-0ff0-4da6-810c-23a427fdba3d.mp4

https://user-images.githubusercontent.com/92912932/189605544-c0c20f04-2634-4468-b431-d725d26809f2.mp4

**8.0.x with php 8.1 : NOK** :x: 

### Expected behavior

The upgrade is functional when try to upgrade modules with php 8.1

### Steps to reproduce

1. Use php8.1
2. Have modules to upgrade (By use an old version of the module)
3. In BO > IMPROVE > Module manager > Updates 
4. Look that there is an Upgrade available
5. Click On Upgrade
6. See Error > An error is displayed with Operation not permitted!

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1

**Comment by hibatallahAouadni** [comment]
Hello @HanaRebaiQA 

@AureRita and me can't reprodcue the issue with ps_distributionapiclient v1.0.2, it seems to be fixed :tada: 
So closing the issue!

Thanks!

**Comment by AureRita** [comment]
Hello @HanaRebaiQA, 

The QA Team reproduce the issue with PrestaShop version 8.0.x and not with the version 1.7.8.7. Nice catch ! It's a regression ! I'll add it to the patch backlog.

Please be aware that some issues might take a very long time to be resolved. 

Thank you

**Comment by atomiix** [comment]
Hi everyone, I'm not able to reproduce this issue and I'm very surprised that this has something to do with php version. This seems to be a file permission issue. Maybe you built the zip module yourself with an owner/group different than the owner/group running your webserver?

**Comment by MatShir** [comment]
We could not reproduce the bug. I put back to `NMI` maybe someone may have more information to reproduce the issue.

**Comment by MatShir** [comment]
maybe @hibatallahAouadni could you test it again? 🙏

**Comment by HanaRebaiQA** [comment]
Hello everyone,

I have checked again this issue with @atomiix (Thanks !) We did not manage to reproduce it again.
So, i'll close it.

It's related to this issue https://github.com/PrestaShop/PrestaShop/issues/28924 

https://user-images.githubusercontent.com/92912932/198296203-ab8ce9c8-8ca1-40ce-8479-6b3d65b91501.mp4



Thank you!
