### ISSUE TITLE
Missing Smarty block around form fields 

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#29612]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The form_field Smarty block seems to have been removed by mistake in https://github.com/PrestaShop/classic-theme/pull/21, which among other things, breaks the display of the "Create an account" heading above the password field at guest checkout.

### Expected behavior

Test every password field of registering and guest checkout forms, and it should work as expected

### Steps to reproduce

1. Add product to the cart
2. Go to checkout
3. Checkout as a guest
4. "Create an account" heading above the password field is not displayed

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

n/a

### If your bug is related to a module, specify its name and its version

n/a

**Comment by hibatallahAouadni** [comment]
Hello @kpodemski 

Thanks for reporting the issue :pray: 
I reproduce the issue only with PS800, it seems it's a regression on 800_beta, see the attached screenshots below:

### PS1.7.8.6

![image](https://user-images.githubusercontent.com/23308427/189650220-b38cfa87-aae2-4e77-b7bf-d9f89fe9e68e.png)

### PS8.0.0_beta

![image](https://user-images.githubusercontent.com/23308427/189650248-8ad0c9a7-6424-4e71-bc71-56bbb082bd7e.png)

I'll add it to the backlog to be fixed! Thanks @balejk for your PR :rocket: 

Thanks!

**Comment by Hlavtox** [comment]
@hibatallahAouadni 🔪
