### ISSUE TITLE
Dashboard Trends Shows No Sales if include September 4 in view range.

### ISSUE THREAD

**Issue by sergioaraos** [PrestaShop/PrestaShop#29623]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The dashboard trends module is not showing sales after september 4th. If I include this date the sales goes to zero. If I exclude the date, sales are ok. If I change the year, but include september 4th in the date range, the behavior repeats.

In the image below you can see sales between september 5th and today

<img width="851" alt="image" src="https://user-images.githubusercontent.com/64826895/189911516-44fd16d8-2010-4056-b3b2-97b3b1b76279.png">

But if i include september 4th, sales dissapear.

<img width="839" alt="image" src="https://user-images.githubusercontent.com/64826895/189911921-cf8141cd-e654-4dbf-a869-63dcbcb2d934.png">

If I change the year, including september 4th.
<img width="838" alt="image" src="https://user-images.githubusercontent.com/64826895/189924631-78ff678b-aa48-4018-a65d-863a6ee590b6.png">

If I exclude september 4th.

<img width="834" alt="image" src="https://user-images.githubusercontent.com/64826895/189924850-2bfc1afb-b946-47cf-a653-ce8a0d7b7853.png">

Is really weird. Please help!

### Expected behavior

Should show all sales in the range.

### Steps to reproduce

1. Login PS Admin Dashboard
2. Set Dashboard trends from september 4th to today.
3. Sales are missing.
4. Now, exclude september 4th.
5. Sales appears ok.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

dashtrends

**Comment by florine2623** [comment]
Hello @sergioaraos ,

I can't reproduce your issue in PS 1.7.8.7.

Including September 4th:
<img width="1206" alt="Screenshot 2022-09-13 at 17 22 25" src="https://user-images.githubusercontent.com/16019289/189942758-676c5252-0dbb-4808-abdc-ff0aedb32d54.png">

Excluding September 6th:
<img width="1207" alt="Screenshot 2022-09-13 at 17 22 42" src="https://user-images.githubusercontent.com/16019289/189942774-aefcfce9-1b68-451c-b707-d5c279809ac8.png">


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

I will close your issue.

Thank you
