### ISSUE TITLE
BO - Employee page - The password strength is always displayed even after cancelling the action

### ISSUE THREAD

**Issue by mflasquin** [PrestaShop/PrestaShop#29626]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Edit employee page, when we cancel the 'modification of the password' and click again on "Change password..." the password strength feedback is not well displayed :

![image](https://user-images.githubusercontent.com/6594752/189948439-a8a53b3b-0621-49ba-8dc5-f004966fef6b.png)

the password strength feedback should not be visible.

### Expected behavior

When we cancel the 'modification of the password' and then click again on "Change password..." the password strength feedback should not be visible.

### Steps to reproduce

1. Go to BO > Advanced Parameters > Team > Employee page
2. Edit your employee account
3. Click on 'change password' it opens a little div with the inputs needed to change password
4. Input inside "New password" with an not secure password, for example "123456789"
5. Click on 'Cancel'
6. Click on 'Change password...'
7. See that the strength is always displayed

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.3

**Comment by florine2623** [comment]
Hello @mflasquin ,

I have reproduced the issue in 1.7.7.8, 1.7.8.7, 8.0.x and develop. This is not a regression. I'll add this to the backlog so it can be fixed.

In 1.7.7.8 and 1.7.8.7:
<img width="641" alt="Screenshot 2022-09-13 at 18 04 18" src="https://user-images.githubusercontent.com/16019289/189951703-debc4580-81ac-43ce-a3f0-ff136dc53a91.png">

In develop:
<img width="634" alt="Screenshot 2022-09-13 at 18 08 18" src="https://user-images.githubusercontent.com/16019289/189952030-6dd479dc-753b-45c2-bc8c-694c85264e31.png">

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by mflasquin** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29630
