### ISSUE TITLE
Can't log to backoffice (prestashop 1.7.7.2)

### ISSUE THREAD

**Issue by tga21** [PrestaShop/PrestaShop#29622]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi everyone,

I have had, in the lapse of 3 weeks, this same bug 2 times. This bug is related to the access of the backoffice. Suddenly I can't log in prestashop's dashboard. I enter the correct user and password and it loads but doesn't log in. When I enter a wrong password, it doesn't display the error (I attach a screenshot of this below, I have changed the cookie in url also some text).
![Captura de Pantalla 2022-09-13 a las 15 54 28](https://user-images.githubusercontent.com/105740679/189920703-92e7721c-e9e3-4d40-ae3d-626068ebfe25.png)

I have solved it twice restoring a backup of the files from the previous 24-36h, because deleting prestashop's cache by ftp and  browser's cache, does not solve the issue.

I have installed the files with the bug in a subdomain in case prestahsop's developers want to have a look.

If anyone have experienced a similar issue, please tell me.

Thanks for reading this. 

Best regards for all of you

### Expected behavior

access prestashop backoffice if credentials are correct ; show alert in case of not correct credentials

### Steps to reproduce

Go to admin url, add correct or not credential.

### PrestaShop version(s) where the bug happened

1.7.7.2

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment]
Hello @tga21 ,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project, this is a specific issue on your shop. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
