### ISSUE TITLE
Unable to load template 'file:../public/preload.tpl' in 'header.tpl'

### ISSUE THREAD

**Issue by musaffar-patel** [PrestaShop/PrestaShop#29634]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After dowbnload the Prestashop 8.0 dev version and installing, logging into the back office produces the following error:

Unable to load template 'file:../public/preload.tpl' in 'header.tpl'

Full stack trace below.

SmartyException:
Unable to load template 'file:../public/preload.tpl' in 'header.tpl'

  at E:\websites\prestashop\80\www\vendor\smarty\smarty\libs\sysplugins\smarty_internal_template.php:195
  at Smarty_Internal_Template->render()
     (E:\websites\prestashop\80\www\vendor\smarty\smarty\libs\sysplugins\smarty_internal_template.php:385)
  at Smarty_Internal_Template->_subTemplateRender('../public/preload.tpl', null, null, 0, 3600, array('admin_dir' => '/adminps/themes/default/public/'), 0, true)
     (E:\websites\prestashop\80\www\var\cache\dev\smarty\compile\d8\5b\20\d85b201d761a5e0539417c24aba1a6d7c2d8fd77_0.file.header.tpl.php:146)
  at content_6321b9379c61a6_54916390(object(Smarty_Internal_Template))
     (E:\websites\prestashop\80\www\vendor\smarty\smarty\libs\sysplugins\smarty_template_resource_base.php:123)
  at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(Smarty_Internal_Template))
     (E:\websites\prestashop\80\www\vendor\smarty\smarty\libs\sysplugins\smarty_template_compiled.php:114)
  at Smarty_Template_Compiled->render(object(Smarty_Internal_Template))
     (E:\websites\prestashop\80\www\vendor\smarty\smarty\libs\sysplugins\smarty_internal_template.php:216)
  at Smarty_Internal_Template->render(false, 0)
     (E:\websites\prestashop\80\www\vendor\smarty\smarty\libs\sysplugins\smarty_internal_templatebase.php:238)
  at Smarty_Internal_TemplateBase->_execute(object(Smarty_Internal_Template), null, null, null, 0)
     (E:\websites\prestashop\80\www\vendor\smarty\smarty\libs\sysplugins\smarty_internal_templatebase.php:116)
  at Smarty_Internal_TemplateBase->fetch('header.tpl')
     (E:\websites\prestashop\80\www\classes\controller\AdminController.php:1943)
  at AdminControllerCore->display()
     (E:\websites\prestashop\80\www\classes\controller\Controller.php:339)
  at ControllerCore->run()
     (E:\websites\prestashop\80\www\classes\Dispatcher.php:503)
  at DispatcherCore->dispatch()
     (E:\websites\prestashop\80\www\adminps\index.php:92) 

### Steps to reproduce

Install Prestashop 8
Remove install folder
rename admin-dev folder to anything else (in my case adminps)
Attenmpt to login into the Back office.

### PrestaShop version(s) where the bug happened

8.0

### PHP version(s) where the bug happened

7.2.34 nts

**Comment by hibatallahAouadni** [comment]
Hello @musaffar-patel 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. It seems your issue is related to your custom theme and modules.

Closing the issue as we only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thanks!

**Comment by musaffar-patel** [comment]
@hibatallahAouadni No custom theme or module is involved.  I simply downloaded Prestashop 8.0 from github, ran composer install in the root folder and then ran the Prestashop installer.

**Comment by hibatallahAouadni** [comment]
did you run `make install` ? if no, try to run it :wink:

**Comment by musaffar-patel** [comment]
I should have mentioned I ran the installer on Windows therefore the make commend is not available.

Other than running composer install in the root folder are any other steps required?

I should point out that the prestashop installer ran and completed without issues, it was when I attempted to login into the back office that the Symfony error was thrown.

**Comment by hibatallahAouadni** [comment]
You can ask @Hlavtox :wink: he uses Windows

**Comment by PrestaSafe** [comment]
Hi, same issue Here. 
Install a new PrestaShop 8.0 from release archive
Do a composer install
then make assets
I can't access to any backend page execept dashboard
Can't access to front office too. 
No custom modules or theme, juste a fresh prestashop install (online)

PHP 8.1 and 8.0 same issue

**Comment by PrestaSafe** [comment]
It seems to block at this point: 
<img width="384" alt="Capture d’écran 2022-11-25 à 12 34 27" src="https://user-images.githubusercontent.com/4788787/203990699-8a74a45c-64c4-4f74-8991-3fb3e5f07e6c.png">
i've tried with node 12 / 14 / 16
