### ISSUE TITLE
blockreassurance SQL query error

### ISSUE THREAD

**Issue by cy-altern** [PrestaShop/PrestaShop#29648]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

With a Prestashop v 1.7.8.7 freshly installed, the **blockreassurance** module throw this error :
```
Unknown column 'prl.id_shop' in 'where clause'<br /><br /><pre>SELECT * FROM `ps_psreassurance` pr LEFT JOIN ps_psreassurance_lang prl ON (pr.id_psreassurance = prl.id_psreassurance) WHERE prl.id_lang = "2" AND prl.id_shop = "1" ORDER BY pr.position</pre>
at line 769 in file classes/db/Db.php
```
The blockreassurance's database tables are standard : `ps_reassurance` and `ps_reassurance_lang`

### Expected behavior

no error expected

### Steps to reproduce

1. activate blockreassurance module
2. open the shop page or the module's configuration page

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

blockreassurance

**Comment by AureRita** [comment]
Hi @cy-altern, 

Thank you for your report. I try to reproduce your issue but I didn't see this querry as you can see

https://user-images.githubusercontent.com/100699445/190447119-4c2ccb90-39d6-43fd-8cc1-db3f98a81fae.mp4

can you tell us which version of block reassurance did you have ? 

waiting for your feedback

**Comment by cy-altern** [comment]
version : Réassurance v5.1.1 - par PrestaShop  (shiped by default in Prestashop 1.7.8.7)

**Comment by hibatallahAouadni** [comment]
Hello @cy-altern 

I didn't manage to reproduce the issue with PS1787 and Réassurance v5.1.1, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/190622305-ba0f70d2-4b40-4637-b9c1-dfe824d1fea4.mp4

Did you apply some changes or overrides on this module? and could you please provide a screen record of your issue :pray: 
Waiting for your feedback.

Thanks!

**Comment by cy-altern** [comment]
I haven't any overrides on this module
![prestoshop_reassurance_tree_no-override](https://user-images.githubusercontent.com/5904309/190624368-fc110338-6c7e-421a-bd6e-ecd80fb924c7.jpg)

The screen record :
https://user-images.githubusercontent.com/5904309/190627887-cd16fa22-9423-4c38-b17d-c58d3df8c5a3.mp4

**Comment by kpodemski** [comment]
Hello @cy-altern 

Support for the multi-store was removed from the module a while ago. You should not have any queries related to the multi-store tables/fields.

Maybe you could try to download the package once again:
https://github.com/PrestaShop/blockreassurance/releases

And upload it to your store?

**Comment by hibatallahAouadni** [comment]
Hello @cy-altern 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or theme problem.

We will close this issue.

Thanks!
