### ISSUE TITLE
[Feature] Use a ThemeUpdater tools to allow theme to be updated like a module

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#29642]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

When you have an installed theme and want to update it, you need to do it by FTP and/or by removing the old one.

If you remove the old one, you need firstly to switch to another theme and so loose the configurations you've done.
If you update it by FTP, you firstly need to know howto and you have to not forgot to move the modules of the dependencies folder to update them, too.

### Describe the solution you'd like

Having the possibility to update a theme throw the Back Office like you will do with a module.

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by AureRita** [comment]
Hi @PrestaEdit  ,

Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments. 

Please be aware that there is no guarantee that this feature will be developed anytime soon.

Waiting for your PR :rocket: 

Thank you

**Comment by matks** [comment]
Reminds me of https://github.com/PrestaShop/PrestaShop/issues/13663 😄
