### ISSUE TITLE
Autoupgrade: missing translations

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#29649]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the auto-upgrade module, there are missing translations, due to translation domains not being hardcoded in some places, making extraction impossible.

### Expected behavior

Translation domains should not be hardcoded

### Steps to reproduce

N/A

### PrestaShop version(s) where the bug happened

N/A

### PHP version(s) where the bug happened

N/A

### If your bug is related to a module, specify its name and its version

autoupgrade

**Comment by AureRita** [comment]
Hi @matthieu-rolland, 

Thank you for your reporting, unfortunately, without steps to reproduce, the version of autoupgrade, the translation of wich languages, I can't reproduce this issue. 

Can you give me more details about this issue ? 

Waiting for your feedback

**Comment by matks** [comment]
@AureRita I think in order to reproduce the problem you need to use the wording extractor tool.

If this tool is controlled by a developer, can developers validate this topic and the PR https://github.com/PrestaShop/autoupgrade/pull/505 ?

**Comment by hibatallahAouadni** [comment]
Hello @matks 

Thanks for your feedback :pray: 
Ping @PrestaShop/prestashop-core-developers can someone please try to reproduce the issue :pray: 

Thanks in advance!

**Comment by matks** [comment]
I validate this issue 👍
