### ISSUE TITLE
Module manager thrown an exception module ps_distributionapiclient is deleted

### ISSUE THREAD

**Issue by atomiix** [PrestaShop/PrestaShop#29651]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I delete the module ps_distributionclientapi, this exception is thrown:
<img width="1074" alt="Capture d’écran 2022-09-15 à 17 16 32" src="https://user-images.githubusercontent.com/2168836/190441935-38c511c9-3791-4367-8685-376102569bda.png">

### Expected behavior

No exception

### Steps to reproduce

1. Go to the Module Manager page
2. Delete the module ps_distributionapiclient
3. Refresh the page
4. See the exception

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.0

**Comment by hibatallahAouadni** [comment]
Hello @atomiix 

I was able to reproduce the issue with PS8.0.0 and `ps_distributionapiclient` v1.0.1. 
I’ll add this to the debug backlog so that it’s fixed. Waiting for your PR :rocket: 

Thank you

**Comment by HanaRebaiQA** [comment]
This issue is fixed in this PR [#29660 ](https://github.com/PrestaShop/PrestaShop/pull/29660)
