### ISSUE TITLE
Bad PHP float comparison in Tools

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#29652]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

[CI was failing](https://github.com/PrestaShop/PrestaShop/issues/29641) this morning because of a change in a PHPUnit dependency was updated: sebastian/comparator was upgraded from 4.0.6 to 4.0.8 and the new release does test floats more accurately.

This provided us an important information: we have php classed that do return an inaccurate result as you can see for example with below screenshot

<img src="https://user-images.githubusercontent.com/3830050/190235301-62af65fd-6983-4ba1-ae05-80eead34996d.png">

In order not to block CI [we have locked sebastian/comparator](https://github.com/PrestaShop/PrestaShop/pull/29643) version to 4.0.6 however we must fix the real problem.

### Describe the solution you'd like

What needs to be done is:
1. Unlock sebastian/comparator to use latest version
2. This will show us inaccurate float comparisons errors
3. Fix the PrestaShop code that is inaccurate in order for PHPUnit test suite to pass

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @matks 

Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. 
Waiting for your PR :rocket: 

Thank you

**Comment by nicosomb** [comment]
PR is merged, bug is fixed ✅
