### ISSUE TITLE
[PHP8.1]/[PHP8.0] PATCH for endpoint /api/products/{product_id}/ and /api/categories/{category_id} are NOK

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#29666]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Using PHP 8.1 & PHP8.0, The HTTP request PATCH for endpoint /api/products/{product_id}/ and /api/categories/{category_id} are NOK
![image](https://user-images.githubusercontent.com/16067358/190672765-b730a98f-3afd-4725-972e-82637f454b92.png)

PS: with PHP7.4 => OK

### Expected behavior

No, error displayed & persistent data

### Steps to reproduce

1. Go to BO > Advanced Parameters > Webservice page
2. Enable Webservice
3. Create a new webservice Key and enable the PATCH method
4. Using postman, try to PATCH for endpoint /api/products/{product_id}/
5. See error
![image](https://user-images.githubusercontent.com/16067358/190673201-630507a4-bc0a-42cc-b0dc-a5919d34ea94.png)
6. Using postman, try to PATCH for endpoint /api/categories/{category_id} 
7. See error 
![image](https://user-images.githubusercontent.com/16067358/190673630-60afc125-d126-4569-9c02-4934f1ad5fe2.png)

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1, 8.0

**Comment by matks** [comment]
@khouloudbelguith Is it the same https://github.com/PrestaShop/PrestaShop/issues/29653 😄 ?

**Comment by khouloudbelguith** [comment]
Hello @matks,

No, it is not the same issue:
#29653: The HTTP PUT & PATCHrequest is not working for endpoint `/api/images/products/{product_id}/` in all PHP versions
#29666: the HTTP PATCH is not working for endpoint` /api/products/{product_id}/` and `/api/categories/{category_id} `only with php8.0 & PHP 8.1, it is ok with php7.4

Thanks!

**Comment by jolelievre** [comment]
It's not the same endpoints, this PR is about entities endpoints. The https://github.com/PrestaShop/PrestaShop/issues/29653 is about images of these entities.

**Comment by jolelievre** [comment]
Fixed by #29756
