### ISSUE TITLE
Install - Informations step - the Password requirements and the tooltip are not displayed

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#29667]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

It is related to this PR: https://github.com/PrestaShop/PrestaShop/pull/29273
When Installing a shop 8.0.x, in the `Informations` step, the Password requirements are not displayed
![image (5)](https://user-images.githubusercontent.com/16067358/190682076-d62d6e65-8735-49e1-bac9-094bc888427d.png)

### Expected behavior

It should be ok
![image](https://user-images.githubusercontent.com/16067358/190682139-41b95e09-63a8-4965-b035-81e8fc668fba.png)
![image](https://user-images.githubusercontent.com/16067358/190682544-8160eda6-9854-49ee-97c8-2586e1022bcc.png)

### Steps to reproduce

1. Install 8.0.x
2. In the Informations step, set the password employee
3. See error: the Password requirements and the tooltip are not displayed

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1, 7.2

**Comment by sallemiines** [comment]
Hello @khouloudbelguith 

I was able to reproduce the issue with PS8.0.x.
I’ll add this to the debug backlog so that it’s fixed. 

Thank you !

**Comment by matks** [comment]
Explanation of the problem:

When we merged https://github.com/PrestaShop/PrestaShop/pull/29273, the file `install-dev/theme/js/sprintf.min.js` was modified by the license header updator. The behavior of the file was not modified BUT as the file changed, the integrity check now fails, causing an error when attempting to load it inside the Installer "Informations" step (see screenshot below)

![Capture d’écran 2022-09-16 à 20 48 51](https://user-images.githubusercontent.com/3830050/190711608-9021287a-8b33-4d7b-b0aa-1fbb64f9f39c.png)


Restoring the file to its initial content https://raw.githubusercontent.com/PrestaShop/PrestaShop/1eacfed357af9c67e373e432182e4322c2298863/install-dev/theme/js/sprintf.min.js allows to restore the correct behavior as done in https://github.com/PrestaShop/PrestaShop/pull/29670

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29670
