### ISSUE TITLE
Problem for save price of zone in the transport

### ISSUE THREAD

**Issue by AlexisVS** [PrestaShop/PrestaShop#29673]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I try to set price for transport zone and i have an error.

![image](https://user-images.githubusercontent.com/63750707/190864757-cdcd55c4-aedb-4b13-b6a9-7d52a57713ca.png)

### Expected behavior

Just a save

### Steps to reproduce

1. Go to transporter page
2. select a zone
3. Enter price for each Kg
4. save it

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.19

**Comment by AlexisVS** [comment]
Okey, I have solved this problem it's because my php config have only 1000 max_input_vars

![image](https://user-images.githubusercontent.com/63750707/190867842-b577820c-cdf5-450f-b256-898ba71fb87a.png)

**Comment by hibatallahAouadni** [comment]
Hello @AlexisVS 
Thanks for your feedback :smile:
