### ISSUE TITLE
Backoffice fatal error : Call to a member function set() on integer

### ISSUE THREAD

**Issue by cretbogdan01** [PrestaShop/PrestaShop#29672]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I restored my shop after some issues but for some reason the Backoffice it is not working. I am getting the following error:
![image](https://user-images.githubusercontent.com/44405153/190806207-7dd7db77-18d0-4278-a766-7aa6da8d2d20.png)

I have already tried to delete cache from var/cache ( dev & prod ) but with no luck.

The strange thing is if I move all the files under a mydomain.com/shop/ for example and update ps_shop_url table accordingly everything works as expected. 

As soon as I move the shop under the maindomain.com I cannot access Backoffice due to the above error.

### Expected behavior

I would expect the shop to run under main domain and I don't understand where is the problem since exact same shop if I move it under a different folder it does work.

### Steps to reproduce

-

### PrestaShop version(s) where the bug happened

1.7.6.8

### PHP version(s) where the bug happened

7.2

**Comment by paulnoelcholot** [comment]
Hello @cretbogdan01 ,

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it.
**You must follow the template and provide clear and concise steps to reproduce the bug**. 

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
