### ISSUE TITLE
Prestashop 1.7.8.7 Auto Log Out on Product Page Only

### ISSUE THREAD

**Issue by arpanjain100** [PrestaShop/PrestaShop#29675]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Front End Problem
On loading any product page, the customer is auto logged out.
The Auto Log out is not on happeneing on any other page.

Tried to delete, var/cache , browser cookies, tried incognito mode + all methods mentioned in #14621 

Problem in classic theme and Zone theme
Check Cookie also disabled

### Expected behavior

The website should not auto log out on the product page.

### Steps to reproduce

1. Go to prestashop FO and log in as a customer
2. browse category page
3. browse product page
4. See error > auto log out happening.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

**Comment by paulnoelcholot** [comment]
Hello @arpanjain100 

You probably have ps installed in a subfolder with wrong webserver configuration.

Could you please check and feedback?

Thanks

**Comment by arpanjain100** [comment]
> Hello @arpanjain100
> 
> You probably have ps installed in a subfolder with wrong webserver configuration.
> 
> Could you please check and feedback?
> 
> Thanks

Hi,


I have installed in public_html and there is no sub folder. 
 What server config I have to check?

The product page loads fine, only the customer gets auto logged out.

**Comment by hibatallahAouadni** [comment]
Hello @arpanjain100 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a module problem.

We will close this issue.

PS: you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thanks!
