### ISSUE TITLE
Grid action column problems and improvements

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#29679]
### Describe the bug and add screenshots

If you set some actions as `'use_inline_display' => true,` and some not, it causes bad display. They should be in one line.

![inline or not](https://user-images.githubusercontent.com/6097524/190923028-6638206f-5ded-4305-94b0-b176d79a64b5.jpg)

If there are only two actions, we don't have to render the hamburger menu by default. It's only an extra click.

![actions](https://user-images.githubusercontent.com/6097524/190923181-ab765dea-c461-4ef5-aa8e-84e37e4c34e1.png)

Template concerned:
`\src\PrestaShopBundle\Resources\views\Admin\Common\Grid\Columns\Content\action.html.twig`

### PrestaShop version(s) where the bug happened

develop

**Comment by paulnoelcholot** [comment]
Hello @Hlavtox ,

Thank you for your good suggestion. 

However it's not bugs, it's features. So can you create a new issue using the rules of creating issue as well as the appropriate template.


Thank you

**Comment by zuk3975** [comment]
@paulnoelcholot - seems like a bug to me (not a feature request)
The option `use_inline_display' => true` is already there in the core, this bug issue focuses on the fact that they are not correctly aligned.

**Comment by hibatallahAouadni** [comment]
Hello @zuk3975 

> @paulnoelcholot - seems like a bug to me (not a feature request)
The option use_inline_display' => true is already there in the core, this bug issue focuses on the fact that they are not correctly aligned.

Thanks for your feedback!
But @Hlavtox need to respect the provided template and provide clear and concise steps to reproduce the issue.
That's why we close the issue.

Thanks for your understanding :pray:

**Comment by zuk3975** [comment]
https://github.com/PrestaShop/PrestaShop/issues/29692
