### ISSUE TITLE
CI issue on 1.7.8.x - Sanity tests fail at install Addons modules step

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#29702]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

CI is failing on branch 1.7.8.x.  Sanity tests fail at install Addons modules step

![Capture d’écran 2022-09-20 à 11 53 50](https://user-images.githubusercontent.com/3830050/191227554-e6f90575-9af9-4ee8-9bf0-79a431e5b418.png)

https://github.com/PrestaShop/PrestaShop/actions/runs/3088446779/jobs/4994925317

Examples of PR impacted:
- https://github.com/PrestaShop/PrestaShop/pull/29698

### Expected behavior

Sanity tests should be able to complete install

### Steps to reproduce

N/A

### PrestaShop version(s) where the bug happened

1.7.8.x

### PHP version(s) where the bug happened

7.1, 7.2, 7.3, 7.4

**Comment by atomiix** [comment]
@matks This is fixed ;)
