### ISSUE TITLE
BO - A bad display of buttom when uninstall the distributionapiclient module (empty checkbox)

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#29712]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This issue is reported here in this [comment](https://github.com/PrestaShop/ps_distributionapiclient/pull/6#pullrequestreview-1062265091) (**Issue 3**)

A bad display of button when uninstall the distributionapiclient module (empty checkbox)

**8.0.x : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/191514216-4a5e6f4c-7f6c-406c-87ea-54ef12e81882.png)

https://user-images.githubusercontent.com/92912932/191525571-4567f97c-13fe-4b92-9470-62053bac3589.mp4

**When uninstall another module : OK** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/191520506-aefd0d65-43e8-4b76-ac9e-196871f4aa20.png)

### Expected behavior

Normally after uninstall the install button is displayed!

### Steps to reproduce

1. Install a new 8.0.0 
2. Go to BO > IMPROVE > Modules > Module manager 
3. Search for `distributionapilclient` `v1.0.1` OR `v1.0.2`
4. Click on the box and click the Uninstall 
5. Check the checkbox : `the optional : delete module folder after uninstall`
6. Click on `Yes, I want to do it`
7. The module is uninstalled
8. Search again for the module
9. See error > The Install button is not displayed! An empty checkbox is displayed

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

distributionapiclient v1.0.1 and v1.0.2

**Comment by MhiriFaten** [comment]
Hello @HanaRebaiQA ,

Thanks for your report. 
I was unable to reproduce your issue using the same provided steps to reproduce.

[Untitled_ Sep 23 2022 4_52 PM.webm](https://user-images.githubusercontent.com/111756615/192001495-ac2c7931-2b9b-4d09-95dd-60cf5762e5f5.webm)

Could you please check again ? Waiting for your feedback!

Thank You!

**Comment by MatShir** [comment]
@MhiriFaten I don't see the errors in your video? 🤔

**Comment by HanaRebaiQA** [comment]
Hello, 

I checked again the issue with 8.0.0RC1. The issue is fixed. 

https://user-images.githubusercontent.com/92912932/195289026-75b04c7a-711a-4477-a147-96af3f1d5814.mp4

So, i'll close the issue.

Thank You!
