### ISSUE TITLE
Backoffice display language does not always take into account the employee's language

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#29717]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

As an employee with configured language German, I log into the Backoffice and see everything in French (except some words sparkled over the screen that are German).
![Immagine 2022-09-21 180753](https://user-images.githubusercontent.com/7520695/191699538-3939ee61-ad65-4b75-90f5-4d2882cffdbf.png)
![Immagine 2022-09-21 180933](https://user-images.githubusercontent.com/7520695/191699553-5d45b92c-7f1e-4ce2-8b34-2e77434182f2.png)

After some tests and some `echo` and `var_dump`, I found that the languages for the employee are overridden by the domain used to access the BO. Since in a multishop installation, it is possible to access to the BO with the URLs of any shop, to configure the shops the employee has access to, the actual behavior is inconsistent.

### Expected behavior

I expect that the employee's language takes effect in the BO.
This should be independent of the URL used to access the BO.

### Steps to reproduce

Prerequisites:
1. In a multishop installation create three shops with there URLs
    - Shop AB at https://shop-ab.com
    - Shop A at https://shop-a.com
    - Shop B at https://shop-b.com
2. Assign languages:
    - Got to `International - Localization - Languages`, edit Language A and select shop AB and shop A, then edit language B and select shop AB and shop B
 
Tests:
1. Go to your employee's profile and set your language to A
2. Connect to the BO using https://shop-ab.com/admin-dev. You will see the BO in language A => OK
3. Connect to the BO using https://shop-a.com/admin-dev. You will see the BO in language A => OK
4. Connect to the BO using https://shop-b.com/admin-dev. You will see the BO in language B => This is unexpected
5. Go to your employee's profile and set your language to B
6. Connect to the BO using https://shop-ab.com/admin-dev. You will see the BO in language B => OK
3. Connect to the BO using https://shop-a.com/admin-dev. You will see the BO in language A => This is unexpected
4. Connect to the BO using https://shop-b.com/admin-dev. You will see the BO in language B => OK

100% reproducible steps, simplified to include only the strict necessary operations.
---------------------------
1. Get a basic multistore installation following [this gist](https://gist.github.com/lmeyer1/c40a19d880758bee11a1e8a2c5e819c3).
2. Log into the backoffice via `localhost:8017/admin-dev`
3. The shops must have different domains:
   - In _Advanced parameters - Multistore_ configure shop 2 with name `French Shop` and URL fr.localhost:8017
   - The default shop has now URL localhost:8017 and `French Shop` fr.localhost:8017
4. `French shop` must only have `French` as language, not any other.
   - Go to `International - Localization - Languages`, for each language, click on edit, check `Default shop` and uncheck `French shop`, except for `French` where you check both shops.
5. Go to `International - Localization - Localization`, make sure that for `French shop` `French` is set as default language.
6. Go to you profile, make sure that your language is set to `English` (from step 1.)
7. Open a new browser window in private navigation and go to `fr.localhost:8017/admin-dev`
8. Login and notice that everything is displayed in French and not in English.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

8.3

**Comment by AureRita** [comment]
Hi @lmeyer1 

Thank you for your report. I tried to reproduce your issue as you can see : 

first of all with a name after the normal name of the shop : 

https://user-images.githubusercontent.com/100699445/191779997-ebb27328-7ad8-46d6-a9f4-42b0838c1b15.mp4


after, by naming shops by itselfs, and I got this : 

https://user-images.githubusercontent.com/100699445/191780180-e03aeb29-b456-417c-a55c-232b84ddc3a2.mp4


Did you have all of your shop on local or with an host ? 

Waiting for your feedback

**Comment by lmeyer1** [comment]
@AureRita 
Hello, I don't really understand what you are doing. Both of your movies do not seem to be in relation with my bug report.
In the first movie, all your BO are in English. You do not show which shop has which languages associated, nor do you change the language of the employee in the profile.
In the second movie, you click on the link to see the FO. This seems completely unrelated.

To answer your question:
I had this bug on my production environment. Look at the URLs I provided, these are full URLs with domains. So yes I am on a hosting, I have several shops with several different domains. I think though, that you could reproduce this on a local install, if your shops are the URLs `localhost/shop-ab`, `localhost/shop-a` and `localhost/shop-b`, and when you access the admin area with `localhost/shop-ab/admin-dev`, `localhost/shop-a/admin-dev` and `localhost/shop-b/admin-dev` respectively. 
 don't know about `localhost/admin-dev`. It would probably show the same behavior as the default shop (id_shop = 1).

**Comment by AureRita** [comment]
@lmeyer1 

I will send you the long version of the video to let you see that there is a li,k to your issue : 

for the first one : 

https://user-images.githubusercontent.com/100699445/191789796-c8359957-03d0-4405-97c7-f8c7f4783f47.mp4


for the second one : 

https://user-images.githubusercontent.com/100699445/191789850-aeb7b90c-fba5-489e-b0c7-2cf3f70fb461.mp4

Currently, I think because i'm on localhost, I can't reproduce this issue, 

So we need to reproduce this issue, @PrestaShop/prestashop-maintainers some one can reproduce this issue with a prestashop hosted ?

**Comment by atomiix** [comment]
Hi @lmeyer1, I'm maybe missing something but I can't reproduce the issue:

https://user-images.githubusercontent.com/2168836/192317149-5738146f-8b15-4caf-8fa0-c2f7166d3bcb.mov

**Comment by lmeyer1** [comment]
OK, I will look at this closer. I have to publish a number of websites this and next week, so I cannot do it now.

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by lmeyer1** [comment]
@hibatallahAouadni 
I still have this problem on my installation. I'm investigating.
@atomiix Thank you for your screen record. I watched it with attention, and conclude that you followed well the setup, but you do not reproduce the issue.

**Comment by lmeyer1** [comment]
I updated the steps to reproduce, more concise, clearer and from scratch on a clean install.

**Comment by lmeyer1** [comment]
This is related to #27617.

**Comment by HanaRebaiQA** [comment]
Hello @lmeyer1 

Yes! as discussed, your issue is indeed a duplicate of https://github.com/PrestaShop/PrestaShop/issues/27617 
So, i'll close the issue.

Thank You

**Comment by HanaRebaiQA** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/27617
