### ISSUE TITLE
Cart rules are not removed from the cart when disabled

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#29710]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If you disable a cart rule from the configuration, it should be removed from the carts where it is applied when you upgrade the cart (add/remove a product)

### Expected behavior

The cart rule should be removed from the cart if it's disabled

### Steps to reproduce

1. Create a cart rule
2. Add a product to the cart and check that the cart rule is applied
3. Disable the cart rule
4. Update the cart, add a product, etc. The cart rule is not removed

### PrestaShop version(s) where the bug happened

1.7.8.7

**Comment by HanaRebaiQA** [comment]
Hello @idnovate 

Thanks fo your report.
Is one of these issues similar to yours [#25481](https://github.com/PrestaShop/PrestaShop/issues/25481
), [#19393](https://github.com/PrestaShop/PrestaShop/issues/19393), [#23757](https://github.com/PrestaShop/PrestaShop/issues/23757), [#15664](https://github.com/PrestaShop/PrestaShop/issues/15664) ?
Please check and feedback!

Thank You!

**Comment by idnovate** [comment]
Yes, it's similar.

Actually the problem is that cart rule is not refreshed/removed once applied if the conditions are not fulfilled any more :sweat_smile:

**Comment by hibatallahAouadni** [comment]
Hello @idnovate 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #19393. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

PS: thanks for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #19393

**Comment by idnovate** [comment]
I can't reproduce this issue in PS 8 but I can not see any commit for it in the related issue https://github.com/PrestaShop/PrestaShop/issues/19393.

Do you know if it has been fixed by any other PR?

Thanks.

**Comment by idnovate** [comment]
@hibatallahAouadni Do you remember any PR that fixed this in PS 8?
