### ISSUE TITLE
Exceed attribute combination limit

### ISSUE THREAD

**Issue by KiLiMaToS** [PrestaShop/PrestaShop#29738]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

I would have to work with about 1,300,000 combinations for one product.  Unfortunately, I cannot split the article into two or more parts.  How can this limit be shaken?

### Describe the solution you'd like

I tried to increase some php variables, I don't know if something needs to be done on phpmyadmin too

### Alternatives you've considered

I could think of using a module for custom attributes… but I would lose the ability to filter for these attributes

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @KiLiMaToS 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #10035. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #10035
