### ISSUE TITLE
Installer is not very clear about required php version 

### ISSUE THREAD

**Issue by nicosomb** [PrestaShop/PrestaShop#29730]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I tried to install Prestashop 1.7.8.7 with PHP 8.0.x version, but the installer tells me "PrestaShop requires PHP 7.4 or lower."

<img width="1080" alt="Capture d’écran 2022-09-23 à 14 23 55" src="https://user-images.githubusercontent.com/121870/191961230-d575b4f9-9caf-4199-9dd9-9d225e1b2bdd.png">

OK. 
So I switched to PHP 5.6.x (which is lower than 7.4 😁)

But the installer tells me "but PrestaShop requires PHP 7.1.3 or newer." 

<img width="1080" alt="Capture d’écran 2022-09-23 à 14 35 03" src="https://user-images.githubusercontent.com/121870/191961427-6be9d525-7e79-4a70-8ad1-277bd943e70d.png">

### Expected behavior

PrestaShop installer should give the correct range of accepted PHP versions. 

### Steps to reproduce

1. Have a PHP 8.0 version
2. Try to install PrestaShop 
3. Switch to PHP 5.6
4. Try to install PrestaShop 

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

PHP 5.6 or newer :D

**Comment by kpodemski** [comment]
You're right. The installer could be more precise, i.e. "The minimum required PHP version is X, and your PrestaShop will work with a maximum of PHP Y"

**Comment by hibatallahAouadni** [comment]
Hello @nicosomb 

Thanks for reporting the issue!
Seems to be a feature more than a bug. So I changed the labels :wink: 
We're waiting for your PR :rocket: 

Thanks!

**Comment by eshraw** [comment]
Hello @nicosomb thanks for the issue !

As discussed previously here is the expected behaviour : 
- Given that I have PHP installed
- When 
   - I install PrestaShop
   - And my PHP version is not supported
- Then the first sentence of the error message displays :
> Your server is running PHP _ABC_, PrestaShop needs a PHP version between PHP _CDE_ and PHP _GHI_.
