### ISSUE TITLE
Pas de connexion analytics 

### ISSUE THREAD

**Issue by Shabanafr** [PrestaShop/PrestaShop#29746]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Le code est inséré dans le module mais Google analytics ne le reconnaît pas.
![Screenshot_20220926-112248_Chrome](https://user-images.githubusercontent.com/114395331/192241161-eb30f9e8-0a97-4abc-845b-82c3c74b2e44.jpg)

![Screenshot_20220926-112428_Analytics](https://user-images.githubusercontent.com/114395331/192241583-af06c540-5cd3-45de-8b5f-9ed1b7e6f399.jpg)

### Steps to reproduce

Ajout du numéro de suivi sur le plugin. 
Visualisation sur Google Analytics 

### PrestaShop version(s) where the bug happened

1.7.7.0

### PHP version(s) where the bug happened

7.3.33

### If your bug is related to a module, specify its name and its version

Google Analytics v4.1.2

**Comment by hibatallahAouadni** [comment]
Hello @Shabanafr 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **Please send your request in English. English is the norm on GitHub**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thank you
