### ISSUE TITLE
Backoffice no menu between 1024 to 1040 pixels.

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#29745]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

There is no menu in backoffice at all, if the screen width is 1024 to 1040 pixels.

### Expected behavior

There should be mobile or desktop menu displayed.

### Steps to reproduce

1. Go to backoffice.
2. Hit F12.
3. Resize page to 1024 pixels wide.
4. See that there is no menu

### PrestaShop version(s) where the bug happened

develop

**Comment by NeOMakinG** [comment]
@Hlavtox wanna check yourself or I just take it?

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

I reproduce the issue only with PS1780, PS1787 see the attached screen record below:

[issue_29745.webm](https://user-images.githubusercontent.com/23308427/192604823-8b1d0434-4a45-41da-92d8-74f985fad0fb.webm)

@NeOMakinG if you remember we discover this regression together last year :sweat_smile: before releasing PS1.7.8.0 but it seems not reproducible on develop, see the attached screen record:

https://user-images.githubusercontent.com/23308427/192608082-e03afbcf-09a4-4982-8a96-d059d222501e.mp4

So @Hlavtox could you please execute this command and check if you still encounter this issue:
`cd admin-dev/themes/new-theme && rm -rf node_modules && npm i && npm run build`
Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
