### ISSUE TITLE
Error in paypal Property order->total product is not valid

### ISSUE THREAD

**Issue by pks891618** [PrestaShop/PrestaShop#29749]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After upgrade from 1.7.1 to latest version 1.7.8.7 getting error related to Paypal

Error in paypal Property order->total product is not valid

### Expected behavior

Customer should be able to place order after making payment.

### Steps to reproduce

1. add items to cart
2. Place order using Paypal credit card

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.2
![B738FB4C-894B-4103-9F3C-6F9DAC758E5F](https://user-images.githubusercontent.com/46920172/192261677-ab948d15-ac3b-43b6-8212-7655f61e6ebd.png)

### If your bug is related to a module, specify its name and its version

paypal v5.7.1

**Comment by hibatallahAouadni** [comment]
Hello @pks891618 

It seems that your issue is not a PrestaShop core bug.
If your module is PayPal Official, please contact support team on Addons

We will close this issue.

Thanks!
