### ISSUE TITLE
Autoupgrade - BO - A bad display on the PRE-UPGRADE CHECKLIST for the autoupgrade module 

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#29755]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

A bad display on the PRE-UPGRADE CHECKLIST for the autoupgrade module 

**Autoupgrade v4.15 : NOK** :x: 

Upgrade from PS1778 to 8.0 

![image](https://user-images.githubusercontent.com/92912932/192312066-860d46ea-61b4-44dd-95f1-8b89c017d215.png)

**It was OK v4.15 : OK** :heavy_check_mark: 

Upgrade from PS1778 to 8.0 

![image](https://user-images.githubusercontent.com/92912932/192312402-da09c68b-2919-4eef-933e-dbeaacca3c4a.png)

It's an autoupgrade module regression ! 

### Expected behavior

The previous display should be always OK with the autopupgrade module v4.15

### Steps to reproduce

1. Install PS1778 OR PS1786
2. Uninstall problematic modules (welcome, ps_mbo, pd_metrics, facebook, psxmarketingwithgoogle)
3. Install the autoupgrade v4.15 module from dev branch
4. Configure the autoupgrade module
5. See error ==> A bad display on the  `PRE-UPGRADE CHECKLIST`

### PrestaShop version(s) where the bug happened

1.7.7.8

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

autoupgrade v4.15.0 from dev branch

**Comment by hibatallahAouadni** [comment]
Hello @HanaRebaiQA 

I reproduce the issue only with dev branch of the module, while with the version 4.14.2 there's no error in the display.
So, indeed it's a regression!
Thanks @matthieu-rolland for your PR :rocket: 

Thanks!
