### ISSUE TITLE
BO>Auto-upgrade shows that maintenance mode is enabled while it's not

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#29758]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you use the latest version of the **1-Click auto-upgrade** module (`dev` branch) **v4.15.0** with any PS version, it shows that the maintenance mode is enabled while it's not, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/192346391-3a886a44-5a75-4b5c-bbbf-88f593196618.png)

### Expected behavior

It should show that the requirement **Your store is in maintenance mode** is not satisfied (as the caching feature when it's not disabled)

### Steps to reproduce

1. `git clone git@github.com:PrestaShop/autoupgrade.git`
2. `cd autoupgrade/`
3. `composer install`
4. `cd ..`
5. compress the folder `autoupgrade`
6. Install PS 1.7.7.8
7. BO>IMPROVE>Modules>Module Manager
8. Click on **Upload a module** button
9. A modal will display 
10. Drag and drop the `autoupgrade.zip` (that we prepared)
11. Install successfully
12. Click on **Configure**
13. See error > the maintenance mode is disabled while the module shows that it is enabled

![image](https://user-images.githubusercontent.com/23308427/192349408-9697d82f-dbab-4c07-880f-afe53c0788f4.png)

### PrestaShop version(s) where the bug happened

1.7.7.8 & 1.7.8.6 

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

autoupgrade v4.15.0 / dev

**Comment by atomiix** [comment]
@hibatallahAouadni what was the URL of your shop? If it's `127.0.0.1`, `::1` or `localhost`, this is the expected behavior as we consider local as maintenance

**Comment by mflasquin** [comment]
Friendly reminder @hibatallahAouadni :wink:

**Comment by matks** [comment]
So what @atomiix is saying is that this issue does not make sense in localhost environment. However in a 'true' hosting environment what happens?

**Comment by hibatallahAouadni** [comment]
Hello @atomiix & @mflasquin & @matks 

I tried again on PS1788 with store hosted on our server, I encounter another problem, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/210399063-5e427995-09c1-4518-87e1-28b021db5ee6.png)

It always shows `Enable maintenance mode` option is not statified even though it's already enabled.
Please check and feedback.

Thanks!

**Comment by atomiix** [comment]
That's right @hibatallahAouadni I can see that error too!
