### ISSUE TITLE
Weird non-translatable french helptext on search page

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#29761]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Since 1.7.7 and implementation of fuzzy search, there is a french help text with a link to github in search settings.

It should be removed, because:
- There is no reason for anything like this to be there. There is nothing like this in anywhere in the backoffice randomly in a form. This feature is not in development and is stable for two majors.
- It's permanently in french and not translatable.

![search](https://user-images.githubusercontent.com/6097524/192446694-12d331d7-86de-4cd8-adda-4490caad5391.jpg)

### Expected behavior

Remove the irrelevant links 

### Steps to reproduce

1. Open `Shop parameter > Search`
2. See the links

### PrestaShop version(s) where the bug happened

from 1.7.7 to develop

**Comment by sallemiines** [comment]
Hello @Hlavtox 

Thanks for reporting the issue :clap: 
I reproduce the issue with PS1778 PS1787 and PS80x. 
Ping @PrestaShop/product-team should we fix the translation and keep the links or should we remove the links?

Thanks for your PR :rocket:

**Comment by eshraw** [comment]
Hello @Hlavtox ,

Thanks for reporting this.
@sallemiines as Daniel said, there is no reason to have those link in this particular place. We should remove them from this particular place :)

Thanks for the PR !

**Comment by Hlavtox** [comment]
@eshraw Thanks Eshane, but try to think about where to put them, I think it's not a bad idea to have it in the help section or in the footer of backoffice. :-)

A small link called "Found some issue?", you click it, modal opens.
"You think something is not working right?"
"The best thing you can do now is to report it bla bla bla"

**Comment by MatShir** [comment]
Bottom of the menu ? 🤔
