### ISSUE TITLE
Free shipping cost based on cart total not applied when using a voucher 

### ISSUE THREAD

**Issue by alama456** [PrestaShop/PrestaShop#29770]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

This ticket is about applying a coupon with free shipping.

The problem appears when a carrier is configured to have a delivery costing 0€ from an amount in the basket, for example from 39€ of purchase on a zone as configured below:

![Shipping config](https://user-images.githubusercontent.com/43988121/192476275-770e0563-ed5b-4065-8c9a-d10029efc0b8.jpg)

We have a cart rule like this:

![cart rule](https://user-images.githubusercontent.com/43988121/192476507-f62b9374-dc7d-4704-bb31-5b6c96f8fddd.png)

If we buy products for an amount greater than €39, free delivery applies:

![Bug4](https://user-images.githubusercontent.com/43988121/192476901-f4a168dc-0907-480d-a969-4636cf675326.jpg)

If we apply the discount voucher in the basket, then the delivery is not free:

![Bug5](https://user-images.githubusercontent.com/43988121/192477125-6e85b936-a80d-4f6b-aa1e-d47fb846fd39.jpg)

One would expect shipping to remain free like on Prestashop 1.6 and expected when using a voucher to pay.

Tested on PS 1.7.8.3 to 1.7.8.6. On Prestashop 1.6.1.24, free delivery is applied when using the voucher.

Regards,

AM

### Expected behavior

Free delivery must be applied

### Steps to reproduce

1- create a cart rule with an amount voucher

2- Use a shipping method based on cart total amount and set up a 0€ delivery cost on a zone for a specific cart amount

3- Apply voucher and if the resulting total is < to the 0€ free shipping treeshold, the free delivery is not applied.

### PrestaShop version(s) where the bug happened

1.7.8.3, 1.7.8.4, 1.7.8.6

### PHP version(s) where the bug happened

7.2

**Comment by sallemiines** [comment]
Hello @alama456 

Thanks for reporting the issue
I reproduce the issue with PrestaShop versions **PS1.7.7.8**, **PS1.7.8.4**, you can see the issue here :



https://user-images.githubusercontent.com/31663369/192503300-5bc64081-c614-41a3-a221-f672400573b7.mp4

Thank you !

**Comment by sallemiines** [comment]
@alama456 

After discussing with QA-team, it seems that the expected behavior cause after applying the voucher the total price has been changed.




![image](https://user-images.githubusercontent.com/31663369/192514160-24d65ef6-ad0f-4e51-9aa2-fa824eae5d47.png)


Thanks for your understanding but I have to close the issue as this is the expected behavior :prière:
Thanks!
