### ISSUE TITLE
Compile Error on backoffice payment method page

### ISSUE THREAD

**Issue by IWSPHIL** [PrestaShop/PrestaShop#29775]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello

This error start appearing after migrate my website from a subdomain to the domain.

Compile Error: require_once(): Failed opening required '/home/u636811410/domains/islandwinestore.com/public_html/presta/modules/ps_wirepayment/ps_wirepayment.php' (include_path='/home/u636811410/domains/islandwinestore.com/public_html/vendor/pear/pear_exception:/home/u636811410/domains/islandwinestore.com/public_html/vendor/pear/console_getopt:/home/u636811410/domains/islandwinestore.com/public_html/vendor/pear/pear-core-minimal/src:/home/u636811410/domains/islandwinestore.com/public_html/vendor/pear/archive_tar:.:/opt/alt/php74/usr/share/pear')

[Symfony\Component\Debug\Exception\FatalErrorException 0]

Could you help me on this?

kind regards

### Steps to reproduce

Presta Back office

### PrestaShop version(s) where the bug happened

1.7.8

### PHP version(s) where the bug happened

8.0

**Comment by hibatallahAouadni** [comment]
Hello @IWSPHIL 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must fill the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
