### ISSUE TITLE
APIS02 - Implement an API Gateway

### ISSUE THREAD

**Issue by eshraw** [PrestaShop/PrestaShop#29777]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

This is a new feature. It aims to make at least one endpoint available to test API Security.

#### Description
As a developer
I want to call the API gateway endpoint when calling PS BO API
In order to call a service provided by the API

#### Business rules
- The API Gateway's endpoint is the only endpoint reachable --> TBD
- Developers cannot query API services directly

#### Acceptance tests
**Acceptance test 1**
Call the API Gateway endpoint to request XYZ
The expected answer of request XYZ is returned

**Acceptance test 2**
Try to call the API to request XYZ by bypassing the gateway
The request is blocked

### Additional context

Tentative subject, currently being explored by the working group. (27/09)

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by mflasquin** [comment]
As discussed, the role of API Gateway is taken by ApiPlatform

**Comment by eshraw** [comment]
As @mflasquin mentioned, @atomiix and him have confirmed that APIPlatform was taking the role of the API Gateway. As a result we'll consider this issue done once #30293 & #29931 are done and we will close this issue then.
