### ISSUE TITLE
APIS06 - Create API access  configurations

### ISSUE THREAD

**Issue by eshraw** [PrestaShop/PrestaShop#29789]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

This is a new feature. It aims to ensure that external applications querying PrestaShop's API are managed correctly through the use of OAuth scopes to handle permissions.

#### Description
As a shop admin
I want to be able to associate scope(s) to an API Access
So that this API Access can only impact selected ressources

#### Business rules
- A scope is one or multiple service related to a specific ressource (ex : customer)
- An API Access can have multiple scopes
- Scopes can be added to an API Access during the creation of an API Access
- Scopes can be added to an API Access after the creation of an API Access (through modification of said access)
- Scopes can be removed from an API Access after the creation of an API Access (through modification of said access)

#### Acceptance tests
**Acceptance test 1**
Try to create an API Access
I can add a scope to the API Access and complete the creation
The scope is displayed in the API Access detail page and the API Access client gets the expected return when querying the API service associated to the scope

**Acceptance test 2**
Try to create an API Access
I can add multiple scope to the API Access and complete the creation
The scopes are displayed in the API Access detail page

**Acceptance test 3**
Try to create an API Access
Add a scope to the API Access. Before the completion of the form, remove the scope.
The scope is not added to the API Access

### Additional context

[Figma link](https://cutt.ly/2MUXEgy)

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by Progi1984** [comment]
@fabienvallon Could you give us a public link for the Figma ? The link is not accessible for the community.

**Comment by Zoefinders** [comment]
related with https://github.com/PrestaShop/PrestaShop/issues/29811
