### ISSUE TITLE
Module natif "Produits Phares" Prestashop 1.7.5.1

### ISSUE THREAD

**Issue by porte-coulissante-shoji** [PrestaShop/PrestaShop#29784]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Bonjour, 

Le module natif "Produits Phares" Prestashop 1.7.5.1 ne peut être configuré correctement dans sa version v2.1.2

Avez-vous des solutions à m'apporter pour modifier/effacer le texte de subtitution qui apparaît sur la page d'accueil de mon site https://porte-coulissante-shoji.fr depuis la back office ?

"Incertus conducentia perviis suae saluti futuris remoti suae saluti industria cognito agitare industria conaretur conaretur suae itinera"

En vous remerciant,
Cdlt.

<img width="1335" alt="Capture d’écran 2022-09-27 à 20 01 53" src="https://user-images.githubusercontent.com/114517562/192602887-1ab45823-aa2f-479c-992d-f7e74ecd2cf8.png">

### Expected behavior

Pouvoir modifier le descriptif. Un texte de remplissage automatique apparaît sur la page de mon site.

### Steps to reproduce

Module manager
Modules du thème
Produits phares
v2.1.2 - par PrestaShop

### PrestaShop version(s) where the bug happened

1.7.5.1

**Comment by hibatallahAouadni** [comment]
Hello @porte-coulissante-shoji 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **Please send your request in English. English is the norm on GitHub**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thank you
