### ISSUE TITLE
Polish documentation 

### ISSUE THREAD

**Issue by Triloworld** [PrestaShop/PrestaShop#29787]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

As a user I like to read documentation in my own languages and as a agency I like to link documentation for client to use properly options in backend

### Describe the solution you'd like

Consider creating copy of repository https://github.com/PrestaShop/user-documentation-en and add me as a contributor to enable Polish translation to be added
Like to fork but now is only English version available for any Pull Request to start translations efforts

Like to add from ground up proper documentation based on existing one and extend developer version too

### Alternatives you've considered

Old version was imported : https://docs.prestashop-project.org/1-6-documentation/polska-dokumentacja

### Additional context

Like to know what about people behind translations regarding this tab: https://contributors.prestashop.com/

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by florine2623** [comment]
Hello @Triloworld ,

@PrestaShop/wording-managers will take a look and get back to you.

Thanks for the suggestion!

**Comment by l-delin** [comment]
Hello @Triloworld, 
Could you please contact me at documentation@prestashop.com to further discuss your request? Thanks! 🙌

**Comment by Triloworld** [comment]
> documentation@prestashop.com

Message send :)

**Comment by Triloworld** [comment]
Get information, we will start from tomorrow. Thx!
