### ISSUE TITLE
A bug of many  native modules 

### ISSUE THREAD

**Issue by sabrinaih** [PrestaShop/PrestaShop#29788]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi , 
I just installed the new version of prestashop and had to do it many times ( instal and disinstal ) due to a many tecnical problems , than while the configuration of the  platform i had many bugs especially when it's about to remove an original text or replace it , like in the modules of Custom text block and Image slider , when i click on configurate the texts don't appear ( in case I'm having access from my laptop )  or appear ( in case I'm having access from my phone )  but while I clear it and write my text don't let me save and skip to the original text , at the moment I just tried to configurate this two modules , I don't know if that are others modules with the same problem .
![2022-09-28](https://user-images.githubusercontent.com/114573674/192746969-b2900883-f581-4aeb-afe6-596a9164781d.png)

### Expected behavior

I hope that you can find a solution to this bugs , I used previeously the 1.6 version and had no problem with , this new version have many bugs that make persons losing time and customers . 

### Steps to reproduce

1.Dashboard prestashop
2. scroll down to modules 
3. click on module manager
4. scroll down to design and navigation
5. search custom text block and click on configurate
6. the window i attached previously will appear 

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.30

### If your bug is related to a module, specify its name and its version

Custom text block v 4.2.0 / Image slider v 3.1.1

**Comment by florine2623** [comment]
Hello @sabrinaih ,

I can't reproduce your issue.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
