### ISSUE TITLE
BO - Stats page data labels are too long in French

### ISSUE THREAD

**Issue by sLorenzini** [PrestaShop/PrestaShop#29792]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On 8.0.0 version, when I want to see my stats on "Sales and orders" tab, data labels above the graphic are too long in French. 

In English no problem. Same for small screens, it's all good.

French:

![statistics-sales-orders-tab-fr](https://user-images.githubusercontent.com/2854834/192785195-cfb0cf08-7cf4-4ff4-9958-eb819f6ae837.png)

English:

![statistics-sales-orders-tab-en](https://user-images.githubusercontent.com/2854834/192785081-16a334de-484f-42f7-9ae8-4bf7c4736fa9.png)

The bug is on 1.7.8.7 & 1.7.7.8 versions too. No regression

### Expected behavior

All data labels must be seperated by a spacing like in English

### Steps to reproduce

1. Go to BO > International > Localization > Add "French" language for example or another language than english
2. Go to icon profile on the header > Click on "Your profile" button
3. Change your default language by the French one
4. Click on  "Stats" entry on the left menu > Choose "Sales and orders" tab
5. See error of data labels above the graphic

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment]
Hello @sLorenzini 👋 ,

I reproduce the issue with PrestaShop version 1.7.8.7, 8.0.0, develop branch, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Arpit-Gulgulia** [comment]
Hi, I would like to contribute to work on this issue as part of the Hacktober fest. Is this issue open to assigning? 
Thanks!
