### ISSUE TITLE
Undefined variable in CategoryController.php

### ISSUE THREAD

**Issue by Texier54** [PrestaShop/PrestaShop#29799]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I reinstalled prestashop version 1.7.8.7 and in the file "controllers/front/listing/CategoryController.php" line 250 the variable "$category->active" in the if is undifined 

I saw in the code on gitlab that the variable is corrected but during the installation it is not 

This problem creates a display error 

<img width="1720" alt="Capture d’écran 2022-09-28 à 16 48 45" src="https://user-images.githubusercontent.com/14057257/192811503-64133590-d47c-4173-9516-2ba971a283cc.png">

### Expected behavior

The varaible should be $this->category->active

### Steps to reproduce

Install version 1.7.8.7, create a category and preview

### PrestaShop version(s) where the bug happened

 1.7.8.7

### PHP version(s) where the bug happened

7.4.30

**Comment by kpodemski** [comment]
Hey @Texier54 

Could you paste entire `getBreadcrumbLinks` here?

**Comment by Texier54** [comment]
public function getBreadcrumbLinks()
{
    $breadcrumb = parent::getBreadcrumbLinks();

    foreach ($this->category->getAllParents() as $category) {
        if ($category->id_parent != 0 && !$category->is_root_category && $category->active) {
            $breadcrumb['links'][] = [
                'title' => $category->name,
                'url' => $this->context->link->getCategoryLink($category),
            ];
        }
    }

    if ($this->category->id_parent != 0 && !$this->category->is_root_category && $category->active) {
        $breadcrumb['links'][] = [
            'title' => $this->category->name,
            'url' => $this->context->link->getCategoryLink($this->category),
        ];
    }

    return $breadcrumb;
}

**Comment by Hlavtox** [comment]
@Texier54 Already fixed in develop - https://github.com/PrestaShop/PrestaShop/blob/cceda1035efa55ad9da47c6a56db76220f938fa8/controllers/front/listing/CategoryController.php#L241

Wait a tiny bit for v8 and it will be solved. ;-)
