### ISSUE TITLE
BO - Responsive - Product page V1 -  bad display of offline/online button in footer page 

### ISSUE THREAD

**Issue by sLorenzini** [PrestaShop/PrestaShop#29795]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Offline/online button is not displayed correctly on small screen (between 1200px & 1473px precisely)
The button goes to a new line instead of staying beside the "Offline/Online" text.
Tested on:

8.0.0 ❌ 
- Offline

<img width="1425" alt="footer-pp1-offline-btn-800" src="https://user-images.githubusercontent.com/2854834/192792896-0dec7943-37e8-4b12-b381-0dae0ca717bc.png">

- Online

<img width="1428" alt="footer-pp1-online-btn-800" src="https://user-images.githubusercontent.com/2854834/192792931-73a39634-c10b-4fcd-ba73-b121e8a76c2b.png">

1.7.8.6 ✅ 
- Offline

<img width="1382" alt="footer-pp1-offline-btn-1786" src="https://user-images.githubusercontent.com/2854834/192793127-ff2112bb-d4b4-4da5-bb0f-2581cd67eb61.png">

- Online

<img width="1376" alt="footer-pp1-online-btn-1786" src="https://user-images.githubusercontent.com/2854834/192793166-5d382ba2-094c-4f2c-a04f-d9ae751157e7.png">

1.7.7.8 ✅
- Offline

<img width="1403" alt="footer-pp1-offline-btn-1778" src="https://user-images.githubusercontent.com/2854834/192793255-d5030eec-f31b-4781-862f-03f61b7f6a28.png">

- Online 

<img width="1422" alt="footer-pp1-online-btn-1778" src="https://user-images.githubusercontent.com/2854834/192793307-feff6e4c-b79d-4194-a63c-e061d65d147c.png">

It's a regression bug

### Expected behavior

The button should be beside the "Offline/Online" text.

### Steps to reproduce

1. Go to BO on a small screen (between 1200px & 1473px)
2. Go to Catalog > Products
3. Edit an online product, see error on the footer page of "Online" button
4. Go back to Products list page > Click on "New product" button
5. See error on the footer page of "Offline" button

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment]
Hello @sLorenzini 👋 ,

I reproduce the issue with PrestaShop version 8.0.0 and develop branch, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
