### ISSUE TITLE
Modules should be able to alter frontend sitemap

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#29796]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

When creating a blog or landing page module, you are unable to add variables (cleanly) to frontend sitemap page.

### Describe the solution you'd like

Add new hook to frontend sitemap to modify these URLS.

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by HanaRebaiQA** [comment]
Hello @Hlavtox 

Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments. 

Thank You for your PR

**Comment by PrestaEdit** [comment]
HI @Hlavtox,

What could be the point to allow a module to edit theses generated URLs ?

**Comment by Hlavtox** [comment]
Hi, I mostly did the hook to allow modules to add new ones. Easiest way is to just pass it as one array.

About edit scenario - I can imagine a developer that would like to remove some controllers he doesn't want customers to use for example.
