### ISSUE TITLE
Add available date for each combinations

### ISSUE THREAD

**Issue by fixo94** [PrestaShop/PrestaShop#29806]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

themes/xxx/templates/checkout/cart.tpl is not able to show good available date when the product have combination.

### Expected behavior

Add available_date on class Cart.php

### Steps to reproduce

1. add available date in a product combination
2. try to show {$product.available_date} in cart.tpl
3. the result will be 0000-00-00 instead good date

### PrestaShop version(s) where the bug happened

>= 1.7.6.9

**Comment by florine2623** [comment]
Hello @fixo94 ,

Can you send me the cart.tpl file so I can see what you changed ?
Also, a screenshot of the result in FO would be great.

Waiting for your feedback.
Thanks!

**Comment by fixo94** [comment]
Ok i find a way in override Cart.php line 194 :
$row['available_date'] = $additionalRow['available_date'];
Just before unset($additionalRow);

I think this line must be add in Cart.php
A screen of the result : 
![image](https://user-images.githubusercontent.com/8167966/192994716-0fe0724f-1b02-4bcd-bc83-b7fdfb0fcbc6.png)

**Comment by florine2623** [comment]
Ok, thanks.
So you solved the issue, right ? I can see that the date has the right format.

**Comment by fixo94** [comment]
Yes but i think this value need to be set for everybody. 
So a PR can be made.

**Comment by AureRita** [comment]
Hi @fixo94 ! 

as you fixed the issue, I will close the issue, if you want, you can [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
