### ISSUE TITLE
APIS10 - Create an App object in the BO to manage API accesses of external applications

### ISSUE THREAD

**Issue by eshraw** [PrestaShop/PrestaShop#29813]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

This is a new feature. It aims to allow the creation of APP objects to manage API accesses in the BO

#### Description
As a shop admin
I want to be able to create an App object in the BO
In order to create API access that is/are related to this app/module

#### Business rules
- An app has a generated appId
- An app has a creation date
- An app has a name (mandatory)
- An app has a description (optional)
- An app can have multiple API Access (i.e : 1 FO access, 1 BO access, 1 WS access)

#### Acceptance tests
**Acceptance test 1**
Create an App object in the BO w/ a name and a description
The app is created with a name and a description

**Acceptance test 2**
Create an App object in the BO w/ a name but no description
The app is created with a name only

**Acceptance test 3**
Try to create an app without a name in the BO
The creation funnel displays an error notifying that the app name is mandatory

**Acceptance test 4**
Create an App object in the BO w/ a name and a description
When displaying the app details I can see its name, its description, its creation date, its appId and its API access(es)

#### UI Tests
* Linked to 
https://github.com/PrestaShop/PrestaShop/blob/d672ad4ccc467722d13746e25fffc95a86e5e3b3/tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/01_internalAuthServer/02_resourceEndpoint.ts#L23-L24

### Additional context

[Figma link](https://cutt.ly/2MUXEgy)

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by Progi1984** [comment]
@fabienvallon Could you give us a public link for the Figma ? The link is not accessible for the community.

**Comment by fabienvallon** [comment]
[Figma public](https://www.figma.com/file/uaRxD74AMc98kLlyyhy0RM/Authorization-server-management?node-id=0%3A1&t=mR7xXT0QluOwlp3D-1)

**Comment by Progi1984** [comment]
@fabienvallon Not accessible : 
![image](https://user-images.githubusercontent.com/1533248/214536159-2f9e6dd7-46d1-4d9b-9afe-87020747cc91.png)

Normal : 
![image](https://user-images.githubusercontent.com/1533248/214537102-97ad864c-b400-417a-bb0d-d6713fc12a22.png)
