### ISSUE TITLE
FO: SEO minor bug in some languages

### ISSUE THREAD

**Issue by nitronco** [PrestaShop/PrestaShop#29814]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In some languages, such as Persian and Arabic, the "json_encode" function converts links with special characters into unintelligible characters. Google identifies these links incompletely and registers as a **404 error** for them in Google search console.
after some time, you can see them on Google search console as a **404 pages** (eg: "http://domain.com/1012-large_default")

### Expected behavior

We hope that the links will not be broken

### Steps to reproduce

1.     Upload an image with Arabic or Persian name for a product
2.     Goto above product page on FO
3.     Inspect page and see boken image link in Js variables (in the script tag)

### PrestaShop version(s) where the bug happened

1.7.8.5, 1.7.8.6

**Comment by florine2623** [comment]
Hello @nitronco ,

I added a product with title and image caption : المنتج الخاص بي
When I go to FO, I see the correct link :
<img width="459" alt="Screenshot 2022-09-29 at 14 11 29" src="https://user-images.githubusercontent.com/16019289/193028129-fe1387e3-1a5e-4a2c-84b4-00baf6e26bad.png">
Because my friendly URL is like this:
<img width="884" alt="Screenshot 2022-09-29 at 14 11 38" src="https://user-images.githubusercontent.com/16019289/193028142-8091d1d9-8223-4b3c-8e11-4f3cdeab70fc.png">

I can't reproduce your issue.
Could you give more info about it, and send screenshots of your case ?

Waiting for your feedback.
Thanks!

**Comment by nitronco** [comment]
Hello @florine2623 
Please note that there is no problem on the page except that inside the div tag with the "product-details" identifier, the information including the product image is created (data-product), which is incomplete. Google scans this link and displays it as a 404 link in Google Console.
As you can see in the second image, the name of the image becomes incomprehensible phrases and creates an incomplete link on the page, which is identified as (for example: https:\\domain.com\393-large_default) in Google Console and is met with a 404 error.



![1](https://user-images.githubusercontent.com/114002013/193406547-2bdc9048-10fd-43df-b664-e4a6a9fa3141.JPG)
![2](https://user-images.githubusercontent.com/114002013/193406550-cab277dc-0645-4392-87d8-afb987491988.JPG)

**Comment by AureRita** [comment]
Hello @nitronco, 

I tried to reproduce you issue as you can see : 

https://user-images.githubusercontent.com/100699445/193581424-4a0969d2-e49b-42bf-a232-a1cd3470e3bb.mp4

I checked the large_default and I didn't have the same result as you, I have the same things of @florine2623. 

Can you give us a video of all the process to reproduce your issue ? 

Waiting for your feedback

**Comment by nitronco** [comment]
> Hello @nitronco,
> 
> I tried to reproduce you issue as you can see :
> Untitled_.Oct.3.2022.2_47.PM.mp4
> 
> I checked the large_default and I didn't have the same result as you, I have the same things of @florine2623.
> 
> Can you give us a video of all the process to reproduce your issue ?
> 
> Waiting for your feedback

Hi
It's not in "product-image", you have to find "**product-data**" at <div id=product-details" ... , as I said before

**Comment by hibatallahAouadni** [comment]
Hello @nitronco 

Following your steps, this is what I got (see attached screen recording below):

[issue_29814.webm](https://user-images.githubusercontent.com/23308427/194122745-eb723006-05c2-4d3e-bfc6-06685d03d963.webm)

Do you mean when we only have `-.jpg` for the image name is a bug?
Please check and feedback.

Thanks!

**Comment by nitronco** [comment]
Hello @hibatallahAouadni 
Yes. As I said, Google crawler recognizes these links incompletely and causes a lot of 404 errors in the Google search console.
I have solved this problem in the same way for several shops in Persian language, and I thought it necessary to contribute to GitHub to solve the problem forever.

**Comment by hibatallahAouadni** [comment]
Hello @nitronco 

Could you please point to the issue if you see it in my screen record :pray: 
Cause I didn't see any issue :sweat_smile: 
Waiting for your feedback.

Thanks!

**Comment by nitronco** [comment]
Hi
Your test has a bigger bug that you need to fix it first: The name of the image has been completely removed.
If the image name is not removed, this problem will be visible in the product-data section.
The error in the Google console is as follows:
![photo_2022-10-12_11-50-51](https://user-images.githubusercontent.com/114002013/195290074-d63c04dc-c46e-4ef2-a1eb-79b79ea6e89d.jpg)

**Comment by AureRita** [comment]
Hi @nitronco , 

Thank you for your screenshot. Currently, we maybe need some videos to let us reproduce your issue, I tried, as you can see : 

[Untitled_ Oct 13, 2022 4_22 PM.webm](https://user-images.githubusercontent.com/100699445/195623614-59b805d2-cc4b-4b90-9668-0fc0855beff5.webm)

and I didn't Identify the issue, does the issue is that the name of the product isn't showed and it will be changed by "-" on the data-product ?

**Comment by nitronco** [comment]
Hi @AureRita 
You can check this page:
[https://mashinesoft.com/antifreeze-tester/1303-%D8%AA%D8%B3%D8%AA%D8%B1-%D8%B6%D8%AF%DB%8C%D8%AE-%D8%AE%D9%88%D8%AF%D8%B1%D9%88-lk-tools.html](https://mashinesoft.com/antifreeze-tester/1303-%D8%AA%D8%B3%D8%AA%D8%B1-%D8%B6%D8%AF%DB%8C%D8%AE-%D8%AE%D9%88%D8%AF%D8%B1%D9%88-lk-tools.html)
This product has images with Persian name. you can find broken image links in data-product section.
In google console: https://mashinesoft.com/2407-large_default | https://mashinesoft.com/2408-large_default and etc

**Comment by hibatallahAouadni** [comment]
Hello @nitronco 

Thanks for your patience :pray: 
Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a module problem.

We will close this issue.

Thanks!
