### ISSUE TITLE
Group access for categories is being checked even after disabling customer groups

### ISSUE THREAD

**Issue by daresh** [PrestaShop/PrestaShop#29820]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

PrestaShop keeps checking group access for categories, even after the "Customer groups" setting is set to NO.

### Expected behavior

Categories should be freely accessible after disabling "Customer groups"

### Steps to reproduce

1. Have some category assigned to only "customer" groups (visitor and guest unassigned).
![2022-09-30 10_30_57-Edit_ Art • 1 7 8 Dev — Firefox Developer Edition](https://user-images.githubusercontent.com/5658940/193227858-d4fcfea0-5e99-43df-9461-2f4e39c91c2e.png)
3. Have some product assigned only to this category and no other.
4. Try to visit both this category and this product while being a visitor - notice a "You do not have access..." error message.
5. Disable "Customer groups" in Performance settings.
6. Try to visit the category and product again, the product becomes visible, but the category page still gives a "You do not have access.." message.

### PrestaShop version(s) where the bug happened

1.7.8.x, 8.0.x

**Comment by Hlavtox** [comment]
@daresh Good catch, will be fixed by https://github.com/PrestaShop/PrestaShop/pull/29821

**Comment by MhiriFaten** [comment]
Hello @daresh ,

I was able to reproduce your issue using the same steps mentioned with PS1778, PS1787, PS178X PS80X and PS800

[Untitled_ Sep 30, 2022 12_36 PM.webm](https://user-images.githubusercontent.com/111756615/193253482-f1fb775f-aea9-481f-9cc7-769554856004.webm)

Thank you
