### ISSUE TITLE
BO - Modules - Titles & subtitles are too close on any configure module's page

### ISSUE THREAD

**Issue by sLorenzini** [PrestaShop/PrestaShop#29825]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I go on any configure module's page (contact form for the example), the title "Configure" is too close of the subtitle "Name of the module"

Tested on 8.0.x / 1.7.8.x / 1.7.7.8 version and the problem is on the 3 versions. No regression.

- 8.0.x ❌ 

![Capture d’écran 2022-09-30 à 14 57 10](https://user-images.githubusercontent.com/2854834/193276403-75a7c603-3d51-45ae-b5ea-6a885f1f6c36.png)

- 1.7.8.x ❌ 

![Capture d’écran 2022-09-30 à 14 57 03](https://user-images.githubusercontent.com/2854834/193276413-1131650a-a31b-486a-862b-00f61a2a9ead.png)

- 1.7.7.8 ❌ 
![Capture d’écran 2022-09-30 à 15 07 11](https://user-images.githubusercontent.com/2854834/193276385-e3c00bfd-c1cd-492c-a5fb-d8b06610f31d.png)

### Expected behavior

Title should have some bottom margin/padding to leave space with the subtitle
Or subtitle should have some top margin/padding to leave space with the title

### Steps to reproduce

1. Go to BO > Module manager
2. Search contact form module for example
3. Click on "Configure" button fo the module
4. See error in the header with the title & subtitle

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.3

**Comment by MhiriFaten** [comment]
Hello @sLorenzini ,

Thanks for your issue.
I was able to reproduce the issue using the same steps to reproduce with PS1778, PS1787 and PS8.0.x
