### ISSUE TITLE
SQL Manager - Help Button - Display all sub part like title 

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#29824]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

We have some sub part on the help button on SQL manager that are displayed like title on prestashop v8.0.0, you can see it on this screen : 
![image](https://user-images.githubusercontent.com/100699445/193264872-ffdeaea8-f8a7-4c39-a7f9-34a811d1e952.png)

this page is related to this one : 
https://app.gitbook.com/o/-MAz0PPl5s9ulE9xyliu/s/jyL8OZq59yY3Nomb341u/user-guide/configuring-shop/advanced-parameters/database/sql-manager
![image](https://user-images.githubusercontent.com/100699445/193265040-c7f73a53-f648-4e55-93f2-012839888e23.png)

### Expected behavior

We want the same result than the version 1.7.8.7 : 
![image](https://user-images.githubusercontent.com/100699445/193265233-33579107-ce22-4315-996c-e78b741bfecd.png)

this page is related to this one :
https://app.gitbook.com/o/-MAz0PPl5s9ulE9xyliu/s/-MCHq1J-FbQwQZ2OB1vQ/user-guide/configuring-shop/advanced-parameters/database/sql-manager
![image](https://user-images.githubusercontent.com/100699445/193271492-376bc7ef-d981-417c-ab40-d0e1bca89565.png)

### Steps to reproduce

1. Go to BO
2. Go to Advenced Manager > Database
3. Clic on Help button 
4. Scroll down and see the issue 

### PrestaShop version(s) where the bug happened

8.0.0 RC

### PHP version(s) where the bug happened

php 7.3

**Comment by MhiriFaten** [comment]
Hello @AureRita ,

Thanks for your issue.
I was able to reproduce the issue using the same steps to reproduce with PS800 and PS8.0.x **but not** with PS1787 and PS1778 so it's a regression.

**Comment by atomiix** [comment]
As the help.prestashop-project.org endpoint now uses the documentation from gitbook and not from confluence, you'll have in the BO what you have on gitbook: subtitles.
For the SQL queries themself, it's not title, it's the style for the `<code></code>` tag.
So I think this is the expected behavior.

**Comment by PrestaEdit** [comment]
As far I know, it's not resolved. Isn't it ?

**Comment by MatShir** [comment]
Seems to be a nice improvement actually, I close this issue
