### ISSUE TITLE
BO - Bad icon display on left menu in French or another long language

### ISSUE THREAD

**Issue by sLorenzini** [PrestaShop/PrestaShop#29826]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

"Shop parameters" icon is not aligned with the text in French language (not centered or on top).
Tested on 8.0.x / 1.7.8.x / 1.7.7.8 versions and it's not ok on those versions. No regression

- 8.0.x ❌ 

![Capture d’écran 2022-09-30 à 16 34 36](https://user-images.githubusercontent.com/2854834/193296092-75609198-8a8b-4167-bfed-0d78a5a88dd6.png)

- 1.7.8.x ❌ 

![Capture d’écran 2022-09-30 à 16 42 17](https://user-images.githubusercontent.com/2854834/193296141-a0688981-5cea-4025-8fc9-c54939299849.png)

- 1.7.7.8 ❌ 
- 
![Capture d’écran 2022-09-30 à 16 43 08](https://user-images.githubusercontent.com/2854834/193296172-99bcb757-42f1-4814-8340-75f14d8afb0d.png)

### Expected behavior

Icon should be centered beside the text or on the top

### Steps to reproduce

1. Go to BO > International > Localization > Add a language with long words like French one for example
2. Click on "profile" icon on top right of your shop > Click on "Your profile" button
3. Change your default language to French
4. See error, check on the left menu, "shop parameters" 's icon is not aligned correctly

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.3

**Comment by MhiriFaten** [comment]
Hello @sLorenzini ,

Thanks for your issue.
I was able to reproduce the issue using the same steps to reproduce with PS1778, PS178X and PS8.0.x
