### ISSUE TITLE
[FO] Wrong datas in order return with multiple products

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#29839]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The data is incorrect when making a return with several products (the reference and status).

### Expected behavior

The information displayed must be that of the current order return.

### Steps to reproduce

1 - Go to FO
2 - Order multiple different products
3 - Go to BO ( update order status set shipped)
4 - Go to SAV en enable order return feature
5 - Go to FO > My account > order history
6 - Return one product
7 - Return a second product  (NOTE : return the products one by one) 
8 - Go to FO > My account > Merchandise returns
9 - See the error : The reference and status of the first seconc (of first) is wrong

![Capture d’écran du 2022-10-03 11-54-22](https://user-images.githubusercontent.com/16455155/193550296-e34799ae-701f-4661-8319-6990720039bf.png)
hargements/Capture d’écran du 2022-10-03 11-54-22.png

### PrestaShop version(s) where the bug happened

1.7.8.7, develop

### PHP version(s) where the bug happened

N/A

**Comment by AureRita** [comment]
Hi @PululuK ,

I reproduce the issue with PrestaShop version1.7.8.7, as we can see on this video : 

https://user-images.githubusercontent.com/100699445/193598081-772158d8-fcad-49ec-9443-6c197f920429.mp4

I'll add this to the backlog so it can be fixed.

Thank you for your PR :rocket: 

Thanks
