### ISSUE TITLE
Page 2 of inside of CMS category return to root

### ISSUE THREAD

**Issue by Rubben1985** [PrestaShop/PrestaShop#29830]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Inside of a **category** CMS, when you have more than 1 page, if you go to the second page, it sends you back to the CMS root, page 1 instead of page 2 of that cms category.

Result: you can not navigate to the second page (or more) inside of a category CMS page

### Steps to reproduce

1. Go to BO > Design > Pages 
2. Add a new page category
3. In this new page category, Add 11 new page 
4. At the bottom, set "items per page" by 10
5. go to page 2 
6. Thats all, you have been "kick out" of the category to the root cms pagination

### PrestaShop version(s) where the bug happened

1.7.8.7 - 1.7.7.8 - 8.0.0

### PHP version(s) where the bug happened

7.4.30

**Comment by Rubben1985** [comment]
Here is the solution for TB fork (&PS 1.6?)
https://github.com/thirtybees/thirtybees/commit/844f9ec4d028d385c90f192c6b14a020165d54b6

I tried to apply it to PS 1.7 but files are differents.

**Comment by AureRita** [comment]
Hi @Rubben1985 

I reproduce the issue with PrestaShop version 1.7.8.7 and not with the version 1.7.7.8. Nice catch ! It's a regression ! I'll add it to the patch backlog.

You can see that the issue isn't always present, on this video : 

https://user-images.githubusercontent.com/100699445/193585339-fba8cfe1-c1e9-4a19-a97d-4e9910dbd372.mp4

Please be aware that some issues might take a very long time to be resolved. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Rubben1985** [comment]
Hi, it is not exactly that but I am glad that you have discover that too :)

It is inside backoffice, cms-> category cms.

**Comment by Rubben1985** [comment]
@AureRita

**Comment by MatShir** [comment]
@AureRita seems you have tested FO instead of the BO. Could you check it again ? 🙏

**Comment by Rubben1985** [comment]
here a video showing the problem.
Look how when I go to page 2 inside of a category, it goes again to page 2 of "inicio category" (home in Spanish) instead of the category I was into.
https://www.loom.com/share/a73e4eb71f284f939feae1411512d31e

**Comment by AureRita** [comment]
Hi @Rubben1985 

Thank you for this video to let met reproduce this issue, as you can see I reproduced also this issue : 

[Untitled_ Oct 10, 2022 5_26 PM.webm](https://user-images.githubusercontent.com/100699445/194901907-7fa72ea8-af0f-4325-8ebc-a54e683573ff.webm)

it's present in 1.7.8.6 and also on 1.7.7.8 
 I'll add this to the backlog so it can be fixed.

I will change your steps to reproduce to give us more info

Thanks

**Comment by AureRita** [comment]
Hi @Rubben1985 

I see that you replied to this issue few days agos : https://github.com/PrestaShop/PrestaShop/issues/10399

is it the same issue than you ?

**Comment by Rubben1985** [comment]
@AureRita it is not exactly the same, but if pagination is like a filter, could be due to the same or similar thing.

**Comment by paulnoelcholot** [comment]
Hello,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of [#10399](https://github.com/PrestaShop/PrestaShop/issues/10399).

Please be aware that some issues might take a very long time to be resolved.

It seem that you fix the issue on your end, can you [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by paulnoelcholot** [comment]
Duplicate of #10399
