### ISSUE TITLE
Target prestashop.com for samples in `ps_imageslider`

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#29836]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When installing `ps_imageslider`, the link targets `https://prestashop.com` rather than `prestashop-project.org`.

The source code can be easily change : https://github.com/PrestaShop/ps_imageslider/blob/ff498da9e415215dab303886f775c9f79b7f725c/ps_imageslider.php#L150

### Expected behavior

Following this EPIC #28771, that should target a `prestashop-project.org` endpoint.

### Steps to reproduce

1. Install `ps_imageslider`
2. Go to Front Office
3. The link of sliders targets `https://prestashop.com`

### PrestaShop version(s) where the bug happened

8.0.0

### If your bug is related to a module, specify its name and its version

ps_imageslider

**Comment by AureRita** [comment]
Hi @Progi1984 ,

Thank for your reprot, I reproduce the issue with PrestaShop version 8.0.0, I'll add this to the backlog so it can be fixed.
We can see your issue on this screen 
![image](https://user-images.githubusercontent.com/100699445/193591302-76548da4-5106-44f2-9d0a-37f0736d2ed0.png)


Please be aware that some issues might take a very long time to be resolved. 

Thanks
