### ISSUE TITLE
BO - Responsive - Update status button and list option status are not displayed correctly in order details page

### ISSUE THREAD

**Issue by sLorenzini** [PrestaShop/PrestaShop#29849]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On responsive screen (from 544px to 1599px), in order details page, the status section with status list option and "Update status" button are not displayed correctly on responsive screens.

Tested on 8.0.x / 1.7.8.x / 1.7.7.8 version. The issue is only on 8.0.x version. It's a regression

8.0.x ❌ 

[status-button-responsive.webm](https://user-images.githubusercontent.com/2854834/193612465-c0abb341-66f6-4232-a128-4a682b819469.webm)

<img width="1427" alt="status-button-80x" src="https://user-images.githubusercontent.com/2854834/193612636-b4ebc719-d670-4418-8e21-850aad69ce08.png">

1.7.8.x ✅ 

![status-button-178x](https://user-images.githubusercontent.com/2854834/193612864-179605f8-e180-4e40-8448-0ab0c8ef7873.png)

1.7.7.8 ✅ 

![status-button-1778](https://user-images.githubusercontent.com/2854834/193612879-94ab0ef9-1f56-46a3-b65d-62dc57647fe2.png)

### Expected behavior

Button and list should be stayed in its section like previous version on responsive screens

### Steps to reproduce

1. Go to BO > Orders > Orders
2. Choose an order > Scroll down to see "Status" section on the right of the page
3. Put your screen between 544px & 1599px > see error

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.3

**Comment by AureRita** [comment]
Hi @sLorenzini  ,

I reproduce the issue with PrestaShop version 8.0.0 and not with the version 1.7.8.7 Nice catch ! It's a regression ! I'll add it to the patch backlog.

Please be aware that some issues might take a very long time to be resolved. 

Thank you
