### ISSUE TITLE
Theme Customization module - Mobile - Disable mobile action is not working + bad display on tab on mobile screens

### ISSUE THREAD

**Issue by sLorenzini** [PrestaShop/PrestaShop#29848]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I want to disable theme customization module on mobile ONLY. I click on action button to disable it and go to Theme & logo page on mobile. 

First issue: 
"Pages configuration" & "Advanced customization" tab are still displayed. They should be removed in that case.

8.0.x ❌ 

![themecusto-disable-mobile-module-80x](https://user-images.githubusercontent.com/2854834/193587718-87073d47-41ad-4f55-9d4e-a18c9d9ad4db.png)

![themecusto-enabled-tab-80x](https://user-images.githubusercontent.com/2854834/193587834-0aecd198-84ef-48b2-bb55-786af2542e90.png)

1.7.8x ❌ 

![themecusto-ps178x](https://user-images.githubusercontent.com/2854834/193588001-9234f2f2-87d3-48c2-b611-64c4805ebc77.png)

1.7.7.8 ❌ 

![themecusto-ps1778](https://user-images.githubusercontent.com/2854834/193588014-2cbf9ecf-3bb8-4b38-9806-2b32788b91da.png)

2nd issue:
Furthermore, when we click on "Pages configuration" tab for example on mobile screen,  those 3 tabs are not aligned with a horizontally scroll like when we are "Theme & logo" tab. The top of the page is cropped.

"Theme & logo" tab active:
![themecusto-enabled-tab-80x](https://user-images.githubusercontent.com/2854834/193588266-27105ec5-2791-495e-81be-e91e359267cc.png)

"Page configuration" tab active:
![themecusto-enabled-tab-page-configuration-80x](https://user-images.githubusercontent.com/2854834/193588359-4418f79a-9b09-4b50-9e5a-819c75655e09.png)

"Advanced customization" tab active:
![themecusto-enabled-tab-advanced-customization-80x](https://user-images.githubusercontent.com/2854834/193588341-a6dc9c06-4df4-4d48-9941-9a080d9b1137.png)

Tested those issue on 8.0.x / 1.7.8.x / 1.7.7.8 versions and v1.2.1 version of ps_themecusto module.

### Expected behavior

First issue: tabs should be removed when the module is disable on mobile
Second issue: tabs should be aligned on mobile with an horizontally scroll

### Steps to reproduce

Go to BO > Module Manager > Search ps_themecusto

First issue:

- Click on "Disable Mobile" button > Success message displayed
- Change your browser on mobile screen > go to Design > Theme & Logo page
- See error, "Pages configuration" & "Advanced customization" tab are displayed

Second issue:

- Change your browser on mobile screen > go to Design > Theme & Logo page
- See that an horizontally scroll is displayed when "Theme & logo" tab is active
- Click on  "Pages configuration" or "Advanced customization" tab
- See error, scroll is removed, tabs are not aligned, top of the page is cropped

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_themecusto v1.2.1

**Comment by AureRita** [comment]
Hi @sLorenzini ,

I reproduce the issue with PrestaShop version 1.7.7.8, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved.
Thanks

**Comment by Hlavtox** [comment]
Firstly - the feature only controlled behavior in front office, not backoffice.
Secondly - enable/disable on mobile was removed on develop.
