### ISSUE TITLE
Problem with product customization upload

### ISSUE THREAD

**Issue by PereGE** [PrestaShop/PrestaShop#29852]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I have a website, where all products must necessarily have a file uploaded by the client. Once the file is uploaded, choose the attributes and characteristics and it is added to the cart.

Well, if you do this always with the same "configuration" of attributes and characteristics, they are added fine, the problem appears when you change these attributes, for example, instead of selecting X, you select Y and upload it to the cart. Something "strange" happens there, and the product is added, but the attached file uploaded by the client is lost.

If we look at the database, the file has been successfully uploaded to the [ps_customized_data] table, but if we go to see the relationship with the product in the cart ([ps_cart_product]t table), there the id_suctomization appears in 0, instead of the file id.

### Steps to reproduce

1. Go to https://aquitutransfer.com/inicio/2-crea-y-ordena-tu-transfer.html
2. Upload the ai, psd, png, pdf file and save it
3. Add the product without modifying anything else
4. Go back to MAKE YOUR ORDER from the menu
5. Upload the ai, psd, png, pdf file and save it
6. Change some fields, for example select "Metro"
7. Add the product

And that's where the problem starts.

### PrestaShop version(s) where the bug happened

1.7.8.6

**Comment by alfonsolr09** [comment]
hola, debes escribir en inglés para obtener alguna respuesta.
hello, you must write in English to get any response.

**Comment by PereGE** [comment]
I have a website, where all products must necessarily have a file uploaded by the client. Once the file is uploaded, choose the attributes and characteristics and it is added to the cart.

Well, if you do this always with the same "configuration" of attributes and characteristics, they are added fine, the problem appears when you change these attributes, for example, instead of selecting X, you select Y and upload it to the cart. Something "strange" happens there, and the product is added, but the attached file uploaded by the client is lost.

If we look at the database, the file has been successfully uploaded to the [ps_customized_data] table, but if we go to see the relationship with the product in the cart ([ps_cart_product]t table), there the id_suctomization appears in 0, instead of the file id.

**Steps to reproduce**

1.- Go to https://aquitutransfer.com/inicio/2-crea-y-ordena-tu-transfer.html

2.- Upload the ai, psd, png, pdf file and save it

3.- Add the product without modifying anything else

4.- Go back to MAKE YOUR ORDER from the menu

5.- Upload the ai, psd, png, pdf file and save it

6.- Change some fields, for example select "Metro"

7.- Add the product

And that's where the problem starts.

**Comment by hibatallahAouadni** [comment]
Hello @PereGE 

Following your steps I didn't encounter any issue.
Did you try to reproduce the issue with the Classic theme? and could you please provide a screen record :pray: 
Waiting for your feedback.

Thanks!

**Comment by PereGE** [comment]
Hello @hibatallahAouadni, Thanks for your answer, but the problem is still there.

I am attaching screenshots of the tests with the native theme.

**Image 1**
![image_1](https://user-images.githubusercontent.com/114938787/194018888-caa4e6f9-8627-4662-9d3c-414eaef9fc6d.png)

**Image 2**
![image_2](https://user-images.githubusercontent.com/114938787/194018884-e8b896ae-fa8e-4229-96e4-7e08b6ab97bc.png)

**Image 3**
![image_3](https://user-images.githubusercontent.com/114938787/194018875-0f63addd-78ba-4fd8-9e27-e1235c649b96.png)

**Image 4**
![image_4](https://user-images.githubusercontent.com/114938787/194018862-df763bd3-770f-46d7-a3ec-8e3452ae02fa.png)

**Image 5**
![image_5](https://user-images.githubusercontent.com/114938787/194018850-2c1a65c4-4e81-4330-a306-204be2afc502.png)

**Comment by florine2623** [comment]
This has been fixed with https://github.com/PrestaShop/PrestaShop/pull/29635

**Comment by misbolsosonline** [comment]
Como subir archivos pdf poe le cliente la web es  [dtf por metros](https://ideagift.es/dtf-por-metros-228)
