### ISSUE TITLE
Duplicate type casting in ps_facetedsearch module

### ISSUE THREAD

**Issue by leemyongpakvn** [PrestaShop/PrestaShop#29869]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

In https://github.com/PrestaShop/ps_facetedsearch/blob/dev/ps_facetedsearch.php, there are some problems with type casting:

1.  `(int) $idCategory` is called 18 times throughout `function rebuildLayeredCache`. 
2.  `(int) $idCategory`,  (int) $idShop,  (int) $limit,  (int) $type, (int) $n are called 8 times (for each variable) throughout `function buildLayeredCategories`

They are redundant and need to be simplified.

Steps to reprodure:
1. Check [function rebuildLayeredCache](https://github.com/PrestaShop/ps_facetedsearch/blob/dev/ps_facetedsearch.php#L1023-L1085)
3. Check [function buildLayeredCategories](https://github.com/PrestaShop/ps_facetedsearch/blob/dev/ps_facetedsearch.php#L1125-L1182)
4. Check [Files changed](https://github.com/PrestaShop/ps_facetedsearch/pull/719/files) for a whole view

### Describe the solution you'd like

Assign `$id_xyz = (int) $id_xyz` once at the beginning of foreach loop, just use `$id_xyz` in the rest.

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @leemyongpakvn 

Thank you for your suggestion and for your PR :rocket:  
The Maintainer Team will take it into consideration for future developments. 

Thank you

**Comment by leemyongpakvn** [comment]
Many changes after one year. This minor improvement can be done in the future.
