### ISSUE TITLE
FO - product quickview : “Write your review” is unclickable

### ISSUE THREAD

**Issue by MhiriFaten** [PrestaShop/PrestaShop#29863]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The button **write your review** is not clickable

[Untitled_ Oct 4, 2022 3_33 PM.webm](https://user-images.githubusercontent.com/111756615/193838244-63435b3d-c68a-4a8b-868e-886db6bab80b.webm)

### Expected behavior

The button **write your review** should not be displayed in the quick view.

### Steps to reproduce

1. Go to FO > Home page
2. Choose the product with combinations and click on **Quick view**
3. Change the combination (exp: dimension, size)
4. See error > The button **write your review** will appear and it is unclickable 

### PrestaShop version(s) where the bug happened

1.7.7.8 , 1.7.8.7 & 8.0.0

### PHP version(s) where the bug happened

7.4 , 8.0

**Comment by sallemiines** [comment]
Hello @MhiriFaten 

Thanks for reporting the issue 
I reproduce the issue with PS1778 PS1787 and PS800,  you can see the issue here :


https://user-images.githubusercontent.com/31663369/194101845-248f656d-7183-4008-81eb-17f211351132.mp4

Thank you !

**Comment by dennisgon** [comment]
Can you assign it to me? I will help to solved the bug

**Comment by MatShir** [comment]
Thanks @dennisgon, you are assigned now. We will be happy to review your PR :)

**Comment by dharmik9829** [comment]
Hello there, i can solve this can you assign to me?

**Comment by dharmik9829** [comment]
> Thanks @dennisgon, you are assigned now. We will be happy to review your PR :)
Hello is this issue closed? if not than i work on it and incase if it is closed can you me a new issue, this is my first time i am trying in contribution

**Comment by MatShir** [comment]
@dharmik9829 great to hear! Assigned!

**Comment by leemyongpakvn** [comment]
@MhiriFaten and @MatShir I think clients are **not** allowed to post comment in _Listing View_ and _Quick View_. So the Expected behavior is: the button **Write your review** will not be showed in Quick View modal in any case.

**Comment by MatShir** [comment]
So the specs should be: hide the button 'Write your review' in the quick view modal ?
It does make sense. Write a review button have a better place in the order history for example than on the modal quick view

**Comment by leemyongpakvn** [comment]
That's it. At least, it is the original design as written at [productcomments.php#L1047-L1049](https://github.com/PrestaShop/productcomments/blob/v6.0.2/productcomments.php#L1047-L1049). We only can see the numbers of comments and the average grade (if any) in QuickView modal.
