### ISSUE TITLE
FO Responsive - Zoom on product image stretches the images

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#29865]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I use my tablet and zoom on a product, the image is stretched.

<img width="881" alt="Screenshot 2022-10-04 at 15 58 35" src="https://user-images.githubusercontent.com/16019289/193842520-1addf032-6f94-4df7-9647-bd76e7412870.png">

It's a 1.7.7.8 regression.

### Expected behavior

It should keep the same format.

<img width="633" alt="Screenshot 2022-10-04 at 16 17 42" src="https://user-images.githubusercontent.com/16019289/193843762-6e00264c-fec0-4ca7-a705-c77083e92729.png">

### Steps to reproduce

1. Use tablet or responsive mode with iPad Air for example
2. Click on + button to zoom image
3. See stretched image

### PrestaShop version(s) where the bug happened

1.7.8.7, 8.0.0

### PHP version(s) where the bug happened

7.4, 8.0

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/29910 on 1.7.8 but still need to be tested for Classic theme for PS 8.0.0

**Comment by matks** [comment]
https://github.com/PrestaShop/PrestaShop/pull/29910 also merged : this issue if fixed!
