### ISSUE TITLE
FO Quickview - On sale, New, Discount, Web only flags are not displayed

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#29862]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Might be related to : https://github.com/PrestaShop/PrestaShop/issues/16633
It is not a regression as reproduced on 1.7.7.8, 1.7.8.7 and 8.0.0.

For all types of product (combination, virtual, standard, pack), no flag is displayed on the quick-view modal.

https://user-images.githubusercontent.com/16019289/193835372-321f8705-9717-421d-b35e-9101e27775a6.mov

### Expected behavior

All flags should be displayed in the quick view modal.

### Steps to reproduce

1. Go to BO > Product > Choose product > Add On Sale, Web only, New, Discount flag to product
2. Go to FO > Quick view this product
3. No flag displayed :x:

### PrestaShop version(s) where the bug happened

1.7.7.8, 1.7.8.7, 8.0.0

### PHP version(s) where the bug happened

7.4, 8.0

**Comment by paulnoelcholot** [comment]
Hello @florine2623 ,

I reproduce the issue with PrestaShop version 1.7.6/1.7.8 and 8.0.x , I'll add this to the backlog so it can be fixed.


Thank you

**Comment by Hlavtox** [comment]
Expected behavior, it's using a different template without flags.
