### ISSUE TITLE
Autoupgrade - BO - Position page & AdminGroup Page - An exception is displayed when the welcome is not uninstalled before the upgrade

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#29867]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On the BO > Design > Positions page an exception is displayed
![image](https://user-images.githubusercontent.com/16067358/193847159-8cfa06ee-9da2-43e6-be63-adf7c773be59.png)

### Expected behavior

No exception displayed

### Steps to reproduce

1. Install PS1787
2. Use the release of autoupgrade.zip (v4.15)
3. Go to 1-click upgrade > Configure
4. Enable the Disable non-native module option
5. Do not uninstall the problematic modules
6. Under auto-upgrade > Download > Use the .zip for the 8.0.0 RC
7. Upgrade from PS1787 to PS8.0.0 RC
8. Check that the upgrade to 8.0 is OK
9. Check that the welcome module is disabled
10. GO to BO > Design > Position page (debug mode enabled)
11. See exception
12. Go to BO > Shop Parameters > Customer Settings > Groups page
13. Click on Add a new group / edit a group
14. See exception

### PrestaShop version(s) where the bug happened

8.0.0RC

### PHP version(s) where the bug happened

7.4, 7.3

### If your bug is related to a module, specify its name and its version

autoupgrade v4.15.0, Welcome V6.0.7

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/welcome/pull/147
