### ISSUE TITLE
Sats dashboard does not appear in menu

### ISSUE THREAD

**Issue by okapicarton** [PrestaShop/PrestaShop#29878]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![Captura de pantalla 2022-10-05 122041](https://user-images.githubusercontent.com/115081522/194052406-90962921-bcd3-4a41-a312-415320d92e75.png)
I cant access my stats dashboard (the one original from prestashop) direcly from ty vertical menu backoffice. I only have the option of prestashop metrics. I even uninstall the Prestashop Metrics to try to solve the problem, but it still does not appear. To go and see the dashboard I have to go to the module manager and find the Stats dashboard and click on configuration. Please tell me what to do, right know I have nothing.
![Captura de pantalla 2022-10-05 134429](https://user-images.githubusercontent.com/115081522/194052798-c1b1c0ae-2c78-4488-a469-31155ac636d9.png)

### Steps to reproduce

1. See the vertical backoffice menu
2. Try to find the stats module beneath the client service
3. Never appears but it is install
4. Go to module manager
5. Look for stats dashboard
6. see that in the right it says configuration

### PrestaShop version(s) where the bug happened

1.7.7.4

**Comment by hibatallahAouadni** [comment]
Hello @okapicarton 

I didn't manage to reproduce the issue with PS1770 and PS1774, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/194114479-6cb96327-519f-46b6-a92d-041fdcb8e9fb.png)

Neither with PS8.0.0, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/194114676-fb7e257c-077a-4f00-8ff8-60f27b6e825f.png)

Closing the issue as it's not related to the Core. It may related to non-native module.

Thanks!

**Comment by okapicarton** [comment]
Hello, the issue is NOT RESOLVED because the screen shots are from one shop (Encajando.es) which is the one that has the access to Stats. But it is the other site, okapi.es, the one that doesn’t. I am still facing the same problem.

***@***.***

 

 

Un saludo,

firma lola-01-01

¡Síguenos en redes!
      <https://www.linkedin.com/company/soyokapi/>    <https://www.instagram.com/soyokapi/>    <https://www.facebook.com/soyokapi/> 

 

De: Hibatallah Aouadni ***@***.*** 
Enviado el: miércoles, 5 de octubre de 2022 18:41
Para: PrestaShop/PrestaShop
CC: okapicarton; Mention
Asunto: Re: [PrestaShop/PrestaShop] Sats dashboard does not appear in menu (Issue #29878)

 

Hello @okapicarton <https://github.com/okapicarton> 

I didn't manage to reproduce the issue with PS1770 and PS1774, see the attached screenshot below:

 <https://user-images.githubusercontent.com/23308427/194114479-6cb96327-519f-46b6-a92d-041fdcb8e9fb.png> image

Neither with PS8.0.0, see the attached screenshot below:

 <https://user-images.githubusercontent.com/23308427/194114676-fb7e257c-077a-4f00-8ff8-60f27b6e825f.png> image

Closing the issue as it's not related to the Core.

Thanks!
