### ISSUE TITLE
1 Click upgrade module does not get uploaded

### ISSUE THREAD

**Issue by B-spot** [PrestaShop/PrestaShop#29873]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi! I downloaded the [1-Click Upgrade Module] to use it on our prestashop eshops in order to update to the latest version but for some reason it does not get uploded in my modules area.

### Expected behavior

To have the module uploaded - up and running

### Steps to reproduce

1. Go to Module Manager
2. Click on "Upload a Module."
3. Drag and Drop the "1-Click upgrade" module from my desktop to the specified box or by browsing my desktop files 
![Screenshot_1](https://user-images.githubusercontent.com/115078518/194046921-d80f9e04-baa4-42d7-a517-22696c326a3b.png)

### PrestaShop version(s) where the bug happened

1.7.6.8

### If your bug is related to a module, specify its name and its version

1-Click Upgrade Module

**Comment by hibatallahAouadni** [comment]
Hello @B-spot 

I didn't reproduce the issue with the provided infos, could you please provide your 1-Click Upgrade Module version :pray: 
Waiting for your feedback.

Thanks!

**Comment by B-spot** [comment]
Hi!
Well, the version is v4.14.2 https://github.com/PrestaShop/autoupgrade/releases/tag/v4.14.2 but you can either download the zipped file from here: https://we.tl/t-Ef9vuBJsg8 
or you can also download it from GitHub, this was from where I downloaded it yesterday: https://github.com/PrestaShop/autoupgrade

Thanks

**Comment by hibatallahAouadni** [comment]
Hello @B-spot 

Could you please follow my steps:

1. **BO**>**IMPROVE**>**Modules**>**Module Catalog**
2. Search for **`1-Click autoupgrade`** module
3. Click on **`Install`** button
4. The module is successfully installed :tada: 

Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @B-spot 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
