### ISSUE TITLE
SSL cannot be disabled Prestashop 8.0

### ISSUE THREAD

**Issue by ValentinGratz** [PrestaShop/PrestaShop#29877]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

I downloaded the beta version 8.0 to test it in localhost.

On the other hand, without doing it on purpose, I activated SSL, and I can't deactivate it.

I have searched the forums and github in the database. I can't find the **PS_SSL_ENABLED** line in the **ps_configuration** table.

Is this normal?

Source of the forum in french: [
Source of the forum: https://planethoster.live/threads/desactivator-ssl-sur-prestashop-sans-backoffice-desactivator-https.2053/](https://planethoster.live/threads/desactivator-ssl-sur-prestashop-sans-backoffice-desactivator-https.2053/)

### Steps to reproduce

1. Install Prestashop 8.0 by activating SSL via the installation setup
2. Access the site url like this: https://localhost/prestashop8/

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by florine2623** [comment]
Hello @ValentinGratz ,

It depends on how your localhost is configured to use SSL.

You should be able to do these steps:
<img width="1206" alt="Screenshot 2022-10-06 at 16 35 10" src="https://user-images.githubusercontent.com/16019289/194341921-6cdc3434-d5c5-4883-8c69-2d6712e6b35d.png">
<img width="1206" alt="Screenshot 2022-10-06 at 16 35 16" src="https://user-images.githubusercontent.com/16019289/194341933-2c6359de-d564-4632-be43-e1271565082e.png">
<img width="1204" alt="Screenshot 2022-10-06 at 16 35 22" src="https://user-images.githubusercontent.com/16019289/194341971-7fda886e-760d-426e-b0b6-8572af1cfd49.png">

In the database, when SSL is disabled:
<img width="1048" alt="Screenshot 2022-10-06 at 16 35 45" src="https://user-images.githubusercontent.com/16019289/194341987-ff3e65cd-d41e-462a-95fe-187906e43f71.png">
When SSL is enabled, the value is 1.

Please check and feedback.
Thanks!

**Comment by ValentinGratz** [comment]
Thanks, in my case I'm talking about disabling it from the database for 8.0.0 beta.

On the other hand in the database, I can't find any line PS_SSL_ENABLE, I looked in all the tables, they are no longer there

table : ps_configuration
![ligne_introuvable](https://user-images.githubusercontent.com/39189263/194362517-1cd1b780-0095-459c-b2d9-02e0d18dfd02.png)

The only solution I found (in localhost) was to totally reinstall prestashop.

**Comment by florine2623** [comment]
Can you go to page 2 or display all lines of the table ?

**Comment by ValentinGratz** [comment]
Thank you, I hadn't seen the few pages there were, and I was no longer used to the multitude of tables.

I am closing this open ticket for nothing, if I may say so.

I apologize.

**Comment by florine2623** [comment]
It's okay ^^
Have a nice day!
