### ISSUE TITLE
Bug Installation PrestaShop 8 last step. Error Install theme. HTTP 500 - error

### ISSUE THREAD

**Issue by Prestapro** [PrestaShop/PrestaShop#29875]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I'm using Mamp Pro and Mac OS and I'm getting an error at the last step in the template installation process. Installation is 56% complete.
[Screenshot](https://prnt.sc/08f_MHvVCxe-)
How to complete the installation?
Thank you.

### Steps to reproduce

1. Install Mamp
2. Download PrestaShop
3. Start the installation process

### PrestaShop version(s) where the bug happened

8.0

### PHP version(s) where the bug happened

7.2.34

**Comment by sallemiines** [comment]
Hello @Prestapro 

Thanks for this issue .
Could you please advise which theme you are using? did you try to install the store with the default theme or did you use another theme?

Please check feedback ! :pray:

**Comment by Prestapro** [comment]
Hi,
Yes, this is the default template.

**Comment by florine2623** [comment]
Hello @Prestapro ,

I can't reproduce your issue using Mamp Pro PHP 7.4.

https://user-images.githubusercontent.com/16019289/194363264-2b7fe041-0c8f-4a64-827c-b35d8da66605.mov

Please update your PHP version and try again.

I will close your issue as it can't be reproduced.
Thank you for your understanding.

**Comment by matks** [comment]
@Prestapro look for logs, it could be plenty things. Wrong permissions, network issue... but installation on a 'standard env' works

**Comment by walid-elmrabet** [comment]
@Prestapro  i have php 8 but and i use xamp, why am i getting this error
![Capture d’écran 2024-04-06 171323](https://github.com/PrestaShop/PrestaShop/assets/101744880/6ea562de-6f40-468f-b8ca-8b8d6054a863)

**Comment by dmcoelho** [comment]
I have the same error, when try install prestashop.
i'm using xampp, and i try with php version 8.2, 8.0.30 and 8.0.0. the installation stop every time in the same zone.
After try phppsinfo.php, tells me the app/Resources/translations is no writable. i check and the folder have full permissions

**Comment by matks** [comment]
Hello can you look inside your PHP error logs?

**Comment by dmcoelho** [comment]
Hi @matks 

I create the folder and file, and retry the process, and recive this information

[26-Apr-2024 10:52:00 Europe/Lisbon] PHP Warning:  Attempt to read property "theme_name" on null in C:\xampp\htdocs\WebStore\var\cache\prod\ContainerXBS8ohR\appAppKernelProdContainer.php on line 2907
[26-Apr-2024 10:52:01 Europe/Lisbon] PHP Notice:  stream_copy_to_stream(): Read of 8192 bytes failed with errno=13 Permission denied in C:\xampp\htdocs\WebStore\vendor\symfony\symfony\src\Symfony\Component\Filesystem\Filesystem.php on line 66
[26-Apr-2024 10:52:02 Europe/Lisbon] PHP Warning:  filemtime(): stat failed for C:\xampp\htdocs\WebStore\var\cache\prod\ContainerXBS8ohR\appAppKernelProdContainer.php in C:\xampp\htdocs\WebStore\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand.php on line 109
[26-Apr-2024 10:52:02 Europe/Lisbon] PHP Warning:  require(C:\xampp\htdocs\WebStore\var\cache\prod\ContainerXBS8ohR\getConsole_Command_CacheWarmupService.php): Failed to open stream: No such file or directory in C:\xampp\htdocs\WebStore\var\cache\prod\ContainerXBS8ohR\appAppKernelProdContainer.php on line 2255
[26-Apr-2024 10:52:02 Europe/Lisbon] PHP Warning:  require(C:\xampp\htdocs\WebStore\var\cache\prod\ContainerXBS8ohR\getSwiftmailer_EmailSender_ListenerService.php): Failed to open stream: No such file or directory in C:\xampp\htdocs\WebStore\var\cache\prod\ContainerXBS8ohR\appAppKernelProdContainer.php on line 2255
[26-Apr-2024 10:52:02 Europe/Lisbon] PHP Fatal error:  Uncaught Error: Failed opening required 'C:\xampp\htdocs\WebStore\var\cache\prod\ContainerXBS8ohR\getSwiftmailer_EmailSender_ListenerService.php' (include_path='C:\xampp\htdocs\WebStore\vendor/pear/pear_exception;C:\xampp\htdocs\WebStore\vendor/pear/console_getopt;C:\xampp\htdocs\WebStore\vendor/pear/pear-core-minimal/src;C:\xampp\htdocs\WebStore\vendor/pear/archive_tar;C:\xampp\php\PEAR') in C:\xampp\htdocs\WebStore\var\cache\prod\ContainerXBS8ohR\appAppKernelProdContainer.php:2255
Stack trace:
#0 C:\xampp\htdocs\WebStore\var\cache\prod\ContainerXBS8ohR\appAppKernelProdContainer.php(2669): ContainerXBS8ohR\appAppKernelProdContainer->load('getSwiftmailer_...')
#1 C:\xampp\htdocs\WebStore\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\EventDispatcher.php(301): ContainerXBS8ohR\appAppKernelProdContainer->ContainerXBS8ohR\{closure}()
#2 C:\xampp\htdocs\WebStore\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\EventDispatcher.php(264): Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}(Object(Symfony\Component\Console\Event\ConsoleErrorEvent), 'console.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 C:\xampp\htdocs\WebStore\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'console.error', Object(Symfony\Component\Console\Event\ConsoleErrorEvent))
#4 C:\xampp\htdocs\WebStore\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'console.error', Object(Symfony\Component\Console\Event\ConsoleErrorEvent))
#5 C:\xampp\htdocs\WebStore\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php(242): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\Console\Event\ConsoleErrorEvent), 'console.error')
#6 C:\xampp\htdocs\WebStore\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php(83): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\NullOutput))
#7 C:\xampp\htdocs\WebStore\src\Adapter\Cache\Clearer\SymfonyCacheClearer.php(103): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\NullOutput))
#8 [internal function]: PrestaShop\PrestaShop\Adapter\Cache\Clearer\SymfonyCacheClearer->PrestaShop\PrestaShop\Adapter\Cache\Clearer\{closure}()
#9 {main}
  thrown in C:\xampp\htdocs\WebStore\var\cache\prod\ContainerXBS8ohR\appAppKernelProdContainer.php on line 2255
[26-Apr-2024 11:52:02 Europe/Berlin] PHP Warning:  Constant _PS_DO_NOT_LOAD_CONFIGURATION_ already defined in C:\xampp\htdocs\WebStore\install\controllers\http\smarty_compile.php on line 26
[26-Apr-2024 11:52:07 Europe/Berlin] PHP Warning:  Constant _PS_DO_NOT_LOAD_CONFIGURATION_ already defined in C:\xampp\htdocs\WebStore\install\controllers\http\smarty_compile.php on line 26

**Comment by matks** [comment]
> [26-Apr-2024 10:52:01 Europe/Lisbon] PHP Notice: stream_copy_to_stream(): Read of 8192 bytes failed with errno=13 Permission denied in C:\xampp\htdocs\WebStore\vendor\symfony\symfony\src\Symfony\Component\Filesystem\Filesystem.php on line 66

From this line we can be sure you have a permission issue. PrestaShop attemps to copy some files but your system refuses.

**Comment by patrizi** [comment]
Hello everyone
sorry for this message in a closed ticket but  I encountered the same problem (see attached image)  
![Screenshot 2024-06-15 110945](https://github.com/PrestaShop/PrestaShop/assets/418807/1893bb7b-0534-4b2c-9982-70b66860f41d)
with **version 8.1.6** and I don't think it's just a question of permissions.
I have repeated the installation attempts several times always without success, when installing the theme, the procedure fails.
During these tests on the hosting server I also changed the permissions on the folder and its contents (the installation files) to 777 and then checked the write permission.


### I copy the logs from the hosting here
15/06/2024 11:00:49 	WARNING: [pool www.testing.app] child 59 said into stderr: "[15-Jun-2024 11:00:49 Europe/Rome] PHP Warning: filemtime(): stat failed for /web/htdocs/www.testing.app/home/shop/var/cache/prod/Container3bMbHJ8/appAppKernelProdContainer.php in /web/htdocs/www.testing.app/home/shop/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php on line 109"
15/06/2024 11:00:49 	WARNING: [pool www.testing.app] child 59 said into stderr: "[15-Jun-2024 11:00:49 Europe/Rome] PHP Warning: require(/web/htdocs/www.testing.app/home/shop/var/cache/prod/Container3bMbHJ8/getConsole_Command_CacheWarmupService.php): Failed to open stream: No such file or directory in /web/htdocs/www.testing.app/home/shop/var/cache/prod/Container3bMbHJ8/appAppKernelProdContainer.php on line 2225"
15/06/2024 11:00:49 	WARNING: [pool www.testing.app] child 59 said into stderr: "[15-Jun-2024 11:00:49 Europe/Rome] PHP Warning: require(/web/htdocs/www.testing.app/home/shop/var/cache/prod/Container3bMbHJ8/getConsole_Command_CacheWarmupService.php): Failed to open stream: No such file or directory in /web/htdocs/www.testing.app/home/shop/var/cache/prod/Container3bMbHJ8/appAppKernelProdContainer.php on line 2225"
15/06/2024 11:00:49 	WARNING: [pool www.testing.app] child 59 said into stderr: "[15-Jun-2024 11:00:49 Europe/Rome] PHP Warning: require(/web/htdocs/www.testing.app/home/shop/var/cache/prod/Container3bMbHJ8/getSwiftmailer_EmailSender_ListenerService.php): Failed to open stream: No such file or directory in /web/htdocs/www.testing.app/home/shop/var/cache/prod/Container3bMbHJ8/appAppKernelProdContainer.php on line 2225"
15/06/2024 11:00:49 	WARNING: [pool www.testing.app] child 59 said into stderr: "[15-Jun-2024 11:00:49 Europe/Rome] PHP Warning: require(/web/htdocs/www.testing.app/home/shop/var/cache/prod/Container3bMbHJ8/getSwiftmailer_EmailSender_ListenerService.php): Failed to open stream: No such file or directory in /web/htdocs/www.testing.app/home/shop/var/cache/prod/Container3bMbHJ8/appAppKernelProdContainer.php on line 2225"
15/06/2024 11:00:49 	WARNING: [pool www.testing.app] child 59 said into stderr: "[15-Jun-2024 11:00:49 Europe/Rome] PHP Fatal error: Uncaught Error: Failed opening required '/web/htdocs/www.testing.app/home/shop/var/cache/prod/Container3bMbHJ8/getSwiftmailer_EmailSender_ListenerService.php' (include_path='/web/htdocs/www.testing.app/home/shop/vendor/pear/pear_exception:/web/htdocs/www.testing.app/home/shop/vendor/pear/console_getopt:/web/htdocs/www.testing.app/home/shop/vendor/pear/pear-core-minimal/src:/web/htdocs/www.testing.app/home/shop/vendor/pear/archive_tar:.:/php8.1/lib/php') in /web/htdocs/www.testing.app/home/shop/var/cache/prod/Container3bMbHJ8/appAppKernelProdContainer.php:2225"
15/06/2024 11:00:49 	WARNING: [pool www.testing.app] child 59 said into stderr: "Stack trace:"
15/06/2024 11:00:49 	WARNING: [pool www.testing.app] child 59 said into stderr: "#0 /web/htdocs/www.testing.app/home/shop/var/cache/prod/Container3bMbHJ8/appAppKernelProdContainer.php(2632): Container3bMbHJ8\appAppKernelProdContainer->load()"
15/06/2024 11:00:49 	WARNING: [pool www.testing.app] child 59 said into stderr: "#1 /web/htdocs/www.testing.app/home/shop/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(301): Container3bMbHJ8\appAppKernelProdContainer->Container3bMbHJ8\{closure}()"
15/06/2024 11:00:49 	WARNING: [pool www.testing.app] child 59 said into stderr: "#2 /web/htdocs/www.testing.app/home/shop/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(264): Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}()"
15/06/2024 11:00:49 	WARNING: [pool www.testing.app] child 59 said into stderr: "#3 /web/htdocs/www.testing.app/home/shop/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()"
15/06/2024 11:00:49 	WARNING: [pool www.testing.app] child 59 said into stderr: "#4 /web/htdocs/www.testing.app/home/shop/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()"
15/06/2024 11:00:49 	WARNING: [pool www.testing.app] child 59 said into stderr: "#5 /web/htdocs/www.testing.app/home/shop/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(242): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()"
15/06/2024 11:00:49 	WARNING: [pool www.testing.app] child 59 said into stderr: "#6 /web/htdocs/www.testing.app/home/shop/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(83): Symfony\Component\Console\Application->doRun()"
15/06/2024 11:00:49 	WARNING: [pool www.testing.app] child 59 said into stderr: "#7 /web/htdocs/www.testing.app/home/shop/src/Adapter/Cache/Clearer/SymfonyCacheClearer.php(103): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()"
15/06/2024 11:00:49 	WARNING: [pool www.testing.app] child 59 said into stderr: "#8 [internal function]: PrestaShop\PrestaShop\Adapter\Cache\Clearer\SymfonyCacheClearer->PrestaShop\PrestaShop\Adapter\Cache\Clearer\{closure}()"
15/06/2024 11:00:49 	WARNING: [pool www.testing.app] child 59 said into stderr: "#9 {main}"
15/06/2024 11:00:49 	WARNING: [pool www.testing.app] child 59 said into stderr: " thrown in /web/htdocs/www.testing.app/home/shop/var/cache/prod/Container3bMbHJ8/appAppKernelProdContainer.php on line 2225"
15/06/2024 10:59:56 	WARNING: [pool www.testing.app] child 62 said into stderr: "[15-Jun-2024 10:59:56 Europe/Rome] PHP Warning: Attempt to read property "theme_name" on null in /web/htdocs/www.testing.app/home/shop/var/cache/prod/Container3bMbHJ8/appAppKernelProdContainer.php on line 2870"
15/06/2024 10:59:31 	WARNING: [pool www.testing.app] child 60 said into stderr: "#0 /web/htdocs/www.testing.app/home/shop/classes/Configuration.php(229): ConfigurationCore::loadConfiguration()"
15/06/2024 10:59:31 	WARNING: [pool www.testing.app] child 60 said into stderr: "#1 /web/htdocs/www.testing.app/home/shop/config/smarty.config.inc.php(28): ConfigurationCore::get()"
15/06/2024 10:59:31 	WARNING: [pool www.testing.app] child 60 said into stderr: "#2 /web/htdocs/www.testing.app/home/shop/install/controllers/http/smarty_compile.php(37): require_once('...')"
15/06/2024 10:59:31 	WARNING: [pool www.testing.app] child 60 said into stderr: "#3 /web/htdocs/www.testing.app/home/shop/install/classes/controllerHttp.php(190): require_once('...')"
15/06/2024 10:59:31 	WARNING: [pool www.testing.app] child 60 said into stderr: "#4 /web/htdocs/www.testing.app/home/shop/install/index.php(53): InstallControllerHttp::execute()"
15/06/2024 10:59:31 	WARNING: [pool www.testing.app] child 60 said into stderr: "#5 {main}"
15/06/2024 10:59:31 	WARNING: [pool www.testing.app] child 60 said into stderr: " thrown in /web/htdocs/www.testing.app/home/shop/classes/Configuration.php on line 175"
15/06/2024 10:58:32 	[error] (2)No such file or directory: - www.testing.app - AH02454: FCGI: attempt to connect to Unix domain socket /aruba/php/php-fpm.sock (*:80) failed
15/06/2024 10:58:32 	[error] - www.testing.app - AH01079: failed to make connection to backend: httpd-UDS, referer https://www.testing.app/shop/install/index.php


With the same version I also did TEST via XAMPP (with administrator privileges on the installation folder), in which case the error is presented like this:
>
> An error has occured:
> Warning: rename(C:\XAMPP\htdocs\TestingApp/index.php.temp,C:\XAMPP\htdocs\TestingApp/index.php): 
> Accesso negato (code: 5) in C:\XAMPP\htdocs\TestingApp\index.php on line 1338
> {"error":false,"numFiles":28605,"lastId":29000}
> 

I attach PHPinfo file
[PHP Version 8.1.txt](https://github.com/user-attachments/files/15846346/PHP.Version.8.1.txt)

thanks for support

**Comment by AztecCodes** [comment]
Check this out: https://prestahero.com/blog/post/167-fix-prestashop-81-installation-error.html

This fixed the issue for me.
