### ISSUE TITLE
403 forbidden error on root categorie

### ISSUE THREAD

**Issue by 01park** [PrestaShop/PrestaShop#29871]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I am not sure if this is a bug, but after updating PS to the latest version. I am getting notifications from Google Search that a 403 error is given to the root category.

Is this normal? or has something changed in settings.

I also noticed that prestashop gsitemap no longer generates full sitemaps. Could this be linked?

### Expected behavior

N/A

### Steps to reproduce

I do not know how to reproduces this issue, thats why I started with asking if this is normal behaviour.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

gsitemap

**Comment by sallemiines** [comment]
Hello @01park ,

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template and provide clear and concise steps to reproduce the bug**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
