### ISSUE TITLE
New Twitter Github Facebook logo in the authentication page

### ISSUE THREAD

**Issue by paulnoelcholot** [PrestaShop/PrestaShop#29884]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

New Twitter Github Facebook logo in In version 8.0.0 in the authentication page, the redirect buttons on Facebook, Twitter and Github pages are no longer the same as those of previous versions.

In 1.7.8 : 
![image](https://user-images.githubusercontent.com/112863083/194072937-5889e7c2-1931-44f3-a64d-0d379f7bdfa6.png)

In 8.0.0 : 
![image](https://user-images.githubusercontent.com/112863083/194073051-f916d413-d53d-4914-910a-8db9006ccafa.png)

### Steps to reproduce

1. Go to authentifate page.

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.4

**Comment by paulnoelcholot** [comment]
@TristanLDD

**Comment by TristanLDD** [comment]
We should keep the new icons as the 1.7 ones were more "customized icons" than official logos, but the spacing between each icon must be 15px, right now they are too close to each other. 
thx!

**Comment by MatShir** [comment]
It's not a bug then thanks @paulnoelcholot :)
