### ISSUE TITLE
Bug in Guest Checkout "Address" "Invoice address"

### ISSUE THREAD

**Issue by Mwaqas1** [PrestaShop/PrestaShop#29882]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

There's is long pending unresolved  bug in, i had re produced the bug in PS 1.7.8.0  to PS 1.7.8.7  it exists in multiple domains having fresh installation. this happens when you checkout with guest account. it take you to a page where nothing can be clicked and you have to go back one page, looks like this screenshot.
![image](https://user-images.githubusercontent.com/61832872/194059429-22a22b70-e1bb-464e-aa36-c1cb5bcc5d03.png)

it happens while creating an address and **UNCKECK**  "Use this address for invoice too" .... another known bug here is that it create duplicate addresses as well. so afterwards when you try to edit any of the invoice as in the screenshot > 
![image](https://user-images.githubusercontent.com/61832872/194059882-aeb726fc-3893-417a-a58e-15055ec6f958.png)

it will take you to that dead end page, shown in the first screenshot.
i had checked for this issue on github even i had checked in PS 1.8 beta but there is no know fix for this.

Thanks

### Expected behavior

When you edit an invoice/billing address as a guest it should go to the address edit page rather then the dead end page. (also multiple addresses should not be created when you uncheck "use this address for invoice too" )

### Steps to reproduce

1. as a guest add a product to cart.
2. Go to checkout page.
3. In login continue as guest.
4. create an address and continue .
5. Go back to addresses and add new address and uncheck "use this address for invoice too" and save it.
6.  Again go back to addresses 1st know bug > (you will see duplicates of that addresses).
7. try to edit the selected invoice/billing address there and it will lead you to the dead end page.
8. if you are not able to see the bug at first, Repeat the steps from 5 to 7 and you will see that dead end page.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.2

**Comment by sallemiines** [comment]
Hello @Mwaqas1 
Thanks for reporting the issue 

Following your steps until the step 7, I reproduce that the created addresses are duplicated , but unfortunately I can't reproduce the steps 7 et 8 ! you can see the issue here : 

https://user-images.githubusercontent.com/31663369/194111273-8d5d7048-30c2-4c86-aa83-ea5c98bb264e.mp4


Could you please provides us a screen record ! 

Thank you !

**Comment by Mwaqas1** [comment]
Thank you so much for looking into this issue.
Well in your video you are editing **shipping address**, while in the step 7 i had wrote to edit the **invoice address**.
please can you test on this as well where i am testing, PS 1.7.8.7 > https://flowfeet.com/ or this > PS 1.7.8.7 http://amnadesigns.pk/
the second one is fresh installation of PS, both the stores are using different themes!
Thanks again for giving your precious time to this issue

**Comment by florine2623** [comment]
Hello @Mwaqas1 ,

I've tested again on my end using 1.7.8.7 version and classic-theme.

https://user-images.githubusercontent.com/16019289/194365269-6e51a584-119d-4e09-bc98-34e49e948728.mov

I can't reproduce your issue. The issue must come from your template itself. I suggest contacting the developer of the template directly.

As I can't reproduce your issue, I will close it.
Thank you for your understanding!

**Comment by Mwaqas1** [comment]
Hi,
Well thanks again, i am developer my self & i had tested on every theme, the bug remains the same.
you are reproducing the bug incorrectly in your video, i wrote at the reproducing steps that edit the "Invoice" please look at the video (the error start at 1:16)

https://user-images.githubusercontent.com/61832872/194379345-71cdfe06-5af0-4365-90a5-32cdf119874b.mp4

Thank you for sparing your time for this

**Comment by Mwaqas1** [comment]
Please open this again, its a genuine bug in PS. you are just reproducing the bug with incorrect steps.

**Comment by Mwaqas1** [comment]
@florine2623 please give it a look again as per my video
