### ISSUE TITLE
SEO isssue:  302 Redirection to default Declination URL ( declinations URLs not included in sitemap )

### ISSUE THREAD

**Issue by smarzougui** [PrestaShop/PrestaShop#29886]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

For products with declinations,
Prestashop make a 302 internal redirection to point to another URL of the declination of the product.

Example:
https://playtunisie.com/produits/145-carte-psn-10.html

Redirects to: 
https://playtunisie.com/produits/145-141-cartes-psn-france-.html

Generated sitemap includes only the base URL of the product.
==> Google crawlers and SEO engins detect that as internal redirect 302 and do not index the product at all.

### Expected behavior

There must be another way to generate the URL of the declination, maybe with #....   instead of internal redirection 302
Or include the products declined URL in the generated sitemap.

As SEO engins detects that as an internal redirection and do not index the page.
This is a very serious SEO issue

Or this issue fixed in later versions of presta 1.7 ?

### Steps to reproduce

Example:
https://playtunisie.com/produits/145-carte-psn-10.html
Presta. Redirects to: 
https://playtunisie.com/produits/145-141-cartes-psn-france-.html
(to point to the default declination)

The problem too is that the Generated sitemap includes only the base URL of the product (https://playtunisie.com/produits/145-carte-psn-10.html
)  and not the final URL (https://playtunisie.com/produits/145-141-cartes-psn-france-.html)

How to fix ? what solutions ?

### PrestaShop version(s) where the bug happened

7.0.33-0ubuntu0.16.04.16

### PHP version(s) where the bug happened

PHP 7.0.33-0ubuntu0.16.04.16 (cli) ( NTS )

**Comment by hibatallahAouadni** [comment]
Hello @smarzougui 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must provide clear and concise steps to reproduce to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
