### ISSUE TITLE
Core archives new API has different format not adapted with the Core

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#29895]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

For PrestaShop version 8, the translations archives API has been adapted to work with the new version format.

Previously the URL was built with the whole version like this:

https://i18n.prestashop-project.org/translations/1.7.7.8/available_languages.json

Now it should only be based on the major version like this:

https://i18n.prestashop-project.org/translations/8/available_languages.json

So we need to update:
- `RemoteLanguagePackLoader::getLanguagePackList`
- `Language::downloadXLFLanguagePack`

So that it builds the URL correctly.

### Expected behavior

Ideally, the `PrestaShop\PrestaShop\Core\Foundation\Version` class could be added with an extra `getTranslationVersion` (for example) that will be used in the URL building code, this way if we need to change this format someday it could be done in the `Version` class only.

### Steps to reproduce

The new API is not ready for product yet but you can use the preproduction one:
http://i18n-preproduction.prestashop-project.org/translations/8/available_languages.json

1. Replace in `RemoteLanguagePackLoader::PACK_LINK` the default used URL to point on the preproduction URL
2. Replace in `Language::SF_LANGUAGE_PACK_URL` and `Language::EMAILS_LANGUAGE_PACK_URL` the default used URL to point to the preproduction URL
3. Those changes should NOT be committed they are just here for test purposes
4. Go to Translation > Localisations
5. Install/update a new language
6. See the error

<img width="1051" alt="Capture d’écran 2022-10-05 à 17 41 52" src="https://user-images.githubusercontent.com/13801017/194095452-0950ea32-c020-4798-ac6b-270cab733934.png">

### PrestaShop version(s) where the bug happened

8.0

**Comment by florine2623** [comment]
Hi @jolelievre
Checking with you, is the shop completely broken ou does it still work ?
It is for the choice of label. If completely broken : `Critical`, if not `Major`.

**Comment by jolelievre** [comment]
Not needed anymore, the fix has been handled on the API server side.
