### ISSUE TITLE
Configure new image format for the new image system

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#29893]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

New configuration for image generation.
We need to be able to generate multiple image formats, instead of single ones.
The current settings "Image format" will be improved.

### Describe the solution you'd like

By default, at the shop creation, JPEG and WebP are selected.
JPEG is used as the default format.

![Image](https://user-images.githubusercontent.com/43613217/201607686-88d96d3d-b98c-46e6-85c7-f7161e18ce08.png)

The form presents 4 checkboxes.
- JPEG
- PNG
- WebP
- AVIF

One option must remain selected. 
If a user deselects all options, the last option is disabled. It is not possible to deselect it.

The fallback allows the user to choose a format that will be supported by all the browser in case the image type selected are not compatible.

The fallback drop list is a dynamic list that lists all the image type checked in the checkbox list.
If the user unchecked the image type used for the fallback then the first checked format in the list is selected as fallback

If the server does not support AIF
Then disable the AVIF option and display a warning message and a link to an external documentation (to the avif documentation). Link to be defined.

![Image](https://user-images.githubusercontent.com/43613217/201603976-8875b32f-0331-4b04-89f9-179a9a8dfa39.png)

If more than 3 image option are select then
A warning message: "Beware the selection of several image formats leads to a higher memory capacity requirement and impacts the performance during generation"

![Image](https://user-images.githubusercontent.com/43613217/201603977-33b987fe-e242-49f1-8072-a725f7a02fe9.png)

The form will have a new input to manage the quality of avif.
- AVIF compression - number input -  by default the input is set to 30.
Label: "Ranges from 0 (worst quality, smaller file) to 100 (best quality, larger file). Recommended: 30."

If the value when saving the form is higher than 100 or lower than 0
Then an error message is displayed: "Incorrect value for the selected AVIF image compression." and the form is not validated.

### Business rule

When an image is uploaded, it generates the image is selected format.

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by Hlavtox** [comment]
@nicosomb @MatShir I think that we are missing a checkbox called "JPG/PNG depending on the original image" in the design.

Now we have 3 options:
- JPG or PNG, depending on the original image. (or rather if the original image was transparent?)
- JPG
- PNG
_(note: all have JPG extension, even though they contain a PNG image)_
