### ISSUE TITLE
id_address_invoice when i change order status

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#29905]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello 

The mail is not sent when I change the order status, I get this message error 

**Une erreur inattendue s'est produite. [Symfony\Component\Debug\Exception\ContextErrorException code 0] : Notice: Trying to get property 'id_address_invoice' of non-object.**

Regards

### Expected behavior

Customer should receive mail when order change

### Steps to reproduce

Go to order 
Change status from accepted payment to any other status 

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.30

**Comment by sallemiines** [comment]
Hello @go-sudo 

Thanks for reporting the issue .

Following your steps I didn't reproduce your issue with PS1778 , PS1787, all the received emails are **OK** ,  see the attached screen record 


https://user-images.githubusercontent.com/31663369/194280356-ad3cf826-45b5-47d9-966a-6558706017e9.mp4



Could you please check in **Shop parameters > Order Setting > Statuses**   that the option` Send an email to the customer when his/her order status has changed.` is selected , see the attached screenShot 


![Statuses _ Edit_ Payment accepted • 1787](https://user-images.githubusercontent.com/31663369/194281421-e84396d0-b8c0-42b6-b88b-f31fb2c0c171.png)

Please check & feedback !

**Comment by go-sudo** [comment]
Hello

https://user-images.githubusercontent.com/11594433/194285150-f0e97e4a-9c06-4700-bc8b-d2cc71321762.MOV
![D1FFFF25-53E4-4FB7-8AF2-B6AA695305DF](https://user-images.githubusercontent.com/11594433/194287973-642e7607-2228-425d-adc8-f134dbfcad9e.png)

Regards

**Comment by go-sudo** [comment]
Hello

I resolved the issue thank you

the order status was linked to deleted template mail

Regards
