### ISSUE TITLE
`HelperOptions` select multiple not work

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#29903]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

`HelperOptions` select multiple not work

![image](https://user-images.githubusercontent.com/16455155/194158579-24c40041-2556-4ccf-9ed1-bdcdddcc954c.png)

### Expected behavior

Able to add multiple attribute for select type

![image](https://user-images.githubusercontent.com/16455155/194158707-7e478886-88da-4400-bbfa-23803672293b.png)

### Steps to reproduce

Edit `AdminGroupsControllerCore::__construct`

Add multiple attribute : 

```php
'PS_UNIDENTIFIED_GROUP' => [
         'multiple' => true,
         'class' => 'chosen' ,
         'title' => $this->trans('Visitors group', [], 'Admin.Shopparameters.Feature'),
         'desc' => $this->trans('The group defined for your un-identified visitors.', [], 'Admin.Shopparameters.Help'),
         'cast' => 'intval',
         'type' => 'select',
          'list' => $groups,
         'identifier' => 'id_group',
 ],
```

See the error : 

![image](https://user-images.githubusercontent.com/16455155/194157810-24f8a6e5-b404-4a39-ade4-bc792a246b04.png)

### PrestaShop version(s) where the bug happened

1.7.8.7, develop

### PHP version(s) where the bug happened

N/A

### If your bug is related to a module, specify its name and its version

N/A

**Comment by sallemiines** [comment]
Hello @PululuK 
Thanks for reporting the issue .

I tried to reproduce your issue with PS1778 , Ps1787,
but I got this behivor , see the attached screen-shot
Could you please check your screenshots: Bug and Expected behavior , because I think you may switch them!

![Groups • 1787](https://user-images.githubusercontent.com/31663369/194267151-a481fea6-2964-4700-9655-72ea594e8244.png)

I think that this issue  could be a feature and not a bug !
Please check and feeback .

**Comment by sallemiines** [comment]
Hello @PululuK 

As we disscussed on slack ,  you encountred an issue while overriding.
Did you encounter this issue only on 1.7.8.7 and 8.0.0 (means a regression) or it's an old bug?
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks!
