### ISSUE TITLE
BO - A bad display of some items with RTL in product page V2 after an upgrade from 1.7 to 8.0

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#29918]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

It's related to this issue [#29336](https://github.com/PrestaShop/PrestaShop/issues/29336) 

When using RTL language, there are some issues with a product with combinations (pProduct V2 page)

**Superposition**
![image](https://user-images.githubusercontent.com/92912932/194342037-3f4af65f-3fa1-4e89-8985-0d6ad3658a8f.png)

![image](https://user-images.githubusercontent.com/92912932/194342439-e7b769f6-dae6-4beb-841c-fe6ffb51c254.png)

**The size is empty**
![image](https://user-images.githubusercontent.com/92912932/194342143-ab21b0ba-523e-4001-8a30-4e25dab2eefc.png)

**Add categories :** The arrow's destination is wrong 
![image](https://user-images.githubusercontent.com/92912932/194351625-78656745-8f66-4b55-aab5-963cd409bcf4.png)

### Expected behavior

A good display with RTL and after an upgrade 

### Steps to reproduce

1. Install PS1778
2. Add languages (Arabic)
3. Use the release of autoupgrade.zip (v4.15)
4. Go to 1-click upgrade > Configure
5. Enable the Disable non-native module option
6. Do not uninstall the problematic modules
7. Under auto-upgrade > Download > Use the .zip for the 8.0.0 RC
8. Upgrade from PS1778 to PS8.0.0 RC
9. Check that the upgrade to 8.0 is OK
10. Go to BO > Advanced parameters > New & Experimental features > Enable New Product page
11. GO to Catalog > Products V2 > Add a new product with combinations 
12. In Combinations tab > Check the different options (Bulk actions, Filter by ...)
13. See different errors > Superpositions and the size tab is empty
14. In Description tab > Click to Add categories 
15. See error > The arrow's destination is wrong 

### PrestaShop version(s) where the bug happened

8.0.0 RC

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

autoupgrade v4.15.0 (Release)

**Comment by RosaBenouamer** [comment]
@florine2623 is this issue really linked to the upgrade ? or does it exist for fresh install of 8.0 ?

**Comment by Quetzacoalt91** [comment]
The PR https://github.com/PrestaShop/autoupgrade/pull/720 will fix one issue provided in the list.

The rest can be found on a fresh install as well, so a new issue will replace this one once closed.
