### ISSUE TITLE
ps_buybuttonlite - Notice error while search products on PHP 7.4

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#29915]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you search a product that have combination but not having associated image, there is an issue on the results and you are not able to choose the product.

Thanks to @dobra947 about the original issue (https://github.com/PrestaShop/PrestaShop/issues/29901)

### Expected behavior

Have no PHP errors.

### Steps to reproduce

1. Be at least on PHP 7.4
2. Install ps_buybuttonlite module
3. Open it's configuration
4. Search after Hummingbird (Colibri) product.

### PrestaShop version(s) where the bug happened

Not usefull

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_buybuttonlite, v1.0.1

**Comment by sallemiines** [comment]
Hello @PrestaEdit 

Thanks for reporting the issue.
I test the issue with **PS1778 PS1787** , see the attached screenShot in **1778** 
![image](https://user-images.githubusercontent.com/31663369/194357061-fed5aed6-98c6-41e1-9216-f4451119ddf3.png)

see the attached screen record in **1787** 

https://user-images.githubusercontent.com/31663369/194357172-3d6cf445-d690-45c7-825c-ddf5343374ec.mp4

 So it’s a regression!
 
 Thank you !
