### ISSUE TITLE
All mails sent to one costumer 

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#29917]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello

 When I resend mail from history Tab Content, all mails are sent with name of one customer and his mail instead of the real buyer

 I checked the sql and everything seem ok
![image](https://user-images.githubusercontent.com/11594433/194347125-bf8538a2-dcfb-4623-9fc4-b7a919a2008c.png)

Regards

### Expected behavior

customer should receive mail with his correct name and address

### Steps to reproduce

Change order status or resend mail 

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.30

**Comment by florine2623** [comment]
Hello @go-sudo ,

I can't reproduce your issue on my end.
<img width="364" alt="Screenshot 2022-10-06 at 17 47 48" src="https://user-images.githubusercontent.com/16019289/194359664-00785117-4160-447d-ae14-3bb0a08d8ad2.png">

The emails are sent to the right customer when I click on "Resend mail" from the order detail Status tab.
<img width="807" alt="Screenshot 2022-10-06 at 17 49 40" src="https://user-images.githubusercontent.com/16019289/194359641-c24fd5b7-64ef-4342-b643-339450233492.png">


I will close your issue as I can't reproduce it.
If you have more info about the steps to reproduce it, you can open a new issue.

Thank you for your understanding!
