### ISSUE TITLE
BO - Products - An exception is displayed after deleting a product created with V1

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#29913]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Catalog > Products page, an exception is displayed after deleting a product 
![image](https://user-images.githubusercontent.com/16067358/194298562-dd6604a8-ebca-473d-967b-4b5ee0c013c9.png)

### Expected behavior

An warning message saying: "The product %name% has been deleted". 

### Steps to reproduce

1. Install 8.0.0 Rc or Use 8.0.0 from an upgrade
2. Enable debug mode
3. Create a Product (with Product V1 or V2)
4. Create an order with this product
5. Go to BO > Catalog > Product & delete the last product created
6. A. Go to BO > Orders > Preview for the previous order created
6. B. Go to BO > Orders > Order detail 
8. Click on the product
9. See exception

https://user-images.githubusercontent.com/16067358/194298724-778580be-b0b2-46d6-98ea-ee871ffcdc22.mp4

PS: I tried with PS1.7.8.7, but we cannot click on the product, this is a new feature on PS8.0.0 
![image](https://user-images.githubusercontent.com/16067358/194298883-65a7127d-3897-420b-b788-47ab04dc7111.png)

### PrestaShop version(s) where the bug happened

8.0.0RC

### PHP version(s) where the bug happened

7.4, 8.1

**Comment by ElodieOS** [comment]
No more need UX review @MatShir ?

**Comment by ElodieOS** [comment]
No more need UX review @MatShir ?

**Comment by MatShir** [comment]
Nop, with @TristanLDD we have identified a quick win
