### ISSUE TITLE
Bug in Guest Checkout "Address" "Invoice address" #29882

### ISSUE THREAD

**Issue by Mwaqas1** [PrestaShop/PrestaShop#29921]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

There's is long pending unresolved bug in, i had re produced the bug in PS 1.7.8.0 to PS 1.7.8.7 it exists in multiple domains having fresh installation. this happens when you checkout with guest account. it take you to a page where nothing can be clicked and you have to go back one page, explained in the video.
it happens while creating an address and UNCKECK "Use this address for invoice too" .... another known bug here is that it create duplicate addresses as well. so afterwards when you try to edit any of the invoice as in the video.
it will take you to that dead end page, shown in the first screenshot.
i had checked for this issue on github even i had checked in PS 1.8 beta but there is no know fix for this.

https://user-images.githubusercontent.com/61832872/194403168-c25ab778-a146-49a4-98fe-f4b67f7ec39b.mp4

Thanks

### Expected behavior

When you edit an invoice/billing address as a guest it should go to the address edit page rather then the dead end page. (also multiple addresses should not be created when you uncheck "use this address for invoice too" )

### Steps to reproduce

1. as a guest add a product to cart.
2. Go to checkout page.
3. In login continue as guest.
4. create an address and continue .
5. Go back to addresses and add new address and uncheck "use this address for invoice too" and save it.
6. Again go back to addresses 1st know bug > (you will see duplicates of that addresses).
7. try to edit the selected invoice/billing address there and it will lead you to the dead end page.
8. if you are not able to see the bug at first, Repeat the steps from 5 to 7 and you will see that dead end page.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment]
Hello @Mwaqas1 

Thanks for the perfect bug report :clap: :rocket: 
I didn't manage to reproduce the issue with PS1787, see the attached screen record below:

[issue_29882.webm](https://user-images.githubusercontent.com/23308427/194616064-7482a4d2-f0b7-457e-a926-566c1a738f2f.webm)

Did you try to switch your theme to CLassic as it may be related to the theme?
Please check and feedback.

Thanks!

**Comment by Mwaqas1** [comment]
@hibatallahAouadni  ok i had checked , and there is no issue while using classic theme.
but the issue is with almost 99% custom theme as i had tested.
(Also please tell me the fix for the duplicate addresses)

thanks

**Comment by hibatallahAouadni** [comment]
Hello @Mwaqas1 

It seems that your issue is not a PrestaShop core bug. It's related to you theme.

We will close this issue as we only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you

**Comment by Mwaqas1** [comment]
@hibatallahAouadni  i am sorry to say that yes i can reproduce this same bug on CLASSIC theme as well.
Please you can reproduce the issue as same steps i am doing.

Regards

**Comment by hibatallahAouadni** [comment]
Hello @Mwaqas1 

> @hibatallahAouadni  ok i had checked , and there is no issue while using classic theme.

But you already said that you didn't reproduce it with Classic theme :open_mouth: 
> Please you can reproduce the issue as same steps i am doing.

As I mentioned above I didn't manage to reproduce the issue with the provided steps :disappointed: 

Thanks!

**Comment by kliford** [comment]
Hello, 
I also had this error when purchasing products as a guest and selecting a different address for the invoice.

I made changes to classes/controller/FrontController.php line 426

`if (isset($cart) && (!isset($cart->id_address_delivery) || $cart->id_address_delivery == 0 ||
                    !isset($cart->id_address_invoice) || $cart->id_address_invoice == 0) && $this->context->cookie->id_customer)`

Commented/deleted out the condition check
` || $cart->id_address_invoice == 0`

and the purchase works without problems.
It may be that it causes other errors but I checked it on 2 stores and it works without errors

**Comment by MatShir** [comment]
@kliford Don't you want to contribute to the projet with your code? We will be happy to review your work -> https://devdocs.prestashop-project.org/8/contribute/contribute-pull-requests/ 🤗
