### ISSUE TITLE
BO - An error when upgrade from 1.7 to 1.7.8 or to 8.0 when the zip and the xml are erased 

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#29929]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An error when upgrade from 1.7.7.8 to 1.7.8 or to 8.0 when the zip and the xml are erased after being used and save it

![image](https://user-images.githubusercontent.com/92912932/194569058-88225e8b-5f47-4a75-81fb-9e534fdc7054.png)

https://user-images.githubusercontent.com/92912932/194569780-f0037501-6a93-464f-920f-69b7b125b791.mp4

### Expected behavior

The upgrade button shouldn't be displayed (Proposition) and an alert to block the upgrade

### Steps to reproduce

1. Install PS1778 OR PS1787
2. Use the release of autoupgrade.zip (v4.15)
3. Go to 1-click upgrade > Configure
4. Enable the Disable non-native module option
5. Do not uninstall the problematic modules
6. Under auto-upgrade > Download > Use the .zip and the xml for the 8.0.0 RC
7. Go to 1-click upgrade > Configure
8. Choose local archive
9. Fill the fields with the zip and the xml and the version 
10. Click on Save 
11. Check that the button `Upgrade Prestashop now` is displayed 
12. Refresh the page
13. Under auto-upgrade > Download > Erase the zip and the xml 
14. Choose local archive
15. There is no field to put
16. Click on Save and Click on `Upgrade PrestaShop now`
17. See error ==> An error is displayed when running the upgrade

### PrestaShop version(s) where the bug happened

1.7.8.7, 8.0.0

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

autoupgrade v4.15.0 (Release) & autoupgrade v4.14.2

**Comment by hibatallahAouadni** [comment]
Hello @HanaRebaiQA 

I reproduce the issue only with 1-Click autoupgrade v4.15.0, with v4.14.2 I didn't manage to reproduce the issue, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/194880060-eb8661d7-ee68-4ee6-8519-0a229ef2eac1.png)

So, it's a regression on the module! I will add to the Backlog to be fixed.

Thanks!

**Comment by gericfo** [comment]
@HanaRebaiQA Thanks for this feedback. We close this issue as we will redesign the autoupgrade module (including this part, we will avoid this situation).
