### ISSUE TITLE
Related product errors in Google Snippet Product

### ISSUE THREAD

**Issue by Bosco91-rn** [PrestaShop/PrestaShop#29939]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I noticed that Google Search Console for each product on the website is finding 2 critical errors:
- Missing field "availability" (in "offers")
- No global identifier specified (example. gtin, brand)
I checked the product's page and is ok because is following correctly the "http://schema.org/Product", but if there is a related product Google can't find these field inside and it displays these errors. How is possible to fix this problem? Because products are correct but Google read them wrongly.

If you need an example product to have a look on the code let me know.
Thanks
Nicola

### Steps to reproduce

1. Set up a test site under 1.7.8.7 using the classic theme or any third-party theme
2. Create a product and a related product
3. Observe the errors reported for all listing pages created on Google Search Console

### PrestaShop version(s) where the bug happened

1.7.8.7

**Comment by sallemiines** [comment]
Hello @Bosco91-rn  
Thanks for reporting the issue.
Following your steps ,I can't reproduce your issue , I tested  with  PS1778 PS1787 !
I get this result, see the attached screenshot 

![Rich Results Test - Google Search Console](https://user-images.githubusercontent.com/31663369/195140449-3849570a-7c6e-424f-ad5a-da7031adb47a.png)

Could you please provides us with the result you have ? 

I think this [issue](https://github.com/PrestaShop/PrestaShop/issues/22962) is similar to yours ! could you please check ?  


Please check & feedback !

**Comment by Bosco91-rn** [comment]
Hello @sallemiines, thanks for your quick reply! Yes in attachment the result of the search console. 
This is the link of the product if you want to have a look: https://www.cebsas.it/it/connettori-occhiello/12670-capicorda-occhiello-m8-isolato-giallo
As you can see the main product is fine and all field are ok as  "http://schema.org/Product", but google snippet find 2 critical errors that are coming from the 2 related products displayed on the end of the page. In attachment the 2 critical errors
I think is a bit different this issue, not the same as the post you linked to me. 
![Immagine](https://user-images.githubusercontent.com/63743449/195143599-0413e81c-504b-47a6-a6c0-be1ea335593f.jpg)
![Immagine1](https://user-images.githubusercontent.com/63743449/195143602-c4f90b81-b18b-4aa9-a501-e331bb324772.jpg)
Let me know if you need other informations

**Comment by AureRita** [comment]
Hi @Bosco91-rn , 

Thank you for all the details. I tried to reproduce your issue with other shop of prestashop as you can see : 
![image](https://user-images.githubusercontent.com/100699445/195617624-0a2fece2-80e9-404c-b792-180e6c565c80.png)

I didn't have issue on this shop, can you tell us wich type of images did you have in your related product ? 
Can you test it with a classic theme ? to see if you have the same result ? 

Waiting for your feedback

**Comment by Bosco91-rn** [comment]
Hi @AureRita, i'm not using the classic theme but i purchased it. Unfortunately i can't test it with the classic theme because i'm using it for my shop actually. 
Can you test this link? https://www.cebsas.it/en/eyelet-connectors/12670-yellow-insulated-m8-eyelet-cable-lugs
Is a product where i found the 2 critical erros, and i guess are coming from the 2 related products.

**Comment by AureRita** [comment]
Hi @Bosco91-rn, 

I tested your link and indeed the google snippet show that you've errors in your images' related product. But, currently I tried to reproduce you issue with an other shop to let have enought details for the developper. 

Did you do other things that this three steps to reproduce your issue ?

Waiting for your feedback

**Comment by HanaRebaiQA** [comment]
Hello @Bosco91-rn 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank You!

**Comment by Olenam123** [comment]
Hi
I have the same problem with Related products on my presta site 1.7.8.7.
@Bosco91-rn did you fix this?
Thanks.
