### ISSUE TITLE
Tax calculation error for EU customers

### ISSUE THREAD

**Issue by fc-mbouzidi** [PrestaShop/PrestaShop#29936]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I have the bug in Prestashop 1.7.8.7 with the vatnumber module installed (and the online verification disabled).

If a customer have a VAT Number in his account and in his address, with a country different form the seller country, the products and the shipping are listed with the excluded tax amount. 

In the cart, there are 2 lines for the totals. One with the Total Tax Excluded and the Total Tax included. But the customer pay the total tax included

### Expected behavior

In this case the customer should pay the total without taxes. The vatnumber is not maintained anymore but Presrashop should handle the selling process through the EU.

### Steps to reproduce

1. Create a customer account with a company name and a VAT number.

2. Create an address in a different country than the seller (ex: if the seller is in France, create a the  Belgium) and add a VAT number too.

3. Continue the checkout process to the payment

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

vatnumber

**Comment by hibatallahAouadni** [comment]
Hello @fc-mbouzidi 

This module has been archived, it’s no longer maintained but you still can fork it if you need it for your shop.
Also let us know if you are voluntary to maintain this module.

Thanks!

**Comment by fc-mbouzidi** [comment]
I know that this module has been archived but because of it, I thought that the 1.7 handle the EU payment without module. It's not the case ?

**Comment by NKoonen** [comment]
> I know that this module has been archived but because of it, I thought that the 1.7 handle the EU payment without module. It's not the case ?

Try: https://www.prestashop.com/forums/topic/1066616-free-module-vat-checker
