### ISSUE TITLE
Displaying informations from installation command from cli : Array to String conversion PHP notice

### ISSUE THREAD

**Issue by thomasnares** [PrestaShop/PrestaShop#29937]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Displaying informations from installation command on PrestaShop 8.x from the command line throws a PHP Notice: 

```
php index_cli.php
Notice: Array to string conversion in /path/install-dev/classes/controllerConsole.php on line 95
```

### Expected behavior

Installing PrestaShop from the command line should succeed without any errors, warning, or notices.

### Steps to reproduce

1. Download the zip and extract PrestaShop.

2. Install composer dependencies (if needed)

3. Go to install-dev (or install)

4. Run php index_cli.php

Note that in PrestaShop 1.7.8.x the following command succeeds without any notices.

### PrestaShop version(s) where the bug happened

8.x

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @thomasnares 

Thanks for reporting the issue and your PR :rocket: 
I reproduce the issue with PS80x, it's a regression as you mentioned, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/194919828-9f408ce0-b436-4d63-9b02-6935e0f1a436.png)

Adding it to the backlog!
Thanks :pray:
