### ISSUE TITLE
Plugin not show on Back office prestashop

### ISSUE THREAD

**Issue by Agencenetcom** [PrestaShop/PrestaShop#29948]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I want to install 1-click upgrade for Prestashop.

So I downloaded the Github source code in ZIP.

On the back office when I try to install it, it does not recognize the file.

So I installed it manually with FTP, but it does not appear on the prestashop modules.

Did I miss a step?

Github link of the module : https://github.com/PrestaShop/autoupgrade

### Steps to reproduce

1. Dezip file
2. Rename folder to autoupgrade
3. Put the file in modules files
4. Go to Dashboard in module
5. The module is not present

### PrestaShop version(s) where the bug happened

1.7.6.9

### PHP version(s) where the bug happened

7.4

**Comment by sallemiines** [comment]
Hello @Agencenetcom  ! 

Thanks for reporting the issue.
I reproduce the issue with PS1778 PS1787 and PS800 , 
I install the module directly from module page , but there's an error displayed , see the attached screen record 

https://user-images.githubusercontent.com/31663369/195063678-0c22d25d-1bbe-475b-8924-facb4ad26cd9.mp4


Also i put the module file in modules files , the module isn't exist, see the attached screen record 


https://user-images.githubusercontent.com/31663369/195063782-6a4596a0-d2c8-4146-b732-bdc2780e94a6.mp4

Thank you !

**Comment by kpodemski** [comment]
Hello @Agencenetcom 

Did you download the module from the [releases page](https://github.com/PrestaShop/autoupgrade/releases)?

If you don't, and all you have are source files, you need to run `composer install` for the module to work properly.

**Comment by Hlavtox** [comment]
Some user error, closing.
