### ISSUE TITLE
BO/FO- HTML tags are not well displayed in different pages

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#29940]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO - Customer Settings - Groups page, the info alert is not well displayed
![image](https://user-images.githubusercontent.com/16067358/194851041-a13d4eba-5e15-49da-aeed-76875e1d8559.png)

In the BO - Notifications bell > Orders
<img width="483" alt="Screenshot 2022-12-20 at 14 31 40" src="https://user-images.githubusercontent.com/16019289/208678970-955467e8-4659-4298-ab3d-8b99de8b743a.png">

In the FO > Create account page, the "Newsletter subscription" block and the block "Customer data privacy" are not well displayed
![image](https://user-images.githubusercontent.com/16067358/195350085-4c9d0527-4bc9-4bba-8c4f-d2b08abab56f.png)

> Edited by @HanaRebaiQA 

When enable multistore and add a new shop, the link tag is bad displayed!
![image](https://user-images.githubusercontent.com/92912932/195367423-d214bcde-c593-499f-bbf8-6323b2136c34.png)

### Steps to reproduce

**Case1**
1. Go to BO - Customer Settings - Groups page
2. See error
3. Go to FO 
4. Click on Sign in
5. Create an account 
6. See error 

PS8.0.0RC1 => oK

> Edited by @HanaRebaiQA 

**Case2**
1. Go to BO > General > Enable Multistore
2. In BO > Advanced parameters > Multistore > Add a new shop
3. In the shop name > see the help message

>Edited by @khouloudbelguith 

**Case3**
1. Go to BO > Advanced Parameters > Performance page
2. Disable Features and save
3. Go to BO > Catalog > Attributes & Features > Features page

![image](https://user-images.githubusercontent.com/16067358/196155245-8fa59b70-f9c3-4fb9-8d7a-4c03fdf82a07.png)

**Case4**
In the FO > Create account page, the "Newsletter subscription" block and the block "Customer data privacy" are not well displayed
![image](https://user-images.githubusercontent.com/16067358/195350085-4c9d0527-4bc9-4bba-8c4f-d2b08abab56f.png)

>Edited by Khouloud

**Case5**

1. Go to BO > Advanced Parameters > Import page
2. Try to import a valid file csv, for example in my case products.csv
3. Click on Import > A modal "Importing data" is displayed
4. See error `<span id="validate_progression_done">0</span>% validated`

![image](https://user-images.githubusercontent.com/16067358/201335878-8eda984e-d8a7-461b-8d62-11500321bfed.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/16067358/194851113-f3c891d4-32c5-432c-a24d-a21350678357.png)
It should be 
![image](https://user-images.githubusercontent.com/16067358/196155283-38ba677e-aca8-42ff-acec-8d0437a8c18d.png)

### PrestaShop version(s) where the bug happened

8.0.x, develop

### PHP version(s) where the bug happened

7.2, 7.3

**Comment by nicosomb** [comment]
Hello, 

By removing `$parameters['legacy'] = 'htmlspecialchars';` in `classes/controller/Controller.php`, all is fine. But the code didn't change recently... 

@matks Do you know what happens here?

**Comment by PrestaEdit** [comment]
It's a legacy controller.

Could I suggest you to check that inside the v1.7.8.2 it's good but not into the 1.7.8.3, maybe ?

**Comment by nicosomb** [comment]
I worked on this issue yesterday (https://github.com/PrestaShop/PrestaShop/pull/29943), but I need to work on an other subject. 

My PR is not OK. 

As discussed with @eternoendless (if you want to add more details, don't hesitate), we need to delete this line https://github.com/PrestaShop/PrestaShop/pull/7026/files#diff-9f289759f04c7012de8116c55f0d0db2eb1f7da736b2949946fd6076743e2977 
Then, we need to check all the `$this->trans()` calls to find those where there are injected parameters, to escape them and prevent injections.

**Comment by kpodemski** [comment]
Latest changes that may have an impact:

https://github.com/PrestaShop/PrestaShop/pull/29441/files

**Comment by theGera** [comment]
the errios is smarty 3.x to 4.1

example:
{$field.label nofilter} **not work well**
{$field.label|unescape: "html" nofilter} **work for my**

I have not verified everything but in my tpl files of the theme it has worked

**Comment by jumper-11** [comment]
Hi, I have the same problem in Presta 8.01
What is the solution for this problem?

**Comment by eternoendless** [comment]
This has been fixed in PrestaShop 8.0.2, with ps_emailsubscription v2.7.1 and ps_dataprivacy v2.1.1

**Comment by jumper-11** [comment]
the update fixed the problem but there is a problem with the css and it displays the data processing text wrong.
You need to change the css code as below.
.custom-checkbox span 
  **position: inherit!important;**
Maybe the developer will fix it right away.
