### ISSUE TITLE
CI is failing on PRs on develop because of 'Checking doubles...' that does not run

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#29946]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

CI is failing on PRs on develop because of 'Checking doubles...' that does not run

Example https://github.com/PrestaShop/PrestaShop/pull/29944

### Expected behavior

CI should not fail because of a build that does not run 🤔 

### Steps to reproduce

See example PR https://github.com/PrestaShop/PrestaShop/pull/29944

### PrestaShop version(s) where the bug happened

develop

**Comment by matks** [comment]
I wonder if this https://github.com/PrestaShop/PrestaShop/pull/29912/ could have introduced an unwanted side effect

**Comment by boubkerbribri** [comment]
> I wonder if this #29912 could have introduced an unwanted side effect

Don't think so, Tests are running on 8.0.x branch (ex : https://github.com/PrestaShop/PrestaShop/pull/29942)

**Comment by atomiix** [comment]
I think it's related to:
https://github.com/PrestaShop/PrestaShop/commit/f8258e8ed42e53724b066cb927b7c12ee6d52594#diff-f8e83c96d3c6b691a585feaf7063e8338365b4fd4a77993b35ab1f8883babcccL65

**Comment by boubkerbribri** [comment]
> I think it's related to: [f8258e8#diff-f8e83c96d3c6b691a585feaf7063e8338365b4fd4a77993b35ab1f8883babcccL65](https://github.com/PrestaShop/PrestaShop/commit/f8258e8ed42e53724b066cb927b7c12ee6d52594#diff-f8e83c96d3c6b691a585feaf7063e8338365b4fd4a77993b35ab1f8883babcccL65)

I don't think so. That was a fix that i tried. The error was way before.

**Comment by matks** [comment]
Fixed by @atomiix : it was a change in GitHub settings
