### ISSUE TITLE
Salve, non riesco a far funzionare il PrestaShop / programma di riferimento sul mio prestashop 1.7

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#29950]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Quando provo ad inserire il modulo non viene riconosciuto come un modulo prestashop, potete aiutarmi?
[trackingfront-dev.zip](https://github.com/PrestaShop/PrestaShop/files/9751841/trackingfront-dev.zip)

### Steps to reproduce

Ho provato a inserire il modulo in presta shop e esce l'errore che non riconosce il modulo

### PrestaShop version(s) where the bug happened

1.7

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

PrestaShop / programma di riferimento

**Comment by sallemiines** [comment]
Hello @Valerio-Varchi !

Please send your request in English. English is the norm on **GitHub**.

Thank you !
