### ISSUE TITLE
Class overridable with private variable in a class

### ISSUE THREAD

**Issue by prestacrazy** [PrestaShop/PrestaShop#29955]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On many class(enough) that are overridable (present in classes folder) like CustomerAddressPersister , there is private var, that make the code not overridable without changing original code, changing it to protected can be the solution.

In my way i have to edit original prestashop file, that is not clean and really bad for update.

It will also great if the private method can be protected cause i also have to copy them in my override cause they are private.

Thank you guys , hope u can make this better for next version , for me it is too late :/ but hope next one will be better about that

### Steps to reproduce

See class CustomerAddressPersister and try to override delete and updateUsedAddress

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.3

**Comment by kpodemski** [comment]
Hello @prestacrazy 

Please describe your scenario to us in detail so we can think of a different way of modifying the behavior. Maybe you could use an additional hook?

**Comment by prestacrazy** [comment]
Hello @kpodemski ,

**i am not here for help**, for myself i will write on original file, not the first time i found problem like this, we can't wait another version.

Here i am speaking about an **architectural Prestashop problem**, not in one case, but **in all Prestashop classes overridable**, and it is also present for Symfony decorator

I report the problem, i will no more give help, u treat it, it is fine, u won't u won't, not my problem, don't want to fight with you for u made it(I see how u treat some ticket, don't want to loose my time).

**Comment by kpodemski** [comment]
We don't want to make classes easier to override. We want to make the core easier to customize through hooks and other mechanisms that are more reliable.

If you don't want any help and it is only a comment, then I'm closing this issue. We can discuss such things [on the open source Slack for the project](https://www.prestashop-project.org/slack/).

**Comment by matks** [comment]
To add some context to @kpodemski message: override is a powerful mechanism but it actually also introduce a lot of instability in your shop. This is especially painful when upgrading PrestaShop versions. This is why the mechanism is still available but not being reworked: we are looking for ways to customize PrestaShop that do not decrease stability.

**Comment by prestacrazy** [comment]
Hello @matks ,

u are right and i know it, but here it is not a customization it is a bug patch of core of Prestashop(and some of them were in 1.6 and are still on 1.7), we prefer to use override cause we consider it as cleaner than edit original file, about migration Prestashop(at this time) is not a solution to use without a professionnal working on IT based on his modular architecture(and his high number of themes) and the number of bugs(Core and modules, a module without bug it's not happen often) , so it passed by test Env before, we see last override put and we see if we steal let them or not. We can't outpassed this test env cause all Prestashop installation are unique ;)

I don't wanna flame u but i don't think Prestashop is thinking about migration, when we see how we have to passed to 1.7, and also for other, it is not Prestashop that manage migration but external modules and this modules we also can say them thanks to the lot of bug and problems(and it is critical problems) , All of this to say u that it is not a good argument cause before to think to migration, u have to do the basic for migration ;)

Nothing against u @matks , on the contrary i see u answering on another tickets and u made a good job

Prestashop can be bigger but u have to take the good decision and not ideological and based on personnal decision.
