### ISSUE TITLE
In All shop context, while editing an order, the default currency might be invalid

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#29961]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

- When editing an order in All Shop context, in the _Payment_ card, the default currency is the currency of shop 1, even if the shop the order belongs to does not have that currency. This might lead to erroneous payments, if the employee that enters them does not pay enough attention to the currency.

### Expected behavior

Either of these:
- When in All shop context, the default currency for payments must be the currency of the shop the order belongs to.
- When in All shop context, it is not possible to edit an order

If I recommend the second option, this is because I suspect multishop related problems with the order states and the emails that are sent to the customers while in All shop context

### Steps to reproduce

In a multishop context configure 
- shop 1 with currency 1
- shop 2 with currency 2, but without currency 1

1. In the BO, in All shop context, go to _Orders - Orders_
2. On an order that belongs to shop 2, click on _Edit_
3. Look at the payment section: the form for adding a payment has currency 1 selected as default.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.3

**Comment by sallemiines** [comment]
Hello @lmeyer1 
Thanks for reporting the issue.
Following your steps, i can't reproduce your issue, actually I'm blocked : 
I create 2 shops but I can't disable the default currency to not be exist in the second shop , see the attached scren record 


https://user-images.githubusercontent.com/31663369/195146747-96d12c28-5c4f-4bd7-86be-9f3d056c1d4f.mp4



Also there is an issue created about this behavior you can check it : [#9857](https://github.com/PrestaShop/PrestaShop/issues/9857)

Could you please provides us how you confugurate your shops with the deferent currencies ? 

Please check & Feedback !

**Comment by florine2623** [comment]
Hello @lmeyer1 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Comment by lmeyer1** [comment]
Issue https://github.com/PrestaShop/PrestaShop/issues/9857 is not related to mine. I will detail and clarify the steps to reproduce.
