### ISSUE TITLE
`Customer` property `is_guest ` not updated on change customer default `group`

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#29963]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Customer `is_guest` return wrong infos

### Expected behavior

The customer  `is_guest` must return the right info.

### Steps to reproduce

1. Go to BO
2. Edit a customer default group and set default group is guest
3. Run the request: ```SELECT `is_guest` FROM `ps_customer` WHERE `id_customer` = THE_CUSTOMER_ID```

### PrestaShop version(s) where the bug happened

1.7.8.7, develop

### PHP version(s) where the bug happened

N/A

**Comment by sallemiines** [comment]
Hello @PululuK 
 
Thanks for reporting the issue.
Im trying to reproduce your issue, but I wanna check if  you mean by : `Edit a customer default group and set default group is guest` this behavior , please check the screen shot bellow 

![image](https://user-images.githubusercontent.com/31663369/195149602-695e8391-bd05-4861-b499-4bc81c589da4.png)

Please check and feedback !

**Comment by PululuK** [comment]
Hi @sallemiines , thanks for the check

I'm talking about edit customer page 

![image](https://user-images.githubusercontent.com/16455155/195161067-082c93b3-b6cd-4e43-8dca-8fb766016a32.png)

**Comment by Hlavtox** [comment]
@PululuK It doesn't work like that. You must transform this guest to a customer.
Groups themselves or his default group are not tied to is_guest property.

**Comment by kpodemski** [comment]
I agree with @Hlavtox 

For now, groups are not the main indicator that this customer is a guest. This way, you'd change the customer to the guest by editing his groups, which is impossible.

**Comment by PululuK** [comment]
oh yes, you are right @Hlavtox @kpodemski ! Thanks guys

**Comment by hibatallahAouadni** [comment]
Thanks guys for your help :pray: @Hlavtox @kpodemski :rocket:
