### ISSUE TITLE
Duplicate, Delete & Preview from all shops / one shop

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#29987]
**US**
As a merchant, I want to delete, duplicate & preview from all shops / one shop

**Specs**
![image](https://user-images.githubusercontent.com/43613217/195462320-338162e4-66eb-4a43-ba50-42510c69a6d3.png)

| Is the product row has more than one shop in the Store(s) column? | Shop contexts | Edit | Duplicate | Enable | Disable | Delete | Preview |
| --- | --- | --- | --- | --- | --- | --- | --- |
| No | Single shop | Opens the edit page in same shop context  | Duplicates the product in the same shop context | Enables the product in the same shop context | Disables the product in the same shop context | Deletes the product in the same shop context | Open a new tab the product page in FO  |
| No | All shops / Groups shops | Opens the edition page in the shop context associated with the product | Duplicates the product in the shop context associated with the product | Enables the product in the shop context associated with the product | Disables the product in the shop context associated with the product | Deletes the product n the shop context associated with the product | Open a new tab the product page in FO in the shop context associated with the product |
| Yes | All shops / Groups shops | Opens the Shop-Selector-Modal before the edit page. <br> Modal title: ‘Choose a Store’ | Duplicates the selected product and all products associated with the selected product with the same shops association | Enables the selected product and all products associated with the selected product from all shops/groups shops.  | Disables the selected product and all products associated with the selected product from all shops/groups shops.  | Deletes the selected product and all products associated with the selected product from all shops/groups shops.  | Not displayed |

**Comment by jolelievre** [comment]
Closed by https://github.com/PrestaShop/PrestaShop/pull/31095
