### ISSUE TITLE
Make the new product list multistore

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#29986]
## **US**
As a merchant, I want in all shop context to know to which stores the product is associated to. 

## **Specs**
**Product Preview**
WHEN all shops or a group of shops is selected, THEN the column of Stores(s) is added to the listing.

Each item in the product list displays the product with a list of the names of the stores associated with the product, the image, the reference, main category, the price of the product without and with, the quantity of the product, the status and the actions.

The list of associated stores displays a maximum of 3 stores and then displays (…) the remaining stores.

The list of stores is displayed by id in ascending order. The default shop in the list is used to display the image, reference, price, category and quantity of the product. The default shop is displayed in bold. The default shop is the first element displayed in the list.

When “all shops” is selected, lists all the products and groups the products associated with different shops together. When a group of shops is selected, only the products list all the products belonging to the shop group and groups products associated with different shops together.

A product associated with different shops:

- Can’t be disabled from the list - the list displays “-”
- Stores(s) - Dropdown button - List all the shops associated with the product. When the dropdown is clicked THEN it displays the selected product and all products associated with the product. The clicked product row is emptied, it only keeps the data concerning the store list and its product image.
- The store column displays the shop name and the color with which it is associated
- Actions button wording depending on the multistore context:

| Is the product row has more than one shop in the Store(s) column? | Shop contexts | Edit | Duplicate | Enable | Disable | Delete | Preview |
| --- | --- | --- | --- | --- | --- | --- | --- |
| No | Single shop | Opens the edit page in same shop context  | Duplicates the product in the same shop context | Enables the product in the same shop context | Disables the product in the same shop context | Deletes the product in the same shop context | Open a new tab the product page in FO  |
| No | All shops / Groups shops | Opens the edition page in the shop context associated with the product | Duplicates the product in the shop context associated with the product | Enables the product in the shop context associated with the product | Disables the product in the shop context associated with the product | Deletes the product n the shop context associated with the product | Open a new tab the product page in FO in the shop context associated with the product |
| Yes | All shops / Groups shops | Opens the Shop-Selector-Modal before the edit page. <br> Modal title: ‘Choose a Store’ | Duplicates the selected product and all products associated with the selected product with the same shops association | Enables the selected product and all products associated with the selected product from all shops/groups shops.  | Disables the selected product and all products associated with the selected product from all shops/groups shops.  | Deletes the selected product and all products associated with the selected product from all shops/groups shops.  | Not displayed |

When a specific shop is selected, only the products belonging to this shop are displayed.

After selecting another shop than the current, I should return to the first page (issue <a href="[https://github.com/PrestaShop/PrestaShop/issues/9612](https://github.com/PrestaShop/PrestaShop/issues/9612)">9612</a>)

If on the last page all products are deleted, I should return to the first page (issue <a href="[https://github.com/PrestaShop/PrestaShop/issues/14713](https://github.com/PrestaShop/PrestaShop/issues/14713)">14713</a>), it's the same behavior another listing

### Product Preview

WHEN the product is associated to more than one store
THEN A dropdown is displayed next to the list of store. 

WHEN the dropdown is pressed 
THEN
It add to the product list all the product in each store in a preview panel. The inital row displays '-' for all the column

![image](https://user-images.githubusercontent.com/43613217/195459515-6e1d8e62-1a9f-4eb8-966d-f4f0d20cd283.png)

Preview should load with Ajax

## Technical Tasks

This will be split into several PRs (discussed with @jolelievre)

- [x] Build shop constraint automatically from ShopContext in kernel.request
- [x] Create a `MultishopProductGridDefinitionFactory` with the same fields  as the product field
- [x] #30734
- [x] Fill the grid with the data
- [x] [Add actions to the list](https://github.com/PrestaShop/PrestaShop/issues/29987) 
- [x] Add actions on preview rows

**Comment by FabienPapet** [comment]
This will be split into several PRs (discussed with @jolelievre 

- [ ] Build shop constraint automatically from ShopContext in kernel.request
- [ ] Create a `MultishopProductGridDefinitionFactory` with the same fields  as the product field
- [ ] Fill the grid with the data
- [ ] Add actions to the list (remove edit ?) 
- [ ] Add a preview of all shops with their associated data
- [ ] Add actions on preview rows

**Comment by jolelievre** [comment]
Closed by https://github.com/PrestaShop/PrestaShop/pull/31095
