### ISSUE TITLE
Theme should be able to not include the core.js files

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/PrestaShop#29994]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Theme should be able to do the whole behavior on their own, instead of being forced to use the corejs files!

### Describe the solution you'd like

A simple yml configuration to disable the corejs inclusion

### Additional context

On hummingbird side, we want to get rid of the core js which is a pain to maintain as a theme developer

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by kpodemski** [comment]
I agree, and I know it's needed, so I'm putting the "Ready" label. Is that enough @hibatallahAouadni? :))
