### ISSUE TITLE
Mail template variables in attributes were not replaced

### ISSUE THREAD

**Issue by ts2666** [PrestaShop/PrestaShop#30002]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Variables in mail templates were not replaced if they are attributes like in 
```
<a href="{guest_tracking_url}">
```
This is because when the mail template was added to the mailmessage in Mail.php the content was modified like this:
```
<a href="%7Bguest_tracking_url%7D">
```
I have modified vendor\swiftmailer\swiftmailer\lib\classes\Swift\Plugins\DecoratorPlugin.phpDecoratorPlugin.php
to replace them back:
line 122++
```
            $children = (array) $message->getChildren();
            foreach ($children as $child) {
                list($type) = sscanf($child->getContentType(), '%[^/]/%s');
                if ('text' == $type) {
                    $body = $child->getBody();
					
					$body=str_replace("%7B","{",$body);
					$body=str_replace("%7D","}",$body);
					
                    $bodyReplaced = str_replace(
                        $search, $replace, $body
                        );
                    if ($body != $bodyReplaced) {
                        $child->setBody($bodyReplaced);
                        $this->originalChildBodies[$child->getId()] = $body;
                    }
                }
            }
```
then it works again

### Steps to reproduce

Simple place an order and have a look in the mail. For example the URL is not replaced. 

https://user-images.githubusercontent.com/83036593/196691390-a5222120-a811-4228-8f4f-b8903f1013df.mp4

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.32

**Comment by hibatallahAouadni** [comment]
Hello @ts2666 

It seems your issue is similar to this one #27984
Could you please check and feedback.

Thanks!

**Comment by ts2666** [comment]
Hello @hibatallahAouadni 
No, it was not the same. In issue #27984 the variables are replaced with an empty value. In my issue the variables were not replaced and their names are in the email instead of the content. This was because swiftmailer was 'html encoding' the { and } to %7B and %ID around the variables so that the decorator Plugin did not found the variables to replace them.

**Comment by ts2666** [comment]
For better understanding here is an excerpt from the send mail:

`<div style="font-family:Open sans, arial, sans-serif;font-size:14px;line-height:25px;text-align:left;color:#363A41;" align="left">If you have a guest account, you can follow your order via the <a href="%7Bguest_tracking_url%7D" target="_blank" style="color: #25B9D7; text-decoration: underline; font-weight: 600;">Bestellverfolgung</a> section on our shop.</div>`

**Comment by hibatallahAouadni** [comment]
Hello @ts2666 

Could you please provide a screen record :pray: Cause with the provided infos, I only manage to reproduce the issue #27984 
Waiting for your feedback.

Thanks!

**Comment by ts2666** [comment]
Please note the attached video for details

https://user-images.githubusercontent.com/83036593/196691390-a5222120-a811-4228-8f4f-b8903f1013df.mp4

**Comment by hibatallahAouadni** [comment]
Hello @ts2666 

Thanks for your patience and the detailled screen record :clap: :pray: 
Ping @PrestaShop/prestashop-core-developers Could you please check this issue :pray: 

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @ts2666 

Could you please check if you still encounter the issue with PS8.1.1 :pray: 
Waiting for your feedback.

Thanks!

**Comment by paulnoelcholot** [comment]
Hello @ts2666,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
