### ISSUE TITLE
ContextErrorException Warning: proc_open() has been disabled for security reasons

### ISSUE THREAD

**Issue by Minde266** [PrestaShop/PrestaShop#30006]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

I am using Prestashop 1.7.8.6. The website URL is: http://www.savigynai.lt/ When I try to create a new account, on the last step I get the following issue. This issue also appears when I try to pay for the product.. The whole message looks as follows: 
![image](https://user-images.githubusercontent.com/115780131/195792726-64278e85-392a-4054-b3d3-cfd6a5e851ca.png)

Does any one maybe know what the reason for that could be? And how to fix it? I am new so a step by step solution would be appreciated

### Expected behavior

To solve the issue.

### Steps to reproduce

1. Go to http://www.savigynai.lt/
2. Press "Prisijungti"
3. Press "Neturite paskyros? Susikurkite ją čia"
4. Fill in some random information and press "Išsaugoti"

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4.29

### If your bug is related to a module, specify its name and its version

I don't know if it is.

**Comment by hibatallahAouadni** [comment]
Hello @Minde266 

Unfortunately, I didn't manage to reproduce the issue with your theme :disappointed: 
Try to switch to the Classic theme, check if you're able to reproduce the issue.
Closing the issue as there's no bug.

Thanks!

**Comment by HartLarsson** [comment]
you have a DEBUG on?
