### ISSUE TITLE
No se visualiza metodo de pago por transferencia

### ISSUE THREAD

**Issue by DarwinImple** [PrestaShop/PrestaShop#30003]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

No se visualiza el metodo de pago por transferencia (wirypayment), tengo activado el modulo pero enla pagina no se visualiza

### Expected behavior

visualizar la opcion de pago en la tienda

### Steps to reproduce

![image](https://user-images.githubusercontent.com/103607812/195645579-8d7946ae-45ac-4e50-b0a3-7c81ff85be55.png)
![Capturamet](https://user-images.githubusercontent.com/103607812/195645631-55fc6bb5-365c-4491-9e74-fd027a67e943.JPG)

no se visualiza metodo de pago por transferencia

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps

**Comment by hibatallahAouadni** [comment]
Hello @DarwinImple

Please send your request in English. English is the norm on GitHub.

Could you please provide a screenshot BO>IMPOROVE>Payment>Payment preference 🙏 
Waiting for your feedback.

Thank you

**Comment by DarwinImple** [comment]
> Hola@DarwinImple
> 
> Envíe su solicitud en inglés. El inglés es la norma en GitHub.
> 
> ¿Podría proporcionar una captura de pantalla? BO>IMPOROVE>Pago>Preferencia de pago🙏 Esperando sus comentarios.
> 
> Gracias

Yes,

![prefe](https://user-images.githubusercontent.com/103607812/195871199-cce5e4a8-dbf0-476b-b702-a90d70390dba.png)

**Comment by DarwinImple** [comment]
thanks , It's already resolved

**Comment by hibatallahAouadni** [comment]
Hello @DarwinImple 


Glad to hear and thanks for your feedback.
