### ISSUE TITLE
Fix errors in V.8 source strings

### ISSUE THREAD

**Issue by l-delin** [PrestaShop/PrestaShop#30008]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,
Here's an overhaul of every error I found in PS 8's source strings. Most of these are minor fixes to comply with the Product Glossary, but some of them are real issues (eg. number 1, 5 & 8). Could we please get those fixed for the next release? Thanks 💪

<img width="897" alt="image" src="https://user-images.githubusercontent.com/113511191/195798525-da851c13-ba4a-4ce1-8880-b1ad9d375fc9.png">
<img width="897" alt="image" src="https://user-images.githubusercontent.com/113511191/195798614-682ccdf8-c5f1-4e96-bdc1-22d1af6175f5.png">
<img width="897" alt="image" src="https://user-images.githubusercontent.com/113511191/195798751-f2d3a4c3-29ef-4c5e-bb6d-dcece1503921.png">

### Steps to reproduce

none

### PrestaShop version(s) where the bug happened

8

**Comment by hibatallahAouadni** [comment]
Hello @l-delin 

Thanks for your first issue :rocket: 
Ping @PrestaShop/wording-managers @PrestaShop/product-team please add the label `Verified` :pray: 

Thanks!

**Comment by MatShir** [comment]
@atomiix What is left to do ?

**Comment by atomiix** [comment]
@MatShir the PR on the autoupgrade module should be merged and I guess a new PR is needed to fix those wordings: https://github.com/PrestaShop/PrestaShop/pull/30521#issuecomment-1342287575
