### ISSUE TITLE
🚀 30000 Issues / PR already !

### ISSUE THREAD

**Issue by FabienPapet** [PrestaShop/PrestaShop#30001]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

😎 

### Steps to reproduce

Create prestashop repository and create 30000 issues / PR

### PrestaShop version(s) where the bug happened

8.0

**Comment by FabienPapet** [comment]
Fail 😂

**Comment by Robin-Fischer-PS** [comment]
Looser @FabienPapet !

**Comment by MatShir** [comment]
😂😂😂😂

**Comment by ghost** [comment]
Hahaha :) Je l'avais pas vu
