### ISSUE TITLE
Menu Bar - The start link is not displayed, nor is the link of the month's must-sees.

### ISSUE THREAD

**Issue by DarwinImple** [PrestaShop/PrestaShop#30016]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Menu Bar - The start link is not displayed, nor is the link of the month's must-sees.
![image](https://user-images.githubusercontent.com/103607812/195913698-8679d66e-c0d3-49a8-89a9-1b6f5e54f01e.png)

### Steps to reproduce

see the store page, the home link is not displayed

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

tvcmsmegamenu

**Comment by hibatallahAouadni** [comment]
Hello @DarwinImple 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must provide clear and concise steps to reproduce to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
