### ISSUE TITLE
European VAT number

### ISSUE THREAD

**Issue by foglmagna** [PrestaShop/PrestaShop#30013]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,
The module does not verify the VAT number. Probably a problem.
I have tried many times on alerts from customers.
![obrazek](https://user-images.githubusercontent.com/65302317/195849678-a5a68d3b-d5d0-4ecb-9cf2-7134a4fd9afc.png)

### Steps to reproduce

Enter company
Enter VAT
Enter Country

### PrestaShop version(s) where the bug happened

1.7.6.2

### PHP version(s) where the bug happened

7.2.34

### If your bug is related to a module, specify its name and its version

European VAT number 2.1.0

**Comment by hibatallahAouadni** [comment]
Hello @foglmagna 

This module has been archived, it’s no longer maintained but you still can fork it if you need it for your shop.
Also let us know if you are voluntary to maintain this module.

Thanks!
