### ISSUE TITLE
Override Class ImageManager is impossible

### ISSUE THREAD

**Issue by slupostrupek** [PrestaShop/PrestaShop#30015]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Creating ImageManager class of ImageManagerCore will override LegacyImageManager.
Impossible to override ImageManagerCore

### Expected behavior

ImageManager ovverride class should override ImageManagerCore

### Steps to reproduce

Create Module with override ImageManagerCore

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.2

**Comment by sallemiines** [comment]
Hello @slupostrupek ,

Could you please provide us with more info ?
We need more details to understand how we can reproduce your issue:
**Example :** 
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
- ... ...... 

You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

Thank you !

**Comment by slupostrupek** [comment]
![imagemanager missing funtion](https://user-images.githubusercontent.com/9866119/196156370-d043037b-025f-4e66-91f4-31441d64c315.jpg)
[overridexample.zip](https://github.com/PrestaShop/PrestaShop/files/9799568/overridexample.zip) - simple module with imagemanager override, but when it overrides iamagemanager , prestashop throwes errors of missing functions.

**Comment by slupostrupek** [comment]
Module override but three are errors of missing function its bug
