### ISSUE TITLE
Missing primary key on accessory table

### ISSUE THREAD

**Issue by jgillich** [PrestaShop/PrestaShop#30022]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The accessory table does not have a primary key. This causes queries to fail when using [Percona XtraDB](https://www.percona.com/software/mysql-database/percona-xtradb-cluster) because it [requires a primary key](https://docs.percona.com/percona-xtradb-cluster/5.7/features/pxc-strict-mode.html#tables-without-the-primary-key).

Other replication solutions may also be affected.

### Steps to reproduce

1. Install PrestaShop and use Percona XtraDB as your database
2. Check the XtraDB logs and find this error:
```
Percona-XtraDB-Cluster prohibits use of DML command on a table (prestashop_41c9cd86_mysql.ps_accessory) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER
```

### PrestaShop version(s) where the bug happened

1.7.8.7

**Comment by hibatallahAouadni** [comment]
Hello @jgillich 

Thanks for reporting the issue!
Ping @PrestaShop/prestashop-maintainers someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by jgillich** [comment]
I think the solution might be to change this to `PRIMARY KEY` https://github.com/PrestaShop/PrestaShop/blob/d1e14ec7b1f959f370915ecb9b34afe28b098e88/install-dev/data/db_structure.sql#L9

And adding a migration somewhere?

All other tables already have primary keys as far as I can tell.

**Comment by hibatallahAouadni** [comment]
Hello @jgillich 

Do you still encounter the issue with 8.1.1? Please check and feedback.

Thanks!

**Comment by kpodemski** [comment]
@hibatallahAouadni, we didn't change the database structure for this table on PrestaShop 8, so yes, this error will still be there.

**Comment by hibatallahAouadni** [comment]
Changing the labels as @kpodemski reproduce it
