### ISSUE TITLE
Typo in Configuration key on images management 

### ISSUE THREAD

**Issue by nicosomb** [PrestaShop/PrestaShop#30032]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In `controllers/admin/AdminImagesController.php`, there is a configuration key, which is named `PS_HIGHT_DPI`. The correct name should be `PS_HIGH_DPI`. 

We can depreciate it (with a script to update the database). 
We can also implement a new feature (alias for configuration keys).

### Steps to reproduce

Open the `controllers/admin/AdminImagesController.php` file, line 189. 

### PrestaShop version(s) where the bug happened

develop

**Comment by AureRita** [comment]
Hi @nicosomb ,

Thank for this report. I find the issue with PrestaShop version 1.7.7.8, as we can see in this screenshot : 

![image](https://user-images.githubusercontent.com/100699445/196440854-31a04e8e-1e87-4f2d-862f-e537090b48f7.png)

 I'll add this to the backlog so it can be fixed.
 
 Caution, this one is present three time in the script so it can be in other script I think 

Please be aware that some issues might take a very long time to be resolved. 

Waiting for your PR :rocket: 

Thanks

**Comment by nicosomb** [comment]
@AureRita I also saw that this configuration key is not available in `install-dev/data/xml/configuration.xml` (files to store default values). Is that a bug?

**Comment by AureRita** [comment]
I checked my `install-dev/data/xml/configuration.xml` and I didn't see the key `PS_HIGHT_DPI`

**Comment by Hlavtox** [comment]
@nicosomb @AureRita This spelling error is everywhere in the core.

This feature is obsolete and will be removed in the near future, I wouldn't loose time on it. ✌️

**Comment by nicosomb** [comment]
@Hlavtox oh you're right, it's planned on https://github.com/PrestaShop/PrestaShop/issues/27318. Sorry for the noise. 

So should we close this issue?

**Comment by Hlavtox** [comment]
Feature removed from develop
