### ISSUE TITLE
Can not get smarty context in prestashop 1.8

### ISSUE THREAD

**Issue by web23421** [PrestaShop/PrestaShop#30044]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello, I see that, I can not get smarty context in prestashop 1.8 and prestashop 1.8 rc1 in my module. I get context to process it and find variables of the module in the product descriptions or category descriptions. I found this problem in category and product page in front office.

I do it in my code of module like this:
For category page:
$category = $this->context->smarty->getVariable('category');

For product page:
$product = $this->context->smarty->getVariable('product')->value;

See screenshot for product page
![333](https://user-images.githubusercontent.com/72523258/196348947-b2635ace-2060-4e00-bb0a-e259ab0f7841.png)

### Expected behavior

So, in prestashop 1.7.8.7 - everything fine. I think the problem in smarty methods like getVariable

### Steps to reproduce

1. Create module with line  $this->context->smarty->getVariable('product')->value; 
2. Go to product page
3. And you can see this error. I think.

### PrestaShop version(s) where the bug happened

1.8 or 1.8rc1

### PHP version(s) where the bug happened

7.4.27 

### If your bug is related to a module, specify its name and its version

galslidereverywhere 1.9.3

**Comment by kpodemski** [comment]
Hello @web23421 

Why would you get Smarty variables this way? 🤔 You can access the category, and product object this way:

`$this->context->controller->getCategory()` && `$this->context->controller->getProduct()`

From what I see, this function was deprecated years ago:
https://capture.dropbox.com/hMmzsDgPfTePaCcA

And it is now removed from the Smarty core.

**Comment by PrestaEdit** [comment]
As Smarty was updated inside this version, deprecated methods are not usable.

You need to use the `getTemplateVars('product')` , also available on the 1.7 PrestaShop.

This is not a bug, it's a need to make compliant the galslidereverywhere module.

**Comment by Hlavtox** [comment]
What about `$this->context->smarty->tpl_vars['customizationFields']->value`?

**Comment by web23421** [comment]
Ok, thanks everybody. Yes, the problem with compatibility of the module. I have replaced by this code: 

getTemplateVars('product')
$this->context->controller->getProduct()

It works.
