### ISSUE TITLE
[FO] Address not updated in Checkout

### ISSUE THREAD

**Issue by fc-mbouzidi** [PrestaShop/PrestaShop#30040]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the checkout, when I edit an address (for the delivery or the invoice), it create a new address and select the new address. The old address is still there without any modification.

### Expected behavior

If we edit an address, according to the database structure, it should create a new address and select it.

The old address should be set to active = 0 and deleted = 1 in the database and nor be shown in the front-office (even in the customer addresses in the back-office)

### Steps to reproduce

1. Start a new checkout 
2. Create addresses if needed
3. Try to edit an address

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.2

**Comment by fc-mbouzidi** [comment]
My bad I tried with the classic theme and it works. It comes from my template

**Comment by AureRita** [comment]
Hi @fc-mbouzidi 

Thank you for your report and your investigation, 

I will close this issue 

Have a great day
