### ISSUE TITLE
Cards helper redirect to 1.7 documentation

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#30043]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

As the user doc of v8 is not yet published, every links on the helper cards are made to reach 1.7.

See https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Resources/config/services/core/util/helper_card.yml

### Expected behavior

Reach v8 docs.

### Steps to reproduce

1. Go to CMS pages management
2. See the block on the top, and go to it's "See more" link

### PrestaShop version(s) where the bug happened

8.0.0-rc.1

**Comment by AureRita** [comment]
Hi @PrestaEdit  ,

Despite our efforts, we were not able to reproduce your issue with the provided information. As you can see in this video : 

[Untitled_ Oct 18, 2022 11_42 AM.webm](https://user-images.githubusercontent.com/100699445/196396351-1bce8ebf-9298-4d53-923c-a7cb9fa5b5fa.webm)

I verified different page wich the problem should be present. 

Can you give me maybe a screen to show me this issue ? 

Thank you

**Comment by PrestaEdit** [comment]
Hi,

Not the "Help" button, but the Helper card, the one where you can see the "Lear more" button on your screen.

**Comment by AureRita** [comment]
Thank you for this details,

I reproduce the issue with PrestaShop version 8.0.0, as we can see here : 

[Untitled_ Oct 18, 2022 11_52 AM.webm](https://user-images.githubusercontent.com/100699445/196398862-e6023176-6931-4819-848d-fedda36edf19.webm)

I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. 

Thanks
