### ISSUE TITLE
On AdminImages, when I don't fill a required field, the form is even so saved

### ISSUE THREAD

**Issue by nicosomb** [PrestaShop/PrestaShop#30046]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On images administration, there are some required fields, for example "JPEG compression". 

If I don't fill this field (the field need to be blank), and at the same time, if I update an other field, for example "PNG compression", when I submit the form, I've got an error "JPEG compression field is required" **but** the new value in the PNG compression field is saved. 

### Expected behavior

An error message should be displayed and the other updated fields shouldn't be updated. 

### Steps to reproduce

1. Go to images admin
2. Empty the JPG compression field 
3. Update an other field, for example PNG compression 
4. Submit the form 

### PrestaShop version(s) where the bug happened

develop

**Comment by AureRita** [comment]
Hi @nicosomb ,

Thank you for your report. I reproduce the issue with PrestaShop version 1.7.7.8, we can see the issue in this video : 

[Untitled_ Oct 18, 2022 2_23 PM.webm](https://user-images.githubusercontent.com/100699445/196429103-e0c6f018-c43d-4e11-b96b-4a5b5bb537a7.webm)

I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved

Waiting for your PR :rocket: 

Thanks
