### ISSUE TITLE
[Console] Error when accessing to BO symfony pages

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShop/PrestaShop#30051]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

404 Error pops on console when trying to open BO > symfony pages
![image](https://user-images.githubusercontent.com/48441421/196442205-ad9f766e-76a2-4e03-9ce3-3b75dcc76a6b.png)

### Expected behavior

No Error

### Steps to reproduce

1. Login to BO 
2. Open Console Tab on the browser
3. Go to Menu -> Catalog -> Categories (works with other symfony pages too)
4. See error displayed on Console (the same on network tab)

### PrestaShop version(s) where the bug happened

8.0.x, 8.0.0-rc

### PHP version(s) where the bug happened

N/A

### If your bug is related to a module, specify its name and its version

N/A

**Comment by AureRita** [comment]
Hi @boubkerbribri  ,

Thank for your report. I reproduce the issue with PrestaShop version 8.0.0 and not with the version 1.7.8.7. You can see the issue on this video : 

[Untitled_ Oct 18, 2022 3_42 PM.webm](https://user-images.githubusercontent.com/100699445/196447324-737038e4-9a6f-4551-a213-9d7497a69cd8.webm)

Nice catch ! It's a regression ! I'll add it to the patch backlog.

Please be aware that some issues might take a very long time to be resolved.

Thank you

**Comment by nicosomb** [comment]
The issue seems to come from `admin-dev/themes/new-theme/public/preload.tpl` with the `{$admin_dir}` variable.

**Comment by nicosomb** [comment]
Maybe this commit https://github.com/PrestaShop/PrestaShop/commit/f3e107b1cf959b57fd2da6193667e28e5088bf2c#diff-a0c11aa945b1bc083a28bb4c339304f0f8fdf8e6bbcb8a8741366da887c2aaa4

**Comment by eshraw** [comment]
To investigate w/ dev @PrestaShop/product-team

**Comment by matks** [comment]
Hello everyone I just checked on `develop` branch and I can't see the issue. I guess it was fixed 😉
