### ISSUE TITLE
FO - The images are not well displayed in the product details page

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#30056]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The images are not well displayed in the product details page

When the images number is < 5 ==> The main image is too small 

![image](https://user-images.githubusercontent.com/92912932/196457191-9859c8e6-c2b5-4989-97f3-e15de0ddb708.png)

PS1787 : Ok :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/196457291-7be096c0-27c1-499b-8fdc-c136522dc576.png)

When the images number is >= 5 ==> All images are not well dispalyed

**PS8.0.x : NOK** :x: 

https://user-images.githubusercontent.com/92912932/196457949-52e39cf8-bdf7-46c6-8f0c-bf9c8c40e253.mp4

![image](https://user-images.githubusercontent.com/92912932/196457410-5f626ffb-b763-4476-a865-25ac1abb225c.png)

![image](https://user-images.githubusercontent.com/92912932/196457438-db9237dc-12d7-4536-8829-845e68f748bf.png)

**PS1.7.8.7 : OK** :heavy_check_mark: 

https://user-images.githubusercontent.com/92912932/196458130-27a286d0-a08b-49c9-bc23-cea38a7fa643.mp4

![image](https://user-images.githubusercontent.com/92912932/196458399-58dc1ffe-ce5c-4822-81c1-0dc6aeae0628.png)

**RC8.0.0 : OK** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/196464695-6c086c80-c3b9-40e6-a857-43d9f276c280.png)

### Expected behavior

The images are well displayed as on PS1787

### Steps to reproduce

1. Go to BO > Products V1 Or V2
2. Edit any product > Basic settings > Add images 
3. Click on preview 
4. In FO > Click to quick view the images 
5. See error > The images are not well displayed

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

classic-theme v2.0.2 and v2.0.3

**Comment by AureRita** [comment]
Hi @HanaRebaiQA  ,

I reproduce the issue with PrestaShop version 8.0.x and not with the version 8.0.0-RC, as you can see in this video : 

[Untitled_ Oct 18, 2022 5_25 PM.webm](https://user-images.githubusercontent.com/100699445/196474351-da5fddc3-0fb6-44d5-90e2-aa0a25769be8.webm)

Nice catch ! It's a regression ! I'll add it to the patch backlog.

it's normal that my pictures have a bad resolution 

Please be aware that some issues might take a very long time to be resolved.

Thank you
