### ISSUE TITLE
BO - Orders - The gift message is not visible enough

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#30059]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you allow the customer to buy a gift package in it's order, he could add a gift message.

Order into Back Office will show the "Gift package" label but not the message.

### Steps to reproduce

1. Enable gift package
2. Pass an order and add a gift message

### PrestaShop version(s) where the bug happened

8.0.0-rc.1

**Comment by PrestaEdit** [comment]
Actually, it's visible but you need to know that it will be.
"Gift package" label is shown on the loading, but the gift message will be on the carrier tab.

<img width="682" alt="Capture d’écran 2022-10-18 à 23 53 25" src="https://user-images.githubusercontent.com/2631425/196552123-2e73ebea-84c9-4395-a618-67027f280c1d.png">

<img width="682" alt="Capture d’écran 2022-10-18 à 23 53 20" src="https://user-images.githubusercontent.com/2631425/196552118-a73f9406-a800-4fa7-bd54-c6b7ec53adfc.png">

**Comment by paulnoelcholot** [comment]
Hi @PrestaEdit,

If I understand the problem, the step to reproduice is : 

On BO : 
1. Go to Shop Parameters > Order Settings
2. Enable the "Offer gift wrapping"

On FO : 
3. Place a order with the gift wrap option enabled in the delivery method and adding a message with the gift.

On BO : 
4. Orders > Orders > click on the order details

I can't see the message added to the gift. The content of this message should be displayed in the "Status" tabnext to "Gift wrapping" label.

That's right?

https://watch.screencastify.com/v/WWCy5gYrDn2RxICOPpM0

**Comment by florine2623** [comment]
Hello @PrestaEdit ,

This is more a new feature than a bug ^^

Your idea is to have the Gift message displayed on all tabs, is that right ?

https://user-images.githubusercontent.com/16019289/199019203-87a70ca2-852c-4113-8fbd-379548236a73.mov

Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you create it. 

If you or anyone else is willing to [contribute this feature](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/) to the PrestaShop Project, the teams will be happy to help by ensuring that it fits well within the project. Please let us know if that is the case!

Thank you

**Comment by florine2623** [comment]
@PrestaShop/product-team ,

Would it be possible to add the gift message on all tabs (Status, Documents, Carriers, Merchandise returns) in the order view section ?

Thanks!
