### ISSUE TITLE
blockreassurance - use pure HTML a tag instead of JavaScript window.open method

### ISSUE THREAD

**Issue by leemyongpakvn** [PrestaShop/PrestaShop#30055]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Three templates in module blockreassurance [displayBlock.tpl](https://github.com/PrestaShop/blockreassurance/blob/dev/views/templates/hook/displayBlock.tpl#L48), [displayBlockProduct.tpl](https://github.com/PrestaShop/blockreassurance/blob/dev/views/templates/hook/displayBlock.tpl#L48), [displayBlockWhite.tpl](https://github.com/PrestaShop/blockreassurance/blob/dev/views/templates/hook/displayBlockWhite.tpl#L47) are using JavaScript `window.open` method to emulate a link.
@nicosomb and @matks suggested using pure html `a` tag instead.

### Describe the solution you'd like

We don't have any validation with links there so just replace the JavaScript `window.open` by a pure HTML `a` tag

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by AureRita** [comment]
Hi @leemyongpakvn  ,

Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments. 

Waiting for your PR :rocket: !

Thank you

**Comment by matks** [comment]
Idea is good 👍 and we're discussing the implementation in https://github.com/PrestaShop/blockreassurance/pull/455

**Comment by leemyongpakvn** [comment]
Close as the use case of the trick is clarified.
