### ISSUE TITLE
Unnamed images for other languages

### ISSUE THREAD

**Issue by Timoenhilda09** [PrestaShop/PrestaShop#30058]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

For some reason, 

When creating a new product in BO:
the productimages only appear for the default language (dutch), most of the time for the English, Deutsch and Spanish language. Sometimes only in Dutch.
When uploading images by CSV images, images for all languages work just fine.
All migrated products (from Prestashop 1.6, using Migration Pro module) only have in Dutch and English the images (that languages were already on our old shop). The new languages doesn't have the images.

It is only frontoffice. Backoffice no problems.
For example: <img src="mysite.com/33-home_default/.jpg">

I already searched in the database, but all looks fine. I don't see any differences between the languages.

### Expected behavior

the productimages should all have the same name, as they are using the same image.

### Steps to reproduce

1. create product
2. save product
3. check on front end.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

**Comment by Hlavtox** [comment]
Hi @Timoenhilda09, thank you for reproducing an issue I didn't know how to reproduce 😄

This PR will fix it - https://github.com/PrestaShop/PrestaShop/pull/27758.

**Comment by Timoenhilda09** [comment]
Thank you!

**Comment by hibatallahAouadni** [comment]
Duplicate of #27757

**Comment by Hlavtox** [comment]
@Timoenhilda09 Fixed on develop ;-)
