### ISSUE TITLE
Disabling customer groups feature still show them inside customer edition

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#30060]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If you disable the customers's groups feature, you still see them on the customer sheet and inside the edit form.

### Expected behavior

Does not see group if feature is disabled.

### Steps to reproduce

1. Go to performances tab
2. Disable "Groups" feature
3. See customer

### PrestaShop version(s) where the bug happened

8.0.0-rc.1

**Comment by paulnoelcholot** [comment]
Hi @PrestaEdit 

Thanks for this issue. Could you specify what you mean by "see customer" and the path to access it?

Waiting for your comment

**Comment by PrestaEdit** [comment]
I mean going to Customers listing and see details/ edit it.

**Comment by paulnoelcholot** [comment]
If I understand the problem, the step to reproduce is:

1. Go to performances tab
2. Disable the customers groups
3. Go to Customers > Customers > Edit a customer
I should not have access to this feature and a message should tell me that the feature has been disabled and give me a link to enable the feature. That's right?

https://watch.screencastify.com/v/VylwyGILF4SpnxcEATqV

**Comment by florine2623** [comment]
Hello @PrestaEdit ,

Could you check @paulnoelcholot 's video and confirm that this is your issue ?

> https://watch.screencastify.com/v/VylwyGILF4SpnxcEATqV

I checked on PS 1.7.8.7, it is the same behavior as it is in 8.0.0 and 8.0.0 rc1.
