### ISSUE TITLE
Groups could be managed even with feature disabled

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#30062]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When the customers groups feature is disabled, you sill can configure add/edit some groups.

### Expected behavior

Like the features, having a warning about feature disabled.

<img width="682" alt="Capture d’écran 2022-10-19 à 00 09 14" src="https://user-images.githubusercontent.com/2631425/196554384-6cff1d7a-668a-4abc-a0cd-f30f428180d8.png">

### Steps to reproduce

1. Go to performances tab
2. Disable the customers groups
3. Go to Preferences > Customer > Groups

### PrestaShop version(s) where the bug happened

8.0.0-rc.1

**Comment by paulnoelcholot** [comment]
Hello @PrestaEdit,

Thanks for your issue.

If I understand the problem, the step to reproduce is:
1. Go to performances tab
2. Disable the customers groups
3. Go to Shop Parameters > Customer Settings > Groups

I should not have access to this feature and a message should tell me that the feature has been disabled and give me a link to enable the feature. That's right?

https://watch.screencastify.com/v/vB8EhwNzhlmiw08TRADR

Waiting for your comment

**Comment by PrestaEdit** [comment]
Hi @paulnoelcholot,

It's exactly that. Your screen capture is perfect to explain this ! :)

**Comment by paulnoelcholot** [comment]
Thank you @PrestaEdit,

I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved.

Thanks

**Comment by matks** [comment]
Issue closed but still valid
