### ISSUE TITLE
Product Page V2 - Features are still configurable on product sheet while you disable features optional feature

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#30061]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If you disable the "Features" feature, the product sheet still allow you to add a feature.

### Steps to reproduce

1. In BO > Advanced parameters > New & Experimental features > Enable new product page
2. Go to performances tab
3. Disable the "Features" feature
4. Go to product edition
5. See that Features config is still available

### PrestaShop version(s) where the bug happened

8.0.0-rc.1

**Comment by paulnoelcholot** [comment]
Hi @PrestaEdit

Thanks for this issue. Could you specify what you mean by "product edition", the path to access it and a screenshot of result please?

Waiting for your comment

**Comment by PrestaEdit** [comment]
I mean Going to catalog, see products list and edit it.

**Comment by paulnoelcholot** [comment]
Thanks. Do you have a visual proposal for us on the desired result?

**Comment by florine2623** [comment]
Hello @PrestaEdit ,

Indeed, I reproduced your issue on PS 8.0.0 with Product Page V2 activated, I'll add this to the backlog so it can be fixed.

In Product Page V1, when you disable the Feature Options, you don't have access to:
- BO, Feature config in Product page
- BO, Attributes and Features page
- FO, Product details

In product V2, you still have access to:
- BO, Feature config in Product page ❌ 
This is OK:
- BO, Attributes and Features page 
- FO, Product details 

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
