### ISSUE TITLE
GDPR Module - translation on help section is always on English

### ISSUE THREAD

**Issue by PrestaPierre** [PrestaShop/PrestaShop#30063]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Help part on GDPR module is always in english even if the merchant uses another language.

Version: 8.0.0 in French language

<img width="1412" alt="Capture d’écran 2022-10-19 à 10 57 48" src="https://user-images.githubusercontent.com/112935373/196672715-abb7ee31-9bb0-432c-8f93-e0eb12261eac.png">

Version : 1.7.8.7 in French language

<img width="1423" alt="Capture d’écran 2022-10-19 à 11 01 59" src="https://user-images.githubusercontent.com/112935373/196672735-e9012712-9677-499c-8677-98be8c0d0799.png">

Version: 1.7.7.8 in French language

![Capture d’écran 2022-10-19 à 10 53 08](https://user-images.githubusercontent.com/112935373/196673288-d0217609-7e45-4e24-aac0-5c4e79d9324f.png)

### Expected behavior

I want to have my help section in my language and not only in English

### Steps to reproduce

- Go to your BO > Modules > Module Manager > Search GDPR module
- Click on Configure > Go to help section
- See error on the right part

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1.0

### If your bug is related to a module, specify its name and its version

psgdpr V.1.4.2

**Comment by paulnoelcholot** [comment]
Hi @PrestaPierre,

I reproduce the issue with PrestaShop version 8.0.0 as we can see here : 

https://watch.screencastify.com/v/3ihC9x6ZcrWs6AyYb9FB

I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved.

Thanks

**Comment by florine2623** [comment]
This issue is fixed with GDPR v1.4.3.

https://github.com/user-attachments/assets/d324c0ec-af2c-49fa-990c-136a7303e289

I'm closing the issue.
