### ISSUE TITLE
Copy of an email is not sent to Bcc address in PS 8.0.0

### ISSUE THREAD

**Issue by teemumantynen** [PrestaShop/PrestaShop#30077]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Copy of an email is not sent to Bcc (blind carbon copy) address.

Each Bcc is logged as separate row to E-mail log (BO / Advanced Parameters / E-mail) as expected. No error message in server's or PrestaShop's log files.

When using Xdebug it appears that Bcc addess is passed from Mail::send() to Swift_Mailer::send() among other message parameters.

### Expected behavior

In earlier PrestaShop versions a copy of an email is sent to each Bcc address. If email logging is active, each Bcc creates an additional separate row to E-mail log (BO / Advanced Parameters / E-mail).

### Steps to reproduce

1. Open BO / Advanced Parameters / E-mail. Make sure config "Log Emails" is set to "Yes".

2. Install an addon module which implements hook ActionEmailSendBefore and in which one or more email addresses are set as values of the bcc-field in hook's parameters.

3. Perform any task that sends an email utilizing PrestaShop's Mail::send()-method. E.g. place an order to trigger order confirmation email.

4. Open BO / Advanced Parameters / E-mail. See rows of logged emails. There should be one row for the To: address and one row for each Bcc: address of the email sent in step 3.

5. See email inbox of the To: address. The email sent in step 3 should be there.

6. See email inbox of one of the Bcc: addresses. A copy of the email sent in step 3 should be there. In PrestaShop 1.7.1-1.7.8 this is fine, but in PrestaShop 8.0.0 Bcc-emails are apparently not sent.

### PrestaShop version(s) where the bug happened

8.0.0 rc1

### PHP version(s) where the bug happened

7.4 and 8.1

**Comment by HanaRebaiQA** [comment]
Hello @teemumantynen 

Thanks for your report.
Could you please specify concise and clear steps to reproduce with a screenshot or a screen-record to reproduce your issue :pray: 

Thanks!

**Comment by teemumantynen** [comment]
Hi @HanaRebaiQA

Steps to reproduce:

1. Open BO / Advanced Parameters / E-mail. Make sure config "Log Emails" is set to "Yes".

2. Install an addon module which implements hook ActionEmailSendBefore and in which one or more email addresses are set as values of the bcc-field in hook's parameters.

3. Perform any task that sends an email utilizing PrestaShop's Mail::send()-method. E.g. place an order to trigger order confirmation email.

4. Open BO / Advanced Parameters / E-mail. See rows of logged emails. There should be one row for the To: address and one row for each Bcc: address of the email sent in step 3.

5. See email inbox of the To: address. The email sent in step 3 should be there.

6. See email inbox of one of the Bcc: addresses. A copy of the email sent in step 3 should be there. In PrestaShop 1.7.1-1.7.8 this is fine, but in PrestaShop 8.0.0 Bcc-emails are apparently not sent.

Thank you.

**Comment by hibatallahAouadni** [comment]
Hello @teemumantynen 

We didn't manage to reproduce your issue without a module and it seems that your issue is not a PrestaShop core bug.
If your module is Official, please contact support team on Addons.

We will close this issue.

Thanks!
