### ISSUE TITLE
FO / Blockwishlist / Mobile - Filter select on small screens are too long

### ISSUE THREAD

**Issue by sLorenzini** [PrestaShop/PrestaShop#30070]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I am on very small screen (below 320px) in my wishlist list in my account user, filter select is too long and an horizontally scroll is added to the window
Tested on 8.0.x / 1.7.8.x / 1.7.7.8 version with blockwishlist module 2.1.2 version. 
No regression

8.0.x ❌ 

![wishlist-filter-mobile-8 0 x](https://user-images.githubusercontent.com/2854834/196724386-7dace66f-4854-4758-a22f-278aba2fafe1.png)

1.7.8.x ❌ 

![wishlist-filter-mobile-1 7 8 x](https://user-images.githubusercontent.com/2854834/196724474-bec32d8b-26dc-4add-8ada-95b8b207e626.png)

1.7.7.8 ❌ 

![wishlist-filter-mobile-1 7 7 8](https://user-images.githubusercontent.com/2854834/196724346-3afb6107-52ec-46ac-93b6-38355f98e52d.png)

### Expected behavior

Filter select should be stayed in its parent section in small screen

### Steps to reproduce

- Go to FO > Click on "Sign in" link > Fill the form with your logins to be logged
- Go to "My wishlists" tab > Click on the default list
- Put your browser on small screen (310px for example)
- See error, filter select is too long

### PrestaShop version(s) where the bug happened

8.0.x / 1.7.8.x / 1.7.7.8

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

blockwishlist 2.1.2

**Comment by HanaRebaiQA** [comment]
Hello @sLorenzini 

Thanks for your report.
I was able to reproduce your issue with 8.0.0RC.

![image](https://user-images.githubusercontent.com/92912932/197007548-4a816f88-7e3b-4e8c-b463-23e2f39bce3b.png)

I'll add this to the debug backlog so that it's fixed.

Thank You!
