### ISSUE TITLE
Legacy translations system is not usable on Front Office with modules having _ in their name

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#30076]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Due to this change (https://github.com/PrestaShop/PrestaShop/pull/27422) and more this line (https://github.com/PrestaShop/PrestaShop/pull/27422/files#diff-0c21bad472a0e3ca7a6d316f7413c14548a102ceaf592118477149b0e74b948aR185), every module using an underscore inside their name lost translations on Front Office (template).

This was not present with the beta release of the 8.0.0, it's was added into 1.7.8.8 and merge into 8.0.0(rc.1) after feature freeze.

### Expected behavior

Of course : not loosing translations.

### Steps to reproduce

1. Have two languages : EN and FR.
2. Install the module in example.
3. Go on the homepage.
4. - On version <= 1.7.8.7: You will see the text "Hello world !" in english and "Bonjour !" in french.
- On version 1.7.8.8/8.0.0(rc.1): You will see the text "Hello world !" in english and the same in french.
[issu_e.zip](https://github.com/PrestaShop/PrestaShop/files/9827048/issu_e.zip)

### PrestaShop version(s) where the bug happened

1.7.8.8, 8.0.0-rc.1

**Comment by jf-viguier** [comment]
Thanks @PrestaEdit, U rocks

**Comment by HanaRebaiQA** [comment]
Hello @PrestaEdit 

Thanks for your report.
I was able to reproduce your issue on **PS178x** and **PS8.0 RC build1**.

**PS1787 : OK** :heavy_check_mark: 

https://user-images.githubusercontent.com/92912932/196926952-47f98595-e69c-41da-afb2-1c619d891457.mp4


**PS178x  : NOK** :x: 

https://user-images.githubusercontent.com/92912932/196926896-e1ee6229-5b22-45d2-b60b-fe7699ce0728.mp4


**PS8.0RC build1 : NOK** :x: 

https://user-images.githubusercontent.com/92912932/196921405-01563b2f-9507-42bf-ba34-66aba585361a.mp4

Indeed, it's a regression on PS178x and 8.0.x
I'll add this to the debug backlog so that it's fixed.

Please be aware that due to the high number of reported issues, some bugs might take a very long time to be resolved. If this issue is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you. 

We are waiting for the PR !

Thank You!

**Comment by PrestaEdit** [comment]
Minor ?

**Comment by HanaRebaiQA** [comment]
Minor because : Results in some unexpected or undesired behavior, but not enough to disrupt system function

**Comment by jf-viguier** [comment]
@HanaRebaiQA is not minor IMO because most of modules have _ in they names.

**Comment by Prestaworks** [comment]
> @HanaRebaiQA is not minor IMO because most of modules have _ in they names.

yes, but devs are not supposed to do that.
https://devdocs.prestashop-project.org/1.7/modules/creation/module-file-structure/

I guess the legacy translation system will be dropped in the future and then those modules will still not work properly. So best thing is to rename the modules for Prestashop8 and use the new translation system.

**Comment by jf-viguier** [comment]
@Prestaworks you cannot change years of development habits in a finger snap, By the way, think about specific code in place for years.
Upgrade to PrestaShop 8 should be smooth, it's the strategy explained by @matks and @eternoendless, we should fit to it.

**Comment by Prestaworks** [comment]
> @Prestaworks you cannot change years of development habits in a finger snap, By the way, think about specific code in place for years. Upgrade to PrestaShop 8 should be smooth, it's the strategy explained by @matks and @eternoendless, we should fit to it.

The _ "recommendation" has been there for basicly the entire 1.7 life time :) so it's not "a finger snap".

**Comment by PrestaEdit** [comment]
It's only a suggestion, and for your information the newest system is only available since 1.7.6 and usable with XLF files on 1.7.8.

You can't change the way of third party module are working without depreciation and nothing as this as you want, for sure.

**Comment by Prestaworks** [comment]
> 

I don't say it's a bad thing to fix this, but eventually the legacy system will have to be dropped. We can't have two systems for translations forever.

**Comment by PrestaEdit** [comment]
That it's true. Surely in v9. If the newest system work wells, it will be a pleasure to use it ;-)

**Comment by PrestaEdit** [comment]
Also, FIY, there is something wrong : this mention was only added one year ago, in this page. On the end of July 2021 :)

**Comment by HanaRebaiQA** [comment]
Hello everybody,

As seen with @khouloudbelguith, we checked this issue with a native module (eg. `ps_emailsubscription`) with **8.0.0RC build1 without PR** having an underscore  in its name.
We did not reproduce the issue using this native module. The translation is well updated with French language. 

This is a screen-record : 


https://user-images.githubusercontent.com/92912932/197214219-4a0750c7-2c6e-43a5-a120-a08b3d6faf63.mp4


Thank You!

**Comment by PrestaEdit** [comment]
Because it's a native module, with ps_ as name. There is an exception. It's why there is a module as example, too.

**Comment by Prestaworks** [comment]
> Hello everybody,
> 
> As seen with @khouloudbelguith, we checked this issue with a native module (eg. `ps_emailsubscription`) with **8.0.0RC build1 without PR** having an underscore in its name. We did not reproduce the issue using this native module. The translation is well updated with French language.
> 
> This is a screen-record :
> Translation.OK.with.8.0.Rc.with.a.native.module.with._.mp4

I think there is a exception specificly for ps_ modules. I remember som discussion about this on slack.

**Comment by HanaRebaiQA** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/30080
