### ISSUE TITLE
New password policy fix causes core.js to be gigantic

### ISSUE THREAD

**Issue by dennispw** [PrestaShop/PrestaShop#30088]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

With the new password policy (which is a good thing) using the [zxcvbn](https://github.com/dropbox/zxcvbn) library, I recently noticed that the final `core.js` filesize when from `~45kb` to `~443kb`, which is almost 10 times larger than before.

**Update:** I was looking in the network tab. Looking at the _actual_ filesize it goes from `~138kb` to `~936kb`. Still almost 7 times larger.

A big part of it seems to be the **gigantic** list of normal (I guess "bad"?) passwords. See attached screen recording:

https://www.loom.com/share/70d0b00132b0424b8ebf2b241eb14401

It seems to have been added in this [PR](https://github.com/PrestaShop/PrestaShop/pull/28127).

### Expected behavior

This is not really my area of expertise but I'm guessing the proper way would to compare the wanted/entered password, against this list with AJAX in order so save filesize and possibly script execution time.

### Steps to reproduce

1. Compare `core.js` filesize between 1.7.x and latest 8.0.0 beta

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by Hlavtox** [comment]
It's 940 kB in the final version. 🤯
In 1.7.6, it's 110 kB...

zxcvbn library = 804 kB

**Comment by NeOMakinG** [comment]
This is a real issue

@Hlavtox wdyt of improving it by async loading zxcvbn only on specific pages using it? `zxcvbn` doesn't provide any way to load the pw catalog on use by querying it or whatever

**Comment by Hlavtox** [comment]
We should just pass it to the core by ajax, to a single password validator. One source of truth. No need to pass any config to FO, no need to load this library.

**Comment by matks** [comment]
About this issue here is this thread https://github.com/dropbox/zxcvbn/issues/169 that contains multiple solutions

**Comment by Hlavtox** [comment]
Even if it was 100 kB, it's too much.

**Comment by Hlavtox** [comment]
https://github.com/dropbox/zxcvbn readme:
```
But we recommend against bundling zxcvbn via tools like browserify and webpack, for three reasons:

- Minified and gzipped, zxcvbn is still several hundred kilobytes. (Significantly grows bundle size.)
- Most sites will only need zxcvbn on a few pages (registration, password reset).
- Most sites won't need zxcvbn() immediately upon page load; since zxcvbn() is typically called in response to user events like filling in a password, there's ample time to fetch zxcvbn.js after initial html/css/js loads and renders.

```

**Comment by Oksydan** [comment]
@NeOMakinG @matks assign me to this task.
What branch should we target?
That core.js size ATM for me is unacceptable.
I am not going to run store on prestashop 8.0 w/o modifying core.js 😕

**Comment by kpodemski** [comment]
@Oksydan I've just assigned you

no one discussed severity of it yet, If you can come up with something I think you could target RC branch, so the project could have it in the final version

**Comment by NeOMakinG** [comment]
> Handling asynchronous prestashop.checkPasswordScore PrestaShop/classic-theme#67

@kpodemski about the severity, remember that that file will be loaded inside `every` theme as it's a forced dependency, it would cause the whole ecosystem to load a file almost 1mb larger than the previous one, this is pretty huge and could block users to adopt the 8.0

**Comment by kpodemski** [comment]
@NeOMakinG, you don't need to convince me, believe me, 👍 I know it's a major issue

**Comment by khouloudbelguith** [comment]
Hello,

I checked the core.js with PS1787
![image](https://user-images.githubusercontent.com/16067358/197750582-33661dcf-4cf6-4e6b-ad57-68f09f1be3de.png)
I checked the core.js file with 8.0.0RC1
![image](https://user-images.githubusercontent.com/16067358/197750771-29f7b709-f399-4655-b7e0-b84806585ce4.png)

Thanks!
