### ISSUE TITLE
Make prestashop compatible with php 8.x

### ISSUE THREAD

**Issue by realtebo** [PrestaShop/PrestaShop#30089]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Yes, of course.

All our new servers are been created with PHP 8.1. 

We cannot install prestashop.

Installer is saying  

"You need at most PHP 7.4 to install PrestaShop. Your current PHP version is 8.1.2"

### Describe the solution you'd like

Make prestashop compatible with php 8.x

### Alternatives you've considered

Using another shop is not a solution for us

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by Hlavtox** [comment]
Hi, new version of Prestashop (v8) is getting released in following days. It supports both PHP 8 and PHP 8.1

**Comment by realtebo** [comment]
WOW Thanks.

Are there any documentation about migration for developers, because we have ... ehm ... a TON of plugin to make compatible with new version?

**Comment by Hlavtox** [comment]
Step 1 - follow this page - https://build.prestashop-project.org/ :-)

All information should be here:
- https://build.prestashop-project.org/news/migrate-your-solutions-from-17-to-80/
- https://devdocs.prestashop-project.org/8/modules/core-updates/8.0/

Maybe the list is long, but I think that most of your modules should work just fine. The upgrade work from 1.7.8 to 8 is the same as from 1.7.7 to 1.7.8. 👍

**Comment by hibatallahAouadni** [comment]
Thanks @Hlavtox for your quick replies :superhero: :pray:
