### ISSUE TITLE
cache problem -not valideted orders

### ISSUE THREAD

**Issue by adamus007p** [PrestaShop/PrestaShop#30094]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,
I have noticed that when I was testing with Paypal that when the cache is on payments are not validated. This can be see in logs.
I was testing with Paypal sandbox.

The same is with Stripe.

I tested with:
CacheMemcached
CacheApc

### Steps to reproduce

Turn on cache:
CacheApc
CacheMemcached

make order e.g with Paypal sandbox

In BackOffice > Logs you will see that orders are not validated.

When you turn off the cache everything is ok.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

CentOS Version: 7.9
Centmin Mod: 124.00stable.s53
Nginx Version: 1.21.6 (031022-221318-centos7-kvm-f6624e7-br-6e975bc)
PHP-FPM Version: 7.4.32
Prestashop 1.7.8.8

**Comment by hibatallahAouadni** [comment]
Hello @adamus007p 


It seems that your issue is not a PrestaShop core bug.
If your module is PayPal Official, please contact support team on Addons

We will close this issue.

Thanks!

**Comment by adamus007p** [comment]
@hibatallahAouadni as I was checking caching it is related to Prestashop.

Two different payment modules can not be wrong ;)

Please do not close this issue.

**Comment by adamus007p** [comment]
@hibatallahAouadni I did not mentioned the problem is with free order too. So it is not related to only paymement modules.
When cache from memcached is off everything is ok.

I see that there is a spagetti code regards cache and payments.

**Comment by hibatallahAouadni** [comment]
Hello @adamus007p 

Could you please provide clear and concise steps to reproduce the issue and a screen record :pray: 
If I reproduce it I will reopen the issue :wink: 
Waiting for your feedback.

Thanks!
