### ISSUE TITLE
Fresh install branch 1.7.8.x is not working (with docker)

### ISSUE THREAD

**Issue by sefirosweb** [PrestaShop/PrestaShop#30098]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you clone the branch 1.7.8.x and make a build of docker compose and try run it, when starts the installation, show an error the php version is not supported,

![Screenshot_19](https://user-images.githubusercontent.com/20754836/197390529-54f85e89-9b85-44e7-bc40-033d60230e9f.png)

I tried to fix them, modifiend the docker-compose & dockerfile, because now is using "latest" version for default:

https://github.com/PrestaShop/PrestaShop/blob/e9623cf29dc058da74ade396dd32fb6e8b09f03a/.docker/Dockerfile#L1

I changed to use docker-compose variables, similar has branch 8.0:

docker-compose.yml
```docker-compose.yml
  prestashop-git:
    build:
      dockerfile: .docker/Dockerfile
      context: .
      args:
        - VERSION=${VERSION:-7.4}
...
```
Dockerfile
```Dockerfile
ARG VERSION

FROM prestashop/prestashop-git:$VERSION

# To run files with the same group as your primary user
RUN groupmod -g 1000 www-data \
  && usermod -u 1000 -g 1000 www-data

COPY .docker/wait-for-it.sh /tmp/
COPY .docker/docker_run_git.sh /tmp/
...
```

With that the full installation works fine, but after that if you try to open backend or frontend all styles are broken,

![image](https://user-images.githubusercontent.com/20754836/197390623-5e88c0fc-64f0-41dc-bfe0-df663819d129.png)

When you enable debug for see errors, they throw this error:

![image](https://user-images.githubusercontent.com/20754836/197390648-02857997-e2a4-493d-b015-308ba847ce45.png)

I tried with php 7.1 / 7.2 / 7.3 / 7.4 all same

### Steps to reproduce

1º Clone branch 1.7.8.x
git clone --branch 1.7.8.x https://github.com/PrestaShop/PrestaShop.git

2º Build docker
docker-compose pull
docker-compose build --no-cache

3º Start Docker
docker-compose up -d

4º Go installation menu
http://localhost:8001/install-dev/

For fix installation glone my branch:
git clone --branch 1.7.8.x git@github.com:sefirosweb/PrestaShop.git

Or fix them manually:

https://github.com/PrestaShop/PrestaShop/commit/ca497115ec7b178374001d384673534db467b840

### PrestaShop version(s) where the bug happened

1.7.8.x

### PHP version(s) where the bug happened

7.4 / 8.0

**Comment by PrestaEdit** [comment]
Hi,

You missed the make assets part (https://devdocs.prestashop-project.org/1.7/basics/installation/localhost/#javascript-and-css-dependencies).

**Comment by sefirosweb** [comment]
Hi,

This step must be done it alone (that's the idea for using docker), 
Seem this branch have a multiple bugs,

![image](https://user-images.githubusercontent.com/20754836/197394656-e7ac2d77-1fec-4edd-9824-aa98ffb7176f.png)

I see that uses a deprecated version of node,
I try to update and let you know if it works well

![image](https://user-images.githubusercontent.com/20754836/197394855-8a9a7a31-11a2-43a7-90b8-219e08777a9f.png)

**Comment by sefirosweb** [comment]
Solved updating node version to 14 works fine,

The docker automatically build the assets,

I will make a PR to update this branch, to fix these issues

**Comment by khouloudbelguith** [comment]
Hi @PrestaEdit,

I manage to reproduce the issue with 1.7.8.x branch
![image](https://user-images.githubusercontent.com/16067358/197841014-7458f18f-461f-4f09-a925-a253a7619c62.png)
![image](https://user-images.githubusercontent.com/16067358/197841047-10a47727-b6d5-43a2-ba07-bd4c76a47649.png)
I'll add this to the backlog.

Thanks for the PR.

**Comment by sefirosweb** [comment]
Fixed bug with PR,

Closed topic

 Thanks all!
