### ISSUE TITLE
BO - An exception is displayed in all migrated page after deleting the employee language

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#30091]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > All migrated pages, An exception is displayed after deleting the employee's language.
I reproduce the same issue with @HanaRebaiQA & @MhiriFaten 

### Expected behavior

All pages are well displayed without exception.
In case of deletion of the language of an employee, this employee's language fallback to the default language of the shop. i.e : French is set as employee language and English is the default shop language, if we delete French from the shop, English is selected for the employee.

### Steps to reproduce

1. Install 8.0.0 with multilanguage (eg. English: default language & French)
2. Go to BO > Advanced Parameters > Team > Employees page
3. Create an employee with the French language
4. Go to BO > International > Languages page
5. Delete the French language
6. Try to Sign in with the new employee created
7. Try to visit any migrated page
8. See exception

![image](https://user-images.githubusercontent.com/16067358/197230833-d908474b-771f-45b1-bbeb-e2aadd9b9051.png)

### PrestaShop version(s) where the bug happened

8.0.0-rc1, 8.0.0-rc branch
It is ok with PS1.7.8.7, PS1.7.7.8

### PHP version(s) where the bug happened

7.2

**Comment by mflasquin** [comment]
Closed by https://github.com/PrestaShop/PrestaShop/pull/30745
