### ISSUE TITLE
Modules page default button changed on 8.0

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#30101]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If module is not configurable, the default module action changed from "Disable" to "Disable on mobile" on 8.0.
There was an attempt to fix it here - https://github.com/PrestaShop/PrestaShop/pull/28332 (issue https://github.com/PrestaShop/PrestaShop/issues/28331), but it wasn't fixed properly.

**1.7.6.9**
![1769](https://user-images.githubusercontent.com/6097524/197405983-391dfb2b-8a3b-4b31-8747-0ba445646e4f.jpg)

**8.0 RC**
![RC](https://user-images.githubusercontent.com/6097524/197405992-9adf2dea-6c43-47c1-b1ca-cbee74d44fe0.jpg)

### Expected behavior

Default action for non configurable, non upgradable module should be **Disable**.

### Steps to reproduce

1. Install 1.7.6 or 1.7.7 or 1.7.8 branch.
2. Install 8.0 RC.
3. Open Module manager and see that there is a different default module action.

### PrestaShop version(s) where the bug happened

8.0

### PHP version(s) where the bug happened

8.0

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

I think it's related to this issue #28331
Could you please check it 🙏 
Waiting for your feedback.

Thanks!

**Comment by Hlavtox** [comment]
@hibatallahAouadni Yes, but it was not fixed by this PR - https://github.com/PrestaShop/PrestaShop/pull/28332.

Primary action for Non-configurable, installed module was `Disable`, now it is `Disable on mobile`.

**Comment by florine2623** [comment]
Hello @Hlavtox ,

I think you are right.

I would like to get approval from PM before puttin the label Verified ^^

It seems like the order has been defined here:
https://github.com/PrestaShop/PrestaShop/pull/28332#issuecomment-1113089728

@PrestaShop/product-team , could you confirm the wanted order of the dropdown button ?

Thanks

**Comment by Hlavtox** [comment]
Ping @MatShir

**Comment by fabienvallon** [comment]
LGTM

**Comment by Hlavtox** [comment]
Thanks @fabienvallon, I go make a PR! 🎉
