### ISSUE TITLE
Fatal error after upgrade to 8.0 RC

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#30100]
After upgrading to 8.0 from 1.7.6 or 1.7.7, fatal error is shown when accessing backoffice.

### Steps to reproduce

1. Install latest 1.7.6 or 1.7.7 release.
2. Get latest autoupgrade code from https://github.com/PrestaShop/autoupgrade, run composer install. Install the module. Or use this: [autoupgrade.zip](https://github.com/PrestaShop/PrestaShop/files/9850726/autoupgrade.zip)
3. Download https://github.com/PrestaShop/PrestaShop/releases/tag/8.0.0-rc.1 ZIP and XML, put it to admin/autoupgrade/download.
4. Open autoupgrade, upgrade from local archive to 8.0 RC.
5. Upgrade is successful, try to access backoffice, see fatal error. Shop is completely unusable until manually removing ps_mbo from database and from modules folder.

![error upgrade](https://user-images.githubusercontent.com/6097524/197405830-a0770531-10ee-429f-9424-ffffcf357d69.jpg)

### PrestaShop version(s) where the bug happened

1.7.6 to 8.0 RC, 1.7.7 to 8.0 RC

### PHP version(s) where the bug happened

8.0

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Before upgrading, did you enable the option `Disable non-native modules`?
I think your issue is related to this one #29469
Please check and feedback.

Thanks!

**Comment by Hlavtox** [comment]
@hibatallahAouadni Not sure it's related. `ps_mbo` is just broken.

- When you upgrade with `Disable non-native modules` `On`, you get this fatal error immediately.
- When you upgrade with `Disable non-native modules` `Off`, you don't have module catalog, so you want to have it back. So you enable `ps_mbo` - you get this fatal error anyway.

**Comment by eternoendless** [comment]
`ps_mbo` needs to be upgraded to v4 to work with PrestaShop 8. You can find the newer version [here](https://github.com/PrestaShopCorp/ps_mbo/releases). However, to the best of my knowledge v4 is not compatible with 1.7.8 so it might be kind of tricky to upgrade it.

@intraordinaire @sowbiba perhaps you can provide some insights here?

**Comment by sowbiba** [comment]
Hello. With PS v8.0 you can only have ps_mbo v4.0+

**Comment by sowbiba** [comment]
You're absolutely right @eternoendless ps_mbo v4 is compatible with PS 8.0
You'll have to manually download the release and upgrade it through the module manager page

**Comment by AureRita** [comment]
Hi @Hlavtox  ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thanks

**Comment by Hlavtox** [comment]
@AureRita @hibatallahAouadni is this fixed? There was no question to me

**Comment by intraordinaire** [comment]
No, it's still not fixed.
We are exploring multiple paths to solve this.
It will be fixed soon.

But the problem is indeed in the module `ps_mbo`, not in PrestaShop itself.

**Comment by Hlavtox** [comment]
@intraordinaire Why is the issue closed for “inactivity” then?

I know the issue is in the module, but the module breaks the shop and there is no way around it. 🤷

**Comment by intraordinaire** [comment]
Yeah I understand your point of view.

We just tested with `autoupgrade`, and it should be fixed now, as we published a new version of the `ps_mbo` module.
It's just that, when you tested it, the module was not released yet.
