### ISSUE TITLE
Form contact + AdminCustomerThreads With and Without order reference

### ISSUE THREAD

**Issue by AlexandreBEUDET** [PrestaShop/PrestaShop#30109]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

From the contact form,

- If an order reference is selected, the message is visible in the SAV module, the email address of the service receives the email in its box.

- If there is no order reference selected, the message is not visible in SAV, but the service address does receive the email in its box.

### Expected behavior

According to the Prestashop notice, all messages must be in the after-sales service module.

### Steps to reproduce

I.
   1. Go to the contact form
   2. Select a past order reference.
   3. Write the message and validate.
   4. The message **is in** the after-sales service module, the copy of the email is sent to the customer and the department concerned receives an email with the question.

II.
   1. Go to the contact form
   2. Select a past order reference.
   3. Write the message and validate.
   4. The message **is not** in the after-sales service module, the copy of the email is sent to the customer and the department concerned receives an email with the question.

### PrestaShop version(s) where the bug happened

1.7.8.5

**Comment by hibatallahAouadni** [comment]
Hello @AlexandreBEUDET 

You just to click on View button to see all messages received from the client, see the attached screen record below:

[issue_30109.webm](https://user-images.githubusercontent.com/23308427/198289988-e23f833c-3608-4949-86b0-3f461a3ed1a1.webm)

Closing the issue as there's no issue.

Thanks!
