### ISSUE TITLE
Can't install beta prestashop 8.0 RC1

### ISSUE THREAD

**Issue by tajriba** [PrestaShop/PrestaShop#30103]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Can't install on apache, php 8.0 from the install wizard.
Language: dutch. 

When creating the database tables this error appears:

<img width="463" alt="Schermafbeelding 2022-10-23 om 20 16 12" src="https://user-images.githubusercontent.com/68469531/197408885-caf57605-0ae7-413c-9235-7c0e370c3b1e.png">
<img width="486" alt="Schermafbeelding 2022-10-23 om 20 16 20" src="https://user-images.githubusercontent.com/68469531/197408886-0dfaad35-b8ee-4103-bd52-ef8342653f57.png">

### Expected behavior

Completed install of fresh 8.0

### Steps to reproduce

1. Download the RC1 prestashop 8 zip
2. Unpack it
3. Upload the /prestashop/ folder files into " domain.com) public_html
4. Go to domain.com/install
5. Fill in the steps and country Netherlands.
6. Connect with database. localhost. 
7. Error appears

### PrestaShop version(s) where the bug happened

8.0 RC1

### PHP version(s) where the bug happened

8.0

<img width="1136" alt="error" src="https://user-images.githubusercontent.com/68469531/197593439-ab8ef990-236d-4eee-b140-4c25aeef367e.png">

**Comment by kpodemski** [comment]
Hello @tajriba 

There's no error screenshot in your issue.

**Comment by tajriba** [comment]
@kpodemski error attachment added now

**Comment by kpodemski** [comment]
@tajriba could you check if you have any installations logs inside `/var/logs/`?

**Comment by tajriba** [comment]
No there are no logs.

**Comment by hibatallahAouadni** [comment]
Hello @tajriba 

I didn't manage to reproduce the issue with the provided info.
Did you check your connection? Cause sometimes it happens when your connection is slow.
Please check and feedback.

Thanks!

**Comment by eternoendless** [comment]
@tajriba consider [setting up the shop in dev mode](https://devdocs.prestashop-project.org/8/basics/installation/configuration/#displaying-error-messages), you might get more information about the error.

**Comment by tajriba** [comment]
@eternoendless @hibatallahAouadni I enabled dev mode, and this is the information:
<img width="691" alt="Schermafbeelding 2022-10-26 om 21 32 14" src="https://user-images.githubusercontent.com/68469531/198121121-b733d09f-e34f-42c3-a062-283164a7aee4.png">
<img width="1030" alt="Schermafbeelding 2022-10-26 om 21 40 45" src="https://user-images.githubusercontent.com/68469531/198121132-42e2165d-99ff-4d0b-9f45-097b05a04082.png">

**Comment by nicosomb** [comment]
Hello @tajriba. 

Maybe you have permissions issue on your folders. Could you have a look in the documentation https://devdocs.prestashop-project.org/8/basics/installation/localhost/#setting-up-file-rights ?

**Comment by tajriba** [comment]
@nicosomb thanks for your tip.
Folder Rights for var folder are: 775.

The errors with the installation, is about dev folder inside: var/cache/dev
Creates during install wizard this files without permissions at all:
dev/class_index.php
dev/class_stub.php

In 1.7.X we never had this?

Afterall, after the /install wizard creates this files without permissions, i changed permissions and the install is working.

**Comment by kpodemski** [comment]
> Afterall, after the /install wizard creates this files without permissions

I believe this part is worth checking.

**Comment by florine2623** [comment]
@PrestaShop/prestashop-maintainers

Can someone check this part?

>Afterall, after the /install wizard creates this files without permissions

Thanks!

**Comment by tajriba** [comment]
this issue is still there? @PrestaShop/prestashop-maintainers

**Comment by matks** [comment]
@tajriba PrestaShop 8.0.0 is now released and, as far as my knowledge goes, we have not encountered any issue similar to what you reported :/ . Moreover probably hundred maybe thousand shops have now been created with PS 8.0.0 and nobody reported a problem similar to yours.

I am sorry but it looks like only you encounter this problem 😞 

I think we can close the issue as 8.0.0 is released https://build.prestashop-project.org/news/2022/prestashop-8-0-0-available/

**Comment by tajriba** [comment]
Ok. We will test it with prestashop 8 final version again.

**Comment by tajriba** [comment]
@matks we have the same issue with 8.0.1 install wizard.
file permission errors as mentioned above 
_Originally posted by @tajriba in https://github.com/PrestaShop/PrestaShop/issues/30103#issuecomment-1294921236_

`
Fatal error: Uncaught Error: Failed opening required '/home/tajribadev/domains/domain.dev/public_html/user/var/cache/dev/appParameters.php' (include_path='/home/tajribadev/domains/domain.dev/public_html/user/vendor/pear/pear_exception:/home/tajribadev/domains/domain.dev/public_html/user/vendor/pear/console_getopt:/home/tajribadev/domains/domain.dev/public_html/user/vendor/pear/pear-core-minimal/src:/home/tajribadev/domains/domain.dev/public_html/user/vendor/pear/archive_tar:.:/usr/local/php80/lib/php') in /home/tajribadev/domains/domain.dev/public_html/user/config/bootstrap.php:87
Stack trace:
#0 /home/tajribadev/domains/domain.dev/public_html/user/install/init.php(93): require_once()
#1 /home/tajribadev/domains/domain.dev/public_html/user/install/index.php(43): require_once('...')
#2 {main}
thrown in /home/tajribadev/domains/domain.dev/public_html/user/config/bootstrap.php on line 87`

**Comment by tajriba** [comment]
Found it. Opcache. 

This issue is related to this: 
https://github.com/PrestaShop/PrestaShop/issues/10998#issuecomment-476361695

I don't know why the original issue is closed, because there is still no solution for this.
Since 2018
@matks @kpodemski #10998

So I suggest to reopen the original issue?

**Comment by matks** [comment]
Issue was closed because someone shared a [solution](https://github.com/PrestaShop/PrestaShop/issues/10998#issuecomment-431596422) using opcache configuration.

As mentioned [there](https://github.com/PrestaShop/PrestaShop/issues/10998#issuecomment-431767863) feel free to open a new issue if needed. Reopening old issues is not useful for bug tracking.
