### ISSUE TITLE
Database structure difference between clean and upgrade to 8.0 RC

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#30102]
## Describe the bug and add screenshots

Database structure is different between clean install of 8.0 RC and upgrade from 1.7.6.9 to 8.0 RC.

### Extra tables
On upgraded install, there are extra unused tables `ps_order_slip_detail_tax` and `ps_attribute_impact`.

### Different column types, charsets, default values etc.
On upgraded install, there are many differences between the two databases.
![difference](https://user-images.githubusercontent.com/6097524/197406948-77c31710-1442-470b-b0ab-284173dff4cc.jpg)

For a full list, compare these two file's content in https://www.diffchecker.com/.
[clean.txt](https://github.com/PrestaShop/PrestaShop/files/9847145/clean.txt)
[upgrade.txt](https://github.com/PrestaShop/PrestaShop/files/9847146/upgrade.txt)

## Expected behavior

Database structure should be absolutely the same.

## Steps to reproduce

1. Install 1.7.6.9, upgrade it to 8.0 RC by latest autoupgrade code.
2. Install clean 8.0 RC.
3. Export database structure in PHPMYADMIN or ADMINER.
4. Compare them by any tool, for example https://www.diffchecker.com

## PrestaShop version(s) where the bug happened

8.0

## PHP version(s) where the bug happened

8.0

**Comment by BenTen** [comment]
For `ps_order_slip_detail_tax` it's normal
https://github.com/PrestaShop/PrestaShop/pull/24118

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thanks for reporting the issue :pray: 
Ping @PrestaShop/prestashop-core-developers someone please try to reproduce the issue, it's too technical!

PS: @BenTen thanks for your quick reply :rocket: 

Thanks!

**Comment by Hlavtox** [comment]
@BenTen Yes, of course, but the table should be removed on upgrade I think, no? Module developers can't count on it being there anway, because some installs would have it, some not.

**Comment by BenTen** [comment]
No because this table exist so maybe someone use it.
That's why the table is not remove from upgrade.

**Comment by hibatallahAouadni** [comment]
@Hlavtox why did you close the issue? Could you please explain :pray:

**Comment by Hlavtox** [comment]
@hibatallahAouadni I created an issue with much more depth and then I remembered I had this old one. :-)

The new one is better and already fixed some of the issues.

**Comment by hibatallahAouadni** [comment]
Duplicate of #33483
