### ISSUE TITLE
Email delivery / PS_SHOP_EMAIL / Not working

### ISSUE THREAD

**Issue by Mecanik** [PrestaShop/PrestaShop#30117]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This is the first time I installed Prestashop via Softaculous on cPanel.

There is no way to make the SMTP work, and I have tested several providers from SendGrid, to more.

Basically, there is a chaos with PS_SHOP_EMAIL. When you try to setup SMTP, you enter your details and click test... The code will try to send the test email using PS_SHOP_EMAIL to both FROM and TO, which is crazy. I had to dive into the code to find out the exact problem and after several testing this is confirmed.

**/src/Adapter/Email/EmailConfigurationTester.php:testConfiguration()**

        _$result = Mail::sendMailTest(
            Tools::htmlentitiesUTF8($smtpChecked),
            Tools::htmlentitiesUTF8($config['smtp_server']),
            Tools::htmlentitiesUTF8($content),
            Tools::htmlentitiesUTF8($subject),
            Tools::htmlentitiesUTF8('text/html'),
            Tools::htmlentitiesUTF8($config['send_email_to']),
            Tools::htmlentitiesUTF8($this->configuration->get('PS_SHOP_EMAIL')),
            Tools::htmlentitiesUTF8($config['smtp_username']),
            $password,
            Tools::htmlentitiesUTF8($config['smtp_port']),
            Tools::htmlentitiesUTF8($config['smtp_encryption'])_

The value of PS_SHOP_EMAIL is set by the input on Test your email configuration ->  Send a test email to, at the same time used as FROM, which will never work (sending an email to yourself!?)

### Expected behavior

Be able to change the FROM email when using SMTP.

### Steps to reproduce

1. Go to Advanced Parameters
 -> Emails
2. Enter SMTP configuration
3. Try to test sending emails

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @Mecanik 

I didn't manage to reproduce the issue with the provided infos. Could you please provide a screen record :pray: 
Waiting for your feedback.

Thanks!

**Comment by AureRita** [comment]
Hi @Mecanik  ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thanks

**Comment by LucasATodoColor** [comment]
I have the same problem, when trying to send an email test it does nothing
Could you help me?

![Sin título](https://user-images.githubusercontent.com/125739724/221200524-40c59741-a5fc-467e-b16a-aa9d0682b9f0.jpg)



Exceptions
Attempted to load class "Mail" from namespace "PrestaShop\PrestaShop\Adapter\Entity".
Did you forget a "use" statement for another namespace?

ExceptionStack Trace
Symfony\Component\Debug\Exception\
ClassNotFoundException
in [src/Adapter/Email/EmailConfigurationTester.php](https://atodocolor.com.ar/test/adminatodocolor/index.php/_profiler/open?_token=UxB4B-Dq-YygkUHsvEMNsNBW0IaxSncTFmwNL7dnuY8?file=src/Adapter/Email/EmailConfigurationTester.php&line=88#line88) (line 88)
            ['&lt;', '&gt;', '&quot;', '&amp;'],            ['<', '>', '"', '&'],            Tools::htmlentitiesUTF8($password)        );        $result = Mail::sendMailTest(            Tools::htmlentitiesUTF8($smtpChecked),            Tools::htmlentitiesUTF8($config['smtp_server']),            Tools::htmlentitiesUTF8($content),            Tools::htmlentitiesUTF8($subject),            Tools::htmlentitiesUTF8('text/html'),
EmailConfigurationTester->testConfiguration(array('send_email_to' => 'lu14t@hotmail.com', 'mail_method' => '2', 'smtp_server' => 'vps-2196686-x.dattaweb.com', 'smtp_username' => 'informacion@atodocolor.com.ar', 'smtp_password' => null, 'smtp_port' => '465', 'smtp_encryption' => 'ssl'))
in [src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmailController.php](https://atodocolor.com.ar/test/adminatodocolor/index.php/_profiler/open?_token=UxB4B-Dq-YygkUHsvEMNsNBW0IaxSncTFmwNL7dnuY8?file=src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmailController.php&line=261#line261) (line 261)
EmailController->sendTestAction(object(Request))
in [vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php](https://atodocolor.com.ar/test/adminatodocolor/index.php/_profiler/open?_token=UxB4B-Dq-YygkUHsvEMNsNBW0IaxSncTFmwNL7dnuY8?file=vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php&line=151#line151) (line 151)
HttpKernel->handleRaw(object(Request), 1)
in [vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php](https://atodocolor.com.ar/test/adminatodocolor/index.php/_profiler/open?_token=UxB4B-Dq-YygkUHsvEMNsNBW0IaxSncTFmwNL7dnuY8?file=vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php&line=68#line68) (line 68)
HttpKernel->handle(object(Request), 1, false)
in [vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php](https://atodocolor.com.ar/test/adminatodocolor/index.php/_profiler/open?_token=UxB4B-Dq-YygkUHsvEMNsNBW0IaxSncTFmwNL7dnuY8?file=vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php&line=200#line200) (line 200)
Kernel->handle(object(Request), 1, false)
in [adminatodocolor/index.php](https://atodocolor.com.ar/test/adminatodocolor/index.php/_profiler/open?_token=UxB4B-Dq-YygkUHsvEMNsNBW0IaxSncTFmwNL7dnuY8?file=adminatodocolor/index.php&line=82#line82) (line 82)

**Comment by Mecanik** [comment]
After all this time, the problem persists...

```
Error: Please check your configuration

Expected response code 250 but got code "550", with message "550 The from address does not match a verified Sender Identity. Mail cannot be sent until this error is resolved. Visit https://sendgrid.com/docs/for-developers/sending-email/sender-identity/ to see the Sender Identity requirements "
```

Seriously guys?

**Comment by topfuel75** [comment]
I had the same issue. I noticed that EmailConfigurationTester.php tried to use the password for the BO, and not the PS_MAIL_PASSWD.
When I changed from
`$password` to `$this->configuration->get('PS_MAIL_PASSWD')` it worked.

So in **_/src/Adapter/Email/EmailConfigurationTester.php_** I changed to this:
```
        $result = Mail::sendMailTest(
            Tools::htmlentitiesUTF8($smtpChecked),
            Tools::htmlentitiesUTF8($config['smtp_server']),
            Tools::htmlentitiesDecodeUTF8($content),
            Tools::htmlentitiesDecodeUTF8($subject),
            Tools::htmlentitiesUTF8('text/html'),
            (string) $config['send_email_to'],
            (string) $this->configuration->get('PS_SHOP_EMAIL'),
            Tools::htmlentitiesUTF8($config['smtp_username']),
            // $password,
            $this->configuration->get('PS_MAIL_PASSWD'),
            Tools::htmlentitiesUTF8($config['smtp_port']),
            Tools::htmlentitiesUTF8($config['smtp_encryption'])
        );
```
