### ISSUE TITLE
Handle categories data for multishop

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#30119]
**US**:
As a merchant, I want to edit the product's categories in multistore while editing the product page

**Specs**:
- When the MultiShop is deactivated:

When pressing on 'add new categories' 
The modal displays the categories' tree without The 'root' category 

- When the MultiShop is activated:
 
One shop can be linked to multiple root categories.

When pressing on 'add new categories' 
The modal displays all the categories' tree of the shops associated to the product. 

<img width="352" alt="Capture d’écran 2022-10-26 à 12 00 14" src="https://user-images.githubusercontent.com/43613217/197997304-f823fe9a-b82d-4c8e-8113-79fe9adf8f97.png">

The 'root' category is not displayed.

**Comment by zuk3975** [comment]
its abit confusing between root and home categories naming, but we discussed it in private.
Afterwards I've checked the current behavior and it seems to work as expected in develop branch.
When multishop is on, I created additional home ("home2") category (through "add new root category" button at the top of the page).
When I open modal I see both of those categories - home and home2 and the root category is not visible (as expected).
<img width="373" alt="Screenshot 2023-01-03 at 14 26 41" src="https://user-images.githubusercontent.com/31609858/210364365-e127423c-5af0-4a87-bb02-5a865e20007e.png">
