### ISSUE TITLE
Carriers new ui in the product page v2

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#30121]
**US:**
As a merchant, I want to manage my carriers easily 
The old ui was not intuitive, none of the carrier has to be selected if you want all your carriers to be used for this product

**Specs:**

By default, 'all carriers' is selected.
When a carrier is selected in the drop list then the carriers are displayed below the drop list as a label.
Only the carriers selected can use to deliver the product.
 

![Image](https://user-images.githubusercontent.com/43613217/215540741-e7c6ded4-aab7-463c-8f25-d6b1d3abe092.png)

If all the carriers are unselected, then All carriers is selected in the drop list

**Comment by jolelievre** [comment]
Closed by https://github.com/PrestaShop/PrestaShop/pull/30769
