### ISSUE TITLE
Handle specific price data for multishop

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#30120]
**US**:
As a merchant, I want to manage the specific price in multistore while editing the product page

**Specs**:
- When the MultiShop is deactivated:

When pressing on 'add new/edit specific price' 
The drop list 'shop' is hidden in the modal

- When the MultiShop is activated:

When pressing on 'add new/edit specific price' 
The drop list 'shop' has current store context preselected in the drop list
The drop list only displays the current shop and all shop (hide the other shops)

The list of the specific price only displays the current shop and all shop.

**Comment by jolelievre** [comment]
Closed by https://github.com/PrestaShop/PrestaShop/pull/30557
