### ISSUE TITLE
Fax number phone and mail. But no VAT number or KvK number seen one shop info. !!

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#30136]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Fax number phone and mail. But no VAT number or KvK number seen one shop info. !! You can't edit it. code has to be made. 

### Describe the solution you'd like

Code edit display shops info. if filled in fax show shop info. Also extra Vat number and KVK number shop. Maby also whatsapp extra. 

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @Gruttershop 

Thanks for your issue. Unfortunately, there is not enough information provided to understand it and work on it.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
