### ISSUE TITLE
Bug saving Ecotax from combinations

### ISSUE THREAD

**Issue by borjagarciab** [PrestaShop/PrestaShop#30145]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you save a product without edit a product combination, the ecotax is wrong saved.
I've seen that do is not saving the decimals (example -> the value is 2.5€ , it will save 2€).

https://user-images.githubusercontent.com/57815173/198570012-e8b33dbf-9d5e-4b22-93db-5803fae65c82.mp4

### Expected behavior

Save the ecotax correctly

### Steps to reproduce

1. Save the ecotax you want.
2. Reload the product page
3. save the product without check any combination.

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.3.33

**Comment by florine2623** [comment]
Hello @borjagarciab ,

I can't reproduce your issue. Is there something else I'm missing ?

https://user-images.githubusercontent.com/16019289/198976920-6fe49cc9-6aae-4a2d-a4e9-439ecd272903.mov

The ecotax is always saved correctly.

Waiting for your feedback, thanks!

**Comment by borjagarciab** [comment]
Hi @florine2623 
I seen that you are testing in last 1.7 prestashop version.
I've test in both versions (1.7.8.3 and 1.7.8.7) 
For new versions it works correctly, but for older the bug exists.

Can you help me to find what code was updated about this to fix it? (if is possible)
Use one click upgrade for this website will be crazy...
Thanks.

**Comment by HanaRebaiQA** [comment]
Hello @borjagarciab 

Thanks for your feedback.
Since the issue is already fixed on the last PrestaShop version 1787, so, this issue should be closed.
I found this issue https://github.com/PrestaShop/PrestaShop/issues/25897 which is similar to yours and was fixed. It maybe can help you.

So, i'll close this issue.

**Comment by HanaRebaiQA** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/25897
