### ISSUE TITLE
Prestashop 8 (Backoffice error 500 accessing Category in Monitoring tab)

### ISSUE THREAD

**Issue by markoopapa** [PrestaShop/PrestaShop#30144]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Prestashop 8 (Backoffice error 500 accesing Category an Monitoring tab)

Prestashop 8 fresh install (tryed clear cache, disable modules)
![Screenshot 2022-10-28 094838](https://user-images.githubusercontent.com/20978213/198562971-02ff384b-6758-4168-a963-4c068c53bab2.jpg)
![Screenshot 2022-10-28 095346](https://user-images.githubusercontent.com/20978213/198562987-783cf2a5-4aa0-45f8-a73f-3cbbca32926f.jpg)

### Steps to reproduce

1. login Back Ofiice
2. Click on Categories = error
3. Click on Monitoring = error

### PrestaShop version(s) where the bug happened

1.8.0.0

### PHP version(s) where the bug happened

8.1

**Comment by nicosomb** [comment]
I can reproduce the issue on the monitoring screen, not on Category one.

**Comment by hibatallahAouadni** [comment]
Hello @markoopapa 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. 

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by markoopapa** [comment]
What more you need about itt? 3xplain plz

**Comment by kpodemski** [comment]
@markoopapa 

I couldn't reproduce your issue. Could you tell us if you did something after the installation? Did you delete any products, or categories? There's no error right after the installation.

If you didn't do anything, let us know about your environment in detail. Is it apache? Nginx? MySQL 5, 8? MariaDB?, etc.

**Comment by markoopapa** [comment]
Database server
Server: Localhost via UNIX socket
Server type: MariaDB
Server connection: SSL is not being used Documentation
Server version: 10.3.36-MariaDB-cll-lve - MariaDB Server
Protocol version: 10
User: minmagro@localhost
Server charset: cp1252 West European (latin1)

After fresh instal, i import from excel main category, after i import alt category, brands and at last produscts. 

After first import of main category's i delete all bec was wrong ids, and i reimport after delete.

**Comment by kpodemski** [comment]
@markoopapa 

In that case, I think the problem is coming from the import. As I expected, something went wrong during this process, and there are some integrity failures inside your database.

To reproduce this issue, we would need some examples of your CSV file.

**Comment by markoopapa** [comment]
@kpodemski  Nice...
I this case i atach all imported file in a zip and a photo where you can see the exact order of imports. all this data is from website admin folder. 
Products was imported last but not with import from prestashop (was with module)

[imported.zip](https://github.com/PrestaShop/PrestaShop/files/9894175/imported.zip)
![Screenshot 2022-10-29 194653](https://user-images.githubusercontent.com/20978213/198843400-cd025d47-533d-446e-8720-948c35e2584b.jpg)

**Comment by markoopapa** [comment]
for you is important only the 27.10.22

The 941 kbs file when was first time imported i dont select to import by id and all categories was from 1,2,3,4.....28 ID. I delete all and reimport to mantain the ID from import.

**Comment by markoopapa** [comment]
@kpodemski If you can now reproduce and know any solution to solve the actual arror plz share with me. 

Thanks
