### ISSUE TITLE
BO - Responsive - Cross to close the menu on tablets/mobile screen is not well placed  (legacy pages only)

### ISSUE THREAD

**Issue by PrestaPierre** [PrestaShop/PrestaShop#30141]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I want to see on tablet/mobile legacy pages ONLY on the BO and click on the burger menu, the cross is not placed correctly

Shop v8

<img width="1433" alt="Capture d’écran 2022-10-28 à 10 38 42" src="https://user-images.githubusercontent.com/112935373/198546169-70d828a1-20f4-4316-9014-a6974a56c527.png">

Shop V1.7.8

<img width="1424" alt="Capture d’écran 2022-10-28 à 10 44 04" src="https://user-images.githubusercontent.com/112935373/198546220-a7cb3dfc-98de-4dbb-be4e-8f813b800e47.png">

No cross on 1.7.7.8 version. No regression

### Expected behavior

When I log in to my BO and want to see it on tablet/mobile screens (legacy pages only), I click on the burger menu, the cross should be located on the burger menu on the right

### Steps to reproduce

- Go to BO > Dashboard page for example (or Stats page)
- Open the debugger on your browser and put your shop on tablet/mobile screens
- Click on burger menu on the top left
- See error, the cross is outside the menu

### PrestaShop version(s) where the bug happened

v8, 1.7.8

### PHP version(s) where the bug happened

8.1.9 and 7.4.30

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/ux-team @NeOMakinG is the location of cross right or wrong? 
Thanks in advance!

**Comment by NeOMakinG** [comment]
If I remember right, the cross was always intended to be displayed outside of the menu, and it's just a visual tip for the user because he can click anywhere outside of the menu to close it

**Comment by hibatallahAouadni** [comment]
Thanks @NeOMakinG for your feedback :pray: 
Closing the issue as the cross should be displayed there :wink:
