### ISSUE TITLE
The dateTime of new customer last visit is not displayed

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#30155]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The dateTime of new customer  last visit is not visible in BO>customers table> last visit column

![Manage your Customers • PrestaShop](https://user-images.githubusercontent.com/24647495/198602031-4c81ebb2-22fa-41b7-a5c7-c728b09a3977.png)

### Expected behavior

The dateTime of the last visit should be visible

![Manage your Customers • PrestaShop (1)](https://user-images.githubusercontent.com/24647495/198602863-95d89cfa-88db-4c84-bf98-21b10d0baf64.png)

### Steps to reproduce

1. Go to FO > Sign in > No account? create one here
2. Create new account
3. Go to BO > Customers > Customers
4. See the error => the last visit date of the created customer is '---'

See the screen video
https://watch.screencastify.com/v/r2TcGRJl8kYQFTFo8kg9

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Regression on develop! Nice catch :clap:
