### ISSUE TITLE
Webservice is broken with PS 8.0 and PHP 8.1

### ISSUE THREAD

**Issue by Max84** [PrestaShop/PrestaShop#30165]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The webservice provides invalid XML  :  

![image](https://user-images.githubusercontent.com/6622400/198968530-ed351229-11ac-491d-ad41-366917eca500.png)

### Expected behavior

We always should get valid XML : 

![image](https://user-images.githubusercontent.com/6622400/198968981-e1908f41-09d7-4531-bbd0-c5832fc991b0.png)

### Steps to reproduce

Try theses step with : 

- php 7.3 : you won't reproduce this bug
- php 8.1 : you will reproduce this bug

1. Install Prestashop 8.0.0 with demo products
2. Enable webservice
3. Open with your browser this url https://YOURURL/api/combinations/3 (this bug happens with some other url, it's just for example)
![image](https://user-images.githubusercontent.com/6622400/198968487-750ed65f-088f-457e-90e4-613a81d5ad41.png)

4. Check XML, you see the bug. XML doesn't allow number as tag, and data are missing

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1

**Comment by HanaRebaiQA** [comment]
Hello @Max84 

Thanks for your report.
I have encountered an issue when adding new webservice key on PS8.0.0 with php 8.0 and php 8.1

https://user-images.githubusercontent.com/92912932/199540444-0a633353-44dd-44ed-947a-b9d9f2b0188f.mp4

I should more investigate on it and will give your my feedback!

Thank You!

**Comment by HanaRebaiQA** [comment]
Hello again,

I tried with 8.0.x and php 8.0, i was able to add a new key for the webservice but when i used the same provied url `https://yoururl/api/combinations/3`, i found this problem : 


https://user-images.githubusercontent.com/92912932/199544027-4a2be551-f32c-48ec-9306-c9f8f1de09a7.mp4


Could you please check again ?

Thanks !

**Comment by Max84** [comment]
Hello Hana,

Well, i don't reproduce the problem on generation key. I used Firefox without Prestashop debug enable. Maybe due to this?
About your second video, you've reproduced my reported bug.
You don't see exactly the same because your browser try to use XML. 
Please, just display source code of the last page, then, you'll see full XML and this reported bug.

Do you get it ?

Thanks.

**Comment by AureRita** [comment]
Hello @Max84 

I also use Firefox and I've got this result when I tried to reproduce your issue : 

[Untitled_ Nov 3, 2022 11_49 AM.webm](https://user-images.githubusercontent.com/100699445/199702503-d0e26e32-9de9-4ffb-9e30-0bb958786a72.webm)

Is it the same than your issue ? 

Waiting for your feedback

**Comment by Max84** [comment]
Hello @AureRita 
Your video file is corrupted. I can watch it.

**Comment by AureRita** [comment]
It seems that you maybe have some trouble with your connection, but no problem, there is a screen that show the errors that I get : 

![image](https://user-images.githubusercontent.com/100699445/199751801-733256c6-e37b-4ce7-a9a5-5d5ac5a26fab.png)

This error message only appears when i'm on php 8.0 or 8.1 
Is it the same than your issue ?

Waiting for your feedback

**Comment by Max84** [comment]
Right, it's the issue. You've reproduced it. 💪

**Comment by AureRita** [comment]
Thank you for all your details and your patience. 

Thank to all of your details, I reproduce the issue with PrestaShop version 8.0.0, It's a regression ! Nice catch ! 
 I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/31023 in 8.0.2
