### ISSUE TITLE
When AdminStats is not enabled, an exception is displayed on backoffice 

### ISSUE THREAD

**Issue by nicosomb** [PrestaShop/PrestaShop#30173]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On backoffice, if AdminStats module is not enabled (click on Modules / Modules manager / Administration section / uninstall "Stats Dashboard" module), the "Stats" link in the menu is still available. 

When we click on it, we have an error, here with PHP 8.1: 

<img width="1044" alt="Capture d’écran 2022-10-31 à 15 16 50" src="https://user-images.githubusercontent.com/121870/199031000-9eb41654-a3a6-487d-87af-bbff5b575f15.png">

Here with PHP 7.4: 

<img width="839" alt="Capture d’écran 2022-10-31 à 15 15 46" src="https://user-images.githubusercontent.com/121870/199031482-6dcd5f94-4cba-49cb-a464-3adeb242ba9f.png">

### Expected behavior

The "stats" item should be removed in the menu if the module is not available (not enabled or not installed)

### Steps to reproduce

1. On fresh install, without demo product and no module
2. Go to backoffice
3. Disable Stats dashboard module 
4. Click on Stats link in the menu (Sell section)

### PrestaShop version(s) where the bug happened

8.0.x, develop

### PHP version(s) where the bug happened

7.4, 8.0, 8.1

**Comment by florine2623** [comment]
Hello @nicosomb ,

Tested with PS 8.0.x and PHP 7.4. I can't reproduce your issue. I tested with disabling the module and uninstalling the module (delete module folder).

https://user-images.githubusercontent.com/16019289/199037261-8e7efc09-0fbd-4f44-b35d-8aafad57c96f.mov

Am I missing something ?
Thanks!

**Comment by nicosomb** [comment]
Could you try on a fresh install without installing demo product? I had this bug on a blank installation.

**Comment by nicosomb** [comment]
And no modules checked in the list from the installer.

**Comment by florine2623** [comment]
Thanks @nicosomb ,

I have reproduced your issue on 8.0.x, I'll add this to the backlog so it can be fixed. ^^

<img width="1438" alt="Screenshot 2022-10-31 at 17 01 29" src="https://user-images.githubusercontent.com/16019289/199053593-2b02d34c-a0ed-4335-b8e2-1a4a1a9d0dff.png">

Thank you
