### ISSUE TITLE
Multistore - It is possible to select a default language for a shop that does not belong to the shop

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#30171]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

1. It is possible to select a default language for a shop that does not belong to the shop.
When selecting the wrong language as default language, it is added to the languages for the shop.

2. On the other hand, it is possible to remove the default language from the shop. The default language setting is not affected.

### Expected behavior

1. It should not be possible to select a language as default language, that is not active in the current shop.

2. It should not be possible to remove the default language from a shop

### Steps to reproduce

Given an environment with more than one language and more than one shop.

Setup
----
1. Create a clean installation of PS 1.7.8.7 following [this step by step guide](https://gist.github.com/lmeyer1/c40a19d880758bee11a1e8a2c5e819c3)
2. Rename `Shop A` to `French shop`
3. In the BO, select `French shop` in the dropdown list
4. Go to _International - Localization - Languages_ 
5. On each language, click on _Edit_ , and make sure, that in shop association only French is associated with `French shop`. In the shop association for German `French shop` must not be checked (but at least one other shop must be checked).

Reproduce bug 1)
----
1. Open Front Office and notice the URL `http://localhost:8017/shop-a`
1. Go to _International - Localization - Localization_ 
2. Look at the option `Default language`. Notice, that we can change all active languages, even the one that does not belong to `French shop`.
3. Select German and click Save
6. Go to _International - Localization - Languages_ 
7. Click on Edit on German. Notice, that in shop association `French shop` is now selected
8. Navigate to the front office, and notice that the URL has changed to http://localhost:8017/shop-a/fr/. It now contains the language. We have inadvertently changed all the URLs. Good by SEO.

Reproduce bug 2)
Currently `French shop` has both languages `French` and `German`, and `German` is the default language.
1. Go to _International - Localization - Languages_ 
2. Click on Edit on `German`'s row. Deselect `French Shop` and save. (This should not be possible, since `German` is the default language).
3. In PHPMySQL look at the configuration `PS_LANG_DEFAULT` for `French Shop. You will find it still pointing to language 2 (German).
4. Go to _International - Localization - Localization_. Notice that `German` is still the default language.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @lmeyer1 

**For the bug 1)**, I have reproduced the issue only in BO
In my case, the language for my second shop should be FR instead of EN, is that right ?

https://user-images.githubusercontent.com/16019289/199033390-ff403003-4d81-4e9e-bba9-67528ba78a32.mov

In FO, the languages are the correct one for each shop.
ShopA: English
<img width="1200" alt="Screenshot 2022-10-31 at 15 36 23" src="https://user-images.githubusercontent.com/16019289/199033915-cb87bb9a-0c9c-422c-9691-4cd9a8163c43.png">

ShopB: French
<img width="1184" alt="Screenshot 2022-10-31 at 15 36 27" src="https://user-images.githubusercontent.com/16019289/199033863-e21e5b66-44ec-4c64-8bbd-8e8b292b882f.png">


**For the bug 2)**, I'm not sure I understand well what I'm supposed to do.
I've tried disabling the language, it is not possible:
<img width="1220" alt="Screenshot 2022-10-31 at 15 41 42" src="https://user-images.githubusercontent.com/16019289/199034949-23a2aeee-235b-4ce8-981a-d0bafa5c25d0.png">

I've tried to deselect the language for a specific shop and I have a warning:
<img width="841" alt="Screenshot 2022-10-31 at 15 40 07" src="https://user-images.githubusercontent.com/16019289/199034817-7d9db421-12c1-4c7c-8522-b4dbbf7b74f9.png">

Could you send a screen record of your case please ?

Waiting for your feedback!
Thanks!

**Comment by lmeyer1** [comment]
@florine2623 
>I've tried disabling the language, it is not possible:

This is what I expected. I don't know why I didn't get that error. I'm installing a clean PrestaShop using Docker, the I will be able to test these bugs in a neutral reproductible environment and not on my production server.

**Comment by florine2623** [comment]
@PrestaShop/qa-functional ,

Could someone with Docker env try to reproduce this issue ? 🙏 
Thanks!

**Comment by lmeyer1** [comment]
Hello @florine2623 
1. I now updated the bug report above with a step by step guide starting at zero (i.e. clean installation).
2. I replaced all A and B with French and German to be very explicit

I know why you got the error 
<img width="1220" alt="199034949-23a2aeee-235b-4ce8-981a-d0bafa5c25d0" src="https://user-images.githubusercontent.com/7520695/199055505-b15ee272-15f0-4d32-a4a5-a5513b181a25.png">

It is not related to the default shop, but it shows up, because Prestashop requires that at least one shop is checked. This why I added in the Setup, point 5: 
> In the shop association for German `French shop` must not be checked (but at least one other shop must be checked).

With this additional detail, you should be able to reproduce the issue without recurring to docker.

**Comment by HanaRebaiQA** [comment]
Hello @lmeyer1 

Thanks for your report.
It seems that your issue is similar to this one https://github.com/PrestaShop/PrestaShop/issues/27617 which is fixed in this [PR](https://github.com/PrestaShop/PrestaShop/pull/28392) on the next **PS1788** release.

Could you please confirm it?

Thank You!

**Comment by lmeyer1** [comment]
@HanaRebaiQA 

No https://github.com/PrestaShop/PrestaShop/issues/27617 is not related with this issue. #27617 is about employee language and display in the BO.
This issue here is about the configuration of the language displayed in the Front Office.

**Comment by HanaRebaiQA** [comment]
Hello @lmeyer1 

Thanks for your feedback.
I tried to reproduce you issue on PS1787, but I did not reproduce step 6 in Reproduce bug 1. But, when I checked in FO with french shop, which is associated to French language, the FO is in English

https://user-images.githubusercontent.com/92912932/199459833-07afc8a6-5fca-412b-b5cc-f7721907b3d8.mp4


What do you think?

Thank You!

**Comment by lmeyer1** [comment]
Hello Hana,
It was difficult for me to follow your screen cast. So I'm not sure where things went wrong.
You say:
> But, when I checked in FO with french shop, which is associated to French language, the FO is in English

IMHO, This is enough to show that there is a bug. The `French shop` must display French only.

**Comment by HanaRebaiQA** [comment]
Hello @lmeyer1 

Thanks for your feedback.
I have checked the same issue that I have communicated with PS1778 and i was able to reproduce it. 
But, i was unable to reproduce the issue with 8.0.0 version.

It may be fixed on 8.0.0.

**PS1778 : NOK** :x: 


https://user-images.githubusercontent.com/92912932/199529862-ea10a6ec-e515-4588-8333-03baf2a16acb.mp4


**PS1787 : NOK** :x: 

https://user-images.githubusercontent.com/92912932/199529414-039a2312-324a-4023-a2ae-5d32edc9bd52.mp4



**PS8.0.0 : OK** :heavy_check_mark: 


https://user-images.githubusercontent.com/92912932/199530979-c84488b9-f51a-49f2-8268-ac0d6403f47a.mp4



Could you please check again?


Thank You!

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Closing the issue as it's not reproducible on 8.0.0 :tada: 

Thanks!
