### ISSUE TITLE
Error 500 on Product Controller 404 at Breadcrumb

### ISSUE THREAD

**Issue by SoftdilGabriel** [PrestaShop/PrestaShop#30183]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When disabling the option "display unavailable attributes" from the product page, accessing the url of a product that has been deleted / deactivated causes a error 500 instead of a 404

![image](https://user-images.githubusercontent.com/93718354/199489102-2f20a9e2-5bda-4e16-b15b-46650e7a1a7c.png)

FrontController calls for getBreadcrumb even with a 404, causing the ProductController to try to get data from a non instanced product object.

### Expected behavior

Show the 404 page

### Steps to reproduce

- On the admin panel, product preferences controller, disable "Display unavailable attributes on the product page"
- On the front of the page, enter the url of a non-existent / not-active product

(Enabling debug may be helpfull, as the 500 disguises itself as an 404 due to headers already been sent)

### PrestaShop version(s) where the bug happened

1.7.8.4+

### PHP version(s) where the bug happened

7+

**Comment by Hlavtox** [comment]
Hi @SoftdilGabriel, I recently cleaned up and refactored some things in ProductController, can you please check if the issue also happens on develop? Maybe I fixed it accidentaly. If not, let's have a look on it and fix it. 👍

https://github.com/PrestaShop/PrestaShop/blob/develop/controllers/front/ProductController.php

**Comment by SoftdilGabriel** [comment]
Hi @Hlavtox , reading the changes from ProductController, and checking also FrontController, it seems unaffected to me.

In [ProductController::init](https://github.com/PrestaShop/PrestaShop/blob/8c60dcf625de7f8dd16e8ffe6793835b1e8ad820/controllers/front/ProductController.php#L148) , if the product is not loaded it returns afeter setting the headers to 404, but the execution continues.
In [FrontController::initContent](https://github.com/PrestaShop/PrestaShop/blob/8c60dcf625de7f8dd16e8ffe6793835b1e8ad820/classes/controller/FrontController.php#L554), the first thing to call is assignGeneralPurposeVariables, wich leads to [getBreadcrumb](https://github.com/PrestaShop/PrestaShop/blob/8c60dcf625de7f8dd16e8ffe6793835b1e8ad820/classes/controller/FrontController.php#L1743) latter on. This calls for [ProductController](https://github.com/PrestaShop/PrestaShop/blob/8c60dcf625de7f8dd16e8ffe6793835b1e8ad820/controllers/front/ProductController.php#L1295), but in it does not check if the product is not loaded and then calls for the info, leading to the error.

(sorry, i dont know how to put proper links to the code)

I think the Stack Trace above is still the same.

**Comment by AureRita** [comment]
Hi @SoftdilGabriel ,

Despite my efforts, I'm not able to reproduce your issue with the provided information. As you can see in this video : 

[Untitled_ Nov 3, 2022 5_52 PM.webm](https://user-images.githubusercontent.com/100699445/199784969-423a6440-4418-4722-bad5-1bc1eddeeffc.webm)

Did I miss something or anything else ? 

Thank you

**Comment by Hlavtox** [comment]
@SoftdilGabriel Can you try adding

```
if (!Validate::isLoadedObject($this->product)) {
   return $breadcrumb;
}
```
after 
```
$breadcrumb = parent::getBreadcrumbLinks();
```
in 
```
ProductController::getBreadcrumbLinks()
```
and tell me if it fixed your issue?

I know where the error is coming from, but I can't reproduce it. I set "Display unavailable attributes" to OFF, deleted a product, tried to access it by `http://localhost/dev/cs/women/2-11-brown-bear-printed-sweater.html#/3-velikost-l` but I have no error. Can try to further check the conditions to reproduce it?

**Comment by SoftdilGabriel** [comment]
@Hlavtox @AureRita Excuse me, i found where the error came from and why you cannot reproduce it.
We're using (in a lot of webs) modules to remove the ID from the url. With it, the $id_product is never set if the product is not found, thus

```
if ($id_product) {
    $this->product = new Product($id_product, true, $this->context->language->id, $this->context->shop->id);
}
```

is tot executing, leading to the error. Sorry for the inconvenience, you can close the issue.

**Comment by AureRita** [comment]
Thanks @SoftdilGabriel for looking about the reason of your bug, 

do not hesitate to contact us if you meet another one 

Have a great day

**Comment by ChillCode** [comment]
Hi 

This issue could be opened I think because it exists, to reproduce:

http://domain.com/en/?controller=product

or using a none existent product ID:

http://domain.com/en/?controller=product&id_product=152989

Found this back in 2021 while I was developing a module and today I was testing an continues to happen.
