### ISSUE TITLE
Fatal error on backoffice Module Manager page, Return value CircuitBreaker

### ISSUE THREAD

**Issue by dheerajwebkul** [PrestaShop/PrestaShop#30182]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Sometimes getting fatal error on the  Backoffice Module Manager page, We are getting this sometimes.

![Return value of PrestaShop_CircuitBreaker_Storage_DoctrineCache__getTransaction() must be an instanc](https://user-images.githubusercontent.com/19220745/199453872-cf997e17-af6b-49f4-bbe3-d383d7387483.png)

### Expected behavior

Must be loaded properly

### Steps to reproduce

1. Enable debug module
2. Go to 'Module Manager' Page

### PrestaShop version(s) where the bug happened

8.0.0.0

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_distributionapiclient  v1.0.2

**Comment by Hlavtox** [comment]
Hi @dheerajwebkul, there is a problem with SSL on your server, check it, fix it, clear presta cache, then it will work. 👍

In `php.ini`, `openssl` extension must be enabled and `openssl.cafile` must be set properly.

**Comment by AureRita** [comment]
Thank you @Hlavtox for your quick answer, 

Hi @dheerajwebkul, 

Did you still get it after clearing the cache ? 

If not, can you give us more details because currently we can't reproduce your issue with this few details on your steps to reproduce 

Waiting for your feedback

**Comment by hibatallahAouadni** [comment]
Hello @dheerajwebkul 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
