### ISSUE TITLE
ps_emailalerts alters $context->shop and $context->language, as a consequence, mails may be sent out in an arbitrary language and shop context

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#30187]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This bug can happen only in a multishop context.

What happened: A merchant received an order confirmation from the email adresse of an other merchant and with the wrong logo, colors and links in it.

How did this happen?
1. A user U subscribed for a notification for product A in shop B
2. Shop B received new stock for product A (hook actionUpdateQuantity was not called by error)
3. In shop A, a customer ordered product A
4. When confirming his order in shop A the following things happened:
   a. hook `actionUpdateQuantity` was called for product A in shop A
   b. `MailAlert::sendCustomerAlert()` was called, and the notification requested by user U in shop B was found
   c. On [`MailAlert.php line 177`](https://github.com/PrestaShop/ps_emailalerts/blob/87a5e4847ce19456f42b797f773c27d525c2484f/MailAlert.php#L177) the context shop and language was changed to shop B and user U's language.
   d. hook `actionValidateOrder` was called to send a notification to the merchant for the new order
5. As the shop and language were now wrong (changed in 4.c.), the merchant received a mail from shop B in the language of user U about the order he received in his shop

### Expected behavior

I expect
- that the module does never change arbitrarily the shop and langage context of the page
- the the `actionUpdateQuantity` hook only affects the current shop and shops in the same shop group if the shop group has the sharing of product quantities enabled.

### Steps to reproduce

Set up the installation

1. Install PS 1.7 locally with multishop enabled using docker ([see this gist](https://gist.github.com/lmeyer1/c40a19d880758bee11a1e8a2c5e819c3))
2. Run maildev `docker run -p 1080:1080 --network prestashop-17 --name maildev maildev/maildev`
3. Go to _Advanced Parameters - Multistore_, Click on the shop group `Default`, then _Edit_. Enable _Share available quantities for sale_.
4. Go to _Shop parameters - Contact_ and setup the _Shop name_ and _Shop email_ for both shop A and B
5. Go to _Design - Theme & Logo_  and upload an email logo for both shop A and B
6. Download ps_emailalerts v. 2.3.3 from https://github.com/PrestaShop/ps_emailalerts/releases/tag/v2.3.3
7. Go to _Modules - Module manager_, click on _Upload module_, upload ps_emailalerts.zip
8. Refresh the page, search for `Mail alerts` and click on _Configure_.
9. Make sure the module is enabled for both shops A and B. Make sure in both shops A and B _Product availability_ is enabled for customers and _New order_ is enabled for merchant and add the merchant's email address.
10. Go to _Design - Email theme_, under _Generate Emails_ choose French, enable_Overwrite templates_, click `Generate Emails`. Do the same thing for German.
11. Go to _Advanced parameters - Email_. Choose `Set my own SMTP parameters (for advanced users ONLY)`, _SMTP server_ : `maildev`, _Port_: `1025`. Click _Save_. Test the configuration by sending a test email. You should get a confirmation, that it succeeded.
12. Navigate to http://localhost:1080/, maildev's webmail, and you should see your test mail.
13. Go to _Shipping - Carriers_ and make sure that a carrier is available in shop A
14. Go to _Payment - Payment methods_ and configure and set up Check or Bankwire.

Reproduce the bug
1. Navigate to http://localhost:8017/shop-b. Change the language to English, click on the Hummingbird T-shirt S white (id_product=1, id_product_attribute=1). Notice it is out of stock. Subscribe to the notification.
![Immagine 2022-11-07 111745](https://user-images.githubusercontent.com/7520695/200285891-81e876dd-af6c-48ae-ab18-d35433cb5dc4.png)
2. Navigate to http://localhost:8018. PHPMyAdmin should open. Enter the password you defined in step _Prerequisites 1._ and run the query `INSERT INTO ps_stock_available (id_product, id_product_attribute, id_shop, id_shop_group, quantity) VALUES ('1', '0', '0', '1', '2'), ('1', '1', '0', '1', '2')`. (Or update, if these lines already exist, they are created when you go into the product page)
3. Navigate to http://localhost:8017/shop-a. Use French. Add the Hummingbird T-shirt S white to the cart. Finalize the order.
4. The order confirmation page is displayed in English. The language just changed for the French customer of the French shop A to English, the language of the unrelated customer of shop B !
5. Navigate to http://localhost:1080/ and look at the emails that were sent out:
![Immagine 2022-11-07 144807](https://user-images.githubusercontent.com/7520695/200326461-68bb4403-6783-49c4-838a-546e5059c5d0.png)
We have:
- Order confirmation for the customer of shop A, it is in French, as Shop A was french
- Check paiement e-mail for the customer of shop A, it's in French too
- The Product available notification for customer of shop B in English (the language of the customer that requested the notification, not the default language of the shop)
- The New order mail for the merchant of shop A. It should be in French as the merchant's language (and the shop's default language) is French.
    - The sender is `Shop B` : wrong
    - The recipient is merchant of shop A: ok
    - The email subject is in French: ok
    - The logo is the one of Shop B (also the link in the footer): wrong
    - The language is English: wrong

### PrestaShop version(s) where the bug happened 

1.7.8.7

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_emailalerts 2.3.3

**Comment by lmeyer1** [comment]
@jolelievre 
Looking at the code, I notice at https://github.com/PrestaShop/ps_emailalerts/blob/87a5e4847ce19456f42b797f773c27d525c2484f/MailAlert.php#L173:
```
        $context = Context::getContext()->cloneContext();
```
Therefore I am astonished, how it was possible that the context switched to another shop in the function `MailAlert::sendCustomerAlert()`.

About `clone` used in `cloneContext()`, the PHP doc says:
> When an object is cloned, PHP will perform a shallow copy of all of the object's properties. Any properties that are references to other variables will remain references.

Is it possible that this is the reason why even though `$context` is a clone, [MailAlert.php line 177](https://github.com/PrestaShop/ps_emailalerts/blob/87a5e4847ce19456f42b797f773c27d525c2484f/MailAlert.php#L177) still changes the shop id of the original `Context` ?

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Thanks for reporting the issue and for the PR :rocket: 
Ping @PrestaShop/prestashop-core-developers can someone please try to reproduce the issue :pray: it's too technical for me!

Thanks in advance!

**Comment by lmeyer1** [comment]
@hibatallahAouadni
Now the steps to reproduce are complete. I reproduced the bug on a clean install of PS 1.7.8.7 with ps_emailalerts v2.3.3.

**Comment by matks** [comment]
Whaaaa @lmeyer1 what a complex bug report 😄 great work

**Comment by lmeyer1** [comment]
@matks And what a simple fix !!! https://github.com/PrestaShop/ps_emailalerts/pull/121/commits/d2037b338f6596cff8b64bfad28d8c6d343c8228

Never the less I needed the whole steps to reproduce to prove to myself that the fix didn't break anything else. 😅

**Comment by HanaRebaiQA** [comment]
Hello @lmeyer1 

I tried to reproduce your issue with **PS1787** and **php 7.4** with **ps_emailalerts v2.4.0 from dev branch**.
I used the same steps to reproduce.

In the email of **New order**, i think i have only the text is wrong which is in English.
But all information about the : 

- The sender is Shop B : OK
- The recipient is merchant of shop A: OK
- The email subject is in French: OK
- The logo is the one of Shop B (also the link in the footer): OK
- The language is English: NOK

In step2, i have used this query which is related to Shop B 

`INSERT INTO hana_stock_available (id_product, id_product_attribute, id_shop, id_shop_group, quantity) VALUES ('1', '1', '4', '1', '2'), ('1', '0', '4', '1', '2');
`
![image](https://user-images.githubusercontent.com/92912932/200815181-09c51e26-56a8-4c32-b071-7afd2c2ac145.png)

https://user-images.githubusercontent.com/92912932/200815100-3b37295f-34db-4bb6-be2d-5b38386d4b95.mp4


What do you think ? Didi I missed something?

Thank You!

**Comment by lmeyer1** [comment]
@HanaRebaiQA 
👏 To be able to reproduce ! I'm amazed !

But, you didn't interpret the result correctly:
> The sender is Shop B : OK
The recipient is merchant of shop A: OK
The email subject is in French: OK
The logo is the one of Shop B (also the link in the footer): OK
The language is English: NOK

The sender is Shop B : ~~OK~~ This should be the shop A. If a customer shops in shop A all related emails must be sent from shop A
The recipient is merchant of shop A: OK
The email subject is in French: OK
The logo is the one of Shop B (also the link in the footer): ~~OK~~ This particularly bad ! The logo and the links must be of shop A and are of shop B! Fortunately the customer did not get this to his eyes, only the merchant. 
The language is English: NOK

Woe to you 😨 as shop owner your correspondence is sent from a foreign shop! 😭

**Comment by HanaRebaiQA** [comment]
Thank You @lmeyer1 

So, it was something missed ? Or, this is the reporter bug ?

**Comment by lmeyer1** [comment]
@HanaRebaiQA 
You reproduced the bug I reported. You only missed the words **_wrong_** in the report
> The sender is Shop B : **_wrong_**
The recipient is merchant of shop A: ok
The email subject is in French: ok
The logo is the one of Shop B (also the link in the footer): **_wrong_**
The language is English: wrong

**Comment by HanaRebaiQA** [comment]
Hello, 

I tried to reproduce the bug also on PS8.0.x, but i was blocked on step 3 in `Reproduce the bug `section. I did the same steps of the `Set up the installation` section like i have reproduced with **PS1787**

The issue is that i was unable to Add the product to cart after inserting these queries of the product related to both of shops.
 `(INSERT INTO hana_stock_available (id_product, id_product_attribute, id_shop, id_shop_group, quantity) VALUES ('1', '1', '3', '1', '2'), ('1', '0', '3', '1', '2');` && `INSERT INTO hana_stock_available (id_product, id_product_attribute, id_shop, id_shop_group, quantity) VALUES ('1', '1', '2', '1', '2'), ('1', '0', '2', '1', '2');)`  

I don't know if the structure of the stock_availability is changed with 8.0.0 ? 
ping @jolelievre What do you think please? 


https://user-images.githubusercontent.com/92912932/200871221-b883d1d1-255f-4080-aab7-2234abd61c9b.mp4

![image](https://user-images.githubusercontent.com/92912932/200872406-7b98c3d4-2f5f-4c32-be04-34779a8538c6.png)

Thank You!
