### ISSUE TITLE
[BO] Can't view shopping carts if customer has no address

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#30180]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Create a new customer without an address and try to add a product in the cart, then access BO>SELL>Order>Shopping Carts, you will encounter this exception (see the attached screenshot below):

![image](https://user-images.githubusercontent.com/23308427/199307711-7767bf5a-3c86-4a3c-a4ca-67e004013fbf.png)

### Expected behavior

This issue has been fixed in PS1.7.5.0 but it seems to be back only on develop.
See the issue #9782 and the PR #11416
Related to #12617
It's a regression! Cause I didn't encounter this issue with PS1787 nor PS800!

### Steps to reproduce

1. FO> Create a new customer without an address
2. Add a product to the cart 
3. BO>SELL>Orders>Shopping Carts
4. See error > an exception will be thrown 

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.2

**Comment by AureRita** [comment]
Hi @hibatallahAouadni  ,

Despite my efforts, I'm not able to reproduce your issue with the provided information.As you can see in this video : 

[Untitled_ Nov 3, 2022 5_25 PM.webm](https://user-images.githubusercontent.com/100699445/199777601-7c83e431-e6d9-4e93-ada3-bd9f9fd4c8ea.webm)

someone of the @PrestaShop/qa-team can reproduce this issue ? 

Thank you

**Comment by florine2623** [comment]
Hello @hibatallahAouadni ,

I couldn't reproduce the issue on `develop` either.
On my end, I'm using PHP 7.4. Installation done with country France and Default language English.

Is there something more about config that I can try ?
Thanks!

**Comment by hibatallahAouadni** [comment]
So, we need to close the issue :wink: 
Thanks everyone for your tests :pray:

Closing the issue as invalid!
