### ISSUE TITLE
Most of native modules use `trans` while 5 others use `getTranslator()->trans`

### ISSUE THREAD

**Issue by leemyongpakvn** [PrestaShop/PrestaShop#30193]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Module class has its own [trans](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/module/Module.php#L3363) function so we need to replace `getTranslator()->trans` by `trans` in these 5 modules to keep consistency and briefness throughout the project:
- [x] [ps_categorytree](https://github.com/PrestaShop/ps_categorytree/blob/dev/ps_categorytree.php)
- [x] [ps_contactinfo](https://github.com/PrestaShop/ps_contactinfo/blob/dev/ps_contactinfo.php)
- [x] [ps_customersignin](https://github.com/PrestaShop/ps_customersignin/blob/dev/ps_customersignin.php)
- [x] [ps_googleanalytics](https://github.com/PrestaShop/ps_googleanalytics/blob/dev/classes/Form/ConfigurationForm.php)
- [x] [ps_imageslider](https://github.com/PrestaShop/ps_imageslider/blob/dev/ps_imageslider.php)

### Describe the solution you'd like

Replace `getTranslator()->trans` by `trans` in 5 modules above

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by AureRita** [comment]
Hi @leemyongpakvn  ,

Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments. 

Thank you for your PR :rocket: 

Thank you

**Comment by leemyongpakvn** [comment]
@jolelievre In fact, this issue is only partially completed because it still has 3 related PRs opening, and 1 related PR coming.
