### ISSUE TITLE
Module vatnumber 2.1.0 not working anymore

### ISSUE THREAD

**Issue by pluscom-kevin** [PrestaShop/PrestaShop#30199]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi everyone !

The module vatnumber version 2.1.0 is not working anymore since the url used to make the VAT search change his behavior
Old url : http://ec.europa.eu/taxation_customs/vies/viesquer.do
New url : https://ec.europa.eu/taxation_customs/vies/services/checkVatService.wsdl

The only answer we get trying to enter a correct VAT number under a customer address is the unavailable service.
![Capture d’écran 2022-11-03 115659](https://user-images.githubusercontent.com/68845619/199704272-9b9faacc-706f-4790-9237-aea116ac78e9.jpg)

### Expected behavior

I should be able to add a vat number.

### Steps to reproduce

1. Go to module > European VAT Number > Activate (Configuration, France).
2. Create an account from Portugal, with existing address
3. Add a VAT number into the correct field (need to be in B2B mode)

### PrestaShop version(s) where the bug happened

1.6.1.24

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

vatnumber 2.1.0

**Comment by Lionel-dev** [comment]
Hello, 

Did you check to see if VIES was UP during your test ? The service is often down at the end/beginning of the month, because it has a big load.

**Comment by AureRita** [comment]
HI @pluscom-kevin  ,

PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).

Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

Thank you
