### ISSUE TITLE
Order Quantity - The website allows you to purchase products when they are out of stock

### ISSUE THREAD

**Issue by arcofins** [PrestaShop/PrestaShop#30198]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In my back-office, I often receive orders whereas the purchased product is out of stock. 

I don't know how my customers can to that. 

On the screenshot below you can see the detail of an order. You can see a negative quantity. 

<img width="1228" alt="Capture d’écran 2022-11-03 à 11 15 17" src="https://user-images.githubusercontent.com/65950828/199696570-76cffa51-f89b-444b-b858-d165d6602184.png">

On this second screenshot (BO/Product/Quantity tap of this product). You can see that I ask to refuse orders if the product is out of stock.

![Uploading Capture d’écran 2022-11-03 à 11.15.32.png…]()

### Expected behavior

If a product is out of stock, my customers couldn't buy it.  

### Steps to reproduce

1. Go to my BO/ Orders
2. See the order 1068
3.Click on the product and click on Quantity tab

### PrestaShop version(s) where the bug happened

1.7.1.2

**Comment by Hlavtox** [comment]
Hi @arcofins, this issue is fixed in Prestashop 8 that was released last week. 🚀 With many other fixes. https://github.com/PrestaShop/PrestaShop/releases/tag/8.0.0

Autoupgrade module will be ready soon, I suggest upgrading when it's ready. :-)

**Comment by AureRita** [comment]
Hi @arcofins 

Thank you @Hlavtox for your quick answer. As he said, it's already fixed in the version 8.0.0 so the issue should be already reported. 
We are aware of this issue, it is already in our debug backlog. 
Thank you for your time but unfortunately I'll close this issue wich is a dupplicate of an other

Thank you

**Comment by AureRita** [comment]
Duplicate of #28097

**Comment by masiorama** [comment]
Sorry to bother but this issue is NOT a duplicate of #28097
I'm having the same issue on 1.7.8.11 version.
