### ISSUE TITLE
 ps_languageselector disappeared, not shown

### ISSUE THREAD

**Issue by ddv1976** [PrestaShop/PrestaShop#30205]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The language selector show 404 links, in the configuration I restarted the module, but it disappeared, the language selector is not visible in my store! What I can do? any solution?

### Steps to reproduce

1. Go to modules
2. Go to manager / modules
3. Find the module Language block selector
4. Click to reset

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.32 

### If your bug is related to a module, specify its name and its version

ps_languageselector  v2.1.0

**Comment by Hlavtox** [comment]
Hi @ddv1976 

- Do you have more than 1 active language?
- Is the module enabled?
- In Module Positions, is the module hooked to proper hooks?

**Comment by ddv1976** [comment]
1. Yes, 4 active language
2. Module is active
3. Yes, hooks to display
4. Today the module show, but the links products category is to 404!
/index.php?controller=category
/it/index.php?controller=category
/fr/index.php?controller=category
/de/index.php?controller=category

**Comment by Hlavtox** [comment]
Friendly URLs enabled?

**Comment by florine2623** [comment]
Hello @ddv1976 ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
