### ISSUE TITLE
Bug after 1clik Upgrade - Impossible to use catalog

### ISSUE THREAD

**Issue by arcofins** [PrestaShop/PrestaShop#30207]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After a 1click upgrade, I have this screen on my catalog.

I can't use it and my BO seems to be broken sometimes.
<img width="1437" alt="Capture d’écran 2022-11-03 à 22 49 10" src="https://user-images.githubusercontent.com/65950828/199841216-93147649-21ef-4350-b3c3-ed08d3a44873.png">

### Expected behavior

A website I can use...

### Steps to reproduce

Go to my BO/Catalog after 1clickupgrade

### PrestaShop version(s) where the bug happened

1.7.0.2

**Comment by Hlavtox** [comment]
Open F12 and copy everything in the console. Also, did you hard flush your cache with CTRL+F5?

**Comment by arcofins** [comment]
Hi Hlavtox,

Thanks for your answer, I just tried to refresh the cache and nothing changes.

Here is my console :
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)

**Comment by arcofins** [comment]
On the dashboard, I also have this on my console 

[Error] ReferenceError: Can't find variable: show_new_orders
	(fonction anonyme) (notifications.js:47)
	j (jquery-1.11.0.min.js:2:27142)
	fireWith (jquery-1.11.0.min.js:2:27951)
	ready (jquery-1.11.0.min.js:2:29795)
	K (jquery-1.11.0.min.js:2:30134)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)
[Error] Failed to load resource: the server responded with a status of 503 () (index.php, line 0)

Maybe it can help

**Comment by arcofins** [comment]
Found a way to rollback to an older version

**Comment by Hlavtox** [comment]
@arcofins What PHP version are you using? What version of Prestashop did you upgrade from and to? We need to know this information to investigate. 👍

**Comment by arcofins** [comment]
@Hlavtox 

I'm using Php 7.1 and I tried to upgrade from 1.7.0.2 to 1.7.8.7
