### ISSUE TITLE
BO - No clear alert is displayed when no permission to create/edit a product V2

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#30202]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

- In the BO, No clear alert is displayed when we try to add a new product V2 & we don't have the right permissions.
- At the edit, I can't see the product details (Blank page)

### Expected behavior

If the user accesses to a direct link of add or edit product
Then he is redirected to the default page

If the user doesn't have the right to edit or add product
Then the button add/edit is hidden 

If the user doesn't have the right to edit or add product
Then the link to the quick access is hidden

### Steps to reproduce

**Case1** reproduced only with **develop** branch
1. Go to BO > Advanced Parameters > Team > Profiles page
2. Create a new profile
3. This profile has only "View" 
![image](https://user-images.githubusercontent.com/16067358/198684155-ff9923ba-847f-44d7-98d8-69a15db10141.png)
4. Create an employee with this profile & try to sign in with it 
![image](https://user-images.githubusercontent.com/16067358/198684320-ae3c4eea-7837-4ffa-8108-86525e413deb.png)
5. Click on "Quick access" > Add a new product
6. See error => No alert displayed 

https://user-images.githubusercontent.com/16067358/198684942-bf84d054-e74d-48e5-ac34-9b9d65883d8f.mp4

**Case2** reproduced with 8.0.0 & develop
1. Go to BO > Advanced Parameters > Team > Profiles page
2. Create a new profile
3. This profile has only "View" 
![image](https://user-images.githubusercontent.com/16067358/198684155-ff9923ba-847f-44d7-98d8-69a15db10141.png)
4. Create an employee with this profile & try to sign in with it 
![image](https://user-images.githubusercontent.com/16067358/198684320-ae3c4eea-7837-4ffa-8108-86525e413deb.png)
5. Go to BO > Catalog > Products V2 and click Add a new product
6. See error => No alert displayed 

**Case3** reproduced with 8.0.0 & develop
1. Go to BO > Advanced Parameters > Team > Profiles page
2. Create a new profile
3. This profile has only "View" 
![image](https://user-images.githubusercontent.com/16067358/198684155-ff9923ba-847f-44d7-98d8-69a15db10141.png)
4. Create an employee with this profile & try to sign in with it 
![image](https://user-images.githubusercontent.com/16067358/198684320-ae3c4eea-7837-4ffa-8108-86525e413deb.png)
5. Go to BO > Catalog > Edit a new product
6. See error (blank page)
### PrestaShop version(s) where the bug happened

8.0.0, develop

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello @khouloudbelguith ,

I reproduce the issue with PrestaShop version **8.0.0** and **develop**, I'll add this to the backlog so it can be fixed.
I don't have the exact same behavior.

**PS 8.0.0:**
**Case1**:
Sometimes the alert is displayed, sometimes not.

https://user-images.githubusercontent.com/16019289/200277907-995be643-3fe5-41c4-b8d9-00636f6f7e69.mov


**Case2**:
<img width="1439" alt="Screenshot 2022-11-07 at 10 36 21" src="https://user-images.githubusercontent.com/16019289/200277961-e03a1abb-1163-423c-b9a6-0e17e92148fe.png">

**PS develop:**

https://user-images.githubusercontent.com/16019289/200288488-fd2ddd6a-481e-41c2-9e25-836179dab421.mov


Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
