### ISSUE TITLE
[PHP8.1] - An error is displayed in the BO > Shopping carts page when debug mode enabled

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#30203]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Orders > Shopping carts page > An error is displayed
![image](https://user-images.githubusercontent.com/16067358/199722219-26fca503-f179-4e2b-917a-1ab3d65e7253.png)

### Expected behavior

No error displayed

### Steps to reproduce

1. Go to BO > Shop Parameters > General page & enable multistore
2. Go to BO > Advanced Parameters > Multistore page & create a new shop & configure it
3. Go to BO > Advanced Parameters > Performance page & enable debug mode
4. Go to BO > Orders > Shopping carts page
5. See error 

![image](https://user-images.githubusercontent.com/16067358/199722507-a41d3377-9cde-45ac-b789-7442b0ecd655.png)

PS: develop + php8.0 => ok
8.0.x + php8.1 => ok

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

**Comment by sallemiines** [comment]
Hello @khouloudbelguith 

I have reproduced your issue with : `develop + PHP 8.0.0` **OK** , `  develop + PHP 8.1` **NOK**  , you can see the attached screenshot
![Capture d’écran du 2022-11-08 13-37-31](https://user-images.githubusercontent.com/31663369/200567840-fb28001f-3464-4034-b6fc-c59e7f724f22.png)


Thank you ! :rocket:
