### ISSUE TITLE
BO - Error on Logs when logging in & out of the shop

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#30204]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In Advanced Parameters > Logs, I have an error displayed in my Logs lists.

<img width="1190" alt="Screenshot 2022-11-03 at 14 43 14" src="https://user-images.githubusercontent.com/16019289/199746346-0dfed620-c286-4c4e-95d2-7971ff9b2695.png">

There was an error with the request. Code: 302

Although, on a fresh install I couldn't reproduce the issue anymore, the error is still present on the nightly.

### Expected behavior

I should not have this error.

It is a regression from PS 1.7.8.7, as it was not reproduced on this version.

### Steps to reproduce

1. Install 1.7.8.x branch
2. Login and logout from your admin account multiple times (user incognito mode as well)
3. Go to BO > Advanced Parameters > Logs
4. Filter on Severity Error (3)
5. See error

### PrestaShop version(s) where the bug happened

1.7.8.x

### PHP version(s) where the bug happened

7.4, 8.0

**Comment by Hlavtox** [comment]
@hibatallahAouadni Can you retest please?

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Indeed it's fixed :tada: :tada: :tada: 

![image](https://github.com/PrestaShop/PrestaShop/assets/23308427/831c2282-dbc1-4899-ad25-096e2f4452f7)

Closing the issue.

Thanks!
