### ISSUE TITLE
Default category should always be enforced on a product, even after category is deleted

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#30219]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

comes from PR https://github.com/PrestaShop/PrestaShop/pull/28141#issuecomment-1303654813

When deleting category, it is possible to leave certain products without default category, which leads to warning in FO and possibly other issues.
Currently the DeleteCategoryHandler only update product categories when they have no categories left, but it doesn't update those that have no default category left. (the product.id_default_category ends up invalid because it points to category which doesn't exist anymore).

### Expected behavior

when deleting category, we should also update products that doesn't have the default category left (or the ones that the default category was the one that we just deleted), so that its not possible for product to end up without default category.

### Steps to reproduce

1. Create 2 categories (I called it catD, catE)
2. Go to BO product page (no matter v1 or v2). Select any product for edition.
3. Add catD and catE to the product (so there is no other categories for that product), and mark catD as default one.
![Screenshot from 2022-11-04 16-28-49](https://user-images.githubusercontent.com/31609858/200006265-30577be8-6857-4e68-9c62-68ab2c49e058.png)

4. Go BO categories page and delete catD (I chose first option when deleting, but it shouldn't matter)
5. Go to BO product page (same product) and see it doesn't have the default category anymore.
![Screenshot from 2022-11-04 16-29-26](https://user-images.githubusercontent.com/31609858/200006327-b3e821be-deed-428f-a118-614b0ac39c30.png)
6. Go to FO, find your product, open it and see error mentioning `Trying to access array offset on value of type bool in /var/www/html/prestashop/classes/Category.php on line 2018`
![Screenshot from 2022-11-04 16-29-42](https://user-images.githubusercontent.com/31609858/200006359-982284e5-c75f-4ab7-85ed-9a33577d8baa.png)

### PrestaShop version(s) where the bug happened

develop (but pretty sure its the same with 178 and 8.0 and maybe even some earlier versions)

**Comment by Hlavtox** [comment]
```php
public function assignHomeDefaultCategory() {
  Db::getInstance()->Execute('UPDATE ps_product SET id_category_default = 2 
  WHERE id_product NOT IN (SELECT id_product FROM ps_category_product);');

  Db::getInstance()->Execute('UPDATE ps_product_shop SET id_category_default = 2 
  WHERE id_product NOT IN (SELECT id_product FROM ps_category_product);');
}
```

and we also need to add it it to ps_category_product somehow, fast

**Comment by florine2623** [comment]
Hello @zuk3975 ,

I reproduced your issue on `1.7.8.7`, I have an exception:
<img width="1117" alt="Screenshot 2022-11-07 at 14 48 13" src="https://user-images.githubusercontent.com/16019289/200326143-1298a81b-9a22-45eb-84ca-433fa0b08c7f.png">

On `8.0.x` and `develop`, I have a warning :
<img width="1318" alt="Screenshot 2022-11-07 at 14 50 18" src="https://user-images.githubusercontent.com/16019289/200326972-fd4f3f28-cab5-41a7-ab18-0a52a7fc3fa4.png">

I'll add this to the backlog so it can be fixed.

Thank you for the PR ^^
