### ISSUE TITLE
Product page v2 list not showing product if its not in category "Home"

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#30212]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Product page v2 list not showing product if its not in category "Home".
It seems to be due to the QueryBuilder which defaults to filter by category id of PS_HOME_CATEGORY in PrestaShop\PrestaShop\Core\Grid\Query\ProductQueryBuilder::getFilteredCategoryId

### Expected behavior

As in product page v1 it should show all the products that exists in database.

### Steps to reproduce

1. Make sure experimental product page v2 is on (Advanced Parameters -> New &Experimental features -> New product page - Single store switched on).
2. Go to BO products list and open any product for edition and scroll down to categories part
3. Remove "Home" category (you may first need to change the default category, because you cannot remove current default product category). This step could probably also be done in product page v1 by unselecting home category.
4. Go to products list and see that the product is gone from list. (you could still find it by filtering by other category though)

### PrestaShop version(s) where the bug happened

develop

**Comment by Hlavtox** [comment]
It should be solved by https://github.com/PrestaShop/PrestaShop/pull/29039

**Comment by zuk3975** [comment]
> It should be solved by #29039

right, by this side bug fix https://github.com/PrestaShop/PrestaShop/pull/29039#issuecomment-1252563077 
:+1: 
Then I guess we will be able to close this Issue after that one is merged.

**Comment by florine2623** [comment]
Hello @zuk3975 ,

I reproduce the issue with PrestaShop version `8.0.x`, `develop`, I'll add this to the backlog so it can be fixed.
It is regression, on `1.7.8.7` with Experimental Page, the issue was nos present.

https://user-images.githubusercontent.com/16019289/200339394-880e7258-44ff-4464-b3e0-fa1394e6d0ec.mov

Thank you for the PR ^^
