### ISSUE TITLE
Friendly URLs don't work after enabling them

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#30217]
### Describe the bug and add screenshots

Friendly URLs don't work after enabling disabling and enabling them. You need to open some rewrite and save it to make it work.

### Expected behavior

Friendly URLs should work fine after enabling friendly URLs, without doing additional action.

### Steps to reproduce - module

1. Have 2 languages active. Not sure if this is needed, but to be safe.
2. Go to `http://localhost/dev/cs/4-men`. OK. Keep the page open.
2. In BO, disable Friendly URLs.
3. Go back to the category in FO, refresh, see error `[Debug] This page has moved`. OK. Keep page open.
4. Go back to BO, enable friendly URLs again.
5. Go back to the category  in FO, refresh, see 404 error. NOK.
6. Go back to BO, open any rewrite on SEO & URLs page and click save.
7. Go back to the category in FO, refresh, see page works again.

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.0

**Comment by florine2623** [comment]
Hello @Hlavtox ,

I reproduce the issue with PrestaShop version `8.0.x` and `develop`, I'll add this to the backlog so it can be fixed.

Not reproduced on `1.7.8.7`. So this is a regression.

This is the wanted behavior:

https://user-images.githubusercontent.com/16019289/200297400-9b2ad197-ab4a-493b-999b-ca3a962881e1.mov


Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
