### ISSUE TITLE
Stop using jqueryuiSortable and jquerySortable in native modules

### ISSUE THREAD

**Issue by leemyongpakvn** [PrestaShop/PrestaShop#30210]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

According to [an article in openjsf.org](https://openjsf.org/projects/#emeritus), jqueryUI is a Emeritus project which the maintainers feel _have reached or are nearing end-of-life_. [jqueryui in PrestaShop core js](https://github.com/PrestaShop/PrestaShop/blob/8.0.0/js/jquery/ui/jquery-ui.js) even stays at 1.10 version since 2013, all jqueryui plugins there are outdated the same.
We need to replace jqueryui plugins by other equivalent modern, active and popular libraries one by one ASAP. 
Starting with [jquery.ui.sortable.js](https://github.com/PrestaShop/PrestaShop/blob/8.0.0/js/jquery/ui/jquery.ui.sortable.min.js) in these 2 native modules is my first step (someone had done initial steps in hummingbird theme and ps_facetedsearch module:)
- [x] [blockreassurance](https://github.com/PrestaShop/blockreassurance/blob/v5.1.1/blockreassurance.php#L246)
- [x] [ps_imageslider](https://github.com/PrestaShop/ps_imageslider/blob/v3.1.1/ps_imageslider.php#L611)

Furthermore, the similar plugin [jquery/plugins/jquery.sortable.js](https://github.com/PrestaShop/PrestaShop/blob/8.0.0/js/jquery/plugins/jquery.sortable.js) (used by  ps_facetedsearch module) is outdated, so we need to replace it as well (my second step;)  
### Describe the solution you'd like

Stop using jquery/ui/jquery.ui.sortable.js in native modules, use  [SortableJS](https://github.com/SortableJS/Sortable) instead, like [Drupal had done with their core](https://www.drupal.org/node/3084730).

Stop using jquery/plugins/jquery.sortable.js, use SortableJS instead, like jquery.sortable's author suggested at [deprecation-notice](https://github.com/farhadi/html5sortable#deprecation-notice).

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @leemyongpakvn 

Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. 
Thanks for yoru PR :rocket: 

Thank you
