### ISSUE TITLE
Payment module does not appear in Australia

### ISSUE THREAD

**Issue by panacy** [PrestaShop/PrestaShop#30223]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello 

My client from Australia reported that payment module does not appear (only Pay by bank wire). 

I have already contacted tech support of my payment module operator (https://www.paynow.pl/), their IT department checked this issue and told me that on their side everything is fine.

Recent orders from other countries (Saudi Arabia, UK) work perfectly.

https://rubyvocalbooth.com

![ruby](https://user-images.githubusercontent.com/33621903/200040380-ae94e828-257e-48c1-9c98-5772866222d1.png)

help

### Expected behavior

Show payment module PayNow in Australia.

### Steps to reproduce

1. Go to cart with added product
2. Type any address in Australia
3. Choose fedex shipping
4. Check if other payment method than "pay by bank wire" appear

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

paynow.pl v1.6.19

**Comment by hibatallahAouadni** [comment]
Hello @panacy 

I didn't manage to reproduce the issue with PS1787.
Did you try to disable the overrides and switch to the default theme CLASSIC? and check if the issue still persists.
Please check if your payment module is enabled in Australia (see the attached screenshot below)

![image](https://user-images.githubusercontent.com/23308427/200054763-860cf8c6-66b6-4e15-a78a-329cb725a042.jpeg)

Please check and feedback.

Thanks!

**Comment by panacy** [comment]
HelloWe were able to check and find out that some conflict with USD currency appears. When client chooses EUR, payment module works fine.Can you suggest how can we fix this issue?PaulWiadomość napisana przez Hibatallah Aouadni ***@***.***> w dniu 04.11.2022, o godz. 19:48:﻿
Hello @panacy
I didn't manage to reproduce the issue with PS1787.
Did you try to disable the overrides and switch to the default theme CLASSIC? and check if the issue still persists.
Please check and feedback.
Thanks!

**Comment by panacy** [comment]
Hello

We were able to check and find out that some conflict with USD currency appears. When client chooses EUR, payment module works fine.

Can you suggest how can we fix this issue?

Paul

**Comment by florine2623** [comment]
Hello @panacy,

Thanks for letting us know.

You just need to check all the currencies for your payment module:
<img width="1172" alt="Screenshot 2022-11-07 at 09 55 24" src="https://user-images.githubusercontent.com/16019289/200268645-a391a19b-76a7-4d6b-ae03-eca915e8e02a.png">

I'll close your issue as we can't reproduce it on our end using a native payment module. Do not hesitate to contact the developer of the module directly.

Thanks!

**Comment by panacy** [comment]
Please read my first post precisely. Module developer checked it out - all ok. Your solution to check propper currencies is wrong because it was done. Module doesn’t work with USD currency module does not appear. Now we deleted USD so the client could only choose EUR (module works). But why it doesn’t appear with USD?PawełWiadomość napisana przez florine2623 ***@***.***> w dniu 07.11.2022, o godz. 09:57:﻿
Hello @panacy,
Thanks for letting us know.
You just need to check all the currencies for your payment module:

I'll close your issue as we can't reproduce it on our end using a native payment module. Do not hesitate to contact the developer of the module directly.
Thanks!
