### ISSUE TITLE
Add TikTok to `ps_socialfollow` module

### ISSUE THREAD

**Issue by micka-fdz** [PrestaShop/PrestaShop#30229]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Everything is in the title. TikTok is a must-have social network in 2022.

### Describe the solution you'd like

Add TikTok to `ps_socialfollow` module. I'll make a PR to add it.

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by florine2623** [comment]
Hello @micka-fdz ,

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 

Thanks for your PR ^^
