### ISSUE TITLE
PS_Wire Transfer

### ISSUE THREAD

**Issue by TGD001** [PrestaShop/PrestaShop#30220]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

the module (rel. 2.1.3)  raised a 500 error on last checkout step.

Debug

<html>
<body>

(1/1) ContextErrorExceptionNotice: Undefined index: weight_attribute
--
in CachingUtility.php line 199
at CachingUtility::getPackages()in PackageCostCalculator.php line 95
at PackageCostCalculator::getPackageCost()in packlink.php line 587
at Packlink->getPackageShippingCost()in Cart.php line 3880
at CartCore->getPackageShippingCostFromModule()in Cart.php line 3821
at CartCore->getPackageShippingCost()in Carrier.php line 767
at CarrierCore::getCarriersForOrder()in Carrier.php line 1564
at CarrierCore::getAvailableCarrierList()in Cart.php line 2634
at CartCore->getPackageList()in Cart.php line 2847
at CartCore->getDeliveryOptionList()in Cart.php line 3395
at CartCore->getDeliveryOption()in Cart.php line 3468
at CartCore->getTotalShippingCost()in Fees.php line 95
at Fees->processCalculation()in Calculator.php line 354
at Calculator->calculateFees()in Calculator.php line 155
at Calculator->processCalculation()in Cart.php line 2190
at CartCore->getOrderTotal()in CartPresenter.php line 335
at CartPresenter->present()in OrderController.php line 251
at OrderControllerCore->initContent()in Controller.php line 306
at ControllerCore->run()in Dispatcher.php line 518
at DispatcherCore->dispatch()in index.php line 28

</body>
</html>

Thank you

### Steps to reproduce

Last checkout step after payment choice, last click to close transaction.

 Every payment choice works exctept wire transfer

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_wirepayment.pho

**Comment by hibatallahAouadni** [comment]
Hello @TGD001 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must provide clear and concise steps to reprodcue**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
