### ISSUE TITLE
PrestaShop Product combinations: Unable to update settings

### ISSUE THREAD

**Issue by Sotoamino** [PrestaShop/PrestaShop#30235]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello. When I try to put combinations, PrestaShop refuses them and gives me an error "Unable to update settings". I have enabled debug mode and these errors stand out:
![image](https://user-images.githubusercontent.com/59519426/200340370-06ec12a8-5a09-405b-bf07-4d1f71ab62ef.png)

Can you help me ?

Thanks in advance

### Steps to reproduce

1 Go to "Products"

2. Add combinations

3. Try to save

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.3.33

**Comment by florine2623** [comment]
Hello @Sotoamino ,

I can't reproduce your issue with the info you provided about your configuration.

https://user-images.githubusercontent.com/16019289/200344911-ffb6c381-e16c-425f-9054-2cbfbb04ee3a.mov

Make sure you are up to date with the system requirements : https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/

**Comment by florine2623** [comment]
Ping @PrestaShop/prestashop-core-developers

Maybe one of you can tell where these errors come from ?

**Comment by nicosomb** [comment]
@florine2623 no error here, just some notice. I don't think (but maybe I'm wrong) that these messages can't explain the issue.

**Comment by Sotoamino** [comment]
I give you the maximum information i have
![image](https://user-images.githubusercontent.com/59519426/200355174-ebb7d5f8-a822-4b4b-a6c0-5ff9d2dcb7c8.png)

Modules
![image](https://user-images.githubusercontent.com/59519426/200355348-fb9689b6-4307-445c-adc5-0db06de84f75.png)
![image](https://user-images.githubusercontent.com/59519426/200355426-d8305537-2c2a-4f1a-a4a0-f7514785476e.png)
![image](https://user-images.githubusercontent.com/59519426/200355463-04a0254d-31c8-4d89-b65b-441badcc38b8.png)



And the problem in video :

https://screenrec.com/share/M6jYbzmCH0

**Comment by templatin** [comment]
I have already reported this issue #30179

**Comment by sallemiines** [comment]
Hello @Sotoamino 

Thanks for your feedback!
Ping @PrestaShop/prestashop-core-developers could someone please try to reproduce the issue and check the author configuration :pray: 

Thanks in advance!

**Comment by nicosomb** [comment]
@sallemiines it seems you already reproduced this bug here https://github.com/PrestaShop/PrestaShop/issues/30179

**Comment by sallemiines** [comment]
Duplicate  of https://github.com/PrestaShop/PrestaShop/issues/30179
