### ISSUE TITLE
Bug if PS_SHIPPING_FREE_PRICE has changed when editing a customer delivery address

### ISSUE THREAD

**Issue by Daaaaad** [PrestaShop/PrestaShop#30238]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

I found a very annoying issue : If you change the value of the "Free shipping starts at" (PS_SHIPPING_FREE_PRICE in configuration table) field value under "Shipping > Preferences" in the backoffice and then edit the delivery address of an order the shipping costs will be recalculated with the current value of the field.

We regularly change the value of the "Free shipping starts at" field from 0 (disabled) to 1 to offer free shipping to our customers. The value of this field should be stored somewhere in the order detail/history to have correct recalculations.

Currently that leads to a mismatch between price paid and price to pay with a red error message : 

<img width="520" alt="Capture d’écran 2022-11-07 à 17 48 38" src="https://user-images.githubusercontent.com/167037/200367286-39aa187d-51a4-43df-a53a-db57436b9394.png">

Could you help?

Regards,

David.

### Expected behavior

Order's delivery address editing should trigger a price recalculation with the right order context (value of the "Free shipping starts at" field at the moment of the order).

### Steps to reproduce

1. Set the "Free shipping starts at" field value to 1€ (to enable free shipping)
2. Place an order
3. Change the "Free shipping starts at" value to 0 (to disable free shipping)
4. Update Order status with Payment accepted
5. Open the order and edit the delivery address (didn't tested with invoice address). Even a change in the phone number will trigger price recalculation
6. You now have a mismatch between price paid and price to pay with a red error message
### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

**Comment by sallemiines** [comment]
Hello @Daaaaad 

I have reproduced your issue with `PS 1787` , `PS 800` , you can see the attached screenshot 

![Orders-Order-TAGZXQZIC-from-John-DOE-•-1787](https://user-images.githubusercontent.com/31663369/200541458-76bc1b98-a697-4fa6-a58f-b4c5c7030fd8.png)

Thank you !

**Comment by Daaaaad** [comment]
Thank you @sallemiines 👍

**Comment by gennaris** [comment]
Not a bug... 

Just use this setting to avoid recalculation:

![jYDU2zvvmJ](https://user-images.githubusercontent.com/43071148/200639486-b583ef6b-3d91-4636-bb16-f3f7562400f1.png)

**Comment by Daaaaad** [comment]
Thank you @gennaris ! I didn't know this option 😀

**Comment by florine2623** [comment]
Not a bug indeed ^^
