### ISSUE TITLE
Logo not showing on invoice

### ISSUE THREAD

**Issue by arirangz** [PrestaShop/PrestaShop#30246]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In prestashop 1.7.8.7, the logo is not showing  on the invoice.
This is because prestashop is now returning the web path :
'logo_path' => Tools::getShopProtocol() . Tools::getMediaServer(_PS_IMG_) . _PS_IMG_ . $logo,
Instead of the img path
'logo_path' => _PS_IMG_ . $logo,

### Expected behavior

logo_path should be relative as before :
'logo_path' => _PS_IMG_ . $logo,

### Steps to reproduce

Display an invoice with logo
Logo is not showing (may be due to some server configuration, ovh shared hosting in that case)

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.3

**Comment by sallemiines** [comment]
Hello @arirangz 


We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #22581
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you
