### ISSUE TITLE
Overall Shop problems - Internal server error...

### ISSUE THREAD

**Issue by AndersSSNielsen** [PrestaShop/PrestaShop#30249]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

No confirmation email to customer after order.

Import data store configuration does not work when applied - 
![image](https://user-images.githubusercontent.com/112540252/200785116-4d8ebbef-5c36-4786-b0d7-b3a86d82d523.png)

When selecting "order accepted" in orders the error occurs:
![image](https://user-images.githubusercontent.com/112540252/200785481-39d363fc-012c-4a79-a2b1-5a40599ea3cd.png)

White screen after ordering items on shop as the last step -> No confirmation email, so the buyer thinks the order didn't go through. 

### Steps to reproduce

Let me know if you new additional info

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.0

**Comment by AndersSSNielsen** [comment]
Or do I have a general problem with the installation?

**Comment by AndersSSNielsen** [comment]
When I try to resend over confirmation I get the following error.

POST https://www.webshop.com/adminxyz/index.php/sell/orders/4/history/12/statuses/2/resend-email?_token=x1232132123123123 500

Is something wrong with the mailing system?

**Comment by HanaRebaiQA** [comment]
Hello @AndersSSNielsen 

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template and provide clear and concise steps to reproduce the bug**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/).

Also, could you please send your request, your screenshot, in English. English is the norm on GitHub.
 Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

I think it's a problem in your environment? Cause, id did not reproduce any error in Order page on PS8.0.0

Thank You!
