### ISSUE TITLE
FileNotFoundException The file "/tmp/php4WJ2D7" does not exist

### ISSUE THREAD

**Issue by augustomurri** [PrestaShop/PrestaShop#30259]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I have an external php script which recive an XML file (about 8.5MB) from the ERP  and update product quantities.
I get random 500 error like this i don't know why..
The same file already loaded into space doesn't retur nany error

it's an evident bug which is causing many problems

**FileNotFoundException The file "/tmp/php4WJ2D7" does not exist**

![image](https://user-images.githubusercontent.com/16515870/200921611-4a8f5b7c-4fe0-47ad-9634-885d4d0ed0d2.png)
![image](https://user-images.githubusercontent.com/16515870/200921673-c249ffd8-5455-4202-ba2c-5d4cc66431b5.png)

### Steps to reproduce

Create an external script a send a file to it, very difficult to debug

```
include dirname(__FILE__).'/../../config/config.inc.php';
include dirname(__FILE__).'/../../init.php';

//error_reporting(E_ERROR | E_WARNING | E_PARSE);

$filename = null;
if (!empty($_FILES['file'])) {
    $filename = "./articoli-danea/".time()."-articoli.xml";
    move_uploaded_file($_FILES['file']['tmp_name'], $filename);
}

//$filename = './articoli-danea/1668020425-articoli.xml';
if (!$filename && !file_exists($filename)) { exit; }

$xml = simplexml_load_file($filename);

if (!empty($xml->Products)) {
    $products = $xml->Products;
}

if (!empty($xml->UpdatedProducts)) {
    $products = $xml->UpdatedProducts;
}

// .... parse XML dom and update product quantities using StockAvailable::setQuantity
```

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @augustomurri ,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by augustomurri** [comment]
Upload works, only few times i get this strange error.
PHP vars, chown chgroup of /tmp directory seems ok (same user and group of php process)

![image](https://user-images.githubusercontent.com/16515870/201043880-d353216d-df95-4b9e-b437-2c5c57059d88.png)

**Comment by florine2623** [comment]
Thanks for the system info.

Have you try to clear your cache ? Do you still have the error after clearing the cache ?

**Comment by augustomurri** [comment]
Yes absolutely, the strange thing is it happens only on file upload
Using a static file already uploaded the process works well
very strange, same script (almost identical) worked without problems with the old PS.16

**Comment by florine2623** [comment]
Could you send me the exact steps to reproduce ?
The file you are using and where you are uploading it ?

If you can send a screen record of it that would be great.

**Comment by augustomurri** [comment]
Ok, where i can send privately? I need some 2-3 days

**Comment by florine2623** [comment]
You can contact me directly via Slack : prestashop.slack.com

**Comment by paulnoelcholot** [comment]
Hello @augustomurri ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Comment by Joaq82** [comment]
Hola, tengo el mismo problema! como se puede solucionar ?¿ no se pueden cargar imagenes en los productos,
FileNotFoundException El archivo "/tmp/php4WJ....

**Comment by GuillaumeKoeglerSeiler** [comment]
if this happens again, check that your ps_eventbus module is not in version 4.0.1. If it is, upgrade to 4.0.2 or higher, which will solve the problem.
