### ISSUE TITLE
Disabling a module in one shop will disable it in all shops

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#30262]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I find this regression while testing these PRs: #29516 & https://github.com/PrestaShop/classic-theme/pull/52 & https://github.com/PrestaShop/ps_contactinfo/pull/49 & https://github.com/PrestaShop/hummingbird/pull/366

Enable the multistore then go to Module Manager page, try to click on configure button of any module. 

1. You will find a trivial regression :smile: (see the strong tag displayed while it should not be displayed)
2. Now, uncheck the **Activate module for this shop context** option to disable the module for this store. Check all stores, you will see that the module is disabled for all shops not just the selected shop. (see the attached screenshot below)

 
![image](https://user-images.githubusercontent.com/23308427/201111629-448a2014-ca22-47cb-baed-36d77d3f86c5.png)

### Expected behavior

1. The strong tag should be displayed
2. The module should be disabled only in the selcted store

### Steps to reproduce

1. BO>CONFIGURE>Shop Parameters>General
2. Enable Multistore then Save
3. BO>CONFIGURE>Advanced Parameters>Multistore
4. Create a second store
5. BO>IMPROVE>Modules>Module Manager
6. Click on Configure button of ps_contactinfo module (for exemple)
7. In Configuration bloc
8. See error > the strong tag displayed
9. Uncheck the **Activate module for this shop context** option to disable the module for the selected shop
10. See error > Check all stores, you will see that the module is disabled for all shops not just the selected shop

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment]
Related to #24354

**Comment by florine2623** [comment]
Hello @hibatallahAouadni ,

I reproduce the issue with PrestaShop version 8.0.0, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by matthieu-rolland** [comment]
Pull request available here: https://github.com/PrestaShop/PrestaShop/pull/31379

**Comment by hibatallahAouadni** [comment]
Related to #29780

**Comment by jolelievre** [comment]
It may also be the same bug as in this issue https://github.com/PrestaShop/PrestaShop/issues/32211
