### ISSUE TITLE
Product listing performance

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#30286]
### Required fields
Following product data is required by default themes on every listing. We should fetch them all in one query if possible. All others should be lazyloaded.

```
$product.id_product
$product.id_product_attribute
product.name
$product.url
$product.cover
$product.main_variants
$product.show_price
$product.has_discount
$product.discount_type
$product.discount_percentage
$product.discount_amount_to_display
$product.regular_price
$product.price
$product.flags
```

### How it works currently.
- In `ProductListingFrontController`, there is a list of product IDs.
- They are sent to `ProductAssembler` which fetches all data from `product` and `product_shop` tables.
- Then, for each of the enriched data, it calls `Product::getProductProperties`. One by one.
- Then, it get's passed to `ProductLazyArray`, which enables us to lazy load the requested data, only when used by the template.

### ✅ Problem 1 - ProductAssembler - DONE
Product assembler is called for each product one by one, thus making 24 database queries instead of only one.
We can make it one query here - https://github.com/PrestaShop/PrestaShop/pull/30234.
About 3% page speed improvement.

### Problem 2 - getProductProperties and lazy array
We must move as many things away (all if possible) away from this function, as it's called one by one for each product.

There is a lot of duplicated queries that are easy wins:
 - `getCover` - 24 requests to image table to get product cover. Could be fetched in product assembler.
 - `Category::getLinkRewrite` for category - 24 requests to category table to get default category rewrite. Could be fetched in product assembler.
 - category_name - 24 requests to category_lang table to get category name. Could be fetched in product assembler.
 - manufacturer_name - 24 requests to category_lang table to get category name. Could be fetched in product assembler.

There are queries that could be lazy loaded in lazyarray so they are fetched only when needed:
- 24 requests for product image table, again. This is only needed when a template displays a second image on hover and requests a key from the images array.
- 24 requests to feature table. This should be lazyloaded. Features are not displayed in listing by default.

If these are solved, average load time 207 ➡️ 174 = 16% improvement, DB query count 508 ➡️332.

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. 
So, we're waiting for your PR 🚀  

Thank you

**Comment by Hlavtox** [comment]
Fixed what I could
