### ISSUE TITLE
There is no image type defined for "products". at line 303 in file src/Adapter/Image/ImageRetriever.php after installation

### ISSUE THREAD

**Issue by anothersailor** [PrestaShop/PrestaShop#30287]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Error when installing with the script /install-dev/index.php, and when switching to the Shop.
Same error when accessing most administration pages (although not the home page).

Installed on OSX by cloning the 8.0x repo, with PHP 7.2

[PrestaShopException]

There is no image type defined for "products".
at line 303 in file src/Adapter/Image/ImageRetriever.php

298.         $urls = [];
299.         $type = 'products';
300.         $imageTypes = ImageType::getImagesTypes($type, true);
301. 
302.         if (empty($imageTypes)) {
303.             throw new PrestaShopException(sprintf('There is no image type defined for "%s".', $type));
304.         }
305. 
306.         foreach ($imageTypes as $imageType) {
307.             $url = $this->link->getImageLink(
308.                 '',
PrestaShop\PrestaShop\Adapter\Image\ImageRetriever->getNoPictureImage - [line 1515 - classes/controller/FrontController.php] - [1 Arguments]
FrontControllerCore->getTemplateVarUrls - [line 1641 - classes/controller/FrontController.php]
FrontControllerCore->getTemplateVarShop - [line 493 - classes/controller/FrontController.php]
FrontControllerCore->assignGeneralPurposeVariables - [line 555 - classes/controller/FrontController.php]
FrontControllerCore->initContent - [line 38 - controllers/front/IndexController.php]
IndexControllerCore->initContent - [line 319 - classes/controller/Controller.php]
ControllerCore->run - [line 503 - classes/Dispatcher.php]
DispatcherCore->dispatch - [line 28 - index.php]

### Steps to reproduce

Install, wait for installation procedure to finish successfully, wait for the installer welcome screen to appear, click on "découvrez votre boutique".

### PrestaShop version(s) where the bug happened

8.0x

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @anothersailor 

I didn't manage to reproduce the issue with the provided infos.
Could you please provide a screen record while re-installing the shop.
Waiting for your feedback.

Thanks!

**Comment by anothersailor** [comment]
Here is a screenshot of the same issue (when connecting to the shop homepage after the install finished successfully), but this time after installing with the "standard" installer: i.e. by launching the Prestashop/index.php installer immediately after cloning the 8.0.x repo & doing the composer install. Same happens with the Prestashop /install-dev/index.php installer.

![SCR-20221114-kmk](https://user-images.githubusercontent.com/32575567/201677627-4bc001f9-d1ac-4178-ba4c-33c3d8462652.png)

Config is OS X Venture, with Chrome or Safari (both), with php@7.4 served by nginx with Valet.

E.

**Comment by hibatallahAouadni** [comment]
Hello @anothersailor 

It seems that you forget to execute the command:
`make install`
Try to execute this command and then install your shop.
Please check and feedback.

Thanks!

**Comment by anothersailor** [comment]
Indeed I have. Will try and let you know.
I had understood that the non-dev install would load the built files, but that was an assumption.

Many thanks,
Cheers,
Eric

Eric Janvier
+33 6 80 94 14 45
***@***.***

**Comment by PrestaEdit** [comment]
Same issue as this one : https://github.com/PrestaShop/PrestaShop/issues/30000

**Comment by anothersailor** [comment]
The build fails (see attached log file).

That said, my error was a PHP error, so I would have thought it would have been independent of the build. Mut I am probably wrong.


Eric % gh repo clone PrestaShop/PrestaShop
Cloning into 'PrestaShop'...
remote: Enumerating objects: 859535, done.
remote: Counting objects: 100% (367/367), done.
remote: Compressing objects: 100% (294/294), done.
remote: Total 859535 (delta 127), reused 193 (delta 69), pack-reused 859168
Receiving objects: 100% (859535/859535), 510.46 MiB | 24.98 MiB/s, done.
Resolving deltas: 100% (593504/593504), done.
Updating files: 100% (13040/13040), done.
Eric@macbook_eric_wifi VraimentBeau % cd Prestashop

Eric@macbook_eric_wifi Prestashop % composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 213 installs, 0 updates, 0 removals
  - Installing composer/installers (v1.12.0): Extracting archive
  - Installing localheinz/diff (1.1.1): Extracting archive
  - Installing justinrainbow/json-schema (5.2.12): Extracting archive
  - Installing ergebnis/json-printer (3.1.1): Extracting archive
  - Installing ergebnis/json-normalizer (1.0.3): Extracting archive
  - Installing ergebnis/composer-normalize (2.13.3): Extracting archive
  - Installing symfony/polyfill-php80 (v1.26.0): Extracting archive
  - Installing symfony/polyfill-php72 (v1.26.0): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.26.0): Extracting archive
  - Installing symfony/polyfill-ctype (v1.25.0): Extracting archive
  - Installing twig/twig (v3.4.3): Extracting archive
  - Installing symfony/polyfill-php81 (v1.26.0): Extracting archive
  - Installing symfony/polyfill-php73 (v1.25.0): Extracting archive
  - Installing symfony/polyfill-intl-normalizer (v1.25.0): Extracting archive
  - Installing symfony/polyfill-intl-idn (v1.25.0): Extracting archive
  - Installing symfony/polyfill-intl-icu (v1.25.0): Extracting archive
  - Installing psr/container (1.1.1): Extracting archive
  - Installing psr/cache (1.0.1): Extracting archive
  - Installing symfony/contracts (v1.1.12): Extracting archive
  - Installing psr/log (1.1.4): Extracting archive
  - Installing psr/link (1.0.0): Extracting archive
  - Installing symfony/symfony (v4.4.44): Extracting archive
  - Installing prestashop/laminas-code-lts (dev-4.5-lts 3dbe7f7): Extracting archive
  - Installing friendsofphp/proxy-manager-lts (v1.0.10): Extracting archive
  - Installing doctrine/event-manager (1.1.1): Extracting archive
  - Installing doctrine/collections (1.6.8): Extracting archive
  - Installing doctrine/persistence (3.0.0): Extracting archive
  - Installing doctrine/lexer (1.2.3): Extracting archive
  - Installing doctrine/instantiator (1.4.1): Extracting archive
  - Installing doctrine/inflector (2.0.4): Extracting archive
  - Installing doctrine/deprecations (v0.5.3): Extracting archive
  - Installing doctrine/cache (2.1.1): Extracting archive
  - Installing doctrine/dbal (2.13.8): Extracting archive
  - Installing doctrine/common (3.3.0): Extracting archive
  - Installing doctrine/orm (2.12.1): Extracting archive
  - Installing beberlei/doctrineextensions (v1.3.0): Extracting archive
  - Installing behat/transliterator (v1.5.0): Extracting archive
  - Installing behat/gherkin (v4.9.0): Extracting archive
  - Installing behat/behat (v3.10.0): Extracting archive
  - Installing bjeavons/zxcvbn-php (1.3.1): Extracting archive
  - Installing composer/pcre (1.0.1): Extracting archive
  - Installing cssjanus/cssjanus (v2.1.0): Extracting archive
  - Installing curl/curl (2.3.3): Extracting archive
  - Installing paragonie/random_compat (v9.99.100): Extracting archive
  - Installing defuse/php-encryption (v2.3.1): Extracting archive
  - Installing symfony/deprecation-contracts (v2.5.1): Extracting archive
  - Installing doctrine/sql-formatter (1.1.2): Extracting archive
  - Installing doctrine/annotations (1.13.3): Extracting archive
  - Installing doctrine/doctrine-bundle (2.6.3): Extracting archive
  - Installing egulias/email-validator (3.1.2): Extracting archive
  - Installing php-cs-fixer/diff (v2.0.2): Extracting archive
  - Installing composer/xdebug-handler (2.0.5): Extracting archive
  - Installing composer/semver (3.3.2): Extracting archive
  - Installing friendsofphp/php-cs-fixer (v3.4.0): Extracting archive
  - Installing willdurand/jsonp-callback-validator (v1.1.0): Extracting archive
  - Installing friendsofsymfony/jsrouting-bundle (2.8.0): Extracting archive
  - Installing composer/ca-bundle (1.3.1): Extracting archive
  - Installing maxmind/web-service-common (v0.9.0): Extracting archive
  - Installing maxmind-db/reader (v1.11.0): Extracting archive
  - Installing geoip2/geoip2 (v2.4.5): Extracting archive
  - Installing greenlion/php-sql-parser (v4.5.0): Extracting archive
  - Installing psr/http-message (1.0.1): Extracting archive
  - Installing psr/http-client (1.0.1): Extracting archive
  - Installing ralouphie/getallheaders (3.0.3): Extracting archive
  - Installing psr/http-factory (1.0.1): Extracting archive
  - Installing guzzlehttp/psr7 (2.4.1): Extracting archive
  - Installing guzzlehttp/promises (1.5.1): Extracting archive
  - Installing guzzlehttp/guzzle (7.5.0): Extracting archive
  - Installing incenteev/composer-parameter-handler (v2.1.4): Extracting archive
  - Installing ircmaxell/password-compat (v1.0.4): Extracting archive
  - Installing ircmaxell/security-lib (v1.1.0): Extracting archive
  - Installing ircmaxell/random-lib (v1.2.0): Extracting archive
  - Installing sebastian/version (2.0.1): Extracting archive
  - Installing sebastian/type (1.1.4): Extracting archive
  - Installing sebastian/resource-operations (2.0.2): Extracting archive
  - Installing sebastian/recursion-context (3.0.1): Extracting archive
  - Installing sebastian/object-reflector (1.1.2): Extracting archive
  - Installing sebastian/object-enumerator (3.0.4): Extracting archive
  - Installing sebastian/global-state (3.0.2): Extracting archive
  - Installing sebastian/exporter (3.1.4): Extracting archive
  - Installing sebastian/environment (4.2.4): Extracting archive
  - Installing sebastian/diff (3.0.3): Extracting archive
  - Installing sebastian/comparator (3.0.3): Extracting archive
  - Installing phpunit/php-timer (2.1.3): Extracting archive
  - Installing phpunit/php-text-template (1.2.1): Extracting archive
  - Installing phpunit/php-file-iterator (2.0.5): Extracting archive
  - Installing theseer/tokenizer (1.2.1): Extracting archive
  - Installing sebastian/code-unit-reverse-lookup (1.0.2): Extracting archive
  - Installing phpunit/php-token-stream (3.1.3): Extracting archive
  - Installing phpunit/php-code-coverage (7.0.15): Extracting archive
  - Installing webmozart/assert (1.10.0): Extracting archive
  - Installing phpdocumentor/reflection-common (2.2.0): Extracting archive
  - Installing phpdocumentor/type-resolver (1.6.1): Extracting archive
  - Installing phpdocumentor/reflection-docblock (5.3.0): Extracting archive
  - Installing phpspec/prophecy (v1.15.0): Extracting archive
  - Installing phar-io/version (3.2.1): Extracting archive
  - Installing phar-io/manifest (2.0.3): Extracting archive
  - Installing myclabs/deep-copy (1.11.0): Extracting archive
  - Installing phpunit/phpunit (8.5.26): Extracting archive
  - Installing johnkary/phpunit-speedtrap (v3.3.0): Extracting archive
  - Installing league/tactician (v1.1.0): Extracting archive
  - Installing league/tactician-logger (v0.10.0): Extracting archive
  - Installing league/tactician-container (2.0.0): Extracting archive
  - Installing league/tactician-bundle (v1.3.2): Extracting archive
  - Installing martinlindhe/php-mb-helpers (0.1.7): Extracting archive
  - Installing matthiasmullie/path-converter (1.1.3): Extracting archive
  - Installing matthiasmullie/minify (1.3.68): Extracting archive
  - Installing mikey179/vfsstream (v1.6.10): Extracting archive
  - Installing mobiledetect/mobiledetectlib (2.8.39): Extracting archive
  - Installing tubalmartin/cssmin (v4.1.1): Extracting archive
  - Installing pimple/pimple (v3.5.0): Extracting archive
  - Installing mrclay/props-dic (3.0.0): Extracting archive
  - Installing mrclay/jsmin-php (2.4.1): Extracting archive
  - Installing monolog/monolog (1.27.0): Extracting archive
  - Installing marcusschwarz/lesserphp (v0.5.5): Extracting archive
  - Installing intervention/httpauth (3.0.1): Extracting archive
  - Installing mrclay/minify (3.0.11): Extracting archive
  - Installing myclabs/php-enum (1.7.7): Extracting archive
  - Installing pear/pear_exception (v1.0.2): Extracting archive
  - Installing pear/console_getopt (v1.4.3): Extracting archive
  - Installing pear/pear-core-minimal (v1.10.11): Extracting archive
  - Installing pear/archive_tar (1.4.14): Extracting archive
  - Installing pelago/emogrifier (v5.0.1): Extracting archive
  - Installing psr/simple-cache (1.0.1): Extracting archive
  - Installing markbaker/matrix (3.0.0): Extracting archive
  - Installing markbaker/complex (3.0.1): Extracting archive
  - Installing maennchen/zipstream-php (2.1.0): Extracting archive
  - Installing ezyang/htmlpurifier (dev-master 1dd3e52): Extracting archive
  - Installing symfony/polyfill-iconv (v1.25.0): Extracting archive
  - Installing phpoffice/phpspreadsheet (1.19.0): Extracting archive
  - Installing prestashop/blockreassurance (v5.1.1): Extracting archive
  - Installing prestashop/blockwishlist (v2.1.2): Extracting archive
  - Installing prestashop/classic (2.0.6): Extracting archive
  - Installing jakeasmith/http_build_url (1.0.1): Extracting archive
  - Installing prestashop/contactform (v4.3.0): Extracting archive
  - Installing prestashop/dashactivity (v2.0.2): Extracting archive
  - Installing prestashop/dashgoals (v2.0.2): Extracting archive
  - Installing prestashop/dashproducts (v2.1.1): Extracting archive
  - Installing prestashop/dashtrends (v2.0.3): Extracting archive
  - Installing prestashop/decimal (1.5.0): Extracting archive
  - Installing prestashop/graphnvd3 (v2.0.2): Extracting archive
  - Installing prestashop/gridhtml (v2.0.2): Extracting archive
  - Installing prestashop/gsitemap (v4.2.0): Extracting archive
  - Installing prestashop/pagesnotfound (v2.0.2): Extracting archive
  - Installing phpstan/phpstan (1.8.11): Extracting archive
  - Installing prestashop/phpstan-prestashop (2.0.0): Extracting archive
  - Installing prestashop/productcomments (v5.0.2): Extracting archive
  - Installing prestashop/ps_banner (v2.1.2): Extracting archive
  - Installing prestashop/ps_bestsellers (v1.0.3): Extracting archive
  - Installing prestashop/ps_brandlist (v1.0.3): Extracting archive
  - Installing prestashop/ps_cashondelivery (v2.0.1): Extracting archive
  - Installing prestashop/ps_categoryproducts (v1.0.4): Extracting archive
  - Installing prestashop/ps_categorytree (v2.0.2): Extracting archive
  - Installing prestashop/ps_checkpayment (v2.0.5): Extracting archive
  - Installing prestashop/ps_contactinfo (v3.3.0): Extracting archive
  - Installing prestashop/ps_crossselling (v2.0.1): Extracting archive
  - Installing prestashop/ps_currencyselector (v2.0.1): Extracting archive
  - Installing prestashop/ps_customeraccountlinks (v3.1.1): Extracting archive
  - Installing prestashop/ps_customersignin (v2.0.5): Extracting archive
  - Installing prestashop/ps_customtext (v4.2.0): Extracting archive
  - Installing prestashop/ps_dataprivacy (v2.1.0): Extracting archive
  - Installing prestashop/circuit-breaker (v4.0.1): Extracting archive
  - Installing prestashop/ps_distributionapiclient (v1.0.2): Extracting archive
  - Installing prestashop/ps_emailalerts (v2.3.3): Extracting archive
  - Installing prestashop/ps_emailsubscription (v2.7.0): Extracting archive
  - Installing prestashop/ps_facetedsearch (v3.8.0): Extracting archive
  - Installing prestashop/ps_faviconnotificationbo (v2.1.1): Extracting archive
  - Installing prestashop/ps_featuredproducts (v2.1.2): Extracting archive
  - Installing prestashop/ps_googleanalytics (v4.1.2): Extracting archive
  - Installing prestashop/ps_imageslider (v3.1.1): Extracting archive
  - Installing prestashop/ps_languageselector (v2.1.0): Extracting archive
  - Installing prestashop/ps_linklist (v5.0.5): Extracting archive
  - Installing prestashop/ps_mainmenu (v2.3.1): Extracting archive
  - Installing prestashop/ps_newproducts (v1.0.1): Extracting archive
  - Installing prestashop/ps_searchbar (v2.1.3): Extracting archive
  - Installing prestashop/ps_sharebuttons (v2.1.1): Extracting archive
  - Installing prestashop/ps_shoppingcart (v2.0.5): Extracting archive
  - Installing prestashop/ps_socialfollow (v2.2.0): Extracting archive
  - Installing prestashop/ps_specials (v1.0.1): Extracting archive
  - Installing prestashop/ps_supplierlist (v1.0.4): Extracting archive
  - Installing prestashop/ps_themecusto (v1.2.1): Extracting archive
  - Installing prestashop/ps_viewedproduct (v1.2.2): Extracting archive
  - Installing prestashop/ps_wirepayment (v2.1.3): Extracting archive
  - Installing prestashop/psgdpr (v1.4.2): Extracting archive
  - Installing prestashop/statsbestcategories (v2.0.1): Extracting archive
  - Installing prestashop/statsbestcustomers (v2.0.3): Extracting archive
  - Installing prestashop/statsbestmanufacturers (v2.0.0): Extracting archive
  - Installing prestashop/statsbestproducts (v2.0.1): Extracting archive
  - Installing prestashop/statsbestsuppliers (v2.0.0): Extracting archive
  - Installing prestashop/statsbestvouchers (v2.0.1): Extracting archive
  - Installing prestashop/statscarrier (v2.0.1): Extracting archive
  - Installing prestashop/statscatalog (v2.0.2): Extracting archive
  - Installing prestashop/statscheckup (v2.0.2): Extracting archive
  - Installing prestashop/statsdata (v2.1.0): Extracting archive
  - Installing prestashop/statsforecast (v2.0.4): Extracting archive
  - Installing prestashop/statsnewsletter (v2.0.3): Extracting archive
  - Installing prestashop/statspersonalinfos (v2.0.4): Extracting archive
  - Installing prestashop/statsproduct (v2.1.1): Extracting archive
  - Installing prestashop/statsregistrations (v2.0.1): Extracting archive
  - Installing prestashop/statssales (v2.1.0): Extracting archive
  - Installing prestashop/statssearch (v2.0.2): Extracting archive
  - Installing prestashop/statsstock (v2.0.0): Extracting archive
  - Installing smarty/smarty (v4.2.1): Extracting archive
  - Installing nikic/php-parser (v4.13.2): Extracting archive
  - Installing prestashop/translationtools-bundle (v5.0.4): Extracting archive
  - Installing sensio/framework-extra-bundle (v5.6.1): Extracting archive
  - Installing soundasleep/html2text (0.5.0): Extracting archive
  - Installing symfony/monolog-bundle (v3.7.1): Extracting archive
  - Installing symfony/phpunit-bridge (v3.4.47): Extracting archive
  - Installing swiftmailer/swiftmailer (v6.3.0): Extracting archive
  - Installing symfony/swiftmailer-bundle (v3.5.4): Extracting archive
  - Installing tecnickcom/tcpdf (6.4.4): Extracting archive
  - Installing tijsverkoyen/css-to-inline-styles (2.2.4): Extracting archive
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package symfony/swiftmailer-bundle is abandoned, you should avoid using it. Use symfony/mailer instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files

Eric % make assets >> log_build_prestashop.txt
(... See attached log file, below)
[2022-11-14T18_06_43_055Z-debug-0.log](https://github.com/PrestaShop/PrestaShop/files/10005930/2022-11-14T18_06_43_055Z-debug-0.log)
npm ERR! Build failed with error code: 1
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Eric/.npm/_logs/2022-11-14T18_06_43_055Z-debug-0.log
make: *** [assets] Error 1

**Comment by AureRita** [comment]
Hi @anothersailor 

Can you give us the current version that you use for nvm ? you maybe use a version too recent (just in cas, to know it, use 
`nvm current`)

Waiting for your feedback

**Comment by Hlavtox** [comment]
I think you installed Prestashop without a valid built theme.

**Comment by anothersailor** [comment]
Thanks for the tip. Will try better!Best,EricEric Janvier+33 6 80 94 14 45 Le 15 nov. 2022 à 13:47, Daniel Hlavacek ***@***.***> a écrit :﻿
I think you installed Prestashop without a valid built theme.

**Comment by AureRita** [comment]
Tell us when you got some new details, 

Waiting for your feedback

**Comment by anothersailor** [comment]
Dear A.

I am going to abandon the idea of installing version 8.0 from the GIT.

Can’t build the assets however I try to follow the instructions.

Apologies for the disturbance and thanks for trying to help,
E.

Eric Janvier
+33 6 80 94 14 45
***@***.***

**Comment by Hlavtox** [comment]
@anothersailor Use this ZIP and it will work perfectly 👍 
https://github.com/PrestaShop/PrestaShop/releases/download/8.0.0/prestashop_8.0.0.zip

**Comment by anothersailor** [comment]
Thanks.Installation works, but it installs tge User rather than the Dev version. And the admin pages send me to the store, so configuration is impossible.I will wait for 8.1. There is no urgency.Thanks anyway for caring!E.Eric Janvier+33 6 80 94 14 45 Le 15 nov. 2022 à 20:19, Daniel Hlavacek ***@***.***> a écrit :﻿
@anothersailor Use this ZIP and it will work perfectly 👍
https://github.com/PrestaShop/PrestaShop/releases/download/8.0.0/prestashop_8.0.0.zip

**Comment by HanaRebaiQA** [comment]
Hello, 

Glad to know that the installation works fine now. 
I'll close the issue. 

Thank You!

**Comment by zuk3975** [comment]
Im still getting this error everytime i reinstall my shop locally for development (current develop branch). I must always hardcode those default types into database, because installation doesn't seem to add them by default

**Comment by Hlavtox** [comment]
@zuk3975 Are you sure you have built and valid theme assets when installing?
