### ISSUE TITLE
Generation of nightlies is broken on `develop` branch

### ISSUE THREAD

**Issue by Quetzacoalt91** [PrestaShop/PrestaShop#30285]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Docker image `prestashop/prestashop:nightly` cannot start properly at the moment, because there is no nightly release to download and install.

It seems the workflow generating these images is broken for 17 days, and the bucket storing the artifacts has an automatic cleaning process that removes files older than 15(?) days.

### Steps to reproduce

* Run `php tools/build/CreateRelease.php --destination-dir=/tmp/ps-release` from the root folder of PrestaShop
* The version won't be found and the generation will fail.

### PrestaShop version(s) where the bug happened

8.0.0 (Nightly)

**Comment by hibatallahAouadni** [comment]
Hello @Quetzacoalt91 

Thanks for reporting the issue and the PR 🚀 
It's a regression on develop branch!

Thanks!
