### ISSUE TITLE
Handle missing parts for combination mutlishop behavior in product v2

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#30304]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Raised from comment https://github.com/PrestaShop/PrestaShop/pull/28395#pullrequestreview-1180582781

### Describe the solution you'd like

.... few things need to be handled in another PR as soon as this one is merged, here's the list:
- [x] `SetDefaultCombinationCommand` needs to have a shop constraint instead of relying on the Context, plus behat tests including scenarios for allShops (PR available https://github.com/PrestaShop/PrestaShop/pull/30320)
- [x] `GenerateProductCombinationsCommand` needs to handle the allShops case (https://github.com/PrestaShop/PrestaShop/pull/30421)
- [x] `DeleteCombinationCommand` needs to handle the allShops case, and should rely on `AbstractMultiShopObjectModelRepository::deleteObjectModelFromShops` (https://github.com/PrestaShop/PrestaShop/pull/30421)
- [x] same for `BulkDeleteCombinationCommand` (https://github.com/PrestaShop/PrestaShop/pull/30421)
- [x] replace hardcoded shop constraint with the one from command when its implemented in UpdateCombinationHandler

Then once all the commands/queries are ready we will have to finish the integration in the form that you started (probably in another PR), we still need to validate the expected behaviour with @MatShir but among which:
- [x] add `Generate for all shops` checkbox in the generation modal (https://github.com/PrestaShop/PrestaShop/pull/30559)
- [x] handle `Delete for shop` and `Delete for all shops` buttons (https://github.com/PrestaShop/PrestaShop/pull/30793)
- [x] handle `Set default` multishop compatible (https://github.com/PrestaShop/PrestaShop/pull/30538)

That's when we'll ask for a functional QA centered on combination generation/association/removals (the edition won't be ready yet).

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by sallemiines** [comment]
Hello @zuk3975 ,

Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments.
Please be aware that there is no guarantee that this feature will be developed anytime soon.
So, we're waiting for your PR rocket

Thank you !

**Comment by zuk3975** [comment]
there are still some points left for form (it was probably automatic close). Reopening.
