### ISSUE TITLE
psgdpr module: jQuery error 

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#30306]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Sometimes a jQuery error is thrown because the code is executed before than the jQuery library is loaded:

![image](https://user-images.githubusercontent.com/15104724/202214610-62fdb8c1-78a0-490f-baa8-37eac9372f05.png)

This script rely on `document.addEventListener('DOMContentLoaded', function() {` but it's possible that this event is fired before than the jQuery library is fully loaded.

### Expected behavior

Execution without error.

### Steps to reproduce

Unfortunately it's not reproducible but it's logic.

The bug is collected by sentry.io.

### PrestaShop version(s) where the bug happened

1.7.8.7

### If your bug is related to a module, specify its name and its version

psgdpr v1.4.2

**Comment by sallemiines** [comment]
Hello @idnovate 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a connection problem.

We will close this issue.

Thank you
