### ISSUE TITLE
A HTTP 500 internal server error in BO > Orders > Credit slips page

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#30302]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An exception is displayed in BO > Orders > Credit slips page
![Capture d’écran de 2022-11-16 10-51-25](https://user-images.githubusercontent.com/24647495/202153340-dc54472d-d8cd-45a9-9773-aa800af6f1b3.png)

### Expected behavior

The page BO > Orders > Credit slips page should be displayed correctly

### Steps to reproduce

1. Go to BO and login
2. Go to Orders > Credit slips page
=> See the exception

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.3

**Comment by sallemiines** [comment]
Hello @nesrineabdmouleh,

Thanks for reporting the issue  ! 

I reproduce the issue only with `PS80x` , So it's a regression ! 

Thank you ! :rocket:
