### ISSUE TITLE
500 Server Error while using backoffice

### ISSUE THREAD

**Issue by srunow** [PrestaShop/PrestaShop#30300]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

![Screenshot_20221116_011716](https://user-images.githubusercontent.com/102793168/202052280-dc31c60f-017d-4d2b-9ba2-1067fc9d13ec.jpg)

This is only shown when debug mode is activated. Otherwise there is only a simple page with a non specific 500 error shown.

### Expected behavior

It's expected to work properly. Otherwise this PrestaShop release is not fully usable.

### Steps to reproduce

1. Go to Backoffice
2. Select 'Design' item in side menu
3. Click on 'Template and Logo' subitem
4. Click on 'Pages configuration' tab
-> 500 occurs

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

Seems to be a problem with `ps_themecusto`. A lot of modules has been uninstalled, but no module was added so far.

**Comment by sallemiines** [comment]
Hello @srunow 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #27384 .
The issue is already fixed with this [PR-47](https://github.com/PrestaShop/ps_themecusto/pull/47) , but the new version **1.2.2** of the module **ps_themecusto** it's not released yet ! 
 
Thank you !

**Comment by sallemiines** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/27384 .
