### ISSUE TITLE
Missing equal sign

### ISSUE THREAD

**Issue by Stirlitz-on-GIT** [PrestaShop/PrestaShop#30307]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Only one equal sign in "if" statement:
                                if ($moduleId = Module::getModuleIdByName($carrier['external_module_name'])) {                          
 In DeliveryOptionsFinderCore class, line #127.All version of Presta affected.

### Steps to reproduce

See the source.....

### PrestaShop version(s) where the bug happened

1.7.8.7

**Comment by Stirlitz-on-GIT** [comment]
Ok, I see....sry

**Comment by sallemiines** [comment]
Hello,

Could you please provide us with more info ?
We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
- ...

You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

Thank you
