### ISSUE TITLE
{url} helper generate the manufacturer url without rewrite rules

### ISSUE THREAD

**Issue by PrestaSafe** [PrestaShop/PrestaShop#30313]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello, 

The `{url}` helper in smarty generate the URL of manufacturer without rewriting url:
ex:
`{url entity='manufacturer' id=1}`
will ouput: 
`//prestashop:8888/brands?id_manufacturer=1`

If we use the `$link` class it works fine: 
`{$link->getManufacturerLink(1)}`
will output: 
`http://prestashop:8888/brand/1-studio-design`

### Expected behavior

`{url entity='manufacturer' id=1}` should be return the same result of `{$link->getManufacturerLink(1)}` (without the http(s))

### Steps to reproduce

For testing: 
Edit file: themes/classic/templates/index.tpl
put this code:

```
{**
 * Copyright since 2007 PrestaShop SA and Contributors
 * PrestaShop is an International Registered Trademark & Property of PrestaShop SA
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License 3.0 (AFL-3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/AFL-3.0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@prestashop.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
 * versions in the future. If you wish to customize PrestaShop for your
 * needs please refer to https://devdocs.prestashop.com/ for more information.
 *
 * @author    PrestaShop SA and Contributors <contact@prestashop.com>
 * @copyright Since 2007 PrestaShop SA and Contributors
 * @license   https://opensource.org/licenses/AFL-3.0 Academic Free License 3.0 (AFL-3.0)
 *}
{extends file='page.tpl'}

    {block name='page_content_container'}
      <section id="content" class="page-home">
        {block name='page_content_top'}{/block}

        {block name='page_content'}
          {block name='hook_home'}
            {* Wrong url *}
            {url entity='manufacturer' id=1}
            <br>
            {* Good url *}
            {$link->getManufacturerLink(1)}
            {$HOOK_HOME nofilter}
          {/block}
        {/block}
      </section>
    {/block}

```

Then empty the smarty cache

Go to the home page of your shop, you will see the url displayed: 
<img width="1356" alt="Capture d’écran 2022-11-17 à 09 25 51" src="https://user-images.githubusercontent.com/4788787/202394633-7725c81a-0b2f-4b64-b59c-c4dc38290d8e.png">

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1.1

**Comment by PrestaEdit** [comment]
The same with the supplier, too.

**Comment by PrestaEdit** [comment]
Also reproduce into 1.7.8.7 there.

**Comment by PrestaSafe** [comment]
Pr: https://github.com/PrestaShop/PrestaShop/pull/30314

**Comment by HanaRebaiQA** [comment]
Hello @PrestaSafe 

Thanks for your report.
I was able to reproduce your issue using the same steps to reproduce on **PS1778**, **PS1787** and **PS8.0.0** with **php8.1** (for PS8.00) and **php7.3**

**PS1778 with php7.3 : NOK** :x:

**Comment by HanaRebaiQA** [comment]
Hello @PrestaSafe 

Thanks for your report.
I was able to reproduce your issue using the same steps to reproduce on **PS1778**, **PS1787** and **PS8.0.0** with **php8.1** (for PS8.00) and **php7.3**

**PS1778 with php7.3 : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/202427254-d3e1d292-8bab-4c0a-8838-feae8184a118.png)

**PS1787 with php7.3 : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/202427305-a634cc6d-09cd-4a5f-9232-264ff8aa32fe.png)

**PS8.0.0 with php7.3 : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/202427340-90c80dea-c792-4a84-addd-9be053578806.png)

Indeed, it's not a regression.

I'll add this to the debug backlog so that it's fixed. And, thanks for your PR.

Thank You!
