### ISSUE TITLE
Attribute addition problem!

### ISSUE THREAD

**Issue by aytekinazmi12** [PrestaShop/PrestaShop#30319]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

Attributes after the first added attribute cannot be displayed on our website and demo site.

### Expected behavior

I need help.

### Steps to reproduce

BO Ss:

https://prnt.sc/aQZxv1AJZyA0

FO Ss:

https://prnt.sc/Gg-yMZmHXY77

### PrestaShop version(s) where the bug happened

1.7.8.4 and 1.7.8.7

### PHP version(s) where the bug happened

7.4

**Comment by Hlavtox** [comment]
@aytekinazmi12 Your combination are configured wrong. You have one combination with only color and one combination with only size.

Read user guide and or see how it's done with demo data. 👍 
https://docs.prestashop-project.org/1.7-documentation/user-guide/selling/managing-catalog/managing-products#managingproducts-creatingaproductwithcombinations

**Comment by aytekinazmi12** [comment]
> @aytekinazmi12 Your combination are configured wrong. You have one combination with only color and one combination with only size.
> 
> Read user guide and or see how it's done with demo data. 👍 https://docs.prestashop-project.org/1.7-documentation/user-guide/selling/managing-catalog/managing-products#managingproducts-creatingaproductwithcombinations

Thank you for your reply..

I added others combination but problem continues

https://prnt.sc/Jc5sfFIdeQmi
https://prnt.sc/l3o4r0vpPXcB

If you want check;

https://test.prestashopmodul.com/Backoffice/
info@eticsoft.com
mL8yK!j57R

**Comment by Hlavtox** [comment]
@aytekinazmi12 You didn't read the article I sent you. You would see how it's done. :-)
I fixed it for you, but it would be enough if you checked your other product, how they are done.

We will close this because this is not a help channel. 👍

**Comment by aytekinazmi12** [comment]
@Hlavtox Im so sorry. Thanks a lot :)
