### ISSUE TITLE
jQuery not found after server change

### ISSUE THREAD

**Issue by 21mac** [PrestaShop/PrestaShop#30318]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After I moved my prestashop from one hoster/server to another, jQuery can't be found in the front- and backend of my webshop (screenshots follow in a second).
Because of that, bootstrap and many javascripts don't work properly and my front- and backend look miserable and most functions do not work.

Note: the domain changed
www.bavariafishing.com --> www.bavaria-fishing.com

The folder structure did not change on the new server.

![BF1](https://user-images.githubusercontent.com/21278627/202445679-4e56267e-4e0c-404e-8624-9e898e219948.png)

### Steps to reproduce

1. Moved my files via FTP to a new server (same PHP version)
2. Exported the database and imported it on the new server (same mysql-version)
3. Change the database connection in the "parameters.php" file
4. changed the shop URL and SSL url in table "ps_shop_url"
5. Deleted the cache from the backend and also manually via FTP tool "filezilla" (var/cache)
6. Dis- and enabled the "user/seo friendly url" feature, regenerated htaccess-files
7. Enabled the DEV mode --> no further error is thrown. Just like before, jQuery is missing (via DEV Tools -> console)

### PrestaShop version(s) where the bug happened

1.7.8

### PHP version(s) where the bug happened

7.4

**Comment by 21mac** [comment]
Update: I got help by a member of the prestashop community but we did not manage to get jquery to load.
since the backend was broken I could not use the "1 click upgrade" feature.
I downloaded the version 1.7.8.7 and copied all files over my files (version 1.7.8.0) and now it works like a charm.

Issue closed

**Comment by HanaRebaiQA** [comment]
Hello @21mac 

Glad to know that! Do not hesitate to open new tickets when needed.

Thank You!
