### ISSUE TITLE
Product Page V1 - Possible to add product to cart when 'Deny orders' and 'Allow ordering of out-of-stock products' are enabled

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#30312]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Firstly reported here : https://github.com/PrestaShop/PrestaShop/pull/29132#pullrequestreview-1174177288

I can always add product to my cart and proceed to checkout, with these 2 options:

- Allow ordering out-of-stock product in Product settings :
<img width="900" alt="Screenshot 2022-11-09 at 15 33 59" src="https://user-images.githubusercontent.com/16019289/200859329-1dcfbffd-228e-420f-85a6-54f83f3d7dd7.png">

- Deny order in Product page
<img width="301" alt="Screenshot 2022-11-09 at 15 34 17" src="https://user-images.githubusercontent.com/16019289/200859360-926d0696-f496-43a6-afff-a4d39d438611.png">

https://user-images.githubusercontent.com/16019289/200858885-8ce096d7-d1b1-4148-b968-3ffa606db9be.mov

### Expected behavior

I should not be able to add my product to my cart when I have `Deny orders` and `Allow ordering of out-of-stock products` options enabled.

### Steps to reproduce

1. Go to BO > Catalog > Product > Edit a product
2.  In Quantities > Choose `Deny order` in Availability Preferences > Save
3. Go to Shop Parameters > Product Settings > Disabled `Allow ordering of out-of-stock products` > Save
4. Go to product page in FO > Add product to cart
5. See that the product is added to the cart, when it should not :x:

### PrestaShop version(s) where the bug happened

8.0.X

### PHP version(s) where the bug happened

7.4

**Comment by HanaRebaiQA** [comment]
Hello @florine2623 

Thanks for your report.
I think it's a normal behavior cause the product contains quantities as i can see in your screen-record.
So, When the product does not contains `quantities = 0`. In this case, `Deny orders `option should be functional. 
But, when the product contains `quantities <> 0 ` , it's possible to Add the product to cart even the `Deny orders `option is selected.


https://user-images.githubusercontent.com/92912932/202410879-47096f0a-928f-4942-83bf-783e4dc23f42.mp4

Could you please check it again?

Thank You!

**Comment by florine2623** [comment]
Hello @HanaRebaiQA ,

I can't reproduce my previous issue even with the PR 😭 
It must have been a specific issue on my shop.

I'll close my issue !
