### ISSUE TITLE
Unable to decorate the Admin\AttributeController

### ISSUE THREAD

**Issue by teddylelong** [PrestaShop/PrestaShop#30323]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I need to add an attribute deactivation feature into PrestaShop admin panel. In order to achieve that, I've chosen to decorate the Core Controller `src\PrestaShopBundle\Controller\Admin\Sell\Catalog\AttributeController` via a custom module, created by myself.

I've followed [PrestaShop Documentation](https://devdocs.prestashop-project.org/1.7/modules/concepts/controllers/admin-controllers/override-decorate-controller/) about controller decoration, but nothing works : after resolving the few error messages encountered, and clearing the dev cache, nothing happens. When I click on _Sell > Catalog > Attributes & Features_ and select an attribute, the original PrestaShop page is still displayed.

In order to test, I even rewrote the `indexAction()` method of the Core Controller with a simple `die()`, and there too, nothing changes.

So, I used XDebug to trace the route, and it seems that the core controller located in `src/PrestaShopBundle/Controller/Admin/Sell/Catalog/AttributeController.php` is not called at all ! `(AttributeGroupController.php` no more) However, the controller located in `controllers/admin/AdminAttributesGroupsController.php` is the right called controller. It looks like a legacy controller; I don't think we can decorate it. The only solution seems to override, which is not recommended.

- Why is a legacy controller called on the Admin side, when all Admin controllers are normally managed by Symfony in this version ?
- What is the purpose of the controller located in `PrestaShopBundle\Controller\Admin\Sell\Catalog\AttributeController` if it is not used with the attributes in the admin ?

You can find more information and code on my [original StackOverflow post](https://stackoverflow.com/questions/74460231/prestashop-how-to-decorate-a-controller).

### Steps to reproduce

I use [Wamp64](https://www.wampserver.com/en/download-wampserver-64bits/) local server, with PHP 7.4.26 and [Xdebug](https://xdebug.org/) v3.1.5. XDebug is launched in [step debugger mode](https://xdebug.org/docs/step_debug) with Visual Studio Code.

Open your project in your code editor, and launch a [Xdebug debugging session](https://xdebug.org/docs/step_debug#activate-debugger-cmd). 

Place breakpoints in the following controllers methods : 
- Open file `src\PrestaShopBundle\Controller\Admin\Sell\Catalog\AttributeController.php`
  - Place breakpoint on method `renderView()`, line 104
- Open file `src\PrestaShopBundle\Controller\Admin\Sell\Catalog\AttributeGroupController.php`
  - Place breakpoint on method `indexAction()`, line 58
- Open file `src\PrestaShopBundle\Controller\Admin\Sell\Catalog\AttributeController.php`
  - Place breakpoint on method `indexAction()`, line 65

Go to _Administration Panel > Sales > Catalog > Attributes & Features_ and click on an attribute. 

XDebug will show you that all the code that relates to the Admin Attributes controller is only executed in the `AdminAttributesGroupsController.php` file. Others Symfony Controllers like `src\PrestaShopBundle\Controller\Admin\Sell\Catalog\AttributeController.php` and `src\PrestaShopBundle\Controller\Admin\Sell\Catalog\AttributeGroupController` will never be called.

![Capture d'écran_20221117_173659](https://user-images.githubusercontent.com/98483314/202505717-627958e2-f5a0-4db4-a3fe-b08f6c13b8e8.png)

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.26

**Comment by HanaRebaiQA** [comment]
Hello @teddylelong 

Could you please provide us with more info ?
We need more details to understand how we can reproduce your issue:

- a clear steps to reproduce
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
- ...

Thank You!

**Comment by teddylelong** [comment]
Hello @HanaRebaiQA,

I clarified the "How to reproduce" section by editing my comment above. Here are some other requested information :

- Host : localhost
- Localhost server configuration : 
  - Intel(R) Core(TM) i3-10105, CPU @ 3.70GHz 3.70 GHz
  - RAM 8.00 Go
  - OS : Windows 11 x64
- PrestaShop version (source) : 1.7.8.7 from Prestashop.com
- Debug mode report : I don't know how to produce that
- PHP Error logs : No error about this, only records like :
```
[17-Nov-2022 15:46:11 UTC] Xdebug: [Config] The setting 'xdebug.remote_autostart' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_autostart (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)
[17-Nov-2022 15:46:11 UTC] Xdebug: [Config] The setting 'xdebug.remote_enable' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_enable (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)
```
- Apache error logs and JS console logs contains sensitive information, I can't share it

I hope this helps ! Thank you

**Comment by AureRita** [comment]
Hi @teddylelong 

Thank for your report,with the details that you give, I know that this issue is too technical for me, ping @PrestaShop/prestashop-core-developers, can someone please reproduce this issue ? 

Thanks

**Comment by hibatallahAouadni** [comment]
Hello @teddylelong 

Do you still encounter this issue with PS811 or the branch 8.1.x? 
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @teddylelong 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
