### ISSUE TITLE
BO - Multistore - Product V2 -  An error of deprecated Passing null to parameter ... in FO when preview the product which is newly associated to a newshop

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#30322]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

This issue is previously reported here in this [comment](https://github.com/PrestaShop/PrestaShop/pull/27712#pullrequestreview-1182898013) (**Issue 1**)

An error of deprecated Passing null to parameter ... in FO when preview the product which is newly associated to a newshop, and do not contains a generated combinations for it.

![image](https://user-images.githubusercontent.com/92912932/202463588-81e020e8-738a-4128-87c0-9c156c06c209.png)

https://user-images.githubusercontent.com/92912932/202463500-bea1c528-e0f6-4268-ae70-ae434014bd4a.mp4

### Expected behavior

The FO when preview the shop is well displayed

### Steps to reproduce

1. Go to BO > Shop Parameters > General page
2. Enable multistore
3. Create a new shops & configure it
4. Go to BO > Advanced Parameters > New & Experimental Features page & Enable New product page - Multi store
5. Go to products V2 > select All shops
6. Add a new product > select a new shop created (ShopA in my example)
7. OR
8. Go to products V2 > select a dedicated shop newly created (ShopA in my example)
9. Add a product with combinations > Generate combinations for it
10. In the product with combinations page > Click on select Shops > Select another shop > Click on Save
11. In the header > Change the new selected shop > The product with combinations is page is displayed for this new shop (newshop)
12. Click on Save
13. Come back to products page > select the newshop shop > see that the product is well displayed in the list
14. Edit this product > Click on Preview > See error in FO

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

**Comment by zuk3975** [comment]
https://github.com/PrestaShop/PrestaShop/pull/30683
This PR should have fixed it.

**Comment by hibatallahAouadni** [comment]
Hello @zuk3975 

Indeed it's fixed cause in the Product V2 we can't access to the other shop, see the attached screenshot below:

<img width="1091" alt="Screenshot 2023-02-16 at 04 05 29" src="https://user-images.githubusercontent.com/23308427/219257949-18d33c16-1d19-44be-acb6-7bb4bc5db539.png">

Thanks!
