### ISSUE TITLE
Upgrade use case for image setting configuration 8.0 -> 8.1

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#30321]
## US
As a merchant, when I upgrade, I want to keep my image configuration with new format added in 8.1

## Specs
The configuration after an upgrade

### **Use case 1:**

8: 
- Use JPEG.

8.1: 
- Fallback: JPEG
- Selected format: JPEG

### **Use case 2:**

8: 
- Use PNG only if the base image is in PNG format.

8.1: 
- Fallback: JPEG
- Selected format: JPEG, PNG

### **Use case 3:**
 
8: 
- Use PNG for all images.

8.1: 
- Fallback: PNG
- Selected format: PNG

###  **Use case 4:**

8: 
- Use WebP only if the base image is in WebP format.

8.1: 
- Fallback: JPEG
- Selected format: JPEG, WebP 

### **Use case 5:**

8: 
- Use WebP for all images.

8.1: 
- Fallback: WebP
- Selected format: WebP 

### Compression value

The default values are kept during the upgrade

**Comment by HanaRebaiQA** [comment]
Hello @MatShir 

Thank you for your suggestion. 
I'll add this to the debug backlog so that it's fixed.


Thank you!

**Comment by MatShir** [comment]
Not need relevant for now
