### ISSUE TITLE
BO - Multistore - Product V2 - The image of product is not displayed when preview the product which is newly associated to a newshop

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#30324]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

This issue is previously reported here in this [comment](https://github.com/PrestaShop/PrestaShop/pull/27712#pullrequestreview-1182898013) (**Issue 2**)

The image of product is not displayed when preview the product which is newly associated to a newshop

![image](https://user-images.githubusercontent.com/92912932/202467344-c93c9a82-ffd8-4311-8ea4-d368ff27536c.png)

### Expected behavior

The images is well displayed!

### Steps to reproduce

1. Go to BO > Shop Parameters > General page
2. Enable multistore
3. Create a new shops & configure it
4. Go to BO > Advanced Parameters > New & Experimental Features page & Enable New product page - Multi store
5. Go to products V2 > select All shops
6. Add a new product > select a new shop created (ShopA in my example)
7. OR
8. Go to products V2 > select a dedicated shop newly created (ShopA in my example)
9. Add a product with combinations > Generate combinations for it (For example)
10. In the product with combinations page > Click on select Shops > Select another shop > Click on Save
11. In the header > Change the new selected shop > The product with combinations is page is displayed for this new shop (newshop)
12. Click on Save
13. Come back to products page > select the newshop shop > see that the product is well displayed in the list
14. See error > The image of product is not displayed!

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

**Comment by jolelievre** [comment]
This one may have been fixed by https://github.com/PrestaShop/PrestaShop/pull/30106
To be checked before trying to fix

**Comment by hibatallahAouadni** [comment]
Hello @HanaRebaiQA 

I didn't manage to reproduce the issue with develop, it seems that the issue has been fixed as mentioned by @jolelievre 
Closing the issue as Fixed :tada: 

Thanks!
