### ISSUE TITLE
PrestaShop must be compatible with PHP8.2

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#30335]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

PrestaShop 8.1.0 is scheduled to be released in the beginning of 2023. PrestaShop must allow PHP developers to use the latest versions of PHP.

### Describe the solution you'd like

PrestaShop 8.1.0 must provide PHP8.2 compatibility.

As PS 8.1.0 is a minor version, we must aim to be as backward compatible as possible with 8.0.0 . So in theory no PHP min version bump and no BC Breaks. However I think PHP8.2 will require us to introduce a few BC breaks that we'll have to document.

**Comment by AureRita** [comment]
Hi @matks  ,

Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments. 

Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you create it. 

If you or anyone else is willing to [contribute this feature](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/) to the PrestaShop Project, the teams will be happy to help by ensuring that it fits well within the project. Please let us know if that is the case!

Thank you
