### ISSUE TITLE
The label "Shipped products" is not correct in the movement section when ordering a virtual product

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#30331]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Previously reported here: https://github.com/PrestaShop/PrestaShop/pull/28640#pullrequestreview-1177295537
The label "Shipped products" is not correct in the movement section when ordering a virtual product

### Expected behavior

Change the wording to "Sold product"

### Steps to reproduce

1. Go to BO > Advanced Parameters > New & Experimental Features page & Enable New product page - Single store
2. Create a vector product with downloadable file & quantity = 10 for example
3. Create an order with this product (No shipping is selected)
4. Go to BO > Orders > View the last order created & change the status to "Payment accepted"

The customer, in this case, can download his attachment > I think, in this specific case, we should add a line for the stock movement

5. Change the Order status to shipped 
6. Go to BO > Catalog > Product list V2 > Edit the product created
7. Check the Virtual tab > The expression "Shipped" is not correct with a virtual product

![image](https://user-images.githubusercontent.com/16067358/201341675-9413dc7d-a68c-4f63-8b5f-9669b2eb58d2.png)

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.0

**Comment by khouloudbelguith** [comment]
Will be fixed by https://github.com/PrestaShop/PrestaShop/issues/27993

**Comment by florine2623** [comment]
Hello @khouloudbelguith ,

I reproduce the issue with PrestaShop version develop, I'll add this to the backlog so it can be fixed.

In previous versions, the "Shipped products" line did not exist.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by zuk3975** [comment]
Fixed label in this PR https://github.com/PrestaShop/PrestaShop/pull/31262.
ping @MatShir 
However I want to notice that IMO the UX in this list seems very poor.
At first I didn't undersand what it shows, until @jolelievre explained it to me (it shows sold product between employee edition or so).
Despite that, it is still frustrating especially if there are no employee editions, then you would see "sold products" where you would expect the `date & time `by looking at the table definition. 
Im pretty sure there is more we could improve to make it more obvious what is happening (like maybe just adjusting wording and adding period dates so it would translate more obvious message, also maybe increasing the list limit would make sense (lets say 5 rows). Ovr the table could look like this (not sure if its hard to do yet, but I guess the UX would be much better this way)
```
| date                   | Quantity    | Movement type       |
| 2015-10-10 -2015-10-11 | -100        | Sold                |
| 2015-09-10             | -10         | Edited by: John Doe |
| 2015-08-10             | +2          | Refunded            |
```

**Comment by MatShir** [comment]
<img width="623" alt="Capture d’écran 2023-02-10 à 11 23 16" src="https://user-images.githubusercontent.com/43613217/218080809-20fe64bc-1ef5-43f9-983e-94cfedf676fc.png">

True might not very clear
