### ISSUE TITLE
{url} helper generate the supplier url without rewrite rules

### ISSUE THREAD

**Issue by PrestaSafe** [PrestaShop/PrestaShop#30341]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, 

The `{url}` helper in smarty generate the URL of supplier without rewriting url:
ex:
`{url entity='supplier' id=1}`
will ouput: 
`//prestashop:8888/fournisseur?id_supplier=1`

If we use the `$link` class it works fine: 
`{$link->getSupplierLink(1)}`
will output: 
`http://prestashop:8888/supplier/1-fashion-supplier`

### Expected behavior

`{url entity='supplier' id=1}` should be return the same result of `{$link->getSupplierLink(1)}`

### Steps to reproduce

For testing: 
Edit file: themes/classic/templates/index.tpl
put this code:

```
{**
 * Copyright since 2007 PrestaShop SA and Contributors
 * PrestaShop is an International Registered Trademark & Property of PrestaShop SA
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License 3.0 (AFL-3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/AFL-3.0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@prestashop.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
 * versions in the future. If you wish to customize PrestaShop for your
 * needs please refer to https://devdocs.prestashop.com/ for more information.
 *
 * @author    PrestaShop SA and Contributors <contact@prestashop.com>
 * @copyright Since 2007 PrestaShop SA and Contributors
 * @license   https://opensource.org/licenses/AFL-3.0 Academic Free License 3.0 (AFL-3.0)
 *}
{extends file='page.tpl'}

    {block name='page_content_container'}
      <section id="content" class="page-home">
        {block name='page_content_top'}{/block}

        {block name='page_content'}
          {block name='hook_home'}
            {* Wrong url *}
            {url entity='supplier' id=1}
            <br>
            {* Good url *}
            {$link->getSupplierLink(1)}
            {$HOOK_HOME nofilter}
          {/block}
        {/block}
      </section>
    {/block}

```

Then empty the smarty cache
Go to the home page of your shop, you will see the url displayed: 
<img width="1469" alt="Capture d’écran 2022-11-18 à 09 05 54" src="https://user-images.githubusercontent.com/4788787/202652043-e5282a70-3e7f-4d45-85b5-fd524e02bf40.png">

It's the same issue as #30313 
I'll make the PR right away

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1.1

**Comment by PrestaSafe** [comment]
PR: https://github.com/PrestaShop/PrestaShop/pull/30342

**Comment by khouloudbelguith** [comment]
Hi @PrestaSafe,

I reproduced the issue with PS1787 & the develop branch
![image](https://user-images.githubusercontent.com/16067358/202697891-4238c51a-bd71-4855-a311-ba6c88a9b088.png)

Thanks for the PR!
