### ISSUE TITLE
File manager blank window

### ISSUE THREAD

**Issue by ni3mm4nd** [PrestaShop/PrestaShop#30343]
Every time I want to add some image into some article I click on "image" icon then icon for "source" and then blank File manager window appear like this:

![image](https://user-images.githubusercontent.com/13623907/202667364-a3a6026b-f88e-4458-9d79-9cfe2d4053ba.png)

### Expected behavior

Show window with some input field and other images I can pick from.

### Steps to reproduce

> Edited by @HanaRebaiQA (Thanks to @Hlavtox)

1. Prepare environment with PHP 8.1.
2. Install Prestashop 8 in CZECH language - important.
3. In BO, go to CMS pages, edit some page, in the content, try to add new image.
4. See empty file manager.

> The main steps of @ni3mm4nd 

1. Go to 'Pages'
2. Select some and click 'Edit'
3. Scroll down to content
4. Click 'Image' icon
5. Click 'Source' icon
6. Empty File manager shows up

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1.9

**Comment by Hlavtox** [comment]
![Snímek obrazovky 2022-11-18 113023](https://user-images.githubusercontent.com/6097524/202681455-1ec1a542-ae5e-400c-835f-9aa9864690b3.jpg)

**Comment by AureRita** [comment]
Hi @ni3mm4nd 

Thank you for your report, I tried to reproduce your issue but I didn't success to do it as you can see : 

[Untitled_ Nov 18, 2022 5_20 PM.webm](https://user-images.githubusercontent.com/100699445/202752641-80b3b38b-07dc-46f3-ad65-fc6a15bc194b.webm)

Can you provide us a video to see the issue ? 

Waiting for your feedback

**Comment by Hlavtox** [comment]
Got a simmilar report today to czech Prestashop group, seems like a common problem. 👍

**Comment by ni3mm4nd** [comment]
@AureRita 

Here it is :-)

[Screencast from 11-20-2022 03:06:27 PM.webm](https://user-images.githubusercontent.com/13623907/202906674-15fef851-5e50-4050-9b75-c35712d1f6ab.webm)

You're welcome.

Don't you have any idea?

Thank you
//Jan Kadlec

**Comment by Hlavtox** [comment]
@ni3mm4nd 
- Can you try different PHP version? Same behavior?
- Can you open developer tools (F12), go to console tab and check if there are any errors?
- Can you check PHP error log and see if there is something related to file manager?

**Comment by AureRita** [comment]
Hi @ni3mm4nd 

As said Hlavtox, can you tell us your php version ? 
and when you are on this blank window, can you do a CTRL+MAJ+R to force the reload ? 

Waiting for your feedback

**Comment by ni3mm4nd** [comment]
@AureRita @Hlavtox 

Once I open up File manager window I get 

`GET https://<mydomain>.cz/adminlogin/filemanager/dialog.php?type=1&descending=false&sort_by=&lang=cs 500 (Internal Server Error)`

If I go to Tools > Errors there are no 500 errors 
![image](https://user-images.githubusercontent.com/13623907/203021985-bb6335d6-4015-4776-a8bf-a625fb55bd97.png)

I've found on the internet that there can be some problem with FS folder rights but I think it should be OK because I haven't changed anything:

```
root@f739024d35a3:/var/www/html# ls -la | grep adminlogin
drwxr-xr-x 8 www-data www-data   4096 Oct 26 12:35 adminlogin
root@f739024d35a3:/var/www/html# 

root@f739024d35a3:/var/www/html# ls -la adminlogin | grep filemanager
drwxr-xr-x 10 www-data www-data  4096 Oct 26 12:35 filemanager
root@f739024d35a3:/var/www/html# 

root@f739024d35a3:/var/www/html# ls -la adminlogin/filemanager | grep img        
drwxr-xr-x  4 www-data www-data  4096 Oct 26 12:35 img
root@f739024d35a3:/var/www/html# 
```

My PrestaShop is just official docker image
```
$ docker images | grep presta
prestashop/prestashop                                               latest            ceed5664d7af   3 weeks ago    1.29GB
$

$ docker ps |grep presta
f739024d35a3   prestashop/prestashop           "docker-php-entrypoi…"   6 days ago     Up 6 days     127.0.0.1:8001->80/tcp              prestashop
2b9bf9059885   mysql:5.7                       "docker-entrypoint.s…"   6 days ago     Up 6 days     33060/tcp, 0.0.0.0:3307->3306/tcp   presta-mysql
$
```

Commands to reproduce my environment:
```
$ docker network create prestashop-net
$ docker run -ti --name presta-mysql --network prestashop-net -e MYSQL_ROOT_PASSWORD=admin -p 3307:3306 -d mysql:5.7
$ docker run -ti --name prestashop --network prestashop-net -e DB_SERVER=presta-mysql -p 127.0.0.1:8001:80 -d prestashop/prestashop
```

I hope it will help.
Every time I will setup it like this I get the same result with non-functioning window manager.

Thank you

**Comment by Hlavtox** [comment]
Managed to reproduce your issue.

```
>Fatal error</b>:  Uncaught Error: Undefined constant &quot;lang_Show_url&quot; in C:\xampp\htdocs\dev\admin-dev\filemanager\dialog.php:295
Stack trace:
#0 {main}
  thrown in <b>C:\xampp\htdocs\dev\admin-dev\filemanager\dialog.php</b> on line <b>295</b><br />
```

![filemanager](https://user-images.githubusercontent.com/6097524/203036062-a3b2079e-0a68-49af-9352-36b7d6e8d283.jpg)

**Comment by Hlavtox** [comment]
File manager is loading some translation strings (defines) from lang folder, but there are three missing in czech `cs.php` file.
```
define('lang_Show_url', 'show URL');
define('lang_File_info', 'file info');
define('lang_Edit_image', 'edit image');
```
This bug will probably occur also with other languages, we need to fix it universally.

**Comment by kpodemski** [comment]
@Hlavtox could you write the exact steps that are required for QA to reproduce the issue?

**Comment by Hlavtox** [comment]
@kpodemski @AureRita 

1. Prepare environment with PHP 8.1.
2. Install Prestashop 8 in **CZECH** language - important.
3. In BO, go to CMS pages, edit some page, in the content, try to add new image.
4. See empty file manager.

**Comment by HanaRebaiQA** [comment]
Hello, 

Thanks to @ni3mm4nd for your report and @Hlavtox for the provided information to reproduce the issue and for your PR!
I was able to reproduce the issue with **PS8.0.x and php8.1** when using the same steps to reproduce

**PS8.0.x and php8.1 : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/203102399-0f7f52c9-7cdf-46a2-ad33-51f4ec8c504d.png)


https://user-images.githubusercontent.com/92912932/203103447-e65af5e9-2924-4fb5-bb0b-cc6b10c0eac3.mp4

**PS8.0.x and php7.4** : Another error but the images of file manager are displayed!

![image](https://user-images.githubusercontent.com/92912932/203103835-59c05b61-92b6-4988-b03f-a8f6c4937e28.png)


**PS1.7.8.7 and php7.4 : OK** :heavy_check_mark:  

![image](https://user-images.githubusercontent.com/92912932/203103314-49f26c62-9c87-4e64-81f0-5302acd12af3.png)

So, indeed it's a regression!

I'll add this to the debug backlog so that it's fixed.

I will give our feedback following the test of the PR 

Thank You!

**Comment by HanaRebaiQA** [comment]
Fixed by [#30362 ](https://github.com/PrestaShop/PrestaShop/pull/30362)

**Comment by futurehousestore** [comment]
how to fix this issue for en-GB lang?

**Comment by futurehousestore** [comment]
I managed to fix the problem by disabling MBO and enabling it again but before that I copied the EN lang file in admin module, renamed it to en-gb and added the lines from your PR. So file manager is finally working for me too. Thanks everyone.

**Comment by sebastian-marinescu** [comment]
> I managed to fix the problem by disabling MBO and enabling it again but before that I copied the EN lang file in admin module, renamed it to en-gb and added the lines from your PR. So file manager is finally working for me too. Thanks everyone.

Hi @futurehousestore - how do you mean "en-gb"? Did that come from the user's browser? 
And you are saying "admin module", but you mean the translations inside the `/admin/filemanager/lang/` directory, right?
