### ISSUE TITLE
Pass variable as reference to improve integration with modules

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#30346]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

When a combination in the product page is select, an AJAX request is sent to get information, and this information is retrieved:

![image](https://user-images.githubusercontent.com/15104724/202709960-64f6e0e0-f2ca-4a4b-bc7d-e8f084d963da.png)

This request is thrown by this JS function:
https://github.com/PrestaShop/PrestaShop/blob/develop/themes/_core/js/product.js#L177

and managed here:
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/controller/Controller.php#L765

And there is a hook at the end of this function to manage this information (great!), so a module can get it:
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/controller/Controller.php#L784

But this variable is not passed by reference, so a module can not modify or add new information, so it can not be returned to the page.

### Describe the solution you'd like

The hook function should pass the variable by reference:

https://github.com/PrestaShop/PrestaShop/blob/develop/classes/controller/Controller.php#L784

```Hook::exec('actionAjaxDie' . $controller . $method . 'Before', ['value' => &$value]);```

So a module could add new information to this request and use it in the frontoffice

```
prestashop.on('updatedProduct', function (event) {
       ....
    }
);
```

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by AureRita** [comment]
Hi @idnovate  ,

Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments. 

Thank you for your PR :rocket: 

Thank you

**Comment by magentix** [comment]
Hi,

It will be great! For example today we must do:

```php
public function hookActionAjaxDieProductControllerdisplayAjaxRefreshBefore(array $params): void
{
        $value = json_decode($params['value'], true);
        $value['foo'] = 'bar';

        header('Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0');
        echo json_encode($value);
        exit();
}
```

But this is not compatible with the Prestashop modularity.

**Comment by idnovate** [comment]
> Hi,
> 
> It will be great! For example today we must do:
> 
> ```
> public function hookActionAjaxDieProductControllerdisplayAjaxRefreshBefore(array $params): void
> {
>         $value = json_decode($params['value'], true);
>         $value['foo'] = 'bar';
> 
>         header('Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0');
>         echo json_encode($value);
>         exit();
> }
> ```
> 
> But this is not compatible with the Prestashop modularity.

We've finally overridden the function as the solution proposed, but it's not a recommended practice neither ;)

**Comment by florine2623** [comment]
ping @PrestaShop/prestashop-maintainers ,

What do you think about this feature request ? Is this approved ?
