### ISSUE TITLE
[Module Image slider] Autoplay doesn't work

### ISSUE THREAD

**Issue by pitalia34** [PrestaShop/PrestaShop#30344]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

ps_imageslider --> autoplay doesn't work. My slider is static.

### Steps to reproduce

just go on innobiz-pro.com

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

ps_imageslider v3.1.1

**Comment by AureRita** [comment]
Hi @pitalia34 

I tried to reproduce your issue but I don't succeed, as you can see : 

[Untitled_ Nov 18, 2022 6_16 PM.webm](https://user-images.githubusercontent.com/100699445/202763578-20348e50-eda3-4aab-bdb0-1747e7971f64.webm)

How many millisecond did you setup ? at the start, it setup to 5 seconds. 

Can you give us a video to see your issue 

for information, we test all the issue in our environment to see if the issue is set by a particular environment or anything else 

Waiting for your feedback

**Comment by pitalia34** [comment]
Hello !
Here is my video link : https://watch.screencastify.com/v/vMw5N4jdKpVWIgEd4bh4
Unfortunately it's still doesn't work !
Thank you 

Pierre

**Comment by AureRita** [comment]
Hi @pitalia34  ,

Despite my efforts, I am not able to reproduce your issue with the provided information. 

did you do anything that can create this issue because with this details I can't reproduce it ? 

Waiting for your feedback

**Comment by pitalia34** [comment]
Hello AureRita,
What can I do for you so show the problem ? Can I give you some acess to my preprod ?

**Comment by AureRita** [comment]
Hi @pitalia34 

I didn't have the right to do that, can you check if your theme have a slider option or anything else that can block the slide ? 
Can you enable the two other option to see if this one will works ? if you have all your image on your computer can you test with a reset of the module ( clic on the down arrow next to the module to find the reset button)

Waiting for your feedback

**Comment by florine2623** [comment]
Hello @pitalia34 ,

I tested on 1.7.8.7, 8.0.0 and develop branch the module ps_imageslider v3.1.1.
I couldn't reproduce your issue.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
