### ISSUE TITLE
Widget pointing to non installed module kills the page

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#30340]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When your templates contains a widget code to display a module that is not installed, it throws a fatal error.
`Fatal error: Uncaught Exception: Module `yourmodule` is not a WidgetInterface`.

Imagine you are doing some work on the shop or something, or you decide not to use this module anymore and it will break all pages where you included it as a widget.

### Expected behavior

It should continue to work and just do not display anything.

### Steps to reproduce

1. Open themes\yourthemename\templates\contact.tpl and scroll to the bottom.
2. If you have `{widget name="contactform"}`, change it to `{widget name="something_contactform"}` for example.
3. If you don't have it there, just put `{widget name="something_contactform"}` somewhere in the file.
4. Open the "Contact us" page and see that you get a fatal error about `Fatal error: Uncaught Exception: Module `something_contactform` is not a WidgetInterface`.

### PrestaShop version(s) where the bug happened

Tested on 1.7.6, 8, develop - happens everywhere

### PHP version(s) where the bug happened

8.0

**Comment by AureRita** [comment]
Hi @Hlavtox ,

Thank for your reporting, I reproduce the issue with PrestaShop develop version and not with the version 8.0.0.  Nice catch ! It's a regression ! I'll add it to the patch backlog.

Please be aware that some issues might take a very long time to be resolved. 

Waiting for your PR :rocket: 

Thank you

**Comment by Hlavtox** [comment]
@AureRita The same behavior in v8
