### ISSUE TITLE
Symfony error when entering the admin panel

### ISSUE THREAD

**Issue by msikorski26** [PrestaShop/PrestaShop#30356]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

![image](https://user-images.githubusercontent.com/41286754/202899872-3a473cd1-15f5-4ab8-b470-eda3d59e8e5d.png)

### Expected behavior

Normal use of the panel

### Steps to reproduce

when entering the admin panel

### PrestaShop version(s) where the bug happened

1.7 I'm guessing 1.7.8 because I can't get into the admin panel and check

### PHP version(s) where the bug happened

7.4

**Comment by msikorski26** [comment]
next error Unable to generate a URL for the named route "admin_mbo_catalog_module" as such route does not exist.

**Comment by msikorski26** [comment]
repaired, i updated ps_mbo and removed cache

**Comment by AureRita** [comment]
Hi @mscodepl 

Thank you for your report, as you said this issue is repaired so I will close this issue 

Have a great day
