### ISSUE TITLE
Error when the Credits Slips page is the default page for an employee

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#30358]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Try to define the Credit Slips page as default page for an employee, connect it and an error is displayed.

### Expected behavior

No error is displayed.

### Steps to reproduce

* Edit the profile
* Define the **CreditSlips** page as default
* Log Out
* Connect 
* An error is triggerred : 
![image](https://user-images.githubusercontent.com/1533248/202997324-6c6c38dd-f478-401f-ab80-81b9dcdcb150.png)

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.3

**Comment by AureRita** [comment]
Hi @Progi1984  ,

Thank for your report,I reproduce the issue with PrestaShop version 8.0.x and not with the version 8.0.0. As you can see on this video : 

[Untitled_ Nov 21, 2022 11_25 AM.webm](https://user-images.githubusercontent.com/100699445/203027589-5c3d8d5a-1063-4e18-a319-00735cf1743a.webm)

 Nice catch ! It's a regression ! I'll add it to the patch backlog.

Please be aware that some issues might take a very long time to be resolved.

Thank you

**Comment by khouloudbelguith** [comment]
Will be fixed by https://github.com/PrestaShop/PrestaShop/pull/30326
