### ISSUE TITLE
New password policy on customer acccount page "Your personal information, The PrestaShop 8.

### ISSUE THREAD

**Issue by web-burn** [PrestaShop/PrestaShop#30367]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Currently on customer acccount page "Your personal information"  a customer enter new password and don't see a hint. Therefore, the new password entered may not comply with the requirements of the new password policy. And a custore will see an error:

![image](https://user-images.githubusercontent.com/22581200/203088498-b3c9af1e-a770-4bec-b0b5-73804c5038d9.png)

### Expected behavior

On customer acccount page "Your personal information" new password policy should be applied for a field "New password", and remove for filed "Password" (old password).
The user needs to be prompted to create a new password.
He already knows the old password. And there is no point in applying the new password policy to the old password field:
![image](https://user-images.githubusercontent.com/22581200/203089074-76f07e99-a11f-484f-ac01-4526cc21ec2d.png)

Also the new password policy should be added for the field "New password" on page "Reset password".

### Steps to reproduce

1. Go to "Your account" -> "Your personal information".
2. Enter old password.
3. Enter new password and "Save"

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.0

**Comment by AureRita** [comment]
Hi @web-burn  ,

I reproduce the issue with PrestaShop version 8.0.0 and not with the version 1.7.8.7. As you can see in this video : 

[Untitled_ Nov 21, 2022 6_16 PM.webm](https://user-images.githubusercontent.com/100699445/203119404-d985f614-d864-49a2-83b7-b3be3fd08406.webm)

Nice catch ! It's a regression ! I'll add it to the patch backlog.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by web-burn** [comment]
Hello [AureRita](https://github.com/AureRita),

As temporary fix i have replaced 34 row "{if $field.type === "password"}" to 
"{if ($page.page_name == "identity" && $field.name === "new_password") || ($page.page_name != "identity" && $field.type === "password")}" in the file "templates/customer/_partials/customer-form.tpl".
It works for me:
Now the new passwrod policy is applied to the filed "New password" on "Your personal information" page.

**Comment by AureRita** [comment]
Hi @web-burn 

Thank for the advice ! If this one works for you, you can[ send a pull request](https://github.com/PrestaShop/PrestaShop/compare) to share this with other contributors 

Thanks !

**Comment by eshraw** [comment]
Hi @web-burn , @AureRita, thanks for creating the issue !

As it stands, it's not a bug nor a regression since the new password policy was added in 8.0.x and didn't exist in 1.7.8.x but a use case that was not implemented. It is however important that we take care of it !

@web-burn it would great if you could provide you change in a PR like @AureRita suggested. If it's your first PR feel free to reach out to the community if you need some help with it and the team would be pleased to review your contribution !

**Comment by web-burn** [comment]
Hello @eshraw,

Unfortunately i don't how to do it.

**Comment by eshraw** [comment]
Hi @web-burn , no prob you can find the how to here --> [Contributing pull request](https://devdocs.prestashop-project.org/8/contribute/contribute-pull-requests/)

Feel free to reach out to the open source community slack if you need help on this as well
