### ISSUE TITLE
ps_mailalerts v2.4.0 + psgdpr v1.4.2 ( on PS 1.7.8.7) compatibility problem

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/PrestaShop#30379]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After updating the ps_emailalerts module to latest 2.4 with the GDPR module v1.4.2 the mailalert module not appear anymore inside GDPR module.

both modules installed:

![image](https://user-images.githubusercontent.com/16102074/203356531-531370f0-aae5-456c-aaad-4c88e85fc40c.png)

Inside the GDPR module the Mail Alert module is not popup

![image](https://user-images.githubusercontent.com/16102074/203356757-4175b76d-f185-4507-a9d1-d3b22809ba4a.png)

This will not consent to add the privacy checkbox.

![image](https://user-images.githubusercontent.com/16102074/203357963-fbeb503c-85e4-4d61-8d4b-e340905657a3.png)

### Expected behavior

Usually the mailalert module appears in the GDPR module list, so is possible to configure the privacy text.

### Steps to reproduce

Install psgdpr module (latest version)
Install ps_emailalerts module (latest version)

Configure the GDPR module, the mail alert module not appear inside.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.2 / 7.3 / 7.4

### If your bug is related to a module, specify its name and its version

ps_emailalerts

**Comment by HartLarsson** [comment]
I add another problem.
When somoene subscribe to be noticed it appears in the table in the database
asap the quantity of the product is positive, the systemn is expectred to send the notice, instead the customer is deleted from the database and no mail is sent.

**Comment by hibatallahAouadni** [comment]
Hello @HartLarsson 

Could you please check this issue #30348 it seems similar to yours.
Please check and feedback.

Thanks!

**Comment by HartLarsson** [comment]
> Hello @HartLarsson
> 
> Could you please check this issue #30348 it seems similar to yours. Please check and feedback.
> 
> Thanks!

hi, seems similar but i've problem on 1.7.8.7 version related to mailalert module only. the other modules are connected to gdpr correctly.

**Comment by marsaldev** [comment]
Hi @HartLarsson, it seems from the 1.7.8 the modules need to implement a specific hook and listener:

See `productscomments` module: https://github.com/PrestaShop/productcomments/blob/0718b6a517ab25be018fffc4f86574e489d35b4e/productcomments.php#L1097

```
/* 
    registerGDPRConsent is a special kind of hook that doesn't need a listener, see :
    https://build.prestashop.com/howtos/module/how-to-make-your-module-compliant-with-prestashop-official-gdpr-compliance-module/
    However since Prestashop 1.7.8, modules must implement a listener for all the hooks they register: a check is made at module installation.
*/
```
that `ps_emailalerts` doesn't have.

I'll prepare a PR later on, you can apply the hotfix to your module waiting the patch release 😉 

~ ~ ~

@hibatallahAouadni 
I made some test on PS v8.1 and also with the v2.3.3 (the previous version), same issue.

**Comment by HartLarsson** [comment]
> Hi @HartLarsson, it seems from the 1.7.8 the modules need to implement a specific hook and listener:
> 
> See `productscomments` module: https://github.com/PrestaShop/productcomments/blob/0718b6a517ab25be018fffc4f86574e489d35b4e/productcomments.php#L1097
> 
> ```
> /* 
>     registerGDPRConsent is a special kind of hook that doesn't need a listener, see :
>     https://build.prestashop.com/howtos/module/how-to-make-your-module-compliant-with-prestashop-official-gdpr-compliance-module/
>     However since Prestashop 1.7.8, modules must implement a listener for all the hooks they register: a check is made at module installation.
> */
> ```
> 
> that `ps_emailalerts` doesn't have.
> 
> I'll prepare a PR later on, you can apply the hotfix to your module waiting the patch release 😉
> 
> ~ ~ ~
> 
> @hibatallahAouadni I made some test on PS v8.1 and also with the v2.3.3 (the previous version), same issue.

that hook problem is the cause that the return in stock of a product will not be sent too?
because one of the problem of the ps_mailaltert is that not send to customers that have choose to be notified if a product is returned available.

Using custom SMPT server (not mail()) the product available notification not works while other features of the modules works and mail are sent.

**Comment by sallemiines** [comment]
Hello @HartLarsson 

Thanks for reporting the issue

I reproduce the issue with `PS1787 ` `PS800` , you can check the screerecord 

 - psgdpr V1.4.0
- ps_emailalert V2.4.4 , also checked with V2.3.3

[Untitled_ Nov 24, 2022 4_10 PM.webm](https://user-images.githubusercontent.com/31663369/203816673-e5a1ad7c-ce39-47bc-b056-a17994b0d6c9.webm)

Thank You !

**Comment by marsaldev** [comment]
> that hook problem is the cause that the return in stock of a product will not be sent too?

I don't think so, that hook is only responsible of compliancy with the psgdpr 😊

**Comment by HartLarsson** [comment]
> > that hook problem is the cause that the return in stock of a product will not be sent too?
> 
> I don't think so, that hook is only responsible of compliancy with the psgdpr 😊

well i thought too that was not the problem. The strange behaviour is with SMTP configured is not send any notice.

**Comment by marsaldev** [comment]
@HartLarsson 
Could you please open a new issue?
I don't think it's related to that hook, could be, but I'm not so sure about that 😊

**Comment by HartLarsson** [comment]
> @HartLarsson Could you please open a new issue? I don't think it's related to that hook, could be, but I'm not so sure about that 😊

i will do asap thanks!
