### ISSUE TITLE
ps_emailalerts 2.4.0 has errors upgrading from 2.3.3 and also with clean install

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#30370]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
today I've upgraded 15 sites ps_emailalerts from 2.3.3 to 2.4.0 but 4 of these have problems
during theri upgrading I got an error, after I've removed them and done a clean installation
all was ok, except its mails/ contains only en folder and the shop's email is not set into the configuration page of this module
now we realized that new order notification emails are not sent from the module, everything was fine with version 2.3.3

now I'll try to upgrade it to other 15 sites

the problem is that it only happens on some sites and you, being unable to replicate the error, will not make any changes

right now another website with the same problem to upgrade it

the website with this problems are 4 wesbites on VPS and just one on shared plan
the others 11 websites are some with vps and some on shared plans

another error on shared website, I don't continue to upgrade the other website until the fix to this problem

![1](https://user-images.githubusercontent.com/653230/203135604-dd3cc04b-eab7-4abb-80a7-ea7df61505e3.png)
![1](https://user-images.githubusercontent.com/653230/203134031-1532a143-2d0f-4241-8ac4-4158b9ecdffb.png)
![2](https://user-images.githubusercontent.com/653230/203134054-1619043c-5efd-4e48-9d2f-d20dd3e9a300.png)
![3](https://user-images.githubusercontent.com/653230/203134138-7a30278a-f938-4a8e-85f4-90d5f57de8a3.png)

### Steps to reproduce

upgrade from 2.3.3 to 2.4.0
and check into its mails folder id there is only en folder

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.3 and 7.4

### If your bug is related to a module, specify its name and its version

ps_emailalerts 2.4.0

**Comment by Maofree** [comment]
I've done a test
removed the ps_emailalerts v2.4.0, installed the 2.3.3 and all is ok in those sites where I got errors with 2.4.0

**Comment by Misty-94** [comment]
Hi @maofree. I have upgraded twice my website and not encountered the problem. What is the value of your php option opcache.revalidate_freq ? Mine is set to 0. Could you try with this value ?

**Comment by Misty-94** [comment]
And also I have opcache.validate_timestamps=1, what is your value ?

**Comment by Maofree** [comment]
Hi
I'll ask to the hosting
as mentioned I have updated many sites and a third of them have this problem, despite being on the same hosting

**Comment by Maofree** [comment]
Hi
in one vps there are these values

opcache.revalidate_freq	2
opcache.validate_timestamps	On

**Comment by hibatallahAouadni** [comment]
Hello @maofree 

I didn't manage to reproduce the issue with the provided infos.
Could you please provide more infos (screenshots or screen record with English language) :pray: 
Waiting for your feedback.

Thanks!

**Comment by Maofree** [comment]
Hi
I cannot give you more infos
with 2.3.3 all 30 websites have no problems with this module, instead of with 2.4 some of them yes
the texts are in italian because the websites are in Italy, however they are easy to understand those texts
whoever did the module update probably knows what he changed that could cause these errors.
almost all of these are on the same hosting, I've seen it happen mostly to vps, not all servers are configured in the same way.
the module should not be too complex, its job is just to check and send emails

**Comment by sallemiines** [comment]
Hello @maofree

Thank you for the issue !
Following your infos unfortunately I didn't manage to reproduce the issue !

I try to check it with those different steps : 

**Step 1 **
I removed the `ps_emailalertsv2.4.0`, and I installed the `ps_emailalertsv2.3.3`, you can see the attached screenshot 

![steps_install](https://user-images.githubusercontent.com/31663369/203735086-fdb3a86d-f888-4821-b98a-fb33f2b3a9a6.png)

**Step 2** 
I upgraded the module from the version `V2.3.3` to `V2.4.0` > No errors displayed, you can seee thea attached screenrecord 


[Untitled_ Nov 24, 2022 9_42 AM.webm](https://user-images.githubusercontent.com/31663369/203735356-8b6531a4-080b-44aa-8c5d-90dae9477b48.webm)


Did I miss something?
Please check and feedback  ! 

Thanks!

**Comment by TaccCZ** [comment]
Same problem for me. PHP 7.4, VPS server. It looks, the tables in database for mulstistore not created. It is not posible save email to the textfield. I must created rows in DB.

**Comment by Maofree** [comment]
Hi @sallemiines
I can create a duplicated website and give you the access to it where you can see that the 2.4.0 has errors on that server

**Comment by sallemiines** [comment]
> Hi @sallemiines I can create a duplicated website and give you the access to it where you can see that the 2.4.0 has errors on that server

Yes please ^^

**Comment by Maofree** [comment]
Hi @sallemiines 

How can I pass you the login credentials of the site, in order not to make them public? could you write me an email?

**Comment by sallemiines** [comment]
> Hi @sallemiines
> 
> How can I pass you the login credentials of the site, in order not to make them public? could you write me an email?

ines-sallemi.ext@prestashop.com

**Comment by masiorama** [comment]
I experienced the same error on PS 1.7.7.4 (I know, it is old).

**Comment by sallemiines** [comment]
@maofree

 Thank you for the  website access ! 
 I cleared the cache, set the cache to no , and enable debug mode I tried to upgrade the ps_email_alerts module and it upgraded successfully 
 You can see the attached screen-shots 
 
 
![Prestazioni-•-AloiseRW](https://user-images.githubusercontent.com/31663369/204288035-4b233d41-3f32-4776-9739-66013ab3fae2.png)

 
 
![Gestione-moduli-•-AloiseRW](https://user-images.githubusercontent.com/31663369/204288010-c0189538-02ee-4925-8fef-8a4586185318.png)

Could you let us know if this solves your problem ? 

Please check & feedback ! 
Waiting for you 

Thank you

**Comment by Maofree** [comment]
Hi
at this moment seams to be ok, I've asked to the shopkeeper to check if he gets emails about new orders
I'll try with other sites

**Comment by sallemiines** [comment]
@maofree 

Thank you for your feedback ! 

Just some information : usually as a **QA team** we follow those steps to check the module autoupgrade ( **example** from v2.3.3 to v2.4.0 ) 

1. In your local machine into your PS project
2. cd ../modules/
3. rm -rf ps_emailalerts
4. git clone https://github.com/PrestaShop/ps_emailalerts.git
5. cd ps_emailalerts
6. git checkout tags/v2.3.3 -b v2.3.3
7. git branch (should be v2.3.3)
8. composer install
9. Then in your shop go to module catalog > search for emailalert module > install
10. Go to module manager search for ps_emailalert > upgrade

Your module should be successfully upgraded :smile: 


I will close this issue , please note that you can always create a new one if further information pops up.

Thank you !

**Comment by Maofree** [comment]
ok thanks

**Comment by Maofree** [comment]
Hi @sallemiines 
I'm testing again on some sites that had this problem. in one of them, cleaning the cache and with debug active I've updated the module in the right mode, but with others no I get the same problems
- no emails are present in the module
- no mail folders are present into mails/
I pass you their access to test it again
I'm upgrading others modules without any problem, but this module 2.4.0 have some conditions that are not good for some server

if I install the 2.3.3 with these websites at the first time all is ok

![1](https://user-images.githubusercontent.com/653230/205438278-f400936a-fb4f-417e-a263-2754f0d1f0dd.png)
![2](https://user-images.githubusercontent.com/653230/205438282-f64c932d-e70c-4d3f-8b8d-f942d20d4263.png)

**Comment by maofree** [comment]
some days ago I've migrated on site to another server and now I can upgrade it without errors

**Comment by Betafer** [comment]
Same problem here

**Comment by Maofree** [comment]
Hi @sallemiines
tell me if it is necessary to create a new topic for the same problem, because the problem exists and it is not solved or you can reopen this one

**Comment by AureRita** [comment]
Hi @maofree 

Thank you for your report ! I tried to reproduce your issue, as you can see : 

[Untitled_ Dec 9, 2022 5_25 PM.webm](https://user-images.githubusercontent.com/100699445/206747169-3656b069-528d-4207-bd90-b9edf16dcd63.webm)

I always have all the email part, did you do anything else than the update ? 

Waiting for your feedback

**Comment by Betafer** [comment]
> Hi @maofree
> 
> Thank you for your report ! I tried to reproduce your issue, as you can see :
> 
>  Untitled_.Dec.9.2022.5_25.PM.webm 
> I always have all the email part, did you do anything else than the update ?
> 
> Waiting for your feedback

the problem with the 2.4.0 module is that it doesn't send emails at all

**Comment by Maofree** [comment]
Hi @AureRita 
it happens only in some websites not in all
at this moment I've 9 websites with this problem, I've tried in many mode, but all have the same problem when the update goes wrong

can I pass you the access to 5 websites? so you can try by yourself (pass me your email)
in 20 websites went well

with the 2.3.3 all was ok on these 30 websites, instead with 10 of them with 2.4.0 there is something that is not right during the installation or during the update

however the module has hundreds of files, it seems to me more than 1500 files, they seem a bit many for a module like this one

**Comment by Maofree** [comment]
Hi
I've tried again right now and I've upgraded to 2.4.0 5 websites but look at this video
I think there is something strange
it is the same of the past tests but now ad the second update I don't get an error
https://watch.screencastify.com/v/oZZk7MR4N2lTjuRIxWbr

**Comment by Maofree** [comment]
upgraded all websites with 2.4.0
today is a lucky day :)
the last day I've done the same things but without a good solution

I close this ticket
thanks
bye
