### ISSUE TITLE
Configuration::haskey is ignorant of multishop configuration

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#30373]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The call of `Configuration::haskey` without the optional `$id_shop` returns false if the key exists in the current shop context, but does not exist as default configuration (`select * from ps_configuration where id_shop is null and id_shop_group is null and name ='[configuration name]'`).

### Expected behavior

I expect for `Configuration::haskey('[configuration name]')` to return true, if we are in a specific shop context and that configuration exists in that shop.

I already found twice code in PrestaShop, that expects this function to return true in the case that a configuration exists in the current shop context.

The code in `FrontController::getShopLogo()` is an example:
```
    public function getShopLogo(): array
    {
        if (!Configuration::hasKey('PS_LOGO')) {
            return [];
        }

        $logoFileName = Configuration::get('PS_LOGO');
```
Here `Configuration::get('PS_LOGO')` looks up the configuration in the current shop context, but `Configuration::hasKey('PS_LOGO')` does not take in account the current shop context.

Another example where `Configuration::haskey` is wrongly used is https://github.com/202-ecommerce/paypal/issues/121.

### Steps to reproduce

1. Install a Prestashop multi-shop environment as described in https://gist.github.com/lmeyer1/c40a19d880758bee11a1e8a2c5e819c3
2. In __Design - Theme & Logo__ set a logo file for each shop.
3. Connect to phpmyadmin (localhost:8018 is installed following 1.)
4. Run the query `select * from ps_configuration where name = 'PS_LOGO';`, and notice that there are now 4 keys: one for each of the three shops and a default for `id_shop is null and id_shop_group is null`
5. Delete the row with the (now unused) default value (query `delete from ps_configuration where id_shop is null and id_shop_group is null and name ='PS_LOGO'`)
6. Navigate to any page in the FO. You notice either:
   - a missing logo
   - an error 500 related to the missing logo (I noticed it with classic theme in the checkout)

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Thanks for the well detailed bug report :clap: :rocket: 
Ping @PrestaShop/prestashop-core-developers could someone please reproduce the issue, it's too technical!

Related to #22581

Thanks!

**Comment by cruftex** [comment]
@hibatallahAouadni it is not related to #22581. 

Reviewing the (little) code around I can find two  more bugs.

`Configuration::hasKey` is called first in this pattern, however, it does not load the configuration as `Configuration::get` does.

 `getShopLogo` allows for a template override but calculates the sizes with the configured logo:

````php
        $logoFileDir = _PS_IMG_DIR_ . $logoFileName;

        if (!file_exists($logoFileDir)) {
            return [];
        }

        list($logoWidth, $logoHeight) = getimagesize($logoFileDir);

        return [
            'src' => ($this->getTemplateVarUrls()['img_ps_url'] ?? _PS_IMG_) . $logoFileName,
            'width' => $logoWidth,
            'height' => $logoHeight,
        ];
````

@Oksydan: is that intentional?

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/committers friendly reminder, can someone please try to reproduce this issue? 
Cause we have a PR to test 🙏 thanks in advance!

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Do you still encounter the same issue with 8.1.x?
Please check and feedback.

Thanks!

**Comment by Hlavtox** [comment]
@hibatallahAouadni The methods are still the same > same issue

**Comment by hibatallahAouadni** [comment]
@Hlavtox Did you reproduce it?

**Comment by kpodemski** [comment]
@Hlavtox @hibatallahAouadni 

The partial fix for this problem has been implemented in this PR:
https://github.com/PrestaShop/PrestaShop/pull/32941

**Comment by kpodemski** [comment]
Well, it's not a partial fix, it solves the problem mentioned in the issue, I'm closing it.
