### ISSUE TITLE
Unable to change country in address

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#30375]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

As a customer, I created my address with the wrong country. I want to change the country. This is how I do it:
- Place an order
- During checkout, click on edit address
- Change the country, save the address
- I notice, that now I have two addresses, the one with the incorrect country was not modified, but a new one with the new country was created.

It seems to be independent of the theme. I reproduced the same issue with classic theme and with classic-rocket.

### Expected behavior

I expect that my address is modified when I click on edit, and that a new address is created when I click on new address.

### Steps to reproduce

1. Setup an installation following https://gist.github.com/lmeyer1/c40a19d880758bee11a1e8a2c5e819c3, multishop setup is not needed
2. Add English (US) as a new language: In __International - Translation__ under __Add / Update a language__ select English.
3. Go to __Shipping - Carriers__, for the carrier `Prestashop default` under `Shipping locations and costs` select `Europe` and `Europe (non-EU)`
4. Go to __International - Locations - Countries__ and activate `Switzerland` and `France`
5. Use Chrome (just to have Dev tools available) and navigate to the FO, switch to English (just to have the screenshot in English)
6. Put an article into your cart and click on `Proceed to checkout`
7. Create your account
8. Fill in your address, but choose a wrong country (e.g. `City: Paris, Zip: 7500, Country: Switzerland`), click `Continue`
9. Now that you are on `Shipping method`, you remember that you typed a wrong Zip and Country. Now click on `Adresses / edit`
10. In the `My address` box, click on `Edit`
11. Hit `F12` or choose `Inspect`, notice this html code `<form method="POST" action="//localhost:8017/en/order?id_address=7" data-refresh-url="//localhost:8017/en/order?ajax=1&amp;action=addressForm">`. There is the number of your address (here `id_address=7`).
12. Choose Country: France and Zip: 75000
13. In Dev tools notice that the action of the form changed to `<form method="POST" action="//localhost:8017/en/order?id_address=0" data-id-address="0" data-refresh-url="//localhost:8017/en/order?ajax=1&amp;action=addressForm">`
15. Click continue, you arrive on `Shipping method`
16. Click again on `Adresses / edit`. 
17. Notice there are now two addresses, one in Switzerland and one in France. Instead of updating to incorrect address, a new one was created.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

I think you mistape your PHP version :sweat_smile: So, what's your PHP version? 
Waiting for your feedback.

Thanks!

**Comment by lmeyer1** [comment]
> I think you mistape your PHP version 😅 So, what's your PHP version?

Oh funny, I think this is github's editor !
See: the steps 1. to 16., The Prestashop version 1.7., the PHP version 18.
If there were a module version, I would have been forced to 19. 🤣

**Comment by lmeyer1** [comment]
>It seems to be independent of the theme. I reproduced the same issue with classic theme and with classic-rocket.

After investigation, the problem is in the theme. Both `classic` and `classic-rocket` are affected.

**Comment by sallemiines** [comment]
Hello @lmeyer1 

Thanks for reporting the issue.

I reproduced your issue  with **PS 1778 and PS 1787** 
you can see the attached screen shots 

![iss4](https://user-images.githubusercontent.com/31663369/204290543-6b05fc83-32cb-48cd-888e-a69d5c50bff7.png)


![iss1](https://user-images.githubusercontent.com/31663369/204290506-623c206f-b2c4-44c0-826e-ee306ae532dd.png)

![iss2](https://user-images.githubusercontent.com/31663369/204290526-3ea65e6c-67cb-44f6-b516-aff2575e7ded.png)


**With PS 1778** 

![image (3)](https://user-images.githubusercontent.com/31663369/204290950-fbbacb9e-9f0d-4a1d-ae5a-00e34822f72a.png)



**With PS 800** ( the issue not exist )

![image (2)](https://user-images.githubusercontent.com/31663369/204290876-605d1630-030d-434a-a731-1f93b328227b.png)


Thank you !

**Comment by sallemiines** [comment]
@lmeyer1 

I will close this issue cauz it's already fixed on `PS800` , please note that you can always create a new one if further information pops up.

Thank you

**Comment by lmeyer1** [comment]
@sallemiines 
What theme did you use in PS 8.0.0 ? As the bug is also related to the theme, it is not sufficient to close the issue if you didn't reproduce it in PS 8.0.0.
I noticed that the problem was present in Prestashop/classic-theme and fixed it there.

**Comment by lmeyer1** [comment]
This issue should be reopened before all the questions are answered. Also, with PS 8.0.0 both the new classic theme and hummingbird should be tested.

**Comment by lmeyer1** [comment]
This problem was fixed in 8.0.0. I can't reproduce it anymore in PS 8.0.0 on docker.

**Comment by kpodemski** [comment]
@lmeyer1 thanks for the confirmation!
