### ISSUE TITLE
Sanity tests are KO on develop branch

### ISSUE THREAD

**Issue by nicosomb** [PrestaShop/PrestaShop#30389]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On each PR, sanity tests fail. For example https://github.com/PrestaShop/PrestaShop/pull/30378 or https://github.com/PrestaShop/PrestaShop/pull/30387 

```
 1) Install Prestashop
       should open the Install page:
     page.waitForSelector: Timeout 10000ms exceeded.
```

### Expected behavior

Test suite should be green unless there is verified issues in a given Pull Request.

### Steps to reproduce

Open a new PR and wait for testsuite. 

### PrestaShop version(s) where the bug happened

develop

**Comment by matks** [comment]
PR to be 100% sure it's not related to code changes https://github.com/PrestaShop/PrestaShop/pull/30390

**Comment by matks** [comment]
It breaks also on 8.0.x https://github.com/PrestaShop/PrestaShop/pull/30391

**Comment by matks** [comment]
It seems that locking GH env target to ubuntu-20.04 instead of latest (ubuntu-22.04) fixes CI https://github.com/PrestaShop/PrestaShop/pull/30392

**Comment by sallemiines** [comment]
Hello @nicosomb 

Thanks for reporting the issue, it's a regression, you can see the attached screenshot


![`HelperList`-`callback`-is-not-called-when-column-data-is-null-by-PululuK-·-Pull-Request-30387-·-PrestaShop-PrestaShop](https://user-images.githubusercontent.com/31663369/203747334-711e37eb-b47d-4386-a142-df53b371146b.png)

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/30396

**Comment by nicosomb** [comment]
Thank you @atomiix @matks
