### ISSUE TITLE
Add an exit button in tablet and phone menu 

### ISSUE THREAD

**Issue by ElodieOS** [PrestaShop/PrestaShop#30382]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Today, you can only leave the menu by clicking outside. Even though this is a common behavior today, there is no indication. This can lose the less technology-savvy users.

### Describe the solution you'd like

It would be better to have the same behavior as dotcom (clicking outside and exit button).

### Additional context

![image](https://user-images.githubusercontent.com/113457393/203505810-74a5beb0-7723-4b27-8ecc-30db2c9d3777.png)

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by florine2623** [comment]
Hello @ElodieOS ,

Thanks for the design and the specifications 👏 🚀
Let's ping the Product Team 😉 Stay tuned!

Ping https://github.com/orgs/PrestaShop/teams/product-team https://github.com/orgs/PrestaShop/teams/ux-team we have a new design proposal, enjoy it 😉
