### ISSUE TITLE
`HelperList` `callback` is not called when column data is null

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#30386]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

`HelperList` `callback` is not called when column data is null

### Expected behavior

The callback must always be called even if the column value is empty.  See the screen after the PR

![image](https://user-images.githubusercontent.com/16455155/203656465-9feea5d5-a5db-4df8-ad70-08cb8c9557f2.png)

### Steps to reproduce

Add module `modules/mymodule/mymodule.php`
```php

<?php

if (!defined('_PS_VERSION_')) {
    exit;
}

class Mymodule extends Module
{
    public function __construct()
    {
        $this->name = 'mymodule';
        $this->tab = 'front_office_features';
        $this->version = '1.0.0';
        $this->author = 'PululuK';

        parent::__construct();

        $this->displayName = $this->l('My module ');
        $this->description = $this->l('Module ');
        $this->confirmUninstall = $this->l('Are you sure you want to uninstall my module?');
        $this->ps_versions_compliancy = ['min' => '1.7', 'max' => _PS_VERSION_];
    }

    public function install()
    {
        return parent::install() && $this->registerHook('actionAdminCartsListingFieldsModifier');
    }

    /**
     * @param type $params
     */
    public function hookActionAdminCartsListingFieldsModifier($params)
    {
        if(!isset($params['checkout_session_data'])) {
	    $params['select'] .= ' , checkout_session_data';
	}

        $params['fields']['checkout_session_data'] = [
            'title' => $this->l('My custom column'),
            'callback' => 'getMyCallBack',
            'callback_object' => $this,
            'orderby' => false,
            'search' => false,
        ];
    }

    public function getMyCallBack($data, $row)
    {
        return 'MY_CUSTOM_ROW_DATA';   
    }
}


```

Go to `BO > Orders > Carts` and see the error. 
When the column data is null, it displays `--` instead of displaying `MY_CUSTOM_ROW_DATA`. (you can force to reproduce the issue, in database edit an cart is `ps_cart` set `checkout_session_data` is NULL)

![image](https://user-images.githubusercontent.com/16455155/203656887-879fb3a5-23dc-4610-9862-9d339c4fd016.png)

## Workaround 

You can get around this by adding a column in your select that will always have a non-null value.

```php
    /**
     * @param type $params
     */
    public function hookActionAdminCartsListingFieldsModifier($params)
    {
        if(!isset($params['my_custom_column'])) {
	    $params['select'] .= ' , 1 as my_custom_column';
	}

        $params['fields']['my_custom_column'] = [
            'title' => $this->l('My custom column'),
            'callback' => 'getMyCallBack',
            'callback_object' => $this,
            'orderby' => false,
            'search' => false,
        ];
    }

```

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

N/A

### If your bug is related to a module, specify its name and its version

N/A

**Comment by sallemiines** [comment]
Hello @PululuK 

Could you please provide us you prestaShop and PHP version ? 

Thank you !

**Comment by PululuK** [comment]
> Hello @PululuK
> 
> Could you please provide us you prestaShop and PHP version ?
> 
> Thank you !

Please read the issue description :)

**Comment by PululuK** [comment]
@sallemiines I took a lot of time and I tried to give as much information as possible, could you also take the time to read the issue and avoid putting labels for nothing? Why `NMI` exactly ?

**Comment by sarahdib** [comment]
> @sallemiines I took a lot of time and I tried to give as much information as possible, could you also take the time to read the issue and avoid putting labels for nothing? Why `NMI` exactly ?

Hello @PululuK I understand you took the time to give us the more information as possible and thank you for that :) . But we need the version in order to reproduce. When you give us this version we will remove the label NMI 

Thank you :)

**Comment by PululuK** [comment]
Yes precisely I indicated `N/A` (Not Applied).
