### ISSUE TITLE
Deleting an Address cause customer's inability to complete an order

### ISSUE THREAD

**Issue by abramofranchetti** [PrestaShop/PrestaShop#30393]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I've found this issue because a customer of my agency ha reported it to me.
Essentially in a customer add a product to cart, then begin the checkout process select ad address but at the moment of choosing the carrier or the payment method he abandon the cart, in example because he want to browse other products on shop the product remain in cart.
If the address that the customer had choosen for the shipping is then deleted (by customer in his customer account or by shop manager in the backoffice) the when the customer returns to the cart, independently to what address now he choose to ship or everything he do, he will not be able to complete the order because an error of type "Unfortunately, there are no carriers available for your delivery address.". That until he empty his cart. There is notingh else the customer can do.

That bug occurs because in the table ps_cart_product is stored the id of the deleted address in the column id_address_delivery, and the function the calculate the carrier available for the order fail because of the missing address (because it was deleted).

the problem is in the getPackageList() function in the class Cart. That function use the id_address_delivery stored in the cart_product table that can be deleted in the meantime. 

If i've some time i will make a pull request to fix this bug, because i've already fix it in production.

The bug is indipendent of the fact that the address was used before in on order (and so is not really deleted but flagged as deleted = 1) or is an address never used in an order (and so it is really deleted from the table)

### Expected behavior

Deleting an address shouldn't cause any problems ;)

### Steps to reproduce

login as a customer
create new address "TEST"
add product to cart
select TEST as address for the order and proceed
select a carrier for the order
exit the cart (go in home page for example)
now go in backoffice and delete the "TEST ADDRESS"
now return to cart and try to checkout the order. 

SEE THE ATTACHED VIDEO
[Registrazione schermo 2022-11-23 alle 17.14.39.zip](https://github.com/PrestaShop/PrestaShop/files/10083041/Registrazione.schermo.2022-11-23.alle.17.14.39.zip)

### PrestaShop version(s) where the bug happened

1.7.8.7  and 8.0

### PHP version(s) where the bug happened

indipendent from php version

**Comment by sallemiines** [comment]
Hello @abramofranchetti 

Thanks for reporting the issue . 
I reproduce the issue with `PS1778 + PHP 7.3 ` `PS1787 + php 7.4` and `PS800 + PHP 8.0`, you can see the attached screen record 


[Untitled_ Nov 24 2022 11_00 AM.webm](https://user-images.githubusercontent.com/31663369/203755158-03856311-fbbd-4f6e-8077-b63751e98bd9.webm)

Thank you !

**Comment by Hlavtox** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/30350
Fixed by https://github.com/PrestaShop/PrestaShop/pull/30349

**Comment by abramofranchetti** [comment]
> Duplicate of #30350 Fixed by #30349

Yes but the "simple" solution found is not correct .

Please, notice the this simple solution, which I also thought about, is incorrect.
The code in that fix,
`$sql = 'UPDATE ' . _DB_PREFIX_ . 'customization SET id_address_delivery = 0 WHERE id_address_delivery = ' . $this->id;`

**does not consider that the field "id_address_delivery" is part of the primary key of the table cart_product** and setting it to zero **can cause a "duplicate key"** if there are two or more rows with the other key fields with the same value (id_cart,id_product,id_product_attribute,id_customization).

f**urthermore the fix does not work if the address is already used in an order**. In that case in fact the address is not really deleted from the table but only flagged as deleted, and the method "deleteCartAddress" (that @stoycho have fixed) is not called. In fact the function "deleteCartAddress" is only called when the address in "new" and never used in other orders.

The correct way to proceed to the solution is already been found by prestashop team (in particular developers of ps_checkout module) and it is calling the "setProductAddressDelivery" function that take care of not generating potential "duplicate key" error and fixing also the customization table.

**Comment by Hlavtox** [comment]
@abramofranchetti Good to know!!! If you know how to fix it better, make a PR please. 🙏

**Comment by sallemiines** [comment]
> Duplicate of #30350 Fixed by #30349

Thank you @Hlavtox for your check and feedback

**Comment by sallemiines** [comment]
Hello @abramofranchetti ,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #30350 .
It's already fixed with this pr [#30349](https://github.com/PrestaShop/PrestaShop/pull/30349) ! 

Thank you
