### ISSUE TITLE
Module Social media follow links

### ISSUE THREAD

**Issue by charlotte2354** [PrestaShop/PrestaShop#30407]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

hello, there is a problem with the "Module Social media follow links". Indeed, there are many networks available but there is no tiktok. While tiktok is a must. How to make it available? Thank you for your help

### Expected behavior

I would like to be able to add the link of my tiktok account, with the appropriate icon on the front office

### Steps to reproduce

1 : go to back-office 
2 : Go to Module Social media follow links 
3: view all available URLs 
4 : we can't find tiktok

### If your bug is related to a module, specify its name and its version

Module Social media follow links

**Comment by hibatallahAouadni** [comment]
Hello @charlotte2354 

Thanks for your suggestion!
It seems your issue looks like a feature and a good one :rocket: So changing the issue from a bug to a feature.

The Maintainer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [hiring a specialist](https://www.prestashop.com/en/experts) to help you create it. 

If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know! 

Thank you

**Comment by florine2623** [comment]
Hello @charlotte2354 ,

This feature has been implemented. You can update your module to v2.3.2.
<img width="779" alt="Screenshot 2024-01-18 at 16 28 32" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/627c3138-2715-4bd7-8846-56420a1323e8">

I'm closing this issue.
