### ISSUE TITLE
Wrong discount calculation on 2 or more free shipping coupon applied on cart (voucher discount value)

### ISSUE THREAD

**Issue by hawe25** [PrestaShop/PrestaShop#30405]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,
I was making my own module and found this bug, and manage to reproduce in the newest stable available prestashop (1.7.8.7)

When you apply 2 or more cart rule (voucher) with free shipping, both voucher line amount is calculating real value + shipping cost. 
![image](https://user-images.githubusercontent.com/10786830/203952670-fee4ecf3-a044-44ed-b134-e170959a1b05.png)

The Discount(s) line become mismatch with the sum of voucher line.

### Expected behavior

The voucher test10 is a 10% voucher, it must be resulted -€2,33 and voucher testamount10 is a -€10 amount voucher, it must be resulted -€10.00

Maybe the best approach is splitting "shipping discount" amount into another line, and the voucher lines are only the amount you get from each voucher.

### Steps to reproduce

1. I set shipping cost value is 8.00 without any taxes and weight (absolute value for every product without considering weight and taxes)
2. Created 2 new cart rules (Catalog > Discounts) with any discount (my case is one with 10% discount, and the other is 10 amount discount), set free shipping true, then put random code and highlight to make things easier.
3. Go to front office, put some item on cart and apply both newly created coupon.
4. You will see this:
![image](https://user-images.githubusercontent.com/10786830/203949326-b7234e36-bb15-4d08-87bb-20d3850f4477.png)

### PrestaShop version(s) where the bug happened

fresh install on 1.7.8.7

### PHP version(s) where the bug happened

7.4

**Comment by sallemiines** [comment]
Hello @hawe25 

Thanks for reporting the issue .
Following your steps, unfortunately I didn't manage to reproduce your issue ! 
I checked the issue with `PS1.7.8.7` and `PS 8.0.0` you can see the attached screen record

[Untitled_ Nov 28, 2022 9_24 AM.webm](https://user-images.githubusercontent.com/31663369/204229435-e6fdfc19-aca6-4023-a3b5-7427fcbae17b.webm)

**Comment by hawe25** [comment]
> Hello @hawe25
> 
> Thanks for reporting the issue . Following your steps, unfortunately I didn't manage to reproduce your issue ! I checked the issue with `PS1.7.8.7` and `PS 8.0.0` you can see the attached screen record
> 
>  Untitled_.Nov.28.2022.9_24.AM.webm

Hi sallemiines,
I saw on video (0:12) the free shipping must be set as true for both coupons.
As the bug happens if there was more than 1 free shipping coupon applied.

And you have to apply a shipping cost on Shipping > Carriers
![image](https://user-images.githubusercontent.com/10786830/204253352-24b501a6-8deb-4e3d-898b-18e13ba21a83.png)

I hope you can reproduce by this details.

Thanks,
Hans

**Comment by geimsdin** [comment]
Why is this closed without even testing it correctly as per hawe description? I tried and can reproduce the bug.

Simone

**Comment by geimsdin** [comment]
@sallemiines

**Comment by MultiTech-MS** [comment]
@sallemiines I saw in an answer on the forum of the paypal module that it was an existing issue that was fixed in 1.7.8.6
But it doesn't, I also have this issue on a Prestashop 1.7.8.7

Just add two vouchers having "free shipping" activated in a cart and... witness

I though it might come from the tax calculations (included or excluded) on the products, total and/or carriers... 
But it doesn't add up.

**Comment by geimsdin** [comment]
@sallemiines reopen please
