### ISSUE TITLE
WebP in file manager not displayed anymore since upgrading to 8.0.0

### ISSUE THREAD

**Issue by nitschis** [PrestaShop/PrestaShop#30412]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I upgraded my shop to the latest 8.0.0 version.

Ever since then, when I open the file browser, WebP images are not displayed at all, like they are gone.

### Steps to reproduce

Open file manager on an existing installation using WebP and none of the images are displayed or selectable.

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.3.24

**Comment by sallemiines** [comment]
Hello @nitschis ,
 Thanks for reporting the issue.

Could you please provide us : The old version of the store you had before the upgrade, as well as the auto-upgrade module's version .

Thank you !

**Comment by HanaRebaiQA** [comment]
Hello @nitschis 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thank You!

**Comment by nitschis** [comment]
Sorry, I had to revert back to the lastest backup.
