### ISSUE TITLE
Product price entry

### ISSUE THREAD

**Issue by necatatay** [PrestaShop/PrestaShop#30411]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Yes
I am not a writer or developer, I just build and deliver websites to my customers and I have to use this feature in my own project. Your popularity will increase even more.

### Describe the solution you'd like

When entering the product, there should be a currency option in the pricing. Those who want $, who want €, who want ₺, can enter by choosing whatever they want. In the store, the currency translation will work and it will be shown as a single currency.
I am sharing a sample site admin management demo
https://www.proticaret.org/eticaret-demo- Sayfasi
https://www.proticaret.org/eticaret-demo- Sayfasi
http://demo.proticaret.org/admin/default.aspx?MNID=52
https://prnt.sc/dHH1SiAqO5xJ

### Alternatives you've considered

https://www.proticaret.org/eticaret-demo- Sayfasi

### Additional context

https://www.proticaret.org/eticaret-demo- Sayfasi
https://www.proticaret.org/eticaret-demo- Sayfasi
http://demo.proticaret.org/admin/default.aspx?MNID=52
https://prnt.sc/dHH1SiAqO5xJ

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by necatatay** [comment]
I am not a writer or developer, I just build and deliver websites to my customers and I have to use this feature in my own project. Your popularity will increase even more.

When entering the product, there should be a currency option in the pricing. Those who want $, who want €, who want ₺, can enter by choosing whatever they want. In the store, the currency translation will work and it will be shown as a single currency.

I am sharing a sample site admin management demo
https://www.proticaret.org/eticaret-demo- Sayfasi
https://www.proticaret.org/eticaret-demo- Sayfasi
http://demo.proticaret.org/admin/default.aspx?MNID=52
https://prnt.sc/dHH1SiAqO5xJ

**Comment by sallemiines** [comment]
Hello @necatatay  ,

Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments.
Please be aware that there is no guarantee that this feature will be developed anytime soon.
So, we're waiting for your PR rocket

Thank you !

**Comment by sallemiines** [comment]
Hello @necatatay !

I think that your feature-issue is talking about adding currencies into the shop ? 
Could you please check this screen record , and provides us if this is your feature-issue goal?

[Untitled_ Nov 28, 2022 9_37 AM (1).webm](https://user-images.githubusercontent.com/31663369/204232272-dd261bb3-3d51-4543-899e-4f19669fcb0f.webm)

Please check & feedback !

**Comment by necatatay** [comment]
Hello
I'm not talking about adding currency.
You can see it in detail in the link I gave you in the e-mail before. then
you can understand what i mean. store currency should always be ₺ when
entering the product

SAYGILARIMLA

https://necahosting.com/
*https://e-ticaretmodul.com/ <https://e-ticaretmodul.com/>*

*https://81iltoptan.com/ <https://81iltoptan.com/>*
*https://trendurunleri.com/ <https://trendurunleri.com/>*
https://www.necaticaret.com/
*https://necaweb.site/ <https://necaweb.site/>*
    Necat ATAY
  0532 465 33 20


ines sallemi ***@***.***>, 28 Kas 2022 Pzt, 11:43 tarihinde
şunu yazdı:

**Comment by sallemiines** [comment]
@necatatay Thanks for you feedback ! 

Could you please provide us your shop version, and if you could switch your theme to Classic theme ? 

Thank you !

**Comment by necatatay** [comment]
1.7.8.7
ok

SAYGILARIMLA

https://necahosting.com/
*https://e-ticaretmodul.com/ <https://e-ticaretmodul.com/>*

*https://81iltoptan.com/ <https://81iltoptan.com/>*
*https://trendurunleri.com/ <https://trendurunleri.com/>*
https://www.necaticaret.com/
*https://necaweb.site/ <https://necaweb.site/>*
    Necat ATAY
  0532 465 33 20


ines sallemi ***@***.***>, 28 Kas 2022 Pzt, 12:36 tarihinde
şunu yazdı:

**Comment by necatatay** [comment]
I switched to the classic theme, I've been waiting for you for 1 hour, why
did you switch to the classic theme, I can't understand it
Kind regards


SAYGILARIMLA

https://necahosting.com/
*https://e-ticaretmodul.com/ <https://e-ticaretmodul.com/>*

*https://81iltoptan.com/ <https://81iltoptan.com/>*
*https://trendurunleri.com/ <https://trendurunleri.com/>*
https://www.necaticaret.com/
*https://necaweb.site/ <https://necaweb.site/>*
    Necat ATAY
  0532 465 33 20


NECAT ATAY ***@***.***>, 28 Kas 2022 Pzt, 12:51 tarihinde şunu
yazdı:

**Comment by sallemiines** [comment]
@necatatay 

Sorry I didn't manage to have some configuration into your shop cauz it's with the turkish language ! 

Could please set your default currency `LIRA` in international > localization  , you can see the screen-record and let us know if that solve your probleme !
 
[Untitled_ Nov 28 2022 3_27 PM (1).webm](https://user-images.githubusercontent.com/31663369/204302851-b0a6b95e-3de0-4191-8a84-f9ea4d06ac36.webm)

Waiting for you ! 
Thank you !

**Comment by HanaRebaiQA** [comment]
Hello @necatatay 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thank You!
