### ISSUE TITLE
Why is v8.0 not available for download on your website?

### ISSUE THREAD

**Issue by K0-RR** [PrestaShop/PrestaShop#30410]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, I wanted to download the latest release however it's not on the prestashop.com. I know about GitHub releases, I was just curious what's holding You back from updating it there.

### Steps to reproduce

Go to https://www.prestashop.com/en/download
The version you get is not the newest

### PrestaShop version(s) where the bug happened

n/a

**Comment by Hlavtox** [comment]
What Prestashop company has on their website is no longer relevant, the main download location you get on https://www.prestashop-project.org/ is now here, github releases.

Why the company does not have v8 available right now is for somebody else to answer, but my guess is because the upgrade process is not yet available. 👍 (https://github.com/PrestaShop/PrestaShop/issues/29215)

**Comment by matks** [comment]
> What Prestashop company has on their website is no longer relevant, the main download location you get on https://www.prestashop-project.org/ is now here, github releases.

As said by @Hlavtox, PrestaShop company chooses what is published on prestashop.com but this GitHub repository belongs to PrestaShop project.

So @RDKRACZ if you want to know why is v8.0 not available for download on your website I think it's better to ask on prestashop.com help channel ;)

**Comment by alfonsolr09** [comment]
can i upgrade from 1.7.8.7 to v 8.0?? with autoupgrade module??

**Comment by kpodemski** [comment]
@alfonsolr09, it is possible using the `develop` version of it

you can clone the module, `composer install`, install a module and then try to upgrade using this version

one thing that is highly recommend is to set "Disable non-native modules" to true, this way there's a high chance that everything will be ok with the upgrade :)

**Comment by matks** [comment]
Hello there, the discussion was out of the scope of the project (then my answer is out of scope too) but I just wanted to mention v8.0.x zip is now available on prestashop.com (which is, again, a decision from PrestaShop company, not from the project) 😉
