### ISSUE TITLE
Help documentation - Opens up on the whole window instead of in a sidebar

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#30424]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The Help documentation is taking the whole page :

https://user-images.githubusercontent.com/16019289/204311270-43030276-a834-4d79-9647-8b8ac665b8f7.mov

This happens on a few different pages:
- Webservice edition/creation
- Category edition/creation
- Currency edition/creation
- SEO & URLs edition/creation

### Expected behavior

The Help card should be opened in a sidebar.

### Steps to reproduce

1. Go to BO > Advanced Parameters > Webservices
2. Click Add a new webservice key
3. Click on the Help button
4. See the documentation on the whole page

### PrestaShop version(s) where the bug happened

1.7.8.7, 1.7.8.8, 8.0.0, develop

### PHP version(s) where the bug happened

7.4

**Comment by sallemiines** [comment]
Hello @florine2623 

Thanks for reporting the issue.

I reproduce the issue with `PS 1.7.8.7`, `PS 1.7.8.8`,` PS 8.0.0`, and `develop`

[Untitled_ Nov 28 2022 4_19 PM.webm](https://user-images.githubusercontent.com/31663369/204314514-668cf135-4122-4b1c-a42a-5b157d049519.webm)

Thank you !

**Comment by florine2623** [comment]
Fixed on PS 9.0.0
