### ISSUE TITLE
Create an account after placing an order as a guest

### ISSUE THREAD

**Issue by paulnoelcholot** [PrestaShop/PrestaShop#30428]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If I create an account from my order details after placing an order as a guest, the creation fails

https://watch.screencastify.com/v/JeDN19m1IAGZpTnPbm15

### Expected behavior

Account creation should be done

### Steps to reproduce

On FO : 
1. Do not log in as an account
2.  Add to cart a product
3. Proceed to checkout
4. Enter personal information but no password
5. Continue
6. Enter adresses
7. Choose shipping and payment method
8. Place Order
9. Scroll down in the order details
10. Enter your personnal information and password
11. Save
12. Enter your Email and Password
13. Sign in
14. See error

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @paulnoelcholot 

This issue has been fixed on 8.0.0 :tada: 
Closing the issue as your issue is duplicate of #14414

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #14414
