### ISSUE TITLE
Customer Groups - Can't add a new customer group when saving Default groups options

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#30422]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In BO, if I save the Default groups options I can't add any other customer groups even after refreshing the page.

https://user-images.githubusercontent.com/16019289/204299467-7dbe6d01-9cfd-4273-b12f-b50e8acccb3a.mov

<img width="1227" alt="Screenshot 2022-11-28 at 15 14 06" src="https://user-images.githubusercontent.com/16019289/204299760-71003035-31b1-4e0f-9e52-02e31f8168f0.png">

### Expected behavior

The add buttons should still be displayed after saving the Default group options :
<img width="1222" alt="Screenshot 2022-11-28 at 15 14 13" src="https://user-images.githubusercontent.com/16019289/204299852-e9659692-a47a-426d-9ee2-32a71229862e.png">

### Steps to reproduce

1. Go to BO > Shop parameters > Customer settings > Groups
2. Save Default groups options
3. Try to add a new Customer group : can do it, Add button are not displayed NOK

### PrestaShop version(s) where the bug happened

1.7.8.7, 1.7.8.8, 8.0.x, develop

### PHP version(s) where the bug happened

7.4

**Comment by sallemiines** [comment]
Hello @florine2623 

Thanx  for reporting the issue.

I reproduce the issue with `PS 1.7.8.7` `PS 800` and `develop` , you can check the screenshot

![Groups-•-1787](https://user-images.githubusercontent.com/31663369/204308431-1d38c5de-1355-4ef8-83b1-31534abbf973.png)

Thank you !
