### ISSUE TITLE
Administration - Addons marketplace mention should be deleted for 8.0.x and next versions

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#30425]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

For 8.0.x and later versions, this option in `Advanced Parameters > Administration` should be deleted : 

<img width="1123" alt="Screenshot 2022-11-28 at 16 24 03" src="https://user-images.githubusercontent.com/16019289/204315439-2c70dd0a-37dc-4c7d-a277-eeb2e6f8ea2a.png">

### Describe the solution you'd like

Remove the feature from the core and the doc v8

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by sallemiines** [comment]
Hello @florine2623  ,

Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments.
Please be aware that there is no guarantee that this feature will be developed anytime soon.

Thank you !

**Comment by Progi1984** [comment]
May be to link to EPIC #28771

**Comment by MatShir** [comment]
I suggest to completely remove the feature, now since everything has been moved into a module.

**Comment by MatShir** [comment]
@Progi1984 yes, i have added it to the EPIC
