### ISSUE TITLE
Password not entered in my personal information

### ISSUE THREAD

**Issue by paulnoelcholot** [PrestaShop/PrestaShop#30427]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If I create a new user account on from the FO and I go to my personal information, my password is not filled in.

https://watch.screencastify.com/v/ZSlphyxhSrKEnPXHU1jG

### Expected behavior

My password should be filled in

### Steps to reproduce

On FO :
1. Create a new account
2. Go on Your account > Information
3. Password is not filled in.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

**Comment by kpodemski** [comment]
No, your password shouldn't be filled in :-)

**Comment by hibatallahAouadni** [comment]
@paulnoelcholot 
FYI: Password shouldn't be filled in neither display it in this page cause it's kind of breach of security.
