### ISSUE TITLE
Missing error message if there is no possible payment method

### ISSUE THREAD

**Issue by paulnoelcholot** [PrestaShop/PrestaShop#30420]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

From the BO, I deactivate the payment modules
From the FO, I want to place an order. In the order confirmation, I cannot validate the order, but I do not have an error message to inform me that there is no payment method available. This is a regression on version 1.7.8.7

### Expected behavior

The error message should be present

### Steps to reproduce

1. On BO, deactivate the payment modules
2. On FO, add to cart a product
3. Proceed to checkout > Proceed to checkout
4. Continue
5. Continue
6. See error

https://watch.screencastify.com/v/DbeNupKgqDsM1mcvPXrQ

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

**Comment by sallemiines** [comment]
Hello @paulnoelcholot 

Thanx  for reporting the issue.

I reproduced your issue with `PS1787` **NOK**  and`PS 800` **OK** , it's a regression nice catch ! 
You can see the screen shots 

**PS1787** NOK  : the error message is not displayed
![1787](https://user-images.githubusercontent.com/31663369/204297512-31e37ce6-7049-4e80-a4d1-9fff0f658a00.png)


**PS800** OK the error message is  displayed

![800](https://user-images.githubusercontent.com/31663369/204297627-57ef6a16-9fc8-43cf-b3df-b2d1c1ae045f.png)


Thank you !

**Comment by paulnoelcholot** [comment]
The problem is not present on 1.7.8.7

![image](https://user-images.githubusercontent.com/112863083/204499136-66582469-9ecb-43ee-81d5-89702d867da5.png)

**Comment by SharakPL** [comment]
This may be a bug with [**ps_checkout**](https://github.com/PrestaShopCorp/ps_checkout) module which is polluting **$payment_options**:

![obraz](https://user-images.githubusercontent.com/5007456/207487808-89e4c506-636d-45be-a539-0b703bc0c400.png)

This variable should be empty for alert to appear (classic theme):

![obraz](https://user-images.githubusercontent.com/5007456/207488333-59809641-fbc2-421b-8cfe-f3a0dc37e66d.png)

**Comment by MartOpenscop** [comment]
Hello, The problem is not present on 1.7.8.8 after followed the previous steps described by @paulnoelcholot 

Here is a screeenshot : 
![image](https://user-images.githubusercontent.com/120645968/207873455-ed5802a0-c965-4465-8423-a12b528da455.png)

effectively, if i enable ps_checkout, the message do not appear. It seems because of the ps_checkout module.

**Comment by hibatallahAouadni** [comment]
Hello everyone,

Indeed the issue is related to ps_checkout, and it's not present in 8.0.0 as @sallemiines mentioned above.
Closing the issue and thanks everyone for your efforts 🙏 

Thanks!

**Comment by SharakPL** [comment]
@hibatallahAouadni afaik this is the issue tracker for native modules so we should keep it open until it's fixed in the module.
