### ISSUE TITLE
Billing address different from delivery address

### ISSUE THREAD

**Issue by paulnoelcholot** [PrestaShop/PrestaShop#30426]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If my billing address is different from the delivery address, I can complete the form without error, but an error occurs during validation.

https://watch.screencastify.com/v/SO6kYYEHNExQ27B7cjNV

### Expected behavior

The error should be reported during the validation of the carrier.

### Steps to reproduce

On FO:

1. add to cart a product
2. Proceed to checkout
3. Choose a delivery address in France
4. Choose a Invoice address in US
5. Choose a Shipping method
6. Choose a payment method
7. Place order
8. see error

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

**Comment by sallemiines** [comment]
Hello @paulnoelcholot 


We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of [#21898](https://github.com/PrestaShop/PrestaShop/issues/21898)
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by sallemiines** [comment]
Duplicate of[ #21898](https://github.com/PrestaShop/PrestaShop/issues/21898)
