### ISSUE TITLE
contactform v4.3.0 - Addons Marketplace mention should not be displayed

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#30431]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

This alert should not be displayed:

<img width="1218" alt="Screenshot 2022-11-28 at 17 42 58" src="https://user-images.githubusercontent.com/16019289/204334712-15a52b3b-c262-4f74-b75a-29cafa84708c.png">

### Expected behavior

For versions PS 8.0.0 and later, this alert should not be displayed.

### Steps to reproduce

1. Go to BO > Modules Manager > Search contactform > Click configure
2. See Addons marketplace alert redirecting to Addons Marketplace

### PrestaShop version(s) where the bug happened

1.7.8.7, 1.7.8.8, 8.0.0, develop

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

contactform v4.3.0

**Comment by sallemiines** [comment]
Hello @florine2623 

Thanks for reporting the issue.

I reproduced the issue with `PS 1787` `PS 1788` `PS 800` and `develop `

![image](https://user-images.githubusercontent.com/31663369/204481220-3b78952c-e3c8-46c4-94b9-c46183b34c45.png)

Thank you !

**Comment by PrestaEdit** [comment]
Fixed on the v4.4.0 (not yet released) : https://github.com/PrestaShop/contactform/pull/57

**Comment by Progi1984** [comment]
@florine2623 May be to link to #28771

**Comment by marsaldev** [comment]
Fixed by https://github.com/PrestaShop/contactform/pull/57
