### ISSUE TITLE
Children list of hook actionCategoryDelete empty

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/PrestaShop#30435]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I delete a category, I want to be able to know the ids of the deleted categories and its children.

I try to listen the hook actionCategoryDelete but the list of children seems empty.

### Expected behavior

Get all deleted ids (parent and child)

### Steps to reproduce

1/ Use the hook actionCategoryDelete

### PrestaShop version(s) where the bug happened

1.7.5

### PHP version(s) where the bug happened

7.2

**Comment by sallemiines** [comment]
Hello @BenTen 

Thanks for reporting the issue.

Following your steps, unfortunately I didn't manage to reproduce your issue, you can see the screen record 

[Quality Assurance • presta1787.webm](https://user-images.githubusercontent.com/31663369/204537816-594077f0-76fe-4e05-8074-5b8412bfc8e8.webm)

I used the module  [ps_qualityassurance.zip](https://github.com/PrestaShop/PrestaShop/files/10113292/ps_qualityassurance.zip), could you please try with it ? 

Please check and feedback.

Thank you !

**Comment by BenTen** [comment]
@sallemiines can't read the file you up.
_(works with chrome, sorry)_
I will check it.

**Comment by sallemiines** [comment]
> @sallemiines can't read the file you up. _(works with chrome, sorry)_ I will check it.

You can clone it from Github  ^^ 

https://github.com/PrestaShop/ps_qualityassurance

**Comment by BenTen** [comment]
My bad, json was not used correctly.

**Comment by hibatallahAouadni** [comment]
@BenTen thanks for your feedback.
