### ISSUE TITLE
Duplicated code

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#30448]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The two classes `\PrestaShop\PrestaShop\Adapter\RoundingMapper` and `\PrestaShop\PrestaShop\Adapter\Number\RoundModeConverter` and their methods `\PrestaShop\PrestaShop\Adapter\RoundingMapper::mapRounding()` and `\PrestaShop\PrestaShop\Adapter\Number\RoundModeConverter::getNumberRoundMode()` are duplicates.

Only `\PrestaShop\PrestaShop\Adapter\Number\RoundModeConverter::getNumberRoundMode()` is used.

### Expected behavior

`\PrestaShop\PrestaShop\Adapter\RoundingMapper::mapRounding()` is duplicate and unused. It should be removed from code.

### Steps to reproduce

1. Search for all occurrences of `mapRounding` in the whole Prestashop 8.0.0 codebase.
2. Notice that there is only one, the definition.
3. Search for all occurrences of `getNumberRoundMode` in the whole Prestashop 8.0.0 codebase.
4. You will find it.

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

any

**Comment by HanaRebaiQA** [comment]
Hello @lmeyer1 

Thanks for your report.
I have checked your issue in : 

-  `\PrestaShop\PrestaShop\Adapter\RoundingMapper` class, there is only `::mapRounding()` method
-  `\PrestaShop\PrestaShop\Adapter\Number\RoundModeConverter` class, there is only `::getNumberRoundMode()` method

and i did not find any duplicates of code. Also, i did not found their occurrences

https://user-images.githubusercontent.com/92912932/204773278-71a44bd0-0b95-45c6-b0bd-f2ac9a83de26.mp4


Could you please provide us a screenshot or screen-record to can see clearly the issue ?

Thank You!

**Comment by lmeyer1** [comment]
> i did not find any duplicates of code

You found both classes and both methods. Thus you found the code duplication. One method is the duplicate of the other. I cannot say it more clearly.

> Also, i did not found their occurrences

I don't mind if you do not know how to search. I'm using PhpStorm and get this:
![Immagine 2022-11-30 113752](https://user-images.githubusercontent.com/7520695/204774478-8b069c24-8bda-4862-a52f-f27a97c472c8.png)
![Immagine 2022-11-30 113808](https://user-images.githubusercontent.com/7520695/204774490-4785d3f1-eabd-45e5-b047-c9f871b24f23.png)

As I said, the first one is never used. It is dead code. So it can be removed.
The second one is used. It's the living code.

**Comment by HanaRebaiQA** [comment]
Thanks @lmeyer1  for your feedback
ping @PrestaShop/prestashop-core-developers Could you please check this technical issue ?

Thank you!

**Comment by nicosomb** [comment]
Hello. 

In `RoundingMapper`, we have these round modes: 

```
        $roundModes = [
            PS_ROUND_UP => Rounding::ROUND_CEIL,
            PS_ROUND_DOWN => Rounding::ROUND_FLOOR,
            PS_ROUND_HALF_UP => Rounding::ROUND_HALF_UP,
            PS_ROUND_HALF_DOWN => Rounding::ROUND_HALF_DOWN,
            PS_ROUND_HALF_EVEN => Rounding::ROUND_HALF_EVEN,
            PS_ROUND_HALF_ODD => Rounding::ROUND_HALF_EVEN, 
        ];
```

and in `RoundModeConverter`, we have these round modes: 

```
    public const MODE_MAP = [
        PS_ROUND_UP => Rounding::ROUND_CEIL,
        PS_ROUND_DOWN => Rounding::ROUND_FLOOR,
        PS_ROUND_HALF_UP => Rounding::ROUND_HALF_UP,
        PS_ROUND_HALF_DOWN => Rounding::ROUND_HALF_DOWN,
        PS_ROUND_HALF_EVEN => Rounding::ROUND_HALF_EVEN,
    ];
```

So technically, we have a little difference. 

Outside of that, the two classes seem to do the same job.

**Comment by lmeyer1** [comment]
> So technically, we have a little difference.

Yes, that is true, and this difference is at the origin of #30441.
In fact the unused code is complete, and the used one is missing one option.

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Do you still encounter the issue with PS81x? Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
