### ISSUE TITLE
Missing field in the dashboard for a delete customer

### ISSUE THREAD

**Issue by paulnoelcholot** [PrestaShop/PrestaShop#30453]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On the dashboard, in the Products and Sales section, if it is a deleted customer, then the field is empty.

On page Order => OK
![image](https://user-images.githubusercontent.com/112863083/204840112-1ff4a874-b203-4ccd-8a2a-a0f9815138c2.png)

On Dashbord => NOK
![image](https://user-images.githubusercontent.com/112863083/204840176-5c3527d8-a316-4fa8-b69f-6e4c6fd37914.png)

### Expected behavior

"Deleted customer" should be displayed

### Steps to reproduce

1. Go to BO > Modules > Module manager page & check that the dashproducts's version is 2.1.2
2. Create an order with a customer
3. Go to BO > check the table Products and Sales > The order is displayed in the Recent Orders
4. Delete this customer
5. Go to BO > check the table Products and Sales
6. See the error

### PrestaShop version(s) where the bug happened

1.7.8.7, 8.0.0

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

 dashproducts 2.1.2

**Comment by AureRita** [comment]
Hi @paulnoelcholot ,

I reproduce the issue with PrestaShop version 1.7.8.7 and dashproducts 2.1.2. As we can see in this picture : 

![image](https://user-images.githubusercontent.com/100699445/205066421-b180d543-247b-43c1-b0b4-e096ae9abbd4.png)

Please be aware that some issues might take a very long time to be resolved. 

Thanks

**Comment by RezaRitm** [comment]
Hello, I want to work on this issue if anyone does not. can I?
