### ISSUE TITLE
save customization when customer fied is empty and not required

### ISSUE THREAD

**Issue by paulnoelcholot** [PrestaShop/PrestaShop#30464]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

From the FO, if I save the customization of a product while one of text field is empty and not required, an error appears.

![image](https://user-images.githubusercontent.com/112863083/205098624-5cc617c4-5e0a-4983-bb3f-3fea08b5ad34.png)

![image](https://user-images.githubusercontent.com/112863083/205098675-bf4746c5-d0ec-4713-b955-527952c13518.png)

### Expected behavior

the error should not appear

### Steps to reproduce

On BO :
1. Catalog > Products > Choose a product
2. Option > Add customization field, Type Text, and not Required
3. Save

On FO : 
4. Open the product on FO
5. do not fill in empty customization text fields
6. Save customization
7. See error

### PrestaShop version(s) where the bug happened

develop - 8.0.0

### PHP version(s) where the bug happened

7.4

**Comment by AureRita** [comment]
Hi @paulnoelcholot  ,

I reproduce the issue with PrestaShop version 8.0.0 and not with the version 1.7.8.7. As you can see on this video : 

[Untitled_ Dec 1, 2022 5_13 PM.webm](https://user-images.githubusercontent.com/100699445/205104478-378dfa68-46fa-475a-a8c0-922b474d4251.webm)

Nice catch ! It's a regression ! I'll add it to the patch backlog.

Please be aware that some issues might take a very long time to be resolved. 

Thank you

**Comment by davidglezz** [comment]
It seems easy, I have created a PR #30465
