### ISSUE TITLE
No upgrade available if first external modules source is empty

### ISSUE THREAD

**Issue by sowbiba** [PrestaShop/PrestaShop#30462]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

There is a bug in PS 8.0+ 

When the first module implementing `actionListModules` returns an empty list of upgradable modules, no available upgrade will be displayed 

![image](https://user-images.githubusercontent.com/7426640/205040425-c75c22c2-2639-4e31-a21f-c50f50452ca8.png)

### Steps to reproduce

1. Install PS 8.0.x
2. Install `ps_mbo`
3. Install a non OS module (like `colissimo`)
4. Modify it to point an old version (example : if colissimo version is 2.1.2, just put 2.1.1 in ps_module table and in colissimo.php)
5. Go to Modules > Updates, you'll see a list of available modules upgrades, including colissimo
6. Do all the OS modules upgrades
7. Now, you'll have an empty list of upgrades

### PrestaShop version(s) where the bug happened

8.0.x

**Comment by AureRita** [comment]
Hi @sowbiba 

Thank you for your report, can you give us the module to test this issue ( mbo and collissimo modified ) ? 

I didn't really understand your issue, what I Understand is : 
When you have no update, you'll have "0 modules to update" in the update tab. That was not expected ? 
or 
When you update the external module version, the update tab will show "0 modules to update" ? 

Waiting for your feedback

**Comment by sowbiba** [comment]
Hello @AureRita 

You can install 

[ps_mbo.preprod (1).zip](https://github.com/PrestaShop/PrestaShop/files/10155662/ps_mbo.preprod.1.zip)

[payplug.zip](https://github.com/PrestaShop/PrestaShop/files/10155671/payplug.zip)

**Comment by sowbiba** [comment]
I manually downgraded the version of paypkug in the zip to 3.1.0

So if you install this one, MBO should say that you have an upgrade available


Without the fix

![image](https://user-images.githubusercontent.com/7426640/205681891-00825d87-64e2-4108-aaf5-90130d87ed63.png)


With the fix

![image](https://user-images.githubusercontent.com/7426640/205682001-d1a1cc97-15dd-45f2-a979-0eabafb61f24.png)

**Comment by sowbiba** [comment]
Please use PS with develop branch. All the core modules are up to date with this version

**Comment by AureRita** [comment]
Hi @sowbiba 

I tried to use your mbo.zip and it didn't seems to work, can you give me another one ? 

Waiting for your zip

**Comment by sowbiba** [comment]
Hi @AureRita It's because there was a zip in the zip 😄 

Please use the one below

[ps_mbo.zip](https://github.com/PrestaShop/PrestaShop/files/10206659/ps_mbo.zip)

**Comment by sallemiines** [comment]
Hello @sowbiba 

Thanks for reporting the issue !

following your steps I didn't manage to reproduce your issue ! could you please provide us with more infos ! 

Thank you

**Comment by hibatallahAouadni** [comment]
Hello @sowbiba 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
