### ISSUE TITLE
Attribute `wait-for-it.sh` or install via `apt`.

### ISSUE THREAD

**Issue by axisofentropy** [PrestaShop/PrestaShop#30474]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

[wait-for-it.sh](https://github.com/PrestaShop/PrestaShop/blob/develop/.docker/wait-for-it.sh) is copyright Giles Hall and distributed under the MIT license. I don't see this copyright in this repository.

Alternatively, you could install the Debian package of `wait-for-it` [in `.docker/Dockerfile`](https://github.com/PrestaShop/PrestaShop/blob/6e1968a3ab867c7d04cc8a20c6c9483684b4948d/.docker/Dockerfile#L24) and then remove it from this repository.

### Steps to reproduce

See author's copyright and license at https://github.com/vishnubob/wait-for-it/blob/master/LICENSE

### PrestaShop version(s) where the bug happened

8.0.0 et al

**Comment by hibatallahAouadni** [comment]
Hello @axisofentropy 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must provide all details to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
