### ISSUE TITLE
Incorrect shipping cost is offered for delivery to certain countries

### ISSUE THREAD

**Issue by mattgorle** [PrestaShop/PrestaShop#30483]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

As a guest customer, I used Paypal Express checkout to purchase a product (using the Prestashop Checkout module).

My UK delivery address was shown correctly in Prestashop, but I was shown a shipping cost for delivery to the USA.

I have marked this as belonging to the ps_checkout module, but the underlying bug is in the Address model in core code.

### Expected behavior

I expected to see a shipping cost for delivery to the UK.

### Steps to reproduce

# Set up shop environment

1. Add a zone for the United Kingdom.
2. Have different shipping costs for the default zone and the UK zone.  See the example below for test data:
![image](https://user-images.githubusercontent.com/3032672/205509625-639d0d0f-337a-4c93-b11e-e5e44c1e8966.png)

# Place test transaction

1. As a guest user (not logged in), purchase an item using Paypal express checkout.
2. At Paypal, define your address as in the UK.
3. When you return to Prestashop, you will be shown shipping costs to the USA.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_checkout 2.20.2

**Comment by HartLarsson** [comment]
If i remember, to see the shipping price when you are not logged you need to enabel the geolocalization.

NB: You shipping costs divided in 4 main area are very unprecise and can give you an unexpected lost of money. 
For example shipping in France is cheaper respect shipping in Corse, that is France too :)

**Comment by mattgorle** [comment]
The issue is not that shipping costs are hidden.  Rather, it is that they are for the wrong zone.

GeoIP is enabled, but I don't believe that it is the relevant factor here.  The address data, including country, is coming from PayPal in this instance.

The sample shipping costs I provided are a simplistic example to demonstrate the issue.

The issue is that an address in the UK, supplied by PayPal, gets an `id_zone` of a State in the USA, but an `id_country` of the UK.  Shipping costs are zone-based and the zone is resolved in Address::getZoneById.  This uses an incompletely constrained JOIN which allows the wrong country, therefore the wrong zone, to be selected in this specific case.

**Comment by mattgorle** [comment]
I have opened a pull request which fixes this issue: https://github.com/PrestaShop/PrestaShop/pull/30482

**Comment by hibatallahAouadni** [comment]
Hello @mattgorle 

Could you please provide a screen record and try to reproduce the issue with the native module (ps_checkpayment, ps_bankwire) as payment module :pray: 
Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @mattgorle 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
