### ISSUE TITLE
Duplicate type casting in ps_emailalerts module

### ISSUE THREAD

**Issue by leemyongpakvn** [PrestaShop/PrestaShop#30481]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

There are some duplication and inconsistency with typecasting in ps_emailalerts module v2.4.0:
1. In [MailAlert.php  function sendCustomerAlert](https://github.com/PrestaShop/ps_emailalerts/blob/v2.4.0/MailAlert.php#L170-L256) `$id_shop` and `$id_lang` are typecasted only one time [at top](https://github.com/PrestaShop/ps_emailalerts/blob/v2.4.0/MailAlert.php#L177-L178), while $id_product is typecasted twice at [line 182](https://github.com/PrestaShop/ps_emailalerts/blob/v2.4.0/MailAlert.php#L182) and [line 251](https://github.com/PrestaShop/ps_emailalerts/blob/v2.4.0/MailAlert.php#L251).
2. In [actions.php function processAdd](https://github.com/PrestaShop/ps_emailalerts/blob/v2.4.0/controllers/front/actions.php#L87-L156), `$id_product` is typecasted twice at [line 108](https://github.com/PrestaShop/ps_emailalerts/blob/v2.4.0/controllers/front/actions.php#L108) and [line 136](https://github.com/PrestaShop/ps_emailalerts/blob/v2.4.0/controllers/front/actions.php#L136)
3. and some others

### Describe the solution you'd like

Typecasting only one time at the top of function to keep consistency and avoid duplication.

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @leemyongpakvn 

Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. 
So, we're waiting for your PR :rocket: 

Thank you
