### ISSUE TITLE
Docker broken

### ISSUE THREAD

**Issue by erikkubica** [PrestaShop/PrestaShop#30484]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Docker script / compose is broken in the repo. 

First it does not like that the version argument does not exists or sth like this, so I have had to replace the frin  $VERSION in Dockerfile to version, then docker compose successfully executed but then my system crashed, then again, then I have noticed that it got some memory leak, most probably on mysql side: https://www.youtube.com/watch?v=GfPrb2xivgQ

### Steps to reproduce

1. Download the prestashop repo
2. Run docker-compose up

### PrestaShop version(s) where the bug happened

8.0

**Comment by hibatallahAouadni** [comment]
Hello @erikkubica 

Could you please check this issue #29037 cause it seems similar to yours.
Waiting for yoyur feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @erikkubica 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
