### ISSUE TITLE
Impossible to create product combinations

### ISSUE THREAD

**Issue by lionelJDN** [PrestaShop/PrestaShop#30506]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On a fresh install, it's impossible to create product combinations.
I get an error: Unable to update settings.
The combinations are not created.
Thank you for your advices.

### Steps to reproduce

1. Go to Catalog / Products
2. I select a product
3. On "Basic settings" tab, I choose " Product with combinations"
4. Go to "Combinations" tab
5. I choose several "Colour" and "Size"
6. I click on "Generate" button
7. I get the error: "Unable to update settings." and the combinations are not created

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.2 and 7.4

**Comment by hibatallahAouadni** [comment]
Hello @lionelJDN 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #9809. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #9809

**Comment by lionelJDN** [comment]
Hello @hibatallahAouadni, thank you but I have not large number of product combinations. It's a fresh install with just two colors and three sizes.

**Comment by hibatallahAouadni** [comment]
@lionelJDN so you should check your php configuration :wink:

**Comment by lionelJDN** [comment]
Hello @hibatallahAouadni thank you for your quick answer.
Do you thkin that my config is too restrictive please?

Server software version: Apache
PHP version: 7.2.34-8+ubuntu16.04.1+deb.sury.org+1
Memory limit: 3000M
Max execution time: 18000
Upload Max File size: 1000M
info_outline Database information
MySQL version: 5.7.32-0ubuntu0.16.04.1 

Thank you very much for your advices.

**Comment by hibatallahAouadni** [comment]
@lionelJDN it seems all good!
So, could you please check `max_execution_time` and `memory_limit` in your php.ini under apache.
