### ISSUE TITLE
SEO URL Enable issue. when SEO URL once disable after enable. Front office url go to 404

### ISSUE THREAD

**Issue by mytry4100803** [PrestaShop/PrestaShop#30502]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

SEO URL Enable issue. when SEO URL once disable after enable. Front office url go to 404

### Expected behavior

seo url not working after disable/enable.

### Steps to reproduce

SEO URL Enable issue. when SEO URL once disable after enable. Front office url go to 404

### PrestaShop version(s) where the bug happened

8.0

**Comment by mytry4100803** [comment]
![Screenshot from 2022-12-06 16-03-46](https://user-images.githubusercontent.com/36532203/205888382-10d4e6c8-7c21-47fa-a04d-bc83a602d9c2.png)

1)disable SEO link setting from back office. 
visiting some linkes
2) after enable SEO URL then main page not 404 found.

**Comment by Hlavtox** [comment]
Hi @mytry4100803, this is already reported here - https://github.com/PrestaShop/PrestaShop/issues/30217

**Comment by mytry4100803** [comment]
its duplicate so, removed

**Comment by hibatallahAouadni** [comment]
Duplicate of #30217
