### ISSUE TITLE
Showing 1 on top left side

### ISSUE THREAD

**Issue by digi-booster** [PrestaShop/PrestaShop#30501]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

![image](https://user-images.githubusercontent.com/74658643/205823513-7ced428b-0157-443f-9bba-082170793454.png)

### Expected behavior

I'm not expecting 1 on top left side

### Steps to reproduce

1. Go to attriccave.com

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

I don't know

**Comment by hibatallahAouadni** [comment]
Hello @digi-booster 

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you

**Comment by digi-booster** [comment]
Hi @hibatallahAouadni, It didn't happen by my side, the error occurred after Prestashop modules update, I won't bother you if I did it by mistake.

**Comment by hibatallahAouadni** [comment]
Hello @digi-booster 

Well you need to provide all details to help me reproducing the issue.
Which modules did you upgrade that caused this problem?

Thanks!

**Comment by digi-booster** [comment]
> Hello @digi-booster
> 
> Well you need to provide all details to help me reproducing the issue. Which modules did you upgrade that caused this problem?
> 
> Thanks!

I updated 5 modules all together, and only remember 2 of them, ps_facebook and contact form. Is there any way to know which modules I have updated like log files, etc?

**Comment by digi-booster** [comment]
oh sorry, sendinblue was causing the problem, I'm so sorry to bother you @hibatallahAouadni 

Thank you for your response

**Comment by hibatallahAouadni** [comment]
@digi-booster no problem :wink: and thanks for your feedback!
