### ISSUE TITLE
Categories image - harmonization of 2 images 

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#30520]
# User story:

Make categories great again.
As a merchant, I want to be able to edit the different categories of images (cover, thumbnail) and using the image set in the back-office.

# Constraint:

→ No BC

The image provided by the back doesn’t send the right data. The file between Category cover image & Category thumbnail are the same.

# Current situation:

* We have two images available to be set to a category in BO. Only one of them is used, one is not available at all and accessing them is a mess.
	* *Category cover image*
		* Currently used for category cover in the header of the category and subcategory thumbnail in the parent category.
		* Accessible by *$category.image.bySize.category_default*
	* *Category thumbnail*
		* Not used in classic theme right now at all.
		* Accessible by *$category.image.bySize.small_default*
	* Image array with *bySize* should contain the same image, but in different sizes, like product images. Not magically a different image for each size. 🙂
* Another problem. In *BO > Image settings*, where we select for which type of objects we want the thumbnail to be generated for. 
	* All other types of objects (product, manufacturer) have only 1 type of image. Either a single one (manufacturer, supplier, store) OR in case of products, multiple images, but serving the same purpose, having the same sizes.
	* But for categories, we have 2 images with different usage (to have in the same time a cover and the thumbnail with a different images).
	* How to solve this?
		* A) Either generate two images in all thumbnail definitions, which will leave some thumbnails unused. So for example, size *‘cover_large’* will be generated for *$category.thumbnail*, but not used at all.
		* B) Or extend upon current settings in image sizes and instead of one “Category” type,  add “Category cover”, “Category thumbnail”. So we can configure sizes for each type of image separately, so we don’t waste space.

# Specs
In FO *$category* object, we need to have two images available as a standardized array with all the sizes. It should for example be *$category.thumbnail* and *$category.cover*.

All of these will be an array as we know from current *$category.image* or product images, but with correct data.

The same should be standardized for all objects in FO, manufacturers for example. Which right now provide only a single URL in *$manufacturer.image*, instead of array with all sizes.

One question to decide. On product page, we have *$product.images* array with the images.
Do we want to have *$category.thumbnail* and *$category.cover* separately? Or put it to a new array called *$category.images* with children thumbnail and cover?

_____________________________________________

# @Hlavtox specs proposal on 22.5.2023
# Basic things to resolve
1. We need to be able to have this data in front office.
2. We need to review a system of how these images are stored on the filesystem.
3. We need to properly retrieve links for these images.
4. We need to be access these images by the rewritten URL.
5. We need ImageRetriever to properly generate and retrieve thumbnails for these images.
6. We need backoffice manual regenerate AND regenerate after upload to do it properly also.
7. We need to be able to define sizing for these images, possibly for other image types.

# 1. We need to be able to have this data in front office. ✅
https://github.com/PrestaShop/PrestaShop/pull/32653

# 2. We need to review a system of how these images are stored on the filesystem. 🟡 
- Original image for cover - `/img/c/1.jpg`, working
- Original image for thumbnail - `/img/c/1_thumb.jpg`, working
- Resized image(s) for cover - `/img/c/1-category_default.jpg`, working
- Resized image(s) for thumbnail - `/img/c/1_thumb-category_default.jpg`. Currently broken, backoffice is generating it as `/img/c/3-small_default.jpg` overwriting the cover image miniature.

# 3. We need to properly retrieve links for these images. ✅
Link class must be able to provide links to these images properly. Works, tested.

# 4. We need to be access these images by the rewritten URL. 🔴 
Rewrites do not work.
`http://localhost/dev/c/4-category_default/men.jpg` works
`http://localhost/dev/c/4_thumb-category_default/men.jpg` does not

There are rewrites only for the basic image.
```
RewriteCond %{HTTP_HOST} ^localhost$
RewriteRule ^c/([\d]+)(\-[\.*\w-]*)/.+(\.(?:jpe?g|webp|png|avif))$ %{ENV:REWRITEBASE}img/c/$1$2$3 [L]
RewriteCond %{HTTP_HOST} ^localhost$
RewriteRule ^c/([a-zA-Z_-]+)(-[\d]+)?/.+(\.(?:jpe?g|webp|png|avif))$ %{ENV:REWRITEBASE}img/c/$1$2$3 [L]
```

Manufacturers don't use any rewrites.
`http://localhost/dev/img/m/1-small_default.webp`
Maybe we can do the same for category images? Do they need rewriting?

# 5. We need ImageRetriever to properly generate and retrieve thumbnails for these images. ✅
After a small change (allowing a string as image id) and passing the ID image with _thumb suffix, ImageRetriever retrieves a proper set of images, in all formats configured.

![Snímek obrazovky 2023-05-20 165004](https://github.com/PrestaShop/PrestaShop/assets/6097524/e2932728-535a-46f8-b863-b911620b57c1)

# 6. We need backoffice to properly generate these thumbnails. 🔴 
Backoffice is currently generating it as `/img/c/3-small_default.jpg` instead of `/img/c/3_thumb-small_default.jpg`, overwriting the cover image miniature.

# 7. We need to be able to define sizing for these images, possibly for other image types. 🔴 
Miniatures that should be generated are stored in ps_image_type table. This table has a problem, it only says that the current size is for categories, but not anything else. There is no way to define additional details.

We can currently get a way by generating both cover and thumbnail in all sizes defined for categories. This would bring SOME additional storage needed, but category counts are in hundreds on most stores. This is how it currently works.

Current table structure looks like this:
| id_image_type	 | name	 | width	 | height	 | products	 | categories	 | manufacturers	 | suppliers	 | stores |
| ---                           | ---          | ---     | ---     | ---      | ---          | ---             | ---         | ---    |
| 1	                          | cart_default	 | 125	 | 125    | 1       | 0	   | 0	           | 0	              | 0 |
| 2	                          | small_default	 | 98	         | 98	    | 1       | 1	   | 1	           | 1	               | 0 |

My proposal is to change it like this, making each size it's own line with it's own purpose. The table would not be much bigger because the image types hardly interfere with each other. Also, it would allow to use this system by custom modules for their images. The change would be done internally and `ImageType::getImagesTypes('products')`; would return the same data.

| id_image_type	 | name	 | width	 | height	 | purpose	 | 
| ---                           | ---          | ---          | ---          | ---                 | 
| 1	                        | cart_default  | 125	 | 125          |    products     |
| 2	                     | cover_default	 | 1000	  | 100	   | category_cover |
| 3	                     | cover_default_2x	 | 2000	  | 200	   | category_cover |
| 4	                     | small_default	 | 98	  | 98	   | category_thumbnail |
| 5	                     | small_default	 | 98	  | 98	   | blog_post_thumbnail |

We can further extend this by adding a column for non-deletable thumbnails for backoffice purposes, which would allow us to get rid of the old thumbnail images generated somewhere. Also, we can add a new column with a desired thumbnail fitment, so we can implement https://github.com/PrestaShop/PrestaShop/issues/26158 properly.

# 8 Acceptance Test
https://github.com/PrestaShop/PrestaShop/blob/d672ad4ccc467722d13746e25fffc95a86e5e3b3/tests/UI/campaigns/functional/BO/08_design/06_imageSettings/11_imageGenerationOnCreation.ts#L301-L302

**Comment by MatShir** [comment]
The [issue](https://github.com/PrestaShop/PrestaShop/issues/18852) makes me think we should make have $category.thumbnail, $category.cover and $category.menu separately and it avoid miss understanding if a image setting are disabled.

**Comment by SharakPL** [comment]
> The [issue](https://github.com/PrestaShop/PrestaShop/issues/18852) makes me think we should make have $category.thumbnail, $category.cover and $category.menu separately and it avoid miss understanding if a image setting are disabled.

1. It should be possible in BO category settings to pick an image version from the list of available for category in _Design > Image settings_ (+ **Don't use** option) for each type (cover, thumbnail. menu)
2. It should be possible to use eg. only thumbnail. Right now when thumbnail is set without main image then $category.image = null and thumbnail can't be accessed unless targeting specifically `...small_default.jpg` or `..._thumb.jpg` files.
3. Only main image can be deleted and it also deletes all other images. They should be independently configured unless specified so option **Generate all thumbs from this image** is needed for main image form.

**Comment by Hlavtox** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/36877
