### ISSUE TITLE
APIS08b - Authorized Applications - Delete an application

### ISSUE THREAD

**Issue by eshraw** [PrestaShop/PrestaShop#30523]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

This is a new feature. It aims to make the Authorized Apps manageable in the BO

### Describe the solution you'd like

As a shop administrator
I want to be able to delete an authorized application in the Authz server management page in the BO
In order to clean my Authz server management

### Additional context

[Figma link](https://cutt.ly/2MUXEgy)

### Acceptance test
AT1

1. Given that
   1. I am a shop administrator
   2. The authorization server administration module accessible
2. When I open the the authz server administration page in the BO
3. Then
   1. I can see the list of applications that have an API access to my shop
   2. I can click on "delete" to delete an authorized app
   3. Then
       1. a pop-up prompting me to confirm the deletion appears
       2. I can click on "Confirm" to delete the target authorized app

### QA Scenarios
* Functional > BO > Advanced Parameters > Authorization Server > CRUD

|**Action** | **Additional** | **Expected** |
|-----------|-----------|-----------|
| | **PRE-COND : Enable experimental feature : Authorization server** | |
In BO, Go to Advanced Parameters > New & Experimental Features |   | New & Experimental Features Page is displayed correctly.
Set checked the checkbox “Authorization server” |   | The checkbox “Authorization server” is check
Click on Save button |   | A modal appeared
Click on Enable button in the modal | | The message “Update successful” is displayed
| | **Main Test** | |
In BO, Go to Advanced Parameters > Authorization Server |   | Authorization Server Page is displayed correctly.<br>No records found in the table
Click on the button "Add new authorized app"|   | New authorized application Page is displayed correctly
Fill the form with following data (App Name : "Application XYZ", Description: "Description ABC")<br>Click on Save button| | The message “Successful creation” is displayed<br>There is 1 application in the list
Click on the edit button on the first row|   | Editing application Page is displayed correctly
Fill the form with following data (App Name : "Application UVW", Description: "Description DEF")<br>Click on Save button| | The message “Successful update” is displayed<br>There is 1 application in the list
On the first row, click on the button “Three points” | | The dropdown is displayed.
Click on the Delete Button in the dropdown | | A modal appeared
Click on the Confirm Button in the modal | | The message “Successful deletion” is displayed<br>No records found in the table
| | **POSTCOND : Disable experimental feature : Authorization server** | |
In BO, Go to Advanced Parameters > New & Experimental Features |   | New & Experimental Features Page is displayed correctly.
Set unchecked the checkbox “Authorization server” |   | The checkbox “Authorization server” is unchecked
Click on Save button |   |  The message “Update successful” is displayed

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by sallemiines** [comment]
Hello @eshraw 

Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments.

Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you create it.

If you or anyone else is willing to [contribute this feature](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/) to the PrestaShop Project, the teams will be happy to help by ensuring that it fits well within the project. Please let us know if that is the case!

Thank you

**Comment by Progi1984** [comment]
Test added : https://forge.prestashop.com/browse/TEST-7068
