### ISSUE TITLE
Improve the Product::getAttributesResume

### ISSUE THREAD

**Issue by StoreCommanderDev** [PrestaShop/PrestaShop#30533]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Hello.
By working on a customer ticket, I discovered an issue into Product::getAttributesResume method.

Somewhere in our interface, a product_attribute should return an `attribute_designation` **color black**, but the method gave us **color green**.
After some reseachs I found there are more `$combinations` array entries than `$lang` array entries.
Fine, the first issue come from merchant data. We keep that in mind but it doesn't block the improvement.

**We could have be a great result even whith those wrong data**.

Here is why:
The foreach loop for `$lang` array fill `$combinations` array by using basic `$k`. 
So if the lenght of the two arrays dosn't match, there could be an error.

In my opinion, using auto_increment index is not the best way to match `$combinations` data with `$lang` data.

![image](https://user-images.githubusercontent.com/52830264/206453564-87d8ae8b-9939-4abd-b535-eb23f96b9823.png)

### Describe the solution you'd like

I think using 'id_product_attribute' as index of `$combinations` array solves the merchant issue, improves code and performances.

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by PrestaEdit** [comment]
Hi,

I can confirm having seen this issue more than 5 times (in different shops/versions).

**Comment by ghost** [comment]
Hello @PrestaShop/committers 

What do you think about this, it's not an easy outcome to reproduce but it seems logical?

**Comment by hibatallahAouadni** [comment]
Hello @StoreCommanderDev 

Welcome to Presta :tada: 
Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon. 
Thanks for your PR :rocket: 

Thank you
