### ISSUE TITLE
PHP Warning:  file_exists(): open_basedir restriction in effect.

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/PrestaShop#30531]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I've upgraded succesfully an installation from PS 1.7.6.5 to PS 1.7.8.7 (classic theme)
All the modules are updated and all works perfectly
When i switch php version from 7.2 to 7.4 tons of warning like this one appear in the error_log_php:

`PHP Warning:  file_exists(): open_basedir restriction in effect. File(/views/templates/hook/pixelheader.tpl) is not within the allowed path(s): (/home2/userx/:/opt/cpanel/ea-php74/root/usr:/usr/local/lib/php:/tmp:/etc/pki/tls/certs/ca-bundle.crt:/var/cpanel/php/sessions:/usr/local/bin/wp) in /home2/userx/public_html/classes/module/Module.php on line 2509`

I've verified that Prestashop detecting the right open_basedir and seems ok.

Looking the part of the code of module.php line 2509:

```
    protected function getCurrentSubTemplate($template, $cache_id = null, $compile_id = null)
    {
        if ($compile_id === null) {
            $compile_id = $this->getDefaultCompileId();
        }

        if (!isset($this->current_subtemplate[$template . '_' . $cache_id . '_' . $compile_id])) {
            if (false === strpos($template, 'module:') &&
                !file_exists(_PS_ROOT_DIR_ . '/' . $template) &&
                !file_exists($template)  <===== line 2509
            ) {
                $template = $this->getTemplatePath($template);
            }

            $this->current_subtemplate[$template . '_' . $cache_id . '_' . $compile_id] = $this->context->smarty->createTemplate(
                $template,
                $cache_id,
                $compile_id,
                $this->smarty
            );
        }
```
the line  !file_exists($template) missing of the _PS_ROOT_DIR_.
If i modify that line into: !file_exists(_PS_ROOT_DIR_ . $template) the warning disappear.

This warning problem could be a script bug (module.php) or a hosting wrong configuration?

I see the same "error" in module.php in PS 8.x too

Thank you for your feedback

### Expected behavior

Because PS 1.7.8.7 is developed for PHP7.4 and all modules are updated must be no difference passing from PHP7.2 to PHP7.4

### Steps to reproduce

1) installa PS 1.7.8.7
2) enable php7.4
3) look in error_log_php to discover tons of "PHP Warning:  file_exists(): open_basedir restriction in effect."

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

**Comment by AureRita** [comment]
Hi @HartLarsson 

Thank you for your report ! I tried to reproduce your issue but I didn't find the files error_log_php from my shop, can you say where we can find this files ? 
Moreover, can you say if some pages are broken because of this issue ? (we can easily find the issue like that) 

Waiting for your feedback

**Comment by kpodemski** [comment]
@HartLarsson 

this issue is coming from the module that tries to add a pixel to the header... there's a call to display `/views/templates/hook/pixelheader.tpl` which is wrong, module author shouldn't use an absolute path to find a template to display

**Comment by kpodemski** [comment]
@AureRita third-party module issue :)

**Comment by AureRita** [comment]
Hi @kpodemski 

so the issue is verified ? 

Waiting for your answer

**Comment by HartLarsson** [comment]
> @HartLarsson
> 
> this issue is coming from the module that tries to add a pixel to the header... there's a call to display `/views/templates/hook/pixelheader.tpl` which is wrong, module author shouldn't use an absolute path to find a template to display

i check the module and this is the line where is called the .tpl

`$output .= $this->display(__FILE__, 'views/templates/hook/pixelheader.tpl');`

Seems is not used an absolute path, anyway, I reported the problem to the developer of the module.

So my mod was not necessary?

**Comment by AureRita** [comment]
Hi @HartLarsson 

Thank for your report,
This issue is too technical for me, ping @PrestaShop/prestashop-core-developers, can someone please reproduce this issue or answer to Hart ? 

Thanks

**Comment by HartLarsson** [comment]
seems no one is interested to find out this problem :)

**Comment by kpodemski** [comment]
@HartLarsson could you share this module? you can send to krystian.podemski (at) prestashop.com

**Comment by HartLarsson** [comment]
> @HartLarsson could you share this module? you can send to krystian.podemski (at) prestashop.com

Done! thanks!

**Comment by kpodemski** [comment]
I discussed with @HartLarsson and this issue doesn't come from the core.

**Comment by HartLarsson** [comment]
> I discussed with @HartLarsson and this issue doesn't come from the core.

yes but the funny part is i cannot find who cause that.

**Comment by HartLarsson** [comment]
I've other problems related to same function file_exists():

```
[2023-01-20 02:23:47] php.DEBUG: Warning: file_exists(): open_basedir restriction in effect. File(/home2/composer.json) is not within the allowed path(s): (/home2/userx/:/opt/cpanel/ea-php74/root/usr:/usr/local/lib/php:/tmp:/etc/pki/tls/certs/ca-bundle.crt:/var/cpanel/php/sessions:/usr/local/bin/wp) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/home2/userx/new.website.com/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Caster/LinkStub.php\",\"line\":94,\"trace\":[{\"file\":\"/home2/userx/new.website.com/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Caster/LinkStub.php\",\"line\":55,\"function\":\"getComposerRoot\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\LinkStub\",\"type\":\"->\"}],\"count\":1})"} []
[2023-01-20 02:23:47] php.DEBUG: Warning: file_exists(): open_basedir restriction in effect. File(/home2) is not within the allowed path(s): (/home2/userx/:/opt/cpanel/ea-php74/root/usr:/usr/local/lib/php:/tmp:/etc/pki/tls/certs/ca-bundle.crt:/var/cpanel/php/sessions:/usr/local/bin/wp) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/home2/userx/new.website.com/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Caster/LinkStub.php\",\"line\":95,\"trace\":[{\"file\":\"/home2/userx/new.website.com/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Caster/LinkStub.php\",\"line\":55,\"function\":\"getComposerRoot\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\LinkStub\",\"type\":\"->\"}],\"count\":1})"} []
```

in the file LinkStub.php @ line 95 there is a problem of path

![image](https://user-images.githubusercontent.com/16102074/213599344-76a590bd-263f-465d-a072-b3b182eadd68.png)

PS: 1.7.8.8
PHP 7.4

**Comment by HartLarsson** [comment]
seems this problem is an old reported problem: https://github.com/PrestaShop/PrestaShop/issues/26783
i see the fix but i dont' know if is correct or not to apply.

I've also in a fresh istallation PS1.7.8.8 PHP7.4 this error when i visti the dashboard:

`Warning alla linea 2509 nel file /home2/rpixelwg/MY-SITE/classes/module/Module.php
[2] file_exists(): open_basedir restriction in effect. File(/views/templates/hook/HookDashboardZoneTwo.tpl) is not within the allowed path(s): (/home2/rpixelwg/:/opt/cpanel/ea-php74/root/usr:/usr/local/lib/php:/tmp:/etc/pki/tls/certs/ca-bundle.crt:/var/cpanel/php/sessions:/usr/local/bin/wp)`

I think that someone of the Dev team must take a look and solve  it.

Hart

**Comment by kpodemski** [comment]
@HartLarsson ps_metrics is not part of the open-source project, you'd need to report it to the team responsible for this module

**Comment by HartLarsson** [comment]
> @HartLarsson ps_metrics is not part of the open-source project, you'd need to report it to the team responsible for this module

i'm not able to find the right repository.
That module is a pain in the a...s

**Comment by PascalNetenvie** [comment]
Hello,
I have exactly the same problem and it also cause bugs during Modules update ...
It was most likely ok when shops were in 1.7.8.5 version ...
So it seems the problem come from a recent version 1.7.8.6+ or something like that.
In my case i have this error :
`AH01071: Got error 'PHP message: PHP Warning: file_exists(): open_basedir restriction in effect. File(/views/templates/hook/HookDashboardZoneTwo.tpl) is not within the allowed path(s): (/var/www/vhosts/monsite.fr/:/tmp/) in /var/www/vhosts/monsite.fr/httpdocs/classes/module/Module.php on line 2509', referer: https://monsite.fr/admin178tjjn44/index.php/modules/metrics`

**Comment by garbus2** [comment]
I am also experiencing this problem. Presta 1.7.8.10 Only on PHP74 while PHP73 seems to produce no error. My error is:
`

>  Warning: file_exists(): open_basedir restriction in effect. File(/views/templates/hook/footerscript.tpl) is not within the allowed path(s): (/usr/home/xxx/public_html:/tmp:/usr/share:/usr/local/share:/dev) in /usr/home/xxx/public_html/classes/module/Module.php on line 2509

**Comment by HartLarsson** [comment]
> /views/templates/hook/footerscript.tpl

thre is a module that try to inject a script using the wrong path "/views/templates/hook/footerscript.tpl" instead of "views/templates/hook/footerscript.tpl"

You must fix the module injection code removing "/" in fron to fo the path to be NOT absolute.

Hart

**Comment by AIPONCEP** [comment]
i have the same problem in prestashop 8.2...
Warning en línea 2315 en archivo /var/www/vhosts/xxx/httpdocs/classes/module/Module.php
[2] file_exists(): open_basedir restriction in effect. File(/views/templates/hook/psshippingPromote.tpl) is not within the allowed path(s): (/var/www/vhosts/xxx/:/tmp/)
