### ISSUE TITLE
Microdata error on `productcomments` module

### ISSUE THREAD

**Issue by micka-fdz** [PrestaShop/PrestaShop#30543]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

There is a microdata error on listings with reviewed product(s) (home page, category pages, accessories...).

![image](https://user-images.githubusercontent.com/50865159/206677596-9effe6ae-84d1-4506-be11-bf3f4d2d5a9b.png)

### Expected behavior

This error is because of `aggregateRating` microdata on product miniatures. I don't think this microdata is useful on listing pages because it is already present on product pages in JSON-LD. I will make a PR to remove it.

### Steps to reproduce

1. Go to category page with reviewed products
3. Copy category page URL
4. Paste URL on https://search.google.com/test/rich-results
5. See `Missing field "itemReviewed"` error

### PrestaShop version(s) where the bug happened

1.7.x.x

### If your bug is related to a module, specify its name and its version

productcomments

**Comment by kpodemski** [comment]
Hi @micka-fdz 

> I don't think this microdata is useful on listing pages because it is already present on product pages in JSON-LD. 

We need to base it on "I know it is not useful to have it there" 👍 maybe there's an explicit information regarding this

**Comment by micka-fdz** [comment]
@kpodemski I think we need the opinion of an SEO expert.

**Comment by Hlavtox** [comment]
I confirm this change, we have no detailed structured data for products in product lists. The inline structured data for comments have no purpose because it has no context. The robot cannot even know what product is it related to.

**Comment by Hlavtox** [comment]
It served purpose when microdata was inlined in the past, like here: https://github.com/PrestaShop/PrestaShop/blob/1.7.5.0/themes/classic/templates/catalog/_partials/miniatures/product.tpl

Right now, the correct solution is to remove it.

**Comment by jf-viguier** [comment]
I agree with Mickael: it's not useful

**Comment by Prestaplugins** [comment]
I agree too, we already have them on the product page, no need for product's micro data on listings.

**Comment by maniT4c** [comment]
I agree, those micro data are useless on listing page.

**Comment by Franck-Bugnet-SITOLOG** [comment]
I agree, not only these micro data are useless in that page, but additionally they create many warning in Google Search.

**Comment by kpodemski** [comment]
Thank you for the comments, everyone. I also agree with the proposal, but it's absolutely incredible to see so much feedback 👍 I hope to see it in more issues 😎

**Comment by micka-fdz** [comment]
Thanks to my French crew 🇫🇷 and also to @Hlavtox and @kpodemski 👏

**Comment by carrinhos3b** [comment]
Hello, I have this issue "item reviewed field missing". I have the module "SeoPro - All-In-One SEO" can you tell me how to configure it to solve this problem? Thank you very much if someone can explain it to me (for newbie)!!
