### ISSUE TITLE
Product breadcrumb is not generated accordingly to accessed category.

### ISSUE THREAD

**Issue by Dreimus** [PrestaShop/PrestaShop#30547]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If you assign a category to : 

- `Home / Category A / Category B`
- `Home / Category C / Category D /  Category E`

And assign the default category "Category B".

If you access the product from ` Home / Category C / Category D /  Category E` 
The generated breadcrumb will be `Home / Category A / Category B` because de Product Controller uses by default the product default category.

Fixed by PR #30546

### Expected behavior

If I'm accessing the product from ` Home / Category C / Category D /  Category E` 
I exped the breadcrumb to be ` Home / Category C / Category D /  Category E / My Product` 

### Steps to reproduce

1. Assign a product to two categories  : 

- `Home / Category A / Category B`
- `Home / Category C / Category D /  Category E`

2. Assign default category to `Category B`

3. Access the product from the catalog by using  `Home / Category C / Category D /  Category E` path
4. See that the generaed breadcrumb is `Home / Category A / Category B`

### PrestaShop version(s) where the bug happened

1.7.8.*

### PHP version(s) where the bug happened

7.2

**Comment by AureRita** [comment]
Hi @Dreimus, 

Thank you for your report and for the PR, but as you can read on your pr : https://github.com/PrestaShop/PrestaShop/pull/30546#pullrequestreview-1211674681

This is a feature put in the previous version so as @Hlavtox said, you can maybe put this on a trigger. 

I'll put this one like a feature which may be able to be validated 

The Maintainer Team will take it into consideration for future developments. 

Thank you

**Comment by Dreimus** [comment]
Hello @AureRita, 

Thanks for your feedback, I've updated my PR with the according trigger.

**Comment by kpodemski** [comment]
ping @MatShir 

I think it's good addition but to ensure we're aligned take a look please so it won't be blocked during QA 👍

**Comment by MatShir** [comment]
I like the idea as well !
If you access to the product from the Home category, what is displayed in your PR ?
So the default would be use only when the product is access from a direct link

**Comment by kpodemski** [comment]
cc @Dreimus @MatShir asked question there 👍

**Comment by Dreimus** [comment]
Hello @MatShir,

From homepage, default behavior is triggered, the product main category is used for breadcrumb display.;

![image](https://user-images.githubusercontent.com/2658244/212058232-1e1686a5-7da2-4f80-8958-5452673e3b66.png)

**Comment by Hlavtox** [comment]
@MatShir This only enables old behavior that was removed in 1.7. Some people may like it.

When you open product page, Prestashop will check if the page the user came from was a category (except HOME category) and it will use it as $category property for the current load. If the previous request was not a category, it will show product's default category.
