### ISSUE TITLE
Hello i need help to create drop down languages prestahsop 1.7

### ISSUE THREAD

**Issue by ninogames12** [PrestaShop/PrestaShop#30552]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

hello i need one know css & html please to help me in create drop down languages prestashop 
i have old style this with flags on my front end 

![1-lang](https://user-images.githubusercontent.com/120318956/206908877-243b065e-75ae-4053-b82a-78698d56b4d9.PNG)

i want create dropdown like this image pelase

![2-lang](https://user-images.githubusercontent.com/120318956/206908897-704198de-0f9d-4d19-9927-6514d8d5a23f.PNG)

the code need modify css html this code with no delete or remove any thing in php 

`<style>
{literal}
#currencies_block_top3  ul {list-style:none }

#currencies_block_top3 li {box-shadow: 1px 1px 1pc #79107a, 0 0 25px #024cd3, 0 0 5px #b9087a;
 margin-right: 3px; padding:3px; background:none ; text-shadow:0px 0px 10px gold; font-size:14px; font-weight:bold; float:left; display:inline-block; margin-left:19px; margin-bottom: 21px;}
#currencies_block_top3 li a {color:white;}
#currencies_block_top3 li.selected {padding:1px; background:black; text-shadow:0px 0px 10px gold; }
#currencies_block_top3 li.selected a{ color:red;}
{/literal}
</style>

<div id="currencies_block_top3">
        <ul>
            {foreach from=$languages item=language}
                    <li {if $language.id_lang == $current_language.id_lang} class="current" {/if}>
                      <a href="{url entity='language' id=$language.id_lang}" class="dropdown-item">
            	         <img src="{$urls.img_lang_url|escape:'html':'UTF-8'}{$language.id_lang|escape:'html':'UTF-8'}.jpg" alt="{$language.iso_code|escape:'html':'UTF-8'}" width="32" height="32" />
            	         {$language.name_simple}
            	        </a>
                    </li>
                  {/foreach}
        </ul>
</div>
`

### Describe the solution you'd like

hello i need one know css & html please to help me in create drop down languages prestashop 
i have old style this with flags on my front end 

![1-lang](https://user-images.githubusercontent.com/120318956/206908877-243b065e-75ae-4053-b82a-78698d56b4d9.PNG)

i want create dropdown like this image pelase

![2-lang](https://user-images.githubusercontent.com/120318956/206908897-704198de-0f9d-4d19-9927-6514d8d5a23f.PNG)

the code need modify css html this code with no delete or remove any thing in php 

`<style>
{literal}
#currencies_block_top3  ul {list-style:none }

#currencies_block_top3 li {box-shadow: 1px 1px 1pc #79107a, 0 0 25px #024cd3, 0 0 5px #b9087a;
 margin-right: 3px; padding:3px; background:none ; text-shadow:0px 0px 10px gold; font-size:14px; font-weight:bold; float:left; display:inline-block; margin-left:19px; margin-bottom: 21px;}
#currencies_block_top3 li a {color:white;}
#currencies_block_top3 li.selected {padding:1px; background:black; text-shadow:0px 0px 10px gold; }
#currencies_block_top3 li.selected a{ color:red;}
{/literal}
</style>

<div id="currencies_block_top3">
        <ul>
            {foreach from=$languages item=language}
                    <li {if $language.id_lang == $current_language.id_lang} class="current" {/if}>
                      <a href="{url entity='language' id=$language.id_lang}" class="dropdown-item">
            	         <img src="{$urls.img_lang_url|escape:'html':'UTF-8'}{$language.id_lang|escape:'html':'UTF-8'}.jpg" alt="{$language.iso_code|escape:'html':'UTF-8'}" width="32" height="32" />
            	         {$language.name_simple}
            	        </a>
                    </li>
                  {/foreach}
        </ul>
</div>
`

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by Hlavtox** [comment]
Hi @ninogames12, if you need help with development, this is not the place to use. For help with PrestaShop, you can get on our Slack and ask for help in community-help channel - https://www.prestashop-project.org/slack/. 

But in this case, this is a question about basic CSS. I think there are better places to get information, like [Kevin Powell's YouTube channel](https://www.youtube.com/watch?v=u044iM9xsWU) or [css-tricks.com](https://css-tricks.com/).
