### ISSUE TITLE
How to create choose type drop down in Prestashop birthday registration form 

### ISSUE THREAD

**Issue by ninogames12** [PrestaShop/PrestaShop#30551]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

hello i want create type input in Prestashop birthday registration form how i can make it i get file modify CustomerFormatter.php 

and i get code the Birthday i want make it drop down choose like prestashop version 1.6 i have version 1.7.6

`if ($this->ask_for_birthdate) {
    $format['birthday'] = (new FormField())
        ->setName('birthday')
        ->setType('text')   //change this to date
        ->setLabel(
            $this->translator->trans(
                'Birthdate',
                [],
                'Shop.Forms.Labels'
            )
        )`

![52NFz](https://user-images.githubusercontent.com/120318956/206908230-ddb53bd2-2141-45e2-a116-473f95c7c8cd.jpg)

i have this now i want change it to image number 1 

![birthday](https://user-images.githubusercontent.com/120318956/206908276-3cf252d6-9545-441e-9787-5590bd8f88eb.PNG)

### Steps to reproduce

I want make it like this image please i don't want old style i have version 1.7.6 

and the code 

`if ($this->ask_for_birthdate) {
    $format['birthday'] = (new FormField())
        ->setName('birthday')
        ->setType('text')   //change this to date
        ->setLabel(
            $this->translator->trans(
                'Birthdate',
                [],
                'Shop.Forms.Labels'
            )
        )`

### PrestaShop version(s) where the bug happened

1.7.6

### PHP version(s) where the bug happened

7.4

**Comment by Hlavtox** [comment]
Hello, for modifying the customer form, on 1.7.6, you need to override `classes\form\CustomerFormatter.php`, on v8, you can use hooks. Don't forget to construct a string date from these selectboxes. 1.6 code:
```
$birthday = (int) Tools::getValue('years').'-'.(int)Tools::getValue('months').'-'.(int)Tools::getValue('days'));
```

And again, please stop creating bug reports for help requests, it clearly says in the bug form that you should use a different channel for this, like PrestaShop Slack - https://www.prestashop-project.org/slack/.

![Snímek obrazovky 2022-12-11 235311](https://user-images.githubusercontent.com/6097524/206933695-3a081456-1db0-44af-8e0d-8befae831f56.jpg)

**Comment by ninogames12** [comment]
> Hello, for modifying the customer form, on 1.7.6, you need to override `classes\form\CustomerFormatter.php`, on v8, you can use hooks. Don't forget to construct a string date from these selectboxes. 1.6 code:
> 
> ```
> $birthday = (int) Tools::getValue('years').'-'.(int)Tools::getValue('months').'-'.(int)Tools::getValue('days'));
> ```
> 
> And again, please stop creating bug reports for help requests, it clearly says in the bug form that you should use a different channel for this, like PrestaShop Slack - https://www.prestashop-project.org/slack/.
> 
> ![Snímek obrazovky 2022-12-11 235311](https://user-images.githubusercontent.com/6097524/206933695-3a081456-1db0-44af-8e0d-8befae831f56.jpg)

Thank you so much for replay Mr Hlavtox where i can paste this code please in line 196 or no 
and you say dont forget construct a string date from these selectboxes i'm not programing i want to help to make it and thank u
