### ISSUE TITLE
Dependency At Risk : SwiftMailer is not maintained since Nov 2021

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#30556]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

As said by the website of SwiftMailer, the dependency is not maintained anymore : 
https://swiftmailer.symfony.com/docs/introduction.html

![image](https://user-images.githubusercontent.com/1533248/207056184-a4503b66-5fd8-4c9e-bf1a-f1ead2226ede.png)

### Expected behavior

The website advices to move to Symfony Mailer : https://symfony.com/doc/current/mailer.html

### Steps to reproduce

1. Go to composer.json
2. See that the dependency `swiftmailer/swiftmailer` is present

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by Hlavtox** [comment]
I have been playing with this here and it's not difficult to migrate - https://github.com/PrestaShop/PrestaShop/pull/29447, but as Fabien said, it would be best to do a new implementation, with on-the-fly rendering from twig.

However, it needs to wait for Symfony 5>, because SymfonyMailer in Symfony 4 does not support DKIM signing. :(

**Comment by Progi1984** [comment]
@Hlavtox Can we use directly  https://packagist.org/packages/symfony/mailer#v5.4.16 ? The version is compatible with Prestashop (PHP Version check).

**Comment by sallemiines** [comment]
Hello @Progi1984 

Thanks for reporting the issue !

**Comment by Hlavtox** [comment]
@Progi1984 It seems that the signer is not part of the mailer package, but of symfony itself. 

See https://github.com/symfony/symfony/blob/5.2/src/Symfony/Component/Mime/Crypto/DkimSigner.php

But looking at it, maybe we could backport it for the time being?? It seems to be a completely standalone logic.

**Comment by Hlavtox** [comment]
There are some issues with it though, not sure if it's fixed or not - https://github.com/symfony/symfony/issues/39354

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/32736
