### ISSUE TITLE
Image zoom problem

### ISSUE THREAD

**Issue by ArminTanzanian** [PrestaShop/PrestaShop#30555]

**Comment by kpodemski** [comment]
@ArminTanzanian, what's the URL to your store? I wonder what the image types displayed are. It looks that the type of the image after the zoom is identical to the type shown normally

**Comment by ArminTanzanian** [comment]
https://studio3dprint.net/

**Comment by ArminTanzanian** [comment]
> https://studio3dprint.net/
> 
> Las imágenes son jpeg, hasta los espectáculos más pequeños.

**Comment by ArminTanzanian** [comment]
https://studio3dprint.net/The images are jpeg, even the smallest shows.   De: Krystian PodemskiEnviado: lunes, 12 de diciembre de 2022 10:02Para: PrestaShop/PrestaShopCC: ArminTanzanian; MentionAsunto: Re: [PrestaShop/PrestaShop] Image zoom problem (Issue ***@***.***, what's the URL to your store? I wonder what the image types displayed are. It looks that the type of the image after the zoom is identical to the type shown normally—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
