### ISSUE TITLE
Autoupgrade module from 1.7.8 to Prestsahop 8.0 not working

### ISSUE THREAD

**Issue by pks891618** [PrestaShop/PrestaShop#30561]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

auto-upgrade module not upgrading fPresathop 1.7.8 to latest Prestashop 8.0

### Expected behavior

autoupgrade should allow to upgrade from 1.7.8 to latest Prestashop 8.0

### Steps to reproduce

1. Install Prestashop 1.7.8 
2. install one click upgrade module
3. Try to upgrade from 1.7.8 , its not showing option that list Prestashop 8.0

### PrestaShop version(s) where the bug happened

1.7.8

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

oneclickupgrade

**Comment by PrestaEdit** [comment]
Cf. https://github.com/PrestaShop/PrestaShop/issues/29215

**Comment by pks891618** [comment]
please send direct link from where i can download latest module

**Comment by Hlavtox** [comment]
Hi @pks891618, Prestashop 8 will be available for upgrade very soon, after new version of autoupgrade module is published. 👍 The team was polishing some things so the upgrade to v8 can be smooth.

Follow this issue: https://github.com/PrestaShop/autoupgrade/pull/535
Then a new version of autoupgrade module will be available here: https://github.com/PrestaShop/autoupgrade/releases/

**Comment by hibatallahAouadni** [comment]
Duplicate of #29215

**Comment by hibatallahAouadni** [comment]
Thanks @PrestaEdit & @Hlavtox for your quick replies :rocket:
