### ISSUE TITLE
Faceted Search and order by Brand

### ISSUE THREAD

**Issue by sonosergio** [PrestaShop/PrestaShop#30562]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

if i set the default order of product to manufacturer in pagination preferences of PrestaShop, with the fateced search module active, products without a manufacturer are not shown.

This is because an inner join is made with the manufacturer table from the module fateced search to get the name of manufacturer
.... INNER JOIN pr_manufacturer m ON (p.id_manufacturer = m.id_manufacturer) ....

### Steps to reproduce

go to shop preference > Products > Pagination e set Manufacturer
![Immagine 2022-12-13 084844](https://user-images.githubusercontent.com/5682550/207257935-286e6d04-02b3-4bdc-b1c9-be68a7887f4a.png)
go to backend > catalog > produtcs and set a product without manufacturer
go to frontend in category page with faceted search module enabled

### PrestaShop version(s) where the bug happened

1.7.6.9

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

ps_facetedsearch v3.8.0

**Comment by Hlavtox** [comment]
Nice catch, it should be a left join

**Comment by AureRita** [comment]
Hi @sonosergio ,

Thank for your report, I reproduce the issue with PrestaShop version 1.7.8.7,As you can see 

[Untitled_ Dec 13, 2022 5_42 PM.webm](https://user-images.githubusercontent.com/100699445/207392483-afcbb2fc-88b0-47dc-bafd-ad22d612fc4e.webm)

 I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks

**Comment by marsaldev** [comment]
@Hlavtox you are an expert of this module, any clue on this? 😊

**Comment by Hlavtox** [comment]
@marsaldev Fixed by https://github.com/PrestaShop/ps_facetedsearch/pull/754 ;-)

**Comment by marsaldev** [comment]
@Hlavtox always one step ahead! 🚀
