### ISSUE TITLE
Default theme requests several font files that do not exist

### ISSUE THREAD

**Issue by danielkauffman** [PrestaShop/PrestaShop#30578]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After a fresh install of PrestaShop 8.0.0, when opening the admin pages, the default theme requests several font files that do not exist.

The specific files that are requested are:

> https://example.com/admin/themes/default/public/570eb83859dc23dd0eec423a49e147fe.woff2
> https://example.com/admin/themes/default/public/012cf6a10129e2275d79d6adac7f3b02.woff
> https://example.com/admin/themes/default/public/a37b0c01c0baf1888ca812cc0508f6e2.ttf

Here is a listing of all of the files in that directory:

```
# ls -1 /opt/prestashop/admin/themes/default/public/
04dfc20e12523485d43b23166a4aacb5.woff2
08952b029e4decbc8ef9fb553cae8cea.woff2
1c0b4eb93fcf561eec03297a24922d6c.ttf
24aab533f87e7b434be5fa5b1684975c.svg
27e2a6b40156552483213a255e598fcf.woff2
2980083682e94d33a66eef2e7d612519.svg
2a9a30e14574c9ec24add2901a80b81c.svg
3326e4d74d3924ee1c882c29f5b571c0.woff2
3343e54368719e3786f78a1b22839455.woff2
33f225b8f5f7d6b34a0926f58f96c1e9.ttf
383eba0e55ed778006d76428812d343c.woff2
389ca666f6d8279a80bf54a644c16f20.png
44414f1d2967f27e4068e451826017c0.woff2
525074686dfb8aa36b1b92e29de467ac.woff
55835483c304eaa8477fea2c36abba17.woff2
59b0f4c15b9b43ef643eefa44b5096f3.gif
5a100916f94b0babde0c92aaa8fb80d6.ttf
5aaceea2d60ddb477c6aafc825eece3d.woff2
5be71612af754cc566ec30ef200d8a65.woff
706450d7bba6374ca02fe167d86685cb.ttf
7be88e73fea7b64568a450d7c01346b0.woff
892667349c5cff6fcf7e40439596b97c.woff
94cef4c50fdde3db87d08031a829d1a8.preload.woff2
97493d3f11c0a3bd5cbd959f5d19b699.woff2
9b30f13428e1b4a659aeeab4ac1fff35.ttf
9f2144213fad53d4e0fdb26ecf93865f.woff
a282a2adada37bcc8a97c8113733e56c.png
a33a878f3861ca67e9bc423c58b2a357.svg
ac327c4db6284ef64ebe872b6308f5da.woff
b46ff9f5c8bcba1ea3b4b320e22be5c7.svg
bf4dde0147bb02556500d922e2efc90b.svg
c36b5ac7c2dddf6f525c8d161412ef41.ttf
cd7296352d159532b66c07d98efb1126.ttf
cd94e25905d9ac90bab221600bf19312.png
d9ee23d59d0e0e727b51368b458a0bff.woff
eb24af6668c633feab6bf8f989296e73.woff2
ec55f263e2b86bc0f28fff46b873d6df.woff
f7c2b4b747b1a225eb8dee034134a1b0.eot
fabb0801a35dfb37b94447b53e588e80.gif
fbc2a379fdad6d5a1b10c881644bc5dd.png
fedf49d31f55f4beaf2c891f3875554f.svg
preload.tpl
rtl.css
theme.bundle.js
theme.css
thirdPartyNotice.json
```

See also #29559 regarding these same files. The most likely explanation for that issue is that these font files were corrupt. If this corruption was corrected, and the file name is simply a hash of the contents, then the file name would have changed when the corruption was corrected. **If the theme was not updated to refer to the updated filenames, that would explain this issue. All three of these file hashes appear in: /themes/custom/assets/css/theme_rtl.css**

### Expected behavior

Expected behavior is for PrestaShop to load the default themes without any missing files.

### Steps to reproduce

1. Download and install PrestaShop from the command line.

```
wget -O /opt/prestashop.zip https://github.com/PrestaShop/PrestaShop/releases/download/8.0.0/prestashop_8.0.0.zip
unzip -q /opt/prestashop.zip
cd /opt/prestashop
rm index.php
unzip -q prestashop.zip
php install/index_cli.php
````

2. Open browser and browse to https://example.com/admin
3. View 404 errors in the inspector for these font files.

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.4.28

**Comment by danielkauffman** [comment]
Same issue in PrestaShop 1.7.8.8.

**Comment by danielkauffman** [comment]
PrestaShop 1.7.8.7 works as expected.

**Comment by danielkauffman** [comment]
Could be related to this commit: https://github.com/PrestaShop/PrestaShop/commit/19ff99e8681379d8e5436558d74c9f6b72a59f73

**Comment by NeOMakinG** [comment]
Mmmh, I would say that shipped assets are wrong compared to the codebase, maybe there was a miss somewhere because I can't reproduce it on develop

**Comment by danielkauffman** [comment]
@florine2623 Regarding NMI what are you needing?

**Comment by danielkauffman** [comment]
As mentioned above, easy to grep  /themes/custom/assets/css/theme_rtl.css to confirm the existence of the missing file names in that file and to list the specified directory to confirm the absence of these files from the directory.

**Comment by NeOMakinG** [comment]
> As mentioned above, easy to grep /themes/custom/assets/css/theme_rtl.css to confirm the existence of the missing file names in that file and to list the specified directory to confirm the absence of these files from the directory.

Oh I didn't notice, this bug can probably be reproduced only using RTL right?

**Comment by hibatallahAouadni** [comment]
Hello @danielkauffman 

It seems there's missing steps, cause following yours, when I try to browse to https://example.com/admin it redirects me to /install
So did you forget to mention any steps? Please check and feedback.

Thanks!

**Comment by runnyren** [comment]
I can't see anything that [influenced](https://gorlice24.pl/pl/661_materialy-partnera/8727_jaki-wplyw-na-handel-elektroniczny-ma-covid-19.html) this one.

**Comment by danielkauffman** [comment]
@NeOMakinG

> Oh I didn't notice, this bug can probably be reproduced only using RTL right?

Strangely, the RTL CSS is loaded even though I'm using the EN-US locale.

**Comment by danielkauffman** [comment]
@hibatallahAouadni Did you install from the command line as described above? I suppose the redirect from /admin to /install would happen if you haven't installed.

**Comment by danielkauffman** [comment]
@hibatallahAouadni @NeOMakinG please join me in reporting runnyren as a spammer/scammer.

**Comment by HanaRebaiQA** [comment]
Hello @danielkauffman 

I tried to reproduce your issue when installing PrestaShop_8.0.0 using the command lines : 

-My proper command line to install via CLI, but I couldn't reproduce your issue when browsing to `mydomain/admin`
![image](https://user-images.githubusercontent.com/92912932/209933300-4b53ef7d-6c83-4668-a60a-4ebafe117672.png)
![image](https://user-images.githubusercontent.com/92912932/209933434-647b9e43-3d20-443e-9de1-3befe39738f3.png)

-Your provided command. In this method, it redirects to install and not to admin, so I have installed it and i couldn't reproduce your issue

```
wget -O /opt/prestashop.zip https://github.com/PrestaShop/PrestaShop/releases/download/8.0.0/prestashop_8.0.0.zip
unzip -q /opt/prestashop.zip
cd /opt/prestashop
rm index.php
unzip -q prestashop.zip
php install/index_cli.php
```

![image](https://user-images.githubusercontent.com/92912932/209933795-c6317902-cb5a-405f-a943-76909b68170c.png)
![image](https://user-images.githubusercontent.com/92912932/209933829-e2da3027-0b37-4ac6-9896-21f122caf781.png)
![image](https://user-images.githubusercontent.com/92912932/209933856-02c5d434-3767-4745-a9e7-6e4d24b27582.png)

![image](https://user-images.githubusercontent.com/92912932/209933741-40923bbd-2e37-4149-8836-26d926ff8b90.png)

Did I missed something?

Thank You!

**Comment by florine2623** [comment]
Hello @danielkauffman ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
