### ISSUE TITLE
Error when accessing the admin in 1.7.8.8

### ISSUE THREAD

**Issue by Carmela-D** [PrestaShop/PrestaShop#30579]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After upgrading from 1.7.8.7 to 1.7.8.8, with 1 click upgrade and all requirements OK and a correct end of process, when trying to access I get this error 

An attempt has been made to call an undefined method called "getLoginActivated" of the class "PrestaShop\Modules\PsAccountsService\PsAccountsService".
[Symfony "Component" methodException "MethodException 0".]

I activated debug mode manually, as I could not access the BO and could not locate the problem. I deleted cookies, cleared caches and did everything I could to see if it would fix it.
In the end I had to rollbak from ssh to remove the update as it is a production site.
Any idea what could be going on?

Información del servidor: Linux #1 SMP Wed Sep 11 10:29:54 EDT 2019 x86_64

Versión del software del servidor: Apache

Versión PHP: 7.4.32

Límite de memoria: 1024M

Tiempo máx. de ejecución: 600

Tamaño máx. para la subida de archivos: 256M

Versión de MySQL: 5.7.36-cll-lve

controllers/front/AuthController.php
modules/contactform/contactform.php

Versión de PrestaShop: 1.7.8.7

URL de la tienda: http://shop.dressageboutique.es/

Ruta de la tienda: /home/mk54swki/public_html

Tema actual en uso: akira-child-theme

### Steps to reproduce

1. Execute 1 click upgrade
2. All Steps Ok
3. Acces Error

![Captura de pantalla 2022-12-14 185449](https://user-images.githubusercontent.com/43498778/207797715-66623eb1-5237-4ad0-aa8f-a835c1e720ac.png)

### PrestaShop version(s) where the bug happened

from 1.7.8.7 to 1.7.8.8

### PHP version(s) where the bug happened

PHP: 7.4.32

### If your bug is related to a module, specify its name and its version

PsAccounts last version

**Comment by florine2623** [comment]
Hello @CcvTam ,

I made an upgrade from 1.7.8.7 to 1.7.8.8, it worked as expected:
<img width="1213" alt="Screenshot 2022-12-15 at 10 53 28" src="https://user-images.githubusercontent.com/16019289/207828577-9f69ead8-24a8-46e8-b66d-5b69e42cc7f4.png">

I suggest you to disable the module psaccount and ps_metrics before you do the upgrade.

As this issue comes from an external module and not a native module, I'll close this issue :)

Thanks!

**Comment by Carmela-D** [comment]
Ok, thank you :)
