### ISSUE TITLE
Partial refunds error

### ISSUE THREAD

**Issue by ZAPS0N** [PrestaShop/PrestaShop#30572]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,
I have a problem with partial refund after Prestashop update. My current version is 1.7.8.7. The error message is: **An unexpected error occurred. [PrestaShopException Code 0]: The OrderDetail->product_quantity_in_stock property is invalid**. There is nothing else except this message, even with dev mode enabled. The crowd of the item is equals to 1.

EDIT: The same error occurs when I'm trying to change customer billing address inside the order "The OrderDetail->product_quantity_in_stock property is invalid"

### Steps to reproduce

1.  Go to orders and select random order
2. Click partial refund
3. Enter quanitity of the product (1)
4. Click partial refund submit button
5. After that error occurs

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment]
Hello @ZAPS0N 

I didn't manage to reproduce the issue with PS1787, see the attached screen record below:

[issue_30572.webm](https://user-images.githubusercontent.com/23308427/207681317-644820a1-5501-4f4b-8838-642bac68d1ff.webm)

Please check and feedback.

Thanks!

**Comment by ZAPS0N** [comment]
Hello @hibatallahAouadni, 
thanks for your reply. 
Unfortunately, I followed the same steps as you when this error occur.
As I wrote before - everything worked fine before the update and stopped after it. 

EDIT: The same error occurs when I'm trying to change customer billing address inside the order "The OrderDetail->product_quantity_in_stock property is invalid"

**Comment by hibatallahAouadni** [comment]
Hello @ZAPS0N 

Thanks for your feedback!
> As I wrote before - everything worked fine before the update and stopped after it.

What do you mean before update? did you upgrade your shop? if so, what was your old version?
Waiting for your feedback.

Thanks!

**Comment by ZAPS0N** [comment]
The previous version was 1.7.6.8 and I updated it using the 1-Click Upgrade module. There was no errors.

**Comment by hibatallahAouadni** [comment]
Hello @ZAPS0N 

thanks for your feedback 🙏 
Could you please provide your 1-Click Upgrade module version and did you encounter any errors while upgrade?
Waiting for your feedback.

Thanks!

**Comment by ZAPS0N** [comment]
Hello @hibatallahAouadni ,

my 1-Click Upgrade module version is 4.14.2 and as I wrote before - there was no errors during the update.

**Comment by hibatallahAouadni** [comment]
Hello @ZAPS0N 

Did you encounter the issue with only orders that are created before the upgarde? or even with the newest created orders?
Waiting for your feedback.

Thanks!

**Comment by ZAPS0N** [comment]
Hello @hibatallahAouadni ,
the error occurs in both old and new orders.

**Comment by HanaRebaiQA** [comment]
Hello @ZAPS0N 

I tried to reproduce your issue with **PS1.7.8.7 fresh install** and using the **upgrade from PS1.7.6.8 to PS1787** as you have mentioned above, but i was unable to reproduce it. 

- Check the partial refund on PS1787 on BO and FO with php 7.3 : OK :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/208869011-c1fabd52-cf2b-4468-8897-1cdab6b8fd1f.png)

https://user-images.githubusercontent.com/92912932/208868715-122401ec-37df-4e3a-9ff3-a9eae9b56d0b.mp4



- Check the partial refund using the 1-click upgrade v4.14.2 to upgrade from PS1.7.6.8 to PS1787 with php 7.2 : 

  - Create an order before the upgrade and check it on BO and FO : OK :heavy_check_mark: 
  - Create a new order following the upgrade and check it on BO and FO : OK :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/208868868-8928a157-5969-4bef-a409-0ca6482acec8.png)

https://user-images.githubusercontent.com/92912932/208869277-5d6355e9-eead-4431-8968-c0ea244bf15b.mp4



So, I'll close your issue cause despite our efforts we were unable to reproduce it.

Thank You!
