### ISSUE TITLE
No route found for "GET /sell/orders/<ORDERID>/status" Method Not Allowed (Allow: POST)

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/PrestaShop#30577]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I've noticed that when an order is payed by BANK Wire, when the customer pay and I go to change the order from "waiting bank payment..." to "Payment Accepted" the Payment area inside the order is not updatet:

![image](https://user-images.githubusercontent.com/16102074/207702879-23a8f34b-3c35-4708-a44f-5d1384a3ecc5.png)

I've upgradced from 1.7.6.5 to 1.7.8.7 and in the previous version 1.7.6.x when you cange the status "payment accepted" automatically the Payment info was filled with the same data and hour of "paytment accepted" status, the total due and the method "Bank Wire".

Now remain empty, and sometimes i get this error on BO every time i've to change a status of an order payed by Bank Wire:

![image](https://user-images.githubusercontent.com/16102074/207703560-7a0467f4-07e3-437a-b244-947c06c8c29d.png)

I tried to investigate on error_logs but no errors are saved, only this screen error

### Expected behavior

When an order is payed by Bank Wire, and you receive the payment from the cusatomer, usually when you change the status from "waiting Bank wire payment.." to "Payment Accepted" the information of the payment will be transfered on the PAYMENT AREA like that:

![image](https://user-images.githubusercontent.com/16102074/207703910-a23e956b-a999-4de2-9cef-1ba118aa8981.png)

### Steps to reproduce

1. Edit and Order made with Bank Wire
2. Change statos to "Payment Accepted"
3. The information oif the payment must appear in the payment area insaide the order but in my case is never filled.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_wirepayment  v2.1.3

**Comment by florine2623** [comment]
Hello @HartLarsson ,

I've followed your steps using autoupgrade module v4.14.2.

Installed PS 1.7.6.5 > updated it to 1.7.8.7 successfully:

<img width="1202" alt="Screenshot 2022-12-15 at 11 21 06" src="https://user-images.githubusercontent.com/16019289/207834932-b3d46ffa-f618-4344-b937-409fc3c13c37.png">

Then updated the shop to PS 1.7.8.8 successfully:
<img width="1191" alt="Screenshot 2022-12-15 at 11 37 14" src="https://user-images.githubusercontent.com/16019289/207837860-63e8b1b9-8509-4b9d-88a6-e4684f14a1ce.png">

I can't reproduce your issue, I'm also using ps_wirepayment v2.1.3:

https://user-images.githubusercontent.com/16019289/207838457-bd371b6c-fca9-4f6e-ac5b-a70d86b037ed.mov

Do you have more info on how to reproduce your issue ?
Please check and feedback ^^
Thanks!

**Comment by HartLarsson** [comment]
@florine2623 i still doing other testing and post more feedback asap ... thank you for your test too :)

**Comment by HanaRebaiQA** [comment]
Hello @HartLarsson 

We are waiting for more information then to can reproduce the issue. 
Thank You!

**Comment by HartLarsson** [comment]
> Hello @HartLarsson
> 
> We are waiting for more information then to can reproduce the issue. Thank You!

I still continue to monitor the situation and captured this error

`[2022-12-22 20:02:58] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: "No route found for "GET /sell/orders/list/1504/status": Method Not Allowed (Allow: POST)" at /home2/userxxx/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 141 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"GET /sell/orders/list/1504/status\": Method Not Allowed (Allow: POST) at /home2/userxxx/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:141, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /home2/userxxx/public_html/var/cache/prod/appProdProjectContainerUrlMatcher.php:7548)"} []`

Every Bank Transfer payment method, i've the same problem, when i change status to "payment accepted" the payment record is not created.

I've done this things:

1) clean the cache
2) reinstalling the bank wire module again (wirepayment v2.1.3)

but every time the record in the payment area is not created automatically. i need to create the record manually that is very strange.

https://gyazo.com/c51b9c0044c9c3fcd7735ed4a108a908

Is there a way or places where i can check if there is a problem during PS upgrade 1.7.6.5 -> 1.7.8.7 related to missing payment update during status update?

Thanks

**Comment by sallemiines** [comment]
Hello @HartLarsson 

I can't reproduce your issue, I'm using` ps_wirepayment v2.1.3`:

You can see the attached screen record 

[Untitled_ Dec 23, 2022 2_26 PM.webm](https://user-images.githubusercontent.com/31663369/209343681-76ebe7bd-8421-46e6-a745-e875da2eac6a.webm)

Thank you !

**Comment by HartLarsson** [comment]
> Hello @HartLarsson
> 
> I can't reproduce your issue, I'm using` ps_wirepayment v2.1.3`:
> 
> You can see the attached screen record
> 
>  Untitled_.Dec.23.2022.2_26.PM.webm 
> Thank you !

Bank Wire not Payment by Check :)

**Comment by 2f2c** [comment]
Hello @HartLarsson,
if you uncheck the box "Consider the associated order as validated" in the report, it's Ok... 
I don't know why...

**Comment by HartLarsson** [comment]
> Hello @HartLarsson, if you uncheck the box "Consider the associated order as validated" in the report, it's Ok... I don't know why...

So uncheck the option in the status "Payment accepted" the Bank Wire payment will be added to Payment list during state change?
very strange!

**Comment by josecarlosphp** [comment]
Hi, I'm working on a PrestaShop 8 store that throws the same error, but it's not related to ps_wirepayment.
I'm getting more information about it.

**Comment by HartLarsson** [comment]
i think the problem depends by the fact I still using a child theme. 
I need to investigate more to find out if the problem occur if the mail template not appear under the child theme.

**Comment by devxpoint** [comment]
Hi there,
the problem still exists. Prestashop 8.2.0 with PHP 8.1 and ps_wirepayment 2.2.0
Uncheck "Consider the associated order as validated" don't help.
Placed order with "wire payment" and also other payments, so the bug is not related to wire payment!
Trying to change the order state to "Payment accepted" crashes.

Found out it was a problem with the module "ps_legalcompliance"

**Comment by Prophecik** [comment]
Hi, did anyone find solution? I have similar problem.

**Comment by devxpoint** [comment]
> Hi, did anyone find solution? I have similar problem.

Mostly it is a problem with a third party module.
Maybe deactivating them -> test. If it works, activating one by one and testing everytime...

**Comment by HartLarsson** [comment]
> Hi there, the problem still exists. Prestashop 8.2.0 with PHP 8.1 and ps_wirepayment 2.2.0 Uncheck "Consider the associated order as validated" don't help. Placed order with "wire payment" and also other payments, so the bug is not related to wire payment! Trying to change the order state to "Payment accepted" crashes.
> 
> Found out it was a problem with the module "ps_legalcompliance"

i've tested on cloned website and disabled all modules that are not ps standard and i've not find a solution. 

How you solved with the module ps_legalcompliance ??

**Comment by devxpoint** [comment]
> > Hi there, the problem still exists. Prestashop 8.2.0 with PHP 8.1 and ps_wirepayment 2.2.0 Uncheck "Consider the associated order as validated" don't help. Placed order with "wire payment" and also other payments, so the bug is not related to wire payment! Trying to change the order state to "Payment accepted" crashes.
> > Found out it was a problem with the module "ps_legalcompliance"
> 
> i've tested on cloned website and disabled all modules that are not ps standard and i've not find a solution.
> 
> How you solved with the module ps_legalcompliance ??

I disabled the module, cleared cache and installed latest version from https://www.onlineshop-module.de/rechtssicherheit-prestashop-8x.html
Its free :)

**Comment by HartLarsson** [comment]
> > > Hi there, the problem still exists. Prestashop 8.2.0 with PHP 8.1 and ps_wirepayment 2.2.0 Uncheck "Consider the associated order as validated" don't help. Placed order with "wire payment" and also other payments, so the bug is not related to wire payment! Trying to change the order state to "Payment accepted" crashes.
> > > Found out it was a problem with the module "ps_legalcompliance"
> > 
> > 
> > i've tested on cloned website and disabled all modules that are not ps standard and i've not find a solution.
> > How you solved with the module ps_legalcompliance ??
> 
> I disabled the module, cleared cache and installed latest version from https://www.onlineshop-module.de/rechtssicherheit-prestashop-8x.html Its free :)

is all in german? :)

**Comment by devxpoint** [comment]
The shop yes, the module has english translation. Maybe you dont need the module???
