### ISSUE TITLE
Images all have a wrong url

### ISSUE THREAD

**Issue by nitschis** [PrestaShop/PrestaShop#30589]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the default E-mail templates, pictures selected in the editor/file picker, and in creative elements, all images have the wrong URL.

The URL is:
/:443/img/cms/5DM_4442.jpg

But it should be and only works if it is like this:
/img/cms/5DM_4442.jpg

Where does the /:443 come from? I did not find anything in the database or config files.

I have tried clearing caches, recreated my .htaccess.

I use the official docker image behind a ngnix-proxy with letsencrypt.

### Steps to reproduce

Explained above

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.3.24

**Comment by HanaRebaiQA** [comment]
Hello @nitschis 

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template and provide clear and concise steps to reproduce the bug**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by nitschis** [comment]
Since I have no idea where the /:443 comes from, it is impossible for me to write a guide to reproduce this issue. My shop is broken in this way, and I am looking for a way to fix this issue.

What do you suggest I do?

**Comment by matks** [comment]
> Since I have no idea where the /:443 comes from, it is impossible for me to write a guide to reproduce this issue. My shop is broken in this way, and I am looking for a way to fix this issue.

Then the best place to look for help would be there https://www.prestashop-project.org/support/

it is possible you'll need to contact a professional to analyze your shop.

**Comment by nitschis** [comment]
Will do, thank you.
