### ISSUE TITLE
ps_emailmanager v1.2.1 with PS 8.0.0 throws an Exception

### ISSUE THREAD

**Issue by maxims73** [PrestaShop/PrestaShop#30580]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello. With Prestashop 8.0.0, trying to configure Email template managed i have error 500 code related to JsonDecode. Here is the description of error code i have:
Attempted to call an undefined method named "jsonDecode" of class "Tools".

Symfony\Component\ErrorHandler\Error\
UndefinedMethodError
in [C:\xampp742\htdocs\presta8\modules\ps_emailsmanager\ps_emailsmanager.php ](http://localhost/presta8/adminmax/index.php/_profiler/open?_token=w73iPafRxTDgnBemcwjMODcpipgu-yZp7aJ2TR4qT_E?file=modules\ps_emailsmanager\ps_emailsmanager.php&line=847#line847)(line 847)
       
842. foreach ($templatesDir as $tpl) {           
843. $settings = $uploadDir.$tpl.DIRECTORY_SEPARATOR.'settings.json';           
844.  if (file_exists($settings)) {              
845.  $settings = Tools::file_get_contents($settings);           
846.  if ($settings) {                    
847. $template = Tools::jsonDecode($settings, true);                  
848.  $template['folder'] = $tpl;                  
849.   $templates[] = $template;               
850.  }        
851.    }      
852.   }

### Steps to reproduce

1. Open Emails Template Manager from Modules
2. click to Configure and error appear.

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

php 7.4.2

### If your bug is related to a module, specify its name and its version

ps_emailsmanager v 1.2.1

**Comment by florine2623** [comment]
Hello @maxims73 ,

This module is not a native module from PrestaShop. 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by florine2623** [comment]
Hello @maxims73 ,

I have reproduced your issue on PS 8.0.0:
<img width="1044" alt="Screenshot 2022-12-15 at 14 52 53" src="https://user-images.githubusercontent.com/16019289/207876171-49502cf0-e212-499e-8c92-cf5b74592201.png">

**Comment by florine2623** [comment]
ping @PrestaShop/product-team ,

Is this module still maintained by OS team ? 
I have found this : https://github.com/PrestaShopCorp/ps_emailsmanager

**Comment by maxims73** [comment]
Thanks Florine for reopen and reproduced the issue. 
The module is still available on Prestashop addons website and marked as Compatible with prestashop from 1.5 to 8.0 versions. I uploaded a screenshop of PS Addons website: https://ibb.co/fCBnM42
In Prestashop 8.0 Backend there is no more a Module catalog such as in previous versions.

**Comment by maxims73** [comment]
> ping @PrestaShop/product-team ,
> 
> Is this module still maintained by OS team ? I have found this : https://github.com/PrestaShopCorp/ps_emailsmanager

Yes, i have used 1.2.1 version of same module

**Comment by matks** [comment]
> ping @PrestaShop/product-team ,
> 
> Is this module still maintained by OS team ? I have found this : https://github.com/PrestaShopCorp/ps_emailsmanager

This module now belongs to the PrestaShopCorp GitHub organization that is managed by PrestaShop SA. This is out of the scope of the open source project.

**Comment by florine2623** [comment]
As @matks said, this module is not in the scope of the open source project. You can contact the developer of the module directly through their support to get an answer.

I will close your issue ^^
Thanks for your understanding!
