### ISSUE TITLE
Extensible logic for displaying delivery methods in checkout (cart)

### ISSUE THREAD

**Issue by integritty** [PrestaShop/PrestaShop#30586]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Currently, PrestaShop does not allow you to create custom logic for displaying delivery methods in the cart. For our clients, we often need to customize the display logic for specific products in the cart.

We currently do this via an override in the PrestaShop core, specifically in /classes/Carrier.php

### Describe the solution you'd like

I'd like to add a new hook to the kernel that will allow transport methods to be changed from the module without using overrides.

In file classes/Carrier.php inside static function getAvailableCarrierList() i would like to add filter hook before returning $carrier_list array.

This hook would pass the cart & product objects and the current list of delivery methods. This would allow the programmer to modify delivery methods before render.

```
Hook::exec('filterAvailableCarrierList', [
        'product' => $product,
        'cart' => $cart,
        'carrier_list' => &$carrier_list
    ]
);
```

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by Hlavtox** [comment]
This hook is already there - `actionFilterDeliveryOptionList`, allowing you to do exactly what you want.

Docs - https://devdocs.prestashop-project.org/8/modules/concepts/hooks/list-of-hooks/actionfilterdeliveryoptionlist/
Cart is accessible by `$this->context->cart`.

**Comment by integritty** [comment]
Ohh, my fault. Thank you.

**Comment by Hlavtox** [comment]
No worries! :-)
