### ISSUE TITLE
How to remove the price on the PDF delivery note

### ISSUE THREAD

**Issue by Peter26100** [PrestaShop/PrestaShop#30582]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

we want to remove the price that is displayed on the PDF delivery note. Can you tell us how to remove this line of information waiting for your help thank you

### Describe the solution you'd like

Delete the price that appears on the PDF delivery note

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by florine2623** [comment]
Hello @Peter26100 ,

You can go to `your_shop/pdf/delivery-slip.payment-tab.tpl` and delete the line:
<img width="899" alt="Screenshot 2022-12-15 at 11 33 36" src="https://user-images.githubusercontent.com/16019289/207837259-079400c4-4412-494e-877b-2f06fc07ded1.png">

I'm closing this issue.
Thanks!

**Comment by Peter26100** [comment]
Thanks for your help !
