### ISSUE TITLE
After installing 8.0.x no css in front and admin loading

### ISSUE THREAD

**Issue by pks891618** [PrestaShop/PrestaShop#30581]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have cloned branch 8.0.x and installed it. But in frontend and backend its not loading the css

### Expected behavior

frontend and backend css should need to load

### Steps to reproduce

1. clone https://github.com/PrestaShop/PrestaShop
2. switch to branch 8.0.x
3. composer install
4. install prestashop 8.0
5. after installing check frontend and backend
6. its not loading CSS 

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.0.x

**Comment by florine2623** [comment]
Hello @pks891618 ,

Can you do a `make assets` after your `composer install` ?

Please check and feedback.
Thanks!

**Comment by pks891618** [comment]
@florine2623  sorry didnt understand

**Comment by kpodemski** [comment]
@pks891618 

Hi! You can see the docs to understand the process better:
https://devdocs.prestashop-project.org/8/basics/installation/localhost/#javascript-and-css-dependencies

It's not a PrestaShop issue, you need to compile assets from sources :)

If you have more questions, you can visit [the project's Slack](https://www.prestashop-project.org/slack/).
