### ISSUE TITLE
FO: classic-theme 2.0.6 Undefined index additional_description in category-footer.tpl in PS 1.7.8.x

### ISSUE THREAD

**Issue by leemyongpakvn** [PrestaShop/PrestaShop#30595]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

classic-theme from v2.0.0 to v2.0.6 throws a ContextErrorException about `Undefined index additional_description in category-footer.tpl` in PS 1.7.8.x
![Prestashop_1 7 8 x_categoryAdditional_notExist](https://user-images.githubusercontent.com/3759923/208303285-71b33022-ae3c-4c6c-8fb9-1e754956c0ef.png) 

### Expected behavior

classic-theme stop throwing that error in PS 1.7.8.x :)

### Steps to reproduce

1. Upgrade classic-theme on PS 1.7.8.x to any version from 2.0.0 to 2.0.6
2. In BO: enable Debug mode 
3. In FO: open a Category page to see error like the above screenshot

### PrestaShop version(s) where the bug happened

1.7.8.x

### If your bug is related to a module, specify its name and its version

classic-theme from v2.0.0 to v2.0.6

**Comment by kpodemski** [comment]
Just FYI, Classic theme v2 meant to be used in PrestaShop 8+.

**Comment by leemyongpakvn** [comment]
Thanks for your information. I think we need to write it down to classic-theme repository's About clearly.

**Comment by leemyongpakvn** [comment]
@kpodemski FYI, **lramos-prolaser** fixed the similar bug with hummingbird for PS 1.7.8.7 at PrestaShop/hummingbird/issues/367 2 months ago.

**Comment by hibatallahAouadni** [comment]
Hello @leemyongpakvn 

Thanks for your issue and your feedback.
But, we need to check with PM if we can make classic theme v2 compatible with PS1788.
Ping @PrestaShop/product-team as @kpodemski mentioned above the classic-theme v2 is not compatible with PS1788, so should we approuve @leemyongpakvn idea and PR?

PS: thanks @kpodemski for your quick reply 🚀 

Thanks!

**Comment by kpodemski** [comment]
Hi @leemyongpakvn

I don't think we need to wait for PM, really. The classic theme is, and should be, compatible only with PrestaShop 8.0+. This was agreed upon weeks ago, and it would make maintaining the classic very problematic if we support both versions.

https://github.com/PrestaShop/classic-theme/blob/develop/config/theme.yml#L11

And regarding Hummingbird, for a moment, there was an idea to make it compatible with PrestaShop 1.7 to allow people to test it. That's not the case anymore. It was discussed with @NeOMakinG and a few other maintainers.
