### ISSUE TITLE
[gsitemap] - Do not include IDs in URL when those have been disabled (via for example SEO Performance - URL cleaner)

### ISSUE THREAD

**Issue by Hokuto-shinken** [PrestaShop/PrestaShop#30617]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Using gsitemap [4.2.0]:
Google search console (ex webmaster tool) is complaining about "Duplicate, Google chose different canonical than user",
because the sitemap that gsitemap module generate URLs using/inserting the ID, while at the same time I am using a SEO URL cleaner module, that generate canonical page without the ID.

Example:

Sitemap generated URL for products:
https://myweb/mycategory/2198-thisproduct.html

This page thanks to the SEO URL cleaner module, is indeed:
https://myweb/mycategory/thisproduct.html (ID removed).
And in the source code of this very page:
<link rel="canonical" href="https://myweb/mycategory/thisproduct.html">

And this triggers error in Google search console: "New Page indexing issues detected in submitted URLs for myweb".

### Describe the solution you'd like

Hi Dear,

So I am not sure I am the only one having a problem here, but it would be very nice to see situation handled but the gsitemap module. If I am wrong or so, please accept kindly in advance my apologizes.

If until this is accepted as a feature-request and somehow merged and showing up, does someone has a way to make gsitemap works as I would like? (maybe detection of URL ID removal can be tricky, so why not add just the option to remove the ID as a button in the gsitemap settings, so people just can switch it on if needed).

Thanks a lot to all in advance.

Best regards

Ken

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by Hlavtox** [comment]
You should implement your own sitemap module or make a fork of the default one and modify it. We do not recommend removing IDs from URLs and native modules are not prepared for this. 👍

**Comment by Hokuto-shinken** [comment]
Hi Dear, @Hlavtox , @hibatallahAouadni, @Caleydon, @gRoussac, @jnadaud, @PierreRambaud 

So I will try to fork it .. but
Please could kindly provide a hint about where I could get rid of the IDs in the URLs in the gsitemap php code?

Thanks a lot.
Regards

Ken

**Comment by PierreRambaud** [comment]
Sorry, I think I'll never touch a prestashop instance or anything else related to it, you should contact the core team ^^

**Comment by gRoussac** [comment]
@PierreRambaud why is that ? after 4 years working on the core, what happened ?

**Comment by PierreRambaud** [comment]
Long story 👀

**Comment by Hokuto-shinken** [comment]
Hi @PierreRambaud  , 

I am sorry to hear about that :( 
I added you and others to the thread before I found your name in the CONTRIB file of this module,
and since I saw a lot of occurence of you being heavily involved in the Prestashop project I though you could maybe help here.

1) If I have understood help, does it really means that you will not be involved in nything related to Prestashop?
It would a pity, and great lost  .. really. I personally hope that in future you revert your decision, so that the whole community can benefit from your experience and expertise.

2) Well, going back to my "issue", do you know, or does someone knows whom I should to get help to get rid of the ID
in URLs generated by gsitemap.

Thanks again to all.
I am wishing you by advance a Merry christmas to all and certainly an Happy 2022 ending and Great 2023 beginning.

And again sorry for disturbing you guys with my request.

Best regards

Ken

**Comment by gRoussac** [comment]
@Hokuto-shinken 

1. that's some nice words man
2. I believe your issue is more like: I am using a custom url cleaner and I would like to tweak this plugin to fit my needs as apparently PS still relies on ids in the url in 2022, maybe 2023. I would search if there is already a module for that in their modules shop and otherwise on the forum you would find somebody who can tweak you that in this module, it's probably arround this line to override https://github.com/PrestaShop/gsitemap/blob/7f0bc3781f160bec649980212f9e961acb1bd39d/gsitemap.php#L404

PS: don't ping random contributors on GitHub to get a modification in PS. Invest your self in the community and make your need raise among Feature requests.

Cheers good luck

**Comment by Hlavtox** [comment]
Guys, raising and thumbing up anyone's need in the pile of feature requests won't help anything. If you have an good idea that most users (>50 %) will benefit from, get a group of people together, make it and submit a PR. That's what it's about.

@Hokuto-shinken I think that any skilled PS developer would be able to make you a custom copy of gsitemap module that will generate the URLs without the ID there. 👍 It should not be THAT difficult, but you need to respect the URL structure of your the module that is removing the IDs from URLs.

_______

And yeah @PierreRambaud went to search different ways in life, so I have to take care of `ps_facetedsearch` now 😄😄

**Comment by Hokuto-shinken** [comment]
Hi everyone,

Definitively, I will along everyone here wish a nice and great new step in life to @PierreRambaud ! 

@gRoussac : Thanks for the hint about where I should start investigate the code! And yes I have got you. 
indeed this thread was originally a feature request, but that got closed.

@Hlavtox: Yes, I got you 100% as well, again I am sorry for not having being able to handle this the optimal way (I based
contacting people using the CONTRIB file of the module, but It looks like this was not the best or aproprite way).

And yes I still need to invest myself in the community (I wish I did this earlier), and understand the workflow (PR vs Feature request for example).

Still, this is great because exchanging with you guys, put my in the right track.

Have a merry christmas everyone, a good 2022 ending and a great 2023 ! 
Wishing the best to everyone ever involved in the PS project and their families !
Thanks a lot guys for bringing to the masses this great product open and free 👍 

Regards

Ken

**Comment by Hlavtox** [comment]
Merry christmas to you too! :-)

Come chat with everyone on Slack - https://www.prestashop-project.org/slack/, maybe there are people with the same module.

**Comment by PierreRambaud** [comment]
> Hi @PierreRambaud ,
> 
> I am sorry to hear about that :( I added you and others to the thread before I found your name in the CONTRIB file of this module, and since I saw a lot of occurence of you being heavily involved in the Prestashop project I though you could maybe help here.
> 
> 1. If I have understood help, does it really means that you will not be involved in nything related to Prestashop?
>    It would a pity, and great lost  .. really. I personally hope that in future you revert your decision, so that the whole community can benefit from your experience and expertise.
> 2. Well, going back to my "issue", do you know, or does someone knows whom I should to get help to get rid of the ID
>    in URLs generated by gsitemap.
> 
> Thanks again to all. I am wishing you by advance a Merry christmas to all and certainly an Happy 2022 ending and Great 2023 beginning.
> 
> And again sorry for disturbing you guys with my request.
> 
> Best regards
> 
> Ken

Thanks a lot for your message (and you too @Hlavtox :heart: ), but there is absolutely no chance for me to come back for a lot of reasons I exposed when I decided to leave this project.
