### ISSUE TITLE
Overflowing logo on maintenance mode page

### ISSUE THREAD

**Issue by amaury-hanser** [PrestaShop/PrestaShop#30625]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I use the Classic theme.
If I upload a wide logo, it will overflow on the maintenance page.

![image](https://user-images.githubusercontent.com/25964813/208725581-25e55c63-1b24-4ff2-bf9f-03f0a8dddb31.png)

---

Bug is related to classic theme, so the PrestaShop version doesn't matter.

### Expected behavior

I want the logo to be resized to not overflow it's container.

### Steps to reproduce

1. Upload a wide logo
2. Activate maintenance mode
3. Go to the front office
4. Cry 😭

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by hibatallahAouadni** [comment]
Hello @amaury-hanser 

Thanks for the funny bug report 😄 Indeed we need to cry 🙄 
I reproduce the issue with PS1768, PS1778, PS1787 and PS800.
Thanks for your PR 🚀 

Thanks!

**Comment by hibatallahAouadni** [comment]
As the PR has been merged 🎉 I close the issue!
