### ISSUE TITLE
[Seo-url] New shops have wrong page titles and friendly URLs

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/PrestaShop#30620]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I'm not sure it's the bug with the shop installation or only with translations (polish in my case). The problem is every new shop needs default urls fixed every time on **Preferences (Shop Parameters) -> Traffic**.
Images below show: id - page_name - title - friendly url:

1. Brands are not translated

![obraz](https://user-images.githubusercontent.com/5007456/208659906-abc5df13-ae8f-467c-936d-6d5aa19ed9ab.png)

2. Sitemap uses title as the friendly url.

![obraz](https://user-images.githubusercontent.com/5007456/208659783-7df081b5-3696-4073-83cb-d2aeac5cd083.png)

3. Authentication has wrong title (`Nazwa użytkownika` means `User's name`)

![obraz](https://user-images.githubusercontent.com/5007456/208660553-6df92fe2-16a0-489e-b082-bc0e210aebb7.png)

4. Non-ASCII character used in url (notice url is `zamówienie` instead of `zamowienie`)

![obraz](https://user-images.githubusercontent.com/5007456/208660998-e2e9cc9c-dcaa-434e-af32-c8734617a444.png)

### Expected behavior

Should be:

1. title `Marki` and url `marki`
2. url `mapa-strony`
3. title `Logowanie`
4. url `zamowienie`

### Steps to reproduce

1. Install shop with polish language as default (I'm not sure if other languages have issues in the same places)
2. Go to Preferences (Shop Parameters) -> Traffic (in polish it's Preferencje -> Ruch)

### PrestaShop version(s) where the bug happened

1.7

### PHP version(s) where the bug happened

7, 8

**Comment by SharakPL** [comment]
@kpodemski I've just updated these on Crowdin version 1.7.8 and 8 on _Shop->Navigation.xlf_. But there's still a problem with Brands. That's what it looks like on new shops:

![obraz](https://user-images.githubusercontent.com/5007456/208679288-79c3ad5d-6aea-4200-8bd6-9c33345f6068.png)

It's the same on other languages eg. CS:

![obraz](https://user-images.githubusercontent.com/5007456/208684148-c77f8b73-185e-43dd-9d0c-80975d19c053.png)

From these phrases only meta title (`Brands list`) has a translation on Crowdin, but as you can see above it's not used anyway. `Brands` and `brands` are missing. `Manufacturer` and `manufacturer` translation are present but not used here.

**Comment by hibatallahAouadni** [comment]
Hello @SharakPL 

Indeed, even without installing a new shop, I encounter this issue while importing the Poland Pack, see the attached screenshot below: 

<img width="462" alt="Screenshot 2022-12-20 at 23 23 42" src="https://user-images.githubusercontent.com/23308427/208778395-d4d9142b-5c4e-4ed8-9d81-559f53b2ace2.png">

I'll add this issue to the backlog to be fixed and thanks for your PR 🚀 

Thanks!

**Comment by SharakPL** [comment]
As @kpodemski informed me, the issue may be elsewhere, as this file should be automatically generated and not changed like that with a PR.

**Comment by SharakPL** [comment]
Should be fixed by #28947, but probably not sooner than after PS v.8.1.0 is released and translations are updated on crowdin and not for 1.7 branch 😢

**Comment by Hlavtox** [comment]
@SharakPL Can you please recheck if it's fixed on 8.1 and close the issue?

**Comment by SharakPL** [comment]
Seems fixed
