### ISSUE TITLE
extending hookActionDispatcherBefore - notice when creating new product

### ISSUE THREAD

**Issue by ShaiMagal** [PrestaShop/PrestaShop#30623]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When extending objectmodel definition in actiondispatcher (hookActionDispatcherBefore), a notice is thrown when creating a new product.

Edit product works fine.

No other negative impact on fuction were observed.

### Steps to reproduce

1. install test module ([download small test module for this issue](https://demo17.psmoduly.cz/shaim_test.zip))
2. enable developer mode
3. try to add new product
4. E_NOTICE will shown

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

![Untitled](https://user-images.githubusercontent.com/8518736/208711540-d3791081-9352-4a69-8784-9b64b31a5c0d.png)

**Comment by Hlavtox** [comment]
@jf-viguier Would you mind please testing this and example module from friends-of-presta? We are following this example https://github.com/friends-of-presta/training/blob/master/src/Product/AlternativeDescription.php

**Comment by kpodemski** [comment]
Hello @ShaiMagal 

It's a very hacky way of extending ObjectModel, and a way that is not recommended. First of all, you modify core tables, which should not be the case, second of all, there is a number of ways to populate your fields to the front office that doesn't require overrides.

I think it's more a discussion for Slack than an issue with the core.

**Comment by ShaiMagal** [comment]
> It's a very hacky way of extending ObjectModel, and a way that is not recommended. First of all, you modify core tables, which should not be the case, second of all, there is a number of ways to populate your fields to the front office that doesn't require overrides.

Hi @kpodemski ,

this solution recommended me @Hlavtox, because we would like to stop using overrides.. (As you know, overrides aren't ideal)

I am using this hook for back office as well. I am using displayAdminProductsExtra as well for modifiing this values.

No overrides, no ActionDispatcherBefore, so ... ? **What is the correct way?**

**Comment by kpodemski** [comment]
Let's chat on Slack someday 👍🏻

**Comment by Hlavtox** [comment]
@kpodemski This should be a legitimate way of extending - https://github.com/PrestaShop/PrestaShop/pull/8853 🤷‍♂️

@mickaelandrieu Hello Mickael, please, as the original creator, would you mind looking on this issue? 🙂

**Comment by ShaiMagal** [comment]
Just an update after 2 years - if someone else will solve it and worry about it, then the only "correct" way is to use the "`actionProductUpdate`" hook to update/edit BO records and a separate table in the database and simply SELECT the values ​​everywhere where you need them (in BO for editing and in FO for display).

`hookActionDispatcherBefore` is still available in PS9 and can be solved through it, but it has been a deprecated solution for a long time.

Save your time with `hookActionDispatcherBefore` and skip this.

**Don't waste your time like I did already multiple times:-D**
