### ISSUE TITLE
Missing text on Stock Management

### ISSUE THREAD

**Issue by paulnoelcholot** [PrestaShop/PrestaShop#30630]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

A text is missing on a checkbox in Stock Management.

![image](https://user-images.githubusercontent.com/112863083/208879627-a045d2d6-b3ea-4af3-9879-e97f4089cf05.png)

### Expected behavior

The text `Display products below low stock level first` should not be missing

### Steps to reproduce

1. BO > Catalog > Stock
2. See error : The text Display products below low stock level first related to checkbox is not displayed

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4

**Comment by HanaRebaiQA** [comment]
Hello @paulnoelcholot 

Thanks for your report.

I was able to reproduce your issue with **develop** and php 7.2 but i was unable to reproduce it on PS8.0.x

**Develop : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/208914522-6410c3e4-cea3-41b6-acf1-eb5381e28574.png)

**PS8.0.x : OK** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/208914495-0317936e-0ca2-4228-b6c9-80f8a2ef3cf6.png)

Indeed it's a regression on develop!

Thank You!

**Comment by Progi1984** [comment]
Ping @NeOMakinG with the Vue Migration
