### ISSUE TITLE
My search bar didn't show any results anymore

### ISSUE THREAD

**Issue by sirine57** [PrestaShop/PrestaShop#30637]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

the matter is simple: search bar displays no results.

I tried to:

- rebuild index form BO Search panel

- Clear cache

- Truncate ps_search_index table in database (and then restored from backup as nothing changed)

I also installed an ajax search module (joli search) but it does not return any result.

Any suggestion?

thank you in advance!

### Expected behavior

nothing

### Steps to reproduce

nothing

### PrestaShop version(s) where the bug happened

1.7.5.0

### PHP version(s) where the bug happened

7.2.34

### If your bug is related to a module, specify its name and its version

ps_serachbar

**Comment by HanaRebaiQA** [comment]
Hello @sirine57 

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template and provide clear and concise steps to reproduce the bug**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank You!
