### ISSUE TITLE
Not possible to modify the Bulk edit quantity by clicking on the arrows

### ISSUE THREAD

**Issue by paulnoelcholot** [PrestaShop/PrestaShop#30634]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On Stock Management, develop, it's not possible to modify the Bulk edit quantity by clicking on the arrows. On 8.0.x,it's possible.

![image](https://user-images.githubusercontent.com/112863083/208883880-f7b8f758-4465-48dd-b7ec-6d7a1121b9c0.png)

### Expected behavior

It should be possible to modify the Bulk edit quantity by clicking on the arrows

### Steps to reproduce

1. On catalog > Stock
2. Click on the checkbox of a product
3. Click on arrows of Bulk edit quantity
4. see error

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4

**Comment by HanaRebaiQA** [comment]
Hello @paulnoelcholot 

Thanks for your report.
I was able to reproduce your issue on **develop** with php 7.2. It's OK on 8.0.x

**Develop : NOK** :x: 

https://user-images.githubusercontent.com/92912932/208926917-d842ee7b-65d2-47af-b822-ed54a4376b87.mp4


**8.0.x : OK** :heavy_check_mark: 

https://user-images.githubusercontent.com/92912932/208926924-90885d5e-5f1b-4d8b-a3ac-f7462c64e8de.mp4

**PS1788 : OK** :heavy_check_mark: 

https://user-images.githubusercontent.com/92912932/208927258-619fe173-aa6b-4c6e-aa55-af3189110c89.mp4


Indeed, it's a regression on develop!

Thank You!

**Comment by kpodemski** [comment]
@NeOMakinG, so I've checked the issue, and it seems that after using the keyboard, there's an event, and we react to it, while if you click on those arrows, there's only a `number` provided - I'm not sure if we can change behavior of `<PsNumber>` to unify events in the minor version 🤔

**Comment by NeOMakinG** [comment]
> @NeOMakinG, so I've checked the issue, and it seems that after using the keyboard, there's an event, and we react to it, while if you click on those arrows, there's only a `number` provided - I'm not sure if we can change behavior of `<PsNumber>` to unify events in the minor version 🤔

Pretty sure we are able to chance these events as it's only about types and at the same time these components are not officially usable publicly
