### ISSUE TITLE
Incorrect product name displayed on front office

### ISSUE THREAD

**Issue by arcofins** [PrestaShop/PrestaShop#30647]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I created a product with a test name (azertyu) in order to make some tests. 
I changed the name of my product in my back office. The product name is well displayed on my home, but on the product page I still have the old name (azertyu). 

I cleared my cache (computer and server) and I still got this problem.

What can I do to update the name of the product on the product page. 

(cf screenshots)

The product displayed on the homepage
<img width="1218" alt="Homepage" src="https://user-images.githubusercontent.com/65950828/209107292-b8c6d559-af14-46a3-9878-c614723c2a1e.png">

The product page with the bug 
 
<img width="1337" alt="Product page" src="https://user-images.githubusercontent.com/65950828/209107389-dd3564a3-c530-4179-a49b-0e80afc6cae6.png">

The back office product page (same page for FR/GB)

<img width="1415" alt="Back office - Product page" src="https://user-images.githubusercontent.com/65950828/209107432-1aad8c29-1c95-4400-aa53-ec61dee6878f.png">

### Expected behavior

Just display the good name on the product page.

### Steps to reproduce

Go to backoffice / catalog
try to edit the product (ID784)
Go to the product page (no change)

### PrestaShop version(s) where the bug happened

1.7.1.2

### PHP version(s) where the bug happened

7.1

**Comment by florine2623** [comment]
Hello @arcofins ,

You can check the following:
- product name has been well edited in all languages
- clear cache in browser (CTRL + shift + R)
- clear cache in server
- clear cache in BO > Advanced Parameters > Performance > Clear cache

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by arcofins** [comment]
Hi @florine2623,

As I said in my first message, I already did that... 
- I have check the product name
- I have cleared the cache in my browser, server and on the BO.

What solution can you suggest ?
