### ISSUE TITLE
GET RID OF "SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes."

### ISSUE THREAD

**Issue by BenoitAdam94** [PrestaShop/PrestaShop#30645]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

So, every time I install Prestashop, either 1.7 or 8.0 I got this goddamn error:

`SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.`

I was hoping this new Prestashop 8.0 would bypass this, or other at least some explanation of that bug, because yes, that's annoying, redundant, and not very user-friendly for anyone trying Prestashop for the first time.

I use WAMP and have to do this :

```
From Wamp Version 3.2.6
Edit this file: C:\wamp64\bin\mysql\mysql[your_version]\my.ini Change the config for innodb-default-row-format value
from innodb-default-row-format=compact
to innodb-default-row-format=dynamic
Restart mysql
```

### Expected behavior

Not the error to happen

OR

more detailed explanation/fix

### Steps to reproduce

1/ Install Prestashop 8
2/ Have a mysql ini file with  "innodb-default-row-format=compact"
3/ After choosing login/pw/Database, installation blocks at about 13% with this error

### PrestaShop version(s) where the bug happened

Prestashop 8.0

### PHP version(s) where the bug happened

8.0

**Comment by florine2623** [comment]
Hello @BenoitAdam94 ,

Please make sure the system requirements are respected:
https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/

There's a fix on this link:
https://www.prestashop.com/forums/topic/1037513-sql-error-on-query-index-column-size-too-large-the-maximum-column-size-is-767-bytes/

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by BenoitAdam** [comment]
I DON'T NEED HELP THANKS !

I want you to change that Prestashop behavior because it's NOT user-friendly.

Gosh, what's hard to understand ?


Je dois parler en Français ? Avec cette erreur mal expliquée a chaque installation en local de Prestashop, ça faire fuir les nouveaux arrivants, vous comprenez ? Ou la notion d'UX vous est étrangère ?

**Comment by kpodemski** [comment]
Hello @BenoitAdam94 

I'm afraid this change would require some drastic moves inside the DB structure, which is only to support the margin of environments used by the community. By default, the value for `innodb-default-row-format` in MySQL 5.7 is `dynamic`. Why not just change this setting as a warning suggested?
