### ISSUE TITLE
[PHP8.0] Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs)

### ISSUE THREAD

**Issue by neoacevedo** [PrestaShop/PrestaShop#30642]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Loging in with PHP8 raises the error described in the title. My guess is Prestasho 1.7.x remains to run only with PHP 7.4.

---

Running locally with PHP 8 and recently updated Prestashop, I get the error described in the title when I login in the backend. As I don't have enable the login in the frontend, I guess it would happen also. What I see once I have loged in is a blank page because it's a replica from my production store.

I updated it locally using PHP 7.4 and closed the session; I changed then the PHP version to 8.0 and I tried to login having this issue.

### Expected behavior

To login and to access the dashboard.

### Steps to reproduce

1. Update via PHP7 from 1.7.8.7 to 1.7.8.8 locally
2. Close the session once updated
3. Change the PHP version from 7.4 to 8.0
4. Access the login page 
5. Login

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

8.0

**Comment by Hlavtox** [comment]
Hi @neoacevedo, Prestashop 1.7.8 is not compatible with PHP 8.

PHP > 8 is supported since Prestashop 8.0.0, upgrade procedure will be available in the following days. Upgrade, then change the PHP version and everything should work fine.👍
