### ISSUE TITLE
dashproducts - PHP Warning: Illegal string offset 'id_category_default' in dashproducts.php : 224

### ISSUE THREAD

**Issue by crv248** [PrestaShop/PrestaShop#30659]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi I have opened 1 issue yesterday with the same name (https://github.com/PrestaShop/PrestaShop/issues/30653) but was closed with a failure in the testing by @florine2623 beacuse I specified the version of the module is 2.1.2 and the testing was in the version 2.1.1 it's working correctly. 
So, please if someone can check with the version **2.1.2** to see if it's a problem in my behaviour or it's a bug. 

-----------------------

Im checking the code and I noticed that the function "getDefaultCategory()" in product class return an string and in the module is using by this way getting a key of an array by **['id_category_default']**: 

modules/dashproducts/dashproducts.php : 224
```
$category = new Category($product_obj->getDefaultCategory()['id_category_default'], $this->context->language->id);
```
In the version 2.1.1 this line is worfink fine:
```
$category = new Category($product_obj->getDefaultCategory(), $this->context->language->id);
```

So, I think this is the problem that is noticed in the PHP warning. 

Maybe the problem it's en the function because if the SQL don't returns anything, it's returns an Array, but with the **getValue** in the **Db::getInstance()** it's returned an String:

classes/Product.php : 7810
```
public function getDefaultCategory()
    {
        $default_category = Db::getInstance()->getValue('
            SELECT product_shop.`id_category_default`
            FROM `' . _DB_PREFIX_ . 'product` p
            ' . Shop::addSqlAssociation('product', 'p') . '
            WHERE p.`id_product` = ' . (int) $this->id);

        if (!$default_category) {
            **return ['id_category_default' => Context::getContext()->shop->id_category];**
        } else {
            return $default_category;
        }
    }
```
classes/Product.php : 7805
So this function expects the return is an array: 
```
    /**
     * Get the default category according to the shop.
     *
     * @return array
     */
```
But if I make some test with this I received an string: 
![image](https://user-images.githubusercontent.com/15896239/209322501-39f0c038-708c-4b3b-98e4-b006620f38e1.png)

The return is:
![image](https://user-images.githubusercontent.com/15896239/209322559-05836b91-54f3-4a06-a0b2-5ad80bcd7c78.png)

And if in the database I put the id_category_default = NULL in the table ps_product_shop, the return is an array:
![image](https://user-images.githubusercontent.com/15896239/209322829-f208f397-ad1d-4202-af99-1fe000a2894a.png)

So maybe here it's the problem.

Thanks in adavance.

### Steps to reproduce

1 - Go to Dashboard
2 - Sales and product block
3 - Best sellers section

Also you can make some test to view the behaviour of the function Product::getDefaultCategory() creating a test.php in the root of the server and using this code: 
```
<?php
require_once __DIR__ . '/config/config.inc.php';

$p = new Product(8);

dump($p->getDefaultCategory());
```
And excuting **localhost/text.php** to see the result.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

dashproducts - v2.1.2

**Comment by sallemiines** [comment]
Hello @crv248 

Using module `Dashboard Products v2.1.2`, I can't reproduce your issue.

![Module-manager-•-1788](https://user-images.githubusercontent.com/31663369/209342035-98d8e449-632e-4b14-b471-cf591a9da7df.png)

The Best sellers section is displayed correctly : 


![Dashboard-•-1788](https://user-images.githubusercontent.com/31663369/209342040-235d39ce-b913-429d-9cde-66516056b740.png)

Thank you !

**Comment by sallemiines** [comment]
Its' also duplicate of (https://github.com/PrestaShop/PrestaShop/issues/30653)
