### ISSUE TITLE
8.0.0 Unable to upload new banner to module ps_imageslider.

### ISSUE THREAD

**Issue by RoseannePeeters** [PrestaShop/PrestaShop#30656]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Trying to upload a new banner image to the ps_imageslider but I get following error: "@getimagesize path cannot be empty"
![image](https://user-images.githubusercontent.com/119082127/209243209-7684810c-bed5-4417-bb33-57e9ed8d2bf4.png)

### Expected behavior

Image gets uploaded succesfully.

### Steps to reproduce

1. Go to Design=>Theme and logo => Pages configuration => Slider => Configure
2. Click change on any of the banners
3. Choose a new image
4. Click save

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_imageslider

**Comment by RoseannePeeters** [comment]
I have checked "$_FILES['image_' . $language['id_lang']]['tmp_name']" and it is not empty

**Comment by sallemiines** [comment]
Hello @RoseannePeeters 

Thanx for reporting the issue.

Following your steps I didn't manage to reproduce your issue , you can see the attached screen record 

[7480.webm](https://user-images.githubusercontent.com/31663369/209336447-e8d20701-9718-4387-8bab-6053880936b7.webm)


**PS** : Module `ps_imageslider` version : 3.1.1 

Did I miss  ? 

Please check and feedback !

**Comment by RoseannePeeters** [comment]
Hey @sallemiines ,

You did the correct steps, so it is a problem on my behalf.
I did update from 1.7.8 to 8.0.0, so maybe this code didn't update well?
Where can I check the version?

Thanks

**Comment by hibatallahAouadni** [comment]
Hello @RoseannePeeters 

Unfortunately, we can't help you any further cause we only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you

**Comment by RoseannePeeters** [comment]
Hey @hibatallahAouadni, you closed this but after doing some more research on the code that was erroring, I came to the conclusion that the '@' Error Control Operator doesn't disable critical errors that will terminate script execution. You can find this in [their documentation](https://www.php.net/manual/en/language.operators.errorcontrol.php) saying: 
```
Warning

Prior to PHP 8.0.0, it was possible for the @ operator to disable critical errors that will terminate script execution. For example, prepending @ to a call of a function which did not exist, by being unavailable or mistyped, would cause the script to terminate with no indication as to why.
```
I've downloaded the latest and greatest version of ps_imageslider and this still uses the @ operator which will always throw errors in PHP 8 due to the operator not working the same and the algorithm not being altered.
