### ISSUE TITLE
Regenerate thumbnails with webp selected does not replace jpg images

### ISSUE THREAD

**Issue by nitschis** [PrestaShop/PrestaShop#30663]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have updated my shop from the latest 1.7.x to 8.0.0 since the "1-click upgrade" update.

Under "Image Settings", I select webp as my "image format", when recreating the thumbnails whit "Erase previous images" enabled, the shop still only displays jpegs which should have been deleted/replaced.

### Expected behavior

All product picture jpgs should be deleted and replaced by webp images.

### Steps to reproduce

1. Add product image in PNG format.
2. Under "image settings" select webp as your "image format" and save.
3. Regenerate thumbnails with  "Erase previous images" enabled.
4. Shop images still displayed as jpg.

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.4

**Comment by jeckyl** [comment]
Hi,

The generated image keeps the JPG extension, but it is a WEBP image as for PNG which keeps the JPG extension.

The system uses this extension, because all the PrestaShop code will create simplified URLs for images with this extension and therefore it is easier to keep the JPG extension and let browsers display the image in the correct format.

**Comment by kpodemski** [comment]
Having images with additional extensions like .webp for WebP, .avif for Avif, etc., is something that a few members of the project are implementing for PrestaShop 8.1 :-) You can some information here: https://github.com/PrestaShop/PrestaShop/issues/28048

PrestaShop 8.0 behaves as described by @jeckyl

**Comment by nitschis** [comment]
Thanks for the reply, and clearing it up, I understand the problem. Make sense that I was confused.
