### ISSUE TITLE
Cache key must be string, "NULL" given

### ISSUE THREAD

**Issue by HeapReaper** [PrestaShop/PrestaShop#30668]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I use Cyberpanel's one click install. It go good by one Prestashop install. Now i want to add another Prestashop, but get error "Cache key must be string, "NULL" given". Tried reinstalling prestashop but no result. Also i tried PHP 7, 7.4 and 8.0. 
I enabled debug mode. here's the output of that:
```
Fatal error: Uncaught Symfony\Component\Cache\Exception\InvalidArgumentException: Cache key must be string, "NULL" given. in /home/testwinkel.handbuildcomputers.nl/public_html/vendor/symfony/symfony/src/Symfony/Component/Cache/CacheItem.php:161 Stack trace: #0 /home/testwinkel.handbuildcomputers.nl/public_html/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/AbstractTrait.php(235): Symfony\Component\Cache\CacheItem::validateKey() #1 /home/testwinkel.handbuildcomputers.nl/public_html/vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/AbstractAdapter.php(154): Symfony\Component\Cache\Adapter\AbstractAdapter->getId() #2 /home/testwinkel.handbuildcomputers.nl/public_html/src/Core/Localization/CLDR/DataLayer/LocaleCache.php(82): Symfony\Component\Cache\Adapter\AbstractAdapter->getItem() #3 /home/testwinkel.handbuildcomputers.nl/public_html/src/Core/Data/Layer/AbstractDataLayer.php(91): PrestaShop\PrestaShop\Core\Localization\CLDR\DataLayer\LocaleCache->doRead() #4 /home/testwinkel.handbuildcomputers.nl/public_ in /home/testwinkel.handbuildcomputers.nl/public_html/vendor/symfony/symfony/src/Symfony/Component/Cache/CacheItem.php on line 161
```

Reinstalling it on a new website in Cyberpanel doesn't work. The first Prestashop works fine still,.

### Expected behavior

That it shows no error :P

### Steps to reproduce

In cyberpanel make a new website
then click on it
On the bottom click "One click Prestashop install"
Full stuff in, wait until finished
Go to domain name.

### PrestaShop version(s) where the bug happened

1.7.8

### PHP version(s) where the bug happened

7.0, 7.4, 8.0

**Comment by hibatallahAouadni** [comment]
Hello @kelvin-codes-stuff 

Try to give full access to the cache folder cause it seems that you have an issue with cache folder.

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you
