### ISSUE TITLE
Keep a solution to customize the backoffice CSS

### ISSUE THREAD

**Issue by jeckyl** [PrestaShop/PrestaShop#30664]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

In the new-theme backoffice, it is no longer possible to customize the CSS of the theme unless you recompile the existing.

### Describe the solution you'd like

In the default theme of the backoffice, there is a file that allows this customization
`/admin/themes/default/css/overrides.css`
It would be good to propose the same solution in the new-theme.

### Alternatives you've considered

The problem with this solution is that the fact that the CSS file is present in all versions means that it will be overwritten at each update.
This problem can be solved by not including this file in the version archives or by creating an autoload directory in the CSS directory.

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @jeckyl 

Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments. 
Thanks so much for your PR 🚀 

Thank you
