### ISSUE TITLE
Product aanmaken gaat steeds naar Dasboard

### ISSUE THREAD

**Issue by E-winkel** [PrestaShop/PrestaShop#30687]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Product aanmaken gaat steeds naar Dasboard

### Expected behavior

.

### Steps to reproduce

producten
nieuw product

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

0

### If your bug is related to a module, specify its name and its version

1.7.8.7

**Comment by florine2623** [comment]
Hello,

Please write a correct issue in English.

Thanks
