### ISSUE TITLE
click upgrade v4.15 maintenance website

### ISSUE THREAD

**Issue by osdijon** [PrestaShop/PrestaShop#30680]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Since the v4.15 update of click upgrade, when I want to check for an update of prestashop, the module asks me to put me in maintenance mode when I am already in it. In addition, the module does not offer me version 8 of prestashop.
![no maintenance](https://user-images.githubusercontent.com/121489021/209652231-8c81aa75-0897-4d34-a195-4a766269c114.jpg)

### Expected behavior

Normally, the module should take into account the fact that the site is under maintenance and thus allow updates

### Steps to reproduce

1. Go to the click upgrade module
2. Click on "check if a new update is available"
3. A link appears asking to put the website in maintenance to activate the search for updates
4. put the site under maintenance
5. Go back to the module and redo the update search query.
6. Always the same maintenance request which is however active

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

4.15.0

**Comment by hibatallahAouadni** [comment]
Hello @osdijon 

Please edit your request in English. English is the norm on GitHub.
And could you please provide the expected behavior 🙏 

Thank you

**Comment by osdijon** [comment]
> Hello @osdijon
> 
> Please edit your request in English. English is the norm on GitHub. And could you please provide the expected behavior 🙏
> 
> Thank you

Done ! Sorry

**Comment by florine2623** [comment]
Hello @osdijon ,

I can't reproduce your issue on PS 1.7.8.8. I only have this issue: https://github.com/PrestaShop/PrestaShop/issues/29758

Please screen record your steps to reproduce so I can see what you are doing exactly.
Thanks!

**Comment by osdijon** [comment]
Like I want see update, all case must be green, I click like is writing in the picture:
![one](https://user-images.githubusercontent.com/121489021/209793048-b7e281bf-58a9-4b90-b8cc-702f4da2e318.jpg)
So I put my website in maintenance:
![two](https://user-images.githubusercontent.com/121489021/209793503-76c67c70-07cb-46f5-909a-da659c510264.jpg)
To finish, I go again to the module but It ask always to put in maintenance:
![three](https://user-images.githubusercontent.com/121489021/209793678-f5f2ce17-f2b3-48cf-870e-c483e58bb81e.jpg)

**Comment by florine2623** [comment]
On my end, I can't reproduce your issue.
The maintenance mode is well configured and on the module autoupgrade v4.15, the checklist is correct :
<img width="1411" alt="Screenshot 2022-12-28 at 11 15 40" src="https://user-images.githubusercontent.com/16019289/209796454-769838d8-d77b-498b-80f9-890973f78bf5.png">

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you!

**Comment by osdijon** [comment]
I have this probleme since I did update of click upgrade to v4.15
I have just to re install click upgrade v4.15 and clear cache.
Nothing change.
I am not isolated case I think because other peoples have same problems (same worse because I think me I don't have php mistakes) -> https://github.com/PrestaShop/PrestaShop/issues/30680

**Comment by MatShir** [comment]
The version 8.0 will be listed next week hopefully, in the meantime you can upgrade from the archive local. Are you trying to do a upgrade from your server or local ?

**Comment by osdijon** [comment]
> The version 8.0 will be listed next week hopefully, in the meantime you can upgrade from the archive local. Are you trying to do a upgrade from your server or local ?

I don't want do that because searching mistake, I cleared all backups before version of my website...

**Comment by osdijon** [comment]
I solved my problem. This came from my maintenance ip address that I had forgotten to indicate. Thanks everyone for helping me find it!
