### ISSUE TITLE
A PDF downloaded from the BO does not take into account the correct translations in 1.7.8.8

### ISSUE THREAD

**Issue by d33x** [PrestaShop/PrestaShop#30688]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I download a PDF (invoice for example) from the BO, the PDF retrieves the translations of the core and not of the custom theme whereas when I download the same invoice from the FO, it is the translations of the personal theme that are retrieved.

This problem has been present since my site was updated from 1.7.8.7 to 1.7.8.8. When I downgrade to 1.7.8.7 the problem disappears

**1.7.8.7 : OK**
![ok-1777](https://user-images.githubusercontent.com/76649472/209826590-62dd1ab4-9177-4755-8fc6-acd2ad0f2211.png)

**1.7.8.8 : KO**
![bug-1788](https://user-images.githubusercontent.com/76649472/209826591-89974887-784c-4289-ba3c-b5645172ce45.png)
![string-1788](https://user-images.githubusercontent.com/76649472/209826587-a42ff0f1-90b1-4b90-828a-6961d0d74baf.png)

### Expected behavior

Get the right translations, like in FO

### Steps to reproduce

1. Have a custom theme (like https://github.com/prestarocket-agence/classic-rocket)
2. Edit the PDF of this theme to add a string (like https://github.com/PrestaShop/PrestaShop/files/11049899/invoice.txt [change the .txt into .tpl]) 
3. Translate the string into a language
4. Download the PDF to the BO and see that the string is translated correctly (into 1.7.8.7)
5. Update from 1.7.8.7 to 1.7.8.8
6. Download the PDF again and see that the string is no longer translated
7. Compare the PDF between the BO and the FO

### PrestaShop version(s) where the bug happened

1.7.8.8

**Comment by florine2623** [comment]
Hello @d33x ,

Your issue is the same as and is fixed : https://github.com/PrestaShop/PrestaShop/issues/29649

So I will close it to avoid cluttering the backlog.
Thanks !

**Comment by d33x** [comment]
Hello @florine2623 

This seems to be completely unrelated... I don't understand...

**Comment by MatShir** [comment]
@florine2623 maybe it is worth to test the issue if it is really fixed ? Since the fix has been merged in the lastest autoupgrade release, we can double-check :)
@d33x What is the auto-upgrade version used for the upgrade ?

**Comment by HanaRebaiQA** [comment]
Hello @d33x 

Could you please provide us with the information about the upgrade version that you used?

Thank You!

**Comment by MatShir** [comment]
> @florine2623 maybe it is worth to test the issue if it is really fixed ? Since the fix has been merged in the lastest autoupgrade release, we can double-check :)

As I said @HanaRebaiQA, the bug might be fixed in 4.15. I think we can test it now first to be sure with the steps provided by the user.

**Comment by d33x** [comment]
When I look at #29649 it doesn't seem to be related to my problem but to a translation problem directly in the autoupgrade module. That's what seems strange to me.


The update is done automatically on our side by our host. The host informs us that he uses his application manager "Installatron":
> Updates to our web applications, except for WordPress, are done via the Installatron application manager that we use: https://installatron.com/

Now we'll see if it's related to that or if it's just a bug in PrestaShop

**Comment by HartLarsson** [comment]
> When I look at #29649 it doesn't seem to be related to my problem but to a translation problem directly in the autoupgrade module. That's what seems strange to me.
> 
> The update is done automatically on our side by our host. The host informs us that he uses his application manager "Installatron":
> 
> > Updates to our web applications, except for WordPress, are done via the Installatron application manager that we use: https://installatron.com/
> 
> Now we'll see if it's related to that or if it's just a bug in PrestaShop

Installatron is not good to upgrade any CMS. Is better to use the upgrade utilities/functions that comes with the original CMS. 
Using a 3rd part script to update Prestashop is not really good and could bring to strange behaviours.
Is always preferable to test upgrades on STAGE and not directly on PRODUCTION server.

**Comment by d33x** [comment]
@HartLarsson You are absolutely right on this point, I can only agree

@MatShir I tried on STAGE to upgrade via the autoupgrade module, and I have the same problem

**Comment by d33x** [comment]
@HanaRebaiQA @florine2623 Were you able to try to reproduce this bug?

**Comment by d33x** [comment]
After investigation, the problem seems to come from the PR #27422 of @atomiix. When I remove this PR from my website, I don't have the problem anymore...

**Comment by d33x** [comment]
@florine2623 @HanaRebaiQA Were you able to try to reproduce this bug?

**Comment by HanaRebaiQA** [comment]
Hello @d33x 

Sorry for the late answer.
ping @hibatallahAouadni Could you please try to reproduce it?

Thank You!

**Comment by d33x** [comment]
@hibatallahAouadni

**Comment by d33x** [comment]
@hibatallahAouadni Friendly reminder (because my customers receive a half French, half English invoice in their parcel...)

**Comment by d33x** [comment]
@hibatallahAouadni Friendly reminder (because my customers receive a half French, half English invoice in their parcel...)

**Comment by hibatallahAouadni** [comment]
Hello @d33x 

I didn't manage to reproduce the issue with CLASSIC theme, it seems related to your custom theme.
So, please contact your theme developer to check the issue 🙏 
Closing the issue as it's not Core bug.

Thanks!

**Comment by d33x** [comment]
Hello @hibatallahAouadni 

The first step to reproduce is to have a different theme (no matter which one). You have to create a child theme or whatever the theme is because the PR #27422 of @atomiix  takes into account the fact that the translation of the core can come before the translation of the theme.

So that's the problem (it's logical that with the classic theme it works)

**Comment by d33x** [comment]
@hibatallahAouadni Can you test with the right steps? I even pointed out the PR that was a problem...

**Comment by d33x** [comment]
3 months that the ticket is open and waiting to be reproduced. I know the development team has a lot of work to do and it's complicated to fix all the problems but here we are not even in the pipeline yet as the problem has still not been reproduced...

I have provided all the necessary steps... is it possible to reproduce it? It's also regression between 1.7.8.7 and 1.7.8.8

@florine2623 @HanaRebaiQA @hibatallahAouadni Thanks!

**Comment by djoelleuch** [comment]
Hello @d33x 

Could you please provide a custom theme to help me reproduce the issue :pray: 
Waiting for your feedback.

Thanks!

**Comment by d33x** [comment]
Hello @djoelleuch

https://github.com/prestarocket-agence/classic-rocket for example

**Comment by AureRita** [comment]
Hi @d33x 

Thank you for your details and your theme , I tried to reproduce your issue as you can see : 

[Untitled_ Mar 13, 2023 10_53 AM.webm](https://user-images.githubusercontent.com/100699445/224746819-e5adee5a-0e97-4156-9fe0-cd70386a6c9b.webm)

I didn't reproduce it, did I miss something about it ? 

Waiting for your feedback

**Comment by d33x** [comment]
Hi @AureRita 

We are not talking about email here but about theme and PDF modification. Here is the complete step: 

1. Have a custom theme
2. Edit the PDF of this theme to add a string (for example: add {l s='Thank you' d='Shop.Pdf' pdf='true'} within invoice.tpl in /themes/custom-theme/pdf)
3. Translate the string into a language (French for example)
4. Download the PDF to the BO and see that the string is translated correctly (into 1.7.8.7)
5. Update from 1.7.8.7 to 1.7.8.8
6. Download the PDF again and see that the string is no longer translated
7. Compare the PDF between the BO and the FO

If you can't find it, I'll provide you with an example file and a video

**Comment by d33x** [comment]
@AureRita ?

**Comment by AureRita** [comment]
Hi @d33x 

Thank you for this details, currently I can't find the invoice.tpl even with your example custom theme ( classic rocket ). That would be very nice if you share us an example file and a video 

Waiting for your feedback

**Comment by d33x** [comment]
Hi @AureRita 

Indeed, there is no pdf folder and invoice.tpl file in this theme. The pdf folder must be added when you want to customise the pdf (with "override"), it doesn't matter what the theme is (it doesn't really matter in reality). So you have to create the pdf folder and the invoice.tpl file yourself.

Attached you will find an example of an invoice.tpl file (I can't attach a tpl file, so I attached a txt) and a video.
[invoice.txt](https://github.com/PrestaShop/PrestaShop/files/11049899/invoice.txt)
![bug-pdf-prestashop](https://user-images.githubusercontent.com/76649472/227208201-a8db7f9a-b1c1-49f9-9f76-f175141bf41a.gif)

**Comment by Jonteep** [comment]
This is also happening from version 8.0.1 to 8.0.2, although I am using the classic theme and there are no PDF-folders in the file structure or similar.

**Comment by AureRita** [comment]
Hi @d33x ,

Thank you for all this details and the different files,I reproduce the issue with PrestaShop version 1.7.8.8 as you can see : 

[Untitled_ Mar 31, 2023 4_04 PM.webm](https://user-images.githubusercontent.com/100699445/229150955-cde37387-eb98-475b-a2df-ea0600eee45c.webm)

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks

**Comment by RosaBenouamer** [comment]
@AureRita is it related to
https://github.com/PrestaShop/PrestaShop/issues/31863

**Comment by fire2** [comment]
Experiencing the same issue in 1.7.8.9

**Comment by MatShir** [comment]
Some fixes have been done to the 8.0.5 and 8.1.1. Could any try again ? 🙏 See if the bugs are still present migrating to thoses versions
ref: https://github.com/PrestaShop/PrestaShop/issues/31863

**Comment by d33x** [comment]
@MatShir We are currently unable to migrate to 8.X.X for various reasons. Are there any plans to include these fixes in a version 1.7.8.X?

**Comment by MatShir** [comment]
You could cherry-pick the fix, probably. The versions PS 1.7.8.x are only for critical bug and security issues, sadly :/
If you test with test env, you could make sure that the upgrade will fix the issue before upgrading the prod

**Comment by Jonteep** [comment]
8.0.5 fixed this issue, as well as 8.1.1. :) @MatShir

**Comment by MatShir** [comment]
Thanks for the update. I'm closing this issue then. If anything comes up, I will reopen :)
