### ISSUE TITLE
BackOffice not translated for hungarian language

### ISSUE THREAD

**Issue by KoreLewi** [PrestaShop/PrestaShop#30686]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have installed PrestaShop 1.7.8.8 in Hungarian language, and everything is hungarian except the BackOffice menu. I have not tested with another language, as I have installed only the hungarian language.
In older versions, this worked perfectly.

### Expected behavior

The menu should be in Hungarian.

### Steps to reproduce

Install PrestaShop 1.7.8.8 in hungarian as main language

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @KoreLewi ,

I can't reproduce your issue on my shop 1.7.8.8 using PHP 7.4.
<img width="1437" alt="Screenshot 2022-12-28 at 09 33 34" src="https://user-images.githubusercontent.com/16019289/209784514-512d2961-8e57-4cc9-9a6d-1cdd885cbe7d.png">


Please update your language in International > Translations:
<img width="1434" alt="Screenshot 2022-12-28 at 09 43 31" src="https://user-images.githubusercontent.com/16019289/209784436-d142ff93-1758-4976-afd1-1ec92646d8a2.png">
