### ISSUE TITLE
Can't upgrade to 1.7.8.8 from 1.7.8.7 with 1-Click Upgrade v4.15.0

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#30690]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I got these errors at the end of the upgrade:

```
[SKIP] directory "/app/cache/" does not exist and cannot be emptied.
[CLEANING CACHE] File dev removed
[CLEANING CACHE] File prod removed
Migrating old setting file...
parameters file already exists!
Finished...
[INTERNAL] /var/www/MYDIRECTORY/modules/autoupgrade/vendor/composer/ClassLoader.php line 444 - include(/var/www/MYDIRECTORY/vendor/composer/../doctrine/event-manager/lib/Doctrine/Common/EventManager.php): failed to open stream: No such file or directory
[INTERNAL] /var/www/MYDIRECTORY/modules/autoupgrade/vendor/composer/ClassLoader.php line 444 - include(): Failed opening '/var/www/MYDIRECTORY/vendor/composer/../doctrine/event-manager/lib/Doctrine/Common/EventManager.php' for inclusion (include_path='/var/www/MYDIRECTORY/vendor/pear/pear_exception:/var/www/MYDIRECTORY/vendor/pear/console_getopt:/var/www/MYDIRECTORY/vendor/pear/pear-core-minimal/src:/var/www/MYDIRECTORY/vendor/pear/archive_tar:.:/usr/share/php')
[INTERNAL] /var/www/MYDIRECTORY/modules/autoupgrade/vendor/composer/ClassLoader.php line 444 - include(/var/www/MYDIRECTORY/vendor/composer/../doctrine/event-manager/lib/Doctrine/Common/EventSubscriber.php): failed to open stream: No such file or directory
[INTERNAL] /var/www/MYDIRECTORY/modules/autoupgrade/vendor/composer/ClassLoader.php line 444 - include(): Failed opening '/var/www/MYDIRECTORY/vendor/composer/../doctrine/event-manager/lib/Doctrine/Common/EventSubscriber.php' for inclusion (include_path='/var/www/MYDIRECTORY/vendor/pear/pear_exception:/var/www/MYDIRECTORY/vendor/pear/console_getopt:/var/www/MYDIRECTORY/vendor/pear/pear-core-minimal/src:/var/www/MYDIRECTORY/vendor/pear/archive_tar:.:/usr/share/php')
[INTERNAL] /var/www/MYDIRECTORY/modules/autoupgrade/vendor/composer/ClassLoader.php line 444 - include(/var/www/MYDIRECTORY/vendor/composer/../doctrine/event-manager/lib/Doctrine/Common/EventManager.php): failed to open stream: No such file or directory
[INTERNAL] /var/www/MYDIRECTORY/modules/autoupgrade/vendor/composer/ClassLoader.php line 444 - include(): Failed opening '/var/www/MYDIRECTORY/vendor/composer/../doctrine/event-manager/lib/Doctrine/Common/EventManager.php' for inclusion (include_path='/var/www/MYDIRECTORY/vendor/pear/pear_exception:/var/www/MYDIRECTORY/vendor/pear/console_getopt:/var/www/MYDIRECTORY/vendor/pear/pear-core-minimal/src:/var/www/MYDIRECTORY/vendor/pear/archive_tar:.:/usr/share/php')
```

`[INTERNAL] /var/www/MYDIRECTORY/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php line 23 - Error: Class 'Doctrine\Common\EventManager' not found #0 /var/www/MYDIRECTORY/modules/autoupgrade/vendor/composer/ClassLoader.php(444): include() #1 /var/www/MYDIRECTORY/modules/autoupgrade/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile() #2 [internal function]: Composer\Autoload\ClassLoader->loadClass() #3 /var/www/MYDIRECTORY/var/cache/prod/ContainerFnfubs4/appProdProjectContainer.php(2935): spl_autoload_call() #4 /var/www/MYDIRECTORY/var/cache/prod/ContainerFnfubs4/appProdProjectContainer.php(2969): ContainerFnfubs4\appProdProjectContainer->getDoctrine_Dbal_DefaultConnectionService() #5 /var/www/MYDIRECTORY/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(306): ContainerFnfubs4\appProdProjectContainer->getDoctrine_Orm_DefaultEntityManagerService() #6 /var/www/MYDIRECTORY/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ManagerRegistry.php(63): Symfony\Component\DependencyInjection\Container->get() #7 /var/www/MYDIRECTORY/vendor/doctrine/persistence/lib/Doctrine/Persistence/AbstractManagerRegistry.php(204): Symfony\Bridge\Doctrine\ManagerRegistry->getService() #8 /var/www/MYDIRECTORY/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/CacheWarmer/ProxyCacheWarmer.php(53): Doctrine\Persistence\AbstractManagerRegistry->getManagers() #9 /var/www/MYDIRECTORY/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/CacheWarmer/CacheWarmerAggregate.php(52): Symfony\Bridge\Doctrine\CacheWarmer\ProxyCacheWarmer->warmUp() #10 /var/www/MYDIRECTORY/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(686): Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() #11 /var/www/MYDIRECTORY/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() #12 /var/www/MYDIRECTORY/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(76): Symfony\Component\HttpKernel\Kernel->boot() #13 /var/www/MYDIRECTORY/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(56): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #14 /var/www/MYDIRECTORY/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(87): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() #15 /var/www/MYDIRECTORY/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(42): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #16 /var/www/MYDIRECTORY/fnm/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #17 {main}`

I also end up with these information at the information page:

```
Missing files (7)
vendor/composer/installers/phpstan.neon.dist
vendor/composer/installers/src/Composer/Installers/MiaoxingInstaller.php
vendor/composer/installers/src/Composer/Installers/WinterInstaller.php
vendor/composer/installers/src/Composer/Installers/TastyIgniterInstaller.php
vendor/composer/installers/src/Composer/Installers/ProcessWireInstaller.php
vendor/composer/installers/src/Composer/Installers/StarbugInstaller.php
vendor/composer/installers/src/Composer/Installers/PantheonInstaller.php
Updated files (10)
vendor/composer/installers/src/Composer/Installers/TaoInstaller.php
vendor/composer/installers/src/Composer/Installers/SyDESInstaller.php
vendor/composer/installers/src/Composer/Installers/MauticInstaller.php
vendor/composer/installers/src/Composer/Installers/Installer.php
vendor/composer/installers/src/Composer/Installers/MoodleInstaller.php
vendor/composer/installers/src/Composer/Installers/OxidInstaller.php
vendor/composer/installers/src/Composer/Installers/BaseInstaller.php
vendor/composer/installers/src/Composer/Installers/CakePHPInstaller.php
vendor/composer/installers/src/Composer/Installers/CockpitInstaller.php
vendor/composer/installers/src/Composer/Installers/OctoberInstaller.php

```
So I just rolled back.

### Expected behavior

Upgrade should go with no errors.

### Steps to reproduce

Upgrade from 1.7.8.7 to 1.7.8.8 via 1-Click Upgrade v4.15.0

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.3

**Comment by HanaRebaiQA** [comment]
Hello @seederp2p 

Thanks for your report. 
The 1-Click upgrade v4.15.0 is compatible only to a 8.0

ping @PrestaShop/product-team to confirm this

**Comment by seederp2p** [comment]
> Hello @seederp2p
> 
> Thanks for your report. The 1-Click upgrade v4.15.0 is compatible only to a 8.0
> 
> ping @PrestaShop/product-team to confirm this

If that's true what should I do to upgrade to 1.7.8.8?

**Comment by seederp2p** [comment]
FYI on my lab, with 1 click version 4.14.2 I got this:

`[INTERNAL] /var/www/MYDIRECTORY/vendor/doctrine/inflector/lib/Doctrine/Common/Inflector/Inflector.php line 70 - Error: Class 'Doctrine\Inflector\InflectorFactory' not found #0 /var/www/MYDIRECTORY/vendor/doctrine/inflector/lib/Doctrine/Common/Inflector/Inflector.php(58): Doctrine\Common\Inflector\Inflector::createFactory() #1 /var/www/MYDIRECTORY/vendor/doctrine/inflector/lib/Doctrine/Common/Inflector/Inflector.php(92): Doctrine\Common\Inflector\Inflector::getInstance() #2 /var/www/MYDIRECTORY/vendor/doctrine/doctrine-cache-bundle/DependencyInjection/CacheProviderLoader.php(117): Doctrine\Common\Inflector\Inflector::classify() #3 /var/www/MYDIRECTORY/vendor/doctrine/doctrine-cache-bundle/DependencyInjection/CacheProviderLoader.php(102): Doctrine\Bundle\DoctrineCacheBundle\DependencyInjection\CacheProviderLoader->getDefinitionClass() #4 /var/www/MYDIRECTORY/vendor/doctrine/doctrine-cache-bundle/DependencyInjection/CacheProviderLoader.php(38): Doctrine\Bundle\DoctrineCacheBundle\DependencyInjection\CacheProviderLoader->definitionClassExists() #5 /var/www/MYDIRECTORY/vendor/doctrine/doctrine-cache-bundle/DependencyInjection/SymfonyBridgeAdapter.php(130): Doctrine\Bundle\DoctrineCacheBundle\DependencyInjection\CacheProviderLoader->loadCacheProvider() #6 /var/www/MYDIRECTORY/vendor/doctrine/doctrine-bundle/DependencyInjection/DoctrineExtension.php(785): Doctrine\Bundle\DoctrineCacheBundle\DependencyInjection\SymfonyBridgeAdapter->loadCacheDriver() #7 /var/www/MYDIRECTORY/vendor/doctrine/doctrine-bundle/DependencyInjection/DoctrineExtension.php(796): Doctrine\Bundle\DoctrineBundle\DependencyInjection\DoctrineExtension->loadCacheDriver() #8 /var/www/MYDIRECTORY/vendor/doctrine/doctrine-bundle/DependencyInjection/DoctrineExtension.php(429): Doctrine\Bundle\DoctrineBundle\DependencyInjection\DoctrineExtension->loadOrmCacheDrivers() #9 /var/www/MYDIRECTORY/vendor/doctrine/doctrine-bundle/DependencyInjection/DoctrineExtension.php(392): Doctrine\Bundle\DoctrineBundle\DependencyInjection\DoctrineExtension->loadOrmEntityManager() #10 /var/www/MYDIRECTORY/vendor/doctrine/doctrine-bundle/DependencyInjection/DoctrineExtension.php(77): Doctrine\Bundle\DoctrineBundle\DependencyInjection\DoctrineExtension->ormLoad() #11 /var/www/MYDIRECTORY/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php(71): Doctrine\Bundle\DoctrineBundle\DependencyInjection\DoctrineExtension->load() #12 /var/www/MYDIRECTORY/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process() #13 /var/www/MYDIRECTORY/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(140): Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process() #14 /var/www/MYDIRECTORY/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(789): Symfony\Component\DependencyInjection\Compiler\Compiler->compile() #15 /var/www/MYDIRECTORY/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(643): Symfony\Component\DependencyInjection\ContainerBuilder->compile() #16 /var/www/MYDIRECTORY/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() #17 /var/www/MYDIRECTORY/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(76): Symfony\Component\HttpKernel\Kernel->boot() #18 /var/www/MYDIRECTORY/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(56): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #19 /var/www/MYDIRECTORY/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(86): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() #20 /var/www/MYDIRECTORY/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #21 /var/www/MYDIRECTORY/MYADMIN/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #22 {main}`

**Comment by MatShir** [comment]
Hi @seederp2p & @HanaRebaiQA,
Version 4.15 works for all version from 1.7.x to 8.0.0

**Comment by MatShir** [comment]
@HanaRebaiQA Could you try to reproduce the issue ?

**Comment by seederp2p** [comment]
If you're going to try to reproduce, here are the versions used:

MySQL: 8.0.31-0ubuntu0.20.04.2
PHP: 7.4.3

**Comment by MatShir** [comment]
Please try in the meantime, to clear the cache and make sure that all the repositories has the permission. And see if the upgrade works in local

**Comment by seederp2p** [comment]
> Please try in the meantime, to clear the cache and make sure that all the repositories has the permission. And see if the upgrade works in local

I did that before opening this report.

**Comment by MatShir** [comment]
Okay thanks

**Comment by seederp2p** [comment]
@HanaRebaiQA did you get any chance to reproduce the error?

**Comment by Kerami82** [comment]
Hi. After update from 1.7.8.7 to 1.7.8.8 i have the same information:
`Missing files (7)
vendor/composer/installers/phpstan.neon.dist
vendor/composer/installers/src/Composer/Installers/MiaoxingInstaller.php
vendor/composer/installers/src/Composer/Installers/WinterInstaller.php
vendor/composer/installers/src/Composer/Installers/TastyIgniterInstaller.php
vendor/composer/installers/src/Composer/Installers/ProcessWireInstaller.php
vendor/composer/installers/src/Composer/Installers/StarbugInstaller.php
vendor/composer/installers/src/Composer/Installers/PantheonInstaller.php`

`Updated files (10)
vendor/composer/installers/src/Composer/Installers/TaoInstaller.php
vendor/composer/installers/src/Composer/Installers/SyDESInstaller.php
vendor/composer/installers/src/Composer/Installers/MauticInstaller.php
vendor/composer/installers/src/Composer/Installers/Installer.php
vendor/composer/installers/src/Composer/Installers/MoodleInstaller.php
vendor/composer/installers/src/Composer/Installers/OxidInstaller.php
vendor/composer/installers/src/Composer/Installers/BaseInstaller.php
vendor/composer/installers/src/Composer/Installers/CakePHPInstaller.php
vendor/composer/installers/src/Composer/Installers/CockpitInstaller.php
vendor/composer/installers/src/Composer/Installers/OctoberInstaller.php`

but I copy this files manually and information gone.

**Comment by joecoolio66** [comment]
I can confirm these messages after upgrade to 1.7.8.8 from 1.7.8.7 as well.. but everything is working fine.  Is this even an issue?  I don't think these files were in 1.7.8.7 either... I don't see them in my 1.7.8.7 backup folder.... so what is going on here?

**Comment by florine2623** [comment]
Hello all,

I did an upgrade from 1.7.8.7 to 1.7.8.8 with autoupgrade v4.15.0 and PHP 7.3.
It was successful.
<img width="1220" alt="Screenshot 2023-01-18 at 10 54 25" src="https://user-images.githubusercontent.com/16019289/213207861-2a207c76-ffdc-42b1-b4f5-186c1765b876.png">

I could log into my newly upgraded shop and access my FO and BO correctly.

I will close your issue to avoid backlog, as I couldn't reproduce it.

Thanks!

**Comment by seederp2p** [comment]
@florine2623 thanks for your time testing.

As you can see there are more people complaining about this. Prestashop has many "moving parts" so I don't really think that only testing with a brand new shop is the correct approach (it's at maximum the initial troubleshooting process).

Anyway, we are used to this policy and I won't waste my time if this is the policy here on Prestashop github.

Thank you once again.
