### ISSUE TITLE
BackOffice Char encoding issue

### ISSUE THREAD

**Issue by plagiewski** [PrestaShop/PrestaShop#30697]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

 I've been installed Prestashop 8.0.0 with Polish language.

MySQL Database has set charset/Collation to UTF8/UTF8_bin.
Table ps_category_lang has set charset/Collation to utf8mb4/utf8mb4_0900_ai_ci.
Charset/Collation has been set automatically.
 
 In Back Office are issues with char encoding. 
 
 The biggest issue seems to be on warehouse list.
 For XHR Request:

-  /admin/index.php/api/categories/?_token=xxx
- /admin/index.php/api/stocks/?_token=xxx&order=product_id+desc&page_size=30&page_index=1

I got this what below on screenshot.
![obraz](https://user-images.githubusercontent.com/25157247/209970159-eb2ee34a-36a4-493d-af47-808ae2393d94.png)

Issue occurs in many places in back office, but not everywhere.

For example, on categories list error occurs, but when we go to change category in the form is everything ok.
![obraz](https://user-images.githubusercontent.com/25157247/209971024-70e09d72-cbcd-4cd8-834d-b0493a6456f7.png)
![obraz](https://user-images.githubusercontent.com/25157247/209971082-18e0a286-ce49-4eda-b03b-4053cb78f8fc.png)

### Steps to reproduce

1. Go to back office -> Catalog -> Warehouse
2. Check requests with error code 500.

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1

**Comment by HanaRebaiQA** [comment]
Hello @plagiewski 

Thanks for your report.
Is this issue #28857 similar to yours?

**Comment by plagiewski** [comment]
> Hello @plagiewski
> 
> Thanks for your report. Is this issue #28857 similar to yours?

No, this is something different. I have correctly defined charsets for tables, most of them is utf8mb4, rest is utf8, but not this tables generate this issue.

For example table ps_category_lang is defined as utf8mb4, but on categories list is issue with  displaying special chars in polish. When we go to change name of category, there name is displayed correctly. Same in front office - category name is displayed correctly.

On Warehouse list problem is with categories names and product attributes values names in polish (JSON has problem with encode), but in BackOffice on Attributes values list, names are displayed correctly.
![obraz](https://user-images.githubusercontent.com/25157247/210047566-88930acc-17dd-410d-bad4-a98840c10bac.png)
![obraz](https://user-images.githubusercontent.com/25157247/210047678-62d245ba-9c74-48ef-834a-fee0fa1ec8ee.png)

For more details about mysql server:
MySQL Server: 5.7.37-40 (Percona Server(GPL), Release '40')

**Comment by kpodemski** [comment]
There's a mismatch somewhere between your database settings and your server default charset settings. This is a common example of it. It's not a problem of the software.

**Comment by plagiewski** [comment]
I will check it but, on same server I have prestahsop 1.6 and problem not occurs. 
Diffrence is only between php version. Prestashop 1.6 is on PHP 7.1

If what you say is true, I think it should be visible everywhere in shop because this are global settings. But now problem occurs just in some parts of back office.

**Comment by kpodemski** [comment]
This problem affects Doctrine-related parts of the software. I'm sure you can get it resolved by tweaking db server configuration 👍🏻

PHP has nothing to do with it 👍🏻

I'll close the ticket. If you need more help you can join our Slack channel :) There's also dev-polish channel :) 


[Slack](https://www.prestashop-project.org/slack/).

**Comment by plagiewski** [comment]
I do not want to change MySQL configuration for this, so I found simple solution.

in app/config/doctrine.yml
I had changed line with options where I added `; SET NAMES 'UTF8'` like on screenshot below
![obraz](https://user-images.githubusercontent.com/25157247/210090864-7c1b9015-4d28-4922-83f0-6b4e3f9d87c5.png)

**Comment by kratekk** [comment]
so, for me your solution didnt work for Prestashop 8.1 and I changed this to 
`'1002: "SET sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY','')), names utf8mb4"'`
whitch is working as expect
