### ISSUE TITLE
Presta will not instal

### ISSUE THREAD

**Issue by Allthejam** [PrestaShop/PrestaShop#30699]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

No matter how many times I try all I get is this:

Warning: set_time_limit(): Cannot set max execution time limit due to system policy in /customers/a/2/1/elitegrantown.co.uk/httpd.www/index.php on line 26 Warning: Cannot modify header information - headers already sent by (output started at /customers/a/2/1/elitegrantown.co.uk/httpd.www/index.php:26) in /customers/a/2/1/elitegrantown.co.uk/httpd.www/index.php on line 39

I have been using Presta for years and my server was upgraded to PHP 8 so I had no choice to reload it after I could NOT get logged into the back office in Prest 7, so I deleted it all and now I can't load anything and have lost my site and all my data inc database, How can I instal Prest 8 ?

Thank you in advance..

### Expected behavior

Warning: set_time_limit(): Cannot set max execution time limit due to system policy in /customers/a/2/1/elitegrantown.co.uk/httpd.www/index.php on line 26 Warning: Cannot modify header information - headers already sent by (output started at /customers/a/2/1/elitegrantown.co.uk/httpd.www/index.php:26) in /customers/a/2/1/elitegrantown.co.uk/httpd.www/index.php on line 39

### Steps to reproduce

There are no steps I can't even instal it.

### PrestaShop version(s) where the bug happened

8

### PHP version(s) where the bug happened

8.0

### If your bug is related to a module, specify its name and its version

n/a

**Comment by matks** [comment]
@Allthejam PrestaShop is attempting to use set_time_limit() but it seems a server setting prevents it to do it. You should contact your hosting provider to see if he can disable this policy.

**Comment by hibatallahAouadni** [comment]
Hello @Allthejam 

Thanks @matks for your quick reply 🚀 
As @matks mentioned above, you need to check your server setting. 

Unfortunately, we only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you
