### ISSUE TITLE
1-click upgrade from version 1.7.2.4 -> 1.7.6.0 fail and prestashop not running

### ISSUE THREAD

**Issue by mirecta** [PrestaShop/PrestaShop#30696]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

1-click upgrade made backup of datbase and files , then upgrade files but upgrade database failed after a while time, 
and in error log was 
`[INTERNAL] /www/doc/www.woodarty.com/www/override/classes/Currency.php line 294 - Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "Repository" from namespace "PrestaShop\PrestaShop\Core\Cldr". Did you forget a "use" statement for e.g. "PrestaShop\PrestaShop\Core\Localization\Locale\Repository" or "PrestaShop\PrestaShop\Core\Localization\Currency\Repository"? #0 /www/doc/www.woodarty.com/www/override/classes/Currency.php(264): CurrencyCore::addCldrDatasToCurrency(Array, true) #1 /www/doc/www.woodarty.com/www/modules/autoupgrade/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php(47): CurrencyCore::getCurrencies(true, false) #2 [internal function]: ps_1760_copy_data_from_currency_to_currency_lang() #3 /www/doc/www.woodarty.com/www/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(382): call_user_func_array('ps_1760_copy_da...', Array) #4 /www/doc/www.woodarty.com/www/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(346): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->runPhpQuery('1.7.6.0', '/* PHP:ps_1760_...') #5 /www/doc/www.woodarty.com/www/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(270): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->runQuery('1.7.6.0', '/* PHP:ps_1760_...') #6 /www/doc/www.woodarty.com/www/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(61): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->upgradeDb('1.7.2.4') #7 /www/doc/www.woodarty.com/www/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(103): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->upgradeDb('1.7.2.4') #8 /www/doc/www.woodarty.com/www/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(42): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #9 /www/doc/www.woodarty.com/www/admin571brgzyy/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #10 {main} `

from this moment prestashop show only blank page and after i do request , this will appear in error log 
`[28-Dec-2022 15:47:33 Europe/Prague] PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "Repository" from namespace "PrestaShop\PrestaShop\Core\Cldr".
Did you forget a "use" statement for e.g. "PrestaShop\PrestaShop\Core\Localization\Locale\Repository" or "PrestaShop\PrestaShop\Core\Localization\Currency\Repository"? in /www/doc/www.woodarty.com/www/override/classes/Tools.php:615
Stack trace:
#0 /www/doc/www.woodarty.com/www/override/classes/Currency.php(100): ToolsCore::getCldr(Object(Context))
#1 /www/doc/www.woodarty.com/www/classes/controller/AdminController.php(2962): CurrencyCore->__construct('2')
#2 /www/doc/www.woodarty.com/www/classes/controller/AdminController.php(545): AdminControllerCore->initShopContext()
#3 /www/doc/www.woodarty.com/www/src/Adapter/LegacyContext.php(86): AdminControllerCore->__construct()
#4 /www/doc/www.woodarty.com/www/src/PrestaShopBundle/EventListener/UserLocaleListener.php(39): PrestaShop\PrestaShop\Adapter\LegacyContext->getContext()
#5 /www/doc/www.woodarty.com/www/var in /www/doc/www.woodarty.com/www/override/classes/Tools.php on line 615
`
yes i deleted cache .... i use php 7.3

### Steps to reproduce

1. install version 1.7.2.4 and run 1-click upgrade ....

### PrestaShop version(s) where the bug happened

1.7.6.0

### PHP version(s) where the bug happened

7.3

**Comment by mirecta** [comment]
![image](https://user-images.githubusercontent.com/1140680/209946711-ab8fc076-3968-428c-8f32-69184210cc41.png)

**Comment by HanaRebaiQA** [comment]
Hello @mirecta 

Thanks for your report.
Could you please specify which 1-click upgrade version you used?

**Comment by mirecta** [comment]
eshop nor admin doesnt work now so how can i obtain version ?

**Comment by kpodemski** [comment]
The best would be to revert your files to the previous version, remove overrides and then update again.

The problem is clearly because of the overrides you have in your store.

**Comment by mirecta** [comment]
so what i must to do ? i have only ftp access i cant run scripts from console so how can i revert it ?

**Comment by kpodemski** [comment]
It's absolutely necessary to do a manual backup before any upgrade. If you didn't do it, maybe your hosting provider can rollback files for you.

Remember that any upgrade attempt is a complicated process and if you are not technical person, it's better to hire a specialist.

**Comment by mirecta** [comment]
i was succesfully rollback using hosting provider web and i was manually rolback database using dump so whats next steps , web running and admin running but i need newest version

**Comment by mirecta** [comment]
so my one click upgrade module was v3.0.3  so i upgrade it, now version is v4.15.0

**Comment by hibatallahAouadni** [comment]
Hello @mirecta 

First, you need to downgrade your PHP version to 7.1 cause PS1.7.2.4 is not compatible with PHP 7.3.
Then, try to upgrade your shop 1.7.2.4 to 1.7.6.0 with 1-Click upgrade module with the latest version 4.15.0.
Finally, check if you still encounter the same issue.
Waiting for your feedback.

Thanks and happy new year 🎉

**Comment by mirecta** [comment]
if fail with error again 
`[INTERNAL] /www/doc/www.woodarty.com/www/modules/blockreassurance/vendor/autoload.php line 7 - Error: Class 'ComposerAutoloaderInitc338ba4ef990b179cdbe132eb1a82002' not found #0 /www/doc/www.woodarty.com/www/app/AppKernel.php(181): include_once() #1 /www/doc/www.woodarty.com/www/app/AppKernel.php(78): AppKernel->enableComposerAutoloaderOnModules(Array) #2 /www/doc/www.woodarty.com/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(493): AppKernel->registerBundles() #3 /www/doc/www.woodarty.com/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(132): Symfony\Component\HttpKernel\Kernel->initializeBundles() #4 /www/doc/www.woodarty.com/www/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(76): Symfony\Component\HttpKernel\Kernel->boot() #5 /www/doc/www.woodarty.com/www/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(56): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #6 /www/doc/www.woodarty.com/www/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(87): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() #7 /www/doc/www.woodarty.com/www/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(42): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #8 /www/doc/www.woodarty.com/www/admin571brgzyy/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #9 {main}`

**Comment by hibatallahAouadni** [comment]
Hello @mirecta 

Could you please provide a screenshot of the auto-upgrade module's configure page 🙏 
It seems related to some configuration. 
Waiting for your feedback.

Thanks!

**Comment by mirecta** [comment]
![image](https://user-images.githubusercontent.com/1140680/210384626-d1acd07b-e81c-4cf3-a58a-5f2081562d0f.png)
![image](https://user-images.githubusercontent.com/1140680/210384741-b7a0eede-0d0d-4f68-ae52-f4da2c62efc0.png)
![image](https://user-images.githubusercontent.com/1140680/210384845-269767eb-3f42-4682-85ea-4bd680128e7d.png)

**Comment by AureRita** [comment]
Hi @mirecta 

As I can see, it's a little bit strange that you can be on php 7.3 with a prestashop v 1.7.2.4. You can see the php compatibility with two these image  : 

![image](https://user-images.githubusercontent.com/100699445/210390701-9c8f6f49-f56e-42b9-8fa1-277750a35ea9.png)

![image](https://user-images.githubusercontent.com/100699445/210390804-66cbcbc3-1e8b-46b3-a865-8545f89fb66b.png)

Moreover, I see that your 1 - click upgrade is setup to do an upgrade from 1.7.2.4 to v 8.0.0 (and not with the version 1.7.6.0). These two version can't support the same php version. 

Can you give us the version of php said in BO> Advanced Parameters > Information 
Can you try to do the autoupdate from your version to this one : https://github.com/PrestaShop/PrestaShop/releases/download/1.7.6.0/prestashop_1.7.6.0.zip
And contact us if it still doesn't works 

Waiting for your feedback

**Comment by hibatallahAouadni** [comment]
Hello @mirecta 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
