### ISSUE TITLE
On customizable product with optionnal customization, when customization are saved without value an error is displayed

### ISSUE THREAD

**Issue by nfacciolo** [PrestaShop/PrestaShop#30698]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

We create a product with customizations:

    Type: text
    Lable: "basictext"
    mandatory: no

When we register customization with one blank value an error is thrown

### Steps to reproduce

1. Create a product with at least 2 customization:

      Type: text
      Lable: basicText
      product price = 0

2. Go to FO > Product page > Save customization  with at least one blank customization value
See error

![image](https://user-images.githubusercontent.com/10351721/209987229-5a7bc933-4912-44b7-a481-33ae098bcfd3.png)

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

1.7.4

**Comment by nfacciolo** [comment]
This issue is fixed on the version 8 of prestashop 

https://github.com/PrestaShop/PrestaShop/issues/30464

**Comment by hibatallahAouadni** [comment]
Duplicate of #30464
