### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by ginodev** [PrestaShop/PrestaShop#30709]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### You need at most PHP 7.4 to install PrestaShop. Your current PHP version is 8.0.26

PHP 8.x is not supported, why?

### Steps to reproduce

1.Wampserver

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

8.0.31

**Comment by matks** [comment]
Good evening @ginodev 

Prestashop 8.0.0 supports PHP7.2 to PHP7.4 _and_ PHP 8.0 and PHP 8.1 https://github.com/PrestaShop/PrestaShop/releases/tag/8.0.0
PrestaShop 1.7.8.8 supports PHP 7.2 to 7.4 https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.8.8

https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/

Choose the version you want 😉
