### ISSUE TITLE
control panel look wird after update 

### ISSUE THREAD

**Issue by Hounsgaard** [PrestaShop/PrestaShop#30700]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I update fra 1.7.8.7 to 1.7.8.8 and now the panel to the left and in the top are wird. But only on the mainpage... 
If I clik on one of the boxses the controlpanel is almost okay again 

![Skærmbillede 2022-12-30 100355](https://user-images.githubusercontent.com/42837655/210053197-3b7d475b-075d-4e4b-a8e3-c129edf82151.png)
![Skærmbillede 2022-12-30 100416](https://user-images.githubusercontent.com/42837655/210053202-412e32a8-667e-42df-86a7-40a68b4104a3.png)

### Expected behavior

I don´t think that it makes problems fore my shop, but it could be nice to see the meny on the control panel 

### Steps to reproduce

1) Open shop main page 

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4.33

**Comment by kpodemski** [comment]
Hello @Hounsgaard 

I think that all you have to do is clear your browser's cache. Make sure to do that. You can also check in incognito mode.

**Comment by hibatallahAouadni** [comment]
Hello @Hounsgaard 

As @kpodemski mentioned above, you need to clear your browser's cache.
Thanks @kpodemski for your quick reply 🚀 
Closing the issue as there's no issue related to the Core 😉 

Thanks!

**Comment by Hounsgaard** [comment]
> Hello @Hounsgaard
> 
> I think that all you have to do is clear your browser's cache. Make sure to do that. You can also check in incognito mode.

Thanks @kpodemski I have pressed F5 1 million times and tried three different  browser without any luck :-/ 
But now when I goes in to Chrome and clear the cache it helps :-)
