### ISSUE TITLE
Stripe & Prestashop issue

### ISSUE THREAD

**Issue by GreenballParis** [PrestaShop/PrestaShop#30707]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Erreur avec le module Stripe! Cela ne fonctionne pas et Stripe nous indique que le problème vient de chez vous. A chaque fois qu'on installe ou configure le module, des clés APIS se mettent toute seule dans le module et on arrive pas à les changer par les notre, cela ne s'enregistre pas et ne fonctionne pas.

1/ La configuration du Webhook n'est pas accessible, cliquez sur le bouton Enregistrer pour résoudre le problème. Un nouveau webhook sera créé sur Stripe.
=> cela recommence à l'infini, appuyer sur le bouton ne change rien.

2/ No such webhook endpoint: 'we_xxxxxxxxxxxxxxxxx'
=> on ne comprend pas ce que cela veut dire.

### Steps to reproduce

Stripe official module 2.5.0

### PrestaShop version(s) where the bug happened

1.7.6.5

**Comment by kpodemski** [comment]
Hello @GreenballParis 

On GitHub, we use English. Your question is related to the Stripe module, which is not part of the core. It would be better if you contact Stripe module authors using the contact form on the Addons Marketplace.

**Comment by GreenballParis** [comment]
Hello,

Thanks, that's prestashop assistance chat who told me to write you.... my
shop can't receive payment because of this issue and I loose many many
money.. that's going to kill me.
I can't wait days to fix that i need a solution now please...

Regards,

**Comment by matks** [comment]
As mentioned by @kpodemski any problem related to a Stripe module must be discussed with the team in charge of the module.

> I can't wait days to fix that i need a solution now please...

I would advise to hire a skilled developer to fix this https://www.prestashop-project.org/support/
