### ISSUE TITLE
The translation does not work for Child Theme

### ISSUE THREAD

**Issue by hrostyk** [PrestaShop/PrestaShop#30716]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I make Child Theme from Classic Theme and upload it back. Set Child Theme as current. Next I want to make a translation in this Child Theme. The translation page is not loading.

### Expected behavior

Load with the possibility of translation or give an error.

### Steps to reproduce

1. Go to BO
2. Theme & Logo
3. Advanced Customization
4. Download theme child_classic.zip
5. Upload child theme child_classic.zip
6. Theme & Logo
7. Child theme of classic's theme - Use this theme
8. International -> Translations
9. Modify translations
10. Modify

<img width="1162" alt="CleanShot 2023-01-02 at 11 37 44@2x" src="https://user-images.githubusercontent.com/7484618/210215117-0a74efef-b87a-4c4c-97df-866d5f03e42d.png">

### PrestaShop version(s) where the bug happened

1.7.8.8 and 8.0.0

### PHP version(s) where the bug happened

7.4.33

**Comment by AureRita** [comment]
Hi @hrostyk 

Thank for your report, this issue seems to be the same as this one : 
https://github.com/PrestaShop/PrestaShop/issues/15268

is it the same as yours in your opinion ? 

Waiting for your feedback

**Comment by hrostyk** [comment]
Looks like it's the same problem.
I did some research. The problem appears when there are no .tpl files with phrases in the child theme folder.

<img width="1448" alt="CleanShot 2023-01-03 at 21 33 17@2x" src="https://user-images.githubusercontent.com/7484618/210428267-8cf0296d-4d82-49bd-ae7b-019ecf6aea82.png">

Here are some solutions:
1. Show error... please, create .tpl files with phrases in your child theme folder.
2. Generate one or more .tpl files in the .zip when download theme.
3. Show all translations for parent theme. (I's logical, because I can change the translation for child theme without changing the .tpl files).

**Comment by HartLarsson** [comment]
I would add also some informations:

if you translate a base theme phrase and you have a child activated the translation not appear.
To make it appearing you need to go to the table:

1. go to ps_translation table
2. search the translation record you want to fix
3. edit in the "theme" column the theme name changing to the child theme name
4. save

now translation appear correctly

In my case i use warehouse:

![image](https://user-images.githubusercontent.com/16102074/210738475-f6fb028c-8e41-4e34-a61e-744125457a83.png)


on point 3 you can delete any name for theme column choose NULL and works anyway

I've not found any other fix, if someone have a Script fix to apply is welcome :)

**Comment by sallemiines** [comment]
duplicate of [#15268](https://github.com/PrestaShop/PrestaShop/issues/15268)

**Comment by mnick73** [comment]
I have the same problem as @HartLarsson after updating to prestashop 1.7.8.8.
In the child theme part of the translations have disappeared. only in the child theme.
It can only be solved by editing the ps_translation table in the theme column.
I think it's a bug because the only updated table in the update process to prestashop 1.7.8.8 is ps_translation.

![image](https://user-images.githubusercontent.com/79770168/218847659-7c98cfce-f598-4676-9cfb-bc5ac2d0144f.png)



I am using php 7.4.33

Please check.

**Comment by venditdevs** [comment]
@florine2623 closed one of my created issues of this problem as a non reproducable bug caused by the theme itself, not in Prestashop. Clearly now it is not a bug in the childtheme but again a bug in Prestashop. Just like the autoupgradebug with the php session error which was closed as not reproducable.

**Comment by Seb33300** [comment]
@HanaRebaiQA this is not a duplicate of https://github.com/PrestaShop/PrestaShop/issues/15268

This regression has been introduced in 1.7.8.8
It was working properly on 1.7.8.7

https://github.com/PrestaShop/PrestaShop/issues/15268 is related to 1.7.6.1

**Comment by Seb33300** [comment]
Seems related to the changes made by @atomiix in https://github.com/PrestaShop/PrestaShop/pull/27422

**Comment by HanaRebaiQA** [comment]
Hello @Seb33300 

Sorry, but it wasn't me who treated the issue.
So, I'll ping again @PrestaShop/qa-team What do you think?

**Comment by Seb33300** [comment]
Oups, sorry I wanted to tag @sallemiines

**Comment by paulnoelcholot** [comment]
Hello @hrostyk,

I reproduce the issue with PrestaShop version 1.7.8.8, 8.0.0 and develop, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by ThomasDrd** [comment]
> Seems related to the changes made by @atomiix in #27422

Doesn't the problem come from the modification in the file src/PrestaShopBundle/Translation/Loader/SqlTranslationLoader.php
?
The previous operation was to retrieve the translations from the core and then add the translations from the child theme. With the code modification, we only get the translations saved for the child theme and we no longer get the translations from the core.

**Comment by mariuszsienkiewicz** [comment]
Yep, it looks like the change you're referring to caused the entire problem. To be honest, I'm not sure why that change was even made. Reverting it should resolve this issue. 

That new `and` in `where` clause in the previous query:

```php
$selectTranslationsQuery = '
    SELECT `key`, `translation`, `domain`
    FROM `' . _DB_PREFIX_ . 'translation`
    WHERE `id_lang` = ' . $localeResults[$locale]['id_lang'];
    AND theme ' . ($this->theme !== null ? '= "' . $this->theme->getName() . '"' : 'IS NULL');
```

doesn't replace this piece of code:

```php
if (null !== $this->theme) {
    $selectThemeTranslationsQuery =
    $selectTranslationsQuery . "\n" .
    "AND theme = '" . $this->theme->getName() . "'";
    $themeTranslations = Db::getInstance()->executeS($selectThemeTranslationsQuery) ?: [];
    $this->addTranslationsToCatalogue($themeTranslations, $catalogue);
}
```

Perhaps the author attempted to simplify the loading process by having one query per function call, but the result of these two approaches is entirely different and causes this problem.

Edit: I'm referencing this commit: de446f282455ecc985ce041d53904526510d09f8

**Comment by matks** [comment]
Fixed by @kpodemski https://github.com/PrestaShop/PrestaShop/pull/33133
