### ISSUE TITLE
non-visible product after loading from management system

### ISSUE THREAD

**Issue by xdario89x** [PrestaShop/PrestaShop#30732]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

hi when I load the product from my management system (danea) on prestashop, the products are active and have quantities greater than 1, but initially I don't see them on the front end of the site, if I go to the product and make a small change and save it, the product after is visible on the site

### Steps to reproduce

send product in prestashop
the product is not visibile in frontend

### PrestaShop version(s) where the bug happened

1.7.8.7

**Comment by Hlavtox** [comment]
Hi @xdario89x, you have something wrong in your import process, I suggest hiring a specialist to fix your code. 👍
