### ISSUE TITLE
Google sitemap doesn't generate the map.

### ISSUE THREAD

**Issue by Defabri01** [PrestaShop/PrestaShop#30747]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I try to configure the module and click on generate sitemap it goes on error

![2023-01-05 18_19_44-Window](https://user-images.githubusercontent.com/59261037/210843212-16cfa763-c644-4828-ad6f-e74c3a47baca.png)

![2023-01-05 18_20_56-Window](https://user-images.githubusercontent.com/59261037/210843227-f5a620b3-2cf6-4726-9738-5a0adf0d0d13.png)

### Expected behavior

It should generate the Sitemap

### Steps to reproduce

1. Go to modules management 
![2023-01-05 18_38_37-Window](https://user-images.githubusercontent.com/59261037/210844966-e1f6d349-8800-4d46-b5ec-cabe5aba2392.png)

2. Clik on configure 
![2023-01-05 18_39_15-Window](https://user-images.githubusercontent.com/59261037/210845080-f46e77a5-a92d-40c4-8c6f-f466f9718e68.png)

4. Open up the page 
![2023-01-05 18_36_03-](https://user-images.githubusercontent.com/59261037/210844531-f8c3b8df-d42c-4cc3-96ad-b686b53fd268.png)

5. Clik on generate sitemap 
![2023-01-05 18_36_55-Window](https://user-images.githubusercontent.com/59261037/210844661-f77bb947-4fcc-4377-81eb-9e1df3504418.png)

6. Gives the error 
![2023-01-05 18_37_49-Window](https://user-images.githubusercontent.com/59261037/210844818-2468633b-9ece-4b49-9076-69be88a99d99.png)

### PrestaShop version(s) where the bug happened

1.7.8.7

### If your bug is related to a module, specify its name and its version

Google Sitemap v4.2.0

**Comment by Hlavtox** [comment]
Hi @Defabri01, you need to contact the author of smartblog to properly implement `gSitemapAppendUrls` hook.

If you can live without blog URLS in sitemap for some time, go to module positions page and unhook smartblog from `gSitemapAppendUrls` hook. 👍

**Comment by Defabri01** [comment]
Hi Daniel,

thank for your help, but it did not work, I'm going to contact the author
of my theme that include the smartblog


Il giorno gio 5 gen 2023 alle ore 18:43 Daniel Hlavacek <
***@***.***> ha scritto:
