### ISSUE TITLE
 4-digit price for a product pack

### ISSUE THREAD

**Issue by Alsacer** [PrestaShop/PrestaShop#30744]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I create a pack, the total amount of the unit products of the pack is displayed under the selling price of the pack, in the form of a sentence " instead of %price% " but this price is only displayed if the amount pack total is a 3-digit number, if the total pack amount.
If the amount is a 4-digit number, the block is no longer displayed.
![2023-01-05_15h55_30](https://user-images.githubusercontent.com/13730511/210809574-61be83ca-0f90-4fbd-8762-d1db2058780a.jpg)
![2023-01-05_15h55_57](https://user-images.githubusercontent.com/13730511/210809583-8d7d5df2-88d2-4fd2-8576-2940ec8da2f2.jpg)

### Steps to reproduce

Create a product pack and add products to it for an amount greater than 999

### PrestaShop version(s) where the bug happened

1.7.6.8

**Comment by sallemiines** [comment]
Hello @Alsacer 

Please send your request in English. English is the norm on GitHub.

Thank you

**Comment by Alsacer** [comment]
Sorry, I was too fast.
I edited the first post. Thank you

**Comment by florine2623** [comment]
The issue has been fixed in 1.7.8.0 : https://github.com/PrestaShop/PrestaShop/issues/21828

You can upgrade your shop to benefit from the fix !

**Comment by Alsacer** [comment]
Thank you very much @florine2623
