### ISSUE TITLE
Webservice 8.0.0

### ISSUE THREAD

**Issue by Nikos22350** [PrestaShop/PrestaShop#30740]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi !!!

Using the Prestashop webservice, we performed tests on version 8.0.0 and we encountered a problem when creating combinations.

We have the following PHP error message : 
`    <code>3</code>
    <message>
    [PHP Warning #2] Trying to access array offset on value of type null (/var/www/vhosts/acdl.bzh/presta8.acdl.bzh/classes/webservice/WebserviceOutputBuilder.php, line 669)
    </message>`

We encounter this problem on the categories, combinations, customers and customer_threads APIs.

In addition, for my product to go up on the site (even if it does not create the combinations), we must uncheck the boxes in the "PATCH" part of the webservice.

Is the version 8 webservice really stable ?

Thanking you in advance for your return.

### Steps to reproduce

Sending an article with variations via the webservice

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.0

**Comment by sallemiines** [comment]
Hello @Nikos22350 
Thanks for the issue ! 

could you please provide the file/code/api that you use to create the product with combination by WS ? 

Thank you !

**Comment by matks** [comment]
Looks very similar to https://github.com/PrestaShop/PrestaShop/issues/26568

**Comment by Nikos22350** [comment]
Hi !

I solved my problem by reverting to PHP version 7.4.33

You can close my issue.

Thank's

**Comment by cun** [comment]
I've got the same issue. Followed your instruction of downgrading, but it still indeed happens on PHP 7.4.33-3+ubuntu20.04.1+deb.sury.org+1 
I can't seem to get it to sync. 

`[Sat Jan 21 00:17:00.767557 2023] [php7:notice] [pid 3771625] [client xxxxx:xxxx] [PHP Notice #8] Trying to access array offset on value of type null (/xxxxxxxxxxxxxxxxxxxxxxxx/classes/webservice/WebserviceOutputBuilder.php, line 669)
`

Any help would be massively apprecaited. Thanks.
