### ISSUE TITLE
Product V2 : Combinations are not deleted when removing product from shop

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#30751]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When using feature "select shops" in product page v2 and unselecting product from certain shop, the combonations of product are not deleted.

### Expected behavior

When shop is unselected for product and product has combinations, then all the combinations should be deleted for that product and that shop.

### Steps to reproduce

1. Enable multistore and create at least 2 shops (lets say shop1 and shop2)
2. Go to product page v2 edit a combinational product and generate combinations in both shops.
3. Go to database (whatever tool you are using to access the database) product_attribute_shop table and see that combinations exists for that product and are associated for both shops. (id_product_attribute and id_shop fields)
4. In top right corner use feature "select shops" and unselect shop "shop2"
5. Go to database again and see that combinations are still there for both shops (❌ ). The correct behavior - they should not be there for shop2 anymore (✅ )

### PrestaShop version(s) where the bug happened

develop

**Comment by florine2623** [comment]
Hello @zuk3975 ,

I reproduced the issue with PrestaShop on branch develop, I'll add this to the backlog so it can be fixed.

My combination product is only available on shop2:
<img width="1188" alt="Screenshot 2023-01-06 at 14 19 54" src="https://user-images.githubusercontent.com/16019289/211020610-2a5167e2-e175-428f-b254-fbcae78b03f5.png">

In database, the combination are still saved for both shops:
<img width="1196" alt="Screenshot 2023-01-06 at 14 20 15" src="https://user-images.githubusercontent.com/16019289/211020628-7151fa1a-cea6-4f5b-b474-3e4ee076041b.png">


Thank you

**Comment by zuk3975** [comment]
fixed by https://github.com/PrestaShop/PrestaShop/pull/30727
