### ISSUE TITLE
Duplicate tabs on module install

### ISSUE THREAD

**Issue by Seb33300** [PrestaShop/PrestaShop#30759]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Since PrestaShop 8.0, when installing a module that use the [`$tabs` property](https://devdocs.prestashop-project.org/8/modules/concepts/controllers/admin-controllers/tabs/#how-to-define-a-tab-in-the-menu), the first menu item is duplicated.

The same `$tabs` config is working as expected on PrestaShop 1.7

Here is the `$tabs` property I defined:

```php
protected $tabs = [
    [
        'class_name' => 'WaQuestionnaire',
        'parent_class_name' => 'SELL',
        'route_name' => 'webarea_module_questionnaire_admin_questionnaire_index',
        'name' => 'Questionnaires',
        'icon' => 'live_help',
    ],
    [
        'class_name' => QuestionnaireController::LEGACY_CONTROLLER,
        'parent_class_name' => 'WaQuestionnaire',
        'route_name' => 'webarea_module_questionnaire_admin_questionnaire_index',
        'name' => 'Questionnaires',
    ],
    [
        'class_name' => SubmissionController::LEGACY_CONTROLLER,
        'parent_class_name' => 'WaQuestionnaire',
        'route_name' => 'webarea_module_questionnaire_admin_submission_index',
        'name' => 'Submissions',
    ],
];
```

On PS 8.0, result after module install:

![image](https://user-images.githubusercontent.com/915273/211149858-4e2865f9-995e-4319-add8-2a157b417166.png)

In `ps_tab`, I can see an extra entry with `_MTR` suffix created:

![image](https://user-images.githubusercontent.com/915273/211150016-00b9de73-8a36-419f-9281-665bdc1097f1.png)

### Expected behavior

The same result as we have on PrestaShop 1.7

![image](https://user-images.githubusercontent.com/915273/211149772-bfaeb1a1-a464-4387-839b-41e254960e9c.png)

![image](https://user-images.githubusercontent.com/915273/211150056-726725e6-10e2-4cfb-adf5-408ed39a5389.png)

### Steps to reproduce

1. create a module with tabs
2. install module
3. see the duplicated entry in the menu

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by Seb33300** [comment]
Also, it looks like `wording` and `wording_domain` are not working on PrestaShop 8.0.0

https://devdocs.prestashop-project.org/8/modules/concepts/controllers/admin-controllers/tabs/#since-prestashop-178

**Comment by hibatallahAouadni** [comment]
Hello @Seb33300 

Could you please provide a module to help me reproduce the issue :pray: 
Waiting for your feedback.

Thanks!
