### ISSUE TITLE
Autoupgrade doesn't detect latest version: 8.0.1

### ISSUE THREAD

**Issue by sharkooon** [PrestaShop/PrestaShop#30753]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Installed prestashop 8.0.0 fresh 3 days ago.
8.0.1 is released today, so time to upgrade.

Autoupgrade module shows this:
<img width="561" alt="Scherm_afbeelding 2023-01-06 om 11 27 00" src="https://user-images.githubusercontent.com/533123/211005806-a92d1faa-d57f-4aa3-a2b6-afc2b07bfbc5.png">

Found the issue in upgrade module..
It is comparing versions 8 (from branch https://api.prestashop.com/xml/channel.xml) to version 8.0 (from installed version)
```
<branch name="8" available="1">
<name>8.0 stable</name>
<num>8.0.1</num>
<download>
<link>https://github.com/PrestaShop/PrestaShop/releases/download/8.0.1/prestashop_8.0.1.zip</link>
<md5>2b7fe5b9213c6fc0a3942058e8d93c68</md5>
</download>
<changelog>https://build.prestashop-project.org/news/2023/prestashop-8-0-1-maintenance-release/</changelog>
</branch>
</channel>
```

```
version_compare('8', '8.0', '>=')
output is: false

```
Changing the installed version to: 8
```
version_compare('8', '8', '>=')
output is: true

```
Version is set at
/modules/autoupgrade/classes/UpgradeContainer.php:301
Version is compared at:
/modules/autoupgrade/classes/Upgrader.php:195

If the branch name="8" on (https://api.prestashop.com/xml/channel.xml) is changed from 8 to 8.0 it will work.

### Expected behavior

Get the latest version 8.0.1

### Steps to reproduce

See above

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1.13

### If your bug is related to a module, specify its name and its version

1-Click Upgrade v4.15.0

**Comment by florine2623** [comment]
Hello @sharkooon ,

I reproduced the issue with PrestaShop version 8.0.0, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by florine2623** [comment]
@kpodemski @nicosomb @matthieu-rolland 
What do you think about that ?

**Comment by sharkooon** [comment]
I think this is very important because nobody can upgrade to the latest version unless this is fixed.

**Comment by matks** [comment]
Strange, the channel file is correct https://api.prestashop.com/xml/channel.xml

**Comment by sharkooon** [comment]
Channel file needs to be:
`branch name="8.0"`
instead of 
`branch name="8"`

At least i think :) Otherwise version_compare wont work

**Comment by nicosomb** [comment]
We just made a quick fix on https://api.prestashop.com/xml/channel.xml (you have to wait for cache). 

We'll fix the autoupgrade module in few days.

**Comment by sharkooon** [comment]
php version_compare() works like that, so i think the channel.xml fix is the best solution.

**Comment by matks** [comment]
https://api.prestashop.com/xml/channel.xml is up to date @sharkooon can you tell us if it's OK?

**Comment by kpodemski** [comment]
It looks good on my side:
![image](https://user-images.githubusercontent.com/2137763/211065194-a0e6d2de-2f45-4072-b2d6-389add3e4aa7.png)

Feel free to close the ticket @sharkooon if you confirm it's ok on your side too.

**Comment by hibatallahAouadni** [comment]
Hello @kpodemski 

I can still reproduce the problem, see the attached screen record below:

[issue_30753.webm](https://user-images.githubusercontent.com/23308427/211067696-7916b50a-9199-4ed0-89f2-56d1aca3c81a.webm)

Thanks!

**Comment by kpodemski** [comment]
@hibatallahAouadni 

and here:
https://api.prestashop.com/xml/channel.xml

you see `branch name="8"` or `branch name="8.0"`?

**Comment by hibatallahAouadni** [comment]
I see: 
```
<branch name="8.0" available="1">
<name>8.0 stable</name>
<num>8.0.1</num>
<download>
<link>https://github.com/PrestaShop/PrestaShop/releases/download/8.0.1/prestashop_8.0.1.zip</link>
<md5>2b7fe5b9213c6fc0a3942058e8d93c68</md5>
</download>
<changelog>https://build.prestashop-project.org/news/2023/prestashop-8-0-1-maintenance-release/</changelog>
</branch>
```

**Comment by sharkooon** [comment]
> Hello @kpodemski
> 
> I can still reproduce the problem, see the attached screen record below:
> 
>  issue_30753.webm 
> Thanks!

You could delete /config/xml/channel.xml and try again?

**Comment by sharkooon** [comment]
> It looks good on my side: ![image](https://user-images.githubusercontent.com/2137763/211065194-a0e6d2de-2f45-4072-b2d6-389add3e4aa7.png)
> 
> Feel free to close the ticket @sharkooon if you confirm it's ok on your side too.

From my side it is working correctly!

**Comment by nicosomb** [comment]
So we can close this issue. I will open a new one on autoupgrade side on monday.
