### ISSUE TITLE
modulo commenti prodotto

### ISSUE THREAD

**Issue by lomaistro** [PrestaShop/PrestaShop#30758]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

salve, configurando il modulo commenti prodotto sul sito mi fa recensire dopo aver confermato mi dice recensione aggiunta ma ricaricando la pagina la recensione non c'è! ho provato varie volte ma nulla! e poi stranamente mi esce tutto in inglese sia recensioni che quando clicco il modulo per scrivere  la recensione  è tutto in inglese

### Expected behavior

che mi facesse inserire realmente le  recensioni sui prodotti e che fosse in italiano

### Steps to reproduce

vado sul sito clicco review e mi fa lasciare la recensione ma non me la pubblica davvero

### PrestaShop version(s) where the bug happened

1.7.7.8

**Comment by hibatallahAouadni** [comment]
Hello @lomaistro 

Please send your request in English. English is the norm on GitHub.
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must provide clear and concise steps to reproduce  to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
