### ISSUE TITLE
Failed to update 1.7.8.8 to 8.0.1

### ISSUE THREAD

**Issue by Stephane1874** [PrestaShop/PrestaShop#30761]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

I tried to update my version 1.7.8.8 to 8.0.1 with the 1-Click Upgrade module version 4.15.0 by choosing the major version option.

On my first try, I got this error:

`[INTERNAL] /htdocs/vendor/composer/autoload_real.php line 59 - require(): Failed opening required '/htdocs/vendor/composer/../react/promise/src/functions_include.php' (include_path='/htdocs/vendor/pear/pear_exception:/htdocs/vendor/pear/console_getopt:/htdocs/vendor/pear/pear-core-minimal/src:/htdocs/vendor/pear/archive_tar:.:/usr/share/php')`

![Capture](https://user-images.githubusercontent.com/46202635/211161481-da083e3a-dd26-41e1-8b41-d3d7062f43c0.JPG)

So I added manually on a version 8.0.1 available on my desktop the folder (react), I compressed the archive and deposited in the folder /admin/autoupgrade/download/, I tried again to update update from the 1-Click Upgrade module by choosing the local archive option.

I got this error:

`[INTERNAL] /htdocs/vendor/composer/autoload_real.php line 59 - require(): Failed opening required '/htdocs/vendor/composer/../markbaker/complex/classes/src/functions/abs.php' (include_path='/htdocs/vendor/pear/pear_exception:/htdocs/vendor/pear/console_getopt:/htdocs/vendor/pear/pear-core-minimal/src:/htdocs/vendor/pear/archive_tar:.:/usr/share/php')`

![add-dossier-react](https://user-images.githubusercontent.com/46202635/211161732-7b0abffa-b280-4913-8f50-66c9a808df0f.JPG)

Same manipulation by adding the missing folder.

I got this error:

`[INTERNAL] /htdocs/vendor/composer/autoload_real.php line 59 - require(): Failed opening required '/htdocs/vendor/composer/../markbaker/matrix/classes/src/Functions/adjoint.php' (include_path='/htdocs/vendor/pear/pear_exception:/htdocs/vendor/pear/console_getopt:/htdocs/vendor/pear/pear-core-minimal/src:/htdocs/vendor/pear/archive_tar:.:/usr/share/php')`

I added the missing folder and finally managed to complete the process with this error :

![adde](https://user-images.githubusercontent.com/46202635/211162125-d330e3e8-cc65-4930-a8a3-255bb23d0577.JPG)

The BO seemed to work correctly, but the FO was in error 500.

I didn't keep looking for the solution for the 500 error, I reinstalled my BDD backups and files before I went crazy :)

Maybe it is not possible to do this update yet 1.7.8.8 to 8.0.1?

### Steps to reproduce

Update 1.7.8.8 to 8.0.1

### PrestaShop version(s) where the bug happened

1.7.8.8 to 8.0.1

### PHP version(s) where the bug happened

7.4

**Comment by Hlavtox** [comment]
Hi @Stephane1874, I have experienced errors like this before, when capital letter changed in some of the packages. There is a simmilar issue here - https://github.com/PrestaShop/PrestaShop/issues/15187.

I just tested upgrade from 1.7.8.8 to 8.0.1 and everything went fine, so I think you intially installed Prestashop on some older version and this is an upgraded install right?

Could you please ZIP your vendor folder of 1.7.8.8 and send it to me somehow? I will compare it to 1.7.8.8 clean.

_______

Regarding the error in FO after upgrade, it will be some minor module issue. If you enable debug mode in BO or you change `_PS_MODE_DEV_` to true in `config/defines.inc.php`, you will see what is causing it. 👍

**Comment by Stephane1874** [comment]
Hi @Hlavtox, thank you for the answer.

Yes, it's an old version 1.7.5 or 1.7.6 I can't remember. I followed the updates every time.

My vendor.zip file by following this link
http://www.hebergeurfichier.com/download/924e531b9e249dd3aed906c9583977d5.html

**Comment by Hlavtox** [comment]
Your vendor folder is correct, that's not the problem. I suggest disabling every non-native module and trying again. Let me know. 👍

**Comment by deepindersingh83** [comment]
Same Issue 

We faced we installed the 1.7.8.4 and updated with the patches and updates till 1.7.8.8

but when updated it to 8.0.1 we got the same error

_Quote removed by @Hlavtox_

**Comment by Stephane1874** [comment]
Hello @Hlavtox,

I did some tests with non-native modules disabled and the default theme. I get the same result with different errors depending on the scenario.

`[INTERNAL] /htdocs/vendor/composer/autoload_real.php line 59 - require(): Failed opening required '/htdocs/vendor/composer/../react/promise/src/functions_include.php' (include_path='/htdocs/vendor/pear/pear_exception:/htdocs/vendor/pear/console_getopt:/htdocs/vendor/pear/pear-core-minimal/src:/htdocs/vendor/pear/archive_tar:.:/usr/share/php')`

I also got this error

`[INTERNAL] /htdocs/src/Adapter/Module/Repository/ModuleRepository.php line 41 - Error: Class 'PrestaShop\PrestaShop\Adapter\AbstractObjectModelRepository' not found #0 /htdocs/modules/autoupgrade/vendor/composer/ClassLoader.php(444): include() #1 /htdocs/modules/autoupgrade/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/htdocs/vendor/...') #2 [internal function]: Composer\Autoload\ClassLoader->loadClass('PrestaShop\\Pres...') #3 /htdocs/app/AppKernel.php(215): spl_autoload_call('PrestaShop\\Pres...') #4 /htdocs/app/AppKernel.php(68): AppKernel->getActiveModules() #5 /htdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(446): AppKernel->registerBundles() #6 /htdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(133): Symfony\Component\HttpKernel\Kernel->initializeBundles() #7 /htdocs/app/AppKernel.php(84): Symfony\Component\HttpKernel\Kernel->boot() #8 /htdocs/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(76): AppKernel->boot() #9 /htdocs/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader80.php(44): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #10 /htdocs/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(87): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader80->initConstants() #11 /htdocs/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(42): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #12 /htdocs/admin???/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #13 {main}`


I will see this update for later, for now 1.7.8.8 works well, thank you.

**Comment by Hlavtox** [comment]
@atomiix @kpodemski We need some investigation guys. 😄

**Comment by dreanmer** [comment]
I'm facing the same problem... First upgraded from 1.7.8.7 direct to 8.0.1, as I got these errors I made the manual upgrade to 1.7.8.8 them upgraded to 8.0.1 (with 1 click) also had the same errors... so I managed to fix it by copying the `/react/promise/src/functions_include.php` from another module (maybe from ps_accounts, I don't remember, but there is many modules that have this) but... after this I found more problems:

- can't run database upgrade manually (lot of errors on dependencies trying to load from wrong dir);
- perhaps the store opens, the admin side wont, there is error with an PrestaShopBundle trying to load   `@prestashop.core.circuit_breaker.guzzle.cache_subscriber` on `news.php` but it cant be found, and gives error;

I also managed to fix it removing this subscriber (idk what can be the consequences...) the admin login page loads, but dont login (only refreshes... maybe this is an consequence lol)

I also tried to upgrade manually, some things that helped with some errors was: 
- deleting `var/cache/prod` and `var/cache/dev`
- disabling all non native modules
but had the same problems as above...

I'm giving up... as I can't change to another system on this project, I'll freeze it to 1.7.8.8 and make changes to the core by myself.

**Comment by sebastian-marinescu** [comment]
I'm trying for the last hours to upgrade to PS8.
I am encountering the exact same problems like @dreanmer. 

Because 1clickupgrade always had connection timeouts, I did the manual upgrade, like described in the docs, and also from 1.7.8.8. After that _nothing_ worked. I started debugging and fixed the php-errors inside my override-classes.
I also updated many modules. But now I encountered this error:

`PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "prestashop.adapter.news.circuit_breaker.settings" has a dependency on a non-existent service "prestashop.core.circuit_breaker.guzzle.cache_subscriber". in /ps_shop/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:86`

The blog posts to this release sounded promising, but the experience while upgrading is not. 

I will have to revert and freeze too, until these issues are resolved.

**Comment by Imunal** [comment]
> I'm trying for the last hours to upgrade to PS8.
> 
> I am encountering the exact same problems like @dreanmer. 
> 
> 
> 
> Because 1clickupgrade always had connection timeouts, I did the manual upgrade, like described in the docs, and also from 1.7.8.8. After that _nothing_ worked. I started debugging and fixed the php-errors inside my override-classes.
> 
> I also updated many modules. But now I encountered this error:
> 
> 
> 
> `PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "prestashop.adapter.news.circuit_breaker.settings" has a dependency on a non-existent service "prestashop.core.circuit_breaker.guzzle.cache_subscriber". in /ps_shop/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:86`
> 
> 
> 
> The blog posts to this release sounded promising, but the experience while upgrading is not. 
> 
> 
> 
> I will have to revert and freeze too, until these issues are resolved.

Facing the same issue, any update on that?

**Comment by dreanmer** [comment]
Nope... I made some tryouts but I gave up. I didn't have much time to spend on it, and seems no one cares about :/

**Comment by AureRita** [comment]
Friendly reminder @PrestaShop/prestashop-core-developers

**Comment by mateuszdraco** [comment]
I faced the same issue, what I did was to remove old `src/PrestaShopBundle` and to copy the new version, so there are no old files in this directory anymore.

**Comment by pixelpusher** [comment]
this is also completely broken for me, the steps above didn't help. I followed the upgrade instructions on https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/upgrade/ and they simply don't work, also the link to the update.php doesn't work (should that be relative to the admin folder)? These instructions are very sparse, they were not very helpful unfortunately.

**Comment by kpodemski** [comment]
Improved documentation for the `autoupgrade` module is now in the works. You can see refreshed upgrade guide here https://github.com/PrestaShop/docs/pull/1611

**Comment by HanaRebaiQA** [comment]
Hello everyone,

Could we close this issue as it's a duplicate of this one #31679 ?

**Comment by RosaBenouamer** [comment]
@kpodemski do you agree with Hana ?

**Comment by pokusa-org** [comment]
Szanowni Państwo, nie pracuję już w firmie Nikos. W sprawach pilnych proszę o kontakt z Moniką ***@***.***

**Comment by sebastian-marinescu** [comment]
@HanaRebaiQA How is this a duplicate? This was posted in January, and the other one in March. 
The other one is the duplicate 😉

**Comment by RosaBenouamer** [comment]
@paulnoelcholot because Hana doesn't work yet for Presta :-)

**Comment by seederp2p** [comment]
> I'm trying for the last hours to upgrade to PS8. I am encountering the exact same problems like @dreanmer.
> 
> Because 1clickupgrade always had connection timeouts, I did the manual upgrade, like described in the docs, and also from 1.7.8.8. After that _nothing_ worked. I started debugging and fixed the php-errors inside my override-classes. I also updated many modules. But now I encountered this error:
> 
> `PHP Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "prestashop.adapter.news.circuit_breaker.settings" has a dependency on a non-existent service "prestashop.core.circuit_breaker.guzzle.cache_subscriber". in /ps_shop/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:86`
> 
> The blog posts to this release sounded promising, but the experience while upgrading is not.
> 
> I will have to revert and freeze too, until these issues are resolved.

I also have this exact problem when tried to upgrade our testing environment.

`INFO - === Step upgradeDb
PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "prestashop.adapter.news.circuit_breaker.settings" has a dependency on a non-existent service "prestashop.core.circuit_breaker.guzzle.cache_subscriber". in /var/www/MYFOLDER/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:86
Stack trace:
#0 /var/www/MYFOLDER/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(83): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue()
#1 /var/www/MYFOLDER/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(49): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue()
#2 /var/www/MYFOLDER/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(83): Symfony\Compon in /var/www/MYFOLDER/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php on line 86`

**Comment by tiollo-eu** [comment]
I could fix this issue by removing the dependency:
- ['setClientOptions', [{'method': 'GET', 'subscribers': ['@prestashop.core.circuit_breaker.guzzle.cache_subscriber']}]]
within: src/PrestaShopBundle/Resources/config/services/adapter/news.yml

Just remove (safe) this line and you should be good to go: I try to restore that line after the upgrade within the file but it broke the functionality. Therefor I would avoid  or replace it with the right dependency if necessary. So far no disadvantage occurred.

**Comment by Ramesh-Chouhan** [comment]
> I'm trying for the last hours to upgrade to PS8. I am encountering the exact same problems like @dreanmer.
> 
> Because 1clickupgrade always had connection timeouts, I did the manual upgrade, like described in the docs, and also from 1.7.8.8. After that _nothing_ worked. I started debugging and fixed the php-errors inside my override-classes. I also updated many modules. But now I encountered this error:
> 
> `PHP Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "prestashop.adapter.news.circuit_breaker.settings" has a dependency on a non-existent service "prestashop.core.circuit_breaker.guzzle.cache_subscriber". in /ps_shop/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:86`
> 
> The blog posts to this release sounded promising, but the experience while upgrading is not.
> 
> I will have to revert and freeze too, until these issues are resolved.

Hi
I have solved this issue by deleting one service file manual and then upgrade.
Service file /src/PrestaShopBundle/Resources/config/services/adapter/news.yml

**Comment by WahbiPS** [comment]
May be linked https://github.com/PrestaShop/autoupgrade/pull/609

**Comment by kpodemski** [comment]
@WahbiPS it is linked, yes

**Comment by tleon** [comment]
Hello, we did a fix in this [PR](https://github.com/PrestaShop/autoupgrade/pull/609) that should also fix this problem. 
This will be shipped in the next version of the autoupgrade module that should be out by next week. I'll post again on this issue when the module is released so you can test the fix.

**Comment by hibatallahAouadni** [comment]
Fixed by https://github.com/PrestaShop/autoupgrade/pull/609
