### ISSUE TITLE
module mails alert 2.4.0: can't enter new mail address in the configuration form

### ISSUE THREAD

**Issue by kimlyweb** [PrestaShop/PrestaShop#30767]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi!
I have installed the module mail alerts of prestashop : version v2.4.0 and prestashop 1.7.8.8.
When i want to configure the email address, i can't registrer and I get the messages : 
Please type one (or more) email address for the new order notification
Please type one (or more) email address for the out of stock notifications
Please type one (or more) email address for return slip notifications
So i can't register...
Thanks for your help

### Steps to reproduce

1 open module email alerts from prestashop
2 enter the emails in the fomr
3 confirm
4 get the error messages

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4.25

### If your bug is related to a module, specify its name and its version

email alerts form prestashop v2.4.0 (in french Alertes par e-mail)

**Comment by venditdevs** [comment]
Hi @kimlyweb 

Did you entered a comma after typing the emailaddres to add the input? It's mandatory to use a comma after.

I can reproduce your problem but only without the comma.


https://user-images.githubusercontent.com/14218917/211281455-05672562-eb21-4e53-96a0-cb14dfae0498.mp4

**Comment by kimlyweb** [comment]
Hi!

Ok It works fine !
Thanks for your help

________________________________
De : venditdevs ***@***.***>
Envoyé : lundi 9 janvier 2023 10:54
À : PrestaShop/PrestaShop ***@***.***>
Cc : kimlyweb ***@***.***>; Mention ***@***.***>
Objet : Re: [PrestaShop/PrestaShop] module mails alert 2.4.0: can't enter new mail address in the configuration form (Issue #30767)


Hi @kimlyweb<https://github.com/kimlyweb>

Did you entered a comma after addon the emailaddres to add the input? It's mandatory to use a comma after.

I can reproduce your problem but only without the comma.

https://user-images.githubusercontent.com/14218917/211281455-05672562-eb21-4e53-96a0-cb14dfae0498.mp4

**Comment by venditdevs** [comment]
You're welcome.

**Comment by hibatallahAouadni** [comment]
Thanks @venditdevs for your quick replies 🚀 
Closing the issue as the problem solved 🙏
