### ISSUE TITLE
Page loads slow due to duplicated sql queries

### ISSUE THREAD

**Issue by afarkassk** [PrestaShop/PrestaShop#30768]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The product page loads very slow, using PS_DEBUG_PROFILING reveals huge amount of duplicated sql queries.
The highest numbers as follow:
82 stock_available
26 product_attribute
21 product_attribute_shop

### Expected behavior

Page loads quicker

### Steps to reproduce

Have product with attribute combinations

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

**Comment by kpodemski** [comment]
Hello,

It's not a valid bug report. The number of queries is only one thing that may impact the performance of the website. This is a complex subject. If you want to optimize a product page, you can hire a specialist or look for support. On the project's website [there's a Support page ](https://www.prestashop-project.org/support/) where you can see available options.

**Comment by afarkassk** [comment]
"The number of queries is only one thing that may impact the performance" ... well, guys, may be i did not explained myself crearly enough, english is not my native language... Therefor i try again and better...
Im not reporting the "number of queries" im reporting the number of DUPLICATED queries...
Those numbers - 82 stock_available, 26 product_attribute, 21 product_attribute_shop are not just numbers of queries, but numbers of DUPLICATED queries
