### ISSUE TITLE
Autocomplete missing in brand input on product page v2

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#30770]
### Describe the bug and add attachments

On legacy product page, there is an autocomplete input on brands, so searching in a long list is easier.
On new product page, there is just a simple selectbox which is hard to navigate on real stores with dozens of brands.

### Expected behavior

Autocomplete missing in brand input on product page v2.

### PrestaShop version(s) where the bug happened

develop

**Comment by Hlavtox** [comment]
cc @zuk3975

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/30776
