### ISSUE TITLE
module Faceted search - URL/Route Bug 

### ISSUE THREAD

**Issue by CentPhiltres** [PrestaShop/PrestaShop#30778]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, 

I have install the Faceted search ( Navigation à facettes in french ) module for my Prestashop ( 1.7.8.7 ). 

Everything is well configured. However, for the url of my filters, i wanted to change to something more relevent. Because, the url of my filters have some special characters like "q=", "+", "-", "%" but i just wanted it to be written with it's id, category and the name of the filter. 

I saw that usually, we can configure the way the url should appear in the Traffic & SEO section of Prestashop Back-office. Infact there is the option : " Route vers la catégorie avec le paramètre "selected_filter" pour le module de navigation à facette: {id}-{rewrite}{/:selected_filters} ".

In my case, when i go to my backoffice, this is all that i can configure for the url:
![image](https://user-images.githubusercontent.com/122299248/211364110-b976cf96-c44e-4eed-8f33-3fc0fc949e08.png)

There is no option related to Faceted search module and it's URL configuration. Therefore, i can't change the way my filters url look. 

can you enlighten me about the reason why i don't have this option in my back-office please? 

Is there any other solution about how can i change my filters url in this order : {id}-{rewrite}{/:selected_filters} ?

Kind Regards,
Cent Philtres

### Steps to reproduce

1. Configure Faceted search module and create a filter. 
2. Go to "Trafic et SEO > Format des URL"

### PrestaShop version(s) where the bug happened

1.7.8.7

### If your bug is related to a module, specify its name and its version

ps_facetedsearch v3.9.0

**Comment by paulnoelcholot** [comment]
Hello @CentPhiltres,

I have tried to reproduice the issus but I did not succed. Can you please prode a screen record pls?

Thanks !

**Comment by CentPhiltres** [comment]
Hello, 

I actually want my url on my category page to be shown in some proper order when i select a filter ( which uses Faceted search module ) . For exemple, for this page when i select the filter "Cartomiseurs", this is how the url is displayed: https://www.centphiltres.co/887-vapoteuse?q=Cat%C3%A9gories-Cartomiseurs

![image](https://user-images.githubusercontent.com/122299248/211587640-e108235b-abd3-4fac-963b-169cb1aa9d7d.png)

However, i wanted it to be displayed without any of these caracters "?q=" "%". I want to keep it simple with just a "/" that shows the main category and the filter category name. 

To do so, i saw that we could manage it in Trafic et SEO
 > SEO & URL section on the Prestashop Back-office, by adding on the route field ( to category with "selected_filter" parameter for this faceted navigation module) this: " {id}-{rewrite}{/:selected_filters} ". But, once i am there, i can't find this option along with the other. Infact, the layered_url field disappeared from configurable routes.
![image](https://user-images.githubusercontent.com/122299248/211588898-329b59d4-e71a-4d79-ba5a-dddf41b6d8b6.png)

**Comment by HanaRebaiQA** [comment]
Hello @CentPhiltres 

Is your issue similar to this one #27571 ? 
Thanks!

**Comment by CentPhiltres** [comment]
Hello, 

Yes, one part of it is similar to #27571 but the main issue concerning the url is still there. The url when a filter is selected on category page isn't friendly.  The url still contains these caracters "?q=" "%" instead of separating the category with "/".

**Comment by AureRita** [comment]
Hi @CentPhiltres 

As I Understand your issue, you set up a name for your categories and with the facted search it's not set,but, as we can see with this video : 

[Untitled_ Jan 12, 2023 4_25 PM (1).webm](https://user-images.githubusercontent.com/100699445/212108414-5a850d1e-a702-489f-b086-994be2663072.webm)

There is a difference between the categories set by a radio point on the faceted search on directly the category, 

So now it's not a real issue 
Can it be take like a feature that you want to make the faceted search more friendly ? 
If yes, you can set your new feature [here](https://build.prestashop-project.org/news/2023/github-discussions-are-now-enabled-in-the-prestashop-project/)

Waiting for your feedback

**Comment by CentPhiltres** [comment]
Hello, 

In my case, the url doesn't change. Character like "?q=" "%" shows anyways when i select an option from filter...

Is there no way other way to change the url ? 

Centphiltres

**Comment by sallemiines** [comment]
Hello @CentPhiltres 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.
Please note that you can always create a new one if further information pops up.


Thank you
