### ISSUE TITLE
Debug mode issue on fresh install via docker

### ISSUE THREAD

**Issue by SuperLanceur** [PrestaShop/PrestaShop#30773]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When installing PrestaShop via docker (prestashop/prestashop:8.0.1-apache) it's not possible to enable debug mode.

``Error: Could not find whether debug mode is enabled. Make sure that the correct permissions are set on the file /var/www/html/app/../config/defines.inc.php``

Permissions are set correctly,

### Expected behavior

Debug mode should be enabled

### Steps to reproduce

1. Fresh install of PrestaShop and its database via docker-compose (https://gist.github.com/SuperLanceur/36b372c2547044c0bb621c8f1555759e)
2. Toggle debug mode activation button and save

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

5.6 (docker's default, php is not installed on the server)

**Comment by paulnoelcholot** [comment]
Hello,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

I followed the procedure and I managed to do a fresh install. So it seems to me that the problem comes from your docker compose.

We will close this issue.

Thank you

**Comment by SuperLanceur** [comment]
Thanks for your answer @paulnoelcholot 
Did you use the docker-compose file I provided? If not, can you please provide me with the one you used, so that I can confirm mine is at fault?
Again, many thanks

**Comment by TechhDan** [comment]
I also had this issue running running a PrestaShop docker container. I found the issue has to do with validating the defines.inc.php or defines_custom.inc.php files. I've explained it more here with a solution as well.

https://github.com/PrestaShop/docker/issues/330

**Comment by TechhDan** [comment]
@paulnoelcholot The way PrestaShop checks if debug mode is enabled in the back-office performance page is a little weird. It scans the contents of the defines inc files and does a regex. The regex doesn't cover scenarios like `getEnv` functions so it throws an error that's misleading about permissions when it reality the regex wasn't able to understand the file.

**Comment by SuperLanceur** [comment]
Your solution works as a work-around to manually enable/disable debug mode. Many thanks !

**Comment by matteolavaggi** [comment]
3 years later and the same bug is here ^^ whats worse than a docker image that does not work out of the box? nothing :P
