### ISSUE TITLE
Includes front-end JavaScript libraries with known security vulnerabilities

### ISSUE THREAD

**Issue by adamus007p** [PrestaShop/PrestaShop#30785]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Prestashop 8.0.1 and Hummingbird [v0.1.2](https://github.com/PrestaShop/hummingbird/releases/tag/v0.1.2)

In the  Lighthouse I see:
Includes front-end JavaScript libraries with known security vulnerabilities
[jQuery UI@1.10.3](https://snyk.io/vuln/npm:jquery-ui?lh=1.10.3&utm_source=lighthouse&utm_medium=ref&utm_campaign=audit)
![image](https://user-images.githubusercontent.com/19956106/211431931-51b371fe-17eb-44ef-a601-847039f98b3e.png)

Is is related to hummingbird itself and to Prestashop? May you update it?

### Steps to reproduce

Developer tools > Lighthouse 

### PrestaShop version(s) where the bug happened

8.0.1

**Comment by Hlavtox** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/27186
