### ISSUE TITLE
index page meta keywords limited to 22

### ISSUE THREAD

**Issue by elmanu13** [PrestaShop/PrestaShop#30783]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On parameters, traffic & SEO page, editing the index page to add meta keywords, I got the error 
 [PrestaShop\PrestaShop\Core\Domain\Meta\Exception\CannotEditMetaException code 0]
when the number of keywords exceed 22.

### Expected behavior

we should be able to add more keywords

### Steps to reproduce

Go to parameters, traffic& SEO page
Clic on the index page (id 4) to edit it
enter 23 keywords and save

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4.33

**Comment by kpodemski** [comment]
Hi @elmanu13 

I think the usage of meta-keywords should eventually be removed from the software. And adding 22 of them seems like a very specific use case. Also, it's probably not about a number of keywords, it's about the entire length of them.

I don't think there's anything to fix, honestly :) Is there any reason you still use meta-kewords?

**Comment by Hlavtox** [comment]
@elmanu13 Bro keywords are dead for like 15 years 😄

**Comment by elmanu13** [comment]
Thanks for the feedback, I was just trying the stuff, but indeed if it's useless @kpodemski is right : that should be removed
