### ISSUE TITLE
HTTP ERROR 500 /public/var/cache/prod

### ISSUE THREAD

**Issue by adamus007p** [PrestaShop/PrestaShop#30786]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have noticed that from time to time in my server there is HTTP ERROR 500
It it related with /public/var/cache/prod that some files have no permission.

I have noticed that here some other users had the similar problems.

![image](https://user-images.githubusercontent.com/19956106/211434344-7c8207ae-b704-48ac-b40f-01ec8680ec47.png)

I can correct manually the permission to 0755 and the shop starts working OK.

namespaced_class_stub.php
appParameters.php
class_index.php
000 permissions ----

Why it may happened? Maybe it is some bug regards cache or Symfony?

On my end I have the same problem with Prestasop 1.7 and now with v8 with different php 7.3, 7.4, 8.0, 8.1.

Nginx Version Installed: 1.23.3 (in older versions too)
PHP Version Installed: 8.1.14
CentOS Version: CentOS 7 64bit
I use LEMP: centminmod but i saw that someone here had the similar problems with other enviroment.

The problem exist as from long time, so it is not introduced now.

### Steps to reproduce

It happen occiasionally when I doing something in BO. Eg. when I was adding new module autoupgrade and wanted to update PS to 8.0.1. 1.7.8.5 > 1.7.8.8 and in 1.7.8.8 > 8.0.1

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

7.3, 7.4, 8.0, 8.1.

**Comment by paulnoelcholot** [comment]
Hello,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem. You seem to be using nginx instead of apache. It seems that the problem stems from there. On our side it is not possible for us to test with this environment.

We will close this issue.

Thank you

**Comment by adviva** [comment]
Hi there! We are having exactly the same problem with two different environments. 
We have a hybrid apache + Nginx reverse proxy. 
Prestashop 1.7.8.7 and PHP 7.4.
Cloudlinux (Almalinux 8)

Somehow, when we save some translations we get this problem too. This happens constantly, so it is not occasionally as @adamus007p. Specifically, file appParameters.php & class_index has **000**.

**Comment by adamus007p** [comment]
@paulnoelcholot as you see this not only my enviroment, in the past i saw other tickets regards it.

This is not normal that files are created as 000 permission and no owner.

@adviva both your enviromets are with Apache and Nginx?

I have problems with many versions Prestashop 1.7.8.5 also 1.7.8.8
I was testing to update first 1.7.8.5 to 1.7.8.8  I have permission problems.
Later I have update from 1.7.8.8 to Prestashop v8.0.1 - I have problems too.

I was testing 7.3, 7.4, 8.0, 8.1.


The question is why that 3 files have no permissions?

@adviva may you list all files which you have a problem or and full path? Are files are in v/public/var/cache/prod ?

> This happens constantly, so it is not occasionally

I agree with it. Constantly

**Comment by adamus007p** [comment]
@adviva do you use OPcache? Zend OPcache ?
Please open your opcache config and check
`opcache.revalidate_freq=0` and what you have here? change to 0
or if you do not have this line please add 
`opcache.revalidate_freq=0`
save and then restart your php service.

After that please test and let me know if you have errors.


Moreover if this will not help you may check to disable opcache and test
`opcache.enable=0` <disabled cache

**Comment by adviva** [comment]
Hi @adamus007p,
yes, they are both Apache + Nginx. What happens constantly is mainly

- var/cache/prod/appParameters.php  -> **000**
- var/cache/prod/class_index.php  -> **000**
- var/cache/prod/class_stub.php (**NOT ALWAYS 0, I HAVE NO IDEA WHY 😅**)
- var/cache/prod/namespaced_class_stub.php (**NOT ALWAYS 0, I HAVE NO IDEA WHY 😅**)

I agree issue should stay open even because it is a breaking bug. We encountered this problem yesterday and we had to edit the **bootstrap.php** as a hotfix.

We are not sure how _opcache_ might be involved in this but we will try and let you know. 

Cheers.

**Comment by adamus007p** [comment]
@adviva I belive that issue is related to Symfony and Opcache. Please change cache to
`opcache.revalidate_freq=0` and let me know if it helped.
only this line, save and restart the php service.

**Comment by adviva** [comment]
Hi @adamus007p,

we have to admit we were skeptical about this fix because we couldn't understand which is the link between permissions and opcache but apparently, you are right! It seems to work!

Can you explain to us a little bit more about what we are missing? 🤔 how opcache is involved in this?
BTW now we need to add in pipeline the script to restart PHP otherwise we will "lose" the configuration....correct?

This is our configuration:

```
[opcache]
opcache.enable_file_override = 1
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0
[core]
zend.detect_unicode = 0
realpath_cache_ttl = 3600
```

**Comment by FabienPapet** [comment]
👋 Hello there, Thank you for submitting the issue. As we are not able to reproduce your issue, if you have a fix, do not hesitate to submit a PR.

Thank you

**Comment by adamus007p** [comment]
The problem, probably some bug comes from Symfony or using it by Prestashop. Problem exist it you use Opcache and you have bigger times of refresh your cache.
Symfony cache something and Opcache case it. I belive that it something with Symfony.


I have other websites not Prestashop and I do not have such problems, even with Opcache.

@FabienPapet to reproduce the problem you shoould have php-fmp + Zend OPcache to reproduce the problem and put opcache.revalidate_freq = 180.

@FabienPapet I could provide you a test envirement if you want to test it, or maybe @adviva can provide it too.


What I have figure out is more workaround not solution of the problem.

I do not know what following files are doing:
namespaced_class_stub.php
appParameters.php
class_index.php
@FabienPapet what that files are doing?




PS. @adviva please try to change to 10.
`opcache.revalidate_freq = 10`
and let me know if this works too

**Comment by adamus007p** [comment]
I was using on the same server and settings Prestashop 1.6 and I never had such cache problems.
It starts from Prestahsop 1.7 and it also are in Prestashop 8.0.1.

This cross tests show that problem is related to Prestashop but I belive more to used by Prestashop Symfony.


My update was a clean install of Prestashop 1.7 and copying manually products via Prestashop API.

Anyway with clear Presta there are the same errors.

**Comment by adamus007p** [comment]
@adviva The error soundslike a Prestashop configuration issue with how it creates files in /public/var/cache/prod - judging from directory names, it's some form of cache the the script generates. 


@FabienPapet what controls file permissions and ownership in /public/var/cache/prod ?

what following files are doing:
namespaced_class_stub.php
appParameters.php
class_index.php?

**Comment by FabienPapet** [comment]
The following files are auto generated from the Autoload system: 
- namespaced_class_stub.php
- class_index.php

Please have a look on `classes/PrestaShopAutoload.php` that generates them, there's perhaps an issue on filemode.

I don't know about appParameters.php

**Comment by adviva** [comment]
@FabienPapet appParameters is simply the generated cache version of the homonymous file

**Comment by adamus007p** [comment]
What I can update but recommended by Prestashop `opcache.revalidate_freq = 10` not works, so please try use `opcache.revalidate_freq = 0`. The best would be if someone would fix it. This issue comes from PS 1.7, in 1.6 was OK.

**Comment by hibatallahAouadni** [comment]
Hello @adamus007p 

Do you still encounter the issue with 8.1.x? Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @adamus007p 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by tzuiopo** [comment]
Does anybody have a solution for this?

When I clear cache the result is whitepage both in BO, FO.
The appParameters.php permission is 644.
It occured that the server was changed (directadmin) .
The serversetting are the same.

Another error occures when I delete abandoned carts . Result 500 error, 
Clicking back in the browser BO goes again. 
It is annoying...

**Comment by adamus007p** [comment]
> Hello [@adamus007p](https://github.com/adamus007p)
> 
> Do you still encounter the issue with 8.1.x? Please check and feedback.
> 
> Thanks!


@hibatallahAouadni @FabienPapet @florine2623 
I can confirm that problem exist in v. 8.2, 

May you reopen that issue?



Only one working wordaround, not a fix is to set up:

opcache config to 0 (disable it)
opcache.revalidate_freq=0

save and then restart your php service.




@adviva  @tzuiopo i open new report https://github.com/PrestaShop/PrestaShop/issues/37666
