### ISSUE TITLE
UniqueConstraintViolationException when copying product with combinations to shop

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#30792]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In product v2 when using multistore feature "copy to shop" an error is thrown when trying to copy a product with combination to another shop.
<img width="810" alt="Screenshot 2023-01-10 at 16 30 07" src="https://user-images.githubusercontent.com/31609858/211579307-597bfacb-5977-4090-9a3f-99054a792a25.png">

Might be related to recent PR https://github.com/PrestaShop/PrestaShop/pull/30584

### Expected behavior

No error

### Steps to reproduce

1. Turn on multistore, create at least 2 shops, enable product v2 page through experimental features and go to product v2 page.
2. Edit any product with combinations
3. If product is already associated for both shops then use "select shop" and unselect shop2.
4. Again use "select shops" and select shop2 again
5. You should see error complaining about `UniqueConstraintViolation`.

### PrestaShop version(s) where the bug happened

develop

**Comment by paulnoelcholot** [comment]
Hello @zuk3975,

Despite my efforts, I have not managed to reproduce this bug, could you send me a video screen pls?

Thanks

**Comment by zuk3975** [comment]
> Hello @zuk3975,
> 
> Despite my efforts, I have not managed to reproduce this bug, could you send me a video screen pls?
> 
> Thanks

I tried reproducing again repeating the same flow, but now I got another error in my way 🤔 (but basically the scenario is the same - create a new shop with all the default options including copying all the data from shop1, then go to product page and try to unselect shop2)

https://user-images.githubusercontent.com/31609858/211593160-d77146a9-8cc3-4ec7-93fb-05c4ad946150.mov

**Comment by AureRita** [comment]
Hello @zuk3975 

Thank for your report, I also tried to reproduce your issue as you can see : 

[Untitled_ Jan 10 2023 5_33 PM.webm](https://user-images.githubusercontent.com/100699445/211613100-59229542-7a6a-4b07-b681-accc615be520.webm)

But I didn't reproduce it. Did you do anything else to do this ? 

Waiting for your feedback

**Comment by zuk3975** [comment]
> Hello @zuk3975
> 
> Thank for your report, I also tried to reproduce your issue as you can see :
> 
>  Untitled_.Jan.10.2023.5_33.PM.webm 
> But I didn't reproduce it. Did you do anything else to do this ?
> 
> Waiting for your feedback

for the first issue I encountered you are still missing one step - trying to associate to the same shop again (thats when I got the unique constraint error the first time).
For additional actions, I haven't done anything much in particular. It was fresh install and I created a shop with copying all source shop data, then did the same as you in video 🤔 
I'll try reinstalling freshly and try again and will come back with the result 🤔

**Comment by zuk3975** [comment]
here I recorded it all from start to finish with a fresh install and I still see the error.

https://user-images.githubusercontent.com/31609858/211768727-d3e50524-ae52-4d2c-b407-5a6b0e55eddb.mov

**Comment by HanaRebaiQA** [comment]
Hello @zuk3975 

I was able to reproduce your issue with develop and php 7.4

![image](https://user-images.githubusercontent.com/92912932/211784753-080e0343-6f32-4bd3-a941-47d11c3d2e2b.png)


Indeed, it's a regression!

I'll add this to the debug backlog so that it's fixed.

Thank You!
