### ISSUE TITLE
Authentification - Bad value for smarty var 'vat_managment'

### ISSUE THREAD

**Issue by sire-sam** [PrestaShop/PrestaShop#308]
## Visible issue

VAT number field is not displayed.
Javascript for diplay 'VAT number' field in authentification/signup form, is not loaded.
The javascript function is englobed by smarty condition, checking '$vat_management' value.
## Controller Issue

In /controllers/front/AuthController.php line 216, the smarty assign get value from configuration 'VATNUMBER_MANAGEMENT', but this value doesn't seems to existe in table '[prefix]_configuration'.

I looked at the admin script who update this value (/controllers/admin/AdminTaxesController.php), and seems to update value for PS_TAX and not 'VATNUMBER_MANAGEMENT''.
## Fix

In /controllers/front/AuthController.php line 216 replace 'VATNUMBER_MANAGEMENT' by 'PS_TAX'

Am I right ?

**Comment by marionf** [comment]
Hello, 
This issue is old, so I close it.
If you still have it on the last version (PrestaShop 1.7.4.2), please open a new one.
Regards

**Comment by sire-sam** [comment]
Omg this is so old 😸 

Thank you for closing this, I don't use this soft anymore but I'm sure it has been fixed. 

Have a nice day 😺 

Regards.
