### ISSUE TITLE
Problem calculating price with tax

### ISSUE THREAD

**Issue by crv248** [PrestaShop/PrestaShop#30807]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I'm having a problem calculating the price of a product wich has a price of 0.12€ witouth taxes. 
And the result of the tax calculation is 0.1452€:
![image](https://user-images.githubusercontent.com/15896239/211793505-57f9287a-5a27-49dd-b5fb-20b2634e030f.png)

And that it's correct, but when I go to the Front to buy this product, the price it's rounded to 0.15€ and the total of the product in the cart is calculated with the price not rounded (0.1452), so if the customer tries to calculate the result it's wrong:

![image](https://user-images.githubusercontent.com/15896239/211794177-fcf1f66f-a392-444f-a8b9-f665c1df78f4.png)

So, the result is 2334 * 0.1452 = 338,90 €
But if the customer does the calulate with the visible information is: 2334 * 0.15 = 350,1 €

And this is a problem for us because we are working with an ERP that we send this information (2334 * 0.15 = 338,90 €) wich is wrong when the ERP tries to validate the total of the order.

How could I fix it?

Regards. 

### Steps to reproduce

1 - Create a product with the price without taxes 0.12
2 - Go to the store to buy and see that the prices it's rounded to 0.15 €

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4

**Comment by HanaRebaiQA** [comment]
Hello @crv248 

Thanks for your report.
I think that our issue is similar to this one #29338. 
What do you think?

Thank You!

**Comment by TRINHTHAIPHUONG** [comment]
> ### Prerequisites
> * [x]  I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
> * [x]  I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.
> 
> ### Describe the bug and add attachments
> I'm having a problem calculating the price of a product wich has a price of 0.12€ witouth taxes. And the result of the tax calculation is 0.1452€: ![image](https://user-images.githubusercontent.com/15896239/211793505-57f9287a-5a27-49dd-b5fb-20b2634e030f.png)
> 
> And that it's correct, but when I go to the Front to buy this product, the price it's rounded to 0.15€ and the total of the product in the cart is calculated with the price not rounded (0.1452), so if the customer tries to calculate the result it's wrong:
> 
> ![image](https://user-images.githubusercontent.com/15896239/211794177-fcf1f66f-a392-444f-a8b9-f665c1df78f4.png)
> 
> So, the result is 2334 * 0.1452 = 338,90 € But if the customer does the calulate with the visible information is: 2334 * 0.15 = 350,1 €
> 
> And this is a problem for us because we are working with an MB that we send 6789001239999 (2334 * 0.15 = 338,90 €) wich is TRINH THAI PHUONG

**Comment by TRINHTHAIPHUONG** [comment]
#28430

**Comment by hibatallahAouadni** [comment]
Hello @crv248 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
