### ISSUE TITLE
Changing combinations with price impact in FO takes 8+ seconds

### ISSUE THREAD

**Issue by afarkassk** [PrestaShop/PrestaShop#30805]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have products with 300+ combinations, different prices. When chenging combination in front office, to reveal price changes takes 8 and more seconds. Using the default prestashop combinations management. Is there anything i can do to speed up this??

### Steps to reproduce

Have many combinations with different prices.
In front office click on different combinations available.
Watsch the price change

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

**Comment by HanaRebaiQA** [comment]
Hello @afarkassk 

Thanks for your report.

It seems that one of these issues is similar to yours #22661, #21240 ?

Thank You!

**Comment by afarkassk** [comment]
> Hello @afarkassk
> 
> Thanks for your report.
> 
> It seems that one of these issues is similar to yours #22661, #21240 ?
> 
> Thank You!

Hi, thanks, no not similar to any of them. The product does update the price, no need to refresh the page and does update it correctly. It only takes ages...
Product with 420 combinations and 12 different prices takes 8 seconds to update the price...

EDIT: Not 18 seconds, it was misstyped, but 8 seconds.
As an example, try this product, try to change dimmension or paper type, then wait the price to change:
https://shop.attila-farkas.sk/en/conceptual/34-2213-blown-by-the-time-11.html#/19-dimension-40cm_x_50cm/22-paper_type-standard_archival_320g_m_matt/40-actual_copy_number_front_back-front/45-show_title_on_front-no

**Comment by HanaRebaiQA** [comment]
Hello @afarkassk 

I forgot this one #12915 to validate with you.
What do you think ?

**Comment by afarkassk** [comment]
> Hello @afarkassk
> 
> I forgot this one #12915 to validate with you. What do you think ?

Hi, yes that is pretty the same issue, and i even saw the thread before, but it is related to much older version of PS than is the actual most recent and in the post it says it was solved in precedent version... so i suggest now it is related to some other  reason as before.

**Comment by kpodemski** [comment]
Hi @afarkassk 

It takes a lot of time to load the category page in your store:
https://shop.attila-farkas.sk/en/11-landscape

I think you have some general issues with your server performance. It's not really **a bug** but a problem that you need to find someone to help you with.

**Comment by afarkassk** [comment]
> Hi @afarkassk
> 
> It takes a lot of time to load the category page in your store: https://shop.attila-farkas.sk/en/11-landscape
> 
> I think you have some general issues with your server performance. It's not really **a bug** but a problem that you need to find someone to help you with.

Oh yes. I submitted a ticket few days ago complaining about a huge ammount of multiple sql queries... my thread was closed saying that big number of sql queries is not a bug or something to heal...
The guy who closed the thread completelly disregarded the fact that im not reporting the ammount of queries but the number of DUPLICATE queries...
Also, i have try to reduce the number of combinations, and when i did, (i had only some 150 with 4 different prices), the whole site was super fast... so this loading time and the number of DUPLICATE queries has definitely something to do with the number of combinations...

**Comment by kpodemski** [comment]
@afarkassk 

>Oh yes. I submitted a ticket few days ago complaining

This is not a support center. This is an open-source project. Project members who run this project don't work for you.

You can search for [commercial support](https://www.prestashop-project.org/support/) and then demand the service be done well and on time.

> Also, i have try to reduce the number of combinations, and when i did, (i had only some 150 with 4 different prices), the whole site was super fast... so this loading time and the number of DUPLICATE queries has definitely something to do with the number of combinations...

Obviously, but again, it's a complex subject. It could go to the "Performance optimization" section to the lists of things that the project would welcome to see, but that doesn't mean that someone will take over on the subject that is interesting to you.

**Comment by afarkassk** [comment]
> @afarkassk
> 
> > Oh yes. I submitted a ticket few days ago complaining
> 
> This is not a support center. This is an open-source project. Project members who run this project don't work for you.
> 
> You can search for [commercial support](https://www.prestashop-project.org/support/) and then demand the service be done well and on time.
> 
> > Also, i have try to reduce the number of combinations, and when i did, (i had only some 150 with 4 different prices), the whole site was super fast... so this loading time and the number of DUPLICATE queries has definitely something to do with the number of combinations...
> 
> Obviously, but again, it's a complex subject. It could go to the "Performance optimization" section to the lists of things that the project would welcome to see, but that doesn't mean that someone will take over on the subject that is interesting to you.

Well, im not seeking for support... im reporting that your open source software is acting non-effectively.

The Performance optimization i already tuned to its best - i had ranking C on GTmetrics, page loaded in 2 seconds - while keeping combinations number low.
As soon as combinations increased, even the main homepage suffered of slow loading and noticed a huge ammount of DUPLICATE sql queries...

Ok, just close the thread, i see there is no interest to take in consideration what i am reporting.
Have a nice day

**Comment by AureRita** [comment]
Hi @afarkassk

Thank for your report, we have interest about your issue because it can improve our project. But, I tried to reproduce your issue : 

[Untitled_ Jan 12, 2023 3_07 PM.webm](https://user-images.githubusercontent.com/100699445/212088250-4a1e940d-9c36-4dff-81f8-ff6aad5b01bd.webm)

As you can see, I can't create enought product because my max input var is too high, if you increase it, you are exposate to some slowdown. 

We have an other issue that threat about the time spend on this part, some fixes in the 8.0 fixes the problem of the double jquerry. 

As we have an other issue with the same problem, I'll close this one. But try with the version 8.0.0, maybe your issue will be solved

**Comment by AureRita** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/12915

**Comment by afarkassk** [comment]
I see, ill consider 8.0. Thanks
