### ISSUE TITLE
[ps_linklist] Wrong template used for left/right column on product page

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/PrestaShop#30802]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Classic theme uses special columns for product page:
https://github.com/PrestaShop/classic-theme/blob/4548524c9cbeb83c4a9a28a9f9c2a121b86b41ce/templates/layouts/layout-both-columns.tpl#L65-L74
https://github.com/PrestaShop/classic-theme/blob/4548524c9cbeb83c4a9a28a9f9c2a121b86b41ce/templates/layouts/layout-both-columns.tpl#L86-L94

Module loads proper "column" template only for hooks `displayLeftColumn` and `displayRightColumn`, but wrong template for `displayLeftColumnProduct` and `displayRightColumnProduct`.

https://github.com/PrestaShop/ps_linklist/blob/564b2b52de43d5a3863387bafd47462294e6fe0c/ps_linklist.php#L260-L268

### Expected behavior

It should use correct templates also inside columns enabled on Product page.

### Steps to reproduce

1. Admin: Design > Theme & Logo > Choose layouts (bottom of the page)
2. For `product` page choose any layout with column (_Three columns..._ to test both columns at once)
3. Go to Modules, find **"Link List"** and hit _Configure_ or Design > Link List
4. Add blocks to hooks `displayLeftColumnProduct` or `displayRightColumnProduct`
5. Check any front office product page to see bad templates used 

### PrestaShop version(s) where the bug happened

1.7.8.8 - 8.0.1 - develop

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_linklist v.5.0.5, classic-theme

**Comment by HanaRebaiQA** [comment]
Hello @SharakPL 

Could you specify which PrestaShop version did you use please?

Thanks!

**Comment by SharakPL** [comment]
Tested on 1.7.8.8. Probably the same on 8.0.x with classic theme. The bug is in the module, not in PS.

**Comment by AureRita** [comment]
Hi @SharakPL,

I reproduce the issue with PrestaShop version 1.7.8.8, as we can see : 

[Untitled_ Jan 12, 2023 4_01 PM.webm](https://user-images.githubusercontent.com/100699445/212102994-66a10e60-fdc1-4bfd-9185-c750986ef32a.webm)

 I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved.

Thank for your PR :rocket: 

Thanks

**Comment by SharakPL** [comment]
Thanks @AureRita
The fix is already there https://github.com/PrestaShop/ps_linklist/pull/155 Just needs some improvements and awaits author's response.

BTW. Could you maybe switch to different codec for your screen records? Even though Firefox supports `webm` natively, most of your videos is unplayable in Firefox (_Error Code: NS_ERROR_DOM_MEDIA_METADATA_ERR (0x806e0006))_
