### ISSUE TITLE
problem on updating the module 1-click upgrade on my prestashop 1.6.1.24

### ISSUE THREAD

**Issue by kingduweb** [PrestaShop/PrestaShop#30815]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

i have a problem when i want tp ugrade my prestashop to the version 1.7, when i want to use the module 1-click upgrade, it's saying that i need to update this module (the actual version is 4.14.2) and when i want tu update it i have error telling that the file is corrupted or error when unzipping the latest version.

### Steps to reproduce

not steps

### PrestaShop version(s) where the bug happened

1.6.1.24

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

1-click upgrade

**Comment by HanaRebaiQA** [comment]
Hello @kingduweb 

PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).

Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

Thank You!
