### ISSUE TITLE
Main menu error

### ISSUE THREAD

**Issue by osdijon** [PrestaShop/PrestaShop#30814]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After to upgrade prestashop 1.7.8.8 to 8.0.1 with click and upgrade and php 7.4 to 8.0 , in front office when I select a tab in main menu (v 2.3.1), a page open with this error:
![500 servor](https://user-images.githubusercontent.com/121489021/211852823-72f86d0e-82b1-4906-8e95-34ff14833c1f.jpg)

### Expected behavior

Once MAJ done, in front office of my website, when I select a tab of my mainmenu, the corresponding page must be open.

### Steps to reproduce

Upgrade PrestaShop 1.7.8.8 to 8.0.1 with click and upgrade, activate Mainmenu module in module management in prestashop 8. Then Upgrade php 7.4 to 8.0 
Then try to select a tab in front office of your website.

### PrestaShop version(s) where the bug happened

prestashop 8.0.1

### PHP version(s) where the bug happened

8.0

### If your bug is related to a module, specify its name and its version

mainmenu v 2.3.1

**Comment by AureRita** [comment]
Hi @osdijon 

Thank you for your report, 

Currently with the provided information I can't where your issue come from, have you correctly install your php v 8.0 ? Can you go back to your php v7.4 ? ( prestashop 8.0.1 can be used with php 7.4) Did you have your php.ini on php/(your version)/apache2/php.ini ? 

Can you set your shop with the debug mode ? (if you can't by the website, go to [name of your shop]/config/defines.inc.php and on the '_PS_MODE_DEV_' set it to true)

Can you give us the version of your autoupgrade ? 

Waiting for your feedback

**Comment by osdijon** [comment]
-Unfortunately I can't go back to a 7 version in php.
- On my folders, I find an ini.php document
-I set up my shop in debug mode:

[PrestaShopException]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db741207464.pkfi_layered_filter_block' doesn't exist
at line 151 in file classes/db/DbPDO.php

146.     protected function _query($sql)
147.     {
148.         try {
149.             return $this->link->query($sql);
150.         } catch (\PDOException $exception) {
151.             throw new PrestaShopException($exception->getMessage(), (int) $exception->getCode(), $exception);
152.         }
153.     }
154. 
155.     /**
156.      * Returns the next row from the result set.
DbPDOCore->_query - [line 377 - classes/db/Db.php] - [1 Arguments]
DbCore->query - [line 664 - classes/db/Db.php] - [1 Arguments]
DbCore->getRow - [line 181 - modules/ps_facetedsearch/src/Filters/Block.php] - [1 Arguments]
PrestaShop\Module\FacetedSearch\Filters\Block->getFromCache - [line 189 - modules/ps_facetedsearch/src/Product/SearchProvider.php] - [1 Arguments]
PrestaShop\Module\FacetedSearch\Product\SearchProvider->runQuery - [line 335 - classes/controller/ProductListingFrontController.php] - [2 Arguments]
ProductListingFrontControllerCore->getProductSearchVariables - [line 613 - classes/controller/ProductListingFrontController.php]
ProductListingFrontControllerCore->doProductSearch - [line 137 - controllers/front/listing/CategoryController.php] - [2 Arguments]
CategoryControllerCore->initContent - [line 319 - classes/controller/Controller.php]
ControllerCore->run - [line 510 - classes/Dispatcher.php]
DispatcherCore->dispatch - [line 28 - index.php

**Comment by AureRita** [comment]
Hi @osdijon 

Thank you for your clarrification, I tried to reproduce your issue as you can see : 

[Untitled_ Jan 16, 2023 12_10 PM.webm](https://user-images.githubusercontent.com/100699445/212665351-36adab8b-46f1-45ba-900a-c72aa7ce582e.webm)

But I can't reproduce it, did I miss something ? 

Just to let you know, I retry the process with php 8.0 ( here it's 8.1 ) 

Waiting for your feedback

**Comment by osdijon** [comment]
Thank you about research. I've just find mistakes!
In fact, like it wrote in debug, it missed a file.
I've just create this file in the database and it is ok. 
I don't know why, during upgrade prestashop 7.8.8 to 8.0 this file I don't created !
Thank you again about you

**Comment by AureRita** [comment]
No problem, 

It's our role to find the issue with our contributors and help them when it's possible, 

I'll close this issue
Thank your too
