### ISSUE TITLE
ps_facetedsearch and ps_facebook, Safari iOS

### ISSUE THREAD

**Issue by dennispw** [PrestaShop/PrestaShop#30811]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Having filters made and chosen with ps_facetedsearch on a category page, going to a productpage and then going back, a JS TypeError occurs.

In this case, this resulted in the overlay/spinner from ps_facetedsearch not being removed - only a page refresh solved it. This isn't necessarily tied to ps_facetedsearch however, since the JS error stops other JS from being run, ps_facetedsearch is very much affected by it.

### Expected behavior

When going back to a category page with or without filters made through ps_facetedsearch, it should work.

### Steps to reproduce

**In Safari in iOS**

1. Make sure that both ps_facebook and ps_facetedsearch are installed and configured.
2. Go to a category, and choose a filter.
3. Choose and go to any product shown by the applied filters.
4. Go back to the category. When going back, make sure that the browser remembers any URL parameters applied by the filter module in this case.
5. You should see a JS error now.

<img width="517" alt="jserror" src="https://user-images.githubusercontent.com/5259451/211826381-a90dfbd6-e291-4ba6-8610-d83abee932fe.png">

### PrestaShop version(s) where the bug happened

1.7.8.5

### If your bug is related to a module, specify its name and its version

ps_facebook 1.21.0, ps_facetedsearch 3.10.0

**Comment by HanaRebaiQA** [comment]
Hello @dennispw 

Thanks for your report.
I tried to reproduce your issue with PS1788 using Safari iOS (with iPhone14) and `ps_facebook 1.21.0`, `ps_facetedsearch 3.10.0` modules but I was unable to reproduce it


https://user-images.githubusercontent.com/92912932/211842042-0fc04a25-234c-432f-a7f6-3a5d37138cc8.mp4

Did I miss something ?

Thank You!

**Comment by dennispw** [comment]
It's in the FO, not BO.

**Comment by dennispw** [comment]
On further inspection this might actually be a iOS Safari specific issue/bug with cache and/or headers. Put this on hold until further notice...

**Comment by dennispw** [comment]
Safari specific issue. Not related to either module or PrestaShop. Closing.

**Comment by AureRita** [comment]
Hi @dennispw 

Thank you for your report and your conclusion
