### ISSUE TITLE
make assets issue

### ISSUE THREAD

**Issue by Maaaleeek** [PrestaShop/PrestaShop#30816]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

```
~/projet via 🐘 v8.0.8 
➜ node -v
v16.19.0
```

```
~/projet via 🐘 v8.0.8 
➜ npm -v
8.19.3
```

```
~/projet via 🐘 v8.0.8 
➜ make assets                
./tools/assets/build.sh
>>> Building admin default theme...
~/projet/admin-dev/themes/default ~/projet
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: css-loader@1.0.1
npm ERR! Found: webpack@5.72.0
npm ERR! node_modules/webpack
npm ERR!   webpack@"^5" from @types/webpack@5.28.0
npm ERR!   node_modules/@types/webpack
npm ERR!     @types/webpack@">=4.0" from csso-webpack-plugin@2.0.0-beta.3
npm ERR!     node_modules/csso-webpack-plugin
npm ERR!       dev csso-webpack-plugin@"^2.0.0-beta.3" from the root project
npm ERR!   peer webpack@"4.x.x || 5.x.x" from @webpack-cli/configtest@1.1.1
npm ERR!   node_modules/@webpack-cli/configtest
npm ERR!     @webpack-cli/configtest@"^1.1.1" from webpack-cli@4.9.2
npm ERR!     node_modules/webpack-cli
npm ERR!       dev webpack-cli@"^4.7.0" from the root project
npm ERR!       3 more (@webpack-cli/configtest, @webpack-cli/info, @webpack-cli/serve)
npm ERR!   12 more (babel-loader, clean-webpack-plugin, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^4.0.0" from css-loader@1.0.1
npm ERR! node_modules/css-loader
npm ERR!   dev css-loader@"^1.0.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: webpack@4.46.0
npm ERR! node_modules/webpack
npm ERR!   peer webpack@"^4.0.0" from css-loader@1.0.1
npm ERR!   node_modules/css-loader
npm ERR!     dev css-loader@"^1.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/mbenelouafi/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mbenelouafi/.npm/_logs/2023-01-11T16_12_27_587Z-debug-0.log
make: *** [assets] Error 1
```

### Expected behavior

I can launch a `make assets` 

### Steps to reproduce

1- install PrestaShop
2- try to make asstes

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.0.8

**Comment by hrostyk** [comment]
I also had a problem with "make assets". If the folder names where the installation is located contain special characters this can be a problem. In my case it was "/#PROJECTS/PrestaShop/"

**Comment by Maaaleeek** [comment]
@hrostyk I have always the problem even if i try to compile assets manually 
https://devdocs.prestashop-project.org/8/development/compile-assets/

**Comment by hrostyk** [comment]
Try to install NVM (Node Version Manager) and choose another Node version.
I make assets without problems 1.7.8.8, 8.0.0 and develop versions with the following versions:
npm -v
6.14.17
node -v
v14.21.2

**Comment by Maaaleeek** [comment]
@hrostyk thank you for sharing, It work fine for me too.
I think the problem is with  `node -v 16.x`  Conflicting peer dependency with Webpack version
However the documentation mentioned the compatibility with `node -v 16.x `

<img width="715" alt="Capture d’écran 2023-01-12 à 11 13 29" src="https://user-images.githubusercontent.com/117845056/212040499-94faf8b7-762f-4766-b813-d1c65b1e70e0.png">

**Comment by AureRita** [comment]
Hi @Maaaleeek 

Thank for your report, currently we didn't have prestashop v8.0.8, our latest version is 8.0.1. But I don't think your issue is from that. 
This issue is too technical for me, ping @PrestaShop/prestashop-core-developers, can someone please reproduce this issue ? 

Thanks

**Comment by nicosomb** [comment]
@AureRita 8.0.8 is about PHP version 🐘  😉

**Comment by Maaaleeek** [comment]
@AureRita thank you for replay, @nicosomb I don't think the problem comes from php version

**Comment by NeOMakinG** [comment]
@Maaaleeek we are aware of that issue, in the past it was working because of some side effects but we did have to fix it, if you try to use make assets with node 16, even maybe 18 and 19 on the `develop` branch which will be the `8.1` version lately, it will work

While waiting for 8.1, I would suggest you use `n` or `nvm` and switch to node 14 until you're using the 8.1 contexts!

**Comment by Maaaleeek** [comment]
@NeOMakinG I'am with the last version 8.0.1 and the issue is always here, but I make a new project test with:
php    v7.2.34 
node  v16.19.0
npm    v8.19.3

I stay working with `nvm v14.x ` to resolve the problem, waiting for the new release `PrestaShop 8.1`

Result:
![Capture d’écran 2023-01-12 à 18 17 30](https://user-images.githubusercontent.com/117845056/212135124-c9159f36-da8a-4ff5-a536-08cf3bd07418.png)

**Comment by NeOMakinG** [comment]
> @NeOMakinG I'am with the last version 8.0.1 and the issue is always here, but I make a new project test with: php v7.2.34 node v16.19.0 npm v8.19.3
> 
> I stay working with `nvm v14.x ` to resolve the problem, waiting for the new release `PrestaShop 8.1`
> 
> Result: ![Capture d’écran 2023-01-12 à 18 17 30](https://user-images.githubusercontent.com/117845056/212135124-c9159f36-da8a-4ff5-a536-08cf3bd07418.png)

Yeah because we fixed it on the develop branch which isn't the 8.0.x branch, if you want to try on develop and confirm that it's working now, that would be cool!

**Comment by Maaaleeek** [comment]
@NeOMakinG even with the develop version the problem is here with; 
the `dev` directory is deleted from `themes/classic` 

See result with different version:

<img width="1203" alt="Capture d’écran 2023-01-13 à 11 16 14" src="https://user-images.githubusercontent.com/117845056/212300127-9e5d6810-a2e1-4f93-92f1-7b084b5fb934.png">

<img width="1203" alt="Capture d’écran 2023-01-13 à 11 30 25" src="https://user-images.githubusercontent.com/117845056/212300153-0cd8501a-e3da-4d25-962d-012ec4446fa4.png">


<img width="1203" alt="Capture d’écran 2023-01-13 à 11 33 56" src="https://user-images.githubusercontent.com/117845056/212300187-71d9bfee-01b4-44f8-adeb-1f59c98f388f.png">

**Comment by NeOMakinG** [comment]
Did you even retrieve classic from composer? You need to run a `composer install` so classic gets installed

**Comment by DamianoMazzara** [comment]
![2023-01-24 18_50_31](https://user-images.githubusercontent.com/42427094/214369795-52eca644-22c8-49fa-a143-0faee2a3cd01.png)

Tried both 8.0 .x and develop branch.
Already run composer install
I've already installed windows-build-tools with npm

**Comment by Maaaleeek** [comment]
my bad @NeOMakinG, working fin with the develop branch.

**Comment by DamianoMazzara** [comment]
> my bad @NeOMakinG, working fin with the develop branch.

I've cloned the repo from "develop" branch
composer i works
make assets still gives me the same error.
I've tried different node version, how did  you fix that?

**Comment by NeOMakinG** [comment]
> > my bad @NeOMakinG, working fin with the develop branch.
> 
> 
> 
> I've cloned the repo from "develop" branch
> 
> composer i works
> 
> make assets still gives me the same error.
> 
> I've tried different node version, how did  you fix that?

Can you send the error again on develop? We might forgot one specific project to make compatible with node 16+ but I doubt about it, might be classic 🤷‍♂️

**Comment by DamianoMazzara** [comment]
> > > my bad @NeOMakinG, working fin with the develop branch.
> > 
> > 
> > I've cloned the repo from "develop" branch
> > composer i works
> > make assets still gives me the same error.
> > I've tried different node version, how did  you fix that?
> 
> Can you send the error again on develop? We might forgot one specific project to make compatible with node 16+ but I doubt about it, might be classic 🤷‍♂️

I've tried lot of node/npm versions by switching with nvm.

Please tell me if I'm doing something wrong before investigating:

PHP 8.1

git clone (branch develop)
composer i in PrestaShop root
make assets 

Did I miss something?

**UPDATE**
I've tried doing the same with the PC I use at office (and not the one I use at home).
PHP 7.4,
Node 18.1
npm 8.19
branch develop

Same problem.

I'll setup a linux subsystem in my w10 machines hoping I can finally compile these assets.
Anyway creating a linux machine, installing php, composer, node, npm just to compile some PrestaShop assets is insane.

Do you want me to create an issue in the develop branch?

**Comment by theMSY** [comment]
@DamianoMazzara As of today, the issue still persists. 
I managed to build the assets by:
- Downgrading my Node version to v14-lts
- Modifying the `tools/assets/build.sh` script by adding `--legacy-peer-deps` to the end of line 28.

I think the the dependency list should be updated to use the latest versions of the conflicting packages.

**Comment by gonfsoto** [comment]
This setup works fine:
Prestashop: 8.04
node: v14.21.3
npm: 6.14.18


node 16.x didnt work

**Comment by hibatallahAouadni** [comment]
Hello @Maaaleeek 

Could you please check on your side if you still encounter the issue on `8.1.x` or `develop`? Cause it seems fixed, if you still have a problem with `make install` try `make assets`.
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Maaaleeek 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
