### ISSUE TITLE
En las estadísticas no aparece ningún dato de pedidos 

### ISSUE THREAD

**Issue by PipaDigital** [PrestaShop/PrestaShop#30829]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

No sales data appears in the statistics, although we do see it in orders

### Steps to reproduce

1. Steps to reproduce
2. go to statistics
3. Go to Sales and Orders
4. Choose the last 2 months, for example

### PrestaShop version(s) where the bug happened

1.7.6.5

**Comment by AureRita** [comment]
Hi @PipaDigital 

Thank you for your reporting but currently I can't follow your steps or anything else because It's not in english 

Please send your request in English because english is the norm on GitHub.

Thank you

**Comment by PipaDigital** [comment]
Describe the bug and add attachments
No sales data appears in the statistics, although we do see it in orders

Steps to reproduce
go to statistics
Go to Sales and Orders
Choose the last 2 months, for example

**Comment by HanaRebaiQA** [comment]
Hello @PipaDigital 

Thanks for the provided steps, but could you please provide us a screenshots or a screen-record to can see the data?
Maybe, because you did not have sales data for the last 2 months

For me i did not have data last 2 months and this is what i have : 
![image](https://user-images.githubusercontent.com/92912932/213461370-56dbfb45-372f-4531-b322-ad2118a01d62.png)

Thank You!

**Comment by florine2623** [comment]
Hello @PipaDigital ,

I can't reproduce your issue in PS 1.7.7.8 or later versions :
<img width="1437" alt="Screenshot 2023-01-25 at 18 06 43" src="https://user-images.githubusercontent.com/16019289/214631744-17df9f81-90ed-4197-b272-8bfa79236fda.png">

I tested with Sales and orders v2.0.0 and v2.1.0.

I'll close this issue to avoid clutter in the backlog.
Thanks!

**Comment by PipaDigital** [comment]
![Captura de pantalla 2023-01-31 a las 15 47 40](https://user-images.githubusercontent.com/122530833/215808454-ead253de-f1c1-4607-9390-338ed8a50997.png)

As you can see, it says we have only registered 134,16 euros of sales. But actually,  the sales for this period are about 6000 euros

**Comment by PipaDigital** [comment]
Hello? Can anyone help? What can we do to see the information?
