### ISSUE TITLE
Square brackets [] cutting off whole UTM during redirection

### ISSUE THREAD

**Issue by Xawier** [PrestaShop/PrestaShop#30821]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, during analyzing my UTM's tags I notice, that PrestaShop during URL rewrite redirection cut off whole UTM's which contain square brackets.

**Fast Example:**
https://peppeshoes.com/en/other-boots/838-14014-modello-darkerro.html?utm_campaign=[JI]%20Conversion%20-%20BOOTS%20[PL]&utm_content=[Zdjecie]%20Glany%201&utm_id=23852358552410789&utm_medium=cpc_Facebook_Desktop_Feed&utm_source=facebook_fb&utm_term=SZEROKO%20(PL)&fbclid=IwAR1KCQUie2K8E5vGne2fbCqXUiX6azeoEZMWy23IhSOMoBz-q1436eDRS1g

**Will redirect to:**
https://peppeshoes.com/en/mens-italian-leather-classic-shoes/838-6873-modello-rapterr.html?utm_id=23852358552410789&utm_medium=cpc_Facebook_Desktop_Feed&utm_source=facebook_fb&utm_term=SZEROKO+%28PL%29&fbclid=IwAR1KCQUie2K8E5vGne2fbCqXUiX6azeoEZMWy23IhSOMoBz-q1436eDRS1g

utm_campaing and utm_content contain "[" and "]" so the whole UTM is delating after redirection.

I notice that it takes place at the moment when the category or combination id is changing in the final URL.

### Expected behavior

All UTM should stay, no matter what they contain.

### Steps to reproduce

1. Take any url from your store
2. Change category, combination ID or friendly product name in url (stay original product id)
3. Add UTMs with square bracets to url, for example: ?utm_campaign=[PL]campaign
4. Hit enter, utm should disappear.

**Screen record**
https://www.dropbox.com/s/1kqk97lymfx5aux/Nagranie%20z%20ekranu%202023-05-26%20o%2018.16.58.mov?dl=0

### PrestaShop version(s) where the bug happened

1.7.x

**Comment by AureRita** [comment]
Hi @Xawier 

Thank for your report,
This issue is too technical for me, ping @PrestaShop/prestashop-core-developers, can someone please reproduce this issue ? 

Thanks

**Comment by Xawier** [comment]
@AureRita This case stays without an answer for 5 months so I am preparing for your video with an explanation: https://www.dropbox.com/s/1kqk97lymfx5aux/Nagranie%20z%20ekranu%202023-05-26%20o%2018.16.58.mov?dl=0

This is a big deal case for all performance marketers using PrestaShop. I will be glad if somebody can try to fix that ;-)

**Comment by Xawier** [comment]
Anyone?

**Comment by hibatallahAouadni** [comment]
Hello @Xawier 

Thanks for the screen record :raised_hands: :clap: it's quite clear!
I didn't manage to reproduce the issue with PS810, see the attached screen record below:

[issue_30821.webm](https://github.com/PrestaShop/PrestaShop/assets/23308427/a5c3ca07-c104-41a8-acc9-b613ab27bf26)

Please check and feedback.

Thanks!

**Comment by paulnoelcholot** [comment]
Hello @Xawier,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
