### ISSUE TITLE
Combination names missing in list

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#30830]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Combination names missing in list of product v2

### Expected behavior

names of attributes should be visible in each row

### Steps to reproduce

1. Go to product page v2, edit product with combinations
2. open combinations tab and see that combination names are missing as in screenshot
<img width="602" alt="Screenshot 2023-01-12 at 14 14 03" src="https://user-images.githubusercontent.com/31609858/212064846-2c69fa7b-3562-4e38-ba05-4afc282e3404.png">

### PrestaShop version(s) where the bug happened

develop

**Comment by AureRita** [comment]
Hi @zuk3975  ,

Thank for your report, I reproduce the issue with PrestaShop version develop and not with the version 8.0.0 as we can see on this video : 

[Untitled_ Jan 12, 2023 5_52 PM.webm](https://user-images.githubusercontent.com/100699445/212130417-c67de9c8-4005-43e7-be86-1f735bd86226.webm)


Nice catch ! It's a regression ! I'll add it to the patch backlog.

Thank you for your PR :rocket: 

Thank you
