### ISSUE TITLE
BO - Button Bulk actions is hidden in PPV2 combinations

### ISSUE THREAD

**Issue by djoelleuch** [PrestaShop/PrestaShop#30843]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Button Bulk actions is hidden

### Steps to reproduce

- FIRST CASE 
1. Go  to  Advanced Parameters >  New & Experimental Features > New product page - Single store 
2. Go to Catalog>Products>Create new product with combinations
3. Go to Combinations page >generate XX combinations >check the checkbox >select all results (XX) >SEE ERROR: the bulk actions button is hidden 

[Untitled_ Jan 12, 2023 3_48 PM (1).webm](https://user-images.githubusercontent.com/115152460/212118392-70cab8a6-686d-477b-bce1-440e299713b5.webm)

- SECOND CASE 
all the steps before > select result on this page (10) > then reselect all the results (XX) > SEE ERROR: it's not the same counts, still gives (10/XX)   combinations 
                                
![bug](https://user-images.githubusercontent.com/115152460/212117652-6e2e97f0-cf2b-46ee-9a37-651c31d59de2.png)

   

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4

**Comment by sallemiines** [comment]
Hi @djoelleuch 

I reproduce the issue with PrestaShop versions


**Develop NOK**

https://user-images.githubusercontent.com/31663369/212285017-c93d54cd-e57f-449d-98a9-f4421ebdbe41.mp4

![Products-•-develop](https://user-images.githubusercontent.com/31663369/212285057-d877a428-4032-4ab5-a75e-191490f21c18.png)

**PS 8.0.x / PS 8.0.0 / PS 8.0.1 OK** 


https://user-images.githubusercontent.com/31663369/212291024-47e8c79a-240b-4ec9-bb4d-3b926cb174a8.mp4

Nice catch ! It's a regression ! I'll add it to the patch backlog.
Thank you for your PR :rocket:
