### ISSUE TITLE
Import product with specific prices for sold don't work

### ISSUE THREAD

**Issue by pppplus** [PrestaShop/PrestaShop#30859]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I import product (existing products) with these columns only : 

Product ID    Name *    Discount percent    Discount from (yyyy-mm-dd)    Discount to (yyyy-mm-dd)    en solde 

When finished, I just receive a message that's indicated the rewriting-url is updated.
And nothing seems to change in products
No discount price added, with dates.

### Expected behavior

I just want to add specific prices, with discount percent, from date X to date Y

### Steps to reproduce

1. Go to import product
2. import product file
3. choose right colums
4. import

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.4

**Comment by pppplus** [comment]
Sorry, my big mistake !
I just forget to force ID !

**Comment by hibatallahAouadni** [comment]
Glad to hear :wink:
