### ISSUE TITLE
Shifting design for the Images in PPV2

### ISSUE THREAD

**Issue by hrostyk** [PrestaShop/PrestaShop#30852]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Please see the screenshots

![CleanShot 2023-01-13 at 10 14 33@2x](https://user-images.githubusercontent.com/7484618/212273289-5ce5a1a9-7136-479c-978e-b0a022950923.png)

![CleanShot 2023-01-13 at 10 12 48@2x](https://user-images.githubusercontent.com/7484618/212273319-dff5f493-05df-4213-b389-0d235620a4fd.png)

![CleanShot 2023-01-13 at 10 36 56@2x](https://user-images.githubusercontent.com/7484618/212275413-dbef7b54-278f-423d-8874-f1beee729b85.png)

### Expected behavior

<img width="1352" alt="CleanShot 2023-01-13 at 10 32 38@2x" src="https://user-images.githubusercontent.com/7484618/212274514-776779ee-9018-48d6-bc34-9b99a1e2934b.png">

### Steps to reproduce

1. Go to BO
2. Advanced Parameters -> New & Experimental Features
3. New product page - Single store -> Enable
4. Catalog -> Products
5. Add new Product
6. Add new images

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.4.33

**Comment by sallemiines** [comment]
Hello @hrostyk 

Thanx for reporting the issue.

I reproduce your issue with `PS8.0.0 `**NOK** 

![Products-•-800](https://user-images.githubusercontent.com/31663369/212295123-00c522b8-d45c-484a-a9a8-fa93bf3e2f0f.png)

and with` PS 8.0.1` **OK** 

![Products-801](https://user-images.githubusercontent.com/31663369/212295278-8316b41c-23e3-4a16-8a87-c9148a7a8227.png)

Thank you !

**Comment by kpodemski** [comment]
Hi @sallemiines 

If it works on 8.0.1, the Issue should be closed. Right?

cc @PrestaShop/qa-team

**Comment by hrostyk** [comment]
In 8.0.1 fixed only partially
