### ISSUE TITLE
Shifting design for the field Meta keywords

### ISSUE THREAD

**Issue by hrostyk** [PrestaShop/PrestaShop#30851]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Shifting design for the field Meta keywords on the pages: Categories, Seo and Urls, Pages, Brands and maybe other with Meta keywords field.

<img width="1014" alt="CleanShot 2023-01-13 at 09 26 38@2x" src="https://user-images.githubusercontent.com/7484618/212261989-c202786a-c06f-4907-8c14-84c3dc96c4ec.png">

### Expected behavior

The width of the field Meta keywords should not change from the number of keywords.

### Steps to reproduce

1. Go to BO
2. Catalog -> Categories
3. Add new Category
4. See Meta Keywords

### PrestaShop version(s) where the bug happened

1.7.8.8 and 8.0.0

### PHP version(s) where the bug happened

7.4.33

**Comment by sallemiines** [comment]
Hello @hrostyk 

Thanx for reporting the issue.

I reproduce your issue with : 

PS 1.7.7.8 **OK** 

![image](https://user-images.githubusercontent.com/31663369/212301534-644684cd-c40a-4685-8d22-c32e1caf332a.png)


PS 1.7.8.8 , PS 8.0.0 , PS 8.0.1 , develop **NOK** 

![image](https://user-images.githubusercontent.com/31663369/212299392-2e4a8ed0-59b6-42bd-bd81-60f4a5f5462c.png)

Thank you !

**Comment by florine2623** [comment]
Meta keywords are not used anymore on this page.
