### ISSUE TITLE
Trolley Overlap

### ISSUE THREAD

**Issue by LuigiMdg** [PrestaShop/PrestaShop#30858]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Since I updated to _1.7.8.8_, I keep getting these errors.
![image](https://user-images.githubusercontent.com/18232125/212309307-1749c682-2d5c-4934-99e9-756d972cdd22.png)
I guess customers are having trouble buying.....

### Expected behavior

That does not give errors

### Steps to reproduce

Install _PrestaShop 1.7.8.5_, then update to the latest version.

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

**Comment by kpodemski** [comment]
Hello @LuigiMdg 

There were no changes in the checkout mechanism between those versions. It has to be something specific to your store. 

You can ask the community for help using [Q&A category in the Discussions tab](https://github.com/PrestaShop/PrestaShop/discussions/categories/q-a).
