### ISSUE TITLE
Distribution API does not provide 8.0.1 modules list

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#30866]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Distribution API does not provide 8.0.1 modules list https://api.prestashop-project.org/modules/8.0.1

For 8.0.0 it is OK https://api.prestashop-project.org/modules/8.0.0

### Expected behavior

Distribution 1PI should provide 8.0.1 modules list https://api.prestashop-project.org/modules/8.0.1

### Steps to reproduce

See above

### PrestaShop version(s) where the bug happened

8.0.1

### If your bug is related to a module, specify its name and its version

distribution-api

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/distribution-api/pull/22

**Comment by matks** [comment]
When trying to fix this bug, we found other problems:

## Preproduction broken GitHub workflow

https://github.com/PrestaShop/distribution-api/actions/runs/3911500505/workflow

```
/ .github/workflows/ci-cd-integration.yml
Invalid workflow file
You have an error in your yaml syntax on line 53
```

Should be fixed by https://github.com/PrestaShop/distribution-api/pull/24

## Duplicate versions on preproduction

```
[{"version":"8.0.0","php_max_version":"8.1","php_min_version":"7.2.5","download_url":"https:\/\/preprod-api.prestashop-project.org\/assets\/prestashop\/8.0.0\/prestashop.zip","stability":"stable"},{"version":"8.0.0-beta.1","php_max_version":"8.1","php_min_version":"7.2.5","download_url":"https:\/\/preprod-api.prestashop-project.org\/assets\/prestashop\/8.0.0-beta.1\/prestashop.zip","stability":"beta"},{"version":"8.0.0-rc.1","php_max_version":"8.1","php_min_version":"7.2.5","download_url":"https:\/\/preprod-api.prestashop-project.org\/assets\/prestashop\/8.0.0-rc.1\/prestashop.zip","stability":"rc"},{"version":"8.0.1","php_max_version":"8.1","php_min_version":"7.2.5","download_url":"https:\/\/preprod-api.prestashop-project.org\/assets\/prestashop\/8.0.1\/prestashop.zip","stability":"stable"},{"version":"8.0.1","php_max_version":"8.1","php_min_version":"7.2.5","download_url":"https:\/\/preprod-api.prestashop-project.org\/assets\/prestashop\/8.0.1\/prestashop.zip","stability":"stable"},{"version":"8.0.1","php_max_version":"8.1","php_min_version":"7.2.5","download_url":"https:\/\/preprod-api.prestashop-project.org\/assets\/prestashop\/8.0.1\/prestashop.zip","stability":"stable"},{"version":"8.0.1","php_max_version":"8.1","php_min_version":"7.2.5","download_url":"https:\/\/preprod-api.prestashop-project.org\/assets\/prestashop\/8.0.1\/prestashop.zip","stability":"stable"},{"version":"8.0.1","php_max_version":"8.1","php_min_version":"7.2.5","download_url":"https:\/\/preprod-api.prestashop-project.org\/assets\/prestashop\/8.0.1\/prestashop.zip","stability":"stable"},{"version":"8.0.1","php_max_version":"8.1","php_min_version":"7.2.5","download_url":"https:\/\/preprod-api.prestashop-project.org\/assets\/prestashop\/8.0.1\/prestashop.zip","stability":"stable"},{"version":"8.0.1","php_max_version":"8.1","php_min_version":"7.2.5","download_url":"https:\/\/preprod-api.prestashop-project.org\/assets\/prestashop\/8.0.1\/prestashop.zip","stability":"stable"},
```

https://preprod-api.prestashop-project.org/prestashop

Should be fixed by https://github.com/PrestaShop/distribution-api/pull/23

**Comment by AureRita** [comment]
Hi @matks 

Thank for your report,
This issue is too technical for me, ping @PrestaShop/prestashop-core-developers, can someone please reproduce this issue ? 

Thanks

**Comment by eternoendless** [comment]
The problem is not on the module, but on [the service](https://github.com/PrestaShop/distribution-api/) that provides [this endpoint](https://api.prestashop-project.org/modules/8.0.1), where you should be getting a list of native modules like on [this one](https://api.prestashop-project.org/modules/8.0.0).

**Comment by matks** [comment]
Fixed by @atomiix

**Comment by LEOMARINO** [comment]
Hola, estoy teniendo el mismo problema en PS 8.0.2 PHP 8.

![image](https://user-images.githubusercontent.com/61874013/229315946-e41fe202-ae47-4c85-927d-c3288be92ca8.png)
