### ISSUE TITLE
error Facebook configuración

### ISSUE THREAD

**Issue by auxfajitex** [PrestaShop/PrestaShop#30862]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

It won't let me connect to my facebook account

### Expected behavior

I want to be connected to my facebook account on prestashop 

### Steps to reproduce

- install prestashop facebook plugin
- enter registration data
- select page and pixel
- synchronize catalog
- agree

### PrestaShop version(s) where the bug happened

1.7.7.5

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

PS Facebook V.1.22.

**Comment by sallemiines** [comment]
Hello @auxfajitex ,

Please send your request in English. English is the norm on GitHub.

Thank you

**Comment by auxfajitex** [comment]
It won't let me connect to my facebook account
Steps
install prestashop facebook plugin
enter registration data
select page and pixel
synchronize catalog
agree

PrestaShop version(s) where the bug happened
1.7.7.5

PHP version(s) where the bug happened
7.3

If your bug is related to a module, specify its name and its version
PS Facebook V.1.22.

**Comment by AureRita** [comment]
Hi @auxfajitex 

Thank you for your report. Can you give us a video to see your issue ? because currently I managed to log in to my facebook account. ( with the video, don't forget to hide your ID ) 

Waiting for your feedback

**Comment by florine2623** [comment]
Hello @auxfajitex ,

Please contact directly the developer of the module here :
<img width="1202" alt="Screenshot 2023-01-18 at 14 20 33" src="https://user-images.githubusercontent.com/16019289/213182224-0d919339-0cff-4d51-bdcd-31e891bf126c.png">

This issue is not related to the core. So I will close it to avoid backlog.
Thanks!
