### ISSUE TITLE
Order items are returnable while order has Shipped status and this status is set not as a Delivery status

### ISSUE THREAD

**Issue by alisamie97** [PrestaShop/PrestaShop#30872]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When order has status of "Shipped", by default customer can return products in order. I checked the current demo and its true.
Then I checked the back office of the order status settings and found that there is a flag for "Is Delivery?" which is what I need for this scenario.
Then I disabled this flag, and checked my front office order details page. Unfortunately I faced the issue again and the return form is visible to customer, however the "Shipped" status is set as a NOT DELIVERY status.
Here are some screen shots
![image](https://user-images.githubusercontent.com/23106000/212536259-14a0af20-c14b-4e01-bf6a-2dc892d534c1.png)
![image](https://user-images.githubusercontent.com/23106000/212536268-660ff104-bd4e-41d9-8497-8782a93477cf.png)

### Expected behavior

When order status of any kind has the flag of "Delivery" as disabled, we show see this as a NOT DELIVERED status. Therefore we should see that the return form does not work too.

### Steps to reproduce

1. Go to back office, the order status settings
2. Disabled the "Delivery" flag for "Shipped" status
3. Go to front office and place an order
4. Go to back office and update the related order to "Shipped" status
5. Go to front office and reload the order details page
6. You will see the return form available

### PrestaShop version(s) where the bug happened

1.7.7.8 - 1.7.8.8

### PHP version(s) where the bug happened

7.4

**Comment by AureRita** [comment]
Hi @stifler97 ,

Thank you for your report. I reproduce the issue with PrestaShop version 1.7.8.8, as you can see : 

[Untitled_ Jan 16, 2023 3_47 PM.webm](https://user-images.githubusercontent.com/100699445/212706300-0e728ffc-0fd6-4805-bba7-1c2558f95fcc.webm)

I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks

**Comment by alisamie97** [comment]
Hi @AureRita 
actually this is not a bug, but a feature
see, prestashop code in this scenario works fine
the issue is in the logic
lets review our case:
1. we have an online shop, with cash payment on delivery
2. customer places an order, and we send it to customer
3. customer wants to return some items of the order and the package is still on its way

doesn't make sense, right?

they must receive at first, check them, and then select some items for return

i have fixed it with an override

i will do the fix as a feature in core and add it here
