### ISSUE TITLE
Archive ps_buybuttonlite

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#30888]
Archive the module on GitHub and edit the README accordingly 

"This repository has been archived, it’s no longer maintained but you still can fork it if you need it."

**Comment by jolelievre** [comment]
The repository https://github.com/PrestaShop/ps_buybuttonlite has been archived

**Comment by Hlavtox** [comment]
@jolelievre remove it also from here please 🙏 https://github.com/Prestashop/PrestaShop-modules

**Comment by MatShir** [comment]
I don't even know the purpose of the repo, ps_welcome is archived as well but still on the list

**Comment by MatShir** [comment]
The repo is used by PrestaShop SA, we won't touch it for now. I consider this subject done
