### ISSUE TITLE
Google Analytics native module, doesn't work with Prestashop 1.7.8.7

### ISSUE THREAD

**Issue by besbog** [PrestaShop/PrestaShop#30884]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Native module Google Analytics v4.1.2 de PrestaShop has never worked in my website. 
I fullfiled the tracking ID and after 2 o 3 months still doesn't work because is not tracking nothing. Is there any error or another way to use it that I am missing?
Thank you.

### Expected behavior

Track events from my website with Google Analytics

### Steps to reproduce

1. Google Analytics native module installed in my Prestashop
2. Tracking ID configured in Google Analytics module
3. Nothing else happens

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

https://addons.prestashop.com/es/informes-estadisticas/27138-google-analytics.html#overview_description

**Comment by Hlavtox** [comment]
This module works correctly for years, are you sure you are using universal analytics? This module doesn't support GA4 yet.

**Comment by besbog** [comment]
Oh! I was using GA4, so it's solved. Will this module support GA4 starting on July, 2023? When UA won't work anymore. Thank you.

**Comment by AureRita** [comment]
Hi @besbog 

As you said it, this issue is solved so I will close it. 

Thank you @Hlavtox of your intervention to explain where is the problem
