### ISSUE TITLE
Dominio bloqueado

### ISSUE THREAD

**Issue by DannaCespedes** [PrestaShop/PrestaShop#30893]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Tengo problemas con las cuentas de correo electrónico, nuestro dominio no está respondiendo a los servidores del housting.

### Expected behavior

Que los correos y la página web funcionen.

### Steps to reproduce

Ingresar a la página web.

### PrestaShop version(s) where the bug happened

1.7.5.2

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

No

**Comment by hibatallahAouadni** [comment]
Hello @DannaCespedes 

Please send your request in English. English is the norm on GitHub.
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must fill the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thank you
