### ISSUE TITLE
Docs for V8 is actually the docs of V1.7 and nothing is working

### ISSUE THREAD

**Issue by Schiocco** [PrestaShop/PrestaShop#30890]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The docs at https://devdocs.prestashop-project.org/8/modules/payment/ are actually a copy of the v 1.7, and nothing is working, including the payment module example.
Very unprofessional. 

### Expected behavior

The docs for the V8

### Steps to reproduce

Visit https://devdocs.prestashop-project.org/8/modules/payment/

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment]
@Schiocco What is not working? If the logic is the same for both versions, why the pages would be different? 😄

If you think it's unprofessional, you can always improve it here - https://github.com/PrestaShop/docs/edit/8.x/modules/payment/_index.md ❤️

**Comment by Schiocco** [comment]
The payment module example is not working on V8 so I assume the logic is not the same. Please try to load the module.

Regards

**Comment by Schiocco** [comment]
Also, in the docs, all references are showing V 1.7 which is wrong. At least the texts must be partially updated.

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/product-team & @PrestaShop/prestashop-core-developers

**Comment by thomasnares** [comment]
Can be closed here, i forwarded it to prestashop/docs 👍

**Comment by Schiocco** [comment]
Great, thanks!





[image: SCHIOCCO] <https://schiocco.com/>

**Comment by dorian-b** [comment]
this is closed, but I opened an issue related to it:
https://github.com/PrestaShop/docs/issues/1629
Ping @PrestaShop/product-team & @PrestaShop/prestashop-core-developers

**Comment by thomasnares** [comment]
Refresh of Payment Module page has been done (https://github.com/PrestaShop/docs/pull/1759), and example module (https://github.com/PrestaShop/paymentexample) has been tested againts PS8.0 : it's working as intented.
