### ISSUE TITLE
Wishlist block display each added product 3 times

### ISSUE THREAD

**Issue by Prestatill** [PrestaShop/PrestaShop#30904]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have a question about Wishlist block Module Developed by PrestaShop v2.1.2 (download from this [link](https://addons.prestashop.com/en/undownloadable/9131-wishlist-block.html)).
I have installed it and it is almost working but I have a bug that I can't solve.
When I consult one of the wish list, each product added to the list is displayed 3 times. I tried to reset the module without success.

![image](https://user-images.githubusercontent.com/23308427/212914981-9a78fb00-986a-42a8-bd0e-4f16175bf0ad.png)

### Expected behavior

Each product added to the list must be displayed once

### Steps to reproduce

1. FO>Add a product to my wishlist
2. FO>Account>Wishlist block
3. Access to my wishlist 
4. See error > every added product is displayed 3 times

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

Wishlist block v2.1.2

**Comment by sallemiines** [comment]
Hello @Prestatill 

Thanx for reporting the issue.

Following your steps I did'nt manage to reprodue your issue ! 

![Module-manager-•-1787 (5)](https://user-images.githubusercontent.com/31663369/212935571-b2ffc46d-4d28-4d32-992f-105c07ced7c0.png)

![image](https://user-images.githubusercontent.com/31663369/212935694-91032222-5584-4584-9835-a88319e22523.png)

I think it's related to some cache , could you please  disable the cache in your shop and check ? 

Waiting for your feedback ! 

Thank you !

**Comment by Prestatill** [comment]
Hi @sallemiines 
Thank a lot but it doesn't change anything.

In PrestaShop:
I have disabled caches completely and cleared the cache.
I reset the module.
I uninstalled and reinstalled the module.
In the browser:
I cleared the caches.
I tried another browser.

Do you have another idea?
Thanks

**Comment by sallemiines** [comment]
thanx for your feedback @Prestatill 

Unfortunately there is no other checks to do !  
It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
We will close this issue.

Please note that you can always create a new one if further information pops up.

Thank you

**Comment by HellYacht** [comment]
Same issue with fix : https://github.com/PrestaShop/PrestaShop/issues/27016
