### ISSUE TITLE
[Classic theme] Quantity form unstable structure

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/PrestaShop#30911]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Feedback from @MhiriFaten: https://github.com/PrestaShop/ps_linklist/pull/155#pullrequestreview-1250294891

![image](https://user-images.githubusercontent.com/111756615/212704509-da5785ae-a738-48d8-908d-3c05149e8dde.png)

When product columns are enabled and/or simply viewing product page on smaller screens, squeezed main content cause quantity form to lose structure.

### Expected behavior

Quantity form should look the same under any circumstances and buttons next to it should wrap into new line if needed

### Steps to reproduce

1. Follow the steps from #30802
2. Optionaly use smaller screen size
3. Check the structure of quantity form

### PrestaShop version(s) where the bug happened

1.7, 8.x

### PHP version(s) where the bug happened

7.x, 8.x

### If your bug is related to a module, specify its name and its version

classic-theme

**Comment by Hlavtox** [comment]
I think we will solve this by giving classic a bye bye :D

**Comment by sallemiines** [comment]
Hello @SharakPL 
Thanx for reporting the issue.

Following your steps , unfortunately I didn't manage to reproduce your isssue 

![Link-List-•-1787](https://user-images.githubusercontent.com/31663369/212919305-eb7768a7-0c76-4bb7-b71f-8dff1236b3b2.png)

![Capture-d’écran-du-2023-01-17-15-01-21-png-1381×682-](https://user-images.githubusercontent.com/31663369/212919307-d09de86d-23e9-4d98-a059-b2b65ce51eaf.png)

Did I miss smthg ? and could you please provide us the version of the module  ps_linklist ? 
Please check & feedback ! 

Thank you !

**Comment by Hlavtox** [comment]
@sallemiines You didn't enable left & right column layout for product page. Also, maybe it happens only in french.

**Comment by SharakPL** [comment]
Yes, it also depends on the language. Add to cart button in french is longer and it seems quantity form and buttons are forced to fill only 1 line. It makes them bleed outside main column margins
![obraz](https://user-images.githubusercontent.com/5007456/212928059-9a35820b-cebb-4617-985b-cf5948d97fc3.png)
