### ISSUE TITLE
with the module ps_linklist or List of links, when I put more than 2 is grouped

### ISSUE THREAD

**Issue by unclickifet** [PrestaShop/PrestaShop#30928]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

con el modulo ps_linklist o Lista de enlaces, cuando pongo mas de 2 se agrupa, he mirado todo y no encuentro solucion, he desactivado otros modulos del footer etc, borrado cache y sigue igual.

https://prnt.sc/bEcrF3-Tl9qS

### Expected behavior

deberia expandirse como hacia al principio

### Steps to reproduce

Se queda descuadrado

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4.30

### If your bug is related to a module, specify its name and its version

ps_linklist

**Comment by kpodemski** [comment]
First of all, please use English to describe your issues. Secondly, this error probably comes from your theme, not the module itself. You can contact theme support to help you solve it.

**Comment by unclickifet** [comment]
Helo @kpodemski 

theme is classic of prestashop, with the module ps_linklist or List of links, when I put more than 2 is grouped, I have looked at everything and I can not find a solution, I have disabled other modules of the footer etc, deleted cache and still the same.

**Comment by kpodemski** [comment]
I suggest creating a new Discussion [there](https://github.com/PrestaShop/PrestaShop/discussions/categories/q-a), so you can share the URL to your store and discuss the technical possibility of doing that. It doesn't look like a bug.
