### ISSUE TITLE
Back office css / js cache busting

### ISSUE THREAD

**Issue by darkWolf-PR** [PrestaShop/PrestaShop#30925]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Most of the time after doing 1-click update and something changed in back office system CSS / JS files, they do not get re-loaded by browser, no matter how many times u try CTRL+F5. So after every update in any eshop, I end up with logging JS errors and TinyMCE not showing anywhere. There is missing cache busting version info within CSS / JS file links.

Happens through pretty much any version of 1.7, but depends on actual changes in CSS / JS files. If there is no change, u won´t get js errors nor bad styling.

Usually, I have to open browser dev tools, set them to use no cache at all, reload page to get browser to load updated files. Then turn it off and it start working normally. No problem with me, but it´s hard to describe to shop owners for who I´m building e-shops...

### Expected behavior

Something like:

<script type="text/javascript" src="[/admin17sue/themes/default/public/bundle.js](view-source:https://www.suestyle.cz/admin17sue/themes/default/public/bundle.js?v=1788)"></script>

### Steps to reproduce

1. Run 1-click update with browser set as normal, awerage user.

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @darkWolf-PR ,

I tried an upgrade from 1.7.8.7 to 1.7.8.8, with autoupgrade v4.15.0. I have no issue with CSS nor JS.

What version did you upgrade from and to ? Version of autoupgrade ?
Can you send a screenshot of your issue ?

**Comment by kpodemski** [comment]
There are indeed some scripts that are loaded without a query string indicating the core version. That would be a good improvement!

So, it's not really a bug. If you wish to see this improvement in the core, please share your idea [here](https://github.com/PrestaShop/PrestaShop/discussions/categories/ideas). Thank you ❤️

**Comment by darkWolf-PR** [comment]
> Hello @darkWolf-PR ,
> 
> I tried an upgrade from 1.7.8.7 to 1.7.8.8, with autoupgrade v4.15.0. I have no issue with CSS nor JS.
> 
> What version did you upgrade from and to ? Version of autoupgrade ? Can you send a screenshot of your issue ?

Sorry, no screenshots, I did not make any and I probably won´t be updating other eshop for a few weeks at least. 

Version of autoupgrade was latest - 4.15.0. Version of eshop, this one was 1.7.6.8 or .9. 

Issue is simple, after reload, even with CTRL + F5, browser loads old scripts and js bugs out(and most notable problem is usually TinyMCE editor not loading, leaving only empty textareas. I have no idea why id does not reload the scripts with CTRL+F5 - browser I´m using is Firefox for Windows, actual, always updated version. 

It does not happen if I open the eshop in other browser, because, of cause, there are no old scripts, so the new ones are loaded here.

No idea if the problem is somehow connected to Firefox, but adding cache busting query string would definitely removed the issue and would be perfectly logical.
