### ISSUE TITLE
ps_linklist se agrupa

### ISSUE THREAD

**Issue by unclickifet** [PrestaShop/PrestaShop#30927]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

el footer no se expande, y el modulo me agrupa, todo, he desactivado varios modulos del footer y lo sigue agrupando.

https://prnt.sc/Jz4cFPq6kjs2

### Expected behavior

Deberia expanderse por todo el footer

### Steps to reproduce

añades enlaces y se agrupan

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4.30

### If your bug is related to a module, specify its name and its version

ps_linklist

**Comment by kpodemski** [comment]
Hello,

First of all, please use English to describe your issues. Secondly, this error probably comes from your theme, not the module itself. You can contact theme support to help you solve it.
