### ISSUE TITLE
FO - Blockreassurance - An error warning is displayed on every page related to the displayed blocks when adding a new block reassurance with an image icon

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#30932]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

This issue is previously reported [here](https://github.com/PrestaShop/blockreassurance/pull/473#pullrequestreview-1228840227) 

An error warning is displayed on every page related to the displayed blocks when adding a new block reassurance with an image icon

**PS1778 with blockreassurance v5.0.0 : OK** :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/92912932/213206141-1cd9f4a7-7b56-4a80-8ac5-33ed61e3f46b.png)

**PS1778 with blockreassurance v5.1.1 : NOK** :x: 
![image](https://user-images.githubusercontent.com/92912932/213205857-bdab1a20-1873-4a2c-8d80-093e706d9254.png)

https://user-images.githubusercontent.com/92912932/213211221-edd12e83-f9f6-4d9f-aeaa-ad85e50b95a3.mp4

**PS1788 with blockreassurance v5.1.1 : NOK** :x: 

**PS8.0.0 with blockreassurance v5.1.1 : NOK** :x: 
![image](https://user-images.githubusercontent.com/92912932/213206533-4f035f42-09ec-40ab-8442-b92ea1cea126.png)

![image](https://user-images.githubusercontent.com/92912932/213206574-4335cd0a-0359-41d8-8313-ca7ea455ef65.png)

![image](https://user-images.githubusercontent.com/92912932/213206603-f9594d6d-298c-45f8-9a44-4d964749a565.png)

**PS8.0.1 with blockreassurance v5.1.1 : NOK** :x: 
![image](https://user-images.githubusercontent.com/92912932/213206206-e75b49bb-5c4b-4271-9a36-d455e90ad7ad.png)

https://user-images.githubusercontent.com/92912932/213206652-2700f991-ca3c-42e7-8894-a7baf5403efd.mp4

**So, it's a regression on the module v5.1.1**

### Expected behavior

No error is displayed in FO related to blockreassurance when adding a new block with an image icon

### Steps to reproduce

1. Install PS1.7.8.8 / PS8.0.0 OR PS8.0.1
2. Go to modules > Blockreassurance v5.1.1
3. Click on Configure
4. Add a new block by clicking on `+` the icon
5. Add an image as an icon and fill the fields
6. Click on Save
7. Activate the Block
8. Click on Display > Select the sections when displaying the blocks
9. Go to Performance > Enable debug mode
10. Go to FO
11. See error >> The error warnings are displayed!

### PrestaShop version(s) where the bug happened

1.7.7.8 & 1.7.8.8 & 8.0.0 & 8.0.1

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

blockreassurance v5.1.1

**Comment by leemyongpakvn** [comment]
@HanaRebaiQA I see no problem with PS 1.7.8.5 and a fresh install of blockreassurance 5.1.1 (totally remove old one 5.0.0, then install 5.1.1). FYI, the issues was reported since Apr 2022 by @khouloudbelguith in #28264, and @matks tried to fix it by PrestaShop/blockreassurance/pull/393

Here is their WARNING in Steps to reproduce:
**bug happens only if store is installed in a subfolder**

**Comment by HanaRebaiQA** [comment]
Hello @leemyongpakvn 

Thanks for your feedback. This issue #28264 is already fixed by this PR [#blockreassurance/473](https://github.com/PrestaShop/blockreassurance/pull/473) (see this [comment](https://github.com/PrestaShop/blockreassurance/pull/473#pullrequestreview-1251923112))
But this current issue is still present.

**Comment by florine2623** [comment]
I'm using PS 9.0.0 and Customer Reassurance v5.1.4, the issue is fixed.

https://github.com/user-attachments/assets/3acf3baa-3c99-4500-a94c-7321fba684e7
