### ISSUE TITLE
Awareness on deactivation of jpg image type

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#30944]
### **User story**
As a merchant, I want to be able to edit the image type without risk 

### **Specs**

Now, the user can select the image format between JPEG, PNG, WebP and AVIF. Since, PrestaShop has always used jpg extension at the image generation, even for other format like PNG or WebP, we need to be careful of the extension used in the image generation.  
So to avoid breaking modules, JPG extension will be kept for JPG as default format.

**- List of checkboxes**

Image format:
- JPEG
- PNG
- WebP 
- AVIF 

**Acceptance test**

When I enable the feature flag 
Then JPEG format is selected by default and can't be unchecked

**Comment by Hlavtox** [comment]
Files with JPG extension are also used throughout the backoffice, so that needs to be sorted first, if you want to allow disabling it. 👍
