### ISSUE TITLE
If demo products are deactivated during installation this causes a language error

### ISSUE THREAD

**Issue by DEL-TRONIK** [PrestaShop/PrestaShop#30940]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If demo products are deactivated during installation this causes a language error.

For example if I select the French language during prestashop 1.7.8.8 installation, I get a mixture of French and English (on the online store but also in the administration interface), Here are some screenshots:

![1](https://user-images.githubusercontent.com/104136464/213269143-6480d4e3-9c7b-4f6c-ac29-39ad148a99ee.png)

![2](https://user-images.githubusercontent.com/104136464/213269146-581689e8-6177-4306-aa9c-7d265a557aaa.png)

### Steps to reproduce

1. Make a PrestaShop installation
1. Select a language that is not English (For example French)
1. Deactivating demonstration products
1. You will get a mixture of English and French

### PrestaShop version(s) where the bug happened

1.7.8.8

**Comment by kpodemski** [comment]
I'm not sure if it's related to the demo products. Have you tried with demo products, and it's the same result?

Have you tried visiting the Translations page and simply updating the language translation?

**Comment by HanaRebaiQA** [comment]
Hello @DEL-TRONIK 

Thanks for your report.
I was able to reproduce your issue using the same steps to reproduce. But, you need to update languages to resolve this problem as you can see here : 

1. Go to BO > IMPROVE > International > Translations
2. Click on `Add or update a language` a few times
3. The problem of translation is resolved


https://user-images.githubusercontent.com/92912932/213421402-20fe4c4f-0552-4e57-9834-24ce31f4b0dd.mp4

I'll close the issue. Don't hesitate to open new tickets when needed!

Thank You!

**Comment by DEL-TRONIK** [comment]
@kpodemski Yes the bug appears only when deactivating demo products during installation (and that you choose another language than the default).

I created a subject on the forum here (sorry it's in French): https://www.prestashop.com/forums/topic/1072700-ps-1788-erreur-langue-installation/

Another user indicates the same error when installing PS 8.0.1.

@HanaRebaiQA Yes that resolved the problem. Thanks.

**Comment by HanaRebaiQA** [comment]
You are welcome !
