### ISSUE TITLE
FO - Combination option not added in the select

### ISSUE THREAD

**Issue by guestisp** [PrestaShop/PrestaShop#30955]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Let's assume you have 2 combinations:

- color [white, red] & size [1, 2, 3]

white is available in 1 only
red is available in 2, 3 only

When you choose "red", the size select removes the option "1", as expected.
But then you are unable to choose "white" because the "1" option in size is not present and not re-added, thus is switching back to red.

### Steps to reproduce

wrote above.

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.1

**Comment by HanaRebaiQA** [comment]
Hello @guestisp 

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template and provide clear and concise steps to reproduce the bug**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you!
