### ISSUE TITLE
 Relaunch basket HTTP 500 error

### ISSUE THREAD

**Issue by alieb2b** [PrestaShop/PrestaShop#30950]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, 

I'm trying to use the native module "customer recovery". When I put the cron URL I get an http 500 error. I changed the module name to ps_reminder and it still doesn't work. 

Would you have a solution for the cron task to work and for me to be able to do cart relaunches? 

Thanks in advance! 

![Capture](https://user-images.githubusercontent.com/122890308/213480005-edb5b96c-323b-401b-9d49-af5d2069a6da.JPG)

### Steps to reproduce

1. I go to the module
2. I copy the cron url in the search bar
3. I get a 500 error page

### PrestaShop version(s) where the bug happened

1.7.6.5

**Comment by HanaRebaiQA** [comment]
Hello @alieb2b 

Thanks for your report.
Please send your request in English. English is the norm on GitHub.
And could you please provide us a screenshot to can reproduce it clearly ?

Thank You!

**Comment by Hlavtox** [comment]
@alieb2b Enable debug mode in Performance section and try again, it will show you the error.

**Comment by alieb2b** [comment]
@Hlavtox I did what you asked. I put the debug mode on. I got this message: 
"
Fatal error: Uncaught Error: Call to undefined function idn_to_ascii() in /home/inorea/repoinorea/classes/Mail.php:901 Stack trace: #0 /home/inorea/repoinorea/classes/Mail.php(323): MailCore::toPunycode('c.pasquis@b2bon...') #1 /home/inorea/repoinorea/modules/ps_reminder/ps_reminder.php(248): MailCore::send(1, 'followup_1', 'Your cart and y...', Array, 'c.pasquis@b2bon...', '=?UTF-8?B?Y2hsb...', 'contact@inorea....', 'Inorea', NULL, NULL, '/home/inorea/re...') #2 /home/inorea/repoinorea/modules/ps_reminder/ps_reminder.php(639): Ps_Reminder->cancelledCart() #3 /home/inorea/repoinorea/modules/ps_reminder/cron.php(35): Ps_Reminder->cronTask() #4 {main} thrown in /home/inorea/repoinorea/classes/Mail.php on line 901
"
I corrected exactly what was written but it didn't change anything....

**Comment by Hlavtox** [comment]
@alieb2b You don't have required `intl` PHP extension activated on your server. Activate it and it will start to work. :-)

**Comment by alieb2b** [comment]
@Hlavtox I just installed it and I still get the same error message
