### ISSUE TITLE
[PHP Notice #8] Undefined index: description

### ISSUE THREAD

**Issue by dax84** [PrestaShop/PrestaShop#30974]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, I have an unexpected issue with prestashop 1.7.8.7 - php version 7.3
I've created a webservice to communicate a software. When I test the key, I have 3 errors:
errors |  
-- | --
0 |  
code | 5
message | "[PHP Notice #8] Undefined index: description (/mywesite.com/classes/webservice/WebserviceOutputBuilder.php, line 331)"
1 |  
code | 5
message | "[PHP Notice #8] Undefined index: description (/mywebsite.com/classes/webservice/WebserviceOutputBuilder.php, line 331)"
2 |  
code | 5
message | "[PHP Notice #8] Undefined index: description (/mywebsite.com/classes/webservice/WebserviceOutputBuilder.php, line 331)"

I've checked on another website with prestashop 1.7.6, no issues. And I've checked on another website with the same version (1.7.8.7), same problem. Any ideas?

### Steps to reproduce

Go to advanced parameters
Webservices
Create a key
then go to https://MYWEBSITE.com/api/?ws_key=MYAPIKEY&output_format=JSON
See bug

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Hello @dax84 

Could you please more details like which method you use to call the API and did you use Postman or the navigator?
Please provide a screen record :pray: Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @dax84 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
