### ISSUE TITLE
Uncaught Exception in Debug Mode with Prestashop Metrics enabled

### ISSUE THREAD

**Issue by KarmCraft** [PrestaShop/PrestaShop#30978]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I'm experiencing following behavior. Shop works normal in normal mode. When I try to enable Debug Mode, it throws 2 Twig/Symfony exceptions, resulting in a 500 status both in front and backend. The error seems related to the first party module Metrics, which I have enabled.

Exception 1
![image](https://user-images.githubusercontent.com/15261206/213693784-049dcb12-cbcc-4f5f-abdc-48ed2c5875dc.png)

Exception 2
![image](https://user-images.githubusercontent.com/15261206/213693844-1f7c2990-a40d-4163-a121-c7ba9914e04e.png)

### Expected behavior

Debug Mode should work normal

### Steps to reproduce

Have Metrics module enabled, connected and synchronized ?
Enable Debug Menu

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

Metrics 3.5.4

**Comment by sallemiines** [comment]
Hello @KarmCraft 

Thans for reporting the issue.
Unfortunately, the metrics module is not native module :disappointed: 
So, could you please contact the modules developers on Addons to fix the issue :pray: 

Thank you !

**Comment by KarmCraft** [comment]
> Hello @KarmCraft 
> 
> Thans for reporting the issue.
> Unfortunately, the metrics module is not native module :disappointed: 
> So, could you please contact the modules developers on Addons to fix the issue :pray: 
> 
> Thank you !

Ok but you could have left the reproduction video.
