### ISSUE TITLE
Unable to generate a URL for the named route "admin_addons_login"

### ISSUE THREAD

**Issue by mxmus** [PrestaShop/PrestaShop#30979]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After updating PrestaShop to 8.0.1 from 1.7.8.8 I have message "Unable to generate a URL for the named route "admin_addons_login" as such route does not exist." on backoffice dashboard.

![Screenshot_13](https://user-images.githubusercontent.com/10479502/213694629-92b1dd2f-e892-4b57-b5d0-480f9230d916.png)

After some researching I found that problem is in module psaddonsconnect.

PrestaShop 1.7.8.8 has following files
src\PrestaShopBundle\Resources\config\routing\admin\improve\modules\addons.yml  content:
```
admin_addons_login:
    path:     /login
    methods:  [POST]
    defaults:
        _controller: PrestaShopBundle:Admin/Addons:login
...

```
src\PrestaShopBundle\Resources\config\routing\admin\improve\modules\\_modules.yml 
```
_addons:
    resource: "addons.yml"
    prefix: /addons/
...

```

PrestaShop 8.0.1 does not have including addons.yml in _modules.yml but have the same addons.yml.

Now I rename psaddonsconnect folder to _psaddonsconnect and message does not appear.

### Expected behavior

Prestashop 8.0.1 should not have error message "Unable to generate a URL for the named route "admin_addons_login" as such route does not exist." on backoffice dashboard.

### Steps to reproduce

1. Update PrestaShop from 1.7.8.8 to 8.0.1 using 1-Click Upgrade
2. Go to backoffice dashboard

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

7.4.20

### If your bug is related to a module, specify its name and its version

psaddonsconnect

**Comment by paulnoelcholot** [comment]
Hello @mxmus,

I have tested your issues and I don't reproduce it :/

Could you give me more information?

Thanks!

**Comment by mxmus** [comment]
Hello @paulnoelcholot 
[psaddonsconnect.zip](https://github.com/PrestaShop/PrestaShop/files/10474941/psaddonsconnect.zip)
I've attached psaddonsconnect folder.

But I see psaddonsconnect (Tips & Updates Module) is not native PrestaShop module and it has compatibility From V1.6.0.4 to V1.7.8.8 on addons.prestashop.com. So maybe that's why the problem exists.

**Comment by florine2623** [comment]
Have you tried disabling the module ?

You should not have this kind of error as the software and the company are separated in PS 8.0.0.
https://github.com/PrestaShop/PrestaShop/issues/28771

**Comment by mxmus** [comment]
@florine2623 
Just have tried. Got the same message.
Only renaming folder "psaddonsconnect" works.

**Comment by florine2623** [comment]
As you don't need this module for PS 8.0.0 you can delete it and/or rename it.

I'll close this issue, as @paulnoelcholot and myself couldn't reproduce this issue anyway.

**Comment by PresDiego** [comment]
Hi, I've the same problem... please to reopen this issue.
I've had problem with the module ps_mbo too: After to change the name I'm able to access to the backend, but there are a lot of mistake.

**Comment by PresDiego** [comment]
I add that probably in the PS upgrade a lot of old modules (not native) are not disactivated.

**Comment by PresDiego** [comment]
@florine2623 I'm not logged to addon marketplace in the backend. maybe you are not able to reproduce this issue for this reason?

**Comment by Vargash** [comment]
> As you don't need this module for PS 8.0.0 you can delete it and/or rename it.
> 
> I'll close this issue, as @paulnoelcholot and myself couldn't reproduce this issue anyway.

If the module is not needed anymore, how are we supposed to upgrade addons.prestashop.com modules?

**Comment by mack94** [comment]
Confirm, same error after update from 1.7.8.8 to 8.0.0 and later 8.0.1.

**Comment by jose73wrc** [comment]
Hi, I have the same problem.
on ps 8.0.1 and beta 8.0.2
when you enter the Backoffice and click on the start button.

**Comment by mdrbx** [comment]
I was able to handle this matter with a little trick.

Problem comes from psaddonsconnect.php and specially hookDashboardZoneTwo function that tries to generate a route that Symfony core cannot produce. I've just added an error handler.

Anyway here is the code for handling at least the problem :
`

    public function hookDashboardZoneOne($params)
    {
        
        $this->loadAsset();

        $addonsConnectionUrl = '';
        $logged_on_addons17 = 0;

        if (true === version_compare(_PS_VERSION_, '1.7', '>=')) {
            global $kernel;

            //router to get the addons URL
            $instance = $kernel->getContainer();
            $router = $instance->get('router');

            if (isset($_COOKIE['username_addons'])) {
                $logged_on_addons17 = 1;
            }

            try {
                $addonsConnectionUrl = $router->generate('admin_addons_login');
            } catch (Exception $e) {
                $addonsConnectionUrl = '';
            }

            if (isset($_COOKIE['username_addons'])) {
                $logged_on_addons17 = 1;
            }
        }

        // API DATA
        $weekAdvice = new WeekAdvice();
        $weekAdviceData = $weekAdvice->getWeekData($this->context->language->iso_code);
        $advice = !empty($weekAdviceData['advice']) ? $weekAdviceData['advice'] : false;
        $currentLangIsoCode = $this->context->language->iso_code;
        $link_advice = false;
        if (!empty($weekAdviceData['link'])) {
            $link_advice = $weekAdviceData['link'] . "?utm_source=back-office&utm_medium=AddonsConnect&utm_campaign=back-office-$currentLangIsoCode&utm_content=tipofthemoment";
        }

        // assign var to smarty
        $this->context->smarty->assign(array(
            'img_path' => $this->img_path,
            'ps_version' => (bool) version_compare(_PS_VERSION_, '1.7', '>='),
            'advice' => $advice,
            'link_advice' => $link_advice,
            'url_connexion' => $addonsConnectionUrl,
            'logged_on_addons17' => $logged_on_addons17,
            'practical_links' => $this->practicalLinks(),
            'currentLangIsoCode' => $currentLangIsoCode,
        ));

        return $this->context->smarty->fetch($this->local_path . 'views/templates/hook/dashboard_zone_one.tpl');
    }
   `

**Comment by kmorgen** [comment]
Just updated from PS 1.7.8.10 to PS 8.1.1 and still experience this issue too.

**Comment by PascalB67** [comment]
Hello 
Same after update from 1.7.8... to 8.1.3 (PHP 8.1) 
Rename /modules/psaddonsconnect empty cache 
This seems to work (Confirmed)
Not sure for /modules/ps_mbo

**Comment by fuga00** [comment]
had the same after update from 1.7 to 8..
