### ISSUE TITLE
Unable to add a first address with error "Invalid postcode" in some circumstances

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#30973]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

As a customer, I'm unable to create my first address with a country that has not the 'NNNNN' zip code format.
![Immagine 2023-01-20 115746](https://user-images.githubusercontent.com/7520695/213679356-6c368d48-b47a-4077-a00e-f31ac4f68664.png)

This bug happens in this circumstances
- Multishop installation
- Main shop has default country `France`, second shop has default country `Switzerland`
- `France` is not associated to second shop, `Switzerland` is not associated to main shop

### Expected behavior

It should be possible to add an address with any country in the drop down list.

### Steps to reproduce

1. Create a clean installation of Prestashop using https://gist.github.com/lmeyer1/c40a19d880758bee11a1e8a2c5e819c3
2. Log into BO, `All shops` context
3. Go to `International - Locations - Countries`, enable `France`. Make sure `France` and `Switzerland` are both enabled.
4. Click on `France`. In shop associations, uncheck `Shop A`
5. Click on `Switzerland`. In shop associations, uncheck `Prestashop default`
6. Go to `International - Localization`
7. Change to `Prestashop default` context. Set `France` as *Default country*.
8. Change to `Shop A` context. Set `Switzerland` as *Default country*.
9. As a customer open Shop A.
10. Create a new account
11. In `Your Account` click on `Add first Address`
12. Enter an *Address*, enter a *Zip code* with four numbers (as Swiss zip codes are), enter a *City* and select `Switzerland` as *Country*.
13. Click save and learn that in Switzerland post codes with 4 numbers are invalid: it says `Invalid postcode - should look like "NNNNN"`

### PrestaShop version(s) where the bug happened

8.0.0, not able to reproduce on 1.7.8.7

### PHP version(s) where the bug happened

8.4

**Comment by florine2623** [comment]
Hello @lmeyer1 ,

Thanks for the clear steps.
I followed them and I have the same issue as you on PS `8.0.x` and `develop`.

https://user-images.githubusercontent.com/16019289/214854469-ad04db13-08a7-4d94-9aaf-5752089c70d0.mov

The issue is only present when you create an address. If you try to edit it and only put 4 digits as postal code, it works well.

Thanks for the PR!

**Comment by atomiix** [comment]
Fixed by #31152
