### ISSUE TITLE
Translations added to tpl don't work

### ISSUE THREAD

**Issue by alexgonbled** [PrestaShop/PrestaShop#30977]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Prestashop does not show this translation in the BO: 
![image](https://user-images.githubusercontent.com/75474559/213692664-7d8ed961-1403-4221-896f-940dc5b016f7.png)

### Expected behavior

That the string to be translated appears in the BO of prestashop

### Steps to reproduce

Add a translatable text in this file: /var/www/html/modules/ps_shoppingcart/ps_shoppingcart.tpl 
It will not appear in the prestashop translation options
i Am using module version v2.0.6 ps_shoppingcart

### PrestaShop version(s) where the bug happened

1.7.5.1

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_shoppingcart

**Comment by florine2623** [comment]
Hello @alexgonbled ,

Can you explicit your steps please ?
Where did you add your code ?
Where it is shown in the software ?
Add screenshots or screen records too ^^

You can also downgrade your PHP version to 7.2.
7.3 is not compatible with your PS version : https://devdocs.prestashop-project.org/1.7/basics/installation/system-requirements/

Waiting for your feedback.
Thanks

**Comment by hibatallahAouadni** [comment]
Hello @alexgonbled 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
