### ISSUE TITLE
Free shipping cart rule not removed after address (country) update

### ISSUE THREAD

**Issue by cyrilv30** [PrestaShop/PrestaShop#30984]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have a cart rule for free shipping from 50€ order, shipping to France only, any carrier. Rule is not updated (and in my case removed) if I update the delivery address after selecting the carrier.

### Expected behavior

After updating the delivery address, cart rule should be updated and in this case, removed.

### Steps to reproduce

During checkout, step 2 filling in the address validate the right to have a free shipping for France. As seen in step 3:
![image](https://user-images.githubusercontent.com/86005006/213737745-81f69871-4cd2-4513-816a-8e87d129e4f6.png)

If I go back to step 2 and change my delivery address to let's say United States:
![image](https://user-images.githubusercontent.com/86005006/213734348-0f469805-5114-4f0b-933b-cf8d86953fba.png)

Step3, coupon for free shipping is still here, with the configured carrier for US:
![image](https://user-images.githubusercontent.com/86005006/213734575-04454a71-3139-4bf8-9055-ee127fff1dcc.png)

Step4, free shipping is gone and we cheated on customer because now he thinks shipping is free but will pay shipping fees if not paying attention.
![image](https://user-images.githubusercontent.com/86005006/213734810-f5ddfeee-50d2-4057-a9c3-aede362868bf.png)

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.3

**Comment by sallemiines** [comment]
Hello @cyrilv30 
Thanx for reporting the issue.

Following your steps I didn't manage to reproduce your issue , you can see the attached screen record 

https://user-images.githubusercontent.com/31663369/214333020-9c4def68-99e9-4e19-8ead-b19ded21eb1e.mp4



Did I miss smthg , 
Please check and feedback ! 
Thank you !

**Comment by hibatallahAouadni** [comment]
Hello @cyrilv30 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
