### ISSUE TITLE
Order and Cart are out of sync

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#30995]
### Describe the bug
_Originally posted by @TheEnglishGartner in https://github.com/PrestaShop/PrestaShop/issues/17598#issuecomment-1399514035_

I have a PS 1.7.8.8 Warehouse Theme 

All modules updated although I have a strange issue, which has been mentioned in another post ;

BO - Order page - An error is displayed when decreasing the gifted product quantity "Could not find the product in cart, meaning Order and Cart are out of sync" #22004

In my Prestashop I get the below:

Could not find the product in cart, meaning Order and Cart are out of sync

and order has been placed - but afterwards I would like to give a discount (which I have been doing many times) When I put in the discount as a value / amount a red bar appears with the above txt. 

Im using One page checkout

### Expected behavior
.................

### Steps to reproduce

A customer places an order
In that specific order 2 products will be out of stuck as a consequence of the order contains the last products - hence the product is set to 0.

I would like to make an amount discount on the order (which is something that always work) - I tried to put in but I got the info above.

Hence after reading around I tried to adjust the two products to a positvie number -and voila I could then provide the discount.

After this I adjusted the products / stuck to the 0 in stuck again.

I do hope this is ok for you all.

As a side note - when tyring this - I also tried it on an order where all products was not out of stuck and this worked as it should.

**Screenshots**
![Red BAr - When Trying to provide Discount](https://user-images.githubusercontent.com/92990704/213922923-5dd57eaa-384f-41db-82e2-d57622d30c92.JPG)

### Additional infos

- PS version: 1.7.8.8
- PHP version:

**Comment by TheEnglishGartner** [comment]
Just and update.

We had to lines were stock level for the product was 0 after the purchase of the order.

What I did was adjust the product amount to a positive number, and then I could provide the discount. Althouhg it should be viable to provide a discount even if the products is sold out - as the discount should be on the total order and not a product.

/Lasse

**Comment by sallemiines** [comment]
Hello @MatShir 

Could you please provide clear and concise steps to reproduce and the expected behavior ?

Thank you !

**Comment by MatShir** [comment]
Hi @TheEnglishGartner,
Could you explicit all the steps (1. .. 2. ...)? I can't reproduce it on my side :/

**Comment by TheEnglishGartner** [comment]
Hi 

the steps:

A customer places an order
In that specific order 2 products will be out of stuck as a consequence of the order contains the last products - hence the product is set to 0.

I would like to make an amount discount on the order (which is something that always work) - I tried to put in but I got the info above.

Hence after reading around I tried to adjust the two products to a positvie number -and voila I could then provide the discount.

After this I adjusted the products / stuck to the 0 in stuck again. 

I do hope this is ok for you all.

As a side note - when tyring this - I also tried it on an order where all products was not out of stuck and this worked as it should.

**Comment by florine2623** [comment]
Hello @TheEnglishGartner ,

I created 2 product with only 1 stock left:
<img width="1163" alt="Screenshot 2023-01-26 at 17 37 58" src="https://user-images.githubusercontent.com/16019289/214895116-253870b8-3a50-4e76-819b-4956acf80760.png">

I placed my order:
<img width="1150" alt="Screenshot 2023-01-26 at 17 38 47" src="https://user-images.githubusercontent.com/16019289/214895225-c0d6f3d5-fb4d-43ca-9398-3abaec626b78.png">

My order is valid:
<img width="1223" alt="Screenshot 2023-01-26 at 17 41 00" src="https://user-images.githubusercontent.com/16019289/214895341-2c8e45bb-bfad-4498-885b-31ef6e6ab379.png">

I created a discount for my specific order:

https://user-images.githubusercontent.com/16019289/214895947-432135cc-4c33-464f-871f-7e6102f27967.mov

I also tested when the Order Status is changed to "Payment accepted":

https://user-images.githubusercontent.com/16019289/214896071-0a0e0468-b235-44ec-aeeb-a166c9a7f4c4.mov

I can't reproduce your issue.
Am I missing something ?
Waiting for your feedback.

**Comment by TheEnglishGartner** [comment]
Nope not messing anything. It could of course be local on my installation.

lets close it for NOW. Thank you all for the effort

best

**Comment by MatShir** [comment]
Okay let us know if it comes back
