### ISSUE TITLE
BO - PPV2 - Previous combination & Next combination buttons can't be clicked

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#30998]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Previous combination & Next combination buttons can't be clicked 

On 8.0.x ✅ :

https://user-images.githubusercontent.com/16019289/214015586-d91fdeeb-2c6b-4cb5-96aa-806823896b96.mov

On develop :x: :

https://user-images.githubusercontent.com/16019289/214015627-9f409ae6-3fe1-4266-9b73-9f850702baa2.mov

### Expected behavior

The buttons should be clickable

### Steps to reproduce

1. BO > Advanced Parameters > New & Experimental features > Enable PPV2
2. Go to a product with combinations > Combinations Tab
3. Edit a combination
4. See that Previous combination & Next combination buttons can't be clicked and are greyed out :x: 

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4

**Comment by sallemiines** [comment]
Hello @florine2623 

Thanx for reporting the issue.

I didn't manage to reproduce the issue with **develop** , LGTM on develop ,  ok you can see the attached screen record 



https://user-images.githubusercontent.com/31663369/214279805-fe68cc75-54a4-4184-85b8-c4b5d26757ea.mp4



Issue tested With  **PS 8.0.0,  OK PS 8.0.1 OK , PS 8.0.X OK**

Could you please check and feedback ! 

Thank you !

**Comment by florine2623** [comment]
@PrestaShop/qa-functional 
Could someone try this ?
I tested on multiple installation of develop with PHP 7.4, I still have the same behavior :/

**Comment by djoelleuch** [comment]
Hello @florine2623 ,
We didn't manage to reproduce your  issue with develop  with the provided information. 

[Untitled_ Mar 15, 2023 11_55 AM.webm](https://user-images.githubusercontent.com/115152460/225289829-1a428a79-b181-4ef8-8aa8-2982e5057ef8.webm)


It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue . 

Thank you
