### ISSUE TITLE
BO - PPV2 - On Save action, the form displays the id of the combination with no further explanation

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#31007]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The ID of the combination appears at the bottom of the edition form :

![image](https://user-images.githubusercontent.com/16019289/214248711-e25f9084-05b6-48fa-ad2e-11b496760503.png)

Discovered in this PR : https://github.com/PrestaShop/PrestaShop/pull/30936

### Expected behavior

This number should not appear

### Steps to reproduce

1. Go to BO > Enable Product Page V2
2. Edit a product with combinations
3. Click on Save > See a number appear

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4

**Comment by sallemiines** [comment]
Hello @florine2623 

Thanx for reporting the issue.

I reproduce the issue with **develop NOK**, with **PS 800 OK** , and with **PS 801 OK**

https://user-images.githubusercontent.com/31663369/214274825-e19e6f63-0499-4c37-9873-49c8206ec557.mp4

It's a regression ! Nice catch 

Thank you !
