### ISSUE TITLE
Invalid conversion from 3-char hex-color to 6-char hex color

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#31002]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Here the formula to convert from 3-char hex-color to 6-char hex color is wrong https://github.com/PrestaShop/PrestaShop/blob/dcdd11673033095fd31b65cca6d9ddb0325464c3/src/Core/Util/ColorBrightnessCalculator.php#L62-L64 

For instance, the color `#0F1` will be converted to `#0F10F1`, which is wrong. `#00FF11` would be correct

### Expected behavior

I expect the conversion from 3-char hex-color to 6-char hex color to give a correct result.

### Steps to reproduce

For devs, not QA-team 😉 
1. Look at this code https://github.com/PrestaShop/PrestaShop/blob/dcdd11673033095fd31b65cca6d9ddb0325464c3/src/Core/Util/ColorBrightnessCalculator.php#L62-L64
2. Imagine what it does and compare to standards

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4

**Comment by lmeyer1** [comment]
### Steps to reproduce for QA

Note: The GUI in the BO does not allow three digit hex codes, therefore we must write to the database directly.
1. Choose a order state, in BO set the color to `#00ff11`
2. You will get  ![2023-01-24_090120](https://user-images.githubusercontent.com/7520695/214240912-5929a515-61e6-4952-b96d-617bcb7dfd82.png)
3. In phpmyadmin set the color to `#0f1`. It's the same color, you should get the same thing.
4. But you will get ![2023-01-24_090317](https://user-images.githubusercontent.com/7520695/214241109-7f19176e-2b6f-4b3d-8f30-2dd8e6bc68e7.png). The color is considered dark, and the white is chosen as the text color.

Check the PR:
After the PR, the contrast color applied is black as expected.

**Comment by Hlavtox** [comment]
Ping @maofree, same issue?

**Comment by Maofree** [comment]
Hi

**Comment by Maofree** [comment]
Hi @Hlavtox 
checking better, I think it's very similar, my problem appears because instead of using a color code like '#A56322' I use the name of the color like 'red' or 'green'

**Comment by Hlavtox** [comment]
@maofree Thats why, you need to use hex. The only text color that it supports is “transparent”.

**Comment by Maofree** [comment]
before it also worked with the name, however it is fine

**Comment by FabienPapet** [comment]
Reproduced.

Only 6 digits hex code are currently supported. PR is adding 3 digit support while fixing the problem.

**Comment by hibatallahAouadni** [comment]
ping @FabienPapet is this a regression or an old bug?

**Comment by FabienPapet** [comment]
regression

**Comment by lmeyer1** [comment]
Fixed with #31006
