### ISSUE TITLE
Featuredproducts

### ISSUE THREAD

**Issue by marieclaude11** [PrestaShop/PrestaShop#31009]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

je n'arrive pas a modifier la traduction de "Featuredproducts".
Sur le back admin , j'arrive à le traduire par ce que je souhaite, mais lorsque je suis sur le site internet en temps que client ca affiche "trending product"
Impossible de le changer dans le paramètre traduction

### Expected behavior

que la traduction se fasse 

### Steps to reproduce

<img width="1082" alt="Capture d’écran 2023-01-24 à 10 36 15" src="https://user-images.githubusercontent.com/123458396/214260046-72c47293-7087-4acc-8a05-9bed9fbb52f2.png">
<img width="1234" alt="Capture d’écran 2023-01-24 à 10 36 36" src="https://user-images.githubusercontent.com/123458396/214260060-f3078c2c-7ace-4aac-81d6-6edd933e65ac.png">
<img width="714" alt="Capture d’écran 2023-01-24 à 10 36 45" src="https://user-images.githubusercontent.com/123458396/214260076-551cdbd9-f4ad-4714-82a3-ed0b62197c44.png">
<img width="1424" alt="Capture d’écran 2023-01-24 à 10 36 59" src="https://user-images.githubusercontent.com/123458396/214260081-059af1eb-cc73-4028-ad2b-5c47a26a60f9.png">

### PrestaShop version(s) where the bug happened

ne sais pas 

### PHP version(s) where the bug happened

ne sais pas 

### If your bug is related to a module, specify its name and its version

ne sais pas

**Comment by sallemiines** [comment]
Hello @marieclaude11 

Please send your request in English. English is the norm on GitHub.

Thank you !

**Comment by hibatallahAouadni** [comment]
Hello @marieclaude11 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
