### ISSUE TITLE
BO- Multistore PPV2 Error warning displayed when set the name of the product 

### ISSUE THREAD

**Issue by MhiriFaten** [PrestaShop/PrestaShop#31000]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

A warning to enter a name product is displayed, even when the product contains a name.

[Untitled_ Jan 23, 2023 11_57 AM.webm](https://user-images.githubusercontent.com/111756615/214022697-3f8db9f1-87d3-4bd5-b311-55a06f10c6bb.webm)

### Expected behavior

the warning shoudln't be displayed and the product should be saved successfully 

### Steps to reproduce

1. Go to BO>Enable Multistore **`Yes`**
2. Go to Advanced Parameters>Multisore
3. Create a new shop
4. Go to New & Experimental Features>New product page - Multi store **`enabled`**
5. Go to Catalog>Products>New product with combinations
6. Create the product and save
7. See ERROR :warning:  a bad warning displayed **`To put this product online, please enter a name.`**

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

**Comment by sallemiines** [comment]
Hello @MhiriFaten 

Thanx for reporting the issue.

I reproduce your issue with **develop** ,the error warning displayed when I click on the button **Apply changes to all stores** you can see the attached screen records bellow : 

**Case 1 Apply changes to all stores , is clicked :** 


https://user-images.githubusercontent.com/31663369/214284526-8ece208b-9f0c-47ed-a231-95d796233fc0.mp4

**Case 2 Apply changes to all stores , is not clicked :** 


https://user-images.githubusercontent.com/31663369/214285271-27a16def-84dd-42dc-9778-2e992e7a32fa.mp4


I checked the issue also with **PS 800** It's OK , you can see the attached screen record 


https://user-images.githubusercontent.com/31663369/214291558-3b010d0c-76fa-45f5-9fd8-ba7e24c51a97.mp4


So it's a regression ! nice catch !

Thank you !

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/31250
