### ISSUE TITLE
BO - GDPR - Unable to generate a URL for the named route "admin_customers_view" as such route does not exist.

### ISSUE THREAD

**Issue by Guillaumegiot** [PrestaShop/PrestaShop#31001]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, when we click on configure for the official GDPR module, we have this displayed : 

```
"Oops! An Error Occurred

The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused."
```

Thanks in advance

### Expected behavior

Solve this problem to be able to configure the module again.

### Steps to reproduce

1. go to "module manager"
2. click to "configure" on the module GDPR Officiel

### PrestaShop version(s) where the bug happened

1.7.5.2

### PHP version(s) where the bug happened

7.3.33

### If your bug is related to a module, specify its name and its version

RGPD Officiel v1.4.3 - par PrestaShop

**Comment by kpodemski** [comment]
Hello @Guillaumegiot 

First of all, here on GitHub we use English to communicate :) Secondly, you should enable developer mode in your store to see the error. Error 500 is generic information that doesn't explain anything.

**Comment by sallemiines** [comment]
Hello @Guillaumegiot ,

Please send your request in English. English is the norm on GitHub.

Thank you

**Comment by hibatallahAouadni** [comment]
Hello @Guillaumegiot 

First of all, you need to edit your issue description and use only English, as @sallemiines and @kpodemski mentioned above.
Second, you should downgrade your PHP version to 7.2 cause PS 1752 is not compatible with PHP 7.3.

Please check and feedback.

Thanks!

**Comment by HartLarsson** [comment]
i've reported another problem of the same module version here: https://github.com/PrestaShop/PrestaShop/issues/30963

**Comment by florine2623** [comment]
Hello @Guillaumegiot ,

I have reproduced your issue with PS 1.7.5.2, PHP 7.2, Official GDPR compliance v1.4.3.

<img width="1024" alt="Screenshot 2023-01-25 at 14 15 13" src="https://user-images.githubusercontent.com/16019289/214572950-eb6c0c67-a1f2-450d-a1a8-bbf6547fa939.png">

With debug mode enabled :
<img width="1070" alt="Screenshot 2023-01-25 at 14 13 14" src="https://user-images.githubusercontent.com/16019289/214572988-d8586347-272c-4301-b540-3d11c347a85f.png">

I tried deleting the cache from /var/cache, but I still have the same issue.

I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
