### ISSUE TITLE
Worflow broken with quick PayPal payments When paying with "Prestashop Checkout and Paypal" no carriers available for your delivery address.

### ISSUE THREAD

**Issue by KarmCraft** [PrestaShop/PrestaShop#31017]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

This is kind of a 2-in1

Issue occurs when paying with Paypal Pill button in Checkout summary (on the top right)

Possibly related to [`13823`](https://github.com/PrestaShop/PrestaShop/issues/13823) ?

Shop is Switzerland-Only

Setup:
-  3 normal carriers
![image](https://user-images.githubusercontent.com/15261206/214345002-2da7ca32-855e-46b3-91ca-f4035f59d6df.png)

- Payments correctly configured for Switzerland
![image](https://user-images.githubusercontent.com/15261206/214345829-b7ea26f2-dedd-4a12-9d5f-73ba29932ad1.png)
![image](https://user-images.githubusercontent.com/15261206/214345782-59e8b74f-fff5-417e-92cb-83f231d67024.png)

- Module Prestashop Checkout configured for PayPal and Credit Cards

Behavior:
1. At the checkout, when paying with the Quick PayPal Pill Button in summary, after Login into Paypal the Prestashop Cart creates a new Address with the details from PayPal Login - OK
2. Unfortunately in the Step 3 it gives the error "Unfortunately, there are no carriers available for your delivery address."
![image](https://user-images.githubusercontent.com/15261206/214348040-bb5a297d-6486-48bd-832c-8d3ba0d8602c.png)

3. I have to go back to Step 2 and choose the first Adress of the registred user, then the Carrier is available as expected
![image](https://user-images.githubusercontent.com/15261206/214348083-865523a3-73ba-49f8-aae8-792a080c4a20.png)

I think the Workflow is kinda broken, because the payment went already through with PayPal, but the steps are still displayed until step 4 where you can pay again?

Workaround: Disable Quick PayPal payments in summary

### Expected behavior

Prestashop Checkout module to work correctly in both scenarios, when chosing PayPal in Step 4 and when chosing PayPal from the Checkout summary

### Steps to reproduce

See description

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

Prestashop checkout 2.21.0

**Comment by hibatallahAouadni** [comment]
Hello @KarmCraft 

Thanks for reporting the issue!
Unfortunately, the Checkout module is not a native module :disappointed: 
So, could you please contact the module developers on Addons to fix the issue :pray: 

Thanks!
