### ISSUE TITLE
BO -  Uninstall function of the module gridhtml shows an error message 

### ISSUE THREAD

**Issue by sallemiines** [PrestaShop/PrestaShop#31012]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The  uninstall function of the module **gridhtml** shows an error message ,  but the module is successfully uninstalled ! 

### Expected behavior

When uninstall the module a success message should appears ! 

https://user-images.githubusercontent.com/31663369/214270071-93e3d12c-158d-481d-859a-b9259c254962.mp4

### Steps to reproduce

1. Install the release  version 2.0.3 of the module gridhtml
2. Uninstall the module 
3. An error message appears , and the module is well uninstalled 

https://user-images.githubusercontent.com/31663369/214269635-425c6405-765f-41c2-99b5-6388dc7377f8.mp4

PS: the  uninstall function is OK on **PS 800** , and already discussed with  @Hlavtox  he confirmed that the issue is not related to the release ! 

### PrestaShop version(s) where the bug happened

1.7.8.7

### If your bug is related to a module, specify its name and its version

gridhtml V2.0.3  and V2.0.2

**Comment by Hlavtox** [comment]
@sallemiines We must still investigate what is so special about this module and if it's core or modules fault. 👍
