### ISSUE TITLE
PrestaShop Checkout module - Inconsitent CSS

### ISSUE THREAD

**Issue by KarmCraft** [PrestaShop/PrestaShop#31018]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On the Product page, payment method images (PayPal, VISA) have the w-fixed. 
On the cart-summary on the top right they have the class w-20.
This leads to inconsistent spacing and visual appearance.

### Expected behavior

They should look all the same

### Steps to reproduce

nothing, default behavior

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

Prestashop Checkout

**Comment by hibatallahAouadni** [comment]
Hello @KarmCraft 

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you
