### ISSUE TITLE
Generate the new format at the image's upload

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#31020]
**User story**

As a merchant, when I upload an image in the product page, I want my image be generated to the configured formats

**Acceptance test**

When I enable the experimental feature 'image new format' 
Then the new format configurator is displayed
When I select avif and jpg as image to generate
Then when I upload a image in the product page, all the image size are generated in avif and jpg

**Comment by Hlavtox** [comment]
@MatShir I think it could be a setting to toggle in `Image settings`, what do you think?

Why - it takes several seconds to render the thumbnails even in a jpg format. Maybe some people would like the images to be generated in FO automatically, after they are done modifying the product. :-)

ping @matthieu-rolland

**Comment by MatShir** [comment]
It will be in a feature flag anyway, so we can improve it anyway afterward. wdyt ?

**Comment by Hlavtox** [comment]
Yes, no worries. A lot of time to polish this. 🤌
