### ISSUE TITLE
Used decimals while creating order detail are not the same and there is an extra quantity discount

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#31025]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you order a product, you could have the colomn `product_quantity_discount` having the `0.000001` value inside it even if your product have no discount on it.

### Expected behavior

Having the value 0 inside this colum.

### Steps to reproduce

Add a product with theses settings : 

- Tax rules : 21%
- Base price (without taxes) : 119€

Set a specific price on it :
- Set the price to 98.347107 and uncheck the "Keep the base price" setting.

Order this product and check the order_details row added.

### PrestaShop version(s) where the bug happened

1.7.8.x, 8.0.1

**Comment by florine2623** [comment]
Hello @PrestaEdit ,

I can't reproduce your issue following your steps.
I tested on 8.0.1.

My product price config:
<img width="1021" alt="Screenshot 2023-01-26 at 12 29 24" src="https://user-images.githubusercontent.com/16019289/214825060-67fe0a04-ce12-4172-b353-a0a4967d7be3.png">

My specific price config:
<img width="1244" alt="Screenshot 2023-01-26 at 12 29 32" src="https://user-images.githubusercontent.com/16019289/214825099-c890745b-1ac1-416f-bc51-59d9bf4ae1da.png">

In my database:
<img width="623" alt="Screenshot 2023-01-26 at 12 28 42" src="https://user-images.githubusercontent.com/16019289/214825124-721993c3-1ee7-4460-a69d-2852f879e660.png">

Am I missing something ?
Waiting for your feedback.
Thanks!

**Comment by PrestaEdit** [comment]
Hi @florine2623 ,

There is the screens and the query to make.

<img width="1437" alt="Capture d’écran 2023-02-15 à 09 38 57" src="https://user-images.githubusercontent.com/2631425/218981071-1a2155a7-fd3c-4a6a-8fdd-157184c4854b.png">
<img width="1437" alt="Capture d’écran 2023-02-15 à 09 39 08" src="https://user-images.githubusercontent.com/2631425/218981079-e5fc7cc5-aab4-4173-841b-e74a9950b188.png">

Query :
`SELECT id_order_detail, product_name, product_price, product_quantity_discount FROM ps_order_detail`

<img width="735" alt="Capture d’écran 2023-02-15 à 09 59 31" src="https://user-images.githubusercontent.com/2631425/218981175-0c099f30-10ee-476b-bdff-ece27284753a.png">

**Comment by florine2623** [comment]
Hello @PrestaEdit ,

I have reproduced your issue on PS 8.x thanks to your query. I also have the `0.000001` amount in quantity when there's no discount applied on the product.

<img width="1084" alt="Screenshot 2023-02-16 at 17 19 08" src="https://user-images.githubusercontent.com/16019289/219425419-621d18cf-dc4c-46f0-aaf3-b936f34f2109.png">

Thank you
