### ISSUE TITLE
After updating module "Mail alerts" to version 2.4, e-mails are not sent

### ISSUE THREAD

**Issue by robProWeb** [PrestaShop/PrestaShop#31039]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi, after upgrading Prestashop and the Mail Alert module to the latest versions, the new order notification emails are no longer sent. In the email log screen you can see that all the emails except the "new_oder" ones are sent correctly (via SMTP).

Prestashop 1.7.8.8
Mail Alert 2.4.0

![Email-•-Bruma-Street-Style-Shop-Online](https://user-images.githubusercontent.com/82451318/214815478-6b23ebba-9dd6-4bf7-8c83-ba9e3c8499bb.png)

How can I fix?
The administrators of our ecommerce sites are no longer receiving new order notifications, so it is urgent for us to find a solution. Thank you

### Expected behavior

For every order made by a customer, a notification email should arrive to the administrator.

### Steps to reproduce

Place an order

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

ps_emailalerts 2.4.0

**Comment by florine2623** [comment]
Hello @robProWeb ,

I can't reproduce your issue on PS 1.7.8.8 with ps_emailalerts v2.4.0 :

<img width="1202" alt="Screenshot 2023-01-26 at 12 15 07" src="https://user-images.githubusercontent.com/16019289/214822578-b19425d7-8b51-4f4a-b779-4c56bde29626.png">

Your issue might come from a configuration issue.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
