### ISSUE TITLE
Module Cash On Delivery non disponible

### ISSUE THREAD

**Issue by manhishop** [PrestaShop/PrestaShop#31041]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Le module Cash On Delivery n'est pas disponible sur la version de Prestashop 1.7 que nous avons installé sur notre boutique manhishopci.com

### Expected behavior

Avoir le fichier du module Cash On Delivery

### Steps to reproduce

Go to Gestionnaire de modules

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

 7.4.29

### If your bug is related to a module, specify its name and its version

Cash On Delivery

**Comment by florine2623** [comment]
Hello @manhishop ,

Please follow my video :

https://user-images.githubusercontent.com/16019289/214840707-0dd84089-46c2-4ce6-8f2d-e7ae743b5e0f.mov

I'll close your issue to avoid cluttering the backlog.
Thanks.
