### ISSUE TITLE
Tools::convertPrice is deprecated and it is suggested to use the convertPriceToCurrency() function, but this is not present in prestashop

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#31052]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
I want to replace
Tools::convertPrice
because it is deprecated
in the Tools.php file there is written

Function 'convertPrice' has been deprecated. since 1.7.4 use convertPriceToCurrency()

but I don't know where is this convertPriceToCurrency

with grep -r I cannot see any file that use this function

instead for
Tools::displayPrice
$this->context->getCurrentLocale()->formatPrice
is ok

can you help me which function I need to use? and fix that text to help others

thanks

### Steps to reproduce

go to Tools.php and search the function convertPrice

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @maofree ,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by Maofree** [comment]
Hi
is there any news?

**Comment by KoreLewi** [comment]
There is any news?

The bug is reproducible in all PrestaShops above 1.7.4.

The Tools.php class says: 
```
/**
     * Return price converted.
     *
     * @deprecated since 1.7.4 use convertPriceToCurrency()
     *
     * @param float|null $price Product price
     * @param object|array $currency Current currency object
     * @param bool $to_currency convert to currency or from currency to default currency
     * @param Context $context
     *
     * @return float|null Price
     */
    public static function convertPrice($price, $currency = null, $to_currency = true, Context $context = null)
    {...}
```
but the convertPriceToCurrency method not exist (Using PHPStorm, I scanned the entire source code.)
