### ISSUE TITLE
Cart Rule with amount off not working properly

### ISSUE THREAD

**Issue by gfiore88** [PrestaShop/PrestaShop#31050]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In Cart Rules, even if the categories restriction has been selected in condition step, when you proceed on to actions and you select the order (without shipping) option, the amount off is offset against the whole order inclusive all the categories.

The alternative could have been to insert specific products instead "order (without shipping)" but the only option that I have is for the addition of a single product only.

 

I have tried that many times before posting here.

I'll leave you also a link where this kind of issue is discussed:

https://www.prestashop.com/forums/topic/507568-how-to-include-specific-categories-for-amount-off-price-rule-cart/

### Steps to reproduce

- Go To Cart Rules
- Create a rule with a condition for certain categories
- In Action set an amount off (for example 20 euros)
- Set order (without shipping) option
- Save the rule

Test the coupon adding into the cart product in selected categories and some other products not in selected categories and you will see that the coupon will be applied to all products (wrong)

### PrestaShop version(s) where the bug happened

1.7.8.7

**Comment by florine2623** [comment]
Hello @gfiore88 ,

I have reproduced your issue. The amount of discount is higher than the value of the product itself :
<img width="1144" alt="Screenshot 2023-01-26 at 17 31 36" src="https://user-images.githubusercontent.com/16019289/214893135-1bb28e79-a149-4c04-be9c-508fe39bb613.png">

Here's the config of my Cart Rule:

<img width="991" alt="Screenshot 2023-01-26 at 17 24 54" src="https://user-images.githubusercontent.com/16019289/214893192-c4b2b7f2-c226-4ae6-b223-0151ee83bcd5.png">


I think it is similar to : https://github.com/PrestaShop/PrestaShop/issues/14933
Could you check and confirm ? ^^

**Comment by gfiore88** [comment]
Yes, is similar

**Comment by hibatallahAouadni** [comment]
Hello @gfiore88 

thanks for your feedback 🙏 
We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #14933. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #14933
