### ISSUE TITLE
Paging error on the first click

### ISSUE THREAD

**Issue by lzhudson** [PrestaShop/PrestaShop#31062]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have an e-commerce site, where the pagination on the first click from page 1 to page 2 does not happen.

In other e-commerce languages it works normally, the problem only happens in the French language.

Video showing the bug: https://www.loom.com/share/1810d182d214451ab714dad07e80c7eb

### Expected behavior

Ideally, the listing should be displayed on screen on the first click

### Steps to reproduce

1. Go to: https://www.1923shop.com/fr/4-vetements-pilote
2. Scroll to the bottom of the page
3. Click to go to the second page
4. The products on page two will not be shown in the interface.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.33

**Comment by HanaRebaiQA** [comment]
Hello @lzhudson 

Thanks for your report.
Could you please precise which is exactly the bug in the steps of reproduce ?

**Comment by lzhudson** [comment]
Hello @HanaRebaiQA 

I added a step 4 with the error.
Is this correct?

**Comment by hibatallahAouadni** [comment]
Hello @lzhudson 

I didn't manage to reproduce the issue with Classic theme and on your site I only reproduce once when I go from page 1 to 2, but when the page 3 is well displayed, the page 4 is well displayed, and when I access to page 2 from page 4, the products of page 2 are well displayed 😉 
It seems a cache issue related to your theme.
Closing the issue as it's not related to the Core.

Thanks for your understanding 🙏
