### ISSUE TITLE
Prestashop modules gone from Home Page ( Bestsellers, New products, Featured producs, viewed products)

### ISSUE THREAD

**Issue by DariuszBladana** [PrestaShop/PrestaShop#31066]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After module updates, few Prestashop modules stopped working or the disappear :
Popular products tab, New products tab, Viewed Products, Featured products tab. All of them were present on home page but now they have gone. Please help.

### Expected behavior

All features are present on home page.

### Steps to reproduce

1. Update modules

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4.29

### If your bug is related to a module, specify its name and its version

New products (1.0.2), Produkty Polecane (2.1.3), Last Viewed (1.2.3),

**Comment by DariuszBladana** [comment]
![Zrzut ekranu 2023-01-28 225933](https://user-images.githubusercontent.com/123813650/215292992-19f73e1b-d684-410d-adce-551c6809013d.jpg)
Tabs are gone from Home page

**Comment by adrienrch** [comment]
HI, I already had this issue. Try to reset the modules and they should be here again

**Comment by DariuszBladana** [comment]
I tried this but it wasnt problem with modules but with theme. I tried almost everything changing data in presta code but nothing has changed. I decided to reupload theme from scratch and issue has been fixed. I did something with modules that ended up with missing a major of them on home page. Now I will be more careful with updating anything in presta.
Anyway, reinstalling theme fixed issue.

**Comment by hibatallahAouadni** [comment]
Hello @DariuszBladana 

Thanks @adrienrch for your quick reply :rocket: 
As @adrienrch mentioned above, with Classic theme, you just need to reset the modules.
But it seems your issue is related to your customized theme. So, closing the issue as it's not related to the Core :wink: 

Thanks for your understanding :pray:
