### ISSUE TITLE
Problem with paypal instalation 

### ISSUE THREAD

**Issue by dam2452** [PrestaShop/PrestaShop#31072]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Good morning, I am having a problem install a module to Prestashop. At first, I received a message saying that the file was too large, but after I increased the file size in php.ini.  I saw this message "The installation of the PayPal module failed. SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ALTER TABLE ps_paypal_capture MODIFY id_paypal_order INT(10) SIGNED NOT NULL' at line 2" If it's possible, my database is not valuable because it's a fresh shop, so if it's possible to quickly reset it or something, I'm open to that solution. I would greatly appreciate any help. Thank you very much in advance.

### Steps to reproduce

1. Click load module 
2. Choose paypal zip
3. and boom "The installation of the PayPal module failed. SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ALTER TABLE ps_paypal_capture MODIFY id_paypal_order INT(10) SIGNED NOT NULL' at line 2"

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.1.2

### If your bug is related to a module, specify its name and its version

paypal 5.7.5

**Comment by dam2452** [comment]
When trying to clear this plugin, I get this message "Could not Reset the paypal module. SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ALTER TABLE ps_paypal_capture MODIFY id_paypal_order INT(10) SIGNED0 NOT NULL' at line 2" and I don't really know what to do with it because I am not familiar with MySQL. When I try to uninstall it, I get the message "Could not perform action uninstall for module paypal. Failed to remove file "/var/www/prestashop/modules//paypal/paypal/services/ServicePaypalVaulting.php": unlink(/var/www/prestashop/modules//paypal/paypal/services/ServicePaypalVaulting.php): Permission denied"

**Comment by matks** [comment]
Hello

It seems that your issue is not a PrestaShop core bug.
If your module is PayPal Official, please contact support team on Addons.

This bug tracker scope is the open source project, not every prestashop module 😉 .

**Comment by hibatallahAouadni** [comment]
Hello @dam2452 

Please contact the module developer on Addons.

Thanks!
