### ISSUE TITLE
Turn product page v2 into stable page

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#31086]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Now that the product page is considered stable even in multishop mode we need to change a fe things:
- remove the Experimental block on the page in multi shop mode
- merge the two feature flags into one `product_page_v2_multi_shop` will be merged into `product_page_v2` (the label should now be `New product page`
- related code to the `product_page_v2_multi_shop` feature flag should be cleaned especially this part https://github.com/PrestaShop/PrestaShop/blob/c067bcf6199f41deaa87d31d4bcbe2194890c73b/src/Adapter/Preferences/PreferencesConfiguration.php#L120
- the feature flag stability of `product_page_v2` should be switch to `stable`
- the default value of product v2 is enabled

### Expected behavior

One feature flag to activate the product page v2

### Steps to reproduce

Expected behaviour to test
1. Go to New & Experimental Features
2. There should only one feature flag related to the product page
3. The product page feature flag should be in the stable block
4. When accessing to the product page V2 in multi shop mode I don't see an experimental warning anymore
5. When product page V2 is enabled and I enable the multishop feature, the product page V2 remains enabled

### PrestaShop version(s) where the bug happened

8.1

**Comment by kvmAlio** [comment]
I don't think product page v2 is stable. 

We have users that when having v2 enabled, cannot add pictures to the products and update de product information. Just add image component is not even visible:

![image](https://github.com/user-attachments/assets/fa7ccef3-bc1c-4e4c-91c4-5db803426299)
