### ISSUE TITLE
Problem with cache when we add/update language twice 

### ISSUE THREAD

**Issue by paulnoelcholot** [PrestaShop/PrestaShop#31094]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On BO > International > Translations

It is not possible to update a language

![image](https://user-images.githubusercontent.com/112863083/215492312-90d9d2ea-3790-4f64-812f-c523fe2a2ae1.png)

### Expected behavior

The update of a language should be possible

### Steps to reproduce

1. On BO > International > Translations

2. On "Add/Update a language"

3. Select on "Update a language" : English (English) 

4. Click to Add or update a language

5. Error 500

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @paulnoelcholot 

Thanks for reporting the issue :pray: 
I reproduce the issue with PS800, PS801 and it's a regression as I didn't reproduce it with PS1788.

Thanks!

**Comment by MatShir** [comment]
I could not reproduce the bug on 8.1.x :/

**Comment by florine2623** [comment]
I've tested with `8.0.x`, `8.1.x` and `develop` branch, with multiple languages and couldn't reproduce the issue.
<img width="388" alt="Screenshot 2023-03-09 at 14 27 20" src="https://user-images.githubusercontent.com/16019289/224037924-06440eea-5374-4474-a2c2-259f26732d6c.png">


It must be a server config issue, wdyt ?
What should be done about this issue ? @MatShir & @Zoefinders

**Comment by MatShir** [comment]
Let's close it and see if someone else reproduces it again !
