### ISSUE TITLE
Error when upgrading module ps_distributionapiclient

### ISSUE THREAD

**Issue by lartist** [PrestaShop/PrestaShop#31098]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When we try to upgrade (or downgrade) ps_distributionapiclient an error shows up. The following steps describe the root of the issue
1. Symfony loads the container with configuration inside ps_distributionapiclient version A
2. The version B is downloaded and the new folder replaces the one from version A
4. Later, from ModuleManager:upgrade we dive deep through several classes until 'actionListModules' hook is executed
5. This hook is catched by ps_distributionapiclient module inside ps_distributionapiclient.php
6. `return $this->getDistributionApi()->getModuleList();` is executed
7. `getDistributionApi()` is a function which try to get DistributionApi service
8. The container try to instantiate it with the constructor of the new version (B) although the configuration from version A was loaded (conf. step 1)
![Capture d’écran 2023-01-30 à 15 20 31](https://user-images.githubusercontent.com/10706307/215502553-884b4f8f-b8ea-4972-900c-5763a3f9ba2d.png)

### Expected behavior

When I try to upgrade (or downgrade) ps_distributionapiclient, no errors should be dislayed.

### Steps to reproduce

1. Go to the module page.
2. Click on install module button on the top right of the page
3. Drop a new version of ps_distributionapiclient
4. See the error

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_distributionapiclient (the version doesn't matter)

**Comment by hibatallahAouadni** [comment]
Hello @lartist 

Thanks for reporting the issue 🙏 
Waiting for your PR 🚀 

Thanks!

**Comment by lartist** [comment]
> Hello @lartist
> 
> Thanks for reporting the issue 🙏 Waiting for your PR 🚀
> 
> Thanks!

Hi @hibatallahAouadni ,

@atomiix is working on https://github.com/PrestaShop/PrestaShop/pull/31137

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/31137 thanks to your idea @lartist 😉
