### ISSUE TITLE
Unable to upgrade manually from PS 8.0.0 to 8.0.1

### ISSUE THREAD

**Issue by templatin** [PrestaShop/PrestaShop#31090]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Using autoupgrade module v4.15.0 (with `vendor` folder).
I'm getting below errors while doing manual upgrade from PS 8.0.0 to 8.0.1.

`Warning: require_once(D:\wamp\www\presta80\modules\autoupgrade\upgrade/../../vendor/autoload.php): failed to open stream: No such file or directory in D:\wamp\www\presta80\modules\autoupgrade\upgrade\upgrade.php on line 47`

`Fatal error: require_once(): Failed opening required 'D:\wamp\www\presta80\modules\autoupgrade\upgrade/../../vendor/autoload.php' (include_path='.;C:\php\pear') in D:\wamp\www\presta80\modules\autoupgrade\upgrade\upgrade.php on line 47`

### Steps to reproduce

1. Install PS 8.0.0.
2. Try the [manual upgrade process](https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/upgrade/) to upgrade it to PS 8.0.1
3. See errors.

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.3.21

### If your bug is related to a module, specify its name and its version

autoupgrade v4.15.0

**Comment by hibatallahAouadni** [comment]
Hello @templatin 

> Using autoupgrade module v4.15.0 (with vendor folder).
I'm getting below errors while doing manual upgrade from PS 8.0.0 to 8.0.1.

Well, these two methods are different :sweat_smile: I see that the 1-Click upgrade module is already installed, so you just need to use it :wink: 

1. **BO** > **CONFIGURE** > **Shop Parameters** > **General** > **Maintenance**
2. Disable the option **Enable Store**, then **Save**
3. **BO** > **MORE** > **1-Click upgrade**
4. Check that all pre-checklist upgrade are green 
5. Then Click on **Upgrade PrestaShop now** button: 

![image](https://user-images.githubusercontent.com/23308427/215733097-88eb65dc-eccf-4bd4-b80d-7f43be13fc19.png)

Please check and feedback.

Thanks!

**Comment by templatin** [comment]
I'm familiar with using the 1-Click upgrade module but still I prefer manual upgrade method and it was working smoothly until PS 1.7.8.

The issue is in this file: `/modules/autoupgrade/upgrade/upgrade.php`

This file is copied from PS 1.7 `/install/upgrade/upgrade.php`.
It calls (require_once) multiple files whose path needs to be edited since it has been moved into `autoupgrade` module in PS 8.0.

For example, in upgrade.php on line-47:
`require_once __DIR__ . '/../../vendor/autoload.php'`

should be changed to:
`require_once __DIR__ . '/../../../vendor/autoload.php'`

I edited the path of all other files in that file and after running the `upgrade.php` in browser, it displayed blank page instead of showing any message or confirmation like in PS 1.7. So, I'm not sure whether the shop was upgraded correctly or not.

**Comment by Simchev38** [comment]
Hi 

I was trying to update a 8.0.1 to a 8.1beta using the manual upgrade method, and I had this error too.

As the beta version doesn't appear in the 1 click upgrade yet (even if I use the beta channel), it seems there is no way to update an existing version to the beta 8.1 ? thanks

**Comment by MatShir** [comment]
FYI @Simchev38 Be aware that you can't upgrade from the 8.1 beta to the 8.1 stable, sharing just in case

**Comment by Simchev38** [comment]
Thanks, But I'm using 8.0.1 stable, and trying to test the 8.1 beta.

As the "manual" update doesn't work, and the 1click upgrade does'nt show the 8.1beta available, it seems there is no way to update a shop to the 8.1beta, only a new install is possible ?

Here is the response I get in the 1click upgrade : 
Latest official version for beta channel.: 8.0 stable - (8.0.1)

**Comment by RosaBenouamer** [comment]
@Simchev38 I just see you have an alternative propose in this ticket : https://github.com/PrestaShop/PrestaShop/issues/31549

**Comment by Simchev38** [comment]
Thanks I'll have a look

**Comment by hibatallahAouadni** [comment]
Hello @templatin 

Do you still encounter the same issue with 8.1.x? Please check and feedback.

Thanks!

**Comment by templatin** [comment]
In Autoupgrade module v4.16.3, the file `/modules/autoupgrade/upgrade/upgrade.php` is still having incorrect paths so I knew it won't work. I have already [mentioned](#issuecomment-1410143006) about it in this issue.

However, I did try manual upgrade from 8.1.0 to 8.1.1 and it showed the same error messages.

**Comment by kpodemski** [comment]
@templatin 

you shouldn't use this file, in the upgraded guide you have this information:

> Manual upgrade without autoupgrade module is not possible at the moment. We recommend using [cli](https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/upgrade-module/upgrade-cli/) mechanism from the upgrade assistant module.

**Comment by florine2623** [comment]
Hello,

Since we had no news from you for more than 30 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
