### ISSUE TITLE
Error on cart when updating product quantity

### ISSUE THREAD

**Issue by Gprotin** [PrestaShop/PrestaShop#311]
When my cart contains a customization, it's impossible to update quantity of every product.
I have an error in CartController.php on line 315

![02](https://f.cloud.github.com/assets/2209843/233042/dbf4d56a-8747-11e2-8976-5bb20b48b25b.jpg)
![01](https://f.cloud.github.com/assets/2209843/233043/dc2661ca-8747-11e2-9214-5d237eb8543a.jpg)

I tried width default theme, and to update CartController.php, cart-summary.js, shopping-cart-product-line.tpl and shopping-cart.tpl

When there is no customized product, there is no problem.

**Comment by marionf** [comment]
Hello, 
This issue is old, so I close it.
If you still have it on the last version (PrestaShop 1.7.4.2), please open a new one.
Regards
