### ISSUE TITLE
API : Request Endpoint `/admin-dev/new-api/hook-status` return bad HTTP Code

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#31107]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I request the endpoint `/admin-dev/new-api/hook-status`
I receive a response where the HTTP code is 200 (Redirect to Login Page)

=> Detected by #31102

### Expected behavior

I request the endpoint `/admin-dev/new-api/hook-status`
I receive a response where the HTTP code is 4040

### Steps to reproduce

1. Request the endpoint `/admin-dev/new-api/hook-status` with method GET

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

7.4

**Comment by mflasquin** [comment]
Closed by https://github.com/PrestaShop/PrestaShop/pull/31136
