### ISSUE TITLE
Debug mode breaks admin panel

### ISSUE THREAD

**Issue by tmarsik42** [PrestaShop/PrestaShop#31101]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Debug mode breaks admin panel. After clicking "debug mode" in settings or manually setting `_PS_MODE_DEV_` to true I cant access admin panel.

Error that appears after enabling debug mode
<img width="1145" alt="Snímek obrazovky 2023-01-30 v 16 02 02" src="https://user-images.githubusercontent.com/95856146/215513292-81de9203-2a12-436d-843f-e2757de60e3c.png">

### Steps to reproduce

1. go to admin -> Advanced Parameters -> Performance -> Debug Mode on
2. you'll get an error
3. Go to defines.inc.php config and revert `_PS_MODE_DEV_` to false

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.1

**Comment by djoelleuch** [comment]
Hello @tmarsik42 ,

I didn't manage to reproduce the issue with PHP 8.1 and PHP 7.4 , see the attached screenshot : 
![image](https://user-images.githubusercontent.com/115152460/216010215-2850f5f8-f179-43cf-8cee-5fde43a7db63.png)

could you please check it . 
thank you !

**Comment by tmarsik42** [comment]
Hi, I've checked that it's broken for me with PHP 8.1 and the issue is consistent on multiple instalations.
7.4 works fine.

**Comment by sallemiines** [comment]
Hello @tmarsik42 

Ididn't manage to reproduce your issue with **PS801** and 

**PHP 7.4 OK** 

![image](https://user-images.githubusercontent.com/31663369/216625755-522b9295-53f1-4b29-a8d9-be777ead8903.png)

**PHP 8.1 OK**

![image](https://user-images.githubusercontent.com/31663369/216629686-3561e33a-1a5f-4ee4-b13a-30a656d5b053.png)

Could you please check and feedback ! 

Thank you !

**Comment by florine2623** [comment]
Hello @tmarsik42 ,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Comment by tmarsik42** [comment]
For future reference or people who come across this issue. I'm no PHP guy so I can't pinpoint the source of an issue. Maybe it's some PHP config. The solution for me was going to `vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php` and commenting `putenv('SHELL_VERBOSITY=3');` (line 127 for me)
