### ISSUE TITLE
page blanche après avoir utilisé autoupgrade pour passer en 1.7.8.8

### ISSUE THREAD

**Issue by Aureliefarid** [PrestaShop/PrestaShop#31113]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

J'ai une page blanche, je ne peux plus accéder à mon tableau de bord.
Mon site également ne s'affiche plus du tout

### Expected behavior

J'ai vidé le cache depuis le FTP mais rien ne change les pages restent blanche.

### Steps to reproduce

go to : https://chicenperle.com/fr/

go to : https://chicenperle.com/icqi7ldblkrx1prq/index.php?controller=AdminDashboard&token=63bdcd80aef876e27debb422d9abdcb7#/dashboard/activity/revenue

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

[report-issue]: https://github.com/PrestaShop/PrestaShop/issues/new/choose [prestashop]: https://www.prestashop.com/ [contribution-guidelines]: https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/project-modules/ [AFL-3.0]: https://opensource.org/licenses/AFL-3.0 [doc]: https://devdocs.prestashop.com/1.7/development/upgrade-module/

**Comment by adrienrch** [comment]
Hi, First of all you should write in English on this page. I faced this issue while upgrading. Try to enable debug mode via the FTP in the folder CONFIG > DEFINES.INC.PHP

Open defines.inc.php file.

Change the line define('_PS_MODE_DEV_', false); to define('_PS_MODE_DEV_', true);

This should help you track down the issue.

**Comment by Aureliefarid** [comment]
Hi,

Thank you for your help.

I maked changes you said and I get the error…i think… but it’s like speaking a new langage to me…

(1/1) FatalErrorException

Compile Error: Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs)
in PDOConnection.php line 70


https://chicenperle.com/icqi7ldblkrx1prq/index.php?controller=AdminDashboard&token=63bdcd80aef876e27debb422d9abdcb7#/dashboard/activity/revenue

Do you know what I have to do with that ? Could you help me please ?

Thank you

Aurélie

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : ***@***.***>
Envoyé le :lundi, 30 janvier 2023 20:07
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [PrestaShop/PrestaShop] page blanche après avoir utilisé autoupgrade pour passer en 1.7.8.8 (Issue #31113)


Hi, First of all you should write in English on this page. I faced this issue while upgrading. Try to enable debug mode via the FTP in the folder CONFIG > DEFINES.INC.PHP

Open defines.inc.php file.

Change the line define('PS_MODE_DEV', false); to define('PS_MODE_DEV', true);

This should help you track down the issue.

**Comment by adrienrch** [comment]
The Livechat pro extension seems to be the culprit for at least a part of the fatal errors. Try to disable it, then delete caches and try again to load the pages.

**Comment by Aureliefarid** [comment]
How can I disable it ? I only know errase on FTP.

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : ***@***.***>
Envoyé le :lundi, 30 janvier 2023 20:49
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [PrestaShop/PrestaShop] page blanche après avoir utilisé autoupgrade pour passer en 1.7.8.8 (Issue #31113)


The Livechat pro extension seems to be the culprit for at least a part of the fatal errors. Try to disable it, then delete caches and try again to load the pages.

**Comment by adrienrch** [comment]
Alright, I understand doing all this may be out of your knowledge. If you have a backup (you must have one every time you try to upgrade your shop), try to restore it so your shop doesn't stay down too long.

**Comment by adrienrch** [comment]
If you downloaded the Live chat pro extension from addons, you'll have to disable it through the database of your shop or try first to delete the module's package through FTP

**Comment by Aureliefarid** [comment]
I choose to deleted the livechatpro module from FTP and know I can connect.

Do I have to change value of debug in false via ftp again ?

Do I have to check something else ?

Thank you even with 0 knowledges its helped me a lot

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : ***@***.***>
Envoyé le :lundi, 30 janvier 2023 21:08
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [PrestaShop/PrestaShop] page blanche après avoir utilisé autoupgrade pour passer en 1.7.8.8 (Issue #31113)


If you downloaded the Live chat pro extension from addons, you'll have to disable it through the database of your shop or try first to delete the module's package through FTP

**Comment by adrienrch** [comment]
Alright. Glad I could help you. And yes you can go in the back office > Performances > Disable debug mode. It's a little switch

**Comment by Aureliefarid** [comment]
Ok I did it all seems to be ok.

Thank you so much for helping me so fast and easier.

I know I have to learn how to install on local I think it can help for those problems.

Have a good Week.

Aurélie

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : ***@***.***>
Envoyé le :lundi, 30 janvier 2023 21:38
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [PrestaShop/PrestaShop] page blanche après avoir utilisé autoupgrade pour passer en 1.7.8.8 (Issue #31113)


Alright. Glad I could help you. And yes you can go in the back office > Performances > Disable debug mode. It's a little switch

**Comment by hibatallahAouadni** [comment]
Hello @Aureliefarid 

@adrienrch thanks for your quick replies and helping @Aureliefarid :pray: :rocket: 
Closing the issue as your problem is not related to Core :wink: 

Thanks!

**Comment by Aureliefarid** [comment]
Hello,

I noticed some changes since the upgrade in my footer (only now sorry I doesn't use my website I am already in post partum "holidays" and I try to prepare my recovery step by step)

1. Social links are not aligned in footer and pass over, link list and customer account as you can see **https://chicenperle.com** 

2.And I had to disable langages for customers because it won't translate and make home pages with full errors, and when I wanted to came back in French (default langage it make 404 not found)

Thank you for telling me all you know about that and for your help.
PS : You can reply during the week it's not an emergency, I desable payment, I have no customers for now I am not working as I said ;)

Aurélie
