### ISSUE TITLE
Translation app URL, refresh and selection issues

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#31115]
### Describe the bug and add attachments

There are multiple issues with translations I found.

### Steps to reproduce

1. Get develop.
2. Go to BO > International > Translations.
3. Select `Front office translations` > `Core` > `Any language`.
4. Click modify.
5. See that the URL is weird - `http://localhost/dev/admin-dev/translations/dev/admin-dev/index.php/improve/international/translations/?lang=cs&type=themes&locale=cs-CZ&selected=0&_token=J5NKtedIAAf0GJu46m40uWTY6OTcB_yZsn-rlnzPnDA` - **Issue 1**
6. Hit refresh or F5 - error 404 - **Issue 2**
7. Go back in your browser, see that `Front office translations` are still selected, but not the second selectbox. - **Issue 3**
8. Click modify. Translation app loads and red `undefined` toast is shown in right top corner - **Issue 4**

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

I reproduce this issue only on develop, it's a regression!
I'll add it to the backlog to be fixed.
Waiting for your PR 🚀 

Thanks!

**Comment by Hlavtox** [comment]
@MatShir Is this in the correct kanban category? It must be fixed :P

**Comment by boherm** [comment]
On it! :-)
