### ISSUE TITLE
Cart update when clic on bin our update amount

### ISSUE THREAD

**Issue by Krustytek** [PrestaShop/PrestaShop#31127]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi, my cart doesn't update when I change the number of items or when I delete an item.
it works when F5.

Looks like there is a problem with the core.js but I can't find the problem.

any ideas ?

Erreur dans les liens source : Error: request failed with status 404

URL du lien source : core.js.map

**Comment by Krustytek** [comment]
Problem solved with upgrade to 8.0.1

**Comment by hibatallahAouadni** [comment]
Glad to hear :tada:
