### ISSUE TITLE
ServiceNotFoundException - prestashop.adapter.product.options.redirect_target_provider

### ISSUE THREAD

**Issue by Imunal** [PrestaShop/PrestaShop#31129]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

Today we got a 500 error on one of our Prestashop websites. After manually turning on a debug mode in define.php we got an error:

```
(1/1) ServiceNotFoundException
The service "prestashop.adapter.product.options.redirect_target_provider" has a dependency on a non-existent service "prestashop.adapter.product.repository.product_preview_repository".
```

We cannot find any information about this problem, anyone can help resolving that?

### Steps to reproduce

.

### PrestaShop version(s) where the bug happened

1.7.8.8

**Comment by hibatallahAouadni** [comment]
Hello @Imunal 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by coop2540** [comment]
Hi
I'm in the same problem.
Prestashop 1.7.8.8
PHP 7.4
Apache2
Debian 10

**Comment by alvgalrus** [comment]
@hibatallahAouadni I have the same issue when upgrading from 1.7.8.6 to 1.7.8.8.

1.7.8.6 to 1.7.8.7 is fine, but 1.7.8.7 to 1.7.8.8 fails too.

```
php7.4 install/upgrade/upgrade.php
PHP Notice:  Undefined index: SCRIPT_NAME in <ps_root>/install/init.php on line 47
PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "prestashop.adapter.product.options.redirect_target_provider" has a dependency on a non-existent service "prestashop.adapter.product.repository.product_preview_repository". in <ps_root>/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:31
Stack trace:
#0 <ps_root>/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(60): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Object(Symfony\Component\DependencyInjection\Reference), false)
#1 <ps_root>/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehavior in <ps_root>/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php on line 31
Status: 500 Internal Server Error
X-Powered-By: PHP/7.4.33
```

I've tried to grep both services mentioned into all the codebase without luck, weird.

The steps to reproduce are just upgrading, either from the 1-click module or manually (replacing files and running the update script).

The result is a blank admin backend, maintenance page still works.

**Comment by alvgalrus** [comment]
It seems the issue was caused by a reverted update from Prestashop 8, there were some leftover files:
- <ps_root>/src/Adapter/Product/Options/RedirectTargetProvider.php
- <ps_root>/src/Adapter/Product/QueryHandler/GetProductForEditingHandler.php

So last night I erased `src` completely and replaced it with the folder from PrestaShop's 1.7.8.8 release. Just in case also `vendor` and `var/cache/prod`.
