### ISSUE TITLE
Contact info on homepage's footer do not update

### ISSUE THREAD

**Issue by NOLEGGITEVBARI** [PrestaShop/PrestaShop#31134]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi all,

I need help with updating our shop's contact information (infois displayed on the footer).
Currently using Prestashop 1.7.8.5 , I updated the phone number via Design > Theme & logo > Pages configuration > Hompage footer > Store by filling in the field.
However the modification I made are not reflected on the store's homepage.

Can I get any help on this please?

### Expected behavior

The new phone number should be correctly displayed on the website homepage footer.

### Steps to reproduce

 Design > Theme & logo > Pages configuration > Hompage footer > Store 
Prestashop: telephone number changed correctly:
![prestashop-bug-2023-01-31-1](https://user-images.githubusercontent.com/124072067/215817927-5e4a3f38-e017-4855-abc0-90bca365a464.png)

Homepage footer not reflecting changes
![prestashop-bug-2023-01-31-2](https://user-images.githubusercontent.com/124072067/215817953-87708005-98e3-4564-b3d6-f8c264170707.png)

### PrestaShop version(s) where the bug happened

1.7.8.5

**Comment by Hlavtox** [comment]
Your TPL has been modified and it has whatsapp hardcoded.

I suggest looking into `/themes/yourtheme/modules/ps_contactinfo/ps_contactinfo.tpl` or hiring a specialist to do it. 👍

**Comment by NOLEGGITEVBARI** [comment]
> Your TPL has been modified and it has whatsapp hardcoded.
> 
> I suggest looking into `/themes/yourtheme/modules/ps_contactinfo/ps_contactinfo.tpl` or hiring a specialist to do it. 👍

Hi Hlavtox,

I am following your instructions, but apparently there is no ps_contactinfo string when browsing on the Theme page

![prestashop-bug-2023-01-31-3](https://user-images.githubusercontent.com/124072067/215840005-45c0e976-4fc4-4d22-9915-03cbe25c363c.png)

Can you help me figure it out?

**Comment by Hlavtox** [comment]
@NOLEGGITEVBARI I sent a path to a file, you must edit your store files (via FTP for example). :-)

**Comment by NOLEGGITEVBARI** [comment]
Hi,

Sorry for the spam but I actually got wher I was supposed to look.
Still, even if I changed the phone number on Prestashop, the update is not reflected on the footer of the homepage...
Moreover, I cannot update the WhatsApp contact module - an error prompt occurs when I try to execute the update.

**Comment by Hlavtox** [comment]
If you change something in the TPL and the changes are not showing, make sure that your Smarty settings in Performance section is NOT set to "Never recompile template files".

Contact me on info@danielhlavacek.cz, I can provide support. 👍

**Comment by NOLEGGITEVBARI** [comment]
I finally found what all the fuss was all about.
I just needed to update ALSO another module, then any changes to the footer are applied correctly.
Thank you for your help!
