### ISSUE TITLE
Bug on Admin Product Page

### ISSUE THREAD

**Issue by frozzen-git** [PrestaShop/PrestaShop#31133]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
I have a "undefined" category name after clicking button "Create" in "Create a New Category" form on Product Page **if my default language is not ID=1**. After refreshing Product Page new category name is displayed correctly.
![изображение](https://user-images.githubusercontent.com/89405630/215771047-92b7e48c-36e5-4580-80e7-ddeec3bd964d.png)

 /src/PrestaShopBundle/Controller/Admin/CategoryController.php: addSimpleCategoryFormAction[53]
/admin/themes/default/js/bundle/product/form.js [322]

### Steps to reproduce

1. set PS_LANG_DEFAULT <> 1
2. click Create a Category
3. input Category name
4. click Create

### PrestaShop version(s) where the bug happened

1.7.8.8, 8.0

**Comment by HanaRebaiQA** [comment]
Hello @frozzen-git 

Thanks for your report.
Could you please provide us with a clear and concise step to reproduce the bug ? Step 1 is not clear, which language did you use, and how to reproduce it exactly?

Thank You

**Comment by frozzen-git** [comment]
Hello @HanaRebaiQA 

My language configuration:

![Снимок экрана от 2023-02-03 09-17-18](https://user-images.githubusercontent.com/89405630/216527446-9e8b5623-1d94-45ea-a9db-edfa84d87a0d.png)
![Снимок экрана от 2023-02-03 09-18-09](https://user-images.githubusercontent.com/89405630/216527448-89e7adb2-89c8-4894-b25e-acc2bcd7f42e.png)

But I don't think language matters. The important thing is that the **default language is not with id=1**

**Comment by sallemiines** [comment]
Hello @frozzen-git 

I didn't manage to reproduce your issue , you can see the attached screen record 


https://user-images.githubusercontent.com/31663369/216637526-a0cff893-1ec2-46b1-bb9c-98dd7ba78527.mp4


Did I miss smthg ! 
Please check and feedback ! 


Thank you

**Comment by frozzen-git** [comment]
@HanaRebaiQA    @sallemiines 
You must Create a New Category on Product Page!!

**Comment by frozzen-git** [comment]
Hi @sallemiines 
You made the wrong movie :)
You must add a new category on the Add Product Page!

**Comment by florine2623** [comment]
Hello @frozzen-git ,

I can't reproduce your issue.

<img width="324" alt="Screenshot 2023-12-21 at 17 24 36" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/845b396c-a4a3-43e3-aca4-acec39057329">


I'm closing the issue to avoid clogging the backlog.
