### ISSUE TITLE
Bug in 1-Click Upgrade

### ISSUE THREAD

**Issue by Bruno0612** [PrestaShop/PrestaShop#31141]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

My prestashop version is 1.5.3.0. I would like tu uprade it.
I installed 1-Click Upgrade module; It's the version 1.6.8 ot the module. 
When I want to configure it to upgrade Prestashop, there was a error message : Update - Download 1-Click Upgrade. But I can't upgrade it.

It asked the prestashop support, who send me a link to download a new version of 1-Click-Upgrade (4.15.0). When when I would like to install it, there was an error message : the version of your module is not compliant with your Prestashop version.
How could I upgrade my Prestashop from 1.5.3.0 ?
Thanks for your help

![1-click-upgrade error 1](https://user-images.githubusercontent.com/124088674/215906354-f2a0f33a-7a46-4d5d-9635-1302c4b7ff11.PNG)
![1-click-upgrade error 2](https://user-images.githubusercontent.com/124088674/215906432-516acaa7-6b76-4375-b30e-006ac68f0f3c.PNG)
![1-click-upgrade error 3](https://user-images.githubusercontent.com/124088674/215906476-973b4b31-d01c-4236-9974-950a2035e8b6.PNG)

### Steps to reproduce

1. Go To Modules
2. Search 1-click Upgrade
4. Install. It's the version 1.6.8 of the module
5. Configure
6. There is a red cross at the first line "The module 1-click upgrade ... Upgrade - Download"

After the support send me a link to download the new version of the module 1-click Upgrade 
1. Add a module
2. Select "autoupgrade.zip"
3. Install. It's the version 4.15.0 of the module
4. there is a error message " the version of your module is not compliant with your Prestashop version."

### PrestaShop version(s) where the bug happened

1.5.3.0

### PHP version(s) where the bug happened

5.6.40

### If your bug is related to a module, specify its name and its version

1-click Upgrade version 1.6.8 and 4.15.0

**Comment by adrienrch** [comment]
Hi, the 4.15 version of the auto upgrade module is not the one you should use to upgrade your store. Try with an older version of the module. https://github.com/PrestaShop/autoupgrade/releases/download/v4.14.2/autoupgrade.zip

**Comment by adrienrch** [comment]
See the release notes of the 4.15 module :
This release enables upgrading process from 1.7.x to 8.0.x versions.
The minimum PrestaShop compatibility version has been bumped to 1.7. If you upgrade from a version older than 1.7, please use a previous version of this module.

As usual, please build a backup of your shop before upgrading it.

**Comment by djoelleuch** [comment]
Hello,
PrestaShop 1.5 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).
Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.
Thank you !

**Comment by Bruno0612** [comment]
Thank you Adrien.

How can I find a previous version of this module ? Could you send me it ?

Thanks.

Bruno

 

De : Adrien ***@***.***> 
Envoyé : mercredi 1 février 2023 10:04
À : PrestaShop/PrestaShop ***@***.***>
Cc : Bruno0612 ***@***.***>; Author ***@***.***>
Objet : Re: [PrestaShop/PrestaShop] Bug in 1-Click Upgrade (Issue #31141)

 

See the release notes of the 4.15 module :
This release enables upgrading process from 1.7.x to 8.0.x versions.
The minimum PrestaShop compatibility version has been bumped to 1.7. If you upgrade from a version older than 1.7, please use a previous version of this module.

As usual, please build a backup of your shop before upgrading it.

**Comment by Bruno0612** [comment]
Thank you Adrine.

I try it. Unfortunately I also have a erroe message. There is a Red Cross for « The module must have the last version »

 

 

De : Adrien ***@***.***> 
Envoyé : mercredi 1 février 2023 10:02
À : PrestaShop/PrestaShop ***@***.***>
Cc : Bruno0612 ***@***.***>; Author ***@***.***>
Objet : Re: [PrestaShop/PrestaShop] Bug in 1-Click Upgrade (Issue #31141)

 

Hi, the 4.15 version of the auto upgrade module is not the one you should use to upgrade your store. Try with an older version of the module. https://github.com/PrestaShop/autoupgrade/releases/download/v4.14.2/autoupgrade.zip
