### ISSUE TITLE
SQL error with Related Products Module

### ISSUE THREAD

**Issue by MFX86** [PrestaShop/PrestaShop#31149]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

SQL error with Related Products Module

 
![imatge](https://user-images.githubusercontent.com/111896322/216024654-397237bb-1083-4003-b2f6-79e620991f33.png)

### Steps to reproduce

1. Module Active
2. No related products shown in Home page
3. Hooks seems to be ok
4. Activate debug mode
5. SQL error is shown
6. uninstall module
7. No error - No products in Home Page
8. Delete module folder
9. re-install module
10. error is back again

### PrestaShop version(s) where the bug happened

1.7.8.8 

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

Related Products

**Comment by Hlavtox** [comment]
Can you please send us your classes/Category.php file in a zip? I cannot find the failing clause `NOT IN (` anywhere in the codebase, I think your core is modified.

**Comment by MFX86** [comment]
I'm using a child theme of classic theme but I think that this archive was not modified. Thanks

[Category_php.zip](https://github.com/PrestaShop/PrestaShop/files/10557885/Category_php.zip)

**Comment by Hlavtox** [comment]
@MFX86 You are using some overrides - `override/classesCategory.php`, remove them or fix them, then your shop will work. 👍

**Comment by MFX86** [comment]
Thanks it works!!!!!
