### ISSUE TITLE
Translation issue on the Information page

### ISSUE THREAD

**Issue by paulnoelcholot** [PrestaShop/PrestaShop#31150]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

These two messages have not been translated

![image](https://user-images.githubusercontent.com/112863083/216065662-b192cdc0-de6b-4161-a084-90eca3126316.png)

### Expected behavior

These two messages should be translated

### Steps to reproduce

1. On a back office translated into French
2. On BO>Configurer>Informations
3. See error

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4

**Comment by paulnoelcholot** [comment]
@l-delin

**Comment by l-delin** [comment]
The two strings are NOT available on Crowdin, so they're not available for translation.

See:
**1. You must provide this information when reporting an issue on GitHub or on the forum.**
![image](https://user-images.githubusercontent.com/113511191/216065766-3423100c-200e-4503-a7f5-bba6ba4a93ea.png)

**2. No overrides have been found**
![image](https://user-images.githubusercontent.com/113511191/216066024-09521246-a655-4cc3-9742-66dfedca1785.png)

**Comment by djoelleuch** [comment]
Hello @paulnoelcholot 

I reproduce this issue only on develop, it's a regression! :rocket: 
![image](https://user-images.githubusercontent.com/115152460/216081447-ae8e86d2-259f-431c-ac8e-222220e69f9a.png)

I'll add it to the backlog to be fixed.

Thank youuu !

**Comment by Hlavtox** [comment]
@paulnoelcholot @djoelleuch There could be hundreds of missing strings, catalog was not yet pushed to crowdin. It will be fixed as usual.
