### ISSUE TITLE
Update to Prestashop 8

### ISSUE THREAD

**Issue by neokat29** [PrestaShop/PrestaShop#31168]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Error that appears when updating to Prestashop 8: Could not close the Zip file properly. Check you are allowed to write on the disk and there is available space on it.

![Capture d’écran 2023-02-03 134730](https://user-images.githubusercontent.com/124276957/216609602-9fd8f941-448c-46a5-ab82-74802f3d6ddd.jpg)

### Steps to reproduce

1. mettre à jour

### PrestaShop version(s) where the bug happened

from 1.7.8.8 to 1.8

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

1-click upgrade 4.15.0

**Comment by HanaRebaiQA** [comment]
Hello @neokat29 

Thanks for your report.
Could you please provide us with a clear and concise step to reproduce the issue with a screenshot or a screen record of the bug? 

I think that in the `PrestaShop version(s) where the bug happened` section you meant: from 1.7.8.8 to 8.1 and not 1.8 ?
in this case, does this [issue](https://github.com/PrestaShop/PrestaShop/issues/30761) similar to yours?

Thank You!

**Comment by neokat29** [comment]
![Capture d’écran 2023-02-03 134730](https://user-images.githubusercontent.com/124276957/216609602-9fd8f941-448c-46a5-ab82-74802f3d6ddd.jpg)

**Comment by neokat29** [comment]
I will wait for the solution to be found before going crazy

**Comment by sallemiines** [comment]
Hello @neokat29 

Could you provid us the zip That you used for the upgrade ? 
and as @HanaRebaiQA mentionned : in the `PrestaShop version(s) where the bug happened` section you meant: from 1.7.8.8 to 8.1 and not 1.8 ?

and please check if this issue https://github.com/PrestaShop/PrestaShop/issues/30761 similar to yours?

Waiting for your feedback ! 
Thank you !

**Comment by neokat29** [comment]
This is the update from 1.7.8.8 to 1.8.0.1
#30761 is not the same issue as me

**Comment by neokat29** [comment]
https://www.dropbox.com/t/wK7vQ3gAn1mcKZLs
for the ZIP file

**Comment by hibatallahAouadni** [comment]
Hello @neokat29 

For your information Sir, there's no 1.8.0.1 it's just 8.0.1 😉 
Please follow these steps to upgrade your shop successfully: 

1. Grant the access to your shop's files (write and read)
2. Enable the **maintenance** mode
3. Check that all **`PrestaShop requirements are satisfied`** in 1-Click upgrade module Configure page
4. Check in the **Start Your upgrade** block that: `Latest official version for minor channel.: 8.0 stable - (8.0.1)`
5. Then click on the **`Upgarde now`** button (please provide a screenshot of this page before upgrading)
6. Check if you still encounter the issue

Please Check and feedback.

Thanks!

**Comment by neokat29** [comment]
Hello, don't have latest official version for minor channel 8.0 stable... always 1.7.8.8.

**Comment by florine2623** [comment]
Hello @neokat29 ,

You can choose Local archive and add the zip file of 8.0 in `adminXXX.autoupgrade/download`.
Step 1:
<img width="1209" alt="Screenshot 2023-02-07 at 15 41 08" src="https://user-images.githubusercontent.com/16019289/217276155-9603c31c-10eb-4c92-9187-122efad4c0fb.png">
Step 2:
<img width="1227" alt="Screenshot 2023-02-07 at 15 42 52" src="https://user-images.githubusercontent.com/16019289/217276376-8612c8f1-5d0c-4611-944b-9853142531d9.png">
