### ISSUE TITLE
The service "prestashop.adaptater.product.options.redirect_target_provider" has a dependency on a non-existent service

### ISSUE THREAD

**Issue by JRichar97** [PrestaShop/PrestaShop#31161]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

![image](https://user-images.githubusercontent.com/124252502/216291410-c6c84166-48c2-444f-9316-92f6de7ccab9.png)
 
I get the following problem when I make some changes to the site.

The backoffice becomes inaccessible

### Steps to reproduce

I don't know the steps because this happens a few times after classic modifications such as translation for example

### PrestaShop version(s) where the bug happened

1.7.8.8

**Comment by HanaRebaiQA** [comment]
Hello @JRichar97 

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template and provide clear and concise steps to reproduce the bug**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
