### ISSUE TITLE
problem of adding to the wishlist when you are part of several customer groups

### ISSUE THREAD

**Issue by GuillaumeKoeglerSeiler** [PrestaShop/PrestaShop#31172]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, I noticed in this version that if a customer is part of several groups of customers, the product is added as many times as it is part of a group, the SQL query adds a product for each CustomerGroup

### Expected behavior

A product added in the notification list must be displayed once in the wishlist

### Steps to reproduce

1. have a client who belongs to several groups
2. add a product to the wishlist
3. check

### PrestaShop version(s) where the bug happened

1.7.7.3

### If your bug is related to a module, specify its name and its version

blockwishlist

**Comment by HanaRebaiQA** [comment]
Hello @GuillaumeKoeglerSeiler 

Thanks for your report.
Could you please provide us with more clear and concise steps to reproduce the bug with a screenshot or a screen record ?

Thank You!

**Comment by GuillaumeKoeglerSeiler** [comment]
I solved the problem, you have to go to the WishListProductSearchProvider and add to the QuerySearch request a group by id_product so that it is not added in duplicate, or triple if the client is part of several groups.
