### ISSUE TITLE
Shop association between combination and shop not found when updating product

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#31170]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Product page v2.
Error happens when we try to load combination by shop constraint (CombinationRepository->getByShopConstraint) using All shops constraint. For All shops code tries to load combination for default shop, but in case it doesn't exist it will throw exeception.
For example doing product with combinations update, code will try update all default suppliers and for that it will search for combinations in all shops (because suppliers are not related specifically to any shop) and it will throw
<img width="1268" alt="Screenshot 2023-02-02 at 18 19 06" src="https://user-images.githubusercontent.com/31609858/216381215-9e6f8c92-e595-4731-86f1-be4a78a58873.png">
 CombinationShopAssociationNotFoundException. 

### Expected behavior

Its valid case that combination might not exist in some shop, but we still need to get combination info, so instead of error we should fallback to any another combination that is associated to shop.

### Steps to reproduce

1. Have multishop enabled and at least 2 shops.
2. Go to product v2 combination tab
3. Generate any different combinations in those 2 shops (its important that combinations between shops differs, else doesn't matter)
4. try to update any product field, lets say "label when in stock" with some random valid value
5. Save & see error `An unexpected error occurred. [PrestaShop\PrestaShop\Core\Domain\Product\Combination\Exception\CombinationShopAssociationNotFoundException code 0]: Could not find association between Combination {someId} and Shop {some shop id}`

### PrestaShop version(s) where the bug happened

8.1.x, develop

**Comment by HanaRebaiQA** [comment]
Hello @zuk3975 

Thanks for your report.
I was able to reproduce your issue using the same steps to reproduce on develop with only **Product V2**

**Product V2 : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/216397130-2d9633dd-ef56-418a-acbb-e9931c11c909.png)

**Product V1 : OK** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/216397253-dcf510f3-ec1b-433a-b21e-fd871dd259e2.png)

Indeed, it's a regression on Product V2 page.
I'll add this to the debug backlog so that it's fixed and Thanks for your PR.

**Comment by florine2623** [comment]
I have the same error with a different display :
<img width="1424" alt="Screenshot 2023-02-09 at 10 58 36" src="https://user-images.githubusercontent.com/16019289/217780329-8dc7f19b-c2e3-4761-aeed-9b6febbee86d.png">

Also, the steps to reproduce are different.
The problem only occurs when I try to modify the combination table in Combination Tab.
If I don't click on `Cancel` on the combination Tab, the button `Save and publish` is greyed out, therefore I can't update my product page.
