### ISSUE TITLE
8.0.0 Unable to upload new banner to module ps_imageslider.

### ISSUE THREAD

**Issue by RoseannePeeters** [PrestaShop/PrestaShop#31194]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Trying to upload a new banner image to the ps_imageslider but I get following error: "@getimagesize path cannot be empty".
I have made [a bug report about this earlier](https://github.com/PrestaShop/PrestaShop/issues/30656) but I have new information now.
![image](https://user-images.githubusercontent.com/119082127/216633809-9acd0742-7010-4c3d-b0c9-f1590cfc5f5f.png)
After doing some more research on the code that was erroring, I came to the conclusion that the '@' Error Control Operator doesn't disable critical errors that will terminate script execution. You can find this in [their documentation](https://www.php.net/manual/en/language.operators.errorcontrol.php) saying: 
```
Warning

Prior to PHP 8.0.0, it was possible for the @ operator to disable critical errors that will terminate script execution. For example, prepending @ to a call of a function which did not exist, by being unavailable or mistyped, would cause the script to terminate with no indication as to why.
```
I've downloaded the latest and greatest version of ps_imageslider and this still uses the @ operator which will always throw errors in PHP 8 due to the operator not working the same and the algorithm not being altered.

### Expected behavior

Image gets uploaded succesfully.

### Steps to reproduce

Go to Design=>Theme and logo => Pages configuration => Slider => Configure
Click change on any of the banners
Choose a new image
Click save

### PrestaShop version(s) where the bug happened

8.0.0 - 8.0.1 - develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_imageslider

**Comment by zaaidaann** [comment]
im using prestashop 8.0.1, while updating slider images, 


Oops! An Error Occurred
The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by RoseannePeeters** [comment]
> im using prestashop 8.0.1, while updating slider images,
> 
> Oops! An Error Occurred The server returned a "500 Internal Server Error".
> 
> Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

Yes and probably when you turn your debug mode on it will tell you the same error as above. Could you try that please?

**Comment by hibatallahAouadni** [comment]
Hello @zaaidaann & @RoseannePeeters 

I didn't manage to reproduce the issue with PS800, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/216926940-1feb6f4e-71ce-47f4-9e3c-088a7d87bbc5.png)

Could you please provide a screen record or some screenshots to understand better the cause of your issue 🙏 
Waiting for your feedback.

Thanks!

**Comment by RoseannePeeters** [comment]
> Hello @zaaidaann & @RoseannePeeters
> 
> I didn't manage to reproduce the issue with PS800, see the attached screenshot below:
> 
> ![image](https://user-images.githubusercontent.com/23308427/216926940-1feb6f4e-71ce-47f4-9e3c-088a7d87bbc5.png)
> 
> Could you please provide a screen record or some screenshots to understand better the cause of your issue 🙏 Waiting for your feedback.
> 
> Thanks!

Hey thanks for responding, 

Could you please confirm which version of PHP you are using and the version of ps_imageslider, because like I stated above if you are using a version prior to PHP 8 the bug will not represent, since the Error Control Operator still has the functionality of disabling critical errors like stated above.

My version of PHP is 8.1 and ps_imageslider version is 3.1.1.

I will not provide any screenshots or records, since these are the exact steps I followed to get to my image above:

Go to Design=>Theme and logo => Pages configuration => Slider => Configure
Click change on any of the banners
Choose a new image
Click save

If you could please confirm me your php version and version of ps_imageslider so we can narrow it down :)

Thanks

**Comment by AureRita** [comment]
Hi @RoseannePeeters  ,

Thank you for your report ! I reproduce the issue with PrestaShop version 8.0.1 and not with the version 1.7.8.8 as you can see : 

[Untitled_ Feb 3, 2023 5_11 PM.webm](https://user-images.githubusercontent.com/100699445/216991997-d9e834f6-7a6d-4d6e-be44-d167410cd9dc.webm)


 Nice catch ! It's a regression ! I'll add it to the patch backlog.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by zaaidaann** [comment]
@AureRita @hibatallahAouadni @RoseannePeeters 

thats what i told in my  ** https://github.com/PrestaShop/PrestaShop/issues/31203 **

 ps_imageslider when updating anything from sample, >> shows internal server error #31203 
 
 ive attached a video to it.
 
 also i closed this issue, but @hibatallahAouadni  labelled it invalid lol**
 
 i fixed this, issue on ps8.0.1
 
 i updated the ps_image slider from downloading the error free version from here 
 
 https://github.com/PrestaShop/ps_imageslider/archive/refs/heads/dev.zip
 
 [ps_imageslider-dev(1).zip](https://github.com/PrestaShop/PrestaShop/files/10671722/ps_imageslider-dev.1.zip)

**Comment by tajriba** [comment]
PS version 801 with imageslider 3.1.1 has this bug.
the dev version is fine as mentioned here: https://github.com/PrestaShop/PrestaShop/issues/31203#issuecomment-1416794663
why?

**Comment by Eltioflipe3D** [comment]
> @AureRita @hibatallahAouadni @RoseannePeeters
> 
> thats what i told in my ** #31203 **
> 
> ps_imageslider when updating anything from sample, >> shows internal server error #31203
> 
> ive attached a video to it.
> 
> also i closed this issue, but @hibatallahAouadni labelled it invalid lol**
> 
> i fixed this, issue on ps8.0.1
> 
> i updated the ps_image slider from downloading the error free version from here
> 
> https://github.com/PrestaShop/ps_imageslider/archive/refs/heads/dev.zip
> 
> [ps_imageslider-dev(1).zip](https://github.com/PrestaShop/PrestaShop/files/10671722/ps_imageslider-dev.1.zip)

that did the trick, thanks

**Comment by CJH297** [comment]
Adding to the reports: I have a new install of 8.00, immediately upgraded to 8.01, and as reported above, any 'save' applied to changes (text, image, anything) produces a 500 error. I also have a slider from a respected third party and this behaves the same way. I found this thread and installed the -dev file linked above and showing v3.1.1 (cache cleared, both smarty and var) but the 500 error persists for me, despite being marked as solved

**Comment by boherm** [comment]
It seems to be resolved by https://github.com/PrestaShop/ps_imageslider/commit/eca49edc1166cad6d0cb122dca1331ff4bb43ce3 few months ago.
A new version can be done I think!

**Comment by CJH297** [comment]
Thanks for taking the time to reply, boherm

Being very much a beginner with code, does that mean I simply need to switch the php file with the one you have linked to? There doesn't seem to be an updated module.

But also, I have used the 'new' module [ps_imageslider-dev(1).zip](https://github.com/PrestaShop/PrestaShop/files/10671722/ps_imageslider-dev.1.zip) from the link two weeks ago, and it did not work for me. Still error 500, just as earlier reports.

**Comment by matks** [comment]
Dear @PrestaShop/qa-functional , according to @boherm the PR https://github.com/PrestaShop/ps_imageslider/pull/75 might be fixing this problem 😉 could you please confirm?

Please note PR https://github.com/PrestaShop/ps_imageslider/pull/75 has been milestoned for ps_imageslider 3.1.2 which has not been released yet. So I think in the next days I might trigger a ps_imageslider release 😄

**Comment by CJH297** [comment]
Thanks for the update. I might add, there seems to be something fundamental going on. I have the same 500 error with third party sliders that I have tried (even though marked good for 8.0.1).

**Comment by florine2623** [comment]
Indeed I have reproduced this bug :
<img width="1082" alt="Screenshot 2023-03-09 at 14 21 58" src="https://user-images.githubusercontent.com/16019289/224035849-bf6c6592-58bc-425e-a175-ce3b5c94175f.png">

After testing https://github.com/PrestaShop/ps_imageslider/pull/75, I can confirm the bug is fixed :
<img width="1225" alt="Screenshot 2023-03-09 at 14 24 07" src="https://user-images.githubusercontent.com/16019289/224036379-a2bb86ff-4b22-439e-852c-51d079b8e22d.png">

I'm closing this issue to avoid clogging the backlog.
Thanks!

**Comment by CJH297** [comment]
Good news that it is fixed (I guess I have to wait for the new module update to be released). I read the older 'fixed' thread and saw that it was tested in php7.4. I can confirm the module works in the older php, but my version 3.1.1 does not in php8.1

**Comment by CJH297** [comment]
Reporting that the module works fine with 8.0.1 and php8.1, with thanks to all.

The associated instruction/explanation text might need an update - this refers to setting the size of the image in the settings area (but there is no such control)
