### ISSUE TITLE
Impossible to have Prestashop 8 installed correctly from CLI 

### ISSUE THREAD

**Issue by AdrienPlx** [PrestaShop/PrestaShop#31198]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I try to install prestashop 8.0.1 on a server or a local env, there is no Image format automatically created with the classic theme and we got these warnings displayed :
![image](https://user-images.githubusercontent.com/43446598/216648873-4fcadbc6-2435-4705-abab-2bf133985053.png)
Also there is several modules that are not installed (ps_mbo, ps_metrics...)
I'm trying to upgrade our auto install tool from our server like I used to do since presta 1.7 but this new version is killing me, I do not have any solution...
I precise that if I change theme for our custom theme, image formats are generated and there is no problem. It's just classic theme at installation ! Also, with module click upgrade from 1.7.8.8 to 8.0.1 we don't have these problems !

### Expected behavior

We just need a correct installation with CLI for prestashop 8.0.1. 

### Steps to reproduce

Juste follow the documentation => https://devdocs.prestashop-project.org/8/basics/installation/localhost/

1. clone branch 8.0.x 
2. composer install
3. index_cli.php insallation
4. make assets (or use files compilated in a personnal git)
5. check the website => imageRetriever warnings !

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.1

**Comment by hibatallahAouadni** [comment]
Hello @AdrienPlx 

> index_cli.php insallation
make assets (or use files compilated in a personnal git)

You should execute the command make assets, then install with index_cli 😉 
Please check and feedback.

Thanks!

**Comment by AdrienPlx** [comment]
Hello ! 
It's much better in this order haha thanks ! ;) 
I try with our own Git with our theme and I tell you if it's ok !

**Comment by AdrienPlx** [comment]
It's normal to have a lot of updates to do on modules when we install prestashop 8.0.x with CLI ??
![image](https://user-images.githubusercontent.com/43446598/217025075-e0b13cf6-3486-4093-ace9-912d30377667.png)

**Comment by hibatallahAouadni** [comment]
Hello @AdrienPlx 

Thanks for your feedback!
Glad to hear that your problem has been solved 🎉 
About your question, I'm not quite sure but let's analyze it by logic 😉 You modify your composer.json with the latest versions modules when the new version of Presta is released, then after awhile you install the shop, and there will be new versions released of some modules. So it makes sense to have modules updates.
Closing the issue as there's no bug 😉 

Thanks!

**Comment by AdrienPlx** [comment]
Hi, 

Ok so we just need to upgrade module versions in composer ^^
Just one more question, when I add module ps_mbo to our installation, the installation is dropping an error on installation of the module. Do you know why this one is not installed by default ? 

Many thanks for your help !
