### ISSUE TITLE
Backoffice Prestashop 404

### ISSUE THREAD

**Issue by beautifullook** [PrestaShop/PrestaShop#31191]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Good morning, I can't access my Prestashop Backoffice, it gives me the following error message: Failed to load resource: the server responded with a status of 404 ()

So far I can only fix the problem by doing the restore on the server.
![2023-02-03_124707](https://user-images.githubusercontent.com/44585313/216600116-d7eedae8-7662-4887-a31f-d78ac95d411d.png)

### Steps to reproduce

1. Go to Backoffice of Prestashop  
2. Click to Login

![2023-02-03_124707](https://user-images.githubusercontent.com/44585313/216600541-9650b965-1cfe-450d-a16e-d81ea585d5c4.png)

### PrestaShop version(s) where the bug happened

1.7.7.1

### PHP version(s) where the bug happened

7.4

**Comment by kpodemski** [comment]
Hello @beautifullook 

As discussed on Slack, 1.7.7.1 is not compatible with PHP 7.4.

**Comment by beautifullook** [comment]
ok I'm trying to upgrade it with the Click Upgrade module, but I get an unsatisfied requirement (see attachment):
It's not possible to write in the following folders:
themes/PRS062/cache/
![2023-02-03_135033](https://user-images.githubusercontent.com/44585313/216608043-8a9e0195-d60e-47f2-adfc-96ada86002fd.png)
