### ISSUE TITLE
Github action to push towards Crowdin

### ISSUE THREAD

**Issue by WahbiPS** [PrestaShop/PrestaShop#31197]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

- Pushing into Crowdin is an annoying task, it should be automated to avoid human errors and losing too much time.

### Describe the solution you'd like

- We should make a github action that allows to manually update and push to crowdin

#### Description

- see issue: https://github.com/PrestaShopCorp/TranslationTool/issues/128

#### Complexity
Size S

**Comment by WahbiPS** [comment]
Expected gain: sanity + time spent to push manually

**Comment by andrii-bodnar** [comment]
What about using [GitHub Crowdin Action](https://github.com/crowdin/github-action)? 🙂
