### ISSUE TITLE
Github action to extract catalog

### ISSUE THREAD

**Issue by WahbiPS** [PrestaShop/PrestaShop#31195]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

- Extracting is an annoying task, it should be automated to avoid human errors and losing too much time.

### Describe the solution you'd like

- We should make a github action that allows to manually do a catalog extract and make the necessary pull request.

#### Description

- see issue: https://github.com/PrestaShopCorp/TranslationTool/issues/127

#### Complexity
Size S

**Comment by WahbiPS** [comment]
Expected gain: a manual task taking few days + stability & sanity (avoid human errors)

**Comment by 0x346e3730** [comment]
The issue links to a doc that links to TranslationTools, the README of the repo talks about Crowdin's API Key and when working on this task the link was dead, Crowdin API went to V2 and there is a new way to create the API Key in your own profile
