### ISSUE TITLE
ps_imageslider when updating anything from sample, >> shows internal server error

### ISSUE THREAD

**Issue by zaaidaann** [PrestaShop/PrestaShop#31203]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

illl add screen recordin, please have a look over it

https://user-images.githubusercontent.com/25261907/216763428-38a1b724-2aae-432d-aba0-267eddf6f063.MOV

### Expected behavior

it should update, what its supposed to do, whether image or text !

### Steps to reproduce

go to themes, slider and configure
update the sample image and text data, 
when updating 
it just shows internal server error !

### PrestaShop version(s) where the bug happened

1.8.0.1

### PHP version(s) where the bug happened

8.1.13

### If your bug is related to a module, specify its name and its version

ps_imageslider

**Comment by RoseannePeeters** [comment]
Hey @zaaidaann , I have already made a bug report about this issue, they have the same cause, you can view it [here](https://github.com/PrestaShop/PrestaShop/issues/31194). Also it would be helpful if you turn debug mode on, so we can see which code is erroring on your version.

**Comment by zaaidaann** [comment]
> Hey @zaaidaann , I have already made a bug report about this issue, they have the same cause, you can view it [here](https://github.com/PrestaShop/PrestaShop/issues/31194). Also it would be helpful if you turn debug mode on, so we can see which code is erroring on your version.

already fixed it, i found a way to fix this, 

mate, i saw your debug report, mine was same tho !

so, i would suggest you, to navigate to modules and take backup of ps_imageslider.

then follow this link [https://github.com/PrestaShop/ps_imageslider](url) and download this source code not the release one, and copy the files into modules ps_image slider, it will fix your issue. 

Also do reply when you have performed this.

download directly here [https://github.com/PrestaShop/ps_imageslider/archive/refs/heads/dev.zip](url)
