### ISSUE TITLE
Visual issue with input during product edit

### ISSUE THREAD

**Issue by devzom** [PrestaShop/PrestaShop#31207]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Invalid input presentation on product edit view,  6th tab named: "Options".
Input with id="form_step6_tags_1-tokenfield" to write "tags" doesn't take full width of the parent container.

### Expected behavior

If input takes full parent container width should allow to fill the whole size by text

### Steps to reproduce

1. Go to edit page of any product
2. Open 6th tab "Options"
3. Try to write something into "tags" input
4. Look for the input length, doesn't take full width of parent container.

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.0

**Comment by hibatallahAouadni** [comment]
Hello @devzom 

Are you talking about the old Product page (Product V1) or the new Experimental Product page (Product V2)?
### Product V1:
![image](https://user-images.githubusercontent.com/23308427/216985954-3547f553-3180-4dc0-866f-a30e5e7a1d26.png)

### Product V2:
![image](https://user-images.githubusercontent.com/23308427/216985665-c5f6e1c0-984e-4351-9953-2efee0af2c80.png)

Please check and feedback.

Thanks!

**Comment by devzom** [comment]
Looks like I had v1.
Sorry and thanks for Your check
Regards!
