### ISSUE TITLE
JS error when trying to translate a module using the new translation system

### ISSUE THREAD

**Issue by MathiasReker** [PrestaShop/PrestaShop#31205]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

![image](https://user-images.githubusercontent.com/26626066/216771729-857d7373-cc51-48d4-b5f6-cd46babc4a86.png)

Translation of modules using the new translation system does not work, as there is an JS error.

### Steps to reproduce

1. Create a module

Add this method to the modules main class:
`public function isUsingNewTranslationSystem()
{
    return true;
}
`

2. Make a new translation in either Twig or PHP using the new syntax:
E.g.: `{{ 'Welcome to this page!'|trans({}, 'Modules.Mymodule.Admin') }}`

> Edit by @hibatallahAouadni 

**Or use this module:**
[mymodule.zip](https://github.com/PrestaShop/PrestaShop/files/10667904/mymodule.zip)

3. Go to: https://localhost/prestashop_8.0.1/admin-dev/index.php/improve/international/translations/settings?_token=qB2sO1cc7nKMGl_eBo10erMNDFVP4476d0WHwdMba84

4. Select the module to translate.

5. Watch er browser console. An Js error appear:
`TypeError: can't access property "forEach", e is undefined
    t https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:95
    domainsTree https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:95
    e https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:39
    n https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:39
    get https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    evaluate https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    yn https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    get https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:39
    domainsTree https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:39
    get https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    evaluate https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    yn https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    g https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    _render https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    r https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    get https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    run https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    fn https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    ne https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    Xt https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    promise callback*Gt https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    ne https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    update https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    update https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    notify https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    set https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    SIDEBAR_LOADING https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:70
    _t https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:39
    commit https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:45
    commit https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:45
    _withCommit https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:45
    commit https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:45
    commit https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:39
    We https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:70
    promise callback*Bt.then https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:45
    We https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:70
    _t https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:39
    dispatch https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:45
    dispatch https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:39
    mounted https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:39
    Ht https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    tn https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    insert https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    T https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    Ui https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    _update https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    r https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    get https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    run https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    fn https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    ne https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    Xt https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    promise callback*Gt https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    ne https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    update https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    update https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    notify https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    set https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    APP_IS_READY https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:70
    _t https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:39
    commit https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:45
    commit https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:45
    _withCommit https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:45
    commit https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:45
    commit https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:39
    qe https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:70
    promise callback*Bt.then https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:45
    qe https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:70
    _t https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:39
    dispatch https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:45
    dispatch https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:39
    beforeMount https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:145
    Ht https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    tn https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    mount https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    $mount https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    $mount https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    _init https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    Cn https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:14
    <anonymous> https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:145
    <anonymous> https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:145
    <anonymous> https://localhost/prestashop_8.0.1/admin-dev/themes/new-theme/public/translations.bundle.js?8.0.1:145
translations.bundle.js:14:11563
`

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.1.14

**Comment by hibatallahAouadni** [comment]
Hello @MathiasReker 

Thanks for reporting the issue and all details 🙏 
But could you please provide a simple test module contains all the modifications that you mentioned in step 1 & 2.
Waiting for your feedback.

Thanks!

**Comment by MathiasReker** [comment]
Hi @hibatallahAouadni 

Please try attached

[mymodule.zip](https://github.com/PrestaShop/PrestaShop/files/10667904/mymodule.zip)

**Comment by hibatallahAouadni** [comment]
Hello @MathiasReker 

Thanks for the module 🙏 
One last question 😅 did you encounter the issue only when you edit translation while using all shops mode or even with one store selected?
Waiting for your feedback.

Thanks!

**Comment by MathiasReker** [comment]
> Hello @MathiasReker 
> 
> Thanks for the module 🙏 
> One last question 😅 did you encounter the issue only when you edit translation while using all shops mode or even with one store selected?
> Waiting for your feedback.
> 
> Thanks!

I have tested with all shop mode only.

**Comment by AureRita** [comment]
Hi @MathiasReker 

Despite my efforts, I'm  not able to reproduce your issue with the provided information, as you can see : 

[Untitled_ Feb 8, 2023 4_35 PM.webm](https://user-images.githubusercontent.com/100699445/217576769-89b5d5ff-f947-4537-bfc6-ff0eb4d1af10.webm)

I checked the console and didn't have any JS error 

Did I do something wrong ? 

Thank you

**Comment by MathiasReker** [comment]
> Hi @MathiasReker 
> 
> Despite my efforts, I'm  not able to reproduce your issue with the provided information, as you can see : 
> 
> [Untitled_ Feb 8, 2023 4_35 PM.webm](https://user-images.githubusercontent.com/100699445/217576769-89b5d5ff-f947-4537-bfc6-ff0eb4d1af10.webm)
> 
> I checked the console and didn't have any JS error 
> 
> Did I do something wrong ? 
> 
> Thank you

Thank you alot. I will investigate the issue on my end.

**Comment by djoelleuch** [comment]
Hi @MathiasReker , 
Please check and feedback.
thank you !

**Comment by djoelleuch** [comment]
Hello @MathiasReker ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Comment by MathiasReker** [comment]
I found the reason to the problem.

Using domain like `MyModule` will raise an exception. The domain must be `Mymodule`. Only the first letter can be uppercase as the documentation says: https://devdocs.prestashop-project.org/8/modules/creation/module-translation/new-system/

**Comment by memosxo-zentegra** [comment]
Hello,

I have same problem to load translations for warehouse theme.
Prestashop 1.7.8.8
@MathiasReker do you have any idea how to fix it?

**I tried to change names for column "domain" in table ps_translation, only first letter uppercase. Didn't help.**

**Debug:**
Symfony\Component\Debug\Exception\
FatalThrowableError
in [src/Core/Translation/Storage/Provider/ModuleCatalogueLayersProvider.php](..../index.php/_profiler/open?_token=........._repayJDM?file=src/Core/Translation/Storage/Provider/ModuleCatalogueLayersProvider.php&line=308#line308) (line 308)
            foreach (array_keys($items) as $translationKey) {                //392759                //if (is_int($translationKey)) {                //continue;                //}                $legacyKey = md5($translationKey);                if ($catalogueFromLegacyTranslationFiles->has($legacyKey, $currentDomain)) {                    $legacyFilesCatalogue->set(                        $translationKey,                        $catalogueFromLegacyTranslationFiles->get($legacyKey, $currentDomain),

**I have this error in chrome consol:**
Failed to load resource: the server responded with a status of 500 ()
.........pl/:2 Uncaught (in promise) SyntaxError: Unexpected token '<', "
<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at translations.bundle.js?1.7.8.8:75:1041

**Comment by MathiasReker** [comment]
> Hello,
> 
> I have same problem to load translations for warehouse theme.
> Prestashop 1.7.8.8
> @MathiasReker do you have any idea how to fix it?
> 
> **I tried to change names for column "domain" in table ps_translation, only first letter uppercase. Didn't help.**
> 
> **Debug:**
> Symfony\Component\Debug\Exception\
> FatalThrowableError
> in [src/Core/Translation/Storage/Provider/ModuleCatalogueLayersProvider.php](..../index.php/_profiler/open?_token=........._repayJDM?file=src/Core/Translation/Storage/Provider/ModuleCatalogueLayersProvider.php&line=308#line308) (line 308)
>             foreach (array_keys($items) as $translationKey) {                //392759                //if (is_int($translationKey)) {                //continue;                //}                $legacyKey = md5($translationKey);                if ($catalogueFromLegacyTranslationFiles->has($legacyKey, $currentDomain)) {                    $legacyFilesCatalogue->set(                        $translationKey,                        $catalogueFromLegacyTranslationFiles->get($legacyKey, $currentDomain),
> 
> **I have this error in chrome consol:**
> Failed to load resource: the server responded with a status of 500 ()
> .........pl/:2 Uncaught (in promise) SyntaxError: Unexpected token '<', "
> <!DOCTYPE "... is not valid JSON
>     at JSON.parse (<anonymous>)
>     at translations.bundle.js?1.7.8.8:75:1041
> 

You have to contact the author of the warehouse theme about this

Make sure not to use UpperCamelCase

**Comment by momo1240** [comment]
Hello guys
I have the same issue with warehouse childtheme
it takes ages to show up, I had to edit timeout from 30s to 300S
did someone managed to solve the issue ?
thank you
