### ISSUE TITLE
Auto upgrade fails due to missing table

### ISSUE THREAD

**Issue by Prestaworks** [PrestaShop/PrestaShop#31219]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When upgrading from Prestashop 1.7.8.8 to Prestashop 8.0.1 using the cli the autoupgrade fails during database upgrade due to a bad SQL query.

#message: "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'prestashop.ps__tab' doesn't exist"
an extra _ is added to the table name in the Query.

### Expected behavior

An successfull upgrade without errors

### Steps to reproduce

1. Install Prestashop 1.7.8.8
2. Install Autoupgrade module 4.15.0
3. Upgrade to Prestashop 8.0.1 using CLI

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.0

### If your bug is related to a module, specify its name and its version

autoupgrade

**Comment by hibatallahAouadni** [comment]
Hello @Prestaworks 

Was your PHP version 8 before the upgrade?? Cause you should downgrade your PHP version to 7.4 with PS1788, then upgrade your shop to PS801, after that you can upgrade your PHP version to 8.
Please check and feedback.

Thanks!

**Comment by Prestaworks** [comment]
> Hello @Prestaworks
> 
> Was your PHP version 8 before the upgrade?? Cause you should downgrade your PHP version to 7.4 with PS1788, then upgrade your shop to PS801, after that you can upgrade your PHP version to 8. Please check and feedback.
> 
> Thanks!

we used php 8 from the cli to upgrade.

**Comment by hibatallahAouadni** [comment]
Hello @Prestaworks 

> we used php 8 from the cli to upgrade.

Well, you should use PHP 7.4 to upgrade. Please try again and feedback.

Thanks!

**Comment by Prestaworks** [comment]
> 

Sorry, I been getting stuck on this issue all morning
https://github.com/PrestaShop/PrestaShop/issues/30761
tested with php 7.2, .7.3 and 7.4

however, PHP version does not affect SQL queries so what php version is used is not relevant.

**Comment by AureRita** [comment]
Hi @Prestaworks 

Currently, I have to put your issue on dupplicate because you already find the original issue, I do a friendly reminder to the dev team, as you can see I tried to reproduce your issue : 

[Untitled_ Feb 8, 2023 3_23 PM.webm](https://user-images.githubusercontent.com/100699445/217558661-a51fe69b-88df-4dc4-a3f5-a2edb6de6e50.webm)

But unfortunately, I can't 

If you can give more video on the original topic, this will be fine 

Thank you for your report

**Comment by AureRita** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/30761

**Comment by Prestaworks** [comment]
> Duplicate of #30761

thats a completly different issue, please reopen my ticket.

**Comment by AureRita** [comment]
This one can be different, but currently I can't reproduce it, ping @PrestaShop/qa-team , can someone please reproduce this issue ? 

Thanks

**Comment by hibatallahAouadni** [comment]
Hello @Prestaworks 

I didn't manage to reproduce your issue 😞 could you please provide more infos, screenshots, screen record 🙏 
Did you disable all non-native modules before the upgrade??
Please check and feedback.

Thanks!

**Comment by kpodemski** [comment]
I can tell by looking at the code that it is indeed a bug to fix. And we can see that here:
https://github.com/PrestaShop/autoupgrade/pull/559/files#diff-ac613973852e3a52479c71dbd2f142185fb75eb7402c5c2cf1d9c148eb49e2ddR31

To me it is a valid bug report.

**Comment by hibatallahAouadni** [comment]
Hello @Prestaworks 

Thanks @kpodemski for your quick reply 🙏 
Well then it's validated by @kpodemski 🙌 Changing the labels 😉 
BTW, the PR that will fix this issue should be tested by a Dev as the issue validated by a dev.

Thanks!

**Comment by RosaBenouamer** [comment]
@hibatallahAouadni : what kind of specification do you need ? Is if for dev of PM. It's seems to be technical

**Comment by kpodemski** [comment]
@RosaBenouamer it has been fixed already :)

**Comment by kpodemski** [comment]
I'm reopening, it **will** be fixed when 4.16 of autoupgrade is live 

PR that fixes this bug: https://github.com/PrestaShop/autoupgrade/pull/559

**Comment by Hlavtox** [comment]
Module released, closing.
