### ISSUE TITLE
Module user-displayable exceptions not working anymore

### ISSUE THREAD

**Issue by bibips** [PrestaShop/PrestaShop#31221]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The pull request https://github.com/PrestaShop/PrestaShop/pull/14239 adds the possibility for modules to display error on controllers thanks to the exception ModuleErrorException.

But because of this commit https://github.com/PrestaShop/PrestaShop/commit/a5619cc54a121e553b3aeb46ef2076c2a6b58f20 all modules exceptions are catch during the call of callHookOn method.

With this try/catch, the exception is no longer raised to the FrameworkBundleAdminController class and the error is not displayed to user.

### Expected behavior

Throw an exception that implements `\PrestaShop\PrestaShop\Core\Module\Exception\ModuleErrorInterface` inside a module should display an error message for users.

For example :
```
public function hookActionAfterUpdateCustomerFormHandler(array $params)
 {
     throw new CustomException('This is a nice display message');
 }
```

![image](https://user-images.githubusercontent.com/6272184/216982428-ba07e818-4870-4b28-8025-4733460ae17b.png)

### Steps to reproduce

- Install [attached module](https://github.com/PrestaShop/PrestaShop/files/10663154/module_for_pr_hook_error.zip)
- Go to Back-Office customer page
- Update a customer
- No message is displayed to the user

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.1.13

**Comment by florine2623** [comment]
Hello @bibips ,

Indeed in PS 8.0.1, I do not have a message error, but an exception :
<img width="1234" alt="Screenshot 2023-02-07 at 16 54 46" src="https://user-images.githubusercontent.com/16019289/217295283-4920fe63-0cb3-46dd-bca8-92a7cb85c7f8.png">

**Comment by florine2623** [comment]
ping @PrestaShop/prestashop-core-developers ,

I have reproduced the error, I think to validate it, it needs a developer point of view.

**Comment by matthieu-rolland** [comment]
This issue seems legit to me :+1:
