### ISSUE TITLE
Github action to update the FOS JSON routing file

### ISSUE THREAD

**Issue by WahbiPS** [PrestaShop/PrestaShop#31232]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

#### Description
Create a github action to update the FOS JSON routing file with this command: 

php bin/console fos:js-routing:dump \
    --format=json \
    --target=admin-dev/themes/new-theme/js/fos_js_routes.json

--> opens a PR with the modifications.

#### Complexity
Size: XS

**Comment by jolelievre** [comment]
Closed because already implemented https://github.com/PrestaShop/PrestaShop/blob/4d2749e94e4f00ed0bf2dcbaa472dc77af5b0ebf/.github/workflows/cron_js_routing.yml#L101
