### ISSUE TITLE
Github action to update new native modules in composer

### ISSUE THREAD

**Issue by WahbiPS** [PrestaShop/PrestaShop#31234]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

#### Description
Github action so that new native modules are  added into composer.json and their latest versions have been updated in composer.lock

composer outdated -D "prestashop/*"

--> opens a PR with the modifications.

And launch auto test if green merged the PR

#### Complexity
Size: XS

**Comment by Progi1984** [comment]
Already done : https://github.com/PrestaShop/PrestaShop/blob/develop/.github/workflows/cron_php_update_modules.yml

Each night 🌌🌃🌌

**Comment by MatShir** [comment]
@jolelievre or @matthieu-rolland can we close the issue then ?

**Comment by jolelievre** [comment]
Yep, the CI used to be failing so we forgot about it, but it's all good now
