### ISSUE TITLE
Feature flags are blocked when multistore is enabled

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#31245]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On the 8.1.x branch, when I enable multi store feature I can't edit the feature flags anymore.

[New & Experimental Features • Prestashop 81.webm](https://user-images.githubusercontent.com/13801017/217209397-af8ac362-29eb-4566-9a6f-8cbc68ee4f3c.webm)
https://watch.screencastify.com/v/MFa5XF060OZMqrkomCeG

### Expected behavior

The feature flags should always be editable, there's some protection that was useful before but needs to be removed now.

### Steps to reproduce

1. Go to Shop Parameters > General
2. Enable multi store
3. Go to Advanced Parameters > New & Experimental Features
4. The feature flags are disabled (I mean you can't click on it or change its value, I'm not referring to its value which is not relevant here)

### PrestaShop version(s) where the bug happened

8.1.0

**Comment by florine2623** [comment]
Hello @jolelievre ,

I reproduce the issue with PrestaShop version 8.1.x, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/31247
