### ISSUE TITLE
Changed/missing files have been detected after upgrade from 1.7.8.7 to 1.7.8.8 were found in Advanced Parameters

### ISSUE THREAD

**Issue by presta888** [PrestaShop/PrestaShop#31242]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After upgrading from 1.7.8.7 to 1.7.8.8 we have found in Advanced Parameters Information that

Changed/missing files have been detected.
Updated files (11)
config/defines.inc.php
vendor/composer/installers/src/Composer/Installers/TaoInstaller.php
vendor/composer/installers/src/Composer/Installers/SyDESInstaller.php
vendor/composer/installers/src/Composer/Installers/MauticInstaller.php
vendor/composer/installers/src/Composer/Installers/Installer.php
vendor/composer/installers/src/Composer/Installers/MoodleInstaller.php
vendor/composer/installers/src/Composer/Installers/OxidInstaller.php
vendor/composer/installers/src/Composer/Installers/BaseInstaller.php
vendor/composer/installers/src/Composer/Installers/CakePHPInstaller.php
vendor/composer/installers/src/Composer/Installers/CockpitInstaller.php
vendor/composer/installers/src/Composer/Installers/OctoberInstaller.php

Our Parameters
Server information: Linux #1 SMP Thu Dec 15 20:31:06 MSK 2022 x86_64
PHP version: 7.3.33
Memory limit: 2048M
Max execution time: 300
Upload Max File size: 128M
MySQL version: 10.3.37-MariaDB
MySQL server: localhost
Tables prefix: psvl_
MySQL engine: InnoDB
MySQL driver: DbPDO

List of overrides
modules/ps_emailsubscription/ps_emailsubscription.php
classes/Context.php
classes/Hook.php
classes/controller/ProductListingFrontController.php
classes/controller/FrontController.php
classes/Media.php

Check your configuration
Required parameters: OK
Optional parameters: OK

### Expected behavior

Is it correct that Changed/missing files have been detected?

### Steps to reproduce

1 Upgrade Prestashop with 1-Click Upgrade v4.15.0 - by PrestaShop
2 Clean the cache
3 update all module
4 debug mode
5 we have found in Advanced Parameters Information that Changed/missing files have been detected.

### PrestaShop version(s) where the bug happened

1.7.8 stable - (1.7.8.8)

### PHP version(s) where the bug happened

7.3.33

**Comment by AureRita** [comment]
Hi @presta888 ,

I reproduce the issue with PrestaShop version 1.7.8.7 to 1.7.8.8, as you can see : 

[Untitled_ Feb 8, 2023 5_21 PM.webm](https://user-images.githubusercontent.com/100699445/217589447-07627731-090b-4121-95a3-dca181e12b20.webm)

@PrestaShop/product-team is it an exepected behavior or not ? 

if this one is not an expected behavior, I'll add this to the backlog so it can be fixed.


Thanks

**Comment by fabienvallon** [comment]
Does it only happens on Debug mode ?

**Comment by presta888** [comment]
> Does it only happens on Debug mode ?

It happen also without debug mode.
Updated files (10)
vendor/composer/installers/src/Composer/Installers/TaoInstaller.php
vendor/composer/installers/src/Composer/Installers/SyDESInstaller.php
vendor/composer/installers/src/Composer/Installers/MauticInstaller.php
vendor/composer/installers/src/Composer/Installers/Installer.php
vendor/composer/installers/src/Composer/Installers/MoodleInstaller.php
vendor/composer/installers/src/Composer/Installers/OxidInstaller.php
vendor/composer/installers/src/Composer/Installers/BaseInstaller.php
vendor/composer/installers/src/Composer/Installers/CakePHPInstaller.php
vendor/composer/installers/src/Composer/Installers/CockpitInstaller.php
vendor/composer/installers/src/Composer/Installers/OctoberInstaller.php

**Comment by RosaBenouamer** [comment]
@jolelievre :  is it an exepected behavior or not ?

**Comment by RosaBenouamer** [comment]
@presta888 : Does it linekd to the auto upgrade or the update of the module. Did you check the missing file before upgrading the module ?

**Comment by presta888** [comment]
@RosaBenouamer We update Prestashop with  auto upgrade  module and was the last released available. 
I confirm we have checked the missing file before upgrading the module.

**Comment by presta888** [comment]
> We update Prestashop with auto upgrade module and was the last released available.
> I confirm we have checked the missing file before upgrading the module.

**Comment by Misty-94** [comment]
Still happens with upgrade to 1.7.8.10 but with missing files too.

Missing:
vendor/composer/installers/phpstan.neon.dist
vendor/composer/installers/src/Composer/Installers/MiaoxingInstaller.php
vendor/composer/installers/src/Composer/Installers/WinterInstaller.php
vendor/composer/installers/src/Composer/Installers/PantheonInstaller.php
vendor/composer/installers/src/Composer/Installers/TastyIgniterInstaller.php
vendor/composer/installers/src/Composer/Installers/StarbugInstaller.php
vendor/composer/installers/src/Composer/Installers/ProcessWireInstaller.php

Modified :
vendor/composer/installers/src/Composer/Installers/SyDESInstaller.php
vendor/composer/installers/src/Composer/Installers/TaoInstaller.php
vendor/composer/installers/src/Composer/Installers/CakePHPInstaller.php
vendor/composer/installers/src/Composer/Installers/Installer.php
vendor/composer/installers/src/Composer/Installers/MoodleInstaller.php
vendor/composer/installers/src/Composer/Installers/OctoberInstaller.php
vendor/composer/installers/src/Composer/Installers/MauticInstaller.php
vendor/composer/installers/src/Composer/Installers/OxidInstaller.php
vendor/composer/installers/src/Composer/Installers/CockpitInstaller.php
vendor/composer/installers/src/Composer/Installers/BaseInstaller.php

**Comment by RosaBenouamer** [comment]
@jolelievre : what do you think about that ?

**Comment by RosaBenouamer** [comment]
@PrestaShop/committers

**Comment by kpodemski** [comment]
It's nothing serious.

**Comment by Hlavtox** [comment]
Fixed in autoupgrade 5.0.0 ;)

**Comment by andreicos1982** [comment]
After upgrading from prestashop 1.7.8.10 to 1.7.8.11 i'm getting missing/modified files in info section. Most of them from vendor/composer.......

**Comment by Hlavtox** [comment]
@andreicos1982 Use latest version of autoupgrade module, should be good.

**Comment by andreicos1982** [comment]
> @andreicos1982 Use latest version of autoupgrade module, should be good.

I use v5.0.0. Is the last version

**Comment by Hlavtox** [comment]
@andreicos1982 Hmm, can you share the list of files that are being reported as missing/modified please?

**Comment by andreicos1982** [comment]
> @andreicos1982 Hmm, can you share the list of files that are being reported as missing/modified please?

rolled back :((( But i remeber was LICENSE and som files from vendor/composer
I will try to upgrade once again tonight and i will post the missing/modified files.
BTW i checked the files after upgrade and all the files was there
