### ISSUE TITLE
Webservice `[GET] /api/customers` returns `null` associated group IDs

### ISSUE THREAD

**Issue by nat-e** [PrestaShop/PrestaShop#31244]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have a test shop running prestashop `v8.0.1`, when I make the following webservice request
`/api/customers/1?display=full` with the `Output-Format: JSON` header I get the following response

```
{
    "customers": [
        {
            "id": 1,
            "id_default_group": 3,
            "id_lang": 1,
            "newsletter_date_add": "0000-00-00 00:00:00",
            "ip_registration_newsletter": "",
            "last_passwd_gen": "2023-02-04 20:42:09",
            "secure_key": "949f5e4a0acb2e439da5973436b6fe4a",
            "deleted": 0,
            "passwd": "$2y$10$bYf1mLZhbYM/nDrxYHIIgOL5SpK5WcmOtLJJRS07mUi7kmz2Ge.Vq",
            "lastname": "Anonymous",
            "firstname": "Anonymous",
            "email": "anonymous@psgdpr.com",
            "id_gender": 1,
            "birthday": "0000-00-00",
            "newsletter": 0,
            "optin": 0,
            "website": "",
            "company": "",
            "siret": "",
            "ape": "",
            "outstanding_allow_amount": "0.000000",
            "show_public_prices": 0,
            "id_risk": 0,
            "max_payment_days": 0,
            "active": 0,
            "note": "",
            "is_guest": 0,
            "id_shop": 1,
            "id_shop_group": 1,
            "date_add": "2023-02-05 02:42:09",
            "date_upd": "2023-02-05 02:42:09",
            "reset_password_token": "",
            "reset_password_validity": "0000-00-00 00:00:00",
            "associations": {
                "groups": [
                    [
                        null
                    ]
                ]
            }
        }
    ]
}
```

In which `groups` is an array containing `null` instead of the groups' ids.
I am trying to make a `PATCH` request to add/remove customers to groups, and this is very problematic because I have no way of doing this if I cannot retrieve the list of groups that a user is previously associated to.

Thank you.

### Expected behavior

Response should contain an array of ids

### Steps to reproduce

1. Enable webservice access
2. Setup a Webservice API key
3. Query `[GET] /api/customers/1?display=full` with `Output-Format:JSON` header

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.0

**Comment by florine2623** [comment]
Hello @nbarraille ,

I can't reproduce your issue on PS 8.0.1.

<img width="1008" alt="Screenshot 2023-02-07 at 15 15 57" src="https://user-images.githubusercontent.com/16019289/217269449-c4de5a24-5da0-439a-9d1b-f72d92464af7.png">

I do not have "null" for the customer groups.

Am I missing something ?
Thanks!

**Comment by nat-e** [comment]
Hello @florine2623 ,
Have you tried with the `Output-Format: JSON` header?

**Comment by hibatallahAouadni** [comment]
Hello @nbarraille 

Thanks for your feedback and your patience 🙏 
I didn't manage to reproduce the issue even with the `Output-Format: JSON` header, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/219031455-f4f8a18c-e4d2-47e1-a323-26931504d1dd.mov

Please check and feedback.

Thanks!

**Comment by djoelleuch** [comment]
Hello  @nbarraille ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. 
Please note that you can always create a new one if further information pops up.

Thank you

**Comment by djoelleuch** [comment]
Hello @nbarraille ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
