### ISSUE TITLE
Can't upgrade Featured product from 2.1.2 to 2.1.3

### ISSUE THREAD

**Issue by nl2ttl** [PrestaShop/PrestaShop#31254]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I login to the modules page on the notification page I get a Update message.

Featured products 2.1.2 -> 2.1.3 When I hut update it says: Upgrade module ps_featuredproducts succes.
Only when I refresh the page it still says upgrade 2.1.2 to 2.1.3.

### Steps to reproduce

1. Try website in maintanance and normal mode.
2. Uninstall and reinstall module

### PrestaShop version(s) where the bug happened

8

### PHP version(s) where the bug happened

8

### If your bug is related to a module, specify its name and its version

ps_featuredproducts

**Comment by Hlavtox** [comment]
Hi @nl2ttl, there was a version mismatch in the build. Tommorow a 2.1.4 version will pop up and the upgrade will work fine.

Or you can manually update from this zip - https://github.com/PrestaShop/ps_featuredproducts/releases/download/v2.1.4/ps_featuredproducts.zip
