### ISSUE TITLE
Email alert wrong notification for "Payment error"

### ISSUE THREAD

**Issue by AurelienSuslec** [PrestaShop/PrestaShop#31256]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I use the native Mail alerts for Prestashop (https://addons.prestashop.com/fr/emails-notifications/24547-mail-alerts.html).
I have an issue when a client buys something in my shop but has a "payment error". The administrator gets an email saying "New order is confirmed" whereas the client cound not finalise its order...

### Expected behavior

There are 2 solutions I expect : 
- No notification to admin for Payment error status (there is no template file in the module)
- The ability to add a new template dealing with this error.
The simpler, the better...

### Steps to reproduce

1. Make an order as client
2. Add a wrong card number to create a Payment error
3. Check the Administrator email notification

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.29

### If your bug is related to a module, specify its name and its version

ps_emailalerts

**Comment by florine2623** [comment]
Hello @AurelienSuslec ,

Can you specify what payment module are you using ?

With the native payment modules of PrestaShop (brank transfer and check payment), I can't reproduce this issue.

**Comment by AurelienSuslec** [comment]
I use Axepta - BNP Paribas module for credit card payment.

**Comment by AureRita** [comment]
Hi @AurelienSuslec 

Unfortunatelly this module isn't created by prestashop itself so we can't do more improve on it, You can contact the dev module on Addons 

Thank you
