### ISSUE TITLE
500 Error trying to update a product fetched with display = full

### ISSUE THREAD

**Issue by TomLorenzi** [PrestaShop/PrestaShop#31252]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I tried fetching a product with `display = full` removeing the unwritable keys and sending it back (with webservice lib).

I got this error 
```
This call to PrestaShop Web Services failed and returned an HTTP status of 500. That means: Internal Server Error - (Code 5): [PHP Notice #8] Trying to access array offset on value of type null (/var/www/itdatabase/prestashop/classes/Product.php, line 7149).
```

### Expected behavior

Do not throw an error

### Steps to reproduce

1. Try to fetch a product with 'display' => 'full'
2. Remove manufacturer_name and quantity bc it's not writable 
3. Push that product, you'll get this 500 error as a NOTICE

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.4

**Comment by TomLorenzi** [comment]
https://github.com/PrestaShop/PrestaShop/pull/31251

**Comment by florine2623** [comment]
Hello @TomLorenzi ,

I'm trying to reproduce your issue.

On step 2, you said to `remove manufacturer_name and quantity bc it's not writable`
How do you remove them ? Manually via BO ou directly via WebService ?
Can you share the exact steps to reproduce please ?

Thanks!

**Comment by TomLorenzi** [comment]
Hi @florine2623 
I'm using the webservice lib, so before i'm calling my edit endpoint I wrote that 
```
unset($xmlProduct->manufacturer_name);
unset($xmlProduct->quantity);
```

It's just to avoid getting the error for trying to update this fields that we're not allowed to.

**Comment by hibatallahAouadni** [comment]
Hello @TomLorenzi 

Thanks for your patience and your feedback 🙏 
Could you please provide the body request that you used in every step.
Waiting for your feedback.

Thanks!

**Comment by TomLorenzi** [comment]
I did wrote all the steps I've done to reproduce the error using the PHP webservice library. I'm not manipulating the request body as it's Prestashop's library that does it.

1. Get an existing product using the webservice
2. Remove the unwritable fields
3. Send again that product

Looking at the PR it could be seen without even running the code that it will throw a PHP notice.

Sorry but I can't really spend more time than I did writting that issue, making a PR and discussing around it.

**Comment by hibatallahAouadni** [comment]
Hello @TomLorenzi 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a module problem.

We will close this issue.

Thanks!

**Comment by TomLorenzi** [comment]
@hibatallahAouadni  Would it be possible for you to show me the request you sent to try tro reproduce my bug ?

**Comment by TomLorenzi** [comment]
Please, can you provide me this ? Cause there's an obvious error in code that produce a PHP Notice.
