### ISSUE TITLE
Fatal Error while checkout with Solvak language

### ISSUE THREAD

**Issue by Kvietok** [PrestaShop/PrestaShop#31265]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

`Fatal error: Uncaught ValueError: The arguments array must contain 3 items, 2 given in /var/www/clients/client(...)/web/src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php:69 Stack trace: #0 /var/www/clients/client(...)/web/src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php(69): vsprintf() #1 /var/www/clients/client(...)/web/classes/form/CustomerForm.php(234): PrestaShopBundle\Translation\TranslatorComponent->trans() #2 /var/www/clients/client(...)/web/classes/form/CustomerForm.php(208): CustomerFormCore->getEmailMaxLengthViolationMessage() #3 /var/www/clients/client(...)/web/classes/form/CustomerForm.php(200): CustomerFormCore->validateFieldsLengths() #4 /var/www/clients/client(...)/web/classes/form/CustomerForm.php(258): CustomerFormCore->validate() #5 /var/www/clients/client(...)/web/classes/checkout/CheckoutPersonalInformationStep.php(67): CustomerFormCore->submit() #6 /var/www/clients/client(...)/web/classes/checkout/CheckoutProcess.php(76): CheckoutPersonalInformationStepCore->handleRequest() #7 /var/www/clients/client(...)/web/controllers/front/OrderController.php(252): CheckoutProcessCore->handleRequest() #8 /var/www/clients/client(...)/web/tools/profiling/Controller.php(60): OrderControllerCore->initContent() #9 /var/www/clients/client(...)/web/classes/Dispatcher.php(510): Controller->run() #10 /var/www/clients/client(...)/web/index.php(28): DispatcherCore->dispatch() #11 {main} thrown in /var/www/clients/client(...)/web/src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php on line 69
`
### Expected behavior

It happens instead of checkout

### Steps to reproduce

1. fresh install of PS 8.0.1 in Slovak language on virtual server with PHP 8.1
2. view my shop
3. add product
4. checkout
5. name, surname, e-mail, checked terms and privacy
6. NEXT => fatal error

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.1, 8.0

### If your bug is related to a module, specify its name and its version

no, installation without anything added

**Comment by djoelleuch** [comment]
Hello @Kvietok 

Thanx for reporting the issue.

Following your steps I did'nt manage to reprodue your issue !

[Untitled_ Feb 8, 2023 1_50 PM.webm](https://user-images.githubusercontent.com/115152460/217548955-a7546404-13e0-4be9-8dc1-41100f48c8ce.webm)

I think it's related to some cache , could you please disable the cache in your shop and check ?

Waiting for your feedback !

Thank you !

**Comment by Kvietok** [comment]
Hello Hejer,

please feel free to visit backoffice and try.

kvetyaranzmany.sk/Benjo22
***@***.***
Prestashop33+

Now it is on PHP 8.0, when PHP is set on 7.4, everything works fine.

Thanks,

Juraj

st 8. 2. 2023 o 14:53 Hejer ELLEUCH ***@***.***> napísal(a):

**Comment by Hlavtox** [comment]
@djoelleuch Same error here.

1. Install 8.0.1
2. Import Slovak language, select it in FO.
3. Go to checkout, continue to step 2, fatal error.

`Fatal error: Uncaught ValueError: The arguments array must contain 3 items, 2 given in C:\xampp\htdocs\801\src\PrestaShopBundle\Translation\PrestaShopTranslatorTrait.php:69 Stack trace: #0 C:\xampp\htdocs\801\src\PrestaShopBundle\Translation\PrestaShopTranslatorTrait.php(69): vsprintf('%1$s (%2$s) pol...', Array) #1 C:\xampp\htdocs\801\classes\form\CustomerForm.php(234): PrestaShopBundle\Translation\TranslatorComponent->trans('The %1$s field ...', Array, 'Shop.Notificati...') #2 C:\xampp\htdocs\801\classes\form\CustomerForm.php(208): CustomerFormCore->getEmailMaxLengthViolationMessage() #3 C:\xampp\htdocs\801\classes\form\CustomerForm.php(200): CustomerFormCore->validateFieldsLengths() #4 C:\xampp\htdocs\801\classes\form\CustomerForm.php(258): CustomerFormCore->validate() #5 C:\xampp\htdocs\801\classes\checkout\CheckoutPersonalInformationStep.php(67): CustomerFormCore->submit() #6 C:\xampp\htdocs\801\classes\checkout\CheckoutProcess.php(76): CheckoutPersonalInformationStepCore->handleRequest(Array) #7 C:\xampp\htdocs\801\controllers\front\OrderController.php(252): CheckoutProcessCore->handleRequest(Array) #8 C:\xampp\htdocs\801\classes\controller\Controller.php(319): OrderControllerCore->initContent() #9 C:\xampp\htdocs\801\classes\Dispatcher.php(510): ControllerCore->run() #10 C:\xampp\htdocs\801\index.php(28): DispatcherCore->dispatch() #11 {main} thrown in C:\xampp\htdocs\801\src\PrestaShopBundle\Translation\PrestaShopTranslatorTrait.php on line 69`

Ping @PrestaShop/committers this is a critical issue.

### Cause - wrong translation argument count
Original string:
```
return $this->translator->trans(
            'The %1$s field is too long (%2$d chars max).',
            ['email', 255],
            'Shop.Notifications.Error'
        );
```

Translation:
`"%1$s (%2$s) pole je príliš dlhé (maximálne %3$d znakov)"`

**Comment by Hlavtox** [comment]
Btw @djoelleuch, maybe you did not reproduce the issue because your video is in different language? :D 🤦‍♂️

**Comment by djoelleuch** [comment]
Hello @Kvietok  ,

I was able to reproduce your issue on 8.0.1 with 
PHP 8.1 NOK 

[Untitled_ Feb 10, 2023 2_04 PM.webm](https://user-images.githubusercontent.com/115152460/218112191-1d347a51-8ba6-4dbe-9321-1c32a533bb2f.webm)


PHP 7.4 OK 

[Untitled_ Feb 10, 2023 2_00 PM.webm](https://user-images.githubusercontent.com/115152460/218112215-ebcda9ae-ae11-4735-b632-d35f7b0812f7.webm)

Thank You!

**Comment by Zoefinders** [comment]
Did you notice any issue for same problem with other language?

**Comment by Hlavtox** [comment]
Already fixed in Crowdin, will be fixed by 8.0.2 build and translations update.

EDIT: Will be fixed by a fresh install OR a translation update.

**Comment by MatShir** [comment]
ok great ! Keep the issue to be sure it is fixed.
How did you fix the issue? And how can we avoid the same issue?

**Comment by l-delin** [comment]
Hello @MatShir, three strings have been updated and uploaded:

![image](https://user-images.githubusercontent.com/113511191/221602191-ee2d1261-9055-4c8b-b4ca-575103e6602c.png)

I don't have the previous version of the two other strings but I can compare the one in the issue and the one that's been approved and fixed the problem:

**BEFORE:** `%1$s (%2$s) pole je príliš dlhé (maximálne %3$d znakov)`
**AFTER:** `Pole %1$s je príliš dlhé (maximálne %2$d znakov)`


I believe it's because the variable was at the beginning of the sentence. Could you confirm, @Hlavtox ?

**Comment by Hlavtox** [comment]
@l-delin The problem was that the variable count was different, it must be the same as in the original string.

**Comment by rafaelt88** [comment]
@djoelleuch @MatShir @Hlavtox 
I install prestashop and when I try to open any category was the same throuble.

<img width="1367" height="634" alt="Image" src="https://github.com/user-attachments/assets/14746981-288c-4bc4-a54f-aab838e14c6d" />

I've added this code to identify the cause of the problem on line `src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php:45`



```
        try {
            $translated = vsprintf($translated, $parameters);
        } catch (\ValueError $e) {
            $log_message = "Translation error: message={$translated}, parameters=" . count($parameters);
            PrestaShopLogger::addLog($log_message, PrestaShopLogger::LOG_SEVERITY_LEVEL_WARNING, $e->getCode());
        }
```
It is resolved and makes the code more robust, It's not correct that the system should fail due to a translation error.

<img width="1366" height="768" alt="Image" src="https://github.com/user-attachments/assets/ac8a9790-be6d-42bf-b9c8-a900050a5939" />

Additionally, all translation errors can be identified with the default theme and installation.

*The problem is that `vsprintf` must have the same number of variables in the string as the parameters passed to it; if this does not match, it fails.*

Reagards.
