### ISSUE TITLE
One-click upgrade module issue

### ISSUE THREAD

**Issue by tibethills** [PrestaShop/PrestaShop#31273]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi, when we want to update the prestashop version to 1.7.8.8 (currently the latest version available) we get an error message in the one-click update module saying that it is not possible to create a php session. I have seen that there are multiple stores having the same problem and so far there is not a definite solution for this, I have decided to create a new error issue to see if we can finally reach a definite solution. Attached is a screenshot of the error in the latest version of the module (4.15.0). I must say that my store uses php 7.4 at the moment which is not a problem to upgrade to 1.7.8.8 of prestashop because in my test store, with the previous version of the module I have been able to upgrade to the latest version of prestashop. The problem is in the latest version of the one-click update module.
![image](https://user-images.githubusercontent.com/42473558/217481743-7d630068-f9d6-42fa-82cd-b78671fe02c6.png)

### Expected behavior

We need to fix the problem in the module to be able to upgrade to the latest version of prestashop.

### Steps to reproduce

1- Upgrade the module to the latest version available (4.15.0)
2- Enter into One click upgrade module.
3- View the error that appears when listing the prerequisites.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

autoupgrade v4.15.0

**Comment by Hlavtox** [comment]
Hi @tibethills, fixed by https://github.com/PrestaShop/autoupgrade/pull/561, will be in the next patch version of autoupgrade.
