### ISSUE TITLE
FO - Search product : The search result is changed after the upgrade of the module ps_facetedsearch

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#31278]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The search result is changed after the upgrade of the module ps_facetedsearch

When we search for the demo product for example 'THE ADVENTURE BEGINS FRAMED POSTER', the search result contains 2 products but the searched product is changed to become the second one in the list.

![Capture d’écran de 2023-02-07 16-05-46](https://user-images.githubusercontent.com/24647495/217555352-b01ac6c2-fdec-4d2d-a32e-072cd250dba5.png)

### Expected behavior

The search result contains 2 products but the searched product should be the first in the list.

![Capture d’écran de 2023-02-07 16-07-45](https://user-images.githubusercontent.com/24647495/217558406-606781e6-56b7-4afa-b10c-ca3ba0d5bd96.png)

### Steps to reproduce

1 - Go to FO
2 - Search for the product  'THE ADVENTURE BEGINS FRAMED POSTER' 
3 - See the search result

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_facetedsearch

**Comment by Hlavtox** [comment]
Hi @nesrineabdmouleh, did you enable faceted search for the search page in the filter template or not?
If not, not sure if it's possible, because faceted search should be not launched at all.

EDIT: Indeed the order is changed, but it should not change if a filtering module responds NULL on the search provider hook. I will investigate.

**Comment by nesrineabdmouleh** [comment]
> Hi @nesrineabdmouleh, did you enable faceted search for the search page in the filter template or not? If not, not sure if it's possible, because faceted search should be not launched at all.
> 
> EDIT: Indeed the order is changed, but it should not change if a filtering module responds NULL on the search provider hook. I will investigate.

Thank you @Hlavtox for your response!
No I didn't enable the module for the search but the PR of upgrade broke UI tests.

Thank your for the investigation!

**Comment by Hlavtox** [comment]
You are right, found two issues.
- Module responds and provides itself as a seach provider, even if there is no template configured. This is not an issue itself, but it's not needed.
- Position property is overriden in faceted search - this is an issue and must be solved.

**Comment by djoelleuch** [comment]
Hello @nesrineabdmouleh ,
Following your steps I reproduce the issue with develop NOK : 
![image](https://user-images.githubusercontent.com/115152460/217570499-c413b581-3f75-4cea-be2b-8d200e3efa86.png)

With PS800 OK you can see the attached screen shot : 
![image](https://user-images.githubusercontent.com/115152460/217572784-c4278107-7506-43f9-9c9a-f092ca4ee62a.png)

Nice Catch it's a regression !

Thank you

**Comment by Hlavtox** [comment]
@nesrineabdmouleh @djoelleuch Mitigated by https://github.com/PrestaShop/ps_facetedsearch/pull/788

**Comment by Hlavtox** [comment]
@nesrineabdmouleh Issue will fully disappear after updating the dependency to https://github.com/PrestaShop/ps_facetedsearch/releases/tag/v3.11.1

Sorry for inconvinience everyone.
