### ISSUE TITLE
Error on install, version 8.0.1

### ISSUE THREAD

**Issue by gabrieldodan** [PrestaShop/PrestaShop#31271]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Trying to install prestashop 8.0.1, manual installation. I get the below error

![prestashop-install-error](https://user-images.githubusercontent.com/1359192/217475629-f01c43b9-3210-4f80-bb29-a2e6006dfd83.png)

This is a screenshot of the System requirements script output 

![prestasho-requirements](https://user-images.githubusercontent.com/1359192/217475923-bf656e35-86d9-4f2d-9fb3-0efda284d1b0.png)

Mysql version ``mysql  Ver 8.0.23 for Linux on x86_64 (MySQL Community Server - GPL)``

Any idea/help/suggestion? 

Thanks!

### Expected behavior

Installation successful 

### Steps to reproduce

Manuall installation as described here https://www.prestashop.com/en/blog/how-to-install-prestashop

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

7.4.33

**Comment by djoelleuch** [comment]
Hi @gabrieldodan 
Unfortunately, I couldn't reproduce your issue with PS 8.0.1 and PHP 7.4
Here's my screenshot :

![image](https://user-images.githubusercontent.com/115152460/217553825-0e2ecada-f950-46e1-aa51-2ba96329ea53.png)
 
Please check and feedback.
Thanks!

**Comment by DevLoris** [comment]
Also got it on fresh install with this error : 

`[09-Feb-2023 11:32:06 Europe/Paris] PHP Notice:  Trying to get property 'theme_name' of non-object in /prestashop/var/cache/prod/ContainerA94VfkM/appAppKernelProdContainer.php on line 2702`


Prestashop Version : 8.0.1

PHP Version : 7.4.21

MySQL Version : 5.7.34

**Comment by florine2623** [comment]
Hello @gabrieldodan @DevLoris ,

I could reproduce your issue either. Could you make sure all the requirements are met : https://devdocs.prestashop-project.org/8/basics/installation/ ?

Thanks, waiting for your feedback.

**Comment by gabrieldodan** [comment]
Hi @florine2623 yes , I ran the phppsinfo.php script. All requirements are met, you can see in issue attachments

**Comment by hibatallahAouadni** [comment]
Hello @gabrieldodan 

Despite our efforts, we were not able to reproduce your issue with the provided information.It seems your issue is related to your connection problems or your server configuration.
We will close this issue.

Thanks!

**Comment by gabrieldodan** [comment]
@hibatallahAouadni but there are two other people here who have similar issue...

Also, can you suggest please where I could change/adjust the code myself in order to display/provide more details about that install error? The error it display now is not usefulnat all, it gives no clue

Thanks!

**Comment by gabrieldodan** [comment]
I have managed to install on a different hosting. So the issue was related to that specific hosting.
