### ISSUE TITLE
Typo in install-dev/data/xml/hook.xml on displayContactContent hook

### ISSUE THREAD

**Issue by thomasnares** [PrestaShop/PrestaShop#31270]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

displayContactContent is written as **dipslay**ContactContent

Humminbird and classic-themes does not have the error
ps_contactinfo does not have the error

### Expected behavior

Should be written as : displayContactContent

### Steps to reproduce

1. Create a module
2. Register a hook on "displayContactContent"

### PrestaShop version(s) where the bug happened

develop, 8.1

### PHP version(s) where the bug happened

all

**Comment by thomasnares** [comment]
Fixed by: https://github.com/PrestaShop/PrestaShop/pull/31367

**Comment by HanaRebaiQA** [comment]
Hello @thomasnares 

Thanks for your report.
Could you please provide us with more information about how to reproduce the issue? 
We need your tested module and the exact steps to reproduce with a screenshot or a screens-record.

Thanks!

**Comment by florine2623** [comment]
Thanks for the report @thomasnares
