### ISSUE TITLE
Product reference cannot be changed in multi-store setup

### ISSUE THREAD

**Issue by cruftex** [PrestaShop/PrestaShop#31287]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

It is not possible to change the reference of a product.

### Expected behavior

Changed product reference is visible in the product listing.

### Steps to reproduce

Steps to reproduce:
- new docker setup with 8.0.1
- enable multi store
- add a second shop "shop2" with virtual URL "shop2" and import all data

Next, see screen recording:

https://user-images.githubusercontent.com/2668191/217457030-84396484-8f17-48ce-84b2-10809d1dff76.mp4

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.1.9

**Comment by djoelleuch** [comment]
Hello @cruftex ,
I reproduce the issue with PrestaShop version 
8.0.0 ==> NOK  :x: 

[Untitled_ Feb 10, 2023 4_43 PM.webm](https://user-images.githubusercontent.com/115152460/218134528-6b5a972c-4b46-4de4-abbf-e6d3e87b387b.webm)


8.0.1==>NOK  :x: 

[Untitled_ Feb 10, 2023 4_45 PM.webm](https://user-images.githubusercontent.com/115152460/218134717-419bd7e1-51b4-453e-9b55-3e073ef0db12.webm)

1.7.8.8 ==> OK  :heavy_check_mark: 

[Untitled_ Feb 10, 2023 4_49 PM.webm](https://user-images.githubusercontent.com/115152460/218135455-9eb393ce-9f2b-4f35-9976-19ff69bd2eb2.webm)

Nice catch ! It's a regression ! :rocket: 
Thank you !

**Comment by ShaiMagal** [comment]
It's not only editing. But when you are creating new product, it's same. Reference doesn't save.

If you switch to any context except "all shops", you can edit/add reference. If you have context "all shops", you are not allowed to add/edit reference.

7Same issue for editing like creating new product.

We would appreciate to fix this issue.

Btw:
**PrestaShop 8.1 - same issue here...**

**Comment by ShaiMagal** [comment]
Here is the video (PS 8.1):
https://www.youtube.com/watch?v=yy79xwwhAyc
