### ISSUE TITLE
PrestaShop can't be installed on Google Cloud SQL.

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#31284]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Try to install ps 1788 with online live installer result in a database error.

1st error -> installer try both innodb and myisam engine without allow to choose one or other (google cloud sql db does not support myisam engine, with good reason).
2nd error -> You must have privileges to select data in tables of database "DBNAME". Ask your hosting provider to enable it.
Unknown table 'DBNAME.ps_test' 

The user as ALL PRIVILEGES on DB, login from adminer allow to create, populate and delete table for the configured database. 

### Steps to reproduce

Try to install ps 1788 with online live installer result in a database error.

1st error -> installer try both innodb and myisam engine without allow to choose one or other (google cloud sql db does not support myisam engine, with good reason).
2nd error -> You must have privileges to select data in tables of database "DBNAME". Ask your hosting provider to enable it.
Unknown table 'DBNAME.ps_test' 

The user as ALL PRIVILEGES on DB, login from adminer allow to create, populate and delete table for the configured database. 

### PrestaShop version(s) where the bug happened

1.7.8.8.

**Comment by matteolavaggi** [comment]
Need to FIX the classes/db/DbPDO.php.
I can't understand why you need to manually edit a class to install with the recommended engine and used on any compatible mysql cloud server. Why does this class force the default engine myisam which is no longer supported by anyone or anything? Is there any particular reason I'm missing?

**Comment by HanaRebaiQA** [comment]
Hello @matteolavaggi 

Thanks for your report.
Could you please provide us with more explanation about the steps to reproduce with a screenshot or a screen-record of the issue?

Cause on my side the 1788 is well installed manually.

Thank You!

**Comment by erlioniel** [comment]
Hi @HanaRebaiQA ,

I encountered exactly the same issue using Google Cloud SQL instance of MySQL 5.7

**Comment by matteolavaggi** [comment]
The installer is written gibberish. As it is written if it detects a
problem on myisam it fails the installation. it's ridiculous I know in 2023
but sadly that's the way it is. You can edit the DB connection file and
manually set the engine to innodb in all functions that require the
parameter engine = "" and force the test only on innodb.

Il Dom 19 Feb 2023, 19:13 Vladimir Kryukov ***@***.***> ha
scritto:

**Comment by florine2623** [comment]
@matteolavaggi ,

Can you follow the system requirement to make your installation ?
https://devdocs.prestashop-project.org/1.7/basics/installation/system-requirements 

Waiting for your feedback.
Thanks!

**Comment by matteolavaggi** [comment]
The problem is the validation script, not the system requirements... I'm
able to run multiple prestashop on Google cloud... The script has bug on
MySQL check.

Il Mar 21 Feb 2023, 10:58 florine2623 ***@***.***> ha scritto:

**Comment by florine2623** [comment]
I tested on local env and on production env, I didn't encounter the error.

Can you send screenshots of the error you have ?

**Comment by matteolavaggi** [comment]
Read carefully the bug report, this is relate to Google cloud SQL that does
not support anymore myisam (no one use isam on 2023).

Il Mar 21 Feb 2023, 18:00 florine2623 ***@***.***> ha scritto:

**Comment by florine2623** [comment]
ping @matks what do you think this issue. PrestaShop can't be installed on Google Cloud SQL.

> this is relate to Google cloud SQL that does
> not support anymore myisam (no one use isam on 2023).

**Comment by matks** [comment]
@florine2623 When PrestaShop is being installed, it attempts to detect the SQL engine being run behind the database service.

Both MyISAM and InnoDB engines are supported, however it is possible that for some SQL flavors the system is not error-proof.

@matteolavaggi Please check PRs https://github.com/PrestaShop/PrestaShop/pull/14402 (merged in 1.7.8) and https://github.com/PrestaShop/PrestaShop/pull/26588 (merged in 8.0.0) that provided improvements for MyISAM and InnoDB support, they might be the solution you're looking for. So it is possible the problem you report is solved with PrestaShop 8.0.0

**Comment by matteolavaggi** [comment]
I understand, what in my humble opinion doesn't make sense is maintaining a
buggy database engine control system, which doesn't allow you to use the
installer on one of the top three cloud service providers in the world. all
because of a check on an obsolete and completely useless database engine
like myisam. The future is Cloud sql and definitely not myisam.

Il Mer 22 Feb 2023, 09:28 Mathieu Ferment ***@***.***> ha
scritto:

**Comment by erlioniel** [comment]
Hi @matks,

Thanks for the reply, it makes complete sense. I think the issue is fixed in version `8.0.0` but in the latest `1.7.x` version it is still there on this particular line: https://github.com/PrestaShop/PrestaShop/blob/573839a859c92675af2d5482a3618426efad6ca1/classes/db/DbPDO.php#L415

The same code you can find in class `DbMySQLi.php`. If I'm not mistaken both methods are used only in one place: https://github.com/PrestaShop/PrestaShop/blob/ad181f7fb89dea67dfebba779a6440854baa6d5b/src/PrestaShopBundle/Install/Database.php#L81

Which is *never* passes database engine, which actually *forcing* test table to be created using `MyISAM` not supported by GCP. I agree with Matteo that it's quite odd, that the modern SQL cloud solution is causing troubles on installation only, even tho it's fully working after this step is passed.

**Comment by AureRita** [comment]
Hi @matteolavaggi 

Unfortunately, Your issue is already corrected on 8.0.0 so I have to close it. 

If you want, you can propose this as a new feature of 1.7.8. on this link : 
https://build.prestashop-project.org/news/2023/github-discussions-are-now-enabled-in-the-prestashop-project/
