### ISSUE TITLE
Add dry-run feature to licence header symfony command

### ISSUE THREAD

**Issue by WahbiPS** [PrestaShop/PrestaShop#31290]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Describe the solution you'd like
Add a dry-run parameter to the licence header command

#### Description
php bin/console prestashop:licenses:update --dry-run

It should be modified to add a `dry-run` parameter which does not perform the modifications but instead return an error, then this command can be added in a CI executed on each PR to block it in case some headers are missing

#### Complexity
Size: S

**Comment by lartist** [comment]
Closed in favour of using https://github.com/PrestaShopCorp/header-stamp/tree/master/bin that already implements dry-run

**Comment by matks** [comment]
Yes 😁 it's me https://github.com/PrestaShopCorp/header-stamp/pull/14

Because in 2020 I already wanted to run this tool in CI (for modules however) 😄 

But I could not find the time to finish it 😞 (I was doing that on my own time)
