### ISSUE TITLE
ps_facetedsearch 3.11 wrong search by query

### ISSUE THREAD

**Issue by codetypepl** [PrestaShop/PrestaShop#31298]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have noticed errors on the site after updating the ps_facetedsearch module from version **3.10 to 3.11**. When searching for goods in the store, e.g. **"Flour"**, **"Face cream"**, other goods than those phrases pop up. **After upgrading to version 3.10, everything is back to normal.**

### Steps to reproduce

Back to version 3.10

### PrestaShop version(s) where the bug happened

1.7.7.8

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

3.11

**Comment by codetypepl** [comment]
**### Flour**

![photo_2023-02-09_15-37-04](https://user-images.githubusercontent.com/106076459/217859762-1ddf7121-a600-41c8-afe7-5f8c993a47a5.jpg)

**Comment by Hlavtox** [comment]
Hi @codetypepl, there are currently two issues we know of.

- `ps_facetedsearch` is used to get products on search page, even if not enabled in any filter template. - 3.11.1 patch will be released in following days that will fix this issue.
- Relevance sort order doesn't work when `ps_facetedsearch` is enabled on the search page. - Still investigating, will probably be in some of the next versions. 

Sorry for inconvinience, my mistake.

**Comment by Hlavtox** [comment]
Also, I think that the products are there, but just in a different order, because faceted search just calls the core functionality, so it will find exactly the same results.

```
$result = SearchCore::find(
            $this->context->language->id,
            Tools::replaceAccentedChars(urldecode($this->query->getSearchString())),
            1,
            PHP_INT_MAX,
            'position',
            'desc',
            false,
            false,
            null
        );
```

**Comment by codetypepl** [comment]
Nothing happened alright :)

We look forward and wish you good luck with the publication of the new version @Hlavtox.

**Comment by Hlavtox** [comment]
@codetypepl Fixed by https://github.com/PrestaShop/ps_facetedsearch/releases/tag/v3.11.1. ;-)
