### ISSUE TITLE
During installation country choice is ignored

### ISSUE THREAD

**Issue by musicpanda** [PrestaShop/PrestaShop#31295]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

During installation you can choose a country. By default the country where you are is selected. 

It doesn't matter what country you choose. The installation will always proceed with the country where you are.

The cause is the select box that is shown during installation:
![country](https://user-images.githubusercontent.com/13930107/217849003-9afddac4-ade8-46b0-a863-8da34fc974ea.jpg)

This box is constructed instead of the html select element. This html select element is hidden and doesn't change no matter what choice you make in the visual box.

### Expected behavior

Installation of the selected country - with the languages and currency that belong to it.

### Steps to reproduce

Do an installation and choose another country than your own.

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @musicpanda 

I'm in Tunisia and when I access to install, it always select France 😉 
I tried with two installations and I didn't encounter your issue:
### PS 1.7.8.8 and country South Korea ✅ 
[issue_31295.webm](https://user-images.githubusercontent.com/23308427/218425340-4fb79af2-d465-4474-92ca-0cbb1e8fe5ca.webm)

### PS 8.0.0 and country Spain ✅ 
[issue_31310.webm](https://user-images.githubusercontent.com/23308427/218425286-1cd1c472-f0f8-4a4e-8a08-5e804cd38b60.webm)

Please check and feedback.

Thanks!

**Comment by musicpanda** [comment]
Did you try it with the Chrome browser? For me with Firefox it works ok, but with Chrome I have problems.

**Comment by hibatallahAouadni** [comment]
Hello Sir,

I'm using Chrome Version 109.0.5414.119 (Official Build). And as you saw I didn't encounter your issue.
Waiting for your feedback.

Thanks!

**Comment by djoelleuch** [comment]
Hello @musicpanda 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
 Please note that you can always create a new one if further information pops up.

Thank you
