### ISSUE TITLE
Translation Module Prestashop 1.7.8.8

### ISSUE THREAD

**Issue by geneclpa** [PrestaShop/PrestaShop#31291]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have problem with some translation. For example, I'm triying to change "Price" in Cart page but I can't because the translation doesn't apply.

Prestashop version 1.7.8.8

PHP version 7.4.33

Template Warehouse 4.5.7

![prestashop_problem](https://user-images.githubusercontent.com/37044638/217812959-13a14252-0869-48a2-b4d4-a714c8fa9a20.png)

### Steps to reproduce

1. Go to Internation
2. Go to Translations
3. Front office translations
4. Theme warehouse
5. Spanish language
6. Go Shop -> Theme -> Checkout -> Product or QTY and then change the translation and doesn't work

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4.33

**Comment by hibatallahAouadni** [comment]
Hello @geneclpa 

It seems your issue is related to your theme. Please switch to CLASSIC theme and change the translation, you will see that the translation has been updated.
Please check and feedback.

Thanks.

**Comment by d0niek** [comment]
The same problem here. After upgrade to `v1.7.8.8` modules translation stop works.
I'm using "new system" translation https://devdocs.prestashop-project.org/1.7/modules/creation/module-translation/new-system/

**Comment by geneclpa** [comment]
> Hello @geneclpa
> 
> It seems your issue is related to your theme. Please switch to CLASSIC theme and change the translation, you will see that the translation has been updated. Please check and feedback.
> 
> Thanks.

Thanks for your response but in my case it didn't work.

**Comment by geneclpa** [comment]
> The same problem here. After upgrade to `v1.7.8.8` modules translation stop works. I'm using "new system" translation https://devdocs.prestashop-project.org/1.7/modules/creation/module-translation/new-system/

Thanks for your comment. In view of the fact that the translations problem is in the checkout and costumers modules and I still haven't been able to solve it.

**Comment by HanaRebaiQA** [comment]
Hello @d0niek 

Thanks for your report.
Does your issue similar to this one #31578 ?

I have answered on this [comment](https://github.com/PrestaShop/PrestaShop/issues/31578#issuecomment-1451672130).

Could you please check again and we are waiting for your feedback!

**Comment by d0niek** [comment]
I think no.

My custom theme translations works well.

My custom modules translations stop work, in front- and back- office.

**Comment by AureRita** [comment]
Hi @doekia 

If I understand correctly, the problem does not come from our module but from a personal module? 

Waiting for your feedback

**Comment by d0niek** [comment]
After upgrade Prestashop from `v1.7.8.7` to `v1.7.8.8` translations of my modules stop working.

Theme translation (classic and my custom one) and backoffice translation are working. Translations of my modules stop working in front- and back- office.

**Comment by AureRita** [comment]
Because your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

I regret to announce that I will have to close this issue.

Thank you

**Comment by d0niek** [comment]
@AureRita please can you explain me more.

I have just upgraded Prestashop.
I have not changed my dev/prod configuration.
I have not changed my modules.

How it can not be a "core bug"?

**Comment by AureRita** [comment]
Hi @d0niek 

It's not a core bug because it's a personal module, so you can contact the developer of the module to have more information

**Comment by d0niek** [comment]
@AureRita I see.

I'm the developer of that modules.

I have made fresh install Prestashop `v1.7.8.7` and fresh install Prestashop `v.1.7.8.8`. In version `*.7` modules translations are working, in version `*.8` aren't.

I've follow this guide, domain is `Modules.Mymodulename.Admin` and in main module class I have entry

```
public function isUsingNewTranslationSystem()
{
    return true;
}
```

In translation (International > Translations > Installed modules) I see all my text to be translated. They're translated but they don't work in front- and back- office.

**Comment by Caleydon** [comment]
I can confirm - this is a bug.

I've got the same problem with theme Panda. I've got existing translations using without problem on PS 1.7.8.7 and earlier. On PS 1.7.8.8 the translations can't load.

**Comment by Hlavtox** [comment]
@AureRita Translations should work for all modules and themes, please don't close issues you know nothing about.

**Comment by d0niek** [comment]
I haven't test it yet (and translate) but maybe this is a solution https://www.prestashop.com/forums/topic/1073741-error-al-intentar-traducir-en-prestashop-8/?fbclid=IwAR1R01NwNegHrvbmjPHFYY7GRYDNCLDcXCetEyAanBIoWIeLg3B1PxwJ9ns?

**Comment by d0niek** [comment]
I don't know if it's related with this issue but when I translate module with "legacy format" and after click `Save` or `Save and stay` I'm always redirected to the main shop page. Translations are save.

**Comment by d0niek** [comment]
Hi @geneclpa !

It works! I don't know if it's correct workflow or it's just a work around but ...

1. Translate your module from backoffice: `International > Translations > Modify translations`.
2. After save go back and export your module translation: `International > Translations > Export a language`.
3. Unzip and upload folder `en-US` (or any other language) to **modules/yourmodulename/translations/** directory.
4. Clear cache (I haven't test it from `Advanced Parameters > Performance > Clear cache`): `bin/console cache:clear --no-warmup` or `rm var/cache/* -rf`.
5. Refresh page and front- and back- office translation should appear.

It looks like Prestashop translation doesn't load translations from `ps_translation` database table, it loads translation only from exported files (new translation system).

**Comment by Caleydon** [comment]
> It looks like Prestashop translation doesn't load translations from `ps_translation` database table, it loads translation only from exported files (new translation system).

Right. The loading of translation from the files working. But the translations 3-rd party modules from PREFIX_translations DB table can't load. This is the issue.

**Comment by kuchomik** [comment]
@d0niek 
I tried to follow the workaround steps you provided, but it didn't work for me. Are you sure that no steps are missing?
I can see correct translations in the exported file (step 3). But after performing step 4 and 5 I can still see corrupted translations in newly created cache files. Any clues?

example:
cache file:
![image](https://github.com/PrestaShop/PrestaShop/assets/31128593/d680750f-461b-45d8-bc91-ba6f1a602bc6)

source file (ShopThemeActions.pl-PL.xlf):
![image](https://github.com/PrestaShop/PrestaShop/assets/31128593/ee676bbb-da4c-4024-8f1f-da7e1c530882)


What's curious for me is that under SOME conditions the translations system takes proper values from my translation... but I am not able pinpoint it. 

I'm running PS 1.7.8.9 on php 7.4.33.

PS. Is there any other way than manually modifying cache files?

**Comment by d0niek** [comment]
@kuchomik it's really wired. Have you check what translation is in the back-office (`International > Translations > Modify translations`)? Maybe there is an old translation and PS somehow read it from db instead of file?

**Comment by kuchomik** [comment]
@d0niek 
Of course I did it before posting :) 
![image](https://github.com/PrestaShop/PrestaShop/assets/31128593/f45ee6af-6a74-4882-bb3a-d55a9970cf41)

**Comment by kpodemski** [comment]
Hi everyone. Sorry for how the issue was handled before.

I must say that I've been using this new translating system for a while and didn't encounter described issues, but I believe something was wrong.

I didn't reproduce this issue with PrestaShop 8.1.0 tho, it is the only supported version right now. I'm attaching the module I've used, and please test your modules on PrestaShop 8.1, if there's something wrong, let us know, and I will reopen this ticket.

[kptesttranslations.zip](https://github.com/PrestaShop/PrestaShop/files/12180331/kptesttranslations.zip)

For 1.7.8, you may want to explore this fix: https://github.com/PrestaShop/PrestaShop/pull/30114 - maybe it messed something up with the domains in the front office, and we missed it then on 1.7, but it fixed a critical issue in the legacy translations. I'll let you guys explore the subject.

Remember that: me, closing this ticket, doesn't mean we don't care, or we won't investigate it further if needed. Believe me, I'm the first person who was super frustrated with a lot of bugs the new translation system introduced, and I would love to help you if there are any left :)
