### ISSUE TITLE
Wrong admin tab name for AdminParentStores

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#31297]
### Describe the bug and add attachments

💡 Still investigating 💡

On my develop install, I have `CMS page` instead of `Contact` in the left column. Tab name is `AdminParentStores`.

![tab](https://user-images.githubusercontent.com/6097524/217857336-181cb07e-25c5-4a0e-9b13-5aa1e2846f09.jpg)

ps_tab seems to be correct:
![ps-tab](https://user-images.githubusercontent.com/6097524/217857614-bed873f3-ccd8-4f61-9d6a-e4ab7b085b02.jpg)

ps_tab_lang has wrong data:
![Snímek obrazovky 2023-02-09 164135](https://user-images.githubusercontent.com/6097524/217861654-7280e705-a445-4d0b-8af9-2c57c652b794.jpg)

### Steps to reproduce

It should be reproduced by installing develop in Czech, importing English language and changing the employee lang to English.

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

**Comment by eternoendless** [comment]
![image](https://user-images.githubusercontent.com/1009343/218062519-29535836-6390-4d30-8bad-d7336eb21a4f.png)
For the record, it seems to be a mistranslation issue. Will be fixed on Crowdin.
