### ISSUE TITLE
Image appers in not webp format when option "Use WebP for all images" is selected

### ISSUE THREAD

**Issue by web-burn** [PrestaShop/PrestaShop#31301]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I installed the PrestaShop 8.0.1. 
I set option "Use WebP for all images":
![image](https://user-images.githubusercontent.com/22581200/217890687-0fb29663-ec44-4fd6-9e17-23cbcc80b96f.png)

Regenerate all images:
![image](https://user-images.githubusercontent.com/22581200/217890835-e0a041c3-a9ec-4ec2-beb4-7d6cff7fcada.png)

But front office images still have jpg:
![image](https://user-images.githubusercontent.com/22581200/217892149-b9d82c15-24ab-46b3-a60f-a845bbe497aa.png)

What the front office image don't have .webp extension in front office?

### Expected behavior

If option "Use WebP for all images" is selected then images appear in webp format in front office (image.webp example).

### Steps to reproduce

1. Image settings. 
2. Set "Use WebP for all images".
3. Regenerate all images.
4. Check images extension in front office.

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.1.15

**Comment by TOPServiciosInformaticos** [comment]
i have same problem

**Comment by Hlavtox** [comment]
Hi, images are in webp format, but they have a jpg extension. I don't know why somebody thought it is a good idea to do it like this, probably for historic reasons.

I suggest to wait for 8.1 for few months, this feature is reworked and you will have checkboxes for every format and it will generate `image.jpg`, `image.webp` and `image.avif`. 👍

**Comment by Hlavtox** [comment]
Btw, did you read what is written on your screenshot? 😁

![6052421A-F375-444D-B7AD-E3A2C2EF0A38](https://user-images.githubusercontent.com/6097524/217923375-1cca3cde-cc53-4371-88e6-f1648f93e040.jpeg)

**Comment by web-burn** [comment]
[Hlavtox](https://github.com/Hlavtox), oh, i see it. 
I have noticed just what images in front office have more light size when webp is seleted in settings.

**Comment by hibatallahAouadni** [comment]
Hello @web-burn 

Thanks @Hlavtox for your quick replies (as usual you 🚀 ).
Closing the issue as this issue is fixed on 8.1.0 (that will be released in few months)

Thanks!

**Comment by amazingballzs** [comment]
Why webp images have to appear as jpg?

**Comment by web-burn** [comment]
@amazingballzs, 
The PrestaShop 8.1.0 allows to display images in webp format:
![image](https://user-images.githubusercontent.com/22581200/231078240-2ed365fe-f142-4f44-9adf-b0d3dad826ce.png)
![image](https://user-images.githubusercontent.com/22581200/231078398-ec6befc2-14e6-4979-ab06-e3b7665a66c9.png)

**Comment by amazingballzs** [comment]
Prestashop 8.0.2 in the advanced parameters > New & Experimental Features section  do not show up these options seen in the pictures above

In PS 8.0.2 version all what is shown in that section is an option to enable "New product page - Single store" (or for multistore if enabled), besides that the use of these experimental features is strongly discouraged for production websites, of course.

Overall I just do not understand why a webp image should be masked to be a jpg image, nor I found reasonbale explications anywhere for this behaviour. Why do prestashop disguise png and webp images to be jpg images?

**Comment by Hlavtox** [comment]
@amazingballzs The new behavior is implemented in 8.1 that is comming in following months. You will be able to generate all formats properly.

**Comment by xga91** [comment]
if we generate all format image, do prestashop will send the compatible image format for the browser ?

if the browser can show all format images which one will be given to the brower ? webp by default ?

**Comment by Hlavtox** [comment]
No, browser will select the best `<source>` from a `<picture>` tag.

**Comment by ArnasL** [comment]
I still have the issue in PS 8.1.2 that images represented as .jpg. I selected WebP, regenerated all images, but in FO shows images with .jpg extension? What am I missing?
![Uploading Screenshot 2024-01-24 at 05.34.51.png…]()


It happens even if I upload image .webp, it renders as .jpg WHY ???

**Comment by Hlavtox** [comment]
@ArnasL male sure to enable “multiple image formats” feature flag

**Comment by ArnasL** [comment]
I did. here is proof - https://ibb.co/WfPwrYh
Is there something else?

**Comment by Hlavtox** [comment]
Did you enable the webp format in Image settings? If yes, then if you go into front office and inspect product image, you should see a picture tag with multiple sources.

**Comment by ArnasL** [comment]
Yes, I have enabled here is my settings - https://ibb.co/P1ZX8xv
Unfortunately I don't see picture tag.
