### ISSUE TITLE
ps_imageslider

### ISSUE THREAD

**Issue by ratchetgang** [PrestaShop/PrestaShop#31315]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Bonjour, j'essaye d'utiliser prestashop avec ionos mais il me rapporte un erreur 500 
avant je l'avais installer sur google cloud et pareilles des erreurs sur google c'etait lorsque je mettais le site en francais il me mettait server not found et la c'est lorsque j'utilise le carrousel il me donne une erreur 500 lorsque je veux enregistrer mes modification sur prestashop et ionos

### Expected behavior

le module devrait enregistrer mes modifications

### Steps to reproduce

1. installer prestashop sur ionos 
2. aller dans modules
3. gestionnaire de module 
4. taper carrousel dans la bar de recherche
5. configurer carrousel et enregistrer

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by hibatallahAouadni** [comment]
Hello @ratchetgang 

Please send your request in English. English is the norm on GitHub.

Thank you

**Comment by florine2623** [comment]
Hello @ratchetgang ,

I can't reproduce your issue.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
