### ISSUE TITLE
Impossible to open an order in multishops :  An exception has been thrown during the rendering of a template ("Unable to load template 'file:catalog/_partials/miniatures/product.tpl'").

### ISSUE THREAD

**Issue by sextoysunivers1964** [PrestaShop/PrestaShop#31316]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,

When I try to open an order I get this error instead  :

An exception has been thrown during the rendering of a template ("Unable to load template 'file:catalog/_partials/miniatures/product.tpl'").

Best regards,
JC

### Expected behavior

To be able to open an order to then be proccesed

### Steps to reproduce

Go to :Orders page
Clic to the order
Error after clicking : An exception has been thrown during the rendering of a template ("Unable to load template 'file:catalog/_partials/miniatures/product.tpl'").

[Twig\Error\RuntimeError 0]

Short video to see the bug : https://app.usebubbles.com/eV2YQHgimnRfXBRiDYr9EL/untitled-bubble

### PrestaShop version(s) where the bug happened

1.7.7.2

### PHP version(s) where the bug happened

PHP 7.3

**Comment by Hlavtox** [comment]
That impossible. It's caused by some of your modules.

**Comment by sextoysunivers1964** [comment]
I'm going to check one by one

Thank you very much.

Have a nice weekend!!

Juan Carlos

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
