### ISSUE TITLE
"Trying to access array offset on value of type null", WebService "/api/categories?schema=blank"

### ISSUE THREAD

**Issue by andreluizsr90** [PrestaShop/PrestaShop#31313]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Using API when trying to retrive a empty category "/api/categories?schema=blank".

The webservice returns error 500 (internal server error):
[PHP Warning #2] Trying to access array offset on value of type null (/var/www/eztoshop/ps/classes/webservice/WebserviceOutputBuilder.php, line 669)

This is similar to the issue #28279.

To fix it temporaly I changed the line 669
From: `if (empty($fields_assoc)) {`
To: `if (empty($fields_assoc) && !is_null($value)) {`

### Steps to reproduce

1. Connect in PS WebService
2. Call endpoint: "/api/categories?schema=blank"

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

PHP 8.0.27 (cli) (built: Feb  7 2023 11:33:40) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.27, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.27, Copyright (c), by Zend Technologies

**Comment by hibatallahAouadni** [comment]
Hello @AndreLuizSr 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #28543. 
This issue is fixed on the next version 8.1.0, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #28543
