### ISSUE TITLE
Abandoned cart with many products makes order creation slow

### ISSUE THREAD

**Issue by blawdi** [PrestaShop/PrestaShop#31328]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When a cart with several products (more than 1000) is abandoned with the name of a customer, it makes the cart creation display very slow in the back office.

### Expected behavior

A normal display 1 or 2 seconds

### Steps to reproduce

Create a client
Make a basket with many different products
Go to the Backoffice
create an order manually with the customer
The list of baskets takes a long time to be displayed and you can't search for products to add to the cart

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment]
Hello @blawdi 

I didn't manage to reproduce your issue following your steps, see the attached screen record below:

[issue_31328.webm](https://user-images.githubusercontent.com/23308427/218777957-1b570efc-f342-4145-aa6d-cf2ad78650aa.webm)

As you can it took only a second to display the product list in the cart, and one second to display the result of search.
Please check and feedback.

Thanks!

**Comment by blawdi** [comment]
Hello, thanks you for ur try, if not correct

I use a translator, that's probably why.

We need many more different products here is a video
https://mega.nz/file/WxNnEAwZ#4YU9xLMrmJkxzMz5PBHzgg7iXSdSWRCN1E05TZArHJI

**Comment by hibatallahAouadni** [comment]
Hello @blawdi 

Yep, you're right it's caused by this issue #30206
I will close yours as a duplicate cause it will be fixed when this issue #30206 is fixed.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #30206
