### ISSUE TITLE
Prestashop erase hooks from products that have a new feature added

### ISSUE THREAD

**Issue by chantes5697** [PrestaShop/PrestaShop#31343]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I added a feature to 2 products and the shop erased the hooks of the page of said products like the head and it ends like this: 
![image](https://user-images.githubusercontent.com/42250478/218530206-a1fb7c25-0b46-4811-8ced-a17c05658b91.png)

I need to fix this, this is an urgent matter since it is a catrastophic bug

### Expected behavior

just add the feature and expect that every parent hook would be obliverated from the product page

it should look like this:

![image](https://user-images.githubusercontent.com/42250478/218530653-b20cbc86-78e7-4e7d-a353-db8e9e3c781c.png)

### Steps to reproduce

1. Create a new feature
2. Add some random values
3. Add the feature and its value to a product
4. Go to that product page

### PrestaShop version(s) where the bug happened

1.7.7.0

**Comment by hibatallahAouadni** [comment]
Hello @chantes5697 

Your issue is related to your custom theme and it's not related of adding some features to your products.
As you can in the screenshot below, my product has two features and it's well displayed:

<img width="1191" alt="Screenshot 2023-02-14 at 21 38 49" src="https://user-images.githubusercontent.com/23308427/218857637-379d515d-5097-4545-99e8-fb8b2e28f4c1.png">

Switch to CLASSIC theme and check if you still encounter the problem.
Waiting for your feedback.

Thanks!

**Comment by chantes5697** [comment]
i checked with classic and yeah, it is a theme issue, still isn't there a way to find the missing hooks in the theme?

**Comment by hibatallahAouadni** [comment]
Hello @chantes5697 

Sorry but I can't help you any further cause we only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you
