### ISSUE TITLE
BO - Employee - Invalid Token When you create a new employee 

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#31341]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I create a new employee and I don't set the dashboard at the default page, when I'm login in with this new account, I'll have an invalid token, as we can see here : 

[Untitled_ Feb 13, 2023 5_24 PM.webm](https://user-images.githubusercontent.com/100699445/218516466-10b357fa-6785-4c1f-92c2-592939b1f1ca.webm)

### Expected behavior

I don't want an invalid token 

### Steps to reproduce

1. Go to Advanced Parameters 
2. Disable the cache 
3. Go to Advanced Parameters > Team > Employee 
4. Add new employee 
5. Set permission profile on "Translator"
6. Set default page to "Product" 
7. Save 
8. Disconnect for the super user 
9. Connect with this new employee 
10. Have the invalid token 

### PrestaShop version(s) where the bug happened

8.0.x - not develop 

### PHP version(s) where the bug happened

7.4

**Comment by HanaRebaiQA** [comment]
Hello @AureRita 

Thanks for your report.
I tried to reproduce your issue using the same steps to reproduce and even with the other data mentioned in your video on **PS8.0.x** with both **PHP 7.3** and **PHP 7.4**. But, I was unable to reproduce it.

The data mentioned in your video : 

- Set permission profile on "Salesman"
- Set the default page to "Invoices"


https://user-images.githubusercontent.com/92912932/218692723-757eef49-d950-408c-95d3-7ee77a620b41.mp4

Could you please check it again?

Thank You!

**Comment by AureRita** [comment]
Hi @HanaRebaiQA, 

Thank you for your check, I tried to reproduce it with a new fresh install of 8.0.x and I can't do it. So this is not a PrestaShop core bug but most likely a server configuration or customization problem.

I will close this issue.

Thank you
