### ISSUE TITLE
Not able to set position of a product in an empty category

### ISSUE THREAD

**Issue by TomLorenzi** [PrestaShop/PrestaShop#31340]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I'm trying to push a product to a new created category that is still empty using the WS.  
My product have these keys and values :  
`id_category_default` => `my_new_id`  
`position_in_category` => `1`.

I'm getting a 500 error (code 135). because the position is higher than the total number of products in the category (0 currently).

### Expected behavior

It should accept new products with position being (current product count + 1).

### Steps to reproduce

Try to push a product in a empty category in `id_category_default` with `position_in_category` set to 1. It should work properly. Same as if you want to set a new category to a product. The category containing 3 products you want your product to be in 4th place. So push the `id_category_default` and `position_in_category` set to 4. It should work. Then test again the same request but with `position_in_category` set to 5, it should not work.

### PrestaShop version(s) where the bug happened

1.7.8.8 and develop

### PHP version(s) where the bug happened

7.4

**Comment by TomLorenzi** [comment]
Actually can get over it with just unsetting the position. But no way to set an higher position for now

**Comment by hibatallahAouadni** [comment]
Hello @TomLorenzi 

Your issue is similar to these issues #31035 & #26761 & #14903
Please check and feedback.

Thanks!

**Comment by TomLorenzi** [comment]
- Not related to this one : https://github.com/PrestaShop/PrestaShop/issues/31035
- Seems duplicated of this one right : https://github.com/PrestaShop/PrestaShop/issues/14903

**Comment by hibatallahAouadni** [comment]
Duplicate of #14903
