### ISSUE TITLE
BO - Invoices - Enable product image doesn't work

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#31354]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After Enabling product image on Invoice, I don't see the product image displayed on the invoice

<img width="961" alt="Screenshot 2023-02-14 at 15 25 35" src="https://user-images.githubusercontent.com/16019289/218766694-9d2d63ea-9110-49db-b673-263a59ae8096.png">

It is a regression on 8.1.0 beta. The issue was not present on 8.0.1.

### Expected behavior

The product image should be displayed
<img width="962" alt="Screenshot 2023-02-14 at 15 25 32" src="https://user-images.githubusercontent.com/16019289/218766407-00ebc9ce-e96e-40fe-90bd-5d86d2059b58.png">

### Steps to reproduce

1. Go to BO > Orders > Invoices > Enable product image
2. Go to Orders > Change status of order to Payment accepted
3. Click on order
4. No image is displayed

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.1

**Comment by hibatallahAouadni** [comment]
Hello @florine2623 

I didn't manage to reproduce the issue with PS810 and PHP 7.2, see the attached screen record below:

[issue_31354.webm](https://user-images.githubusercontent.com/23308427/219248700-793bf424-c360-4b7f-b0c7-916ba486c2af.webm)

It seems the issue related to PHP version 🤔 did you reproduce the issue with PS800 and PHP 8?
Please check and feedback.

Thanks!

**Comment by florine2623** [comment]
Hello @hibatallahAouadni ,

I tested with PS 8.1.0 and PHP 8.1.15.

There's a slight difference in spaces between the 2 options. But still no image displayed. 

| Product disabled  | Product image enabled |
| ------------- | ------------- |
| <img width="962" alt="Screenshot 2023-02-16 at 16 47 39" src="https://user-images.githubusercontent.com/16019289/219416741-7c7a2d77-256e-46f3-9cde-46c1e1124df3.png"> | <img width="962" alt="Screenshot 2023-02-16 at 16 47 46" src="https://user-images.githubusercontent.com/16019289/219416776-a454d234-1570-4128-a415-1395dc734329.png"> |

In BO > Order the image exists and is displayed correctly:
<img width="780" alt="Screenshot 2023-02-16 at 16 46 59" src="https://user-images.githubusercontent.com/16019289/219416534-97fe0bda-4e63-42d7-85c0-9c9050fb5cea.png">

**Comment by sallemiines** [comment]
Hello @florine2623 
I didn't manage to reproduce the issue with **PS810 with PHP 7.4 and PS810 with PHP 8.0**, see the attached screenshot :


![IN000002-1-pdf](https://user-images.githubusercontent.com/31663369/219660652-4455b596-1bfe-4975-a97a-f06755420f8f.png)


Please check and feedback.

Thanks!

**Comment by florine2623** [comment]
I think it might be a server configuration issue if you can't reproduce it 🤔 

I'll close it until I have new information about it.

Thanks!
