### ISSUE TITLE
BO - Attributes value - Missing error on Save button

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#31359]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

This error is displayed only when I **Save** my value, not when I **Save then add another value**

<img width="1246" alt="Screenshot 2023-02-14 at 16 27 54" src="https://user-images.githubusercontent.com/16019289/218782428-1fb06ea7-26e9-4e7d-ae47-26e5825b3ea8.png">

When the error is not displayed, I am redirected to the list of attributes and my attribute is not saved.

### Expected behavior

I should have the same error message whether I click on "Save then add another value" or "Save"

### Steps to reproduce

1. Go to BO > Catalog > Attributes & Features
2. View Color > Add new value
3. Add a Value, a Color and a Texture : .mov
4. Click Save 
5. Error : Image format not recognized, allowed formats are: gif, jpg, jpeg, jpe, png, webp ✅ 
6. Add a Texture with a .mov file
7. Click Save then add another texture
8. No error is displayed :x: 

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1

**Comment by hibatallahAouadni** [comment]
Hello @florine2623 

I didn't manage to reproduce the issue with PS810, PS800 and PHP 7.2, see the attached screen record below:

[issue_31359.webm](https://user-images.githubusercontent.com/23308427/219266151-993d1942-3ae3-4e1f-8cbb-1a064887175e.webm)

Please check and feedback.

Thanks!

**Comment by florine2623** [comment]
Hello @hibatallahAouadni ,

I couldn't reproduce my issue on another installation on a different server.
I might have had an misconfiguration somewhere.

I'll close the issue ^^
