### ISSUE TITLE
BO - Strange behavior Order reference is suddenly a number and Invoice Number is always 2147483647

### ISSUE THREAD

**Issue by nibelungen** [PrestaShop/PrestaShop#31369]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

As you can see, the order reference switched from letters to numeric, thats not the biggest concern - it is the malfunction and always the same invoice number since february 2022
![image](https://user-images.githubusercontent.com/1270854/218973009-c36c5dce-17d4-4a3f-9116-d7be8a81e8f2.png)
![image](https://user-images.githubusercontent.com/1270854/218978146-f42c9b38-5075-43f5-8e8c-fd9af8cd5c36.png)
(before this bug report i changed the old orders via database - if i create a new one like in the last line - the invoice number is
still the highest number in the invoice id field and if i create another order, the invoice id will still be the same: 214748364)
I also checked the ps_configuration 
![image](https://user-images.githubusercontent.com/1270854/218979191-99322819-7f1b-43d3-82b7-f5c91f0af03b.png)
To be a little bit more precise - it should look like 
![image](https://user-images.githubusercontent.com/1270854/219001651-bd2dea15-9792-43e5-893a-e020bb6650b6.png)
but now every invoice looks like this
![image](https://user-images.githubusercontent.com/1270854/219001754-a730293b-9bd0-470d-9c87-84b05575e0d3.png)

### Expected behavior

Letters in Order reference and counting invoice numbers.

### Steps to reproduce

As it occurde without any upgrade or changes i dont know how to reproduce.
Maybe it was one of these upgrades:
![image](https://user-images.githubusercontent.com/1270854/218974116-f4986fd4-ca46-49d9-95be-fce9c98e60da.png)
Obviously i missed to check the complete functions after the upgrade from 1.7.8.0 to 1.7.8.2 
The last check was after the upgrade from 24.01.2022 (Order Number 38).
I checked the ps_orders Table and find out the order reference was from the beginning a number and switch at a specific time to the default one:
![image](https://user-images.githubusercontent.com/1270854/218976169-1c998bcf-d157-4d1a-bd43-1833bab025eb.png)
I dont know what happend in between, the only module i use (from the beginning) is the default paypal one.

Compared with the upgrade date it seems like it switched with the upgrade from 1.7.7.3 to 1.7.8.0 to letters only.
And later back to numbers.
The occurence with the wrong / not counting invoice id happend first after Order 40 and could not be fixed, so i dont see any accordance with the first switch from numbers to letters in order reference. 

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4.28

**Comment by florine2623** [comment]
ping @PrestaShop/prestashop-core-developers ,
Maybe it's related to https://github.com/PrestaShop/PrestaShop/issues/31277
What do you think ?

**Comment by nibelungen** [comment]
@florine2623, maybe - i found older entries in the prestshop forum with issues around the 'magic' number 2147483647

My system seems to be 64bit:
php -r "echo 'Min: '  .  PHP_INT_MIN . ' Max: ' .  PHP_INT_MAX . PHP_EOL;"
Min: -9223372036854775808 Max: 9223372036854775807

**Comment by nibelungen** [comment]
I cloned the system into a dev system and made an upgrade to 8.0.1 - i had to change the last ps_orders und ps_order_invoive to update the 2147483647 values to be in line with the previous numbers - so far it looks good. 
The upgrade change some template parts that where disabled before and some translations got lost... 
I will try it further with the new latest version.

**Comment by hibatallahAouadni** [comment]
Hello @nibelungen 

Do you still encounter the issue with 8.1.x? Please check and feedback.

Thanks!

**Comment by nibelungen** [comment]
Hi,
to be tax cpmliant i made a quick and dirty upgrade to 8.0.4. and this issue was not present. 
I am still at 8.0.4 so i cant tell if it is part of 8.1.x - i will soon upgrade. i delayed it because of another error where the invoice in backend is allways in englisch. Maybe that is fixed too, didnt check the changelog so far.

**Comment by MHC-France** [comment]
It seems to be still active with 8.1.4. Test made with new DB...
