### ISSUE TITLE
Conflict between the declinations and the multiboutique

### ISSUE THREAD

**Issue by Gaja-A** [PrestaShop/PrestaShop#31362]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,

I tried to generate the same group of attributes by selecting them from the list on the right, it is not working.

For example, I have already generated some attributes for the group **Vernis à Ongles 1944** and when I try to add another attribute from the same group, it doesn't generate whereas when I select a different group of attributes, it works.

To generate the attributes from the same attribute group, I have to search for that attribute in the search bar and then generate it so that it saves.

https://www.loom.com/share/1bb8868f25434bba93ef72d5d2cad382

Any solution ?

Regards,
Gaja

### Steps to reproduce

![image](https://user-images.githubusercontent.com/51961329/218794721-be3f29c8-87ff-49d8-9256-c355b7bbf8b6.png)
![image](https://user-images.githubusercontent.com/51961329/218794801-f1582844-3512-4468-9b55-799eaa138c49.png)

### PrestaShop version(s) where the bug happened

1.7.8.2

**Comment by hibatallahAouadni** [comment]
Hello @Gaja-A 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must respect the template to submit a complete bug report and provide clear and concise steps to reproduce**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
