### ISSUE TITLE
1-Click Upgrade fails from v.1.7.8.8 to 8.0.1

### ISSUE THREAD

**Issue by madibashop** [PrestaShop/PrestaShop#31376]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I try to upgrade from v 1.7.8.8 to 8.0.1 with 1-Click Upgrade v.4.15.0.
PHP version is 7.4
MySQL version is 5.7
I deactivate non native modules, overviews and cache.
Shop offline.
Upgrade process result in some errors: 

[Errores actualización 1.7.8.8 a 8.0.1.txt](https://github.com/PrestaShop/PrestaShop/files/10742478/Errores.actualizacion.1.7.8.8.a.8.0.1.txt)

After this errors the web page fails in some situations:
Back office: It's not possible to navigate from root category to subcategories: 500 Error.
Front office: Main menu only opens root category. The rest of the menu only shows white pages.

### Expected behavior

I expected upgrade without errors.

### Steps to reproduce

Go to advanced parameters - perfomance: cache off and clear cache.
Go to shop - configuration - maintenance: offline.
Go to 1-Click Upgrade v.4.15.0 deactivate non native modules and overviews. Only mail templates on.
Run upgrade.
Result: errors commented before.

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @madibashop 

It seems you're using a custom theme and you didn't switch to CLASSIC before upgrading.
Try to switch to CLASSIC theme and check if you still encounter the issue, if not, means that you need to contact the theme developer to upgrade his theme.
If you still encounter the issue, try to roll-back and check if your categories are accessibles, if so, switch to CLASSIC theme and upgarde your shop. You will not encounter any issue 😉 

Closing the issue as it's not Core bug.
Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you

**Comment by madibashop** [comment]
Hello Hibatallah Aouadni

I am using CLASSIC theme, version 1.0.0.
All categories were accessible before upgrade.

Thank you
