### ISSUE TITLE
BO - The customer service view page is displayed as a migrated page while the Customer threads feature flag is deactivated 

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#31377]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Since 8.0.0 we use feature flags to hide migrated pages that are not finished.

The "Customer Service" **View** back-office page migrated to Symfony is accessible when the "Customer threads" feature flag is deactivated. It should not be accessible.

**8.1.0_betabuild1 : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/219035645-10643288-c8ff-46c1-81b3-18c6e99f8c64.png)

https://user-images.githubusercontent.com/92912932/219036085-86e79ba6-00c5-49fe-8077-3a8a6201258e.mp4

### Expected behavior

When clicking on the "View" link on the _legacy_ back-office "Customer service" page, we should not be redirected on the _migrated_ "customer service" View back-office page. We should be redirected to legacy Customer service View page instead.

### Steps to reproduce

1. Install the 8.1.0_beta_build1 (branch `8.1.x`)
2. Go to back-office in Advanced parameters > New & Experimental Features. Then make sure the Feature Flag of Customer Threads is _disabled_
3. Go to Back-office SELL > Customers > "Add a new Customer" page, then create a new customer
4. Go to Front-office. You are going to create a fake customer support request 😁 using the customer you just created. Login using the customer login/password then in your "My account" space, go to "Contact US" > Fill in the information of the Customer request with the created customer and submit it.
5. Go to back-office again. Go to SELL > Customer Service > Click on to View: you can see the sent customer request you just created. 
6. Click on "View": you have been redirected to the "View Customer service" Symfony page. It is the problem. You should have been redirected to the "View customer service" legacy page.

### PrestaShop version(s) where the bug happened

8.1.0_beta_build1, develop

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @HanaRebaiQA 

This is the migrated page 😅 see the attached screen record below:

[issue_31377.webm](https://user-images.githubusercontent.com/23308427/219262292-074887e1-7299-4370-81e0-57e0940a2ffe.webm)

Thanks!

**Comment by hibatallahAouadni** [comment]
I reopened the issue cause it seems that I missed a step :sweat: following Hana's steps I reproduce the issue :slightly_smiling_face:

**Comment by boherm** [comment]
On it!

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/31674
