### ISSUE TITLE
BO - Languages - Language page throws Exception when file added is too big

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#31372]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Exception is thrown when I add a file too big for Flag field during creation of language. 
Edition of a language does not throw any error.

`Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 25169920 bytes)`

https://user-images.githubusercontent.com/16019289/218999128-f30b5f5a-aa72-4fe4-bfbc-fca0ec9883dc.mov

In 1.7.8.8, no exception was displayed. It is a regression.

### Expected behavior

No Exception should be displayed

### Steps to reproduce

1. Go to BO > International > Language > Add a new language
2. Add a big file in Flag field
3. Save 
4. See Exception

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.1

**Comment by HanaRebaiQA** [comment]
Hello @florine2623 

Thanks for your report.
I tried to reproduce your issue using a big file (.mov and .mp4) but i have this error message
![image](https://user-images.githubusercontent.com/92912932/219424066-feba4345-d5e4-4374-b9fa-7fb1d47d4995.png)

Could you please check it again ? Maybe it needs a force refresh.

Thank You!

**Comment by HanaRebaiQA** [comment]
ping @PrestaShop/qa-team Could someone else try to reproduce it please ?

**Comment by djoelleuch** [comment]
Hello @florine2623 ,
I tried to reproduce your issue but i have this error message .

https://user-images.githubusercontent.com/115152460/225373025-623c001e-32c2-40a1-8b4b-8c8f4c249e26.mp4

We will close this issue.

Thank you .
