### ISSUE TITLE
BO - Shopping carts - Warning displayed addslashes(): Passing null to parameter #1 ($string) of type string is deprecated - php8.1 only

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#31385]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

A warning is displayed on Shopping cart page

`
Unknown error on line 65 in file myshop/var/cache/dev/smarty/compile/03/a0/22/03a0227187fd3a8b111c0eccbf2f8ba30db4d248_0.file.kpi.tpl.php
[8192] addslashes(): Passing null to parameter #1 ($string) of type string is deprecated
`
<img width="1440" alt="Screenshot 2023-02-15 at 09 45 57" src="https://user-images.githubusercontent.com/16019289/219051448-6935366b-190f-4ffa-a566-e0427d4acb94.png">

https://user-images.githubusercontent.com/16019289/219051008-3ac63694-ef46-400c-9786-7dae8e4d2e37.mov

### Expected behavior

No warning should be displayed

### Steps to reproduce

1. Go to BO > Orders > Shopping carts
2. View 1 order > Go back to Shopping carts page
3. See error

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

Only in php8.1

**Comment by HanaRebaiQA** [comment]
Hello @florine2623 

I was able to reproduce your issue on PS8.1.0_beta with only php8.1. 

**PS8.1.0_beta : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/219404954-8cf7d63d-cc02-41ad-afb2-7241484b1205.png)


**PS8.0.1 : OK** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/219405536-fdeefae9-c0b8-4559-a7fe-d896e5b31b5f.png)


Indeed, it's a regression on 8.1.0

I'll add this to the debug backlog so that it's fixed.

Thank You!

**Comment by MatShir** [comment]
Very strange I don't reproduce :/
we will see if the devs can reproduce it 🤷‍♂️

**Comment by HanaRebaiQA** [comment]
@MatShir It's only with PHP 8.1.

**Comment by MatShir** [comment]
You are right ! thanks @HanaRebaiQA for the quick feedback

**Comment by HanaRebaiQA** [comment]
You are welcome @MatShir :)

**Comment by BenTen** [comment]
> @MatShir It's only with PHP 8.1.

Does it mean PS 8 is not yet fully compatible with php 8.1? Do we need to use php 8.0 on our project to limit error?

**Comment by MatShir** [comment]
PS 8 is compatible PHP 8.1 for sure. I understand the warning can be concerning but it doesn't affect critically the software. It's one of the few that I know of.

**Comment by MatShir** [comment]
It is our recommended version -> https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/
If you find issues, let me know ;)

**Comment by marcos-ba** [comment]
Same warning is displayed on Shopping cart page. PHP 8.1
![warning cart](https://github.com/PrestaShop/PrestaShop/assets/37938630/d0c51b27-5f73-4223-b27d-02f135426240)

**Comment by Hlavtox** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/31153
