### ISSUE TITLE
BO - A bad display of the date/time in the Customer service when creating orders 

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#31380]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

A bad display of the date/time in the Customer service when creating orders 

**8.1.0_beta_build1 : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/219042880-475a99e7-3e57-4e8c-b3bd-7c2043f70ebf.png)

**8.0.x : OK** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/219042918-f9e81b91-4843-4f3b-83b8-39de71c61d02.png)

### Expected behavior

The date/time should be well displayed in the correct position

### Steps to reproduce

1. Install the 8.1.0_beta_build1 
2. BO > SELL > Customers > Add a new Customer
3. FO > Create an order with the created customer
4. Come back to BO > SELL > Orders > Change the status of the created order to any other status (eg: Delivered)
5. Go to FO > Contact US > Fill in the information of the Customer Service with the mail of created customer and the reference of his order
6. Click on Send
7. Go to BO > SELL > Customer Service > Click on to View the sent customer service
8. Go to Orders and messages timeline section > see error

### PrestaShop version(s) where the bug happened

8.0.1_beta_build1

### PHP version(s) where the bug happened

7.4

**Comment by MatShir** [comment]
Wait until this bug to be fixed [#31377](https://github.com/PrestaShop/PrestaShop/issues/31377)

**Comment by mflasquin** [comment]
Hi @HanaRebaiQA I can't reproduce the issue on 8.1.x, maybe it will be ok on the future build ?

**Comment by HanaRebaiQA** [comment]
Thanks @mflasquin 
We will check it again if it's fixed and come back to you.
ping our dear @hibatallahAouadni : Could you please check it ?

Thank You!

**Comment by florine2623** [comment]
This is fixed on `8.0.x`, 8`.1.x` and `develop` branches.
