### ISSUE TITLE
BO - The experimental features of the Product V2 is not correct after an upgrade from 8.0.1 to 8.1.0

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#31381]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The experimental features of the **Product V2** is not correct after an upgrade from 8.0.1 to 8.1.0

https://user-images.githubusercontent.com/92912932/219045907-5428262b-fa5b-4c08-ac33-b04fe3b33da3.mp4

The problem is that because on the 8.0.1, the FF for the PPV2 contains 2 options for the single and multi store. 
But, on 8.1.0_beta_build1 fresh install or develop, the behavior is updated to only one option "New product page".  

**8.1.0_beta_build1 : OK** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/219045346-a920c6af-e131-4ff3-ba23-e66f904980e5.png)

**Upgrade from 8.0.1 to 8.1.0 : NOK** (before and After the upgrade) : NOK :x: 

![image](https://user-images.githubusercontent.com/92912932/219045486-dce57c1a-440a-40e9-80f1-ac29d649debb.png)

**Possibility to enable both options after the upgrade to 8.1.0_beta : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/219045579-b4eb2063-e290-4466-8f0d-a1fbf8aa212c.png)

### Expected behavior

The FF of the product V2 is well displayed after the upgrade from 8.0.1 to 8.1.0

Normally this should be fixed, following the upgrade in 8.1.0_beta it is the "New product page" option that should be displayed.

### Steps to reproduce

1. Install 8.0.1
2. BO > Catalog > Products > Create any product type
3. Enable multistore and add new shops
4. BO > Advances parameters > Experimental Features > Enable page product V2 with multi-store
5. Install the autoupgrade module via dev branch
6. git clone git@github.com:PrestaShop/autoupgrade.git
7. cd autoupgrade > composer install
8. Configure autoupgrade module
9. Use the local archive and choose the 8.1.0_beta.zip and put the 8.1.0 as a version
10. Click to Upgrade
11. Connect to 8.1.0_beta shop
12. Go to BO > Advances parameters > Experimental Features > see that `New product page - Multi store` option is enabled
13. Go to Catalog > Products > edit the created product / Or any other demo product
14. See error > **The product V1 is displayed instead of Product V2** !!
15. When Go to BO > Advances parameters > Experimental Features > Enable `New product page - Signle store` **(And the multistore is enabled!)**
16. Come back Go to Catalog > Products > edit the created product / Or any other demo product
17. See result > The product V2 is displayed 

### PrestaShop version(s) where the bug happened

8.1.0_beta_build1

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

autoupgrade dev branch (next v4.16)

**Comment by florine2623** [comment]
Hello @HanaRebaiQA ,

I couldn't reproduce your issue as I have an error while following your step for the upgrade :
<img width="1434" alt="Screenshot 2023-02-16 at 16 24 36" src="https://user-images.githubusercontent.com/16019289/219410578-1a844cc7-4ff0-48e6-90dc-4b0a87b06e6b.png">

Some more details about the error :
```
[INTERNAL] /Users/fHea/Desktop/prestashop_8.0.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/DefinitionErrorExceptionPass.php line 54 - Symfony\Component\DependencyInjection\Exception\RuntimeException: You have requested a non-existent parameter "api_private_key". #0 /Users/fHea/Desktop/prestashop_8.0.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(83): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true) #1 /Users/fHea/Desktop/prestashop_8.0.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/DefinitionErrorExceptionPass.php(32): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, true) #2 /Users/fHea/Desktop/prestashop_8.0.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(47): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue(Array, true) #3 /Users/fHea/Desktop/prestashop_8.0.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(94): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #4 /Users/fHea/Desktop/prestashop_8.0.1/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(762): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #5 /Users/fHea/Desktop/prestashop_8.0.1/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(594): Symfony\Component\DependencyInjection\ContainerBuilder->compile() #6 /Users/fHea/Desktop/prestashop_8.0.1/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(136): Symfony\Component\HttpKernel\Kernel->initializeContainer() #7 /Users/fHea/Desktop/prestashop_8.0.1/app/AppKernel.php(87): Symfony\Component\HttpKernel\Kernel->boot() #8 /Users/fHea/Desktop/prestashop_8.0.1/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(76): AppKernel->boot() #9 /Users/fHea/Desktop/prestashop_8.0.1/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader80.php(44): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #10 /Users/fHea/Desktop/prestashop_8.0.1/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(87): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader80->initConstants() #11 /Users/fHea/Desktop/prestashop_8.0.1/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(42): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #12 /Users/fHea/Desktop/prestashop_8.0.1/admin467tkvnpyupnrjilxd1/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #13 {main}
```

ping @PrestaShop/qa-team ,
could someone try to reproduce this issue please ?

Thanks!

**Comment by AureRita** [comment]
Hi @HanaRebaiQA  ,

I reproduce the issue with PrestaShop version 8.1.0_beta and not with the version 8.0.1.as you can see 

[Untitled_ Feb 22, 2023 4_17 PM.webm](https://user-images.githubusercontent.com/100699445/220666965-0499a61c-2f5b-423b-8c08-d2d10275c2f0.webm)


 Nice catch ! It's a regression ! I'll add it to the patch backlog.

Please be aware that some issues might take a very long time to be resolved.

Thank you

**Comment by WahbiPS** [comment]
is this still blocked @AureRita & @HanaRebaiQA ?

**Comment by MatShir** [comment]
Still blocked bc the module upgrade is not ready yet !

**Comment by MatShir** [comment]
oups
