### ISSUE TITLE
The 1-click upgrade module is up-to-date (your current version is v1.6.8)   Update - Download  X

### ISSUE THREAD

**Issue by frevab** [PrestaShop/PrestaShop#31393]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I want to upgrade my shop from v. 1.5.4.1 to 1.7 or even 8.0
The module that was in my bo was outdated and gave a red X on the module version.
So I installed the latest version from GitHub and still has this contradictory error: it says the module is up-to-date but still shows a red X. It shows the links to "Update - Download"  But the update link does not update the module in the bo (probably because it is up-to-date) and the download link gets you to the addons page of PS but not download button.
HELP.
![afbeelding](https://user-images.githubusercontent.com/53129699/219215029-204a7e50-67d7-4168-92c0-2e866af1a2af.png)

### Expected behavior

the obvious, if it says the module version is up-to-date to give a green go-ahead or give the reason why it stays red.

### Steps to reproduce

-

### PrestaShop version(s) where the bug happened

1.5.4.1

### PHP version(s) where the bug happened

5.6.40

### If your bug is related to a module, specify its name and its version

1-click Upgrade 4.14.2

**Comment by hibatallahAouadni** [comment]
Hello @frevab 

PrestaShop 1.5 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).

Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you
