### ISSUE TITLE
PPV2 - An exception is displayed when adding a set of combination values of feature

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#31402]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

An exception is displayed when adding a new set of combination values of features on product page V2

**PS8.1.0_beta with product V2 : NOK** :x: 

`An unexpected error occurred. [PrestaShop\PrestaShop\Core\Domain\Product\FeatureValue\Exception\InvalidProductFeatureValuesFormatException code 0]: Feature value missing, specify a feature_value_id or new custom_values`

![image](https://user-images.githubusercontent.com/92912932/219383297-b3983fda-9aa8-4670-88f6-8971fe7ef010.png)

https://user-images.githubusercontent.com/92912932/219388546-76250f68-b96f-4fb4-b925-72d5b58994ee.mp4

**PS8.1.0_beta with product V1 : OK** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/219383519-f4dd5f9b-61e2-4fd7-944c-bfeb7fefd05b.png)

**PS8.0.1 : NOK** :x:

![image](https://user-images.githubusercontent.com/92912932/219383393-7728c150-051f-42ef-9940-2855486589f7.png)
 
It's a regression on 8.0.1!

### Expected behavior

No exception is displayed!

### Steps to reproduce

1. Go to BO > Advanced parameters > New & Experimental features > Enable New product page
2. Go to BO > Catalog > Products > Create a product V2
3. Click on `Add a feature`
4. Set these values : 

> Feature: Choose a feature / Pre-defined value : Choose a feature / OR Customized value : empty
> Feature: Composition (for example) / Pre-defined value : Choose a feature / OR Customized value : empty
> Feature: Property (for example) / Pre-defined value : Choose a feature / OR Customized value : any value (eg:12)

5. Click on Save
6. See error of Details ==> This value is not valid
7. Click again on `Pre-defined value` and choose again `Choose a value `
8. Change the `OR Customized value` to any other value
9. Click on Save
10. See error >> The exception is displayed!

### PrestaShop version(s) where the bug happened

8.1.0_beta_build1, 8.0.1

### PHP version(s) where the bug happened

7.4

**Comment by HanaRebaiQA** [comment]
It's related to this issue #31401 but not the same.

**Comment by florine2623** [comment]
Hello @HanaRebaiQA ,

I couldn't reproduce your issue, following your steps, here's what I have :
<img width="1437" alt="Screenshot 2023-02-16 at 16 12 04" src="https://user-images.githubusercontent.com/16019289/219406259-d4b68e00-d270-4b2c-80f2-feac33432e2d.png">

I don not have an exception, just a warning message.

ping @PrestaShop/qa-team could someone try to reproduce the issue please ?
Thanks!
