### ISSUE TITLE
Prestashop Upgrade from 1.7.6.3 to 1.7.8.8

### ISSUE THREAD

**Issue by Ilirium23** [PrestaShop/PrestaShop#31403]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I try to Upgarde my e-shop from Prestashop 1.7.6.3 to Prestashop 1.7.8.8 and it fails. I get message "Error when trying to add /var/www/vhosts/mysite.gr/httpdocs/.cagefs/opt/alt/php71/link/conf to archive .cagefs/opt/alt/php71/link/conf."
PHP version: 7.3.33

Any help would be appreciated.

### Steps to reproduce

1. install 1.7.6.3
2. BO>Module Catalog
3. search the module 1-Click autoupgrade
4. install it
5. BO>Shop Parameters>General>Maintenance
6. disable the option "Enable store"
7. save
8. BO>Module Manager> 1-Click autoupgrade
9. click on configure
10. choose 1.7.8.8
11. upgrade
12. see error > upgrade fails displaying this error "Error when trying to add /var/www/vhosts/mysite.gr/httpdocs/.cagefs/opt/alt/php71/link/conf to archive .cagefs/opt/alt/php71/link/conf."

### PrestaShop version(s) where the bug happened

1.7.6.3 to 1.7.8.8

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

1-Click autoupgrade v4.15

**Comment by florine2623** [comment]
Hello @Ilirium23 ,

Are you using the autoupgrade module ?
If yes, which version ?

Waiting for your feedback.
Thanks!

**Comment by Ilirium23** [comment]
Dear @florine2623 thank you for your reply. 
Yes I use 1-Click Upgrade Version 4.15.0 .

**Comment by Ilirium23** [comment]
> Hello @Ilirium23 ,
> 
> Are you using the autoupgrade module ? If yes, which version ?
> 
> Waiting for your feedback. Thanks!

Dear @florine2623 thank you for your reply.
Yes I use 1-Click Upgrade Version 4.15.0 .

**Comment by hibatallahAouadni** [comment]
Hello @Ilirium23 

I just update your steps to reproduce in the issue description.
Could you please check it and see if I miss something 🙏 
Waiting for your feedback.

Thanks!

**Comment by Ilirium23** [comment]
@hibatallahAouadni everything is ok...thank you...

**Comment by AureRita** [comment]
Hi @Ilirium23 

Thank you for your details, I tried to reproduce your issue but I find another one as you can see here : 

[Untitled_ Feb 22, 2023 12_23 PM.webm](https://user-images.githubusercontent.com/100699445/220635909-4d32e988-0752-4476-9779-2188b12f0c62.webm)

Can you give us a video or a screenshot to show us your errors message ?

**Comment by Ilirium23** [comment]
@AureRita Finally I solved the problem. I set Back Up options to No.
<img width="1433" alt="Στιγμιότυπο οθόνης 2023-02-23, 8 25 08 μμ" src="https://user-images.githubusercontent.com/125577936/220998141-9409e5c5-6926-4ba7-b1a7-75c368510dbe.png">
