### ISSUE TITLE
Problems with "1click upgrade"

### ISSUE THREAD

**Issue by joanasca** [PrestaShop/PrestaShop#31408]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After running the free "1-click upgrade" module to upgrade my prestashop, my store has stopped working. Fortunately I have been able to access the back office, but I do not have access to the start of the store in the front office. Nor can I access the prestashop marketplace from the backoffice, I get the following error: "Attempted to load class "ModuleCatalogController" from namespace "PrestaShop\Module\Mbo\Controller\Admin". Did you forget a "use" statement for another namespace?

[Symfony\Component\Debug\Exception\ClassNotFoundException 0]"

### Steps to reproduce

I run the 1-click upgrade module
At the end, the store stops working

### PrestaShop version(s) where the bug happened

1.7.7.2

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

1-click upgrade

**Comment by sallemiines** [comment]
Hello @joanasca 

I couldn't reproduce the issue with the information provided. They are not clear enough ! 
could you please provide more infos ( screenrecord/screenshots / the module version ... ) 

Thank you !

**Comment by djoelleuch** [comment]
Hello @joanasca 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thank you

**Comment by djoelleuch** [comment]
Hello @joanasca 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thank you
