### ISSUE TITLE
BO - The bulk action shouldn't be displayed on the shopping carts page when there is no shopping carts with No ordered status

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#31406]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The bulk action shouldn't be displayed on the shopping carts page when there is no shopping carts with No ordered status

**PS 8.1.0_beta : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/219415286-c0408777-211c-444f-b992-2758176ac87a.png)

https://user-images.githubusercontent.com/92912932/219415562-a4597e6f-5dae-49d7-b4db-c405c8705d11.mp4

**PS 8.0.1 : OK** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/219415311-e0367f1d-6e7d-425c-b5d5-1e677bef8a60.png)

[Untitled_ Feb 16, 2023 4_20 PM (1).webm](https://user-images.githubusercontent.com/92912932/219415953-cde94d58-506f-4b3a-b9b4-2a5662670a11.webm)

So, it's a regression on 8.1.0_beta !

### Expected behavior

The bulk action should not be displayed!

### Steps to reproduce

1. Use 8.1.0_beta
2. Go to BO > Orders > Shopping carts
3. See error >> Check that there is a bulk action displayed
4. Click on `Delete selected`
5. See error >> An error message is displayed! `You must select at least one element to delete.`

![image](https://user-images.githubusercontent.com/92912932/219417037-f1268f0e-7bb2-46a6-a983-6dc523b22633.png)

### PrestaShop version(s) where the bug happened

8.1.0_beta_build1

### PHP version(s) where the bug happened

8.1

**Comment by MatShir** [comment]
I think it is the normal behavior :) 
To double check

**Comment by MatShir** [comment]
The bulk is only displayed when there is an abandoned cart

**Comment by HanaRebaiQA** [comment]
Thanks @MatShir for your feedback. So we can move it to Ready again.

**Comment by MatShir** [comment]
So we can close the issue then
