### ISSUE TITLE
Error with tmp file when sending email, after order, test etc

### ISSUE THREAD

**Issue by Euszek** [PrestaShop/PrestaShop#31409]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Geting Error when try to send email of confirmation order etc.

Błąd: proszę sprawdzić konfigurację    (Error, please check configuration)

Failed to create cache directory /tmp/3b6da03******************

I was talking with my hosting, they check everything, and from hosting side everything is ok.
To 13.02.2023 everythink work properly. After 14.02.2023 after order email should be send automaticaly, but i have got this error.

Didnt change anythink at 13.02, dont have idea what i can check. Settings of email smtp is ok. Problem is with tmp file. 

### Steps to reproduce

1. visit email settings in BO
2. Tring to send test email
3. get this error

1. Make order
2. didnt get email confirmation

### PrestaShop version(s) where the bug happened

1,7,8,3

### PHP version(s) where the bug happened

7.4.33

**Comment by sallemiines** [comment]
Hello @Euszek 

I didn't manage to reproduce the issue with  `PS1787 , PS801 and PS810`  see the attached screen record below:

https://user-images.githubusercontent.com/31663369/219667977-a7d65b1e-f547-4b72-a9b5-a922243c5237.mp4

Please check your configuration ! 
Thank you !
