### ISSUE TITLE
Upload Images via CURL in multistore with nginx

### ISSUE THREAD

**Issue by nbgroup-git** [PrestaShop/PrestaShop#31404]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If I upload a image to a product via CURL in multistore returns error 400.

In the same server, same configuration in a not multistore prestashop image uploads ok

$ch = curl_init();
        curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type:multipart/form-data', 'Expect:'));
        curl_setopt($ch, CURLOPT_URL, $urlImage);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_USERPWD, $key . ':');
        curl_setopt($ch, CURLOPT_POSTFIELDS, array('image' => new CurlFile($image_path) ));
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        $result = curl_exec($ch);

### Steps to reproduce

- upload an image via curl (code in the forst post) with a multistore environment calling an external PHP file.
- In non multistore prestashop curl return 200 ok and image is uploaded
- In multistore prestashop curl returns 400 and image is not uploaded.

### PrestaShop version(s) where the bug happened

1.7.7.7

### PHP version(s) where the bug happened

NGINX 1.14 and PHP 7.2

**Comment by florine2623** [comment]
Hello @nbgroup-git ,

Could you specify the exact steps to reproduce the issue please ?

Waiting for your feedback.
Thanks!

**Comment by nbgroup-git** [comment]
The steps are:
upload an image via curl (code in the forst post) with a multistore environment calling an external PHP file. 
In non multistore prestashop curl return 200 ok and image is uploaded
In multistore prestashop curl returns 400 and image is not uploaded.

**Comment by hibatallahAouadni** [comment]
Hello @nbgroup-git 

Thanks for reporting the issue!
Ping @PrestaShop/prestashop-core-developers someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by hibatallahAouadni** [comment]
Hello @nbgroup-git 

Do you still encounter the issue with 8.1.x? Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @nbgroup-git 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
