### ISSUE TITLE
Autoupgrade: Error during database upgrade

### ISSUE THREAD

**Issue by PR0SAT** [PrestaShop/PrestaShop#31413]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi DEVs,

Tried to update my Prestashop 1.7.8.6 to 1.7.8.8 using the autoupgrade 4.15.0 module.
The PHP: 7.4.33, MySQL: 8.0.31 on Apache/N-G-I-N-X-htaccess-support.
Several attempts even using the cli method resulted in database error.
The shop works, but not sure what can happen in the future and how many DB changes were left to complete.
The update process suggests a backup restore at the end, canceled it and was able to browse the FRONT and BO.
My errors look like this:
`Error during database upgrade. You may need to restore your database.
Error upgrading Doctrine schema`
More detailed explanation says what went wrong:
`09:09:27 ERROR [console] Error thrown while running command "prestashop:schema:update-without-foreign --env=prod". Message: "The table with name 'DB.ps_attribute' already exists." ["exception" => Doctrine\DBAL\Schema\SchemaException { …},"command" => "prestashop:schema:update-without-foreign --env=prod","message" => "The table with name 'DB.ps_attribute' already exists."]
In SchemaException.php line 108:
The table with name 'DB.ps_attribute' already exists.
prestashop:schema:update-without-foreign [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--id_shop [ID_SHOP]] [--id_shop_group [ID_SHOP_GROUP]] [--] `

Hope you can point to resolve the issue or tell that it is save to use the updated shop even with this error. Googled the message but no results.

Thx for any help.

### Expected behavior

Installation finished without errors

### Steps to reproduce

1. Running the specified versions of sotware
2. Try to upgrade
3. Finish to complete

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

autoupgrade 4.15.0

**Comment by hibatallahAouadni** [comment]
Hello @PR0SAT 

I didn't manage to reproduce the issue with the provided info.
Did you disable all non-native modules and your overrides before the upgrade?
Please check and feedback.

Thanks!

**Comment by PR0SAT** [comment]
@hibatallahAouadni  Sure thing, all disabled, the modules and the overrides, don't understand the message.
I noticed you updated the autoupgrade module and picked up the new version. The error changed to a diffrent table:
`Updating database schema...
14:07:55 ERROR [console] Error thrown while running command "prestashop:schema:update-without-foreign --env=prod". Message: "There is no column with name 'nleft' on table 'rc_category'." ["exception" => Doctrine\DBAL\Schema\SchemaException { …},"command" => "prestashop:schema:update-without-foreign --env=prod","message" => "There is no column with name 'nleft' on table 'rc_category'."]
In SchemaException.php line 82:
There is no column with name 'nleft' on table 'rc_category'.
prestashop:schema:update-without-foreign [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--id_shop [ID_SHOP]] [--id_shop_group [ID_SHOP_GROUP]] [--] `
The prefix is also strange, never used the "rc_", always sticked with "ps_".
EDIT: Naah, you didn't, I forged the module 2'nd time, this time I used composer2

**Comment by PR0SAT** [comment]
The /var/log/prod.log message is:
`[2023-02-21 15:19:33] console.ERROR: Error thrown while running command "prestashop:schema:update-without-foreign --env=prod". Message: "There is no column with name 'nleft' on table 'rc_category'." {"exception":"[object] (Doctrine\\DBAL\\Schema\\SchemaException(code: 30): There is no column with name 'nleft' on table 'rc_category'. at /usr/home/name/domains/some.host.com/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaException.php:82)","command":"prestashop:schema:update-without-foreign --env=prod","message":"There is no column with name 'nleft' on table 'rc_category'."} []
[2023-02-21 15:19:33] console.DEBUG: Command "prestashop:schema:update-without-foreign --env=prod" exited with code "30" {"command":"prestashop:schema:update-without-foreign --env=prod","code":30} []`

**Comment by florine2623** [comment]
Hello @PR0SAT ,

About your error log, you can check in Advanced Parameters > Information the prefix of your tables :
<img width="591" alt="Screenshot 2023-02-21 at 17 54 21" src="https://user-images.githubusercontent.com/16019289/220409729-b0af4a3e-a4db-474a-af4f-7804331f0244.png">

You can also check in your database directly why you have these table prefix.

**Comment by PR0SAT** [comment]
I know my table prefix, I look at them every day ;) why is the prestashop:schema seeing otherwise is a mystery

**Comment by hibatallahAouadni** [comment]
Hello @PR0SAT 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug 😞 🙏 We will close this issue.

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thanks!
