### ISSUE TITLE
PPV2 - The number of filter is not well displayed when filtering more than one in a product with combinations 

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#31417]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The number of filters is not well displayed when filtering more than one in a product with combinations 

**PS8.1.0_beta_build1 : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/219609553-0ad93eb5-f311-4c72-86e6-af2e2055d694.png)

**PS8.1.0_beta_build2 : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/219609619-2ced5f2f-2eac-44a8-89ac-50489544e53e.png)

https://user-images.githubusercontent.com/92912932/219618605-947c58c0-701e-4202-93e0-d58e25d27897.mp4

**PS8.0.1 : OK** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/219609673-897adbfc-6f86-48b4-bddf-95e52089f834.png)

https://user-images.githubusercontent.com/92912932/219619437-e880c75a-a1ca-47c1-b738-f3ac73338342.mp4

So, it's a regression on **8.1.0_beta**!

### Expected behavior

The number of filters is well displayed

### Steps to reproduce

1. Use the 8.1.0_beta
2. Go to BO > Advanced parameters > New & Experimental features > Enable New product page
3. Go to BO > Catalog > Products V2 > Create a product with combinations
4. Add new combinations (eg: more than 2 combinations) for the product 
5. Click on Save
6. On the `Manage product combinations` section > Use Filter by > Choose the first filter
7. Click on the second filter 
8. See error >> The filter number is not well displayed
9. Click on the third/fourth.. filter 
8. See error >> The filter number is not well displayed

### PrestaShop version(s) where the bug happened

8.1.0_beta

### PHP version(s) where the bug happened

8.1

**Comment by zuk3975** [comment]
will be solved by this https://github.com/PrestaShop/PrestaShop/pull/30769
