### ISSUE TITLE
Faceted search module causes brand to be missing on some product miniatures

### ISSUE THREAD

**Issue by pipalot** [PrestaShop/PrestaShop#31422]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The brand name doesn't always appear on the product miniatures when browsing in a list of products in a category.  This problem seems to occur for some products, not all products.  In some categories, the brand is missing from most of the product miniatures, in other categories it is missing for only a small number of product miniatures.  

So there are two ways to ensure that the brand name appears on the product miniatures.  Either 1) disable Faceted Search Module, or 2) add the product to the cart.

I contacted the developer of the Warehouse theme (IQIT).  They told me that the issue is being caused by the Faceted Search Module and that I needed to report it here.

I found another user having a similar problem, however I checked the templates mentioned in the solution and found that they already contained the correct code that was suggested:
https://www.prestashop.com/forums/topic/1037397-solved-brands-not-displaying-on-products-miniatures/

I am also currently unable to upgrade Prestashop from 1.7.8.7 to version 8, because I get html error 500 when I click to configure 1-Click upgrade.  I also get html error 500 when I try to open the Information page from Advanced Parameters in the back office.  I doubt that these issues are related to the missing brand on some product miniatures, but I mention them just for full disclosure in case you think that it is related.

![Bug - Brand is Missing](https://user-images.githubusercontent.com/67150212/219663409-bc456772-b233-4b48-af66-bd9af560c4eb.jpg)

### Expected behavior

Brand name should appear on product miniatures, without having to disable Faceted Search Module or add a product to the cart.

### Steps to reproduce

1.  Assign a brand to products in Prestashop back office.
2.  In Back Office go to Iqit Theme Editor (using Warehouse Theme), Content Pages, Product Lists/Carousel, scroll down and choose to show Product brand and click Save.  This is meant to show the brand names on the product miniatures.
3.  Ensure that the Faceted Search Module is enabled and that it is configured to with Brands as one of the filters.
4.  In front office, go into the menu and choose to view a single category of products.  You will see the brand does not appear on all of the product miniatures in the product list, even though the products have been assigned to a brand in the back office.
5.  Click a product that has a missing brand name on its miniature.  You can see the brand name does appear on the product page, so it is only missing from the product miniature in the list of products when viewing a category of products.  
6.  Either add the product to cart the cart, or disable the Faceted Search module.
7.  Continue shopping and go back to viewing the list of products in the same category.  The product miniature now displays the brand name which was previously missing.
8.  Remove the product from the cart or enable the Faceted search module again and the brand name will go missing again on the product miniature.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_facetedsearch v3.11.1 (Prestashop Faceted Search Module)

**Comment by hibatallahAouadni** [comment]
Hello @pipalot 

I can not reproduce the issue cause I use CLASSIC 😞 so could you please provide a theme to help me reproducing the issue 🙏 to check if the issue is related to FacetedSearch or to your theme 😉 
Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @pipalot 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by pipalot** [comment]
Hi @hibatallahAouadni,

Sorry for not replying sooner.

I tested in the Warehouse Theme and the coders of that theme have told me that the problem is in the Faceted Search module, not in their theme.

Are you saying that you want me to send you a copy of the Warehouse Theme?  I don't think I'm able to do that because it is a paid product.  I have contacted the theme developer again to ask if there is anything they can do to liaise with you directly, because I seem to be stuck in the middle with neither side of developers being able to progress fully currently.

Are you able to keep this ticket open please instead of having it closed?

Kind regards,
Gavin
