### ISSUE TITLE
.php-cs-fixer.dist.php on zip release doesn't work

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#31427]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

- install prestashop from the zip release
- launch php-cs-fixer fix 
- see the error  The "PATH/tests" directory does not exist.

### Expected behavior

no error: 
The build script should remove the tests directory in line 9 of .php-cs-fixer.dist.php 

### Steps to reproduce

- install prestashop from the zip release
- launch php-cs-fixer fix on a file
- see the error  The "PATH/tests" directory does not exist.

### PrestaShop version(s) where the bug happened

8.0, 8.1

### PHP version(s) where the bug happened

all

**Comment by sallemiines** [comment]
Hello @jf-viguier 

Could you please provide us a screen record for the steps that you set ?
 how can we `launch php-cs-fixer fix on a file` ? 
 
Thank you !

**Comment by jf-viguier** [comment]
- Go to PrestaShop project root in command line
- launch > php-cs-fixer fix thephpfile.php

To install it : https://github.com/PHP-CS-Fixer/PHP-CS-Fixer#installation

**Comment by florine2623** [comment]
Hello @jf-viguier ,

After installing PHP-CS-Fixer, I have an error :

> command not found: php-cs-fixer

Can you specify which file should be targeted when launching this command ?
I tested with `php-cs-fixer fix index.php`

**Comment by jf-viguier** [comment]
@florine2623 
install php-cs-fixer : https://github.com/PHP-CS-Fixer/PHP-CS-Fixer#installation
And launch it from the folder you install it, it's certainly not in your path.

By example : 
./tools/php-cs-fixer/vendor/bin/php-cs-fixer fix thefile

**Comment by AureRita** [comment]
Hi @jf-viguier 

Thank for your details, I reproduce your issue with PrestaShop version 8.0.0 as you can see 
![image](https://user-images.githubusercontent.com/100699445/220646206-070bc37a-cca7-44a2-872f-366ae6150c89.png)

I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. 

Thanks

**Comment by matks** [comment]
[PHP CS Fixer](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer) is a tool we use in the CI of the project, it is used to help writing the code correctly for the software. It is useful to work on the source code.

The ZIP release that we deliver in releases, such as this one https://github.com/PrestaShop/PrestaShop/releases/tag/8.0.4 should not contain tools meant for working on the source code.

I think the expected behavior should be: the ZIP should NOT contain the .php-cs-fixer.dist.php https://github.com/PrestaShop/PrestaShop/blob/develop/.php-cs-fixer.dist.php file. This file should be removed when we build the ZIP.

To perform the removal, one must modify the ZIP creator tool and update this list https://github.com/PrestaShop/PrestaShop/blob/develop/tools/build/Library/ReleaseCreator.php#L74 . This list contains files that the Creator removes.

**Comment by jf-viguier** [comment]
@matks PHP CS Fixer can be useful for module developers that doesn't need develop version of prestashop.

**Comment by jf-viguier** [comment]
@matks BTW, I've posted a PR for the suggested removal, thanks.

**Comment by matks** [comment]
> @matks PHP CS Fixer can be useful for module developers that doesn't need develop version of prestashop.

But we dont want to force module developers to do it 😄 . This PHP CS Fixer configuration file is meant to enforce coding style on the Core, module developers are free to use whatever style they want ^^

**Comment by polrue** [comment]
Modules validator at least seem to be requiring the CS-Fixer to be applied.

I'm also facing the same issues /tests folder does not exist.

In my case after some attempts I just created the "tests" folder inside the PrestaShop root and the fixer started to work.

I think the documentation is quite poor on this, hard to work with it the first time and not friendly at all.

After performing it I've seen that none of the module files have been reviewed, only the core ones.

Several things needs to be reviewed here.
