### ISSUE TITLE
BO - WS - Text helper is confusing

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#31423]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The grey text helper should not mention "at least" as the length of the webservice can only be 32 characters.

<img width="1100" alt="Screenshot 2023-02-14 at 17 57 31" src="https://user-images.githubusercontent.com/16019289/219675222-cd0e7b98-3be8-465a-80c0-cf9d12c099c1.png">

@l-delin what do you think ? ^^

### Expected behavior

The helptext displays "The key must be 32 characters long."
 
### Steps to reproduce

1. Go to BO > Advanced Parameters > Webservices
2. Add a new webservice key
3. See text helper

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1

**Comment by sallemiines** [comment]
Hello @florine2623 

I reproduce your issue with `PS 800 , PS 801 , and PS 810 `

![Webservice-•-800](https://user-images.githubusercontent.com/31663369/219677601-fde12dc6-ad5b-4db9-8708-ac532b308165.png)

But it's OK with `PS 1788 `

![Webservice-•-1787](https://user-images.githubusercontent.com/31663369/219682799-7ddca4f8-f1b1-4f42-ab01-a23aaa8a134a.png)



Thank you !

**Comment by l-delin** [comment]
Hello @florine2623 :-) I completely agree with your suggestion. If the 32-character limit is a restriction, what do you think of `"The key must be 32 characters long."` ?
