### ISSUE TITLE
the mudel stup work good in my weebsite

### ISSUE THREAD

**Issue by shaiohana** [PrestaShop/PrestaShop#31438]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello Team,

I have Wishlist block Module, when I updated to the last version it stops to work, and I don't have wishlist list on the website, and it needs to work can you help me please? My website version 1.7.8
My website : https://shopgold.co.il/he/
PrestaShop version: 1.7.8.7
Module version : v2.1.2
Shop URL: http://shopgold.co.il/
Shop path: /home/admin/domains/shopgold.co.il/public_html
shaiohana83@gmail.com my account PrestaShop

Could you please get back to me to help me resolve the problem?

Thank you for your help.

### Expected behavior

Hello Team,

I have Wishlist block Module, when I updated to the last version it stops to work, and I don't have wishlist list on the website, and it needs to work can you help me please? My website version 1.7.8
My website : https://shopgold.co.il/he/
PrestaShop version: 1.7.8.7
Module version : v2.1.2
Shop URL: http://shopgold.co.il/
Shop path: /home/admin/domains/shopgold.co.il/public_html
shaiohana83@gmail.com my account PrestaShop

Could you please get back to me to help me resolve the problem?

Thank you for your help.

### Steps to reproduce

rthgdfgbtrerwbrg

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

Module version : v2.1.2

**Comment by shaiohana** [comment]
[Wishlist block Module](https://addons.prestashop.com/en/undownloadable/9131-wishlist-block.html#overview_description)

this the mudel that not work good in my weebsite

**Comment by sallemiines** [comment]
Hello @shaiohana ,

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template and provide clear and concise steps to reproduce the bug**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
