### ISSUE TITLE
Problem with Addons Payment https://addons.prestashop.com

### ISSUE THREAD

**Issue by pdkey** [PrestaShop/PrestaShop#31430]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

There is a problem in the payment process when purchasing addons.
After entering the credit card, an error is displayed with the zip code.
Although the credit card was used for all payments in the last months.
Chat Support refers that another credit card should be used.
The result: 2 times the amount for the module was reserved on the credit card.

Chat Support now again recommends to use another card.
How much amount should be reserved for Prestashop?

There is no phone nor chat help. The amounts are reserved on the credit card.

Please check the new checkout in Addons store.

### Steps to reproduce

Pay a Addon on https://addons.prestashop.com/de

### PrestaShop version(s) where the bug happened

PS1788

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

https://addons.prestashop.com/de

**Comment by hibatallahAouadni** [comment]
Hello @pdkey 

It seems that your issue is not a PrestaShop core bug.
Please contact support team on Addons

We will close this issue.

Thanks!
