### ISSUE TITLE
modulo 1click . zip no funciona

### ISSUE THREAD

**Issue by taniaruiz93** [PrestaShop/PrestaShop#31432]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Me he descargado el .zip para instalar el modulo 1-click en mi prestashop y me reporta un error de que no se puede instalar por que no es valido .zip.

### Steps to reproduce

1. Me he descargado de git el modulo en .zip
2. He ido a prestashop y lo he subido
3. Error de subida... no es compatible el archivo zip.

### PrestaShop version(s) where the bug happened

1.7.6.4

### PHP version(s) where the bug happened

7.2

**Comment by sallemiines** [comment]
Hello @taniaruiz93 ,

Please send your request in English. English is the norm on GitHub.

Thank you
