### ISSUE TITLE
BO: after two/three clicks it logs me out

### ISSUE THREAD

**Issue by JavierLinaresMorales** [PrestaShop/PrestaShop#31444]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Desde el backoffice, cuando se hace click en una opción del menu lateral, cierra la sesion. 

### Steps to reproduce

1. Vaya a backoffice
2. Haga click en cualquier opcion del menú lateral

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

7.4.33

**Comment by sallemiines** [comment]
Hello @JavierLinaresMorales  ,

Please send your request in English. English is the norm on GitHub.

Thank you

**Comment by JavierLinaresMorales** [comment]
Good morning, I installed Prestashop 8.0.1 with PHP: 7.4.33. When I enter the backoffice and try to access the side menu options, sometimes in two and sometimes in three clicks it logs me out.

**Comment by hibatallahAouadni** [comment]
Hello @JavierLinaresMorales 

Thanks for your feedback.
You need to check this option when you log in 😉 
Closing the issue as there's no bug 🙏 

Thanks!
