### ISSUE TITLE
Module psxmarketingwithgoogle (Marketing with Google), weight, price, configuration problems

### ISSUE THREAD

**Issue by PeNov** [PrestaShop/PrestaShop#31459]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,
There are below listed problems:
**1)	Campaign configuration,**

Marketing/Google/Campaign/Launch campaign

The is not possible change product filters.
Every time is enabled: Include all synced products and is not possible switch to radio button Select products using product partition filters.
![image](https://user-images.githubusercontent.com/38213520/220117391-f7b81f51-fda8-4328-9606-37e07a321335.png)

**2) Products are declined by Google because weight is missing**. 
Each declined case is with product which contain combinations. Weight was already filed in the administration (in past). Problem usually solving opening problematic combination and again save in the administration. But not every time.

**3)	Product with sale**
**_Example 1_**, product contain two special prices, one is outdated:
Special prices:
3264	--	All combination, All currency, All ???, All group, All customers,--,	- 35 %,	No limit 	1
3094	--	All combination, All currency, All ???, All group, All customers,--,	- 15 %	From 2022-11-24 00:00:00 to 2022-11-28 00:00:00	1

Product price is 1817,-
Correct price after -35% is 1181.05,-
But sale price transferred to the Google by API (feed) is 1544,- (this is value outdated sale price -15%)

**_Example 2_**, product with combination bigger size have price impact +100,-, only one special price - 15%
Product price is 1790,- (size 20)
Product price is 1890,- (size 30)

API generate:
Product price is 1890,- (size 30)
Sale price 1 701,00 Kč – this is completely wrong. I have no idea where problem is. Correct sale price is 1606.5,- (showed in the FO)

**4)	Products are declined for different price.**
API price is different compare with google robot found price on the webpage.
Each time is problem with product with combination (bigger size) with bigger price. I guess Google robot have price from first combination.
I guess that Meta data are not changed according to selected combination.
_This picture showing selected bigger size but meta data contain price from first or default combination:_
Correct is 1612,-
![image](https://user-images.githubusercontent.com/38213520/220117236-4c9542cb-3d14-446b-af96-8bcfea18a557.png)
or
product:price:amount (Ctrl+I - Page Info in the Firefox) is still same. But bigger size have set price impact +52,-

**5)	API transferring products which are out of stock as on stock.**
**GMC** - show **on stock**:
![image](https://user-images.githubusercontent.com/38213520/220122700-2424b8cb-4957-4af6-b616-1127c7386432.png)
**Admin** - is **out of stock**:
![image](https://user-images.githubusercontent.com/38213520/220123427-46b4e647-6442-4ac6-b7a9-afb8f3d78cbe.png)

**6)	Is there possible set more frequent synchronization?**
**7)	Is there possible show product feed as xml link for checking data?**

Module version: v1.41.0
PS version: 1.7.8.5

Thank you
Best regards
PN

### Expected behavior

Generate correct data for google ads.

### Steps to reproduce

Described above

### PrestaShop version(s) where the bug happened

1.7.8.5 + #GHSA-hrgx-p36p-89q4

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

psxmarketingwithgoogle v1.41.0

**Comment by hibatallahAouadni** [comment]
Hello @PeNov 

It seems that your issue is not a PrestaShop core bug.
If your module is psxmarketingwithgoogle Official, please contact support team on Addons

We will close this issue.

Thanks!

**Comment by PeNov** [comment]
Hello @hibatallahAouadni 

I think that point 4) is problem of the PS core.

Thank you
Best regards
PN

**Comment by PeNov** [comment]
Hello, 
Problem described on the point 1 is solved by updating module to the version 1.42.0.
Thank you

**Comment by PeNov** [comment]
Hello @Quetzacoalt91,
after update to the version 1.43.0 - problem with product filter appeared again (point 1)
after update to the version 1.44.0 (1) - problem with product filter persist
after **downgrade** to the version 1.**42**.0 - problem with product filter persist

Steps to reproduce:
Start new campaign or modify existing campaign, the campaign filter looks like (select filter is grayed):
 
![image](https://user-images.githubusercontent.com/38213520/222742460-5167a47e-9656-4322-b9cf-0ce46d4958d3.png)

after reload page (F5 or Ctrl+F5) button appear (is not grayed), we can click. But popup window only still loading. 
![image](https://user-images.githubusercontent.com/38213520/222742477-39be4569-403b-4668-a1ad-ed82e7976a29.png)

 
![image](https://user-images.githubusercontent.com/38213520/222742510-a3f195bd-8ade-4ecb-98de-69ab62b64c50.png)

 

We have a lot of these errors on the web server log file:
[03-Mar-2023 14:35:43 Europe/Prague] PHP Notice:  Trying to access array offset on value of type bool in /home/www/domain.cz/www/domain.cz/src/Adapter/Cart/QueryHandler/GetCartForViewingHandler.php on line 224
[03-Mar-2023 14:40:51 Europe/Prague] PHP Notice:  Trying to access array offset on value of type null in /home/www/domain.cz/www/domain.cz/classes/order/Order.php on line 981
[03-Mar-2023 14:40:51 Europe/Prague] PHP Notice:  Trying to access array offset on value of type null in /home/www/domain.cz/www/domain.cz/classes/order/Order.php on line 982
[03-Mar-2023 14:40:51 Europe/Prague] PHP Notice:  Trying to access array offset on value of type null in /home/www/domain.cz/www/domain.cz/classes/order/Order.php on line 983
[03-Mar-2023 14:40:51 Europe/Prague] PHP Warning:  file_exists(): open_basedir restriction in effect. File(/views/templates/hook/gtagEvent.tpl) is not within the allowed path(s): (/home/www/domain.cz/www/domain.cz:/home/www/tmp) in /home/www/domain.cz/www/domain.cz/classes/module/Module.php on line 2509

Thank you
Best regards
PN

**Comment by PeNov** [comment]
Hi,
And there is one more thing, all others prestastop native modules were updated too. Maybe it is related.
PN

**Comment by PeNov** [comment]
Hello @Quetzacoalt91,

Today I tested new version 1.45.0. Product filter works but after more than 30min spent by selecting products for campaign (It is terrible work you must select all combinations).
Results for 668 products:
![image](https://user-images.githubusercontent.com/38213520/225336382-42c9b093-3524-4d2a-a5ea-c31f72b03484.png)
Now I click to dashboard, orders, it does not matter.
After this I returned to the Marketing/Google/Campaign, I see No product filter or only 1 product selected on the overview and same situation is after click modify. 30 min work was absolutely lost ☹. This behavior is strange.

![image](https://user-images.githubusercontent.com/38213520/225336478-020781db-bc9a-4c3d-a98c-8dc9d59a894a.png)
or
![image](https://user-images.githubusercontent.com/38213520/225336525-dfd16d5a-e0b1-4996-8b95-a264b7b92493.png)

It would be possibility add new filter choose product listed from eshop category? Choose some category from eshop?
![image](https://user-images.githubusercontent.com/38213520/225336616-ab1d9b1b-aa4a-4cad-9809-fb99a722542f.png)
Thank you
Best regards
PN

**Comment by PeNov** [comment]
Hello @Quetzacoalt91 

I thank you for the version 1.46.0. I will test new version now. This version is not available for the update, because file psxmarketingwithgoogle.php contain old version:  `$this->version = '1.45.0';` and file: config.xml have same problem. I think this should be updated.

Thank you
Best regards
PN

**Comment by PeNov** [comment]
Hello @Quetzacoalt91 

I think that for avoid many these errors in the log of the web server. 
_(PHP Warning: file_exists(): open_basedir restriction in effect. File(/views/templates/hook/gtagEvent.tpl) is not within the allowed path(s): (/home/www/domain.cz/www/domain.cz:/home/www/tmp) in /home/www/domain.cz/www/domain.cz/classes/module/Module.php on line 2509)_

We should change file:  /modules/psxmarketingwithgoogle/classes/Handler/RemarketingHookHandler.php

Lines: 106, 118, 134

From:
`$this->module->display($this->module->getfilePath(), '/views/templates/hook/gtagEvent.tpl')`

To
`$this->module->display($this->module->getfilePath(), 'views/templates/hook/gtagEvent.tpl')`

What do you think?

Than you

Best regards
PN

**Comment by Quetzacoalt91** [comment]
We had a contribution on the same topic on Facebook (https://github.com/PrestaShopCorp/ps_facebook/pull/407). This can be done on Marketing with Google as well.
I indeed forgot to bump the version with the latest release. However the configuration page is distributing via CDN, no need to upgrade the module to see the latest changes. If you force the refresh of the page on the module page, you'll get the latest version.
