### ISSUE TITLE
Kanban PR Dashboard - Enter column Need second review

### ISSUE THREAD

**Issue by WahbiPS** [PrestaShop/PrestaShop#31452]
### How Pull Requests enter this column

*PRs on the main PrestaShop repository need 2 approvals, at least one from the maintainer. This column contains PR that needs the 2nd approval.*

- If a PR is in PrestaShop repo and has one approved, then the PR is placed automatically in second review.

**Comment by nicosomb** [comment]
"Github Project Automation +" works for classic projects https://github.com/alex-page/github-project-automation-plus
But Github abandoned classic projects. So we can't use "Github Project Automation +". 

We need to use native automatic workflows (for example https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/archiving-items-automatically), as Mateus found about "nexts priority". 

Automatic workflows are very simple for now. We can just configure "if there is an approve, then set this status to this PR". 
The trouble with this workflow is that even if the approve comes from someone which is not in the committers team, it will assign the "Need 2nd approve" status.
