### ISSUE TITLE
PHP Fatal error:  require(): Failed opening required '/var/www/vhosts/vestilafamiglia.it/httpdocs/var/cache/prod/ContainerKvthlig/removed-ids.php'

### ISSUE THREAD

**Issue by MajorKevin07** [PrestaShop/PrestaShop#31468]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I'm facing 500 internal error and unable to add things into the cart. 

### Steps to reproduce

PHP Fatal error:  require(): Failed opening required '/var/www/vhosts/[vestilafamiglia.it/httpdocs/var/cache/prod/ContainerKvthlig/removed-ids.php](http://vestilafamiglia.it/httpdocs/var/cache/prod/ContainerKvthlig/removed-ids.php)'

### PrestaShop version(s) where the bug happened

1.7.6.3

**Comment by hibatallahAouadni** [comment]
Hello @MajorKevin07 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must fill the template to submit a complete bug report and provide clear and concise step to reproduce**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: it seems you have a problem with rights acces 😉 

Thanks!
