### ISSUE TITLE
autoupgrade: rows not created for inactive langs in product_attribute_lang 

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#31466]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The ps_810_add_product_attribute_lang_data.php of autoupgrade module doesn't create rows for inactive langs.

Inactive langs are hidden for the front but should be set in back office.

### Expected behavior

`ps_product_attribute_lang` should contain generated entries for both languages even the inactive langs too.

### Steps to reproduce

1. install ps 8.0 
2. Have two languages, disable the second one.
3. upgrade to 8.1 with autoupgrade
4. See missing rows for inactive id langs product_attribute_lang 

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

all

**Comment by Hlavtox** [comment]
@jf-viguier Will by fixed by https://github.com/PrestaShop/autoupgrade/pull/568, my mistake.

**Comment by jf-viguier** [comment]
@Hlavtox thanks
Why not adding this rows directly in sql with an insert and a join with lang table ?

**Comment by Hlavtox** [comment]
@jf-viguier Honestly, because I don't know how, you do?
We would need to run this for each entry in ps_lang.
```sql
INSERT INTO ps_product_attribute_lang 
(id_product_attribute, id_lang, available_now, available_later)
SELECT pa.id_product_attribute, $id_lang, '', ''
FROM ps_product_attribute pa;
```

**Comment by Hlavtox** [comment]
Oh, this works! :D

```sql
INSERT INTO ps_product_attribute_lang 
(id_product_attribute, id_lang, available_now, available_later)
SELECT ps_product_attribute.id_product_attribute, ps_lang.id_lang, '', ''
FROM ps_product_attribute CROSS JOIN ps_lang;
```

**Comment by jf-viguier** [comment]
or:
```
INSERT INTO ps_product_attribute_lang 
(id_product_attribute, id_lang, available_now, available_later)
SELECT ps_product_attribute.id_product_attribute, ps_lang.id_lang, '', ''
FROM ps_product_attribute, ps_lang;
```

**Comment by Zoefinders** [comment]
@hibatallahAouadni If problem existe from 1.7.8 to 8.0 ?

**Comment by Hlavtox** [comment]
@Zoefinders I added this feature to 8.1, the table was not present in 8 and older.

**Comment by hibatallahAouadni** [comment]
Hello @Zoefinders 

> @hibatallahAouadni If problem existe from 1.7.8 to 8.0 ?

When we use the label `Regression`, means the issue is a regression on the version mentionned :wink: In our case, it's a regression on 8.0.0, which means that the problem doesn't occurs with the older version like 1.7.8 :wink: 

Thanks!

**Comment by Hlavtox** [comment]
@hibatallahAouadni I added the feature on 8.1, it's not a regression on 8.0.

**Comment by Hlavtox** [comment]
Fixed by https://github.com/PrestaShop/autoupgrade/pull/568
