### ISSUE TITLE
Fatal error in module file

### ISSUE THREAD

**Issue by Maximesimoens** [PrestaShop/PrestaShop#31460]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

an error message is displayed when I want to access my modules and services section :

[PrestaShop] Fatal error in module file :/var/www/clients/client149/web716/web/classes/module/Module.php(1361) : eval()'d code:
syntax error, unexpected 'use' (T_USE)

### Expected behavior

i hoped to see the module work..

### Steps to reproduce

go to your backoffice, go to mods and services, add a module, upload the compressed folder of the installation module prestashop facebook, 

![Capture d’écran 2023-02-20 121835](https://user-images.githubusercontent.com/125880656/220125336-665bf3d9-7e50-47ac-b87a-422265daa0ae.png)

### PrestaShop version(s) where the bug happened

1.6.1.7

### If your bug is related to a module, specify its name and its version

v1.24.0-ps_facebook

**Comment by sallemiines** [comment]
Hello @Maximesimoens  ,

PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).

Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

Thank you
