### ISSUE TITLE
PPV2 - The images of products V2 are not displayed in stocks page 

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#31478]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

 The images of products P2 are not displayed in stocks page 

**8.1.0_beta : NOK With Product V2** :x: 

![image](https://user-images.githubusercontent.com/92912932/220398653-f3227f13-0aba-4e42-b510-43bf4f9da7d0.png)

![image](https://user-images.githubusercontent.com/92912932/220398618-eca13888-e699-4521-9b93-0bd7c508dcd2.png)

develop : NOK :x: 

![image](https://user-images.githubusercontent.com/92912932/220398538-343785e7-4fcc-457a-a26e-c316f768f3b6.png)

**8.1.0_beta : OK With Product V1** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/220398435-581124ba-f8af-4bc3-9d55-371b07e9de39.png)

**8.0.1 : OK** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/220398566-0003b412-94c7-4399-af94-de85d4fa0a3d.png)

Indeed, it's a regression on 8.0.1_beta!

### Expected behavior

The images are well displayed on stock page

### Steps to reproduce

1. Use 8.1.0_beta
2. Go to 
3. Go to BO > CONFIGURE > Advanced parameters > New & Experimental Features > Enable `New product page`
4. Go to BO > SELL > Catalog > Products > Create any product type (eg:With combinations) with **Product V2**
5. In the Description field > Add an image 
6. Click on Save
7. Go to BO > SELL > Catalog > Stock 
8. See error > the images related to product type V2 are not displayed

### PrestaShop version(s) where the bug happened

8.1.0_beta

### PHP version(s) where the bug happened

7.3, 8.1

**Comment by AureRita** [comment]
Hi @HanaRebaiQA  ,

I reproduce the issue with PrestaShop version 8.1.0 beta and not with the version 8.0.1. as you can see : 

in 8.1.0 beta 
![image](https://user-images.githubusercontent.com/100699445/220653679-00f6b6d4-77fc-43dc-93f5-6567e20cbc4a.png)

In 8.0.1 
![image](https://user-images.githubusercontent.com/100699445/220653852-1d7b74c0-20ba-4b63-8a11-48c67351c904.png)



Nice catch ! It's a regression ! I'll add it to the patch backlog.

Please be aware that some issues might take a very long time to be resolved. 

Thank you
