### ISSUE TITLE
FO - An error related to the ManufacturerController is displayed on the brands page

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#31476]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

An error related to the ManufacturerController is displayed on the brands page

**8.1.0_beta : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/220382348-95adeee4-204a-4c8b-9cd2-3d30726990bd.png)

https://user-images.githubusercontent.com/92912932/220383819-1623721a-9955-4b04-8ffc-0b49a1df5884.mp4

**develop : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/220382301-20c8bf06-8459-48c8-a46f-8f63bf01bf82.png)

**8.0.1 : OK** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/220382330-44d66ef2-0d1c-406c-91c7-dfb22ce9e904.png)

Indeed, it's a regression on the 8**.1.0_beta**!

### Expected behavior

No error is displayed on Brands page in FO

### Steps to reproduce

1. Use 8.1.0_beta
2. Go to FO > Click on the `Sitemap` link
3. Then, Click on the `Brands` link
4. The Brands page is displayed
5. See error > An error related to the ManufacturerController is displayed
6. OR
7. Click on any product > the product details page is displayed
8. Click on `Product details`
9. Then, click on the brand logo
10. Click on the `Brands` link
11. See error > An error related to the ManufacturerController is displayed

### PrestaShop version(s) where the bug happened

8.1.0_beta

### PHP version(s) where the bug happened

7.3, 8.1

**Comment by Hlavtox** [comment]
@HanaRebaiQA Fixed by https://github.com/PrestaShop/PrestaShop/pull/31319, but merged 1 day after beta build.

**Comment by florine2623** [comment]
I can confirm what @Hlavtox said.
I tested the page, and it is looking good ! ✅ 

Thanks to both of you !

**Comment by HanaRebaiQA** [comment]
Thank You @florine2623 and @Hlavtox ^^
