### ISSUE TITLE
Can't create any Cart Rule per customer

### ISSUE THREAD

**Issue by JulienAK** [PrestaShop/PrestaShop#31484]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Impossible to create a cart rule per customer. No matter what you enter in the text field, nothing happens and nothing is saved.

![CleanShot 2023-02-22 at 11 02 25](https://user-images.githubusercontent.com/126061885/220588141-01eda8cd-4b69-421e-b772-f4c81e33d2bc.png)

### Expected behavior

A display and selection of available clients according to the value of the entry.

### Steps to reproduce

1. Go to "Cart Rule"
2. Create a new one
3. Try to limit the discount to a single customer by entering his name, first name or email in the field provided

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

8.0

**Comment by AureRita** [comment]
Hi @JulienAK 

Thank you for your report, I tried to reproduce your issue with the provided information but I didn't have issue as you can see ; 

[Untitled_ Feb 22, 2023 4_36 PM.webm](https://user-images.githubusercontent.com/100699445/220673491-f9df8d00-3a90-4116-a355-f4c4ccaf8ca8.webm)

Did I miss something ? 

Waiting for your feedback

**Comment by JulienAK** [comment]
Hello,

Indeed you do not have the problem. The compilation of my assets seemed to have gone well but after checking, I have the impression that there is a JS problem on my side.

Below is the display when clicking on the "Add cart rule" button.

I'll look into this on my end, thanks for your reply.

![CleanShot 2023-02-22 at 17 44 01](https://user-images.githubusercontent.com/126061885/220697898-b1c3a625-6e3c-4ce5-befe-c7f223facdf2.png)
