### ISSUE TITLE
Prestashop Dashboard Upgradation Error.

### ISSUE THREAD

**Issue by anjalishopping** [PrestaShop/PrestaShop#31481]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Cant able to upgrade Our prestashop Dashboard. even though i click upgrade its showing the attached error. kindly check and solve the issue.
![prestashop error](https://user-images.githubusercontent.com/125979009/220541738-5eac3055-c894-4301-9d45-7dd5b665ba33.png)

### Expected behavior

i want to upgrade our dashboard metrix

### Steps to reproduce

Nothing

### PrestaShop version(s) where the bug happened

1.7.7.7

**Comment by ghost** [comment]
Hello,
You must contact [PrestaShop SA here ](https://addons.prestashop.com/fr/contactez-nous?id_product=49583)
Have a nice day

**Comment by AureRita** [comment]
Hi @anjalishopping 

Thank you for your report, as said @okom3pom, you can contact the developper about this issue([PrestaShop SA here](https://addons.prestashop.com/fr/contactez-nous?id_product=49583)), it's not related to us, so I'll close this issue 

Have a nice day
