### ISSUE TITLE
Wrong format when generating thumbnails

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#31488]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When not using the new image generation formats, the thumbnails always contain JPEG files regardless to what is choose in image settings. This bug only happens if the front end is generating the image. If the backend generates it, it works fine.

You can check the format of generated thumbnails easily by this online tool - https://www.checkfiletype.com/.

Fixed by https://github.com/PrestaShop/PrestaShop/pull/31485

### Expected behavior

Image generation (for `.jpg` files) should respect the settings in Image settings and not force JPEG file format.

### Steps to reproduce
1. Create a product and upload one JPEG image 
2. Create a product and upload  one PNG image. You can make them in MS PAINT for example.
3. Go to Design > Image settings and choose image settings like this.
![settings](https://user-images.githubusercontent.com/6097524/220625459-6d880e18-d9b2-4105-827d-acd5782a5ee0.jpg)

4. Delete the thumbnail of your PNG image on the folder [yourshop]/img/p/[idofyourproduct]
5. Go to FO to generate thumbnails and see that all thumbails are JPEGs. 🔴 
**Thumbnails of image 25 should be PNGs inside.**

![Snímek obrazovky 2023-02-22 113528](https://user-images.githubusercontent.com/6097524/220625644-60107c0f-d615-4402-9ab4-d88913d05ac2.jpg)

To verify your images, you can use this link : https://www.checkfiletype.com/

### PrestaShop version(s) where the bug happened

8.1

**Comment by AureRita** [comment]
Hi @Hlavtox 

Thank you for your report, I reproduce the issue with PrestaShop version 8.1.0  and not with the version 8.0.1 as you can see : 

[Untitled_ Feb 22, 2023 6_00 PM.webm](https://user-images.githubusercontent.com/100699445/220701430-8e032dbf-9338-471d-bcfa-1dde9082a91a.webm)

Nice catch ! It's a regression ! I'll add it to the patch backlog.

Thank you for your PR 

Thank you
