### ISSUE TITLE
Incorrect cart rule detail if products with different VAT

### ISSUE THREAD

**Issue by joseantgv** [PrestaShop/PrestaShop#31486]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If you create a cart rule and apply it only to a selected products, and you have products with different VAT in the cart, the amount displayed is not correct.

### Expected behavior

The cart rule detail and the "Discount" row must match.

### Steps to reproduce

1. Create a cart rule with 100% discount and apply it to the cheapest product
![image](https://user-images.githubusercontent.com/5071263/220595734-ae14f790-0a41-4bd5-a54b-3fe25ecfbdbe.png)

2. Configure different VAT for 2 products
![image](https://user-images.githubusercontent.com/5071263/220596004-477bead9-9504-4c35-bad3-db86a2e1fbf6.png)
![image](https://user-images.githubusercontent.com/5071263/220595973-3fa01885-a7aa-4b55-9679-fbdeff27777b.png)

3. Add both products to the cart and check the cart summary details
![image](https://user-images.githubusercontent.com/5071263/220596334-8ffa2029-f7e6-4281-8580-b596dcc04f4d.png)

### PrestaShop version(s) where the bug happened

8.0.1

**Comment by AureRita** [comment]
Hi @joseantgv  

Thank you for your report, I reproduce the issue with PrestaShop version 1.7.8.8 as you can see : 

[Untitled_ Feb 22, 2023 4_53 PM.webm](https://user-images.githubusercontent.com/100699445/220683071-ac42a93a-c29a-4ee3-9399-db1e40ba0ad2.webm)


I'll add this to the backlog so it can be fixed.

Thanks
