### ISSUE TITLE
Data from PrestaShop Addons is invalid, and cannot fallback on cache

### ISSUE THREAD

**Issue by itaak** [PrestaShop/PrestaShop#31506]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hey !

I'm tired.... For a week I have a error 500 during install addons modules. I’ve tested everything (docker, laragon, xamp) another wifi etc... nothing change. Nevertheless with 1.7.8 it's ok. The mistake come of addons API. 

In the logs I have 'Data from PrestaShop Addons is invalid, and cannot fallback on cache' when I'm 67%

Do you have an answer ? Thx

### Steps to reproduce

- Unzip Prestashop Installation in development environment and go to install folder

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4.33

**Comment by HanaRebaiQA** [comment]
Hello @Itaak 

Thanks for your report.
I tried to reproduce your issue on PS1786 and php7.4. But, I was unable to reproduce it.

The Install Addons modules are well passed.

![image](https://user-images.githubusercontent.com/92912932/220966589-97a68a18-b30a-4342-a552-1e5d30b4000a.png)

![image](https://user-images.githubusercontent.com/92912932/220967187-f5b256df-8ab7-4f88-ba8e-39eb28c41406.png)


Could you please check again?

Thank You!

**Comment by itaak** [comment]
Hello @HanaRebaiQA 

Thank you for your time !

The problem is Firefox ... I just tested with Chrome and it's OK. I don't know why but it works ^^
