### ISSUE TITLE
PHP Fatal Error in config/smartyfront.config.inc.php:97

### ISSUE THREAD

**Issue by nl2ttl** [PrestaShop/PrestaShop#31528]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

My PHP Errorlog shows:

**PHP Fatal error:  Uncaught Error: Call to a member function setTemplate() on null in /public_html/config/smartyfront.config.inc.php:97**

Stack trace:
#0 /home/kassarollen/public_html/classes/Smarty/SmartyLazyRegister.php(81): smartyRender(Array, Object(Smarty_Internal_Template))
#1 /home/kassarollen/public_html/var/cache/prod/smarty/compile/AngarThemelayouts_layout_full_width_tpl/ab/c5/cd/abc5cd4ed5074b239711b76ad0952ff0fa36dbb4_2.file.order-confirmation.tpl.php(194): SmartyLazyRegister->__call('smartyRender', Array)
#2 /home/kassarollen/public_html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(248): Block_69322176563f4b2dee9c275_03086088->callBlock(Object(Smarty_Internal_Template))
#3 /home/kassarollen/public_html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(184): Smarty_Internal_Runtime_Inheritance->callBlock(Object(Block_69322176563f4b2dee9c275_03086088), Object(Smarty_Internal_Template))
#4 /home/kassarollen/public_html/vendor/smarty/smarty/libs/ in /home/kassarollen/public_html/config/smartyfront.config.inc.php on line 97
[21-Feb-2023 13:49:09 Europe/Amsterdam] PHP Deprecated:  The hook "createAccount" is deprecated, please use "actionCustomerAccountAdd" instead in module "statsdata". in /home/kassarollen/public_html/classes/Hook.php on line 850

### Expected behavior

No PHP error :)

### Steps to reproduce

Test serval PHP versions

**Your current PrestaShop version: 8.0.1

Your current PHP version: 7.4.33

Latest official version for minor channel.: 8.0 stable - (8.0.1)**

### PrestaShop version(s) where the bug happened

8.01

### PHP version(s) where the bug happened

7.4.33

**Comment by hibatallahAouadni** [comment]
Hello @nl2ttl 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must fill the template to submit a complete bug report and provide clear and concise steps to reproduce**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by adviva** [comment]
https://www.prestashop.com/forums/topic/1078118-error-500-php-fatal-error-uncaught-error-call-to-a-member-function-settemplate-on-null-in-configsmartyfrontconfigincphp97/

**Comment by adviva** [comment]
@hibatallahAouadni  BTW it looks like it has been fixed in this last version of the file.
https://github.com/PrestaShop/PrestaShop/blob/develop/config/smartyfront.config.inc.php
