### ISSUE TITLE
Autoupgrade - An exception and errors related to JavaScript are displayed when do the rollback from 8.1.0 to 8.0.1 only with php 8.1 + the shop is broken

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#31530]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

An error related to JavaScript is displayed when do the rollback from 8.1.0 to 8.0.1 only with php 8.1

**Rollback from 8.1.0 to 8.0.1 with PHP 8.1: NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/221201391-bf0bc08f-1606-49c7-9a02-deef6f8f60c3.png)

![image](https://user-images.githubusercontent.com/92912932/221201413-4a761532-ce35-4352-8034-0703563add55.png)

![image](https://user-images.githubusercontent.com/92912932/221201541-1a06f0df-bbe9-49a4-b623-4525011746b1.png)

**THEN, THE SHOP IS BROKEN!**

**Rollback from 8.1.0 to 8.0.1 with PHP 7.4: OK** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/221201917-dcdfcf03-61f3-47e6-82f7-94c3fee8112c.png)

Indeed, it's a **regression related to PHP version**!

### Expected behavior

The rollback should be passed!

### Steps to reproduce

1. Use PHP 8.1
2. Install the 8.0.1
3. Create a release for the 8.1.0
4. Install the autoupgrade v4.16 module from dev branch
5. git clone git@github.com:PrestaShop/autoupgrade.git 
6. cd autoupgrade
7. git pull --rebase origin dev
8. composer install
9. Go to BO > Module manager > Install the autoupgrade module
10. Click to configure > Make the shop on in maintenance mode
11. Upgrade to 8.1.0
12. Connect to the 8.1.0 shop
13. Go to 1-click upgrade
14. Do the rollback from 8.1.0 to 8.0.1
15. See error >> Errors related to JS
16. Click another time on Rollback >> Same errors of JS
17. Refresh the page >> See the thrown exception!

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

autoupgrade v4.16.0 from dev branch

**Comment by MatShir** [comment]
To retest when [4.16 milestone is done](https://github.com/PrestaShop/autoupgrade/milestone/26)

**Comment by Hlavtox** [comment]
@PrestaShop/qa-functional Can you retest?

**Comment by florine2623** [comment]
Tested with autoupgrade `v4.16.2` and PHP `8.1`.

Upgraded to `8.1.0` using Major release option:
<img width="1198" alt="Screenshot 2023-08-03 at 14 42 44" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/32e42fe4-9422-4af2-a830-9ca80cc3924e">

Upgrade and Rollback went well, no issue or exception related to javascript.

https://github.com/PrestaShop/PrestaShop/assets/16019289/b9d5c1d0-5265-4e09-8492-ff8e0522365f

I'm closing this issue as it is not reproductible with latest version of autoupgrade.
