### ISSUE TITLE
Activiti overview not working

### ISSUE THREAD

**Issue by Movinyl** [PrestaShop/PrestaShop#31538]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The arrows keep turning and no results are displayed
![prestashop screenshot](https://user-images.githubusercontent.com/126312011/221341338-e2662035-8a9a-475c-918b-8917dec8f74d.png)

### Expected behavior

Results for example how many visitors are on the site should be displayed

### Steps to reproduce

Dashboard

### PrestaShop version(s) where the bug happened

8.0.1

**Comment by sallemiines** [comment]
Hello @Movinyl 

Could you please add the steps to reproduce , and the php version ? 

Thank you!

**Comment by Movinyl** [comment]
Hello,

PHP version = 8.0.28

there are no steps to produce, when i open the dashboard teh arrows next to how many visitors there are keeps turning

kind regards, walter

**Comment by djoelleuch** [comment]
Hello @Movinyl ,
I didn't manage to reproduce your issue , i think is a cache problem .

Could you please check and feedback !
Thank you !

**Comment by Movinyl** [comment]
Hi, 
i cleared my cache, no result.

kind regards
Walter

**Comment by hibatallahAouadni** [comment]
Hello @Movinyl 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must respect the template to submit a complete bug report, provide clear and concise steps to reproduce and a screen record.**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thanks!
