### ISSUE TITLE
email notification not working

### ISSUE THREAD

**Issue by djsmoye** [PrestaShop/PrestaShop#31539]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

despite the activation of an e-mail address intended to receive notifications of new orders, no message arrives. All status notifications work for clients but no administrator receives a message

### Expected behavior

Correct operation for a native module

### Steps to reproduce

Make a order
Admin wait for notification
Wait and wait...

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_emailalerts

**Comment by sallemiines** [comment]
Hello @djsmoye 

Could you please provide us the module `ps_emailalert` version ? and add a screen record / screenshot for your configuration in the `Advanced Parameters > Emails `


Thank you !

**Comment by djsmoye** [comment]
Hi @sallemiines,

Version are 2.4.0. All other email (order or update work perfectly).
![presta](https://user-images.githubusercontent.com/126320937/221540934-46659940-e27f-44cd-9db8-d3a32b5f4606.png)

**Comment by hibatallahAouadni** [comment]
Hello @djsmoye 

It seems that you didn't set your email configuration as I can see throught your screenshot.
Please configure it and feedback.

Thanks!

**Comment by djsmoye** [comment]
Hi. you cannot see email but I have set email configuration since all the other sendings work correctly except the alerts.

**Comment by florine2623** [comment]
You need to add the email address in the "New order" section in your email alert module :
<img width="855" alt="Screenshot 2023-03-03 at 12 19 19" src="https://user-images.githubusercontent.com/16019289/222707370-45b34a36-4918-4b91-8145-27fa82712c7e.png">

I'll close your issue as it is a configuration mistake and not an issue ^^
Thanks!

**Comment by djsmoye** [comment]
Hi have email address in the "New order".
![ps](https://user-images.githubusercontent.com/126320937/222714559-4402c4cb-114e-42e6-af86-d601696ed44d.png)

**Comment by djsmoye** [comment]
> You need to add the email address in the "New order" section in your email alert module : <img alt="Screenshot 2023-03-03 at 12 19 19" width="855" src="https://user-images.githubusercontent.com/16019289/222707370-45b34a36-4918-4b91-8145-27fa82712c7e.png">
> 
> I'll close your issue as it is a configuration mistake and not an issue ^^ Thanks!

Please reopen my ticket. Thanks
