### ISSUE TITLE
8.0.1 BO order status field unreadable

### ISSUE THREAD

**Issue by PrestaVision** [PrestaShop/PrestaShop#31540]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

PS 8.0.1 (update over 8.0.0):
when entering back office, and select an order, the field for the order status remains fully colored, thus unreadable.
I suspect this is due to the new-theme's CSS, but i'm not sure.
![Screenshot - 25-2-2023 , 10_10_56](https://user-images.githubusercontent.com/119726053/221349122-7e52fa5e-13d4-4c47-b829-b78a6d5b179c.png)

### Expected behavior

Previously, the order status in the colored bar was readable with white or grey text on the colored background.

### Steps to reproduce

1. install the PS 8.0.1 update over PS 8.0.0
2. log in to BO
3. go to 'Orders' > 'Orders'
4. select an existing order
5. check the order status in the upper left corner in the status bar.

### PrestaShop version(s) where the bug happened

8.0.1 update

### PHP version(s) where the bug happened

8.0

**Comment by sallemiines** [comment]
Hello @PrestaVision 

I didn't manage to reproduce the issue with the previous steps ! Could you please provide us more infos : screen record for example? the language of your shop ..

![Orders-Order-KHWLILZLL-from-John-DOE-•-801](https://user-images.githubusercontent.com/31663369/221602307-9a1b61a7-f837-4e37-80b5-24b0b0fe3af5.png)

Thank you !

**Comment by PrestaVision** [comment]
Hi @sallemiines ,
then it could also be an error in the installed theme i use: Toy Story theme from Prestashop Addons Store.
The error only occured after the upgrade from 8.0.0 to 8.0.1, so i thought the upgrade caused the error.
I will further investigate and let you know ASAP, plus the solution to this.

Thank you kindly,
best,
Rene.

**Comment by PrestaVision** [comment]
BTW i am using the Dutch (Netherlands) language in backoffice.

**Comment by djoelleuch** [comment]
Hello @PrestaVision ,
I didn't manage to reproduce the issue with the previous steps even when i changed the language to Dutch .

![image](https://user-images.githubusercontent.com/115152460/222117316-d3dc75b8-1bb2-431a-a905-124cc1f0a48c.png)

I think it's about using the Toy Story theme  so try to switch to the classic theme 
Waiting for your feedback ,thanks .

**Comment by PrestaVision** [comment]
@djoelleuch @sallemiines ,

you can consider this one **solved**.
I still do not know what triggered the error in the make up, but i have the working solution for it:

1. download from the PS 8.0.1 zip file the 2 following .CSS files and copy them to the live site in the same position:
a. admin***/themes/new-theme/public/orders.css
b. admin***/themes/new-theme/public/theme.css

2. go to back office > advanced settings > performance  and click on Clear Cache

This solves the problem 100%. The old css files were somehow changed in configuration and filesize, but an overwrite with the original css files and clearing cache solved everything.
