### ISSUE TITLE
Autoupgrade manual(cli) doesn't work 

### ISSUE THREAD

**Issue by venditdevs** [PrestaShop/PrestaShop#31549]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Since release of PS8 there is no more /install/upgrade.php but we now must use: /modules/autoupgrade/upgrade.php
But really everything is broken.

These manual/steps are not working:
https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/upgrade/

After some quick and dirty fixes ( e.g. paths incorrect and variables not set) i 'm now stuck with this one and i can't seems to fix it:
PHP Fatal error:  Uncaught Error: Call to undefined method PrestaShop\PrestaShop\Core\Module\ModuleRepository::getFilteredList()

### Expected behavior

Give us a working 1-click/autoupgrade that should work as documented by you.

The CLI method described in the module is NOT the way we need to update.E.g.: It's impossible to update from a directory or archive

There is a serious problem going on with the 8.x release. Basic things like upgrading are totally broken.

### Steps to reproduce

Just follow your own manual:
https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/upgrade/

### PrestaShop version(s) where the bug happened

8.0.0  - 8.0.1

### PHP version(s) where the bug happened

7.4 to 8.1

### If your bug is related to a module, specify its name and its version

autoupgrade

**Comment by sallemiines** [comment]
Hello @venditdevs 

Could you please provide us the version of the module autoupgrade that you used ? 
and can you set a screenshot of the exception that you have?

Thank you !

**Comment by venditdevs** [comment]
@sallemiines We used 4.15.0 and the not (yet)released version 4.15.1 since it's impossible to upgrade from PS 1.7.8.X to PS 8 with the autoupgrade module version below 4.15.0

The first errors you get is include errors because all these paths are wrong :
```
require_once __DIR__ . '/../../vendor/autoload.php';
require_once __DIR__ . '/../../config/defines.inc.php';
require_once __DIR__ . '/../../config/autoload.php';

```
Then, the files /classes/datas.php cannot be found
Because these paths are also wrong:
```
require_once __DIR__ . '/../classes/datas.php';
require_once dirname(__FILE__) . '/../init.php';
require_once _PS_CONFIG_DIR_ . 'bootstrap.php';
```
And then you get the next error and so on and on and on and on ....

It's literally broken everywhere and thus imposible to screenshot every single error here
And we finally updated the store through the web version so i can't view those errors anymore.

Let the autopupgrade developer try for him/herself. ( or maybe you) Just follow the steps in the manual. It will all go wrong at the step 'Database upgrade': php modules/autoupgrade/upgrade/upgrade.php

=========================================================================
Story of Upgrade from 1.7.8.8 to 8.0.1 with autoupgrade module 4.15.X

After i edited the first paths above  the line 'Upgrade::migrateSettingsFile();' i get the following error:
```
PHP Warning:  require_once(/home/test/domains/presta.test/public_html/modules/autoupgrade/upgrade/../../classes/datas.php): failed to open stream: No such file or directory in /home/test/domains/presta.test/public_html/modules/autoupgrade/upgrade/upgrade.php on line 51
PHP Fatal error:  require_once(): Failed opening required '/home/test/domains/presta.test/public_html/modules/autoupgrade/upgrade/../../classes/datas.php' (include_path='/home/test/domains/presta.test/public_html/vendor/pear/pear_exception:/home/test/domains/presta.test/public_html/vendor/pear/console_getopt:/home/test/domains/presta.test/public_html/vendor/pear/pear-core-minimal/src:/home/test/domains/presta.test/public_html/vendor/pear/archive_tar:.:/opt/alt/php74/usr/share/pear') in /home/test/domains/presta.test/public_html/modules/autoupgrade/upgrade/upgrade.php on line 51
```

Changed:
`require_once __DIR__ . '/../../classes/datas.php';`
to:
`require_once __DIR__ . '/../../../install/classes/datas.php';`

Paths in the file are now:
```
require_once __DIR__ . '/../../../vendor/autoload.php';
require_once __DIR__ . '/../../../config/defines.inc.php';
require_once __DIR__ . '/../../../config/autoload.php';
Upgrade::migrateSettingsFile();
require_once __DIR__ . '/../../../install/classes/datas.php';
#require_once __DIR__ . '/../../classes/datas.php';
require_once dirname(__FILE__) . '/../../../init.php';
require_once _PS_CONFIG_DIR_ . 'bootstrap.php';
```

Then stuck at
```
PHP Notice:  Trying to get property 'locale' of non-object in /home/test/domains/presta.test/public_html/classes/Context.php on line 415
PHP Warning:  Use of undefined constant _DB_PREFIX_ - assumed '_DB_PREFIX_' (this will throw an Error in a future version of PHP) in /home/test/domains/presta.test/public_html/classes/Configuration.php on line 175
PHP Warning:  Use of undefined constant _DB_SERVER_ - assumed '_DB_SERVER_' (this will throw an Error in a future version of PHP) in /home/test/domains/presta.test/public_html/classes/db/Db.php on line 219
PHP Warning:  Use of undefined constant _DB_USER_ - assumed '_DB_USER_' (this will throw an Error in a future version of PHP) in /home/test/domains/presta.test/public_html/classes/db/Db.php on line 219
PHP Warning:  Use of undefined constant _DB_PASSWD_ - assumed '_DB_PASSWD_' (this will throw an Error in a future version of PHP) in /home/test/domains/presta.test/public_html/classes/db/Db.php on line 219
PHP Warning:  Use of undefined constant _DB_NAME_ - assumed '_DB_NAME_' (this will throw an Error in a future version of PHP) in /home/test/domains/presta.test/public_html/classes/db/Db.php on line 219
PHP Fatal error:  Uncaught PrestaShopException: Link to database cannot be established: SQLSTATE[HY000] [2005] Unknown MySQL server host '_DB_SERVER_' (-2) in /home/test/domains/presta.test/public_html/classes/db/DbPDO.php:119
Stack trace:
#0 /home/test/domains/presta.test/public_html/classes/db/Db.php(331): DbPDOCore->connect()
#1 /home/test/domains/presta.test/public_html/classes/db/Db.php(241): DbCore->__construct('_DB_SERVER_', '_DB_USER_', '_DB_PASSWD_', '_DB_NAME_')
#2 /home/test/domains/presta.test/public_html/config/alias.php(47): DbCore::getInstance()
#3 /home/test/domains/presta.test/public_html/config/alias.php(52): pSQL('configuration')
#4 /home/test/domains/presta.test/public_html/classes/Configuration.php(175): bqSQL('configuration')
#5 /home/test/domains/presta.test/public_html/classes/Configuration.php(229): ConfigurationCore::loadConfiguration()
#6 /ho in /home/test/domains/presta.test/public_html/classes/db/DbPDO.php on line 119
```

Then i swiched the lines
```
require_once dirname(__FILE__) . '/../../../init.php';
require_once _PS_CONFIG_DIR_ . 'bootstrap.php';
```
to
```
require_once _PS_CONFIG_DIR_ . 'bootstrap.php';
require_once dirname(__FILE__) . '/../../../init.php';
```
Because of that error. That fixed it but now; you get:
```
PHP Notice:  Trying to get property 'locale' of non-object in /home/test/domains/presta.test/public_html/classes/Context.php on line 415
PHP Notice:  Trying to get property 'locale' of non-object in /home/test/domains/presta.test/public_html/classes/Context.php on line 407
PHP Notice:  Trying to get property 'locale' of non-object in /home/test/domains/presta.test/public_html/classes/Context.php on line 415
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PrestaShop\PrestaShop\Adapter\Image\ImageRetriever::__construct() must be an instance of Link, null given, called in /home/test/domains/presta.test/public_html/src/Adapter/Presenter/Cart/CartPresenter.php on line 92 and defined in /home/test/domains/presta.test/public_html/src/Adapter/Image/ImageRetriever.php:50
Stack trace:
#0 /home/test/domains/presta.test/public_html/src/Adapter/Presenter/Cart/CartPresenter.php(92): PrestaShop\PrestaShop\Adapter\Image\ImageRetriever->__construct(NULL)
#1 /home/test/domains/presta.test/public_html/classes/controller/FrontController.php(208): PrestaShop\PrestaShop\Adapter\Presenter\Cart\CartPresenter->__construct()
#2 /home/test/domains/presta.test/public_html/init.php(30): FrontControllerCore->__construct()
#3 /home/test/domains/presta.test/public_html/modules/autoupgrade/upgrade/upgrade.php(54): r in /home/test/domains/presta.test/public_html/src/Adapter/Image/ImageRetriever.php on line 50
```

 I don't want to proceed from here because i know i will run into other problems again. As you can see....it's a huge mess.
 Why on earth did Prestashop removed the install/upgrade.php and forced us to use the new file when it doesn't even work at all.
 With all the new things going on in and with Prestashop it's fair to say that the quality and experience is gone from 'bad' to 'nightmare'. What's up with all of this. We need to update 300 stores through the CLI  method( automated ) Which is now impossible.

**Comment by venditdevs** [comment]
Also tried to copy the files to the location where they used to be (/install/upgrade) 
Then i get :
```
PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "prestashop.adapter.news.circuit_breaker.settings" has a dependency on a non-existent service "prestashop.core.circuit_breaker.guzzle.cache_subscriber". in /home/test/domains/presta.test/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:86
Stack trace:
#0 /home/test/domains/presta.test/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(83): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Object(Symfony\Component\DependencyInjection\Reference), false)
#1 /home/test/domains/presta.test/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(49): Symfony\Component\Dependenc in /home/test/domains/presta.test/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php on line 86
```

**Comment by hibatallahAouadni** [comment]
Hello @venditdevs 

Thanks for all technical details :sweat_smile: 
Ping @PrestaShop/committers can someone please reproduce the issue :pray: 

Thanks in advance!

**Comment by kpodemski** [comment]
Hi @venditdevs 

We're reworking upgrade documentation as it needs to be updated. You can see work in progress there:
https://github.com/PrestaShop/docs/pull/1611

Have you tried to run an upgrade using the web interface? The upgrade from 1.7.8 to 8.0 is relatively light. Not a lot of heavy changes on the DB, etc. I did a few upgrades using the local archive/directory myself, well, [I even have that on video](https://youtu.be/SBz7lApJ_pA?t=1064) 😅 

I'm finishing some other projects now, and then I will focus on the autoupgrade. One thing is certain, you shouldn't try to bring back the old way of upgrading PrestaShop, it really is not worth your time :)

**Comment by venditdevs** [comment]
Hi @kpodemski 

"Have you tried to run an upgrade using the web interface?"
Yes, on one shop but like i said we have  300 shops. Webinterface upgrade is not an option.

"it really is not worth your time"
Well it  saves time when you need to update 300 shops.

I haven't read the full docs yet you've sent but it seems you are pushing to use cli-upgrade.php and that's another real major problem because you can't upgrade from a local (custom) folder/archive with it.
Other problem is that you need to delete the 'Vendor' folder (like in the older manual)and put the new 'Vendor' in that place which you can do...but your cli-upgrade.php won't run anymore. At least that was my experience when i tried that before posting the bug report here.

"One thing is certain, you shouldn't try to bring back the old way of upgrading PrestaShop"
Well we weren't. We were trying to get it working again after it broke. 
We were aware the file moved to the autoupgrade folder but not that this wasn't ment to work anymore.

I hope you'll have time very soon for this.

**Comment by kpodemski** [comment]
Hi @venditdevs 

Could you check [this doc](https://github.com/PrestaShop/docs/blob/131c273ba2b5b162206673298fb0c3c182fd1147/basics/keeping-up-to-date/upgrade-module/upgrade-cli.md)? 

It's the summary of what I did to use autoupgrade to upgrade from 1.7 to 8 using CLI commands only.

**Comment by ChillCode** [comment]
Hi,

Been a month wanting to upgrade to 8 and today was that day and also I wanted to upgrade using the manual way documented [here](https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/upgrade/), so I just copied all new files over old ones and then I run upgrade.php to upgrade the DB, but encountered the same issues as you.

I updated upgrade.php this way, using missing files from install folder:

```
require_once __DIR__ . '/../../../vendor/autoload.php';
require_once __DIR__ . '/../../../config/defines.inc.php';
require_once __DIR__ . '/../../../config/autoload.php';
Upgrade::migrateSettingsFile();
require_once '/var/www/html/install/classes/datas.php';
require_once '/var/www/html/install/init.php';
require_once _PS_CONFIG_DIR_ . 'bootstrap.php';
```

And to solve the Service error:

```
PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "prestashop.adapter.news.circuit_breaker.settings" has a dependency on a non-existent service "prestashop.core.circuit_breaker.guzzle.cache_subscriber". in /home/test/domains/presta.test/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:86
Stack trace:
#0 /home/test/domains/presta.test/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(83): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Object(Symfony\Component\DependencyInjection\Reference), false)
#1 /home/test/domains/presta.test/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(49): Symfony\Component\Dependenc in /home/test/domains/presta.test/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php on line 86
```

I just removed the required config file from resources config dir where PrestaShop walks to load services and where the dependency resides:

`rm /var/www/html/src/PrestaShopBundle/Resources/config/services/adapter/news.yml`

Now I'm facing another issues but I think they are related to noncore modules.

**Comment by kpodemski** [comment]
Hi @ChillCode 

Please check the link I shared above for the upgraded documentation.

**Comment by ChillCode** [comment]
Hi @kpodemski 

Yes, and it worked, was testing if it worked like before as stated on the link I posted, basically doing it manually and I see it's better to use your method using `cli-upgrade.php` instead of `upgrade.php`.

Thanks for the great effort you put on this.

**Comment by kpodemski** [comment]
Great. I'm not sure why there's this error with news.yml, but I had the same when I upgraded using CLI.

**Comment by seederp2p** [comment]
> Hi,
> 
> Been a month wanting to upgrade to 8 and today was that day and also I wanted to upgrade using the manual way documented [here](https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/upgrade/), so I just copied all new files over old ones and then I run upgrade.php to upgrade the DB, but encountered the same issues as you.
> 
> I updated upgrade.php this way, using missing files from install folder:
> 
> ```
> require_once __DIR__ . '/../../../vendor/autoload.php';
> require_once __DIR__ . '/../../../config/defines.inc.php';
> require_once __DIR__ . '/../../../config/autoload.php';
> Upgrade::migrateSettingsFile();
> require_once '/var/www/html/install/classes/datas.php';
> require_once '/var/www/html/install/init.php';
> require_once _PS_CONFIG_DIR_ . 'bootstrap.php';
> ```
> 
> And to solve the Service error:
> 
> ```
> PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "prestashop.adapter.news.circuit_breaker.settings" has a dependency on a non-existent service "prestashop.core.circuit_breaker.guzzle.cache_subscriber". in /home/test/domains/presta.test/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:86
> Stack trace:
> #0 /home/test/domains/presta.test/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(83): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Object(Symfony\Component\DependencyInjection\Reference), false)
> #1 /home/test/domains/presta.test/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(49): Symfony\Component\Dependenc in /home/test/domains/presta.test/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php on line 86
> ```
> 
> I just removed the required config file from resources config dir where PrestaShop walks to load services and where the dependency resides:
> 
> `rm /var/www/html/src/PrestaShopBundle/Resources/config/services/adapter/news.yml`
> 
> Now I'm facing another issues but I think they are related to noncore modules.

> rm /var/www/html/src/PrestaShopBundle/Resources/config/services/adapter/news.yml

I followed your tip by deleting the news.yml, however now I get this:

`INFO - === Step upgradeDb
PHP Fatal error:  Uncaught Error: Class 'PrestaShop\PrestaShop\Core\Util\ArrayFinder' not found in /var/www/MYFOLDER/src/Core/Addon/Theme/Theme.php:70
Stack trace:
#0 /var/www/MYFOLDER/src/Core/Addon/Theme/ThemeRepository.php(93): PrestaShop\PrestaShop\Core\Addon\Theme\Theme->__construct()
#1 /var/www/MYFOLDER/classes/shop/Shop.php(504): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeRepository->getInstanceByName()
#2 /var/www/MYFOLDER/classes/shop/Shop.php(147): ShopCore->setTheme()
#3 /var/www/MYFOLDER/classes/shop/Shop.php(405): ShopCore->__construct()
#4 /var/www/MYFOLDER/config/config.inc.php(117): ShopCore::initialize()
#5 /var/www/MYFOLDER/modules/autoupgrade/classes/UpgradeContainer.php(576): require_once('/var/www/novada...')
#6 /var/www/MYFOLDER/modules/autoupgrade/classes/TaskRunner/AbstractTask.php(120): PrestaShop\Module\AutoUpgrade\UpgradeContainer->initPrestaShopCore()
#7 /var/www/MYFOLDER/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(86): PrestaShop\Module\AutoUpgrade\TaskRunner\Ab in /var/www/MYFOLDER/src/Core/Addon/Theme/Theme.php on line 70`

**Comment by kpodemski** [comment]
Hi @seederp2p 

Did you upgrade using the CLI upgrade method? https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/upgrade-module/upgrade-cli/#upgrade-cli

**Comment by seederp2p** [comment]
I tried the module upgrade, manual and the cli method. All of them failed.

The log I shared is from the cli method

**Comment by mati771** [comment]
@kpodemski 

I updated the store as per the guide -> https://www.youtube.com/watch?v=SBz7lApJ_pA&t=1064s&ab_channel=PrestaShopProject

The store has updated but why has the product page remained the same?
![image](https://github.com/PrestaShop/PrestaShop/assets/63502371/5ecc6015-4521-421f-b9b3-6826dfd5ca46)

It should look like this ->
![image](https://github.com/PrestaShop/PrestaShop/assets/63502371/2cec3b6e-ecb0-42b3-8823-7a6992e1a67d)

**Comment by Hlavtox** [comment]
@mati771 You must enable new product page in experimental features settings. 👍

**Comment by mati771** [comment]
Dziękuję :)

**Comment by ersoftwaregmbh** [comment]
Hi,

i'm trying to update manually from PrestaShop 1.6.7.6 to PrestaShop 8.1.4 using the CLI method outlined here: 

https://github.com/PrestaShop/docs/blob/131c273ba2b5b162206673298fb0c3c182fd1147/basics/keeping-up-to-date/upgrade-module/upgrade-cli.md

The upgrade module v5.0.1 has been installed via shop backend (module manager).

How can i avoid this error which comes from "Symfony" obviously?

![error-cli-upgrade](https://github.com/PrestaShop/PrestaShop/assets/69257372/d22723a5-2d10-4b3e-9e5e-057234fcb1d6)


All previous steps were running fine.

(Linux Debian 12.5 / Plesk Obsidian 18.0.59 / PHP 7.4.33, also used for CLI)


Thanks!

**Comment by Quetzacoalt91** [comment]
Hi everyone,

The upgrade.php file was not supposed to be used since its migration from the `PrestaShop` to the `autoupgrade` repositories. It has been moved without checking its references to the core files, thus all the errors you got when trying to run it.

The new endpoint is now cli-upgrade.php, and the related content has been updated accordingly: https://github.com/PrestaShop/docs/pull/1797
