### ISSUE TITLE
BO - An exception is thrown when adding a bad query with an alias in a wrong position only with php8

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#31551]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

An exception is thrown when adding a bad query only with php8

**PS8.1.0 with php 8.1 : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/221571734-8a33062c-0ff9-4829-9abb-fed7211c0d81.png)

**PS8.0.1 with php 8.1 : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/221571668-7af26104-4e4d-4ef8-973e-bf65c5f95cfc.png)

**PS8.1.0 with php 7.3 : OK** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/221571622-2de1fd95-d79e-49cb-affa-952575924fa7.png)

**PS8.0.1 with php 7.4 : OK** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/221571704-dae96566-6d67-4f55-a699-9e454523f61c.png)

https://user-images.githubusercontent.com/92912932/221572216-3c520703-d01d-451d-9daa-459c8fe01bda.mp4

https://user-images.githubusercontent.com/92912932/221572665-9396f6c7-1384-443b-a31d-fb122680d182.mp4

So, **it's a regression with php8!**

### Expected behavior

An alert message "Bad query" is displayed!

### Steps to reproduce

1. Use PHP 8.1
2. Go to CONFIGURE > Advanced parameters > Database
3. Add new SQL query > add a bad query (for example An alias is set near SELECT *)

```
SELECT * CUST
FROM hana_customer 
WHERE  id_customer = 2
```
4. Add a name for the SQL query
5. Click on Save
6. See error > An exception is displayed!

### PrestaShop version(s) where the bug happened

8.0.1, 8.1.0

### PHP version(s) where the bug happened

8.1

**Comment by matks** [comment]
@boherm starts working on it

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/31667
