### ISSUE TITLE
PROBLÈME DE MISE A JOUR

### ISSUE THREAD

**Issue by educatif** [PrestaShop/PrestaShop#31564]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Bonjour,
j'ai un problème avec la mise à jour de Prestashop on utilisant le 1-click upgarde pour passer de la version 1.7.8.6 à 1.7.8.8
![Capture d’écran 2023-02-27 122032](https://user-images.githubusercontent.com/126564789/221823228-290979a8-70bc-43fe-ace7-6e8105241813.png)

### Steps to reproduce

Bonjour,
j'ai un problème avec la mise à jour de Prestashop on utilisant le 1-click upgarde pour passer de la version 1.7.8.6 à 1.7.8.8
![Capture d’écran 2023-02-27 122032](https://user-images.githubusercontent.com/126564789/221823672-c5d8b723-e4d6-4d14-8c5d-23edcb34645c.png)

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4.32

### If your bug is related to a module, specify its name and its version

1-CLICK UPGARDE

**Comment by hibatallahAouadni** [comment]
Hello @educatif 

Please send your request in English. English is the norm on GitHub.
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must respect the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

PS: click on "Save" button, then the page will be refreshed and that part will change.

Thank you

**Comment by educatif** [comment]
je n'ai pas compris comme reproduire le problème
