### ISSUE TITLE
Order message: no Mail client

### ISSUE THREAD

**Issue by Niamor13** [PrestaShop/PrestaShop#31565]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When a customer leaves me a message on his order tracking page, I do receive a notification by email (with subject: Message from a customer....). However the reverse does not work, that is to say that when I write a message on an order the customer does not receive a notification by email.

Test email configuration in advanced settings / email : is ok
( Configuration SMTP is ok )

![Capture d’écran 2023-02-28 111053](https://user-images.githubusercontent.com/126564494/221824181-797aed83-8f2e-4517-80a1-5d5285a28f33.png)

### Expected behavior

The customer receives an notification email when I write a comment in the order.

### Steps to reproduce

1 : Select a order
2 : Write comment in the order and select " Show to customer "
3 : Send message

### PrestaShop version(s) where the bug happened

1.7.6.5

### PHP version(s) where the bug happened

7.3.33

**Comment by HanaRebaiQA** [comment]
Hello @Niamor13 

Thanks for your report.
I should ping @PrestaShop/product-team Could you please confirm what is the expected behavior? And, if it's really an issue ?

Thank You!

**Comment by Niamor13** [comment]
Hello @HanaRebaiQA 
I confirm the expected behavior. This is actually a bug as the client should receive a notification.

**Comment by MatShir** [comment]
It seems to be bugged, if the email is not sent after sending a message to the client from the order page and the emails are nicely configured.

**Comment by MatShir** [comment]
To double-check, we can test in local @HanaRebaiQA :)

**Comment by florine2623** [comment]
I can't reproduce your issue.

The email is sent to the customer when the merchant answers the customer :
<img width="588" alt="Screenshot 2023-04-06 at 09 26 47" src="https://user-images.githubusercontent.com/16019289/230305306-f1bfe2c9-5b24-46ca-a86c-7f333aa8cfd4.png">
<img width="1027" alt="Screenshot 2023-04-06 at 09 28 47" src="https://user-images.githubusercontent.com/16019289/230305630-d1dc4b54-106f-4d96-ae17-3e4c634c4289.png">


The customer can also see the message in his order details :
<img width="771" alt="Screenshot 2023-04-06 at 09 26 24" src="https://user-images.githubusercontent.com/16019289/230305491-5d7303ba-f129-49ba-b14a-19f984dc4233.png">

The feature works as expected.

So I close the issue.
Thanks!

**Comment by MatShir** [comment]
@Niamor13 it seems the issue doesn't come from the software. Please contact [an expert](https://www.prestashop-project.org/support/) to help you to solve the problem in your environment.
