### ISSUE TITLE
BO - Features - Exception when editing a feature

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#31572]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

An exception is displayed when I edit a Feature :
`An unexpected error occurred. [PrestaShop\PrestaShop\Core\Domain\Feature\Exception\InvalidFeatureIdException code 0]: Invalid feature id '1' supplied. Feature id must be positive integer.`

<img width="1440" alt="Screenshot 2023-02-28 at 16 43 13" src="https://user-images.githubusercontent.com/16019289/221903784-ad71f788-5354-4c66-8cdc-e9c123a461e5.png">

https://user-images.githubusercontent.com/16019289/221903805-faae2a9d-6f7d-4034-8f97-a2f5f5bdb821.mov

This is a regression found by @nesrineabdmouleh .
On 8.0.x, it works properly.

### Expected behavior

The edition should be successful

### Steps to reproduce

1. Go to BO > Catalog > Attributes & Features > Feature tab
2. Edit a Feature
3. Save
4. See error :x:

### PrestaShop version(s) where the bug happened

8.1.x, develop

### PHP version(s) where the bug happened

8.1

**Comment by djoelleuch** [comment]
Hello @florine2623 ,

Thank you for your report, I reproduce the issue with Develop and not with the version 1.7.8.8 as you can see :

**with develop :** 

[devFLORINE.webm](https://user-images.githubusercontent.com/115152460/222100010-78f03f1a-fd44-4811-ba77-0c0b85be9cc5.webm)

**with 1.7.8.8**  

https://user-images.githubusercontent.com/115152460/222100157-6eec84a9-c411-47b1-bc0f-9e21fd066df0.mp4

Nice catch ! It's a regression ! 
thank  you

**Comment by lartist** [comment]
Hi @florine2623 and @djoelleuch, I didn't succeed to reproduce the bug in 8.1.x. Maybe it has been solved in another PR. Can you confirm the PrestaShop version where the bug occurs in please?

**Comment by lartist** [comment]
@boherm already fixed it here https://github.com/PrestaShop/PrestaShop/pull/31682
I think we can close this issue
