### ISSUE TITLE
Module update's changelog is out of order

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/PrestaShop#31581]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

![obraz](https://user-images.githubusercontent.com/5007456/222101169-aaf0114f-7f94-4f9d-b32a-b48f10a1ad41.png)

### Expected behavior

Changelog should be in descending order and mark changes relevant to the update.

### Steps to reproduce

1. Go to Modules > Module manager : Updates tab
2. If there's update available for modules like ps_mbo, ps_metrics or ps_facebook there also should be changelog available.

### PrestaShop version(s) where the bug happened

1.7.8, 8.0

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_mbo

**Comment by HanaRebaiQA** [comment]
Hello @SharakPL 

Thanks for your report.
I have checked your steps to reproduce on **PS1788** for example, and I have the changelog on **ps_facebook** (example) in the Updates tab. See these screenshots : 

![image](https://user-images.githubusercontent.com/92912932/222403631-d7d46884-eedd-4a4a-b955-fc48af280a24.png)


![image](https://user-images.githubusercontent.com/92912932/222403269-2f4f8f13-8daa-46d3-8fdf-fb16e6f9650b.png)

https://user-images.githubusercontent.com/92912932/222403885-9e300f98-b289-46e9-ace5-2ddc492435bf.mp4

Could you please check again ? Did I miss something?

Thank You!

**Comment by SharakPL** [comment]
No @HanaRebaiQA , you didn't miss anything :) If you look closer on Prestashop Marketplace update changelog you'll see version 2.x.x and 4.x.x mixed up. Probably because it's sorted by date by default and v.2 is still being developed along v.4 https://github.com/PrestaShopCorp/ps_mbo/releases
IMO this changelog should be ordered by version, especially that on 1.7 you can't even install v.4:
https://github.com/PrestaShopCorp/ps_mbo/blob/bea35f8bbd7bf0c6e1d77b39b0b969f3dca4b01f/ps_mbo.php#L107-L108

![obraz](https://user-images.githubusercontent.com/5007456/222433595-9d2d4f9b-b2ea-4f53-8e4e-5d39af10db91.png)

v.4 changelog is irrelevant at this point. In this case changes from 2.0.3 to 2.1.0 should be emphasized to know what the update will actually do. Or better yet, changes irrelevant to the update shouldn't be loaded at all. Instead maybe only a small info about new version available, but requiring newer version of Prestashop.

I guess it would be more of an improvement than a bug fix ;)

**Comment by HanaRebaiQA** [comment]
Thanks @SharakPL for your response!
I'll ping the @PrestaShop/product-team What do you think about this issue and @SharakPL 's feedback already?

**Comment by kpodemski** [comment]
I don't think it's relevant for the open-source project because module authors from the community - probably - don't have a way to provide a changelog (I might be wrong).

**Comment by MatShir** [comment]
Maybe there are some improvement to do. Apple Store for ex have a dedicated list with each release. It may help, so they don't have to push all the changelog of all the version all the time and to help them to handle it better? 🤷

**Comment by SharakPL** [comment]
I think they already have improved it by removing changelog completely from updates list. Now it's a **Read more** button that loads whole module card:

https://user-images.githubusercontent.com/5007456/225578684-dc4b052f-52fb-4b3a-85f0-12cc9c899550.mp4


But what about this one? Seems useless now.
https://github.com/PrestaShop/PrestaShop/blob/28aa6c21f3b76b3587dc0dc11cc80757d9fcfd18/src/PrestaShopBundle/Resources/views/Admin/Module/Includes/card_notification_update.html.twig#L34-L48

**Comment by kpodemski** [comment]
@SharakPL yes, I think it can be removed in v9
