### ISSUE TITLE
The footer has too many interactive buttons (most buttons should be in dropdown)

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#31586]
## US

- The footer has too many interactive buttons (most buttons should be in dropdown)
- Height of the footer to be set at 56px

## Acceptance test
When the product page is displayed, the footer only contains:
- go to catalog
- Save and publish
- Cancel
- 3 dot button (containing: add new product, delete, duplicate and Preview)
The height is adjusted, so we can save some little bit space

**Comment by jolelievre** [comment]
Closed by https://github.com/PrestaShop/PrestaShop/pull/31584

**Comment by Hlavtox** [comment]
So the result of the recent fixes...

On desktop, all buttons are stashed and I need to do an extra click. While there is more than enough space to display the buttons.
![Snímek obrazovky 2023-03-28 110816](https://user-images.githubusercontent.com/6097524/228187748-ecd22184-78cd-4172-94b1-2aae76652d17.jpg)

On mobile, still broken.
![Snímek obrazovky 2023-03-28 110834](https://user-images.githubusercontent.com/6097524/228187751-3150e44a-57d8-4ed9-9f70-ba8153d4c34b.jpg)

Also:
- It was the mobile only that should have been optimized, not adding extra click on desktop.
- Why the most useless button "Go back to catalog" is the only one visible on the left and taking most space?
