### ISSUE TITLE
UI mobile on the new product page

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#31589]
## Mockups:
![image](https://user-images.githubusercontent.com/43613217/222147608-5b2f9e28-2cd0-4a70-adac-5318b7df04e0.png)

- Apply modification of display for the header based on the mockups
- We hide the references in the header in mobile
- In mobile don't make for now the header sticky
- The actions present next to the tabs (sales, product list, ...) should be accessed in the header (see if it implies having two sets of buttons that switch, or if it should always be in the header)
- put the all the buttons in the dropdown in the footer in desktop and mobile view except for 'go to catalog', 'cancel' and 'save and published' (should be most handled for desktop mode already)
- Make the cancel button as an icon in mobile view
- make the tab sticky in the header if possible (NTH)

## Combination modal

- Hide the 'Edited combination'
- The button 'Next combination >' become '>'
- The button '< Preview combination' become '<'

## Combination List

- Combinations list has a Horizontal scroll bar 
- Min size for the column 

## Footer

The footer has too many interactive buttons (most buttons should be in dropdown)

### Acceptance test
When the product page is displayed on mobile without any modification, the footer only contains:
- go to catalog
- Save and publish
- 3 dot button (containing: add new product, delete, duplicate and Preview)

When the product page is displayed on mobile with one modification, the footer only contains:
- Cancel 
- Save and publish

**Comment by WahbiPS** [comment]
Fixed with this PR https://github.com/PrestaShop/PrestaShop/pull/31968
