### ISSUE TITLE
Can't Create Order in BO when virtual product is in cart and customer address is from a Country that is not served by a carrier

### ISSUE THREAD

**Issue by cquintini** [PrestaShop/PrestaShop#31594]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In front office customers can complete orders for digital products even if their address country is not served by any carrier, it just requires to the country to be enabled.   When triying to do the same in the BO you are unable to create the order because it says "No carrier can be applied to this order" 

![image](https://user-images.githubusercontent.com/13757587/222273787-cbd232ae-1ae5-4533-a09b-12f841b75be5.png)

### Expected behavior

It is expected to have the same behavior as in the front office where you are able to create an order for a virtual product even if the customer country address  is not served by any carrier.

### Steps to reproduce

1. Create a Virtual product 
2. Remove the country of your choice from all the enabled carriers  in the store.
3. Go to Orders
4. Click Add new order
5. Select customer
6. select/add an address which uses the country you choose in step 2.
7. add a virtual product to the order
8. once you are here you wont be able to proceed to create the order

### PrestaShop version(s) where the bug happened

1.7.x -  8.1.x

### PHP version(s) where the bug happened

7.4

**Comment by HanaRebaiQA** [comment]
Hello @cquintini 

Thanks for your report.
Is your issue similar to this one #20636 ?

**Comment by cquintini** [comment]
Hello @HanaRebaiQA no, it is a completely different issue.  I will Record a Loom later so you can have more details about it.

**Comment by cquintini** [comment]
https://www.loom.com/share/316fa3207d384929b98d6902f4b1499b

**Comment by florine2623** [comment]
Hello @cquintini ,

I have this error message, is it the same as yours ?
<img width="1227" alt="Screenshot 2023-03-03 at 16 54 32" src="https://user-images.githubusercontent.com/16019289/222766225-060a4927-f0d6-475f-bc22-6063322de7ef.png">

Waiting for your feedback.
Thanks!

**Comment by cquintini** [comment]
@florine2623 No, the message I get is that there are no carriers available to fulfill the shipment, even though it is a virtual cart that does not require physical delivery.

**Comment by AureRita** [comment]
Hi @cquintini 

Thank you for your issue and your video, I reproduce the issue with PrestaShop version 1.7.8.8 as you can see here : 

[Untitled_ Mar 6, 2023 11_56 AM.webm](https://user-images.githubusercontent.com/100699445/223091681-66467118-d475-44e3-af00-96016192c95f.webm)

I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks

**Comment by cquintini** [comment]
@AureRita here is the PR with the fix #31621
