### ISSUE TITLE
BO - Voucher is displayed in tax excluded while it's saved as tax incl

### ISSUE THREAD

**Issue by RosaBenouamer** [PrestaShop/PrestaShop#31605]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I click on VAT included and click on "Save"
The value stay VAT excluded
![image](https://user-images.githubusercontent.com/124665010/222447618-b58ce0a9-a106-485e-b7e1-50342b0f7073.png)

In the customer parameter the default value is included
![image](https://user-images.githubusercontent.com/124665010/222448521-4f0678e8-7224-42b2-9891-ccd997cf710b.png)

### Steps to reproduce

1. Create an Order
2. Change the order status to payment aceepted
3. Click on Partial refund
4. add the quantity 1 to one product
5. uncheck the options re-stock the product and create credit slip
6. check the option create a voucher
7. Click on Partial refund button
8. Catalog>Discounts> Edit the voucher
9. Check the Actions tab
10. See error > the tax is execluded

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.1.9

**Comment by florine2623** [comment]
Hello @RosaBenouamer ,

Can you share the step to create the Discount ?
The order created should have a minimum amount or not ?

<img width="1221" alt="Screenshot 2023-03-03 at 14 07 48" src="https://user-images.githubusercontent.com/16019289/222728025-fa4ade21-b2a8-47a2-8797-e8c84737df6b.png">

Waiting for your feedback, thansk

**Comment by RosaBenouamer** [comment]
Hello @florine2623,

You don't have to create a discount just to follow the step.

1. Create an Order
2. Change the order status to payment aceepted
3. Click on Partial refund
4. add the quantity 1 to one product
5. uncheck the options re-stock the product and create credit slip
6. check the option create a voucher
7. Click on Partial refund button
8. Catalog>Discounts> Edit the voucher
9. Check the Actions tab
10. See error > the tax is execluded

We have create this issue with @hibatallahAouadni
The issue is only on my shop not in her shop. It seems to be specifical.
We have create an issue in case in someone else have the same issue.

**Comment by AureRita** [comment]
Hi @RosaBenouamer 

Thank you for your issue, despite my effort, I can't reproduce your issue as you can see : 

[Untitled_ Mar 6, 2023 11_33 AM.webm](https://user-images.githubusercontent.com/100699445/223086395-4a76346f-0f1b-436f-9213-57503576390f.webm)

did I miss something ? 

Waiting for your feedback

**Comment by RosaBenouamer** [comment]
Hello @AureRita 
Your process is the good one. I am the only one to have this problem. I don't know why. Perhaps let the issue open in case of someone else have the same one ? Or how do you prefer process ?

**Comment by AureRita** [comment]
We will see if other QA can reproduce this issue : 
ping @PrestaShop/qa-team , anyone can reproduce the issue ?

**Comment by djoelleuch** [comment]
Hello @RosaBenouamer  , 
we were not able to reproduce your issue with the provided information.
![image](https://user-images.githubusercontent.com/115152460/223476583-b6c06d5e-5086-48c7-9755-cc1f609944b1.png)

We will see if the @PrestaShop/prestashop-core-developers can reproduce it .
thanks !

**Comment by RosaBenouamer** [comment]
Thank you for your (@djoelleuch @AureRita @florine2623 ) help. I will close the issue because it seems to be specific to my configuration... :-)
