### ISSUE TITLE
Multistore - Special characters in URL break your shop in BO and FO

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#31607]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you set the url of your shop, if you put a special character, like é"'(-è_ç, this will break your shop and you can't acces to it anymore, except if you delete the .htacess files. If you do it, you'll have only one try to modify your url name. You can see it and this video : 

[Untitled_ Mar 2, 2023 4_35 PM.webm](https://user-images.githubusercontent.com/100699445/222474998-7db2aba8-c46c-4106-b1f3-be1e957ff5ae.webm)

### Expected behavior

I wish that my shop will not be broken

a solution possible : 

special character is not allowed for the url 

### Steps to reproduce

1. Go to BO > Shop Parameters > General 
2. Enable Multistore 
3. Go to Advanced Parameters > Multistore
4.  Clic on "Add a new shop" 
5. Set a "Shop name" and save 
6. Clic on it url link named " Click here to set a URL for this shop. " 
7. On "virtual url" put some special character : "'(-è_çà
8. TAAADAAA, your shop is broken

### PrestaShop version(s) where the bug happened

1.7.8.8 - 8.0.0 - 8.0.1 - develop 

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment]
Hello @AureRita ,

I reproduce the issue, I'll add this to the backlog so it can be fixed.

<img width="1050" alt="Screenshot 2023-03-03 at 09 44 16" src="https://user-images.githubusercontent.com/16019289/222673902-1ccdf349-6c32-4a37-a599-dd7182f4bfa1.png">


Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
