### ISSUE TITLE
As a merchant I want to know what is tracked during modules installation (disable by env)

### ISSUE THREAD

**Issue by fabienvallon** [PrestaShop/PrestaShop#31627]
As a merchant I want to be informed what data are tracked in the software during modules installation 

## Context

When prestashop is being installed, the project wishes to collect the shop (being installed) URL and the version of PrestaShop being used.
The user must be given a way to disable the data collection.

Data collection mechanism was introduced in https://github.com/PrestaShop/ps_distributionapiclient/pull/15 but removed in https://github.com/PrestaShop/ps_distributionapiclient/pull/19 as we considered it needed some improvements (like this one).

Revert PR https://github.com/PrestaShop/ps_distributionapiclient/pull/19 was done in order to allow releasing ps_distributionapiclient 1.0.3 without an incomplete tracking mechanism (incomplete = cannot opt-out).

## Business rules

- The data collection mechanism introduced in https://github.com/PrestaShop/ps_distributionapiclient/pull/15 should be put back in place
- It however could be disabled using a [environment variable](https://en.wikipedia.org/wiki/Environment_variable) PS_URL_TRACKING

- if PS_URL_TRACKING is not set, then data collection happens
- if PS_URL_TRACKING is set to `true`, then data collection happens
- if PS_URL_TRACKING is set to `false`, then data collection should be disabled (using a worldly famous `if` 😄 )

**Comment by Progi1984** [comment]
@fabienvallon When you write "the project wishes to collect the shop", do you say that only PrestaShop Project Members will have access to this data collection ?

**Comment by MatShir** [comment]
It was flagged as 'Done'. What is it left to do @jolelievre ?

**Comment by jolelievre** [comment]
Well everything, the initial PR https://github.com/PrestaShop/ps_distributionapiclient/pull/15 was reverted by https://github.com/PrestaShop/ps_distributionapiclient/pull/19

So the feature must be added again but with the opt-out feature handled by `PS_URL_TRACKING `
