### ISSUE TITLE
As a merchant I want to know what is tracked during the modules installation step (installer)

### ISSUE THREAD

**Issue by fabienvallon** [PrestaShop/PrestaShop#31625]
As a merchant I want to be informed what data are tracked in the software during modules installation 

## Context

When prestashop is being installed, the project wishes to collect the shop (being installed) URL and the version of PrestaShop being used.
Even if this is compliant with GDPR we wish the user to be fully informed.

## Business rules

During the shop installation (inside installer) - Step 2  (license) 
Add 
- A specific Title (legal information <- Need wording ) 
- A textfied  (need wording)  with 
     - a message / text : it should warn the user that the shop URL will be collected  (need wording) 
     -  add a link to a specific webpage on https://www.prestashop-project.org/ (see https://github.com/PrestaShop/open-source/issues/166)

## Wording

Provided directly in PR by @l-delin : https://github.com/PrestaShop/PrestaShop/pull/31697#issuecomment-1466090061

**Comment by Progi1984** [comment]
Like `PS_URL_TRACKING` is an environment variable, why not add a checbox for enable it ?

**Comment by RosaBenouamer** [comment]
@fabienvallon : ajouter la condition

**Comment by matks** [comment]
Hello there I see this ticket has label "Ready" but I think it is not ready: before a developer can implement this, we need
- the title
- the text
- the location (even broad) where to put the text inside the Step 2 Installer: at the top? middle ? bottom ?

**Comment by matks** [comment]
I mark the issue Ready because missing specs have been added... in the PR 😆 https://github.com/PrestaShop/PrestaShop/pull/31697
