### ISSUE TITLE
Irrelevant issue

### ISSUE THREAD

**Issue by Gruttersshop** [PrestaShop/PrestaShop#31648]
Hi @Gruttersshop. I think you should start a topic about it in **Discussions** section first, because adding bunch of `todo`s and few columns to the database tables won't change a thing and is not a valuable addition to the project.

_Originally posted by @SharakPL in https://github.com/PrestaShop/PrestaShop/issues/31646#issuecomment-1454669952_
I can't show change if 1st the intallation database is not change. I have already started discussion. and when a change to much you blok me. So some 1 said. do it in little steps. So i start by the 1st step. But you blok it. So how to get to point i can show my work and let it run?? If you can help?? You can see in picture what it's going to look like??
![Store information front](https://user-images.githubusercontent.com/124369064/222902430-fce6c34d-8931-442c-b5aa-1672a8de2613.jpg)
![Store information](https://user-images.githubusercontent.com/124369064/222902433-6d66d5a3-0f6c-4e34-a3a5-5d34497dc7b4.jpg)

**Comment by SharakPL** [comment]
Feel free to add more commits to your PR. I'll change it to draft for now.
