### ISSUE TITLE
Autoupgrade - The contact us block is not displayed after an upgrade from 1.7.8 to 8.0.1/8.0.2

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#31640]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The contact us section is not displayed after an upgrade from 1.7.8.8 to 8.0.1/8.0.2

Thanks to @hibatallahAouadni to also reproducing the issue :) 

**Upgrade from 1.7.8.8 to 8.0.1 : NOK** :x: 

https://user-images.githubusercontent.com/92912932/222747134-596f303b-0a7e-4189-aab5-75193992655e.mp4

**Upgrade from 1.7.8.8 to 8.0.2 : NOK** :x: 

**PS8.0.2 fresh install: OK** :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/92912932/222747407-803ab651-e0f3-4389-b82b-c9121ad335e4.png)

![image](https://user-images.githubusercontent.com/92912932/222747354-4a160eb1-06d8-44fa-952a-ea6e8867f465.png)

It's a regression after the upgrade to 8.0!

### Expected behavior

The contact us block should be displayed after an upgrade from 1.7.8 to 8.0.1/8.0.2

### Steps to reproduce

1. Install 1788 
2. On BO > Marketplace > Install the autoupgrade module v4.15
3. Place the PS8.0.2.zip and 8.0.2.xml under the admin dev > autoupgrdae > download of PS1788
4. On BO > Module manager > Autoupgrade > Click on configure
5. use the local Archive and select the 8.0.2.zip and 8.0.2.xml
6. Do the upgrade
7. Connect to the shop of PS8.0.2
8. GO to FO > Contact US
9. See error > The block is not displayed!

### PrestaShop version(s) where the bug happened

8.0.1, 8.0.2

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

autoupgrade v4.15

**Comment by Hlavtox** [comment]
@PrestaShop/committers This is the exact scenario where we need a hook after upgrade 👍

![Snímek obrazovky 2023-03-03 160924](https://user-images.githubusercontent.com/6097524/222755562-a2ff9b23-7d01-47f9-8b62-8422bd79c380.jpg)

**Comment by kpodemski** [comment]
@Hlavtox no, it should be module job to handle hook registration

**Comment by kpodemski** [comment]
@HanaRebaiQA which version of classic and which version of contactform?

**Comment by Hlavtox** [comment]
@kpodemski The module doesn't know that upgrade passed.

**Comment by HanaRebaiQA** [comment]
@kpodemski The contactform is v4.3.0 and Classic Version 1.0.0

**Comment by kpodemski** [comment]
@HanaRebaiQA classic should be in 2.0.8, are you sure it is 1.0.0?

@Hlavtox but what do you need this  for? module during its upgrade hooks to displayContactFormLeft and Right, Classic should handle display of those. Where's the job for autoupgrade module there?

**Comment by kpodemski** [comment]
@HanaRebaiQA also, you should have contactform 4.4, 4.3 is not the newest version, but it won't be available in Distribution API client until we tag PrestaShop release

in other words: it's not an issue 🤷🏼‍♂️

you can upgrade to 4.4 contactform manually to see if it works

**Comment by Hlavtox** [comment]
@kpodemski `contactform` `4.4.0` is compatible with `1.7.2 `and higher.

You are on `1.7.2`, `contactform` `4.4.0` and you are using widgets to display it.
You upgrade to `8.0.1` and how should the `contactform` know that it should hook itself to the new hooks?

**Comment by HanaRebaiQA** [comment]
@kpodemski Cause this is after the upgrade. That's why we have these versions
But on PS8.0.2 fresh install, the classic theme version is `2.0.6`
The upgrade option is not available for the contactform.

**Comment by kpodemski** [comment]
Ok, after checking situation I can confirm that it's a contactform problem. It should register new hooks. I was sure that's the case already 🙁

**Comment by Steppenw** [comment]
Hello everyone,
I just wanted to confirm that after the update performed today via '1-Click Upgrade' (v1.7.8.8 -> v.8.0.1) the contact form (v4.4.0) does not appear.
Also, the version of the 'Classic' theme is 1.0.0 .
EDIT:
If it helps:
I was using the child theme from the previous version.
I activated the classic theme just to see what happens: now it shows as 'version 2.0.6' and the contact form is displayed...
I really don't know, maybe those who know more than me can interpret it correctly.
