### ISSUE TITLE
OBIOSEED

### ISSUE THREAD

**Issue by groupealtea** [PrestaShop/PrestaShop#31658]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,
On the main page of Prestashop, if I go to Iqit Elementor - Page builder, I can't modify the photo of Acceuil V2
Kindly see the photo atteched.

![altea](https://user-images.githubusercontent.com/127114984/223126164-02220951-779e-4c29-8a7f-fc4bbfaa15f8.png)

### Steps to reproduce

1. go to Iqit Elementor - Page builder
2. click on modify next to ACCUIEL V2
3. Cleck Edit with Elementir (in red)
4. on the topmost right of the image, click modify (in blue)
5. on the leftside, click on Choose Image
6. 
![altea](https://user-images.githubusercontent.com/127114984/223127019-1633e3f1-861e-4e4b-8b05-5a55b86e0a91.png)

### PrestaShop version(s) where the bug happened

1.7.4.4

**Comment by Hlavtox** [comment]
@groupealtea You need to contact the author of your theme, no page builder is a part of Prestashop.
