### ISSUE TITLE
Autoupgrade - An exception is thrown on many pages related to welcome module after the upgrade from 1.7.8 to 8.0.1 and 8.0.2

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#31659]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

An exception is thrown on many pages related to the `welcome` module after the upgrade from 1.7.8 to 8.0.1 et 8.0.2
-Positions page
-Customer Settings > Groups > Add new group OR Edit a group
-When using the search
-Permissions page

**Upgrade from PS1788 to 8.0.2 : NOK** :x: 

![image](https://user-images.githubusercontent.com/92912932/223147456-45aa2ec4-2f70-4105-8162-fd1f80aca809.png)

https://user-images.githubusercontent.com/92912932/223147199-0c661427-3674-442a-9f6b-8a771ab3f7b6.mp4

https://user-images.githubusercontent.com/92912932/223160591-636879f7-ee5a-4f38-ad9a-415d9c87130e.mp4

**Upgrade from PS1788 to 8.0.1 : NOK** :x: 

**Positions :**

https://user-images.githubusercontent.com/92912932/223146660-df603aa6-3ad6-44df-bf58-af07ac9e0113.mp4

**Search :**

https://user-images.githubusercontent.com/92912932/223146795-9f740d9b-f584-410f-a25c-d5ee8497164e.mp4

**Add / Edit new group :** 

https://user-images.githubusercontent.com/92912932/223150646-1c864d5a-64cb-4aea-b360-87be0893f48c.mp4

**Upgrade from PS8.0.1 to 8.0.2 : OK** :heavy_check_mark: 

**Search :**
![image](https://user-images.githubusercontent.com/92912932/223145835-df76c13b-f2c2-412b-9e46-1e69ece39498.png)

**Positions :** 
![image](https://user-images.githubusercontent.com/92912932/223145882-5859723b-f022-4550-9ca6-7bbc6623e2bf.png)

**Add / Edit new group :** 
![image](https://user-images.githubusercontent.com/92912932/223145945-94bafa84-8973-470a-9cf5-cf5fa4b76b3c.png)

**Upgrade from PS1788 to 8.0.0 : OK** :heavy_check_mark: 

https://user-images.githubusercontent.com/92912932/223147378-548c58b8-bda4-43ca-b839-66a68f2cdc33.mp4

**PS8.0.2 fresh install : OK** :heavy_check_mark: 

**Search :**
![image](https://user-images.githubusercontent.com/92912932/223145993-21f7400f-3fc7-4613-8456-916ba356f931.png)

**Positions :** 
![image](https://user-images.githubusercontent.com/92912932/223146038-585180a4-5aaf-41bf-bc54-5a0464c9516b.png)

**Add / Edit new group :** 
![image](https://user-images.githubusercontent.com/92912932/223146065-986460eb-3bbd-4a71-89d9-2d60c52c8acf.png)

Indeed, **it's a regression on PS8.0.1 and PS8.0.2**!

### Expected behavior

No exception should be displayed!

### Steps to reproduce

1. Install PS1788
2. Go to Marketplace > install autoupgrade module v4.15
3. Click on Configure
4. Use the local Archive and select the 8.0.1 OR 8.0.2 .zip
5. Upgrade to 8.0.1 OR 8.0.2
6. After the upgrade > Connect to the 8.0.1 / 8.0.2 shop
7. Go to BO > Design > Positions page 
8. See error > An exception is displayed
9. BO > Shop Parameters > Customer Settings > Groups page > Add new group OR Edit a group
10. See error > An exception is displayed
11. BO > Use the search bar and search for anything (eg:Orders)
12. See error > An exception is displayed
13. BO > CONFIGURE > Team > Permissions
14. See error > An exception is displayed

### PrestaShop version(s) where the bug happened

8.0.1, 8.0.2

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

autoupgrade v4.15

**Comment by AureRita** [comment]
Hi @HanaRebaiQA  ,

I reproduce the issue with PrestaShop version 8.0.1 and not with the version 1.7.8.8 as we can see : 

[Untitled_ Mar 6, 2023 6_15 PM.webm](https://user-images.githubusercontent.com/100699445/223183094-df70a8ea-407c-406d-abd2-395e1af167d1.webm)

 Nice catch ! It's a regression ! I'll add it to the patch backlog.

Please be aware that some issues might take a very long time to be resolved. 

Thank you

**Comment by 0x346e3730** [comment]
What version of the `welcome` module is being used ?
