### ISSUE TITLE
Autoupgrade reports not possible to write to modules folder

### ISSUE THREAD

**Issue by KodeToad** [PrestaShop/PrestaShop#31650]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When attempting a 1-click upgrade as SuperAdmin, it won't continue saying it can't write to the modules folder even though the modules folder has the correct permissions even after disabling the shop and adding the maintenance IP.
![1click-upgrade problem](https://user-images.githubusercontent.com/3880336/222056918-aad918de-5773-4b0a-acb0-3c29eaa68be7.png)
NB! This image shows the shop not in maintenance mode. That is just for reporting purposes. The behaviour is exactly as described even once maintenance mode is enabled.
![find permissions](https://user-images.githubusercontent.com/3880336/222057091-b87544a4-ec90-4e00-95f4-96cdbffee9e7.png)

### Expected behavior

1-click upgrade should know the folder modules is writable and allow the upgrade

### Steps to reproduce

1. Sign into the administration web console
2. Enable maintenance mode and add a maintenance IP
3. Upgrade all modules
4. click 1-click upgrade on the left hand navigation panel
5. Checklist should be all green but it an error is produced falsely claiming the folder modules is unwritable

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.3.31-1~deb10u2

### If your bug is related to a module, specify its name and its version

unknown

**Comment by Hlavtox** [comment]
@KodeToad Autoupgrade is using a built in function called `test_module_dir` in `classes/ConfigurationTest.php`. I have never seen this test fail, I think it's a misconfiguration on your hosting that you are not aware of, but lets find out what is wrong. :-)

If you want to know more, put this code anywhere, in `controllers/front/IndexController.php` for example (homepage).
`dump(ConfigurationTest::test_dir('modules'));`
Then go to `classes/ConfigurationTest`, find `test_dir` function and try to find out where exactly does it return `false` in your case.

Maintenance mode is not related to this test.

**Comment by KodeToad** [comment]
> dump(ConfigurationTest::test_dir('modules'));

How do I observe the output result of this? 
There is nothing in journalctl or /var/log/apache2
What should I be looking for?

```
class IndexControllerCore extends FrontController
{
    public $php_self = 'index';

    /**
     * Assign template vars related to page content.
     *
     * @see FrontController::initContent()
     */
    public function initContent()
    {
        parent::initContent();
        $this->context->smarty->assign([
            'HOOK_HOME' => Hook::exec('displayHome'),
        ]);
        $this->setTemplate('index');
dump(ConfigurationTest::test_dir('modules'));
    }
}
```

**Comment by Hlavtox** [comment]
@KodeToad Just visit a homepage, you should see it. Just dump it anywhere and go investigate that function.

**Comment by KodeToad** [comment]
> Just visit a homepage, you should see it

I don't see a thing in either the shop homepage or the back office

**Comment by Hlavtox** [comment]
@KodeToad Then, you will need a help from some developer. Unfortunately, we can't help more in diagnose platform specific issues. :(

**Comment by KodeToad** [comment]
> we can't help more in diagnose platform specific issues.

I've 1-click upgraded this system twice before without issues. The only other thing I've done is installed official modules.
Now the latest upgrade, collapses in a heap. How is that platform specific?
The instructions you offered didn't go as described. Perhaps you can elaborate more since the code you suggested clearly wasn't being called so maybe it's misplaced or there are some initialisation steps required that weren't mentioned.
Are you sure there isn't anything else you could suggest that might help?

**Comment by Hlavtox** [comment]
@KodeToad 

> I've 1-click upgraded this system twice before without issues. The only other thing I've done is installed official modules.
> Now the latest upgrade, collapses in a heap. 

Yeah, but server configuration could change in the meantime, some OS/apache/plesk/cpanel upgrades were installed, anything.

> How is that platform specific?

No one else reports this error.

> The instructions you offered didn't go as described. Perhaps you can elaborate more since the code you suggested clearly wasn't being called so maybe it's misplaced or there are some initialisation steps required that weren't mentioned.
> Are you sure there isn't anything else you could suggest that might help?

I would like to help you, but I can't offer you more help than hinting to call `ConfigurationTest::test_dir('modules')` and tell me what are the results, this is not a helpdesk. 

If you want to get this resolved, you will need a help of a professional. We cannot fix what we can't reproduce and the issue will be closed.

**Comment by AureRita** [comment]
Hi @KodeToad 

Thank for your report,This issue is too technical for me, ping @PrestaShop/prestashop-core-developers, can someone please reproduce this issue ? 

Thank you @Hlavtox for your help. 

If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

Thanks

**Comment by KodeToad** [comment]
dump(ConfigurationTest::test_dir('modules'));
it just returns true;

**Comment by KodeToad** [comment]
Hi and thanks for your help.
This turned out to be just as you suspected.
I am entirely to blame for not constructing my find statement properly and for not knowing what to expect when troubleshooting php. Thank you @Hlavtox for your help.
For future reference, this is a better find statement:
`find /var/www/prestashop/ \( -not -user www-data -o -not -group www-data -o \( -type d -not -perm -700 \) -o \( -type f -not -perm -600 \) -o -perm /002 \) -exec ls -ld {} \;`
