### ISSUE TITLE
Setting DNI mandatory after address creation launches an exception during checkout

### ISSUE THREAD

**Issue by Codencode** [PrestaShop/PrestaShop#31668]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If for a country there is the mandatory CF field and try to make an order (in the front-office) with an address that has the DNI empty field, the system shows an error that I attach.
![Screenshot 2023-03-07 at 10-22-40 Screenshot](https://user-images.githubusercontent.com/2463965/223379289-ce53d578-4646-4d3c-8978-e5f57ff7e198.png)

### Expected behavior

Error/Alert message inviting the customer to complete all the mandatory fields in the address

### Steps to reproduce

1. Add a product to the cart (no account)
2. Go in the checkout and create an account
3. Add an address, select Italy as a country
4. Save the address (don't complete the checkout, very important)
5. As an administrator (BO), go to back office, International > Country, edit Italy and enable the DNI field as mandatory
6. As the new customer (FO) try to complete the checkout

The problem occurs due to the modification to the **restorePersistedData** method of the Controller **controllers/front/Ordercontroller.php**
Until version 1.7.8.7 of PS the education $ This-> Cartchecksum-> GenerateChecksum ($ cart) Venifa performed only if there were no non-valid addresses, while in 1.7.8.8 this is always performed and therefore one is launched "non -managed" exception

**PS 1.7.8.7**
```

    protected function restorePersistedData(CheckoutProcess $process)
    {
        $cart = $this->context->cart;
        $customer = $this->context->customer;
        $rawData = Db::getInstance()->getValue(
            'SELECT checkout_session_data FROM ' . _DB_PREFIX_ . 'cart WHERE id_cart = ' . (int) $cart->id
        );
        $data = json_decode($rawData, true);
        if (!is_array($data)) {
            $data = [];
        }

        $addressValidator = new AddressValidator();
        $invalidAddressIds = $addressValidator->validateCartAddresses($cart);

        // Build the currently selected address' warning message (if relevant)
        if (!$customer->isGuest() && !empty($invalidAddressIds)) {
            $this->checkoutWarning['address'] = [
                'id_address' => (int) reset($invalidAddressIds),
                'exception' => $this->trans(
                    'Your address is incomplete, please update it.',
                    [],
                    'Shop.Notifications.Error'
                ),
            ];

            $checksum = null;
        } else {
            $checksum = $this->cartChecksum->generateChecksum($cart);
        }

        // Prevent check for guests
        if ($customer->id) {
            // Prepare all other addresses' warning messages (if relevant).
            // These messages are displayed when changing the selected address.
            $allInvalidAddressIds = $addressValidator->validateCustomerAddresses($customer, $this->context->language);
            $this->checkoutWarning['invalid_addresses'] = $allInvalidAddressIds;
        }

        if (isset($data['checksum']) && $data['checksum'] === $checksum) {
            $process->restorePersistedData($data);
        }
    }

```

**PS 1.7.8.8**

```

    protected function restorePersistedData(CheckoutProcess $process)
    {
        $cart = $this->context->cart;
        $customer = $this->context->customer;
        $rawData = Db::getInstance()->getValue(
            'SELECT checkout_session_data FROM ' . _DB_PREFIX_ . 'cart WHERE id_cart = ' . (int) $cart->id
        );
        $data = json_decode($rawData, true);
        if (!is_array($data)) {
            $data = [];
        }

        $addressValidator = new AddressValidator();
        $invalidAddressIds = $addressValidator->validateCartAddresses($cart);

        // Build the currently selected address' warning message (if relevant)
        if (!$customer->isGuest() && !empty($invalidAddressIds)) {
            $this->checkoutWarning['address'] = [
                'id_address' => (int) reset($invalidAddressIds),
                'exception' => $this->trans(
                    'Your address is incomplete, please update it.',
                    [],
                    'Shop.Notifications.Error'
                ),
            ];
        }

        // Prevent check for guests
        if ($customer->id) {
            // Prepare all other addresses' warning messages (if relevant).
            // These messages are displayed when changing the selected address.
            $allInvalidAddressIds = $addressValidator->validateCustomerAddresses($customer, $this->context->language);
            $this->checkoutWarning['invalid_addresses'] = $allInvalidAddressIds;
        }

        if (isset($data['checksum']) && $data['checksum'] === $this->cartChecksum->generateChecksum($cart)) {
            $process->restorePersistedData($data);
        }
    }

```

### PrestaShop version(s) where the bug happened

1.7.8.8, 8.0.x, 8.1.0

### PHP version(s) where the bug happened

7.4, 8.0, 8.1

**Comment by Codencode** [comment]
I solved by adding the following code in the **Cartchecksum::generateChecksum()** method
```

        if (version_compare(_PS_VERSION_, '1.7.8.8', '>=')) {
            $addressValidator = new AddressValidator();
            $invalidAddressIds = $addressValidator->validateCartAddresses($cart);
            
            if (!empty($invalidAddressIds)) {
                return false;
            }
        }
```

Full file:

```

class CartChecksumCore implements ChecksumInterface
{
    public $addressChecksum = null;
    private $separator = '_';
    private $subseparator = '-';

    public function __construct(AddressChecksum $addressChecksum)
    {
        $this->addressChecksum = $addressChecksum;
    }

    /**
     * @param $cart
     *
     * @return string cart SHA1
     */
    public function generateChecksum($cart)
    {
        // **** CUSTOM CODE
        if (version_compare(_PS_VERSION_, '1.7.8.8', '>=')) {
            $addressValidator = new AddressValidator();
            $invalidAddressIds = $addressValidator->validateCartAddresses($cart);
            
            if (!empty($invalidAddressIds)) {
                return false;
            }
        }
        // ***************        
        
        $uniq_id = '';
        $uniq_id .= $cart->id_shop;
        $uniq_id .= $this->separator;
        $uniq_id .= $cart->id_customer;
        $uniq_id .= $this->separator;
        $uniq_id .= $cart->id_guest;
        $uniq_id .= $this->separator;
        $uniq_id .= $cart->id_currency;
        $uniq_id .= $this->separator;
        $uniq_id .= $cart->id_lang;
        $uniq_id .= $this->separator;

        $uniq_id .= $this->addressChecksum->generateChecksum(new Address($cart->id_address_delivery));
        $uniq_id .= $this->separator;
        $uniq_id .= $this->addressChecksum->generateChecksum(new Address($cart->id_address_invoice));
        $uniq_id .= $this->separator;

        $products = $cart->getProducts($refresh = true);
        foreach ($products as $product) {
            $uniq_id .= $product['id_shop']
                . $this->subseparator
                . $product['id_product']
                . $this->subseparator
                . $product['id_product_attribute']
                . $this->subseparator
                . $product['cart_quantity']
                . $this->subseparator
                . $product['total_wt'];
            $uniq_id .= $this->separator;
        }

        $uniq_id = rtrim($uniq_id, $this->separator);
        $uniq_id = rtrim($uniq_id, $this->subseparator);

        return sha1($uniq_id);
    }
}

```

**Comment by florine2623** [comment]
Hello @Codencode ,

This issue is fixed here : https://github.com/PrestaShop/PrestaShop/pull/11726

So I'll close your issue.
Thanks!

**Comment by Codencode** [comment]
Hello @florine2623,
This bug is different from the one fixed in [#11726](https://github.com/PrestaShop/PrestaShop/pull/11726)

The problem occurs if the address already exists (with empty dni field) and occurs from PS version 1.7.8.8 which already includes the changes proposed in [#11726](https://github.com/PrestaShop/PrestaShop/pull/11726)

With the solution I proposed I solved the problem, but I don't know if it can be solved in any other way.

I hope everything is clear.

Thanks!

**Comment by marsaldev** [comment]
Hi @florine2623 !
I've checked the issue, and the report is right.
I tried in 1.7.8.8, 8.0.1, 8.1.0 (develop) and the bug exists.

The steps to reproduce it are very easy:
1. Add a product to the cart (no account)
2. Go in the checkout and create an account
3. Add an address, select Italy as a country
4. Save the address (don't complete the checkout, very important)
5. As an administrator (BO), go to back office, International > Country, edit Italy and enable the DNI field as mandatory
6. As the new customer (FO) try to complete the checkout

@Codencode could you record your screen during the test to reproduce the bug and update the issue description?

Thanks a lot!

**Comment by Codencode** [comment]
Hi @marsaldev,

here is the screen recording of the error

Tranks!

[2023-03-13-15-29-13.webm](https://user-images.githubusercontent.com/2463965/224734207-2e037d05-b5df-4428-9048-df30f79ea508.webm)

**Comment by paulnoelcholot** [comment]
Hello @Codencode,

I reproduce the issue with PrestaShop versions 1.7.8.8, 8.0.1 and 8.1.0 , I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

1.7.8.8 = NOK
![image](https://user-images.githubusercontent.com/112863083/224972270-7a82b783-55dd-4fe3-9676-642da436f940.png)

8.0.1 = NOK
![image](https://user-images.githubusercontent.com/112863083/224973503-c1b17c94-4436-43f9-b1b8-4341ea4d20c6.png)

8.1.0 = NOK
![image](https://user-images.githubusercontent.com/112863083/224974066-aa90ac96-5e2c-452f-8517-d89158cb6a2c.png)

**Comment by Codencode** [comment]
Hello @paulnoelcholot  
I solved for my customers and I also attached my solution.

Thank you
