### ISSUE TITLE
Translation locale override doesn't work if translation is missing for default language

### ISSUE THREAD

**Issue by samaij** [PrestaShop/PrestaShop#31665]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If you pass the optional `$locale` parameter to `trans()`, the function still returns the translation in the default language unless a translation also exists in the default language in the database. So if your default locale is English but you want your translation to always show up in Finnish, the translation needs to exist in both languages in the database for it to show up in Finnish.

### Expected behavior

The translation should be returned in the desired language regardless of whether a translation exists in the default one.

This used to work in PrestaShop versions <8.0.1.

### Steps to reproduce

1. Download and install [this test module](https://github.com/PrestaShop/PrestaShop/files/10901709/localetest.zip)
2. Set your back office language to English
3. Download and install the Finnish language pack OR modify the trans() function call in the test module to use another language that you already have installed
4. Translate the test string (in domain "Modules.Localetest.Test") to Finnish or the language you used for the override (you can translate it to whatever, the string just needs to be different)
5. DO NOT translate the test string in English
6. Go to the test module configuration page and see that the test string is still in English

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

7.2.34

**Comment by djoelleuch** [comment]
Hello @samaij 

I didn't manage to reproduce the issue with PS801, see the attached screenshots below:

![image](https://user-images.githubusercontent.com/115152460/223481614-f03b07ef-ac73-42fe-af59-37a31d3063d5.png)

![image](https://user-images.githubusercontent.com/115152460/223481668-0389a8df-5199-4c2e-b394-51e0664fd0ba.png)

As you can see the test string is well displayed. Did you change your Back Office language to Finnish? 
Otherwise the test string will be always displayed with BO language.

![image](https://user-images.githubusercontent.com/115152460/223482567-16a1eb3a-71fd-4773-b68e-0fc3b332297f.png)

Please check and feedback.

Thanks!

**Comment by samaij** [comment]
Sorry, I was a bit unclear. I'm talking about the fourth parameter of the trans() function:
```php
$this->trans("Untranslated string", [], "Modules.Localetest.Test", "fi-FI");
```
The test string should be in Finnish, no matter what your back office language is set to.

From [docs](https://devdocs.prestashop-project.org/8/modules/creation/module-translation/new-system/):

> $locale – (optional) The locale identifier (eg. “en-US”) if you want to translate in a different language than the current one.

**Comment by AureRita** [comment]
Hi @samaij ,

Thank for your report and your details, I think I reproduce the issue with PrestaShop version 8.0.1, as you can see : 

[Untitled_ Mar 13, 2023 2_29 PM.webm](https://user-images.githubusercontent.com/100699445/224746248-221450ad-589a-495d-ac40-715b401ac29a.webm)


That's the behavior you were talking about ? if yes, I think it's a waiting behavior 

Waiting for your feedback

**Comment by samaij** [comment]
@AureRita That's exactly it. The string should be displayed in French, even when your back office is set to English. 

Now, if you translate the string into English as well, then the French string will be displayed correctly.

**Comment by AureRita** [comment]
Hi @samaij 

For me, because you're not in french, the string shouldn't be translate because you set it in french and not int english. 
I'll put it into need specs. 
@PrestaShop/product-team what did you think about this issue ? 

Waiting for feedback

**Comment by samaij** [comment]
If you want to see how the system should work, you can repeat the test in a v1.7.8 shop.

**Comment by fabienvallon** [comment]
Yes , It is a regression
