### ISSUE TITLE
Upgrade PS_1.7.8.8 to PS_8.0.2 fails with 1-Click Upgrade modul

### ISSUE THREAD

**Issue by madibashop** [PrestaShop/PrestaShop#31679]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I tried to upgrade PS v1.7.8.8 to v8.0.1
PHP: 7.4.3.3
![imatge](https://user-images.githubusercontent.com/125015630/223669456-647ae2e6-ca5d-4459-99ba-709d1c6935da.png)
Database: 5.7.38
![imatge](https://user-images.githubusercontent.com/125015630/223669786-3c33259b-7b45-4c8e-8837-70a2bb418e85.png)
Tema CLASSIC v.1.0.0
![Porta-retalls01](https://user-images.githubusercontent.com/125015630/223670172-c74a0e0c-a7e1-4021-b389-e5289be5f9e6.jpg)

I started upgrade with cache, overrides and not native modules deactivated:
![Porta-retalls02](https://user-images.githubusercontent.com/125015630/223670997-049ad9b1-0da7-4bb9-b5f7-ebafa2ee61ab.jpg)
![Porta-retalls03b](https://user-images.githubusercontent.com/125015630/223671888-cd8426d1-4a00-4d47-beee-f2b5cb562b8e.jpg)
![Porta-retalls04](https://user-images.githubusercontent.com/125015630/223672128-6dd26e09-0f90-496e-8b7c-ad005bf6f2f1.jpg)
![Porta-retalls06](https://user-images.githubusercontent.com/125015630/223672399-9a1af528-a793-461c-bfcd-7ef1f99476b1.jpg)

**And after upgrade 8 ERRORS:**
![Error1](https://user-images.githubusercontent.com/125015630/223673016-09a5bf37-6bef-4782-bbfc-b5ba418d2405.jpg)
![Error2b](https://user-images.githubusercontent.com/125015630/223673695-828a2e38-cc21-45a2-8d64-bf59afca82c0.jpg)

I do not know what it is causing the error. I tried 3 times.

Some ideas:
Can it be related to the contents of the database?
Can the "null" content in some field affect?
What are the conditions that the database must fulfil?

Thanks for your help

### Expected behavior

I expected success upgrade.

### Steps to reproduce

1. Backup copy.
2. Deactive cache, not native modules and overrides.
3. Shop offline.
4. Run 1-Click Upgrade
5. BAD RESULT: 8 errors.

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

1-Click Upgrade v.4.15.0

**Comment by paulnoelcholot** [comment]
Hello @madibashop,

I followed the step to reproduce but I couldn't reproduce the bug. Do you have any additional information to share with us?

![image](https://user-images.githubusercontent.com/112863083/223721988-f6a36d81-f4bc-4b28-988a-011fd23db1a5.png)

Thanks!

**Comment by madibashop** [comment]
I have no more information:
1 Cache offline
2 Override disabled
3 Non native modules disabled

Because this, I think if the database can influence:  Fields with some null content, ... ???

**Comment by hibatallahAouadni** [comment]
Hello @madibashop 

It seems your issue is related to one of your non-native modules, cause I tried on my side with three modules non-native and it works without any errors, check the screen record below:

[upgrade1788-801.webm](https://user-images.githubusercontent.com/23308427/224013839-e1dd2f75-977a-4ee3-b2c3-507573a4cdd1.webm)

BTW, your issue is related to this one #25649 which has been fixed with the 1-ClickUpgrade module v4.15.0
Waiting for your feedback.

Thanks!

**Comment by VIPWebdesign** [comment]
Hi 

I have the same problem with the 5 prestashop sites. I upgrade to the latest 1.7.8.8 version clean chach etc and then i selected major release. I upgrade with 1 click upgrade latest version and the website is crash with error 429 Too Many Requests
nginx the update kills and the website is broken. 
I tryed to install the files with ftp but the omly solutions is restore.

Have anybody an idea?

Regards

Eric

**Comment by madibashop** [comment]
I tried again to update. 
Aside from doing all the above, I manually disabled ALL non-native modules and override.
The update ends with exactly the same errors. Updates the database correctly and fails below without finishing the process.

After that Prestashop works, but has a major problem. Non-native modules can be activated, they seem to be activated, but they don't work. They do nothing, as if they did not exist.

Uninstalling a module, deleting configuration, and reinstalling it does not solve the problem. 
Again: backtrack from backup.

Configuration information is:
![Inf1](https://user-images.githubusercontent.com/125015630/224542670-1277afff-74dd-4821-9c6a-209c7904c97d.jpg)
![Inf2](https://user-images.githubusercontent.com/125015630/224542678-78dd8f12-07d8-416a-99db-70528ee08003.jpg)

**Comment by AureRita** [comment]
Hi @madibashop ,

Thank you for your report and you details. I reproduce the issue with PrestaShop version 1.7.8.8 as you can see 

[Untitled_ Mar 13, 2023 3_39 PM.webm](https://user-images.githubusercontent.com/100699445/224744415-5713bc83-9f1d-4058-97a1-5afbab13db90.webm)


 Nice catch ! It's a regression ! I'll add it to the patch backlog.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by madibashop** [comment]
Someone suggested if the problem was the PS Checkout module. I have again tried to update. This time it is for version 8.0.2.The result has been exactly the same. Same errors:

Database upgrade OK

*********************
errores
*********************

[INTERNAL] 
/homepages/**/**********/******/**************/PrestaShop/**********/src/Core/Addon/Theme/ThemeManager.php line 384 - PrestaShop\PrestaShop\Core\Domain\Theme\Exception\FailedToEnableThemeModuleException: Unfortunately, the module did not return additional details. #0 

/homepages/**/**********/******/**************/PrestaShop/**********/src/Core/Addon/Theme/ThemeManager.php(245): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManager->doEnableModules(Array) #1 

/homepages/**/**********/******/**************/PrestaShop/**********/modules/autoupgrade/classes/UpgradeTools/ThemeAdapter.php(113): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManager->enable('classic') #2 

/homepages/**/**********/******/**************/PrestaShop/**********/modules/autoupgrade/classes/UpgradeTools/ThemeAdapter.php(51): PrestaShop\Module\AutoUpgrade\UpgradeTools\ThemeAdapter->enableTheme17('classic') #3 
 
/homepages/**/**********/******/**************/PrestaShop/**********/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(662): PrestaShop\Module\AutoUpgrade\UpgradeTools\ThemeAdapter->enableTheme('classic') #4 

/homepages/**/**********/******/**************/PrestaShop/**********/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(119): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->updateTheme() #5 

/homepages/**/**********/******/**************/PrestaShop/**********/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(42): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #6 

/homepages/**/**********/******/**************/PrestaShop/**********/***************/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #7 {main}



**I have tried to analyse the first error, but I do not understand the cause of the problem:**

**************************
FIRST ERROR #0:

/homepages/**/**********/******/**************/PrestaShop/**********/src/Core/Addon/Theme/ThemeManager.php line 384

    /**
     * Reset the modules received in parameters if they are installed and enabled.
     *
     * @param string[] $modules
     *
     * @return $this
     */
    private function doResetModules(array $modules)
    {
        $moduleManagerBuilder = ModuleManagerBuilder::getInstance();
        $moduleManager = $moduleManagerBuilder->build();

        foreach ($modules as $moduleName) {
            if ($moduleManager->isInstalled($moduleName)) {
                $moduleManager->reset($moduleName);
            }
        }

        return $this;
    }

**********

FailedToEnableThemeModuleException.php

namespace PrestaShop\PrestaShop\Core\Domain\Theme\Exception;

class FailedToEnableThemeModuleException extends ThemeException
{
    /**
     * @var string
     */
    private $moduleName;

    public function __construct(
        $moduleName,
        $message = '',
        $code = 0,
        $previous = null
    ) {
        parent::__construct($message, $code, $previous);

        $this->moduleName = $moduleName;
    }

    /**
     * @return string
     */
    public function getModuleName()
    {
        return $this->moduleName;
    }
}

*******************************************

I don't know what else I can do.
Thanks!

**Comment by HanaRebaiQA** [comment]
Hello @madibashop 

It seems that your issue is similar to this one #30761 Do you confirm it?

**Comment by madibashop** [comment]
Yes.

My errors are not the same, but it is similar.
I can't update.

Disabling non native modules, cache, override, ... and always same errors:

errores

```
[INTERNAL]
/homepages//****//************/PrestaShop/**********/src/Core/Addon/Theme/ThemeManager.php line 384 - PrestaShop\PrestaShop\Core\Domain\Theme\Exception\FailedToEnableThemeModuleException: Unfortunately, the module did not return additional details. #0

/homepages//****//************/PrestaShop/**********/src/Core/Addon/Theme/ThemeManager.php(245): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManager->doEnableModules(Array) https://github.com/PrestaShop/PrestaShop/pull/1

/homepages//****//************/PrestaShop/**********/modules/autoupgrade/classes/UpgradeTools/ThemeAdapter.php(113): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManager->enable('classic') https://github.com/PrestaShop/PrestaShop/pull/2

/homepages//****//************/PrestaShop/**********/modules/autoupgrade/classes/UpgradeTools/ThemeAdapter.php(51): PrestaShop\Module\AutoUpgrade\UpgradeTools\ThemeAdapter->enableTheme17('classic') https://github.com/PrestaShop/PrestaShop/pull/3

/homepages//****//************/PrestaShop/**********/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(662): PrestaShop\Module\AutoUpgrade\UpgradeTools\ThemeAdapter->enableTheme('classic') https://github.com/PrestaShop/PrestaShop/pull/4

/homepages//****//************/PrestaShop/**********/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(119): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->updateTheme() https://github.com/PrestaShop/PrestaShop/pull/5

/homepages//****//************/PrestaShop/**********/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(42): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() https://github.com/PrestaShop/PrestaShop/pull/6

/homepages//****//*******/PrestaShop///autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() https://github.com/PrestaShop/PrestaShop/pull/7 {main}
```

**Comment by madibashop** [comment]
Update with som errors.
Web is running OK.
