### ISSUE TITLE
If `_PS_MODE_DEV_` = false, the endpoint `/admin-dev/new-api/` returns a 500 HTTP Code

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#31675]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If `_PS_MODE_DEV_` = `true`, the endpoint `/admin-dev/new-api/` returns a 404 HTTP Code.
If `_PS_MODE_DEV_` = `false`, the endpoint `/admin-dev/new-api/` returns a 500 HTTP Code.

### Expected behavior

If `_PS_MODE_DEV_` = `true`, the endpoint `/admin-dev/new-api/` returns a 404 HTTP Code.
If `_PS_MODE_DEV_` = `false`, the endpoint `/admin-dev/new-api/` returns a 404 HTTP Code.

### Steps to reproduce

1. Create a file `config/defines_custom.inc.php`

```php
<?php

define('_PS_MODE_DEV_', false);
```

2. Request https://domain.tld/admin-dev/new-api/
3. The HTTP Code is 500 (and should be 404)

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

7.3

**Comment by paulnoelcholot** [comment]
Hello @Progi1984 

I reproduce the issue with PrestaShop version 8.1.x, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

![image](https://user-images.githubusercontent.com/112863083/223731291-9a444a3b-ab54-4ae6-9baa-61496c8ab4b3.png)

**Comment by Progi1984** [comment]
Fixed with #31511
