### ISSUE TITLE
API : The endpoint /admin-dev/new-api/hook-status/1 without access token returns bad result 

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#31670]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I request the endpoint without access token and result is not conform to the scenario.

https://build.prestashop-project.org/test-scenarios/scenarios/core/functional/api/client-credential-grant-flow/internal-authentification-server/resource-endpoint.html

### Expected behavior

1. Request /admin-dev/new-api/hook-status/1 without access token
2. The response code is 401
3. The response header "WWW-Authenticate" exist
3. The response header "WWW-Authenticate" is equal to "Bearer"

### Steps to reproduce

1. Request /admin-dev/new-api/hook-status/1 without access token
2. The response code is 404
3. The reponse header "WWW-Authenticate" doesn't exists

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

7.3

**Comment by paulnoelcholot** [comment]
Hello @Progi1984,

I followed the step to reproduce but I did not manage to reproduce the bug on 8.1.x, I also tested on develop and I also have a 401. Nevertheless I have a 404 on 8.0.1 .
Do you have any additional information to share with us?

**Comment by Progi1984** [comment]
Thanks @paulnoelcholot.

After a fresh install, that works. Weird. And Sorry.
