### ISSUE TITLE
<PsAccounts> integration: Given context is invalid: "psIs17" is required on ps_accounts (5.3.3)

### ISSUE THREAD

**Issue by masiorama** [PrestaShop/PrestaShop#31684]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, I just upgraded from ps_accounts 5.3.2 to 5.3.3.
The upgrade ended without issues but as soon as I access the config page a red error message is shown:

`<PsAccounts> integration: Given context is invalid: "psIs17" is required`

and no other data is shown

### Steps to reproduce

1. upgrade ps_accounts module
2. access module config page

### PrestaShop version(s) where the bug happened

1.7.7.4

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_accounts

**Comment by PeNov** [comment]
Hello,

I have same problem.
PHP: 7.4.33, PS: 1.7.8.5 + #GHSA-hrgx-p36p-89q4

This problem affects modules: Google and Facebook marketing. 

Changelog is mixed:
![image](https://user-images.githubusercontent.com/38213520/223739554-63aa05ae-e4be-43a2-8a10-23f3f9c7e40f.png)


Thank you
Best regards
PN

**Comment by paulnoelcholot** [comment]
Hello @masiorama,

Can you test again with PHP 7.2 because PHP 7.3 is not compatible with 1.7.7.4

Thanks

**Comment by masiorama** [comment]
> Hello @masiorama,
> 
> Can you test again with PHP 7.2 because PHP 7.3 is not compatible with 1.7.7.4
> 
> Thanks

Hello @paulnoelcholot  , from what I can tell it's not true: https://devdocs.prestashop-project.org/1.7/modules/core-updates/1.7.7/

**Comment by Guillaumelpg** [comment]
Hello, 

Thank you for your feedback. 

The problem has been fixed in version 5.3.4 of the module which was released yesterday. If you have other bugs like this, please contact me here.

**Comment by emmanuelgautier** [comment]
Hello @masiorama,

We have found an issue in the ps_accounts module that causes this error. A new ps_account version v5.3.4 has just been published to fix this issue.

Thank you for your feedback and sorry for the inconvenience caused.

**Comment by masiorama** [comment]
@emmanuelgautier thanks!

**Comment by MatShir** [comment]
thanks @emmanuelgautier for the update. 
Small reminder: the module is not supported by the project open source, but by the PrestaShop company. If you find any issues, don't hesitate to contact the company :)

**Comment by masiorama** [comment]
@MatShir you mean next time I should avoid to open an issue here?

**Comment by MatShir** [comment]
Yes, for commercial services from the company is it more recommended contacting them [here](https://help-center.prestashop.com/en/contact) for a quicker reply :)
Edit: Sometime, it is not very obvious :/
