### ISSUE TITLE
Update product via api Product class setWsPositionInCategory error

### ISSUE THREAD

**Issue by navneet77** [PrestaShop/PrestaShop#31685]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Trying to update product via api gives error in Product class line 7094. 

array_unshift($result, null);
        foreach ($result as &$value) {
            $value = $value['id_product'];
        }

As you can see the first loop will have the $value as null and this gives an error

### Steps to reproduce

Update product using api

### PrestaShop version(s) where the bug happened

8.0.1

**Comment by paulnoelcholot** [comment]
Hello @navneet77 ,

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template and provide clear and concise steps to reproduce the bug**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
