### ISSUE TITLE
The new API is available for everyone with default credential & default API keys

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#31694]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Actually, it's possible to use the new API (there is no Feature Flag for this experimental feature) in developer mode with default credentials (https://github.com/PrestaShop/PrestaShop/blob/8.1.x/app/config/security_dev.yml#L16).

### Steps to reproduce

1. Enable developer mode
2. Target the http://domain.tld/admin-dev/api/oauth2/token with credentials 
```
{
          client_id: 'my_client_id',
          client_secret: 'prestashop',
          grant_type: 'client_credentials',
}
```
3. You obtain a valid access token.

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

7.3

**Comment by AureRita** [comment]
Hi @Progi1984 

Thank for your report, this issue is too technical for me, ping @PrestaShop/prestashop-core-developers, can someone please reproduce this issue ? 

Thanks

**Comment by kpodemski** [comment]
@MatShir @FabienPapet 

we should put it to 8.1 kanban :)

**Comment by jolelievre** [comment]
Closed by https://github.com/PrestaShop/PrestaShop/pull/31874
