### ISSUE TITLE
Problem displaying the wishlist block on the customer info page in the BO

### ISSUE THREAD

**Issue by JoBICHE** [PrestaShop/PrestaShop#31699]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Problem displaying the wishlist block on the customer info page in the BO : Customers/customers => click on a name.
The wishlist block is out of the flex-wrap container.
<img width="1440" alt="Screenshot 2023-03-09 at 14 28 34" src="https://user-images.githubusercontent.com/43602697/224039819-64e4a28a-346e-4a7a-9ced-b16e5c8dc685.png">

### Expected behavior

The wishlist block should be included in the flex-wrap container.

### Steps to reproduce

1. Go to Customers/customers
2. Click on a name
3. Scroll down
4. The wishlist block is at the bottom of the page

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.0

**Comment by florine2623** [comment]
ping @PrestaShop/ux-team ,

wdyt about this design improvement idea ? 

Thanks!

**Comment by Hlavtox** [comment]
@JoBICHE This is expected behavior. The block is displayed full width under the main content, where the hook is present. 🤷‍♂️

**Comment by florine2623** [comment]
@JoBICHE ,

Sorry, actually you need to create a discussion for the improvement ^^
https://github.com/PrestaShop/PrestaShop/discussions
