### ISSUE TITLE
BO: PPV2 - duplicated debugbar

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/PrestaShop#31706]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Modal for combination edit gets separate debugbar in debug mode:

![obraz](https://user-images.githubusercontent.com/5007456/224176254-bae52f92-4ad1-4805-8cd4-1214ff8463cc.png)

### Expected behavior

There should be one debugbar handling whole page

### Steps to reproduce

1. Enable debug mode
2. Edit product with combinations in BO
3. Go to Combinations tab and edit single combination to trigger a modal

### PrestaShop version(s) where the bug happened

8.1.0, develop

### PHP version(s) where the bug happened

8.1

**Comment by AureRita** [comment]
Hi @SharakPL 

Thank you for your report, I reproduce your issue on 8.1.0 as you can see : 

[Untitled_ Mar 13, 2023 6_27 PM.webm](https://user-images.githubusercontent.com/100699445/224780711-a6c1ef20-74c1-4351-8de8-035ad098e070.webm)

But I think it's a desire behaviour because the modal is set with symphony, What did you think @PrestaShop/prestashop-core-developers / @PrestaShop/product-team ? 

Waiting for feedback

**Comment by SharakPL** [comment]
It was discussed on Slack. Modal content is an iframe and thus loads its own debugbar. Problem is this debugbar doesn't work properly. Its features open profiler inside the modal and fail to load assets
![obraz](https://user-images.githubusercontent.com/5007456/224983260-7afbe373-4c0a-45c3-9bd2-61761b43c49d.png)
Although it's not a problem when profiler is opened in new tab (with middle mouse button - scroll click or just using context menu > Open link in new tab) so it's not a big issue after all.

**Comment by florine2623** [comment]
@jolelievre @zuk3975 @0x346e3730 

What do you think about that ?

**Comment by sallemiines** [comment]
Reproduced with 81x and New Product Page

**Comment by jolelievre** [comment]
Hello, this is not a bug

The modal shown here actually includes iframes and loads another page. Since each page has its dedicated debug bar that's why there are multiple twig debug bars displayed. And each one also has its dedicated and relevant information, so we can't change this.

**Comment by florine2623** [comment]
I'm closing this issue as it is not a bug.
