### ISSUE TITLE
Delay to see a promo code in BO and mysql

### ISSUE THREAD

**Issue by synicko** [PrestaShop/PrestaShop#31704]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

- I created a new cart rule
<img width="1375" alt="codePromo" src="https://user-images.githubusercontent.com/108397693/224084259-f941b9d6-adec-44cb-be65-2dfb8679d7f8.png">

- applied it as a customer to an order
<img width="372" alt="codePromoApplied" src="https://user-images.githubusercontent.com/108397693/224084423-e5b86bee-b16b-43c0-9f96-ce1bca1234e1.png">

- checked the order out
<img width="1156" alt="orderConfirmed" src="https://user-images.githubusercontent.com/108397693/224084534-a6c07ddd-fc5c-4f2c-928c-bd0928030219.png">

- I couldn't find any rec in ps_order_cart_rule on mysql
<img width="792" alt="noRec" src="https://user-images.githubusercontent.com/108397693/224084704-89b518fc-9959-40fc-a412-93b3825ec6ba.png">

- as a vendor in the BO, I displayed the order, no promo code there either
<img width="1024" alt="noPromo" src="https://user-images.githubusercontent.com/108397693/224084854-d4fa3cea-c6ad-48d1-b37b-2f5915feec82.png">

- still as a vendor, I added a discount
<img width="680" alt="addDiscount" src="https://user-images.githubusercontent.com/108397693/224084989-9433191d-a803-43d1-b7a5-3326db8c2f28.png">

- only then can I see the first discount applied via the promo code in BO
<img width="1019" alt="promoApplied" src="https://user-images.githubusercontent.com/108397693/224085164-5628408d-2b07-4f53-9fc4-851451cfb479.png">

- and in mysql
<img width="1164" alt="recsInDB" src="https://user-images.githubusercontent.com/108397693/224085223-48b0af6a-78e9-4d7b-84ed-71c3e7d2ce77.png">

### Expected behavior

The promo code should appear in mysql ps_order_cart_rule as well as in BO as soon as the order is checked out

### Steps to reproduce

1. create a new cart_rule
2. create an order as a customer
3. apply the promo code when checking out
4. check in BO and in mysql, no rec in ps_order_cart_rule and no promo code displayed
5. as a merchant, add a new discount to the order
6. check in BO and in mysql, boths discounts now appear

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.1.9

**Comment by hibatallahAouadni** [comment]
Hello @synicko 

Thanks for your reporting the issue and for your patience :pray: 
I didn't manage to reproduce the issue following your steps with PS801, see the attached screenshots below:

- apply the promo code when checking out

![image](https://user-images.githubusercontent.com/23308427/225330171-0e57b895-1bab-4b3f-8e5c-32dce790cbdb.png)

- check in BO and in mysql, no rec in ps_order_cart_rule and no promo code displayed: :x: 

![image](https://user-images.githubusercontent.com/23308427/225330219-2f5d9e58-8bb0-494b-891d-894e7514d5a0.png)

Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @synicko 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
