### ISSUE TITLE
Seems that new ps_googleanalytics module v4.2.0 don’t measure (not switching js script)

### ISSUE THREAD

**Issue by PeNov** [PrestaShop/PrestaShop#31715]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello @Hlavtox 

Seems that new module does not change script to **gtag/js**
but still remain on the universal setting: **analytics.js**

![image](https://user-images.githubusercontent.com/38213520/224291380-4b22810d-f7fd-47e6-ba55-59056f21fb9f.png)

Examples:
**Setting for UA:**
![image](https://user-images.githubusercontent.com/38213520/224291518-88f036f8-1d1f-45ec-baca-689c96334fca.png)

Result in the FO:
![image](https://user-images.githubusercontent.com/38213520/224291622-ff13f63c-0cbf-4674-b45d-dbbb62792b4f.png)

**Setting for the GA4:**
![image](https://user-images.githubusercontent.com/38213520/224291992-c39ad7f3-1783-4319-a25a-dbed9fba600e.png)

Result in the FO:
![image](https://user-images.githubusercontent.com/38213520/224291867-dbc9a8e2-2378-4e11-970b-0b3722440917.png)

Thank you
Best regards
PN

### Steps to reproduce

Described above.

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

 ps_googleanalytics

**Comment by Hlavtox** [comment]
Ahoj @PeNov :-), you are using some overrides of the module template, probably coming from a cookiebar module. There is no such thing as `data-cookiecategory="analytics"` in the template - https://github.com/PrestaShop/ps_googleanalytics/blob/dev/views/templates/hook/ps_googleanalytics.tpl.

I am using it on all my client's stores and it's working perfectly.

Try to check if there are no overrides in your `themes/themename/modules/ps_googleanalytics/views/templates` and also check your other modules if they are not messing with the module. I will close it for now, if you don't find the issue, contact me on Slack. 😎

**Comment by PeNov** [comment]
Hello @Hlavtox,

you are right. Problem was here:
![image](https://user-images.githubusercontent.com/38213520/224297440-d49086e9-a478-4b48-9b4e-25fe4af2b558.png)

this location contain old files. Must be updated to new files from the version 4.2.0.

Sorry and thank you for the support.
PN
