### ISSUE TITLE
ps_imageslider: relative links are broken

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/PrestaShop#31721]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Relative links, eg. `/content/4-about-us`, set as slide's url are broken. On the FO the link is `http:///content/4-about-us` which doesn't work.

### Expected behavior

The link without changes should be used in this case `/content/4-about-us` or it should simply add base url in front `http://myshopdomain.com/content/4-about-us`

### Steps to reproduce

1. In BO go to Modules > ps_imageslider
2. Edit the slide with relative url eg. `/content/4-about-us`
3. Check the link set on this slide in FO.

### PrestaShop version(s) where the bug happened

1.7, 8.x

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_imageslider

**Comment by AureRita** [comment]
Hi @SharakPL ,

I reproduce the issue with PrestaShop version 1.7.8.8, as you can see : 

[Untitled_ Mar 13, 2023 6_20 PM.webm](https://user-images.githubusercontent.com/100699445/224778244-acbe5c37-b8b6-451f-ba40-7fe20079a888.webm)

 I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. 

Thank you for your PR :rocket: 

Thanks
