### ISSUE TITLE
Incorrect condition disallows use of index `date_add` on table `ps_connections`

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#31727]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The display of the Carts page in the BO takes a lot of time (often it delays after the timeout of 300 s). The query used is 

```
SELECT a.`id_cart`, a.`date_add` AS `date_add` , CONCAT(LEFT(c.`firstname`, 1), '. ', c.`lastname`) `customer`, a.id_cart total, ca.name carrier, o.id_order, IF ( IFNULL(o.id_order, 'Non commandé') = 'Non commandé', IF(TIME_TO_SEC(TIMEDIFF('2023-03-03 09:08:00', a.`date_add`)) > 86400, 'Panier abandonné', 'Non commandé'), o.id_order ) AS status, IF(o.id_order, 1, 0) badge_success, IF(o.id_order, 0, 1) badge_danger, IF(co.id_guest, 1, 0) id_guest, shop.name as shop_name 
FROM `ps_cart` a 
LEFT JOIN ps_customer c ON (c.id_customer = a.id_customer) 
LEFT JOIN ps_currency cu ON (cu.id_currency = a.id_currency) 
LEFT JOIN ps_carrier ca ON (ca.id_carrier = a.id_carrier) 
LEFT JOIN ps_orders o ON (o.id_cart = a.id_cart) 
LEFT JOIN ( SELECT DISTINCT `id_guest` FROM `ps_connections` 
WHERE TIME_TO_SEC(TIMEDIFF('2023-03-03 09:08:00', `date_add`)) < 1800 ) AS co ON co.`id_guest` = a.`id_guest` 
LEFT JOIN `ps_shop` shop ON a.`id_shop` = shop.`id_shop` 
WHERE 1 AND a.id_shop IN (20) ORDER BY a.id_cart DESC LIMIT 0, 50;
```
Notice the inner select `SELECT DISTINCT id_guest FROM ps_connections WHERE TIME_TO_SEC(TIMEDIFF('2023-03-03 09:08:00', date_add)) < 1800`. The table ps_connections does have an index on the field `date_add`, but with this condition it cannot be used. In fact the calculation must be executed for each of the lines in ps_connections (these can be tens or hundreds of thousnad).

### Expected behavior

The condition in the query should be turned around in a way that the calculation is only done once. For instance: 
```
`date_add` > date_add(now(), interval -30 minute))
```
That way the index `date_add` on the table `ps_connections` can be used and the query time drops into fractions of a second.

### Steps to reproduce

1. In the BO, navigate to `Orders - Carts`
2. Notice that the page takes a long time to load.

Note: my `ps_connections` table has 2M+ rows

### PrestaShop version(s) where the bug happened

8.0.1 and develop

### PHP version(s) where the bug happened

any

**Comment by paulnoelcholot** [comment]
Hello @lmeyer1 ,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by Hlavtox** [comment]
LGTM
