### ISSUE TITLE
Products in the same category v1.0.7

### ISSUE THREAD

**Issue by Peter26100** [PrestaShop/PrestaShop#31734]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Since the update of the module the price and the description are no longer displayed, I saw that other people were also affected by this problem

![Capture444](https://user-images.githubusercontent.com/120638880/224476883-29d7e76b-3cef-4d9a-822d-85b8eafab010.JPG)

prestashop forum :
https://www.prestashop.com/forums/topic/1028248-probl%C3%A8me-daffichage-dans-produits-dans-la-m%C3%AAme-cat%C3%A9gorie/#comment-3437163

### Steps to reproduce

Since the update of the module the price and the description are no longer displayed, I saw that other people were also affected by this problem

![Capture444](https://user-images.githubusercontent.com/120638880/224476883-29d7e76b-3cef-4d9a-822d-85b8eafab010.JPG)

prestashop forum :
https://www.prestashop.com/forums/topic/1028248-probl%C3%A8me-daffichage-dans-produits-dans-la-m%C3%AAme-cat%C3%A9gorie/#comment-3437163

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

Products in the same category v1.0.7

**Comment by Hlavtox** [comment]
Hi @Peter26100, it's working perfectly on default themes, you need to contact the developer of your custom theme.

PS: The module code is nearly the same since 2018 and the thread you sent a link to, was open in 2020, so module updates are not the cause.

![Snímek obrazovky 2023-03-11 141106](https://user-images.githubusercontent.com/6097524/224486497-25a1efd3-ac7d-4fdf-b771-a57d5db8f8e6.jpg)
