### ISSUE TITLE
Dashboardproducts wrongly uses NULL default Category

### ISSUE THREAD

**Issue by lea-BMS** [PrestaShop/PrestaShop#31747]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The Dashboardproducts native module always uses `NULL` as the default Category for products, because of a silent bug only revealed by PHP warnings.

Within early PrestaShop 1.7
```none
PHP Warning: Illegal string offset 'id_category_default'
```
- After @Progi1984  's Patch https://github.com/PrestaShop/PrestaShop/blame/21aa4c7d00b66aef61ca37494e63403ad6e79f9c/classes/Product.php#L7852
```none
PHP Warning:  Trying to access array offset on value of type int
```

The fallback value after the warnings is always `NULL` and it is used to construct the default `new Category` object in the Dashboardproducts module.

### Expected behavior

`Product->getDefaultCategory` may return either a string, an int or an array with an `id_category_default` key, when SQL value is found \(due to another bug in `ProductCore->getDefaultCategory` which uses `Db::getInstance()->getValue` and proceeds like it would return a result array from PDO or MySQLI.

Due to the upstream core bug in the `Product->getDefaultCategory`, the returned value has to be checked for type and handled accordingly. \(_to maintain backward compatibility with the Core bug and plan forward compatibility for when the Core bug patch PrestaShop/PrestaShop#31752 can be merged_).

### Steps to reproduce

1. Open backoffice Dashboard
2. Open server logs and see the PHP Warning

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

dashproducts

**Comment by AureRita** [comment]
Hi @lea-BMS 

Thank for your report, This issue is too technical for me, ping @PrestaShop/prestashop-core-developers, can someone please reproduce this issue ? 

Thanks

**Comment by 0x346e3730** [comment]
Hi @lea-BMS, I tried reproducing your issue on the develop branch but couldn't, I see your PRs are targeting develop branches that is why I did it, have you also experienced the issue on PS 8+ or only on 1.7 ?

**Comment by 0x346e3730** [comment]
I don't reproduce on 1.7.8.x either
![image](https://user-images.githubusercontent.com/28731165/225242160-4c2ed0ae-e1e1-4923-8149-f0996dd771ad.png)

**Comment by lea-BMS** [comment]
> Hi @lea-BMS, I tried reproducing your issue on the develop branch but couldn't, I see your PRs are targeting develop branches that is why I did it, have you also experienced the issue on PS 8+ or only on 1.7 ?

Reproduced it with PS 1.7.8.8 and (php7.2, php7.4). The Warning lands into Apache using php-fpm logs:

Example of what I got in logs:
```none
[Mon Mar 06 14:47:57.396702 2023] [proxy_fcgi:error] [pid #####:tid #####] [client 127.0.0.1:#####] PHP Warning:  Illegal string offset 'id_category_default' in #########/modules/dashproducts/dashproducts.php on line 224
```
Points here: https://github.com/PrestaShop/dashproducts/blob/613479aaee3f03bf0e7c7cff17003dceba565f0f/dashproducts.php#L224
```php
$category = new Category($product_obj->getDefaultCategory()['id_category_default'], $this->context->language->id);
```

Calling `getDefaultCategory()` on the `Product` object instance.
As implemented in PrestaShop 1.7.8.8 https://github.com/PrestaShop/PrestaShop/blob/e664e3d4cd5d59695d207ec186296a1857297da4/classes/Product.php#L7813-L7831
```php
    /**
     * Get the default category according to the shop.
     *
     * @return array
     */
    public function getDefaultCategory()
    {
        $default_category = Db::getInstance()->getValue('
            SELECT product_shop.`id_category_default`
            FROM `' . _DB_PREFIX_ . 'product` p
            ' . Shop::addSqlAssociation('product', 'p') . '
            WHERE p.`id_product` = ' . (int) $this->id);

        if (!$default_category) {
            return ['id_category_default' => Context::getContext()->shop->id_category];
        } else {
            return $default_category;
        }
    }
```
This returns either an array when `$default_category` is `false` \(if `Db::getInstance()->getValue` failed.\),
or a `string` because `Db::getInstance()->getValue` returns a string when Db request succeeds.

When the dashproducts module gets the value back from the PrestaShop's Product object, it index it with the key `'id_category_default'` which makes PHP warns it tries to index a string because `getDefaultCategory` returned a string.

On PrestaShop dev branch, the type of `$default_category;` is cast to an `int` instead of a string for when the Db query succeed, or if the SQL Db Query fails, it fallback to returning an array with an `'id_category_default'` key containing the context's shop's category.

https://github.com/PrestaShop/PrestaShop/blob/4f78450af5154012334046862530889bb6311a77/classes/Product.php#L7852
```php
        if (!$default_category) {
            return ['id_category_default' => Context::getContext()->shop->id_category];
        } else {
            return (int) $default_category;
        }
```
This is also causing a PHP Warning as the dashproducts module expects an array result and tries to index that returned int.

Also reproduced it with php up to 8.1 with dummy codes:

**Before PHPStan (Level 3) on classes**
https://github.com/PrestaShop/PrestaShop/blame/21aa4c7d00b66aef61ca37494e63403ad6e79f9c/classes/Product.php#L7852

**PHP 7.0**
```sh
$ php7.0 -r "\$default_category = '3'; \$val = \$default_category['id_catego
ry_default']; var_dump(\$val);"
PHP Warning:  Illegal string offset 'id_category_default' in Command line code on line 1
string(1) "3"
```

**PHP 7.4**
```sh
$ php7.4 -r "\$default_category = '3'; \$val = \$default_category['id_catego
ry_default']; var_dump(\$val);"
PHP Warning:  Illegal string offset 'id_category_default' in Command line code on line 1
string(1) "3"
```

**After PHPStan (Level 3) on classes**
https://github.com/PrestaShop/PrestaShop/blame/21aa4c7d00b66aef61ca37494e63403ad6e79f9c/classes/Product.php#L7852

```sh
$ php7.4 -r "\$default_category = 3; \$val = \$default_category['id_category
_default']; var_dump(\$val);"
PHP Notice:  Trying to access array offset on value of type int in Command line code on line 1
NULL
$ php8.1 -r "\$default_category = 3; \$val = \$default_category['id_category
_default']; var_dump(\$val);"
PHP Warning:  Trying to access array offset on value of type int in Command line code on line 1
NULL
```

**Comment by 0x346e3730** [comment]
Issue confirmed 👍 ping @AureRita I don't know what is the process with the labels when technically confirming an issue

**Comment by TheEnglishGartner** [comment]
Hi sorry for commenting on this but I have the same in my error logs. Im running PS 8.1.2 and PHP 8.1 please do see below erro log:

<html>
<body>

[proxy_fcgi:error [pid 3258:tid 140156249794304 AH01071: Got error 'PHP message: PHP Warning: Trying to access array offset on value of type int in /home/566272.cloudwaysapps.com/upqgguyrzr............e int in /home/566272.cloudwaysapps.com/upqgguyrzr/public_html/modules/dashproducts/dashproducts.php on line 224', referer: https://den-engelske-gartner-shop.dk/index.php?controller=AdminDashboard&token=bfd1ce547e7590f2ceb7970c196e6220
--
Mon Nov 27 16:25:24.931516 2023


</body>
</html>


Is here a fix for this? 

Best

**Comment by jf-viguier** [comment]
fixed by https://github.com/PrestaShop/dashproducts/pull/50
Can some one change this ?
