### ISSUE TITLE
Currencies : The reset of currency format doesn't work

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#31759]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After editing a currency format with a custom symbol, the reset doesn't work

### Expected behavior

After editing a currency format with a custom symbol, the reset work (the example column is up-to-date).

### Steps to reproduce

Detected by #31761

1. Go to Currencies page
2. Edit the EUR currency
3. Edit the symbol for English (English) language
4. Define with a custom symbol (`@`, for example)
5. Save the modal
6. The currency format example is up-to-date with `@`
7. Save the currency
8. :tada: The currency use the custom symbol
9. Edit the EUR currency
10. Reset the currency format for English (English) language
11. :red_circle: The currency format example is not up-to-date with `€`
12. Save the currency
13. :red_circle: The currency don't use the symbol `€`

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

7.3

**Comment by AureRita** [comment]
Hi @Progi1984  ,

Thank for your report, I reproduce the issue with PrestaShop version 8.1.X and not with the version 8.0.1, as you can see : 

[Untitled_ Mar 13, 2023 6_04 PM.webm](https://user-images.githubusercontent.com/100699445/224774088-d62c25d4-f7a1-4057-83c9-9ea2c3f45ae9.webm)

 Nice catch ! It's a regression ! I'll add it to the patch backlog.

Please be aware that some issues might take a very long time to be resolved.

Thank you

**Comment by RosaBenouamer** [comment]
Hello @Progi1984 
the videos seem to show the same issue that the  #31812 ?
