### ISSUE TITLE
 1-Click Upgrade  prestashop 1.6

### ISSUE THREAD

**Issue by capadif** [PrestaShop/PrestaShop#31779]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

1-Click Upgrade  Le module de mise à jour en 1 clic est à jour (votre version est v4.14.2)   malgré cela  une croix rouge est présente et je peux pas fare la mise a jours de prestashop  1.6.0.14   vers  stable - (1.6.1.24)

### Expected behavior

une fois le module a jours normalement  une croix verte apparait et  nous pouvons poursuivre la mise a jours

### Steps to reproduce

mise a jours 1-Click Upgrade  v4.14.2 

### PrestaShop version(s) where the bug happened

1.6.0.14

### PHP version(s) where the bug happened

5.6

### If your bug is related to a module, specify its name and its version

1-Click Upgrade  v4.14.2

**Comment by paulnoelcholot** [comment]
Hello @capadif,

I regret to tell you that the version of prestashop 1.6 is now obsolete and we no longer deal with bugs related to versions prior to 1.7

In the future, it is also preferable to write the issues in English.

We will close this issue.

Thanks!
