### ISSUE TITLE
Error installing PrestaShop Checkout : PS Account module is needed to continue

### ISSUE THREAD

**Issue by ArchyAzur** [PrestaShop/PrestaShop#31775]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

I use Prestashop 8.0.0 and I have download **Paypal module & Checkout Module** for payment.
But when I try to use the Checkout Module for payment by card, I got this warning :

Checkout can't be configured at the moment
PS Account module is needed to continue

![Gestionnaire de modules • Megasocial - buy likes, views and followers - Google Chrome](https://user-images.githubusercontent.com/88629908/224889319-1b6b163b-40b7-4dcd-8d8f-6732158c4054.jpg)

Can you help me please? 

### Expected behavior

I want to customize and use the prestashop checkout payment module for payment by card.

### Steps to reproduce

Download Prestashop checkout
Install Prestashop checkout
Error on step "Authentication"

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by paulnoelcholot** [comment]
Hello @ArchyAzur,

It seems that your issue is not a PrestaShop core bug.
If your module is PayPal Official, please contact support team on Addons

We will close this issue.

Thanks!
