### ISSUE TITLE
BO - Multistore - PPV2 -  Some issues when duplicating a product for all stores by Build actions 

### ISSUE THREAD

**Issue by djoelleuch** [PrestaShop/PrestaShop#31778]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments & expected behavior

the wording :ok: 
the product should be duplicated to all the stores . 

### Steps to reproduce

1. Go to BO > Shop parameters > General > Enable multistore
2. Go to BO > Advanced parameters > Multistore > Add two  new shops (shop1) , (shop2)
3. go to catalog >products>shop1 >create a new product .
4. go to products ALL SHOPS > select the product created , click on Duplicate selection for all stores on BUILD ACTIONS > see the first issue : _name store have only the parent shop name_ :x:
5. go to shop2 > see the second issue : _there is not a copy of the product created_ :x:

[Untitled_ Mar 14, 2023 10_23 AM.webm](https://user-images.githubusercontent.com/115152460/224960471-12792368-586f-4e13-a38f-c9e0fc39e15e.webm)

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

7.4

**Comment by paulnoelcholot** [comment]
Hello @djoelleuch ,

I reproduce the issue with PrestaShop version 8.1.x, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/product-team could you please prioritize this issue :pray:

**Comment by MatShir** [comment]
It is the expected behavior. In all store context, the product is duplicated and all the association are duplicated. So if a product is duplicated and is associated to 3 shops on the 5 shops available, then the product will be duplicated and will be only associated to the 3 shops.
But the wording can be improved for sure, @l-delin what do you think ?
I suggest: 'Duplicate selection for all associated stores "

**Comment by l-delin** [comment]
Hellooo @MatShir 
The wording you suggested is much clearer than the current one. It may be a bit too long, though:
![image](https://user-images.githubusercontent.com/113511191/228769037-161569ba-e8a4-428a-8add-d687f3a7e1e8.png)

The wording could be **"Duplicate selection for all associated stores"**, it's a bit shorter.
![image](https://user-images.githubusercontent.com/113511191/228769343-d23fb299-3b2c-4a91-a5fd-76b9661ba056.png)

What do you think?

**Comment by aniszr** [comment]
Hello,

I tested the wording LGTM.
The issues still persists, should wait for another PR to fix it.

Thanks!

**Comment by MatShir** [comment]
It is the expected behavior. The issue is around the wording, the PR has fixed a small part of it.
