### ISSUE TITLE
migation de 1.7.8.8 vers 8.0.1 avec module natif 1 Click Upgrade

### ISSUE THREAD

**Issue by thomas11140** [PrestaShop/PrestaShop#31788]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

![image](https://user-images.githubusercontent.com/127859712/225081052-8d7e5d61-f25b-4447-a21f-251dbd790043.png)

### Expected behavior

ouverture de la page gestionnaire de module

### Steps to reproduce

click sur gestionaire de module

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8

### If your bug is related to a module, specify its name and its version

migration de 1.7.8.8  vers 8.0.1

**Comment by hibatallahAouadni** [comment]
Hello @thomas11140 

Please send your request in English. English is the norm on GitHub.
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must provide clear and concise "steps to reproduce" to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thank you
