### ISSUE TITLE
simplePagination.js library in productcomments module is obsolete

### ISSUE THREAD

**Issue by leemyongpakvn** [PrestaShop/PrestaShop#31781]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

simplePagination.js has been outdated for 7 years and is not available in npm.
It is **not a bug** but using an obsolete library comes from an uncommon repository is not good for the project.
(I can not find an appropriate category for this issue so I post it as a bug :)

### Expected behavior

Replace simplePagination.js by a modern one in npm like https://www.npmjs.com/package/paginationjs, or a simpler custom pagination code.

### Steps to reproduce

Check 
https://github.com/PrestaShop/productcomments#update-dependency 
https://github.com/PrestaShop/productcomments/tree/dev/views/js
https://github.com/flaviusmatis/simplePagination.js
to see how obsolete the library is.

### PrestaShop version(s) where the bug happened

1.7.x, 8.x

### If your bug is related to a module, specify its name and its version

productcomments

**Comment by paulnoelcholot** [comment]
Hello @leemyongpakvn,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by leemyongpakvn** [comment]
FYI, the original idea is https://github.com/PrestaShop/PrestaShop/discussions/31624

**Comment by kpodemski** [comment]
@leemyongpakvn for the future, no need to create an issue if we agree on the solution in the Discussions 👍🏻 but thanks anyway :D
