### ISSUE TITLE
Disallow display of category from other shop

### ISSUE THREAD

**Issue by mkdgs** [PrestaShop/PrestaShop#31797]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

With a multishop installation, you can display the list of products of a category from another store, even if this category is not associated with the current store.  
Just need to know the category ID
ex: https://shop.com/1234-id-cat-other-shop

### Expected behavior

display a 404 page if the category is not associated with the current shop

### Steps to reproduce

1) you have a multisite installation with two shop (ore more)
2) in general context create a category tree 
- root
-- shop 1
--- cat-1
-- shop 2
--- cat-2
3) got to shop 1 assign cat-1 to this shop  
4) got to shop 2 assign cat-2 to this shop  

Get the id of cat-1
Got to front of shop 2, on listing of cat-2, 
change the id of cat-2 with id cat-1   
You will see category of shop-1 on shop-2

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @mkdgs ,

Thanks for the issue, it is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/13468

@MatShir , can you decide if we keep this issue with the PR related or keep the original one and keep this PR ?

Thanks!

**Comment by mkdgs** [comment]
@florine2623 its not really a duplicate #13468 i've not reproduced the issue about product's page.
I think #13468 is may be related, but outdated.
Breadcrumbs issue still exist but need to be addressed separately.
PR is only about this one, no plan to fix breadcrumb inside.

**Comment by MatShir** [comment]
Let's keep this one as @mkdgs say. Maybe for the testing we could check if it fixed by side effect (big big maybe)

**Comment by mkdgs** [comment]
Pr moved on #31876

**Comment by Prestafan1234** [comment]
Any news on this? It is a bug that seems to have been present since 2019. I have several clients using multistore and the issue is really bad for SEO as non-active categories are indexed by search engines because inactive category pages are actually active in front office

**Comment by Hlavtox** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/35321
