### ISSUE TITLE
I want upgrade 1.6.1.24 to 1.7.8.8

### ISSUE THREAD

**Issue by aytekinazmi12** [PrestaShop/PrestaShop#31796]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi Friends

I want upgrade 1.6.1.24 to 1.7.8.8 but I have problem at upgrade checklist.

Problem 1-click module update (current version v4.14.2). I know for upgrade 1.6.1.24 to 1.7.8.8 I can v4.14.2 

Can you help me?

### Steps to reproduce

Hi Friends

I want upgrade 1.6.1.24 to 1.7.8.8 but I have problem at upgrade checklist.

Problem 1-click module update (current version v4.14.2). I know for upgrade 1.6.1.24 to 1.7.8.8 I can v4.14.2 

Can you help me?

### PrestaShop version(s) where the bug happened

1.6.1.24 to 1.7.8.8

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

autoupgrade

**Comment by djoelleuch** [comment]
Hello,

PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).

Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

Thank you

**Comment by aytekinazmi12** [comment]
Hi,

so i want to update my site and request update help.

**Comment by gerdus** [comment]
This is definite a legit bug in currently supported autoupgrade module.
The problem is newest version 4.15.0 is 1.7 only but check list does not take this into account.

The solution is to lie by changing the version in /modules/autoupgrade/config.xml to 4.15.0

`<version><![CDATA[4.15.0]]></version>`

**Comment by aytekinazmi12** [comment]
> This is definite a legit bug in currently supported autoupgrade module. The problem is newest version 4.15.0 is 1.7 only but check list does not take this into account.
> 
> The solution is to lie by changing the version in /modules/autoupgrade/config.xml to 4.15.0
> 
> `<version><![CDATA[4.15.0]]></version>`

Thank you for reply but I did that already but problem not fixed :(

**Comment by KKE-motor** [comment]
Hi
I cheated the xml file for the 1 click upgrade module. Changed from 4.14.2 to 5.0.0.

Like:  <version><![CDATA[5.0.0]]></version> in the config.xml in /public_html/modules/autoupgrade

That worked
