### ISSUE TITLE
In autoupgrade, calls are made to Addons API

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#31793]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Calls are made to Addons API (https://github.com/PrestaShop/autoupgrade/blob/dev/classes/Upgrader.php#L40) in spite of the differenciation.

### Expected behavior

Related to EPIC #28771

### Steps to reproduce

N/A

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
@PrestaShop/prestashop-core-developers could someone validated the issue :pray: 
Thanks in advance!

**Comment by Quetzacoalt91** [comment]
We've started plugging the module with Distribution API. We already use it to get PHP requirements of PrestaShop 8+ and we plan to use it to get modules updates as well.
