### ISSUE TITLE
FO - Products page - The sort by price hight to low is not correct when we have a product with discount

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#31801]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In FO > All products page, the sort of products list by price high to low is not correct when we have a product with discount in the list.

![Capture d’écran de 2023-03-15 15-28-39](https://user-images.githubusercontent.com/24647495/225340549-a747e11c-c96d-4ee1-80fb-6083414521c5.png)

### Expected behavior

The sort should be applied to the price after discount.

### Steps to reproduce

1- Go to FO > All products page
2- Sort products list by price high to low
3- See the products list

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.3

**Comment by djoelleuch** [comment]
Hello @nesrineabdmouleh  ,

I have reproduced your issue with 8.1.x ,8.0.x 1.7.8.8  and develop .

![image](https://user-images.githubusercontent.com/115152460/225353349-2cdbd542-a926-4b46-a88a-7a1b874e3e60.png)

Thank you !

**Comment by Hlavtox** [comment]
@djoelleuch @nesrineabdmouleh Duplicate of https://github.com/PrestaShop/PrestaShop/issues/19810

**Comment by hibatallahAouadni** [comment]
Thanks @Hlavtox :rocket: 
Duplicate of #19810

**Comment by hibatallahAouadni** [comment]
Duplicate of #19810
