### ISSUE TITLE
As a merchant I want to know what is tracked during the upgrade process

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#31805]
As a merchant I want to be informed what data are tracked in the software if I am upgrading my PrestaShop to a version that contain telemetry

This is an issue similar to PrestaShop/PrestaShop#31625 but for upgrade part.

## Context

When prestashop is being installed, the project wishes to collect the shop (being installed) URL and the version of PrestaShop being used.
Even if this is compliant with GDPR 

## Business rules

If I use a version A of PrestaShop and I wish to use the autoupgrade module to upgrade to a version B
And version A does not include telemetry but version B does include telemetry
Then the user must be fully informed.

In the Autoupgrade panel where user selects its upgrade option
Add 
- A specific Title
- A textfied with 
     - a message / text : it should warn the user that the shop URL will be collected
     -  add a link to a specific webpage on https://www.prestashop-project.org/ (see https://github.com/PrestaShop/open-source/issues/166)

## Wording

To be defined by @l-delin
Can probably be very similar to PrestaShop/PrestaShop#31625

**Comment by l-delin** [comment]
> ### Privacy note
> 
> You are upgrading your current version of PrestaShop. In this newer version, public and technical information about your store will be sent to the PrestaShop Project for analytics purposes. To learn more and make an informed choice, read [this article](https://www.prestashop-project.org/data-transparency/).

We can keep something similar to PR 31625 as you said. I think it would be better to keep something similar for consistency anyway.

My only doubt is this: "In this **newer** version", can version B be older than A?

**Comment by gericfo** [comment]
Hello, 
After consulting the DPO, the e-privacy directive does not apply to the trackers included in the PrestaShop BO. These are already mentioned in the PS legal documentation. There are no critical changes to bring to the PrestaShop autoupgrade.
