### ISSUE TITLE
Broken main menu

### ISSUE THREAD

**Issue by etsibou** [PrestaShop/PrestaShop#31817]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello! I am facing a problem with my main menu. I would like to proceed with some changes and It seems that it is broken. 
In the attachement is a screeshot.
![main menu](https://user-images.githubusercontent.com/128134357/225859471-e8159c81-c05a-487d-9616-3d1c8b580eac.jpg)

Any help please?

### Steps to reproduce

.

### PrestaShop version(s) where the bug happened

1.7.8.7

**Comment by florine2623** [comment]
Hello @etsibou ,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Please contact your theme provider for that issue.
This is not a PrestaShop core issue.

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
