### ISSUE TITLE
Error 500 when trying to export current theme

### ISSUE THREAD

**Issue by darkf3d3** [PrestaShop/PrestaShop#31819]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When exporting classic theme from Design > Theme & Logo > Theme > Export current theme on PS8.0.2 error 500 it's showed.

Detail showed with debut mode enabled:

**Could not crawl for translation files: The "/var/www/vhosts/httpdocs/websitename.com/app/../translations/en-US" directory does not exist.**

`
PrestaShop\PrestaShop\Core\Exception\
FileNotFoundException
in [src/PrestaShopBundle/Translation/Provider/TranslationFinder.php ](https://www.websitename.com/admin/index.php/_profiler/open?_token=xxxxxxxxxxxxxxx?file=src/PrestaShopBundle/Translation/Provider/TranslationFinder.php&line=106#line106) (line 106)
        }
        try {
            $translationFiles = $finder->files()->notName('index.php')->in($paths);
        } catch (InvalidArgumentException $e) {
            throw new FileNotFoundException(sprintf('Could not crawl for translation files: %s', $e->getMessage()), self::ERR_DIRECTORY_NOT_FOUND, $e);
        }
        if (count($translationFiles) === 0) {
            throw new FileNotFoundException('There are no translation file available.', self::ERR_NO_FILES_IN_DIRECTORY);
        }
`

### Expected behavior

Prestashop should export the theme

### Steps to reproduce

From back office, go to Design > Theme & Logo > Theme
Then click on "Export current theme" button

### PrestaShop version(s) where the bug happened

8.0.2

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello @darfk3d3 ,

I can't reproduce your issue using 8.0.2. It must be a server config issue on your side.

https://user-images.githubusercontent.com/16019289/225884199-f6d2e74a-27ae-46e3-b3a4-1a85b9fa8c89.mov

---
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by darkf3d3** [comment]
Why server configuration?
