### ISSUE TITLE
Improve wording Advanced Parameters > Team > Profiles

### ISSUE THREAD

**Issue by Julievrz** [PrestaShop/PrestaShop#31814]
### The problem

The same word (profile) is used in different places in the back office but with different meanings. 

1. Here "profile" refers to the employee's page, where they can modify their name, language, avatar, and password. 
<img width="299" alt="Capture d’écran 2023-03-16 à 17 24 56" src="https://user-images.githubusercontent.com/70583503/225686664-6ae5e840-d9f6-44fd-bf5b-63d1d4389caa.png">
2. Here, "profile" refers to the role of an employee. The employee's permissions depend on his profile (his role). 
<img width="1218" alt="Capture d’écran 2023-03-16 à 17 30 13" src="https://user-images.githubusercontent.com/70583503/225688156-63770f75-1f5f-44d2-a4f7-5fdc3ac24cc1.png">

### The solution

To avoid confusing the user with the same word having different meanings, **I suggest replacing "Profile" with "Role" on the Advanced Parameters > Team > Profiles pages.** 

<img width="803" alt="Capture d’écran 2023-03-16 à 17 34 38" src="https://user-images.githubusercontent.com/70583503/225689325-926e2dc4-b2d9-4501-a40a-80cea3a0dacb.png">

<img width="667" alt="Capture d’écran 2023-03-16 à 17 36 29" src="https://user-images.githubusercontent.com/70583503/225689784-665033c3-6722-4b38-9753-992a0d8e0e09.png">

The strings to replace are: 
'**Profile**' in Admin.Advparameters.Feature
'Add new **profile**' in Admin.Advparameters.Feature
'**Profiles**' in Admin.Navigation.Menu
'Create **profiles** for your employees with specific rights. SuperAdmin can access the entire store while other people can only be dedicated to the catalog or orders pages.' in Admin.Navigation.Feature (Idk where this string appears but I saw it on Crowdin)

I can update the documentation accordingly. 

### Do you plan to work on this subject?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.</div>

**Comment by l-delin** [comment]
Looks good to me ✅
