### ISSUE TITLE
Attributes & Features > Features list actions not working

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#31821]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments
![image](https://user-images.githubusercontent.com/31609858/225927784-9a5cbcb0-aecd-4934-8574-5d619d0cba56.png)

Features list is migrated horizontally and is not compatable with recently merged legacy_feature_flag, so when you enable experimental migrated feature page the list actions aren't working. 
There is also one related error - Even when "new features page" is disabled, when you go to features list and open up edit action from list, you can see that it opens up the new migrated edit page. (it should open old one). To differentiate legacy and new pages you can just see that in new page there is a symfony debug toolbar at the bottom of the screen (as well as the link is different new being `/sell/catalog/features`, old something like `/index.php?controller=AdminFeatures`...)

### Expected behavior

As horizontal migration approach was cancelled as inefective and there is already PR to merge list vertically, it would be wise just to disable the feature in 8.1 and wait to be fixed in develop branch. So from UX point of view, merchant should not have the option to enable new "features" page and always see a working legacy features page.

### Steps to reproduce

issue1:
1. Go to BO new & experimental features and enable "Features" toggle.
2. Go to Sell > Catalog  > Attributes & Features > Features
3. Check that list actions are not working. (clicking view/edit or delete juts redirects back)

issue2:
1. Go to BO new & experimental features and disable "Features" toggle.
2.  Go to Sell > Catalog  > Attributes & Features > Features
3. Click on edit action and see that it opens up a new features page, while it should open legacy one. (explained how to differentiate between new and legacy page in description above)

### PrestaShop version(s) where the bug happened

8.1.x, develop

**Comment by florine2623** [comment]
Hello @zuk3975 ,

I reproduced the issue with PrestaShop version `8.1.x` and `develop`, I'll add this to the backlog so it can be fixed.

issue1:

https://user-images.githubusercontent.com/16019289/226627460-c31383d2-a8f3-4956-99d6-5c6fc5f8a0e3.mov

---
issue2:

https://user-images.githubusercontent.com/16019289/226627737-1e6f7313-cdd4-4388-b1be-e04ddbd9d140.mov


Thanks for the PR !

Thank you

**Comment by Hlavtox** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/31823
