### ISSUE TITLE
ip2long manages only ipv4 adresses

### ISSUE THREAD

**Issue by NicolasCador** [PrestaShop/PrestaShop#31831]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Prestashop manages ip adresses for several needs.
For exemple the class connection.php records the ip address in the database.
This record is done with ip2long converting.
ip2long manages only ipv4 adresses, so there is a 0 in the record.

dashactivity module checks if connection ip is the same than the ones in the maintenance ip.
If there is at least one ipv6 address in several maintenance ip adresses, the module doesn't show data on dashboard due to a sql error because there is ",," in the query.

### Expected behavior

The dashboard should show dash activity module data.

### Steps to reproduce

Go to maintenance page
Put 1 ipv4 then 1ipv6 then 1 ipv4 in maintenance ip, save
Go to dashboard
you see only arrow turning instead of data of visitors, carts, ...

### PrestaShop version(s) where the bug happened

8.0.2

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello @NicolasCador ,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please check if this issue is relevant, it's too technical!

Thanks in advance!

**Comment by NicolasCador** [comment]
Hello @florine2623 ,

thanks for your answer.

I proposed a solution for dashactivity module, but I think the issue is more general than this module as today the Prestashop class connection.php is using ip2long to record the connections in database.

**Comment by NicolasCador** [comment]
Hello @nicosomb,

I proposed a solution for dashactivity module, but I think the issue is more general than this module as today the Prestashop class connection.php is using ip2long to record the connections in database.

Maybe a solution should be found  to avoid a "" record in the database, for maintenance IP and also for visit IP in case of ipv6 addresses?

**Comment by BarbUk** [comment]
This is not resolved and should be reopened, php `ip2long` [still does not support ipv6.](https://www.php.net/manual/en/function.ip2long.php).

Handling ipv6 for the [`connection` class](https://github.com/PrestaShop/PrestaShop/blob/0efc4e74c43ec91f6bf2a29878a5ddd709137349/classes/Connection.php#L181) can be done:
 - by storing all ip (v4 and v6) in a `BINARY(16)` column with [`inet-pton`](https://www.php.net/manual/en/function.inet-pton.php) and reading it back with [`inet-ntop`](https://www.php.net/manual/en/function.inet-ntop.php).
**This will require a database schema change**

 - by using a custom function to store ip4 and ipv6 in the existing `big int` column.
[Something like that (not tested).](https://inkplant.com/code/ipv6-to-number)

**Comment by ChillCode** [comment]
Hi @nicosomb @kpodemski 

Can you reopen/rethink this please?

Now a lot of people are using IPV6 and if we get into AdminDashboard and have statslive it says there are 87 visitors online but when we follow the link we get no connections at all and some site owners get paranoid.

As stated by BarbUk it's possible to change to use inet_pton and inet_ntop, but also found this issue while ago, since few people used IPV6 at that time I just refactored that class and integrated into a firewall module for that specific site and I used INET6_ATON and INET_ATON directly with MYSQL and to store both the correct would be VARBINARY(16).

**Comment by HartLarsson** [comment]
is this solved?
