### ISSUE TITLE
Bug affichage produits

### ISSUE THREAD

**Issue by ValSofipel** [PrestaShop/PrestaShop#31838]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Bonjour,

Lorsque j'installe module "Mails alerts" ou n'importe quel module, la page produits sur toutes mes boutiques est modifié. L'emplacement des produits est complétement modifié.

### Expected behavior

Pouvez-vous me dire pourquoi dès que j'installe un module ou que je fais la mise à jour des modules, la page produits de toutes les boutiques est impactées.

### Steps to reproduce

1. Go to "Modules" --> Catalogue de modules
2. Chercher le module "Mails Alert"
3. Installer le module
4. La disposition de produits est complétement changée sur les boutiques.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.28

**Comment by florine2623** [comment]
Hello @ValSofipel ,

Next time, please send your request in English. English is the norm on GitHub.

Also, I can't reproduce your issue.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
