### ISSUE TITLE
Cart product with quantity greater than stock available doesn't allow to reduce it

### ISSUE THREAD

**Issue by diezsiete** [PrestaShop/PrestaShop#31833]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the cart page, if you have a product with quantity greater than the established in stock available a error shows up stating:
'product x' is no longer available in this quantity. You cannot proceed with your order until the quantity is adjusted.

If you proceed to reduce the quantity in the quantity input, the cart will not allow it showing :
The available purchase order quantity for this product is 'x'.
And reverts back the previous quantity value

This always happens with products without attribute, if the product is with attribute, it will allow the reduction of quantity only if the change is less or equal than the stock available.

### Expected behavior

When the quantity of a product in the cart is less than the available quantity and the user presses the "Order" button in the cart, a message is displayed: "The available quantity for the order of this product is X" and the product quantity is set to the quantity available X.

If the user presses the up key or types a quantity greater than the available quantity, the quantity is reset to the available quantity.
if the user presses the down key or types a quantity equal to or less than the available quantity, the quantity value is not updated.

### Steps to reproduce

With the demo store:

1. Go to the product 7 page ('Mug The adventure begins') and add 5 items to your cart
2. In the admin modify the stock of this product in such a way that only 3 are left available
3. Back in the front go to the cart page and you will see the error message, and the product with the quantity of 5 that you requested
4. Try to reduce the quantity, is not possible

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello @diezsiete ,

I reproduced the issue with PrestaShop version `8.1.x`, `develop`, I'll add this to the backlog so it can be fixed.
It's a regression, in `8.0.x`, it worked correctly.


https://user-images.githubusercontent.com/16019289/226637351-3766d72d-b15c-4081-b92e-ec904e0f5319.mov


https://user-images.githubusercontent.com/16019289/226637366-e0fba25b-5bb0-447b-acd6-b5a238250579.mov

---

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
