### ISSUE TITLE
Spike: create repositories and entities interfaces for entities from Context

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#31848]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Based on the following ADR https://github.com/PrestaShop/ADR/pull/33 (still in progress) we plan on introducing some better interfaces for Entities and Repositories

The main purpose is to stop always relying on legacy objects (based on ObjectModel) or even Doctrine entities in the code that is being migrated thus we won't keep increasing our technical debt with each new PR.

### Expected behavior

Once the ADR is voted and validated we can start implementing the interfaces for a few entities as a test and a spike, this will allow us to dig out most of the technical issues that could be related. We want to use this as an occasion to reduce the coupling that is everywhere with `Context::getContext` so the first entities handled would be the one accessible in this Context so that we can propose better alternative and refacto and remove the usages of the Context piece by piece.

### Steps

- [ ] Language
- [ ] Currency
- [ ] Shop
- [ ] Employee
- [ ] Customer
- [ ] Country

These would be the initial ones, this issue is only about anticipating the creation of the related interfaces and repositories. The replacement of Context will be handled in another issue.

Once these entities will have been handled, we can keep going on all the other entities with the help of the community and then refactor the CQRS handlers for the related entities.

### Expected from the spike

The spike aims at creating a first repository for one of the mentioned entities, it should be accompanied with integration tests in a dedicated PR, the purpose is to evaluate how much time it takes for one repository so that we can evaluate the total for all these entities (and in the end all of the entities).

### PrestaShop version(s) where the bug happened

9.0

**Comment by matthieu-rolland** [comment]
First PR, for Language: https://github.com/PrestaShop/PrestaShop/pull/32234

**Comment by WahbiPS** [comment]
Waiting for ADR ( @jolelievre )

**Comment by jolelievre** [comment]
Duplicate of more detailed epic https://github.com/PrestaShop/PrestaShop/issues/33194
