### ISSUE TITLE
Spike: Make Symfony Container accessible in Front Office

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#31846]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

So far the Symfony container is only accessible in the Back Office, as such many services from Symfony are not usable in Front Office Even though we don't plan on starting the migration of the front in Symfony right now we could still anticipate at least the access of the container so that some services can be used in front as well among which:
- the CQRS command bus
- the future CartRule/Price new computer
- doctrine entities / services (even if today an alternative exists)
- ...

### Expected behavior

- [ ] We need to instanciate the Symfony kernel in the FO endpoint index.php file so it's accessible
- [ ] In the FO we need a clean way to get the container (for now we use SymfonyContainer::getInstance in legacy code in the BO but it should be improvable)
- [ ] We need to test that any service from the BO is also usable in FO
- [ ] We need to perform a benchmark and analyze the cost of this container in FO
  - [ ] When no Symfony services is used
  - [ ] When a simple Symfony service is used
  - [ ] When multiple services are used
- [ ] This feature should be handled via a feature flag so it can be completely disabled

### Steps to reproduce

See previous content

### PrestaShop version(s) where the bug happened

9.0

**Comment by WahbiPS** [comment]
Waiting for Blackfire access

**Comment by d0niek** [comment]
@jolelievre nice to hear that! Waiting!

Is there any reason why I shouldn't build Symfony container in FO by my own in PS `1.7.8`? Here is a nice article which explain how to do it https://blog.floriancourgey.com/2018/05/how-to-work-with-the-symfony-kernel-anywhere-in-prestashop-1-7/ and it works (!) ;-)

I know it slow down front a little but are there any other issues?

**Comment by boherm** [comment]
Need merge https://github.com/PrestaShop/PrestaShop/issues/32698 to continue!
