### ISSUE TITLE
EPIC: get rid of Context::getContext in modern code and Symfony services

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#31849]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Today we have a deep coupling based on `Context::getContext` everywhere in our code base, it is a bad practice as it's not strict enough, it's not immutable so any module can mess with it and even the building of this Context is a bit messy causing unexpected behaviour (like the shell commands that fail most of the time because Context::employee is not set even if it's not needed)

### Expected behavior

Blocked by this Epic https://github.com/PrestaShop/PrestaShop/issues/33194

We aim at removing the usage of the Context fields with dedicated repositories that should be injected everywhere these fields are currently needed. We won't be able to remove all the usages in legacy code for now, the purpose here is to at least get rid of it in the recent code and the services handled by Symfony, including all the references to `LeagcyContext` and `Context::getContext` in the services definition.

### Steps to reproduce

Replace field by field the usages of these fields from the Context
List of TS:
- [x] Language
- [x] Currency
- [x] Shop
- [x] Employee
- [ ] Customer
- [x] Country

And deprecate them one by one.

### Expected from the spike

The purpose is to evaluate the size of this task, a first PR should start removing a few references for one of the entities, Language or Currency may be interesting since they are transverse to many form types and handlers, but Employee and Shop are also a good candidate as it caused a few bugs in the past when the context was not correctly initialized.

We will have to think about how we replace the legacy Context, should we use a similar context but handled by Symfony, or should we replace all the references with the appropriate repository and request the data just in time to avoid errors during kernel/services initialization?

A report about the number of references in modern code and service definitions would be nice as well.

### PrestaShop version(s) where the bug happened

9.0

**Comment by WahbiPS** [comment]
Waiting for ADR @jolelievre
