### ISSUE TITLE
Update button doesn't work

### ISSUE THREAD

**Issue by Casadostecidos** [PrestaShop/PrestaShop#31843]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The steps for the update were followed but when clicking on the upgrade button nothing happens

### Expected behavior

Start update of Prestashop version

### Steps to reproduce

![1 clique](https://user-images.githubusercontent.com/128379197/226335462-4ca06779-e172-4833-b371-753ff181c836.PNG)

The steps for the update were followed but when clicking on the upgrade button nothing happens

### PrestaShop version(s) where the bug happened

1.7.5.1

### PHP version(s) where the bug happened

7.2.34

### If your bug is related to a module, specify its name and its version

1-Click Upgrade v4.15.0

**Comment by florine2623** [comment]
Hello @Casadostecidos ,

Can you check if there's an error in the console ?
Also, please send a screen record of your actions.

Waiting for your feedback.
Thanks

**Comment by Casadostecidos** [comment]
Hello,

How can I check the console for an error?

I send a screenshot of the screen to check how it appears.

I follow all the steps but when I click to upgrade nothing happens.


One difference I notice is that the diff version that is undefined.

![Passo 1](https://user-images.githubusercontent.com/128379197/226706044-6791400c-0e19-4ef2-9038-8df2a0e10ff5.PNG)
![Passo 2](https://user-images.githubusercontent.com/128379197/226706050-cd4ac6b5-012b-4e02-86bb-ce8ab5d64191.PNG)
![Passo 3](https://user-images.githubusercontent.com/128379197/226706054-5191130d-1bb6-4344-b4f0-495a0abdcf55.PNG)


Thanks

**Comment by florine2623** [comment]
To open the console, click right > Inspect element > Console tab

**Comment by Casadostecidos** [comment]
Hello, Florine

When inspecting the console, the data below appeared:

![Console](https://user-images.githubusercontent.com/128379197/227606042-f82e8777-838f-47da-ba4f-799067463804.PNG)



What could it be?

Thanks

**Comment by florine2623** [comment]
@Casadostecidos ,

The pre-upgrade checklist needs to be all green. That's why you can't upgrade your shop.

I'll close your issue as it is a config issue and not a core problem ^^

Thanks!

**Comment by Casadostecidos** [comment]
Hello,

Yes, I know that everything needs to be checked. My first attempt was all right and the button didn't work. I resend the test the button is still not working I click to perform the upgrade nothing happens.

I'm waiting.

![Upgrade](https://user-images.githubusercontent.com/128379197/228818176-122c0d71-75f0-4d7e-bbfe-446335b97c07.PNG)


Thanks.
