### ISSUE TITLE
New_order email not being sent to the seller

### ISSUE THREAD

**Issue by xandraco** [PrestaShop/PrestaShop#31854]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi!
When a new order is placed:
- The customer receives the order confirmation email without problem
- The seller doesn't recevie the new_order email
I've checked the config in the ps_mailalerts module, and everything is correct as shown in this image
![ps_mailalerts-config](https://user-images.githubusercontent.com/72945658/226430793-79e4ae5b-ccf8-4368-b8cf-c76dc47467ef.jpg)

Also, as you can see, there are various email directions that should receive the new_order email, but none of them receive it
- When i try to send a test email from BO => Advanced => Emails => Send a test email, this one is sent correctly
- Also in  BO => Advanced => Emails, on the email log, i see that the confirmation emails are sent to the costumer, but nothing is sent to the seller
![mail-lo](https://user-images.githubusercontent.com/72945658/226433754-182f5765-99c4-4e6f-8df7-e89ef2a84a97.jpg)

- On the seller side all the directions receive the product out of stock email
- We also receive the contact form emails

On the server side in /modules/ps_mailalerts/mails
there's only the folder and templates for english, must say that the store is in spanish mx, so i'm not sure if that could be a problem
![image](https://user-images.githubusercontent.com/72945658/226432689-7f80def8-620c-463f-afd1-c7e514c1cc24.png)

### Expected behavior

Receive the new_order order emails

### Steps to reproduce

1. Set the store language to spanish mx
2. Go to the Front
3. Login as a costumer 
4. Place an order
5. Go to the seller email
6. Wait for the new_order email
7. Wait....

### PrestaShop version(s) where the bug happened

1.7.7.7

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

ps_mailalerts 2.4.0

**Comment by xandraco** [comment]
I managed to solve this just going to the host files /modules/ps_mailalerts/mails
Then there you should fine a folder that contains all the templates for english language, duplicate it and change the name to match the laguage code for your country/language i tried that before, with no success, then found that the name for spanish mx, was just mx
i changed it, deleted the folders in /var/cache/
then placed an order and everything is working fine now

i'll close this and leave it, i hope it helps other people facing the same problem, because i see that's pretty common

**Comment by JavierEB** [comment]
> I managed to solve this just going to the host files /modules/ps_mailalerts/mails Then there you should fine a folder that contains all the templates for english language, duplicate it and change the name to match the laguage code for your country/language i tried that before, with no success, then found that the name for spanish mx, was just mx i changed it, deleted the folders in /var/cache/ then placed an order and everything is working fine now
> 
> i'll close this and leave it, i hope it helps other people facing the same problem, because i see that's pretty common

I have tried to solve the problem as you say @xandraco but with language /es but without success, you say that the path of the module is /modules/ps_mailalerts/mails but that path does not exist on my host, the path of my host is / modules/ps_emailalerts/mails
If you can help me to solve it... I've tried all the ways and it doesn't work, it doesn't send a "new order" email
thanks ;)

**Comment by xandraco** [comment]
> > I managed to solve this just going to the host files /modules/ps_mailalerts/mails Then there you should fine a folder that contains all the templates for english language, duplicate it and change the name to match the laguage code for your country/language i tried that before, with no success, then found that the name for spanish mx, was just mx i changed it, deleted the folders in /var/cache/ then placed an order and everything is working fine now
> > i'll close this and leave it, i hope it helps other people facing the same problem, because i see that's pretty common
> 
> I have tried to solve the problem as you say @xandraco but with language /es but without success, you say that the path of the module is /modules/ps_mailalerts/mails but that path does not exist on my host, the path of my host is / modules/ps_emailalerts/mails If you can help me to solve it... I've tried all the ways and it doesn't work, it doesn't send a "new order" email thanks ;)


Which version of the module are you using?
Also, which language has your store selected as main?

**Comment by JavierEB** [comment]
Which version of the module are you using?Yes, Ps 1.7.8.8 and Module ps_mailalerts  v2.4.0 and PHP 7.4.x
Also, which language has your store selected as main? Yes, Spanish "es"

**Comment by xandraco** [comment]
Could you attach an image of your module configuration?, And also you can try to reset the module, to discard the possibility of that one not getting the updated info

**Comment by JavierEB** [comment]
> Could you attach an image of your module configuration?, And also you can try to reset the module, to discard the possibility of that one not getting the updated info

![imagen](https://user-images.githubusercontent.com/5004396/226982274-b05c32b8-3313-4fe2-b822-6cede8cbec69.png)
PD: With the version of the module ps_emailalerts V2.3.3 it works perfectly for me....It was just after updating when I stopped receiving emails...

**Comment by Hlavtox** [comment]
@kpodemski @PrestaShop/qa-team Guys could you please test this scenario @xandraco reported? Manually fixing an error is good, but we should find the cause, because it's not the first person reporting that emails don't arrive.

- Install 8.0.2 in English.
- Check there is ps_emailalerts in latest version.
- Import another language, french for example.
- Does `fr` folder appear in `modules/ps_emailalerts/mails`?

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Following your steps, I didn't manage to reproduce the issue:

- Install 8.0.2 in English.
- Check there is ps_emailalerts in latest version.

![image](https://user-images.githubusercontent.com/23308427/227493464-3fbba363-5794-4d8b-82d8-2039c33daf5f.png)

- Import another localization pack, France or Czech
- The fr and cs folder appear in modules/ps_emailalerts/mails :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/23308427/227493333-c5256cd9-18cb-4aea-a581-9d4bc8170e4f.png)

Please check and feedback.

Thanks!

**Comment by JavierEB** [comment]
> Hello @Hlavtox
> 
> Following your steps, I didn't manage to reproduce the issue:
> 
>     * Install 8.0.2 in English.
> 
>     * Check there is ps_emailalerts in latest version.
> 
> 
> ![image](https://user-images.githubusercontent.com/23308427/227493464-3fbba363-5794-4d8b-82d8-2039c33daf5f.png)
> 
>     * Import another localization pack, France or Czech
> 
>     * The fr and cs folder appear in modules/ps_emailalerts/mails ✔️
> 
> 
> ![image](https://user-images.githubusercontent.com/23308427/227493333-c5256cd9-18cb-4aea-a581-9d4bc8170e4f.png)
> 
> Please check and feedback.
> 
> Thanks!

here you are using another higher version 2.4.1 released just yesterday, maybe this one no longer has that error and is corrected...

**Comment by waazdakka** [comment]
Problem solved here with creating the folder of my language into /ps_emailalerts folder...
Thanks for the solution!
