### ISSUE TITLE
Problem with module. Strange characters in the text.

### ISSUE THREAD

**Issue by jumper-11** [PrestaShop/PrestaShop#31860]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,
Suddenly, the website started displaying with errors (with additional html characters and mixed content in 2 languages) information for the client.
Nothing was installed or uninstalled.
https://postimg.cc/qh4kfWR7
https://postimg.cc/PprBQHJ1

### Expected behavior

Correct display of the "privacy policy" content

### Steps to reproduce

1. Go to website e-mrowka.com
2. Add to cart any product
3. next click "Przejdź do realizacji zamówienia"
4. And below of the page are data privacy checkbox with this problem

### PrestaShop version(s) where the bug happened

8

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_dataprivacy

**Comment by florine2623** [comment]
Hello @jumper-11 ,

We are aware of this issue, it is already fixed. This issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/29940.

Thank you

**Comment by jumper-11** [comment]
Hi,
but I read and I don't see a solution here for presta 8.
People describe that it works on version 1.7.8.8 but not on version 8.1.
Is it the module's fault? Have you released any update to the module?
Why did this problem occur to me only a few days ago when the store has been installed since December?
