### ISSUE TITLE
Bump Symfony version for PrestonBot

### ISSUE THREAD

**Issue by matthieu-rolland** [PrestaShop/PrestaShop#31873]
The Symfony version used in prestonbot is way outdated. We should bumb it.

**Comment by matks** [comment]
> We should bumb it.

<img src="https://ahf.nuclearmuseum.org/wp-content/uploads/2014/06/Castle%20Bravo.jpg">

**Comment by leemyongpakvn** [comment]
Using depleted means is much more environment-friendly.

**Comment by MatShir** [comment]
closing this issue since we are planning to migrate all the bots in kanbanbot  https://github.com/PrestaShop/PrestaShop/issues/34126
