### ISSUE TITLE
Used vouchers are being displayed in customer account

### ISSUE THREAD

**Issue by gennaris** [PrestaShop/PrestaShop#31871]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If you create an "highlighted" cart rule, 
it will be shown in the customer account even when it reaches 0 "total quantity"

<img width="1042" alt="Screenshot 2023-03-21 alle 20 34 58" src="https://user-images.githubusercontent.com/43071148/226721651-e59d3cd0-b814-41b7-a0a6-03969d783e9e.png">

<img width="1113" alt="Screenshot 2023-03-21 alle 20 35 09" src="https://user-images.githubusercontent.com/43071148/226721705-dfaae12f-66c1-4310-97c4-0b317578c9d5.png">

<img width="1150" alt="Screenshot 2023-03-21 alle 20 35 24" src="https://user-images.githubusercontent.com/43071148/226721822-88647057-df42-41e9-801f-aa8788b5464f.png">

### Expected behavior

A cart rule with quantity 0 (not usable) should not be shown to a customer.

If the total quantity is set to 0 on the cart rule
Then the cart is not usable and hidden in the discount page of the customer

If the quantity available per user is reached on a cart rule
Then the cart is not usable and hidden in the discount page of the customer

### Steps to reproduce

1. Create a valid cart rule with a discount code , enable "Highlight" 
2. Set the "Total available" quantity to 0 in "Conditions" tab.
3. Login as a customer, check  the Voucher section, the unusable rule will be there alongside other valid rules. 

### PrestaShop version(s) where the bug happened

8.0.2

### PHP version(s) where the bug happened

8.1

**Comment by AureRita** [comment]
Hi @gennaris ,

Thank for your report,I reproduce the issue with PrestaShop version 8.0.1, as you can see : 

[Untitled_ Mar 23, 2023 4_59 PM.webm](https://user-images.githubusercontent.com/100699445/227262681-aaf2a04d-010f-4142-a189-7cd17d257a5e.webm)

I'll add this to the backlog so it can be fixed. But I don't know if it's not really an expected beahvior

Ping @PrestaShop/product-team , what do you think about it ? 

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks

**Comment by tleon** [comment]
I'm fixing this one

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/32345
