### ISSUE TITLE
PS 1.7.8.7 payment problems via Mollie

### ISSUE THREAD

**Issue by PrestaVision** [PrestaShop/PrestaShop#31879]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In 2022 I used PS 1.7.8.7 on PHP 7.4 and Mollie's payment module. Now that I'm working on the accounting and administration for 2022, I discovered the following problem:

some payment notifications in Back Office > Orders at the bottom of Payment show the following for a payment: (see image)

the amount to be paid is transferred in 2 parts to Mollie from the customer's account on the same date and at the same time; not a problem in itself, because the total amount is equal to both parts. So far so good...

However, with Mollie only the first part of the payment is registered!! The 2nd part is not listed with Mollie and will not be paid to you later!!

I approached Mollie about this and was turned down:
first it would be up to Prestashop, and after a screenshot of the payments I have to ask my customers for a copy of the bank statement of the transfer, and only then do they want to investigate further.

The problem is that it is not a one-off error/problem, but a much more frequent occurrence.
My question is:
1. why a payment is read or created by Prestashop in 2 parts,
2. how the customer has paid from his account,
3. why Mollie does not register that 2nd partial payment,
4. this problem A. lies with the bank, B. lies with Prestashop, C. lies with Mollie or with Mollie's module.

---

I'm really not going to bother my customers after months and sadly ask for a copy of their bank statement; I have more to do and I don't want to sound like a jerk. For the time being, I'll take those losses for granted and adjust my invoices with an extra discount; It is what it is.

What I am furious about is that Mollie is laying the problem with Prestashop and with me as a webshop owner.
I want to know:
A. if this only happens to me
B. how often this happens to others
C. what causes the error 1. Prestashop, 2. the Mollie module, 3. banking or, 4. Mollie itself
D. how this can be solved Mollie is not done with me yet, because this is costing me a lot of time and money now.

### Expected behavior

I expect a payment via Mollie to be paid to me in full, or that Prestashop stops cutting the payment transaction into parts.

### Steps to reproduce

Please see attachment:

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

mollie

### Your company or customer's name goes here (if applicable).

Pandorrah

**Comment by PrestaVision** [comment]
![probleem](https://user-images.githubusercontent.com/119726053/226942077-e25feca7-58a5-420e-b8a7-45b7e54b7cbe.jpg)

**Comment by AureRita** [comment]
Hi @PrestaVision 

Thank you for your report, can you tell me if you can reproduce this issue with a native payment module (like bank transfer or anything else create by Prestashop and not Prestashop Partner) ? 

Waiting for your feedback

**Comment by PrestaVision** [comment]
Hi @AureRita ,

thank you for the quick reply. :)
I will dive into the matter fully this weekend and come back to you on monday with a detailed analysis.

Thank you and have a great weekend!

Best,
Rene.

**Comment by florine2623** [comment]
Waiting for your feedback !

**Comment by venditdevs** [comment]
@PrestaVision, Mollie is always pointing at others instead of resolving the issues. This is the main reason we stopped supporting Mollie on the webshops we're maintaining.

They can't seem to solve their problems, it's never them, always Prestashop or another party. 

If you take a look on the Github page of Mollie, you''ll see a huge ammount of issues/bugs on all platforms, way more than other providers. The fastest way do solve this is to switch to another paymentprovider with less issues.

**Comment by PrestaVision** [comment]
As far as i can see and backtrack in my situation (PS 1.7.8.7 on PHP 7.4) it is only the Mollie module that gives this specific error, of 2 partial payments in Prestashop orders with the same date and timestamp. 
I already have downloaded the Adyen module as a permanent replacement for Mollie. (now working with PS 8.0.1 on PHP 8).

Mollie customer service indeed does blame Prestashop itself for any errors, and does not investigate if you report a problem; you yourself need to do all the work, in my case ask my customers for a copy of their bankstatements and send it to Mollie, which i will not and cannot do, due to privacy.

I am done with Mollie and i don't think that Prestashop has any blame whatsoever; other payment modules do not make the same errors, so it must be Mollie.

Thank you for the input @venditdevs and thank you for looking into the matter with me @florine2623 and @AureRita . It's time to get rid of Mollie as a payment provider in this case.
