### ISSUE TITLE
Problem with google analytics tag code

### ISSUE THREAD

**Issue by ximo1974** [PrestaShop/PrestaShop#31897]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

hola un error no es sino que desde google analytics tengo el código de la etiqueta pero no se como hacerlo.
..

### Expected behavior

esta todo bien solo que no se como poner el código de la etiqueta de google analytics

### Steps to reproduce

este es el codigo:

<script async src="https://www.googletagmanager.com/gtag/js?id=G-X2B7973XSH"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-X2B7973XSH');
</script>

### PrestaShop version(s) where the bug happened

1.7.8.2

### Your company or customer's name goes here (if applicable).

relojesyjoyasdelujo.org

**Comment by AureRita** [comment]
Hello,

Please send your request in English. English is the norm on GitHub.

Thank you

**Comment by jlores** [comment]
Hello,

Necesitas instalar el módulo de google analytics. Lo tienes disponible de forma gratuita.Ahí puedes poner el código 

You need to install the google analytics module. You have it available for free.

Best regards
Jose

**Comment by florine2623** [comment]
Can you explicit the steps to reproduce your bug ?
Please add a screenshot also.

**Comment by ximo1974** [comment]
hello, an error is only that from google analytics I have the code of the label but I don't know how to do it.
I already have google analytics installed but I don't know where I have to put the code. thank you

**Comment by Hlavtox** [comment]
You need to go to Module manager, find google analytics module and paste the code there, then it will work. For further support, you must contain a specialist. 👍
