### ISSUE TITLE
[BO] module blockreassurance - Duplicate material-icons import and missing landscape material-icon

### ISSUE THREAD

**Issue by leemyongpakvn** [PrestaShop/PrestaShop#31896]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In BO, material-icons is already loaded by [default theme](https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/default/package.json#L31) and [new-theme](https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/new-theme/package.json#L39) so it is duplicated when adding this library in module [blockreassurance dependencies](https://github.com/PrestaShop/blockreassurance/blob/dev/package.json#L39).
Also in BO, a [wrong syntax of landscape material icon](https://github.com/PrestaShop/blockreassurance/blob/dev/views/templates/admin/tabs/content/config_elements/icon.tpl#L33) makes it missing - as showed in the screenshot bellow
![blockreassurance_material-icon_landscape_missing](https://user-images.githubusercontent.com/3759923/227232773-902bebcb-40d6-474e-9eb4-ff6bba305a2a.png)

### Expected behavior

Stop import material-icons library in blockreassurance dependencies.
landscape material-icon must be showed above Modify icon label.

### Steps to reproduce

1. For the first issue, check the referred links above.
2. For the second issue, try to edit an item in module blockreassurance's Content tab in BO, you won't see the landscape icon there.

### PrestaShop version(s) where the bug happened

1.7.8.x, 8.0.x

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

blockreassurance

**Comment by florine2623** [comment]
Hi @leemyongpakvn ,

It should look like that, with no landscape icon :
<img width="602" alt="Screenshot 2023-03-24 at 10 39 05" src="https://user-images.githubusercontent.com/16019289/227483830-8fb9ee4d-5a13-4e29-83ad-a97674989fef.png">

Can you specify the version you are using ?
I'm checking on v5.1.1 and I can't reproduce the issue.

**Comment by leemyongpakvn** [comment]
It is supposed to have a `landscape` icon above Modify icon `span` as coded [here](https://github.com/PrestaShop/blockreassurance/blob/dev/views/templates/admin/tabs/content/config_elements/icon.tpl#L33) and showed in my screenshot.
Your screenshot shows exactly the missing issue.

**Comment by florine2623** [comment]
Thanks for the clarification ! 
The issue is `Verified` then.

**Comment by leemyongpakvn** [comment]
@florine2623 It's time to close this issue :)

**Comment by MatShir** [comment]
haha :)
It didn't closed bc you have to add **Fixes** #Issue Number in the PR description @leemyongpakvn.
Anyway thanks for the reminder
