### ISSUE TITLE
Uncaught PHP Exception: "Call to a member function isLogged() on null" at /modules/ps_customersignin/ps_customersignin.php line 76

### ISSUE THREAD

**Issue by VincePrisma** [PrestaShop/PrestaShop#31905]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments
FR : 
Bonjour, 

En essayant de me connecter au back-office de prestashop, je reçois une page ERREUR500 qui serait lié au module ps_customersignin.

Je n'ai absolument rien changé par rapport au prestashop de base, cette erreur est apparue comme ça et je n'arrive pas à déterminer pouquoi...

Voici un screenshot de l'erreur :

EN : 
Hello,

When I try to connect to the prestashop back-office, I get an ERROR500 page which would be linked to the ps_customersignin module.

I have not changed anything in relation to the basic prestashop, this error appeared like that and I can't determine why...

Here is a screenshot of the error:
![image](https://user-images.githubusercontent.com/128794910/227475889-592e2bc6-29bd-492f-83cf-1acf49f3cd33.png)

### Expected behavior

Pouvoir me connecter au Bo et que les Customer puisse accéder à leur compte

### Steps to reproduce

Dans mon admin login panel, je note mes informations de connexion et au lieu d'atterrir dans le back-office, une erreur 500 m'est renvoyé

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.2.24

### If your bug is related to a module, specify its name and its version

ps_customersignin

### Your company or customer's name goes here (if applicable).

Customer : GLENWOOD

**Comment by florine2623** [comment]
Hello @VincePrisma ,

Could you please provide us with more info ?
We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- PrestaShop version (source)
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- screenshots
- ...

You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

Thank you

**Comment by Hlavtox** [comment]
@VincePrisma There is no reason for ps_customersignin to be hooked to backOfficeHeader, unhook it and the header will disappear.

**Comment by VincePrisma** [comment]
@Hlavtox How should I do it? Because i don't have acces to my back-office. :/

**Comment by VincePrisma** [comment]
@florine2623 
Host : is our hosting provider (cloud100.nevasystems.be)
Sever conf : I don't have any information about it, what do you need to know about it ? (i will ask my N+1)
PrestaShop version (source) : 1.7.8.0
debug mode report : i don't have any report except the screen above
PHP error logs : 
![image](https://user-images.githubusercontent.com/128794910/227483496-b185c616-2344-408c-b944-88e867b753ad.png)
apache error log : what do you need to know about it ?
Javascript console log : nothing :/

**Comment by Hlavtox** [comment]
@VincePrisma Run this in your phpmyadmin, should work.

```sql
DELETE FROM ps_hook_module hm
INNER JOIN ps_hook h ON hm.id_hook = h.id_hook
INNER JOIN ps_module m ON hm.id_module = m.id_module 
WHERE m.name='ps_customersignin' AND (h.name='displayBackOfficeHeader' OR h.name='backOfficeHeader');

```

**Comment by VincePrisma** [comment]
Hello @Hlavtox
This is working, i've access to my BO but my front page is empty now :/
![image](https://user-images.githubusercontent.com/128794910/227502867-2a7fc9d2-a041-40cd-8a22-46df1be1b52b.png)

**Comment by VincePrisma** [comment]
@Hlavtox @florine2623 okay thanks i've fix the problem, i close this issue
Thx all
