### ISSUE TITLE
Since last update do not send new_order mail

### ISSUE THREAD

**Issue by FactoryBike** [PrestaShop/PrestaShop#31918]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Since last ps_emailalerts update v2.4.1 do not send new_order mail. All the other mails works fine.

### Steps to reproduce

1. Do an order
2. Admin does not receive the new_order email

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.33

### Your company or customer's name goes here (if applicable).

www.factory-bike.es

**Comment by Hlavtox** [comment]
@PrestaShop/qa-team Please spend some time testing this, because this is a third issue in 3 weeks reporting the same issue.
(https://github.com/PrestaShop/PrestaShop/issues/31854, https://github.com/PrestaShop/PrestaShop/issues/31649)

**Comment by HanaRebaiQA** [comment]
Hello @Hlavtox 

We are aware of this issue. It's present with other ones in our new issues to treat. Our issue manager will treat it as soon!

**Comment by FactoryBike** [comment]
Hello @HanaRebaiQA 

I reviewed the @Hlavtox insues but the insues that explain in github we are not affected.
Then ¿we will wait for your solution?

thank´s a lot an waiting for our answer….

**Comment by HanaRebaiQA** [comment]
Thanks you @FactoryBike FYI : @hibatallahAouadni is on this issue :)

**Comment by FactoryBike** [comment]
@hibatallahAouadni Any news about this issue?

**Comment by hibatallahAouadni** [comment]
Hello @FactoryBike 

Thanks for your patience and your issue 🙏 
I didn't manage to reproduce the issue with PS1787 and PS1788, see the attached screen record below:

[new_order-mail.webm](https://user-images.githubusercontent.com/23308427/228325462-c3e1fc0f-8823-4b27-bb90-ce14bdf28371.webm)

It seems your issue is related to your mail server configuration.
If you want to check, here's the tool I used to test mailing: https://mailtrap.io/
Please check and feedback.

PS: @Hlavtox I tried but as you can there's no problem, did I miss something?

Thanks!

**Comment by FactoryBike** [comment]
Hello @hibatallahAouadni 
All the other mail in my web works fine....if i test a send mail, works fine. If i go to Avanced Parameters>Email, i can see all the emails sent by the web except _new_order email.
The problems start since las ps_emailalerts update

**Comment by FactoryBike** [comment]
Hello @hibatallahAouadni , any news?. Something change in Last module update. Maybe could start from that.

**Comment by Hlavtox** [comment]
@FactoryBike Try these two things.
- Are you 100% sure that you have the email filled in module settings? There was some upgrade logic that migrated the settings, maybe it failed. Module upgrades randomly fail for me sometimes on all PS versions. Check it.
- If it's ok, check another thing. Go to `modules/ps_emailalerts/mails` and check if there are `new_order.html` and `new_order.txt` **for each of your languages**.

**Comment by FactoryBike** [comment]
Hello @Hlavtox i had check the folder that you explain in your post and the folder "ES" was not there....i put an backup and now the module works.
Thank´s a lot for your idea and best regards.
I will change the insue like solved.

**Comment by Hlavtox** [comment]
@FactoryBike GOOOD!!! But we should investigate it why the mails disappear.

@hibatallahAouadni My dear, could you please check it again on this version? Install 1.7.8.7 in spanish, install some older version of ps_emailalerts like 2.2.0, then try to upgrade to 2.4.1 and see if the mail folder is there? 🙏 

It's absolutely the same issue as in https://github.com/PrestaShop/PrestaShop/issues/31854 and https://github.com/PrestaShop/PrestaShop/issues/31649.

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Following the steps that you provide:

1. Install 1787 in spanich
2. Configure email
3. Install emailalerts v2.2.0
4. Create an order
5. Check the mail new_order is sent
6. Upgrade emailalerts to v2.4.1
7. Create another Order
8. Check the mail new_order is sent

See the attached screen record below:

[emailalerts.webm](https://user-images.githubusercontent.com/23308427/229157910-a0dd7a22-9052-459f-b145-75982ce2716d.webm)

Thanks!
