### ISSUE TITLE
Unable to update list of product pages in pagination version 8.0.1

### ISSUE THREAD

**Issue by louisservices88** [PrestaShop/PrestaShop#31915]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I consult the products of a category, this one displays the list with the following pages. when I go to the following pages the products are not displayed but perform an F5 (refresh) the update is carried out.
workaround increase the minimum list of products per page.

### Expected behavior

Show complementary products in the following pages without refreshing

### Steps to reproduce

display the products of a category whose list is > to the minimum quantity displayable per page
go to the next page or click on the page number

### PrestaShop version(s) where the bug happened

8.0.1

### Your company or customer's name goes here (if applicable).

louisservices

**Comment by florine2623** [comment]
Hello @louisservices88 ,

Please send your request in English. English is the norm on GitHub.

Thank you

**Comment by louisservices88** [comment]
ok, so in the same ticket ? in english ?

**Comment by louisservices88** [comment]
it's good now

**Comment by FabienPapet** [comment]
can you update the title as well ?
Thank you
