### ISSUE TITLE
Spike: analyze all the dependencies of the core and see if some should be updated

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#31937]
### Spike for version 9.0

We already identified a few of our dependencies that needed to be updated/replaced for v9.0 (Symfony, SwiftMailer, ...)
The purpose of this spike is to analyze our dependencies tree and detect if other dependencies need major updates and/or replacements.

### Expected from this spike

A list of dependencies that need to be updated and why, this will allow creating an Epic/Issue for each one. IF possible a rough estimation of the complexity and impact the update can have.

### Spike results

![Image](https://user-images.githubusercontent.com/10706307/233020754-bfe95d97-f02d-408f-a40e-b4d16624a911.png)

![Image](https://user-images.githubusercontent.com/10706307/233020155-9be32fc4-d457-4b1b-9c68-b5d2d3b93770.png)

**Comment by WahbiPS** [comment]
Next Step: create Epic and Issues :) @fabienvallon
