### ISSUE TITLE
Many PHP notices in the log file from module ps_googleanalytics and translation does not work

### ISSUE THREAD

**Issue by PeNov** [PrestaShop/PrestaShop#31931]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello Daniel @Hlavtox,

**1)**	I have question about the module ps_googleanalytics. This new module 4.2.1. generate thousand and thousand PHP notice in the log file. Is it normal? Because log file is huge after a few days and must be deleted.

Each time when any category is opened.

```
PHP Notice:  Undefined index: quantity in /home/www/domain.cz/www/domain.cz/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 157
PHP Notice:  Undefined index: price in /home/www/domain.cz/www/domain.cz/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 158
PHP Notice:  Undefined index: position in /home/www/domain.cz/www/domain.cz/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 160
PHP Notice:  Undefined index: brand in /home/www/domain.cz/www/domain.cz/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 161
PHP Notice:  Undefined index: category in /home/www/domain.cz/www/domain.cz/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 162
PHP Notice:  Undefined index: list in /home/www/domain.cz/www/domain.cz/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 163
PHP Notice:  Undefined index: variant in /home/www/domain.cz/www/domain.cz/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 164
```
**2)	Second thing is If I try click to translate this module is showed nothing.**
![image](https://user-images.githubusercontent.com/38213520/227885264-6636934c-5566-4e69-90ef-21acffb057be.png)

Result:
![image](https://user-images.githubusercontent.com/38213520/227885311-18c49ee8-370f-491a-8b2c-39f5f4a78154.png)

I chose again but now according to folder name:
![image](https://user-images.githubusercontent.com/38213520/227885394-a5ad5760-22c5-4f58-ba1c-4b2bd33a925a.png)

Result is the same as above.

But I think should be something like this from module Prestashop Event Bus:

![image](https://user-images.githubusercontent.com/38213520/227885479-80093d63-e4ab-4fe6-bac8-5c15e24ad92e.png)

Thank you
Best regards
PN

Tested od these configurations:
PS 1.7.8.8 and 8.0.2
PHP: 7.4.33
MySQL: 10.1.48-MariaDB-0+deb9u2

### Expected behavior

Work without errors :-) (without overfilling log file)

### Steps to reproduce

Steps are described above.

### PrestaShop version(s) where the bug happened

PS 1.7.8.8 and 8.0.2

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

ps_googleanalytics

**Comment by PeNov** [comment]
Sorry, I forgot add screenshot (for point 1) in case on debug mode true:
![image](https://user-images.githubusercontent.com/38213520/227890215-dd31bbc3-26a6-4380-8c87-6333656dfeaa.png)
![image](https://user-images.githubusercontent.com/38213520/227890239-6a2a8b8f-15b7-494b-92a1-937adefe70d8.png)

**Comment by florine2623** [comment]
Hello @PeNov ,

1) I can't reproduce your issue. My debug mode is enabled, but no exception is displayed. Did you do something special or just the translation of the google analyitcs module / opening of category page ?

---

2) I reproduce the issue with PrestaShop version 8.0.2, I'll add this to the backlog so it can be fixed.
It is a regression on ps_googleanalytics module.
With Google Analytics `v4.1.2`, the translation is available :
<img width="1437" alt="Screenshot 2023-03-30 at 12 30 20" src="https://user-images.githubusercontent.com/16019289/228809171-3b70e31a-60fe-4d8f-9b2a-1c696a847d62.png">

After upgrading to Google Analytics `v4.2.1`, the translation is not displayed anymore : 
<img width="1436" alt="Screenshot 2023-03-30 at 12 32 19" src="https://user-images.githubusercontent.com/16019289/228809593-59d42da2-9b73-411b-b226-6a97ddcb829b.png">



Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by MatShir** [comment]
@Progi1984 Have you any ideas why?

**Comment by PeNov** [comment]
Hello @florine2623,

**About point 1)**

I am not using anything special. It is a very old installation (PS 0.9) which is regularly updated. E-shop use classic theme with small changes.

I tried delete cache, disable nonnative modules, disable override, reinstall modules...

May be what is a little special is using new GA4 and old UA analytics modules together. But module for old UA was released by @Hlavtox .

I tried a lot of things and I don't know what else to try.

I discovered one strange thing while I am investigating this problem.

These PHP notices are generated only on some categories. For example, 3 categories from 10 categories generate these PHP notices. Non problematic categories have not pagination (only one page). One page has 24 product per page.

**Home page – no problem on the featured product:**
GA4:
 
![image](https://user-images.githubusercontent.com/38213520/229059822-a38c5029-d504-4aa0-8230-2523913ce079.png)

UA:
 
![image](https://user-images.githubusercontent.com/38213520/229059846-cd0caede-50a7-47a5-868b-a85bf06758d0.png)

**Non problematic categories:**
GA4:
 
![image](https://user-images.githubusercontent.com/38213520/229059893-969160ae-0540-4cff-a446-16e30c5414a2.png)

UA:
 
![image](https://user-images.githubusercontent.com/38213520/229059873-1017f656-4302-4e0b-bc62-697b387ce2b3.png)

**Problematic categories:**

Products from the featured block – GA4 - It is OK:
![image](https://user-images.githubusercontent.com/38213520/229059932-2ad73849-ec7a-4e5d-ac0c-0a007e2b7eb9.png)

Products from the category – GA4: (Load NULL):
![image](https://user-images.githubusercontent.com/38213520/229059997-3d5920da-9e56-4563-8af6-b773a4e8c204.png)
----------------------------------------------------------------------------------------------------------------------------------------
**Point 3) GA script is not updated content according to pages:**
If category have more than 24 product = 2 pages:
First page showing 24 products with NULL values. After click to second page. Products on the web page are changed but script contain still product from the page 1:
![image](https://user-images.githubusercontent.com/38213520/229060348-c3bd68bb-86df-435a-a993-65bd0569a63e.png)

Now I have url: **...ozky?page=2** After clik to reload page – content of the script is updated without NULL and contain correct products from page 2:
![image](https://user-images.githubusercontent.com/38213520/229060517-d1d4599c-fa92-42af-a78f-0942640b996b.png)

I would be appreciating some advice how to investigate this problem.  I'm starting to run out of ideas on what else to try.

Thank you
Best regards
PN

**Comment by PeNov** [comment]
Hello @florine2623 @Hlavtox 

Here is way how to reproduce error from the point 1 on the clear installation of the prestashop.

Steps:
1-Create new or duplicate old products till you reach 21 products assigned to the same category.
2-Go to Shop Parameters - Product Settings – Pagination and set Product per page to more than 20.

1-20 works without errors in the server log
21 and more generate errors

![image](https://user-images.githubusercontent.com/38213520/231711544-406b54c7-ae8a-42aa-972f-59e848a9152d.png)

3-Open category with 21 products in the FO. Now you can check server log or you can see the difference in the FO code:

Pagination is 12:
![image](https://user-images.githubusercontent.com/38213520/231712402-ca0c6d9c-c4b0-4969-be39-de498caa9db8.png)


Pagination is 21:
![image](https://user-images.githubusercontent.com/38213520/231711842-a3c0f4d4-35f6-4266-aa0b-77f57a3f5a7d.png)

Thank you
Best regards
Petr

**Comment by florine2623** [comment]
Hello @PeNov ,

For issue 1), I'm testing on PS 8.0.3, with debug mode enabled, overrides disabled, non native PS module disabled.
I'm testing with Google Analytics v4.2.2.

Checked on my server log in /var/logs, but nothing shows up.
I also checked in the console, but I don't have the same result as you :/

**Comment by florine2623** [comment]
@PrestaShop/qa-functional 
Can someone check this issue and try to reproduce the second one please ? ^^

**Comment by laurx2000** [comment]
Hi!

I have the same problem with googleanalytics 4.2.2 (PHP notice), tested on:
prestashop 1.7.8.9 
MySQL: 10.6.12-MariaDB-1:10.6.12+maria~ubu2004
php 7.4.33


prestashop 8.0.4
MySQL: 10.6.12-MariaDB-1:10.6.12+maria~ubu2004
php 8.1.17

Thank you!

**Comment by Hlavtox** [comment]
@PeNov Can you retest with the current dev branch of GA module?

**Comment by PeNov** [comment]
@Hlavtox Yes, I can. Is necessary re-install module or swapping files on the FTP is sufficient?

**Comment by PeNov** [comment]
Hi Daniel @Hlavtox ,

after upgrade to v 5.0.0 FO office stop working (white page). PS version: 8.1.0.

Debug:
`Fatal error: Uncaught Error: Class 'PrestaShop\Module\Ps_Googleanalytics\Hooks\HookDisplayBeforeBodyClosingTag' not found in /home/www/domain.cz/www/test.domain.cz/modules/ps_googleanalytics/ps_googleanalytics.php:107 Stack trace: #0 /home/www/domain.cz/www/test.domain.cz/classes/Hook.php(993): Ps_Googleanalytics->hookDisplayBeforeBodyClosingTag() #1 /home/www/domain.cz/www/test.domain.cz/classes/Hook.php(418): HookCore::coreCallHook() #2 /home/www/domain.cz/www/test.domain.cz/classes/Hook.php(928): HookCore::callHookOn() #3 /home/www/domain.cz/www/test.domain.cz/config/smarty.config.inc.php(187): HookCore::exec() #4 /home/www/domain.cz/www/test.domain.cz/classes/Smarty/SmartyLazyRegister.php(81): smartyHook() #5 /home/www/domain.cz/www/test.domain.cz/var/cache/dev/smarty/compile/classiclayouts_layout_full_width_tpl/bf/9d/68/bf9d680547f22f9ea2016267ddf62347267ced33_2.file.layout-both-columns.tpl.php(379): SmartyLazyRegister->__call() #6 /home/www/domain.cz/www/test.domain.cz/vendor/smarty/s in /home/www/domain.cz/www/test.domain.cz/modules/ps_googleanalytics/ps_googleanalytics.php on line 107`

Translation still does not working.
Debug:
`Unknown error na řádku 114 v souboru /home/www/domain.cz/www/test.domain.cz/vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_modifier.php
[16384] Using php-function "stripslashes" as a modifier is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier.

Unknown error na řádku 114 v souboru /home/www/domain.cz/www/test.domain.cz/vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_modifier.php
[16384] Using php-function "md5" as a modifier is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier.

Unknown error na řádku 114 v souboru /home/www/domain.cz/www/test.domain.cz/vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_modifier.php
[16384] Using php-function "stripslashes" as a modifier is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier.

Unknown error na řádku 114 v souboru /home/www/domain.cz/www/test.domain.cz/vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_modifier.php
[16384] Using php-function "md5" as a modifier is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier.

Unknown error na řádku 114 v souboru /home/www/domain.cz/www/test.domain.cz/vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_modifier.php
[16384] Using php-function "stripslashes" as a modifier is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier.
`

Petr

**Comment by Hlavtox** [comment]
@PeNov You must run composer `dump-autoload`, then it will work. 👍

Translations are not showing up because there is no XLF catalog in the core right now, that is a core problem unfortunately.

**Comment by PeNov** [comment]
@Hlavtox Sorry, I don't know how to run composer on the server. Can you please create standard package for upgrade?
Thank you

**Comment by hibatallahAouadni** [comment]
@PrestaShop/prestashop-core-developers can someone please help @PeNov 🙏

**Comment by PacaPop** [comment]
The same happens to me on catalog listings that have more than 20 products. 
It's because the ProductWrapper::wrapProductList(...) method checks if count($products) is greater than 20. 
The error happens because the $full variable is set to false in this case, and the $products array is left only with product ids and names, missing a lot of fields, including quantity.
Front office only crashes when debug mode is on.

It seems that the team is modifying a lot of things in the module's code in the master branch:
https://github.com/PrestaShop/ps_googleanalytics/commit/15864bc3668041a32a667b0bfb50913533465003#diff-4955f69cd56184318e70c2e05116a329b39d822c93c4d960a5df4d3528ad5caf

They also seem to have removed the count in products array.

**Comment by zilvinasklp** [comment]
Same problem on Prestashop 1.7.8.7
PHP version: 7.4.33
MySQL version: 8.0.35-0ubuntu0.20.04.1 
24 items in one page/list.

Module: Google Analytics v4.2.2

Undefined vars errors in Apache errors log.
`[Mon Nov 27 19:05:21.555710 2023] [fcgid:warn] [pid 879695] [client 172.71.98.46:15418] mod_fcgid: stderr: PHP Notice:  Undefined index: variant in /home/domain/public_html/modules/ps_googleanalytics/classes/GoogleAnalyticsTools.php on line 164`

**Comment by Hlavtox** [comment]
Will be fixed after this is merged and a new version of the module released - https://github.com/PrestaShop/ps_googleanalytics/pull/153. :-)
