### ISSUE TITLE
Autoupgrade - 8.0.1 to 8.0.3 break the FO

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#31945]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I Autoupgrade from 8.0.1 to 8.0.3, when I go on the FO after the upgrade, this one will show us a white screen. 

as you can see : 

[Untitled_ Mar 28, 2023 12_16 PM.webm](https://user-images.githubusercontent.com/100699445/228205827-9bc24573-10dd-463e-ab8e-44b6b8520093.webm)

![image](https://user-images.githubusercontent.com/112863083/228226704-80f8aa74-4b67-4602-9027-51ce0b3565f9.png)

### Expected behavior

The FO should works correctly 

### Steps to reproduce

1. Go to BO > Advanced Parameters > Performance
2. Disable the cache 
3. Enable Debug Mode 
4. Install Autoupgrade
5. Clic on Configure
6. Set up your local archive to have the 8.0.3 on it
7. Select on the expert mode your local archive and your different zip/xml 
8. Save it 
9. Launch the Autoupgrade 
10. Go to FO 
11. / ! \ Look at the extent of this white screen 

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

Autoupgrade v4.15

**Comment by Hlavtox** [comment]
@AureRita You need to report more information. I can clearly see that debug mode is disabled after upgrade in your video.

As you can read when creating a bug report:

> Reporting bugs with "error 500" or "white page" may not help us reproduce them. This is a universal error that hides what is underneath. Instead, enable debug mode in the Performance section of PrestaShop and try again. You should get a proper error message.

**Comment by paulnoelcholot** [comment]
Hello @AureRita,

I reproduce the issue with PrestaShop version 8.0.1 to 8.0.3 , I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you!

https://watch.screencastify.com/v/2Hpxx5Qw4b7xZwEGMWNa
![image](https://user-images.githubusercontent.com/112863083/228226565-744e6b79-332c-400f-b3f0-154d62709135.png)

**Comment by Hlavtox** [comment]
@paulnoelcholot @AureRita Can you give us a version of the ps_googleanalytics module you get after the upgrade?

**Comment by AureRita** [comment]
I've the version 4.1.2 as you can see : 

![image](https://user-images.githubusercontent.com/100699445/228242804-202cc8f8-f637-4829-8527-0e5d5c95e39e.png)

and yes, after disable it, the FO works correctly

**Comment by Hlavtox** [comment]
Could you ZIP the folder with the module so we can inspect it?

**Comment by SharakPL** [comment]
What's the version of GA module before the upgrade? https://github.com/PrestaShop/ps_googleanalytics/pull/116 removed hookDisplayHome class in 4.2.0. Can you please check the file _modules/ps_googleanalytics/ps_googleanalytics.php_ if there actually is 
```php
$this->version = '4.1.2';
```
and if _modules/ps_googleanalytics/classes/hook/hookDisplayHome.php_ is present after the upgrade.

**Comment by AureRita** [comment]
Hi @SharakPL 

GA have the same version than after the upgrade. In the files, it's currently 4.1.2. The hook, in it side, isn't present after the upgrade. 

Currently we find that the autoupgrade doesn't update all the module

**Comment by MatShir** [comment]
Fixed, the API from addons upgrading the module was not responding well. It should be fixed now :)

**Comment by JappeHallunken** [comment]
I upgraded today from latest 1.7 to 8.1.2 (with the 1-click upgrade module) and I have the same issue. It shows available updates for link list module  (v5.0.5 to v6.0.4) and wish list module (v2.1.2 to v3.0.1).
When I click tp update I get an error `Could not perform action update for module undefined`.

**Comment by Hlavtox** [comment]
@JappeHallunken Upgrade these modules manually by uploading a zip, maybe they are somehow corrupted during to some random issue in the upgrade process.
- https://github.com/PrestaShop/ps_linklist/releases/download/v6.0.4/ps_linklist.zip
- https://github.com/PrestaShop/blockwishlist/releases/download/v3.0.1/blockwishlist.zip

**Comment by JappeHallunken** [comment]
This just give me "error Oops... Upload failed." And when I click on "What happened?" No error message is shown

**Comment by Hlavtox** [comment]
@JappeHallunken Try extracting them and manually put them to modules folder. Do server error logs say anything?

**Comment by JappeHallunken** [comment]
@Hlavtox 
logs:

```
Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\ClassNotFoundError: "Attempted to load class "ServiceContainer" from namespace "PrestaShop\ModuleLibServiceContainer\DependencyInjection". Did you forget a "use" statement for another namespace?" at /var/www/vhosts/hosting159589.ae813.netcup.net/httpdocs/testshop/modules/pluginhiveshipping/pluginhiveshipping.php line 68

Uncaught Error: Class "PrestaShop\ModuleLibServiceContainer\DependencyInjection\ServiceContainer" not found
```

Extracting them manually didn't change anything, at first. 
I tried then, without improving of the situation:

>  clearing the cache
> reset link list module
> reset wishlist module -> got some error about a duplicate primarey key somewhere

Then I uninstalled both and reinstalled (from Web GUI) and now they are up to date.
Thanks for your help!
