### ISSUE TITLE
WebService - Help card is in full screen when you modify a Webservice

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#31943]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I clic on the help button during a modification of a webservice, the help information is on full screen insteed of put it in a modal (like all other help card) as you can see : 

[Untitled_ Mar 28, 2023 11_21 AM.webm](https://user-images.githubusercontent.com/100699445/228191114-521185cc-e851-49ef-84ab-8df0adad1bbe.webm)

### Expected behavior

This help card should be on a modal 

### Steps to reproduce

1. Go to BO > Advanced Parameters > WebService
2. Clic on "Add new webservice key"
3. Clic on Help button 
4. Look at this big help 

If you check another back-office page you'll see on other BO pages the "help" opens inside a modal, not in full screen.

### PrestaShop version(s) where the bug happened

8.0.3 - 8.0.1 - 1.7.7.8

### PHP version(s) where the bug happened

7.4

**Comment by paulnoelcholot** [comment]
Hello @AureRita,

I reproduce the issue with PrestaShop version 1.7.8.8 and 8.0.1, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by matks** [comment]
@tleon starts working on this
