### ISSUE TITLE
Remove shipping cost refund limit in prestashop 1.7.8.

### ISSUE THREAD

**Issue by azeqwert** [PrestaShop/PrestaShop#31949]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Remove shipping cost refund limit in prestashop 1.7.8.

Hi,

I want to remove shipping cost refund limit when i do partial refund of the order in backoffice.

This work fine in prestashop 1.6

see the pictures below.

How can i  do this in prestashop 1.7.8 ?

Thank you.
![Capturlllle](https://user-images.githubusercontent.com/129189669/228261979-e5fa67af-2465-451b-8fc3-f085e022f3f8.PNG)
![Capturezz](https://user-images.githubusercontent.com/129189669/228261986-b9ed7b20-5d57-4d0e-8036-908d6836dba8.PNG)

### Steps to reproduce

1. go to order detail
2. put order in preparation
3. click in partial refund
4. add partial refund shipping cost : it is limited 

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.2

**Comment by azeqwert** [comment]
for example 

the customer ordered some products 100€ for total products + 10€ for shipping 

and when during delivery some products damaged and customer want refund like 23.5 € for all(product + shipping)

that why i need the same functionnalty in prestashop 1.6

this is important for accounting

thanks you for all

**Comment by paulnoelcholot** [comment]
Hello @azeqwert,

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com/).

Thank you
