### ISSUE TITLE
Unable to save or create new products PS1.7.8.8

### ISSUE THREAD

**Issue by laserstore** [PrestaShop/PrestaShop#31952]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I know that same people have similar problems but i dont find a solution, i have upgrade form 1.7.8.7 to 17.8.8, but now i can´t create or save a product, it stay thinking and dont do anything for a long time, and give this error:

504 Gateway Time-out
nginx

I dont know what to do more.

Regards
Luis Miguel

### Steps to reproduce

go to products
then new one or edit a existing one

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

### Your company or customer's name goes here (if applicable).

Laser Store

**Comment by paulnoelcholot** [comment]
Hello @laserstore 

I have tested your issue but I don't reproduce the bug as you can see here : 
https://watch.screencastify.com/v/rjz802i7v0NhD7rkloYk

Did I miss something? 

Thanks

**Comment by laserstore** [comment]
Hi,

Its not in this store, is in my other BO.

**Comment by laserstore** [comment]
If a create a new one it stuck there if i edit a old one it stays there also.

https://user-images.githubusercontent.com/97463258/228491849-db020813-c3c2-49c5-8a86-b470c714c3db.mp4

**Comment by laserstore** [comment]
This is when i edit and save a old one:

https://user-images.githubusercontent.com/97463258/228497307-15fe324e-880d-4643-b1f9-86b012f63864.mp4

**Comment by paulnoelcholot** [comment]
Did you cleared the cache and make Ctrl+Shift+R ?

**Comment by paulnoelcholot** [comment]
Can you enabled debug mode and give me the screenshot of the error pls?

Thanks

**Comment by laserstore** [comment]
Yes i have cleared the cache many times im sending you the screenshot

**Comment by laserstore** [comment]
After i activate debug mode and go to products, it gives this error.

![screencapture-contaseberloques-pt-lasernova-admin2004-index-php-sell-catalog-products-2023-03-29-11_21_49](https://user-images.githubusercontent.com/97463258/228504632-86cb4b12-1bb5-49e9-8417-45c5eed1bca2.png)

**Comment by florine2623** [comment]
Hello @laserstore ,

You have a permission issue on your server [Permission denied].
Please check your issue with directly with your host.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
