### ISSUE TITLE
Cart rule tax display wrong

### ISSUE THREAD

**Issue by AaronTajriba** [PrestaShop/PrestaShop#31958]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When editing an cart rule the tax values are always set to "excluding tax" even if you saved it with"included  tax". When you edit something in the cart rule and don't save it with tax the with tax is overwritten with excluding tax.

### Expected behavior

When the cart rule is saved with tax and you open the rule in the backoffice it should display with tax.

### Steps to reproduce

Create an cart rule
add a value with including tax
save
Open the created cart rule
and you will see it display excluding tax

### PrestaShop version(s) where the bug happened

8.0.1 - 8.0.3

### PHP version(s) where the bug happened

8.1

**Comment by AaronTajriba** [comment]
When saving
![Scherm­afbeelding 2023-03-29 om 11 37 46](https://user-images.githubusercontent.com/70962249/228493155-bc7e3c2d-d681-43e4-bb34-a73c89bd62da.png)
![Scherm­afbeelding 2023-03-29 om 11 39 12](https://user-images.githubusercontent.com/70962249/228493483-caea1a60-99ad-4f2e-af83-e97068cdb8ac.png)

After opening
![Scherm­afbeelding 2023-03-29 om 11 38 49](https://user-images.githubusercontent.com/70962249/228493405-54444670-a580-4e72-954a-afa7d23058dd.png)

![Scherm­afbeelding 2023-03-29 om 11 39 56](https://user-images.githubusercontent.com/70962249/228493661-483482f1-2446-42c0-8dd5-e84549313b15.png)

**Comment by paulnoelcholot** [comment]
Hello @AaronTajriba,

I have tested your issue but I can't reproduce this bug as you can see here : 
https://watch.screencastify.com/v/QcwfyXvRHH4wH92w93as

Did I miss something? 

Thanks

**Comment by sharkooon** [comment]
Having the same issue. It also effects the Actions tab for adding € 5 discount including tax. After saving, it is excluding tax.

Shop country and tax rules: NL

See screencast: https://watch.screencastify.com/v/DiYt9nKYYw9pEffOsnLS

**Comment by sharkooon** [comment]
I also tried it programmaticly: https://gist.github.com/sharkooon/166196326e1e44022d1c483c30f77012

Below settings:
<img width="1172" alt="Scherm­afbeelding 2023-04-12 om 09 59 47" src="https://user-images.githubusercontent.com/533123/231392051-641a5710-a477-4673-af61-6a03226dac73.png">

**Comment by sharkooon** [comment]
When i change the PHP version to 7.4.30, or 8.0.25 it works.
Changing it back to 8.1.13, the including tax didn't saved.

**Comment by sharkooon** [comment]
In database table 'cart_rule' the value for 'reduction_tax' = 1, so displaying the select is wrong on the admin side.

I did a var_dump on admin template
/admin-dev/themes/default/template/controllers/cart_rules/actions.tpl
`{$currentTab->getFieldValue($currentObject, 'reduction_tax')|var_dump}`

php 8.0: `string '1'`
php 8.1: `int 1`

**Comment by AureRita** [comment]
Hi @AaronTajriba and @sharkooon 

Thank you for your report and the details. I reproduce the issue with php version 8.1 and not with the version 7.4, as you can see  : 

[Untitled_ Apr 19, 2023 11_58 AM.webm](https://user-images.githubusercontent.com/100699445/233072916-4f1ce4a5-2010-43bc-9d0c-2eea9c03f098.webm)

Nice catch ! It's a regression ! I'll add it to the patch backlog.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by EdEichman-LentillasSi** [comment]
A fix....
![image](https://user-images.githubusercontent.com/6961175/233126284-94fa9b77-bcc2-40b7-a334-b14891164c83.png)

**Comment by sharkooon** [comment]
It effects multiple files:
/themes/default/template/controllers/cart_rules/conditions.tpl
/themes/default/template/controllers/cart_rules/actions.tpl

**Comment by EdEichman-LentillasSi** [comment]
> It effects multiple files: /themes/default/template/controllers/cart_rules/conditions.tpl /themes/default/template/controllers/cart_rules/actions.tpl

You mean reduction_tax in actions.tpl? Or is there something more?
reduction_tax in actions.tpl does look like the same type of bug.
Confirmed, it is a bug there, too
The fix:
![image](https://user-images.githubusercontent.com/6961175/233125738-600b49e9-0458-4af1-a062-6ccbe81a55a5.png)

**Comment by nicosomb** [comment]
@EdEichman @sharkooon your fix is ok for PHP 8.1 but it's KO on 7.4.

**Comment by nicosomb** [comment]
@AaronTajriba @EdEichman @sharkooon the fix has been merged in 8.0.x branch.
