### ISSUE TITLE
Cannot install module is_themecore. The module is invalid and cannot be loaded. for falcon theme

### ISSUE THREAD

**Issue by aponahamed** [PrestaShop/PrestaShop#31965]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When i want to install falcon theme showing this error - Cannot install module is_themecore. The module is invalid and cannot be loaded.
But i don't get any clear documentation how can i use is_themecore module using. if paid theme or module where i can find. GitHub is not clear brief.

### Steps to reproduce

1. download file from https://github.com/Oksydan/falcon
2. upload and try to install

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

7.4

**Comment by Oksydan** [comment]
Hi @aponahamed,

falcon theme isn't prestashop related project.
Please close this issue and answer my question in falcon repository issue you created.
