### ISSUE TITLE
Module Navigation à facette 

### ISSUE THREAD

**Issue by Beauregardstudio** [PrestaShop/PrestaShop#31971]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I use the module to manage the filters. This module has not been working for at least 3 weeks. When I want to modify my filter, it doesn't work anymore. there is this message that appears "you lust select at least one page". can you intervene so that it works again please. My contact is bonjour@beauregardstudio.com
![module nav](https://user-images.githubusercontent.com/128160917/228768075-0b5eaaf4-ee0d-41a0-a194-3cc720e924f3.jpg)
![step 1](https://user-images.githubusercontent.com/128160917/228768913-ff92e2a1-0061-4cec-908c-2700a02adca6.jpg)
![step 2](https://user-images.githubusercontent.com/128160917/228770082-6263081c-7051-4215-8032-b82191ee2e94.jpg)
![step 3](https://user-images.githubusercontent.com/128160917/228770105-4db7b2d7-7b50-4d5a-9509-de18b02e6c1e.jpg)
![step 4](https://user-images.githubusercontent.com/128160917/228770116-a80f1842-bf65-4e62-839c-b13f580765e8.jpg)

### Expected behavior

I want to be able to organize the filters as before.

### Steps to reproduce

![step 1](https://user-images.githubusercontent.com/128160917/228776326-4626cd35-73af-4147-a842-5bc50705e43a.jpg)
![step 2](https://user-images.githubusercontent.com/128160917/228776369-8e63876b-9d03-42c5-a0f4-ce0259c632e4.jpg)
![step 3](https://user-images.githubusercontent.com/128160917/228776422-640bc18f-ab3f-4613-a7d4-5a37a04956a7.jpg)
![step 4](https://user-images.githubusercontent.com/128160917/228776445-6046aa1a-71cc-4cc4-badd-819ceeeb79a6.jpg)

### PrestaShop version(s) where the bug happened

1.7.7.1

### If your bug is related to a module, specify its name and its version

 Navigation à facettes, v3.12.1 - par PrestaShop

### Your company or customer's name goes here (if applicable).

Beauregard studio

**Comment by Beauregardstudio** [comment]
please keep me informed of the situation. When you have found the error. my contact is bonjour@beauregardstudio.com and laura@beauregardstudio.com

**Comment by florine2623** [comment]
Hello @Beauregardstudio ,

Please change your admin folder. It is visible to the whole community.

I'm using Faceted search .v3.12.1
I can't reproduce your issue, the update of my filter is well saved, as you can see from my screen record :


https://user-images.githubusercontent.com/16019289/228801047-31069295-dca9-46ce-914a-8e0956d80cc3.mov


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
