### ISSUE TITLE
Delete permission needed to access module configure pages

### ISSUE THREAD

**Issue by SamiSiitonen** [PrestaShop/PrestaShop#31975]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In Prestashop 8 you need to give BO account delete rights to Module manager in order to access module configuration pages. 

If you don't give delete rights you get an error when clicking 'Configure' for a module.

In previous versions it has been possible to not give delete rights to module manager and still be able to access the configuration pages.

### Expected behavior

BO accounts should be able to access module configuration pages even without delete rights.

### Steps to reproduce

1. Go to Advanced Parameters -> Team -> Permissions
2. Remove this: ![Screenshot 2023-03-30 at 15 14 13](https://user-images.githubusercontent.com/41159177/228833272-0fca9b7b-d6eb-4ac3-86ee-87e92428f22e.png)
3. Go to Modules -> Module Manager -> [Module] -> Configure
4. You should get an error like this 
![Screenshot 2023-03-30 at 15 06 03](https://user-images.githubusercontent.com/41159177/228837515-0e858a77-9163-4dcc-a332-7115d366084d.png)

### PrestaShop version(s) where the bug happened

8.0.0 and 8.0.1

### PHP version(s) where the bug happened

8.1.17

**Comment by florine2623** [comment]
Hello @SamiSiitonen ,

With PS 8.0.x and the same config as you I couldn't reproduce the issue.

Tested with these different configs :
<img width="463" alt="Screenshot 2023-03-30 at 15 20 05" src="https://user-images.githubusercontent.com/16019289/228850145-55f28a8a-41bc-4205-a2c8-cacaf373a568.png">
<img width="461" alt="Screenshot 2023-03-30 at 15 22 22" src="https://user-images.githubusercontent.com/16019289/228850179-3c46c3d7-75ee-47ca-8c1a-6728c7d8b0b6.png">
<img width="468" alt="Screenshot 2023-03-30 at 15 22 10" src="https://user-images.githubusercontent.com/16019289/228850200-430d75eb-1943-4534-891d-aac409c05f6f.png">

Here's the result on my Module page :
<img width="1439" alt="Screenshot 2023-03-30 at 15 21 03" src="https://user-images.githubusercontent.com/16019289/228850349-79f88e19-9380-47fd-ab13-54f52334bbfa.png">

Can you do a screen record and give the exact config of your Profile Permission page ?
Waiting for your feedback.

**Comment by SamiSiitonen** [comment]
Hey @florine2623 

I meant these configure buttons, not bulk actions:
![Screenshot 2023-03-31 at 14 35 03](https://user-images.githubusercontent.com/41159177/229110550-2967f314-8f24-4923-a4e9-34e6b92b5b24.png)

**Comment by AureRita** [comment]
Hello @SamiSiitonen 

Thank you for your details, I tried to reproduce your issue but currently I can't clic on configure because I don't have the button to do it if I only have these rights, as you can see : 

[Untitled_ Apr 4, 2023 5_17 PM.webm](https://user-images.githubusercontent.com/100699445/229840291-8f1eb2c7-b749-4271-bbef-87891f547585.webm)

Did I miss something ? 

Waiting for your feedback

**Comment by hibatallahAouadni** [comment]
Hello @SamiSiitonen 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
