### ISSUE TITLE
Not able to install 8.1.0-beta.1

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#31972]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

While trying to install the 8.1.0-beta.1, I'm facing an issue.

<img width="1210" alt="Capture d’écran 2023-03-30 à 10 02 27" src="https://user-images.githubusercontent.com/2631425/228779034-f98fa2a5-6620-4cd2-9d25-4fd1c84497cf.png">

There is the full error trace :

> [WARNING] Some commands could not be registered:
> 
> In Configuration.php line 331:
> 
> [TypeError]
> Argument 1 passed to PrestaShop\PrestaShop\Adapter\Configuration::restrictUpdatesTo() must be an instance of Shop, null given, called in /src/Core/Addon/Theme/ThemeManagerBuilder.php on line 61
> 
> Exception trace:
> 
> at /src/Adapter/Configuration.php:331
> PrestaShop\PrestaShop\Adapter\Configuration->restrictUpdatesTo() at /src/Core/Addon/Theme/ThemeManagerBuilder.php:61
> PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManagerBuilder->build() at /var/cache/dev/ContainerZDXQJ39/getPrestashop_Core_Addon_Theme_ThemeManagerService.php:9
> require() at /var/cache/dev/ContainerZDXQJ39/appAppKernelDevDebugContainer.php:2295
> ContainerZDXQJ39\appAppKernelDevDebugContainer->load() at /var/cache/dev/ContainerZDXQJ39/getThemeEnablerCommandService.php:9
> require() at /var/cache/dev/ContainerZDXQJ39/appAppKernelDevDebugContainer.php:2295
> ContainerZDXQJ39\appAppKernelDevDebugContainer->load() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:255
> Symfony\Component\DependencyInjection\Container->make() at /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:231
> Symfony\Component\DependencyInjection\Container->get() at /vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:192
> Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() at /vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:156
> Symfony\Bundle\FrameworkBundle\Console\Application->add() at /src/PrestaShopBundle/Service/Database/Upgrade.php:40
> PrestaShopBundle\Service\Database\Upgrade->addDoctrineSchemaUpdate() at /src/PrestaShopBundle/Install/Install.php:347
> PrestaShopBundle\Install\Install->updateSchema() at /src/PrestaShopBundle/Install/Install.php:334
> PrestaShopBundle\Install\Install->installDatabase() at /install-dev/controllers/http/process.php:166
> InstallControllerHttpProcess->processInstallDatabase() at /install-dev/controllers/http/process.php:92
> InstallControllerHttpProcess->process() at /install-dev/classes/controllerHttp.php:277

### Expected behavior

Be able to pass this step.

### Steps to reproduce

Difficult to say.

I make a `composer create-project` with the `make assets` installation and trying to install.

### PrestaShop version(s) where the bug happened

8.1.0-beta.1

### PHP version(s) where the bug happened

7.2.34

### Your company or customer's name goes here (if applicable).

@Wepika

**Comment by nicosomb** [comment]
Hmm I tried to reproduce it locally, same PHP version and same tests to reproduce (`composer create-project prestashop/prestashop:8.1.0-beta.1`) but ... it works :(

**Comment by PrestaEdit** [comment]
Too. With Laravel Valet, trying to switch PHP version and MySQL too, but no issues.

On the server, it's a Nginx.

- MySQL 5.6.51
- Nginx 1.23.1
- Php 7.2.34

PrestaShop 8.0.0 is installed on the same servers, just an another folder on the same directory.

**Comment by florine2623** [comment]
@PrestaEdit ,

Can you try with PHP 7.2.5 or later and feedback ?
`PHP: We recommend PHP 7.2.5 or later.`
https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/

**Comment by PrestaEdit** [comment]
Mmmmmpf.

Not able to update the PHP version right now, and maybe never on this server.

Also, it's true. But the installation could be started, the verification system allow me to make it (it pass the step about requirements) and the compatibility chart mention the 7.2 (not 7.2.5).
Of course, I will not mention the phppsinfos.php that it still for olders versions ;-)

**Comment by nicosomb** [comment]
@florine2623 PHP 7.2.34 is higher than 7.2.5 😉

**Comment by PrestaEdit** [comment]
True ! 😅

**Comment by florine2623** [comment]
Sorry my bad 😅 

I tested on my side with PHP 8.1 and it works well.
I'm not sure what I can check more to reproduce your issue.
<img width="990" alt="Screenshot 2023-03-30 at 12 16 46" src="https://user-images.githubusercontent.com/16019289/228805594-8f999dfb-70bd-4f90-b159-8185ecebf26b.png">

**Comment by llqfront** [comment]
> Sorry my bad 😅
> 
> I tested on my side with PHP 8.1 and it works well. I'm not sure what I can check more to reproduce your issue. <img alt="Screenshot 2023-03-30 at 12 16 46" width="990" src="https://user-images.githubusercontent.com/16019289/228805594-8f999dfb-70bd-4f90-b159-8185ecebf26b.png">

How did you implement HTTPS in the future? Can you give me some advice

**Comment by florine2623** [comment]
@llqfront 
You need ton contact your hosting provider to enable the SSL option.

Once done, you can go to your BO > Shop Parameters > General and enable these 2 options :
 
<img width="1438" alt="Screenshot 2023-04-06 at 15 10 32" src="https://user-images.githubusercontent.com/16019289/230388560-17b90b60-b77b-48c6-9326-d15e269fc5fe.png">

**Comment by florine2623** [comment]
@PrestaEdit , do you still have the issue ?

**Comment by PrestaEdit** [comment]
Yes; but not every time on another place. But, yes, every time on this same install (where I can install a 8.0.x).

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

Thanks for your all feedback but despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration problem.

We will close this issue.

PS: if you can provide more details, please ping us to reopen and rework on the issue 🙏 

Thanks!
