### ISSUE TITLE
CLI upgrade from 1.6 to 1.7 fails at UpgradeDb

### ISSUE THREAD

**Issue by pladen** [PrestaShop/PrestaShop#31989]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Your current PrestaShop version: 1.6.1.24
Your current PHP version: 7.1.33 
1-click upgrade v4.14.2 (I have to make a little hack to unlock the upgrade checks as it is not the latest version)
all other selfchecks okay

Set up to private link with MD5
https://github.com/PrestaShop/PrestaShop/releases/download/1.7.8.8/prestashop_1.7.8.8.zip
No backup (I have already), and default options
```
php ./modules/autoupgrade/cli-upgrade.php --dir=admin --channel=private --action=download
INFO - Download complete. Now extracting...
INFO - === Step unzip
INFO - File extraction complete. Removing sample files...
INFO - === Step removeSamples
INFO - All sample files removed. Now backing up files.
INFO - === Step backupFiles
INFO - File backup skipped.
INFO - === Step backupDb
INFO - Database backup skipped. Now upgrading files...
INFO - Restart requested. Please run the following command to continue your upgrade:
INFO - $ ./modules/autoupgrade/cli-upgrade.php  --dir=admin --channel=private --action=upgradeFile (snip)
php ./modules/autoupgrade/cli-upgrade.php --dir=admin --channel=private --action=upgradeFiles --data=(snip)
(snip)
INFO - All files upgraded. Now upgrading database...
INFO - Restart requested. Please run the following command to continue your upgrade:
INFO - $ ./modules/autoupgrade/cli-upgrade.php --dir=admin --channel=private --action=upgradeDb 
```

```
$ php ./modules/autoupgrade/cli-upgrade.php --dir=admin --channel=private --action=upgradeDb --data=(snip)
INFO - === Step upgradeDb
$ echo $?
255
```
How can I have more logs of the upgradeDb step ?
If I restore a full  backup, then launch the upgrade through Web GUI, it fails also at upgradeDb step wih something like :
```
DROP TABLE IF EXISTS `PREFIX_modules_perfs`;
Unknown column 't0.locale' in 'field list' ... in table ps_lang
```

### Expected behavior

I was hopping my PS1.6 to be fully upgraded to 1.7 :-)

### Steps to reproduce

Launch autoupgrade on 1.6.1.24 to achieve a 1.7 installation

### PrestaShop version(s) where the bug happened

1.6.1.24

### PHP version(s) where the bug happened

7.1.33

### If your bug is related to a module, specify its name and its version

autoupgrade

**Comment by AureRita** [comment]
Hi @pladen 

Thank for your report,
This issue is too technical for me, ping @PrestaShop/prestashop-core-developers, can someone please reproduce this issue ? 

Thanks

**Comment by pladen** [comment]
I've also tried to upgrade from CLI and seems that the same field makes the whole process crash

```
$ php install/upgrade/upgrade.php 
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.locale' in 'field list' in /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117
```
I've added the "locale" field as a empty varchar(32) in ps_lang, and now I can run the DB Upgrade

**Comment by venditdevs** [comment]
@pladen Looks like a similar issue we're encountering. The whole CLI upgrade does not work (good) anymore. No mather the PS version clearly.

[https://github.com/PrestaShop/PrestaShop/issues/31549](url)

**Comment by hibatallahAouadni** [comment]
Hello @pladen 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #31549
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks @venditdevs for your reply :rocket: 

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #31549
