### ISSUE TITLE
prestashop 8.0.2 cannot edit or create categories

### ISSUE THREAD

**Issue by rudolfkastl** [PrestaShop/PrestaShop#31983]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The edit (for setting root category) and create (for creating a new category) buttons are missing.

### Expected behavior

Having both the edit and create category buttons / options displayed.

### Steps to reproduce

1. Click on Categories
2. See missing category management  buttons-
![Bildschirmfoto vom 2023-03-30 23-35-47](https://user-images.githubusercontent.com/33659565/228970539-dd027c15-e5b0-42ad-9d30-4bb39c7a03c8.png)

NOTE: https://myshop.com/admin/index.php?controller=AdminCategories&id_category=1 has everything displayed (the categories and the add / edit options)

### PrestaShop version(s) where the bug happened

8.0.2

### PHP version(s) where the bug happened

8.1

**Comment by rudolfkastl** [comment]
This is the default SQL query for getting the Category overview:
`SELECT COUNT(cp.`id_product`) AS `products_count`, c.id_category, c.id_parent, c.active, cl.name, cl.description, cs.position FROM ps_category c LEFT JOIN ps_category_lang cl ON c.id_category = cl.id_category AND cl.id_lang = 1 AND cl.id_shop = c.id_shop_default LEFT JOIN ps_category_shop cs ON c.id_category = cs.id_category AND cs.id_shop = 1 LEFT JOIN ps_category_product cp ON c.`id_category` = cp.`id_category` WHERE (c.id_category != '800') AND (c.id_parent = 2) AND (c.id_category != '800') AND (c.id_category != '800') GROUP BY c.`id_category` ORDER BY position asc LIMIT 50`

Changing "c.id_parent = 2" to "c.id_parent = 1" shows the categories.

**Comment by AureRita** [comment]
Hi @rudolfkastl 

Thank you for your issue, your issue seems to be the same than this comment : https://github.com/PrestaShop/PrestaShop/issues/31945#issuecomment-1488256771 

This one is corrected by dev. 
can you do a rollback to the previous version and do a new upgrade ? 

Waiting for your feedback

**Comment by AureRita** [comment]
Hi @rudolfkastl 

Thank you for your report. DId you do anything else on the version 8.0.2 ? because I go to the page category and I have all that different element as you can see : 

![image](https://user-images.githubusercontent.com/100699445/229164050-0810d9c7-1e8c-46e9-bb36-0173e4ae7da1.png)

Waiting for your feedback

**Comment by rudolfkastl** [comment]
Actually the Categories are initially from another shop version (1.6.1.7) and the situation is there after upgrading the shop. 
Could you please post what the default sql query is for showing the categories with your fresh install?

Also what i tried is that i enabled multistore to change the "root" of the categories. but when i go to url:
https://myshop.de/admin/index.php?controller=AdminShop&token=sometoken&shop_id=1&updateshop causes an error 500.

**Comment by AureRita** [comment]
Hi @rudolfkastl 

Thank you for the details. Currently, you can't update a shop from the version 1.6.1.7 to a version 8.0.2 you should pass by the 1.7.8.x before. Moreover you said that you were in php 8.1 but on 1.6.1.7 you can't use it. 

Can you try to do an upgrade on a version 1.7 before do it to the 8.0 ? 

About the sql query, I think @PrestaShop/prestashop-core-developers can help you 

Waiting for your feedback

**Comment by hibatallahAouadni** [comment]
Hello @rudolfkastl 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by chico11mbit** [comment]
Same here...
