### ISSUE TITLE
Specific price doesn't take into account the VAT 

### ISSUE THREAD

**Issue by daxitsolutions** [PrestaShop/PrestaShop#31982]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

## Case 1 : When changing the initial selling price for a group of customer

I have a product sell at 10€ with 21% taxes. 
Price HT (VAT excluded) = 10 €
VAT = 2,1 €
Price TTC (VAT included) = 12,1 €

When adding a special price for a group of customer, defining the price to 100 € 
![image](https://user-images.githubusercontent.com/26635105/228944604-55522094-8cbc-4b53-b937-6b3e143298eb.png)

ERROR : the final price doesn't include the correct VAT amount 

![image](https://user-images.githubusercontent.com/26635105/228944734-8b6ce34f-cbc8-48b8-8ce9-489e321e1735.png)

Price should be 
Price HT (VAT excluded) = 10 €
VAT = 21 €
Price TTC (VAT included) = 121 €

instead we have 108,9

## Case 2 : When appling a discount for a certain group of customer 

I have a product sell at 10€ with 21% taxes. 
Price HT (VAT excluded) = 10 €
VAT = 2,1 €
Price TTC (VAT included) = 12,1 €

When adding a special discount for a group of customer, for example 2 € (excl vat) 

ERROR : the original price doesn't include the correct VAT amount 
ERROR : the final price doesn't include the correct VAT amount 

![test](https://user-images.githubusercontent.com/26635105/229094643-08f08f9f-a7cb-4055-86c2-4e38916f5a0f.png)

Price should be 
Price HT (VAT excluded) = 8 €
VAT = 1,68 €
Price TTC (VAT included) = 9,68 €

### Expected behavior

Calculate the correct VAT amount on a product when setup another price excluding VAT

### Steps to reproduce

1. Create a product 
2. setup regular price 10 
3. setup VAT 21% (Belgium)
4. setup a special price for group a user belong to : 100€

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

**Comment by sudo-do** [comment]
Tested on 8.0.2 and issue persists.

**Comment by AureRita** [comment]
Hi @daxitsolutions 

You issue seems to be similar than this issue : https://github.com/PrestaShop/PrestaShop/issues/31910 

What did you think ? 

Waiting for your feedback

**Comment by daxitsolutions** [comment]
@AureRita It's a third case (anotherone), with TTC (VAT included) the example for this issue occurs when the price are HTVA (VAT excluded). 

My specific example did not overide the VAT calculation because we setup price excluded VAT. 

So, maybe related in the code, but functionally it's anotherone.

**Comment by daxitsolutions** [comment]
Issue related to a messy prestashop theme --> I delete everything and start again from scratch. 
It works like a charm now that I came back on the original theme.
