### ISSUE TITLE
Unable to save/edit products with combination after updating to 8.0.2

### ISSUE THREAD

**Issue by bluegifts** [PrestaShop/PrestaShop#31985]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello.
I have an error that happens when i try to add or edit a product with combinations after updating from 1.7.8 to 8.0.2 via 1clickupgrade module. I get an red error message and loading sign that keeps loading forever (only after i hit save or click back to catalog) - see belo
![Screenshot 2023-03-31 at 11 19 30](https://user-images.githubusercontent.com/11062549/229065781-24dbb090-0704-485c-bf5a-dfd3d4c79783.png)

in dev mode and console i get following error:
![Screenshot 2023-03-31 at 11 22 52](https://user-images.githubusercontent.com/11062549/229067608-e5988bba-5aa4-495a-87ef-6323a5014524.png)

![Screenshot 2023-03-31 at 11 24 04](https://user-images.githubusercontent.com/11062549/229067664-a11b808f-a4e3-4377-8dd5-00a9fa97f138.png)

Mentions of solutions that i already found and not applicable in my case: 
- not related to iframe or other html code, description is 100 characters only text
- not related to stock management - i have not enabled the stock management
- i can create and modify product without combinations
- in debug mode i have no error displayed
- cleared cache, etc

Any ideea?

### Steps to reproduce

Go to product page that has a combination and try to save/edit/hit back to catalog.

### PrestaShop version(s) where the bug happened

8.0.2

### PHP version(s) where the bug happened

8.1

**Comment by AureRita** [comment]
Hi @bluegifts 

Thank you for your report, I tried to reproduce your issue but in my shop I can modify products with combination, 
Can you give us more steps to reproduce your issue ? 

Waiting for your feedback

**Comment by bluegifts** [comment]
Hello
All details are in first message, also the errors that i get in dev. 
Don.t know what to mention diffrent.

**Comment by AureRita** [comment]
Hi @bluegifts  ,

Despite my efforts, I'm not able to reproduce your issue with the provided information. @PrestaShop/qa-team Can someone try to reproduce the issue ? 

Thank you

**Comment by bluegifts** [comment]
problem dissapeared when i enabled experimental features - new product page. when disabled problem appeares again..

**Comment by qcol** [comment]
Probably an old bug, you cannot save a product with combinations if you have stock management disabled in the product settings.

**Comment by areaeuro** [comment]
@AureRita  
I was having the same problem on a fresh install of 8.0.3. with Stock management disabled.
Enabling Stock Management allows me to save products with combinations, but is not really what I want to do.
> Probably an old bug, you cannot save a product with combinations if you have stock management disabled in the product settings.

**Comment by RosaBenouamer** [comment]
@AureRita : if as mentionned the issue exists for fresh install perhaps take off the label autoupgrade ?

**Comment by hibatallahAouadni** [comment]
Hello everyone,

@bluegifts did you upgrade your PHP version after upgrading the shop? if you use PHP 8.1 with PS1788 before upgrading, you need to downgrade your PHP version before the upgrade to PHP 7.4, then after the upgrade your shop to 8.0.3 you can upgrade your PHP version  to 8.1.

@areaeuro & @RosaBenouamer I didn't manage to reproduce the issue with PS8.0.2 nor 8.0.3 neither 8.0.4, see the attached screen record below:

[issue_31985.webm](https://github.com/PrestaShop/PrestaShop/assets/23308427/4f08cb03-5342-4a4d-95f1-ecf2c612011a)

Closing the issue as it seems related to your server configuration and not to the Core.

Thanks!
