### ISSUE TITLE
After upgrading 8.0.1 to 8.0.2 cannot upgrade modules via backoffice.

### ISSUE THREAD

**Issue by joecoolio66** [PrestaShop/PrestaShop#31998]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After upgrading from PS 8.0.1 to 8.0.2 we can no longer upgrade modules from the back office.  When attempting we get:

Could not perform action update for module undefined

We tried upgrading two separate sites and the same thing happened.  Upgrading was fine when using 8.0.1 before the upgrade.  We suspect something in the database was not upgraded.

This applied to all modules PS and 3rd party.

### Expected behavior

We should be able to upgrade modules from the back end.

### Steps to reproduce

1. Upgrade PS from 8.0.1 to 8.0.2
2. Go to modules manager
3. Find modules highlighted in the updates tab
4. Try to click upgrade
5. See error > `Could not perform action update for module undefined`

### PrestaShop version(s) where the bug happened

8.0.2

### PHP version(s) where the bug happened

8.1

**Comment by AureRita** [comment]
Hi @joecoolio66 

Thank you for your issue, your issue seems to be the same than this comment : https://github.com/PrestaShop/PrestaShop/issues/31945#issuecomment-1488256771 

This one is corrected by dev. 
can you do a rollback to the previous version and do a new upgrade ? 

Waiting for your feedback

**Comment by joecoolio66** [comment]
I don't believe this is the same issue.

For more information:

In debug mode, when upgrade is clicked for a module, a 406 error is shown... which looks like there may be an issue with the HTTP request.

**Comment by abd983** [comment]
I have the same issue also !!!!!! with clean installation and I tried all PHP versions but same problem
I found solution work good with me
Make debug mode on and upgrade all modules via backoffice after that switch of the Debug mode .... all will work fine
Good luck

**Comment by abd983** [comment]
Make debug mode on and upgrade all modules via backoffice after that switch of the Debug mode .... all will work fine
Good luck

**Comment by joecoolio66** [comment]
Thanks, but that doesn't work.  Entering Debug mode is how I found out I was getting 406 errors when trying to upgrade.

**Comment by SharakPL** [comment]
❗❗❗
@joecoolio66 you should **NEVER** share any link to your shop's admin panel. Please rename your shop's admin folder through FTP/SSH and **never** use any simple name like you have now. Prestashop generates random names (eg. adminklkjjr45jk3h6h54) for security.

**Comment by AureRita** [comment]
Hi @joecoolio66 

With all the provided information, I tried to reproduce you issue as you can see : 

[Untitled_ Apr 4, 2023 11_34 AM.webm](https://user-images.githubusercontent.com/100699445/229751335-9dd06b94-a021-4970-9489-7ac6b8fcc46c.webm)

I tested it with php 8.1 and also with php 7.4 
But currently I didn't have any issue on it, 

Can you give us some videos or anything else about the error ? 

Waiting for your feedback

**Comment by joecoolio66** [comment]
All we can really say is that when debug is enabled, trying to upgrade the module results in 406 errors... so there is something wrong with the configuration which happened after upgrade to 8.0.2.

We upgraded a test site to 8.0.3 and will await new module releases to see if the same issue occurs.  There doesn't seem to be any logging for this anywhere and the error logs contain nothing.

**Comment by joecoolio66** [comment]
main.bundle.js:181          POST https://www.canadacardworld.com/xxxxxxxxxx/index.php/improve/modules/manage/action/upgrade/dashgoals?source=https%3A%2F%2Faddons.prestashop.com%2Fen%2Fdashboards%2F15251-dashboard-goals.html%3Futm_source%3Dback-office%26utm_medium%3Dpush-addons%26utm_campaign%3Dback-office-EN%26utm_content%3Ddownload&_token=Ap6ydT403Ip2WGOMEJTkW2FLti8-6kLPcQtuv5qgRLg 

406

**Comment by joecoolio66** [comment]
When using google's dev tools this is what comes up... x's added for security

**Comment by venditdevs** [comment]
@joecoolio66, We've encountered the same problem but it was resolved after installing the Distriution API Client and clearing all of the cache (delete content in /var/cache). Maybe this works for you.

**Comment by joecoolio66** [comment]
We tried everything... resetting and re-installing the distribution api module, clearing cache... resetting the mbo module... clearing cache... resetting prestashop account.  We upgraded a test site to 8.0.3(from 8.0.2) and it's the same... constant 406 errors when trying to do an upgrade from the back office.  This needs to be resolved as some modules can't be downloaded and installed manually (ie prestashop account).  Any other suggestions would be welcomed.

**Comment by AureRita** [comment]
Hi @joecoolio66 

Could you provide us some module that fails for you ?Maybe it's specific modules ? Moreover, can you update the api module before updating prestashop ? 

Waiting for your feedback

**Comment by joecoolio66** [comment]
All modules fail, 3rd party and prestashop native.  Does anyone know the process on how the upgrade will connect successfully?  There must be a configuration issue whether it be database, permissions, or something is missing.  There has to be a simple reason and fix for this.

**Comment by venditdevs** [comment]
> modules fail, 3rd party and prestashop native. Does anyone know the process on how the upgrade will connect successfully? There must be a configuration issue whether it be database, permissions, or something is missing. There has to be a simple reason and fix for this.

I think it's a faulty module override. I had a testshop last friday with the same message, it was caused by a faulty overide from the DPDConnect module (/override/classes/checkout/DeliveryOptionsFinder).

What you can try to do (with and without debug mode on) is check the inspector of the browser (Chrome preferred) on the network and/or Console tab, update the module and check the complete path/error. Hope this helps.

**Comment by joecoolio66** [comment]
Thanks, but that doesn't seem to work.  We disabled overrides, cleared cache and tried the upgrade with debug on and off.  There was no change.. immediate 406 error when trying to upgrade.  It has to be a configuration error

**Comment by hibatallahAouadni** [comment]
Hello @joecoolio66 

> We disabled overrides

How did you disable the overrides?? in BO? or manually?
Waiting for your feedback.

Thanks!

**Comment by joecoolio66** [comment]
Just in the back office under performance

**Comment by joecoolio66** [comment]
This has been resolved:

Upon closer inspection, apache mod_security was rejecting the upgrade url.  Once added to the white list the error went away.  We're not sure why this started after upgrading from 8.0.1 to 8.0.2... perhaps something triggered a security rule.. it may be worth investigating.

This can be closed

**Comment by hibatallahAouadni** [comment]
Thanks for your feedback :pray:

**Comment by marquand26** [comment]
Hi, 

How do you add the apache mod_security to a white list? Is this with the host?

**Comment by Dar-us-Salam** [comment]
I have the exact same issue while I don't use mod_security as I have LiteSpeed Enterprise instead of Apache. Would I need to contact LiteSpeed support about this? Something seems off in PS 8.1.1 as other users are having the same issue. Please help. Thanks.
