### ISSUE TITLE
xml files contains not escaped illegal caracters as like ampersands '&'

### ISSUE THREAD

**Issue by dominiqueblanc** [PrestaShop/PrestaShop#32004]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

Accordingly the [#17039] case, I modified the file ' fr.xml ' stored in /localization/CLDR/core/common/main, in particular the decimal from (comma) ',' to (point) '.' .

After saving the file, I encountered several parsing errors due to not escaped illegal caracters (ampersands) '&'.

**Errors :**
BO (debug activated) : ("Warning: simplexml_load_file():  ...  /localization/CLDR/core/common/main/fr.xml:1474: parser error : xmlParseEntityRef: no name")

FO : Warning: simplexml_load_file(): ">[\- ‐ ‑ – — , ; \: ! ? . … ’ " “ ” « » ( ) \[ \] § @ * / \& in / ....  src/Core/Localization/CLDR/Reader.php on line 228

FO : Warning: simplexml_load_file(): ^ in / ....  src/Core/Localization/CLDR/Reader.php on line 228

I fixed the issue by writing : ' \&#038; ' instead (on each encountered ampersands) on local files.
I suggest a patch to be applied on the files on the server, hoping it helps.

source : [https://stackoverflow.com/questions/1328538/how-do-i-escape-ampersands-in-xml-so-they-are-rendered-as-entities-in-html](url)

### Expected behavior

I was supposed just to modify the decimal, save the file and done.

### Steps to reproduce

1. Goto to : ' /localization/CLDR/core/common/main '
2. Open the file : ' fr.xml '
3. Modify and save the file (no need to modify something specific in the file, just to make the system saving that file (it was never opened in the FTP since the install)
4. It can be reproduced with any of the xml file containing an ampersand (e.g ' en.xml ')

### PrestaShop version(s) where the bug happened

8.0.0, 8.0.1, 8.0.2

### PHP version(s) where the bug happened

8.0

**Comment by Hlavtox** [comment]
@DomShop Your text editor is messing up that file, I don't think it's a core issue no?

**Comment by dominiqueblanc** [comment]
Hi @Hlavtox,

Thank you for your reply.
I will investigate, thank you for the clue.
So far, I am using FTP Manager but I will try to reproduce the issue with another one.
I wish you a good day.
BR

**Comment by dominiqueblanc** [comment]
Hi @Hlavtox,

You were right !
I tried to modify the xml using Filezilla, and it worked like a charm.
The text editor's behaviour was good to know... Thank you for your help.
Happy Easter
