### ISSUE TITLE
https://../../index.php/sell/catalog/suppliers/ HTTP 500 Internal Server Error (only in the Ukrainian language)

### ISSUE THREAD

**Issue by Kos-tash** [PrestaShop/PrestaShop#32005]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

![image](https://user-images.githubusercontent.com/129620584/229308456-769c0cf1-8f9f-43dc-b337-7d385db9d23c.png)
![image](https://user-images.githubusercontent.com/129620584/229308462-efeb989b-54ee-40f4-9b42-e760682c7604.png)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/129620584/229308498-b455f9cb-0a6f-4eff-b564-a18159b0cc16.png)

### PrestaShop version(s) where the bug happened

PrestaShop 8.0.2

### PHP version(s) where the bug happened

PHP: 8.1.16

**Comment by Kos-tash** [comment]
I switched to PHP Version 7.4.33 and then the problem disappeared. Now the 500 error is not displayed.

PHP Version 8.0.28 also has a 500 error. The server returned a "500 Internal Server Error".

**Comment by florine2623** [comment]
Hello @Kos-tash ,

I tried to reproduce your issue but I can't. I tried with multiple versions of PHP, I still have access to the page. I also added la language Russian, but it doesn't change anything.

It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

I will close this issue.

Thank you

**Comment by Kos-tash** [comment]
> Hello @Kos-tash ,
> 
> I tried to reproduce your issue but I can't. I tried with multiple versions of PHP, I still have access to the page. I also added la language Russian, but it doesn't change anything.
> 
> It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
> 
> We will close this issue.
> 
> Thank you
> 
> I will close this issue.
> 
> Thank you

Hello, @florine2623  Yes, you are absolutely right. I tested and I agree with you that the Russian language works fine. But. I don't speak Russian, and I have Prestashop installed with the Ukrainian language.
Updated Prestashop to version 8.0.4. When the language is set to Russian, there is no error. And if I set the Ukrainian language, the error is on PHP > 8.0

Please check. Waiting for your reply.
