### ISSUE TITLE
 Zero control panel

### ISSUE THREAD

**Issue by MolinoCipolla23** [PrestaShop/PrestaShop#32016]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Since I updated the version of prestashop to 1.7.8.5 I lost counting of statistics, like the "control panel" module no longer communicates with the database, it only kept the past sales, but to date despite the orders it always marks zero
![a0ff9dda-9493-4bfd-bfba-cd56270e1427](https://user-images.githubusercontent.com/129739676/229471468-6bcd4728-0e96-4ba9-ae5e-b8b6ed0aba9a.jpg)

### Expected behavior

The form is supposed to add up the revenue and give me sales statistics

### Steps to reproduce

Andare direttamente sulla Home del backend, il modulo si trova lì

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

Statistiche Dashboard 2.0.4

### Your company or customer's name goes here (if applicable).

Molino Cipolla

**Comment by hibatallahAouadni** [comment]
Hello @MolinoCipolla23 

Please send your request in English. English is the norm on GitHub.
Could you please reset the stats module and check if the stats are back or no?
Waiting for your feedback.

Thanks!

**Comment by MolinoCipolla23** [comment]
I apologize in advance for not having translated the problem well. Yes, I have already reset the module several times but nothing happens, it always remains at zero.

**Comment by AureRita** [comment]
Hi @MolinoCipolla23 

Thank you for your report, can you translate also the steps to reproduce. Moreover, can you tell us wich version did you have before the upgrade, is it an upgrade from the previous version of the module or previous version of presta  ? 
Did you do it with the module 1-click-upgrade ? or with other things ? 

Waiting for your feedback

**Comment by MolinoCipolla23** [comment]
It's an upgrade of the previous version of prestashop, done via 1-click-upgrade I suppose, because due to some technical problems it was the hosting technician who completed the operation.
The version I had before was 1.6.
There is no step to reproduce, just go to the backend dashboard to see the module

**Comment by hibatallahAouadni** [comment]
Hello @MolinoCipolla23 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug. We will close this issue.

Thanks!
