### ISSUE TITLE
Dashboard Orders-reminder html codes

### ISSUE THREAD

**Issue by tm8544** [PrestaShop/PrestaShop#32029]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On dashboard reminders for orders html-codes are incorrect, as if they had been handled with 'htmlspecialchars '.
See attached image.

The example is in Finnish language, but I don't thinks it is due to translation.
original line: Have you checked your [1][2]abandoned carts[/2][/1]?[3]Your next order could be hiding there!
translated line: Tarkistitko [1][2]hylätyt ostoskorit[/2][/1]?[3]Seuraava tilaus saattaa piillä siellä!

The same error appears also with Prestashop 8.0.2.

### Expected behavior

html-codes "strong", "a" and "br" should not be text, but actual html-codes

### Steps to reproduce

1. Go to dashboard
2. Click reminder icon (bell)
3. Click 'Orders'

### PrestaShop version(s) where the bug happened

8.0.3
![Näyttökuva 2023-04-04 075358](https://user-images.githubusercontent.com/15167679/229691746-0e8bd7a3-d065-461b-93f9-7b15404e78c0.jpg)

### PHP version(s) where the bug happened

8.0.28

**Comment by tm8544** [comment]
At least in my case, I was able to solve it with this:

In file 'classes/controller/AdminController.php'

change line 1984
from: `'no_order_tip' => $this->getNotificationTip('order'),`
to: `'no_order_tip' => htmlspecialchars_decode($this->getNotificationTip('order')),`

If this is a proper solution, should it be applied also to line 1985 ('no_customer_tip') and 1986 ('no_customer_message_tip')?

**Comment by florine2623** [comment]
Hello @tm8544 ,

This issue is fixed : https://github.com/PrestaShop/PrestaShop/issues/29940

I'll close your issue to avoid clogging the backlog !
Thanks!
