### ISSUE TITLE
FO - The products 'image are not displayed in order confirmation details page

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#32022]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The products' image are not displayed on the order confirmation details page

**develop : NOK** :x: 
![image](https://user-images.githubusercontent.com/92912932/229524946-a363c0fa-0a38-4743-824a-00ffa48f9106.png)

It's a regression!

### Expected behavior

The images are well displayed

### Steps to reproduce

1. Go to FO
2. Sign in with the customer account
3. Add products to cart
4. Go to checkout
5. Click to checkout
6. See error > The images are not displayed! (No image available)

### PrestaShop version(s) where the bug happened

7.3

### PHP version(s) where the bug happened

develop

**Comment by matks** [comment]
@tleon starts it

**Comment by jolelievre** [comment]
I'm not sure but it may be related to this PR https://github.com/PrestaShop/PrestaShop/pull/32199 especially if it happens only with products created with page v2
