### ISSUE TITLE
[PrestaShop] Fatal error in module file

### ISSUE THREAD

**Issue by artistgentleman** [PrestaShop/PrestaShop#32038]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello everyone,
I'm french and hope my english we'll be good for all of you. Don't have the technic vocabulary.

I came on the site : https://pagebuilder.webshopworks.com/

I clicked "buy now" that redirected me on : https://sites.fastspring.com/globalillusion/product/creativeelements

I purchased "Creative Elements - live Theme & Page Builder" on this page.

Then I received an email from mailer@fastspring.com with my order ID.

Another mail from them telling me to join my "download area" on this website : https://webshopworks.com/download/

I got a ".zip" file named "creativeelements".

I went in my prestashop backoffice to click on "modules and services" to import that same .zip file.

And at this point I got that error message on a withe page (please see the attachment) : 
**[PrestaShop] Fatal error in module file :/home/killbizzcn/www/classes/module/Module.php(1361) : eval()'d code:
syntax error, unexpected 'const' (T_CONST)**

Please tell me you have the solution because everytime I go on the tab "modules and services" I have this error message.

Thank a lot for your help !!!
Corentin

### Steps to reproduce

I purchased "Creative Elements - live Theme & Page Builder" on this page.

Then I received an email from mailer@fastspring.com with my order ID.

Another mail from them telling me to join my "download area" on this website : https://webshopworks.com/download/

I got a ".zip" file named "creativeelements".

I went in my prestashop backoffice to click on "modules and services" to import that same .zip file.

And at this point I got that error message on a withe page (please see the attachment) : 
**[PrestaShop] Fatal error in module file :/home/killbizzcn/www/classes/module/Module.php(1361) : eval()'d code:
syntax error, unexpected 'const' (T_CONST)**

### PrestaShop version(s) where the bug happened

1.6.1.12

**Comment by sudo-do** [comment]
This is not a core issue, module you purchased used may need PHP 5 to work, contract the module dev.

**Comment by KDeluxe2023** [comment]
> This is not a core issue, module you purchased used may need PHP 5 to work, contract the module dev.

the other way around, he's actually using obsolete presta version that is too old for creativeelements

**Comment by florine2623** [comment]
Hello @artistgentleman ,

PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).

Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
