### ISSUE TITLE
ps_emailalert - customer id cannot be empty

### ISSUE THREAD

**Issue by BoutiquesInternet** [PrestaShop/PrestaShop#32037]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Since the lastest module version of ps_emailalerts 2.4.1
When adding new mail alert with customer unlogged, you have an error 
La propriété MailAlert->id_customer est vide. at line 1046 in file classes/ObjectModel.php

### Expected behavior

We expect to register new mail alert when customer is unlogged.

### Steps to reproduce

1. update ps_emailalerts module to 2.4.1
2. be sure to not be logged into your shop
3. add an email that is not a customer email register in your Prestashop
4. see error in your network panel

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_emailalerts

**Comment by florine2623** [comment]
Hello @BoutiquesInternet ,

The steps are not clear enough. Can you send a screen record of your issue ?

> 2. be sure to not be logged into your shop

Do you mean in the back-office or as a customer ?

> 3. add an email that is not a customer email register in your Prestashop

Do you mean in the BO or elsewhere ?

> 4. see error in your network panel

Send a screenshot of the error please.

**Comment by BoutiquesInternet** [comment]
2. I mean as a customer in the front office.
3. I mean in the product page in the front office, in the email field of the module
4. see error below
![image](https://user-images.githubusercontent.com/36631714/230067328-c74e3afe-27cc-4cd0-b772-c4e735892ed1.png)

I fixed this error with a modification in the file \modules\ps_emailalerts\controllers\front\actions.php at line 134
before
`$mail_alert->id_customer = $id_customer;`
after
`$mail_alert->id_customer = (int) $id_customer;`

**Comment by florine2623** [comment]
Thanks @BoutiquesInternet !

I indeed have an issue. In my case, I have an error 500 in the console and the customer never receives an alert or notification when the product is available.
<img width="1440" alt="Screenshot 2023-04-06 at 09 54 40" src="https://user-images.githubusercontent.com/16019289/230312178-a01de29e-c31b-4cb8-9b5d-8ad6f367211f.png">

This is a regression. I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
