### ISSUE TITLE
1 click module not working

### ISSUE THREAD

**Issue by Casadostecidos** [PrestaShop/PrestaShop#32035]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

I'm trying to update the version of my Prestashop, but when I click on the upgrade button nothing happens. I am aware that the entire checklist needs to be green. Can you help me please?

![Upgrade](https://user-images.githubusercontent.com/128379197/229749312-8842b215-cc87-4b9d-93d8-947a7c5b0a44.PNG)

Thanks

### Expected behavior

I'm trying to update the version of my Prestashop, but when I click on the upgrade button nothing happens. 

### Steps to reproduce

![Passo 1](https://user-images.githubusercontent.com/128379197/229749474-3e4729f9-5185-4904-99c2-5647e7009ff3.PNG)
![Passo 2](https://user-images.githubusercontent.com/128379197/229749478-97927224-3cf0-47be-8382-abd07176b732.PNG)
![Passo 3](https://user-images.githubusercontent.com/128379197/229749480-a0c6920f-96cd-47ea-a3b1-47afc5da43b4.PNG)

### PrestaShop version(s) where the bug happened

1.7.5.1

### PHP version(s) where the bug happened

7.2.34

### If your bug is related to a module, specify its name and its version

1-Click Upgrade v4.15.0

### Your company or customer's name goes here (if applicable).

Casa dos Tecidos

**Comment by florine2623** [comment]
Hello @Casadostecidos ,

Please change your Admin name ^^
It is visible to all the community.

On my side I can upgrade correctly my shop.

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by Casadostecidos** [comment]
Hello, 

Our «Custom Dedicated - server» does not display any alerts or notifications.

We check that the /public_html/backoffice/error_log file is checked for the errors that caused the situation.

[05-Apr-2023 15:43:33 Portugal] PHP Warning: count(): Parameter must be an array or an object that implements Countable in /home/casadostecidos/public_html/modules/jxcategoryproducts/src/JXCategoryProductsRepository.php on line 113
[05-Apr-2023 15:43:45 Portugal] PHP Warning: count(): Parameter must be an array or an object that implements Countable in /home/casadostecidos/public_html/modules/jxcategoryproducts/src/JXCategoryProductsRepository.php on line 113

Any suggestions on what might be causing the error?

Thanks
