### ISSUE TITLE
Error with smarty_internal_template Creation of dynamic propery Smarty_Internal_Template

### ISSUE THREAD

**Issue by case90** [PrestaShop/PrestaShop#32059]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I got this error when I activate debug mode and navigate to any legacy controller

![screenshoot](https://user-images.githubusercontent.com/13955678/230135671-fc61bf44-5ad5-4b9e-97f2-cba360ecfb0d.png)

### Steps to reproduce

Enable debug mode and naviaget to any screen with legacy controllers

### PrestaShop version(s) where the bug happened

8.0.2

### PHP version(s) where the bug happened

8.2.0

**Comment by florine2623** [comment]
Hello @case90 ,

PrestaShop 8.0.2 is compatible with PHP 8.1. Please downgrade your PHP version and try again.

https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/

I'll close your issue.
Thanks!
