### ISSUE TITLE
Prestashop 8.0.3 fresh install - Error 500 while clearing cache in BO

### ISSUE THREAD

**Issue by Jonteep** [PrestaShop/PrestaShop#32051]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Clearing cache in a fresh Prestashop 8.0.3 install generates error 500.

### Expected behavior

Clear the cache via BO without any issues. :)

### Steps to reproduce

1. New/fresh install of Prestashop 8.0.3.
2. Put the site in maintenance mode.
3. Upgraded the modules i BO (got notification that three modules needed update).
4. Go to performance > clear cache.
5. Error 500 page.
6. Updated the browser / F5 and the cache cleared.
7. Tried again by clearing the cache via the button in performance > cache and it worked.
8. Tried once again and error 500 occured.
9. Updated the browser (while error 500) and I get a message the cache has cleared.
10. I have tried to delete the var/cache folder so it re-generates, but the issue is still there, I can only clear the cache 50/50 without error 500.

### PrestaShop version(s) where the bug happened

New install of 8.0.3

### PHP version(s) where the bug happened

Apache 2.4 - PHP 8.1

### If your bug is related to a module, specify its name and its version

No module.

**Comment by florine2623** [comment]
Hello @Jonteep ,

I can't reproduce your issue following your steps :

https://user-images.githubusercontent.com/16019289/230125313-d8268e4a-1537-4615-9d88-d9f938e08cb3.mov

I'm using Apache 2.4.54 and PHP 8.1.13.

The cache is cleared properly without any error.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by Jonteep** [comment]
Hi,

The issue is noticeable with all my sites, now running Prestashop 8.0.3 with PHP 8.1.18 and 10.5.17-MariaDB.

Whenever I log into admin, go to performance and click "Clear Cache", I end up with "Oops, an error occured - Error 500" etc. if I then press F5 to refresh the browser, I can see a successfull message that the cache has been cleared. And if I once again click "Clear Cache" (the button) right afterwards, it works. But if I browse the admin area for some time and then go back to performance > clear cache, I get the error 500 and have to repeat F5 and so on.

Best regards,
