### ISSUE TITLE
ps_currencyselector - wrong wording for the description 

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#32056]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The description of ps_currencyselector doesn't describe well the module, as you can see : 

![image](https://user-images.githubusercontent.com/100699445/230096230-6454134c-2f84-4e56-85c7-55e425e465c9.png)

this description is more for the related product than currency selector 

### Expected behavior

wording expected: "Add a currency selector to help visitors from targeted countries purchase on your store."

### Steps to reproduce

1. Have a fresh install of ps 1.7.8.8 or 8.0.1 
2. Go to BO > Improve > Modules > Module Manager 
3. Search "currency" on the search bar 
4. The currency block is in 2.0.1 and the wording is correct 
5. Update the module 
6. /!\ Your currency block is in 2.1.1 and the wording is wrong 

### PrestaShop version(s) where the bug happened

1.7.8.3 - 1.7.8.8 - 8.0.1 

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_currencyselector v2.1.0

**Comment by mflasquin** [comment]
It seems this is not a regression, the PR that change the description of the module is here : https://github.com/PrestaShop/ps_currencyselector/pull/21

**Comment by Julievrz** [comment]
Hello, 
A while ago, we updated all the short descriptions of built-in modules. But there was a mistake with this one. The right short description is "Add a currency selector to help visitors from targeted countries purchase on your store." 

The idea is to match the wording in the brochure (https://app.hubspot.com/documents/4323170/view/76452587?accessId=514827)

**Comment by ArnieO** [comment]
The wording is still incorrect. 
- Prestashop v8.1.7
- Currency block v2.1.1

![image](https://github.com/user-attachments/assets/127000fa-f375-41b7-99dd-edeefe822667)
