### ISSUE TITLE
I installed it using docker, but there is always a problem with ssl

### ISSUE THREAD

**Issue by llqfront** [PrestaShop/PrestaShop#32064]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

https://hub.docker.com/r/prestashop/prestashop
docker pull prestashop/prestashop

docker network create prestashop-net

docker run -ti -p 3307:3306 --network prestashop-net --name prestashop-mysql -e MYSQL_ROOT_PASSWORD=admin123 -d mysql --default-authentication-plugin=mysql_native_password

docker run -ti --name prestashop --network prestashop-net -e DB_SERVER=prestashop-mysql -p 8081:80 -d -e PS_INSTALL_AUTO=0 prestashop/prestashop

Successful installation

My nginx before installation is as follows:
```conf
server {
    listen 80;
    listen [::]:80;
    server_name aaa.com www.aaa.com;
    return 301 https://$host$request_uri;
}
server{
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name  aaa.com www.aaa.com;
    ssl_certificate   /cert/www.aaa.com/ssl.pem;
    ssl_certificate_key  /cert/www.aaa.com/ssl.key;
    ssl_session_timeout 5m;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    location / {
        proxy_set_header X-Forwarded-For proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_redirect off;
        proxy_pass http://localhost:8081;

        # Websocket proxy configuration (optional)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
    location ~ /\. {
            return 403;
    }
    access_log  /data/logs/www/www.aaa.com.log;
}
```
In the install I click enable ssl

I delete the install folder and modify the admin file name
On subsequent visits only the dashboard will be accessible

When accessing other pages, the following error occurs

```html
This page is not working www.aaa.com has redirected you too many times.
Try clearing cookies.
ERR_TOO_MANY_REDIRECTS

```

I also tried not to choose ssl when installing. But if you don’t select it, you can no longer enable the ssl option to be disabled. It’s not whether it’s a status, but it’s completely disabled.

I hope to get help.

If the above method does not work, can I modify the configuration file.
For example, wordpress, I can add a code like https on
Then can we add this too?

### Expected behavior

I delete the install folder and modify the admin file name
On subsequent visits only the dashboard will be accessible

When accessing other pages, the following error occurs
```html
This page is not working www.aaa.com has redirected you too many times.
Try clearing cookies.
ERR_TOO_MANY_REDIRECTS

```

### Steps to reproduce

All completed, started accessing and successfully accessed the dashboard homepage
When clicking on any other page, an error will appear, such as

### PrestaShop version(s) where the bug happened

PrestaShop 8.0.3

**Comment by AureRita** [comment]
Hi @llqfront 

Thank for your report,
This issue is too technical for me, ping @PrestaShop/committers, can someone please reproduce this issue ? 

Thanks

**Comment by justarandomsysadmin** [comment]
Same issue here, latest image from dockerhub, nginx reverse proxy redirecting to ssl and proxy pass http to container with the following options:

``` 
client_max_body_size 16M;
proxy_set_header X-Real-IP  $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Server $host;
proxy_set_header X-Scheme $scheme;
proxy_set_header X-Forwarded-Proto $scheme;
```

Interesting thing is, https during initial install wizzard works totally fine without any errors. And first loading of backend url also looks fine, just after login it starts to look broken and show mixed content errors in dev console.

I've been stuck on this issue trying to find a solution for hours and I came across many people having the same redirect loops when using a reverse proxy. But it can't be due to reverse proxy right? I'm sure there are bunch of people using nginx in front of their applications, but has any dev actually tested if the latest release (docker) is actually working with SSL-Termination?

**Comment by llqfront** [comment]
I have solved it.

**Comment by justarandomsysadmin** [comment]
> I have solved it.

@llqfront So can you share how you fixed it? What was the issue?

**Comment by llqfront** [comment]
> > I have solved it.
> 
> @llqfront So can you share how you fixed it? What was the issue?
I have made some modifications to the source code.

**Comment by llqfront** [comment]
> > I have solved it.
> 
> @llqfront So can you share how you fixed it? What was the issue?

I directly changed the source code
