### ISSUE TITLE
Cart_rule endpoints API to assign product restrictions does not exist.

### ISSUE THREAD

**Issue by LEOMARINO** [PrestaShop/PrestaShop#32077]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

We are integrating Prestashop to an ERP. We find the following peculiarity that seems very strange to us.
We need to create a cart_rule via API with a product_restriction. The problem is that by API we can indicate that there is a product_restriction, as indicated in its documentation or we can see in the blank schema. BUT it does not provide us with a field where we can indicate the id_products that belong to the restriction.

Which seems illogical to me, how can it allow me to indicate that there is a product restriction, but not add which products are part of it.

Thank you very much in advance, stay tuned.

![image](https://user-images.githubusercontent.com/61874013/230404063-3ae638a8-b58e-4eb9-b30f-3ea38dff6bfa.png)

### Expected behavior

There should be an endpoint to indicate via API that id_product belong to the created cart_rule constraint.

### Steps to reproduce

1. I see the documentation provided by prestashop
2. The field we need is not found
3. we check the blank schematic and neither

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8

### Your company or customer's name goes here (if applicable).

Sercom

**Comment by florine2623** [comment]
Hello @LEOMARINO ,

Please send your request in English. English is the norm on GitHub.

Thank you

**Comment by LEOMARINO** [comment]
> Hello @LEOMARINO ,
> 
> Please send your request in English. English is the norm on GitHub.
> 
> Thank you

**Comment by LEOMARINO** [comment]
Sorry, @florine2623 

We are integrating Prestashop to an ERP. We find the following peculiarity that seems very strange to us.
We need to create a cart_rule via API with a product_restriction. The problem is that by API we can indicate that there is a product_restriction, as indicated in its documentation or we can see in the blank schema. BUT it does not provide us with a field where we can indicate the id_products that belong to the restriction.

Which seems illogical to me, how can it allow me to indicate that there is a product restriction, but not add which products are part of it.

Thank you very much in advance, stay tuned.

**Comment by florine2623** [comment]
@LEOMARINO ,

Do not hesitate to edit your full issue in English with the steps to reproduce, before re-opening your issue !

**Comment by LEOMARINO** [comment]
@florine2623 Sorry, now its ok.
