### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by marcosbagno** [PrestaShop/PrestaShop#32073]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

None of my Prestashop store modules are able to update. It seems to be a bug that I don't know about

### Expected behavior

None of my Prestashop store modules are able to update. It seems to be a bug that I don't know about

The modules ask me to be updated, but when I do the operation it doesn't give an error: "Could not perform action update for module undefined"

### Steps to reproduce

1 Forms
2 Forms management
3 Updates
4 Update everything

### PrestaShop version(s) where the bug happened

1.7.8.2

### Your company or customer's name goes here (if applicable).

Global Store di Bagno Marcos Antonio

**Comment by florine2623** [comment]
Hello @marcosbagno ,

I can't reproduce your issue.

https://user-images.githubusercontent.com/16019289/230377160-71f1f7c5-d2c9-45ba-87fd-b1fe8b1f1894.mov

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by marcosbagno** [comment]
Good morning,
I don't understand what you mean by "I can't reproduce your problem". the screenshot is the right one. If I try to update any module ni gives an error, as I wrote.


![Acquisisci schermata Web_6-4-2023_112612_global-shopping eu](https://user-images.githubusercontent.com/114733982
![Acquisisci schermata Web_6-4-2023_112612_global-shopping eu](https://user-images.githubusercontent.com/114733982/230388206-0a788684-3385-4796-9b2d-3a16f4e4391b.jpeg)
/230388138-db7b345c-a84d-43e8-b09b-96d3318ccff3.jpeg)

**Comment by marcosbagno** [comment]
ecco lo screenshot.
![Acquisisci schermata Web_6-4-2023_15112_global-shopping eu](https://user-images.githubusercontent.com/114733982/230388822-f94547a9-f071-4000-beed-7fdf417c58ed.jpeg)
