### ISSUE TITLE
[Spike] Establish a policy to keep javascript libraries up to date regarding the security.

### ISSUE THREAD

**Issue by lartist** [PrestaShop/PrestaShop#32084]
Here are some questions to answer:
1. Which tool do we use to check known security vulnerabilities?
2. What if a vulnerability is only patched in a next minor or major version?
3. Security checker tools raises many types of errors, which one do we consider as a security issue

**Comment by boherm** [comment]
On it!

**Comment by boherm** [comment]
It's done.
I made a [notion page](https://www.notion.so/prestashopcorp/Etablish-a-policy-to-keep-javascript-libraries-up-to-date-regarding-the-security-b6437aa72e044ed9ac7be2480ff8e4b2?pvs=4) that can be used to discuss about this subject.

**Comment by Progi1984** [comment]
@boherm The notion page is not public.
