### ISSUE TITLE
On April 5, I made a request to withdraw my money from the seller's account. my money has not been sent to me and no one at support is answering my questions. what the hell is going on?

### ISSUE THREAD

**Issue by Rus-Design** [PrestaShop/PrestaShop#32086]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On April 5, I made a request to withdraw my money from the seller's account. my money has not been sent to me and no one at support is answering my questions. what the hell is going on?

### Expected behavior

On April 5, I made a request to withdraw my money from the seller's account. my money has not been sent to me and no one at support is answering my questions. what the hell is going on?

### Steps to reproduce

On April 5, I made a request to withdraw my money from the seller's account. my money has not been sent to me and no one at support is answering my questions. what the hell is going on?

### PrestaShop version(s) where the bug happened

1

**Comment by AureRita** [comment]
Hi @Rus-Design  ,

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. even if the support doesn't answer. If you need support, the link of the support (if you didn't used it)  : [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Thank you

**Comment by matks** [comment]
I think @Rus-Design you are referring to https://addons.prestashop.com/

This GitHub repository is about the prestashop project, not the prestashop company. If you need to discuss with people from Addons team please use the contact methods of https://addons.prestashop.com/ .
