### ISSUE TITLE
Default password for development environment

### ISSUE THREAD

**Issue by BElluu** [PrestaShop/PrestaShop#32088]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,
In documentation we have information about default credentials
https://devdocs.prestashop-project.org/8/contribute/contribute-pull-requests/contribute_using_docker/
![image](https://user-images.githubusercontent.com/11333925/230639919-794b442f-aa78-48fc-8c48-096f2e31ff38.png)

But password is wrong. Password set in docker-compose.yml is "**Correct Horse Battery Staple**". We should change default password in docker-compose or change information in documentation.

### Expected behavior

Same password in docs and docker-compose.

### Steps to reproduce

Check docs and docker-compose.yml :)
https://devdocs.prestashop-project.org/8/contribute/contribute-pull-requests/contribute_using_docker/

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8

**Comment by hibatallahAouadni** [comment]
Hello @BElluu 

Thanks for reporting this issue 👏 
Indeed it's a regression caused by this commit https://github.com/PrestaShop/PrestaShop/commit/5beb48c25514b06ea0b191f5b4df849854a4ea4f in this PR #28724
@boubkerbribri I think we should update the documentation [here](https://devdocs.prestashop-project.org/8/contribute/contribute-pull-requests/contribute_using_docker/).

Thanks!

**Comment by boubkerbribri** [comment]
Yes we should update the documentation because the new password is for the new password policy.

**Comment by thomasnares** [comment]
Forwarded the issue in https://github.com/PrestaShop/docs/issues/1641 👍 
Thanks @BElluu
