### ISSUE TITLE
Problems with the search engine

### ISSUE THREAD

**Issue by aloisejulian** [PrestaShop/PrestaShop#321]
I have a problem with the search engine. when I look up a word eg "eraser"..But, results not shown me all the erasers in my store... Just find two. This happend with all articles, the results aren't perfect...The indexiation is OKEY... 2600 of 2600... I use prestashop 1.5

Thanks

**Comment by marionf** [comment]
Hello, 
This issue is old, so I close it.
If you still have it on the last version (PrestaShop 1.7.4.2), please open a new one.
Regards
