### ISSUE TITLE
In version 8.0.2 or 8.0.3 the site has the language selection English and Spanish in it. In home page when choosing the language in create a url with index

### ISSUE THREAD

**Issue by DevCorchid** [PrestaShop/PrestaShop#32101]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Using version 8.0.2 or 8.0.3 the site has the language selection English and Spanish in it. On the home page when choosing the language create a URL with the index at the end.
Example
mysite.com/en/
When changing the language on the homepage looks like
mysite.com/es/**index**

Resulting in a 404 because the homepage is at /en/ not /en/index

This also happens vise-versa. Does anyone know how to fix this? This looks like a bug.

### Expected behavior

It should stay on the homepage. 
mysite.com/en/ (for English)
mysite.com/es/(for Spanish)

### Steps to reproduce

1. Add a language for example Spanish
2. Go to the front-end homepage.
3. In the top header there should be the language selection change the language and it will add the  "**index**" the the end of the URL

### PrestaShop version(s) where the bug happened

8.0.2 and 8.0.3

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

Translations

**Comment by DevCorchid** [comment]
Issue with friendly URLs

**Comment by hibatallahAouadni** [comment]
Thanks for your feedback 🙏

**Comment by DevCorchid** [comment]
> Thanks for your feedback 🙏

The confusion is because the friendly URL for the index homepage has the red * as required but it will allow saving the field without any information.
