### ISSUE TITLE
PS 1.7.8.7. on PHP 7.x: Payment Problems

### ISSUE THREAD

**Issue by PrestaVision** [PrestaShop/PrestaShop#32108]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In 2022 I used PS 1.7.8.7 on PHP 7.4 and Mollie's payment module. Now that I'm working on the accounting and administration for 2022, I discovered the following problem:

some payment notifications in Back Office > Orders at the bottom of Payment show the following for a payment: (see image)

the amount to be paid is transferred in 2 parts to Mollie from the customer's account on the same date and at the same time; not a problem in itself, because the total amount is equal to both parts. So far so good...

However, with Mollie only the first part of the payment is registered!! The 2nd part is not listed with Mollie and will not be paid to you later!!

I approached Mollie about this and was turned down:
first it would be up to Prestashop, and after a screenshot of the payments I have to ask my customers for a copy of the bank statement of the transfer, and only then do they want to investigate further.

The problem is that it is not a one-off error/problem, but a much more frequent occurrence.
My question is:
1. why a payment is read or created by Prestashop in 2 parts,
2. how the customer has paid from his account,
3. why Mollie does not register that 2nd partial payment,
4. this problem A. lies with the bank, B. lies with Prestashop, C. lies with Mollie or with Mollie's module.

---

I'm really not going to bother my customers after months and sadly ask for a copy of their bank statement; I have more to do and I don't want to sound like a jerk. For the time being, I'll take those losses for granted and adjust my invoices with an extra discount; It is what it is.

What I am furious about is that Mollie is laying the problem with Prestashop and with me as a webshop owner.
I want to know:
A. if this only happens to me
B. how often this happens to others
C. what causes the error 1. Prestashop, 2. the Mollie module, 3. banking or, 4. Mollie itself
D. how this can be solved Mollie is not done with me yet, because this is costing me a lot of time and money now.
![probleem thumb jpg 913a208f41f85efe2aad294b8ee8849f](https://user-images.githubusercontent.com/119726053/231102852-7407aa03-3f69-4869-9579-5c64016297f6.jpg)

### Expected behavior

If Prestashop creates a payment in backoffice and sends it to the payment provider:

1. payment must be in total
2. payment amount must be the same as on the invoice
3. payment must be in just one line of creating the payment, not two
4. payment creation should be double checked against the payment creation rolling out
5. 5. multiple payment orders never should have an identical time- and datestamp

### Steps to reproduce

I use PHP 1.7.8.7 on PHP 7.x, with Mollie v5.3.1. module

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.x

### If your bug is related to a module, specify its name and its version

mollie v5.3.1

### Your company or customer's name goes here (if applicable).

PANDORRAH

**Comment by PrestaVision** [comment]
**UPDATE:**

after communicating with Mollie  I have made a bit more progress:

1. Prestashop generates and sends the payment, not Mollie. Mollie only processes the payment generated from Prestashop.

2. in my case (case study 1, Prestashop 1.7.8.7. on PHP 7.x) the total amount on the invoice is €93.30. Prestashop creates 2 partial payments, with an identical date and time stamp, namely €92.67 and €0.63. See image. Mollie receives and confirms the partial payment of €92.67 and transfers it to us. This is confirmed to the bottom left of the image.

The following questions remain:

A. how does Prestashop create and process a payment request?

B. how can this be created in parts? What causes this?

C. why does Prestashop send partial payments with an identical date and time stamp? How can this happen and how can it be prevented?

D. why is only the first part of the created partial payment sent, and never the second part? So I have had this problem several times in 2022 with multiple orders.

E. How can Prestashop communicate better with a payment module like Mollie? For example, by checking the total invoice amount against the payment requests created?

F. who is responsible for this? Not liable, because I use all software at my own risk, so that ship has sailed... But who is responsible for the programming in this one? Who is the point of contact? Again, I'll take the losses on this one. But I do want it resolved, and Prestashop will really have to come up with an answer.
![payment error](https://user-images.githubusercontent.com/119726053/231104120-8acbf1c1-7ff1-475e-b454-a7f2eb908669.jpg)

**Comment by AureRita** [comment]
Hi @PrestaVision  ,

Thank you for your report, We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

You can give them all the different screenshot and I think they'll have all the answer your need 

Thank you
