### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [PrestaShop/PrestaShop#32100]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by matks** [comment]
Hello @igibek and thank you for reaching out!

Security issues can be reported by sending an email to security@prestashop.com or by our [YesWeHack Bug Bounty Program](https://yeswehack.com/programs/prestashop), which will go to security team members.

We have seen the Private vulnerability reporting feature published by GitHub but using a bug bounty allows for more advanced management of vulnerabilities, including rewarding securiy researchers 😉
