### ISSUE TITLE
ps_emailalerts - Product availability notification does not work, but only for unregistered user

### ISSUE THREAD

**Issue by CaesaR2005** [PrestaShop/PrestaShop#32102]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,

I have installed the module mail alerts of prestashop : version v2.4.1 and prestashop 1.7.8.8.

Product availability notification does not work, but only for unregistered user.

![image](https://user-images.githubusercontent.com/130400392/230986516-2d13833e-e5ae-4a16-9124-588d73ddbe9a.png)

After clicking on the banner nothing happens, no message...

In the case of a logged-in user, after clicking on the above-mentioned banner is information:

![image](https://user-images.githubusercontent.com/130400392/230987643-80a7beb5-f1d1-4fa4-bc74-54cc57f96468.png)

so it worked fine in this case.

Thanks for your help

### Steps to reproduce

1 find a product unavailable on the store's website
2 make sure you are not logged in to your store account 
3 enter the emails in the fomr
4 confirm
5 no message, no confirmation of saving the product availability notification request

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

ps_emailalerts v2.4.1

**Comment by Kero34** [comment]
Same here.
Error 500 module/ps_emailalerts/actions?process=add
![firefox_bO7SUYonN1](https://user-images.githubusercontent.com/43095348/230995281-a757f79f-fb85-4064-b23a-84d789059607.jpg)

**Comment by CaesaR2005** [comment]
I confirm, I check, the console comes to the rescue, I confirm the error

![image](https://user-images.githubusercontent.com/130400392/231086699-d8a5d99a-acb9-4a59-a8c8-d0fd30384165.png)

What should be done in this situation? :-)

**Comment by CaesaR2005** [comment]
In my case, the solution to the problem proposed in the solution

https://github.com/PrestaShop/PrestaShop/issues/32037

"I fixed this error with a modification in the file \modules\ps_emailalerts\controllers\front\actions.php at line 134"

before
$mail_alert->id_customer = $id_customer;
after
$mail_alert->id_customer = (int) $id_customer;

Wow THX :-)

**Comment by hibatallahAouadni** [comment]
Thanks for your feedback 🙏

**Comment by hibatallahAouadni** [comment]
Duplicate of #32037
