### ISSUE TITLE
Php 8.1 Page Admin categories

### ISSUE THREAD

**Issue by nbao** [PrestaShop/PrestaShop#32119]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

![image](https://user-images.githubusercontent.com/5112514/231215380-ab437d52-1e24-47cf-8393-adefc9772489.png)
Fantal Php error stripslashes must have value.

### Steps to reproduce

1. update prestashop 1.7.8.8 to 8.0.3
2. go to Admin page categories

### PrestaShop version(s) where the bug happened

8.0.3

### PHP version(s) where the bug happened

8.0

### Your company or customer's name goes here (if applicable).

atragene

**Comment by nbao** [comment]
please check if not empty
```
        foreach ($records as $key => $record) {
          if(!empty($record['description'])){
            $records[$key]['description'] = mb_substr(strip_tags(stripslashes($record['description'])), 0, self::DESCRIPTION_MAX_LENGTH);
          }
        }
```

**Comment by hibatallahAouadni** [comment]
Hello @nbao 

I didn't manage to reproduce the issue with the provided infos 😞 
But it seems your issue similar to this one which the author found a solution for it, please read his [comment](https://github.com/PrestaShop/PrestaShop/issues/31075#issuecomment-1407763352).
Please check and feedback.

Thanks!

**Comment by nbao** [comment]
Because when you export database in php application like phpmyadmin or adminer or prestashop/admin/configure/advanced/backups/ It will rewrite the empty field in INSERT sql with NULL.
this error comes from code 2 years ago with php 7.2 So developer can't test this error at this moment
![image](https://user-images.githubusercontent.com/5112514/231785373-b758eadd-e2c0-4fa7-bd43-1fcfddf738e1.png)
it fixes with empty check 

if(!empty($record['description'])){
            $records[$key]['description'] = mb_substr(strip_tags(stripslashes($record['description'])), 0, self::DESCRIPTION_MAX_LENGTH);
          }

**Comment by hibatallahAouadni** [comment]
Hello @nbao 

Thanks for the technical detils but could you please provide clear and concise steps to reproduce the issue 🙏 
Waiting for your feedback.

Thanks!

**Comment by florine2623** [comment]
Hello @nbao ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Comment by Tofandel** [comment]
I have the same issue upgrading from an old version

To reproduce simply go into the database and set a category description to `null` in the `ps_category_lang` table

The description field is `nullable` in the database, so this is a valid bug and creating a description in older versions of prestashop would create them with a `null` description, in recent versions they are created with an empty string which is why this issue does not normally pop up

```
INSERT INTO `ps_category` (`id_category`, `id_parent`, `id_shop_default`, `level_depth`, `nleft`, `nright`, `active`, `date_add`, `date_upd`, `position`, `is_root_category`) VALUES
(1, 0, 1, 0, 1, 246, 1, '2013-11-13 13:56:15', '2013-11-13 13:56:15', 0, 1);
INSERT INTO `ps_category_lang` (`id_category`, `id_shop`, `id_lang`, `name`, `description`, `additional_description`, `link_rewrite`, `meta_title`, `meta_keywords`, `meta_description`) VALUES
(1, 1, 1, 'Root', NULL, NULL, 'root', NULL, NULL, NULL);

```

A workaround is to run this query `UPDATE ps_category_lang SET description = '' WHERE description IS NULL`

**Comment by kmorgen** [comment]
I confirm I have the same problem when updating PS 1.7.8.10 to PS 8.1.1 (PHP 8.1) with 1-click Upgrade V4.16.3.
Cannot access several menu points like Categories.

Running this SQL Query: UPDATE ps_category_lang SET description = '' WHERE description IS NULL
also solved it for me.

**Comment by PascalB67** [comment]
Hi, 

![Capture d'écran 2024-02-22 175341](https://github.com/PrestaShop/PrestaShop/assets/93264859/6afc3b1a-1148-4add-96b3-7cc6ea7e5349)

Same problem after update to 8.1.3 from 1.7.8
UPDATE ps_category_lang SET description = '' WHERE description IS NULL return 0

**Comment by jookyltd** [comment]
Change code : 
protected function modifyRecords(array $records): array
    {
        foreach ($records as $key => $record) {
            //$records[$key]['description'] = mb_substr(strip_tags(stripslashes($record['description'])), 0, self::DESCRIPTION_MAX_LENGTH);
            if( $record['description'] ){
            $records[$key]['description'] = mb_substr(strip_tags($record['description']), 0, self::DESCRIPTION_MAX_LENGTH);
            }
        }

        return $records;
    }

**Comment by jookyltd** [comment]
protected function modifyRecords(array $records): array
    {
        foreach ($records as $key => $record) {
            //$records[$key]['description'] = mb_substr(strip_tags(stripslashes($record['description'])), 0, self::DESCRIPTION_MAX_LENGTH);
            if( $record['description'] ){
            $records[$key]['description'] = mb_substr(strip_tags(stripslashes($record['description'])), 0, self::DESCRIPTION_MAX_LENGTH);
            }
        }

        return $records;
    }

**Comment by jookyltd** [comment]
mysql repair : DELETE FROM `ps_category` WHERE `id_category` NOT IN (select id_category FROM `ps_category_lang`)
