### ISSUE TITLE
Autoupgrade -FO - The FO is broken with an exception after the upgrade from 1788 to 8.0.3 when debug mode is enabled

### ISSUE THREAD

**Issue by HanaRebaiQA** [PrestaShop/PrestaShop#32113]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The FO is broken with an exception after the upgrade from 1788 to 8.0.3 when debug mode is enabled

![image](https://user-images.githubusercontent.com/92912932/231155797-ed109908-5dc9-4c86-8abb-7a3b26b3702c.png)

https://user-images.githubusercontent.com/92912932/231156040-99506de4-cf0a-4548-9d22-a6121d5c4ea5.mp4

### Expected behavior

The FO is well displayed when debug mode is enabled after the upgrade !

### Steps to reproduce

1. Install PS1788
2. Install the `autoupgrade module v4.16` from dev branch
```
3. cd modules > git clone git@github.com:PrestaShop/autoupgrade.git
4. cd autoupgrade 
5. git pull --rebase origin dev
6. composer install
```
3. Under admin-dev > autoupgrade > put the 8.0.3.zip and .xml
4. Configure the module
5. Choose the local archive and select the 8.0.3.zip and 8.0.3.xml
6. Do the upgrade
7. Check that the upgrade is successful and connect to the shop
8. BO > CONFIGURE > Advanced parameters > Enable debug mode
9. Click to View my shop
10. See error >> The FO is broken!

### PrestaShop version(s) where the bug happened

8.0.3

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

autoupgrade v4.16.0 from dev branch

**Comment by hibatallahAouadni** [comment]
Hello @HanaRebaiQA 

I didn't manage to reproduce the issue :disappointed: 
From 1788 to 803 with autoupgrade v4.16 (dev branch) whatever the maintainance mode is enabled or diabled.
Could you please provide more infos :pray: 

Thanks!

**Comment by HanaRebaiQA** [comment]
@hibatallahAouadni Thanks for your feedback!
Did you check that debug mode is ON ? You can enabled it even before the upgrade

**Comment by hibatallahAouadni** [comment]
Hello @HanaRebaiQA 

Yes! I did :wink: and still can't reproduce the issue :disappointed: 
Could you please provide more details. Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @HanaRebaiQA 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
