### ISSUE TITLE
Free Order error placing order

### ISSUE THREAD

**Issue by Rventura1989** [PrestaShop/PrestaShop#32111]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Free order, gives error on order confirmation in front office. Order is placed and appears in backoffice but without associated status, and customers do not receive any email.

### Expected behavior

Order confirmation page placed in the frontoffice and in backoffice order associated with paid status

### Steps to reproduce

1. Add free items to cart
2. Finalize the order with all steps
3. place your order
4. Error visible
5. Go to backoffice order list
6. Visible Error

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @Rventura1989 

I didn't manage to reproduce the issue with PS1788, see the attached screen record below:

[issue.webm](https://user-images.githubusercontent.com/23308427/231474446-c42536fb-7b5b-4939-8698-4a5e56a65cf7.webm)

Please check and feedback.

Thanks!

**Comment by Rventura1989** [comment]
Hello,

Thank you very much for your answer.

I saw your video and in my case the error occurs as per video I send
attached.

Could it be my theme?

Thank you very much

**Comment by AureRita** [comment]
Hi @Rventura1989 

Can you send your video in the website and not in the mail ? Currently we can't see it 

Waiting for your feedback

**Comment by Rventura1989** [comment]
Hi @AureRita,

Sorry,
[recording-2023-04-12-17-22-16.webm](https://user-images.githubusercontent.com/95083228/231824733-41334025-ba73-42fb-b3aa-14249fee5db0.webm)

**Comment by hibatallahAouadni** [comment]
Hello @Rventura1989 

Could you please check your screen record cause it display only this page without any action:

![image](https://user-images.githubusercontent.com/23308427/232739043-a12f926b-e1f8-40e7-a362-8bcb7441a806.png)

Please check and feedback.

Thanks!

**Comment by florine2623** [comment]
Hello @Rventura1989 ,

Please change your admin folder name. This is a public space and your admin should not be displayed openly ^^

I'll close your issue as we do not have any answer from you.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
