### ISSUE TITLE
addons.prestashop login loop

### ISSUE THREAD

**Issue by teemoguy2001** [PrestaShop/PrestaShop#32121]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Whenever I try to log into addons.prestashop I get stuck in a loop of trying to log in.
It displays "My account - You already have an account on PrestaShop Addons? Login now!"

I log in with correct credentials and it sends me right back to the same page. It's been like this for a couple months now for me, I thought it would fix itself. 

### Expected behavior

Should be able to log in and be able to do what I need to do in there

### Steps to reproduce

1. Go to addons.prestashop.com 
2. Log in
3. "My account - You already have an account on PrestaShop Addons? Login now!" Should appear
4. Click login
5. You should be redirected to the same "My account - You already have an account on PrestaShop Addons? Login now!" page

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

1.7.8.0

### If your bug is related to a module, specify its name and its version

N/A

### Your company or customer's name goes here (if applicable).

N/A

**Comment by hibatallahAouadni** [comment]
Hello @teemoguy2001 

Your issue is not a PrestaShop core bug.
Please contact support team on Addons.

We will close this issue.

Thanks!
