### ISSUE TITLE
Cannot Upgrade module xxxxxx. Handler not found for source

### ISSUE THREAD

**Issue by joecoolio66** [PrestaShop/PrestaShop#32129]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

We are getting odd errors when trying to upgrade modules from the back office  For example:

Cannot Upgrade module dashtrends. Handler not found for source https://addons.prestashop.com/en/dashboards/15253-dashboard-trends.html?utm_source=back-office&utm_medium=push-addons&utm_campaign=back-office-EN&utm_content=download

We tried resetting distributionapi, mbo, and ps_account modules and logging out and back in as well as clearing cache.  There doesn't seem to be any errors recorded anywhere for this.  We can't find the root of the issue.   It may be a server configuration issue as it's happening on our 8.02 live and 8.03 test site.

### Expected behavior

Modules should update from the back office

### Steps to reproduce

This may be hard to reproduce

### PrestaShop version(s) where the bug happened

8.02 and 8.03

### PHP version(s) where the bug happened

8.1

**Comment by joecoolio66** [comment]
Additional information:

Two of the modules we're having issues with upgrading from the back end (dash goals and dash trends) we decided to download direct from github and manually install.  When we try to install the downloaded zip files we get:

Installation of module failed. This file does not seem to be a valid module zip

Perhaps this is more of an issue with the configuration of the modules themselves?  Any feedback would be appreciated

**Comment by joecoolio66** [comment]
It looks to us like the packages that facilitate these upgrades are not published on github which is causing issues.  Perhaps they were bundled into 8.0.3 or something else changed.

**Comment by NicolasCador** [comment]
Hi all,

I've exactly the same problem on several modules
![image](https://user-images.githubusercontent.com/96910631/231748767-2ce32574-3753-426c-b239-74c24cd2e3e1.png)

**Comment by joecoolio66** [comment]
This seems like a configuration issue on the prestashop side.  It's getting confusing and more convoluted with the marketplace module, distribution api module and the prestashop account module.  Sounds like this could all be one module.

**Comment by AureRita** [comment]
Hi @joecoolio66 

Thank you for your report, currently with the provided information, I can't reproduce your issue, 

Can you give us : 
-  Modules that you want to upgrade, 
- The version of distibution api
- Can you provide us a video ? 

Waiting for your feedback

**Comment by NicolasCador** [comment]
Hi @AureRita,

let's start by the 6 modules I shown on the print screen on my last post https://github.com/PrestaShop/PrestaShop/issues/32129#issuecomment-1506824938, you have the 6 module names, the screenshot is clear on the error and FYI, my distribution API version is:
<img width="932" alt="Capture d’écran 2023-04-13 à 16 32 34" src="https://user-images.githubusercontent.com/96910631/231793160-6944f310-8854-4499-9093-0f806d8195ab.png">

**Comment by przemexm** [comment]
I have the same problem, updating modules worked before, I didn't do anything in the store and suddenly I can't update them in the Modules tab

![1](https://user-images.githubusercontent.com/77234765/231978723-c5c5649f-e81f-4ea7-a508-8f1d208e093e.jpg)

![2](https://user-images.githubusercontent.com/77234765/231978667-c81ab79d-2b99-4fc1-bc12-0dcc96d5df60.jpg)

It's probably a global PrestaShop 8 error because more and more people have a problem with it, neither changing the php version nor turning on the technical break helps, interestingly, after installing the store, it was going to update the modules and suddenly this error appeared.

**Comment by joecoolio66** [comment]
Someone must know why this is happening and be able to explain it!

**Comment by royalcloudmining** [comment]
Hi, got same issue here !
![image](https://user-images.githubusercontent.com/91324492/232167554-396ab467-24cc-47ff-90d2-971f3ab1f181.png)

**Comment by GRANTIOX** [comment]
I have the same problem
PS 8.0.2 / PHP 8.1
![Screenshot 2023-04-15 191321](https://user-images.githubusercontent.com/130856235/232237348-1bfba588-5310-480a-af48-13eedaae3754.png)

**Comment by przemexm** [comment]
This is a global bug, maybe in the next update it will be corrected, but it is not known who to report it to.

**Comment by hibatallahAouadni** [comment]
Hello @joecoolio66 

I didn't manage to reproduce the issue with `ps_distrubtionapi` v1.0.2, see the attached screen record below:

[issue_32129.webm](https://user-images.githubusercontent.com/23308427/233001785-572f5b79-afd9-490a-93b0-bbc95a7c9e1e.webm)

So, could you please upgrade this module `ps_distrubtionapi` and then upgrade all modules 😉 
Please check and feedback.

Thanks!

**Comment by przemexm** [comment]
Where to download the new ps_distrubtionapi module? or how to update it?

**Comment by przemexm** [comment]
I have the store version
ps_distributionapiclient
v1.1.0 - z PrestaShop 

I found version 1.0.2 here
it's probably an older version  https://github.com/PrestaShop/ps_distributionapiclient/releases/tag/v1.0.2

I install it 1.0.2 

![snap](https://user-images.githubusercontent.com/77234765/233021268-eeaf8369-65d9-44c0-b8ca-edd145172617.jpg)

I install it but the version is still in the modules
ps_distributionpiclient
v1.1.0 - from PrestaShop

![snap2](https://user-images.githubusercontent.com/77234765/233021519-c3d2f7be-4034-4238-b94d-ccc3001092c6.jpg)

but it doesn't change anything

Modules still fail to update

**Comment by rnervi** [comment]
same here. just installed a fresh 8.0.2 and "9 module updates" dont update at all with same error :(


> _Cannot Upgrade module statsbestcustomers. 
> Handler not found for source https://addons.prestashop.com/en/analytics-statistics/15265-best-customers.html?utm_source=back-office&utm_medium=push-addons&utm_campaign=back-office-EN&utm_content=download_

**Comment by joecoolio66** [comment]
Everyone needs to stop suggesting different versions or techniques to update their modules.  This is obviously a global configuration issue that someone at prestashop has to be aware of and should be explaining in here what it is, how it occured and what they are doing about it.  These are fundamental things here.. this can't be allowed to happen

**Comment by AureRita** [comment]
Hi @przemexm 

To correctly install the version 1.0.2, you should uninstall the module v.1.1.0 (and check the checkboxe to delete it into your database,etc ) after that, you can install correctly the version 1.0.2, can you tell me if with this solution you can update your module ? 

@joecoolio66 Currently, we propose solutions for contributors to let them update their modules, We know that this issue is very disturbing but to be able to find the problem, we must first understand if it comes from the version, the configuration, or a version of PHP.  This is why we offer solutions to update the other modules, because if it works we already have a point on what works and we can compare them

Waiting for You feedback

**Comment by przemexm** [comment]
It doesn't help starting that when uninstalling the module there is no option to delete from the msql database, there is an option to delete files from the server, which I mark with a tick, i.e. Optional: deleting the module folder after uninstalling.
This action cannot be undone.

I download the version from this page https://github.com/PrestaShop/ps_distributionapiclient/releases/tag/v1.0.2 I install, the module is installed correctly and in the admin panel I still have the module in version 1.1.0

![233021519-c3d2f7be-4034-4238-b94d-ccc3001092c6](https://user-images.githubusercontent.com/77234765/233133889-0ca13d1f-1ca8-419d-af6d-125a187bc354.jpg)

**Comment by przemexm** [comment]
I install the correct version because I see in the ps_distributionpiclient.php zip file that it is $this->version = '1.0.2';

why does it not change to the older version after reinstalling? the more that the newer physically, its files are deleted from the server

public function __construct()
    {
        $this->name = 'ps_distributionapiclient';
        $this->displayName = $this->trans('Distribution API Client', [], 'Modules.Distributionapiclient.Admin');
        $this->description = $this->trans('Download and upgrade PrestaShop\'s native modules.', [], 'Modules.Distributionapiclient.Admin');
        $this->author = 'PrestaShop';
        $this->version = '1.0.2';
        $this->ps_versions_compliancy = ['min' => '8.0.0', 'max' => _PS_VERSION_];
        $this->tab = 'market_place';
        parent::__construct();
    }

**Comment by fran1096** [comment]
I have downloaded prestashop 8.0.2 to test locally. I am using php version 8.1.
No new theme or module was installed, just tested from scratch. It does not update any modules.

![image](https://user-images.githubusercontent.com/114681839/233345302-31320736-d147-49c3-92af-1e119e6de2cf.png)

**Comment by NicolasCador** [comment]
Hi @joecoolio66,

you should write something to remove the "waiting for author" label

Thanks

**Comment by joecoolio66** [comment]
Lol.. nothing to add.. people are having the same issues.  Someone must know why this is happening, can explain it and set expectations here

**Comment by joecoolio66** [comment]
Everyone, don't do that, the current release of mbo is 4.4.1.  Ironically this updated fine for me today from my back end.  I have no idea what's going on

**Comment by fran1096** [comment]
It's very weird, we'll wait for another version to be released then...

**Comment by przemexm** [comment]
I am afraid that the next version may not solve the problem, and it is not known whether it is possible to update the modules if it is not possible to update the version.

**Comment by joecoolio66** [comment]
We upgraded our main site to 8.0.3... and with that all modules became up to date.  Ever since we've had no problem upgrading our modules on our main site from the back end... no errors.  However... this is not the same for our test site... which is also 8.0.3 but we can't seem to upgrade modules (we get the handler error).  This HAS to be a configuration issue... and someone must know what to change to fix it.

**Comment by Pitxiglass** [comment]
Hello, I can confirm that I cannot update any module either, I have the same error reported here, the Prestashop version is 8.0.2 with PHP 7.4.33

**Comment by hennaboy** [comment]
Highly likely it is a 3rd party module causing this.

For myself it was a payment module. Turn on debugging and attempt to update a module and check the errors.

**Comment by AureRita** [comment]
Hello, 

Despite our efforts, we were not able to reproduce your issue with the provided information. As @joecoolio66 said i, it seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Try to follow what @hennaboy said, try to disable your payement module and try to update them again 

Thank you

**Comment by Pitxiglass** [comment]
> Highly likely it is a 3rd party module causing this.
> 
>" For myself it was a payment module. Turn on debugging and attempt to update a module and check the errors."

In my case it is not the payment modules, I have deactivated all of them and it keeps failing.
If I disable the PrestaShop Marketplace in your Back Office module, then if I can update the rest of the modules (only the ones that appear, not the ones that are from the marketplace), I think the error may be in the PrestaShop Marketplace in your Back Office module

**Comment by przemexm** [comment]
I do not have additional payment modules, only a transfer to the account, the original prestashop module, in debug mode there are no errors and the modules cannot be updated, all over the world people report a problem with this on various forums, so this is not one case but hundreds of the same problem, on On the server, I have version 1.7 and the mod update works there, so it's not the server's fault, the problem appeared from version 8

**Comment by Pitxiglass** [comment]
I found the solution!
Download the module from this address: https://addons.prestashop.com/es/administrative-tools/39574-prestashop-marketplace-in-your-back-office.html, install and then you can update all the modules. I hope it works as well for you as it did for me.

**Comment by joecoolio66** [comment]
I can confirm @Pitxiglass solution.  My test site was not working for upgrading modules with MBO 4.4.0... 4.4.1 seems to have fixed this issue.

**Comment by joecoolio66** [comment]
With that being said... it looks like this is a PRESTASHOP module issue with mbo 4.4.0... not a configuration issue!

**Comment by ash-f** [comment]
I'm having similar problem in 8.1.2.
But  the error message is different.
"Could not perform action update for module undefined"

**Comment by Ramss3s** [comment]
i can confirm @Pitxiglass ! PrestaShop Marketplace in your Back Office module!

**Comment by ash-f** [comment]
Installing MBO partially solved the problem.  but still a few modules can not be updated.
I tried to uninstalled/deleted them. didn't work.

**Comment by albertosilvestro** [comment]
I sorted out the problem with a turneround , deactivate the module before to update. If the module to be updated is active it's giving the reported error. Often the problem was generated by a single module that was generating the error on all the modules to be updated, doing the turneround on the single blocking module, all the others started to update regularly.

**Comment by Djolhan1** [comment]
I encountered the same error today, in French: "L'action Upgrade est impossible pour le module prestablog. Cannot download the module from Addons: Invalid credentials."

While searching on Google for similar cases, I ended up here, and I think it’s useful to both confirm the solution and bump the thread so that PrestaShop looks into it.

The fix is indeed simple: just deactivate the PrestaShop Marketplace module, and you'll be able to update your modules.

So yes, there is clearly a bug with this module that affects other modules as well.
This issue appeared overnight, with a module that was installed manually (not via Addons) for development purposes.

**Comment by tlombert** [comment]
I gets a similar error then try to install a new module. New setup, first purchased module from Marketplace to install. As the module is not installed, I can't deactivate Marketplace.. Any suggestions?

PrestaShop 9.0.2 PHP 8.4.15.

<img width="871" height="677" alt="Image" src="https://github.com/user-attachments/assets/79fb7827-da5f-4ba9-a12e-443cbcfb929b" />

<img width="1499" height="906" alt="Image" src="https://github.com/user-attachments/assets/2ef2b631-a768-4b92-9df6-a9f2a1dc28d3" />

EDIT: Found how I can download module outside the Marketplace. After deactivate marketplace, module was installed and is running. So my problem was the Marketplace..
