### ISSUE TITLE
backend admin menu doesn't traslate

### ISSUE THREAD

**Issue by augustomurri** [PrestaShop/PrestaShop#32120]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Backend menu doesn't traslate on a clean 1.7.8.8 installation

I changed the language settings in my user profile to Italian but strangely the menu is not translated :/ The central content is yes but the menu items are not

I have tried in a thousand ways also adding the English language and uninstalling it but nothing, I don't know how to fix it without having to reinstall it

![image](https://user-images.githubusercontent.com/16515870/231219394-d620787f-a78f-4837-883b-8da23cc0a446.png)

### Steps to reproduce

Go to backend admin

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @augustomurri 

Just try to update the Italien language (two to three times) BO>International>Translations using this block (see the attached screenshot below):

![image](https://user-images.githubusercontent.com/23308427/231507801-8bb5eea5-ba62-42c2-a3d4-b0b7d7f623d0.png)

Closing the issue as it's not Core bug, it's just a problem of loading the language.

Thanks!

**Comment by HartLarsson** [comment]
this problem is solved if you install DEMO records.
Without installing DEMO records the BO menu will be always in english forcing you to update italian language manually as explained by @hibatallahAouadni .
This is a problem of installation process.

**Comment by Tofandel** [comment]
I have the same issue, this shouldn't be closed, it is a core bug **at installation**


I have tried importing the french language. I have done everything from a clean prestashop installed in French, it's impossible to get the menu translated automatically, you have to install another language, change it to default, delete the original default language and reinstall it, you lose all your translations in the process


To reproduce, simply install prestashop following the install guide, at the language selection step, select any other language than english

When the installation is done, notice that the menu is in English
