### ISSUE TITLE
Translations not optimized and very slow on localhost (windows)

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/PrestaShop#32128]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I open Translations to search specific strings and translate them, but the page loads all translations at the start and on every search string change. This is completely useless and makes whole process much slower than it should be. On shops setup on windows wampserver it's awfully slow. It's been like that from the start of this new translations system of PS1.7 and it's still the same on PS8. Video says it all:

https://user-images.githubusercontent.com/5007456/231437379-ed28336f-2bb1-477c-896f-e39805bf96e0.mp4

### Expected behavior

It should **NEVER** load all translations, because noone ever needs it. There should be separate button for that.
I know it's still quite fast on production linux servers, but it doesn't change the fact that it's designed badly and lacks optimization.

### Steps to reproduce

Video says it all. To test it locally:

1. Install [wampserver](https://www.wampserver.com/en/) on windows
2. Setup local domain and install shop
3. Add custom theme and open translations for this theme.

### PrestaShop version(s) where the bug happened

1.7, 8.0

### PHP version(s) where the bug happened

7.4, 8.0

**Comment by SharakPL** [comment]
I see alerts are also messed up.

1. Search started during loading of all translations and it immediately says it couldn't find "at least", but later it does.

![obraz](https://user-images.githubusercontent.com/5007456/231444626-23fe7c79-ac91-4567-9eed-18662f6af43e.png)

2. Here it says it found 4 phrases about "credit slip", but the list of phrases below has nothing to do with it. Correct list of phrases loads on last second of the video.

![obraz](https://user-images.githubusercontent.com/5007456/231445369-66ac2388-6d72-4cf6-877a-778ca7ef4a23.png)

**Comment by AureRita** [comment]
Hi @SharakPL  ,

It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Comment by SharakPL** [comment]
@AureRita it's not. The issue is about fetching all translations many times on the same page, which is completely unnecessary and hurts performance. Slow wampserver configuration just helps point out where is the problem.

**Comment by AaronTajriba** [comment]
@AureRita We're using an good live server and an upgrade the entire translations page takes longer than 2 min to load! We're using 10 different languages and have thousands translations PER language! This is an big issue. it takes 2 min to load initially and then when you navigate it also takes 2 more minutes (if it loads at all).

@SharakPL Did you found any fix for this issue by any chance?

**Comment by SharakPL** [comment]
Unfortunately no fix yet.

**Comment by adviva** [comment]
We are facing kinda the same problem affecting our translation back office page. We have a **HUGE** “Waiting for server response” time (even 27 seconds load!) which we can’t explain. We have done many Prestashop sites and this is the first time facing such a problem. (v8.1.4). We have many sites inside the same server performing very well on that page.

For example, in here “_/api/translations/it-IT/AdminNavigationNotification_”, does have 1000 expressions on it. which 404 are missing. I don’t think we are even talking about big numbers here then.

![scsccscs](https://github.com/PrestaShop/PrestaShop/assets/26090185/22ae048d-add3-4c03-ad03-ca5080cc76b6)
![Screenshot 2024-03-04 at 18 19 17](https://github.com/PrestaShop/PrestaShop/assets/26090185/7576255c-2120-4708-b951-b8ef3b1a88dc)

I think it is anyway related to https://github.com/PrestaShop/PrestaShop/issues/34604
