### ISSUE TITLE
Verification needed for the RSS blog feed for 1.7.x and 1.6.x versions

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#32133]
## Background

In PrestaShop 1.7 and 1.6, the back-office dashboard featured a column where the prestashop.com blog RSS feed was used to display content from the prestashop.com blog.

The team in charge of prestashop.com is rebuilding the RSS blog feed. In theory, the old feed and the new feed structures are identical, so swapping the two should not create any problems. But we better verify that theory 😄 .

### Risk

It is important to test the new RSS feed on 1.6.x shops and 1.7.x shops because, if the new feed is badly handled by the software, it could break the back-office dashboard.

The worst case scenario would be that, when the new RSS feed replaces the old feed, we simply break every 1.6.x and 1.7.x back-office dashboard webpages in all over the world 😱 . We don't want that.

## To Do

In order to avoid the scenario above we need to verify how the software reacts to the new feed.

Test RSS feeds for English and French have been provided. Please contact me to get it.

However to use them, one needs to be using PrestaShop SA VPN.

### For Prestashop 1.6

Setup a 1.6 shop using the latest 1.6.1.x patch release available.
Modify the class AdminDashboardController to use the new feed instead of the old feed
https://github.com/PrestaShop/PrestaShop-1.6/blob/14511463911e96906335135e46a249b5cf39f525/controllers/admin/AdminDashboardController.php#L385
Verify whether the dashboard works properly

### For Prestashop 1.7

Setup a 1.7 shop using the latest 1.7.8.x patch release available.
Modify the class NewsDataProvider to use the new feed instead of the old feed
https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/src/Adapter/News/NewsDataProvider.php#L119
Verify whether the dashboard works properly

Expected outputs are:
A. When using the test feed, the behavior of the dashboard is OK. No noticeable issues.
B. When using the test feed, some issues appear (bad display, PHP warnings...).
C. When using the test feed, it triggers important behavior problems.

**Comment by matks** [comment]
By the way:
- PrestaShop 1.6.x is EOL
- PrestaShop 1.7.x is in extended support only

But that does not mean we should act recklessly and risk breaking the back-office dashboard of thousand of prestashop users 😅

**Comment by 0x346e3730** [comment]
PS 1.6 FR OK
![image](https://user-images.githubusercontent.com/28731165/233018010-ac0cd027-01a5-4041-8fe2-ddd1d3b85748.png)

PS 1.6 EN OK
![image](https://user-images.githubusercontent.com/28731165/233018405-3995a8bf-52de-4d36-8396-6fc068f1da13.png)

**Comment by 0x346e3730** [comment]
PS 1.7 FR OK
![image](https://user-images.githubusercontent.com/28731165/233031108-da4b5f4a-a010-452d-95ed-dbd9bdfa33b8.png)

PS 1.7 EN OK
![image](https://user-images.githubusercontent.com/28731165/233031256-37938ed1-92f8-4de6-94f3-64a452a43e16.png)
