### ISSUE TITLE
GDPR v2.0.0 launch error during update process from Ver. 8.0.2

### ISSUE THREAD

**Issue by amazingballzs** [PrestaShop/PrestaShop#32138]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If the tables in the database have a different prefix than the default one ps_, updating psgdpr module causes an error as the table yourprefix_psgdpr_log is not being picked up by the module which will complain telling that the table with ps_ prefix ps_psgdpr_log does not exist.

just to test renaming the yourprefix_psgdpr_log to ps_psgdpr_log satisfy the module psgdpr 2.0.0 needs but of course creates other troubles.

In fact in particular in this situation in which one has tables prefix different than ps_ and has updated psgdpr (and did rename the table or did not rename the table) then trying to update prestashop form version 8.0.2 to version 8.0.3 the autoupgrade process fails when in the final step the database has to be upgraded.

Again in the situation in which one has a different prefix than ps_ , if one does not update the psgdpr module and do autoupgrade prestashop form version 8.02 to 8.03 the autoupgrade process ends with success, BUT the psgdpr module too is updated and this causes to have the yourprefix_psgdpr_log abandoned in favor of the newly created ps_psgdpr_log table, which is empty, so the old data is stored in the old yourprefix_psgdpr_log and the new data allegedly will be written in the new ps_psgdpr_log.

I guess also in future in that situation one will have more problems with updates and upgrades

One last notice, prior to do any update or autoupgrade I tried to change the prefix of the tables, I used phpmysdmin to change all tables prefix to the standard ps_ , then changed a line to reflect this into /app/config/parameters.php file.

This workaround too do not circumvent this issue of the psgdpr module as in order to change the tables prefix something else too must be done obviously,  in fact int eh back office after changing the prefix trying to access any panel results into a 500 internal server error, if one does enable debug everything works fine, so it is also very hard to understand what else is missing and what is going wrong, but I could not find an information about how exactly one can change the tables prefix in PS 8X if needed for any reason.

### Expected behavior

the expected behavior simply is that the module should take into account the tables prefix one used for each prestashop installation

### Steps to reproduce

1) having a prestashop installation with tables having prefix different than ps_ go to modules and update psgdpr to version 2.0.0
2) if you just go on you notice nothing special as the module do not report errors thus try to configure the module
3) see how the module throws errors and complains that the ps_psgdpr_log do not exist
4) try to autoupgrade, it will fail
5) if you restore everything and without first updating the psgdpr module you try to autoupgrade prestashop from 8.0.2 to 8.0.3 everything seems going fine, but then you end up having an abandoned yourprefix_psgdpr_log and an empty ps_psgdpr_log and inconsistencies in your database
6) If prior to do updates or upgrades you do try to change your custom prefix to the default ps_ prefix due to lack of  information/documentation specific for PS8 you fail and end up into a blind alley, in fact seems that is not enough to just rename all tables and edit the /app/config/parameters.php file

### PrestaShop version(s) where the bug happened

8.0.2

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

psgdpr

**Comment by AureRita** [comment]
Hi @amazingballzs,

Thank you for your report, I reproduce the issue with psgpr 2.0.0 and not with the version 1.4.3, as you can see : 

[Untitled_ Apr 13, 2023 3_40 PM.webm](https://user-images.githubusercontent.com/100699445/231777520-d2fd631d-cd15-4c82-94cd-28941984c82d.webm)

Nice catch ! It's a regression ! I'll add it to the patch backlog.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by tswfi** [comment]
Looks like there already exists a PR to fix this: https://github.com/PrestaShop/psgdpr/pull/208 (or at least part of it)

**Comment by eveneme** [comment]
When and how can I update to 8.0.3 without problems?

**Comment by Yan-Studio-WEB** [comment]
You can update follow these steps
Disable GDPR
Update Prestashop
Enable GDPR and Reset

**Comment by Yan-Studio-WEB** [comment]
> When and how can I update to 8.0.3 without problems?

You can update follow these steps
Disable GDPR
Update Prestashop
Enable GDPR and Reset
