### ISSUE TITLE
The controller AdminPsMboModule is missing or invalid Prestashop 8.0.3

### ISSUE THREAD

**Issue by bsylwek** [PrestaShop/PrestaShop#32132]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello
Unfortunately, after updating to the latest version of Prestashop 8.03, I have an error that I showed in the screenshot in the marketplace modules. How to solve it?

![mbo](https://user-images.githubusercontent.com/66308504/231465417-2b5cf753-79ea-4a00-9092-59b47d82b483.jpg)

### Steps to reproduce

Go to Admin panel --> Module - > this error

### PrestaShop version(s) where the bug happened

8.03

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

mbo

### Your company or customer's name goes here (if applicable).

Sylwester

**Comment by KiLiMaToS** [comment]
I have your same problem, after upgrade to 8.0.3 some modules are not available. Are there any solutions?
Also in the theme catalog (AdminPsMboTheme) same problem.
Unlike you I have PHP 8.1 active.
Were you able to solve it?

**Comment by KiLiMaToS** [comment]
I solved it like this...
Going to Module Management and activating the marketplace.
![Immagine 2023-04-12 221424](https://user-images.githubusercontent.com/64029935/231574716-0d4836d5-728a-4ae2-9d93-2020418dab61.png)

Now unfortunately I find two entries for Marketplace and two entries for Theme Catalogue, but at least it works.
![Immagine 2023-04-12 221548](https://user-images.githubusercontent.com/64029935/231574857-615b4dd8-00db-496b-8866-6d50d759399f.png)
![Immagine 2023-04-12 221523](https://user-images.githubusercontent.com/64029935/231574876-d43eae7a-7a8c-42e3-9129-8e6265c90f41.png)

**Comment by KiLiMaToS** [comment]
Ok, going back to module management and looking for Marketplace again and clicking on "Reset" the double entry also goes away.
My client is in Italian, but the item to select is Reset

![image](https://user-images.githubusercontent.com/64029935/231576822-1592fcb9-3813-40a7-a5ba-184e470d77fb.png)

**Comment by bsylwek** [comment]
Thank you. Works !

**Comment by vaerlor** [comment]
Wroked for me too. Thanks!
