### ISSUE TITLE
Email delivery problems presta 1.8.0.2

### ISSUE THREAD

**Issue by onemove25** [PrestaShop/PrestaShop#32139]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello everyone, i m new on prestashop 1.8.0.2 and already used the version 1.6 before.  After configure the Email setting properly, Email test send successfully, my probleme is that the costumer received the email notifications but note us owner. I try to send a test Email from the Email template and evrething seems to work but when New account has been created I don't receive anything, from new order the same, contact form the same.  Did someone had this issue before? P.S the website is hosted not localhost on pc. Thanks in advance 

### Steps to reproduce

1. Giftsinbrussels.be to checking if you receive any mail after registration.

### PrestaShop version(s) where the bug happened

8.0

**Comment by hibatallahAouadni** [comment]
Hello @onemove25 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
