### ISSUE TITLE
psgdpr LoggerRepository table name

### ISSUE THREAD

**Issue by igorxut** [PrestaShop/PrestaShop#32148]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello. I think there is an error here: https://github.com/PrestaShop/psgdpr/blob/dev/src/Repository/LoggerRepository.php#L55.

```php
$query = $queryBuilder->select('*')->from('ps_psgdpr_log', 'l');
```

The name of table is hardcoded! I have another db prefix, that's why I get an error when click on "Configure" module.

### Expected behavior

The name of the table must use db prefix of the shop.

### Steps to reproduce

1. Open file "\modules\psgdpr\src\Repository\"
2. Look at line: ``` $query = $queryBuilder->select('*')->from('ps_psgdpr_log', 'l');```

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

7.2.34

### If your bug is related to a module, specify its name and its version

psgdpr 2.0.0

**Comment by igorxut** [comment]
Oh, I think the problem was described here: https://github.com/PrestaShop/PrestaShop/issues/32138

**Comment by AureRita** [comment]
Hi @igorxut 

Thank you for your report, yes, indeed this problem is described on https://github.com/PrestaShop/PrestaShop/issues/32138

So I have to close your issue because it's a dupplicate 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by AureRita** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/32138
