### ISSUE TITLE
Wire Payment PHP 8.0 version 8.0.3

### ISSUE THREAD

**Issue by hennaboy** [PrestaShop/PrestaShop#32141]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Upon checking out using wire payment an error occurs when using PHP 8.0

Error: parameter "idShop" is corrupted

module/ps_wirepayment/validation 

Does not occur when you switch back to PHP 7.4 

### Expected behavior

Check out to complete and order confirmation and email sent to admin & customer

### Steps to reproduce

Try to checkout using wirepayment on 8.0.3 using PHP 8.0 to reproduce. 

### PrestaShop version(s) where the bug happened

8.0.3

### PHP version(s) where the bug happened

8.0

### If your bug is related to a module, specify its name and its version

ps_wirepayment

**Comment by AureRita** [comment]
Hi @hennaboy 

Thank you for your report, I tried to reproduce your issue as you can see on this video : 

[Untitled_ Apr 13, 2023 3_40 PM.webm](https://user-images.githubusercontent.com/100699445/231783029-5ec3b8a7-549e-4f30-887a-451bb7ab05ed.webm)

but I can't reproduce your issue, did I miss something ? 

Waiting for your feedback

**Comment by hennaboy** [comment]
Er yeah missed the point completely you sure you responded to the correct
report here with this video as this is about reinstall after a failed
upgrade and mine is nothing about that in the slightest.

**Comment by AureRita** [comment]
Hi @hennaboy 

Sorry for that mistakes, there is the correct video to show that I can't reproduce your issue : 

[Untitled_ Apr 19, 2023 3_16 PM.webm](https://user-images.githubusercontent.com/100699445/233086616-cdae4b4f-3836-4a20-82e0-df0defd71b68.webm)

Did I miss something again ? 

Waiting for your feedback

**Comment by hibatallahAouadni** [comment]
Hello @hennaboy 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
