### ISSUE TITLE
Prestashop sitemap error 500

### ISSUE THREAD

**Issue by hivano90** [PrestaShop/PrestaShop#32146]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi all,

I've installed Prestashop sitemap free module on PS 8.0.1 and while generating sitemap, i receive error 500 with this error code:

PHP Fatal error:  Uncaught PrestaShopException: Dispatcher::createUrl() miss required parameter "rewrite" for route "module-smartblog-category" in /home/buste/public_html/classes/Dispatcher.php:913 Stack trace: #0 /home/buste/public_html/classes/Link.php(1150): DispatcherCore->createUrl('module-smartblo...', '2', Array, false, '', 1) #1 /home/buste/public_html/modules/gsitemap/gsitemap.php(365): LinkCore->getPageLink('module-smartblo...', NULL, '2') #2 /home/buste/public_html/modules/gsitemap/gsitemap.php(658): Gsitemap->getMetaLink(Array, Array, 0, 17, 0) #3 /home/buste/public_html/modules/gsitemap/gsitemap-cron.php(63): Gsitemap->createSitemap(1) #4 {main}   thrown in /home/buste/public_html/classes/Dispatcher.php on line 913

I am attaching console error too.

Can you help me fixing that? Thanks
<img width="1696" alt="Screenshot 2023-04-12 alle 17 39 29" src="https://user-images.githubusercontent.com/130652349/231716257-4c8717a4-7090-4a60-a2fc-c474b80a8e54.png">

### Steps to reproduce

1. Go to Google sitemap free module in PS 8.0.1
2. Select checkboxes to choose which pages must be included in sitemap
3. Click on generate sitemap or on cron job link
4. Here, in both cases, i receive error 500

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8

### If your bug is related to a module, specify its name and its version

google sitemap 4.3.0

**Comment by hivano90** [comment]
Sorry i've found and solved the error.
Just disable the blog modules on your prestashop and all will work good.

Thanks

**Comment by hibatallahAouadni** [comment]
Thanks for your feedback!
