### ISSUE TITLE
Faced serach problem

### ISSUE THREAD

**Issue by KamilFierka** [PrestaShop/PrestaShop#32158]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

https://drive.google.com/file/d/1dOf042J9x0szGdCnlb4WZNbxENyFWGE7/view?usp=drivesdk

Hello i have a problem with faced search module. I choose some subcategories and nothing happend.

### Steps to reproduce

Go to category and try to choose subcategory from list on mobile.

### PrestaShop version(s) where the bug happened

1.8

### PHP version(s) where the bug happened

8.0

### If your bug is related to a module, specify its name and its version

ps_facetedsearchmodule last version

### Your company or customer's name goes here (if applicable).

Deldom.pl

**Comment by florine2623** [comment]
Hello @KamilFierka ,

I can't reproduce your issue.

https://user-images.githubusercontent.com/16019289/235146463-1fa903b7-0f79-4f80-a9a1-361d44c03a3e.mov


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
