### ISSUE TITLE
GDPR Module create error during update process from Ver. 8.0.2

### ISSUE THREAD

**Issue by Yan-Studio-WEB** [PrestaShop/PrestaShop#32166]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,
I attempt to update from Ver. 8.0.2 to 8.0.3. 
In 3 PS installations that is completely empty from products and only theme installed (Leo Themes)

While 1 click update module arrived to the point to update modules the process stopped and give me this error (see image bellow)

![GDPR Error](https://user-images.githubusercontent.com/32092642/232009199-4a313b72-4f99-420e-824d-d500b44a635c.jpg)

![Update Error](https://user-images.githubusercontent.com/32092642/232009208-b23a5add-2e5e-4070-870e-a041c676a9ee.jpg)
 
I found out a solution
1. I first restore the Prestashop to previous version 8.0.2
2. I disabled the GDPR Module
3. I reinstall the update with no Errors
4. I enable and reset the Module because with no reset was not working (see image above}

Thank you

### Expected behavior

The Update process to end with no Issues

### Steps to reproduce

Just try to update with gdpr enabled

### PrestaShop version(s) where the bug happened

8.0.2

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

GDPR

### Your company or customer's name goes here (if applicable).

Yan Studio

**Comment by hibatallahAouadni** [comment]
Hello @Yan-Studio-WEB 

Thanks for reporting the issue 🙏 
Could you please provide the GDPR version and did you try to switch to the CLASSIC theme?
Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Yan-Studio-WEB 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #32138. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #32138
