### ISSUE TITLE
Bug Remboursement Partielle

### ISSUE THREAD

**Issue by Rktthierry** [PrestaShop/PrestaShop#32165]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Bonjour tous,
j'ai un problème sur la mise en remboursement sur mon site prestashop !
ça me renvoie une erreur 
=> Une erreur inattendue s'est produite. [PrestaShop\PrestaShop\Core\Domain\Shop\Exception\ShopException code 0]

### Steps to reproduce

<img width="1421" alt="Capture d’écran 2023-04-13 à 15 07 56 (1)" src="https://user-images.githubusercontent.com/108149643/232007100-bd3c4eef-cf17-4abb-be37-f8cd639d0cfb.png">

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.2

### Your company or customer's name goes here (if applicable).

Thierry

**Comment by hibatallahAouadni** [comment]
Hello @Rktthierry 

Please send your request in English. English is the norm on GitHub.
Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thank you

**Comment by Anthotill** [comment]
I confirm this issue, PS version 1.7.8.7, when you try to refund customers, you've got this erreor : "Une erreur inattendue s'est produite. [PrestaShop\PrestaShop\Core\Domain\Shop\Exception\ShopException code 0]". It's not always but very often

**Comment by aurelienljd** [comment]
Hello,

I confirm this issue too on 1.7.8.7.
I've got it on both multishop and monoshop installation.
As Anthotill said, it's not on every orders
