### ISSUE TITLE
Internal server error when using web service and setting Io-Format as JSON

### ISSUE THREAD

**Issue by 4strodev** [PrestaShop/PrestaShop#32179]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I'm using PrestaShop 8.0.3 in windows with XAMPP. I need to user the API REST and I try to use JSON as input output format.

I have an internal server error when I try to set the IO format. I see the logs and I found this

```
[Mon Apr 17 09:52:22.400518 2023] [php:error] [pid 3788:tid 1736] [client ::1:51203] PHP Fatal error:  Uncaught TypeError: array_filter(): Argument #1 ($array) must be of type array, string given in C:\\xampp\\htdocs\\prestashop\\classes\\webservice\\WebserviceOutputJSON.php:168\nStack trace:\n#0 C:\\xampp\\htdocs\\prestashop\\classes\\webservice\\WebserviceOutputJSON.php(168): array_filter('addresses')\n#1 [internal function]: WebserviceOutputJSONCore->{closure}('addresses', 0)\n#2 C:\\xampp\\htdocs\\prestashop\\classes\\webservice\\WebserviceOutputJSON.php(169): array_walk(Array, Object(Closure))\n#3 C:\\xampp\\htdocs\\prestashop\\classes\\webservice\\WebserviceOutputBuilder.php(350): WebserviceOutputJSONCore->overrideContent('The Customer, B...')\n#4 C:\\xampp\\htdocs\\prestashop\\classes\\webservice\\WebserviceRequest.php(1840): WebserviceOutputBuilderCore->getResourcesList(Array)\n#5 C:\\xampp\\htdocs\\prestashop\\classes\\webservice\\WebserviceRequest.php(631): WebserviceRequestCore->returnOutput()\n#6 C:\\xampp\\htdocs\\prestashop\\webservice\\dispatcher.php(90): WebserviceRequestCore->fetch('8XS8SD4HIRZ68EF...', 'GET', '', Array, false, NULL)\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\prestashop\\classes\\webservice\\WebserviceOutputJSON.php on line 168
```

After searching in source code, I think that the error is in `classes/webservice/WebserviceOutputBuilder.php` in function `getResourceList()` line `350`. As I understand, the output is a string and the method override Content expects an array. This is why the API cannot return a response in JSON format

**[NOTE]**

After enabling debug mode the api returns this
```
Fatal error: Uncaught TypeError: array_filter(): Argument #1 ($array) must be of type array, string given in
C:\xampp\htdocs\prestashop\classes\webservice\WebserviceOutputJSON.php:168
Stack trace:
#0 C:\xampp\htdocs\prestashop\classes\webservice\WebserviceOutputJSON.php(168): array_filter('addresses')
#1 [internal function]: WebserviceOutputJSONCore->{closure}('addresses', 0)
#2 C:\xampp\htdocs\prestashop\classes\webservice\WebserviceOutputJSON.php(169): array_walk(Array, Object(Closure))
#3 C:\xampp\htdocs\prestashop\classes\webservice\WebserviceOutputBuilder.php(350):
WebserviceOutputJSONCore->overrideContent('The Customer, B...')
#4 C:\xampp\htdocs\prestashop\classes\webservice\WebserviceRequest.php(1840):
WebserviceOutputBuilderCore->getResourcesList(Array)
#5 C:\xampp\htdocs\prestashop\classes\webservice\WebserviceRequest.php(631): WebserviceRequestCore->returnOutput()
#6 C:\xampp\htdocs\prestashop\webservice\dispatcher.php(90): WebserviceRequestCore->fetch('8XS8SD4HIRZ68EF...', 'GET',
'', Array, false, NULL)
#7 {main}
thrown in C:\xampp\htdocs\prestashop\classes\webservice\WebserviceOutputJSON.php on line 168
```

### Expected behavior

After making a request to the root API route, the API should return a response in JSON format.

### Steps to reproduce

1. Generate a private key with full access
2. Make a request to root API route setting IO format to JSON using query parameters or headers.

### PrestaShop version(s) where the bug happened

8.0.3

### PHP version(s) where the bug happened

8.1.6

**Comment by 4strodev** [comment]
This error only happens in root route!!! If you use it in resources like customer, it works!!!

**Comment by lymianin** [comment]
Maybe check the variable to see if it is an array?
classes\webservice\WebserviceOutputJSON.php#168
```
   public function overrideContent($content)
    {
        array_walk($this->content, function (&$item) {
            //$item = array_filter($item); //removed
	    $item = is_array($item)?array_filter($item):$item; //inserted
        });
        $content = json_encode($this->content, JSON_UNESCAPED_UNICODE);

        return (false !== $content) ? $content : '';
    }
```

**Comment by rayanzaatari** [comment]
@4strodev  Where you able to resolve this at the root level ? I have it working for all resources but I also need it on the root level

**Comment by 4strodev** [comment]
Sorry but this happens to my team for a project that needs an ecommerce platform and since we couldn't use PrestaShop we created from scratch our own platform. So we leave this issue aside.

Even this error could happen to us because we are not using the API correctly. I recommend improving the API documentation and if it's possible make the use of JSON easier.

I mean, the API was designed to be used with a PHP library that cannot be installed with composer because something was deprecated or outdated. And the usage with pure HTTP requests needs XML and this XML needs to be parsed using a non-standard way. The majority of XML libraries for node cannot parse and create XML with the format that the API expects.

So we found that to use it with JSON is so complicated and not well documented. To use XML we need a library that even using the official docs we can't install. I know that the API is not the main product of PrestaShop, and it is a massive project, even I noticed that a migration to DDD and CQRS is happening to the source code of PrestaShop, but for developers a good doc and updated libraries could make the difference.

**Comment by rayanzaatari** [comment]
Thank you for the update & I couldn't agree more, documentation is misleading & needs improvement.

**Comment by 4strodev** [comment]
Good luck, my friend 🫡

**Comment by 4strodev** [comment]
The API needs improvements on docs, check why the library is outdated and review the support for JSON.
I'm not reopening this Issue for a project that I'm making, but it's necessary to review this.

**Comment by JanMikes** [comment]
Hi, why is this issue closed? It still persists in the newest prestashop 8.1.7:
```
[28/Jun/2024:00:24:35 +0000] "GET /api/?io_format=JSON HTTP/1.1" 500 185 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15"

[Fri Jun 28 00:24:40.132898 2024] [php:error] [pid 36] [client 172.25.0.7:58268] PHP Fatal error:  Uncaught TypeError: array_filter(): Argument #1 ($array) must be of type array, string given in /var/www/html/classes/webservice/WebserviceOutputJSON.php:168
Stack trace:
#0 /var/www/html/classes/webservice/WebserviceOutputJSON.php(168): array_filter('addresses')
#1 [internal function]: WebserviceOutputJSONCore->{closure}('addresses', 0)
#2 /var/www/html/classes/webservice/WebserviceOutputJSON.php(169): array_walk(Array, Object(Closure))
#3 /var/www/html/classes/webservice/WebserviceOutputBuilder.php(350): WebserviceOutputJSONCore->overrideContent('The Customer, B...')
#4 /var/www/html/classes/webservice/WebserviceRequest.php(1842): WebserviceOutputBuilderCore->getResourcesList(Array)
#5 /var/www/html/classes/webservice/WebserviceRequest.php(634): WebserviceRequestCore->returnOutput()
#6 /var/www/html/webservice/dispatcher.php(94): WebserviceRequestCore->fetch('CKY3VGM514932U1...', 'GET', '', Array, false, NULL)
#7 {main}
  thrown in /var/www/html/classes/webservice/WebserviceOutputJSON.php on line 168
```

Fresh install, demo mode, just activated the webservice, no changes in the code.

The proposed fix (https://github.com/PrestaShop/PrestaShop/issues/32179#issuecomment-1625084657) works well.
