### ISSUE TITLE
Google Analytics 4.2.2 - can't translate and export module translations

### ISSUE THREAD

**Issue by Caleydon** [PrestaShop/PrestaShop#32175]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Can't translate Google Analytics module version 4.2.2. and export translations of this module doesn't work.

The module author ignored the new rules for translations. He used "Modules.GAnalytics.Admin" domain instead correct "Modules.Googleanalytics.Admin" in php and tpl files.

### Steps to reproduce

Please watch the video.
https://vimeo.com/817906782/109a81f1fa

Description for the video:
1. trying load new translation system from module BO - still is loading old translation system
2. trying load new translation system from Translation page - still is loading old translation system
3. trying cheat the system - load new translation system using other module and then add "ps_googleanalytics" variable in the URL. The new translation system stuck in loading the page.
4. trying to export module translations - get the error

![bug_ps_googleanalytics_422_01](https://user-images.githubusercontent.com/2806752/232224149-02474446-c419-4425-8a31-c5a0b27dc9f5.png)

![bug_ps_googleanalytics_422_02](https://user-images.githubusercontent.com/2806752/232224159-84810ec1-11c3-4c14-b620-2f1e77291ef8.png)

![bug_ps_googleanalytics_422_03](https://user-images.githubusercontent.com/2806752/232224161-e593dbe4-01bc-4934-ae6c-763a94cb22be.png)

### PrestaShop version(s) where the bug happened

1.7.8.8 - 8.0.3

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

ps_googleanalytics v4.2.2

**Comment by AureRita** [comment]
Hi @Caleydon ,

Thank you for your report, I reproduce the issue with PrestaShop version 1.7.8.8, as you can see : 

[Untitled_ Apr 20, 2023 11_54 AM.webm](https://user-images.githubusercontent.com/100699445/233331180-f4e0819c-595c-4902-94a9-65dfd5b20eae.webm)

 I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks

**Comment by MatShir** [comment]
Fixed by https://github.com/PrestaShop/ps_googleanalytics/pull/148
