### ISSUE TITLE
LinkList : Error triggered `Attempted to call an undefined method named "setHookDispatcher" of class "PrestaShop\Module\LinkList\Core\Grid\Definition\Factory\LinkBlockDefinitionFactory"`

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#32178]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you will go to LinkList page, you will have an error : 

![image](https://user-images.githubusercontent.com/1533248/232424081-3f7f25e1-2ed6-49d8-b7ad-a2230c182cd9.png)

### Expected behavior

No error, ofc.

### Steps to reproduce

1. Install `develop` branch
2. Go to the BackOffice
3. Go to Design > Link List
4. You have the error

### PrestaShop version(s) where the bug happened

9.0.x

### PHP version(s) where the bug happened

7.3

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

**Comment by hibatallahAouadni** [comment]
Hello @Progi1984 

Nice catch :clap: it's a regression only on develop branch as I didn't reproduce it with 8.1.x branch.
I will add it to the backlog to be fixed.

Thanks!
