### ISSUE TITLE
Cart Rule: Minimum Amount does not save "tax included" and "shipping included" settings 

### ISSUE THREAD

**Issue by EdEichman-LentillasSi** [PrestaShop/PrestaShop#32182]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

It's impossible to create a cart rule with minimum amount "Tax INCLUDED" and "Shipping INCLUDED". You can create and save it, but when you open the rule, both values are reset to "Tax EXCLUDED" and "Shipping "EXCLUDED"

### Expected behavior

The settings "Tax Included" and "Shipping Included" should be saved correctly

### Steps to reproduce

- Create a cart rule
- Give it a name
- Set minimum amount to e.g. 35 EUR
- Set "Tax included" and "Shipping Included"
- Add e.g. free shipping
- Save and close the cart rule
- Open the cart rule again, and you will see that it's now "Tax EXCLUDED" and "Shipping EXCLUDED". Changing the values and saving does not help... everything still excluded.

### PrestaShop version(s) where the bug happened

8.0.3

### PHP version(s) where the bug happened

8.1.8

### Your company or customer's name goes here (if applicable).

Lentillas Si

**Comment by hibatallahAouadni** [comment]
Hello @EdEichman 

Thanks for the detailed bug report :clap: 
I didn't manage to reproduce the issue with the provided infos, please check the attached screen record below:

[issue_32182.webm](https://user-images.githubusercontent.com/23308427/232510505-6862db5e-1696-4b59-939a-d5cc17aa93e7.webm)

Are you using some third-party module that override the cart rule? Please check and feedback.

Thanks!

**Comment by EdEichman-LentillasSi** [comment]
Hi Hibatallah,
Which version of PHP are you using? I'm seeing the bug on PHP 8.1.17 and 8.1.8. We did not see this bug till we upgraded to PHP8.
I installed a fresh PrestaShop 8.0.3 (using the default options) and recorded [ a loom](https://www.loom.com/share/f77ab13dc9fb4a42a49104226acfc1fa) to show the problem. 

My guess is that you were using PHP7 when you recorded your video?

Thanks,
Ed

**Comment by EdEichman-LentillasSi** [comment]
![image](https://user-images.githubusercontent.com/6961175/232733733-fbfb60cc-3c84-402d-8774-ffaa7bd53d98.png)

**Comment by AureRita** [comment]
Hi @EdEichman 

Thank you for your report, this issue seems to be like this one : https://github.com/PrestaShop/PrestaShop/issues/31958

So it's an issue on php ? 

Waiting for your feedback

**Comment by EdEichman-LentillasSi** [comment]
My bad... it's a duplicate bug report. It's an issue with PrestatShop on PHP8.1.
I will close this ticket and post our fix to https://github.com/PrestaShop/PrestaShop/issues/31958
Sorry & Thanks!
Ed

**Comment by EdEichman-LentillasSi** [comment]
My bad... it's a duplicate bug report. It's an issue with PrestatShop on PHP8.1.
I will close this ticket and post our fix to https://github.com/PrestaShop/PrestaShop/issues/31958
Sorry & Thanks!
Ed

**Comment by hibatallahAouadni** [comment]
Duplicate of #31958
