### ISSUE TITLE
Why did i get a syntax error from a day to the next who resulted on a http server 500 error

### ISSUE THREAD

**Issue by Arkoos62** [PrestaShop/PrestaShop#32188]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

From a day to the next, i got an error on my website Prestashop 1.7.5.1,

Parse error: syntax error, unexpected '$html' (T_VARIABLE), expecting function (T_FUNCTION) in /home/bijougrasl/ideecad/classes/controller/FrontController.php on line 669

Here is the line 669 : 
![image](https://user-images.githubusercontent.com/46033921/232516556-47a9361b-41c8-4ad7-bae4-684645af9204.png)

### Steps to reproduce

I did nothing to have this error, it happened from a day to the next

### PrestaShop version(s) where the bug happened

1.7.5.1

### PHP version(s) where the bug happened

7.2

**Comment by Hlavtox** [comment]
Your files are modified, that's why you get the error. See the original file here - https://github.com/PrestaShop/PrestaShop/blob/8f39d24b0dd345d9e33145e326c81faa867a0555/classes/controller/FrontController.php#L669

**Comment by Arkoos62** [comment]
Yes i saw that and i tried to replace the file by the original one but some displays could not work anymore 
I think i've installed a plugin who overrode the core files in question
Nvm i've resolved the issue but i would have liked to know which addons modified the core file 
Thanks to you for your involvement in my issue
