### ISSUE TITLE
bogue : error 500

### ISSUE THREAD

**Issue by graziellaMG** [PrestaShop/PrestaShop#32192]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

![6](https://user-images.githubusercontent.com/131011903/232544439-e3faa98b-cf64-4ab5-88e3-56034cc49a6c.PNG)
bonjour,
j'ai la version PrestaShop 8.0.2 en serveur local. il m'est impossible d'effacer la boutique par défaut ...
avec l'équipe d'aide en ligne, nous n'avons pas trouvé la solution... ils m'ont dit de vous écrire pour avoir une solution rapide à ce problème, qui m'empêche d'installer le module acheté de la nouvelle boutique. 
j'ai hâte de recevoir une réponse ;)
merci
bonne continuation
Graziella MG

### Expected behavior

une confirmation d'effacement de ce qui est lié à la boutique
si possible en français et non en anglais ;) 

### Steps to reproduce

![5](https://user-images.githubusercontent.com/131011903/232550622-a90e36e2-c3b5-46cb-a817-5a64782e90be.PNG)
1 : activé
2 : delete orders et customers
3 : error 500

### PrestaShop version(s) where the bug happened

8.0.2

### PHP version(s) where the bug happened

8

### If your bug is related to a module, specify its name and its version

module pscleaner

**Comment by Hlavtox** [comment]
@graziellaMG Hi, please follow the steps written on the top of bug request form. 👍

> Reporting bugs with "error 500" or "white page" may not help us reproduce them. This is a universal error that hides what is underneath. Instead, enable debug mode in the Performance section of PrestaShop and try again. You should get a proper error message.
> 
> Use English, reports in all other languages will be closed.

**Comment by hibatallahAouadni** [comment]
Hello @graziellaMG 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must provide clear and concise steps to reproduce to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Please send your request in English. English is the norm on GitHub.

Thank you
