### ISSUE TITLE
generate nested sitemap in "en" langage.

### ISSUE THREAD

**Issue by juanitos-emilio** [PrestaShop/PrestaShop#32196]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have no choice but to use V3.2.2 for PS 1.6.1.16, V4 does not work. V3.2.2 in multilingual, the module does not generate the English sitemap but a nested sitemap which makes it loop and therefore google does not find the urls of the /en sitemap.
the module works for the languages fr, de, es but not in.

### Expected behavior

I am interested in information to solve this problem or install an update file or modify a file into the module to stop this

### PrestaShop version(s) where the bug happened

1.6.1.16

### PHP version(s) where the bug happened

5.6.40-60+0~20220627.67+debian10~1.gbp1f7ffd

### If your bug is related to a module, specify its name and its version

Google Sitemaps v3.2.2 PrestaShop

### Your company or customer's name goes here (if applicable).

MFG Parts

**Comment by Hlavtox** [comment]
@juanitos-emilio Hey, can you please check if `1_en_0_sitemap.xml` generated in the root of prestashop or not? So we know if it's a redirect problem or what is happening.

**Comment by juanitos-emilio** [comment]
hello and thank you very much for your answer. Yes the sitemap is generated at the root, as in 3 other languages.
I have a cron task every day at 2am to launch the editing of new sitemaps and the sitemap in "en" version is well written on the server (see attachment).

**Comment by AureRita** [comment]
HI @juanitos-emilio  ,

PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).

Maintenance for this version is now being performed exclusively by volunteers (like our dear @Hlavtox) on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

So, unfortunately, I have to close this issue, but you can continue chatting below

Thank you

**Comment by juanitos-emilio** [comment]
ok, thanks a lot but in this case there is no working version of this module for V1.6.1.16? or an equivalent module on github.com?
