### ISSUE TITLE
no carriers available, Javascript refresh issue

### ISSUE THREAD

**Issue by asfortech** [PrestaShop/PrestaShop#322]
Hi All,

In a default prestashop install, with multiple carriers, when you are logged in as a customer:

If you checkout, it will show you the proper carrier, regardless of which address you choose. However, if you change the address, it automatically switches to "no carrier". NOW, if you refresh the page, with the other address, it WILL show the proper carrier for the address, but if you change addresses again, it will show you "no carrier", unless you refresh. 

Has anyone come across this issue? Would love to know. Thanks!

**Comment by marionf** [comment]
Hello, 
This issue is old, so I close it.
If you still have it on the last version (PrestaShop 1.7.4.2), please open a new one.
Regards
