### ISSUE TITLE
Cannot replace image on new product page

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#32200]
### Steps to reproduce

1. Get 8.1.x, enable new product page. Multistore off.
2. Go edit any product.
3. Select it's image, click "replace image".
4. Replace it.
5. Save it.
6. `[ErrorException kód 0]: Warning: Undefined array key "shop_id"`

### Additional data for @zuk3975 & @jolelievre 

Data sent when saving image.
```
product_image[is_cover]: 0
product_image[legend][1]: 
product_image[_token]: Wp4W2-6FPL-lU3tQL1XpH1q1JIa2tmpgv9pceTWS0FU
product_image[shop_id]: 1
```

Data sent when uploading new image.
```
product_image[product_id]: 19
product_image[_token]: Wp4W2-6FPL-lU3tQL1XpH1q1JIa2tmpgv9pceTWS0FU
product_image[file]: (binary)
```

Data sent when replacing image.
```
product_image[file]: (binary)
product_image[_token]: Wp4W2-6FPL-lU3tQL1XpH1q1JIa2tmpgv9pceTWS0FU
_method: PATCH
```

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

8.0

**Comment by zuk3975** [comment]
thanks, probably my bad introduced by https://github.com/PrestaShop/PrestaShop/pull/31099/files. I'll fix it

**Comment by hibatallahAouadni** [comment]
Nice catch Daniel 👏

**Comment by Hlavtox** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/32201
