### ISSUE TITLE
Visual issues on the new product page (desktop version)

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#32214]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

There are some visual issues on the new product page.

 1. If you have a multi-lang site, language iso-codes should be uppercase (this is a feature request ;-))
https://capture.dropbox.com/Ipr6P4gHlCDQWdTt

**Apply uppercase for all ISO codes - both dropdown selectors for multi-language text inputs AND TinyMCE Text Editors (impacts the entire BO, not only product page)**  

 2. Element below indicates whether the field is required or not, but there's no label explaining that.
https://capture.dropbox.com/cjYTfYu4WZISB6Sc

Tab Details -> Attached files -> **Add a label « Required field » before yes/no toogle** 

3. What do you want me to type there? Missing placeholder.
https://capture.dropbox.com/qlvsa0rqqBvj43OE

Tab Stocks -> Stock alert input -> **Add placeholder "Enter threshold value / Enter low stock value" + Change text input into numeric input** 

 4. Link below is misaligned. It is not in the center, it is not to the left, etc.
https://capture.dropbox.com/jMWWFibWdYOzwAGP

Tab Pricing -> Retail price -> **Align internal link on bottom right, under Retail price input**

 5. There are a few issues there. The help text doesn't look like a help text, warning/info text doesn't look like one.
https://capture.dropbox.com/Mru43SJO6TP3oxxG

Tab Pricing -> Add new specific price modale -> **Turn text « For customer meeting the… » into blue info alert**

6. Worth considering making it more readable. (feature request)
https://capture.dropbox.com/dcMEAaJ4kHKd1vuI

Tab SEO -> Redirection page -> Long Info alert -> **Change paragraph text into bullet list inside info alert**

 7. When you click this button, it gets a weird border covering part of the text.
https://capture.dropbox.com/VJZHmF53l6JJft0i

Tab SEO -> Meta title / Meta description / Friendly URL ->
Quick win: **Fix behavior of Reset button (on click: filled - after click: back to outlined)** 
Nice to have: **Dynamic behavior - Reset button is disabled when input value = reset value, Reset button is enabled when input value ≠ reset value**

 8. I don't understand this part. What is this currency for? I have PLN but still the EUR symbol on the left. (edit, ok, it doesn't change dynamically).
https://capture.dropbox.com/esELxbafmUtZ8nnh

Tab Options -> Supplier reference(s)
Quick win: **Remove the currency symbol from cost price input**
Nice to have: **Make Cost price input's currency symbol dynamic: Cost price currency symbol adapts to the Currency selected in dropdown next to it** (should be possible as this behavior already exists) 

**Other improvements :** 

- Tab Pricing -> Retail price -> **Make Tax rules input disabled when taxes are disabled** 

- Mobile -> Tab description -> Add categories - > Category selection modale -> **Center modale + align Cancel/Save buttons on bottom right** 

- Mobile -> Tab Stock -> **Fix display for Add or subtract item input** 

- Virtual Product > Tab Virtual 
If the Add downloadable file is set to no, all the input are disabled

![Capture d’écran 2023-08-06 à 23 04 16](https://github.com/PrestaShop/PrestaShop/assets/43613217/f96dda82-5039-415f-abbe-efa78f57a448)

 

### Expected behavior

Some of the elements could be fixed/improved.

### Steps to reproduce

Visit the new product page and the places you see on screenshots.

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

n/a

**Comment by AureRita** [comment]
Hi @kpodemski 

Thank you for all this report, Currently I reproduce all of them except the number four as you can see : 

![image](https://user-images.githubusercontent.com/100699445/233397660-4633bea0-1f64-45c4-bdcd-c7363142d72b.png)

Some of them need to be validated by PM (like some feature) 

Thank you

**Comment by kpodemski** [comment]
@AureRita why did you put 8.0.3 label there?

**Comment by AureRita** [comment]
Hi @kpodemski 

I put the label 8.0.3 because I also reproduce it on 8.0.3 ( except the number 6 ) and we always put the the oldest version that have the same issue and we reproduce it

**Comment by kpodemski** [comment]
@AureRita ok, and how do you want the team to know that it is something that should be fixed in 8.1? 🤔 I think it's complicated to know what's going on in 8.1 if there's no indicator that this bug is related to 8.1

**Comment by AureRita** [comment]
@kpodemski 
This will be checked by the PMs, if they decide that this issue needs to be corrected for 8.1.0, they will put the milestone accordingly

**Comment by Robin-Fischer-PS** [comment]
@kpodemski QA team does not decide which "old" bugs needs to be fixed in the next version, since this bug is not introduced in 8.1.0, it can be fixed in 8.0.5 for example (and then merged with 8.1.0), so the PMs will check and decide that.

**Comment by kpodemski** [comment]
@Robin-Fischer-PS, but it's on the experimental page, which will be enabled by default in 8.1, there will be no bugfixes for the experimental page in 8.0.x, I think this should be handled a bit differently than a regular bug report

**Comment by jolelievre** [comment]
No bug related with new product page will be fixed on 8.0.x there's a massive difference between the two versions and we couldn't fix everything without back porting the whole code from 8.1.x to 8.0.x

It's a page that was experimental in 8.0, no code has been added in it since the freeze of 8.0. So the only place where this could be fixed is in 8.1.x It's now up to @MatShir to decide the validity and priority of these feedbacks, probably to be validated by @TristanLDD as well

**Comment by TristanLDD** [comment]
Hi @kpodemski, thank you for your feedback
We reviewed your suggestions with @jolelievre and @MatShir, here are the **expected changes**: 


> 1. If you have a multi-lang site, language iso-codes should be uppercase (this is a feature request ;-))
https://capture.dropbox.com/Ipr6P4gHlCDQWdTt

**Apply uppercase for all ISO codes - both dropdown selectors for multi-language text inputs AND TinyMCE Text Editors (impacts the entire BO, not only product page)**  


> 2. Element below indicates whether the field is required or not, but there's no label explaining that.
https://capture.dropbox.com/cjYTfYu4WZISB6Sc

Tab Details -> Attached files -> **Add a label « Required field » (ping @PrestaShop/wording-managers) before yes/no toogle** 


> 3. What do you want me to type there? Missing placeholder.
https://capture.dropbox.com/qlvsa0rqqBvj43OE

Tab Stocks -> Stock alert input -> **Add placeholder "Enter threshold value / Enter low stock value" (ping @PrestaShop/wording-managers)  + Change text input into numeric input** 

> 4. Link below is misaligned. It is not in the center, it is not to the left, etc.
https://capture.dropbox.com/jMWWFibWdYOzwAGP

Tab Pricing -> Retail price -> **Align internal link on bottom right, under Retail price input**


> 5. There are a few issues there. The help text doesn't look like a help text, warning/info text doesn't look like one.
https://capture.dropbox.com/Mru43SJO6TP3oxxG

Tab Pricing -> Add new specific price modale -> **Turn text « For customer meeting the… » into blue info alert**

> 6. Worth considering making it more readable. (feature request)
https://capture.dropbox.com/dcMEAaJ4kHKd1vuI

Tab SEO -> Redirection page -> Long Info alert -> **Change paragraph text into bullet list inside info alert**

> 7. When you click this button, it gets a weird border covering part of the text.
https://capture.dropbox.com/VJZHmF53l6JJft0i

Tab SEO -> Meta title / Meta description / Friendly URL ->
Quick win: **Fix behavior of Reset button (on click: filled - after click: back to outlined)** 
Nice to have: **Dynamic behavior - Reset button is disabled when input value = reset value, Reset button is enabled when input value ≠ reset value**

> 8. I don't understand this part. What is this currency for? I have PLN but still the EUR symbol on the left. (edit, ok, it doesn't change dynamically).
https://capture.dropbox.com/esELxbafmUtZ8nnh

Tab Options -> Supplier reference(s)
Quick win: **Remove the currency symbol from cost price input**
Nice to have: **Make Cost price input's currency symbol dynamic: Cost price currency symbol adapts to the Currency selected in dropdown next to it** (should be possible as this behavior already exists) 


**Other improvements :** 

- Tab Pricing -> Retail price -> **Make Tax rules input disabled when taxes are disabled** 

- Mobile -> Tab description -> Add categories - > Category selection modale -> **Center modale + align Cancel/Save buttons on bottom right** 

- Mobile -> Tab Stock -> **Fix display for Add or subtract item input**
