### ISSUE TITLE
Smarty and Helper warning in legacy admin controllers

### ISSUE THREAD

**Issue by Codencode** [PrestaShop/PrestaShop#32219]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

With debug mode active, a series of warnings such as "Creation of dynamic property is deprecated" are shown in the legacy admin controllers (e.g.: Dashboard or Image settings)
ex:
```
Unknown error on line 182 in file \\vendor\\smarty\\smarty\\libs\\sysplugins\\smarty_internal_extension_handler.php
[8192] Creation of dynamic property Smarty_Internal_Extension_Handler::$createData is deprecated

Unknown error on line 719 in file \\vendor\\smarty\\smarty\\libs\\sysplugins\\smarty_internal_template.php
[8192] Creation of dynamic property Smarty_Internal_Template::$compiled is deprecated

Unknown error on line 2592 in file \\classes\\controller\\AdminController.php
[8192] Creation of dynamic property HelperList::$languages is deprecated

Unknown error on line 2595 in file \\classes\\controller\\AdminController.php
[8192] Creation of dynamic property HelperOptions::$no_link is deprecated
```

I attach screenshots of the "Dashboard" page and the "Image settings" page.

### Steps to reproduce

1. Activate **Debug mode** in Advanced Parameters > Performance
2. Go in Dashboard page or Design > Image settings
3. At this point the warnings are shown

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.2.0

**Comment by AureRita** [comment]
Hi @Codencode 

Thank you for your report, 

As you can see on the [Prestashop documentation](https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/), Prestashop v8 doesn't support the php 8.2, that's why you've some warning messages 

Because this is a expected behavior, I'll close this issue 

Thank you

**Comment by Codencode** [comment]
Hi @AureRita 

I'm sorry, but I hadn't noticed that PHP version 8.2 is not supported.

Thank you
