### ISSUE TITLE
Visual issues on the new product page (mobile)

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#32218]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

There are a few issues on mobile worth checking.

0. Save and publish display problem.
https://capture.dropbox.com/sNn0AT3eOBRYcCzN

1. Three dots icon is not aligned correctly.
https://capture.dropbox.com/b3owdasT9xJwIskM

2. We could use a little more spacing there.
https://capture.dropbox.com/xugYktCr23hUE0En

3. Features are displayed in a very confusing way.
https://capture.dropbox.com/99WqNlcGRvUq9eev

4. Problems with "Add new file" popup.
https://capture.dropbox.com/ZLJ0vVA1ETZz2eB3

5. Customizable product. Problems with spacing and alignment.
https://capture.dropbox.com/Wwtlef6xog066k7m

6. It is impossible to edit the stock on a mobile device.
https://capture.dropbox.com/dtjVuCfDQeHZ7mUN

7. Alignment problem.
https://capture.dropbox.com/Mw8BgK2GNY9XYWXw

8. Incorrectly displayed prices.
https://capture.dropbox.com/xu2plzoqvpek5GFZ

9. Cost price displayed incorrectly (I'm aware that it's a tricky element to display, maybe a responsive table would be better).
https://capture.dropbox.com/kHk2MsytitYtfaO4

### Steps to reproduce

Visit the new product page, and places that you see on the screenshots.

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

7.4

**Comment by AureRita** [comment]
Hi @kpodemski 

Thank you for your report, I reproduced some of them : 

We could use a little more spacing there.

![image](https://user-images.githubusercontent.com/100699445/233411289-7ff8c6b5-037c-48cf-a76a-6487af1abea1.png)

For the number four,with add new file, I've a "had new file ception" as you can see : 

[Untitled_ Apr 20, 2023 5_01 PM.webm](https://user-images.githubusercontent.com/100699445/233407071-5f482a1a-0617-4925-aeec-54d96e3933d6.webm)

and I have your issue 

![image](https://user-images.githubusercontent.com/100699445/233407437-33de1464-261a-422d-9ce4-ce67ddf0a215.png)

Customizable product. Problems with spacing and alignment.

![image](https://user-images.githubusercontent.com/100699445/233408710-f79b2329-ae4f-461a-a216-a9151c7b2b04.png)

For the number six, you currently can add stocks but it's a little be hidden : 

[Untitled_ Apr 20, 2023 5_09 PM.webm](https://user-images.githubusercontent.com/100699445/233409205-5338dc49-6af9-4794-8c2b-101964f04744.webm)

Alignment problem.

![image](https://user-images.githubusercontent.com/100699445/233409543-84bc7043-7737-41cd-a2d6-a93ef156d845.png)

Incorrectly displayed prices.

![image](https://user-images.githubusercontent.com/100699445/233410146-994187a9-3af6-438d-942a-08cf2e9b7132.png)

---------------------------------

But with some of them I didn't reproduce it,
Did you do a hard refresh on the page with mobile system ?

as you can see : 

Save and publish display problem.

![image](https://user-images.githubusercontent.com/100699445/233404968-56a8f673-3f89-45d6-9472-be1ff6506b99.png)

Three dots icon is not aligned correctly.

![image](https://user-images.githubusercontent.com/100699445/233405453-6ea03e0e-a20e-4c2a-85be-1fd546c0ca98.png)

Features are displayed in a very confusing way.

![image](https://user-images.githubusercontent.com/100699445/233406274-ffd8b326-1a58-4c9b-af3b-9ddb8ab7e9cb.png)

Cost price displayed incorrectly (I'm aware that it's a tricky element to display, maybe a responsive table would be better).

![image](https://user-images.githubusercontent.com/100699445/233410835-e365aab7-0297-46b4-adc0-aa18b81c646a.png)

--------------------------------

Some of these issue can be directly corrected, but some of them (like the button placement) should be checked by PM 

Thank you

**Comment by ElodieOS** [comment]
Hello @kpodemski,

Like @AureRita said, some of issues can be directly corrected and I am agree with these propositions. 

For the 8: "incorrectly display prices", we already have an issue which is resolved (for UX phase): https://github.com/PrestaShop/PrestaShop/issues/34675

I made mockup for 5 and 6 and I add the mockup for the 8

Wdyt?

![image](https://github.com/PrestaShop/PrestaShop/assets/113457393/468afe41-213e-45b1-a54b-3b20789d6cb8)

**Comment by mattgoud** [comment]
I'm watching

**Comment by mattgoud** [comment]
For number 4, I created a separate issue : #35765
