### ISSUE TITLE
GDPR module v1.4.3 + PS 8.0.3 - tinysetup error

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/PrestaShop#32210]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When i try to add text in the richtext box, thre is no Tinyeditor active.

![image](https://user-images.githubusercontent.com/16102074/233152864-2486b61e-87cc-4427-b52e-c590b85fc1eb.png)

Looking in browser console appear this error, like the TinyEditor is not loaded correctly
![image](https://user-images.githubusercontent.com/16102074/233152547-fd28aef8-d3c4-433b-a25a-12934002833a.png)

### Expected behavior

usually in GDPR module where there are richtext area the editor appear like that:

![image](https://user-images.githubusercontent.com/16102074/233153089-62e6c588-8ca4-4a7e-9de8-f863fa0b4fc2.png)

### Steps to reproduce

1) fresh install PS 8.0.3
2) go to the module GDPR 
3) Try to edit text in richtext area, there are no richtext (TinyEditor) active
4) look in browser console and see that is present an error as reported

### PrestaShop version(s) where the bug happened

8.0.3

### PHP version(s) where the bug happened

7.4 / 8.1

### If your bug is related to a module, specify its name and its version

psgdpr

**Comment by AureRita** [comment]
Hi @HartLarsson 

Thank you for your report, I try to reproduce your issue as you can see : 

[Untitled_ Apr 20, 2023 12_56 PM.webm](https://user-images.githubusercontent.com/100699445/233345988-b3c21802-691b-44b4-9531-f51eedadd2d6.webm)

But unfortunately, I can't reproduce it, did I miss something ? 

Can you provide us a video ? 

Waiting for your feedback

**Comment by Jonteep** [comment]
I am having the same issue, although only on one(?!) of my two websites which now has 8.0.3.

The websites are identical, with PHP 8.1, mariaDB 10.5, Prestashop 8.0.3, same modules, etc.

On one of the websites the tiny editor is missing in backend, for Official GDPR Module?

Anyone with a solution? I have tried resetting the module, disable and enable, and so on.

EDIT: It's the same with version 1.4.3 and also the pre-release 2.0.0 and 2.0.1.

Best regards,

**Comment by HartLarsson** [comment]
> Hi @HartLarsson
> 
> Thank you for your report, I try to reproduce your issue as you can see :
> 
>  Untitled_.Apr.20.2023.12_56.PM.webm 
> But unfortunately, I can't reproduce it, did I miss something ?
> 
> Can you provide us a video ?
> 
> Waiting for your feedback

the only way to fix it is to reset or reinstall the gdpr module again.

**Comment by HartLarsson** [comment]
> Hi @HartLarsson
> 
> Thank you for your report, I try to reproduce your issue as you can see :
> 
>  Untitled_.Apr.20.2023.12_56.PM.webm 
> But unfortunately, I can't reproduce it, did I miss something ?
> 
> Can you provide us a video ?
> 
> Waiting for your feedback

please try to install from scratch and NO DEMO record installed too.

Thanks

**Comment by AureRita** [comment]
Hi @HartLarsson 

I tried with a new install as you can see and I don't reproduce your issue, as you can see : 


https://user-images.githubusercontent.com/100699445/236258088-81568bc0-3975-4708-aef1-a8a29b7d849e.mp4


Did I miss something ? 

waiting for your feedback

**Comment by HartLarsson** [comment]
i've no idea why yours work. have you choose as language ITALIAN? I forgot to specify i choose not english as defautl language.
Maybe coudl be that the problem?

**Comment by paulnoelcholot** [comment]
Hello @HartLarsson,

I tried to reproduce your issue as you can see : https://watch.screencastify.com/v/UYcvnyBzCFDOaYHMB9v9

But I can't reproduce too. Do you have any additional information that could help us reproduce the problem?

Thanks for your feedback

**Comment by djoelleuch** [comment]
Hello @HartLarsson ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. 
Please note that you can always create a new one if further information pops up.

Thank you
