### ISSUE TITLE
ImageManager: Bad error msg on "Product page" in BO when loading unsupported image formats with enabled Debug mode

### ISSUE THREAD

**Issue by szavadskiy** [PrestaShop/PrestaShop#32220]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Debug mode enabled: if I add image with unsupported image format (.bmp) for the product, I get en wrong error msg:
![scrnli_4_19_2023_6-06-16 PM](https://user-images.githubusercontent.com/90208051/233352112-cb11dae3-3401-4b2b-b1d9-06dc18cf6f14.png)
 

### Expected behavior

![scrnli_20_04_2023_13-26-27](https://user-images.githubusercontent.com/90208051/233352326-9d243809-9552-4421-9c8e-78361d9990dd.png)

### Steps to reproduce

1. Enable "Debug mode" in BO
2. Open some product page in BO
3. Add some image with unsupported image formats like .bmp / .webp
4. Check msg

### PrestaShop version(s) where the bug happened

1.7.8.8 / 1.7.8.9 

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @szavadskiy ,

I have indeed reproduced your issue in PS 1.7.8.9 in PPV1 :x: , but not PPV2 ✅ . 
In later versions : 8.0.x, 8.1.x and develop branch, it is OK, the error message is correct. ✅ 

![image](https://user-images.githubusercontent.com/16019289/234237403-854f37e9-a396-4fd1-ba2b-159706cb8320.png)

I'm not sure this will be fixed. @PrestaShop/product-team can you confirm what is the future for this issue ?

**Comment by MatShir** [comment]
Hi @szavadskiy, 
We won't fix this issue since it is fixed in the new product page and the 1.7.8.x is only maintained for critical bugs and security issue. 
Thanks anyway for the bug report 🤗
