### ISSUE TITLE
Spike : definition of scopes

### ISSUE THREAD

**Issue by fabienvallon** [PrestaShop/PrestaShop#32231]
### Description 

We need to define scopes for our WebAPI v2
These scopes are a list of endpoint based on our CQRS 

### Expected Attendee 

- [x] - Check what is the best way to do it + benchmark ?  ( github, slack ) : @Zoefinders 
- [x] - Define permissions ( Read, Write , R+W ? , Delete , Bulk ....) & url 
- [x] - Definition des noms des scopes, need endpoint & ADR  https://github.com/PrestaShop/ADR/pull/35

List of scopes  / permissions and related endpoint 

We need to identify the commands that use VOs as parameters in their constructors/setters. (`AddressId`, `ProductId`, anything that is not a scalar value)

**Comment by WahbiPS** [comment]
~~Waiting for CQRS export (cc @fabienvallon )~~

**Comment by mflasquin** [comment]
https://www.notion.so/prestashopcorp/b3e5bef5c17b40bb9b4783af981ab3c0?v=9a86006f9ef04a0996c1cc72120383a6

**Comment by Zoefinders** [comment]
Models of scopes 

**MVP, select box très simple**
[Cart.read, Order.read, OrderReturn.read, Cart.read_and_write, Order.read_and_write, OrderReturn.read_and_write]


**More advanced, donner une structure pour structure et définir des groupes de scopes pour simplifier l'UX**
- ScopeDomainA
  label:
    en: Cart only
    fr: Just les paniers
  description:
    en: You can control carts
    fr: Vous pouvez éditer les paniers
  access options:
    - no accesses:
      labels:
        en: No access
        fr: Aucun accès
      scopes: []
    - read only:
      labels:
        en: Read only
        fr: Lecture seule
      scopes: [Cart.read]
- ScopeDomainB
  label:
    en: Order management
    fr: Gestion commandes
  description:
    en: You can control orders and related data
    fr: Vous pouvez éditer les commandes et leur configuration
  access options:
    - no accesses:
      labels:
        en: No access
        fr: Aucun accès
      scopes: []
    - read only:
      labels:
        en: Read only
        fr: Lecture seule
      scopes: [Order.read, Cart.read]
    - read and rite:
      labels:
        en: Read and write
        fr: Lecture et écriture
      scopes: [Order.read_and_write, Cart.read_and_write]
