### ISSUE TITLE
ps_accounts big problems

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#32237]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
today at the same time, I had two websites down due a curl error from ps_accounts (they are on a dedicated server)

![a](https://user-images.githubusercontent.com/653230/233563976-62e9adb2-c370-453b-85ca-87b725fdadc7.png)

to resolve this problem I have renamed ps_accounts to ps_accounts111 but the paypal doesn't appears on the checkout

can I ask you to remove the dependence from ps_checkout? because in this mode you add problems are added if ps_accounts doesn't workblem

bye

### Steps to reproduce

this problem is present on two websites and the other 20 work well, but it is necessary to remove the dependency between the two modules

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_accounts 5.3.6

**Comment by Maofree** [comment]
the hosting told me that the problem is due to the ps_accounts module and not the site server. I see a timeout error on a curl call, I guess to the prestashop servers and then it fails because it doesn't get a response, this then sends the site down, both admin side and front side and now it doesn't make the other ps_checkout module work

**Comment by Maofree** [comment]
right now I've renamed from ps_accounts111 to ps_accounts and all is ok without this error

in practice if there were connection problems between the site server and the prestashop one with the ps_accounts module the site crashes because the module returns a timeout error in the curl connection to the prestashop server. To solve it, you need to rename the folder and wait 1-2 hours, to see the connection problems on the Prestashop servers resolved, then rename the module folder again. Meanwhile paypal is not working. The problem is if it happened at night when no one warns you, or during holidays or on multiple sites it would be crazy

**Comment by emmanuelgautier** [comment]
Hello @maofree,

Thanks for reaching out. The ps_checkout module depends on the ps_account module to work properly, you should not disable it or remove it.

The ps_account module needs to get access to an API exposed by our services to keep the association active between your shop and our system. We did not have any outages recently, a timeout sounds strange here. Can your shop make external requests server-side?

**Comment by Maofree** [comment]
Hi @emmanuelgautier 
these two websites are configurated like others, nothing of specials, te strange thing is that both were down at the same time this morning with the same timeout curl error
so this depends from your server who did not answer their calls. The problem only happened to these two sites, which are on two dedicated servers.
after 2 hours the situation returned to normal

**Comment by emmanuelgautier** [comment]
This timeout can happen between your shop and our service. But, no matter where the timeout occurred, this behavior should not happen. We are discussing a different way to manage those errors inside our module and modules that integrate us so that will not have such an impact on the shop.

Meanwhile, this repository is the Open Source core solution of Prestashop and this issue is not related to this project but to the checkout and account modules. If it is OK for you, we can close this issue on this repo. You can fill out a ticket on the [Prestashop Help Center](https://help-center.prestashop.com/en) with some additional information about your shop and your hosting provider in order to have a closer look at your case. Do not hesitate to share this issue to have some continuation for this discussion.

**Comment by Maofree** [comment]
ok you can close this topic

you should avoid extra connections for this type of modules, because ps_checkout connects to paypal servers and sometimes they have errors, then if you add more connections to other remote servers the chances of error increase a lot. The bad thing is that they create errors that crash entire sites
