### ISSUE TITLE
Incorrect count of the quantity of a customized product in the cart.

### ISSUE THREAD

**Issue by Codencode** [PrestaShop/PrestaShop#32233]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If an product has 3 available quantities and has a text field for customization (not mandatory), by adding the customized product to the cart, it is also possible to add 3 non-customized ones.
This occurs because the system for calculating the quantity of the item in the cart does not count the customization.
I attach a video

https://user-images.githubusercontent.com/2463965/233431462-45f4394d-ca31-4241-ba3f-2a00e6ff6207.mp4

https://user-images.githubusercontent.com/2463965/233431471-9646ac18-0fea-4a40-8979-f18afcb3687b.mp4

https://user-images.githubusercontent.com/2463965/233431476-9fc0336a-541a-4db2-97ec-9483547c86a3.mp4

### Expected behavior

The system should add a maximum of 3 quantities of the article, thus also verifying the personalized article

### Steps to reproduce

In a fresh installation of Prestashop:
1. Modify article ID 19 by setting quantity 3 and setting the non-mandatory customization field (Options > Customization tab).
2. Go to the product in fronoffice.
3. Fill the personalization field.
4. Save customization.
5. Add the newly customized product to cart.
6. Add 3 quantities of the product (non-customized) to the cart.
7. At this point we have 4 units of item ID 19 in the cart when there are only 4 available.

### PrestaShop version(s) where the bug happened

1.7.x 8.0.x

### PHP version(s) where the bug happened

all

**Comment by paulnoelcholot** [comment]
Hello @Codencode ,

I reproduce the issue with PrestaShop version 1.7.x as you can see, I'll add this to the backlog so it can be fixed.

https://watch.screencastify.com/v/b8UE0HjNwTb1DF2UHSz4

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Codencode** [comment]
Hi @paulnoelcholot,
for my customers I solved, now I try to create a pullrequest with the solution I found.

Thank you!
