### ISSUE TITLE
Spike : Details step of module upgrade and differents ways to upgrade it

### ISSUE THREAD

**Issue by fabienvallon** [PrestaShop/PrestaShop#32258]
### Context 

We need to understand exactly how a module is upgrade 

### Expected Attendees 

1) The differents way to upgrade it ( UX/UI in BO, command line , API ...? ) and if for each mode ( if different ) see (2) 

2) A list of different step of the upgrade  (to add  [into this page :  notion](https://www.notion.so/prestashopcorp/Key-moment-K6-Module-upgrade-1f84ce42e2dd43f8a53f5b9fe6e49fb0)  + into this spike )

Example  [in notion here for installation ](https://www.notion.so/prestashopcorp/Key-moment-K3-Module-installation-done-f2fc4b2ded734f9384a692d4c0f13fe6)

![Image](https://user-images.githubusercontent.com/93661074/233594503-81e3a26e-2b47-46a5-af8c-fcc6a2e82291.png)

**Comment by RosaBenouamer** [comment]
Some question in the notion page https://www.notion.so/prestashopcorp/Key-moment-K6-Module-upgrade-done-1f84ce42e2dd43f8a53f5b9fe6e49fb0

Here a print screen : 
![Image](https://user-images.githubusercontent.com/124665010/236140554-42bbe9f4-8769-4e3a-84c9-717bb2caf496.png)

**Comment by boherm** [comment]
Hi @RosaBenouamer, I answered your questions directly on the notion page :)

**Comment by RosaBenouamer** [comment]
Thany you  @boherm :-)
 @fabienvallon add this question ont the notion page :-) : "Does the upgrade change Right access if needed ? "
