### ISSUE TITLE
Spike : Details step of module uninstallation and differents ways to uninstall it

### ISSUE THREAD

**Issue by fabienvallon** [PrestaShop/PrestaShop#32257]
### Context 

We need to understand exactly how a module is uninstall 

### Expected Attendees 

1) The differents way to uninstall it ( UX/UI in BO, command line , API ...? ) and if for each mode ( if different ) see (2) 

2) A list of different step of the uninstallation (to add  [into this page :  notion](https://www.notion.so/prestashopcorp/Key-moment-K4-Module-uninstallation-de6bfc67a09c441d9e39643222e1816f)  + into this spike )

Example  [in notion here for installation ](https://www.notion.so/prestashopcorp/Key-moment-K3-Module-installation-done-f2fc4b2ded734f9384a692d4c0f13fe6)

![Image](https://user-images.githubusercontent.com/93661074/233594503-81e3a26e-2b47-46a5-af8c-fcc6a2e82291.png)

**Comment by RosaBenouamer** [comment]
Result of the spike
 <html>
<body>


Steps
--



</body>
</html>


Question 1) about step $this->database->set('installed', !$result);
What does it do ?

Question 2) about step <html>
<body>


Delete meta_lang and meta associate to module controller
--



</body>
</html> What does it do ?
