### ISSUE TITLE
Spike : upgrade PS Core & different ways to upgrade it

### ISSUE THREAD

**Issue by fabienvallon** [PrestaShop/PrestaShop#32264]
### Context 

To better improve the upgrade module, we need to understand the major elements executed in the script of the upgrade module or CLI to improve them in future versions.

### Expected Attendees 

1. The different way to upgrade PSCore:

-  (auto)-upgrade (1-click upgrade module)
- command line 
- and if there are different ways see (ask @kpodemski for inputs)

2. A list of different steps of the PS Core upgrades (to add  [into this page :  notion](https://www.notion.so/prestashopcorp/Key-moment-K8-Shop-upgrade-d0b7122d867f48bfbde7c46931465b03)  + into this spike )

Example  [in notion here for installation ](https://www.notion.so/prestashopcorp/Key-moment-K3-Module-installation-done-f2fc4b2ded734f9384a692d4c0f13fe6)

**Comment by matks** [comment]
```
1. The different way to upgrade PSCore:
(auto)-upgrade (1-click upgrade module)
command line
and if there are different ways see (ask @kpodemski for inputs)
```

The Autoupgrade module assistant provides 2 ways to upgrade shops: one using command line and one using a web interface. Both are being powered by https://github.com/prestashop/autoupgrade

Here is a detailed documentation about the web interface about how to use https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/use-autoupgrade-module/
Here is a detailed documentation about the command line https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/upgrade-module/upgrade-cli/

> and if there are different ways see (ask @kpodemski for inputs)
The Upgrade assistant is an _engine_ that automatically runs a series of steps.
These steps are
- PHP scripts
- SQL queries to be run against the database

Some people do not trust the automatic process. Then they choose to _run the PHP scripts and execute the SQL queries themselves_. As they do it manually, this allows them to better control the process, they can stop, they can run again something, they can fine-tune or customize one script or query. They simply look at the _related script_ and do it.

By _related script_ I mean: each PrestaShop version centralizes PHP scripts and SQL queries in a single file, with version in name. Here they are, all of them https://github.com/PrestaShop/autoupgrade/tree/dev/upgrade/sql

So these people pick the file, check the content and then do it step by step, manually

**Comment by matks** [comment]
> A list of different steps of the PS Core upgrades (to add [into this page : notion](https://www.notion.so/prestashopcorp/Key-moment-K8-Shop-upgrade-d0b7122d867f48bfbde7c46931465b03) + into this spike )

Here is a detailed documentation about the steps that the Upgrade module performs https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/upgrade-module/upgrade-process-steps/

As you can see, there is multiple steps. If we exclude the "Unzip" steps or steps similar, and focus on "what happens when I upgrade my shop" and remove the "security steps" you can see it happens in 3 steps
- UpgradeFiles
- UpgradeDb
- UpgradeModules

**Comment by matks** [comment]
When a developer starts working on this, ping me or jolelievre for an introduction about the Upgrade topic

**Comment by mflasquin** [comment]
More detailed steps in notion : https://www.notion.so/prestashopcorp/Key-moment-K8-Shop-upgrade-d0b7122d867f48bfbde7c46931465b03

**Comment by WahbiPS** [comment]
Already presented to Rosa
