### ISSUE TITLE
[develop] - Exception displayed Attempted to call an undefined method named "l" of class "AdminPsThemeCustoConfigurationController".

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#32266]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In Theme & Logo > Pages Configuration, an exception is displayed.

```
Attempted to call an undefined method named "l" of class "AdminPsThemeCustoConfigurationController".
Did you mean to call e.g. "addFiltersToBreadcrumbs", "addJqueryPlugin", "addMetaTitle", "ajaxProcessUpdateModule", "authorizationLevel", "createTemplate", "display", "displayAjax", "displayFooter", "displayHeader", "displayHeaderJavaScript", "displayRequiredFields", "getController", "getFieldValue", "getFieldsValue", "getTabSlug", "getTemplateFormVars", "getTemplateListVars", "getTemplatePath", "getTemplateViewVars", "initModal", "initMultistoreHeader", "initPageHeaderToolbar", "initToolbar", "initToolbarFlags", "initToolbarTitle", "isMultistoreEnabled", "isXmlHttpRequest", "myErrorHandler", "processDelete", "processDeleteImage", "processFilter", "processResetFilters", "processUpdateFields", "renderDetails", "renderModal", "setFinalList", "setHelperDisplay", "setModuleFinalList", "setTemplate", "sortArrayInstalledModulesFirst", "validateRules" or "viewDetails"?
```

<img width="1089" alt="Screenshot 2023-04-21 at 15 31 42" src="https://user-images.githubusercontent.com/16019289/233648968-9810d2f8-4ed6-4321-847e-e919bc336abc.png">

If I disable ps_themecusto, the tab Pages Configuration is not displayed, so no exception is displayed.

This error is only present on `develop` branch, on `8.0.x` and `8.1.x` it works fine.

### Expected behavior

I should access this page without exception :
<img width="1234" alt="Screenshot 2023-04-21 at 15 33 42" src="https://user-images.githubusercontent.com/16019289/233649147-aae16dda-2edd-479d-ad62-16381c5b5891.png">

### Steps to reproduce

1. Go to BO > Design > Theme & Logo
2. Click on Pages Configuration
3. See exception

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

Theme Customization v1.2.2

**Comment by matks** [comment]
@florine2623 Is it identical to https://github.com/PrestaShop/PrestaShop/issues/32180 ?
