### ISSUE TITLE
refresh admin after change subdomain to domain

### ISSUE THREAD

**Issue by EhsanAllahyari** [PrestaShop/PrestaShop#32295]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,
I use my website on a shared hosting and I move to a new one.
before that I move the site, I create a subdomain and test the new shared hosting. and every thing working fine.
after I change subdomain to domain the login page refreshed and did not login.

I modify the shop_url on database and .htaccess file and configuration table on database.

but the login form refreshing every time that I enter login info.
no error appear after refresh

Database server
Server: Localhost via UNIX socket
Server type: MariaDB
Server connection: SSL is not being used Documentation
Server version: 10.3.38-MariaDB - MariaDB Server
Protocol version: 10
User: myuser@localhost
Server charset: cp1252 West European (latin1)

Web server
cpsrvd 11.108.0.15
Database client version: libmysql - mysqlnd 7.4.33
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 7.4.33

phpMyAdmin
Version information: 4.9.11

### Steps to reproduce

install a fresh PS 1.7.8.5 on subdomain
check everything and working fine
change the subdomain to domain
modify shop_url and configuration
modify htaccess and change subdomain to domain
clear cache
admin login not working

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @EhsanAllahyari ,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

Thank you
