### ISSUE TITLE
Order creation from cart with expired voucher

### ISSUE THREAD

**Issue by Codencode** [PrestaShop/PrestaShop#32303]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If a coupon with an expiry date is inserted in a cart, but the order is concluded after this expiry, the coupon remains in the cart anyway and the system concludes the order with the expired coupon.
For convenience, I attach a video in which I add a voucher with an expiry date after the date of addition, then I change the expiry date of the voucher to an earlier date, and the system lets me complete the order.

https://user-images.githubusercontent.com/2463965/233968537-3e2d7b3e-cef6-4426-84e2-b9d05808c2c5.mp4

https://user-images.githubusercontent.com/2463965/233968551-fe8f1b0f-b2dd-4d1f-abdc-65aead10c1b9.mp4

### Expected behavior

The system should behave as if the voucher has been deactivated and therefore remove it from the cart.

### Steps to reproduce

1. Create a coupon dated after the current day
2. In the front-office, add the coupon to the cart
3. Change the coupon expiration date to a date before the current day
4. In the front office complete the order
5. The system has created the order including the expired coupon

### PrestaShop version(s) where the bug happened

8.0.x, 8.1.x

### PHP version(s) where the bug happened

all

**Comment by Hlavtox** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/19393

It could be fixed by this PR - https://github.com/PrestaShop/PrestaShop/pull/30905

**Comment by Codencode** [comment]
Hi @Hlavtox,
in issue #19393 the problem occurs in case the voucher is disabled. This problem has been solved.
The problem I have is when changing the expiration date to a past date.
I attach a video.

Thank you!

https://user-images.githubusercontent.com/2463965/233972503-aab95e84-bac5-4143-948a-7d4e34943c46.mp4

**Comment by Hlavtox** [comment]
@Codencode There is definitely an issue for this somewhere. The cart rule is just not removed from cart if it expires.

**Comment by Codencode** [comment]
> @Codencode There is definitely an issue for this somewhere. The cart rule is just not removed from cart if it expires.

Ok,
I fixed it by making some changes.
As soon as possible create a PR to propose my solution.

**Comment by florine2623** [comment]
Hello @Codencode ,

Can you confirm your issue is similar to this one : https://github.com/PrestaShop/PrestaShop/issues/19393 ?

Waiting for your feedback ^^
Thanks!

**Comment by Codencode** [comment]
> Hello @Codencode ,
> 
> Can you confirm your issue is similar to this one : #19393 ?
> 
> Waiting for your feedback ^^ Thanks!
Hi @florine2623 ,
you are right the problem I encountered is similar to [#19393](https://github.com/PrestaShop/PrestaShop/issues/19393).
@Hlavtox already pointed it out to me and it seemed different to me, now I checked better and I confirm.
Sorry @Hlavtox.
