### ISSUE TITLE
Tooling for cqrs - endpoints - kanban managment

### ISSUE THREAD

**Issue by fabienvallon** [PrestaShop/PrestaShop#32313]
As a PM I want be able to manage list of cqrs & endpoint so I can create and maintain Kanbans for contributors

## Tooling

Serveral tools : 

Tool 1: 

List all CQRS available into a branch ( develop for example ) & into a build : see console prestashop:list:commands-and-queries

Acceptance test  : 
- The list should be filtered by domain `--domain Zone => CQRS from PrestaShop\PrestaShop\Core\Domain\Zone` `--all-domains` => tous less domaines
- The output list should be at the least a list of CQRS `--format simple` (list command on each line)
- The output should usable into a file ( for all Operating system : Windows , Linux , Mac ) `--output /file/list`

Tool 2 : 
Make difference of the available CQRS in 2 weeks or more `diff list-week1 list-week2`
It could be a simple set of Unix command : diff , sort &   tool1 (see above ) 

Acceptance test : 
Between 2 dates ( for exemple 2 sorted files ) , the tool should have as output the difference ( new CQRS or modified CQRS )  

Tool 3 : 
The tool should show the implemented endpoint based on CQRS from a list of CQRS ( Tool 1 or tool 2 ) 

The command can check the mapping between a CQRS command and an API that depends on it
```
397.
Class: PrestaShop\PrestaShop\Core\Domain\Zone\Command\BulkToggleZoneStatusCommand
Type: Command
API: /zone/bulk-toggle
Toggles zones status on bulk action
```

`--format simple` => 
List opk CQRS commands OK or NOT OK (has API?)
```
PrestaShop\PrestaShop\Core\Domain\Zone\Command\BulkDeleteZoneCommand OK
PrestaShop\PrestaShop\Core\Domain\Zone\Command\BulkToggleZoneStatusCommand NOT OK
```

**Comment by tleon** [comment]
Regarding the behavior of the command. 

The --all option has not been implemented as it is the default behavior of the command. 
The --output option has not been implemented either because this behavior can be easily achieve with a > ( linux output redirection) and it simplifies the logic of the command by a lot.

The rest of the options have been implemented as asked.
