### ISSUE TITLE
Stocks page refresh issue - token removed from URL

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#32329]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When refreshing the page on back-office Stocks page, I lose the token in the URL.

### Expected behavior

Refreshing the page should preserve the token

### Steps to reproduce

1. Get 8.1.x
2. Go to Back-office, go to "Stocks" page
3. Go to `Movements` tab
4. Verify URL contains token as expected
5. Refresh page in your browser = security compromised, the token has been removed from the URL

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

N/A

**Comment by boherm** [comment]
@Hlavtox, it seems to be in 8.0.x and 1.7.8.x branches as well.

**Comment by Hlavtox** [comment]
@boherm Ha, possible, did not test it. Do you think it's an easy fix like with translation page urls?

**Comment by boherm** [comment]
@Hlavtox, I'm checking that.
We use `<router-link>` for this tabs links and we don't inject `_token`, but I don't really know how to do it in a good way.

**Comment by florine2623** [comment]
Hello @Hlavtox ,

I reproduce the issue with PrestaShop versions `1.7.8.x`, `8.0.x`, `8.1.x`, `develop`, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Hlavtox** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/32424
