### ISSUE TITLE
The languages of terms of service pop-up is not coherent with the languages of FO

### ISSUE THREAD

**Issue by AchrafKchaou1991** [PrestaShop/PrestaShop#32333]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I found this issue #28556 but it's not the same

The language of the terms of service is not compatible with the current language on FO

[bug2.webm](https://user-images.githubusercontent.com/131356155/234256174-114e6d56-1f9b-4638-b21c-87b0361cf457.webm)

### Expected behavior

The language in `the terms of service` shall be similar than required by the user

### Steps to reproduce

1.Connect to the FO
2.Choose any product and click add to cart then PROCEEED TO CHEKOUT
3.Continue to 1.PERSONAL INFORMATION , 2.ADDRESSES 3.SHIPPING METHOD
4.In Payement click in terms of service,

### PrestaShop version(s) where the bug happened

8.0.3

### PHP version(s) where the bug happened

8.0

**Comment by florine2623** [comment]
Hello @AchrafKchaou1991 ,

This is Lorem Ipsum. It is meant to be modified by the merchant ^^

This is not an issue. I'll close it to avoid clogging the backlog.
Thanks
