### ISSUE TITLE
A bad display of the menu when changing the language using the translator of chrome

### ISSUE THREAD

**Issue by AchrafKchaou1991** [PrestaShop/PrestaShop#32332]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I connect to the BO and I use the plugin of google translator in the browser (google Chrome version 112,0,561549) to translate the language from English to French,a misalignment appear in the menu.

[bug1.webm](https://user-images.githubusercontent.com/131356155/234254282-f6f00914-cf84-4d60-99f1-b28dd93a4503.webm)

### Expected behavior

The menu will appear aligned.

### Steps to reproduce

1. Have the transalator on google as extension
2. Connect to the BO
3. Choose the English in Prestashop
4. Click in the plugins to change the languages from English to French
5. See the misalignment in the menu 

### PrestaShop version(s) where the bug happened

8.0.3

### PHP version(s) where the bug happened

8.0

**Comment by florine2623** [comment]
Hello @AchrafKchaou1991 ,

This is not an issue from PrestaShop. With your plugging, the menu is correct.

So I will close it.

**Comment by AchrafKchaou1991** [comment]
@florine2623 Thanks for your quick feedback. But, the issue is displayed when using the translation of the extension of Chrome
Did you try it ?
