### ISSUE TITLE
Deprecated message has raisen while order confirmation

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#32331]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I found a similar issue #27204 but this last one has been fixed by this PR https://github.com/PrestaShop/ps_checkpayment/pull/55 withthe latest version 2.0.6. But yet the problem still exist: 

![image](https://user-images.githubusercontent.com/23308427/234301745-062da4a5-2622-44ed-8cfa-8b83732eadaa.png)

### Expected behavior

No warning message is displayed

### Steps to reproduce

1. FO > Create an order
2. Choose `ps_checkpayment` as payment method
3. Confirm the order
4. See error > a Deprecated warning is displayed

### PrestaShop version(s) where the bug happened

8.0.2

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_checkpayment 2.0.6

**Comment by hibatallahAouadni** [comment]
Reported originally by @EmnaChou

**Comment by florine2623** [comment]
Hello @hibatallahAouadni & @EmnaChou

I can't reproduce your issue on my end.
I tested with ps_checkpayment v2.0.6, with PHP 7.3 and 8.1, on 1.7.8.x, 8.0.x, 8.1.x and develop.


https://user-images.githubusercontent.com/16019289/234306792-4230c73f-ce15-41c7-a01c-c6a29830ca00.mov

ping @PrestaShop/qa-functional could you test it on your end ?
Thanks :)

**Comment by Hlavtox** [comment]
@hibatallahAouadni Are you sure that you are testing on a 2.0.6 version of the module? And that the install is not somehow corrupted and the module is not hooked to `paymentReturn`?

**Comment by hibatallahAouadni** [comment]
Sorry my bad :sweat_smile: it was a cache issue :wink:
