### ISSUE TITLE
Displaying 'Last item' instead of 'Sold Out' on a product page

### ISSUE THREAD

**Issue by 01Kuzma** [PrestaShop/PrestaShop#32341]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I sell only one unique product in my PrestaShop store (upgraded to 8.03), and I want to maintain its SEO value even when it's sold out. To do so, I'm displaying a "sold" label on the main catalog page, but when I open the sold product the label is changed to "Last item". And this is incorrect.

The problem is that the `{$product.availability|print_r} value currently shows "last_remaining_items1,"`
It's misleading for customers who think the product is still available, while it's sold out. 
![image](https://user-images.githubusercontent.com/569504/234520702-9d34f2cc-5084-42a0-9e58-7ac2023665e1.png)

I've created a [dedicated forum thread](https://www.prestashop.com/forums/topic/1076094-displaying-last-item-instead-of-sold-out-on-a-product-page/) for this

### Steps to reproduce

Open the sold product, the label is changed to "Last item".

### PrestaShop version(s) where the bug happened

8.0, 8.03

### PHP version(s) where the bug happened

7.4, 8.0

**Comment by Hlavtox** [comment]
Can you tell us your exact settings so I can have a look on it?
- Send screenshots of labels set in Prestashop settings.
- Send screenshots of labels set on product.
- How many pieces of product are in stock?
- Is it allowed to order it when not in stock?

BTW, I added a new functionality to Prestashop 8.1 that will allow you to keep displaying disabled products with a "NO LONGER FOR SALE" label. 👍

**Comment by 01Kuzma** [comment]
Hi, here they are, sorry, it's in Lithuanian:
![image](https://user-images.githubusercontent.com/569504/234555637-44b42451-d155-4960-8968-fadd1dae0af9.png)
"Send screenshots of labels set on product." - point me please, where product labels are controlled in BO
We sell only 1 product, so in stock only "1"
"Is it allowed to order it when not in stock?" - no

If it's not enough, please ask me for a specific details

**Comment by 01Kuzma** [comment]
@Hlavtox can you confirm it?

**Comment by Hlavtox** [comment]
@01Kuzma You must send a screenshot of your settings because from what I know the availability labels are working perfectly.

Availability labels are controlled on Stock or Combinations tab when editing a product. You can type in whatever "Label when not in stock" you want.

**Comment by 01Kuzma** [comment]
I've changed UI to English.
I'm posting the options from the product. Is it enough or I've skipped something?
Thank you!
![image](https://user-images.githubusercontent.com/569504/235062537-02f28e30-99e8-4331-8203-df18a1573e7c.png)
![image](https://user-images.githubusercontent.com/569504/235062555-546e603e-7689-4885-a1f1-f80fc6e99291.png)
![image](https://user-images.githubusercontent.com/569504/235062571-999e56da-171f-4f39-bf8d-bde2a59d7734.png)

**Comment by Hlavtox** [comment]
Just fill out “Label when out of stock” on the Quantities tab and you can have whatever text you want. :-)

**Comment by 01Kuzma** [comment]
@Hlavtox , strange, but this does not work.
Still accessing the sold product label is wrong, while in the main list it's right,
Cache is cleared and smarty cache is turned off.
Here are the settings and results:
![image](https://user-images.githubusercontent.com/569504/235135872-7c5953a9-71e9-406a-bd51-ba8e14f6ae54.png)
![image](https://user-images.githubusercontent.com/569504/235135885-5f0568c9-bdcc-4092-a297-65c1728c7bc4.png)

**Comment by 01Kuzma** [comment]
@Hlavtox , @florine2623 , as you can see suggestions don't work. 
You hurried up closing it.
Bear in mind, that my shop by default runs on non-native (non-english) FO and BO language, so, it could be the issue

**Comment by Hlavtox** [comment]
@01Kuzma I worked on this feature recently, it works perfectly.

If you want to report an issue, we will need a screenshot in english, with classic theme.

**Comment by 01Kuzma** [comment]
@Hlavtox , here it is:
![image](https://user-images.githubusercontent.com/569504/235420821-fa53f012-3aa2-4920-bc6a-b5a90a0a342a.png)

**Comment by 01Kuzma** [comment]
@Hlavtox is it enough?
