### ISSUE TITLE
If you delete thumbnails of placeholder images, their thumbnails are not regenerated again.

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#32351]
**Issue**

If you delete thumbnails of placeholder images, their thumbnails are not regenerated again.

![Snímek obrazovky 2023-04-21 140353](https://user-images.githubusercontent.com/6097524/233630915-62cbbe31-fb05-415b-ad5c-7dbb49aec136.jpg)

_Originally posted by @Hlavtox in https://github.com/PrestaShop/PrestaShop/issues/18257#issuecomment-1517720020_

**Expected behavior**

Image 'not found' should be generated 

**PS version**

8.1 rc, develop

**Comment by hibatallahAouadni** [comment]
Hello @MatShir 

Could you please provide the version of your Presta and your PHP version.
Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @MatShir 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
