### ISSUE TITLE
Warnings in BO > Shipping > Carrier > New carrier page

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#32355]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Some errors related to translation  appear in BO > Shipping > Carrier > New carrier page

![Capture d’écran de 2023-04-27 09-51-36](https://user-images.githubusercontent.com/24647495/234797580-c340ab0c-0e62-454a-9cc9-cbb3c7ba073b.png)

### Expected behavior

The page should be displayed correctly

### Steps to reproduce

1- Go to BO > SHipping > Carriers
2- Go to new carrier page
3- See the errors

### PrestaShop version(s) where the bug happened

Develop

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment]
Related to https://github.com/PrestaShop/PrestaShop/issues/32262

**Comment by florine2623** [comment]
I have found a new Warning on develop branch :
<img width="1436" alt="Screenshot 2023-05-02 at 14 45 11" src="https://user-images.githubusercontent.com/16019289/235669888-85984d06-cc6d-432a-b9c4-f2d2b726ae25.png">
