### ISSUE TITLE
autoupgrade issues from 8.0.1 onwards

### ISSUE THREAD

**Issue by garbus2** [PrestaShop/PrestaShop#32365]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I keep getting similar error every time upgrade PS8 althought the shop seems to be working :

```
[INTERNAL] /usr/home/garbus2/domains/nowysklep8.sokolnictwo.pl/public_html/src/PrestaShopBundle/Command/UpdateSchemaCommand.php line 141 - TypeError: Unsupported operand types: int + Doctrine\DBAL\ForwardCompatibility\Result #0 
/usr/home/garbus2/domains/nowysklep8.sokolnictwo.pl/public_html/src/PrestaShopBundle/Command/UpdateSchemaCommand.php(76): PrestaShopBundle\Command\UpdateSchemaCommand->dropExistingForeignKeys(Object(Doctrine\DBAL\Connection), Object(Symfony\Component\Console\Output\BufferedOutput)) #1 
/usr/home/garbus2/domains/nowysklep8.sokolnictwo.pl/public_html/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(255): PrestaShopBundle\Command\UpdateSchemaCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput)) #2 
/usr/home/garbus2/domains/nowysklep8.sokolnictwo.pl/public_html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(1039): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput)) #3 
/usr/home/garbus2/domains/nowysklep8.sokolnictwo.pl/public_html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(97): Symfony\Component\Console\Application->doRunCommand(Object(PrestaShopBundle\Command\UpdateSchemaCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput)) #4 
/usr/home/garbus2/domains/nowysklep8.sokolnictwo.pl/public_html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(275): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(PrestaShopBundle\Command\UpdateSchemaCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput)) #5 
/usr/home/garbus2/domains/nowysklep8.sokolnictwo.pl/public_html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(83): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput)) #6 
/usr/home/garbus2/domains/nowysklep8.sokolnictwo.pl/public_html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput)) #7 
/usr/home/garbus2/domains/nowysklep8.sokolnictwo.pl/public_html/src/PrestaShopBundle/Service/Command/AbstractCommand.php(81): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput)) #8 
/usr/home/garbus2/domains/nowysklep8.sokolnictwo.pl/public_html/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(56): PrestaShopBundle\Service\Command\AbstractCommand->execute() #9 
/usr/home/garbus2/domains/nowysklep8.sokolnictwo.pl/public_html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader80.php(51): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->runSchemaUpgradeCommand() #10 
/usr/home/garbus2/domains/nowysklep8.sokolnictwo.pl/public_html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(103): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader80->upgradeDb('8.0.0.0') #11 
/usr/home/garbus2/domains/nowysklep8.sokolnictwo.pl/public_html/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(42): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #12 
/usr/home/garbus2/domains/nowysklep8.sokolnictwo.pl/public_html/admin619071guwbcrhhobu3e/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #13 {main}

```

### Expected behavior

bug fix?

### Steps to reproduce

normal autoupgrade script - just click "upgrade prestashop now"

### PrestaShop version(s) where the bug happened

8.0.3

### PHP version(s) where the bug happened

8.1.17

**Comment by garbus2** [comment]
Informacje o serwerze: FreeBSD FreeBSD 13.0-RELEASE-p12 #4 9f398ead8: Tue Aug 9 21:57:22 UTC 2022 root@pkg13.admin.net.pl:/usr/obj/usr/src/amd64.amd64/sys/devil amd64

Wersja oprogramowania serwera: Apache/N-G-I-N-X-htaccess-support

Wersja PHP: 8.1.17

Limit pamięci: -1

Maksymalny czas wykonywania: 300

Maksymalny rozmiar pliku do przesłania: 2048M

**Comment by garbus2** [comment]
I have read that maybe this is connected with non standard prefix in DB however mine is a standrad ps_



Wersja MySQL: 8.0.32

Nazwa MySQL: m1058_presta8

Użytkownik MySQL: 

Prefix tabel: ps_

Silnik MySQL: InnoDB

Sterownik MySQL: DbPDO

**Comment by nocrap** [comment]
I have exactly same problem. This is really annoying and needs fix. I saw other posts complaining about this. I am using diffferent prefix than ps_ for databases, but considering that OP is using ps_ problem is probably somewhere else.

**Comment by florine2623** [comment]
Hello @garbus2 ,

I'm upgrading from PS [8.0.1](https://build.prestashop-project.org/news/2023/prestashop-8-0-1-maintenance-release/) to 8.0.4 (latest version available).

I'm using 1-Click Upgrade v4.15.0.

The upgrade is successful:

<img width="1434" alt="Screenshot 2023-04-28 at 16 08 06" src="https://user-images.githubusercontent.com/16019289/235170438-878be3e5-7064-49f2-8f82-f42eb520736e.png">

https://user-images.githubusercontent.com/16019289/235170407-9ab18307-76f7-42fb-b860-4b16734a5015.mov

**Comment by garbus2** [comment]
@florine2623 - in my case I got errors upgrading from 8.0.0.1 to 8.0.0.2, 8.0.0.2 to 8.0.0.3 and 8.0.0.3 to 8.0.0.4. You can see the problem above - it keeps repeating. Maybe only in my configuration of server although I have not done any adjustments and using defaults

**Comment by nocrap** [comment]
I have tried to change my database prefix to ps_ and tried to upgrade from 8.0.2 to 8.0.4 and again got same error as OP in first post. There is definitely issue with 1-click upgrade during database upgrading process and it is not related to database prefix.

I have fresh install of prestashop 8.0.2. Just installed "Warehouse theme" on it and nothing else.

Here is error:

> [INTERNAL] /home/******/domains/******/public_html/src/PrestaShopBundle/Command/UpdateSchemaCommand.php line 141 - TypeError: Unsupported operand types: int + Doctrine\DBAL\ForwardCompatibility\Result #0 /home/******/domains/******/public_html/src/PrestaShopBundle/Command/UpdateSchemaCommand.php(76): PrestaShopBundle\Command\UpdateSchemaCommand->dropExistingForeignKeys() #1 /home/******/domains/******/public_html/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(255): PrestaShopBundle\Command\UpdateSchemaCommand->execute() #2
/home/******/domains/******/public_html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(1039): Symfony\Component\Console\Command\Command->run() #3 
/home/******/domains/******/public_html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(97): Symfony\Component\Console\Application->doRunCommand() #4 
/home/******/domains/******/public_html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(275): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() #5 
/home/******/domains/******/public_html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(83): Symfony\Component\Console\Application->doRun() #6 
/home/******/domains/******/public_html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun() #7 
/home/******/domains/******/public_html/src/PrestaShopBundle/Service/Command/AbstractCommand.php(81): Symfony\Component\Console\Application->run() #8 /home/******/domains/******/public_html/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(56): PrestaShopBundle\Service\Command\AbstractCommand->execute() #9 
/home/******/domains/******/public_html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader80.php(51): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->runSchemaUpgradeCommand() #10 
/home/******/domains/******/public_html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(103): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader80->upgradeDb() #11 
/home/******/domains/******/public_html/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(42): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #12 
/home/******/domains/******/public_html/******/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #13 {main}

**Comment by AureRita** [comment]
Hi @garbus2 

Thank you for all these details, can you give us the OS you use with your computer and if you use avast on it ? 

Waiting for your feedback

**Comment by garbus2** [comment]
Hi @AureRita 
OS is Win 11 Home 22H2, browser firefox including Adblock and yes I use avast (free version)

**Comment by nocrap** [comment]
Just for the record, I am also using W11 Pro 22H2 and free Avast.

**Comment by matks** [comment]
Might be related to https://github.com/PrestaShop/PrestaShop/discussions/32348

**Comment by ChillCode** [comment]
Hi @florine2623,

Did you try using PHP 8.1 like the OP did?

**Comment by hibatallahAouadni** [comment]
Hello everyone,

I think you should disable your anti-virus while upgrading.
@matks I think it's related to Operating System Windows and the anti-virus Avast, see this Slack discussion:

![image](https://user-images.githubusercontent.com/23308427/237019734-64970acf-b6cc-45e5-b35f-565347456052.png)

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @garbus2 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by garbus2** [comment]
turning off avast does not help. The error still occurs. Have same issue while trying to upgrade from 8.0.4 to 8.1.0
