### ISSUE TITLE
faceted_search - some pages in FO do not use the filter template

### ISSUE THREAD

**Issue by daniweb78** [PrestaShop/PrestaShop#32363]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The feature "Pages using this template:" doesn't work on all options.
It works for : ✅ 
- Category
- New products
- Best sales
- Prices drop

It doesn't work for : ❌ 
- Manufacturer
- Supplier
- Search (experimental)

<img width="1226" alt="Screenshot 2023-04-28 at 16 51 53" src="https://user-images.githubusercontent.com/16019289/235180892-11372f3e-7c88-4fd4-8748-868bede65049.png">

### Expected behavior

The filter should be visible on all the pages that are checked in BO.

### Steps to reproduce

1. Go to BO > Module > Configure module faceted_search
2. Add the pages (Manufacturer, Supplier and Search) using the template > Save
3. Go to FO in those 3 pages
4. See the filter is not displayed

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_facetedsearch 3.12.1

**Comment by florine2623** [comment]
Hello @daniweb78 ,

Tested with `v3.12.1`, `3.11.1` and `3.10`. The result is the same.

In pages Manufacturers, Suppliers and Search, the filter is not displayed.
```
myshop.com/en/supplier/2-accessories-supplier
myshop.com/en/brand/1-studio-design
myshop.com/en/search?controller=search&s=mug
```

I think it was added in 3.10 with this PR :  https://github.com/PrestaShop/ps_facetedsearch/pull/757. But even after testing it, the filter doesn't show up on the FO.


Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Hlavtox** [comment]
@daniweb78 @florine2623 You need to enable left column in your theme settings
