### ISSUE TITLE
Error 404 Page not found, after trying to update from PrestaShop 1.7.8.8 to 1.7.8.9 using 1-Click Upgrade module

### ISSUE THREAD

**Issue by CCDorel** [PrestaShop/PrestaShop#32368]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

As I wrote in the title I am having an issues (Error 404 - Page not found) when I try to update the store from PrestaShop 1.7.8.8. to 1.7.8.9, using 1-Click upgrade module. The error occurs when I put the store into maintenance mode and trying to acces the 1-Click upgrade module. 

Here are the steps I made:

1. I put the store into maintenance mode;
2. I am trying to access the 1 Click upgrade module... and BOOM the error 404 Page not found occures.

This is my configuration:
PrestaShop 1.7.8.8
PHP 7.4
Theme used: Warehouse (4.5.8)
Languge used: Romanian
Multistore: No

### Expected behavior

After I put the store into Maintenance mode, I'm waiting to be able to access the 1-Click upgrade module interface and do the update.

### Steps to reproduce

1. I put the store into Maintenance mode;
2. Trying to access the 1-Click update module and BOOM....the 404 error occurs ... and it get me out from Back office Dash board into the Front office of the store;
3.  If I disable the Maintenance mode (set to off) It let me access the 1-Click update module again, but since he (1-Click update module) is asking me to put the store into Maintenance mode, the button to perform the upgrade it doesn't appear

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

I don t know

**Comment by paulnoelcholot** [comment]
Hello @CCDorel,

I tried to reproduce this issue but I can't as you can see. Did I miss something?

https://watch.screencastify.com/v/r0mtVNeoQ2KD5GJtjxqC

Thanks for your feedback.

**Comment by CCDorel** [comment]
Hello @paulnoelcholot!

Thank you for triyng to help me

You didn't missed anything, you reproduced the steps correctly, but in my case unfortunately the problem persists. Does anyone have any ideea on how to find where the problem cames from, should I enable debug mode? I will try to disable some custom modules one by one to see if anything changes.

Thank you!

**Comment by AureRita** [comment]
Hi @CCDorel 

I tried with the language romania, with enabled and disabled the debug mode, I didn't reproduce your issue, did you try with the classical theme ? 

If you have some news about this issue tell us, we would be happy to help you 

Waiting for your feedback

**Comment by CCDorel** [comment]
Hi @AureRita,

I apologise for my late answer

Swithing to classical theme didn't changed anything unfortunately, the error persists.
Enabeling the debug mode it showed me these errors:

![13_de_editat](https://user-images.githubusercontent.com/78930359/236729829-e0b84358-fa32-4c62-ad00-8f9cdb703cac.jpg)
![1](https://user-images.githubusercontent.com/78930359/236729854-24197174-3fbc-488e-8800-0633c002c4e8.jpg)
![2](https://user-images.githubusercontent.com/78930359/236729864-6b450465-6b8b-4d7a-ae5b-a5d347743a3e.jpg)
![3](https://user-images.githubusercontent.com/78930359/236729874-3061fb2e-b7a5-4ddf-b560-0a55c0b0aaab.jpg)
![4](https://user-images.githubusercontent.com/78930359/236729881-74f5b933-ba75-4769-86a6-708ea7eff08a.jpg)
![5](https://user-images.githubusercontent.com/78930359/236729888-3841ed6a-7537-47dc-9f98-858135418699.jpg)
![6](https://user-images.githubusercontent.com/78930359/236729895-107cf129-6725-4439-b8cd-ad9d30b232b1.jpg)
![7](https://user-images.githubusercontent.com/78930359/236729902-3bd68060-412f-4217-ab34-f466f8c8ff24.jpg)
![8](https://user-images.githubusercontent.com/78930359/236729911-a243afa0-e46a-41e1-9d42-4b35fbe9b053.jpg)
![9](https://user-images.githubusercontent.com/78930359/236729919-bfb6a72b-56d5-449f-ac4c-b5b7d0e37e81.jpg)
![10](https://user-images.githubusercontent.com/78930359/236729934-6b75035e-b237-43fd-9cb7-d5bcc87ccfd7.jpg)
![11](https://user-images.githubusercontent.com/78930359/236729945-cea68938-0542-4512-ad50-729cccf276a1.jpg)
![12](https://user-images.githubusercontent.com/78930359/236729947-2205662e-ec85-47bd-9c3a-a5b00edc0722.jpg)

Pleas tell me if by mistake I forget to hide important, security informations!

**Comment by florine2623** [comment]
hello @CCDorel ,

Can you make sure the version of 1-click upgrade you are using is the latest one ?
-> v4.15.0

**Comment by CCDorel** [comment]
Yes, the 1-Click Upgrade it's updated to the latest version

**Comment by paulnoelcholot** [comment]
Hello,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you
