### ISSUE TITLE
PPV2 - Searchbox dropdown not displaying properly on "Generate combinations" modal

### ISSUE THREAD

**Issue by l-delin** [PrestaShop/PrestaShop#32360]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

When trying to manually type in an attribute's name and choosing it from the dropdown list on the PPV2, the list isn't displayed properly:

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/113511191/234817145-15739f4c-9857-403f-9ad9-0e33c75dac65.png">

![image](https://user-images.githubusercontent.com/113511191/234819991-123ccd2e-f9c1-4855-b95f-dc7a5f514c7d.png)

### Expected behavior

The list should be displayed properly, like this:
![image](https://user-images.githubusercontent.com/113511191/234819356-9411c300-657c-40cf-9914-b518a98e0694.png)

### Steps to reproduce

1. Go to **Catalog > Products**
2. Click on **Add new product > Product with combinations**
3. Click on the **Combinations tab > Generate combinations**
4. Search for anything in the **"Search for attributes..."** box
5. Check out if the dropdown searchbox is displayed properly

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.1.7

**Comment by florine2623** [comment]
Hello @l-delin ,

I reproduced the issue with PrestaShop version `develop`, I'll add this to the backlog so it can be fixed.

<img width="1215" alt="Screenshot 2023-04-28 at 10 00 15" src="https://user-images.githubusercontent.com/16019289/235090588-3d10d6b0-6524-48ed-b1f7-d152745577bd.png">

On `8.0.x` and `8.1.x`, it worked as expected :
<img width="1217" alt="Screenshot 2023-04-28 at 10 01 43" src="https://user-images.githubusercontent.com/16019289/235090766-6a706f8e-13fe-4336-81c0-4dcc38e1adef.png">
<img width="1232" alt="Screenshot 2023-04-28 at 10 02 00" src="https://user-images.githubusercontent.com/16019289/235090773-69b4aad9-f5ab-4f76-b4fc-9237881c6f2d.png">

This is a regression.



Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
