### ISSUE TITLE
Upgrade using 1-click from minor release 8.0.3 - 8.0.4 scheme error in database relating to gdpr module

### ISSUE THREAD

**Issue by gpmcuk** [PrestaShop/PrestaShop#32377]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When upgrading the last portion of the update fails due to a scheme error in the gdpr table

### Expected behavior

complete the update

### Steps to reproduce

upgrade using 1 click updater

### PrestaShop version(s) where the bug happened

8.0.3

**Comment by gpmcuk** [comment]
This relates to the following code:

An exception occurred while executing 'ALTER TABLE ps_psgdpr_consent CHANGE
id_gdpr_consent id_gdpr_consent INT AUTO_INCREMENT NOT NULL, CHANGE id_mod
ule id_module INT NOT NULL, CHANGE active active TINYINT(1) NOT NULL, CHANG
E error error TINYINT(1) NOT NULL, CHANGE error_message error_message VARCH
AR(255) NOT NULL':
SQLSTATE[42000]: Syntax error or access violation: 1075 Incorrect table def
inition; there can be only one auto column and it must be defined as a key
In Exception.php line 18:
SQLSTATE[42000]: Syntax error or access violation: 1075 Incorrect table def
inition; there can be only one auto column and it must be defined as a key
In PDOConnection.php line 141:
SQLSTATE[42000]: Syntax error or access violation: 1075 Incorrect table def
inition; there can be only one auto column and it must be defined as a key
prestashop:schema:update-without-foreign [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--id_shop [ID_SHOP]] [--id_shop_group [ID_SHOP_GROUP]] [--]
-------------------------

Previously reported by a couple of users as a bug / discussion here; This discussion was converted from issue #32336 on April 26, 2023 14:51.

**Comment by florine2623** [comment]
Hello @gpmcuk ,

I'm upgrading from [8.0.3 ](https://build.prestashop-project.org/news/2023/prestashop-8-0-3-maintenance-release/)to [8.0.4](https://build.prestashop-project.org/news/2023/prestashop-8-0-4-maintenance-release/).

Using 1-Click Upgrade v4.15.0 and Official GDPR compliance v1.4.3.

The upgrade is successful :
<img width="1435" alt="Screenshot 2023-04-28 at 15 45 27" src="https://user-images.githubusercontent.com/16019289/235164918-2230507e-e897-44a5-ba94-07b04a7e51a0.png">

https://user-images.githubusercontent.com/16019289/235164906-ad4e1027-b1b0-4a9a-a6e7-11eb1d65ccf3.mov

**Comment by gpmcuk** [comment]
We have Official GDPR compliance v2

**Comment by florine2623** [comment]
The version v2.0.0 is a Pre-release. This means that you should no use it. It has some major bugs.
Please disable the module GDPR or use a previous version v.1.4.3 and try again your upgrade ^^

https://github.com/PrestaShop/psgdpr/releases

Waiting for your feedback.

**Comment by gpmcuk** [comment]
Completely uninstalling the module and reuploading the 1.4.3 worked

if this is the case why is the 2.0.0 version on the account? we fresh installed PS and it was automatically v2

**Comment by paulnoelcholot** [comment]
Hello  @gpmcuk;

We quickly noticed the problem and blocked access to the GDPR module version 2.0.0. You must have carried out the operation during this period of time. Our apologies for this problem.
