### ISSUE TITLE
Newsletter Spelling Problem

### ISSUE THREAD

**Issue by naeemaslam78** [PrestaShop/PrestaShop#32384]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi, Spelling problem in French, on cart, when you accept to subscribe the newsletter and when you accept data sharing law, i highlighted the text error in yellow, as you can see u have <br><em>, d&#039;, .</em> and other mistake, can you help me to fix.
![Capture d'écran 2023-04-28 213544](https://user-images.githubusercontent.com/76230701/235238009-a8ca6f3c-8dc0-4700-beb1-063e4e677556.png)

### Expected behavior

1.J'accepte les conditions générales et la politique de confidentialité

2. Recevoir notre newsletter. Vous pouvez vous désinscrire à tout moment. Vous trouverez pour cela nos informations de contact dans les conditions d'utilisation du site.

3.Message concernant la confidentialité des données clients. Conformément aux dispositions de la loi du n°78-17 du 6 janvier 1978, vous disposez d'un droit d'accès, de rectification et d'opposition sur les données nominatives vous concernant.

### Steps to reproduce

1. Go to https://c-pas-cher.com
2. just pick a product and add to your cart
3. click on order
4. on the https://c-pas-cher.com/panier?action=show click again on order ( commander in French )
5. you will see it just at the end of personnel details ( Informations personnelles ), just before 2 adress

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

7.4.33

### Your company or customer's name goes here (if applicable).

naeem aslam

**Comment by paulnoelcholot** [comment]
Hello @naeemaslam78,

This problem has already been reported and corrected on version 8.0.3. I invite you to update your store to apply the fix.

Thank you
