### ISSUE TITLE
When make an order, the check to accept the conditions is not displayed correctly

### ISSUE THREAD

**Issue by jlores** [PrestaShop/PrestaShop#32386]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

When a buyer is going to complete an order, the box to accept the general conditions is not displayed correctly. My test store has Spanish and English, in Spanish if displayed correctly. Tested on mobile and desktop, the same thing happens.

In English:

![checkout](https://user-images.githubusercontent.com/48771938/235294171-79ab80a0-a430-4d47-b764-aec500b28440.png)

In Spanish:

![Captura desde 2023-04-29 10-50-16](https://user-images.githubusercontent.com/48771938/235294184-a6c85e56-e4b8-42d7-b630-6a7501223f0f.png)

### Steps to reproduce

Add one item to cart. 
Proceed to checkout
The check "I accept the general ..." shows incorrectly

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

7.4 8.0 8.1

**Comment by paulnoelcholot** [comment]
Hello @jlores,

I tried to reproduce this issue but I can't as you can see : https://watch.screencastify.com/v/mStqwCYuJ59ftKQy1YTG

Did I miss something?

Thanks for your feedback

**Comment by jlores** [comment]
Hello,

I have Spanish and English on my shop. With default language shows OK. But when change to English shows like the capture.

The process is like your video

Best regards

**Comment by tesshsu** [comment]
Hi @jlores ,
Same here I had the same test result as @paulnoelcholot as I did install the Spanish version + English version
But I noticed one thing different is right tab part of your screenshot had paypal commercial text which was both written in Spanish

![1](https://user-images.githubusercontent.com/3927152/235656038-db74e521-fdf8-4d55-baa8-a35dd02e756e.png)

This might be an issue of your browser cache then loading CSS style error, you could either clean the cache in your browser or go to admin: Clear the cache: Go to Advanced Parameters -> Performance -> Clear Cache

Hope this could help, tks

**Comment by jlores** [comment]
Hello,

The paypal text in Spanish is prestashop checkout v8.3.1.0.

I clear cache on the shop and tried with Firefox, Chrome and Edge in other PC with the same result.


Best regards

**Comment by tesshsu** [comment]
Hi @jlores :
If the issue still persists, please try to deactivate the PayPal module and then back to the checkout page to see if the issue still occurred
![1](https://user-images.githubusercontent.com/3927152/235657600-89b85821-fb3b-4ade-b43c-3084a77add97.png)
If not then this could be a bug issue related to the PayPal module

**Comment by jlores** [comment]
Hello,

I don't have Paypal module. Only prestashop checkout.

I disabled ps_checkout and clear cache. same error.


Best regards

**Comment by hibatallahAouadni** [comment]
Hello @jlores 

Could you please provide more information or a screen record 🙏 Cause with the provided infos I didn't manage to reproduce the issue.
Waiting for your feedback.

Thanks!

**Comment by jlores** [comment]
Hello,

See the attached

[Grabación de pantalla desde 2023-05-09 12-03-18.webm](https://github.com/PrestaShop/PrestaShop/assets/48771938/6bcc0288-0c93-4fbb-a870-3dd7250651ec)

**Comment by florine2623** [comment]
Hello @jlores ,

Please make sure the message in the GDPR module is correct and that there's not an HTML tag that is not supposed to be there.

https://github.com/PrestaShop/PrestaShop/assets/16019289/53775103-aec3-478d-984a-dac70acfed57

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you
