### ISSUE TITLE
shopping cart v.2.0.3 by Prestashop NOT WORKING

### ISSUE THREAD

**Issue by nelawal** [PrestaShop/PrestaShop#32388]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, 
I have this big issue that my add to cart suddently stopped working. 
When we press add to cart, there is no response. The cart remains empty. 
This happens from google chrome , Firefox , internet and also from any mobile . 
I did not have this issue before . 
I have not installed  any new module. I have uninstalled and reinstalled the shopping cart module, and the problem still exists.
**The page gets updated, but nothing get added to the shopping cart, so the cart stays empty.**

**Steps to reproduce the behavior:**

Go to [https://benush.es/en/all_products/35-milk-chocolate-tablet-14](url)
Click on **Add to Cart**
See that **Cart icon stays empty**

**Additionnal information**
I use **prestashop 1.7.6.2**
**PHP version: 7.2.34**

Thanks in advanced

https://user-images.githubusercontent.com/62702976/235353403-904450b3-4024-4be4-b113-5b523bf9582b.mp4

### Expected behavior

The add to cart should work, and should add product to the cart.

### Steps to reproduce

**Steps to reproduce the behavior:**

Go to [https://benush.es/en/all_products/35-milk-chocolate-tablet-14](url)
Click on **Add to Cart**
See that **Cart icon stays empty**

### PrestaShop version(s) where the bug happened

1.7.6.2

### PHP version(s) where the bug happened

7.2.34

### If your bug is related to a module, specify its name and its version

shopping cart v.2.0.3 by Prestashop

### Your company or customer's name goes here (if applicable).

Benush Chocolatiere

**Comment by darkf3d3** [comment]
Have you tried switching to classic theme to see if the problem persists?

**Comment by nelawal** [comment]
> Have you tried switching to classic theme to see if the problem persists?

I am using the classic theme. Have just made some few changes to the design, and was working just fine the last 3 years, and suddenly it stopped working. I have no clue what has happened.

**Comment by joecoolio66** [comment]
There was an issue with one of the cart version for anything under 1.7.7 I believe.. be sure to upgrade to the latest version you can.

**Comment by nelawal** [comment]
> There was an issue with one of the cart version for anything under 1.7.7 I believe.. be sure to upgrade to the latest version you can.

I have already installed the latest version of shopping cart V2.0.7 
Any other idea?

**Comment by florine2623** [comment]
Hello @nelawal ,

I can't reproduce your issue with ps_shoppingcart v2.0.7.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by nelawal** [comment]
> 

Hi @florine2623 ,
I am using now Shopping cart
v2.0.4 - by PrestaShop

And the cart are not updating . 

I mean there is a bug in this version. also when I upgrade to 2.0.7 the problem still exists. 
I am using classic theme.

**Comment by darkf3d3** [comment]
@nelawal
Check if the shopping cart module it's hooked to displayHeader hook.

**Comment by nelawal** [comment]
> @nelawal Check if the shopping cart module it's hooked to displayHeader hook.

@darfk3d3 
I am not sure what to answer you but I attach a screen shot. Why? 
![image](https://user-images.githubusercontent.com/62702976/236033397-fb63bbf1-d91a-4281-a1c1-388a361d72c3.png)

**Comment by darkf3d3** [comment]
@nelawal 
From Design >> Positions, click on the light blue button on the top right of the page "Transplant a module".
Select "Shopping cart" module from the first list, then "displayHeader" on the second list.
Click Save.
