### ISSUE TITLE
When open search in submenu, the focus is not on search field

### ISSUE THREAD

**Issue by sunnyextreme** [PrestaShop/PrestaShop#32389]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When open search in submenu, the focus is not on search field. The field must be clicked to be able to write in it.

### Expected behavior

When such a menu is opened, the marker (focus) should be positioned on it,
![Clipboard01](https://user-images.githubusercontent.com/132200425/235362955-7fea804f-0352-45ca-ada1-c74954b0dd20.jpg)
![Clipboard02](https://user-images.githubusercontent.com/132200425/235362957-fab613a9-6622-461c-bd47-31a7141c1266.jpg)
 like BO modules >> Improve >> Design >> Positions >> Transplant a module

### Steps to reproduce

Go to BO modules >> Improve >> Design >> Positions and open "All modules"
or
BO >> Search (up, left global search), it sometime work on write a word and click enter, sometime not and must click on magnifying glass to start searching

### PrestaShop version(s) where the bug happened

8.0-8.03

### PHP version(s) where the bug happened

7.4

**Comment by paulnoelcholot** [comment]
Hello @sunnyextreme ,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

https://watch.screencastify.com/v/CXR2fRl9UnI0U25b51Ci
