### ISSUE TITLE
Order status not getting visible in Order Dashboard

### ISSUE THREAD

**Issue by amol-beast** [PrestaShop/PrestaShop#32380]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

List of orders should be visible with colour-coded status, but not getting visible
![error1](https://user-images.githubusercontent.com/3284767/235148060-989642e3-7ba6-4bd8-817e-4d33727aab25.png)

### Expected behavior

List of orders should be visible with colour-coded status, but not getting visible

### Steps to reproduce

Go to Orders-> Orders.

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.3 fpm

### If your bug is related to a module, specify its name and its version

No

### Your company or customer's name goes here (if applicable).

slnd.jps@gmail.com

**Comment by florine2623** [comment]
Hello @amol-beast ,

I can't reproduce your issue on 1.7.8.9, 8.0.x, 8.1.x and develop.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
