### ISSUE TITLE
I have this error, Prestashop v. 8.0.4, PHP 7.4, when I try to edit an product in backend I have "500 Internal Server Error"

### ISSUE THREAD

**Issue by sharkysign** [PrestaShop/PrestaShop#32397]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have this error, Prestashop v. 8.0.4, PHP 7.4, when I try to edit an product in backend I have "500 Internal Server Error"

![image](https://user-images.githubusercontent.com/36325399/235499170-b983ffd1-fc12-4ca4-b7cf-d42c04561222.png)
![image](https://user-images.githubusercontent.com/36325399/235499212-16b10aa2-74d9-42fb-9553-1bd5a9b83204.png)

### Expected behavior

I can't edit any of my products.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/36325399/235499499-db28cdf0-4eca-440a-a82d-6cb5edef988f.png)

### PrestaShop version(s) where the bug happened

8.0.3 and 8.0.4

### PHP version(s) where the bug happened

PHP 7.4

**Comment by tesshsu** [comment]
Hi @sharkysign 
The error message you are seeing is indicating that there is a TypeError in the ProductDetails class of the src/Core/Domain/Product/QueryResult/ProductDetails.php file. This means that there is an issue with the type of data being passed to a function or method in the class.

You have to go to your BO in the product detail tab to check any value you entered is not a correct string
![1](https://user-images.githubusercontent.com/3927152/235648470-e52c32be-9b5f-4a71-bf3b-c9a327a38465.png)

And if your input field entered had been the correct string, then Clear the cache: Go to Advanced Parameters -> Performance -> Clear Cache

Hope this could be work for you

**Comment by sharkysign** [comment]
> Hi @sharkysign The error message you are seeing is indicating that there is a TypeError in the ProductDetails class of the src/Core/Domain/Product/QueryResult/ProductDetails.php file. This means that there is an issue with the type of data being passed to a function or method in the class.
> 
> You have to go to your BO in the product detail tab to check any value you entered is not a correct string ![1](https://user-images.githubusercontent.com/3927152/235648470-e52c32be-9b5f-4a71-bf3b-c9a327a38465.png)
> 
> And if your input field entered had been the correct string, then Clear the cache: Go to Advanced Parameters -> Performance -> Clear Cache
> 
> Hope this could be work for you

Thank you @tesshsu for your replay, but I can't access the product detail tab that is the main problem.

**Comment by sharkysign** [comment]
Here is the solution:
`declare(strict_types=1);

namespace PrestaShop\PrestaShop\Core\Domain\Product\QueryResult;

/**
 * Holds product details
 */
class ProductDetails
{
    /**
     * @var string|null
     */
    private $isbn;

    /**
     * @var string|null
     */
    private $upc;

    /**
     * @var string|null
     */
    private $ean13;

    /**
     * @var string|null
     */
    private $mpn;

    /**
     * @var string|null
     */
    private $reference;

    /**
     * @param string|null $isbn
     * @param string|null $upc
     * @param string|null $ean13
     * @param string|null $mpn
     * @param string|null $reference
     */
    public function __construct(
        ?string $isbn = null,
        ?string $upc = null,
        ?string $ean13 = null,
        ?string $mpn = null,
        ?string $reference = null
    ) {
        $this->isbn = $isbn;
        $this->upc = $upc;
        $this->ean13 = $ean13;
        $this->mpn = $mpn;
        $this->reference = $reference;
    }

    /**
     * @return string|null
     */
    public function getIsbn(): ?string
    {
        return $this->isbn;
    }

    /**
     * @return string|null
     */
    public function getUpc(): ?string
    {
        return $this->upc;
    }

    /**
     * @return string|null
     */
    public function getEan13(): ?string
    {
        return $this->ean13;
    }

    /**
     * @return string|null
     */
    public function getMpn(): ?string
    {
        return $this->mpn;
    }

    /**
     * @return string|null
     */
    public function getReference(): ?string
    {
        return $this->reference;
    }
}
`

**Comment by tesshsu** [comment]
Hi @sharkysign 
The solution you mentioned should not be the right solution, instead, you might break some functional calls if certain module import ProductDetails class

To remove the "Product details" tab from the product edit page in Prestashop back office, you can use the following steps:

1. Navigate to the "Catalog" menu and select "Products."
2. Click on the product that you want to edit.
3. Scroll down to the "Preferences" tab and click on it.
4. In the "Product details" section, uncheck the "Enable product details" checkbox.
5. Click on the "Save" button to save your changes.

This should remove the "Product details" tab from the product edit page. If you want to add it back later, simply follow the same steps and check the "Enable product details" checkbox.

Hope this could help tks
