### ISSUE TITLE
Upgrade from 8.0.3 to 8.0.4 results in error while trying to run database update

### ISSUE THREAD

**Issue by Jonteep** [PrestaShop/PrestaShop#32399]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,

I have been trying to update from Prestashop 8.0.3 to 8.0.4 with the Autoupgrade Module of the latest version 4.1.5.

When the files have been updated and database update begins, it shuts down with error in a separate text box, red text beginning with "INTERNAL ..". It mentions "autoupgrade" several times in the message.

Unfortunately I didn't save the message or any screenshot.

I am running PHP 8.1.18 and mariaDB 10.5.

Best regards and thanks in advance,
Jonte

### Expected behavior

Successfull update from 8.0.3 to 8.0.4 =)

### Steps to reproduce

Go to autoupgrade and perform the update from 8.0.3 to 8.0.4, all with the default settings.

### PrestaShop version(s) where the bug happened

8.0.3 to 8.0.4

### PHP version(s) where the bug happened

8.1.18

### If your bug is related to a module, specify its name and its version

Autoupgrade, maybe?

**Comment by paulnoelcholot** [comment]
Hello @Jonteep,

I tried to reproduce your issue but I can't as you can see : https://watch.screencastify.com/v/JJdauZK54No8BcQDydsO

Did I miss something?

**Comment by Jonteep** [comment]
Hi, this happens on all my sites.

Some other users seems to have the same problem, only the files could be updated, not the database:

https://build.prestashop-project.org/news/2023/prestashop-8-0-4-maintenance-release/

..if looking into the comments section.

Best regards,

**Comment by AureRita** [comment]
Hi @Jonteep 

Can you tell us wich OS did you use ? 

Waiting for your feedback

**Comment by matks** [comment]
Might be related to https://github.com/PrestaShop/PrestaShop/discussions/32348

**Comment by Jonteep** [comment]
> Hi @Jonteep
> 
> Can you tell us wich OS did you use ?
> 
> Waiting for your feedback

Hi, I am using OS Windows 10. Best regards,

**Comment by Jonteep** [comment]
This is the error I get when I try to update from 8.0.3 to 8.0.4 (PHP 8.1.18 / mariaDB 10.5.17):

[SKIP] directory "/app/cache/" does not exist and cannot be emptied.
[CLEANING CACHE] File prod removed

And I get the following error:

[INTERNAL] /data/f/1/f115e4c4-34604-42a7-bd5grht/XXXXXXXXXX/web/config/bootstrap.php line 87 - Error: Failed opening required '/data/f/1/f115e4c4-34604-42a7-bd5grht/XXXXXXXXXX/web/var/cache/prod/appParameters.php' (include_path='/data/f/1/f115e4c4-34604-42a7-bd5grht/XXXXXXXXXX/web/vendor/pear/pear_exception:/data/f/1/f115e4c4-34604-42a7-bd5grht/XXXXXXXXXX/web/vendor/pear/console_getopt:/data/f/1/f115e4c4-34604-42a7-bd5grht/XXXXXXXXXX/web/vendor/pear/pear-core-minimal/src:/data/f/1/f115e4c4-34604-42a7-bd5grht/XXXXXXXXXX/web/vendor/pear/archive_tar:.:/usr/php81/lib/php') #0 /data/f/1/f115e4c4-34604-42a7-bd5grht/XXXXXXXXXX/web/config/config.inc.php(57): require_once() #1 /data/f/1/f115e4c4-34604-42a7-bd5grht/XXXXXXXXXX/web/modules/autoupgrade/classes/UpgradeContainer.php(576): require_once('/data/f/1/f149e...') #2 /data/f/1/f115e4c4-34604-42a7-bd5grht/XXXXXXXXXX/web/modules/autoupgrade/classes/TaskRunner/AbstractTask.php(120): PrestaShop\Module\AutoUpgrade\UpgradeContainer->initPrestaShopCore() #3 /data/f/1/f115e4c4-34604-42a7-bd5grht/XXXXXXXXXX/web/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(81): PrestaShop\Module\AutoUpgrade\TaskRunner\AbstractTask->init() #4 /data/f/1/f115e4c4-34604-42a7-bd5grht/XXXXXXXXXX/web/ADMIN/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->init() #5 {main}

Notice, some URL's etc. replaced! But the message is that of above.

No database update or modules update etc.

Best regards,

**Comment by Jonteep** [comment]
Does anyone know what's wrong? I can't update these sites at all.

**Comment by Jonteep** [comment]
So I tried downgrading these three sites to PHP 8 (fron 8.1) and it still doesn't work, same error as above.

The database type is set to mariaDB 10.5, could that cause any issue?

**Comment by Jonteep** [comment]
So I found the problem, I turned OFF opcache on my hosting admin and it helped.

But isn't Prestashop supposed to be compatible with OPCACHE?

Best regards,

**Comment by paulnoelcholot** [comment]
Hello @Jonteep,

Hello,

Indeed it is a valid bug if there is a compatibility problem between PrestaShop and OPCACHE. I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by KiLiMaToS** [comment]
I believe I have the same issue, but I'm not very sure about it.
If opening a new issue is necessary for my problem, please let me know, and I will do it.
When I try to upgrade from 8.03 to 8.0.4, it seems to have a problem with the database upgrade. I am attaching a screenshot of my error.
Fortunately, the rollback worked perfectly, and I have reverted back to version 8.0.3.
Thank you
![Screenshot 2023-06-06 162135](https://github.com/PrestaShop/PrestaShop/assets/64029935/8e038113-1e3f-45dd-88f3-dfdad31b341a)

**Comment by MatShir** [comment]
I think your bug is strongly related to https://github.com/PrestaShop/PrestaShop/discussions/32348 which should be fixed now. I will close the issue. BUT if you still have the pb again later on, don't hesitate to open the issue again. Thanks :)

**Comment by Jonteep** [comment]
Hi, the problem was with OPCACHE regarding this issue, not the GDPR-module.

When I turned OFF OPCACHE with my hosting, the update was successfull.

I think this thread should be opened again, since it's a different issue.

Best regards,

**Comment by MatShir** [comment]
You are right ! I mixed up the comment @KiLiMaToS your screenshot is related to the module gpdr that is fixed now.

**Comment by MatShir** [comment]
What OPCache config do you have?

**Comment by MatShir** [comment]
OPcache can interfere in the upgrade. I'm wondering If we should add warning or add in the checklist to disable OPCache 🤔

**Comment by KiLiMaToS** [comment]
> I think your bug is strongly related to #32348 which should be fixed now. I will close the issue. BUT if you still have the pb again later on, don't hesitate to open the issue again. Thanks :)

I'm sorry, I didn't understand if you were referring to me. Was the problem resolved with the GDPR form related to me? Thank you.

**Comment by MatShir** [comment]
@KiLiMaToS It should be solved for you

**Comment by aniszr** [comment]
Hello @Jonteep  ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
