### ISSUE TITLE
Upgrade from version 1.7.6.7 to 1.7.8.9 fails: An exception occurred while establishing a connection to figure out your platform version.

### ISSUE THREAD

**Issue by Mecanik** [PrestaShop/PrestaShop#32396]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I tried for several hours by backing up and restoring after the below failure:

`[INTERNAL] /home/tfehcom/public_html/vendor/doctrine/doctrine-bundle/ConnectionFactory.php line 79 - Doctrine\DBAL\DBALException: An exception occured while establishing a connection to figure out your platform version. You can circumvent this by setting a 'server_version' configuration value For further information have a look at: https://github.com/doctrine/DoctrineBundle/issues/673 #0 /home/tfehcom/public_html/vendor/doctrine/doctrine-bundle/ConnectionFactory.php(50): Doctrine\Bundle\DoctrineBundle\ConnectionFactory->getDatabasePlatform(Object(Doctrine\DBAL\Connection)) #1 /home/tfehcom/public_html/var/cache/prod/ContainerFg8mr6q/appProdProjectContainer.php(2920): Doctrine\Bundle\DoctrineBundle\ConnectionFactory->createConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Symfony\Bridge\Doctrine\ContainerAwareEventManager), Array) #2 /home/tfehcom/public_html/var/cache/prod/ContainerFg8mr6q/appProdProjectContainer.php(2951): ContainerFg8mr6q\appProdProjectContainer->getDoctrine_Dbal_DefaultConnectionService() #3 /home/tfehcom/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(306): ContainerFg8mr6q\appProdProjectContainer->getDoctrine_Orm_DefaultEntityManagerService() #4 /home/tfehcom/public_html/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ManagerRegistry.php(63): Symfony\Component\DependencyInjection\Container->get('doctrine.orm.de...') #5 /home/tfehcom/public_html/vendor/doctrine/persistence/lib/Doctrine/Persistence/AbstractManagerRegistry.php(204): Symfony\Bridge\Doctrine\ManagerRegistry->getService('doctrine.orm.de...') #6 /home/tfehcom/public_html/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/CacheWarmer/ProxyCacheWarmer.php(53): Doctrine\Persistence\AbstractManagerRegistry->getManagers() #7 /home/tfehcom/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/CacheWarmer/CacheWarmerAggregate.php(52): Symfony\Bridge\Doctrine\CacheWarmer\ProxyCacheWarmer->warmUp('/home/tfehcom/p...') #8 /home/tfehcom/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(686): Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp('/home/tfehcom/p...') #9 /home/tfehcom/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() #10 /home/tfehcom/public_html/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(76): Symfony\Component\HttpKernel\Kernel->boot() #11 /home/tfehcom/public_html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(56): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #12 /home/tfehcom/public_html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(87): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() #13 /home/tfehcom/public_html/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(42): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #14 /home/tfehcom/public_html/admin055zrsmlu/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #15 {main}`

The server_version of course is defined, I even tried to set different versions thinking that Doctrine might be too old. The MySQL version is 8.0.33 on the server.

### Expected behavior

Upgrade ok?

### Steps to reproduce

Try to upgrade between the mentioned versions.

### PrestaShop version(s) where the bug happened

1.7.6.7

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Hello @Mecanik 

You need to downgrade your PHP version to 7.2 before upgrading cause the 1.7.6.7 is not compatible with PHP 7.3 (see our system requirements), then try to upgarde. Could you please provide the upgarde module version 🙏 
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Mecanik 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by musicpanda** [comment]
This is a copy of https://github.com/PrestaShop/PrestaShop/issues/33524
