### ISSUE TITLE
1.7.8.9 upgrade erase the "previsions" module datas (dashgoals)

### ISSUE THREAD

**Issue by elmanu13** [PrestaShop/PrestaShop#32405]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the dashboard I had the "previsions" module working ok with numbers and graph for my 2023 year.
After the upgrade, no more numbers, all the fields are back to zero.

### Expected behavior

the fields should have been saved

### Steps to reproduce

1) fill all the fields of dashgoals module to have beautiful graphs and goals for the year, under version 1.7.8.8
2) upgrade to 1.7.8.9 with 1clic module
3) go to dashboard and cry because all the work have to be done once again.

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

dashgoals 2.0.4

**Comment by elmanu13** [comment]
To be complete : the module doesn't work any more, like in a previous version
Even if you fill all the fields the graphs stays at zero.
I have to modify the dashgoals.php file to replace all the ConfigurationKPI by Configuration to make it work.
Why did you upgraded this module without correcting this old bug ?

**Comment by hibatallahAouadni** [comment]
Hello @elmanu13 

This issue has been fixed with the next major version 8.1.0 (see this Pull Request #29741).
Closing the issue as a duplicate of #9662.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #9662
