### ISSUE TITLE
Prestashop 8.0.3 fresh install - Error 500 when trying to clear cache in Back Office

### ISSUE THREAD

**Issue by Jonteep** [PrestaShop/PrestaShop#32400]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Clearing cache in a fresh Prestashop 8.0.3 install generates error 500.

The issue is noticeable with all my sites, now running Prestashop 8.0.3 with PHP 8.1.18 and 10.5.17-MariaDB.

Whenever I log into admin, go to performance and click "Clear Cache", I end up with "Oops, an error occured - Error 500" etc. if I then press F5 to refresh the browser, I can see a successfull message that the cache has been cleared. And if I once again click "Clear Cache" (the button) right afterwards, it works. But if I browse the admin area for some time and then go back to performance > clear cache, I get the error 500 and have to repeat F5 and so on.

Best regards,

### Expected behavior

Clear the cache via BO without any issues. =)

### Steps to reproduce

1. New/fresh install of Prestashop 8.0.3.
2. Put the site in maintenance mode.
3. Upgraded the modules i BO (got notification that three modules needed update).
4. Go to performance > clear cache.
5. Error 500 page.
6. Updated the browser / F5 and the cache cleared.
7. Tried again by clearing the cache via the button in performance > cache and it worked.
8. Tried once again and error 500 occured.
9. Updated the browser (while error 500) and I get a message the cache has cleared.
10. I have tried to delete the var/cache folder so it re-generates, but the issue is still there, I can only clear the cache 50/50 without error 500.

### PrestaShop version(s) where the bug happened

8.0.3

### PHP version(s) where the bug happened

Apache 2.4 - PHP 8.1.18 - mariaDB 10.5

### If your bug is related to a module, specify its name and its version

No module

**Comment by tesshsu** [comment]
Hi @Jonteep 
After testing by my side follow your step ( notice that I had Prestashop 8.1.0 and PHP  8.1.18, limited memory: 256M, maxima execution time : 30) , I had no 500 error

![1](https://user-images.githubusercontent.com/3927152/235665616-91f93493-8320-43c5-9330-96c8ca99b1e0.png)

Since 500 error is a server-side error, which means that there may be a problem with the server configuration. Check your server logs for any error messages that may provide insight into the cause of the error in Var/logs

Increase the PHP memory limit: If the server logs do not provide any useful information, you can try increasing the PHP memory limit in your server's php.ini file. Prestashop requires a minimum of 256MB of memory to run, so make sure that your server meets this requirement.

Update your Prestashop installation: Make sure that your installation of Prestashop is up to date with the latest version. There may be bug fixes or performance improvements that could resolve the issue

Hope this could help, tks

**Comment by Jonteep** [comment]
So I finally got the debug message, sorry about the late reply.

Here it is:

Warning: require_once(/data/f/1/f145ghh095-3352-46j7-bg45-9292f0ho48d/XXXXXXXXXXX/web/var/cache/dev/namespaced_class_stub.php): Failed to open stream: No such file or directory


ErrorException

in classes/PrestaShopAutoload.php (line 160)
require_once()

in classes/PrestaShopAutoload.php (line 160)
MultistoreFeature->isUsed()

in src/PrestaShopBundle/Form/Admin/Extension/ModifyAllShopsExtension.php (line 99)

in vendor/symfony/symfony/src/Symfony/Component/Form/ResolvedFormType.php -> buildForm (line 134)

in vendor/symfony/symfony/src/Symfony/Component/Form/Extension/DataCollector/Proxy/ResolvedTypeDataCollectorProxy.php -> buildForm (line 95)

in vendor/symfony/symfony/src/Symfony/Component/Form/ResolvedFormType.php -> buildForm (line 128)

in vendor/symfony/symfony/src/Symfony/Component/Form/Extension/DataCollector/Proxy/ResolvedTypeDataCollectorProxy.php -> buildForm (line 95)

in vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php -> buildForm (line 82)
FormFactory->createNamedBuilder('smarty', object(ResolvedTypeDataCollectorProxy))

in src/Core/Form/Handler.php (line 103)
Handler->getForm()

in src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/PerformanceController.php (line 64)

in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php -> indexAction (line 169)

in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php -> handleRaw (line 81)

in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php -> handle (line 201)
Kernel->handle(object(Request), 1, false)

in adminXXXXXXXX/index.php (line 81)

I cannot clear the cache without getting error 500. If I update with F5 (the browser), the cache clears and I can clear it via the button one more time without any error 500. If I surf around the back office and try to clear it again, same thing happens.

Best regards,

**Comment by tesshsu** [comment]
Hi @Jonteep 

This error message indicates that the file "/data/f/1/f145ghh095-3352-46j7-bg45-9292f0ho48d/XXXXXXXXXXX/web/var/cache/dev/namespaced_class_stub.php" is missing. This file is required by PrestaShop to function properly, and its absence can cause errors like the one you're seeing.

To resolve this issue, you can try deleting the contents of the "var/cache" directory manually. This will force PrestaShop to rebuild its cache files from scratch. 

Hopes this could help, tks

**Comment by Jonteep** [comment]
Hi, thanks for your reply.

The crazy thing is that I have tried that several times, and the cache directory rebuilds.

The same with three sites, all 8.0.3 and PHP 8.1.18.

I can press F5 while I get error 500 and then I receive a gree box that says the cache cleared successfully. If I push the blue "Clear Cache" again right afterwards, I get no error 500. But if I continue to browse the Back Office for some while, and then get back to Performance > Clear Cache, I get error 500.

Best regards,

**Comment by paulnoelcholot** [comment]
Hello,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Comment by Jonteep** [comment]
So I found the problem, I turned OFF opcache on my hosting admin and it helped.

But isn't Prestashop supposed to be compatible with OPCACHE?

Best regards,

**Comment by Madmin27** [comment]
As someone who has the same problem, I wanted to note that we have Opcache in common.
