### ISSUE TITLE
Multiple image formats : The WebP original file is converted to JPEG

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#32408]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I upload a category cover image in WebP Format, it's converted to JPEG.

### Expected behavior

When I upload a category cover image in WebP Format, it remains in WebP.

### JPEG
1. Enable Multiple image formats on the "New & Experimental Features" page
2. Enable WebP in Image Format page
3. Create a category with a JPEG file for cover
4. The `img/c/{idCategory}/{idCategory}.jpg` exist => It's a JPEG file.

### PNG
1. Enable Multiple image formats on the "New & Experimental Features" page
2. Enable WebP in Image Format page
3. Create a category with a PNG file for cover
4. The `img/c/{idCategory}/{idCategory}.jpg` exist => It's a PNG file.

### WebP
1. Enable Multiple image formats on the "New & Experimental Features" page
2. Enable WebP in Image Format page
3. Create a category with a WebP file for cover
4. The `img/c/{idCategory}/{idCategory}.jpg` exist => It's a JPEG file. **:warning: ERROR :warning:**

#### Acceptance Test
Unskip this comment : https://github.com/PrestaShop/PrestaShop/blob/d672ad4ccc467722d13746e25fffc95a86e5e3b3/tests/UI/campaigns/functional/BO/08_design/06_imageSettings/14_checkCategoryImageFormat.ts#L153-L155

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

7.3

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

**Comment by hibatallahAouadni** [comment]
Hello @Progi1984 

I reproduce the issue with PS810 and PS800 even without enabling the option Enable Multiple image formats on the "New & Experimental Features" page, see the attached screen record below:

[issue_32408.webm](https://user-images.githubusercontent.com/23308427/237003325-c43d09b8-24d8-49c4-8244-ce69bc4703ff.webm)

Ping @PrestaShop/product-team could you please provide specs for this behavior 🙏 

Thanks!
