### ISSUE TITLE
The MPN column is missing in products' import file

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#32413]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The MPN column is missing, so the file could not be used as wanted without changing the fields related to each column.

### Steps to reproduce

1. Go to Import page
2. Download the example about products
3. Use it inside the import
4. See that after EAN/UPC, there is a no match.

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

7.4.33

### Your company or customer's name goes here (if applicable).

@Wepika

**Comment by florine2623** [comment]
Hello @PrestaEdit ,

I reproduced the issue with PrestaShop version 1.7.8.9, 8.0.4, it is not a regression. I'll add this to the backlog so it can be fixed.

Thank you for the PR. Once the review is done, it will be tested ^^
