### ISSUE TITLE
Product importation overwrite the default category

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#32412]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Once you have a product with more than one categories and having a default one, you could be affected with an import of it even if you don't update the categories.

### Expected behavior

Let the default category as previously setted.

### Steps to reproduce

1. Use this file to import a product with multiple categories and enable the use of "Force ID" option.
[20230502170440-products_import.csv](https://github.com/PrestaShop/PrestaShop/files/11374846/20230502170440-products_import.csv)
2. Set the default one to "Ipods" on the newest product (ID = 42)
3. Re-import the same file, with the sames options. You can remove the categories column or ignore it into the import configuration.
4. See that the default category is now the first of the listing (Accessories, instead of Ipods).

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

7.4.33

### Your company or customer's name goes here (if applicable).

@Wepika

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

I think your issue is similar to this one #12092 could you please check it 🙏 
And did you encounter this issue with older version? Please check and feedback.

Thanks!

**Comment by PrestaEdit** [comment]
Hi @hibatallahAouadni,

It's seems not related as it's doesn't mention the change of default category there.

I doesn't test this in older version yet.

**Comment by AureRita** [comment]
Hi @PrestaEdit 

Thank you for your report, I tried to reproduce you issue as you can see : 

[Untitled_ May 11, 2023 3_58 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/3fcc2860-a228-4555-a735-032243c852ab)

But I currently can't reproduce it, did I miss something ? 

Waiting for your feedback

**Comment by djoelleuch** [comment]
Hello @PrestaEdit ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Comment by ShaiMagal** [comment]
@PrestaEdit 
Try edit this file:
`/controllers/admin/AdminImportController.php`
Comment this section for test:
```
/*
if ($product->category && is_array($product->category)) {
continue;
}
*/
```

Worked now?
Is default category still same or changed again with this edit?
