### ISSUE TITLE
Product Save function not working

### ISSUE THREAD

**Issue by nad-maahirsystems** [PrestaShop/PrestaShop#32429]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,
I'm trying to create a product, but on saving product I'm unable to save it, showing error message 'Unable to update settings.

Do you have any idea how to fix it.
It would be great help.

Thanks,
Nad
'

### Steps to reproduce

Created product
saved it, but not working

### PrestaShop version(s) where the bug happened

1.7.8.3

**Comment by hibatallahAouadni** [comment]
Hello @nad-maahirsystems 

Could you please provide screenshot of your product page, cause it seems that you mistype some field.
Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @nad-maahirsystems 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
