### ISSUE TITLE
Useless redirection in the Customer Service page

### ISSUE THREAD

**Issue by ElodieOS** [PrestaShop/PrestaShop#32423]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you click in the "Pending Discussion Threads", your page reload.  

![image](https://user-images.githubusercontent.com/113457393/235887699-ba24ed56-32ed-4f1d-8045-5e6b5afc9c72.png)

### Expected behavior

We can delete this comportement because it's useless 

### Steps to reproduce

Customer service > Customer service > Pending discussion threads

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by mflasquin** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/32465
