### ISSUE TITLE
Two Cart rule with "exclude discounted products" do not work as expected

### ISSUE THREAD

**Issue by dburgon** [PrestaShop/PrestaShop#32427]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Bug report : 

After adding two products to the cart, I have two codes that exclude promotional products. The total of the discounts is good but not the total of the cart rules. 

![image](https://user-images.githubusercontent.com/132479487/235967066-ac50ea71-4575-4a97-afbc-1b35b702b6e8.png)

### Expected behavior

The expected behavior is that of the image: 

- a correct total
- a correct reduced total
- an incorrect cart rule

### Steps to reproduce

1. Create 2 cart rules with "exclude discounted products"
2. Add one product without discount 
3. Add another product with discount 
4. Add two cart rules in cart

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @dburgon ,

Is your issue similar to https://github.com/PrestaShop/PrestaShop/issues/11506 ?

Waiting for your feedback

**Comment by dburgon** [comment]
Hello @florine2623, 

Thanks for your reply. 

I'm not sure, I don't have gift cart rule. I have two cart rules with percent and with "exclude discounted products" option. 

Waiting for your feedback.

**Comment by hibatallahAouadni** [comment]
Hello @dburgon 

Thanks for your feedback.
Well, it's the same scope of your issue applying two cart rule cause the problem.
Closing the issue as it is already in our debug backlog. This issue is a duplicate of #11506. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #11506
