### ISSUE TITLE
We have a misuse of the help text and tooltip in the delivery slips page.

### ISSUE THREAD

**Issue by ElodieOS** [PrestaShop/PrestaShop#32422]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the delivery slip options, we use help text while tooltip are more adapted. 

As a reminder, the rule is: 
- if it's about information to understand and fill the field, we use a tooltip
- if it's an information describing the input format in a field or an indication on the nature of the expected information, a help text is used

![image](https://user-images.githubusercontent.com/113457393/235885471-75a93ba1-dd48-466c-a5e3-ff4fce4bcf83.png)

### Expected behavior

- Delivery prefix : remove the help text which doesn't bring much more information or review the wording to add a more useful tooltip
- Delivery number : use the tooltip
- Enable product image : use the tooltip and I would remove the Enable label which can be confusing

![image](https://user-images.githubusercontent.com/113457393/235885827-c0b29c3d-036d-4f33-9595-51c06227473f.png)

### Steps to reproduce

Orders > Delivery Slips > Delivery slip options 

### PrestaShop version(s) where the bug happened

8.0.0

**Comment by matks** [comment]
Fixed by @nicosomb with https://github.com/PrestaShop/PrestaShop/pull/33880
