### ISSUE TITLE
PrestaShopException right after clean installation with cli

### ISSUE THREAD

**Issue by Zudjo** [PrestaShop/PrestaShop#32426]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

## Environment

- Windows 11 x64
- node 16.0.0
- npm 7.10.0
- ![image](https://user-images.githubusercontent.com/113335680/235920850-06c7719d-3a5b-4d40-8553-ce8e8107f896.png)

## Error

```
There is no image type defined for "products".
at line 364 in file src/Adapter/Image/ImageRetriever.php
```

![image](https://user-images.githubusercontent.com/113335680/235917402-f9ec61b9-da9c-40aa-8135-cfd133453cff.png)

### Expected behavior

No errors on clean installation.

### Steps to reproduce

- I cloned the PrestaShop repository with git, in `C:\xampp\htdocs`
- Moved out all the files from the auto generated `PrestaShop` folder, to simulate a real host
- Now `C:\xampp\htdocs` is the root folder of the project
- Ran `composer install`
- Compiled manually all 4 folders indicated in the doc [here](https://devdocs.prestashop-project.org/8/development/compile-assets/#compiling-assets)
- Ran `php .\install-dev\index_cli.php --domain=localhost --db_server=localhost --db_name=banane --db_user=root --db_password=  --prefix=  --email=gi*****@ec*********.it --password=A2************`

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.0.28

**Comment by tesshsu** [comment]
Hi @Zudjo 
I got the same error once I re-install version 8
You could try to fix if you have access phpMyAdmin and go to {PREFIX}_image_type table 

```
INSERT INTO `{PREFIX}_image_type` (`id_image_type`, `name`, `width`, `height`, `products`, `categories`, `manufacturers`, `suppliers`, `stores`)
VALUES
	(10, 'large_banner', 960, 400, 0, 1, 0, 0, 0),
	(9, 'product_listing', 220, 220, 1, 1, 1, 1, 0),
	(8, 'category_default', 960, 350, 0, 1, 0, 0, 0),
	(7, 'home_default', 250, 250, 1, 0, 0, 0, 0),
	(6, 'large_default', 500, 500, 1, 0, 0, 0, 0),
	(5, 'medium_default', 300, 300, 1, 1, 1, 1, 0),
	(4, 'small_default', 125, 125, 1, 1, 1, 1, 0),
	(3, 'cart_default', 80, 80, 1, 0, 0, 0, 0);

```
You could find out from this[ issue 17539](https://github.com/PrestaShop/PrestaShop/issues/17539) 
Hope this could help

**Comment by matks** [comment]
Hi @Zudjo you forgot to build assets. Use `make assets` see https://devdocs.prestashop-project.org/8/basics/installation/localhost/#download-dependencies
