### ISSUE TITLE
Setting minimum quantity for sale to 0 breaks availability display logic

### ISSUE THREAD

**Issue by 01Kuzma** [PrestaShop/PrestaShop#32437]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I sell only one unique product in my PrestaShop store (upgraded to 8.03), and I want to maintain its SEO value even when it's sold out. To do so, I'm displaying a "sold" label on the main catalog page, but when I open the sold product the label is changed to "Last item". And this is incorrect.

The problem is that the {$product.availability|print_r} value currently shows "last_remaining_items1,"
It's misleading for customers who think the product is still available, while it's sold out.
![image](https://user-images.githubusercontent.com/569504/236125170-3f3f90cc-6158-440d-93eb-729f716810b8.png)

I've created a [dedicated forum thread](https://www.prestashop.com/forums/topic/1076094-displaying-last-item-instead-of-sold-out-on-a-product-page/) for this

### Steps to reproduce

1. Create a new product.
2. Set quantity to zero.
3. Set minimum quantity for sale to zero.
4. Deny orders when not in stock.
5. See FO product page in classic - availability is "Last items available".
6. When you set minimum quantity for sale to 1, it works correctly and shows "Sold out".

### PrestaShop version(s) where the bug happened

8.0, 8.1.x

### PHP version(s) where the bug happened

7.4, 8.0

**Comment by Hlavtox** [comment]
@01Kuzma Please don't open more threads about this. 

But, I have investigated this and the cause is actually setting "Minimum quantity for sale" to zero. 🤔 Set it to 1 and it will work. We will see how we can fix it.

**Comment by 01Kuzma** [comment]
@Hlavtox , I thought, that you have skipped the old thread.
OK, will wait for the fix.
Thank you!

**Comment by hibatallahAouadni** [comment]
Hello @01Kuzma 

Thanks for reporting the issue, it's a regression on 8.0.0!
Thanks @Hlavtox for your investigation 🚀 I will add this to the Backlog to be fixed.

Thanks!
