### ISSUE TITLE
HTTP 500 error - unsure why

### ISSUE THREAD

**Issue by gpmcuk** [PrestaShop/PrestaShop#32436]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

For some reason my site has gone down with a 500 error - it was working absolutely fine and we have not upgraded or changed anything. next minute it went down

### Steps to reproduce

Error as follows:

Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ps_translation' doesn't exist in /home/gpmc/public_html/classes/db/DbPDO.php:149 

any help on this would be appreciated

### PrestaShop version(s) where the bug happened

8.0.3

### PHP version(s) where the bug happened

8.0

**Comment by gpmcuk** [comment]
further to this - we even rolled back 24hrs using jetbackup to a point we know it was 100% working and still the same error

**Comment by kpodemski** [comment]
Hello @gpmcuk 

It really looks like a problem with your environment. Either the database table is missing, or it is corrupted. I suggest checking in the phpMyAdmin, Adminer, or something whether the table exists or not. You can also consult with your hosting support.
