### ISSUE TITLE
Error during install - Country pt-PT

### ISSUE THREAD

**Issue by Borgas** [PrestaShop/PrestaShop#32435]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On live server, fresh install, all config ok. 

Turns error during tables creating, but the tables are there

Tried different languages, without sucess

<img width="762" alt="Captura de ecrã 2023-05-04 003243" src="https://user-images.githubusercontent.com/54105234/236073900-ab3e0582-7622-4018-9b8d-aa33d1f9d7c2.png">
<img width="1021" alt="Captura de ecrã 2023-05-04 003307" src="https://user-images.githubusercontent.com/54105234/236073902-23bea2e6-dabb-412a-b6ef-dae98f856224.png">
<img width="799" alt="Captura de ecrã 2023-05-04 003421" src="https://user-images.githubusercontent.com/54105234/236073905-1769edf8-55ac-42d9-9e26-9561093a90de.png">

Log record in server

**PHP Warning:  Invalid argument supplied for foreach() in .../classes/shop/Shop.php on line 360**

### Steps to reproduce

Downloaded from prestashop website (commercial version)
Extract and zip it again
Upload to server
Extract and run install :)

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @Borgas 

Try to install the PrestaShop from Github, here's the link: https://github.com/PrestaShop/PrestaShop/releases/tag/8.0.4
And check your server configuration, cause it seems you have some issue on it 😉 
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @Borgas 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
