### ISSUE TITLE
Brands page - HTTP 500 Internal Server Error (only in the Ukrainian language)

### ISSUE THREAD

**Issue by Kos-tash** [PrestaShop/PrestaShop#32441]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

![image](https://user-images.githubusercontent.com/129620584/236149744-cfe8e5e8-f5d1-454c-95f9-8fa4df458bb5.png)
![image](https://user-images.githubusercontent.com/129620584/236149924-df7cea1d-7888-4196-adc6-2e6b68d28926.png)
![image](https://user-images.githubusercontent.com/129620584/236150241-2a6f453c-d5a8-4829-a0f2-9e0f5408d6f7.png)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/129620584/236149957-2c22ef1e-f19b-4d01-8206-f56504918c74.png)

### PrestaShop version(s) where the bug happened

PrestaShop 8.0.4

### PHP version(s) where the bug happened

PHP: 8.1.16

**Comment by AureRita** [comment]
Hello @Kos-tash ,

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template and provide clear and concise steps to reproduce the bug**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). 

Only screen can't help us, can you provide us a complete step to reproduce ? 

Thank you
Waiting for your feedback

**Comment by Kos-tash** [comment]
Hello, @AureRita 
I just installed Prestashop, so no additional modules are installed. 
PrestaShop: 8.0.4
PHP: 8.2.4 (And on version 8.1 it doesn't work properly either)
![image](https://user-images.githubusercontent.com/129620584/236385085-8169d5a0-3eb2-4124-aad5-fcc77bb4f0bd.png)


**To reproduce the error, you need to follow the pattern and follow clear and correct steps.**
**1.** You need to install Prestashop 8.0.4 with Ukrainian localization or simply add Ukrainian localization to an already configured store
**2.** Now we just need to go to the next page: catalog > Brands & Suppliers > Suppliers
![image](https://user-images.githubusercontent.com/129620584/236385733-cd5111fe-8e01-470f-ae56-3083d2967327.png)
**3.** After clicking on the "Suppliers" button, we get a 500 error.
![image](https://user-images.githubusercontent.com/129620584/236385901-d78788bd-6b29-4a18-9d08-9ad3a206b46a.png)

! When I install PHP 7.4.33 there is no error. It turns out that the error only occurs when PHP version 8.0 and newer is configured.

_Please check. Waiting for your reply._

**Comment by kpodemski** [comment]
@Hlavtox, you had a very similar error in Czech, what was wrong then? It was something in Crowdin translations, right?

**Comment by florine2623** [comment]
Hello @Kos-tash ,

I have reproduced your issue in `8.0.4`, `8.1.x` and `develop` with PHP 8.1. I'll add this to the backlog so it can be fixed.

https://github.com/PrestaShop/PrestaShop/assets/16019289/c001a12f-7703-41d0-97e5-f78f58d66a35

It is a regression 1.7.8.9 as it was working fine on this version.

When I enable debug mode, here's the issue I have :
<img width="1088" alt="Screenshot 2023-05-09 at 16 48 20" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/f112850a-a1b4-44e9-a710-2fe1f893d672">
`Unknown format specifier "�"`

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by l-delin** [comment]
Hello, this issue is due to a missing variable (%s) in some translated strings on the PS Crowdin project:
![image](https://github.com/PrestaShop/PrestaShop/assets/113511191/aafdbfff-e0c9-4519-a387-3553fb562a0b)

Namely, all of these:
<img width="830" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/113511191/9bccd4b5-e0b2-4744-a41a-4c66700827ac">

I fixed it and I can access the supplier page now.

Before:
<img width="1440" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/113511191/1647dbd0-e3fd-4d45-b6ba-5a1039f35084">

After:
<img width="1440" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/113511191/f6c91222-42c1-445a-aadf-d28592126a40">

@Kos-tash could you update your translations **tomorrow** (09/05) and let me know if the issue is fixed?

Thank you!

**Comment by Kos-tash** [comment]
@l-delin When I checked all the translations and added the missing letter "s", the error disappeared.
Now working stably on php 8.2.4.
If I understand correctly, the error is caused by using the vsprintf function.
Vsprintf function received changes in php version > 8.0.0
https://www.php.net/manual/en/function.vsprintf.php - This function no longer returns false on failure.

**Comment by matks** [comment]
@Kos-tash Where do you see `We set the condition that in the case of a translation error, a standard phrase should be used` in the code ?

I look at https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php#L64 I do not see it

**Comment by MatShir** [comment]
It seems fixed. Should we close the issue then?

**Comment by hibatallahAouadni** [comment]
Yes it's fixed :tada:
