### ISSUE TITLE
error payment prestashop 8.0.2 with api

### ISSUE THREAD

**Issue by thomas-upecom** [PrestaShop/PrestaShop#32440]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi guys 
i m working on the prestashop 8.0.2 edition (SAAS) 
I try to create orders from the api (so without real payment)
So i choose Check payment . Is it the good ? (i also try with ps_wirepayment)

When i create the order , the order comes with the status "payment error" 
I don t' know why . 

### Expected behavior

I expect the order comes with the status processing , how to do that?

### Steps to reproduce

Here is my params i send on the API : 
```
<?xml version="1.0" encoding="UTF-8"?>
<prestashop>
   <order>
      <id_address_delivery>207</id_address_delivery>
      <id_address_invoice>208</id_address_invoice>
      <id_cart>79</id_cart>
      <id_customer>16</id_customer>
      <id_currency>1</id_currency>
      <id_carrier>6</id_carrier>
      <id_lang>1</id_lang>
      <current_state>PS_OS_PAYMENT_ACCEPTED</current_state>
      <module>ps_checkpayment</module>
      <payment>ps_checkpayment</payment>
      <total_paid>883.97</total_paid>
      <total_paid_real>883.97</total_paid_real>
      <total_products>733.31</total_products>
      <total_products_wt>879.97</total_products_wt>
      <conversion_rate>20</conversion_rate>
      <total_shipping_tax_incl>4</total_shipping_tax_incl>
   </order>
</prestashop>
```

### PrestaShop version(s) where the bug happened

1.8.0.2 edition

### Your company or customer's name goes here (if applicable).

jumpl

**Comment by florine2623** [comment]
Hello @thomas-upecom ,

You can add the current_state element.
<img width="536" alt="Screenshot 2023-05-09 at 16 05 12" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/505ca7b9-7b75-433d-b445-9ed5cf32bfc5">


More info here : https://devdocs.prestashop-project.org/8/webservice/resources/orders/

What exactly is your bug ? I'm not sure I understand.

**Comment by Ljz7** [comment]
@florine2623 

Hello, 

I kind of face the same issue. For a new order created with Prestashop WS, the current_state parameter is not applied. The current_state is automatically set to `PS_OS_WS_PAYMENT`.

There is a "setter" method defined in the Order class : 

https://github.com/PrestaShop/PrestaShop/blob/develop/classes/order/Order.php#LL2402C1-L2409C6

But as this is a new order, `$this->id` is not set yet. And so, we don't enter the conditional instruction block.

**Comment by hibatallahAouadni** [comment]
Hello @thomas-upecom 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
