### ISSUE TITLE
Installations are blocked on Step Install Addons modules for versions 1.7.5.2 + 1.7.6.1 + 1.7.6.7 + 1.7.7.8 + 1.7.8.9

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#32444]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The installation cannot be finished properly 
<img width="688" alt="Screenshot 2023-05-04 at 11 21 41" src="https://user-images.githubusercontent.com/16019289/236171924-096cfec2-9912-474e-ba51-feca51b04a0a.png">

Work around :
Change URL : `myshop.com/install` by `myshop.com/admin`
Access to BO is OK, but no product, no category, no nothing is installed. Even though I check "install demo products" during installation

For @hibatallahAouadni , this workaround allows all products, categories, etc to be installed with `1.7.5.2` ONLY

### Expected behavior

Installation should finished without error

### Steps to reproduce

1. [Download](https://github.com/PrestaShop/PrestaShop/releases) zip for any of the versions mentioned above
2. Go through installation
3. See step Install Addons module is broken ❌ 

### PrestaShop version(s) where the bug happened

Any version above 1.7.4.x and below 8.0.x

### PHP version(s) where the bug happened

7.1

**Comment by tesshsu** [comment]
Hi @florine2623 ,
Just curious like to know if you installed that different version with docker or base by Apache Xampp ?  tks

**Comment by matks** [comment]
> Just curious like to know if you installed that different version with docker or base by Apache Xampp ? tks

We're testing with every possible settings 😄 but we have people who observe the problem and other people who have no issues

**Comment by florine2623** [comment]
Fixed with https://stackoverflow.com/questions/24715426/how-do-you-increase-the-apache-fastcgi-timeout-on-mamp-mamp-pro
