### ISSUE TITLE
UTF8 charset brake after installation 1.7.8.9 from 1.7.6.x

### ISSUE THREAD

**Issue by rozwand** [PrestaShop/PrestaShop#32449]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After update the prestashop read wrong UTF8 characters untill update everything is ok but after this:
![ps-utfproblem 1 7 8 9](https://user-images.githubusercontent.com/69338080/236211680-3dd7b83c-918c-4b24-bb75-ce15ca9d523a.png)

### Expected behavior

Well Expected after this update all will work fine. But it dont.

I found this https://github.com/PrestaShop/PrestaShop/issues/12113 was maintioned before but You did not fix it untill now.

There is a post in there at the end that fix this error

### Steps to reproduce

1. 1.7.6.x with UTF8
2. Update to 1.7.8.9
3. The UTF8 coding will show ĹciÄgacz E06 Kwiaty BeĹź instead Ściągacz kwiaty beż or Strona gĹĂłwna  / Strona główna. problem is in front an back office.

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.4

**Comment by kpodemski** [comment]
It is not directly related to PrestaShop. Your SQL server has incorrect default encoding, possibly latin2 or something like this. You can work around this problem by forcing encoding in Doctrine, [this](https://stackoverflow.com/a/41456603/2895156) is how you can do that. The config file is inside app/config/doctrine.yml.

The final solution should be to change the default encoding of your database.

**Comment by rozwand** [comment]
My encoding in DB is fine its all UTF-8 and as you said i have the server default latin2. But question why it was working fine before update and broke after update?
