### ISSUE TITLE
Language is not selected by default in Advanced parameters > Import page

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#32443]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Language is not selected by default in Advanced parameters > Import page

![Import-•-PrestaShop](https://user-images.githubusercontent.com/24647495/236167196-59267a07-b68a-49dc-8afe-f14b2e3a063d.png)

### Expected behavior

Language should be selected by default

![Import-•-PrestaShop (1)](https://user-images.githubusercontent.com/24647495/236167235-dc40733d-84dd-43b8-8843-5498b633f420.png)

### Steps to reproduce

1- Go to BO > Advanced paramerets
2- Go to Import page
3- Language is not selected

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

**Comment by hibatallahAouadni** [comment]
Hello @nesrineabdmouleh 

I reproduce the issue with develop and PHP8, see the attached screen record below:

[issue 32443 with PHP 8.webm](https://user-images.githubusercontent.com/23308427/237004152-94992e46-dfb6-4c9c-bdeb-a6dd113875b0.webm)

It's a regression! nice catch 🚀 

Thanks!

**Comment by 0x346e3730** [comment]
Apparently regression comes from https://github.com/PrestaShop/PrestaShop/pull/32325
