### ISSUE TITLE
Fix & complete GDPR 2.0.x refactoring

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#32459]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

## GDPR 2.0.X refactoring background

A few weeks ago, GDPR module 2.0.0 then 2.0.1 were released https://github.com/PrestaShop/psgdpr
These 2 versions were the first releases of GDPR 2.0.x new major version. This major version mainly embeds a major refactoring of the inner working of the module and uses more modern code.

However multiple issues were found in this new major version after it was released, so the release was cancelled (rollback). The GitHub releases 2.0.0 and 2.0.1 have been marked pre-release https://github.com/PrestaShop/psgdpr/releases . Latest available version is back to 1.4.3

## Shop upgrades failures background
After 8.0.4 and 1.7.8.9 upgrades, multiple people reported upgrade failures from 1.7.8.x and 8.0.x versions to 8.0.4 . Looking at the bug reports and joined assets (screenshots, logs...) we noticed problems were seemingly coming from the upgrade process trying to upgrade the GDPR module on people’s shops from 1.4.3 to 2.0.1
Please read https://github.com/PrestaShop/PrestaShop/discussions/32348#discussioncomment-5782671 for more informations about it

## Current situation
The GitHub releases 2.0.0 and 2.0.1 have been marked pre-release https://github.com/PrestaShop/psgdpr/releases

Official latest GDPR module available version is 1.4.3

However `master` branch from https://github.com/PrestaShop/psgdpr/ contains the code from 2.0.1

### Steps to reproduce 

1. someone wants to upgrade from version 8.0.x to 8.0.4
2. the autoupgrade assistant sees the shop is using GDPR module 1.4.3
3. the autoupgrade assistant polls Addons API and sees GDPR module 2.0.1 is the latest available version
4. the autoupgrade assistant attempts to upgrade GDPR module from 1.4.3 to 2.0.1
5. upgrade error happens

## What should be done?
We need to finish the work :smile: . We need to fix the problems inside GDPR module and release version 2.0.2 of the GDPR module, a version that works correctly and does not introduce shop upgrade failures.

In order to achieve this, at least 3 steps are needed:
1. Fix the bug https://github.com/PrestaShop/PrestaShop/issues/32211
2. Analyze then reproduce the shop upgrade issue responsible for https://github.com/PrestaShop/PrestaShop/discussions/32348
3. Perform a 2.0.2 release of the GDPR module (and test it extensively!)

Some items might be missing from this list: issues we are not (yet) aware of and will hopefully be found while testing the module and the upgrade process

**Comment by matks** [comment]
@RosaBenouamer I dont know what labels to add 😅

**Comment by WahbiPS** [comment]
May be linked to [Disabling a module in one shop will disable it in all shops#30262](https://github.com/PrestaShop/PrestaShop/issues/30262)

**Comment by fabienvallon** [comment]
Looks like it is not reproduced 
CC : @MhiriFaten

**Comment by matks** [comment]
I close as https://github.com/PrestaShop/PrestaShop/pull/31379 was merged and I will create a ticket better explained

**Comment by kmorgen** [comment]
1. If trying to install/update from BO Marketplace (inside PS) latest version say 1.4.3
2. At the online Marketplace latest version is called 2.0.2 (screenshot): 
https://addons.prestashop.com/en/natif/39324-official-gdpr-compliance-by-prestashop-17.html
3. If trying to download for PS8.2 it will appear as 1.4.3
4. Hovever my current installed version in PS8.2.1 is labled 2.0.2

Confused! - So should I uninstall the 2.0.2 and install the apparently older 1.4.3 again (despite different BO). Is the current 2.0.2 broken somehow? (it seem to work, but menu is not themed, which was my reason for looking into it)

![Image](https://github.com/user-attachments/assets/2febccf8-42fa-4aef-9ee3-9996fece0ba5)
