### ISSUE TITLE
Error 500 when redirect from successful payment to the order confirmation

### ISSUE THREAD

**Issue by mack94** [PrestaShop/PrestaShop#32463]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After upgrade from 8.0.3 up to 8.0.4 I found the bug, when testing both Stripe and PayPal payments. When I make a cart, then create an order I am redirected to PayPal or Stripe. Then I authorize my payment and those steps were fluently done. When authorized payment is redirected to my address: 

`https://XXX.de/bestellbestatigung?id_cart=34&id_module=141&id_order=15&key=b9cc923d213e7a833adb27248e7e6afe
`
I got Error 500 and: 

> Ta strona obecnie nie działa. Witryna XXX.de nie może obecnie obsłużyć tego żądania.
HTTP ERROR 500

It can't handle the request. Unfortunately in my log file, both in Debug and Production modes, any error is recorded. **When I refresh the page, then it loads properly, I can see success and created order!!** 

After small investigation we decided to rollback to 8.0.3 version and this bug disappeared. Again tried to update to 8.0.4. and error come back. When updating 8.0.3. to 8.0.4 I got an error, but rolling back also however it didn't affect this error. 

This error was, but I don't think it is connected with the problem I described. 

> Error: Class "Composer\Autoload\ComposerStaticInit015ec6598460e77da763c3cb9c71a97c" not found #0 /home/platne/serwer166088/public_html/XXX.de/vendor/autoload.php(25): ComposerAutoloaderInit015ec6598460e77da763c3cb9c71a97c::getLoader() #1 /home/platne/serwer166088/public_html/XXX.de/modules/autoupgrade/classes/UpgradeContainer.php(567): require_once('...') #2 /home/platne/serwer166088/public_html/XXX.de/modules/autoupgrade/classes/TaskRunner/Rollback/RestoreDb.php(256): PrestaShop\Module\AutoUpgrade\UpgradeContainer->initPrestaShopAutoloader() #3 /home/platne/serwer166088/public_html/XXX.de/admin897emraqx/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\Rollback\RestoreDb->init() #4 {main}

**Mark this error (Error 500, not an upgrade/rollback error) as regression and check yourself.**

### Expected behavior

If payment authorized, it should go to the page "[Your Order Is Confirmed](https://XXX.de/bestellbestatigung)", not require to refresh the page after giving Error 500. 

### Steps to reproduce

1. Add product to cart,
2. Make an order
3. Pay for it - PayPal, Stripe, etc. 
4. You will be redirected back to your shop - **then you got Error 500**
5. **Refresh the page with error 500**
6. You got what you wanted - **Your order in confirmed.** - this is okay.

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.1

**Comment by kpodemski** [comment]
Hello @mack94 

Error 500 doesn't say anything. Please enable developer mode and then proceed to the page where the error occurs. This should show you more detailed information.

**Comment by mack94** [comment]
Hello @kpodemski 

I am aware of this, but unfortunately both in production and developer mode I just only got 500 error. Moreover, any record in var/logs appear. Nobody could confirm or reproduce similar issue?

**Comment by hibatallahAouadni** [comment]
Hello @mack94 

It seems that your issue is not a PrestaShop core bug.
If your module is PayPal or Stripe Official, please contact support team on Addons.

We will close this issue.

Thanks!

**Comment by radumchristian** [comment]
I am experiencing exactly the same but with square module.. could you please let me know which support team on addons to add by providing a url, thank you

**Comment by rafavargas** [comment]
Same here. Using PrestaShop's Official Docker Image.

**Comment by radumchristian** [comment]
Hello, I don't know if this applies for the others but I was able to solve it following this guide: 

What solved the issue was to open the file /config/smartyfront.config.inc.php
and editing the function starting on line 95

function smartyRender($params, &$smarty)
{
    $ui = $params['ui'];

    if (array_key_exists('file', $params)) {
        $ui->setTemplate($params['file']);
    }

    return $ui->render($params);
}
into 

function smartyRender($params, &$smarty)
{
    $ui = $params['ui'];

    if ($ui !== null) {
        if (array_key_exists('file', $params)) {
            $ui->setTemplate($params['file']);
        }

        return $ui->render($params);
    } else {
        // Handle the case where $params['ui'] is null
        // You can throw an exception, log an error, or take appropriate action.
    }
}
The if checks whether the value $ui is null and if it is not it does what prestashop wants it to do (setTemplate etc) but if it in fact IS null it just does nothing.

Please feel free to add a function in the area where the comments are ( // ... )

reference: https://www.prestashop.com/forums/topic/1078118-error-500-php-fatal-error-uncaught-error-call-to-a-member-function-settemplate-on-null-in-configsmartyfrontconfigincphp97/

**Comment by kpodemski** [comment]
@radumchristian 

Thank you for your message. The fix is inside PrestaShop 8.1.3:
https://github.com/PrestaShop/PrestaShop/pull/34448

Could you let me know if you've tested it on 8.1.3?

**Comment by radumchristian** [comment]
> @radumchristian
> 
> Thank you for your message. The fix is inside PrestaShop 8.1.3: #34448
> 
> Could you let me know if you've tested it on 8.1.3?

Hello, I haven't tested it on that version as I am running 8.1.1, will probably have to set up another store with the latest update and if the issue still persists I'll get back to you, thanks for your reply.
