### ISSUE TITLE
PS_Categoryproducts Gives everyone the same template, leading to error when adding a product to cart

### ISSUE THREAD

**Issue by acalvomanxa** [PrestaShop/PrestaShop#32461]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi, so basically what happens is we had this carroussel (ps_categoryproducts) and we couldn't click the add to cart button. We found that the hidden input "token" was not the one that the customer should have, but another's. Checking ps_categoryproducts.php, we found out that the same template is served to everyone that would enter the page. Therefore, if custoemr 4320 entered the page, the template was saved onto cache (and his token on the carroussel's products), and everyone else who tried to click add to cart wouldn't be able, because they would be seeing the 4320 user's token
![image](https://user-images.githubusercontent.com/123938331/236418874-2d7db3b2-945e-419b-9f4f-2bd22abadd6c.png)

Our solution was to neglect the function "isCached" and clear the cache every time the widget is loaded.
![image](https://user-images.githubusercontent.com/123938331/236420290-3636121a-e107-4bd7-9824-19bcd32ef217.png)

### Steps to reproduce

Go to product page
Click on add to cart on the ps_categoryproducts carroussel
Enter with another customer
Go to same product page
Click on add to cart on the ps_categoryproductscarroussel

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_categoryproducts 1.0.4

### Your company or customer's name goes here (if applicable).

Alex Calvo

**Comment by Hlavtox** [comment]
Add to cart button is not supported in the template by default for these reasons. Bug does not happen with classic theme.

I suggest making a fork of ps_categoryproducts and removing the caching functionality. :-) Performance will be the same. 👍

**Comment by kpodemski** [comment]
There's a workaround. Fill the token with javascript, the token is available in `prestashop.static_token`.

@Hlavtox removing the cache from this module **is not** a good idea :D

**Comment by kpodemski** [comment]
I'm closing this issue as it is related to the custom feature you have :-)

**Comment by acalvomanxa** [comment]
Thank you!
