### ISSUE TITLE
Delivery time shows empty under product miniature of the related products on product page.

### ISSUE THREAD

**Issue by frettka** [PrestaShop/PrestaShop#32478]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Similar issues:
#28457
#18559
#29856

Information from delivery_in_stock and delivery_out_stock does not show on product minature template under related products (a.k.a. product accesories) tab on product page.

I have added following code to my template \mytheme\templates\catalog\_partials\minatures\product.tpl:
{$product.delivery_in_stock|print_r}
{$product.delivery_out_stock|print_r}
{$product.delivery_information|print_r}

$product.delivery_information shows the correct value (it is default value from the shop settings) but other 2 variables (which are the values from the product settings) show Array ( ) 1 -> as a result the delivery time doesn't show under the minature of related product.

Minatures under category page show correct values for all of those 3 variables. The problem is only with the minature under related products tab on product page.

### Expected behavior

Display delivery time under product minature of related product (a.k.a. product accesory) on product page.

### Steps to reproduce

1. set default template active
2. edit template  \mytheme\templates\catalog_partials\minatures\product.tpl
3. add variables $product.delivery_out_stock and $product.delivery_in_stock
4. set custom delivery times for product "A"
5. set product "A" as a related product for product "B"
6. open FO product "B" page
7. under product accesories you should see product "A" minature with delivery time but the text is empty

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.3

![related-products](https://user-images.githubusercontent.com/132687539/236813583-5a24c6da-11be-4893-8de1-75bce95dd1dd.jpg)
![category](https://user-images.githubusercontent.com/132687539/236813602-490f0afb-0dd6-4e13-9a27-6c3594797c2e.jpg)

**Comment by hibatallahAouadni** [comment]
Hello @frettka 

Thanks for reporting the issue and for your patience 🙏 
As you mentioned, we need to add this code below to the file  `themes\mytheme\templates\catalog_partials\miniatures\product.tpl`
```
{$product.delivery_in_stock|print_r}
{$product.delivery_out_stock|print_r}
{$product.delivery_information|print_r}
```
But, could you please specify in which block we need to add it? is it `product_thumbnail` or `quick_view` or `product_variants` or `product_price_and_shipping`?
Waiting for your feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @frettka 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
