### ISSUE TITLE
Wrong total price tax incl. calculation during address update on order backoffice page

### ISSUE THREAD

**Issue by mcaldex** [PrestaShop/PrestaShop#32477]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the updateOrderDetailsTaxes function located here: https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Order/OrderDetailUpdater.php#L160

which gets called everytime you update an address from the backoffice order page, we have a bad calculation of the orderDetail object, specifically of the 'total_price_tax_incl' property.
You can see the issues are two:

1. The two properties unit_price_tax_incl and total_price_tax_incl are being assigned twice with the same values:
![image](https://user-images.githubusercontent.com/79152536/236805492-d9eb615a-b6a5-4f27-bc9c-df8482e59ff7.png)
                        
2. This line: `$orderDetail->total_price_tax_incl = (float) $orderDetail->total_price_tax_incl + $totalAmount;` should be: `$orderDetail->total_price_tax_incl = (float) $orderDetail->total_price_tax_excl + $totalAmount;` , otherwise the tax is added twice.

**However**, this bad calculation gets fixed automatically since these properties gets replaced immediately here thanks to the update call through the orderAmountUpdater:
![image](https://user-images.githubusercontent.com/79152536/236806512-01ab9ed1-0c61-441d-8697-90db9c55caf4.png)

which calls the updateOrderDetail function https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Order/OrderDetailUpdater.php#L85 and replaces the two properties with the correct values.

### Expected behavior

Do not repeat the same calculations, maybe you can remove the call to the updateOrderDetailsTaxes() function which has the bad calculation.

### Steps to reproduce

No way to reproduce the bug on the frontend, just follow the backend code flow.

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

Hostinato

**Comment by florine2623** [comment]
Hello,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by dpuhach** [comment]
> **However**, this bad calculation gets fixed automatically since these properties gets replaced immediately here thanks to the update call through the orderAmountUpdater

@MHostinato Unfortunately this doesn't work for the case when we have more than one tax. In this case, the result is incorrect amounts. Removing the OrderDetails updating from updateOrderDetailsTaxes in my tests caused an order not to be recalculated even when required.

My issue can be found here:
https://github.com/PrestaShop/PrestaShop/issues/33591

My solution can be found here:
https://user-images.githubusercontent.com/56586957/259727218-48247b75-3f2c-4e68-bd27-2fe0033568ba.png

**Comment by sallemiines** [comment]
Hello @MHostinato  

Thanx for your feedback ! 

This issue  is duplicate [#33951](https://github.com/PrestaShop/PrestaShop/issues/33591) 

We will close this issue 
Thank you

**Comment by sallemiines** [comment]
Duplicate to [#33951](https://github.com/PrestaShop/PrestaShop/issues/33591)
