### ISSUE TITLE
PDF invoice generator footer is not showing the correct information only show a %s

### ISSUE THREAD

**Issue by DevCorchid** [PrestaShop/PrestaShop#32485]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the PDF invoice generator footer is not showing the correct information only shows a %s instead of the phone
![image](https://github.com/PrestaShop/PrestaShop/assets/130400998/527150f9-bdca-4959-889d-01c741b42a23)

`        $shop_address = $this->getShopAddress();

        $id_shop = (int) $this->shop->id;

        $this->smarty->assign([
            'available_in_your_account' => $this->available_in_your_account,
            'shop_address' => $shop_address,
            'shop_fax' => Configuration::get('PS_SHOP_FAX', null, null, $id_shop),
            'shop_phone' => Configuration::get('PS_SHOP_PHONE', null, null, $id_shop),
            'shop_email' => Configuration::get('PS_SHOP_EMAIL', null, null, $id_shop),
            'free_text' => Configuration::get('PS_INVOICE_FREE_TEXT', (int) Context::getContext()->language->id, null, $id_shop),
        ]);
`

### Expected behavior

It should add the phone number instead of  %s

### Steps to reproduce

Go to orders > Invoice> generate a PDF

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

PDF Generator

**Comment by tesshsu** [comment]
Hi @DevCorchid 
![2](https://github.com/PrestaShop/PrestaShop/assets/3927152/beba6faf-13ad-485a-bf48-86295e38922d)
Could you please provide a screenshot cause depending on the version the bug might differ? my screen shot provide is version 8.0.4 and php 7.3 , tks

**Comment by DevCorchid** [comment]
@florine2623 @tesshsu Sure, for me was in the ver. 8.0.2 - 8.0.4
![image](https://github.com/PrestaShop/PrestaShop/assets/130400998/85c59f51-82ff-413d-b704-5cdd111c2ea5)
The bug for me is at the PDF footer. I was able to fix the issue by changing the /public_html/pdf/footer.tpl to the code below
`{if !empty($shop_phone) OR !empty($shop_fax)}
   {l s='For more assistance, contact Support:' d='Shop.Pdf' pdf='true'}<br />
   {if !empty($shop_phone)}
      tel: {$shop_phone|escape:'html':'UTF-8'}<br />
   {/if}`

**Comment by florine2623** [comment]
Hello @DevCorchid ,

I have reproduced your issue on `8.0.x`, `8.1.x` and `develop`. I'll add this to the backlog so it can be fixed.
<img width="311" alt="Screenshot 2023-05-09 at 16 23 52" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/097e6b4e-5f8e-4119-bbd4-d2056702b0c5">

It is a regression from 1.7.8.9.

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you 🙏
