### ISSUE TITLE
Emailalerts don't send email when product out of stock

### ISSUE THREAD

**Issue by jlores** [PrestaShop/PrestaShop#32489]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

In Prestashop 8.0.x ps_emailalerts don't send an email when the the product have low stock. 

In case of new order, the email is sent correctly

![email](https://user-images.githubusercontent.com/48771938/237037563-a00fcb0a-7937-48d6-8f1c-4cb5534e7d48.png)

### Steps to reproduce

Go to products
Modify a product with quantity < 3 and push "save"
In Prestashop 1.7.x.x in this case you received an email. And with Prestashop 8.0.x nothing happens

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

7.3.33

### If your bug is related to a module, specify its name and its version

ps_emailalerts 2.4.1

**Comment by jlores** [comment]
I think i found something. In PS 8.0.x in product page this check is disabled. When I mark then, I received the email.

In previous versions, this was not necessary.

![Captura desde 2023-05-09 11-49-17](https://user-images.githubusercontent.com/48771938/237061154-69c4907a-1c21-4705-ad0f-6ac2d992abdd.png)

**Comment by SharakPL** [comment]
@jlores do you still not get alerts without this option checked with the latest version of ps_emailalerts?

> I think i found something. In PS 8.0.x in product page this check is disabled. When I mark then, I received the email.
> 
> In previous versions, this was not necessary.
> 
> ![Captura desde 2023-05-09 11-49-17](https://user-images.githubusercontent.com/48771938/237061154-69c4907a-1c21-4705-ad0f-6ac2d992abdd.png)

This is really awful option and I honestly don't know why is it even there. It sends emails **to all employees** and not the ones you have configured in ps_emailalerts. I doubt this option has any relevance to the module as it completely ignores module's configuration.

This option should be **always OFF** unless you want to spam all admins with stock related emails!
