### ISSUE TITLE
Doctrine proxy error

### ISSUE THREAD

**Issue by dylan-ramos** [PrestaShop/PrestaShop#32502]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,
I have a problem on a module I created.
In my module I use 2 entities:

-	ThemeWidget
-	ThemeWidgetLang

In order to use the multi lang features, the entity "ThemeWidgetLang" uses the entity "PrestaShopBundle\Entity\Lang" for the $lang property.

```
    /**
     * @var Lang
     *
     * @ORM\Id
     * @ORM\ManyToOne(targetEntity="PrestaShopBundle\Entity\Lang")
     * @ORM\JoinColumn(name="id_lang", referencedColumnName="id_lang", nullable=false, onDelete="CASCADE")
     */
    private $lang;
```

In DEV environment everything works, but when switching to PROD I get the following error (cache completely empty):

```
Compile Error: require(): Failed opening required www\var\cache\prod/doctrine/orm/Proxies\__CG__PrestaShopBundleEntityLang.php' (include_path=www\vendor/pear/archive_tar; www\vendor/pear/console_getopt; www\vendor/pear/pear-core-minimal/src; www\vendor/pear/pear_exception;.;C:\php\pear')

[Symfony\Component\Debug\Exception\FatalErrorException 0]
```

According to the information I found, in order to solve this error, I have to launch the creation of proxies manually, via the commands :

``
php ./bin/console cache:clear --env=prod --no-debug
``
and
``
php ./bin/console cache:warmup --env=prod --no-debug
``

But this does not create the proxies.
The folder "/var/cache/doctrine/orm/Proxies" is created but remains empty.

In order to work around the problem, I have to modify the "app/config/doctrine.yml" file.

```
  orm:
    auto_generate_proxy_classes: "%kernel.debug%" /** #### <- set to true ### */
    naming_strategy: prestashop.database.naming_strategy
    auto_mapping: true
    dql:
      string_functions:
        regexp: DoctrineExtensions\Query\Mysql\Regexp
```

And reload the pages that had the errors, so that the cache is correctly created.
Once the proxies are created, I rollback the "app/config/doctrine.yml" file.

Sincerely,

### Expected behavior

Is this the right way to do it?

Why do I have to modify the app/config/doctrine.yml file?

### Steps to reproduce

1. delete the cache ($var/cache rm -rf *)
2. disable the debug mode

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.2.34

**Comment by florine2623** [comment]
Hello,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers @PrestaShop/committers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by matks** [comment]
Hi @dylan-ramos I used [collapsed block](https://codex.so/collapsed-block-for-github-markdown) to improve your template so we dont have to scroll for a very long time 😄

**Comment by dylan-ramos** [comment]
Hi

The creation of proxies is not automatic, in order to limit the resources used in the prod environment. If it is necessary to create them, use the command :

`
php ./bin/console cache:clear --env=prod --no-debug
`

This command cleans the cache and automatically launches the "cache:warmup" (this step creates proxies and other caches).

---

The problem came from a module, which has a file "/modules/########/src/Entity/Payment/index.php".

This stops the creation of the cache, as the "index.php" file terminates the script via the "exit" function.

All files in the "/modules/########/src/Entity" folder are interpreted except "/modules/########/src/Entity/index.php", which is manually excluded, so an "index.php" file in a child folder "/modules/########/src/Entity/*/" is not expected and causes the app to stop.

In conclusion, deleting the file "/modules/########/src/Entity/Payment/index.php" will solve the problem.

---

<details>
  <summary>Code</summary>
  <p>

*fichier "/var/cache/prod/Container#######/appProdProjectContainer.php"*
```
...
/*
 * This class has been auto-generated
 * by the Symfony Dependency Injection Component.
 *
 * @final since Symfony 3.3
 */
class appProdProjectContainer extends Container
{
...

    /*
     * Gets the public 'doctrine.orm.default_entity_manager' shared service.
     *
     * @return \Doctrine\ORM\EntityManager
     */
    protected function getDoctrine_Orm_DefaultEntityManagerService($lazyLoad = true)
    {
        $a = new \Doctrine\ORM\Configuration();

        $b = new \Doctrine\Persistence\Mapping\Driver\MappingDriverChain();
...
        $g = new \Doctrine\ORM\Mapping\Driver\AnnotationDriver($c, [0 => ($this->targetDirs[3].'\\modules\\########\\src\\Entity')]);
        $g->addExcludePaths([0 => ($this->targetDirs[3].'\\modules\\########\\src\\Entity/index.php')]);
...
}
...
}
...
```

*fichier "index.php"*
```
<?php
/**
* 2007-2015 PrestaShop
*
* NOTICE OF LICENSE
*
* This source file is subject to the Academic Free License (AFL 3.0)
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/afl-3.0.php
* If you did not receive a copy of the license and are unable to
* obtain it through the world-wide-web, please send an email
* to license@prestashop.com so we can send you a copy immediately.
*
* DISCLAIMER
*
* Do not edit or add to this file if you wish to upgrade PrestaShop to newer
* versions in the future. If you wish to customize PrestaShop for your
* needs please refer to http://www.prestashop.com for more information.
*
*  @author    PrestaShop SA <contact@prestashop.com>
*  @copyright 2007-2015 PrestaShop SA
*  @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
*  International Registered Trademark & Property of PrestaShop SA
*/

header('Expires: Mon, 26 Jul 1997 05:00:00 GMT');
header('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT');

header('Cache-Control: no-store, no-cache, must-revalidate');
header('Cache-Control: post-check=0, pre-check=0', false);
header('Pragma: no-cache');

header('Location: ../');
exit;
```
  </p>
</details>

---

<details>
  <summary>FR</summary>
  <p>
Bonjour,

La création des proxies n'est pas automatique afin de limiter les ressources utilisées. S'il est nécessaire de les créer alors il faut utiliser la commande 

`
php ./bin/console cache:clear --env=prod --no-debug
`

Cette commande se charge du nettoyage du cache et lance automatiquement le "cache:warmup" (c'est cette étape qui crée les proxies et autres caches).

---

Le problème venait d'un module, qui a un fichier "/modules/########/src/Entity/Payment/index.php".

Cela provoque l'arrêt de la création du cache car ce fichier "index.php" met fin au script via la fonction "exit".

Tous les fichiers dans le dossier "/modules/########/src/Entity" sont interprétés sauf le "/modules/########/src/Entity/index.php" qui lui est exclu manuellement, donc un fichier "index.php" dans un dossier enfant "/modules/########/src/Entity/*/" n'est pas prévu et provoque l'arrêt de l'app.

En conclusion, supprimer le fichier "/modules/########/src/Entity/Payment/index.php" permet de résoudre le problème.
  </p>
</details>

**Comment by studiokiwik** [comment]
Same problem, in PS 8.2.0.
Removing all `index.php` from `modules/*/src/Entity` did not solve the problem.
Done with:
```shell
find ./modules/*/src -name 'index.php' -delete
```

But setting `auto_generate_proxy_classes` to `true` in the yml did the trick.

Is there any reason why we would NOT generate proxy in prod env? Why is there this limitation?


**EDIT:**
 auto-response: because it would overload each future client request, as Symfony will try to detect if it must update cache files, making disk I/O.

On our case, doing a `php bin/console cache:warmup --env=prod` after the `rm -Rf var/cache/prod/*` fixed the error too.

**Comment by PululuK** [comment]
Hi @studiokiwik 

> Is there any reason why we would NOT generate proxy in prod env? Why is there this limitation?

To avoid performances issue

**Comment by dylan-ramos** [comment]
Hi @studiokiwik 

For your information, the `php ./bin/console cache:clear --env=prod --no-debug` command will automatically start the cache warmup. This saves you from having to delete the cache folder manually.

Also, as regards the “index.php” files in the “src/Entity” folders, the structure “/modules/MyModule/src/Entity/index.php” is OK.

But the structure “/modules/MyModule/src/Entity/anAnotherFolder/index.php” is NOT OK, so this is where you need to delete the index.php file (behavior still present on v8.2).

😉

---

<details>
  <summary>FR</summary>
  <p>
Bonjour @studiokiwik 

Pour information, la commande `php ./bin/console cache:clear --env=prod --no-debug` lancera automatiquement le warmup du cache. Cela vous évite de devoir supprimer le dossier de cache manuellement.

Aussi, en ce qui concerne les fichiers "index.php" dans les dossier "src/Entity", la structure "/modules/MyModule/src/Entity/index.php" est OK.

Mais la structure "/modules/MyModule/src/Entity/anAnotherFolder/index.php" n'est pas OK, c'est donc ici qu'il faut supprimer le fichier index.php (comportement toujours présent sur v8.2).

😉
</p>
</details>
