### ISSUE TITLE
Issue with notification admin back end - not rendering HTML

### ISSUE THREAD

**Issue by DevCorchid** [PrestaShop/PrestaShop#32503]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

For PrestaShop ver. 8.0.2 - 8.0.4 The notification menu in the backend shows the following:
![image](https://github.com/PrestaShop/PrestaShop/assets/130400998/46cb2c5e-c9e9-4921-87d2-96120773aa52)
The file that controls the text: Have you checked your... is located here 
/src/PrestaShopBundle/Bridge/Smarty/HeaderConfigurator.php

`    private function getNotificationTip(string $type): string
    {
        $tips = [
            'order' => [
                $this->translator->trans(
                    'Have you checked your [1][2]abandoned carts[/2][/1]?[3]Your next order could be hiding there!',
                    [
                        '[1]' => '<strong>',
                        '[/1]' => '</strong>',
                        '[2]' => '<a href="' . $this->link->getAdminLink('AdminCarts', true, [], ['action' => 'filterOnlyAbandonedCarts']) . '">',
                        '[/2]' => '</a>',
                        '[3]' => '<br>',
                    ],
                    'Admin.Navigation.Notification'
                ),
            ],`
            
            Does anyone know how to get rendered? so it can look like this:
            
![image](https://github.com/PrestaShop/PrestaShop/assets/130400998/49605ee6-8a6c-4b0a-a1e4-d9e7cc658665)

### Expected behavior

![image](https://github.com/PrestaShop/PrestaShop/assets/130400998/daacf22a-2112-4f29-81bc-e19ce9908bc5)

### Steps to reproduce

1. Login into the admin backend
2. Top Right corner notification area

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

PrestaShopBundle/Bridge/Smarty

**Comment by xga91** [comment]
I ve the same problem 8.04 and php 8.1.18

**Comment by paulnoelcholot** [comment]
Hello @DevCorchid ,

I reproduce the issue with PrestaShop version 8.0.1, 8.0.2, 8.0.3, 8.0.4, I'll add this to the backlog so it can be fixed.

![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/702e9cb4-5e21-4d23-b093-ee21b95d0fc7)


Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Hlavtox** [comment]
@paulnoelcholot Duplicate of https://github.com/PrestaShop/PrestaShop/issues/32216

**Comment by DevCorchid** [comment]
Resolved here https://github.com/PrestaShop/PrestaShop/pull/32215/files/101986fcd411a04f3d88e18c8bed72da7594d7c4
