### ISSUE TITLE
Empty tracking URL for "in transit" email

### ISSUE THREAD

**Issue by Codencode** [PrestaShop/PrestaShop#32508]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you enter the tracking number in an order, the "in_transit" email is sent which contains the link for tracking the shipment. Obviously, this link is valued only if the "Tracking URL" field has been valued for the courier.
Perhaps it would be appropriate to send this e-mail only if the "Tracking URL" field is set, also because entering the "Sent" status another e-mail is sent.
If this solution is considered appropriate, I can create a PR to solve the problem.

E-mail received with "tracking url" in the case of the courier with the "Tracking URL" field filled in
![Screenshot with tracking url](https://github.com/PrestaShop/PrestaShop/assets/2463965/498a6252-5d4b-4863-9892-a6df3e31f86d)

E-mail received with empty "tracking url" case of the courier with the "Tracking URL" field not filled in
![Screenshot without tracking url png](https://github.com/PrestaShop/PrestaShop/assets/2463965/f2c8521c-b2a6-4dc2-b74c-0ad9cb2c2f48)

Courier box backoffice order page
![Screenshot order carrier](https://github.com/PrestaShop/PrestaShop/assets/2463965/6b036040-845b-42a8-8fd5-31a09a1014c2)

"Tracking number" entry pop-up
![Screenshot order tracking](https://github.com/PrestaShop/PrestaShop/assets/2463965/35d74e54-f9c0-4ce6-b1b3-37e44936aa78)

### Expected behavior

The email must not be sent.

### Steps to reproduce

1. create a courier with the "Tracking URL" field blank
2. create an order by selecting the courier created
3. in the backoffice enter the order and enter the "Tracking number"
4. Check the received email to see that the tracking link is missing

### PrestaShop version(s) where the bug happened

all

### PHP version(s) where the bug happened

all

**Comment by Hlavtox** [comment]
This can be fixed only after we migrate the mailing system to Symfony and start using twig templates directly. No way to do conditions in emails unfortunately. :(

**Comment by Codencode** [comment]
> This can be fixed only after we migrate the mailing system to Symfony and start using twig templates directly. No way to do conditions in emails unfortunately. :(

Hi @Hlavtox,
yes of course I know this, but you might think not to send this e-mail at all because in any case when you set the "Shipped" status the system already sends an e-mail, therefore the "in_transit" e-mail without the link is almost useless , so you might think not to send it if the carrier's "Tracking URL" field is empty.
What do you think?

Thanks!

**Comment by Hlavtox** [comment]
On my stores, I don't send any email for shipped status and only use `in_transit` with the link.

**Quick solution from a module:**
```php
public function hookActionEmailSendBefore($params)
    {        
        if ($params['template'] == 'in_transit' && empty($params['templateVars']['{followup}'])) {
          $params['to'] = 'somenonses@yourshop.cz';
        }
    }
```

It should be able to stop the processing, but I could not make it work.

**Comment by Codencode** [comment]
In your case, the email would still be sent because the courier's "Tracking URL" field is filled in.
I propose to insert a check to send the "in_transit" e-mail only if the courier's "Tracking URL" field is completed, in this way if the field is not completed, the email is not sent, because this e-mail I think it's useless without the link.

**Comment by Codencode** [comment]
I would make the following change in the `OrderCarrierCore::sendInTransitEmail()` method:

```
    public function sendInTransitEmail($order)
    {
        $orderLanguageId = (int) $order->getAssociatedLanguage()->getId();
        $customer = new Customer((int) $order->id_customer);
        $carrier = new Carrier((int) $order->id_carrier, $orderLanguageId);
        $address = new Address((int) $order->id_address_delivery);

        // ***** addition code
        if (!$carrier->url) {
            return true;
        }
        // **********************
        ....
   }
```
Or a change should be made where this method is called so that it is called only if the courier has the "Tracking URL" field valued

**Comment by florine2623** [comment]
Hello @Codencode ,

I reproduce the issue with PrestaShop version 8.1.0, I'll add this to the backlog so it can be fixed.

<img width="566" alt="Screenshot 2023-05-15 at 14 53 59" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/cd8a9fa5-3d52-443c-a5b9-fb805c2d713d">

Thank you for the PR !
