### ISSUE TITLE
Var/cache folder are writable, but PrestaShop ask to set write permissions 

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#32512]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello
When attempting a 1-click upgrade, it won't continue, saying it can't, It's not possible to write in the following folders
var/cache
folder has the correct permissions. 755
![image](https://github.com/PrestaShop/PrestaShop/assets/11594433/61c858cb-d901-4e31-84d0-668627925ddb)
![image](https://github.com/PrestaShop/PrestaShop/assets/11594433/391d0fbc-a4ca-4c8b-8166-a34c5e90b912)
![image](https://github.com/PrestaShop/PrestaShop/assets/11594433/7a24cfe3-79f4-4e47-82df-301c5327d460)
![image](https://github.com/PrestaShop/PrestaShop/assets/11594433/1bb04002-8229-425d-b905-93af4ba052d8)

info_outline Server information
Server information: Linux https://github.com/PrestaShop/PrestaShop/pull/1 SMP Mon Feb 27 14:44:55 UTC 2023 x86_64
Server software version: LiteSpeed
PHP version: 7.4.33
Memory limit: 1G
Max execution time: 6360
Upload Max File size: 128M

PrestaShop version: 1.7.8.8

Check your configuration
Required parameters: Please fix the following error(s)
**Set write permissions for the "cache" folder.**
Optional parameters: OK

### Expected behavior

Upgrade the PS frrom 1.7.8.8 to 1.7.8.9

### Steps to reproduce

go to upgrade module

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4.33

**Comment by AureRita** [comment]
Hi @go-sudo,

Thank you for your report but we only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Thank you
