### ISSUE TITLE
cannot send emails from prestashop

### ISSUE THREAD

**Issue by cherrycoding** [PrestaShop/PrestaShop#32526]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I've have upgraded to latestet PS but when I do an order I am receiving this error in debug mode:

(1/1) ContextErrorException

Notice: Undefined variable: shop in Mail.php line 393

I've checked the Mail.php but I think $store variable is only for multistore? I only have a single store active.

### Steps to reproduce

1. complete an order
2. confirmation should be sent 

or
1. go to an existing order in the backend
2. click on "send message" 

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.4

**Comment by Democrowft** [comment]
Hey, how did you fix this?
