### ISSUE TITLE
Multiple image formats : The PNG original file is converted to JPEG

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#32527]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I upload a store image in PNG Format, it's converted to JPEG.

With this configuration : 
![image](https://github.com/PrestaShop/PrestaShop/assets/1533248/4ccfb6fb-e474-480e-b4ac-87001ec2324a)

### Expected behavior

When I upload a store image in PNG Format, it remains a PNG.

### JPEG
1. Enable Multiple image formats on the "New & Experimental Features" page
2. Create a store with a JPEG file for picture
3. The `img/st/{idStore}.jpg` exist => It's a JPEG file.

### PNG
1. Enable Multiple image formats on the "New & Experimental Features" page
2. Create a store with a PNG file for picture
3. The `img/st/{idStore}.jpg` exist => It's a JPEG file .**:warning: ERROR :warning:**

#### Acceptance Test
Unskip this test : 
https://github.com/PrestaShop/PrestaShop/blob/d672ad4ccc467722d13746e25fffc95a86e5e3b3/tests/UI/campaigns/functional/BO/08_design/06_imageSettings/15_checkStoreImageFormat.ts#L206-L209

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

7.3

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

**Comment by venditdevs** [comment]
Is it really a bug? Because it's known that Prestashop creates a PNG image with a JPG extension.
It always has been that way.

**Comment by Progi1984** [comment]
@venditdevs I don't talk about the extension. I talk about the file format. The file is converted in JPEG.

**Comment by AureRita** [comment]
Hi @Progi1984 

Thank you for your report, I reproduce you issue but it's a waiting behavior, as you can see on this video : 

[Untitled_ May 11, 2023 4_58 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/94e32c89-7374-43aa-b8b2-1d5f184d8bf8)

Indeed the file is in jpg but internally it's a png file 

I'll close this issue

**Comment by Progi1984** [comment]
@AureRita I reopened. You check with creating a product. I talk about creating a store.

**Comment by hibatallahAouadni** [comment]
Hello @Progi1984 

I reproduce the issue but let's check with Product team if this is the expected behavior or it's a bug 😉 
Ping @PrestaShop/product-team while upgrading a png file, should it be saved as png or jpg?

Thanks!

**Comment by fabienvallon** [comment]
If I remember 
jpeg > png 
png > png 

CC: @matthieu-rolland , @MatShir

**Comment by Hlavtox** [comment]
The file should remain in it's original format, with a JPEG extension

**Comment by RosaBenouamer** [comment]
I agree with  @Hlavtox.
@fabienvallon look [here ](https://github.com/PrestaShop/PrestaShop/pull/31485):-)
@hibatallahAouadni : when you have reproduce the issue. Did you check that the 'jpeg' file is not a png file with https://www.checkfiletype.com/
Indeed we just verified with @AureRita and we check that the jpeg file is in fact a png.So we didn't reproduce the issue.

**Comment by RosaBenouamer** [comment]
@paulnoelcholot can you check please ?

**Comment by Progi1984** [comment]
@RosaBenouamer & @paulnoelcholot Don't forget this configuration : 
![image](https://github.com/PrestaShop/PrestaShop/assets/1533248/345150e7-3014-48b6-a314-6a46a5d3efa7)

FYI The bug has been declared after tests with UI tests (they can't lie).

**Comment by Hlavtox** [comment]
@Progi1984 That configuration is for thumbnails, the original image should stay like it is.

**Comment by Progi1984** [comment]
I disagree. It is "Base format".

**Comment by Hlavtox** [comment]
The original image uploaded (img/st/1.jpg) MUST remain in it's original format with a jpg extension, regardless on what is set in image settings.

JPG/PNG options in image settings apply only to generated thumbnails.

**Comment by MatShir** [comment]
It is a feature request the feature works only for product images

**Comment by MatShir** [comment]
I may have spoken to soon, it does not work only for product images but for all the images types. As said @Hlavtox, the behavior keep adding the jpg extension at the end anyway. Your UI test needs to be adjusted.

**Comment by Progi1984** [comment]
@AureRita Could you modify this test : https://build.prestashop-project.org/test-scenarios/scenarios/core/functional/bo/design/image-settings/bo-design-image-settings-check-stores-image-format.html ?

Despite the configuration, the last line should be a jpeg : 

![image](https://github.com/PrestaShop/PrestaShop/assets/1533248/ce98d2d1-5381-414a-a433-b2575f3dd911)


`¯\_(ツ)_/¯`

**Comment by MatShir** [comment]
The test scenario seems to be correct, in fact the store is in PNG format with the jpg extension. You should check the store's file type without looking at its extension.

**Comment by Progi1984** [comment]
It is what I do in my UI test. And it's why I created this issue.

**Comment by Progi1984** [comment]
After discussion with @MatShir, 

* The behavior doesn't change (since a lot of versions) : image uploaded  (aka as base image) is in JPEG format (that doesn't listen the configuration).
*  So my bug is not a bug, it's a behavior change request, or a feature request.

**Comment by noszone** [comment]
Similar question, I can't save category images as PNG. I need transparency. However it's saves as jpg. Any ideas?

**Comment by MatShir** [comment]
closed by https://github.com/PrestaShop/PrestaShop/pull/34172
