### ISSUE TITLE
Multiple image formats : WebP is not generated when an image for a store is uploaded

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#32528]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

WebP is not generated when a picture image for a store  is uploaded

### Expected behavior

WebP is generated when a picture image for a store  is uploaded

### Steps to reproduce

1. Enable Multiple image formats on the "New & Experimental Features" page
2. Enable WebP in Image Format page
3. Create a store with a JPEG/PNG file for picture file for thumb
4. The `img/st/{idStore}-stores_default.webp` doesn't exist => **ERROR**
5. When I go on the front office
6. The `img/st/{idStore}-stores_default.webp` exist

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

7.3

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

**Comment by hibatallahAouadni** [comment]
Hello @Progi1984 

Up to fourth step, it's all clear and yes I reproduce the issue but I think it's the expected behavior.
Ping @PrestaShop/product-team while uploading a webp image should it saved as webp or jpg?
About the fifth and sixth step, could you please provide screen record 🙏 

Thanks!

**Comment by Progi1984** [comment]
@hibatallahAouadni The WebP Image should be generated like the config is checked (step 2).

**Comment by fabienvallon** [comment]
I think it should be saved in both format if I remember
CC: @matthieu-rolland , @nicosomb  , @MatShir

**Comment by AureRita** [comment]
Hi @Progi1984 

Thank you for your report, 
Currently, we have only product's image that are generated on creation, this is not really an issue but a feature not implemented 

Thank you

**Comment by Progi1984** [comment]
@AureRita In this case, it's a feature for the Working Group "IMS". No ?

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/product-team wdyt? should we convert this issue to a fetaure/discussion?

**Comment by RosaBenouamer** [comment]
@hibatallahAouadni yes :-)

**Comment by Progi1984** [comment]
Fixed in #33152 by @Hlavtox. Thanks
