### ISSUE TITLE
PDF files are always in English instead of shop language

### ISSUE THREAD

**Issue by Webalpina** [PrestaShop/PrestaShop#32530]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Prestashop est configuré en français, le client est en France.
Lorsqu'une commande est payée, La facture envoyée au client est libellé en anglais sauf le mot facture. La facture dans le BO est aussi en anglais.
Si le client affiche la facture depuis son compte la facture est en français et est correcte.
Ce n'est donc pas un problème de traduction.

[FA0000042023 - Français depuis le compte du client.pdf](https://github.com/PrestaShop/PrestaShop/files/11449905/FA0000042023.-.Francais.depuis.le.compte.du.client.pdf)
[FA0000042023 - Anglais envoyé en email.pdf](https://github.com/PrestaShop/PrestaShop/files/11449906/FA0000042023.-.Anglais.envoye.en.email.pdf)

### Expected behavior

J'attends un correctif pour que les factures soient libellées en français

### Steps to reproduce

1. Commande : Statut Paiement accepté
2. Affichage de la facture depuis le BO => elle est en anglais
3. Affichage de la facture reçue par le client en email  => elle est en anglais
4. Affichage de la facture par le compte du client  (Historique Commandes)  => elle est en anglais
Tout devrait être en français

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.0

### If your bug is related to a module, specify its name and its version

core ??

### Your company or customer's name goes here (if applicable).

Webalpina, le client est atelier-mahd.com site en développement

**Comment by AureRita** [comment]
Hi @Webalpina ,

Thank you for your report but can you send your request in English. English is the norm on GitHub.

Thank you

**Comment by xga91** [comment]
I confirm i have the same problem, all invoices are in english, and the shop is full French. whenever the language is, it seems it's always in english.

**Comment by jlores** [comment]
Hello,

In Spanish I have the same problem. The invoices is always in English

**Comment by florine2623** [comment]
Hello,

I reproduce the issue with PrestaShop version 8.0.4, 8.1.x and develop,  I'll add this to the backlog so it can be fixed.
It is a regression as it cannot be reproduced with 1.7.8.9.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Samx2222** [comment]
I have the same probleme.
Can I have a mail when this is ok ?
Thanks

**Comment by matks** [comment]
@Samx2222 You can click on "Subscribe" button on this issue to get notified about next messages ;)

**Comment by studioatable** [comment]
I have the same probleme...

**Comment by MatShir** [comment]
The issue is fixed on the next 8.1 (that should be released at the end of the month). If you want to fix it without upgrading, you can apply the changes by yourself from https://github.com/PrestaShop/PrestaShop/pull/32790/files

**Comment by studioatable** [comment]
> The issue is fixed on the next 8.1 (that should be released at the end of the month). If you want to fix it without upgrading, you can apply the changes by yourself from https://github.com/PrestaShop/PrestaShop/pull/32790/files


Good morning. This point concerns the PDS, but all customer emails/orders etc... on the prestashop 8.0.4 site remain in English. Have you found a solution please??
Thanks for sharing.

**Comment by MatShir** [comment]
2 options available for you: 
- Apply the fix from this PR https://github.com/PrestaShop/PrestaShop/pull/32790/files or [ask a technical help](https://www.prestashop-project.org/support/) to do it.
- Or wait the release of the 8.1 (minor version, it should simple upgrade from the 8.0.4), which would be released next week. To follow up the [release](https://github.com/PrestaShop/PrestaShop/issues/30719)

**Comment by Webalpina** [comment]
Yes, your solution works fine.

Thank you so much

 

Cordialement

 

Daniel JEAN

Webalpina

Création de sites Internet

587 route du Peray

74700 Cordon

www.webalpina.com <http://www.webalpina.com/> 

Tél. 06.32.58.50.31

 

De : Yvan GAPIN ***@***.***> 
Envoyé : lundi 19 juin 2023 15:00
À : PrestaShop/PrestaShop ***@***.***>
Cc : Webalpina ***@***.***>; Mention ***@***.***>
Objet : Re: [PrestaShop/PrestaShop] PDF files are always in English instead of shop language (Issue #32530)

 

The issue is fixed on the next 8.1 (that should be released at the end of the month). If you want to fix it without upgrading, you can apply the changes by yourself from https://github.com/PrestaShop/PrestaShop/pull/32790/files

Good morning. This point concerns the PDS, but all customer emails/orders etc... on the prestashop 8.0.4 site remain in English. Have you found a solution please??
Thanks for sharing.

**Comment by DanielBuisson** [comment]
Same problem in 8.1. this bug has not been corrected, the description of the problem is the same as at the start of this topic.

**Comment by MatShir** [comment]
This fix is included in the 8.0.5 :)
