### ISSUE TITLE
Error creating order when order amount is 0

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#32534]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If you try to make an order of 0 € applying cart rules, there's an error.

### Steps to reproduce

1. Create a cart rule of 100 €, for example
2. Make an order for a lower amount and try to finish it
![image](https://github.com/PrestaShop/PrestaShop/assets/15104724/ff7ef7d9-9708-485d-a67f-22ef4cd7f8cf)
3. Error
![image](https://github.com/PrestaShop/PrestaShop/assets/15104724/c42fe022-77cf-4da9-897b-855301ff01e3)

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.0.4

**Comment by AureRita** [comment]
Hi @idnovate 

Thank you for your report, I tried to reproduce your issue as you can see : 

[Untitled_ May 11, 2023 4_38 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/86eeb140-b300-477e-8fc9-178f6570c3d6)

But currently I can't, did I miss something ? 

Waiting for your feedback
