### ISSUE TITLE
Fatal error when placing an order Fatal error: Uncaught Error: Call to undefined method PDF::getFilename()

### ISSUE THREAD

**Issue by Rventura1989** [PrestaShop/PrestaShop#32541]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When finishing the order, regardless of whether the Bank Transfer payment method or external payment module is used, it gives an error:
**" Fatal error: Uncaught Error: Call to undefined method PDF::getFilename() in /home/papelar1/----/----/classes/order/OrderHistory.php:520 Stack trace: #0 /home/------/public_html/------/classes/order/OrderHistory.php(452): OrderHistoryCore->sendEmail(Object(Order), Array) #1 /home/------/public_html/------/classes/PaymentModule.php(575): OrderHistoryCore->addWithemail(true, Array) #2 /home/----/public_html/----/modules/ps_wirepayment/controllers/front/validation.php(63): PaymentModuleCore->validateOrder(2347, 10, 11.35, 'Payment by t...', NULL, Array, 1, false, '405e4bd97bce602...') #3 /home/----/public_html/-----/classes/controller/Controller.php(308): Ps_WirepaymentValidationModuleFrontController->postProcess() #4 /home/----/public_html/-----/classes/Dispatcher.php(510): ControllerCore->run() #5 /home/------/public_html/------/index.php(28): DispatcherCore->dispatch() #6 {main} thrown in /home/-----/public_html/------/classes/order/OrderHistory.php on line 520"**
In OR the order is placed normally and you can download the pdf of the invoice, but not send email to client

### Expected behavior

The placed order confirmation screen will be shown and an email will be sent to the customer.

### Steps to reproduce

1. add produts to cart
2. checkout
3. chosse the adress, payment, transporter
4. click in place order
5. the error appears (the above error transcript was taken with debug active, with debug inactive it gives error 500)

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_wirepayment v2.1.3

https://github.com/PrestaShop/PrestaShop/assets/95083228/df0db194-c63a-4c3d-a489-cdbd9a609f57

**Comment by alkorotkovas** [comment]
Hi @Rventura1989 ,

I had the same problem caused by Marketing with the Google module.
Can you confirm if the order goes through?

**Comment by Rventura1989** [comment]
Hello,
I have disabled the only module google that is installed, Google Analytics,
as well as disabled Recaptcha, however the error persists.

Atentamente,

**Comment by hibatallahAouadni** [comment]
Hello @Rventura1989 

Could you please disable all your overrides and switch your theme to CLASSIC, then check if the issue still persist 🙏 
Waiting for your feedback.

Thanks!

**Comment by Rventura1989** [comment]
Hello,
I disabled the overrides and switched to the Classic theme, cache clearing
and the issue still persist 😕



Thanks

Hibatallah Aouadni ***@***.***> escreveu no dia terça,
16/05/2023 à(s) 01:24:

**Comment by matks** [comment]
The PDF::getFilename() function is there in prestashop 8.0.4 https://github.com/PrestaShop/PrestaShop/blob/8.0.4/classes/pdf/PDF.php#L199

@Rventura1989 Can you verify if you have the same content for file classes/pdf/PDF.php ?

**Comment by Rventura1989** [comment]
Hi,

Yes, it is exactly the same content we have in our file.

Thank you very much




Atentamente,



P Antes de imprimir este documento, pense se é mesmo necessário. Para
produzir 1 tonelada de papel são necessárias 10 a 20 árvores, 10.000 litros
de água e 5 MWh de energia. A protecção do ambiente deve ser uma
preocupação de todos nós. Obrigada.

Esta mensagem e quaisquer ficheiros anexos podem incluir informação
privilegiada ou confidencial legalmente protegida, que só deve ser acedida
pela pessoa ou entidade a quem se dirige. Se a recebeu por erro,
solicitamos que o comunique ao remetente e a elimine, assim como qualquer
documento anexo. É estritamente proibido o uso, distribuição, cópia ou
qualquer forma de difusão não autorizada desta mensagem e respetivos
anexos. Qualquer opinião expressa nesta mensagem pertence unicamente ao
autor remetente e não representa, necessariamente, a opinião da Papelaria
Káká, a não ser que tal seja expressamente afirmado.


Mathieu Ferment ***@***.***> escreveu no dia quinta,
18/05/2023 à(s) 20:25:

**Comment by AureRita** [comment]
Hi @Rventura1989 

Did you have other payement module than  Payments by check -	 PrestaShop Checkout -	Wire payment ? 
Did you have module that are enable during the checkout ? 

Waiting for your feedback

**Comment by Rventura1989** [comment]
Hello,

We have bank transfer payment and two more active payment modules, these
not native, however the error happens in all of them.
We do not have any other modules active during checkout,

Thank you





AureRita ***@***.***> escreveu no dia sexta, 19/05/2023 à(s)
16:25:

**Comment by hibatallahAouadni** [comment]
Hello @Rventura1989 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a module problem.

We will close this issue.

Thanks!
