### ISSUE TITLE
The installation does not stop if there are commands with warnings

### ISSUE THREAD

**Issue by M0rgan01** [PrestaShop/PrestaShop#32547]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

During installation, a "prestashop:schema:update-without-foreign" command is executed. 

```
/**
     * cache:clear
     * assetic:dump
     * doctrine:schema:update.
     *
     * @return bool
     */
    public function updateSchema()
    {
        $schemaUpgrade = new UpgradeDatabase();
        $schemaUpgrade->addDoctrineSchemaUpdate();
        $output = $schemaUpgrade->execute();

        if (0 !== $output['prestashop:schema:update-without-foreign']['exitCode']) {
            $this->setError(explode("\n", $output['prestashop:schema:update-without-foreign']['output']));

            return false;
        }

        return true;
    }
```
We do not stop the installation if there are warnings in the command output

### Expected behavior

Stop the installation if warnings are in the result of the command, in development mode

### Steps to reproduce

1. Update `updateSchema()` method in `src/Install/Install.php` like this or place a breakpoint

```
    /**
     * cache:clear
     * assetic:dump
     * doctrine:schema:update.
     *
     * @return bool
     */
    public function updateSchema()
    {
        $schemaUpgrade = new UpgradeDatabase();
        $schemaUpgrade->addDoctrineSchemaUpdate();
        $output = $schemaUpgrade->execute();

        var_dump($output['prestashop:schema:update-without-foreign']['output']);

        if (0 !== $output['prestashop:schema:update-without-foreign']['exitCode']) {
            $this->setError(explode("\n", $output['prestashop:schema:update-without-foreign']['output']));

            return false;
        }

        return true;
    }
```

2. Install PrestaShop using the command line

`php install-dev/index_cli.php --step=database --domain=Toto --db_server=mysql --db_user=root --db_password=prestashop --country=us --firstname=toto --lastname=tata --password=Test123! --email=user@example.com`

3. The installation does not stop if warnings are in the result of the command

### PrestaShop version(s) where the bug happened

 1.7.8.9, 8.0.1

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment]
Hello @M0rgan01 

Thanks for reporting the issue!
Ping @PrestaShop/prestashop-core-developers  someone please try to reproduce the issue, it's too technical!

Thanks in advance!
