### ISSUE TITLE
Product registration: unable to update settings

### ISSUE THREAD

**Issue by ftrouve** [PrestaShop/PrestaShop#32553]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Good morning,

on prestashop 1.7.8.8 and also on another store 1.7.6.4, on some products that have many variations (42 or 48) registration is suddenly impossible. These products have been around for a long time but now impossible to make any changes. Error message: unable to update settings

I appealed to prestashop support via a purchase of credits but did not find a solution except for a message which indicated to increase the memory_limit, thing done but which does not solve the problem.
in browser/console I have this :
caught SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
    at Function.parse [as parseJSON] (<anonymous>)
    at Object.error (form.js?1.7.6.4:703:23)
    at u (main.bundle.js:253:90912)
    at Object.fireWith [as rejectWith] (main.bundle.js:253:91661)
    at n (main.bundle.js:253:127082)
    at XMLHttpRequest.<anonymous> (main.bundle.js:253:131927)
error @ form.js?1.7.6.4:703
u @ main.bundle.js:253
fireWith @ main.bundle.js:253
n @ main.bundle.js:253
(anonyme) @ main.bundle.js:253
load (asynchrone)
send @ main.bundle.js:253
ajax @ main.bundle.js:253
send @ form.js?1.7.6.4:651
(anonyme) @ form.js?1.7.6.4:845
dispatch @ main.bundle.js:253
_.handle @ main.bundle.js:253

message that I don't get when the file registration is ok

Thanks 

### Steps to reproduce

 Product registration

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.2

**Comment by hibatallahAouadni** [comment]
Hello @ftrouve 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must provide clear and concise steps to reproduce to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks
