### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by skyloic** [PrestaShop/PrestaShop#32561]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,
I have this error message that appears when I import products, has anyone ever had this problem?
THANKS.
![capture](https://github.com/PrestaShop/PrestaShop/assets/102284923/44ad7d78-142b-4fb6-893b-2aadff66dc8c)

### Steps to reproduce

importation

### PrestaShop version(s) where the bug happened

1.7.7.2

### PHP version(s) where the bug happened

7.3.33

**Comment by hibatallahAouadni** [comment]
Hello @skyloic 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must provide clear and concise steps to reproduce to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
