### ISSUE TITLE
Special characters are sent on the test email as html entities, and thus not parsed correctly.

### ISSUE THREAD

**Issue by edelmacias** [PrestaShop/PrestaShop#32564]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When sending a test email from the back office and using Spanish as the default language, the email will be received with html entities instead of actual special characters. Example:

Message received:
`Este es un mensaje de prueba. Tu servidor est&aacute; ahora configurado para enviar correo electr&oacute;nico. `

Instead of:
`Este es un mensaje de prueba. Tu servidor está ahora configurado para enviar correo electrónico. `

### Expected behavior

Email contains:
`Este es un mensaje de prueba. Tu servidor está ahora configurado para enviar correo electrónico.`

### Steps to reproduce

1. Set Spanish as the default language.
2. Configure emails.
3. Send a test email.
4. Receive the email and observe html entities instead of áéíóú.

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4.30

### Your company or customer's name goes here (if applicable).

Cubix Tech

**Comment by hibatallahAouadni** [comment]
Hello @edelmacias 

Your issue seems similar to this one #15469 could you please check it.
Waiting for your feedback.

Thanks!

**Comment by edelmacias** [comment]
It seems similar, and probably the same. I tried looking before but couldn't find something related. I hope the PR I sent can resolve both of the issues.

**Comment by djoelleuch** [comment]
Hello @edelmacias ,

Closing the issue as it is already in our debug backlog. This issue is a duplicate of  [#15469](https://github.com/PrestaShop/PrestaShop/issues/15469)


Thank you  !

**Comment by hibatallahAouadni** [comment]
Duplicate of #15469
