### ISSUE TITLE
Problem receiving customer and merchant order summary email

### ISSUE THREAD

**Issue by Pphasmes** [PrestaShop/PrestaShop#32565]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,
I am in the process of creating my site. I simulated commands. The customer does not receive the summary email of his order. Also I do not receive the order notification email. Can you help me please?
 THANKS

### Expected behavior

The customer should receive the summary of his order by email.
I should also be notified by email with each order.

### Steps to reproduce

Prestashop support

### PrestaShop version(s) where the bug happened

8.0.3

### Your company or customer's name goes here (if applicable).

planete-phasmes.com

**Comment by tesshsu** [comment]
Hi @Pphasmes 
Could you provide more your email setting configuration part ? You could verify testing SMTP if is working by follow step:

Go to "Advanced Parameters" > "E-mail".
In the "SMTP server" field, enter "smtp.gmail.com".
In the "SMTP user" field, enter your Gmail email address.
In the "SMTP password" field, enter your Gmail password.
In the "Encryption" field, select "TLS".
In the "Port" field, enter "587".
Click on the "Test your email configuration" button.
If the test is successful, you should see a message saying "Test email sent successfully". 

![1](https://github.com/PrestaShop/PrestaShop/assets/3927152/c739611c-acfa-4f54-8bcf-d7a458d5997b)
![2](https://github.com/PrestaShop/PrestaShop/assets/3927152/ed8042f3-60d7-4427-a7d4-a2bbd178f534)
![3](https://github.com/PrestaShop/PrestaShop/assets/3927152/88707c24-5d6c-4982-b9ad-7d92daabce10)


If not, check your settings and try again, hope this could help. tks

**Comment by Pphasmes** [comment]
It still does not work
[image: Email 2.JPG]
[image: Email 3.JPG]
[image: Email 1.JPG]

**Comment by hibatallahAouadni** [comment]
Hello @Pphasmes 

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you
