### ISSUE TITLE
Fix missing LegacyLink missing for 9.0.0

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#32576]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Release task

This is one of the last steps to do for 8.1.0 Release Candidate.

This ticket is about performing this step from the https://www.prestashop-project.org/maintainers-guide/processes/release/prestashop/preliminary-tasks/ process.

The Command `php bin/console prestashop:linter:legacy-link` helps us finding routes that do NOT have the [LegacyLink](https://devdocs.prestashop-project.org/8/modules/concepts/controllers/admin-controllers/tabs/#manual-tab-insertion) needed to match Symfony routes to legacy routes.

https://devdocs.prestashop-project.org/8/development/components/console/prestashop-linter-legacy-link/

For some routes that is expected: for example new routes (so they do not replace a legacy route, this is a new feature that was built directly in Symfony).

## What to do

It is necessary, to make sure 8.1.0 Release Candidate is secure, to go through the list that is the output of the Command, when run on `8.1.x` branch, and verify for each line whether the missing LegacyLink is normal or not.

**Comment by Zoefinders** [comment]
Once we will finish this EPIC, this ticket will be unblock:  https://github.com/PrestaShop/PrestaShop/issues/31231
