### ISSUE TITLE
Spike : doc - auto-generation ?

### ISSUE THREAD

**Issue by WahbiPS** [PrestaShop/PrestaShop#32581]
As a developer an easy way to document our endpoints so I can provide to other developers a good documentation  

## Description 

We need to know how to (auto)-generate documentation for an endpoint , including scope 

Doc examples : 
[github API Rest](https://docs.github.com/fr/rest/overview/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28#blocking)
[Slack API](https://api.slack.com/legacy/oauth-scopes)

## Attendees

- Documentation : how to (auto-generate) documentation for endpoint / scopes
- If not possible "AS IS" : TS ( technical stories ) to implement it

## Acceptance criterarias

- Lead Tech & PM validation

**Comment by jolelievre** [comment]
Based on the doc
https://api-platform.com/docs/v2.7/core/openapi/

- have a Swagger auto-generated doc that returns something similar to https://petstore.swagger.io/?_ga=2.230065113.494069494.1684246669-432785158.1684246669 fully dynamic
- see how we can detail the DTO with better comments for description, type, required or not
- see how we can integrate the scopes (maybe will have to rely on https://api-platform.com/docs/v2.7/core/openapi/#overriding-the-ui-template) (this part may be blocked until we know of we'll implement the scopes security)
