### ISSUE TITLE
Spike : Modularisation WebAPI

### ISSUE THREAD

**Issue by WahbiPS** [PrestaShop/PrestaShop#32582]
### Description 

Our current implementation does not support modularisation

We wish to know if we need to implement it for the MVP and how 

### Expected attendies

In doc : notion 

- List of risks for module implementation
- Status if is MUST be done for the MVP or later
- List of technical task to do and functional impact ( for example scope def / configuration ). The last one should be done with a PM

### Acceptances criterias 

- Lead Tech & PM validation

**Comment by jolelievre** [comment]
### Technical inputs

The idea is to externalize the configuration of API resources in a module. We follow the same principle modules' services, doctrine entities, routes, .... The module must follow a convention and add its root yaml file inside the folder `config/api_platform/resources.yml` (like how it's done in the Core)

Here are some example for the current existing features:
- [load services](https://github.com/PrestaShop/PrestaShop/blob/47d2daba6e140c36d2894092d8c4a3de0c39ab3c/src/PrestaShopBundle/DependencyInjection/Compiler/LoadServicesFromModulesPass.php#L68)
- [load doctrine entities](https://github.com/PrestaShop/PrestaShop/blob/30f717d045052e1c97a5596fd06c18d6a308d884/src/PrestaShopBundle/DependencyInjection/Compiler/ModulesDoctrineCompilerPass.php#L48)
- [load routes](https://github.com/PrestaShop/PrestaShop/blob/350f935eb557543ac38f878cbf4f510781c4b123/src/PrestaShopBundle/Routing/YamlModuleLoader.php#L57)

We need to find a similar principle, either by compiler pass or via an interface/tagged service that API Platform can load.
