### ISSUE TITLE
The group 'Visitors' is selected by default in customers list table

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#32583]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In 'BO > Customers > Customers' page, the gender 'Visitors' is selected by default in customers list table

![Customers-•-PrestaShop](https://github.com/PrestaShop/PrestaShop/assets/24647495/6122e842-909d-49a9-b912-587060c1f5bd)

### Expected behavior

The group should not be selected by default

![Capture d’écran de 2023-05-16 09-29-48](https://github.com/PrestaShop/PrestaShop/assets/24647495/69d1b97c-4d84-4aa4-9157-350fc7a85ff6)

### Steps to reproduce

1- Go to BO > CUstomers > Customers page
2- See the regression => The group visitor is selected by default in the table

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello @nesrineabdmouleh ,

I reproduce the issue with PrestaShop version 9.0.0 develop, I'll add this to the backlog so it can be fixed.

Related to https://github.com/PrestaShop/PrestaShop/pull/32370
Link to automated tests : https://github.com/florine2623/testing_pr/actions/runs/4989070343

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
