### ISSUE TITLE
Google Analytics (4.2.2) double count purchases in GA4 and has a NON-standard implementation

### ISSUE THREAD

**Issue by xrdm** [PrestaShop/PrestaShop#32588]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Google Analytics v4.2.2 base default module of Prestashop double counts purchase events.

![immagine](https://github.com/PrestaShop/PrestaShop/assets/9445033/26cd843a-0787-40f7-a88d-dc328ba28bff)

And on Google Tag Assistant it gives:
- Invalid or missing account ID (on alla pages)
- Non-standard implementation (on some pages)

![immagine](https://github.com/PrestaShop/PrestaShop/assets/9445033/926b42df-7089-42b0-80ac-d83c49f3bcc8)

### Steps to reproduce

- Istall module
- add GA4 id
- see that on GA4 the double count of purchases
- and see on Google Tag Assistant the messages for Invalid or missing account ID and/or Non-standard implementation.

### PrestaShop version(s) where the bug happened

1.7.5.2

### If your bug is related to a module, specify its name and its version

ps_googleanalytics 4.2.2

**Comment by hibatallahAouadni** [comment]
Hello @xrdm 

Thanks for reporting the issue and for your patience :pray: 
Did you encounter the issue only with ps_googleanalytics v4.2.2? or even with older version like v4.2.0?
Could you please share your configuration or provide a screen record? cause it seems I miss some steps as I didn't manage to reproduce :pray: 
Waiting for your feedback.

Thanks!

**Comment by xrdm** [comment]
Hello,
I started from 4.2.2 version of the module

![immagine](https://github.com/PrestaShop/PrestaShop/assets/9445033/dcb21ead-e9ba-468f-813c-20a31030623c)

**Comment by kpodemski** [comment]
cc @Hlavtox

**Comment by xrdm** [comment]
Hello,
any news?
thank you

**Comment by Hlavtox** [comment]
@xrdm Nothing like this is happening normally. 

Can you check if you are not hooking the module twice on confirmation page? Are you using some other tracking module?

Also, to check the script, use https://tagassistant.google.com/, not the legacy assistant.

**Comment by hibatallahAouadni** [comment]
Hello @xrdm 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
