### ISSUE TITLE
The templated used for "Updated PrestaShop Packages" PR is broken

### ISSUE THREAD

**Issue by nicosomb** [PrestaShop/PrestaShop#32585]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When Github Actions opens a new pull request to update PrestaShop packages, the template used to generate the description is broken. See https://github.com/PrestaShop/PrestaShop/pull/32580 for example. 

The file used by Github Actions to generate this content is here: https://github.com/PrestaShop/PrestaShop/blob/develop/.github/workflows/cron_update_modules/script.php

### Steps to reproduce

Open https://github.com/PrestaShop/PrestaShop/pull/32580

### PrestaShop version(s) where the bug happened

NA

### Your company or customer's name goes here (if applicable).

PrestaShop

**Comment by kpodemski** [comment]
It was fixed multiple-times, maybe it's because of the fact that we have a different template on different branches.

**Comment by florine2623** [comment]
Hello @nicosomb ,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by hibatallahAouadni** [comment]
@kpodemski I see that you validated the issue, could you please specify if it's a regression or not :pray:

**Comment by kpodemski** [comment]
@hibatallahAouadni it doesn't matter, it's not a software bug but internal tool

**Comment by RosaBenouamer** [comment]
@kpodemski is that issue linked to the PR https://github.com/PrestaShop/PrestaShop/pull/32690

**Comment by kpodemski** [comment]
@RosaBenouamer no, it is completely unrelated to the software, it's related to the tool we use on Github

**Comment by RosaBenouamer** [comment]
@kpodemski : my question is not on the godd issue :-( sorry

**Comment by kpodemski** [comment]
Doesn't work. Have to be updated on the 8.0.x branch. I already fixed it on the `develop` because it works correctly when updating modules for this branch.

Edit: I see that you submitted PR already. I'm gonna check this.

**Comment by kpodemski** [comment]
@tleon I checked, and it doesn't work, you should consider using the same template as on develop on 8.0.x https://github.com/PrestaShop/PrestaShop/pull/32765

**Comment by kpodemski** [comment]
@tleon it works after backporting changes from the develop branch :) 
https://github.com/PrestaShop/PrestaShop/pull/32784

thanks
