### ISSUE TITLE
Sales statistics

### ISSUE THREAD

**Issue by KaeligBrl** [PrestaShop/PrestaShop#32591]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Link photo 1: https://prnt.sc/eekEL4LOuwp-
Link photo 2: https://prnt.sc/9HF2zzT58Fgg

### Expected behavior

Good morning,

On my shop, I make sales but I don't have my conversion rate

I don't have my visitors online. I'm missing a lot of information and I don't understand.

Could you help me please.

I am attaching pictures.

I am french ;)

Best regards,

Kaëlig

### Steps to reproduce

Click On the board and on the statistics 

### PrestaShop version(s) where the bug happened

1.7.8.8

**Comment by florine2623** [comment]
Hello @KaeligShebam ,

I can't reproduce your issue on 1.7.8.9.
<img width="705" alt="Screenshot 2023-05-16 at 15 11 30"
 src="https://github.com/PrestaShop/PrestaShop/assets/16019289/d76695b3-f76c-4346-a064-ff608e335170">

<img width="1019" alt="Screenshot 2023-05-16 at 15 12 13" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/f8c17d61-b63b-445d-ba6a-5ca3d5bc6365">


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by KaeligBrl** [comment]
Hello, I have a problem on this version.

Are you sure this is the prestashop version?

**Comment by KaeligBrl** [comment]
Hello, 

i update the prestashop version but i have the same problem ;) do you have an solution please ?
