### ISSUE TITLE
Can't import combinations with Safari

### ISSUE THREAD

**Issue by NicolasCador** [PrestaShop/PrestaShop#32590]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,
when I try to import combinations with Safari, I get a warning "Two columns cannot have the same type of values" and can't import while there is not 2 columns with same type of value.
For example, with firefox, it works perfectly.
_Another abnormal behavior: if you don't put any column with "Attribute (Name:Type:Position)*", you don't have the warning (so it shows it's really that, with value "group", which doesn't work), but you can import while it should not due to the fact that "Attribute (Name:Type:Position)*" is mandatory.
I tried only with Combinations, but I think it will be the same with other things to import with an option having a value "group" in the select, like Customers_

https://github.com/PrestaShop/PrestaShop/assets/96910631/c68e97f4-331e-4b22-9dc0-108671abc908

For memory:
admin-dev/themes/default/template/controllers/import/helpers/view/view.tpl
controllers/admin/AdminImportController.php
js/admin/import.js

### Expected behavior

It should not show the warning "Two columns cannot have the same type of values", and import.

https://github.com/PrestaShop/PrestaShop/assets/96910631/184b7681-6967-42b6-bcfb-c0a416f7aeb0

### Steps to reproduce

1. Open Safari
2. Go to Prestashop admin
3. Go to import
4. choose combinations
5. select a file with combinations to import
6. click on "next step"
7. be sure you don't have any column with same type
8. click on "import"
9. A warning will appear: "Two columns cannot have the same type of values"

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
You have this error only if you are using the same columns for different element.
Can you send me the csv file you are using ?

I think the second video does not show everything, you canceled the action.

**Comment by NicolasCador** [comment]
Hi @florine2623,

the second video shows the import starts with firefox, then I aborted but the import has started while with Safari it never starts and shows a warning in yellow.

Yes I know this error should appear only if you put 2 (or more) same fields on several columns.
In this case, I didn't change any field on any column, so there is not 2 (or more) columns on several columns.
I can't send the file there are pricing data inside. But the file is useless because it doesn't manage anything for that. The check is managed by the select option on each column.

**Comment by AchrafKchaou1991** [comment]
Hello @NicolasCador 

I didn't manage to reproduce the issue with PS1789 and PS804, see the attached screenshot below:

PS1789:
![Capture d’écran du 2023-05-23 14-30-24](https://github.com/PrestaShop/PrestaShop/assets/131356155/744c523a-c7f7-4736-b579-e6fce4f03f40)

PS804:
![Capture d’écran du 2023-05-23 14-30-39](https://github.com/PrestaShop/PrestaShop/assets/131356155/1690f3ce-ddb6-4d41-8512-6353712e54d9)

I use this file to import combinations:
[combinations - Sheet1.csv](https://github.com/PrestaShop/PrestaShop/files/11544461/combinations.-.Sheet1.csv)

Please check and feedback.

Thanks!

**Comment by NicolasCador** [comment]
Hi @AchrafKchaou1991,

did you use Safari? I don't see in the screenshots.

I took your file, I updated it to put ; instead of , to separate the columns because , is between data of each column.
[combinations.-.Sheet1.csv](https://github.com/PrestaShop/PrestaShop/files/11573137/combinations.-.Sheet1.csv)

I have still the same behavior: I got a warning "Two columns cannot have the same type of values", and it didn't import


https://github.com/PrestaShop/PrestaShop/assets/96910631/565f1e37-12ca-4b00-ac76-58022efa5cbd

**Comment by hibatallahAouadni** [comment]
Hello @NicolasCador 

Thanks for your patience and your feedback.
Could you please provide all infos that could help us to reproduce the issue 🙏 

- Safari version
- Operating System
- Firefox version

Waiting for your feedback.

Thanks!

**Comment by NicolasCador** [comment]
Hello @hibatallahAouadni,

please find required data
<img width="933" alt="Versions" src="https://github.com/PrestaShop/PrestaShop/assets/96910631/c79ca2d9-f65c-49be-b055-c3ddbd543fda">

**Comment by hibatallahAouadni** [comment]
Hello @NicolasCador 

Thanks for your all feedback :pray: 
Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a third-party module problem.

We will close this issue.

Thanks!

**Comment by ceer** [comment]
Same problem with Safari 16.5 and PrestaShop 1.6.1
it looks like the first time the error was legit, then after file correction, the same error message always show off. It works in Chrome.
