### ISSUE TITLE
New Translations Do Not Appear

### ISSUE THREAD

**Issue by LuigiMdg** [PrestaShop/PrestaShop#32605]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Greetings,
I don't know if the problem has already been reported, however I made a copy of my ecommerce and made an attempt to update to _8.0.3_, so far so good, except for the fact that _PrestaShop_ no longer creates translations automatically. .!

With up to the 'old' _1.7.8.7_ it was enough for me to insert a simple `{l s='%s Stickers' d='Shop.Theme.Catalog'}` to find it among the translations, while now it doesn't appear even after having emptied the cache.. I checked the _ps_translations_ table and the _.xlf_ files but there is no trace of the new words.

I await your suggestions.

### Steps to reproduce

1. Open any _.tpl_ file
2. Add the code {l s='%s Stickers' d='Shop.Theme.Catalog'}

### PrestaShop version(s) where the bug happened

8.0.3

### PHP version(s) where the bug happened

7.4

**Comment by kpodemski** [comment]
Hello @LuigiMdg 

Which theme do you use? From what I've checked, if you use `classic`, new phrases are not automatically discovered. If I use `child_classic`, and add new phrases there, there are visible when I translate `child_classic`.

**Comment by LuigiMdg** [comment]
Hi @kpodemski, I'm using the classic theme but I don't understand the logic of this procedure.. Should I create a child theme with the exact same files and work on those?
By the way it doesn't work even using the translation of the module, is this another problem or does it refer to the same problem..?

**Comment by hibatallahAouadni** [comment]
Hello @LuigiMdg 

You can find the child theme attached here:

[child_classic.zip](https://github.com/PrestaShop/PrestaShop/files/11546792/child_classic.zip)

Check if you still encounter the issue and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @LuigiMdg 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
