### ISSUE TITLE
BO - A bad display on dashboard page 

### ISSUE THREAD

**Issue by AchrafKchaou1991** [PrestaShop/PrestaShop#32619]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After logging into the BO and each time you click on `the dashboard` using `debug mode`, a warning pop-up is displayed.

![Capture d’écran du 2023-05-18 07-59-50](https://github.com/PrestaShop/PrestaShop/assets/131356155/1e16b17c-7fcc-4a38-ad75-3d835951bca8)

### Expected behavior

The display of the BO, shall be without any warning.

### Steps to reproduce

1.Go to the `Advanced Parameters` > `Perfermance` > enable `Debug mode` > 
2.Click on `Dashboard` page and see error.

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

php 8.2

**Comment by Codencode** [comment]
Hi @AchrafKchaou1991,
Prestashop 8 does not currently support PHP 8.2.

https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/#php-compatibility-chart

**Comment by djoelleuch** [comment]
Hello @AchrafKchaou1991  ,

as @Codencode  said  ,prestashop 8 does not currently support PHP 8.2.

https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/#php-compatibility-chart .

We will close this issue.
 
Thank you
