### ISSUE TITLE
Database error upgrading from 8.03 to 8.04 [Error upgrading Doctrine schema]

### ISSUE THREAD

**Issue by 01Kuzma** [PrestaShop/PrestaShop#32610]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The second upgrade attempt failed on localhost.
I was trying to upgrade from 8.03 to 8.04 since the last was released, but it failed with DB upgrade.
Today I also made the attempt, the error log is simple:
```
Error during database upgrade. You may need to restore your database.
Error upgrading Doctrine schema
```
I'm attaching the screenshot:
![image](https://github.com/PrestaShop/PrestaShop/assets/569504/52b31155-f2fe-446f-a42d-10974aa4f6ad)

### Steps to reproduce

Start the upgrade process from 8.03 to 8.04 version

### PrestaShop version(s) where the bug happened

8.03, 8.04

### PHP version(s) where the bug happened

8.1

**Comment by paulnoelcholot** [comment]
Hello @01Kuzma,

I tried to reproduce this issue but as you can see, I can't: /var/www/html/.zip/prestashop_8.0.4+build.3.xml
/var/www/html/.zip/prestashop_8.0.4+build.3.zip

Did I miss something?

Thanks for your feedback

**Comment by 01Kuzma** [comment]
Hi @paulnoelcholot ,
what do you want to show me with the empty link?
`/var/www/html/.zip/prestashop_8.0.4+build.3.xml
/var/www/html/.zip/prestashop_8.0.4+build.3.zip`
P.S. MySql and Apache logs do not give more detailed information

**Comment by djoelleuch** [comment]
Hello @01Kuzma ,

Despite our efforts, we were not able to reproduce your issue with the provided information : 

[Untitled_ May 18 2023 5_14 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/67a395df-37b5-4fc8-9832-f64ecde8deea)


We will close this issue.

Thank you

**Comment by djoelleuch** [comment]
Hello @01Kuzma  ,

Despite our efforts, we were not able to reproduce your issue : 

[Untitled_ May 18 2023 5_31 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/e2e1025c-b256-4e69-b4fb-43bf41a6cf91)

We will close this issue.

Thank you
