### ISSUE TITLE
Unusually high memory usage, slow saving time

### ISSUE THREAD

**Issue by vipdpcolor** [PrestaShop/PrestaShop#32612]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

A couple of weeks ago I've noticed my Prestashop store's admin page was unusually slow, especially when adding new products. Today I sat down to debug this issue and noticed on our server's resource usage monitor (shared hosting) that apparently since ~18th of April we've been getting throttled by our hosting company. CPU usage related to databases was up to 200% from 1-2%. My immediate action was making a clone of the website and disabling all of the modules, which did not help. I've checked the logs but couldn't find anything out of the ordinary - no new errors, a lot of the old ones are just missing translations etc.
I've enabled the debug profiling mode and saw that memory peak usage values were reaching about 55-60mb, on some product pages even 160mb, which seems insane. I've also tried updating my store as I'm running an older version but that didn't seem to do anything either. We've always had slow saving times because our products have a lot of combinations and other small settings but it's unbearably slow right now. I'm a bit lost as to what should I try next - as disabling third party modules (manually and via the setting) did not do the trick I fear that it might be something related to Prestashop itself.

### Steps to reproduce

Does not apply, I'm attaching some screenshots instead:

![cpu usage](https://github.com/PrestaShop/PrestaShop/assets/61168103/57d7f9f6-80e0-4af4-9bfd-4a6e0599636c)
![product](https://github.com/PrestaShop/PrestaShop/assets/61168103/22a668a6-934e-4b45-a7a7-b5cf33ff6591)

### PrestaShop version(s) where the bug happened

1.7.6.4

### PHP version(s) where the bug happened

7.2.34

**Comment by djoelleuch** [comment]
Hello @frntdev 

Your issue is due to the enormous saved products, and as we don't fix the performance issues any more, please subscribe to this [discussion](https://github.com/PrestaShop/PrestaShop/discussions/31782), it may help to improve your store performance.

Thanks!
