### ISSUE TITLE
Glitch on Dashboard Stats v2.0.4 by PrestaShop

### ISSUE THREAD

**Issue by plutocrata** [PrestaShop/PrestaShop#32620]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello guys, the Dashboard Stats v2.0.4 by PrestaShop is not working since this month for an unknown reason.

It doesn't shows any sale and only shows the registrations - new accounts.

Since 16/05 is recording the visits too, but only in the last three days and ZERO sales, despite we have sales.

Of course period is correct.

Until 26/04 we could see the registrations and orders (no visits) and we only noticed because the sales didn't grow up at the dashboard, despite having sales.

### Expected behavior

Shows visitors, new account and of course orders!

<img width="1071" alt="Screenshot 2023-05-18 at 13 00 27" src="https://github.com/PrestaShop/PrestaShop/assets/133967971/892b9b25-68ae-4234-91d7-21fb1b981833">

### Steps to reproduce

Click on Dashboard

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4.33

### Your company or customer's name goes here (if applicable).

PrestaShop

**Comment by djoelleuch** [comment]
Hello @plutocrata ,

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must provide clear and concise steps to reproduce to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
