### ISSUE TITLE
Module ps_emailalerts - See the customers who have subscribed in admin

### ISSUE THREAD

**Issue by ytilotti** [PrestaShop/PrestaShop#32633]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

This module gives customers the possibility to know if a product is back in stock and to have an alert. How to see the customers and on which products these alerts have been made?

### Steps to reproduce

1. Go to front on a product out of stock
2. Click on "Notify me when available"
3. Add you email and send
4. Go to the admin with an admin account
5. How to see this subscriber?

### PrestaShop version(s) where the bug happened

all

### If your bug is related to a module, specify its name and its version

ps_emailalerts

**Comment by darkf3d3** [comment]
I'd like to see subscribers too. Actually the module it's very limited.

**Comment by hibatallahAouadni** [comment]
Hello @ytilotti 

Thanks for reporting the issue :pray: 
Could you please provide the module version, and did you encounter this issue with older version of this module?
Waiting for your feedback.

Thanks!

**Comment by ytilotti** [comment]
@hibatallahAouadni all the version. My version is 2.4.1

**Comment by hibatallahAouadni** [comment]
Hello @ytilotti 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #28233. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #28233
