### ISSUE TITLE
Removing an item from the cart is broken

### ISSUE THREAD

**Issue by M0rgan01** [PrestaShop/PrestaShop#32630]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Removing an item from the cart is broken in the FO. 
It is deleted but the display is not updated.

### Expected behavior

When clicking on the button, the article must disappear dynamically

### Steps to reproduce

1. Add item to cart
2. Go to cart details
3. Click on the delete article button

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

**Comment by AureRita** [comment]
Hi @M0rgan01 

Thank you for your report, I tried to reproduce your issue as you can see : 

[Untitled_ May 19 2023 5_35 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/0f693602-d479-4eab-ac57-e57ee1da66d2)

But I can't reproduce it, did I miss something ? 

Waiting for your feedback

**Comment by M0rgan01** [comment]
Hello ! I re-tested, on a fresh install, by emptying the cache on 2 different browsers and reinstalling the theme.
I confirm that the problem persists. @AureRita 
[simplescreenrecorder-2023-05-22_09.44.27.webm](https://github.com/PrestaShop/PrestaShop/assets/36233446/cb702f36-eb92-46db-b373-584161ed08c8)

**Comment by hibatallahAouadni** [comment]
Hello @M0rgan01 

I didn't manage to reproduce the issue, could you please provide us with more info ?
We need more details to understand how we can reproduce your issue:
- host
- server setup and configuration
- debug mode report
- PHP error logs
- apache error log
- Javascript console log
- did you encounter this issue with older version
- ...

You don't know how to get this information? Please read the following article: [How to create a bug report]
(http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

Thanks!

**Comment by M0rgan01** [comment]
Hello @hibatallahAouadni and thank you for the feedback :smiley: 

I will give you more informations:

1. The application runs with docker, using the image from the repository, without modification
2. I use the following command to have a fresh installation: 
```
git clean -dfx && \
docker compose down -v  && \
docker compose build --no-cache && \
docker compose up -d --force-recreate
```
4. No JS logs when clicking
5. PHP Warning -> `PHP Warning:  Undefined array key "id_manufacturer" in /var/www/html/classes/Product.php on line 5620, referer: http://localhost:8001/fr/panier?action=show`
6. I don't have the problem on the 8.0.x branch and on the 8.1.x branch
7. Here is a capture of the warning:

[screen-capture (1).webm](https://github.com/PrestaShop/PrestaShop/assets/36233446/fb5df1e2-dc1c-4a95-b99c-3f72716092ad)

**Comment by hibatallahAouadni** [comment]
Hello @M0rgan01 

Thanks for your feedback and the details 🚀 
Did you reproduce this issue with fresh install without creating any order with a brand then deleting the brand??
Cause I didn't manage to reproduce with fresh install on develop with PHP8 😞 
Please check and feedback.

Thanks!

**Comment by M0rgan01** [comment]
@hibatallahAouadni I did my tests by not touching the back office, I directly put something in the cart and tried to delete it, on the 8.0.x, 8.1.x and develop branches.

**Comment by tleon** [comment]
Hello I reproduced the issue on a fresh install not on docker ( local apache / mysql server ) with a cli install of the shop.

**Comment by M0rgan01** [comment]
@hibatallahAouadni @AureRita I think I know why you are not reproducing the bug. If the dev mode is not activated there is no problem. this is a "silent" bug in dev mode false. cc @boherm

**Comment by paulnoelcholot** [comment]
Hello @M0rgan01,

I reproduce the issue with PrestaShop version develop, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

https://watch.screencastify.com/v/sk8RG3CGWKwtmwHiUjgY

**Comment by WahbiPS** [comment]
related to [FO-Card content still displayed even deleted until you refresh the page#32889](https://github.com/PrestaShop/PrestaShop/issues/32889)

**Comment by Hlavtox** [comment]
@MatShir Changing severity, broken cart functionality is not a minor bug.

**Comment by M0rgan01** [comment]
PR: https://github.com/PrestaShop/PrestaShop/pull/33113
