### ISSUE TITLE
Overriding Carrier class Attempted to load class "RatesHelper"

### ISSUE THREAD

**Issue by kurollo** [PrestaShop/PrestaShop#32632]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

**Describe the bug**

After install Prestashop 8.0.4 on this environnement:

- Container docker PHP:8.1-FPM 
- Container Nginx 1.23
- Container Mysql 8.0 

When attempting to edit any product, an error 500 is encountered:

Attempted to load class "RatesHelper" from namespace "Prestashop\Module\Mbeshipping\Helper".
Did you forget a "use" statement for another namespace ?

![github_error](https://github.com/PrestaShop/PrestaShop/assets/7980607/b9f381da-f918-48ef-bbf2-ee765fa65eeb)

### Expected behavior

Instead of the error, I expected i can edit the product and the core of Prestashop will process the mechanism of Override of the class in question automatically without any problems.

### Steps to reproduce

1. Install Prestashop 8.0.4 on the same environment like me (as described in the bug report).
2. Enable debug mode.
3. Clear the cache.
4. Edit any product or add a product to the shopping basket and proceed to complete the order.

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

php:8.1-fpm

### If your bug is related to a module, specify its name and its version

Mbeshipping

**Comment by GreyShinbusan** [comment]
Same problem with 8.0.4

When I changed file name  override/classes/Carrier.php to override/classes/_Carrier.php (in other words I deactivated override)
editing and adding to the cart works properly. At least as I can see it.

**Comment by hibatallahAouadni** [comment]
Hello @kurollo 

It seems that your issue is not a PrestaShop core bug.
If your module is Mbeshipping Official, please contact support team on Addons

We will close this issue.

Thanks!

**Comment by kurollo** [comment]
Hello @hibatallahAouadni

I agree with you, but this module 'Mbeshipping' comes by default with Prestashop modules.

Thanks !

**Comment by benhmidafares01** [comment]
Hello @hibatallahAouadni 

I would like to clarify some information regarding the Mbeshipping Official module in PrestaShop 8.0.4.

Mbeshipping is a module that comes by default in the official PrestaShop 8.0.4 folder. Considering its presence within the core distribution, I believe it is essential to address the reported bug rather than dismissing it.

I kindly request that you either rectify the bug in the module or consider removing it from the PrestaShop core, as its current state affects the functionality and stability of the platform.

Thank you.

**Comment by kpodemski** [comment]
@benhmidafares01 it is distributed on a version that is not maintained by the project members, project distribution doesn't have this module by default 

as Hiba wrote, you should contact PrestaShop Marketplace support

**Comment by GreyShinbusan** [comment]
Wait, what? I downloaded it from Prestashop.com as a suggested distribution automaticly downloaded. As anyone else will. What do you mean you do not support it?!

**Comment by kpodemski** [comment]
@GreyShinbusan 

https://github.com/PrestaShop/ is part of the https://www.prestashop-project.org/, not https://prestashop.com/

https://prestashop.com/ release a version of PrestaShop, which is based on the open-source project core and includes some extra modules, a little different design, etc. Those are not identical versions, and the open-source project does not support the version from prestashop.com.

We are not maintainers of the MBE module, we don't know how it's been created, etc.

**Comment by GreyShinbusan** [comment]
Oh, ok, thank you.

**Comment by kurollo** [comment]
@kpodemski 

Everything is clear to me now, I will disable the override of this module.

Thanks.

**Comment by faresbenhmida** [comment]
Hello @kpodemski,

Thanks for the detailed explanations you provided. Your response was much clearer than the one from @hibatallahAouadni. I appreciate your clarification regarding the distinction between the open-source project core and the version released by prestashop.com.

**Comment by GrilladeSurCharbon** [comment]
Hi there, 

I find a solution about your problem who was my problem too.

I delete new module for MBA and it works again !

**Comment by GrilladeSurCharbon** [comment]
Hi everyone,

I've got the same problem few days ago and here is how I solve this error.

I delete this 
![image](https://github.com/PrestaShop/PrestaShop/assets/17316641/48ac762a-7261-47d3-b713-5cfea45fd987)

It's work perfectly after clear cache and delete this module !
