### ISSUE TITLE
Spike : list of changes to do for contexts

### ISSUE THREAD

**Issue by fabienvallon** [PrestaShop/PrestaShop#32641]
As a developer I want to have the list of all changes I should make to migrate to the new Context class so I can create Technical stories and refine the Context migration 

The most important ones are all the usage of `LegacyContext` in the modern code, and especially when it's used in the service definition in the yaml. All the usage in yaml MUST be modified, instead the appropriate service will have to be injected and the data will be fetched right on time on runtime. Then all usage inside the code (when LegacyContext is injected and not used in YAML) is the second priority.

We still don't know with what we'll replace the legacy context, either a new cleaner generic Context that allows access to the same thing OR multiple sub contexts. So in all cases we should identify for each usage with sub scope is related (employee, language, shop, ...) and provide a categorized list for each scope.

## Description 

- List all changes for Context ( notion )
- Create TS / Epic for it 

## Acceptances criterias

Review by tech lead & PM

**Comment by WahbiPS** [comment]
Already discussed with @jolelievre
