### ISSUE TITLE
double tags in template code

### ISSUE THREAD

**Issue by ERGBET** [PrestaShop/PrestaShop#32647]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The company that positions our store sent us a message that they need to fix errors in the code of the presta store template because it negatively affects its functioning. I am posting a message from them below:

while working on the website, a problem was found in the structure of the website. The <html>, </html> and </body> tags are doubled in the code and this is a bug. Double-placed tags may cause errors with the display and proper functioning of the page on different devices or browsers. More importantly, such errors can negatively affect the positioning process of such a site, because Google robots will have a problem with correctly reading the content of the page. As a consequence, algorithms may evaluate such a website worse, and this translates into, among others, to a decline in results.

These tags can be seen in the website code, e.g. view-source: https://sklep.ergbet.com.pl/13-tasmy-z-nadrukiem

Ruler no. 447 - first closing </body>

Ruler no. 448 - first closing </html>

Ruler no. 2313 - second </body> closure

Ruler no. 2315 - second closing </html>

### Steps to reproduce

The IT specialist who created this page for us claims that over 3 million stores based on free templates contain these errors and it does not affect the work or positioning of the store, and fixing the error is pointless because after the update everything will come back.

Please let me know which company is right

### PrestaShop version(s) where the bug happened

1.7.8.8

**Comment by hibatallahAouadni** [comment]
Hello @ERGBET 

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://prestashop.slack.com).

Thank you

**Comment by ERGBET** [comment]
Dzień Dobry,


This is a problem. I wrote to support of Presta and they said:
The problem that you reported does not fall within the scope of Prestashop Support.
 You must therefore create a ticket on Github from this link:
 
- https://github.com/PrestaShop/PrestaShop/issues 
 
 
I only need know that really double tags (<html>, </html> i </body> ) in template code
can affect the work and positioning of the store. 
 
The company positioning our store says yes and wants to improve it for a fee. 
And the IT specialist who created this store says that all stores around the world have these tags and it does not affect the operation and positioning of the store.
 
Pozdrawiam serdecznie
Weronika Bednarska
______________________________________
ERG-BET Taśmy samoprzylepne z nadrukiem · folia stretch
NIP 6291774286  · BDO 000351699
  Wypoczynkowa 8, 42-520 Dąbrowa Górnicza 
   pon-czw 7.00-16.00 · pt 7.00-15.00
   32 261-79-97 · 32 260-56-47 · mobile ***@***.*** 
 

Szanujemy Państwa prywatność dlatego starannie zabezpieczamy dane osobowe. Sposób w jaki przetwarzamy dane osobowe jest zgodny z aktualnym rozporządzeniem Parlamentu Europejskiego i Rady (UE) 2016/679 z dnia 27 kwietnia 2016 r. w sprawie ochrony osób fizycznych w związku z przetwarzaniem danych osobowych i w sprawie swobodnego przepływu takich danych. Administratorem Państwa danych osobowych jest : Erg-Bet Grzegorz Łoboda .Osobie, której dane dotyczą, przysługuje prawo dostępu do treści danych, żądania ich sprostowania, usunięcia, ograniczenia przetwarzania, prawo wniesienia sprzeciwu względem przetwarzania danych, prawo do przenoszenia danych oraz prawo wniesienia skargi do Prezesa Urzędu Ochrony Danych Osobowych.
Niniejsza korespondencja przeznaczona jest wyłącznie do osoby/podmiotu, do którego jest zaadresowana i może zawierać treść o charakterze poufnym lub zastrzeżonym. Wgląd w treść e-maila, dalsze jego przekazywanie, rozpowszechnianie lub innego rodzaju wykorzystanie przez osobę/podmiot niebędący jego adresatem, jest niedozwolone. Jeżeli niniejsza korespondencja trafiła do Państwa omyłkowo, proszę o zawiadomienie o tym na adres zwrotny i usunięcie wiadomości z komputera.
W liście datowanym środa, 24 maja 2023 (17:37:10) napisano:
