### ISSUE TITLE
symfony/property-access

### ISSUE THREAD

**Issue by fabienvallon** [PrestaShop/PrestaShop#32648]
As a developer I want to have framework up2date so : 
- I have a secure plateform
- New features 
- more performant prlateform in some case

## Description 

Upgrade [symfony/property-access](https://packagist.org/packages/symfony/property-access) to,  at least, 6.2.8 version.

See also : 
[frameworks - PHP dependancies](https://www.notion.so/prestashopcorp/Les-cons-quence-en-fonction-des-versions-de-PHP-support-es-5fa9b7e6654a495cbcbbf86cb82fee91)
and 
[dependencies](https://miro.com/app/board/uXjVMMFa4_Y=/?share_link_id=447161604159)

## AT

PS should work (ISO) with the 6.2.8 version of symfony/property-access

**Comment by WahbiPS** [comment]
Already aligned with Symfony 5.4
