### ISSUE TITLE
Customer group checkbox has an empty value and has been changed to select2

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#32655]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Customer default group has an empty value in the list.
![Bez názvu](https://github.com/PrestaShop/PrestaShop/assets/6097524/de08c8dd-1932-4301-95f5-a2368a5712f9)

Also, should it be a normal select or a select2? In 1.7.6 - normal select, 8.1.x - select2

### Steps to reproduce

1. BO > Customers > edit any customer
2. See default group selectbox.

### PrestaShop version(s) where the bug happened

develop

**Comment by Hlavtox** [comment]
Ping @M0rgan01 - do you think it has the same solution as your PR in https://github.com/PrestaShop/PrestaShop/pull/32589 🙏

**Comment by M0rgan01** [comment]
Well seen :) An option was missing
