### ISSUE TITLE
Official GDPR compliance v2.0.0 - PS 8.0.4 - php 8.0.28  error 500

### ISSUE THREAD

**Issue by giasemis** [PrestaShop/PrestaShop#32681]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello 
I use Prestashop 8.0.4 and php 8.0.28 fresh install.

When I press configure on Official GDPR compliance I receive server error 500.

Enable the debug and I receive the following error

An exception occurred while executing 'SELECT * FROM ps_psgdpr_log l':

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxxxxnew_xxxx.ps_psgdpr_log' doesn't exist

### Steps to reproduce

1. Go on backoffice > modules
2. Find module  Official GDPR compliance   
3.  click configure

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.0.28

### If your bug is related to a module, specify its name and its version

Official GDPR compliance v2.0.0 - by PrestaShop

**Comment by giasemis** [comment]
dublicate with issue #32148

**Comment by hibatallahAouadni** [comment]
Duplicate of #32138
