### ISSUE TITLE
[BO] : Error notification displayed in Multistore page 

### ISSUE THREAD

**Issue by sallemiines** [PrestaShop/PrestaShop#32680]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After installing the PS 810 RC version and activating the multistore option, go to the multistore page, an error notification is displayed

### Expected behavior

No error or exception should be visble 

### Steps to reproduce

1. Enable MultiStore 
2. Go to MultiStore Page 
3. See the Error 

The result With PS PS 810-rc , PS 81x  
![image](https://github.com/PrestaShop/PrestaShop/assets/31663369/a20a38f9-93b8-41f0-b1c8-ef0bc3edb1be)

The result with Develop 

![image](https://github.com/PrestaShop/PrestaShop/assets/31663369/5350d08a-cc13-4b0d-aec7-c54b845bf45b)

### PrestaShop version(s) where the bug happened

PS 810-rc , PS 81x 

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @sallemiines 

I was able to reproduce the issue with PrestaShop version 8.0.4, 8.1.x and develop.
It's a regression! as I didn't reproduce with PS802 :tada: 
I’ll add this to the debug backlog so that it’s fixed.

Thank you

**Comment by RosaBenouamer** [comment]
@hibatallahAouadni if we close the popup does the multishop works correctly or does this message implicate some consequences ?

**Comment by hibatallahAouadni** [comment]
Hello @RosaBenouamer 

Indeed when we close the popup, the page works perfectly!

Thnaks!

**Comment by RosaBenouamer** [comment]
@hibatallahAouadni thank you for your feed back !

**Comment by RosaBenouamer** [comment]
Looks like this error [32654](https://github.com/PrestaShop/PrestaShop/issues/32654)
