### ISSUE TITLE
Webshop shows price without tax on first load in FireFox

### ISSUE THREAD

**Issue by thetestspecimen** [PrestaShop/PrestaShop#32684]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The webshop is set to include tax in the frontend. However, when the site is initially loaded it shows the prices without tax when Firefox is used as the browser. 

This does not occur in either chrome or edge.

### Examples

This happens both on the home page:

https://github.com/PrestaShop/PrestaShop/assets/40262729/c83dbd21-992a-45b0-ba00-f6c9678cbdb1

...and the product and category pages (product page as an example):

https://github.com/PrestaShop/PrestaShop/assets/40262729/90156e6c-d0ed-4aa7-8c1d-fb34fb44d689

### Fresh install

The site in the videos is a brand new fresh install specifically for this test. No themes or modules have been added, and no adjustments have been made in the backend.

### Tested on

I have tested the behaviour on:

Windows 11 chrome: loads with tax
**Windows 11 firefox (version 113.0.2): loads without tax** 
Windows 11 edge: loads with tax

Windows 10 chrome: loads with tax
**Windows 10 firefox  (version 113.0.2): loads without tax**
Windows 10 edge: loads with tax

Linux Manjaro chrome: loads with tax
**Linux Manjaro firefox (version 113.0): loads without tax**

Android 13 chrome: loads with tax
Android 13 firefox: loads with tax

I have also seen the same behaviour on Firefox 112.x so this is not just a Firefox 113.x issue.

### Other notes

There was a previous (but now closed issue) of exactly the same thing for Prestashop 1.7:

https://github.com/PrestaShop/PrestaShop/issues/20227

I have no idea whether that issue was resolved, but I have previously used Prestashop 1.7 and don't remember having this issue. 

If the problem above was solved then perhaps it is a similar issue and can easily be remedied?

### Expected behavior

I would expect all prices to be displayed with tax included on first page load in Firefox.

### Steps to reproduce

1. Open a private browser window in firefox
2. Go to https://teststore.patsavouras.com
3. Make a mental note of the prices
4. Refresh the page
5. The prices will now update to include tax

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.1

**Comment by hibatallahAouadni** [comment]
Hello @thetestspecimen 

What do you mean by `Make a mental note of the prices` ? :thinking: 
Waiting for your feedback.

Thanks!

**Comment by thetestspecimen** [comment]
Hi @hibatallahAouadni 

It literally just means "Remember the value of the prices" or "Keep the value of the prices in your memory"

The point being that the prices are about to change from "without tax" to "with tax" when you press the refresh button, so pay attention to the value displayed before you hit refresh.

Apologies for any confusion.

**Comment by AureRita** [comment]
Hello @thetestspecimen 

Thank you for your report, 

I tried to reproduce your issue as you can see : 

[Uploading Untitled_ Jun 2, 2023 3_03 PM.webm…]()

I tried from firefox (v113.0.1)  and with a linux ( I didn't have computer with windows to test this ) 
I also tried from a new shop and I don't reproduce it, 

did you have more information to reproduce this issue ? 

waiting for your feedback

**Comment by thetestspecimen** [comment]
Hello @AureRita 

I can't see the video you linked. When clicked it just reverts to this page?

Any chance you can re-upload it so I can see?

**Comment by AureRita** [comment]
Yes, indeed, sorry for that, I think the video is already uploaded 

[Untitled_ Jun 2, 2023 3_03 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/9b9f3e4b-a6b8-43cd-9d3c-e12226cc98e7)

**Comment by thetestspecimen** [comment]
@AureRita OK thank you for re-uploading.

I went away and did a little testing.

Just to be absolutely sure my server setup isn't the problem I setup a local dev environment using XAMPP on PHP 8.1, and I still get the same problem (see video):


https://github.com/PrestaShop/PrestaShop/assets/40262729/34c9ffa5-dafb-4d01-abcf-b8cfd93ca8c1

Again this is a clean setup. The only thing worth mentioning is that during setup I use the country "Greece" which will then cause the install to include a second language (Greek), so you can see the URL it defaults to ends in "/en" for English. Not sure if this is relevant, but thought I would mention it.

In terms of where we go from here. I notice in your video you finish the install and then click to go straight to your shop in the same browser instance. What I would like you to try is:

1. Finish your install (preferably with Greece as the "Country" in the setup)
2. Close all FireFox browsers
3. Open a "Private browsing" FireFox instance
4. Go to the main Presta domain you setup
5. See whether you now replicate the problem?

**Comment by djoelleuch** [comment]
Hello @thetestspecimen ,

Despite our efforts, we were not able to reproduce your issue with the provided information as you can see below :  

[Untitled_ Jun 8, 2023 5_50 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/17cdd3f9-9c13-446b-a468-de88b4ffb0ce)

We will close this issue.

Thank you!
