### ISSUE TITLE
[BO] : PPV2 Multistore - Checkbox button displayed twice  

### ISSUE THREAD

**Issue by sallemiines** [PrestaShop/PrestaShop#32683]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When enabling the option Multistore , and PPV2 is enabled ,  in the page create product the checkbox **Apply changes to all stores** displayed twice .

### Expected behavior

A single display for the checkbox Apply changes to all stores

**PS 804** 

https://github.com/PrestaShop/PrestaShop/assets/31663369/4b55591f-d219-48d1-84c8-31deb04eef39

### Steps to reproduce

1. Enable Multistore 
2. Enable PPV2 
3. Go to products page > add new product 
4. The checkbox **Apply changes to all stores** displayed twice 

https://github.com/PrestaShop/PrestaShop/assets/31663369/fe4c5038-fa01-477a-af9c-816a9f63500d

### PrestaShop version(s) where the bug happened

PS 810-rc , PS81x

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @sallemiines 

I think this is the new expected behavior 🤔 
Ping @PrestaShop/product-team could you please confirm the new checkbox button under offline/online switch button is a new feature or a bug?

Thanks in advance 🙏

**Comment by RosaBenouamer** [comment]
@hibatallahAouadni why a new features whereas it's twice the same checkbox ?

@Mateus : do you agree it's a bug ?

**Comment by Codencode** [comment]
In my opinion it's not a bug, in fact the "Apply changes to all stores" checkbox appears for each field that is updated.
If you modify any other field, for example "Summary" or "Description" the "Apply changes to all stores" checkbox appears after each modified field.


https://github.com/PrestaShop/PrestaShop/assets/2463965/902fc8e0-a782-4143-afef-735d1b4ba5ea

**Comment by kpodemski** [comment]
It is not a bug, every single field that can be populated differently across the stores has this checkbox.

**Comment by MatShir** [comment]
@Codencode +1 and @kpodemski +1

**Comment by MatShir** [comment]
It is the expected behavior :)
