### ISSUE TITLE
ps_emailalerts: The latest version gives error 500 if subscribing to an out of stock alert as guest

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#32685]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When subscribing to an out of stock alert as guest, I don't get a confirmation.
When looking into the dev console, I notice an error 500 on the request `/module/ps_emailalerts/actions?process=add`

In the logs I get an error 
```
PrestaShopException /classes/ObjectModel.php in ObjectModelCore::validateFields
La propriété MailAlert-&gt;id_customer est vide.
```

The breaking change happened here: 
https://github.com/PrestaShop/ps_emailalerts/commit/e96355bd033f12dbdb593dce24a3a3be9c5343f9#r114775403

### Expected behavior

I expect that the functionality of out of stock notifications is working for guests

### Steps to reproduce

1. Activate `Product avaliability` in the BO in module ps_emailalerts
2. Navigate to a product that is out of stock
3. Hit F12 in Chrome to display dev console
4. Subscribe to get an alert when the product is available
5. Notice that
    - You do not get the subscription confirmaiton
    - In Dev console you see an error 500 on the request `/module/ps_emailalerts/actions?process=add`

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.0

### If your bug is related to a module, specify its name and its version

ps_emailalerts 2.4.1

### Your company or customer's name goes here (if applicable).

Société Biblique de Genève

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Nice catch :rocket: it's a regression on ps_emailalerts v2.4.1
And thanks for your PR :pray: I'll add to the backlog.

Thanks!

**Comment by SA-full-stack-developer** [comment]
Good Morning,

this error occurs in /classes/ObjectModel.php in function getFields() in call $this->validateFields(); this call does not exist inside the object or class, if it is commented out it works, there must be some related error.

**Comment by jooim12** [comment]
Hi

I have the same problem
Prestashop 8.0.4, PHP 7.3

You do not get the subscription confirmaiton
In Dev console you see an error 500 on the request /module/ps_emailalerts/actions?process=add
Chrome is reporting an error in the developer console.  /themes/core.js:37

s.send(e.hasContent && e.data || null)

**Comment by Hlavtox** [comment]
@hibatallahAouadni Fixed by https://github.com/PrestaShop/ps_emailalerts/pull/127

**Comment by hibatallahAouadni** [comment]
Glad to hear :tada: let's close this issue when the ps_emailalerts v2.4.2 will be released

**Comment by ShaiMagal** [comment]
> Glad to hear 🎉 let's close this issue when the ps_emailalerts v2.4.2 will be released

When will ps_emailalers 2.4.2. release date? This should be release ASAP, because it's global problem for e-shop owners :)

**Comment by Hlavtox** [comment]
@ShaiMagal https://github.com/PrestaShop/ps_emailalerts/releases/tag/v2.4.2

**Comment by lmeyer1** [comment]
Thanks @Hlavtox
Finally! I waited for this since the last release in March !
