### ISSUE TITLE
Improvement of Feature Flags

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#32698]
We want to improve the feature flags and allow storing them in different places (other than DB).

### Introduce type of feature flag

Add `type` column that indicates where the feature flag is used (this represents the order of priorities as well):

- `env` (from server/php config)
- `DotEnv` (from .env file at the root of the project)
- `db` (like it's done right now)

This column can have multiple values separated by a comma, it will then be exploded by the repository to know where it needs to find the data respecting the hierarchy defined above.

### As an env variable

Via `getenv` we can check if the value has been forced/set directly in the environment, the BO page must show the feature flag with the switch adapted with this value. But it should be disabled and have a help message indicating that it cannot be edited because the value was forced by env.

Idea1: to do so we add an option `forced_by_env` on `FeatureFlagType`, when the option is enabled the widget of this form type can add the extra help message.

Idea2: add a `type` field in `FeatureFlagType` that indicate which "storage" was used (db, env or DotEnv)

Idea3: Change the display of the form to display more like a table

### DotEnv variable

DotEnv must be implemented in FO and BO (should be done in the PR for container in FO not this one). This value has stronger priority to the DB value, but it can be edited from the BO (we use sed/reprint of the .env file to dynamize this value).

### DB value

This one doesn't change, however the FeatureFlagRepository should ignore it in case env or DotEnv value is set.

**Comment by matks** [comment]
@jolelievre As the feature flag system continues to evolve, could you check https://github.com/PrestaShop/PrestaShop/issues/23235
- close issues which are not relevant anymore as "won't do"
- include this issue in the EPIC 😉
