### ISSUE TITLE
BugFix for the module updater

### ISSUE THREAD

**Issue by madef** [PrestaShop/PrestaShop#327]
Hi,

I see a BIG problem on the module updater. The module are not updated because of a bug with a line on module's class : $this->database_version = $this->version;

This line was add in the fix https://github.com/PrestaShop/PrestaShop/commit/27eaed42bd7abe598a9baafeda04bb3c0ff221e4, but it makes a huge bug : the module is to the new version before the update script was loaded.

Removing this line must fix the problem

**Comment by marionf** [comment]
Hello, 
This issue is old, so I close it.
If you still have it on the last version (PrestaShop 1.7.4.2), please open a new one.
Regards
