### ISSUE TITLE
8.1.0 (Demo shop) - Pages Configuration & Advanced Configuration pages broken

### ISSUE THREAD

**Issue by l-delin** [PrestaShop/PrestaShop#32705]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

The `Pages Configuration` & `Advanced Configuration` pages seem broken on a PS 8.1.0. I use a demo store through MyDemoShop. Note that I couldn't reproduce the bug on PS 8.0.4 on a demo store.

In 8.1.0, the bug could **not** be reproduced on a local store -- @AureRita tested it for the QA.

See:

https://github.com/PrestaShop/PrestaShop/assets/113511191/5a70809c-3a22-46b5-be08-3a59b7aab18d

### Expected behavior

The two pages should open correctly.

### Steps to reproduce

1. Go to **Design > Theme & Logo**
2. Try to open the **Pages Configuration** page
3. Try to open the **Advanced Customization** page
4. See if either of these two pages work.

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.1.7

**Comment by hibatallahAouadni** [comment]
Hello @l-delin 

I didn't manage to reproduce the issue with PS810 and PS81x, see the attached screen record below:

[issue_32705.webm](https://github.com/PrestaShop/PrestaShop/assets/23308427/46125acf-b698-480d-a081-f14b1ebcc285)

Please check and feedback.

Thanks!

**Comment by l-delin** [comment]
Hello @hibatallahAouadni, There isn't much more info I can give you about this store apart from this 😖 Note that this is a demo store, I was only able to reproduce the issue on demo stores
<img width="197" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/113511191/e0c5a4af-be55-4c9a-9c6f-d5770bd8f0fc">

**Comment by sallemiines** [comment]
Hello @l-delin

unfortunately  didn't manage to reproduce the issue with PS810 and PS81x 

We will close this issue .
