### ISSUE TITLE
Deleting an attached file from the webservice API does not work

### ISSUE THREAD

**Issue by olecorre** [PrestaShop/PrestaShop#32700]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

There is an apparent subtlety, namely that :
{url}/api/attachments/1 => work on the DB model in the products_attachment table
{url}/api/attachments/file/1 => allows binary operations on the file itself

I delete an attachment from the API, so I send a DELETE request to https://mywebsite/api/attachments/file/1
The API answers 200, I check with Postman... And the file is still there

### Expected behavior

 I send a DELETE request to https://mywebsite/api/attachments/file/1
 the file with id_attachment = 1 must be delete

### Steps to reproduce

Since 1.7.8
Add a attachment file and use API for delete it
I send a DELETE request to https://mywebsite/api/attachments/file/1

### PrestaShop version(s) where the bug happened

since 1.7.8

**Comment by hibatallahAouadni** [comment]
Hello @olecorre 

AFAIK, this issue has been fixed with PS800, check this [comment](https://github.com/PrestaShop/PrestaShop/issues/28748#issuecomment-1246948865) .
Could you please check if you still encounter the issue after upgrading your shop to 8.0.4 :pray: 
Wairting for your feedback.

Thanks!

**Comment by olecorre** [comment]
my test was done on a 1.7.8 and the code is still the same on the develop version.
See my PR https://github.com/PrestaShop/PrestaShop/pull/32701

**Comment by kpodemski** [comment]
@hibatallahAouadni mentioned issue was a bit different, I think @olecorre is right here

**Comment by paulnoelcholot** [comment]
Hello @olecorre ,

I reproduce the issue with PrestaShop version 1.7.8.0, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by olecorre** [comment]
thank @paulnoelcholot, i am a developer and i have create a PR https://github.com/PrestaShop/PrestaShop/pull/32701

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/32701
