### ISSUE TITLE
BO - A bad display of alert success update  

### ISSUE THREAD

**Issue by djoelleuch** [PrestaShop/PrestaShop#32716]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

when you edit a combination  , the green alert is bad displayed .

### Expected behavior

![image](https://github.com/PrestaShop/PrestaShop/assets/115152460/31029c37-8884-4f27-a4f4-80fb553f9532)

### Steps to reproduce

1. Go to Catalog > Products> create a product with combination 
2. Edit the first one > ex : change the quantity of combination > click on save > **SEE THE ALERT MESSAGE IS BAD DISPLAYED**

![image](https://github.com/PrestaShop/PrestaShop/assets/115152460/d7081dfe-9293-4028-9cce-fa2dc8641a11)

### PrestaShop version(s) where the bug happened

PS 8.1.x / PS 810-rc / develop

### PHP version(s) where the bug happened

8.1

**Comment by hibatallahAouadni** [comment]
Regression on 8.1.0 :rocket:

**Comment by boherm** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/33120
