### ISSUE TITLE
Product microdata problems with application/ld+json solution

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#32728]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
now I have better checked the application/ld+json solution used for the microdata of the individual products, the one present in the product-jsonld.tpl file

in my opinion it presents problems when the product has combinations.
$product.reference
$product.mpn
$product.ean13
$product.upc
$product.id

here it only provides data related to the generic product and not to the combination selected on the page.
many enter references, ean codes only in the combination and not in the product option section, so no information would come out here

if the data relating to the combinations are sent to google merchant center, the id codes would become type product id - combination id
or the reference of the combinations, so there would be no match with the checks made for example by google merchant center when it check the website. Same problem when product reviews are released to google, where they are reported on combinations.
the combinations, the marketplaces and price comparison sites, consider them as separate products.

in my opinion this solution is not correct when the product has combinations on the page

![2](https://github.com/PrestaShop/PrestaShop/assets/653230/915fd735-83bf-48d0-aae7-2b11ac2f1c97)

bye

### Steps to reproduce

there are not step, it is necessary to check this file

product-jsonld.tpl

### PrestaShop version(s) where the bug happened

1.7.8.9 and 8

### PHP version(s) where the bug happened

7.4

### Your company or customer's name goes here (if applicable).

maofree

**Comment by AureRita** [comment]
Hi @maofree 

Thank for your report,
This issue is too technical for me, ping @PrestaShop/prestashop-maintainers , can someone please reproduce this issue ? 

Thanks

**Comment by hibatallahAouadni** [comment]
Hello @maofree 

Do you still encounter the issue with 8.1.x? Please check and feedback.

Thanks!

**Comment by Maofree** [comment]
Hi
yes

**Comment by kpodemski** [comment]
I've never encountered any issues with this. Did you @maofree? I don't recall any reports from GMC center saying that structured data is incorrect.

**Comment by Maofree** [comment]
Hi
let's take as an example a product that has combinations.
with this method, it can be seen that it always refers to the generic product and not to the combination in question.

For example, google shopping is passed the products including combinations with different references for each combination and these combinations are treated as if they were an independent product. I think there may be some problems when they do checks on the product page since they don't find the same references passed via csv, xml or api

my doubts are related to products with combinations, not when they are simple products

**Comment by kpodemski** [comment]
>  I think there may be some problems when they do checks on the product page since they don't find the same references passed via xml or API

Well, for years, it's been like that, and I do not recall any issues. My clients use combinations and generate XML with the product_id-combination_id, as you mentioned, I don't recall a single situation where Google would complain about schema.org vs. XML file regarding the id. Regarding prices? Yes. Regarding identifier? Never. So you think hypothetically, not based on a real-case scenario, right?

**Comment by Maofree** [comment]
Yes, it is
I should check better, by now I'm a little afraid of these google systems that constantly change strategies and become more and more precise and selective.
mine is more of a warning to prevent problems

**Comment by kpodemski** [comment]
@maofree I understand your point of view. Right now, let's keep the current behavior, the change, if needed, would be quite easy to implement, but there's no need to do that now. Thanks for the discussion and your feedback!
