### ISSUE TITLE
BO - Products : bad error message display

### ISSUE THREAD

**Issue by MhiriFaten** [PrestaShop/PrestaShop#32724]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The error message contain code details

PS_8.0.4 :x: 
![image](https://github.com/PrestaShop/PrestaShop/assets/111756615/030eee4c-1356-4559-a029-8417c04c6eb4)

PS_8.1.0 :x: 
![image](https://github.com/PrestaShop/PrestaShop/assets/111756615/0cd3cb2d-0101-42f5-8b77-c7d623dd3ac7)

PS_1.7.8.9 :x:
![image](https://github.com/PrestaShop/PrestaShop/assets/111756615/6e998797-557c-4050-b1e7-e34cb62c9ab9)

### Expected behavior

the error message does not contain `PrestaShop\PrestaShop\Core\Domain\Product\Exception\ProductConstraintException code 320` and table attributes.

### Steps to reproduce

The SHOP is on PPV2
Go to BO>Catalog>Products
Go to `Hummingbird - Vector graphics` product and click on edit
Go to virtual product>Minimum quantity for sale
Put a number >0 (example -4)
see error :warning: the error message contain code details

### PrestaShop version(s) where the bug happened

8.1.x, 8.0.x, 1.7.8.x

### PHP version(s) where the bug happened

7.4 & 8.1

**Comment by djoelleuch** [comment]
Hello @MhiriFaten

Thanks for reporting the issue, I reproduce it with PS 8.1.x 

[Untitled_ May 30, 2023 12_51 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/c2a4942e-6dbc-401d-aab2-03b6d7c88711)

Thanks!

**Comment by florine2623** [comment]
This issue is fixed :

<img width="817" alt="Screenshot 2023-12-27 at 13 45 03" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/97b88e85-22e5-4d6f-9102-495dba53a9fa">
