### ISSUE TITLE
On forum website, the cookie message displays in polish

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#32722]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Not sure where to notify this, so I'm creating a bug.
On the Prestashop forum in English, the cookie message shows in Polish
![Immagine 2023-05-26 112726](https://github.com/PrestaShop/PrestaShop/assets/7520695/e6b32b7f-acb8-4751-b0e0-510b6056d96d)

### Expected behavior

Have it in English

### Steps to reproduce

1. https://www.prestashop.com/forums/topic/547614-prestashop-within-a-docker-container/
2. Click on the cookie icon (hand)

### PrestaShop version(s) where the bug happened

https://www.prestashop.com/forums

**Comment by kpodemski** [comment]
Thanks, Lorenz. I'll pass the news to somebody who can help with that.
