### ISSUE TITLE
Fix popup size on add to cart on mobile

### ISSUE THREAD

**Issue by vsilva9000** [PrestaShop/PrestaShop#32725]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Im using prestashop 8.0.4

When i have produt combination and add to cart the popup dont resize on mobile.

### Expected behavior

Popup auto resize on mobile

### Steps to reproduce

1. Use prestashop 8.0.4 php 7.24
2. Create produt combination
3. Add to cart on mobile
4. Popup add to cart is not autoresize

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

7.24

![Screenshot_331](https://github.com/PrestaShop/PrestaShop/assets/134699441/3a5f3654-5055-4f4e-8f4c-95367cc4689f)

**Comment by Hlavtox** [comment]
Third party theme, works fine on classic and humingbird.

**Comment by aniszr** [comment]
Hello @vsilva9000 

I didn't manage to reproduce this issue with classic theme,see attached screen shot

![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/ca6f490b-1227-43e0-84a6-a1295ce9ba50)


Thanks!

**Comment by hibatallahAouadni** [comment]
Hello everyone,

Thanks guys for your quick replies.
Closing the issue as it's related to your customized theme.

Thanks!
