### ISSUE TITLE
[FO] Blockwishlist - Multistore : the product tripled in quantity 

### ISSUE THREAD

**Issue by MhiriFaten** [PrestaShop/PrestaShop#32737]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

8.0.1 RC :x: 

[Untitled_ May 29, 2023 12_02 PM (1).webm](https://github.com/PrestaShop/PrestaShop/assets/111756615/8e5aa86a-a158-4516-9e6f-0693e9bfaf7a)

8.0.4 :x: 
![image](https://github.com/PrestaShop/PrestaShop/assets/111756615/c2bfe508-d998-49d3-b468-9781d29ee8e1)

1.7.8.9 :x: 
![image](https://github.com/PrestaShop/PrestaShop/assets/111756615/dddb7247-f374-44ea-a07b-e43c75ef9079)

### Steps to reproduce

1. GO to **BO**> Shop parameters > General
2. Enable Multistore : `YES`
3. Advanced Parameters> Multistore> Add a new shop
4. Go to **FO of new store**> All products
5. Add product to wishlist> Create new list> Choose it
6. Go to customer account> My wishlist> **the new wishlist**
7. :warning: see error : the product has tripled in quantity 

### PrestaShop version(s) where the bug happened

8.1.0 RC, 8.0.4, 1.7.8.9

### PHP version(s) where the bug happened

7.4 & 8.1

### If your bug is related to a module, specify its name and its version

Blockwishlist

**Comment by hibatallahAouadni** [comment]
Hello @MhiriFaten 

I didn't manage to reproduce the issue with PS804 and PS81x with both old and new version of module v2.1.2 and v3.0.0, see the attached screen record below:

[issue_32737.webm](https://github.com/PrestaShop/PrestaShop/assets/23308427/aa67856a-9278-4c3c-a81b-0c3f77256f76)

Please check and feedback.

Thanks!

**Comment by MhiriFaten** [comment]
@PrestaShop/qa-functional Could someone else check it please?

**Comment by djoelleuch** [comment]
Hello @MhiriFaten  ,


Despite our efforts, we were not able to reproduce your issue with the provided information. it seems that your issue is related to cache . 

[Untitled_ May 30, 2023 11_40 AM.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/349571a5-bae4-4f7a-b2fc-517cee8d143a)

We will close this issue.

Thank you!
