### ISSUE TITLE
FO - Bad redirection of  maintenance 

### ISSUE THREAD

**Issue by djoelleuch** [PrestaShop/PrestaShop#32740]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Bad redirection of  maintenance 
 PS 8.1.0 RC  :x: 

[rc.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/05810f2a-f3af-4a52-ab64-1c38f33568c2)

PS 8.1.x :heavy_check_mark: 

[81x.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/4a5c5d6f-a868-4fcc-8521-d29772b4e7f8)

### Steps to reproduce

1. Go to  General > Maintenance > disable "enable store " and "enable store for logged-in employees " >Save 
2. view my store > see  **the shop is well displayed**  !!

### PrestaShop version(s) where the bug happened

PS 8.1.0-rc

### PHP version(s) where the bug happened

8.1

**Comment by kpodemski** [comment]
On the first video, you provided your IP, on the second one, you didn't. Maybe you could see the store because of it?

**Comment by hibatallahAouadni** [comment]
Indeed @kpodemski 
Could you please recheck @djoelleuch :pray:

**Comment by djoelleuch** [comment]
Hello @hibatallahAouadni  , 

it was a mistake , I have rechecked it and it looks good ^ 
I will close this issue.

Thank you !
