### ISSUE TITLE
Autoupgrade module, check version dependencies for PHP

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#32745]
In the autoupgrade module we check the minimum requirement to upgrade the shop towards the expected target including the PHP version

For now this version is hard-coded to PHP 7.2 in https://github.com/PrestaShop/autoupgrade/blob/fe858599e3c85ae01a9fe2e9158b5b454b45c653/classes/UpgradeSelfCheck.php#L416

This behaviour should be more dynamic as for PrestaShop 9.0 the minimum PHP version is now PHP 8.1

**Comment by Quetzacoalt91** [comment]
@jolelievre Can we rely on the distribution API to dinamically get the PHP compatibility range?

We are able to get the version for a [`stable` channel](https://api.prestashop-project.org/prestashop/stable), but as far as I know we cannot match the `minor` and `major` channels of the module. Is there another way to get details for a given version of PrestaShop?

**Comment by jolelievre** [comment]
Hmm, seems like you can get all the versions starting from 8.0.0 here https://api.prestashop-project.org/prestashop
But nothing prior 8.0.0, if it's really needed though maybe we can increase the number of releases that the distribution API knows

**Comment by jolelievre** [comment]
Or maybe we can keep PHP 7.2 hard coded for older versions and use a more accurate version based on the API for version after 8.0?

**Comment by Quetzacoalt91** [comment]
Fixed by https://github.com/PrestaShop/autoupgrade/pull/715 and released with v6.0.0 of autoupgrade
