### ISSUE TITLE
PrestashopDatabaseException on cart confirmation with free delivery cart rules in debug mode

### ISSUE THREAD

**Issue by martinloic** [PrestaShop/PrestaShop#32748]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When creating a new customer group and creating a new cart rule with free delivery for this specific group when ordering i have an error in debug mode :

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND ccr.id_cart_rule = 1 AND o.id_order IS NULL LIMIT 1' at line 5<br /><br /><pre> SELECT count(*) FROM `ps_cart_cart_rule` ccr INNER JOIN `ps_cart` c ON c.id_cart = ccr.id_cart LEFT JOIN `ps_orders` o ON o.id_cart = c.id_cart WHERE c.id_customer = 3 AND **c.id_cart = AND** ccr.id_cart_rule = 1 AND o.id_order IS NULL LIMIT 1</pre>

It seems that the value for the c.id_cart parameter is not being properly assigned or retrieved.

![image](https://github.com/PrestaShop/PrestaShop/assets/6592948/43ba64dd-6208-475c-8dbe-2d978735130e)

I tried with a fresh install of prestashop i have the same error.

### Expected behavior

It seems that the value for the c.id_cart parameter is not being properly assigned or retrieved.
Normally the c.id_cart parameter should be retrieved

### Steps to reproduce

**BO**
1. Turn on debug mode
2. Create a new customer group
3. Create a new cart rules with a voucher code
4. Add a minimum amount, a minimum quantity & quantity per user (for example 100)
5. Make a restriction with the carrier
6. Check the free delivery and save
7. Create a new customer
8. Check the new group that you have created & uncheck the others
9. Select the new group as default group.
10. Save

**FO**
1. Login with the new customer account
2. Add products to your cart
3. Go the the order page
4. Add the free delivery voucher
5. Confirm by paying by check or transfer

You should get an 500 Error or the prestashop database exeption

Link to the video : https://drive.google.com/file/d/1OV8Q3E329ZMJbKyHPXUu4Ab3BwIA_zsP/view?usp=sharing

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.1.33-52,7.4.21

**Comment by aniszr** [comment]
Hello,

I couldn't reproduce this issue with my PS 8.0.4, as you can see in attached screen record.


https://github.com/PrestaShop/PrestaShop/assets/92626242/d0bf52a8-c6b5-4a9a-970e-d44d3b97f2b6



Additional infos:
PS version:8.0.4
PHP version:8.1.19

Thanks

**Comment by florine2623** [comment]
Hello @martinloic ,

I have reproduced your issue with `PS 1.7.8.9` :
<img width="1434" alt="Screenshot 2023-06-20 at 11 24 29" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/26b4a868-e94d-401b-9629-5d46667adcf9">

Tested the same thing on `8.0.4`, `8.1.0`. I'm having an issue as well :
<img width="1252" alt="Screenshot 2023-06-20 at 14 25 46" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/c4d47fe6-ace5-473c-9c38-4f05f7dc8978">

But on `develop,` it is fixed :
<img width="1152" alt="Screenshot 2023-06-20 at 14 38 03" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/5e6b8422-7599-4041-a946-141e367cfa19">


@MatShir , what should be done with that issue ?

Thanks!

**Comment by MatShir** [comment]
Unfortunately, the upcoming patches for version 1.7.8 will be for security bugs only. If we fix the problem in 8.1.x (patches to come), you'll have to upgrade the store or apply the changes directly to your source code.

**Comment by MatShir** [comment]
@florine2623 in develop the cart rule is well applied I guess ?

**Comment by florine2623** [comment]
@MatShir , yes, on `develop`, the discount is well applied. It works as expected.

**Comment by MatShir** [comment]
If someone find the PR that fixed the issue on `develop`, we could back port it

**Comment by sallemiines** [comment]
ping @PrestaShop/prestashop-core-developers

**Comment by hibatallahAouadni** [comment]
Friendly reminder @PrestaShop/prestashop-maintainers

**Comment by studiokiwik** [comment]
Hi, 

We have the same issue with PS 8.1.6.
