### ISSUE TITLE
Profiler shows incorrect execution time

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#32753]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When using the Profiler, I notice that the execution time is wrong.
In fact the start_time is when `Profiler::__construct` is called https://github.com/PrestaShop/PrestaShop/blob/ff3780e47ad5ff031440c6856f6ec031801de0d3/tools/profiling/Profiler.php#L76,
but it should be the start of the request, when `index.php` is starting to execute.

![Immagine 2023-05-30 153824](https://github.com/PrestaShop/PrestaShop/assets/7520695/82cb86cf-c377-4b68-b386-7ece557efb30)

In this image, the three numbers displayed at the top are `{$smarty.server.REQUEST_TIME_FLOAT} {$run.startTime}
  {load_time data=($run.startTime - $smarty.server.REQUEST_TIME_FLOAT)}` added in https://github.com/PrestaShop/PrestaShop/blob/develop/tools/profiling/templates/run.tpl

This proves that there are 91ms that are used by the initialisation of Prestashop before `Profiler::__construct()`

### Expected behavior

In the profiler, the time should start to run when the script starts executing.
This would be the good starting time on which the calculations for the profiler should be base on: https://github.com/PrestaShop/PrestaShop/blob/ff3780e47ad5ff031440c6856f6ec031801de0d3/config/config.inc.php#L38
If the server exposes the variable `$_SERVER['REQUEST_TIME_FLOAT']`, then this would also be a good candidate as start time.

The correct value for `config` Time in the image above should be 5.611ms + 91.627ms = 97.238ms

### Steps to reproduce

1. Enable profiling in `defines_custom.inc.php` by adding `define('_PS_DEBUG_PROFILING_', true);`
2. In https://github.com/PrestaShop/PrestaShop/blob/ff3780e47ad5ff031440c6856f6ec031801de0d3/tools/profiling/templates/run.tpl#L26, before the `<table>` add `{$smarty.server.REQUEST_TIME_FLOAT} {$run.startTime}
  {load_time data=($run.startTime - $smarty.server.REQUEST_TIME_FLOAT)}`
3. Load a page in the front end and look at the output of the Profiler

### PrestaShop version(s) where the bug happened

8.0.4 and devel

### PHP version(s) where the bug happened

any

### Your company or customer's name goes here (if applicable).

Société Biblique de Genève

**Comment by aniszr** [comment]
Hello @lmeyer1 

I did reproduce the issue with develop branch, see the attached screenshot below:

![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/05089cdd-be51-4ab0-a6bd-596b5f8a2295)

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 & @aniszr 

Thanks guys for your hard working.
Ping @PrestaShop/prestashop-maintainers wdyt? Is it a valid bug or feature to improve the performance? 

Waiting for your feedback.

Thanks!
