### ISSUE TITLE
ps_facetedsearch 

### ISSUE THREAD

**Issue by daniweb78** [PrestaShop/PrestaShop#32775]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello everyone.
I downloaded the module because I needed to have the filter when a brand is selected.
I removed the module I had and installed the zip file.
but the functionality doesn't work.
everything remains as before.
can you help me?

### Expected behavior

selecting a brand the filters had to be present

### Steps to reproduce

I select a brand from the menu, the products are displayed but the filters are not

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_facetedsearch-3.12.1

**Comment by paulnoelcholot** [comment]
Hello @daniweb78,

In order to be able to try to reproduce this bug, we would need you to detail the step to reproduce.

Thanks for your feedback

**Comment by florine2623** [comment]
Hello @daniweb78 ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
