### ISSUE TITLE
Despite the correctly configured settings, I do not receive notifications about new purchases on my website in my e-mail.

### ISSUE THREAD

**Issue by koma-shop** [PrestaShop/PrestaShop#32772]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Despite the correctly co
![presta](https://github.com/PrestaShop/PrestaShop/assets/135128587/f0054655-86e9-4f36-8743-c302a2dfd7fb)
nfigured settings, I do not receive notifications about new purchases on my website in my e-mail.

### Expected behavior

Despite the correctly configured settings, I do not receive notifications about new purchases on my website in my e-mail.

### Steps to reproduce

![presta](https://github.com/PrestaShop/PrestaShop/assets/135128587/e5ac0b00-2b46-41d7-b1dd-eea771270489)

### PrestaShop version(s) where the bug happened

1.7.8.6

### If your bug is related to a module, specify its name and its version

ps_emailalerts

**Comment by paulnoelcholot** [comment]
Hello @koma-shop,

Can you give me more information about your configuration, PHP version, step to reproduce, and screenshots in the English language, please?

Thanks for your feedback

**Comment by MatShir** [comment]
The issue might come from your server provider or your module configuration. Check if the module ps_emailalerts is well configured, and if it is please contact your server provider. Keep us updated :)

**Comment by florine2623** [comment]
@koma-shop ,

This is a server configuration error. Please contact your server provider to fix this issue ^^
