### ISSUE TITLE
Visitor online not working

### ISSUE THREAD

**Issue by KaeligBrl** [PrestaShop/PrestaShop#32774]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello:visage_légèrement_souriant:
Prestashop version: 1.7.8.9
I have a native problem on prestashop.
My online visitors are not showing up and I don't have the conversion rate, everything is 0.
Of course, I have orders on the site.
Do you know what it could be
Sincerely
Kaelig (modifié) 

### Expected behavior

Sreenshot: https://prnt.sc/oImJzrQhqOOw

### Steps to reproduce

1 go to dashboard and see statisttiques
2 See the visitor online 0 (i visit the website with my mobile phone)

### PrestaShop version(s) where the bug happened

1.7.8.9

### If your bug is related to a module, specify its name and its version

statitics

### Your company or customer's name goes here (if applicable).

Nellumbo

**Comment by paulnoelcholot** [comment]
Hello @KaeligShebam,

I tried to reproduce your issue but as you can see, I can't : 
![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/085ff7e0-b70b-4887-bc10-7ad0ea152b97)

Did I miss something?

**Comment by KaeligBrl** [comment]
> Hello @KaeligShebam,
> 
> I tried to reproduce your issue but as you can see, I can't : ![image](https://user-images.githubusercontent.com/112863083/242403792-085ff7e0-b70b-4887-bc10-7ad0ea152b97.png)
> 
> Did I miss something?


Me it doesn't work

**Comment by paulnoelcholot** [comment]
Hello @KaeligShebam 

Can you confirm that you are in version 1.7.8.9?

The Online visitor statistic is only for the last 30 minutes. Can you confirm that you tried to connect less than 30min ago?

Thanks for your feedback.

**Comment by KaeligBrl** [comment]
> Hello @KaeligShebam
> 
> Can you confirm that you are in version 1.7.8.9?
> 
> The Online visitor statistic is only for the last 30 minutes. Can you confirm that you tried to connect less than 30min ago?
> 
> Thanks for your feedback.

Helllo ;)

Yes I am on 1.7.8.9

And yes I tried with two different computers.

Reset the statslive, dashactitivy, statsvisit modules then reinstall and still nothing.

**Comment by paulnoelcholot** [comment]
What is your PHP version?

**Comment by KaeligShebam** [comment]
> What is your PHP version?

 7.4.33

**Comment by KaeligBrl** [comment]
> What is your PHP version?

7.4.33

**Comment by AchrafKchaou1991** [comment]
Hello @KaeligShebam 
I tried to reproduce the issues using PS 1.7.8.9 but an exception appears :

[issue 32774.webm](https://github.com/PrestaShop/PrestaShop/assets/131356155/494088d3-6686-484b-a635-df6239b6444e)


Can you check please ?Did I miss any steps?
Waiting for your feedback,
Thank you

**Comment by KaeligBrl** [comment]
> Hello @KaeligShebam I tried to reproduce the issues using PS 1.7.8.9 but an exception appears :
> 
>  issue.32774.webm 
> Can you check please ?Did I miss any steps? Waiting for your feedback, Thank you

Hello:

This link: https://www.loom.com/share/45f9570563f04e15aa19db4a8913b005

i don't reproduce... There are hooks to put I don't know I reset and reinstalled the modules nothing done

**Comment by kpodemski** [comment]
@KaeligShebam you probably have a module that is responsible for getting this data unhooked from the front office

it is not a bug coming from the module, because as you can see from @paulnoelcholot it works for him

I suggest you to contact somebody technical to help you out and check everything directly in your store

**Comment by KaeligBrl** [comment]
@kpodemski Exactly I want to contact a technician that's why prestashop support told me to post a message here

**Comment by kpodemski** [comment]
@KaeligShebam ok :)

https://www.prestashop-project.org/support/ - this should work better for you :)

**Comment by KaeligBrl** [comment]
@kpodemski I already come from there and I was told to post on github for the prestashop core developer to answer me
