### ISSUE TITLE
Migration of tactician towards Symfony Messenger

### ISSUE THREAD

**Issue by lartist** [PrestaShop/PrestaShop#32786]
Currently we're using a library called [league/tactician-bundle](https://packagist.org/packages/league/tactician-bundle) which provide a message bus.
Symfony (since the version 4) provides it's own component with a message bus which is [symfony/messenger](https://symfony.com/doc/current/messenger.html).
We should migrate to symfony/messenger to take advantage of the symfony ecosystem. Also it's more maintainable since this library evolves the same rythme than the other components. For example all the symfony components use the same php version for a given symfony version.

**Comment by WahbiPS** [comment]
A new issue should be created for other repositories
