### ISSUE TITLE
Update DocToolsBundle once Messenger is used for CQRS

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#32799]
We planned on replacing Tactitian with Messenger to handle our CQRS commands/queries

As such this bundle https://github.com/PrestaShop/DocToolsBundle used to generate the CQRS doc won't be working anymore.
We should update the bundle to:
- be compatible with PS9 and SF 5.4 PHP 8.1
- fix the command that lists the commands/queries and list/prints out the documentation

Once this is fixed and merged we should update the devdoc for:
- 1.7.8
- 8.0
- 8.1 (not sure it's been created yet)
- 9.0 

For version 8.0 and 8.1 we'll use the current version based on tactician, for 9.0 the new one based on messenger. Two tags will probably be needed (or at least one for the old version) since the repo doesn't have any tag so far.

**Comment by WahbiPS** [comment]
Blocked : waiting for https://github.com/PrestaShop/PrestaShop/issues/32786

**Comment by WahbiPS** [comment]
Associated PR : https://github.com/PrestaShop/DocToolsBundle/pull/4

**Comment by matks** [comment]
Still blocked by https://github.com/PrestaShop/PrestaShop/issues/32786

**Comment by M0rgan01** [comment]
PR: https://github.com/PrestaShop/DocToolsBundle/pull/4

**Comment by WahbiPS** [comment]
Tested and approved by @matthieu-rolland
