### ISSUE TITLE
<br> in description  onhover "Maintenance mode" button

### ISSUE THREAD

**Issue by 4ECHatu** [PrestaShop/PrestaShop#32794]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

![obraz](https://github.com/PrestaShop/PrestaShop/assets/82656195/21e85362-451a-4384-9a77-046070005cf1)

### Expected behavior

I wish to have no < br > in the description 

### Steps to reproduce

1. Go to BO > Shop Parameters > General > Maintenance
2. Enable Maintenance mode
3. hover on main "Maintenance  mode" button

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

7.2.34 

### Your company or customer's name goes here (if applicable).

[4ec.eu](https://4ec.eu/)

**Comment by AchrafKchaou1991** [comment]
Hi @4ECHatu  ,
I reproduce the issue with PrestaShop version 8.0.4 and not with the version 8.0.0. as you can see :


[issue 32794.webm](https://github.com/PrestaShop/PrestaShop/assets/131356155/9f32031b-5e8f-4df1-b9e4-f440c9adcb23)


 Nice catch ! It's a regression ! I'll add it to the patch backlog.
Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you.
If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.
Thank you

**Comment by MatShir** [comment]
Seems to be fixed on 8.1 :)

**Comment by florine2623** [comment]
Fixed on `8.1.0` and `develop`.

But another issue arises.

On legacy pages, it is ok.
<img width="443" alt="Screenshot 2023-06-28 at 15 38 03" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/1e19b976-309c-435d-aff8-602b37a43928">

But on migrated page, the title is not totally displayed :
<img width="427" alt="Screenshot 2023-06-28 at 15 38 11" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/8814e1c4-ea3c-4ad9-b998-3fc47594d5fd">

@MatShir , we can leave that issue open until the second issue is fixed. What do you think ?
