### ISSUE TITLE
Handle commands with advanced setter

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#32805]
Blocked by this issue https://github.com/PrestaShop/PrestaShop/issues/32803 some commands have setters with multiple values.

https://github.com/PrestaShop/PrestaShop/blob/d3c081a6fdd107c442ec783000cbc93056da14a3/src/Core/Domain/CartRule/Command/EditCartRuleCommand.php#L250

**Comment by WahbiPS** [comment]
~~Blocked, waiting for [Handle command/query with constructor/setters using DecimalNumber and/or DateTime#32804](https://github.com/PrestaShop/PrestaShop/issues/32804)~~
