### ISSUE TITLE
Handle command/query with constructor/setters using DecimalNumber and/or DateTime

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#32804]
Kind of related to https://github.com/PrestaShop/PrestaShop/issues/32803 because the solution will use the same service but can be started in parallel

Most of the commands parameters are scalar (string; int, bool) but some can be a bit more advanced like DecimalNumber and/or DateTime. Like in the mentioned issue, this feature of prefill/building commands should be handled by a dedicated and unit tested service. We need to handle the conversion of this kind of input, maybe ApiPlatform can handle dates natively as long as they are used in the DTO, but for `DecimalNumber` probably not.

Example:

https://github.com/PrestaShop/PrestaShop/blob/f5cfdf3fffbd1fdf967c49e933e62fed09a1d23d/src/Core/Domain/Customer/Group/Command/AddCustomerGroupCommand.php#L70

**Comment by WahbiPS** [comment]
Blocked until https://github.com/PrestaShop/PrestaShop/issues/32803 done
