### ISSUE TITLE
Extract first API endpoints into an external native module

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#32806]
Blocked by https://github.com/PrestaShop/PrestaShop/issues/32582 once this issue is finished all the existing ApiPlatform endpoints in the core should be moved into a dedicated PrestaShop native module

This module will contain all the APIs related to commands/queries in the core, and once it exists all the additional endpoints should be added inside it instead of the core.

**Comment by Zoefinders** [comment]
Waiting for @jo to validate this issue
