### ISSUE TITLE
Acceptance tests Mail

### ISSUE THREAD

**Issue by fabienvallon** [PrestaShop/PrestaShop#32801]
## Description 

For QA team, we need some acceptance tests for all mail that could be send by PrestaShop

Based [on this list ](https://github.com/PrestaShop/PrestaShop/issues/32217#issuecomment-1558707155)

   1. write specs 
   2. Create 1 video per mail sent for QA

## Acceptance tests 

QA review

**Comment by Zoefinders** [comment]
Link of specs : https://www.notion.so/prestashopcorp/08312cc1a5eb43b89b54fa8a5195e679?v=4942181bbf4043a2a32a07e9b8627cec
