### ISSUE TITLE
Catalog price reduction is not highlighted in cart even price is well calculated

### ISSUE THREAD

**Issue by gmaurice** [PrestaShop/PrestaShop#32810]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When defining a catalog price rule only with "from quantity", the cart display the right price reduced for the same products id, however the reduction percentage is not highlighted.
It will be highlighted only if each cart line reaches the "from quantity" reduction.

Note, I previously removed the specific price defined on the product.

Here is the definition of the catalog price rule : 
![catalog-rule-from-10-apply-10pct](https://github.com/PrestaShop/PrestaShop/assets/344348/eba01655-99aa-4d0b-abb0-549a05b3f7d8)

Here is the regular price with no reduction :
![cart-2pcs-no-discount](https://github.com/PrestaShop/PrestaShop/assets/344348/f2ece80d-6545-4ae4-bc40-b6ccbf1511fa)

Here is the reduction applied because the total quantity of product id reaches the reduction quantity : 
![cart-10pcs-total-with-discount](https://github.com/PrestaShop/PrestaShop/assets/344348/d729c708-fa22-41b8-bde4-13030f101e05)

Here, the reduction percentage is displayed as soon as the second cart line reaches the reduction quantity : 
![cart-10pcs-on-product-with-discount](https://github.com/PrestaShop/PrestaShop/assets/344348/09ac5436-feeb-4ef6-8d7f-d8274207ab82)

I tried to find a similar issue without success, i don't know if it could fit in this EPIC https://github.com/PrestaShop/PrestaShop/issues/20183

### Expected behavior

Catalog price rule reduction applied should be displayed as this : 
![cart-10pcs-total-expected](https://github.com/PrestaShop/PrestaShop/assets/344348/8366249e-cdb4-4bb3-b52a-35943454c88d)

### Steps to reproduce

- Define the catalog price rule as this : ![catalog-rule-from-10-apply-10pct](https://github.com/PrestaShop/PrestaShop/assets/344348/eba01655-99aa-4d0b-abb0-549a05b3f7d8)
- Add product in "**S**" size and **white**, quantity = 1, in cart
- Add the same product in "**S**" size and **black**, quantity = 1, in cart
- Go to Cart
- You see regular prices for the same product id : ![cart-2pcs-no-discount](https://github.com/PrestaShop/PrestaShop/assets/344348/f2ece80d-6545-4ae4-bc40-b6ccbf1511fa)
- Grow quantity to reach the total quantity >= 10 in cart
- You see price reduced with no highlight of reduction : 
![cart-10pcs-total-no-reduction-highlight](https://github.com/PrestaShop/PrestaShop/assets/344348/699824d1-30ab-4176-a708-aeae4201539b)

### PrestaShop version(s) where the bug happened

1.7.8.9, 8.0.1, 8.0.2, 8.0.3, 8.0.4, 8.1.0

**Comment by dnkhack** [comment]
Hello. This is not a bug. This is normal behavior! Products with the combination (attributes) are separate products with a single father! 

When you set conditions to "All combinations" it is mean to each combination, not the whole combination! 
You can use a module from Addons to solve your desire!

**Comment by sallemiines** [comment]
Hello @gmaurice 

I check your issue with a product type = combination 


https://github.com/PrestaShop/PrestaShop/assets/31663369/95875129-9824-4642-82be-e84ce9cd1a73


product type = simple  


https://github.com/PrestaShop/PrestaShop/assets/31663369/77f323f6-2a63-4c26-986f-f342f403ae6f

It's  the normal behavior  ! 

Thank you !

**Comment by sallemiines** [comment]
Hello, 

I didn't manage to reproduce your issue , it's look the normal behavior ! 


Product type = Combination 

https://github.com/PrestaShop/PrestaShop/assets/31663369/ba45c071-b4ff-4fe3-89e7-60bcc42ffdf5

Product type = simple 

https://github.com/PrestaShop/PrestaShop/assets/31663369/a67a5399-ff1f-4bf4-a552-9b3e8ccfa8fb

Thank you

**Comment by dnkhack** [comment]
@sallemiines now I got it. He wants in order to display the discount flag already when the discount was applied. And on all combinations at the same time!
This is a bug and needs to be improved. The discount applied flag is not displayed! Very bad for marketing when customers do not see the sale stimulation discount flag!

**Comment by gmaurice** [comment]
Thank you @dnkhack for taking time to understand what it implies for customers.
For now, the company i work for (fashion), uses 1.6 version, where the bug does not exist.
The company is most of time based on quantity discount, and they are migrating to 8.x, so i'm pretty sure their customers will call them too often because they don't clearly see the price discount applied with the various size, colors,...

**Comment by gmaurice** [comment]
Hello, should we reopen the issue ?

**Comment by dnkhack** [comment]
Hello, I suppose, Yes. But with explanations also add a link to this page and explain that @sallemiines video proved the bug. Explain about PS 1.6. Be better if you add a screenshot from version 1.6

**Comment by gmaurice** [comment]
Hello, for sure !
Add in the cart : 
- 9 **white** M t-shirts
- 1 **black** M t-shirt
Here is the screenshot of 1.6 behavior :
![ps16-cart-10pcs-total-right-behavior](https://github.com/PrestaShop/PrestaShop/assets/344348/26d6b943-e596-43a5-bffa-44eac9650a2f)

**Comment by dnkhack** [comment]
@gmaurice Excellent! Inform about the bug!

**Comment by gmaurice** [comment]
Hello, maybe i misunderstand something, but why the issue is still closed ?

**Comment by dnkhack** [comment]
@gmaurice 
Hello, I suppose you have to create a new thread! Closed thread, not to review!

**Comment by gmaurice** [comment]
Ok, but it will be almost a copy of the present one and how to be sure it will not be closed once again ?
Moreover, in the first video of @sallemiines the bug is well reproduced but declared as normal behavior :/

**Comment by dnkhack** [comment]
@gmaurice Yes it will be almost copy. But you add a screenshot from 1.6. Link to this page. And notice about video @sallemiines that her video proved the issue! 
Bro, I'm not a PS core dev, simply a developer of modules. But as the owner of an e-shop, I see this as a big issue. Quantity discount is the best sale stimulation method of all time!
