### ISSUE TITLE
Error appearing in error log

### ISSUE THREAD

**Issue by musaffarpatel** [PrestaShop/PrestaShop#32828]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The following error is appearing in our error log:

[2023-05-03 09:34:11] request.CRITICAL: Exception thrown when handling an exception (Twig
rror\SyntaxError: A template that extends another one cannot include content outside Twig blocks. Did you forget to put the content inside a {% block %} tag? at /var/www/html/src/PrestaShopBundle/Resources/views/Admin/Exception/error.html.twig line 25) {"exception":"[object] (Twig\Error\SyntaxError(code: 0): A template that extends another one cannot include content outside Twig blocks. Did you forget to put the content inside a {% block %} tag? at /var/www/html/src/PrestaShopBundle/Resources/views/Admin/Exception/error.html.twig:25)"} []

### Steps to reproduce

Not able to identify the exact steps we need to undertake to reproduce the problem unfortunately.

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.1.8

**Comment by sallemiines** [comment]
Hello @musaffarpatel ,

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template and provide clear and concise steps to reproduce the bug**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by musaffarpatel** [comment]
The template is the core template that ships with Prestashop as indicated in the error:
/var/www/html/src/PrestaShopBundle/Resources/views/Admin/Exception/error.html.twig

I couldn't see anything particularly wrong with the template which suggests it could be a bug related to parsing of twig templates somewhere in the core.

In regards to the steps to reproduce, attempted several ways to reproduce the error directly but could not do so
