### ISSUE TITLE
HTML tags on translations

### ISSUE THREAD

**Issue by borjagarciab** [PrestaShop/PrestaShop#32825]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I am developing a module with some translations, and I see that if I include the HTML tags in the translation, the tag is displayed.
![image](https://github.com/PrestaShop/PrestaShop/assets/57815173/9a55a220-3b79-4eb2-9997-3ad3c539d1c4)

![image](https://github.com/PrestaShop/PrestaShop/assets/57815173/3551c9d9-b333-4abb-a3b1-be7b61709878)

### Expected behavior

Do not see the HTML tag
![image](https://github.com/PrestaShop/PrestaShop/assets/57815173/d673edf2-2b2e-4457-b216-93364b7d2d04)

### Steps to reproduce

Just use the trans method , and add an HTML tag.
![image](https://github.com/PrestaShop/PrestaShop/assets/57815173/a9cefa16-6723-4793-97f1-14cd346c400b)

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.1

**Comment by borjagarciab** [comment]
A temporal fix can be this , but i don't know if this will add other issues:
html/classes/controller/Controller.php method trans
![image](https://github.com/PrestaShop/PrestaShop/assets/57815173/5e7245b7-f680-4868-bb02-097c145f9f75)
Just remove the htmlspecialchars method.
![image](https://github.com/PrestaShop/PrestaShop/assets/57815173/847990ff-fba5-4280-b940-a1b2188fb0ce)

**Comment by dnkhack** [comment]
Hello. This is not the bug. Please read the documentation first. 

If you want to include an HTML tag in the translation, you must use the "trick" described in the article!  

https://devdocs.prestashop-project.org/8/development/internationalization/translation/translation-tips/

**Comment by sallemiines** [comment]
Hello @dnkhack 

Your issue dosen't not look a bug related to prestashopCorp ! 
We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).
Thank you

**Comment by borjagarciab** [comment]
Hi @sallemiines , @dnkhack 
In my opinion , is a bug, or a change of functionality:
1. I don't see what you say about documentation. @dnkhack 

2. We have upgraded the shop from PS 8.0.0 to 8.0.4 and this was working. (And was working for all 1.7.X)
@sallemiines 
I've found the commit where this code is changed on PS 8.0.1
https://github.com/PrestaShop/PrestaShop/commit/8c295183c38ca443f4b93075c6c52d813baa0a11#diff-9f289759f04c7012de8116c55f0d0db2eb1f7da736b2949946fd6076743e2977

Can you check it? Because was a feature that was working. 
(Or tell me please  what is the correct way for this)

Thanks!

**Comment by dnkhack** [comment]
@sallemiines Hello.
This is not my request. I have answered for @borjagarciab 

I show how to use HTML tags in translations. 

` $this->trans('This is [1]strong text[/1] [2]this is a link[/2]', [
'[1]' => '<strong>',
'[/1]' => '</strong>',
'[2]' => '<a href="' . Code_To_Get_Link . '">',
'[/2]' => '</a>',
], 'Admin.Catalog.Feature'),`

For TPL just show you part of the code from \themes\classic\templates\checkout\_partials\steps\personal-information.tpl

`      {* [1][/1] is for a HTML tag. *}
      {l s='Connected as [1]%firstname% %lastname%[/1].'
        d='Shop.Theme.Customeraccount'
        sprintf=[
          '[1]' => "<a href='{$urls.pages.identity}'>",
          '[/1]' => "</a>",
          '%firstname%' => $customer.firstname,
          '%lastname%' => $customer.lastname
        ]`

If you have developer questions about PS feel free to ask me

**Comment by borjagarciab** [comment]
> @sallemiines Hello. This is not my request. I have answered for @borjagarciab
> 
> I show how to use HTML tags in translations.
> 
> ` $this->trans('This is [1]strong text[/1] [2]this is a link[/2]', [ '[1]' => '\<strong\>', '[/1]' => '\</strong\>', '[2]' => '<a href="' . Code_To_Get_Link . '">', '[/2]' => '</a>', ], 'Admin.Catalog.Feature'),`
> 
> For TPL just show you part of the code from \themes\classic\templates\checkout_partials\steps\personal-information.tpl
> 
> ` {* [1][/1] is for a HTML tag. *} {l s='Connected as [1]%firstname% %lastname%[/1].' d='Shop.Theme.Customeraccount' sprintf=[ '[1]' => "<a href='{$urls.pages.identity}'>", '[/1]' => "</a>", '%firstname%' => $customer.firstname, '%lastname%' => $customer.lastname ]`
> 
> If you have developer questions about PS feel free to ask me

Your solution does not work with the latest version, same as mine, the parameters are okay for both methods (In my opinion)
The problem is the change in prestashop Controller.php file (You can see the commit in my last post).
In the latest prestashop version was added htmlspecialchars function that for some reason breaks this.

You can test it too...
![image](https://github.com/PrestaShop/PrestaShop/assets/57815173/333c37ba-8270-4c20-a659-4cd0f9e34755)

Please can you re-open it? 
@sallemiines 

Thanks!

**Comment by dnkhack** [comment]
@borjagarciab Please attach your main file I want to research it!

Because htmlspecialchars always was here! 

And I think this is not the spot to discuss this. Contact me by email or GitHub

**Comment by borjagarciab** [comment]
@dnkhack You can replicate it on clean prestashop 8.0.4 with any module...
And is obviously that was not here always ... 
https://github.com/PrestaShop/PrestaShop/commit/8c295183c38ca443f4b93075c6c52d813baa0a11#diff-9f289759f04c7012de8116c55f0d0db2eb1f7da736b2949946fd6076743e2977


@jolelievre I've seen that you commited it, is a mandatory change ? 

Thanks!

**Comment by dnkhack** [comment]
@sallemiines Yes. I tested it is a bug.
code lines
![image](https://github.com/PrestaShop/PrestaShop/assets/35419462/5f05553f-862b-4bfc-a213-a0a0749cabd8)

![image](https://github.com/PrestaShop/PrestaShop/assets/35419462/58f34cb1-3d55-4c84-92f8-102329849b84)

![image](https://github.com/PrestaShop/PrestaShop/assets/35419462/00ef9aa8-0650-4f6e-bc6d-aec56f109104)

**Comment by dnkhack** [comment]
@borjagarciab you can use parameter "_raw" to solve your problem.
`$this->trans('Min and Max number of digits in a phone number separated by a comma. The range is from [1]9 to 15[/1]. For instance | 9,12 | 12,12 | 12-13 | 9-15 |', ['[1]' => '<strong>','[/1]' => '</strong>','_raw' => true,], 'Modules.Dnkphonelogin.General'),`

But as you might notice this feature is deprecated and will be removed in the next major version.
![image](https://github.com/PrestaShop/PrestaShop/assets/35419462/e1afa8c8-9560-4891-b12e-b96385d57653)

You can read about this here
https://devdocs.prestashop-project.org/8/modules/core-updates/8.1/#deprecations
**Introduction of _raw parameter on translations to avoid html escaping in translator.**

https://github.com/PrestaShop/PrestaShop/pull/30415
