### ISSUE TITLE
 Error on the credit note when refunding with a reduction

### ISSUE THREAD

**Issue by cindyasg** [PrestaShop/PrestaShop#32826]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have prestashop version

My PHP version is 7.4

When I want to partially refund a customer who has benefited from a reduction on my site, I check the box "price less the initial reduction voucher"

But when I print the credit, the amounts do not correspond to what I requested. It's as if the discount was not taken into account on the credit note.

Can you help me please ?

![Capture d’écran 2023-06-05 à 10 10 13](https://github.com/PrestaShop/PrestaShop/assets/135114372/bf8c88c8-3504-4efd-af72-6e7746504e0f)

![Capture d’écran 2023-06-05 à 10 04 32](https://github.com/PrestaShop/PrestaShop/assets/135114372/a8c69db3-79d5-43e7-901a-f7830bbcd8ac)

### Expected behavior

It is important for us to have this credit note with the right amount for the accountant.

### Steps to reproduce

Click on a sales order that received a discount

Click on "partially refund"

Enter the quantity in question and the corresponding shipping costs.

Check "Generate a credit note"

In the section "choose the amount you wish to refund, tick "Price of the products, reduced by the amount of the initial reduction voucher"

Validate by clicking on "Partially refunded"

Download the credit note corresponding to this refund and you will see the error of amount that does not correspond.

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.4

### Your company or customer's name goes here (if applicable).

Company : La Madeleine Deco and customer's name is Caroline Bret

**Comment by dnkhack** [comment]
Hello, this is not the bug. When you use a partial refund the invoice in orders leaves off the same. Go to "Credit Slips" and you can download the corresponding invoice!

![image](https://github.com/PrestaShop/PrestaShop/assets/35419462/b837e67a-d5e1-4661-be52-04a47b4fa083)

**Comment by sallemiines** [comment]
Hello 

@dnkhack Thank you for your feedback ! 

@cindyasg could you please check @dnkhack response in the previous [comment](https://github.com/PrestaShop/PrestaShop/issues/32826#issuecomment-1576541513)  and inform us if it's seems to your problem  solution ? 

Waiting for your feedback ! 
Thank you !

**Comment by cindyasg** [comment]
Hello 
Thanks @dnkhack but when i download the credit slip the amount is not correct as you can see : 

The order is about 339,10€ 

The credit slip is 375€ 

The discount is 35,90€ 

My client's purchase is €339.10.

So the credit slip takes the amount of the order + the reduction of €35.90

![243311583-bf8c88c8-3504-4efd-af72-6e7746504e0f](https://github.com/PrestaShop/PrestaShop/assets/135114372/5e00b449-6bdf-49fa-8f71-6e2634e45082)

**Comment by dnkhack** [comment]
@cindyasg I apologize, for the difficulty understanding the language on your screenshots!

I can't reproduce your issue.
My Orders and credit slips look following 

![image](https://github.com/PrestaShop/PrestaShop/assets/35419462/c53b2866-84da-4008-848f-5322d07d659d)

![image](https://github.com/PrestaShop/PrestaShop/assets/35419462/cb0d9c55-e4a6-4339-9198-1ecf1d54db39)

![image](https://github.com/PrestaShop/PrestaShop/assets/35419462/b24ea039-4cbd-447e-ac94-fb81164d1b5b)

I see on the screenshot you have external payment modules. Have they overrides or HOOKS which have an effect on price calculation on Invoices? Can you clarify the details about taxes on your screenshot?

**Comment by cindyasg** [comment]
I can't change the language i'm sorry. We have exactly the same screen but you test the issues on a order taht doesn't have a reduction, my probleme is only when i wan't to refund a client that have a discount code

**Comment by cindyasg** [comment]
When i do the refound on the back office, the amount is correct, the probleme seems to be when i download the credit slip, the PDF is incorrect

**Comment by florine2623** [comment]
Hello @cindyasg 

Is your issue similar to https://github.com/PrestaShop/PrestaShop/issues/18319 or https://github.com/PrestaShop/PrestaShop/issues/16826 ?

**Comment by MatShir** [comment]
@dnkhack you missed the discount in your steps

**Comment by florine2623** [comment]
Hello @cindyasg ,

Since we had no news from you for more than 30 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Comment by anthonypare** [comment]
The problem persists in PrestaShop 9. I manage to reproduce the same bug on a fresh install. It's problematic for customers that use PrestaShop for accounting...
