### ISSUE TITLE
Statistic Bug

### ISSUE THREAD

**Issue by KaeligBrl** [PrestaShop/PrestaShop#32823]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Good morning,
I have a native problem on prestashop.
My online visitors are not showing up and I don't have the conversion rate, everything is 0.
Of course, I have orders on the site. I reset the stats modules and reinstalled but nothing happened :)
Do you know what it could be?
Link screen cast: https://www.loom.com/share/45f9570563f04e15aa19db4a8913b005
Link screenshot: https://prnt.sc/oImJzrQhqOOw
Sincerely

### Steps to reproduce

Go to Dashboard

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.1.33

### If your bug is related to a module, specify its name and its version

dashactivity, statslive, statslive

**Comment by sallemiines** [comment]
Hello @KaeligShebam 

Thank you for submitting this issue

Your issue is duplicate [#32823]( https://github.com/PrestaShop/PrestaShop/issues/31321) and fixed with the module **bestsellers V2.1.5**  which is  not released yet ! 

You can check this[ PR#31752](https://github.com/PrestaShop/PrestaShop/pull/31752) on develop  ( fixed 9.0.0 not released )

Please check and feedback ! 
Thank you !

**Comment by KaeligBrl** [comment]
> Hello @KaeligShebam
> 
> Thank you for submitting this issue
> 
> Your issue is duplicate [#32823](https://github.com/PrestaShop/PrestaShop/issues/31321) and fixed with the module **bestsellers V2.1.5** which is not released yet !
> 
> You can check this[ PR#31752](https://github.com/PrestaShop/PrestaShop/pull/31752) on develop ( fixed 9.0.0 not released )
> 
> Please check and feedback ! Thank you !

Hello, the current site I showed you was migrated to change the design. Version 1 worked fine ;)

**Comment by KaeligBrl** [comment]
Hello The bug is fixed 😉

 

Cordialement,


 

De : ines sallemi ***@***.***> 
Envoyé : lundi 5 juin 2023 11:28
À : PrestaShop/PrestaShop ***@***.***>
Cc : KaeligShebam ***@***.***>; Mention ***@***.***>
Objet : Re: [PrestaShop/PrestaShop] Statistic Bug (Issue #32823)

 

Hello @KaeligShebam <https://github.com/KaeligShebam> 

Thank you for submitting this issue

Your issue is duplicate #32823 <https://github.com/PrestaShop/PrestaShop/issues/31321>  and fixed with the module bestsellers V2.1.5 which is not released yet !

You can check this PR#31752 <https://github.com/PrestaShop/PrestaShop/pull/31752>  on develop ( fixed 9.0.0 not released )

Please check and feedback !
Thank you !
