### ISSUE TITLE
Error productsAlreadyTagged is not defined with latest blockwishlist

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#32838]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I get the error `productsAlreadyTagged is not defined` with the latest blockwishlist module.
I can't reproduce it locally, but I get the error regularly in my customer's navigator. The error seems to happen here 
``` 
<script type="text/javascript">
   document.addEventListener("DOMContentLoaded", function(){
   if(productsAlreadyTagged.length) document.getElementById('wishlist_header').classList.remove('d-none')
   })
</script>
```
It should be `if(productsAlreadyTagged && productsAlreadyTagged.length)`

![2023-06-06_120652](https://github.com/PrestaShop/PrestaShop/assets/7520695/a7661233-7089-48e2-98e7-2bf0ee6ae51b)

### Expected behavior

I expect that there is no javascript error in my customer's navigators.

### Steps to reproduce

I get the errors in my Sentry log. They are happening on my customer's navigator and not locally.

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

any

### If your bug is related to a module, specify its name and its version

blockwishlist 3.0.0

### Your company or customer's name goes here (if applicable).

Société Biblique de Genève

**Comment by florine2623** [comment]
Hello @lmeyer1 ,

I can't reproduce the issue using 8.0.4 and blockwishlist 3.0.0. I'm checking the error in the console, bit i don't have the same as yours.

Is there another way to reproduce the issue without Sentry ?

**Comment by lmeyer1** [comment]
@florine2623 
There are two aspects:
1. There is an obvious way to fix the error as indicated in the description
2. This error happens with some but not all customers.

As of sentry, this is just a tool to be informed about all the bugs that happen in production, either on client or server side. As such it has no effect IF an bug happens or not, it's sole effect is that I'm aware of it.

> I can't reproduce the issue

Me neither, I was not able to reproduce it locally

> Is there another way to reproduce the issue without Sentry ?

It happens frequently and regularly. Unfortunately I don't know under which circumstances exactly. As I ignore the circumstances, I can't give detailed steps to reproduce. As it really happens often and regularly, there should be ways to reproduce.

By the way, I'm actively testing an alternative to your blockwishlist module. This is not the only problem with it, and I'm largely unsatified with it . Primarily because it is IMHO, and sorry to tell it, it is bloatware.

**Comment by djoelleuch** [comment]
Hello @lmeyer1  ,

I can't reproduce the issue  neither  ..

If you find something, you can reopen , we will close the issue .

thank you  !

**Comment by lmeyer1** [comment]
OK. Thanks @djoelleuch @florine2623

**Comment by lmeyer1** [comment]
I understand now, why you couldn't reproduce this issue. It is related to a custom integration of wishlist in the classic-rocket template.
Sorry for bothering you.
