### ISSUE TITLE
error in cache key name

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#32837]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In Hook.php, method getAllHookIds, the `$cacheId` is wrong for `with aliases`. It is `'hook_idsbynamehook_idsbyname_withalias'` instead of `'hook_idsbyname_withalias'`.
https://github.com/PrestaShop/PrestaShop/blob/32b958d86912b5ece2087e307dfc6aca9c7ba385/classes/Hook.php#L1223

The correct cache ids are 'hook_idsbyname' without aliases and 'hook_idsbyname_withalias' with, as ussed elsewhere, see https://github.com/PrestaShop/PrestaShop/blob/32b958d86912b5ece2087e307dfc6aca9c7ba385/classes/Hook.php#L126

### Expected behavior

 The correct name is `'hook_idsbyname_withalias'`.

### Steps to reproduce

Look at the two lines. The error is obvious. https://github.com/PrestaShop/PrestaShop/blob/32b958d86912b5ece2087e307dfc6aca9c7ba385/classes/Hook.php#L1223
https://github.com/PrestaShop/PrestaShop/blob/32b958d86912b5ece2087e307dfc6aca9c7ba385/classes/Hook.php#L126

### PrestaShop version(s) where the bug happened

1.7.7 - develop

### PHP version(s) where the bug happened

any

### Your company or customer's name goes here (if applicable).

Société Biblique de Genève

**Comment by florine2623** [comment]
@PrestaShop/prestashop-core-developers 

Can you confirm this issue ?
