### ISSUE TITLE
Admin -  cannot change products positions in categories at version 8.1

### ISSUE THREAD

**Issue by kacpirdt** [PrestaShop/PrestaShop#32833]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Product position Reordering is gone in version 8.1. It was still awailable 8.04. This is extremly important, because there is needed to change product display positions in categories

![Screenshot 2023-06-06 at 07 21 53](https://github.com/PrestaShop/PrestaShop/assets/135665287/2a1059c7-84c2-4599-98a9-8d5065bbaf15)

![Screenshot 2023-06-06 at 07 23 31](https://github.com/PrestaShop/PrestaShop/assets/135665287/21074f09-2256-475c-b24c-37f3118530b9)

### Expected behavior

Display the button "Reorder" only.
When the button is pressed, display the drag and drop icon on the list.

![Capture d’écran 2023-07-19 à 16 26 26](https://github.com/PrestaShop/PrestaShop/assets/43613217/bcba93dd-e1a3-4b27-a20a-4adb1f56cdeb)

and 

![Screenshot 2023-06-06 at 07 23 31](https://github.com/PrestaShop/PrestaShop/assets/135665287/21074f09-2256-475c-b24c-37f3118530b9)

### Steps to reproduce

GO to admin Products -> select category -> try to change positions of products

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

8.1

**Comment by paulnoelcholot** [comment]
Hello,

I reproduce the issue with PrestaShop version 8.1. I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/4f9b58ed-0eb5-4d89-b197-c413c2e95046)

**Comment by kacpirdt** [comment]
Thank you. We are waiting ver 8.1 to launch our new webstore. And we are extremly using the category product positioning.
I'm now programmer myself, so I'm not abel to fix this issue. I hope it will be fixed 8.1

**Comment by MatShir** [comment]
In fact, the feature is still present ! 🥳 
You have to sort by position and then you can drag and drop. The drag and drop feature is placed near the ID column. On 8.1, the feature has changed. 

<img width="1263" alt="Capture d’écran 2023-06-07 à 09 15 23" src="https://github.com/PrestaShop/PrestaShop/assets/43613217/e5cb3548-244e-4b00-bd3c-071b317d3bc1">
 
So, I will put the severity to trivial BUT we will work on it on th next patch version after the release of 8.1 to improve the UI.
Thanks for the report.

**Comment by kacpirdt** [comment]
Thank you for info. This works indeed

**Comment by ElodieOS** [comment]
Hello everyone! 
Yes, I think it's a little bit complicated to find this functionality when you're not used to it. I suggest keeping the first filter by category and, when it activated, sorting directly by position. With this, you can display the drag and drop icon permanently and limit the number of interactions to reorganise your products. We're keeping the first part of the route (filter by categories), which is already familiar to users, and adapting the second to make drag and drop more straightforward.

The advantage is that this behaviour adapts to all tables that use drag and drop. You can maintain consistency throughout the course of the journey. What's more, this system does not block other user actions. They can always sort the other elements as they see fit. 

Wdyt?

![image](https://github.com/PrestaShop/PrestaShop/assets/113457393/d323d73e-8de6-469c-bc6f-fa773fb8d257)
![image](https://github.com/PrestaShop/PrestaShop/assets/113457393/735f714f-05af-43c1-8660-329f9cd46fa0)

**Comment by MatShir** [comment]
Thanks for design :)
I like the idea @ElodieOS

**Comment by kpodemski** [comment]
I'm afraid I have to disagree that filtering by category should automatically change sorting to position. The solution should be to display the button instead of this useless search input as it was in previous versions.

We discussed it @MatShir

**Comment by MatShir** [comment]
I forgot the button. True, we can really see the feature @ElodieOS. Since now for each changes of position it is directly saved the button "saved" is not needed but the "sort" could be used to highlight the feature. WDYT?

**Comment by ElodieOS** [comment]
We add a click with this method, but it was the initial method, so we know it works
