### ISSUE TITLE
Can't override front Controllers PS8.1 and don't see modules classes

### ISSUE THREAD

**Issue by dnkhack** [PrestaShop/PrestaShop#32839]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Module development. Module using an override. An override not working getting errors. And overridden classes don't see main classes from modules! Indeed for 
/override/controllers/front/AuthController.php
/override/controllers/front/IdentityController.php
/override/controllers/front/PasswordController.php
/classes/checkout/CheckoutPersonalInformationStep.php

For example /override/controllers/front/AuthController.php
code
`class AuthController extends AuthControllerCore
{
    /*
    * module: dnkphonelogin
    * date: 2023-06-06 11:32:14
    * version: 1.0.0
    */
    public function initContent()
    {
        parent::initContent();
    }
}`

![image](https://github.com/PrestaShop/PrestaShop/assets/35419462/3abd3d2c-effa-4777-8d9f-d8bc64061ee8)

getting the error
![image](https://github.com/PrestaShop/PrestaShop/assets/35419462/e99e5dcb-7df9-4d2a-a104-294281db6908)

Example with modules class uses
![image](https://github.com/PrestaShop/PrestaShop/assets/35419462/7487d1cf-a909-4892-8d5c-69cf8cb676cd)

![image](https://github.com/PrestaShop/PrestaShop/assets/35419462/b4b50b9d-f5db-4701-81d5-5c2687aab7c8)

I understand that the problem with the class static method Dnkphonelogin::checkPhoneNumber(); can be solved 
like this `        if (Module::isEnabled('dnkphonelogin') && ($dnkphonelogin = Module::getInstanceByName('dnkphonelogin')) && Validate::isLoadedObject($dnkphonelogin)) {
            $dnkphonelogin::checkPhoneNumber();
        }`

But the problem is not in the module class.

### Expected behavior

Ordinary behavior for class overriding.

### Steps to reproduce

1. create the file to override class /override/controllers/front/AuthController.php
2. add code `class AuthController extends AuthControllerCore
{
    public function initContent()
    {
        parent::initContent();
    }
}`
3. Clear PS cache 
4. Go to Front Office
5. Click "Sign in" to the customer account
6. Fill in login form fields with random data. Correct email format, and password.
7.  Click "Login" 

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

7.4

### Your company or customer's name goes here (if applicable).

DNK Soft

**Comment by paulnoelcholot** [comment]
Hello,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by Hlavtox** [comment]
Ping @PrestaShop/committers

**Comment by kpodemski** [comment]
Hello @dnkhack 

Two of your errors don't seem to be related to overrides. The first clearly says that you're using a method that is no longer available in PrestaShop 8.1 because it was removed in PrestaShop 8.0.

I suggest you read notable changes for PrestaShop 8.0 and 8.1:
https://devdocs.prestashop-project.org/8/modules/core-updates/8.0/
https://devdocs.prestashop-project.org/8/modules/core-updates/8.1/

**Comment by dnkhack** [comment]
@kpodemski My bad. I was not very attentive. I was Thank you very much for explaining and for your time!
Have a good one :)
