### ISSUE TITLE
hook validateCustomerFormFields is not launched if a module add a field with hookAdditionalCustomerFormFields by reference

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#32847]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

cf https://github.com/PrestaShop/PrestaShop/pull/13119#issuecomment-579496517

### Steps to reproduce

1. add a new field in hookAdditionalCustomerFormFields by using fields parameter by reference and don't return anything
2. the hook validateCustomerFormFields is not launched for this new field

### PrestaShop version(s) where the bug happened

1.7.7 to 8.1

### PHP version(s) where the bug happened

all

### Your company or customer's name goes here (if applicable).

Creabilis

**Comment by florine2623** [comment]
Hello @jf-viguier ,

Could you share more explicit steps to reproduce the issue please ?

Or does it need to be tested by a dev ?

**Comment by jf-viguier** [comment]
@florine2623 yes it has to be confirmed by a dev.
Everything is explain here https://github.com/PrestaShop/PrestaShop/pull/13119

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers Could someone please try to reproduce the issue :pray: 
Thanks in advance

**Comment by kpodemski** [comment]
@jf-viguier this hook always expected `FormField` array to be returned 🤔

**Comment by hibatallahAouadni** [comment]
Hello @jf-viguier 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by jf-viguier** [comment]
> @jf-viguier this hook always expected FormField array to be returned 🤔
@kpodemski maybe, the documentation seems not clear enougth, I've found a module that doesn't return anything.
