### ISSUE TITLE
[BlockWishList] `wishlist-button-add` & the list of `My wishlists` are not displayed on dev branch

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#32844]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After cloning the module from this repo https://github.com/PrestaShop/blockwishlist and executing these commands:

1. `composer install`
2. `npm i && npm run build`

And installing the module in **BO**, access to **FO** and you will see that there's no `wishlist-button-add` displayed. Try to access to the customer profile > `My wishlists`, you will find the block empty.

![image](https://github.com/PrestaShop/PrestaShop/assets/23308427/b947bef9-2180-4a2f-a5b4-2f9d3440078f)

![image](https://github.com/PrestaShop/PrestaShop/assets/23308427/f557e120-a2d4-4579-98c3-bda6fd20a512)

### Expected behavior

The `wishlist-button-add` and the list of `My wishlists` should be displayed.

![image](https://github.com/PrestaShop/PrestaShop/assets/23308427/0d8defd5-6c68-46c2-81a8-71949873ba0f)

![image](https://github.com/PrestaShop/PrestaShop/assets/23308427/32c79489-94e2-4e61-b342-90d37b9c3c91)

### Steps to reproduce

1. `cd modules`
2. `git clone https://github.com/PrestaShop/blockwishlist.git`
3. `cd blockwishlist`
4. `composer install`
5. `npm i && npm run build`
6. BO>Modules>Module Manager
7. Search the module, then click on Install button
8. FO> see error > the `wishlist-button-add` is not displayed
9. Access to Customer profile > `My wishlists`
10. See error > the block is empty

### PrestaShop version(s) where the bug happened

1.7.8.9 & 8.0.4

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

blockwishlist (dev branch) 3.0.1

### Your company or customer's name goes here (if applicable).

PrestaShop

**Comment by paulnoelcholot** [comment]
Hello @hibatallahAouadni,

I tried to reproduce this issue but I can't. If I try to make this change before creating the shop, I have this error during installation: 
![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/923e5f88-68d7-4415-a388-92ef8cfab22b)

And if I make the change after an installation, I haven't an issue. 
![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/44ebb655-1e66-4100-b48a-394acb7518db)

@AureRita can you try to reproduce, please?

**Comment by leemyongpakvn** [comment]
@hibatallahAouadni FYI, blockwishlist dropped support for PS 1.7 since [v3.0.0](https://github.com/PrestaShop/blockwishlist/pull/209/files#diff-2a0af5782eb21ffa80caa7694114e129a6d3a4f3f5f03030d0f86e514f6e85bc)
And don't forget to switch to Node14 or Node16 before running `npm` commands. Posting the result of `npm` commands will be helpful to debug :)

**Comment by florine2623** [comment]
Hello @hibatallahAouadni @paulnoelcholot ,

I tried to reproduce the issue but I can't.
Tested with PS 8.0.4 and PHP 7.4 and PHP 8.1.

I `rm -rf` the blockwishlist module before following your steps.
On step 7, I don't have the install button, but the Upgrade button :
<img width="1070" alt="Screenshot 2023-06-08 at 14 52 20" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/58b41975-f175-40eb-8471-6e23f7f9ce95">

After upgraded the module to 3.0.1, I checked the FO and it was like usual. I have access to wishlist-button-add and My wishlist in my customer account.

**Comment by leemyongpakvn** [comment]
@hibatallahAouadni 
Before step 2. `git clone https://github.com/PrestaShop/blockwishlist.git`, we need to remove blockwishlist directory by `rm -rf` in terminal, or Uninstall in BO.
Before step 5. `npm i && npm run build`, we need switch to Node16 with 'nvm use 16'.
With these 2 additional steps, I see wishlist-button-add and My wishlist show and work as usual, on both PS 8.0.4 and PS 8.1.0.

**Comment by hibatallahAouadni** [comment]
Hello @leemyongpakvn 

> Before step 2. git clone https://github.com/PrestaShop/blockwishlist.git, we need to remove blockwishlist directory by rm -rf in terminal, or Uninstall in BO.

I already did it :wink: and yet I encountered the issue.
> Before step 5. npm i && npm run build, we need switch to Node16 with 'nvm use 16'.

Why Node16? we can't use Node14? :confused: 

Thanks!

**Comment by leemyongpakvn** [comment]
@hibatallahAouadni We can use Node14 as well. I suggested Node 16 because Node14 became unmaintained since 30 Apr 2023, and just want to make sure that you don't use Node18 or Node20 to build asset ;)
If you still encountered the issue after applying these 2 additional steps, then we can use these 2 traditional steps: BO - Performance > Clear cache, and FO - clear Browser cache :pray:

**Comment by M0rgan01** [comment]
@hibatallahAouadni  After several tries, I can't reproduce the error. On PS 8.04 I performed the following operations:

1. Have a fresh installation
2. Uninstalled the blockwishlist module (with the force delete option) on the module manager of the BO
3. Clone blockwishlist  from https://github.com/PrestaShop/blockwishlist.git (dev branch) and install dependencies
4. Install the module from module manger
5. FO is correct

**Comment by MhiriFaten** [comment]
@hibatallahAouadni I tried to reproduce, despite our efforts, we were not able to reproduce your issue with the provided information

8.1.0 :x: 

[Untitled_ Aug 4, 2023 10_10 AM.webm](https://github.com/PrestaShop/PrestaShop/assets/111756615/06d9884a-57a9-44f1-a3c7-d7ddd556f163)

8.0.4 :x: 

[Untitled_ Aug 4, 2023 9_48 AM.webm](https://github.com/PrestaShop/PrestaShop/assets/111756615/bfeedae5-c91f-478b-a8e9-2e238f57f67c)

I will close this issue.
