### ISSUE TITLE
Bump minimum compatibility to PHP 7.1.3 and PS 1.7.7 for Native Modules

### ISSUE THREAD

**Issue by leemyongpakvn** [PrestaShop/PrestaShop#32841]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Many native modules are keeping support for PHP 5.6 or even PHP 5.4 like [ps_imageslider](https://github.com/PrestaShop/ps_imageslider/blob/v3.1.2/composer.json), [ps_languageselector](https://github.com/PrestaShop/ps_languageselector/blob/v2.1.3/composer.json), and many others :). It is a security issue because PHP 5.6 was EOL since 31 Dec 2018, and it also [prevents phpstan 0.12 running inside composer.json](https://github.com/PrestaShop/ps_languageselector/blob/v2.1.3/tests/phpstan.sh). 
Beside that, we need to drop [PHP test for PHP 5.6 and PS 1.7.6 and previous version](https://github.com/PrestaShop/ps_languageselector/blob/v2.1.3/.github/workflows/php.yml) also.
- [x] blockreassurance
- [x] blockwishlist
- [x] pagesnotfound
- [x] productcomments
- [x] ps_emailalerts
- [ ] ps_facetedsearch
- [x] ps_googleanalytics
- [ ] ps_imageslider
- [ ] ps_languageselector
- [x] ps_linklist
- [ ] ps_mainmenu
- [ ] ps_newproducts
- [ ] ps_searchbar
- [ ] ps_sharebuttons

Progi1984 already bumped min compat to PHP 7.2 and PS 8.0 for blockwishlist and ps_linklist. I will apply changes for a dozen of modules, other contributors are welcomed to do the rest ;)

### Expected behavior

Bump minimum compatibility to PHP 7.1.3 and PS 1.7.7 in composer.json.
Drop PHP test for PHP 5.4 and PS 1.7.6 and previous version.

### Steps to reproduce

Please check links in Description.

### PrestaShop version(s) where the bug happened

1.7.4, 1.7.5, 1.7.6

### PHP version(s) where the bug happened

PHP 5.6

**Comment by paulnoelcholot** [comment]
Hello,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by matks** [comment]
Hello @leemyongpakvn I think it's a great idea 👍 

In a module, we cannot mark "this module is NOT compatible with PHP {...}" (we can mark it in composer.json but it will not be scanned by PrestaShop) however we can mark "this module compatibility range is {...} to {...}"

As each Core version has a dedicated PHP range, it follows.

For example if you say the module minimum Core version is 1.7.7, as [1.7.7 min PHP version is 7.1](https://devdocs.prestashop-project.org/1.7/basics/installation/system-requirements/) then it can be understood as "the module minimum PHP version is 7.1"

I love this idea, but to be sure let me ask the opinion of @PrestaShop/committers

**Comment by M0rgan01** [comment]
Indeed, I have already gone through modules in php 5.4 and with older versions of phpstan.
I also think there is work to be done on php versions and some dependencies in modules.

The PHP version of the modules must follow the PHP version of prestashop, taking into account their compatibility range.

**Comment by kpodemski** [comment]
I like the idea.

**Comment by leemyongpakvn** [comment]
@matks I chose PHP 7.1.3 and PS 1.7.7 because of this [composer.json](https://github.com/PrestaShop/PrestaShop/blob/1.7.7.x/composer.json#L6).
Furthermore, I suggest removing 
```
    "platform": {
      "php": "5.6"
    }

```
from module's composer.json. That way, we can keep support for PHP 7.1.3 and PS 1.7.7 in **production** environment (merchants won't be shocked ;), while allow devs using php-dev-tools v4 and php-cs-fixer v3 (those require PHP 7.2) in **development** environment.

**Comment by boherm** [comment]
@leemyongpakvn, it seems to be a good idea to me for PHP 7.1 instead of oldies versions.

**Comment by kpodemski** [comment]
@leemyongpakvn yes, that's a good idea, because if you have platform requirement composer will throw you a warning if you don't meet requirements, so if we have:
```
   "platform": {
      "php": "5.6"
    }
```
and you, for example, generate autoloader, i'll check whether the version of PHP is correct

**Comment by matks** [comment]
Idea approved 👍 and I change the labels: it's not a Bug it's a Feature

**Comment by Hlavtox** [comment]
Full list:

| Module         | Min version | Status
| ----------------- | ----------------- | -----------------
| [ps_googleanalytics](https://github.com/PrestaShop/ps_googleanalytics) | 1.7.7 | OK
| [blockreassurance](https://github.com/PrestaShop/blockreassurance) | 1.7.7 | OK
| [ps_themecusto](https://github.com/PrestaShop/ps_themecusto) | 1.7 | Needs bump
| [autoupgrade](https://github.com/PrestaShop/autoupgrade) | 1.7.0.0 | Needs bump
| [ps_bestsellers](https://github.com/PrestaShop/ps_bestsellers) | 1.7.0.0 | Needs bump
| [ps_brandlist](https://github.com/PrestaShop/ps_brandlist) | 1.7.0.0 | Needs bump
| [ps_categoryproducts](https://github.com/PrestaShop/ps_categoryproducts) | 1.7.0.0 | Needs bump
| [ps_newproducts](https://github.com/PrestaShop/ps_newproducts) | 1.7.0.0 | Needs bump
| [ps_specials](https://github.com/PrestaShop/ps_specials) | 1.7.0.0 | Needs bump
| [ps_supplierlist](https://github.com/PrestaShop/ps_supplierlist) | 1.7.0.0 | Needs bump
| [ps_viewedproduct](https://github.com/PrestaShop/ps_viewedproduct) | 1.7.0.0 | Needs bump
| [dashgoals](https://github.com/PrestaShop/dashgoals) | 1.7.1.0 | Needs bump
| [graphnvd3](https://github.com/PrestaShop/graphnvd3) | 1.7.1.0 | Needs bump
| [gridhtml](https://github.com/PrestaShop/gridhtml) | 1.7.1.0 | Needs bump
| [gsitemap](https://github.com/PrestaShop/gsitemap) | 1.7.1.0 | Needs bump
| [pagesnotfound](https://github.com/PrestaShop/pagesnotfound) | 1.7.7 | OK
| [ps_banner](https://github.com/PrestaShop/ps_banner) | 1.7.1.0 | Needs bump
| [ps_categorytree](https://github.com/PrestaShop/ps_categorytree) | 1.7.7 | OK
| [ps_customersignin](https://github.com/PrestaShop/ps_customersignin) | 1.7.1.0 | Needs bump
| [ps_emailsubscription](https://github.com/PrestaShop/ps_emailsubscription) | 1.7.1.0 | Needs bump
| [ps_featuredproducts](https://github.com/PrestaShop/ps_featuredproducts) | 1.7.1.0 | Needs bump
| [ps_languageselector](https://github.com/PrestaShop/ps_languageselector) | 1.7.1.0 | Needs bump
| [ps_mainmenu](https://github.com/PrestaShop/ps_mainmenu) | 1.7.1.0 | Needs bump
| [ps_sharebuttons](https://github.com/PrestaShop/ps_sharebuttons) | 1.7.1.0 | Needs bump
| [ps_shoppingcart](https://github.com/PrestaShop/ps_shoppingcart) | 1.7.1.0 | Needs bump
| [statsbestcustomers](https://github.com/PrestaShop/statsbestcustomers) | 1.7.1.0 | Needs bump
| [statsbestmanufacturers](https://github.com/PrestaShop/statsbestmanufacturers) | 1.7.1.0 | Needs bump
| [statsbestsuppliers](https://github.com/PrestaShop/statsbestsuppliers) | 1.7.1.0 | Needs bump
| [statscarrier](https://github.com/PrestaShop/statscarrier) | 1.7.1.0 | Needs bump
| [statsdata](https://github.com/PrestaShop/statsdata) | 1.7.1.0 | Needs bump
| [statscheckup](https://github.com/PrestaShop/statscheckup) | 1.7.1.0 | Needs bump
| [statsnewsletter](https://github.com/PrestaShop/statsnewsletter) | 1.7.1.0 | Needs bump
| [statspersonalinfos](https://github.com/PrestaShop/statspersonalinfos) | 1.7.1.0 | Needs bump
| [statsregistrations](https://github.com/PrestaShop/statsregistrations) | 1.7.1.0 | Needs bump
| [statssearch](https://github.com/PrestaShop/statssearch) | 1.7.1.0 | Needs bump
| [contactform](https://github.com/PrestaShop/contactform) | 1.7.2.0 | Needs bump
| [ps_contactinfo](https://github.com/PrestaShop/ps_contactinfo) | 1.7.2.0 | Needs bump
| [ps_crossselling](https://github.com/PrestaShop/ps_crossselling) | 1.7.2.0 | Needs bump
| [ps_dataprivacy](https://github.com/PrestaShop/ps_dataprivacy) | 1.7.2.0 | Needs bump
| [ps_customeraccountlinks](https://github.com/PrestaShop/ps_customeraccountlinks) | 1.7.4.0 | Needs bump
| [ps_imageslider](https://github.com/PrestaShop/ps_imageslider) | 1.7.5 | Needs bump
| [ps_socialfollow](https://github.com/PrestaShop/ps_socialfollow) | 1.7.4.0 | Needs bump
| [ps_currencyselector](https://github.com/PrestaShop/ps_currencyselector) | 1.7.5.0 | Needs bump
| [ps_customtext](https://github.com/PrestaShop/ps_customtext) | 1.7.5.0 | Needs bump
| [productcomments](https://github.com/PrestaShop/productcomments) | 1.7.8 | OK
| [dashproducts](https://github.com/PrestaShop/dashproducts) | 1.7.6.0 | Needs bump
| [dashtrends](https://github.com/PrestaShop/dashtrends) | 1.7.6.0 | Needs bump
| [ps_cashondelivery](https://github.com/PrestaShop/ps_cashondelivery) | 1.7.6.0 | Needs bump
| [ps_emailalerts](https://github.com/PrestaShop/ps_emailalerts) | 1.7.6.0 | Needs bump
| [ps_facetedsearch](https://github.com/PrestaShop/ps_facetedsearch) | 1.7.6.0 | Needs bump
| [ps_faviconnotificationbo](https://github.com/PrestaShop/ps_faviconnotificationbo) | 1.7.6.0 | Needs bump
| [ps_checkpayment](https://github.com/PrestaShop/ps_checkpayment) | 1.7.6.0 | Needs bump
| [ps_wirepayment](https://github.com/PrestaShop/ps_wirepayment) | 1.7.6.0 | Needs bump
| [statsbestcategories](https://github.com/PrestaShop/statsbestcategories) | 1.7.6.0 | Needs bump
| [statsbestproducts](https://github.com/PrestaShop/statsbestproducts) | 1.7.6.0 | Needs bump
| [statsbestvouchers](https://github.com/PrestaShop/statsbestvouchers) | 1.7.6.0 | Needs bump
| [statscatalog](https://github.com/PrestaShop/statscatalog) | 1.7.6.0 | Needs bump
| [statsforecast](https://github.com/PrestaShop/statsforecast) | 1.7.6.0 | Needs bump
| [statsproduct](https://github.com/PrestaShop/statsproduct) | 1.7.6.0 | Needs bump
| [statssales](https://github.com/PrestaShop/statssales) | 1.7.6.0 | Needs bump
| [statsstock](https://github.com/PrestaShop/statsstock) | 1.7.6.0 | Needs bump
| [welcome](https://github.com/PrestaShop/welcome) | 1.7.6.0 | Needs bump
| [dashactivity](https://github.com/PrestaShop/dashactivity) | 1.7.7.0 | OK
| [ps_searchbar](https://github.com/PrestaShop/ps_searchbar) | 1.7.8.0 | OK
| [blockwishlist](https://github.com/PrestaShop/blockwishlist) | 8.0.0 | OK
| [psgdpr](https://github.com/PrestaShop/psgdpr) | 8.0.0 | OK
| [ps_distributionapiclient](https://github.com/PrestaShop/ps_distributionapiclient) | 8.0.2 | OK
| [ps_linklist](https://github.com/PrestaShop/ps_linklist) | 9.0.0 | OK
