### ISSUE TITLE
BO - cannot clear filters when we Filter by empty category

### ISSUE THREAD

**Issue by aniszr** [PrestaShop/PrestaShop#32858]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you create a new empty Category(there is no products assigned to this category), and try to filter products by the category that you  just created, you can observe that you can’t clear the filter you just used and you can’t display the rest of products, the only way out of this issue is to create a new product and assign it to the empty category so you can get the normal display in which you have clear filter option and Filter by categories drop-down list.

See attached screenrecord :

https://github.com/PrestaShop/PrestaShop/assets/92626242/4202cbe2-a6f0-4653-b46f-de5136a39bb7

### Expected behavior

See attached screen shot (PrestaShop 8.0.4)
![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/522c37a8-a0db-4122-9083-bc9f563f4723)

### Steps to reproduce

1. BO > Catalog > Categories 
2. Click on Add new category button > Click on Save button
3. Catalog > Products 
4. Select the category name you just created in Filter by categories  drop-down list
5. See error > `Clear filter` option and `Filter by categories` drop-down list are not displayed
6. Click on Create new product button 
7. Create a random product and assign it to the category you've chosen as a filter

### PrestaShop version(s) where the bug happened

8.1.x & develop

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello @aniszr ,

I think this is a improvement But to be sure, we should ping @PrestaShop/product-team to get their view on this.

On product page, when filtering on a category without product, this page is displayed. Is that alright ?
<img width="1440" alt="Screenshot 2023-06-07 at 18 18 47" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/7b3ca160-a4ef-4df5-9b5f-dd06ea4cc292">

Or should it be like like previous versions :
<img width="1231" alt="Screenshot 2023-06-07 at 18 19 29" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/64cf691c-77c2-4404-b6fb-9385dab17b65">

**Comment by Hlavtox** [comment]
@florine2623 This is definitely a bug. And there is no way around it.

It basically breaks your product management until you add some product into this category. If you manage to remember the name of the category you selected, because you can't see it.

"Manage your products" should be displayed only if there is no product at all.

Labels set after discussion with @MatShir

**Comment by MatShir** [comment]
It is a regression. It is working well on 8.0.4

**Comment by PululuK** [comment]
fixe by https://github.com/PrestaShop/PrestaShop/pull/32906
thanks
