### ISSUE TITLE
There's No Specifications written

### ISSUE THREAD

**Issue by m4jor101** [PrestaShop/PrestaShop#32856]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

<img width="1440" alt="Screenshot 2023-06-07 at 7 00 27 PM" src="https://github.com/PrestaShop/PrestaShop/assets/70167116/86a60351-a7c7-476c-a38c-2cd86065ce69">

### Expected behavior

I guess there should be a specifications written in this page but it's not there.

### Steps to reproduce

1. Go to https://www.prestashop-project.org/
2. Under Project Documentation go to "Specification"

### PrestaShop version(s) where the bug happened

current version

**Comment by florine2623** [comment]
@Dheeraj-2001 ,

You need to navigate on the left menu.
