### ISSUE TITLE
ps account 6.2.3 caused timeouts when logging into back end admin

### ISSUE THREAD

**Issue by joecoolio66** [PrestaShop/PrestaShop#32857]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After upgrading the ps account module to 6.2.3 (latest), we experienced cloudflare timeouts error 524 when trying to access the dashboard in our admin.  After this, when trying to log back in, we got continued timeouts.  Cloudflare will timeout when an operation takes more than 100 seconds.

We resolved this by reverting the ps accounts module to the version that was in our 8.0.3 back up.  Luckily this worked.

### Expected behavior

There should be no change in prestashop operation when upgrading ANY native module

### Steps to reproduce

Upgrade ps account to 6.2.3 and try to access dashboard or log in.  We are on cloudflare, so we experienced timeouts... if not on cloudflare we assume then that logging in takes more than 100 seconds

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_account

**Comment by joecoolio66** [comment]
More information:  This is what our admin log was showing for this module:

[07-Jun-2023 10:44:02 Canada/Atlantic] PHP Deprecated:  Return type of Ramsey\Collection\AbstractArray::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home2/canadac3/public_html/modules/ps_accounts/vendor/ramsey/collection/src/AbstractArray.php on line 87
[07-Jun-2023 10:44:02 Canada/Atlantic] PHP Deprecated:  Return type of Ramsey\Collection\AbstractArray::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home2/canadac3/public_html/modules/ps_accounts/vendor/ramsey/collection/src/AbstractArray.php on line 87
[07-Jun-2023 10:44:02 Canada/Atlantic] PHP Deprecated:  Ramsey\Uuid\Builder\BuilderCollection implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in /home2/canadac3/public_html/modules/ps_accounts/vendor/ramsey/uuid/src/Builder/BuilderCollection.php on line 32
[07-Jun-2023 10:44:02 Canada/Atlantic] PHP Deprecated:  Ramsey\Uuid\Provider\Node\NodeProviderCollection implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in /home2/canadac3/public_html/modules/ps_accounts/vendor/ramsey/uuid/src/Provider/Node/NodeProviderCollection.php on line 0

**Comment by florine2623** [comment]
Hello @joecoolio66 ,

The latest version os ps_account available on the Market place is v5.4.3.
<img width="998" alt="Screenshot 2023-06-07 at 17 19 08" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/7662bef6-6491-4f4b-9502-cf9b05c829f8">


Can you confirm your version of the module ?

**Comment by joecoolio66** [comment]
6.2.3 was pushed out to us... here's the changelog.  

Changelog
6.2.3

## What\\\'s Changed
* chore: mention which type of token for APIs by @emmanuelgautier in https://github.com/PrestaShopCorp/ps_accounts/pull/342
* feat: add api requests signature by @emmanuelgautier in https://github.com/PrestaShopCorp/ps_accounts/pull/343
**Full Changelog**: https://github.com/PrestaShopCorp/ps_accounts/compare/v6.2.2...v6.2.3
6.2.2

## What\\\'s Changed
* fix: avoid open_basedir restriction by @emmanuelgautier in https://github.com/PrestaShopCorp/ps_accounts/pull/340
**Full Changelog**: https://github.com/PrestaShopCorp/ps_accounts/compare/v6.2.1...v6.2.2
6.2.1

## What\\\'s Changed
* chore: clean assets by @emmanuelgautier in https://github.com/PrestaShopCorp/ps_accounts/pull/338
Configuration changed with testimonials json.
**Full Changelog**: https://github.com/PrestaShopCorp/ps_accounts/compare/v6.2.0...v6.2.1
6.2.0

## What\\\'s Changed
* [ACCOUNT-1799] Update logo for new branding by @atourneriePresta in https://github.com/PrestaShopCorp/ps_accounts/pull/323
* fix: get symfony container by @hschoenenberger in https://github.com/PrestaShopCorp/ps_accounts/pull/331
* chore: update readme by @emmanuelgautier in https://github.com/PrestaShopCorp/ps_accounts/pull/336
* [ACCOUNT-1819] feat: cleanup oauth2 client and user token after shop is unlinked by @hschoenenberger in https://github.com/PrestaShopCorp/ps_accounts/pull/330
* fix: replace throwable with exception by @hschoenenberger in https://github.com/PrestaShopCorp/ps_accounts/pull/334
* [ACCOUNT-1794] branding update by @atourneriePresta in https://github.com/PrestaShopCorp/ps_accounts/pull/326
* chore: deprecate gae staging for preprod new url by @emmanuelgautier in https://github.com/PrestaShopCorp/ps_accounts/pull/337
**Full Changelog**: https://github.com/PrestaShopCorp/ps_accounts/compare/v6.1.7...v6.2.0
6.1.7

## What\\\'s Changed
* fix: update package version to module version by @atourneriePresta in https://github.com/PrestaShopCorp/ps_accounts/pull/324
* [ACCOUNT-1413] feat: ajax get or refresh oauth token from bo by @hschoenenberger in https://github.com/PrestaShopCorp/ps_accounts/pull/319
**Full Changelog**: https://github.com/PrestaShopCorp/ps_accounts/compare/v6.1.6...v6.1.7
6.1.6

## What\\\'s Changed
* chore: keep the same log as support/5.x by @emmanuelgautier in https://github.com/PrestaShopCorp/ps_accounts/pull/321
* [ACCOUNT-1664] feat: custom hooks for shop link & unlink events by @hschoenenberger in https://github.com/PrestaShopCorp/ps_accounts/pull/316
**Full Changelog**: https://github.com/PrestaShopCorp/ps_accounts/compare/v6.1.5...v6.1.6
6.1.5

## What\\\'s Changed
* fix: log without response when response does not exist by @emmanuelgautier in https://github.com/PrestaShopCorp/ps_accounts/pull/317
**Full Changelog**: https://github.com/PrestaShopCorp/ps_accounts/compare/v6.1.4...v6.1.5
6.1.4

## What\\\'s Changed
* [ACCOUNT-1551] feat: add link to centralized account by @antoinemetifeu in https://github.com/PrestaShopCorp/ps_accounts/pull/308
* New Crowdin updates by @devops-prestashop in https://github.com/PrestaShopCorp/ps_accounts/pull/315
**Full Changelog**: https://github.com/PrestaShopCorp/ps_accounts/compare/v6.1.3...v6.1.4
6.1.3

## What\\\'s Changed
* feat: update vue component dependency by @hschoenenberger in https://github.com/PrestaShopCorp/ps_accounts/pull/313
* feat: activate oauth2 logout from config
**Full Changelog**: https://github.com/PrestaShopCorp/ps_accounts/compare/v6.1.2...v6.1.3
6.1.2

## What\\\'s Changed
* New Crowdin updates by @devops-prestashop in https://github.com/PrestaShopCorp/ps_accounts/pull/307
**Full Changelog**: https://github.com/PrestaShopCorp/ps_accounts/compare/v6.1.1...v6.1.2
6.1.1

## What\\\'s Changed
* [ACCOUNT-1629] Wording changes in login page by @aAmorim27 in https://github.com/PrestaShopCorp/ps_accounts/pull/298
* New Crowdin updates by @devops-prestashop in https://github.com/PrestaShopCorp/ps_accounts/pull/302
* fix: load script with defer option by @atourneriePresta in https://github.com/PrestaShopCorp/ps_accounts/pull/290
* [ACCOUNT-1686] fix: regression on PrestaShop original redirect parameter after login by @hschoenenberger in https://github.com/PrestaShopCorp/ps_accounts/pull/299
* [ACCOUNT-1655] Removed link to help center article for employee not found error by @aAmorim27 in https://github.com/PrestaShopCorp/ps_accounts/pull/300
* New Crowdin updates by @devops-prestashop in https://github.com/PrestaShopCorp/ps_accounts/pull/304
**Full Changelog**: https://github.com/PrestaShopCorp/ps_accounts/compare/v6.1.0...v6.1.1
6.1.0

## What\\\'s Changed
* [ACCOUNT-1584] Use navigator language for oauth2 login redirection by @antoinemetifeu in https://github.com/PrestaShopCorp/ps_accounts/pull/295
* feat:oauth2 logout by @hschoenenberger in https://github.com/PrestaShopCorp/ps_accounts/pull/294
* [ACCOUNT-1591] feat:tracking bo login & oauth2 logout by @hschoenenberger in https://github.com/PrestaShopCorp/ps_accounts/pull/292
**Full Changelog**: https://github.com/PrestaShopCorp/ps_accounts/compare/v6.0.5...6.1.0
6.0.5

## What\\\'s Changed
* [ACCOUNT-1583] fix: translations by @antoinemetifeu in https://github.com/PrestaShopCorp/ps_accounts/pull/293
**Full Changelog**: https://github.com/PrestaShopCorp/ps_accounts/compare/v6.0.4...v6.0.5
6.0.4

## What\\\'s Changed
* fix: code coverage regression by @hschoenenberger in https://github.com/PrestaShopCorp/ps_accounts/pull/289
**Full Changelog**: https://github.com/PrestaShopCorp/ps_accounts/compare/v6.0.3...v6.0.4
6.0.3

## What\\\'s Changed
* ci: add tests coverage on the CI by @emmanuelgautier in https://github.com/PrestaShopCorp/ps_accounts/pull/281
* refactor: phpunit setup by @hschoenenberger in https://github.com/PrestaShopCorp/ps_accounts/pull/284
* New Crowdin updates by @devops-prestashop in https://github.com/PrestaShopCorp/ps_accounts/pull/286
**Full Changelog**: https://github.com/PrestaShopCorp/ps_accounts/compare/v6.0.2...v6.0.3
6.0.2

## What\\\'s Changed
* fix: clean shop credentials after three refresh token fails by @antoinemetifeu in https://github.com/PrestaShopCorp/ps_accounts/pull/265
**Full Changelog**: https://github.com/PrestaShopCorp/ps_accounts/compare/v6.0.1...v6.0.2
6.0.1

## What\\\'s Changed
* fix: compatibility chart by @hschoenenberger in https://github.com/PrestaShopCorp/ps_accounts/pull/277
* New Crowdin updates by @devops-prestashop in https://github.com/PrestaShopCorp/ps_accounts/pull/280
**Full Changelog**: https://github.com/PrestaShopCorp/ps_accounts/compare/v6.0.0...v6.0.1
6.0.0

## What\\\'s Changed
* [Account 1057] feat:compat-prestashop8 by @hschoenenberger in https://github.com/PrestaShopCorp/ps_accounts/pull/241
* [Refactor] - Clean /_dev, reduce bundle size, Vue 3 and dependencies update by @aAmorim27 in https://github.com/PrestaShopCorp/ps_accounts/pull/259
* [ACCOUNT-1281] feat:oauth2 login by @hschoenenberger in https://github.com/PrestaShopCorp/ps_accounts/pull/257
* fix(ci): remove working-dir for yarn cache in build job by @aAmorim27 in https://github.com/PrestaShopCorp/ps_accounts/pull/262
* fix(ci): pass npm RO token to install deps in build job by @aAmorim27 in https://github.com/PrestaShopCorp/ps_accounts/pull/263
* [ACCOUNT 1281] feat: activate ps_accounts login by @hschoenenberger in https://github.com/PrestaShopCorp/ps_accounts/pull/260
* [ACCOUNT-1467] refactor: enhance error handling with targeted exceptions by @hschoenenberger in https://github.com/PrestaShopCorp/ps_accounts/pull/264
* Update composer.json for distribution via packagist by @Quetzacoalt91 in https://github.com/PrestaShopCorp/ps_accounts/pull/255
* Remove unused release drafter by @aAmorim27 in https://github.com/PrestaShopCorp/ps_accounts/pull/267
* fix/packaging docker by @jokesterfr in https://github.com/PrestaShopCorp/ps_accounts/pull/258
* Account 1475/fix/get real backoffice url by @atourneriePresta in https://github.com/PrestaShopCorp/ps_accounts/pull/269
* [ACCOUNT-1483] Fix null response when shop is not associated by @antoinemetifeu in https://github.com/PrestaShopCorp/ps_accounts/pull/270
* feat: cleanup oauth client id and secret on unlink shop by @hschoenenberger in https://github.com/PrestaShopCorp/ps_accounts/pull/266
* fix: fix link null error by @hschoenenberger in https://github.com/PrestaShopCorp/ps_accounts/pull/271
* May fix ACCOUNT-1483 by @antoinemetifeu in https://github.com/PrestaShopCorp/ps_accounts/pull/272
* [ACCOUNT-1504] feat: new message for employee_not_found error by @hschoenenberger in https://github.com/PrestaShopCorp/ps_accounts/pull/274
## New Contributors
* @aAmorim27 made their first contribution in https://github.com/PrestaShopCorp/ps_accounts/pull/259
**Full Changelog**: https://github.com/PrestaShopCorp/ps_accounts/compare/v5.3.0...v6.0.0

**Comment by joecoolio66** [comment]
We assume 5.4.3 was the last version released since this confusing split for some modules to prestashopcorp... whatever that is

**Comment by emmanuelgautier** [comment]
Hello @joecoolio66,

We are sorry to hear that you are facing an issue with a module. Without more informations, it is hard to say what is the issue exactly. However, we are publishing right now a new version of the module fixing an issue that causes a timeout that can be the one you encounter.

Waiting for the publishing of the module on the Marketplace, here you can find the zip for the fixed versions:
- [v6.2.4-ps_accounts.zip](https://github.com/PrestaShop/PrestaShop/files/11680380/v6.2.4-ps_accounts.zip)
- [v5.4.5-ps_accounts.zip](https://github.com/PrestaShop/PrestaShop/files/11687147/v5.4.5-ps_accounts.zip)

Can you install the 6.2.4 version and check whether this new version is fixing your issue? If it is not, can you share more information about what you have in your PHP logs?

@florine2623 We currently maintain two major versions of the module depending on the Prestashop version compatibility. You can check out a compatibility matrix here for more informations: [https://docs.cloud.prestashop.com/0-introduction/#prerequisites](https://docs.cloud.prestashop.com/0-introduction/#prerequisites)

**Comment by joecoolio66** [comment]
I have installed the attached 6.2.4 successfully on my test and live site and see no issues.  It looks like this resolved the issue.. but man... that was a big issue to have in a release...

**Comment by emmanuelgautier** [comment]
Glad to hear the new version fixes your issue.

We are sorry for the convenience this version caused you. Be sure, we are making all our effort to keep the module the most reliable as possible. A review of what happened has already been done and we are identifying improvements in our quality process in order to avoid this situation happening again to keep the module stable as it is usually.

**Comment by sasp76** [comment]
Hi, 

Yesterday I encountered the same problem when upgrading the prestashop account module to v5.4.3. I was without access to the BO with message 504. In addition to absorbing high resources on cpu.

I can use this upgrade 5.4.5 to 1.7.6.3?
Thank you

**Comment by hschoenenberger** [comment]
Hello @sasp76,
ps_accounts v5.4.5 fix that problem.
Sorry for the inconvenience again.

**Comment by sasp76** [comment]
Hi ,
Thank you. Resolved

**Comment by dainora** [comment]
Hello, Indeed the issue is with ps_account module, I tried many different things until I found out this issue.
Update version you uploaded solved the problem, thanks.
Hopefully any future module won't have this issue.

**Comment by hibatallahAouadni** [comment]
Hello @joecoolio66 

Thanks for your issue :pray: Unfortunately, ps_account doesn't belong to PrestaShop Open Source anymore.
So you can create your issue here under PrestaShopCorp: https://github.com/PrestaShopCorp/ps_accounts/issues
Closing the issue.

Thanks for your understanding.

**Comment by dainora** [comment]
Can't access this Github, got 404
PrestaShopCorp: https://github.com/PrestaShopCorp/ps_accounts/issues
