### ISSUE TITLE
BO - Multistore - Store crashes when deleting main URL

### ISSUE THREAD

**Issue by aniszr** [PrestaShop/PrestaShop#32864]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In multistore mode, when you assign for the main shop two main URLs, you can see that after adding the second URL, the first one become not main anymore.

In fact you can observe that the first URL assigned to the shop have no delete option, only Edit button; in the other side the second URL even it became a main URL we have the option to delete it.

See attached screenshots :
![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/b6a37f8c-a00e-4ecb-af80-2579fa2c9b75)

If I delete the second URL which became the main URL all the store crashes and you can’t even go back to previous menu.

See attached screenrecord for store crash :

https://github.com/PrestaShop/PrestaShop/assets/92626242/0729cf3e-367d-4af4-990e-56347be74884

Related to #11477

### Expected behavior

I think that the system should prevent us from deleting a main URL if there is only one available, or if there is two URLs it should automatically switch to the second one so the store won’t crash .

### Steps to reproduce

1. BO > Configure > General > Enable Multistore > click on `Save` button
2. Advanced Parameters > Multistore > click on `Add a new shop` button> click on `Save` button
3. In Multistore tree select the first shop > click on the URL below
4. Click on `Add a new URL` button
5. In URL options section : In Shop field choose your first shop in the drop-down list and enable the button `Is it the main URL for this shop?`
6. IN Shop URL section > add Virtual URL name
7. Get back to  URL options and click on `Save `button
8. Go to Multistore tree section > click on `Default` to show stores URLs
9. Go to the second URL assigned for the store(URL that you've just created in step 4 & 5) > click on `Edit `button 
10. Go to Shop URL section > click on Save button
11. Go to Multistore tree section > click on `Default` to show stores URLs
12. Go to the second URL (URL that you've just created in step 4 & 5) > click on the arrow from `Edit` button > click on `Delete` and confirm
13. See error > See attached video record :

https://github.com/PrestaShop/PrestaShop/assets/92626242/da9c8927-47f3-44ba-a25c-f964f1f14159

### PrestaShop version(s) where the bug happened

1.7.8.9 & 8.0.4

### PHP version(s) where the bug happened

7.4

**Comment by djoelleuch** [comment]
Hello @aniszr , 
I reproduce the issue with PrestaShop version 1.7.8.9, 8.0.4, develop  , I'll add this to the backlog so it can be fixed .

[Untitled_ Jun 8, 2023 3_38 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/e718c3b7-9f09-4f04-bb3a-1c44ea21dfd3)

thank you

**Comment by kpodemski** [comment]
Critical? 🤯  Who does that? Who removes the default URL for the shop? :D

**Comment by Hlavtox** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/33255
