### ISSUE TITLE
BO - Error when accessing the Back Office after updating PS_Account module

### ISSUE THREAD

**Issue by ccorpRx45** [PrestaShop/PrestaShop#32865]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After updating the PS_Account module from version 5.4.2 to 5.4.3 I can't access the Back Office and I get the following error:

![error_1](https://github.com/PrestaShop/PrestaShop/assets/88554276/9bc0ab50-999d-4485-acdb-2619c4c4ddd7)

CRITICAL
php	Fatal Error: Maximum execution time of 30 seconds exceeded
CRITICAL
request	Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Maximum execution time of 30 seconds exceeded" at /bitnami/prestashop/src/PrestaShopBundle/Routing/Converter/AbstractLegacyRouteProvider.php line 67

### Expected behavior

Access to Back Office.

### Steps to reproduce

1. Go to BO login
2. Complete email and password
3. Log in

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4.28

### If your bug is related to a module, specify its name and its version

PS_Account v5.4.3

**Comment by hschoenenberger** [comment]
see #32857

The bug is fixed with 5.4.5 and 6.2.4

**Comment by ccorpRx45** [comment]
Hi, 
I have restored a backup and updated to version 5.4.5 and it works correctly.
Thank you.

**Comment by hibatallahAouadni** [comment]
Glad to hear :tada:
