### ISSUE TITLE
The hook "header" is deprecated

### ISSUE THREAD

**Issue by ginodev** [PrestaShop/PrestaShop#32871]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

PHP Deprecated:  The hook "header" is deprecated, please use "displayHeader" instead in module "ps_checkout". in /public_html/classes/Hook.php on line 865

### Expected behavior

In my log file

### Steps to reproduce

4

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

classes

### Your company or customer's name goes here (if applicable).

-

**Comment by tleon** [comment]
Hello, thank you for bringing this issue up to us. Could you enrich the description, the expected behaviour & the steps to reproduce on this issue ? It would help us reproduce and handle the issue. From what i can guess, you encounter this message in your log file and you want it gone ? Is that it ? 

Thank you in advance.

**Comment by Progi1984** [comment]
Please contact the PrestaShopCorp team. They have a repository : https://github.com/PrestaShopCorp/ps_checkout.

Thank you for your help.

**Comment by antonov95** [comment]
Hello,

i use creative elements, default theme, PS8.1  and when i have past my PS in debug profiling by “false” to true i have problem with server, after i change true by false, and now i have this line error :

Deprecated: The hook “header” is deprecated, please use “displayHeader” instead in module “ps_checkout”. in /var/www/vhosts/XXXXXXX.fr/preprod.XXXXXX.fr/classes/Hook.php on line 875

How i can resolved my problems please ?

Thank u very much

**Comment by antonov95** [comment]
i have found, 
thank's ...

**Comment by okechukwu0127** [comment]
> i have found, thank's ...

Hallo, how were you able to resolve the issue cos i am having same issue onmy end

`Got error 'PHP message: PHP Deprecated: The hook "header" is deprecated, please use "displayHeader" instead in module "customproductdesign"`


Kindly tell me how you were able to resolve yours

**Comment by Mohamedwasim45** [comment]
HI ,

I am also facing the issue from my end. Kindly could you please help me to resolve this. 

[07-Mar-2024 10:06:06 Asia/Kolkata] PHP Deprecated:  The hook "header" is deprecated, please use "displayHeader" instead in module "Fiserv". in /home2/pujassfq/public_html/upgrade/classes/Hook.php on line 921

**Comment by hotpro1** [comment]
can andy one provide an update or fix this issue we are getting the same error
