### ISSUE TITLE
API : External Auth Server : Returns (not) a header `WWW-Authenticate : Bearer` if the access token is invalid

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#32882]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When using an external Auth Server, the API doesn't return a header `WWW-Authenticate : Bearer` if the access token is invalid

### Expected behavior

When using an external Auth Server, the API returns a header `WWW-Authenticate : Bearer` if the access token is invalid

The CI must be green : `TEST_PATH="functional/API/01*/02*/02*" npm run test:specific`

### Steps to reproduce

1. Launch a keycloak : `docker run -p 8003:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:19.0.3 start-dev`
2. Install the module KeyCloak Connector Demo
3. Configure the realm endpoint : http://127.0.0.1:8003/realms/master
4. Request the endpoint `http://domain.tld/admin-dev/new-api/hook-status/1` with header `Authorization: 'Bearer INVALIDTOKEN'`
5. The HTTP Code received is a 401
6. The header  `WWW-Authenticate : Bearer` is not returned

#### Acceptance Test
Unskip the test : 
https://github.com/PrestaShop/PrestaShop/blob/d672ad4ccc467722d13746e25fffc95a86e5e3b3/tests/UI/campaigns/functional/API/01_clientCredentialGrantFlow/02_externalAuthServer/02_resourceEndpoint.ts#L136-L137

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

keycloak_connector_demo v1.0.2

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

**Comment by sallemiines** [comment]
Hello @Progi1984 
I didn't manage to reproduce the issue 

![image (1)](https://github.com/PrestaShop/PrestaShop/assets/31663369/2218d1d9-7d0a-4eea-b6bd-c58db311a9c8)

Could you please check  if there's  any config is missing and feddback  !

Thank you

**Comment by florine2623** [comment]
Seen with @Progi1984 ,

I reproduced the issue with PS 8.1.x.

https://github.com/PrestaShop/PrestaShop/assets/16019289/6697f0a4-eb47-4db8-9824-f4f97fd5a69b

The header `WWW-Authenticate : Bearer` is not returned:
<img width="1338" alt="Screenshot 2023-06-29 at 17 16 52" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/89be23da-b696-4e48-975a-55b8f4abbca1">
