### ISSUE TITLE
FO-Cart content still displayed even deleted until you refresh the page

### ISSUE THREAD

**Issue by aniszr** [PrestaShop/PrestaShop#32889]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments
Hello,

When you try to delete an item from your card, visually nothing happens,in fact the item still displayed until you click refresh button it disappears. 
This issue happens only when you choose second language for your shop (Not the default language).

See attached screen record:(Tested with French as a second language)

https://github.com/PrestaShop/PrestaShop/assets/92626242/4eea73b9-2075-4169-bf01-ca093852dd26

Thanks!
### Expected behavior

When we click on delete button, the items list on the card should be updated right on click and the item selected should be removed no matter what the language selected.

### Steps to reproduce

1. Go to FO
2. Choose an article > click on ADD TO CART button
3. Click on PROCEED TO CHECKOUT 
4. In the displayed SHOPPING CART click on delete button for any item
5. See the bug : Nothing happens : The item still there

### PrestaShop version(s) where the bug happened

8.0.x & develop

### PHP version(s) where the bug happened

7.4 & 8.1

**Comment by djoelleuch** [comment]
Hello @aniszr  , 
I reproduce the issue on PS 8.1.x , 8.0.x , DEVELOP and not on PS 1.7.8.9 /PS 8.0.4  : 

[Untitled_ Jun 13, 2023 5_34 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/05d98cf8-5f33-4617-baf7-a9330122a982)

[Untitled_ Jun 13 2023 5_54 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/90ad6f35-a7f5-4e65-b62f-ed6a775f4414)

Nice catch , it's a REGRESSION on 8.0.x :rocket: 
Thank you !

**Comment by M0rgan01** [comment]
After several tests on 8.0.x, 8.1.x and develop, I reproduce the error only on develop, and the result is the same as the ticket #32630  , The problem only occurs when dev mode is enabled.

**Comment by Hlavtox** [comment]
@MatShir Changing severity, broken cart functionality is not a minor bug.

**Comment by MatShir** [comment]
It was minor because it is only on debug mode, so the issue doesn't occur on prod.

**Comment by M0rgan01** [comment]
PR: https://github.com/PrestaShop/PrestaShop/pull/33113
