### ISSUE TITLE
Deleting product image doesn't work via API/webservice

### ISSUE THREAD

**Issue by averatec1337** [PrestaShop/PrestaShop#32897]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

As title says, image isn't deleted.
Error says
```
Fatal error: Uncaught Error: Call to a member function get() on null in /var/www/html/classes/Image.php:640
Stack trace:
#0 /var/www/html/classes/Image.php(210): ImageCore->deleteImage()
#1 /var/www/html/classes/webservice/WebserviceSpecificManagementImages.php(822): ImageCore->delete()
#2 /var/www/html/classes/webservice/WebserviceSpecificManagementImages.php(625): WebserviceSpecificManagementImagesCore->manageDeclinatedImagesCRUD(true, '/var/www/html/i...', Array, '/var/www/html/i...')
#3 /var/www/html/classes/webservice/WebserviceSpecificManagementImages.php(650): WebserviceSpecificManagementImagesCore->manageEntityDeclinatedImages('/var/www/html/i...', Array)
#4 /var/www/html/classes/webservice/WebserviceSpecificManagementImages.php(656): WebserviceSpecificManagementImagesCore->manageDeclinatedImages('/var/www/html/i...')
#5 /var/www/html/classes/webservice/WebserviceSpecificManagementImages.php(315): WebserviceSpecificManagementImagesCore->manageProductImages()
#6 /var/www/html/classes/webservice/WebserviceSpecificManagementImages.php(184): WebserviceSpecificManagementImagesCore->manageImages()
#7 /var/www/html/classes/webservice/WebserviceRequest.php(619): WebserviceSpecificManagementImagesCore->manage()
#8 /var/www/html/webservice/dispatcher.php(94): WebserviceRequestCore->fetch('8A7LBRETHEZ9PUS...', 'DELETE', 'images/products...', Array, false, NULL)
#9 {main}
  thrown in /var/www/html/classes/Image.php on line 640
```

https://github.com/PrestaShop/PrestaShop/assets/23308427/8dacd8c2-d869-4f7f-aabc-dcdf3c10916a

### Expected behavior

Image is deleted.

### Steps to reproduce

1. Generate API key
2. Obtain product image ID 
3. Call /api/images/products/PRODUCT_ID/IMAGE_ID with DELETE method.

### PrestaShop version(s) where the bug happened

dev/master

### PHP version(s) where the bug happened

8.1

**Comment by averatec1337** [comment]
8.0.4 is not affected by this issue.

**Comment by sallemiines** [comment]
Hello @kamil-karkus 

Ididn't manage to reproduce your issue,  you can see the attached screen recorder 

[Capture vidéo du 14-06-2023 15_16_31 (1).webm](https://github.com/PrestaShop/PrestaShop/assets/31663369/181200ee-d2f7-44d2-aa02-516bd5b88734)

Thank you !

**Comment by alexll** [comment]
We are having similar error when deleting an image using the web service.

We are using Prestashop 8.1.0 and PHP 8.1.21 

The error also raises when deleting product with images using the webservice.

SymfonyContainer in function deleteImage in ImageCore class is null.

'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /var/www/classes/Image.php:642
Stack trace:\n#0 /var/www/classes/Image.php(210): ImageCore->deleteImage()
1 /var/www/classes/Product.php(1600): ImageCore->delete()
2 /var/www/classes/Product.php(1336): ProductCore->deleteImages()
3 /var/www/classes/webservice/WebserviceRequest.php(1511): ProductCore->delete()
4 /var/www/classes/webservice/WebserviceRequest.php(597): WebserviceRequestCore->executeEntityDelete()
5 /var/www/webservice/dispatcher.php(94): WebserviceRequestCore->fetch()
6 {main}\n  thrown in /var/www/classes/Image.php on line 642'

**Comment by boherm** [comment]
Hi @alexll! This issue is closed, can you create another issue and mention your new issue in your PR please? :)

**Comment by kpodemski** [comment]
I'm reopening the issue it seems like a valid bug report.

**Comment by hibatallahAouadni** [comment]
@kpodemski & @Hlavtox can someone please try to reproduce the issue :pray:

**Comment by hibatallahAouadni** [comment]
Hello @kamil-karkus 

I reproduce the issue with 8.1.x, see the attached screen record below:


https://github.com/PrestaShop/PrestaShop/assets/23308427/8dacd8c2-d869-4f7f-aabc-dcdf3c10916a

Thanks @Hlavtox for your PR :rocket: 

Thanks!

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/33407
