### ISSUE TITLE
Dash modules

### ISSUE THREAD

**Issue by Kurnik1337** [PrestaShop/PrestaShop#32899]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I installed Prestashop 8.0.4 dash module stoped working. Store visits are not displayed now.  Everything worked fine on previous versions. 

### Expected behavior

I expected it to work the same as previous versions

### Steps to reproduce

1)Go to desktop 2)Check store visits 3)No visits, only zeros

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_dashactivity ps_dashgoals ps_dashproducts ps_dashtrends

### Your company or customer's name goes here (if applicable).

Lingerie Collection

**Comment by sallemiines** [comment]
Hello @Kurnik1337 

I didn't manage to reprouce your issue with PS 804 

![Dashboard-•-804 (1)](https://github.com/PrestaShop/PrestaShop/assets/31663369/5a38f74d-e5fc-4ddf-926d-6342d6061785)

Thanks to reset your module dashactivity !

Thank you

**Comment by Kurnik1337** [comment]
I've reset the module a thousand times and it still doesn't work.  Only
reverting to the old version helps.

śr., 14 cze 2023, 11:54 użytkownik ines sallemi ***@***.***>
napisał:
