### ISSUE TITLE
Multishop, multicurrency, BO, order shipping change, bad currency coversation

### ISSUE THREAD

**Issue by SNor42** [PrestaShop/PrestaShop#32907]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you change the shipping method under all shop, then it the shipping price will be converted to main currency.
Here:
![kép](https://github.com/PrestaShop/PrestaShop/assets/1334351/1dc803ff-bbf0-4e1a-8856-7d0e992a2e4e)

### Expected behavior

Not to convert the price (it works when you are on the right shop context.)

### Steps to reproduce

1. Multishop, with two shop
2. Import two different country with different currency (France, UK)
3. Shop A = UK, shop B =France
4. Base currency GBP
5. two shipping method, 10eur, or 10gbp
6. Create an order on shop B) with EUR
7. Under -- All shop -- context in BO change the shipping method. It will convert the 10EUR to GBP, but still showing EUR. Something 8.5eur and not 10 eur.

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment]
Hello @SNor42 ,

Can you show me how you configure both your carriers ?

The carriers can be created only with the Default currency. You're not supposed to have different currencies for each carrier.

**Comment by SNor42** [comment]
Hello @florine2623 ,
I'm bit confused, because can't reproduce on a test environment. So maybe it's a module problem. ?!

**Comment by florine2623** [comment]
It might be a module problem yes. I don't know what kind of shipping module you're using, you might have more information if you contact directly the developer of the module ^^

**Comment by florine2623** [comment]
Hello @SNor42 ,

I'm closing this issue. Feel free to consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
