### ISSUE TITLE
Regression: input groups in BO are not aligned properly

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/PrestaShop#32904]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

#29589 made inputs 100% wide and forced addons to brake from the inputs

![obraz](https://github.com/PrestaShop/PrestaShop/assets/5007456/30fcba59-d766-4ac7-a327-2796433a7d35)

### Expected behavior

It should look like this:
![obraz](https://github.com/PrestaShop/PrestaShop/assets/5007456/0856de2e-0880-4ad0-9388-a065f5509f39)

### Steps to reproduce

1. Go to Prestashop's BO.
2. Edit any product
3. Check the Shipping tab and package properties

### PrestaShop version(s) where the bug happened

8.0.x, 8.1.x

**Comment by SharakPL** [comment]
Looks like PPV2 isn't affected, even when activated on PS.8.0.x

**Comment by sallemiines** [comment]
Hello @SharakPL 

Issue tested with 

- PS 1787 OK 
- PS 1789 Ok 

![Product-•-1787](https://github.com/PrestaShop/PrestaShop/assets/31663369/d9db9e8c-b9b2-4f23-a1b9-b8e25cb2ff30)

-  PS 80x, 81x , 804 

If the PPV2 is activated the issue is not exist , and if the PPV1 is enabled the issue displayed 

https://github.com/PrestaShop/PrestaShop/assets/31663369/c7528e90-ebb2-4ced-90d2-5ce8b4db57b5

 Thank you

**Comment by sallemiines** [comment]
@PrestaShop/product-team this issue is happen only on PPV1 and it's fixed on PPV2 ! 
do I close this issue ? 
WDT ? 

Thank you !

**Comment by SharakPL** [comment]
The code of input group in the changed file is still broken. I'm not sure it is used anywhere else than the BO's old product page. So it either should be fixed or removed.

**Comment by MatShir** [comment]
I'm not sure to understand your sugestion. 
In anycase, the Open Source team from PrestaShop for now will only contribute to the new page unless major regressions on the old one. Do you feel like fixing it ?

**Comment by SharakPL** [comment]
https://github.com/PrestaShop/PrestaShop/blob/83d0dd94b5e78956dcda25f9abb7c34d49b11cfb/src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/bootstrap_4_horizontal_layout.html.twig#L144-L152

Is this `number_widget` block used anywhere else than old product page? It's still broken whenever `form_unit` or `form_unit_prepend` is also used. Although I checked few other places with components like that (number with unit addon) and they seem to be using different template. TBH I'm not even sure how it got to be used in a product shipping tab. I got stuck on
https://github.com/PrestaShop/PrestaShop/blob/83d0dd94b5e78956dcda25f9abb7c34d49b11cfb/src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_shipping.html.twig#L34-L37

Anyway if this part of the template is still used then it should be fixed. Otherwise it's obsolete. Right?

**Comment by MatShir** [comment]
It seems the only place used AFAIK

**Comment by kpodemski** [comment]
It seems that this issue can be closed @MatShir

**Comment by florine2623** [comment]
I'm closing this issue as it is only affecting PPV1.
