### ISSUE TITLE
Symfony Exception when access to orders backoffice. method_exists(): Argument #1 ($object_or_class) 

### ISSUE THREAD

**Issue by voltiosin** [PrestaShop/PrestaShop#32909]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After update fro, 1.7.9 to 8.0.4 I can't access to old orders, I get Symfony Exception when debug is On.

<img width="1080" alt="Captura de pantalla 2023-06-14 a las 19 50 00" src="https://github.com/PrestaShop/PrestaShop/assets/136633450/080888e0-43fc-43db-865a-3a484c9f6dca">

**Temporal fix:** After checking Symphony bug reports from other platforms I have fixed it adding: is_object($value) && at rc/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php line 535 should be:

       **if (is_object($module) && method_exists($module, 'displayInfoByCart')) {**

Now works, but I am not sure if its a great fix or if I should add the same fix to others files.

### Expected behavior

Access to the back office order data

### Steps to reproduce

Go to orders at back office
Click and old order

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.0

**Comment by paulnoelcholot** [comment]
Hello @voltiosin,

I tried to reproduce this issue but as you can see, I can't : https://watch.screencastify.com/v/KSP5l9bP1sxjaBvdfVyC

Did I miss something?

Thanks for your feedback

**Comment by florine2623** [comment]
Hello @voltiosin ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
