### ISSUE TITLE
I always be redirect to mi local ip 

### ISSUE THREAD

**Issue by hiddenotebook** [PrestaShop/PrestaShop#32908]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I nice to see you all.

I got a domain www.alcalacompra.com point to mi public IP by redirecting DNS tipe A. but wen I try to go the store always redirect me to mi local IP.

![imagen](https://github.com/PrestaShop/PrestaShop/assets/11570499/69ce1aee-8bc6-4e26-a42a-8d1ed47563ea)

But I got another webpage with the same configuration and everything goes well.

![imagen](https://github.com/PrestaShop/PrestaShop/assets/11570499/b27cfbb6-6559-415c-ae55-fa80709579c8)

All the web pages are in my private server.  what you need to know for this Issue? to help me with this mess.

Thanks in advance!

### Expected behavior

I expect to go to the domain not to mi IP local.

### Steps to reproduce

I isntall the web by the ZIP installer.

### PrestaShop version(s) where the bug happened

prestashop 8.1

### PHP version(s) where the bug happened

php7.4

**Comment by antso24** [comment]
I think you still have your local adress somewhere in table ps_configuration. look at PS_SHOP_DOMAIN and PS_SHOP_DOMAIN_SSL

**Comment by paulnoelcholot** [comment]
Hello @hiddenotebook,

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Thank you
