### ISSUE TITLE
Customer can order disabled product from front office

### ISSUE THREAD

**Issue by Arshlanwebkul** [PrestaShop/PrestaShop#32900]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When customer added product in the cart and at the same time admin disabled the product.
Not customer does not refresh page and click on "Proceed to checkout" button then customer can complete the checkout process and order will be created successfully.

**Note**: if customer reload the page "Proceed to checkout" button is disable, so everything is fine in this case.

Please check below video:

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023.06.14-09_52_07.webm](https://github.com/PrestaShop/PrestaShop/assets/136475297/7c0c8ae3-40e0-495a-8163-cd30eb2837c2)

### Expected behavior

While clicking on "Proceed to checkout" button on the next page or on the same page it should display error that "Product is not available"

### Steps to reproduce

1. Go to FO and add a product in cart
2. Now come to backoffice and disable the same product
3. Now go to front office and without reloading just press on "Proceed to checkout"
4. You can see, you can order the product successfully, which must not be.

### PrestaShop version(s) where the bug happened

8.0.4 , 8.1.0 beta

### PHP version(s) where the bug happened

7.4 and 8.0

### Your company or customer's name goes here (if applicable).

Webkul

**Comment by sallemiines** [comment]
Hello @Arshlanwebkul 

Thanx for this issue , I didn't manage to reproduce your issue with **PS 1789,804,810Beta** 


https://github.com/PrestaShop/PrestaShop/assets/31663369/4ca61ab4-0b11-4f0e-9f01-8eaa7f1a7e1e



https://github.com/PrestaShop/PrestaShop/assets/31663369/c440dbb6-d173-4721-a0be-d50556eba169

Please check your cache ! 
Thank you

**Comment by Arshlanwebkul** [comment]
Hello @sallemiines 

I am not talking about pop-up "Proceed to checkout" button, I am talking about cart page "Proceed to checkout".

Please follow exactly as my video.

On pop-up click on 'Proceed to checkout' do not cut popup, and go to cart page, then on cart page hold and disable product. and after disable Do not refresh cart page and click on "Proceed to checkout".

Thanks,

**Comment by Arshlanwebkul** [comment]
@sallemiines

Please test only on PS 8.x.x. As I have tested issue exist on PS v8.0.4.

And its working fine on PS v1.7.x.x.


Thanks,
