### ISSUE TITLE
The CI for 1.7.8.x is locked

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#32915]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

All Github Actions are not started

### Expected behavior

Some Github Actions are executed and :green_circle: 

### Steps to reproduce

Create a PR on 1.7.8.x

### PrestaShop version(s) where the bug happened

1.7.8.x

### PHP version(s) where the bug happened

N/A

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

**Comment by AureRita** [comment]
Hi @Progi1984 

Thank for your report,
This issue is too technical for me, ping @PrestaShop/prestashop-core-developers, can someone please reproduce this issue ? 

Thanks
