### ISSUE TITLE
After disabling/enabling a tax, the linked tax rule is not present for the Ecotax

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#32914]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After disabling/enabling a tax, the linked tax rule is not present for the Ecotax

### Expected behavior

After disabling/enabling a tax, the linked tax rule is present for the Ecotax

### Steps to reproduce

1. Install PrestaShop (Language : English / Country : France)
2. Go to BackOffice
3. Go to Internation > Taxes
4. Enable "Use Ecotax" and Save
5. :green_circle: In the select "FR Taux Standard (20%)" is present 
6. In the tab "Taxes", disable and enable "TVA FR 20%"
5. :red_circle: In the select "FR Taux Standard (20%)" is not present 

### PrestaShop version(s) where the bug happened

1.7.8.x

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

N/A

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

**Comment by AureRita** [comment]
Hi @Progi1984 ,

Thank you for your report,I reproduce your issue with PrestaShop version 1.7.8.9,as you can see : 

[Untitled_ Jun 16, 2023 5_25 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/0b6a5d1e-dee5-4cea-b80c-e0af396ddea2)

 I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved.

Thanks

**Comment by MatShir** [comment]
And also 8.1 :/

**Comment by mflasquin** [comment]
Same as : https://github.com/PrestaShop/PrestaShop/issues/19715

**Comment by Progi1984** [comment]
> And also 8.1 :/

@MatShir The bug is in 8.0.x and develop, too. It's normal because it's :red_circle: on 1.7.8.x.

**Comment by MatShir** [comment]
The bug is from the 1.7.6 check the issue https://github.com/PrestaShop/PrestaShop/issues/19715. So the issue is from the order of execution UI test performed. I thought you had a chat with @mflasquin.

**Comment by Progi1984** [comment]
Fixed in #33124 by @mflasquin (Version 8.0.5)
