### ISSUE TITLE
New Translations Do Not Appear

### ISSUE THREAD

**Issue by LuigiMdg** [PrestaShop/PrestaShop#32921]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Greetings,
I don't know if the problem has already been reported, however I made a copy of my ecommerce and made an attempt to update to 8.0.3, so far so good, except for the fact that PrestaShop no longer creates translations automatically. .!

With up to the 'old' 1.7.8.7 it was enough for me to insert a simple {l s='%s Stickers' d='Shop.Theme.Catalog'} to find it among the translations, while now it doesn't appear even after having emptied the cache.. I checked the ps_translations table and the .xlf files but there is no trace of the new words.

I await your suggestions.

PS: As suggested in the previously created topic (#32605), I uploaded the copy of the topic you attached.  Not only did this not solve the problem, but it also reinstalled modules that I had carefully uninstalled and rearranged the positions of the modules template.. In short, I hope the next tip will be more useful..!

### Steps to reproduce

1. Open any .tpl file
2. Add the code {l s='%s Stickers' d='Shop.Theme.Catalog'}

### PrestaShop version(s) where the bug happened

8.0.3

### PHP version(s) where the bug happened

7.4

**Comment by AureRita** [comment]
Hi @LuigiMdg 

I tried to reproduce your issue as you can see : 

[Untitled_ Jun 16, 2023 3_09 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/fa388ee7-01be-4dc9-9320-5ac25d39ec74)

because you didn't give us the expected behavior, I don't know which behavior I expected 
Moreover, this issue is maybe too technical for me, ping @PrestaShop/prestashop-core-developers, can someone please reproduce this issue ? 

Thanks

**Comment by dnkhack** [comment]
@AureRita Hello. Yes, translation does not work, actually does not appear in the translation back office tool. 
Classic theme, PS 8.0.4
![image](https://github.com/PrestaShop/PrestaShop/assets/35419462/2678c634-ad1e-4029-aaad-4a6a13a322f8)
![image](https://github.com/PrestaShop/PrestaShop/assets/35419462/b01fcd66-115d-4b0e-95e0-5766dbca94a2)
![image](https://github.com/PrestaShop/PrestaShop/assets/35419462/f7a7723c-0c02-4357-909e-c2e590a03c4f)

**Comment by LuigiMdg** [comment]
> @AureRita Hello. Yes, translation does not work, actually does not appear in the translation back office tool. Classic theme, PS 8.0.4 !

Exactly, thanks for trying and being able to reproduce the issue!

**Comment by aniszr** [comment]
Hello,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by LuigiMdg** [comment]
Imagine, we hope to receive feedback however, it is a problem that has continued since the last version and the problem has also been reproduced by others in this topic, but if no one replies, it will be closed in 20 days and the problem will remain..

**Comment by LuigiMdg** [comment]
So..?
Do we ignore the bug? It doesn't seem like a trivial thing to me.. I don't think users will be satisfied with having a site half in one language and half in another....

**Comment by dnkhack** [comment]
@LuigiMdg Hello, how are you, bro? Did you test it on 8.1?

**Comment by LuigiMdg** [comment]
Updated now.. Not work..!

**Comment by kpodemski** [comment]
Hello

Use `classic-child`, or copy of Classic. That should do it. It is not recommended to edit the default theme for many reasons, this is another one.

**Comment by dnkhack** [comment]
@kpodemski Thank you again!

**Comment by kpodemski** [comment]
No worries 👍🏻 I'll close this issue.

**Comment by LuigiMdg** [comment]
Now that I think about it, I had already solved this way, years ago, in 1.7..
I confirm that I tried and solved, thanks
