### ISSUE TITLE
[FO] - Discount wrong value display

### ISSUE THREAD

**Issue by RosaBenouamer** [PrestaShop/PrestaShop#32924]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have a product : 
- Mug The best is yet to come
Cost taxes included : 14.28
Cost taxes excluded : 11.90

- Specific price : Apply a discount of 10 euros taxes included

- I have a group (Shop parameters>customer settings>Groups) with Discount:
Discount: 50.00%
Price display method:
Tax included

When I connect on the front office an research the product  Mug The best is yet to come.
The discount displayed is not good
![image](https://github.com/PrestaShop/PrestaShop/assets/124665010/58fc6651-1d25-4e91-aaf8-b4e39ffc186d)

### Expected behavior

![image](https://github.com/PrestaShop/PrestaShop/assets/124665010/02bd1d9e-1372-4c19-87b2-47195ccf287e)

Because initial price is 14.28
14.28 - 10 (specific price) = 4.28
4.28/2 (50% du groupe) = 2.14
So the discount is 14.28-2.14 = 12.14

### Steps to reproduce

Create a product : 
- Mug The best is yet to come
Cost taxes included : 14.28
Cost taxes excluded : 11.90

Add a Specific price : Apply a discount of 10 euros taxes included

Add a group (Shop parameters>customer settings>Groups) with Discount:
Discount: 50.00%
Price display method:
Tax included

Gonnect to the FO with a customer of the added group who has the discount .
When I connect on the front office an research the product  Mug The best is yet to come.
The discount displayed is not good
![image](https://github.com/PrestaShop/PrestaShop/assets/124665010/58fc6651-1d25-4e91-aaf8-b4e39ffc186d)

### PrestaShop version(s) where the bug happened

8.0.4/8.1

### PHP version(s) where the bug happened

8.1.9/8.1.19

**Comment by AureRita** [comment]
Hi @RosaBenouamer ,

I reproduce the issue with PrestaShop version 1.7.8.9,as you can see : 

[Untitled_ Jun 16, 2023 2_40 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/6984c882-86c8-407c-8e91-429d6cf8039f)

 I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks
