### ISSUE TITLE
`ps_image_shop` and `ps_product_shop` getting filled while multistore feature is disabled

### ISSUE THREAD

**Issue by alisamie97** [PrestaShop/PrestaShop#32929]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi everyone, we have a problem which is strange for us.

We have our shop with multistore feature disabled, however when we check the database for `ps_image_shop` and `ps_product_shop` we have nearly the same number of rows for each product and image. For sure this is a waste of resources.

Is there any way to fix it easily?

here are some screen shots
![image](https://github.com/PrestaShop/PrestaShop/assets/23106000/912b5984-270f-4f85-baea-b519baf8b79d)
![image](https://github.com/PrestaShop/PrestaShop/assets/23106000/d9f09ed5-6f81-4a56-b451-131774fba14c)

### Expected behavior

I expect these table stay empty while the multi store feature is disabled

### Steps to reproduce

1. create product
2. add image
3. check ps_product_shop and ps_image_shop

### PrestaShop version(s) where the bug happened

1.7.8.8

**Comment by Hlavtox** [comment]
Hi @stifler97, that's normal, there will always be a default "shop" with a ID 1.

**Comment by alisamie97** [comment]
> Hi @stifler97, that's normal, there will always be a default "shop" with a ID 1.

Do you think if we empty the `_shop` tables it would affect the performance? Imagine there is a way to avoid filling these tables while the multistore feature is disabled.
