### ISSUE TITLE
/?schema=synopsis in Webservices throws error

### ISSUE THREAD

**Issue by mamodesign** [PrestaShop/PrestaShop#32925]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Invalid XML when call 
https://DOMAIN/api/customers/?schema=synopsis

```
<associations>
<groups nodeType="group" api="groups">
	<group>
	<0><![CDATA[]]></0>
	</group>
</groups>
</associations>

```
### Expected behavior

Valid XML

```
<associations>
<groups nodeType="group" api="groups">
<group>
<id></id>
</group>
</groups>
</associations>
```

### Steps to reproduce

Call https://DOMAIN/api/customers/?schema=synopsis

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

7.3, 7.4, 8

**Comment by mamodesign** [comment]
To solve I changed classes/webservice/WebserviceOutputBuilder.php line 714
from 

`if (isset($field['id']) && !isset($field['sqlId'])) {`

to

`if (array_key_exists('id',$field) && !isset($field['sqlId'])) {`

**Comment by AureRita** [comment]
Hi @mamodesign 

Thank you for your report, I tried to reproduce your issue and I get this  :
![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/9e77e7a2-3252-47c0-ab0d-7e6b6f8dbb3e)

Is it you issue or you have anything else ? 

Waiting for your feedback

**Comment by mamodesign** [comment]
Yes, same issue. Thank you

**Comment by ThomasGhignon** [comment]
Hi there,

I got the same problem today, I guess the bug come from this recent issue #30993

To solve it, I changed this :
`$fields_assoc = [['id' => ($value['id'] ?? null)]];`

<img width="180" alt="Capture d’écran 2023-06-20 à 15 54 14" src="https://github.com/PrestaShop/PrestaShop/assets/55481382/7265b4f1-e53d-42ee-b608-182e9107ad5c">

To this :
`$fields_assoc = [['id' => ($value['id'] ?? "")]];`

<img width="173" alt="Capture d’écran 2023-06-20 à 15 55 05" src="https://github.com/PrestaShop/PrestaShop/assets/55481382/e92ba7d2-ee61-4e58-9cfa-daddf2877726">

I don't know if it's the best way but I hope it can help.

**Comment by florine2623** [comment]
Hello @mamodesign ,

I have reproduced your issue.

I have the issue on branches `8.0.x` and `8.1.x`. Not on `1.7.8.x` and `develop`. It is a regression.

<img width="1434" alt="Screenshot 2023-06-20 at 16 30 21" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/d66bb652-2e25-4928-9f6e-3e43a5a1d170">

```
This page contains the following errors:
error on line 39 at column 3: StartTag: invalid element name
Below is a rendering of the page up to the first error.
```

 I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by mamodesign** [comment]
> Hello @mamodesign ,
> 
> 
> 
> I have reproduced your issue.
> 
> 
> 
> I have the issue on branches `8.0.x` and `8.1.x`. Not on `1.7.8.x` and `develop`. It is a regression.
> 
> 
> 
> <img width="1434" alt="Screenshot 2023-06-20 at 16 30 21" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/d66bb652-2e25-4928-9f6e-3e43a5a1d170">
> 
> 
> 
> ```
> 
> This page contains the following errors:
> 
> error on line 39 at column 3: StartTag: invalid element name
> 
> Below is a rendering of the page up to the first error.
> 
> ```
> 
> 
> 
>  I'll add this to the backlog so it can be fixed.
> 
> 
> 
> Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 
> 
> 
> 
> If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.
> 
> 
> 
> Thank you

Hello,
after an analysis I proposed a solution in above answer.

**Comment by florine2623** [comment]
@mamodesign thanks ^^

Do you think you could create a PR ?

**Comment by MatShir** [comment]
@mamodesign or @ThomasGhignon Not motivated, it would be cool to have your fix part of the next patch release of PS. Wdyt ?

**Comment by matks** [comment]
Hello everyone if this issue is similar to https://github.com/PrestaShop/PrestaShop/issues/32476 then it has been fixed on branch `develop` by PR https://github.com/PrestaShop/PrestaShop/pull/32884

**Comment by florine2623** [comment]
Hello all,

After testing on `develop` branch, I couldn't reproduce it.


No more tag <0><![CDATA[]]></0> is displayed :
<img width="337" alt="Screenshot 2023-10-03 at 17 45 01" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/1dc5a2aa-13c7-4ee8-8863-d6530d84a348">

So as @matks said, it has been fixed ^^

**Comment by florine2623** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/32884
