### ISSUE TITLE
Russian localization state error

### ISSUE THREAD

**Issue by hentaro** [PrestaShop/PrestaShop#32947]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After a clean install of Prestashop 1.7.8.9 with Russian language, I have two identical order statuses in the status list.
"Платеж принят" / "Payment accepted" (2) PS_OS_PAYMENT
"Платеж принят" / "Payment accepted" (11) PS_OS_WS_PAYMENT
Statuses are different, but they have the same names.

![2023-06-19_17-17](https://github.com/PrestaShop/PrestaShop/assets/4835225/f7f02dc1-979c-442c-9506-f75b89a85b80)

After downloading the "US" language, statuses have the same names again "Payment accepted".

![2023-06-08_14-07](https://github.com/PrestaShop/PrestaShop/assets/4835225/cb28feea-f49e-4e8a-9daa-074a170cc80a)

And when I open the orders list page, I only have one status "Payment accepted" (11) PS_OS_WS_PAYMENT without (2) PS_OS_PAYMENT.

![2023-06-19_16-26](https://github.com/PrestaShop/PrestaShop/assets/4835225/a0fe6153-2342-4610-95ca-39874ac86612)

Orders with status PS_OS_PAYMENT just have an empty status name.

![2023-06-19_15-29](https://github.com/PrestaShop/PrestaShop/assets/4835225/205d93e3-53ee-47fe-98d7-c0ee583bd27d)

I don't know, but maybe this issue can be repeated with other languages

### Expected behavior

There must be a unique name for each order state and each language

### Steps to reproduce

1. Install Prestashop 1.7.8.9 with any other language (not US) by default.
2. Check order states translation

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @hentaro ,

I have reproduced the same issue with Russian language, but not French.
**RUSSIAN**
<img width="1206" alt="Screenshot 2023-06-20 at 09 39 45" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/0d747caa-fa6d-459f-8790-dcecc279d311">

**FRENCH**
<img width="1220" alt="Screenshot 2023-06-20 at 09 39 17" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/b4b71e87-64cd-407a-9fcf-61333a8fb482">


This is a translation issue not a core issue ^^

**Comment by florine2623** [comment]
Hello @l-delin ,

Could you confirm that this is a translation issue ? 🤗 

Thanks!

**Comment by l-delin** [comment]
Hello! 
I can confirm that the two strings `Payment accepted` and `Remote payment accepted` are translated the same in Russian (Платеж принят), this is a translation issue!

<img width="567" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/113511191/29cb6172-1aee-4ce5-a315-00152e7ad3db">
<img width="567" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/113511191/27d69790-8391-48db-9e4e-fdb462301655">

I removed the translation, so if you have a suggestion on how to translate `Remote payment accepted`, I could replace the faulty translation string 🙂
The English strings are fine, though.

**Comment by hentaro** [comment]
Hello @l-delin !
I'm not a language expert, but I think the correct translation of `Remote payment accepted` is `Удаленный платеж принят`.

**Comment by l-delin** [comment]
Hello @hentaro 🙂 

Thank you for your help! I've corrected the translation, it should be effective by tomorrow.

**Comment by l-delin** [comment]
Hello @hentaro, the translation issue seems fixed now :) 
![image](https://github.com/PrestaShop/PrestaShop/assets/113511191/12cb8679-20e1-4506-a236-9e5f257b74ca)

Could you please **update your translations** and let me know if your issue is fixed? (Go to Локализация > Переводы > Добавить / Обновить перевод > русский (Russian) > **Добавить или обновить язык**) 

Thank you!

**Comment by hibatallahAouadni** [comment]
Hello @hentaro 

It seems your issue is fixed, so closing the issue :tada: 

Thanks!
