### ISSUE TITLE
[BO] Unknown error displayed in customer messages

### ISSUE THREAD

**Issue by MhiriFaten** [PrestaShop/PrestaShop#32953]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After sending a contact us message in the FO, an error appeared in the customer messages thread in the BO

PS_8.0.4 :x: 

[Capture vidéo du 20-06-2023 11:08:55.webm](https://github.com/PrestaShop/PrestaShop/assets/111756615/914bc9de-7890-4382-ab46-bc25db6efed2)

PS_8.0.3 :heavy_check_mark: 

[Capture vidéo du 20-06-2023 11:12:58.webm](https://github.com/PrestaShop/PrestaShop/assets/111756615/f7b311aa-2e33-4992-97b0-f8e3be199cc5)

PS_1.7.8.9 :heavy_check_mark: 

[Capture vidéo du 20-06-2023 11:15:26.webm](https://github.com/PrestaShop/PrestaShop/assets/111756615/e42175d3-4d5c-424e-9a87-41f95280cf41)

### Steps to reproduce

1. Go to FO> Contact us
2. Send a message to the customer connected
3. Go to BO> messages
4. See error :warning: an unknown message is displayed

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello @MhiriFaten ,

I reproduce the issue with PrestaShop version `8.0.4`, `8.0.x` and `develop`, I'll add this to the backlog so it can be fixed.

```
Unknown error on line 114 in file /Users/fHea/Desktop/develop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_modifier.php
[16384] Using php-function "substr" as a modifier is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier.

Unknown error on line 114 in file /Users/fHea/Desktop/develop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_modifier.php
[16384] Using php-function "substr" as a modifier is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier.
```

It is a regression, as it cannot be reproduced on 1.7.8.9.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by florine2623** [comment]
This is fixed. So I'm closing the issue.

https://github.com/PrestaShop/PrestaShop/assets/16019289/17320800-dacd-4d1e-9380-90885e19f1a3
