### ISSUE TITLE
Add image to product: "Error while creating additional image"

### ISSUE THREAD

**Issue by yannicka** [PrestaShop/PrestaShop#32958]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Sometimes, when I add images to a product, some of them don't import.

Upload image:
![image](https://github.com/PrestaShop/PrestaShop/assets/22885898/3675edcb-a2a3-4c6c-8316-1ffe26eba3f8)

HTTP request executed:
![image](https://github.com/PrestaShop/PrestaShop/assets/22885898/4effe5bb-d7a0-4817-8e19-0c63edb8df11)

When it works:
![image](https://github.com/PrestaShop/PrestaShop/assets/22885898/7177ec15-98f7-47c5-8f8e-1d7aeef94732)

When it doesn't work:
![image](https://github.com/PrestaShop/PrestaShop/assets/22885898/9ada6d88-af5f-4d13-af3c-ef4f8dbfb844)

The error says "erreur lors de la création de l'image supplémentaire" (or "Error while creating additional image" in english).

The error seems to occur more often when I import several images at once. But it's not systematic at all, sometimes it works without a hitch for a while, and sometimes it works very badly for a while. This doesn't necessarily affect all the images: if I import 3 images, only 2 will be imported (for example).

### Expected behavior

All images are imported.

### Steps to reproduce

1. Create a product
2. Import images on the products
3. Look if all images are imported

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.3

**Comment by aniszr** [comment]
Hello,
I couldn't reproduce this issue, it seems that the problem is solved.
 
 See attached screenshot:
 
![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/993205b4-99db-4e73-8ffb-410b8dd8fc4d)

Thanks!

**Comment by yannicka** [comment]
As I said, the problem doesn't appear every time. How many tests have you done?
