### ISSUE TITLE
Is not possible to modify the faceted search query

### ISSUE THREAD

**Issue by borjagarciab** [PrestaShop/PrestaShop#32951]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

For developers , is not possible to modify the query from faceted seach module.
I've created this pull request https://github.com/PrestaShop/ps_facetedsearch/pull/857 to sort this.

I don't know if you need more information.

Thanks!

### Steps to reproduce

-

### PrestaShop version(s) where the bug happened

1.7.8.9

### If your bug is related to a module, specify its name and its version

ps_facetedsearch

**Comment by florine2623** [comment]
Hello @borjagarciab ,

Could you specify the steps to reproduce and the expected behavior in your issue please ?

Thanks!

**Comment by borjagarciab** [comment]
Hi!
Is not replicable because the functionality does not exists.
Simply , from module is not possible override or use any hook to modify the faceted search query.
I've sent the PR to allow to modify the query.
I have open this ticket because is required for PR.

Thanks!

**Comment by florine2623** [comment]
Ok ^^
So this is not a bug, rather an improvement.
Thank you for your suggestion. The Product Team will take it into consideration for future developments. 

Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you create it. 

If you or anyone else is willing to [contribute this feature](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/) to the PrestaShop Project, the teams will be happy to help by ensuring that it fits well within the project. Please let us know if that is the case!

Thank you

**Comment by RosaBenouamer** [comment]
not sure it's a question for the product team.
It's more a technical question to be able to override a research ?
What is the functional impact of the modification you propose @borjagarciab
