### ISSUE TITLE
A 404 error is displayed when enabling the column 'Is it the mail URL' in shop url page

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#32964]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

A 404 error is displayed when disabling the column 'Is it the mail URL' in shop url page

Please see the screen video => https://watch.screencastify.com/v/MZEtRcHiT885lTDdzc5d

### Expected behavior

An error /validation message should be displayed when we try to disable 'Is it the mail URL'

### Steps to reproduce

1- Enable multistore
2- Go to multistore page
3- Create new shop URL (add virtual URL)
4- Enable 'Is it the mail URL' from the table
5- See the error

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

8.1

**Comment by aniszr** [comment]
Hello,

I couldn't reproduce this issue with PS Version :8.1 & PHP version:8.1
See Attached screenrecord:

https://github.com/PrestaShop/PrestaShop/assets/92626242/88ca39f1-3872-4c4b-b347-7f1e3318c02d

Please check and feedback
Thanks!

**Comment by hibatallahAouadni** [comment]
Ping @nesrineabdmouleh could you please provide more infos to help us reproducing the issue :pray: 
Thanks in advance!

**Comment by nesrineabdmouleh** [comment]
Hello @hibatallahAouadni, @aniszr 
It was a config problem in my **/etc/apache2/apache2.conf** file (`AllowOverride` is not enabled)
Thank you all !
