### ISSUE TITLE
False TVA rounding calculation

### ISSUE THREAD

**Issue by Samuel871933** [PrestaShop/PrestaShop#32963]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Good morning,

I face a pbolem on prestashop 1.7.8.3 with the VAT rounding system when a specific tariff is applied to the products.

As the screen shows here we have a total price worth 430.58 with a 20% VAT therefore 430.58*0.2 = 86.116.

The tax is rounded to 86.11€. See screen

![image](https://github.com/PrestaShop/PrestaShop/assets/77780957/1af78259-bb25-42fd-ad9e-916f0ed5f094)

However the rounding should be done to 86.12 given my store settings. See screen.

![image](https://github.com/PrestaShop/PrestaShop/assets/77780957/89886101-d549-416b-9665-965a04b22916)

I tried to look a little bit, but I haven’t found any solutions yet. Do you have a suggestion? 

Thank you.

### Expected behavior

Price should be rounded up 

### Steps to reproduce

1- Go into products, add VAT to a product.
2 - Add a Percentage Discount to the product from 2 products.
3 - Add product to cart in quantity 2
4 - Perform VAT calculations manually.
5 - Check that the third digit > 5 otherwise modify price to notice the problem with a price having the 3rd digit > 5

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4.33

**Comment by cruftex** [comment]
Hello,

I recently hit the same or similar problem. I am doing some testing before going live. Unfortunately, the third invoice had a wrong total off by 1 cent. 

The epics regarding wrong price calculations are:

- https://github.com/PrestaShop/PrestaShop/issues/14900
- https://github.com/PrestaShop/PrestaShop/issues/19445
- https://github.com/PrestaShop/PrestaShop/issues/13822
- https://github.com/PrestaShop/PrestaShop/issues/9703

Please check whether your particular issue is adding a new aspect. If not, please close it.

I know the problem is frustrating, but more issues will not make it any better.

**Comment by aniszr** [comment]
Hello @SamuelRdev 

Thanx for this issue  , I was unable to reproduce it with same steps you mentioned.

See attached screenrecord:


https://github.com/PrestaShop/PrestaShop/assets/92626242/95a351f4-70c2-4dc8-9e7d-344233dd4508

Thank you !

**Comment by cruftex** [comment]
@sallemiines @aniszr 
>  I was unable to reproduce it with same steps you mentioned.

That is not help full, either. To reproduce this, you need to have the exact same product net prices.

Since this issue tracker is in English, it would also be great to see the recording in English.

**Comment by Samuel871933** [comment]
To reproduce the problem, you must add a discount on products of a certain amount. For example: 5% discount of 2 products.
