### ISSUE TITLE
Unfortunately, there are no carriers available for your delivery address.

### ISSUE THREAD

**Issue by OliverCG** [PrestaShop/PrestaShop#32977]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The customer is not able to select an active and well configured carrier for selected address delivery. We've tried the following steps without luck:
- Login with the customer information in a private tab.
- Implement the [fix stated here](https://github.com/PrestaShop/PrestaShop/issues/9932#issuecomment-783376475).
- Disable/re-enable country.
- Disable/re-enable zone.
- Disable/re-enable states.
- Change country specification like set the identification number or states as required and set back to non required.
- Re-save carrier.
- Insert a new address for that customer.
- Try with Germany instead of France with same results.
- Disable non-native modules.

There are no carriers modules or, at least, the modules are not modifying the checkout carrier step.

We're read all previous issues related to this bug but all what we have found is too old or fixed in previous releases.

Payment preferences
![Captura de pantalla 2023-06-22 a las 13 23 02](https://github.com/PrestaShop/PrestaShop/assets/1497981/a1e29186-67b2-4925-a350-71109729a430)

Country settings
![Captura de pantalla 2023-06-22 a las 13 22 41](https://github.com/PrestaShop/PrestaShop/assets/1497981/8c7def9d-6c5b-4157-a187-e5279a71a9bd)

States enabled
![Captura de pantalla 2023-06-22 a las 13 22 21](https://github.com/PrestaShop/PrestaShop/assets/1497981/eabc956e-0626-4084-8436-03929ad8a760)

Countries enabled
![Captura de pantalla 2023-06-22 a las 13 22 12](https://github.com/PrestaShop/PrestaShop/assets/1497981/20003e00-0bc1-407c-b96b-c199619662f1)

Zones enabled
![Captura de pantalla 2023-06-22 a las 13 22 06](https://github.com/PrestaShop/PrestaShop/assets/1497981/d67bbabb-adf4-4829-b50a-d03266b69722)

Carrier settings
![Captura de pantalla 2023-06-22 a las 13 21 49](https://github.com/PrestaShop/PrestaShop/assets/1497981/d8da8c21-f4fd-456e-9e8b-332e80bb41d4)

There is no carrier restriction inside the product specifications.

### Expected behavior

The system should show the carrier active for that zone, country, product and customer group.

### Steps to reproduce

1. Go to FrontOffice.
2. Login with the customer information.
3. Insert a product (no matter what) in the cart.
4. Go to checkout.
5. Select the shipping and delivery address.
6. Shipping step with no carriers available.

It's also happening on BackOffice:
1. Go to Orders -> Orders.
2. Add new order.
3. Search for that customer and select it.
4. Insert a product.
5. Select address.
6. Shipping section with no carriers available.

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.1.18

### Your company or customer's name goes here (if applicable).

TejidosOnline

**Comment by AureRita** [comment]
Hi @OliverCG 

Thank you for your report, I tried to reproduce your Issue but currently I can't as you can see : 

[Untitled_ Jun 22, 2023 4_10 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/875f5519-bfba-4c19-938a-337722aa476f)

Can you give us in wich languages you set up your shop and also in which countries ? 
Did you set the same thing with Italia and Germany ? 

Waiting for your feedback

**Comment by OliverCG** [comment]
> Hi @OliverCG
> 
> Thank you for your report, I tried to reproduce your Issue but currently I can't as you can see :
> Untitled_.Jun.22.2023.4_10.PM.webm
> 
> Can you give us in wich languages you set up your shop and also in which countries ? Did you set the same thing with Italia and Germany ?
> 
> Waiting for your feedback

Hi @AureRita,

Of course. The language of my shop is only one, and it's Spanish.

And yes, changing the shipping/delivery address by Italy or Germany causes the same issue.

We have to say that this shop started in PrestaShop 8.0.1 and was upgraded to 8.0.4 on every release, one by one. Do you think that one of these upgrades can be causing this issue, maybe?

What would be the next step in any case? Thank you!

**Comment by sallemiines** [comment]
Hello @OliverCG 


Thank you for your feedback, I didn't manage to reproduce your issue with PS 804 , 810 

https://github.com/PrestaShop/PrestaShop/assets/31663369/3edacab1-3cd9-4e1b-9410-e3d8aa59f7e5

Could you please provide us a screen recorder  for the result you had ! 

Waiting for you ! 
Thank you !

**Comment by OliverCG** [comment]
Of course. Give me some days and I'll record my screen to show you what's happening.

Thank you!

**Comment by AureRita** [comment]
Hi @OliverCG 

Thank you for your time ! When you test again with your issue, can you said us if you can't reproduce this issue with portugal country ? 

Waiting for your video

**Comment by OliverCG** [comment]
Sure. But are you talking about setting the country of the shop to Portugal, or about using a delivery/shipping address from Portugal?

I'll try to record the video as soon as possible. Sorry for the delay. :)

**Comment by AureRita** [comment]
I'm talking about using a delivery.shipping address from Portugal, because it's also a contry from europe and I think you'll not have issue with it. 

No problem, take your time

**Comment by aniszr** [comment]
Hello @OliverCG ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Comment by OliverCG** [comment]
Sorry for the very late reply but you're right @AureRita! The issue is not present with Portugal, just Germany and France.

Can you please re-open the issue, @aniszr? :) 

https://github.com/PrestaShop/PrestaShop/assets/1497981/a8ce2b39-8596-421f-91ef-24cc59f991d6

**Comment by ilyassw** [comment]
Hi ,

I got the same issue as OliverCG but unfortunately i couldn't get to the bottom of it and i am running latest prestashop 8.1.2.  What could be the cause ?   @OliverCG  did you manage to sort this issue ? Thanks
