### ISSUE TITLE
Precio unitario sale mal con selector de cantidad

### ISSUE THREAD

**Issue by AlbertoADV** [PrestaShop/PrestaShop#32978]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

There is a bug when setting the unit price on products with quantity variations that each quantity has a different price, this makes the unit price wrong since it always takes the final price with VAT and the first quantity that is selected always takes the unit price with 25 units, example:
The product has a unit price of €3.18 and its final price is worth €79.46, this is fine (I would also like the unit price to be without VAT)
Now the problem comes from the fact that when you put quantities 50, the final price with VAT changes because it is so set in the variations, so what the unit price does is take the final price and keep dividing it between 25 and not 50,
What I ask is that you look at why it does that, that the unit price does not change according to the quantity that is selected at that moment
![image](https://github.com/PrestaShop/PrestaShop/assets/137405393/df443578-d7c4-4d7f-be9e-14251b614df1)
![image](https://github.com/PrestaShop/PrestaShop/assets/137405393/cea2feed-8dfc-445d-9300-6614f7bb102d)
I attached pictures so you can see it more clearly.

### Expected behavior

What I expect to happen is that when the quantity is changed that does the unit price well,
Example
Unit price is €3.18 with a total value of €74.49 for a quantity of 25
Well, when the quantity changes, the unit price changes and out
Unit price is €1.90 with a total value of €95.4 for a quantity of 50
 

### Steps to reproduce

1. Go to http://bowings.es/imanes-gota-resina/36-1415-doming-magnets-high-quality-square-50-x-50-mm.html#/19-dimension-50x50mm/33-cantidad-25
2. Select 50 in quantity and you will see that the unit price is not the one that corresponds and you are always taking either 50 or 200 in quantity you are taking 25 to do the operation

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4.33

### Your company or customer's name goes here (if applicable).

http://bowings.es/

**Comment by AureRita** [comment]
Hello,

Please send your request in English. English is the norm on GitHub.
Can you modify your issue ? 

Thank you
Waiting for your feedback

**Comment by florine2623** [comment]
Hello @AlbertoADV ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Comment by AlbertoADV** [comment]
Hello I have posted the comment in English please check it.
