### ISSUE TITLE
Faceted_search Filter disabled and cannot be enabled

### ISSUE THREAD

**Issue by paulnoelcholot** [PrestaShop/PrestaShop#32987]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On the develop branch, all the template filters of the Faceted search module are disabled and cannot be enabled.

### Expected behavior

If I activate the filters of a template and I save, the changes should be applied

### Steps to reproduce

1. On BO > Modules > Module Manager > Faceted search > Configure
2. Edit a template.
3. You can see that all filters are disabled when it should be enabled by default.
4. Enable all filters.
5. Save.
6. Edit again this template.
7. You can see that all filters are disabled. They are saved correctly to the database, but their checkboxes are not set to ON position.

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_facetedsearch (all version)

**Comment by sallemiines** [comment]
Hello @paulnoelcholot 

Thank you for this issue 

I reproduce your issue with PS develop NOK :x: 


https://github.com/PrestaShop/PrestaShop/assets/31663369/fb58c37c-9ab5-4338-a7fd-f6a7c1bbe69f




PS 804 , PS 1789  OK :heavy_check_mark: 


https://github.com/PrestaShop/PrestaShop/assets/31663369/3842e27e-3211-47ae-9fbd-52626486b3f6


NIce Catch it's a regression on develop !

Thank you !
