### ISSUE TITLE
$subcategory.image is not set in template/catalog/_partials/subcategories.tpl when header category image is not set

### ISSUE THREAD

**Issue by GreyShinbusan** [PrestaShop/PrestaShop#33009]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I am moving from 1.6 to 8.1rc.
And found an issue with categories miniatures.
For some reason they are set as $subcategory.image.large.url but shoud not
I found they should be set as 
$subcategory.image.small.url

But this variable is not set if the $subcategory.image.large.url is not set.
Even when miniature of the subcategory is set and just subcategory header image is not set.

### Expected behavior

Category miniature should be seen on category list page even when category image is not set.

### Steps to reproduce

1. Make sure you have set miniature image for a subcategory and do not have set any main image for the subcategory.
2. Go to template/catalog/_partials/subcategories.tpl
3. put code: {$subcategory.image|var_dump}
4. clear website cache
5. view subcategory page
6. no image variable although miniature is set, miniature of the subcateogry is not seen.

### PrestaShop version(s) where the bug happened

8.1rc

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

Chris Studzinski

**Comment by AureRita** [comment]
Hi @GreyShinbusan 

Thank your for your report, Currently, this issue is already on our scope, as you can see here : https://github.com/PrestaShop/PrestaShop/issues/30520

So, because of that, I will close your issue 

Thank you !
