### ISSUE TITLE
Compile Error: Declaration of Egulias after restore from backup

### ISSUE THREAD

**Issue by Peter4661** [PrestaShop/PrestaShop#33019]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After failed upgrade to version 1.8, restored website from backup.

Now with changing order status, error message appears: 

Compile Error: Declaration of Egulias\EmailValidator\Validation\MessageIDValidation::isValid(string $email, Egulias\EmailValidator\EmailLexer $emailLexer): bool must be compatible with Egulias\EmailValidator\Validation\EmailValidation::isValid($email, Egulias\EmailValidator\EmailLexer $emailLexer)

[Symfony\Component\Debug\Exception\FatalErrorException 0]

### Expected behavior

When in backoffice order status is changed, error message appears. If returned to the order previous page, order status has been changed.

### Steps to reproduce

see above

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

not applicable

**Comment by sallemiines** [comment]
Hello @Peter4661 


Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template and provide clear and concise steps to reproduce the bug**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). 
Feel free to open a new one if you can provide more infos :wink: 

Thank you
