### ISSUE TITLE
PHP Fatal error - Kernel Container is not available in

### ISSUE THREAD

**Issue by Peter4661** [PrestaShop/PrestaShop#33018]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Upgrade Prestashop from 1.7.8.9 to 8.0.4.
all overrides disabled,  non Prestashop modules disabled, classic theme. 
PHP : 7.4.33 (After installation of 8.0.4 switched to PHP 8.2)

### Expected behavior

Admin side okay.
Front side "white screen".
With debug active, error"Error "Kernel Cotainer is not available in ContainerFinder.php" 

### Steps to reproduce

see above

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.4.33 / 8.2 (after upgrade)

### If your bug is related to a module, specify its name and its version

not applicable

**Comment by jlores** [comment]
Prestashop 8.0.4 is not compatible with PHP8.2

https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/

**Comment by sallemiines** [comment]
Hello @Peter4661 

You need to downgrade your PHP version as @jlores  said the Prestashop 8.0.4 is not compatible with PHP8.2.

If you still enocunter the issue try to rollback and then upgrade again.
Closing the issue as it seems to be related to System requirements breach.

Thanks!

**Comment by Peter4661** [comment]
Downgraded PHP version to 8.04. Issue stil present.

Rollback and upgraded again as suggested. PHP 8.0.4.  Encountered issue again.

Debug on:
**Error front**:
Fatal error: Uncaught PrestaShop\PrestaShop\Core\Exception\ContainerNotFoundException: Kernel Container is not available in /var/www/vhosts/xxxxxx/httpdocs/src/Adapter/ContainerFinder.php:77 Stack trace: #0 /var/www/vhosts/xxxxxx/httpdocs/classes/module/Module.php(1671): PrestaShop\PrestaShop\Adapter\ContainerFinder->getContainer() #1 /var/www/vhosts/xxxxxx/httpdocs/classes/module/Module.php(1660): ModuleCore::getModuleRepository() #2 /var/www/vhosts/xxxxxx/httpdocs/classes/Hook.php(836): ModuleCore::getNativeModuleList() #3 /var/www/vhosts/xxxxxx/httpdocs/classes/Dispatcher.php(586): HookCore::exec('moduleRoutes', Array, NULL, true, false) #4 /var/www/vhosts/xxxxxx/httpdocs/classes/Dispatcher.php(243): DispatcherCore->loadRoutes() #5 /var/www/vhosts/xxxxxx/httpdocs/classes/Dispatcher.php(201): DispatcherCore->__construct(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/vhosts/xxxxxx/httpdocs/index.php(28): DispatcherCore::getInstance() #7 {main} thrown in /var/www/vhosts/xxxxxx/httpdocs/src/Adapter/ContainerFinder.php on line 77


**Error in backoffice:**
PrestaShopException
in /var/www/vhosts/xxxxxx/httpdocs/classes/db/DbPDO.php (line 151)
    protected function _query($sql)    {        try {            return $this->link->query($sql);        } catch (\PDOException $exception) {            throw new PrestaShopException($exception->getMessage(), (int) $exception->getCode(), $exception);        }    }    /**
	
	
	PDOException
SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

in /var/www/vhosts/xxxxxx/httpdocs/classes/db/DbPDO.php (line 149)
     * @return PDOStatement     */    protected function _query($sql)    {        try {            return $this->link->query($sql);        } catch (\PDOException $exception) {            throw new PrestaShopException($exception->getMessage(), (int) $exception->getCode(), $exception);        }    }
	 
	 PrestaShopException
SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

in /var/www/vhosts/xxxxxx/httpdocs/classes/db/DbPDO.php (line 151)
    protected function _query($sql)    {        try {            return $this->link->query($sql);        } catch (\PDOException $exception) {            throw new PrestaShopException($exception->getMessage(), (int) $exception->getCode(), $exception);        }
