### ISSUE TITLE
problems with changing the quantity of the products and discount

### ISSUE THREAD

**Issue by PatrykFamilis** [PrestaShop/PrestaShop#33025]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello.

Recently on the PrestaShop, there have been bugs with giving discounts. Once a discount is given, the discount does not appear on the front end page, and sometimes the discount cannot be removed later.

In addition, problems with changing the quantity of available products. Stock levels of products do not update either after a customer purchases or after a manual change of stocks. In addition, after selecting the "allow ordering" option - the product cannot be ordered. Isn't this a bug of the program?

Problems started about one week ago. Up to this point, we have not made any changes, we have not installed any additional modules, etc. The only change was the update of PrestaShop modules from the back end.

There is a bug of PrestaShop? What can be the reason, that errors shows up without any changing from my side?

What is the easiest and fastest way to checked it and fixed it.

Thanks in advance for help and advice:)

Regards

### Steps to reproduce

[Produkt error www_familis_pl – 2023-06-26 20-34-30.zip](https://github.com/PrestaShop/PrestaShop/files/11886262/Produkt.error.www_familis_pl.2023-06-26.20-34-30.zip)

### PrestaShop version(s) where the bug happened

1.7.6.7

### PHP version(s) where the bug happened

7.2.34

**Comment by florine2623** [comment]
Hello @PatrykFamilis ,

Thanks for your report.
Sadly, we do not fix issues on the old product page anymore. The new product page is out on newer versions of PrestaShop. More info here : https://www.prestashop-project.org/releases/prestashop80/

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
