### ISSUE TITLE
[develop] FO - Warning is displayed in product page

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#33030]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

A warning is displayed on my product page.

<img width="1304" alt="Screenshot 2023-06-28 at 10 58 21" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/e9afec48-7104-4c79-999c-b309af38a105">

`Warning: Trying to access array offset on value of type null in my-shop/controllers/front/ProductController.php on line 455`

### Expected behavior

The warning should not be displayed.
On demo products, the warning is not displayed; only newly created products.

### Steps to reproduce

1. Install branch `develop`
2. Create a new product
3. Preview
4. See Warning displayed

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment]
Something with the manufacturer image fallback, I will look into it.👍
