### ISSUE TITLE
PHP Fatal error - Kernel Container is not available

### ISSUE THREAD

**Issue by Peter4661** [PrestaShop/PrestaShop#33038]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

upgrade Prestashop from 1.7.8.9 to 8.0.4.
all overrides disabled, non Prestashop modules disabled, classic theme.
PHP : 7.4.33 (After installation of PS 8.0.4 switched to PHP 8.0.4
White screen in front

**Debug on:**
**Error front:**
`Fatal error: Uncaught PrestaShop\PrestaShop\Core\Exception\ContainerNotFoundException: Kernel Container is not available in /var/www/vhosts/xxxxxx/httpdocs/src/Adapter/ContainerFinder.php:77 Stack trace: #0 /var/www/vhosts/xxxxxx/httpdocs/classes/module/Module.php(1671): PrestaShop\PrestaShop\Adapter\ContainerFinder->getContainer() #1 /var/www/vhosts/xxxxxx/httpdocs/classes/module/Module.php(1660): ModuleCore::getModuleRepository() #2 /var/www/vhosts/xxxxxx/httpdocs/classes/Hook.php(836): ModuleCore::getNativeModuleList() #3 /var/www/vhosts/xxxxxx/httpdocs/classes/Dispatcher.php(586): HookCore::exec('moduleRoutes', Array, NULL, true, false) #4 /var/www/vhosts/xxxxxx/httpdocs/classes/Dispatcher.php(243): DispatcherCore->loadRoutes() #5 /var/www/vhosts/xxxxxx/httpdocs/classes/Dispatcher.php(201): DispatcherCore->__construct(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/vhosts/xxxxxx/httpdocs/index.php(28): DispatcherCore::getInstance() #7 {main} thrown in /var/www/vhosts/xxxxxx/httpdocs/src/Adapter/ContainerFinder.php on line 77`

**Error in backoffice:**
```
PrestaShopException
in /var/www/vhosts/xxxxxx/httpdocs/classes/db/DbPDO.php (line 151)
protected function _query($sql) { try { return $this->link->query($sql); } catch (\PDOException $exception) { throw new PrestaShopException($exception->getMessage(), (int) $exception->getCode(), $exception); } } /**

PDOException
SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

in /var/www/vhosts/xxxxxx/httpdocs/classes/db/DbPDO.php (line 149)
* @return PDOStatement */ protected function _query($sql) { try { return $this->link->query($sql); } catch (\PDOException $exception) { throw new PrestaShopException($exception->getMessage(), (int) $exception->getCode(), $exception); } }

 PrestaShopException
SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

in /var/www/vhosts/xxxxxx/httpdocs/classes/db/DbPDO.php (line 151)
protected function _query($sql) { try { return $this->link->query($sql); } catch (\PDOException $exception) { throw new PrestaShopException($exception->getMessage(), (int) $exception->getCode(), $exception); }

)
```

### Expected behavior

Normal operation of Prestashop

### Steps to reproduce

1 normal upgrade though automated upgrade module

### PrestaShop version(s) where the bug happened

from 1.7.8.9 to 1.8.04

### PHP version(s) where the bug happened

8.04

### If your bug is related to a module, specify its name and its version

not applicable

**Comment by florine2623** [comment]
Hello @Peter4661 ,

Which version of autoupgrade are you using ?

**Comment by Peter4661** [comment]
Hello Florine2623,

Thank you for coming back to me. :) We are on v4.16.0 - door PrestaShop

**Comment by florine2623** [comment]
@Peter4661 ,

Using the same config as you, I can't reproduce your issue.
On my end, the upgrade went well.

<img width="1440" alt="Screenshot 2023-06-29 at 10 03 20" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/b7780716-07cf-4855-b1fa-4755644dcac3">

https://github.com/PrestaShop/PrestaShop/assets/16019289/516d5e7a-42e9-4fc2-9083-a0a5e5cb7aa5

**Comment by Peter4661** [comment]
With our site, the upgrade also went well. 

However, the front end had white screen. Admin side seemd okay. With dubug activated, the error messages showed up.

**Comment by florine2623** [comment]
On what pages the error are displayed ? The whole FO and BO ?

With and without debug mode enabled, I can access both FO and FO and make an order.

https://github.com/PrestaShop/PrestaShop/assets/16019289/534f9921-b566-4089-a5c7-e632d02d5e73


https://github.com/PrestaShop/PrestaShop/assets/16019289/15049081-046d-4408-9f7e-7b99c592dc48

**Comment by florine2623** [comment]
Also, the error `SQLSTATE[HY000]: General error: 2006 MySQL server has gone away` seems like the issue comes from your server. You need to contact your hosting provider to allow a longer execution time.

**Comment by Peter4661** [comment]
Hi Florine2623,

We  made another 2 attempts to update. Unfortunatly both failed, now with different error (debug on), see below. Server error log below. 

Folder and file permissions okay.

In server log: Connection to  [uds://usr/local/lsws/extapp-sock/APVH_derkswie_Suphp80.sock] on request  #0, confirmed, 1, associated process: 2935993, running: 1, error:  Connection reset by peer! |  

This is resulting in 503 error.
 
On the internet, I fould following suggestion to resolve this issue: Simply open the php.ini file and remove the bad directive (in my case register_globals) or comment it out.

We made no attempt to test if the suggestion would work for us.

Do you have suggestions how we could get our finger nails behind this problem?

Debug on:
In Front

Warning: Attempt to read property "id_category_default" on null in /var/www/vhosts/derks-wielersport.nl/httpdocs/controllers/front/ProductController.php on line 1332

Warning: Attempt to read property "name" on null in /var/www/vhosts/derks-wielersport.nl/httpdocs/controllers/front/ProductController.php on line 1352

Fatal error: Uncaught Error: Call to a member function getAttributeCombinations() on null in /var/www/vhosts/xxxxxx/httpdocs/controllers/front/ProductController.php:1091 Stack trace: #0 /var/www/vhosts/xxxxxx/httpdocs/controllers/front/ProductController.php(1044): ProductControllerCore->tryToGetAvailableIdProductAttribute(0) #1 /var/www/vhosts/xxxxxx/httpdocs/controllers/front/ProductController.php(1353): ProductControllerCore->getIdProductAttributeByRequest() #2 /var/www/vhosts/xxxxxx/httpdocs/classes/controller/FrontController.php(1819): ProductControllerCore->getBreadcrumbLinks() #3 /var/www/vhosts/xxxxxx/httpdocs/classes/controller/FrontController.php(512): FrontControllerCore->getBreadcrumb() #4 /var/www/vhosts/xxxxxx/httpdocs/classes/controller/FrontController.php(569): FrontControllerCore->assignGeneralPurposeVariables() #5 /var/www/vhosts/xxxxxx/httpdocs/controllers/front/ProductController.php(464): FrontControllerCore->initContent() #6 /var/www/vhosts/xxxxxx/httpdocs/tools/profiling/Controller.php(60): ProductControllerCore->initContent() #7 /var/www/vhosts/xxxxxx/httpdocs/classes/Dispatcher.php(510): Controller->run() #8 /var/www/vhosts/xxxxxx/httpdocs/index.php(28): DispatcherCore->dispatch() #9 {main} thrown in /var/www/vhosts/xxxxxx/httpdocs/controllers/front/ProductController.php on line 1091

Serverlog as result of access modules folder:

<html><body>


2023-06-30 11:03:13 | Error |   |   | .162126  [INFO] [2927484] [T0]  [95.98.50.12:54408-H3:6290803CD4B50F21-84#APVH_xxxxxx:443]  connection to  [uds://usr/local/lsws/extapp-sock/APVH_derkswie_Suphp80.sock] on request  #0, confirmed, 1, associated process: 0, running: 0, error: Connection  reset by peer! |   |   |  
2023-06-30 11:03:13 | Error |   |   | .511031  [INFO] [2927484] [T0]  [95.98.50.12:54408-H3:6290803CD4B50F21-84#APVH_xxxxxx:443]  connection to  [uds://usr/local/lsws/extapp-sock/APVH_derkswie_Suphp80.sock] on request  #0, confirmed, 1, associated process: 2935989, running: 1, error:  Connection reset by peer! |   |   |  
2023-06-30 11:03:13 | Error |   |   | .833862  [INFO] [2927484] [T0]  [95.98.50.12:54408-H3:6290803CD4B50F21-84#APVH_xxxxxx:443]  connection to  [uds://usr/local/lsws/extapp-sock/APVH_derkswie_Suphp80.sock] on request  #0, confirmed, 1, associated process: 2935993, running: 1, error:  Connection reset by peer! |   |   |  
2023-06-30 11:03:13 | Error |   |   | .833886  [NOTICE] [2927484] [T0]  [95.98.50.12:54408-H3:6290803CD4B50F21-84#APVH_xxxxxx:443]  **Max retries has been reached**, 503! |   |   |  
2023-06-30 11:03:13 | Error |   |   | .833934  [NOTICE] [2927484] [T0]  [95.98.50.12:54408-H3:6290803CD4B50F21-84#APVH_xxxxxx:443]  oops! 503 Service Unavailable


</body>
</html>

**Comment by florine2623** [comment]
Hello @Peter4661 ,

Maybe these threads can help : 
- https://www.prestashop.com/forums/topic/1052034-php-fatal-error-kernel-container-is-not-available-in-varwwwhtmlwwwsrcadaptercontainerfinderphp77/
- https://github.com/PrestaShop/PrestaShop/issues/15503

As this issue can't be reproduced, I suggest considering one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by jonasburneika** [comment]
I'd like to add info for these who will be in  same situation as I was. Managed to reproduce this issue with two separate PrestaShop instances. (1.7.7.8 was upgraded with 1-click module) and (1.7.8.7 fresh install)
On both cases executed same file with code and both cases failed:

```
<?php
require dirname(__FILE__) . '/config/config.inc.php';
class shippedOrder
{
    const SHIPPED_STATUS = 4;
    public function __construct($idOrder)
    {
        $order = new Order($idOrder);
        if(!Validate::isLoadedObject($order)){
            throw new Exception("Order not found");
        }
        $order->setCurrentState(self::SHIPPED_STATUS);
    }
}

$idOrder = 1; /// SET YOUR VALID ORDER ID

new shippedOrder($idOrder);
```
I think problem is in Tools::getContextLocale() method with this code part:

```
     $containerFinder = new ContainerFinder($context);
        $container = $containerFinder->getContainer();
        if (null === $context->container) {
            $context->container = $container;
        }
```
At this time context does not have any container. And it tries to assign it, but Method **getContainer()** tries to get container from three sources:

1. Context - does not have container at all.
2. Controller - this part works only if context has controller.
3. Kernel - was not loaded. **Global $kernel returned null**

Fixed with:
```

    public static function getContextLocale(Context $context)
    {
        $locale = $context->getCurrentLocale();
        if (null !== $locale) {
            return $locale;
        }

        $containerFinder = new ContainerFinder($context);
        if (null === $context->container) {
            $context->container = ContainerBuilder::getContainer('front', _PS_MODE_DEV_);
        }
        $container = $containerFinder->getContainer();

        /** @var LocaleRepository $localeRepository */
        $localeRepository = $container->get(self::SERVICE_LOCALE_REPOSITORY);
        $locale = $localeRepository->getLocale(
            $context->language->getLocale()
        );

        return $locale;
    }
```
