### ISSUE TITLE
[8.1.x] - BO - Product Page - Popup "Add new file" button displays the Dashboard instead of the New File Form

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#33036]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the product page, in Details tab, when I try to add a new file, a popup is supposed to allow me to add a new file.
Now the popup displays the Dashboard page.

https://github.com/PrestaShop/PrestaShop/assets/16019289/c77a15b9-f993-49bf-b2c4-30cc2fc90603

### Expected behavior

It should display this popup :
<img width="1440" alt="Screenshot 2023-06-28 at 17 47 20" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/16e0c38d-7e60-4a08-8bcc-cc29eb710644">

### Steps to reproduce

1. Go to Catalog > Products > Edit a product > Go to Details Tab
2.  In Step Attached files > Click on Add new file
3. First time, the correct popup is displayed.
4. Refresh, open the popup multiple time, see Dashboard displayed in popup :x:

### PrestaShop version(s) where the bug happened

8.1.x, develop

### PHP version(s) where the bug happened

8.1

**Comment by hibatallahAouadni** [comment]
From the first time it display the dashboard in the modal :scream: 
Nice catch @florine2623 it's a regression on 8.1.x

![image](https://github.com/PrestaShop/PrestaShop/assets/23308427/5db4ee90-6889-4c89-a273-eb65b257662c)
