### ISSUE TITLE
Create new order : The listing of carts/orders doesn't work

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#33049]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Create new order : The listing of carts/orders doesn't work

![image](https://github.com/PrestaShop/PrestaShop/assets/1533248/3e3954f3-2eee-4d64-9d9e-351fbf205309)

Maybe linked to #31621

### Expected behavior

Create new order : The listing of carts works

## Functional Test
1. Go to BO
2. Go to Orders Page
3. Click on "Add new order"
4. Search for Customer "John Doe"
5. Click on "Choose" button
6. The listing of carts/orders remains on "Loading"

## Automated Test
1. Go to `tests/UI` directory
2. Run `TEST_PATH="functional/BO/02*/01*/createOrders/04*" npm run test:specific:fast-fail`

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

**Comment by hibatallahAouadni** [comment]
Indeed it's a regression caused by the mentioned PR, see the attached screen record you will see at 2.42 that it keeps loading:
https://github.com/PrestaShop/PrestaShop/pull/31621#pullrequestreview-1500754947
