### ISSUE TITLE
ps_eventbus if module is installed prestashop is not accessible anymore

### ISSUE THREAD

**Issue by Jerome08** [PrestaShop/PrestaShop#33046]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

when the module ps_eventbus is installed, the prestashop is not accessible anymore
there is http 500 error
if i rename the module and kill processus on my host, the prestatop is working again
each time the module is in the folder modules, the prestashop is not accessible

Regards

### Steps to reproduce

go to folder ~/modules
if there is the module named "ps_eventbus" > prestashop is not working anymore
rename to other name like  : __ps_eventbus
kill host processus
prestashop works again normaly ...

### PrestaShop version(s) where the bug happened

1.7.6.7

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

ps_eventbus

**Comment by florine2623** [comment]
Hello @Jerome08 ,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
