### ISSUE TITLE
Module statsproduct does not show the sales graph

### ISSUE THREAD

**Issue by tecmikro** [PrestaShop/PrestaShop#33054]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have installed module **statsproduct (Product details)** v 2.1.1 in Prestashop 1.7.8.9, but the module does not show the sales graph (see attached image).
![image](https://github.com/PrestaShop/PrestaShop/assets/102133629/5b027370-dfc0-4a85-9057-20dfaf5b7a54)

### Expected behavior

The module should display the sales chart along with the visit chart.

### Steps to reproduce

1. Go to _Statistics > Product details_
2. Select a category
3. Select a product with sales

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

statsproduct, version 2.1.1

### Your company or customer's name goes here (if applicable).

tecmikro

**Comment by hibatallahAouadni** [comment]
Hello @tecmikro 

Did you encounter this issue only with statsproduct v_2.1.1 or even with older versions?
Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @tecmikro 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by tecmikro** [comment]
Hello @hibatallahAouadni, excuse me for not answering before.
With version **v2.1.0** it works better, but there is an error in the graphics labels. Where it says **Popularity** it should say **Sales**, and where it say **Sales** it should say **Visits**.
![image](https://github.com/PrestaShop/PrestaShop/assets/102133629/b221bda8-f5cb-4b80-86c6-e1c5973e37c5)
![image](https://github.com/PrestaShop/PrestaShop/assets/102133629/68bb8e80-db58-4752-9423-106c855fdaec)
