### ISSUE TITLE
Error upgrading from 8.0.4 to 8.1.0 with autoupgrade 4.16

### ISSUE THREAD

**Issue by xga91** [PrestaShop/PrestaShop#33064]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

At the end upgraded red messaging.

[INTERNAL] /home/perles/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 180 - Symfony\Component\Config\Exception\LoaderLoadException: There is no extension able to load the configuration for "api_platform" (in "/home/perles/public_html/app/config/config.yml"). Looked for namespace "api_platform", found ""framework", "security", "twig", "monolog", "swiftmailer", "doctrine", "sensio_framework_extra", "prestashop", "translation_tools", "tactician", "fos_js_routing"" in /home/perles/public_html/app/config/config.yml (which is being imported from "/home/perles/public_html/app/config/config_prod.yml"). #0 /home/perles/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(104): Symfony\Component\Config\Loader\FileLoader->doImport() #1 /home/perles/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/FileLoader.php(66): Symfony\Component\Config\Loader\FileLoader->import() #2 /home/perles/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(197): Symfony\Component\DependencyInjection\Loader\FileLoader->import() #3 /home/perles/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(133): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseImports() #4 /home/perles/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/DelegatingLoader.php(40): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load() #5 /home/perles/public_html/app/AppKernel.php(211): Symfony\Component\Config\Loader\DelegatingLoader->load() #6 /home/perles/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(697): AppKernel->registerContainerConfiguration() #7 /home/perles/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(593): Symfony\Component\HttpKernel\Kernel->buildContainer() #8 /home/perles/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(136): Symfony\Component\HttpKernel\Kernel->initializeContainer() #9 /home/perles/public_html/app/AppKernel.php(93): Symfony\Component\HttpKernel\Kernel->boot() #10 /home/perles/public_html/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(76): AppKernel->boot() #11 /home/perles/public_html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader80.php(44): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #12 /home/perles/public_html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(87): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader80->initConstants() #13 /home/perles/public_html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader81.php(46): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #14 /home/perles/public_html/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(43): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader81->doUpgrade() #15 /home/perles/public_html/admin930dmtwi5/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #16 {main}

![2](https://github.com/PrestaShop/PrestaShop/assets/101413251/9a3c70e2-1cea-4d41-b606-97f120cf5db2)

### Expected behavior

working

### Steps to reproduce

Just using the auto upgrade module 4.16 latest version.

### PrestaShop version(s) where the bug happened

8.04 to 8.1

### PHP version(s) where the bug happened

8.1.19

**Comment by p0p3j** [comment]
I have the same problem with upgrade from 8.0.4 to 8.1.0. 
PHP 7.3
1-click upgrade v4.16.0

![Zrzut ekranu 2023-07-01 180640](https://github.com/PrestaShop/PrestaShop/assets/58376065/94facfb3-8f11-4923-b1ab-5aa7899f40b7)

**Comment by kpodemski** [comment]
Hello guys

Did you select "Disable non-native modules while upgrading" option? If not, could you try with it?

**Comment by p0p3j** [comment]
@kpodemski The problem occurs when option is set for "yes".

U mnie przy pierwszej próbie aktualizacja się udała, ale pacjent nie przeżył (nie miałem wyłączenia modułów, posypało sklep przez integrator od x13). Kolejne próby z wyłączeniem modułów kończyły się jak wyżej.

**Comment by xga91** [comment]
Pareil, apparement il y a un problème avec 2 clées manquante dans le fichier parameters.php

A quoi corresponde t-elle ? car en version 8.04, je n'ai pas ces champs dans ce fichier.

    'api_public_key'
    'api_private_key'

**Comment by x13pl** [comment]
@p0p3j zawsze na aktualizację sklepu sugerujemy aktualizację modułów do najwyższej wersji i nie zaszkodzi zmiana ich nazwy na sam czas aktualizacji, jak przechodzisz na wyższe PHP to trzeba pamiętać że moduł musi je obsługiwać

**Comment by p0p3j** [comment]
@x13pl standardowo przed i po aktualizacji presty puszczam dostępne aktualizacje modułów. Odnośnie PHP jasna sprawa, ze względu na integrator zgodnie z dokumentacją siedzę na 7.3 dalej. Myślałem że to może być powodem wykrzaczenia aktualizacji, jednak autor tematu ma ten sam problem na rekomendowanej PHP 8.1.

**Comment by AureRita** [comment]
Hi, 

Thank youf for your answer but please send your answer in English. English is the norm on GitHub.

Moreover, If I understand well the issue is about the private key or anything else, this element is already send in this issue : 
https://github.com/PrestaShop/PrestaShop/issues/33041

or this one https://github.com/PrestaShop/PrestaShop/issues/33021 

Can you confirm me that this issue is a dupplicate of on of the issues above ? 

Thank you

**Comment by xga91** [comment]
yep 

this 'api_public_key'
'api_private_key'

are not present at the end of the file in the app/config/parameters.php on 8.04

What is the purpose of these keys ? who is using it ?

**Comment by AureRita** [comment]
ok, because this one is a dupplicate, I'll close it because we are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #33041  .
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by AureRita** [comment]
Duplicate of #33041
