### ISSUE TITLE
Can't add tax to products

### ISSUE THREAD

**Issue by MockoB** [PrestaShop/PrestaShop#33073]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

There are TAX rules added, i choose countries, enabled the rules etc. But when I'm on the product page pricing tab, whatever I do, no matter, if it's new or demo product, there is just "NO Tax" standing in the Tax rule field and no tax could be choosen.

### Expected behavior

To be able to add tax on my products.

### Steps to reproduce

1. Enable taxes.
2. Go to products/pricing tab
3. Try to add tax to a product

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

8.1

**Comment by AureRita** [comment]
Hi @MockoB 

Thank you for your report, I tried to reproduce your issue as you can see : 

[Untitled_ Jul 3, 2023 5_06 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/6623cd30-73e2-4fc6-92e7-af4e6b963276)

Did I miss something ? 

Can you provide us more information ? a video ? some screenshot ? 

Waiting for your feedback

**Comment by MockoB** [comment]
Here are some screenshots. If you steel need video I'll try uploading one.

1. Enabled tax with 20% rate. I disabled all the others, but with or without them it's the same.
<a href="https://ibb.co/2jScTvV"><img src="https://i.ibb.co/2jScTvV/1tax.png" alt="1tax" border="0"></a>

2. Tax enabled.
<a href="https://ibb.co/fNpXFqY"><img src="https://i.ibb.co/fNpXFqY/2tax.png" alt="2tax" border="0"></a>

3. Still no tax could be chosen in the dropdown.
<a href="https://ibb.co/jvR2f7H"><img src="https://i.ibb.co/jvR2f7H/3tax.png" alt="3tax" border="0"></a>

**Comment by sallemiines** [comment]
Hello @MockoB 

Thank you for your report, I didn't manage to reproduce your issue 

![image (2)](https://github.com/PrestaShop/PrestaShop/assets/31663369/636ca58e-2306-4f27-b39a-1f25eeec415a)

![image (3)](https://github.com/PrestaShop/PrestaShop/assets/31663369/e816f8b2-f1f5-4b38-ae60-08ce9e97fccd)

Did I miss something ?

Waiting for your feedback

**Comment by MockoB** [comment]
Hi @sallemiines, here is the video, it expires in 48 hours.

https://streamable.com/e/ouaeig

**Comment by cruftex** [comment]
@MockoB 
I think you are confusing Taxes with Tax Rules. Cite from the documentation:

> You cannot directly apply a tax to a product; you can only apply tax rules. Therefore, you must first register all relevant taxes, then create a tax rule for that tax in order to specify the countries where the tax applies, and finally set the tax rule to the product.

**Comment by MockoB** [comment]
Obviously I’m complete idiot, enough lazy to read:)
Thanks for the clarification @cruftex
