### ISSUE TITLE
Errors in Upgrade PS from 8.0.4 to 8.1.0 - Error upgrading

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#33077]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I tried to upgrade prestashop from 8.0.4 to 8.1 several times  **with several php versions**, I do backup D-1 and I re do updating, I
tried with tow modules: autoupgrade v4.16.0 and  1-Click Direct Upgrade v 2.3.4

**autoupgrade v4.16.0**

[INTERNAL] /home/myweb/myweb/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/DefinitionErrorExceptionPass.php line 54 - Symfony\Component\DependencyInjection\Exception\RuntimeException: You have requested a non-existent parameter "api_private_key". #0 /home/myweb/myweb/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(83): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true) #1 /home/myweb/myweb/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/DefinitionErrorExceptionPass.php(32): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, true) #2 /home/mywebmyweb/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(47): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue(Array, true) #3 /home/myweb/myweb/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(94): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #4 /home/myweb/myweb/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(762): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #5 /home/myweb/myweb/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(594): Symfony\Component\DependencyInjection\ContainerBuilder->compile() #6 /home/myweb/myweb/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(136): Symfony\Component\HttpKernel\Kernel->initializeContainer() #7 /home/********/********/app/AppKernel.php(96): Symfony\Component\HttpKernel\Kernel->boot() #8 /home/myweb/myweb/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(76): AppKernel->boot() #9 /home/myweb/myweb/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader80.php(44): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #10 /home/myweb/myweb/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(87): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader80->initConstants() #11 /home/myweb/myweb/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader81.php(46): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #12 /home/myweb/myweb/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(43): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader81->doUpgrade() #13 /home/myweb/myweb/myweb/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #14 {main}

**1-Click Direct Upgrade v 2.3.4**

[INTERNAL] /home/myweb/myweb/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/DefinitionErrorExceptionPass.php line 54 - Symfony\Component\DependencyInjection\Exception\RuntimeException: You have requested a non-existent parameter "api_private_key". #0 /home/myweb/myweb*/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(83): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true) #1 /home/myweb/myweb/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/DefinitionErrorExceptionPass.php(32): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, true) #2 /home/myweb/myweb/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(47): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue(Array, true) #3 /home/myweb/myweb/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(94): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #4 /home/myweb/myweb/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(762): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #5 /home/myweb/myweb/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(594): Symfony\Component\DependencyInjection\ContainerBuilder->compile() #6 /home/myweb/myweb/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(136): Symfony\Component\HttpKernel\Kernel->initializeContainer() #7 /home/*******/******/app/AppKernel.php(96): Symfony\Component\HttpKernel\Kernel->boot() #8 /home/myweb/myweb/modules/ets_upgrade/classes/UpgradeTools/SymfonyAdapter(69): AppKernel->boot() #9 /home/myweb/myweb/modules/ets_upgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader80.php(41): PrestaShop\Module\EtsAutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #10 /home/myweb/myweb/modules/ets_upgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(88): PrestaShop\Module\EtsAutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader80->initConstants() #11 /home/myweb/myweb/modules/ets_upgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(39): PrestaShop\Module\EtsAutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #12 /home/myweb/myweb/myweb/ets_upgrade/upgradetab.php(72): PrestaShop\Module\EtsAutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #13 {main}

### Expected behavior

Working

### Steps to reproduce

Just simple updating from 8.0.4 to 8.1

### PrestaShop version(s) where the bug happened

8.0.4 to 8.1.0

### PHP version(s) where the bug happened

Tested with many php versions like 7.4

**Comment by AureRita** [comment]
Hi @prozou , 

Thank your for your report but this one seem to be the same of this one : https://github.com/PrestaShop/PrestaShop/issues/33041  

To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you
