### ISSUE TITLE
Bug / Image slider for your homepage v1.6.1

### ISSUE THREAD

**Issue by sasulm** [PrestaShop/PrestaShop#33074]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,
I have problems with the module "Image slider for your homepage v1.6.1 - by PrestaShop"
I have not access to this module and when we click on "install" the error message "The following module is already installed: homeslider" is displayed.
In addition, it is always displayed:
-colissimo (syntax error in /modules/colissimo/colissimo.php)
-colissimo (missing class in /modules/colissimo/colissimo.php)

Thanks for your help

### Steps to reproduce

1. I click on "install"
2. the error message "The following module is already installed: homeslider" is displayed.

### PrestaShop version(s) where the bug happened

1.6.1.11

### PHP version(s) where the bug happened

1361

### If your bug is related to a module, specify its name and its version

Image slider for your homepage v1.6.1 - by PrestaShop

**Comment by AureRita** [comment]
HI @sasulm  ,

PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).

Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

Thank you
