### ISSUE TITLE
Customer can order disabled product from front office 

### ISSUE THREAD

**Issue by Arshlanwebkul** [PrestaShop/PrestaShop#33071]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Please follow exactly as my video.

[github3.webm](https://github.com/PrestaShop/PrestaShop/assets/136475297/efb497b0-fa50-4d0a-a3b8-c7f92726f546)

### Expected behavior

While clicking on "Proceed to checkout" button on the next page or on the same page it should display error that "Product is not available"

### Steps to reproduce

Go to FO and add a product in cart
Now come to backoffice and disable the same product
Now go to the front office and without reloading just press on "Proceed to checkout"
You can see, you can order the product successfully, which must not be.

### PrestaShop version(s) where the bug happened

 8.1.0

### PHP version(s) where the bug happened

7.4 and 8.0

### Your company or customer's name goes here (if applicable).

Webkul

**Comment by AureRita** [comment]
Hi @Arshlanwebkul  ,

I reproduce the issue with PrestaShop version 8.0.4 and not with the version 1.7.8.9 as you can see : 

[Untitled_ Jul 3, 2023 5_14 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/a4a389fd-f61f-4d2c-bd5b-7341ddf52995)

Nice catch ! It's a regression ! I'll add it to the patch backlog.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
