### ISSUE TITLE
Unexpected behaviour with DateTimeColumn empty value

### ISSUE THREAD

**Issue by Kaikina** [PrestaShop/PrestaShop#33090]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you use a DateTimeColumn in a Grid, you're able to define a value to display in case the DateTimeColumn value would be empty, thanks to the empty_data parameter. Empty_data parameter is by default set to an empty string.

When passing an empty value to this column type, the current datetime is displayed.

### Expected behavior

The expected behaviour, is that if the DateTimeColumn receives an empty data, it displays an empty string, or the defined empty_data parameter's value.

### Steps to reproduce

Add or use any DateTimeColumn in a Grid. 
Pass it an empty value (false, null, 0, "", ...).
Check that it renders the current datetime instead of the empty_data parameter's value.

### PrestaShop version(s) where the bug happened

latest

### PHP version(s) where the bug happened

any

### Your company or customer's name goes here (if applicable).

Evolutive Group

**Comment by sallemiines** [comment]
Hello @Kaikina ,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!
