### ISSUE TITLE
Friendly URL break when used in Multistore context with LiteSpeed server

### ISSUE THREAD

**Issue by LameuleFR** [PrestaShop/PrestaShop#33099]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After switching to LiteSpeed to replace Apache, the URL friendly rewrite no longer works on virtual multishops.

According to my research, the .htaccess file is invalid and LiteSpeed server interprets it differently.

### Expected behavior

Functional url rewriting like Apache or Adaptative htaccess to fit LiteSpeed server

### Steps to reproduce

- Install a Prestashop on a LiteSpeed server
- Create a second shop with virtual url on the same domain
- Category url & image show 404 error.

### PrestaShop version(s) where the bug happened

1.6.1.11 - 8.0

### PHP version(s) where the bug happened

7.1-7.4

### Your company or customer's name goes here (if applicable).

**Comment by Hlavtox** [comment]
@LameuleFR Hi, could you try to find out which rules in htaccess are problematic? LiteSpeed should support standard Apache's htaccess files. It would be beneficial for the community if it worked right out of the box. 👍

**Comment by LameuleFR** [comment]
@Hlavtox 
https://i.gyazo.com/7ac0b3a0e38f7326a063d264645fbc33.png

If we delete the [L] on last line all URL become valid, there is no 404 error remaining on categories page.
Only images still have problem (https://i.gyazo.com/27dd197ebd77525e5ed7159a79f8af69.png)

**Comment by sallemiines** [comment]
Hello,

PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).

Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

Thank you

**Comment by LameuleFR** [comment]
Hello @sallemiines 

After more test the problem is also present with Prestashop 1.7.7.8 & Prestashop 8.
Also there is other trace of this problem: https://github.com/PrestaShop/PrestaShop/issues/28051

Benjamin

**Comment by cenourinha** [comment]
> @Hlavtox https://i.gyazo.com/7ac0b3a0e38f7326a063d264645fbc33.png
> 
> If we delete the [L] on last line all URL become valid, there is no 404 error remaining on categories page. Only images still have problem (https://i.gyazo.com/27dd197ebd77525e5ed7159a79f8af69.png)

Were you able to solve the problem with the images? We have the last LiteSpeed version, but this is still happening.
