### ISSUE TITLE
Module's information in backoffice are in different language after changing employee's lang

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#33091]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you change language in your backoffice, your module list in Module Manager remains in the original language. The issue is caused by module manager caching the list in the wrong language.

Chaging the caching key by adding a language fixes the issue.
```
protected function getCacheKey(string $moduleName, ?int $shopId = null): string
    {
        $shop = $shopId ? [$shopId] : Shop::getContextListShopID();

        return $moduleName . implode('-', $shop) . Context::getContext()->language->id;
    }
```

The second issue is that the cache does not get cleared when using Performance > Clear cache button.

### Expected behavior

It should be in the correct language.

### Steps to reproduce

1. Install Prestashop in Czech.
2. Go to International > Localization and import United Kingdom localization, select to import only "Languages".
3. Go to right-top > Your profile and change your Language to English.
4. Go to Modules > Module Manager and see that all module names and descriptions are in Czech, not in English.
5. Clearing cache, still nothing.
6. When you reset a single module, that module will fix itself and appear in English.

![Snímek obrazovky 2023-07-04 090956](https://github.com/PrestaShop/PrestaShop/assets/6097524/fcf8701e-9719-430b-ad32-0a2e3fffb7dc)

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

**Comment by sallemiines** [comment]
Hello @Hlavtox 
Thanx for this issue 
Tested with develop NOK ,  PS804 NOK

[Capture vidéo du 04-07-2023 11_49_05.webm](https://github.com/PrestaShop/PrestaShop/assets/31663369/9be644b9-5e76-4dca-809f-dc1feb35187b)

 

With 1789 OK 


https://github.com/PrestaShop/PrestaShop/assets/31663369/b0f32ba5-6ce1-4c9b-8e8a-a85e44595718

It's a regression on 804 ! 
Thank you !
