### ISSUE TITLE
Multistore - Fatal error when removing an main shop URL

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#33104]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

A fatal error is displayed when we delete a main shop URL 

[Multistore • PrestaShop.webm](https://github.com/PrestaShop/PrestaShop/assets/24647495/8bb9ac17-9862-4a0d-a7fb-b71cf21accbf)

### Expected behavior

When we delete a main URL an error message should be displayed

### Steps to reproduce

1-Enable multistore
2- Go to advanced parameters > multistore page
3- Create new URL
4- Disable "is the main URL" for the default url
5- Delete the created url
=> See the error

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.1

**Comment by sallemiines** [comment]
Hello @nesrineabdmouleh 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #32864.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by sallemiines** [comment]
Duplicate of #32864.
