### ISSUE TITLE
Controller paths is added in sitemap

### ISSUE THREAD

**Issue by norbertlaza** [PrestaShop/PrestaShop#33100]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the xml file the module includes the controller path of this pages and generates 404 error.

Controller paths in sitemap:

/index.php?controller=product ]]
/index.php?controller=category]]
/index.php?controller=cms]]

If we exclude from sitemap the product or the cms our sitemap will no longer have products.

The issue was described [here ](https://github.com/PrestaShop/PrestaShop/issues/16994)and the tk was closed for no reason!

### Expected behavior

Exclude controllers path from sitemap!

### Steps to reproduce

1. Go to gsitemap 
2. Unchek the product, cms, category
3. Manual generate sitemap or with cron
4. Check the sitemap and search for controller keyword.

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

gsitemap v4.3.0

**Comment by sallemiines** [comment]
Hello 

Following your steps with PS 1789 I didn't find the options : cms , category 

![image](https://github.com/PrestaShop/PrestaShop/assets/31663369/1a3c3a94-f805-423a-bcb1-8d52fe181747)

Did I miss smthng ? 
Please check and feedback ! 
Thank you

**Comment by norbertlaza** [comment]
/

> Hello
> 
> Following your steps with PS 1789 I didn't find the options : cms , category
> 
> ![image](https://user-images.githubusercontent.com/31663369/250932558-1a3c3a94-f805-423a-bcb1-8d52fe181747.png)
> 
> Did I miss smthng ? Please check and feedback ! Thank you

T

**Comment by norbertlaza** [comment]
<img width="1631" alt="Screenshot 2023-07-05 at 20 37 33" src="https://github.com/PrestaShop/PrestaShop/assets/53519809/1ae07092-a250-4794-8cc1-c3fdd092b7dc">
This is how it looks like....

**Comment by norbertlaza** [comment]
And this is the result:
<img width="721" alt="Screenshot 2023-07-05 at 20 41 34" src="https://github.com/PrestaShop/PrestaShop/assets/53519809/e3ca0297-6ecb-4387-ad09-1c16e9981885">

**Comment by norbertlaza** [comment]
So the problem was solved by deleting from seo and url the following pages: product, cms and category!

**Comment by aniszr** [comment]
Glad to hear :tada:
