### ISSUE TITLE
Regarding 33047 - Issue with missing id_employee in ps_order_payment table

### ISSUE THREAD

**Issue by Johnnyx2010** [PrestaShop/PrestaShop#33108]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I'm logging this here as it was previously logged at 33047. However its unclear was this ticket closed due the poster finding a solution via a manual entry in the db or was this logged as a fix todo at the upgrade level.
On a PS 1.7 there is no id_employee field. So when we upgrade to ps8 this field isn't present. This field needs to be part of the upgrade script as is important as third party modules can use this table.

### Expected behavior

id_employee to be added on ps_order_payment table via  an  upgrade script from 1.7 to PS 8

### Steps to reproduce

Upgrade existing PS 1.7 to PS 8 - check for the id_employee field its missing in ps_order_payment table. Clean install of PS8 has this field in the table

### PrestaShop version(s) where the bug happened

8

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

upgrade script

### Your company or customer's name goes here (if applicable).

NA

**Comment by florine2623** [comment]
Hello @Johnnyx2010 ,

Could you specify the exact version of PrestaShop before your upgrade ?
As well as send a screenshot of your error ?

The previous issue was closed because it couldn't be reproduced : https://github.com/PrestaShop/PrestaShop/issues/33047#issuecomment-1613143187

Waiting for your feedback^^

**Comment by Johnnyx2010** [comment]
its ps 1.7.8.9. 
upgrade it to straight to 8.1
Have a look at https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/install-dev/data/db_structure.sql - there's no mention of the field here
 https://github.com/PrestaShop/PrestaShop/blob/8.1.x/install-dev/data/db_structure.sql - line 1594 the field is added

**Comment by BenTen** [comment]
It's a recent update of the structure. It does not exist before 8.1

- https://github.com/PrestaShop/PrestaShop/pull/28820

@okom3pom said "Don't forget autoupgrade."
https://github.com/PrestaShop/PrestaShop/pull/28820#pullrequestreview-1016462970

> As well as send a screenshot of your error ?

It is an issue with autoupgrade who doesn't update this table.
https://github.com/PrestaShop/autoupgrade/blob/dev/upgrade/sql/8.1.0.sql

![Screenshot 2023-07-06 at 05-37-53 Add employee info on the Payments tab when payment is registered by Progi1984 · Pull Request #28820 · PrestaShop_PrestaShop](https://github.com/PrestaShop/PrestaShop/assets/915869/b78fca80-e1ec-40d5-a947-7234433f9e1c)

**Comment by aniszr** [comment]
Hello,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers: Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by kpodemski** [comment]
I can confirm this issue.

**Comment by kpodemski** [comment]
@MatShir @RosaBenouamer @Zoefinders @fabienvallon 

The important, easy solvable issue for the `autoupgrade` module.

**Comment by ocio87** [comment]
I add the following Bug that was closed that is associated with the same problem:

https://github.com/PrestaShop/PrestaShop/issues/33118

By having an initial state checking boxes where it is reported that it was paid, it throws an error 500.

In addition to adding a payment in orders orders. It fails to add the payment and the ps_order_payment table fails to insert rows.

![image](https://github.com/PrestaShop/PrestaShop/assets/12537826/6b550adf-9a1d-496e-bc33-5917e6b591df)

Please check if they are independent issues and leave the Bug that I reported as a duplicate.

**Comment by BenTen** [comment]
@ocio87 

You have to do that
https://github.com/PrestaShop/PrestaShop/issues/33047#issuecomment-1613173939

or ask someone or wait the update.

**Comment by FlyMeFR** [comment]
Thanks a lot, it worked !

**Comment by ocio87** [comment]
> @ocio87
> 
> You have to do that [#33047 (comment)](https://github.com/PrestaShop/PrestaShop/issues/33047#issuecomment-1613173939)
> 
> or ask someone or wait the update.

Thanks, if it worked with the change.

Does this change not affect future updates where prestashop includes this field?

**Comment by LuigiMdg** [comment]
Same problem here, ok that just add the column and it works, but the point of this column?
No value is recorded in it.

**Comment by ocio87** [comment]
when payment is added from orders, it shows the employee who made the deposit.

**Comment by Hlavtox** [comment]
Issue will be resolved after release of new version of autoupgrade module.
For existing upgrades, you can fix the issue permanently by running this SQL.

```sql
ALTER TABLE `ps_order_payment` ADD `id_employee` INT NULL AFTER `date_add`;
```
