### ISSUE TITLE
Order confirmation error in Front Office with ps_wirepayment module PS 8.1.0

### ISSUE THREAD

**Issue by ocio87** [PrestaShop/PrestaShop#33118]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

An update from version 1.7.8.7 to 8.1.0 is made and it is found that when selecting the payment method of the ps_wirepayment module, it throws error 500.

Debug is enabled and displays the following error when the customer completes the order.

[PrestaShopDatabaseException]
Unknown column 'id_employee' in 'field list'<br /><br /><pre>INSERT INTO `ps_order_payment` (`order_reference`, `id_currency`, `amount`, `payment_method`, `conversion_rate`, `transaction_id`, `card_number`, `card_brand`, `card_expiration`, `card_holder`, `date_add`, `id_employee`) VALUES ('XZROQTWKY', '2', '166920', 'Pagos por transferencia bancaria', '1', '', '', '', '', '', '2023-07-05 16:49:13', NULL)</pre>
at line 769 in file classes/db/Db.php

764.         if ($webservice_call && $errno) {
765.             $dbg = debug_backtrace();
766.             WebserviceRequest::getInstance()->setError(500, '[SQL Error] ' . $this->getMsgError() . '. From ' . (isset($dbg[3]['class']) ? $dbg[3]['class'] : '') . '->' . $dbg[3]['function'] . '() Query was : ' . $sql, 97);
767.         } elseif (_PS_DEBUG_SQL_ && $errno && !defined('PS_INSTALLATION_IN_PROGRESS')) {
768.             if ($sql) {
769.                 throw new PrestaShopDatabaseException($this->getMsgError() . '<br /><br /><pre>' . $sql . '</pre>');
770.             }
771. 
772.             throw new PrestaShopDatabaseException($this->getMsgError());
773.         }
774.     }
DbCore->displayError - [line 385 - classes/db/Db.php] - [1 Arguments]
DbCore->query - [line 740 - classes/db/Db.php] - [1 Arguments]
DbCore->q - [line 477 - classes/db/Db.php] - [2 Arguments]
DbCore->insert - [line 621 - classes/ObjectModel.php] - [3 Arguments]
ObjectModelCore->add - [line 72 - classes/order/OrderPayment.php] - [2 Arguments]
OrderPaymentCore->add - [line 1982 - classes/order/Order.php] - [1 Arguments]
OrderCore->addOrderPayment - [line 388 - classes/PaymentModule.php] - [3 Arguments]
PaymentModuleCore->validateOrder - [line 63 - modules/ps_wirepayment/controllers/front/validation.php] - [9 Arguments]
Ps_WirepaymentValidationModuleFrontController->postProcess - [line 308 - classes/controller/Controller.php]
ControllerCore->run - [line 510 - classes/Dispatcher.php]
DispatcherCore->dispatch - [line 28 - index.php]

![image](https://github.com/PrestaShop/PrestaShop/assets/12537826/ef3d6fc9-0e94-424e-81dc-771b179c3090)

https://drive.google.com/file/d/1puPtjDPZaGRnZKPwZuLa37JZukK35jp1/view?usp=sharing

Also found missing files after version upgrade in prestashop.

![image](https://github.com/PrestaShop/PrestaShop/assets/12537826/b06deb67-9c03-4982-89a4-3b812d735321)

### Steps to reproduce

Upgrade version 1.7.8.7 to 8.1.0 with autoupgrade module 4.16.0
mount order in front office with default theme and select payment method ps_wirepayment
Confirm the order

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

7.4 and 8.1

### If your bug is related to a module, specify its name and its version

ps_wirepayment

**Comment by ocio87** [comment]
Updating from version 1.7.8.7 to 8.0.4 the error does not occur.

![image](https://github.com/PrestaShop/PrestaShop/assets/12537826/f459cb43-894a-447c-98ec-ba74bc7c1355)

![image](https://github.com/PrestaShop/PrestaShop/assets/12537826/7f2406ac-1cf1-4384-bb5b-6d684e748fb3)

**Comment by djoelleuch** [comment]
Hello @ocio87  

I m not able to reproduce your issue with the provided information as you can see : 

![image](https://github.com/PrestaShop/PrestaShop/assets/115152460/41d888eb-7db4-4079-873f-aefce1584baa)
did i miss any thing ?

**Comment by ocio87** [comment]
As I reported, I migrated from 1.7.8.7 to prestashop 8.1.0.

I have done the migration several times and the result is the same.

When I migrate from 1.7.8.7 to prestashop 8.0.4, the order is created without problems.

**Comment by ocio87** [comment]
I just migrated from prestashop 8.0.4 to 8.1.0 and the order confirmation was also damaged.

![image](https://github.com/PrestaShop/PrestaShop/assets/12537826/2818abec-5b2c-49e7-b451-ef40ec4817d1)

There are no active override:

![image](https://github.com/PrestaShop/PrestaShop/assets/12537826/339abb9e-3223-43ff-830a-d5b0fd552c19)

**Comment by aniszr** [comment]
Hello ,@ocio87 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

See attached screenvideo : 

https://github.com/PrestaShop/PrestaShop/assets/92626242/f7bb338a-e031-4526-8788-00d517f555b3

We will close this issue.

Thank you!

**Comment by ocio87** [comment]
In what state was it in orders?

**Comment by ocio87** [comment]
In my case, it remains without status because I have removed the payment error status. It should appear with the status "Pending payment"

![image](https://github.com/PrestaShop/PrestaShop/assets/12537826/ad187cf5-b479-4464-8ff8-89bbcbfaa247)

**Comment by ocio87** [comment]
My store has been running since version 1.5. It has been updating smoothly up to version 1.7.8.7.

I did a clean install of version 1.7.8.7 and upgraded to version 8.1.0.

It does not throw an error when confirming the order, however I see that there is an error in the order detail which when trying to enter a payment, it throws an error:

![image](https://github.com/PrestaShop/PrestaShop/assets/12537826/838817ad-90e3-492a-888d-cd467b1d2e49)


![image](https://github.com/PrestaShop/PrestaShop/assets/12537826/3c9f7cb8-2121-4912-b4b0-f2c57a771286)


I perform payment entry tests in version 8.0.4 and enter the amount without problems.

![image](https://github.com/PrestaShop/PrestaShop/assets/12537826/79f7fd8a-f074-43b0-918f-41718a51021e)

According to the previous analysis, there is a bug in the payment entry in the order in version 8.1.0.

The ps_order_payment table is entered and does not show records.

In this table should be the records of the payments of the orders.

![image](https://github.com/PrestaShop/PrestaShop/assets/12537826/70275340-83d1-471c-8508-50b952df4fc3)

**Comment by ocio87** [comment]
The bug has already been found.

The Bug is due to state 10 where the following configuration is carried out, the request is mounted and it throws error 500:

![image](https://github.com/PrestaShop/PrestaShop/assets/12537826/8a910242-5f1b-4eeb-a978-937350b3ce3a)


https://drive.google.com/file/d/1q0qWUk4HY-DvQKpXXHVBodbL3kTQypN6/view?usp=sharing

**Comment by FlyMeFR** [comment]
I have exactly the same bug since my upgrade to 8.1.
I disabled the before last option "Consider the order as paid" (I guess in english (I'm French sorry)) on all the status I'm using and it solved part of the problem. At least I do not have the error when I change the status of the order, and mails are sent. 
I'm waiting my next order via PayPlug to see if it work by itself or not. 
And of course waiting for 8.1.1 update to correct this bug.

**Comment by ocio87** [comment]
Yes, we have to wait for the bug to be reviewed, I think it was too early for the testers to close this bug.

For me it is not viable to deactivate this box since in inventory it does not reserve the unit that they buy.

**Comment by FlyMeFR** [comment]
Oh I didn't know what was the impact to deactivate this option. Indeed, not viable. 
I hope it will be corrected asap.

**Comment by aniszr** [comment]
Hello @ocio87 

Could you please check this issue #27471 it seems related to yours!
Waiting for your feedback.

Thanks!

**Comment by ocio87** [comment]
The bug is more related to the following: https://github.com/PrestaShop/PrestaShop/issues/33108

I manually added the column and it fixed it.

Before:

![image](https://github.com/PrestaShop/PrestaShop/assets/12537826/81a4c733-4e58-4745-9c1e-05b10166847d)

After:

![image](https://github.com/PrestaShop/PrestaShop/assets/12537826/a1ed77b5-019b-4c4b-90d0-0f2ff7de6edf)

If they should correct the Update module to add that column in the ps_order_payment table.

Order:

![image](https://github.com/PrestaShop/PrestaShop/assets/12537826/57c0ea2d-55bc-4645-87e4-523b56276010)

Order Detail:

![image](https://github.com/PrestaShop/PrestaShop/assets/12537826/a870129b-7e3b-4d9e-a095-7bc37cbae86a)



![image](https://github.com/PrestaShop/PrestaShop/assets/12537826/3d70a6af-9c4e-47ef-9c07-1fd14bd7b387)

It also allowed adding payment manually.

**Comment by FlyMeFR** [comment]
Hi. I also just added the "id_employee" column into the ps_order_payment table and it seems to have solved the issue.
Thanks a lot !!!

**Comment by venditdevs** [comment]
Same problem here after updating from 1.7.8.8 to 8.1.0, id_employee table is not created.

It would be nice if the Prestashop developers would use a real environment on a server instead of doing things locally. Maybe then some thing would be reporducable. Again there are multiple persons with this problem and again it's not reproducable by the developers.

**Comment by Hlavtox** [comment]
Issue will be resolved after release of new version of autoupgrade module.
For existing upgrades, you can fix the issue permanently by running this SQL.

```sql
ALTER TABLE `ps_order_payment` ADD `id_employee` INT NULL AFTER `date_add`;
```
