### ISSUE TITLE
BO - Problem searching for products in product pack

### ISSUE THREAD

**Issue by gbr161** [PrestaShop/PrestaShop#33114]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello
We are experiencing weird issue when creating new product pack in BO. Issue is connected to product search input in "Pack" tab.

When trying to add product, search input makes "random" search. For example: product is named "xxx yyy zzz". 
Expected result:
- when typing xxx product appears
- when typing yyy product appears
- when typing zzz product appears

What we are getting:
- when typing xxx nothing shows
- when typing yyy it shows products somehow close to what we are searching

Most of products are not accesible via this search. Tried to search by product index/ean - still nothing.
Is there other index to rebuild when using this search bar?
Cleared cache, rebulded search index, nothing changed.

### Steps to reproduce

Try to add product pack, go to pack tab and start searching for product you want to add to pack.

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @gbr161 ,

I can't reproduce your issue with 8.1.0:

https://github.com/PrestaShop/PrestaShop/assets/16019289/be32cf8d-c36a-4741-93a8-eb708c70e095

**Comment by gbr161** [comment]
Thats a weird one.
Here are our products:
![image](https://github.com/PrestaShop/PrestaShop/assets/3307202/cbc9f78c-4363-4b8f-8de1-67377d6221c9)
As you can see there is "wkręt" part in name, so i should be able to search it and add to pack:
![image](https://github.com/PrestaShop/PrestaShop/assets/3307202/129fc9b8-4ae2-4ed8-82b7-cb5055785100)

It searches nothing...

**Comment by florine2623** [comment]
⚠️  Please change your admin folder name for security reasons

**Comment by florine2623** [comment]
I checked with a disabled product, the search can still be found.

I think the issue might be a configuration or a server issue. If you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by gbr161** [comment]
This is the error that server is returning when performing search with no products found:
`[2023-07-06 08:12:32] request.CRITICAL: Uncaught PHP Exception TypeError: "Argument 2 passed to PrestaShop\PrestaShop\Core\Product\Combination\NameBuilder\CombinationNameBuilder::buildFullName() must be of the type array, null given, called in ///public_html/src/Adapter/Product/Combination/QueryHandler/SearchCombinationsForAssociationHandler.php on line 146" at ///public_html/src/Core/Product/Combination/NameBuilder/CombinationNameBuilder.php line 92 {"exception":"[object] (TypeError(code: 0): Argument 2 passed to PrestaShop\\PrestaShop\\Core\\Product\\Combination\\NameBuilder\\CombinationNameBuilder::buildFullName() must be of the type array, null given, called in ///public_html/src/Adapter/Product/Combination/QueryHandler/SearchCombinationsForAssociationHandler.php on line 146 at ///public_html/src/Core/Product/Combination/NameBuilder/CombinationNameBuilder.php:92)"} []`

**Comment by PetryV** [comment]
hello!
Has anyone found a solution to the above problem?
thank you very much
