### ISSUE TITLE
Viewed products not showing on prestashop

### ISSUE THREAD

**Issue by calichelozano** [PrestaShop/PrestaShop#33184]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi, I have installed "Viewed products block" module, it's activated but it doesn't show on any of the product pages, what could be wrong?

Prestashop  ver 1.7.8.2
PHP: 7.4.33
URL: https://tienda.mariamarin.com
Theme: Ecolife 2.1.2
Using Elementor

Thanks!

### Expected behavior

I need this module to show the viewed products on thes ecommerce  while visiting product pages.

### Steps to reproduce

Go to: https://tienda.mariamarin.com/es/inicio/89-588-coconut-mct-oil.html#/191-cant-1_unidad
There's no "viewed products" showing on tne product page.

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

PS_Viewed products block ver 1.2.2

**Comment by florine2623** [comment]
Hello @calichelozano ,

Tested with PS `1.7.8.9`, `8.0.4`, `8.1.0` and `develop`.
I'm using Viewed products block module v1.2.4.

The viewed products block is well displayed.

https://github.com/PrestaShop/PrestaShop/assets/16019289/38e80277-1beb-4e99-bdbd-d61a86584f77

Please make sure the hooks are well hooked (displayFooterProduct, displayProductAdditionalInfo) for your module.

I'm closing your issue as it couldn't be reproduced.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
