### ISSUE TITLE
[EPIC] Independent twig component: Header toolbar

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#33182]
## Description

See #33101 for description in Step 2

This is the Header toolbar part.

This component should be quite autonomous.

This component is a bit special as it can be partially driven by the controllers by modifying the `layoutHeaderToolbarBtn` (in Symfony but a similar override also exists in legacy). And toolbar button are probably not the only elements that are customizable so we need to search into its related variables which one need to be customized (also by modules maybe).

~~Blocked by https://github.com/PrestaShop/PrestaShop/issues/33102~~

Since this one is quite complex we'll divide it into three parts:

- [x] #33566
- [x] #33603
- [x] #33604
- [x] #33701

**Comment by lartist** [comment]
Blocked by :

- [x] https://github.com/PrestaShop/PrestaShop/issues/33566

and other issues which should be created by @jolelievre
