### ISSUE TITLE
Independent twig component: Non responsive

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#33187]
## Description

See #33101 for description in Step 2

This is the Non responsive part.

This component should be quite autonomous.

Blocked by https://github.com/PrestaShop/PrestaShop/issues/33175

**Comment by lartist** [comment]
This issue is useless since the underlying feature is not used anymore. See https://github.com/PrestaShop/PrestaShop/pull/33324#issuecomment-1647513407
