### ISSUE TITLE
BO-Team: The time fixed to wait between two password changement has no effect

### ISSUE THREAD

**Issue by aniszr** [PrestaShop/PrestaShop#33209]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I fixed the time to wait between two password changes in Password regeneration field.
When editing the Employee password, I was able to change it as many times as I went without waiting the time configured already.

See attached screenvideo:

https://github.com/PrestaShop/PrestaShop/assets/92626242/897b2ae0-0eac-4d6e-95f0-3a1c987b2fa6

### Expected behavior

After changing the Employee password for the first time, I should be prevented from changing it again until the configured time elapses.

### Steps to reproduce

1. BO > Advanced Parameters > Team
2. Go to Employee options section 
3. Set the field Password regeneration to 10
4. Click Save button
5. Go to Employees section > click Edit button
6. Click Change password button
7. Set the fields:  Current password | New password | Confirm password
8. Click Save button : `Successful update` message is displayed
9. Repeat the steps 6,7 and 8 : always `Successful update` message is displayed

### PrestaShop version(s) where the bug happened

1.7.8.9 & 8.0.4 & 8.1.0

### PHP version(s) where the bug happened

7.4 & 8.1

**Comment by aniszr** [comment]
Hello, 

This issue is partially related to : [#29011](https://github.com/PrestaShop/PrestaShop/issues/29011)

Thanks!

**Comment by Hlavtox** [comment]
Hi @aniszr, that configuration value (`PS_PASSWD_TIME_BACK`) is related to password reset from the login screen, not changing the password from backoffice.

**Comment by aniszr** [comment]
Hello @Hlavtox 

Thanks for your feedback, I tried to change the password from the login screen as you mentioned and the reset password timer works well  :heavy_check_mark:  ALGTM

See attached screenshot:
![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/5109eeb3-6d9c-49c9-9c0f-21cb33310879)

I will close this issue.

Thanks!
