### ISSUE TITLE
Deleting !LoadedObject Customer deletes all CartRules that don't have customer restrictions

### ISSUE THREAD

**Issue by tswfi** [PrestaShop/PrestaShop#33202]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

This does not happen in regular use but happens when someone (me) does integration without checking everything all the time (which is way too easy)

Take this code:

```php
$Customer = new Customer(-1);
$Customer->delete();
```

delete does not complain anything BUT there is a side effect!

Customer::delete https://github.com/PrestaShop/PrestaShop/blob/65e20f37cfe40d4ad47480ada09c4fc45a4fa0f0/classes/Customer.php#L416

Does `CartRule::deleteByIdCustomer((int) $this->id);` but because the Customer was not really loaded (id -1 does not exists) the Customer object id is `null` but casting null to int makes it zero...

https://github.com/PrestaShop/PrestaShop/blob/65e20f37cfe40d4ad47480ada09c4fc45a4fa0f0/classes/CartRule.php#L614

`deleteByIdCustomer` does not check for 0 being a case and selects all CartRules where id_customer==0 and happily deletes them.

### Expected behavior

* Calling $Object->delete() when object is not valid loaded object should fail.
* `deleteByIdCustomer` should never be able to delete CartRules that do not have Customer condition set (e.g id_customer is 0)

### Steps to reproduce

1. Create CartRules with and withourt customer conditions
2. run the code above

=> all CartRules that didn't have customer conditions set are deleted

### PrestaShop version(s) where the bug happened

1.7.8.0

**Comment by tswfi** [comment]
The merchant in question is not in 8.0 yet, but the links to code are from develop branch where the same thing can still be seen.. So this probably affects versions from ancient history to develop.

**Comment by florine2623** [comment]
Hello,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!
