### ISSUE TITLE
Implement healthcheck for PR Dashboard

### ISSUE THREAD

**Issue by WahbiPS** [PrestaShop/PrestaShop#33218]
the HC for the kanbanbot application.
Follow up is made here from INFRA side : 
https://forge.prestashop.com/browse/INFRA-1341

**Comment by MatShir** [comment]
https://www.notion.so/New-Applications-Project-Checks-37c79a006c4942e0ab576397fd470f96

https://github.com/PrestaShopCorp/ADR-Architecture-Decision-Records/tree/main/0015-application-healthchecks
