### ISSUE TITLE
ps_checkout module: eligible payment methods won't update without full page reload

### ISSUE THREAD

**Issue by zelarg** [PrestaShop/PrestaShop#33210]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The issue is related to ps_checkout module and it's eligible payment methods returned on hook call.

`getEligiblePayment` method shall return all payment methods for currently set country. It does so correctly only at full-page reload, but when `paymentOptions` hook is called through ajax, user address's country is ignored. 

It looks like Paypal SDK is not reloaded when `paymentOptions` hook is called (it seems to be loaded at full page reload only).

_Important note_: this doesn't exhibit in Prestashop native checkout, where address is never changed without full page reload. But it's very much relevant for custom code or third party modules that modify user address and relies on `paymentOptions` hook to return valid payment options for that address - all through ajax, without full page reload.

### Expected behavior

`paymentOptions` hook to use actual user address to return eligible payment methods; or return piece of JS that would include Paypal SDK with correct parameters using actual user address

### Steps to reproduce

1. Use a code to dynamically fetch `paymentOptions` hook, either custom code, or use any third party checkout module
2. Change country through ajax (or in another tab), e.g. from Czech Republic to Netherlands, and then re-fetch `paymentOptions`
3. Result: same payment options are returned, ignoring user's newly selected address (country)
4. Expected behavior: Payment methods, that weren't eligible in Czech Republic, shall be visible, e.g. 'Ideal', 'Sofort'

### PrestaShop version(s) where the bug happened

1.7.8

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_checkout v7.3

**Comment by Hlavtox** [comment]
@PrestaShop/committers Could you point this to relevant people from SA?

**Comment by matks** [comment]
Hello @zelarg 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project, not products from PrestaShop company. For Checkout, there's an email address where you can explain your problem : support-checkout-download@prestashop.com

Thanks you

**Comment by zelarg** [comment]
Thanks for the contact email; I'm in touch with Prestashop support for about a week, they finally suggested I create Github issue, so I'm confused now it shall go back to them: 

![image](https://github.com/PrestaShop/PrestaShop/assets/9821742/eb0cb136-0c4e-49c1-bb0e-1cf5b79cbafc)

Anyway, I'll continue there, thanks!

**Comment by matks** [comment]
If the issue is inside the Core codebase this issue is valid and can remain there
If the issue is inside ps_checkout module this issue is not valid and must be handled by PrestaShop Checkout team

So the question is where the root of the problem is 😄

**Comment by zelarg** [comment]
I believe the issue is in ps_checkout module and how it includes (uses) Paypal API.
