### ISSUE TITLE
Module manager : Broken links for empty categories 

### ISSUE THREAD

**Issue by sowbiba** [PrestaShop/PrestaShop#33235]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The links added for empty categories in the modules manager are not displayed well

![image](https://github.com/PrestaShop/PrestaShop/assets/7426640/d7559574-31fa-423e-9b9a-2f934fd58f02)

### Expected behavior

Any html content added by hooks for empty categories must be displayed normally

### Steps to reproduce

1 - Have MBO installed
2 - Go to module manager
3 - Search for an empty category and see that the links are not displayed well

### PrestaShop version(s) where the bug happened

8.1.0

**Comment by hibatallahAouadni** [comment]
Hello @sowbiba 

I reproduce the issue with PS810 and ps_mbo v4.5.0 / v4.4.3

![image](https://github.com/PrestaShop/PrestaShop/assets/23308427/79c4be6b-e2b7-4ada-8482-f9a9ce9b5fdf)

Thanks for your PR :rocket:
