### ISSUE TITLE
An exception occurred while establishing a connection to figure out your pl

### ISSUE THREAD

**Issue by brokercl** [PrestaShop/PrestaShop#33239]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

7: 6
atform version.
8: 7
You can circumvent this by setting a 'server_version' configuration value
9: 8
10: 9
For further information have a look at:
11: 10
https://github.com/doctrine/DoctrineBundle/issues/673
12: 11
13: 12
14: 13
In AbstractMySQLDriver.php line 128:
15: 14
16: 15
An exception occurred in driver: SQLSTATE[HY000] [2026] SSL connection erro
17: 16
r: SSL_CTX_set_default_verify_paths failed
18: 17
19: 18
20: 19
In Exception.php line 18:
21: 20
22: 21
SQLSTATE[HY000] [2026] SSL connection error: SSL_CTX_set_default_verify_pat
23: 22
hs failed
24: 23
25: 24
26: 25
In PDOConnection.php line 40:
27: 26
28: 27
SQLSTATE[HY000] [2026] SSL connection error: SSL_CTX_set_default_verify_pat
29: 28
hs failed
30: 29
31: 30
32: 31
In Configuration.php line 331:
33: 32
34: 33
PrestaShop\PrestaShop\Adapter\Configuration::restrictUpdatesTo(): Argument
35: 34
#1 ($shop) must be of type Shop, null given, called in /home5/cci84196/publ
36: 35
ic_html/src/Core/Addon/Theme/ThemeManagerBuilder.php on line 61

### Steps to reproduce

+

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

7.4.29

**Comment by brokercl** [comment]
impossible install prestashop 8.1

**Comment by hibatallahAouadni** [comment]
Hello @brokercl 

Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must fill the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!

**Comment by musicpanda** [comment]
A duplicate of https://github.com/PrestaShop/PrestaShop/issues/33524

**Comment by brokercl** [comment]
I have to Download to
PrestaShop
1.7.8.9
And it works
