### ISSUE TITLE
Problem with large amount of attachmets

### ISSUE THREAD

**Issue by jumat-dt** [PrestaShop/PrestaShop#33247]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have a problem with editing products in the backoffice, due to a large number of attachments (10572).
It takes 20 seconds to load the product before editing.
Its same in 1.7.8.2 or 8.0.4 version.

### Steps to reproduce

Try working with a large number of attachments in the backoffice.

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.2

**Comment by hibatallahAouadni** [comment]
Hello @jumat-dt 

Please downgrade your PHP version to 8.1 cause PHP 8.2 is not compatible with PS8.0.4 (see our [system requirements](https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/#php-compatibility-chart)).
Closing this issue cause it's related to Performance, and we treat Performance issues as improvements.
So, could you please create your issue [here](https://github.com/PrestaShop/PrestaShop/discussions/new?category=ideas) :pray:  

Thanks for your understanding!

**Comment by jumat-dt** [comment]
I changed PHP to 8.1 and its same.
