### ISSUE TITLE
Unable to upgrade to 1.7.8 due to 500 error

### ISSUE THREAD

**Issue by OrangeSalute** [PrestaShop/PrestaShop#33254]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

![356173696_287589280377499_1391111152592417197_n](https://github.com/PrestaShop/PrestaShop/assets/139232523/49b7aaa8-2581-4970-8552-86be714315d4)
![354073134_994439431558403_3312202719674213966_n](https://github.com/PrestaShop/PrestaShop/assets/139232523/480703cf-5b11-4715-b038-67df1dbc6ded)

### Steps to reproduce

I am trying to upgrade Prestashop to 1.7.8 version.

Module 1 click upgrade brings 500 error with specific error messages attached

Please advise 

### PrestaShop version(s) where the bug happened

 1.7.7.3

### Your company or customer's name goes here (if applicable).

Paolo Donati

**Comment by aniszr** [comment]
Hello @OrangeSalute 

Could you please provide me more details about : which version you went exactly to upgrade to 1.7.8.9 or 1.7.8.0 and the version of your upgrade module

Thanks !

**Comment by OrangeSalute** [comment]
we want to upgrade to 1.7.8.9 and the version of 1 click module was v4.16.1.

We attach log file and settings adopted on Prestashop.

we urgently require an upgrade, please answer asap.

Thanks


[LOG3.txt](https://github.com/PrestaShop/PrestaShop/files/12184129/LOG3.txt)
[1-Click Upgrade 1-Click Upgrade • www.orangesalute.com__.pdf](https://github.com/PrestaShop/PrestaShop/files/12184130/1-Click.Upgrade.1-Click.Upgrade.www.orangesalute.com__.pdf)
[Prestazioni • www.orangesalute.com.pdf](https://github.com/PrestaShop/PrestaShop/files/12184131/Prestazioni.www.orangesalute.com.pdf)

**Comment by florine2623** [comment]
Hello @OrangeSalute ,

I upgraded from 1.7.7.3 to 1.7.8.9 like you.

I had no issue : 
<img width="870" alt="Screenshot 2023-08-02 at 09 52 57" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/4669e050-8193-45b9-9cf6-041285ae3c98">
<img width="1435" alt="Screenshot 2023-08-02 at 09 58 55" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/7d40ce87-5a8f-427b-aa0b-acbf0f247ccf">

https://github.com/PrestaShop/PrestaShop/assets/16019289/e3257596-4a47-4910-a63a-00ca35ee2d7c

Also, please change your admin folder name and your admin account for security reasons. This is a public platform.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by OrangeSalute** [comment]
Thanks for nothing for letting us know you had no issues, I am happy for you.

This answer is of no help.
