### ISSUE TITLE
Products in the same category addon missing Structures Offers rich meta tag

### ISSUE THREAD

**Issue by nafribs** [PrestaShop/PrestaShop#33256]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If you are using  Products in the same category  and run a test on  a product which is displaying Products in the same category  
 
via

https://search.google.com/test/rich-results

It shows 

![image](https://github.com/PrestaShop/PrestaShop/assets/12098918/332549fe-525c-4039-9c07-ca5e40c856e0)

![image](https://github.com/PrestaShop/PrestaShop/assets/12098918/5b21d9a7-39b5-45d1-b3ec-50871039d979)

The Offers tag is important , others  are not compulsory.

### Expected behavior

It should display the offers tag, it is already displaying the name, url and  image tag.

### Steps to reproduce

If you are using  Products in the same category  and run a test on  a product which is displaying Products in the same category  
 
via

https://search.google.com/test/rich-results

### PrestaShop version(s) where the bug happened

1.7.8.6

### If your bug is related to a module, specify its name and its version

Products in the same category 1.0.7

**Comment by aniszr** [comment]
Hello,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of ##22962.

To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by aniszr** [comment]
Duplicate of ##22962
