### ISSUE TITLE
Issue with invalid URLs inside products and categories

### ISSUE THREAD

**Issue by CrochetFeve0251** [PrestaShop/PrestaShop#33258]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

 Inside the method `getLanguageLink` the check for the `$params` is always done wrong as the key is present when a page is not found but the actual value is `false` on the key corresponding to the ID.
That makes the application raise a fatal later on when it search for the link:
`Invalid product vars at line 174 in file classes/Link.php`
`category vars at line 405 in file classes/Link.php

### Expected behavior

The page shouldn't raise a 500 error and return a 404.

### Steps to reproduce

1. The easiest way I found to test this is to install [`SEO Friendly URL Module`](https://github.com/softwaremistri/smseourl) which gonna remove the behavior on top of that method to redirect the user and makes it less complex to reproduce the issue.
2. Then update the URLs patterns to remove the ID (that remove the layer on top of the bug. However the bug is not linked directly to it)
3. Then you can enter any wrong URL in category or product and the problem gonna show up.

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.4

### Your company or customer's name goes here (if applicable).

MBS Design

**Comment by Hlavtox** [comment]
@CrochetFeve0251 Hi, please provide a proper example with a method call to show what is not working. Your module is messing with the `$_GET` parameter and putting nonsense there. https://github.com/softwaremistri/smseourl/blob/a5e26470b0de7beff3267ca45edc7df769f96c2b/smseourl.php#L260

**Everything is working normally on product page:**
![Snímek obrazovky 2023-07-15 145726](https://github.com/PrestaShop/PrestaShop/assets/6097524/bc920568-e650-4bef-bf31-0f28662ca684)

**Everything is working normally on category page:**
![Snímek obrazovky 2023-07-15 145734](https://github.com/PrestaShop/PrestaShop/assets/6097524/44659644-0c39-40bc-bd27-4419bbfb2708)

**Comment by guillemfedez** [comment]
Hi! Same problem here. When I type an invalid URL it shows a 500 error instead of 404. On debug mode it throws this, hope it helps
![error-500](https://github.com/PrestaShop/PrestaShop/assets/56740158/036776cf-866f-4e19-9439-9fad6c69bdac)

**Comment by Hlavtox** [comment]
@guillemfedez Please open a new issue about your problem, that is something different. :-)

**Comment by CrochetFeve0251** [comment]
@Hlavtox my issues looks the same as this issue: #33306 (which provides a way to reproduce it without the module I provided) and @guillemfedez got the same error I got. However afterward I went to debug it and found it was due to the ID being `false` instead of being a valid ID.

**Comment by djoelleuch** [comment]
Hello @CrochetFeve0251 

Duplicate of https://github.com/PrestaShop/PrestaShop/issues/33306

To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by guillemfedez** [comment]
Is what I thought @CrochetFeve0251 . It takes me crazy for a long time!

**Comment by guillemfedez** [comment]
Hi! Any news about this bug? It drives me crazy! Thank you!! :)

**Comment by pelopinxu** [comment]
For those who are worried about this: https://github.com/PrestaShop/PrestaShop/issues/33306#issuecomment-3571675374
