### ISSUE TITLE
Out of nowhere: Error 500

### ISSUE THREAD

**Issue by Freebase394** [PrestaShop/PrestaShop#33268]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Out of nowhere: Error 500

### Expected behavior

After uploading the new files, the site applies the new files and works perfectly! 

### Steps to reproduce

i inly have edites the /img/ files inside.

I change the IMG files to make the website look the way it needs to, and out of nowhere after a few hours later, the site gets corrupted with "error 500"

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

7.4.x

**Comment by Hlavtox** [comment]
Hi @Freebase394, you need to provide us with a detailed error.

> Reporting bugs with "error 500" or "white page" may not help us reproduce them. This is a universal error that hides what is underneath. Instead, enable debug mode in the Performance section of PrestaShop and try again. You should get a proper error message.

Open config/defines.inc.php and change `define('_PS_MODE_DEV_', false);` to `define('_PS_MODE_DEV_', true);`

**Comment by ghost** [comment]
Hi @Freebase394 
There is a **very special** case maybe that it was reproduced with you...
1- When you switch to debug mode can you access the backoffice?
2- Are you with OVH shared hosting?
3- Before the occurrence of this bug, have you tried testing another php version in your hosting space?

**Comment by florine2623** [comment]
Hello @Freebase394 ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
