### ISSUE TITLE
Order validation error : SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id_employee' in 'field list'; File:

### ISSUE THREAD

**Issue by darkf3d3** [PrestaShop/PrestaShop#33267]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After upgrading Prestashop 1.7.7.7 to 8.1, when placing order with specific payment methods, orders are saved without any status and no confirmtion email it's sent to the customer.
Other that that I received an email that notify me about a crash report into Prestashop log:
Order validation error : SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id_employee' in 'field list';
File: /var/www/vhosts/mywebsite.com/httpdocs/classes/db/DbPDO.php; Line: 151;
![image](https://github.com/PrestaShop/PrestaShop/assets/42684711/4f0bbc9d-aafe-47e9-81c3-a92898b92f33)

Actually I was able to reproduce this problem only when paying with Stripe module:
https://addons.prestashop.com/it/pagamento-carta-credito-wallet/17856-stripe-payment-pro-sca-ready.html
I contacted the developer and he said that it's not an issue related to his module but to prestashop itself.

### Expected behavior

Orders should be placed correctly without any issue and status set.

### Steps to reproduce

Upgrade Prestashop from 1.7.7.7 to PS8.1

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment]
Issue will be resolved after release of new version of autoupgrade module.
For existing upgrades, you can fix the issue permanently by running this SQL.

```sql
ALTER TABLE `ps_order_payment` ADD `id_employee` INT NULL AFTER `date_add`;
```

**Comment by hibatallahAouadni** [comment]
Duplicate of #33047
