### ISSUE TITLE
displayAdminProductsExtra layout problem in Prestashop 8.1

### ISSUE THREAD

**Issue by musaffarpatel** [PrestaShop/PrestaShop#33287]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Layout seems to be all messed up for modules which utilise the hook "displayAdminProductsExtra"

See attachment.
![screenshot](https://github.com/PrestaShop/PrestaShop/assets/5041037/f3f7b6da-704a-4160-84bb-4e5bee19e008)

This issue only started occurring in Prestashop 8.1 

### Expected behavior

The layout should match the layout in Previous versions of Prestashop.

### Steps to reproduce

Create a blank module which contains a logo.
If the module utilises the displayAdminProductsExtra hook, then the logo will be displayed too large as shown in the attachment.  The issue only affects Prestashop 8.1

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

8.1.4

**Comment by florine2623** [comment]
Hello @musaffarpatel ,

Your issue is the same as : https://github.com/PrestaShop/PrestaShop/issues/32928

I'm closing it to avoid clogging the backlog.
Thanks!

**Comment by musaffarpatel** [comment]
@florine2623 Many thanks
