### ISSUE TITLE
Cannot set specific price with currency filter

### ISSUE THREAD

**Issue by zelarg** [PrestaShop/PrestaShop#33285]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When setting specific price for a product, if (non default) currency is used in filter, it's not possible to enter new price in "target" currency.

The table shows like it's been set properly, see: 
![image](https://github.com/PrestaShop/PrestaShop/assets/9821742/a546a41f-4f85-4b79-8f8b-2e014300ecd9)

But in reality, price is set in default currency and calculated through exchange rate on Frontend: 
![image](https://github.com/PrestaShop/PrestaShop/assets/9821742/93b8586c-b968-4c4b-99b3-482b0f692527)

(!) important note - this had worked in PS 1.7.8.x, although the input prompt for specific prices said the currency being entered is base currency, it actually used it properly as target currency. In PS 8.0.3, it ain't working anymore this way.

### Expected behavior

Rationale behind this is to allow shop owner set up nicely rounded fixed price for different currencies.

Partial workaround to date is setting up exchange rate to 1:1 with base currency, however that messes up shipping cost.

### Steps to reproduce

1. Import localization pack of another country (e.g. base currency is EUR, import Czech Republic for CZK)
2. Edit product page in the BO
3. Set specific price to be a fixed amount for CZK
4. Result: On the Frontend, fixed price is NOT used.

### PrestaShop version(s) where the bug happened

8.0.3

### PHP version(s) where the bug happened

8.2

**Comment by AureRita** [comment]
Hi @zelarg 

Thank you for your report, I tried to reproduce your issue as you can see : 

[Untitled_ Jul 18, 2023 12_11 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/97d2973e-0406-4fc2-9047-8de7fc5bdc3b)

But currently, I can't reproduce it, 
Did I miss something ? 
Did you see that the price you put in the specific price is without taxes ? 

Waiting for your feedback

**Comment by zelarg** [comment]
@AureRita you did everything correct, I cannot see anything I'd do differently, compared to my test, you just have slightly higher PS version, so I went ahead and upgraded also to PS 8.0.4 and repeated test; still seeing wrong behavior, maybe check also my screencast if you can spot something there. Basically I set 240 CZK to be fixed price, but in reality, it's calculating exactly as if it was set in GBP: price_in_CZK * exchange_rate * vat =  240 * 27,654919 * 1,2 = 7964,617.
Btw, it wasn't just me - I did replicate this after my customer reported me same issue, so I guess there's indeed something wrong... I tested on basically clean PS 8.0.3 installation upgraded now to 8.0.4.

https://github.com/PrestaShop/PrestaShop/assets/9821742/0ce8d564-86d7-4850-bea1-2bd6a4bed2dd

**Comment by djoelleuch** [comment]
Hello @zelarg ,

Thank you for your report, I tried to reproduce your issue  on PS 8.0.3 et avec  PS  8.1.0 ,But currently, I can't reproduce it as you can see : 


[Untitled_ Jul 20, 2023 3_37 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/99ab8d1a-18df-49b8-8066-b7d98589b46b)

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you!

**Comment by zelarg** [comment]
@djoelleuch Thanks for your efforts, I have installed clean PS v8.1, no config changes whatsoever, and I was again able to replicate the problem. Digging further, I've discovered interesting behavior, you may want to check it out:

I've opened `classes/Product.php` and inspected how specific price is being converted, it's when this condition is true:

```php
       if (
            !$specific_price ||
            !(
                $specific_price['price'] >= 0 &&
                $specific_price['id_currency'] &&
                $id_currency !== $specific_price['id_currency']
            )
        )
```

Which means, when the condition `$id_currency !== $specific_price['id_currency']` is falsy, that means when `$id_currency === $specific_price['id_currency']` is truthy -> whole condition will be truthy (=we do currency conversion). Now think about that - when "session" id_currency is same (identical) to currency set in specific price **we do convert**. Actually when is the need to convert fixed price? I'd say never, as the specific_price is already in target currency.

But then how is possible it's been working when you tested this and conversion did not happen? That's due to identity check and un-intentional side-effect; I haven't dug further, but it seems that $specific_price['id_currency'] is sometimes string and sometimes int. Based on my tests / PHP config, on PHP 7.4 specific_price['id_currency'] is string (and I bet same for you), and thus the $id_currency never identity-equals to $specific_price['id_currency'] (unintentionally).

Here's what I did to test this - I've added debug code to `classes/Product.php` and run it with 2 PHP version:

```php
// convert only if the specific price is in the default currency (id_currency = 0)
        
        // -----------------------------
        echo "phpversion: " . phpversion() . "<br />";
        echo "type of \$id_currency: " . gettype($id_currency) . "<br />";
        echo "type of \$specific_price['id_currency'] " . gettype($specific_price['id_currency']) . "<hr />";
        // ------------------------------

        if (
            !$specific_price ||
            !(
                $specific_price['price'] >= 0 &&
                $specific_price['id_currency'] &&
                $id_currency !== $specific_price['id_currency']
            )
        ) {
            $price = Tools::convertPrice($price, $id_currency);

            if (isset($specific_price['price']) && $specific_price['price'] >= 0) {
                $specific_price['price'] = $price;
            }
        }
```

Results were:

1/ 
phpversion: 7.4.33
type of $id_currency: **integer**
type of $specific_price['id_currency'] **string**

2/
phpversion: 8.2.7
type of $id_currency: **integer**
type of $specific_price['id_currency'] **integer**

**Proposed solution:** 
The condition `$id_currency !== $specific_price['id_currency']` a/ is not type-safe, b/ shall not be there at all - as the conversion shall not depend on it.

**Comment by zelarg** [comment]
@AureRita @djoelleuch Could you please check this issue with regards to the new information provided? (see a comment above)

Thanks.

**Comment by MatShir** [comment]
@zelarg could you test your scenario on the develop branch ?
The PrestaShop 8.0 is [only compatible with PHP 8.1 max](https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/#php-compatibility-chart) but PrestaShop 9.0 will be compatible with PHP 8.2 (which his the current develop branch)

**Comment by zelarg** [comment]
@MatShir Unfortunately, no change even with PS 9.0: 
![image](https://github.com/PrestaShop/PrestaShop/assets/9821742/ced8a3b3-4bc0-459a-8484-b1adc36aff41)

As I expected, there's same source code for specific price calculation, so the result of debug message is: 
phpversion: 8.2.7
type of $id_currency: **integer**
type of $specific_price['id_currency'] **integer**

Which means, both compared values are of the same type (which is OK!), so we cannot rely on "fauly" behavior from older (maybe PHP?) versions, where we did compare integer to string, which was always false and thus the (IMHO redundant and incorrect) condition `$id_currency !== $specific_price['id_currency']` was always true; while now it could be false, and conversion is being made even when not necessary.

What's your PHP version please? Does it not behave this way on your end? Is it maybe PHP config thing? I did test on multiple installations and as I can tell, it behaves same everywhere.

**Comment by MatShir** [comment]
I didn't try ! But if the bug is still persistent on develop, then there is a bug.

**Comment by MatShir** [comment]
I'am adding 'Waiting for QA' for a double check

**Comment by florine2623** [comment]
Hello @zelarg & @MatShir ,

I have reproduced the issue using PPV2 on develop.

<img width="1208" alt="Screenshot 2023-08-03 at 11 33 03" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/c0bf581a-2067-4eab-829d-958e291f7503">

With currency Euro: ✅ 
<img width="1225" alt="Screenshot 2023-08-03 at 11 33 36" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/74c4d2f7-93ef-4ae0-8f0e-f41e3a1ff42e">

With currency Czech Koruna: :x:
<img width="1186" alt="Screenshot 2023-08-03 at 11 34 03" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/81a5b01b-c995-4ee9-b88d-1330024183f5">

There's a bug.

**Comment by mrkalchemy** [comment]
We have also experienced this issue and rolling back from PHP 8.1 to 8.0 fixed it for now.

**Comment by dingedi** [comment]
same problem, fixed with the proposal of @zelarg (remove the condition)

> Proposed solution:
The condition $id_currency !== $specific_price['id_currency'] a/ is not type-safe, b/ shall not be there at all - as the conversion shall not depend on it.

**Comment by MatShir** [comment]
Folks on which PS version are you ?

**Comment by dingedi** [comment]
- PrestaShop 8.1.1
- PHP: 8.1.12
