### ISSUE TITLE
Prestashop 8.1 Installation fails

### ISSUE THREAD

**Issue by musaffarpatel** [PrestaShop/PrestaShop#33286]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Installation of Prestashop 8.10 fails.

See attached:

![screenshot](https://github.com/PrestaShop/PrestaShop/assets/5041037/5a8fc030-ba66-445a-aa34-a67180cc15bd)

Below are the contents of my error log:

-----------------------

[17-Jul-2023 18:18:21 UTC] PHP Warning:  Constant _PS_DO_NOT_LOAD_CONFIGURATION_ already defined in C:\websites\prestashop\81\wwwpco\install\controllers\http\smarty_compile.php on line 26
[17-Jul-2023 18:18:21 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "_DB_PREFIX_" in C:\websites\prestashop\81\wwwpco\classes\Configuration.php:175
Stack trace:
#0 C:\websites\prestashop\81\wwwpco\classes\Configuration.php(229): ConfigurationCore::loadConfiguration()
#1 C:\websites\prestashop\81\wwwpco\config\smarty.config.inc.php(28): ConfigurationCore::get('PS_SMARTY_LOCAL')
#2 C:\websites\prestashop\81\wwwpco\install\controllers\http\smarty_compile.php(37): require_once('C:\\websites\\pre...')
#3 C:\websites\prestashop\81\wwwpco\install\classes\controllerHttp.php(190): require_once('C:\\websites\\pre...')
#4 C:\websites\prestashop\81\wwwpco\install\index.php(53): InstallControllerHttp::execute()
#5 {main}
  thrown in C:\websites\prestashop\81\wwwpco\classes\Configuration.php on line 175
[17-Jul-2023 18:18:21 UTC] PHP Warning:  Constant _PS_DO_NOT_LOAD_CONFIGURATION_ already defined in C:\websites\prestashop\81\wwwpco\install\controllers\http\smarty_compile.php on line 26
[17-Jul-2023 18:18:21 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "_DB_PREFIX_" in C:\websites\prestashop\81\wwwpco\classes\Configuration.php:175
Stack trace:
#0 C:\websites\prestashop\81\wwwpco\classes\Configuration.php(229): ConfigurationCore::loadConfiguration()
#1 C:\websites\prestashop\81\wwwpco\config\smarty.config.inc.php(28): ConfigurationCore::get('PS_SMARTY_LOCAL')
#2 C:\websites\prestashop\81\wwwpco\install\controllers\http\smarty_compile.php(37): require_once('C:\\websites\\pre...')
#3 C:\websites\prestashop\81\wwwpco\install\classes\controllerHttp.php(190): require_once('C:\\websites\\pre...')
#4 C:\websites\prestashop\81\wwwpco\install\index.php(53): InstallControllerHttp::execute()
#5 {main}
  thrown in C:\websites\prestashop\81\wwwpco\classes\Configuration.php on line 175
[17-Jul-2023 19:18:22 Europe/London] PHP Warning:  openssl_pkey_export(): Cannot get key from parameter 1 in C:\websites\prestashop\81\wwwpco\src\PrestaShopBundle\Install\Install.php on line 197
[17-Jul-2023 19:18:22 Europe/London] PHP Fatal error:  Uncaught TypeError: openssl_pkey_get_details(): Argument #1 ($key) must be of type OpenSSLAsymmetricKey, bool given in C:\websites\prestashop\81\wwwpco\src\PrestaShopBundle\Install\Install.php:198
Stack trace:
#0 C:\websites\prestashop\81\wwwpco\src\PrestaShopBundle\Install\Install.php(198): openssl_pkey_get_details(false)
#1 C:\websites\prestashop\81\wwwpco\install\controllers\http\process.php(150): PrestaShopBundle\Install\Install->generateSettingsFile('127.0.0.1', 'root', 'Hello', 'prestashop81_pc...', 'ps_', 'InnoDB')
#2 C:\websites\prestashop\81\wwwpco\install\controllers\http\process.php(90): InstallControllerHttpProcess->processGenerateSettingsFile()
#3 C:\websites\prestashop\81\wwwpco\install\classes\controllerHttp.php(277): InstallControllerHttpProcess->process()
#4 C:\websites\prestashop\81\wwwpco\install\index.php(53): InstallControllerHttp::execute()
#5 {main}
  thrown in C:\websites\prestashop\81\wwwpco\src\PrestaShopBundle\Install\Install.php on line 198

---------------------------

If we ignore the warnings in the error log, the fatal error part is as follows:

--------------------------
PHP Fatal error:  Uncaught TypeError: openssl_pkey_get_details(): Argument #1 ($key) must be of type OpenSSLAsymmetricKey, bool given in C:\websites\prestashop\81\wwwpco\src\PrestaShopBundle\Install\Install.php:198
Stack trace:
#0 C:\websites\prestashop\81\wwwpco\src\PrestaShopBundle\Install\Install.php(198): openssl_pkey_get_details(false)
#1 C:\websites\prestashop\81\wwwpco\install\controllers\http\process.php(150): PrestaShopBundle\Install\Install->generateSettingsFile('127.0.0.1', 'root', 'Hello', 'prestashop81_pc...', 'ps_', 'InnoDB')
#2 C:\websites\prestashop\81\wwwpco\install\controllers\http\process.php(90): InstallControllerHttpProcess->processGenerateSettingsFile()
#3 C:\websites\prestashop\81\wwwpco\install\classes\controllerHttp.php(277): InstallControllerHttpProcess->process()
#4 C:\websites\prestashop\81\wwwpco\install\index.php(53): InstallControllerHttp::execute()
#5 {main}
  thrown in C:\websites\prestashop\81\wwwpco\src\PrestaShopBundle\Install\Install.php on line 198
-------------------------------

Php Version 8.1.8

Previous versions of Prestashop install without issues.

The fun never ends, please advise.

### Steps to reproduce

Download the basic version of Prestashop of 8.1
Install on either a local or live server.

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

8.1.8

**Comment by Hlavtox** [comment]
@PrestaShop/committers `openssl_pkey_new` returns false

https://www.php.net/manual/en/function.openssl-pkey-new.php
> Note: You need to have a valid openssl.cnf installed for this function to operate correctly. See the notes under [the installation section](https://www.php.net/manual/en/openssl.installation.php) for more information.

**Comment by musaffarpatel** [comment]
@Hlavtox Thanks.  Is there anyway to proceed without openSSL for local installations - as it was prior to PS 8.1?

**Comment by musaffarpatel** [comment]
@Hlavtox I have opensssl already installed, below is the screenshot from my phpinfo to confirm.  Yet installation still produces same error:

![screenshot](https://github.com/PrestaShop/PrestaShop/assets/5041037/8c1a62d8-9d0e-400b-895e-32ed8e06043a)

**Comment by kpodemski** [comment]
Have you tried to use Laragon or Wamp or any webserver for Windows that covers all the basics, such as OpenSSL?

**Comment by musaffarpatel** [comment]
@kpodemski Yes, i'm using Laragon for Windows version 5.0

**Comment by musaffarpatel** [comment]
I notice the error log also has the following Fatal error:

PHP Fatal error:  Uncaught Error: Undefined constant "_DB_PREFIX_" in C:\websites\prestashop\81\wwwpco\classes\Configuration.php:175

**Comment by kpodemski** [comment]
Maybe it is something that we didn't anticipate that `openssl_pkey_new` works differently on Windows. Via https://www.php.net/manual/en/function.openssl-pkey-new.php#123410

**Comment by Hlavtox** [comment]
@musaffarpatel To install it, modify src/PrestashopBundle/Install/Install.php like this. The api keys are not needed, only for new api, which is not even finished.

```php
        $key = PhpEncryption::createNewRandomKey();
        /*$privateKey = openssl_pkey_new([
            'private_key_bits' => 2048,
            'private_key_type' => OPENSSL_KEYTYPE_RSA,
        ]);
        openssl_pkey_export($privateKey, $apiPrivateKey);
        $apiPublicKey = openssl_pkey_get_details($privateKey)['key'];*/

        $parameters = [
            'parameters' => [
                'database_host' => $database_host,
                'database_port' => $database_port,
                'database_user' => $database_user,
                'database_password' => $database_password,
                'database_name' => $database_name,
                'database_prefix' => $database_prefix,
                'database_engine' => $database_engine,
                'cookie_key' => $cookie_key,
                'cookie_iv' => $cookie_iv,
                'new_cookie_key' => $key,
                'api_public_key' => 'blablabla', // Temp
                'api_private_key' => 'blablabla', // Temp
                'ps_creation_date' => date('Y-m-d'),
                'secret' => $secret,
                'locale' => $this->language->getLanguage()->getLocale(),
            ],
        ];
```

**Comment by musaffarpatel** [comment]
@Hlavtox This allowed installation to go through, thank you for providing this fix.  I hope this doesn't come back to bite when the API is completed and necessary

**Comment by Hlavtox** [comment]
@musaffarpatel I think it's a problem in configuration though. Can you check this section in php.ini?

```
[openssl]
; The location of a Certificate Authority (CA) file on the local filesystem
; to use when verifying the identity of SSL/TLS peers. Most users should
; not specify a value for this directive as PHP will attempt to use the
; OS-managed cert stores in its absence. If specified, this value may still
; be overridden on a per-stream basis via the "cafile" SSL stream context
; option.
openssl.cafile = "\xampp\apache\bin\curl-ca-bundle.crt"
```

**Comment by musaffarpatel** [comment]
@Hlavtox This entry was empty in my php.ini file.  The comment for the setting suggests it should be empty for most users.  However, I did the following:

Download from (https://curl.haxx.se/ca/cacert.pem)
Change the name 'cacert.pem' to 'curl-ca-bundle.crt'
Copy it to: C:\Program Files (x86)\Common Files\SSL
In php.ini I change the setting to:
openssl.cafile="C:\Program Files (x86)\Common Files\SSL\curl-ca-bundle.crt"

I also tried to pointing to the original pem file downloaded
openssl.cafile="C:\Program Files (x86)\Common Files\SSL\cacert.pem"

Unfortunately none of the above helps on windows.

**Comment by ChillCode** [comment]
Hi

WAMP and similar packages usually does not touch the windows PATH variable but they install openssl, check the following i posted on the other issue.

> Note: Note to Win32 Users
> In order for this extension to work, there are DLL files that must be available to the Windows system PATH. For information on how to do this, see the FAQ entitled "[How do I add my PHP directory to the PATH on Windows](https://www.php.net/manual/en/faq.installation.php#faq.installation.addtopath)". Although copying DLL files from the PHP folder into the Windows system directory also works (because the system directory is by default in the system's PATH), this is not recommended. This extension requires the following files to be in the PATH: libeay32.dll, or, as of OpenSSL 1.1, libcrypto-*.dll
> 
> Additionally, if you are planning to use the key generation and certificate signing functions, you will need to install a valid openssl.cnf file on your system. We include a sample configuration file in our win32 binary distributions, in the extras/ssl directory.
> 
> PHP will search for the openssl.cnf using the following logic:
> 
> the OPENSSL_CONF environmental variable, if set, will be used as the path (including filename) of the configuration file.
> the SSLEAY_CONF environmental variable, if set, will be used as the path (including filename) of the configuration file.
> The file openssl.cnf will be assumed to be found in the default certificate area, as configured at the time that the openssl DLL was compiled. This is usually means that the default filename is C:\Program Files\Common Files\SSL\openssl.cnf (x64) or C:\Program Files (x86)\Common Files\SSL\openssl.cnf (x86), or, prior to PHP 7.4.0, C:\usr\local\ssl\openssl.cnf.
> In your installation, you need to decide whether to install the configuration file in the default path or whether to install it someplace else and use environmental variables (possibly on a per-virtual-host basis) to locate the configuration file. Note that it is possible to override the default path from the script using the options of the functions that require a configuration file.
> Caution
> Ensure that non-privileged users are not allowed to modify openssl.cnf.

[EDITED]

Forget to mention that PHP Info shows the default place but does not mean it exists, so also make sure `C:\Program Files\Common Files\SSL/openssl.conf` exists.

**Comment by ChillCode** [comment]
I just tested with Laragon, was curious, the upgrade failed but when I created `C:\Program Files\Common Files\SSL/openssl.conf` the keys were generated and upgrade finished.

So as stated on my previous comment, PHP Info only gives the default dir but you have to create it since Laragon dosen't.

You can just copy the file from `C:\laragon\bin\php\php-8.1.10-Win32-vs16-x64\extras\ssl\openssl.conf`

**Comment by musaffarpatel** [comment]
@ChillCode Thanks for this.  Your message made me realise I had placed opensssl.conf in the wrong folder (C:\Program Files (x86)) instead of C:\Program Files\.  Now the installation works.

**Comment by jherry** [comment]
For those using WAMP I created an environment variable OPENSSL_CONF set to the full path to the default openssl.cnf file, the one provided with PHP in <wamp dir>/bin/php/<php version>\extras\ssl\openssl.conf
It fixed the problem.

**Comment by web-burn** [comment]
> I just tested with Laragon, was curious, the upgrade failed but when I created `C:\Program Files\Common Files\SSL/openssl.conf` the keys were generated and upgrade finished.
> 
> So as stated on my previous comment, PHP Info only gives the default dir but you have to create it since Laragon dosen't.
> 
> You can just copy the file from `C:\laragon\bin\php\php-8.1.10-Win32-vs16-x64\extras\ssl\openssl.conf`

Many thanks @ChillCode! It help me
