### ISSUE TITLE
Prestashop 8.1.0 bug on entering specific prices

### ISSUE THREAD

**Issue by claudiodex61** [PrestaShop/PrestaShop#33283]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the case of a product with variants, specific prices cannot be entered as the drop-down menu only offers "all variants" instead of the single variants
![screenshot-prestashop-8 1 0-bug](https://github.com/PrestaShop/PrestaShop/assets/139777281/de77507d-3a07-479a-bbb8-0c8ef2f74505)

### Expected behavior

When I enter the specific prices I should be able to define the variant to assign the price to, as in all previous versions

### Steps to reproduce

Go to Price
Click on "add specific price"
Choose the attribute variant
The drop-down menu offers only "all attributes" even if the product has many attributes !

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.2

**Comment by AureRita** [comment]
HI @claudiodex61 ,

Thank you for your report but we are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #33261 .
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by AureRita** [comment]
Duplicate of #33261

**Comment by claudiodex61** [comment]
I'm sorry, I searched the forum but I didn't find this problem.. my fault. I sign up now to follow the problem and its definition.
Thank you
