### ISSUE TITLE
Fatal error after autoupgrade from 1.7.6.5 to 1.7.8.9 

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#33297]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I want to autoupgrade from 1.7.6.5 / 1.7.6.3 to 1.7.8.9 I get a fatal error after the upgrade because of the favicon as you can see : 

[Untitled_ Jul 18, 2023 5_17 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/0954a4a9-3f44-40a9-b345-1f69a58bbf15)

### Expected behavior

I want to autoupgrade my shop and don't get fatal error 

### Steps to reproduce

1. Install prestashop 1.7.6.5 
2. Install 1 clic upgrade 
3. Do the upgrade to 1769 
4. Connect to the BO :x: **Error** 

### PrestaShop version(s) where the bug happened

1.7.6.3 - 1.7.6.5

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

autoupgrade 4.16.0

**Comment by AureRita** [comment]
for information, the files` faviconbo.tpl `is deleted from the file `[yourshop]/modules/ps_faviconnotificationbo/views/templates/hook` during the installation

**Comment by Hlavtox** [comment]
@AureRita Could you please provide the log of the upgrade here? There were some module upgrade errors, that's important information. Thank you.

**Comment by aniszr** [comment]
Hello @AureRita 

I managed to reproduce this issue!

See attached scereen record:

https://github.com/PrestaShop/PrestaShop/assets/92626242/c8b9970f-8b17-4afa-9342-22119abf8203

Log message from **prod.log** File : 
`

> [2023-07-28 15:09:26] request.CRITICAL: Uncaught PHP Exception SmartyException: "Unable to load template 'file:/var/www/html/prestashop_1.7.6.5/modules/ps_faviconnotificationbo/views/templates/hook/faviconbo.tpl'" at /var/www/html/prestashop_1.7.6.5/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php line 195 {"exception":"[object] (SmartyException(code: 0): Unable to load template 'file:/var/www/html/prestashop_1.7.6.5/modules/ps_faviconnotificationbo/views/templates/hook/faviconbo.tpl' at /var/www/html/prestashop_1.7.6.5/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:195)"} []

`
Thanks!

**Comment by Hlavtox** [comment]
@AureRita  Please open `/admin/autoupgrade/tmp` and attach `log.txt` here.

**Comment by AureRita** [comment]
@Hlavtox 

there is a new log with this issue on it : [log.txt](https://github.com/PrestaShop/PrestaShop/files/12914854/log.txt)

**Comment by dantecarlo** [comment]
I fixed this by creating an empty file on /modules/ps_faviconnotificationbo/views/templates/hook named faviconbo.tpl

**Comment by Quetzacoalt91** [comment]
This issue has been fixed with https://github.com/PrestaShop/autoupgrade/pull/699, published with the autoupgrade module v5.0.2.
The old files are still deleted but now the new files are properly extracted from the core release.
