### ISSUE TITLE
The button install is not available after uninstall with force deletion

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#33295]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The button install is not available after uninstall with force deletion when the module ps_distribapi is active on develop branch and nightly

We can't test native module maj on branch under development and nightly. We'll have to find a solution for the next release.

### Expected behavior

The button install is available after uninstall with force deletion.
Find a solution to have the API working on the development branch not released yet.

### Steps to reproduce

Same problem than : #32497 but in  8.1.x

#### Functional test
1. Go to BackOffice
2. Go to Modules > Module Manager
3. Filter on a module "Best brands" for example
4. Uninstall it (with force deletion)
5. The row is removed (we should have a row with Install button)

#### Automated test
Run command `TEST_PATH="modules/ps_facetedsearch/01*/04*" npm run test:specific:fast-fail`

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

**Comment by AureRita** [comment]
Hi @Progi1984  ,

Thank you for your report, I reproduce the issue with PrestaShop version 8.1.x and not with the version 8.1.0 as you can see  : 

[Untitled_ Jul 18, 2023 5_33 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/1004059a-913a-448d-9641-5d2802d8dbf2)

Nice catch ! It's a regression ! I'll add it to the patch backlog.

Please be aware that some issues might take a very long time to be resolved. 

Thank you

**Comment by hibatallahAouadni** [comment]
Ping @Progi1984 & @AureRita is it a regression??

**Comment by Progi1984** [comment]
Yes, it worked fine in the previous week in the nightly.

**Comment by Hlavtox** [comment]
@Progi1984 This is expected behavior, the module **should be removed from the list** after uninstall&delete. Unless it's available from `ps_distributionapi`.

**Comment by Progi1984** [comment]
@Hlavtox This is the problem. The module exists and is present. But the API is not update.

**Comment by Hlavtox** [comment]
@Progi1984 Not sure what _But the API is not update._ means.

**Expected behavior:**
- If I uninstall & delete a module:
  - If the module is available from `ps_distributionapi`, it should stay in the list with "Install" button.
  - If the module is NOT available from `ps_distributionapi`, it should be deleted from the list.

**Comment by Progi1984** [comment]
Yes, but in the nightly, we should have always the "Install" button. And currently, it's not the case.

**Comment by Hlavtox** [comment]
@Progi1984 Do you have ps_distributionapi in the nightly?

**Comment by Progi1984** [comment]
Yes, it is in the composer.json ;)

**Comment by MatShir** [comment]
The pb is that on the nightly 8.1.x (next 8.1.2), the module ps_distributionapi can't find the updates since the release of 8.1.2 has not been released yet. So the nightly fails at new patch release under development

**Comment by kpodemski** [comment]
@MatShir we should have a fallback to the nearest minor version IMHO, there's a veeeery little chance that the module won't be compatible in some patch version :)

**Comment by MatShir** [comment]
Nearest patch release you mean ?

**Comment by kpodemski** [comment]
@MatShir 

or patch release if available, but the lowest should be 8.1.0, so:

- we plan to release 8.1.1, endpoint doesn't exist
- fallback to 8.1.0

- we plan to release 8.1.2, endpoint doesn't exist
- fallback to 8.1.1 :)

**Comment by MatShir** [comment]
and for the next develop then when it is a major ?

**Comment by kpodemski** [comment]
@MatShir makes sense, to put it simply: we shouldn't be in a situation where we cannot use distribution API because the endpoint doesn't exist

**Comment by tleon** [comment]
This will have to be QA by dev imo

**Comment by Hlavtox** [comment]
Maybe this issue is also caused by a mistake in the core introduced between 8.1.0 and 8.1.1.

I fixed it on 8.1.x here - https://github.com/PrestaShop/PrestaShop/pull/33581

**Comment by tleon** [comment]
The addition on the distribution api released today should have fixed this issue. This is ready to be tested.

**Comment by aniszr** [comment]
Hello @Progi1984 

I didn't manage to reproduce this issue in both versions : 8.1.x & Develop!

After forcing deletion of the module :

- The module still displayed on modules list with **Install** button :heavy_check_mark: 
- The re-installing process of the module went well :heavy_check_mark: 

See attached screenrecord :

- **8.1.x**

https://github.com/PrestaShop/PrestaShop/assets/92626242/e0421a9a-842e-45f5-b73a-a3a60c38e291

- **Develop**


https://github.com/PrestaShop/PrestaShop/assets/92626242/99d7be29-f6c8-4772-b252-3e5fc6f0a023

Thanks!

**Comment by Progi1984** [comment]
@aniszr This error will be back when the AppVersion will be modified to 8.1.2

Ping @MatShir
