### ISSUE TITLE
MultiStore : After defining a shop URL, it's not possible to delete a shop URL

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#33291]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After the  PR #33255, it's not anymore possible to delete a shop URL.

### Expected behavior

It's possible to delete a shop URL.

### Steps to reproduce

1. Enable Multistore
2. Create a shop
3. Set a virtual URL to the shop
4. After submitting the form, try to remove the shop URL
5. It's not possible

--- 
Execute the following UI test : `TEST_PATH="functional/BO/14*/10*/03*" npm run test:specific:fast-fail`

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

**Comment by AureRita** [comment]
Hi @Progi1984 

Thank you for your report, I try to reproduce your issue as you can see : 

[Untitled_ Jul 18, 2023 5_41 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/924d18d5-2ee7-4b06-ba8e-b0f63af67a39)

But currently I can't, did I miss something ? 

I actualized my 8.1.x just before the test, 

Waiting for your feedback

**Comment by Progi1984** [comment]
@AureRita You should stop at 0:31. You can note that you can't remove the Shop URL. In 8.0.x or before #33255, you can.

**Comment by Hlavtox** [comment]
@Progi1984 This is expected behavior no? You cannot remove a default URL for the store. That was the issue that was fixed.

**Comment by Progi1984** [comment]
I learn today that specs have been changed. And UI Tests have not been executed on this PR, so that broke the nightly.
