### ISSUE TITLE
icon and product names on RTL language back office 

### ISSUE THREAD

**Issue by hogo20** [PrestaShop/PrestaShop#33302]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

hello friends
I update from 8.0.4 to 8.1.0
in new version on farsi (RTL) language, in backend:
1- when enable EN for backend Lang, menu name and icon is okay, but product name not seen! 
2- when Enable Fa for admin language , menu icon not seen , but product name appear. 

### Steps to reproduce

when admin language is changed in backend (only on backend this problem appears) 

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

7.4.33

**Comment by florine2623** [comment]
Hello @hogo20 ,

I upgraded from 8.0.5 to 8.1.0.
<img width="1430" alt="Screenshot 2023-07-19 at 18 30 07" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/ddaa63c4-b714-4f85-b734-0967068ab9c0">

I have 2 languages Farsi and English. When I interchange both languages, menu icons and product names are always displayed.

<img width="1439" alt="Screenshot 2023-07-19 at 18 31 53" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/43696164-b596-4fb9-93c5-126fd73b60a8">

<img width="1436" alt="Screenshot 2023-07-19 at 18 32 18" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/2d0d9187-46ae-4bf7-848f-4647ea126ae8">


1- when enable EN for backend Lang, menu name and icon is okay, but product name not seen!
-> Make sure you have a product title for both languages.

I'm closing your issue as it cannot be reproduced.
Thanks!
