### ISSUE TITLE
ps_emailalerts error when no customer is found with specific email

### ISSUE THREAD

**Issue by stefanovita** [PrestaShop/PrestaShop#33304]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When a customer register to have a notification when a product is back in stock, there is condition that leds to error 500. 
The problem is in controller ps_emailsubscription/controllers/front:

```
if ($context->customer->isLogged()) {
            $id_customer = (int) $context->customer->id;
            $customer = new Customer($id_customer);
            $customer_email = (string) $customer->email;
        } elseif (Validate::isEmail((string) Tools::getValue('customer_email'))) {
            $customer_email = (string) Tools::getValue('customer_email');
            $customer = $context->customer->getByEmail($customer_email);
            $id_customer = (isset($customer->id) && ($customer->id != null)) ? (int) $customer->id : null;
        } else {
            exit(json_encode(
                [
                    'error' => true,
                    'message' => $this->trans('Your email address is invalid.', [], 'Modules.Emailalerts.Shop'),
                ]
            ));
        }
```

If the customer is NOT logged (elseif block) and no customer is found with the getByEmail function, $id_customer is set to null, and this leads to an error 500 when we instantiate MailAlert object:
```
$mail_alert = new MailAlert();
$mail_alert->id_customer = $id_customer;   ---> null
$mail_alert->customer_email = $customer_email;
```
since the definition for MailAlert is:

```
public static $definition = [
        'table' => 'mailalert_customer_oos',
        'primary' => 'id_customer',
        'fields' => [
            'id_customer' => ['type' => self::TYPE_INT, 'validate' => 'isUnsignedInt', 'required' => true],
            'customer_email' => ['type' => self::TYPE_STRING, 'validate' => 'isEmail', 'required' => true],
            'id_product' => ['type' => self::TYPE_INT, 'validate' => 'isUnsignedInt', 'required' => true],
            'id_product_attribute' => ['type' => self::TYPE_INT, 'validate' => 'isUnsignedInt', 'required' => true],
            'id_shop' => ['type' => self::TYPE_INT, 'validate' => 'isUnsignedInt', 'required' => true],
            'id_lang' => ['type' => self::TYPE_INT, 'validate' => 'isUnsignedInt', 'required' => true],
        ],
    ];
```

### Steps to reproduce

1. Activate product back in stock in module ps_emailalerts
2. Logout form Prestashop front
3. Search for a product out of stock
4. Insert an email that is not regiterede in customers table
5. Nothing happen and the ajax call goes to 500 with error about id_customer not set in object MailAlert 

### PrestaShop version(s) where the bug happened

Latest module version 2.4.1

**Comment by stefanovita** [comment]
Maybe the problem is this commit:

https://github.com/PrestaShop/ps_emailalerts/commit/e96355bd033f12dbdb593dce24a3a3be9c5343f9

**Comment by florine2623** [comment]
Hello @stefanovita ,

Your issue is a duplicate of : https://github.com/PrestaShop/PrestaShop/issues/32685

I'm closing it to avoid clogging the backlog.
Thanks!
