### ISSUE TITLE
Quantity format in dropdown filter

### ISSUE THREAD

**Issue by creasity** [PrestaShop/PrestaShop#33300]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

In filter dropdown the quantity is only showing a number (exemple: filter attribute 12 instead of filter attribute (12) ). I would like to show something like :
filter attribute = 12

You can check the issue in extension dropdown in this page : https://pokesumo.fr/25-display-pokemon-jcc
I searched in module files if I can change quantity format but I find only that code
{$filter.label}
{if $filter.magnitude and $show_quantities}
{$filter.magnitude}
{/if}
![Screenshot 2023-07-19 at 09-47-42 Précommande Cartes à collectionner et à jouer Pokemon One Piece Yu-Gi-Oh](https://github.com/PrestaShop/PrestaShop/assets/59027260/43527f69-0667-438e-885e-995f1c0be0ab)

### Expected behavior

I would like to show something like :
filter attribute = 12 
or filter attribute (12)

### Steps to reproduce

When you go in category pages and select "extension" filter

### PrestaShop version(s) where the bug happened

8.0.4

**Comment by florine2623** [comment]
Hello @creasity ,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
