### ISSUE TITLE
Error 500 instead 404 when URL is invalid

### ISSUE THREAD

**Issue by guillemfedez** [PrestaShop/PrestaShop#33307]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I type an invalid URL it shows a 500 error instead of 404. On debug mode it throws this, hope it helps
![error-500](https://github.com/PrestaShop/PrestaShop/assets/56740158/61d80d14-932a-4cbd-961a-20c033def83f)

### Expected behavior

Expecting a 404 instead of 500

### Steps to reproduce

Just write down an invalid link and it shows up

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

7.3.29

**Comment by ZoubaierHadden** [comment]
Try to test with another php version... 7.4 and above....

**Comment by florine2623** [comment]
Hello @guillemfedez ,

Is your issue similar to : https://github.com/PrestaShop/PrestaShop/issues/33306 ?

Waiting your feedback.
Thanks!

**Comment by guillemfedez** [comment]
it looks like! Thank you!

**Comment by florine2623** [comment]
Thanks @guillemfedez ,

I'll close your issue to avoid clogging the backlog ^^
You can keep track of it directly on https://github.com/PrestaShop/PrestaShop/issues/33306
