### ISSUE TITLE
Cannot reset category filter in the Products page (BO)

### ISSUE THREAD

**Issue by antoprudenzano** [PrestaShop/PrestaShop#33311]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In PS 8.1 with the new product page enabled it's not possible to reset the category filter in the backoffice.

If the category filtered is empty no reset option will be available, to restore the filter you have to manually remove the rows from the "ps_admin_filter" table.

https://github.com/PrestaShop/PrestaShop/assets/109733115/bfdce4d7-0046-4eb2-a2bc-cb979e46d6e5

### Expected behavior

Have a way to reset the filter.

### Steps to reproduce

1. Login in the Backoffice
2. Go to "Catalog->Products"
3. Filter the products by pressing "Filter by categories"
4. Choose an empty category from the list
5. Now the filter cannot be reset.

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.1.18

### Your company or customer's name goes here (if applicable).

Studio ITC

**Comment by florine2623** [comment]
Hello @antoprudenzano ,

I can't reproduce your issue on PS 8.1.x.

https://github.com/PrestaShop/PrestaShop/assets/16019289/7c9299cf-b7a3-4a5c-851a-35c82e6c37da

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

I'm closing your issue to avoir clogging the backlog.

Thank you

**Comment by antoprudenzano** [comment]
@florine2623 You are using 8.1.1 version, this is not a production release.

I encountered the issue with PS 8.0.4 and PS 8.1.0 versions, i am trying now if it is fixed with the latest development commit.

Please try with PS 8.1.0.

**Comment by antoprudenzano** [comment]
@florine2623 I can confirm that in the 8.1.1 version the problem does not exists.

**Comment by florine2623** [comment]
If it is fixed in 8.1.1, it won't be fixed again in 8.1.0.

@MatShir , could you confirm ?

**Comment by MatShir** [comment]
The 8.1.1 will be released soon. Stay tuned @antoprudenzano !
The 8.0.x versions are only maintained for security reasons. If you are already on 8.0 version, upgrading to 8.1 should be simple as patch upgrade.
