### ISSUE TITLE
Admin logon redirects to admin logon page with a 302 redirect

### ISSUE THREAD

**Issue by Issomane** [PrestaShop/PrestaShop#33317]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I am struggling to resolve an issue I am having with PS 1.7.8.4.

I have a **prod** environment where everything is working as expected. In order to prepare my planned upgrade in **Prod**, I wanted to set up a **staging environment.**

Here are the steps I followed:

1. Copied the files from Prod to the Staging subdomain
2. Exported the prod DB and imported into the staging DB
3. Changed different DB values (Store Url, Disabled Caching, Disabled the cookie check for the Admin, disabled URL rewrites)
4. Deleted the cache folders in the PS filesystem
5. Put a default .htaccess (like with the bare minimum)

The staging fronted works fine.
However, the staging admin login just keeps me in a loop. When entering the correct credentials, a 302 redirect gets me back to the same logon page. GIF attached for the example

Web server details:

- LiteSpeed
- DNS via Cloudflare (also tried bypassing CloudFlare, for both DNS and cache, without success)
- PHP version:7.4.33

Any help would be appreciated.

![253937858-e64fd57a-b0c7-4d7e-b638-73e2ea0c993a](https://github.com/PrestaShop/PrestaShop/assets/4606467/bbb59a61-d8f4-48b4-b0cc-5ae4225b66ed)

### Expected behavior

Get redirected to the Back Office with an HTTP 200 code

### Steps to reproduce

1. Go to the Web Admin
2. Logon with your admin credentials
3. You get redirected to the very same page

A list of prerequisites is in the description (db export > db import > file system import)

### PrestaShop version(s) where the bug happened

1.7.8.4

### PHP version(s) where the bug happened

7.4.33

**Comment by florine2623** [comment]
Hello @Issomane ,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by Issomane** [comment]
Hi @florine2623 , 

Thanks for the quick follow-up.  
Could you please explain why this does not qualify as a bug?  The software is not behaving like it should.  Isn't it a bug?

Edit: It looks like the Slack Channel does not exist anymore (or at least the page you are mentioning returns a 404)
Edit 2: I found the correct Slack channel, nvm (https://www.prestashop-project.org/slack/)

Thanks for enlightening me 😊
