### ISSUE TITLE
Uninterpreted HTML : import function

### ISSUE THREAD

**Issue by luger95** [PrestaShop/PrestaShop#33318]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

HTML code is not interpreted in the import modal

### Steps to reproduce

Using the import function

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

AdminImport

### Your company or customer's name goes here (if applicable).

LEXPROD SAS

**Comment by florine2623** [comment]
Hello @luger95 ,

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
