### ISSUE TITLE
After upgrade some parts of BO are in EN some parts in FR

### ISSUE THREAD

**Issue by Soonz** [PrestaShop/PrestaShop#33321]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hey,

I recently upgraded PrestaShop using the autoupgrade module, needless to say that I had a crazy amount of issue but I managed to most of them. But there's one that I can't fix, my back office is half english / half french.

The menu on the left is in English, the content itself is in French.

There's definitly something wrong during the update, how can I fix it ?

Thanks.

### Steps to reproduce

- Prestashop 1.7.6
- Installed languages - Czech (active, store default, employee default), Slovak (not active)
- Upgrade prestashop - left menu is in english. BUT, I can see translations for experimental features page. 🤔
- Clean cache - nothing, still english.
- Update language manually in backoffice - menu in czech.

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment]
Hi @Soonz, let's try few things.

- Can you send screenshot of your `BO > Localization > Languages` page?
- Did you try clearing cache? (I guess you did.)
- Did you try to update language in `BO > Translations > Add / Update language` and clear cache?
- Can you dump table ps_tab_lang and attach it here?

**Comment by Soonz** [comment]
`Did you try to update language in BO > Translations > Add / Update language and clear cache?`

This worked, thanks!

I think the upgrade documentation should be updated mentionning this could be an issue. There was also an SQL line that I had to execute to make it work, this wasn't mentionned in the doc but was a known issue. If I find it I'll link it.

Thanks again.

**Comment by Hlavtox** [comment]
@Soonz Perfect, but please, can you specify which was the exact version of Prestashop you upgraded from? There was only 1 language - French when you upgraded?

**Comment by Soonz** [comment]
There was two languages, French and English and I upgraded from 1.7.7.5 to 8.1.0 with the autoupgrader module.

If you don't mind, I don't want to open another ticket because I'm not sure if it comes from a specific theme or PrestaShop itself, I have another shop and this one ignores the manual product position inside each categories. It could be the theme but I don't get why a theme would interact with the product sorting.

Thanks again.

**Comment by Hlavtox** [comment]
@Soonz OK, thanks for the information, please:
- Both languages are enabled? (International > Localization > Languages)
- What is the default language? (International > Localization > Configuration > Default language)
- Your employee language is French?

**Comment by Soonz** [comment]
- Both languages are enabled
- Default language is French
- Employee language is French

**Comment by Hlavtox** [comment]
OK, I checked the code and it must have been some random error, but I found an improvement we can do https://github.com/PrestaShop/autoupgrade/pull/600.

However, your issue must have been some random error.
Ping @PrestaShop/qa-functional - if upgrades in other languages have been tested and work fine, you can close this issue.

**Comment by florine2623** [comment]
Hello @Soonz and @Hlavtox ,

I have tested an upgrade from 1.7 to 8.1.

With Spanish and English language.
After the upgrade, only my menu was in English, while the rest of the shop is in Spanish.
After updating the language, all is fine.

**Comment by Soonz** [comment]
> After updating the language, all is fine.

Yes, same for me but i'm happy to read that you managed to reproduce it, I didn't like the fact that it could be "random" :)

**Comment by Hlavtox** [comment]
Just reproduced the same issue.
- Prestashop 1.7.6
- Installed languages - Czech (active, store default, employee default), Slovak (not active)
- Upgrade prestashop - left menu is in english. BUT, I can see translations for experimental features page. 🤔
- Clean cache - nothing, still english.
- Update language manually in backoffice - menu in czech.

**Comment by venditdevs** [comment]
Also a duplicate of this closed issue: https://github.com/PrestaShop/PrestaShop/issues/33647

**Comment by kpodemski** [comment]
@venditdevs it was marked as invalid after you closed it, which basically means nothing

**Comment by M0rgan01** [comment]
Fix in https://github.com/PrestaShop/autoupgrade/pull/1066
