### ISSUE TITLE
Traceback on the exception pages needs to show full namespaces

### ISSUE THREAD

**Issue by mehov** [PrestaShop/PrestaShop#33320]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

No namespaces in the traceback:
![Imgur](https://i.imgur.com/1GSS49D.png)

One has to either know where these classes are, or spend time looking for them.

### Expected behavior

Full namespaces in the traceback for a better developer experience:

![CakePHP Exception page](https://i.imgur.com/xJNGTE4.png)

(Example screenshot from a [cakephp/cakephp](https://github.com/cakephp/cakephp) app)

### Steps to reproduce

Run into any exception

### PrestaShop version(s) where the bug happened

8.0.x-dev

### PHP version(s) where the bug happened

8.0

**Comment by Hlavtox** [comment]
Are you using the latest develop branch? I am getting this, with full paths.

![Snímek obrazovky 2023-07-20 131155](https://github.com/PrestaShop/PrestaShop/assets/6097524/f33c8fa9-9e36-45c3-8b40-2672a5d0fd0e)

**Comment by aniszr** [comment]
Hello ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
