### ISSUE TITLE
actionAttributeCombinationDelete is not working

### ISSUE THREAD

**Issue by fkomaralp** [PrestaShop/PrestaShop#33330]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi, i can't use actionAttributeCombinationDelete hook. I can't register this hook on pretashop v1.7.6.5.

### Steps to reproduce

1. Create a module
2. Register the actionAttributeCombinationDelete hook.

### PrestaShop version(s) where the bug happened

1.7.6.5

### PHP version(s) where the bug happened

7.1

**Comment by Hlavtox** [comment]
@fkomaralp Hi, you are doing something wrong, I suggest asking a specialist or in Prestashop Slack channel for help. :-)
