### ISSUE TITLE
Error after uninstalling and re-installing ps_emailsubscription module

### ISSUE THREAD

**Issue by laurentVeliscek** [PrestaShop/PrestaShop#33348]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi, 

after upgrading to Prestashop, the newsletter module doesn't work anymore.
I uninstalled and re-installed the module, but I get an error : 
```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'eshop.ps_emailsubscription' doesn't exist
at line 151 in file classes/db/DbPDO.php
```

I checked and the Table 'eshop.ps_emailsubscription' doesn't exist.
The Table disappeared when uninstallling the module, but re-installing it seems unable to recreate the table.

I join the error i get (.pdf and .RTF)

I googled to find some clue about this error, but found nothing....

Any idea ?

Thanks

[prestashop exception.pdf](https://github.com/PrestaShop/PrestaShop/files/12142489/prestashop.exception.pdf)
[prestashop.exception RTF.zip](https://github.com/PrestaShop/PrestaShop/files/12142585/prestashop.exception.RTF.zip)

### Steps to reproduce

uninstall module ps_emailsubscription
re-install ps_emailsubscription

### PrestaShop version(s) where the bug happened

1.7.8.9 ==> 8.1

### PHP version(s) where the bug happened

8.0.29

### If your bug is related to a module, specify its name and its version

ps_emailsubscription

**Comment by florine2623** [comment]
Hello @laurentVeliscek ,

Upgrade done with autoupgrade v4.16.1:
<img width="222" alt="Screenshot 2023-07-24 at 14 47 06" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/67252b7c-5515-48e3-a150-423464ed19f6">

Upgrade successful from 1.7.8.9 to 8.1.0:
<img width="1440" alt="Screenshot 2023-07-24 at 14 53 14" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/5064f15a-7712-4e23-97a7-b00128855d52">

Module email subscription still works :
<img width="992" alt="Screenshot 2023-07-24 at 14 46 35" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/4785ff68-79ae-4bfe-b794-caf67022ef06">
<img width="1440" alt="Screenshot 2023-07-24 at 14 54 58" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/e2d0d850-761a-440f-a41f-2532bde0a8bb">

I had no issue uninstalling and installing again the module ps_emailsubscription

https://github.com/PrestaShop/PrestaShop/assets/16019289/f9000645-68a9-4e7d-9b4a-4b24a08852dc

**Comment by laurentVeliscek** [comment]
Hi !

Thank you for your answer.

I didn't precise that I used the latest official 2.7.1 version of the module, not the dev one.

I noticed that uninstall the module "ps_emailsubscription" delete the ps_emailsubscription Table
And I can confirm that reinstalling the module on my shop does not recreate it (on my updated 8.1 Prestashop).

As a workaround, I exported this table from a backup I made before upgrading to 8.1
(when I was under 1.7.8.9 Prestashop)

Then, I imported it in my current shop database.

Then the error was fixed, the table is found, 

\o/

but then I got a new error: something like "missing field id_lang"
This field didn't exist in earlier version.

So I manually added the column "id_lang" (integer 10) to the table 
(as it is defined in ps_emailsubscription.php)

Then I updated each line's "id_lang" value to 1.

And bingo, it seems to work now.

Not tested everything yet, but I wanted to share how I fixed the problem.

Just to mention, the fact that the ps_emailsubscription Table is destroyed when you uninstall the module is not a  good idea, as user may then lose all the subscribers email adress (precious data...). 

May be could you add the option to NOT delete it when you uninstall the module...

Thanks again.

**Comment by laurentVeliscek** [comment]
BTW, the did not occur when you re-install the module, but when you try to Configure it.

**Comment by florine2623** [comment]
Hello @laurentVeliscek ,

Thanks for the details ^^

I'm closing your issue as you have fixed it!
