### ISSUE TITLE
Modules updates

### ISSUE THREAD

**Issue by marquand26** [PrestaShop/PrestaShop#33358]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I'm on Prestashop 8.0.4 and am trying to update the modules. Firstly none of them show as having updates except the theme specific ones. 

But I get an unspecified error on one of my sites when I try and upgrage the modules. Even manually uploading them causes an error. I then tried uninstalling it and then reinstalling it and it works. But obviously I'm worried about the settings. 

I checked the modules folder permissions on that site and it is 705 which is what it should be. 

Any ideas on what is going on? 

The issue of the modules not showing updates is on all 3 Prestashop 8 sites I am looking after. 

Thanks

### Expected behavior

I expected it to upgrade. 

### Steps to reproduce

1. Go to Modules page. Look for updates. None shows. This is on all three sites I administer. 
2. The module the them came with shows upgrades, but I'm unable to upgrade them as it throws an error. This is on one of the sites I administer. 

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.0

### If your bug is related to a module, specify its name and its version

all modules

**Comment by venditdevs** [comment]
It's (most likely) an annoying cache problem which cannot be solved by just clearing the cache, for the time being (till there's an solution) just delete the content in /var/cache/prod and/or dev. I recommend you to do this on server level, not on FTP level, it takes way to long then. After the clearing refresh the update tab and you'll see all of your modules which needs to be updated.

Every time when you want to update modules or check for updates, you'll have to repeat the cacheclearing. We encounter a similar, or the exact same problem here on all of our PS8 shops we maintain after updating. No problems on the remaining 65 1.7 shops.

We didn't opened a case here because we allready know this probably cannot be reproduced by the dev team cause they all work on local machines instead of a server environment like every Prestashop user.

**Comment by marquand26** [comment]
Thanks for getting  back to me. I tried that. It just doesn't do anything. I still can't update the modules. The only way I can do it is manually download it from the source (theme or Prestashop addons), uninstall the existing module, and then upload the latest version. 

If I try and upload it without uninstalling it first, it gives an error. Which funny enough is not happening on the other two sites with Prestashop 8.0,4 running. 

I'll try clearing the cache on the other two installs and post what happens here. When you mean server side, I take it, you log in to the host and use their webspace tool to clear it? **Update**: I have done this and the updates still don't show on any of the sites. Version 8.0.4. 

Please find the attached error log from the modules page. 
![Screenshot 2023-07-25 at 08-13-11 Symfony Profiler](https://github.com/PrestaShop/PrestaShop/assets/139572481/f04d6a33-f8a0-449f-a921-101e14080def)

**Comment by florine2623** [comment]
Hello @marquand26 ,

Do you have any problems updating PrestaShop native modules ?

**Comment by marquand26** [comment]
> Hello @marquand26 ,
> 
> Do you have any problems updating PrestaShop native modules ?

Yes. Firstly none of them show any updates available when I know there are when I look at the addons.

**Comment by marquand26** [comment]
Okay, I've just discovered something. You need to install the Distribution API client so the prestashop can check for updates to it's own modules. I take it it does so for Paypal, Stripe, etc? As soon as I installed it, the native prestashop modules showed updates. So that is resolved.

However, on one of the site which I have posted the above log, I am still unable to update any module. it's like something is preventing it. Should I update the site to 8.1 and see if that resolves the problem?

**Comment by joecoolio66** [comment]
You need to have the latest versions of:

ps_distributionapiclient v1.1
PrestaShop Marketplace in your Back Office v4.5

and... sometimes you have to reset them to pick up the latest module updates.  It's all pretty ramdom at times.

**Comment by joecoolio66** [comment]
Actually I just reset the ps_distributionapiclient and PrestaShop Marketplace in your Back Office v4.5.1 showed up for update LOL

**Comment by joecoolio66** [comment]
Oh and FYI... modules such as PayPal NEVER show up... I always just manually search the prestashop modules marketplace and download the latest version periodically.

**Comment by marquand26** [comment]
Oh, thank you so much. That worked. I can see the updates now. 

However, on the one site, where the updates do show, it just gives an error - Could not perform upgrade for module undefined. This is for all modules and it has happened after I updated from 1.7.9 to 8.0.4. I have no idea what the problem is. I've pasted the error log above.

**Comment by joecoolio66** [comment]
We had the same issue, but it was resolved when we upgraded the api distribution client to 1.1... so not sure there

**Comment by marquand26** [comment]
> We had the same issue, but it was resolved when we upgraded the api distribution client to 1.1... so not sure there

Tried that but still doesn't work. Cleared the cache too.

**Comment by marquand26** [comment]
Thanks for all your help everyone. I managed to resolve this. It was with an issue from a disabled old module. Not sure why it was referencing it anyway. 

Thank you. I'll mark this as solved.
