### ISSUE TITLE
BO - Bad displayed of WebP checkbox

### ISSUE THREAD

**Issue by MhiriFaten** [PrestaShop/PrestaShop#33357]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

[Untitled_ Jul 24, 2023 2_16 PM (1).webm](https://github.com/PrestaShop/PrestaShop/assets/111756615/a281158a-b436-4dba-9574-bae9a61f78fa)

### Expected behavior

the WebP option is checked.
![image](https://github.com/PrestaShop/PrestaShop/assets/111756615/bcdf618f-a784-494e-9738-fa6d61a75158)

### Steps to reproduce

1. Go to BO> Advanced Parameters> New & Experimental Feautures
2. Enable **Multiple image formats**
3. Go to Design> Image Settings> Images generation options
4. Check WebP Format
5. Go to **Dashboard** and goback to  Image **Settings page**
6. :warning: See Error : the WebP option is not checked.

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment]
@MhiriFaten It tells you on the video (0:12 - 0:14), that you don't have any base format selected.

![Snímek obrazovky 2023-07-24 152840](https://github.com/PrestaShop/PrestaShop/assets/6097524/7864c43c-14ff-4f96-8b6b-579b9c64c558)

**Comment by Hlavtox** [comment]
Closing to avoid cluttering the backlog, you have the error message on the video. :-)
