### ISSUE TITLE
1-Click Upgrade - Errors while upgrading from 1.7.8.9 to 8.1

### ISSUE THREAD

**Issue by alkorotkovas** [PrestaShop/PrestaShop#33367]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

N/A

### Expected behavior

Successful upgrade to Prestashop 8.1

### Steps to reproduce

Go to 1-Click Upgrade.
Select the latest 8.1 stable version.
Perform upgrade.

### PrestaShop version(s) where the bug happened

1.7.8.9 - > 8.1

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

1-Click Upgrade

**Comment by Hlavtox** [comment]
@alkorotkovas Hi, please send us the full content of the Errors block, so we know what happened. Thank you.

**Comment by alkorotkovas** [comment]
@Hlavtox  Hello, I can't access it anymore as the admin panel throws a 500 error.

**Comment by alkorotkovas** [comment]
I also did it on the freshly installed version of 1.7.8.9.
Here is the full log:
[INTERNAL] /home/u458701518/domains/drinkabledreams.com/public_html/modules/ps_mbo/upgrade/upgrade-2.0.3.php line 81 - Error: Call to undefined method ps_mbo::changeTabPosition() #0 /home/u458701518/domains/drinkabledreams.com/public_html/classes/module/Module.php(591): upgrade_module_2_0_3(Object(ps_mbo)) #1 /home/u458701518/domains/drinkabledreams.com/public_html/modules/autoupgrade/classes/UpgradeTools/ModuleAdapter.php(249): ModuleCore->runUpgradeModule() #2 /home/u458701518/domains/drinkabledreams.com/public_html/modules/autoupgrade/classes/UpgradeTools/ModuleAdapter.php(228): PrestaShop\Module\AutoUpgrade\UpgradeTools\ModuleAdapter->doUpgradeModule('ps_mbo') #3 /home/u458701518/domains/drinkabledreams.com/public_html/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeModules.php(65): PrestaShop\Module\AutoUpgrade\UpgradeTools\ModuleAdapter->upgradeModule(39574, 'ps_mbo') #4 /home/u458701518/domains/drinkabledreams.com/public_html/bzya28cnpjrc3nbt/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeModules->run() #5 {main}

**Comment by florine2623** [comment]
Hello @alkorotkovas ,

I have deleted your screenshots for security reasons.
Please change your admin folder name.

I did an upgrade from 1.7.8.9 to 8.1 with autoupgrade v4.16.1 without issue:
<img width="1430" alt="Screenshot 2023-07-26 at 11 51 29" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/c0694fcd-5f34-4e58-975b-fca7ab7b2795">

Have you tried to disable the module MBO ?

Waiting for your feedback

**Comment by kpodemski** [comment]
@alkorotkovas your issue probably comes from opcache, you can try to disable opcache before performing an upgrade

**Comment by alkorotkovas** [comment]
@florine2623 I tried to disable it, still the same issue.

**Comment by intraordinaire** [comment]
Hello @alkorotkovas ,

I'm working on the `ps_mbo` module.
Can you tell us the initial version of the module version (The one installed on the 1.7.8.x)  ?

Thanks

**Comment by sowbiba** [comment]
What I don't understand here is that
When you upgrade from PS 1.7.8 MBO<2.0.3 to PS 8.x MBO>4, you get from sources a MBO 4.x version, replace the module's files and execute upgrade script
There is no upgrade-2.0.3.php in MBO 4.x files

**Comment by alkorotkovas** [comment]
Hello @intraordinaire,

The version is v2.2.1. I'm using hostinger.o.uk. They have the automatic installer of PrestaShop, I can choose version 8.1 from the installer and it will work well, but I currently have a website in production with version 1.7.8.9 and I tried to upgrade it after I faced issues with the 1-Click Upgrade module, I installed a fresh version of Prestashop 1.7.8.9 to double check if I can do it on a different domain and tried to perform an upgrade. I always receive errors in the module. On a fresh version, it's different errors as you can see above.

**Comment by intraordinaire** [comment]
Hum ok.
I don't understand, the error
> modules/ps_mbo/upgrade/upgrade-2.0.3.php line 81 - Error: Call to undefined method ps_mbo::changeTabPosition()

Why the `upgrade-2.0.3.php` is called if you are already on a 2.2 version ? Upgrade files should be called once, when the upgrade is processed. It seems to not be the case.

Normally, there will be 2 cases :  
- You upgrade from a version before 2.0.3. The `upgrade-2.0.3.php` was never executed, but, it does not exist in the new version, so should never exist, and never launched.
- You upgrade from 2.0.3 or after, the `upgrade-2.0.3.php` was executed, and should not be launched ever again.

As mentioned by @kpodemski , is opcache enabled ? Have you tried without it ?

**Comment by alkorotkovas** [comment]
@intraordinaire Thank you for your suggestion, I will give it a try by disabling Opache.
To clarify, my module version is v2.2.1, not 2.2.2.

**Comment by florine2623** [comment]
Waiting for your feedback @alkorotkovas

**Comment by alkorotkovas** [comment]
@florine2623 updated on different hosting, looks like works.
The only issue is when I enable php 8, it throws an error in the admin panel: Attempt to modify property "warnings" on null [Error 0]

**Comment by sallemiines** [comment]
Hello @alkorotkovas 

Thanx for your feedback ! 
Glad to know that your probleme is resolved when you updated the host 
we will close the issue,  but feel free to create a new issue if you have any other problemes , we will be glad to investigate it. 

Thank you
