### ISSUE TITLE
[FO] - Can not access to Supplier page, it redirects to 404 page

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#33361]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I tried to access to the **Supplier** page, the page redirects you to 404 page.

[suppliers.webm](https://github.com/PrestaShop/PrestaShop/assets/23308427/83928f86-80a8-4620-a5de-fb4c8414dc75)

### Expected behavior

It should redirects to **Supplier** page with all products provided by the chosen supplier

### Steps to reproduce

1. FO>See all products
2. Click on any Supplier in the Supplier block
3. See error > 404 page is displayed

### PrestaShop version(s) where the bug happened

1.7.8.9 & 8.0.4 & 8.1.1

### PHP version(s) where the bug happened

7.4

**Comment by aniszr** [comment]
Hello @hibatallahAouadni 

I managed to reproduce this issue, the Supplier page is inaccessible !

See attached screenshot:
![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/2900a007-e49d-4801-b177-522f3a8f22f7)

Thanks!

**Comment by Hlavtox** [comment]
@hibatallahAouadni @aniszr `BO > Shop configuration > General > Show suppliers`, then you can close this issue. :-)

**Comment by hibatallahAouadni** [comment]
Thanks @Hlavtox 🙏

**Comment by Hlavtox** [comment]
However, it makes no sense to display related modules if the supplier/manufacturer listing is disabled, so made two PRs to hide it if these options are disabled. :-)
