### ISSUE TITLE
Click Upgrade v4.16.1 : maintenance mode not recognized

### ISSUE THREAD

**Issue by Repitol12** [PrestaShop/PrestaShop#33365]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,
Prestashop 1.7.7.1 with module Click Upgrade v4.16.1
maintenance mode is enabled and IP edited
The module doesn't accept launching the upgrade because the maintenance mode is not recognized as enabled
![Capture d’écran 2023-07-25 à 08 48 37](https://github.com/PrestaShop/PrestaShop/assets/140485502/3e013bbc-ba50-4c73-b752-e4b0988f9e49)
![Capture d’écran 2023-07-25 à 08 51 26](https://github.com/PrestaShop/PrestaShop/assets/140485502/89c17b76-9763-4daa-851c-e7eb1f464fd7)

### Expected behavior

PrestaShop requirements are not satisfied. They should be.

### Steps to reproduce

1. add module Click Upgrade v4.16.1
2. set the maintenance mode enabled and add your IP - save
3. verify the prestashop requirements

### PrestaShop version(s) where the bug happened

1.7.7.1

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

Click Upgrade v4.16.1 by Prestashop

**Comment by florine2623** [comment]
Hello @Repitol12 ,

I can't reproduce your issue on 1.7.7.1 with autoupgrade v4.16.1.
Here's what I have :
<img width="1440" alt="Screenshot 2023-07-25 at 11 00 39" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/e163d515-e9c4-4c92-973b-7ef3c219a966">

On my end, I don't put my shop in Maintenance mode.

**Comment by florine2623** [comment]
Ping @MatShir ,

Could you confirm the expected behavior for Maintenance mode during upgrades ?

**Comment by MatShir** [comment]
Look like a bug to me, maybe the module doesn't find the right IP address

**Comment by florine2623** [comment]
@PrestaShop/qa-functional 
Could someone check this please ?

**Comment by Repitol12** [comment]
well I don't have any other option but setting the shop on maintenance mode. The module doesn't let me the choice.
@florine2623 your screenshot is different from my version. Maintenance mode is not in the pre-upgrade checklist. :/

**Comment by sallemiines** [comment]
Hello @Repitol12 ,

I can't reproduce your issue on 1.7.7.1 with autoupgrade v4.16.1.

https://github.com/PrestaShop/PrestaShop/assets/31663369/c84074d4-8bed-4ad1-b042-1f2fbeefad4b

Please check and feedback ! 
Thank you

**Comment by MatShir** [comment]
Please contact your server provider to ask for help :/
We can't reproduce in our side.

**Comment by hibatallahAouadni** [comment]
Hello @Repitol12 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
