### ISSUE TITLE
Moduli nativi non si aggiornano

### ISSUE THREAD

**Issue by Vittoria65** [PrestaShop/PrestaShop#33368]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Buongiorno, ho un prestashop 1.7.8.9 PHP versione 7.4.33
Non si aggiornano i moduli nativi Checkout / Eventbus / Account / PS Social with Facebook & Instagram // Metriche / Marketing with Google. 
Vi invio 
![errore abbigliamento](https://github.com/PrestaShop/PrestaShop/assets/140499894/b44ba069-cb3b-45d9-abbc-56fdb5d22b30)
Screenshot

### Expected behavior

![errore abbigliamento](https://github.com/PrestaShop/PrestaShop/assets/140499894/0dac5a10-685b-4c46-b085-02633375428c)

### Steps to reproduce

1 Sito in manutenzione
2 moduli 
3 aggiornamento

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

Checkout / Eventbus / Account / PS Social with Facebook & Instagram // Metriche / Marketing with Google

### Your company or customer's name goes here (if applicable).

https://abbigliamentocanegatto.it/

**Comment by florine2623** [comment]
Hello,

Please send your request in English. English is the norm on GitHub.

Thank you

**Comment by Vittoria65** [comment]
Hello, I have a Prestashop 1.7.8.9 PHP version 7.4.33
The native modules Checkout / Eventbus / Account / PS Social with Facebook & Instagram // Metrics / Marketing with Google do not update.
website: https://abbigliamentocanegatto.it/
I send you screenshots
![errore abbigliamento](https://github.com/PrestaShop/PrestaShop/assets/140499894/8e28a8b1-0909-46ed-866c-ccb084c455da)

**Comment by Vittoria65** [comment]
Hello, I have a Prestashop 1.7.8.9 PHP version 7.4.33
The native modules Checkout / Eventbus / Account / PS Social with Facebook & Instagram // Metrics / Marketing with Google do not update.
website https://abbigliamentocanegatto.it/
![errore abbigliamento](https://github.com/PrestaShop/PrestaShop/assets/140499894/3fd99d10-8aeb-4784-ad42-a4e2af7f51b1)

I send you screenshots

**Comment by hibatallahAouadni** [comment]
Hello @Vittoria65 

Your issue is not a PrestaShop core bug.
If your modules are Official, please contact support team on Addons.

We will close this issue.

Thanks!
