### ISSUE TITLE
Mail alerts module does not save informations and email to admin don't work

### ISSUE THREAD

**Issue by lorenzog1983** [PrestaShop/PrestaShop#33376]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Good evening, hello, thank you

I have a problem: Prestashop 1.7.8.9 installation updated from 1.7.8.1 the mail alerts v2.4.1 module doesn't work anymore; runs on php 7.4

If I change the "send to" field in the "notifications to sellers--new order" section it gives me the error "Please enter one (or more) email address for the new order notification.", it doesn't save the email and the administrator does not receive order email.

### Expected behavior

I expect email is saved and not erased during save.

### Steps to reproduce

Enter mail alerts module to configure it, click "order confirmation" insert an email address and save

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

mail alerts v2.4.1

### Your company or customer's name goes here (if applicable).

Adiacent SRL

**Comment by florine2623** [comment]
Hello @lorenzog1983 ,

Is your issue similar to https://github.com/PrestaShop/PrestaShop/issues/33389 ?

**Comment by lorenzog1983** [comment]
> Hello @lorenzog1983 ,
> 
> Is your issue similar to #33389 ?

Hi, thank you for answer.
Yes, similar, but different versions of PS and php, while the module mail alerts is the same version.
I uninstalled it and reinstalled too but the problem persists.
Best regards

**Comment by kpodemski** [comment]
As you can now type multiple emails in the configuration field, you have to type the email address and click the "Enter" key first.

Please try that first.

**Comment by florine2623** [comment]
@lorenzog1983 ,

Could you refer to https://github.com/PrestaShop/PrestaShop/issues/33389 directly ?
It has a little more details than this issue ^^

I'm closing this issue on order to avoid clogging the backlog.
