### ISSUE TITLE
Issue with same file overrode by two modules

### ISSUE THREAD

**Issue by NordineA** [PrestaShop/PrestaShop#33378]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,

Here's my problem : I've created two module that override the Product.php like so

mymoduleone/override/classes/Product.php
```
class Product extends ProductCore {

    public function mymoduleone() {
        echo "my module one" . PHP_EOL;
    }
}
```

mymoduletwo/override/classes/Product.php
```
class Product extends ProductCore {

    public function mymoduletwo() {
        echo "my module two" . PHP_EOL;
    }
}
```

When I install and enable the two modules, here's what the override/classes/Product.php file looks like : 

override/classes/Product.php
```
class Product extends ProductCore {
    /*
    * module: mymoduleone
    * date: 2023-07-25 17:29:42
    * version: 1.0.0
    */
    public function mymoduleone() {
        echo "my module one" . PHP_EOL;
    }
        echo "my module two" . PHP_EOL;
    }
}
```

The function Product::mymoduletwo() is not generated as expected.

[mymoduletwo.zip](https://github.com/PrestaShop/PrestaShop/files/12163196/mymoduletwo.zip)
[mymoduleone.zip](https://github.com/PrestaShop/PrestaShop/files/12163198/mymoduleone.zip)

### Expected behavior

override/classes/Product.php
```
class Product extends ProductCore {
    /*
    * module: mymoduleone
    * date: 2023-07-25 17:29:42
    * version: 1.0.0
    */
    public function mymoduleone() {
        echo "my module one" . PHP_EOL;
    }
    /*
     * module: mymoduletwo
     * date: XXXX-XX-XX XX:XX:XX
     * version: 1.0.0
     */
    public function mymoduletwo() {
        echo "my module two" . PHP_EOL;
    }
}
```

### Steps to reproduce

1. Unzip mymoduleone.zip and mymoduletwo.zip archives in modules/ directory
2. Go to Modules -> Marketplace
3. Install MyModuleOne module
4. Install MyModuleTwo module
5. Enable MyModuleTwo module
6. Check override/classes/Product.php file from shop

### PrestaShop version(s) where the bug happened

1.7.5.1

### PHP version(s) where the bug happened

7.2

### Your company or customer's name goes here (if applicable).

NordineA

**Comment by Hlavtox** [comment]
Hi, that's normal. Two modules can't override the same file. See https://devdocs.prestashop-project.org/8/modules/concepts/overrides/

> Overrides in PrestaShop are exclusive. This means that if your module overrides one of PrestaShop’s behaviors, another module will not be able to use that behavior properly, or override it in an predictable way.
> 
> Therefore, overrides should only be used for your own local modules, when you have a specific need that cannot be applied with it.
> 
> It is not recommended to use an override in a module that you intend to distribute (for instance through the PrestaShop Addons marketplace), and they are forbidden in partner modules.
