### ISSUE TITLE
Popups blocked in product page v2

### ISSUE THREAD

**Issue by Simchev38** [PrestaShop/PrestaShop#33377]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello 

I have an issue with the new product page. I had this problem with 8.0 and still have it in 8.1

When page product v2 is enabled, the "popups" to add a specific price, or to select the shops where the product is enabled (in 8.1) won't work.

The popup itself opens, but the request to fill its content is blocked, and the popup display a message "request blocked" instead of its content.

If I copy the  URL requested when the popup is opened,  and open it in a new tab, the content is displayed correctly.

I checked the browser dev console, and I have the following errors that seem relevant : 

`Refused to frame 'https://MYURL/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".`

product_edit.bundle.js?8.1.0:343 
```
Uncaught DOMException: Blocked a frame with origin "https://MYURL" from accessing a cross-origin frame.
    at Lt.getForm (https://MYURL/admin26s5d65/themes/new-theme/public/product_edit.bundle.js?8.1.0:343:814)
    at Lt.onIframeLoaded (https://MYURL/admin26s5d65/themes/new-theme/public/product_edit.bundle.js?8.1.0:343:522)
    at Object.onLoaded (https://MYURL/admin26s5d65/themes/new-theme/public/product_edit.bundle.js?8.1.0:343:217)
    at HTMLIFrameElement.<anonymous> (https://MYURL/admin26s5d65/themes/new-theme/public/product_edit.bundle.js?8.1.0:318:2006)
```

Is that a bug ? is it specific to my server  ? any idea on how to solve it please ? 

Thanks 

### Steps to reproduce

Enable product page v2
go to a product page 
try to open a popup (add specific price, select shops)

### PrestaShop version(s) where the bug happened

8.0 8.1

### PHP version(s) where the bug happened

8.1.21

**Comment by florine2623** [comment]
Hello @Simchev38 ,

I can't reproduce your issue.

https://github.com/PrestaShop/PrestaShop/assets/16019289/e5126091-d7d9-4177-818d-383d3e67de5c


Can you send a screen record ?

**Comment by Simchev38** [comment]
Hello 

No problem you'll find the screen capture here :

**Comment by florine2623** [comment]
It seems like it's a server problem.

Have you followed the [system requirements](https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/) ?

**Comment by Simchev38** [comment]
The requirements were fine

I found the cause of the issue, it seems the official UPS module adds a "frame-ancestor:none" http header, If I disable the module it works properly

Thanks

**Comment by alexandrebru83** [comment]
Same issue, Thanks @Simchev38 !

**Comment by Simchev38** [comment]
Actually you can disable this feature in the last part of UPS module config, something like "Security enhancements / Content securiy policy header"

That way you can still use the module
