### ISSUE TITLE
Multiple PHP Fatal error in error logs in server

### ISSUE THREAD

**Issue by nelero** [PrestaShop/PrestaShop#33382]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

hi,
checking my error logs in server, i found this multiple times.

```
PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PrestaShop\\PrestaShop\\Core\\Localization\\CLDR\\ComputingPrecision::getPrecision() must be of the type int, null given, called in /classes/Context.php on line 498 and defined in /src/Core/Localization/CLDR/ComputingPrecision.php:41, referer https://www.google.com/
Stack trace:, referer https://www.google.com/
#0 /classes/Context.php(498): PrestaShop\\PrestaShop\\Core\\Localization\\CLDR\\ComputingPrecision->getPrecision(NULL), referer https://www.google.com/
#1 /classes/Product.php(5685): ContextCore->getComputingPrecision(), referer https://www.google.com/
#2 /classes/Cart.php(833): ProductCore::getProductProperties(2, Array), referer https://www.google.com/
#3 ...ssage: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PrestaShop\\PrestaShop\\Core\\Localization\\CLDR\\ComputingPrecision::getPrecision() must be of the type int, null given, called in /classes/Context.php on line 498 and defined in /src/Core/Localization/CLDR/ComputingPrecision.php:41, referer https://www.google.com/
```

After checking the stacktrace,
Line 833 of Cart.php is 
`Product::getProductProperties((int) $this->id_lang, $row);`
Line 5685 of Product is 
`Context::getContext()->getComputingPrecision()
`
but getComputingPrecision is calling getPrecision from ComputingPrecision class with a currency
```
public function getComputingPrecision()
    {
        if ($this->priceComputingPrecision === null) {
            $computingPrecision = new ComputingPrecision();
            $this->priceComputingPrecision = $computingPrecision->getPrecision($this->currency->precision);
        }

        return $this->priceComputingPrecision;
    }
```

Why currency->precision could be empty and not set to default ?

Some issues are talking about other parameters of context or orders, but it doesn't seem relevant, even if the end is the $displayPrecision parameter not sent to the function getPrecision.

### Expected behavior

no PHP fatal error. Pass a parameter to the function or, transform it optional to get a default precision.

### Steps to reproduce

For example, just call a $cart->getProducts() in a hook for actionCartSave
Registered like this in a null module 
`$this->registerHook('actionCartSave');`

```
public function hookActionCartSave($params){
        $cart = $this->context->cart;
        foreach ($cart->getProducts() as $row) {
                $id_product = (int)$row['id_product'];
        }
}

```

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.4.33

**Comment by florine2623** [comment]
Hello @nelero ,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone answer this issue, it's too technical!

Thanks in advance!

**Comment by hibatallahAouadni** [comment]
Friendly reminder @PrestaShop/committers :pray:

**Comment by hibatallahAouadni** [comment]
Hello @nelero 

Do you still encounter the issue with 8.1.x? Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @nelero 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
