### ISSUE TITLE
An exception is displayed when we create a new store

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#33385]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In 'Shop parameters > contact > stores' page, when we create a new store an exception is displayed

-> Mode debug on
![Capture d’écran de 2023-07-26 10-04-24](https://github.com/PrestaShop/PrestaShop/assets/24647495/eeebadbf-915a-4d94-93a4-6fa7aad80be9)

-> Mode debug off
![Capture d’écran de 2023-07-26 10-29-40](https://github.com/PrestaShop/PrestaShop/assets/24647495/07d038e6-656a-4e6c-bb4d-ea8302889d68)

### Expected behavior

A validation message should be displayed when we create a new store

### Steps to reproduce

1- Go to 'Shop parameters > contact > stores' page
2- Fill all the inputs
3- Save and see the error

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.1

**Comment by M0rgan01** [comment]
ce5746d6c2965592eca79b83934acc71389cc0e8 

```
  prestashop.core.admin.feature_flag.repository:
    alias: PrestaShopBundle\Entity\Repository\FeatureFlagRepository
    deprecated: ~
```
the alias had to be removed, without checking its use I think
