### ISSUE TITLE
impossible de faire la mise à jour 8.04 vers 8.1

### ISSUE THREAD

**Issue by ECC64** [PrestaShop/PrestaShop#33390]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Bonjour,

Installation neuve 8.0.4 installée sur O2Switch PHP8.1, MySQL 10.6.14 MariaDB.
Aucun module externe installé, thème d'origine. Uniquement les produits de démo.
Version du module 1click : 4.16.1
Tous les voyants au vert.
Choix : mise à jour majeure pour avoir accès à la V8.1
Toutes les options décochées sauf : mise à jour du thème par défaut.
Je vous joins l'erreur en copie d'écran
![363319787_6935942923085585_8847954977700699894_n](https://github.com/PrestaShop/PrestaShop/assets/61431435/ccf48194-5d83-4626-9d36-9a8941526d23)

Aprsè 2 essais infructueux, j'ai restauré la sauvegarde de la veille en attendant que ce soit résolu

### Expected behavior

Passer en version 8.1

### Steps to reproduce

Site en maintenance
Mise à jour du module 1click Upgrade
Choisir le canal Version majeure
Cliquer sur Upgrade Now pour la 8.1
Puis . . . . plantage
![363319787_6935942923085585_8847954977700699894_n](https://github.com/PrestaShop/PrestaShop/assets/61431435/328a6a84-610e-4e7e-99cf-c2779b8e6742)

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

Le Havanitos

**Comment by florine2623** [comment]
Hello @ECC64 ,

This is not the core project.
This is Edition. You can contact the Edition team directly.

I'm closing the issue to avoid backlog.
Thanks!

**Comment by Hlavtox** [comment]
@kpodemski @florine2623 @MatShir Reopening, prestashop edition has nothing to do with this.

@ECC64 Please translate your bug report into english - `Use English, reports in all other languages will be closed.`. :-)

**Comment by kpodemski** [comment]
@Hlavtox he solved his issue already by changing php version and increasing memory limit
