### ISSUE TITLE
upgrade V8.0.4 to V8.1.0

### ISSUE THREAD

**Issue by ECC64** [PrestaShop/PrestaShop#33408]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

New installation 8.0.4 installed on O2Switch PHP8.1, MySQL 10.6.14 MariaDB.
No plugins installed, original theme. Demo products only.
1click module version: 4.16.1
All lights green.
Choice: major update to have access to V8.1
All options unchecked except: update default theme.
I am attaching the error as a screenshot.
![363319787_6935942923085585_8847954977700699894_n](https://github.com/PrestaShop/PrestaShop/assets/61431435/0e797a46-6fb6-4bb3-9ff7-8897f6a25c9d)

if I am not in the right place to ask my problem, please tell me where to turn with a link, an email or a form, because simply tell me to see Team Edition, nobody knows at Prestashop.

### Steps to reproduce

upgrade 1click Upgrade too 4.16.1
Put in mantenance mode
launch the upgrade to 8.1.0
and see the picture join
![363319787_6935942923085585_8847954977700699894_n](https://github.com/PrestaShop/PrestaShop/assets/61431435/903b9d9c-b9cc-49b1-a2c4-34983c35740e)

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.1

**Comment by kpodemski** [comment]
You should have more details about what went wrong inside /your_admin_dir/autoupgrade/tmp/log.txt

Could you see if there's something at the end of this file that could be helpful? It is impossible to tell what problem you had.

**Comment by florine2623** [comment]
I'm not sure this is related to the Core.

**Comment by ECC64** [comment]
Hello,
the end of log.txt 

2023-07-27 10:48:01] Copied /vendor/willdurand/negotiation/src/Negotiation/LanguageNegotiator.php.
[2023-07-27 10:48:01] Copied /vendor/willdurand/negotiation/src/Negotiation/Negotiator.php.
[2023-07-27 10:48:01] Directory /webservice already exists.
[2023-07-27 10:48:01] Copied /webservice/dispatcher.php.
[2023-07-27 10:48:01] Copied /webservice/index.php.
[2023-07-27 10:48:01] All files upgraded. Now upgrading database...
[2023-07-27 10:48:01] [SKIP] directory "/app/cache/" does not exist and cannot be emptied.
[2023-07-27 10:48:02] [CLEANING CACHE] File prod removed
[2023-07-27 10:48:02] [INTERNAL] /home/vafr5898/public_html/vendor/composer/autoload_real.php line 36 - Error: Class "Composer\Autoload\ComposerStaticInit015ec6598460e77da763c3cb9c71a97c" not found
#0 /home/vafr5898/public_html/vendor/autoload.php(25): ComposerAutoloaderInit015ec6598460e77da763c3cb9c71a97c::getLoader()
#1 /home/vafr5898/public_html/modules/autoupgrade/classes/UpgradeContainer.php(567): require_once('/home/vafr5898/...')
#2 /home/vafr5898/public_html/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(84): PrestaShop\Module\AutoUpgrade\UpgradeContainer->initPrestaShopAutoloader()
#3 /home/vafr5898/public_html/admin715gbiovfq89jobpeky/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->init()
#4 {main}

thank's for your help

**Comment by kpodemski** [comment]
@ECC64 thanks, do you opcache enabled on your server?

**Comment by ECC64** [comment]
@kpodemski no cache enabled, no CCC enabled

**Comment by ECC64** [comment]
Salut  :)

j'ai trouvé la solution, obligé de passer en PHP 7.4 et 1024 de RAM allouées

**Comment by kpodemski** [comment]
ok, thanks @ECC64! in that case, I'm closing this ticket
