### ISSUE TITLE
[Responsive] Contact page is badly displayed

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#33415]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

From `767px` to `567px`, the contact page is badly displayed, cause: 

- `col-sm-4` should be `col-md-4`
- `col-md-3` should be `col-lg-3`

![image](https://github.com/PrestaShop/PrestaShop/assets/23308427/d5c440cf-47f3-4e1d-88c5-94981fb9ef04)

### Expected behavior

![image](https://github.com/PrestaShop/PrestaShop/assets/23308427/42ae2e0f-d665-44a4-ae90-a5c1decb97cf)

### Steps to reproduce

1. FO>Contact us
2. Use responsive mode, click F12
3. Shrink the window to width 650px
4. See error > bad display

### PrestaShop version(s) where the bug happened

1.7.8.8 & 8.0.4 & 8.1.0

### PHP version(s) where the bug happened

7.4

**Comment by iamtiagogalvao** [comment]
I will work on a PR for this issue. However, this is not related to this repo. I Will do my PR on [PrestaShop/classic-theme](https://github.com/PrestaShop/classic-theme).

**Comment by matks** [comment]
Hi @Slaveworx really cool! Please checkout the contributions guidelines before 😉 https://devdocs.prestashop-project.org/8/contribute/contribution-guidelines/

**Comment by iamtiagogalvao** [comment]
I assume that this issue can now be closed as per the merge of PR [#123](https://github.com/PrestaShop/classic-theme/pull/123) ?

**Comment by matks** [comment]
@iamtiagogalvao Yes

Usuall GitHub does it automatically when we use `Fixes ...` but sometimes it fails 😅

**Comment by matks** [comment]
This bug is now solved in classic-theme 2.0.2 which is not published yet.
