### ISSUE TITLE
Cart rules - When you add two block of product in the condition tab, the first one doesn't works 

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#33416]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you add another block of product in condition of a cart rules, it'll doesn't works except if this product is also in the cart, as you can see : 

[Untitled_ Jul 26, 2023 3_16 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/6327994a-25ac-4b50-8cf7-910424697f21)

Doesn't know if it's an issue or an expected behavior (check the entire video)

### Expected behavior

I wish my product have the discount 

### Steps to reproduce

1. Go to BO > Catalog > Discount
2. Add a new cart rules
3. On the condition enable "product selection" and add a first block of product with "Mountain fox notebook "
4. Add another block of product with "Hummingbird notebook"
5. Go to FO and add Mountain fox notebook to you cart
6.  Check your cart, you'll see your product without the discount 

### PrestaShop version(s) where the bug happened

1.7.8.9 - 8.0.4 - 8.1.1 

### PHP version(s) where the bug happened

7.4.33

**Comment by kpodemski** [comment]
It's never worked like that in PrestaShop. There are no discounts on the product line in PrestaShop. The issue can be closed.

**Comment by florine2623** [comment]
In the [user doc](https://docs.prestashop-project.org/v.8-documentation/user-guide/selling/managing-catalog/managing-discounts/cart-rules) I found : `Product selection. Another very useful tool, which enables to create automatic vouchers for a cart which contain specific products. The tool is explained in more detail below.`

To me it means that I can enjoy a discount when a specific product is in the cart.

ping @PrestaShop/product-team @MatShir could you confirm the behavior ?

**Comment by kpodemski** [comment]
but there is a discount available, it's just not marked on the product since it is a discount for the cart, not a specific price for the product

so I confirm the behavior 👍🏻

**Comment by Hlavtox** [comment]
I confirm the behavior. ✅

**Comment by MatShir** [comment]
We agree it is the expected behavior ? Shall we close the issue ? 
You can have X Product selection, in these products select it can have different criteria, lets called them product criteria. So between product criteria is an OR logic (one of the criteria have to be matched) and between product selection is an AND logic. So if i follow the steps, the cart can only work if the 2 product are present in the cart. Or did I miss a step ?

**Comment by Hlavtox** [comment]
@MatShir This is a normal behavior.

When you add multiple condition groups, they all must be met for the discount to apply. Then work as AND.
The rules inside work as OR.

**Comment by MatShir** [comment]
So what is the issue then ? 🤔

**Comment by Hlavtox** [comment]
There is no issue, you can close it.

**Comment by MatShir** [comment]
ok cool, maybe we should improve the doc and the interface @TristanLDD ;)
