### ISSUE TITLE
Image - Avif format doesn't works when I regenerate the thumbnail 

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#33424]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I want to regenerate the thumbnail with the new feature image, if I enable the Avif, I've a red screen as you can see : 

[Untitled_ Jul 26, 2023 3_40 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/cd9cef5f-2987-4a18-a96d-9a99729bcb76)

### Expected behavior

I expected that I have no red screen on it

### Steps to reproduce

1. Go to BO > Advanced Parameters > New & Experimental Features 
2. Enable Multiple Image Format 
3. Go to BO > Image Settings
4. Try to Enable Avif, even if your bowser doesn't enable it for you 
5. Save it 
6. Scroll down and Clic on Regenerate thumbnails, Regenerate :x: **Error** You'll have a red screen 
7. **Bonus** If you go on FO, you'll have a **Fatal Error**

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

7.4.33

**Comment by florine2623** [comment]
Hello @AureRita ,

I reproduced the issue with PrestaShop version `8.1.1` and `develop,` I'll add this to the backlog so it can be fixed.
<img width="1067" alt="Screenshot 2023-07-26 at 16 34 01" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/e13effb1-c97a-4835-afe8-192cd193cea7">

It also breaks the FO:
<img width="1439" alt="Screenshot 2023-07-26 at 16 38 18" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/9c8e139e-e486-4916-b0b4-0781800ad027">


Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by kpodemski** [comment]
We lack back-end validation, I agree, but I'm not sure if this is a major issue if one is required to _hack_ PrestaShop. Nice catch, tho :-)

**Comment by florine2623** [comment]
You are right ^^
