### ISSUE TITLE
Duplicating products when a category has a discount for a group of customers

### ISSUE THREAD

**Issue by Tomex4** [PrestaShop/PrestaShop#33449]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If the product is assigned to a category that has a discount assigned to a group of customers, an attempt to duplicate (copy) such a product ends with a 500 error.
Debugging gives the error description:

> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'INSERT INTO `ps_product_group_reduction_cache` (`id_product`, `id_group`, `re...' at line 1<br /><br /><pre>INSERT INTO `ps_product_group_reduction_cache` (`id_product`, `id_group`, `reduction`) VALUES (2542, 4, 0.05) ON DUPLICATE KEY UPDATE `reduction` = 0.05;INSERT INTO `ps_product_group_reduction_cache` (`id_product`, `id_group`, `reduction`) VALUES (2542, 5, 0.1) ON DUPLICATE KEY UPDATE `reduction` = 0.1;INSERT INTO `ps_product_group_reduction_cache` (`id_product`, `id_group`, `reduction` `) VALUES (2542, 6, 0.15) ON DUPLICATE KEY UPDATE `reduction` = 0.15;INSERT INTO `ps_product_group_reduction_cache` (`id_product`, `id_group`, `reduction`) VALUES (2542, 7, 0.2) ON DUPLICATE KEY UPDATE `reduction` = 0.2;</pre>

The problem occurs when there are entries in the ps_product_group_reduction_cache table for a given id_product.
If a given product is not assigned to a category that meets the above conditions fo, there are no records for its id_product in the ps_product_group_reduction_cache table and duplication of such a product is correct.

### Expected behavior

Duplicate product

### Steps to reproduce

1. Preferences > Customers >Groups > Edit > Discount = 0%
2.  Category discount = 5%
3. Catalog > Products > Edit 
4. Catalog > Products > Duplicate

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @Tomex4 ,

I can't reproduce your issue in PS 8.0.

I have added a discount on the Home Category for the Visitor customer group:
<img width="969" alt="Screenshot 2023-07-27 at 14 36 49" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/5e44ddb7-6080-4eeb-8a3f-7910c855964b">

I have no problem duplicating the product from Home category or any other category from the Product edition page and from the Products listing page.

Am I missing something ?

Waiting for your feedback.
Thanks!

**Comment by Tomex4** [comment]
You're right. I did something else that in the ps_product_group_reduction_cache table there were data:
  | id_product | id_group | reduction |  
  | 13 | 4 | 0.0500
  | 13 | 5 | 0.1000
  | 13 | 6 | 0.1500
  | 13 | 7 | 0.2000
  | 20 | 4 | 0.0500
  | 20 | 5 | 0.1000
  | 20 | 6 | 0.1500
  | 20 | 7 | 0.2000

If you add this to the table, duplicating products doesn't work, but for now I can't determine what led to this data being left. I will still try.

**Comment by florine2623** [comment]
Hello @Tomex4 ,

Can you share how you manage to have this data in this table ?
Or did you add it manually ?

**Comment by Tomex4** [comment]
I'm pretty sure that the entries in this table were created during one of the data imports. However, I am unable to reproduce the error.

I manually removed the data from the table and the problem disappeared.

**Comment by florine2623** [comment]
Ok thanks for the details.

I'm closing your issus as you fixed it ^^

**Comment by bicipres** [comment]
Hi @Tomex4, @florine2623,

Tomex, I suceed to reproduce your bug in a simple way.  

Have a look on this PR: https://github.com/PrestaShop/PrestaShop/issues/31737

Making the change of config/defines.inc.php define('PS_ALLOW_MULTI_STATEMENTS_QUERIES', false); FALSE change to TRUE

To temporarily fix it works, but it's not a solution...
