### ISSUE TITLE
Extend mail layout from module with prestashop 8.0.4

### ISSUE THREAD

**Issue by industria01** [PrestaShop/PrestaShop#33447]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,
I have created a module following this [guideline](https://devdocs.prestashop-project.org/8/modules/concepts/mail-templates/extend-a-layout-from-module/), but with prestashop 8.0.4 when I go to back office to preview the extended layout, twig die with error 500: Could not find layout file: /...full-path-to.../modules/my_module_name/mails/layouts/order_conf.html.twig. 

I have added in /src/Adapter/MailTemplate/MailTemplateTwigRenderer.php on line 130 this code to debug `dd($layoutPath);` and without my module hook the output is:
```
"@MailThemes/modern/core/order_conf.html.twig"
```
with my module hook (hookActionListMailThemes) the output is:
```
"/...full-path-to.../modules/my_module_name/mails/layouts/custom_order_conf.html.twig"
```

I have installed this module in prestashop 1.7.8.7 and works like a charm, the order_conf mail load the overrided layout, instead in prestashop 8 load the core mail layout.

### Steps to reproduce

1. Create a module following this [guideline](https://devdocs.prestashop-project.org/8/modules/concepts/mail-templates/extend-a-layout-from-module/)
2. Go to Back Office > Design > Mail Theme
3. Click to order_conf http
4. View 500 error code.

1. Create an order
2. order_conf mail layout is loaded from prestashop core instead of module folder.

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.0.29

**Comment by industria01** [comment]
I've solved. With prestashop 8 change this:
```
$theme->getLayouts()->offsetSet($orderIndex, new Layout(
            $orderConfLayout->getName(),
            __DIR__ . '/mails/layouts/order_conf.html.twig',
            ''
        ));
```
with 
```
$theme->getLayouts()->offsetSet($orderIndex, new Layout(
                $orderConfLayout->getName(),
                '@Modules/your_module_name/mails/layouts/order_conf.html.twig',
                ''
            ));
```
Please update this [guideline](https://devdocs.prestashop-project.org/8/modules/concepts/mail-templates/extend-a-layout-from-module/)

**Comment by florine2623** [comment]
ping @PrestaShop/prestashop-core-developers @PrestaShop/product-team
