### ISSUE TITLE
ps_facetedsearch does not respect visibility in multistore enviroment

### ISSUE THREAD

**Issue by mariuszsienkiewicz** [PrestaShop/PrestaShop#33454]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The problem is that `ps_facetedsearch` does not respect the **visibility** set in the particular shop - it checks the **visibility** in the `ps_product` table instead of `ps_product_shop`. In the result, the module shows products in a category that shouldn't even be visible.

You can easily fix that by adding this:

```php
'visibility' => [
    'tableName' => 'product_shop',
    'tableAlias' => 'ps',
    'joinCondition' => '(p.id_product = ps.id_product AND ps.id_shop = ' .
    $this->getContext()->shop->id . ' AND ps.active = TRUE)',
    'joinType' => self::INNER_JOIN,
],
```

in `src/Adaper/MySQL.php`.

It will automatically assign the visibility where clause to `ps_product_shop` instead of `ps_product`.

### Expected behavior

When we set visibility to none in some shop then it shouldn't be visible.

### Steps to reproduce

1. Enable multistore.
2. Add an additional shop.
3. Set the visibility of a product in the first shop to `both`.
4. Set the visibility of the same product in the second shop to `none`.

After that, you will see that the product is still visible in the second shop.

### PrestaShop version(s) where the bug happened

1.7.7.1

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_facetedsearch 3.12.1

**Comment by mariuszsienkiewicz** [comment]
Oops, this fix is already in the `dev` branch of that module I haven't checked the codebase. This change is still awaiting release for 4 months.

I'm gonna close this issue then.

**Comment by Hlavtox** [comment]
Hi @mariuszsienkiewicz, let's update! :-) https://github.com/PrestaShop/ps_facetedsearch/releases/tag/v3.13.0
