### ISSUE TITLE
Address form issue - actionValidateCustomerAddressForm does not exist

### ISSUE THREAD

**Issue by OctaYann** [PrestaShop/PrestaShop#33461]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After autoupgrade with the module from 1.7.7.5 to 1.7.8.9 the fronted address form cannot be submited anymore.
When submited it says : "Please fix the error below." => [found a fix here ](https://www.prestashop.com/forums/topic/1064559-frontend-add-new-address-error-after-upgrade/#elComment_3395723).
It seams to be the actionValidateCustomerAddressForm that doesnt exists in database

### Expected behavior

Autoupagrade module should have create the hook in db if it doesnt exist.
Prestashop sould throw an error in debug mode to make this type of error debuggable...

### Steps to reproduce

Get 1.7.7.5
update to 1.7.8.9
try create an address

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment]
Hello @OctaYann ,

Could you send a screenshot of your issue ?

Also, is is similar to https://github.com/PrestaShop/PrestaShop/issues/27184 ?

**Comment by OctaYann** [comment]
Hello, thanks for your reply, here was the error.
There is an issue but no issue in specific input soooo....
![image](https://github.com/PrestaShop/PrestaShop/assets/107422379/2fb7b431-3328-4937-98ec-585567db6c80)

**Comment by florine2623** [comment]
Hello @OctaYann ,

I can't reproduce your issue after upgrading my shop from 1.7.7.3 to 1.7.8.9.

https://github.com/PrestaShop/PrestaShop/assets/16019289/9756a50d-c0d0-4e0d-8f4d-b533b5d9d3b4

The error comes from your theme. With classic theme, the error is well displayed.

I'm closing this issue as it cannot be reproduced.
Thanks!
