### ISSUE TITLE
Bug on prestashop 8.1.0 when I try to remove from cart a product with a not default combination

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#33473]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
I've found a bug on prestashop 8.1
there is some problem to remove a product from the cart when it is selected a combination that is not the default one

it reports a problem on the id_manufacturer but it is not the problem, because if I try to remove the default combination there are no problems

`Warning: Undefined array key "id_manufacturer" in /var/www/html/CMS/prestashop/prestashop8/classes/Product.php on line 5620
{"success":true,"id_product":2,"id_product_attribute":11,"id_customization":0,"quantity":0,"cart":{"products":[],"totals":{"total":{"type":"total","label":"Totale","amount":0,"value":"0,00\u00a0\u20ac"},"total_including_tax":{"type":"total","label":"Totale (tasse incl.)","amount":0,"value":"0,00\u00a0\u20ac"},"total_excluding_tax":{"type":"total","label":"Totale (tasse escl.)","amount":0,"value":"0,00\u00a0\u20ac"}},"subtotals":{"products":{"type":"products","label":"Totale parziale","amount":0,"value":"0,00\u00a0\u20ac"},"discounts":null,"shipping":{"type":"shipping","label":"Spedizione","amount":0,"value":""},"tax":null},"products_count":0,"summary_string":"0 articoli","labels":{"tax_short":"(Tasse incl.)","tax_long":"(Iva inclusa)"},"id_address_delivery":0,"id_address_invoice":0,"is_virtual":false,"vouchers":{"allowed":0,"added":[]},"discounts":[],"minimalPurchase":0,"minimalPurchaseRequired":""},"errors":""}`

at 5620 there is this line

`$row['manufacturer_name'] = !empty((int) $row['id_manufacturer']) ? Manufacturer::getNameById((int) $row['id_manufacturer']) : null;`

![1](https://github.com/PrestaShop/PrestaShop/assets/653230/f9266ae4-83eb-4e03-a521-86fd6570f966)

bye

### Steps to reproduce

1. go in a product with combination
2. select a different combination from default one
3. add it to the cart
4. go in the cart summary
5. try to remove it from cart
6. the product will not remove
7. check in the dev tool in the network section like I show in the video

https://watch.screencastify.com/v/jEv6NSqesof918k9thgM

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

maofree

**Comment by aniszr** [comment]
Hello @maofree 

I managed to reproduce this issue 

See attached screen record :

https://github.com/PrestaShop/PrestaShop/assets/92626242/fb9d6a62-9070-4142-845c-bff1715f1ab5

- `PS : Make sure you add to the cart a combination different from the default one displayed `
- `The problem disappears when refreshing the page`

I THINK ITS SIMILAR TO THIS [ISSUE](https://github.com/PrestaShop/PrestaShop/issues/32889) WHAT DO YOU THINK ?

Thanks!

**Comment by Maofree** [comment]
Hi @aniszr 
yes it is the same issue

at the refresh the product is removed from the cart, because the command is sent, but there is a php error that block the return of the data to update that part in the front office

**Comment by aniszr** [comment]
This issue is a duplicate of [#32889](https://github.com/PrestaShop/PrestaShop/issues/32889).

To be informed when it's fixed, please subscribe to the issue mentioned above.
We will close the issue.
Thank you

**Comment by aniszr** [comment]
Duplicate of [#32889 ](https://github.com/PrestaShop/PrestaShop/issues/32889)

**Comment by hibatallahAouadni** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/32889
