### ISSUE TITLE
VAT calculation problem on invoices

### ISSUE THREAD

**Issue by buddyfrance** [PrestaShop/PrestaShop#33470]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Good morning,

When I place an order with different VAT (20 and 5.5) using a cart rule, the VAT calculation is wrong.
If I make a discount of X euros on products with VAT 20 and I order other products which are at a VAT of 5.5 the discount applies to the 2 VATs when it should only apply to the VAT 20.

- Prestashop version: 8.1.0 (same problem on version 4.0.1)
- PHP version: 8.1
[#EBUD000007_2023.pdf](https://github.com/PrestaShop/PrestaShop/files/12192024/EBUD000007_2023.pdf) (With the miscalculation)
[#EBUD000006_2023.pdf](https://github.com/PrestaShop/PrestaShop/files/12192050/EBUD000006_2023.pdf) without calculation error)

### Expected behavior

What I would like would be to be able to order different products which do not necessarily have the same VAT, with or without a discount on them and for the invoices to be correct. That there is no invoice error.
This is a very urgent issue as it is preventing me from putting the website into production. Please do the necessary as soon as possible.
### Steps to reproduce

1 - Go to the site https://buddy-france.mypresta.shop/ and choose the products: 
https://buddy-france.mypresta.shop/accueil/19-customizable-mug.html (TVA 20%)
https://buddy-france.mypresta.shop/fleurs/52-341-santa-maria.html#/35-poids-100_g (TVA 5.5%)
https://buddy-france.mypresta.shop/resines/31-374-double-zero.html#/35-poids-100_g (TVA 20%)
2 - add products in the cart that have different VAT 5.5% and 20%
3 - use of the basket rule on the product (https://buddy-france.mypresta.shop/accueil/19-customizable-mug.html) with 20% VAT. In my case add the reduction code "test2" which gives me a discount of 5.39€
4 - validate the order
5 - validate the payment to obtain the invoice

Maybe a clue here: https://www.prestashop.com/forums/topic/902515-calcul-tva-avec-ristourne-erron%C3%A9/

### PrestaShop version(s) where the bug happened

4.0.1 et 8.1.0

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

module règle panier

### Your company or customer's name goes here (if applicable).

Buddy France

**Comment by aniszr** [comment]
Hello @buddyfrance 

Could you please change your issue title in English cause English  is the norme on Github.
I see that you're using the PS version 8.1.0, but you wrote 4.0.1 & 8.1.0 as PS version!!! what do you mean?
About the module that you use, is it a native one? if so, could you please provide its name in English, if it's not, please contact the module developer on Addons.
Waiting for your feedback.

Thanks!

**Comment by buddyfrance** [comment]
Hello Anis,

I am using version 8.1.0, but before I was on version 4 and had the same
problem. The module in question is a prestashop ntif module, it is the
"basket rule" module for making discounts.

Le ven. 28 juil. 2023 à 17:24, anis zouari ***@***.***> a
écrit :

**Comment by MatShir** [comment]
I'm still not sure of which module you are talking about @buddyfrance :/ (maybe could you share the module technical name or a screenshot)

@aniszr the issue seems quite problematic, could you check on 8.1 PS if you can reproduce the issue ? (even tho without the module name for now) 🙏

**Comment by buddyfrance** [comment]
Good morning,
By using the solution indicated on this link:
https://www.prestashop.com/forums/topic/902515-calcul-tva-avec-ristourne-erron%C3%A9/
I solved my problem. Apparently when you make a cart discount and you have
products that do not have the same VAT in the cart, the calculation was
incorrect. When I made the modification indicated in the previous link,
this modification fixed the problem.

**Comment by florine2623** [comment]
I'm closing the issue as you fixed it !
Thanks!

**Comment by MatShir** [comment]
The bug still needs to be reproduced 🙏

**Comment by MatShir** [comment]
Fixing on his shop doesn't mean it is fixed on the project

**Comment by buddyfrance** [comment]
Good morning,
I no longer have the bug after using the following modification:
In the CartRules.php file at line 990 I replaced the code:
$price = $product['price'];
                            if ($use_tax) {
                                $price *= (1 +
$context->cart->getAverageProductsTaxRate());
                            }
by

                            $price =
Product::getPriceStatic($product['id_product'],
                                $use_tax,
                                isset($product['id_product_attribute']) ?
(int)$product['id_product_attribute']: null,
                                6,
                                null,
                                false,
                                false,
                                $product['cart_quantity']);

This corrected my VAT calculation problem. I can no longer reproduce the
anomaly.

**Comment by florine2623** [comment]
Hello @buddyfrance & @MatShir ,

On my end I couldn't reproduce the issue.

The final price on the invoice and the website is the same.
I used a cart rule of 10% for my discount as an example.
<img width="1094" alt="Screenshot 2023-08-03 at 10 57 03" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/ea9179d3-87a0-4fa4-aa2f-3c5e874dc6e1">
<img width="987" alt="Screenshot 2023-08-03 at 10 56 54" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/10b6851a-c480-45e8-a16e-e9e488b2821a">

Could you specify the config of the "Promo 3 à 5 Cartouches - 5,39 €" ?

**Comment by buddyfrance** [comment]
I use the "Promotions and discounts - (3x2, discounts, campaigns)" module
which allows me to make a promotion with a percentage discount depending on
the quantity ordered. The products affected by this promo are products with
20% VAT.


Le jeu. 3 août 2023 à 11:00, florine2623 ***@***.***> a
écrit :

**Comment by florine2623** [comment]
This is not a native module from PrestaShop. 
You should contact the developer of the module directly to get this bug fixed ^^

**Comment by kpodemski** [comment]
I agree with @florine2623 

You should definitely consult this problem with the author of the module. I'll also ping them here, so they are aware of the issue :)

cc @idnovate

**Comment by idnovate** [comment]
This is not related with the module but with this bug https://github.com/PrestaShop/PrestaShop/issues/33543 ;)

**Comment by kpodemski** [comment]
@idnovate ok! thanks :)

PS: I appreciate your latest activity in the project. It's great to see a successful tech vendor from the marketplace being here with us to improve things ❤️

**Comment by MatShir** [comment]
Thanks @idnovate for your PR !
I will close this issue in favor of https://github.com/PrestaShop/PrestaShop/issues/33543.
Thanks also @florine2623 @buddyfrance

**Comment by MatShir** [comment]
duplicate of https://github.com/PrestaShop/PrestaShop/issues/33543
