### ISSUE TITLE
Update address in backoffice

### ISSUE THREAD

**Issue by luigimassa** [PrestaShop/PrestaShop#33477]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

when you update a customer address in the back office, the address is logically deleted and a new address is created.
In the process and in the hooks, the id of the new address was not passed, but of the old one and it is not possible to trace the new address in any way
`FormHandler` calls the command `EditCustomerAddressHandler` that copy the object and return it. But `FormHandler` doesn't save the new Address object and dispatch the hook `actionAfterUpdateCustomerAddressFormHandler` with old object 

Affected: 
 - PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler  (line 143 and 145)
 - PrestaShop\PrestaShop\Adapter\Address\CommandHandler\EditCustomerAddressHandler 

### Expected behavior

It would be necessary to pass the id of the new object to the hook

### Steps to reproduce

1. implement a module with hook `actionAfterUpdateCustomerAddressFormHandler`
1. create ad order in front office
2. go to address
3. edit address of customer of this order
4. change somthings
5. save

when save in `hookActionAfterUpdate` params contains only old address object

### PrestaShop version(s) where the bug happened

from 1.7.* to 8.1.1

### PHP version(s) where the bug happened

7.4

**Comment by ghost** [comment]
Please correct the php version its not "1.7.8.1"

**Comment by sallemiines** [comment]
Hello @luigimassa 

could you please provide simple module with hook `actionAfterUpdate` , to help me reproduce the issue
Waiting for your feedback .

Thank you

**Comment by luigimassa** [comment]
@sallemiines hello
my mistake
the correct hook were actionAfterUpdateCustomerAddressFormHandler
In attach the module
[testhook.zip](https://github.com/PrestaShop/PrestaShop/files/12258443/testhook.zip)

**Comment by florine2623** [comment]
Hello @luigimassa ,

Is that your issue ?

https://github.com/PrestaShop/PrestaShop/assets/16019289/858bf0ee-6960-4a5e-be3b-e1aa265e0dd5

When I uninstall the test module, I do not have any issue.

**Comment by florine2623** [comment]
Hello,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
