### ISSUE TITLE
Controller WishlistStatisticsAdminController missing or faulty in Blockwishlist

### ISSUE THREAD

**Issue by musicpanda** [PrestaShop/PrestaShop#33485]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you configure Blockwishlist it has a second tab at the top that shows statistics.

In version 2.1.2 - that comes with Prestashop 8.1 - this works ok. However, with version 3.0 of Blockwishlist I get an error.
![wish](https://github.com/PrestaShop/PrestaShop/assets/13930107/d6d47039-a390-46c7-8c4d-cb93b6b859d7)

### Expected behavior

Showing of statistics.

### Steps to reproduce

Go to modules -> Blockwishlist
Click Configure
Click the second tab: statistics

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

blockwishlist

**Comment by sallemiines** [comment]
Hello @musicpanda 

Thanx for the issue 

I didn't manage to reproduce the issue with `PS 810 , PS 811 , PS 1789 `
I test the issue with  blockwishlist module V 3.0.0 and V 2.1.2

https://github.com/PrestaShop/PrestaShop/assets/31663369/8d91b3d2-715a-4225-b677-c713b5d68a65


Did I miss smthng ? 
Please check and feedback ! 
Thank you

**Comment by musicpanda** [comment]
I tested it again and now it works. 

There must have been some caching problem. Maybe due to the update...

One thing to add: when things didn't work the url for the statistics tab was:
    /admin/index.php?controller=WishlistStatisticsAdminController
When it did work the url was:
  /admin/index.php/modules/blockwishlist/statistics

I have  no idea why at different times it shows different urls. Anyway, I will close the topic for now.
