### ISSUE TITLE
Oops! An Error Occurred

### ISSUE THREAD

**Issue by elfahci** [PrestaShop/PrestaShop#33482]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

https://motos-eurotapi.mypresta.shop/admin698iyv8pakckzjbxwmv/index.php

error msg

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

### Expected behavior

dont have acces to my backoffice after being updating some moduls 

### Steps to reproduce

https://motos-eurotapi.mypresta.shop/admin698iyv8pakckzjbxwmv/index.php

trying to access

### PrestaShop version(s) where the bug happened

8

**Comment by PrestaEdit** [comment]
Please... remove the Back Office link on your message (and change it, now).

**Comment by sallemiines** [comment]
@Hlavtox 

Thanx for the created PR !

**Comment by sallemiines** [comment]
Hello @elfahci 


Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template and provide clear and concise steps to reproduce the bug**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by elfahci** [comment]
i have no more info. i even can t access to try doing something.

**Comment by AlienzEyes** [comment]
I'm using PHP version 8.1 with PS version Basic_version_9.0.1-1. After a fresh install, all proper files ownership on Debian 12 apache2 server and after what appears to be a smooth installation with a new database, after immediately erasing the install then trying to access the admin login area, I'm presented with:

The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused. 

I never get to log in and there are no errors left in the error.log. Will you help an tell me what I am missing to fix this?

UPDATE: I fixed it by erasing all the files in the directory /var/cache/prod..
