### ISSUE TITLE
Cannot add specific price rule

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#33486]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

...

### Expected behavior

...

### Steps to reproduce

1. Install 8.1.x branch. Check that all feature flags are deactivated.
2. Go to Catalog > Catalog price rules > Add new.
3. Fill the name.
5. Leave Price (tax excl) empty.
6. Uncheck "Keep original price".
7. Enter some discount in the bottom.
8. Save.
9. Error `number_format(): Argument #1 ($num) must be of type float, string given` in `\controllers\admin\AdminSpecificPriceRuleController.php (line 324)`.

Input values
![Snímek obrazovky 2023-07-30 160833](https://github.com/PrestaShop/PrestaShop/assets/6097524/68fab584-2ecd-483e-902d-f67f7843d8bf)

Errors
![error](https://github.com/PrestaShop/PrestaShop/assets/6097524/5fbd0978-1ebb-45cc-914f-edf67f0b7990)

### PrestaShop version(s) where the bug happened

8.1.x branch

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment]
Ping @PrestaShop/committers

**Comment by sallemiines** [comment]
Hello @Hlavtox 

Thanx for he issue 

I reproduce your issue with PS-81x  

![image (2)](https://github.com/PrestaShop/PrestaShop/assets/31663369/c0c4ea0a-a79a-4ff8-91ae-0c9ec8437c47)


PS 810 
![image](https://github.com/PrestaShop/PrestaShop/assets/31663369/92507711-cf6e-4936-a569-fafbf69061c9)

PS 1789

![image (3)](https://github.com/PrestaShop/PrestaShop/assets/31663369/2660a76a-ee67-46c9-8579-8321d1864051)

 I'll add this to the backlog so it can be fixed.
 
 Thank you
