### ISSUE TITLE
Initial values for MPN fields are not set when upgrading

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#33493]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When upgrading PS from versions lower than 1.7.7, somebody forgot to set empty values after adding new columns for MPN field. This value is added, but is NULL. This was not a problem on legacy product page, but results in exception when opening products on new product page.

➡️ I opened a PR that fixes it for NEW UPGRADES, but it also must be fixed for people that already upgraded. Although they probably fought with this error themselves.

### Expected behavior

Values must be initialized to empty string.

### Steps to reproduce

1. Install 1.7.6.
2. Upgrade to 8.1
3. Enable new product page.
4. Open any product in BO.
5. Fatal error.

### PrestaShop version(s) where the bug happened

1.7.6 to 8.1

### PHP version(s) where the bug happened

8.1

**Comment by sallemiines** [comment]
Hello @Hlavtox 

I didn't manage to reproduce the issue , Upgrade from  PS 1768 => PS 810 with autoupgrade module v 4.16 


https://github.com/PrestaShop/PrestaShop/assets/31663369/cd232451-25b1-487d-9288-cb2e213439fd

Did I miss smthng ? 

PLease check and feedback !

**Comment by Hlavtox** [comment]
@sallemiines You are upgrading from 1.7.7.6, not 1.7.6 - see steps to reproduce. :-)

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

I reproduce the issue with PS1767 upgraded to PS810 (only when you use the Product Page V2), see the attached screenshot below:

<img width="1172" alt="Screenshot 2023-08-02 at 08 25 41" src="https://github.com/PrestaShop/PrestaShop/assets/23308427/a6a70985-9bef-43a2-91cd-29efa11df8b8">

I will add it to the becklog and thanks for your PR 🚀 

Thanks!
