### ISSUE TITLE
Fixtures do not contain low_stock_threshold

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#33490]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Default demo data doesn't contain low_stock_threshold, which results in this value being NULL in the database, while in fact, it should be 0, like it is for all new products.

### Expected behavior

Fixtures must be changed. PR created.

### Steps to reproduce

1. Install Prestashop, 
2. open phpmyadmin, 
3. find ps_product
4. check that values in low_stock_threshold are zeroes, instead NULL for demo products.

### PrestaShop version(s) where the bug happened

8.1.0

**Comment by sallemiines** [comment]
Hello @Hlavtox 
Thanx for the created issue 

I reproduce the issue with PS810  

![image](https://github.com/PrestaShop/PrestaShop/assets/31663369/a070dd6d-40e1-4c83-91de-448d1a727623)

Thank you !
