### ISSUE TITLE
ps_mbo  Module issue: Disconnects marketplace

### ISSUE THREAD

**Issue by alkorotkovas** [PrestaShop/PrestaShop#33519]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the back office, the ps_mbo module disconnects daily. When connecting, after a few hours it shows "connect to Prestashop marketplace" again and again.

The same happens with the Trustpilot module, but I would say it's on a weekly basis, not daily. 

### Expected behavior

Module should not disconnect.

### Steps to reproduce

In the admin back office connect to the Prestashop marketplace
It will disconnect after few hours.

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_mbo

**Comment by sallemiines** [comment]
Hello @alkorotkovas 

 The issue is incomplete, cannot be reproduced . 
 
 we will wlose this issue ! 
 Thank you
