### ISSUE TITLE
Faceted search module cache increasing my database size 

### ISSUE THREAD

**Issue by Kabir260** [PrestaShop/PrestaShop#33517]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,

I use Faceted search module for my Prestashop 8.1 but the cache size (_price_index) is so high which is around 3.2 Gb. The allocated database size of my website is 5 GB whereas only this specific cache covers 3.2 GB. I tried to clear the cache from the Prestashop backoffice (Faceted search module) but still,
![price_indexx](https://github.com/PrestaShop/PrestaShop/assets/141034057/3155705d-840b-479e-a8e3-482be9ee36c6)
 the cache size shows almost the same. Can anybody please help me out how I can solve this issue?

Thank you very much. Looking forward to hearing from you. 
![Backoffice](https://github.com/PrestaShop/PrestaShop/assets/141034057/44741db2-efee-4aca-9039-a960e5f90e8c)
![price_indexx](https://github.com/PrestaShop/PrestaShop/assets/141034057/3c4aef7f-b1ce-4f8e-9ae4-567977e51cd7)

### Steps to reproduce

1. Modules 
2. ps_facetedsearch   
3. Configure

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_facetedsearch  (Faceted search)

**Comment by Hlavtox** [comment]
@Kabir260 Clear cache button in faceted search clears only block cache, not the index.

Prices get indexed for every active country, active currency product. How many countries, currencies and products do you have on your shop?

**Comment by Kabir260** [comment]
Hi Hlavtox,

Thank you for your reply. I ship the products all over the world. In that sense, all countries are active. 
And the active currency is one (Euro). I set 2 other currencies but kept them disabled mood on the backoffice. My website has two language option (English and German). And there are almost 5000 products. The website address is:
https://brandshopi.com/en/  
Looking forward to hearing from you.

**Comment by Hlavtox** [comment]
@Kabir260 You are welcome.

Yeah, that is the explanation, you have 241 countries in your shop and every one needs to be indexed. If you had only one country enabled, your whole index would have around 13 MB instead of 3,2 GB.

If you don't use specific prices or catalog rules limited to a specific country, you could modify the faceted search a bit so it doesn't consider id_country at all.

**Comment by Kabir260** [comment]
Hi Hlavtox,

Thank you very much for your explanation. Now I understand. I would like to ask you if it is possible to move just ONLY my database (MariaDB) to another root server where I will have enough space? If so, would it be any drawback?

Thank you. Looking forward to hearing from you.

**Comment by sallemiines** [comment]
Hello @Hlavtox 


Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Comment by Hlavtox** [comment]
@Kabir260 You can do it, but I think a database on another server will be too slow. I would just ask the provider to increase the size of the database or move you to a bigger plan/tariff.

**Comment by Kabir260** [comment]
Hi Hlavtox,

Thank you very much for your help.

Regards.
