### ISSUE TITLE
Symfony controllers not being found in Perstashop 8.0.4 +

### ISSUE THREAD

**Issue by musaffarpatel** [PrestaShop/PrestaShop#33510]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

It seems with each new update something major seems to break.

In Prestashop 8.0.4, 8.1.0 and 8.1.1 The usual symfony module controllers and routes no longer seem to work.  They were working find in previous controller.

You may use your own demo-grid module to observe the problem.

The error produced is:
include(C:\websites\prestashop\80\wwwpqap\modules\demo_grid\vendor\composer/../composer/InstalledVersions.php): Failed to open stream: No such file or directory

I have a feeling this is the first of other errors.

I spent a few months developing a module based on the example modules provided and everything worked great foir the later versions of Prestashop 1.7 and 8.0.1 and things seemed to have collapsed thereafter.  

### Steps to reproduce

Download the Prestashop demo-grid module from : https://github.com/sarjon/demo-grid-module
Install a fresh install of Prestashop 8.04 or 8.1.0
In the demo-grid module folder, run the command composer dumpautoload
Now try to access the module in the back office and the following error is thrown:

include(C:\websites\prestashop\80\wwwpqap\modules\demo_grid\vendor\composer/../composer/InstalledVersions.php): Failed to open stream: No such file or directory

### PrestaShop version(s) where the bug happened

8.0.4, 8.1.0, 8.1.1

**Comment by kpodemski** [comment]
Hello @musaffarpatel 

This is a module from 5 years ago, and it is not even maintained by PrestaShop Project. You have all the example modules here:
https://github.com/PrestaShop/example-modules/

**Comment by musaffarpatel** [comment]
@kpodemski Apologies, I posted the wrong link in my question.  I can confirm it the demo_grid module from https://github.com/PrestaShop/example-modules/ which fails to install on Prestashop 8.0.4+ with the error I originally posted

**Comment by kpodemski** [comment]
I have the `demo_grid` installed on my PrestaShop installation. Did you run `composer install` (not dump-autoload, but install)
