### ISSUE TITLE
Retry downloading language pack

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#33514]
### Describe the bug and add attachments

Sometimes upgrades or installs fail because of a failed language pack download, due to temporary server outage, connection problem or something.

Example: https://github.com/PrestaShop/autoupgrade/actions/runs/5723138582/job/15507245693?pr=607

![Snímek obrazovky 2023-08-01 084309](https://github.com/PrestaShop/PrestaShop/assets/6097524/7cac2994-8bc6-4b0d-8400-2baff62b4a2f)

### Expected behavior

We should add a a basic while loop for 3 attempts in `Language::downloadXLFLanguagePack()`.

### PrestaShop version(s) where the bug happened

1.7 to develop

**Comment by kpodemski** [comment]
@Hlavtox do you want to keep the issue open, so it will be fixed on autoupgrade level as well, or we can close it?

**Comment by Hlavtox** [comment]
@kpodemski Well, since the autoupgrade is using the core method if I am not mistaken, people would get this fix when upgrading to 8.1.2 and later, so I think it's not worth it.

But, we must check if installer is using this. ;-) It is?
