### ISSUE TITLE
Back office theme not updated after update from v 8.0.3 to 8.1.0

### ISSUE THREAD

**Issue by musaffarpatel** [PrestaShop/PrestaShop#33525]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After updating Prestashop 8.0.3 to 8.1.0 the back office theme remains the same and doe snot match the back office theme of a new 8.1.0 install.

The update is successful according the 1 click upgrade process.

All caches have been cleared, including browser and also tested on different devices.

![screenshot](https://github.com/PrestaShop/PrestaShop/assets/5041037/880ba17d-1bd6-448c-9971-0d9c8073883b)

### Expected behavior

The back office theme should match the theme displayed in a fresh 8.1.0 install

![screenshot-2](https://github.com/PrestaShop/PrestaShop/assets/5041037/d6d40d14-c1c7-4153-838e-d545c1f0c7e6)

### Steps to reproduce

Run the 1 click upgrade process on a Prestashop 8.0.3 install

### PrestaShop version(s) where the bug happened

8.0.3 to 8.1.0

**Comment by Hlavtox** [comment]
The second screenshot you see is from a customized edition of prestashop company.

The clean opensource version looks like on the first screnshot, there is nothing wrong with it. 👍

**Comment by musaffarpatel** [comment]
@Hlavtox I simply downloaded the second version from https://prestashop.com/versions/
From there I download Prestashop 8.1.0 and it has the new interface.
Is there more information on the alternate versions you mention (cuzstomized edition vs opensource) ?

**Comment by florine2623** [comment]
You can download the open source version here : https://github.com/PrestaShop/PrestaShop/releases/tag/8.1.0

**Comment by musaffarpatel** [comment]
@florine2623 In terms of functionality is there any difference between the open source version on github and the versions clients are downloading through the Prestashop site?

**Comment by Hlavtox** [comment]
@musaffarpatel It contains some preinstalled modules and changes styling of the backoffice a bit. I suggest going with the clean version.

**Comment by musaffarpatel** [comment]
@Hlavtox Thanks

**Comment by MatShir** [comment]
The module which change the styling are disabled after an upgrade. You need to enable them to have it back :)

**Comment by musaffarpatel** [comment]
@MatShir Which module should I enable again?

**Comment by MatShir** [comment]
something like ps_edition_basic
