### ISSUE TITLE
errores de borrado y alta

### ISSUE THREAD

**Issue by Korporativos** [PrestaShop/PrestaShop#33534]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Buenos dias,

tengo un problema con mi prestashop:
1º.- no me borra categorias
2ª.- no me añade productos
3º.- la pagina esta desconfigurada, esta descuadrada.
![a3](https://github.com/PrestaShop/PrestaShop/assets/141316371/a48abf0b-ae36-40a5-a36e-71004e3e344d)
![t5](https://github.com/PrestaShop/PrestaShop/assets/141316371/d3afc189-8865-4e0e-8853-fdbce0e6eb5e)

### Expected behavior

que todo funcione correctamente

### Steps to reproduce

1º.- no me borra categorias
2ª.- no me añade productos
3º.- la pagina esta desconfigurada, esta descuadrada.

### PrestaShop version(s) where the bug happened

1.7.6.2

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

sera el modulo catalogo

### Your company or customer's name goes here (if applicable).

Korporativos

**Comment by florine2623** [comment]
Hello @Korporativos ,

Please send your request in english.

Check this link for system requirements : https://devdocs.prestashop-project.org/1.7/basics/installation/system-requirements/

And change your PHP version to 7.2.

Waiting for your feedback.
Thanks!

**Comment by florine2623** [comment]
I'm closing your issue as it is a PHP version issue ^^
