### ISSUE TITLE
Weight and shipping cost not correct for combinations 

### ISSUE THREAD

**Issue by George-Cara** [PrestaShop/PrestaShop#33549]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Values for impact on weight and shipping price at combination level, won't be taken into account when adding products to cart in FO or into an order in BO. They are simply not calculated. Only values at product level are considered.

### Expected behavior

Values at combination levels should be added to the ones at product level for weight and additional shipping price of weight

### Steps to reproduce

1. add a product with combinations with 0 and 0 at product level for weight and additional shipping cost, but insert some values at combination level for those fields.
2. add that product to cart and observe nothing added to shipping price
3. Also add products in BO into an order with "recalculate shipping price for each order change" option activated and observe the shipping price wont change
4. All of the above only work if those fields are set at product level and only that value is taken into account nomatter what you insert at combination level for them

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

7.3.33

**Comment by AureRita** [comment]
Hi @George-Cara 

Thank you for your report, I tried to reproduce your issue as you can see : 

[Untitled_ Aug 8, 2023 3_22 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/2163d8bf-d050-43c0-861f-270ac2d334c8)

But currently I can't, 
Did I miss something ? 

Can you provide us some screen / video ? 

Thank you 

Waiting for your feedback

**Comment by George-Cara** [comment]
Hello.
Thank you for your answer.
First you have version 8.1.1 (I dont know if that would be a difference but just saying.
Second you already have carriers defined and maybe you have them calculate shipping by weight so the differences at carrier cost is because the difference in the weights. The problem is not there. Just set the weight 1 to all but change the price/weight in combination like i show in this capture of your video. So make them all 1 at weight in combination but change the cost to be 1,2,3,4 for each of those combination. Then, at the checkout you shoul have shipping prices wihth 1 unit more as you change combinations, but it wont happen it is not taking into account that price
![Untitled-3](https://github.com/PrestaShop/PrestaShop/assets/116998491/1a277481-a2b8-428e-8629-96296b1ea50a)

**Comment by sallemiines** [comment]
Hi @George-Cara

Thank you for your report, I didn't manage to reproduce your issue with PS 810 , could you please provide us a full screen recorder describes the steps ! 

Thank you !

**Comment by aniszr** [comment]
Hello @George-Cara ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Comment by George-Cara** [comment]
Sorry. Didn't have the time to answer. Can I reopen this ?
Here you have pictures of what I was testing

This is the product (with 2 combinations) with 0 weight and 0 additional costs for weight at product level:

<img width="1072" alt="0" src="https://github.com/PrestaShop/PrestaShop/assets/116998491/1ae736a4-c3e5-4688-b716-2242d4dd8355">

The resulting shipping cost is here ... 18 lei and it is correct

<img width="1057" alt="1" src="https://github.com/PrestaShop/PrestaShop/assets/116998491/9138cb1d-92a2-458d-b42b-f4dd26ad4a13">

If we set 1 and 1 as weight and additional costs for weight like this (at product level):

<img width="1049" alt="2" src="https://github.com/PrestaShop/PrestaShop/assets/116998491/c96c45f6-48b1-4d27-ae41-b47fe8646b32">

the result would be ok. It added 1 to the shipping cost as you can see

<img width="1052" alt="3" src="https://github.com/PrestaShop/PrestaShop/assets/116998491/df46e465-55e6-4209-a0ad-d234a61f73ec">

But if we edit a combination of this product

<img width="1052" alt="4" src="https://github.com/PrestaShop/PrestaShop/assets/116998491/1b822d9d-202f-4a16-a812-b790dd3fe5a9">

and set the weight and weight impact price at combination level like this

<img width="1056" alt="5" src="https://github.com/PrestaShop/PrestaShop/assets/116998491/42e39cd9-a367-4a52-9a87-c83fe9f6550e">

it should increase the price of shipping by 10 lei, but it doesn't

<img width="1065" alt="6" src="https://github.com/PrestaShop/PrestaShop/assets/116998491/353099a7-e541-4187-a8cd-b7a8a9bd81ba">

When getting the shipping costs it doesn't take into account the weight price impact set at combination level, it only considers the price impact of weight at product level !
