### ISSUE TITLE
undefined method call after upgrade from version 1.7.8.7 to 1.7.8.9

### ISSUE THREAD

**Issue by andai06** [PrestaShop/PrestaShop#33547]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have encountered some issues while using the 1-click upgrade module (version 4.16.1) developed by the PrestaShop team. I'm hoping you can assist in diagnosing and fixing these problems.

Module Version 4.16.1 Issue: When I used version 4.16.1 of the module and clicked on the "configure" button, the back office of the site became inaccessible. I had to manually remove the module via FTP to regain access.

Module Version 4.16.0 Issue: After installing version 4.16.0 of the module, the upgrade was successful, but I encountered numerous warnings and errors throughout the site and back office. Here are some examples:

Warning: Use of undefined constant _PS_ALLOW_MULTI_STATEMENTS_QUERIES_ - assumed '_PS_ALLOW_MULTI_STATEMENTS_QUERIES_' (this will throw an Error in a future version of PHP) in /var/www/html/classes/db/DbPDO.php on line 92
Warning: Use of undefined constant _PS_SMARTY_CACHING_TYPE_ - assumed '_PS_SMARTY_CACHING_TYPE_' (this will throw an Error in a future version of PHP) in /var/www/html/config/smarty.config.inc.php on line 43
Environment variable not found: "runtime:_PS_ALLOW_MULTI_STATEMENTS_QUERIES_".
Attempted to call an undefined method named "hasMediaServer" of class "Tools".
Attempted to call an undefined method named "setFallbackParameters" of class "Tools". => LegacyParametersListener
These errors appear to indicate that some constants and methods are not defined in the current system configuration. It is unclear whether these issues are specific to my environment or if they are a result of a bug within the module.

### Steps to reproduce

1. Go to module manager
2. Find 1 click upgrade
3. Click to configuration
4. BO is inaccessible

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.3.33

### If your bug is related to a module, specify its name and its version

autoupgrade (4.16.1)

**Comment by AureRita** [comment]
Hi @andai06 

Thank you for your report, I tried to reproduce your Issue as you can see : 

[Untitled_ Aug 4, 2023 4_25 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/cd00f158-457f-4a1f-82d2-1b5d648f6a0a)

But I can't reproduce it, did you reproduce it with the new version 4.16.2 ? a new patch is released. 

did I miss anything to reproduce your issue ? 

Waiting for your feedback

**Comment by andy-tuzeyi06** [comment]
Ok, I will try to reproduce this with the latest version.

**Comment by hibatallahAouadni** [comment]
Hello @andai06 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
