### ISSUE TITLE
Incorrect tax detail in the invoice when a cart rule is applied to more than 1 unit of a specific product

### ISSUE THREAD

**Issue by idnovate** [PrestaShop/PrestaShop#33543]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The tax detail from the invoice is not calculated correctly when there are products with different VAT rate and you apply a cart rule to more than 1 unit for a specific product.

### Steps to reproduce

1. Configure 2 products with different VAT rule
![image](https://github.com/PrestaShop/PrestaShop/assets/15104724/339fb787-eaa7-4a67-a442-5c248accc70e)
![image](https://github.com/PrestaShop/PrestaShop/assets/15104724/98176289-cdae-45e3-9ab3-220b51f4accf)

2. Create a cart rule that applies to one of these products
![image](https://github.com/PrestaShop/PrestaShop/assets/15104724/09dac2b7-c575-40d2-ac14-f13c8f3867be)

3. Make an order with 1x the first product and 2x the second product
4. Change the order status to one that generates the invoice
5. Check the invoice detail

![image](https://github.com/PrestaShop/PrestaShop/assets/15104724/fd93b915-9767-44e4-b627-7f6c4ceca6dc)

The base price is wrong, so the tax is incorrect. 21% tax should be for a base price of €30.00, and 10% tax for €40.00 - €4.00 = €36.00.

### PrestaShop version(s) where the bug happened

8.1.0

### Your company or customer's name goes here (if applicable).

idnovate.com

**Comment by AureRita** [comment]
Hi @idnovate ,

Thank you for your report, I reproduce the issue with PrestaShop version 8.1.1, as you can see : 

![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/2014ebb4-f774-47bc-a651-bd5171d15b50)


 I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. I

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by idnovate** [comment]
It's fixed in this PR https://github.com/idnovate/PrestaShop/pull/2

**Comment by kpodemski** [comment]
@idnovate could you send it as a Pull Request to the core? :D It is now a Pull Request to your own fork

**Comment by MatShir** [comment]
You could even target 8.1.x branch :)

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/33608
