### ISSUE TITLE
Smarty template precompilation during installation is broken

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#33540]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When installing the `develop` branch, I noticed there were two XHR requests failing:

<img width="944" alt="Screenshot" src="https://github.com/PrestaShop/PrestaShop/assets/1009343/b505be1e-1ef7-4327-802f-b08566b0f35e">

After some digging up, I noticed that the error was a redeclaration of `_PS_DO_NOT_LOAD_CONFIGURATION_` [in smarty_compile.php](https://github.com/PrestaShop/PrestaShop/blob/8.1.0/install-dev/controllers/http/smarty_compile.php#L26), because it is initially declared [in defines.inc.php](https://github.com/PrestaShop/PrestaShop/blob/8.1.0/config/defines.inc.php#L62).

This error is a regression from 8.1.0, coming from [this change](https://github.com/PrestaShop/PrestaShop/pull/30518).

It also appears that BO precompilation doesn't work when running from sources (as opposed to build) because of the hardcoded "admin" directory [here](https://github.com/PrestaShop/PrestaShop/blob/8.1.0/install-dev/controllers/http/smarty_compile.php#L28).

### Expected behavior

The request doesn't fail and the templates are precompiled.

### Steps to reproduce

1. Go to install
2. See error

### PrestaShop version(s) where the bug happened

develop, 8.1.0

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello @eternoendless ,

I have reproduced your issue with `8.1.0`, `develop`. Ok with 8.0.0.
<img width="1432" alt="Screenshot 2023-08-03 at 17 05 49" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/a54d706e-86be-4888-aa96-5bedf4d0ac92">

**Comment by kpodemski** [comment]
@florine2623 it's not a major issue 👍🏻

**Comment by kpodemski** [comment]
cc @Robin-Fischer-PS @hibatallahAouadni

**Comment by SharakPL** [comment]
Looks like there's more to it. Besides `_PS_DO_NOT_LOAD_CONFIGURATION_` warning there's also fatal error:

> PHP Fatal error:  Uncaught Error: Undefined constant "_DB_PREFIX_" in classes\Configuration.php:175

Both generated twice on each step of the installation until the database is configured and installation process starts (not fatal after all since whole process looks smooth as always on the front). Then a known error about missing `theme_name` https://github.com/PrestaShop/PrestaShop/issues/29557 (already fixed, but for PS9 only) and a new notice never generated in previous prestashop versions:

> PHP Notice:  stream_copy_to_stream(): Read of 8192 bytes failed with errno=13 Permission denied in vendor\symfony\symfony\src\Symfony\Component\Filesystem\Filesystem.php on line 66

Also 2 deprecations on generating new admin folder name:

> PHP Deprecated:  strtolower(): Passing null to parameter `#1` ($string) of type string is deprecated in classes\Tab.php on line 389

> PHP Deprecated:  trim(): Passing null to parameter `#1` ($string) of type string is deprecated in classes\Dispatcher.php on line 902

Installation of PS 8.1.1 on windows' Wampserver, cgi php 8.1.9, mysql 5.7

**Comment by kpodemski** [comment]
@SharakPL Windows-things.

**Comment by SharakPL** [comment]
I always install on Windows and never had that before. Although it's the first time on PHP 8.1.

**Comment by dzatoah** [comment]
Related to #33717?

**Comment by SharakPL** [comment]
Yes. Although I'm still not sure why my installation went on despite multiple fatal errors generated. Should be stopped like in that issue.

**Comment by promokit** [comment]
@SharakPL @eternoendless Please check your php configuration and try to set `session.use_strict_mode=0`

**Comment by SharakPL** [comment]
It is set like that.

**Comment by promokit** [comment]
@SharakPL that resolved my problem. Try to play with other session parameters

**Comment by SharakPL** [comment]
You mean all these repeated fatal errors are caused by session configuration?
