### ISSUE TITLE
ps_shop_group' doesn't exist

### ISSUE THREAD

**Issue by joe-gdn** [PrestaShop/PrestaShop#33553]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In a fresh Install of Prestashop 8.1 I get this error

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database.ps_shop_group' doesn't exist

The error happen at 25% when create shop and default language.

All other table are created, if I create the table and restart the installation it delete the table and get same error.

### Steps to reproduce

Download on github https://github.com/PrestaShop/PrestaShop/releases/download/8.1.0/prestashop_8.1.0.zip and follow the instruction for a normal setup

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.1

**Comment by kpodemski** [comment]
Hello @joe-gdn 

I'm sure it is related to your hosting environment. I'm 100% sure it will be impossible to reproduce this behavior for us since the software installation is something we do every day.

I suggest you try using a different environment first, if it works, then try to compare settings, especially those related to the database engine.

**Comment by joe-gdn** [comment]
The hosting is virtualmin on Ubuntu 22.04 with enabled extension as
suggested from PrestaShop installation and php check.
I will try to indagate more, but If you have some suggestions is weel
accepted

Il dom 6 ago 2023, 20:36 Krystian Podemski ***@***.***> ha
scritto:

**Comment by kpodemski** [comment]
As for now, try on a different environment first 👍🏻  If you have more questions, I suggest you visit us on [Slack](https://www.prestashop-project.org/slack/) or create a topic on [Discussions Q&A](https://github.com/PrestaShop/PrestaShop/discussions/categories/q-a)

**Comment by sammirata** [comment]
This exact error is happening for me too. My hosting environment cannot be changed. We use our own Linux OS distro and have 100% control of all the packages and scripts as we install everything from scratch. Can you please give us some pointers on how to find out what the incompatibility is? Is there a log file? can we perhaps create the database and tables manually with a script to see if the error is with the execution of your db creation script?
