### ISSUE TITLE
addJqueryUI load all JqueryUI, not just a component

### ISSUE THREAD

**Issue by tups** [PrestaShop/PrestaShop#33558]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On the frontController, calling the `addJqueryUI` function automatically adds the whole jQuery UI library.

### Expected behavior

The function should only add the necessary components. (The jQuery library being quite heavy, it is interesting for web performance (webperf) to load only the necessary components)

We can also see that in the Controller `classes/controller/Controller.php` does it very well for the administration.

Example we execute:
`$this->context->controller->addJqueryUi('ui.autocomplete');`

The jQuery UI library is fully loaded:
     - `/js/jquery/ui/jquery-ui.min.js`
     - `/js/jquery/ui/themes/base/minified/jquery.ui.theme.min.css`
     - `/js/jquery/ui/themes/base/minified/jquery-ui.min.css`
Instead of just charging:

- `js/jquery/ui/jquery.ui.core.min.js`
- `js/jquery/ui/jquery.ui.widget.min.js`
- `js/jquery/ui/jquery.ui.position.min.js`
- `js/jquery/ui/jquery.ui.menu.min.js`
- `js/jquery/ui/jquery.ui.autocomplete.min.js`

- `/js/jquery/ui/themes/base/jquery.ui.core.css`
- `/js/jquery/ui/themes/base/jquery.ui.widget.css`
- `/js/jquery/ui/themes/base/jquery.ui.position.css`
- `/js/jquery/ui/themes/base/jquery.ui.menu.css`
- `/js/jquery/ui/themes/base/jquery.ui.autocomplete.css`

### Steps to reproduce

1. Add search bar module (ps_searchbar)
2. Check on the Front side, the list of assets loaded in the network console of the web browser

### PrestaShop version(s) where the bug happened

All

### PHP version(s) where the bug happened

All

### Your company or customer's name goes here (if applicable).

Damien TUPINIER & Lord of Web

**Comment by Hlavtox** [comment]
@tups Yeah, this is an issue. This is some half-baked migration when 1.7 was created.

We investigated it when working on my related issue - https://github.com/PrestaShop/PrestaShop/issues/27186.

Another thing - there is both minified and "per-widget" version in the same folder. And the backoffice is still using the separated version, but the front is loading the whole minified package. :-)

I personally solved it on my stores by creating a custom build just with datepicker and slider for FO purposes and loading it instead of the original one. It has 46 kB vs the original 223 kB.

**Comment by tups** [comment]
For my part, on my projects, I have already patched the modules, and the frontController with an override.
Afterwards, if you activate the CCC compression, the compression works very well.

I'm going to propose a PR, I'll come back quickly with a proposal

**Comment by AureRita** [comment]
Hi @tups 

Thank you for your report, currently this one is too technical for me. 
As @Hlavtox said this one is a real issue, This is concidered as verified.

Thank you for your PR :rocket: 

Thanks

**Comment by Hlavtox** [comment]
@AureRita I will explain briefly:
- jQueryUI is a javascript library that has some nice things like datepicker, slider, autocomplete, spinner and goodies like this. https://jqueryui.com/
- It's used in both FO and BO.
- You can add it to the page by calling `addJqueryUI('nameofcomponentyouneedtoadd');`
- When you do this in BO, it adds only things needed for this single component, like datepicker. For example, about 25 kB of code. 🟢
- But if you do it in FO, it adds the whole package with ALL components, which is huge in size (224 kB), which slows down the front office. 🔴
