### ISSUE TITLE
GH Action to publish docker images for PS 1.7.8.10, 8.0.5 and 8.1.1 is failing

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#33568]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

GH Action to publish docker images for PS 1.7.8.10, 8.0.5 and 8.1.1 is failing
https://github.com/PrestaShop/docker/actions/runs/5787114810

This step is the last step to complete the release process of PS 1.7.8.10, 8.0.5 and 8.1.1 . It aims at publishing docker images for these versions on https://hub.docker.com/r/prestashop/prestashop/

It was triggered by merged PR https://github.com/PrestaShop/docker/pull/349

### Expected behavior

We need the GH action to run, in order to publish the docker images

### Steps to reproduce

1. Open https://github.com/PrestaShop/docker/actions/runs/5787114810
2. See error 😄 

### PrestaShop version(s) where the bug happened

N/A

**Comment by jolelievre** [comment]
Related PR to split the workflow https://github.com/PrestaShop/docker/pull/351

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/docker/pull/351
