### ISSUE TITLE
Can NOT Upgrade from local archive 9.0.0 which was extract from develop branch

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#33578]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Founded and reproduced by @matthieu-rolland 🚀 
See the attached screen record below:

[1ClickUpgrade_presta810.webm](https://github.com/PrestaShop/PrestaShop/assets/23308427/7416eb88-5b20-49d8-bc4e-af481a995c28)

### Expected behavior

The upgarde should be processed as usual 

### Steps to reproduce

1. git clone https://github.com/PrestaShop/PrestaShop.git
2. cd PrestaShop
3. composer install
4. make install OR make assets
5. Install your shop by access to PrestaShop/install-dev
6. then under PrestaShop, execute this command : `php tools/build/CreateRelease.php --version="9.0.0"` to create an archive
7. Install a new shop with stable version 8.0.5 or 8.1.1
8. BO>Module Manager
9. Install the latest version of `1-Click autoupgrade` module: 4.16.2
10. Copy the generated zip and xml file from PrestaShop (develop branch), you can find it under tools>build>releases>9.0.0_date
11. and paste it under admin-dev>autoupgrade>download
12. Back to BO>1-Click autoupgrade module
13. Choose Local archive as Channel
14. Select your zip and xml file, put 9.0.0 as number of version
15. Save
16. See error > an Info pop up displayed saying: `You need to enter the version number associated with the archive.`

### PrestaShop version(s) where the bug happened

8.0.5 & 8.1.1

### PHP version(s) where the bug happened

7.4 & 8.1

### If your bug is related to a module, specify its name and its version

1-Click autoupgrade v4.16.2

**Comment by matthieu-rolland** [comment]
I think this is because of [this condition](https://github.com/PrestaShop/autoupgrade/blob/830a720032271c259c0e211f5381f2b3474d4da8/js/upgrade.js#L828) in autoupgrade JS

Edit: yes that was it, here's a fix: https://github.com/PrestaShop/autoupgrade/pull/613
