### ISSUE TITLE
FO - Combination - Dustbin doesn't reload the cart when you delete a combinated item

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#33576]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you want to delete a product combination wich the combination isn't the preselected, the reload of the cart doesn't occur so you didn't see that the product is not in your cart, as you can see : 

[Untitled_ Aug 8, 2023 5_04 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/340dba8a-b786-421f-a53a-3ee566c40b92)

### Expected behavior

I wish my product should be delete when I clic on the dustbin like other product 

### Steps to reproduce

1. Go to FO 
2. Select a combination product 
3. Select the second combination on the dropdown list
4. add this product to your cart 
5. Go to checkout 
6. Clic on the dustbin 
7. The product is displayed like here but it's not in you cart 

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

7.4.33

**Comment by MatShir** [comment]
Might be related to https://github.com/PrestaShop/PrestaShop/issues/32630

**Comment by kpodemski** [comment]
@AureRita could you enable developer mode and check the networks tab after you click the "Delete" button? We would need to see what happens to the sent request

**Comment by aniszr** [comment]
Hello @AureRita 

I didn't manage to reproduce this issue with PS 8.1.1 & 8.0.5 & 1.7.8.10.
It may be a problem related to cache!

See attached screenrecord :

https://github.com/PrestaShop/PrestaShop/assets/92626242/3a87a463-b8d8-4a30-b37b-33c0b65c09bd

Please check & feedback!

@MatShir  I checked this [issue](https://github.com/PrestaShop/PrestaShop/issues/32630) u'v mentioned, the only difference with this issue is about the type of product added to the card, what do you think ? it's a diplucation or not ?

Thanks!

**Comment by MatShir** [comment]
@aniszr and related issue is only on develop.
I couldn't reproduce either, so I guess we will keep the issue and wait for more inputs

**Comment by aniszr** [comment]
Hello @AureRita ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
