### ISSUE TITLE
Test issue (for bot)

### ISSUE THREAD

**Issue by boherm** [PrestaShop/PrestaShop#33574]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Nothing

### Steps to reproduce

Nothing

### PrestaShop version(s) where the bug happened

8.1.1

**Comment by boherm** [comment]
okoko

**Comment by AureRita** [comment]
:clap:
