### ISSUE TITLE
Meta keywords empty despite 'SEO > Tags' being populated

### ISSUE THREAD

**Issue by LarsGMortensen** [PrestaShop/PrestaShop#33585]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On a product (I tested on a product with combinations in PrestaShop 8.1.0), 
under the SEO-tab, at the bottom,
there is a field for "Tags"...

I have filled in several tags:

![image](https://github.com/PrestaShop/PrestaShop/assets/26773745/a6b8d583-3c61-45c2-a99b-4bfe6fc2d46e)

But when inspecting the source code for the product page, I notice that the 'meta keywords' is empty:

![image](https://github.com/PrestaShop/PrestaShop/assets/26773745/e2e23c57-8e91-4228-a9e7-4cf9114394a4)

### Expected behavior

As a user, I would expect that "tags" filled in under the "SEO"-tab for a product,
would also populate the 'meta keywords'-tag on the webpage.

### Steps to reproduce

1. Go to the SEO-tab for a product, go to the bottom.
2. Fill in some 'tags' in the 'tags'-input field.
3. Go to the front end webpage for that product, and inspect the source code for that page.
4. Notice that the 'meta keywords'-content is empty.
(please see screendumps above for visual explanation)

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

7.4.33

**Comment by Hlavtox** [comment]
Hi @LarsGMortensen, the tags you fill in backoffice are not meta keywords. The tags are used only for search and custom module purposes.

Since meta_keywords are dead for 15-20 years, there field to fill it on product page is not even there. 👍 It will eventually removed completely.

**Comment by MatShir** [comment]
That's right. Tags are only used for the internal search of the Front Office. 
I'm closing this use in favor of https://github.com/PrestaShop/PrestaShop/issues/11144

**Comment by aniszr** [comment]
Hello @LarsGMortensen 

Thank you for this issue, however it seems that it's a normal bahavior since all the tags are saved in a specific table `ps_tag`  in backend and consumed in front throught requests, so it's not necessary to display tags is front code !

Beside meta_keywords are no more used for searching as developpers confirmed!

 You can find more details about meta keywords in this [comments](https://github.com/PrestaShop/PrestaShop/issues/11144#issuecomment-432806306) 
 
Thanks!
