### ISSUE TITLE
Bulk edit of prices not working for product variants

### ISSUE THREAD

**Issue by LarsGMortensen** [PrestaShop/PrestaShop#33580]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On a product with combinations, 
I would like to bulk-edit prices for a number of the variations.
PrestaShop (8.1.0) tries to perform the desired action,
but nothing actually changes.

See screen-recording for visual explanation:

![chrome_KG3MIWmXlP](https://github.com/PrestaShop/PrestaShop/assets/26773745/468c19df-8886-4a4f-b81f-78569fa98924)

### Expected behavior

I would expect the functionality in PrestaShop to actually work.

### Steps to reproduce

1: Go to (or create) a product with combinations.
2: Select some of the combinations (i.e. every product with size = S)
3: Make a bulk-edit of the prices.
Note that the prices arent actually changing. See screen-recording above for visual explanation.

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

7.4.33

**Comment by aniszr** [comment]
Hello @LarsGMortensen 

I couldn't reproduce this issue with PS 8.1.0.

Could you please check in your product page the Pricing tab and make sure you filled the pricing fields to ensure right calculations!

See attached screenvideo :

https://github.com/PrestaShop/PrestaShop/assets/92626242/a0d6a548-44e3-4fdb-a567-50176625eb67


Check and feedback if I missed something!

Thanks!

**Comment by LarsGMortensen** [comment]
Hi @aniszr 
Thank you for the quick reply! :)
I have done some more testing and found the error:
I have the pricing field for the product set to 0 (zero), because its easier to manage when just setting the specific price for the individual combinations.
BUT that does not seem to be the issue.
However, the issue is that I didn't activate the change for the price without tax. When I do activate that, it does work as expected.
Please see attached screen-recording below for visual explanation.
I do, however, still maintain (from a user's perspecitive) that this is a bug - as the user would expect it to change the price as instructed (and silently just update the price excl. tax too, without needing the user input to explicitly activate the change for price excl. tax).

If you do decide to fix this, I would vote for making it a server-side solution (fixing it client-side would lead to confusion and/or further execution problems - so just update the price ex. tax silently on the server side).

![2a6mTHWXVs](https://github.com/PrestaShop/PrestaShop/assets/26773745/7ad5556d-d926-4ca4-8d74-2b929f8448fd)

**Comment by sallemiines** [comment]
Hello @LarsGMortensen 

unfortunately I didn't manage to reproduce the  issue with PS 810 

https://github.com/PrestaShop/PrestaShop/assets/31663369/a4c396ef-4717-44fb-a149-f7258228fc63

Could you please check another time if there is a missing step to do ? 

Thank you

**Comment by Hlavtox** [comment]
@sallemiines As the author says, the bug happens when you change only the price with tax. On your video, you check both fields.

> However, the issue is that I didn't activate the change for the price without tax. When I do activate that, it does work as expected.

---------------------------

@LarsGMortensen I reproduced the issue, it must be fixed.

https://github.com/PrestaShop/PrestaShop/assets/6097524/a583f19e-87ed-4947-a3a3-95c534da9ce7

Ping @zuk3975 @jolelievre - any idea how to fix it? :-)

**Comment by LarsGMortensen** [comment]
@sallemiines please see the reply from @Hlavtox above.

Also, I just upgraded to 8.1.1 and I am still able to reproduce the error as described in my issue-report above.

**Comment by Hlavtox** [comment]
Ping @hibatallahAouadni

**Comment by jolelievre** [comment]
Yeah actually the bug is that the input for tax excluded should be automatically enabled when the one for tax included is enabled
Both fields are supposed to be synced, but I guess something went off in the JS
