### ISSUE TITLE
[BO] Stock management - Bad display of Bulk edit quantity

### ISSUE THREAD

**Issue by MhiriFaten** [PrestaShop/PrestaShop#33583]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

We can not click on the arrows to choose the quantity value to modify

develop :x: 

[Untitled_ Aug 9, 2023 12_06 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/111756615/633c5330-badd-47ef-ba6f-d78438a14033)

8.1.1 :x: 

[Untitled_ Aug 9, 2023 11_28 AM.webm](https://github.com/PrestaShop/PrestaShop/assets/111756615/0f7e1375-1bea-4edf-9144-69164576d3ff)

8.1.0 :x: 

[Untitled_ Aug 9, 2023 11_51 AM (1).webm](https://github.com/PrestaShop/PrestaShop/assets/111756615/4f7e3ae6-1fdc-4daa-bc3b-a0794bb928ce)

### Expected behavior

1.7.8.10 :heavy_check_mark: 

[Untitled_ Aug 9 2023 11_57 AM.webm](https://github.com/PrestaShop/PrestaShop/assets/111756615/0b301408-2e72-486c-8f46-3d20408e57e0)

8.0.5 :heavy_check_mark: 

[Untitled_ Aug 9 2023 12_04 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/111756615/768f9e08-d73b-4f5c-9642-9a7ea713cf59)

### Steps to reproduce

1. Go to BO> Catalog> Stock
2. Go to Bulk edit quantity and edit quantity with arrows

:warning: **_See Error :_** arrows not working

### PrestaShop version(s) where the bug happened

develop, 8.1.1, 8.1.0

### PHP version(s) where the bug happened

7.4 & 8.1

**Comment by aniszr** [comment]
Hello @MhiriFaten 

I managed to reproduce the issue you mentioned it's a regression on 1.7.8.10.

- Develop & 8.1.1 & 8.1.0 :x:
- 8.0.5 & 1.7.8.10 :heavy_check_mark: 

See attached screenrecord :


https://github.com/PrestaShop/PrestaShop/assets/92626242/eabc8c3a-51c6-4d94-b6f5-9e31ffd25468

Thanks!

**Comment by aniszr** [comment]
Hello ,

This issue is a duplicate of [#30634](https://github.com/PrestaShop/PrestaShop/issues/30634)_number.


Thank you

**Comment by aniszr** [comment]
Duplicate of #30634
