### ISSUE TITLE
Since 8.1, using namespace with ObjectModel will throw a PrestaShopLogger issue

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#33590]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Since this change : https://github.com/PrestaShop/PrestaShop/commit/39e5ad1392dc46b8e2bdd1d60d35cbee418b4395

While using a namespace into our own ObjectModel classes, the save of an element into a AdminController using this namespace will work but throw an alert about PrestaShopLogger->object_type as not valid.

### Steps to reproduce

1. Use ObjectModel with namespace
2. Use a ModuleAdminController using this ObjectModel as ClassName
3. Save the form
4. See the alert

### PrestaShop version(s) where the bug happened

8.1.0

### Your company or customer's name goes here (if applicable).

@Wepika

**Comment by hibatallahAouadni** [comment]
Hello @PrestaEdit 

Thanks for reporting the issue :raised_hands: 
Could you please provide a test module :pray: that will help me reproducing the issue.
Waiting for your feedback.

Thanks!

**Comment by MatShir** [comment]
What should be the expected behavior in your opinion?

**Comment by kpodemski** [comment]
It's not the only problem you'll encounter with namespaces for `ObjectModel` 🤔 anyway, if it spams the logs, I think it should be fixed, whether by changing validation method or getting back to the previous version

**Comment by PrestaEdit** [comment]
As I use them since years on 1.6 (with a Little adaptation on controllers), and without issues on 1.7, is it the only one and it's now a régression.

**Comment by sallemiines** [comment]
Hello @PrestaEdit

As @hibatallahAouadni  montionned above 
Could you please provide a test module  that will help us to  reproducing the issue.
Waiting for your feedback.

Thanks!

**Comment by gross-nvs** [comment]
Hello,

This module will allow you to easily test the issue described in this case: [test_33590.zip](https://github.com/PrestaShop/PrestaShop/files/12475413/test_33590.zip)
Just install the module and then configure it to trigger the error.

As mentioned above, I made a pull request for this issue: #33771

**Comment by MatShir** [comment]
thanks @gross-nvs

**Comment by sallemiines** [comment]
Hello @gross-nvs 

Thanks for the module :rocket: 
Indeed I reproduce the issue with PS81x, see the attached screen record below:

[issue_33590.webm](https://github.com/PrestaShop/PrestaShop/assets/31663369/612be613-6bf7-4d45-a7ed-a74c97be09e0)

I'll add this to the backlog so it can be fixed.
Thanks for your PR :rocket: :raised_hands: 

Thank you

**Comment by PrestaEdit** [comment]
This seems to be merged : https://github.com/PrestaShop/PrestaShop/pull/33771
So the issue could be closed, no ?

**Comment by Hlavtox** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/33771
