### ISSUE TITLE
BO Error after upgrade to 1.7.8.10

### ISSUE THREAD

**Issue by DPStudioGR** [PrestaShop/PrestaShop#33596]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On 2 different occasions upgrade to 1.7.8.10 has ended with no problem but when i try to connect to BO the page is blank, white..
I had php version 7.4.33 and i did upgrade to 8.1.21 with no difference.
i turned on debug mode and have this error..

"fatal error: Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs): PDOStatement|false in /var/www/vhosts/motormaniacs.gr/httpdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 70"

### Expected behavior

Normally i would login to my BO...

### Steps to reproduce

1

### PrestaShop version(s) where the bug happened

1.7.8.10

### PHP version(s) where the bug happened

8.1.21

### Your company or customer's name goes here (if applicable).

dpstudio

**Comment by Hlavtox** [comment]
@Stampa-Stampa 1.7.8 is not compatible with PHP 8, change your php version.

**Comment by sallemiines** [comment]
Hello @Stampa-Stampa 

Could you please change your php version as hlvatox mentioned  above !

`PS 178x  is not compatible with PHP 8`

![image](https://github.com/PrestaShop/PrestaShop/assets/31663369/1bc1c816-1992-4f34-9900-1e09d7939725)

Thank you !
