### ISSUE TITLE
Icons "View my store", "Bell", "My profile" - displayed incorrectly.

### ISSUE THREAD

**Issue by alkorotkovas** [PrestaShop/PrestaShop#33595]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After upgrading to Prestashop 1.7.8.9 -> 8.1 icons display
![Screenshot 2023-08-10 at 15 00 57](https://github.com/PrestaShop/PrestaShop/assets/103935370/d5c1ff62-dd6b-4138-a36c-9804fdbf23e9)
 like "list" items.

### Expected behavior

Items displayed inline.

### Steps to reproduce

1.7.8.9 - > 8.1

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

7.4

**Comment by hibatallahAouadni** [comment]
Hello @alkorotkovas 

Please try to refresh the page after disabling the cache and check if you still have this issue.
Waiting for your feedback.

Thanks!

**Comment by alkorotkovas** [comment]
@hibatallahAouadni Yes, it's still there. Also tried to rename the var/cache folder and etc.

**Comment by hibatallahAouadni** [comment]
Hello @alkorotkovas 

Thanks for your quick reply.
Could you please provide screenshot of your console, to check if there's an error :pray: 
Waiting for your feedback.

Thanks!

**Comment by Hlavtox** [comment]
CSS cache
@kpodemski We must backport the asset versioning

**Comment by kpodemski** [comment]
@alkorotkovas I'm certain it is a browser cache, could you try in the incognito mode? maybe you have some extra cache layer like Cloudflare?

**Comment by alkorotkovas** [comment]
@kpodemski I have tried it in Safari looks like works.

**Comment by sallemiines** [comment]
@alkorotkovas 

Glad to hear it works! Please try clearing caches in other browsers ! 
We will close this issue ! 

Thank you
