### ISSUE TITLE
Independent toolbar buttons twig component

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#33604]
A bit more details in #33182

**Comment by boherm** [comment]
In fact, it's preferable to wait the global Symfony twig component to retrieve all data without the use of Legacy Context!

So this issue is blocked by [#33140](https://github.com/PrestaShop/PrestaShop/issues/33140).

**Comment by WahbiPS** [comment]
included in https://github.com/PrestaShop/PrestaShop/issues/33140
