### ISSUE TITLE
Wrong html in "Documents" and "Carriers" order detail back office

### ISSUE THREAD

**Issue by 4k2k** [PrestaShop/PrestaShop#33613]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Fresh install of Prestashop 8.0.3 and html is wrong in fields "Documents" and "Carriers" of order detail of bakcoffice.
I apply this fix but it not solve the problem: https://github.com/PrestaShop/PrestaShop/pull/32215/files/101986fcd411a04f3d88e18c8bed72da7594d7c4
<img width="1736" alt="z" src="https://github.com/PrestaShop/PrestaShop/assets/29382179/6cf20dde-6d11-4d5b-a96b-1897ec915bc0">

### Expected behavior

<img width="1736" alt="z2" src="https://github.com/PrestaShop/PrestaShop/assets/29382179/471789ca-1d50-4150-a85d-ee113109f4cf">

### Steps to reproduce

Go to Orders and clic in View

### PrestaShop version(s) where the bug happened

8.0.3

### PHP version(s) where the bug happened

8.2.8

### Your company or customer's name goes here (if applicable).

edgar

**Comment by hibatallahAouadni** [comment]
Hello @4k2k 

Please downgrade your PHP version cause PS 8.0.3 is not compatible with PHP 8.2, see our [system requirements](https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/#php-compatibility-chart).
Please check and feedback.

Thanks!

**Comment by 4k2k** [comment]
I downgraded to PHP 8.1.22 but the error of html escape still is

**Comment by hibatallahAouadni** [comment]
@4k2k try to clear and disable the cache :wink:

**Comment by 4k2k** [comment]
Cache is cleared and disabled, it is not the problem

**Comment by aniszr** [comment]
Hello @4k2k 

I didn't manage to reproduce this issue in both versions :

Develop :x:
![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/65e58fcc-b87d-4fc0-9b08-a7e5f2a07589)

8.1.x :x:

![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/21acd01e-039b-485d-94a1-bdfa25088b6d)

All HTML LGTM:heavy_check_mark: 

This type of issue is often related to cache problems, try to use a private navigation window and clear cache in both sides : browser and shop (BO > Advanced Parameters >Performance )

Check and feedback please!

Thanks!

**Comment by 4k2k** [comment]
Is not PS 8.1.X, is PS 8.0.3. I cleared cache, disabled cache and logged from other browser but the problem continue, is the same problem as alert box html escape https://github.com/PrestaShop/PrestaShop/pull/32215/files/101986fcd411a04f3d88e18c8bed72da7594d7c4 but only the alert box was fixed with this change

**Comment by hibatallahAouadni** [comment]
Hello @4k2k 

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely an override or a third-party module problem, see the attached screenshot below:

![image](https://github.com/PrestaShop/PrestaShop/assets/23308427/ab89fd58-9252-46a4-85c7-dc7e17158833)

We will close this issue.

Thanks!
