### ISSUE TITLE
Error while changing the cover image on Product edit page

### ISSUE THREAD

**Issue by stefchrif** [PrestaShop/PrestaShop#33611]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

While changing a the cover image from the product edit page, it show an error : https://stefchrif.tinytake.com/msc/ODU2NDQ3NF8yMTkwNDY2OA 

And after enabling the debug mode I have this : 
https://stefchrif.tinytake.com/msc/ODU2NDQ3OF8yMTkwNDY3Mg

### Steps to reproduce

1-Go to edit page of a product on backoffice that have more than one image.
2-Select another image than the cover one.
3-Set it as cover image.
4-Click on save button.

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

7.4.33 

### Your company or customer's name goes here (if applicable).

stef-chrif

**Comment by sallemiines** [comment]
Hello @stefchrif 

I didn't manage to reproduce your issue with PS 810 81X and develop ( in the two cases debug mode is enabled and disabled ) 


https://github.com/PrestaShop/PrestaShop/assets/31663369/2a86fff3-f191-415d-9430-97ee4cb40a86

https://github.com/PrestaShop/PrestaShop/assets/31663369/3818a7f3-fad5-44eb-a91a-d512d609c5ab

Did I miss smthg ! 

Please check and feedback !

**Comment by sallemiines** [comment]
Hello @stefchrif 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Comment by jix31** [comment]
I have exactly the same bug with a **fresh installation** 

when i want to set cover product image   /  or save caption text  / and  move product image don't works 

 i have this red message :  function(){return r&&o(s,r),(e.migrateIsPatchEnabled(s)?i:a||e.noop).apply(this,arguments)}



**PrestaShop version(s) where the bug happened**
8.1.2

**PHP version(s) where the bug happened**
8.1.24
