### ISSUE TITLE
WebP - Not regenerating images

### ISSUE THREAD

**Issue by alkorotkovas** [PrestaShop/PrestaShop#33625]
![Screenshot 2023-08-15 at 10 26 55](https://github.com/PrestaShop/PrestaShop/assets/103935370/69b097c3-dc0a-4bfc-b328-81d7684078cd)
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Regenerate thumbnails do not work once WebP is selected to convert images from another format like jpg.
After regenerations, it says "The thumbnails were successfully regenerated", however by checking in the console it still says jpg.

"Erase previous" is selected.

### Expected behavior

Convert all images to WebP format.

### Steps to reproduce

Go to image settings
Select WebP
Regenerate all images and erase old ones.

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

7.4

**Comment by Hlavtox** [comment]
Do you have "Multiple image formats" enabled in "New & Experimental features" section or not?

If not = using the old system, webp images will be generated with JPG extension. So you can't see it on first glance.
If you enable the new format, you will be able to generate JPG, WEBP and AVIF at once with proper extensions.

**Comment by alkorotkovas** [comment]
Hi, @Hlavtox 
It's not enabled, I just enabled it. 
After trying to save WebP format it throws a warning: field Base format is required.
How should I deal with it?

**Comment by Hlavtox** [comment]
There is a tiny bug in the form, you need to select a base format below the webp.

![Snímek obrazovky 2023-08-15 144325](https://github.com/PrestaShop/PrestaShop/assets/6097524/c575eed4-37a5-450b-b35e-663a24eca639)

Beware that your theme must support multiple image formats - classic and hummingbird default themes do. :-)

**Comment by alkorotkovas** [comment]
Thanks, now works.
