### ISSUE TITLE
API modularization

### ISSUE THREAD

**Issue by Zoefinders** [PrestaShop/PrestaShop#33622]
Create a native module with all endpoints and scope. 
The rest will be in the CORE  - compatible 9.0 minimum.

**Comment by Zoefinders** [comment]
To begin this issue, this issues must be completed: 

- [Handle scopes on endpoints #33242](https://github.com/PrestaShop/PrestaShop/issues/33242)
- [Spike : definition of scopes#32231](https://github.com/PrestaShop/PrestaShop/issues/32231)
- Finish MVP

**Comment by jolelievre** [comment]
Moving the endpoints to a module won't be hard and has already been tested The most complex here is how we will export the PHPUnit tests though, since we need a PrestaShop instance to install the module into so the tests can be run..
