### ISSUE TITLE
Prestashop TAGS not working - Product list Empty - There are no products

### ISSUE THREAD

**Issue by Dori1993** [PrestaShop/PrestaShop#33630]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,
I have a problem and cant figure it out, i`ve been searching forums for 1 week now and cant find anny solution.
My prestashop store uses TAGS, wich worked perfecly before a update, afther a prestashop update to a more recent version, the tags does not work annymore.
Even if I put the products in tags,  when I search for the tags in the front office, the TAGS appear on the products page, but when I open the link wich is www.mystore.com/search?tag=TAGNAME  is does not work, it shows only that there are no products to show.
Currently using PRESTA 1.7.8.8 on our website www.gimihome.ro
You can find an example here: https://gimihome.ro/cautare?tag=Damigene
As I mentioned, the TAGS worked perfectly before the update.
Please help!

### Steps to reproduce

Hello,
I have a problem and cant figure it out, i`ve been searching forums for 1 week now and cant find anny solution.
My prestashop store uses TAGS, wich worked perfecly before a update, afther a prestashop update to a more recent version, the tags does not work annymore.
Even if I put the products in tags,  when I search for the tags in the front office, the TAGS appear on the products page, but when I open the link wich is www.mystore.com/search?tag=TAGNAME  is does not work, it shows only that there are no products to show.
Currently using PRESTA 1.7.8.8 on our website www.gimihome.ro
You can find an example here: https://gimihome.ro/cautare?tag=Damigene
As I mentioned, the TAGS worked perfectly before the update.
Please help!

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_tags

**Comment by sallemiines** [comment]
Hello @Dori1993 ,

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template and provide clear and concise steps to reproduce the bug**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
