### ISSUE TITLE
the override folder is completely emptied when upgrading from 1.7.8.x to 8.1.x

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#33634]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
upgrading from 1.7.8.9 to 8.1.1 all seems ok except for the override folder
after the upgrade the override folder is completely emptied

bye

### Steps to reproduce

1. upgrade from prestashop 1.7.8.9 or .10 to 8.1.1 using 1-click upgrade
2. after the upgrade go to see inside override folder, and you will see only the index.php file

bye

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

maofree

**Comment by sallemiines** [comment]
Hello @maofree ,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by venditdevs** [comment]
Not only to update 8.1.x, also to 8.0. It has been since the release of PS8.

**Comment by kpodemski** [comment]
@maofree do you mean that all the overrides are removed?

**Comment by venditdevs** [comment]
> @maofree do you mean that all the overrides are removed?

Yess, all of the files and mappings are gone in /overrides exept the readme_override.txt, index.php and .htaccess in the root folder of /overrides after updating to Prestashop 8, not matter what PS8 version you go to from 1.7.

**Comment by Maofree** [comment]
Hi
yes, the override folder become so

![1](https://github.com/PrestaShop/PrestaShop/assets/653230/b8114b06-98ef-4f2e-8d9f-1ba12428d6f1)

**Comment by Hlavtox** [comment]
@kpodemski Yes, I did not notice, this is a critical issue.

![Snímek obrazovky 2023-08-24 094600](https://github.com/PrestaShop/PrestaShop/assets/6097524/a8de0382-ee14-4842-a9eb-46223bce4764)
![Snímek obrazovky 2023-08-24 094617](https://github.com/PrestaShop/PrestaShop/assets/6097524/2bd27e4f-855e-43a6-9f8b-43f94c6e7ebb)

**Comment by gennaris** [comment]
I have explored this one a couple of days ago as it affected some of my PS upgrade scripts. 

Looks like issue is caused by PS 8.x releases being shipped with only **override/index.php** 
without other folders (**override/classes** , **override/controllers** etc.).

I managed to fix it in my operations with the PR I just submitted - Seems to work good to me.
