### ISSUE TITLE
Debug not showing errors on frontend 8.1

### ISSUE THREAD

**Issue by alkorotkovas** [PrestaShop/PrestaShop#33646]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When DEBUG is enabled, it does not show errors in the front end (shown in 1.7.8.9).

### Expected behavior

Errors displayed on the front end.

### Steps to reproduce

Enable Debug mode in 8.1 and try.

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

7.4

**Comment by kpodemski** [comment]
@alkorotkovas 

It may be related to your server configuration or third-party modules. I changed some code, and all I see in the front office is the following:
Parse error: syntax error, unexpected '$this' (T_VARIABLE) in /Users/kpodemski/code/prestashop81/classes/controller/FrontController.php on line 450

**Comment by hibatallahAouadni** [comment]
Hello @alkorotkovas 

Could you please provide some screenshots or screen record where it shows the diff between the two versions 🙏 
Thanks @kpodemski for your quick reply 🚀 

Thanks!

**Comment by alkorotkovas** [comment]
Hello @hibatallahAouadni 

Usually it showed error like this:
![erro2 PNG e9a298b766ad81e9e7136d0775132d82](https://github.com/PrestaShop/PrestaShop/assets/103935370/d55868f4-aa2c-4641-abed-b83f4f58f3ff)

Now, for example, if I have a 500 error after checkout, with enabled debug it does not show any error. (In 1.7 it showed).

**Comment by hibatallahAouadni** [comment]
Hello @alkorotkovas 

Well, I think it's related to your server configuration as @kpodemski mentioned above cause we already have some reported issues like this one #33306 where the debug mode launch Error 500 in FO.
So, closing the issue 😉 don't hesitate to ping me or @kpodemski if you can provide more infos.

Thanks!

**Comment by abd159** [comment]
same problem in my website [CPAP Tunisie](https://www.cpap-tunisie.tn/)

I edit
 Edit:

Debug mode on PrestaShop 8.0

PrestaShop Dashboard > Advanced Parameters > Performance > DEBUG MODE PANEL > Set it to YES 

while szcreen after activating in. Why ?
