### ISSUE TITLE
Upgrade PS from 8.0.4 to 8.1.1 fail with installed module psgdpr 2.0.1

### ISSUE THREAD

**Issue by PeNov** [PrestaShop/PrestaShop#33641]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,
upgrade PS from 8.0.4 to 8.1.1 fail with installed module psgdpr 2.0.1.

Here is log:
[log_804_to_811.txt](https://github.com/PrestaShop/PrestaShop/files/12367594/log_804_to_811.txt)

upgrade PS from 8.0.4 to 8.1.1 works after downgrade module psgdpr to 1.4.3.

Thank you
Best regards
PN

### Expected behavior

Upgrade without fail.

### Steps to reproduce

Standard 1-click upgrade process.

### PrestaShop version(s) where the bug happened

8.0.4 to 8.1.1

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

psgdpr 2.0.1, autoupgrade 4.16.2

**Comment by paulnoelcholot** [comment]
Hello,

I reproduce the issue with PrestaShop version 8.1.1, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/0e580dad-067b-41d9-b5b8-9cf31a4b0b51)

![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/72c31e58-278a-4cc8-bb73-366e23341f9e)

**Comment by LarsGMortensen** [comment]
Hi guys 

I also experienced an issue with db related to psgdpr when upgrading from 8.1.0 to 8.1.1

Prestashop version: 8.1.0
psgdpr version: 2.0.1
1-Click Upgrade version: 4.16.2
PHP version: 7.4.33
MySQL-version: 8.0.33-25


here is the log:

[CLEANING CACHE] File dev removed
[CLEANING CACHE] File prod removed
Cleaning file cache
API keys not present in parameters, generating
Keys generated using openssl_pkey_new, exporting private and public keys
Updating parameters file
Invalidating opcache for parameters file
Parameters file updated
Running opcache_reset
Initializing required environment constants
Checking version validity
Checking connection to database
Disabling all non native modules
[OK] SQL 8.1.1 SET SESSION sql_mode=''
[OK] SQL 8.1.1 SET NAMES 'utf8mb4'
[OK] PHP 8.1.1 : /* We forgot to update redirect_type in 8.1.0. This updates it, if it's not done already */ /* PHP:ps_811_update_redirect_type(); */
Updating database schema...
Executing: ALTER TABLE ps_authorized_application CHANGE name name VARCHAR(50) NOT NULL
Executing: ALTER TABLE ps_translation CHANGE `key` `key` TEXT NOT NULL COLLATE `utf8_bin`
Executing: ALTER TABLE ps_feature_flag CHANGE state state TINYINT(1) DEFAULT '0'
Executing: DROP INDEX id_customer ON ps_psgdpr_log
Executing: DROP INDEX idx_id_customer ON ps_psgdpr_log
Executing: ALTER TABLE ps_psgdpr_log CHANGE id_gdpr_log id_gdpr_log INT AUTO_INCREMENT NOT NULL, CHANGE id_customer id_customer INT NOT NULL, CHANGE id_guest id_guest INT NOT NULL, CHANGE client_name client_name VARCHAR(255) NOT NULL, CHANGE id_module id_module INT NOT NULL
Executing: ALTER TABLE ps_psgdpr_consent MODIFY id_gdpr_consent INT UNSIGNED NOT NULL
Executing: ALTER TABLE ps_psgdpr_consent DROP PRIMARY KEY
Executing: ALTER TABLE ps_psgdpr_consent CHANGE id_gdpr_consent id_gdpr_consent INT AUTO_INCREMENT NOT NULL, CHANGE id_module id_module INT NOT NULL, CHANGE active active TINYINT(1) NOT NULL, CHANGE error error TINYINT(1) NOT NULL, CHANGE error_message error_message VARCHAR(255) NOT NULL
15:36:51 CRITICAL [console] Error thrown while running command "prestashop:schema:update-without-foreign --env=prod". Message: "An exception occurred while executing 'ALTER TABLE ps_psgdpr_consent CHANGE id_gdpr_consent id_gdpr_consent INT AUTO_INCREMENT NOT NULL, CHANGE id_module id_module INT NOT NULL, CHANGE active active TINYINT(1) NOT NULL, CHANGE error error TINYINT(1) NOT NULL, CHANGE error_message error_message VARCHAR(255) NOT NULL':
SQLSTATE[42000]: Syntax error or access violation: 1075 Incorrect table definition; there can be only one auto column and it must be defined as a key" ["exception" => Doctrine\DBAL\Exception\DriverException { …},"command" => "prestashop:schema:update-without-foreign --env=prod","message" => """ An exception occurred while executing 'ALTER TABLE ps_psgdpr_consent CHANGE id_gdpr_consent id_gdpr_consent INT AUTO_INCREMENT NOT NULL, CHANGE id_module id_module INT NOT NULL, CHANGE active active TINYINT(1) NOT NULL, CHANGE error error TINYINT(1) NOT NULL, CHANGE error_message error_message VARCHAR(255) NOT NULL':\n \n SQLSTATE[42000]: Syntax error or access violation: 1075 Incorrect table definition; there can be only one auto column and it must be defined as a key """]
In AbstractMySQLDriver.php line 128:
An exception occurred while executing 'ALTER TABLE ps_psgdpr_consent CHANGE
id_gdpr_consent id_gdpr_consent INT AUTO_INCREMENT NOT NULL, CHANGE id_mod
ule id_module INT NOT NULL, CHANGE active active TINYINT(1) NOT NULL, CHANG
E error error TINYINT(1) NOT NULL, CHANGE error_message error_message VARCH
AR(255) NOT NULL':
SQLSTATE[42000]: Syntax error or access violation: 1075 Incorrect table def
inition; there can be only one auto column and it must be defined as a key
In Exception.php line 18:
SQLSTATE[42000]: Syntax error or access violation: 1075 Incorrect table def
inition; there can be only one auto column and it must be defined as a key
In PDOConnection.php line 141:
SQLSTATE[42000]: Syntax error or access violation: 1075 Incorrect table def
inition; there can be only one auto column and it must be defined as a key
prestashop:schema:update-without-foreign [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--id_shop [ID_SHOP]] [--id_shop_group [ID_SHOP_GROUP]] [--]


Errors:
Error during database upgrade. You may need to restore your database.
Error upgrading Doctrine schema

**Comment by SerenaButler** [comment]
Same here:

```
Executing: ALTER TABLE ps_psgdpr_consent CHANGE id_gdpr_consent id_gdpr_consent INT AUTO_INCREMENT NOT NULL, CHANGE id_module id_module INT NOT NULL, CHANGE active active TINYINT(1) NOT NULL, CHANGE error error TINYINT(1) NOT NULL, CHANGE error_message error_message VARCHAR(255) NOT NULL
15:16:04 CRITICAL [console] Error thrown while running command "prestashop:schema:update-without-foreign --env=prod". Message: "There is no active transaction" ["exception" => PDOException { …},"command" => "prestashop:schema:update-without-foreign --env=prod","message" => "There is no active transaction"]
```
