### ISSUE TITLE
Error in the translation pages for extra modules with php 8.1 and prestashop 8.1.1 - strtolower(): Passing null to parameter

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#33640]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
now I've found this little error in the translation pages for no native modules with php 8.1 and prestashop 8.1.1

Unknown error alla linea 1092 nel file /var/www/html/controllers/admin/AdminTranslationsController.php
[8192] strtolower(): Passing null to parameter #1 ($string) of type string is deprecated

![1](https://github.com/PrestaShop/PrestaShop/assets/653230/a7c9156d-c36d-4c9a-95dc-7199e52adf26)

bye

### Steps to reproduce

1. active the debug
2. go in the translation page
3. select the translation for a module, and select a non-native one
4. when the page will be opened you will see the errors

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

maofree

**Comment by venditdevs** [comment]
Looks like a duplicate of this issue: [https://github.com/PrestaShop/PrestaShop/issues/31731](url)

![image](https://github.com/PrestaShop/PrestaShop/assets/14218917/3ddb4a67-726f-4362-98d0-4f7940396df3)

**Comment by Maofree** [comment]
Hi
I think it is different, in this case the problem is around strtolower

**Comment by paulnoelcholot** [comment]
Hello!

I reproduce the issue with PrestaShop version 8.1.x, but only for non-native modules. @PrestaShop/committers  did you think it's a Prestashop bug or non native modules bug?

Thank you


[Translations • the future.webm](https://github.com/PrestaShop/PrestaShop/assets/112863083/1394300c-5d09-45b9-8967-b7a820a27646)

**Comment by Maofree** [comment]
Hi
you can see this problem for each not native modules, so it is a prestashop problem when it is not used the new translation mode

**Comment by hibatallahAouadni** [comment]
FYI: @Hlavtox we use your non-native module :wink: and wdyt of this issue?

**Comment by milor-nl** [comment]
I have the same errors but I have Prestashop 8.0.5  (with PHP 8.1.22).

when opening translation modules in BO:

Unknown error op lijn 1092 in bestand /home/pellets/domains/xxxxxx/public_html/controllers/admin/AdminTranslationsController.php
[8192] strtolower(): Passing null to parameter #1 ($string) of type string is deprecated

I can't translate any not native module now.

When trying to translate and save:    Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by venditdevs** [comment]
> Hi I think it is different, in this case the problem is around strtolower

It is exact the same error in my screenshot.

Even the situation @milor-nl describes is described is our situation. It;s the exact same problem we posted in may this year.

A workaround is to activate PHP 7.4 to translate the modules.

**Comment by kpodemski** [comment]
@maofree @venditdevs 

Try to use this file:
https://github.com/PrestaShop/PrestaShop/blob/8.1.x/config/smarty.config.inc.php

Replace the file from your installation with the one mentioned above.

**Comment by milor-nl** [comment]
@kpodemski   after replacing file the list of errors is gone but when trying to translate a module i can't save translations and I still got eror:  

Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by SharakPL** [comment]
Then it looks like the problem is with your server. Check Advanced > Configuration if there are some missing requirements. Maybe at least one of your modules requires ioncube. If so then make sure the proper version for your current php is installed.

**Comment by Maofree** [comment]
Hi @kpodemski 
after replacing the file nothing change, the errors list is still present. However I can save the translations

**Comment by venditdevs** [comment]
> Then it looks like the problem is with your server. Check Advanced > Configuration if there are some missing requirements. Maybe at least one of your modules requires ioncube. If so then make sure the proper version for your current php is installed.

30 servers and a couple of 100 webshops with the exact same problem here. Multiple people here commiting this issue which only occurs on PHP8.1 (multiple versions) and non native modules does not look like a server problem to me.

**Comment by milor-nl** [comment]
Same here 

 Advanced > Configuration                everything  Oke
 
Linux #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64
Apache/2
PHP-versie: 8.1.22
MySQL versie: 10.6.14-MariaDB-log
MySQL-engine: InnoDB
MySQL-driver: DbPDO
PrestaShop-versie: 8.0.5

**Comment by kpodemski** [comment]
Ok, now, when I'm not on my mobile device, I see that this is unrelated to the Smarty error.

It is also true what @venditdevs reports. It is impossible to save translations for modules using a legacy translation system.

I.e. I confirm the issue.
