### ISSUE TITLE
Persian alphabets changes to English in the URL

### ISSUE THREAD

**Issue by aminvatandoust** [PrestaShop/PrestaShop#33642]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I upgraded my PrestaShop store, which was in Persian, from 1.7.8.9 to 8.1.1 and found out all the URLs have been changed to English, I have "Accented URL" enabled in the "Traffic & SEO > SEO & URLs menu". We always have to enable this option when we want to have Persian URLs (products, categories, etc.).

I never had this problem in PS 1.6 or 1.7, You would just enable that option and start creating your products with Persian names and friendly URLs, and that's how it should work. Something has changed in PS8 which is absolutely wrong and it's a serious problem for shops that are in Persian.

Here is an example of the changed URL:

Original URL:
`site.com/1-پوشاک-مردانه`

New (**Wrong**) URL:
`site.com/1-pwshak-mrdanh`

It changes every charchter to English, one by one:
پوشاک -> pwshak
پ -> p
و -> w
ش -> sh
ا -> a
ک -> k

The main problem is that URL fields have been changed in the BO. So even if I disable the Accented URL, I can't get my old URLs back, unless there is an option to revert these changes. 

### Expected behavior

It shouldn't convert Persian Charchter to English when "Accented URL" is enabled. I want my URLs to be in Persian.

### Steps to reproduce

1. Install PS in Persian (Farsi), or add the Persian language to PS 8.1.1.
2. Enable the Accented URL in the SEO & URLs menu.
3. Create a product combi and write a Persian Name for it. (You can Try "فارسی" which is "Farsi").)

Previous edit: (3. Create a category/product and write a Persian Name for it. (You can Try "فارسی" which is "Farsi").)

(I'm not sure how/when this change applies, I think it takes time to change the URL, or maybe it's related to some sort of cache.)

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

7.4.33

**Comment by hibatallahAouadni** [comment]
Hello @aminvatandoust 

I didn't manage to reproduce the issue with PS81x, see the attached screenshot below:

<img width="592" alt="Screenshot 2023-08-22 at 09 45 38" src="https://github.com/PrestaShop/PrestaShop/assets/23308427/57cfa98a-1a0e-49d3-8f66-81017959aa7a">

Please check and feedback.

Thanks!

**Comment by aminvatandoust** [comment]
Hey @hibatallahAouadni 

I couldn't figure out how to reproduce the problem and what triggers it. As I mentioned before, it looks like it takes some time to applies. Can you please check if your category URL is still persian?

**Comment by florine2623** [comment]
Hello @aminvatandoust ,

I tested on my end, and I can't reproduce your issue either.
On my end, I tested with an installation in English and I added the Persian language to my store later on.

The URL is correct :
<img width="833" alt="Screenshot 2023-08-30 at 17 33 03" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/06bc31a8-5491-4b27-bd67-2ad93b3638ae">

<img width="1186" alt="Screenshot 2023-08-30 at 17 30 07" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/d828d9eb-7b72-4195-aca7-3928fdaacecc">

Make sure you check those areas when creation a product/category :

<img width="955" alt="Screenshot 2023-08-30 at 17 33 18" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/8a22bc8c-6b42-47ac-bcf8-f4ba35d5657b">

<img width="1151" alt="Screenshot 2023-08-30 at 17 31 10" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/316897ae-2a60-4e78-b92e-23403f2a35e3">

Could you please provide more infos to help us reproducing the issue.
Waiting for your feedback.

Thanks!

**Comment by hafkhami** [comment]
Hello @florine2623 , @hibatallahAouadni 
This problem occurs when the [Tools::str2url](https://github.com/PrestaShop/PrestaShop/blob/d97a0e1b1fbf33e71369941660bcbba490cd3472/classes/Tools.php#L1199)  function is called.

In PrestaShop 8 changes, this function uses the php [Transliterator](https://www.php.net/manual/en/class.transliterator.php) class. ([used here](https://github.com/PrestaShop/PrestaShop/blob/d97a0e1b1fbf33e71369941660bcbba490cd3472/src/Core/Util/String/StringModifier.php#L95))

For example, when PrestaShop is upgraded from version 1.7 to version 8, all Persian url for products and categories change.

To see this problem, you can do the following:

1- Create a Attribute in Persian language.
![image](https://github.com/PrestaShop/PrestaShop/assets/10551562/1a8a73ad-e1d3-4808-b2e1-41e77a7b7a8a)

2- Add a "Product with combinations" with this Attribute .
![image](https://github.com/PrestaShop/PrestaShop/assets/10551562/2fcab618-fa26-4e24-a6d3-95f022d4e408)


3- Check the address of the product with the combination.
![image](https://github.com/PrestaShop/PrestaShop/assets/10551562/d49ce718-60b0-4734-9701-b75cd2b18647)

Thanks

**Comment by sallemiines** [comment]
Ping @PrestaShop/committers it seems a little bit tech for me, help please :pray: :relaxed:

**Comment by hogo20** [comment]
helllo
I have this problem.
"product" and "category" URL, goes to Fingish 😐 (English +Persian ), I don't know when trigger that exactly. 
but attribute always is fingish. (even in new installation) 

Thank you for your efforts

**Comment by nicosomb** [comment]
I can't reproduce on fresh install (PrestaShop 8.1.1) with both french and persian. 
And it seems to be ok. 

![Capture d’écran 2023-09-07 à 15 47 26](https://github.com/PrestaShop/PrestaShop/assets/121870/973906ac-b98f-4324-a5d1-dd4fa6c6ce0c)
![Capture d’écran 2023-09-07 à 15 47 37](https://github.com/PrestaShop/PrestaShop/assets/121870/a515264d-d33d-4949-b46e-64df3efbda00)
![Capture d’écran 2023-09-07 à 15 48 04](https://github.com/PrestaShop/PrestaShop/assets/121870/6ed76fc5-8817-475e-845a-ac1914de4763)
![Capture d’écran 2023-09-07 à 15 48 19](https://github.com/PrestaShop/PrestaShop/assets/121870/134b2776-40ab-4823-a78b-55fcc7b2640a)

**Comment by nicosomb** [comment]
@aminvatandoust Could you please send us a video on a fresh install please?

**Comment by hafkhami** [comment]
> Hello @florine2623 , @hibatallahAouadni 
> This problem occurs when the [Tools::str2url](https://github.com/PrestaShop/PrestaShop/blob/d97a0e1b1fbf33e71369941660bcbba490cd3472/classes/Tools.php#L1199)  function is called.
> 
> In PrestaShop 8 changes, this function uses the php [Transliterator](https://www.php.net/manual/en/class.transliterator.php) class. ([used here](https://github.com/PrestaShop/PrestaShop/blob/d97a0e1b1fbf33e71369941660bcbba490cd3472/src/Core/Util/String/StringModifier.php#L95))
> 
> For example, when PrestaShop is upgraded from version 1.7 to version 8, all Persian url for products and categories change.
> 
> To see this problem, you can do the following:
> 
> 1- Create a Attribute in Persian language.
> ![image](https://github.com/PrestaShop/PrestaShop/assets/10551562/1a8a73ad-e1d3-4808-b2e1-41e77a7b7a8a)
> 
> 2- Add a "Product with combinations" with this Attribute .
> ![image](https://github.com/PrestaShop/PrestaShop/assets/10551562/2fcab618-fa26-4e24-a6d3-95f022d4e408)
> 
> 
> 3- Check the address of the product with the combination.
> ![image](https://github.com/PrestaShop/PrestaShop/assets/10551562/d49ce718-60b0-4734-9701-b75cd2b18647)
> 
> Thanks

Hello @nicosomb 
Please test the product with the combination

**Comment by nicosomb** [comment]
@hafkhami you're right, I have this URL : `/fa/accueil/21-40-qsdfsqfqsf.html#/26-arsy-1`

I confirm the bug.

**Comment by MatShir** [comment]
On a fresh install, it only affects product with combination?

**Comment by amirrzd** [comment]
As @hafkhami mentioned, "This problem occurs whenever the [Tools::str2url](https://github.com/PrestaShop/PrestaShop/blob/d97a0e1b1fbf33e71369941660bcbba490cd3472/classes/Tools.php#L1199) function is called."
