### ISSUE TITLE
Upgrade TranslationTool to use Crowdin API v2 (v1 will soon be shut down)

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#33655]
### Discussed in https://github.com/PrestaShop/PrestaShop/discussions/33654

<div type='discussions-op-text'>

<sup>Originally posted by **matks** August 18, 2023</sup>
### The problem

Crowdin v1 api will be shut down in November 2023 and we still use it to create Language Packs.

See: https://developer.crowdin.com/assets/api/api_v1_docs_crowdin.pdf

### The solution

Upgrade to Crowdin API v2

**Comment by matks** [comment]
Related ticket on private repository https://github.com/PrestaShopCorp/TranslationTool/issues/105

**Comment by jolelievre** [comment]
Related PR https://github.com/PrestaShopCorp/TranslationTool/pull/145
