### ISSUE TITLE
impossible to install or update module in V8.0.4

### ISSUE THREAD

**Issue by ECC64** [PrestaShop/PrestaShop#33653]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Prestashop 8.0.4 - PHP 7.4
Only original modules except: Creative elements and Shipping Costs By Postal Codes
The error returned is: Failed to install module module-1. Employee->email property is empty
Whether installing or updating a module

### Steps to reproduce

Go to Modules
Click : install module
choose the module and click OK

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

7.4

### Your company or customer's name goes here (if applicable).

Mobilier Inox CB

**Comment by matks** [comment]
Hello I suggest you check https://github.com/PrestaShop/PrestaShop/issues/32603#issuecomment-1550869896

**Comment by ECC64** [comment]
thank's, i find the soluce : reinit module ps_mbo
you can close the issue
best regards
Patrick
