### ISSUE TITLE
translators.prestashop-project.org is in degraded mode

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#33651]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

https://translators.prestashop-project.org/ is not working.

It should present the list of sorted translators of the project, similarly to https://translators.prestashop.com/

https://translators.prestashop.com/ is the old version and https://translators.prestashop-project.org/ is the new

Right now on https://translators.prestashop-project.org/ we see the content of the https://github.com/PrestaShop/TopTranslators README

### UPDATE

See https://github.com/PrestaShop/PrestaShop/issues/33651#issuecomment-1702663955

### Expected behavior

https://translators.prestashop-project.org/ should present the list of sorted translators of the project, similarly to https://translators.prestashop.com/ . But up to date 😄 

### Steps to reproduce

1. Go to https://translators.prestashop-project.org/
2. See the content is not what is expected

### PrestaShop version(s) where the bug happened

N/A

**Comment by matks** [comment]
When this ticket is solved, we will be able to
- redirect https://translators.prestashop.com to https://translators.prestashop-project.org/
- shut down the legacy application behind https://translators.prestashop.com

**Comment by matks** [comment]
Issue is the GH Action that deploys the site fails
https://github.com/PrestaShop/TopTranslators/actions/runs/5899381854/job/16005540953
```
# Run curl "https://api.crowdin.com/api/project/prestashop-official/status?key=${ENV_CROWDIN_API_KEY}&json" | jq -r '.[] | [.name, .approved_progress]| @csv' > ./data/languages.csv

  curl "https://api.crowdin.com/api/project/prestashop-official/status?key=${ENV_CROWDIN_API_KEY}&json" | jq -r '.[] | [.name, .approved_progress]| @csv' > ./data/languages.csv
  
  shell: /usr/bin/bash -e {0}
  env:
    ENV_CROWDIN_API_KEY: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   145    0   145    0     0    1[3](https://github.com/PrestaShop/TopTranslators/actions/runs/5899381854/job/16005540953#step:3:3)3      0 --:--:--  0:00:01 --:--:--   133
100   1[4](https://github.com/PrestaShop/TopTranslators/actions/runs/5899381854/job/16005540953#step:3:4)[5](https://github.com/PrestaShop/TopTranslators/actions/runs/5899381854/job/16005540953#step:3:5)    0   145    0     0    133      0 --:--:--  0:00:01 --:--:--   133
jq: error (at <stdin>:[7](https://github.com/PrestaShop/TopTranslators/actions/runs/5899381854/job/16005540953#step:3:8)): Cannot index boolean with string "name"
Error: Process completed with exit code 5.
```

**Comment by Progi1984** [comment]
I have a PR on my local. I can fix it when I come back from holidays.

**Comment by matks** [comment]
I fixed a first problem: there was no secret ENV_CROWDIN_API_KEY

But steps after this fail, mostly because of outdated npm dependencies. It seems a broad upgrade of NPM scripts is needed. The GH Action runs NPM8 and fails to find some very old dependencies.

However because ENV_CROWDIN_API_KEY is a secret, you cannot test with a PR of your fork. You need to create a branch on the original repository. Secrets are not shared with forks in GitHub Actions.

**Comment by eternoendless** [comment]
I did some part of the work but it seems that a complete update of webpack will be necessary https://github.com/PrestaShop/TopTranslators/pull/58

**Comment by matks** [comment]
I was able to make https://translators.prestashop-project.org/ run again ; it is now live but it is in Degraded Mode. See https://github.com/PrestaShop/TopTranslators/issues/65

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/TopTranslators/pull/68
