### ISSUE TITLE
1-Click Upgrade

### ISSUE THREAD

**Issue by Bonobernat** [PrestaShop/PrestaShop#33667]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Good morning.
We have tried several times to update Prestashop from version 1.7.8.8 to version 8.x, but it has not been possible, it stops and a warning "exceeded execution time" appears, I have it in 360, I increase it to 3600 and it gives me the Same problem and I can't update.
If it helps you in Back Office, advanced parameters, information, this warning appears - Missing files (1) Backoffice/autoupgrade/index.php.
Can you help me solve it?
Thank you

### Steps to reproduce

Delete the version that was installed and download the latest version from your page, install the module and configure all the options that it asks you to do the update but it cannot be updated.

### PrestaShop version(s) where the bug happened

1.7.8.8 a 8.x

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

1-Click Upgrade 4.16.2

### Your company or customer's name goes here (if applicable).

berelishop

**Comment by venditdevs** [comment]
Is it possible that your overall max execution time is limited? You have a setting above all user (php) settings which will overrule your own max settings, you'll need to contact your system/server administrator the check of change that.

**Comment by hibatallahAouadni** [comment]
Hello @venditdevs 

Could you please check this issue #33641 it seems similar to yours.
Waiting for your feedback.

Thanks!

**Comment by Bonobernat** [comment]
Hello The time is limited to 360, but when the administrator saw the error, I extended it to 3600, but it could not be updated either since it gave the same error

**Comment by Bonobernat** [comment]
It looks similar but not the same, we want to upgrade from 1.7.8.8 to version 8.x

**Comment by paulnoelcholot** [comment]
Hello @Bonobernat,

What is your version of ps_GDPR? 

Thanks

**Comment by Bonobernat** [comment]
Good afternoon.The Prestashop version (which was already answered in the questionnaire you asked for) is 1.7.8.8, something else?Kind regards,Bernat Bono

**Comment by paulnoelcholot** [comment]
@Bonobernat 

Not your version of Prestashop. But the version of ps_gdpr. ps_gdpr is a native module in Prestashop.

**Comment by Bonobernat** [comment]
If Prestashop tells me that GitHub is a collaborator and developer of 1 click upgarde, contact me directly and download the latest version to solve the problem.I connect to Github, download the latest version 4.16.2, install it and the problem remains the same, I think you would be more honored by not answering absurd things and extending the solution that you do not have.I recommend that you visit the Prestashop forums to understand how badly you are doing it.

Kind regards.Bernat Bono

**Comment by kpodemski** [comment]
@Bonobernat 

You are welcome to hire somebody to help you out with this issue. It clearly comes from your environment, not from the module itself.

You can find more details here: https://www.prestashop-project.org/support/

I'm closing this ticket since you need to follow the Code of Conduct of the project.

**Comment by Bonobernat** [comment]
El código de conducta te lo tendrías que aplicar tu, ya que no has solucionado el problema. Cerrando el ticket, lo único que demuestras es tu incapacidad para resolver el problema, que según Prestashop habéis creado ya que el fallo viene de la aplicación que se descarga de github. Que tengas suerte en la vida. Doy por cerrado este ticket, no se atenderán más correos.        Mail: ***@***.***   Tel. 651 909 417 – 651 909 418      Barcelona  De: Krystian Podemski ***@***.***>Fecha: jueves, 24 de agosto de 2023, 15:59Para: PrestaShop/PrestaShop ***@***.***>CC: Bonobernat ***@***.***>, Mention ***@***.***>Asunto: Re: [PrestaShop/PrestaShop] 1-Click Upgrade (Issue ***@***.*** are welcome to hire somebody to help you out with this issue. It clearly comes from your environment, not from the module itself.You can find more details here: https://www.prestashop-project.org/support/I'm closing this ticket since you need to follow the Code of Conduct of the project.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
