### ISSUE TITLE
Content of "password" email changed - seems like an error.

### ISSUE THREAD

**Issue by LarsGMortensen** [PrestaShop/PrestaShop#33661]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have just upgraded from PS 8.1.0 to 8.1.1

In the Danish version of the "password" it used to send the message "Din adgangskode er blevet opdateret." (Your password has been changed.)

But now, it merely just writes: "E-mail adresse: {email}"

So, there is no longer a confirming message letting the user know that the password was changed. It now simply just sends the user an email stating what his/her own email-addresss is.
This seems pretty odd.
So I am guessing it's a bug.

Also, the subject line of the email reads: "Din nye adgangskode", which means "Your new password". However, the e-mail doesn't contain any password (for obvious reasons), so it seems odd to choose this subject for that e-mail. Maybe it would be better to use a subject like "Din adgangskode blev nulstillet" (Your password has been reset).

### Expected behavior

As a user, I would expect it to send me a message that the password had been successfully changed (just like it did in PS 8.1.0), and I find it very odd to recieve an email with the content: "Email: <my own email address>"

### Steps to reproduce

1. Open PS 8.1.1 in Danish (possibly also other languages?)
2. Go to the customer-account-login-page
3. Click "forgot password"-link to make it send you an email with a link to reset the password
4. Click the link in the email, and set a new pasword
5. Check the email that will now be sent to your email-address (the email template "password")

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

7.4.33

**Comment by paulnoelcholot** [comment]
Hello @LarsGMortensen,

I tested in English :

![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/6bd45174-421c-4ac8-a01d-1b3d8f7907e0)

And in Danish : 

![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/464d870d-710b-44ac-9c30-8710fb09ce2d)

Did I miss someting?

Thank for your feedback

**Comment by hibatallahAouadni** [comment]
Hello @LarsGMortensen 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!
