### ISSUE TITLE
Uncaught Exception: Template "PrestaShopBundle:Admin/Configure/ShopParameters/TrafficSeo/Meta/Blocks:shop_urls_configuration.html.twig is not defined

### ISSUE THREAD

**Issue by rangoliFR** [PrestaShop/PrestaShop#33669]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I got this error while accessing seo link (BO):

CRITICAL13:00:39 | php | Uncaught Exception: Template "PrestaShopBundle:Admin/Configure/ShopParameters/TrafficSeo/Meta/Blocks:shop_urls_configuration.html.twig" is not defined in "@PrestaShop/Admin/Configure/ShopParameters/TrafficSeo/Meta/Blocks/shop_urls_configuration.html.twig" at line 19.{     "exception": {} }

### Expected behavior

No error

### Steps to reproduce

https://www.domain.com/admin/index.php/configure/shop/seo-urls/?_token=XXX

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1.22

**Comment by hibatallahAouadni** [comment]
Hello @rangoliFR 


Thanks for your issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template to submit a complete bug report**.

Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it.

Thanks!
