### ISSUE TITLE
Product::getAttributesResume() must return values that are safe to use in foreach

### ISSUE THREAD

**Issue by alisamie97** [PrestaShop/PrestaShop#33678]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

This method: `Product::getAttributesResume()` is used in this method: `ProductLazyArray::shouldShowOutOfStockLabel` in a `foreach` loop.

As per PHP docs, we must use arrays or objects in `foreach` loops. I realized that in `Product::getAttributesResume()` if there are no combinations for a product, it will return `false` and it is not what a `foreach` expects.

The fix is very simple and exists in the same method here: https://github.com/PrestaShop/PrestaShop/blob/169403873a23c1b3822a70d88d1f1dc903cba5d2/classes/Product.php#L2658C17-L2658C17

We just need to return empty array.

### Steps to reproduce

This is not a bug because the PHP core will fix it on the fly and skip. But in order to reproduce this issue, you need to enable `error_log` in a server and then you will see this warning in logs.

### PrestaShop version(s) where the bug happened

1.7.8.9

**Comment by kpodemski** [comment]
Hi @stifler97 

It makes sense, so the change is to change `false` to `[]` here?
https://github.com/PrestaShop/PrestaShop/blob/8.1.x/classes/Product.php#L2739

right? are you interested in submitting a PR? If so, you could do that against the 8.1.x branch.

**Comment by Hlavtox** [comment]
@stifler97 @kpodemski https://github.com/PrestaShop/PrestaShop/pull/32735

**Comment by hibatallahAouadni** [comment]
@kpodemski @Hlavtox did you reproduce the issue? if so, please edit the steps section and add clear and concise steps 🙏
