### ISSUE TITLE
[BO] PPV2  Friendly URL is not updated automatically after updating a product name

### ISSUE THREAD

**Issue by sallemiines** [PrestaShop/PrestaShop#33670]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When enabling the Force update of friendly URL in shop parameters > Product Settings , the Friendly URL is not updated automatically after updating a product name 
 

### Expected behavior

We only update the URL field content in the frontend thanks to JS.
On name input change the value from name input is sluggified and automatically put in the friendly URL input.

We only do this automatic change when the product is **offline** to avoid breaking production URLs.

Label in configuration form: When enabled, friendly URL will be updated on every name change for offline product only

The button `Reset URL` should be renamed into `Generate URL from name` and it should be enabled when the name is modified and the URL doesn't match anymore

### Steps to reproduce

1. Go to 'Shop parameters > Product Settings' page
2. Enable force update friendly URL
3. Go to product page and create a product > save 
4. Update name of  the created product > name of the product is update 
==> Friendly URL should updated automatically

https://github.com/PrestaShop/PrestaShop/assets/31663369/7d140dae-f910-4297-9db9-43aae1288d59

### PrestaShop version(s) where the bug happened

PS 81x

### PHP version(s) where the bug happened

PHP 8.1.0

**Comment by kpodemski** [comment]
Duplicate:
https://github.com/PrestaShop/PrestaShop/issues/33432

**Comment by kpodemski** [comment]
cc @PrestaShop/qa-functional

**Comment by boubkerbribri** [comment]
> Duplicate: #33432

Yes it's the same but it's for the new product page
