### ISSUE TITLE
RTL cannot read CSS files  

### ISSUE THREAD

**Issue by maxdo200** [PrestaShop/PrestaShop#33672]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

**There is an error in supporting CSS files when using the RTL interface**

![Screenshot 2023-08-21 152006](https://github.com/PrestaShop/PrestaShop/assets/23308427/649841e0-a91e-4f9f-9cdc-2d13f703a471)

### Steps to reproduce

**1- Catalog
2-Products
3-Create new product**
A window will appear that does not support RTL

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

PHP Version 7.4.29

**Comment by hibatallahAouadni** [comment]
Hello @maxdo200 

Your issue seems similar to this one #29918
Please check and feedback.

Thanks!

**Comment by sallemiines** [comment]
Hello @maxdo200 

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. 
Please note that you can always create a new one if further information pops up.

Thank you
