### ISSUE TITLE
Show command error page

### ISSUE THREAD

**Issue by WeR-Best** [PrestaShop/PrestaShop#33674]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Click on the order list order information, the page is wrong.

### Expected behavior

![截屏2023-08-21 17 29 24](https://github.com/PrestaShop/PrestaShop/assets/37808758/d384ba9f-c09c-48e0-950e-a0de3f40f192)

### Steps to reproduce

Click on an order to view the order details

### PrestaShop version(s) where the bug happened

1.7.7.3

### PHP version(s) where the bug happened

7.2.34

### If your bug is related to a module, specify its name and its version

BNP Paribas - Axepta 1.3.1

**Comment by kpodemski** [comment]
Hello @ideatechfr 

You need to contact the author of the BNP Paribas - Axepta 1.3.1 module. This problem is not caused by the core of the PrestaShop.
