### ISSUE TITLE
Color product attributes not selectable when option to hide out of stock combinations is enabled

### ISSUE THREAD

**Issue by korsgaard** [PrestaShop/PrestaShop#33689]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When more than to attributes are active, and when the option to hide combinations not in stock is enabled and color attributes are enabled as the first attribute, you cannot select colors that doesn't have a size like the one currently selected. See the attached screen recording.

https://github.com/PrestaShop/PrestaShop/assets/20941567/c115e856-73ee-4213-9544-4d9a55940bfe

### Expected behavior

It should be possible to select another color and then another size is selected.

### Steps to reproduce

1. Go to product
2. Try to switch to a combination without the same size at currently selected

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

7.3

**Comment by korsgaard** [comment]
I can add that it works fine as long as you select the color attribute as radio buttons or dropdown instead.

**Comment by hibatallahAouadni** [comment]
Hello @korsgaard 

Do you encounter this issue only with mobile version? and did you encounter this issue with older version of PrestaShop?
Waiting for your feedback.

Thanks!

**Comment by korsgaard** [comment]
Both, it was just easier to do screenrecording from mobile. We've started this shop on 8.0 and just found out, so I cannot speak for previous versions.

**Comment by sallemiines** [comment]
Hello @korsgaard 

is your issue look similar to this one [issue-33720](https://github.com/PrestaShop/PrestaShop/issues/33720) 

Please check and feedback !

**Comment by korsgaard** [comment]
Yes, it seems like the same issue, though I thought it was only color combinations.

**Comment by florine2623** [comment]
Hello @korsgaard ,

I'm closing your issue as it is a duplicate.
You can follow and comment directly on https://github.com/PrestaShop/PrestaShop/issues/33720 if needed !

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/33720
