### ISSUE TITLE
[BO] Add new zip theme - Error appears :  file size is not allowed

### ISSUE THREAD

**Issue by sallemiines** [PrestaShop/PrestaShop#33683]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When try to add a new theme using l'option Import from your computer , the size of imported file is not supported it's only allowed for 2 MIB .

### Expected behavior

Import theme zip successfully

### Steps to reproduce

1. Go to Improve > Design > Theme & Logo
2. Import from your computer > Click to Browse and select your theme > Click to save
==> Error message appears **The file is too large. Allowed maximum size is 2 MiB.**

[classic-rocket.zip](https://github.com/PrestaShop/PrestaShop/files/12409468/classic-rocket.zip)  to check with it 

**NB**
 - Error appears with PS 805 , PS 811 ,PS 81x ,develop
- OK with PS 1789 , PS 810

https://github.com/PrestaShop/PrestaShop/assets/31663369/4ffbec3e-54b4-4e06-8cc4-e4cd101c61f6

### PrestaShop version(s) where the bug happened

PS 805 , PS 811 ,PS 81x , develop

### PHP version(s) where the bug happened

PHP 810

**Comment by hibatallahAouadni** [comment]
Hello @sallemiines 

I didn't manage to reproduce the issue with PS81x and develop, see the attached screen record below:

[issue_33683.webm](https://github.com/PrestaShop/PrestaShop/assets/23308427/883f4bd8-afab-4e90-a0cd-5c4a4fe84d22)

Please check your Upload Max File size under BO>Advanced Parameters>Performance and feedback.

Thanks!

**Comment by sallemiines** [comment]
Closing the issue as it seems related to my configuration :pray:
