### ISSUE TITLE
Prevent directory listings in the htaccess for Apache

### ISSUE THREAD

**Issue by maxime-morel** [PrestaShop/PrestaShop#33699]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Some hosting providers, by default, do not prevent directory listings. We frequently encounter merchants whose directories can be viewed because of the absence of an `index.php` file, particularly when their hosting hasn't been configured correctly to restrict directory listings. Consequently, when these directories are accessed online, a list of files becomes visible. This poses a security risk, especially in cases where custom directories contain configuration files or other resources that shouldn't be publicly accessible.

### Expected behavior

The directly listing should be prevented in the htaccess.

### Steps to reproduce

To reproduce the issue, the Apache server should not enforce the Indexes.
The accessing to a directory (https://example.test/directory_notprotected) will [display the list of files](https://ibb.co/xDp4CnY).

### PrestaShop version(s) where the bug happened

All versions

### Your company or customer's name goes here (if applicable).

Profileo

**Comment by hibatallahAouadni** [comment]
Hello @maxime-profileo 

PrestaShop 1.5 & 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).

Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

Thank you

**Comment by maxime-morel** [comment]
Hello @hibatallahAouadni , it seems to be a confusion from my side, I entered the starting version. The issue is concerns all versions including 8.X
Thanks,

**Comment by maxime-morel** [comment]
Hello,
For information :
To reproduce that, `Options +indexes` should be set as the configuration in the vhost. Then you can see the listing of directories in the vhost. It's for default configurations in some hosting providers that do not enforce `Options -indexes`

**Comment by sallemiines** [comment]
Hello @maxime-profileo 

is this issue is similar to this created one [issue-33722](https://github.com/PrestaShop/PrestaShop/issues/33722)

waiting for your feedback ! 
Thank you  !

**Comment by maxime-morel** [comment]
Hello @sallemiines .
This is two different issues, but they can be reproduced with the same server configuration.
issue-33699 is protecting the listing of directories/files globally
issue-33722 is forbidding the access to all resources from the web in `/templates` directory.
Thanks !

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers can someone please reproduce the issue and validated cause we have a PR available to be tested :wink: :pray: 

Thanks in advance!
