### ISSUE TITLE
Can not edit the product after importing combinations

### ISSUE THREAD

**Issue by jucenaa** [PrestaShop/PrestaShop#33704]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I imported some products into Prestashop and, as the problem had already occurred in the version I was using previously, I decided to test whether the products were editable, and everything was fine.
After importing the combinations, i was no longer able to edit the products I had previously imported, even those without combinations. It doesn't allow you to edit categories, images or anything like that

![Captura de ecrã 2023-08-23 200536](https://github.com/PrestaShop/PrestaShop/assets/121062341/685b4928-7647-4abe-a6fe-c6c3c905f259)

I looked in a few places and the answer was that the 'smarty_lazy_cache' table was missing, but I have this table.

### Steps to reproduce

1. Go to import, in advanced parameters
2. import the products and test whether they are editable
3. Import the combinations and test again to see if you can still edit them (I couldn't).

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.0.29

**Comment by sallemiines** [comment]
Hello @jucenaa 

Could you please switch to Classic theme or disable the BO overrides and check again if the imported combinations are not editable ? 

waiting for your feedback ! 
Thank you

**Comment by jucenaa** [comment]
Hi,@sallemiines 
I'm using the classic theme.
But it doesn't work.
I deactivated and reactivated the new product management page 3 days ago and 2 of the products are editable again. But the rest are not

**Comment by jucenaa** [comment]
> Olá@jucenaa
> 
> Você poderia mudar para o tema Clássico ou desativar as substituições de BO e verificar novamente se as combinações importadas não são editáveis?
> 
> aguardando seu feedback! Obrigado

Hi,@sallemiines
I'm using the classic theme.
But it doesn't work.
I deactivated and reactivated the new product management page 3 days ago and 2 of the products are editable again. But the rest are not

**Comment by florine2623** [comment]
Hello @jucenaa ,

Could you send a sample of your Product file and Combination file ?

Waiting for you feedback
Thanks!

**Comment by bybzibybzi** [comment]
> > Olá@jucenaa
> > Você poderia mudar para o tema Clássico ou desativar as substituições de BO e verificar novamente se as combinações importadas não são editáveis?
> > aguardando seu feedback! Obrigado
> 
> Hi,@sallemiines I'm using the classic theme. But it doesn't work. I deactivated and reactivated the new product management page 3 days ago and 2 of the products are editable again. But the rest are not

Hi @jucenaa, i think i might have found solution. I've been dealing with similar issue. What worked out for me was disabling "New product managment", and then i was able to get the error message "Product must be in default category". I then went to Catalog / Categories, found my product's category and assigned parent category. I could finally edit product afterwards!

**Comment by keeper7** [comment]
Looks like there is a problem with validations. Javascript doesnt show validation error but crash instead.
I found this when i tried to upload file and add description with more than 32 characters. When debug is on then response is 500 with error code.

**Comment by djoelleuch** [comment]
Hello @jucenaa ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
