### ISSUE TITLE
Catalog - Categories not accessible after upgrading to PS 8.0.4

### ISSUE THREAD

**Issue by ogi99** [PrestaShop/PrestaShop#33703]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After upgrading to PS 8.0.4 it is impossible to access Categories or Monitoring in the Catalog section.
I have attached a pdf showing all information displayed when Debug was enabled and the Information section of the advanced parameters.
It only affects the BO area.
[Category issues.pdf](https://github.com/PrestaShop/PrestaShop/files/12421374/Category.issues.pdf)

### Expected behavior

being able to access and modify the categories.

### Steps to reproduce

1. Go to the BO
2. Select Catalog
3. Select Categories  - its not working

### PrestaShop version(s) where the bug happened

8.0.4

### If your bug is related to a module, specify its name and its version

8.1.22

### Your company or customer's name goes here (if applicable).

Kinkysabine

**Comment by hibatallahAouadni** [comment]
Hello @ogi99 

I see that you encounter this issue after upgrading your shop, could you please provide your shop version before the upgrade and the version of 1-ClickUpgrade module 🙏 
Waiting for your feedback.

Thanks!

**Comment by MatShir** [comment]
A module might not be compatible with PS 8.0.4. Try to disable them, see if the error is still persistent

**Comment by ogi99** [comment]
Hi,

 

the shop runs on PS 8.0.4,

PHP 8.1.22

1-Click Upgrade Module v4.16.2

 

Thanks

 

Olaf

 

 

 

Von: Hibatallah Aouadni ***@***.***> 
Gesendet: Freitag, 25. August 2023 01:36
An: PrestaShop/PrestaShop ***@***.***>
Cc: ogi99 ***@***.***>; Mention ***@***.***>
Betreff: Re: [PrestaShop/PrestaShop] Catalog - Categories not accessible after upgrading to PS 8.0.4 (Issue #33703)

 

Hello  <https://github.com/ogi99> @ogi99

I see that you encounter this issue after upgrading your shop, could you please provide your shop version before the upgrade and the version of 1-ClickUpgrade module 🙏
Waiting for your feedback.

Thanks!

**Comment by Hlavtox** [comment]
@kpodemski null values in lang tables again, we need to normalize it during upgrade or cast it, so it works with nulls.

**Comment by Hlavtox** [comment]
@ogi99 Run this and tell me if it fixes your issue. ;)

```
UPDATE `c5ob_category_lang` SET `description`='' WHERE `description` IS NULL;
```

**Comment by ogi99** [comment]
Hi Daniel,I assume this is a command line command.Please can you tell me how to do it?Thanks in advance OlafVon meinem iPhone gesendetAm 25.08.2023 um 18:21 schrieb Daniel Hlavacek ***@***.***>:﻿
@ogi99 Run this and tell me if it fixes your issue. ;)
UPDATE c5ob_category_langSETdescription='' WHERE description IS NULL;

**Comment by Hlavtox** [comment]
@ogi99 Hi, you need to run in in database admin. I suggest hiring a specialist to fix the database inconcistencies. 👍

@hibatallahAouadni You can close this. :-)

**Comment by sallemiines** [comment]
Closing the issue :wink:
