### ISSUE TITLE
Edit API access (1/5): Generate Client ID

### ISSUE THREAD

**Issue by Zoefinders** [PrestaShop/PrestaShop#33712]
### Description
As a shop admin
I want to be able chose between automatically manage the Client ID or fill it in myself 
So to have a secure client id 

### Acceptance tests
**Acceptance test 1: Fill in client id myself**

**Given** i am on " Edit %API access name" 
**When** I fill "Client ID" filed and click in "save" button
**Then** the Client ID is change 

**Acceptance test 2: "Automatically manage the client ID** 
**Given** i am on " Edit %API access name" 
**When** I click on "renegerate an client ID" and click in "save" button
**Then** the Client ID is change 

### Additional context
![Image](https://user-images.githubusercontent.com/99200820/262938037-00efe5b7-dfaa-45ad-b3b3-774833411e60.png)

### Additional context

[Figma link](https://www.figma.com/file/uaRxD74AMc98kLlyyhy0RM/Authorization-server-management?type=design&node-id=1041-655&mode=design&t=rU5kcuGFOARrcKYs-0)

**Comment by Progi1984** [comment]
@Zoefinders Closed but where are QA Scenarios ?

**Comment by Zoefinders** [comment]
@Progi1984 finaly we have cancelled this feature ;)
