### ISSUE TITLE
API access configuration - Delete API access

### ISSUE THREAD

**Issue by Zoefinders** [PrestaShop/PrestaShop#33711]
### Description
As a shop admin
I want to be able delete API Access
So that I can fully configure API access 

### Acceptance tests
**Acceptance test 1: "View" boutton**

**Given** i am on " API access list" 
**When** 
1. I click on " Delete" API acces" button in "This is an app name" line in droo/down menu 

**Then** the API access must be delate and you shouldn't see it in the list 

### QA Scenarios

* Functional > BO > Advanced Parameters > Authorization Server > Delete API Access

|**Action** | **Additional** | **Expected** |
|-----------|-----------|-----------|
| | **PRE-COND : Enable experimental feature : Authorization server** | |
In BO, Go to Advanced Parameters > New & Experimental Features |   | New & Experimental Features Page is displayed correctly.
Set checked the checkbox “Authorization server” |   | The checkbox “Authorization server” is check
Click on Save button |   | A modal appeared
Click on Enable button in the modal | | The message “Update successful” is displayed
| | **PRE-COND : Add an API Access** | |
In BO, Go to Advanced Parameters > Authorization Server |   | Authorization Server Page is displayed correctly.<br>No records found in the table
Click on the button "Add new API access"|   | New API access Page is displayed correctly
Fill the form with following data (Client ID : "Client XYZ", Client Name: "ClientName ABC")<br>Click on "Generate client secret & Save" button| | There is 1 application in the list<br>The message “The API access and Client secret has been generated sucessfully” is displayed<br>The message "Client secret: " is available<br>The button Copy put the client secret in the clipboard
| | **Main Test** | |
In BO, Go to Advanced Parameters > Authorization Server |   | Authorization Server Page is displayed correctly.<br>1 record found in the table
On the first row, click on the delete button | | A modal appeared
Click on the Confirm Button in the modal | | The message “Successful deletion” is displayed<br>No records found in the table
| | **POSTCOND : Disable experimental feature : Authorization server** | |
In BO, Go to Advanced Parameters > New & Experimental Features |   | New & Experimental Features Page is displayed correctly.
Set unchecked the checkbox “Authorization server” |   | The checkbox “Authorization server” is unchecked
Click on Save button |   |  The message “Update successful” is displayed

### Additional context

[Figma link](https://www.figma.com/file/uaRxD74AMc98kLlyyhy0RM/Authorization-server-management?type=design&node-id=1041-655&mode=design&t=rU5kcuGFOARrcKYs-0)

**Comment by WahbiPS** [comment]
Done with the Grid integration
