### ISSUE TITLE
Missing directory protection (from htaccess) for templates directory

### ISSUE THREAD

**Issue by maxime-morel** [PrestaShop/PrestaShop#33722]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The `/templates` directory is not protected with an `htaccess`

### Expected behavior

The `/templates` directory should be protected with an `htaccess` as all other code directories (eg: `/src`)

### Steps to reproduce

1. Enable listing directories on the server
2. Access to `/templates`

Modules PrestaScan Security is for exemple listing this directory as unprotected:
https://ibb.co/JRSFZKB

### PrestaShop version(s) where the bug happened

Seen in 8.0.5

### Your company or customer's name goes here (if applicable).

Profileo

**Comment by sallemiines** [comment]
Hello @maxime-profileo ,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by maxime-morel** [comment]
Hello,
For information :
To reproduce that, `Options +indexes` should be set as the configuration in the vhost. Then you can see the listing of directories in the vhost. It's for default configurations in some hosting providers that do not enforce `Options -indexes`
