### ISSUE TITLE
Can't find products in products page in backoffice

### ISSUE THREAD

**Issue by MockoB** [PrestaShop/PrestaShop#33724]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I've started uploading products and tried sorting the products by category. Choose an empty category from the dropdown list  and there is no way now how to view products in the backoffice. Tried it on another browser which I never opened prestashop with and the products page is still empty.

### Expected behavior

I need to view all my products in the products page to be able to edit or sort them.

### Steps to reproduce

1. Create some categories.
2. Upload some products.
3. Choose an empty category from the sorting drop down list in the products page.
4. And voila, there is no way to view your products anymore. Just the shopping bag with two buttons "create new product" or "import a list of products"

![backoffice](https://github.com/PrestaShop/PrestaShop/assets/25778255/4fd1336d-190b-47bf-bcda-4811ec5ad020)

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.1.22

**Comment by sallemiines** [comment]
Hello @MockoB 

Following your steps I didn't manage to reproduce your issue ! 

![image](https://github.com/PrestaShop/PrestaShop/assets/31663369/c204ee45-b01d-4ce2-9a08-1064f5261113)

Could you please provide us a screenrecorder ? 

Waiting for your feedback ! 
Thank you

**Comment by MockoB** [comment]
I am uploading screen record, unfortunately I can't reproduce the issue, because I can't see any products in my list.

https://github.com/PrestaShop/PrestaShop/assets/25778255/33744497-1a09-447a-839c-50382347db1d

As you may see in the categories list, there are already some products uploaded.

**Comment by Hlavtox** [comment]
@MockoB Product page v1 or v2?

If old page, enable new product page in New & Experimental features section and let us know.

**Comment by MockoB** [comment]
Hi @Hlavtox thank you so much!
It was the new product page, when switched it off I can see my products. Unfortunately when I turn it on i still can't see any products.
Any chance using again the new product page view again, because I got used to it?

**Comment by Hlavtox** [comment]
@MockoB As a temp solution, create a new product with that category as default, if you remeber what category it was. The you should be able to reset the filter.

It sucks though, I will check it during the weekend 👍

**Comment by MockoB** [comment]
Thank you @Hlavtox, I don't remember, but there are not many categories, so I will experiment.
I know it's not the place, but I saw on the monitoring page, that all my products are in the list without description and summary. The reason is, that there is no description in English. I don't use English in my store, just Bulgarian. It's not an big issue, but I suppose the monitoring page will be flooded in a while. Or I have to put some description in the English page also ?

**Comment by gfourquet** [comment]
I had the same problem.
- Use a filter with a category on page products
- Go to catégories and delete this category
- back to product list => No prodict available (because the filter on a deleted category is still active
Guillaume

**Comment by Hlavtox** [comment]
I am getting a slighly different behavior, but it "works for me".

- Create empty category
- Go to product list and filter by this category - empty grid ✅
- Delete this category
- Go back to product list - filter is broken, but I can still use the page.

![Snímek obrazovky 2023-08-28 103833](https://github.com/PrestaShop/PrestaShop/assets/6097524/adc378c9-4942-4f25-bf6e-c3ba3c652f1a)

**Comment by sallemiines** [comment]
Hello @MockoB 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #32858.
It's fixed on 8.1.1 :tada: 

Thank you

**Comment by sallemiines** [comment]
Duplicate of #32858
