### ISSUE TITLE
The module "My Account Block" is not functioning ( Ps 1.7.8.9).

### ISSUE THREAD

**Issue by Mnce57** [PrestaShop/PrestaShop#33725]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On my website, I am encountering an issue with accessing and utilizing the "My Account Block" module's functionalities. Despite successfully completing the registration process, I am unable to access the features of the module on the client (site) side.

### Expected behavior

I expect to be able to access and use the functionalities of the "My Account Block" module on the website after successfully registering. This would allow me to perform various actions related to my account seamlessly.

### Steps to reproduce

Logging into the website: When attempting to log into the website ([https://monptitcolis-secret.fr/fr/connexion?back=my-account]), the registration process works correctly on the backend. However, there is no access granted on the frontend of the website.

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

"My Account Block".

### Your company or customer's name goes here (if applicable).

Mnce

**Comment by sallemiines** [comment]
Hello @Mnce57 

Please provide us  a screen recorder or clearer information! the steps you mentioned are not enough to reproduce the problem ! 

Waiting for your feedback  !

Thank you  !

**Comment by Mnce57** [comment]
On the website, a client without an account has the option to register at: "https://monptitcolis-secret.fr/fr/connexion?create_account=1". The registration process is completed correctly in the Prestashop back office. However, on the client side of the website, nothing happens; the screen remains unchanged. Despite this, the client receives registration confirmation emails. The client does not have any access to their customer account on the website.

**Comment by sallemiines** [comment]
Thanx  @Mnce57 for your feedback ! 
Do you mean that the problem is with the client registration - connexion ? 

At my side looks OK , you can see the screen recorder and check if this describe your issue ! 

**REGISTRATION FROM FO AND CONNECT FO** **OK** 

https://github.com/PrestaShop/PrestaShop/assets/31663369/7de90b34-7a4d-465d-a290-4c16c9d029cd

**REGISTRATION FROM BO AND CONNECT FO** **OK** 

https://github.com/PrestaShop/PrestaShop/assets/31663369/9896b971-f55e-430e-bb69-0af3c30b0b1b



waiting for your feedback ! 
Thank you

**Comment by Mnce57** [comment]
Customer registrations are successful, but they are unable to access their customer accounts on our site. Please perform a test on our website "https://monptitcolis-secret.fr/fr/connexion?back=my-account" (create an account with a random username), then attempt to log in or access your account to better understand the anomaly.

**Comment by sallemiines** [comment]
I check on your site it's LGTM ! 

https://github.com/PrestaShop/PrestaShop/assets/31663369/587f89be-3ed8-47a8-bbb4-e08fae848db3

IF it's ok ! please inform us to close the issue ! 

Thank you

**Comment by Mnce57** [comment]
For my part , during a connection test in private browsing mode, the anomaly disappears. However, during a regular connection, it's impossible to access the customer account on the website. The issue on my side has been partially resolved, but I don't understand where the blockage could be located. Thank you for your assistance,

**Comment by Hlavtox** [comment]
@Mnce57 You are probably using some badly made caching module or your server caches it somehow.

**Comment by hibatallahAouadni** [comment]
Hello @Mnce57 

Thanks @Hlavtox for yor quick reply :rocket: 
Closing the issue as it seems to be related to cache.

Thanks!
