### ISSUE TITLE
Error when editing specific prices

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#33737]
### Describe the bug and add attachments

When you set up specific prices like this.

![Snímek obrazovky 2023-08-28 065140](https://github.com/PrestaShop/PrestaShop/assets/6097524/9d485067-5b6e-4cc7-b120-8bac3e1e7f20)

And try to change groups on specific price ID 2 to Visitor, you get an error.

![Snímek obrazovky 2023-08-28 065749](https://github.com/PrestaShop/PrestaShop/assets/6097524/80cc4aef-145e-4bcb-84d0-919bea6ec94a)

```
Integrity constraint violation: 1062 Duplicate entry '1-0-0-0-0000-00-00 00:00:00-0000-00-00 00:00:00-1-0-0-0-1-1-0' for key 'id_product_2' (500 Internal Server Error)
```

### Expected behavior

It should throw the same error like it does when creating a new speficic price. 

![Snímek obrazovky 2023-08-28 065705](https://github.com/PrestaShop/PrestaShop/assets/6097524/be5beaf1-fcd2-433a-b31a-7658aeef5882)

### Steps to reproduce

1. Make sure to enable new product page.
2. Create a product, set no tax rule, set price to 1000.
3. Create specific price - Visitor group, uncheck "Keep original price" and type 90.
4. Create specific price - All groups, uncheck "Keep original price" and type 89.
5. Open the speficic price with All groups and try to change the it to Visitor group - see error.

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
It is fixed on 8.1.3 :

https://github.com/PrestaShop/PrestaShop/assets/16019289/27cbddc1-7e64-4e84-aefa-3ac040afde1b
