### ISSUE TITLE
Error code in the "Featured products" module in PrestaShop 8.1.0

### ISSUE THREAD

**Issue by Angar90** [PrestaShop/PrestaShop#33730]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In PrestaShop 8.1.0, when the debug mode is enabled and I try to configure the "Featured products" module, I see this error:
Unknown error on line 114 in file /vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_modifier.php
[16384] Using php-function "implode" as a modifier is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier.

Screenshot:
https://prnt.sc/65zIfzkeyZEg

### Steps to reproduce

1.Install PrestaShop 8.1.0
2.Enable the debug mode.
3.Configure the "Featured products" module.

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.1.21

### If your bug is related to a module, specify its name and its version

ps_featuredproducts v2.1.4

**Comment by hibatallahAouadni** [comment]
Hello @Angar90 

I didn't manage to reproduce the issue with PS805, 810 and 811, see the attached screen record below:

[issue_33730.webm](https://github.com/PrestaShop/PrestaShop/assets/23308427/5dd11baa-93ba-4ec5-8252-5af5d7b41297)

Did you apply some overrides? Please check and feedback.

Thanks!

**Comment by Angar90** [comment]
I see that I have this problem only in PrestaShop 8.0.4 and 8.1.0, but in PrestaShop 8.1.1 everything is ok, so it might be a local problem on my server.

**Comment by paulnoelcholot** [comment]
Hello,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you
