### ISSUE TITLE
Bad default status of Specific price field

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#33738]
### Steps to reproduce

1. Make sure to ~~enable new~~ USE OLD product page.
2. Open any product, click "New specific price".
3. Field looks like this:

![Snímek obrazovky 2023-08-28 070210](https://github.com/PrestaShop/PrestaShop/assets/6097524/1041f1d9-93d8-44d8-bbc6-ed7bc6aa7553)

4. Uncheck "keep original price", type some price, save it.
5. Click "New specific price" again.
6. Field looks like this, which is wrong. It must be disabled if that checkbox is checked.

![Snímek obrazovky 2023-08-28 070258](https://github.com/PrestaShop/PrestaShop/assets/6097524/f59e8620-6a59-4c6f-8ec8-96bab10a1004)

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

8.1

**Comment by RosaBenouamer** [comment]
@hibatallahAouadni @sallemiines in this case if the check default price is setted but that we enter a price in the field (which should be grayed out) does it used or ignored ?

**Comment by Hlavtox** [comment]
@RosaBenouamer If that field is not disable, it will get casted to zero.

When you save it like this:
![Snímek obrazovky 2023-08-28 120036](https://github.com/PrestaShop/PrestaShop/assets/6097524/e85a797e-1789-4031-86bb-48dc26937028)

You get this:
![Snímek obrazovky 2023-08-28 120048](https://github.com/PrestaShop/PrestaShop/assets/6097524/8a23f318-7dbf-4362-a583-f3e51ffbdf82)

And you get zero price in front office:
![Snímek obrazovky 2023-08-28 120059](https://github.com/PrestaShop/PrestaShop/assets/6097524/bf392aae-0ee7-4ff4-b15e-09c09d3587bc)

------------------

BTW, this field is buggy also on catalog price rule page - https://github.com/PrestaShop/PrestaShop/issues/33609 and https://github.com/PrestaShop/PrestaShop/issues/33486

**Comment by Hlavtox** [comment]
@RosaBenouamer And I don't know why you ping QA for expected behavior? 🤔

**Comment by RosaBenouamer** [comment]
@Hlavtox not for expected behavior but for actual behavior to give some priority :-)

**Comment by RosaBenouamer** [comment]
@Hlavtox Why do you have some print screen of product V1 when the problem is in V2 ? Not sure to understand.

**Comment by Hlavtox** [comment]
@RosaBenouamer Ha, because I am stupid and the bug is on product page v1. 😄 Sorry.

@MatShir Should I close it? Do we care about V1 page?

**Comment by MatShir** [comment]
Let's close it ! ;)
