### ISSUE TITLE
Release drafter not working on zip step

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#33749]
The release drafter step of the CI is no longer working when merging a dev branch into the master.

Here are some error reports:

- https://github.com/PrestaShop/productcomments/actions/runs/5953972519
- https://github.com/PrestaShop/ps_facetedsearch/actions/runs/5683725438
- https://github.com/PrestaShop/ps_linklist/actions/runs/5354084130

As a result, we need to manually build the zip and finalize the release.

**Comment by M0rgan01** [comment]
https://prestashop.slack.com/archives/C03LFE4KV6K/p1690479969255129 can be a beginning of a solution, to be tested

**Comment by matks** [comment]
Hi guys can we move the issue to the Core repository just like all other issues? I looked for this issue for 5 minutes 😄 because it was not in the same place as all other issues

**Comment by M0rgan01** [comment]
We will test a fix with https://github.com/PrestaShop/productcomments/pull/183

**Comment by M0rgan01** [comment]
I think the problem comes from the PR https://github.com/PrestaShop/.github/pull/7. When going from actions/download-artifact@v1 to actions/download-artifact@v2, the tree structure changed. See https://github.com/actions/download-artifact/tree/releases/v2#compatibility-between-v1-and-v2.

**Comment by matks** [comment]
It seems like productcomments 6.0.1 fixes the problem we had on 6.0.0 thanks to work from @leemyongpakvn and @M0rgan01 .

However to fully fix the impacted modules, we need
- to search for all module releases done between https://github.com/PrestaShop/.github/pull/7 and today
- verify for each of them if ZIP archive is correct on GitHub
- verify for each of them if ZIP archive hosted on Distribution API (and distributed to prestashop instances) is correct
- fix wrong ZIP archives, preferably by releasing new patch version

**Comment by matks** [comment]
@M0rgan01 @MatShir I transferred the issue to the Core repository

**Comment by matks** [comment]
Releases performed in June, July and August

* [dashtrends](https://github.com/PrestaShop/dashtrends): [v2.1.2](https://github.com/PrestaShop/dashtrends/releases/tag/v2.1.2)
* [blockwishlist](https://github.com/PrestaShop/blockwishlist): [v3.0.1](https://github.com/PrestaShop/blockwishlist/releases/tag/v3.0.1)
* [productcomments](https://github.com/PrestaShop/productcomments): [Release 6.0.1](https://github.com/PrestaShop/productcomments/releases/tag/v6.0.1)
* [autoupgrade](https://github.com/PrestaShop/autoupgrade): [v4.16.2](https://github.com/PrestaShop/autoupgrade/releases/tag/v4.16.2)
* [ps_linklist](https://github.com/PrestaShop/ps_linklist): [v6.0.3](https://github.com/PrestaShop/ps_linklist/releases/tag/v6.0.3)
* [ps_imageslider](https://github.com/PrestaShop/ps_imageslider): [v3.1.3](https://github.com/PrestaShop/ps_imageslider/releases/tag/v3.1.3)
* [ps_facetedsearch](https://github.com/PrestaShop/ps_facetedsearch): [v3.13.1](https://github.com/PrestaShop/ps_facetedsearch/releases/tag/v3.13.1)

**Comment by matks** [comment]
Dashtrends GH Build action worked correctly https://github.com/PrestaShop/ps_imageslider/actions/runs/5211389389
Ps_imageslider worked https://github.com/PrestaShop/ps_imageslider/actions/runs/5211389389

Blockwishlist failed https://github.com/PrestaShop/blockwishlist/actions/runs/5831378802
Ps_linklist GH Build action failed https://github.com/PrestaShop/ps_linklist/actions/runs/5354084130
Autoupgrade failed https://github.com/PrestaShop/autoupgrade/actions/runs/5740510871
Ps_facetedsearch failed https://github.com/PrestaShop/ps_facetedsearch/actions/runs/5811246443

In spite of this all GH releases have a ZIP so I guess people who did the releases built the ZIP manually.

**Comment by kpodemski** [comment]
@M0rgan01, you've reopened this issue, isn't it ready? I see that productcomments were released successfully?

**Comment by M0rgan01** [comment]
@kpodemski I was waiting for confirmation on the search for a potential buggy release. Now it is good
