### ISSUE TITLE
Newsletter Subscribe

### ISSUE THREAD

**Issue by CompusoftTecnic** [PrestaShop/PrestaShop#33743]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [ ] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

the prestashop module 'newsletter subscribe' doesn't work. 
When you write an email and click to 'subscribe', nothings happen

### Steps to reproduce

1. Go to footer sirocorecambios.com
2. introduce an email
3. click to subscribe

### PrestaShop version(s) where the bug happened

1.7.7.8

### PHP version(s) where the bug happened

7.4.33

**Comment by HartLarsson** [comment]
have you configured the module correctly to enable the welcome mail sending and so on?
Seems you still using a theme, have you check if in the theme is all configured correctly and you theme support the default module?
Seems the GDPR module is missing too or is not configured with your newsletter module.

**Comment by CompusoftTecnic** [comment]
![imagen](https://github.com/PrestaShop/PrestaShop/assets/51398161/4bdfb43a-194b-465b-87b9-0b97d69e5052)

its configuret but it doesnt work with the newsletter module.

**Comment by hibatallahAouadni** [comment]
Hello @CompusoftTecnic 

Thanks @HartLarsson for your quick reply :rocket: 
@CompusoftTecnic did you well configure your BO>Advanced Parameters>email? if so, could you please share some screenshots of your configuration :pray: 

Thanks!

**Comment by CompusoftTecnic** [comment]
![imagen](https://github.com/PrestaShop/PrestaShop/assets/51398161/ed2ec0d7-3a80-45d2-8c5b-0ed93c16f531)

the email works on other forms.

**Comment by florine2623** [comment]
Hello @CompusoftTecnic ,

You need to check the following module :
<img width="996" alt="Screenshot 2023-08-30 at 15 10 00" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/218a9eb4-5426-472a-8e38-c4985749ef1e">

If a customer has subscribed, you should see his email address here :
<img width="1209" alt="Screenshot 2023-08-30 at 15 09 53" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/af377338-08a3-4ef3-a1f7-b323f58a41a3">

Please check and feedback.

Thanks!

**Comment by CompusoftTecnic** [comment]
> Hello @CompusoftTecnic ,
> 
> You need to check the following module : <img alt="Screenshot 2023-08-30 at 15 10 00" width="996" src="https://user-images.githubusercontent.com/16019289/264352692-218a9eb4-5426-472a-8e38-c4985749ef1e.png">
> 
> If a customer has subscribed, you should see his email address here : <img alt="Screenshot 2023-08-30 at 15 09 53" width="1209" src="https://user-images.githubusercontent.com/16019289/264352793-af377338-08a3-4ef3-a1f7-b323f58a41a3.png">
> 
> Please check and feedback.
> 
> Thanks!

I know, I am attaching an export of subscribed users, it only works when you verify the subscription to the newsletter when you register a new user, if you just want to subscribe, the module does not work since 2021. It is a website made by someone else and transferred,

![imagen](https://github.com/PrestaShop/PrestaShop/assets/51398161/a419253c-90cc-4e62-a075-0682a5b04ce7)

**Comment by CompusoftTecnic** [comment]
I tried with the original Prestashop theme (classic Version) and it works correctly. It seems like an incompatibility with theme autima3.

**Comment by HartLarsson** [comment]
> I tried with the original Prestashop theme (classic Version) and it works correctly. It seems like an incompatibility with theme autima3.

i told you :)
Theme must support the template of the newsletter module. If not supporting any email insertedinto the form will not processed and saved into the database and you can see in the module "Newsletter Subscription" an empty list of subscribers as  @florine2623 told in a previous post.

Hart

**Comment by sallemiines** [comment]
Glad to hear :tada: 
Closing the issue as it's related to your theme and not the Core!
