### ISSUE TITLE
Autoupgrade 8.0.4 to 8.0.5 not possible

### ISSUE THREAD

**Issue by ComonSoft** [PrestaShop/PrestaShop#33740]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Click on One click upgrade, got information message "Your current version of the module is out of date. Update now [Modules > Module Manager > Updates)". Cannot upgrade, button is not activated.

![capt1](https://github.com/PrestaShop/PrestaShop/assets/13507563/44a4cf0a-389f-435c-9109-bb983f47f13a)

When clicking to upgrade module, no upgrade is available. Dead loop!

![capt2](https://github.com/PrestaShop/PrestaShop/assets/13507563/93f32052-d7ea-4282-8cd0-1ea6c9bfa868)

### Expected behavior

Button active to upgrade Prestashop, or upgrade module available.

**Workaround**: download and install manually the latest version of the module (4.16.2 at date we reported). But it's not a simple and accessible solution for all merchants.

### Steps to reproduce

1. Click on One click upgrade
2. verify all settings are satisfied 
3. Click on link in formation message "Your current version of the module is out of date. Update now [Modules > Module Manager > Updates)
4. No update available for module autoupdate

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

autoupgrade 4.15.0

### Your company or customer's name goes here (if applicable).

Com'onSoft

**Comment by matks** [comment]
Autoupgrade 4.16.2 is the latest version https://github.com/PrestaShop/autoupgrade/releases/tag/v4.16.2

It's strange it does not appear in your back office

**Comment by ComonSoft** [comment]
Yest strange. And I already explained a workaround by installing the latest version ;-). But this is not easy for merchants

**Comment by Hlavtox** [comment]
@matks I suspect the module manager list cache. 🔍

**Comment by venditdevs** [comment]
> ade, got information message "Your current version of th

It probably is, you need to delete the content in the /var/cache folder to see the updates (i assume the Distribution API-Client module is installed in this case), we've mentioned this cache issue before in one or two another ticket. It's quite annoying.

**Comment by ComonSoft** [comment]
I've tried to clear /var/cache/, and yes Distribution API-Client  is activated, same issue.

**Comment by aniszr** [comment]
Hello @ComonSoft 

I couldn't reproduce this issue, I installed Autoupgrade module v4.15.0 in PS 8.0.4, the module manager automatically ask to upgrade the module to v4.16.2!

I recommend you to clear the cache of BO and browser it may solve the problem

See attached screenrecord:

https://github.com/PrestaShop/PrestaShop/assets/92626242/4a9d2d26-e9cd-4bde-9ef7-6451ea4463ad

Thanks!

**Comment by ComonSoft** [comment]
As I already explained, I did everything you ask for, but nothing works  :-( . We had to use the workaround described above. We are in local Windows environment, may be it comes from that!

**Comment by JBPSA** [comment]
Can you upgrade other modules?

May your local environment is blocking incoming/outgoing connections to the API endpoint.

**Comment by sallemiines** [comment]
Hello @ComonSoft 

Your issue is fixed with PS8.1.1 and Autoupgrade 4.16.2 and a part of your issue is a duplicate of #27896
Closing the issue as it's fixed :tada: 

PS: please upgrade your module then upgrade your shop, if you still encounter the same issue please ping us here or open a new issue with more infos to investigate it.

Thanks!

**Comment by KungMatsW** [comment]
Hi
I have the same kind of issue. I can't upgrade my 8.0.2.

- I do have the latest v4.16.2 autoupgrade modul.
- All list points is green checked
- I have cleared the /var/cache as told above.
- I have cleared the cache from back office
- I have uninstalled the v4.16.2 autoupgrade modul and reinstalled it.
- I have deleted the autopupgrade folder and installed it again.
NOTHING helps!

![111](https://github.com/PrestaShop/PrestaShop/assets/118338163/aca7a156-5331-4f36-98cd-12e72ea3521c)
![333](https://github.com/PrestaShop/PrestaShop/assets/118338163/407e1732-9e84-4281-8c34-7dffb28680f7)
![222](https://github.com/PrestaShop/PrestaShop/assets/118338163/b51fbccb-0bc1-4220-9f26-95ad6ab0324a)

**Comment by ComonSoft** [comment]
Same issue when trying to upgrade from 8.1.4 to 8.1.5, and 1-Click Upgrade v5.0.0 :-( I add to install 1-Click Upgrade v5.0.1 manually.
