### ISSUE TITLE
[SOLVED] PS 8.1.1 error [PrestaShop\PrestaShop\Core\Domain\Product\Exception\ProductConstraintException codice 50]

### ISSUE THREAD

**Issue by scardovi** [PrestaShop/PrestaShop#33755]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I was manually updating the quantity of a standard product (without variants) and I got the error in question.
I haven't had any errors with other products.

The database was imported from a 1.6.1.24 installation with the module https://addons.prestashop.com/it/data-migration-backup/27376-1-clicca-per-migrare-o-aggiornare.html
![Immagine 2023-08-29 103454](https://github.com/PrestaShop/PrestaShop/assets/11573474/0af7766b-64d5-405e-b3cf-50be59d54f5b)

### Expected behavior

It should update the availability without showing errors

### Steps to reproduce

1 go to the product sheet
2 go to the inventory tab
3 change quantity

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

7.4

**Comment by scardovi** [comment]
The product I wish tu upgrade has <iframe> content in description and shop <iframe> parameter was disabled.

I suggest to replace the error message with a more specific one for users.

**Comment by hibatallahAouadni** [comment]
Well, it's good suggestion! 
Ping @kpodemski could you please transfer this issue to Discussion tab :pray:
