### ISSUE TITLE
when I delete the last product in a category, I can't see the products in the prestashop 8.1.0 catalog anymore

### ISSUE THREAD

**Issue by masztalweb** [PrestaShop/PrestaShop#33750]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

when I delete the last product in a category, I can't see the products in the prestashop 8.1 catalog anymore

### Steps to reproduce

1. Create new category "test"
2. Added one product "test" into new category "test".
3. Delete product "test" into category named "test".
4. I received Manage your products "0".
5. I can't select anymore product in catalog. 

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

7.4

**Comment by masztalweb** [comment]
I forgot to add that this is when filtering products by category in Backofice in the catalog tab.

**Comment by MatShir** [comment]
Seems to be related to https://github.com/PrestaShop/PrestaShop/issues/33724

**Comment by masztalweb** [comment]
Yes is this the same problem

**Comment by florine2623** [comment]
Hello @masztalweb ,

I'm not sure I understand well your issue.
If I delete a product from a category, it is normal that the product can't be selected anymore.

Here's my screen record :

https://github.com/PrestaShop/PrestaShop/assets/16019289/2ca44912-7adb-4e50-a060-e549e4e88551


Could you send me a screenrecord or the steps you are following please ?
(do not forget to hide your admin link)

**Comment by masztalweb** [comment]
Unfortunately, I have already removed version 8.1.0. the same problem is also in 8.1.1. Only there is no problem in version 8.04 and below.

Simply, after removing the last product in a given category with filtering by category, all products in the catalog > Products disappear. You can't do anything anymore, the category and product filters are not working, there are 0.

**Comment by sallemiines** [comment]
Hello @masztalweb 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #32858.
It's fixed on 8.1.1 :tada: 

Thank you

**Comment by sallemiines** [comment]
Duplicate of #32858

**Comment by MatShir** [comment]
@sallemiines are you sure it is fixed. It's the second report about. The PR linked is milestone 8.1.0 but the issus is 8.1.1 (my fault, sorry). Have double-check the issue well fixed ? 🙏
