### ISSUE TITLE
Several admin tabs are missing translation domain and wording

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#33763]
### Describe the bug and add attachments

Translations of some admin menu items are not getting updated because the tabs are missing their domain.

**From my install**
- AdminSecuritySessionEmployee
- AdminSecuritySessionCustomer
- AdminSelfUpgrade
- and others, full list - `SELECT * FROM ps_tab WHERE wording = '' OR wording IS NULL;`

### Expected behavior

These tabs must have a translation domain.

### Steps to reproduce

1. Get any 8.1.x
2. Run this in phpmyadmin: `UPDATE ps_tab_lang SET name = 'Blabla';`
3. Go to International > Translations (Blabla > Blabla, but you will find it. 😄)
4. Install / Update the language you are currently using in backoffice.
5. Check that all left menu tabs have been correctly updated, but all the tabs that don't have proper domains are still `Blabla`.
 
![Snímek obrazovky 2023-08-30 105226](https://github.com/PrestaShop/PrestaShop/assets/6097524/bb0d82d5-ff51-464b-926f-4a2a4ecb3dca)

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello @Hlavtox ,

I reproduce the issue with PrestaShop version 8.1.x and develop, I'll add this to the backlog so it can be fixed.

https://github.com/PrestaShop/PrestaShop/assets/16019289/f6028ea9-4b79-44a2-b0f8-5122b22a8f38

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
