### ISSUE TITLE
Replace annotations from core to remove sensio/framework-extra-bundle

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#33769]
Clean all the annotations:
- `@AdminSecurity`
- `@DemoRestricted`
- `@ModuleActivated`

They must be replaced by some attributes following the latest Symfony conventions (attributes instead of annotations) we can then remove our dependency to `sensio/framework-extra-bundle`

A first PR was already done for DemoRestricted https://github.com/PrestaShop/PrestaShop/pull/33057 the steps to follow are:
- turn the annotation into an attribute
- replace the usage of the annotation by the attribute everywhere in the core (this can be done thanks to rektor)

Once all the references have been replaced we can remove our dependency with `sensio/framework-extra-bundle` which is a breaking change. But to help the transition for modules we need to test something: 
- can a module use **both** the annotation **AND** the attribute in the same file?
- this would allow the module to be compatible with
  - version prior to 9.0 thanks to the annotation (the attribute would not exist and therefore not be used)
  - version after 9.0 thanks to the attribute (then it's the annotation that becomes useless since the framework can't interpret it anymore)
- the main question is to know if it's possible to keep both annotation and attributes without causing an error like Attribute not existing, invalid use statement, ...

Tasks:

- [x] Replace `@DemoRestricted`
- [ ] Replace `@ModuleActivated`
- [ ] Replace `@AdminSecurity`
- [ ] Remove `sensio/framework-extra-bundle` from composer
- [ ] Perform a test/check on one of our core module (probably one with Symfony controller that uses `@AdminSecurity`) and check if the double annotation/attribute can work in a single module version

**Comment by MatShir** [comment]
Waiting for SF 6.4 decision @fabienvallon !

**Comment by WahbiPS** [comment]
Blocked, waiting for [Upgrade to Symfony 6.0 at least, if possible 6.3 or 6.4 depending on latest available version at the time#34006](https://github.com/PrestaShop/PrestaShop/issues/34006)
