### ISSUE TITLE
BIG ISSUE with ps_events after each module updates logs out the account in the ps_accounts module

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#33776]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
yesterday I've updated, on 25 websites, ps_events from 2.3.1 to 2.3.2
today the a my customer alerts me telling me that paypal was no longer in the payment list
in fact ps_account had disassociated the addons account

this problem happened on 12 sites out of the 25 to which I made this update.
this thing happened before with another update but in that case I thought it was due to an update of ps_accounts since that's what disconnects and creates problems.
now I understand that the problem is created by each update of the ps_events module

it happened on 12 sites out of the 25 to which I made this update.
this thing happened before with another update but in that case I thought it was due to an update of ps_accounts since that's what disconnects and creates problems.
now I understand that the problem is created by each update of the ps_events module

the problema happens the day after the ps_events upgrade. The same happens some weeks ago

This problem happens on 1.7.8.9 and on 8.1.1 with php 7.4 and 8.1
PrestaShop Account v6.2.6 and with PrestaShop Account v5.4.8

![1](https://github.com/PrestaShop/PrestaShop/assets/653230/02becfb3-b610-48ef-96ad-841cca82c838)
![2](https://github.com/PrestaShop/PrestaShop/assets/653230/b0ddf25a-6429-41f3-bb64-94a15da7199a)

these are similar topic already created, I didn't quite understand this problem
https://github.com/PrestaShop/PrestaShop/issues/33331
https://github.com/PrestaShop/PrestaShop/issues/32237

bye

### Steps to reproduce

1. already installed ps_events 2.3.1
2. already installed ps_accounts
3. wait  24 hours and che if ps_accounts is without associations
4. the problem happens in random mode, not happens each times. On 25 websites only 12 have this problem

### PrestaShop version(s) where the bug happened

8.1.1 and 1.7.8.9

### PHP version(s) where the bug happened

7.4 and 8.1

### If your bug is related to a module, specify its name and its version

ps_events and ps_accounts

### Your company or customer's name goes here (if applicable).

maofree

**Comment by kpodemski** [comment]
Hello @maofree 

As you know, these modules are not part of the open-source project. I let the team responsible for these modules know about your issues.

**Comment by Maofree** [comment]
ok thanks

this error is causing me several problems, because it happens randomly and on different sites that I manage, so every time I'm forced to double check if they are connected and if they weren't to reconnect them. Then paypal stops working and therefore becomes a problem for shopkeepers who don't know about the problem unless notified by customers.
now I know that the day after I update these modules I will have to check them again
