### ISSUE TITLE
Error security.user.provider.concrete.oauth2

### ISSUE THREAD

**Issue by DanSilva926** [PrestaShop/PrestaShop#33772]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The service "PrestaShopBundle\Security\OAuth2\Repository\ClientRepository" has a dependency on a non-existent service "security.user.provider.concrete.oauth2".

I found another user with the same problem, but no solution :  https://www.prestashop.com/forums/topic/1077378-problema-con-single-sing-on-en-backoffice-tras-actualizaci%C3%B3n/

error recording:  https://streamable.com/xzxoxh

### Expected behavior

update successfully

### Steps to reproduce

Updade 8.0.4 to 8.0.5

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.1.22

**Comment by florine2623** [comment]
Hello @DanSilva926 ,

Can you provide the steps to reproduce your issues and screenshots please ?
Thanks!

**Comment by DanSilva926** [comment]
```
[INTERNAL] /public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php line 86 - Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "PrestaShopBundle\Security\OAuth2\Repository\ClientRepository" has a dependency on a non-existent service "security.user.provider.concrete.oauth2". #0
 /public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(83): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue() #1
 /public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(49): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue() #2  /public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(92): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue() #3
 /public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(49): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue() #4
 /public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(83): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue() #5
 /public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(49): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue() #6
 /public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(47): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue() #7
 /public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(40): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process() #8
 /public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(94): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->process() #9
 /public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(762): Symfony\Component\DependencyInjection\Compiler\Compiler->compile() #10
 /public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(594): Symfony\Component\DependencyInjection\ContainerBuilder->compile() #11
 /public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(136): Symfony\Component\HttpKernel\Kernel->initializeContainer() #12
 /public_html/app/AppKernel.php(93): Symfony\Component\HttpKernel\Kernel->boot() #13
 /public_html/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(76): AppKernel->boot() #14
 /public_html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader80.php(45): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() #15
 /public_html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(88): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader80->initConstants() #16
 /public_html/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(43): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #17
 /public_html/backoffice/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #18 {main}
```


Video : https://streamable.com/xzxoxh

**Comment by florine2623** [comment]
I upgraded from 8.0.4 to 8.0.5 using autoupgrade v4.16.2.

The upgrade was successful.
<img width="1435" alt="Screenshot 2023-08-30 at 17 54 13" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/a7842964-4f79-4b48-8cb3-06d77ee02c3d">

https://github.com/PrestaShop/PrestaShop/assets/16019289/a053234c-a074-4b8e-9085-21d9ca312b07

Can you provide your server setup and configuration ?
Thanks

**Comment by DanSilva926** [comment]
yes i use last version

**Comment by kpodemski** [comment]
Hello @DanSilva926 

Make sure that you don't have opcache or any other server cache that could keep previous PHP files in memory enabled. Could you please if your server use opcache and if so, disable it, and try the upgrade again?

**Comment by DanSilva926** [comment]
> 

i have opcache disable

**Comment by sallemiines** [comment]
Hello @DanSilva926 

Could you please provide more details and informations to help us reproducing the issue :pray: 
Waiting for your feedback.

Thanks!

**Comment by egorshubin** [comment]
I have Prestashop 8.0.4. I get 500 error 
The service "PrestaShopBundle\Security\OAuth2\Repository\ClientRepository" has a dependency on a non-existent service "security.user.provider.concrete.oauth2".
Currently it appears when I try to open the admin panel in dev mode.
But when I delete var/cache folder, the whole shop stops working in prod mode, too.
So I think that there's missing dependency injection in cache/dev. But when I delete the cache folder, then it's also missing in prod.
Also when I start to upgrade Prestashop to version 8.0.5, it's not successful because of the same error.
So why isn't that dependency injection created? Is it fixed in 8.1.1? How can we go prod with such an unstable system?

**Comment by DanSilva926** [comment]
Exactly that's the problem

**Comment by egorshubin** [comment]
Installed Prestashop 8.1.1 on local server, and everything works good. Then installed it on hosting - and the admin panel isn't opened with the same error.
If Prestashop added such a feature as oAuth, why aren't there any instructions about what is necessary for the installation? All the server requirements during installation were green-passed

**Comment by paulnoelcholot** [comment]
Hello @DanSilva926,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by egorshubin** [comment]
The issue is that service "security.user.provider.concrete.oauth2" is not determined in config files. When I determined it, then some other servises were missing. When I added them all step by step, 8.0.4 started working again. I'm sorry, I cannot show how I did it, because it's was a long time ago already. Anyway, I made changes in the core, which is a bad practice. Finally, upgrade to Prestashop 8.1.1 solved that issue.

**Comment by RosaBenouamer** [comment]
Hello @DanSilva926,

The record https://streamable.com/xzxoxh is not yet available, is it possible to do something ?

**Comment by MeK-KeM** [comment]
Same issue with our e-commerce website. Getting a 500 error on the back office.

The service "PrestaShopBundle\Security\OAuth2\Repository\ClientRepository" has a dependency on a non-existent service "security.user.provider.concrete.oauth2".

**Comment by gericfo** [comment]
Hi @MeK-KeM,
Thanks for your feedback. Can you give us more details about your issue? (PS versions linked to your problem for example).
It will help us to investigate the issue.
Thanks!

**Comment by gericfo** [comment]
Unless I receive a reply, I am closing this issue. Please feel free to reopen an issue if the problem persists. Thanks!
