### ISSUE TITLE
PrestaShop 8.1.1 - Problem with the translation of the "New" label

### ISSUE THREAD

**Issue by Angar90** [PrestaShop/PrestaShop#33780]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

In PrestaShop 8.1.1 the "New" label is not correctly translated to other languages:
https://prnt.sc/_B6LaipwyIFV

### Expected behavior

To fix this problem, I edited the file:
/src/Adapter/Presenter/Product/ProductLazyArray.php

and changed in line 493:
'label' => $this->translator->trans('New', [], 'Shop.Theme.Global'),

to:
'label' => $this->translator->trans('New', [], 'Shop.Theme.Catalog'),

### Steps to reproduce

1.Install PrestaShop 8.1.1
2.Change language.
3.Check the new label:
https://prnt.sc/_B6LaipwyIFV

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1.21

**Comment by Hlavtox** [comment]
@kpodemski Once again, wasn't this solved already? :D

**Comment by kpodemski** [comment]
@Hlavtox no, the problem is because we didn't export the translations catalog for the patch version

it's something what @jolelievre and @l-delin already discussed

**Comment by aniszr** [comment]
Hello @Angar90 

I managed to reproduce this issue in two PS versions :

- **Develop** & **8.1.x**

See attached screenshot:
![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/e108d275-6b53-453c-824c-23f928167eb0)

However I tried to change the code as you recommended in your description following thoes steps :

1. Go to :  /src/Adapter/Presenter/Product/ProductLazyArray.php
2. Change the line 514:

'label' => $this->translator->trans('New', [], 'Shop.Theme.**Global**'),
by:
'label' => $this->translator->trans('New', [], 'Shop.Theme.**Catalog**'),

3. Save and refresh your FO

The solution worked very well :heavy_check_mark: 

See attached screenrecord for **Develop**:

https://github.com/PrestaShop/PrestaShop/assets/92626242/f6b1e637-14af-4fae-93a9-4bf68648210b

See attached screenrecord for **8.1.x**:

https://github.com/PrestaShop/PrestaShop/assets/92626242/f6724c57-b94a-4897-92ce-bb40f3f25192

Thanks!

**Comment by LarsGMortensen** [comment]
Hi :)
I have the same issue in PS 8.1.1
So I tried following the solution recommended in the description, following these steps :

Go to : /src/Adapter/Presenter/Product/ProductLazyArray.php
Change the line 493:
'label' => $this->translator->trans('New', [], 'Shop.Theme.Global'),
by:
'label' => $this->translator->trans('New', [], 'Shop.Theme.Catalog'),

BUT!

In mine, I already have:

![image](https://github.com/PrestaShop/PrestaShop/assets/26773745/8477bda6-7aeb-4db0-8dbb-734433619b01)

And its still not translated:

![image](https://github.com/PrestaShop/PrestaShop/assets/26773745/a0603bdd-36c9-461d-bc92-7118644e8850)

**Comment by thebodzio** [comment]
Hmmm… just 2 ideas:
Have you cleaned your cache after making the changes?
Perhaps the string in question is not translated in your locale yet. You 
could check in the translation utility in BO.
I hope this will help 😊👍

--
Bogdan
<><



------ Wiadomość oryginalna ------
Nadawca "Lars Mortensen" ***@***.***>
Do "PrestaShop/PrestaShop" ***@***.***>
DW "thebodzio" ***@***.***>; "Manual" 
***@***.***>
Data 08.09.2023 14:47:55
Temat Re: [PrestaShop/PrestaShop] PrestaShop 8.1.1 - Problem with the 
translation of the "New" label (Issue #33780)

**Comment by LarsGMortensen** [comment]
Hi @thebodzio Thank you for replying (via email) to my comment. However, I already deleted my comment, as I found the error (the latest version of that folder had not been downloaded to my local xampp-server from the prod-server since upgrading from 8.1.0 to 8.1.1, so the (old) localhost-version was ok, while the live prod-version wasn't). Sorry for the confusion. Thought I could avoid the confusion by deleting my comment, but I can see that wasn't a solution as you replied via email :)

**Comment by ytilotti** [comment]
Same error here since 8.0.5, and problem on product condition (field name `form[step6][condition]`) translation on admin.

**Comment by MatShir** [comment]
It should be fixed on release 8.1.2. Like @kpodemski said, we didn't push the new catalog last time

**Comment by MatShir** [comment]
The bug is fixed, make sure to update the translation catalog !
