### ISSUE TITLE
put product with api web service

### ISSUE THREAD

**Issue by danieleb90** [PrestaShop/PrestaShop#33783]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I activated the webservice to synchronize the price of a product with the program that manages the warehouse via API. With the Postman program I make a test by sending a put with this text:

<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
  <specific_price>
   <id><![CDATA[47874]]></id>
   <price><![CDATA[98]]></price>
  </specific_price>
</prestashop>

response 200 OK

On prestashop the price is modified but all the values ​​present in the product are canceled and consequently the product becomes inactive.

### Expected behavior

SHOULD KEEP THE OTHER FIELDS AND UPDATE "PRICE"

### Steps to reproduce

![Screenshot 2023-08-31 110329](https://github.com/PrestaShop/PrestaShop/assets/143699705/a859b065-c646-4092-add4-43c3b4f1592a)

### PrestaShop version(s) where the bug happened

1.7.8.10

### PHP version(s) where the bug happened

7

**Comment by kpodemski** [comment]
Hello @danieleb90 

What you are looking for is a PATCH method, unfortunately, it is not available in PrestaShop 1.7.8. It is available in PrestaShop 8.

Feel free to read more about webservice [in our developer documentation](https://devdocs.prestashop-project.org/8/webservice/).

**Comment by danieleb90** [comment]
there are several paid modules to synchronize prices and quantities via webservice so it can also be done in prestashop 7

**Comment by kpodemski** [comment]
@danieleb90 feel free to use those, if they are paid modules they probably added this possibility, either by modifying webservices feature in PrestaShop or by doing it using some dedicated API :)
