### ISSUE TITLE
Error 404 core.js

### ISSUE THREAD

**Issue by AR404lab** [PrestaShop/PrestaShop#33785]
![2023-08-31 13_19_06-Window](https://github.com/PrestaShop/PrestaShop/assets/97963753/66676044-2b4c-40d1-b52e-58a11877ada2)
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I'm getting a 404 error in core.js. Does anyone know how to solve this type of problem?

### Steps to reproduce

I have a display problem that prevents me from being referenced on google. I would like to be able to solve this problem. 

### PrestaShop version(s) where the bug happened

1.7.8.2

**Comment by kpodemski** [comment]
Hello! If you have any questions feel free to open [a new discussion here](https://github.com/PrestaShop/PrestaShop/discussions/categories/q-a), but don't create a bug report just to ask questions.
