### ISSUE TITLE
Distribution API data computing consumes too much memory

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#33797]
### Discussed in https://github.com/PrestaShop/PrestaShop/discussions/33796

<div type='discussions-op-text'>

<sup>Originally posted by **matks** September  1, 2023</sup>
### The problem

[Distribution API](https://github.com/PrestaShop/distribution-api) data is currently outdated, latest data update was 2 days ago. This is because computing the JSON files from GitHub data was consuming too much memory for the instance it was running on.

The instance memory limit will be raised to fix the problem quickly, however memory optimization must happen, else we'll have the same problem in the future. Because the more GitHub releases we do, the more data Distribution API will have to parse.

### The solution

Monitor the different steps being performed during data computing https://github.com/PrestaShop/distribution-api#main-commands and find which one(s) is consuming too much memory. Then optimize it 🚀 

- [ ] Investigation & look for the issue -> We'll have to use `integration` environment to do our testing https://github.com/PrestaShop/distribution-api#environments
- [ ] Provide the fix

### Do you plan to work on this subject?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.</div>

**Comment by jolelievre** [comment]
For a better accuracy, we need more details about what consumed too much memory, and what kind of memory are we talking about? Is it RAM or is it disk space?

Also how come we only detected this after a few days? Shouldn't there be some monitoring and dome alert about this?

**Comment by matks** [comment]
Answers will be given by @djodjo3 😄

**Comment by matks** [comment]
I'm working on this with the help of @JMorinPS

**Comment by matks** [comment]
Looks like we are now back online 

https://api.prestashop-project.org/modules/8.1.1 seems to contain correct data

**Comment by matks** [comment]
The API is working again, however we simply because we updated the settings:
- memory limit increased from 512M to 2048M
- time limit for the generation of JSON files increased from 120s to 240s

Memory consumption is a problem that needs to be fixed.
As for time limit... I'm not sure we can do much. I guess it's expected, as we have slowly more and more versions to parse, that it gets longer.

**Comment by matks** [comment]
Little analysis: the step that consumes a lot of memory is `$ ./bin/console updateModuleConfigFiles` (see README https://github.com/PrestaShop/distribution-api)

**Comment by matks** [comment]
Can't reproduce locally

We'll have to use `integration` environment to do our testing https://github.com/PrestaShop/distribution-api#environments

**Comment by matks** [comment]
Some informations about this ticket: @tleon and @matthieu-rolland have attempted to reproduce the high memory usage problem and did not observe this. Even after switching from localhost to integration environment, and using a real GCP bucket.

This morning @jolelievre suggested that it might be a high memory usage that happens only "just after a new release of the Core". Because when a new release of the Core, a lot of new informations have to be computed. These extra calculations could explain the extra memory usage.

So the "Distribution API data computing consumes too much" phenomenon would only happen just after we release a Core version, every 1 or 2 months.

**Comment by matks** [comment]
Yeeeeeah it's for me

**Comment by matks** [comment]
We tried again and again to reproduce that problem and could not, despite many efforts, the use of Blackfire.io for monitoring, we tried locally, we tried on integration environment.

PrestaShop 8.1.3 was released this tuesday and the problem did not happen again.

I close this issue for now as we fail to understand how it happened :/ (so how can you fix a problem you can't reproduce?) . We can reopen in the future if it happens again.
