### ISSUE TITLE
New module routes don't work when installed after switching dev to prod

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#33800]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

See steps to reproduce

### Steps to reproduce

1. Get 8.1.0
2. Enable debug mode
3. Install [100.zip](https://github.com/PrestaShop/PrestaShop/files/12498134/100.zip).
4. Disable debug mode
5. Click the new controller added in left menu.
6. `The controller ToxRoutetestSettings is missing or invalid.`
7. Clear cache via BO > works.

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.1, standard Linux webserver

**Comment by sallemiines** [comment]
Hello @Hlavtox 

I didn't manage to reproduce the issue with PS81x and develop, see the attached screen record below:

[issue_33800.webm](https://github.com/PrestaShop/PrestaShop/assets/31663369/4ced068a-e338-4415-8c45-b165af998db7)

Please check and feedback.

Thanks!

**Comment by paulnoelcholot** [comment]
Hello @Hlavtox,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Comment by Hlavtox** [comment]
Please don't close it and try to reproduce it

**Comment by ChillCode** [comment]
Hi @Hlavtox 

I thought this was the expected beaviour, since when we delete the cache we do on the current env, but i see is solved by this PR:

https://github.com/PrestaShop/PrestaShop/pull/34171

Thanks for the great effort you all put on this.

**Comment by Hlavtox** [comment]
Solved by https://github.com/PrestaShop/PrestaShop/pull/34171
