### ISSUE TITLE
Google analitics module shutdown my admin panel 

### ISSUE THREAD

**Issue by jackob987** [PrestaShop/PrestaShop#33809]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,
- PrestaShop 1.7.8.7
![problem](https://github.com/PrestaShop/PrestaShop/assets/143831213/4d872f44-2cab-4b70-a82f-625c6c500bed)

after installing module [https://addons.prestashop.com/pl/analizy-statystyki/27138-google-analytics.html](url)
my admin panel shutdown with this report. im amature. if some one know how can i get back or how i can fix it. thank you

### Steps to reproduce

uploud module v4.2.2-ps_googleanalytics
cklic button to configure
fail

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4 

### If your bug is related to a module, specify its name and its version

v4.2.2-ps_googleanalytics

**Comment by jackob987** [comment]
solved. i just delate cache from dev folder.

**Comment by kpodemski** [comment]
Thanks for the confirmation @jackob987 - the next time you have some questions feel free to use [Discussions](https://github.com/PrestaShop/PrestaShop/discussions) :)
