### ISSUE TITLE
Combinations and VAT 8.1

### ISSUE THREAD

**Issue by MockoB** [PrestaShop/PrestaShop#33810]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The product price is calculated wrong when added in the combinations tab in price impact field.
When there is no VAT rule selected in the price tab and the price is added in the “impact on price VAT incl” field in the combinations tab, when saving the product the price is calculated with additional VAT value. The value you entered in the “impact on price VAT incl.” field is translated in the vat. excl. field, and additional VAT is calculated to the price you entered in the VAT incl. field … 

### Expected behavior

I want to see the price I added

### Steps to reproduce

1. Create a product with combinations.
2. Don’t select price rule and don’t put base price in the price field.
3. Directly go to combinations tab and generate combinations.
4. Put some prices in the “impact on price VAT incl.” fields and save the product.
5. Go back in the product combinations tab and you’ll see the difference.

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

8.1.2

**Comment by sallemiines** [comment]
Hello @MockoB 

I didn't manage to reproduce the issue with PS811, see the attached screenshot below:

![image](https://github.com/PrestaShop/PrestaShop/assets/31663369/093199ce-acc9-48b0-9af2-5060d7982658)

I only added the impact price by 10 on combinations with `Color : Orange` and it's well saved.
Please check and feedback.

Thanks!

**Comment by MockoB** [comment]
Hi @sallemiines 
I believe the issue here is that the price rule in the Pricing tab is predefined with NO Tax and price rule 0%, although I got just one price rule which is 20%. I have to choose every time the 20% price rule from the drop down menu when adding a product, which is not very convenient.
I think that no matter if I'm adding base price in the pricing tab, if I add it just in the combinations tab, if it is VAT incl. it should be calculated right after save.
Please let me know why the tax rule is not predefined in the pricing tab? And if there is any way making it pre difined? That will resolve my issue, although I don't believe it is the right decision.

**Comment by MockoB** [comment]
One more thing @sallemiines 
Is your tax rule 0%? I just checked your picture and noticed that you price tax incl and tax excl has no difference.

**Comment by sallemiines** [comment]
Hello @MockoB 

> Is your tax rule 0%? I just checked your picture and noticed that you price tax incl and tax excl has no difference.

Of course it's cause I just followed your steps: **`Don’t select price rule and don’t put base price in the price field`**.
I didn't select any price rule and I didn't put base price :wink: 
Could you please update your steps to reproduce :pray: 
Waiting for your feedback.

Thanks!

**Comment by MockoB** [comment]
Hi @sallemiines Sorry for my late reply. I am uploading you video to check how the VAT price is calculated. It's not showed in the video, but I filled the VAT incl. field first in product combinations tab. For some reason the VAT field in pricing tab is not selected by default and I have to choose it every time I upload a product. After saving the product the VAT incl. price is changed... I just realised that if I'm filling the VAT excl. field, everything will be fine, but that's not the way I fill prices ... If you decide it is normal behaviour, you may close the issue. I already got used to it.


https://github.com/PrestaShop/PrestaShop/assets/25778255/5bf67b21-76f4-451e-b11f-4970d1d3352d

**Comment by djoelleuch** [comment]
Hello @MockoB 
I think it is normal behaviour , as you can see : 

[Untitled_ Sep 22, 2023 5_30 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/c86bc5e1-46a4-4d78-9690-03a401b779c0)

 I'll close the issue 
Thank you .
