### ISSUE TITLE
8.0.5 many log : Log ID | Failed to find customer address . context: []

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#33813]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Dear I have upgrade from 8.0.4 to 8.0.5 and in my log I have a very important number list of 
Log ID (xxf2173XX463X2.92561XXX) | Failed to find customer address . context: [] 
Log ID (XXf217XX081XX.7190XXXX)  | Failed to find customer address . context: []
I have replace some letter and number by X here but every ID are different 
the alert statut is logged as 2 in the alert list 

I have try to search what's the problem, and where is the problem  but I really do not really understand so I write you today to ask you what can be the problem 

Since more than 10 days I have many alert log LOG ID and many abandoned carts and no orders so I have try myself to create an account in the front I not see a problem create an order, and add address + modify address in front it's ok but in the back office appears LOD ID  

So can you maybe telle me if you have seen this problem and also it's difficult here to reproduce the bug because I not seen really where it's the problem. 

Thank you very much by advance and hope to read you soon 

### Steps to reproduce

it's difficult here to reproduce the bug because I not seen really where it's the problem.  

It's on the BACK OFFICE > LOGS  and there appears so many Log ID (XXf217XX081XX.7190XXXX)   | Failed to find customer address . context: []
each log is with an different number 

i have activate the DEBUG MODE, and reproduce the way on the front office as a customer :  add a product on cart go to check out, confirm create an account ( without the address ) validate, then the page add address appears then register the address and there, when I register the address the log appears in the logs section  on the Backoffice and being rated by 2 attention 
so I have try 2 times and create 2 different account and 2 logs appears for each account 
é log account created like this : 
Log ID (XXf217XX081XX.7190XXXX)   | Failed to find customer address . context: [] ID OBJECT 0 02/09/2023 09:10:11
Log ID (XXf217XX081XX.7190XXXX)   | Failed to find customer address . context: [] ,  ID OBJECT 0 02/09/2023 09:10:11

### PrestaShop version(s) where the bug happened

8.0.5

### PHP version(s) where the bug happened

8

**Comment by sallemiines** [comment]
Hello @didjou 

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #26351.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by sallemiines** [comment]
Duplicate of #26351

**Comment by ghost** [comment]
Great a duplicate for the 1.7 from OCTOBER 2021  version but I'm on the 8.0.5  in 2023 and this is not really the same problem so Great and thank you for your non consideration :)

**Comment by matks** [comment]
Hello @didjou it seems you are mistaken. The PrestaShop open-source project can be freely downloaded and used by anyone, but it is provided “as is”, with no warranty or dedicated support.

if you need help with your shop, I suggest to have a look at [this page](https://www.prestashop-project.org/support/) 😉

**Comment by RobMeerwijk** [comment]
I see this issue is closed because it was considered a duplicate of [#26351] Personally I doubt that after reading that issue. I get lots of loglines whenever a new customer registers containing the following:

- [ ] Log ID (65250e34bef752.78426123) | Failed to find customer address . context: []  

We get as many emails. I think this is a bug. It started a few weeks ago. 

We have 8.1.2 installed, but it happened also in 8.1.1

Serverinformatie: Linux https://github.com/PrestaShop/PrestaShop/pull/1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64
Server softwareversie: Apache/2.4.57 (Debian)
PHP-versie: 8.1.23
Geheugenlimiet: 512M
Maximale uitvoeringstijd: 30
Maximale bestandsgrootte voor uploads: 1024M
MySQL versie: 10.3.37-MariaDB-log

Would you consider to re-open this issue? 

Thanks!

**Comment by Juiliard** [comment]
the same issue after upgrade to PS 8.2

**Comment by spidernapster** [comment]
I’m experiencing exactly the same issue described in #33813, not #26351, and I'm running PrestaShop 1.7.6.2.

I suspect the Mollie payment module might be involved. It seems to trigger the address check too early during the checkout process — possibly before the customer address is properly created or attached to the cart.

The logs appear in groups of 6 entries, consistently between the cart creation and the order/payment step.

Could you please re-open this issue ?

Thanks!
