### ISSUE TITLE
Error deleting template with Faceted Search module

### ISSUE THREAD

**Issue by musicpanda** [PrestaShop/PrestaShop#33829]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When deleting an existing template with Faceted search I got a stream of errors. The template was deleted anyway.

Creating a new template produces similar errors.
![facetted](https://github.com/PrestaShop/PrestaShop/assets/13930107/787c06e3-96cf-425d-bebc-983145b968a2)

### Expected behavior

No errors

### Steps to reproduce

Go to the Modules Manager 
Choose Configure for the Facetedsearch module
Delete a template

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

facetedsearch 1.13.1

**Comment by sallemiines** [comment]
Hello @musicpanda 

Thanks for detailed report :clap: 
Unfortunately, I didn't encounter your issue :disappointed: I create a new template and then I delete it :heavy_check_mark: 
See the attached screen record below:

[issue_33829.webm](https://github.com/PrestaShop/PrestaShop/assets/31663369/03abaa43-ce39-4ae8-b3ea-6480c4fdbfdb)

Please check and feedback.

Thanks!

**Comment by paulnoelcholot** [comment]
Hello @musicpanda,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
