### ISSUE TITLE
ps_checkout error on throttling

### ISSUE THREAD

**Issue by AlexMike-maker** [PrestaShop/PrestaShop#33839]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When throttling is activated after the page has been fully loaded, loading persists indefinitely with errors in the console. We noticed this when loading the checkout from mobile.

Version: 
-ps_checkout: v7.3.4.0

![Screenshot from 2023-09-05 11-25-46](https://github.com/PrestaShop/PrestaShop/assets/84742138/d2139ea1-9b5d-4db7-94c1-6d2a6d9ef6ff)

### Steps to reproduce

1. Install module
2. Configure it
3. Make a checkout
4. On 4th step (payment)
5. Press f12 (dev tools)
6. Network tab
7. Enable throttling
8. Refresh

### PrestaShop version(s) where the bug happened

1.7.6.1

### PHP version(s) where the bug happened

7.1.33

### Your company or customer's name goes here (if applicable).

Studio ITC

**Comment by sallemiines** [comment]
Hello @AlexMike-maker 

It seems that your issue is not a PrestaShop core bug.
If your module is Checkout Official, please contact support team on Addons, ping @Matt75 

We will close this issue.

Thanks!
