### ISSUE TITLE
[BO] Copying language to another fails

### ISSUE THREAD

**Issue by surffari** [PrestaShop/PrestaShop#33834]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Copying language from existing to newly created fails.
The directory for the created language is not what expected (yy instead of xx-YY)

![image](https://github.com/PrestaShop/PrestaShop/assets/2113356/4dbd31f4-f5a7-4c80-b821-fa4b2809fa37)

### Expected behavior

Copy from one lang to another is completed without errors.

New folder for new language created is xx-YY format (Like en-AU), not au

### Steps to reproduce

Install fresh PS 8.1.0
By default, have en-us is installed.
Create new language en-AU
Directory /translations/en is created (expecting /translations/en-AU)

Copy translations en-us -> en-au:
![image](https://github.com/PrestaShop/PrestaShop/assets/2113356/b1cc0599-6974-4e44-b4f0-957b02eb65b9)
Result, copy fails:
![image](https://github.com/PrestaShop/PrestaShop/assets/2113356/a916cdbd-9ab9-4831-b001-f86f3dc793d8)

Diagnoses: PS tries to copy files from non-existent directory (translations/en/) as the language directories is en-US:
![image](https://github.com/PrestaShop/PrestaShop/assets/2113356/fd4c4ab6-1f04-4fa9-98e1-06aa5559874f)

Let's try the same with abnother language:
Install new language en-gb. New folder /translations/en-GB is created.
Copy translations en-gb -> en-au.
Result again:
![image](https://github.com/PrestaShop/PrestaShop/assets/2113356/5fe31817-f0d4-4bc9-bf77-767528040943)

PS tried to copy files from directory translations/gb which is non-existing.

Also file(s) PS is trying to copy, not exist. Example admin.php:
![image](https://github.com/PrestaShop/PrestaShop/assets/2113356/6c62d093-4894-42fc-bf75-a3fa0fb6fa3f)

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

GoPure

**Comment by sallemiines** [comment]
Hello @surffari 

I beleive your problem is related to your permission to access, please change the Owner and Group by your pc username and give the right access to execute these files (please read this [doc](https://linuxhint.com/chmod-777-mean/#:~:text=Permission%20to%20read%20and%20write,write%2C%20or%20execute%20the%20file.) it may help).
Then check if you still encounter the same issue. 
Waiting for your feedback.

Thanks!

**Comment by kpodemski** [comment]
Hello @surffari 

This feature is obsolete. It handles legacy back office translations, which were removed a while ago. We should probably rework or remove this feature entirely.

cc @MatShir

**Comment by surffari** [comment]
Hi Krystian,

Ok thanks for letting me know, PS is always full of surprises.

J

**Comment by florine2623** [comment]
I'm closing this issue in favor of https://github.com/PrestaShop/PrestaShop/issues/16132 to avoid duplicates
