### ISSUE TITLE
Cannot update Autoupgrade module to 4.16.xx

### ISSUE THREAD

**Issue by Tomi1444** [PrestaShop/PrestaShop#33854]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I cannot update module from 4.15 to 4.16.(any).

Error message: "403 Forbidden Access to this resource on the server is denied!"

### Steps to reproduce

Download any 4.16.xx autoupgrade zip and try to upload in BO

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7,4

**Comment by Tomi1444** [comment]
Also I cannot update my shop from 1.7.8.7. to higher for no reason

![error](https://github.com/PrestaShop/PrestaShop/assets/118079647/7278b8d8-8a2e-4cf0-ad63-f3ded6fea7f8)

**Comment by Tomi1444** [comment]
I can only reinstall 4.15 using zip. This work, but nothing more

**Comment by sallemiines** [comment]
Hello @Tomi1444 

Could you please provide a screen record of how you try to upgrade your module autoupgrade :pray: 
Waiting for your feedback.

Thanks!

**Comment by Tomi1444** [comment]
Maybe I'm doing something wrong?

![image](https://github.com/PrestaShop/PrestaShop/assets/118079647/536456f1-2542-4258-bdee-32e4dc357679)

**Comment by matks** [comment]
Hello @Tomi1444 so if I understand this is what you do

1. Download ZIP autoupgrade module 4.16.3
2. Open Backoffice, go to "Module Manager" page
3. Click "Upload module" button, the dropzone window is opened
4. Drag-and-drop the ZIP 4.16.3 into the dropzone
5. Error appears

Correct?

**Comment by Tomi1444** [comment]
Exactly, I apologize for not providing clear information.

**Comment by matks** [comment]
The ZIP is on your computer/server, and same for the source code. This might be a permissions issue.

For example if your server is configured so that it is not possible to upload/write new files into your `/modules` folder, then you might get this problem. Hence the "Denied".

To solve it:
- verify access rights of your shop files
- verify error logs you might have more detailed informations

Here's an example of how you can do it https://classydevs.com/prestashop-folder-permission/

**Comment by Tomi1444** [comment]
I can uninstal 4.15 and install it this way. It work.
I only can't install 4.16.xx

**Comment by Tomi1444** [comment]
755 and 644 for file permmisions helped

**Comment by matks** [comment]
@Tomi1444 Happy to hear that 😄
