### ISSUE TITLE
Small typo in documentation of TextWithRecommendedLengthType.php

### ISSUE THREAD

**Issue by thomasnares** [PrestaShop/PrestaShop#33851]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

`src/PrestaShopBundle/Form/Admin/Type/TextWithRecommendedLengthType.php` has a small typo: 

`lenght` instead of `length`at line 37

Also, it misses the complete path to this js file

### Steps to reproduce

1. this is a documentation / comment type
2. not testable

### PrestaShop version(s) where the bug happened

found on 8.0, but should be on all versions

**Comment by kpodemski** [comment]
@thomasnares no needed for the issue to improve doc blocks in the code 👍🏻👍🏻
