### ISSUE TITLE
Autoupgrade fails with an infinite loop when trying to upgrade a module from a local storage folder.

### ISSUE THREAD

**Issue by aniszr** [PrestaShop/PrestaShop#33866]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When trying to upgrade your PS store, using the alternative of upgrading a module (ps_linklist) from a local storage folder.
The autoupgrade process gets into an infinite loop .

See attached screenshot:

![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/cae85777-f9d1-4241-be45-192b450d34e4)

### Expected behavior

The autoupgrade process should be completed with success message

- Store version is upgraded
- Module is upgraded to the version available in local folder `admin/autoupgrade/modules/[your module.zip]`

### Steps to reproduce

In a PS 8.0.5 newly installed, make sure you install autoupgrade module version 4.16.3
Go to your project folder : `admin/autoupgrade/modules` (Create modules folder manually)
Save the ps_linklist.zip module version 6.0.5 in modules folder
Click upgrade process (to PS 8.1.1)
See error : infinite loop

### PrestaShop version(s) where the bug happened

1.7.8.10 , 8.0.5

### PHP version(s) where the bug happened

7.2 , 8.1

### If your bug is related to a module, specify its name and its version

autoupgrade 4.16.3

**Comment by ChillCode** [comment]
H @aniszr 

Without testing and just reading your log it really looks strange behavior since the installation process should stop after the first [INTERNAL] Operation failed.

You can check if the folders have the right permission.

**Comment by sallemiines** [comment]
Hello @aniszr 

Indeed you need to give the right access / permission to your modules folder as @ChillCode mentioned above.
Otherwise, I didn't manage to reproduce the issue.
Please check and feedback.

Thanks!

**Comment by florine2623** [comment]
Hello @aniszr ,

I tested your issue.
I'm using autoupgrade `v4.16.4` and Link List `v6.0.4`.
I'm upgrading to PS `8.1.2` as it is the latest version available.

I'm having the same issue as you.
I have the right permissions on my folders as well.

https://github.com/PrestaShop/PrestaShop/assets/16019289/dffe996d-879c-4ec1-b8f5-62ace7b03605

The upgrades are never finished.

**Comment by Hlavtox** [comment]
Fixed
