### ISSUE TITLE
Export feature value not working

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#33862]
### PB 

- Exporting from inside a Feature (the previous Feature should be deleted ):x:

See attached screenrecord:

https://github.com/PrestaShop/PrestaShop/assets/92626242/ec181244-f9d3-4aa0-961b-f371c0553419

### Steps to reproduce
These are detailed steps for how to reproduce the issue :

1. Create two features : **feature 1** and **feature 2**
2. For each feature add three feature values : test1 , test2 , test3 for **feature 1** & test11,test22,test33 for **feature 2**
3. Click on view button for **feature 1**
4. Delete the feature value **test3** from **feature 1**
5. Back to list
6. Delete **feature 1**
7. Click view on **feature 2**
8. Click on Setting icon button > Click Export > See the Error :x:

### PS version
 9.0.x

_Originally posted by @aniszr in https://github.com/PrestaShop/PrestaShop/pull/33051#pullrequestreview-1583027505_

**Comment by sallemiines** [comment]
Hello @aniszr 

I didn't manage to reproduce the issue on develop, could you please provide steps to reproduce the issue :pray: 
Waiting for your feedback.

Thanks!

**Comment by aniszr** [comment]
Hello @sallemiines 

Thanks for your feedback.

These are detailed steps for how to reproduce the issue :

1. Create two features : **feature 1** and **feature 2**
2. For each feature add three feature values : test1 , test2 , test3 for **feature 1** & test11,test22,test33 for **feature 2**
3. Click on view button for **feature 1**
4. Delete the feature value **test3** from **feature 1**
5. Back to list
6. Delete **feature 1**
7. Click view on **feature 2**
8. Click on Setting icon button > Click Export > See the Error :x:

Thanks!

**Comment by MhiriFaten** [comment]
Hello @MatShir ,

I reproduce the issue with develop PrestaShop.


[Untitled_ Sep 14 2023 4_09 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/111756615/4e2e78d8-88b4-491b-9cde-98f6fb1540ae)


Thank you
