### ISSUE TITLE
Stock Movement - Multiple Advanced Filters "Employee & Movement Type" doesn't work

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#33861]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Multiple Advanced Filters "Employee & Movement Type" doesn't work

Tested with 9.0.x but should apply on previous versions

### Steps to reproduce

1. FO > Make an order of "Hummingbird printed sweater"
2. BO > Orders > Validate the order from BO and put `Delivered` as **Order_Status**
3. BO > Stock > Movement
4. Filter by "Movement type" : "Customer Order"
5. :+1: It's OK : ![image](https://github.com/PrestaShop/PrestaShop/assets/1533248/d21a2b6a-f00a-4368-9018-86563e4a25f5)
6. Add the filter "Employee" with the current employee
7. :-1: It's KO : ![image](https://github.com/PrestaShop/PrestaShop/assets/1533248/7be25d57-15bf-4b9f-9832-475af61abca1)

### PrestaShop version(s) where the bug happened

9.0.x

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

N/A

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

**Comment by sallemiines** [comment]
Hello @Progi1984 

I think there's a missing step where I validate the order from BO and put `Delivered` as **Order_Status**, isn't it?
Please check and feedback.

Thanks!

**Comment by Progi1984** [comment]
@sallemiines I confirm. Sorry.

**Comment by sallemiines** [comment]
Hello @Progi1984 

Even with the new step I didn't manage to reproduce the issue, see the attached screen record below:

[issue_33861.webm](https://github.com/PrestaShop/PrestaShop/assets/31663369/abe028d8-2c0d-4664-bfeb-0746a9697af0)

It seems that this issue related to cache issues, wdyt?

Thanks!

**Comment by Progi1984** [comment]
@sallemiines The order you filter has been done by an employee  or a customer on the front ?

I updated steps to reproduce

**Comment by sallemiines** [comment]
@Progi1984 the order has been created by a customer on FO and it was validated by an employee in BO
