### ISSUE TITLE
In autoupgrade process, Doctrine entities schema updates are managed by Doctrine command prestashop:schema:update and it creates plenty issues

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#33874]
## Problem

In autoupgrade process, Doctrine entities schema updates are managed by Doctrine command prestashop:schema:update

Module autoupgrade [CoreUpgrader80:: upgradeDb()](https://github.com/PrestaShop/autoupgrade/blob/v4.16.3/classes/UpgradeTools/CoreUpgrader/CoreUpgrader80.php#L68)
```
    protected function upgradeDb($oldversion)
    {
        parent::upgradeDb($oldversion);

        $commandResult = $this->container->getSymfonyAdapter()->runSchemaUpgradeCommand();
        if (0 !== $commandResult['exitCode']) {
            throw (new UpgradeException($this->container->getTranslator()->trans('Error upgrading Doctrine schema', [], 'Modules.Autoupgrade.Admin')))->setQuickInfos(explode("\n", $commandResult['output']));
        }
    }
```

`runSchemaUpgradeCommand()` relies on Doctrine `prestashop:schema:update` (which is a very bad idea).

We have confirmation that this was a really bad idea by many recent reports about autoupgrade issues that fail because of this:

- https://github.com/PrestaShop/PrestaShop/issues/33820
- https://github.com/PrestaShop/PrestaShop/issues/33641
- https://github.com/PrestaShop/PrestaShop/issues/33337
- https://github.com/PrestaShop/PrestaShop/issues/33524
- https://github.com/PrestaShop/PrestaShop/issues/33513
- https://github.com/PrestaShop/PrestaShop/issues/33364
- https://github.com/PrestaShop/PrestaShop/issues/33021
- https://github.com/PrestaShop/PrestaShop/issues/32350
- https://github.com/PrestaShop/PrestaShop/issues/32336
- https://github.com/PrestaShop/PrestaShop/issues/32030

And also older reports
- https://github.com/PrestaShop/PrestaShop/issues/31413
- https://github.com/PrestaShop/PrestaShop/issues/27999
- https://github.com/PrestaShop/PrestaShop/issues/24727
- https://github.com/PrestaShop/PrestaShop/issues/23712
- https://github.com/PrestaShop/PrestaShop/issues/23448
- https://github.com/PrestaShop/PrestaShop/issues/20332
- https://github.com/PrestaShop/PrestaShop/issues/12413

## Solution

This idea must be removed and replaced by something more reliable.

**Comment by ChillCode** [comment]
Hi

If someone is interested, the problem is executing Transactional DDL on MySQL/MariaDB that don't support them and when one of the command fails then we are getting "There is no active transaction", have sense, because there is no transaction to active transaction to rollback.

The following issue https://github.com/PrestaShop/PrestaShop/issues/33337 looks like the OP is using an old MariaDB/MySQL server and the following command fails [because of key size](https://github.com/PrestaShop/PrestaShop/issues/33021):

> Executing: CREATE TABLE ps_authorized_application (id_authorized_application INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, UNIQUE INDEX UNIQ_475B9BA55E237E06 (name), PRIMARY KEY(id_authorized_application)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB

Disabling Transactional DDL will give better output for when ALTER, CREATE TABLE fails.

https://www.doctrine-project.org/projects/doctrine-migrations/en/3.6/reference/configuration.html#using-or-not-using-transactions

https://www.doctrine-project.org/projects/doctrine-migrations/en/3.6/reference/migration-classes.html#istransactional

**Comment by jolelievre** [comment]
### Technical solution

We need a script that:
- checkout the project for a defined version/tag install the shop and the DB
- exports the DB sructure as is to get the frozen state in for example db-structure-frozen-1.7.0.0.sql
- then checkout the project for the next tag
- update dependencies with composer install
- run the command doctrine schema update and export the SQL commands to either
  - a dedicated SQL file for this version upgrade, and we’ll use these files as reference to then add them in the autoupgrade SQL scripts
  - automatically updates the SQL script in the autoupgrade module and prepend/append the queries in the file
- export the SQL Db structure in a new sql file db-structure-upgraded-1.7.0.1.sql
- compare the upgraded structure with the frozen structure (except in first step)

Then we increment the version and we do it all over again

**Comment by Hlavtox** [comment]
@jolelievre Make sure to not delete any custom columns when adapting the structure.

**Comment by matks** [comment]
> @jolelievre Make sure to not delete any custom columns when adapting the structure.

Actually let's delete all custom columns :trollface: so we make sure the SQL schema is formatted to follow the standard

It will be a feature 😄 not a bug

**Comment by M0rgan01** [comment]
Script to retrieve SQL files equivalent to each execution of a `prestashop:schema:update-without-foreign` command for each version between 1.7.1.0 and 8.1.1

```
#!/bin/bash

install() {
  echo "Installation of v$1 ..."

  major_version=$(echo "$1" | awk -F'.' '{print $1}')
  minor_version=$(echo "$1" | awk -F'.' '{print $2}')
  patch_version=$(echo "$1" | awk -F'.' '{print $3}')

  if [ "$major_version" -gt 1 ] || [ "$major_version" -eq 1 -a "$minor_version" -eq 7 -a "$patch_version" -ge 5 ]; then
    version="7.2"
  else
    version="5.6"
  fi

  docker run -it --rm --network=script_upgrade -v "$PWD":/usr/src/myapp -w /usr/src/myapp prestashop/base:$version-fpm \
    php install/index_cli.php --db_server=mysql:3306 --db_name=prestashop --db_user=root --db_password=prestashop --prefix=ps_ \
    --db_clear=1 \
    --domain=localhost:8001 --firstname="Marc" --lastname="Beier" \
    --password=Toto123! --email=demo@prestashop.com --language=fr --country=fr \
    --newsletter=0 --send_email=0 --ssl=0

  if [ $? -ne 0 ]; then
    echo "Docker command failed. Stopping the script (v$1)."
    exit 1
  fi

  echo "Installation of v$1 successful"
}

upgrade() {
  echo "Upgrading from v$2 to v$1 ..."
  cp /.../parameters.php app/config

  major_version=$(echo "$1" | awk -F'.' '{print $1}')
  minor_version=$(echo "$1" | awk -F'.' '{print $2}')
  patch_version=$(echo "$1" | awk -F'.' '{print $3}')

  if [ "$major_version" -gt 1 ] || [ "$major_version" -eq 1 -a "$minor_version" -eq 7 -a "$patch_version" -ge 4 ]; then
    consoleLocation="bin"
  else
    consoleLocation="app"
  fi

  chmod +x $consoleLocation/console

  docker run -it --rm --network=script_upgrade -v "$PWD":/usr/src/myapp -w /usr/src/myapp prestashop/base:7.2-fpm \
    $consoleLocation/console prestashop:schema:update-without-foreign >$dump_directory/"$1"_upgrade.sql

  if [ $? -ne 0 ]; then
    echo "Docker command failed. Stopping the script (v$1)."
    exit 1
  fi

  sed -i '1d' $dump_directory/"$1"_upgrade.sql
  sed -i 's/Executing://g' $dump_directory/"$1"_upgrade.sql
  sed -i '$d' $dump_directory/"$1"_upgrade.sql

  echo "Upgrading from v$2 to v$1 successful"
}

download_release() {
  curl -LO https://github.com/PrestaShop/PrestaShop/releases/download/"$1"/prestashop_"$1".zip
  unzip -o prestashop_"$1".zip -d "$1" >/dev/null
  rm prestashop_"$1".zip
  cd "$1" || exit
  unzip -o prestashop.zip >/dev/null
  rm prestashop.zip
}

release_directory="..."
dump_directory="..."

mkdir -p "$release_directory"
mkdir -p "$dump_directory"

docker network create script_upgrade
docker run -d --network=script_upgrade -p 3306:3306 --name mysql -e MYSQL_ROOT_PASSWORD=prestashop -e MYSQL_DATABASE=prestashop mysql:5
sleep 10

first=true
previousTag=null

for tag in $(git ls-remote --tags --refs git@github.com:PrestaShop/PrestaShop.git | awk -F/ '{print $NF}'); do
  if [[ "$tag" > "1.7.1" && "$tag" != *'beta'* && "$tag" != *'rc'* ]]; then

    cd "$release_directory" || exit
    download_release "$tag"
    echo "Tag Git : $tag"

    if [ "$first" = true ]; then
      install "$tag"
      first=false
    else
      upgrade "$tag" "$previousTag"
      install "$tag"
    fi

    previousTag=$tag
  fi
done
```

**Comment by M0rgan01** [comment]
after several tests, there were errors due to updates to certain modules: https://github.com/PrestaShop/autoupgrade/issues/1571

**Comment by M0rgan01** [comment]
Script for performing updates starting from version 1.7.1.0.

```
#!/bin/bash

release_directory="..."
dump_directory="..."

mkdir -p "$release_directory"
mkdir -p "$dump_directory"

install() {
  echo "Installation of v$1 ..."

  docker run --network=script_upgrade -it --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp prestashop/base:7.2-fpm \
    php install/index_cli.php --step=database --db_server=mysql:3306 --db_name=prestashop --db_user=root --db_password=prestashop --prefix=ps_ \
    --db_clear=1 \
    --domain=localhost:8001 --firstname="Marc" --lastname="Beier" \
    --password=Toto123! --email=demo@prestashop.com --language=fr --country=fr \
    --newsletter=0 --send_email=0 --ssl=0

  if [ $? -ne 0 ]; then
    echo "Docker command failed. Stopping the script (v$1)."
    exit 1
  fi

  echo "Installation of v$1 successful"
}

dump_DB() {
  docker exec -it mysql mysqldump -u root -pprestashop --no-data prestashop >$dump_directory/dump_classic.sql

  if [ $? -ne 0 ]; then
    echo "Docker command failed. Stopping the script."
    exit 1
  fi
}

download_release_and_xml() {
  docker run -it --rm --network=script_upgrade -v "$PWD":/usr/src/myapp -w /usr/src/myapp prestashop/base:7.2-fpm \
    curl -L https://github.com/PrestaShop/PrestaShop/releases/download/"$1"/prestashop_"$1".zip -o admin/autoupgrade/download/prestashop_"$1".zip
  docker run -it --rm --network=script_upgrade -v "$PWD":/usr/src/myapp -w /usr/src/myapp prestashop/base:7.2-fpm \
    curl -L https://api.prestashop.com/xml/md5/"$1".xml -o admin/autoupgrade/download/prestashop_"$1".xml
}

upgrade_with_autoupgrade_module() {
  echo "Upgrade from v$1 to v$2 ..."

  docker run -it --rm --network=script_upgrade -v "$PWD":/usr/src/myapp -w /usr/src/myapp prestashop/base:7.2-fpm /bin/sh -c \
    "cp -r modules/autoupgrade .;
    rm -rf modules/*;
    mv autoupgrade modules/;"

  download_release_and_xml "$2"

  docker run -it --rm --network=script_upgrade -v "$PWD":/usr/src/myapp -w /usr/src/myapp prestashop/base:7.2-fpm \
    sh -c "echo '{\"channel\":\"archive\",\"archive_prestashop\":\"prestashop_$2.zip\",\"archive_num\":\"$2\", \"archive_xml\":\"prestashop_$2.xml\", \"PS_AUTOUP_CHANGE_DEFAULT_THEME\":\"0\", \"skip_backup\": \"1\"}' > modules/autoupgrade/config.json"

  docker run -it --rm --network=script_upgrade -v "$PWD":/usr/src/myapp -w /usr/src/myapp prestashop/base:7.2-fpm \
    php modules/autoupgrade/cli-updateconfig.php --from=modules/autoupgrade/config.json --dir=admin

  docker run -it --rm --network=script_upgrade -v "$PWD":/usr/src/myapp -w /usr/src/myapp prestashop/base:7.2-fpm \
    php modules/autoupgrade/tests/testCliProcess.php modules/autoupgrade/cli-upgrade.php --dir="admin" --action="compareReleases"

  docker run -it --rm --network=script_upgrade -v "$PWD":/usr/src/myapp -w /usr/src/myapp prestashop/base:7.2-fpm \
    php modules/autoupgrade/tests/testCliProcess.php modules/autoupgrade/cli-upgrade.php --dir="admin"
}

download_release() {
  docker run -it --rm --network=script_upgrade -v "$PWD":/usr/src/myapp -w /usr/src/myapp prestashop/base:7.2-fpm /bin/sh -c \
    "curl -LO https://github.com/PrestaShop/PrestaShop/releases/download/$1/prestashop_$1.zip;
    unzip -o prestashop_$1.zip -d $1 >/dev/null;
    rm prestashop_$1.zip;
    cd $1 || exit;
    unzip -o prestashop.zip >/dev/null;
    rm prestashop.zip;
    mkdir admin/autoupgrade/download;"
}

install_module() {
  docker run -it --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp composer:latest /bin/sh -c \
    "cd modules;
   git clone https://github.com/PrestaShop/autoupgrade.git;
   cd autoupgrade;
   composer install;"
}

docker network create script_upgrade
docker run --network=script_upgrade -d -p 3306:3306 --name mysql -e MYSQL_ROOT_PASSWORD=prestashop -e MYSQL_DATABASE=prestashop mysql:5
sleep 10

cd "$release_directory" || exit
download_release "1.7.1.0"
cd 1.7.1.0 || exit
install "1.7.1.0"
install_module
previousTag=1.7.1.0

for tag in $(git ls-remote --tags --refs git@github.com:PrestaShop/PrestaShop.git | awk -F/ '{print $NF}'); do
  if [[ "$tag" > "1.7.1.0" && "$tag" != *'beta'* && "$tag" != *'rc'* ]]; then

    upgrade_with_autoupgrade_module $previousTag "$tag"

    previousTag=$tag
  fi
done

dump_DB
```

**Comment by M0rgan01** [comment]
A pull request is ready but waiting for the addition of automated tests on the autoupgrade feature. Some initial work has been started [here](https://github.com/PrestaShop/ga.tests.ui.pr/pull/51), but it needs to be able to upgrade from version 1.7.1.0 to the latest release. We will also need to address [issues](https://github.com/PrestaShop/autoupgrade/issues/1571) with updating modules in order to automatically test older versions of PrestaShop.

**Comment by RosaBenouamer** [comment]
Waiting for [test UI](https://github.com/PrestaShop/PrestaShop/issues/34139) de @jolelievre

**Comment by rbuelund** [comment]
Any ETA for when this problem will be fixed. I am still on 8.0.2 and unable to update - this is an security issue for me..
