### ISSUE TITLE
ps_account logged out due to errors (5xx) in retrieve token

### ISSUE THREAD

**Issue by cdigruttola** [PrestaShop/PrestaShop#33870]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
yesterday my customer alerts me telling me that paypal was no longer in the payment list
in fact ps_account had disassociated the addons account.

### Steps to reproduce

It happens randomly. In attachment the log of ps_account

[ps_accounts-2023-09-06.log](https://github.com/PrestaShop/PrestaShop/files/12547548/ps_accounts-2023-09-06.log)

### PrestaShop version(s) where the bug happened

8.1.1, 1.7.8.10

### PHP version(s) where the bug happened

8.1, 7.4

### If your bug is related to a module, specify its name and its version

ps_account, ps_checkout

**Comment by kpodemski** [comment]
Hello @cdigruttola 

These solutions are not supported through Github. Please use Help Center to contact the support team:

https://help-center.prestashop.com/en/sections/4420018873746-modules#360006118171

**Comment by cdigruttola** [comment]
Please reopen https://github.com/PrestaShop/PrestaShop/discussions/33786
