### ISSUE TITLE
Autoupgrade shows a warning when running with php8.1

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#33886]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I go to the Configuration page of AutoUpgrade 4.16.3 using PHP8.1.20 I see a warning:
```
Unknown error à la ligne 530 du fichier /Users/mFerment/www/prestashop/PrestaShop/modules/autoupgrade/classes/UpgradeSelfCheck.php
[8192] version_compare(): Passing null to parameter #1 ($version1) of type string is deprecated
```

I think it will happen for other versions of autoupgrade module too.

### Expected behavior

There should be no warning

### Steps to reproduce

1. Install a 9.0.0 shop (`develop` branch) and use php 8.1
2. Install module autoupgrade 4.16.3
3. Click on "Configure" module autoupgrade on backoffice page "Module Manager"
4. See the warning

<img width="669" alt="Capture d’écran 2023-09-08 à 17 58 10" src="https://github.com/PrestaShop/PrestaShop/assets/3830050/52f9dabc-0b91-4bd9-849e-dc63bc553156">

I think it will also happen for 8.1.1

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

autoupgrade 4.16.3

**Comment by matks** [comment]
I submitted a PR to fix the bug https://github.com/PrestaShop/autoupgrade/pull/624

**Comment by sallemiines** [comment]
Hello @matks 

I only reproduce the issue with develop branch! 

![image](https://github.com/PrestaShop/PrestaShop/assets/31663369/aac68a92-6075-460e-8eba-c4b65aa5fbdf)

Thanks for your PR :rocket: 

Thanks!
