### ISSUE TITLE
Email Template Manager error 500

### ISSUE THREAD

**Issue by JeromeOnyx** [PrestaShop/PrestaShop#33884]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Bonjour, 
Je vous contacte ce jour, car j'ai un bug au niveau du module Email Template Manager.
Lorsque je clique dessus, j'ai un directement un code erreur 500.

### Expected behavior

Je souhaitais pouvoir configurer les templates des mails envoyés

### Steps to reproduce

1 aller sur modules
2 choisir gestionnaire de modules
3 rechercher Email Template Manager
4 cliquer sur configurer

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.1.23

### If your bug is related to a module, specify its name and its version

Email Templates Manager

**Comment by hibatallahAouadni** [comment]
Hello @JeromeOnyx 

Please send your request in English. English is the norm on GitHub.
It seems that your issue is not a PrestaShop core bug.
If your module is Email Templates Manager Official, please contact support team on Addons.

We will close this issue.

Thank you
