### ISSUE TITLE
Prestashop 8.1.1 category Description is not multilingual

### ISSUE THREAD

**Issue by mikajaxxx** [PrestaShop/PrestaShop#33895]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello
in ps 8.1.1 we can't have multilingual description ! the text remain the same for all language

### Expected behavior

every language must have its own description 

### Steps to reproduce

1 Go to categories
2 edit/ add new category
3 Scroll to Description field
4 put some text in one language
5 change language and the text still is the same!

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1

**Comment by sallemiines** [comment]
Hello @mikajaxxx 

I didn't manage to reproduce the issue with 8.1.1, see the attached screen record below:

[issue_33895.webm](https://github.com/PrestaShop/PrestaShop/assets/31663369/47d6b693-32e1-4c41-afc8-967ace2f580e)

Please check and feedback.

Thanks!

**Comment by mikajaxxx** [comment]
just disable second language ! all fields has language tag except description! sometimes people need complete data before activating second language

**Comment by djoelleuch** [comment]
Hello @mikajaxxx 
I couldn't reproduce this issue, since the expected behavior is totally correct as you can see below : 

[Untitled_ Sep 15 2023 12_58 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/6bd55bf9-cb20-4958-a765-1bac7ddbb6d3)


We will close this issue.

Thank you

**Comment by MatShir** [comment]
@mikajaxxx Why you would want to translate a disabled language ? Is your need similar to this https://github.com/PrestaShop/PrestaShop/discussions/32275, it is does don't hesitate to comment and upvote it ;)

**Comment by mikajaxxx** [comment]
@MatShir  Because in real life we need translate all products before enabling other languages. so as this ability is provided for all fields why not for description field?
