### ISSUE TITLE
Error 500 when generating credit slips just for delivery fees

### ISSUE THREAD

**Issue by paul933** [PrestaShop/PrestaShop#33890]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I want to generate a PDF for credit slips for refund only delivery fees, I have an 500 error on my server.
![image](https://github.com/PrestaShop/PrestaShop/assets/74627861/0086f19c-78f9-436f-b336-518fea7e54b2)

I have try on a new installation of prestashop 8.1.1 and on my website recently upgraded (1.7.8.10 -> 8.1.1), I have the same error. 
I try with PHP 7.4 and 8.1 and it's the same error. 

### Steps to reproduce

1. Generate a credit slips just for the delivery fees
![image](https://github.com/PrestaShop/PrestaShop/assets/74627861/943ea2cd-5cc6-4b8e-ba12-c22f3166ed64)
2. Try to open the PDF file generated 
![image](https://github.com/PrestaShop/PrestaShop/assets/74627861/0086f19c-78f9-436f-b336-518fea7e54b2)

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

7.4.33

**Comment by sallemiines** [comment]
Hello @paul933 

I reproduce the issue with 81x and develop, see the attached screenshot below:

![image](https://github.com/PrestaShop/PrestaShop/assets/31663369/5e7d4db4-0117-4f51-b9e8-8a813b96356c)

It display an error 500 related to this file HTMLTemplateOrderSlip. It only occurs when we create a credit slip with shipping fee. I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by florine2623** [comment]
Fixed in https://github.com/PrestaShop/PrestaShop/pull/35439
