### ISSUE TITLE
When adding language, the logic ignores primary columns in object models

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#33893]
➡️ TLDR - If you have tables `ps_something` and `ps_something_lang` and your ID columns are not called `id_something`, you get bad data when you add a new language.
____________

### Describe the bug and add attachments

When you add new language, Prestashop creates the missing entries in _lang tables by using the entries of a default language.

This logic is using a following identifier to detect a primary column:
```
preg_match('#^' . preg_quote(_DB_PREFIX_) . '(.+)_lang$#i', $tableName, $m);
$identifier = 'id_' . $m[1];
```

So if you have a table called `ps_psgdpr_consent_lang`, it thinks the primary key is `id_psgdpr_consent`, but in case of the GDPR module it's `id_gdpr_consent`. So for this module, no language entries are created.

### Expected behavior

The logic should use a `primary` attribute of the given object model, as stated in `$definition`, for example `'primary' => 'id_gdpr_consent',` or not use it at all, it doesn't need it.
I fix the issue by simplifying the logic in https://github.com/PrestaShop/PrestaShop/pull/33894.

### Steps to reproduce

1. Add new language.
2. Check database and check that `ps_psgdpr_consent_lang` does not contain new entries, but `ps_product_lang `does.

### PrestaShop version(s) where the bug happened

8.1x

**Comment by Hlavtox** [comment]
No need to test this, I spent a lot of time finding and fixing the issue. Trust me. :-)

**Comment by sallemiines** [comment]
Hello @Hlavtox 

The most dangerous thing QA can do is trust a developer :grin: 
So, it seems your issue is kind of related to this one #27942
I added a new lang and I see that the message with this new lang is void, see the attached screenshot below:

![image](https://github.com/PrestaShop/PrestaShop/assets/31663369/8ba48a70-2ae9-4639-bf53-dde9aa58829b)

Is this the bug that you encountred? Please check and feedback.

Thanks!

**Comment by florine2623** [comment]
@Hlavtox , should I close your issue because it is related to https://github.com/PrestaShop/PrestaShop/issues/27942 ?

**Comment by Hlavtox** [comment]
@florine2623 It's not related, but this issue was fixed. :-)
