### ISSUE TITLE
Error after updating from 1.7.8.7 to 1.7.8.10

### ISSUE THREAD

**Issue by Tomi1444** [PrestaShop/PrestaShop#33892]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have disabled all extension modules before update.
Lunch update, and when it finish, that error occurs: 

_"[INTERNAL] /home/sklepvid/domains/vidos-domofony.pl/public_html/src/PrestaShopBundle/Form/Admin/Extension/ModifyAllShopsExtension.php line 49 - Class PrestaShopBundle\Form\Admin\Extension\ModifyAllShopsExtension contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Component\Form\FormTypeExtensionInterface::getExtendedType)"_

When I try to reload page for my BO, error 500 occurs

### Steps to reproduce

Run update from 1.7.8.7 to 1.7.8.10 
Wait till end
The summary shows error 

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

**Comment by sallemiines** [comment]
Hello @Tomi1444 

I didn't manage to reproduce the issue with the provided infos, could you please provide some screenshots or a screen record :pray: 
Waiting for your feedback.

Thanks!

**Comment by Tomi1444** [comment]
This is what it looks like

![image](https://github.com/PrestaShop/PrestaShop/assets/118079647/28c34c1b-b8ea-4d18-ba2f-970ec76153f2)

**Comment by AureRita** [comment]
Hi @Tomi1444 

Thank you for your report, can you give us the version of autoupgrade that you use ? 
Did you try when you disable your module "crazy Element page builder" ? 

Waiting for your feedback

**Comment by Tomi1444** [comment]
That not help. I even disabled all non presta modules, but still the same results.
Version 4.16.3, and last few tries 4.16.4

**Comment by Tomi1444** [comment]
If I try update to 8.1, update succesful, but when I try to get into BO I got this message:

```
"Attempted to call an undefined method named "jsonDecode" of class "Tools".

[Symfony\Component\ErrorHandler\Error\UndefinedMethodError 0]"
```

**Comment by Tomi1444** [comment]
Today when I try to update to 8.1.2


I have this two messages:

![image](https://github.com/PrestaShop/PrestaShop/assets/118079647/7ba2ca3b-9225-4347-ae21-a045833ae571)


and second error:

![image](https://github.com/PrestaShop/PrestaShop/assets/118079647/ff19cb4f-3185-46a1-b33a-d7d21ef310ee)

**Comment by giacant** [comment]
I have exactly the same problem, but updating prestashop 1.7.8.8 to 1.7.8.10 using 1 click upgrade 4.16.4
![Screenshot 2023-11-14 103845](https://github.com/PrestaShop/PrestaShop/assets/17580291/b3c28783-1690-4e8f-9761-68c64ac40a98)

**Comment by Tomi1444** [comment]
I'll tell you what helped me.

The first time, when I had no idea, I went to the folder with my backups. I chose a copy from around February 2022.
I took the /SRC folder and completely replaced it with the one on the server.
I performed the update and everything went smoothly.

Unfortunately, I had to restore the backup from a few days ago, and this time I decided not to copy the entire SRC folder, but somehow I found out that the whole thing had to be uploaded: /VENDOR/EGULIAS

And it helped :)
Since then, after updating, the problem has not occurred again, and I keep SRC and EGULIAS in a separate backup.
[egulias.zip](https://github.com/PrestaShop/PrestaShop/files/13352624/egulias.zip)
[src.zip](https://github.com/PrestaShop/PrestaShop/files/13352635/src.zip)
(I hope these folders do not contain my data)

**Comment by giacant** [comment]
It works! the upgrade end correctly, but when i try to load backoffice, i have this error:

gument 2 passed to PrestaShop\Module\Mbo\ModuleCollectionDataProvider::__construct() must be an instance of PrestaShop\PrestaShop\Core\Addon\Module\ModuleRepositoryInterface, instance of ModuleRepository_091bb2f given, called in /var/www/vhosts/xxxxxxx/httpdocs/var/cache/dev/ContainerPO2szGg/getMbo_Adapter_ModuleCollectionDataProviderService.php on line 9

**Comment by giacant** [comment]
Thank you, with your files at least i could upgrade to 1.7.8.10.... do you think that with this version  i can upgrade to 8.1 without problems?

**Comment by Quetzacoalt91** [comment]
Although I cannot explained how it happened, it looks like an upgrade to the v8 branch has been executed. If you still have your log file, can you check and/or share it?
It can be found in `<admin_folder>/autoupgrade/tmp/log.txt`, and you should find inside it details about the release that has been downloaded, for instance:

```
[2024-04-10 15:13:34] Starting upgrade...
[2024-04-10 15:13:34] Shop deactivated. Now downloading... (this can take a while)
[2024-04-10 15:13:34] Downloaded archive will come from https://github.com/PrestaShop/PrestaShop/releases/download/1.7.8.11/prestashop_1.7.8.11.zip
[2024-04-10 15:13:34] MD5 hash will be checked against d29d55f89a2c44bef3d5c51b70e3a771
[2024-04-10 15:13:34] Downloading from https://github.com/PrestaShop/PrestaShop/releases/download/1.7.8.11/prestashop_1.7.8.11.zip
[2024-04-10 15:13:34] File will be saved in /var/www/html/admin-dev/autoupgrade/download/prestashop.zip
[2024-04-10 15:13:34] Download directory has been emptied
[2024-04-10 15:14:14] Téléchargement terminé.
[2024-04-10 15:14:14] Download complete. Now extracting...
[2024-04-10 15:14:14] &quot;/latest&quot; directory has been emptied
```

Before sharing content, you may need to remove references to your actual back-office folder.

**Comment by Quetzacoalt91** [comment]
I don't understand how this file appeared on the shop while upgrading to PS 1.7 as it was pushed for the first time in the branch 8.0.x.
![image](https://github.com/PrestaShop/PrestaShop/assets/6768917/276b4b48-0ccb-45ee-8abf-d6db1ebf5d00)

We did not manage to reproduce this error during the previous month and the thread seems to be inactive. I'm closing the issue but remain available in case you get this error later with more information to reproduce.
