### ISSUE TITLE
Help not displaying on the PrestaShop dashboard of Products

### ISSUE THREAD

**Issue by AsgadKodithodika** [PrestaShop/PrestaShop#33917]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi team,

As you see in the below image, the Help section is not displaying in the Product section!
![screenshot-herba flysoft dev-2023 09 12-11_53_15](https://github.com/PrestaShop/PrestaShop/assets/108669841/793abe0e-9fce-411f-95b3-9517eef76f6e)

Why is this happening? Could you please solve this issue?

Regards

### Steps to reproduce

1. Go to Catalog
2. Select Products
3. Click on any products listed
4. Now, click on the 'Help' button on the right top side

### PrestaShop version(s) where the bug happened

1.7.8.8

**Comment by sallemiines** [comment]
Hello @AsgadKodithodika 

Ping @sersis-dev I saw your [comment](https://github.com/PrestaShop/PrestaShop/issues/33902#issuecomment-1713613582) on the other issue.
But this issue was fixed with 1.7.8.0 and on 8.1.1 I didn't encounter the issue, see the attached screen record below:

[issue_33917.webm](https://github.com/PrestaShop/PrestaShop/assets/31663369/abee5fed-f786-41a1-ac55-d266e5e73c1c)

![image](https://github.com/PrestaShop/PrestaShop/assets/31663369/e543caf2-af32-4445-8a4f-13a198df85f7)

Please check and feedback.

Thanks!

**Comment by matks** [comment]
@AsgadKodithodika I suggest to open Developer console and check Network tab. You should be able to see 1 line of error when you open the Help page and it might tell you what is the problem

**Comment by AsgadKodithodika** [comment]
Hi,

As you see in the video, it is not visible in my PrestaShop
[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023.09.13-09_40_07.webm](https://github.com/PrestaShop/PrestaShop/assets/108669841/6627b894-b693-4973-9483-2c84d725e7f8)

Is there any solution to display it?

Best regards

**Comment by sersis-dev** [comment]
Hi,
I have the same problem as @AsgadKodithodika and as suggested by @matks I opened the Developer console and checked the Network tab.
I see an url similar to this with 404 http response: https://www.mysite.com/manager/index.php/common/sidebar/https%253A%252F%252Fhelp.prestashop.com%252Fen%252Fdoc%252FAdminProducts%253Fversion%253D1.7.8.9%2526country%253Den/Help?_token=uSJZf9vGOPqO0pC3dLA1as9TG2gIKAvj9G6joChSQ1g

where "www.mysite.com/manager" is the my site's backoffice url.

Best regards.

**Comment by matks** [comment]
I reproduce the issue
1. Install PrestaShop 1.7.8.10
2. Go to any back-office page, open the contextual help by clicking the "Help" button on the right
3. It opens a blank page

![Capture d’écran 2023-09-13 à 15 02 11](https://github.com/PrestaShop/PrestaShop/assets/3830050/8dc64cf3-d1c0-43e0-8929-92ccfa2dbdd1)


The root cause is that help.prestashop.com returns blank result. My shop attempts to load content from https://help.prestashop.com/en/doc/AdminCustomers?version=1.7.8.10&country=en and result is blank

It is likely all users of PrestaShop 1.7.x are impacted while users of PrestaShop 8.x are not impacted because PrestaShop 8.x use https://help.prestashop-project.org/ which works well

**Comment by MatShir** [comment]
https://help.prestashop.com/en/doc/AdminCustomers?version=1.7.8.10&country=en is working again ! 🥳 
Could you try again see if it works on your side ?

**Comment by MatShir** [comment]
Closing the issue. Don't hesitate to report if it fails again !

**Comment by matks** [comment]
Thank you @djodjo3 for that @JMorinPS !

**Comment by sersis-dev** [comment]
Hi,
unfortunately it still doesn't work on my site.
If I click on the link of @MatShir , I see everything correctly. If I try from the help button in the backoffice I still don't see anything. This is what I see:
![sidebar_help_bis](https://github.com/PrestaShop/PrestaShop/assets/118921057/55749b8b-80e7-4c61-b2d7-d37cfcc6d3c6)

Best regards.

**Comment by MatShir** [comment]
Could you try again and share the link from the console (change your domain name)  ? I'm very surprised about this error. On my side, everything works fine. Maybe a issue from your server provider ? 🤷

**Comment by sersis-dev** [comment]
The link in the console is:
https://www.mysite.com/manager/index.php/common/sidebar/https%253A%252F%252Fhelp.prestashop.com%252Fen%252Fdoc%252FAdminProducts%253Fversion%253D1.7.8.9%2526country%253Den/Help?_token=Gw4Akxc-RRjm__MKI9mTsldnnCTnF5IJdqBJDQmV41U
where "www.mysite.com/manager" is the my site's backoffice url.

Maybe, I do not know. I'll try to check.

Thank you for your help.

**Comment by MatShir** [comment]
Your link on my domain seems to work. I suggest to check with the provider. Sorry for the inconvenience :/

**Comment by sersis-dev** [comment]
Sorry for the delay in the response.

To verify the problem what should I tell the provider to check?
All other links seem to work fine.

Thank you.

**Comment by MatShir** [comment]
Why can't you access to the link from your server (when all the links work perfectly fine) ?

**Comment by MatShir** [comment]
in the meantime, here the doc https://docs.prestashop-project.org/1.7-documentation/

**Comment by sersis-dev** [comment]
HI.
I did several tests, so as to better present the problem.

On the site I added the following instruction to the web.config file:
<security>
            <requestFiltering allowDoubleEscaping="true" />
        </security>
In this way, the loading of the sidebar no longer fails, but a redirect is made to the dashboard, with an orrible result.
![sidebar-dashboard](https://github.com/PrestaShop/PrestaShop/assets/118921057/258c7686-dc00-43d5-88b7-ca0108713444)

So I also tested it with an empty new prestashop, without any particular themes.
For example, in the Catalog:
if I don't have any products, the sidebar doesn't open, but a redirect is made to the url https://help.prestashop.com/en/doc/AdminProducts?version=1.7.8.9&country=en
![redirect-site](https://github.com/PrestaShop/PrestaShop/assets/118921057/1038a4d5-cbb0-4f9e-b1d0-6d79f5f8240b)


if I add even just one product, the sidebar appears and does not load or it sends me back to the dashboard if I insert the above instruction in the web.config

Do you have any ideas?

Could it be a problem of special characters being coded twice (for example %3D to %253D )?
if so, how can it be resolved?

Thank you for your help.
