### ISSUE TITLE
Problem with loading shopping cart

### ISSUE THREAD

**Issue by Frits1969** [PrestaShop/PrestaShop#33915]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

I use Prestashop 1.7.8.10 with the "shopping cart" module.

When a visiter opens the shopping cart, it lookslike that it's loading all the time.
The customers wait until it has finished loading. He may already be, because everything seems to be working.

How can I fix this? Or is there a update?

Kind regards,
Frits van Leeuwen

### Expected behavior

No waiting cerkle line when done.

### Steps to reproduce

1. be a visitor of the webshop.
2. go to the shopping cart.
3. then you see the problem.

### PrestaShop version(s) where the bug happened

1.7.8.10

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

ps_shoppingcart V2.0.7

### Your company or customer's name goes here (if applicable).

Geschenkenlaantje

**Comment by sallemiines** [comment]
Hello @Frits1969 

I didn't manage to reproduce the issue with PS811, see the attached screen record below:

[issue_33915.webm](https://github.com/PrestaShop/PrestaShop/assets/31663369/466eb08c-ea8e-4b37-a9d6-9dcfc8bc0f30)

Please check andf feedback.

Thanks!

**Comment by Frits1969** [comment]
@sallemiines,
thanks for the quick reaction. 
For this problem, it doesn't matter if AJAX is on or off. They both gives the same result.
And also it doesn't matter how many products there are in the cart.

May be you can take a look at [https://geschenkenlaantje.nl ](https://geschenkenlaantje.nl ) that's my webshop.

**Comment by sallemiines** [comment]
Hello @Frits1969 

Well, I couldn't access to your shop :disappointed: But if you're using a cutomized theme, please switch to CLASSIC theme and check if you still encounter the issue. Cause I didn't with Classic theme.
Waiting for your feedback.

Thanks!

**Comment by Frits1969** [comment]
Thanks again for the response and suggestion.
I want to try to activate the Classic template. But I do need some peace and time for that. I'm in the middle of a renovation now. That takes several days.
The templete classic is the basis of my current template. Is it true that if I rename custom.css, the classic is standard again. so without my more personal changes?

**Comment by Frits1969** [comment]
I renamed the custom.css 
So I use the theme classic. But with the same result. It still had the waiting cirkle line.
Now I renamed it back, because I want my own look of the site.
I took a better look. I found this. Look at the picture.
![Schermafbeelding 2023-09-15 122619](https://github.com/PrestaShop/PrestaShop/assets/28409740/cf37e19a-aae7-475d-bb94-e140725607e2)

**Comment by hibatallahAouadni** [comment]
Hello @Frits1969 

Are you using any third-party modules? if so, could you please disable it and check if you still encounter the issue.
Waiting for your feedback.

Thanks!

**Comment by Frits1969** [comment]
I found the trouble maker. It is "Bonus cashback sustem" of Ewonta. I'll tell them and I hope they have an answer.

**Comment by florine2623** [comment]
Hello @Frits1969 ,

I'm closing the issue as it is not a PrestaShop core issue ^^
