### ISSUE TITLE
CSV Import Issue

### ISSUE THREAD

**Issue by guycowling** [PrestaShop/PrestaShop#33916]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I import a Combinations csv file, the Quantities are all zeroised.
This only happened after our upgrade to 1.7 from 1.6 last year.
One of the guys at Prestashop Support fixed this issue for me in April this year but now it seems to have stopped working again.
Can you please fix this again?
Guy

### Expected behavior

Quantities should not be zeroised.

### Steps to reproduce

Go to CSV Import
Then Combinations
Choose File and Upload

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

Not sure

### Your company or customer's name goes here (if applicable).

Cowling & Wilcox, Guy Cowling

**Comment by sallemiines** [comment]
Hello @guycowling 

Could you please check this issue #23083 seems similar to yours.
Waiting for your feedback.

Thanks!

**Comment by guycowling** [comment]
Hi

Yes, that sounds about right.
As I said, it was fixed but now seems to be having the same issue again.
In April it was fixed.
In July it reverted back to the bug again.

Kind regards
Guy Cowling

**Comment by hibatallahAouadni** [comment]
Hello @guycowling 

Thanks for your feedback.
We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #23083. 
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thanks!

**Comment by hibatallahAouadni** [comment]
Duplicate of #23083

**Comment by guycowling** [comment]
Hi

This is a major issue for us as we use CSV Imports a lot.
Is there any way we could get this expedited?

Kind regards
Guy Cowling
Cowling & Wilcox Ltd
Tel: 01303 290 555
Mob: 07710 445142
www.cowlingandwilcox.com<http://www.cowlingandwilcox.com/>
www.portfoliosplus.com<http://www.portfoliosplus.com/>

 Official Site<https://www.cowlingandwilcox.com/>  ·  Portfolios Plus<https://www.portfoliosplus.co.uk/>

***@***.***<https://www.facebook.com/cowlingandwilcox>    ***@***.*** <https://www.instagram.com/cowlingandwilcox/>     ***@***.*** <https://twitter.com/cowlingwilcox>     ***@***.*** <https://www.youtube.com/channel/UCpByNWN_CTO7ZFOmxl2Ec1w>
***@***.***<https://www.cowlingandwilcox.com/>
