### ISSUE TITLE
Uncaught error: Syntax error, unrecognized expression: in main.bundle.js 

### ISSUE THREAD

**Issue by Aleafrank** [PrestaShop/PrestaShop#33920]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Good morning;

I am writing because I have a problem with PrestaShop 8.1.

Let me tell you, I have imported my product list into Prestashop as I usually do, using a file created in Excel or sublime text - encoded CVS (ISO-8859-1 --from-code=UTF-8) and everything is perfect.

But once I enter the product catalog and select a product to modify, I cannot, any modification I make does not give me the option to save it, nor does it give me the option to add images, or modify price, or categories. (I can change it but the save and publish button is disabled)

This only happens with the products that I have exported, I have created a product manually and the same thing does not happen.

Made two new installations, both on localhost and on the server and the same thing happens. The error is the following.

(image 1) Uncaught error: Syntax error, unrecognized expression: in main.bundle.js file

Image 2 When you add these characters in the meta description <.,"'¡!¿?`´[]{}@=/%&#$| the error in image 1 appears
![imagen1](https://github.com/PrestaShop/PrestaShop/assets/125338827/1df185e2-1b28-418a-81c3-be2d94d7140f)
![imagen2](https://github.com/PrestaShop/PrestaShop/assets/125338827/4c81f36d-f12d-428a-9f29-faf6444ce093)

### Steps to reproduce

1. Go a product
2. Click edit product
3. Scroll through all product descriptions, images, SEO, price.
4. Cannot edit: Save changes button disabled - error in console - Syntax error

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.0/8.2

**Comment by sallemiines** [comment]
Hello @Aleafrank 

> This only happens with the products that I have exported

You means the products that you have imported, is that so? 
And could you please provide the csv file and the import configuration that you used :pray: 
BTW, it seems another contributor encountered a similar issue, check #33704
Please check andf feedback.

Thanks!

**Comment by Aleafrank** [comment]
Hello, I had already seen the other contribution and I have done nothing, everything and nothing,

My CVS file is correct, I have done the export on another website 8.0.4 and it does not give an error.

Now I have tried to create the products in .xlsx and the error continues.

**Comment by MatShir** [comment]
@Aleafrank Could share an example file .xlsx that cause errors, so we can reproduce the issue in our side. It will help for debugging :)

**Comment by hk-pack** [comment]
I just had the same problem. This is an error in description_short in ps_product_lang, a special character may cause troubles and closes javascript files.. Not all my products were impacted by this bug (~15.000 products imported with CSV)

What will I do : Download all description_short by sql, replace the string, update table.

Edit : Actually this is weird, the value in description_short doesn't have <p> but description does in the database.
In wysiwyg editor description_short have <p> 

Edit 2 : I deleted all specials chars 1 by 1 (î,é,:,.) in database in description_short, and this is good now...

**Comment by gianluca77** [comment]
Hi, I just found that in mysql db ps_product_lang the description_short field WANTS a `<p></p>` to wrap the text else it will give the syntax error!!! So if you pragmatically insert from csv you have to wrap the description_short between the `<p></p`> tags.
For example`<p>`you description!`</p>` works and does not give the JS error in product edit.
It is a bug from ps 8.1.1, needs to be solved because it is unfashionable to have to use a paragraph tag to make it work.

**Comment by Aleafrank** [comment]
Hello, for now I have been able to solve the problem, deactivating in Prestashop 8.1, all the functions of "New and experimental features"

Once I deactivated them, I was able to edit the catalog and combinations without problems.

**Comment by paulnoelcholot** [comment]
Hello @Aleafrank,

I tried to reproduce your issue but as you can see, I can't : 
[Products • the future (3).webm](https://github.com/PrestaShop/PrestaShop/assets/112863083/8bba6086-7778-41a9-a4d9-8acd2f0ca7a5)

Did I miss something?

Thank you for your feedback!

**Comment by jibayski** [comment]
Hello @paulnoelcholot 

If you want to reproduce this issue just add slash to the product name. In our store we have products model like 1/2/c/2 and when i save a product with this in name and then try to change something this error occurs.

Thank you for your feedback!

**Comment by paulnoelcholot** [comment]
@jibayski 

I just did it and it's the same. I don't reproduce the issue : 
![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/1a9dbbfc-43b0-4541-bec2-153dded479d1)

**Comment by paulnoelcholot** [comment]
Hello @Aleafrank,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Comment by doominio** [comment]
> Hello, for now I have been able to solve the problem, deactivating in Prestashop 8.1, all the functions of "New and experimental features"
> 
> Once I deactivated them, I was able to edit the catalog and combinations without problems.

I'm having the same problem and this solution worked for me, but I'm interested in finding the root cause of the problem.

**Comment by hk-pack** [comment]
Hello actually, I solved all of these problems by correcting the translations.

When you translate some variable in translations menu, that close some javascripts tags

Exemple : 
**script's** 

Result in html : 

let var = 'script's'; <=== the translation is closing the tag.

This is a common issue in prestashop.

Hope, that could help, check your console to see where are the problems

**Comment by doominio** [comment]
Thanks @hk-pack , that's not my particular case though. In the console I get "Error: Syntax error, unrecognized expression:" followed by the actual content of the summary description field.

**Comment by hk-pack** [comment]
@doominio, can you show us the javascript part please?

**Comment by doominio** [comment]
The javascript that errors is `[main.bundle.js:660:10037](https://DOMAIN/ADMINDIRECTORY/themes/new-theme/public/main.bundle.js)`

**Comment by tippysrl** [comment]
I am having the same issue, which is caused - as stated before - by missing paragraph tag in the imported description.
I followed the solution suggested in this similar thread, and it worked for me:
https://github.com/PrestaShop/PrestaShop/issues/11911#issuecomment-999447540

**Comment by RosaBenouamer** [comment]
Seems to be similar to https://github.com/PrestaShop/PrestaShop/issues/34347
