### ISSUE TITLE
Can't upgrade from 8.0.2 - Your current version of the module is out of date.

### ISSUE THREAD

**Issue by KungMatsW** [PrestaShop/PrestaShop#33926]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
I have the same kind of issue. I can't upgrade my 8.0.2.
I'm told: "Your current version of the module is out of date. Update now".
But there is nothing to upgrade and I do have latest module.

I do have the latest v4.16.2 autoupgrade modul.
All list points is green checked
I have cleared the /var/cache as told in other threads.
I have cleared the cache from back office
I have uninstalled the v4.16.2 autoupgrade modul and reinstalled it.
I have deleted the autopupgrade folder and installed the v4.16.2 autoupgrade modul again.
NOTHING helps!
![333](https://github.com/PrestaShop/PrestaShop/assets/118338163/9098fb7f-0c80-42ae-8257-1d14722b7939)
![222](https://github.com/PrestaShop/PrestaShop/assets/118338163/1c3b922e-0817-4d2d-bd54-92bfa334d13a)
![111](https://github.com/PrestaShop/PrestaShop/assets/118338163/b5129374-6786-4386-bbd7-b159cc93badf)
[log.txt](https://github.com/PrestaShop/PrestaShop/files/12595025/log.txt)

### Steps to reproduce

1. go to 1-Click upgrade module and you see the issue right away

### PrestaShop version(s) where the bug happened

8.0.2

### PHP version(s) where the bug happened

8.2

### If your bug is related to a module, specify its name and its version

Autoupgrade v4.16.2

**Comment by Hlavtox** [comment]
@KungMatsW Latest version is https://github.com/PrestaShop/autoupgrade/releases/tag/v4.16.3, install it and you will be able to upgrade.

Not sure why it doesn't offer you the upgrade on module list though, the endpoint is correct - https://api.prestashop-project.org/modules/8.0.2.

Do you have Distribution API module installed?

**Comment by KungMatsW** [comment]
1) Thank you very much @Hlavtox ! .. YOU MADE MY DAY  🌟🌟🌟🌟🌟

2) I don't know. I don't recognize "Distribution API"
What is it?
I can see I don't have it installed. Should I install it?

**Comment by Hlavtox** [comment]
Yes, from 8.0.0, Distribution API module is responsible for providing online updates of native modules. Install it - https://github.com/PrestaShop/ps_distributionapiclient/releases/download/v1.1.0/ps_distributionapiclient.zip and you will get updates.

**Comment by Hlavtox** [comment]
@PrestaShop/qa-functional You can close this

**Comment by sallemiines** [comment]
Thanks @Hlavtox for your quick reply :wink:

**Comment by MatShir** [comment]
FYI: The API that check the upgrade inside the module autoupgrade is https://api.prestashop.com/xml/channel.xml. So super strange, the bug :/
