### ISSUE TITLE
BO-Increase front office security option have no effect on FO

### ISSUE THREAD

**Issue by aniszr** [PrestaShop/PrestaShop#33932]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In BO > Shop Parameters > General when you enable this option `Increase front office security` and login into customer account in FO a Token should be generated with POST method in order to increase front office security.

When inspect the FO, there is no token generated on Network tab and all displayed methods are GET!

See attached screenshot:

![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/95671b9c-7c65-467a-b9c1-7e1ab5356006)

Same result no matter the option `Increase front office security` is **Enabled** or **Disabled**

 =>The feature has no visible effect on FO

### Expected behavior

- A token should be generated with POST method
- The token should have an expiry time so the session disconnect automatically for security reasons
- When inspecting the FO the token should be displayed with POST method

See attached screenshot for token in **BO**:

![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/832a1653-cf94-4b0c-b17d-ded0cd80edd3)

### Steps to reproduce

1. BO > Shop Parameters > General 
2. Enable **Increase front office security** toggle switch button
3. Go to FO > Sign in
4. inspect > look in Network tab
5. See error : no Token displayed in the list
6. Disable **Increase front office security** toggle switch button
7. Refresh FO > inspect > look in Network tab
8. See error : no Token displayed in the list

![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/7b762dbc-88d6-459b-abd6-16db2c865f5b)

### PrestaShop version(s) where the bug happened

8.1.1 & Develop

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment]
@aniszr The token is enabled only for functionality regarding adding and removing to cart.

Inspect the delete button on cart page and you will see that token is there. :-) `http://localhost/81x/gb/cart?delete=1&id_product=8&id_product_attribute=0&token=c2e8c8b3cc227f4781cc2200f7c78ce1`

**Comment by aniszr** [comment]
Hello @Hlavtox 

Thanks for your feedback!

I found the Token as you mentioned, see attached screenshot:

![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/9ba00a90-cd9b-4625-9b59-020d83b373b0)

But I still don't see the impact of the BO option `Increase front office security` on the FO the token exists in all cases!!

Thanks!

**Comment by Hlavtox** [comment]
It's not meant to work like that, you don't need any token in FO. The token is there just to prevent CSRF attacks. Well attacks... Is it even an attack if you add something to your cart by a link.

**Comment by Hlavtox** [comment]
@aniszr The difference is that the token is not validated if that option is disabled. It works correctly. :) I suggest closing this.

**Comment by djoelleuch** [comment]
Hello @aniszr  
i will close the issue .
thank you
