### ISSUE TITLE
prestashop install stucks  on 75% 

### ISSUE THREAD

**Issue by mikajaxxx** [PrestaShop/PrestaShop#33938]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello
prestashop installation stucked on 75% . the screenshot has been attached
i tested on two seperate servers, but same error!
![Screenshot 2023-09-14 at 12-37-13 PrestaShop Installation Assistant](https://github.com/PrestaShop/PrestaShop/assets/5157272/a76dee66-4d12-47d7-bf5d-a5807b7a0192)

### Expected behavior

prestashop install correctly

### Steps to reproduce

1 uploaded prestashop install file on subfolder of subdomain
2 run the installation
3 install progress stops on 75% with attached error

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

8.1 (open litespeed)

**Comment by MatShir** [comment]
Currently under investigation. I will let you know when it is fixed

**Comment by MatShir** [comment]
It should be fixed now ! I'm closing the issue. if you are facing new pbs don't hesitate to comment this issue or create a new one. :)

**Comment by mikajaxxx** [comment]
> It should be fixed now ! I'm closing the issue. if you are facing new pbs don't hesitate to comment this issue or create a new one. :)

It is not fixed! do i should download prestashop again?

**Comment by MatShir** [comment]
Yes! Please redownload it again. 🙏

**Comment by mikajaxxx** [comment]
Hello
Yeah after downloading agian the problem have been solved
tnx
