### ISSUE TITLE
Unable to add a specific price per combination

### ISSUE THREAD

**Issue by m4ikel** [PrestaShop/PrestaShop#33942]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When editing a product with combinations, the user is unable to select a specific combination within the "Add new specific price" modal / iframe.

Console shows error:
Uncaught TypeError: this.getShopIdSelect() is null init /backoffice/themes/new-theme/public/specific_price_form.bundle.js?8.1.1:254

Error can be reproduced on client and demo.

[Image of error and bug](https://ibb.co/Phdt3qB)

### Expected behavior

List of available combinations, so the user can set a unique price

### Steps to reproduce

1: Go to https://demo.prestashop.com/#/en/back
2: Login.
3: Open Catalog / Products.
4: Select a random product with combinations.
5: Go to the price tab.
6: Click "Add a specific price".
7: Note "Combinations" does not have options, while combinations are available.
8: Note console log shows error.

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.X

**Comment by MhiriFaten** [comment]
Hello  @m4ikel ,

It seems that your issue is related to demo PrestaShop.

I can not reproduce it, You should install a PrestaShop version

![image](https://github.com/PrestaShop/PrestaShop/assets/111756615/87ec71a4-b497-4808-83cd-9390bc7d266e)

We will close this issue.

Thank you

**Comment by m4ikel** [comment]
@MhiriFaten We experience the same issue on a client's production website. So this is not only related to the demo environment (so you are able to reproduce it). Following, we have reproduced the issue on the live demo.

**Comment by m4ikel** [comment]
@MhiriFaten 

I've debugged the issue: On line: 254 of specific_price_form.bundle.js 

`getShopIdSelect(){return document.querySelector(${i} ${h})}}` is attempting to fetch a select field `form[name="specific_price"] #specific_price_groups_shop_id`, but on a single site website (without a multi store website added) this select isn't being generated, hence causing a JS error, which stops rendering the select2 component.

See line: 134 of /src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/ApplicableGroupsType.php

`if ($this->isMultiShopEnabled) {`

Disabling this if statement will resolve the issue, or the specific_price_form.js should be altered to ignore the missing specific_price_groups_shop_id field.

**Comment by hibatallahAouadni** [comment]
Hello @m4ikel 

Are you using the PrestaShop edition (did you download it from the prestashop site)?
Cause with OS version (downloaded from github), I didn't reproduce the issue.
Waiting for your feedback.

Thanks!

**Comment by m4ikel** [comment]
That is strange, I will retry to do a fresh install and report the steps back asap.
