### ISSUE TITLE
FO - Cart - Alert message is not correct in cart when the stock is low

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#33947]
### Describe the bug and add attachments

There are two issues on cart page.
- When product is no longer available, the error you get is different:
  - If you refresh the page cleanly
  - If you change amounts in arrows.
- When there is an error and you change quantity of another product that is in stock, the error disappears and you can continue checkout. It will redirect you back, but it's wrong.

### Expected behavior

- The error must be always the same. It should probably only be `Mug Today is a good day is no longer available in this quantity. You cannot proceed with your order until the quantity is adjusted.`
- If there is an error, it can't be cleared after doing a valid action.

### Videos 

https://github.com/PrestaShop/PrestaShop/assets/6097524/67dda64b-0c56-45d0-b0c4-8152fec8c383

https://github.com/PrestaShop/PrestaShop/assets/16019289/4d74199b-7f4b-4dd9-a3bf-dc7a3d1f485c

### Steps to reproduce

1. Create 2 products. Product A will have quantity 1 and disabled backorders. Product B will have quantity 300 and enabled backorders.
2. Add both products to cart. Go to cart.
3. Change quantity of Product A to 2. See one error.
4. Refresh page, see different error. 🔴 <- You should get the same one?
5. Change quantity of Product B. See that the error disappears and you can apparently continue checkout. 🔴

You can reproduce the issue with those easier steps :
1. Add 2 products "Mug Today is a good day" to you cart
2. Go to BO > Catalog > Products > Edit "Mug Today is a good day"
3. Edit quantity to 1 > Save
4. Edit Minimum quantity for sale : 2 > Save
5. Go to FO > Cart
6. Edit quantity
7. See alert message is incorrect :x:
8. You can still click on proceed to checkout even thought the product is not available anymore :x:

### PrestaShop version(s) where the bug happened

8.1.x, develop

### PHP version(s) where the bug happened

8.1

**Comment by djoelleuch** [comment]
Hello @florine2623  

Following your steps I didn't manage to reproduce your issue ! 

8.1.x : 

[Untitled_ Sep 15, 2023 3_50 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/bca32477-e739-4ea1-9285-668c4d96caa9)

Develop : 


[Untitled_ Sep 15 2023 4_01 PM (1).webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/ec4e04f3-8505-4520-befb-48c055a2ed8b)

could you please check again !
Waiting for your feedback.

Thanks!

**Comment by Hlavtox** [comment]
@djoelleuch It's reproduced by me and @MhiriFaten. And you also reproduced it on your video. :-)
