### ISSUE TITLE
Can't load large number of categories on product edit page

### ISSUE THREAD

**Issue by Caleydon** [PrestaShop/PrestaShop#33944]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I imported existing catalog from PS 1.6 into PS 8.1.1. with 1200 categories 

The product edit page now can't load such amount of categories. On the edit page (version 1) I get blank page, in version 2 (in PS 8.x) modal window with category tree is blank. 

So PrestaShop is unusable and the merchants can't migrate on PS 1.7.x and 8.x with categories above aprox. 400+.

### Steps to reproduce

1. Install PrestaShop
2. Import 400+ categories
3. Go to product edit page

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment]
Hi @Caleydon, could you provide an SQL file with all tables `ps_category*`? Anonymized with some random names and descriptions.

**Comment by Hlavtox** [comment]
Investigated privately, caused by invalid data structure:

```
INSERT INTO `ps_category` (`id_category`, `id_parent`,...
(409, 417...
(417, 409...
```

and this loop:
https://github.com/PrestaShop/PrestaShop/blob/47549203f866d63f811ad72f479d81039a013d35/src/Adapter/Category/CategoryDataProvider.php#L204
