### ISSUE TITLE
Problème sur le front office, les produits associés "vous pourriez aussi aimer tel ou tel produit" n'apparaissent plus

### ISSUE THREAD

**Issue by ALICEOBI** [PrestaShop/PrestaShop#33948]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Sur mon back office, sur chaque fiche produit, j'ai bien associé d'autres produits de mon catalogue mais je me suis aperçu qu'ils n'apparaissent plus sur les fiches produits de mon front office,  alors que je n'ai rien changé

### Expected behavior

![Capture d’écran (21)](https://github.com/PrestaShop/PrestaShop/assets/145126939/80ed0617-6d32-40ea-ad37-3f6c3393e805)
![Capture d’écran (22)](https://github.com/PrestaShop/PrestaShop/assets/145126939/84c569ef-b65d-47e8-b6fb-bddfcb3d2ac4)

### Steps to reproduce

![Capture d’écran (25)](https://github.com/PrestaShop/PrestaShop/assets/145126939/da43d3dd-709a-40d9-be06-7124edcacbb9)

### PrestaShop version(s) where the bug happened

1.7.6.7

### PHP version(s) where the bug happened

7.2.28

### If your bug is related to a module, specify its name and its version

je pense que c'est à cause du module creative element

### Your company or customer's name goes here (if applicable).

obialice

**Comment by venditdevs** [comment]
Please provide the content in English, it's an international community and the use of the English language is mandatory.

**Comment by djoelleuch** [comment]
Hello @ALICEOBI  ,

Please send your request in English. English is the norm on GitHub.

Thank you
