### ISSUE TITLE
Undefined context currency in actionCartSave

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#33953]
### Describe the bug and add attachments

There is a fatal error if there is a module hooked to `actionCartSave` that is doing something with currency (for example ps_googleanalytics) and the cart needs to be updated on these two places.

https://github.com/PrestaShop/PrestaShop/blob/5314c7dbc7a745f5d8aed42c681a7b88c6ff1e15/classes/controller/FrontController.php#L361

https://github.com/PrestaShop/PrestaShop/blob/5314c7dbc7a745f5d8aed42c681a7b88c6ff1e15/classes/controller/FrontController.php#L379

### Stack trace
```
PHP Fatal error: Uncaught PrestaShop\\PrestaShop\\Core\\Localization\\Exception\\LocalizationException: Price specification not found for currency: ""
in /var/www/vhosts/domain.cz/httpdocs/src/Core/Localization/Locale.php:171

Stack trace:
#0 /var/www/vhosts/domain.cz/httpdocs/src/Core/Localization/Locale.php(155): PrestaShop\\PrestaShop\\Core\\Localization\\Locale->getPriceSpecification('')
#1 /var/www/vhosts/domain.cz/httpdocs/classes/Tools.php(776): PrestaShop\\PrestaShop\\Core\\Localization\\Locale->formatPrice(52.231405, NULL)
#2 /var/www/vhosts/domain.cz/httpdocs/classes/Product.php(5567): ToolsCore::displayPrice(52.231405, NULL)
#3 /var/www/vhosts/domain.cz/httpdocs/modules/ps_googleanalytics/classes/Hook/HookActionCartSave.php(96): ProductCore::getProductProperties(1, Array)
#4 /var/www/vhosts/domain.cz/httpdocs/modules/ps_googleanalytics/ps_googleanalytics.php(203): PrestaShop\\Module\\Ps_Googleanalytics\\Hooks\\HookActionCartSave->run()
#5 /var/www/vhosts/kidspara...', referer: https://domain.cz/kosik?action=show
```

### Cause
The issue is caused by currency being initialized at the right place here:

https://github.com/PrestaShop/PrestaShop/blob/5314c7dbc7a745f5d8aed42c681a7b88c6ff1e15/classes/controller/FrontController.php#L318

But assigned to the context all the way on the bottom:

https://github.com/PrestaShop/PrestaShop/blob/5314c7dbc7a745f5d8aed42c681a7b88c6ff1e15/classes/controller/FrontController.php#L430

### Solution
Assign currency to the context right away.
PR to fix this: https://github.com/PrestaShop/PrestaShop/pull/33954

### Expected behavior

No error should be thrown

### Steps to reproduce

1. Make sure [tox_carttest.zip](https://github.com/PrestaShop/PrestaShop/files/12718116/tox_carttest.zip) is installed.
2. Go to FO, add two products to cart.
3. Go to cart page.
4. Change language with switcher in header.
5. Error.
6. Apply my PR, it will work fine.

### PrestaShop version(s) where the bug happened

1.7.6.0, 8.1.x, develop

### PHP version(s) where the bug happened

7.3, 8.1

### If your bug is related to a module, specify its name and its version

ps_googleanalytics

**Comment by florine2623** [comment]
Hello @Hlavtox ,

I can't reproduce your issue on `develop` :/

I have followed your steps correctly.

<img width="924" alt="Screenshot 2023-09-20 at 16 58 11" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/99a2156f-383f-4a72-b33c-8c87400bcab7">
<img width="1096" alt="Screenshot 2023-09-20 at 17 01 40" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/d44a2f4b-b958-4c76-a247-fdbd261e4973">

When I go back to my cart page and delete some article, I don't have an 500 error :


https://github.com/PrestaShop/PrestaShop/assets/16019289/5d9cd6e8-3103-4269-b273-badd40d728c1

Am I missing something ?

**Comment by Hlavtox** [comment]
@florine2623 I have investigated it and it indeed doesn't happen with this scenario on develop, because there is a different logic, but I managed to reproduce it manually by a simmilar call. 

Running `$this->context->getCurrentLocale()->formatPrice(42.5, $this->context->currency->iso_code);` will result in fatal error without my PR. With my PR, it's fixed. :-)

[tox_carttest.zip](https://github.com/PrestaShop/PrestaShop/files/12718116/tox_carttest.zip)

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

First of all, your module trigger an exception when I try to switch my language to English, see the attached screenshot below:

![image](https://github.com/PrestaShop/PrestaShop/assets/23308427/87e6a1e5-e6ba-4174-97fe-74311f91d2ab)

Following your new steps, I didn't encounter any error:
> Open PHPmyadmin, go to ps_cart, find your cart, set id_address_delivery to 0, id_address_invoice to 0 to simulate the condition.

![image](https://github.com/PrestaShop/PrestaShop/assets/23308427/b6dffc7f-4c18-4405-975c-c1257b429350)

> Refresh any FO page - error

![image](https://github.com/PrestaShop/PrestaShop/assets/23308427/dd613b63-ff12-41e3-8706-ae2b03cc737b)

Even when I refresh the page multiple times, the address still saved ! 
Please check and feedback.

Thanks!
