### ISSUE TITLE
prestashop fresh install console error!

### ISSUE THREAD

**Issue by mikajaxxx** [PrestaShop/PrestaShop#33950]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello
i installed prestashop 8.1.1 but i have some error on console:
`
API Schema is not valid: SyntaxError: JSON.parse: unexpected character at line 2 column 1 of the JSON data [index.js:90:111109](https://unpkg.com/@prestashopcorp/smb-edition-homepage/dist/assets/index.js)

    fetchInitialDatas https://unpkg.com/@prestashopcorp/smb-edition-homepage/dist/assets/index.js:90

Error: Unexpected error.: {"response":{"errors":[{"message":"Unexpected error.","path":["getOneSubscription"]}],"data":{"getOneSubscription":null},"extensions":{"httpDetails":[{"sourceName":"billing","path":{"key":"_0_CustomersSubscriptionsController_getOneSubscription","typename":"Query"},"request":{"timestamp":1694866599231,"url":"https://billing-api.distribution.prestashop.net/v1/customers//subscriptions/smb_edition","method":"GET","headers":{"authorization":"Bearer","sandbox":"undefined"}},"response":{"timestamp":1694866599286,"status":404,"statusText":"Not Found","headers":{"alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000","connection":"close","content-length":"98","content-type":"application/json","date":"Sat, 16 Sep 2023 12:16:39 GMT","server":"nginx/1.23.4","vary":"Origin","via":"1.1 google","x-envoy-upstream-service-time":"1"}},"responseTime":55}]},"status":200,"headers":{"map":{"content-type":"application/json"}}},"request":{"query":"\n    query GetOneSubscription($customerId: String!) {\n      getOneSubscription(customer_id: $customerId, product_id: \"smb_edition\") {\n        id\n        trial_end\n      }\n    }\n  ","variables":{"customerId":""}}}

Mo https://unpkg.com/@prestashopcorp/smb-edition-homepage/dist/assets/index.js:83
    Sl https://unpkg.com/@prestashopcorp/smb-edition-homepage/dist/assets/index.js:83
[index.js:2:15046](https://unpkg.com/@prestashopcorp/smb-edition-homepage/dist/assets/index.js)
    J_ https://unpkg.com/@prestashopcorp/smb-edition-homepage/dist/assets/index.js:2
    da https://unpkg.com/@prestashopcorp/smb-edition-homepage/dist/assets/index.js:2
    er https://unpkg.com/@prestashopcorp/smb-edition-homepage/dist/assets/index.js:2

`

### Expected behavior

admin panel without error

### Steps to reproduce

1 install prestashop
2 open prestashop Admin panel in firefox
3 open browser console errors window

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1

**Comment by matks** [comment]
Hello @mikajaxxx can you tell us where you downloaded the ZIP?

**Comment by mikajaxxx** [comment]
@matks prestashop.com!

**Comment by matks** [comment]
I see 😉 you have download PrestaShop Edition.

PrestaShop Edition is a solution based on the open source project PrestaShop. It contains additional functionalities powered by modules directly installed at the creation of the store and is being built and distributed by PrestaShop company.

The bug you have encountered is specific to PrestaShop Edition, you should go to https://help-center.prestashop.com/

**Comment by hibatallahAouadni** [comment]
Hello @mikajaxxx 

If you want to install the Open Source version of PrestaShop, download 8.1.1 from github on this [link](https://github.com/PrestaShop/PrestaShop/releases/tag/8.1.1).
Closing the issue cause with the OS version, there's no problem.

PS: Thanks @matks for your quick replies 🚀 

Thanks!
