### ISSUE TITLE
Error 500 when trying to install

### ISSUE THREAD

**Issue by Pikachubolk** [PrestaShop/PrestaShop#33960]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The install script gives a 500 error when trying to install (on the modules section)

<img width="614" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/58044069/76d8b238-bc0c-4ba8-840f-aac19236e9d8">
<img width="397" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/58044069/11845b5b-bbfe-4969-9b4d-6dc002a276fb">

### Expected behavior

Install the modules

### Steps to reproduce

Just run the installer 

### PrestaShop version(s) where the bug happened

Basic 8.1.1

### PHP version(s) where the bug happened

7.4

### Your company or customer's name goes here (if applicable).

Noa

**Comment by hibatallahAouadni** [comment]
Hello @Pikachubolk 

Did you download the PS from prestashop.com? if so, please download 8.1.1 from github on this [link](https://github.com/PrestaShop/PrestaShop/releases/tag/8.1.1). 
Check and feedback.

Thanks!

**Comment by Pikachubolk** [comment]
> Hello @Pikachubolk
> 
> Did you download the PS from prestashop.com? if so, please download 8.1.1 from github on this [link](https://github.com/PrestaShop/PrestaShop/releases/tag/8.1.1). Check and feedback.
> 
> Thanks!

Yes i did install via installer on prestashop.com, though I'll try the GitHub download and I'll let you know if it works.

**Comment by Pikachubolk** [comment]
It worked, thanks for the help!
