### ISSUE TITLE
Product V2 [Combination Tab] - Cannot click on next or previous combination

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#33965]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In combination tab > edit combination modal the save button is enabled. 
When we click on next combination button, a modal is displayed to discard or cancel changes.

![Capture d’écran de 2023-09-18 16-19-34](https://github.com/PrestaShop/PrestaShop/assets/24647495/9961426c-39a4-4fba-97e1-53cb04988499)

### Expected behavior

In combination tab > edit combination modal, the save button should be enabled only when we edit the combination.

-> Save button is disabled
![Capture d’écran de 2023-09-18 16-13-55](https://github.com/PrestaShop/PrestaShop/assets/24647495/e9153e71-3ae9-463e-9890-b8640124ed0b)

### Steps to reproduce

1- Create product with combination
2- Create combinations
3- Click on edit combination
4- See the error => 
    - Save button is not disabled
    - we cannot go to next or previous page

#### Acceptance Test
Unskip this test : 
* https://github.com/PrestaShop/PrestaShop/blob/dd87f6c3e91c52203869d1354468ad9f4c05cc8f/tests/UI/campaigns/productV2/functional/11_combinationTab.ts#L201-L218

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello @nesrineabdmouleh ,

I reproduce the issue with PrestaShop versions 8.0.x, 8.1.x, develop with Firefox., I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/34343
