### ISSUE TITLE
`ps_featuredproducts` module should use `ProductListingPresenter`

### ISSUE THREAD

**Issue by micka-fdz** [PrestaShop/PrestaShop#33979]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

`ps_featuredproducts` module use `ProductPresenter` instead of `ProductListingPresenter`

### Expected behavior

`ps_featuredproducts` module should use `ProductListingPresenter` instead of `ProductPresenter`

Other native modules that use `ProductListingPresenter` :

- `ps_bestsellers`
- `ps_crossselling`
- `ps_newproducts`
- `ps_specials`

### Steps to reproduce

To be reproduced by a dev

### PrestaShop version(s) where the bug happened

1.7.x.x, 8.x.x

### If your bug is related to a module, specify its name and its version

ps_featuredproducts

### Your company or customer's name goes here (if applicable).

Creabilis

**Comment by micka-fdz** [comment]
I'll make a PR soon.

**Comment by Hlavtox** [comment]
@micka-fdz Good find! :-) Let's go.
