### ISSUE TITLE
Ecommerce tracking issues - PS 1.6.0.11

### ISSUE THREAD

**Issue by israr-seovalley** [PrestaShop/PrestaShop#33986]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

We have installed Google Analytics module for ecommerce tracking. Ecommerce tracking already enabled from admin you can see in the attached screenshot. But tracking not working. Please fix this issue as soon as possible.
![Modules-•-Giftware-Direct (1)](https://github.com/PrestaShop/PrestaShop/assets/123145801/5b7b6100-5c4f-4e54-b17a-c43505b0f6d5)

### Steps to reproduce

1. Go admin
2. Module
3. Google Analytics 

### PrestaShop version(s) where the bug happened

1.6.0.11

**Comment by matks** [comment]
Hello @israr-seovalley you are using an outdated version of the module Google Analytics, on an un-maintained version of PrestaShop.

PrestaShop 1.6.0.11 is not maintained anymore and the only maintained version of the module is v4.2.2 https://github.com/PrestaShop/ps_googleanalytics/releases/tag/v4.2.2 which is compatible with versions 1.7.6 and higher.

I am afraid nobody can help you with this old and un-maintained software on this GitHub area. You might find help here https://www.prestashop-project.org/support/

**Comment by hibatallahAouadni** [comment]
Hello @israr-seovalley 

PrestaShop 1.6 has reached end of life and is no longer officially maintained ([see announcement](http://build.prestashop.com/news/1.6.1.x-what-s-next/)).

Maintenance for this version is now being performed exclusively by volunteers on a very limited scope. You can open an issue on its [dedicated repository](https://github.com/PrestaShop/PrestaShop-1.6/issues), but please keep in mind that only absolutely critical issues may be acknowledged.

Thank you
