### ISSUE TITLE
Marketing / Google / Ads

### ISSUE THREAD

**Issue by juliomgm** [PrestaShop/PrestaShop#33989]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When i try to link a existing google ads account it gives me the error

`Could not connect your Google Ads account, it's on our side, please give it another try.`

### Steps to reproduce

Updated everything.
Linked Store to Prestashop account.
Linked Google Account
Linked Merchant Center account 
Setup Product feed 

Everything good until now.

Go to Google Ads account option chose my account that shows on the option list and hit Connect.
I get the error:
`Could not connect your Google Ads account, it's on our side, please give it another try.`

### PrestaShop version(s) where the bug happened

1.7.7.3

### PHP version(s) where the bug happened

7.2 and 7.4

### If your bug is related to a module, specify its name and its version

psxmarketingwithgoogle - Marketing with Google v1.59.0

**Comment by juliomgm** [comment]
![imagem](https://github.com/PrestaShop/PrestaShop/assets/34062888/59888f54-775c-4e6d-aee2-79ce80f58ff3)

**Comment by Quetzacoalt91** [comment]
Hi @juliomgm,

As we deal with an issue of Marketing with Google, would you mind contacting our support via the Help tab? You'll find a `Contact us` button that will lead to a more suitable help platform.

Thank you

**Comment by florine2623** [comment]
I'm closing the issue to avoid clogging the backlog ^^
