### ISSUE TITLE
There is no way to make specific price for only one combination

### ISSUE THREAD

**Issue by jmarcini** [PrestaShop/PrestaShop#33987]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In version 8.1.1 is no option to create a specific price for one combination.

### Expected behavior

Make it happen :)

### Steps to reproduce

1. Go to product
2. Quotation
3. Add specific price
4. Choose Combination
<img width="807" alt="Zrzut ekranu 2023-09-20 o 09 53 52" src="https://github.com/PrestaShop/PrestaShop/assets/39645/17c0d5ee-e997-48b2-a73b-3ddb96305fb1">

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1.23

**Comment by florine2623** [comment]
Hello @jmarcini ,

I can't reproduce your issue. What browser are you using ?

https://github.com/PrestaShop/PrestaShop/assets/16019289/e747e6b6-f49a-4717-9846-066fbaa6db3b

Waiting for your feedback

**Comment by jmarcini** [comment]
I made test on PS v8.1.1. On Chrome and Safari.

**Comment by florine2623** [comment]
I can't reproduce your issue on Safari either.

<img width="811" alt="Screenshot 2023-09-20 at 14 23 28" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/7f734f2b-9d6e-4252-83a3-73b7b0ac4b65">


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
