### ISSUE TITLE
SF6 : Remove deprecated code from Form

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#33996]
## Description 

See https://github.com/symfony/symfony/blob/6.4/UPGRADE-6.0.md#form
EPIC : https://github.com/PrestaShop/PrestaShop/issues/33993

## Acceptance tests 
ISO

**Comment by MatShir** [comment]
closed by https://github.com/PrestaShop/PrestaShop/pull/34550
