### ISSUE TITLE
Unavailable edit address in FO 

### ISSUE THREAD

**Issue by metacreo** [PrestaShop/PrestaShop#33991]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On editing address in FO, you always must enter state. Even on countries without states.

https://github.com/PrestaShop/PrestaShop/assets/543458/7e30ca5b-8457-49e3-9fe5-92431b1f7150

### Expected behavior

Option State must be only for countries with states 

### Steps to reproduce

1. Create address with country France or any other without states. Save it.
2. go to address edit by clicking Update
3. click Save

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.2.10

**Comment by florine2623** [comment]
Hello @metacreo ,

I can't reproduce your issue.

https://github.com/PrestaShop/PrestaShop/assets/16019289/79368089-08e6-44f4-8ad0-54a6dac63b84

Could you please send a screen record of your issue and the configuration of the concerned country ?

Waiting for your feedback.

**Comment by metacreo** [comment]
@florine2623 now click edit on address who without states
[Screencast from 20.09.2023 19:38:55.webm](https://github.com/PrestaShop/PrestaShop/assets/543458/352418aa-401d-4730-a736-60e0be9a0aae)

**Comment by aniszr** [comment]
Hello @metacreo 

I couldn't either reproduce your issue when editing an address for a country without states!

See attached screenrecord:

https://github.com/PrestaShop/PrestaShop/assets/92626242/9ff06d26-8436-4fbb-9635-51d3b80fe066

Could you please check in your BO that you imported Stated for the chosen country !

See attached screenshot :

![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/1b1459a1-d0e3-4f10-b185-b7c1512a706a)

Waiting for your Feed-back.

Thank you!

**Comment by metacreo** [comment]
@aniszr not need change any row
go to demo.prestashop.com
click Sign In
click No account? Create one here 
fill form and click Save
click on name on top to go to profile
click Add First Address
fill form, choose France and click Save
click Update on address 
click Save

**Comment by Steven44223** [comment]
I'm am having the same problem on 3 different installs (PS version 8.1.1).

This happens only in Google Chrome (desktop and mobile). Firefox, Edge and Opera are not showing the state dropdown when you edit an address for a Country without states from the My Account page.

Also, if you edit the address from the checkout, the form is displayed correctly, the state dropdown is not displayed in Chrome.

**Comment by metacreo** [comment]
@Steven44223 I`m using Firefox only. Just now tried Chrome. Confirm, on chrome no State dropdown.

**Comment by Steven44223** [comment]
> @Steven44223 I`m using Firefox only. Just now tried Chrome. Confirm, on chrome no State dropdown.

Strange, I'm only having this problem in Chrome.

**Comment by florine2623** [comment]
Hello @metacreo @Steven44223 ,

You need to add states if you enable this option.
<img width="1198" alt="Screenshot 2023-09-21 at 15 06 45" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/62d73e0a-928d-4a8c-943c-a62f47d2cd8f">


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by metacreo** [comment]
@florine2623 No. We no need add some. This is a bug and is not related to states addition or some.
Already 2 people have confirmed that the bug exists, one only on Chrome, the other on Firefox.
If you don't understand what the bug is, look at the description carefully.
In top of this page I used prestashop demo site and latest browser FF and chrome, everything is clearly visible there

**Comment by metacreo** [comment]
@Steven44223 how do you like this ?? they just closed. without even understanding what's going on. (^^)

**Comment by Steven44223** [comment]
Hello @florine2623

The problem is not about Adding addresses but Editing an existing address with a country that does not contain states. I checked the database and the BO and the option "Contain states" is not enabled for countries that do not have states.

And if you edit an address when you Check Out it shows the correct form without the State field. The problem just occurs in the My Account section.

So, editing an existing address should not contain the State field unless you select a country where states are enabled. It's also inconsistent between browsers.

If you need more information let me know.

**Comment by metacreo** [comment]
Another issue is the zip code. If I disable the postcode requirements for the country in BO, it is still required in the form.
