### ISSUE TITLE
Import images from CSV

### ISSUE THREAD

**Issue by cnicodeme** [PrestaShop/PrestaShop#340]
Hi!

I just downloaded the HEAD version of Prestashop and using it for importing a CSV file with image.

I defined the images as absolute path (/var/www/path/to/prestashop/my_images/{image.jpg}) or via the url (http://www.mywebsite.com/my_images/{image}.jpg)

The import runs but no image are saved in the products.

I checked the rights and if the images exists and yes they all exist. I verified the access via the url (when trying with the url) and the image shows up on my browser.

I think the import system is broken for the images.

**Comment by marionf** [comment]
Hello, 
This issue is old, so I close it.
If you still have it on the last version (PrestaShop 1.7.4.2), please open a new one.
Regards
