### ISSUE TITLE
SF6 - Remove deprecated code from Inflector

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#34000]
## Description 

https://github.com/symfony/symfony/blob/6.4/UPGRADE-6.0.md#inflector

Use the recommended `EnglishInflector` and remove our custom implementations which is a useless bridge `PrestaShop\PrestaShop\Core\Util\Inflector`

EPIC : https://github.com/PrestaShop/PrestaShop/issues/33993

## Acceptance test

ISO

**Comment by M0rgan01** [comment]
We use the Inflector class from doctrine, not the remove class from sf 6 (https://symfony.com/components/Inflector)
