### ISSUE TITLE
Can't use "Marketing with Google" module because I cant install ps_accounts

### ISSUE THREAD

**Issue by LarsGMortensen** [PrestaShop/PrestaShop#34008]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The other day PrestaShop sent out a newsletter-email which inspired me to install the "Marketing with Google"-module (this module: https://addons.prestashop.com/en/promotions-marketing/85751-prestashop-marketing-with-google-.html).

It installed nicely.

After installation, it prompted me to configure the module to get started.

On the configuration page, it wants me to first install the "PrestaShop Account module".
But when I click the "install"-button, it just responds: "Something went wrong. Please try again."
I have googled this issue and found that many others also have this problem, but I found no solution. Please advise.

Here is a screen-recording:

![s6gl2QKVWX](https://github.com/PrestaShop/PrestaShop/assets/26773745/511be3fd-dba4-45f5-bbba-06ba62610a46)

### Expected behavior

I would expect the PrestaShop modules (especially the ones created by PrestaShop) to install flawlessly.

### Steps to reproduce

On PrestaShop 8.1.1

1. Install PrestaShop Marketing with Google, v. v1.59.0 (the latest version downloaded the other day). Found here: https://addons.prestashop.com/en/promotions-marketing/85751-prestashop-marketing-with-google-.html
2. Configure the Marketing with Google.
3. I will tell you to first install the PrestaShop Account module. Click the "install"-button.

Please see this screen-recording from beginning to end to follow my steps correctly:

![s6gl2QKVWX](https://github.com/PrestaShop/PrestaShop/assets/26773745/e832820a-0716-4a67-8d8c-ab9927d4e1a4)

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

PrestaShop Marketing with Google, v1.59.0

**Comment by Guillaumelpg** [comment]
Hello @LarsGMortensen 

I am part of the team that takes care of the PS Account module. 

This problem occurs on version 8 of PrestaShop when MBO is not installed.

We are considering solutions to resolve this frustration. 

In the meantime, you can find the latest version of the PS Account module on this Github page: https://github.com/PrestaShopCorp/ps_accounts/releases/tag/v6.2.6 

Best regards,
Guillaume

**Comment by LarsGMortensen** [comment]
Hi @Guillaumelpg 

Thank you so much for the update :)

The link you provided responds with 404 ...is there another link?

I also tried https://github.com/PrestaShopCorp/ps_accounts/releases/ but that also responds with 404

Please advise :)

**Comment by matks** [comment]
@Guillaumelpg this GitHub repository is private 😅 

Maybe attach the ZIP here 😉 ?

**Comment by LarsGMortensen** [comment]
I downloaded the latest version of ps_mbo from here:
https://github.com/PrestaShopCorp/ps_mbo

With ps_mbo installed, I could easily install ps_accounts.

But now I have another issue, trying to "link" my PrestaShop-installation to my account - but thats another story, which I will write about in another ticket.

**Comment by LarsGMortensen** [comment]
@Guillaumelpg please see this ticket: https://github.com/PrestaShop/PrestaShop/issues/34038

**Comment by MatShir** [comment]
I'm closing this issue as well. Thanks @LarsGMortensen for the reports, it's very well appreciated. The team is investigating. For a quick support reply, please use this [form contact](https://help-center.prestashop.com/en/contact) in the near future
