### ISSUE TITLE
Export table ps_cart

### ISSUE THREAD

**Issue by nael-belacom** [PrestaShop/PrestaShop#34004]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, 

I'd like to export the data from the ps_card table, when I run the following query:

select * from ps_cart 

I get a blank page when I try to download the csv file.

Best regards 

Naël

### Expected behavior

I want to export all the data in the ps_card table

### Steps to reproduce

Go to order in the left-hand drop-down menu
Click on the settings icon 
Click on Export to SQL Manager
Write the query 
Save 
When I click on the red-framed icon to download the file, nothing happens. I get a white spot instead of an export file. 

<img width="1437" alt="Capture d’écran 2023-09-20 à 16 57 14" src="https://github.com/PrestaShop/PrestaShop/assets/145580868/af926a71-5e81-4d37-bfed-9cd14419a00c">
<img width="1437" alt="Capture d’écran 2023-09-20 à 17 04 32" src="https://github.com/PrestaShop/PrestaShop/assets/145580868/e594810e-3a2a-44fa-963e-adceb1bb8323">

### PrestaShop version(s) where the bug happened

1.7.7.5

### Your company or customer's name goes here (if applicable).

https://bioflore.be/fr/

**Comment by florine2623** [comment]
Hello @nael-belacom ,

Do you want to export the cart or the orders ?
Because these are 2 different tables.

Do not forget to add the ; at the end of the query.

In my case I can export the carts :

https://github.com/PrestaShop/PrestaShop/assets/16019289/c3d64b0c-8020-433b-814d-6f0d59eb4d81

**Comment by nael-belacom** [comment]
Hello Florine,

I want to export the card.

Naël
[Belacom]<https://www.belacom.fr/>
[web]<https://sign.belacom.fr/l/S3U2SmNTMFVBYmRGbHE4UzFIS21vdz09-VzNGNG5oU1pWYjZRMTVQMUxBZ2xJZz09>
[linkedin]<https://sign.belacom.fr/l/S3U2SmNTMFVBYmRGbHE4UzFIS21vdz09-eFZMaExNZWZGQjMvaVVJaDArTTl6Zz09>

Naël Henni
Chef de projet / Support
***@***.***

09 77 55 26 04<tel:09%2077%2055%2026%2004>

[img]<https://support.belacom.fr/support/login>
[Salon Paris Retail Week 2023]<https://sign.belacom.fr/l/S3U2SmNTMFVBYmRGbHE4UzFIS21vdz09-a1RCUlYzaUFUM1hkQTZoV29vMXBjUT09-U3I0aVZkL09SV1JNNHJIWStheEcvUT09>
De : florine2623 ***@***.***>
Date : mercredi, 20 septembre 2023 à 17:31
À : PrestaShop/PrestaShop ***@***.***>
Cc : Naël HENNI ***@***.***>, Mention ***@***.***>
Objet : Re: [PrestaShop/PrestaShop] Export table ps_card (Issue #34004)

Hello @nael-belacom<https://github.com/nael-belacom> ,

Do you want to export the cart or the orders ?

Because these are 2 different tables.

**Comment by florine2623** [comment]
Use the following query :

SELECT * FROM ps_cart;

**Comment by nael-belacom** [comment]
Florine,

I tried your request and it doesn't change anything, the behavior is similar.
If you want we can make a call to make it easyier

Naël
[Belacom]<https://www.belacom.fr/>
[web]<https://sign.belacom.fr/l/S3U2SmNTMFVBYmRGbHE4UzFIS21vdz09-VzNGNG5oU1pWYjZRMTVQMUxBZ2xJZz09>
[linkedin]<https://sign.belacom.fr/l/S3U2SmNTMFVBYmRGbHE4UzFIS21vdz09-eFZMaExNZWZGQjMvaVVJaDArTTl6Zz09>

Naël Henni
Chef de projet / Support
***@***.***

09 77 55 26 04<tel:09%2077%2055%2026%2004>

[img]<https://support.belacom.fr/support/login>
[Salon Paris Retail Week 2023]<https://sign.belacom.fr/l/S3U2SmNTMFVBYmRGbHE4UzFIS21vdz09-a1RCUlYzaUFUM1hkQTZoV29vMXBjUT09-U3I0aVZkL09SV1JNNHJIWStheEcvUT09>
De : florine2623 ***@***.***>
Envoyé : mercredi 20 septembre 2023 17:48
À : PrestaShop/PrestaShop ***@***.***>
Cc : Naël HENNI ***@***.***>; Mention ***@***.***>
Objet : Re: [PrestaShop/PrestaShop] Export table ps_cart (Issue #34004)


Use the following query :

SELECT * FROM ps_cart;

**Comment by florine2623** [comment]
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by nael-belacom** [comment]
Hello,

I don't understand why you tell me to contact support when support tells me to make a ticket via github.

Please help me to solve this problem, making a call teams will probably be much faster.

Sincerely

Naël
[Belacom]<https://www.belacom.fr/>
[web]<https://sign.belacom.fr/l/S3U2SmNTMFVBYmRGbHE4UzFIS21vdz09-VzNGNG5oU1pWYjZRMTVQMUxBZ2xJZz09>
[linkedin]<https://sign.belacom.fr/l/S3U2SmNTMFVBYmRGbHE4UzFIS21vdz09-eFZMaExNZWZGQjMvaVVJaDArTTl6Zz09>

Naël Henni
Chef de projet / Support
***@***.***

09 77 55 26 04<tel:09%2077%2055%2026%2004>

[img]<https://support.belacom.fr/support/login>
[Salon Paris Retail Week 2023]<https://sign.belacom.fr/l/S3U2SmNTMFVBYmRGbHE4UzFIS21vdz09-a1RCUlYzaUFUM1hkQTZoV29vMXBjUT09-U3I0aVZkL09SV1JNNHJIWStheEcvUT09>
De : florine2623 ***@***.***>
Envoyé : mercredi 20 septembre 2023 18:11
À : PrestaShop/PrestaShop ***@***.***>
Cc : Naël HENNI ***@***.***>; Mention ***@***.***>
Objet : Re: [PrestaShop/PrestaShop] Export table ps_cart (Issue #34004)


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our support plans<https://www.prestashop.com/support>.

Alternatively, you can also ask for help in the community forums<https://www.prestashop.com/forums/> or in the public Slack channel<https://github.com/PrestaShop/open-source/tree/master/slack>.

Thank you
