### ISSUE TITLE
Upgrade to Symfony 6.0

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#34006]
The idea is to upgrade the composer dependency and upgrade to symfony 6, it also implies all the framework dependencies of course And it may imply upgrading some other dependencies we have that wouldn't be compatible with SF6 and need to be upgraded as well.

The target version should be as high as possible depending on the latest version when this task is done.

We must prevent the usage of already deprecated methods/code as much as possible.

> [!NOTE]  
> This hunt on deprecated code can be done in separated PRs if the upgrade PR is already too big

**Comment by TiaNex-Com** [comment]
yes,up to least php version,symfony version(stable) and remove old stuff of ps.1.6
