### ISSUE TITLE
Multiple domains inside modules translations will slower the theme translations

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#34028]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Once you have a theme (not Classic, as it's the core one) having somes modules views inside it that contains multiple string as the third part of the domain, the module will be inside the listing of the modules to translate each time.

It could (it does) slow the translations page.

### Expected behavior

Have an unique list, to faster the whole thing.

### Steps to reproduce

1. Install the child theme (or any other themes, as you want) like this : 
[child_classic.zip](https://github.com/PrestaShop/PrestaShop/files/12697983/child_classic.zip)
2. Go to translations page
3. Check the Front Office translations, with the child theme added
4. You will not be able to see without modifying a method to see the results, actually.
5. Ask a dev to confirm you that point, thanks.

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

n/d

### If your bug is related to a module, specify its name and its version

n/d

### Your company or customer's name goes here (if applicable).

Wepika

**Comment by sallemiines** [comment]
Hello @PrestaEdit 

I reproduce your issue on PS 811 / PS 812 ! 

Ping https://github.com/orgs/PrestaShop/teams/prestashop-core-developers : Could someone please  confirm that is a bug and not the normal behavior !

Thank you !

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/product-council can someone please confirm that this is a bug and not the expected behavior :pray:

**Comment by PrestaEdit** [comment]
Someone on board ?

**Comment by kpodemski** [comment]
@PrestaEdit good timing lol, I'm just on it

**Comment by kpodemski** [comment]
@PrestaEdit 

I didn't notice any change in behavior, it loads translations with or without the change, so I guess the change is to optimize the performance? :) Asking because I'm not sure what QA reproduced here ;-)

**Comment by PrestaEdit** [comment]
> Have an unique list, to faster the whole thing.

So, yes :)

**Comment by kpodemski** [comment]
thanks @PrestaEdit 

and again, good timing 😂
