### ISSUE TITLE
BO - multistore : bulk actions shops does not work

### ISSUE THREAD

**Issue by MhiriFaten** [PrestaShop/PrestaShop#34032]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

[Untitled_ Sep 22 2023 9_41 AM.webm](https://github.com/PrestaShop/PrestaShop/assets/111756615/3a5cf29d-1dcd-4947-b52b-f5291a693afc)

### Expected behavior

![image](https://github.com/PrestaShop/PrestaShop/assets/111756615/2772322f-9dea-49f8-b54d-905887354d32)

### Steps to reproduce

Go to Advanced Parameters >Multistore
Add new store and a new URL
GO to multistore page and click on bulk actions
see error : bulk action does not work and check box not displayed

![image](https://github.com/PrestaShop/PrestaShop/assets/111756615/36081e7b-b0a9-4dcd-bc31-8e955fc280ca)

### PrestaShop version(s) where the bug happened

8.1.1 & develop

### PHP version(s) where the bug happened

8.1

**Comment by djoelleuch** [comment]
Hello @MhiriFaten 

I reproduce the issue with 8.1.x,develop .  see the attached screen record below:

[Untitled_ Sep 22, 2023 12_05 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/43e4592c-284f-4407-9ff9-9a73e95aff5c)

Thank you  .

**Comment by Hlavtox** [comment]
This is expected behavior, you cannot delete a main URL of a store. That's a thing I fixed. Please confirm @PrestaShop/product-council

**Comment by MatShir** [comment]
So main URL can't be removed so, we might need to test again without all the store as main URL as said @Hlavtox. Could you try with some store not as main ? 🙏

**Comment by florine2623** [comment]
@Hlavtox @MatShir ,

When it is not a Main URL, the bulk action works as expected.

<img width="1226" alt="Screenshot 2023-09-27 at 13 37 04" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/b2ebeb83-5f86-4c4b-b601-8caf37c08715">

I'm closing this issue as it is the expected behavior.
Thanks!
