### ISSUE TITLE
Module GDPR generates exception in FO

### ISSUE THREAD

**Issue by aniszr** [PrestaShop/PrestaShop#34036]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After installing the Module GDPR v2.0.2 an exception is displayed in FO and it remain displayed in the bottom of all pages in FO!

**Develop**

![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/cd2ac162-2e54-4f3d-b0fb-5e881abb641b)

**8.1.x**

![image](https://github.com/PrestaShop/PrestaShop/assets/92626242/8afc0f3d-a84d-4c47-8445-12c0d2b879fa)

`PS : The problem is not reproduced in`**8.1.1**

### Expected behavior

The module shouldn't throw any exception in FO

### Steps to reproduce

1. Install GDPR module v2.0.2
2. Make sure the Debug mode is enabled
3. Go to FO
4. See Error in page buttom

### PrestaShop version(s) where the bug happened

8.1.x & Develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

psgdpr v2.0.2

**Comment by djoelleuch** [comment]
Hello @aniszr 
I reproduce the issue only on develop as you can see  below:
On develop :

[Untitled_ Sep 22, 2023 4_10 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/b423bd24-24fc-4d86-85b5-bcb27e74aa55)


on 8.1.x : 

[Untitled_ Sep 22, 2023 4_22 PM (1).webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/457b76f6-1f07-486f-8efb-aa4241c1f55b)

Thank you .
