### ISSUE TITLE
Make PrestaShop compatible with Node.js 20

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#34058]
As [the documentation](https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/#nodejs) states:

> PrestaShop uses NPM to manage frontend dependencies and [Webpack](https://webpack.js.org/) to compile them into static assets. You only need NodeJS 14.x (version 16.x is recommended, [you can get it here](https://nodejs.org/)), and NPM will take care of it all.

PrestaShop Javascript dependencies should be updated to be compatible with [standard stable Node.js versions 18 and 20](https://nodejs.dev/en/about/releases/).

**Comment by matks** [comment]
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by Progi1984** [comment]
We begin to have some incompatibles dependencies  : [PrestaShop/PrestaShop](https://github.com/PrestaShop/PrestaShop/pull/35734#issuecomment-2017434231)

**Comment by Progi1984** [comment]
`pdfjs-dist` : Node 18 min. since [v3.7.107](https://github.com/mozilla/pdf.js/releases/tag/v3.7.107)
`@typescript-eslint/parser` : Node 18 min. since [v7.0.0](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v7.0.0)

**Comment by Progi1984** [comment]
`@faker-js/faker` : Node 18 min.  since [v9.0.0](https://github.com/faker-js/faker/releases/tag/v9.0.0)

**Comment by jolelievre** [comment]
We decided to simplify the scope and handle compatibility with Node 20 minimum

**Comment by Progi1984** [comment]
Done for UI Tests : 
* https://github.com/PrestaShop/PrestaShop/pull/37064
* https://github.com/PrestaShop/PrestaShop/pull/37063
* https://github.com/PrestaShop/PrestaShop/pull/37068
