### ISSUE TITLE
Error: 'No Carriers Available' Message When Deleting Address with Products in Cart

### ISSUE THREAD

**Issue by dotnetmario** [PrestaShop/PrestaShop#34059]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When a user begins the checkout process, selects a delivery address, but does not complete the payment process, and later, an administrator deletes the address that the customer previously selected from the back office, an issue arises. If the customer returns to complete their checkout and adds a new address, they encounter the error message "Unfortunately, there are no carriers available for your delivery address." This error occurs even when the new address should have carriers available.

Address deleted from the backoffice:
![image](https://github.com/PrestaShop/PrestaShop/assets/40273288/f69b198a-4835-4996-8814-a133017fa130)
Error message in the checkout process
![image](https://github.com/PrestaShop/PrestaShop/assets/40273288/08007a58-f3a1-486e-8331-82ae706e2a98)

### Expected behavior

When a user adds a new address during the checkout process, the system should accurately display the carriers available for that address, ensuring that the customer can proceed with their purchase smoothly.

### Steps to reproduce

Begin the checkout process as a customer.

Select or create a delivery address during the checkout but do not complete the entire process (i.e., do not make the payment).

![image](https://github.com/PrestaShop/PrestaShop/assets/40273288/6029d10e-698c-4377-9f23-3399e3ee0382)

As an administrator, access the back office.

Locate and delete the customer's previously selected address from the back office.

![image](https://github.com/PrestaShop/PrestaShop/assets/40273288/abcc89c5-948d-4937-90c0-b71d18f2067f)

The customer returns to complete their checkout process.

During this return visit, the customer creates a new or the same delivery address and selects it for the order.

![image](https://github.com/PrestaShop/PrestaShop/assets/40273288/1c4f2684-07ec-4113-9da7-fddcdae5e15b)

Observe the issue: The system indicates that no carriers are available for the newly selected delivery address, even though carriers should be available for it.

![image](https://github.com/PrestaShop/PrestaShop/assets/40273288/97774f2d-e92a-409a-b42e-952fe59c667f)

### PrestaShop version(s) where the bug happened

1.7.8.10

### PHP version(s) where the bug happened

7.4.0

**Comment by florine2623** [comment]
Hello @dotnetmario ,

I have reproduced your issue on `8.0.x` and `8.1.x`. But on `develop` this is fixed.

PS 8.0.x and 8.1.x :x:

https://github.com/PrestaShop/PrestaShop/assets/16019289/dda7173a-65cd-4d0e-ad9b-902af87958f2

PS develop branch : ✅ 

https://github.com/PrestaShop/PrestaShop/assets/16019289/242b0575-09dc-4173-9e51-e4c8ad972493

ping @MatShir, @dotnetmario has created a PR targeting develop.
I think it should target another branch. WDYT ?

**Comment by dotnetmario** [comment]
Hello @florine2623,
i have changed the target branch from `develop` to `8.1.x`
Thanx

**Comment by Hlavtox** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/35017
