### ISSUE TITLE
block .git directory in htaccess

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#34052]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

.git folder can expose secrets, personal data like email, ...
let's check https://www.repo-lookout.org/
"Including our most recent security scan on September 25, 2023, we have scanned 8,098,645,218 URLs on 1,024,952,741 domains. A total of 985,940 publicly exposed source code repositories have been found to date."

### Expected behavior

block .git folder anywhere in PrestaShop folders.

### Steps to reproduce

1. git to a PrestaShop instance with .git folder
2. Call /.git/logs/HEAD

### PrestaShop version(s) where the bug happened

all

### PHP version(s) where the bug happened

all

### Your company or customer's name goes here (if applicable).

Creabilis

**Comment by nicosomb** [comment]
I wonder if it's a "bug" from PrestaShop side or not. 

For me, 2 ways to install PrestaShop: 
* download the package and deploy it. This one has no .git folder. 
* `git clone` the repository, `composer install`, `make assets`, etc. So you have a tech profile. So you have to know that `.git` folders **should not be deployed**.

**Comment by AureRita** [comment]
Hi @jf-viguier,

Thank you for your suggestion, this one seems more like a new feature to implement than an issue. To share it with the product team, I recommend you to[ open a discussion on this subject.](https://build.prestashop-project.org/news/2023/github-discussions-are-now-enabled-in-the-prestashop-project/)  

Thank you

**Comment by jf-viguier** [comment]
> * that `.git` folders **should not be deployed**.
Check : [repo-lookout.org/](https://www.repo-lookout.org/) You will see that it's not the case.

And what about development servers open on the internet ?

**Comment by jf-viguier** [comment]
fixed in https://github.com/PrestaShop/PrestaShop/pull/34122

**Comment by nicosomb** [comment]
> And what about development servers open on the internet ?

I don't understand. 

You can have development servers open to the internet, but your development server **should not** be your server where websites are hosted.

**Comment by jf-viguier** [comment]
hi, I've changed htaccess directive to a RewriteRule because Directory directive is not allowed in a htaccess, only in httpd.conf

**Comment by jf-viguier** [comment]
According to some adminsys, It should be a better solution to protect all dot files and folders. WDYT ?

**Comment by florine2623** [comment]
ping @PrestaShop/product-council and @PrestaShop/prestashop-core-developers 

Is it possible to get the labels PM ✅  and dev ✅ ?
A PR is already available

**Comment by MatShir** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/34122
