### ISSUE TITLE
Cannot add a carrier to the webshop

### ISSUE THREAD

**Issue by cdi121212** [PrestaShop/PrestaShop#34062]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Cannot add a carrier to the webshop as the Save button is not displayed

### Expected behavior

I should be able to add a carrier so that I can sell products, add carrier to products

### Steps to reproduce

1. Go to  the Shopping/Carriers page in the admin console
2. Try to add a carrier 
3. 
![image](https://github.com/PrestaShop/PrestaShop/assets/146025974/91cde4ae-129f-4b8e-aff1-d20235cb83b2)

### PrestaShop version(s) where the bug happened

1.7.6.4

**Comment by florine2623** [comment]
Hello @cdi121212 ,

I can't reproduce your issue.

https://github.com/PrestaShop/PrestaShop/assets/16019289/098a162e-f137-4488-90d6-f6cbff9b324a

It seems like you have an external module or modified code on this section.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
