### ISSUE TITLE
Inactive discount coupons (cart rule) still applied after deactivation

### ISSUE THREAD

**Issue by LarsGMortensen** [PrestaShop/PrestaShop#34067]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In PrestaShop 8.1.1
a cart rule (discount coupon code) was set to give 11% discount on certain categories between 2023-09-22 14:00:00 and 2023-10-23 13:00:00
a customer put some of the goods in the cart on 2023-09-22, and left the cart.

The customer then returned on 2023-09-26, added more items to the cart (same item but increased the amount), and then completed the purchase (on 2023-09-26) and the cart rule was still applied - so the customer got the discount even though it was set to expire on 2023-10-23 13:00:00 AND even had been manually deactivated too.

### Expected behavior

When we set the cart rule to expire on a given datetime, and even manually deactivate it too, we would naturally NOT expect customers to complete purchases with the cart rule discount many days later.

### Steps to reproduce

1. Create a cart rule of 11% on a specific category, and set a coupon code, and set the cart rule to expire on a given date.
2. Go to front office and put some items from the category in the cart and apply the coupon code. Then leave without completing the order.
3. Come back after the cart rule has expired, and then complete the purchase (with the cart rule still applied, even though it has expired).

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

7.4.33

**Comment by florine2623** [comment]
Hello @LarsGMortensen ,

We are aware of this issue, it is already in our debug backlog. Your issue is the same as https://github.com/PrestaShop/PrestaShop/issues/26235
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you
