### ISSUE TITLE
date_add field not updated when duplicating a product

### ISSUE THREAD

**Issue by ks129** [PrestaShop/PrestaShop#34079]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If you duplicate a product, its date_add field is not updated and remains the same as the original product. It causes missing "New" labels and the product is not listed on the New Products page.

### Expected behavior

When duplicating a product, the new product's date_add should be duplication datetime.

### Steps to reproduce

1. Go to the product listing.
2. Duplicate a product using the bulk action.
OR
1. Go to the product view/edit page of any product.
2. Duplicate the product.

3. Check date_add of newly created product(s) directly from database - they have the original product's date_add values.

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.1

**Comment by sallemiines** [comment]
Hello @ks129 

I reproduce your issue on PS 810 / PS 812  as you can see :

https://github.com/PrestaShop/PrestaShop/assets/31663369/6d742a60-4fb6-49f4-b6f3-d3222f015d33

Thank you !

**Comment by Thierry-Pimentbleu** [comment]
When a product is duplicated, the stock of the initial product is also duplicated and this can cause stock errors if the modification is forgotten. It would be logical to reset the field to 0 when duplicating.
Especially as it adds unnecessary lines to stock movements.

**Comment by webeshop** [comment]
src/Adapter/Product/Update/ProductDuplicator.php

after line:
`$shopProduct->active = false;`

add line:
`$shopProduct->date_add = date('Y-m-d H:i:s');`

**Comment by Codencode** [comment]
The problem could depend on the fact that the product is recovered using the old ID

in **src/Adapter/Product/Update/ProductDuplicator.php**, education could be replaced
```
$shopProduct = $this->productRepository->get($sourceProductId, $shopId);
````
with
```
$shopProduct = $this->productRepository->get($newProductId, $shopId);
```

**Comment by Codencode** [comment]
The solution I proposed has a problem with multishop.
The pull request proposed by @webeshop #34823 should be considered.

**Comment by ricmyra** [comment]
> When a product is duplicated, the stock of the initial product is also duplicated and this can cause stock errors if the modification is forgotten. It would be logical to reset the field to 0 when duplicating. Especially as it adds unnecessary lines to stock movements.

Tks! It's really works!

**Comment by ricmyra** [comment]
> src/Adapter/Product/Update/ProductDuplicator.php
> 
> after line: `$shopProduct->active = false;`
> 
> add line: `$shopProduct->date_add = date('Y-m-d H:i:s');`

Tks! It's really works!

**Comment by Hlavtox** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/34823
