### ISSUE TITLE
Error 500 after order validation

### ISSUE THREAD

**Issue by moez2302** [PrestaShop/PrestaShop#34070]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Lorsqu'un client finalise sa commande en validant le moyen de paiement, il tombe sur une page blanche ! :/ et ne récoit pas de validation de la commande... Moi seul qui récoit une confirmation de la commande
toujours 

### Expected behavior

j attend que après la confirmation d une commande le client sera rediriger vers une page de remercîment ou ou moins vers l accueil 

### Steps to reproduce

.

### PrestaShop version(s) where the bug happened

Version de PrestaShop : 8.1.1

### PHP version(s) where the bug happened

Version de PrestaShop : 8.1.1

### If your bug is related to a module, specify its name and its version

Version de PrestaShop : 8.1.1

### Your company or customer's name goes here (if applicable).

fayderma

**Comment by florine2623** [comment]
Hello,

Please send your request in English. English is the norm on GitHub.

Thank you

**Comment by moez2302** [comment]
"When a customer finalizes their order by confirming the payment method, they encounter a blank page! :/ and do not receive an order confirmation... Only I receive an order confirmation."

**Comment by moez2302** [comment]
"I purchased the Beauty Cosmetic theme and installed it, but I have a problem. After the checkout in my shop, the customer gets redirected to a blank page with the following message: 'This page isn't working. Unable to process this request at fayderma.com at the moment. HTTP ERROR 500.'"

**Comment by moez2302** [comment]
"I purchased the Beauty Cosmetic theme and installed it, but I have a
problem. After the checkout in my shop, the customer gets redirected to a
blank page with the following message: 'This page isn't working. Unable to
process this request at fayderma.com at the moment. HTTP ERROR 500.'"

Le mar. 26 sept. 2023 à 15:19, florine2623 ***@***.***> a
écrit :

**Comment by moez2302** [comment]
hello !!

**Comment by moez2302** [comment]
hello

**Comment by paulnoelcholot** [comment]
Hello @moez2302,

Thanks for your issue but despite my effort, I cannot reproduce your problem. Can you edit your issue description to translate to English and add a complete and detailed "step to reproduce"?

Thanks for your feedback!

**Comment by florine2623** [comment]
@moez2302 ,

This is not a core issue. You should contact the developer of the template you purchased.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
