### ISSUE TITLE
Can't switch product edition tabs when profile restricted to "View" only (Firefox Only)

### ISSUE THREAD

**Issue by Kaikina** [PrestaShop/PrestaShop#34073]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When viewing a product details, it's not possible to visualize other tabs by clicking the tabs names. The 'active' class is not properly attached to the new tab.
On the following screenshots, I were on the Price tab, and clicked the Shipping tab.
![image](https://github.com/PrestaShop/PrestaShop/assets/14168333/0e1fdbbe-40bf-4225-9a17-34d7833cb564)
As you can see, Shipping tab is active, but the tab content is not displayed.
![image](https://github.com/PrestaShop/PrestaShop/assets/14168333/9a2f05d9-c097-48b8-96e3-22c297603be4)
Here, you can see that the li element of the Shipping tab got the active class.
However, no any form content got the active class, thus the tab content being empty.

Reloading the page allows to get the tab content active.

  Using Firefox 117.0.1 for Ubuntu
  

### Expected behavior

The clicked tab get correctly displayed.

### Steps to reproduce

1. Create or update an existing profile.
2. For the catalog product page, keep only the view capability.
3. Go to the catalog product page, and visualize a product details.
4. Click on a new tab

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

1.7.8.9

### Your company or customer's name goes here (if applicable).

Evolutive

**Comment by Kaikina** [comment]
`$('#form-nav a').on('click', function (event) {
  event.preventDefault();
  $(this).tab('show');
});`

Executing this in the console, solves the issue on Firefox. Tabs not initialized at all, or too early ?

Adding this snippet to the product-header.js is a temporary fix, waiting for the solution.

**Comment by florine2623** [comment]
Hello,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you
