### ISSUE TITLE
ps_facetedsearch-price-indexer.php permission denied on cronjob

### ISSUE THREAD

**Issue by ValentiniVini** [PrestaShop/PrestaShop#34082]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi, for some time the cronjob in question has been giving me a strange result.

Start Exemple:
--2023-09-28 05:00:31--  https://catalogo.valentinivini.com/modules/ps_facetedsearch/ps_facetedsearch-price-indexer.php?token=a2a6c8a205&full=1
Risoluzione di catalogo.valentinivini.com (catalogo.valentinivini.com)... 46.252.149.241
Connessione a catalogo.valentinivini.com (catalogo.valentinivini.com)|46.252.149.241|:443... connesso.
Richiesta HTTP inviata, in attesa di risposta... 200 OK
Lunghezza: 4 [text/html]
ps_facetedsearch-price-indexer.php?token=a2a6c8a205&full=1: Permission denied

Impossibile scrivere in "ps_facetedsearch-price-indexer.php?token=a2a6c8a205&full=1" (Permission denied).
End Exemple.

To start the cronjob I use the wget command from the crontab of a Linux server.
Checking my online store it seems to me that the reconstruction of the price index worked correctly, as well as the winged cronjobs that I launch daily.
It appears that the index rebuilding process is trying to write something somewhere but doesn't have permission to do so.
I tried to change the permissions of the ps_facetedsearch-price-indexer.php file to 755 via my hosting cpanel but this didn't solve the problem.
I suspect that the problem arose after the update to version 1.7.8.10 or after the latest update of the ps_facetedsearch module but I'm not sure yet.
In your opinion, are there any files or folders whose permissions I need to change to avoid the error?

### Steps to reproduce

lunch this command:
https://catalogo.valentinivini.com/modules/ps_facetedsearch/ps_facetedsearch-price-indexer.php?token=a2a6c8a205&full=1
using wget and saving the resutl to file.

### PrestaShop version(s) where the bug happened

1.7.8.10

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

3.13.2

### Your company or customer's name goes here (if applicable).

Valentini Vini e Liquori

**Comment by sallemiines** [comment]
Hello,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers  : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by matks** [comment]
Hello @ValentiniVini try to look at the PHP error logs they should tell you exactly which line of code is failing

**Comment by ValentiniVini** [comment]
> Hello @ValentiniVini try to look at the PHP error logs they should tell you exactly which line of code is failing

Hallo.
Are there any php logs that can be consulted via ftp client or do you mean the hosting's php logs?

**Comment by matks** [comment]
I mean the hosting PHP logs

**Comment by ValentiniVini** [comment]
It seems to be very difficult to find the hosting's php logs.
They recommend activating Prestashop's internal logs but I don't know if it can be done or where to activate them.

**Comment by ValentiniVini** [comment]
There is a way to ativate a php log inside prestshop?

**Comment by ValentiniVini** [comment]
The problem was related to the permissions on the folders of the server that launches the cron job.
It basically couldn't write a spool file.
By changing the folder from which the command was launched the problem was solved.
This was not a plugin bug.

**Comment by ValentiniVini** [comment]
Thank you all for your assistance.
I apologize for the time I have wasted.

I close the request.
