### ISSUE TITLE
PHP Deprecated messages in Prestashop 8.1.2

### ISSUE THREAD

**Issue by tm8544** [PrestaShop/PrestaShop#34090]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Picked up from Apache log after updating to 8.1.2 (PHP is versio 8.1.24) (Windows 11 x64)

`PHP Deprecated:  strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in ...\classes\Tab.php on line 389`

`PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in ...\classes\Dispatcher.php on line 969`

`PHP Deprecated:  ucfirst(): Passing null to parameter #1 ($string) of type string is deprecated in ...\classes\controller\AdminController.php on line 987`

`PHP Deprecated:  ucfirst(): Passing null to parameter #1 ($string) of type string is deprecated in ...\classes\controller\AdminController.php on line 988
`

### Expected behavior

No 'PHP Deprecated' messages

### Steps to reproduce

Use Prestashop with PHP version 8.1 +

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1.24

**Comment by sallemiines** [comment]
Hello @tm8544 

Your PHP version is not comptabile with PS 812, Please check your systeme requirements ! 

https://devdocs.prestashop-project.org/1.7/basics/installation/system-requirements/ 

I'll close this ticket !  Please note that you can always create a new one if further information pops up.

Thank you !

**Comment by hibatallahAouadni** [comment]
Hello @tm8544 

Could you please provide clear and concise steps to reproduce the issue :pray: 
Please read our [system requirements](https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/#php-compatibility-chart), you shouldn't use PHP 8.2 with PS 8.1.1 .
Waiting for your feedback.

Thanks!

**Comment by tm8544** [comment]
My case is about using PS 8.1.2 with PHP 8.1, not PS 8.1.1 with PHP 8.2.
Mentioning "PHP 8 .1+" is my mistake, it should be PHP 8.1.
So, by the system requirements you referred to, I believe I'm using correct version when I have PHP 8.1.24.

**Comment by ljnuxxx** [comment]
Same for me,
Php 8.1.2
Prestashop 8.1.3
Php deprecated errors are shown on the apache error log, even if disabled from php config.
