### ISSUE TITLE
Not possible to add a cart rule with migrated page

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#34094]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Using the migrated Cart Rules page, is not possible to add a cart rule.

![Capture d’écran 2023-09-28 à 16 51 56](https://github.com/PrestaShop/PrestaShop/assets/2631425/e7859cec-850e-46bf-a6df-a7ea974793c9)
![Capture d’écran 2023-09-28 à 16 51 42](https://github.com/PrestaShop/PrestaShop/assets/2631425/2ec6f917-b290-4612-af21-0c4e3e7aadcc)

### Steps to reproduce

1. Enable "Cart Rules" feature flag
2. Go to Catalog > Discounts
3. See that a button is missing

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

n/d

### Your company or customer's name goes here (if applicable).

@Wepika

**Comment by jolelievre** [comment]
This page is still under development, I think the page was accessed with manual URL It's currently on pause because we lack resources but it should be continued later Of course you're welcome to take the job upon yourself

But this issue has no value IMHO so I close it
