### ISSUE TITLE
Can't select new image on original product back office edit after upgrading to 8.1.2

### ISSUE THREAD

**Issue by joecoolio66** [PrestaShop/PrestaShop#34110]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When adding a new image to existing product on original product back office page it will upload, but you can't select it to add a caption or change it to cover until saving the product first.  Once saved you can re-open it and select the new image.  This was not the case with 8.1.1.

### Expected behavior

You should be able to upload an image, select it and it should bring up the image details window so you can change to cover image or add a caption.  

### Steps to reproduce

1. Upload a new image to an existing product
2. Try to select it... it won't bring up the image details
3. Save the product
4. Re-open the product
5. Now you can select the new image and add details.

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1.23

**Comment by joecoolio66** [comment]
Also, when you open the product back up after saving, the image looks blank.. but it is not

**Comment by paulnoelcholot** [comment]
Hello @joecoolio66,

I tried to reproduce your issue but as you can see, I can't : 
[Products • the future (2).webm](https://github.com/PrestaShop/PrestaShop/assets/112863083/b1e29305-47a7-4f8b-be01-147c7d58e298)

Did I miss something?

Thanks

**Comment by joecoolio66** [comment]
The video shows the update using the new product page.  I'm saying the old product page now isn't working since the upgrade to 8.1.2.   We have a test site that we switched to the new product page for and I can confirm it does work with the new product page BUT the save and publish button stays gray if you just make changes to the images.  I have to make a small change to the description for it to become active.  This is another bug I guess

**Comment by joecoolio66** [comment]
This is the same as #34142.  Someone please merge them

**Comment by florine2623** [comment]
Ok, I'm closing this issue if the other one is the same as yours.

Let's follow the updates there.
