### ISSUE TITLE
PrestonBot : Retro engineering

### ISSUE THREAD

**Issue by RosaBenouamer** [PrestaShop/PrestaShop#34129]
[Steps of the PrestonBot](https://docs.google.com/spreadsheets/d/165vzK3-M1U2vzZVfEzuRk1atlpDGjx59WK0b7Lh36yc/edit#gid=158073843)

**Comment by boherm** [comment]
Done!

We have also a command in it to build and send by email a reports of PR (`bin/console pull_request:report:send_mail`) for:
- Waiting for code review
- Waiting for QA review
- Waiting for PM review
- Silent pull requests (PR with no labels, certainly in case of bot failure I guess?!)
