### ISSUE TITLE
missing hook actionSubmitAccountBefore

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#34134]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

missing hook at install in hook table

### Steps to reproduce

1. Install prestashop
2. look at hook table

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

all

### Your company or customer's name goes here (if applicable).

Creabilis

**Comment by florine2623** [comment]
Hello @jf-viguier ,

I reproduce the issue with PrestaShop version develop. In previous versions, the hook actionSubmitAccountBefore was available, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by jf-viguier** [comment]
@florine2623 i've already posted a PR https://github.com/PrestaShop/PrestaShop/pull/34133
