### ISSUE TITLE
Visual error on product slider listing on Product Page

### ISSUE THREAD

**Issue by gasacuna** [PrestaShop/PrestaShop#34145]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On product list for recommended products when you are on the product page, only the first product shows image, name, price and "add to cart" button. All other products only show the image.
[Error preview](https://drive.google.com/file/d/1j56_qKjnRcUh1j6Me4OEAq_3klOnVSU_/view?usp=sharing)

### Expected behavior

All products on the product list should look like the first one, with all the information

### Steps to reproduce

1. Go to https://bazarandreplast.com/mas-electrodomesticos/microondas-digital-23-lts-eiffel--2532
2. Scroll down to section "X otros productos en la misma categoría:"
3. There is the error

### PrestaShop version(s) where the bug happened

1.7.6.7

### PHP version(s) where the bug happened

8.1.16

### If your bug is related to a module, specify its name and its version

ps_categoryproducts 1.0.7

### Your company or customer's name goes here (if applicable).

Bazar Andreplast

**Comment by florine2623** [comment]
Hello @gasacuna ,

Please downgrade your PHP version to fit the configuration requirements : 
https://devdocs.prestashop-project.org/1.7/basics/installation/system-requirements/

**Comment by gasacuna** [comment]
Hi @florine2623, thank you for your reply!

I had made a mistake, site's PHP version was correct from the begining. We are currently using PHP 7.0 and based on the link you sent, it's supported.

What else could be causing this issue?

**Comment by paulnoelcholot** [comment]
Hello @gasacuna,

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Thank you

**Comment by gasacuna** [comment]
Hi @paulnoelcholot, I don't understand what you are saying, I'm currently having a bug on my site with module ps_categoryproducts.

I tried to talk with Prestashop Support and they told me I have create a ticket here on GitHub. I just need someone to help me with this weird error
