### ISSUE TITLE
Backoffice does not create thumbnails when inserting product images using old backoffice product page - 8.1.2

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#34142]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
today I've found a big problem in the product page, admin side with the classic view

when the images are uploaded the thumbs are not created

instead with the new structure, the thumbs are created

on the 8.1.1 was ok, the problem has been added on 8.1.2

![1](https://github.com/PrestaShop/PrestaShop/assets/653230/8f7a9608-529c-4a02-8a7c-8f9658d5dfd5)

bye

### Steps to reproduce

1. prestashop 8.1.2
2. go to the product page
3. set the classic view and not the experimental view
4. upload an image
5. push on F5
6. the image will be blank
7. in the img/p/.... will be present only the original photo

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello @maofree ,

I can't reproduce your issue on 8.1.2.

https://github.com/PrestaShop/PrestaShop/assets/16019289/5f0f4129-0eef-4ae9-b785-cd05e1583b33

Am I missing something ?

**Comment by Maofree** [comment]
Hi
I've tested on some websites and I get this problem on all of them
![1](https://github.com/PrestaShop/PrestaShop/assets/653230/657a411b-3a1b-48a6-af53-5483b29dd003)
upgraded on 8.1.2 saturday

**Comment by matks** [comment]
I wonder if this could be related to https://github.com/PrestaShop/PrestaShop/pull/33152 or https://github.com/PrestaShop/PrestaShop/pull/33407 (both PRs were done in 8.1.2)

**Comment by wakdev** [comment]
We have the same problem here. Seems like it's related to the new Multiple image formats feature.
If you enable it in the advanced settings, upload your image to your product, then go to the product page, seems like the images are generated correctly.

Weird behavior...

I confirm that the problem was not here on the 8.1.0 version.

**Comment by Maofree** [comment]
uploading the image I've seen this 500 error in the console

![1](https://github.com/PrestaShop/PrestaShop/assets/653230/ae945543-89e5-4ed5-84c8-3a95c35f154a)

![1](https://github.com/PrestaShop/PrestaShop/assets/653230/ed5852a1-440c-42f3-b32d-c43da41b8c23)

![1](https://github.com/PrestaShop/PrestaShop/assets/653230/39189b7b-5c4e-4038-b0d4-6341920a08f4)

**Comment by wakdev** [comment]
Seems like if you open the product page after upload your image, the thumbnails are generated.

**Comment by Maofree** [comment]
@wakdev 
yes the same for me

**Comment by matks** [comment]
(I improved a little the title to make it easier to find using keywords for other users)

**Comment by florine2623** [comment]
Here's my config :
<img width="822" alt="Screenshot 2023-10-03 at 15 48 03" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/1f3db6ee-b707-4175-ba39-672c1724f0af">


I have reproduced your issue. But if you refresh one more time, the problem won't be here no more. Can you try again like I did in the screenrecord ?

https://github.com/PrestaShop/PrestaShop/assets/16019289/fb32fe96-22cb-4021-a146-83160a108c17

**Comment by joecoolio66** [comment]
The behaviour is the same with multiple image formats disabled

**Comment by joecoolio66** [comment]
Also refreshing does not solve the issue... for example, you cannot make the new image the cover image until after going back to catalog and re-opening.... annnnnd the thumbnail is still blank even though the image is loaded properly

**Comment by wakdev** [comment]
> Here's my config : <img alt="Screenshot 2023-10-03 at 15 48 03" width="822" src="https://user-images.githubusercontent.com/16019289/272284371-1f3db6ee-b707-4175-ba39-672c1724f0af.png">
> 
> I have reproduced your issue. But if you refresh one more time, the problem won't be here no more. Can you try again like I did in the screenrecord ?
> Screen.Recording.2023-10-03.at.15.49.03.mov


> The behaviour is the same with multiple image formats disabled


I confirm that the behavior is the same whether the option is disabled or enabled.
In your screen recording, you go to your product page, this action seems to generate the thumbnails.

We're currently using this technique as a workaround, but there's obviously a problem here.

**Comment by joecoolio66** [comment]
I guess the question is... is the new product page reliable at this point?  If this issue doesn't exist in the new product page and there are no other reported issues, then the obvious resolution would be to switch.

**Comment by wakdev** [comment]
> I guess the question is... is the new product page reliable at this point? If this issue doesn't exist in the new product page and there are no other reported issues, then the obvious resolution would be to switch.

On our side, we experienced the same problem whether is a new product or a old product.

**Comment by florine2623** [comment]
> Also refreshing does not solve the issue... for example, you cannot make the new image the cover image until after going back to catalog and re-opening.... annnnnd the thumbnail is still blank even though the image is loaded properly

On my end, I can't reproduce your exact issue here.

> is the new product page reliable at this point?

@MatShir could you answer this question please ? :)

**Comment by joecoolio66** [comment]
> > I guess the question is... is the new product page reliable at this point? If this issue doesn't exist in the new product page and there are no other reported issues, then the obvious resolution would be to switch.
> 
> On our side, we experienced the same problem whether is a new product or a old product.

I was referencing the new product page... not a new product lol

**Comment by Maofree** [comment]
the problem in using the new graphics is that many modules that appear on the product page on the admin side are not compatible with this new solution and I saw that their configuration is not displayed. However, it worked fine on 8.1.1, as soon as I updated to 8.1.2 this problem arose. So I think we need to check what was changed in 8.1.2

**Comment by Maofree** [comment]
with this error I cannot upgrade other websites from the 1.7

**Comment by MatShir** [comment]
Thanks guys for the input ! We would like to fix this issue on the next patch but we can't reproduce it eachtime. Maybe there is some steps missing, do you have "multiformat image" enabled ?

**Comment by Maofree** [comment]
Hi
on my local demo is active the "Multiple image formats" option
instead on the other websites no, the same for New product page
I can give you the access to a website (installed from 8.1.0 to 8.1.1 to 8.1.2)

**Comment by MatShir** [comment]
> I guess the question is... is the new product page reliable at this point? I

For this question, I'm pretty confident the page is more stable than the previous one. The new page fixes more [55 old bugs](https://github.com/PrestaShop/PrestaShop/issues?page=3&q=is%3Aissue+label%3A%22Old+Products+Page%22+milestone%3A8.1.0+is%3Aclosed). The page is new, so there are small regressions that went through the QA's sharp eye. I know some agencies are very happy about it but only suggest using the old one if some of your module are not compatible with the new view. 
Anyway, if regressions are reported, we will try our best to provide a fix in the coming month ;)

**Comment by joecoolio66** [comment]
> > I guess the question is... is the new product page reliable at this point? I
> 
> For this question, I pretty confident the page is more stable than the previous one. The new page fixes more [55 old bugs](https://github.com/PrestaShop/PrestaShop/issues?page=3&q=is%3Aissue+label%3A%22Old+Products+Page%22+milestone%3A8.1.0+is%3Aclosed). The page is new, so there are small regressions that went through the QA's sharp eye. I know some agencies are very happy about it but only suggest using the old one if some of your module are not compatible with the new view. Anyway, if regressions are reported, we will try our best to provide a fix in the coming month ;)

We see some issues with it.  It's not as streamlined as the old product page for one.. but that can be gotten used to.  It's too strict on field lengths.. the old page allowed titles greater than 70 chars in length.  Also, we found a bug when trying to modify an already existing product... when trying to save a product with description of 5000 chars, it wouldn't allow it saying the description was over 21000 chars.  We switched back to the old product page... we can live with this minor bug for now.

**Comment by matks** [comment]
> I guess the question is... is the new product page reliable at this point? If this issue doesn't exist in the new product page and there are no other reported issues, then the obvious resolution would be to switch.

Hello there ✋ 

The "old product" page has been introduced in PS 1.7.0, like 5 years ago. The "new product" page has been introduced in PS 8.1 . You cannot compare a 5-years backoffice page to a 5-months backoffice page and expect the same thing 😉 one has benefited from continuous improvements and bugfixing over 5 years, one is brand new and is now being battle-tested by users (although it was also already tested in Beta phase). But the old page has some major problems that were there since 1.7.0 (for example it would simply crash as soon as there was too many combinations) that could not be fixed because the problem was how it was designed, and the new product page handles them way better. But yeah, just like any product freshly shipped, there are minor problems in it.

I think the old product page has a lot more bugs than the new, but people got _used_ to these bugs and forgot about them 😄 . They learnt how to work around them. But they were still there, and we wiped them in new product page.

The new product page is the future and from now it's only going to get better and better, and this can only happen _if people start using it_. If nobody uses it, the switch is never going to happen 😄 . Help us making it better 💪

**Comment by joecoolio66** [comment]
For sure... like I said, we found a bug when trying to save an existing product with less than 21000 characters in the description field.  We don't use combinations or attributes with products... so we've never noticed any issues with the older page, we think its great lol.  Anyway, we'll likely continue to use it until we can't anymore... I'm sure the new page will be quite robust by then.

**Comment by florine2623** [comment]
@PrestaShop/qa-functional ,
Can someone try to reproduce the following issue ?

> > Also refreshing does not solve the issue... for example, you cannot make the new image the cover image until after going back to catalog and re-opening.... annnnnd the thumbnail is still blank even though the image is loaded properly
> 
> On my end, I can't reproduce your exact issue here.
 

On my end, I can't reproduce it.

**Comment by Maofree** [comment]
- disable the new style about product page
- go in a product page and add a new image
- new or existing product should have the same problem

**Comment by joecoolio66** [comment]
Basically, once you upload an image you can't access it until you save, go back to catalog and then re-open it.  After you do that, it will allow you to change it's attributes (ie cover image or caption)

**Comment by Hlavtox** [comment]
@maofree Can you try this?

- Open `controllers/admin/AdminProductsController.php`.
- Find line 2898 - `$configuredImageFormats = $this->get(ImageFormatConfiguration::class)->getGenerationFormats();`
- Replace it with `$configuredImageFormats = SymfonyContainer::getInstance()->get(ImageFormatConfiguration::class)->getGenerationFormats();`

**Comment by joecoolio66** [comment]
Another issue we noticed with the new back office product page is that when duplicating an item which is no longer new, the new item created is also not considered new.  This is a deviation from the classic product page where we could list new items based on older items and have them be included as new.

**Comment by Hlavtox** [comment]
@joecoolio66 Please open separate issues for other problems, even more if it concerns the new product page. We are discussing the old one here. :-)

**Comment by ShaiMagal** [comment]
> @maofree Can you try this?
> 
> * Open `controllers/admin/AdminProductsController.php`.
> * Find line 2898 - `$configuredImageFormats = $this->get(ImageFormatConfiguration::class)->getGenerationFormats();`
> * Replace it with `$configuredImageFormats = SymfonyContainer::getInstance()->get(ImageFormatConfiguration::class)->getGenerationFormats();`

It works well. It should be ready for the next version 8.1.x :)

**Comment by AureRita** [comment]
Hi @maofree, 

Thank you for all your details and your report, I reproduce the issue with PrestaShop version 8.1.2, as you can see  

[Untitled_ Oct 16, 2023 4_14 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/c09af653-4d23-487c-9a22-23c3778cde31)

I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved.

Indeed, we can't put it in cover when we upload it and if we refresh or not go in FO, this image shouldn't be blank

Thanks

**Comment by Maofree** [comment]
> @maofree Can you try this?
> 
> * Open `controllers/admin/AdminProductsController.php`.
> * Find line 2898 - `$configuredImageFormats = $this->get(ImageFormatConfiguration::class)->getGenerationFormats();`
> * Replace it with `$configuredImageFormats = SymfonyContainer::getInstance()->get(ImageFormatConfiguration::class)->getGenerationFormats();`

Hi @Hlavtox 
yes it solves this problem

**Comment by RosaBenouamer** [comment]
Hello,
@maofree @Hlavtox 
if it's a sustainable solution perhaps @maofree you could propose a PR :-) ?

**Comment by joecoolio66** [comment]
I can confirm that this line change solves the issue as well

**Comment by ShaiMagal** [comment]
Yes, make PR please. Tested on 5 websites. Works well.

**Comment by MatShir** [comment]
@maofree a PR, a PR, a PR !!! :raised_hands:

**Comment by Maofree** [comment]
@MatShir 
I still don't know how to create a PR. Soon I'll start studying these github things too, I'll do it after updating all the sites to prestashop 8 (I also made my first theme for 8), I'm sorry but for the moment I don't know how to create a PR

**Comment by nicosomb** [comment]
Hello @maofree. You can have a look on this documentation: https://devdocs.prestashop-project.org/8/contribute/contribute-pull-requests/

**Comment by Maofree** [comment]
Hi @Hlavtox 
I've found another big problem with the new product page style. It creates problems to ps_mailalerts
https://github.com/PrestaShop/PrestaShop/issues/34358

**Comment by MatShir** [comment]
Fixed by #34351

**Comment by MatShir** [comment]
Thanks @Hlavtox
