### ISSUE TITLE
psgdpr - Release 2.0.3 - Details of Personal info of customers throws exception

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#34150]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On `develop` branch only, there's an exception when I click on psgdpr > Configure > Personal data management > Search for a customer name : John > Details

`An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "admin_products_v2_preview" as such route does not exist.").`

<img width="1439" alt="271952919-68550eb7-7cef-41dd-bfb6-b0493aa624b0" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/1833c23b-ccb8-4e90-aeb6-04ac61e3cf1e">

### Expected behavior

I should be redirected to the customer's information page in BO.

### Steps to reproduce

1. Install PS `develop` branch
2. Install https://github.com/PrestaShop/psgdpr/pull/222
3. Update the module psgdpr
4. Click Configure
5. GO to Tab 2 : Personal data management
6. Search for a customer
7. Click on Details
8. Error :x:

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

psgdpr

**Comment by Hlavtox** [comment]
@florine2623 
Does clearing the cache in `BO > Performance` fix the issue?
Does manually deleting content of `/var/cache` fix the issue?

**Comment by AureRita** [comment]
Hi @florine2623 

Thank you for your report, Unfortunately, I can't reproduce your issue, as you can see : 

[Untitled_ Oct 4, 2023 5_27 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/60dbb1a4-b24b-474d-8475-4ef8fae59e16)


Did I miss something ? 

Waiting for your feedback

**Comment by florine2623** [comment]
I did multiple things on my shop : generate robots.txt, clear cache, reinstall PR, I can't reproduce the issue 😓 
I guess we can close it now ^^
