### ISSUE TITLE
Issue to display products with combination on iphone 8 with Safari

### ISSUE THREAD

**Issue by Gaja-A** [PrestaShop/PrestaShop#34157]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,

I have the same problem as in issue #27589.

This page won't open on iOS 8 - https://1944.paris/fr/264-227-vernis-a-ongles-vegan-naturel.html

We have tested on 2 phones but the error still occurs. We have tried clearing the cache in safari and updating it but the error still occurs.

![image](https://github.com/PrestaShop/PrestaShop/assets/51961329/6cabe81b-2776-4876-96e7-14060f3121fa)

### Expected behavior

The product with combination page should load properly as it is the case in Google Chrome or Firefox.

### Steps to reproduce

Using a mobile phone with Safari (iphone 8 preferrably - I tested in android where it works well), access our site front-office
https://1944.paris/fr/264-227-vernis-a-ongles-vegan-naturel.html

Url to test : https://1944.paris/fr/264-227-vernis-a-ongles-vegan-naturel.html

### PrestaShop version(s) where the bug happened

1.7.8.2

**Comment by AureRita** [comment]
Hi @Gaja-A 

Thank you for your report, Unfortunately, we can't go in other website to reproduce an issue, 
Can you explain to us how we can reproduce your issue from a new install of prestashop 1.7.8.2 ? 

How did you create your product ? with wich type of Images ? 

Waiting for your feedback

**Comment by Gaja-A** [comment]
Hi,

I created a product with 94 combinations directly in Prestashop (all are in jpg format)

![image](https://github.com/PrestaShop/PrestaShop/assets/51961329/de2c9587-b90b-4f6e-83fb-db0600e82e7d)

Regards,
Gaja

**Comment by buggyzap** [comment]
Cannot visit your page... check that you make devices ddos. Think you have biggest problem than that redirect.

Also i think is not related by Prestashop.

https://github.com/PrestaShop/PrestaShop/assets/14024456/01541058-96ed-419e-a694-44d42b8cbee1

**Comment by florine2623** [comment]
Hello @Gaja-A ,

I have reproduced your issue. But this is an issue with your shop in particular. With other example shops, I couldn't reproduce your error.

![IMG_EDE6E86747D8-1](https://github.com/PrestaShop/PrestaShop/assets/16019289/8598636a-611b-40b4-9348-da943cfbd0b2)


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
