### ISSUE TITLE
Issue with update quantity on product sheet

### ISSUE THREAD

**Issue by lionelJDN** [PrestaShop/PrestaShop#34168]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello PrestaShop community! 😊

I am asking you because I am encountering an issue on version 1.7.8.6.

I'm unable to add quantities in the cart when I displayed a product sheet.
When I wrote a quantity of 100, the field reset the value and displays 30 (the minimum quantity configured for this product).

https://github.com/PrestaShop/PrestaShop/assets/111759208/89fe4eeb-1a7f-4945-8624-d6423de30e5e

![video](https://github.com/PrestaShop/PrestaShop/assets/111759208/9a2a0244-5eaf-4a45-8cea-2efe22d24509)

I got the following original javascript files from version 1.7.8.6 and updated them but it didn't change anything:
/themes/core.js
/themes/classic/assets/js/theme.js

Have you ever encountered this issue please?

Thank you very much for your advice.

Have a nice day.

### Steps to reproduce

1. Go to a sheet product on front-end
2. Change the quantity to 100

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4.13

**Comment by AureRita** [comment]
Hi @lionelJDN 

Thank you for your report, currently, your issue seems similar to this one : 
#31656 

(the issue is based on the first number you put, if you set a number under 3, this will change instantly) 

because this issue is already in our backlog, I'll close your issue. 

if you disagree and think it's not a dupplicate, you can say here and I'll open you issue 

Thank you for your contribution

**Comment by AureRita** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/31656

**Comment by lionelJDN** [comment]
I have the issue only if the "Minimum quantity for sale" is defined.
