### ISSUE TITLE
Product Search Relevance Option is Reversed When Manually Selected

### ISSUE THREAD

**Issue by mrkalchemy** [PrestaShop/PrestaShop#34174]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When using the search products are displayed ordered by "Relevance" but the "Sort by:" drop-down shows "Choose". If "Relevance" is selected from options the products are listed in reverse order. i.e. the lease relevant first. 

### Expected behavior

The "Relevance" option should be selected by default and list products with the most relevant first.

### Steps to reproduce

Do a search in the front end.
Check the sort order displayed on the results page and make note of the product order.
Use the on page drop-down to select "Relevance" sort order.
Check the order of the displayed products.

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

**Comment by mrkalchemy** [comment]
The problem can be solved by modifying src/Core/Product/Search/SortOrdersCollection.php and changing the 'asc' to 'desc' at line 54.

change:
            (new SortOrder('product', 'position', 'asc'))->setLabel(
                $this->translator->trans('Relevance', [], 'Shop.Theme.Catalog')
            ),
to:
            (new SortOrder('product', 'position', 'desc'))->setLabel(
                $this->translator->trans('Relevance', [], 'Shop.Theme.Catalog')
            ),

If required I can submit a PR on the 8.1.x branch.

**Comment by Hlavtox** [comment]
It's the responsibility of the product search provider to return properly ordered products depending on what the core is passing.

So if you have default product sort set to `relevance, ascending`, but the products are sorted wrong, it's not a problem of `SortOrdersCollection`, but `SearchCore`.

**Comment by mrkalchemy** [comment]
Sorry I think maybe there is some confusion.

If you do a search the results are displayed in the correct order. The order only becomes reversed when you manually select "Relevance" from the drop-down. I believe this is caused by the option being 'asc' not 'desc' as the higher the value the more relevant the result is.

I just had a look at the develop branch and it seems that a lot of stuff has changed so it may not be an issue in the future PS 9.x releases.

I've only tested in the current 8.1.2 version.

**Comment by Hlavtox** [comment]
OK I see the issue.

- My default sorting in `BO > Shop settings > Products` is `Position inside category, Ascending`.
- On search page, I get `field: "position", direction: "desc"`.
- When I manually select "Relevance" in the dropdown, I get `field: "position", direction: "asc"`.

So, two questions/issues.
- I think the search results should be ordered correctly on ASC order. Because like in category -> lowest position, most relevance?
- Why is the core changing the default sort order from asc to desc on initial page load? It does so only on search controller, on category page, I get `field: "position", direction: "asc"` like I should.

**Update:**
- It's because search controller is ignoring the default sort order set in BO configuration and hard sets it to `->setSortOrder(new SortOrder('product', 'position', 'desc'))` in `SearchController`, unless you manually selected a different sort order.

**Comment by mrkalchemy** [comment]
I think that the higher the number the more relevant the result and that's why it's set to descending. Because the most relevant results should be at the beginning of the page.

**Update:**

Just checked and in classes/Search.php at line 351 there is a subquery that calculates the "position" value and it is indeed as I suspected. It seems that the search results page works differently to the other product listings.

**Comment by florine2623** [comment]
Hello @mrkalchemy ,

I have my product displayed in reverse order here :

<img width="1167" alt="Screenshot 2023-10-09 at 16 27 29" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/3e4c29dc-b417-4fa5-8471-e09d871b451b">

<img width="1163" alt="Screenshot 2023-10-09 at 16 28 17" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/5d388d68-cbcd-44b5-a600-d7e465e779d0">

Is that the issue you're explaining ?

Waiting for your feedback.

**Comment by mrkalchemy** [comment]
Hello @florine2623,

Here's an image that may help explain the issue.

![Search12](https://github.com/PrestaShop/PrestaShop/assets/123658706/d8b53362-73c4-4962-bb8e-fa0899a45629)

When a search is performed by a user the results are listed by in the correct order so the most relevant products are at the beginning of the list. But the "Sort by" drop-down option for "Relevance" is not selected.

If you change the "Sort by" drop-down to "Relevance" and refresh the search page the results become reversed so the least relevant products are shown first.

This seems to be caused by a mismatch between the query in classes/Search.php at line 351 that calculates the search weight/position and the drop-down menu in src/Core/Product/Search/SortOrderCollection.php.

Hope that clears things up a bit.

**Comment by mrkalchemy** [comment]
My original though was to simply update the position option in the SortOrderCollection.php file. However I didn't realise that this would effect other product lists not just the search.

If the query in the Search class was changed to add a "0-" prefix then that would reverse the order by making the position have negative values but the default sort order would also have to be changed in the SearchController as well.

I can submit a PR for this second method if that would be helpful.

**Comment by AureRita** [comment]
Hi @mrkalchemy 

Thank you for your report, I tried to reproduce your issue but currently I can't as you can see : 

[Untitled_ Oct 16, 2023 4_46 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/5bef03cf-666a-44b1-ace2-675c71ff523a)

Did I miss something ? 

I just have another space between two product but I don't think this is your issue 

Waiting for your feedback

**Comment by Hlavtox** [comment]
@kpodemski What do you think is a correct way to solve this problem?

- One thing is that search controller hard sets some sort order ignoring the default sort set in BO.
- Second thing that search class has reverse logic for the relevance.

**Comment by mrkalchemy** [comment]
Hi @AureRita
Yes the spacing changes as well when you select the option from the drop-down list. That's a problem with the JavaScript that does the in page update. Not what I was having the issue with but it probably does fixing as well.

**Comment by mrkalchemy** [comment]
Hi @Hlavtox and @kpodemski

I suggested a solution, above, to fix the problem that should work on both the 8.1.x and dev branches. If you're not sure then I can submit a PR for you to look at.

**Comment by mrkalchemy** [comment]
I've created a PR (https://github.com/PrestaShop/PrestaShop/pull/34317) of my proposed solution. It's a pretty simple fix so it shouldn't cause any further problems.

**Comment by mrkalchemy** [comment]
> Thank you for your report, I tried to reproduce your issue but currently I can't as you can see :
> Untitled_.Oct.16.2023.4_46.PM.webm
> 
> Did I miss something ?

Hi @AureRita,

Sorry I just realised that I never fully answered the question. If the search results are all equally good matches (identically weighted) then the display order wouldn't appear to change. I finally installed OBS so I made a screen capture that should make it clear.

[2023-11-03 09-51-17.mkv.webm](https://github.com/PrestaShop/PrestaShop/assets/123658706/d1a500f4-b098-413a-8696-0774638f8d20)

In the video I do a search for "note fox" this matches three products but the one that includes "fox" in it's title comes first. Then I select the "Relevance" option from the "Sort by" drop-down and the order is reversed.

My issue was that the "Relevance" option should be selected by default and it should display in the correct order when it is selected.

Hope this helps.

**Comment by AureRita** [comment]
Hi @mrkalchemy 

Thank you for your details, with the provided information I can reproduce your issue with prestashop version 8.1.2, as we can see : 

[Untitled_ Nov 9, 2023 3_59 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/4d69a5fd-b607-4ec1-8526-b0cecafb73af)

I'll add this on the patch backlog, 

Thank you for your PR :rocket: 

Thank you

**Comment by matks** [comment]
Fixed in 8.1.3 by https://github.com/PrestaShop/PrestaShop/pull/34317
