### ISSUE TITLE
Log/Retry for call api github

### ISSUE THREAD

**Issue by RosaBenouamer** [PrestaShop/PrestaShop#34175]
To log all failed calls to the GitHub API, and retry in the wake. 

This could be avoid this kind of problem: No QA after 10 minutes https://github.com/PrestaShop/PrestaShop/pull/34078#event-10510259448

discuss with @boherm

An[ other issue](https://github.com/PrestaShop/PrestaShop/issues/34176) will be created to try to add a system of retry a couple of minutes later if needed after testing the solution in the wake.

**Comment by boherm** [comment]
Maybe this can work, we must check the footprint in memory anyway:
https://symfony.com/blog/new-in-symfony-5-2-retryable-http-client

**Comment by boherm** [comment]
Fixed by https://github.com/PrestaShop/kanbanbot/pull/28
