### ISSUE TITLE
Template email product details before header table

### ISSUE THREAD

**Issue by lionelJDN** [PrestaShop/PrestaShop#34189]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

PrestaShop : 1.7.8.6

Hello everyone,

I am asking for your advices because I have an issue about email template (order_conf).
I made some HTML modifications and I ended up with the product details before the table headers:

[https://imagizer.imageshack.com/v2/1536x445q90/r/922/N3ayoK.png](https://imagizer.imageshack.com/v2/1536x445q90/r/922/N3ayoK.png)

 I finally used the original email template that I pasted in order_conf but I cannot find the products under my table. I use the good template because when I changed some text, I receive the updated template by email but the product display issue still remains.

### Steps to reproduce

1. Go to International / Translations 
2. Choose Type of translation ==> Emails translations
3. Select the type of email content ==> Body
4. Select your theme  ==> classic
5. Select your language ==> Français (French)
6. Modify
7. Core emails mails/fr/ ==> order_conf
8. Edit HTML version
9. Replace  src="{shop_logo}" by a static image
10. Save
11. When i placed an order, the confirmation order mail displayed with product details before head of the tab instead of after the heading of the tab

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4.13

**Comment by florine2623** [comment]
Hello @lionelJDN , 

Your issue is the same as https://github.com/PrestaShop/PrestaShop/issues/34057

I'm closing it to avoid clogging the backlog
