### ISSUE TITLE
Blockwishlist is not working with error on is_logged

### ISSUE THREAD

**Issue by perezborja** [PrestaShop/PrestaShop#34185]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you try to add a product to wish list, nothing happens. When you open browser terminal, it shows an error:

`TypeError: Cannot read properties of undefined (reading 'is_logged')`

It happens every time you click on favourite icon. No matter if you're logged or not.
![Captura desde 2023-10-06 10-20-43](https://github.com/PrestaShop/PrestaShop/assets/113688106/4d1e1e1e-2e00-4990-9b1c-0195a077ea56)

### Expected behavior

It should open the wish list and add this item to the list.

### Steps to reproduce

1. Open a product sheet.
2. Try to click on wish list hearth icon

### PrestaShop version(s) where the bug happened

8.0.3

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

blockwishlist 3.0.1

**Comment by AureRita** [comment]
Hi @perezborja 

Thank you for your report, I tried to reproduce your issue but currently I can't as you can see : 

[Untitled_ Oct 6, 2023 5_13 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/a36580f5-8fe7-4f47-b48d-a55563508e96)

Did I miss something ? 

Waiting for your feedback

**Comment by perezborja** [comment]
> Hi @perezborja
> 
> Thank you for your report, I tried to reproduce your issue but currently I can't as you can see :
> 
>  Untitled_.Oct.6.2023.5_13.PM.webm 
> Did I miss something ?
> 
> Waiting for your feedback

No, seems to be working fine for you. But with same procedure, I does not add to the customer wishlist and when you open browser terminal, it appears the error that I attached on main msg, every time you press the wish button.

**Comment by AureRita** [comment]
Hi @perezborja 

Thank you for your detail, @PrestaShop/quality-council some of you can try to reproduce this issue ? 

In my part I can't 

Thank you

**Comment by florine2623** [comment]
Hello @perezborja ,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you
