### ISSUE TITLE
PS 8.1.2:Modules marketplace :Page non trouvée, Le contrôleur AdminPsMboModule est manquant ou non valable.

### ISSUE THREAD

**Issue by orvalvert** [PrestaShop/PrestaShop#34188]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi

Page modules >marketplace not found 
 AdminPsMboModule is missing or not available

![erreur click sur  Module - marketplace](https://github.com/PrestaShop/PrestaShop/assets/143817250/27b0e26f-6d35-4622-9f2f-16db1ced73de)

### Steps to reproduce

Modules 
click on Marketplace 

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1.20

### If your bug is related to a module, specify its name and its version

AdminPsMboModule

**Comment by matks** [comment]
Sounds similar to https://github.com/PrestaShop/PrestaShop/issues/32132

**Comment by orvalvert** [comment]
see #34170 who 's not finished and explain why did this happened

**Comment by AureRita** [comment]
Hi @orvalvert 

Thank you for your report, Currently we didn't have marketplace on 8.1.2, Did you do an autoupgrade previously ? if yes, can you tell us from wich version ? 

Waiting for your feedback

**Comment by orvalvert** [comment]
Hi @AureRita 
Please read #34170 last comment, you 'll understand . first was ps 8.1.0 then upgrade with errors on 8.1.2
What do you mean " Currently we didn't have marketplace on 8.1.2," ?

Thanks

**Comment by florine2623** [comment]
Hello @orvalvert ,

You can download the module here : https://addons.prestashop.com/en/administrative-tools/39574-prestashop-marketplace-in-your-back-office.html
