### ISSUE TITLE
Prestashop 8.1.2 product list on catalogue : on click error Symphony, unable to display product by this way

### ISSUE THREAD

**Issue by orvalvert** [PrestaShop/PrestaShop#34186]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
in the list of products in the catalog I select a product by clicking on the image or on price or on modify (pen)   I obtain:

Oups... une erreur inattendue semble s'être produite!
Attempted to load class "RatesHelper" from namespace "PrestaShop\Module\Mbeshipping\Helper". Did you forget a "use" statement for another namespace?
[Symfony\Component\ErrorHandler\Error\ClassNotFoundError 0]

> 
![erreur click sur ligne produit du catalogue_ etape1](https://github.com/PrestaShop
![erreur click sur ligne produit du catalogue_message d'erreur](https://github.com/PrestaShop/PrestaShop/assets/143817250/b460f646-96bb-486e-a2ce-2daa9dd583c7)
/PrestaShop/assets/143817250/80559a2e-4f9b-4a7a-bb67-d9feaad08bf5)

### Steps to reproduce

(upgrade PS 8.1.0 to 8.1.2   parameter to switch to French)

go to catalogue > Products
click on first image of the list

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1.20

**Comment by orvalvert** [comment]
see #34170 who 's not finished and explain why did this happened

**Comment by florine2623** [comment]
Hello @orvalvert ,

Can you try to rollback ?
And the disable the module MbeShipping before relaunching another upgrade ?

**Comment by orvalvert** [comment]
Hello Florine

Thanks for your help

I 've done a new upgrade by click upgrade mode expert , copying zip and xml from site prestashop and this problem is  no longer present. But the upgrade ends with errors (PJ)

![erreur upgrade ps 8 1 0 to 8 1 2 mode expert](https://github.com/PrestaShop/PrestaShop/assets/143817250/b8052357-432f-49d4-9bfd-06c088db03d2)

**Comment by AureRita** [comment]
Hi @orvalvert 

Thank you for your report, I try to reproduce your issue also with the expert mode as you can see : 

[Untitled_ Oct 16, 2023 5_15 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/01d2afe7-3ba6-49fd-aca7-2548e067d6bd)

Currently I can't reproduce your issue, did I miss something ? 

Can you enable the debug mode to see your error ? 

Waiting for your feedback

**Comment by florine2623** [comment]
Hello @orvalvert ,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
