### ISSUE TITLE
PPV2 - multistore - Exception is displayed when I change my context shop while editing a product

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#34197]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

There's an exception displayed in the shop context modal.

<img width="1440" alt="Screenshot 2023-10-06 at 17 05 32" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/0e1111b4-216f-49b7-8341-c4653f682bf2">

`An exception has been thrown during the rendering of a template ("Field "cancel" has already been rendered, save the result of previous render call to a variable and output that instead.").`

Without debug mode :
<img width="1438" alt="Screenshot 2023-10-06 at 17 08 41" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/0b085347-96bd-4a21-b06d-a8f035f21e4f">

### Expected behavior

I should be able to change my context shop without error.

### Steps to reproduce

1. Go to BO > Shop parameters > General > Enable multistore
2. Go to Advanced parameters > Multistore > Create a new shop
3. name of your new shop : new shop > Add your URL /newshop
4. You are now in your shop context "new shop"
5. Go to Catalog > Products > Add a product > Save
6. Go back to listing product
7. Edit your product
8. Change shop context with Select stores
9. See exception in modal :x:

#### Acceptances tests
* Tests ti modify : 
  * https://github.com/PrestaShop/PrestaShop/blob/c1546756c43f4d579e9c4da231e46a2966765bce/tests/UI/campaigns/productV2/functional/20_multistore.ts#L190-L194
  * https://github.com/PrestaShop/PrestaShop/blob/c1546756c43f4d579e9c4da231e46a2966765bce/tests/UI/campaigns/productV2/functional/20_multistore.ts#L235-L244

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

**Comment by buggyzap** [comment]
I'm working on it, temporary commenting the exception will result in

![immagine](https://github.com/PrestaShop/PrestaShop/assets/14024456/e807609c-66be-4332-8a47-8f9b597fa3cc)

**Comment by florine2623** [comment]
Do you have the link to the PR ? 
If yes, can you share it please ?
Thanks!

**Comment by buggyzap** [comment]
> Do you have the link to the PR ? If yes, can you share it please ? Thanks!

Hi, sure, I have created the PR.
