### ISSUE TITLE
How to add an image banner to a Tema email?

### ISSUE THREAD

**Issue by nickosubisubombom** [PrestaShop/PrestaShop#34196]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

How to add an image banner to a Tema email?
I tried to add an image in the translation email - Edit HTML, but the accepted emails are faulty images (a question mark), and defective email logos!

### Steps to reproduce

How to add an image banner to a Tema email?

### PrestaShop version(s) where the bug happened

8.1

**Comment by matks** [comment]
Hello @nickosubisubombom maybe https://belvg.com/blog/how-to-edit-email-templates-in-prestashop-1-7.html will be useful

**Comment by nickosubisubombom** [comment]
image not showing in email template

**Comment by florine2623** [comment]
Please check this link : https://www.prestashop.com/forums/topic/373261-image-not-showing-in-email-template/

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
