### ISSUE TITLE
Cant enable WebP image format, PS 1.8.2

### ISSUE THREAD

**Issue by markoopapa** [PrestaShop/PrestaShop#34204]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Cant enable Webp Image format

I aatache a demo (video)

https://github.com/PrestaShop/PrestaShop/assets/20978213/1f5c350b-a78f-4446-ad1a-76e1fdd43e08

### Expected behavior

The settings cant be saved

### Steps to reproduce

1. Go to Dashboard
2. go to experimental future, 
3. enable new generation image
4. go to image settings
5. enable webp image format
6. refresh page an see webp settings saved go away

### PrestaShop version(s) where the bug happened

8.1.1-8.1.2

### PHP version(s) where the bug happened

8.1

**Comment by markoopapa** [comment]
P.S.

I try to clear all VAR folder to have clean cache, but the problem presist

**Comment by florine2623** [comment]
Hello @markoopapa ,

I can't reproduce your issue on PS 8.1.2 :

https://github.com/PrestaShop/PrestaShop/assets/16019289/facf7bf0-f305-4324-9c56-8c7416b2ccdb

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by adviva** [comment]
@markoopapa I had the same issue because I had multiple PS_IMAGE_FORMAT configuration records in my database. Not entirely sure how this is happened but I guess is about the switch to the "experimental feature". Somehow it is not deleting the previous "not experimental feature" configuration or something like that I guess.

Deleting all the records and saving the config again worked. Hope it helps.
