### ISSUE TITLE
Product thumbnails not generating

### ISSUE THREAD

**Issue by shiyasp** [PrestaShop/PrestaShop#34218]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

No thumbnails are generated when saving/uploading pictures for newly added product unless I visit the preview product page.

https://github.com/PrestaShop/PrestaShop/assets/63903099/1e2b04c3-dcf2-4c7c-9ff1-073b14bb9e55

### Expected behavior

Product thumbnails should be generated automatically when uploading new product images

### Steps to reproduce

In BO, go to catalogue> Products> New Product (Create a new product and upload some pictures)> Save.
Go back to products and check the product added.

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

Qshop

**Comment by florine2623** [comment]
Hello @shiyasp ,

It seems like your issue is similar to https://github.com/PrestaShop/PrestaShop/issues/34142

Could you confirm ?

**Comment by shiyasp** [comment]
Yes It's same.
