### ISSUE TITLE
Message "The controller HOME is missing or invalid" after upgrade to 8.1.2

### ISSUE THREAD

**Issue by clement74** [PrestaShop/PrestaShop#34222]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello

After upgrading to version 8.1.2 with module 1-Click Upgrade, I get an error message "The controller HOME is missing or invalid" after login on the backoffice.
(No error message were shown during the upgrade process)

By checking the debug logs I get following warnings who seems link to the message:

WARNING                                                 app | Route not found in one of the Tab ps_edition_basic_homepage                                   Hide context                                             [▼   "message" => "Unable to generate a URL for the named route "ps_edition_basic_homepage" as such route does not exist."   "file" => "/home/thiasmax/public_prestashop/thias_skwal_prod/vendor/symfony/symfony/src/Symfony/Component/Routing/Generator/CompiledUrlGenerator.php"   "line" => 50 ]

WARNING                                                 app | Route not found in one of the Tab ps_edition_basic_settings                                   Hide context                                             [▼   "message" => "Unable to generate a URL for the named route "ps_edition_basic_settings" as such route does not exist."   "file" => "/home/thiasmax/public_prestashop/thias_skwal_prod/vendor/symfony/symfony/src/Symfony/Component/Routing/Generator/CompiledUrlGenerator.php"   "line" => 50 ]

Could you please help me to solve it ?

Best regard

### Expected behavior

Be redirected to a welcome page or the dashboard module.

### Steps to reproduce

1. Login on the backopffice then error message is shown directly
or
2. Click on prestashop top left logo then error message is shown

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1.22

**Comment by paulnoelcholot** [comment]
Hello @clement74,

I tried to reproduce your issue but as you can see, I can't :
[1-Click Upgrade _ 1-Click Upgrade • the future (1).webm](https://github.com/PrestaShop/PrestaShop/assets/112863083/190c7cfe-8c67-4c51-8dec-954dbe233d36)


Can you give me a detailed step to reproduce please? What is your version of 1-Click Upgrade? What is your PrestaShop version before the upgrade?

Thanks for your feedback

**Comment by clement74** [comment]
Hello paulnoel

The 1-Click Upgrade use is v4.16.4 
Previous version of the shop was 8.1.1 (downloaded from prestashop website and fresh install).
I have keep the default theme and only prepare some category and products.
When I see the availability of the version 8.1.2 in 1 click upgrade I install and get this error message

I share with you in the archive the "dev-2023-10-10.log" generate with those steps if it could help:
 - deleteing log of this day
 - click on prestashop top left icon to reproduce it
 - download new log file for this case.
 
Also if it could be revelant I add to the archive the "log.txt" of the upgrade process

[log.zip](https://github.com/PrestaShop/PrestaShop/files/12861419/log.zip)

Thanks !

**Comment by clement74** [comment]
Hi, 

By doing more test I discover that the 1 click upgrade had desactivate further modules causing the same kind of message for "prestashop metric" one as exemple.

The AdminPsEditionBasic module was also disabled so I guessed that the controller home message error was link to this.
I tried to turn it on, but degrade the situation :/

After login I 'm not able to get the back office working at all with following error message

----
Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "PrestaShop\Module\PsAccounts\Service\PsAccountsService"." at /home/thiasmax/public_prestashop/thias_skwal_prod/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php line 289 

Uncaught Exception: You have requested a non-existent service "PrestaShop\Module\PsAccounts\Service\PsAccountsService". 

Trace
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException:
You have requested a non-existent service "PrestaShop\Module\PsAccounts\Service\PsAccountsService".

  at vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:289
  at Symfony\Component\DependencyInjection\Container->make()
     (vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:231)
  at Symfony\Component\DependencyInjection\Container->get()
     (vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerTrait.php:68)
  at Symfony\Bundle\FrameworkBundle\Controller\AbstractController->get()
     (modules/ps_edition_basic/src/Controller/AdminPsEditionBasicController.php:99)
  at PrestaShop\Module\PsEditionBasic\Controller\AdminPsEditionBasicController->indexAction()
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:169)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:81)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (admin986vfhkiwrt7ap4kskh/index.php:84)         

Is there any way to activate psaccount (that may be disabled) or disable AdminPsEditionBasic ?

Best Regards

**Comment by clement74** [comment]
I finally find a way to disable AdminPsEditionBasic by renaming it folder "module/ps_edition_basic" and clear the /var/cache/dev and prod. 
This make the backoffice available again and I have been able to re-enable psaccount module.
So I try again to reactivate the rename properly module/ps_edition_basic (and clear the /var/cache/dev and prod) and all is finally working without any "controller XXX is missing or invalid"

I guess the root case of my incident is having tried to use 1 click upgrade with some prestashop modules not part of the opensource code and Upgrade has disabled lot's of those modules but not re-enable them.

I don't know if it's something normal because I have to avoid 1 click upgrade in my situation or if you may improve it with my experience of this case.

So waiting for your feedbacks, and decision to keep or close this case :-)

Best regards !

**Comment by florine2623** [comment]
Hello @clement74 ,

Glad to hear that it works properly now.
There's an option that you can disable or enable according to what you want to do with the modules :
<img width="1221" alt="Screenshot 2023-10-17 at 10 14 21" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/5b901e4b-1583-4d1a-9788-e9992f098652">

I'm closing the issue as it is fixed.
