### ISSUE TITLE
"Bell" notification display

### ISSUE THREAD

**Issue by Matteo-Perri** [PrestaShop/PrestaShop#34228]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If I deactivate the notifications of new customers, clicking on the bell no longer sells the word "customers" but you see the notifications and they never disappear.

![Notifiche](https://github.com/PrestaShop/PrestaShop/assets/147481683/8973aeab-ca6b-45a8-ab71-811b1210a3b0)
![Bell 2](https://github.com/PrestaShop/PrestaShop/assets/147481683/0d46c868-730b-49bb-9afc-fd6cd53ed5a1)

### Steps to reproduce

1. go to advanced parameters
2. go to administration
3. Turn off notifications for new customers
4. Look at the top right, the bell continues to show notifications for new customers even if they are turned off. (even when refreshing the page the notifications do not disappear)

### PrestaShop version(s) where the bug happened

1.7.7.4

### PHP version(s) where the bug happened

7.3.33

**Comment by paulnoelcholot** [comment]
Hello @Matteo-Perri 

PrestaShop 1.7 has reached end of life and is no longer officially maintained. We invite you to upgrade your shop to 8.0.4 or 8.1.2

If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Thank you
