### ISSUE TITLE
PPV2 - Specific prices can't be created for a particular combination

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#34229]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In PS 8.1.2, I want to create a specific price for a combination in particular. But all the combinations are not displayed; also I can't search for the said combination, there's no search field.

https://github.com/PrestaShop/PrestaShop/assets/16019289/ff58766f-d6dc-4717-9187-d4ec29886ccf

Might be related to https://github.com/PrestaShop/PrestaShop/issues/34203

### Expected behavior

All my combination should be displayed. Or I should have a search input field.

### Steps to reproduce

1. Go to BO > Create a combination product
2. Generate more than 20 combinations
3. Go to Pricing > Specific price block > Add a specific price
4. See in "All combinations" : only 10 combinations are displayed :x:
5. There's no search field to find another combination that is not already displayed in the dropdown :x:

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

**Comment by paulnoelcholot** [comment]
Hello,

I reproduce the issue with PrestaShop version 8.1.2, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

[Products • the future (5).webm](https://github.com/PrestaShop/PrestaShop/assets/112863083/fc13a677-087a-4e49-bc5b-1101c9f47f07)

**Comment by Codencode** [comment]
Perhaps the only solution could be to set "minimumResultsForSearch" (select2) to 0, from what you can see from the select2 documentation there is no other solution https://select2.org/configuration/options-api


For a test in the file src/PrestasShopBundle/Form/Admin/Sell/Product/Pricing/SpecificPriceType.php on line 157

substitute:
`'data-minimum-results-for-search' => self::COMBINATION_RESULTS_LIMIT,`
with
`
'data-minimum-results-for-search' => 0,`

I created a pull request.

Obviously it is not the best solution in case of many combinations.

**Comment by kpodemski** [comment]
@PrestaShop/product-council can we prioritize it for 8.1.3? :)

**Comment by RosaBenouamer** [comment]
@MatShir I think it could be nice :-)

**Comment by MatShir** [comment]
closed by #34715

**Comment by MatShir** [comment]
closed by #34715
