### ISSUE TITLE
In the BO footer, the current shop is displayed between <strong> tags

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#34234]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the backoffice, on module pages, the footer contains a html-escaped <strong> tag:
![2023-10-10_132417](https://github.com/PrestaShop/PrestaShop/assets/7520695/fcc40adc-3b37-4ae0-8dec-e4b39fc04513)

I searched in existing issues, I didn't find, but I'm pretty sure it should be there. 

### Expected behavior

I expect the HTML tag not to be escaped.

### Steps to reproduce

In an installation with multishop activated
1. Choose a shop to set the shop context
2. Navigate to the modules page
3. Select module and click on `Configure` (If you don't see the footer in the screenshot, try another module. Not all module show this footer.)

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

any

### Your company or customer's name goes here (if applicable).

Société Biblique de Genève

**Comment by paulnoelcholot** [comment]
Hello @lmeyer1,

I reproduce the issue with PrestaShop version 8.1.2 with psgdpr 2.0.3, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/ddbf8101-1b90-49da-986c-d62a5e8e4db1)
