### ISSUE TITLE
1-click update doesnt work

### ISSUE THREAD

**Issue by Wondertoy** [PrestaShop/PrestaShop#34248]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

module is installed but when press the config button it gets timed out
I've tried to de-install and re-install module again

### Expected behavior

Module to work properly and update my prestashop version

### Steps to reproduce

module manager
click on 1-click update/config

### PrestaShop version(s) where the bug happened

1.7.6.7

### If your bug is related to a module, specify its name and its version

1-click update

### Your company or customer's name goes here (if applicable).

Wondertoys

**Comment by florine2623** [comment]
What is the exact issue ?
Please send screenshots.

**Comment by Wondertoy** [comment]
Hello,
hosting provider changed time from 30 to 300 seconds and solved the timeout issue.
Thank you

**Comment by florine2623** [comment]
I'm closing to issue then.
