### ISSUE TITLE
Menus doesn't work

### ISSUE THREAD

**Issue by Wondertoy** [PrestaShop/PrestaShop#34247]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

version 1.7.6.7
advanced options/import
menu doesn't work, all items are listed but any item can be selected.

![image](https://github.com/PrestaShop/PrestaShop/assets/147625681/a37abea3-d8b1-4a74-889a-b0048ef89ffa)

Any list in the back office is working

### Expected behavior

Menu should open and items should be elegible.

### Steps to reproduce

advanced options
click on import
what do you want to import? menu

### PrestaShop version(s) where the bug happened

1.7.6.7

### Your company or customer's name goes here (if applicable).

Wondertoys

**Comment by florine2623** [comment]
Hello @Wondertoy ,

You need to use the right version of PHP for your shop.

Please use PHP 7.2 max.

https://devdocs.prestashop-project.org/1.7/basics/installation/system-requirements/
