### ISSUE TITLE
Unnecessary page refresh when changing delivery option selection in checkout page

### ISSUE THREAD

**Issue by jouino16** [PrestaShop/PrestaShop#34259]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the following video, you can notice that there is an unnecessary page refresh when changing delivery option selection in checkout page.
In my humble opinion, this causes a bad user experience, especially in the case when the user has to make an action after changing the delivery option, like selecting a drop-off location.

https://github.com/PrestaShop/PrestaShop/assets/12447492/5053e13b-84e2-4cbb-b919-281ad95779bd

The code responsible for this behavior is the following:
<img width="1275" alt="refresh-code" src="https://github.com/PrestaShop/PrestaShop/assets/12447492/2098d802-8b3e-4284-bf0e-c2040835c007">

And this is controlled by the existence of this code `<div style="display:none" class="js-cart-payment-step-refresh"></div>` in the \templates\checkout\_partials\steps\payment.tpl file. This is the comment related to this line of code: {* used by javascript to correctly handle cart updates when we are on payment step (eg vouchers added) *}.

When you try to reproduce the issue, you will notice, that when you switch your choice (between the delivery options) in the delivery step (before reaching the payment step - IMPORTANT), the checkout page does not reload after each option change.
<img width="1275" alt="delivery-step" src="https://github.com/PrestaShop/PrestaShop/assets/12447492/fe22bbc0-68f9-4c8f-8992-358218d21f46">

This is the page source code at this step, and it does not have `<div style="display:none" class="js-cart-payment-step-refresh"></div>`.
<img width="1275" alt="delivery-step-first-display-code" src="https://github.com/PrestaShop/PrestaShop/assets/12447492/b3b14315-be17-48d1-8257-f45d1b28acba">

But then when submitting the delivery option and reaching to payment step, then heading back to the delivery step: the page will refresh after the first delivery option change.
<img width="1275" alt="delivery-step-edit" src="https://github.com/PrestaShop/PrestaShop/assets/12447492/0dfd0130-d6e4-4fbb-bd5e-97129a7f13ce">

This is due to the fact that the code `<div style="display:none" class="js-cart-payment-step-refresh"></div>` still exists in the code:
<img width="1275" alt="delivery-step-edit-code" src="https://github.com/PrestaShop/PrestaShop/assets/12447492/b5c04605-d2e7-4aa7-a9d8-570130aa013a">

I already checked a couple of related threads, where it was mentioned that this is a wanted behavior, that allows to update the order amount when applying a voucher in the checkout page at the payment step:
- https://github.com/PrestaShop/PrestaShop/issues/12456
- https://github.com/PrestaShop/PrestaShop/issues/14486

What is really happening is that when applying a voucher, the page only reloads when the snippet `<div style="display:none" class="js-cart-payment-step-refresh"></div>` is available in the source code (meaning at the payment step, or after clicking the edit button of the delivery step).

In my humble opinion, I find it weird to only reload the page when applying a voucher, only at the payment step. The customer may add a voucher at any other step from the above ones.
Applying the voucher at any other step other than the payment step (identification, address and delivery steps) does not trigger the page refresh, but the calculation is refreshed correctly through AJAX. But if the voucher comes with a gift product, the gift product will not be displayed as the section of products (top right in desktop mode) is not refreshed through AJAX.

In my humble opinion, the fix should be done by refreshing the products section (preferred solution), or only refreshing the checkout page when applying the voucher code.

I also saw in another comment in one of the previous threads, that the refresh is useful when the voucher code is based on carrier restriction. I tested it, by using a voucher that only works on a specific carrier, and it worked without the need to refresh the checkout page.

### Expected behavior

Checkout page should not reload when changing delivery option, after reaching payment step.

### Steps to reproduce

1. Add a product to the cart
2. Follow the steps in the above video

### PrestaShop version(s) where the bug happened

1.7.8.10

### PHP version(s) where the bug happened

7.4

**Comment by AureRita** [comment]
Hi @jouino16 

Thank you for your report, I tried to reproduce you issue and as you can see I can't reproduce your issue  : 

[Untitled_ Oct 13, 2023 11_38 AM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/98a9c323-204a-48f7-9280-b2f0f7958a88)

Did I miss something ? 

Waiting for your feedback

**Comment by jouino16** [comment]
@AureRita thank you for taking into consideration my reported issue.

You have actually reproduced the issue. Please check the following screenshot from your video (at second 41). You can see that the page is refreshing due to the request `order/updatedTransaction=1`.
<img width="1280" alt="issue-reproduced" src="https://github.com/PrestaShop/PrestaShop/assets/12447492/af33e495-e3ae-47fe-a370-851ceee16bdc">

To facilitate your test, please consider adding the request filter 'order' in the network tab of the browser, in case you are testing in English.

Also, please keep in mind that the issue does not occur when changing the delivery options, when reaching the delivery step the first time. But it occurs when you have already reached the payment step, then after clicking "Edit" on the delivery step, and then changing the delivery option.

Hope this helps.

**Comment by florine2623** [comment]
Hello @jouino16 ,

In future versions PS 8.0.x, 8.1.0 and develop, this bug doesn't exist anymore.

https://github.com/PrestaShop/PrestaShop/assets/16019289/ecda7c7c-1a3d-4af2-b4eb-56eeafda689f

So I am closing this issue to avoid clogging the backlog.
Thanks!

**Comment by jouino16** [comment]
Hi @florine2623,

Thank you for your message.

The video you have posted does not reproduce the correct steps.

Please recheck the video I have posted in my initial post (I showed the scenario twice).

Please note that you have to reach the payment step, then get back to the shipping step, then choose a different delivery option, this is when the issue happens which is the page refreshing.

Please let me know if you need any help with reproducing the issue.

Hope this helps.

**Comment by jouino16** [comment]
Hi @florine2623,

Have you got the time to check my previous message?

Please consider remaking your test based on the steps in my video.

**I have just tested on version 8.1.3 and the issue is still here.**

Thank you in advance.

**Comment by supportA3WEB** [comment]
Hi 

Sorry if I didn't follow all the issues.

But I have the same problem when I change step, to go back to the transporter step. The refresh happens even before I have selected a new transporter. 

I would like to know why the exit is closed and what has been done?

**Comment by dngraphisme** [comment]
I also looked for it myself because I don't find it consistent. In core_js (Prestashop 8.2), there's this:

```
if (queryParams.updatedTransaction) {
// this parameter is used to display some info message
// already set: just refresh page
window.location.reload();

return;
}
```

And the explanation from the comment:

```
/**
* On checkout page, when we get the refresh flag:
* On payment step, we need to refresh the page to be sure
* Amount is correctly updated on payment modules
*/
```

We really should think about doing something other than reloading the page...

**Comment by jouino16** [comment]
Hello, thank you guys for your comments. It looks like others are starting to notice this issue.

@dngraphisme please provide the file names and locations where you have found the mentioned code and comment.

Again, I see that @florine2623 didn't notice the issue, as she didn't take the time to replicate the steps.

Unfortunately, I don't have the permission to open the issue again.

Maybe @khouloudbelguith can do something about this. I appreciate your contribution in advance.

And also, this time you can test on PrestaShop 8.2.1, you will see that the issue persists.

This time please reproduce the exact same steps I have mentioned above, please take your time doing it.

**Comment by dngraphisme** [comment]
Hello @jouino16,

It's in PrestaShop's core_js: common.js

Line 55 `function refreshCheckoutPage()`

Sorry, but @florine2623  never answers correctly, and most of the time it's off the mark... I've already opened tickets too, and apart from saying "no, it's not working" or "no, it's not PS's fault, I'm closing it," nothing else happens...

So I don't even bother writing issues on GitHub anymore, even though I've been using PrestaShop for 14 years.

**Comment by jouino16** [comment]
Hello @dngraphisme,

Thank you for your reply. It is the function called from within the checkout-delivery.js. The solution I suggested above is to use Ajax, as it is the case for the rest of the page elements.

Regarding @florine2623, unfortunately, I agree, this is what I also noticed. She's always on a rush, and she doesn't take her time, apparently.

Again, please @khouloudbelguith come to the rescue.

Also, @AureRita, please check again, as you have already tested the issue.

**Comment by dngraphisme** [comment]
@jouino16 , @florine2623  didn't look at the function at all. This happens when you go back to the transporter step. 

At that point, it refreshes the browser...

 It's still incredible to close an exit without looking carefully...

Please @khouloudbelguith can you look at and do something else for this part that can be managed differently ?

Thanks Nicolas
