### ISSUE TITLE
PrestonBot - CheckForTableDescription

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#34269]
**[Specs](https://miro.com/app/board/uXjVNaqugCo=/?userEmail=rosa.benouamer@prestashop.com&track=true&utm_source=notification&utm_medium=email&utm_campaign=add-to-board&utm_content=go-to-board&share_link_id=108122974968):**
"1) Check some informations about table description in PR:
- PR Description : not empty
- PR Type: new feature, improvement, bug fix or refacto
- PR Category : BO, CO, FO, IN, LO, ME, PM, TE or WS
- Related issue (fixed ticket) : issue required  if PR is bug fix or feature and isn't TE, ME, or PM category
 
2) PrestonBot post a comment with theses errors (only if we have some errors to dispatch)"

**Todo**

- [ ] Opened
- [ ] Edited

**Comment by hibatallahAouadni** [comment]
@florine2623 @AureRita @paulnoelcholot don't forget to add the labels foreach new Task created by our beloved PM Mr. @MatShir  (my eyes are on you 👀  )
