### ISSUE TITLE
Errors with 1-Click Upgrade module 

### ISSUE THREAD

**Issue by LBl21** [PrestaShop/PrestaShop#34264]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, 

I tried to update my site on prestashop with 1-Click Upgrade but it didn't work (from 1.7.6.3 to 1.7.8) I couldn't access to the login page & dashboard, so I had to rollback to 1.7.6.3 to access to my dashboard. 

Prestashop version: 1.7.6.3
PHP version: 7.2.34
![Capture d’écran 2023-10-11 à 15 39 14](https://github.com/PrestaShop/PrestaShop/assets/147816292/c309e0b2-1c57-4f91-8daa-0cc23338dce7)

### Steps to reproduce

1. Enable maintenance mode 
2. Go to 1 click upgrade
3. Click on "Upgrade prestashop now!"
4. After the upgrade is done the errors appear on the screen 

### PrestaShop version(s) where the bug happened

1.7.6.3

### PHP version(s) where the bug happened

7.2.34

### If your bug is related to a module, specify its name and its version

1-Click Upgrade v4.16.4

### Your company or customer's name goes here (if applicable).

Drotek

**Comment by AureRita** [comment]
Hi @LBl21 

Thank you for your report, I tried to reproduce your issue but I can't reproduce it as you can see : 

[Untitled_ Oct 16, 2023 11_31 AM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/bccbfbe2-48ed-4878-8362-e09f03586a05)

Did I miss something ? You seems to have many files to update, try to update them before ? 

About the issue at the end, this one is already reported here https://github.com/PrestaShop/PrestaShop/issues/33297

Waiting for your feedback

**Comment by LBl21** [comment]
Hello @AureRita,

Thank you for trying ! How do I update the files before the upgrade ? 
Ok I'll check #33297 for the issue.

**Comment by florine2623** [comment]
You can go to Module > Module Manager > Update > Update all for the upgrade.
Say us if it's the same because in this case, this issue is already in our debug backlog and it's a dupplicate, To be informed when it's fixed, please subscribe to the issue mentioned above.
