### ISSUE TITLE
module Product Reviews

### ISSUE THREAD

**Issue by Frits1969** [PrestaShop/PrestaShop#34263]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I use the Prestashop module Product Reviews v6.0.2

When there is a update of any module, I have to turn on again the module Product Reviews

### Expected behavior

I expect that the module Product Reviews stay on.

### Steps to reproduce

1 Turn on the module Product Reviews
2 Update any module
3 Watch to the situation of the module Product Reviews

### PrestaShop version(s) where the bug happened

1.7.8.10

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

Product Reviews v6.0.2

### Your company or customer's name goes here (if applicable).

Geschenkenlaantje

**Comment by AureRita** [comment]
Hi @Frits1969 

Thank you for your report, currently I try to reproduce your issue but as you can see I can't : 

[Untitled_ Oct 13, 2023 11_33 AM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/4b1eebc2-fbca-471d-9449-d8f4711b7d0d)

Did I miss something ? 

Waiting for your feedback

**Comment by Frits1969** [comment]
I'm back

**Comment by Frits1969** [comment]
That's strange. Because I notice that every time I do an update, no reviews are visible or created that can be filled in on the site. And when I look at the module, I see that it is turned off.
When I get new updates, I want to film it and send it here,

**Comment by Frits1969** [comment]
Hello, 
I made a film about my issue (this issue) by mobile phone. 

https://github.com/PrestaShop/PrestaShop/assets/28409740/530879c2-f2bd-40b1-a911-1a73dd09c023

**Comment by florine2623** [comment]
Hello,

Thanks for your screen record.

I can't reproduce your issue.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

You should also change your admin folder name as it is displayed here on a public space.

Thank you
