### ISSUE TITLE
PrestonBot-initPullRequestTypeLabel

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#34273]
**Specs** 

Add label according to the type selected in PR table description: new feature, improvement, bug fix or refacto

**Todo**
- [ ] Opened 
- [ ] Edited

**Comment by hibatallahAouadni** [comment]
@florine2623 @AureRita @paulnoelcholot don't forget to add the labels foreach new Task created by our beloved PM Mr. @MatShir  (my eyes are on you 👀  )
