### ISSUE TITLE
PrestonBot-initBCBreakLabel

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#34274]
**Specs**

Add "BC break" label if the PR table description declare BC Breaks.

**To do**

- [ ] Opened
- [ ] Edited

**Comment by hibatallahAouadni** [comment]
@florine2623 @AureRita @paulnoelcholot don't forget to add the labels foreach new Task created by our beloved PM Mr. @MatShir  (my eyes are on you 👀  )
