### ISSUE TITLE
PrestonBot-removePullRequestValidationComment

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#34276]
**Spec**

"Revalidate table description of the PR:
if no errors detected, we remove the PrestonBot comment about it."

**To do**

- [ ] Opened
- [ ] Edited

**Comment by hibatallahAouadni** [comment]
@florine2623 @AureRita @paulnoelcholot don't forget to add the labels foreach new Task created by our beloved PM Mr. @MatShir  (my eyes are on you 👀  )
