### ISSUE TITLE
PrestonBot-initPRAvailableLabelInIssue

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#34275]
**Specs**

Add "PR available" label if the PR has an issue in the description.

**To do**

- [ ] Opened
- [ ] Edited

**Comment by hibatallahAouadni** [comment]
@florine2623 @AureRita @paulnoelcholot don't forget to add the labels foreach new Task created by our beloved PM Mr. @MatShir  (my eyes are on you 👀  )

**Comment by boherm** [comment]
This is canceled, because isn't necessary anymore. (hi @MatShir!)
