### ISSUE TITLE
PrestonBot-WelcomePeople

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#34270]
**[Specs](https://miro.com/app/board/uXjVNaqugCo=/?userEmail=rosa.benouamer@prestashop.com&track=true&utm_source=notification&utm_medium=email&utm_campaign=add-to-board&utm_content=go-to-board&share_link_id=108122974968)**
"1) Check if the PR author have already some commits in git history.

2) If not, PrestonBot post a comment with the welcome message."

**Todo**

- [ ] Opened
- [ ] Edited

**Comment by hibatallahAouadni** [comment]
@florine2623 @AureRita @paulnoelcholot don't forget to add the labels foreach new Task created by our beloved PM Mr. @MatShir  (my eyes are on you 👀  )
