### ISSUE TITLE
PrestonBot-CheckForNewTranslations

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#34271]
**Specs**
"1) Check if we have some translations string in the PR files.

2) If we have some new translations that isn't already exists in Catalogue EN of translations,
PrestonBot post a comment with all new strings to validate. (Or edit the comment if already in PR)

3) If needed, we add ""Waiting for wording"" label to the PR.

Note: If we have an old comment with new strings that is already validated with 
""Wording ✔️"", we declare them already valided when editing the comment."

**New rule**: If a string is edited on the PR (not only the new strings)

**To do**

- [ ] Opened
- [ ] Edited

**Comment by hibatallahAouadni** [comment]
@florine2623 @AureRita @paulnoelcholot don't forget to add the labels foreach new Task created by our beloved PM Mr. @MatShir  (my eyes are on you 👀  )

**Comment by WahbiPS** [comment]
@boherm Do we need QA on this ?

**Comment by boherm** [comment]
@WahbiPS, No, It can't be tested by hand before merging and deployed.
