### ISSUE TITLE
Multishipping chosing incorrect carrier for linked orders

### ISSUE THREAD

**Issue by joseharitza** [PrestaShop/PrestaShop#34288]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When an order contains products with carrier selections that do not math Prestashop creates linked orders and the user decides the carrier he wants. For the linked orders it is Prestashop who decides the carrier normally the cheapest (so in our case the "Pick and collect" witch is free).

The main problem is that this decision making does not correspond to the client's needs and the client gets to pay less than he/she should for the delivery of the global order.

We have even noticed that sometimes even if there are country restricted options when multishipping orders get accepted.

### Expected behavior

The ideal behavior would be to let the client chose the carrier for each of the linked orders.

Other solution would be to disable the orders when carries among products do not match.

### Steps to reproduce

1. Log into the back office
2. Create 2 different carriers and a third carrier "free"
3. Create 2 different products and attribute one of the carriers for each of the products and the "free" carrier on one of the products
4. Pass an order with the 2 products
5. You will get a linked order where the global delivery price equals just the fee of one carrier as for the second product Prestashop has chosen the "free" option even if it is not a real choice for the client.

### PrestaShop version(s) where the bug happened

1.7.5.1

### PHP version(s) where the bug happened

7.3

### Your company or customer's name goes here (if applicable).

Haritza

**Comment by Hlavtox** [comment]
Yeah, this doesn't work. There are some historic issues related to this.

Maybe:
- https://github.com/PrestaShop/PrestaShop/issues/15369
- https://github.com/PrestaShop/PrestaShop/issues/9998
- https://github.com/PrestaShop/PrestaShop/issues/28529

It would be good to summarize it into one well-written english issue and make specifications for it. 👍

**Comment by joseharitza** [comment]
It is a pity that seems to be no solution for the issue at the moment...

**Comment by AureRita** [comment]
Hi @joseharitza 

Thank you for your report, as Hlavtox said, your issue seems to be the same than #15369, are you agree with this ? 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Waiting for your feedback

**Comment by joseharitza** [comment]
The origin of the problem is the same but the issue is described only as a display error as if Prestashop makes its decision correctly while most of the times that does not correspond to the client needs...
Even worse, it is difficult to handle when the explanation is given to the client asking them for further money as what has been paid it is not enough to deliver the order...

I was looking for help, I have talked to the experts from addons and they have guided me here telling that I should open a ticket...

**Comment by florine2623** [comment]
Hello @joseharitza ,

Here you will find all the issues regarding multicarriers : https://github.com/PrestaShop/PrestaShop/issues/15491

It is still a WIP.
I'm closing your issue to avoid clogging the backlog.
