### ISSUE TITLE
MPN and EAN13 with NULL can give errors in the new product page. Upgrade from 1.7 to 8.1

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#34287]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
I report an error that I get with some websites after the upgrade from 1.7.8.9 to 8.1.2 using the new product page

it is due from NULL values in the ps_product and ps_product_attribute about these fields
mpn
ean13
upc
isbn

normally I get this problem with mpn and ean13

to solve it I remove the NULL values from those fields

I wanted to warn you about this problem

![1](https://github.com/PrestaShop/PrestaShop/assets/653230/f6483d04-4afb-4536-96fe-5767341766c6)
![2](https://github.com/PrestaShop/PrestaShop/assets/653230/6fe9e70f-ba96-4d8b-97da-49bc937b0f1b)

bye

### Steps to reproduce

1. set the new style of product page, admin side
2. set NULL for a product in the database into ps_product and ps_product_attribute if it has combinations

bye

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

**Comment by AureRita** [comment]
Hi @maofree 

Thank you for your report, I try to reproduce your issue but I can't reproduce it as you can see : 

[Untitled_ Oct 16, 2023 2_57 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/bcf8a999-e89c-4ece-a15e-bf2fd46bff7c)

Did I miss something ? 

Did you change anything else ?

Can you give us a video ? Can you enable debug mode to see your error ?  

Waiting for your feedback

**Comment by Maofree** [comment]
Hi
the error appears in product page of the back-office, not in the front-office

go to see in the product page of the product with id = 1 (you have tested on this one). If the product has combinations it is necessary to add NULL in ps_product_attribute of that demo product

**Comment by Hlavtox** [comment]
@maofree @AureRita 

Most information - https://github.com/PrestaShop/PrestaShop/issues/22215
Duplicates:
- https://github.com/PrestaShop/PrestaShop/issues/25996
- https://github.com/PrestaShop/PrestaShop/issues/22862
- https://github.com/PrestaShop/PrestaShop/issues/22386
- https://github.com/PrestaShop/PrestaShop/issues/22215

**Comment by Hlavtox** [comment]
@maofree Run these queries, it will fix the DB ;-) https://github.com/PrestaShop/autoupgrade/pull/605/files

**Comment by Maofree** [comment]
@Hlavtox 
thanks for this file
it is for 8.1.1, so why in the 8.1.2 I got this problem?
in theory it should correct these things itself by updating to 8.1.1 and later. Maybe the fix was applied after I had already updated to 8.1.1

**Comment by Hlavtox** [comment]
@maofree It wasn't merged, it's not a permanent good solution because for example even the built in backup function will mess up the data. :(

Backup DB using backoffice > restore it > errors with NULL values everywhere.

**Comment by florine2623** [comment]
@maofree ,

I can't reproduce your issue.

I created 1 product (id 23) on 1.7.8.9 with the options ISBN, EAN, MPN, UPC and 1 product without anything (id 24). On BO and FO it is OK. On the database, the info is well saved :
<img width="1190" alt="Screenshot 2023-10-18 at 15 11 33" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/b025d67a-4055-4c6c-9896-31f0553e128a">

I upgraded from 1.7.8.9 to 8.1.2 ✅ 
<img width="1213" alt="Screenshot 2023-10-18 at 15 27 50" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/ce837b9c-3a88-4cbb-a3dc-dbd4eff35966">

After the upgrade, I checked the BO and FO, both of the product pages are well displayed.

The only problem that I have is that the format of ISBN is not correct so I have an error like this :
<img width="792" alt="Screenshot 2023-10-18 at 15 29 50" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/19359535-2756-417c-b2c1-cc2e939bed2a">

**Comment by Maofree** [comment]
Hi  @florine2623 
@Hlavtox  knows this problem
to reproduce this error, you need to go in the phpmyadmin and set NULL into the ean13 or mpn field (if the product has combinations you need to do that into ps_product_attribute)
then go to the product page back-office side and you will get this error

**Comment by Hlavtox** [comment]
@florine2623 It happens only on installs upgraded from older versions of prestashop. It's a legit issue open million times before.

**Comment by florine2623** [comment]
Oh yes sorry. I have reproduced the issue now 😅 


<img width="1096" alt="Screenshot 2023-10-18 at 16 03 43" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/0c9f3ceb-d77e-4c77-8e75-8b7af3f081d5">


Here are the exact steps I followed :

- Install 1.7.8.9
- Create 1 product with ISBN, with old product page
- Upgrade your shop to 8.1.2
- Enable New product page
- Enable mode debug
- Go to phpmyadmin, modify ISBN to NULL
- Go to BO > Product page > See error

**Comment by MatShir** [comment]
Do you know where the NULL could come from ?

**Comment by florine2623** [comment]
@MatShir it is modified directly in the database

**Comment by MatShir** [comment]
My question was for @maofree and @Hlavtox if they had hint on why we add NULL values

**Comment by Maofree** [comment]
@MatShir 
I don't know the answer, maybe it was something that happened on the first versions of prestashop 1.7

**Comment by Hlavtox** [comment]
Everything is here - https://github.com/PrestaShop/PrestaShop/issues/34454

I think we can close this issue

**Comment by Hlavtox** [comment]
Closing in favor of https://github.com/PrestaShop/PrestaShop/issues/34454
