### ISSUE TITLE
List all the places in the DB where we store a reference to an Employee (only for actions / history)

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#34298]
List all the places in the DB where we store a reference to an Employee (only for actions / history)

- [ ] Investigate everywhere where the id_employee is used
  - [ ] Check if you have an associated command to identify UI impacts

**Comment by tleon** [comment]
# Employee ID uses in database

| Fields       |   Tables | BO Url|
| -------- | ------- | ------ |
| id_employee | customer_message | Bell icon in BO inside a popup |
| | employee table |
| id_employee | employee_shop |
| id_employee | message |  Bell icon in BO inside a popup |
| id_employee | message_readed |  Bell icon in BO inside a popup |
| id_employee | order_history |
| id_employee | order_payment |
| id_employee | log | /admin-dev/index.php/configure/advanced/logs/|
| id_employee | warehouse | admin-dev/index.php/improve/shipping/preferences/ ? |
| id_employee employee_lastname employee_firstname | supply_order_history |
| id_employee employee_lastname employee_firstname | supply_order_receipt_history |
| id_employee | module_preference | admin-dev/index.php/improve/modules/manage ? |
| id_employee | tab_module_preference | admin-dev/index.php/improve/modules/manage ? |
| id_employee id_employee_session | employee_session |


# Doctrine 

| Fields       |   Tables |
| -------- | ------- |
| id_employee | ModuleHistory |
| employee | AdminFilter |
| id_employee | StockMvt |


# Object Model property use 

| ObjectModel | FilePath | Line | 
| ----------- | -------- | ---- |
| CustomerMessage | classes/CustomerMessage.php | 38, 71, 87, 119 | 
| Message | classes/Message.php | 47, 66, 83, 131, 132, 164, 165, 191 |
| EmployeeSession | classes/EmployeeSession.php | 33, 49, 51, 71, 79 |
| Cookie | classes/Cookie.php | 503, 504, 556, 563, 574 |
| PrestaShopLogger | classes/PrestaShopLogger.php | 58, 59, 97, 155, 156, 160 |
| Config.inc | config/config.inc.php | 196, 198, 199, 201, 202, 206, 215 |
| Security | src/PrestaShopBundle/Resources/config/services/core/security.yml | 16 |
| admin | js/admin.js | (references to employee not usage) 215, 227, 992, 994, 1015 |
| define.inc | config/defines.inc.php | 159 |
| define_url.inc | config/defines_uri.inc.php | 50 |
| phpstan | phpstan-baseline.neon | multiples rules on employee |
| phpstan | phpstan-disallowed-calls.neon | some occurences | 
| PageVoter | src/PrestaShopBundle/Security/Voter/PageVoter.php | 117, 119, 122 |
| Access | src/Adapter/Security/Access.php | 36, 38 |


# Doctrine Property use 

| Entity | FilePath | Line | 
| ------ | -------- | ---- | 
| ModuleHistory | src/PrestaShopBundle/Entity/ModuleHistory.php | 53, 55, 89, 91, 95, 103, 109 |
| AdminFilter | src/PrestaShopBundle/Entity/AdminFilter.php | 51, 53, 101, 103, 107, 109, 115, 121 |
| AdminProductDataProvider | src/Adapter/Product/AdminProductDataProvider.php | 87, 88, 90, 96, 145, 149, 157, 171, 172, 174 |
| StockMvt | src/PrestaShopBundle/Entity/StockMvt.php | 80, 82, 260, 262, 266, 268, 274, 280, 284, 290, 292, 298, 302, 304, 308, 310, 314, 316, 322, 326, 328 |
| StockManager | src/Core/Stock/StockManager.php | 314, 315, 316, 318, 319, 320, 327, 408, 409, 410, 411, 412 |

# Methods that modify Ids

| Method | File | Short description | 
| ------ | ---- | ----------------- | 
| registerSession | classes/Cookie.php | Register a new session |
| configureModuleAction | src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php | Update a module configuration |
| persistFilterParameters | src/Adapter/Product/AdminProductDataProvider.php | Parameter for the product data filter |
| prepareMovement | src/Core/Stock/StockManager.php | Prepare a Movement for registration |
