### ISSUE TITLE
Prestashop cart slow because of a big cart response

### ISSUE THREAD

**Issue by chattago2002** [PrestaShop/PrestaShop#34304]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi everyone.
I have less then 150 products in my catalog but each product has combinations, for a total of about 1500 combinations.

When a user add items to cart the response is exponentially slower; on the contrary, with every product that is removed the cart response is faster (in the attached image you can see the remove operation of all items in the cart, one by one, and the response is faster and faster).

[Cart responses waterfall](https://i.stack.imgur.com/7zyTx.jpg)

I think the problem could be that response contains a lot of details about items in the cart, including superfluous information. For each product in the cart there's the list of "main_variants" of the item, so if you have 10 products in the cart and each product has 10 variants, the response includes details for all 100 variants.

Why is this "main_variants" attribute (object) useful in the cart response? Is there a way to avoid it in the cart response? Is this a different problem otherwise?

P.S. I have a few cart rules (about 40), not so many I believe, mainly related to customer and not to products (or cart amount)

### Expected behavior

A faster response to have a light cart management

### Steps to reproduce

1. Insert multiple products on the shop with 10-12 combinations
2. Add various products and combination to the cart
3. Every time you add a product the cart response is slower than the previous request

### PrestaShop version(s) where the bug happened

1.7.8.10

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment]
Hello @chattago2002 ,

It seems like your issue is the same as : https://github.com/PrestaShop/PrestaShop/issues/12915
My recommendations is to update your shop to a newer version.

**Comment by chattago2002** [comment]
> Hello @chattago2002 ,
> 
> It seems like your issue is the same as : #12915 My recommendations is to update your shop to a newer version.

Hi @florine2623 and thanks for reply.
Do you mean update to Prestashop 8?

**Comment by florine2623** [comment]
Yes exactly.
You can find the latest versions here : https://github.com/PrestaShop/PrestaShop/releases

If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Thank you

**Comment by chattago2002** [comment]
Is there no way to exlude it from the response in my version? even just as a test

**Comment by paulnoelcholot** [comment]
Hello @chattago2002 

I'm sorry but version 1.7.8 is now only maintained to resolve security vulnerabilities. To resolve this problem there is no other solution than to upgrade your version.
