### ISSUE TITLE
Restricted carrier still displayed

### ISSUE THREAD

**Issue by Daaaaad** [PrestaShop/PrestaShop#34316]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I restrict some carriers on the product page they are still displayed on checkout even if the restricted product is in the car.

### Expected behavior

I would like to see the "no carriers available" message

### Steps to reproduce

1. Create 2 carriers (1 named Belgium with only country Belgium selected and 1 named Others with other countries selected).
2. Choose a product and select only "Belgium" carrier in the delivery tab of the product (because we only want to deliver this product to Belgium).
3. If you checkout with a belgian address the right carrier is ok (https://capture.dropbox.com/luTEBqgHBMkZ2gga).
4. If you checkout with another address (spanish address for example) there is a carrier with blank name (https://capture.dropbox.com/575S69pwykgCGuAR).

### PrestaShop version(s) where the bug happened

1.7.8.7

**Comment by florine2623** [comment]
Hello @Daaaaad ,

I can't reproduce your issue.

When my address is in Belgium :
<img width="736" alt="Screenshot 2023-10-17 at 14 20 34" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/dc4f4111-8908-44b7-96f7-d86218dbb86c">

When my address is elsewhere :
<img width="727" alt="Screenshot 2023-10-17 at 14 20 46" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/fe0bea24-5be8-4e15-80bf-e3ae8c40a3bc">

**Comment by Daaaaad** [comment]
Hi @florine2623 👋 Thank you for taking the time to test it 👍 Are you trying on PS 1.7.8.7?

**Comment by florine2623** [comment]
On 1.7.8.10 yes

**Comment by Daaaaad** [comment]
Hello @florine2623 I forgot one step to reproduce my error : You need to have at least 2 products in your cart. The one you configured with the "Belgium carrier" only and another one with the default delivery configuration.

**Comment by florine2623** [comment]
Oh yes indeed ^^

I have reproduced it, and your issue is the same as https://github.com/PrestaShop/PrestaShop/issues/13080

So I'm closing your issue in favor of that one to avoid clogging the backlog ^^

**Comment by florine2623** [comment]
You can also find a list of issues that you might encounter when using multi carriers : https://github.com/PrestaShop/PrestaShop/issues/15491
