### ISSUE TITLE
BO - dashactivity - In block Traffic, Unique visitors redirects to an archived module

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#34322]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The link for Unique visitors redirects to an archived module :

<img width="273" alt="Screenshot 2023-10-17 at 16 14 59" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/e944d231-034d-4881-9a08-029cd0551083">

https://github.com/PrestaShop/statsvisits

<img width="1226" alt="Screenshot 2023-10-17 at 16 13 14" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/938e8af9-8c54-4f27-9756-c810f40028cc">

### Expected behavior

The link should not be displayed. Or it should redirect to the correct module.

### Steps to reproduce

1. Go to BO > Dashboard > Traffic block
2. Click on Unique visitors
3. See "Module not found"

### PrestaShop version(s) where the bug happened

8.1.x, develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

Dashboard Activity v2.1.0

**Comment by AureRita** [comment]
Hi @florine2623 ,

Thank you for your report, I reproduce the issue with PrestaShop version 8.1.X, as you can see :

[Untitled_ Oct 24, 2023 3_02 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/a4de0b90-4044-44c1-894c-644cfe1a6a85)

I'll add this to the backlog so it can be fixed.

Thank you for your PR 

Thanks

**Comment by florine2623** [comment]
@Hlavtox would you like to do this one too ? 🤗

**Comment by Hlavtox** [comment]
@florine2623 Yes! :-) Updated the PR - https://github.com/PrestaShop/dashactivity/pull/43
