### ISSUE TITLE
BO - dashactivity - Return/Exchanges are not updated

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#34321]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I have a merchandise return, the module dashactivity is not update with the correct information

https://github.com/PrestaShop/PrestaShop/assets/16019289/6578bc3f-595c-400f-8615-8b3bcf4f981a

Here I should have Return/Exchanges : 1

### Expected behavior

The module should update the number of merchandise return there is currently

### Steps to reproduce

1. Go to BO > Customer Service > Merchandise returns
2. Enable return > Save
3. Go to FO > Log into your customer account > Make an order
4. Go to Orders > Update status of your latest order to Delivered
5. Go to your customer account > Order details and history 
6. Click on your latest order > Request a return
7. Click on Dashboard > See Activity overview - Return/Exchanges is still at 0 :x:
8. Click on the link > See 1 merchandise return

### PrestaShop version(s) where the bug happened

8.1.x, develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

Dashboard Activity v2.1.0

**Comment by AureRita** [comment]
Hi @florine2623 

Thank you for your report, I tried to reproduce your issue, but currently I can't as you can see : 

[Untitled_ Oct 24, 2023 3_14 PM (1).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/4e6b158f-17aa-42e7-84a8-9cb7ba8df262)

Did you refresh your page when you do the return/exchanges ? 

Waiting for your feedback

**Comment by florine2623** [comment]
It seems fixed. I'm closing the issue.
