### ISSUE TITLE
BO - dashactivity, dashproduct - module can't be configured

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#34326]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have an error when I edit my Overview activity board
`This hook is not allowed here.`

https://github.com/PrestaShop/PrestaShop/assets/16019289/f0a14f4d-6fe6-4e6d-8de2-1955e3e849ef

Same error on dashproduct module :

https://github.com/PrestaShop/PrestaShop/assets/16019289/2e47dec2-8762-4183-aef9-f85dd2873021

### Expected behavior

I should not have the error and my configuration should be saved correctly.

### Steps to reproduce

1. Go to BO 
2. In  Activity overview > Click on the configure button
3. Edit any of the parameters
4. See error `This hook is not allowed here.` :x:
5. Refresh the page > See that the edition is not taken into account :x:

### Acceptance Tests
* Contact @PrestaShop/ui-tests-maintainers
  * https://github.com/PrestaShop/PrestaShop/blob/f490ea66621309290d8653bc134d9d2bf7be2395/tests/UI/campaigns/functional/BO/01_dashboard/03_productsAndSales.ts#L117-L126 
  * https://github.com/PrestaShop/PrestaShop/blob/f490ea66621309290d8653bc134d9d2bf7be2395/tests/UI/campaigns/functional/BO/01_dashboard/02_activityOverview.ts#L820-L829

### PrestaShop version(s) where the bug happened

8.1.x, develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

Dashboard Activity v2.1.0 & Dashboard Products v2.1.3

**Comment by AureRita** [comment]
Hi @florine2623 ,

Thank you for your report, I reproduce the issue with PrestaShop version 8.1.2, as you can see :

[Untitled_ Oct 24, 2023 2_56 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/4447bfba-855b-4e67-9e1f-6633b3527f34)

 I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved.

Thanks

**Comment by marianhlavac** [comment]
Experiencing the same issue on PrestaShop version: 8.1.2

<details>

Server information: Linux #15~22.04.1-Ubuntu SMP Fri Oct 6 13:20:44 UTC 2023 x86_64
Server software version: Apache/2.4.52 (Ubuntu)
PHP version: 8.1.2-1ubuntu2.14
Memory limit: 128M
Max execution time: 30
Upload Max File size: 128M
MySQL version: 10.6.12-MariaDB-0ubuntu0.22.04.1
MySQL server: 127.0.0.1
MySQL name: prestashop
MySQL user: prestashop
Tables prefix: ps_
MySQL engine: InnoDB
MySQL driver: DbPDO
Your web browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15

</details>

**Comment by Muksu38** [comment]
Hello

I have found the solution :
1) go to MAINTENANCE page (tab maintenance) in GENERAL PARAMETERS
2) Remove the IPs of the MAINTENANCE IP
Save
And voila !!! the ACTIVITY BOARD Works .... incredible

**Comment by Ferry74** [comment]
Hello,

Same problem in Prestashop 8.1.5 on two sites. One upgraded from Prestashop 1.7 to 8 and one fresh installed from Prestashop 8.1.0.
And above solution doesn't work on both sites.

**Comment by Mihai-Buiciac** [comment]
Hello,

I followed the chain of events and found that in `public function ajaxProcessSaveDashConfig()` the variable `$hook = Tools::getValue('hook');` receives the value of the form "hookName" (with "hook" prefix) and in the declaration of the constant DASHBOARD_ALLOWED_HOOKS it contains the names of the hooks without a prefix.

in controllers/admin/AdminDashboardController.php :
change

`private const DASHBOARD_ALLOWED_HOOKS = ['dashboardData', 'dashboardZoneOne', 'dashboardZoneTwo', 'displayDashboardToolbarIcons', displayDashboardToolbarTopMenu', 'displayDashboardTop'];`

with

`private const DASHBOARD_ALLOWED_HOOKS = ['hookDashboardData', 'hookDashboardZoneOne', 'hookDashboardZoneTwo', 'hookDisplayDashboardToolbarIcons', 'hookDisplayDashboardToolbarTopMenu', 'hookDisplayDashboardTop'];`

**Comment by EmilianoOzi** [comment]
> Hello,
> 
> I followed the chain of events and found that in `public function ajaxProcessSaveDashConfig()` the variable `$hook = Tools::getValue('hook');` receives the value of the form "hookName" (with "hook" prefix) and in the declaration of the constant DASHBOARD_ALLOWED_HOOKS it contains the names of the hooks without a prefix.
> 
> in controllers/admin/AdminDashboardController.php : change
> 
> `private const DASHBOARD_ALLOWED_HOOKS = ['dashboardData', 'dashboardZoneOne', 'dashboardZoneTwo', 'displayDashboardToolbarIcons', displayDashboardToolbarTopMenu', 'displayDashboardTop'];`
> 
> with
> 
> `private const DASHBOARD_ALLOWED_HOOKS = ['hookDashboardData', 'hookDashboardZoneOne', 'hookDashboardZoneTwo', 'hookDisplayDashboardToolbarIcons', 'hookDisplayDashboardToolbarTopMenu', 'hookDisplayDashboardTop'];`

Thanks, This is working Good

**Comment by matks** [comment]
Fixed in https://github.com/PrestaShop/PrestaShop/pull/36521

Problem introduced in PS 8.1.2  https://github.com/PrestaShop/PrestaShop/commit/1b884c8b4a5850cd45925bb41416ea16fffb1084

**Comment by TGD001** [comment]
> private const DASHBOARD_ALLOWED_HOOKS = ['hookDashboardData', 'hookDashboardZoneOne', 'hookDashboardZoneTwo', 'hookDisplayDashboardToolbarIcons', 'hookDisplayDashboardToolbarTopMenu', 'hookDisplayDashboardTop'];

it works also for me. Thank you
