### ISSUE TITLE
All assets urls are html encoded with symfony layout FF

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#34332]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

![Snímek obrazovky 2023-10-18 153952](https://github.com/PrestaShop/PrestaShop/assets/6097524/bac7af19-c954-4d00-a472-5bfe53fc3213)

### Expected behavior

It MUST NOT be encoded and it must be the same as before.

### Steps to reproduce

1. Get develop.
2. Enable "Symfony layout" feature flag.
3. Go to any symfony page and inspect the source code.

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

doesn't matter

Ping @M0rgan01 @jolelievre

**Comment by florine2623** [comment]
This can be tested by @PrestaShop/prestashop-core-developers

**Comment by M0rgan01** [comment]
This will be probably resolved by https://github.com/PrestaShop/PrestaShop/pull/33864

**Comment by Hlavtox** [comment]
@M0rgan01 Good! PR https://github.com/PrestaShop/PrestaShop/pull/33864 solved encoded assets! :-)

However, there are still some encoded URLs:
- Quick access links
- Quick access links in search
- Show my store link 
- Edit links
- Logo link
- (just show source code and search for `&#`)

**Comment by M0rgan01** [comment]
@Hlavtox Thanks for the list, I will try to correct them between 2 topics
