### ISSUE TITLE
Prestashop Checkout module not displayed on payment page

### ISSUE THREAD

**Issue by RocknRollAnimal** [PrestaShop/PrestaShop#34357]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

I currently use the Checkout module with Paypal's Sandbox mode. At the end of the URL I added after the #, experimental. Then I was able to connect my two accounts (the prestashop account and my Sandbox account) to the module.
In the module settings in the back office, I checked all the boxes to activate the payment module as explained in the tutorial.

However, it doesn't appear during the payment phase.

What's more, in debug mode, nothing appears during the payment phase. In the back office -> settings -> logs I don't see any errors either. So where can I see the error logs? Have you got any solution ?

Thank you in advance for your reply. Have a nice day!

### Steps to reproduce

1. Configure the Prestashop Module, after the # add experimental.
2. In test mode, link two accounts ( the prestashop one and the Paypal Sandbox one )
3. Configure preferences of payment, check every boxes are checked ( type of money + visitor,guests... + countries )
4. Try to do a payment on your shop. It doesn't work for me, nothing appears.

### PrestaShop version(s) where the bug happened

8.04

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

Prestashop Checkout 8.3.4.0

**Comment by florine2623** [comment]
Hello @RocknRollAnimal ,

Please contact the support of the module directly : https://help-center.prestashop.com/contact

Thank you
