### ISSUE TITLE
New product page style - doesn't pass  $params['id_product_attribute'] to its hook when the product has combinations

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#34358]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
I've found a big problem on the module Mail alerts v2.4.2
after many tests I can say that for products with combinations the module doesn't sent email to alert customers when they return available

instead for standard product without combinations the module sends email to registered and non-registered customers

![10](https://github.com/PrestaShop/PrestaShop/assets/653230/219735d7-1277-4b80-8913-5293a5e3ac98)
![12](https://github.com/PrestaShop/PrestaShop/assets/653230/ad44f889-2853-4604-954e-c76c409e1dcd)

only emaiils associated to standard products are sent

After some tests this problem is present only if the new product page style is active

bye

### Steps to reproduce

1. go to a product with combinations
2. choose a combination and set it to 0
3. go to its product page, select the combination with quantity to zero
4. set your email e submit to get a reminder
5. return to the product configuration
6. set 10 to that combination
7. look if you get the email

you can repeat the same steps for a standard product and you will see that you get it, instead on the previous test not

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

**Comment by Maofree** [comment]
after some tests I can confirm that there are more then one error with is_product_attribute

- the condition at line 718 doesn't  allow to move forward
`if ($result && $this->customer_qty && $quantity >= $result['minimal_quantity']) {`

- inside sendCustomerAlert the function getCustomers has problems, it doesn't give data
- deleteAlert doesn't remove the email data in the table ps_mailalert_customer_oos

I tested getCustomers from the main php and I got the correct data about customer but inside sendCustomerAlert no

- I use a wrong code to get an error and see where is the problem

`        $customers = [];
        $customers[] = [
            'id_customer' => 0,
            'customer_email' => 'ssss@sss.ss',
            'id_shop' => 1,
            'id_lang' => 2
        ];`

with this array the module sends the email but not remove the customer data from its table

I hope I have given you some information to help you correct this error

![2](https://github.com/PrestaShop/PrestaShop/assets/653230/b8c30b27-0c2b-4c44-917a-542a5686b48c)
![3](https://github.com/PrestaShop/PrestaShop/assets/653230/d54eb628-0e7e-4728-9628-270cd006ee09)
![4](https://github.com/PrestaShop/PrestaShop/assets/653230/5ed2405d-b7e8-4552-8552-b27ce2e5b5c7)
![5](https://github.com/PrestaShop/PrestaShop/assets/653230/1fa6f247-f4c5-4da6-b3d4-95fd031e4e2a)
![6](https://github.com/PrestaShop/PrestaShop/assets/653230/58f8ec12-b604-499e-9db0-11fcbeaee1de)

**Comment by maofree** [comment]
this problem is present only if it is active the new product page style

**Comment by Maofree** [comment]
done other tests
found the error, inside hookActionUpdateQuantity the problem is due from

`$id_product_attribute = (int) $params['id_product_attribute'];`

with the new product page style, this value $params['id_product_attribute']; is null o zero, even when the product has combinations, this is why the rest of the code doesn't work

I think this problem is not present only for hookActionUpdateQuantity

Just a suggestion, this line
MailAlert::sendCustomerAlert((int) $product->id, (int) $params['id_product_attribute']);
should be
MailAlert::sendCustomerAlert((int) $product->id, $id_product_attribute);

the problem about this error is not in the module but in the core file that pass $params['id_product_attribute']
so it is a bug of prestashop core and not of this module
Probably is present on other hooks managed by the product page

**Comment by AureRita** [comment]
Hi @maofree ,

Thank you for your report, I reproduce the issue with PrestaShop version 8.1.2, as you can see : 

[Untitled_ Oct 23, 2023 10_56 AM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/873c23e0-d7d6-4d2e-beda-e3f86b4b3cda)

 I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks
