### ISSUE TITLE
blockwishlist module not translated

### ISSUE THREAD

**Issue by c-t-24-7** [PrestaShop/PrestaShop#34359]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The module was installed new. Our onlineshop cara-tech-24.eu is changeable for 3 languages German, English, French.
Instead of choosing e.g. German the module stays all time in English.

![Bug_wishlist](https://github.com/PrestaShop/PrestaShop/assets/148694269/be8fac63-59f2-474c-8896-08d9d31365d3)

### Expected behavior

We would expect that the shop-langauge is adapted to the module language. 

### Steps to reproduce

1. Go to https://cara-tech-24.eu/de
2. Verify the langauge is different from English
3. scroll down to "Top-Produkte"
4. click on 1 of the heart-icons 
5. First message should apear that you have to sign in first ,which should be in German like "Bitte anmelden"

### PrestaShop version(s) where the bug happened

1.7.6.8

### PHP version(s) where the bug happened

7.2.34

### If your bug is related to a module, specify its name and its version

Wishlist Module v2.1.2

### Your company or customer's name goes here (if applicable).

cara-tech-24

**Comment by AureRita** [comment]
Hi @c-t-24-7 

Thank you for your report. We can't test on other website, we need to reproduce issue on a fresh install. Currently I can't reproduce your issue as you can see : 

[Untitled_ Oct 23, 2023 4_47 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/998253f4-fda0-4052-a800-fbcbd01e125f)

Did I miss something ? 
Did you do something on the translation directly in the module ? 

Waiting for your feedback

**Comment by c-t-24-7** [comment]
Hi AureRita
I see it well working with your example.
I did a fresh installation on our test shop - but same result.

Regarding your questions:
1) Perhaps thje reason is grounded in the different theme we are using?
2) We did nothing on the translation: We checked them and find them well fitting.

**Comment by florine2623** [comment]
Hello @c-t-24-7 ,

If you have an issue with your theme you should contact the developer of if directly.

You can also try to update your language from your BO > International > Translations > Update a language

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by c-t-24-7** [comment]
Hi,
it was indeed the prestashop team itself who advices to find the solution for this bug with GitHub.
We really do not believe to have a prob with the theme.

This hint was mentioned because of the idea that the wishlist may not link completely if not default theme is used.
