### ISSUE TITLE
Broken "See all the available features" link in README

### ISSUE THREAD

**Issue by lisenet** [PrestaShop/PrestaShop#34374]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Broken "[See all the available features](https://www.prestashop.com/en/online-store-builder)." link on the landing page:

https://www.prestashop.com/en/online-store-builder

which leads to an HTTP 404 "Page not found".

### Expected behavior

Working link provided.

### Steps to reproduce

Go to [See all the available features](https://www.prestashop.com/en/online-store-builder).

### PrestaShop version(s) where the bug happened

Latest

**Comment by matks** [comment]
Hello @lisenet I could not find the link "See all the available features" on https://prestashop.com can you verify?

**Comment by lisenet** [comment]
@matks https://github.com/PrestaShop/PrestaShop/blob/8.1.x/README.md?plain=1#L130

**Comment by matks** [comment]
Aaaaah I thought you were talking about https://prestashop.com/ 😄 but no you talk about the README

**Comment by lisenet** [comment]
Sorry, it was indeed for a broken link on the landing page of the repository.
