### ISSUE TITLE
Clicking the "add to cart" button while the product page is loading will lead you to cart page.

### ISSUE THREAD

**Issue by YUxiangLuo** [PrestaShop/PrestaShop#34388]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Clicking the "add to cart" button while the product page is loading will lead you to cart page.

### Expected behavior

do nothing or add current product to cart.

### Steps to reproduce

1. open browser, cleara all cache
2. open devtools and disable all cache to make the product page load slowly
3. open the hompage, click a product, while the product is loading, click "add to cart" quickly

### PrestaShop version(s) where the bug happened

1.7.8.10

### PHP version(s) where the bug happened

7.2.24

**Comment by florine2623** [comment]
Hello @YUxiangLuo ,

Is your issue similar to https://github.com/PrestaShop/PrestaShop/issues/15483 ?

**Comment by YUxiangLuo** [comment]
https://github.com/PrestaShop/PrestaShop/assets/24310210/c669ac26-d095-42c4-83ad-40649179694d

I am sure it appears on 1.7.X and 8.1.*

**Comment by YUxiangLuo** [comment]
> Hello @YUxiangLuo ,
> 
> Is your issue similar to #15483 ?

not really

**Comment by paulnoelcholot** [comment]
Hello @YUxiangLuo,

I reproduce the bug on 1.7.8.10 but not on 8.1.x. This version of Prestashop is no longer maintained, I invite you to upgrade your version of Prestashop.
