### ISSUE TITLE
Files incosistency on upgraded installs

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#34385]
### Describe the bug and add attachments

During my upgrade explorations, I found following.

If you upgrade from 1.7.6.9 to 8.1.2 ➡️

**Following files are missing** ➡️
vendor/composer/installers/phpstan.neon.dist
vendor/composer/installers/src/Composer/Installers/DframeInstaller.php
vendor/composer/installers/src/Composer/Installers/KnownInstaller.php
vendor/composer/installers/src/Composer/Installers/MantisBTInstaller.php
vendor/composer/installers/src/Composer/Installers/MiaoxingInstaller.php
vendor/composer/installers/src/Composer/Installers/PantheonInstaller.php
vendor/composer/installers/src/Composer/Installers/ProcessWireInstaller.php
vendor/composer/installers/src/Composer/Installers/Redaxo5Installer.php
vendor/composer/installers/src/Composer/Installers/StarbugInstaller.php
vendor/composer/installers/src/Composer/Installers/SyliusInstaller.php
vendor/composer/installers/src/Composer/Installers/TaoInstaller.php
vendor/composer/installers/src/Composer/Installers/TastyIgniterInstaller.php
vendor/composer/installers/src/Composer/Installers/WinterInstaller.php

**Following files are not updated** ➡️
vendor/composer/installers/src/Composer/Installers/DrupalInstaller.php
vendor/composer/installers/src/Composer/Installers/CockpitInstaller.php
vendor/composer/installers/src/Composer/Installers/Plugin.php
vendor/composer/installers/src/Composer/Installers/OctoberInstaller.php
vendor/composer/installers/src/Composer/Installers/MoodleInstaller.php
vendor/composer/installers/src/Composer/Installers/BaseInstaller.php
vendor/composer/installers/src/Composer/Installers/CakePHPInstaller.php
vendor/composer/installers/src/Composer/Installers/MauticInstaller.php
vendor/composer/installers/src/Composer/Installers/OxidInstaller.php
vendor/composer/installers/src/Composer/Installers/WHMCSInstaller.php
vendor/composer/installers/src/Composer/Installers/Installer.php
vendor/composer/installers/src/Composer/Installers/SyDESInstaller.php
vendor/composer/installers/src/Composer/Installers/MicroweberInstaller.php

**Following files are not deleted** ➡️
controllers/admin/AdminAddressesController.php
controllers/admin/AdminAttachmentsController.php
controllers/admin/AdminAttributeGeneratorController.php
controllers/admin/AdminCmsCategoriesController.php
controllers/admin/AdminCmsContentController.php
controllers/admin/AdminCmsController.php
controllers/admin/AdminManufacturersController.php
controllers/admin/AdminOrderMessageController.php
controllers/admin/AdminOrdersController.php
controllers/admin/AdminOutstandingController.php
controllers/admin/AdminPatternsController.php
controllers/admin/AdminPreferencesController.php
controllers/admin/AdminReferrersController.php
controllers/admin/AdminSearchEnginesController.php
controllers/admin/AdminSlipController.php
controllers/admin/AdminTrackingController.php
controllers/admin/AdminZonesController.php
js/admin/orders.js
js/admin-categories-tree.js
src/PrestaShopBundle/Resources/config/routing/admin/improve/modules/addons.yml

@PrestaShop/qa-functional Guys could you please try the upgrade on your end and check if you get the same results? I want to know if it's a random issue or some code error.

### Steps to reproduce

1. Install 1.7.6.9.
2. Upgrade to 8.1.2 using autoupgrade.
3. Check if you get same situation as me.

### PrestaShop version(s) where the bug happened

1.7.6.9 to 8.1.2

### PHP version(s) where the bug happened

7.3, Linux server

**Comment by matks** [comment]
@Hlavtox which "channel" did you use when performing the upgrade?

**Comment by Hlavtox** [comment]
@matks Major version, standard automatic upgrade. (No local zip or things like this.)

![Snímek obrazovky 2023-10-25 182402](https://github.com/PrestaShop/PrestaShop/assets/6097524/8c118d0c-49b0-41dc-8012-ef16d37ef65f)

**Comment by AureRita** [comment]
Hi @Hlavtox ,

Thank you for your report, I reproduce the issue with PrestaShop version 1.7.6.9 to 8.1.2, as you can see : 

[Untitled_ Oct 27, 2023 11_33 AM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/05c9bcd1-8ba7-47de-9a36-94d1ab4e14ce)

 I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved.

I checked all files you mentionned and I've the same result 

Thanks

**Comment by Hlavtox** [comment]
Updated the list with some more files. Very weird that all of those files that were not upgraded have "install" in their path.
