### ISSUE TITLE
Cant find the full open api spec for PrestaShop

### ISSUE THREAD

**Issue by hackS3c101** [PrestaShop/PrestaShop#34386]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Is still an updated OpenAPI spec (aka Swagger) for API integration?
Could not find anywhere in the docs
Thanks 

### Steps to reproduce

Could not find anywhere

### PrestaShop version(s) where the bug happened

*

**Comment by florine2623** [comment]
ping @matks and @PrestaShop/prestashop-core-developers 
Are you aware of this option ?
