### ISSUE TITLE
New product page "add category" window empty in some stores , ok in other stores.

### ISSUE THREAD

**Issue by Simchev38** [PrestaShop/PrestaShop#34384]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello 

I have a strange behavior in 8.1.2.

My shop is in multi-store mode , it contains 3 enabled stores.

If I enable the "new product page" feature, when I click on the "Add category" button in the product page , it opens a popup window to manage the product categories, but : 

- In one of my stores, the category list contains all the categories associated to the store, and the category search works properly.
- in the other two stores, the category list is empty , and the search bar show no results

All the stores have some categories registered.

If I disable the "new product page" feature, on the "old" product page the categories lists are displayed correctly for every stores.

### Expected behavior

I expect the "new product page"  product categories window to be filled correctly in every stores of my multistore shop.

### Steps to reproduce

1 Enable new product page 
2 Go to a product management page 
3 click on add categories button
4 in some stores the category list is filled, in some it is not

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1.24

**Comment by florine2623** [comment]
Hello @Simchev38 ,

You need to make sure the category are well shared for all of your stores.

<img width="1227" alt="Screenshot 2023-10-26 at 09 22 11" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/2e1e30bb-a4a6-4e88-9739-2d6907e7f4f0">

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by Simchev38** [comment]
Hi 

Thanks for your answer, but I guess you did not  see what I wrote , specially those parts  : 

`All the stores have some categories registered.`

`
If I disable the "new product page" feature, on the "old" product page the categories lists are displayed correctly for every stores.`

If the categories were not registered properly to the stores, it would not work in the "old" product page as well, but it does work correctly in the old product page, the problem occurs only in the new product page 


Could you please re-open the ticket ?   

Thanks
