### ISSUE TITLE
In Stock availability for variants shown in English even if the label setting is blank

### ISSUE THREAD

**Issue by ash-f** [PrestaShop/PrestaShop#34399]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In stock availability for variants is shown on the product page in English when it's not suppose to be shown. 

Prestashop 8.1.2
Hummingbird theme 0.1.6

### Expected behavior

When selecting a variants that's in stock, In Stock message should not be shown on the product page in English. 

### Steps to reproduce
Before do this, make sure that "Label of in-stock products" in Shop Parameters>Product Settings is blank in English.

1. Go to product page that has variants in English
2. Select a variants  that's in stock.
3. In Stock message is shown.

### PrestaShop version(s) where the bug happened

1.8.2

### PHP version(s) where the bug happened

8.1

**Comment by ash-f** [comment]
I guess English is not working rather than Japanese?

In Shop Parameters>Product Settings
Label of in-stock products is blank for both language, but it's shown only in English.
When It's blank, It should not be shown in English also.

I confirmed that Label of in-stock products is shown in Japanese by filling the setting.
If it's empty, It's not shown in Japanese.

**Comment by Hlavtox** [comment]
So you found out that it works as it should, or there is some issue you think?

The feature works as intended for what I know. :-)

**Comment by ash-f** [comment]
No, It turned out that it's not working as it should in English.
If "Label of in-stock products" is blank, In Stock message should not be shown regardless of languages.

**Comment by ash-f** [comment]
Revised the original post.

**Comment by AureRita** [comment]
Hi @ash-f 

Thank your for your report, I tried to reproduce you issue but currently I can't as you can see : 

[Untitled_ Oct 27, 2023 11_13 AM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/bf898c2a-b39a-42c6-8108-09c1b8024494)

Did I miss something ? 

Waiting for your feedback

**Comment by ash-f** [comment]
Not sure, but I have not modified the core/the modules/the theme code.

English:
the label field both blank & filled results "In Stock" message. 
![settings-en-blank](https://github.com/PrestaShop/PrestaShop/assets/5485032/a727c2bb-ac46-4f37-83c5-8f384dbdaf7f)
![settings-en-filled](https://github.com/PrestaShop/PrestaShop/assets/5485032/09cf3309-971f-4523-8b30-44067cec938a)
![product-page-en](https://github.com/PrestaShop/PrestaShop/assets/5485032/e232bf35-780e-4297-b6a6-37039aeb45cb)

Japanese:
Leave the label blank hides the message.
![settings-ja-blank](https://github.com/PrestaShop/PrestaShop/assets/5485032/8009fdb9-3501-4296-992a-bda333cec9e0)
![product-page-ja](https://github.com/PrestaShop/PrestaShop/assets/5485032/ed00b1f8-b528-4304-be2c-3cd3b4b66473)

Language setup:
Could the language setup be related...?
![Languages](https://github.com/PrestaShop/PrestaShop/assets/5485032/83a8a710-3240-4134-9b23-446a8ea8dd40)

**Comment by ash-f** [comment]
This does not happen with a product that does not have variants.

**Comment by Hlavtox** [comment]
@ash-f Please, provide these screenshots from ALL languages:
- Given product availability labels.
- Given combination availability.
- BO > Shop settings > Product settings labels.

**Comment by ash-f** [comment]
Both English and Japanese now ignore label settings for some reason.

This is an example of combination.
![product-combination](https://github.com/PrestaShop/PrestaShop/assets/5485032/2afdbd32-fcbe-44df-8bc6-d85798523e16)

English
![EN-label-settings](https://github.com/PrestaShop/PrestaShop/assets/5485032/865f8037-dd08-49a5-9b01-05b9f235574d)
![EN-IN-STOCK](https://github.com/PrestaShop/PrestaShop/assets/5485032/7adcf191-3773-435a-8471-f8ad946b3dc8)
![EN-OOS ](https://github.com/PrestaShop/PrestaShop/assets/5485032/881cc3e1-aa71-46d7-9659-7262b2a29297)

Japanese
![JA-lable-settings](https://github.com/PrestaShop/PrestaShop/assets/5485032/414c026e-e7b9-486e-a18c-b5b9d1ee7715)
![JA-IN-STOCK](https://github.com/PrestaShop/PrestaShop/assets/5485032/9c5469c8-63ac-4a56-985e-15233a82b96e)
![JA-OOS](https://github.com/PrestaShop/PrestaShop/assets/5485032/c6957a1a-1762-41cc-a2fd-ba9359ec4c6a)

When the label setting is blank, its message on the product page should not be displayed  in Prestashop's manner from previous versions.

**Comment by Hlavtox** [comment]
@ash-f Please read what I am writing, again:
- SEND LABELS SET TO COMBINATION.
- SEND LABELS SET TO PRODUCT.

**Comment by AureRita** [comment]
Hi @ash-f 

Thank you for your details but currently we need more information, as Hlavtox ask, you had maybe change the parameters, can you share to us there data ? you can see them right here : 

[Untitled_ Nov 6, 2023 3_18 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/9ecccfc1-6516-40a5-8533-59e2c23dbc06)

Waiting for your feedback

**Comment by ash-f** [comment]
Sorry, I did not know that each combination have label setting since I just upgraded from 1.6.
They are blank.
![product label ja](https://github.com/PrestaShop/PrestaShop/assets/5485032/1a6e792d-8930-48f3-85e5-bd6dc924e294)
![product label en](https://github.com/PrestaShop/PrestaShop/assets/5485032/667febac-774b-4fd2-824e-3d484dc874b1)
![combination label ja](https://github.com/PrestaShop/PrestaShop/assets/5485032/d311730f-76cb-433b-9ec3-22aee8c0f90e)
![combination label en](https://github.com/PrestaShop/PrestaShop/assets/5485032/30e65b51-a9c2-428d-abef-b91b99ebd9d8)

I  checked all combination and there are the same setting - blank.

**Comment by ash-f** [comment]
I noticed another thing.
When the all combinations are the same status, the label will be shown properly.

**Comment by florine2623** [comment]
Hello @ash-f ,

The config seems fine on your side. But I can't reproduce your issue either.

I suggest contacting the support directly, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
