### ISSUE TITLE
Bad links to some resources under symfony layout FF

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#34392]
### Describe the bug and add attachments

When you enable symfony layout, some resources have bad URLs.

Given your test shop is on `http://localhost/dev/`, you get following:

```
<script src="/js/admin.js"></script>
<script src="/js/tools.js"></script>
<script src="/js/jquery/plugins/fancybox/jquery.fancybox.js"></script>
<script src="/js/jquery/plugins/chosen/jquery.chosen.js"></script>
<link rel="stylesheet" href="/js/jquery/plugins/fancybox/jquery.fancybox.css" media="all">
<link rel="stylesheet" href="/js/jquery/plugins/chosen/jquery.chosen.css" media="all">
```

![Snímek obrazovky 2023-10-26 100658](https://github.com/PrestaShop/PrestaShop/assets/6097524/78874612-a803-4e9e-bc78-527880b9f366)

### Steps to reproduce

1. Get develop.
2. Enable symfony layout feature flag.
3. Inspect source code in browser.

### PrestaShop version(s) where the bug happened

develop

**Comment by Hlavtox** [comment]
Ping @M0rgan01 ;-)

**Comment by florine2623** [comment]
Hello @Hlavtox ,

I have enabled the symfony layout feature.
But I can't find those URLs in view-source option in browser.

**Comment by M0rgan01** [comment]
@Hlavtox Thank you for the feedback, I will propose a PR in a few moments
