### ISSUE TITLE
State selectors are not working

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#34393]
### Describe the bug and add attachments

Somebody deleted `AdminStatesController` here https://github.com/PrestaShop/PrestaShop/pull/29510 and forgot to migrate things that depend on it. By default, `United states` should give you a state list in these places:

- `BO > Stores > Edit store` - state input not working, doesn't load any states.
- `BO > International > Tax rules > Edit tax rule > Add new tax` - state input not working, doesn't load any states.

If you hit F12 and open network tab, when you select `United states`, it loads this URL:
http://localhost/dev/admin-dev/index.php?ajax=1&tab=AdminStates&token=xxx&action=states&id_country=21&id_state=&empty_value=All&_=1698309238594

Which returns nothing (you can see that on the response tab):
```
<div class="alert alert-danger">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
    Page not found
  </div>
```

### PrestaShop version(s) where the bug happened

develop

**Comment by florine2623** [comment]
Hello @Hlavtox ,

I reproduce the issue with PrestaShop version develop, I'll add this to the backlog so it can be fixed.

https://github.com/PrestaShop/PrestaShop/assets/16019289/8e550b11-b83f-4dc3-8db6-b6d17f655490


Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Hlavtox** [comment]
@Progi1984 Could you fix this? :-)

**Comment by Progi1984** [comment]
@Hlavtox Sorry, no. I'm focus on UI tests.

**Comment by Hlavtox** [comment]
@Progi1984 Didn't expect any other answer. 👍

**Comment by Hlavtox** [comment]
This is fixed, the page calls a new migrated endpoint.
