### ISSUE TITLE
Email settings: SMTP password can NOT be saved, it's always blank.

### ISSUE THREAD

**Issue by YUxiangLuo** [PrestaShop/PrestaShop#34409]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I entered the smtp password then click "save" button, it's still blank.
Both 1.7.8.10 and 8.1.2 have this problem.

https://github.com/PrestaShop/PrestaShop/assets/24310210/a498ca48-72f6-4949-a588-9736eaaaa5d1

### Steps to reproduce

1. go to email settings
2. edit the smtp server fields and save

### PrestaShop version(s) where the bug happened

1.7.8.10, 8.1.2

### PHP version(s) where the bug happened

7.2, 8.0

**Comment by alisamie97** [comment]
@YUxiangLuo 
You can check the database to make sure it's not saving
1. Run this query before update  `SELECT c.value FROM presta_configuration c WHERE c.name LIKE 'PS_MAIL_PASSWD';`
2. Update the password
3. Run the query again and compare passwords. 

I guess only for security reasons it is not rendered in the form but it is actually saved in the database.

**Comment by YUxiangLuo** [comment]
@alisamie97 
Thank you, it exists in db.
