### ISSUE TITLE
New product page "add category" window empty, OK in old product page

### ISSUE THREAD

**Issue by Simchev38** [PrestaShop/PrestaShop#34416]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello

I have a strange behavior in 8.1.2.

My shop is in multi-store mode , it contains 3 enabled stores.

If I enable the "new product page" feature, when I click on the "Add category" button in the product page , it opens a popup window to manage the product categories, but :

In one of my stores, the category list contains all the categories associated to the store, and the category search works properly.
in the other two stores, the category list is empty , and the search bar show no results
All the stores have some categories registered.

If I disable the "new product page" feature, on the "old" product page the categories lists are displayed correctly for every stores.

I previously opened an other ticket for this bug https://github.com/PrestaShop/PrestaShop/issues/34384 , but it has been closed and not reopened despite my request, the person who closed it said I had to register some categories to the other shops ....  but : 

`All the stores have some categories registered.
`
` If I disable the "new product page" feature, on the "old" product page the categories lists are displayed correctly for every stores.`

If the categories were not registered properly to the stores, it would not work in the "old" product page as well, but it does work correctly in the old product page, the problem occurs only in the new product page.

So it cannot be a problm of categories not registered to the store I guess.

Thanks 

### Expected behavior

I expect the "new product page" product categories window to be filled correctly in every stores of my multistore shop.

### Steps to reproduce

1 Enable new product page
2 Go to a product management page
3 click on add categories button
4 in some stores the category list is filled, in some it is not

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1.24

**Comment by AureRita** [comment]
Hi @Simchev38 

Thank you for your report, Despite my effort, I can't reproduce your issue as you can see : 

[Untitled_ Oct 31 2023 2_57 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/435b40cd-ddfb-442b-aced-bf65879e5034)

Did I miss something ? 

Waiting for your feedback

**Comment by Simchev38** [comment]
No that is it, I checked and I have the issue when it's a new product or an existing one.

Are there "new" database JOIN , or maybe categories filtering in the new product page  that are not in the old one ? and taht could explain that it works properly in the old product page ?

**Comment by florine2623** [comment]
You need to add the categories to the product/shop that you want to : 

https://github.com/PrestaShop/PrestaShop/assets/16019289/09aaf3b9-f1e4-4796-9d35-07f91bf06676

**Comment by Simchev38** [comment]
Hello 

I'm sorry but it is the second ticket where you answer me that I have to register categories to the shop or product, despite me writing in the bug description that it is already the case,  am I missing something ?

-There are already categories registered to the shops or products 

- It is working perfectly with the old product page (I can see the categories lists ), the problem only occurs in the new product page, and only in 2 shops out of 3

I attached a video , hoping it would explain better the issue.

In the first part of the vidéo, it is the "old" product page, we can see that categories list is populated for the three shops, and that the category search returns results when I type "vo"

In the second part of the video, I enabled new product page, we can see in the first two shops that the categories list is empty, and the category search returns no results when I type "vo".   
Strangely, for the third shop it works as expected, the category list is populated and the search returns results.
[

https://github.com/PrestaShop/PrestaShop/assets/102355874/4311e2b5-e7c8-4a74-975f-6f5ce47d53ca

](url)

I checked the network monitor, and the request to get the category tree when we open the categories popu returns empty results for the two shops that are not working as expected, the request returns results for the shop that is working
https://url.fr/adminfolder/index.php/sell/catalog/categories/tree?_token=uM10XQykqfILpk0FOZQgLJU49AJbxmf-7ePy9ksUjlQ

**Comment by florine2623** [comment]
Please change your admin folder for security reasons. This is a public space.

I tested with new product page and old product page. I do not have any issues regarding the share of categories between shops.

If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
