### ISSUE TITLE
Search bar not accepting letters a and p (small case)

### ISSUE THREAD

**Issue by yorgocom70** [PrestaShop/PrestaShop#34412]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

when searching for a product in the search bar, the letters a and p cannot be typed! If I copy paste them it works but i cannot type the letters. If I use capslock, I can enter the letters. 

### Expected behavior

search bar should take any letter that is typed by keyboard (standard english keyboard)

### Steps to reproduce

1- in the shop view, go to search bar
2- type the name of a product you wish to search for
3- if the name of the product contains letter a or p the letters will not be shown on the bar

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

7.2.24

### If your bug is related to a module, specify its name and its version

search bar 2.1.3

### Your company or customer's name goes here (if applicable).

Patricia

**Comment by AureRita** [comment]
Hi @yorgocom70  ,

Thank you for your report, despite my efforts, i'm not able to reproduce your issue with the provided information, as you can see : 

[Untitled_ Oct 31, 2023 2_23 PM (2).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/2ca1ebc5-1775-45e5-a322-cd306e03da34)

Did I miss something ? 

Waiting for your feedback

**Comment by yorgocom70** [comment]
Thank you for your feedback. This is weird as we are getting this on some machines and not on all. browsers used: edge, chrome. 
now for instance I am getting two A and two P whenever i type a or p!!! 
[Ishoprural - Google Chrome 2023-11-02 10-59-05.webm](https://github.com/PrestaShop/PrestaShop/assets/136168072/8b0aec11-4151-47fe-95bb-f61751f2572e)

**Comment by florine2623** [comment]
Hello @yorgocom70 ,

I can't reproduce your issue either.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by matks** [comment]
@yorgocom70 There is nothing in the code that is doing something specific for a or p so it is probably something on your side 🤔 . Try with the computer of a friend? Try with a different keyboard? This will allow you to find out what exactly is causing this
