### ISSUE TITLE
Problem linking account with Prestashop Account Module

### ISSUE THREAD

**Issue by robergh** [PrestaShop/PrestaShop#34425]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I try to link the shop decostyl.es through prestashop accounts module I get the error  "The shop has not been verified. Reason : Error while getting domain as appears in the screen video below

This happens on 
Prestashop 1.7.8.10

there is no error that can be observed in logs at the moment of launching the process

### Expected behavior

I should be able to link the shop with prestashop accounts module

### Steps to reproduce

Try to link an account through prestashop modules-> manage modules- > Prestashop  account module, watch the video below

### PrestaShop version(s) where the bug happened

1.7.8.10

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

Prestashop Account 5.6.1

**Comment by florine2623** [comment]
Hello @robergh ,

Please contact the support center directly available in your Back-office.

Also, please change your admin space name. This is a public space.
