### ISSUE TITLE
Authorization Server : Error with the "Regenerate client secret" link : No route found

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#34421]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Error with the "Regenerate client secret" link : No route found for "GET https://domain.tld/admin-dev/index.php/configure/advanced/authorization-server/api-accesses/2/regenerate-secret": Method Not Allowed (Allow: POST)

### Expected behavior

No error found

### Steps to reproduce

1. Go to BO
2. Go to Advanced Parameters > New & experimental features
3. Enable "Authorization server"
4. Go to Advanced Parameters > Authorization Server
5. Add new API access 
![image](https://github.com/PrestaShop/PrestaShop/assets/1533248/25bab52a-ac31-44f6-a2bc-0da53868c7f9)
6. Go to "Generate client secret and save"
7. Right click on the link "Regenerate client secret" & Open in a new tab
![image](https://github.com/PrestaShop/PrestaShop/assets/1533248/251304ab-e995-45fa-9159-d2e96bdb54de)

### PrestaShop version(s) where the bug happened

9.0.x

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

**Comment by AureRita** [comment]
Hi @Progi1984 ,

I reproduce the issue with PrestaShop versiondevelop, as you can see : 

[Untitled_ Oct 31, 2023 3_38 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/8aedd840-a588-450c-9f43-5216058d7d4d)


 I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved.

Thanks

**Comment by Progi1984** [comment]
It's closed.

The old button was a link. It's a button now.
