### ISSUE TITLE
Module list in BO contains cached outdated module status

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#34437]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

More issues with caching of module list in backoffice. Check steps to reproduce.

### Expected behavior

This caching must be removed because this is just unmaintainable.

### Steps to reproduce

1. Go to module list, pick some module you like and check that it's enabled. 
2. Disable some module by calling `$module->disable();` from another module or some place in prestashop.
3. Go to module list, module still looks like it's enabled.

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
@Hlavtox ,

Can you further explain how to do step 2 ? ^^

**Comment by florine2623** [comment]
@Hlavtox ,

I can't reproduce your issue on PS 8.1.x :

https://github.com/PrestaShop/PrestaShop/assets/16019289/8e80a4bc-4e9d-483f-83e9-89e74c568e6f

Is there another way to reproduce it ?
THanks!

**Comment by paulnoelcholot** [comment]
Hello @Hlavtox,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Comment by Hlavtox** [comment]
@paulnoelcholot I will open so I don't forget, I will get back to you and provide a test module. 🙏🙏 Don't have access to pc right now.

**Comment by paulnoelcholot** [comment]
Hello @Hlavtox ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
