### ISSUE TITLE
The duplication of products doesn't allow apostrophes (') in the customization field

### ISSUE THREAD

**Issue by Lunyyx** [PrestaShop/PrestaShop#34442]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you try to duplicate a product with apostrophes ('), a bug is triggered (FAILED_DUPLICATE_CUSTOMIZATION_FIELDS) causing the duplicated product to be incomplete, and impossible to access.

The error is:

PrestaShop\PrestaShop\Core\Domain\Product\Exception\CannotDuplicateProductException code 90: Cannot bulk insert into table customization_field_lang failed

### Expected behavior

The duplication should work

### Steps to reproduce

1. Login to the Back-office
2. Open the Products page
3. Try to duplicate a product with a customization field with an apostrophe (') such as "Merci d'insérer votre personnalisation"
4. An error appear

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.2.7

**Comment by Hlavtox** [comment]
@Lunyyx Do you have `New product page` enabled in `Advanced parameters > New and experimental features`?

So the QA can reproduce the issue and verify your related PR as fast as possible. Thanks! :-)

**Comment by Lunyyx** [comment]
> @Lunyyx Do you have `New product page` enabled in `Advanced parameters > New and experimental features`?
> 
> So the QA can reproduce the issue and verify your related PR as fast as possible. Thanks! :-)

No, it's disabled
The attached PR is the fix that I found for this problem

**Comment by paulnoelcholot** [comment]
Hello @Lunyyx,

I reproduce the issue with PrestaShop version 8.1.x, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

[Products • the future (6).webm](https://github.com/PrestaShop/PrestaShop/assets/112863083/f4780d47-4492-424d-ae89-a4ab1e86fccd)

**Comment by MatShir** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/34441
