### ISSUE TITLE
Modules - upgrade 8.0.5 to 8.1.2 Using short namespace alias error

### ISSUE THREAD

**Issue by ytilotti** [PrestaShop/PrestaShop#34445]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On a upgrade from 8.0.5 to 8.1.2, I have this error:

```
In NotSupported.php line 31:
                                                                               
  Context: Using short namespace alias "Modulepsgdpr" by calling Doctrine\ORM  
  \Configuration::addEntityNamespace                                           
  Problem: Feature was deprecated in doctrine/persistence 2.x and is not supp  
  orted by installed doctrine/persistence:3.x                                  
  Solution: See the doctrine/deprecations logs for new alternative approaches  
  .    
```

### Steps to reproduce

no idea

### PrestaShop version(s) where the bug happened

8.1.2

### If your bug is related to a module, specify its name and its version

psgdpr

### Your company or customer's name goes here (if applicable).

Yneet

**Comment by paulnoelcholot** [comment]
Hello @ytilotti,

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template and provide clear and concise steps to reproduce the bug**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you

**Comment by ytilotti** [comment]
I just found why. A problem with the composer.lock version. I restaured this [version](https://github.com/PrestaShop/PrestaShop/blob/8.1.2/composer.lock) and it's fine!

The problem was here:
```php
#in appAppKernelDevDebugContainer.php
$a->addEntityNamespace('Modulepsgdpr', 'PrestaShop\\Module\\Psgpr\\Entity');
$a->addEntityNamespace('ModulepsAccounts', 'PrestaShop\\Module\\PsAccounts\\Entity');
```
