### ISSUE TITLE
Very slow loading of admin product page due to product features

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#34455]
### Discussed in https://github.com/PrestaShop/PrestaShop/discussions/31782

<div type='discussions-op-text'>

<sup>Originally posted by **ioweb-gr** March 11, 2023</sup>
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

We have a website with fairly large products with combinations packed with features. Most of our products have over 60 features active (with more than 20 possible values  per feature)  and some have combinations of over 40 colors and 10 sizes and there are more than 40 images as well per product. 

### Expected behavior

Improvement of the performance by reducing the number of queries

### Steps to reproduce

1. Create a product with combinations of 40 colors and 10 sizes
2. Add 40+ images to the product
3. Add two languages
4. Create 60+ features with at least 20 feature values per feature
5. Set values to the product for all features 
6. Try to edit the product in the backend in any browser and watch it freeze. 

### Appendix 

When trying to edit the product in the backend we face extreme slowdown and browser freezing. 
It can take more than 5 minutes to give control to the user, until the interface becomes responsive and fully loaded. 

Microsoft edge profiler, reports loops of rendering layout which takes more than 2-3 seconds I'm assuming for each new feature it causes layout shift and re-render. 

Moreover, we profiled prestashop and noticed there are fairly large execution times just to load the form, apart from rendering it in the browser. 

e.g. a request like this 

![image](https://user-images.githubusercontent.com/20220341/224469093-37a00b1a-fdd5-40dd-868d-450b53fbc8ee.png)

is repeated 3 times with total execution of over 10 seconds to fetch the combinations with the timeline like this

![image](https://user-images.githubusercontent.com/20220341/224469119-f0ef1c03-ac19-4865-a9b3-5e1250196b6a.png)

Also the actual request to fetch the product in admin is taking more than 34 seconds

![image](https://user-images.githubusercontent.com/20220341/224469262-03440ae5-773d-4c89-9b46-647e30aa58d8.png)

With the timeline showing some very specific delays in evaluating twig templates for display

![image](https://user-images.githubusercontent.com/20220341/224469298-5652b474-28be-4936-a7a4-c8e74b5bbe17.png)
![image](https://user-images.githubusercontent.com/20220341/224469318-9d4ffe51-f8a0-4543-940e-b53ff602602c.png)

The server is a 12core dedicated server with 64G RAM and Nvme disk and the load is very low so we can exclude server performance 
![image](https://user-images.githubusercontent.com/20220341/224469364-8a8a7243-e24c-4d0c-83fe-5d4b81a0340c.png)

### PrestaShop version(s) where the bug happened

1.7.5.2

### PHP version(s) where the bug happened

7.2/7.3

### If your bug is related to a module, specify its name and its version

Prestashop Features</div>

**Comment by Hlavtox** [comment]
Recap

Issue is caused by `FeatureValueRepository::getFeatureValues`, where due to a bad join, it fetches values for all products this value is assigned to. 

https://github.com/PrestaShop/PrestaShop/blob/2f63163d221cbf1e9e17565c63f0dbbd1a3a288b/src/Adapter/Feature/Repository/FeatureValueRepository.php#L166

Resulting to thousands of records found, while the feature has only 10 values for example. On my shop with 4 thousand products, it found 7 thousand feature values.

Then of reach of this record it fetches localized values one by one of these 7 thousand.

https://github.com/PrestaShop/PrestaShop/blob/2f63163d221cbf1e9e17565c63f0dbbd1a3a288b/src/Adapter/Feature/Repository/FeatureValueRepository.php#L176

It can be done with one database query. Also, a cache can be added so when there are multiple SAME features assigned to the product, their values are loaded only once.

```
        // Build cache key
        $cache_key = 'getAllValuesForFeature';
        if (isset($filters['id_feature'])) {
            $cache_key .= '_id_feature_' . (int) $filters['id_feature'];
        }
        if (isset($filters['custom'])) {
            $cache_key .= '_custom_' . (int) $filters['custom'];
        }
        
        if (isset($this->featureValueCache[$cache_key])) {
            return $this->featureValueCache[$cache_key];
        }

        $qb = $this->connection->createQueryBuilder();
        $qb->select('fvl.*')
            ->from($this->dbPrefix . 'feature_value_lang', 'fvl')
            ->leftJoin('fvl', $this->dbPrefix . 'feature_value', 'fv', 'fv.id_feature_value = fvl.id_feature_value')
            ->orderBy('fvl.value', 'ASC')
        ;

        // Assign filters if provided
        if (isset($filters['id_feature'])) {
            $qb
                ->andWhere('fv.id_feature = :id_feature')
                ->setParameter('id_feature', (int) $filters['id_feature'])
            ;
        }
        if (isset($filters['custom'])) {
            $qb
                ->andWhere('fv.custom = :custom')
                ->setParameter('custom', (int) $filters['custom'])
            ;
        }

        // Prepare array with localized values
        $localizedFeatureValues = [];
        foreach ($qb->execute()->fetchAll() as $featureValue) {
            $localizedFeatureValues[(int) $featureValue['id_feature_value']][(int) $featureValue['id_lang']] = $featureValue['value'];
        }

        // Cache it
        $this->featureValueCache[$cache_key] = $localizedFeatureValues;

        return $localizedFeatureValues;
```

**Comment by vipdpcolor** [comment]
We had a similar issue on products with more than 200 combinations, updating to 8.1.2 and using the new experimental product page did the trick. Saving times went from a couple minutes to a couple seconds.

**Comment by venditdevs** [comment]
> It can be done with one database query. Also, a cache can be added so when there are multiple SAME features assigned to the product, their values are loaded only once.

We have the similair problem with around a total +4 million features in ps_feature_product, but version 8.1.2 in combination with the experimental product page doesn't provide the solution.

**Comment by ChronoBrake** [comment]
please repair it. WTF

**Comment by OrionCodeDev** [comment]
It's only affected on new experimental product page. Old one working fine. Repair it pls
