### ISSUE TITLE
FO: Slow loading of product page with many combinations

### ISSUE THREAD

**Issue by Shoprunners** [PrestaShop/PrestaShop#34453]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When we have many variants, like 500 or more, the site loading is pretty slow.

### Expected behavior

The site speed should not be affected massively

### Steps to reproduce

1. Create a product with 4 different attribute groups and a certain amount of attributes and create > 500 variants
2. Create a product with only few combinations
3. Go to front office and load both products and compare times in profiler. Compare the initContent method times.

Those will be dramatically different

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

**Comment by Shoprunners** [comment]
I will give the way to improve the performance here, because I found a very simple way without breaking any compatibilities. Unfortunately I can't find the time to do provide the whole code in a merge request 

1. Find ProductController and assignAttributesCombinations method

the little row
$val = str_replace(Configuration::get('PS_ATTRIBUTE_ANCHOR_SEPARATOR'), '_', Tools::str2url(str_replace([',', '.'], '-', $val)));

is the problem.
Why? Tools::str2url creates for each call a new StringModifier which create a new Transliterator ...

Solution: reuse the instance. 

1: in Tools class change to
```
public static function str2url($str,$string_modifier = null)
    {
if(null == $string_modifier) {
 $string_modifier = new StringModifier();
}
 return ($string_modifier->str2url((string) $str);
    }
```

original was:

```
  public static function str2url($str)
    {
        return (new StringModifier())->str2url((string) $str);
    }
```
2. create the stringModifier in the assignAttributesCombinations method and reuse it

` ....if (is_array($attributes_combinations) && count($attributes_combinations)) {
$string_modifier = new StringModifier();
foreach ($attributes_combinations as &$ac) {
  foreach ($ac as &$val) {					
    $val = str_replace(Configuration::get('PS_ATTRIBUTE_ANCHOR_SEPARATOR'), '_', $this->str2url($string_modifier,str_replace([',', '.'], '-', $val)));
                }
            }
        } else {
            $attributes_combinations = [];
        }`



performance improved by 400ms in my case

**Comment by florine2623** [comment]
Hello @PrestaEdit ,

There's indeed a difference in loading the page with a lot of combinations.

With 672 combinations :
<img width="462" alt="Screenshot 2023-11-03 at 10 14 33" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/4c9e6499-adcb-4494-8d74-7db8d2e6c5a5">

With 2 combinations :
<img width="455" alt="Screenshot 2023-11-03 at 10 14 41" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/b3f8f205-6fb4-449a-bca7-7d2a4a6d9880">

Without combinations :
<img width="453" alt="Screenshot 2023-11-03 at 10 15 07" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/4c904931-b8ad-4cc2-8c7e-560624c4ed52">

Although, the page is not loading that slowly.
What is your initContent time ?

**Comment by Shoprunners** [comment]
So without the reuse of StringModifier:
![image](https://github.com/PrestaShop/PrestaShop/assets/4729231/7a73598b-4e91-43cb-90ce-dcf053fa5f8f)


and with just reusing the StringModifier:
![image](https://github.com/PrestaShop/PrestaShop/assets/4729231/2aa35799-f8d2-4a24-91d3-ccf2d237ce79)

Just two lines changed, 2640 variants  seperated in 3 groups.

So from 12871ms! down to 1541ms.

**Comment by Shoprunners** [comment]
If I look at the code again: StringModifier instance is used in the Tools class several times. So you should do make this a static var / singleton in Tools class and reuse it. This would minimize the changes.

The whole change was made with commit 

https://github.com/PrestaShop/PrestaShop/commit/0c620929febcb834c2bd1001eac9677dfb982bc0

**Comment by florine2623** [comment]
ping @PrestaShop/prestashop-core-developers 
WDYT ?

Although, I can't reproduce the issue, this might help the performance of shops.

**Comment by Shoprunners** [comment]
I created a PR....
https://github.com/PrestaShop/PrestaShop/pull/34458

**Comment by M0rgan01** [comment]
This is a very good thing for performance.

**Comment by florine2623** [comment]
@PrestaShop/product-council can you put the label PM ✅ ? if it is ok for you

**Comment by Hlavtox** [comment]
Issue improved by https://github.com/PrestaShop/PrestaShop/pull/34458

**Comment by Prestaworks** [comment]
@Hlavtox there are still some issues here
The function tryToGetAvailableIdProductAttribute seems to be something that take lots of time to run if the feature to hide "out of stock" options is active. It's in the productController.

**Comment by MatShir** [comment]
@Prestaworks could you create a dedicated issue ? 🙏 
So we could have a look ;)
