### ISSUE TITLE
ps_mbo has problem - has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header'

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#34468]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
today I've upgraded a site to prestashop 8.1.2 with php 8.1 and I've a problem to install modules from ps_mbo
there is an ajax problem about

has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header'

![1](https://github.com/PrestaShop/PrestaShop/assets/653230/1984562f-be29-4aa2-bb58-04e8c65f0ef8)

the website is on a vps in Spain

this type of error is present only into this website, probably is due from hosting or vps configuration

### Steps to reproduce

1. I don't know how to reproduce this error

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_mbo

**Comment by Maofree** [comment]
now, I get the same error from a different website, after an upgrade to 8.1.2 to install a module from ps_mbo
in this case the hosting is different from the other one and it is netsons on share solution

![11](https://github.com/PrestaShop/PrestaShop/assets/653230/afa89cce-e1c0-47a1-bd80-80d322b5875c)

**Comment by kpodemski** [comment]
@maofree 

This is not the first time we're writing this, but please do not report issues regarding these modules in the open source space. You can contact team responsible for MBO using contact form on Addons Marketplace or[ PrestaShop Help Center](https://help-center.prestashop.com/en/contact)

**Comment by Maofree** [comment]
you're right, it's just that I see it as an essential module and instinctively come here when to report the error
