### ISSUE TITLE
Add compression for text resources (js, css, html)

### ISSUE THREAD

**Issue by elyesnaouar** [PrestaShop/PrestaShop#34479]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

**Motivation**: For best performance, it's necessary to combine all these techniques. The advantage of compression is that it not only reduces file size, but also reduces the time it takes to transmit compressed files over computer networks. 
**Reference** : https://www.php.net/manual/fr/filters.compression.php

### Steps to reproduce

create a shop using v8.1.2

### PrestaShop version(s) where the bug happened

8.1.2

**Comment by Hlavtox** [comment]
Already implemented, we minify all assets and gzip everything if the server supports it.

**Comment by elyesnaouar** [comment]
implemented from which version ?

**Comment by Hlavtox** [comment]
Asset combining and minification is there since 1.6 and maybe sooner. GZIP support depends on your server.

**Comment by elyesnaouar** [comment]
Asset combining includes combining several CSS files into a single file ?

**Comment by Hlavtox** [comment]
@elyesnaouar Yes, enable it in Backoffice > Advanced parameters > Performance

**Comment by AureRita** [comment]
Hi @elyesnaouar 

Thank you for your report, does the answer of @Hlavtox Help you ? Do you see anything else ? 

Can I close your issue ? 

Waiting for your feedback

**Comment by elyesnaouar** [comment]
I'm not pretty sure that's ressources compression is already implemented. 
You can use the LightHouse tool of chrome to check as indicated on capture in attachment.

<img width="444" alt="compression txt ressources" src="https://github.com/PrestaShop/PrestaShop/assets/122271944/08576fcd-9bb9-4b1b-9772-298c55dba354">

**Comment by paulnoelcholot** [comment]
@Hlavtox, what do you think about that?

**Comment by Hlavtox** [comment]
As I said, @elyesnaouar must update his Prestashop and server configuration. :-)

![Snímek obrazovky 2023-11-07 162011](https://github.com/PrestaShop/PrestaShop/assets/6097524/82ff7883-fbf3-4474-ae7f-ee6c21986194)

**Comment by elyesnaouar** [comment]
@Hlavtox After configuring parameters as recomanded, i confirm i have all asset combining and minification as you show on on capture (by enabling in Backoffice > Advanced parameters > Performance).
<img width="389" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/122271944/b31cd267-a000-4937-bd7b-157bf7de7919">

I refer back to you to ask the load of all JavaScripts files are in synchronous or asychronous mode ?

**Comment by AureRita** [comment]
@Hlavtox 

> @Hlavtox After configuring parameters as recomanded, i confirm i have all asset combining and minification as you show on on capture (by enabling in Backoffice > Advanced parameters > Performance). <img alt="image" width="389" src="https://user-images.githubusercontent.com/122271944/281115962-b31cd267-a000-4937-bd7b-157bf7de7919.png">
> 
> I refer back to you to ask the load of all JavaScripts files are in synchronous or asychronous mode ?

**Comment by Hlavtox** [comment]
@elyesnaouar The loading depends on the way you include it in the front controller.

https://github.com/PrestaShop/PrestaShop/blob/dd7c14901c004b7b539cba28acc3f792b32f3dbb/classes/controller/FrontController.php#L1069

it then goes into 

https://github.com/PrestaShop/PrestaShop/blob/dd7c14901c004b7b539cba28acc3f792b32f3dbb/classes/assets/JavascriptManager.php#L59

and you can pass both defer and async. :-)
