### ISSUE TITLE
Total shipping cost is zero for some orders, even though carrier has cost for that weight range

### ISSUE THREAD

**Issue by rhariskumar3** [PrestaShop/PrestaShop#34488]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In PrestaShop, for some orders, the total shipping cost is zero, even when the carrier has a cost for that weight range. This issue has been observed on both old and new versions of PrestaShop, and there is no address mismatch in the cart_product table.
![cart_products](https://github.com/PrestaShop/PrestaShop/assets/26006601/afdae665-2b70-4fe5-abfe-48037686c2ce)
<img width="721" alt="Screenshot 2023-11-06 at 22 23 09" src="https://github.com/PrestaShop/PrestaShop/assets/26006601/c08ca519-a1e4-4d3f-b1a9-67094f2851f8">
<img width="1367" alt="Screenshot 2023-11-06 at 22 21 08" src="https://github.com/PrestaShop/PrestaShop/assets/26006601/b1d0efce-edda-4687-b949-c5d58453429e">
<img width="1480" alt="Screenshot 2023-11-06 at 22 21 56" src="https://github.com/PrestaShop/PrestaShop/assets/26006601/aeddbde6-1b39-45f7-bf9a-7661513a87ea">

### Expected behavior

The shipping cost should be calculated correctly for all orders, based on the weight of the products and the selected shipping carrier.

### Steps to reproduce

1. Add a product to the cart.
2. Go to checkout and select a shipping carrier.
3. The shipping cost should be calculated and displayed.
4. However, for some orders, the shipping cost will be zero, even though the carrier has a cost for that weight range.

### PrestaShop version(s) where the bug happened

1.7.8.10

### PHP version(s) where the bug happened

7.2.34

### Your company or customer's name goes here (if applicable).

Bazodo Enteprises

**Comment by paulnoelcholot** [comment]
Hello @rhariskumar3,

Do you have any idea what causes this problem to occur on one order rather than another?

Thanks for your feedback!

**Comment by rhariskumar3** [comment]
Hi @paulnoelcholot 
I tried to figure it out. But i can't able to find.

**Comment by paulnoelcholot** [comment]
@rhariskumar3, 
With the recent downsizing of our workforce, we are unable to investigate the issue. It is necessary that you provide us with steps to reproduce allowing us to reproduce the bug systematically.

Thank you for understanding

**Comment by rhariskumar3** [comment]
I will try to find the cause of the issue and let you know if I find anything.

**Comment by florine2623** [comment]
Hello,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
