### ISSUE TITLE
Order Confirmation : Switch language is broken

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#34483]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Order Confirmation : Switch language is broken

### Steps to reproduce

1. Install a shop in Language : English / Country : France
2. Connect in 
3. Order a product in John Doe (for example) : `pub@prestashop.com` - `123456789`
4. On the order confirmation page, switch the language

![image](https://github.com/PrestaShop/PrestaShop/assets/1533248/7e257ad1-e1d0-409d-b0f9-45879a3c74f2)

### PrestaShop version(s) where the bug happened

9.0.x

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

**Comment by AureRita** [comment]
Hi @Progi1984 ,

Thank you for your report, I reproduce the issue with PrestaShop version 9.0.0, as you can see : 

[Untitled_ Nov 6, 2023 3_03 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/62bc2e42-6a19-4c37-8940-801e412b812a)

 I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved.

Thanks

**Comment by Hlavtox** [comment]
Will be fixed by https://github.com/PrestaShop/PrestaShop/pull/34376
