### ISSUE TITLE
Total value of split orders mismatched, carrier name and shipping cost inaccurate for one of the split orders

### ISSUE THREAD

**Issue by rhariskumar3** [PrestaShop/PrestaShop#34489]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When splitting orders in PrestaShop, the total value of all orders may not match. Additionally, the carrier name and shipping cost may be inaccurate for one of the split orders.

<img width="1452" alt="#16467 PKUDLRODP" src="https://github.com/PrestaShop/PrestaShop/assets/26006601/996d3d86-c0c4-40c0-aeeb-3a21bd76a9a0">
<img width="1465" alt="#16466 PKUDLRODP" src="https://github.com/PrestaShop/PrestaShop/assets/26006601/d3b81d66-f3f7-4d00-b015-777619fd326a">

### Expected behavior

The total value of all split orders should match the total value of the original order. Additionally, the carrier name and shipping cost for each split order should be accurate.

### Steps to reproduce

Add products to the cart that have different shipping carriers assigned to them.
Go to checkout and split the order into multiple orders.
Observe the total value, carrier name, and shipping cost for each split order.

### PrestaShop version(s) where the bug happened

1.7.8.10

### PHP version(s) where the bug happened

7.2.34

### Your company or customer's name goes here (if applicable).

Bazodo Enteprises

**Comment by florine2623** [comment]
Hello @rhariskumar3 

Is your issue similar to https://github.com/PrestaShop/PrestaShop/issues/20409 ?

**Comment by rhariskumar3** [comment]
Hi @florine2623 

No, My issue is totally different from other one

**Comment by florine2623** [comment]
Hello @rhariskumar3 ,

The orders are split in order to get a delivery slip for each carrier. It is normal behavior.

The order has split into 2 different orders :
<img width="1171" alt="Screenshot 2023-11-08 at 17 34 26" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/7845a505-971f-47ec-80c0-dfac90cc6046">

Each of the order have their own product with their own carrier and shipping cost :
<img width="1215" alt="Screenshot 2023-11-08 at 17 35 39" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/b54c9ad2-34d0-43b2-97da-b8096d8cc934">
<img width="1221" alt="Screenshot 2023-11-08 at 17 36 18" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/3ad5421b-b02b-480c-830b-c5f9075214a0">

**Comment by rhariskumar3** [comment]
@florine2623 I hope you mistakenly closed thread. Could you please check attached screenshots in Bug.
1. Order Value is mismatch and Prestashop itself showing mismatch error
2. In First order, There is No carrier name, weight and price

**Comment by rhariskumar3** [comment]
@florine2623 
I noticed that the Customer side Carrier name is empty for Split Orders. I inspected the template, and found that the carrier ID in the delivery options list is formatted as (341,0). When the table tries to search for a carrier with this ID, it fails because the ID is not in the correct format.

<img width="1477" alt="Screenshot 2023-11-11 at 08 43 59" src="https://github.com/PrestaShop/PrestaShop/assets/26006601/cac1a8eb-287c-4152-b346-2dfb943726c5">
<img width="1237" alt="carrier" src="https://github.com/PrestaShop/PrestaShop/assets/26006601/88c01e6e-0bc2-4f86-a136-309a7582ebbc">

**Comment by shorrog** [comment]
I have exactly the same issue with Prestashop 8.1.1 PHP version  8.1.26. 
My experience is this has been around for years.
