### ISSUE TITLE
The API path doesn't follow the ADR 

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#34493]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The ADR : https://github.com/PrestaShop/ADR/pull/35 has been accepted

But some paths are in snake case `/api/cartRule/{apiAccessId}` 

### Steps to reproduce

N/A

### PrestaShop version(s) where the bug happened

9.0.x

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

**Comment by hibatallahAouadni** [comment]
@paulnoelcholot 👀  my eyes on you boy!
Boy you need to add the `WS `label ⚠️

**Comment by Progi1984** [comment]
@hibatallahAouadni No Need of the `WS` label. It's about the new `API` :wink:.

**Comment by hibatallahAouadni** [comment]
@Progi1984 I see! Thanks for your feedback but we need a category label for each issue 😉 
Sorry @paulnoelcholot but not too much 😁
