### ISSUE TITLE
Fatal error if I delete a reported comment from module productcomments BO page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#34512]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When user admin, on the productcomments module backoffice page, use the "Delete" button to delete a comment that has been reported as abusive, then after the page is refreshed a fatal error is thrown
```
PrestaShop\Module\ProductComment\Repository\ProductCommentRepository::delete(): Argument #1 ($entity) must be of type PrestaShop\Module\ProductComment\Entity\ProductComment, null given, called in /Users/AAA/www/prestashop/PrestaShop/modules/productcomments/productcomments.php on line 210
```

### Expected behavior

The "delete" button should successfully delete the comment and not display an error page

### Steps to reproduce

1. Install PrestaShop `develop` branch
2. Open a first tab, go to front-office, create a customer account. Then open a product Front-office page and review the product: you need to submit a comment about the product. The comment is submitted but must be approved by a shop admin.
3. Open a 2nd tab, you login on backoffice, go to module manager Backoffice page, then "configure" module "Product Comments"
4. On 2nd tab, approve the comment.
5. On 1st tab refresh the product page: now the comment can be seen.
6. On the 1st tab, use the "report abusive comment" flag icon to report the comment
7. Back on 2nd tab, on the productcomments module backoffice page you should see the reported comment
8. Click on "Delete" button next to reported comment
9. Refresh the page, see the fatal error

![Capture d’écran 2023-11-09 à 18 13 02](https://github.com/PrestaShop/PrestaShop/assets/3830050/da7722c1-7f61-4f0a-b8da-d1963016d5a2)

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.2

### If your bug is related to a module, specify its name and its version

productcomments 6.0.2

**Comment by matks** [comment]
Mmmm looks like the root cause is that I **refresh** at step 9

As the URL contains the parameter for the action, the module attempts to delete the comment again, and it fails because the comment was successfully deleted at step 8.

The URL is
```
admin-dev/index.php?controller=AdminModules&configure=productcomments&id_product_comment=3&deleteproductcomments&token=AAA
```

As you can see the parameters contain the action, so when you hit the refresh button it send the same request

I will submit a PR to mitigate the problem

**Comment by leemyongpakvn** [comment]
I guess we need an Exception for deleting a deleted comment and a Redirect after a comment deleted ;)

**Comment by florine2623** [comment]
Hello @matks ,

I reproduce the issue with PrestaShop version develop, I'll add this to the backlog so it can be fixed.


https://github.com/PrestaShop/PrestaShop/assets/16019289/f16d4e5d-302e-4c38-b332-a86fa8a52e55

When I refresh my page, I have the following exception :
<img width="1091" alt="Screenshot 2023-11-13 at 11 05 32" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/04d8c942-c684-47bd-af3f-f86352cf525d">


Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by matks** [comment]
I submitted the PR https://github.com/PrestaShop/productcomments/pull/190
