### ISSUE TITLE
Error 500 when clicking on Active Baskets or baskets

### ISSUE THREAD

**Issue by TheEnglishGartner** [PrestaShop/PrestaShop#34510]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,

I have recently upgraded my Prestashop to version 8.1.2 and also my theme Warehouse to the latest version 4.6.4 as well as the PHP to 8.1.

When I run in debug mode I get the below:

[PrestaShopException]
Invalid address #4742
at line 558 in file classes/Address.php

553.             // if an id_address has been specified retrieve the address
554.             if ($id_address) {
555.                 $address = new Address((int) $id_address);
556. 
557.                 if (!Validate::isLoadedObject($address)) {
558.                     throw new PrestaShopException('Invalid address #' . (int) $id_address);
559.                 }
560.             } elseif ($with_geoloc && isset($context->customer->geoloc_id_country)) {
561.                 $address = new Address();
562.                 $address->id_country = (int) $context->customer->geoloc_id_country;
563.                 $address->id_state = (int) $context->customer->id_state;
AddressCore::initialize - [line 3691 - classes/Product.php]
ProductCore::getPriceStatic - [line 1072 - classes/Cart.php]
CartCore->getCartPriceFromCatalog - [line 991 - classes/Cart.php]
CartCore->getCartPrices - [line 907 - classes/Cart.php]
CartCore->applyProductCalculations - [line 828 - classes/Cart.php]
CartCore->getProducts - [line 2127 - classes/Cart.php]
CartCore->getOrderTotal - [line 2038 - classes/Cart.php]
CartCore::getTotalCart - [line 928 - controllers/admin/AdminCartsController.php]
AdminCartsControllerCore::getOrderTotalUsingTaxCalculationMethod - [line 409 - classes/helper/HelperList.php]
HelperListCore->displayListContent - [line 233 - classes/helper/HelperList.php]
HelperListCore->generateList - [line 986 - controllers/admin/AdminCartsController.php]
AdminCartsControllerCore->renderList - [line 2252 - classes/controller/AdminController.php]
AdminControllerCore->initContent - [line 319 - classes/controller/Controller.php]
ControllerCore->run - [line 510 - classes/Dispatcher.php]
DispatcherCore->dispatch - [line 95 - admin/index.php]

![500 error in active baskets](https://github.com/PrestaShop/PrestaShop/assets/92990704/6eda67fb-bc56-4b53-be4e-d6194062b976)
![500 error ](https://github.com/PrestaShop/PrestaShop/assets/92990704/a22c4606-762f-40f4-9795-fdffccfd5bb1)

### Expected behavior

I expect that i will get the default list of active baskets as always in PS

### Steps to reproduce

1: Login to the backend
2: Click on Active Baskets 
3: Error 500 is present 

### PrestaShop version(s) where the bug happened

1.7.8.10 - 8.1.2

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

I think it could be related to the tools element in PRestashop but not sure 

### Your company or customer's name goes here (if applicable).

Den Engelske Gartner ApS

**Comment by AureRita** [comment]
Hi @TheEnglishGartner 

Thank you for your report, Despite my effort, I can't reproduce your issue, as you can see : 

[Untitled_ Nov 6, 2023 3_18 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/4626b140-f856-4cc6-b72a-07fc1fa44c06)

Did I miss something ? 

Can you try your update with the classic theme ? 

Waiting for your feedback

**Comment by Hlavtox** [comment]
@TheEnglishGartner I suggest checking what it tells you - the invalid address with ID 4742. :-)

**Comment by TheEnglishGartner** [comment]
Hi Hlavtox - which database table should I look in? thank you I didn't find an entyr for is in ps_address

**Comment by TheEnglishGartner** [comment]
Hi AureRita

As far as I can see you are in the products section - it is in the baskets. I will see if I can find the address in the db

Best,


Lasse

**Comment by TheEnglishGartner** [comment]
Hi Hlavtox,

Thank you I have solved it by the below

select * ps_cart where search id_address_delivery=4742 and then deleted this entry. 

Thank you very much :-)

**Comment by Hlavtox** [comment]
@TheEnglishGartner It's the ID you see in Customer > Adresses page, search for it and you will see that something is probably wrong.

The database table is ps_adress.

**Comment by LameuleFR** [comment]
Related to https://github.com/PrestaShop/PrestaShop/issues/12617
