### ISSUE TITLE
BO - Product Settings - Wording help text is confusing when I want to disable the "Add to cart" button

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#34519]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The help text message for the option `Display the "Add to cart" button when a product has attributes` is confusing.

<img width="945" alt="Screenshot 2023-11-10 at 15 31 30" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/cbd2d7b7-0343-45c5-9881-ba47bd7cb682">

It says : 
`Display or hide the "Add to basket" button on category pages for products that have attributes forcing customers to see product details.`

In our case, the behavior is the same in the Homepage or in the Category page.
If the option is disabled and the product has attributes, the cart button is hidden.

@Hlavtox  has proposed something like this :
`If your theme allows displaying "Add to basket" button on product lists, it won't be allowed for products with combinations. Customers will need to see product details.`

### Expected behavior

The help text message could be improved.

### Steps to reproduce

1. Install hummingbird theme
2. Go to BO > Shop Parameters > Products Settings
3. See the help text for the option “Display the “Add to cart” button when a product has attributes” :x:

### PrestaShop version(s) where the bug happened

8.1.x, develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

hummingbird

**Comment by Hlavtox** [comment]
@Julievrz Julie could you please check the proposed wording and make some adjustments if needed? :-)

**Comment by AureRita** [comment]
Hi @florine2623 

Thank you for your report, we'll see with the dedicated team if we have to change this help text. 

Thank you

**Comment by Julievrz** [comment]
"Some themes allow your customers to add a product to their cart directly from the product list. You may wish to deactivate this feature if the product has combinations, forcing your customers to check the product details and make their choice."

Hi @Hlavtox,
Thank you for your suggestion. You're right, the help text is not clear.
Your suggestion is clearer but I think we shouldn't say "it won't be allowed for products with combinations" in the help text, just in case the feature is set to yes. 

So here's my suggestion. Let me know what you think.

"Some themes allow your customers to add a product to their cart directly from the product list. You may want to deactivate this feature if a product has combinations, requiring your customers to check product details and make their choice." 

or 

"Some themes allow your customers to add a product to their cart directly from the product list. You may want to deactivate this feature if a product has combinations, requiring your customers to check product details and choose one of the options."

**Comment by Hlavtox** [comment]
@Julievrz Love this one 🚀 

`Some themes allow your customers to add a product to their cart directly from the product list. You may want to deactivate this feature if a product has combinations, requiring your customers to check product details and choose one of the options.`

**Comment by Julievrz** [comment]
Perfect then! 🚀 

@florine2623 I think we're ready to go.

**Comment by Julievrz** [comment]
And by the way, we could also edit the label:

Display the "Add to cart button" when a product has combinations

**Comment by Hlavtox** [comment]
@Julievrz done :-)

**Comment by Hlavtox** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/34563
