### ISSUE TITLE
Unit price of combination of zero-priced product is considered zero even if it is not

### ISSUE THREAD

**Issue by the-ge** [PrestaShop/PrestaShop#34518]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Suppose I have a product with combinations. I want to set combinations' prices and unit prices based solely on combination's impact on both prices, so I set the price/unit price (both of them) to zero on the product and the price impact/unit price impact to the desired values. Of course, I set the unity to the desired value, too.
When I click on the "Save" button, it will change nothing - as long as either the product unit price or the combination price impact are zero, even if all that matters is their sum, PrestaShop will incorectly conclude the final unit price is zero.
And, since the unit price is passed as zero to the theme, the theme will show nothing.

There are the #34260 and #34418 issues about the error on saving zero unit prices. PR #34419 removed the artificial constraints enforced on the form prices, but there is still such a constraint in the Product class in the `computeUnitPriceRatio()` method (lines 5883-5885):
```PHP
5872    private static function computeUnitPriceRatio(array $productRow, int $combinationId, int $quantity, Context $context): float
5873    {
5874        $baseUnitPrice = 0.0;
5875        if (isset($productRow['unit_price'])) {
5876            // Unit price is supposed to be in DB and accessible in the row
5877            $baseUnitPrice = (float) $productRow['unit_price'];
5878        }
5879
5880        // Then if combination has an impact we apply it on unit price
5881        if ($combinationId) {
5882            $combination = new Combination($combinationId);
5883            if (0 != $combination->unit_price_impact && 0 != $baseUnitPrice) {
5884                $baseUnitPrice = $baseUnitPrice + $combination->unit_price_impact;
5885            }
5886        }
5887
5888        // Finally, we apply the currency rate
5889        $defaultCurrencyId = Currency::getDefaultCurrencyId();
5890        $currencyId = Validate::isLoadedObject($context->currency) ? (int) $context->currency->id : $defaultCurrencyId;
5891        if ($currencyId !== $defaultCurrencyId) {
5892            $baseUnitPrice = Tools::convertPrice($baseUnitPrice, $currencyId);
5893        }
5894
5895        if ($baseUnitPrice == 0) {
5896            return 0;
5897        }
...
```
The issue could be simply solved by commenting/removing line 5886 and 5885 (I also moved the zero testing a bit upwards to bail as early as possible):
```PHP
5872    private static function computeUnitPriceRatio(array $productRow, int $combinationId, int $quantity, Context $context): float
5873    {
5874        $baseUnitPrice = 0.0;
5875        if (isset($productRow['unit_price'])) {
5876            // Unit price is supposed to be in DB and accessible in the row
5877            $baseUnitPrice = (float) $productRow['unit_price'];
5878        }
5879
5880        // Then if combination has an impact we apply it on unit price
5881        if ($combinationId) {
5882            $combination = new Combination($combinationId);
5883            //if (0 != $combination->unit_price_impact && 0 != $baseUnitPrice) {
5884                $baseUnitPrice = $baseUnitPrice + $combination->unit_price_impact;
5885            //}
5886        }
5887
5888        if ($baseUnitPrice == 0) {
5889            return 0;
5890        }
5891
5892        // Finally, we apply the currency rate
5893        $defaultCurrencyId = Currency::getDefaultCurrencyId();
5894        $currencyId = Validate::isLoadedObject($context->currency) ? (int) $context->currency->id : $defaultCurrencyId;
5895        if ($currencyId !== $defaultCurrencyId) {
5896            $baseUnitPrice = Tools::convertPrice($baseUnitPrice, $currencyId);
5897        }
...
```

### Expected behavior

The Product object should calculate the unit price as the sum of the product unit price and the combination unit price impact, and only then it should test it for zero value. Which will pass along a non-zero unit price if any of the two components is non-zero.
And, ultimately, the final unit price will be displayed by the theme if it's not zero.

### Steps to reproduce

Edit a demo product:
- product: Hummingbird notebook (ID: 18)
- product price: 0
- unit product: 0
- combination: Paper Type - Ruled (ID: 36)
- price impact: 10 euro (or whatever currency your shop is using)
- unit price impact: 1 euro
- unity: kg (heavy notebook, IKR :smile: )

Click on the "Save" button. Nothing changes. Check the product page: no unit price.

### PrestaShop version(s) where the bug happened

8.1.

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment]
Good change, we recently allowed to set product unit price to zero, can you make a PR for this?

Your code is good!

**Comment by the-ge** [comment]
[Done.](https://github.com/PrestaShop/PrestaShop/pull/34523)

**Comment by the-ge** [comment]
Should I make a PR for the `develop` branch, too, or is there a way to port this?

**Comment by Hlavtox** [comment]
@the-ge No need, it will be backported to develop branch in a week or two. :-)

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/34523
