### ISSUE TITLE
file_exists(): open_basedir restriction in effect. - composer.json

### ISSUE THREAD

**Issue by Zboru** [PrestaShop/PrestaShop#34526]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I try to change the product cover, it only gets an error window, and the Network tab in the inspector shows a request with a status of "403 Forbidden." Going to the Prestashop logs I noticed the following two errors:

`[2023-11-06 15:17:10] php.DEBUG: Warning: file_exists(): open_basedir restriction in effect. File(/ssd/composer.json) is not within the allowed path(s): (/ssd/<hidden-info>:/tmp:/usr/local/php52:/usr/local/php53:/usr/local/php54:/usr/local/php55:/usr/local/php56:/usr/local/php70:/usr/local/php71:/usr/local/php72:/var/www/html) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/ssd/<hidden-info>/domains/<hidden-info>/public_html/widnokrag/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Caster/LinkStub.php\",\"line\":94,\"trace\":[{\"file\":\"/ssd/<hidden-info>/domains/<hidden-info>/public_html/widnokrag/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Caster/LinkStub.php\",\"line\":55,\"function\":\"getComposerRoot\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\LinkStub\",\"type\":\"->\"}],\"count\":1})"} []`

`[2023-11-06 15:17:10] php.DEBUG: Warning: file_exists(): open_basedir restriction in effect. File(/ssd) is not within the allowed path(s): (/ssd/<hidden-info>:/tmp:/usr/local/php52:/usr/local/php53:/usr/local/php54:/usr/local/php55:/usr/local/php56:/usr/local/php70:/usr/local/php71:/usr/local/php72:/var/www/html) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/ssd/<hidden-info>/domains/<hidden-info>/public_html/widnokrag/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Caster/LinkStub.php\",\"line\":95,\"trace\":[{\"file\":\"/ssd/<hidden-info>/domains/<hidden-info>/public_html/widnokrag/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Caster/LinkStub.php\",\"line\":55,\"function\":\"getComposerRoot\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\LinkStub\",\"type\":\"->\"}],\"count\":1})"} []
`

The Prestashop instance is running on a shared hosting account managed by the company that provides the infrastructure. After disabling the ModSecurity apache2 module, everything returns to normal, unfortunately the company does not allow this setting.

The error occurs on a clean, unmodified instance of Prestashop.

Other users also report similar problems: https://github.com/PrestaShop/PrestaShop/issues/30531#issuecomment-1397821725

### Expected behavior

When setting the product cover, the page will correctly perform the operation and will not return an error

### Steps to reproduce

Reproduction can be complicated due to Apache2 server settings, while it looks like this:

1. Install the latest Prestashop
2. Go to edit the product
3. Try to change the product cover

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment]
This is caused by some third party module you have installed. No `ssd` string can be found anywhere in the prestashop codebase, including vendor folder.

**Comment by Zboru** [comment]
As I wrote in the issue, the problem is with a clean, unmodified version of Prestashop. The problem is in the while function in the LinkStub.php file. It consists of the code in the while loop trying to find the composer.json file. If the composer.json file is not found, it goes to the folder above. It gets to the point where the server blocks it and returns a 403.

**Comment by Hlavtox** [comment]
@Zboru Oh, yeah. Are you using prestashop.com edition (the one with bundled ps_metrics, ps_checkout and other bloatware) or the open source one?

**Comment by Zboru** [comment]
It has nothing to do with the installed modules. I disabled all of them, and even renamed the 'modules' folder so that it could not be recognized by Prestashop.

**Comment by florine2623** [comment]
Hello @Zboru ,

I can't reproduce your issue as you can see here : 

https://github.com/PrestaShop/PrestaShop/assets/16019289/bb99888c-e0e7-4e1d-806b-51b4e3cee3be


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
