### ISSUE TITLE
Category issue after bulk uploading categories using PHP 8.2. After downgrading to PHP 8.1, errors persist

### ISSUE THREAD

**Issue by kathep** [PrestaShop/PrestaShop#34535]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Prestashop version: 8.1.2
PHP version: 8.1.22
MySQL version: 10.5.19-MariaDB-0+deb11u2
Server software version: nginx/1.18.0

I am receiving an error whenever I try to access categories (by clicking on it in the menu area).
This issue started after doing a bulk upload of category data.

Steps taken in attempts to fix:
- downgrade php from 8.2 to 8.1
- upgrade Prestashop from 8.1.1 to 8.1.2
- delete all existing category data (via Monitoring interface)
- restart nginx
- restart mysql

Here are the logs:
INFO08:16:15 | php | User Deprecated: Since api-platform/core 2.7: The service "ApiPlatform\Core\Bridge\Symfony\Routing\IriConverter" is deprecated, use ApiPlatform\Symfony\Routing\IriConverter instead. {     "exception": {} }
-- | -- | --
INFO08:16:15 | request | Matched route "admin_categories_index". {     "route": "admin_categories_index",     "route_parameters": {         "_route": "admin_categories_index",         "_controller": "PrestaShopBundle\\Controller\\Admin\\Sell\\Catalog\\CategoryController::indexAction",         "_legacy_controller": "AdminCategories",         "_legacy_link": "AdminCategories",         "_legacy_parameters": {             "id_category": "categoryId"         },         "categoryId": null     },     "request_uri": "https://shop.nqo.link/admin624tllio5njwhgkwbtw/index.php/sell/catalog/categories?_token=uTMUDpOFR-QSWr1BE6z2NjySSaRd7QmCtMMBzndwKLk",     "method": "GET" }
DEBUG08:16:15 | doctrine | SELECT t0.id_lang AS id_lang_1, t0.name AS name_2, t0.active AS active_3, t0.iso_code AS iso_code_4, t0.language_code AS language_code_5, t0.locale AS locale_6, t0.date_format_lite AS date_format_lite_7, t0.date_format_full AS date_format_full_8, t0.is_rtl AS is_rtl_9 FROM ps_lang t0 WHERE t0.id_lang = ? [     1 ]
DEBUG08:16:15 | security | Read existing security token from the session. {     "key": "_security_main",     "token_class": "Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken" }
DEBUG08:16:15 | security | User was reloaded from a user provider. {     "provider": "PrestaShopBundle\\Security\\Admin\\EmployeeProvider",     "username": "hello@neuroqueero.com" }
INFO08:16:15 | php | User Deprecated: __construct is deprecated since version 8.1 and will be removed in the next major version. {     "exception": {} }
INFO08:16:15 | php | User Deprecated: Not specifying the optional ShopConstraint parameter is deprecated since version 1.7.8.0 {     "exception": {} }
DEBUG08:16:15 | doctrine | SELECT t0.id AS id_1, t0.employee AS employee_2, t0.shop AS shop_3, t0.controller AS controller_4, t0.action AS action_5, t0.filter AS filter_6, t0.filter_id AS filter_id_7 FROM ps_admin_filter t0 WHERE t0.employee = ? AND t0.shop = ? AND t0.filter_id = ? LIMIT 1 [     1,     1,     "category" ]
DEBUG08:16:15 | doctrine | SELECT t0.id AS id_1, t0.employee AS employee_2, t0.shop AS shop_3, t0.controller AS controller_4, t0.action AS action_5, t0.filter AS filter_6, t0.filter_id AS filter_id_7 FROM ps_admin_filter t0 WHERE t0.employee = ? AND t0.shop = ? AND t0.filter_id = ? LIMIT 1 [     1,     1,     "category" ]
INFO08:16:15 | php | User Deprecated: Not specifying the optional ShopConstraint parameter is deprecated since version 1.7.8.0 {     "exception": {} }
INFO08:16:15 | php | User Deprecated: Not specifying the optional ShopConstraint parameter is deprecated since version 1.7.8.0 {     "exception": {} }
DEBUG08:16:15 | doctrine | SELECT COUNT(cp.`id_product`) AS `products_count`, c.id_category, c.id_parent, c.active, cl.name, cl.description, cs.position FROM ps_category c LEFT JOIN ps_category_lang cl ON c.id_category = cl.id_category AND cl.id_lang = :context_lang_id AND cl.id_shop = c.id_shop_default LEFT JOIN ps_category_shop cs ON c.id_category = cs.id_category AND cs.id_shop = :context_shop_id LEFT JOIN ps_category_product cp ON c.`id_category` = cp.`id_category` WHERE (c.id_category != :root_category_id) AND (c.id_parent = :id_category_parent) AND (c.id_category != :root_category_id) AND (c.id_category != :root_category_id) GROUP BY c.`id_category` ORDER BY position asc LIMIT 50 {     "context_lang_id": 1,     "context_shop_id": 1,     "root_category_id": "1",     "id_category_parent": 2 }
DEBUG08:16:15 | doctrine | SELECT COUNT(c.id_category) FROM ps_category c LEFT JOIN ps_category_lang cl ON c.id_category = cl.id_category AND cl.id_lang = :context_lang_id AND cl.id_shop = c.id_shop_default LEFT JOIN ps_category_shop cs ON c.id_category = cs.id_category AND cs.id_shop = :context_shop_id WHERE (c.id_category != :root_category_id) AND (c.id_parent = :id_category_parent) AND (c.id_category != :root_category_id) AND (c.id_category != :root_category_id) {     "context_lang_id": 1,     "context_shop_id": 1,     "root_category_id": "1",     "id_category_parent": 2 }
INFO08:16:15 | php | User Deprecated: The "$name" argument in method "Symfony\Component\HttpKernel\DataCollector\ConfigDataCollector::__construct()" is deprecated since Symfony 4.2. {     "exception": {} }
INFO08:16:15 | php | User Deprecated: The "$version" argument in method "Symfony\Component\HttpKernel\DataCollector\ConfigDataCollector::__construct()" is deprecated since Symfony 4.2. {     "exception": {} }
INFO08:16:15 | php | User Deprecated: __construct is deprecated since version 8.1 and will be removed in the next major version. {     "exception": {} }
INFO08:16:15 | php | User Deprecated: The "Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent::getException()" method is deprecated since Symfony 4.4, use "getThrowable()" instead. {     "exception": {} }
INFO08:16:15 | php | User Deprecated: The "Symfony\Component\Debug\Exception\FatalThrowableError" class is deprecated since Symfony 4.4. {     "exception": {} }
INFO08:16:15 | php | User Deprecated: The "Symfony\Component\Debug\Exception\FatalErrorException" class is deprecated since Symfony 4.4, use "Symfony\Component\ErrorHandler\Error\FatalError" instead. {     "exception": {} }
CRITICAL08:16:15 | request | Uncaught PHP Exception TypeError: "stripslashes(): Argument #1 ($string) must be of type string, null given" at /var/www/prestashop/src/Core/Grid/Data/Factory/AbstractCategoryDataFactory.php line 77 {     "exception": {} }
CRITICAL08:16:15 | php | Uncaught Error: stripslashes(): Argument #1 ($string) must be of type string, null given {     "exception": {} }

### Expected behavior

I expect when I click on the Category menu item, the Category area will open without errors

### Steps to reproduce

1. Install Prestashop using php 8.2
2. Bulk upload categories data with '1 click import' tool (and possibly a syntax error?)
3. Downgrade php to 8.1.22
4. Restart nginx and mysql
5. Log out of prestashop and log back in
6. Click on categories (the errors remain).

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1.22

### If your bug is related to a module, specify its name and its version

default features

### Your company or customer's name goes here (if applicable).

n/a

**Comment by Hlavtox** [comment]
@kathep Some of your categories have NULL in name or description. You need to fix your 3rd party import tool. It's not possible to create this situation with a clean installation.

Moreover, PrestaShop is NOT COMPATIBLE with PHP 8.2 - https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/.

**Comment by kathep** [comment]
@Hlavtox I do not have skills to fix the 3rd party import tool. I just want to revert to as if I never used it. But that is proving difficult.

re PHP, I know. That's why I downgraded.

**Comment by kathep** [comment]
@Hlavtox Also, '1 click import' is perhaps a core feature, not a 3rd party tool. It comes loaded with Prestashop (under Advanced Parameters/Import) and cannot be removed.

**Comment by Hlavtox** [comment]
Oh, it was the built in tool? Hm...

Do this first, open phpmyadmin and run these queries:
```
UPDATE `ps_category_lang` SET `additional_description`='' WHERE `additional_description` IS NULL;
UPDATE `ps_category_lang` SET `description`='' WHERE `description` IS NULL;
UPDATE `ps_category_lang` SET `meta_description`='' WHERE `meta_description` IS NULL;
UPDATE `ps_category_lang` SET `meta_keywords`='' WHERE `meta_keywords` IS NULL;
UPDATE `ps_category_lang` SET `meta_title`='' WHERE `meta_title` IS NULL;
```

If it fixes your shop, can you provide me with the import configuration you used and the example file? Something is broken in that tool.

**Comment by kathep** [comment]
@Hlavtox My shop is fixed, thanks! I used TRUNCATE tool in a mariaDB/mysql via command line, then ran your queries in phpmyadmin. Overkill, but I wasn't confident I ran the truncate queries correctly. Anyway, something worked! 

Yes, the import tool is definitely crooked currently. 

<img width="507" alt="Screenshot 2023-11-12 at 9 18 53 am" src="https://github.com/PrestaShop/PrestaShop/assets/7587390/26a28e4c-95c0-4d8c-b9a0-e499aae17b23">

I could only import with the settings as shown above. Import fails with any other radio checked to yes - cannot finish import with custom IDs, for example.

This might be partly due to my csv file having formatting errors. I created it in LibreOffice but haven't checked it in another program (OpenRefine etc).

Here are my import files: 
Main categories: https://www.dropbox.com/scl/fi/ixg03s3qtknko0j5p4w3c/nqo_categories_import_shortcatIDs_1maincats.csv?rlkey=z7qsm8kop2evx1p0kfqvqkgvw&dl=0

Sub categories:
https://www.dropbox.com/scl/fi/ip9gnxu1hn9h45x4mx6ct/nqo_categories_import_shortcatIDs_2subcategories1.csv?rlkey=ataqhj1gkmzjceyx3ekbz2vsl&dl=0

Sub sub categories: 
https://www.dropbox.com/scl/fi/ka3we956ht115vyng5few/nqo_categories_import_shortcatIDs_3subsubcategories.csv?rlkey=x5td5ku006jiry3vmcevtt82g&dl=0

They are broken up like this because I got errors trying to import them together.

Thanks for looking into this!

**Comment by florine2623** [comment]
It seems like your issue is fixed.

You need to change the field separator like so :
<img width="629" alt="Screenshot 2023-11-13 at 10 17 11" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/494c53da-364f-4bda-835a-1091844f877e">

And ignore the first column ID :
<img width="1186" alt="Screenshot 2023-11-13 at 10 16 53" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/1b17eaf8-cc97-4e7c-813f-f9cb7b57a5ae">


Import successful :
<img width="609" alt="Screenshot 2023-11-13 at 10 17 00" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/f5c83f28-7f26-4821-baa8-2cd8a9a4d797">


I imported the categories with your files. And it worked :
<img width="1182" alt="Screenshot 2023-11-13 at 10 15 00" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/1095afe0-653c-49ca-9328-524aabe65c20">

I'm closing the issue ot avoid clogging the backlog.

**Comment by kathep** [comment]
Thank you Florine!

Yes, when I imported, it worked. However, the php errors described above were received after the import.

That is the issue with the import module - the errors received after import. 

KJ

On 13 Nov 2023, at 7:49 pm, florine2623 ***@***.***> wrote:


It seems like your issue is fixed.

You need to change the field separator like so :
 <https://user-images.githubusercontent.com/16019289/282415979-494c53da-364f-4bda-835a-1091844f877e.png>
And ignore the first column ID :
 <https://user-images.githubusercontent.com/16019289/282416409-1b17eaf8-cc97-4e7c-813f-f9cb7b57a5ae.png>
Import successful :
 <https://user-images.githubusercontent.com/16019289/282416103-f5c83f28-7f26-4821-baa8-2cd8a9a4d797.png>
I imported the categories with your files. And it worked :
 <https://user-images.githubusercontent.com/16019289/282415160-1095afe0-653c-49ca-9328-524aabe65c20.png>
I'm closing the issue ot avoid clogging the backlog.

**Comment by kathep** [comment]
Hey @Hlavtox and @florine2623 

This comment is to say thank you. <3
And also as a trail for anyone else who gets stuck on this categories error.

I just received the same error again, after a bulk upload. 

I ran the queries you listed above @Hlavtox , and it cleared the errors. :D

Next, when I re-uploaded, I was VERY careful to check and double check which columns I need to set the uploader to ignore, as in your post, @florine2623.

Thank you both, so much. I've learned a lot about mysql, as well as keeping my shop functioning.

**Comment by Hlavtox** [comment]
@kathep Cool, you are welcome! :-)

And please, if you think that anything in PrestaShop could be improved, don't hesitate to open a discussion https://github.com/PrestaShop/PrestaShop/discussions with your findings and possible improvements, we can then have a look. 🚀 Some things don't have sense, but once you learn it, you stop caring and forget. :-)

**Comment by kathep** [comment]
I didn’t think of this! Yes, excellent point, I’ll raise a discussion item. I think the bulk importer could be much easier to use with a few UI tweaks and nudges. But I’ll put more details of this in the discussion post.

Thanks again for being so welcoming of me into this community. It’s the first time I’ve consistently contributed to a dev community and aside from the pain of a steep learning curve, it’s been a joy. :)

On 2 Jan 2024, at 8:04 pm, Daniel Hlaváček ***@***.***> wrote:


@kathep <https://github.com/kathep> Cool, you are welcome! :-)

And please, if you think that anything in PrestaShop could be improved, don't hesitate to open a discussion https://github.com/PrestaShop/PrestaShop/discussions with your findings and possible improvements, we can then have a look. 🚀 Some things don't have sense, but once you learn it, you stop caring and forget. :-)
