### ISSUE TITLE
Currency API is not actual

### ISSUE THREAD

**Issue by dwcssol** [PrestaShop/PrestaShop#34559]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The Currency API https://api.prestashop.com/xml/currencies.xml has not been updated for 2 weeks. Please check and solve the problem.
This is the same data for 2 weeks now:
![image](https://github.com/PrestaShop/PrestaShop/assets/75415197/19cec016-a7b9-45e9-9932-b0aad23360df)

### Steps to reproduce

Go to https://api.prestashop.com/xml/currencies.xml
Check every day
The response doesn't change

### PrestaShop version(s) where the bug happened

all

**Comment by matks** [comment]
Thank you @dwcssol we're checking it right now 😉

**Comment by matks** [comment]
Problem should be fixed now

Can you confirm @dwcssol ?

**Comment by dwcssol** [comment]
Thanks. Actually it works.
We'll see tomorrow whether the night job works. But if you can assure me that it will work again, that's fine by me. If not, I'll just open another ticket tomorrow 😉


Mit freundlichem Gruß / Best regards,



Dennis Weber



[cid:810bcf91-ef01-4fef-ac10-3c43e3f3889b]



C/S-Solutions GmbH

Freiburger Straße 19 | 75179 Pforzheim

Telefon: +49 (0) 72 31 / 13 92 9 – 12

E-Mail: ***@***.******@***.***>



Zentrale: +49 (0) 72 31 / 13 92 9 – 0

Telefax: +49 (0) 72 31 / 13 92 9 – 29



www.cssol.de<http://www.cssol.de/>



Die Client/Server-Solutions EDV- und Kommunikationssysteme GmbH wird vertreten durch Herrn Jürgen Weber und Herrn Lorenz Heinz

Registergericht: Mannheim HRB 504018 | Sitz: Pforzheim | USt-Id-Nr.: DE 182084859



Diese Nachricht kann vertrauliche, firmeninterne Informationen enthalten. Sie ist ausschließlich für den oder die oben adressierten Empfänger bestimmt. Sollten Sie nicht der beabsichtigte Empfänger sein, bitten wir Sie, den Sender zu informieren und die Nachricht sowie deren Anhänge zu löschen. Unzulässige Veröffentlichungen, Verwendungen, Verbreitung, Weiterleitung sowie das Drucken oder Kopieren dieser Mail und ihrer verknüpften Anhänge sind strikt untersagt.

________________________________
Von: Mathieu Ferment ***@***.***>
Gesendet: Dienstag, 14. November 2023 11:44
An: PrestaShop/PrestaShop ***@***.***>
Cc: Dennis Weber ***@***.***>; Mention ***@***.***>
Betreff: Re: [PrestaShop/PrestaShop] Currency API is not actual (Issue #34559)


Problem should be fixed now

Can you confirm @dwcssol<https://github.com/dwcssol> ?

**Comment by AureRita** [comment]
Hi @dwcssol 

I tried to reproduce your issue and you can see this : 

![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/f1de0d0f-eb81-4dfc-b07d-b13517506351)

![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/f24d9cbd-4781-42c2-86f3-8922180d005b)

We can see the USD haven't the good value but USD at 1.07 is the good price yesterday. 

Moreover, I take this screenshot at 16h30, as we can see we don't have the same value and you issue is 7 hours ago 

![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/b641536b-d71f-45f8-8c2c-fb017b0ee308)

Did I miss something ? From wich date did you install your prestashop ? what is you last update about your shop ( some new order or anything else ) 

Waiting for your feedback

**Comment by matks** [comment]
Hello @AureRita thanks to @lfourreau the API was fixed this morning 😉
