### ISSUE TITLE
Display available quantities on the product page

### ISSUE THREAD

**Issue by nicosomb** [PrestaShop/PrestaShop#34551]
### Discussed in https://github.com/PrestaShop/PrestaShop/discussions/34471

<div type='discussions-op-text'>

<sup>Originally posted by **marcos-ba** November  5, 2023</sup>
Prestshop 8
option "Display available quantities on the product page" not working.
![BO setting](https://github.com/PrestaShop/PrestaShop/assets/37938630/42394b37-6ae2-44fd-94ba-9c9d29cfb57b)

![FO setting](https://github.com/PrestaShop/PrestaShop/assets/37938630/b82f9c6f-8584-444b-bc2b-ab2f3edb1b1d)
</div>

**Comment by MatShir** [comment]
### Expected

Should display the quantity on the FO page

**Comment by florine2623** [comment]
The stock is displayed here :


https://github.com/PrestaShop/PrestaShop/assets/16019289/bda4a826-f4ee-4dd3-9042-bdb9f50ea887

I'm closing the issue.

**Comment by MatShir** [comment]
Thansk @florine2623, the field in a bit hidden. 
@marcos-ba you could customize the theme if you want to highlight his value.

**Comment by marcos-ba** [comment]
> The stock is displayed here :
> 
>  Screen.Recording.2023-11-13.at.16.49.48.mov 
> I'm closing the issue.

thanks. 
There is any way to show this value in better place ?
