### ISSUE TITLE
Bug on product display

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#34554]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

![IMG_0107](https://github.com/PrestaShop/PrestaShop/assets/114789189/2ff50e68-e803-4237-998c-0a2b017eca5f)
![IMG_0081](https://github.com/PrestaShop/PrestaShop/assets/114789189/3891757c-9def-49b0-b8a6-63c33f4ac56c)
![IMG_0107](https://github.com/PrestaShop/PrestaShop/assets/114789189/471dad02-6614-46d2-b18f-fc385d85151a)

### Steps to reproduce

![ IMG_0107](https://github.com/PrestaShop/PrestaShop/assets/114789189/2e66c630-6b0d-4b04-af71-4b22d3881c06)il faut allez dans le menu principal pour le configurer 

### PrestaShop version(s) where the bug happened

1.7.8

**Comment by AureRita** [comment]
Hi @stanleylolli 

Thank you for your report, 
Please send your request in English. English is the norm on GitHub.
Moreover, can you do an hard refresh to see if it's not an issue about the cache ( you can do with Ctrl+Shift+R ) and can you give us a bigger detail about the steps to reproduce 

Waiting for your feedback

**Comment by ghost** [comment]
Bonjour, i m sorry i don’t speak English, merci pour votre retour je vais regarder avec les touches Ctrl+Shift+R cordialement 

Envoyé de mon iPhone

**Comment by ghost** [comment]
![IMG_0117](https://github.com/PrestaShop/PrestaShop/assets/114789189/09a7ec65-8328-48d0-bd2c-375d601d241c)
![IMG_0116](https://github.com/PrestaShop/PrestaShop/assets/114789189/4f4ca840-2d7a-44d8-8dd4-a6059b140e58)

**Comment by ghost** [comment]
![IMG_0119](https://github.com/PrestaShop/PrestaShop/assets/114789189/7ea728bc-0c40-4fc5-8cea-1a5f4f38ffbf)
![IMG_0118](https://github.com/PrestaShop/PrestaShop/assets/114789189/56fde742-5433-45ed-90cc-91fefd22fa30)

**Comment by paulnoelcholot** [comment]
Hello @stanleylolli,

Please add expected behavior, as well as clear and precise steps to reproduce. Screenshots without explanations are of no use to us. If you do not speak English, please use a translator.
If there is no modification to the ticket, it will be closed.

Thank you for your understanding

**Comment by ghost** [comment]
hi, the screenshots are to show that on the website we see 3 articles because in the backoffice there are 45 articles, there is a bug in the main menu the word home has disappeared twice

**Comment by florine2623** [comment]
Hello @stanleylolli ,

You have 3 product in your **subcategory** and 45 products in **total**.

You need to configure your menu according to what you want your customers to see.

This is not a Core matter. 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by stanleylolli** [comment]
hello, thank you for your information, at the beginning the parameters were configured like this on the site and it worked well, best regardsEnvoyé de mon iPhoneLe 16 nov. 2023 à 12:42, florine2623 ***@***.***> a écrit :﻿
Hello @stanleylolli ,
You have 3 product in your subcategory and 45 products in total.
You need to configure your menu according to what you want your customers to see.
This is not a Core matter.
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: Get help with PrestaShop.
Alternatively, you can also ask for help in the community forums or in the public Slack channel.
Thank you

**Comment by ghost** [comment]
hello, thank you for your information, at the beginning the parameters were configured like this on the site and it worked well, best regards
