### ISSUE TITLE
Wording conflict after changing modules from Upgrade to Update

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#34568]
### Describe the bug and add attachments

After wording of module actions was changed from Upgrade to Update on develop, it created conflict at least in Czech language.

![Snímek obrazovky 2023-11-14 220317](https://github.com/PrestaShop/PrestaShop/assets/6097524/37cd83cc-e8bf-479d-954f-c9aa96f3c6b0)

Now when you open Module Manager, you see word `Upravit`, which means to modify something (a text, a piece of wood, a car), not to update a module. For update, it should be `Aktualizovat`.

### Expected behavior

We must start using proper wording domains to avoid conflicts like this. The same story goes with neverending New for new products and new product condition.

If we are not using technical names for source strings, we should at least use specific domains.

### Steps to reproduce

Don't waste time by installing czech prestashop on develop, just check the screenshot. :-)

### PrestaShop version(s) where the bug happened

develop

**Comment by paulnoelcholot** [comment]
Hello @Hlavtox,

I reproduce the issue with PrestaShop version develop, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
