### ISSUE TITLE
SQLstate[42S02] Base table or view not found: 1146 Table upqgguyrzr.ps-pagenotfound doesnt exist

### ISSUE THREAD

**Issue by TheEnglishGartner** [PrestaShop/PrestaShop#34566]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,

I have recently upgraded to PS 8.1.2 with PHP 8.1 it seems prettygood. Although when clicking on a module "url-redirects-301-302-303-and-404-seo" Configure I get a page 500 - I enabled debug and have attached the result as an attachment. 

I have contacted the @Línea Gráfica but I thought that maybe others have seen this error, and could be happy to assist. 

### Expected behavior

I should get the configure tab for the module mentioned above. Also Im not sure that the module is working. 

### Steps to reproduce

Go to module 
Click on module configure 
500 error pops up 

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

url-redirects-301-302-303-and-404-seo version 1.4.7 (latest)

**Comment by Hlavtox** [comment]
Hi @TheEnglishGartner, you need to contact author of that module. Thank you for understanding. :-)
