### ISSUE TITLE
All the steps for completing an order take a lot to process

### ISSUE THREAD

**Issue by thecovrig** [PrestaShop/PrestaShop#34567]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

All the steps from adding an item to the cart, all the way to completing an order take a lot of time to load.

### Expected behavior

The steps should be instant or, at the very least, take a lot less to be processed.

### Steps to reproduce

1. Go to https://staterra.ro/en/62-eagles-henna
2. Click on any product to pen the page
3. Click on add to cart (takes several minutes)
4. Click on checkout in the pop-up window (takes several minutes) 
5. Click on checkout on the next window (takes several minutes) 
6. Add your personal information and click on "continue" (takes several minutes) 
7. Fill in your address and click on "continue" (takes several minutes) 
8. Pick a delivery method and click on "continue" (takes several minutes) 
9. Pick the "Pay by Cash on Delivery" option, so you don't have to actually pay
10. Check the agreement box and click the "Order" button (takes several minutes) 

If the issue can be diagnosed otherwise, please feel free to not go through the whole process.

### PrestaShop version(s) where the bug happened

1.7.8.10

### PHP version(s) where the bug happened

7.2.34

### Your company or customer's name goes here (if applicable).

staterra

**Comment by Hlavtox** [comment]
@thecovrig Something is wrong with your server or your installation, but this is not a help channel, you must contact a professional. 👍

**Comment by paulnoelcholot** [comment]
Hello @thecovrig,

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Thank you
