### ISSUE TITLE
Product on multistore activated automatically

### ISSUE THREAD

**Issue by Comval202** [PrestaShop/PrestaShop#34574]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On PS multistore, when modify the category of a product on 'AllShop' context, the status of the product is update on all shop contexts.

Probably same issue than https://github.com/PrestaShop/PrestaShop/issues/28008 

### Expected behavior

When modify a product category on All Shop context, the status of the product should not been update on the other shops.

### Steps to reproduce

1- On All Shop context : Activate a product
2- On non default shop context : Deactivate the same product
3- On All Shop context : Modify the product category (add a new category, or modify default category for example) and save
4- On non default shop context : Product status had been changed to 'Activate'

[20231115-ProductStatusChangedOK.webm](https://github.com/PrestaShop/PrestaShop/assets/58256765/659bfac6-ad7d-40b0-b347-e5375efbf572)

### PrestaShop version(s) where the bug happened

1.7.8.9 and 8.1.3 when "new product page' is desactivated

### PHP version(s) where the bug happened

7.4.33

### Your company or customer's name goes here (if applicable).

202 ecommerce

**Comment by florine2623** [comment]
Hello @Comval202 ,

Tested with the new product page. It works as expected.


Please used the latest product page available from now on as it is stabilised.

And if a bug is present on the old product page and fixed on the new product page, it won't be fixed on the old product page.


I'm closing the issue to avoid clogging the backlog.
Thanks!
