### ISSUE TITLE
psgdpr - replace Tools::jsonDecode with json_decode in APIFAQClass.php for prestashop 8.1

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#34575]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
I've seen that it is necessary to replace Tools::jsonDecode with json_decode in APIFAQClass.php for prestashop 8.1.2

![1](https://github.com/PrestaShop/PrestaShop/assets/653230/ca1c5ef1-dbb3-4ff4-aa04-4a7f56a3e400)

Tools::jsonDecode is not present into prestashop 8.1.2

bye

### Steps to reproduce

1. look at the file APIFAQClass.php inside the module

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

psgdpr 1.4.3

**Comment by paulnoelcholot** [comment]
Hello @maofree,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by ShaiMagal** [comment]
@maofree @paulnoelcholot file "APIFAQClass.php" not exists in module "psgdpr".

It's same like I already wrote here today:
https://github.com/PrestaShop/PrestaShop/issues/34581
(**similar story, different module**)

**Comment by Maofree** [comment]
Hi @ShaiMagal 
I've seen that it is present from old versions not removed from last updates

thanks

**Comment by Maofree** [comment]
look here

the modules seems to be a different version but it is also 1.4.3

![1](https://github.com/PrestaShop/PrestaShop/assets/653230/01525012-ab5c-4c70-a4dc-ea617b4d8768)

I give you the zip present on some websites

[psgdpr.zip](https://github.com/PrestaShop/PrestaShop/files/13382542/psgdpr.zip)

look inside controllers is present admin folder, instead config folder is not present

it is so strange to be the same version

**Comment by ShaiMagal** [comment]
@maofree our module psgdrp is without this file. Check github:
https://github.com/PrestaShop/psgdpr

Delete whole module and install again. Not from zip, from distribution api.
Will be there this file again?

**Comment by Maofree** [comment]
Hi
Surely if I remove it and reinstall it I will find the new files. I'll do it tomorrow on many sites

**Comment by Maofree** [comment]
Hi @ShaiMagal 
I've tested now, I reopen this topic because there is an error about this module

prestashop 8.1.2 with php 8.1

I start by uninstalling the module and removing its folder
then I install it again

the module installed has not the folders like here https://github.com/PrestaShop/psgdpr but they are so:

![1](https://github.com/PrestaShop/PrestaShop/assets/653230/3b69b805-5360-42d4-b64a-570fef7bd4d5)

I tried with two sites, one on my local server and one on a real server

try by yourself

**Comment by Maofree** [comment]
Hi @ShaiMagal
Have you done a test?

**Comment by ShaiMagal** [comment]
@maofree no, it is not my speciality. I dont know.
Open new issue. This name issue not coresspondent to content.

**Comment by Maofree** [comment]
ok

**Comment by Maofree** [comment]
https://github.com/PrestaShop/PrestaShop/issues/34624
