### ISSUE TITLE
ps_legalcompliance - replace Tools::jsonDecode with json_decode in ps_legalcompliance.php for prestashop 8.1

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#34579]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
I've seen that it is necessary to replace Tools::jsonDecode with json_decode in ps_legalcompliance.php for prestashop 8.1.2

![1](https://github.com/PrestaShop/PrestaShop/assets/653230/a07ed32d-1391-43f9-9c7c-ede41e8a24a9)

Tools::jsonDecode is not present into prestashop 8.1.2

bye

### Steps to reproduce

1. look at the file ps_legalcompliance.php inside the module

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_legalcompliance v3.0.2

**Comment by ShaiMagal** [comment]
@maofree @florine2623 module "ps_legalcompliance" is obsolete 2 years.

"_This repository has been archived by the owner on Dec 3, 2021. It is now read-only._"

This should be close.

@Hlavtox is it correct? Or am I missing something?

I guess obsolete modules are now totally out.

**Comment by Hlavtox** [comment]
Yeah, sorry @maofree if you want to fix it, you must fork the module. Thanks for understanding. :-)
