### ISSUE TITLE
Create Product Button not showing on BackOffice

### ISSUE THREAD

**Issue by joseindexeo** [PrestaShop/PrestaShop#34585]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello everyone. 
I am developing a multistore shop and I have a problem on adding new products. 
When a click on the add new product button on the product catalog the popup with the options appear.

Then, I choose the shop and the product options are shown (combination, individual,...); and here is the problem, there are no button to continue. 

I've looked in the browser's developer console and the button appears when I search for it using ctrl+f. The funny thing is that it also appears in the popup when I perform the search.
I have tried to add CSS styles to make it display but there is no way.

 

Popup before searching on the console:
![image](https://github.com/PrestaShop/PrestaShop/assets/150949404/65db7b20-11c4-4593-9a40-8b613a584c3c)
Popup after searching on the console:
![image](https://github.com/PrestaShop/PrestaShop/assets/150949404/cd9559f5-d6bc-4f73-92df-7eb6b72f8560)

### Steps to reproduce

1. Go to product catalog
2. Click on add new product

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello @joseindexeo ,

Please contact the support directly via your BO :
![Capture d'écran 16 11 2023 à 14 19 59 PM](https://github.com/PrestaShop/PrestaShop/assets/16019289/08180065-34d0-488b-8c4f-d3bce44c5880)

Alternatively, you can check this link for more info : 
https://help-center.prestashop.com/fr?utm_source=back-office&utm_medium=home

I'm closing your issue as it is not related to the Core.
Thanks!
