### ISSUE TITLE
ps_faviconnotificationbo - replace Tools::jsonDecode with json_decode in APIFAQClass.php for prestashop 8.1

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#34581]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi

I've seen that it is necessary to replace Tools::jsonDecode with json_decode in ps_faviconnotificationbo/classes/APIFAQClass.php for prestashop 8.1.2

![1](https://github.com/PrestaShop/PrestaShop/assets/653230/dc015506-aa46-4d59-836a-ab3f0471b734)

### Steps to reproduce

1. look at the file APIFAQClass.php inside the module

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_faviconnotificationbo v2.1.3

**Comment by ShaiMagal** [comment]
@maofree I don't see file APIFAQClass.php and folder "classes":
https://github.com/PrestaShop/ps_faviconnotificationbo

**Comment by Maofree** [comment]
Hi
yes you are right
I've found it in a site that I've upgraded to 8.1, perhaps that folder was left over from a past module update
![1](https://github.com/PrestaShop/PrestaShop/assets/653230/397acdfe-c508-47f7-a421-61bb6c099e2d)
