### ISSUE TITLE
ps_emailsmanager - replace Tools::jsonDecode with json_decode in ps_emailsmanager.php for prestashop 8.1

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#34583]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
I've seen that it is necessary to replace Tools::jsonDecode with json_decode in ps_emailsmanager.php for prestashop 8.1.2
you need to do it several times in this file

![1](https://github.com/PrestaShop/PrestaShop/assets/653230/f344a927-7662-44ef-b804-46a555203444)

bye

### Steps to reproduce

1. look at the file ps_emailsmanager.php inside the module

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_emailsmanager  v1.2.1

**Comment by buggyzap** [comment]
Hi, thanks for reporting, but it is related to a specific module so I will suggest you to open the issue here: https://github.com/PrestaShopCorp/ps_emailsmanager and this Issue needs to be closed / deleted.

**Comment by Maofree** [comment]
Hi @buggyzap 
here they report the same problem
https://github.com/PrestaShopCorp/ps_emailsmanager/issues/19

Why hasn't it been resolved yet?

**Comment by ShaiMagal** [comment]
@maofree Because noone make PR...? Why you don't make PR yourself?

Done, here PR for this:
https://github.com/PrestaShopCorp/ps_emailsmanager/pull/20

btw, I see this module first time in my life :)

**Comment by Hlavtox** [comment]
@ShaiMagal Thanks for the PR bro. WH!!!

@maofree Closing this issue as it's a Prestashop company module and this is the open source project. Thank you for understanding.

**Comment by Maofree** [comment]
Hi @Hlavtox 
Could you explain this to me better, because I didn't understand, so for the next errors I'll know what to do.
Do I have to report the errors I find in the forms in their own section?
https://github.com/PrestaShopCorp/ps_emailsmanager/issues

another question, how do I increase the priority of an error? there are minor errors and other major ones, but they are often classified as minor

I finish updating the last 3 sites to prestashop 8.1 and then I start studying github so I can solve them myself by creating the PRs without having to do it to others and they are corrected faster

**Comment by Hlavtox** [comment]
@maofree Yeah, so, all our native modules that come bundled with Prestashop are here - https://github.com/PrestaShop, and we can manage them.

But the module ps_emailsmanager is managed by Prestashop company here - https://github.com/PrestaShopCorp, which people outside don't have access to.
