### ISSUE TITLE
Change picture in product modify

### ISSUE THREAD

**Issue by ECC64** [PrestaShop/PrestaShop#34580]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I modify a product and I want to add an image, once the image is uploaded, when I click on it the window with the caption does not open. When I refresh the page, the image is fine, but white, and there we can open the window to choose it as the cover image. And finally we do not return this image in the variations.

### Expected behavior

we insert the new image, modify the ALT tag and choose it as the cover. we can also assign it to a variation

### Steps to reproduce

Edit a product (thsi product have images)
clic to insert another image
upload it
try to open the windows with legend and choice cover
refresh the page
the image appear white
try to modify image variation

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

7.4

### Your company or customer's name goes here (if applicable).

Mobilier Inox CB

**Comment by Hlavtox** [comment]
@ECC64 Hi, this will be fixed in 8.1.3. 

Please apply this fix manually for now and your images will work. It's just one line. https://github.com/PrestaShop/PrestaShop/pull/34351/files

**Comment by ECC64** [comment]
Thank you, it works very well :)
