### ISSUE TITLE
 fatal error when translation key is numeric

### ISSUE THREAD

**Issue by ioweb-gr** [PrestaShop/PrestaShop#34603]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When using legacy translation system and the key is numeric e.g. 

1 => "1" 
2 => "2" 

The whole translation system breaks because md5 cannot handle numbers. 

![283630911-728baad8-a23b-4a6d-a834-8387a91bf652](https://github.com/PrestaShop/PrestaShop/assets/20220341/27575ca5-618c-4de1-8008-aa6b2db0d27b)

### Expected behavior

Translation system works

### Steps to reproduce

Create a translation file with numeric keys as index

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.4+

### Your company or customer's name goes here (if applicable).

IOWEB TECHNOLOGIES

**Comment by ioweb-gr** [comment]
Please check PR https://github.com/PrestaShop/PrestaShop/pull/34602

**Comment by AureRita** [comment]
Hi @ioweb-gr 

Thank you for your report, Despite my effort, I can't reproduce your issue as you can see : 

[Untitled_ Nov 17, 2023 5_00 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/9ec45300-f118-4b52-8d51-1cf9d7fde258)

Did I miss something ? 

Waiting for your feedback

**Comment by ioweb-gr** [comment]
Yes in order to reproduce this you need to add the translation with the numeric key in the `lang/<code>.php` files in modules

**Comment by florine2623** [comment]
Can you specify exactly what to change and in which file ?

**Comment by ioweb-gr** [comment]
I'm not sure I can find that offending declaration with that as due to the nature of the translation system I couldn't trace the failing translation definition when I tried the first time after a few hours.

So, I went from the reverse direction and found the issue by debugging the \Throwable and found that the translation key was set as (int) 1. 

I hava a feeling that at some point before execution when the strings are collected someone used an array_keys function which converts the string keys to integers if they are numeric causing the issue. Unfortunately I'm not that well familiarized with Prestashop code

However I did provide a PR for this to eliminate the issue https://github.com/PrestaShop/PrestaShop/pull/34602

**Comment by florine2623** [comment]
Thanks for the details and for the PR.
I meant, could you send the details of what to change in what file so I can reproduce your error ?
If we don't reproduce the issue, the PR will not be tested.

**Comment by florine2623** [comment]
ping @ioweb-gr 
Could you specify the steps to reproduce ?
I see your PR ready to test, but in order to test it we need to confirm the issue first !

**Comment by ioweb-gr** [comment]
As mentioned before unfortunately I don't have the possibility or time to backtrace all translation files to find the offending key.
I have tracked the faulty line and the reason behind it, but I can't invest the extra time needed to find the exact translation file for reproducing it without charging a fee which my client won't accept unfortunately :( 

If the PR can't be merged due to this I'll just keep it as a composer patch for future versions.

**Comment by florine2623** [comment]
Hello,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by florine2623** [comment]
Closed as it cannot be reproduced

**Comment by kpodemski** [comment]
Fixed in PrestaShop 9.
