### ISSUE TITLE
Fatal Error when login to the shop

### ISSUE THREAD

**Issue by huyhoang8398** [PrestaShop/PrestaShop#34605]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have multishops, when i login to the 1st shop, it was fine, but the 2nd shop gave Fatal Error at the top left corner
Bellow is the log with debug log enabled:

```
Fatal error
at line 1182 in file classes/Tools.php

1177.                 ->getTranslator()
1178.                 ->trans('Fatal error', [], 'Admin.Notifications.Error');
1179.         }
1180. 
1181.         if (_PS_MODE_DEV_) {
1182.             throw new PrestaShopException($errorMessage);
1183.         }
1184. 
1185.         return $errorMessage;
1186.     }
1187. 
ToolsCore::displayError - [line 3632 - classes/Product.php]
ProductCore::getPriceStatic - [line 5640 - classes/Product.php] - [8 Arguments]
ProductCore::getProductProperties - [line 833 - classes/Cart.php] - [2 Arguments]
CartCore->getProducts - [line 1478 - modules/pm_subscription/pm_subscription.php]
pm_subscription->hookActionCartSave - [line 1007 - classes/Hook.php] - [1 Arguments]
HookCore::coreCallHook - [line 431 - classes/Hook.php] - [3 Arguments]
HookCore::callHookOn - [line 944 - classes/Hook.php] - [3 Arguments]
HookCore::exec - [line 299 - classes/Cart.php] - [2 Arguments]
CartCore->update - [line 437 - classes/controller/FrontController.php]
FrontControllerCore->init - [line 287 - classes/controller/Controller.php]
ControllerCore->run - [line 525 - classes/Dispatcher.php]
DispatcherCore->dispatch - [line 28 - index.php]
```

### Expected behavior

Can login same as shop 1

### Steps to reproduce

1. Go to 1st shop -> Login -> can login
2. Go to 2nd shop -> Login -> Fatal error

### PrestaShop version(s) where the bug happened

1.7.8.10

### PHP version(s) where the bug happened

7.4.33

**Comment by AureRita** [comment]
Hi @huyhoang8398 

Thank you for your report, Despite my effort I can't reproduce your issue, as you can see : 

[Untitled_ Nov 17, 2023 4_43 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/e7260a2f-ff6b-46d8-b0d7-86ab19042185)

Did I miss something ? 

Waiting for your feedback

**Comment by huyhoang8398** [comment]
Hi, Thanks for you reply, here is my video to demonstrate the issue

I tried with another account, it will also give Fatal error

https://github.com/PrestaShop/PrestaShop/assets/25379882/3db7f91c-38db-4872-809f-8f681fb67d38

**Comment by Hlavtox** [comment]
Disable pm_subscription and check

**Comment by huyhoang8398** [comment]
thank @Hlavtox, it's working well now

**Comment by TheEnglishGartner** [comment]
Hi, could I get a bit more explanation on this? I also startet to get this - The first customer called and I tried to log in as that specific customer and got the fATAL Error - I deleted the customer and recreated the customer and it worked again. But why is this happening Im on PS 8.1.2 
PHP-version: 8.1.27
Using warehouse theme




Thanks in advance
