### ISSUE TITLE
Search Bar letters a and p are duplicated when typing

### ISSUE THREAD

**Issue by yorgocom70** [PrestaShop/PrestaShop#34612]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When typing in the search bar, letters a and p are "typed" twice! 

### Expected behavior

each letter should be typed once per keyboard click

### Steps to reproduce

1. go to search bar in main shop (webdev.ishoprural.com) 
2. click on search bar
3. type the name of a product you wish to search for (should contain letters a or p) 
[Ishoprural - Google Chrome 2023-11-18 13-51-00.webm](https://github.com/PrestaShop/PrestaShop/assets/136168072/9ba29b74-8603-43f1-ad98-9e69ef5aa6eb)

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

7.2.24

### If your bug is related to a module, specify its name and its version

search bar 2.1.3

**Comment by Hlavtox** [comment]
Hi @yorgocom70, this is a problem with your keyboard or your theme. :-)
