### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by lxregistry** [PrestaShop/PrestaShop#34623]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Unknown error on line 81 in file /var/www/vhosts/prestashop/public_html/classes/Smarty/SmartyLazyRegister.php
[8192] addslashes(): Passing null to parameter #1 ($string) of type string is deprecated

Unknown error on line 2599 in file /var/www/vhosts/prestashop/public_html/classes/controller/AdminController.php
[8192] Creation of dynamic property HelperList::$languages is deprecated

Unknown error on line 2606 in file /var/www/vhosts/prestashop/public_html/classes/controller/AdminController.php
[8192] Creation of dynamic property HelperList::$default_form_language is deprecated

### Expected behavior

expect a clean code, without warnings in backoffice

### Steps to reproduce

just open admin area

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

-

### Your company or customer's name goes here (if applicable).

anonymous

**Comment by florine2623** [comment]
Hello,

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
