### ISSUE TITLE
Search engine in the shop does not work

### ISSUE THREAD

**Issue by Ksampl** [PrestaShop/PrestaShop#34622]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,

As in the title - the search engine is not working in the shop v 1.7.7.5. The problem appears with every template also with classic, I have already tried rebuilding the index, disabling and enabling the search module. I have cleared the site cache + my cookies and search engine file.

After trying to search, I get these errors in the console and I do not know if they are related:
![image](https://github.com/PrestaShop/PrestaShop/assets/151520507/5c0d55bf-16b5-4b21-98a9-49f66a24d4db)

### Steps to reproduce

![image](https://github.com/PrestaShop/PrestaShop/assets/151520507/0b6b4fd7-bc4a-4428-b287-f332aa5d5304)

### PrestaShop version(s) where the bug happened

1.7.7.5

### PHP version(s) where the bug happened

7.2

**Comment by Hlavtox** [comment]
@Ksampl Something wrong with your installation, I suggest hiring a specialist to find what is wrong.

The errors in the console are not related, because at least the search page should work normally, even without javascript. 👍
