### ISSUE TITLE
Create Product Button at multistore not showing on BackOffice

### ISSUE THREAD

**Issue by joseindexeo** [PrestaShop/PrestaShop#34621]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello everyone.
(I contacted support after an issue was closed telling me to contact support and when I contacted support via email they told me to open an issue on github)
I am developing a multistore shop and I have a problem on adding new products.
When a click on the add new product button on the product catalog the popup with the options appear.

Then, I choose the shop and the product options are shown (combination, individual,...); and here is the problem, there are no button to continue.

I've looked in the browser's developer console and the button appears when I search for it using ctrl+f. The funny thing is that it also appears in the popup when I perform the search.
I have tried to add CSS styles to make it display but there is no way.

Popup before searching on the console:
![283198404-65db7b20-11c4-4593-9a40-8b613a584c3c](https://github.com/PrestaShop/PrestaShop/assets/150949404/d756f204-18c4-4b10-82a3-3b97bfb19673)
Popup after searching on the console:
![283198499-cd9559f5-d6bc-4f73-92df-7eb6b72f8560](https://github.com/PrestaShop/PrestaShop/assets/150949404/2de3d861-29f1-4d3c-ac0b-e9a8a18f8c77)

### Expected behavior

What is expected is that the button that allows you to advance in the process of creating a product appears from the beginning

### Steps to reproduce

1. Go to product catalog
2. Click on add new product

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello! I see 😉 you have downloaded PrestaShop Edition.

PrestaShop Edition is a solution based on the open source project PrestaShop. It contains additional functionalities powered by modules directly installed at the creation of the store and is being built and distributed by PrestaShop company.

To find help for PS Edition, I suggest to go to https://help-center.prestashop.com/
