### ISSUE TITLE
Installation failure at 78% prestashop edition

### ISSUE THREAD

**Issue by vitalijalbu** [PrestaShop/PrestaShop#34620]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Donwloaded 8.1 version and tried to install prestashop in italian.
Using mamp, php version 8.2

![Screenshot 2023-11-20 alle 08 23 57](https://github.com/PrestaShop/PrestaShop/assets/40239902/806a6546-5740-4d8c-8f60-3acac2651788)

### Steps to reproduce

1. download prestashop
2. setup installation with demo data

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.2

### If your bug is related to a module, specify its name and its version

no

**Comment by matks** [comment]
Hello! I see 😉 you have downloaded PrestaShop Edition.

PrestaShop Edition is a solution based on the open source project PrestaShop. It contains additional functionalities powered by modules directly installed at the creation of the store and is being built and distributed by PrestaShop company.

To find help for PS Edition, I suggest to go to https://help-center.prestashop.com/
