### ISSUE TITLE
Error adding images 

### ISSUE THREAD

**Issue by pedroideavity** [PrestaShop/PrestaShop#34639]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have a multistore.
I cannot upload images to the products page.
The images i have were imorted through csv.

Also when create a new product, it gives an error when i try to upload the images

### Expected behavior

Upload images

### Steps to reproduce

Try to upload an image

The error: https://fre****.com/admin*************/index.php/sell/catalog/products-v2/images/add?_token=rS81BQIl-sQsBnmAR6vcwXw-0rOIwESU0UBgHwQipuw 404 (Not Found)

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

 8.1.25

### Your company or customer's name goes here (if applicable).

Pedro

**Comment by florine2623** [comment]
Hello @pedroideavity ,

Please, for security reasons, change your admin link. This is a public space.

I can't reproduce your issue.

https://github.com/PrestaShop/PrestaShop/assets/16019289/986f37fe-f59c-405a-a3d0-b265ef203dd6


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
