### ISSUE TITLE
Bug enregistrement description produit 

### ISSUE THREAD

**Issue by alexiskaze** [PrestaShop/PrestaShop#34644]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Bonjour 

J'ai 02 bugs

1. 

Dysfonctionnement enregistrement description produit. 
Quand tente d'enregistrer la sélection de la catégorie associée au produit, il y a une alerte qui est la suivante "ce champ ne doit pas dépasser 21844 caractères ". Or le nombre de caractères est inférieur à 21844. 
J'ai ce problème par exemple sur les produits dont les ID sont : 62133  &  8269

2.

De temps à autres, impossible de mettre à jour les modules natifs de PrestaShop. 

  

### Expected behavior

1.

Je m'attends au succès de l'enregistrement des modifications des descriptions de produit surtout du choix de la catégorie. 

2.

Je m'attends au succès de la mise à jour des catégories sans avoir besoin de réinitialiser le module. 

### Steps to reproduce

Bug 1

BO--> Catalogue ---> Produits ---> choix ID 62133  ou  8269 ---> ajouter des catégories ---> services ---> enregistrer ---> résultat : ce champ ne doit pas dépasser 21844 caractères

Bug 2 : choix module ---> Mettre à jour 

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.0

### Your company or customer's name goes here (if applicable).

orapeco

**Comment by Hlavtox** [comment]
@alexiskaze Can you please copy the source code of description and paste it here? https://mothereff.in/byte-counter

And send a screenshot?

**Comment by hibatallahAouadni** [comment]
Hello @alexiskaze 

Please send your request in English. English is the norm on GitHub.

PS: thanks @Hlavtox for your quick reply 🚀 

Thank you

**Comment by alexiskaze** [comment]
Hello
The error code has been sent from the link received:
https://mothereff.in/byte-counter

Here is the capture of the alert each time you try to save changes to the
description of a product, especially when assigning a category to the
product.


[image: image.png]


Thanks for your help

Sincerely

Alexis Kazé

Entrepreneur

Dirigeant ORAPECO

***@***.***

06 13 16 35 92

15 rue du vieux Moulin

78370

Plaisir - France

**Comment by Hlavtox** [comment]
@alexiskaze Image not working, respond using github :-)

**Comment by alexiskaze** [comment]
![Description](https://github.com/PrestaShop/PrestaShop/assets/148473231/a9e850ea-3fd6-42f2-97f8-d79e28e03959)

**Comment by florine2623** [comment]
Hello @alexiskaze ,

I can't reproduce your issue.

https://github.com/PrestaShop/PrestaShop/assets/16019289/19e299ae-1626-4000-a7a8-2abcc26dab05

Try it with PPV2.
`Advanced parameters > New and experimental features > Enable New product page`

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by Hlavtox** [comment]
@alexiskaze Please, read what I write.

Open the product that doesn't save.

Click on “Show source code” button in the tinymce editor of the description that does not save. `<>`

Save it in TXT file and attach it here, I will check the length.
