### ISSUE TITLE
Can't set cover product image on Product edit page

### ISSUE THREAD

**Issue by jix31** [PrestaShop/PrestaShop#34646]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After a fresh Prestshop 8.1.2 (downloaded from github)  when I edit a product in backend  👍 
-  i can move and set the cover image 
- and when i to save the caption text on image product I have an error ( see screen below) 
 
<img width="712" alt="Capture d’écran 2023-11-21 à 18 27 01" src="https://github.com/PrestaShop/PrestaShop/assets/151663961/77af0fa4-9417-4b86-bdd4-1d02f857dbfc">

i see this error on the Chrome DevTools

![2023-11-22-à-08 14 16](https://github.com/PrestaShop/PrestaShop/assets/151663961/c58e5e55-6e9f-4b4a-b43c-3b3e69500f46)

### Steps to reproduce

1-Go to edit page of a product on back-office that have more than one image.
2-Select another image than the cover one and try to set as cover  
3 - click button to save  ( the image is not set as cover) 

1 - try to change position of a product image on back-office
2 - the product image don't move

 1-Go to edit page of a product on back-office that have more than one image.
 2 -click on image and set the caption text
 3 save ( the save process works, the caption text is saved but an error show) 

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1.24

### If your bug is related to a module, specify its name and its version

no

**Comment by paulnoelcholot** [comment]
Hello @jix31,

I reproduce the issue with PrestaShop version 8.1.2, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

[Untitled_ Nov 22 2023 2_26 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/112863083/066fc15a-7d6a-486b-92b4-9a32dfa34076)

**Comment by Hlavtox** [comment]
@paulnoelcholot I think you show something completely different on your video. The author is getting some javascript errors and you don't show any on the video, so I don't know what issue you have reproduced.

Morover, the reason that your image is not displayed in front office is because you did not add it to any combination.

Putting labels back so it's reproduced again properly or closed.

**Comment by jix31** [comment]
@Hlavtox you're right this is not the same  "bug"   in the @paulnoelcholot  screen video ...

**Comment by jix31** [comment]
i find 2 others occurrences of the problem I am describing with set cover image and move product images

>> #33611 
>>  #34534

**Comment by Hlavtox** [comment]
@jix31 Could you try to open F12 (developer tools), go to network tab and check what response comes from the core when you upload the image?

**Comment by jix31** [comment]
another error information (from console dev) , when i try to move image: 
<img width="1422" alt="Capture d’écran 2023-11-22 à 18 48 26" src="https://github.com/PrestaShop/PrestaShop/assets/151663961/d2da1660-502b-4dba-a144-20108884e03b">

**Comment by jix31** [comment]
@Hlavtox  i don't have any problem when i upload image

the problem is when i want to set cover image  or when i want to move image , or when i want to add caption text on image

**Comment by Hlavtox** [comment]
OK, so try to open the network tab, move the image, set cover, whatever, and check the response. ;-)

![Snímek obrazovky 2023-11-22 185815](https://github.com/PrestaShop/PrestaShop/assets/6097524/708d5465-360d-4232-a0a5-27b3368f42c5)

**Comment by jix31** [comment]
nothing ins response when itrry to set cover (or move) 


Cordialement, 

J

**Comment by jix31** [comment]
and when i click on red message on dev tool (network) i have this error message 

No route found for "GET /sell/catalog/products-v2/images/21/update": Method Not Allowed (Allow: PATCH)
[Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException 0]
Activer le mode debug



Cordialement, 



J

**Comment by Hlavtox** [comment]
Go to Bo > Performance, enable debug mode and try again. There should be something in that responses now.

**Comment by jix31** [comment]
i have this when i activate debug in BO

<img width="517" alt="Capture d’écran 2023-11-22 à 19 34 22" src="https://github.com/PrestaShop/PrestaShop/assets/151663961/7a97eacf-0d29-4fc1-a2aa-c1833fff9771">

**Comment by Hlavtox** [comment]
@jix31 I need you to check the developer tools in your browser, and inspect the responses of the failing requests.

Or try to click on the failed request in symfony debug toolbar as you sent.

**Comment by jix31** [comment]
no responses

<img width="2556" alt="Capture d’écran 2023-11-22 à 19 04 01" src="https://github.com/PrestaShop/PrestaShop/assets/151663961/6b2f86d0-e6ed-4a95-aac4-69f3a23d4fab">

**Comment by jix31** [comment]
here another scree from begug toolbar 
<img width="1414" alt="Capture d’écran 2023-11-22 à 19 10 17" src="https://github.com/PrestaShop/PrestaShop/assets/151663961/af1e8d2b-523f-44a8-8319-353045605ef0">

**Comment by florine2623** [comment]
Hello @jix31 ,

I can't reproduce your issue :

https://github.com/PrestaShop/PrestaShop/assets/16019289/6ff3004e-1ffa-45c9-bbce-d73390ba8054

I'm closing your issue. You can still continue to respond to the issue.

**Comment by jix31** [comment]
i not agree to close the issu ,there is at least 3 issues of the same bug and YOU close all ....

**Comment by jix31** [comment]
@florine2623  i'am not ok to close this issue  
there is at least 3 issues of this bug and you closed all

i made 4 fresh install of prestashop 8.1.2 (downloaded from github) and all times the same issues with image products .

And  you can see all the errors messages and from debug below ...

**Comment by jix31** [comment]
@florine2623  withch version of prestashop and php do you use for your video ?

**Comment by Hlavtox** [comment]
@jix31 I would like to help you but you need to read what I write. I say enable debug mode and you don't have it enabled. :-))

Please:
- KEEP DEBUG ENABLED
- Check error logs on your server if there are any errors when you try to save the image.
- Try to check the responses of the patch request again, it should show some error in debug mode, check if it ends up with 500 http code.

**Comment by jix31** [comment]
@Hlavtox  thanks for your help !!

i try to read everything  step by step  and here a screen of this  

<img width="2557" alt="Capture d’écran 2023-11-24 à 17 11 56" src="https://github.com/PrestaShop/PrestaShop/assets/151663961/1d9fbe1d-ec6f-4a50-b17b-b295a840694f">

i don't find error in logs server

**Comment by jix31** [comment]
and here the console screen 
<img width="2560" alt="Capture d’écran 2023-11-24 à 17 15 17" src="https://github.com/PrestaShop/PrestaShop/assets/151663961/632f7f8e-d544-400d-a79b-f58caf5cbd14">
