### ISSUE TITLE
Integrating Stripe Payment Module in PrestaShop API Webserver

### ISSUE THREAD

**Issue by oubihis** [PrestaShop/PrestaShop#34643]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I am encountering an issue while attempting to integrate the Stripe payment module into PrestaShop via the webserver API. Below, I provide details of the problem along with relevant information to facilitate a quick resolution.

**Bug Report Details:**

PrestaShop Version: 1.7.8
Stripe Payment Module Version: v3.1.3
Webserver Environment: Apache
PHP Version: 7.3

**Problem Description:**

When using the PrestaShop API to create orders with the Stripe payment module, I am encountering difficulties in executing successful payments. The exact steps and configurations used are as follows:

_**Create Order**_ 

Api url : /api/orders 
`<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
  <order>
    <id_address_delivery><![CDATA[2]]></id_address_delivery>
    <id_address_invoice><![CDATA[3]]></id_address_invoice>
    <id_cart><![CDATA[60]]></id_cart>
    <id_currency><![CDATA[1]]></id_currency>
    <id_lang><![CDATA[1]]></id_lang>
    <id_customer><![CDATA[1]]></id_customer>
    <id_carrier><![CDATA[2]]></id_carrier>
    <current_state><![CDATA[1]]></current_state>
    <module><![CDATA[stripe_official]]></module>
    <invoice_number><![CDATA[]]></invoice_number>
    <invoice_date><![CDATA[]]></invoice_date>
    <delivery_number><![CDATA[]]></delivery_number>
    <delivery_date><![CDATA[]]></delivery_date>
    <valid><![CDATA[]]></valid>
    <date_add><![CDATA[]]></date_add>
    <date_upd><![CDATA[]]></date_upd>
    <shipping_number><![CDATA[]]></shipping_number>
    <note><![CDATA[]]></note>
    <id_shop_group><![CDATA[]]></id_shop_group>
    <id_shop><![CDATA[1]]></id_shop>
    <secure_key><![CDATA[]]></secure_key>
    <payment><![CDATA[Card via Stripe]]></payment>
    <recyclable><![CDATA[]]></recyclable>
    <gift><![CDATA[]]></gift>
    <gift_message><![CDATA[]]></gift_message>
    <mobile_theme><![CDATA[]]></mobile_theme>
    <total_discounts><![CDATA[]]></total_discounts>
    <total_discounts_tax_incl><![CDATA[]]></total_discounts_tax_incl>
    <total_discounts_tax_excl><![CDATA[]]></total_discounts_tax_excl>
    <total_paid><![CDATA[180.000000]]></total_paid>
    <total_paid_tax_incl><![CDATA[180.000000]]></total_paid_tax_incl>
    <total_paid_tax_excl><![CDATA[180.000000]]></total_paid_tax_excl>
    <total_paid_real><![CDATA[180.000000]]></total_paid_real>
    <total_products><![CDATA[180.000000]]></total_products>
    <total_products_wt><![CDATA[180.000000]]></total_products_wt>
    <total_shipping><![CDATA[]]></total_shipping>
    <total_shipping_tax_incl><![CDATA[]]></total_shipping_tax_incl>
    <total_shipping_tax_excl><![CDATA[]]></total_shipping_tax_excl>
    <carrier_tax_rate><![CDATA[]]></carrier_tax_rate>
    <total_wrapping><![CDATA[]]></total_wrapping>
    <total_wrapping_tax_incl><![CDATA[]]></total_wrapping_tax_incl>
    <total_wrapping_tax_excl><![CDATA[]]></total_wrapping_tax_excl>
    <round_mode><![CDATA[]]></round_mode>
    <round_type><![CDATA[]]></round_type>
    <conversion_rate><![CDATA[180.000000]]></conversion_rate>
    <reference><![CDATA[]]></reference>
    <associations>
      <order_rows>
        <order_row>
          <product_id><![CDATA[1]]></product_id>
          <product_attribute_id><![CDATA[]]></product_attribute_id>
          <product_quantity><![CDATA[1]]></product_quantity>
          <product_name><![CDATA[]]></product_name>
          <product_reference><![CDATA[]]></product_reference>
          <product_ean13><![CDATA[]]></product_ean13>
          <product_isbn><![CDATA[]]></product_isbn>
          <product_upc><![CDATA[]]></product_upc>
          <product_price><![CDATA[]]></product_price>
          <id_customization><![CDATA[]]></id_customization>
          <unit_price_tax_incl><![CDATA[]]></unit_price_tax_incl>
          <unit_price_tax_excl><![CDATA[]]></unit_price_tax_excl>
        </order_row>
      </order_rows>
    </associations>
  </order>
</prestashop>
`

_**Screenshot Order**_ 

![Screenshot 2023-11-21 at 18 35 16](https://github.com/PrestaShop/PrestaShop/assets/29286895/f7322565-1981-402f-ab86-2f9fd5632084)

Request for Assistance:
I am seeking guidance on how to correctly utilize the Stripe payment module within the PrestaShop API for webserver integration. Specifically, I need information on the proper API endpoints, payload format, and any additional configurations required to ensure seamless payment processing.

Additional Notes:

I have thoroughly reviewed the bug report guidelines outlined by the PrestaShop community.
I understand the importance of providing detailed information for effective issue resolution.
Your prompt attention and assistance in resolving this matter would be greatly appreciated. If any additional information is required, please do not hesitate to ask.

Thank you for your time and support.

### Steps to reproduce

1. /api/orders
2. check orders in backoffice

### PrestaShop version(s) where the bug happened

1.7.8.10

### PHP version(s) where the bug happened

7.3

**Comment by hibatallahAouadni** [comment]
Hello @oubihis 

It seems that your issue is not a PrestaShop core bug.
If your module is Stripe Official, please contact support team on Addons

We will close this issue.

Thanks!
