### ISSUE TITLE
Error during instalation with modules selected - Attempted to load RatesHelper - MbeShipping

### ISSUE THREAD

**Issue by MorrowxD** [PrestaShop/PrestaShop#34640]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I've recently noticed an error during presta instalation
https://ibb.co/1qWqzSS

It's only ocurs while "isntall modules" option is selected

### Expected behavior

Walk through installation

### Steps to reproduce

1. Check install modules during installation

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

7.4, 8.0, 8.1

### If your bug is related to a module, specify its name and its version

mbeshipping

**Comment by florine2623** [comment]
Hello @MorrowxD ,

Are you using PrestaShop Edition ?

**Comment by florine2623** [comment]
Hello,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
