### ISSUE TITLE
creation of baskets (5/6 per minute) without log access

### ISSUE THREAD

**Issue by ECC64** [PrestaShop/PrestaShop#34654]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

every minute 5/6 baskets are created in the store, these baskets are 0€, no trace in the logs, I deactivated the Webservices and non-Prestashop modules and that doesn't change anything. There are no CRON jobs running on the server

### Expected behavior

no creation of basket at 0€

### Steps to reproduce

go to BO
go to cart menu

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

**Comment by Hlavtox** [comment]
This does not happen on latest clean version of Prestashop.

So, either it was fixed or some of your modules is causing it.

I suggest updating to 8.1.2 and checking if this behavior continues.

**Comment by paulnoelcholot** [comment]
Hello @ECC64,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you
