### ISSUE TITLE
Unable to add or modify a supplier

### ISSUE THREAD

**Issue by guil14um3** [PrestaShop/PrestaShop#34656]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

It is impossible to add or modify a supplier, I receive the following message during creation:
"An unexpected error occurred. [PrestaShop\PrestaShop\Core\Domain\Supplier\Exception\SupplierException code 0]"

And when I try to edit an already created supplier, I get this message:
"An unexpected error occurred. [PrestaShop\PrestaShop\Core\Domain\Supplier\Exception\SupplierException code 0]"

The modification works directly from the database.
![Capture d'écran 2023-11-23 083934](https://github.com/PrestaShop/PrestaShop/assets/151820052/ff11457b-ed4c-45cc-b5d2-26e3e047b3c8)

### Steps to reproduce

 - Catalog
 - Supplier
 - Add a supplier

### PrestaShop version(s) where the bug happened

8.1.2

### If your bug is related to a module, specify its name and its version

8.1.25

**Comment by florine2623** [comment]
Hello @guil14um3 ,

I can' reproduce your issue in PS 8.1.x :

https://github.com/PrestaShop/PrestaShop/assets/16019289/e01381ad-46f5-412c-a9a2-318d5bd86e19


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
