### ISSUE TITLE
PPV2 - Pricing tab - Can't apply a specific price to a customer in particular

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#34652]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In my product page v2, in the pricing tab, when I add a Specific price, I cannot choose a specific customer.

https://github.com/PrestaShop/PrestaShop/assets/16019289/1ab5e372-902f-4f8b-906d-b4361dc2f1dc

### Expected behavior

The drop down with the list of customers should be displayed and I should be able to choose my customer.

### Steps to reproduce

1. Go to BO > Catalog > Products
2. Edit product > Pricing tab
3. Add a specific price > Disable option "Apply to all customers"
4. Write your customer's name in input field
5. No customer are displayed :x:

### PrestaShop version(s) where the bug happened

8.1.x, develop

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

PS

**Comment by RosaBenouamer** [comment]
I reproduce the issue

**Comment by paulnoelcholot** [comment]
Hello @florine2623,

I reproduce the issue with PrestaShop version 8.1.x and develop, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by MatShir** [comment]
Closed by https://github.com/PrestaShop/PrestaShop/pull/34699
