### ISSUE TITLE
Prestashop Checkout : PayPal button issue

### ISSUE THREAD

**Issue by acidlavaa** [PrestaShop/PrestaShop#34651]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

I have configured PayPal using the Prestashop Checkout module. The issue is that the "Pay with PayPal" button is displayed by default at the payment stage, even if credit card payment is selected or no method at all. Any suggestions on how to make it appear only when PayPal payment is selected? Thanks.

<img width="681" alt="Capture d’écran 2023-11-22 à 11 32 04" src="https://github.com/PrestaShop/PrestaShop/assets/151734296/15525783-50c5-40de-aef8-71973e647c11">
<img width="696" alt="Capture d’écran 2023-11-22 à 11 31 58" src="https://github.com/PrestaShop/PrestaShop/assets/151734296/eb2951ec-9e74-4cb5-a537-fbb1bb7ac0be">

### Expected behavior

Button should appear only when PayPal method is selected.

### Steps to reproduce

Install PayPal with Prestashop Checkout
Add a product to the basket
Proceed to checkout
See the payment methods

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

8

### If your bug is related to a module, specify its name and its version

Prestashop Checkout

**Comment by hibatallahAouadni** [comment]
Hello @acidlavaa 

It seems that your issue is not a PrestaShop core bug.
If your module is PayPal Official, please contact support team on Addons

We will close this issue.

Thanks!

**Comment by acidlavaa** [comment]
I contacted the support team and they redirected me here. We talk about the module Prestashop Checkout so... It includes PayPal, yes.
