### ISSUE TITLE
Newsletter Module not Working

### ISSUE THREAD

**Issue by jlmartincoffee** [PrestaShop/PrestaShop#34657]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I access https://shop.cafescornella.coffee/ca/, I enter my email on this form: 
![imagen](https://github.com/PrestaShop/PrestaShop/assets/151830289/02a960bc-2485-44fd-ac1a-88717551dd85)
And I have the module configured like this:
![imagen](https://github.com/PrestaShop/PrestaShop/assets/151830289/caeb2a1d-a0f4-4ffd-91ba-ad48ec327dd5)
I don't receive any emails. If i make a test here:
![imagen](https://github.com/PrestaShop/PrestaShop/assets/151830289/23ed88ae-3f95-4a61-b497-b3fc02032a88)
I receive the email. So the problem should come from the module.

### Expected behavior

People should recieved an email when suscribes. Also I have an integration with mailchimp, but i would like to have this module working before.

### Steps to reproduce

1. Go to https://shop.cafescornella.coffee/ca/
2. Enter your email on the footer page form.
3. See on your email how you receive nothing.

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.2.16-1+ubuntu16.04.1+deb.sury.org+1 

### If your bug is related to a module, specify its name and its version

Subscription to newsletter v2.7.1

### Your company or customer's name goes here (if applicable).

CofeCompany

**Comment by florine2623** [comment]
Hello @jlmartincoffee ,

You need to contact your server provider to get all the info you need to configure your email.

Thanks!

**Comment by jlmartincoffee** [comment]
@florine2623  If I go to Avanced Parameters > Email, and I make a test, I receive the email, so the problem doesn't come from my server provider. The email is already correctly configured.
