### ISSUE TITLE
[FO] - Autoupgrade 1.7.6.9 to 8.1.2 there is the policy that doesn't know it position 

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#34664]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When we do an autoupgrade from 1.7.6.9 to 8.1.2 we've the FO like this : 

![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/11fda379-7b6e-4052-b7bf-391b9eb9ae34)

![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/73d85916-d2f0-406b-bf2f-db444b673796)

![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/7acd8161-df98-4a31-b7e6-1d6cdd26f8e3)

-----------------
For this one, I don't know if it's the good position because there are everywhere : 
![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/174946f7-c463-4785-9e85-4b27a2550299)

### Expected behavior

I wish "Security policy", "Delivery policy" and "Return policy" know there position 

### Steps to reproduce

1. fresh install Prestashop 1.7.6.9 
2. Go to the Module > Marketplace and install 1-Click-Upgrade (autoupgrade) 
3. Clic on Configure 
4. On the expert mode, select major release 
5. Launch the Autoupgrade 
6. After the installation go to your FO 
7. Boom, Policy everywhere !

### PrestaShop version(s) where the bug happened

1.7.6.9 -> 8.1.2

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

Autoupgrade 4.16.4

### Your company or customer's name goes here (if applicable).

PS

**Comment by florine2623** [comment]
Hello @AureRita ,

I have reproduced your issue with an upgrade from 1.7.6.9 to 8.1.2 :
<img width="1440" alt="Screenshot 2023-11-24 at 11 24 17" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/856e93f2-3157-4014-a4b6-216f0b118321">
<img width="985" alt="Screenshot 2023-11-24 at 11 24 22" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/74752768-a7e3-4f5b-8eb1-245389fd66d6">
<img width="1071" alt="Screenshot 2023-11-24 at 11 24 29" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/85018072-27fc-46c1-8f09-4e0ad260c5ce">


I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by ga-devfront** [comment]
I try to reproduced this issue with 1.7.8.9 to 8.1.5 but I can't.
Any know if this issue is already fixed (from the module or from the autougprader)
@AureRita

**Comment by AureRita** [comment]
I try it Again and currently I can't reproduce it anymore so I'll close the issue
