### ISSUE TITLE
Undefined array key 0 in Subject select input

### ISSUE THREAD

**Issue by NicolasCador** [PrestaShop/PrestaShop#34672]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you send a message through the PO in BO, then you send a new message trough Customer Service in BO, there is an error in Subject select input.

### Expected behavior

It should write "Customer service" or "Webmaster"

### Steps to reproduce

Open an Order in BO
Send a message to customer
Open Customer Service/Customer Service tab in BO
Send a new message concerning this Order
Open the customer e-mail, follow the link to answer
It opens the Contact us page
There is an error in the Subject select input

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

contactform

**Comment by florine2623** [comment]
Hello @NicolasCador ,

What is PO ?

**Comment by NicolasCador** [comment]
Hello @florine2623,

it's Purchase Order

**Comment by NicolasCador** [comment]
I updated Steps to reproduce

**Comment by Arababer** [comment]
Hello, @NicolasCador 

I reproduce the issue with PrestaShop version 8.1.x, and the module contact form v4.4.1. I'll add this to the backlog so it can be fixed.
![Screenshot 2023-11-27 at 15 51 45](https://github.com/PrestaShop/PrestaShop/assets/152183599/36601bb3-a57f-4437-9fa6-bc975d3e0fda)

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project's own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
