### ISSUE TITLE
Front controller called in cli is blocked by ssl redirection and maintenance mode

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#34670]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Look at this https://devdocs.prestashop-project.org/8/modules/concepts/controllers/front-controllers/#using-a-front-controller-as-a-cron-task
A cron task in cli can be blocked by ssl redirection and maintenance mode

### Expected behavior

cli not blocked.
This PR allow front controller like crons tu be launched indifferently by http or by cli.

### Steps to reproduce

1. Call a front controller in CLI directly with php like explained in the doc : php patch/myscript.php
2. Activate SSL and Maintenance mode
3. The command doesn't works

### PrestaShop version(s) where the bug happened

1.7, 8, develop

### PHP version(s) where the bug happened

all

### Your company or customer's name goes here (if applicable).

Creabilis

**Comment by florine2623** [comment]
Can this be tested by @PrestaShop/prestashop-core-developers  ?

**Comment by matks** [comment]
Hello @jf-viguier if I am not wrong, the documentation explains a workaround for modules that want to run scripts in a similar way than CLI for old 1.7 versions.

But your PR targets PS 9.0.0 https://github.com/PrestaShop/PrestaShop/pull/34671 . It looks wrong? In PS 9.0.0 we can have proper CLI Commands, and we do not need to rely on fake-CLI front controllers?

**Comment by jf-viguier** [comment]
Yes, but old way has not been deprecated. So It can be relevant to version 9.
BTW, with direct cron blocked by htaccess, module developers that target 1.7,8 and 9 don't have to it manage several ways.

**Comment by jf-viguier** [comment]
I've done a PR for 8.1 https://github.com/PrestaShop/PrestaShop/pull/34698

**Comment by matks** [comment]
Fixed on 8.1.x https://github.com/PrestaShop/PrestaShop/pull/34698/

**Comment by matks** [comment]
@prestashop-issue-bot No believe me it's really fixed 👍
