### ISSUE TITLE
Message "The geolocation database is unavailable." while GeoLite2-Country.mmdb is present

### ISSUE THREAD

**Issue by Fr3dJa** [PrestaShop/PrestaShop#34679]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When attempting to activate the geolocalization by IP address, the message "The geolocation database is unavailable." when saving while GeoLite2-Country.mmdb is present in the /app/Resources/geoip/ directory

### Expected behavior

I'm expecting the the geolocalization by IP address to be activated

### Steps to reproduce

1. upload GeoLite2-Country.mmdb in the /app/Resources/geoip/ directory
2. go to International -> Localization -> Geolocation
3. Set Geolocation by IP address slider to Yes
4. Save
5. Message "The geolocation database is unavailable." is displayed

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1.25

**Comment by Hlavtox** [comment]
@Fr3dJa Filename must be `GeoLite2-City.mmdb`

**Comment by Fr3dJa** [comment]
> @Fr3dJa Filename must be `GeoLite2-City.mmdb`

Oh, I see. Thanks a lot, no issue with this file indeed.
May i suggest a cleanup in the documentation?

**Comment by Arababer** [comment]
hello @Fr3dJa 
yes the repository of the documentation is here https://github.com/PrestaShop/docs 
thanks
