### ISSUE TITLE
PS8.1 Fatal Error on order validation process

### ISSUE THREAD

**Issue by BideoGemu** [PrestaShop/PrestaShop#34681]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Prestashop usage : 
- Multistore with orders, carts and customers sharing.
- Store A is default store and B, C, D ... are other stores.
- All stores have differents products, products from store A aren't in others stores, and it's the same for all other stores.
- Customers can add to cart all products for store A and just one another store to make just one order.
- Store B to Z are under .htpasswd

===================================================================

When customer order products with product from store A and store B I have this error : 

```2023/11/26 11:13:11 [error] 9#9: *300171 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught InvalidArgumentException: "" cannot be interpreted as a number in /var/www/vendor/prestashop/decimal/src/Builder.php:37
Stack trace:
#0 /var/www/vendor/prestashop/decimal/src/DecimalNumber.php(73): PrestaShop\Decimal\Builder::parseNumber()
#1 /var/www/src/Core/Localization/Number/Formatter.php(147): PrestaShop\Decimal\DecimalNumber->__construct()
#2 /var/www/src/Core/Localization/Number/Formatter.php(106): PrestaShop\PrestaShop\Core\Localization\Number\Formatter->prepareNumber()
#3 /var/www/src/Core/Localization/Locale.php(154): PrestaShop\PrestaShop\Core\Localization\Number\Formatter->format()
#4 /var/www/classes/PaymentModule.php(453): PrestaShop\PrestaShop\Core\Localization\Locale->formatPrice()
#5 /var/www/modules/ps_wirepayment/controllers/front/validation.php(63): PaymentModuleCore->validateOrder()
#6 /var/www/classes/controller/Controller.php(308): Ps_WirepaymentValidationModuleFrontController->postProcess()
#7 /var/www/classes/Dispatcher.php(510): Co" while reading response header from upstream, client: *.*.*.*, server: ***, request: "POST /module/ps_wirepayment/validation HTTP/1.1", upstream: "***", host: "***", referrer: "https://***/index.php?controller=order"
```
(I have hidden the IP addresses for confidentiality)

The order is saved on DB, but there is no order state associated. 

![Order screenshot](https://github.com/PrestaShop/PrestaShop/assets/71313676/efcbf096-a6ee-4a56-80b2-58a2d0916cc3)

I tried 3 order on differents stores, and same issue for all of them, and we have 2 order from customers with the same issue.

This issue occurs only if customer order products from differents stores.

If products aren't in default store and when cart is shared between stores I think "$product_price" get only default store and can't find product price because default store don't know it. 

===================================================================

Tests I've made : 
- Add products from Store A and Store B in my cart
- Try to order them from Store B
- I've got the error I paste

I've tried the same process with store C & D.

Customer behavior : 
- Add products from Store A and Store B in the cart
- Try to order them from Store A
- Same error

Other customer behaviors : 
- Add products from Store A in the cart
- Try to order them from Store A
- No error
OR
- Add products from Store B in the cart
- Try to order them from Store B
- No error
OR
- Add products from Store [x] in the cart
- Try to order them from Store [x]
- No error

### Expected behavior

Not null price informations and add order state.

### Steps to reproduce

1. Enable multistore and cart sharing
2. Create product on store A and another one in store B
3. Add the 2 products on cart
4. Order them

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.1.18

**Comment by florine2623** [comment]
Hello @BideoGemu ,

I can't reproduce your issue.

My 2 shops are on different URL, so the carts are on a different URL.

If the products are shared between shop, they do not belong to one shop in particular.

Could you specify the configuration of the multistore ? and the product on each store ?

**Comment by BideoGemu** [comment]
Hello @florine2623, thank for your answer, as I said in my initial message, products are NOT shared between the store, only carts and customers.

For multistore configuration:
- 15 different stores
- Only one group
- 15 subdomains
- Different products on all stores, not shared
- Shared carts
- Shared clients

For products: I have different types of products, with or without attributes, and each product belongs to a particular store, customers cannot add my mug to the cart of store B if they are in store A, this product is only on store B. But customers can go to store B to add products, and they can add products from store A in the same cart and with this cart they can place an order in store A or B (in facts customers often order from the last store where they added products).

**Comment by florine2623** [comment]
If the product are not shared, how do you add 2 products from different stores in the same cart ?

Could you send a screen record please ?

**Comment by paulnoelcholot** [comment]
Hello @BideoGemu,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
