### ISSUE TITLE
Bug with the associated product

### ISSUE THREAD

**Issue by dngraphisme** [PrestaShop/PrestaShop#34694]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If the associated products (**on quickview**) have a combination with combination IDs (name="") greater than the combination IDs (name="") of the current product

### Expected behavior

Change the variation of the associated product

### Steps to reproduce

Steps: 

1st : product, combination with sizes
![image-1](https://github.com/PrestaShop/PrestaShop/assets/5530905/e7a0e671-ae68-4841-a5a4-2a92fe832ff8)

----

2nd : product combination with colors in quick view modal the attribute of the associated product can't be changed
![image-2](https://github.com/PrestaShop/PrestaShop/assets/5530905/d5fdc86a-8781-464b-85b7-b9bf1ff8d9e9)

----

3nd : the associated product does not have the correct product_variants checked. 
![image-4](https://github.com/PrestaShop/PrestaShop/assets/5530905/b96b81b0-bd39-4056-8483-9a5d252a33d5)

----

You must modify the request to simply send the group[] of the correct product and not both: The parent product and the associated product

### PrestaShop version(s) where the bug happened

1.7.8.10 / 8.1

### PHP version(s) where the bug happened

7.4

### Your company or customer's name goes here (if applicable).

Kosmo

**Comment by dngraphisme** [comment]
To fix the problem in core.js, modified product.js line 121 with .last(); :

`const $productActions = $(prestashop.selectors.product.actions).last();`

**Comment by matks** [comment]
Hello I attempted to reproduce the bug but I did not see any issue.

- I used a product A with combinations A1 and A2
- I used a product B with combinations B1 and B2
- I verified ID of product B are higher than product A
- Using the Back-office product page V2, I marked that Product B is an "associated product" for product A

Then I go to the front-office page of product A, and I see the product B marked as "associated":

![Capture d’écran 2023-11-28 à 15 07 55](https://github.com/PrestaShop/PrestaShop/assets/3830050/244d2236-cc55-4701-823a-8d9c9e7ed1ef)

But if I click on any of the links, to combinations B1 or B2 it works. I do not see a wrong behavior.

**Comment by Gryndel-webrd** [comment]
> Hello I attempted to reproduce the bug but I did not see any issue.
> 
>     * I used a product A with combinations A1 and A2
> 
>     * I used a product B with combinations B1 and B2
> 
>     * I verified ID of product B are higher than product A
> 
>     * Using the Back-office product page V2, I marked that Product B is an "associated product" for product A
> 
> 
> Then I go to the front-office page of product A, and I see the product B marked as "associated":
> 
> ![Capture d’écran 2023-11-28 à 15 07 55](https://private-user-images.githubusercontent.com/3830050/286278635-244d2236-cc55-4701-823a-8d9c9e7ed1ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExODQ4NDMsIm5iZiI6MTcwMTE4NDU0MywicGF0aCI6Ii8zODMwMDUwLzI4NjI3ODYzNS0yNDRkMjIzNi1jYzU1LTQ3MDEtODIzYS04ZDljOWU3ZWQxZWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjhUMTUxNTQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTMzNzBlYmY5YTY5ZDcwMDRmNGVkMjM4YjA2MjE5YTY3YmE2MWIyY2NiMDc5ZDY5NWE4NjYxZWFiNzc4YjZhOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pmyp3DpuwyKARBW7XSUdk0auP1L21qUXzr3j0rCM1A4)
> 
> But if I click on any of the links, to combinations B1 or B2 it works. I do not see a wrong behavior.

Did you check in the modal ? it's a bug when I click on combination in modal

**Comment by SharakPL** [comment]
Could you maybe provide a screen recording for better understanding of the issue?

**Comment by Gryndel-webrd** [comment]
[screen-recorder-tue-nov-28-2023-19-14-26.webm](https://github.com/PrestaShop/PrestaShop/assets/5007456/ea780a7a-1cae-4611-a165-80f406a78eb1)

**Comment by SharakPL** [comment]
please add your video directly in the post :)

**Comment by matks** [comment]
OK I can reproduce the 1st problem using the following scenario

1. I used a product A with combinations A1 and A2
2. I used a product B with combinations B1 and B2
3. I verified ID of product B are higher than product A
4. Using the Back-office product page V2, I marked that Product B is an "associated product" for product A
5. Then I go to the front-office page of product A, and I see the product B marked as "associated". It's written in a part "YOU MIGHT ALSO LIKE"
6. I click on "Quickview" to open the modal of product B (I am still on the page of product A)
7. I cannot select another combination. If it is a tshirt I can order in black or white, clicking the black color does not work.

> 3nd : the associated product does not have the correct product_variants checked.

This however I do not understand yet.

<hr>

Please note I verified on PrestaShop 9.0.0 (develop branch) ; the above bug is fixed 😉 . But we could fix it on 8.1 anyways.

**Comment by AureRita** [comment]
Hi @dngraphisme ,

Thank you for your report, I reproduce the issue with PrestaShop version 8.1.x, as you can see : 

[Untitled_ Dec 5, 2023 11_02 AM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/759f559b-0867-4b14-8721-780aff883b54)


I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

Thank you for your PR :rocket: 

Thanks
