### ISSUE TITLE
FO - Product with 0 quantity show us a date with : 0000-00-00

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#34692]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I create a new product with 0 quantity, If I go to the FO and check this one, we'll have a Available date : 0000-00-00 as you can see : 

![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/be69b81f-2a54-4ac2-8eef-9bc9a2441cec)

### Expected behavior

We expected that if we don't put a date, the available date shouldn't be show, and if there is no product detail, this tab shouldn't be show.

### Steps to reproduce

1. Go to BO 
2. Go to Catalog > Products
3. Clic on New Product 
4. Clic on Standard Product 
5. Clic on Add new Product 
6. Set a title 
7. Put it Online 
8. Save it 
9. Go to FO 
10. Check you product 
11. :negative_squared_cross_mark: You'll have the available date with many 0

### PrestaShop version(s) where the bug happened

8.1.x - develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

None 

### Your company or customer's name goes here (if applicable).

PS

**Comment by Hlavtox** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/34695
