### ISSUE TITLE
Original product image converted to WebP if set Image format: Use WebP for all images.

### ISSUE THREAD

**Issue by Codencode** [PrestaShop/PrestaShop#34705]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you upload a product image with the following settings:

- Advanced Parameters > New & Experimental Features > Multiple image formats: DISABLED
- Design Image Settings > Image Settings > Image format: Use WebP for all images.

![Screenshot - New   Experimental Features - 1](https://github.com/PrestaShop/PrestaShop/assets/2463965/51652517-b2e1-4664-afab-5a8d04acf12f)
![Screenshot - Image Settings - 1](https://github.com/PrestaShop/PrestaShop/assets/2463965/f6dc58da-5719-413d-94e5-01436059fd6f)

the system also compresses the original image in WebP, ERROR

When you upload a product image with the following settings:

- Advanced Parameters > New & Experimental Features > Multiple image formats: ENABLED
- Design Image Settings > Image Settings > Image formats to generate: WebP, AVIF
- Design Image Settings > Image Settings > Base format: Use JPEG
![Screenshot - New   Experimental Features - 2](https://github.com/PrestaShop/PrestaShop/assets/2463965/5bc40d55-8024-495e-a3a4-27e44af7d390)
![Screenshot - Image Settings - 2](https://github.com/PrestaShop/PrestaShop/assets/2463965/30ca3ab4-0285-4065-8726-3bf557558385)

the system does not convert the original image to WebP, CORRECT

Video:
https://github.com/PrestaShop/PrestaShop/assets/2463965/5efb77b4-c28b-40f7-8a68-e1aede3f32e5

### Steps to reproduce

1. Go to Advanced **Parameters > New & Experimental Features** and set **Multiple image formats** to **Disabled**
2. Go to **Design Image Settings > Image Settings** and set **Image format** to **Use WebP for all images**
3. ​Upload an image of a product
4. The original file is of type WebP

### PrestaShop version(s) where the bug happened

8

### PHP version(s) where the bug happened

all

**Comment by Hlavtox** [comment]
@Codencode I will be honest, the original implementation of webp is not very good. I suggest avoid using it and jumping into the new image management. 👍

**Comment by Codencode** [comment]
@Hlavtox,
OK thank you.

However, if you use this configuration you will find yourself with the original images converted to WebP and therefore in the event of regeneration the system would use the WebP images as a starting point.

**Comment by florine2623** [comment]
Hello @Codencode ,

I'm not sure I understand the issue.

Following your steps, I see that the product image is still in JPG.
Is that the issue ?

https://github.com/PrestaShop/PrestaShop/assets/16019289/34ed4de2-379e-4136-a24c-bf631fc423e7

**Comment by Hlavtox** [comment]
@florine2623 

To reproduce:
- Use 8.1.x
- Disable multiple images feature flag
- Set image settings to “Use webp”
- Upload image to a product
- Check the original image in /img/p/somenumbers/imageid.jpg
- You will see that the image is jpg extension, but webp inside. You can use this website to check the format - https://www.checkfiletype.com/

It will be fixed with my PR I linked, for develop branch. :-)

**Comment by florine2623** [comment]
Hello @Codencode @ @Hlavtox ,

Yes I have reproduced the issue on develop ^^

<img width="760" alt="Screenshot 2023-12-07 at 15 57 11" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/5b866ec7-6944-481c-aa86-5a588ecdf01a">


Thanks or the details !

**Comment by MatShir** [comment]
closed by https://github.com/PrestaShop/PrestaShop/pull/34172
