### ISSUE TITLE
Duplicated threads customer service

### ISSUE THREAD

**Issue by Astalyos** [PrestaShop/PrestaShop#34703]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When customer send a message through the contact us form in the contact us page, create duplicated threads instead of one 

### Expected behavior

Create a customer thread but only one, without duplicate

### Steps to reproduce

Not happening all the time, but most of the time
1. Go to contact us page
2. Send the form
3. Sometimes it will create double threads

### PrestaShop version(s) where the bug happened

1.7.7.1

### PHP version(s) where the bug happened

7.3

**Comment by paulnoelcholot** [comment]
Hello @Astalyos,

Version 1.7.7.x is unfortunately no longer maintained. We invite you to upgrade to version 8.1.x
