### ISSUE TITLE
PS9 - Missing Main menu for iPad Pro 

### ISSUE THREAD

**Issue by szavadskiy** [PrestaShop/PrestaShop#34706]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

iPad Pro is a good tool to manage the BO, but have specific browser.
On iPad Pro missing main menu and menu button like for mobile browsers
![Screenshot from 2023-11-28 09-52-50](https://github.com/PrestaShop/PrestaShop/assets/90208051/43d7e095-b8bd-4702-bb49-57389ade9ca7)

See video:

https://github.com/PrestaShop/PrestaShop/assets/90208051/5aa89bdd-fe10-41ca-80aa-e0854f834b17

Ok with other iPads

### Expected behavior

Main menu exist or main menu button like for mobile 

### Steps to reproduce

1. open PS BO in iPad Pro 
2. check main menu

### PrestaShop version(s) where the bug happened

9.0/8.x/1.7.8.X

### PHP version(s) where the bug happened

8.1 / 7.4

**Comment by paulnoelcholot** [comment]
Hello @szavadskiy,

I can't reproduce your issue, did I miss something?

![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/cb9d2934-b714-4982-90f6-b0498b73fc2f)

Thanks for your feedback!

**Comment by szavadskiy** [comment]
Hello @paulnoelcholot thank you for answer  
I checked also PS 8.0.4 
On my side issue reproducing on screen with resolution 1920 * 1080 
and not reproducing on screen with resolution 1440 ' 900

**Comment by florine2623** [comment]
I do not reproduce any of the issue mentioned :/

iPad Pro, 1920 * 1080 and 1440 * 900. On 9.0.x and 8.1.x.


https://github.com/PrestaShop/PrestaShop/assets/16019289/d902de23-c0ef-4b0e-8be5-d1259ed8b690


I'm closing the issue as none of us could reproduce it ^^
