### ISSUE TITLE
Module relancez vos clients 

### ISSUE THREAD

**Issue by Souclem44** [PrestaShop/PrestaShop#34701]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Good morning,
I installed the Relaunch your customers module. The emails are not sent automatically, although I have set a cron task as requested in the module. thank you in advance for your help

### Steps to reproduce

Allez sur le module relancez vos clients 

### PrestaShop version(s) where the bug happened

1751

### If your bug is related to a module, specify its name and its version

Relancez vos clients

**Comment by venditdevs** [comment]
@Souclem44 Please submit your ticket in English, it's the norm here so that everyone can help you.

**Comment by paulnoelcholot** [comment]
Hello,

We are aware of this issue, it is already in our debug backlog. This issue is a duplicate of #34710.
To be informed when it's fixed, please subscribe to the issue mentioned above.

Thank you

**Comment by paulnoelcholot** [comment]
Duplicate of #34710
