### ISSUE TITLE
Script admin/init.php fails on develop

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#34717]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Script [admin/init.php](https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/init.php) fails on develop with error

```
Fatal error: Uncaught Error: Undefined constant "FRONT_LEGACY_CONTEXT" in /Users/mFerment/www/prestashop/PrestaShop/classes/controller/FrontController.php:2085 Stack trace: #0 /Users/mFerment/www/prestashop/PrestaShop/classes/controller/Controller.php(215): FrontControllerCore->buildContainer() #1 /Users/mFerment/www/prestashop/PrestaShop/classes/controller/FrontController.php(242): ControllerCore->init() #2 /Users/mFerment/www/prestashop/PrestaShop/init.php(31): FrontControllerCore->init() #3 /Users/mFerment/www/prestashop/PrestaShop/modules/ps_imageslider/ajax_ps_imageslider.php(23): include_once('/Users/mFerment...') #4 {main} thrown in /Users/mFerment/www/prestashop/PrestaShop/classes/controller/FrontController.php on line 2085
```

This is because of PR https://github.com/PrestaShop/PrestaShop/pull/32719/

### Expected behavior

The script should not fail although I do not know what is his purpose

### Steps to reproduce

It is possible to observe the problem with current ps_imageslider module.

1. Install PrestaShop from `develop` branch
2. Go to back-office and click on "Configure" button of ps_imageslider module in Module Manager
3. Use the back-office page to drag-and-drop slides, and update their position. See error in "Network" tab of the developer console.

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
ping @PrestaShop/qa-functional ,

Can someone reproduce this ?

On my end, I can't :

https://github.com/PrestaShop/PrestaShop/assets/16019289/83e2a179-5831-49c9-a42d-7639d8f447dd

**Comment by matks** [comment]
Ah, you have errors 403 Forbidden because of PR https://github.com/PrestaShop/PrestaShop/pull/34184

**Comment by florine2623** [comment]
Is there another way to verify the issue ?

**Comment by AureRita** [comment]
Hi @matks 

Thank you for your report, I try to reproduce your issue as you can see : 

[Untitled_ Nov 29, 2023 4_28 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/4bfdc1fb-5603-411f-a6f8-ebadabb82783)

so currently I have the same behavior of @florine2623, moreover, I install my 9.0.0, 20 minutes ago

Waiting for your feedback

**Comment by matks** [comment]
It is currently impossible to test this issue on 9.0.0 without modifying the source code
Because of PR [#34184](https://github.com/PrestaShop/PrestaShop/pull/34184) 😄

**Comment by florine2623** [comment]
I managed to reproduce the issue :

![Screenshot 2023-12-05 at 11 36 39](https://github.com/PrestaShop/PrestaShop/assets/16019289/1e0bcc0b-dec7-4536-9e3e-528d9a9f7e69)
