### ISSUE TITLE
SEO, product keywords present but empty content <meta name="keywords">

### ISSUE THREAD

**Issue by TibreFR44** [PrestaShop/PrestaShop#34711]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,
When I declare product keywords and description for the SEO, they are recorded but keywords are not present in the content \<meta name="keywords"\> tag. description is okay in the content \<meta name="description"\>. Clear cache does not update the meta. 

### Steps to reproduce

1. Go to the "Products" panel ;
2. Select a product ;
3. Select the “SEO” tab ;
4. Enter "Keywords" and save ;
5. Go to the product HTML page on the store ;
6. Request the source page (CTRL+U on Google Chrome) ;
7. Search for meta name="keywords". The "content" attribut is empty.

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1.26

**Comment by Hlavtox** [comment]
@TibreFR44 Keywords field controls the tags assigned to the product, they are used in shop search or modules.

Meta keywords themselves are dead for more than 20 years and they will be removed from the software completely.

**Comment by venditdevs** [comment]
Meta Keywords are no longer used by the most search engines. So don't waste your time on that. Only use it for the internal search optimalisation of the webshop itself.

**Comment by florine2623** [comment]
ping @PrestaShop/product-council 
Can this issue be closed ?
