### ISSUE TITLE
Relaunch your customers

### ISSUE THREAD

**Issue by Souclem44** [PrestaShop/PrestaShop#34710]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Good morning,
I installed the Relaunch your customers module. The emails are not sent automatically, although I have set a cron task as requested in the module. thank you in advance for your help

### Expected behavior

Relaunch your customers

### Steps to reproduce

Relaunch your customers

### PrestaShop version(s) where the bug happened

1751

### PHP version(s) where the bug happened

1751

### If your bug is related to a module, specify its name and its version

Relaunch your customers

**Comment by Hlavtox** [comment]
@Souclem44 What is `Relaunch your customers`? :-)

**Comment by paulnoelcholot** [comment]
Hello @Souclem44,

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Thank you

**Comment by Souclem44** [comment]
Bonjour,
Un technicien de prestashop m'a dit de vous contacter.
Cordialement
Mme Sourice

**Comment by paulnoelcholot** [comment]
(Message in French to simplify communication with the contributor)

Bonjour @Souclem44,
Je me permet de vous répondre en français (contrairement à la politique de l'entreprise) car il me semble que cela va simplifier la communication. Vous venez de répondre en commentaire et non au support PrestaShop. Si vous cliquer sur ce lien : [Get help with PrestaShop](https://www.prestashop-project.org/support/). vous aurez accès à la page PrestaShop qui vous propose les différentes solutions pour trouver une solution à votre problème (poser la question à la communauté, bénéficier d'un support PrestaShop (payant) etc...). Je peux vous conseiller également de vous rediriger vers la personne qui a mis en place votre boutique PrestaShop (si il ne s'agit pas vous).
