### ISSUE TITLE
Module updates broken on develop

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#34728]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Module updates are broken on develop branch in some cases. See steps to reproduce and the go back here.

### Workflow
- `C:\xampp\htdocs\dev\src\Core\Module\ModuleManager.php::upgradeMigration` calls `Module::initUpgradeModule` which tells it if there is a module upgrade available and loads upgrade data. 
- So let's go inside `Module::initUpgradeModule` method. It preloads `static::$modules_cache[$module->name]['upgrade']` with empty data, including `number_upgraded` counter. 
- Right after that, it calls `Module::needUpgrade` ➡️  `Module::getInstanceByName($module->name)` ➡️ `Module::coreLoadModule($module_name);` and by calling `ServiceLocator::get($module_name);`, it wipes the static data for some reason.
- So `static::$modules_cache[$module->name]['upgrade']['upgraded_from'] = $module->database_version;` set in `Module::needUpgrade` is maybe useless.
- Then, it loads this list partially back in `$module->loadUpgradeVersionList`, but without those default empty keys.
- Now, back to ModuleManager and runUpgradeModule call - we don't have `number_upgraded` in that data.

### Steps to reproduce

1. Get develop
2. Install https://github.com/PrestaShop/gsitemap/releases/tag/v4.3.0
3. Clone following branch https://github.com/ShaiMagal/gsitemap/tree/dev
4. Go to backoffice and try to update the module.
5. 🔴 See error `Cannot update module gsitemap. Warning: Undefined array key "number_upgraded"`

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello @Hlavtox ,

Following until step 4, I don't have the option to update the gsitemap module in the BO ^^'

<img width="331" alt="Screenshot 2023-12-04 at 12 29 56" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/8a2c4703-8a8b-409b-85b2-de58d8a5e925">

<img width="1078" alt="Screenshot 2023-12-04 at 12 30 04" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/fac38429-8e60-42be-a941-7cf62f32daf0">

Am I missing something ?

**Comment by Hlavtox** [comment]
@florine2623 Yes, probably a cache issue. :( But I think that enough QA is if you try to update any other module. :-) Or try a zip file.

**Comment by florine2623** [comment]
I have reproduced the issue :

<img width="661" alt="Screenshot 2023-12-05 at 14 59 46" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/ad3cb8ad-fdea-4c67-a9b5-f452b049ed36">

**Comment by Hlavtox** [comment]
Good! Florine, what about you test the PR https://github.com/PrestaShop/PrestaShop/pull/34731
and also the gsitemap autoupgrade? You would know how to reproduce and verify the PR. :-)

**Comment by Hlavtox** [comment]
Also, this issue doesn't happen on 8.1.x? I didn't check. If yes, I could change the pr target branch. :-)

**Comment by AureRita** [comment]
I didn't reproduce it on 8.1.x but I can reproduce this one in develop
