### ISSUE TITLE
Mobile ajax cart wont update (no problem on dektop) prestashop 8.1.2

### ISSUE THREAD

**Issue by revartov** [PrestaShop/PrestaShop#34734]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you go on my online store with dektop then its working great. Adding products to the cart is okey.

When you are going to there on mobile, then that is not going to update cart. We can see the products on the cart ONLY when we add to the cart and then refresh the page.

### Expected behavior

It has to update after add to cart is clicked. Right now we havet to do it manually.
We use classic theme and no module is harm this because we installed fresh presta with no modules at all at first place and tested everything after installing modules 1 by 1

### Steps to reproduce

1. Go to www.proparts.ee/varuosad

2. Scroll down and select some category like in first section (filters)

3. Add product to cart and you see the issue.

PS. Desktop working great. On mobile theres that issue.

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

7.4

**Comment by Hlavtox** [comment]
You have a custom module for adding things to cart, it works on clean Prestashop
