### ISSUE TITLE
Non riesco a modificare/aggiornare i prodotti

### ISSUE THREAD

**Issue by ghost** [PrestaShop/PrestaShop#34735]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

![Cattura](https://github.com/PrestaShop/PrestaShop/assets/152481513/26ecbd2a-0890-43a6-aaa0-eccd339c7ef3)
Quando vado a modificare un prodotto mi dice impossibile perché il campo descrizione italiano non è valido

### Expected behavior

Devo modificare un prodotto testi e descrizioni ma non mi fa salvare le modifiche. Ho provato acnhe a duplicare ma non fi fa modificare, ho eliminato le lingue ma rimane il problema

### Steps to reproduce

1 catalago
2 prodotti
3 modifica/duplica
4inserisci cambiamenti
5 salva

### PrestaShop version(s) where the bug happened

1.7.5.2 

### PHP version(s) where the bug happened

7.1.33

### Your company or customer's name goes here (if applicable).

Sca Il Noceto

**Comment by paulnoelcholot** [comment]
Hello @RicFra75,

Please send your request in English. English is the norm on GitHub.

Thank you

**Comment by ghost** [comment]
When I go to modify a product it tells me impossible because the Italian description field is not valid

Expected behavior
I need to edit a product's texts and descriptions but it won't let me save the changes. I tried to duplicate but it doesn't let me edit, I deleted the languages but the problem remains

Steps to reproduce
1 catalogue
2 products
3 edit/duplicate
4insert changes
5 saves

PrestaShop versions where the bug occurred
1.7.5.2

Versions of PHP where the bug occurred
7.1.33

If your bug is related to a module, specify its name and version
No reply

Your company or client name goes here (if applicable).
Sca Il Noceto
![Cattura](https://github.com/PrestaShop/PrestaShop/assets/152481513/59941a93-a913-425b-84af-23ff34c343ce)
