### ISSUE TITLE
partially refund

### ISSUE THREAD

**Issue by huyhoang8398** [PrestaShop/PrestaShop#34744]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I am trying to partially refund and I am getting this message

```
Type error: Argument 3 passed to PrestaShop\PrestaShop\Core\Domain\Order\Command\IssuePartialRefundCommand::__construct() must be of the type string, null given, called in /httpdocs/www/storage-accessories.agilebio.com/src/Core/Form/IdentifiableObject/DataHandler/PartialRefundFormDataHandler.php on line 80
[Symfony\Component\Debug\Exception\FatalThrowableError 0]
```

### Expected behavior

No error

### Steps to reproduce

1. Go to Orders 
2. Get any order, go to `Open Details`
3. In Details -> Click Partial Refund
![image](https://github.com/PrestaShop/PrestaShop/assets/25379882/6931f5d8-3ace-4425-bb5c-982eceb44767)
4. Submit

### PrestaShop version(s) where the bug happened

1.7.8.10

### PHP version(s) where the bug happened

7.4.33

**Comment by florine2623** [comment]
Hello @huyhoang8398 ,

I can't reproduce your issue on PS 1.7.8.10.

https://github.com/PrestaShop/PrestaShop/assets/16019289/d994cb3e-9588-4e12-bc61-69956b92aa5b

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
