### ISSUE TITLE
1-click upgrade v1.6.8 problem witth PrestaShop 1.4.4

### ISSUE THREAD

**Issue by fioestio** [PrestaShop/PrestaShop#34753]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, when i try to update my Prestashop 1.4.4 with 1-click upgrade module v.1.6.8 i have a message that "The checklist is not OK. You can only upgrade your shop once all indicators are green." and one of lines not OK its that availiable new version of module and i need download it. But when i dowload new one i cant install it because it for new Presta versions. How can i solve this problem?
![10](https://github.com/PrestaShop/PrestaShop/assets/152685376/e6aea870-9413-4813-ac8f-920344bf0776)

### Steps to reproduce

download new version 

### PrestaShop version(s) where the bug happened

1.4.4

**Comment by ChillCode** [comment]
Hi @fioestio 

Wow, that one is pretty old and I guess upgrading from it will require you to do some hard craft job or to hire an expert if no module exists on PS marketplace, I doubt there is.

But I think should be much easier to export data and then import to a new site.

**Comment by ShaiMagal** [comment]
You should hire any PrestaShop expert. This version isn't supported a lot of years.
