### ISSUE TITLE
Prestashop 8.1 incompatible with PHP 8.1.26

### ISSUE THREAD

**Issue by shorrog** [PrestaShop/PrestaShop#34769]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I am running Prestashop 8.1.1. and PHP version 8.1.26 All customer shop functions work and orders are processed correctly. However trying to edit statuses in the back office throws the following error array_merge(): Argument #1 must be of type array, bool given
[TypeError 0]
Reverting back to PHP version 7.4.33 fixes the problem and I am able to edit the Statuses.

In addition, Stock management fails with PHP version 8.1.26. Instead of seeing the list of stock there is a grey sliding line and the stock never gets loaded.
![stock management](https://github.com/PrestaShop/PrestaShop/assets/16224215/a4bc10fa-f9b3-4410-b61a-597f511143a5)
Reverting to PHP 7.4.33 fixes the issue.

Running debug mode gives the following error 
array_merge(): Argument #1 must be of type array, bool given

in [controllers/admin/AdminStatusesController.php ](URL xxxxxxxxx) (line 536)

 }            $theme_templates_dir = _PS_ADMIN_DIR_ . '/' . $theme_path . $iso_code;            $theme_templates = is_dir($theme_templates_dir) ? scandir($theme_templates_dir, SCANDIR_SORT_NONE) : [];            // We merge all available emails in one array            $templates = array_unique(array_merge(scandir(_PS_ADMIN_DIR_ . '/' . $default_path . $iso_code, SCANDIR_SORT_NONE), $theme_templates));            foreach ($templates as $key => $template) {                if (!strncmp(strrev($template), 'lmth.', 5)) {                    $search_result = array_search($template, $theme_templates);                    $array[$iso_code][] = [                        'id' => substr($template, 0, -5),

### Expected behavior

You should be able to edit the Statuses and use the stock management capability

### Steps to reproduce

Set the PHP version as 8.1
Access the stock management page and it fails to show a list of stock.
Access the Status page in order settings and edit a status. Throws the bug as described previously.
Revert to PHP version 7.4 and the functionality works

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

Marston Sunbeam Club

**Comment by florine2623** [comment]
Hello @shorrog ,

I can't reproduce your issue.

I'm using PHP 8.1.13 with PS 8.1 and my Stock movements page is working well as well as editing the Order Statuses and Order return Statuses.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by shorrog** [comment]
Ok thanks.
Must be to do with a configuration set up on both my local
development environment and the production server. I will investigate
further.
Best Regards


Graham Shorrock Marston Sunbeam Club
<https://marston-sunbeam.org/index.html> IT Manager

**Comment by hannes01** [comment]
Hello,

I'm facing exactly the same issue, did you find a fix for this?

Thanks.

**Comment by shorrog** [comment]
I am afraid not. I have left my server running PHP 8.2.15 but I cant access the stock management page or statuses. 
I think the issue is probably something to do with the configuration or installation of Prestashop but I have not been able to find the solution. 
Another user also contacted me saying they had the same problem. So I definitely think it is a bug.
Graham

**Comment by Efeutute** [comment]
Hi,

I am experiencing exactly the same problem. Trying to edit statuses is throwing the error. Running PS 8.1.1 on PHP 8.1.27.
Did anyone officially report the bug or how can we proceed getting support?

**Comment by Bari1up** [comment]
Same issue, it works if you switch PHP back to 7.4 but it throws this error when trying to edit order statuses on PHP 8.0+

The bug isn't there on a clean install so it's definitely related to the upgrade process.  Disabling non native modules still produces the error.

**Comment by shorrog** [comment]
I did report this and was told it could not be reproduced and the bug was
closed. It would be great if you could report the bug again.
Best Regards


Graham

**Comment by darkf3d3** [comment]
Same error here.
I'm using PS8.1 with PHP8.1

**Comment by matks** [comment]
Hello everyone, this bug report was closed because using the above informations we were not able to reproduce the problem.

It does mean there is no problem. What it means is: "we dont know how to reproduce, on our own environment, the problem you are facing".

We cannot simply try random things 😅 until hopefully we find the right situation / configuration / environment where it fails. What we need is a clear list of steps / infos we can follow to reproduce the issue.

For example: "On a ubuntu 18 server running php7.4 and apache 2.4, mysql 7.5, I install PrestaShop version A then I upgrade to version B and then I open the back-office page C and I see an error" 😉 

Unfortunately we don't have your server or your shop so only you can provide us these informations. The solution is in your hands 👍

**Comment by hannes01** [comment]
Hello everyone,

please check if you have "en" email folder available in /mails folder. 

I personally got rid of this error by copying "en" folder from my template folder to /mails folder.

Hope it helps.

**Comment by shorrog** [comment]
Hi Hannes01, I just did the same as you and it fixed the issue of being unable to edit the statuses. I did find however that the .htaccess file in the themes directory prevents previewing the template. Hiding the .htaccess file and you can preview the template.
The issue of stock management still exists.

Matks, Like others that have experienced this issue I upgraded using oneclick upgrade to 8.1. I am running on 
Ubuntu 22.04.4 LTS, MariaDB 10.6.16.  PHP 8.1.27.  If I revert to php 7.4.33 the stock management issue disappears.

**Comment by darkf3d3** [comment]
Same here, adding "en" folder fixed the problem.
Thanks @hannes01

**Comment by shorrog** [comment]
darkf3d3 Do you have the problem with stock management or is that ok?

**Comment by darkf3d3** [comment]
I just checked and it seem working correctly, but it's a feature I never used, so I don't know if before today it was ok or not.
