### ISSUE TITLE
1clickUpgrade 1.7.8.10 to 8.1.2

### ISSUE THREAD

**Issue by ECC64** [PrestaShop/PrestaShop#34777]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

after putting the store in maintenance, emptying the cache, I launched 1ClickUpgrade with these parameters 
all points to check are green
Disable backup (i have backup server)
server power : low
disable non-prestashop modules: yes
disable override : no
upgrade default theme : yes
switch to default : no
RTL and email template : no

and the error is 
[INTERNAL] /home/hfrquggt/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 180 - Symfony\Component\Config\Exception\LoaderLoadException: The file "/home/hfrquggt/public_html/modules/ps_eventbus/config/admin/../parameters.yml" does not contain valid YAML: Duplicate key "parameters" 
detected at line 7 in /home/hfrquggt/public_html/modules/ps_eventbus/config/admin/../parameters.yml (which is being imported 
from "/home/hfrquggt/public_html/modules/ps_eventbus/config/admin/../common.yml"). 
 #0 /home/hfrquggt/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(104): Symfony\Component\Config\Loader\FileLoader->doImport('/home/hfrquggt/...', NULL, false, '/home/hfrquggt/...') 
 #1 /home/hfrquggt/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/FileLoader.php(66): Symfony\Component\Config\Loader\FileLoader->import('parameters.yml', NULL, false,  '/home/hfrquggt/...') 
 #2 /home/hfrquggt/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(197):  Symfony\Component\DependencyInjection\Loader\FileLoader->import('parameters.yml', NULL, false, '/home/hfrquggt/...') 
 #3 /home/hfrquggt/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(133): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseImports(Array,  '/home/hfrquggt/...') 
 #4 /home/hfrquggt/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(165):  Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('/home/hfrquggt/...', NULL) 
 #5 /home/hfrquggt/public_html/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(104): Symfony\Component\Config\Loader\FileLoader->doImport('/home/hfrquggt/...', NULL, false, '/home/hfrquggt/...') 
 #6 /home/hfrquggt/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/FileLoader.php(66): Symfony\Component\Config\Loader\FileLoader->import('../common.yml', NULL, false, '/home/hfrquggt/...') 
 #7 /home/hfrquggt/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(197):  Symfony\Component\DependencyInjection\Loader\FileLoader->import('../common.yml', NULL, false, '/home/hfrquggt/...') 
 #8 /home/hfrquggt/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(133): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseImports(Array, '/home/hfrquggt/...') 
 #9 /home/hfrquggt/public_html/src/PrestaShopBundle/DependencyInjection/Compiler/LoadServicesFromModulesPass.php(83): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('services.yml') 
 #10 /home/hfrquggt/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(94):  PrestaShopBundle\DependencyInjection\Compiler\LoadServicesFromModulesPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) 
 #11 /home/hfrquggt/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(762):  Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) 
 #12 /home/hfrquggt/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(594): Symfony\Component\DependencyInjection\ContainerBuilder->compile() 
 #13 /home/hfrquggt/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(136): Symfony\Component\HttpKernel\Kernel->initializeContainer() 
 #14 /home/hfrquggt/public_html/app/AppKernel.php(96): Symfony\Component\HttpKernel\Kernel->boot() 
 #15 /home/hfrquggt/public_html/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(76): AppKernel->boot() 
 #16 /home/hfrquggt/public_html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader80.php(45): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initAppKernel() 
 #17 /home/hfrquggt/public_html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(88): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader80->initConstants() 
 #18 /home/hfrquggt/public_html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader81.php(46): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() 
 #19 /home/hfrquggt/public_html/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(43): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader81->doUpgrade() 
 #20 /home/hfrquggt/public_html/arriereboutique/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() 
 #21 {main}
RE

update actions : 
Copied /vendor/willdurand/negotiation/src/Negotiation/Exception/InvalidMediaType.php.
Copied /vendor/willdurand/negotiation/src/Negotiation/LanguageNegotiator.php.
Copied /vendor/willdurand/negotiation/src/Negotiation/Negotiator.php.
Directory /webservice already exists.
Copied /webservice/dispatcher.php.
Copied /webservice/index.php.
[SKIP] directory "/app/cache/" does not exist and cannot be emptied.
[CLEANING CACHE] File dev removed
[CLEANING CACHE] File dsd removed
[CLEANING CACHE] File gfhfdh removed
[CLEANING CACHE] File prod removed
Cleaning file cache
API keys not present in parameters, generating
Keys generated using openssl_pkey_new, exporting private and public keys
Updating parameters file
Parameters file updated
Running opcache_reset

### Expected behavior

A complete upgrade

### Steps to reproduce

after putting the store in maintenance, emptying the cache, I launched 1ClickUpgrade with these parameters 
all points to check are green
Disable backup (i have backup server)
server power : low
disable non-prestashop modules: yes
disable override : no
upgrade default theme : yes
switch to default : no
RTL and email template : no

### PrestaShop version(s) where the bug happened

1.7.8.10

### PHP version(s) where the bug happened

7.4

**Comment by paulnoelcholot** [comment]
Hello @ECC64,

As you can see, I can't reproduce your problem. Did I miss something? 

Thanks for your feedback.

[1-Click Upgrade _ 1-Click Upgrade • the future (2).webm](https://github.com/PrestaShop/PrestaShop/assets/112863083/53bf380b-2d22-4aca-acf6-126587b85686)

**Comment by MatShir** [comment]
Could you provide ps_eventbus version ?
