### ISSUE TITLE
Prevent set the same order state twice (or more) in a row

### ISSUE THREAD

**Issue by Caleydon** [PrestaShop/PrestaShop#34774]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Prevent set the same order state twice (or more) in a row

For example: If the order has current state "Awaiting bank wire payment" the employees, function in the module, via request webservice etc. can't set as next state "Awaiting bank wire payment". Next order state need to be different order state. 

### Steps to reproduce

Iam experienced that card payment gateway sent answer about payment 3 times in one moment. The result is 3 payment statuses "Payment Accepted" in the order and 3 notification emails to customer in one moment. It is unwanted behaviour.

### PrestaShop version(s) where the bug happened

8.1.2

**Comment by paulnoelcholot** [comment]
Hello @Caleydon 

In order for us to test this issue, it is necessary that you provide us with a clear expected behavior and steps to reproduce allowing us to reproduce the bug.

Thank you for your understanding and looking forward to your feedback.

**Comment by Prestaworks** [comment]
This behaviour is usually handled by the payment module.

**Comment by florine2623** [comment]
Hello @Caleydon ,

I can't reproduce your issue in 9.0.x and the natives modules from PS.

https://github.com/PrestaShop/PrestaShop/assets/16019289/18472a93-6f46-4bdf-984a-d26283f40357

I'm closing your issue. If you have an issue with another payment module, please contact the develop of the module directly.

Thanks
