### ISSUE TITLE
Autoupgrade doesn't detect latest version

### ISSUE THREAD

**Issue by Carindesign** [PrestaShop/PrestaShop#34776]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I will upgrade Prestashop 8.0.5 to 8.1.2
But the autoupgrade module doesn't detect the latest version. Also manual upgrade have a lot of problems

Autoupgrade module shows this:

Congratulations, you are already using the latest version available!
Your current PrestaShop version: 8.0.5
Your current PHP version: 8.0.30
Latest official version for minor channel.: 8.0 stable - (8.0.5)

![autoupgrade](https://github.com/PrestaShop/PrestaShop/assets/58775883/85b81f6c-2be8-4d30-9b14-ae9488b53057)

How can I fix it?  

### Expected behavior

Get the latest version 8.1.2

### Steps to reproduce

?

### PrestaShop version(s) where the bug happened

8.0.5

### PHP version(s) where the bug happened

8.0.30

### If your bug is related to a module, specify its name and its version

1-click upgrade

**Comment by paulnoelcholot** [comment]
Hello @Carindesign,

I reproduce the issue with PrestaShop version 8.0.5, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/ace950b2-7d97-4aca-af6b-1de7d71619e3)

**Comment by ChillCode** [comment]
Hi @Carindesign 

Have you changed the upgrade channel? If not, you can change it  by clicking `More options (expert mode)`  and set the Channel to `Major release`.

**Comment by Hlavtox** [comment]
@Carindesign You must change the channel :-)

@paulnoelcholot You can close it ;-)
