### ISSUE TITLE
Combinations via webservice

### ISSUE THREAD

**Issue by LEOMARINO** [PrestaShop/PrestaShop#34779]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

We try to send the combinations of the products via webservice, sending all the values ​​associated with the product at once, I leave an example of the xml.

<prestashop xmlns:xlink='http://www.w3.org/1999/xlink'>
   <combination>
       <id_product>3666</id_product>
       <location></location>
       <ean13></ean13>
       <isbn></isbn>
       <upc></upc>
       <mpn></mpn>
       <quantity>1300</quantity>
       <reference></reference>
       <supplier_reference></supplier_reference>
       <wholesale_price></wholesale_price>
       <price></price>
       <ecotax></ecotax>
       <weight></weight>
       <unit_price_impact></unit_price_impact>
       <minimal_quantity>1</minimal_quantity>
       <low_stock_threshold></low_stock_threshold>
       <low_stock_alert></low_stock_alert>
       <default_on></default_on>
       <available_date></available_date>
       <associations>
           <product_option_values>
              <product_option_value>
              <id>5550</id>
              <id>5496</id>
              <id>5959</id>
              <id>6087</id>
               </product_option_value>
            </product_option_values>
       </associations>
    </combination>
</prestashop>

Whats wrong with this xml? Its possible send multiple assosiations?

Only associate the product with 1 attribute.

### Expected behavior

An association of combinations with multiple attributes

### Steps to reproduce

-

### PrestaShop version(s) where the bug happened

1.7.8

### PHP version(s) where the bug happened

7.4

**Comment by LEOMARINO** [comment]
`<prestashop xmlns:xlink='http://www.w3.org/1999/xlink'>
   <combination>
       <id_product>3666</id_product>
       <location></location>
       <ean13></ean13>
       <isbn></isbn>
       <upc></upc>
       <mpn></mpn>
       <quantity>1300</quantity>
       <reference></reference>
       <supplier_reference></supplier_reference>
       <wholesale_price></wholesale_price>
       <price></price>
       <ecotax></ecotax>
       <weight></weight>
       <unit_price_impact></unit_price_impact>
       <minimal_quantity>1</minimal_quantity>
       <low_stock_threshold></low_stock_threshold>
       <low_stock_alert></low_stock_alert>
       <default_on></default_on>
       <available_date></available_date>
       <associations>
           <product_option_values>
              <product_option_value>
              <id>5550</id>
              <id>5496</id>
              <id>5959</id>
              <id>6087</id>
               </product_option_value>
            </product_option_values>
       </associations>
    </combination>
</prestashop>`

**Comment by paulnoelcholot** [comment]
Hello @LEOMARINO,

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Thank you
