### ISSUE TITLE
Prestashop 8.1.2 An error occurred during installation (75%)

### ISSUE THREAD

**Issue by pushpikasj** [PrestaShop/PrestaShop#34771]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

- PrestaShop Version: Prestashop 8.1.2

- PHP Version: PHP version: 8.1.16

- Database client version: libmysql - mysqlnd 8.1.16

- Steps to reproduce the problem
1. Godaddy.com = Web Hosting Deluxe
2. Run Setup Prestashop 8.1.2
3. ->

Step 1

![image](https://github.com/PrestaShop/PrestaShop/assets/9498899/f8819e8c-f08d-453f-bd7e-8ce641819325)

Step 2

Error Message An error has occurrederror

![image](https://github.com/PrestaShop/PrestaShop/assets/9498899/47533b14-2b13-4c92-891f-73eb0d3e3fbc)

|   ID | Description                                                                                                 | Description1                                                    |
|-----:|:------------------------------------------------------------------------------------------------------------|:----------------------------------------------------------------|
|  nan | Useful settings                                                                                             | nan                                                             |
|    1 | System: Unix, Linux, or Windows                                                                             | Linux                                                           |
|    2 | MySQL: 5.6 or later                                                                                         | Server version: 5.7.43-cll-lve - MySQL - Community Server - (GPL) |
|    3 | PHP: 7.2 or later                                                                                           | PHP Version 8.1.24                                              |
|    4 | allow_url_fopen                                                                                             | on                                                              |
|    5 | register_globals                                                                                            | off                                                             |
|    6 | upload_max_filesize set to "16MB" or more                                                                   | 32 MB                                                           |
|  nan | Must have PHP extensions                                                                                    | nan                                                             |
|    7 | CURL: the Client URL extension is used to download remote resources like modules and localization packages. | enabled                                                         |
|    8 | DOM: the DOM extension is needed to parse XML documents.                                                    | enabled                                                         |
|    9 | Fileinfo: the File information extension is used to find out the file type of uploaded files.               | enabled                                                         |
|   10 | GD: the GD extension is used to create thumbnails for the images that you upload.                           | enabled                                                         |
|   11 | Intl: the ICONV extension is used to convert character sets.                                                | enabled                                                         |
|   12 | Mbstring: the Multibyte string extension is used to perform string operations everywhere.                   | enabled                                                         |
|   13 | Zip: the Zip extension is used to expand compressed files such as modules and localization packages.        | enabled                                                         |
|   14 | JSON: the JSON extension is used to manage JSON format.                                                     | enabled                                                         |
|   15 | Iconv: the ICONV extension is used to convert character sets.                                               | enabled                                                         |

### Expected behavior

Complete Setup the Prestashop 

### Steps to reproduce

1. Godaddy.com = Web Hosting Deluxe
2. Run Setup Prestashop 8.1.2
3. Error An error has occurrederror (75%)

### PrestaShop version(s) where the bug happened

Prestashop 8.1.2

### PHP version(s) where the bug happened

PHP version: 8.1.16

**Comment by paulnoelcholot** [comment]
Hello @pushpikasj,

I tested to reproduce your issue but as you can see, I can't.

Did I miss something?

Thanks
[google - Recherche Google.webm](https://github.com/PrestaShop/PrestaShop/assets/112863083/926866ec-67cc-4f23-be66-2d0ee574ea89)

**Comment by pushpikasj** [comment]
**Hello @paulnoelcholot 

**Thank You For your Support _Paul_ and please see more details for step screens. also tell how can I see the setup error log.****

Step 1

![screencapture-p3plzcpnl497223-prod-phx3-secureserver-net-2083-cpsess1332042521-frontend-jupiter-lveversion-php-selector-live-pl-2023-12-07-19_19_11](https://github.com/PrestaShop/PrestaShop/assets/9498899/bcf450a2-c3fc-48df-a843-c7e5964a4ba4)

Step 2

![screencapture-p3plzcpnl497223-prod-phx3-secureserver-net-2083-cpsess1332042521-frontend-jupiter-lveversion-php-selector-live-pl-2023-12-07-19_19_41](https://github.com/PrestaShop/PrestaShop/assets/9498899/c023f84b-4d64-4dd0-bca2-e586d754eacd)

Step 3

![image](https://github.com/PrestaShop/PrestaShop/assets/9498899/e9eafcbd-0a9b-401e-a319-fcde40e23e35)

Step 4

![image](https://github.com/PrestaShop/PrestaShop/assets/9498899/084097a3-7f29-41fb-9729-b09505dc9df2)

Step 5

![image](https://github.com/PrestaShop/PrestaShop/assets/9498899/82d7b70b-cf98-42b7-a8dc-ca2b4f1c0319)

**Comment by Hlavtox** [comment]
@pushpikasj Some error in configuration, check PHP logs.

If you want to advance further, extract the zip locally and upload the extracted files. Then it will directly start the install, skipping the extracting step.

**Comment by florine2623** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
