### ISSUE TITLE
contactform - Fatal error when sending a message

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#34770]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

There's a fatal error when a user sends a message through the customer form.

<img width="1440" alt="Screenshot 2023-12-05 at 15 14 08" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/055dd684-09ac-4c4b-bd79-2653f43ae6a8">

### Expected behavior

Message should be sent without problem

### Steps to reproduce

1. Go to BO > Module > contactform > Configure
2. Enable Send confirmation email to your customers & Receive customers' messages by email options
3. Go to BO > Advanced parameters > Email > Configure your SMTP parameters > Save
4. Go to FO > Contact Us
5. Send a message
6. See error :x:

### Acceptance Tests
* Uncomment these lines 
https://github.com/PrestaShop/PrestaShop/blob/51a646b1b31c4be3c2f8b0d8db5303b0d582c35b/tests/UI/campaigns/functional/FO/classic/05_contactUs/02_sendMessageWithCustomer.ts#L190-L192
https://github.com/PrestaShop/PrestaShop/blob/51a646b1b31c4be3c2f8b0d8db5303b0d582c35b/tests/UI/campaigns/functional/FO/classic/05_contactUs/03_sendMessageAsAnonymous.ts#L224-L226
* Unskip these tests
https://github.com/PrestaShop/PrestaShop/blob/51a646b1b31c4be3c2f8b0d8db5303b0d582c35b/tests/UI/campaigns/functional/FO/classic/05_contactUs/02_sendMessageWithCustomer.ts#L195-L200
https://github.com/PrestaShop/PrestaShop/blob/51a646b1b31c4be3c2f8b0d8db5303b0d582c35b/tests/UI/campaigns/functional/FO/classic/05_contactUs/03_sendMessageAsAnonymous.ts#L229-L234

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

contactform v4.4.1

**Comment by paulnoelcholot** [comment]
Hello @florine2623,

I reproduce the issue with PrestaShop version develop, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
