### ISSUE TITLE
Bug when Upgrading from 1.7.0.0 to 8.1.2

### ISSUE THREAD

**Issue by Pixomaniak** [PrestaShop/PrestaShop#34787]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I launch an upgrade via CLI commande : D:\xampp\php>php D:\mysite\modules\autoupgrade\cli-upgrade.php --dir=admin --channel=major I have this error : 
PHP Fatal error:  Uncaught Exception: Can't find PrestaShop Version in D:\pixomaniakWebSites\modules\autoupgrade\classes\PrestashopConfiguration.php:90
Stack trace:
#0 D:\pixomaniakWebSites\modules\autoupgrade\classes\UpgradeContainer.php(202): PrestaShop\Module\AutoUpgrade\PrestashopConfiguration->getPrestaShopVersion()
#1 D:\pixomaniakWebSites\modules\autoupgrade\classes\UpgradeContainer.php(299): PrestaShop\Module\AutoUpgrade\UpgradeContainer->getProperty('version')
#2 D:\pixomaniakWebSites\modules\autoupgrade\classes\TaskRunner\Upgrade\AllUpgradeTasks.php(64): PrestaShop\Module\AutoUpgrade\UpgradeContainer->getUpgrader()
#3 D:\pixomaniakWebSites\modules\autoupgrade\cli-upgrade.php(37): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\AllUpgradeTasks->setOptions(Array)
#4 {main}
  thrown in D:\pixomaniakWebSites\modules\autoupgrade\classes\PrestashopConfiguration.php on line 90

Fatal error: Uncaught Exception: Can't find PrestaShop Version in D:\pixomaniakWebSites\modules\autoupgrade\classes\PrestashopConfiguration.php:90
Stack trace:
#0 D:\pixomaniakWebSites\modules\autoupgrade\classes\UpgradeContainer.php(202): PrestaShop\Module\AutoUpgrade\PrestashopConfiguration->getPrestaShopVersion()
#1 D:\pixomaniakWebSites\modules\autoupgrade\classes\UpgradeContainer.php(299): PrestaShop\Module\AutoUpgrade\UpgradeContainer->getProperty('version')
#2 D:\pixomaniakWebSites\modules\autoupgrade\classes\TaskRunner\Upgrade\AllUpgradeTasks.php(64): PrestaShop\Module\AutoUpgrade\UpgradeContainer->getUpgrader()
#3 D:\pixomaniakWebSites\modules\autoupgrade\cli-upgrade.php(37): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\AllUpgradeTasks->setOptions(Array)
#4 {main}
  thrown in D:\pixomaniakWebSites\modules\autoupgrade\classes\PrestashopConfiguration.php on line 90

### Expected behavior

I exprect that upgrade should be smooth

### Steps to reproduce

Upgrade with SQLI

### PrestaShop version(s) where the bug happened

1.7.7.0

**Comment by musicpanda** [comment]
Prestashop 1.7.0 until 8.0 have the version number in  /app/AppKernel.php
Prestashop 8.1 has  its version number in /app/AppKernel.php to /src/Core/Version.php

It looks like the latest version of the autoupgrade module has forgotten about that change.

The least that should change is the function  getPrestaShopVersion() in /modules/autoupgrade/classes\PrestashopConfiguration.php
It contains now:
`    public function getPrestaShopVersion()
    {
        if (defined('_PS_VERSION_')) {
            return _PS_VERSION_;
        }
        $files = [
            $this->psRootDir . '/config/settings.inc.php',
            $this->psRootDir . '/config/autoload.php',
            $this->psRootDir . '/app/AppKernel.php',
        ];`

At the $files array /src/Core/Version.php should be added.

**Comment by Pixomaniak** [comment]
Ok so it seems that module is buggy. When do you think it will be corrected ?

**Comment by musicpanda** [comment]
Obviously the module is not always buggy. Sometimes the upgrade succeeds without problem. So we need details from the people who experience the problem.

**Comment by florine2623** [comment]
Hello @Pixomaniak ,

Did you upgrade your shop in 2 steps ? From `1.7.0.0 to 8.0.0` first and then from `8.0.0 to 8.1.2` ?

In 2 steps, you should not have any issue.

**Comment by Pixomaniak** [comment]
Hello,
No i didn't update in two steps... But it's not written any where that we have to update in two steps...

**Comment by florine2623** [comment]
Please make sure when you upgrade, you use the correct version of PHP regarding your PrestaShop version.
https://devdocs.prestashop-project.org/1.7/basics/installation/system-requirements/
https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/

Waiting for your feedback.

**Comment by Pixomaniak** [comment]
Hello,
So to update from 1.7.0.0 to 8.0.0 I have to use PHP 7.1 or later ?
And to upgrade from 8.0.0 to 8.1.2 I have tu use PHP 8.1 ?

It looks very complicated, there is not a way to correct the "one click upgrade module" to update from  1.7.0.0 to 8.1.2 directly and using PHP version required for 1.7.0.0 (PHP 7.1 or later) ?

**Comment by Pixomaniak** [comment]
Hello, it seems impossible to upgrade to 8.0.0... The only proposition in major channel is 8.1.2
<img width="533" alt="Capture d'écran 2023-12-14 113007" src="https://github.com/PrestaShop/PrestaShop/assets/4272879/49816c93-ef4e-4f4e-9cf3-c7fc5296bf27">

**Comment by Pixomaniak** [comment]
Hello,
I manage to find the 8.0.0 archive and tryed to update from the local archive. Unfortunatly the upgrade blocks on the step upgradeDB without any message this time...

In the \autoupgrade\tmp\log.txt file, last line is : [2023-12-14 14:02:36] Initializing required environment constants

<img width="1161" alt="Capture d'écran 2023-12-14 113007" src="https://github.com/PrestaShop/PrestaShop/assets/4272879/bbb46f8c-877d-468f-bc22-7326a6eae80f">

**Comment by florine2623** [comment]
You can use PHP 7.3 to upgrade from 1.7.7.0 to 8.1.2.

**Comment by Pixomaniak** [comment]
It does'nt work also with PHP 7.3; I used PHP 7.3.21...

**Comment by AureRita** [comment]
Hi @Pixomaniak 

Thank for your report and your details,
This issue is too technical for us, ping @PrestaShop/tech-council can someone please help for this issue ? 

Thanks

**Comment by matks** [comment]
> It looks very complicated, there is not a way to correct the "one click upgrade module" to update from 1.7.0.0 to 8.1.2 directly and using PHP version required for 1.7.0.0 (PHP 7.1 or later) ?

Unfortunately no because there is close to 7 years between these 2 versions of the software. It's already complex to build an upgrade process for 2 versions of a software separated by 2 to 3 years, 7 years is a no-go.

I'll be honest: performing a 1.7.0 to 8.1.2 upgrade is complex because 10 important versions have been released between these two. You have probably installed modules on this shop 1.7.0 : are they compatible with PS 8.1 ? I doubt it. I can suggest 3 things:

1. Do not use the web interface of the 1-click upgrade but use the CLI tool, more reliable https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/upgrade-module/upgrade-cli/#upgrade-cli
2. Or do not perform an _upgrade_ but a _data transfer_ : this means you take your shop A in 1.7.0, then you create a brand new fresh shop 8.1.0 we'll call B then you transfer the data from shop A to B. You'll have to adapt the data. There are some paying modules to do that on marketplace https://addons.prestashop.com/ that do the job very well
3. But the simplest way to is [to reach out for a professional](https://www.prestashop-project.org/support/#contact-a-professional) who is used to this usecase and will do it efficiently and swiftly, but obviously you'll be invoiced for that

**Comment by Quetzacoalt91** [comment]
Some changes have been done on the upgrade module regarding upgrades toward PS 8+, especially about version detection.
* https://github.com/PrestaShop/autoupgrade/pull/661
* https://github.com/PrestaShop/autoupgrade/pull/657

Upgrade from 1.7 to 8.1 are possible, sometimes in several steps when you're coming from a very old version of PHP / PrestaShop. We have an improvement planned [in another topic](https://github.com/PrestaShop/PrestaShop/issues/32745) where we provide information if something non compliant is found, allowing merchants to fallback on another channel or at least know what should be done before starting the upgrade.
