### ISSUE TITLE
Undefined array key tabs_simplify

### ISSUE THREAD

**Issue by musicpanda** [PrestaShop/PrestaShop#34791]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Two people on the forum report the same problem.  Their backoffice crashes with the error: _Warning Undefined array key tabs_simplify_

The error happens during a "getLegacyLayout" function call in a Twig file.

The error is puzzling as the word "tabs_simplify" is not present in the Prestashop code.

The forum posts are:
https://www.prestashop.com/forums/topic/1082345-probl%C3%A8me-prestashop-81-warning-undefined-array-key-tabs_simplify/
and
https://www.prestashop.com/forums/topic/1082642-oops-please-correct-the-items-below-and-then-click-refresh-information-to-test-the-compatibility-of-your-new-system/?do=findComment&comment=3468757

### Expected behavior

correct running of backoffice

### Steps to reproduce

Open backoffice

### PrestaShop version(s) where the bug happened

8.0 and 8.1

### PHP version(s) where the bug happened

8.1

**Comment by paulnoelcholot** [comment]
Hello @musicpanda,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by kpodemski** [comment]
The issue is probably related to the pseditionbasic module, not the core itself.

**Comment by amine-O** [comment]
Hello @musicpanda we fixed this issue in 8.1.2 version of Prestashop Classic, could you please retry it with this version and tell us if it's ok ?

**Comment by musicpanda** [comment]
I can't immediately test it. But I trust that it has been fixed and will close the issue.
