### ISSUE TITLE
Hook displayAdminProductsPriceStepBottom no longer executed

### ISSUE THREAD

**Issue by skutovamir** [PrestaShop/PrestaShop#34815]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hook displayAdminProductsPriceStepBottom should display additional content on Admin -> Products -> (Product) -> Pricing tab. It worked on 1.7.8.x.

[It is currently present in 8.x documentation.](https://devdocs.prestashop-project.org/8/modules/concepts/hooks/list-of-hooks/displayadminproductspricestepbottom/)

The file, where the hook is rendered, is no longer called. Product page is completely new. Now it renders the whole product form and all specific forms on tabs as Symfony form (PrestaShopBundle\Form\Admin\Sell\Product\EditProductFormType). This results in the hook not being rendered at all. 

This might influence other hooks called on admin product page and should be looked into (if not done yet).

The hook should be added into the form, or removed from documentation.

### Expected behavior

The hook (displayAdminProductsPriceStepBottom) should be called.

### Steps to reproduce

1. Turn on debug mode
2. Open specific product in new admin page
3. Look into profiler, search for "Hooks" section
4. See that no displayAdminProductsPriceStepBottom is called

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

**Comment by skutovamir** [comment]
[I just found this doc page](https://devdocs.prestashop-project.org/8/modules/sample-modules/extend-product-page/), after some time spent debugging and conveniently after opening this issue. The issue can be closed, as this explains my problem and solution, and I do apologize for opening a new one.

But I still believe the hook should be removed from the documentation, or some warning should be added that notifies developers the hook is available only for 8.0. I was upgrading my module for a new PS 8 page, did the usual round of "check for existence of hooks, it is in the doc, yay, proceed" and then got stuck.

**Comment by Hlavtox** [comment]
@skutovamir Yes, the hook list will be updated after the old product page is removed in v9. ;) 

Ping @thomasnares

**Comment by vcopleutre** [comment]
Hi, just to say that it could be great to update the documentation without waiting for the new version.

I spent some time trying to make it works because this gives no warning about deprecation.
https://devdocs.prestashop-project.org/8/modules/concepts/hooks/list-of-hooks/displayadminproductspricestepbottom/
