### ISSUE TITLE
Unable to remove the "legal notes" from the Home page footer”.

### ISSUE THREAD

**Issue by StreetSport** [PrestaShop/PrestaShop#34822]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I tried to remove the ‘legal notes’ from the footer of my store’s homepage but without success. I went to the module management section and then to the ‘links tree’ module which is already updated and in which the ‘legal notes’ item that I would like to remove does not appear, but it continues to appear on the homepage. [I am attaching the screenshots."]
Is it possible to reupdate that model in order to eliminate the "note legali" voice?
Thanks in advance
![Screenshot 2023-12-12 171018](https://github.com/PrestaShop/PrestaShop/assets/153656102/02b9e662-98d4-4196-91e6-7729ef35096e)
![Screenshot 2023-12-12 174049](https://github.com/PrestaShop/PrestaShop/assets/153656102/c730cf0f-37e1-42e2-9fba-3b81124c1aa8)

### Expected behavior

I would like to have the voice "note legali" to be seen in the Links tree, in order to remove it

### Steps to reproduce

Go to Module Management section
Click on Links Tree
Search for the "Legal Notes " voice
Delete it

### PrestaShop version(s) where the bug happened

1.7.8.10

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

Link Tree V5.0.5

### Your company or customer's name goes here (if applicable).

StreetSport.it

**Comment by Codencode** [comment]
Try clearing the Prestashop cache in "Shop parameters > Performance > Clear cache (top right button)"

**Comment by StreetSport** [comment]
Hi,
It works!
Thank you so much!
Have a nice day
