### ISSUE TITLE
FO - In All products page, Sort by Prices doesn't work with all currencies

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#34838]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I change my currency and I want to sort my product by Prices, no produce are displayed.

https://github.com/PrestaShop/PrestaShop/assets/16019289/947c1233-bf9b-4a4d-8f18-148d6895c8dc

I tested with Vietnamese Dong and Argentine Peso.

### Expected behavior

I should be able to sort my product by Prices.

### Steps to reproduce

1. Go to BO > International > Localization
2. Add 2 localization packs : Vietnam and Argentina
3. Go to FO > Display all products
4. Change currency to `VND` or `ARS`
5. Sort by `Prices, low to high` or `Prices, high to low`
6. No products are displayed :x:

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

PS

**Comment by MatShir** [comment]
I have the bug with PS 8.1.1 and v3.13.2 and v3.14.1
