### ISSUE TITLE
API Access Info endpoint

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#34844]
### Specs:
A default scope has to be defined, otherwise the API access will get access to all the scopes. 

is_authenticated to /api-access/infos → get the info of the scope allowed and the shop associated (the name of the endpoint still have to be defined) 
  - List of shops (no multishop for now)
  - List scopes 
  - All API access info except the secret

--
A query get access info, handle the info of the API access (get the id or to be managed by the handler)
The endpoint should be defined in the core (not in the module)

### Acceptance test
When the endpoint is called with the authorization Then
  - List of shops associated to the API access
  - List scopes allowed
  - All API access info except the secret are displayed
  - Add integration tests in the core

### Technical note
First we should check if the `is_authenticated` scope is really useful to access public endpoints (without any scopes assigned on it), and if the other ones are correctly protected If yes then we could remove the `is_authenticated` scope completely

**Comment by WahbiPS** [comment]
Blocked by [#35306](https://github.com/PrestaShop/PrestaShop/issues/35306)

**Comment by Progi1984** [comment]
UI Tests added : https://github.com/PrestaShop/PrestaShop/pull/35555
