### ISSUE TITLE
Add integration test for API endpoint from the module CI

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#34846]
#### Specs

1. Investigate → How to launch integration test into the module, but the module needs the core. So one of the possibility is to use flashlight @jokesterfr (check faceted search module may have CI)
2. Integrate the CI test into the module repo !

#### Acceptance test 
Working and green CI

**Comment by tleon** [comment]
PR => https://github.com/PrestaShop/ps_apiresources/pull/8
