### ISSUE TITLE
Bug : impossible to connect modules with their respectives site

### ISSUE THREAD

**Issue by Colgeo1357** [PrestaShop/PrestaShop#34842]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Since the migration from PS 1.7.9.10 to PS 8.1.2, these 5 modules do not connect with their respective sites :
Prestashop acount
Prestashop Checkout
Colissimo
Mondial Relay
Relais Colis

### Expected behavior

Find the solution

### Steps to reproduce

Migrate 1.7.9.10 to 8.1.2

### PrestaShop version(s) where the bug happened

1.7.9.10 to 8.1.2

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

Marc

**Comment by AureRita** [comment]
Hi @Colgeo1357 

Thank you for your issue, Despite my effort, I can't reproduce your issue as you can see : 

[recording(15).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/5cbcbf5c-bf75-4719-8a64-520bbe2bc573)

Did you know that a new version of autoupgrade is released ? Wich of autoupgrade version did you use ? 

Can you try to reproduce your issue with the new version ? 

Waiting for your feedback

**Comment by Colgeo1357** [comment]
PS 7.9.10 migrated to PS 8.1.2 by 27 November.MarcEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : AureRita ***@***.***> Date : 20/12/2023  16:58  (GMT+01:00) À : PrestaShop/PrestaShop ***@***.***> Cc : Colgeo1357 ***@***.***>, Mention ***@***.***> Objet : Re: [PrestaShop/PrestaShop] Bug : impossible to connect modules with their respectives site (Issue #34842) 
Hi @Colgeo1357
Thank you for your issue, Despite my effort, I can't reproduce your issue as you can see :
recording(15).webm
Did you know that a new version of autoupgrade is released ? Wich of autoupgrade version did you use ?
Can you try to reproduce your issue with the new version ?
Waiting for your feedback

**Comment by florine2623** [comment]
@Colgeo1357 ,

Please answer directly via GitHub. Nor Email.

**Comment by Colgeo1357** [comment]
I used the last version of 1 click upgrade.
The problem is with ps account : impossible to connect him with prestashop

**Comment by paulnoelcholot** [comment]
Hello @Colgeo1357,

I tried to reproduce your issue but I can't. Can you give us screenshot or video of your issue please?

Thanks for your feedback!

**Comment by Colgeo1357** [comment]
Hello,

 

To late.

I have installed a new Prestashop 8.1.2.

 

thanks

 

De : Paul-Noël ***@***.***> 
Envoyé : lundi 15 janvier 2024 14:25
À : PrestaShop/PrestaShop ***@***.***>
Cc : Colgeo1357 ***@***.***>; Mention ***@***.***>
Objet : Re: [PrestaShop/PrestaShop] Bug : impossible to connect modules with their respectives site (Issue #34842)

 

Hello @Colgeo1357 <https://github.com/Colgeo1357> ,

I tried to reproduce your issue but I can't. Can you give us screenshot or video of your issue please?

Thanks for your feedback!
