### ISSUE TITLE
Upgrade APIPlatform to version 3

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#34854]
Depending of the SF version update at least the API Platform v3
blocked by https://github.com/PrestaShop/PrestaShop/issues/34006

**Comment by WahbiPS** [comment]
@jolelievre can you please check if this devlopment is blocked by symfony 6.0 migration or 6.3/4 ?

**Comment by WahbiPS** [comment]
Will require at least Symfony 6.1
