### ISSUE TITLE
blockwishlist - In BO > Customer page, the wishlist is always empty

### ISSUE THREAD

**Issue by Arcoirismagico** [PrestaShop/PrestaShop#34853]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Customers put products on the wish list and they don't appear in the back office

Product is well added : 
<img width="441" alt="Screenshot 2023-12-18 at 12 03 50" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/d5c743f4-800a-4f8c-a53b-5663afaf8071">

In BO > Customer page > empty
<img width="584" alt="Screenshot 2023-12-18 at 12 03 54" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/45aa260e-bf9b-4350-ab90-ac7551198ef4">

### Expected behavior

In the customer page, the wishlist should be updated with the products added to it.

### Steps to reproduce

1. Go to FO > Log into customer account
2. Add product to wishlist
3. Go to BO > Customer page
4. See Wishlist block is empty

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1.26

### If your bug is related to a module, specify its name and its version

blockwishlist v3.0.1

### Your company or customer's name goes here (if applicable).

Arcoíris Mágico Baby Shop

**Comment by florine2623** [comment]
Your issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/27143

**Comment by hibatallahAouadni** [comment]
Duplicate of #27143
