### ISSUE TITLE
Nous recontrons un bug sur la gestion et téléchargement des PJ sur GitHub - PrestaShop/contactform: Adds a contact form to the "Contact us" page

### ISSUE THREAD

**Issue by max-mich** [PrestaShop/PrestaShop#34869]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Nos visiteurs sont susceptibles de nous contacter via le formulaire de contact : https://www.maison-colibri.com/fr/info/contact
Or, lorsqu'ils ajoutent une pj, elle s'affiche, dans le mail depuis le formulaire, comme un lien. Ce lien renvoie vers une page avec une erreur. Le pb se situe dans le HT access. Comment le corriger ? 
Nom : MAXENCE TEST
Email : [maxence.michel@maison-colibri.com](mailto:maxence.michel@maison-colibri.com)
Objet : [adv@maison-colibri.com](mailto:adv@maison-colibri.com)
Pièce jointe : 
•	http://www.maison-colibri.com/upload/pfg/658048fc16fd2.pdf
Message : Bonjour ceci est un test. Pouvez-vous me confirmer en retour de mail que vous arrivez à ouvrir la PJ ? Merci

### Expected behavior

La PJ est cliquable et téléchargeable. 
On peut l'ouvrir sur le navigateur (.pdf) ou le télécharger (.doc / .docx). 

### Steps to reproduce

1. Aller sur la page : https://www.maison-colibri.com/fr/info/contact
2. Compléter le formulaire en ajoutant une pj 
3. Envoyer le formulaire
4. Recevoir le formulaire (pas possible de reproduire pour vous)

### PrestaShop version(s) where the bug happened

v1.7.8.8

### If your bug is related to a module, specify its name and its version

prestashop/contactform v4.3.0

### Your company or customer's name goes here (if applicable).

MAISON COLIBRI

**Comment by florine2623** [comment]
Hello @max-mich ,


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).


After more verification, we can view the attachment of a comment in contact us, as you can see : 


https://github.com/PrestaShop/PrestaShop/assets/16019289/cf1bb2ed-97d8-4ccb-8a65-7fed89d39a4f

Thank you
