### ISSUE TITLE
Critical log on each backooffice load

### ISSUE THREAD

**Issue by clement74** [PrestaShop/PrestaShop#34862]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello

On each backoffice content load, logs are showing a critical error

request.CRITICAL: Uncaught PHP Exception Symfony\Component\Routing\Exception\RouteNotFoundException: "Unable to generate a URL for the named route "admin_logos_index" as such route does not exist." at /home/thiasmax/public_prestashop/thias_skwal_prod/vendor/symfony/symfony/src/Symfony/Component/Routing/Generator/CompiledUrlGenerator.php line 50 {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"admin_logos_index\" as such route does not exist. at /home/thiasmax/public_prestashop/thias_skwal_prod/vendor/symfony/symfony/src/Symfony/Component/Routing/Generator/CompiledUrlGenerator.php:50)"} []

It probably cause the slownesses to load pages on the backoffice

I joined a log file containing 2 examples of this issue with other debug and info log link to the critical one

[log.txt](https://github.com/PrestaShop/PrestaShop/files/13695176/log.txt)

Could you help me to investigate it ?

Thanks :-)

### Steps to reproduce

Load the backoffice page after login

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1.26

**Comment by Hlavtox** [comment]
@clement74 Some of your modules is adding a new route `admin_logos_index`, which is registered as a tab in left menu.

As a first thing I suggest manually deleting `var/cache` folder and see if it was just a cache issue. If not, that module does not properly register the route in `routes.yml` file. 👍If it was a paid module, contact the author, he should fix it for you.

So, go try to find the issue, but we will close this so we don't clutter the backlog with 3rd party issues. ;-)

**Comment by fire2** [comment]
> So, go try to find the issue, but we will close this so we don't clutter the backlog with 3rd party issues. ;-)

Actually, the problem is in the Prestashop module ;) `ps_edition_basic`. In the file `/src/Presenter/SetupGuideDataPresenter.php` line 168: 

```
[
       [
           'cta' => $this->translator->trans('Add a Logo', [], 'Modules.Editionbasic.Admin'),
           'href' => $router->generate('admin_logos_index'),
           'userflow_id' => '02f43ff1-f2ff-4ab6-9480-2229b2524f7c',
       ],
 ]
```

I'm facing the same situation in a shop, it's complaining that route doesn't exist. 
The route is not registered in `/config/routes.yml`.

**Comment by fire2** [comment]
I'm pretty sure the correct route there should be `admin_themes_index`, which is the admin route to add a logo to the theme.

**Comment by KevinFromSA** [comment]
Did the route change to admin_themes_index resolve the issue? I am having exactly the same problem with the associated 2 second delay on page loads.

**Comment by fire2** [comment]
Yes, for me it solved the issue.

**Comment by KevinFromSA** [comment]
Thank you so much. This fix resolved the error and sped up page loads for me as well. 

Ver 8.1.2
