### ISSUE TITLE
loading import field matches does not show settings to user.

### ISSUE THREAD

**Issue by Prestaworks** [PrestaShop/PrestaShop#34876]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

It's possible to save the column/database matches when importing csv files, however, when loading a saved setting, the display is not updated so the user will not see the correct data that was loaded from the save.

### Expected behavior

the display should show the same data as the hidden selectors in the background.

### Steps to reproduce

1. go to advanced settings -> import
2. select to import products
3. make a few changes to the column matches and save.
4. go back to advanced settings -> import
5. select to import products
6. load the saved matches from step 3.
7. Nothing changes in the display.

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1.12

### Your company or customer's name goes here (if applicable).

Prestaworks AB

**Comment by Prestaworks** [comment]
issue is fixed on dev code so should be fine in next release?
https://github.com/PrestaShop/PrestaShop/commit/c103f52f208ded17c06f225132956a2ba7fbf760

**Comment by AureRita** [comment]
Hi @Prestaworks 

Thank you for your report, Currently, your issue seems to be the same than this issue : 
https://github.com/PrestaShop/PrestaShop/issues/32798

Are you agree with that ? 

Moreover, this issue is corrected by this PR : 
https://github.com/PrestaShop/PrestaShop/pull/34438

This one 'll be on the version 8.1.3 that should be release in few days 

Waiting for your feedback

**Comment by Prestaworks** [comment]
Yes you correct, we can close this issue.
