### ISSUE TITLE
ps_wirepayment show blank page on validation

### ISSUE THREAD

**Issue by mikajaxxx** [PrestaShop/PrestaShop#34871]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

on wire payment we get blank page on validation page!
` Fatal error: Uncaught Error: Call to undefined function proc_open() in /home/sepidal/domains/sepidal.com/public_html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:291 Stack trace: #0 /home/sepidal/domains/sepidal.com/public_html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(54): Swift_Transport_StreamBuffer->establishProcessConnection() #1 /home/sepidal/domains/sepidal.com/public_html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(143): Swift_Transport_StreamBuffer->initialize() #2 /home/sepidal/domains/sepidal.com/public_html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/SendmailTransport.php(50): Swift_Transport_AbstractSmtpTransport->start() #3 /home/sepidal/domains/sepidal.com/public_html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_SendmailTransport->start() #4 /home/sepidal/domains/sepidal.com/public_html/classes/Mail.php(629): Swift_Mailer->send() #5 /home/sepidal/domains/sepidal.com/public_html/classes/order/OrderHistory.php(549): MailCore::send() #6 /home/sepidal/domains/sepidal.com/public_html/classes/order/OrderHistory.php(452): OrderHistoryCore->sendEmail() #7 /home/sepidal/domains/sepidal.com/public_html/classes/PaymentModule.php(575): OrderHistoryCore->addWithemail() #8 /home/sepidal/domains/sepidal.com/public_html/modules/ps_wirepayment/controllers/front/validation.php(63): PaymentModuleCore->validateOrder() #9 /home/sepidal/domains/sepidal.com/public_html/classes/controller/Controller.php(308): Ps_WirepaymentValidationModuleFrontController->postProcess() #10 /home/sepidal/domains/sepidal.com/public_html/classes/Dispatcher.php(510): ControllerCore->run() #11 /home/sepidal/domains/sepidal.com/public_html/index.php(28): DispatcherCore->dispatch() #12 {main} thrown in /home/sepidal/domains/sepidal.com/public_html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php on line 291`

### Expected behavior

wire payment must show bank account detail on last page

### Steps to reproduce

1 order a product
2 select wire payment  as payment
3 submit order
4 blank page on /module/ps_wirepayment/validation

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_wirepayment

**Comment by Hlavtox** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/22262

**Comment by mikajaxxx** [comment]
@Hlavtox  it is not duplicate
actualy it solved on php 7.4 . the error apears on php 8.1

**Comment by Hlavtox** [comment]
@mikajaxxx Your PHP 8.1 configuration is different than 7.4. You need to allow proc_open or change hosting. :-)

**Comment by AureRita** [comment]
Hi @mikajaxxx 

Thank you for your report, Despite my effort, I can't reproduce your issue as you can see : 

[recording(12).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/70568c3f-6d1b-4dff-9781-76c81ab37400)

Did I miss something ? 

Did you do anything with wire payment before ? Can you give us the version of wire payment ? 

Did you use any other module for your wire payment ? 

Waiting for your feedback

**Comment by mikajaxxx** [comment]
@Hlavtox it is not secure function to be enabled on host!  :-) any alternative solution?

**Comment by mikajaxxx** [comment]
@Hlavtox  as i checked  proc_open is disabled on both php 7.4 & php 8.1 but i see no problem on php 7.4

**Comment by paulnoelcholot** [comment]
Hello @mikajaxxx,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

**Comment by Bakis89** [comment]
hi, is have simmalar problem in no soltuions for this!

![Error](https://github.com/PrestaShop/PrestaShop/assets/175059676/5890fd28-c094-4d48-8445-b97aa7e87871)

**Comment by Hlavtox** [comment]
@Bakis89 You have completely different problem, and it's cause by some of your modifications or tpl override from theme.

**Comment by Bakis89** [comment]
> @Bakis89 You have completely different problem, and it's cause by some of your modifications or tpl override from theme.

Srange, becouse theme support tells, the problem is only with wirepayment. :(

**Comment by Hlavtox** [comment]
@Bakis89 Theme support will always tell you problem is not on their side. :)

Check themes/yourthemename/modules/ps_wirepayment for any overrides. If empty, reinstall the native module, check php compatibility and it has to work.
