### ISSUE TITLE
Adding new product has a problem with uploading product picture.

### ISSUE THREAD

**Issue by Zoran23** [PrestaShop/PrestaShop#34886]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Adding new product has a problem with uploading product picture.
![01](https://github.com/PrestaShop/PrestaShop/assets/45638558/ea16dd4b-310b-41b9-bbb6-971b165973ab)
![02](https://github.com/PrestaShop/PrestaShop/assets/45638558/02624fd4-c999-43da-b0c0-2c695ca7a8dd)
![03](https://github.com/PrestaShop/PrestaShop/assets/45638558/d9e0445b-7267-4554-966d-a759eaae7938)
![04](https://github.com/PrestaShop/PrestaShop/assets/45638558/f94281db-9f05-4f9a-bd43-9f302b0d8aae)
I have tested it on my two different servers, and on two different servers of two different web-hosting providers. I had same problem on every server. 

### Expected behavior

Pictures should be visible and clickable. That you can click on picture set as default or delete it.
As it is now it is not possible. 

### Steps to reproduce

Ad new product with one or more pictures. 
Save it
Exit from product
Try to edit this product, to change default picture if you have uploaded two pictures.

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1.26

### Your company or customer's name goes here (if applicable).

Zoran

**Comment by AureRita** [comment]
Hi @Zoran23 ,

Thank you for your report, I reproduce the issue with PrestaShop version 8.1.x, as you can see : 

[recording(16).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/4ed8f188-4607-4c1e-8a9a-f18c11884afa)

 I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks

**Comment by bluegifts** [comment]
I can confirm this issue. PS 8.1.2  with PHP 8.1.26 on apache

**Comment by hannes01** [comment]
I confirm this issue. PS 8.1.3 with PHP 8.1.

**Comment by OrionCodeDev** [comment]
I can confirm PS 8.1.3 it's important. How it's can be fixed?

**Comment by MatShir** [comment]
I can't reproduce. Could you give all your steps ? 🙏

**Comment by bluegifts** [comment]
my problem dissapeared after updating to 8.1.3

**Comment by OrionCodeDev** [comment]
> I can't reproduce. Could you give all your steps ? 🙏

1. Enable multistore
2. Have few stores
3. turn on new product page v2
4. create new product for example for sohp id 1
5. add images and save product
6. assign new item to other stores via "select stores"
7. switch to other store context in that edit product page
8. you will see that errors (blank images container)
![image](https://github.com/PrestaShop/PrestaShop/assets/47286873/260d037d-6dc9-419f-8bb8-5df83662a468)

**Comment by MatShir** [comment]
@ChronoBrake 
What's is multistore config virtual url or physical URL ?

**Comment by OrionCodeDev** [comment]
> @ChronoBrake What's is multistore config virtual url or physical URL ?

all stores be physical URL = /

so default option

**Comment by M0rgan01** [comment]
I do not reproduce on a store in 8.1.3. On the original post there is no mention of multistore, nor even on the QA video. Can someone from QA retest to verify that the problem persists in 8.1.3? @AureRita @paulnoelcholot @florine2623

**Comment by paulnoelcholot** [comment]
@MatShir,

I tried to reproduce this issue with and without multistore on 8.1.x and I can't...

**Comment by paulnoelcholot** [comment]
@Zoran23 tell me if you reproduce on 8.1.5 please :pray: 
Thanks!

**Comment by OrionCodeDev** [comment]
@M0rgan01 @paulnoelcholot i not mentioned one important thing. Every store in multistore has different domain in settings. For example:


Shop ID 1: shop1.example.com
Shop ID 2: shop2.example.com
etc.

maybe that will help

**Comment by MatShir** [comment]
@ChronoBrake If your main concern is regarding the multistore, let's shift the discussion to this matter on https://github.com/PrestaShop/PrestaShop/issues/34898. 
Can you provide details about your setup, including the Physical URL or virtual URL configuration?

For now, I will close the matter until someone can replicate it with version 8.1.5 😉
