### ISSUE TITLE
Bugs on migrated features and feature values page

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#34889]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

There are many issues on the migrated features page.
- Extra message that features are enabled on store. It wasn't there on the legacy page and just wastes space.
- Feature grid rows are not clickable.
- Feature value grid rows are not clickable.
- When adding new feature value and clicking cancel, you are always redirected to feature listing, instead of value listing.

### Steps to reproduce

1. Get develop branch.
2. Check Catalog > Attributes and features

### PrestaShop version(s) where the bug happened

develop

**Comment by AureRita** [comment]
Hi @Hlavtox ,
 
Thank you for your report, I reproduce the issue with PrestaShop version 9.0.x, as you can see : 

[recording(17).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/3231f0f3-5408-40ed-8a75-6d7962a3a6dd)

I'll add this to the backlog so it can be fixed.

Thank you for your PR :rocket:

Thanks
