### ISSUE TITLE
Autoupgrade - From 1.7.8.11 to 8.0.5 - Compile Error from class Attribute 

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#34885]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I do an upgrade from 1.7.8.11 to 8.0.5, I've this error on every migrated page, on the other I can go on it : 

![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/8e92c5ea-c597-4289-9266-f942b39f4481)

there is a video of the full proces : 

[recording(10).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/2621803e-f053-4944-bf0b-dc9042792241)

### Expected behavior

I wish I could go on migrated page when I do my upgrade

### Steps to reproduce

1. fresh install of Prestashop 1.7.8.11
2. Install Autoupgrade (currently 5.0.0)
3. Go to 1-Click Upgrade tab (or clic on configure at the end of the installation)
4. Put your Zip file and you xml file of prestashop v 8.0.5 on the folder [yourshop]/admin-dev/autoupgrade/download
5. Restart your page of 1-Click Upgrade 
6. On the expert mode, select local archive and put the 8.0.5 on it 
7. Save it 
8. Clic on the button to launch the update
9. At the end of the installation, Connect to the BO with your ID 
10. Go to a migrated page like Orders > Orders 

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

autoupgrade 5.0.0

### Your company or customer's name goes here (if applicable).

PS

**Comment by florine2623** [comment]
Same issue on my side.

Upgrade from 1.7.8.11 to 8.0.5 OK ✅ 
<img width="1435" alt="Screenshot 2023-12-20 at 14 18 22" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/44f4df8c-3a29-449a-9f76-de8e73fdfaa8">


PS 8.0.5 on migrated page is NOK :x:
<img width="690" alt="Screenshot 2023-12-20 at 14 18 35" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/b34a6a9c-f3dd-4a04-a082-d46154acb9a2">

Mode debug enabled :
<img width="1079" alt="Screenshot 2023-12-20 at 14 20 30" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/7e94dfa9-41d1-4da1-bb8e-f5eccb7a16d1">

**Comment by tleon** [comment]
So we investigated this problem. It is due to a class that should have been deleted after a rename and was not. This mistake may have happened because of a process during the upgrade. 
During the upgrade, the module is suppose to compare the xml file of the old version and the new one to figure out witch file to keep and witch to delete. 
Since the 1.7.8.11 is not released yet, there is no xml file. This comparaison cannot happen during the upgrade. 

This means that we cannot be certain this bug will still be present until we have this xml file.
