### ISSUE TITLE
New Product Page not available after upgrade from 1.7.8.7

### ISSUE THREAD

**Issue by HelixMartin** [PrestaShop/PrestaShop#34897]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After upgrading from 1.7.8.7 to latest 8.1.2, I don't see the New Product Page options anywhere. I can't find any information either that this is  only availböe for new installations and not upgrades.

Under "New & Experimental Features" I only find one option: Multiple image formats. 

### Steps to reproduce

New & Experimental Features

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

 7.4.33

**Comment by paulnoelcholot** [comment]
Hello @paulnoelcholot,

I tried to reproduce your issue but as you can see, I can't.

[1-Click Upgrade _ 1-Click Upgrade • the future (3).webm](https://github.com/PrestaShop/PrestaShop/assets/112863083/93280d60-cc34-4dec-8a84-9fbfffecabcc)

Did I miss something?

Thanks for your feedback

**Comment by HelixMartin** [comment]
Thank you.

As for my upgrade I used "Major Release", not "Local Archive". Should that be the difference?  (I will try to do it with Local Archive)
I also have multistore activated.

I run this upgrade several times, no difference. I though maybe it is due to the difference in Open Souce and Basic Edition of Prestashop. But clearly the upgrade you made is with the Open Source edition and you see that feature.

![newfeature](https://github.com/PrestaShop/PrestaShop/assets/154530191/6d74de5f-749c-4764-931c-90baf8acb687)

**Comment by paulnoelcholot** [comment]
Thank you for this additional information. However, in multistore and choosing "Major release", I have the same result as before.

https://www.loom.com/share/926194c5407a4acf81b96466cd90415c?sid=46c1d3db-109b-4985-801b-0faa7fd8c414

**Comment by HelixMartin** [comment]
Ok, that is indeed "bad" news for me :(

(Could some overrides be the reason for that difference? - removed all overrides, didn't make a difference)  

Are there an internal checks for that new feature to show? Trying to find something in my installation that is missing.

I also check in my 1.7.8.7 installation, and I can't see the "Experimental product page"-option  there  as you can see that in your first video. The 1.7.8.7 was a new installtion and then I migrated products from an old 1.6.xx installtion.

**Comment by HelixMartin** [comment]
Checked the table ps_feature_flag and is it empty.

**Comment by paulnoelcholot** [comment]
@Hlavtox Did you have any idea? :thinking:

**Comment by HelixMartin** [comment]
Before the upgrade the table ps_feature_flag and is it empty.

After another upgrade, the ps_feature_flag have the info for "Multiple image formats". (see screenshot).

I guess that since the "New Product Page" was not in the table for 1.7.8.7 for some resason, it is not there after the upgrade either.

![ps_feature_flag_after_upgrade](https://github.com/PrestaShop/PrestaShop/assets/154530191/5a85f689-1273-45b5-8576-279a3c56343d)

In the log after the update I found:
[OK] PHP 8.1.0 : /* Update feature flags */ /* PHP:ps_810_update_product_page_feature_flags(); */

I guess it was not really successfull, If there was no flag for product page, then probably the update failed, since there was no flag tp update.

**Comment by HelixMartin** [comment]
Inserted this into database:

`INSERT INTO `ps_feature_flag` (`id_feature_flag`, `name`, `state`, `label_wording`, `label_domain`, `description_wording`, `description_domain`, `stability`) VALUES
(1, 'product_page_v2', 1, 'New product page', 'Admin.Advparameters.Feature', 'This page benefits from increased performance and includes new features such as a new combination management system.', 'Admin.Advparameters.Help', 'stable\r\n');`

New Product Page work, but in back office under "New & Experimental Features" I stil can't see that option, to turn on and off. Did I miss something?

**Comment by HelixMartin** [comment]
A space in the query after "stable" coused the missing option in the BO, after runing the query above. Correct query 

`INSERT INTO ps_feature_flag (id_feature_flag, name, state, label_wording, label_domain, description_wording, description_domain, stability) VALUES (1, 'product_page_v2', 1, 'New product page', 'Admin.Advparameters.Feature', 'This page benefits from increased performance and includes new features such as a new combination management system.', 'Admin.Advparameters.Help', 'stable');`

---

So in the end the problem was/is that I have no New Product Page entry in XX_feature_flags table, in my 1.7.8.7 installtion of some reason - I do not understand why since it was  new installation and not an upgrade. The upgrade module only update that entry in the versions 8.0, 8.1, 8.1.2 and since I had no entry in database, no New Product Page was visible and available at all. 

I don't know if that helps, but maybe more users will search for this and will have same error.

**Comment by florine2623** [comment]
Thank for letting us know how you corrected it.
It will be useful if someone encounters the same issue as you !

I'm closing this issue to avoid clogging the backlog.
Thanks!
