### ISSUE TITLE
Applying the new PrestaShop branding on PrestaShop project site

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#34895]
The PrestaShop project site must follow the new branding guidelines.

# General informations

Live website https://www.prestashop-project.org/
GitHub repository https://github.com/PrestaShop/open-source

This website is built using GitHub Actions and [Hugo](https://gohugo.io/). Read the README to run the site locally. Don't hesitate to ask @matks.

# Header and title “Welcome to the PrestaShop project”

![Capture d’écran 2023-12-11 à 21 53 23](https://github.com/matks/prestashop-repos-bulk-editor/assets/3830050/f8c262e7-b76f-4a35-b711-b59a254f6c49)

- Replace current logo with puffin by simple “PRESTASHOP” SVG logo
- Background color  #F8E08E
- Menu uses font Arial Black in Capital Letters
- Title uses PRESTAFONT black
- Subtitle Arial bold

PRESTAFONT is a custom PrestaShop font

# Section “Project documentation”

Below the header

- TITLE SECTION ARIAL BLACK BOLD
- Please use attached icons SVG / PNG
- 3 columns, title bold + text arial black  

# CTA “Ready to get started”

![Capture d’écran 2023-12-11 à 21 53 28](https://github.com/matks/prestashop-repos-bulk-editor/assets/3830050/0834fd68-57db-454b-8ce5-1c06a41e16b9)

- Background black
- Use given Picture
- Title ARIAL WHITE BOLD CAPITAL LETTERS
- Call To Action Button white box + TRIANGLE + CAPITAL LETTERS  

# Footer

Follow style of prestashop.com footer

Use the SVG logo
Menu in black + triangle

# Rest of the site / other pages

- Navbar -> follow homepage example, background color yellow f8e08e
- Page title Header PrestaFont corps 120pt
- Subtitle when there is one: Arial Corps 28pt
- Header 1 when there is one: Arial Black corps 41pt
-  CTA white on black background, triangle ► HTML
- Bullet points: Black on white background

# Favicon

Nice-to-have: change the favicon to use the same as https://prestashop.com/

**Comment by matks** [comment]
Full homepage

![open-project](https://github.com/matks/prestashop-repos-bulk-editor/assets/3830050/a9a09780-0c4b-40b0-a920-7720a5b07fbc)

**Comment by boherm** [comment]
It's ok !
- https://github.com/boherm/ps-open-source/tree/reskin-prestashop
- https://github.com/boherm/ps-org-theme/tree/reskin-prestashop

**Comment by matks** [comment]
Done https://build.prestashop-project.org/
