### ISSUE TITLE
PHP 8.1 compatibility errors

### ISSUE THREAD

**Issue by Yabbertb** [PrestaShop/PrestaShop#34906]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

PHP Deprecated:  ucfirst(): Passing null to parameter #1 ($string) of type string is deprecated in /classes/controller/AdminController.php on line 987
PHP Deprecated:  ucfirst(): Passing null to parameter #1 ($string) of type string is deprecated in /classes/controller/AdminController.php on line 988
PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /vendor/twig/twig/src/Loader/FilesystemLoader.php on line 134
PHP Deprecated:  strncmp(): Passing null to parameter #1 ($string1) of type string is deprecated in /vendor/twig/twig/src/Loader/FilesystemLoader.php on line 135

### Steps to reproduce

1. Go to server error_log

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello ,

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
