### ISSUE TITLE
PrestaShop 8.1.2 "Home" and "Settings" tabs in backoffice are empty

### ISSUE THREAD

**Issue by Angar90** [PrestaShop/PrestaShop#34916]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

I installed PrestaShop 8.1.2 and the "Home" and "Settings" tabs are empty:
https://prnt.sc/HbWEK5u2tfum
https://prnt.sc/ex2TkoUhQA3T

I tested this in clean PrestaShop on localhost, my server and the customer server and in all shops I see the same problem.

### Expected behavior

These tabs should display data or should be removed.

### Steps to reproduce

1.Install clean PrestaShop 8.1.2 on the server.
2.Open the "Home" and "Settings" tab.

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1.26

**Comment by RosaBenouamer** [comment]
Hello @Angar90 
It seems to be the hosted edition, not the core version. Isn't it ?

**Comment by kpodemski** [comment]
@RosaBenouamer it's Classic version because he installed it on localhost 👍🏻

**Comment by Hlavtox** [comment]
Not related to the open source project, use https://github.com/PrestaShop/PrestaShop/releases/tag/8.1.2. 👍

**Comment by RosaBenouamer** [comment]
> @RosaBenouamer it's Classic version because he installed it on localhost 👍🏻

print screens in the description look like edition :-)

**Comment by fabio-nettis** [comment]
@Angar90 I have the same issue, is there any update on this? Maybe a linked issue or other resources I could use?

Is this issue related to the AngarTheme?

**Comment by jakub8109** [comment]
Też mam ten sam problem :(
