### ISSUE TITLE
Error "no route" during trying delete all catalogs with all products

### ISSUE THREAD

**Issue by sharkson-mgn** [PrestaShop/PrestaShop#34918]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When i trying delete all catalogs and i select delete product when it does not have category then that error appear. This problem happened during trying delete demo categories who put after install.

"No route found for "GET /sell/catalog/categories/bulk-delete": Method Not Allowed (Allow: POST)"

![image](https://github.com/PrestaShop/PrestaShop/assets/62204514/7dae19e2-7750-423c-b5a3-db827ff43baf)

### Expected behavior

The categories will be deleted along with the products without any error messages.

### Steps to reproduce

1. Go to Prestashop Backoffice
2. Then go to Catalog/Categories
3. Check all categories
4. Click "mass activites" and delete
5. Select "If they don't have other categories, I want to remove them too."

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello @sharkson-mgn ,

I can't reproduce your issue :


https://github.com/PrestaShop/PrestaShop/assets/16019289/aa9b2af9-6759-42ae-97fa-b58b7dfde879

**Comment by sharkson-mgn** [comment]
@florine2623 I downloaded Presta version directly from github as 8.1.2 latest release, maybe version on the page is different?

edit: You tried to reproduce on 8.1.3 but i have 8.1.2 and "1-click upgrade" showed me that 8.1.2 is the latest stable version

**Comment by florine2623** [comment]
I tried on a fresh install of PS 8.1.2.


https://github.com/PrestaShop/PrestaShop/assets/16019289/66e349b0-3257-4322-904e-921130bb04b5



I can't reproduce the issue either.

Did you do another action ?

**Comment by sharkson-mgn** [comment]
No, only that what i described. I think we can close this issue, unless are any questions?

When i saw problem, I repeated this action, every done with error, but next one category had deleted every time, in sum i repeated it three times - there are three categories by default at start. Anyway I decited to report this. Maybe environment is reason.

**Comment by florine2623** [comment]
Yes, as it can't be reproduced everywhere, it must be an env issue. I will close your issue.

You can check here that all the system requirements are met for PS 8 : https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/

Do not hesitate to create another issue if you encounter another one.
