### ISSUE TITLE
Slider Image not Uploading 

### ISSUE THREAD

**Issue by Hasa777** [PrestaShop/PrestaShop#34921]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I am having difficulties on uploading new sliders for my webpage PRESTASHOP version 1.7.6.8
![Screenshot 2023-12-27 114033](https://github.com/PrestaShop/PrestaShop/assets/154978478/32ebe9ba-55b0-4e16-819c-6db0ebf89ecd)
Everytime i try to upload a photo it crashes at gives me that error!

### Steps to reproduce

1 Moduls
2 ps_imageslider 
3 configure
4 upload a new photo
5 Save

### PrestaShop version(s) where the bug happened

1.7.6.8

### If your bug is related to a module, specify its name and its version

ps_imageslider

### Your company or customer's name goes here (if applicable).

Elektro-Tek

**Comment by florine2623** [comment]
Hello @Hasa777 ,

I can't reproduce your issue.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
