### ISSUE TITLE
New Product Page vs. Old product page; maxchar for meta title and description

### ISSUE THREAD

**Issue by HelixMartin** [PrestaShop/PrestaShop#34925]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

_Old product page:_ maximum characters for meta title and meta description is 70 and 160 chars. Although **more characters can be saved** when old product page is used. The table accepts 128 characters for meta title and 512 characters for meta description. 

_New Product Page:_ maximum characters for meta title and meta description is 70 and 160 chars. **Saving page with more characters can't not be done** and **information is showing under the form informing than only 70/160 characters can be used**.

The different behaviours of those two pages, old vs. new, is complicating updating products in the future. When using old page, longer titles and longer desctiptions can be saved. Those longer titles and desctiptions can be showed in the New Product Page, but then the product can't be updated with other info, unless the title and description has been decreased to 70/160 characters.

For some older shop owners this will complictate things, they will have to update all meta titles and description in order to use the New Product Page, just to be able to update simple things like stock amount.

This change in the New PRoduct Page will be a massive problems for many updated shop and owners.

Should it be better if the **product can be saved anyway**, but **with warning text that recommendation** is that meta title should be maximum 70 chars and meta description 160 chars? 

### Expected behavior
x the number of characters in the field.

- for the meta_title

Display on the bottom of the field : "x of 70 characters used (recommended)"
Validation server: 255 characters, like on the previous page.

- for the meta_description

Display on the bottom of the field : "x of 160 characters used (recommended)"
Validation server: 512 characters, like on the previous page.

### Steps to reproduce

Swithing between old and new product page, shows clearly what can be saved.

### PrestaShop version(s) where the bug happened

8.1.0, 8.1.2

### PHP version(s) where the bug happened

7.4

**Comment by AureRita** [comment]
Hi @HelixMartin ,

Thank you for your report, I reproduce the issue with PrestaShop version 8.1.x, as we can see : 

[recording(29).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/66de3d47-3602-4ecd-8572-81ef73319fd4)

Do I put this one in discussion or let it in issue @PrestaShop/product-council ?

Please be aware that some issues might take a very long time to be resolved. 

Thanks

**Comment by HelixMartin** [comment]
Thank you @AureRita .

Yes, I do understand the time issue. It is what it is. 

I'm only testing out 8.1.2 before a possible uprade. Also since my meta titles/description are longer slightly than 70/160, 8.1.2 with New Product Page will be impossible to use. The only option I can do it make some changes to remove 70/160 check for the New Product Page - although I think that is quite an impossible task for my knowledge of how and where it is coded. :(  On the other hand I have no interest of editing 8000 meta titles/description in order to be able to save the products.

I think many shop owners have the meta titles/description longer than 70/160 and they will be way suprised when upgrading to a version with New Product Page.

I hope the Prestashop team will allow longer titles/description in New Product Page, but with a warning instead of no way to save the product at all.

**Comment by Hlavtox** [comment]
Option 4 - `UPDATE ps_product_lang SET meta_title = SUBSTRING(meta_title, 1, 70), meta_description = SUBSTRING(meta_description, 1, 160);`

**Comment by HelixMartin** [comment]
> Option 4 - `UPDATE ps_product_lang SET meta_title = SUBSTRING(meta_title, 1, 70), meta_description = SUBSTRING(meta_description, 1, 160);`

Well, just cutting them off? No, that would probably remove a lot of information and make the titles/description look very bad. Maybe not for search engine, but at least for page visitors for the titles. It's probabaly the last thing I would do, but thanks for the suggesion.

**Comment by MatShir** [comment]
As the wording explains, the character limit only applies to recommendations. I also assume that the user after upgrades won't be able to modify his product without changing the content of the meta-description if the field exceeds the limit.

**Comment by HelixMartin** [comment]
> As the wording explains, the character limit only applies to recommendations. I also assume that the user won't be able to modify his product without changing the content of the meta-description if the field exceeds the limit.

Yes, that is correct. Modifying the product is impossible, without shortening the content. That is a difference from many, many PS versions before and also the Old Product Page. The table allows to have longer meta titles and description, so why not allowing to save the content anyway as it has been before. It is a huge change, to which also shop owners have to put in a massive work in order to change all the content already created for long time in previous versions in general or in Old Product Page..

- keep the recommendations of 70/160
- allow to modify and save longer content if user have it

**Comment by MatShir** [comment]
Thanks @HelixMartin for the report. I will push it forward to the project team member to prioritize it for the next patch. @Hlavtox, is there an alternative hack that doesn't involve altering the meta content for now?

**Comment by HelixMartin** [comment]
By the way @MatShir ...

I'm not sure if the characters amount should be counting down "live" on the New Product Page or not as amount of char is updated live in the old product page. As I can see, the count is not moving, counting down, as writing. Not sure what the intended behaviour should be, but if there are recommended limits, I think the intension was to count it down as writing (?)....


https://github.com/PrestaShop/PrestaShop/assets/154530191/e671eee5-84e2-4b0c-aa26-639969b320cc

**Comment by elektronenPL** [comment]
Hi,

is there any temporary solution before a fix? Can't save many products when updating stock amount.

**Comment by elektronenPL** [comment]
No tips? Maybe somebody can point me the files, where this check is done?

**Comment by HelixMartin** [comment]
Got this tip in forums.

Change can be made here:
src/Core/Domain/Product/ProductSettings.php

`
public const MAX_NAME_LENGTH = 128;
public const MAX_MPN_LENGTH = 40;
public const MAX_META_TITLE_LENGTH = 160;
public const MAX_META_DESCRIPTION_LENGTH = 350;
`

Maybe usefull to somebody,

**Comment by MatShir** [comment]
Fixed by #35564
