### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by TOLEBEAU** [PrestaShop/PrestaShop#34936]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

![Capture d'écran 2023-12-29 173003](https://github.com/PrestaShop/PrestaShop/assets/155180470/760877cb-0d21-4df7-bf2e-7ef2a212d844)

Good morning,
Following an update of the website. To move from version 1.6.8 to version 1.7.8 we encountered a problem.
The update was carried out without problems but a few minutes later the Prestashop page no longer works and displays an error 500.

### Steps to reproduce

After updating Prestashop, error message 500 was displayed.

### PrestaShop version(s) where the bug happened

1.6.8 / 1.7.8

### Your company or customer's name goes here (if applicable).

StreetOfWorker

**Comment by Hlavtox** [comment]
@TOLEBEAU 

> Avoid reporting "error 500" or "white page" errors - this is a universal error message that does not provide enough information to qualify the issue. Enable debug mode in the Performance section of PrestaShop or manually in /config/defines.inc.php and try again. You should get a proper error message.

**Comment by paulnoelcholot** [comment]
Hello @TOLEBEAU,

There is no version 1.6.8 of Prestashop. Do you mean 1.6.0.8?

Thanks in advance

**Comment by PrestaEdit** [comment]
Before checking your issue : please, an advice, edit your message to remove the name of the Back Office folder. Thanks.

**Comment by alfonsolr09** [comment]
did you check php version ??

**Comment by florine2623** [comment]
Hello,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
