### ISSUE TITLE
Error in credit slip with voucher code

### ISSUE THREAD

**Issue by itisco** [PrestaShop/PrestaShop#34958]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello
When you place an order with a voucher code, if you have to make a refund it generates a credit slip with the wrong numbers. The voucher code is not taken into account and so the credit slip total is wrong.
Ex : You place an order of 100€ with a voucher of 20€. The customer pays 80€.
You do the refund and the credit slip indicates 100€ and not 80€ as the customer paid.

### Expected behavior

The credit slip should be equal to the total paid discounts/vouchers included.

### Steps to reproduce

1. place an order with a voucher code
2. in the BO, do a partial refund with credit slip generated
3. open the PDF credit slip. You'll see that the total doesn't take in consigeration the voucher code.

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1.26

### Your company or customer's name goes here (if applicable).

ITIS Commerce

**Comment by florine2623** [comment]
Hello @itisco ,

It seems like your issue is the same as https://github.com/PrestaShop/PrestaShop/issues/18319. Could you confirm ?

**Comment by florine2623** [comment]
Hello,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
