### ISSUE TITLE
Failed upgrade from 8.1.2 to 8.1.3 

### ISSUE THREAD

**Issue by EmmaPal** [PrestaShop/PrestaShop#34961]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The **Status** of upgrade finish is clean without errors.
No possibility to access backoffice: It gives 500 error
After activating  debug mode, I think this is the cause: 
Warning: Zend OPcache API is restricted by "restrict_api" configuration directive
Also downgrading is failed.

So only one solution: Restauration day-1 with OVH.....

### Expected behavior

We must have a website that works after upgrade

### Steps to reproduce

Do a simple upgrade from 8.1.2 to 8.1.3

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

7.3

**Comment by EmmaPal** [comment]
Downgrading errors:

[INTERNAL] /home/------/-----/config/config.inc.php line 121 - Error: Call to a member function getName() on null #0 /home/--------/------/modules/autoupgrade/classes/UpgradeContainer.php(576): require_once() #1 /home/-------/-----------/modules/autoupgrade/classes/TaskRunner/AbstractTask.php(120): PrestaShop\Module\AutoUpgrade\UpgradeContainer->initPrestaShopCore() #2 /home/------/------/-----/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\AbstractTask->init() #3 {main}

**Comment by EmmaPal** [comment]
I have tried several times and each time I find **different errors**.


**Problem solved after 7 tries**:

- php must be at least **7.4**
- **Uncheck** the backup of files and database

**Comment by AureRita** [comment]
Hi @EmmaPal 

Thank your for your report, did you reproduce again your issue ? Currently this issue seems to be corrected yesterday at 3 PM 

Waiting for your feedback

**Comment by EmmaPal** [comment]
Hi @AureRita really after I upgraded successfuly I did't try to reproduce it.

What's odd is that each time it gives a different error type! (not only error mentionned above...).
The only time in witch the migration succeeded was when I disabled the backup and changed PHP to 7.4 for the update. Then I switched back to php  7.3 without any issues.

**Comment by MatShir** [comment]
Thanks for the report ! We are planning to rework the upgrade feature. Hopefully next time it would be easier
