### ISSUE TITLE
Menu button on mobile not working

### ISSUE THREAD

**Issue by eroskamp33** [PrestaShop/PrestaShop#34963]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On my prestashop site www.doro.cy I have an issue with the menu on mobile phone. When I click on the menu it doesn't open the menu items but just refreshes the current page. This happens on every page.

### Expected behavior

Clicking on Menu button should open all menu items

### Steps to reproduce

1. Open www.doro.cy on your mobile phone
2. Click on the yellow menu button

### PrestaShop version(s) where the bug happened

1.7.6.8

### Your company or customer's name goes here (if applicable).

adscore

**Comment by Hlavtox** [comment]
Hi @eroskamp33, you need to contact a professional. This an issue with your theme. 👍
