### ISSUE TITLE
Commands loading is extremely slow due to KPI on old websites with tons of data.

### ISSUE THREAD

**Issue by CrochetFeve0251** [PrestaShop/PrestaShop#34986]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When going to the commands pages my client complained about the page to load the order being incredibly slow to the point he could not work with the website as a single page was taking up to 50sec to load.

Digging into it I found out it was related to notifications and AdminStats which were taking ages to load. (Mocking them to empty values fixed the issue)

BTW I found [that issue](https://github.com/PrestaShop/PrestaShop/issues/18956) closed for the same problem but they said the problem was fixed with 1.7.7.0 which can't be the case cause the website of my client is under 1.7.8.9

### Expected behavior

I think the use of caching on that calls should be able to fix the problem or at least to make it acceptable.
So we would have the first load that take a long time but not the other times.

### Steps to reproduce

1. Fill your db with a lot of orders, visitors and carts.
2. Visit the commands page on the BO
3. Try to access a single command page right after.
4. You should have to wait for ages :D

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.4

**Comment by Hlavtox** [comment]
@CrochetFeve0251 Hey, could you please provide rough row counts of your data? Orders, customers etc. Do you think you could provide anonymized data that we could test it?

Could you find out which exact function causes this slowdown?

**Comment by florine2623** [comment]
It seems like your issue has already been encountered by others users :
https://github.com/PrestaShop/PrestaShop/issues/27232
https://github.com/PrestaShop/PrestaShop/issues/30206

Could you confirm ?

**Comment by paulnoelcholot** [comment]
Hello @CrochetFeve0251,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
