### ISSUE TITLE
Autoupgrade (1-Click Upgrade) failed using PHP 8.x (get_magic_quotes_gpc function deprecated)

### ISSUE THREAD

**Issue by xsbr** [PrestaShop/PrestaShop#34988]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

During the upgrade process received a fatal error about a undefined function named **get_magic_quotes_gpc()**
https://github.com/PrestaShop/autoupgrade/blob/dev/classes/UpgradeTools/Translation.php#L175

This function **get_magic_quotes_gpc() always returns false** since PHP 5.4, **DEPRECATED** in PHP 7.4 and **REMOVED** in PHP 8.0

Autoupgrade module requires PHP 5.6, so this code (lines 175-177) could be useless

To fix my upgrade I added a **function_exists()** check
`if (function_exists('get_magic_quotes_gpc') && get_magic_quotes_gpc())`

### Expected behavior

Complete upgrade without errors

### Steps to reproduce

Try upgrade using autoupgrade module (1-Click Upgrade) using PHP 8.1

### PrestaShop version(s) where the bug happened

Upgrading from 1.8.0 to 1.8.3

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

autoupgrade

**Comment by xsbr** [comment]
Created a PR https://github.com/PrestaShop/autoupgrade/pull/662

**Comment by florine2623** [comment]
Hello @xsbr ,

I upgraded from 8.1.0 to 8.1.3 using PHP 8.1 and autoupgrade 5.0.0.


https://github.com/PrestaShop/PrestaShop/assets/16019289/3353d914-e76e-4f6b-b23c-cf89baf0cb2d



I can't reproduce your issue.
Where exactly is your issue ? Could you send a screenshot ?

**Comment by xsbr** [comment]
Hi @florine2623, I have difficulty reproducing the error because I don't know in which situations the mergeTranslationFile() method is called during the upgrade process. Probably this method isn't called in a fresh installation.

Anyway when https://github.com/PrestaShop/autoupgrade/pull/662 is merged this issue will be finished

This is the upgrade log with error:
> [2024-01-06 16:47:44] Copied /modules/ps_googleanalytics/index.php.
> [2024-01-06 16:47:44] Copied /modules/ps_googleanalytics/logo.png.
> [2024-01-06 16:47:44] Copied /modules/ps_googleanalytics/ps_googleanalytics.php.
> [2024-01-06 16:47:44] Directory /modules/ps_googleanalytics/translations already exists.
> [2024-01-06 16:47:44] Copied /modules/ps_googleanalytics/translations/de.php.
> [2024-01-06 16:47:44] [INTERNAL] /opt/prestashop/web/modules/autoupgrade/classes/UpgradeTools/Translation.php line 175 - Error: Call to undefined function PrestaShop\Module\AutoUpgrade\UpgradeTools\get_magic_quotes_gpc()
> #0 /opt/prestashop/web/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeFiles.php(184): PrestaShop\Module\AutoUpgrade\UpgradeTools\Translation->mergeTranslationFile()
> #1 /opt/prestashop/web/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeFiles.php(75): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeFiles->upgradeThisFile()
> #2 /opt/prestashop/web/adminxxxxxxx/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeFiles->run()
> #3 {main}

**Comment by paulnoelcholot** [comment]
Hello @xsbr,

As @florine2623, I tried to reproduce your issue but I can't... https://www.loom.com/share/ba7651b4cdeb4a5ab738d51ad9f37c20?sid=aa02b46b-3cc3-4b11-873b-8861232bcc28

We are sorry but if we are not able to have a step to reproduce, we will not be able to validate the issue, and if the issue is not validated, the PR cannot be validated either: / Can you investigate the problem?

Thanks in advance

**Comment by xsbr** [comment]
Hi @paulnoelcholot,

Sorry, but I can't help you replicate this error due to my lack of knowledge about the autoupgrade module.

As Prestashop 9 the minimum version will be PHP 8.1, there will certainly be a failure in some situation due to the use of a discontinued PHP function (get_magic_quotes_gpc).

Maybe @Hlavtox or @boherm could help to explain about it

**Comment by florine2623** [comment]
Closing your issue as your PR has been merged.
