### ISSUE TITLE
Prestashop 8.1.3 BuildPaginated URL

### ISSUE THREAD

**Issue by fryd13** [PrestaShop/PrestaShop#34985]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After updating the store to version **8.1.3**, category pages in the front-end stopped working. The error returned was related to the **buildPaginatedUrl** function referenced by the **getCanonicalURL()** function:

Fatal error: Uncaught Error: Call to undefined method CategoryController::buildPaginatedUrl() in /home/admin/domains/pixeldev.davicar.pl/public_html/controllers/front/listing/CategoryController.php:63 Stack trace: #0 /home/admin/domains/pixeldev.davicar.pl/public_html/classes/controller/FrontController.php(1800): CategoryControllerCore->getCanonicalURL() #1 /home/admin/domains/pixeldev.davicar.pl/public_html/controllers/front/listing/CategoryController.php(275): FrontControllerCore->getTemplateVarPage() #2 /home/admin/domains/pixeldev.davicar.pl/public_html/classes/controller/FrontController.php(543): CategoryControllerCore->getTemplateVarPage() #3 /home/admin/domains/pixeldev.davicar.pl/public_html/classes/controller/FrontController.php(607): FrontControllerCore->assignGeneralPurposeVariables() #4 /home/admin/domains/pixeldev.davicar.pl/public_html/controllers/front/listing/CategoryController.php(127): FrontControllerCore->initContent() #5 /home/admin/domains/pixeldev.davicar.pl/public_html/classes/controller/Controller. in /home/admin/domains/pixeldev.davicar.pl/public_html/controllers/front/listing/CategoryController.php on line 63

I replaced the code with:

 ```
public function getCanonicalURL()
    {
        /*if (!Validate::isLoadedObject($this->category)) {
            return '';
        }

        return $this->buildPaginatedUrl($this->context->link->getCategoryLink($this->category));*/
        $canonicalUrl = $this->context->link->getCategoryLink($this->category);
        $parsedUrl = parse_url($canonicalUrl);
        if (isset($parsedUrl['query'])) {
            parse_str($parsedUrl['query'], $params);
        } else {
            $params = array();
        }
        $page = (int) Tools::getValue('page');
        if ($page > 1) {
            $params['page'] = $page;
        } else {
            unset($params['page']);
        }
        $canonicalUrl = http_build_url($parsedUrl, ['query' => http_build_query($params)]);

        return $canonicalUrl;
    }
```
And everything started working correctly.

This is my first time reporting an issue on GitHub, and I apologize if I mixed anything up.

### Steps to reproduce

1. Click on any category at Prestashop 8.1.3

### PrestaShop version(s) where the bug happened

Prestashop 8.1.3

### PHP version(s) where the bug happened

PHP 7.2

### Your company or customer's name goes here (if applicable).

PixelDuetWeb

**Comment by Hlavtox** [comment]
@fryd13 Could you check if there are any overrides? This normally works correctly.

**Comment by florine2623** [comment]
Hello,

Since we had no news from you, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
