### ISSUE TITLE
You have requested a non-existent parameter "database_prefix" after update from 1.7.2.4 to 1.7.8.11

### ISSUE THREAD

**Issue by jakub-lipinski** [PrestaShop/PrestaShop#34997]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After upgrading from version 1.7.2.4 to 1.7.8.11 (files and database) my admin panel works fine, but the front end returns error 500, when I turn on debug mode I see this error.

Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: You have requested a non-existent parameter "database_prefix". in /home/sdf/domains/algichamot.strondlafirm.hekko24.pl/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/DefinitionErrorExceptionPass.php:37 Stack trace: #0 /home/sdf/domains/algichamot.strondlafirm.hekko24.pl/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(60): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true) #1 /home/sdf/domains/algichamot.strondlafirm.hekko24.pl/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/DefinitionErrorExceptionPass.php(30): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, true) #2 /home/sdf/domains/algichamot.strondlafirm.hekko24.pl/public_html/vendor/symfony/symfony/s in /home/sdf/domains/algichamot.strondlafirm.hekko24.pl/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/DefinitionErrorExceptionPass.php on line 37

![error](https://github.com/PrestaShop/PrestaShop/assets/84547080/7eff20aa-deb5-46c5-a838-679e4dc226e8)

### Expected behavior

The front of the site is supposed to work

### Steps to reproduce

I just manually updated Prestashop from 1.7.2.4 to 1.7.8.11

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

7.4

**Comment by Hlavtox** [comment]
@Jakub017 Two questions:
- Does `database_prefix` exist in `app/config/parameters.php`?
- If you delete everything inside in `/var/cache/`, does the issue still exist?

**Comment by jakub-lipinski** [comment]
Yes, I cleared cache and the `database_prefix` exists in my file:
`'database_prefix' => 'ps_',`

**Comment by paulnoelcholot** [comment]
Hello @Jakub017 

It seems that it is currently not possible to create a shop in 1.7.2.4. We will have to deal with this problem before we can test your issue. Thanks for your patience

![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/63336b33-4270-4d01-a0c3-839cf21a5952)

**Comment by AureRita** [comment]
Hello @Jakub017 , 

for further information, did you do your update with php 7.1 ? Because as you can see in this tab, the only version that are enable for the two version is php 7.1 : 
![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/fc77f722-5097-4659-9a72-6f789cddd5e3)

Waiting for your feedback

**Comment by jakub-lipinski** [comment]
Yes, I had PHP 7.1 for the whole upgrade process.

**Comment by jakub-lipinski** [comment]
I tried again to upgrade but to 1.7.8.10 and this error occured when I hit /install/upgrade/upgrade.php
![image](https://github.com/PrestaShop/PrestaShop/assets/84547080/096c1749-65a4-49fc-b4e2-2b533571003e)

When I tried to upgrade again I got error telling me that 1.7.8.10 version is already installed.

**Comment by AureRita** [comment]
Hi @Jakub017 

Despite my effort, I can't reproduce your issue as you can see : 

[recording(72).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/6b991cc1-d8c6-4f2a-b554-372ced8e3c7d)

Did you use the module 1-Click Upgrade ? If yes, wich version did you use ? 
After this installation could you do a rollback to return on your shop 1.7.2.4 ? 

Can you provide us a video to see all the different problem occured during you installation ? 

Waiting for your feedback

**Comment by florine2623** [comment]
Hello,

Since we had no news from you for, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
