### ISSUE TITLE
Prestashop Upgrade 1.7 to 8.X - api_private_key

### ISSUE THREAD

**Issue by mati771** [PrestaShop/PrestaShop#34998]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When updating Prestashop from 1.7 to 8.x, an error occurs.

I noticed that this is a global problem, does anyone already have a solution?

 

When updating Prestashop to version 8.x, the following errors were displayed -> [INTERNAL]
/var/www/prestashop/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/DefinitionErrorExceptionPass.php line 54 - Symfony\Component\DependencyInjection\Exception\RuntimeException: You have requested a non-existent parameter "api_private_key". #0 /var/www/prestashop/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(83): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue() #1 /var/www/prestashop/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/DefinitionErrorExceptionPass.php(32): 

### Expected behavior

Hassle-free, automatic prestashop version update

### Steps to reproduce

I see discussions no. #33041, no solution to the problem.
There is no solution in Google.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

v7.4.3

**Comment by EmmaPal** [comment]
@mati771 Last months they closed 5 issues in relation with api_private_key. So I think that they will close your issue because they don't like this api private key.
I paid 120 dollars to do migration from 8.0.4 to 8.1.0 due to this "api_private_key".

Last day i I gave proof of a new other bug but also one of them closed it (problem between new and old product page)

**Comment by mati771** [comment]
Solved.
Add in parametrs.php:
'api_public_key' => ' '
'api_private_key' => ' '

**Comment by Hlavtox** [comment]
https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+api_private_key+is%3Aclosed

**Comment by mati771** [comment]
I've been trying to update the store for 4 days, with lots of errors. Finally succeeded.

In the file parameters.php: add the following lines
'api_public_key' => ' '
'api_private_key' => ' '
(In short, create a new store on another server version 8.1 and copy these keys)

The next very important step is to disable all modules and set the classic template.

The official store update module is definitely enough if you follow the steps above.
