### ISSUE TITLE
Prestashop Upgrade 1.7 to 8.X - Error: Access to undeclared static property: Hook::$_hook_modules_cache_exec

### ISSUE THREAD

**Issue by mati771** [PrestaShop/PrestaShop#35001]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

An error occurs when updating the store version to 8.1

[INTERNAL] /prestashop/override/classes/Hook.php line 249 - Error: Access to undeclared static property: Hook::$_hook_modules_cache_exec #0 /prestashop/override/classes/Hook.php(13): Hook::getAllHookRegistrationsLG() #1 /prestashop/src/Adapter/LegacyHookSubscriber.php(76): Hook::getHookModuleExecList() #2 /prestashop/vendor/symfony/symfony/src/Symfony/Component/Config/Resource/ReflectionClassResource.php(250): 

![image](https://github.com/PrestaShop/PrestaShop/assets/63502371/edc058ea-3aa7-4a1e-af5f-7826d7ce6803)

### Steps to reproduce

I cleared and disabled the cache

### PrestaShop version(s) where the bug happened

1.7.8.7

**Comment by Hlavtox** [comment]
Hi @mati771, you need to fix your overrides - `/prestashop/override/classes/Hook.php`. 👍

Best thing is to make a copy of your shop that you can easily restore, for testing.
Update all your modules to be compatible with 8.1.x, update your theme, update your overrides.

Then the upgrade will be a 5 minute breeze.

**Comment by mati771** [comment]
I've been trying to update the store for 4 days, with lots of errors. Finally succeeded.

In the file parameters.php: add the following lines
'api_public_key' => ' '
'api_private_key' => ' '
(In short, create a new store on another server version 8.1 and copy these keys)

The next very important step is to disable all modules and set the classic template.

The official store update module is definitely enough if you follow the steps above.
