### ISSUE TITLE
ps_emailsubscription - Switch buttons need to be clicked twice in order to enable option

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#35004]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I need to click twice to order to enable the option :

https://github.com/PrestaShop/PrestaShop/assets/16019289/a1fd8a87-1c24-41f0-93ab-16ab9041fbe1

This problem occurs only when I configure the module on the second try.

### Expected behavior

I should be able to click the switch button just once to enable the option.

### Steps to reproduce

1. Go to BO > Modules > Email subscription > Configure
2. Enable option 1 or 2 
3. See that the switch does not switch in the first try

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_emailsubscription v2.7.1

**Comment by Hlavtox** [comment]
It's because a configuration value for this switch is missing.

Two outcomes:
- Default values need to be added to install method in this module.
- The switch should probably behave the same regardless on the data. :-)

**Comment by Hlavtox** [comment]
@florine2623 Update
- https://github.com/PrestaShop/ps_emailsubscription/pull/102 this will fix issues on 8.1.x
- On develop, the switch has been improved so there is no behavior difference
![Snímek obrazovky 2024-01-09 103912](https://github.com/PrestaShop/PrestaShop/assets/6097524/7da515dc-57a1-47ac-8461-440d0b5c468e)

**Comment by florine2623** [comment]
ping @Hlavtox ,

I still have the issue actually. I need to click twice on the switch to make it work. I tested with ps_emailsubscription v2.8.0

https://github.com/PrestaShop/PrestaShop/assets/16019289/bd8971b0-05ca-47f4-be93-c0c20fda2e49

Could you check ? And maybe do another release of the module ?

**Comment by Hlavtox** [comment]
Fixed by https://github.com/PrestaShop/ps_emailsubscription/releases/tag/v2.8.1
