### ISSUE TITLE
PS 8.1.1 break BC with ObjectModel having translatable bool fields

### ISSUE THREAD

**Issue by gross-nvs** [PrestaShop/PrestaShop#35003]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Since Prestashop 8.1.1 loading an ObjectModel with a boolean field that is translatable triggers an 'Array to string conversion' error.

### Expected behavior

ObjectModel with translatable boolean must load properly.
If to be deprecated in a near future it should not break in a minor version.

PR #34873 solves the issue

### Steps to reproduce

1. Install the provided module
2. Try to configure the module
[castcrash.zip](https://github.com/PrestaShop/PrestaShop/files/13871512/castcrash.zip)

### PrestaShop version(s) where the bug happened

8.1.1+

### Your company or customer's name goes here (if applicable).

Novius

**Comment by AureRita** [comment]
Hi @gross-nvs ,

Thank you for your report, I reproduce the issue with PrestaShop version 8.1.x, as you can see 

[recording(43).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/ee4cb5bd-6039-4f6e-8b90-d5185f77c9f7)

I'll add this to the backlog so it can be fixed.

Thank you for your PR :rocket: 

Thanks
