### ISSUE TITLE
FileManager not working properly to regen thumbnails

### ISSUE THREAD

**Issue by devgraal** [PrestaShop/PrestaShop#35005]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When deleted images in "/img/tmp/cms" FileManager should recreate them on the go, but in some case, it doesnt.

### Steps to reproduce

if you configure php to specify "memory_limit" with another suffix than "M", FileManager doesnt calculate properly memory usage.

[In the file ](https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/filemanager/include/utils.php#L303)

Some admins may configure this value in php settings with a "G" or "k" or nothing, thumbnail regeneration will fail

### PrestaShop version(s) where the bug happened

1.7.7+ (at least)

### Your company or customer's name goes here (if applicable).

Graal Network

**Comment by AureRita** [comment]
Hi @devgraal 

Thank you for your report. Despite my efforts, I can't reproduce your issue as you can see : 

[recording(44).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/5890709e-1f9d-4846-99ed-ba52467cc20b)

Did I miss something ? 

Currently the image are often reload when they are displayed on the FO 

Waiting for your feedback

**Comment by devgraal** [comment]
We use php-fpm and the original config in it was "php_admin_value[memory_limit] = 1G"
after deleting "/img/tmp/cms/*" the thumbnails in the filemanager werent regen'd
updating config to "php_admin_value[memory_limit] = 1024M" did fix the problem of regen

**Comment by Hlavtox** [comment]
This is not fixed.

@AureRita Two problems with your testing:
A) You should not change anything in the source code of Prestashop.
B) You must restart your server to see the changes.
C) I don't think that 128G will be accepted, but maybe I am wrong.

**Comment by Hlavtox** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/35006
