### ISSUE TITLE
Front office error after update 8.1.1 to 8.1.3

### ISSUE THREAD

**Issue by z3n4j** [PrestaShop/PrestaShop#35022]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After upgrade from 8.1.1 to 8.1.3 front office don't work. Back office work.

Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'saqzmqei_terpinshop.ps_connections_source' doesn't exist in /home/saqzmqei/shop.terpin.it/classes/db/DbPDO.php:149 Stack trace: #0 /home/saqzmqei/shop.terpin.it/classes/db/DbPDO.php(149): PDO->query() #1 /home/saqzmqei/shop.terpin.it/classes/db/Db.php(377): DbPDOCore->_query() #2 /home/saqzmqei/shop.terpin.it/classes/db/Db.php(744): DbCore->query() #3 /home/saqzmqei/shop.terpin.it/classes/db/Db.php(477): DbCore->q() #4 /home/saqzmqei/shop.terpin.it/classes/ObjectModel.php(622): DbCore->insert() #5 /home/saqzmqei/shop.terpin.it/classes/ConnectionsSource.php(105): ObjectModelCore->add() #6 /home/saqzmqei/shop.terpin.it/modules/statsdata/statsdata.php(119): ConnectionsSourceCore::logHttpReferer() #7 /home/saqzmqei/shop.terpin.it/modules/statsdata/statsdata.php(74): statsdata->getScriptCustomerPagesViews() #8 /home/saqzmqei/shop.terpin.it/classes/Hook.php(1043): statsdata->hookDisplayBeforeBodyClosingTag() #9 /home/saqzmqei/shop.terpin.it/classes/Hook.php(418): HookCore::coreCallHook() #10 /home/saqzmqei/shop.terpin.it/classes/Hook.php(981): HookCore::callHookOn() #11 /home/saqzmqei/shop.terpin.it/config/smarty.config.inc.php(198): HookCore::exec() #12 /home/saqzmqei/shop.terpin.it/classes/Smarty/SmartyLazyRegister.php(81): smartyHook() #13 /home/saqzmqei/shop.terpin.it/var/cache/dev/smarty/compile/Bigstore_Layout2layouts_layout_full_width_tpl/ea/d1/b5/ead1b51c988034cc14e3ea5987e9a758d12a3005_2.file.layout-both-columns.tpl.php(381): SmartyLazyRegister->__call() #14 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(248): Block_174328677659efb4065e4f1_14211261->callBlock() #15 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(184): Smarty_Internal_Runtime_Inheritance->callBlock() #16 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(156): Smarty_Internal_Runtime_Inheritance->process() #17 /home/saqzmqei/shop.terpin.it/var/cache/dev/smarty/compile/Bigstore_Layout2layouts_layout_full_width_tpl/ea/d1/b5/ead1b51c988034cc14e3ea5987e9a758d12a3005_2.file.layout-both-columns.tpl.php(125): Smarty_Internal_Runtime_Inheritance->instanceBlock() #18 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_659efb4065f398_42427690() #19 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode() #20 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render() #21 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(386): Smarty_Internal_Template->render() #22 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(116): Smarty_Internal_Template->_subTemplateRender() #23 /home/saqzmqei/shop.terpin.it/var/cache/dev/smarty/compile/Bigstore_Layout2layouts_layout_full_width_tpl/9f/7d/a5/9f7da5bd54ab81496b712ceab3fd31e68d2c076e_2.file.layout-full-width.tpl.php(42): Smarty_Internal_Runtime_Inheritance->endChild() #24 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_659efb40645229_85144033() #25 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode() #26 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render() #27 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(386): Smarty_Internal_Template->render() #28 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(116): Smarty_Internal_Template->_subTemplateRender() #29 /home/saqzmqei/shop.terpin.it/var/cache/dev/smarty/compile/Bigstore_Layout2layouts_layout_full_width_tpl/26/15/ea/2615eaf2dfdb0695b81c366f6261b1602538b2be_2.file.page.tpl.php(33): Smarty_Internal_Runtime_Inheritance->endChild() #30 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_659efb4063d894_31081681() #31 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode() #32 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render() #33 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(386): Smarty_Internal_Template->render() #34 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(116): Smarty_Internal_Template->_subTemplateRender() #35 /home/saqzmqei/shop.terpin.it/var/cache/dev/smarty/compile/Bigstore_Layout2layouts_layout_full_width_tpl/c1/dc/0b/c1dc0b7dcca56b54112ba90606ee59df60bec798_2.file.index.tpl.php(33): Smarty_Internal_Runtime_Inheritance->endChild() #36 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_659efb40631a95_36112358() #37 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode() #38 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render() #39 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render() #40 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute() #41 /home/saqzmqei/shop.terpin.it/classes/Smarty/SmartyDev.php(40): Smarty_Internal_TemplateBase->fetch() #42 /home/saqzmqei/shop.terpin.it/override/classes/controller/FrontController.php(50): SmartyDev->fetch() #43 /home/saqzmqei/shop.terpin.it/classes/controller/FrontController.php(735): FrontController->smartyOutputContent() #44 /home/saqzmqei/shop.terpin.it/classes/controller/Controller.php(339): FrontControllerCore->display() #45 /home/saqzmqei/shop.terpin.it/classes/Dispatcher.php(510): ControllerCore->run() #46 /home/saqzmqei/shop.terpin.it/index.php(28): DispatcherCore->dispatch() #47 {main} Next PrestaShopException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'saqzmqei_terpinshop.ps_connections_source' doesn't exist in /home/saqzmqei/shop.terpin.it/classes/db/DbPDO.php:151 Stack trace: #0 /home/saqzmqei/shop.terpin.it/classes/db/Db.php(377): DbPDOCore->_query() #1 /home/saqzmqei/shop.terpin.it/classes/db/Db.php(744): DbCore->query() #2 /home/saqzmqei/shop.terpin.it/classes/db/Db.php(477): DbCore->q() #3 /home/saqzmqei/shop.terpin.it/classes/ObjectModel.php(622): DbCore->insert() #4 /home/saqzmqei/shop.terpin.it/classes/ConnectionsSource.php(105): ObjectModelCore->add() #5 /home/saqzmqei/shop.terpin.it/modules/statsdata/statsdata.php(119): ConnectionsSourceCore::logHttpReferer() #6 /home/saqzmqei/shop.terpin.it/modules/statsdata/statsdata.php(74): statsdata->getScriptCustomerPagesViews() #7 /home/saqzmqei/shop.terpin.it/classes/Hook.php(1043): statsdata->hookDisplayBeforeBodyClosingTag() #8 /home/saqzmqei/shop.terpin.it/classes/Hook.php(418): HookCore::coreCallHook() #9 /home/saqzmqei/shop.terpin.it/classes/Hook.php(981): HookCore::callHookOn() #10 /home/saqzmqei/shop.terpin.it/config/smarty.config.inc.php(198): HookCore::exec() #11 /home/saqzmqei/shop.terpin.it/classes/Smarty/SmartyLazyRegister.php(81): smartyHook() #12 /home/saqzmqei/shop.terpin.it/var/cache/dev/smarty/compile/Bigstore_Layout2layouts_layout_full_width_tpl/ea/d1/b5/ead1b51c988034cc14e3ea5987e9a758d12a3005_2.file.layout-both-columns.tpl.php(381): SmartyLazyRegister->__call() #13 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(248): Block_174328677659efb4065e4f1_14211261->callBlock() #14 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(184): Smarty_Internal_Runtime_Inheritance->callBlock() #15 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(156): Smarty_Internal_Runtime_Inheritance->process() #16 /home/saqzmqei/shop.terpin.it/var/cache/dev/smarty/compile/Bigstore_Layout2layouts_layout_full_width_tpl/ea/d1/b5/ead1b51c988034cc14e3ea5987e9a758d12a3005_2.file.layout-both-columns.tpl.php(125): Smarty_Internal_Runtime_Inheritance->instanceBlock() #17 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_659efb4065f398_42427690() #18 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode() #19 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render() #20 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(386): Smarty_Internal_Template->render() #21 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(116): Smarty_Internal_Template->_subTemplateRender() #22 /home/saqzmqei/shop.terpin.it/var/cache/dev/smarty/compile/Bigstore_Layout2layouts_layout_full_width_tpl/9f/7d/a5/9f7da5bd54ab81496b712ceab3fd31e68d2c076e_2.file.layout-full-width.tpl.php(42): Smarty_Internal_Runtime_Inheritance->endChild() #23 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_659efb40645229_85144033() #24 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode() #25 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render() #26 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(386): Smarty_Internal_Template->render() #27 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(116): Smarty_Internal_Template->_subTemplateRender() #28 /home/saqzmqei/shop.terpin.it/var/cache/dev/smarty/compile/Bigstore_Layout2layouts_layout_full_width_tpl/26/15/ea/2615eaf2dfdb0695b81c366f6261b1602538b2be_2.file.page.tpl.php(33): Smarty_Internal_Runtime_Inheritance->endChild() #29 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_659efb4063d894_31081681() #30 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode() #31 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render() #32 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(386): Smarty_Internal_Template->render() #33 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(116): Smarty_Internal_Template->_subTemplateRender() #34 /home/saqzmqei/shop.terpin.it/var/cache/dev/smarty/compile/Bigstore_Layout2layouts_layout_full_width_tpl/c1/dc/0b/c1dc0b7dcca56b54112ba90606ee59df60bec798_2.file.index.tpl.php(33): Smarty_Internal_Runtime_Inheritance->endChild() #35 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_659efb40631a95_36112358() #36 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode() #37 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render() #38 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render() #39 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute() #40 /home/saqzmqei/shop.terpin.it/classes/Smarty/SmartyDev.php(40): Smarty_Internal_TemplateBase->fetch() #41 /home/saqzmqei/shop.terpin.it/override/classes/controller/FrontController.php(50): SmartyDev->fetch() #42 /home/saqzmqei/shop.terpin.it/classes/controller/FrontController.php(735): FrontController->smartyOutputContent() #43 /home/saqzmqei/shop.terpin.it/classes/controller/Controller.php(339): FrontControllerCore->display() #44 /home/saqzmqei/shop.terpin.it/classes/Dispatcher.php(510): ControllerCore->run() #45 /home/saqzmqei/shop.terpin.it/index.php(28): DispatcherCore->dispatch() #46 {main} Next PrestaShop\PrestaShop\Core\Exception\CoreException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'saqzmqei_terpinshop.ps_connections_source' doesn't exist in /home/saqzmqei/shop.terpin.it/classes/Hook.php:431 Stack trace: #0 /home/saqzmqei/shop.terpin.it/classes/Hook.php(981): HookCore::callHookOn() #1 /home/saqzmqei/shop.terpin.it/config/smarty.config.inc.php(198): HookCore::exec() #2 /home/saqzmqei/shop.terpin.it/classes/Smarty/SmartyLazyRegister.php(81): smartyHook() #3 /home/saqzmqei/shop.terpin.it/var/cache/dev/smarty/compile/Bigstore_Layout2layouts_layout_full_width_tpl/ea/d1/b5/ead1b51c988034cc14e3ea5987e9a758d12a3005_2.file.layout-both-columns.tpl.php(381): SmartyLazyRegister->__call() #4 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(248): Block_174328677659efb4065e4f1_14211261->callBlock() #5 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(184): Smarty_Internal_Runtime_Inheritance->callBlock() #6 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(156): Smarty_Internal_Runtime_Inheritance->process() #7 /home/saqzmqei/shop.terpin.it/var/cache/dev/smarty/compile/Bigstore_Layout2layouts_layout_full_width_tpl/ea/d1/b5/ead1b51c988034cc14e3ea5987e9a758d12a3005_2.file.layout-both-columns.tpl.php(125): Smarty_Internal_Runtime_Inheritance->instanceBlock() #8 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_659efb4065f398_42427690() #9 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode() #10 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render() #11 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(386): Smarty_Internal_Template->render() #12 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(116): Smarty_Internal_Template->_subTemplateRender() #13 /home/saqzmqei/shop.terpin.it/var/cache/dev/smarty/compile/Bigstore_Layout2layouts_layout_full_width_tpl/9f/7d/a5/9f7da5bd54ab81496b712ceab3fd31e68d2c076e_2.file.layout-full-width.tpl.php(42): Smarty_Internal_Runtime_Inheritance->endChild() #14 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_659efb40645229_85144033() #15 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode() #16 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render() #17 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(386): Smarty_Internal_Template->render() #18 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(116): Smarty_Internal_Template->_subTemplateRender() #19 /home/saqzmqei/shop.terpin.it/var/cache/dev/smarty/compile/Bigstore_Layout2layouts_layout_full_width_tpl/26/15/ea/2615eaf2dfdb0695b81c366f6261b1602538b2be_2.file.page.tpl.php(33): Smarty_Internal_Runtime_Inheritance->endChild() #20 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_659efb4063d894_31081681() #21 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode() #22 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render() #23 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(386): Smarty_Internal_Template->render() #24 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(116): Smarty_Internal_Template->_subTemplateRender() #25 /home/saqzmqei/shop.terpin.it/var/cache/dev/smarty/compile/Bigstore_Layout2layouts_layout_full_width_tpl/c1/dc/0b/c1dc0b7dcca56b54112ba90606ee59df60bec798_2.file.index.tpl.php(33): Smarty_Internal_Runtime_Inheritance->endChild() #26 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_659efb40631a95_36112358() #27 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode() #28 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render() #29 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render() #30 /home/saqzmqei/shop.terpin.it/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute() #31 /home/saqzmqei/shop.terpin.it/classes/Smarty/SmartyDev.php(40): Smarty_Internal_TemplateBase->fetch() #32 /home/saqzmqei/shop.terpin.it/override/classes/controller/FrontController.php(50): SmartyDev->fetch() #33 /home/saqzmqei/shop.terpin.it/classes/controller/FrontController.php(735): FrontController->smartyOutputContent() #34 /home/saqzmqei/shop.terpin.it/classes/controller/Controller.php(339): FrontControllerCore->display() #35 /home/saqzmqei/shop.terpin.it/classes/Dispatcher.php(510): ControllerCore->run() #36 /home/saqzmqei/shop.terpin.it/index.php(28): DispatcherCore->dispatch() #37 {main} thrown in /home/saqzmqei/shop.terpin.it/classes/Hook.php on line 431

### Steps to reproduce

1. upgrade with 1 click upgrade
2. front office don't work

### PrestaShop version(s) where the bug happened

8.1.1 to 8.1.3

### PHP version(s) where the bug happened

 8.1.26

**Comment by florine2623** [comment]
Hello @z3n4j ,

I can't reproduce your issue upgrading from 8.1.1 to 8.1.3.
<img width="880" alt="Screenshot 2024-01-11 at 11 04 30" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/879ed810-0263-4add-ad01-c3320b79d9bc">


https://github.com/PrestaShop/PrestaShop/assets/16019289/b11cfeec-db61-4341-a5c4-9e9c07933dc3

Have you disabled your overrides ?

<img width="931" alt="Screenshot 2024-01-11 at 11 11 08" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/95379dad-177e-412a-9a08-3261f7d55995">

**Comment by Hlavtox** [comment]
@z3n4j Can you check if ps_connections_source exists in your database? Apparently it doesn't, meaning your install was corrupted before the upgrade.

This is a core table and must be present in every prestashop install.

**Comment by z3n4j** [comment]
> Hello @z3n4j ,
> 
> I can't reproduce your issue upgrading from 8.1.1 to 8.1.3. <img alt="Screenshot 2024-01-11 at 11 04 30" width="880" src="https://private-user-images.githubusercontent.com/16019289/295871783-879ed810-0263-4add-ad01-c3320b79d9bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NzQ2MjMsIm5iZiI6MTcwNDk3NDMyMywicGF0aCI6Ii8xNjAxOTI4OS8yOTU4NzE3ODMtODc5ZWQ4MTAtMDI2My00YWRkLWFkMDEtYzMzMjBiNzlkOWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDExNTg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxODMyYTcwYmIwNzJiNWQxYzAwMWY4NjljNTRiMzFkYzEzMWEyNzI5OTFjYTBmYzAyZDY4NzZlZmRhYTljMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RlDyf9rqat71clPGhvayI9fUana3LcQ2b1hcOY6enC4">
> 
>  Screen.Recording.2024-01-11.at.11.09.26.mov 
> Have you disabled your overrides ?
> 
> <img alt="Screenshot 2024-01-11 at 11 11 08" width="931" src="https://private-user-images.githubusercontent.com/16019289/295873413-95379dad-177e-412a-9a08-3261f7d55995.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NzQ2MjMsIm5iZiI6MTcwNDk3NDMyMywicGF0aCI6Ii8xNjAxOTI4OS8yOTU4NzM0MTMtOTUzNzlkYWQtMTc3ZS00MTJhLTlhMDgtMzI2MWY3ZDU1OTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDExNTg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzMjdlODNmNjA3NzY0ODJhOWRmZmY4Yzc2YThkOWIyNmVlYWIyM2VhMzhiMTg3OGQwZDJjYmMyMTFkMjYwYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4YkcfgllXhiQk3QjUaR1Q_cNmLdyIly0Dhw0yzyk9IQ">

Sorry, but I'm not an expert. From what I understood. Moving from 8.1.1 to 8.1.3, all non-native modules have been disabled. I manually enabled the modules and the store works normally. For the update I used 1 click upgrade. This didn't usually happen to me.

**Comment by z3n4j** [comment]
> @z3n4j Can you check if ps_connections_source exists in your database? Apparently it doesn't, meaning your install was corrupted before the upgrade.
> 
> This is a core table and must be present in every prestashop install.

Hi.
In the db I have the ps_connections table, but not the ps_connections_source table

**Comment by Hlavtox** [comment]
OK, so your installation is corrupted.

Run following query in phpmyadmin and your shop should work

```sql
CREATE TABLE `ps_connections_source` (
  `id_connections_source` int(10) unsigned NOT NULL auto_increment,
  `id_connections` int(10) unsigned NOT NULL,
  `http_referer` varchar(255) DEFAULT NULL,
  `request_uri` varchar(255) DEFAULT NULL,
  `keywords` varchar(255) DEFAULT NULL,
  `date_add` datetime NOT NULL,
  PRIMARY KEY (`id_connections_source`),
  KEY `connections` (`id_connections`),
  KEY `orderby` (`date_add`),
  KEY `http_referer` (`http_referer`),
  KEY `request_uri` (`request_uri`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8mb4 COLLATION;
```

For the next upgrade, I suggest hiring an expert. 👍
