### ISSUE TITLE
Upgrade to develop branch broken because of AppKernel

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#35029]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Upgrade to develop branch is broken, ending in an error `Cannot instantiate abstract class AppKernel`.

It's caused by https://github.com/PrestaShop/autoupgrade/blob/dev/classes/UpgradeTools/SymfonyAdapter.php doing `$kernel = new \AppKernel($env, _PS_MODE_DEV_);`

This worked in the past, but recently the class has been changed in https://github.com/PrestaShop/PrestaShop/pull/32719/files to `abstract` and two new children has been made - `FrontKernel` and `AdminKernel`.

![screenshot_2024-01-11_at_15 28 16](https://github.com/PrestaShop/PrestaShop/assets/6097524/605c4ac3-00ba-4c06-883a-e294d9cb3005)

Reproduced by @florine2623

### Expected behavior

There are two solutions.
- Removing the abstract keyword. I tried it and all works OK. There are no abstract methods in that class so the keyword is not needed.
- Instantiate AdminKernel instead, but that would need to bring some conditions into play and some other stuff.

### Steps to reproduce

Upgrade from 8.1.x to develop branch.

### PrestaShop version(s) where the bug happened

upgrade from any version to 9.0.0

**Comment by florine2623** [comment]
Not sure about the Severity, so I'll the PM decide ^^

**Comment by Hlavtox** [comment]
@MatShir company PM needed

**Comment by Hlavtox** [comment]
Ping @jolelievre @mflasquin, guys can you check? It's blocking upgrades to develop.

**Comment by MatShir** [comment]
@Hlavtox major seems right. There are still a lot of problems upgrading to version 9.0. We are in the process of completing the SF 6.4 upgrade, then we will be working on making the versions upgradable to 9.0 ;)

**Comment by Hlavtox** [comment]
Ping @M0rgan01 @jolelievre Guys please check this, so we can test upgrade things to 9.0 :-)

**Comment by jolelievre** [comment]
I think the second solution is better:
- Instantiate AdminKernel instead, but that would need to bring some conditions into play and some other stuff.

It's not that complex, we'd just need to check if `AdminKernel` exists then this is the class to use, if not fallback to AppKernel

**Comment by matks** [comment]
@Hlavtox I wanted to clarify something: making sure people can upgrade from current `8.1.x` branch to `develop` branch is not a priority right now for PrestaShop company teams

V9 is still far away, and the time/energy we could put in that topic is something that would have to be taken away from something else.

`Upgrade from 8.1.x to develop branch` is not something supported right now and it is expected IMO

If you want to improve the topic, you can submit PRs but I want to clarify the company teams don't plan to invest a lot of time in this topic now. This time will come later 😉 .

**Comment by Hlavtox** [comment]
@matks Yes, but the company is blocking other people from working and QA people from testing PRs with changes. I think that when SA employees make and merge a PR that breaks it, they can invest some time to fix it, so they don't block other people.

Also, what is the difference in fixing it now and fixing it later? Other than having upgrades broken for longer?

**Comment by matks** [comment]
> @matks Yes, but the company is blocking other people from working and QA people from testing PRs with changes. I think that when SA employees make and merge a PR that breaks it, they can invest some time to fix it, so they don't block other people.

It does not work like that for nobody. If we find tomorrow that https://github.com/PrestaShop/PrestaShop/pull/35259 has broken something we do not ask the PR 35259 author to fix it. It was reviewed, approved, tested, merged -> too bad for us if we broke something.

So no `when SA employees make and merge a PR that breaks it, they can invest some time to fix it` rule, for PrestaShop SA or for anybody.

> Also, what is the difference in fixing it now and fixing it later? Other than having upgrades broken for longer?

Because we have other things to do at the moment, and working on this now obliges us to postpone our current priorities. Can't do both. If you work on A you have to abandon B, if you work on C you have to give up on D. Got two hands and 24 hours per day, no more ;)

**Comment by ga-devfront** [comment]
PR for fix need to be reviewed ⇾ https://github.com/PrestaShop/autoupgrade/pull/679
