### ISSUE TITLE
Prestashop 8.0.0 cannot be upgraded

### ISSUE THREAD

**Issue by asamex** [PrestaShop/PrestaShop#35038]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

With my Prestashop 8.0.0 I cannot update many modules, there are more and more. The “Payment by bank transfer” module does not appear in the front office when you want to pay. Someone in the forum advised me to upgrade. I wanted to do that and version 8.0.5 was suggested to me. I then put the shop in maintenance mode and started the upgrade. It didn't end and got stuck. You could see a field with red error messages. I then canceled the matter and contacted Prestashop Helpdesk. They referred me to them. The “Assistance by Prestashop” module is also installed.
![Backup auf 8 0 5-1](https://github.com/PrestaShop/PrestaShop/assets/155176745/51e2c7ad-39d4-48ef-b9ba-831c9210f71f)
![Backup auf 8 0 5-2](https://github.com/PrestaShop/PrestaShop/assets/155176745/46bc4b99-0b90-4618-b217-16bf8d549d96)

How can I upload a video?

### Expected behavior

![Version2](https://github.com/PrestaShop/PrestaShop/assets/155176745/f0268e23-0ee8-4336-8822-1cb0d62422c3)
I thought that an automatic upgrade would fix the errors. Unfortunately that was not the case as this upgrade was not completed
![Module](https://github.com/PrestaShop/PrestaShop/assets/155176745/df66e774-e2e3-4f12-a70c-c83e65491025)
![Zahlung](https://github.com/PrestaShop/PrestaShop/assets/155176745/761aae29-a7a0-48e3-a9ff-3c284291f9ff)
![Zahlung2](https://github.com/PrestaShop/PrestaShop/assets/155176745/d7398ec7-6ab1-4d31-a4a8-e4b1d53e1a3b)
![Zahlung3](https://github.com/PrestaShop/PrestaShop/assets/155176745/2e2803ab-9489-4de7-a9fb-b752c7c3f4ec)
![Version](https://github.com/PrestaShop/PrestaShop/assets/155176745/5cc9d68c-ec3c-4037-b9e2-33d4a6a80969)

### Steps to reproduce

1. Set maintenance mode
2. Save
3. Click Upgrade
4. Check if all ticks are green
5. Then start the automatic upgrade

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.2.14

### Your company or customer's name goes here (if applicable).

asamex

**Comment by Hlavtox** [comment]
Prestashop 8.x.x does not support PHP 8.2, change your PHP version and try again.

**Comment by asamex** [comment]
Hallo

Bei der Version Prestashop 8.0.0 habe ich folgende Änderungen gemacht und
es hat sich nichts geändert:

Ich habe PHP von 8.2 auf 8.1 zurück gesetzt
Es gibt keinerlei Änderung
Die Module lassen sich nicht aktualisieren
Die Zahlungsform "Banküberweisung" erscheint nicht

Hello

In the Prestashop 8.0.0 version I made the following changes and nothing
changed:

I reset PHP from 8.2 to 8.1
There is no change whatsoever
The modules cannot be updated
The payment form “bank transfer” does not appear



[image: PHP zurück gesetzt1.jpg]

[image: PHP zurück gesetzt2.jpg]

[image: Module 15.jpg]

[image: Bankzahlung.jpg]















*Met vriendelijke groet, best regards,*



*Jorg Timm*

*CEO*

**Comment by paulnoelcholot** [comment]
Hello @asamex,

I tried to reproduce your issue but as you can see, I can't : https://www.loom.com/share/075b40b925e545b6ba18c1ed6840ab50?sid=c02fa132-7ce6-4a38-8bd7-5d5a1e9e2303

Did I miss something?

Thanks for your feedback!

**Comment by asamex** [comment]
Hello,

I also took a video of the screen and copied the error code or error
message that appears. Where can I upload the video so you can see it? I am
attaching the error message as a file.


*Met vriendelijke groet, best regards,*



*Jorg Timm*

*CEO*

**Comment by florine2623** [comment]
You need to answer directly via GitHub, not via email.

**Comment by asamex** [comment]
Hello,

When I try to upgrade from 8.0.0 to 8.0.5 it stops and the following error message appears

![Fehler1](https://github.com/PrestaShop/PrestaShop/assets/155176745/88921623-aca0-4ff7-a20c-7ba053a0afc3)
[Fehler.pdf](https://github.com/PrestaShop/PrestaShop/files/13974761/Fehler.pdf)

**Comment by florine2623** [comment]
Hello @asamex ,

I can't reproduce your issue upgrading from 8.0.0 to 8.0.5.
<img width="388" alt="Screenshot 2024-01-18 at 14 15 28" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/64822f4a-887d-4349-95c9-d51a54c8a8c7">

Upgrade completed :
<img width="1208" alt="Screenshot 2024-01-18 at 14 20 25" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/533cac87-25af-45ff-929b-cee7981a2888">

Also, please modify your admin folder for security reasons. This is a public space.

I'm closing your issue as I can't reproduce your issue.

**Comment by asamex** [comment]
Hello,

I get this error message
![Fehler1](https://github.com/PrestaShop/PrestaShop/assets/155176745/f17de942-4a79-4c72-a5f0-64864bcc00d2)

**Comment by asamex** [comment]
Hallo

Eine andere Frage: Warum ist diese Feld der Artikelbeschreibung so schmal bei der Version 8.0.0? Gibt es die Möglichkeit dieses zu verbreitern weiter nach links damit man den Text richtig lesen kann? Wenn ja wie kann ich dieses ändern oder einstellen?

Hello

Another question: Why is this item description field so narrow in version 8.0.0? Is it possible to widen this further to the left so that you can read the text correctly? If so, how can I change or adjust this?

https://github.com/PrestaShop/PrestaShop/assets/155176745/99309118-85a9-4b05-a62e-5885a2d3e55f

**Comment by asamex** [comment]
Hello,

so far they haven't solved the problem. So far everything is only getting
worse. Now the email messages no longer work when an order is received or
you want to communicate with customers. The order status is also no longer
sent by email. At least it worked before. Are you sure that you are
professionals? The Prestashop always works worse instead of better. It
can't be that the "specialists" can't fix these problems. It's been like
this for many months now.


*Met vriendelijke groet, best regards,*



*Jorg Timm*

*CEO*
