### ISSUE TITLE
Admin Search error when token disabled

### ISSUE THREAD

**Issue by simulbeni** [PrestaShop/PrestaShop#35065]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Turn off token from Advanced Parameters -> Security and admin search will start giving error.

### Expected behavior

Show search results.

### Steps to reproduce

1. Advanced Parameters
2. Security
3. Back office token protection turn this off 
4. Search with any number 
5. It will give error

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1

**Comment by AureRita** [comment]
Hi @simulbeni 

Thank you for your report, Despite my effort, I can't reproduce your issue as you can see : 

[recording(60).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/6d2ca50f-fd7e-4efc-9572-e772e186a4b8)

Did I miss something ? 
Can you provide us a video to see the error ? 

Waiting for your feedback

Thank you

**Comment by paulnoelcholot** [comment]
Hello @simulbeni,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
