### ISSUE TITLE
Upgrade to Symfony 6.3

### ISSUE THREAD

**Issue by WahbiPS** [PrestaShop/PrestaShop#35066]
Upgrade from Symfony 6.0 to Symfony 6.3

Also we should keep in mind what Symfony recommends in its step by step migration guide for each version:
- https://github.com/symfony/symfony/blob/6.4/UPGRADE-6.1.md
- https://github.com/symfony/symfony/blob/6.4/UPGRADE-6.2.md
- https://github.com/symfony/symfony/blob/6.4/UPGRADE-6.3.md

We must prevent the usage of already deprecated methods/code as much as possible.

> [!NOTE]  
> This hunt on deprecated code can be done in separated PRs if the upgrade PR is already too big

**Comment by MatShir** [comment]
Blocked by #35069
