### ISSUE TITLE
Error 500 when placing an order when placing an order as a guest. Cash on delivery (COD) v2.0.1 - from PrestaShop.

### ISSUE THREAD

**Issue by embeembe** [PrestaShop/PrestaShop#35061]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have an issue with the basic Cash on delivery (COD) v2.0.1 - from PrestaShop
 module in my PrestaShop store. I am using version 8.0.4 on a server with PHP 7.4. Cash On Delivery is the only available option in my store. When a customer placing an order has an account and is logged in, everything works fine. Unfortunately, if a customer wants to place an order without creating an account as a guest, an error 500 occurs in the order process just before the last screen confirming the order. After refreshing with F5, it proceeds to the order confirmation page (but the guest's email address is not entered there). This happens every time. I have searched for a solution to this problem online, but there is no specific solution available. I've noticed that more people are experiencing this issue.
![1](https://github.com/PrestaShop/PrestaShop/assets/156842422/32b491ea-bc30-45ff-93b4-e7b50f55e31b)
![2](https://github.com/PrestaShop/PrestaShop/assets/156842422/3cff8ebd-9d83-474a-8e49-ab9ba302b100)
![3](https://github.com/PrestaShop/PrestaShop/assets/156842422/5621f2f0-d855-4a88-a5f7-081f04fd5678)

### Expected behavior

I would like to resolve the 500 error when a guest places an order, and I would also like the guest's email address to appear on the order confirmation page.

### Steps to reproduce

1. I navigate to the product page.
2. I click the "Buy Now" button on the product page.
3. On the shopping cart page, I click the "Proceed to Checkout" button.
4. I fill in the fields for first name, last name, shipping address, email address, and phone number. I leave the password field blank.
5. I agree to the terms and conditions and the privacy policy. I click the "Continue" button.
6. I click the "Continue" button when selecting the Shipping Method. Since I have only one carrier to choose from, I simply confirm by clicking "Continue."
7. In the "Payment" tab, I already have the Cash On Delivery option selected as it is the only payment method available in the store. I check the "I agree to the terms of service as set out by the user agreement" box and click the "Place Order" button.
8. I receive a 500 error. This page is not working. HTTP ERROR 500.
9. I refresh the page with F5 and receive the order confirmation page, but the email information does not include the email address.

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

Cash on delivery (COD) v2.0.1 - from PrestaShop

### Your company or customer's name goes here (if applicable).

Martin

**Comment by Hlavtox** [comment]
Enable debug mode, simulate this issue and post the exact error message here. :-)

**Comment by embeembe** [comment]
> Enable debug mode, simulate this issue and post the exact error message here. :-)

After enabling debugging mode, I immediately encounter 1 error on the homepage:
Warning: Declaration of Link::getProductLink($product, $alias = NULL, $category = NULL, $ean13 = NULL, $idLang = NULL, $idShop = NULL, $ipa = 0, $force_routes = false, $relativeProtocol = false, $addAnchor = false, $extraParams = Array) should be compatible with LinkCore::getProductLink($product, $alias = NULL, $category = NULL, $ean13 = NULL, $idLang = NULL, $idShop = NULL, $idProductAttribute = NULL, $force_routes = false, $relativeProtocol = false, $withIdInAnchor = false, $extraParams = Array, bool $addAnchor = true) in /home/meblinonvd/meblinonl/override/classes/Link.php on line 67

I don't know if I'm doing everything correctly, but when placing an order in debugging mode, I can't click the "Place Order" button. Nothing happens.

**Comment by AureRita** [comment]
Hi @embeembe 

Thank you for your report, Despite my effort, I can't reproduce your issue as you can see : 

[recording(58).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/ec9d6f05-75bb-42e7-84d6-63789611c711)

With the details you give with your debug mode, can you give us more information about the product you put in the cart ? 
Did you take more than 10 minutes to complete your order ? 
Did you reproduce it if you put other product in your cart ? 

Waiting for your feedback, 

Thank you

**Comment by Hlavtox** [comment]
@embeembe You have some overrides (along with other issues) that are faulty, I suggest hiring an expert to fix your issues. :-)

**Comment by embeembe** [comment]
> With the details you give with your debug mode, can you give us more information about the product you put in the cart ?
> Did you take more than 10 minutes to complete your order ?
> Did you reproduce it if you put other product in your cart ?

This happens with every product from the store when ordered as a guest. If the customer is logged in, there is no such issue.
The order takes less than a minute. Just like in your video.
I have seen that several people are experiencing the same issue with the same module. They are reporting the same symptoms and encountering error 500. I have tried solutions that I found, including reinstalling the module, etc. 
I would be willing to provide access to the store so that you can investigate it yourself.

**Comment by florine2623** [comment]
Hello @embeembe ,

The issue comes from your file `/home/meblinonvd/meblinonl/override/classes/Link.php`

You must have added some custom code to it.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

I'm closing your issue.

Thank you

**Comment by darkWolf-PR** [comment]
@embeembe go to performance settings and check "disable all overrides" ( or remove file `/override/classes/Link.php` ) and try again - or search through your modules, which one adds this override, that module is not compatible with with your PS version probably. That file is not from the COD module, so reinstalling it will not change anything.
