### ISSUE TITLE
Issue with variants in product creation (shopId=NaN)

### ISSUE THREAD

**Issue by imclint21** [PrestaShop/PrestaShop#35074]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the variants tab of the product view, variants are not loading...

I can see a shopId=NaN in the Ajax calls...

<img width="1505" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/5221349/cdbe2a04-d5ab-4a08-87c8-ac6bad2e51fb">

### Expected behavior

Just loading of this tab correctly

### Steps to reproduce

1. Create a new product
2. Open variant tab

### PrestaShop version(s) where the bug happened

8.1.2

**Comment by florine2623** [comment]
Hello @imclint21 ,

Please modify your admin folder name for security reasons. This is a public space.

I can't reproduce your issue.

<img width="1440" alt="Screenshot 2024-01-18 at 09 34 22" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/802d2cc9-1e7f-4a95-8824-62664d1cf1b0">

Are you using the multistore option ?

**Comment by imclint21** [comment]
Hello,


Oh I didn't saw, I'll change it!

No only one store but I discovered that the ps_store table was empty and then I went in the contact/store page and created one store, but does not fix the problem,

**Comment by florine2623** [comment]
Can you enable the debug mode please and try again ?
Advanced parameters > Performance > Enable debug mode

On my end, the shop id is present :

https://github.com/PrestaShop/PrestaShop/assets/16019289/55c20c23-ea7d-4fb4-9f6b-5f7b2e8ccabd

**Comment by imclint21** [comment]
Sure,

I have this when I go to contact > stores

<img width="1497" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/5221349/65195d57-fb80-4ed4-93e1-50cf5bb78c47">

**Comment by imclint21** [comment]
I tried to display the shopId from the index.php with this and it works;

```php
echo Context::getContext()->shop->id;
```

**Comment by florine2623** [comment]
This is an error with a template module iqit extended product.
You should contact the develop of the theme direct for this issue.

In the Add product page > Combinations, with debug mod enabled, do you have any error ?

**Comment by imclint21** [comment]
I got this

<img width="808" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/5221349/69932395-8e88-46d5-aecb-7ec3b89b309b">

**Comment by florine2623** [comment]
Do you have any overrides ? Go to Advanced parameters > Performance > Disable overrides
<img width="496" alt="Screenshot 2024-01-19 at 09 35 11" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/14e0695d-9e51-4171-9187-4d20d2328164">

I suggest disabling them and try again.

**Comment by imclint21** [comment]
Hmm does not change nothing, what mean `Warning: Undefined array key "config_file_url"`?

**Comment by florine2623** [comment]
I don't know, it's not error that happens on the core of PrestaShop.
I can't reproduce the same issue as you with a fresh install.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by imclint21** [comment]
Do you think we should reinstall it?

**Comment by imclint21** [comment]
Finally the problem come from this plugins: https://addons.prestashop.com/fr/declinaisons-personnalisation/47181-champ-personnalise-du-produit.html

**Comment by imclint21** [comment]
@florine2623
