### ISSUE TITLE
Coupons problem

### ISSUE THREAD

**Issue by cnclove69** [PrestaShop/PrestaShop#35105]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello everyone,

I'm having a problem with promotional codes.

Some promotional codes have been used and validated even though their end date has passed. How is it possible ?

Additionally, some codes stopped working for a few days and then worked again... very strange.

Thank you for your help and have a nice day everyone!

### Steps to reproduce

promotional code problem. 

### PrestaShop version(s) where the bug happened

1.7.8.6

**Comment by florine2623** [comment]
Hello @cnclove69 ,

Your issue is the same as : https://github.com/PrestaShop/PrestaShop/issues/26235

I'm closing it to avoid clogging the backlog. You can follow the updates directly there.
