### ISSUE TITLE
Logging in error

### ISSUE THREAD

**Issue by djwayne1985** [PrestaShop/PrestaShop#35115]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When ever i log in no matter what option i select it logs me back out

### Expected behavior

I would expect to go to the option i have selected so i can configure my store.

### Steps to reproduce

Logged in 
Whent to settings option
Got logged straight out

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

7.4

**Comment by Hlavtox** [comment]
Happens to me also sometime after fresh install or re-pull from git. Any idea @kpodemski ?

**Comment by AureRita** [comment]
Hi @djwayne1985 

Thank you for your report, despite my effort, I can't reproduce your issue as you can see : 

[recording(69).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/7deb19b7-1fc0-44ea-90f3-85a9e653b281)

Did I miss something ? 
Your settings that you mentioned is "your profile" settings ? 
Can you provide a video ? 

Waiting for your feedback

**Comment by djwayne1985** [comment]
How would i pm you the screen record please as it has my domain on it and i would rather just pm you the video pal

**Comment by paulnoelcholot** [comment]
Hello @djwayne1985,

Unfortunately we cannot accept private messages. I invite you to use a screen recorder (like loom) which allows you to record only your tab (and therefore your domain name will not be visible)

Waiting for your feedback

**Comment by florine2623** [comment]
I'm closing the issue as it cannot be reproduced.
