### ISSUE TITLE
BO Product page - Unit price is not translatable

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#35110]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Same issue on Old Product Page and New Product Page.
I can't add a unit value for different language.
If I add "per kilo", il will always be "per kilo" for all the languages enables on my shop.

<img width="925" alt="Screenshot 2024-01-19 at 17 14 16" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/d0f67203-39b4-4ef4-81ca-05e7d01b98f1">

### Expected behavior

I should be able to translate this element for all my languages.

### Steps to reproduce

1. Make sure you have at least 2 active languages
2. Go to BO > Products > Edit any product
3. Go to Pricing tab > Enable Display retail price per unit 
4. See that you can only add a unique value for the Unit element :x:

### PrestaShop version(s) where the bug happened

8.1.x, develop

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment]
Good find, but it's like this since ever, not really a bug. :-) We can consider it a feature request. Ping @prestashop/product-council

**Comment by AureRita** [comment]
Hi @florine2623 

Thank you for your report, as Hlavtox said, we can consider it like a feature request. 
As view with you, I'll transform this issue into discussion to speak about this new feature. 

Thank you
