### ISSUE TITLE
Unit sales price (excluding tax) does not update when changing prices via webservice

### ISSUE THREAD

**Issue by Ronald72a** [PrestaShop/PrestaShop#35128]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Good morning this is my first post (thanks for google traduction from french to english),

My problem is that the unit price on PS 8.1.2 does not change on Prestashop when I update the price via the webservice.

I first create an item which has a price of €25 excluding tax and I add in the 'Price' tab the price per meter which is €1 excluding tax
Then I modify the price in my commercial management to €50 excluding tax
With the e-Connector using the Webservice the price of the article and well updated
To be sure that this is not an unchecked option, I created a profile in which I checked ALL the boxes in the webservice!
Once the update has been carried out, the price has increased to €50 excluding tax but the unit price remains at €1 per meter
![image](https://github.com/PrestaShop/PrestaShop/assets/100924786/fb089f8d-a504-4f42-a094-8df19779a971)

![image](https://github.com/PrestaShop/PrestaShop/assets/100924786/23c1cfa8-4c5f-4f49-b3f3-d2da6d532d49)

![image](https://github.com/PrestaShop/PrestaShop/assets/100924786/a48a0752-eb04-423d-9761-45083e376e3f)

### Expected behavior

Normally the unit price should change when the price of the product changes, in this case the price per meter should increase to €2 excluding VAT per meter since the price for 25 meters has doubled

### Steps to reproduce

1 Create an item with a unit price
2 modify the price via the webservice
3 note that the unit price does not change while the price of the item has changed

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

7.4.25

### Your company or customer's name goes here (if applicable).

AMMERLAAN Ronald

**Comment by paulnoelcholot** [comment]
Hello @Ronald72a

Thank you for your contribution! Could you tell me more about the action you carry out via the webservice?

Thanks for your feedback

**Comment by Ronald72a** [comment]
Hello @paulnoelcholot 

I asked to the support Vaisonet of the Module "E-connector" to explain here how it carry out ;) 
I hope they will 

thanks Ronald

**Comment by florine2623** [comment]
Hello @Ronald72a ,

I tested on PS 8.1.x, I can't reproduce your issue.

https://github.com/PrestaShop/PrestaShop/assets/16019289/5ee151e3-6067-4bf7-b2fb-002b106e1642

Waiting for your feedback.

**Comment by Ronald72a** [comment]
Hello @florine2623 
Sorry, didn't now that with the Webservice you need to send the  <unit_price>  and it's not a automatic calculation when the price changes, like when you change the price directly on PS
So I need to create these information in my system ERP and send it with the SDK E-connecteur.
[](https://assistance.e-connecteur.fr/support/solutions/articles/9000152844-comment-envoyer-des-champs-ebp-standard-non-pris-en-charge-par-e-connecteur-)

Thank you all for your attention :) and sorry for losing your time ;) 
Ronald

**Comment by AureRita** [comment]
Hi @Ronald72a 

You're Welcome, you didn't just waste our time, you allowed us to check a potentially sensitive point. We take all comments into consideration. So thank you for taking the trouble to fill in an issue and for giving us as much information as possible.  

Thank you, I'll close the issue
