### ISSUE TITLE
Warning on every Backoffice page when there are no Quick Access pages created

### ISSUE THREAD

**Issue by mcaldex** [PrestaShop/PrestaShop#35136]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When there are no Quick pages created and debug mode is enabled, you get an warning message in almost every page of Backoffice.

This could be easily fixed by modifying these two .tpl files:

- admin-dev/themes/new-theme/template/components/layout/mobile_quickaccess.tpl
- admin-dev/themes/new-theme/template/components/layout/quick_access.tpl

and by wrapping the foreach loops within an if statement, so this:
`{foreach $quick_access as $quick}
......
 {/foreach}`

becomes:

` {if $quick_access}
    {foreach $quick_access as $quick}
....
    {/foreach}
  {/if}`

### Expected behavior

bo pages load correctly

### Steps to reproduce

1. Click on "Manage quick accesses" under the Quick Access menu available on every Backoffice page
![image](https://github.com/PrestaShop/PrestaShop/assets/79152536/6efbdc47-2336-4b39-8a3d-50175ec1c23a)
2. Delete every entry in there
3. Enable debug mode
4. Go to another Backoffice page, eg. Orders
5. See error:
![image](https://github.com/PrestaShop/PrestaShop/assets/79152536/4e1b9f3d-949f-43df-9bbd-6733845f28d8)

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

Hostinato

**Comment by paulnoelcholot** [comment]
Hello @MHostinato,

I reproduce the issue with PrestaShop version 8.1.x, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/2eaac20d-e379-46db-af23-e2a565056916)
