### ISSUE TITLE
Canonical Url is missing from the homepage

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#35133]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
I've seen that the homepage is without the canonical url. I think it is very useful to prevent duplication issues

using this code into head.tpl the problem is fixed

![1](https://github.com/PrestaShop/PrestaShop/assets/653230/3df97028-cecd-4033-b5d0-9ef9f2a0e31c)

the better solution should be using Controller::getCanonicalURL() method to assign it to $page.canonical

canonical URLs are used to protect pages from duplication, both internal to the site and external if they made a copy of the site on other servers. at an SEO level, in this way Google would only index the reported page.
you can see it on Google Search Console, for example with sites that have multiple languages and currencies, you would see that Google reports duplication errors because it sees duplications without a canonical URL. A bit like what happens with pagination

bye

### Steps to reproduce

1. go to the homepage
2. open the source code of your browser
3. search for canonical url

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment]
@maofree you are perfectly right, I checked all pages and this is what I found.

**Should be implemented**
- AuthController (login)
- CmsController
- ContactController
- GuestTrackingController
- IndexController (homepage)
- PasswordController
- RegistrationController
- SitemapController
- StoresController

Ping @PrestaShop/product-council

**Comment by jolelievre** [comment]
I also think it should be handled in the controller to keep the consistency, in other pages it's the controller that specifies it and sometimes the logic can be a bit complex so easier to handle on the PHP side to keep the template simple

**Comment by Hlavtox** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/35134
