### ISSUE TITLE
Href Lang tag issue with attribute id

### ISSUE THREAD

**Issue by tibethills** [PrestaShop/PrestaShop#35143]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi, I need help with a problem I have when enabling multi-language on my website. It turns out that in the default language of my site (in my case Spanish) everything works correctly. The problem arises with the attributes of the products when using them as combinations because in the default version of my site works perfectly but in the English, French or German version of my website when I want to select a combination of the product and add it to the cart, I get an error 404 undefined. I have already investigated what could be and I saw in forums that if you do not have translated the names of the combinations can generate this error. However I have everything translated to the corresponding language and still I get the error undefined.

### Expected behavior

You should be able to add the product combination to the cart when you are visiting the site in English, German, French or any other language.

### Steps to reproduce

1- Go to intermaquinas.es
2- Search for a product with combinations ( here you have one to see the failure: https://intermaquinas.es/motobombas-generadores-tractor/motobomba-pto-zeppelin-125-hp-258491-259134#/258993-motobomba_pto_zeppelin_125_hp-motobomba_pto_60m3_h_caudal_es70609 )
3- Check that in the spanish version (default) of the site the combinations work well.
4- Select the english, french or german language of the flags in the header.
5- Select again a combination of the product to add to the cart the product in the english version.
6- See the undefined error that occurs when selecting the combination and see that you can not finalize the purchase.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.33

### Your company or customer's name goes here (if applicable).

Spainlex Global Center SL

**Comment by florine2623** [comment]
Hello @tibethills 

It seems like you have the same error as https://github.com/PrestaShop/PrestaShop/issues/27977 but with different steps to reproduce.

Although I couldn't reproduce the issue on my shop 8.0.x, 8.1.x and on develop branch.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by tibethills** [comment]
No @florine2623 is not the same issue. The #27977 bug is for virtual products in quickview but my issue is with multilanguages and product combinations.
