### ISSUE TITLE
prestashop 8 can not show sample data product category on the main menu when i resave the sample data product category

### ISSUE THREAD

**Issue by sangdiyage** [PrestaShop/PrestaShop#35177]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

prestashop 8 can not show sample data product category on the main menu when i resave the sample data product category with no updated on this product category, i see the main menu module on backend, it has the product category 
![image](https://github.com/PrestaShop/PrestaShop/assets/1712390/4d8f4709-e838-49f1-b689-b0681fd2ed92)
![image](https://github.com/PrestaShop/PrestaShop/assets/1712390/2ebab901-81f9-4ecc-8102-215c3b91581f)
![image](https://github.com/PrestaShop/PrestaShop/assets/1712390/a344ebde-f812-4169-b059-6203a76ef850)

### Steps to reproduce

1, Install Project whth sample data
2, login the backend
3, resave one product category
4, missed on front main menu

### PrestaShop version(s) where the bug happened

8.x

### PHP version(s) where the bug happened

8.1

**Comment by AureRita** [comment]
Hi @sangdiyage 

Thank you for your report. Despite my effort, I can't reproduce your issue as you can see : 

[recording(83).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/eb0e4347-13f6-47ff-b29a-fc0bc4bd48bc)

Did I miss something ? 
Can you give us a video ? 
About your Prestashop version, is it 8.0.x ? or 8.1.x ? 

Did you do anything else ? 

Waiting for your feedback

**Comment by florine2623** [comment]
Hello @sangdiyage ,

Make sure that you have the name of the category in your language.

Your issue can't be reproduced.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
