### ISSUE TITLE
Error on ps_edition_basic Route error:500

### ISSUE THREAD

**Issue by msaustral** [PrestaShop/PrestaShop#35170]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The module ps_edition_basic on file src->Presetner->SetupGuideDataPresenter.php line 168 is pointing to a route that does not exist
'href' => $router->generate('admin_logos_index'),

This is causing an error 500 on BO as such route does not exist

![image](https://github.com/PrestaShop/PrestaShop/assets/46203943/0ebb3a85-a767-4fe8-b4f0-e0c1217bfe9f)

### Steps to reproduce

Enter to BO with debug on

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_edition_basic

### Your company or customer's name goes here (if applicable).

Multiservicios Austral (PS partner)

**Comment by paulnoelcholot** [comment]
Notified to Edition team, they will take care of it.

**Comment by RiKaZaRai** [comment]
This problem isn't solved...
Upgrade 8.1 -> 8.2.1 and i have a same bug
