### ISSUE TITLE
Shipping cost dissapeared

### ISSUE THREAD

**Issue by huyhoang8398** [PrestaShop/PrestaShop#35184]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi, 

When I do my quotations, I manually specify shipping costs ( 200 eur for example )
![image](https://github.com/PrestaShop/PrestaShop/assets/25379882/1a5e8ea6-b3ef-4a7d-8523-436d7d2f57cb)

After that, I download my invoiced and it says well with my manually shipping costs fee.
But When I go to order -> view invoice it disappear and saying free shipping instead.
And a warning message 
![image](https://github.com/PrestaShop/PrestaShop/assets/25379882/5ca0322f-c02a-4eb8-a1f5-d8994ac4dd9a)

### Steps to reproduce

1. Create quote
2. specify manuall shipping fee
3. Go to invoices

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

7.4.33

**Comment by AureRita** [comment]
Hi @huyhoang8398 

Thank you for your report, Despite my effort I can reproduce your issue as you can see : 

[recording(84).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/1de00813-d324-417f-be1c-6d57e43eaa9b)

Did I miss something ? 
I tested also with some carrier that offer the shipping and I have the correct behavior, 
Can you provide us a video or anything else ? 

Waiting for your feedback

**Comment by florine2623** [comment]
Hello @huyhoang8398 ,

This is not a native feature of PrestaShop. I suggest contacting the developer of the module directly.

I'm closing the issue.
