### ISSUE TITLE
"Order confirmation page" is NOT appearing when Mollie payment is used 

### ISSUE THREAD

**Issue by Juiliard** [PrestaShop/PrestaShop#35187]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

"Order confirmation page" is NOT appearing when Mollie payment method is used + user is Logged Out when returns from Mollie payment page. (Order is processed, but customer do not see "Order confirmation page" and have to login back to account to check the status of order)

I suspect problem is somewhere in Maria DB, because:
- clean PS8.1.3 + clean MariaDB + Mollie = all good
- clean PS8.1.3 + my current MariaDB + Mollie = no "Order confirmation page" + "Logged Out"

If I switched to Prestashop payment method (bank wire)= all good

Errors in console:
- jQuery.Deferred exception: Can't find variable: PluginDetect 
- ReferenceError: Can't find variable: PluginDetect

For info: 
- my own PS and DB was upgraded during years: 1.7.6 -> 1.7.8 -> 8.1.2 -> 8.1.3 (if i remember correctly) 
- I have been in contact with Mollie support and followed all advises (deactivate all non_native modules) = did not help

Question: how to fix errors mentioned in console ?

<img width="944" alt="Screenshot 2024-01-26 at 11 26 29" src="https://github.com/PrestaShop/PrestaShop/assets/58143423/f4ce3601-5b48-4ac4-a008-11dd4e038b3d">

### Expected behavior

"Order confirmation page" appears AND Customer stays logged in after payment.

### Steps to reproduce

1. clean install PS8.1.3 + clean DB + Mollie 6.0.4 = no problem
2. clean install PS8.1.3 (replace img + add my theme) + replace DB with my own + Mollie 6.0.4 = problem

### PrestaShop version(s) where the bug happened

8.1.2, 8.1.3

### PHP version(s) where the bug happened

8.1.18

### If your bug is related to a module, specify its name and its version

Mollie 6.0.4

**Comment by Hlavtox** [comment]
Hi @Juiliard, please contact author of Mollie 6.0.4, thank you for understanding. :-)
