### ISSUE TITLE
BO > Customer page - Exception thrown when I create an order from the BO with a customizable product

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#35190]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I create an order from the BO with a customizable product and a free shipping. I find an exception in the customer page. I can't take a look at the customer page.

https://github.com/PrestaShop/PrestaShop/assets/16019289/13550355-8456-47cb-b82a-d4c109e73ce7

<img width="1132" alt="Screenshot 2024-01-26 at 17 25 16" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/d70e400a-bca0-4c50-8d2d-4e67ceedf4d6">

`Warning: Undefined array key "id_address_delivery"`

### Expected behavior

The customer page should be displayed normally.

### Steps to reproduce

1. Go to BO > Orders > Add new order > Choose a customer
2. Add customizable mug to the cart > Add a customization > Add to cart
3. Choose Shipping : My carrier + Enable Free shipping
4. Choose any payment + Order status
5. Create order
6. Go to Customers > Customers > View your customer
7. Exception displayed :x:

### PrestaShop version(s) where the bug happened

develop only

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment]
@florine2623 I think I broke this one, I will fix it. :-)

**Comment by paulnoelcholot** [comment]
Hello @florine2623,

I reproduce the issue with PrestaShop version develop, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/80559511-d457-486f-97e9-f7706fb36652)
