### ISSUE TITLE
The server returned a "500 Internal Server Error".

### ISSUE THREAD

**Issue by SaulesMali** [PrestaShop/PrestaShop#35195]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Oops! An Error Occurred
The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

### Steps to reproduce

Oops! An Error Occurred
The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

### PrestaShop version(s) where the bug happened

Your current PrestaShop version: 8.1.3

### PHP version(s) where the bug happened

Your current PHP version: 8.1.27

### If your bug is related to a module, specify its name and its version

ps marketing

### Your company or customer's name goes here (if applicable).

Saules Māli

**Comment by Hlavtox** [comment]
@SaulesMali 

> Avoid reporting "error 500" or "white page" errors - this is a universal error message that does not provide enough information to qualify the issue. Enable debug mode in the Performance section of PrestaShop or manually in /config/defines.inc.php and try again. You should get a proper error message.

**Comment by SaulesMali** [comment]
cannot be opened "Enable debug mode in the Performance section of
PrestaShop""
Oops! An Error Occurred The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error
occurred. We will fix it as soon as possible. Sorry for any inconvenience
caused.

svētd., 2024. g. 28. janv., plkst. 22:03 — lietotājs Daniel Hlaváček (<
***@***.***>) rakstīja:

**Comment by Hlavtox** [comment]
@SaulesMali You can "enable debug mode manually in /config/defines.inc.php". 👍

**Comment by SaulesMali** [comment]
Thanks, which part to edit?

svētd., 2024. g. 28. janv., plkst. 22:27 — lietotājs Daniel Hlaváček (<
***@***.***>) rakstīja:

**Comment by AureRita** [comment]
Hi @SaulesMali 

It's on line 35 : "if (!defined('_PS_MODE_DEV_')) {
    define('_PS_MODE_DEV_', false);"
    
    Put this one on true
