### ISSUE TITLE
کنترل کننده AdminPsEditionBasicHomepageController یافت نشد یا نامعتبر است.

### ISSUE THREAD

**Issue by amir385276** [PrestaShop/PrestaShop#35193]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the BO menu i see this issue
کنترل کننده AdminPsEditionBasicHomepageController یافت نشد یا نامعتبر است.

### Expected behavior

کنترل کننده AdminPsEditionBasicHomepageController یافت نشد یا نامعتبر است.

### Steps to reproduce

کنترل کننده AdminPsEditionBasicHomepageController یافت نشد یا نامعتبر است.

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

7.4

**Comment by paulnoelcholot** [comment]
Hello @amir385276,

Please send your request in English. English is the norm on GitHub.

Thank you

**Comment by Hlavtox** [comment]
@amir385276 Not related to the open source project. Please contact prestashop.com support. :-)
