### ISSUE TITLE
The ps_searchbar module does not appear on mobile

### ISSUE THREAD

**Issue by BreizhAquario** [PrestaShop/PrestaShop#35209]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I install the ps_searchbar version 2.1.3 module, it appears on the web version of my site but does not appear on the mobile version.
I have already uninstalled then reinstalled the module, I also reset it but the problem persists.

### Expected behavior

I thought the module would work on the mobile version of my website.

### Steps to reproduce

1. Install the module
2. Activate on mobile

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.3.33

### If your bug is related to a module, specify its name and its version

ps_searchbar v2.1.3

### Your company or customer's name goes here (if applicable).

Breizh Aquario E.I

**Comment by AureRita** [comment]
Hi @BreizhAquario 

Thank you for your report, Despite my effort, I can't reproduce your issue as you can see : 

[recording(86).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/5302fde9-f66e-46da-8873-c0b802ba021c)

Did I miss something ? 
Did you do anything else with your shop ? 
Is the position of the searchbar is correctly set on your shop ? 

Waiting for feedback

**Comment by BreizhAquario** [comment]
Good morning,
I've already done this but it doesn't work. Note that I do not have the classic theme but a theme that I purchased.

**Comment by florine2623** [comment]
Hello @BreizhAquario ,

I suggest contacting the developer of the theme directly.

I'm closing the issue as it can't be reproduced with classic theme.
