### ISSUE TITLE
BO > Link list - Exception thrown when trying to change position

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#35218]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have an exception when I try to move the position of the block.

`Input value "positions" contains a non-scalar value.`
<img width="1081" alt="Screenshot 2024-01-30 at 14 22 39" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/6b2fb542-351e-4ecf-9ced-37fca3786acb">

### Expected behavior

Should work and have a alert message : successful update.

### Steps to reproduce

1. Go to BO > Design > Link list
2. Move position of block
3. See exception :x:

### PrestaShop version(s) where the bug happened

develop only

### PHP version(s) where the bug happened

8.1

**Comment by AureRita** [comment]
Hi @florine2623 ,

I reproduce the issue with PrestaShop version develop as you can see, 

[recording(88).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/b711a16c-d437-457c-b733-0ea2b7eb0502)

I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks
