### ISSUE TITLE
Manual update of prestashop to 8.x - ERROR after use: php modules/autoupgrade/upgrade/upgrade.php

### ISSUE THREAD

**Issue by mati771** [PrestaShop/PrestaShop#35224]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Before updating, I installed the autoupgrade module

I manually upgrade clean version 1.7.8.7 to 8.1.3
Official guide -> https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/upgrade-module/upgrade-cli/

![image](https://github.com/PrestaShop/PrestaShop/assets/63502371/f33dc971-5432-46b8-961a-0a8e4f71f687)
![image](https://github.com/PrestaShop/PrestaShop/assets/63502371/bf0296c9-1fcc-4d2f-8b56-655830e78357)
![image](https://github.com/PrestaShop/PrestaShop/assets/63502371/eedee197-b1a0-4b7e-892c-39c9d7fcebee)

`
PHP Warning:  require_once(/var/www/prestashop/modules/autoupgrade/upgrade/../../vendor/autoload.php): faile                      d to open stream: No such file or directory in /var/www/prestashop/modules/autoupgrade/upgrade/upgrade.php o                      n line 47
PHP Fatal error:  require_once(): Failed opening required '/var/www/prestashop/modules/autoupgrade/upgrade/.                      ./../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/prestashop/modules/autoupgrade/upgra                      de/upgrade.php on line 47
`

### Expected behavior

Update prestashop to latest version

### Steps to reproduce

1. unzip prestashop-upgrade.zip && unzip prestashop.zip
2. Remove folder img/ & override/
3. I am deleting a folder from an older version that is being updated - rm -rf vendor/
4. cp -R /var/www/prestashop-upgrade/* /var/www/prestashop/
5. cd /var/www/prestashop
6. php modules/autoupgrade/upgrade/upgrade.php
7. ERROR: 
PHP Warning:  require_once(/var/www/prestashop/modules/autoupgrade/upgrade/../../vendor/autoload.php): faile                      d to open stream: No such file or directory in /var/www/prestashop/modules/autoupgrade/upgrade/upgrade.php o                      n line 47
PHP Fatal error:  require_once(): Failed opening required '/var/www/prestashop/modules/autoupgrade/upgrade/.                      ./../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/prestashop/modules/autoupgrade/upgra                      de/upgrade.php on line 47

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

Autoupgrade

**Comment by AureRita** [comment]
Hi @mati771 

Thank for your report,
This issue is too technical for me, ping @PrestaShop/tech-council, can someone please reproduce this issue ? 

Thanks

**Comment by Quetzacoalt91** [comment]
Indeed, this file could not be used since the migration from PrestaShop to autoupgrade repositories.
The documentation has been modified to not rely on this file anymore on PS 8 (https://github.com/PrestaShop/docs/pull/1797).

The documentation website will be updated in the next following hours.
