### ISSUE TITLE
BO > Modules - API distribution doesn't retrieve all modules

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#35228]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I delete a native module, I should be able to reinstall it how I please.
This is a regression.

https://github.com/PrestaShop/PrestaShop/assets/16019289/3bc747d6-1ee0-4c2b-a02f-c927055d29f3

`Unable to retrieve informations from Distribution API : cannot automatically update native modules for the moment.`

Before the regression :

https://github.com/PrestaShop/PrestaShop/assets/16019289/436c86a6-dd92-434a-9efd-0e3a89824333

### Expected behavior

I should be able to reinstall the module after deleting it.

### Steps to reproduce

1. Go to BO > Modules > Search facetedsearch module
2. Uninstall module and check delete the module
3. See the module is not displayed anymore :x:
4. Refresh the page > Search the module : can't find it, can't install it back :x:

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

8.1

**Comment by matks** [comment]
Hello @florine2623 could you please verify again? I think it is fixed

8.1.4 is now acknowledged by Distribution API https://api.prestashop-project.org/modules/8.1.4

**Comment by florine2623** [comment]
I confirm this is fixed in PS 9.0.x.

https://github.com/user-attachments/assets/26de7ac9-8e03-4b38-b924-85e5b57a0a96
