### ISSUE TITLE
Clean install of 8.1.3 show error on backoffice when submit login | Requesting unavailable service

### ISSUE THREAD

**Issue by perezborja** [PrestaShop/PrestaShop#35229]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Recently, I downloaded the last version available of PrestaShop 8.1.3. Installation went  well, without any error.

Once is installed, and deleted /install folder, when try to log as admin into back-office, an error appears: 

```
You have requested a non-existent service "ps_edition_basic.module".
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException 0]
```

I have tried changed PHP version, and made a clean install multiple times, but always get the same error. Also, tried to manually delete /var/cache folder, but it nothing solved.
![Captura desde 2024-01-31 11-48-15](https://github.com/PrestaShop/PrestaShop/assets/113688106/260449aa-0faa-4d73-b712-ca10e8cce1b5)

This doesn't happen with PS 8.1.2.

### Expected behavior

It should show the back-office admin.

### Steps to reproduce

1. Download PrestaShop from: https://prestashop.es/versions/
2. Make a clean installation.
3. Delete /install folder
4. Login with admin credentials to back-office.

Then, error appears.

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

8.0, 7.4

**Comment by Hlavtox** [comment]
@perezborja You have download PrestaShop Edition.

PrestaShop Edition is a solution based on the open source project PrestaShop. It contains additional functionalities powered by modules directly installed at the creation of the store and is being built and distributed by PrestaShop company.

The bug you have encountered is specific to PrestaShop Edition, you contact  https://help-center.prestashop.com/ to get help about it.

Else you can download the prestashop open source project from https://github.com/PrestaShop/PrestaShop/releases

 I will close this issue as it's not related to open source project.

**Comment by Hlavtox** [comment]
Ping @PrestaShop/prestashop-sa
