### ISSUE TITLE
BO - Customer page throws exception when the customer deletes his addresses from his shopping cart

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#35233]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I delete all customer addresses from the shopping cart in FO, in BO i can't access the customer's page anymore.
Regression on develop branch. On 8.1.x it used to work well.

https://github.com/PrestaShop/PrestaShop/assets/16019289/79dc0ffb-e06d-49e5-a05b-be5cd1675355

<img width="1094" alt="Screenshot 2024-01-31 at 16 45 19" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/2835ec41-b296-437a-955e-b91066016519">

```
HTTP 500 Internal Server Error
An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "admin_products_v2_preview" as such route does not exist.").
```

### Expected behavior

I should be able to access my customer page in BO without exception.

### Steps to reproduce

1. Go to FO >  Add any product to you cart > Proceed to checkout
2. Sign into your customer (pub@prestashop.com)
3. In addresses step, delete all your addresses
4. Go to BO > Customer > Open customer John Doe
5. Exception :x:

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment]
@florine2623 Florine can you recheck if it doesn't happen all the time? It's not related to addresses. :-)

@PrestaShop/committers Guys can you check why the route doesn't exist? `admin_products_v2_preview`, I think that they hav e been kept no? If not, we need to change it to the proper one.

**Comment by Hlavtox** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/35234
