### ISSUE TITLE
Unable to rearrange product position between different pages of categories 

### ISSUE THREAD

**Issue by darkf3d3** [PrestaShop/PrestaShop#35243]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The feature that allow to rearrange product position into categories it's not fully working.
To rearrange product position you have to drag and drop them.
The problem is that this feature works only on the actual page, so if the category has more than 300 products (the maximum products that can be showed on a single page) you can't move a product to another page.

### Expected behavior

Rearrange product position feature should allow the user to choose any position, even if on a different page

### Steps to reproduce

Back office
Catalog >> Products
Filter products by a category
Then into the Position column click "rearrange"
If category have pagination, there's no way to move a product to another page

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

8.1

**Comment by paulnoelcholot** [comment]
Hello @darkf3d3,

Thank you for your suggestion. The Maintainer Team will take it into consideration for future developments. 

Please be aware that there is no guarantee that this feature will be developed anytime soon. If this is important to you, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you create it. 

If you or anyone else is willing to [contribute this feature](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/) to the PrestaShop Project, the teams will be happy to help by ensuring that it fits well within the project. Please let us know if that is the case!

Thank you
