### ISSUE TITLE
Show products in drop price slider and drop price page of disabled category

### ISSUE THREAD

**Issue by periota** [PrestaShop/PrestaShop#35252]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have disabled a category and assigned several products in that category, in all Prestashop it works correctly, it does not show those products but in both sections it does show them in a slider that shows the discounted products and in the discounted products section.
For some reason, when Prestashop orders this type of product, it does not filter those whose category is disabled. 
Thank you

### Steps to reproduce

1. disabled category
2. go to discount page

### PrestaShop version(s) where the bug happened

allways

### PHP version(s) where the bug happened

7.1

### Your company or customer's name goes here (if applicable).

golfriends.es

**Comment by Hlavtox** [comment]
@periota **Expected behavior - disabling category != disabling product.** The product can be in many categories and disabling them doesn't didsable the product itself. It will still display on all other places in front office.

**Comment by periota** [comment]
Currently, these products are only in 1 category, and in the rest of the sections it is done correctly only in the sections that are price-drop. I have managed to manually layer it in the view, but it is not the correct way.

In catalog/_partials/product.tpl

`{if !in_array(209,Product::getProductCategories($product->id|intval))}
{include file='catalog/_partials/miniature/product.tpl' product=$product position=$position}
{/if}`
* the 209 is disabled category

thanks

**Comment by florine2623** [comment]
As @Hlavtox said, it is the wanted behavior. So I'm closing your issue :)

**Comment by periota** [comment]
> @periota **Expected behavior - disabling category != disabling product.** The product can be in many categories and disabling them doesn't didsable the product itself. It will still display on all other places in front office.

But in the rest of the Prestashop sections it does have the correct behavior, of not showing products that are in a disabled category. It is clear that if they were in several categories and only one was visible, the product should be visible, but in my case it is only in one category and said category is disabled, but it is only in one section where it is shown and it should not be in drop-prices in the rest works correctly.

I don't understand, there must be a bug

**Comment by periota** [comment]
> As @Hlavtox said, it is the wanted behavior. So I'm closing your issue :)

Please not close, i think is a real bug
