### ISSUE TITLE
Unable to install Prestashop 8.1.3 in a subdirectory

### ISSUE THREAD

**Issue by nikitakothari06** [PrestaShop/PrestaShop#35258]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,

I tried installing Prestashop 8.1.1, 8.1.2 and 8.1.3 on my test server with PHP 8.1 and Mysql 5.7 The installation went successful. However when I visit the admin panel it shows blank page on "Home" screen and on "Setting" page as well.

On turning on debug it throws following error.

[1/2] ErrorException

ErrorException: Notice: SessionHandler::gc(): ps_files_cleanup_dir: opendir(/var/cpanel/php/sessions/ea-php81) failed: Permission denied (13) at [[path]]/prestashop811/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/StrictSessionHandler.php:116

[2/2] RuntimeException

RuntimeException: Failed to start the session: already started by PHP. at [[path]]/prestashop811/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php:148

What could be the issue ?

However when I install it in a root directory it works perfectly fine. Is the subdirectory installations not supported ?

Also, Are PHP 7.x not supported anymore ? Because I am not able to install 8.1.x version on PHP 7.2,7.3,7.4 as well. The script throws "500 Internal Server Error" on PS edition basic module install while manual installation.

### Expected behavior

smooth installation in subdirectory and PHP >= 7.2 if supported

### Steps to reproduce

1. Download the package.
2. Extract on the server.
3. Make the manual installation.
4. Login into the admin panel.
5. Visit "Home" and it will throw an error.
6. Visit "Setting" and it will throw an error.

### PrestaShop version(s) where the bug happened

8.1.1, 8.1.2, 8.1.3

### PHP version(s) where the bug happened

8.0

### If your bug is related to a module, specify its name and its version

PS edition basic module

**Comment by paulnoelcholot** [comment]
Hello @nikitakothari06,

Notified to Edition team, they will take care of it.

Thanks

**Comment by nikitakothari06** [comment]
How do I contact edition team ?
