### ISSUE TITLE
No images in sitemap

### ISSUE THREAD

**Issue by nachols889** [PrestaShop/PrestaShop#35260]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I am using the module "Google Sitemap" and it includes images in sitemap. Is there any way to exclude them? I checked for other modules that allow it like "Sitemaps Pro Multi idiomas y Multi tiendas" but they are paying. 

### Expected behavior

Add the option to exclude images. 

### Steps to reproduce

Go to Google Sitemap module. 
Settings
Exclude images

### PrestaShop version(s) where the bug happened

1.7.7.7

### If your bug is related to a module, specify its name and its version

Google Sitemap v4.4.0

### Your company or customer's name goes here (if applicable).

Decoracionbeltran.com

**Comment by paulnoelcholot** [comment]
Hello @nachols889,

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Thank you
