### ISSUE TITLE
Identified bug on transactional order_conf email on PrestaShop 8

### ISSUE THREAD

**Issue by yat-daria** [PrestaShop/PrestaShop#35269]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

As a PrestaShop Partner agency, we identified a bug specific to the transactional "order_conf" email. 

We tried to edit the content of the transactional email "order_conf" through the HTML in the translations, but afterward, the layout is completely broken. 

Here's a video that illustrate the bug > https://www.loom.com/share/1376ede58ea04e12ba08a35b2b076554?sid=701d8cdd-82f2-45f8-ae3f-0094d02e0ac3 
To reproduce the problem, you must edit the content of the transactional "order_conf" email via the translations.

- Screenshot before the edit : https://prnt.sc/Olpag0a8COwI

- Screenshot after the edit :  https://prnt.sc/cb-WfQSPYiTL

Thank you. I remain available for any questions. 

Best Regards

### Expected behavior

The expected behavior is that when we change the content of the "order_conf" email, the layout remains the same. 

### Steps to reproduce

1. Go to the Back Office
2. Click on "International"
3. Then click on "Translations"
4. Select "Emails translations" as a type of translation
5. Select "Body" as a type of content
6. Select a theme
7. Select a language 
8. Click on "Edit"
9. Click on "Core emails"
10. Click on "order_conf"
11. Click on "Edit HTML version"
12. Edit the content
13. Click on "Save"
14. Order something from the front to receive the order confirmation email

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

8.1.27

**Comment by florine2623** [comment]
You issue is a duplicate of https://github.com/PrestaShop/PrestaShop/issues/32843

So I'm closing it :)
