### ISSUE TITLE
webservice: "Error occurred while setting the product_option_values value" with multistore active and id_group_shop

### ISSUE THREAD

**Issue by Max84** [PrestaShop/PrestaShop#35267]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I update a product throw webservice, error "Error occurred while setting the product_option_values value" occurs and database is corrupted.

### Expected behavior

Product should be updated without error, and database mustn't be corrupted.

### Steps to reproduce

1. Enable multistore
2. With backoffice, create 2 stores in the same shop group
3. With backoffice, create a product with combinations
4. Enable webservice

Now, do a webservice request, in order to see added product:
=> http://localhost/api/products/your_id
Check XML output, no bug, it's OK.

Now check it with id_group_shop parameter:
=>  http://localhost/api/products/your_id?id_group_shop=1
Check XML, go onto combinations node, you'll see duplicate id. It might not be a problem, but it's strange.

Now, reproduce this issue:
1. use something like postman, in order to do a GET resquest with id_group_shop=1 parameter in url.
2. with your postman, just update this product, still with id_group_shop=1 parameter in url, so you'll only send previous data.

You will get a webservice error with this message "Error occurred while setting the product_option_values value"
AND check combination, you have loose combinations' id in database.

### PrestaShop version(s) where the bug happened

1.7.7.8, 1.7.8.6, 8.1.0

**Comment by florine2623** [comment]
Hello @Max84 ,

On Step 3, did you create the product only for the second shop ?

Waiting for your feedback.
Thanks

**Comment by Max84** [comment]
Hello @florine2623,

I'm sorry, I didn't explained this step. I tested several Prestashop version, and we have different behavior.
With Prestashop 1.7.x, you can create a product for all shop, that's what I did.
With Prestashop 8, you can only create a product for a specific shop, so I did it for the first shop because the webservice url used is the first shop url.

Feel free to ask me if needed.

**Comment by florine2623** [comment]
Ok, noted ^^
Could you send me the body of your PUT request ?

**Comment by Max84** [comment]
Not really, I do a GET request and I resend it as PUT body.
I just remove 2 fields, quantity and type.
It's because it's my own test data, but i can do a POST (in order to create), and then give you the PUT.
Will it be usefull for you ?

**Comment by florine2623** [comment]
I do not have the same behavior as yours here :

> Now check it with id_group_shop parameter:
> => http://localhost/api/products/your_id?id_group_shop=1
> Check XML, go onto combinations node, you'll see duplicate id. It might not be a problem, but it's strange.

My product has combinations and no duplicate ID
<img width="595" alt="Screenshot 2024-02-09 at 09 56 23" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/98986cae-69d6-479b-bb2e-5f13dd96e072">

Although I have another issue.
When I modify my product price, the whole product is not displayed anymore. It only exist in the webservice.

As you can see here :

https://github.com/PrestaShop/PrestaShop/assets/16019289/14ebf64b-5e8c-4f27-b55e-87d1bc86bbaa

The body of my PUT request is the following :

<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<product>
	<id><![CDATA[23]]></id>
	<price><![CDATA[12345.000000]]></price>
</product>
</prestashop>

Do you encounter the same problem ?

**Comment by Max84** [comment]
Hello @florine2623,

I tested different Prestashop version, i may did some mistake or confusion between 2 versions.
Is it useful to get these data from Prestashop 1.7 too? Maybe not, because it is unsupported now, am I right?

If yes, I'll do only a screencast for Prestashop 8.1.
Please, tell me.
Thanks.

**Comment by florine2623** [comment]
Yes, PS 1.7 will only have updates if it concerns security fixes.

Waiting for your feedback.

**Comment by paulnoelcholot** [comment]
Hello @Max84,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
