### ISSUE TITLE
Can't access link blocks from BO with wrong language on employee

### ISSUE THREAD

**Issue by Prestaworks** [PrestaShop/PrestaShop#35275]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When edititing the blocks in ps_linklist, it's not possible to access the blocks in multistore of the language of the employee is not matching the language of the shop.

### Expected behavior

It should always be possible to edit the blocks from the BO.

### Steps to reproduce

1. Set up a Prestashop installation with two multistores.
2. Make sure you have different languages in each store, one store has only French and the other only English.
3. Create a linklist block in each shop, entering information in only that shops specific language (no english in the french shop and vice versa.
4. Toggle between the shops, you will only see the block in one of the shops.
5. Change language on your employee account, you will now see the blocks from the other shop.

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

8.1.12

### If your bug is related to a module, specify its name and its version

ps_linklist 6.0.4

### Your company or customer's name goes here (if applicable).

Prestaworks AB

**Comment by florine2623** [comment]
Hello @Prestaworks ,

I reproduced the issue with PrestaShop version `8.1.x`, `develop` and module ps_linklist `6.0.4`, I'll add this to the backlog so it can be fixed.

https://github.com/PrestaShop/PrestaShop/assets/16019289/240c09b5-b161-4ede-82eb-0104412b3a7f

Thank you for the PR, it will be reviewed soon ^^
