### ISSUE TITLE
1-Click update module error report (v5.0.0autoupgrade.zip)

### ISSUE THREAD

**Issue by mauro-60** [PrestaShop/PrestaShop#35288]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Running the module everything proceeds correctly until the messages: 
Cleaning cache file
Running opcache_reset

at this point an error appears (shown at the bottom). The front office works but the back office can no longer be accessed. The login page remains blank. I tried restoring individual folders but none solved the problem or I didn't identify a guilty folder. Only the restore of all folders (excluding /images /img) allowed logging again into the backoffice.

**Last row in autoupgrade log.txt:**
[2023-06-27 11:34:18] Configuration successfully updated. <strong>This page will now be reloaded and the module will check if a new version is available.</strong>

**Report on going upgrade Rows:**
Directory /webservice already exists.
Copied /webservice/dispatcher.php.
Copied /webservice/index.php.
[SKIP] directory "/app/cache/" does not exist and cannot be emptied.
[CLEANING CACHE] File dev removed
[CLEANING CACHE] File dev1 removed
[CLEANING CACHE] File dev2 removed
[CLEANING CACHE] File pro_ removed
[INTERNAL] mydomain.com/public_html/modules/autoupgrade/classes/Tools14.php line 142 - rmdir(mydomain.com/public_html/var/cache/prod/): Directory not empty
[CLEANING CACHE] File prod removed
[CLEANING CACHE] File prod1 removed
[CLEANING CACHE] File prod2 removed
Cleaning file cache
Running opcache_reset
 
**Error:**
**[INTERNAL] mydomain.com/public_html/src/PrestaShopBundle/Form/Admin/Extension/ModifyAllShopsExtension.php line 49 - Class PrestaShopBundle\Form\Admin\Extension\ModifyAllShopsExtension contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Component\Form\FormTypeExtensionInterface::getExtendedType)**

### Expected behavior

Just enter in the backoffice to test the new release upgraded

### Steps to reproduce

Using 1-clickupdate module
Click Configure
Select minor release (target 1.7.8.11)
Run "Upgrade Now"
The module stops with the error reported. 
Front End is working , calling Backoffice url the browser page remains blank. Can not access
The only solution is restore 

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

1-click upgrade ( v5.0.0autoupgrade.zip)

**Comment by AureRita** [comment]
Hi @mauro-60 

Thank for your report,
This issue is too technical for me, ping @PrestaShop/tech-council / @Hlavtox , can someone please check the log to find this issue ? 

Thanks

**Comment by Quetzacoalt91** [comment]
Hi @mauro-60,

Can you please double check the steps to reproduce? I don't understand how you end with this error:

> [INTERNAL] mydomain.com/public_html/src/PrestaShopBundle/Form/Admin/Extension/ModifyAllShopsExtension.php line 49 - Class PrestaShopBundle\Form\Admin\Extension\ModifyAllShopsExtension contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Component\Form\FormTypeExtensionInterface::getExtendedType)

The main reason is the file you're talking about in present from PS 8.0. I'll try with a major upgrade but the accurate process to reproduce always helps.

**Comment by Quetzacoalt91** [comment]
Although I cannot explained how it happened, it looks like an upgrade to the v8 branch has been executed. If you still have your log file, can you check and/or share it?
It can be found in `<admin_folder>/autoupgrade/tmp/log.txt`, and you should find inside it details about the release that has been downloaded, for instance:

```
[2024-04-10 15:13:34] Starting upgrade...
[2024-04-10 15:13:34] Shop deactivated. Now downloading... (this can take a while)
[2024-04-10 15:13:34] Downloaded archive will come from https://github.com/PrestaShop/PrestaShop/releases/download/1.7.8.11/prestashop_1.7.8.11.zip
[2024-04-10 15:13:34] MD5 hash will be checked against d29d55f89a2c44bef3d5c51b70e3a771
[2024-04-10 15:13:34] Downloading from https://github.com/PrestaShop/PrestaShop/releases/download/1.7.8.11/prestashop_1.7.8.11.zip
[2024-04-10 15:13:34] File will be saved in /var/www/html/admin-dev/autoupgrade/download/prestashop.zip
[2024-04-10 15:13:34] Download directory has been emptied
[2024-04-10 15:14:14] Téléchargement terminé.
[2024-04-10 15:14:14] Download complete. Now extracting...
[2024-04-10 15:14:14] &quot;/latest&quot; directory has been emptied
```

Before sharing content, you may need to remove references to your actual back-office folder.

Related tickets:
* https://github.com/PrestaShop/PrestaShop/issues/34962
* https://github.com/PrestaShop/PrestaShop/issues/33892

**Comment by Quetzacoalt91** [comment]
I don't understand how this file appeared on the shop while upgrading to PS 1.7 as it was pushed for the first time in the branch 8.0.x.
![image](https://github.com/PrestaShop/PrestaShop/assets/6768917/276b4b48-0ccb-45ee-8abf-d6db1ebf5d00)

We did not manage to reproduce this error during the previous month and the thread seems to be inactive. I'm closing the issue but remain available in case you get this error later with more information to reproduce.
