### ISSUE TITLE
Catalog - Stocks  - multiple filters not working

### ISSUE THREAD

**Issue by LukVrCz** [PrestaShop/PrestaShop#35280]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In search in Catalog - Stocks when I add multiple filters, no products are shown. If I use only one keyword in search it is working.
![NotWorking](https://github.com/PrestaShop/PrestaShop/assets/159191949/e7de3fa7-c927-48cb-a7f4-2a55feddf6b2)
![Working](https://github.com/PrestaShop/PrestaShop/assets/159191949/e611969d-2144-4a56-a20d-d49e07c710ab)

### Expected behavior

In previous version when I add multiple filters it shows me relevant products. I need to add multiple keywords to find relevant products.

### Steps to reproduce

1. Go to Catalog - Stocks
2. Search with one keyword (searching is working)
3. Type in second keyword
4. No products found - error ❌

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

8.2

**Comment by AureRita** [comment]
Hi @LukVrCz ,

Thank you for your report, I reproduce the issue with PrestaShop version 8.1..x, as you can see : 

[recording(96).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/c4240165-3867-4ae0-a067-da6eccd9afc4)

I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you for your first clear issue ! It's great to see issue writted like that. 

Thanks

**Comment by kpodemski** [comment]
This issue has been fixed in PrestaShop 8.1.5.
