### ISSUE TITLE
Edit translation in Back Office displays compromised page, and then an error

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#35289]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When we try to edit translation in Back Office a compromised page is first displayed (that's the first problem) then even if we click on `I understand the risk` an error is displayed about a badly formed URL

[Dashboard • Prestashop develop.webm](https://github.com/PrestaShop/PrestaShop/assets/13801017/11c63e7c-7be3-4aed-91b5-78224baff2d4)

### Expected behavior

We should probably first fix the bug displayed after compromised page to understand the core of this bug, and then avoid the compromised page in between when we try to edit translations.

When everything is fixed I expect to see the translation UX after I click on modify.
Also maybe some UI tests are missing on this part since it as not detected by automatic tests.

### Steps to reproduce

1. In back office go to International > Translations
2. In the `Modify translations` card select a language and click on `Modify`
3. You should see a compromised page inviting you to either "Understand the risk" or "Get out of here"
4. Click on `I understand the risk`
5. You should now see an exception popping `Input value "form" contains a non-scalar value.`

Note: this was tested with Symfony layout And Legacy layout so it's probably not related (likely related to Symfony upgrades)

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

**Comment by matks** [comment]
Found it first 😛 https://github.com/PrestaShop/PrestaShop/issues/35175

**Comment by AureRita** [comment]
Hi @jolelievre 

as said @matks, your issue seems to be similar than the #35175 , as you agree with that ? 
If yes, I'll close your issue because it's a dupplicate of the other 

Waiting for your feedback

**Comment by jolelievre** [comment]
Yep it's a duplicate
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/35175
