### ISSUE TITLE
1.7.8.11 - ps_emailsubscription no newsletter_verif message after registration

### ISSUE THREAD

**Issue by lim3ra** [PrestaShop/PrestaShop#35293]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,

I'm using ps_emailsubscription version 2.8.1 Option "Send verification e-mail to subscribe to the newsletter" doesn't work.

The store does not send the message, does not generate an error in the logs and the message is visible as sent in Advanced > E-mail address.

645jawoh61716@gosarlar.com newsletter_verif Polish (Polish) [Shop] Verification email 2024-02-07 14:55:40

Any ideas on what to check/verify?

Other emails including "Send an email confirming your subscription to the newsletter?" and "Newsletter voucher" from the same module work correctly.

Under this path:
/modules/ps_emailsubscription/mails/en/

I have these files:
index.php
newsletter_conf.html
newsletter_conf.txt
newsletter_verif.html
newsletter_verif.txt
newsletter_voucher.html
newsletter_voucher.txt

I also tried creating /modules/ps_emailsubscription/mails/pl/ with the same content (copied from "en") - with no result.

### Expected behavior

A verification e-mail should be sent. 

### Steps to reproduce

1. Go to ps_emailsubscription and enable "Send verification e-mail to subscribe to the newsletter"
2. Use newsletter form to add new e-mail
3. See the message that the verification e-mail was sent
4. No e-mail in the mailbox
5. In the database subscribed e-mail is marked as not verified
6. In Advanced > E-mail address logs mail is marked as "sent"

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_emailsubscription v2.8.1

**Comment by paulnoelcholot** [comment]
Hello @lim3ra,

I tested your issues but I can't reproduce it on 8.1.3 as you see : 
![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/550c6f71-94e9-46f3-8b53-53ce167b5265)

Since version 1.7.8.11 is no longer maintained, if the bug is present on this version we are not able to correct it. I can only advise you to upgrade your shop to 8.1.3.

Thanks
