### ISSUE TITLE
Synch doesn't work

### ISSUE THREAD

**Issue by nolnul** [PrestaShop/PrestaShop#35291]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, I have a problem with PrestaShop modules. Synchronization is set up with the physical store's database via a cron job. Categories have been created to match those in the physical store's accounting system. However, products do not automatically appear in the product list. Do I need to manually add each product separately, and will stock levels and prices automatically update when they change in the physical store, or do I need to do additional work for that?
![0b42a2a6e6c62ff969633f7b96e7faf6](https://github.com/PrestaShop/PrestaShop/assets/93933991/b42e657e-139d-4612-a7f4-14944765f81c)

### Steps to reproduce

idk

### PrestaShop version(s) where the bug happened

8.1.3

**Comment by Hlavtox** [comment]
@nolnul Hi, you need to contact author of your sync module. 👍 Thank you for understanding
