### ISSUE TITLE
No Results on module=pagesnotfound

### ISSUE THREAD

**Issue by dav1403** [PrestaShop/PrestaShop#35301]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

![pagenotfound](https://github.com/PrestaShop/PrestaShop/assets/19288932/e3f7ebe4-d725-40d7-9bc3-dd64a1de5b92)
![404](https://github.com/PrestaShop/PrestaShop/assets/19288932/faa8c463-8a0a-4c53-bccc-910f12d3cde3)

### Steps to reproduce

Stats > pagesnotfound

### PrestaShop version(s) where the bug happened

8.1.1

**Comment by paulnoelcholot** [comment]
Hello @dav1403,

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. **You must follow the template and provide clear and concise steps to reproduce the bug**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
