### ISSUE TITLE
Cannot log in with Google instead it goes to the sign up page

### ISSUE THREAD

**Issue by burnsboyamazing** [PrestaShop/PrestaShop#35317]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Cannot log in with Google if you redirected to the sign up page when you choose the account.
[Screen recording 2024-02-10 12.29.18 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/154830140/bfe41123-7f79-4e89-b9a7-ea9689abd6c9)

### Expected behavior

If you log in with Google, it does not sign up and redirected to the PrestaShop page.

### Steps to reproduce

1. Log in with Google when you go to prestashop.com and then click on "Sign In" button.
2. It redirects to sign up page when you choose the account.

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_login 8.1

### Your company or customer's name goes here (if applicable).

PrestaShop

**Comment by Hlavtox** [comment]
@burnsboyamazing Hi, you need to contact prestashop company with those issues. Thank you for understanding

**Comment by burnsboyamazing** [comment]
Thank you, I will do that.

**Comment by burnsboyamazing** [comment]
<details><summary>Contacting @shakaran at prestashop.</summary>
<p>
Contacting at prestashop.
</p>
</details>
