### ISSUE TITLE
Cannot install any module via Marketplace (ps_mbo)

### ISSUE THREAD

**Issue by wapry90** [PrestaShop/PrestaShop#35314]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello Team,

i'm facing an issue after upgrade from 1.7 to 8.0.0.   The issue is related to Prestashop Marketplace and I cannot install any module.  I receive the following error: "admin_token must be a string".   Using Chrome Inspector, I can see that when I press install button, the following request goes in error (400 bad request) with the above message.
https://mbo-api.prestashop.com/api/shops/action.

Thanks for the support.

![error](https://github.com/PrestaShop/PrestaShop/assets/159557152/87b8f9b0-6760-49c0-a782-7b54d86fcccc)

### Expected behavior

Any module can be installed via Marketplace

### Steps to reproduce

1. Go to PrestaShop Marketplace
2. Choose a module
3. Press Install

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.0.30

### If your bug is related to a module, specify its name and its version

ps_mbo (4.9.0)

**Comment by florine2623** [comment]
Hello @wapry90 ,

Your issue has been transferred to the ps_mbo team.
I'm closing your issue as it is not a Core problem.

Thanks!

**Comment by intraordinaire** [comment]
@wapry90 

Indeed, you can open your issue here if needed => https://github.com/PrestaShopCorp/ps_mbo/issues

In the meantime, you can try to reset the module (uninstall/install) and maybe delete sources, and try with fresh zip downloaded from github.
Also, I suggest you to update to at least the last 8.0.x version of PS, and not to the 8.0.0, some fixes have been made about module management in minor versions.

**Comment by wapry90** [comment]
Yes, I already tried to uninstall/install the module and now I have the latest version (4.9.0).
I created the issue under ps_mbo.   

Thanks.
