### ISSUE TITLE
The field delay is required at least in .

### ISSUE THREAD

**Issue by hekep** [PrestaShop/PrestaShop#35311]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

"Transit time" field is hidden.  

Error Message: "The field delay is required at least in ."

![kuva](https://github.com/PrestaShop/PrestaShop/assets/1901788/986730c4-baae-4056-ba7f-675af379bead)

### Expected behavior

Make Delay field available, foolproofly.

### Steps to reproduce

shipping
carriers
add new carrier

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

PHP version: 7.4.33

**Comment by hekep** [comment]
The Prestashop is in multishop mode.

**Comment by florine2623** [comment]
Hello @hekep ,

I can't reproduce your issue :
<img width="1429" alt="Screenshot 2024-02-09 at 14 43 35" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/ba079918-1944-482f-989f-ce5880ceb01a">


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
