### ISSUE TITLE
Cannot update, grayed-out appears when a button is clicked but only the "Edit" and "Edit password" buttons appear

### ISSUE THREAD

**Issue by burnsboyamazing** [PrestaShop/PrestaShop#35318]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Cannot update or click the button, grayed-out buttons appear but only the "Edit" and "Edit password" buttons appeared.
[Screen recording 2024-02-10 12.36.41 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/154830140/cfbe9ece-6d2b-4a37-9f9b-c1358c5fd6ad)
![Screenshot 2024-02-10 12 41 00 PM](https://github.com/PrestaShop/PrestaShop/assets/154830140/7d5e3538-fc39-45ac-bcbb-f1494999cad7)
![Screenshot 2024-02-10 12 37 14 PM](https://github.com/PrestaShop/PrestaShop/assets/154830140/ba9f8d48-e174-4e92-ac46-9335c66a8a9e)

### Expected behavior

Can only click the placeholder text on "First name", "Last name", "Email", "Phone", and "Country" in text box.

### Steps to reproduce

1. Log in to the account.
2. In "Personal Info" it appears as grayed-out buttons when only click the "Edit" and "Edit password" buttons.

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_login 8.1

### Your company or customer's name goes here (if applicable).

PrestaShop

**Comment by Hlavtox** [comment]
@burnsboyamazing Hi, you need to contact prestashop company with those issues. Thank you for understanding

**Comment by burnsboyamazing** [comment]
<details><summary>Contacting @shakaran at prestashop, similar to https://github.com/prestashop/prestashop/issues/35317.</summary>
<p>
Contacting at prestashop.
</p>
</details>
