### ISSUE TITLE
Wrong data in Stats

### ISSUE THREAD

**Issue by Samiaegis** [PrestaShop/PrestaShop#35330]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello everybody, 

Since I set up Prestashop, I cannot get the right data (order numbers, products quantity sold ...).
I've installed 3 different modules but none are getting the right data, so I deactivated them. Maybe they were basing their data on the prestashop's native module data for the stats. 
Example : When I check My invoices for a period of time, I know i sold 6 of X products. When I go to stats, I only have one sold. 

Thank you for any help or insight. 
Samia

### Expected behavior

I just expect my data to be coherent with my orders. 

### Steps to reproduce

1 - Cannot access the module from the left panel (it disappeared). So go to modules > Stats dashboard > configure > Best-sellers.
2 - Choose a period of time
3 - Compare products sold to actual product solds in orders. 

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

stats_dashboard 2.0.4

### Your company or customer's name goes here (if applicable).

Aegis

**Comment by florine2623** [comment]
Hello @Samiaegis ,

The stats are well updated as you can see from here :

https://github.com/PrestaShop/PrestaShop/assets/16019289/3bd2a329-8f66-4604-a788-fe61bbec1446

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
