### ISSUE TITLE
'Version' param from registerJavascript and registerStylesheet break CCC 

### ISSUE THREAD

**Issue by hugofintecture** [PrestaShop/PrestaShop#35341]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When registering a JavaScript script using `registerJavascript` with a `version` parameter and enabling CCC (Combine, Compress, and Cache) for JavaScript, the generated 'bottom-*.js' file breaks. Instead of including the minified file content, the full path with the version is added to the bottom file. Consequently, this leads to JavaScript errors that disrupt the functionality of all shop JavaScript components.

![image](https://github.com/PrestaShop/PrestaShop/assets/89129201/decf9c32-7c42-4a01-93ba-6da86a316954)

![image](https://github.com/PrestaShop/PrestaShop/assets/89129201/f19349fc-2f91-498a-b12a-f67d609a0c88)

```
$this->context->controller->registerJavascript(
            'module-' . $this->name . '-shop-js',
            'modules/' . $this->name . '/views/js/shop.js',
            [
                'version' => $this->version,
            ]
        );
```

It also does the same with CCC for CSS and registerStylesheet.

While examining the code and the documentation, I also noticed something noteworthy:

- On [this doc page](https://devdocs.prestashop-project.org/8/themes/getting-started/asset-management/), the parameter `attributes` is mentioned.
- However, in [this line of code](https://github.com/PrestaShop/PrestaShop/blob/de990c7031a7833b1d7572f67105b16bae3c6723/classes/assets/CccReducer.php#L108), the parameter is referred to as `attribute`. I realized this because my code previously had `'attribute' => 'async'`, and yet the issue persisted (while the asset should have been ignored if I understood the code correctly). Hence, there may also be a discrepancy regarding this matter.

Many thanks to @NicoVmax who spent some time helping me and who found that the problem was with the 'version' parameter.

@NicoVmax tried this on PS 1.7 and could not reproduce the issue. So maybe it's a regression...

### Expected behavior

The 'bottom-*.js' file should include the minified content of the JavaScript script registered with registerJavascript, regardless of whether a version parameter is provided.

### Steps to reproduce

1. Enable CCC for JavaScript in the PrestaShop backend.
2. Register a JavaScript script in a module using registerJavascript with a version parameter.
3. Observe the generated 'bottom-*.js' file, noticing the inclusion of the full path with the version instead of the minified file content.
4. Attempt to execute JavaScript functionalities in the shop (product popups, ...), resulting in errors due to the broken script inclusion.

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

PHP 8.1

### If your bug is related to a module, specify its name and its version

Can easily be tested with our module Fintecture on PrestaShop 8.

### Your company or customer's name goes here (if applicable).

Fintecture

**Comment by paulnoelcholot** [comment]
Hello @hugofintecture,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by ComonSoft** [comment]
We confirm this issue, also on PS 8.1.4 with PHP 7.4, / 8.1. This is a big issue for SEO because it has an effect on performances.

**Comment by JS-starlord** [comment]
Same here, can't use CCC without modifying fintecture module because of this bug.

**Comment by ComonSoft** [comment]
We found the bug in StylesheetManager.php and JavascriptManager.php in file list construction. We will propose a fix asap.

**Comment by ComonSoft** [comment]
Pull request is in progress, proposal fix is [here](https://github.com/PrestaShop/PrestaShop/compare/develop...ComonSoft:PrestaShop:develop).
