### ISSUE TITLE
Module updates have very small image and no info about changes

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/PrestaShop#35348]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Modules -> Updates: detailed information about the module has very small image and no information about what changes with current update

### Expected behavior

1. Image should fill the container
2. There should be clear information about changes

### Steps to reproduce

https://github.com/PrestaShop/PrestaShop/assets/5007456/288dffef-9461-4f28-886d-4912c8b0fd2c

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

7.4, 8.0

### If your bug is related to a module, specify its name and its version

[ps_mbo](https://github.com/PrestaShopCorp/ps_mbo)

**Comment by florine2623** [comment]
Hello @SharakPL ,

I can't reproduce your issue with PS 8.1.4.
<img width="1440" alt="Screenshot 2024-02-14 at 14 08 04" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/b4696585-c975-4ff6-ae94-33fb40918265">

I do not have the "more info" link.

Are you on PS Open source or the Edition version ?

Waiting for your feedback ^^
Thanks!

**Comment by SharakPL** [comment]
Right, PS 8.1 doesn't have `Read more`. It's coming from https://github.com/PrestaShopCorp/ps_mbo module (if it's installed) so I better take this issue there.

Thanks @florine2623
