### ISSUE TITLE
PS 8.0.5 form don't send mail but customer support yes

### ISSUE THREAD

**Issue by GpToRAK** [PrestaShop/PrestaShop#35347]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello all.
I try to setup contact form to send email to admin contact.
I use SMTP setup, look like it's working fine when sending test email but nothing sent
in customer support tab I can see submitted form and I can reply, this way email are sent to customers and they can reply and so on.

Using front-end form on website everything look ok, form are submitted and copy appears on customers support tab, but no email are sent......

I didn't find any solutions about that please help me :-)

WKR

### Expected behavior

when submitting contact form an email has to be sent to the contact set in shop-->contact

### Steps to reproduce

set a simple form on a CMS page
set contact in shop->contact
try to submit form

### PrestaShop version(s) where the bug happened

8.0.5

### PHP version(s) where the bug happened

8.1.20

### If your bug is related to a module, specify its name and its version

CONTACT FORM

**Comment by florine2623** [comment]
Hello @GpToRAK ,

You need to configure the contact form module and enable the option you need : 
<img width="1224" alt="Screenshot 2024-02-14 at 09 45 35" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/7f020e59-1ceb-4e3c-8c1f-c714e1f78a82">

Thanks!

**Comment by GpToRAK** [comment]
I aready did that since long, still the same no form are sent ;-)
