### ISSUE TITLE
Hardcoded path in config: The "/var/www/html/admin-dev/themes/new-theme" directory does not exist

### ISSUE THREAD

**Issue by Quetzacoalt91** [PrestaShop/PrestaShop#35354]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello there,

Modifying the admin folder on the nightly build makes the BO fail. This seems to be caused by a hardcoded path in the config files with `admin-dev` I found in this [commit](https://github.com/PrestaShop/PrestaShop/commit/1b70d5a7637fa11fa12a03dbf5b18a625c1353ea#diff-58ea7cc56899a1bcf3bdb6fc0d9cee247056d8e8ffc845a8ee8648f24ed7c3e8R89).

![image](https://github.com/PrestaShop/PrestaShop/assets/6768917/1f6590ac-c623-4f0b-ba0a-65cb1b8107e7)

### Expected behavior

I expect the Back-office to work even if I rename my `admin-dev` folder.

### Steps to reproduce

1. Install the nightly with a folder `admin-dev` present (if you rename it prior installation, it will fail)
2. Access your back office. It should load
3. Rename `admin-dev` as anything you want
4. Access your back ffice. It should load

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.2

**Comment by florine2623** [comment]
Hello @Quetzacoalt91 ,

I have a similar issue to yours during installation : 

<img width="690" alt="Screenshot 2024-02-14 at 14 36 42" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/3650191d-b24b-42e4-9d2c-26adebaf208a">

**Comment by Quetzacoalt91** [comment]
Thanks! <3
