### ISSUE TITLE
PS 8.0.5 form don't send mail but customer support yes 

### ISSUE THREAD

**Issue by GpToRAK** [PrestaShop/PrestaShop#35353]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello all.
I try to setup contact form to send email to admin contact.
I use SMTP setup, look like it's working fine when sending test email but nothing sent
in customer support tab I can see submitted form and I can reply, this way email are sent to customers and they can reply and so on.

Using front-end form on website everything look ok, form are submitted and copy appears on customers support tab, but no email are sent......

I already set the Contact Form to send customers messages by email
![Capture d’écran 2024-02-14 à 13 34 33](https://github.com/PrestaShop/PrestaShop/assets/160004622/99a2381a-33e7-41ec-9ef8-e5abff67216c)

I didn't find any solutions about that please help me :-)

WKR

### Expected behavior

when submitting contact form an email has to be sent to the contact set in shop-->contact

### Steps to reproduce

set a simple form on a CMS page
set contact in shop->contact
try to submit form

### PrestaShop version(s) where the bug happened

8.0.5

### PHP version(s) where the bug happened

8.1.20

### If your bug is related to a module, specify its name and its version

CONTACT FORM

**Comment by florine2623** [comment]
Hello @GpToRAK ,

I can't reproduce your issue.

https://github.com/PrestaShop/PrestaShop/assets/16019289/a24385ab-dd45-43b7-a543-baa3507919d9

You can choose to who you're sending the email in Advanced Parameters > Emails :
<img width="1214" alt="Screenshot 2024-02-14 at 14 23 38" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/be5e2930-cc41-439d-b479-1d6cefb582c1">

Please contact the support team if this is not helpful.

**Comment by GpToRAK** [comment]
Thank you Florine

I did exactly the same as you said :-)

what is strange is that using customer service tab, while replying to message, email are sent right, so it's not a problem of SMTP server, not a problem of TCP ports on instance, not a problem of mail server...

I can't understand why :-(

**Comment by GpToRAK** [comment]
Hello

just to let you know that I found the solutions :

SMTP username in Advanced Papameters->E-mail
￼

must be the same as Shop Parameters—>Contact—>Stores
￼

WKR

Patrice

**Comment by pollat** [comment]
> Hello [@GpToRAK](https://github.com/GpToRAK) ,
> 
> I can't reproduce your issue.
> 
>  Screen.Recording.2024-02-14.at.14.21.38.mov 
> You can choose to who you're sending the email in Advanced Parameters > Emails : <img alt="Screenshot 2024-02-14 at 14 23 38" width="1214" src="https://private-user-images.githubusercontent.com/16019289/304746987-be5e2930-cc41-439d-b479-1d6cefb582c1.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzUxMjMyMTQsIm5iZiI6MTc3NTEyMjkxNCwicGF0aCI6Ii8xNjAxOTI4OS8zMDQ3NDY5ODctYmU1ZTI5MzAtY2M0MS00MzlkLWI0NzktMWQ2Y2VmYjU4MmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNDAyVDA5NDE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiZjNlOTU0OWI1Y2YxYTBjNDNiMDI2NTBkM2ViM2FiMDU1N2ZiNzI4Mjc3NTU3MTM5N2IzN2VhZDVmYjYxZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3EY5-ihGtzxDOyQoeidPP2jaHIyc2xGV1XdQIsntu6U">
> 
> Please contact the support team if this is not helpful.


You can reproduce this issue sending mail from front-end contact form by logged user.

I have same problem, in prestashop 1.7.8.8 if a logged user use prestashop contact form on the front-end, no mail are recived by admin, do you solve this issue? This is a big bug because admin lost messages sended by clients.

P.s. SMTP and contact form module are right configured and if not logged user send mail by contact form, the mail arrive to admin.
