### ISSUE TITLE
`available_quantity` coming from `Cart::getProducts()` is 0 for packs

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#35366]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you create a product pack and set it's stock type to `Decrement products in pack only.` (`PackStockType::STOCK_TYPE_PRODUCTS_ONLY`), it doesn't work in cart.

### Expected behavior

It should provide a value of stock quantity of this pack.
The problem is that it uses available_quantity from the raw query, not a calculated value for the pack.

### Steps to reproduce

0. Open `themes\classic\templates\checkout\_partials\cart-detailed-product-line.tpl` and add `Stock: {$product.quantity_available}` somewhere you can see it.
1. Create pack of two standard products, 1 piece of each.
2. Set stock quantity of these two products to 100 each.
3. Go back to the pack, set quantity of the pack to 1, so you can add it to cart. (...another bug), set `Pack quantities` to `Decrement products in pack only`.
4. Go to FO, add this pack to cart, go to checkout and see that the stock is 1, but it should be 100.

### PrestaShop version(s) where the bug happened

1.7.6 - develop

**Comment by Codencode** [comment]
The solution to this problem is similar to the issue https://github.com/PrestaShop/PrestaShop/issues/35367, I try to create a PR so we see if it can work.

**Comment by Hlavtox** [comment]
@Codencode For now, I fixed it for the client by adding this into `foreach ($result as &$row) {` in `Cart::getProducts`

```
// Fix pack stock
if (Pack::isPack((int) $row['id_product'])) {
  $row['quantity_available'] = Pack::getQuantity((int) $row['id_product'], (int) $row['id_product_attribute'], true);
}
```

**Comment by Codencode** [comment]
> @Codencode For now, I fixed it for the client by adding this into `foreach ($result as &$row) {` in `Cart::getProducts`
> 
> ```
> // Fix pack stock
> if (Pack::isPack((int) $row['id_product'])) {
>   $row['quantity_available'] = Pack::getQuantity((int) $row['id_product'], (int) $row['id_product_attribute'], true);
> }
> ```
Ok, that's what I proposed in the PR.
I closed the previous PR (https://github.com/PrestaShop/PrestaShop/pull/35376) and created the new one (https://github.com/PrestaShop/PrestaShop/pull/35379) because I had created the previous one mistakenly starting from the "develop" branch

**Comment by florine2623** [comment]
Hello @Hlavtox ,

I have reproduced your scenario.
<img width="1157" alt="Screenshot 2024-02-22 at 14 43 53" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/4d900342-97cf-47d9-8043-3fad569b28ff">

But to me that's the wanted behavior.

3. Go back to the pack, `set quantity of the pack to 1`, so you can add it to cart. (...another bug), set Pack quantities to Decrement products in pack only.
4. Go to FO, add this pack to cart, go to checkout and `see that the stock is 1,` but it should be 100.
-> this is normal behavior.

**Comment by Hlavtox** [comment]
@florine2623 No, it's bug, trust me. :-) It should be the same stock that is on the product page. The `available_quantity` is the amount in stock.

We already have a PR to fix it, no need to reproduce anymore.

**Comment by Hlavtox** [comment]
Will be fixed by https://github.com/PrestaShop/PrestaShop/pull/35372
