### ISSUE TITLE
Merchandise returns pdf file - a deprecation alert is displayed on the return form

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#35362]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When a customer request a return, when I change the status of the return, the return form is available.
When I click on it, I have the return form with a warning on it.

<img width="1008" alt="Screenshot 2024-02-14 at 17 32 24" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/5f267f05-dd5d-4c95-aa62-df26e1f6807a">

`Deprecated: Using php-function "sprintf" as a modifier is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier. in /develop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_modifier.php on line 114`

It is only displayed one time. When I download this file another time, the warning is not displayed anymore.

### Expected behavior

Should not display the deprecation warning

### Steps to reproduce

1. Go to BO > Enable merchandise return
2. Log into your customer account > Make an order
3. Go back to BO > Change status of latest order made to Delivered
4. Go to your customer account > Order history and details > Details > Scroll down to Product section
5. Select the product you want to return > Request a return
6. Go to BO > Customer Service > Merchandise return > Click on the latest merchandise return
7. Change status to Waiting for package
8. Click on Print out button
9. See Deprecation displayed in PDF :x:

### PrestaShop version(s) where the bug happened

8.1.x, 9.0.x

### PHP version(s) where the bug happened

8.1

**Comment by AureRita** [comment]
Hi @florine2623 ,

Thank you for your report, I reproduce the issue with PrestaShop version develop, as you can see : 

![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/87e2d338-fdd1-4911-a6aa-7c7c31e445ad)

I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. 

Thanks
