### ISSUE TITLE
A pack set to `Decrement products in pack only.` cannot be added to cart

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#35367]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you create a product pack and set it's stock type to `Decrement products in pack only.` (`PackStockType::STOCK_TYPE_PRODUCTS_ONLY`) and the quantity of the pack is zero, **it cannot be added to cart**.

### Expected behavior

You MUST be able to add this product to cart even if the quantity is zero.
It worked properly on 1.7.6.

### Steps to reproduce

1. Create pack of two standard products, 1 piece of each.
2. Set stock quantity of these two products to 100 each.
3. Go back to the pack, set quantity of the pack to 0, set `Pack quantities` to `Decrement products in pack only`, disable ordering when not in stock.
4. Go to FO and try to add it to cart.
5. Can't be added to cart and no error message is shown. 🔴 
6. Product page shows quantity 0 or nothing, it should show the quantity. 🔴 

### PrestaShop version(s) where the bug happened

broken on 8.1.3, works properly on 1.7.6

**Comment by Codencode** [comment]
The problem occurs because the following code has been replaced in the CartController::shouldAvailabilityErrorBeRaised() method:
```
PS 1.7.6.9
// product quantity is the available quantity after decreasing products in cart
         $productQuantity = Product::getQuantity(
             $this->id_product,
             $this->id_product_attribute,
             null,
             $this->context->cart,
             $this->customization_id
         );
```
with:
```
PS 8.1.3
         $availableProductQuantity = StockAvailable::getQuantityAvailableByProduct(
             $this->id_product,
             $this->id_product_attribute
         );
```
The StockAvailable::getQuantityAvailableByProduc() method does not take the package into account and consequently the item is not available.

Re-entering the code from version 1.7.6.9 works, but then going to the cart the system blocks the process as there is a problem here too (already present in 1.7.6.9).
This second problem is due to the Cart::checkQuantities() method where there is the following code:
```
             if (
                 !$product['active'] ||
                 !$product['available_for_order'] ||
                 (!$product['allow_oosp'] && $product['stock_quantity'] < $product['cart_quantity'])
             ) {
                 return $returnProductOnFailure ? $product : false;
             }
```
In which it should be checked if the product is not a "Package", then it should be changed to:
```
             if (
                 !$product['active'] ||
                 !$product['available_for_order'] ||
                 (!$product['allow_oosp'] && $product['stock_quantity'] < $product['cart_quantity'] &&
                 !Pack::isPack((int) $product['id_product'])
                 )
             ) {
                 return $returnProductOnFailure ? $product : false;
             }
```
What do you think?

I might create a PR so the code is clearer and can be tested.

**Comment by Codencode** [comment]
The problem occurs because the following code has been replaced in the **CartController::shouldAvailabilityErrorBeRaised()** method:
```
PS 1.7.6.9
         // product quantity is the available quantity after decreasing products in cart
         $productQuantity = Product::getQuantity(
             $this->id_product,
             $this->id_product_attribute,
             null,
             $this->context->cart,
             $this->customization_id
         );
```
with:
```
PS 8.1.3
         // Check if this product is out-of-stock
         $availableProductQuantity = StockAvailable::getQuantityAvailableByProduct(
             $this->id_product,
             $this->id_product_attribute
         );
```
The **StockAvailable::getQuantityAvailableByProduc()** method does not take the package into account and consequently the item is not available.

Therefore availability should be checked using **Product::getQuantity()**, without however passing the cart as a parameter otherwise another problem occurs, so the following code:
```
        // Check if this product is out-of-stock
         $availableProductQuantity = StockAvailable::getQuantityAvailableByProduct(
             $this->id_product,
             $this->id_product_attribute
         );
```
should be replaced with:
```
         // product quantity is the available quantity after decreasing products in cart
         $productQuantity = Product::getQuantity(
             $this->id_product,
             $this->id_product_attribute,
             null,
             null,
             $this->customization_id
         );
```

Furthermore, going to the cart the system blocks the process as there is a problem here too (already present in 1.7.6.9).
This second problem is due to the **Cart::checkQuantities()** method where there is the following code:
```
             if (
                 !$product['active'] ||
                 !$product['available_for_order'] ||
                 (!$product['allow_oosp'] && $product['stock_quantity'] < $product['cart_quantity'])
             ) {
                 return $returnProductOnFailure ? $product : false;
             }
```
In which it should be checked if the product is not a "Package", then it should be changed to:
```
             if (
                 !$product['active'] ||
                 !$product['available_for_order'] ||
                 (!$product['allow_oosp'] && $product['stock_quantity'] < $product['cart_quantity'] &&
                 ! Pack::isPack((int) $product['id_product'])
                 )
             ) {
                 return $returnProductOnFailure ? $product : false;
             }
```
What do you think?

I might create a PR so the code is clearer and can be tested.

**Comment by Hlavtox** [comment]
@Codencode Nice find brother. YES, if you can open a PR with suggested solution, I will check it out immediately. It's a major issue for some clients. :(

**Comment by Codencode** [comment]
> @Codencode Nice find brother. YES, if you can open a PR with suggested solution, I will check it out immediately. It's a major issue for some clients. :(

Ok, I'll create the PR.
I just hope the code doesn't create any other problems, it should be tested in various scenarios.

**Comment by Codencode** [comment]
@Hlavtox PR created.

**Comment by Hlavtox** [comment]
@MatShir @kpodemski I am adding critical label because adding things to cart is a crucial functionality of an ecommerce system. Packs are used by most of my clients.

**Comment by MatShir** [comment]
It is a big `major` for sure ! Critical implies a super sayen quick urgent patch release in tha minute. cf https://www.prestashop-project.org/get-involved/report-issues/how-issues-are-sorted/

**Comment by Hlavtox** [comment]
@nesrineabdmouleh @boubkerbribri Guys, do you think you could cover this with tests after we fix it?

Configure a pack > Go to FO > Order it. For all 3 types of pack settings.

**Comment by nesrineabdmouleh** [comment]
hello @Hlavtox, 

We have this [test](https://github.com/PrestaShop/PrestaShop/blob/develop/tests/UI/campaigns/functional/BO/13_shopParameters/03_productSettings/03_productsStock/02_defaultPackStockManagement.ts) to check all options of default pack stock management, 
@florine2623 can you please add some steps to test the option _Decrement pack only_ when pack quantity = 0 ?
Thank you!

**Comment by Hlavtox** [comment]
@MatShir @nesrineabdmouleh @Progi1984 @Codencode I have tested everything now and made a table with scenarios. I think if you update the tests, you will get the same results.

- Quantity displayed on product page works fine in all cases.
- What doesn't work is case number 3 - the logic that checks if the product can be added to cart and if it can stay in the cart.

| | Poster | Mug | Pack | Final quantity | Should I be able to add to cart? | Why I can or can't?
| --- | --- | --- | --- | --- | --- | ---
| Pack only | 0 | 7 | 10 | 10 | Yes | Pack is in stock and that is what matters.
| Pack only | 3 | 7 | 0 | 0 | No | Pack is not in stock, even if product are.
| Product of pack only | 3 | 7 | 0 | 3 | Yes - NOT WORKING IN 8.1, CAN'T ADD IT TO CART | Pack quantity is ignored, it depends on products.
| Both | 3 | 7 | 2 | 2 | Yes | Depends on both, whatever is lower, here on the pack.
| Both | 3 | 7 | 200 | 3 | Yes | Depends on both, whatever is lower, here on the products.
| Both | 0 | 7 | 2 | 0 | No | Depends on both, whatever is lower, here one of the products is not in stock, even if the pack is.
| Both | 3 | 7 | 0 | 0 | No | Depends on both, whatever is lower, here the pack is not in stock, even if the products are.
