### ISSUE TITLE
Issue with new module for prestashop cloud sync

### ISSUE THREAD

**Issue by cWebCo** [PrestaShop/PrestaShop#35371]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

https://github.com/PrestaShopCorp/builtforjsexample

I used your module for cloud sync its working fine. But when i change module name to **builtforjsexampletest** its stop working. Change module name everywhere where ever is defined

### Expected behavior

Data must by share
![Module Manager • gomer](https://github.com/PrestaShop/PrestaShop/assets/26286624/47708438-eda6-472b-b725-7a7a6008f793)

This is working with when we not change your module name builtforjsexample

### Steps to reproduce

**Step 1.** Please download attached module and upload this module in prestashop.
[builtforjsexampletest.zip](https://github.com/PrestaShop/PrestaShop/files/14296785/builtforjsexampletest.zip)
**Step 2.** composer install 
![Screenshot from 2024-02-15 17-56-36](https://github.com/PrestaShop/PrestaShop/assets/26286624/96762b81-d3a5-4a66-8bbc-31c7fdf3e0ed)
**Step 3.** Then install module and goto configuration page
**Step 4.** Sync shop
**Step 5.** then client share data sync its generating issue

### PrestaShop version(s) where the bug happened

On every version. Module compatibility start from 1.7 version

### If your bug is related to a module, specify its name and its version

builtforjsexampletest

**Comment by Hlavtox** [comment]
Hi @cWebCo, you need to contact someone from @PrestashopCorp, we can't help you with those issues. Thank you for understanding.
