### ISSUE TITLE
unit_price_ratio not updated using the webservice

### ISSUE THREAD

**Issue by Daaaaad** [PrestaShop/PrestaShop#35370]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello 👋

I've searched and searched all this github repo but unfortunately I can't find a solution to my problem.

There's been a lot of discussion on this subject, but the only resolution I've found relates to PS 8.0 (I'm using 1.7.8.7).

### Expected behavior

We are trying to update the unit_price_ratio using the api.

### Steps to reproduce

1. I'm using postman to call the webservice.
2. I just get a product XML with {{webservice_url}}/api/products/{{product_id}}
3. unit_price_ratio is <unit_price_ratio><![CDATA[0.000000]]></unit_price_ratio>
4. I change the value to 5.000000
5. I also change the name of the product to be sure that update is ok
6. I use this edited XML to do a PUT request on {{webservice_url}}/api/products/{{product_id}}
7. Name is updated but unit_price_ratio is still 0.000000
8. Response XML of the update do contain <unit_price_ratio><![CDATA[5.000000]]></unit_price_ratio> but it's not saved in database :( 

As I told I found a lot of issues about this problem but no resolution for PS 1.7 : 
https://github.com/PrestaShop/PrestaShop/issues/9922
https://github.com/PrestaShop/PrestaShop/issues/20071

Could you help?

### PrestaShop version(s) where the bug happened

1.7.8

### PHP version(s) where the bug happened

7.4

**Comment by Hlavtox** [comment]
Try to investigate what is going on in this area of code.
https://github.com/PrestaShop/PrestaShop/blob/f88272aeb41f883fa146dca7a8a1c90ff29ad614/classes/Product.php#L7377

**Comment by AureRita** [comment]
Hi @Daaaaad 

Thank you for your report, Currently this issue seems to be corrected on the 8.0.x, as you can see : 

![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/e024040d-551f-41af-8c7f-e22bdc8b3fbe)

Unfortunatelly, because the issue on 1.7.8 is only checked for security issue, others' checked on, at least, 8.0.x we have to close your issue. 

I recommand you to upgrade your shop on a new version of prestashop
