### ISSUE TITLE
It Pop Up's product images and can't close. Also Pop Up's a blank window on Pay Options.

### ISSUE THREAD

**Issue by santos0289** [PrestaShop/PrestaShop#35385]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Case 1: When we click one aleatory product, it pop ups the product images on one windows an can't close so we have to refresh the page for quit that images. 
Case 2: when we are going to pay, appears a blank windows (it seems like a modal windows) but this we can close by clicking the close button.
We have to say, that when we refresh (in case 1), we reproduce the step and don't occurs. Only if we delete the browsing data or prestashop caché.
It is not, theme error, because with the classic theme of prestashop also ocurrs this 2 cases.
I attack the videos of the procedure:

Case1: https://github.com/PrestaShop/PrestaShop/assets/93709131/7364d949-5e17-4112-a7ef-8359e5ab90ef

Case2:

https://github.com/PrestaShop/PrestaShop/assets/93709131/c4ef8382-bd94-4d94-ab14-160915c0c584

### Expected behavior

Case 1:When we click one product it would not show the images poppup
Case 2:When we go to payment options, it would not show the black window.

### Steps to reproduce

Case1:
1. Click one product of  https://www.smsportnutrition.com
2. It pop ups a windows with the product images
3. Try to close clicking the X button 

Case2:
1. Add one product to shopping cart
2. Proceed to checkout 
3. In the payment options will appear the blank windows

This occurs only ones, so if you do the same procedure it not occurs until you delete the browser data...

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

8.0.30

**Comment by Hlavtox** [comment]
@santos0289 This is an issue with your third party theme, contact the author. 👍

**Comment by santos0289** [comment]
Hi and thanks for the answer @Hlavtox . I contact them and say that the theme is ok, so we check with the classic theme and same error

**Comment by Hlavtox** [comment]
@santos0289 Ok then it's some module that is doing the popup, you need to find it. ;-)

**Comment by santos0289** [comment]
> @santos0289 Ok then it's some module that is doing the popup, you need to find it. ;-)

Thank you!I have been checking all and deffinitively was one module that appears an almos all hooks...

Best regards!

**Comment by AureRita** [comment]
Thank you for your report @santos0289 

and thank you for the answer @Hlavtox 

We're delighted that you were able to find a solution to your problem.
