### ISSUE TITLE
FO discount section shows all vouchers without code that even if not highlighted

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#35408]
### Describe the bug and add attachments

Customer discount section shows all vouchers without code that even if not highlighted. The problem is caused by this PR - https://github.com/PrestaShop/PrestaShop/pull/22518, which added `cr.highlight = 1 OR cr.code = ""`.

Also, it hides the posibility to set voucher highlighted when it has no code.

The result is following.

### 1.7.6 - no vouchers
![Snímek obrazovky 2023-11-22 165221](https://github.com/PrestaShop/PrestaShop/assets/6097524/d248ecf6-c59a-4fcf-8c63-e9835245c7ef)

### 8.1.3 - all of the business logic is exposed
![sn__mek_obrazovky_2023-10-31_143703](https://github.com/PrestaShop/PrestaShop/assets/6097524/0c0302b7-8350-4641-9298-9680936360e2)

| Voucher | My account zone | Cart page | Cart page logged out | Backoffice customer detail
| --- | --- | --- | --- | ---
|   | This page should show only vouchers specific to this single customer. | This case should show only rules highlighted and either for current customer or for everyone. | This case should show only rules highlighted and for everyone. | This page should show only vouchers specific to this single customer.
| Code, highlight, for everyone | 🔴 YES - not a disaster, but wrong, it's not his specific voucher | 🟢YES | 🟢YES |  🔴YES - wrong, it's not his specific voucher
| Code, highlight, specific customer | 🟢 YES | 🟢YES | 🟢NO | 🟢YES
| Code, no highlight, for everyone | 🟢NO | 🟢NO | 🟢NO |  🟢NO
| Code, no highlight, specific customer | 🟢YES | 🟢NO | 🟢NO |  🟢YES
| No code, highlight, for everyone | 🔴YES - not a disaster, but wrong, it's not his specific voucher | 🟢YES | 🟢YES |  🔴YES - wrong, it's not his specific voucher
| No code, highlight, specific customer | 🟢YES | 🟢YES | 🟢NO |  🟢YES
| No code, no highlight, for everyone | 🔴YES - VERY WRONG, nobody should see this logic | 🟢NO | 🟢NO |  🔴YES - wrong, it's not his specific voucher
| No code, no highlight, specific customer | 🟢YES | 🟢NO | 🟢NO |  🟢YES

### Expected behavior

The change must be reverted and in the customer zone, only vouchers **FOR THAT SPECIFIC CUSTOMER** or **HIGHLIGHTED** should be displayed.

The only thing that the PR did was to prevent people configuring if they want people to see this voucher or not.

| Voucher | My account zone | Cart page | Cart page logged out | Backoffice customer detail
| --- | --- | --- | --- | ---
|   | This page should show only vouchers specific to this single customer. | This case should show only rules highlighted and either for current customer or for everyone. | This case should show only rules highlighted and for everyone. | This page should show only vouchers specific to this single customer.
| Code, highlight, for everyone | 🟢NO | 🟢YES | 🟢YES |  🟢NO
| Code, highlight, specific customer | 🟢YES | 🟢YES | 🟢NO |  🟢YES
| Code, no highlight, for everyone | 🟢NO | 🟢NO | 🟢NO |  🟢NO
| Code, no highlight, specific customer | 🟢YES | 🟢NO | 🟢NO |  🟢YES
| No code, highlight, for everyone | 🟢NO | 🟢YES | 🟢YES |  🟢NO
| No code, highlight, specific customer | 🟢YES | 🟢YES | 🟢NO |  🟢YES
| No code, no highlight, for everyone | 🟢NO | 🟢NO | 🟢NO |  🟢NO
| No code, no highlight, specific customer | 🟢YES | 🟢NO | 🟢NO |  🟢YES

### Steps to reproduce

1. Create cart rule with no code, valid for all customers, with infinte quantity.
2. Login as a customer in FO, see that you can see the voucher even if you did not highlight it.

### PrestaShop version(s) where the bug happened

8.1.3

**Comment by Codencode** [comment]
The `CartRule::getCustomerCartRules()` method accepts the `$highlight_only` parameter which, if set to `true`, allows you to retrieve only the visible coupons, however those associated with the customer himself but with `Highlight` false would also be excluded.

**Comment by paulnoelcholot** [comment]
FYI @PrestaShop/product-council 

What do you think of this issue, bug or feature?

**Comment by Hlavtox** [comment]
Will be fixed by https://github.com/PrestaShop/PrestaShop/pull/35464

**Comment by MatShir** [comment]
When the bug is fixed, the specs will need to be updated so we don't have the issue again. I did decide to display all on the account page, but I agree with @Hlavtox's arguments that we don't need to display all the vouchers on the account client page since they will already be highlighted in the cart.
Thanks for the input @Hlavtox

**Comment by MatShir** [comment]
I flag it as `Minor`, it doesn't put the merchant business at risk. @Hlavtox ;)

**Comment by Hlavtox** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/35464
