### ISSUE TITLE
Create a new product, it does not select the correct VAT group.

### ISSUE THREAD

**Issue by Billeskov** [PrestaShop/PrestaShop#35403]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

![Skærmbillede 2024-01-22 200724](https://github.com/PrestaShop/PrestaShop/assets/160105785/71967383-ffe8-44ca-938f-2a44a2a00e06)
I want it to chose this one EVERY TIME and not the "No Tax".

### Steps to reproduce

Create a new product

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

7.4.33

**Comment by paulnoelcholot** [comment]
Hello @Billeskov,

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Thank you

(or you can click on "Administrer momsregler" below the input Detailpris)

**Comment by MatShir** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/issues/35216
