### ISSUE TITLE
Import prodcut csv

### ISSUE THREAD

**Issue by tajLink** [PrestaShop/PrestaShop#35416]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have an issue with importing products via CSV on the PrestaShop platform version 1.7.0.2. The PHP version is 7.0.33. It keeps showing the same error. I'm attaching screenshots for reference. To make it easier, I've included only the product name and ID in the CSV file.
![import](https://github.com/PrestaShop/PrestaShop/assets/160510064/014b88d6-1621-4143-9af8-1e7639f4ac35)
![import-1](https://github.com/PrestaShop/PrestaShop/assets/160510064/440d43c2-2851-4b72-818e-4570eea18b14)
![import-2](https://github.com/PrestaShop/PrestaShop/assets/160510064/54814627-a7d7-4602-b907-0f4ea7b80597)
![import-3](https://github.com/PrestaShop/PrestaShop/assets/160510064/176c4710-850a-48cf-a9d4-0820a93d2bcd)

### Steps to reproduce

1.Import CSV

### PrestaShop version(s) where the bug happened

1.7.0.2.

### PHP version(s) where the bug happened

7.0.33

### Your company or customer's name goes here (if applicable).

www.dobreljekarne.com

**Comment by anthony0118** [comment]
Hi @tajLink 
As I am Full Stack Develop who has over 8 years of experience in PHP, JavaScript and CSS. I have built over 15 websites with PHP (Laravel, Symfony and CI) and implemented a lot of features and enhanced User friendly features with my experinece.
I am really interested on collaborating this project. I hope you have assign this issue to me.

**Comment by paulnoelcholot** [comment]
Hello @anthony0118

Unfortunately, we no longer maintain versions of PrestaShop before 8.0.x
To correct your problem, we invite you to do a version upgrade.
