### ISSUE TITLE
The new password policy is not present in the reset password page

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#35410]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
if you try to do the password reset steps, you will get the reset page where to set a new password two times
from this page is not present the new password verification, in fact it is possible to set weak password

![1](https://github.com/PrestaShop/PrestaShop/assets/653230/3deef0da-3e55-4ce3-88eb-cf84d4783833)

bye

### Steps to reproduce

1. go at login
2. push on the link "I don't remember the password"
3. set an email to get the reset link
4. push on the reset link
5. set a new password, but weak like "casetta"
6. Password verification will not appear

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

8.1

**Comment by paulnoelcholot** [comment]
Hello @maofree,

I reproduce the issue with PrestaShop version 8.1.x, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Nakahiru** [comment]
@paulnoelcholot, @kpodemski I think we can close the issue. It has been fixed on February 26 🙂
