### ISSUE TITLE
Duplicate 'Marketplace' and 'Themes Catalog' entry in backend

### ISSUE THREAD

**Issue by seakrebel** [PrestaShop/PrestaShop#35426]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

There is a duplicate 'Marketplace' and 'Themes Catalog' entry in backend. It started happening after upgrading from 8.1.2 to 8.1.4 using one-click-upgrade. 

I already tried disabling/enabling Marketplace plugin as well as disabling/clearing caches, and disabling ps_edition_basic but the issue persists. Only when Marketplace plugin is disabled - both menu entries disappear, which is expected.

![Screenshot 2024-02-20 at 13 27 24@2x](https://github.com/PrestaShop/PrestaShop/assets/16282150/7e21f3e1-634e-42a1-87ff-eb7b13b4dd3c)

![Screenshot 2024-02-20 at 13 32 49@2x](https://github.com/PrestaShop/PrestaShop/assets/16282150/00342faf-f4cb-4ffd-b386-dfc07772fcb0)

### Steps to reproduce

I guess upgrade from 8.1.2 to 8.1.4

### PrestaShop version(s) where the bug happened

8.1.4

### PHP version(s) where the bug happened

8.1.27

### If your bug is related to a module, specify its name and its version

ps_mbo v4.10.1

**Comment by paulnoelcholot** [comment]
Hello @seakrebel,

I tried to reproduce your issue but as you can see, I can't : https://www.loom.com/share/dab09803df0f4cf89a09fc3f9eb14f25?sid=69b917b3-783d-49ca-9fb7-c5d7f180e251

Did I miss something?

Thanks for your feedback

**Comment by seakrebel** [comment]
Weird. Especially since my site was a clean installation of 8.1.2, without any 3rd-party modules, and only in beginning phase of development.

The only 'major' thing I did was upgrade all stock modules (including one-click-upgrade to v5.0.0), and then I used the one-click-upgrade to upgrade PrestaShop from 8.1.2 to 8.1.4, after which the issue was first present.
There were no errors during the upgrade. I also tried reinstalling the 'Marketplace' module, but the issue was there again.

I not only cleaned the caches through PrestaShop interface, but also disabled caching, cleaned the caches manually from /var/cache, as well as purged and disabled Cloudflare caches and PageSpeed. But since the menu items disappear when 'Marketplace' (ps_mbo) plugin is disabled, then caching is irrelevant anyway.

![Screenshot 2024-02-21 at 14 05 40@2x](https://github.com/PrestaShop/PrestaShop/assets/16282150/194cc48e-3df9-4013-a94f-07e4775acdd7)

**Comment by sowbiba** [comment]
Hello
Do you remember which ps_mbo version you had before autoupgrading ?

**Comment by seakrebel** [comment]
Yes. Before running **1-Click Upgrade** I upgraded all modules to their newest version.
**ps_mbo** was initially at **v4.7.0**, then upgraded to **v4.10.1** (this is the answer to your question), and then I ran the **1-Click Upgrade**.

The **1-Click Upgrade** itself was at **v5.0.0** before I ran it.

**Comment by sowbiba** [comment]
Do I miss something ?

https://github.com/PrestaShop/PrestaShop/assets/7426640/2c2bb0ec-6a8e-444f-992a-688eabccc659

**Comment by seakrebel** [comment]
I think we can't reproduce it so easily. Is there any way I could check what had generated each of those duplicated menu entries? I tried looking for them in debug mode, but no idea where exactly to look.

**Comment by sowbiba** [comment]
If you are cumfortable with the DB, you can look at _PREFIX__tab and filter by tabs linked to ps_mbo

**Comment by sowbiba** [comment]
Re @seakrebel 

A new version of ps_mbo is coming very soon and will fix you issue 

You can view the PR here https://github.com/PrestaShopCorp/ps_mbo/pull/730

As soon as it's release, you just have to upgrade ps_mbo and your duplicated tabs will be solved 

Let us know if not. Thanks 😉

**Comment by sowbiba** [comment]
Hello

ps_mbo v4.10.2 is now available. Please upgrade and tell us if it fixes your issues

Thanks

**Comment by seakrebel** [comment]
![Screenshot 2024-02-23 at 11 07 14](https://github.com/PrestaShop/PrestaShop/assets/16282150/ed7d41f5-1197-4ed5-b666-6a0856354e18)

After updating to v4.10.2 and resetting the module (important step), it has been fixed! Thank you
