### ISSUE TITLE
1 click upgrade won't allow me to update Prestashop

### ISSUE THREAD

**Issue by KKE-motor** [PrestaShop/PrestaShop#35423]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
I'm upgading a Prestashop version from 1.6.1.23. In the control panel it says: You can update to PrestaShop 1.6.1.24.
I thought it would be better to upgrade to 1.6.1.24 before going to 8.x, but really don't care IF I could just upgrade to the newest.
However, 1 click upgrade wont let me upgrade. It says that the 1 click upgrade module needs to be update (even tho in the same sentence it says its the newest version). So Im stuck in a loop where I can upgrade the module but nothing changes
Please see the screen shots. Can you help me "get out of this loop?" so I can upgrade?
![Screenshot_1](https://github.com/PrestaShop/PrestaShop/assets/160591398/3eef18de-28e3-4799-8581-69f554fa0b6c)
![Screenshot_2](https://github.com/PrestaShop/PrestaShop/assets/160591398/1f8a9c57-3d49-4b2a-b42b-b0764dacad0d)

### Expected behavior

After I click Upgrade, the 1 click Upgrade module should allow be to upgrade the Prestashop install.

### Steps to reproduce

1. Advanced functions
2. 1 click upgrade
3. Line 1 "1 click upgrade" presss Update
4. After update go to 1. (now the check marks should all be gree)

### PrestaShop version(s) where the bug happened

1.6.1.23 to 1.6.1.24

### PHP version(s) where the bug happened

1.6.1.23

### If your bug is related to a module, specify its name and its version

1-click upgrade v4.14.2 - byPrestaShop

### Your company or customer's name goes here (if applicable).

KKE Motorer

**Comment by KKE-motor** [comment]
Hi
I cheated the xml file for the 1 click upgrade module. Changed from 4.14.2 to 5.0.0.

Like:  <version><![CDATA[5.0.0]]></version> in the config.xml in /public_html/modules/autoupgrade

Now the check list is all green and it is installing. I hope it ends well, but the above solved the issue

**Comment by AureRita** [comment]
Thank you for your report, 

We're delighted that you were able to find a solution to your issue.
