### ISSUE TITLE
opgrade prestashop stoped at 85% 

### ISSUE THREAD

**Issue by MTProDK** [PrestaShop/PrestaShop#35432]

**Comment by matks** [comment]
@MTProDK Please dont post here your FTP password it is a public space anybody could get it

**Comment by MTProDK** [comment]
Where shall I make the ticket

Fra: Mathieu Ferment ***@***.***>
Sendt: 20. februar 2024 22:20
Til: PrestaShop/PrestaShop ***@***.***>
Cc: Michael Thomsen ***@***.***>; Mention ***@***.***>
Emne: Re: [PrestaShop/PrestaShop] opgrade prestashop stoped at 85% (Issue #35432)


@MTProDK<https://github.com/MTProDK> Please dont post here your FTP password it is a public space anybody could get it

**Comment by MTProDK** [comment]
problem solvet by A2Hosting
