### ISSUE TITLE
BO - statslive - Activity overview, Online Visitors redirects to an archived module

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#35448]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The link Online Visitors redirect to an archived module.

https://github.com/PrestaShop/statslive

https://github.com/PrestaShop/PrestaShop/assets/16019289/4ce28fdd-9f19-4c1f-ad5f-4d40285f2ef1

### Expected behavior

The link should not be displayed anymore.

### Steps to reproduce

1. Go to BO > In Activity overview > Click on Online Visitors
2. See Module not found

### PrestaShop version(s) where the bug happened

8.0.x, 8.1.x, develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

statslive

**Comment by Hlavtox** [comment]
@florine2623 Fixed here - https://github.com/PrestaShop/dashactivity/pull/43
