### ISSUE TITLE
alt tags are filled with the titles

### ISSUE THREAD

**Issue by BasilDiouf** [PrestaShop/PrestaShop#35446]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, I am writing because today I found that all my alt tags are filled with the titles of my products instead of the captions I have written. I have the same issue with both the theme I purchased and the classic theme.

### Expected behavior

I would like my alt tags to be filled with my captions.

### Steps to reproduce

Go to any product page.
Inspect an picture.
You can see the title of the product.

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.2

**Comment by BasilDiouf** [comment]
![Screenshot 2024-02-22 091244](https://github.com/PrestaShop/PrestaShop/assets/134514622/1baf937f-9cdb-4960-8745-48f376ab444e)

**Comment by BasilDiouf** [comment]
![Screenshot 2024-02-22 091352](https://github.com/PrestaShop/PrestaShop/assets/134514622/baa7659e-6151-42a4-a907-36913351842d)

**Comment by florine2623** [comment]
Hello @BasilDiouf ,

I can't reproduce your issue on `8.1.x` and `develop`.

On `8.1.x` :

<img width="1154" alt="Screenshot 2024-02-22 at 09 43 08" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/93137f49-d10a-4b0a-8571-334736a786f6">
<img width="876" alt="Screenshot 2024-02-22 at 09 43 14" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/71570fd5-0edd-49a4-9bd8-29cb2cc572bc">


On `develop` :
<img width="1198" alt="Screenshot 2024-02-22 at 09 39 40" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/a0352932-526d-45d9-8528-d4c03bba5e9c">

<img width="1433" alt="Screenshot 2024-02-22 at 09 40 03" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/9a73fd27-dec7-4903-a6a7-3979b8c961d6">


**Please try to clear your cache from PS and from browser.**


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by Hlavtox** [comment]
@BasilDiouf Hey, it has been fixed on 8.1.3. Upgrade your prestashop and it will work properly. ;-)

It was this PR if you want to apply the changes manually - https://github.com/PrestaShop/PrestaShop/pull/34689
