### ISSUE TITLE
 Module error ps_cashondelivery/validation

### ISSUE THREAD

**Issue by casamarsel** [PrestaShop/PrestaShop#35444]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

no carga la validacion del pago contra reembolso, 
https://casamarsel.es/module/ps_cashondelivery/validation 
appears the next message The gateway did not receive a timely response from the upstream server or application.
It is not allowing the customer to complete the purchase, because the module does not respond

### Expected behavior

That the customer can complete the purchase

### Steps to reproduce

1. Go to the store at casamarsel.es then add products to the cart.
2. Fill out customer information.
3. choose shipping method (delivery)
4. Choose cash on delivery payment method.
5. proceed to validate order
6. error

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.2.16

### If your bug is related to a module, specify its name and its version

Cash on delivery (COD) v2.0.1

### Your company or customer's name goes here (if applicable).

Casa marsel

**Comment by casamarsel** [comment]
help

**Comment by florine2623** [comment]
Hello @casamarsel ,

I'm using Cash on delivery (COD) v2.0.1 on PS 8.1.x and develop. 
I can't reproduce your issue, the checkout process works well.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
