### ISSUE TITLE
New Product Page - Image - Webp too big ? and wrong error message

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#35443]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi, when I want to upload a Webp Image on my product, when this one seems to be to big, I have an error message but it's not related to the issue, as we can see : 

[recording(107).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/d02c4c7a-b52e-4045-8046-6cf2704ed450)

### Expected behavior

I wish I could use any Webp Image

### Steps to reproduce

1. GO to BO
2. Go to catalog > Products
3. Create a new simple product
4. On the image, try to put a webp with more than 45 Ko 
5. You should have the same error than me 

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

PS

**Comment by Hlavtox** [comment]
@AureRita Hey, could you try to put the image here and send a screenshot of the result? https://www.checkfiletype.com/

I think the image is somehow damaged or something else is inside other than webp, 45kb is nothing.

**Comment by florine2623** [comment]
Hello @AureRita ,

I can't reproduce your issue on 9.0.0. I'm using 2 images, size 30 KB and 61 KB.

https://github.com/PrestaShop/PrestaShop/assets/16019289/aeb15326-cdd0-402a-b28c-26f87f5c654a

Am I missing something ?

**Comment by AureRita** [comment]
Hi @Hlavtox 

Thank you for your help, I tested with your website and tell me that it's an ISO image, how could it be possible ? 

![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/21ef80ee-cd2f-42a5-bea2-aed7dd96a467)

@florine2623 You didn't miss thing 

I'll close this issue because it's not related to Webp but @Hlavtox I'd be happy to know how it's possible that the file is of iso type 

Thank you.

**Comment by Hlavtox** [comment]
@AureRita I have no idea what it is dude. 🤣 But good, it's not a problem with the core. :-)
