### ISSUE TITLE
Faceted search problem

### ISSUE THREAD

**Issue by jaroslav61** [PrestaShop/PrestaShop#35457]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have a problem with displaying product availability in the Faceted search module. Availability is showing correctly for some products. "In stock" and "Unavailable". See image good.png
But for some it shows me like this: "In stock" "Available" and "Unavailable" See image bad.png. It should only show "In Stock" or "Available" and "Unavailable". There should only be two options. Some products are displayed with both "In stock" and "Available" filters

### Expected behavior

 There should only be two options. In Stock and Unavailable

### Steps to reproduce

1. Go to Main Page [https://www.srubky.sk](url)
2. Click on left  menu "Srubky"
3. See Faceted filter
4. There are 3 availabilities: In Stock, Available, Unavailable.
5. --
6. Go to Main Page [https://www.srubky.sk](url)
7. Click on left Menu "Kotvy mechanicke do betonu"
8. See Faceted filter
9. There are 2 availabilities: In Stock and Unavailable.

### PrestaShop version(s) where the bug happened

8,0.5

### PHP version(s) where the bug happened

8.1.27

### If your bug is related to a module, specify its name and its version

ps_facetedsearch v.3.15.0

### Your company or customer's name goes here (if applicable).

Stealthtech, s.r.o.

**Comment by Hlavtox** [comment]
@jaroslav61 Hi Jaroslav, this is an expected behavior, when the amount of products available and in stock is the same, it has no sense to show both filters. :-)

**Comment by jaroslav61** [comment]
I don't know if I understand it right, but I don't display both filters. I have only three filters set in the settings of the Faceted search module. Price filter, Properties filter and stock filter. I don't understand why both the stock filter and the availability filter are displayed there.
![filt](https://github.com/PrestaShop/PrestaShop/assets/161019354/9f620d92-8d5e-47de-a596-f6a56f269471)

**Comment by Hlavtox** [comment]
@jaroslav61 Vysvětlím. :-)

Filtr zobrazuje 3 možnosti:
- Produkty skladem (ks skladem > 0)
- Produkty které jdou objednat, nemusí být skladem
- Produkty co nejsou skladem a nejdou objednat

No a protože si lidi stěžovali, proč mají v tom filtru možnosti "Skladem" a "Dostupné", když to ukazuje úplně to samý. No, protože všechno co jde objednat, mají i skladem, což je i případ tvojí kategorie. Tak jsme to udělali tak, že jsme schovali tu druhou volbu, pokud ty počty jsou stejné.

**Comment by jaroslav61** [comment]
Môžeš mi poradiť ako to opraviť? Neviem kde to mám spraviť. Produkty mám nastavené tak, že ak nie je skladom, nedá sa objednať. 
Ďakujem

**Comment by Hlavtox** [comment]
@jaroslav61 Nijak, takhle je to prece spravne. Proc bys tam mel dve hodnoty, ktere budou ukazovat stejne zbozi? :-)

**Comment by jaroslav61** [comment]
Nejak tomu nerozumiem. Mne sa zobrazujú dve hodnoty, Na sklade a dostupné. A to já nechcem. Chcem tam mať len Na sklade a  Nedostupné. Toto neviem ako vyriešiť.

**Comment by Hlavtox** [comment]
@jaroslav61 Uz rozumim. :-) Muzes to vyresit upravou funkce `getAvailabilitiesBlock` v souboru `modules/ps_facetedsearch/src/Filters/Block.php`.

Mozna to udelam do budoucna editovatelne, aby bylo mozne zvolit, jake hodnoty zobrazovat.

Tu issue zatim ted zavru, protoze to neni bug. 👍

**Comment by jaroslav61** [comment]
Ďakujem za pomoc. Ale môžeš mi ešte poradiť čo mám v tom súbore zmeniť?

**Comment by jaroslav61** [comment]
Zablokoval som túto funkciu. Teraz to ide správne. Spravil som to dobré?

       /*    $availabilityOptions[Availability::AVAILABLE]['nbr'] = $filteredSearchAdapter->count();

            // Products in stock
            $filteredSearchAdapter->addOperationsFilter(
                Search::STOCK_MANAGEMENT_FILTER,
                [
                    [
                        ['quantity', [0], '>'],
                    ],
                ]
            );
          */

**Comment by Hlavtox** [comment]
@jaroslav61 Jo, to stačí. :-) Ještě můžeš vymazat `Availability::AVAILABLE` z `$availabilityOptions` o kousek výš.

**Comment by jaroslav61** [comment]
OK,ešte raz ďakujem za pomoc.
