### ISSUE TITLE
Ps_accounts make it impossible to reset password

### ISSUE THREAD

**Issue by Prestaworks** [PrestaShop/PrestaShop#35454]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When the module ps_accounts is installed, the login page to the BO is replaced. 
When clicking on the "connect with another method" to try to login with a regular account, the password reset feature does not work.
Clicking on "I forgot my password" will send a link to my email, but when clicking on that link, instead of the password reset form, I get the ps_accounts login page. Thus, I am not able to reset my password any more.

### Expected behavior

I expect to be able to reset my password even if ps_accounts is installed.

### Steps to reproduce

1. Install and configure ps_accounts
2. create a new employee
3. log out from your account
4. use the forgot password feature found under "connect with another method" 
5. click the link sent to your email.

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

8.1.12

### If your bug is related to a module, specify its name and its version

ps_accounts 6.3.2

### Your company or customer's name goes here (if applicable).

Prestaworks AB

**Comment by Hlavtox** [comment]
@Prestaworks Hi, you need to contact Prestashop SA with this. This is not an opensource module. 👍
Ping @sowbiba

**Comment by Prestaworks** [comment]
> @Prestaworks Hi, you need to contact Prestashop SA with this. This is not an opensource module. 👍 Ping @sowbiba

I tried :D but their support at addons don't understand the issue..

**Comment by Hlavtox** [comment]
@matks @kpodemski Guys could you please forward this to somebody competent so @Prestaworks can skip the L1 support? :-))

**Comment by sowbiba** [comment]
I'm in the MBO team @Hlavtox , not accounts

Maybe @atourneriePresta or @hschoenenberger ?

**Comment by kpodemski** [comment]
I sent the issue to the team responsible for ps_accounts.
