### ISSUE TITLE
Text Formatting Bar disappeared

### ISSUE THREAD

**Issue by maurizioioppolo** [PrestaShop/PrestaShop#35461]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

As you can see from the image enclosed:
![problema](https://github.com/PrestaShop/PrestaShop/assets/89464623/7ee45c0c-4ace-4465-9700-650ed2f909e4)

I cannot edit anymore any text in the website since the Text Formatting Bar is not visible anymore. How can i solve that?

### Expected behavior

The expected behaviour is the Text Formatting Bar visible as in this image:
![image](https://github.com/PrestaShop/PrestaShop/assets/89464623/59480e79-50c6-40b5-aaf7-37f2f079cfca)

### Steps to reproduce

go to Design/Pages and try to edit any page

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

7.4.33

**Comment by florine2623** [comment]
Hello @maurizioioppolo ,

I can't reproduce your issue :
<img width="1440" alt="Screenshot 2024-02-26 at 10 45 15" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/7f89b61f-5144-4326-804e-7fc35cdbaa7e">

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
