### ISSUE TITLE
BO - Order Creation - Customizable product with same customization can be added to an order individually

### ISSUE THREAD

**Issue by dustsucker** [PrestaShop/PrestaShop#35478]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I add a product with customization to an order, when the same customization is added, it should not add another product, but it should increase the quantity of the existing product.

https://github.com/PrestaShop/PrestaShop/assets/16019289/e7eb0a1a-5177-44d9-8fbe-d958d37b162c

### Expected behavior

Exact same customization should be detected and stacked.

### Steps to reproduce

1. Go to BO > Orders > Add an order > Choose Customer
2. Choose "Customizable mug" > Add a Customization "hello" > Add to cart
3. Click again on Add to cart
4. 2 entities of the same products with the same custom are added :x: 

### PrestaShop version(s) where the bug happened

8.1.3, develop

### PHP version(s) where the bug happened

8.1.27

### Your company or customer's name goes here (if applicable).

Symcon GmbH

**Comment by florine2623** [comment]
Hello @dustsucker 

I have reproduced just a part of your bug and edited your issue to make it more clear.

Thanks for the report!

**Comment by dustsucker** [comment]
I recorded it one time it worked to change the amount the other time not. 
[Screencast 2024-02-27 11:14:57.webm](https://github.com/PrestaShop/PrestaShop/assets/17184952/49a560b7-ef14-4b42-890d-7312341ccae7)

I hope this helps to Explain it a bit better

**Comment by Hlavtox** [comment]
This is expected behavior, ping @kpodemski

**Comment by TheoAlloin** [comment]
Hi @Hlavtox , TBH I don't get your point. 

Adding two times the same product with the same customization should generate two different product lines in the cart?

**Comment by Hlavtox** [comment]
Yes, because they have different customization ID, and the only way you are able to reproduce it is because the field is not cleared after adding it to cart. It would also provide incosistent results - you would magically merge two text customizations, but what about files, images, module customizations.

**Comment by kpodemski** [comment]
I don't see this as a bug + I see potential errors in third-party modules.

**Comment by MatShir** [comment]
If the custom is strictly the same, why not incrementing the stock directly ? @kpodemski or @Hlavtox do you have use cases where it is required to have 2 distinct product into the cart with the same custo ?

**Comment by Hlavtox** [comment]
@MatShir You don't know what modules are doing with the customization, they may save custom data for the given customization ID to another table or something.

This is not reproducible in FO and would just bring confusion.

**Comment by kpodemski** [comment]
I agree with @Hlavtox. We risk unexpected behavior for a little added value.

**Comment by MatShir** [comment]
I trust @kpodemski and @Hlavtox about the impact and side effects that such a minor change can bring. I think for now we can live with this bug around, I'm closing the PR and the issue. 
Thanks anyway @TheoAlloin for the PR and @dustsucker for issue report 🤗

**Comment by dustsucker** [comment]
> I recorded it one time it worked to change the amount the other time not. [Screencast 2024-02-27 11:14:57.webm](https://github.com/PrestaShop/PrestaShop/assets/17184952/49a560b7-ef14-4b42-890d-7312341ccae7)
> 
> I hope this helps to Explain it a bit better

@MatShir As I showed here, it's not just the stacking, I cannot reliably add the Amount I Want to the Cart I can live without the Merging of the Two Products with the same Modification I cannot live with the fact that I add 4 Tot the Cart after I already added one, and it just adds 3 or sometimes only 2 so it's not reliable to add the amount I specify. If it's not stacking fine, but why can't I just add the same amount twice? And why is it changing the mount to 3 and not 4 as I specified? Especially I had already 2 in the cart and added 4, I could live with the fact that it made it 4 Total if it was reliable. I could reproduce this issue on 2 Separate Installations, one with only one module installed, the other just with one, but that didn't hook into anything with Products. This is a Deal braking issue for us if we can't trust the system to behave in the same way with adding Products every time, we can't use the system as we rely heavily on user customizations. Please review again.

**Comment by Hlavtox** [comment]
@dustsucker Customizations being buggy is one thing, stacking them is another. 👍
