### ISSUE TITLE
Multiple Carrier Options, splitting the order even if one option is free shipping only one Order Overview.

### ISSUE THREAD

**Issue by dustsucker** [PrestaShop/PrestaShop#35475]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

As I didn't find an exact Issue Describing it, but some Really close ones:

If I want to Order 2 Different Products, one with a Free shipping digital Delivery (With Variations so not a virtual Product) and the Other with DHL Delivery Both Options Are Configured one Item is only Virtual, and the Other is a Physical Product so need to be shipped. After I order the Products, the Order is Spit according to the Carrier Option(DHL and Virtual Product Delivery). And only one Order Overview is showing with only one Product, so the Customer Only Sees the One Product ordered in the Browser. But is Send 2 Emails with the Order Overview. 

Cart: 
![grafik](https://github.com/PrestaShop/PrestaShop/assets/17184952/c764abba-68c8-4c74-85fb-c45723e2f1a5)

Sometimes Displays: "Digital Versand" (Virtual Product Delivery) some time DHL and always Displays the Fee for the Highest Price but with Wrong name.

![grafik](https://github.com/PrestaShop/PrestaShop/assets/17184952/34801477-0826-4f07-b8b6-7aea66c7049c)

only one tab with Order Confirmation and only one Product contained:
![grafik](https://github.com/PrestaShop/PrestaShop/assets/17184952/e5614627-4b62-4a06-b297-af0ecf2ebba5)

Next Issue: there is no option as far as I could research To not Split the Order and just use the highest Delivery Option if one is free.

### Expected behavior

Both Products Should either be contained in one Order with Product Specific Delivery or split but shows both Order Confirmations, so the Customer is Informed in the Browser that all the Product will be delivered.  On top of that, the Delivery Option Should not be displayed one as there are two different Delivery Options (But I can live with one if I can set the name reliably to DHL at the moment I think it's Last added or something like this).

### Steps to reproduce

Complicated:
1. Add 2 products with Variants
2. Add 2 Delivery Options one Free, one with Fee
3. Assign the 2 Products Different Delivery Options
4. Add Both Products to the Cart and Order 

### PrestaShop version(s) where the bug happened

1.8.3

### PHP version(s) where the bug happened

8.1.3 

### Your company or customer's name goes here (if applicable).

Symcon GmbH

**Comment by florine2623** [comment]
Hello @dustsucker ,

Is your issue similar to https://github.com/PrestaShop/PrestaShop/issues/13080 ?

**Comment by dustsucker** [comment]
Yes that is certainly a Part of the issue. The Part with spliting and not showing all the items in the order confirm seems to be missing. But seems to be similar.

**Comment by dustsucker** [comment]
The part that I'm missing in https://github.com/PrestaShop/PrestaShop/issues/13080 is that I ordered 2 Things and only got one confirmed within the Browser. The confirmation itself is missing a part Of the Order. It Would be Fine if it just opened 2 Tabs with Both Confirmations, not ideal, but at least the customer has a chance to see both order confirmations.

**Comment by florine2623** [comment]
Hello @dustsucker ,

We have an Epic with all the bugs regarding multicarriers options : https://github.com/PrestaShop/PrestaShop/issues/15491

I think your issue is a mix between https://github.com/PrestaShop/PrestaShop/issues/13080, https://github.com/PrestaShop/PrestaShop/issues/22836 and https://github.com/PrestaShop/PrestaShop/issues/15369

So I will be closing your issue to avoid clogging the backlog.
Once these issues are fixed, your issue will be fixed as well.
You can subscribe to these issues if you want to follow the progress.

Thanks for reporting this ^^
