### ISSUE TITLE
UndefinedFunctionException - Attempted to call function "imagecreatefromjpeg" from the global namespace.

### ISSUE THREAD

**Issue by b44x** [PrestaShop/PrestaShop#35493]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

During the installation process, if PHP is not compiled with the '--with-jpeg' flag, attempting to install (template step) - results in an HTTP 500 error. This issue poses a significant challenge for regular users who may not be aware of the underlying cause.

trace:
```
Attempted to call function "imagecreatefromjpeg" from the global namespace.
(1/1) UndefinedFunctionException
Attempted to call function "imagecreatefromjpeg" from the global namespace.

in ImageManager.php line 619
at ImageManagerCore::create(2, '/www/hidden.pl/install/langs/bs/img/bs.jpg')
in ImageManager.php line 318
at ImageManagerCore::resize('/www/hidden.pl/install/langs/bs/img/bs.jpg', '/www/hidden.pl/img/p/bs-default-cart_default.jpg', 125, 125)
in Install.php line 712
at Install->copyLanguageImages('bs')
in Install.php line 1191
at Install->installTheme('classic')
in process.php line 294
at InstallControllerHttpProcess->processInstallTheme()
in process.php line 104
at InstallControllerHttpProcess->process()
in controllerHttp.php line 277
at InstallControllerHttp::execute()
in index.php line 53
```

### Steps to reproduce

1. Begin a fresh installation of the software.
2. Ensure that PHP is not compiled with the '--with-jpeg' flag.
3. Attempt to install

### PrestaShop version(s) where the bug happened

8.1.4

### PHP version(s) where the bug happened

8.3

**Comment by Hlavtox** [comment]
@b44x Can you provide a PR for this that will test if some basic GD methods are available?

This is the current check, but clearly not enough. :-)
```
public static function test_gd()
    {
        return function_exists('imagecreatetruecolor');
    }
```

Ping @PrestaShop/tech-council

**Comment by kpodemski** [comment]
`imagecreatefromjpeg` is something that PrestaShop has required for ages already :) It is not a new requirement.

**Comment by paulnoelcholot** [comment]
Hello @b44x,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
