### ISSUE TITLE
Prestashop 1.8.1  Invoice cannot be issued again with right amount after Partial refund

### ISSUE THREAD

**Issue by kpoptown** [PrestaShop/PrestaShop#35491]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I issued a refund from " Partial Refund" Button from prestashop
One of two items is sold out and I issued a paypal refund withint prestashop admin page

And I need Corrected / New invoice for customer
But I cannot get the new invoice after partial refund

### Steps to reproduce

1. Orders 
2. Choose any order and Partial Refund
3. View Invoice

### PrestaShop version(s) where the bug happened

1.8.1

### PHP version(s) where the bug happened

7.4

### Your company or customer's name goes here (if applicable).

dhglobal

**Comment by florine2623** [comment]
Hello @kpoptown ,

The invoice is not edited, you will either have a Credit slip or a Voucher created after issuing a Partial Refund ^^
Legally, you cannot change an invoice.

I'm closing your issue.
