### ISSUE TITLE
Email alert problém

### ISSUE THREAD

**Issue by jaroslav61** [PrestaShop/PrestaShop#35497]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Even though I have the Product Availability option enabled in the Email alerts module, I don't see the address field and submit button on the product tab.
We are trying to hook module "Email Alert" for product page position name "displayProductAdditionalInfo" but i can see in store admin panel there is js related console error so, we can not hook module

### Expected behavior

Email alert on product page

### Steps to reproduce

1. Go to on product page on [https://www.srubky.sk](url)
2. The field for the email address and the send button are not displayed on the product page

### PrestaShop version(s) where the bug happened

8.0.5

### PHP version(s) where the bug happened

8.1.27

### If your bug is related to a module, specify its name and its version

ps_emailalerts

### Your company or customer's name goes here (if applicable).

Stealthtech, s.r.o.

**Comment by jaroslav61** [comment]
Screenshot from Hook Position
![ea](https://github.com/PrestaShop/PrestaShop/assets/161019354/374c4a7c-d410-4a40-98cc-5d4a316a9d11)

**Comment by florine2623** [comment]
Hello @jaroslav61 ,

I can't reproduce your issue.

<img width="1185" alt="Screenshot 2024-02-27 at 15 32 46" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/eb7525d2-a828-47c1-9caf-285f5f05d58d">

Make sure in Positions your Mail alerts module is well hooked to **displayProductAdditionalInfo** :

<img width="882" alt="Screenshot 2024-02-27 at 15 33 54" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/0b27d1d0-860d-4979-a63e-a5c2eeed6f58">

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
