### ISSUE TITLE
Add a redirection function 301 or 302 on Category page

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#35500]
### Is your feature request related to a problem? 

It is a problem for SEO not to have this function add redirection function 301 or 302 on category page
I am always frustrated when I see that Prestashop has set up on the product pages the 301 or 302 redirects to another product or category and that this has not been done also for the category pages

### Describe the solution you'd like

We could take a large part of the code of the product page to adapt it to the category page and to redirect 301 or 302 to another category page or to choose why not a CMS page in order to keep the SEO referencing of this category

### Specs

Below the form group of the **Friendly URL**, add the form group **Redirection when not displayed**. The form group is composed of the label **"Redirection when not displayed"** and a dropdown with 4 options:

- Permanent redirection to a category (301)
- Temporary redirection to a category (302)
- No redirection (404), display error page
- No redirection (410), display error page
The default value is “Permanent redirection to a category (301)” with default category select ("Home") 

if it is the root category, only list:
- No redirection (404), display error page
- No redirection (410), display error page
The default value is "No redirection (410)"

When “Permanent redirection to a category (301)” or “Temporary redirection to a category (302)” is selected 
Then **Target category** field is displayed. This search field is displayed if you select in the dropdown Permanent redirection to a category or Temporary redirection to a category.

There is a placeholder: `“To which category the page should redirect ?”`

If no category is selected, the Home Category is used.

You can search by category name. When you start typing, if there are results, they are displayed under and you can click on it. Then, the selected category is displayed under the field.

Information message is displayed below the droplist:

```
"Permanent redirection (301) = Permanently display another category instead.

Temporary redirection (302) = Temporarily display another  category instead.

No redirection (404), display error page = Do not redirect anywhere and display a 404 "Not Found" page.

No redirection (410), display error page = Do not redirect anywhere and display a 410 "Gone" page."
```

Upgrade to take into account 

### Acceptance test

When the categories X is not displayed and set at Permanent redirection to a category (301) 
Then on the FO the category page direct link displays the http error 301 page

**Comment by Hlavtox** [comment]
@MatShir Few remarks on this, I didn't get a chance to check it out properly...

So now all disabled categories automatically redirect to home category by default? So if I want to retain the behavior from previous PS versions, I need to go through each category on the shop and set it to 404? 🤔 There should be an option to set a default behavior, like I did for products.

Also, it would be good if you select 301/302 + don't specify any category, that it would redirect to the closest active parent. It would display far more relevant products than throwing the user to home category with no explanation.

Ping @jf-viguier, @ShaiMagal

**Comment by Hlavtox** [comment]
@kpodemski Please check this out. I forgot about this and saw that 301 redirect is now a default solution, that makes no sense.

Default behavior should be 410 or 404 page.
