### ISSUE TITLE
ps_facetedsearch - "duplicite" query - performance killer for e-shop with 200 000 products and for smaller as well

### ISSUE THREAD

**Issue by ShaiMagal** [PrestaShop/PrestaShop#35524]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Image, you have big customer with 200 000 products and there are 2 queries from module ps_facetedsearch. (They are taking 80% of performance -> loading time)

I understand usage of two queries, but there is possibility to do it with ONE query and then parse results with PHP.

I already tested this in "plain php" and results were great.
Now is website category with filter loading 4 seconds, but after this change 2.2 seconds, very big difference.

I have only one problem, I don't know how to edit ps_facetedsearch and change behaviour and from 2 queries make one and then from results one query parse results for 2 "use cases".

Already consulted with @Hlavtox last year.

This edit can be HUGE performance improvement for EVERYONE. Especially for big eshop or PrestaShop on poor hostings.
Any expert, who is able to edit funcionality of this module? (I am not able to do this, already tried, but I am not familiar with this module)

Query one:
`SELECT SQL_NO_CACHE p.id_product, sa.out_of_stock FROM (SELECT p.id_product, p.id_manufacturer, SUM(sa.quantity) as quantity, p.condition, p.weight, p.price, psales.quantity as sales, cp.position FROM ps_product p LEFT JOIN ps_product_attribute pa ON (p.id_product = pa.id_product) LEFT JOIN ps_product_attribute_combination pac ON (pa.id_product_attribute = pac.id_product_attribute) LEFT JOIN ps_stock_available sa ON (p.id_product = sa.id_product AND IFNULL(pac.id_product_attribute, 0) = sa.id_product_attribute AND sa.id_shop = 1  AND sa.id_shop_group = 0 ) LEFT JOIN ps_product_sale psales ON (psales.id_product = p.id_product) INNER JOIN ps_category_product cp ON (p.id_product = cp.id_product) INNER JOIN ps_product_shop ps ON (p.id_product = ps.id_product AND ps.id_shop = 1 AND ps.active = TRUE) INNER JOIN ps_category c ON (cp.id_category = c.id_category AND c.active=1) LEFT JOIN ps_category_group cg ON (cg.id_category = c.id_category) WHERE ps.id_shop='1' AND p.visibility IN ('both', 'catalog') AND cg.id_group='1' AND c.nleft&gt;=292 AND c.nright&lt;=293 GROUP BY p.id_product) p LEFT JOIN ps_product_attribute pa ON (p.id_product = pa.id_product) LEFT JOIN ps_product_attribute_combination pac ON (pa.id_product_attribute = pac.id_product_attribute) LEFT JOIN ps_stock_available sa ON (p.id_product = sa.id_product AND IFNULL(pac.id_product_attribute, 0) = sa.id_product_attribute AND sa.id_shop = 1  AND sa.id_shop_group = 0 ) INNER JOIN ps_category_product cp ON (p.id_product = cp.id_product) GROUP BY p.id_product ORDER BY IFNULL(p.quantity, 0) &lt;= 0, IFNULL(p.quantity, 0) &lt;= 0 AND FIELD(sa.out_of_stock, 0) ASC, p.position DESC, p.id_product DESC LIMIT 0, 39
`
Query two:
`SELECT SQL_NO_CACHE COUNT(DISTINCT p.id_product) c FROM (SELECT p.id_product, p.id_manufacturer, SUM(sa.quantity) as quantity, p.condition, p.weight, p.price, psales.quantity as sales, cp.position FROM ps_product p LEFT JOIN ps_product_attribute pa ON (p.id_product = pa.id_product) LEFT JOIN ps_product_attribute_combination pac ON (pa.id_product_attribute = pac.id_product_attribute) LEFT JOIN ps_stock_available sa ON (p.id_product = sa.id_product AND IFNULL(pac.id_product_attribute, 0) = sa.id_product_attribute AND sa.id_shop = 1  AND sa.id_shop_group = 0 ) LEFT JOIN ps_product_sale psales ON (psales.id_product = p.id_product) INNER JOIN ps_category_product cp ON (p.id_product = cp.id_product) INNER JOIN ps_product_shop ps ON (p.id_product = ps.id_product AND ps.id_shop = 1 AND ps.active = TRUE) INNER JOIN ps_category c ON (cp.id_category = c.id_category AND c.active=1) LEFT JOIN ps_category_group cg ON (cg.id_category = c.id_category) WHERE ps.id_shop='1' AND p.visibility IN ('both', 'catalog') AND cg.id_group='1' AND c.nleft&gt;=292 AND c.nright&lt;=293 GROUP BY p.id_product) p`

As you can see, this 2 queries is possible to merge to one query and we need limit 39 there, so we will use than PHP way:
array_slice($bla, 0, 39) and we get what we need and save nearly 2 seconds of mysql query
 + other small changes in query.
 This queries are nearly same
 
 This "feature" is problem X years, nothing new. Same for all module version, php version, prestashop version. Tested on more hostings and PrestaShops - still same results. Not related to any specific enviroment, global problem(feature).
 **Now can be good time to fix this and make PrestaShop category listing smoother.**

### Expected behavior

Only one mysql query with php parsing of results for 2 usage cases. Huge performance improvement.

### Steps to reproduce

1) enable filter for module
2) go to any category
3) enable profiling
4) you will see "duplicite" query

### PrestaShop version(s) where the bug happened

8.1.4

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

3.15.0

### Your company or customer's name goes here (if applicable).

openservis.cz

**Comment by lmeyer1** [comment]
Sure, ps_facetedsearch was not done with performance in mind...

**Comment by AureRita** [comment]
Hi @ShaiMagal 

Thank for your report,
This issue is too technical for me, ping @PrestaShop/tech-council , can someone please reproduce this issue ? 

Thanks

**Comment by Hlavtox** [comment]
Yep, that's a killer. Category with 4 thousand products, total load time 435 ms and half of this are those two queries. And also that query for specific prices, which I don't know what it's is purpose honestly.

 | Query | Time (ms) | Rows | Location
 |  --- |  --- |  --- |  ---
 | SELECT SQL_NO_CACHE p.id_product FROM (SELECT p.id_product, p.id_manufacturer, SUM(sa.quantity) as quantity, p.condition, p.weight, p.price, psales.quantity as sales, p.on_sale, p.date_add FROM ps_product p LEFT JOIN ps_product_attribute pa ON (p.id_product = pa.id_product) LEFT JOIN ps_product_attribute_combination pac ON (pa.id_product_attribute = pac.id_product_attribute) LEFT JOIN ps_stock_available sa ON (p.id_product = sa.id_product AND IFNULL(pac.id_product_attribute, 0) = sa.id_product_attribute AND sa.id_shop = 1  AND sa.id_shop_group = 0 ) LEFT JOIN ps_product_sale psales ON (psales.id_product = p.id_product) INNER JOIN ps_product_shop ps ON (p.id_product = ps.id_product AND ps.id_shop = 1 AND ps.active = TRUE) INNER JOIN ps_category_product cp ON (p.id_product = cp.id_product) INNER JOIN ps_category c ON (cp.id_category = c.id_category AND c.active=1) LEFT JOIN ps_category_group cg ON (cg.id_category = c.id_category) WHERE ps.id_shop='1' AND ps.visibility IN ('both', 'catalog') AND cg.id_group='1' AND c.nleft>=46 AND c.nright<=151 GROUP BY p.id_product) p LEFT JOIN ps_product_attribute pa ON (p.id_product = pa.id_product) LEFT JOIN ps_product_attribute_combination pac ON (pa.id_product_attribute = pac.id_product_attribute) LEFT JOIN ps_stock_available sa ON (p.id_product = sa.id_product AND IFNULL(pac.id_product_attribute, 0) = sa.id_product_attribute AND sa.id_shop = 1  AND sa.id_shop_group = 0 ) GROUP BY p.id_product ORDER BY p.quantity DESC, p.id_product DESC LIMIT 0, 24 | 97.1 | 2950662400 | /modules/ps_facetedsearch/src/Adapter/MySQL.php:86
 | SELECT SQL_NO_CACHE COUNT(DISTINCT p.id_product) c FROM (SELECT p.id_product, p.id_manufacturer, SUM(sa.quantity) as quantity, p.condition, p.weight, p.price, psales.quantity as sales, p.on_sale, p.date_add FROM ps_product p LEFT JOIN ps_product_attribute pa ON (p.id_product = pa.id_product) LEFT JOIN ps_product_attribute_combination pac ON (pa.id_product_attribute = pac.id_product_attribute) LEFT JOIN ps_stock_available sa ON (p.id_product = sa.id_product AND IFNULL(pac.id_product_attribute, 0) = sa.id_product_attribute AND sa.id_shop = 1  AND sa.id_shop_group = 0 ) LEFT JOIN ps_product_sale psales ON (psales.id_product = p.id_product) INNER JOIN ps_product_shop ps ON (p.id_product = ps.id_product AND ps.id_shop = 1 AND ps.active = TRUE) INNER JOIN ps_category_product cp ON (p.id_product = cp.id_product) INNER JOIN ps_category c ON (cp.id_category = c.id_category AND c.active=1) LEFT JOIN ps_category_group cg ON (cg.id_category = c.id_category) WHERE ps.id_shop='1' AND ps.visibility IN ('both', 'catalog') AND cg.id_group='1' AND c.nleft>=46 AND c.nright<=151 GROUP BY p.id_product) p | 85.1 | 737665600 | /modules/ps_facetedsearch/src/Adapter/MySQL.php:86
 | SELECT SQL_NO_CACHE COUNT(DISTINCT `id_product`) FROM `ps_specific_price` WHERE `id_product` != 0 LIMIT 1 | 33.4 | 22777 | /classes/SpecificPrice.php:283

**Comment by ShaiMagal** [comment]
I think, this issue will be solved by PR here:
https://github.com/PrestaShop/ps_facetedsearch/pull/1020

**Comment by ShaiMagal** [comment]
Closing, solved by 
https://github.com/PrestaShop/ps_facetedsearch/pull/1020
