### ISSUE TITLE
Geolocation in PS 8.1.4 is not compatible with PHP 8.1

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#35520]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I updated my PHP version from 8.0.30 to 8.1.27 and started to get errors in my log.
Note: I activated geolocation in my Prestashop.

```
Deprecated: Return type of GeoIp2\Model\AbstractModel::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
```

### Expected behavior

Since PS announces compatibility for PHP 8.1, I expect that there are no deprecation notices, even with geolocation activated.

### Steps to reproduce

1. Configure the server to log deprecation notices
2. Enable geolocation in the BO
3. Upgrade from PHP 8.0 to PHP 8.1

### PrestaShop version(s) where the bug happened

8.1.4

### PHP version(s) where the bug happened

8.1.27

### Your company or customer's name goes here (if applicable).

Société Biblique de Genève

**Comment by florine2623** [comment]
Hello @lmeyer1 ,

I have configured my Geolocation, I am using PHP 8.1.13.

I checked the files `php_error.log` and `apache_error.log` of my server but I have no errors regarding GeoIp2.

Is there something I am missing ?

Waiting for your feedback
Thanks!

**Comment by lmeyer1** [comment]
@florine2623
Do you have logging of deprecation notices enabled?
What version of geoip2/geoip2 do you have in your composer.lock? I had geoip2/geoip2 2.4.5, that was not compatible with PHP 8.1. I double checked in the PS 8.1.4 release where there is also 2.4.5.
Now I have geoip2/geoip2 2.13.0 that is compatible with PHP 8.1

**Comment by florine2623** [comment]
Yes, I haven't disable the deprecation notices on my server.

I also have v2.4.5.

Where do you see the compatibility of PHP with geoip2 ? I couldn't find that information.

**Comment by paulnoelcholot** [comment]
Hello @lmeyer1,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
