### ISSUE TITLE
Inappropriate "Invalid e-mail address" error message

### ISSUE THREAD

**Issue by Palmitch** [PrestaShop/PrestaShop#35539]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The form rejects any input with error message "Invalid e-mail address" (Adresse e-mail invalide. in French) even though the given e-mail address exists.

### Expected behavior

A proper e-mail address should be accepted by the form.

### Steps to reproduce

1. Go to https://www.anjea-skincare.fr/fr
2. Scroll to the footer
3. Try to insert your e-mail address

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_emailsubscription v2.8.1

### Your company or customer's name goes here (if applicable).

Anjea Skincare

**Comment by florine2623** [comment]
Hello @Palmitch ,

Tested this email address on a fresh install. I can't reproduce your issue.

https://github.com/PrestaShop/PrestaShop/assets/16019289/b5021376-a40b-4fef-ae7a-5044607f5bd8

You might have an external module that is blocking this feature.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
