### ISSUE TITLE
  Error page when configuring autoupgrade

### ISSUE THREAD

**Issue by M0rgan01** [PrestaShop/PrestaShop#35540]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

  Error page when configuring autoupgrade

![image](https://github.com/PrestaShop/PrestaShop/assets/36233446/f9df3920-b994-4404-9851-040823e3a23b)

### Expected behavior

No errors in configuration display

### Steps to reproduce

On a fresh store:

1. Install 1-Click Upgrade module
2. Go to configure
3. See error

### PrestaShop version(s) where the bug happened

9

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

autoupgrade 5.0.1

**Comment by AureRita** [comment]
Hi @M0rgan01 ,

Thank you for your report, I reproduce the issue with PrestaShop version develop, as you can see : 

[recording(124).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/d9b8d423-7ee0-4c8f-8d6c-2e134f331124)

I'll add this to the backlog so it can be fixed.

FYI : this issue isn't on 8.1.x. 

Waiting for your PR :rocket: 

Thanks

**Comment by Quetzacoalt91** [comment]
The legacy AdminController is supposed to be in the folder `controllers/admin`, but can be found in the root of the module.

Could this be the cause of the issue?
