### ISSUE TITLE
Mail alerts - Customer notifications - feature "Product Availability" not working 

### ISSUE THREAD

**Issue by ZT-UC** [PrestaShop/PrestaShop#35553]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After enabling this feature, there's no email / contact field for a customer to leave their email / contact when viewing the product which is out of stock.

### Expected behavior

addons.prestashop.com/en/emails-notifications/24547-mail-alerts.html
--

> Customer notifications:
> 
> Product Availability: when you enable this setting, a field appears on the product page of your shop when the product is out of stock and if you disallow order of out of stock products. It asks your customers to leave their contact information so that they may be contacted when your shop will have this product back in stock.

![IMG_01](https://github.com/PrestaShop/PrestaShop/assets/94435436/33a70a71-6f4f-409e-9f5d-851bbea82ceb)

### Steps to reproduce

Enable feature in PS administration under IMPROVE (left menu / panel)
--
Modules > Module Manager > Mail alerts > Configure > Product availability (1st option)

### PrestaShop version(s) where the bug happened

1.7.8.11

### If your bug is related to a module, specify its name and its version

ps_emailalerts v3.0.0

**Comment by AureRita** [comment]
Hi @ZT-UC 

Thank you for your report, currently I tried to reproduce your issue but I can't as you can see : 

[recording(126).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/890d2775-da9b-49c7-bb8c-6b281ca29077)

FYI : We have to test it on 8.1.x because currently this is the last branch that'll be update (except for security problems) 

Did your product is out of stock ? 
Did you are connected with an account ? 
Did I miss something ? 
(Instead of it, thank you for your title that give me many information :rocket: )

Waiting for feedback

**Comment by ZT-UC** [comment]
@AureRita Thanks a lot for your swift reply and information. All looks good on your end, but I've checked all settings again on my end and I still can't see why it's not working as intended. I'm definitely missing something, but I have no idea what / where.

> Did your product is out of stock ?
- yes, it is OOS

> Did you are connected with an account ?
- I've tried with an account (logged in / out), same results, no field there

**Comment by ZT-UC** [comment]
@AureRita Is there a chance that MA module is conflicting with another module?

**Comment by kpodemski** [comment]
@ZT-UC could you provide us with a full screenshot of the modules's settings page?

**Comment by ZT-UC** [comment]
@kpodemski Sure. See below.

![IMG_01](https://github.com/PrestaShop/PrestaShop/assets/94435436/66c2471c-028c-47a2-b046-5303b4fb0a3e)

**Comment by kpodemski** [comment]
@ZT-UC thank you, I wanted to make sure you have emails correctly set as you need to press enter key to insert them.

Do you see outgoing emails from this module in Advanced preferences -> Emails?

**Comment by ZT-UC** [comment]
@kpodemski Yes.

**Comment by ZT-UC** [comment]
@kpodemski Do you have any idea what could be causing the issue here?

**Comment by joecoolio66** [comment]
It works fine for us... try resetting the module.  If it's not showing up on your product pages it could also be theme related

**Comment by ZT-UC** [comment]
@joecoolio66 Uninstalling helped. Thanks.
