### ISSUE TITLE
Prestashop Edition Basic after update doesn't work

### ISSUE THREAD

**Issue by Theodoros7777** [PrestaShop/PrestaShop#35588]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

my first install is 8.1.3. I tried updating to 8.1.4 but the Edition Basic mod doesn't work and can't be uninstalled either. Any experience? what exactly is the difference between Prestashop 8 Edition Basic? Can I switch to the regular version?

### Steps to reproduce

1 click upadate a and then the non-functionality of the Edition Base module. the main page of the administration has changed the template.

### PrestaShop version(s) where the bug happened

8.1.4

**Comment by florine2623** [comment]
Hello,

Your issue has been shared with the Edition Team.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project.

Thank you

**Comment by Theodoros7777** [comment]
> Hello,
> 
> Your issue has been shared with the Edition Team.
> 
> We use GitHub issues only to discuss about bugs and new features in the PrestaShop project.
> 
> Thank you

Thank you.
