### ISSUE TITLE
Impossible de générer de clé privée à partir de openssl_pkey_new. 

### ISSUE THREAD

**Issue by rsbst** [PrestaShop/PrestaShop#35593]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

J'essaye d'installer prestashop mais je tombe sur l'erreur ci-dessous, j'ai essayer de creer un environement comme jai vu sur un tuto mai sca marche toujours pas. Merci d'avance
<img width="736" alt="Capture d’écran 2024-03-08 163600" src="https://github.com/PrestaShop/PrestaShop/assets/161261845/d9245555-bc37-48a9-b34f-11c34f3afdf7">
 

### Steps to reproduce

installation de prestashop

### PrestaShop version(s) where the bug happened

prestashop 8.1.4

**Comment by Hlavtox** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/33615, you need to properly configure your enviroment. Also, please open next issues in English. :-)

**Comment by rsbst** [comment]
i don t understand how to fix it

**Comment by AureRita** [comment]
Hi @rsbst 

FYI : Prestashop is not supported on Windows because it block the possibility to writte on some files like your first information box said. 
Moreover, you need to give more data to the parameters "realpath_cache_size" as the second block mention it 

I'll keep this ticket close because as Hlavtox said it, it's a dupplicate

**Comment by AureRita** [comment]
Duplicate of #33615,

**Comment by rsbst** [comment]
J'ai pas trouvé la réponse dans l'autre, si c'est si simple expliquez moi comment faire au lieu de me mettre dupliquer et classer ma question

**Comment by AureRita** [comment]
Hello,

Please send your request in English. English is the norm on GitHub. Moreover the answer of your question is three comments above. 

Thank you

**Comment by TeddyBear06** [comment]
@rsbst Je ne sais pas quel est votre environnement mais j'ai rédigé une solution possible (comme toutes configurations, il existe de nombreuses approches) avec `Wamp 3.3.7`, cf : https://github.com/PrestaShop/PrestaShop/issues/33615#issuecomment-2525311571

@AureRita With all the respect that I have for you, your answer do not help users to understand the real issue. I know that participating in an open source project is both time consuming and - sometimes - painfull but we have to care about people who use our software. Peace.
