### ISSUE TITLE
PrestaShop Marketplace update impossible

### ISSUE THREAD

**Issue by Sash10** [PrestaShop/PrestaShop#35592]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello !

First of all, thank you for your work on this project :) I'm sorry if this issue has been solved somewhere, I've found other similar problems but not one that seems to be fixing what I experience.

As you can see in the video attached, everytime I try to update PrestaShop Marketplace, it seems to be failing. I'm not refreshing the page or touching anything, I first get a pop up saying that the upgrade went well but then the notification saying that PS Marketplace should be updated appears again. 

When I check the logs I can see some errors too (that's what led me to some similar issues) but can't figure them out. 

Record of my screen : https://www.awesomescreenshot.com/video/25646679?key=4a555ad2ba3eed21c11da549c36f7137

Do you have any idea of what can cause this ? Let me know if you need more information of course.

Thanks a lot !

Sasha

### Expected behavior

I expect the upgrade to be taken into account

### Steps to reproduce

1. Go in the admin page
2. Try to update PS Marketplace

### PrestaShop version(s) where the bug happened

1.7.8.7

**Comment by paulnoelcholot** [comment]
Hello @Sash10 

I am really sorry for the inconvenience you are experiencing, unfortunately, versions prior to 8.0.0 are no longer maintained. We invite you to upgrade your store.

**Comment by picoroma** [comment]
I have same issue with PS 8.2.1
The upgrade process seems to be OK.. but the "upgradable" module " PrestaShop Marketplace in your Back Office
v4.13.1 arrow_forward v4.14.1" remain.

I havce this error - if I try to upgrade from inside the module:
An error occurred while upgrading PrestaShop Marketplace in your Back Office.
Unexpected token '<', "
