### ISSUE TITLE
Support palleted PNG file

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#35601]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

PrestaShop only support true color png file.

### Expected behavior

Support 8 bits png file

### Steps to reproduce

1. Upload a 8 bits png file (256 colors file)
2. Check the uploaded file: it is in true color and size is doubled

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

all

### Your company or customer's name goes here (if applicable).

Creabilis.com

**Comment by paulnoelcholot** [comment]
Hello @jf-viguier,

I reproduce the issue with PrestaShop version 8.1.x, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
