### ISSUE TITLE
BO > Design > Positions : Can't hook a module

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#35612]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The list of hooks was available in 8.1.x but not on develop.

`develop` : 
![image](https://github.com/PrestaShop/PrestaShop/assets/1533248/5239ec3f-5f01-4f96-95ae-a37eb110efab)

`8.1.4` : 
![image](https://github.com/PrestaShop/PrestaShop/assets/1533248/54c95926-4cd3-459b-90b9-714519e629ac)

### Expected behavior

The list of hooks is available.

### Steps to reproduce

1. Go to BO
2. Design > Positions
3. Click on "Hook a module"
4. Choose a module like "Bank transfer"
5. List of hooks is not available

### PrestaShop version(s) where the bug happened

9.0.x

### PHP version(s) where the bug happened

8.2

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

**Comment by AureRita** [comment]
Hi @Progi1984 ,

Thank you for your report, I reproduce the issue with PrestaShop version develop, as you can see : 

[recording(132).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/7325073a-0931-4224-b345-75d4b61ab33d)

I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved.

Thanks
