### ISSUE TITLE
Data conversion in backup

### ISSUE THREAD

**Issue by musicpanda** [PrestaShop/PrestaShop#35622]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

During restoration of a backup I found some problems with a table connected to a third party module that contained lots of non-Latin characters.

This led me to do some investigation and then I saw that Prestashop isn't doing any conversion when storing the data in the backup file. This probably worked when UTF8 was used, as the backup file uses UTF8. But I wonder whether that still always works with UTF8mb4. Also note that third party modules sometimes still use pre-UTF8 collations like latin1_swedish for their tables.

The Export class of phpMyAdmin does use conversion.

### Expected behavior

Correct conversion

### Steps to reproduce

Backup and retrieve a database with many non-Latin characters.

### PrestaShop version(s) where the bug happened

8

### PHP version(s) where the bug happened

8

**Comment by AureRita** [comment]
Hi @musicpanda 

Thank you for your report, currently your issue seems to relate the same issue than this one #35433. 

What do you think ? 
If you check it, you'll see that this issue have a PR related on it, you can test it on your shop to say us if it fix your issue. 

Waiting for your feedback

**Comment by musicpanda** [comment]
Hi  @AureRita 
I don't see any relationship. #35433  is not about backups.

**Comment by Hlavtox** [comment]
@AureRita The only thing simmilar in that issue is UTF8 in the name. :-))) Not related.

**Comment by florine2623** [comment]
Hello @musicpanda ,

I added some categories with arabic characters.
I did a DB Backup and downloaded it.
When I open the sql file, I find the items correctly :
<img width="336" alt="Screenshot 2024-03-21 at 16 40 20" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/a71251a1-dd4a-4f4c-bb47-8ef926c76408">

I am not sure I understand your issue, could you explicit it ?

Waiting for your feedback
Thanks!

**Comment by Hlavtox** [comment]
@musicpanda Can you try to dig in some more info about the table charsets?

But I think if the core tables backup & restore properly, we should bombard the module author, WDYT?

**Comment by florine2623** [comment]
Friendly reminder @musicpanda  ^^

**Comment by musicpanda** [comment]
> Friendly reminder @musicpanda ^^

I have no longer access to the shop where I noticed a problem. I did some study on the subject, but I don't yet fully understand the relationship between PHP and Mysql charsets. That makes it difficult to design experiments. So for the moment I see no alternative but closing this issue.
