### ISSUE TITLE
No best seller products

### ISSUE THREAD

**Issue by sirius82** [PrestaShop/PrestaShop#35636]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I don’t know if it’s a bug or not. I installed a new PS 8.1.4 ( downloaded here) and imported all the data from a PS 1.7.4. So there are commands. But the Best seller block does not display any products.

### Expected behavior

Display best sellers

### Steps to reproduce

1. The Theme is Panda. it has its own module to display best sellers. But it doesn't display anything. On the PS 1.7, best sellers are displayed.
2. I try with the native module of Prestashop. But it's the same

### PrestaShop version(s) where the bug happened

8.1.4

### PHP version(s) where the bug happened

8.2

### If your bug is related to a module, specify its name and its version

bestsellers

**Comment by florine2623** [comment]
Hello @sirius82 ,

With a fresh installation or an upgrade, the bet seller block is well displayed :
<img width="1146" alt="Screenshot 2024-03-13 at 10 05 01" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/c24c1f09-e3d2-4aa3-82a4-fbf485e2fb79">

Make sure your native module top-seller or the top seller block from your Panda theme is well hooked to displayHome :

<img width="881" alt="Screenshot 2024-03-13 at 10 07 19" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/12f36279-7e71-43a9-aa9d-e7efd0084ea8">

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by kpodemski** [comment]
Hello @sirius82 

It might be because of the fact that your order states don't see your orders as paid, and products from completed orders don't go to the best sellers table.

Do you have any data inside `ps_product_sale` table in your database?

**Comment by sirius82** [comment]
Krystian, you're right ! ps_product_sale is empty. Migration was made with MigratioPro. I don't understand why it didn't yet migrate this table. Do you think I can copy this table in the new install ? Is it different between 1.6 and 8 ? 
A very big thanks !

**Comment by kpodemski** [comment]
@sirius82 I think it's the same between versions, but make sure to backup table from target store anyway

**Comment by sirius82** [comment]
@kpodemski Yes it's the same. Of course, I imported it from the old database only after saving ;-)
A very very big thanks, you saved me !

**Comment by kpodemski** [comment]
@sirius82 great 👍🏻 happy to help :)
