### ISSUE TITLE
Manual update from PrestaShop 1.7.6.7 to PrestaShop 8.1.4 using CLI method fails - Symfony ClassNotFoundError

### ISSUE THREAD

**Issue by ersoftwaregmbh** [PrestaShop/PrestaShop#35635]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,

i'm trying to update manually from PrestaShop 1.7.6.7 to PrestaShop 8.1.4 using the CLI method outlined here: 

https://github.com/PrestaShop/docs/blob/131c273ba2b5b162206673298fb0c3c182fd1147/basics/keeping-up-to-date/upgrade-module/upgrade-cli.md

The upgrade module v5.0.1 has been installed via shop backend (module manager).

How can i avoid this error which comes from "Symfony" obviously?

![error-cli-upgrade](https://github.com/PrestaShop/PrestaShop/assets/69257372/e962c8d8-d191-435c-aa29-022ed2e9e9e7)

All previous steps were running fine.

(Linux Debian 12.5 / Plesk Obsidian 18.0.59 / PHP 7.4.33, also used for CLI)

Thanks!

### Expected behavior

A smooth update of the PrestaShop database structure.

### Steps to reproduce

cd /var/www/vhosts/xxx/httpdocs/
rm -rf var/cache/prod/
rm -rf var/cache/dev/

curl -L https://github.com/PrestaShop/PrestaShop/releases/download/8.1.4/prestashop_8.1.4.zip -o adminxxx/autoupgrade/download/prestashop.zip
curl -L https://github.com/PrestaShop/PrestaShop/releases/download/8.1.4/prestashop_8.1.4.xml -o adminxxx/autoupgrade/download/prestashop.xml
echo "{\"channel\":\"archive\",\"archive_prestashop\":\"prestashop.zip\",\"archive_num\":\"8.1.4\", \"archive_xml\":\"prestashop.xml\", \"PS_AUTOUP_CHANGE_DEFAULT_THEME\":0, \"skip_backup\": 1}" > modules/autoupgrade/config.json

php modules/autoupgrade/cli-updateconfig.php --from=modules/autoupgrade/config.json --dir=adminxxx

php modules/autoupgrade/cli-upgrade.php --dir=adminxxx --channel=archive --action=unzip
php modules/autoupgrade/cli-upgrade.php --dir=adminxxx --channel=archive --action=removeSamples
php modules/autoupgrade/cli-upgrade.php --dir=adminxxx --channel=archive --action=upgradeFiles
php modules/autoupgrade/cli-upgrade.php --dir=adminxxx --channel=archive --action=upgradeDb

### PrestaShop version(s) where the bug happened

1.7.6.7

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

upgrade-module 5.0.1

**Comment by AureRita** [comment]
Hi @ersoftwaregmbh 

Thank for your report,
This issue is too technical for me, ping @PrestaShop/tech-council , can someone please reproduce this issue ? 

Thanks

**Comment by Hlavtox** [comment]
@PrestaShop/tech-council Shouldn't there be a more specific namespace? (`use Behat\Transliterator\Transliterator;`)

https://github.com/PrestaShop/PrestaShop/blob/ee86802e5c73ca885e071c2e8ae530c5fe782023/src/Core/Util/String/StringModifier.php#L29

**Comment by ChillCode** [comment]
Faced the same issue and I think is already reported.

Avoided this one by temporally adding  a line `$module::updateTranslationsAfterInstall(false);` to `/modules/autoupgrade/upgrade/php/install_ps_distributionapiclient.php`

```
function install_ps_distributionapiclient()
{
    if (class_exists('Ps_Distributionapiclient')) {
        $module = new Ps_Distributionapiclient();
        $module::updateTranslationsAfterInstall(false);
        $module->install();
    }
}
```

You can give it a try if you really need it, and don't upgrade the modules through cli or will face the issue again if I remember correctly.

**Comment by ersoftwaregmbh** [comment]
Hi,

yes that did the trick, the ClassNotFoundError is gone. But now i'm getting this one:

<img width="910" alt="error-language-pack" src="https://github.com/PrestaShop/PrestaShop/assets/69257372/605a9037-b069-49c3-9520-d74a1aaa0e47">

How could this be possible?

**Comment by ChillCode** [comment]
Hi,

That one is weird and did not face it, I'd just try once again since looks like some network/connection issues between your site and PS project, or a corrupted language pack.

**Comment by venditdevs** [comment]
Isn't this a duplicate of: https://github.com/PrestaShop/PrestaShop/issues/31549?

**Comment by ersoftwaregmbh** [comment]
> Isn't this a duplicate of: #31549?

Not exactly. I'm trying to update to 8.1.4 and i think there's also a new version of the autoupgrade module.

**Comment by ersoftwaregmbh** [comment]
> Hi,
> 
> That one is weird and did not face it, I'd just try once again since looks like some network/connection issues between your site and PS project, or a corrupted language pack.

Ok. So how can i check what's going wrong? Are there any logs where i can check the error code or something? Alternatively, how i can i reproduce which steps are necessary to do the "database upgrade"? Can i do this manually? I do not need the language pack updated right now.

Thanks

**Comment by ersoftwaregmbh** [comment]
I've done the files update successfully. The problem is the database upgrade to 8.1.4. How can i do this manually? Are there any SQL files which will do the job, when i run them against the database?

<img width="909" alt="Bildschirmfoto 2024-03-20 um 16 13 32" src="https://github.com/PrestaShop/PrestaShop/assets/69257372/b826493c-e1ec-479c-a3f4-a9e126138b82">

**Comment by ChillCode** [comment]
> > Hi,
> > That one is weird and did not face it, I'd just try once again since looks like some network/connection issues between your site and PS project, or a corrupted language pack.
> 
> Ok. So how can i check what's going wrong? Are there any logs where i can check the error code or something? Alternatively, how i can i reproduce which steps are necessary to do the "database upgrade"? Can i do this manually? I do not need the language pack updated right now.
> 
> Thanks

That message is ambiguous, read before "Error during database upgrade."  it clearly says "Database Upgrade Ok" and then it says "Upgrading languages" and then fails, no? Maybe I'm reading another log.

So now looks like it fails during another process that is ligated to upgradeDb action. What happens if you go to BO and login as an admin?

**Comment by ersoftwaregmbh** [comment]
> > > Hi,
> > > That one is weird and did not face it, I'd just try once again since looks like some network/connection issues between your site and PS project, or a corrupted language pack.
> > 
> > 
> > Ok. So how can i check what's going wrong? Are there any logs where i can check the error code or something? Alternatively, how i can i reproduce which steps are necessary to do the "database upgrade"? Can i do this manually? I do not need the language pack updated right now.
> > Thanks
> 
> That message is ambiguous, read before "Error during database upgrade." it clearly says "Database Upgrade Ok" and then it says "Upgrading languages" and then fails, no? Maybe I'm reading another log.
> 
> So now looks like it fails during another process that is ligated to upgradeDb action. What happens if you go to BO and login as an admin?

I can only login to BO if i enable debug mode (otherwise, there's a 500 error). After login, some translations are missing. But it's a PrestaShop 8.1.4.

**Comment by ChillCode** [comment]
You can try to upgrade languages, theme and modules through BO and then delete cache folders, those are the steps you're missing, also the tabs reorder but it's not critical.

And if everything works it's required you to change PS_DB_VERSION in ps_configuration table to 8.1.4.

But I'd try to solve that package issue so installation finishes as per module guidance.

**Comment by ersoftwaregmbh** [comment]
> You can try to upgrade languages, theme and modules through BO and then delete cache folders, those are the steps you're missing, also the tabs reorder but it's not critical.
> 
> And if everything works it's required you to change PS_DB_VERSION in ps_configuration table to 8.1.4.
> 
> But I'd try to solve that package issue so installation finishes as per module guidance.

Ok i will try that. Can you imagine that any kind of security mechanism blocks the http download of the language pack? I have apache nginx, Plesk installed, on Debian 12.

**Comment by ersoftwaregmbh** [comment]
> You can try to upgrade languages, theme and modules through BO and then delete cache folders, those are the steps you're missing, also the tabs reorder but it's not critical.
> 
> And if everything works it's required you to change PS_DB_VERSION in ps_configuration table to 8.1.4.
> 
> But I'd try to solve that package issue so installation finishes as per module guidance.

PrestaShop is updated to 8.1.4 now. But:

I did as suggested, and skipped the language pack installation. Switched to default theme, all overrides are deactivated. All modules uninstalled. Did not try to add the language pack (DE) manually. 

When i try to access the Module Manager page, it says:

<img width="1141" alt="Bildschirmfoto 2024-03-21 um 11 18 18" src="https://github.com/PrestaShop/PrestaShop/assets/69257372/2533e092-db57-4761-ba50-2fbfec153c22">


Should i completely replace the /vendors folder, to get rid of the old Symfony version? What does "Symfony" do anyway?

**Comment by ChillCode** [comment]
As you can read you have customfields module overriding PaymentModule.php and looks that is not compatible with PS 8.1, disabling overrides from BO should solve that issue then try to upgrade the module or you can also hire someone at [prestashop](https://www.prestashop-project.org/support/) that will solve these issues in a matter of minutes.

**Comment by ersoftwaregmbh** [comment]
> As you can read you have customfields module overriding PaymentModule.php and looks that is not compatible with PS 8.1, disabling overrides from BO should solve that issue then try to upgrade the module or you can also hire someone at [prestashop](https://www.prestashop-project.org/support/) that will solve these issues in a matter of minutes.

I don't think so. All overrides ARE DEACTIVATED. How could this be possible then?


<img width="939" alt="Bildschirmfoto 2024-03-21 um 11 37 03" src="https://github.com/PrestaShop/PrestaShop/assets/69257372/f2e374af-dec8-4a38-beaf-f7144c6475b8">
<img width="1095" alt="Bildschirmfoto 2024-03-21 um 11 35 40" src="https://github.com/PrestaShop/PrestaShop/assets/69257372/18b6b313-2835-4154-bb35-68602a2fab68">

And i also uninstalled ALL modules before updating.

**Comment by ChillCode** [comment]
Well, in your capture we can clearly see it loads the file from overrides folder, so try to mv override/classes/PaymentModule.php and see what happens.

**Comment by ersoftwaregmbh** [comment]
> Well, in your capture we can clearly see it loads the file from overrides folder, so try to mv override/classes/PaymentModule.php and see what happens.

Thanks, that worked, the error is gone! I just renamed the file to .old.

So - last problem i have - when i click the Articles (Products) page, i get a 500 error and no specific error message. Debug mode is enabled but does not throw any error message. How can i debug this error, where are the logs to check this?

<img width="799" alt="Bildschirmfoto 2024-03-21 um 13 47 10" src="https://github.com/PrestaShop/PrestaShop/assets/69257372/a6f81a38-873d-4f9f-b288-62a0adbf5e4e">

**Comment by Hlavtox** [comment]
Guys please don't pollute this thread with not related issues in the upgrade... It's making it very hard to read and follow.

The issue is `Transliterator` not found, nothing else. :-)

**Comment by gericfo** [comment]
Hello @ersoftwaregmbh 
Are you still having problems with the product page? 
If so, can you declare a new issue? (the initial problem having been resolved)
Thank you very much!

**Comment by ChillCode** [comment]
Hi @gericfo @Hlavtox 

This issue is embarrassing, since those errors came from not having php-curl, php-intl and php-gd installed.

To manage transliterations Transliterator class from php-intl is required.
To download language pack php-curl is required.
To resize images php-gd is required.

I saw some users just upgrading php on their Plesk but not activating the required extensions.

Hope this clarifies these issues.

**Comment by Quetzacoalt91** [comment]
For people visiting the configuration page, the autoupgrade module is able to check these extensions and warn in they are not enabled.

![image](https://github.com/PrestaShop/PrestaShop/assets/6768917/54c81a22-0bfc-4af0-9518-68e06fe4fb7c)

At the moment the upgrade via CLI can start wathever the status of these requirements as it is not checked on this mode. It should change with https://github.com/PrestaShop/PrestaShop/issues/35084
