### ISSUE TITLE
TaxRulesGroupCore::getIdByName() can return an invalid result

### ISSUE THREAD

**Issue by paulc010** [PrestaShop/PrestaShop#35641]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The function TaxRulesGroupCore::getIdByName() is used (at least) in localization to return the id associated with a Tax Rule (Group), however it doesn't take account of disabled or deleted entries and instead returns the first (LIMIT 1) result. This means that the function can return an invalid id, most likely in older stores that have had successive upgrades. While its use in localization perhaps has little to no overall effect on a store, the use of this function by any community-generated content could cause incorrect behaviour in the front office.

A select query on the relevant table (found in the wild and used by an active store) including all rows which match the tax rule group name (only one - with the id 19 - is active and therefor valid).
![database-query-name](https://github.com/PrestaShop/PrestaShop/assets/1579146/5ebce66e-057f-4113-886e-b7fbe8112ef0)

The result of simulating the sql used by the function. It returns the id 1 (and not 19 as would be expected). This record is marked active but deleted.
![function-sql-simulated](https://github.com/PrestaShop/PrestaShop/assets/1579146/2bc3a638-94b3-4085-ace9-07b1c33719eb)

It could, of course, be any of the records in that list that is active and not deleted that is the value which *should* be returned not just the highest id as in this case. The back office user interface will not display deleted records, so the issue may even be completely transparent to the user if the duplicates have been deleted. It should also be noted that it is possible even in 8.1.4 to add multiple entries to this table via the back office all with the same name and all enabled (which, in itself, is a quality/usability issue).

### Expected behavior

It is expected that this function returns a valid id of an active and enabled tax rules group. Either the name should be enforced as unique (likely a BC) or at the very least the enable/disable and deleted properties should be taken into account in the underlying sql.

### Steps to reproduce

1. Add several tax rules groups with the same name as the existing one
2. Delete and/or disable one or more of the "duplicate" tax rules groups
3. The function will return only the id of the first matching record.

### PrestaShop version(s) where the bug happened

All

### PHP version(s) where the bug happened

All

**Comment by Hlavtox** [comment]
Hey @paulc010, I see that the method is used only in LocalizationPack class to check if given tax rule exists or not, so it should be fairly safe fix.

Although, I don't think it's really a bug, we don't know what was the original meaning of what that method should do. But, I agree it makes sense to improve this behavior. 👍

I think the best way to fix it would be just to add `ORDER BY active DESC, deleted ASC` to the query, so it returns the active record first. ;-)

Can you make a PR for this?
