### ISSUE TITLE
Problem with changing php version to 8

### ISSUE THREAD

**Issue by embeembe** [PrestaShop/PrestaShop#35659]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,

I am using PRESTASHOP version 8.0.4, hosted on an OVH server with PHP version 7.4. I wanted to change the PHP version to 8, but unfortunately, I am having trouble with this. If I change the PHP version to any above 8 (8.0, 8.1, 8.2, 8.3), the website stops working. Instead of the page loading, strange characters appear. I have attached a screenshot. If I revert to version 7.4, the website starts working normally again. Please help.

### Expected behavior

Changing the server version to PHP 8

### Steps to reproduce

1. Log in to my OVH account.
2. In the server configuration, in the PHP version window, click "Change configuration."
3. Select PHP version: 8.0, stable64.
4. Confirm the configuration change.
5. After receiving confirmation of the PHP version change, go to the website.
6. Instead of the website, strange characters appear.

![meblinophp8](https://github.com/PrestaShop/PrestaShop/assets/156842422/61daecd4-0043-4aa5-9066-050e94f9cd17)

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

7.4

### Your company or customer's name goes here (if applicable).

meblino.nl

**Comment by paulnoelcholot** [comment]
Hello @embeembe,

Can you clear your cache and try again please?

Thanks!

**Comment by embeembe** [comment]
> Hello @embeembe,
> 
> Can you clear your cache and try again please?
> 
> Thanks!

Unfortunately, the admin panel looks the same. Is it enough to delete the contents of the cache folder on the server?

**Comment by matks** [comment]
@embeembe Changing the version of PHP might require to also change the webserver configuration

I think your problem has nothing to do with PrestaShop. It seems when you change your PHP version, something is off and does not work correctly, and I guess it's related to your webserver (apache?) config

You need to ask your hosting provider

**Comment by florine2623** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
