### ISSUE TITLE
Module ps_emailalerts - problem with product attribute

### ISSUE THREAD

**Issue by blim-pl** [PrestaShop/PrestaShop#35663]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Signing up for notification of product availability does not transfer the selected size.
Product attribute id is undefined because backward compatibility should set "productAttributeId" instead of "productIdAttribute".

HTML
`<input class="input-radio" type="radio" data-product-attribute="7" name="group[7]" value="152" checked="checked">`

POST request
`id_product=1644&id_product_attribute=undefined&customer_email=example@go2.pl`

JS:
https://github.com/PrestaShop/ps_emailalerts/blob/v3.0.0/js/mailalerts.js#L25
`function  addNotification(productId, productAttributeId) {
  // to keep backward compatibility
  if (typeof productId === 'undefined') {
    var ids = $('div.js-mailalert > input[type=hidden]');
    productId = ids.eq(0).val();
    productIdAttribute = ids.eq(1).val();
  }`

### Expected behavior

Backward compatibility should set variable "productAttributeId" instead of "productIdAttribute".

POST request:
`id_product=1644&id_product_attribute=7&customer_email=example@go2.pl`

JS:
https://github.com/PrestaShop/ps_emailalerts/blob/v3.0.0/js/mailalerts.js#L25
`function  addNotification(productId, productAttributeId) {
  // to keep backward compatibility
  if (typeof productId === 'undefined') {
    var ids = $('div.js-mailalert > input[type=hidden]');
    productId = ids.eq(0).val();
    productAttributeId = ids.eq(1).val();
  }`

### Steps to reproduce

1. Find product with soldout size
2. Sign for stock notificiation
3. Sent POST request has id_product_attribute with "undefined" value

### PrestaShop version(s) where the bug happened

1.7.6.7

### If your bug is related to a module, specify its name and its version

ps_emailalerts

### Your company or customer's name goes here (if applicable).

Blim

**Comment by florine2623** [comment]
Hello @blim-pl ,

Could you send the body of your POST request ?

Waiting fro your feedback
Thanks!

**Comment by blim-pl** [comment]
> Hello @blim-pl ,
> 
> Could you send the body of your POST request ?
> 
> Waiting fro your feedback Thanks!

Current POST request:
`id_product=1644&id_product_attribute=undefined&customer_email=example@go2.pl`

![screen-post](https://github.com/PrestaShop/PrestaShop/assets/5311409/551cabb5-b149-46e9-bff5-f53b4fe1e84d)

**Comment by florine2623** [comment]
A POST request should allow you to add data, so you can choose what is the product attribute. You need to put something else that "undefined"

In my case if I add my email to a specific combination, when the combination is on stock again, I received the email with the correct combination. 

<img width="563" alt="Screenshot 2024-03-21 at 16 28 48" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/cc139789-60f2-479c-8d1d-1bdde551e79e">

**Comment by blim-pl** [comment]
Line 25: https://github.com/PrestaShop/ps_emailalerts/blob/v3.0.0/js/mailalerts.js#L25

Problem is in this place "to keep backward compatibility"

![Firefox_Screenshot](https://github.com/PrestaShop/PrestaShop/assets/5311409/e4da86ce-ccaa-468b-9eaa-99b976df5a32)

**Comment by florine2623** [comment]
How can I reproduce the issue ?

With the steps you shared, I actually cannot.

**Comment by blim-pl** [comment]
Did you open url to file on github already sent?
Can you see screenshot with code and a big red arrow?

I don't know where it is in default design. I'm not using default theme. I've got some custom modifications and when I want to use "BACKWORD COMPATIBILITY" of this module it's not working becouse there is wrong variable name. 

If you really don't see this bug in code please close this issue.
