### ISSUE TITLE
Faceted Search price filter not based on action prices

### ISSUE THREAD

**Issue by venditdevs** [PrestaShop/PrestaShop#35679]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The Faceted Search module filters the price based on the base sales price instead of the action (specific) price.

So for example, if you sell a bike for 1899 with a discount of 400, so the actual price will be 1499, the Faceted Search won't show this product in the list when you set the maximum price on, for example, 1600.

### Expected behavior

The Faceted Search should have the abillity to filter the list based on the action price of the product.

### Steps to reproduce

Don't need reproduction steps, it's quite clear.

### PrestaShop version(s) where the bug happened

8.1.4

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_facetedsearch 3.15.1

**Comment by paulnoelcholot** [comment]
Hello @venditdevs,

I tried to reproduce your issue, but as you can see, I can't : 
![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/f7184f0c-0711-46cf-9b3f-8c31c76d0d3e)

Did I miss something?

Thanks!

**Comment by Roxayl** [comment]
Hello @venditdevs,

Could you try to disable the module's cache system via the Faceted search configuration page, and see if that fixes the issue? If that is the case, you might try to reinstall the module (in case some hooks didn't get to install successfully), or call one of the CRON task URLs from the module configuration page to make sure all indexed prices are up to date.

**Comment by florine2623** [comment]
Hello @venditdevs ,

I can't reproduce your issue with your config for the product.

https://github.com/PrestaShop/PrestaShop/assets/16019289/30ab642f-1d8e-46da-9f91-0d3b52b39a17

Make sure you have stock for that product.

I'm closing your issue as it cannot be reproduced.
Thanks!

**Comment by venditdevs** [comment]
> Hello @venditdevs ,
> 
> I can't reproduce your issue with your config for the product.
> 
>  Screen.Recording.2024-03-21.at.15.03.12.mov 
> Make sure you have stock for that product.
> 
> I'm closing your issue as it cannot be reproduced. Thanks!

Hello Florine,

We are currently checking in the code if there's maybe a compatibillity error with the theme or something else.

For now we know that the amazzing filter module works fine, so there is something not working i.c.m. the Faceted Search module. 

So do not close this issue yet.

**Comment by webtimeorologi** [comment]
We have this problem on our website www.webtimeorologi.it. If we try to select 2 filters at the same time the module deletes the first one. For example, if we go to JEWELRY - MORELLATO and select BRACELET and then want to add MAN, the module deletes the first BRACELET selection 

Prestashop Version 8.0.4
PHP Version: 7.4.33

<img width="1385" alt="Screenshot 2024-05-13 alle 13 03 58" src="https://github.com/PrestaShop/PrestaShop/assets/169664501/5a607ecd-ed4d-48f8-8915-a97eae64d586">
<img width="1462" alt="Screenshot 2024-05-13 alle 13 04 08" src="https://github.com/PrestaShop/PrestaShop/assets/169664501/eefc44b8-273e-490a-a735-bcedb8a826f6">
