### ISSUE TITLE
Total label in cart always displayed including tax even when the total is not including tax

### ISSUE THREAD

**Issue by jokn74** [PrestaShop/PrestaShop#35688]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the cart the label for the total always includes tax even if the price is shown without tax. The Tax is depending on the destination country. 
![tax in cart error](https://github.com/PrestaShop/PrestaShop/assets/122433444/2d849d0b-7f7b-4d1e-be84-8eaec462040a)

### Expected behavior

The label for the total should be without tax when the prices is without tax

### Steps to reproduce

Put something in the cart
Add a address with a destination without Tax
Check the prices are without tax

### PrestaShop version(s) where the bug happened

8.1.4

### PHP version(s) where the bug happened

8.2.14

### If your bug is related to a module, specify its name and its version

everything is latest version

### Your company or customer's name goes here (if applicable).

KOK MC ApS

**Comment by AureRita** [comment]
Hi @jokn74 

Thank you for your report, Despite my effort, I can't reproduce your issue as you can see : 

![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/3ac89728-326a-4038-bff5-7dd65793e01c)

[recording(148).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/ee97aace-623b-4043-a654-071471d7df46)

Did I miss something ? 

FYI : I tested it on 8.1.x 

Waiting for your feedback

**Comment by jokn74** [comment]
Hi

You did not miss anything 😊

I missed the fact that every country should be set up to include or not include the string with/without tax in the country manager. I tought that this would be picked automatically. So now i can correct this myself.

But it would be a nice addition to Prestashop if it was 100% automatic. 

I think that this issue should be closed.

Best regards
Jeppe
