### ISSUE TITLE
Venipak Carrier shows all payment methods

### ISSUE THREAD

**Issue by tautuxs** [PrestaShop/PrestaShop#35683]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When selected Venipak courier, it shows all the payment methods: Pay when picked up in store, Bank transfer, Paysera payment.
The Venipak Pickup point courier works normally, shows Bank transfer and Paysera payment.
For some reason it only affects Pickup Point courier.

Venipak courier payment methods:
![image](https://github.com/PrestaShop/PrestaShop/assets/77743151/7a866809-1f91-40b1-bcd4-f47652ccf4a6)

Venipak pickup point payment methods:
![image](https://github.com/PrestaShop/PrestaShop/assets/77743151/22929b3e-ad40-44f2-b0ff-d8be19eaf47b)

### Expected behavior

It should only show Bank transfer and Paysera payment methods like the Venipak Pickup Point courier.

### Steps to reproduce

1. Select desired products
2. Go to shopping cart to pay for them
3. Select Venipak courier
4. See all 3 Payment methods

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

8.0.28

### If your bug is related to a module, specify its name and its version

venipakcarrier v1.0.3

**Comment by tautuxs** [comment]
Found a fix.
You need to go to Payment -> Settings. Scroll down till you see Courier Restrictions and remove a ✓ on the desired courier on that column where it says: Pickup in store.

**Comment by AureRita** [comment]
Hi @Tautvydas3 

Thank you for your report, Currently, we don't support module/carrier that are not native module from prestashop (like Venipak courrier) but we are pleased to know that you fix your issue. 

We will close this issue because we don't support this type of issue 

Thank you !
