### ISSUE TITLE
Translation for child theme does not work

### ISSUE THREAD

**Issue by venditdevs** [PrestaShop/PrestaShop#35693]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The problem as noteed before seems to be back in Prestashop 8.1.5. Not sure if it is the same problem or a new created problem.,

https://github.com/PrestaShop/PrestaShop/issues/30716

We've updated 5 stores to 8.1.5 this morning and all of them have this translation problem again. The translations are correct in the backoffice, but not in the frontoffice (Warehouse theme).

![image](https://github.com/PrestaShop/PrestaShop/assets/14218917/f7b03352-96bd-44d8-90c3-c0d54f09a38f)

![image](https://github.com/PrestaShop/PrestaShop/assets/14218917/4a729554-aefa-46dc-8069-a2f0ed90f6bb)

![image](https://github.com/PrestaShop/PrestaShop/assets/14218917/02a9e334-afe8-404c-9f1c-263898fa5b05)

![image](https://github.com/PrestaShop/PrestaShop/assets/14218917/6aaeb692-02e4-4fb8-9b21-50184458d1df)

### Expected behavior

The right translations should be visible.

### Steps to reproduce

Install a non classic theme, preferred Warehouse and translate "View" of "Follow us" and you;ll see that the translations are not working.

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.1 and 7.4

**Comment by AureRita** [comment]
Hi @venditdevs 

Thank you for your report, Despite my effort, I can't reproduce your issue as you can see : 

[recording(146).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/f5177fa6-2b15-4d39-89cb-afdf25a6bb55)

Did I miss something ? 

It's maybe something about your theme directly ? 

Did you have other information to provide us to maybe reproduce your issue ? 

Waiting for your feedback

**Comment by venditdevs** [comment]
> Hi @venditdevs
> 
> Thank you for your report, Despite my effort, I can't reproduce your issue as you can see :
> 
>  recording.146.webm 
> Did I miss something ?
> 
> It's maybe something about your theme directly ?
> 
> Did you have other information to provide us to maybe reproduce your issue ?
> 
> Waiting for your feedback

Considering it are the exact same broken translation fields as before i do not think it is a theme problem but again a translation issue in Prestashop itself. It was not reproducable before.

**Comment by AureRita** [comment]
Hi @venditdevs 

Currently I try it again as you see : 

[recording(157).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/2fcb5352-c537-43b0-8725-c8a85b4272d2)

If you don't provide more information we'll have to close your issue because we can't reproduce it. 

@PrestaShop/qa-functional can some one reproduce this issue ? 

Waiting for feedback

**Comment by venditdevs** [comment]
Hello @AureRita,

Are you using a child theme?

At this moment we have the idea that the problem only occurs when you upgrade from 8.1.3 or 8.1.4 to 8.1.5. This is when it happends, when we upgrade from 1.7.8.8 to 8.1.5 directly we don't encounter translation problems.

This is what we see at this moment.

**Comment by venditdevs** [comment]
@AureRita, i found something that might help, and i found a solution to fix it for the time being. Please note that the translations DID work before upgrading the shop to 8.1.5. 

As you can see the translation is present, if you click on safe it does take a long time, but eventually it's ready (i just did this on 3 shops, sorry that this was the slowest). but no changes on the frontoffice. The second time i made a little change to the translation, this can be anything from a space or some letters, and undo the changes to save the translation again. After this the translations are back. Also the translations i did not update at that moment but where present in the translations.

https://github.com/PrestaShop/PrestaShop/assets/14218917/17b2eb0a-7abf-4f4d-bfd3-cab9c13e27c0

![image](https://github.com/PrestaShop/PrestaShop/assets/14218917/9cdfb9f2-0f19-44f2-9af6-252527e338e9)

**Comment by florine2623** [comment]
Hello @venditdevs ,

I have reproduced your issue using child theme, with PrestaShop version 8.0.X, 8.1.x and develop, I'll add this to the backlog so it can be fixed.

There's no expression to translate in BO :

https://github.com/PrestaShop/PrestaShop/assets/16019289/bd29c56e-cc1f-4fae-a34e-445411b392ec

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by kpodemski** [comment]
@florine2623 

I think you haven't checked it correctly, Florine. This is not what the user reported, you did not reproduce the reported issue. You don't have translations because your child theme doesn't have any custom translatable phrases.

**Comment by AureRita** [comment]
Hi @venditdevs 

Can you tell us if you have the same issue than @florine2623 ? 

waiting for feedback

**Comment by venditdevs** [comment]
@AureRita, no it's a different problem. My problem is "explained" in the screenrecording i posted.

**Comment by florine2623** [comment]
@kpodemski ,

How can I add custom translations of my theme ?

**Comment by florine2623** [comment]
Friendly reminder @kpodemski ^^

**Comment by paulnoelcholot** [comment]
Hello @venditdevs,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Comment by venditdevs** [comment]
> u for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

@paulnoelcholot, it was not our task to respond, i have given an awnser with an example. It was an ongiong discussion between @florine2623 and @kpodemski.

I don't care that you close it, we know how to solve the problem for our shops, It's up to you guys if your willing to let a bug stay (and maybe grow into a bigger problem) in Prestashop or not.

**Comment by kpodemski** [comment]
Hello @venditdevs 

If you know how to solve the problem, it would be worth sharing it with others, and maybe even contributing back, so you don't need to worry about it in the future versions :)

**Comment by venditdevs** [comment]
Hello @kpodemski, it's a workaround solution by just changing a translation and save it again, like in the video in this reaction (https://github.com/PrestaShop/PrestaShop/issues/35693#issuecomment-2019329851). So it is not a code fix, there a more than one problem with the translations inside Prestashop, probably more than one are linked to the same bug/source (PHP 8.1 non-native module translations for example), or our first issue about the translations was closed by @florine2623 because is was not reproducable so it was not a PS problem.. well.. it turns out it was not.(https://github.com/PrestaShop/PrestaShop/issues/35693#issuecomment-2019329851)

I really wonder how they can't reproduce the most of those (translation) problems while a lot of people in the community encounter them. So there must be something wrong right? And if someone reports a problem linked to let's say a child theme, then try to reproduce it with an actual child theme.
