### ISSUE TITLE
ps_imageslider - Can't add/edit image in slider anymore

### ISSUE THREAD

**Issue by xDaniBix** [PrestaShop/PrestaShop#35704]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

PrestaShop Image Slider module is not working properly. When you try to delete the default images, the module displays a message that the photo has been successfully deleted, but the photo is not deleted. The same when it comes to uploading your own photos. Additionally, the slider does not appear on the store's website, it looks as if it was uninstalled.

https://github.com/PrestaShop/PrestaShop/assets/16019289/f9db16ac-f508-4df5-9e87-48e0b7b0db20

Doesn't work on 8.0.x and 8.1.x, on develop it works fine.

### Expected behavior

Add my own photo that shows on my shop.

### Steps to reproduce

1. Go to Image slider 
2. Tap Configure 
3. Ad Your own photo 
4. The photo doesn't appear on the shop

### PrestaShop version(s) where the bug happened

8.0.x, 8.1.x

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_imageslider v3.1.4

**Comment by kpodemski** [comment]
@PrestaShop/qa-functional @florine2623 I cannot reproduce any of the mentioned issues

**Comment by amine-O** [comment]
Blocked : waiting for QA confirmation

**Comment by florine2623** [comment]
Hello @kpodemski and @amine-O ,

I can reproduce the issue using PS 8.1.6 and image_slider v3.1.4, PHP 8.1.13.


https://github.com/PrestaShop/PrestaShop/assets/16019289/d754a00a-7da3-40fe-a2b1-e4b4f844ba09

**Comment by kpodemski** [comment]
@florine2623 I can confirm, it works for multistore, it doesn't work for a single store.

**Comment by kpodemski** [comment]
@florine2623 the problem is because you added an image to the language which is different from your default language in back office, if you add an image for all languages, it works well

**Comment by kpodemski** [comment]
Potential fix here https://github.com/PrestaShop/ps_imageslider/pull/104
