### ISSUE TITLE
ps_emailalerts module: text email templates render HTML

### ISSUE THREAD

**Issue by Caleydon** [PrestaShop/PrestaShop#35702]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, 

module ps_emailalerts generate TXT email templates with HTML code.

### Steps to reproduce

1. install and setup ps_emailalerts module
2. set text email notifications only in the Emails part of PS BO
3. make an order
4. check received email about a new order
5. notification email about a new order included HTML code - see following screenshot

![ps_emailalerts-text-emails](https://github.com/PrestaShop/PrestaShop/assets/2806752/c543a120-29c6-4db9-a872-00b098339dbb)

### PrestaShop version(s) where the bug happened

8.1.4

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_emailalerts 3.0.0

**Comment by florine2623** [comment]
Hello @Caleydon ,

I can't reproduce your issue.

The email is well displayed :
<img width="554" alt="Screenshot 2024-03-21 at 14 08 36" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/9a067b1c-415a-40dd-b045-f0e56f67f80b">

Your issue must come from your email server and not PS itself.

I'm closing the issue as I can't reproduce it.
Thanks

**Comment by Caleydon** [comment]
Please, I am talking about TXT version of email templates. You posted screenshot of HTML template. Affected is text version, not HTML!

**Comment by Caleydon** [comment]
Please folow reproduction steps I provide. You skipped most important step #2.

**Comment by Caleydon** [comment]
![email-settings](https://github.com/PrestaShop/PrestaShop/assets/2806752/a95ec7bb-f839-46d2-aae8-24ef533cc872)

**Comment by Caleydon** [comment]
Could you please open the report? The issue has not been completed or resolved. If you can't reproduce the issue, it doesn't mean there is no bug; please don't close the report immediately.
