### ISSUE TITLE
Spams on my contact form

### ISSUE THREAD

**Issue by Maitarmoir** [PrestaShop/PrestaShop#35714]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi ! We receive hundreds of email from or contact form daily from strangers. This seems to be a way to scam us. We receive as much as 10 mails from the same adress per day in every language possible. We don't know how to block these spams without enabling our contact form. Here's one example.
<img width="657" alt="Capture d’écran 2024-03-21 à 12 55 42" src="https://github.com/PrestaShop/PrestaShop/assets/164348485/cf88a9f1-e299-4d33-9406-278463270d76">

### Expected behavior

We want to stop these spams and block these false adress without enabling our contact form

### Steps to reproduce

It's an issue with our contact form, I don't know how to reproduce it by myself.

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

?

### If your bug is related to a module, specify its name and its version

Formulaire de contact v4.3.0

### Your company or customer's name goes here (if applicable).

Mait Armoir

**Comment by matks** [comment]
@Maitarmoir Consider adding a [CAPTCHA module](https://build.prestashop-project.org/news/2019/fighting-against-spamming-again/)

**Comment by florine2623** [comment]
Hello @Maitarmoir ,

I suggest you read this thread : 
https://github.com/PrestaShop/PrestaShop/discussions/34417

This is not a PS issue.

I'm closing your issue.
