### ISSUE TITLE
Cannot save cart rules on some stores

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#35717]
### Describe the bug and add attachments

Some of cart rules created on previous versions of PrestaShop cannot be saved.

### Expected behavior

I should be able to save all cart rules properly.

### Steps to reproduce

1. I click on edit cart rule. Edit page opens.
2. The URL is `/admin/index.php?controller=AdminCartRules&updatecart_rule=&id_cart_rule=70&token=xxx`
3. I change name. Click Save.
4. I get redirected to `/admin258ytdyrs/index.php?controller=AdminCartRules&token=xxx&addcart_rule` and nothing was saved.
5. I click save, page just refreshes. Nothing, no error, no message.
6. When I go back, the cart rule is still original.

### PrestaShop version(s) where the bug happened

8.1.5, did not happen on 1.7.6.9

**Comment by florine2623** [comment]
Hello @Hlavtox ,

I can't reproduce your issue with the latest zip available.

https://github.com/PrestaShop/PrestaShop/assets/16019289/48dcae80-af9f-4616-80db-234168e339d7

Did you do an upgrade, if yes from which version to 8.1.5 ?

**Comment by Hlavtox** [comment]
@florine2623 Hi, I upgraded from 1.7.6.9.

There doesn't seem to be any difference, between them, but ID 61 just can't be saved and ID 69 can. The only difference is in gift product, but even if I change it, no change.

![Snímek obrazovky 2024-03-21 172945](https://github.com/PrestaShop/PrestaShop/assets/6097524/d91de572-84bd-4243-9961-9203432f167d)
![Snímek obrazovky 2024-03-21 172954](https://github.com/PrestaShop/PrestaShop/assets/6097524/af4543b5-8951-4d02-a984-f0a43988ca30)
![Snímek obrazovky 2024-03-21 173005](https://github.com/PrestaShop/PrestaShop/assets/6097524/765a58a4-544c-4f2b-97ca-b33819d97629)
![Snímek obrazovky 2024-03-21 173013](https://github.com/PrestaShop/PrestaShop/assets/6097524/9920a739-2050-47dd-aca4-9d83b271339b)
![Snímek obrazovky 2024-03-21 173020](https://github.com/PrestaShop/PrestaShop/assets/6097524/bee8a438-0535-4d57-82fc-bd4d3546b2c4)
![Snímek obrazovky 2024-03-21 173047](https://github.com/PrestaShop/PrestaShop/assets/6097524/6c2cccec-722f-43b1-85cb-57c0d37f07f9)
![2](https://github.com/PrestaShop/PrestaShop/assets/6097524/ebb10340-b429-4804-a105-a28ebb8396bd)

**Comment by florine2623** [comment]
I upgraded from 1.7.6.9 to 8.1.5 with some cart rules with discount amount/percentage and free gift.
<img width="1438" alt="Screenshot 2024-03-21 at 17 48 55" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/f00191a7-dc92-479b-9213-4cd193c2f063">


Here's the result after the upgrade :

https://github.com/PrestaShop/PrestaShop/assets/16019289/620c2ea7-27d9-458d-9b06-a9ee9d63ea2a

I can't reproduce your issue. I edited all my cart rules, I didn't have any issues.
I edited the name, the condition and the action.

**Comment by Hlavtox** [comment]
It has something to do with products, but I can't figure what.

There are 4022 products on the cart rule.
![amount](https://github.com/PrestaShop/PrestaShop/assets/6097524/829f69ab-c3d4-4a73-bab4-948254d90e94)

All of the products in the rule set exists.
![verification](https://github.com/PrestaShop/PrestaShop/assets/6097524/f9cfcef9-29a2-4d71-98eb-ed806bd24ce3)

But I just can't save it...

When I delete all but 1 product from the rule set, I can suddenly save it just fine. 🤷‍♂️ 

![Snímek obrazovky 2024-03-21 180324](https://github.com/PrestaShop/PrestaShop/assets/6097524/4d7adc59-36ca-498e-9ff8-8905f13cc52f)

**Comment by Hlavtox** [comment]
Sorry for wasting your time @florine2623, the issue was caused by low max input vars. 🤦

**Comment by AureRita** [comment]
Hi @Hlavtox 

Can we put this issue on invalid so ? Because it's set with your environment or do we change it on Prestashop ? 

Waiting for your feeback

**Comment by florine2623** [comment]
@Hlavtox , no worries ! I'm closing your issue then :)
