### ISSUE TITLE
Adding new image slide in "Image slider" module (ps_imageslider) does not work

### ISSUE THREAD

**Issue by Codencode** [PrestaShop/PrestaShop#35713]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When trying to add a new slide in the ps_imageslider module, file selection doesn't work.
This problem occurs up to version 1.7.6.9 of Prestashop, in subsequent versions it does not occur, however the javascript error which is the cause of the problem is still there.

I attach a video.

The problem occurs because the `headerHTML` method of the form does not include the action of adding a new slide.

https://github.com/PrestaShop/PrestaShop/assets/2463965/19908f45-5383-45aa-9f92-caba57f11f59

### Steps to reproduce

1. go to the ps_imageslider module
2. click on Add new slider
3. click on "Select a file"
4. The file selection popup is not shown

### PrestaShop version(s) where the bug happened

<= 1.7.6.9

### PHP version(s) where the bug happened

all

### If your bug is related to a module, specify its name and its version

ps_imageslider 

### Your company or customer's name goes here (if applicable).

Codencode

**Comment by florine2623** [comment]
Hello @Codencode ,

I can't reproduce your issue with Image Slider v3.1.4.

https://github.com/PrestaShop/PrestaShop/assets/16019289/791a836d-b8c4-441b-b293-46d46668901d

What version are you using ?

**Comment by Codencode** [comment]
Hi @florine2623,
the problem occurs up to version 1.7.6.9 of Prestashop, I tried both version 3.1.3 and version 3.1.4 of the module.
In subsequent versions you are able to select the file correctly, but if you view the javascript console you will see the following error:
```Uncaught Sortable: `el` must be an HTMLElement, not [object Undefined]```

**Comment by florine2623** [comment]
I tested with 1.7.6.9 and image slider module v3.1.0 and v3.1.4. 
It works as expected :

https://github.com/PrestaShop/PrestaShop/assets/16019289/26ec0042-1bac-4165-b5f1-0628ab936f0d

**Comment by SharakPL** [comment]
@florine2623 I can confirm the bug is there and provided fix is valid. Sortable plugin is supposed to be attached only on the main configuration page to allow changing the order of slides. It's not supposed to load on "Edit slide" page and this is covered by https://github.com/PrestaShop/ps_imageslider/blob/6baeac7dcd9f08af334e5d3451cfbc3a1f4509ad/ps_imageslider.php#L618 but should also be avoided on "Add new slide" page - this is missing so you get error triggered in the browser console:

> Uncaught Sortable: `el` must be an HTMLElement, not [object Undefined]

**Comment by florine2623** [comment]
@PrestaShop/qa-functional 
Please can someone test this issue ? ^^

**Comment by SharakPL** [comment]
Btw you don't need to select any file to see the bug in the console, just open "Add new slide" page 😉

**Comment by florine2623** [comment]
Oh yes, indeed, I have the issue in the console :

<img width="1435" alt="Screenshot 2024-03-21 at 16 11 49" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/eca422c3-185d-4c3f-a9d0-96abc8baca86">

For the PR, the test should be : No error in console and the module works as before.

Thanks @SharakPL ! 💪
