### ISSUE TITLE
file_get_contents_curl failed to download http://api.prestashop.com/xml/tab_modules_list_17.xml : (error code 7)

### ISSUE THREAD

**Issue by paulius-bulotas** [PrestaShop/PrestaShop#35724]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

(httpd apache)

In a unpredictable way, backoffice in my debug mode is not accessible when i turn off debug mode i see the modules are not grouped and the error is:
An exception has been thrown during the rendering of a template ("file_get_contents_curl failed to download http://api.prestashop.com/xml/tab_modules_list_17.xml : (error code 7) ").

i tried to delete config/xml but it doesn't generating.

![image](https://github.com/PrestaShop/PrestaShop/assets/70526727/9f2467a1-0615-44f6-bb00-7e8de9e938e2)

### Steps to reproduce

I turned debug mode.
and got random error.

### PrestaShop version(s) where the bug happened

1.7.6.5

### PHP version(s) where the bug happened

7.2.34

**Comment by matks** [comment]
@paulius-bulotas https://api.prestashop.com/xml/tab_modules_list_17.xml seems accessible :/ so I'm afraid problem might come from your env

**Comment by paulius-bulotas** [comment]
Do you have any ideas on how to resolve this issue? I've tried following solutions to similar problems, but they haven't helped me.

**Comment by paulius-bulotas** [comment]
Backoffice when debug mode is off.
![image](https://github.com/PrestaShop/PrestaShop/assets/70526727/b116d175-f6b8-4cbb-96b7-45d4639b630e)
![image](https://github.com/PrestaShop/PrestaShop/assets/70526727/eaf93b2e-7b5b-4766-afa6-c0a2cc842eb7)

**Comment by paulius-bulotas** [comment]
> @paulius-bulotas https://api.prestashop.com/xml/tab_modules_list_17.xml seems accessible :/ so I'm afraid problem might come from your env

By the way, I believe it's causing all payment problems, such as: Exception on hook paymentOptions for module. Warning: fsockopen(): unable to connect to ssl://www.paysera.com:443 (Permission denied).

**Comment by paulius-bulotas** [comment]
I apologize for doubting you. You were correct; the issue indeed stemmed from my env.

finally find out the how to solve that:
setsebool -P httpd_can_network_connect on

**Comment by matks** [comment]
I'm simply happy it now works for you 😊

**Comment by paulius-bulotas** [comment]
Thank you.
