### ISSUE TITLE
Autoupgrade - We don't have the autoupgrade on the side bar for the v9 

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#35726]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you install autoupgrade on Prestashop V9. You don't have the fast link of autoupgrade on the side bar as you can see : 
![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/81b8351c-a1cb-4991-9cf1-4393e44ed486)

### Expected behavior

I wish I could have my fast link on the side bar, like this : 
![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/50a0d1dd-7982-40e8-b572-492cb1af1cbe)

### Steps to reproduce

1. Go to BO 
2. Go to Module Manager
3. Install Autoupgrade
4. Clic on Configure 
5. Autoupgrade is not on side bar :negative_squared_cross_mark: 

### PrestaShop version(s) where the bug happened

develop 

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

autoupgrade v5.0.1

### Your company or customer's name goes here (if applicable).

PS

**Comment by florine2623** [comment]
Hello @AureRita ,

I have reproduced your issue on develop. I can't even hook the module on the left menu.

https://github.com/PrestaShop/PrestaShop/assets/16019289/e8403553-5b91-40bb-8f5b-0bf36f820a19

Thanks!
