### ISSUE TITLE
Autoupgrade - Don't have the experimental feature on autoupgrade

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#35727]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I do an upgrade 8.0.5 from to 8.1.5, I don't have the experimental feature as we have with a fresh version of 8.1.5 as you can see : 

[recording(150).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/1dcfae17-ce55-42b3-91bc-95db241ddfae)

### Expected behavior

I wish I could Find all the experimental feature as you can see here : 
![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/17c72644-172d-44f0-a2a9-0434cd283ace)

### Steps to reproduce

1. Go to BO 
2. Go to module manager
3. install Autoupgrade
4. Do an upgrade on 8.1.5 from major release 
5. Go to Bo > Advanced Parameters > Experimental Feature 

### PrestaShop version(s) where the bug happened

8.0.5

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

autoupgrade v5.0.1

### Your company or customer's name goes here (if applicable).

PS

**Comment by florine2623** [comment]
Hello @AureRita ,

I have reproduced your issue upgrading from 8.0.5 to 8.1.5.

https://github.com/PrestaShop/PrestaShop/assets/16019289/9dd0c3f3-3525-4bfd-a37e-d5c0c0445d12

Thanks !

**Comment by MatShir** [comment]
Nice catch ! I Since there are experimental feature, it doesn't affect the prod or merchant business. In that case, I will lower the severity.
