### ISSUE TITLE
Be able to filter products when you are reordering the products

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/PrestaShop#35730]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

You cannot filter products when you are reordering the products. It is something that should be able to be done since you may only be interested in reordering the products that are active
[https://www.awesomescreenshot.com/video/26109913?key=3821cd5a704cdf222aa7cf7f34a753ac](https://www.awesomescreenshot.com/video/26109913?key=3821cd5a704cdf222aa7cf7f34a753ac)

### Expected behavior

Be able to reorder the products and also be able to use the filter while

### Steps to reproduce

1. Products
2. Reorder
3. Try to use filters

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

7.4.33

**Comment by AureRita** [comment]
Hi @alfonsolr09 

Thank you for your report, Despite my effort, I can't reproduce this issue as you can see : 

[recording(154).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/60600d6e-8584-49b6-9a8f-ed903534c466)

Did I miss something ? 

FYI : we have to test all new issue on the last version suported ( here 8.1.x ) so if it's not on the last one, it's maybe already corrected.

Waiting for feedback

**Comment by kpodemski** [comment]
Hello @alfonsolr09 

I'm not sure if that's a good idea, this could lead to issues with setting the actual position, also, remember that PrestaShop 1.7.8 is no longer supported with regular updates, best would be if you check this behavior on the newest PrestaShop version.

@AureRita you didn't test reordering products, you've only tested filtering

**Comment by alfonsolr09** [comment]
> Hello @alfonsolr09 
> 
> I'm not sure if that's a good idea, this could lead to issues with setting the actual position, also, remember that PrestaShop 1.7.8 is no longer supported with regular updates, best would be if you check this behavior on the newest PrestaShop version.
> 
> @AureRita you didn't test reordering products, you've only tested filtering

Could you check if it is feasible to improve that point?

**Comment by kpodemski** [comment]
@alfonsolr09 

how do you think that could work? you have Category A and you want to sort products there, you filter by name, you set some products to the first position, but they were with the name starting with Z, all of the previous products will stay in their places 🤔

Could you share with me any real-life example where filtering could be used first to later sort the products?

**Comment by florine2623** [comment]
friendly reminder @alfonsolr09

**Comment by alfonsolr09** [comment]
at least be able to filter by active and deactivated products, in my case I have several hundred deactivated products and to do the reordering I have to scroll down a lot

**Comment by florine2623** [comment]
It is possible to do so : 

https://github.com/PrestaShop/PrestaShop/assets/16019289/04b1fa7a-ec50-499e-a58b-8e77daaf5b8b
