### ISSUE TITLE
unable to enter image captions

### ISSUE THREAD

**Issue by ECC64** [PrestaShop/PrestaShop#35747]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After an update, 1click Upgrade, 8.1.3 to 8.1.5, we want to try the new product page in back office, and an error is displayed when i want to write the caution (legend or ALT balise).
I had to put back the old back office product page
![Capture d'écran 2024-03-26 133324](https://github.com/PrestaShop/PrestaShop/assets/61431435/72981f90-f13f-4fc8-8215-ad6779db85e1)

### Expected behavior

go to product
edit product
edit caution legend
error displayed

### Steps to reproduce

go to product
edit product
edit caution legend
error displayed

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello @ECC64 ,

Your issue is fixed by https://github.com/PrestaShop/PrestaShop/pull/35699

The fix will be available in the next patch 8.1.6.

I'm closing the issue as it is fixed.

Thanks!
