### ISSUE TITLE
Autoupgrade - When you upgrade on V9.0, you'll have a feature flag doesn't exist 

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#35748]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, when I upgrade from 8.1.5 or 8.0.5 to V9.0.0, I have an Error 500 aboput the feature flag 

![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/b16dacc1-b653-47ab-a9c2-57aa80f170c1)

### Expected behavior

I wish I could use my shop v9.0

### Steps to reproduce

1. Install a fresh install of 8.1.5 
2. Download an autoupgrade from dev version of presta
3. do an upgrade from a folder 
4. Launch the upgrade 
5. :negative_squared_cross_mark: you'll have the 500 error 

### PrestaShop version(s) where the bug happened

8.0.5 and 8.1.5 to develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

autoupgrade v5.0.1 - dev mode

### Your company or customer's name goes here (if applicable).

PS

**Comment by florine2623** [comment]
Hello @AureRita ,

Tested with an upgrade from 8.1.5 to 9.0.0 using autoupgrade v5.0.1 has an error.

With branch dev of autoupgrade, I have this error before even clicking on Configure button of the module :
<img width="1084" alt="Screenshot 2024-03-26 at 16 29 59" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/6738c051-6a8a-4c01-a071-820509f24844">

```
Attempted to load class "Translator" from namespace "PrestaShop\Module\AutoUpgrade\UpgradeTools".
Did you forget a "use" statement for e.g. "Symfony\Component\Translation\Translator", "Symfony\Component\CssSelector\XPath\Translator", "Symfony\Bundle\FrameworkBundle\Translation\Translator" or "PrestaShopBundle\Translation\Translator"?
```

I tested with the [PR 679](https://github.com/PrestaShop/autoupgrade/pull/679) of autoupgrade :

<img width="1089" alt="Screenshot 2024-03-26 at 17 23 01" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/b1e30c8d-15a7-4eab-be86-4714a700aa8e">
