### ISSUE TITLE
Problem in updating Prestashop 1.7.8.7 

### ISSUE THREAD

**Issue by federica979** [PrestaShop/PrestaShop#35744]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Dear assistance,
we faced an  issue in updating our Prestashop version from the actual 1.7.8.7 to the desired 1.7.8.11. The problem was that Prestashop couldn't complete the backup of the files and stop the update.

Here following the data that Prestashop support told us to report you: 

- Prestashop version: 1.7.8.7

- PHP version: 7.4.33

- Screenshots
![IMG-20240322-WA0003](https://github.com/PrestaShop/PrestaShop/assets/165001100/a7f2aa49-878e-4c56-be3c-53feaf96df56)
![IMG-20240322-WA0003](https://github.com/PrestaShop/PrestaShop/assets/165001100/2ba55dec-7913-45a5-a177-ca0049a56048)

- Steps to reproduce the problem: simply start the Prestashop version update

### Expected behavior

To complete the Prestashop version update.

### Steps to reproduce

1. Launch the update to version 1.7.8.11 from the right side of the dashboard.
2.  Save the update zip file in local.
3. Upload the zip file in Prestashop

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.33

### Your company or customer's name goes here (if applicable).

Saiet Telecomunicazioni

**Comment by florine2623** [comment]
Hello @federica979 ,

I suggest trying to use a back-up to redo an upgrade with the module ps_account disabled.

In my case, I updated from 1.7.8.7 to 1.7.8.11, it worked as expected.

<img width="401" alt="Screenshot 2024-03-26 at 10 10 14" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/be570f8b-1aa0-484a-b9d3-e077a016f79c">

https://github.com/PrestaShop/PrestaShop/assets/16019289/ec443e0f-3a4d-4ae9-aa90-b3ba458b4882


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by federica979** [comment]
Dear florine2623,
I will surely proceed as you suggested.
Just consider that we contected Prestashop Tech Support and they send us to github to have more specific assistance (mail in attached).

Thank you
Federica

________________________________
Da: florine2623 ***@***.***>
Inviato: martedì 26 marzo 2024 10:22
A: PrestaShop/PrestaShop ***@***.***>
Cc: federica979 ***@***.***>; Mention ***@***.***>
Oggetto: Re: [PrestaShop/PrestaShop] Problem in updating Prestashop 1.7.8.7 (Issue #35744)


Hello @federica979<https://github.com/federica979> ,

I suggest trying to use a back-up to redo an upgrade with the module ps_account disabled.

In my case, I updated from 1.7.8.7 to 1.7.8.11, it worked as expected.

Screenshot.2024-03-26.at.10.10.14.png (view on web)<https://github.com/PrestaShop/PrestaShop/assets/16019289/be570f8b-1aa0-484a-b9d3-e077a016f79c>

https://github.com/PrestaShop/PrestaShop/assets/16019289/ec443e0f-3a4d-4ae9-aa90-b3ba458b4882

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: Get help with PrestaShop<https://www.prestashop-project.org/support/>.

Alternatively, you can also ask for help in the community forums<https://www.prestashop.com/forums/> or in the public Slack channel<https://github.com/PrestaShop/open-source/tree/master/slack>.

Thank you
