### ISSUE TITLE
contactform module - Incorrect path to TPL file

### ISSUE THREAD

**Issue by Caleydon** [PrestaShop/PrestaShop#35746]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the contactform module is a path to contactform.tpl defined in incorrect way.

In the module is path defined as:
`return $this->display(__FILE__, 'views/templates/widget/contactform.tpl');`

but contactform.tpl file is in the module structure in the path:
`views/templates/hook/`

Vice versa in the theme override is contactform.tpl file present in the path:
` themes/classic/modules/contactform/views/templates/widget/`

It should be unified because when the module will be used with 3rd party theme without overrided contactform.tpl file, the module itself will wont find contactform.tpl file in the module folder.

### Steps to reproduce

1. install contactform module
2. delete /themes/classic/modules/contactform/views/templates/widget/contactform.tpl
3. Contact page will return message "No template found for module contactform"

### PrestaShop version(s) where the bug happened

8.1.4

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

contactform v4.4.2

**Comment by florine2623** [comment]
Hello @Caleydon ,

I have reproduced your issue.
<img width="1130" alt="Screenshot 2024-03-26 at 14 42 09" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/94d07313-c8ed-470c-ac62-f163bbdcb9fc">

What should be the expected behavior in that case ?
Waiting for your feedback.
Thanks!

**Comment by florine2623** [comment]
Friendly reminder @Caleydon ^^

**Comment by Caleydon** [comment]
Hello.

Just change location of the contactform.tpl file in the "contactform" module following way:

`views/templates/hook/contactform.tpl`

change to

`views/templates/widget/contactform.tpl`

Or said simple: rename "hook" folder name into "widget".

**Comment by paulnoelcholot** [comment]
@PrestaShop/product-council  What did you think about that?

**Comment by Hlavtox** [comment]
That is a question for @PrestaShop/committers

**Comment by kpodemski** [comment]
I want to confirm this issue, the module should work without files present in the /themes/classic or themes/whatever, that's the expected behavior.
