### ISSUE TITLE
Dont show Category thumbnail images in parent category if not add Category cover image

### ISSUE THREAD

**Issue by martinshalfo** [PrestaShop/PrestaShop#35767]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Don't show Category thumbnail images in parent category if not add Category cover image.
Version 8.1.4.
Dont show thumbnail images in parent category if not add cover image. only with cover image show thumbnail.

### Steps to reproduce

Don't show Category thumbnail images in parent category if not add Category cover image.
Version 8.1.4.
Dont show thumbnail images in parent category if not add cover image. only with cover image show thumbnail.

### PrestaShop version(s) where the bug happened

8.1.4

### PHP version(s) where the bug happened

PHP version: 8.2.17

**Comment by florine2623** [comment]
You issue is unclear.

You need to change your PHP version to match the system requirements : https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/

I'm closing your issue.
