### ISSUE TITLE
Not all related products are showing in product admin when searching

### ISSUE THREAD

**Issue by JoryHogeveen** [PrestaShop/PrestaShop#35778]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the product admin page not all results are displayed when searching for related products.
In many cases it only shows 1 result even though I see a whole list in the actual fetch response (ajax).

Note that I am using 1.7.8.11 for this site but there are no notable changes for this part (besides codestyle/indentation): https://github.com/PrestaShop/PrestaShop/commits/develop/admin-dev/themes/new-theme/js/product-page/product-search-autocomplete.js

### Expected behavior

Since the fetch results are correct (a full list of all possible matches) I would thing that all results should be rendered in the list.

### Steps to reproduce

1: Create many products staring with the same name (at least 30). Example: Presta Product 01, Presta Product 02, etc.
2: Create a new product and search for related products by typing "Presta".
3: Even though the fetch response will include all products, the actual HTML only renders 1 or in some cases a few.

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

N.A.

### If your bug is related to a module, specify its name and its version

N.A.

**Comment by florine2623** [comment]
Hello @JoryHogeveen ,

I have already seen this issue in the past, but I can't put my finger on it anymore.

I'm asking for @Hlavtox , @kpodemski or @MatShir 's help :p 

Thanks!

**Comment by JoryHogeveen** [comment]
Hi @florine2623 
Ah ok! I couldn't find anything related that could fix this but if there is then that is awesome, even if it would be a workaround.

**Comment by florine2623** [comment]
In my memories, it was said that it would make the whole product page too long to charge if all the products are charged in the search area.

If I'm not mistaken @jolelievre was the one who said that.

**Comment by JoryHogeveen** [comment]
Makes sense, though a scrollable container would fix that :)
However, in my case, only 1 item is shown even though the API (fetch) requests returns multiple (all matches: 20+)
It feels more like a bug than a UI related decision.

**Comment by florine2623** [comment]
@JoryHogeveen ,

Indeed, it seems that you have a problem that I can't reproduce. I have tested and in my case I have 12 products displayed.

https://github.com/PrestaShop/PrestaShop/assets/16019289/8b5c2268-f0fc-41f5-b219-de98d3ab67c5

As we use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you!
