### ISSUE TITLE
PrestaShop 8 warehouse search not working

### ISSUE THREAD

**Issue by PrestaShopLAB4IT** [PrestaShop/PrestaShop#35777]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

We noticed that searching in Warehouse no longer works well.
If I search for two separate words, it doesn't give me any results, I have to search in a single word. For example, if I have to search for this Retro Men's jacket which, as you can see from the screenshots, is present, I have to search for "retro men" all at once, and I can no longer build the search step by step, "retro" and then "man", as it could instead on 1.7.
![Screenshot 2024-03-28 092233](https://github.com/PrestaShop/PrestaShop/assets/165366974/24b96cce-1895-47ec-9857-4d4549ba3fb0)
![Screenshot 2024-03-28 092241](https://github.com/PrestaShop/PrestaShop/assets/165366974/fcb11b27-4e97-4d85-ac20-1d6d70b117f3)

### Steps to reproduce

1. Go to the Back Office
2. Click on Catalog --> Warehouse
3. Try search a product and then add another word in the search to be more specific

### PrestaShop version(s) where the bug happened

8.1.4

### PHP version(s) where the bug happened

8.1.27

**Comment by Codencode** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/35280.

The issue has been fixed in PS version 8.1.5.

Here you will find the fix https://github.com/PrestaShop/PrestaShop/pull/35384

**Comment by PrestaShopLAB4IT** [comment]
Thank you so much! I'm new here I'm still getting the hang of this.
