### ISSUE TITLE
Autoupgrade - Exception in autoupgrade for 1.7.8.11 to 9.0.0 due to ps_checkout and ps_account

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#35774]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you want to upgrade from 1.7.8.11 to 9.0.0, you'll have an issue first of all with ps_checkout as you can see : 

![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/6fbafa4a-bf66-422d-bad6-24e6eee243b1)

If you delete ps_checkout, the problem'll be about ps_account and if you delete it also, you'll have many error due to the different compatibility 

Error message : 

> "[INTERNAL] /var/www/html/pr_autoup/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php line 88 - Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "mbo.addons.user" has a dependency on a non-existent service "session". Did you mean one of these: "argument_resolver.session", "session.factory", "session.storage.factory.native", "session.handler.native", "session_listener", "prestashop.core.grid.query_builder.security.session.employee", "prestashop.core.grid.query_builder.security.session.customer", "prestashop.core.grid.data_factory.security.session.employee", "prestashop.core.grid.data_factory.security.session.customer", "prestashop.core.grid.definition.factory.security.session.employee", "prestashop.core.grid.definition.factory.security.session.customer", "prestashop.core.grid.factory.security.session.employee", "prestashop.core.grid.factory.security.session.customer", "prestashop.adapter.security.command_handler.delete_customer_session_handler", "prestashop.adapter.security.command_handler.clear_customer_session_handler", "prestashop.adapter.security.command_handler.delete_employee_session_handler", "prestashop.adapter.security.command_handler.clear_employee_session_handler", "prestashop.adapter.security.command_handler.bulk_delete_employees_sessions_handler", "prestashop.adapter.security.command_handler.bulk_delete_customers_sessions_handler", "prestashop.adapter.security.repository.customer_session_repository", "prestashop.adapter.security.repository.employee_session_repository"? #0 /var/www/html/pr_autoup/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(90): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue() #1 /var/www/html/pr_autoup/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(51): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue() #2 /var/www/html/pr_autoup/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(99): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue() #3 /var/www/html/pr_autoup/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(51): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue() #4 /var/www/html/pr_autoup/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(90): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue() #5 /var/www/html/pr_autoup/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(51): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue() #6 /var/www/html/pr_autoup/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(48): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue() #7 /var/www/html/pr_autoup/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(42): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process() #8 /var/www/html/pr_autoup/vendor/symfony/dependency-injection/Compiler/Compiler.php(80): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->process() #9 /var/www/html/pr_autoup/vendor/symfony/dependency-injection/ContainerBuilder.php(767): Symfony\Component\DependencyInjection\Compiler\Compiler->compile() #10 /var/www/html/pr_autoup/vendor/symfony/http-kernel/Kernel.php(506): Symfony\Component\DependencyInjection\ContainerBuilder->compile() #11 /var/www/html/pr_autoup/vendor/symfony/http-kernel/Kernel.php(763): Symfony\Component\HttpKernel\Kernel->initializeContainer() #12 /var/www/html/pr_autoup/vendor/symfony/http-kernel/Kernel.php(126): Symfony\Component\HttpKernel\Kernel->preBoot() #13 /var/www/html/pr_autoup/app/AppKernel.php(102): Symfony\Component\HttpKernel\Kernel->boot() #14 /var/www/html/pr_autoup/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(87): AppKernel->boot() #15 /var/www/html/pr_autoup/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader80.php(45): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initKernel() #16 /var/www/html/pr_autoup/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(88): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader80->initConstants() #17 /var/www/html/pr_autoup/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader81.php(46): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #18 /var/www/html/pr_autoup/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader81->doUpgrade() #19 /var/www/html/pr_autoup/admin-dev/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #20 {main}"

### Expected behavior

I wish I could update from 1.7.8.11 to 9.0.0 

### Steps to reproduce

1. Install Prestashop 1.7.8.11 
2. Install module Autoupgrade from the develop branch 
3. Clic on configure
4. Select major Release to upgrade to 8.1.5 
5. Change your PHP to 8.1 
6. Do an upgrade from a folder to have the version 9.0.0 :negative_squared_cross_mark: ps_checkout is the problem
7. Uninstall ps_checkout from your shop and your files 
8. Do an upgrade from a folder to have the version 9.0.0 :negative_squared_cross_mark: ps_account is the problem
9. Uninstall ps_account from your shop and your files 
10. Do an upgrade from a folder to have the version 9.0.0 :negative_squared_cross_mark: You got all the error

### PrestaShop version(s) where the bug happened

1.7.8.11 to 8.1.5 to 9.0.0

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

autoupgrade v5.0.1

### Your company or customer's name goes here (if applicable).

PS

**Comment by florine2623** [comment]
Hello @AureRita ,

I do not have the same final error, but the upgrade doesn't work anyway :/

Error account :
<img width="1180" alt="Screenshot 2024-03-29 at 14 03 21" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/c511d05c-b8e4-4662-ac85-73dd6af2af9c">

Error checkout :
<img width="1180" alt="Screenshot 2024-03-29 at 14 20 55" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/a3f697b7-1ef3-47a4-9a50-3ce65f1492e0">

Error upgrade to 9.0.0 :
<img width="1221" alt="Screenshot 2024-03-29 at 14 28 36" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/8085f3b7-2500-400d-9d7e-83acc3f543be">

**Comment by bambinounos** [comment]
I faced a problem similar, now the store is broken . I upgrade from 1.7.8.11 to 8.1.5

**Comment by bambinounos** [comment]
#35790

**Comment by bambinounos** [comment]
@florine2623 did you got white page or error 500 ?
