### ISSUE TITLE
Failed to start the session: already started by PHP

### ISSUE THREAD

**Issue by malcek** [PrestaShop/PrestaShop#35785]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have migrate shop from 1.6 to 8.1.5 and everything went fine, but on one order I get error and offered that debug mode enable. If you hit back you can work normally on Backoffice. But if you hit debug mode you get error. 
![image](https://github.com/PrestaShop/PrestaShop/assets/54998637/ec789ad8-3c0d-4da6-97a8-d0cfff4c6e1f)

after that i try to manually delete cache directory no luck.
If i look at defines file there is no debug mode enable.

### Expected behavior

back to normal work in BO

### Steps to reproduce

Open order on new migrated shop from old shop
On some order there is problem with decimal values and getting error
If you hit enable debug mode you can't access to BO any more ang get this error
If you don't hit debug mode everything work fine.

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

no

**Comment by paulnoelcholot** [comment]
FYI @AureRita

**Comment by AureRita** [comment]
Hi @malcek 

Thank you for your report. Despite my effort I can't reproduce your issue, 

Did you use our module 1-Click-Upgrade to upgrade your shop or did you use another module for that ? 

Waiting for feedback

**Comment by malcek** [comment]
No, i have use Migration pro from Addons, but this problem is related to token generated from shop, not migration process. Or I'm I wrong? 🤔
1 click upgrade isn't capable to upgrade from that old shop. 
best regards,
Martin

**Comment by AureRita** [comment]
Hi @malcek 

I think this can be an issue from the migration. 
Indeed, if we go directly on a fresh install of 8.1.5, we don't have issue on token when we enable the debug mode. 

The decimal issue can only be an issue from the migration ( it doesn't take your round mode or anything you have already set up with some modules or anything else )

I think you can ask it direcly with the addons team. 

If you need more support from prestashop, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Thank you

**Comment by vipulhadiya** [comment]
I have installed fresh PrestaShop 8.1.7 and I am facing the same issue on Product listing page.
I can see on most of threads they closed the topics by saying they cannot reproduce the error. But still error persists for sure.
