### ISSUE TITLE
Prestashop v.8.1.5

### ISSUE THREAD

**Issue by kristogaleta** [PrestaShop/PrestaShop#35795]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Fresh install and made test order and if you mark order shipped and debug mode is on I will get this error:

![bug](https://github.com/PrestaShop/PrestaShop/assets/73786380/1418779b-a58e-4a32-9cf6-e12f1623f87d)

Server information: Linux #1 SMP Wed Nov 15 10:55:18 -00 2023 x86_64
Server software version: Apache / ZoneOS
PHP version: 8.1.27
Memory limit: 1024M
Max execution time: 30
Upload Max File size: 2047M

 
Anyone can help me how to fix it?

### Steps to reproduce

1. Create a new order in frontend.
2. Finish ordering, payment etc.
3. emails are send, order is being made in backoffice.
4. click on order to view; 
5. Mark shipped - the error occurs.

### PrestaShop version(s) where the bug happened

1.8.5

### PHP version(s) where the bug happened

8.1.27

**Comment by jlores** [comment]
This error occurs with any state change. as a hint, with php7.4 it doesn't happen to me

**Comment by Hlavtox** [comment]
Some module or override is using a property $order->shipping_number that is no longer used in 8.x.x. Probably hooked to email sending process.

**Comment by kristogaleta** [comment]
I think you are right shipping modules are causing that issue

**Comment by AureRita** [comment]
Hi @kristogaleta 

Thank you for your report, Despite my effort, I can't reproduce your issue as you can see : 

[recording(162).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/1d7d49d9-60d5-41d5-bae4-bb2743542628)

Did I miss something ? 

Is it a native module of shipping did you use ? 

Waiting for feedback

**Comment by kristogaleta** [comment]
All these shipping modules have same problem

https://github.com/ItellaPlugins/itella-shipping-prestashop
https://github.com/venipak/Venipak-Prestashop-1.6-1.7.7-8
https://github.com/mijora/omniva-prestashop-1.6-1.7

If you install any of them you can reproduce that

**Comment by Hlavtox** [comment]
@kristogaleta Yeah, all of those are faulty and must be updated fo v8 spec. :-)

Shipping number is no longer used and was removed.

Closing as related to third party incompatible modules.
