### ISSUE TITLE
Upgrade PrestaShop 1.7.8.11 to 8.1.5 failed/White page backend and error 500 frontend

### ISSUE THREAD

**Issue by bambinounos** [PrestaShop/PrestaShop#35790]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I was upgrading with the module and it shows 
[INTERNAL] /var/www/html/prestashop/vendor/symfony/symfony/src/Symfony/Component/Finder/Iterator/ExcludeDirectoryFilterIterator.php line 37 - Error: Call to undefined function Symfony\Component\Finder\Iterator\str_contains() #0 /var/www/html/prestashop/vendor/symfony/symfony/src/Symfony/Component/Finder/Finder.php(691): Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator->__construct() #1 /var/www/html/prestashop/vendor/symfony/symfony/src/Symfony/Component/Finder/Finder.php(573): Symfony\Component\Finder\Finder->searchInDirectory() #2 [internal function]: Symfony\Component\Finder\Finder->getIterator() #3 /var/www/html/prestashop/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php(165): iterator_to_array() #4 /var/www/html/prestashop/classes/Context.php(436): Symfony\Component\Filesystem\Filesystem->remove() #5 /var/www/html/prestashop/classes/Context.php(399): ContextCore->getTranslatorFromLocale() #6 /var/www/html/prestashop/classes/Translate.php(282): ContextCore->getTranslator() #7 /var/www/html/prestashop/modules/autoupgrade/classes/UpgradeTools/Translator.php(60): TranslateCore::getModuleTranslation() #8 /var/www/html/prestashop/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader81.php(58): PrestaShop\Module\AutoUpgrade\UpgradeTools\Translator->trans() #9 /var/www/html/prestashop/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader81.php(43): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader81->writeNewSettings() #10 /var/www/html/prestashop/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader81->doUpgrade() #11 /var/www/html/prestashop/admin191dsf4mp/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #12 {main}
it got crashed and white was shown
I tried to rollback to the previous version and it also gives other error, now frontend shows erorr 500 and backend white page. i deleted cookies and it is the same..
Error logs from log.txt  /admin/autoupgrade/tmp
Please check attchment

### Expected behavior

The store version 8.1.5

### Steps to reproduce

The upgrade process from module.
[log.txt](https://github.com/PrestaShop/PrestaShop/files/14820190/log.txt)

### PrestaShop version(s) where the bug happened

1.7.8.11 to 8.1.5

### PHP version(s) where the bug happened

7.4.3

### If your bug is related to a module, specify its name and its version

1-click upgrade last version

**Comment by AureRita** [comment]
Hi @bambinounos 

Thank you for your report, Despite my effort, I can't reproduce you issue as you can see : 

[recording(169).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/fe331444-82ef-4b4e-846d-7ef315e4b130)

Did I miss something ? 

I did it from a fresh install. 

Did you use a folder to do the upgrade ? 

Waiting for feedback

**Comment by rboadalabelgrup** [comment]
Hi @AureRita, today I had the same problem described by @bambinounos, and in order to update from 1.7.8.11 to 8.1.5, first I had to update from 1.7.8.11 to 8.1.1 and then to 8.1.5. I have the same PHP version as shown in the video. The only difference in my update is that I didn't have debug mode active. Now I ask, should debug mode be activated before updating? Thank you in advance.

**Comment by bambinounos** [comment]
@AureRita hi and thanks for time .
I forgot cache, selection no. I let cache yes. 
When I got the error and I tried to roll back and it. Doesn't work as well. Now the store is  error 500 and backend white.
There is any solution? Or I have to restore from backup? I also have the database from PrestaShop only, I didn't make a database dump from command line so the database is about 37 MB, but I did a dump from the database right now and it's about 375 mb . I don't know why it's the difference between both database.

**Comment by bambinounos** [comment]
@rboadalabelgrup when I updated it didn't let to choose another version. It was available 8.1.5 , no other.

**Comment by rboadalabelgrup** [comment]
@bambinounos I updated using the Archive option in channels list https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/upgrade-module/channels/#archive

**Comment by bambinounos** [comment]
@AureRita hi how are you?
Do you have any ideas about problem and how to solve it ?
Thanks in advance for your help.

**Comment by bambinounos** [comment]
hi @AureRita I am trying to rollback using cli command line, but I got this error, maybe do you have the cause?
![error-cli-rollback](https://github.com/PrestaShop/PrestaShop/assets/65610134/d1b94f05-1976-49c1-b484-512a285035e5)

**Comment by AureRita** [comment]
Hi @bambinounos 

I tested again your issue but I can't reproduce your issue even if I use the Archive option as you can see : 

[recording(179).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/908f1614-bc5d-49d8-b432-440a8f55243c)

Currently I can't find the way you have your error, maybe you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Thank you

**Comment by bambinounos** [comment]
@AureRita right now I restored it successfully.
But i am afraid if I will try to update to 8.1.5 again it will happen again.
What php version are using ?
I was reading version 8 needs php8.1 or more, maybe might it be the problem?

**Comment by AureRita** [comment]
Hi @bambinounos 

for the php version, you can see on this link : https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/

that you can use php 7.2 to 8.1 

if you use 7.4, it's ok. 

the last version that supported by 1.7.8 it's php 7.4 as you can see : 
![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/41872035-7c9b-4fdb-a373-b3c7ce77aa98)

Make it a try and tell me if you still have the bug 

Waiting for feedback

**Comment by bambinounos** [comment]
Did you try it with cache selection "yes"?
I see it's the difference between both procedures .

**Comment by AureRita** [comment]
Yes, I try it with cache selection put on "yes". For the first test I dot it without because I try to do it without external interference to see if, without it, it works. 

Waiting for your try

**Comment by ChillCode** [comment]
Hi @bambinounos 

If I understand correctly the error message, there is a call to a function (str_contains) that doesn't exists in PHP 7.4, so PS 8.1.5 is not fully compatible with PHP 7.4 ~~and the [requirements ](https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/) are wrong.~~

Also make sure you have all requirements, like php-zip php-gd php-intl etc...

**Comment by matks** [comment]
Please check discussion here https://github.com/PrestaShop/PrestaShop/discussions/35874

**Comment by bambinounos** [comment]
Hi @matks @AureRita and @ChillCode for your time. 
I am confused now.
Prestashop 1.7 php versions are the following.
![imagen](https://github.com/PrestaShop/PrestaShop/assets/65610134/0071ccb3-e096-4696-86c7-621d6904e50f)
it does not seem to be supported to php 8., so if we update php version before upgrading, it also would be a problem.
If I understand it correctly. 
I should add symfony/polyfill-php80 before upgrading, right?
If yes, I am not sure how to install it.
Best regards to you all

**Comment by ChillCode** [comment]
Theoretically you should do nothing, composer loads symfony/polyfill-php80 to prevent your error, but it's not.

From here you'll have to investigate further or get some [support](https://www.prestashop-project.org/support/).

**Comment by bambinounos** [comment]
@ChillCode you faced that error, did not you?
how did you solve it?
I do not have installed composer in the server.

**Comment by AureRita** [comment]
Hi @bambinounos 

We can see that you're trying to make your shop work and that you want to continue your adventure with Prestashop, so this kind of question won't be a waste of our time. Some questions can be answered more quickly by support, indeed, but you can see on this site https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/ that 8.0 and 8.1 support php 7.4 and minus version. 

To have the best autoupgrade, I think you could do an upgrade on minor version to 1.7.8.11 and do an upgrade with a major version just after that.

Waiting for your try

**Comment by paulnoelcholot** [comment]
Hello @bambinounos,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
