### ISSUE TITLE
Prestashop marketing with google error when sync 

### ISSUE THREAD

**Issue by valentinflausse** [PrestaShop/PrestaShop#35805]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have install "prestashop marketing with google" module to have a product flow. 
I configure it. 
Then, it tell me a date for the next sync.
It doesn't create product in my google account. 
But i have a fatal error in logs : 

`02-Apr-2024 07:00:01 Europe/Paris] PHP Fatal error:  Uncaught TypeError: ProductControllerCore::addProductCustomizationData(): Argument #1 ($product_full) must be of type array, bool given, called in /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/controllers/front/ProductController.php on line 1208 and defined in /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/controllers/front/ProductController.php:1359
Stack trace:
#0 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/controllers/front/ProductController.php(1208): ProductControllerCore->addProductCustomizationData()
#1 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/modules/psxmarketingwithgoogle/classes/Provider/PageViewEventDataProvider.php(49): ProductControllerCore->getTemplateVarProduct()
#2 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/modules/psxmarketingwithgoogle/classes/Handler/RemarketingHookHandler.php(103): PrestaShop\Module\PsxMarketingWithGoogle\Provider\PageViewEventDataProvider->getEventData()
#3 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/modules/psxmarketingwithgoogle/psxmarketingwithgoogle.php(249): PrestaShop\Module\PsxMarketingWithGoogle\Handler\RemarketingHookHandler->handleHook()
#4 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/classes/Hook.php(993): PsxMarketingWithGoogle->hookDisplayTop()
#5 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/classes/Hook.php(418): HookCore::coreCallHook()
#6 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/classes/Hook.php(928): HookCore::callHookOn()
#7 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/config/smarty.config.inc.php(205): HookCore::exec()
#8 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/classes/Smarty/SmartyLazyRegister.php(81): smartyHook()
#9 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/var/cache/prod/smarty/compile/AngarThemelayouts_layout_full_width_tpl/5e/94/80/5e94807def2ac301dbd2ae9ebf26a25a143f6cc5_2.file.header.tpl.php(131): SmartyLazyRegister->__call()
#10 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(248): Block_120400009066092416d74404_32527093->callBlock()
#11 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(184): Smarty_Internal_Runtime_Inheritance->callBlock()
#12 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(156): Smarty_Internal_Runtime_Inheritance->process()
#13 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/var/cache/prod/smarty/compile/AngarThemelayouts_layout_full_width_tpl/5e/94/80/5e94807def2ac301dbd2ae9ebf26a25a143f6cc5_2.file.header.tpl.php(40): Smarty_Internal_Runtime_Inheritance->instanceBlock()
#14 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_66092416d800f6_17315481()
#15 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#16 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render()
#17 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(386): Smarty_Internal_Template->render()
#18 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/var/cache/prod/smarty/compile/AngarThemelayouts_layout_full_width_tpl/3e/f6/25/3ef6258f81a1fd82a23dec124856f25191be9bdf_2.file.layout-both-columns.tpl.php(307): Smarty_Internal_Template->_subTemplateRender()
#19 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(248): Block_165324000266092416c0c705_76419572->callBlock()
#20 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(184): Smarty_Internal_Runtime_Inheritance->callBlock()
#21 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(156): Smarty_Internal_Runtime_Inheritance->process()
#22 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/var/cache/prod/smarty/compile/AngarThemelayouts_layout_full_width_tpl/3e/f6/25/3ef6258f81a1fd82a23dec124856f25191be9bdf_2.file.layout-both-columns.tpl.php(129): Smarty_Internal_Runtime_Inheritance->instanceBlock()
#23 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_66092416c27e69_97769044()
#24 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#25 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render()
#26 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(386): Smarty_Internal_Template->render()
#27 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(115): Smarty_Internal_Template->_subTemplateRender()
#28 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/var/cache/prod/smarty/compile/AngarThemelayouts_layout_full_width_tpl/05/e9/33/05e933f512ffe90f825805d88162708fd50e5d35_2.file.layout-full-width.tpl.php(43): Smarty_Internal_Runtime_Inheritance->endChild()
#29 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_66092416bb7ed8_50989580()
#30 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#31 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render()
#32 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(386): Smarty_Internal_Template->render()
#33 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(115): Smarty_Internal_Template->_subTemplateRender()
#34 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/var/cache/prod/smarty/compile/AngarThemelayouts_layout_full_width_tpl/7b/4c/ce/7b4cce38228e4a7c82c12cb5534fae848510971a_2.file.page.tpl.php(33): Smarty_Internal_Runtime_Inheritance->endChild()
#35 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_66092416b99897_96439688()
#36 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#37 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render()
#38 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(386): Smarty_Internal_Template->render()
#39 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_inheritance.php(115): Smarty_Internal_Template->_subTemplateRender()
#40 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/var/cache/prod/smarty/compile/AngarThemelayouts_layout_full_width_tpl/b3/77/e3/b377e3c0bf7a92d4c80f7e60e4b968b24db51d05_2.file.404.tpl.php(39): Smarty_Internal_Runtime_Inheritance->endChild()
#41 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_660940c91410a4_99527948()
#42 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#43 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render()
#44 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render()
#45 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute()
#46 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/classes/controller/FrontController.php(715): Smarty_Internal_TemplateBase->fetch()
#47 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/classes/controller/FrontController.php(697): FrontControllerCore->smartyOutputContent()
#48 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/classes/controller/Controller.php(339): FrontControllerCore->display()
#49 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/classes/Dispatcher.php(510): ControllerCore->run()
#50 /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/index.php(28): DispatcherCore->dispatch()
#51 {main}
  thrown in /srv/data/web/vhosts/besancon-archerie.fr/htdocs/boutique/controllers/front/ProductController.php on line 1359`

### Expected behavior

Create google products and sync theme with my google account, with no fatal error php.

### Steps to reproduce

Install module, 
set up, 
wait sync.

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.2.13

### If your bug is related to a module, specify its name and its version

Prestashop marketing with google v1.69.0 

### Your company or customer's name goes here (if applicable).

besancon archerie

**Comment by Hlavtox** [comment]
Hi, you need to contact Prestashop company for support with this module. It's not a native module. Thank you for understanding.

ping @sowbiba
