### ISSUE TITLE
Unit price not working correctly outside of product page and cart

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#35811]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Put 

```
{l s='(%unit_price%)' d='Shop.Theme.Catalog' sprintf=['%unit_price%' => $product.unit_price_full]}
```

anywhere into `/classic/templates/catalog/_partials/miniatures/product.tpl` and see that it has wrong values.

### Expected behavior

Unit price must display correctly everywhere, with taxes, with specific prices.

### Steps to reproduce

See issue description.

### PrestaShop version(s) where the bug happened

8.1.5

**Comment by Hlavtox** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/35812

**Comment by florine2623** [comment]
Hello @Hlavtox ,

Thanks for the report. It is indeed a bug.

The unit price should stay the same with specific price or not, displayed with tax or not.

| Product details page  | Quick View |
| ------------- | ------------- |
| <img width="933" alt="Screenshot 2024-04-04 at 14 59 45" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/cca3c227-b1f8-4e21-b588-b05098687e11">  |  <img width="1150" alt="Screenshot 2024-04-04 at 15 01 31" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/8abbf9b7-2268-44aa-ae84-f12ba6eb17ba"> |
| <img width="938" alt="Screenshot 2024-04-04 at 15 02 35" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/e9df4491-62f3-4169-a46b-f6c326fe6652">  |  <img width="1139" alt="Screenshot 2024-04-04 at 15 02 24" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/50417ba3-462e-4a1f-bdb2-6fc0ec7d1528"> |

Thanks!
