### ISSUE TITLE
Problem when switching context for multistore in symfony layout

### ISSUE THREAD

**Issue by M0rgan01** [PrestaShop/PrestaShop#35828]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

[Capture vidéo du 04-04-2024 15:10:43.webm](https://github.com/PrestaShop/PrestaShop/assets/36233446/3a86b2c7-0f6b-41d0-8139-b380521b4147)

The context is not correct in the symfony layout, it should be in all context, as indicated in the warning. This error is present on all pages which should switch from context to all shops

### Expected behavior

The context should be in all shops on the symfony layout

### Steps to reproduce

1. Enable multistore && symfony layout
2. Create a new shop
3. Select a shop in a page allowing you to select a store, like the product page
4. Go to a page which normally switches to an all shop context
5. See shop context

### PrestaShop version(s) where the bug happened

9

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

-

### Your company or customer's name goes here (if applicable).

-

**Comment by florine2623** [comment]
Hello,

I reproduce the issue with PrestaShop version develop, I'll add this to the backlog so it can be fixed.

https://github.com/PrestaShop/PrestaShop/assets/16019289/3d8324f9-e23a-4c67-a6cf-f6c719caf628

Thank you
