### ISSUE TITLE
A new order email is sent when the order status is payment error

### ISSUE THREAD

**Issue by airudel** [PrestaShop/PrestaShop#35820]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have received several complaints from customers who report that they receive a new order email but when they log into prestashop they discover that the order has not been carried out as there has been an error in the payment, i.e. the order has been generated but has not been completed due to an error in the payment. 

Normally customers only check their email to see if they receive new orders and more than once they have prepared and sent the order and then realised that there was an error in the payment.

In the mail alerts module you will find the code that sends these new order mails. I do not know if prestashop has taken into account that another type of email is sent saying that someone has placed an order but there has been a failure in the payment, or directly if the order status is error in the payment that this email is not sent. 

### Steps to reproduce

To reproduce it you only have to generate an error in the payment in a test environment with card payment and you will receive a new order email. 

### PrestaShop version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello @airudel ,

What is the payment module you're using that causing this issue ?
Is it bank transfer or wire payment ?

Waiting for your feedback.

**Comment by Hlavtox** [comment]
@airudel This entirely depends on the payment module.

Some create the order and THEN proceed with the payment, setting the appropriate state.
Some modules DON'T create the order right away, they do it if the payment went through.

### What sends what
- All mailing related to payment is processed by the payment module.
- Prestashop core sends only order_conf email.
- Admin email is sent by email alerts module after creating the order.

@florine2623 I suggest closing it as it depends on payment module implementation.

**Comment by airudel** [comment]
I would say it is the email alert module. 

This module is responsible for sending the email of a new order but does not control the status of the order. 

In the ps_emailalerts.php file in the hookActionValidateOrder function. At the end we see the conditions for sending that email but not to control the status of the order sends the email even if that order has produced a failure to pay. I do not know if in that case there should be a conditional more to control the status of the order and send another type of mail that says the order has failed see the prestashop panel for more information, for example. 

I think this would help customers a lot more.

**Comment by Hlavtox** [comment]
@airudel ps_emailalerts sends admin notifications only. If you want to change it's behavior, you can make a copy of it with modified behavior. 👍

**Comment by airudel** [comment]
I understand that, I was always referring to the notification for the administrator, not for the client. If there is a failure in the payment, the customer receives a notification with that error, but the administrator receives a new order notification. 

In the prestashop support chat they suggested me to talk about this to notify it and that this module could be updated with this variation as I think it is important because many customers screw up and send orders in which the payment has not been done correctly and notice it later.

I am sorry if it was confusing when I referred to customer, but I am referring to my customers for whom I manage the ecommerce.

**Comment by florine2623** [comment]
@airudel 
If you can sent me the steps to reproduce a failed payment with a native payment module from PS like wire payment or bank transfer, I could test it.

**Comment by airudel** [comment]
@florine2623 

To show the order status error in the payment it is impossible to do it with the bank transfer payment module, as by default the order status is pending payment.

I can recreate it with a credit card payment module and a test environment, but these modules are for a fee. 

I can recreate it for you attaching screenshots of the process and the emails sent to the administrator and the customer.

**Comment by Hlavtox** [comment]
I get your point, but this is purely a module thing AND a feature request. Most merchants want to know about an order with failed payment, so they can contact the customer.

You can easily do this by your own notification module. 👍

**Comment by airudel** [comment]
@Hlavtox 

That's why I think that the notification to the administrator of a new order that has generated an error status in the payment should appear in the email that arrives. I think it should be a default in the module as it is the logical thing to do.

I will leave a solution here in case someone needs it at some point.
