### ISSUE TITLE
Disparition module Carrousel

### ISSUE THREAD

**Issue by Guy7572** [PrestaShop/PrestaShop#35836]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have an issue with the 8.1.3 Prestashop Version. I can't find more the native module "Carrousel" as u can see in my captur screen below.

![Uploading Capture d'écran 2024-04-04 194226.png…]()

### Steps to reproduce

1. Go to module section
2. Look for "carrousel"
3. If you fin module, all good, but if you dont find it we have the same problem.

### PrestaShop version(s) where the bug happened

8.1.3

**Comment by paulnoelcholot** [comment]
@PrestaShop/product-council It seems to me that this module no longer exists since version 8.0.0. Can you confirm this for me?

**Comment by kpodemski** [comment]
Hello @Guy7572 

The screenshot you tried to upload didn't get through. I don't recall any "carousel" module from the native modules, there's [ps_imageslider](https://github.com/PrestaShop/ps_imageslider/releases) module and it is still available in PrestaShop as a native module. If you could share the module's technical name with us, that would be helpful, but as far as I recall, we haven't removed any native modules recently.

**Comment by florine2623** [comment]
Carrousel module must be an external module you manually added or a module that came with a template.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
