### ISSUE TITLE
Errors when regenerating index by cron call

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#35833]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When search index regeneration is called by CRON, errors are logged in console, if the URL contains `&redirect=1`.

```
 PHP Warning:  Undefined array key "HTTP_REFERER" in /var/www/vhosts/xxxxx.cz/xxxxx.cz/controllers/admin/AdminSearchController.php on line 569'

PHP Deprecated:  strtolower(): Passing null to parameter #1 ($string) of type string is deprecated
in /var/www/vhosts/agrola.cz/xxxxx.cz/classes/Tab.php on line 389

PHP message: PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated
in /var/www/vhosts/agrola.cz/xxxxx.cz/classes/Dispatcher.php on line 973'
```

because $_SERVER['HTTP_REFERER'] may not be passed when calling the URL by cron.

### Expected behavior

No error should be logged.

### Steps to reproduce

See issue description.

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.1, Plesk management panel

**Comment by paulnoelcholot** [comment]
Hello @Hlavtox,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by Hlavtox** [comment]
@paulnoelcholot You can reproduce if you call this URL by cron - https://domain.cz/admin/index.php?controller=AdminSearch&action=searchCron&ajax=1&full=1&token=something&redirect=1&id_shop=1

It's very easy if you copy the "Regenerate index" url accidentaly, instead of the one below.

**Comment by Hlavtox** [comment]
Fixed https://github.com/PrestaShop/PrestaShop/pull/35834
