### ISSUE TITLE
Cannot access Admin page after upgrading Product Comments module from 6.02 to 6.0.3 in Prestashop 1.7.7.8 

### ISSUE THREAD

**Issue by mmursalov** [PrestaShop/PrestaShop#35854]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After upgrading Product Comments module from 6.0.2 to 6.0.3, I can no longer access the Admin page as it shows the following error message:

Oops... looks like an unexpected error occurred.

The service "product_comment_criterion_form_data_provider" has a dependency on a non-existent service "prestashop.core.admin.lang.repository".

[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException 0]

### Steps to reproduce

Upgraded the module Product Comments from 6.0.2 to 6.0.3 and Admin page stopped loading

### PrestaShop version(s) where the bug happened

1.7.7.8

### PHP version(s) where the bug happened

PHP Version 7.3.33

### If your bug is related to a module, specify its name and its version

product_comment

**Comment by AureRita** [comment]
Hi @mmursalov 

Thank you for your report, Despite my effort, I can't reproduce your issue as you can see : 
![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/965d9633-e36a-4d39-b5c0-0c1db8b934f2)

FYI : I need to test it on the last release of Prestashop, that's why I'm on 8.1.5. 

Did you use the system of Prestashop to upgrade your product comment on 6.0.3 or did you download it on a command ? 

Waiting for feedback

**Comment by mmursalov** [comment]
Hi,

thanks for working on this issue. I have upgraded using the Module Manager via Admin. So, it was not via a command.

kind regards,
Murad:

**Comment by Tialp** [comment]
I got exactly the same issue and i did exactly the same step, i need help on that please.

**Comment by Ami-more** [comment]
Hello, I have the same problem with the same configuration. Thank you for your help and give us a fix to restore our sites.
Kind regards
Richard

**Comment by Tialp** [comment]
The "Solution" that i find for know is to delete the "productcomment" and replace it with the same module but from a backup before i did the upgrade

**Comment by Ami-more** [comment]
I've tried it before and just tried it again, and it's always the same. The attachment shows the message I have.
![Screenshot 2024-04-08 at 17-03-46 https __www ami-more com](https://github.com/PrestaShop/PrestaShop/assets/166413383/2579b97a-b0f6-44a1-9a33-0c88400eb96d)

**Comment by Tialp** [comment]
i have delete it directly in my host file if you want to try

**Comment by Ami-more** [comment]
That's what I did, but I'm still stuck in debug mode.

**Comment by Ami-more** [comment]
Thanks for your help, I've managed to reactivate the site by modifying the config/defines.inc.php file.
https://www.prestashop.com/forums/topic/1014486-impossible-de-quiter-le-mode-debug/

**Comment by mmursalov** [comment]
Not sure why this got closed, as problem still exists. Workaround’s mentioned here is not a fix, as upgrading add-on from 6.0.2 to 6.0.3 will still lead to the same issue.

**Comment by azanianFr** [comment]
Hi I'm having the same issue as well ! If someone have a solution to permanently fix it ?

**Comment by ChillCode** [comment]
Hi

~~Justo to note that 6.0.3 use services and ps_feature_flag table only available from PS 1.7.8.0 >.~~

**Comment by kpodemski** [comment]
@ChillCode could you be more specific? where is it using those?

**Comment by ChillCode** [comment]
@kpodemski when services load:

https://github.com/PrestaShop/productcomments/blob/dev/config/admin/services.yml

This argument required is only available from 1.7.8 not present in 1.7.7

`- '@prestashop.core.admin.lang.repository'
`

Committed here:

https://github.com/PrestaShop/productcomments/pull/191/commits

**Comment by kpodemski** [comment]
@ChillCode 

https://github.com/PrestaShop/PrestaShop/blob/1.7.7.x/src/PrestaShopBundle/Resources/config/services/bundle/repository.yml#L27

**Comment by ChillCode** [comment]
Hi @kpodemski 

I've seen this module appearing and disappearing from few days ago but just found this when faced this error, so some ghost is there:

If you debug the controller the services prestashop.core.admin.* are not loaded, via php bin/console debug:container they can be seen.

If we add the service to /var/www/prestashop/public_html/modules/productcomments/config/admin/services.yml:

```
  prestashop.core.admin.lang.repository:
    class: PrestaShopBundle\Entity\Repository\LangRepository
    factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
    arguments:
      - PrestaShopBundle\Entity\Lang
```

Module works:

![image](https://github.com/PrestaShop/PrestaShop/assets/9787055/4f938dd6-2555-4931-9c26-eb8380122e05)

Then I just upgraded to 8.1.5 so problems are gone.

**Comment by ChillCode** [comment]
At the end I did just thought that the service was not present and since I'm working with 8 this just was an update for a merchant, sorry for the misunderstanding.
