### ISSUE TITLE
Product list display issue in Admin - v8.1.5

### ISSUE THREAD

**Issue by tgd1973** [PrestaShop/PrestaShop#35853]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The new Admin theme - v8.1.5 implements the download of a foreign source:
https://unpkg.com/@prestashopcorp/edition-reskin@0.2.4/dist/back.min.css

( which in my opinion is also a little out of privacy as this site can track exactly who and how is using prestashop! )

Aside from all legality problems.... it is not possible to change the way in which the list of products is displayed on the admin page which for a large store becomes difficult to follow all the products...
making the central part narrower even if in reality there is plenty of space to adjust the page with products so as not to force the admin to scroll to the bottom of the page every time to pull the horizontal bar and then return again to up and down again...

the self-adaptation of the central part is missing due precisely to instructions that we don't know because they are there ... but they do more harm than good... and above all, being a remote .css file, you can't even modify them...

I also post some screenshots so can understand the situation:

![Actual](https://github.com/PrestaShop/PrestaShop/assets/15127860/8a614315-fad5-4b94-8c32-95d48825ec80)

![Desired](https://github.com/PrestaShop/PrestaShop/assets/15127860/ab1511bf-19bb-4614-bb06-3f401ed56460)

### Steps to reproduce

Go to Admin page of products

### PrestaShop version(s) where the bug happened

v8.1.5

### PHP version(s) where the bug happened

8.1

**Comment by AureRita** [comment]
Hi @tgd1973 

Thank you for your issue. Unfortunately, this issue is about the edition theme and we only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Thank you

**Comment by tblivet** [comment]
Hello @tgd1973,

We have applied a fix to the remote CSS file to address the issue.
After refreshing the cache, the problem should be resolved on your BO.

Thank you

**Comment by tgd1973** [comment]
Thank you very much.

**Comment by haveyougotanypets** [comment]
@tblivet are you sure this issue has been fixed, it seems to be present in 8.2.1
