### ISSUE TITLE
ps_emailalerts with external payment module sends email to admin even though payment not finished

### ISSUE THREAD

**Issue by DF94** [PrestaShop/PrestaShop#35862]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

I am using an external module for payment procedures. At the prestashop checkout page, when I choose the external payment method and confirm the purchase, I am redirected to the external payment page. I make the payment and get redirected back to prestashop success order page which shows me that the order was placed successfully. Everything working as expected. ✔️ 
Now the problem:
When I click the confirm button after choosing the payment method, an email is sent to the admin that an order was placed through the use of the module "ps_emailalerts", but I haven't even paid yet... And I can still cancel or just leave the payment page.
I'm asuming it's because the payment is usualy done inside the prestashop checkout page and not on an external page.
Is this a bug or is there something I can do about it? Maybe change a hook? Or anything else on the code?

### Expected behavior

1. Proceed through the checkout page in prestashop.
2. Choose external module payment method that uses an external link for the payment.
3. Get redirected to external page.
4. Do the payment.
5. Get redirected back to prestashop and get shown the successfull order placed page.
6. Order email gets sent to the admin through the module "ps_emailalerts".

### Steps to reproduce

1. Proceed through the checkout page in prestashop.
2. Choose external module payment method that used an external link for the payment.
3. Get redirected to external page.
4. "ps_emailalerts" sends an email to the shop admin that an order was placed. But buyer hasn't payed yet.

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

 8.1.27

### If your bug is related to a module, specify its name and its version

ps_emailalerts v3.0 and  vivawalletsmartcheckout v1.3.1

**Comment by Hlavtox** [comment]
Hi, the same answer as in the issue opened 4 days ago - https://github.com/PrestaShop/PrestaShop/issues/35820.

Best way to handle this is to make your own copy of ps_emailalerts module and modify it, so it sends the notification:
- On actionValidateOrder for all other payment methods except vivawalletsmartcheckout.
- On hookActionOrderStatusUpdate, if payment module is vivawalletsmartcheckout and new order status is payment accepted.

Hire a professional to do this modification for you.

However, personal note - I suggest you also handle these orders with failed payments. Often the customer goes to a different store after his payment fails. If you get notified, you can still call him and ask him what was wrong and change the payment method for him.
