### ISSUE TITLE
Associations in Webservice Request Synopsis are incorrect

### ISSUE THREAD

**Issue by luigimassa** [PrestaShop/PrestaShop#35867]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When call `/api/categories?schema=synopsis` associations in response are incorrect:  entity contain number 0 not filed id!
```xml
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <category>
        ......
        <associations>
            <categories nodeType="category" api="categories">
                <category>
                    <0>
                        <![CDATA[]]>
                    </0>
                </category>
            </categories>
            <products nodeType="product" api="products">
                <product>
                    <0>
                        <![CDATA[]]>
                    </0>
                </product>
            </products>
        </associations>
    </category>
</prestashop>
```

### Expected behavior

```xml
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <category>
        ......
        <associations>
            <categories nodeType="category" api="categories">
                <category>
                    <id>
                        <![CDATA[]]>
                    </id>
                </category>
            </categories>
            <products nodeType="product" api="products">
                <product>
                    <id>
                        <![CDATA[]]>
                    </id>
                </product>
            </products>
        </associations>
    </category>
</prestashop>
```

### Steps to reproduce

1. enable web service
2. create web service key
3. enable entity category, product or others with associations
4. save
5. open post man 
6. call web service:  /api/categories?schema=synopsis

### PrestaShop version(s) where the bug happened

8.0.2

### PHP version(s) where the bug happened

7.4

### Your company or customer's name goes here (if applicable).

Bwlab, Luigi Massa

**Comment by luigimassa** [comment]
Problem is in file `classes\WebserviceOutputBuilder.php`, line ~ 714
```php
  foreach ($fields_assoc as $field_name => $field) {
            if (!is_array($this->fieldsToDisplay) || in_array($field_name, $this->fieldsToDisplay[$assoc_name])) {
                if (isset($field['id']) && !isset($field['sqlId'])) {   //<-----error
                    $field['sqlId'] = 'id';
                    $field['value'] = isset($object_assoc['id']) ? $object_assoc['id'] : null;
                } elseif (!isset($field['sqlId'])) {
                    $field['sqlId'] = $field_name;
                    $field['value'] = isset($object_assoc[$field_name]) ? $object_assoc[$field_name] : null;
...
```
` if (isset($field['id']) && !isset($field['sqlId'])) ` is always false because `isset($field['id'])` check if `id` key exist and if the value is not null. But, with synopsis is always `null`
In version 8.0.1 was `if ($field_name == 'id' && !isset($field['sqlId']))`

**Comment by florine2623** [comment]
Hello @luigimassa ,

I can't reproduce your issue.

In my browser, when I call `my_shop.com/api/categories?schema=synopsis`
<img width="499" alt="Screenshot 2024-04-09 at 09 53 35" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/840cfbc6-a2c9-4b0f-b6d7-24fe0c863eaf">

In postman when i use a GET request :
<img width="475" alt="Screenshot 2024-04-09 at 09 53 52" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/c222d4b8-86d2-4ff3-8125-06512a59d27c">

Am I missing something ?
Waiting for your feedback.

**Comment by luigimassa** [comment]
Correct.
I checked. 
Thanks
