### ISSUE TITLE
International > Languages : Display locale in list & readonly edit

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#35860]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The locale is very useful for the language.
But it is in database and not displayed in BO (Listing / Edit (readonly mode))

After discussion with @jolelievre, it should be a good idea.

### Steps to reproduce

1. Go to BO
2. Go to International > Languages
3. In List, the locale should be displayed

### PrestaShop version(s) where the bug happened

9.0.x

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

**Comment by AureRita** [comment]
Hi @Progi1984 ,

Thank you for your report, I reproduce the issue with PrestaShop version 8.1.x, as you can see : 
![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/23baf5e3-a5f2-4879-bd7c-b01795635dbf)

![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/ab7affb8-8e30-4966-b46d-88d74fc36df1)

I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved.

Thanks

**Comment by Progi1984** [comment]
Fixed by #37692 & #37742.

Thanks @jolelievre 😍
