### ISSUE TITLE
Impossible to assign a specific price to a variation

### ISSUE THREAD

**Issue by onwebb** [PrestaShop/PrestaShop#35868]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you want to define a specific price for a single variation, you cannot select it from the drop-down list.
![screenshot](https://github.com/PrestaShop/PrestaShop/assets/166424855/20c63dcf-ab43-4926-a651-948bf702a675)

### Steps to reproduce

1. Go to product ID 2345
2. “Price” tab
3. Change the specific price

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.0

### Your company or customer's name goes here (if applicable).

Bomoï

**Comment by florine2623** [comment]
Hello @onwebb ,

This is not a core issue.
Please contact the Edition support for that issue.

**Comment by onwebb** [comment]
Support told me that the problem comes from the new experimental product page and that this problem is not supported within the scope of Prestashop Support. So they told me to report the problem to you.

**Comment by florine2623** [comment]
I can't reproduce your issue on the core :

<img width="1440" alt="Screenshot 2024-04-09 at 09 44 26" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/8fa0e466-3a61-408a-8b21-dd1c9444be6c">

**Comment by onwebb** [comment]
Do you want backoffice access?

**Comment by onwebb** [comment]
Hello

Do you want backoffice access?

Thanks,

Baptiste
