### ISSUE TITLE
erreur 500 sur backend

### ISSUE THREAD

**Issue by elodie66000** [PrestaShop/PrestaShop#35869]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Bonjour

j'ai une erreur qui s'affiche des l'affichage de la page backend 

`Warning: require(/var/www/vhosts/xxxxxxxx/httpdocs/www/var/cache/dev/Container1J3L2B8/getDebug_ArgumentResolver_RequestAttributeService.php): Failed to open stream: No such file or directory`

`Warning: require(/var/www/vhosts/bbbbb/httpdocs/www/var/cache/dev/Container1J3L2B8/getRouting_LoaderService.php): Failed to open stream: No such file or directory`

No route found for "POST /modules/improve/design/themes
merci pour votre aide.

### Steps to reproduce

1/j'ai été sur les theme pour activer le theme par defaut et constaté une erreur 500.
Il m'a affiche un message dans le dossier cache, j'ai vidé le cache et un autre message est apparut

in [/var/www/vhosts/xxxxx/httpdocs/www/var/cache/dev/Container1J3L2B8/a](https://xxxx/admin6459wqcii7knt2wyztl/)

si je desactive le debogage j'ai de nouveau acces mais lors du changement theme toujours erreur 500

### PrestaShop version(s) where the bug happened

8.0.2

### PHP version(s) where the bug happened

7.4

**Comment by elodie66000** [comment]
j'ai régle le bug en desactivant le module design prestashop mais j'ai ce message qui apparait coté frontend 



Warning: Undefined array key "controller" in /var/www/vhosts/xxxxxxxxxxx/httpdocs/www/classes/Dispatcher.php on line 1053

**Comment by elodie66000** [comment]
j'ai compris que des que j'active les url simplifié j'ai les erreurs 404 dans les pages reecrite

**Comment by ebuildy** [comment]
hello, tu peux tenter de clear le cache Php ? (un gros rm -rf du dossier var/cache)

**Comment by florine2623** [comment]
I'm closing the issue as this does not respect the norm of the issues. Your  issue must be in English.

Also, this is an issue that can't be reproduced on a fresh install.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
