### ISSUE TITLE
product_comment_criterion_form_data_provider

### ISSUE THREAD

**Issue by Guigui50** [PrestaShop/PrestaShop#35884]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Bonjour, 
Depuis une dernière mise à jour, je n'ai plus accès à mon Back office.

Le service "product_comment_criterion_form_data_provider" a une dépendance sur un service "prestashop.core.admin.lang.repository" inexistant.

Merci.

### Steps to reproduce

1. ouverture de la page d'accueil du back office inaccessible

### PrestaShop version(s) where the bug happened

1.7.6 ?

### PHP version(s) where the bug happened

?

### If your bug is related to a module, specify its name and its version

Je ne sais pas quel module ?

**Comment by paulnoelcholot** [comment]
Hello @Guigui50,

Please send your request in English. English is the norm on GitHub.

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Thank you

**Comment by matks** [comment]
@leemyongpakva is able to reproduce the issue on PS 1.7.7 but has no issues with PS 1.7.8

So it looks this is a bug only impacting PS < 1.7.8
