### ISSUE TITLE
Missing Bank data in email confirmation on prestashop 8.1.5

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#35881]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
I've upgraded many websites to prestashop 8.1.5, unfortunately two of these have the problem again in the 1.7 versions
Even in the past these two sites had the same problems, with the bank transfer confirmation email not showing the bank details.
I saw that several corrections were made, I see that there are two files
/mails/themes/classic/core/bankwire.html.twig
/mails/themes/modern/core/bankwire.html.twig

both sites are multilingual, the prestashop cache is not active, they are on dedicated servers in different countries, I don't see any overrides that can create problems.

I solve the problem only by putting the email files in the theme used for each language, entering the data for the bank transfer

on my demo site I can't reproduce the error

Unfortunately these reports came from their customers

![Screenshot_2024-04-09-11-29-39-562_com google android gm](https://github.com/PrestaShop/PrestaShop/assets/653230/ee770cfc-b074-48f2-a633-9647cef5d559)

bye

### Steps to reproduce

I will do some tests on copies of those sites, to try to give you more information, in the meantime I wanted to warn you of the presence of this problem

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_wirepayment v2.2.0

**Comment by Maofree** [comment]
if I set this code in a module to see if the sendEmail of OrderHistory.php gets the bankwire data, I can see them

`        $module_name = 'ps_wirepayment';
        if ($module_name) {
            $module = Module::getInstanceByName($module_name);
            if (Validate::isLoadedObject($module) && isset($module->extra_mail_vars) && is_array($module->extra_mail_vars)) {
                var_dump($module->extra_mail_vars);
            }
        }`

**Comment by florine2623** [comment]
I can't reproduce your issue.

Do you have some steps to reproduce it ? 
Thanks!

**Comment by Maofree** [comment]
Hi
I only reproduce it on 4 real multilingual sites where bank data is not sent in bankwire emails.
Unfortunately there are errors that do not reproduce on small demo sites, but this does not prove that there are no errors of this type too. I haven't had time to test yet.
I feel like I think it's a cache problem or something like that, because at a code level it seems correct to me, given that I can get the data present in the bankwire module from another module, but when confirming the order, maybe other things also come into play factors where perhaps the data are zero

**Comment by florine2623** [comment]
As it cannot be reproduces everywhere it might be a specific issue with your shops.

If you have the steps to reproduce, you can re-open this issue.
