### ISSUE TITLE
Bug sur le module "produit de la même catégorie

### ISSUE THREAD

**Issue by DTStudio38** [PrestaShop/PrestaShop#35889]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Le module affiche que le premier cadre avec les informations du produits. 
Les autres, il n'y a que l'image mais pas les informations. 

![bug site](https://github.com/PrestaShop/PrestaShop/assets/166630021/9c7af96a-25bd-4572-89f4-68f39c91305c)

### Expected behavior

Avoir un module à installer avec une mise à jour qui élimine le bug

### Steps to reproduce

J'ai desactivé le module mais avant je voyais ça sur la page produit 
![bug site](https://github.com/PrestaShop/PrestaShop/assets/166630021/c3412a0b-7080-4916-a2ee-7f985a7ad334)

### PrestaShop version(s) where the bug happened

1.7.8.11

**Comment by Hlavtox** [comment]
Hi @DTStudio38, please open a new issue in English. And I think that your issue is related to third party themes and modules anway. 👍

**Comment by florine2623** [comment]
You need to contact the develop of your theme directly.
