### ISSUE TITLE
I Can not access Admin page after upgrading Product Comments module from 6.02 to 6.0.3 in Prestashop 1.7 

### ISSUE THREAD

**Issue by BENHAM40** [PrestaShop/PrestaShop#35897]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

after I update the product comment product and I lost access to admin and our website is down. 

![Screenshot 2024-04-11 at 11-55-59 https __lenda ma](https://github.com/PrestaShop/PrestaShop/assets/166665589/06e643ee-69df-4dcd-8226-68957d986739)
![Screenshot 2024-04-11 at 11-55-46 The service product_comment_criterion_form_data_provider has a dependency on a non-existent service prestashop core admin lang repository   (500 Internal Server Error)](https://github.com/PrestaShop/PrestaShop/assets/166665589/e02ff318-0a21-479c-a877-4d6699563092)

### Steps to reproduce

Upgraded the module Product Comments from 6.0.2 to 6.0.3 and Admin page stopped loading

### PrestaShop version(s) where the bug happened

1.7.7.4

### PHP version(s) where the bug happened

PHP Version 7.3.33

### If your bug is related to a module, specify its name and its version

product_comment

**Comment by florine2623** [comment]
Hello @BENHAM40 ,

Your issue is similar to : https://github.com/PrestaShop/PrestaShop/issues/35886

I'm closing it to avoid clogging the backlog.
Thanks!

**Comment by matks** [comment]
@leemyongpakva is able to reproduce the issue on PS 1.7.7 but has no issues with PS 1.7.8

So it looks this is a bug only impacting PS < 1.7.8
