### ISSUE TITLE
[develop] BO - blockwishlist module throws an exception

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#35899]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

An exception is thrown and I can't configure my module blockwishlist from the BO.

Works well on PS 8.0.x and 8.1.x with `v2.1.2` and `v3.0.1`

<img width="1055" alt="Screenshot 2024-04-11 at 16 04 08" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/daf970b3-8e73-4d47-bee7-ae2a7b909056">

`The controller for URI "/modules/blockwishlist/configuration" is not callable: Controller "PrestaShop\Module\BlockWishList\Controller\WishlistConfigurationAdminController" has required constructor arguments and does not exist in the container. Did you forget to define the controller as a service?`

### Expected behavior

Should open the configuration page correctly

### Steps to reproduce

1. Go to BO > Modules manager
2. Search blockwishlist
3. Click Configure, see exception :x:

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

blockwishlist v3.0.1

**Comment by paulnoelcholot** [comment]
FYI @AureRita
