### ISSUE TITLE
Changelog modules always empty

### ISSUE THREAD

**Issue by sharkooon** [PrestaShop/PrestaShop#35896]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Changelog on module update page is always empty for all modules. But there are changes if you click on "Read more".

<img width="982" alt="Scherm­afbeelding 2024-04-11 om 13 17 30" src="https://github.com/PrestaShop/PrestaShop/assets/533123/56b775b1-d8c3-45ba-bfa7-1d9c14cf5c9a">
<img width="769" alt="Scherm­afbeelding 2024-04-11 om 13 17 44" src="https://github.com/PrestaShop/PrestaShop/assets/533123/ed1d19a2-7b1c-4321-9c92-919262c24e8e">

### Expected behavior

See changlog for each module.

### Steps to reproduce

1. go to Module manager
2. go to Updates
3. see list of upgradable modules.

### PrestaShop version(s) where the bug happened

8.1.5 (only dutch language installed)

**Comment by florine2623** [comment]
Hello @sharkooon ,

This is the wanted behavior.

Here's the related PR : https://github.com/PrestaShop/PrestaShop/pull/27111

On fresh install of version 8, you should not be seing the Read More button.

I'm closing this issue.
