### ISSUE TITLE
BUG icon disappeared in "orders" View invoice, View delivery note, display

### ISSUE THREAD

**Issue by AR404lab** [PrestaShop/PrestaShop#35908]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have a problem on my PrestaShop 1.7.8.2 website: the buttons "View invoice" "View delivery note" "View" are clickable but the icons / pictograms have disappeared ! 

### Steps to reproduce

Go on Orders and see 

![image png ebf1dcb105cc34577060545ee9661b57](https://github.com/PrestaShop/PrestaShop/assets/97963753/d9e077a2-8d5d-4cc2-a8c7-990d1dc90b45)

### PrestaShop version(s) where the bug happened

1.7.8.2

**Comment by paulnoelcholot** [comment]
Hello @AR404lab,

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Thank you
