### ISSUE TITLE
Where the data is stored?

### ISSUE THREAD

**Issue by MajaMistrz** [PrestaShop/PrestaShop#35904]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have a question about this module. Where can I find the e-mails of people who left their accounts to be notified about the product being available for purchase again? Where the data of these people is stored?

### Steps to reproduce

1. the customer signs up for the notification
2. gets the notification
3. his email is not visible anywhere in Prestashop

### PrestaShop version(s) where the bug happened

1.7.2.4

### PHP version(s) where the bug happened

7.1.33

### If your bug is related to a module, specify its name and its version

ps_emailalerts, v2.2.1

### Your company or customer's name goes here (if applicable).

wdomu24.pl

**Comment by florine2623** [comment]
Hello @MajaMistrz ,

You can go to Advanced parameters > Database > Add a new SQL query and add this query : 

> SELECT * FROM `ps_mailalert_customer_oos`

And you will see something like that :

<img width="1225" alt="Screenshot 2024-04-12 at 15 55 47" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/8e6cc466-d97b-4fd9-b7d9-f1d3b981fc5d">

**Comment by MajaMistrz** [comment]
Unfortunately it's empty. Do you know why?
![sql](https://github.com/PrestaShop/PrestaShop/assets/166830460/10024d2e-e09e-4aa4-8765-761c682a316f)
