### ISSUE TITLE
`{html_select_date}` doesn't work in form-fields.tpl

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/PrestaShop#35900]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

https://smarty-php.github.io/smarty/4.x/designers/language-custom-functions/

Few of those work as expected eg. `{mailto}` or `{debug}`. Others have been used by PS themes for many years but honestly I can't remember them ever working as expected. For example `{html_select_date}` is supposed to generate a [set of selectors for day, month and year](https://smarty-php.github.io/smarty/4.x/designers/language-custom-functions/language-function-html-select-date/#exaples) but it only generates a simple text input:

![obraz](https://github.com/PrestaShop/PrestaShop/assets/5007456/b3f9a31c-e04a-4679-b274-f617ba75015a)

**Classic**:
https://github.com/PrestaShop/classic-theme/blob/842f4f602c3b1c9f12da952dcf957b15cbf4f09e/templates/_partials/form-fields.tpl#L116-L130

**Hummingbird**:
https://github.com/PrestaShop/hummingbird/blob/06ff161bf74ae0939fa676e814a60e31a7012e11/templates/_partials/form-fields.tpl#L105-L119

### Expected behavior

TBH I'm not sure we need these selectors for birthday anyway. Simple `type="date"` input would be better.

### Steps to reproduce

1. Go to **Create an account** page and check if birthday field is displayed as a set of 3 selectors

### PrestaShop version(s) where the bug happened

1.6, 1.7, 8.x, develop

**Comment by SharakPL** [comment]
I checked these functions on index.tpl and they work:

![obraz](https://github.com/PrestaShop/PrestaShop/assets/5007456/e7d77202-e84d-4a55-bc20-66cf49688b23)

Looks like this whole block is obsolete in all themes:
```php
      {elseif $field.type === 'birthday'}

        {block name='form_field_item_birthday'}
          <div class="js-parent-focus">
            {html_select_date
            field_order=DMY
            time={$field.value|default}
            field_array={$field.name}
            prefix=false
            reverse_years=true
            field_separator='<br>'
            day_extra='class="form-control form-control-select"'
            month_extra='class="form-control form-control-select"'
            year_extra='class="form-control form-control-select"'
            day_empty={l s='-- day --' d='Shop.Forms.Labels'}
            month_empty={l s='-- month --' d='Shop.Forms.Labels'}
            year_empty={l s='-- year --' d='Shop.Forms.Labels'}
            start_year={'Y'|date}-100 end_year={'Y'|date}
            }
          </div>
        {/block}

```
and birthday field is completely generated here:
https://github.com/PrestaShop/PrestaShop/blob/65cec328e709ba9527e35f428ea84fc938b0668e/classes/form/CustomerFormatter.php#L203-L219

**Comment by florine2623** [comment]
Hello @SharakPL ,

The birthdate field is displayed as an input and not 3 selectors.

ping @PrestaShop/product-council to have their opinion on that topic.

**Comment by kpodemski** [comment]
There is no need to do anything there. We don't use these functions since the birthday field is not type birthday but text, and the smarty function is working correctly. This condition maintains backward compatibility for those who want to use setType('birthday').
