### ISSUE TITLE
WHITE OR BLANK  PAGES ERROR

### ISSUE THREAD

**Issue by bambinounos** [PrestaShop/PrestaShop#35911]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Store does not load and instead it loads blank pages
The store was working properly.
We just update php with `sudo apt upgrade`
Error
[client 181.113.65.22:37434] PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /var/www/html/tiendakama/var/cache/prod/FrontContainer.php:2666\nStack trace:\n#0 /var/www/html/tiendakama/var/cac>
memcached is not installed but the store was working properly before some days
It does not matter what we need to load, it is blank and of couser the error is different.
Server is arm

### Expected behavior

The store should works perfecttly

### Steps to reproduce

load any page from the store, only works home page

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

7.4.3

**Comment by bambinounos** [comment]
I edited parameters.php file and I changed 'ps_cache_enable' => true, to 'ps_cache_enable' => false,
But it did not work

**Comment by bambinounos** [comment]
errors
Mon Apr 15 00:11:19.343273 2024] [php7:error] [pid 75800] [client 72.14.201.216:35717] PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /var/www/html/tiendakama/var/cache/prod/FrontContainer.php:2666\nStack trace:\n#0 /var/www/html/tiendakama/var/cac>
[Mon Apr 15 00:39:43.157264 2024] [php7:error] [pid 75782] [client 51.222.253.1:15972] PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /var/www/html/tiendakama/var/cache/prod/FrontContainer.php:2666\nStack trace:\n#0 /var/www/html/tiendakama/var/cach>
[Mon Apr 15 01:13:23.227372 2024] [php7:error] [pid 75800] [client 51.222.253.3:25160] PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /var/www/html/tiendakama/var/cache/prod/FrontContainer.php:2666\nStack trace:\n#0 /var/www/html/tiendakama/var/cach>
[Mon Apr 15 01:14:37.274941 2024] [php7:error] [pid 75782] [client 186.53.138.169:49291] PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /var/www/html/tiendakama/var/cache/prod/FrontContainer.php:2666\nStack trace:\n#0 /var/www/html/tiendakama/var/ca>
[Mon Apr 15 01:16:54.215028 2024] [php7:error] [pid 75785] [client 181.113.65.22:54292] PHP Fatal error:  Uncaught Symfony\\Component\\Debug\\Exception\\ClassNotFoundException: Attempted to load class "Memcached" from the global namespace.\nDid you forget a "use" sta>
[Mon Apr 15 01:17:26.349464 2024] [php7:error] [pid 76978] [client 181.113.65.22:60354] PHP Fatal error:  Uncaught Symfony\\Component\\Debug\\Exception\\ClassNotFoundException: Attempted to load class "Memcached" from the global namespace.\nDid you forget a "use" sta>
[Mon Apr 15 01:17:36.368167 2024] [php7:error] [pid 75800] [client 181.113.65.22:41726] PHP Fatal error:  Uncaught Symfony\\Component\\Debug\\Exception\\ClassNotFoundException: Attempted to load class "Memcached" from the global namespace.\nDid you forget a "use" sta>
[Mon Apr 15 01:17:39.321492 2024] [php7:error] [pid 75785] [client 193.186.4.218:42460] PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /var/www/html/tiendakama/var/cache/prod/FrontContainer.php:2666\nStack trace:\n#0 /var/www/html/tiendakama/var/cac>
[Mon Apr 15 01:17:51.258335 2024] [php7:error] [pid 76978] [client 181.113.65.22:41268] PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /var/www/html/tiendakama/var/cache/prod/FrontContainer.php:2666\nStack trace:\n#0 /var/www/html/tiendakama/var/cac>
[Mon Apr 15 01:19:42.814363 2024] [php7:error] [pid 77171] [client 181.113.65.22:52128] PHP Fatal error:  Uncaught Symfony\\Component\\Debug\\Exception\\ClassNotFoundException: Attempted to load class "Memcached" from the global namespace.\nDid you forget a "use" sta>
[Mon Apr 15 01:19:57.300107 2024] [php7:error] [pid 75784] [client 181.113.65.22:43670] PHP Fatal error:  Uncaught Symfony\\Component\\Debug\\Exception\\ClassNotFoundException: Attempted to load class "Memcached" from the global namespace.\nDid you forget a "use" sta>
[Mon Apr 15 01:20:16.224171 2024] [php7:error] [pid 75785] [client 181.113.65.22:45926] PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /var/www/html/tiendakama/var/cache/prod/FrontContainer.php:2666\nStack trace:\n#0 /var/www/html/tiendakama/var/cac>
[Mon Apr 15 01:21:58.437616 2024] [php7:error] [pid 75800] [client 181.113.65.22:36950] PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /var/www/html/tiendakama/var/cache/prod/FrontContainer.php:2666\nStack trace:\n#0 /var/www/html/tiendakama/var/cac>
[Mon Apr 15 01:25:59.317394 2024] [php7:error] [pid 75784] [client 181.113.65.22:39164] PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /var/www/html/tiendakama/var/cache/prod/FrontContainer.php:2666\nStack trace:\n#0 /var/www/html/tiendakama/var/cac>
[Mon Apr 15 01:26:01.555618 2024] [php7:error] [pid 77172] [client 181.113.65.22:39180] PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /var/www/html/tiendakama/var/cache/prod/FrontContainer.php:2666\nStack trace:\n#0 /var/www/html/tiendakama/var/cac>
[Mon Apr 15 01:32:46.731857 2024] [php7:error] [pid 77174] [client 181.113.65.22:37434] PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /var/www/html/tiendakama/var/cache/prod/FrontContainer.php:2666\nStack trace:\n#0 /var/www/html/tiendakama/var/cac>
[Mon Apr 15 01:41:27.931113 2024] [php7:error] [pid 75783] [client 181.113.65.22:47334] PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /var/www/html/tiendakama/var/cache/prod/FrontContainer.php:2666\nStack trace:\n#0 /var/www/html/tiendakama/var/cac>
[Mon Apr 15 01:41:51.887758 2024] [php7:error] [pid 77779] [client 181.113.65.22:35702] PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /var/www/html/tiendakama/var/cache/prod/FrontContainer.php:2666\nStack trace:\n#0 /var/www/html/tiendakama/var/cac>
[Mon Apr 15 01:57:41.445670 2024] [php7:error] [pid 77965] [client 181.113.65.22:42360] PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /var/www/html/tiendakama/var/cache/prod/FrontContainer.php:2666\nStack trace:\n#0 /var/www/html/tiendakama/var/cac>
[Mon Apr 15 02:02:39.282865 2024] [php7:error] [pid 77969] [client 181.113.65.22:56688] PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /var/www/html/tiendakama/var/cache/prod/FrontContainer.php:2666\nStack trace:\n#0 /var/www/html/tiendakama/var/cac>
[Mon Apr 15 02:02:55.224335 2024] [php7:error] [pid 77965] [client 181.113.65.22:54382] PHP Fatal error:  Uncaught Symfony\\Component\\Debug\\Exception\\ClassNotFoundException: Attempted to load class "Memcached" from the global namespace.\nDid you forget a "use" sta>
[Mon Apr 15 02:03:02.637857 2024] [php7:error] [pid 77966] [client 181.113.65.22:33142] PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /var/www/html/tiendakama/var/cache/prod/FrontContainer.php:2666\nStack trace:\n#0 /var/www/html/tiendakama/var/cac>
[Mon Apr 15 02:03:04.490584 2024] [php7:error] [pid 77967] [client 181.113.65.22:33146] PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /var/www/html/tiendakama/var/cache/prod/FrontContainer.php:2666\nStack trace:\n#0 /var/www/html/tiendakama/var/cac>
[Mon Apr 15 02:10:56.017518 2024] [php7:error] [pid 77965] [client 181.113.65.22:48872] PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /var/www/html/tiendakama/var/cache/prod/FrontContainer.php:2666\nStack trace:\n#0 /var/www/html/tiendakama/var/cac>
[Mon Apr 15 02:14:44.416530 2024] [php7:error] [pid 78224] [client 181.113.65.22:36644] PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /var/www/html/tiendakama/var/cache/prod/FrontContainer.php:2666\nStack trace:\n#0 /var/www/html/tiendakama/var/cac>
[Mon Apr 15 02:16:05.590196 2024] [php7:error] [pid 78224] [client 181.113.65.22:33826] PHP Fatal error:  Uncaught Symfony\\Component\\Debug\\Exception\\ClassNotFoundException: Attempted to load class "Memcached" from the global namespace.\nDid you forget a "use" sta>
[Mon Apr 15 02:16:32.666945 2024] [php7:error] [pid 78227] [client 181.113.65.22:51408] PHP Fatal error:  Uncaught Symfony\\Component\\Debug\\Exception\\ClassNotFoundException: Attempted to load class "Memcached" from the global namespace.\nDid you forget a "use" sta>
[Mon Apr 15 02:16:37.062998 2024] [php7:error] [pid 78228] [client 181.113.65.22:51424] PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /var/www/html/tiendakama/var/cache/prod/FrontContainer.php:2666\nStack trace:\n#0 /var/www/html/tiendakama/var/cac>
[Mon Apr 15 02:19:34.354464 2024] [php7:error] [pid 78228] [client 51.222.253.15:20608] PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in /var/www/html/tiendakama/var/cache/prod/FrontContainer.php:2666\nStack trace:\n#0 /var/www/html/tiendakama/var/cac>

**Comment by bambinounos** [comment]
The complete log file
[error_prestashop.log](https://github.com/PrestaShop/PrestaShop/files/14973328/error_prestashop.log)

**Comment by Hlavtox** [comment]
@bambinounos You just answered yourself with "We just update php with sudo apt upgrade". Fix your server configuration, then your shop will work. I think you should hire a specialist for this.

I would suggest trying to delete everything in /var/cache folders, not much more we can do for you. 👍

**Comment by paulnoelcholot** [comment]
Hello @bambinounos,

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Thank you

**Comment by bambinounos** [comment]
@Hlavtox when I wrote "We just update php with sudo apt upgrade" I meant the shop was ok, we did not do anything to damage it.
It just stopped working.
But I deleted the var/cache folders and it works. I do not understand what happened.
Thanks for your help
