### ISSUE TITLE
Shipping - Carriers - non-effective change of position

### ISSUE THREAD

**Issue by paulnoelcholot** [PrestaShop/PrestaShop#35932]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Modifying the positioning of carriers in the BO is not taken into account in the FO

### Expected behavior

modifying the positioning of carriers in the BO should be taken into account in the FO

### Steps to reproduce

1. On FO add a product in cart
2. Proceed to checkout
3. Go to shipping method 
4. See the order
5. On BO > Shipping > Carriers
6. Change the positions of Carriers
7. On FO > refresh the page
8. Error

### PrestaShop version(s) where the bug happened

8.1.5

**Comment by AureRita** [comment]
Hi @paulnoelcholot 

Thank you for your report, Despite my effort, I can't reproduce your issue as you can see : 

[recording(190).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/a879ad7a-908f-4705-ba84-825db0fe79f1)

[recording(191).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/f24238ef-d012-495e-99dc-4c4a60f1aab2)

Did I miss something ? 

Waiting for feedback
