### ISSUE TITLE
Bug on module "products of the same category"

### ISSUE THREAD

**Issue by DTStudio38** [PrestaShop/PrestaShop#35949]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The module displays only the first frame with product information.
The others, there is only the image but not the information.
![bug site](https://github.com/PrestaShop/PrestaShop/assets/166630021/a5cfa5e7-5514-4469-946d-2b22338c80cf)

### Expected behavior

Have a module to install with an update that eliminates the bug

### Steps to reproduce

J'ai désactivé le module mais avant je voyais ça sur la page produit

### PrestaShop version(s) where the bug happened

1.7.8.11

**Comment by florine2623** [comment]
This is not an issue with PrestaShop.

The issue might come from your template or a third-party module.

I suggest you to contact directly the developer of the module.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
