### ISSUE TITLE
 Hyphen after every product name in order_conf e-mail

### ISSUE THREAD

**Issue by ComonSoft** [PrestaShop/PrestaShop#35942]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the order confirmation mail received by the customer, every product as an hyphen - added at the and of each product name.
![image](https://github.com/PrestaShop/PrestaShop/assets/13507563/3205e3ab-9da6-4ee9-9174-047f5f887123)

### Expected behavior

Normally the hyphen is only added when product has a combination, like : Product name - Size - Color
Should be
![image](https://github.com/PrestaShop/PrestaShop/assets/13507563/eae2455c-7d64-4d19-b90b-50c57eaaebd1)

### Steps to reproduce

1/ Add products to cart with and without combination
2/ Place order
3/ See confirmation order mail

### PrestaShop version(s) where the bug happened

1.7.8.11 to 8.1.5

### PHP version(s) where the bug happened

7.4

### Your company or customer's name goes here (if applicable).

@ComonSoft

**Comment by florine2623** [comment]
Hello @ComonSoft ,

I reproduce the issue with PrestaShop version 8.1.x, develop, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by ComonSoft** [comment]
Hi,

 

This is already done https://github.com/PrestaShop/PrestaShop/pull/35943 :-) 

 

Best Regards

Jean

 

De : florine2623 ***@***.***> 
Envoyé : mercredi 17 avril 2024 09:27
À : PrestaShop/PrestaShop ***@***.***>
Cc : ComonSoft ***@***.***>; Mention ***@***.***>
Objet : Re: [PrestaShop/PrestaShop] Hyphen after every product name in order_conf e-mail (Issue #35942)

 

Hello @ComonSoft <https://github.com/ComonSoft>  ,

I reproduce the issue with PrestaShop version 8.1.x, develop, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider contacting a professional <https://www.prestashop-project.org/support/>  to help you.

If you fix the issue on your end, please contribute it back to the project <https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/> . Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
