### ISSUE TITLE
[BO]On changing status order it show "Token not valid" only in multishop in "all sites"

### ISSUE THREAD

**Issue by tone87** [PrestaShop/PrestaShop#35956]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I change the order status in the administration page of a single order, it shows the "invalid token" page (compromised)
This error is only shown to me in "all sites" mode, but if I select only one shop it doesn't happen to me.
it's very annoying.
To rule out that the problem was caused by a module or an override, I disabled all modules and deleted the overrides folder, also deleting every module in the modules folder.
I've always had this error since I updated to version 8 of prestashop. and even now that I have version 8.1.5 the error occurs.

### Steps to reproduce

1. enter the backoffice in "all shop" mode
1. take an order in the backoffice order list
2. open the single order
3. change the order status from the drop-down menu at the top
4. confirm the change of state
5. Invalid token error is shown

### PrestaShop version(s) where the bug happened

8.0 -> 8.1.5

### PHP version(s) where the bug happened

8.1.28

**Comment by AureRita** [comment]
Hi @tone87 

Thank you for your report, Despite my effort, I can't reproduce your issue as you can see : 

[recording(194).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/55f1390b-f3a3-4904-8dbd-42ace275b182)

Did I miss something ? 

Is it the only issue that you do ? did you take many time to do this issue ? 

Can you provide us a video to sse your issue ? 

Waiting for feedback

**Comment by tone87** [comment]
Yes, with a clean installation i tried and it works .. i confirm ... i don't know where are the problem because i removed all modules and overrides in staging version.
maybe is somethings in database ? 
video in attachment
[token_not_valid.webm](https://github.com/PrestaShop/PrestaShop/assets/8173557/206d35ac-74f5-45eb-96c3-c8819b46cb1b)

**Comment by tone87** [comment]
also i check if there are files edited .. but not for that section .. i don't know .
![Screenshot 2024-04-19 165123](https://github.com/PrestaShop/PrestaShop/assets/8173557/d390224a-e51d-4500-9ad6-8a9d83ba438c)

**Comment by tone87** [comment]
I also noticed that it says "invalid token"
when I switch from single shop mode to all shop mode in all sections of the backoffice.
what can influence this?
I suspect something in the database, but I don't know where.
In a clean and new installation it does not give the same problem

**Comment by florine2623** [comment]
This is an issue that is not occurring on PS Open Source Project.
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. 

You can contact the support directly from your BO.

I'm closing your issue.
Thanks!

**Comment by tone87** [comment]
i found the bug... i haved a double configuration stored in database table _configuration , the name is PS_SECURITY_TOKEN ... i deleted one row and now it's all ok 

I think I was dragging this error from various updates and I never noticed it
