### ISSUE TITLE
[BO] Products - Bad date creation on copy

### ISSUE THREAD

**Issue by ytilotti** [PrestaShop/PrestaShop#35958]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On the copy of product, the creation date is still like the product copied. 

Fields in database :
- date_add on ps_product
- date_add on ps_product_shop

### Expected behavior

The date need to be at now.

### Steps to reproduce

1. Go to admin and log in
2. Create a product at day 1
3. Create a product at day 2
4. Copy the product of day 1 in day 3 **OR** check in database on the copied product

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8

### Your company or customer's name goes here (if applicable).

Yneet

**Comment by matks** [comment]
@ytilotti have a look at https://github.com/PrestaShop/PrestaShop/pull/35645 😉

**Comment by florine2623** [comment]
@ytilotti ,

Could you confirm that the PR fixes your issue ?

**Comment by ytilotti** [comment]
@jolelievre on your PR, date_add will be deprecated? Warning on pagination[default_order_by] on configuration products.
@florine2623 I review the PR code and it seems that this solves the problem.

**Comment by cerodesign** [comment]
Same isue. When you try to create product by copping the old one, for extample from old product from 2023, the new product will have create data 2023 and will never been set and new one. 
This is in all 8.X versions. also in 8.1.5.
@ytilotti : what do you meen by  "I review the PR code and it seems that this solves the problem." did you solved the problem?

**Comment by ytilotti** [comment]
@cerodesign, the PR shared by @matks : https://github.com/PrestaShop/PrestaShop/pull/35645

**Comment by cerodesign** [comment]
> @cerodesign, the PR shared by @matks : #35645

Sorry ytilotti but which code changes worked for you? I tried those from [jolelievre]. And it make arror for me during product copying.

**Comment by Hlavtox** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/34079
