### ISSUE TITLE
Empty meta title, description ans keywords

### ISSUE THREAD

**Issue by Georgitht** [PrestaShop/PrestaShop#35955]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Empty meta title, meta description ans meta keywords in frontoffice with cms pages, category pages and product pages.
Any idea about this issue ?

### Steps to reproduce

Go to

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

7.4.33

**Comment by paulnoelcholot** [comment]
Hello @Georgitht

Could you please provide us with more info ?
We need Expected behavior and Step to reproduce to understand how we can reproduce your issue.

You don't know how to get this information? Please read the following article: [How to create a bug report](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/).

Thank you

**Comment by Georgitht** [comment]
Hi,

Thank you for your reply.

The issue appears when i display pages in frontoffice. Many pages (cms 
pages, category pages, product pages) haven't got any meta title, meta 
description neither meta keywords.
I remember having the same issue in 2010 with 1.5.4 version of 
Prestashop. The team sent me a patch to solve this issue.

Thank you


Le 2024-04-18 10:27, Paul-Noël a écrit :

**Comment by Georgitht** [comment]
Hi,

The steps to reproduce are very basics. Display a cms page for example 
to see there are no meta tags. That's all.

Please, could you tell me what information is missing to reproduce the 
issue ?


Le 2024-04-18 10:27, Paul-Noël a écrit :

**Comment by Georgitht** [comment]
More information:
Informations du serveur : Linux #1 SMP Wed Nov 30 08:49:06 UTC 2022 
x86_64
Version du logiciel serveur : Apache
Version de PHP : 7.4.33
Limite de mémoire : 512M
Temps maximal d'exécution : 165
Version de PrestaShop : 8.1.5
Version de MySQL : 5.7.42-log
Moteur MySQL : InnoDB
Connecteur MySQL : DbPDO

**Comment by florine2623** [comment]
Hello @Georgitht ,

I can't reproduce your issue.
<img width="1428" alt="Screenshot 2024-04-22 at 09 57 34" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/c90124d5-ff99-4dae-aa3e-e1c0517ee72d">

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
