### ISSUE TITLE
Core Error: SessionHandler::open(): Cannot call default session handler after Manuale Upgrade from 1.7.8.10 to 1.7.8.11 using PHP7.4

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#35965]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After upgrading from 1.7.8.10 to 1.7.8.11 i'm unable to use the back office with php 7.4

![image](https://github.com/PrestaShop/PrestaShop/assets/24798703/d16ecb14-82ea-4023-911b-e170666eb3e9)

`session.save_handler = redis
session.save_path = "tcp://redb01.XXXX.internal:6379?auth=XXXX"`

Same config work in front-end and with php7.2 also in back end.

`2024-04-18 12:37:10.106298 [NOTICE] [2189816] [T0] [10.132.0.9:47114#XXX] [STDERR] PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalErrorException: Core Error: SessionHandler::open(): Cannot call default session handler in Unknown:0\nStack trace:\n#0 {main}\n\nNext Symfony\Component\Filesystem\Exception\IOException: Failed to create "yaml": mkdir(): Permission denied in /var/www/html/XXX/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:104\nStack trace:\n#0 /var/www/html/XXX/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php(676): Symfony\Component\Filesystem\Filesystem->mkdir()\n#1 /var/www/html/XXX/vendor/symfony/symfony/src/Symfony/Component/Config/ResourceCheckerConfigCache.php(124): Symfony\Component\Filesystem\Filesystem->dumpFile()\n#2 /var/www/html/XXX/src/Core/Util/File/YamlParser.php(92): Symfony\Component\Config\ResourceCheckerConfigCache->write()\n#3 /var/www/html/XXX/src/Core/Addon/Theme/Theme.php(43): PrestaShop\PrestaShop\Core\Util\File\YamlParse in /var/www/html/XXX/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php on line 104\n
`

### Steps to reproduce

1) Manual upgrade from 1.7.8.10 to 1.7.8.11 
2) Try to open back office with php 7.4 

### PrestaShop version(s) where the bug happened

1.7.8.11

**Comment by matteolavaggi** [comment]
Some more info with php 8.1 (i know its not supported):
<html>
<body>

(1/1) FatalThrowableErrorCannot call default session handler
--
in StrictSessionHandler.php line 40
at SessionHandler->open()in StrictSessionHandler.php line 40
at StrictSessionHandler->open()in SessionHandlerProxy.php line 43
at SessionHandlerProxy->open()
at session_start()in NativeSessionStorage.php line 154
at NativeSessionStorage->start()in Session.php line 57
at Session->start()in SessionTokenStorage.php line 78
at SessionTokenStorage->hasToken()in CsrfTokenManager.php line 72
at CsrfTokenManager->getToken()in Router.php line 64
at Router->generate()in Link.php line 844
at LinkCore->getAdminLink()in AdminController.php line 2734
at AdminControllerCore->setMedia()in AdminDashboardController.php line 44
at AdminDashboardControllerCore->setMedia()in Controller.php line 291
at ControllerCore->run()in Dispatcher.php line 525
at DispatcherCore->dispatch()in index.php line 93


</body>
</html>(1/1) FatalThrowableError
Cannot call default session handler

in [StrictSessionHandler.php line 40](https://XXX/admin/index.php?controller=AdminDashboard&token=5775614e8a17e0e15727d4a35f8e264e)
at SessionHandler->open()
in [StrictSessionHandler.php line 40](https://XXX/admin/index.php?controller=AdminDashboard&token=5775614e8a17e0e15727d4a35f8e264e)
at StrictSessionHandler->open()
in [SessionHandlerProxy.php line 43](https://XXX/admin/index.php?controller=AdminDashboard&token=5775614e8a17e0e15727d4a35f8e264e)
at SessionHandlerProxy->open()
at session_start()
in [NativeSessionStorage.php line 154](https://XXX/admin/index.php?controller=AdminDashboard&token=5775614e8a17e0e15727d4a35f8e264e)
at NativeSessionStorage->start()
in [Session.php line 57](https://XXX/admin/index.php?controller=AdminDashboard&token=5775614e8a17e0e15727d4a35f8e264e)
at Session->start()
in [SessionTokenStorage.php line 78](https://XXX/admin/index.php?controller=AdminDashboard&token=5775614e8a17e0e15727d4a35f8e264e)
at SessionTokenStorage->hasToken()
in [CsrfTokenManager.php line 72](https://XXX/admin/index.php?controller=AdminDashboard&token=5775614e8a17e0e15727d4a35f8e264e)
at CsrfTokenManager->getToken()
in [Router.php line 64](https://XXX/admin/index.php?controller=AdminDashboard&token=5775614e8a17e0e15727d4a35f8e264e)
at Router->generate()
in [Link.php line 844](https://XXX/admin/index.php?controller=AdminDashboard&token=5775614e8a17e0e15727d4a35f8e264e)
at LinkCore->getAdminLink()
in [AdminController.php line 2734](https://XXX/admin/index.php?controller=AdminDashboard&token=5775614e8a17e0e15727d4a35f8e264e)
at AdminControllerCore->setMedia()
in [AdminDashboardController.php line 44](https://XXX/admin/index.php?controller=AdminDashboard&token=5775614e8a17e0e15727d4a35f8e264e)
at AdminDashboardControllerCore->setMedia()
in [Controller.php line 291](https://XXX/admin/index.php?controller=AdminDashboard&token=5775614e8a17e0e15727d4a35f8e264e)
at ControllerCore->run()
in [Dispatcher.php line 525](https://XXX/admin/index.php?controller=AdminDashboard&token=5775614e8a17e0e15727d4a35f8e264e)
at DispatcherCore->dispatch()
in [index.php line 93](https://XXX/admin/index.php?controller=AdminDashboard&token=5775614e8a17e0e15727d4a35f8e264e)

Seem that only php7.2 work

**Comment by AureRita** [comment]
Hi @matteolavaggi 

Thank for your report,
This issue is too technical for me, ping @PrestaShop/prestashop-core-developers, can someone please reproduce this issue ? 

Thanks

**Comment by matteolavaggi** [comment]
Problem with auto upgrade module are terrible difficult to debug. Suggest clean install and migration of db and module.
