### ISSUE TITLE
Unknown column 'product_type' in 'field list'<br /><br /><pre>INSERT INTO `ps_product` AFTER MANUAL UPGRADE from 1.7.8.10 to 1.7.8.11

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#35964]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Unknown column 'product_type' in 'field list'<br /><br /><pre>INSERT INTO `ps_product` (`id_shop_default`, `id_manufacturer`, `id_supplier`, `reference`, `supplier_reference`, `location`, `width`, `height`, `depth`, `weight`, `quantity_discount`, `ean13`, `isbn`, `upc`, `mpn`, `cache_is_pack`, `cache_has_attachments`, `is_virtual`, `state`, `additional_delivery_times`, `product_type`, `id_category_default`, `id_tax_rules_group`, `on_sale`, `online_only`, `ecotax`, `minimal_quantity`, `low_stock_threshold`, `low_stock_alert`, `price`, `wholesale_price`, `unity`, `unit_price_ratio`, `additional_shipping_cost`, `customizable`, `text_fields`, `uploadable_files`, `active`, `redirect_type`, `id_type_redirected`, `available_for_order`, `available_date`, `show_condition`, `condition`, `show_price`, `indexed`, `visibility`, `cache_default_attribute`, `advanced_stock_management`, `date_add`, `date_upd`, `pack_stock_type`) VALUES ('1', '0', '0', '', '', '', '0', '0', '0', '0', '0', '', '', '', '', '0', '0', '0', '0', '1', '', '2', '1', '0', '0', '0', '1', NULL, '0', '0', '0', '', '0', '0', '0', '0', '0', '1', '404', '0', '1', '0000-00-00', '0', 'new', '1', '0', 'both', '0', '0', '2024-04-18 14:04:44', '2024-04-18 14:04:44', '3')</pre>
ExceptionLogs 2Stack Trace
PrestaShopDatabaseException
in [classes/db/Db.php](https://ps1788.matteolavaggi.it/admin372wt46of/index.php/_profiler/open?_token=G2vjdcVr_twmi680LYxurIQ7jwFQV-9s1mJx0tzZ4vw?file=classes/db/Db.php&line=769#line769) (line 769)
        if ($webservice_call && $errno) {            $dbg = debug_backtrace();            WebserviceRequest::getInstance()->setError(500, '[SQL Error] ' . $this->getMsgError() . '. From ' . (isset($dbg[3]['class']) ? $dbg[3]['class'] : '') . '->' . $dbg[3]['function'] . '() Query was : ' . $sql, 97);        } elseif (_PS_DEBUG_SQL_ && $errno && !defined('PS_INSTALLATION_IN_PROGRESS')) {            if ($sql) {                throw new PrestaShopDatabaseException($this->getMsgError() . '<br /><br /><pre>' . $sql . '</pre>');            }            throw new PrestaShopDatabaseException($this->getMsgError());        }    }
DbCore->displayError('INSERT INTO `ps_product` (`id_shop_default`, `id_manufacturer`, `id_supplier`, `reference`, `supplier_reference`, `location`, `width`, `height`, `depth`, `weight`, `quantity_discount`, `ean13`, `isbn`, `upc`, `mpn`, `cache_is_pack`, `cache_has_attachments`, `is_virtual`, `state`, `additional_delivery_times`, `product_type`, `id_category_default`, `id_tax_rules_group`, `on_sale`, `online_only`, `ecotax`, `minimal_quantity`, `low_stock_threshold`, `low_stock_alert`, `price`, `wholesale_price`, `unity`, `unit_price_ratio`, `additional_shipping_cost`, `customizable`, `text_fields`, `uploadable_files`, `active`, `redirect_type`, `id_type_redirected`, `available_for_order`, `available_date`, `show_condition`, `condition`, `show_price`, `indexed`, `visibility`, `cache_default_attribute`, `advanced_stock_management`, `date_add`, `date_upd`, `pack_stock_type`) VALUES (\'1\', \'0\', \'0\', \'\', \'\', \'\', \'0\', \'0\', \'0\', \'0\', \'0\', \'\', \'\', \'\', \'\', \'0\', \'0\', \'0\', \'0\', \'1\', \'\', \'2\', \'1\', \'0\', \'0\', \'0\', \'1\', NULL, \'0\', \'0\', \'0\', \'\', \'0\', \'0\', \'0\', \'0\', \'0\', \'1\', \'404\', \'0\', \'1\', \'0000-00-00\', \'0\', \'new\', \'1\', \'0\', \'both\', \'0\', \'0\', \'2024-04-18 14:04:44\', \'2024-04-18 14:04:44\', \'3\')')
in [classes/db/Db.php](https://ps1788.matteolavaggi.it/admin372wt46of/index.php/_profiler/open?_token=G2vjdcVr_twmi680LYxurIQ7jwFQV-9s1mJx0tzZ4vw?file=classes/db/Db.php&line=385#line385) (line 385)
DbCore->query('INSERT INTO `ps_product` (`id_shop_default`, `id_manufacturer`, `id_supplier`, `reference`, `supplier_reference`, `location`, `width`, `height`, `depth`, `weight`, `quantity_discount`, `ean13`, `isbn`, `upc`, `mpn`, `cache_is_pack`, `cache_has_attachments`, `is_virtual`, `state`, `additional_delivery_times`, `product_type`, `id_category_default`, `id_tax_rules_group`, `on_sale`, `online_only`, `ecotax`, `minimal_quantity`, `low_stock_threshold`, `low_stock_alert`, `price`, `wholesale_price`, `unity`, `unit_price_ratio`, `additional_shipping_cost`, `customizable`, `text_fields`, `uploadable_files`, `active`, `redirect_type`, `id_type_redirected`, `available_for_order`, `available_date`, `show_condition`, `condition`, `show_price`, `indexed`, `visibility`, `cache_default_attribute`, `advanced_stock_management`, `date_add`, `date_upd`, `pack_stock_type`) VALUES (\'1\', \'0\', \'0\', \'\', \'\', \'\', \'0\', \'0\', \'0\', \'0\', \'0\', \'\', \'\', \'\', \'\', \'0\', \'0\', \'0\', \'0\', \'1\', \'\', \'2\', \'1\', \'0\', \'0\', \'0\', \'1\', NULL, \'0\', \'0\', \'0\', \'\', \'0\', \'0\', \'0\', \'0\', \'0\', \'1\', \'404\', \'0\', \'1\', \'0000-00-00\', \'0\', \'new\', \'1\', \'0\', \'both\', \'0\', \'0\', \'2024-04-18 14:04:44\', \'2024-04-18 14:04:44\', \'3\')')
in [classes/db/Db.php](https://ps1788.matteolavaggi.it/admin372wt46of/index.php/_profiler/open?_token=G2vjdcVr_twmi680LYxurIQ7jwFQV-9s1mJx0tzZ4vw?file=classes/db/Db.php&line=740#line740) (line 740)
DbCore->q('INSERT INTO `ps_product` (`id_shop_default`, `id_manufacturer`, `id_supplier`, `reference`, `supplier_reference`, `location`, `width`, `height`, `depth`, `weight`, `quantity_discount`, `ean13`, `isbn`, `upc`, `mpn`, `cache_is_pack`, `cache_has_attachments`, `is_virtual`, `state`, `additional_delivery_times`, `product_type`, `id_category_default`, `id_tax_rules_group`, `on_sale`, `online_only`, `ecotax`, `minimal_quantity`, `low_stock_threshold`, `low_stock_alert`, `price`, `wholesale_price`, `unity`, `unit_price_ratio`, `additional_shipping_cost`, `customizable`, `text_fields`, `uploadable_files`, `active`, `redirect_type`, `id_type_redirected`, `available_for_order`, `available_date`, `show_condition`, `condition`, `show_price`, `indexed`, `visibility`, `cache_default_attribute`, `advanced_stock_management`, `date_add`, `date_upd`, `pack_stock_type`) VALUES (\'1\', \'0\', \'0\', \'\', \'\', \'\', \'0\', \'0\', \'0\', \'0\', \'0\', \'\', \'\', \'\', \'\', \'0\', \'0\', \'0\', \'0\', \'1\', \'\', \'2\', \'1\', \'0\', \'0\', \'0\', \'1\', NULL, \'0\', \'0\', \'0\', \'\', \'0\', \'0\', \'0\', \'0\', \'0\', \'1\', \'404\', \'0\', \'1\', \'0000-00-00\', \'0\', \'new\', \'1\', \'0\', \'both\', \'0\', \'0\', \'2024-04-18 14:04:44\', \'2024-04-18 14:04:44\', \'3\')', true)
in [classes/db/Db.php](https://ps1788.matteolavaggi.it/admin372wt46of/index.php/_profiler/open?_token=G2vjdcVr_twmi680LYxurIQ7jwFQV-9s1mJx0tzZ4vw?file=classes/db/Db.php&line=476#line476) (line 476)
DbCore->insert('ps_product', array(array('id_shop_default' => 1, 'id_manufacturer' => 0, 'id_supplier' => 0, 'reference' => '', 'supplier_reference' => '', 'location' => '', 'width' => 0.0, 'height' => 0.0, 'depth' => 0.0, 'weight' => 0.0, 'quantity_discount' => 0, 'ean13' => '', 'isbn' => '', 'upc' => '', 'mpn' => '', 'cache_is_pack' => 0, 'cache_has_attachments' => 0, 'is_virtual' => 0, 'state' => 0, 'additional_delivery_times' => 1, 'product_type' => '', 'id_category_default' => 2, 'id_tax_rules_group' => 1, 'on_sale' => 0, 'online_only' => 0, 'ecotax' => 0.0, 'minimal_quantity' => 1, 'low_stock_threshold' => array('type' => 'sql', 'value' => 'NULL'), 'low_stock_alert' => 0, 'price' => 0.0, 'wholesale_price' => 0.0, 'unity' => '', 'unit_price_ratio' => 0, 'additional_shipping_cost' => 0.0, 'customizable' => 0, 'text_fields' => 0, 'uploadable_files' => 0, 'active' => 1, 'redirect_type' => '404', 'id_type_redirected' => 0, 'available_for_order' => 1, 'available_date' => '0000-00-00', 'show_condition' => 0, 'condition' => 'new', 'show_price' => 1, 'indexed' => 0, 'visibility' => 'both', 'cache_default_attribute' => 0, 'advanced_stock_management' => 0, 'date_add' => '2024-04-18 14:04:44', 'date_upd' => '2024-04-18 14:04:44', 'pack_stock_type' => 3)), false)
in [classes/ObjectModel.php](https://ps1788.matteolavaggi.it/admin372wt46of/index.php/_profiler/open?_token=G2vjdcVr_twmi680LYxurIQ7jwFQV-9s1mJx0tzZ4vw?file=classes/ObjectModel.php&line=578#line578) (line 578)
ObjectModelCore->add(true, false)
in [classes/Product.php](https://ps1788.matteolavaggi.it/admin372wt46of/index.php/_profiler/open?_token=G2vjdcVr_twmi680LYxurIQ7jwFQV-9s1mJx0tzZ4vw?file=classes/Product.php&line=782#line782) (line 782)
ProductCore->add(true, false)
in [classes/ObjectModel.php](https://ps1788.matteolavaggi.it/admin372wt46of/index.php/_profiler/open?_token=G2vjdcVr_twmi680LYxurIQ7jwFQV-9s1mJx0tzZ4vw?file=classes/ObjectModel.php&line=535#line535) (line 535)
ObjectModelCore->save()
in [src/PrestaShopBundle/Controller/Admin/ProductController.php](https://ps1788.matteolavaggi.it/admin372wt46of/index.php/_profiler/open?_token=G2vjdcVr_twmi680LYxurIQ7jwFQV-9s1mJx0tzZ4vw?file=src/PrestaShopBundle/Controller/Admin/ProductController.php&line=431#line431) (line 431)
ProductController->newAction()
in [vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php](https://ps1788.matteolavaggi.it/admin372wt46of/index.php/_profiler/open?_token=G2vjdcVr_twmi680LYxurIQ7jwFQV-9s1mJx0tzZ4vw?file=vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php&line=151#line151) (line 151)
HttpKernel->handleRaw(object(Request), 1)
in [vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php](https://ps1788.matteolavaggi.it/admin372wt46of/index.php/_profiler/open?_token=G2vjdcVr_twmi680LYxurIQ7jwFQV-9s1mJx0tzZ4vw?file=vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php&line=68#line68) (line 68)
HttpKernel->handle(object(Request), 1, false)
in [vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php](https://ps1788.matteolavaggi.it/admin372wt46of/index.php/_profiler/open?_token=G2vjdcVr_twmi680LYxurIQ7jwFQV-9s1mJx0tzZ4vw?file=vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php&line=200#line200) (line 200)
Kernel->handle(object(Request), 1, false)
in [admin372wt46of/index.php](https://ps1788.matteolavaggi.it/admin372wt46of/index.php/_profiler/open?_token=G2vjdcVr_twmi680LYxurIQ7jwFQV-9s1mJx0tzZ4vw?file=admin372wt46of/index.php&line=82#line82) (line 82)

### Expected behavior

All the field of ps_product need to be created during the post-upgrade script launch.

### Steps to reproduce

1) Manual upgrade from 1.7.8.10 to 1.7.8.11 using this guide https://devdocs.prestashop-project.org/1.7/basics/keeping-up-to-date/upgrade/
2) Run database upgrade with http://<shop_domain>/install/upgrade/upgrade.php
3) Get error code Error #32: No upgrade needs to be applied. -> This seem to be an "ok" code, its not very good to use an error code to notify it
4) Try to add a new product result in a missing table field product_type

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

7.2

**Comment by matteolavaggi** [comment]
Also related to this issue:
product_type field, after manual creating it, are not update for "standard":

Virtual
![image](https://github.com/PrestaShop/PrestaShop/assets/24798703/ca6bb408-8060-4907-8da8-9cd1ba189dfb)
![image](https://github.com/PrestaShop/PrestaShop/assets/24798703/07aa1605-2426-4d21-ba81-530c330f41e5)

Pack
![image](https://github.com/PrestaShop/PrestaShop/assets/24798703/ae81f741-8d1e-4d71-8f77-3696407c188b)
![image](https://github.com/PrestaShop/PrestaShop/assets/24798703/ec599838-8a7b-483b-aa5e-fcfc6ebe027d)

Standard
![image](https://github.com/PrestaShop/PrestaShop/assets/24798703/0758eee5-ab62-4746-97f5-19b6e94096b7)
value are not changed
![image](https://github.com/PrestaShop/PrestaShop/assets/24798703/035195d2-1257-4bef-a638-04d178f898e9)

on first save value is empty:
![image](https://github.com/PrestaShop/PrestaShop/assets/24798703/dc6d0506-c2b6-401d-bd69-4d06d95ca1f1)

**Comment by AureRita** [comment]
Hi @matteolavaggi 

Thank for your report,
This issue is too technical for me, ping @PrestaShop/tech-council , can someone please reproduce this issue ? 

Thanks

**Comment by kpodemski** [comment]
Hello @matteolavaggi 

Something went wrong during your manual upgrade. The `product_type` field is only used by the new product page, which was enabled for PrestaShop 8.1. On PrestaShop 1.7.8, it was in the early experimental phase.

A few other things to remember:
- there was no need to upgrade database between 1.7.8.10 and 1.7.8.11, see that there's no SQL upgrade available https://github.com/PrestaShop/autoupgrade/tree/dev/upgrade/sql 
- Unfortunately, the manual upgrade method doesn't work correctly anymore, it's recommended to use CLI upgrade as described [in the newer version of the documentation ](https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/upgrade/#manual-upgrade)

I suggest reverting your shop to 1.7.8.10 and [applying only the changed files](https://github.com/PrestaShop/PrestaShop/compare/1.7.8.10...1.7.8.11) if you want to do the upgrade manually.

**Comment by matteolavaggi** [comment]
Hello @kpodemski thanks for your reply, i need some more information because i cant really understand well your suggestion.

When you say "The product_type field is only used by the new product page, which was enabled for PrestaShop 8.1" , and "Something went wrong during your manual upgrade" there is a lack of information, i've downloaded the official 1.7.8.11 zip package from official web page reposistory and extracted it, how its possible that in this package there are core modification for a future version of PS (8.1) ?!

When you say "there was no need to upgrade database between 1.7.8.10 and 1.7.8.11" i agree, the upgrade procedure say there is nothing to upgrade but the zip package released from prestashop.com contain file that NEED a database upgrade, so i'm a bit confused.

When you say "Unfortunately, the manual upgrade method doesn't work correctly" , where this is explained? I can find a online official guide here "https://devdocs.prestashop-project.org/1.7/basics/keeping-up-to-date/upgrade/" that explain exactly how to do a manual upgrade, without any information or alert on the deprecation of this procedure.

When you say "it's recommended to use CLI upgrade as described [in the newer version of the documentation](https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/upgrade/#manual-upgrade)" , i CANT find any support on CLI with ps lower than 8.0 , there is no cli script at all , so i dont think we can upgrade 1.7.8.10 to 1.7.8.11 with CLI.

At least, 1.7.8.11 is a security update, but...

There is no way to upgrade it using manual upgrade
There is no way to upgrade using CLI

So how we can apply the patch to 1.7.8.10 ?

**Comment by matteolavaggi** [comment]
Any more information? it is very serious that the last release of a project before the transition to a new version is not updatable

**Comment by kpodemski** [comment]
@matteolavaggi it is upgradable, you can use autoupgrade module or as I mentioned you can only replace the files manually and that will be enough

**Comment by matteolavaggi** [comment]
Hi, i've replaced the file manually and the result Is that some core file
ask for a database field that does not exist in that release db schema, how
can you call this "upgradable" ? Somewhere there Is dev code in the 17811
official repo.

So please correct me if in wrong but if i download a 17810 repo and i'm
able tò run It, when i replaced file from 17811 into It, i get a database
schema error that must not exist until the 81 there Is something very
Dangerous in the official repository!

This for me Is a problem that male unable to upgrade from 10 to 11!

Some file MODIFIED from .10 to .11 (so the One you Say me to manually Copy)
contain dev code that can not be run with original database schema.

Il Mar 23 Apr 2024, 15:31 Krystian Podemski ***@***.***> ha
scritto:

**Comment by kpodemski** [comment]
Your original error says:
Unknown column 'product_type' in 'field list'

And the `product_type` column should be added in 1.7.8.0 upgrade:

https://github.com/PrestaShop/autoupgrade/blob/dev/upgrade/sql/1.7.8.0.sql#L172-L180

This means that you had a broken database structure before this upgrade or did something unexpected in one of the previous attempts to upgrade PrestaShop.

**Comment by kpodemski** [comment]
> Some file MODIFIED from .10 to .11 (so the One you Say me to manually Copy)
contain dev code that can not be run with original database schema.

That's not true. In the link I provided you:
https://github.com/PrestaShop/PrestaShop/compare/1.7.8.10...1.7.8.11

There are no changes related to the `product_type`. Product type has been added way back in 1.7.8.0.

**Comment by matteolavaggi** [comment]
FYI 1.7.8 was upgraded with one click upgrade... But 1 click upgrade does
not work with redis cache due to a 3 years old bug... Btw if you are
satisfied with the upgrade procedure, good for you , close this issue.

Il Mar 23 Apr 2024, 16:18 Krystian Podemski ***@***.***> ha
scritto:

**Comment by kpodemski** [comment]
I don't think upgrading your store with Redis enabled is wise :)

**Comment by matteolavaggi** [comment]
Redis is a session handler for php, if you know a way to use prestshop
without php session make me a call.

Il Mar 23 Apr 2024, 16:58 Krystian Podemski ***@***.***> ha
scritto:
