### ISSUE TITLE
Mutlinvoice Number for each Shop

### ISSUE THREAD

**Issue by huyhoang8398** [PrestaShop/PrestaShop#35973]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Do we have the feature to have multi invoice number in each shop? on both prestashop 1.7.8.x and prestashop 8?

### Steps to reproduce

1. Specify Invoice number for each shop

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

php 7.4

### Your company or customer's name goes here (if applicable).

AgileBio

**Comment by florine2623** [comment]
Hello @huyhoang8398 ,

You can specify an invoice prefix for each shop in Orders > Invoices > Invoices options :

<img width="1437" alt="Screenshot 2024-04-22 at 10 13 50" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/78233f5d-3ec3-4bfc-8cba-ddbf3755bb19">


Also, ou will find all the multi invoice related issues here : https://github.com/PrestaShop/PrestaShop/issues/21100

Thanks!

**Comment by huyhoang8398** [comment]
Hi, What I would like is have dedicated invoice number for each shop with prefix, for example: shop 1 start at 001 and shop 2 start at 0001

**Comment by huyhoang8398** [comment]
@florine2623
