### ISSUE TITLE
Can't view order prestashop 1.7.8.11

### ISSUE THREAD

**Issue by andreicos1982** [PrestaShop/PrestaShop#35979]
### Prerequisites

- [ ] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [ ] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello. I run prestashop 1.7.8.11.  On one oreder, can't view the order. I don't understand why I get error. The error is:
 Type error: Argument 1 passed to PrestaShop\PrestaShop\Core\Domain\Order\QueryResult\OrderInvoiceAddressForViewing::__construct() must be of the type int, null given, called in public_html/src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php on line 330

[Symfony\Component\Debug\Exception\FatalThrowableError 0]
I received other orders after the order with this error and they can all be viewed.

### Steps to reproduce

Cant reproduce

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

7.4

**Comment by matks** [comment]
Hi @andreicos1982 this looks very similar to https://github.com/PrestaShop/PrestaShop/issues/22215 please check it plenty solutions have been suggested

**Comment by florine2623** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
