### ISSUE TITLE
[BUG] Auto logout after first login in presta shop admin after first install and login

### ISSUE THREAD

**Issue by BlackYuzia** [PrestaShop/PrestaShop#35977]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Logout after first and each next login

https://github.com/PrestaShop/PrestaShop/assets/25010528/51dd563c-fb22-49ac-b3d0-ac748f2298fc

Also, I found a few errors after login in Network tab. But I didn't sure did that change anything
![image](https://github.com/PrestaShop/PrestaShop/assets/25010528/6d887712-f3ed-4191-a6d9-c2be97fd43fd)

### Expected behavior

All should work fine after first install.

### Steps to reproduce

- Install panel.
- Go to /{admin} path
- Try login with your creds
- Success first loggin in acconut
- After reloading page you **WILL BE** logout and then you can't login again without any errors

### System Info

- **Ubuntu 22.04**
- Using **CyberPanel**

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.0,8.1,8.2,8.3

**Comment by matks** [comment]
Hello @BlackYuzia

When you login in PrestaShop backoffice, your browser receives a cookie that authenticates you. From what you describe it seems that when you browse the backoffice, PrestaShop fails to authenticate you. Maybe something in the cookie is wrong, maybe it fails to receive the cookie.

Can I suggest to try with another browser to see if it happens too?

**Comment by BlackYuzia** [comment]
@matks tested on Chrome, Firefox and Edge. All the same. I could share creds to you. Then you could test in by your own.

**Comment by florine2623** [comment]
Hello @BlackYuzia ,

You can contact the support of PrestaShop Edition directly.

I'm closing the issue as theis is the platform for PrestaShop Open Source project.

**Comment by BlackYuzia** [comment]
Tested with XenForo (the same domain and same browser)
![image](https://github.com/PrestaShop/PrestaShop/assets/25010528/b721fd46-1fd6-4b46-9495-4f85fd0c8f2e)

How you could see login in XenForo work instead of prestashop. I don't know did this issue in developers or not. But, you didn't get support there. **Think twice before try install PrestaShop.** 

Your issue will be closed by `@florine2623` or else.

**Comment by BlackYuzia** [comment]
UPD: Hmm, seems like web server settings issue. In docker this service run and work fine.
