### ISSUE TITLE
Problem with images showed on product page, when is selected a specific main combination. 

### ISSUE THREAD

**Issue by pollat** [PrestaShop/PrestaShop#35986]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,
I have a big problem with images showed on product page:
on combination products, if I select a specific image for the main combination, when the user goes to the product page, they only see the image associated with the combination, rather than all the images set on the product.

On all eCommerce, if user go to the product page, he can see all product images and only the first image change if he select a specific combination: so how ca I do this on prestashop?

P.s. I have Prestashop v.1.7.8.10

### Expected behavior

O front-end, when user go to the product page, he can see all product images and only the first image change if he select a specific combination, like happen on all eComemrce. 

### Steps to reproduce

1) on back-office create a product with combination
2) insert 4 images on the product
3) go to combinations section and associate a specific image to main combination
4) save
5) on front-end go to product page and see than is showed only teh image associated to main combination (the hoters products images are not display)

### PrestaShop version(s) where the bug happened

1.7.8.10

### PHP version(s) where the bug happened

7.3

### Your company or customer's name goes here (if applicable).

Massimo

**Comment by Hlavtox** [comment]
Hi, this is how it works.

- If you want to see all images on that combination, don't select anything.
- If you want to see only specific images, select them.

> O front-end, when user go to the product page, he can see all product images and only the first image change if he select a specific combination, like happen on all eComemrce.

You can easily achieve this by selecting proper first image and all the other ones.

**Comment by florine2623** [comment]
@pollat 

I'm closing your issue as this is not a bug.

**Comment by pollat** [comment]
> You can easily achieve this by selecting proper first image and all the other ones.
> 

Select all image for the main combination is not a good solution, because when user changes combination I have the same problem (pretashop show to user only the image associated to combination selected) and if I select all images in all combinations the image is not changed for each selected combination.

**Comment by Hlavtox** [comment]
@pollat

If you have 4 images uploaded to the product:
- 🔴
- 🔵
- 🚗
- 🛣️

And you have 2 combinations:
- Color red
- Color blue

And you edit the combination and assign following images to the combinations:
- Color red - 🔴 🚗 🛣️
- Color blue - 🔵 🚗 🛣️

When you go to front office and user selects:
- Red, he will see images 🔴 🚗 🛣️
- Blue, he will see images 🔵 🚗 🛣️

If this doesn't work, you have a problem in your template.
