### ISSUE TITLE
Folder permissions removed after clear cache from BO

### ISSUE THREAD

**Issue by bluegifts** [PrestaShop/PrestaShop#35993]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Everytime i clear cache from BO  the folder permissions are changed ( /var/cache/ ) and errors appear in BO/FO - i must enable dev mode to enter on BO.
Happened to somebody until now? It.s not server related. Maybe a hint where to find the problem? Other website with same config is working well.

### Steps to reproduce

1. go to Advanced Parameters - Performance
2. hit Clear Cache

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.1.27

### If your bug is related to a module, specify its name and its version

MySQL: 5.6.51-log

**Comment by matks** [comment]
Hi @bluegifts when you perform a clear cache from BO, the var/cache folder is emptied. Maybe even deleted 🤔 (I'm not sure)

What happens next? Next time you attempt to browse the prestashop instance, PrestaShop will see var/cache folder is empty/deleted and will recreate it because it needs to function.

So if you have permissions issues, maybe this is because _the user who does the var/cache clean/removal and the user who does the re-creation of var/cache are two different users_.

I suggest you verify how your shop is installed, what users are running apache or nginx 😉

**Comment by bluegifts** [comment]
hello.
can you explain to me how to check this?
i use admin / owner user to clear the cache.

**Comment by AureRita** [comment]
Hi @bluegifts 

Thank you for your report, Despite my effort I can't reproduce your issue as you can see : 

[recording(199).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/e8621608-9a91-42a2-a593-9c18e4a25711)

Did I miss something ? 

Currently, in my case, when I delete the cash, it's directly completed with new files. 

Did you use many users on your shop or only one of them ? 

Waiting for feedback

**Comment by bluegifts** [comment]
hello
for backend i have 3 super admin users (one of them is mbo-XXX@prestashop.com), 1 editor and 1 sales.

**Comment by bluegifts** [comment]
this only happens to one of our shop, so i know it.s hard to replicate. i don.t know why this happens.

**Comment by florine2623** [comment]
Hello @bluegifts ,

It is not about the users from your BO, but the user from your server.

For that you need to contact directly your hosting provider to have this information.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
