### ISSUE TITLE
Changing state of an order is very slow (and sometimes results to a "504 Gateway Time-out - Nginx")

### ISSUE THREAD

**Issue by zenplayx** [PrestaShop/PrestaShop#35997]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have Prestashop 8.1.5 installed and working on VPS server.
I performed manual data migration from Prestashop 1.6.1.24 to Prestashop 8.1.5
I carefully followed the steps from this documentation :
https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/migration/
Database contains more than 37,000 orders.

Everything is working fine except :

Changing state of an order is very slow (at least 1 minute) and sometimes this results in a "504 Gateway Time-out - Nginx".
In the Server log file, I can see the Nginx error after about 1 minute : "upstream timed out (110: Connection timed out) while reading response header from upstream".

Note 1 : If I install this PrestaShop 8.1.5 locally with the same data (files and database) on my computer with MAMP server, then changing state is OK.

### Expected behavior

Changing state of an order should be fast

### Steps to reproduce

1. Select one order from the order list
2. Change state of the order. For example choose "Payment accepted"
3. Click the "change state" button

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.1.28

**Comment by florine2623** [comment]
Hello @zenplayx ,

Can you make sure your system requirements are met : https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/ ?

**Comment by zenplayx** [comment]
Yes. I think the requirements are met.
See attached photos.
<img width="975" alt="Capture d’écran 2024-04-25 à 06 09 56" src="https://github.com/PrestaShop/PrestaShop/assets/102356860/29c70e2b-b571-4532-a2c9-5167f57d29b4">

**Comment by florine2623** [comment]
I can't see your attachment

**Comment by zenplayx** [comment]
<img width="975" alt="Capture d’écran 2024-04-25 à 06 09 56" src="https://github.com/PrestaShop/PrestaShop/assets/102356860/29c70e2b-b571-4532-a2c9-5167f57d29b4">

**Comment by ChillCode** [comment]
Usually if works locally and not remotely it could mean is a server misconfiguration.

Do this happen with states that do not send emails? A similar issue I solved a while ago was because of that, connection to SMTP was slow so the state change required almost 20'.

You can always check execution time on different places.

**Comment by zenplayx** [comment]
I have disabled emails features. The problem is the same.

**Comment by ChillCode** [comment]
Since it can be caused by many different you'll need to investigate further since there would be more reports if it was common issue.

**Comment by florine2623** [comment]
Hello @zenplayx ,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
