### ISSUE TITLE
Translation of Product Flag "new" mappes to wrong location.

### ISSUE THREAD

**Issue by Fakeles** [PrestaShop/PrestaShop#35999]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I noticed that i can't change the translation of the product flag 'new' in the backoffice overlay because in the [src/Adapter/Presenter/Product/ProductLazyArray.php](https://github.com/PrestaShop/PrestaShop/blob/da757e42cf7923c5cba0c930438aee8523c60381/src/Adapter/Presenter/Product/ProductLazyArray.php#L638) the translation is mapped to Shop.Theme.Global even tho it should be mapped to Shop.Theme.Catalog to work correctly.
Thank you for looking into it. <3

### Expected behavior

No change for changing translation.

### Steps to reproduce

just try to change the translation of the product flag 'new' over the backoffice settings.

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment]
Fixed in newer version - https://github.com/PrestaShop/PrestaShop/issues/33780

**Comment by Fakeles** [comment]
ahh okay thank you
