### ISSUE TITLE
Migrate Login backoffice page and authentication system to Symfony

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#36001]
The Symfony Layout project is not complete because the backoffice Login page cannot work with SF Layout. If we enable the feature flag for the Symfony Layout, every backoffice pages work except this one. Due to its specific structure the only way to make it work is to migrate it to Symfony.

- [x] Main PR #36002
- [x] #36138
- [x] #36159
- [x] #36140
- [x] #36143
- [x] #36155
- [x] #36204
- [x] #36242
- [x] #36157
- [x] #36180
- [x] #36243
- [ ] Clean employee entity from useless fields (like bo width, bo theme, ...), add unicity constraint on email
- [x] #36249
- [x] #36241
- [x] #36347
- [x] #36212

**Comment by Robin-Fischer-PS** [comment]
Hello there,

As discussed together, PRs of this Epic can be merged without manual QA (but with green UI and CI tests). The QA will manually test the Epic once all the points have been dealt with.
