### ISSUE TITLE
related #35591 - bug 6 : Can't add texture (file upload field Texture in Attribute type color)

### ISSUE THREAD

**Issue by mattgoud** [PrestaShop/PrestaShop#36014]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Regression on the migrated Attributes pages

see #35591 B6

The texture can't be added. The color Black is automatically added.

### Steps to reproduce

- Go to Attributes & Features > Attributes Tab
- Click on 'Add new value' btn
- select Color on Attribute group field
- Try to add Texture file

### PrestaShop version(s) where the bug happened

develop

**Comment by Hlavtox** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/36068
