### ISSUE TITLE
Problem with the add to cart button when declining products

### ISSUE THREAD

**Issue by Prestadhauc** [PrestaShop/PrestaShop#36019]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello
I currently have a problem with the "Add to cart" button that does not appear when I activate the declination mode on all products, even though the stock is valid (see images below). 

Thanks
![Eolia 1](https://github.com/PrestaShop/PrestaShop/assets/167996825/cc1e807c-82ad-45be-8f04-29937238a74c)
![Eolia 2](https://github.com/PrestaShop/PrestaShop/assets/167996825/3a7ab504-719d-491a-a22c-aad64babf95f)
![Eolia 3](https://github.com/PrestaShop/PrestaShop/assets/167996825/10736aa6-4402-4cf6-a031-1f451dbb6f3f)
![Eolia 4](https://github.com/PrestaShop/PrestaShop/assets/167996825/d83bbe86-7cd4-424a-916e-54f7ef6539a6)

### Expected behavior

I expect the button to be displayed on the different product variations.

### Steps to reproduce

See images above

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

8.7

### If your bug is related to a module, specify its name and its version

i dn't now

### Your company or customer's name goes here (if applicable).

Adhauc

**Comment by florine2623** [comment]
Hello @Prestadhauc ,

Make sure the following option is disabled.
<img width="1202" alt="Screenshot 2024-04-24 at 16 30 18" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/0f6640a8-5f37-429f-aeed-ffbfde9f62b0">

If you still don't have the add to cart button, you need to check directly with the developer of your template directly. 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by Prestadhauc** [comment]
All right, thanks, I'll see what I can do.
