### ISSUE TITLE
Product page mobile layout default theme broken width

### ISSUE THREAD

**Issue by matteolavaggi** [PrestaShop/PrestaShop#36015]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

PS 8.1.4 default theme has horizontal width scroll on product page on the right out of the page margin.

See attached picture from Galaxy S24 

### Expected behavior

Page must not allow right scroll.

### Steps to reproduce

1. Install ps 8.1.4 
2. Open a default product page from mobile
3. Slide from right to left your finger
4. Page scroll outside the "visible" area

### PrestaShop version(s) where the bug happened

8.1.4

### PHP version(s) where the bug happened

8.1

**Comment by matteolavaggi** [comment]
![Screenshot_20240424_125408_Chrome](https://github.com/PrestaShop/PrestaShop/assets/24798703/62bee79e-743a-4085-b8ff-e5e151a4793f)

**Comment by florine2623** [comment]
Hello @matteolavaggi ,

I can't reproduce your issue using an emulator for Samsung S24.

https://github.com/PrestaShop/PrestaShop/assets/16019289/fa785b38-60af-4429-b414-b64035d17140

So I'm closing your issue.

**Comment by matteolavaggi** [comment]
@florine2623 

My real Galaxy S24

https://github.com/PrestaShop/PrestaShop/assets/24798703/b552ac4b-8bdf-4f6c-9ff7-5ec1a6f23a01
