### ISSUE TITLE
Unexpected error when creating a new order in the back office

### ISSUE THREAD

**Issue by anita-coody** [PrestaShop/PrestaShop#36013]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When creating a new order from the back office of the shop, the error in the attachment appears. It takes several attempts to place an order. Sometimes the error appears and sometimes it does not.
![image (6)](https://github.com/PrestaShop/PrestaShop/assets/160582644/5a960d11-f855-48cd-83a0-db1231d3b878)

### Steps to reproduce

1. Go to the "orders" tab
2. Click "Add new order"
3. Fill in all the required information
4. Click "Create order"

After following these steps, the error sometimes appears and sometimes not. 

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.3.33

**Comment by florine2623** [comment]
Hello @anita-coody ,

I can't reproduce your issue. You must have an issue with an external module. 
Please take a look at : https://www.prestashop.com/forums/topic/1080833-manuelle-bestellung-anlegen-fehler-no-route-found-for-get-sellordersplace-method-not-allowed-allow-post/

Thanks!
