### ISSUE TITLE
Problem with Shopping cart module

### ISSUE THREAD

**Issue by InnaPan** [PrestaShop/PrestaShop#36016]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have a problem with Shopping cart module, when I press the "Add to cart" button nothing happens, I have to refresh the page and then the goods appear in the cart.  

### Steps to reproduce

1. Go to watchmark.pl
2. Click on any product
3. Scroll down to ADD TO CART
4. Error: Nothing happens
5. Refresh the page and then the goods appear in the cart

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_shoppingcart

### Your company or customer's name goes here (if applicable).

Ampliton

**Comment by Hlavtox** [comment]
Hi, this is a problem with your theme. There are many errors in the console and when you add something to cart, the response is correct with all the data.

**Comment by florine2623** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
