### ISSUE TITLE
config docker-compose.override.yml : php-my-admin container not in the same network as mysql

### ISSUE THREAD

**Issue by mattgoud** [PrestaShop/PrestaShop#36017]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

via docker-compose, connection refused when I want to access php-my-admin

### Expected behavior

access the phpmyadmin interface

### Steps to reproduce

- Go to localhost:8080 => connection refused

### PrestaShop version(s) where the bug happened

develop

**Comment by florine2623** [comment]
Hello @mattgoud ,

I have reproduced your issue on develop :

<img width="1266" alt="Screenshot 2024-04-26 at 11 34 09" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/9933062d-8a55-4c61-87b0-92f0c5b1a627">

Thanks!
