### ISSUE TITLE
Product Physical quantity in wrongly increased when Order status is changed

### ISSUE THREAD

**Issue by Sekar33000** [PrestaShop/PrestaShop#36024]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When an order placed in "Awaiting bank transfer or check payment" status is cancelled (status change) and the order is then set to "Awaiting bank transfer payment" or "Awaiting check payment" status in versions 8... (tested on 8.0.5, 8.1.1, and 8.1.5), the system increases the physical quantity. Here's an example of the incorrect behavior:

Initial stock (physical/reserved/available): 15/0/15.
Order status: Awaiting bank transfer payment -> Physical quantity: 15, Reserved quantity: 1, Available: 14.
The order is cancelled -> Physical quantity: 15, Reserved quantity: 0, Available: 15.
The order is set again to "Awaiting bank transfer payment" or "Awaiting check payment" -> Physical quantity: 16, Reserved quantity: 1, Available: 15.

This incorrect behavior is observed in versions 8... of Prestashop and leads to an incorrect increase in the physical quantity reserved when an order is cancelled and modified again to the "Awaiting bank transfer payment" or "Awaiting check payment" status. It's not acceptable for stock levels to increase in this way; if, for example, an employee mistakenly changes the status to cancelled and then reverts to the initial status, the physical quantity will have increased.

### Expected behavior

I expected that when an order is cancelled and then set back to the "Awaiting bank transfer payment" or "Awaiting check payment" status in Prestashop 8.x, the system should not increase the physical quantity. Instead, the physical quantity should remain the same as before the cancellation.

### Steps to reproduce

1. Place an order in Prestashop 8.x and set the status to "Awaiting bank transfer payment" or "Awaiting check payment".
2. Verify the initial stock levels (physical/reserved/available).
3. Cancel the order.
4. Confirm that the physical quantity remains the same after cancellation.
5. Set the order status back to "Awaiting bank transfer payment" or "Awaiting check payment".
6. Verify the stock levels again and observe that the physical quantity has increased incorrectly.

### PrestaShop version(s) where the bug happened

8.0.0 - 8.1.6

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @Sekar33000 ,

Is your issue similar to https://github.com/PrestaShop/PrestaShop/issues/27631 ?

Waiting for your feedback.
Thanks!

**Comment by Sekar33000** [comment]
According to me, the issues encountered are different:

In the problem described in the other post, when an order is placed for a product with zero stock in PrestaShop 1.7.7.8 (and possibly in earlier versions), the system incorrectly changes the quantity of the product in the database. For example, when the order is marked as "shipped" or "refunded", the quantity of the product can become negative or the physical stock can be incorrectly modified.

On the other hand, in the problem I'm addressing, when you cancel an order in PrestaShop 8.x and then re-place it in "Awaiting bank transfer payment" or "Awaiting check payment" status, the physical quantity of the product increases incorrectly.

While both issues involve incorrect changes in product quantities during order processing, they are caused by different mechanisms.

**Comment by florine2623** [comment]
Hello @Sekar33000 ,

I reproduce the issue with PrestaShop version 8.1.x, I'll add this to the backlog so it can be fixed.

Following your steps I have :

I create a product with quantity = 300 : ✅ 
<img width="890" alt="Screenshot 2024-07-04 at 15 08 41" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/9bf577a2-48bd-40cb-ae14-660e00d992e6">

I make an order : ✅ 
<img width="890" alt="Screenshot 2024-07-04 at 15 09 46" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/6cdd51c4-c508-45f0-a35a-30508a4df4da">

I cancel my order : ✅ 
<img width="887" alt="Screenshot 2024-07-04 at 15 10 12" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/89f7eaa7-0ecc-4b67-8092-0349a9e1efa7">

I change back my order status to Awaiting for payment : the physical quantity is incorrect :x: 
<img width="885" alt="Screenshot 2024-07-04 at 15 10 39" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/a07e2d51-ede6-424b-9194-aaee88911221">

The quantity in the BO is correct :
<img width="621" alt="Screenshot 2024-07-04 at 15 17 55" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/7634767c-c632-493d-9841-ba4f169a29f2">

I cannot buy more product than I have in my BO :
<img width="426" alt="Screenshot 2024-07-04 at 15 18 55" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/b8d2d562-7426-47e1-bfbc-bdfc88fa2ba9">


Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Sekar33000** [comment]
Hello this solution is worked for me = 
https://github.com/PrestaShop/PrestaShop/pull/36123/files/d161a4bab167ce4f6404a67e20774d3ea3b1f9f7
https://github.com/PrestaShop/PrestaShop/pull/36123
