### ISSUE TITLE
Add to card with minimal quantity product

### ISSUE THREAD

**Issue by Guimik** [PrestaShop/PrestaShop#36022]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug. Quantity is going back to five when you try to add to card

### Describe the bug and add attachments

When a product have a minimal quantity to be added in card, it's imposible to add more than the quantity in the product page,  Quantity is going back to five when you try to add to card

That works fine from the quickview.

I hope my explaination are clear.

Thanx

### Steps to reproduce

go to https://www.atypics.fr/sweats/176-3276-sweat-zippe-capuche-carter-unisexe.html#/8-couleur-blanc/35-choix_emplacements-logo_coeur
Adding a number higher than 5 is impossible (always going back to 5 when you remove the cursor)
From the quickview, that works fine.
![add1](https://github.com/PrestaShop/PrestaShop/assets/31242178/fee82418-97ad-4260-bea2-56bed055e95f)
![add2](https://github.com/PrestaShop/PrestaShop/assets/31242178/63ee2ef4-208d-4c08-acfc-90ba01fb85b1)
![add3](https://github.com/PrestaShop/PrestaShop/assets/31242178/fd2a0057-0637-41e1-ae81-dea04c9dd185)

From the quickview
![add4](https://github.com/PrestaShop/PrestaShop/assets/31242178/c9f70776-a83f-4e22-bd61-66d552137a3b)
![add5](https://github.com/PrestaShop/PrestaShop/assets/31242178/db6f4344-0ca0-478c-a60e-167c4b3c4b43)

### PrestaShop version(s) where the bug happened

1.8.5

### PHP version(s) where the bug happened

8.1.27

**Comment by florine2623** [comment]
Hello @Guimik ,

This is probably an issue coming from theme not the PS Open Source project itself.

You should contact the develop of your theme.

https://github.com/PrestaShop/PrestaShop/assets/16019289/e3c16097-6f0f-42af-9db8-3a65f973f39c

Thanks!

**Comment by Guimik** [comment]
Thanks for you answer, I use the Classic Theme, may be I should take a look the modified TPL files (not a lot, just custom.css)
