### ISSUE TITLE
Prestashop 8.0 Shipping Options Bug

### ISSUE THREAD

**Issue by alkorotkovas** [PrestaShop/PrestaShop#36025]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have a few options for shipping:
1. By price with ranges.
2. By weight from 0 to 30kg and so on.

I have over 500 products with assigned carriers by price, and only 4 assigned by weight. (due to heavy items).

If products with assigned carriers by price are added to the cart and do not mix with those assigned by weight, everything works well. However, if I add a product with an assigned carrier by price and another with an assigned carrier by weight, I experience a bug.

I assume the system does not understand what shipping option to show since there is no carrier that would be assigned to both products. But, that's not all, in the checkout I can see 2 shipping options (showing carrier by weight) with 2 different prices, 1 with a price like I set in carrier by price, and the other one is correct one that is assigned by weight).

Like in woocommerce or other platform, if there are no matching carrier for both products, it will show the only 1 with highest price range or priority on those with weight.
![Screenshot 2024-04-25 at 10 01 04](https://github.com/PrestaShop/PrestaShop/assets/103935370/260620fc-89ad-424f-910c-3914241e3bea)
![Screenshot 2024-04-25 at 10 01 36](https://github.com/PrestaShop/PrestaShop/assets/103935370/e2261e55-0a32-4290-9398-95439e547474)
![Screenshot 2024-04-25 at 10 02 06](https://github.com/PrestaShop/PrestaShop/assets/103935370/8824a41d-707b-485a-b6c5-458e0f3f606d)

### Expected behavior

Since, I have 2 carriers (by price) and (by weight), if products with different carriers are added to the cart I expect to display a price with the one which has the highest price or is assigned by with). You can't ship light items for a lower price if they were in the cart with those assigned by weight and with a higher shipping price.

### Steps to reproduce

1. Create products.
2. Create carrier by price range and by weight range.
3. Add both to the cart.

### PrestaShop version(s) where the bug happened

8.0

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @alkorotkovas ,

I think your issue is related to : 
https://github.com/PrestaShop/PrestaShop/issues/15369
https://github.com/PrestaShop/PrestaShop/issues/9998
https://github.com/PrestaShop/PrestaShop/issues/13080

Here's the EPIC listing all the issues regarding multi carrier : https://github.com/PrestaShop/PrestaShop/issues/15491

Could you confirm ?

Waiting for your feedback.
Thanks!

**Comment by alkorotkovas** [comment]
@florine2623 Yes, looks like the same. But, it's open since 2019 and there is no solution for it.

**Comment by florine2623** [comment]
Sorry for that. PrestaShop is an Ppen-Source project, so anyone can create pull-requests to fix an issue !

I suggest subscribing to the issue that matches yours. So we can close this issue and avoid clogging the backlog.

**Comment by alkorotkovas** [comment]
I understand the decision, but I'm curious why close the issue if there haven't been any updates from the developers for years? It would be helpful if a developer could provide a brief comment about any future plans regarding this bug. As it stands, once the case is closed, it becomes invisible unless specifically searched for.

@Hlavtox @jolelievre @florine2623  not sure whom to tag, sorry if I'm wrong.
