### ISSUE TITLE
SQL_MODE : STRICT_TRANS_TABLES vs STRICT_ALL_TABLES

### ISSUE THREAD

**Issue by Max84** [PrestaShop/PrestaShop#36033]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Prestashop database doesn't have default value for several fields. But a lot of them can be set to 0. For example, into ps_specific_prices, id_specific_price_rule can be equal to 0.

So when you'll do an insert, you may ignore it because it's null.

If you MySQL/MariaDB SQL MODE is set to STRICT_TRANS_TABLES, the default install value, it will work.
But if your sysadmin uses STRICT_ALL_TABLES, it won't work.

I think it can be a good practice to fix this in order to make all development stronger.

I don't know what is the best way if to define default value in database or write in Prestashop requirements to use STRICT_TRANS_TABLES instead of STRICT_ALL_TABLES.

### Steps to reproduce

I hope the description is enough, but you can try to this request with different SQL_MODE:
INSERT INTO ps_specific_price SET id_product = '1',id_shop = '0',id_currency = '0',id_country = '0',id_group = '0',id_customer = '1',id_product_attribute = '',price = '-1',from_quantity = '1',reduction = '0.1',reduction_tax = '0',reduction_type = 'percentage'

### PrestaShop version(s) where the bug happened

all

**Comment by florine2623** [comment]
Hello @Max84 ,

Could you specify the current behavior and what you expect ?
With steps to reproduce and screenshots ?

Thanks!
Waiting for your feedback.

**Comment by Max84** [comment]
Hello @florine2623,

After your reply, I think it may be better to use discussion instead of issue, I just created one here => https://github.com/PrestaShop/PrestaShop/discussions/36038

thanks
