### ISSUE TITLE
Customers list BO customersKpi warning

### ISSUE THREAD

**Issue by wlutek1** [PrestaShop/PrestaShop#36035]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In multishop `PrestaShop\PrestaShop\Adapter\Kpi\AverageCustomerAgeKpi` & `PrestaShop\PrestaShop\Adapter\Kpi\MostCommonCustomersGenderKpi` get the array from kpi configuration - string is needed

![image](https://github.com/PrestaShop/PrestaShop/assets/162972241/fa1b47d4-b37f-471a-912e-4c364a114d20)

![image](https://github.com/PrestaShop/PrestaShop/assets/162972241/f7c19e6e-4c25-4797-8535-a37f782e754e)

### Steps to reproduce

1. Go to BO customers list in specyfic shop context

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.1.28

**Comment by florine2623** [comment]
Hello @wlutek1 ,

I can't reproduce your issue :

https://github.com/PrestaShop/PrestaShop/assets/16019289/664bc43c-abe5-4cff-9b35-dd37995c65ed

**Comment by wlutek1** [comment]
Issue is in PS 8.1.4, 8.1.5 
You have 9.0

**Comment by kpodemski** [comment]
thanks for the report @wlutek1 but this warning comes from inconsistency in the DB, it doesn't exist on a clean installation, it won't be reproducible for our QA team
