### ISSUE TITLE
Italian language on the help window

### ISSUE THREAD

**Issue by GUANASTA50** [PrestaShop/PrestaShop#36040]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi, in the prestashop 8.04 Italian version, when the help window of the various pages opens, the language is in English not Italian. How to solve the problem? Thank you

### Expected behavior

That the help language was in Italian

### Steps to reproduce

https://anastasishop.it/adminxxx/index.php/sell/catalog/products?_token=xxx

Look help Window.

### PrestaShop version(s) where the bug happened

prestashop 8.04

### Your company or customer's name goes here (if applicable).

anastasi.srl

**Comment by florine2623** [comment]
Please contact directly the support for PrestaShop Edition.

This space is for PrestaShop Open Source only.
