### ISSUE TITLE
Backend Order Summary text is wrong

### ISSUE THREAD

**Issue by PJMasksBoy** [PrestaShop/PrestaShop#36047]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The text for 
documentsTitle , carriersTitle, merchantReturnsTitle

is wrong 

### Expected behavior

we have to modify :
src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/details.html.twig

and delete <span data-role="count"> and </span>

Best regards

### Steps to reproduce

1. go to orders
2. select an order
3. look at the "informations about the order"
![xxxxxxxxxxxxxxxxxxx](https://github.com/PrestaShop/PrestaShop/assets/168263086/83df292e-73d9-4bd1-9128-0c34ec9b7f17)

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.3.6

**Comment by paulnoelcholot** [comment]
Hello @PJMasksBoy,

I tried to reproduce your issue but as you can see, I can't. Did I miss something?

![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/35d5b690-653e-4137-9854-7f4a6cc7c773)


Thanks for your feedback

**Comment by PJMasksBoy** [comment]
hello, here is my details.html.twig file. best regards
[details.html.twig.txt](https://github.com/PrestaShop/PrestaShop/files/15214491/details.html.twig.txt)

**Comment by florine2623** [comment]
Hello @PJMasksBoy ,

Please use PHP 8.1 maximum.
https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/

Also, these columns are added via an external module. You can directly ask the developer of the module to fix it.

Thanks!
