### ISSUE TITLE
Publish prestashop.com repo

### ISSUE THREAD

**Issue by fulldecent** [PrestaShop/PrestaShop#36054]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The website prestashop.com is not checked into GitHub.

### Expected behavior

I can find and report bugs against the website prestashop.com.

For example, right now the main link to download/install PrestaShop is broken. I can't fix it or report this fact in GitHub which is the main place on Earth where problems like this get fixed.

![Screenshot 2024-04-29 at 21 41 30](https://github.com/PrestaShop/PrestaShop/assets/382183/fdbd1c28-cb0e-4b65-b1be-47498fd5c1e3)

### Steps to reproduce

1. GitHub.com
2. Click search
3. Enter some text from the prestashop.com homepage
4. Find which repo hosts that source code

### PrestaShop version(s) where the bug happened

all

### PHP version(s) where the bug happened

n/a

### If your bug is related to a module, specify its name and its version

n/a

### Your company or customer's name goes here (if applicable).

n/a

**Comment by paulnoelcholot** [comment]
@fulldecent Items offered on www.prestashop.com are purely in the hands of Prestashop SA company, not this open source project. However, I forwarded the information to the competent person.
