### ISSUE TITLE
Zipball on GitHub does not match website

### ISSUE THREAD

**Issue by fulldecent** [PrestaShop/PrestaShop#36055]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The Zipball in this GitHub repo 

https://github.com/PrestaShop/PrestaShop/releases/tag/8.1.5

does not match the same offered product when downloaded from the website at 

https://prestashop.com/prestashop-offers/classic/ (not a permalink)

Please note that the website also requires you to type in some b-s email address before the download proceeds. This is similar to how Docker works, right before everyone started boycotting Docker.

### Steps to reproduce

Download both
Compare

### PrestaShop version(s) where the bug happened

8.1.5

**Comment by Hlavtox** [comment]
@fulldecent Items offered on www.prestashop.com are purely in the hands of Prestashop SA company, not this open source project. It contains some extra modules and other things.

If you want a clean installation of Prestashop, download it from github OR from official project website - https://www.prestashop-project.org/.

**Comment by fulldecent** [comment]
Thank you @Hlavtox for the explanation. I have introduced this as a PR https://github.com/PrestaShop/PrestaShop/pull/36088 to hopefully help other people to understand, to improve transparency, and to help introduce the PrestaShop commercial product.

**Comment by Hlavtox** [comment]
@fulldecent Just approved the PR, good job ;-)
