### ISSUE TITLE
Problem adding products with no shipping carrier to the state or country of the buyer

### ISSUE THREAD

**Issue by msaustral** [PrestaShop/PrestaShop#36064]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The platform allow to buy products with carriers that have not coverage on zone (state/country) were customer is when in cart are product that does have carrier with coverage

### Expected behavior

Not allow to buy products that have a specific carrier enable with a specific coverage that is not on the customer country or state when it is mixed with products that does have a carrier with coverage

### Steps to reproduce

1.- Have 2 different carriers that have service only on a specific zone (state or country), let say, carrier 1 for Europe and carrier 2 South America
2.- Add carrier 1 to product 1 and carrier 2 to product 2
3.- Go to front office, create a user and add country on Europe to the address
4.- Add to the cart product 1 and product 2
5.- Finish the buy process 

Then you will get 2 orders with the same reference, one with carrier 1 for Europe and one without carrier because carrier 2 of the  product 2 has not service on Europe 

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

Multiservicios Austral (PS Partner)

**Comment by paulnoelcholot** [comment]
Hello @msaustral,

I reproduce the issue with PrestaShop version 8.1.x, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/41b627a8-a197-4a1d-be9c-fa8cbab62767)

**Comment by msaustral** [comment]
Hi, thank you for the fix, it did work perfectly
