### ISSUE TITLE
Error with Product POST to Empty Category on Webservice

### ISSUE THREAD

**Issue by mcclede** [PrestaShop/PrestaShop#36077]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Using Postman I created a new Category, then using Postman again I attempted to create a new Product with the previously created category as the id_category_default, and a position of 1. The webservice returned an error:
{
    "errors": [
        {
            "code": 135,
            "message": "You cannot set a position greater than the total number of products in the category, starting at 1."
        }
    ]
}
The code in classes/Product.php first checks whether position <= 0, issuing an error if that is the case. After some processing, it checks whether Position is > the number of products already associated with the category. If so, an error is issued. This makes it impossible to add the first product to the category through the webservice. A good solution here would be to always allow a position of zero to append the product to the end of the list of category products.

### Expected behavior

The Product is added as the first Product in the Category

### Steps to reproduce

1. Use Postman to create a new Category
2. Use Postman to attempt to add the first Product in the new Category

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.1.27

**Comment by angeligle** [comment]
My prestashop version is 1.7.8.9 and i have the same problem. The first product in category fault.
public function setWsPositionInCategory($position)
    {
        if ($position <=0 ) {
            WebserviceRequest::getInstance()->setError(
                500,
                $this->trans(
                    'You cannot set 0 or a negative position, the minimum is 1.',
                    [],
                    'Admin.Catalog.Notification'
                ),
                134
            );

            return false;
        }

**Comment by mcclede** [comment]
I've thought further about this issue, and I think it is not a bug. The
position in category is only valid if there are already products in the
category and you want to insert a new one.

To insert the first product into a category, and in fact append a product
to a category, you would not specify the position in category, and you
would specify the category in the associations collection, and optionally
the default category id.
