### ISSUE TITLE
Problem with generating images in .webp format

### ISSUE THREAD

**Issue by albert28** [PrestaShop/PrestaShop#36071]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,

I have configured Prestashop to generate the images in .webp format. However, images are still generated in .jpg on the frontend and are also saved in .jpg in the /img directory. I have regenerated the images and the problem remains, the new images are generated with the .jpg format. I have also cleared the cache.

I have tried the experimental option of having images with different formats, and then I see that the images in the product page are still .jpg, but there are the <source srcset> with the images in webp format.

Is this correct? Why does Prestashop give the option to generate images in .webp if they are then displayed in .jpg anyway by default?

### Steps to reproduce

Go to Admin Images page
Select webp format

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

7.4 and 8.1

**Comment by Hlavtox** [comment]
Yes, this is correct. The old implementation of webp generates webp images with jpg extension.

If you enable the new image system, you will get both JPG images with JPG extension AND WEBP images with WEBP extension.

The new image system will be default since 9.0.0.

**Comment by Hlavtox** [comment]
It's also written on the image settings page - `Note that in all cases the image files will have the .jpg extension.`
