### ISSUE TITLE
Blockwishlist 3.0.0 and 3.0.1 white page on wishlist page in customer dettails

### ISSUE THREAD

**Issue by ValentiniVini** [PrestaShop/PrestaShop#36070]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Greetings,
on my prestashop versions 3.0.0 and 3.0.1 of the module are installed only if version 2.1.2 is already installed.
Uninstalling 2.1.2 and installing 3.0.0 or 3.0.1 results in an installation error.

Upgrading 2.1.2 to 3.0.0. or 3.0.1 a blank page appears when you try to open a wish list in the account management pages.
With version 2.1.2 the bug does not seem to occur.

Has anyone already had a similar problem?

### Steps to reproduce

Update module from 2.1.2 to 3.0.0 or 3.0.1 anche go to custemer wishlist page.
The page is white.

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

7.4.3

### If your bug is related to a module, specify its name and its version

3.0.0 or 3.0.1

**Comment by florine2623** [comment]
Hello @ValentiniVini ,

Versions 3.0.0 and later are for PS > 8.0.0.
For 1.7.8.11, you should use v2.1.2.

Please use v2.1.2.

I'm closing the issue as this is not an issue. This is a incompatible version.
