### ISSUE TITLE
Translation prestashop product flag (New)

### ISSUE THREAD

**Issue by medMethnani** [PrestaShop/PrestaShop#36076]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The translation of the product flag **New** is not working in any language, after checking i found a bug on Prestashop 8.X 
This is my pull request to fix the issue : https://github.com/PrestaShop/PrestaShop/pull/36067
![new_traduction](https://github.com/PrestaShop/PrestaShop/assets/3436150/b6e32130-a680-4b2b-975f-65fb4a771853)

### Expected behavior

This problem is related to Prestashop _multi-languges_ only

### Steps to reproduce

1) Add new language pack in prestashop Ex: French 
2) In front end check new product badge it will show New instead of Nouveau  
NB: even if you translate the New => Nouveau from the backend it will not work

### PrestaShop version(s) where the bug happened

8.X

### PHP version(s) where the bug happened

8.X

### Your company or customer's name goes here (if applicable).

MedMethnani

**Comment by Hlavtox** [comment]
@medMethnani The field is translatable just fine.

1. Go to Translations > Front office translations > Core (no theme selected) > French.
2. Search for `new`.
3. Click `Shop > Theme > Global` in the left column
4. Find `New` and translate.

**Comment by medMethnani** [comment]
@Hlavtox Thank you for your answer.
That's exactly what I did, the translation always shows **New** instead of **Nouveau**  in front office.
Be aware that I'm testing on fresh install of Prestashop 8.1.1 origin with English language  then I added the French package.
I tested other versions of Prestashop and it seems the problem is on PS 8.X
This is my pull request to fix the issue : https://github.com/PrestaShop/PrestaShop/pull/36067

**Comment by Hlavtox** [comment]
@medMethnani Isn't it just homepage modules cache? Did you clearing cache?

**Comment by medMethnani** [comment]
Yes of course :)

**Comment by florine2623** [comment]
Hello @medMethnani ,

I can't reproduce your issue :

https://github.com/PrestaShop/PrestaShop/assets/16019289/86efef72-0049-4669-8305-af7bbf88405d

If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by medMethnani** [comment]
Hello @florine2623 , in fact to reproduce the issue please follow this steps:

- Add new language pack in prestashop Ex: **French**
- In front end check new product badge it will show New instead of **Nouveau**

NB: even if you translate the New => Nouveau from the backend it will not work
