### ISSUE TITLE
fix error in PHP 8: count(): Argument #1 ($value) must be of type Countable

### ISSUE THREAD

**Issue by olecorre** [PrestaShop/PrestaShop#36083]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

fix error in PHP 8: count(): Argument https://github.com/PrestaShop/PrestaShop/pull/1 ($value) must be of type Countable

### Expected behavior

in code : 
$tab = [];
foreach ($tables as $table) {
    if ($this->attributExistInTable($attr, $table['table'])) {
        $tab = $table['table'];
    }
}
if (count($tab) == 1) {
    return $tab;
}
in PHP 8 $tab = $table['table']; delete the array property ans $tab become a string

### Steps to reproduce

1. go to BO SQL Manager 
2 . Create a new SQL request with join
Exemple : 
SELECT p.id_product , p.reference FROM `ps_stock_available` sa INNER JOIN `ps_product` p ON p.`id_product`=sa.`id_product` INNER JOIN `ps_product_lang` pl on pl.`id_product`=p.`id_product` WHERE `id_product_attribute` = 0 AND pl.`id_lang` = 9 AND pl.`available_later` = 'Hors Stock' AND sa.`quantity` <= 0 AND p.`active`=1
3. You have a error  "count(): Argument https://github.com/PrestaShop/PrestaShop/pull/1 ($value) must be of type Countable"

### PrestaShop version(s) where the bug happened

All Version

### PHP version(s) where the bug happened

PHP 8.1

**Comment by florine2623** [comment]
Hello @olecorre ,

I reproduce the issue with PrestaShop version 8.1.x and develop, I'll add this to the backlog so it can be fixed.

<img width="1066" alt="Screenshot 2024-05-13 at 11 50 59" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/571dae4f-8217-441e-a100-e7c688e89469">

`count(): Argument #1 ($value) must be of type Countable|array, string given`

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
