### ISSUE TITLE
Product Comments module displays raw JSON instead of updating the DOM

### ISSUE THREAD

**Issue by jak78** [PrestaShop/PrestaShop#36093]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I submit the form to submit a product comment using the native Prestashop Product Comments module, the raw JSON is displayed.  Feel free to watch the enclosed screen recording.
The behavior is the same wether the form submission is an error (error message) or a success (no error message).
I can reproduce the issue on both Chrome (latest version) & Firefox (latest version)

https://github.com/PrestaShop/PrestaShop/assets/351773/43358c08-3589-478c-9c58-df08235a3673

### Expected behavior

I would expect the HTML page to be updated instead and display a message to the user.

### Steps to reproduce

1. Go to a product page
2. Click the button to show the product comment form
3. Submit a comment

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.1.12

### If your bug is related to a module, specify its name and its version

product comments 7.0.0

**Comment by spanishsnapper** [comment]
Same error present on 8.1.3 (PHP version 8.2)

<img width="935" alt="Screenshot 2024-05-05 at 09 41 49" src="https://github.com/PrestaShop/PrestaShop/assets/36232063/7fbfd2f2-cc7a-4d95-9d92-74fafe579d52">
<img width="648" alt="Screenshot 2024-05-05 at 09 42 03" src="https://github.com/PrestaShop/PrestaShop/assets/36232063/737679ba-8cb1-49f5-b388-d3f8f2f1b93a">

**Comment by leemyongpakva** [comment]
@spanishsnapper This bug comes from my recent implementation for @jak78 request [make rating mandatory](https://github.com/PrestaShop/PrestaShop/issues/26001). If you use a theme with **override module template** (like hummingbird for example), you need add these two lines (inside `<script>` tag)
```
  var productCommentMandatoryMessage = '{l s='Please choose a rating for your review.' d='Modules.Productcomments.Shop' js=1}';
  var ratingChosen = false;  

```
at the very top of your theme's `modules/productcomments/views/templates/hook/post-comment-modal.tpl` file to make new implementation works correctly.
You can see an example for hummingbird theme at [modules/productcomments/views/templates/hook/post-comment-modal.tpl](https://github.com/PrestaShop/hummingbird/pull/577/files#diff-2abe9e855056346d8cf667c2b66997007d3f96f6f3294bd1e523d883ddc68fca)

**Comment by spanishsnapper** [comment]
That fixed it - Thank you @leemyongpakva

**Comment by jak78** [comment]
@leemyongpakva thanks for implementing my suggestion. I use the classic theme version 2.1.1, there is no module template override, but I have the issue. Is there a workaround? I'd love to help solve the issue but I'm a beginner: feel free to provide me with instructions.

**Comment by leemyongpakva** [comment]
@jak78 I think it was a cache issue in your case. You can try CONFIGURE > Advanced Parameters > Performance > Clear Cache in Back-Office, and Clear browser cache in Front-Office.

**Comment by jak78** [comment]
Thanks. I just cleared the cache on the back office (do you mean the Smarty
cache?) and the browser cache, but the issue still persists.

**Comment by leemyongpakva** [comment]
Yes, we usually call it Smarty cache. I see you use Classic theme but with its child_classic **also**. If you have no module template override in your child_classic theme, then I only have one solution left for you (: copy `your_site_root/modules/productcomments/views/templates/hook/post-comment-modal.tpl` file to `your_site_root/themes/classic/modules/productcomments/views/templates/hook` folder.

**Comment by spanishsnapper** [comment]
@jak78 I see your site is _en françias_.
I also had to regenerate translations to make sure I had a translation for the new variable on a site that was in Spanish.
Before I did it, the invalid translation was causing a javascript error that prevented the subsequent code from executing. 
You could try that to see if it solves issue.

**Comment by jak78** [comment]
> Yes, we usually call it Smarty cache. I see you use Classic theme but with its child_classic **also**. If you have no module template override in your child_classic theme, then I only have one solution left for you (: copy `your_site_root/modules/productcomments/views/templates/hook/post-comment-modal.tpl` file to `your_site_root/themes/classic/modules/productcomments/views/templates/hook` folder.

Thanks @leemyongpakva - I've just done that, then cleaned the Smarty cache and the browser cache, but the issue persists.

**Comment by jak78** [comment]
@leemyongpakva I've figured out the issue 🎉 
One translation contained a `'` character. That triggered a JavaScript error as seen on the screenshot below:
<img width="631" alt="Screenshot 2024-05-13 at 14 20 51" src="https://github.com/PrestaShop/PrestaShop/assets/351773/8198d8d8-d4d1-4f25-b132-3b5bbcc622f7">
I've escaped the character in the translation string and now it works!
<img width="356" alt="Screenshot 2024-05-13 at 14 25 18" src="https://github.com/PrestaShop/PrestaShop/assets/351773/408969c4-71f3-4c4d-a923-acb3f1ea0d7f">

**Comment by jak78** [comment]
I guess there would be some escaping to implement in the module

**Comment by leemyongpakva** [comment]
@jak78 Great, we still need some improvements on this feature.

**Comment by florine2623** [comment]
@jak78 ,

I can't reproduce your issue on my end :

https://github.com/PrestaShop/PrestaShop/assets/16019289/1f324a59-9a06-4395-a809-db80032ab776

I'm using productcomments v7.0.0, PS 8.1.5 and PHP 8.1.13.

@leemyongpakva , does this issue needs a PR ? Should I keep it open ?

Thanks!

**Comment by jak78** [comment]
@florine2623 did you try to use a `'` character in a transation string as described [here](https://github.com/PrestaShop/PrestaShop/issues/36093#issuecomment-2107443806)?

**Comment by leemyongpakva** [comment]
@florine2623 Yes, this issue really a need a PR to solve escaping for special character in JS message variables (**jak78** case) and 3rd party themes that have its own productcomments template override (**spanishsnapper** case).

**Comment by leemyongpakva** [comment]
@jak78 Is `'` character above shipped with original productcomments module or customized by yourself ?

**Comment by jak78** [comment]
> @jak78 Is `'` character above shipped with original productcomments module or customized by yourself ?

@leemyongpakva the French translation string for 'Please choose a rating for your review.' is missing from the productcomments module translation. I had to customize the string to ensure that the text is displayed in French. My French translation contains a `'` character.

**Comment by florine2623** [comment]
Hello @jak78 ,

I tested with the `'` character. But I still can't reproduce it.

<img width="874" alt="Screenshot 2024-07-02 at 11 58 40" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/c5c91f4d-766a-47b6-8fde-ae3f03fc60a1">
<img width="1125" alt="Screenshot 2024-07-02 at 11 58 51" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/74e9e208-3fdf-42d9-b7d0-7ca6e89f3da3">

**Comment by paulnoelcholot** [comment]
Hello @jak78,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
