### ISSUE TITLE
Impossible to edit a country

### ISSUE THREAD

**Issue by pquattro** [PrestaShop/PrestaShop#36105]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In 8.1.3, its just impossible to edit a country. 3 files are missing on the official package.
After " Denial acces", when i put debug mode on, the message change by "Page no found".
https://capture.dropbox.com/3OLVHk9Yw2UryqZ5
<img width="1838" alt="Capture d’écran 2024-05-06 à 19 51 53" src="https://github.com/PrestaShop/PrestaShop/assets/1635700/4bcc602d-1dc4-4e65-9f05-7410840ceba8">

After investigating, @PrestaShop/Admin/Improve/International/Country/Blocks/Editing.html.twig is missing, function in controler too, etc...
Thanks for fix !

### Expected behavior

Be able to edit a country....
<img width="1838" alt="Capture d’écran 2024-05-06 à 19 51 53" src="https://github.com/PrestaShop/PrestaShop/assets/1635700/6df6e29f-1b3a-4d84-b3ea-0739f5d0b17f">

### Steps to reproduce

Try to edit a country on official 8.1.3 bundle. (i search on dev branch, dev is not finish yet...)

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

8.1.27

### Your company or customer's name goes here (if applicable).

Isquarecube SAS

**Comment by Hlavtox** [comment]
Hi @pquattro, it seems your installation is corrupted. Editing country works just fine on 8.1.5.

Check list of changed files in Advanced parameters > Information and if there are some, fix it using the offcial package.

I hope you find a solution. 👍

**Comment by pquattro** [comment]
I know its corrupted, and no, i have the official 8.1.5. Files are just missing.

**Comment by Hlavtox** [comment]
You wrote 8.1.3 👍

If some files are missing, fix them using https://github.com/PrestaShop/PrestaShop/releases/download/8.1.5/prestashop_8.1.5.zip

Otherwise, I suggest hiring a specialist to fix your install.
