### ISSUE TITLE
You have requested a non-existent service "PrestaShop\Module\PsAccounts\Service\PsAccountsService".

### ISSUE THREAD

**Issue by louloudev59** [PrestaShop/PrestaShop#36104]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I try to access my admin panel, it returns the following error: You have requested a non-existent service "PrestaShop\Module\PsAccounts\Service\PsAccountsService". However, my Ps Accounts module is up to date

### Expected behavior

Just access to the admin panel

### Steps to reproduce

1. Idk, I just dump by database on phpmyadmin

### PrestaShop version(s) where the bug happened

8.1.5

**Comment by Hlavtox** [comment]
Ping @PrestaShop/prestashop-sa

**Comment by nicosomb** [comment]
@louloudev59 Hello. Thank you for opening this issue. 

I tried to reproduce your issue, but I didn't. 

Please give us more details (how did you install PrestaShop, where does the database come from, etc.).

**Comment by MatShir** [comment]
PsAccountsService is from the ps_account. I will redirect the issue to module dev

**Comment by ChillCode** [comment]
>  I just dump by database on phpmyadmin

Before dumping data over a Docker or whatsoever is good to read the [docs](https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/migration/#quick-and-complete-export-recommended) regarding data migration. 

> tab: This table contains the admin controllers accessible on your backoffice. As its values are mainly managed by PrestaShop, do not alter the content of the new shop.

**Comment by Guillaumelpg** [comment]
Hello @louloudev59 
Can you try clearing your cache first? And if that doesn't work, you can reset the ps_account module.

**Comment by paulnoelcholot** [comment]
Hello @louloudev59,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
