### ISSUE TITLE
1-Click Upgrade HTTP ERROR 500, when images 20K in presta

### ISSUE THREAD

**Issue by LaurynasLTU** [PrestaShop/PrestaShop#36106]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

_1-Click Upgrade start HTTP ERROR 500, when products >20K with images in presta.

![500-status-code](https://github.com/PrestaShop/PrestaShop/assets/169133634/ff24c14d-04e7-4c1d-a00c-fdf0dc70edaa)

### Expected behavior

When I start the program, I press configure - it takes about five minutes to load and the program is broken. It is not possible to use the program, it is not possible to update the version of prestashop. I noticed this error since presta stop version 8.1, because with 8.0.4 I still managed to update to version 8.0.5.

I noticed that the error is related to the pictures, on the new version of presta never have this error and everything works.

Somewhere in the forums it is written that you need to increase server resources, more ram, etc.

However, the solution is very simple, when you upload an empty image directory, everything works.

Make it so that there is no checking and counting of images by default, simply leave it to default to update prestashop without allowing and checking the image directory, whoever wants to, let them do backup, but by default do not touch the image directory.

### Steps to reproduce

1. go to prestashop 8.1.5 with 20k products with images when images innode 200k, with thousands folders
2.. go to 1-Click Upgrade 
3. see 5oo error page do not load

### PrestaShop version(s) where the bug happened

8.x

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

1-Click Upgrade

**Comment by Hlavtox** [comment]
What more to say here - you just need to backup your shop on your own, using external tools.

Having 20k of products is just a next level of "merchanting" and you need better tools than to run some script with 300s timeout, expecting it to backup gigabytes of data.

Do your own backup.
Disable backup in autoupgrade or comment it out in the code.
Run upgrade. :-)

**Comment by Quetzacoalt91** [comment]
This is likely related to the recursive check of writing access in the `img/` folder, and the module relies on PrestaShopTest class: https://github.com/PrestaShop/PrestaShop/blob/54275fab841dd851b1de249495afe54f09ded399/classes/ConfigurationTest.php#L307-L310

This folder is checked for restorations, where we bring back images saved in a backup.

There are 2 workarounds while we work on a potential fix:
* If you are sure the permissions have been granted in the whole folder `img/`, you can comment the value `img_dir` in https://github.com/PrestaShop/autoupgrade/blob/984d161450dc6d36c5daf202ed91e8ec564328e6/classes/UpgradeSelfCheck.php#L645
These checks can indeed take a while in shops with many files and folders.
* Run the upgrade via CLI

**Comment by LaurynasLTU** [comment]
I rename the image directory to image-2, upload a new presta default image directory and do the upgrade. But that is not written anywhere, it is a problem for thousands of people. And I discovered this after many trials and nerve wracking. There are already 600,000 innodes with presta on the server. When will you finally fix this mess with images.

**Comment by Hlavtox** [comment]
@LaurynasLTU 

> But that is not written anywhere, it is a problem for thousands of people. 

First off, this is not issue for thousands of people, when you are the first one to report it. There is obviously something wrong with your configuration, amount of data or bad permissions. I personally upgraded about 20 stores last month, and my colleague running a hosting company is regularily upgrading dozens of stores and there wasn't any issue about images.

> When will you finally fix this mess with images.

We are not your servants. You get this software for free. If you don't like it, don't use it. If you want to use it, fix the issue and contribute back, so when you do the next upgrade, it works flawlessly even on your server.

**Comment by florine2623** [comment]
ping @elyesnaouar for performance issue ^^

**Comment by venditdevs** [comment]
@LaurynasLTU, i would recommend to check your hosting performance/limitations. We have shops with a lot more products/images (biggest one has 250k+ products and 210K+ images) which update without a problem.

Most of the time it is a PHP limitation, let's say execution time, memory limit or another serverperformane related issue. considering the 5 minutes you've mentioned it's likely that your max_execution_time is set to 300. Keep in mind that there is a possibility that there's a overarching time-out setting on server level (Apache has this), if you don't have a own dedicated server you can configure you'll need to contact your hostingprovider.

![image](https://github.com/PrestaShop/PrestaShop/assets/14218917/1a250df0-f79e-44a9-81bd-3b7daf6c672e)

**Comment by centoasa** [comment]
max_execution_time to 300
max_input_time to 120
renamed img to img.old
created new folder named img
upgrade OK
Thank you so much!
