### ISSUE TITLE
"propriété Address-&gt;lastname n'est pas valide"

### ISSUE THREAD

**Issue by klorydryk** [PrestaShop/PrestaShop#36102]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Using module mdsmartpickup, we should get the addresses of the shop. If the name contains numbers, we get an error " La propriété Address-&gt;lastname n'est pas valide.". As I change the name of the shop to an alphabetic name, it works.

### Expected behavior

To get the shop address should work whatever the shop name contains.

### Steps to reproduce

install mdsmartpickup module
create a shop with a number in its name
select this shop address for delivery
-> we get the error.

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1.14 

### If your bug is related to a module, specify its name and its version

mdsmartpickup

### Your company or customer's name goes here (if applicable).

CRF

**Comment by Hlavtox** [comment]
Hi, this issue is related to third party module.
mdsmartpickup should not put numbers into lastname property of an adress.

**Comment by klorydryk** [comment]
The number don't come from the third party module but from the user (me). It is the name of the shop I put. The error trigger when the module read the name to write it into the delivery address of the order.
