### ISSUE TITLE
CartRule->checkValidity FatalThrowableError

### ISSUE THREAD

**Issue by Eva-F** [PrestaShop/PrestaShop#36115]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

when using a plugin that is connected to "hookActionCartSave", we get a FatalThrowableError in the CartRule->checkValidity function for older cookies.
These legacy cookies contain id_cart, which refer to a no longer existing record in table _DB_PREFIX_.'cart' (table _DB_PREFIX_.'cart' is periodically deleted by the abandoned cart plugin)
![checkValidity1](https://github.com/PrestaShop/PrestaShop/assets/3242659/d2678048-d0c6-4282-936d-e270f21e08a9)

### Expected behavior

the problem imho is caused that  **$context->cart** is not set

this simple patch of **/classes/controller/FrontController.php** solves our problem

````
   public function init()
// ...
        if ((int) $this->context->cookie->id_cart) {

            if (!isset($cart)) {
                $cart = new Cart($this->context->cookie->id_cart);
            }
            if (Validate::isLoadedObject($cart) && $cart->orderExists()) {
// ...
````
change to:
````
   public function init()
// ...
        if ((int) $this->context->cookie->id_cart) {

            if (!isset($cart)) {
                $cart = new Cart($this->context->cookie->id_cart);
            }
// adding lines 
	}
        if (isset($cart) && $cart->id && isset($context->cart) ) {
// adding lines 

            if (Validate::isLoadedObject($cart) && $cart->orderExists()) {
// ...
````
       

### Steps to reproduce

-

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

 7.3.33

**Comment by Hlavtox** [comment]
@Eva-F Hi, can you please provide a clearly reproducible scenario so we can test this? I fixed a very related issue to this - https://github.com/PrestaShop/PrestaShop/pull/33954, so I am interested if this isn't maybe also fixed?

Something like:
- Install module XY that hooks into actionCartSave.
- Create cart
- Create cart rule with settings A, B, C
- Delete this cart in database
- Go to FO bla bla bla

Thanks!

**Comment by Eva-F** [comment]
my sorry - I didn't realized all consequences of placing the condition 

``
isset($context->cart) 
``

should by just before 

``
$cart->update();
``

this way

````
 if ($to_update&& isset($context->cart)  ) {
      $cart->update();
 }
````

To @Hlavtox 

I am not able to describe the exact steps because I am only an external consultant who should try to solve the urgent problems with the eshop.

The tricky was that the cookie contained id_cart, which was created say 2 months ago and the related order was not created. Moreover (maybe) here played its role a voucher (here i am not sure) - the error occured thanks the affiliate plugin, that hooks "hookActionCartSave")
In db was this cart removed as abandoned and this obsolete cookie was a source of problem when FrontController initialized

And yes 

also ComputingPrecision->getPrecision() error occured before and was patched the similiar way as you did

but $cart->update() is called twice in init and our problem cas was related on /* Select an address if not set */

**Comment by florine2623** [comment]
Closing the issue as it cannot be reproduce on a native shop
