### ISSUE TITLE
errores en actualizacion de version

### ISSUE THREAD

**Issue by Mariscosanna** [PrestaShop/PrestaShop#36116]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

me da errores cuando intento cambiar de version en el modulo 1-clic
![Screenshot of 1-Click Upgrade _ 1-Click Upgrade • Pescados y mariscos Anna](https://github.com/PrestaShop/PrestaShop/assets/169261327/13c09a07-095a-4091-b38b-688fe8ece4f8)

### Expected behavior

actualizar a una nueva version de prestashop

### Steps to reproduce

al actulizar no me deja no hace nada.

### PrestaShop version(s) where the bug happened

1.7.7.7.0

### PHP version(s) where the bug happened

Versión PHP: 7.3.33

### Your company or customer's name goes here (if applicable).

pescadosymariscosanna.es

**Comment by Mariscosanna** [comment]
necesitaria ayuda rapida por favor gracias

**Comment by florine2623** [comment]
Hello,

It seems like you have an issue with the module that I cannot reproduce on my end.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
