### ISSUE TITLE
Problems OrderProductForViewing "must be of type string (or int), null given" and Memcached

### ISSUE THREAD

**Issue by DimitriBouriez** [PrestaShop/PrestaShop#36126]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I had a problem with retrieving the stock location for products that are no longer available when viewing an old order. Normally, this should return false when the stock location is not found. But when the Memcached cache is active, the null value is returned, causing a fatal error. This must be linked to the fact that Memcached doesn't distinguish between null and false. 

To correct my specific problem, I added the following processing at the end of the setProductCurrentStock() method in /classes/order/Order.php:
```
if ($product['location'] === null) {
    $product['location'] = false;
}
```

This ensures that false is returned and not null. 

The following issues seem to be affected by a similar bug: 
[#22215](https://github.com/PrestaShop/PrestaShop/pull/22215)
[#35753](https://github.com/PrestaShop/PrestaShop/pull/35753)
[#35979](https://github.com/PrestaShop/PrestaShop/pull/35979)

### Steps to reproduce

1. Enable Memcached cache
2. Create an order
3. Delete an ordered product from the catalog
4. View order

### PrestaShop version(s) where the bug happened

8.1.2

**Comment by florine2623** [comment]
Hello @DimitriBouriez ,

Do you have the same issue with memcached disabled ?

Thanks!

**Comment by DimitriBouriez** [comment]
Hello @florine2623 ,
Once the Memcached cache is deactivated, everything works as expected.
Regards,

**Comment by florine2623** [comment]
@PrestaShop/qa-functional 
Can someone try to reproduce this issue please ? I'm encountering [this error](https://github.com/PrestaShop/PrestaShop/issues/34313) while testing.

**Comment by Arnaud140** [comment]
I'm having the same issue on PrestaShop 8.1.6, after deleting a product, the order becomes inaccessible...
I disabled Memcached and it works now, it's a shame not to have another solution

**Comment by matks** [comment]
Issue can be analyzed after https://github.com/PrestaShop/PrestaShop/issues/34313 is fixed

**Comment by matks** [comment]
As I'm able to setup memcached, I was able to
- reproduce the bug 👍 
- validate the fix

@DimitriBouriez Would you submit a Pull Request with your code changes?

![Capture d’écran 2024-07-08 à 16 01 09](https://github.com/PrestaShop/PrestaShop/assets/3830050/2bbf32e9-f118-43b0-8e53-7db1d835554e)

**Comment by ShaiMagal** [comment]
Author isn't responding one month, so I made this small PR #36662

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/36662
