### ISSUE TITLE
Search_bar_module version  2.1.3

### ISSUE THREAD

**Issue by WWW-HTTP** [PrestaShop/PrestaShop#36128]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello everyone
I need help!
The search module version 2.1.3 is displayed incorrectly, not in full width and length.
![PIC3](https://github.com/PrestaShop/PrestaShop/assets/169485175/708ae9be-9f59-4703-97dc-30599db5ad2d)

### Expected behavior

![Correct_bar](https://github.com/PrestaShop/PrestaShop/assets/169485175/ab327d8c-fe84-4e0c-aa15-acabd9e23940)

### Steps to reproduce

The module was re-downloaded but w/o any improving the problem

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.3.28

### If your bug is related to a module, specify its name and its version

Search bar by PrestaShop version 2.1.3.

**Comment by Hlavtox** [comment]
Hi, this is an issue of your third party theme, you need to contact the author.
