### ISSUE TITLE
Defaut shipping are not set for visitors when geolocation is enabled

### ISSUE THREAD

**Issue by momo1240** [PrestaShop/PrestaShop#36133]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello guys,
I've noticed an issue on Prestashop when Geolocation is enabled.
instead of displaying default country shipping costs for visitors, shipping is set ''to free shipping''
I think it is because detected IP country is used as default country.
I've set France as default country in "international/localization/parameters"
Default carrier is also set (here cheapest ) and enabled for all groups (visitors, etc..)
When geolocation is disabled, default country shipping costs are set.
When geolocation is enabled : 
-acess from default country Ip (France) : default shipping costs are set for visitors
-access from non default country IP (UK for example ) : displays free shipping for visitors
Thank you 

### Expected behavior

By default Prestashop should use default country shipping carrier for visitors
regardless of detected visitor ip

### Steps to reproduce

1.setup a default country
2.setup default carrier (carrier name, cheapest, best grade etc) for all groups
3.enable Geolocation
4. access to shop from non default country ip using a vpn
5. add a product to cart as visitor

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

PHP 7.4.33

### If your bug is related to a module, specify its name and its version

no

**Comment by florine2623** [comment]
Hello @momo1240 ,

Your issue is similar to : https://github.com/PrestaShop/PrestaShop/issues/19134

Could you confirm ?
Thanks!

**Comment by paulnoelcholot** [comment]
Hello @momo1240,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
