### ISSUE TITLE
Redirected Back to Step 1 When Choosing Another Country at Checkout

### ISSUE THREAD

**Issue by liger24** [PrestaShop/PrestaShop#36131]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Let's say the default country set for the shop is France. When you proceed to checkout as a guest and move to the next step to create your first address and you choose another country, like Germany, and submit the form, you'll be redirected back to step 1. You'll then need to click "continue" again, go to the "address" step, and from there you can finally proceed.

The issue arises because after saving the form, the country and cookie country don't seem to update immediately. Despite several attempts, including using a custom module and hooks, I couldn't successfully set the correct country immediately after submitting the form. This bug or whatever it should be called exists in Prestashop 1.7, 8x. Didn't try older ones. Even the Prestashop live demo has this bug.

### Expected behavior

If a customer chooses another country during checkout, the country in the context should be updated immediately. Currently, customers are cancelling their purchases because they mistakenly believe there's an issue with the shop. After submitting the form, the country should be set to the newly chosen one right away. For instance, if I do this within a module's constructor and choose Germany (with 1 representing Germany), it works fine because the country is correctly set. However, finding where to implement this fix has been challenging. I've looked through classes and controllers but haven't found the appropriate place to add it.

Simple example which seems to fix (but of course its not the solution): 
      $default_country = new Country(1); 
        $context = Context::getContext();
        $context->country = $default_country;
        $context->cookie->iso_code_country = 'DE';
        
       

### Steps to reproduce

1. Proceed to Checkout.
2. Choose to Continue as a guest.
3. Select a country different from the default one.
4. You'll be redirected back to step 1.
5. Continue once more, and now the address should be set correctly.

### PrestaShop version(s) where the bug happened

1.7.8.11 - 8 

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @liger24 ,

I can't reproduce your issue :

https://github.com/PrestaShop/PrestaShop/assets/16019289/9265f7aa-fca4-4aa4-bc4e-151dc793cb3d

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by liger24** [comment]
@florine2623 Thank you for your reply. Please check this video out:

https://github.com/PrestaShop/PrestaShop/assets/169559275/949711cf-56bb-4532-80b8-fb0bcd551a01
