### ISSUE TITLE
NPE when downloading credit slip for shipping only

### ISSUE THREAD

**Issue by fire2** [PrestaShop/PrestaShop#36130]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When trying to download a credit slip where only the shipping was reimbursed, a NPE exception is thrown. 

```
PrestaShop\PrestaShop\Core\Util\Sorter::natural0:Argument#1(Sarray) must be of type array, null given, called in
/public_html/classes/pdf/HTMLTemplateOrderSlip.phponline167
```

### Expected behavior

The credit slip can be downloaded just fine.

### Steps to reproduce

1. Refund just the shipping for an order (no products)
2. Go to "Credit slips" and try to download the generated credit slip
3. You get the NPE

### PrestaShop version(s) where the bug happened

8.1.4

**Comment by florine2623** [comment]
Hello @fire2 ,

I can't reproduce your issue :

https://github.com/PrestaShop/PrestaShop/assets/16019289/82434421-96f9-4f17-ac2f-82b2638656dd

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by fire2** [comment]
You're not even using the same PS version reported. 

Note to self: there's no point in reporting bugs.
