### ISSUE TITLE
Autoupgrade - Autoupgrade from 8.0.5 to 9.0.0 - Fatal Error with "_PS_PRICE_DISPLAY_PRECISION_"

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#36153]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you want to upgrade from 8.0.5 to 9.0.0 (last develop version) with an autoupgrade from dev branch ( like autoupgrade#690 ) as you can see : 

[recording(202).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/58583a03-541f-46a4-ab96-2a4c5fc99ff8)

### Expected behavior

I expect that I can go on my BO without Fatal Error 

### Steps to reproduce

1. Install a fresh version of 8.0.5 
2. install autoupgrade from dev branch (like autoupgrade#690)
3. Do an upgrade with a archive version to upgrade to develop 
4. At the end of the upgrade, clic on the dashboard 
5. You should Login into BO without Fatal Error 

### PrestaShop version(s) where the bug happened

8.0.5

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

autoupgrade v5.0.1 from dev branch 

### Your company or customer's name goes here (if applicable).

PS

**Comment by florine2623** [comment]
Hello @AureRita ,

I have reproduced your issue :

`Undefined constant "_PS_PRICE_DISPLAY_PRECISION_"
`
<img width="1031" alt="Screenshot 2024-05-15 at 10 51 52" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/a37c117a-f0de-4cf7-bbe5-b3ddb1251ef4">

https://github.com/PrestaShop/PrestaShop/assets/16019289/8b7b559d-00b0-4ddf-a171-f9de1629a97b

I have access to Dashboard page if a delete/rename the module dashtrends.
My module pages is not accessible, I have a blank page.

Thanks!

**Comment by Hlavtox** [comment]
@florine2623 @AureRita Usage of this had been removed from the module and released - https://github.com/PrestaShop/dashtrends/releases/tag/v2.1.3

You need to investigate why you dont have dashtrends 2.1.3 after update.

**Comment by Quetzacoalt91** [comment]
Need more investigation on this issue before closing it: The bug is likely to happen in the case where the module is manually installed. We can try reproducing it by uninstalling the module and reinstalling the old version by uploading a zip on the module manager.

**Comment by M0rgan01** [comment]
The subject was corrected following the PR https://github.com/PrestaShop/autoupgrade/pull/850
