### ISSUE TITLE
,,Failed to download'' - That's google search console said, when I paste site map.

### ISSUE THREAD

**Issue by Sciepkola** [PrestaShop/PrestaShop#36167]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

,,Failed to download'' - That's google search console said, when I paste site map.
Site map adress: https://sklep.s4honline.pl/1_index_sitemap.xml
What is the problem? That still doesn't work and I have no idea what to do.
I need help.

### Steps to reproduce

1. I generate site map in Presta Shop site map module. 2, I copy it ,,https://sklep.s4honline.pl/1_index_sitemap.xml'' 3. I paste it to google search console (sitemap) 4. I see ,, Failed to downald.'' 
(PS: I have tried https://sklep.s4honline.pl/1_pl_0_sitemap.xml too, and was the same  ,, Failed to downald.'' )

### PrestaShop version(s) where the bug happened

8.1.3

**Comment by florine2623** [comment]
Please explicit the steps to reproduce.

**Comment by Sciepkola** [comment]
Steps to reproduce - filled

**Comment by florine2623** [comment]
Are you talking about that : 

<img width="1125" alt="Screenshot 2024-05-15 at 16 25 08" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/a9dc2eaa-eae2-4f16-968b-5699bf08431c">

Can you send a screenshot ?

**Comment by Sciepkola** [comment]
![Zrzut_ekranu_2024-05-15_082128](https://github.com/PrestaShop/PrestaShop/assets/71154696/99ea97ec-6094-4c35-b7a4-bd566e782bc5)
About site map

**Comment by Hlavtox** [comment]
@Sciepkola As we can see, we can download your sitemap normally. Tis is an issue either with your server, or you blocking google IPs or there is an issue on google side.

**Comment by kpodemski** [comment]
Hello @Sciepkola 

This is not a PrestaShop bug. Sitemap is accessible via URL, Google cannot download it, as @Hlavtox correctly noticed, this might be related to your server configuration, maybe something prevents Google from reading XML files from your server. It is impossible for us to tell what exactly is going on.

**Comment by Sciepkola** [comment]
![Zrzut ekranu 2024-05-16 135346](https://github.com/PrestaShop/PrestaShop/assets/71154696/6989b659-c1c4-4bd2-9386-b0d4cbbc54d1)
 Thank you. My last question is could it be related to robot txt? Or it doesn't matter?
