### ISSUE TITLE
Remove email "Preview" from BO section "Statutes" (because it's not working)

### ISSUE THREAD

**Issue by ShaiMagal** [PrestaShop/PrestaShop#36165]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Preview button is not working and customers are confused and consistently reporting problem to developers, very difficult to explain it's "security feature", because customers are asking "Why is there button Preview, if it's not working"...

Real issue from real production environment.

![1](https://github.com/PrestaShop/PrestaShop/assets/8518736/d8017c3c-4734-418e-9c64-1704d3a078fd)
![2](https://github.com/PrestaShop/PrestaShop/assets/8518736/be57f40e-c16b-4a03-80dd-4af6e5bb43b2)

### Expected behavior

Preview will show email content only for logged BO users, but it can be a **lot of edits**, so for now **it's better to hide button "Preview" at least.** Maybe in future improve it.

### Steps to reproduce

1. Go to BO to section "Statutes"
2. Open any State with "Send email to customer" enabled
3. Scroll down and click on button "Preview"
4. Popup will appears, but we see only error 403 Forbidden (because of security protection of email contents from outside)

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

openservis.cz

**Comment by florine2623** [comment]
Hello @ShaiMagal ,

On `develop` branch, it works correctly :

https://github.com/PrestaShop/PrestaShop/assets/16019289/6e3ffc91-0538-4d00-bddf-747b8d4b2bb6

On PS 8.1.x, I do have a forbidden message.

The feature can be left as is. What do you think @MatShir ?

**Comment by sharkooon** [comment]
I reported that issue in 2020, still no fix!
https://github.com/PrestaShop/PrestaShop/issues/17759

**Comment by Hlavtox** [comment]
@ShaiMagal @sharkooon Fixed on develop branch by migration to symfony

**Comment by ShaiMagal** [comment]
I think we can hide it for next 8.1.6 release... Becase every second customer is reporting this problem. It's boring to still "explain" people same think "sorry, it's bug and noone fixed it"...

It makes no sense leave it there if this is not working... Because it looks like bug (in reality this is bug) - so better is to hide it........

**Should I make PR for hiding this "non working feature"?**

**Comment by ShaiMagal** [comment]
I make PR here https://github.com/PrestaShop/PrestaShop/pull/36171
It's not "fix", but removing/hiding is better option, than leave it non working for 4 years! (https://github.com/PrestaShop/PrestaShop/issues/17759)

In developer branch, it's fixed already.

If we update any customer to 8.1.5, they are complaining about this "not working", so, when we hide this, customer will not reporting problem. Not best option, but better than leave this bug there X more years I think.......

**Comment by Tanguy-SALMON** [comment]
Really glad to discover that feature, thanks @ShaiMagal for that.
Btw, this feature look to work perfectly for me on PS 8.1.5:

![image](https://github.com/PrestaShop/PrestaShop/assets/6756795/188d2340-3530-420d-9a8a-61ea1dd398f6)

**Comment by florine2623** [comment]
@amine-O what do you think about that ?

**Comment by ShaiMagal** [comment]
@florine2623 I think, we should close this issue, because already done by PR #36171 (merged)
