### ISSUE TITLE
Traductions files ignored when symlink

### ISSUE THREAD

**Issue by Jeremie-Kiwik** [PrestaShop/PrestaShop#36161]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The Finder used to search traduction files does not follow symlinks by default. Which is a major problem when working with modern and robust solutions like Deployer.

On those environments, each GIT release is in a specific folder, and the "living" files (traductions, images...) are in a common shared folder. And symlinks are made to point to the shared folder.

So for now, all the traduction files are ignored by Presta, as they are symlinks.

### Expected behavior

Also parse symlinked traduction files

### Steps to reproduce

- Move a traduction file somewhere else on your filesystem (mainly Linux)
- make a symlink (for example: ln -fs /moved/file /original/place)
- rm Prestashop cache (rm var/cache/*/translations -Rf)
- navigate to a page
- check the traductions are no longer visible

### PrestaShop version(s) where the bug happened

1.7.8 to 9.0

### Your company or customer's name goes here (if applicable).

KIWIK (kiwik.com)

**Comment by Tanguy-SALMON** [comment]
I don't know if that can help, simlink does not transfert permissions...
Btw, I nerver did a rm on only a particular item in the cache directiory like you did. 
Do you have the problem if you rm on all cache file?

**Comment by Jeremie-Kiwik** [comment]
This is not related to the cache files. You can indeed `rm -rf var/cache`. The problem is that the new generated cache file of traductions will not have all the traductions, as the native PS code will ignore symlinks:
- it parses `app/Resources/translations` for regular files,
- it concatenates them all in a cache file,
- and put the result in `var/cache/traductions/xxx`.

But in "Deployer" environment, we only have symbolic links in `app/Resources/translations`, pointing to a "shared" folder elsewhere. So Presta ignores them. And do not add them in the generated cache file.

**Comment by Tanguy-SALMON** [comment]
I don't know if that can help, did you tried to bind the directory?
mount --bind /some/where /else/where

**Comment by Jeremie-Kiwik** [comment]
Mmh, this should work. You're right. But you also have traductions folders in every module. Which would generate a hudge number of mounts.

To my mind, patching as I did in the PR is the best approach, as it does not impact the server. It just takes care of every files.
