### ISSUE TITLE
Customer addresses persist in the XML even after deletion from FO or BO ( WEBSERVICES )

### ISSUE THREAD

**Issue by NicolaMazzaferroCoimaf** [PrestaShop/PrestaShop#36181]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If I delete an address from a user's profile, it doesn't actually delete in the database and therefore my xml has saved addresses that my users don't have.
![Screenshot 2024-05-17 094904](https://github.com/PrestaShop/PrestaShop/assets/156414093/79db01cc-1000-4303-a554-103f9dd13638)
![Screenshot 2024-05-17 095058](https://github.com/PrestaShop/PrestaShop/assets/156414093/5c0bdaa3-21a7-4694-adc8-3ccdca8216f0)

### Expected behavior

When I delete an address from my profile it should also be deleted in the API

### Steps to reproduce

1. Create user
2. Add Address
3. Delete Address
4. Check www.site.it/api/addresses

### PrestaShop version(s) where the bug happened

8.1.5

**Comment by Hlavtox** [comment]
Address is not deleted permamently sometimes, but only softdeleted - flagged with `deleted = 1` in the database. That's the reason why you see some more addresses in the XML.

**Comment by NicolaMazzaferroCoimaf** [comment]
> Address is not deleted permamently sometimes, but only softdeleted - flagged with `deleted = 1` in the database. That's the reason why you see some more addresses in the XML.

Right! I hadn't noticed  `deleted = 1`

In this case I can manage via 1 - 0.

Besides this solution, can I make sure that an address is permanently deleted?

**Comment by paulnoelcholot** [comment]
FYI @PrestaShop/product-council 

What do you think about that? Bug? Feature? Expected behavior?

**Comment by Hlavtox** [comment]
@NicolaMazzaferroCoimaf If it doesn't appear in the XML, it's deleted.

If there is an order for this adress = soft delete.
If there is no order for this address = permanent delete. :-)

**Comment by NicolaMazzaferroCoimaf** [comment]
> @NicolaMazzaferroCoimaf If it doesn't appear in the XML, it's deleted.
> 
> If there is an order for this adress = soft delete. If there is no order for this address = permanent delete. :-)

Yes, I mean if I use deleted = 1/0 I do a soft delete.

To do a permanent delete I can simply use:
```

    $webService->delete([
        'resource' => 'addresses',
        'id' => $id,
    ]);
```
