### ISSUE TITLE
Autoupgrade - From 8.0.5 to 8.1.6 - FO is blank

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#36184]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I upgrade from a Prestashop version 8.0.5 to 8.1.6 by a major version, I have a blank FO as you can see : 

[recording(205).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/ff2f2a68-d5ee-4d9b-abfb-267b88649336)

FYI : I didn't have this issue with 8.1.5 and 1.7.8.11

### Expected behavior

I wish I could use my FO after the upgrade

### Steps to reproduce

1. Install a fresh 8.0.5
2. Go to BO > Modules > Modules Manager
3. Install Autoupgrade (1-Click Upgrade)
4. Clic on configure 
5. Select the Major version 
6. Do the upgrade 
7. After the upgrade, clic on view my shop :x: 

### PrestaShop version(s) where the bug happened

8.0.5

### PHP version(s) where the bug happened

7.4 and 8.1

### If your bug is related to a module, specify its name and its version

autoupgrade v5.0.1

### Your company or customer's name goes here (if applicable).

PS

**Comment by Hlavtox** [comment]
@AureRita 

> Avoid reporting "error 500" or "white page" errors - this is a universal error message that does not provide enough information to qualify the issue. Enable debug mode in the Performance section of PrestaShop or manually in /config/defines.inc.php and try again. You should get a proper error message.
