### ISSUE TITLE
Edit Layout of template button link going in module page

### ISSUE THREAD

**Issue by tone87** [PrestaShop/PrestaShop#36192]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

i cannot edit layout of theme installed.
The link going on module page but not in layout configuration
Prestashop 8.1.6
PHP 8.1.28

https://github.com/PrestaShop/PrestaShop/assets/8173557/98ad82b0-fe35-4562-a6f1-58c7d1b3f2c3

https://github.com/PrestaShop/PrestaShop/assets/8173557/32898645-3238-4969-8017-9425f9f693a4

### Steps to reproduce

Design -> customization

### PrestaShop version(s) where the bug happened

8.1.6

### PHP version(s) where the bug happened

8.1.28

### Your company or customer's name goes here (if applicable).

Fershop.it

**Comment by Hlavtox** [comment]
Hi, this is an issue of your 3rd party theme. You must contact the author to fix the bundled module(s).

**Comment by tone87** [comment]
are you sure ? because the author show me in same version a different page then my screenshot .. 
maybe is related to edition basic ? 
i installed 8.1.6 from an update and i have a multistore 
![image](https://github.com/PrestaShop/PrestaShop/assets/8173557/7216d7e2-4189-419e-b49e-f6240d611e3a)

**Comment by Hlavtox** [comment]
Yeah, maybe the things bundled with the prestashop.com edition are the issue.

**Comment by tone87** [comment]
i founded the module cause this bug , is a new module "Prestashop Design"
when is disabled working all goods
![image](https://github.com/PrestaShop/PrestaShop/assets/8173557/c8ec4341-3a8c-4656-8988-dba3b67814a5)

**Comment by Hlavtox** [comment]
Ping @PrestaShop/prestashop-sa
