### ISSUE TITLE
During the installation process, at the "Install Module" step, the message "1: HTTP 500 - error -" appears. " error

### ISSUE THREAD

**Issue by LaoJiuYes** [PrestaShop/PrestaShop#36196]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

![image](https://github.com/PrestaShop/PrestaShop/assets/53503340/5349e12c-3700-444e-9d9d-ac3d5a481290)
During the installation process, at the "Install Module" step, the message "1: HTTP 500 - error -" appears.
" error.
I've tested this in a number of ways, including local VM testing, VPS testing all of which have issues when it comes to this step.

### Steps to reproduce

During the installation process, at the "Install Module" step, the message "1: HTTP 500 - error -" appears.
" error.
I've tested this in a number of ways, including local VM testing, VPS testing all of which have issues when it comes to this step.

### PrestaShop version(s) where the bug happened

8.1.6

### PHP version(s) where the bug happened

8.1

**Comment by paulnoelcholot** [comment]
Hello @LaoJiuYes,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you

https://www.loom.com/share/5b13c53e360f4179b67eba3f84125415?sid=d4c46bf3-82ad-4572-b79f-f5966dc390eb

**Comment by LaoJiuYes** [comment]
> Hello @LaoJiuYes,
> 
> Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.
> 
> We will close this issue.
> 
> Thank you
> 
> https://www.loom.com/share/5b13c53e360f4179b67eba3f84125415?sid=d4c46bf3-82ad-4572-b79f-f5966dc390eb

Hello and thank you for your reply! I am following your documentation to configure php and Apache environment. I don't understand what went wrong with the configuration and you want to close this issue, then well, I have to give up using PrestaShop. there is nothing I can do about it.
