### ISSUE TITLE
Autoupgrade - Upgrade to 9.0.0 - When you want to go on 1 Click Upgrade, you don't have the right 

### ISSUE THREAD

**Issue by AureRita** [PrestaShop/PrestaShop#36202]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, When I do an upgrade from version 8.x.x to 9.0.0, I'll have an exception when I want to go on 1 click Upgrade (to rollback for example) as you can see : 

[recording(208).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/07ee16df-0ae2-451e-81cf-114fe1afa97b)

### Expected behavior

I wish I could use the module after the upgrade 

### Steps to reproduce

1. Install a fresh Prestashop 8.1.6 
2. Install a autoupgrade in dev version (for example https://github.com/PrestaShop/autoupgrade/pull/699) 
3. Do a manual upgrade to 9.0.0 
4. Go on the BO of 9.0.0 
5. Clic on the 1-Click Upgrade shortcut 
6. You'll have the exception 

### PrestaShop version(s) where the bug happened

8.x.x

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

autoupgrade v5.0.1 from dev branch 

### Your company or customer's name goes here (if applicable).

PS

**Comment by Quetzacoalt91** [comment]
Duplicates https://github.com/PrestaShop/PrestaShop/issues/36212, where the fix was linked https://github.com/PrestaShop/PrestaShop/pull/36229.
