### ISSUE TITLE
New product page: category of a product cannot be modified/searched

### ISSUE THREAD

**Issue by Tofandel** [PrestaShop/PrestaShop#36205]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

https://github.com/PrestaShop/PrestaShop/assets/6115458/b1911da0-6af5-45b5-9eba-b1b45ab676a8

### Expected behavior

Categories to be searchable and editable

### Steps to reproduce

1. Go to the Experimental feature section and enable the new product page
2. Go to a product and try to edit the category

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.1.28

### Additional information

The old product page works fine
![image](https://github.com/PrestaShop/PrestaShop/assets/6115458/961da956-3d20-4640-9bdd-f60e8f0cea47)

No requests are happening when searching, I don't know if it's supposed to though as the old one doesn't seem to make any request either
No js errors either
A request is happening when opening the category modal like so `/admin.../index.php/sell/catalog/categories/tree?_token=xxx` but returns `[]`

**Comment by Hlavtox** [comment]
@Tofandel I had a simmilar issue on one of my stores, can you please check if in `ps_category_lang` there is a record for id_category 1 in all languages?

**Comment by Tofandel** [comment]
Thanks, I checked and it was missing so I created it, but still the same issue even after clearing the cache

I have a different root category, maybe that's related? But even with it active like this it still returns `[]`
![image](https://github.com/PrestaShop/PrestaShop/assets/6115458/78bb3f4b-a3bc-40f5-bef5-223e0f9573d9)


It now looks like this (I can provide a dump of a few categories if that helps)
![image](https://github.com/PrestaShop/PrestaShop/assets/6115458/ac28eaa6-c6f8-4dcd-9a65-19b755d7d085)
![image](https://github.com/PrestaShop/PrestaShop/assets/6115458/89e18f95-3f1a-4765-ae5f-b70b83569352)

Do you know where is the code for the `sell/catalog/categories/tree` controller? No idea where to look for, but if I know I can debug the issue

**Comment by Hlavtox** [comment]
@Tofandel It should look like this, and there must be a record in lang table for every category and lang.

![Snímek obrazovky 2024-05-21 152756](https://github.com/PrestaShop/PrestaShop/assets/6097524/81a72ba4-5826-4586-86d8-8f3ab1b05074)

I think it's `/src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController::getCategoriesTreeAction`

**Comment by Tofandel** [comment]
Ah I got it to work, I had to resave any category to clear the cache
![image](https://github.com/PrestaShop/PrestaShop/assets/6115458/26464708-b996-4fd3-9bfe-d9133f96d15a)

So yes seems the missing translation for the root category is indeed an issue when migrating from much older prestashop database

**Comment by paulnoelcholot** [comment]
Hello @PrestaShop/product-council, 
What do you think about that? For me, old product is not anymore maintained, only for critical bug.

**Comment by ibahloul-ps** [comment]
Thanks for your feedback!
