### ISSUE TITLE
Display bug footer link - EMERGENCY

### ISSUE THREAD

**Issue by OupsDady** [PrestaShop/PrestaShop#36206]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I am taking the liberty of contacting you, because despite my research I am unfortunately bredouille.
The problem is that my Link List is disconnected for no apparent reason. 

It worked for more than 3 months and then the drama. ^^

![Footer bug](https://github.com/PrestaShop/PrestaShop/assets/170365377/45e309cb-eb49-4fa3-a1b8-70436ff30e85)

I'd like to ask you a quick question: do you know why a menu is displayed like this?
And more importantly, how do you get it to display correctly ?

### Steps to reproduce

No special manipulations, it simply appears like this. 

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

8.1.28

### If your bug is related to a module, specify its name and its version

Link List v6.0.7

**Comment by paulnoelcholot** [comment]
Hello @OupsDady,

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Thank you
