### ISSUE TITLE
Uploading win10 local source code to a remote server prompts HTTP ERROR 500 【请求帮助！！！谢谢！】

### ISSUE THREAD

**Issue by stuffren** [PrestaShop/PrestaShop#36201]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have created website in win10 local wsl2 using prestashop open source program, which currently works fine on win10.
I uploaded the source code from the root directory of the website /var/www/ucoredata to the /var/www/ucoredata.tech directory on the remote server via scp.
At the same time, I also created a mysql database prestashop on the remote server and imported the local sql database into prestashop.
I used the virtual domain ucoredata.com locally for testing and development.
I have used the real domain ucoredata.tech on the remote server
I have changed the virtual domain ucoredata.com to www.ucoredata.tech in the remote database.

Currently when I visit www.ucoredata.tech through my browser, it prompts:
This page is not functioning properly www.ucoredata.tech cannot process this request at this time.
HTTP ERROR 500

Looking forward to your help and answers, thanks in advance! Thanks in advance!

Visit the frontend
![01](https://github.com/PrestaShop/PrestaShop/assets/136626456/1133b19c-24fa-4119-a8ef-b8501d94f868)

Visit Backend
![02](https://github.com/PrestaShop/PrestaShop/assets/136626456/34313e11-169c-4647-9198-9a28aa16cb60)

### Expected behavior

The site can be accessed normally

### Steps to reproduce

Environment test: Upload environment test file
scp phppsinfo.php stuffren@192.3.112.214:/var/www/ucoredata.tech/
![03-phppsinfo](https://github.com/PrestaShop/PrestaShop/assets/136626456/185eec15-bc8f-48e5-9b9d-4cc200d61db4)

As you can see based on the screenshot, my configuration almost always matches the environment configuration officially required by prestashop.

Step 1. Package the source code in win10 local wsl2

Step 2: Upload the packaged file to the server using the scp command

Step 3: Unzip the file

Step 4: Create a new database
Name, login and password of the mysql database in the remote server.
Keep the same name, login name and password of the database in the remote server as the mysql database in the local wsl2.

### PrestaShop version(s) where the bug happened

8.1.5;I didn't do the upgrade, it has nothing to do with the upgrade

### PHP version(s) where the bug happened

PHP 8.1.2-1ubuntu2.17 (cli) (built: May  1 2024 10:10:07) (NTS)

### If your bug is related to a module, specify its name and its version

no

### Your company or customer's name goes here (if applicable).

no

**Comment by SharakPL** [comment]
First of all you may want to get a [fresh copy of phppsinfo](https://raw.githubusercontent.com/PrestaShop/php-ps-info/master/phppsinfo.php) from GitHub to have current requirements.

When you upload your store from localhost to a remote server there are few places that need to be updated.
1. In your database dump change any occurrence (there's at least 4) of your localhost shop domain to match the online domain eg. change localhost:8001 to mydomain.com
2. On your server the prime requirement is to update app/config/parameters.php. Even if you use the same database settings as on your localhost, you still need to make sure the host and port are correct. Servers don't always use localhost or 127.0.0.1 with port 3306.
3. If you packed all files to be sent to your server then you need to make sure to remove the old cache. Just clear all the contents of var/cache/

You may also want to update your .htaccess in the root of your shop to also match the new shop domain, but you could also regenerate it from the admin panel.

You also need to regenerate mail templates because they also include references to localhost domain.

**Comment by stuffren** [comment]
> First of all you may want to get a fresh copy of phppsinfo from GitHub to have current requirements.
> 
> When you upload your store from localhost to a remote server there are few places that need to be updated.
> 
> 1. In your database dump change any occurrence of your localhost shop domain to match the online domain eg. change localhost:8001 to mydomain.com
> 2. On your server the prime requirement is to update app/config/parameters.php. Even if you use the same database settings as on your localhost, you still need to make sure the host is correct. Servers don't always use localhost or 127.0.0.1
> 3. If you packed all files to be sent to your server then you need to make sure to remove the old cache. Just clear all the contents of var/cache/
> 
> You may also want to update your .htaccess in the root of your shop to also match the new shop domain, but you could also regenerate it from the admin panel.
> 
> You also need to regenerate mail templates because they also include references to localhost.

----------------------
Thanks @SharakPL, for your patience, I followed the first, second and third steps you told me.
1. in the database, replaced all the fields of ucoredata.com with www.ucoredata.tech
2. in app/config/parameters.php, I made sure that the database address is localhost, because I can access http://Server IP Server IP address/phpmyadmin/ normally, and the phpmyadmin homepage shows the server address as server: localhost:3306. the login name and password I configured are working fine.
3. I deleted all the cache files in the var/cache/ directory

Finally I restarted apache2 and mysql.
Still can't access www.ucoredata.tech

Can you please help me see where else I need to tweak or modify?

If it was you who needed to upload the prestashop source code and mysql database, from your local wsl2 to a remote server (lamp environment), what are the necessary steps you would take?

**Comment by SharakPL** [comment]
Make sure everything is exactly as it should be. Is your domain name `ucoredata.tech` or `www.ucoredata.tech`. You'll get into the redirections loop if you get it wrong.

Try to access your admin panel first.

**Comment by stuffren** [comment]
> Make sure everything is exactly as it should be. Is your domain name `ucoredata.tech` or `www.ucoredata.tech`. You'll get into the redirections loop if you get it wrong.
> 
> Try to access your admin panel first.

Currently accessing the admin panel, it still prompts:
![02](https://github.com/PrestaShop/PrestaShop/assets/136626456/ba17ee06-cd36-4941-a51b-1091bf788377)

**Comment by stuffren** [comment]
This is the configuration file for my website

ucoredata.tech.conf
<VirtualHost *:80>
    ServerAdmin ucoredata@hotmail.com
    ServerName ucoredata.tech
    ServerAlias www.ucoredata.tech
    DocumentRoot /var/www/ucoredata.tech
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
RewriteEngine on
RewriteCond %{SERVER_NAME} =ucoredata.tech [OR]
RewriteCond %{SERVER_NAME} =www.ucoredata.tech
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

ucoredata.tech-le-ssl.conf
<IfModule mod_ssl.c>
<VirtualHost *:443>
    ServerAdmin ucoredata@hotmail.com
    ServerName ucoredata.tech
    ServerAlias www.ucoredata.tech
    DocumentRoot /var/www/ucoredata.tech
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateFile /etc/letsencrypt/live/ucoredata.tech/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/ucoredata.tech/privkey.pem
</VirtualHost>
</IfModule>

Can you please help me to see if it will conflict with the prestashop configuration?

**Comment by stuffren** [comment]
Sincerely, I have a question for you:
If it's you, and you need to upload the prestashop source code and sql files that already have data from win10 local wsl2 to ubuntu server (lamp environment), what are the steps that you would take in order to get the site up and running?

**Comment by SharakPL** [comment]
@stuffren I already explained required steps in my [1st post](https://github.com/PrestaShop/PrestaShop/issues/36201#issuecomment-2121748924) 😉

If it doesn't work for you then either you have misconfiguration in your **app/config/parameters.php** or within your server config.
First of all I recommend setting `memory_limit` to at least 512M.
Then enable dev mode to get more specifics on the error instead of just error code 500. Make sure error_reporting is enabled on your server and then change **config/defines.inc.php** from
![obraz](https://github.com/PrestaShop/PrestaShop/assets/5007456/e3f99211-4044-4704-9300-3eafa14d0777)
to
![obraz](https://github.com/PrestaShop/PrestaShop/assets/5007456/c6276945-6640-4ebf-86f4-ed6339bb1378)

**Comment by SharakPL** [comment]
Closing. This is not a bug. Just a user's misconfiguration.

Please [join Slack](https://www.prestashop-project.org/slack/) or [start a discussion](https://github.com/PrestaShop/PrestaShop/discussions/categories/q-a) if you need help with your shop.

**Comment by stuffren** [comment]
Even though my problem was not solved, I still appreciate your response! Thank you!

Finally, I suggest prestashop official to write a tutorial on **《How to publish win10 local prestashop source code and mysql database to server》**.
