### ISSUE TITLE
Initialization Error in TaxManagerModuleCore Class

### ISSUE THREAD

**Issue by andreapozza** [PrestaShop/PrestaShop#36217]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the abstract class `TaxManagerModuleCore`, the `hookTaxManager` method returns a new instance of the current class (`new $class()`). However, the returned class should be initialized with two mandatory arguments: `address` and `type`. This initialization error can lead to malfunctions and unexpected behavior of the module.

### Expected behavior

The `hookTaxManager` method should return a new instance of the current class correctly initialized with the `address` and `type` arguments.

### Steps to reproduce

1. Create a custom module that extends the `TaxManagerModuleCore` class.
2. Implement the `hookTaxManager` method in the custom module.
3. Run the module in Prestashop.

### PrestaShop version(s) where the bug happened

1.7.x, 8.x

**Comment by AureRita** [comment]
Hi @andreapozza 

Thank you for your report and sorry for the time spend on your issue, can you provide us the exemple module to test your issue ? 

Waiting for your feedback

**Comment by florine2623** [comment]
Friendly reminder @andreapozza

**Comment by andreapozza** [comment]
I recently attempted to develop a custom module that extends the core module's functionality and encountered an issue in the process.

**Comment by florine2623** [comment]
I will close this issue as it cannot be reproduced.

If you can provide a module to test, please re-open an issue so we can test it and confirm the bug.
