### ISSUE TITLE
Incomplete Hook Registration in TaxManagerModuleCore Class

### ISSUE THREAD

**Issue by andreapozza** [PrestaShop/PrestaShop#36219]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the `TaxManagerModuleCore` class, the `install` method registers the module to the `taxManager` hook. However, this is insufficient for proper functionality. The module should also be registered to the `actionTagManager` hook to ensure complete integration with the tax management system.

### Expected behavior

The module should seamlessly integrate with the tax management system, handling tax calculations and related tasks effectively.

### Steps to reproduce

1. Develop a custom module that extends the `TaxManagerModuleCore` class. This module will serve as a test case to demonstrate the incomplete hook registration issue.

2. Utilize the `Hook::getModulesFromHook(Hook::getIdByName('taxManager'));` method within the custom module. This will retrieve a list of modules registered to the `taxManager` hook.

3. Verify that the custom module is not included in the retrieved list of modules. This confirms that the `TaxManagerModuleCore` class is not properly registered to the `actionTagManager` hook.

### PrestaShop version(s) where the bug happened

develop

**Comment by AureRita** [comment]
Hi @andreapozza 

Thank you for your report and sorry for the time spend to answer you. Can you provide us a module to test your issue ? 

Waiting for feedback

**Comment by florine2623** [comment]
friendly reminder @andreapozza

**Comment by andreapozza** [comment]
I recently attempted to develop a custom module that extends the core module's functionality and encountered an issue in the process.

**Comment by florine2623** [comment]
I will close this issue as it cannot be reproduced.

If you can provide a module to test, please re-open an issue so we can test it and confirm the bug.
