### ISSUE TITLE
Deprecated error on many pages. Prestashop 8.1.6 with PHP 8.2.16

### ISSUE THREAD

**Issue by CarlCBS** [PrestaShop/PrestaShop#36214]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I'm currently building an new PrestaShop 8.1.6 shop and had no issues until I tried to add a new user. I discovered that the file OptionsChecker.php was not uploaded to the server with FileZilla, so I uploaded it again. From that moment I have "deprecated" errors on practically everypage I edit in the back-end. Could this be PHP version related?

### Steps to reproduce

![error na aanmaken nieuwe gebruiker 01](https://github.com/PrestaShop/PrestaShop/assets/45594881/896abae3-79e1-426e-898e-32fbbf919398)
![error na adresgegevens invoer 05](https://github.com/PrestaShop/PrestaShop/assets/45594881/f7a01418-5f80-423b-aff8-a1bc6cd45e4f)

### PrestaShop version(s) where the bug happened

8.1.6

### PHP version(s) where the bug happened

8.2.16

### Your company or customer's name goes here (if applicable).

Caer boardsports

**Comment by jlores** [comment]
Hello,

Check https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/

"We recommend PHP 8.1. See the compatibility chart below for more details. (Although compatible, PHP 7.2.5 to 8.0 are not recommended since they reached their end of support"

**Comment by Hlavtox** [comment]
Hi @CarlCBS, two things here - deprecated messages are shown only in debug mode, depending on configuration of error reporting. Many are triggered from Prestashop side.

Regarding PHP compatibility - Prestashop 8.1.6 is NOT compatible with PHP 8.2. You need to switch to 8.1.

**Comment by CarlCBS** [comment]
Thank you for your response. It was indeed the PHP version. The problem is solved now.

Carl
