### ISSUE TITLE
Error loading "Paccofacile" module

### ISSUE THREAD

**Issue by Laura-BdG** [PrestaShop/PrestaShop#36218]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Good evening,

After trying to load the 'Paccofacile' form from the BO, the error below emerged after doing these actions:

The ZIP file of the module was not loaded, I thought it was a problem of the Prestashop marketplace and I was deactivating the module then but it was a bad idea because the error came back. I went into debug mode without understanding the problem and restored the last backup. I cleaned the cache but nothing ....

Compile Error: Declaration of WebserviceSpecificManagementPaccofaciletracking::setObjectOutput(WebserviceOutputBuilderCore $obj) must be compatible with WebserviceSpecificManagementInterface::setObjectOutput(WebserviceOutputBuilder $obj)
[Symfony\Component\ErrorHandler\Error\FatalError 0]

Thank you for your help.

Laura

### Steps to reproduce

1)The ZIP file of the module was not loaded, I thought it was a problem of the Prestashop marketplace and I was deactivating the module then but it was a bad idea because the error came back. 
2)I went into debug mode without understanding the problem and restored the last backup. 
3) I cleaned the cache but nothing ....

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

Paccofacile v.1.0.19

**Comment by Laura-BdG** [comment]
<img width="1058" alt="Screenshot 2024-05-23 alle 00 04 42" src="https://github.com/PrestaShop/PrestaShop/assets/160724004/e46ab24f-808e-41fd-8847-affe38f50f5e">

**Comment by Hlavtox** [comment]
Hi @Laura-BdG, you must contact the author of this module. :-)

**Comment by Laura-BdG** [comment]
Thanks
