### ISSUE TITLE
Discounts > Cart rules > Actions > Apply discount to > Selected product(s) is undefined behavior

### ISSUE THREAD

**Issue by fulldecent** [PrestaShop/PrestaShop#36225]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When setting up a discount, there is an option to define a discount based on "selected product(s)".

However, the in-line documentation (i.e. hover over this option) and the "help" button/screen on the right side of the page do not define this behavior.

Perhaps this discount applies to the "Condition > production selection" items. If so, it should specifically say that.

---

# Applicable best practice / mantra

Any error when pricing products can be very bad for a merchant. Therefore software for setting up pricing should be reliable and unambiguous.

### Expected behavior

An in-line popup clearly and unambiguously explains how the pricing discount will be applied.

### Steps to reproduce

Go here and click this:

![Screenshot 2024-05-23 at 16 08 25](https://github.com/PrestaShop/PrestaShop/assets/382183/417ac33f-5f95-4f0c-bdcb-904b271a9e66)

### PrestaShop version(s) where the bug happened

8

**Comment by AureRita** [comment]
Hi @fulldecent 

Thank you for your report, currently, when we want to select this behavior, we have a little details under the behavior as you can see : 

[recording(222).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/78d1b4ee-a35c-4e92-a50a-a6837e3552b8)

If you are aggree with that I think I can close this issue 

Waiting for your feedback

**Comment by fulldecent** [comment]
That additional information is only show if no products have been selected. 

In the case that products have been selected, ([screenshot at top](https://github.com/PrestaShop/PrestaShop/issues/36225#issue-2313752949)) this context is missing.

A good fix here would be to show a similar tip like "This applies to products selected on the CONDITIONS tab" in the situation at top.

**Comment by ibahloul-ps** [comment]
Hello @fulldecent,
Thanks for you feedback!
You can directly contribue to the [documentation](https://github.com/PrestaShop/user-documentation-en/blob/master/user-guide/selling/managing-catalog/managing-discounts/cart-rules.md) if you want to add some details like that :)

FYI, we are going to migrate the cart rules screen, we'll take into account your feedback.

Have a good day
