### ISSUE TITLE
Tooltip missing for Cart Rule / Status

### ISSUE THREAD

**Issue by fulldecent** [PrestaShop/PrestaShop#36222]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Tooltip is missing here
![Screenshot 2024-05-23 at 11 57 07](https://github.com/PrestaShop/PrestaShop/assets/382183/e58d91a5-6ab9-46b8-90be-3b2b208c3234)

### Expected behavior

Similar tooltip like this:

![Screenshot 2024-05-23 at 11 57 09](https://github.com/PrestaShop/PrestaShop/assets/382183/50c123a5-d48e-4cae-9fcd-26a0dd61649a)

### Steps to reproduce

Visit admin####/index.php?controller=AdminCartRules&addcart_rule&token=####

### PrestaShop version(s) where the bug happened

8

**Comment by paulnoelcholot** [comment]
Hello @fulldecent,

I reproduce the issue with PrestaShop version 8.1.x, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by Poulinhoo** [comment]
Hello @paulnoelcholot, 

I don't think this issue is relevant, as there has never been a tooltip for this input. However, it's possible to add one, but I think it isn't necessary. Can you give me the required translation if you want to add one?

Thank you

**Comment by florine2623** [comment]
This issue can be closed.
