### ISSUE TITLE
Integrate proper icons for facebook, twitter and github in the login page

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#36242]

**Comment by Hlavtox** [comment]
@PrestaShop/product-council @jolelievre

Is this even needed? Nobody from the public should be able to see the login page. And the admin already knows about the project, if he chose it for his business.

If we just don't show any social links, less crap to care about I guess? :-)

**Comment by jolelievre** [comment]
It's clearly not a must-have, so far the links are still present with text, if it's a quick win to re-integrate the logos why not do it? The idea was mainly to keep the migrated page closer to the initial one

**Comment by kpodemski** [comment]
@jolelievre 

It's like when you're moving out of your old house and discarding things you no longer need. It does make sense not to keep them if they are useless.

**Comment by jolelievre** [comment]
Yep, I don't mind, it's not up to me to decide this though

**Comment by kpodemski** [comment]
@jolelievre, can we agree to put the Waiting for PM label here?

**Comment by mattgoud** [comment]
@jolelievre, I'll take a look
