### ISSUE TITLE
Reset password -> back button not working.

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#36249]
On login page click on `I forgot my password`
Then click on `Cancel` button, nothing happens

This used to work but the IDs must have changed because of some refacto, updating the selector should be good Basing it on a dedicated class should make it more stable as well https://github.com/PrestaShop/PrestaShop/blob/77e912bfde5011c34ffa64475f7ae78980e9cc8d/admin-dev/themes/new-theme/js/pages/login/login-map.ts#L33

**Comment by mattgoud** [comment]
ok @jolelievre, I'll take a look
