### ISSUE TITLE
Dependabot (module) fails when there is nothing to be done

### ISSUE THREAD

**Issue by WahbiPS** [PrestaShop/PrestaShop#36254]
When dependabot has no module to update in prestashop, it fails on this error:

`cron_php_update_modules.txt: No such file or directory`

seems like this file is created only when there are modules to update, so it fails when trying to read it while there's no module to update

https://github.com/PrestaShop/PrestaShop/actions/runs/6843635964/job/18606450426

**Comment by amine-O** [comment]
Fixed with https://github.com/PrestaShop/PrestaShop/pull/36073
