### ISSUE TITLE
[UI] Create & Update command Size, weight, and group access

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#36258]
**US**

I want to set a max width, height, weight and deph of an order

**Specs**

- Maximum order width (Dimension unit) input behavior
This is input field to enter package width. The dimension unit mentioned in parenthesis is the one defined in International > Localization > Localization.
- Maximum order height (Dimension unit) input
This is input field to enter package height. The dimension unit mentioned in parenthesis is the one defined in International > Localization > Localization.
- Maximum order depth (Dimension unit) input behavior
This is input field to enter package depth. The dimension unit mentioned in parenthesis is the one defined in International > Localization > Localization.
- Maximum order weight (Dimension unit) input behavior
This is input field to enter package weight. The weight dimension unit mentioned in parenthesis is the one defined in International > Localization > Localization.

**Notes**
Package is renamed Order. and the image will not be replaced.

**Design**

https://www.figma.com/design/QlgjdPJHkpTZ8NSgLa4qzr/Carrier-page?node-id=1-1913&t=dxi5Fx4de7sqiuT1-0

**Comment by amine-O** [comment]
Block by #36257
