### ISSUE TITLE
[UI] Create & Update General Setting

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#36257]
**US**

As a merchant, I want to be able edit the general setting of my carrier.

**Specs**

- Carrier name input behavior
This is input (Forms normal UI kit) to enter carrier name. 
- Transit time input behavior
This is input (Forms normal UI kit) to enter transit time. This input has language dropdown to enter information for customers in different languages.
- Speed grade input behavior
This is input (Forms normal UI kit) to enter speed grade.
- Logo input behavior
This is input (Forms files UI kit) to choose file that will be shown as carrier logo. This input has a file icon on the left input side. On the right input side there is CTA button with a catalog icon with title Choose a file. Once clicked on input or button opens modal with this PC files. When file uploaded it is shown in Logo block in each carrier creation step.
- Tracking URL input
This is input (Forms normal UI kit) to enter tracking URL.
- Group and Shop association checkboxes behavior
The user associate the Group and Shop through the modal. The modal lists all the Groups and Shops
The ID and the name of all existing customers' groups are displayed. A checkbox (Forms checkboxes UI kit) is displayed before each group to select or unselect them. 

A global checkbox allows selecting/unselecting all customers' groups in one click. It displays on the form the label 'All'

Once an element is selected and the modal closes, the selected elements are displayed in a tag. A tag can be deleted by pressing the cross next to the tag label.

![Image](https://github.com/PrestaShop/PrestaShop/assets/43613217/29a1a58a-a4a3-4bea-9b6b-51443bc0475a)

By default, the All the shop and All the customer are selected

**Remarks**
- Ideally, the shops should filter the groups and location. If yes then, put the shop association first.

**Design**

https://www.figma.com/design/QlgjdPJHkpTZ8NSgLa4qzr/Carrier-page?node-id=1-1913&t=dxi5Fx4de7sqiuT1-0

**Comment by MatShir** [comment]
Group access & Shops can use the usual component

**Comment by jolelievre** [comment]
Here is an example of group selection https://github.com/PrestaShop/PrestaShop/blob/f8791f87ec80d32ae73a5f65f6340ffa3018c709/src/PrestaShopBundle/Form/Admin/Catalog/Category/AbstractCategoryType.php#L325
It could probably be extracted into a dedicated and reusable `GroupAssociationType`

Similar to the existing form type for shop association https://github.com/PrestaShop/PrestaShop/blob/f8791f87ec80d32ae73a5f65f6340ffa3018c709/src/PrestaShopBundle/Form/Admin/Catalog/Category/AbstractCategoryType.php#L338
