### ISSUE TITLE
Password Reset Link Redirects to Email Request Page Instead of Password Change Page When Clicked

### ISSUE THREAD

**Issue by Delvezio** [PrestaShop/PrestaShop#36265]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When a user clicks on the "Forgot your password?" link. is redirected to a page where the email address linked to the account is requested in order to receive the link to change the password.

However, the link they receive, if clicked, takes you back to the page where you are asked to enter your email, instead of opening the page for changing your password.

If the link displayed in the email is instead copied and pasted, it correctly takes you back to the password change page.

With the inspect tool I saw that the text of the generated link does not correspond to the actual link indicated in the href.
![1](https://github.com/PrestaShop/PrestaShop/assets/20090246/cb204eb9-0e6f-4064-9c11-32154d8c29e4)
![2](https://github.com/PrestaShop/PrestaShop/assets/20090246/787ab712-d40d-4962-82a7-f3fc409b5eac)
![3](https://github.com/PrestaShop/PrestaShop/assets/20090246/2a2e3ead-6129-44b2-9453-39b39bca68b6)
![4](https://github.com/PrestaShop/PrestaShop/assets/20090246/6d83e954-4cdb-4115-b4b9-c23501cd4d02)
![5-a](https://github.com/PrestaShop/PrestaShop/assets/20090246/ac84d02a-e541-4d98-8e54-31332da12569)
![5-b](https://github.com/PrestaShop/PrestaShop/assets/20090246/2eb8dd2f-b60f-433b-90cd-d6383a90bee7)
![6](https://github.com/PrestaShop/PrestaShop/assets/20090246/e0543e0d-2b31-4c7a-be0d-973d0ce3b253)

### Expected behavior

I plan to access the password change page by clicking on the link received

### Steps to reproduce

1. Click "Forgot your password?" on login page
2. Enter your registered email and click the button to receive the password reset link
3. Click on the link you received via email

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

E-mail module and/or Customer "Sign in" module

**Comment by Hlavtox** [comment]
@Delvezio Hi, that is a problem with your SMTP server messing up your links. You can see that the link contains some `sendibt2.com` crap that is definitely not generated by PrestaShop. :-)

I suggest checking the configuration of sendibt2 or contacting their customer support.

**Comment by Delvezio** [comment]
Ok, thank you for u replay!

Il giorno gio 30 mag 2024 alle ore 11:24 Daniel Hlaváček <
***@***.***> ha scritto:

**Comment by AureRita** [comment]
Hi @Delvezio 

Thank you for your report, Currently I tried to reproduce it but I can't as you can see : 

[recording(224).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/13a282c9-a3b7-45be-845c-bac7356aedbe)

Did I miss something ? 

You can follow the advice of Hlavtox, he's a major contributor to Prestashop and has extensive knowledge of the project. 

Tell us if your issue is solved thank to him

Waiting for your feedback
