### ISSUE TITLE
Optimize the carrier update, avoid generating a new instance on each save, handle duplication ONLY when the carrier is already assigned to an order

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#36263]
**US**
Optimize the carrier update, avoid generating a new instance on each save, handle duplication ONLY when the carrier is already assigned to an order

Impact on module ??

**Comment by Hlavtox** [comment]
@MatShir No impact, modules track the carrier objects by `id_reference` which stays the same for the whole lifetime of the carrier. 

If the carrier is assigned a new ID or not, the module basically doesn't care.
