### ISSUE TITLE
Payment module charges you, but the order is not created.

### ISSUE THREAD

**Issue by rodriciru** [PrestaShop/PrestaShop#36277]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If you are in maintenance mode, but you have access to the backoffice, you can place an order (with external validation) and you will be charged, but PrestaShop will not register it.

This is because (at least with Redsys in Spain) the POS itself calls a URL (to validate the cart) `https://bmw-motorrad.burgocar.es/index.php?fc=module&module=redsyspur&controller=validation` that does not execute the `postProcess()` method of the `validation.php` file, which extends `ModuleFrontController`. Redsys takes it for good, they charge you, but PrestaShop has not been able to make its checks, and, therefore, the order does not exist or anything.

The order of execution is like this:
1. The previous URL is called.
2. It ends up getting to Controller.php, method run()
3. That method calls `init()`, but as the `RedsyspurValidationModuleFrontController` class extends `ModuleFrontController` which in turn extends `FrontController`, first the `init()` of `FrontController` is executed, which on line 474 checks that I am in maintenance. As I am, it shows me the maintenance page, the `init()` call of `Controller.php`, is not executed and, therefore, the rest of the `run()` code is not executed either (which is who calls `postProcess()` of `RedsyspurValidationModuleFrontController`).
Therefore, I have not been able to validate the POS result and I do not create the order or anything else, but the money in the bank account has disappeared.

### Steps to reproduce

1. Put in maintenance mode.
2. buy something with a method which does external validation.
3. no validation is executed, so the order is not created.

### PrestaShop version(s) where the bug happened

8.1.6

### PHP version(s) where the bug happened

8.1.23

**Comment by florine2623** [comment]
Hello @rodriciru ,

I can't reproduce your issue with any PS native payment modules. (bank wire, check payment, cod)

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
