### ISSUE TITLE
Unknown error alla linea 114 nel file /home/customer/www........

### ISSUE THREAD

**Issue by Laura-BdG** [PrestaShop/PrestaShop#36273]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Unknown error alla linea 114 nel file /home/customer/www/***********
<img width="524" alt="Screenshot 2024-05-29 alle 22 22 01" src="https://github.com/PrestaShop/PrestaShop/assets/160724004/73ecb116-fcb0-4403-a249-0474f5a5dfd8">
.it/public_html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_modifier.php
[16384] Using php-function "array_merge" as a modifier is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier.

### Steps to reproduce

No particular action
Unfortunately, after installing version 8.1.5, many errors continue to follow one another

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.0.30

**Comment by AureRita** [comment]
Hi @Laura-BdG 

Thank you for your report, Currently we can't try to reproduce your issue on prestashop 8.1.5 because you don't provide enought information. Indeed, when I install version 8.1.5 I didn't have any error message. 

In wich page did you see this error ? 
In FO or BO ? 
What did you currently do to have this error ? 

Waiting for your feedback

**Comment by Laura-BdG** [comment]
Hi @AureRita,

Thank you for your kind reply.The error appeared in the BO immediately after logging in. The installation of version 8.1.5 had not generated errors for me either but it has been a few days that everything seems to be deprecated and many errors continue to follow one another.

For example, now I have agreed that I can no longer view/edit email templates because it goes into error.

**Comment by PrestaEdit** [comment]
There is where is located the issue : https://github.com/PrestaShopCorp/ps_mbo/blob/bc9c71e6fd62d648ed3faede65f308d9c334c883/views/templates/hook/dashboard-zone-one.tpl#L43

**Comment by florine2623** [comment]
Hello @Laura-BdG ,

I can't reproduce your issue on my end.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by PrestaEdit** [comment]
Please. ...

I reproduce this error and even mention where is located the issue.

**Comment by matks** [comment]
If the issue is indeed located in the ps_mbo module, then the right place to report the problem is here https://github.com/PrestaShopCorp/ps_mbo/issues

ps_mbo is outside of the perimeter of this github repository

**Comment by matks** [comment]
I also encounter this issue.

This is the source PR on Smarty side https://github.com/smarty-php/smarty/pull/814

**Comment by lf2s** [comment]
I have the same on a new install with only 2 modules (Creative Elements + Configurateur avancé de produit sur-mesure par étape) and default theme.
