### ISSUE TITLE
Problems with Product Customizations

### ISSUE THREAD

**Issue by Codencode** [PrestaShop/PrestaShop#36286]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When using product customizations with an additional cost, two issues arise. The additional cost for basic customizations in Prestashop cannot be managed directly, but they can be handled through a custom module by utilizing the id_module and price fields in the customized_data table, which Prestashop automatically uses to calculate the product cost.

# Issue 1: (fixed by https://github.com/PrestaShop/PrestaShop/pull/36834)
When purchasing a customized item with an extra charge, the "Total products" column on the order confirmation page is incorrect.
Attached are screenshot **01 - Order create.png** and video **01 - Order create.webm**.

# Issue 2: (fixed by https://github.com/PrestaShop/PrestaShop/pull/36287)
When purchasing the same customized item with two different customizations and two different costs, if I modify the cost of one of the two items in the order, the system updates the cost of both products.
Attached are screenshots **02 - Order edit - 01.png** and **02 - Order edit - 02.png** and video **02 - Order edit.webm**.

Attached is a module that adds 2 customizations to any item added to the cart. Adding the same item twice (with two separate cart additions), the system adds 2 different customizations with 2 different costs.
The module is just an example and with quickly developed code.

**01 - Order create.png**
![01 - Order create](https://github.com/PrestaShop/PrestaShop/assets/2463965/cf4007d1-da5c-4594-a5bb-17e7406dd086)

**01 - Order create.webm**
[01 - Order create.webm](https://github.com/PrestaShop/PrestaShop/assets/2463965/a44ac956-c171-429b-b49e-afdbd7dfd6e1)

**02 - Order edit - 01.png**
![02 - Order edit - 01](https://github.com/PrestaShop/PrestaShop/assets/2463965/bed55618-5d58-4396-9771-8c962759bf97)

**02 - Order edit - 02.png**
![02 - Order edit - 02](https://github.com/PrestaShop/PrestaShop/assets/2463965/065994ab-2d9f-4db7-805f-15f90c3b1091)

**02 - Order edit.webm**
[02 - Order edit.webm](https://github.com/PrestaShop/PrestaShop/assets/2463965/55280fda-5fa3-49d9-8e7e-9f9e008975ef)

**Module**
[cnc_prova_configurazionearticolo.zip](https://github.com/user-attachments/files/15520943/cnc_prova_configurazionearticolo.zip)

### Steps to reproduce

Issue 1:
1. Access the site and add a product to the cart.
2. Add a customization with an additional cost to the product.
3. Proceed to checkout and complete the order.
4. Observe the "Total products" column on the order confirmation page.

Issue 2:
1. Access the site and add the same product to the cart with two different customizations and different costs.
2. Complete the order.
3. Modify the cost of one of the customizations in the order.
4. Observe that the system updates the cost of both customizations.

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

all

### Your company or customer's name goes here (if applicable).

Codencode

**Comment by Codencode** [comment]
I have created a PR for issue 2
PR: https://github.com/PrestaShop/PrestaShop/pull/36287

**Comment by florine2623** [comment]
Hello @Codencode ,

I reproduce both issues with PrestaShop version 8.1.x, I'll add this to the backlog so it can be fixed.

Issue 1 :
<img width="1130" alt="Screenshot 2024-06-11 at 10 17 26" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/6fd43249-c0ea-46d7-bb15-28519f125da1">

Issue 2 :
<img width="817" alt="Screenshot 2024-06-11 at 11 17 11" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/9d427b10-2b56-4f13-b075-c7fea12fe6ce">


Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by florine2623** [comment]
Issue 1 is fixed here : https://github.com/PrestaShop/PrestaShop/pull/36834

Issue 2 is fixed here : https://github.com/PrestaShop/PrestaShop/pull/36287

Thanks @Codencode 💪
