### ISSUE TITLE
Error design/mail_theme/preview

### ISSUE THREAD

**Issue by Laura-BdG** [PrestaShop/PrestaShop#36297]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Good morning, every time I try to go to the preview of the default email templates, the attached error appears.
Unfortunately, I am not knowledgable enough to be able to solve the problem.

![Screenshot 2024-06-03 alle 12 47 19](https://github.com/PrestaShop/PrestaShop/assets/160724004/eeffecef-d7e9-4096-8e2d-8445215b3467)

![Screenshot 2024-06-03 alle 12 08 14](https://github.com/PrestaShop/PrestaShop/assets/160724004/9f150d53-6414-4d76-9a1e-1e105b1d4f9f)

![Screenshot 2024-06-03 alle 12 09 43](https://github.com/PrestaShop/PrestaShop/assets/160724004/ef60c9f6-fb24-43b9-a19b-9b516687f899)

### Steps to reproduce

1) I'm going to design/mail_theme/preview
2) I click on HTTP or in the menu with the 3 dots
3) the error appears

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.0.30

**Comment by florine2623** [comment]
Hello @Laura-BdG ,

I can't reproduce your issue.

https://github.com/PrestaShop/PrestaShop/assets/16019289/e927401f-6aff-4e52-b496-2bc09f9e7372

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
