### ISSUE TITLE
empty abandoned carts with no customers

### ISSUE THREAD

**Issue by SimplyAsh99** [PrestaShop/PrestaShop#36296]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,
I have 552594 empty abandoned carts with no id customers. They are all bots? How can I fix that problem, because It slows down the site a lot.
![image](https://github.com/PrestaShop/PrestaShop/assets/171563439/25725ac7-90dc-4fba-a29f-11b733747e63)
Thanks if someone help me!

### Steps to reproduce

1. Go to Orders
2. Go to Abandoned Carts

### PrestaShop version(s) where the bug happened

1.7.8

**Comment by venditdevs** [comment]
Check your serverlogs and block the bot who's causing this. It would not be very surprising if it is claudebot.

**Comment by SimplyAsh99** [comment]
How i can check for sure? Maybe is semrush?

**Comment by venditdevs** [comment]
In your server(usage)logs and/or usage statistics.

**Comment by Hlavtox** [comment]
I think there is nothing Prestashop project can do with this unfortunately. Clever enough bot will always be able to do this, if it wants to.

Ping @kpodemski

**Comment by florine2623** [comment]
Hello @SimplyAsh99 

You need to block it directly via your server.
You might be using an external module that let's bots create empty/abandoned carts.
