### ISSUE TITLE
Order payment failure

### ISSUE THREAD

**Issue by cgv8** [PrestaShop/PrestaShop#36304]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, First I will leave this information about the versions that I use on my system.

- Prestashop version: 1.7.8.8
- PHP version: 7.4.33

The problem is that when transferring an order from Prestashop to Factusol, sometimes it adds a few cents, other times, as is the situation in the following screenshot, Prestashop adds them only without passing it to Factusol, and the customers pay that amount with the added cents. . By doing the math we can realize the error.
Down below I attach the screenshot of the erroneous order in which 5 cents are added. thank you so much.
![bh jhb](https://github.com/PrestaShop/PrestaShop/assets/171682414/88dc54d3-4faa-401f-aefc-c2af89b0eecb)

### Steps to reproduce

To reproduce the error, first the connector (FesteWeb) migrates the order and it appears, when clicking on it the cost is changed, and in Prestashop to reproduce it we believe that the error occurs on its own and adds the 5 cents but it only happened to us with a only request.

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

no

**Comment by SharakPL** [comment]
180.00 + 37.85 = 217.85 - nothing wrong here 😉

Though I'm guessing you have a tax of 21% so it should be
180.00 + 37.80 = 217.80

It's all about rounding values for each product in the cart and then separately total for the whole cart like [here](https://github.com/PrestaShop/PrestaShop/issues/36308#issue-2333912293). Try changing rounding type on shop's main preferences page.

**Comment by florine2623** [comment]
Hello @cgv8 ,

I can't reproduce your issue using PS without any external module.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
