### ISSUE TITLE
AutoUpgrade - fatal error when configuring v5.0.2

### ISSUE THREAD

**Issue by paulc010** [PrestaShop/PrestaShop#36317]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Can't access the "Configure" screen of the autoupgrade module (after updating to version 5.0.2)

![autoupgrade-error](https://github.com/PrestaShop/PrestaShop/assets/1579146/66432afd-9965-40fe-8c19-d53db48cc6b2)

### Expected behavior

Access to module's main configuration screen

### Steps to reproduce

1. Update module to latest version (5.0.2)
2. Click Configure

### PrestaShop version(s) where the bug happened

8.1.6

### PHP version(s) where the bug happened

8.1.28

### If your bug is related to a module, specify its name and its version

autoupgrade v5.0.2

**Comment by venditdevs** [comment]
More info:

![image](https://github.com/PrestaShop/PrestaShop/assets/14218917/c405c22c-9cfc-4721-973f-22621c14c19a)

![image](https://github.com/PrestaShop/PrestaShop/assets/14218917/145759d8-d898-42cb-be1d-1eea17e8f0a0)

**Comment by venditdevs** [comment]
More info:

![image](https://github.com/PrestaShop/PrestaShop/assets/14218917/fec4eae2-bae8-462b-aa61-0d828680ad5b)

![image](https://github.com/PrestaShop/PrestaShop/assets/14218917/557d351a-ad07-4a52-8654-69824eec94d5)

**Comment by AureRita** [comment]
Hi @paulc010 ,

Thank you for your report, I reproduce the issue with PrestaShop version 8.1.x, as you can see : 

[recording(227).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/465d180e-5954-4ba8-b03c-83e9d26a9eef)

I'll add this to the backlog so it can be fixed.

If you want the last version, as you can see on the video, you can uninstall and delete the files during the uninstall and install again the module to have the last version 

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thanks

**Comment by paulc010** [comment]
@AureRita thank you. It's not a major problem for folks who keep up to date. Until 8.1.7 is released that is!

**Comment by M0rgan01** [comment]
Hello ! We are preparing a 5.0.3 release which resolves the problem.

A quick fix in the meantime is to delete the "AdminSelfUpgrade.php" file at the root of the module which normally should have been deleted during the module upgrade.

**Comment by Quetzacoalt91** [comment]
The version 5.0.3 has been released to fix this issue. You may update the module.
