### ISSUE TITLE
1- Click Update : Error Ajax

### ISSUE THREAD

**Issue by MajinVe** [PrestaShop/PrestaShop#36344]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I try to update my PS 1.7.7.1 to 1.7.8 with 1-Click Update but i have an Ajax Error : 
![2024-06-11 14_16_05-Clipboard](https://github.com/PrestaShop/PrestaShop/assets/72204935/c92fe797-8e20-4c40-b2d1-74cc419d824f)
 my php server is with this setting : 
![2024-06-11 14_17_05-Clipboard](https://github.com/PrestaShop/PrestaShop/assets/72204935/7f73dd2f-3b75-4e61-bf10-6f76b4206e4d)

1-Click Update is on 5.0.2

**How can i fix it ?**

### Steps to reproduce

Click on update, i wait and i have an ajax error

### PrestaShop version(s) where the bug happened

1.7.7.1

### PHP version(s) where the bug happened

7.3

**Comment by paulnoelcholot** [comment]
FYI @AureRita

**Comment by Quetzacoalt91** [comment]
Hi @MajinVe,

Do you have anything reported in your server logs that would help us to understand what the error was?
The module received an empty response but something must be hidden.

**Comment by MajinVe** [comment]
Hi @Quetzacoalt91 , thx for your answer, where can i found a correct log for my problem ?

**Comment by Quetzacoalt91** [comment]
There is one created by the autoupgrade module in `[admin folder]/autoupgrade/tmp/log.txt`.

If there is nothing relevant at the end of the file, you may check on the logs generated by your webserver. However you'll need to check with its documentation how to find them, because each environment can be different.

**Comment by MajinVe** [comment]
I don't have any log because it's down on 504 error 
![image](https://github.com/PrestaShop/PrestaShop/assets/72204935/f1a31877-0988-41ea-9897-558873e832a6)

i have this of settings : 
![image](https://github.com/PrestaShop/PrestaShop/assets/72204935/967c8684-bfb6-4ef7-b542-ea3adcc57965)

it's very long and i don't understand why it's so long ...

**Comment by MajinVe** [comment]
if i have 504 error, it's because the value of max_execution_time is too lower ?

**Comment by MajinVe** [comment]
I have just uncheck backup of img during upgrade and it's successful

**Comment by MajinVe** [comment]
i close it
