### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by Yassine3708** [PrestaShop/PrestaShop#36354]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello
I have an issue in last step on my checkout when I place order
<img width="960" alt="Capture d'écran 2024-06-07 130941" src="https://github.com/PrestaShop/PrestaShop/assets/172133197/5c0d05ad-da6b-44f3-b15b-f7e60e33bf5a">

### Steps to reproduce

link : https://datatechboutique.com/
I get an error page as you can see in attachment
 - version Prestashop /// 8.1.2
 - version PHP //// PHP 8.1
<img width="960" alt="Capture d'écran 2024-06-07 130941" src="https://github.com/PrestaShop/PrestaShop/assets/172133197/c2a5227f-5143-4e18-9fba-8803f58cfce5">

 - steps to have this error
1- select the item to add to cart
2- add to cart
3- proceed to checkout
4- click proceed to checkout
5- fill full of personal informations
6- click continue
7- click continue
8- select shipping method ( cod with tawssil here )
9- select : Pay by Cash on Delivery
10 - select : I agree to the [terms of service](https://datatechboutique.com/en/content/3-conditions-utilisation) and will adhere to them unconditionally.

11- click place order

I get this error page like the attach file
HTTP ERROR 500

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

DATA SOFTWARE

**Comment by venditdevs** [comment]
@Yassine3708  This is probably an issue with the Pay By Cash on Delivery option (i guess that it is a module?).

What are the errors with debug mode enabled? We need that info to determine if it is a bug in Prestashop or not.

**Comment by florine2623** [comment]
Hello @Yassine3708 ,

I can't reproduce your bug. Cash on delivery module v2.0.1 work fine 

https://github.com/PrestaShop/PrestaShop/assets/16019289/084d33ff-e49e-4552-8ad9-d2af6f818985


Can you enable debug mode and try again to place the order?
Go to BO > Advanced parameters > Performances > Enable debug mode > Save

Thank you

**Comment by Yassine3708** [comment]
Hello 

I activated the debug mode 

bello the error message when I place order 

regards 
<img width="960" alt="enable moode debug" src="https://github.com/PrestaShop/PrestaShop/assets/172133197/9cce40a4-48fa-424e-811f-48012dfaf74f">

**Comment by Hlavtox** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/22262

**Comment by Yassine3708** [comment]
it's not a duplicate 

this error shows when you place your order

**Comment by Hlavtox** [comment]
@Yassine3708 Yes, because email gets sent and your server is blocking proc_open function.

You must configure SMTP to send emails or contact your server administrator.
