### ISSUE TITLE
Pagination will go crazy and reload the same page non-stop

### ISSUE THREAD

**Issue by Programacion-Agarimo** [PrestaShop/PrestaShop#36355]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Our client report us a strange behavior con the category pages, when you paginate, if you try to scroll down, you will get back to the top, and the mobile menu will not open.
While we were trying to find the error, we realised on the Network this behaviour. When i paginate to page 2, it will load:
index.php, some js scripts, and this two pages "category/?page=2" and "category/?page=2&from-xhr"
When we go page 3. This category page=3 will load 4 times, and the js scripts will load 2 times.
When we go page 4. This category page=4 will load 8 times, and the js scripts will load 4 times.
For some reason, on each pagination will double the requests, page will be slow and we will have this jumps
![image](https://github.com/PrestaShop/PrestaShop/assets/172577532/91109a79-7f1a-4958-a67a-9bc7097af25d)

We disabled cache, disabled smart cache, disable modules (payment module that was giving us several errors on the console, Google tag manager), we also cleared all the cache on our ftp (public_html/var/cache and the asset/cache from our theme)

### Expected behavior

Smooth scroll on the website without jumps that will not allow the client to have a good experience on the website

### Steps to reproduce

1. Go to this [website](https://www.joyeriamuinos.com/) and go to any category with paginations (We recommend "Joyas Mujer", has a lot)
2. Scroll down and paginate
3. On page 4-5 you will start to experience the jumps
4. If you keep scrolling and paginate more, the experience will be worse

### PrestaShop version(s) where the bug happened

1.7.5.0

### PHP version(s) where the bug happened

7.3.3

**Comment by florine2623** [comment]
Hello @Programacion-Agarimo ,

You need to contact the develop of the theme directly.
I tried with the classic theme of PrestaShop and I cannot reproduce the issue.
<img width="650" alt="Screenshot 2024-06-13 at 10 10 15" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/a85acd4a-cf1a-4e26-9d84-063c2585f005">


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
