### ISSUE TITLE
 The currency API is not updated

### ISSUE THREAD

**Issue by gs2k84** [PrestaShop/PrestaShop#36362]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

I noticed that the currency update in Prestashop stopped working.

from June 11 to 14 I have the same exchange rate in BO.

I checked and it corresponds to archive exchange rates from June 1-4.

According to API, the EUR to PLN exchange rate is 1EUR = 4.280393 PLN
https://api.prestashop.com/xml/currencies.xml

The actual exchange rate is
1EUR = 4.3570PLN

### Steps to reproduce

I noticed that the currency update in Prestashop stopped working.

from June 11 to 14 I have the same exchange rate in BO.

I checked and it corresponds to archive exchange rates from June 1-4.

According to API, the EUR to PLN exchange rate is 1EUR = 4.280393 PLN
https://api.prestashop.com/xml/currencies.xml

The actual exchange rate is
1EUR = 4.3570PLN

### PrestaShop version(s) where the bug happened

8.1.1, 8.1.6

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello @gs2k84 

I have found this rate : `EUR 1 = PLN 4.3473`

On PS we have `<currency iso_code="PLN" rate="4.280393"/>`

Although I have just checked for today and not for a period of time.

**Comment by matks** [comment]
Looks fine today too, I checked a few rates and they seem OK on https://api.prestashop.com/xml/currencies.xml

The currency rate is updated every 24 hours

**Comment by gs2k84** [comment]
> Looks fine today too, I checked a few rates and they seem OK on https://api.prestashop.com/xml/currencies.xml
> 
> The currency rate is updated every 24 hours

In fact, it's already working well today.

**Comment by matks** [comment]
So I close the issue 😉 as it seems there's no problem right now

**Comment by matks** [comment]
@florine2623 The rate is updated every 24 hours so if the rate evolves during the day, it's expected the API info and the real rate are not the same 😉

**Comment by gs2k84** [comment]
> @florine2623Stawka jest aktualizowana co 24 godziny, więc jeśli stawka zmienia się w ciągu dnia, należy się spodziewać, że informacje API i rzeczywista stawka nie będą takie same 😉

Yes, that's why it can now be considered to be working well.

Previously, the rates did not change for several days. That's why the problem was reported.

The EUR to PLN rate was the same for several days

EUR > PLN" = 4.280393

and in fact the rate in other systems and on banks' websites was different.

So, from the beginning of June until you wrote, the bank rate was changing, and the Presta API was still showing the rate

EUR > PLN" = 4.280393

It wasn't about one update in one day.

Regards
gs2k
