### ISSUE TITLE
Contact form email already registered

### ISSUE THREAD

**Issue by mycca85** [PrestaShop/PrestaShop#36371]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When a customer already registered buy with a Guest account (log out), the second time he tried to order:
- If his email belong to a corporate domain (ex. segureco@segureco.com) he can't register twice, so he can't continue the checking out process.
- But if his email is from gmail or hotmail he can order withoyt any problem even if his email is already registered.
![Screenshot 2024-06-17 at 09-53-14 Segureco Seguridad Industrial S L](https://github.com/PrestaShop/PrestaShop/assets/126907053/c0a8d8ae-324c-4120-9887-ea7764feb2e5)

### Expected behavior

All the emails should be registered twice when we buy using any email with a Guest account.
It worked perfectly obn the previous PrestaShop version we had.

### Steps to reproduce

1. Go to https://segureco.com/
2. Clic on the first product you find.
3. Add it to the cart (red button)
4. Click on SOLICITAR PRESUPUESTO (the second red button)
5.  Click again on SOLICITAR PRESUPUESTO (red button on the rigth)
6. Fill all the fields.
7. Repeat steps 1-6. 

### PrestaShop version(s) where the bug happened

 1.7.8.8

### PHP version(s) where the bug happened

7.4.33

**Comment by Hlavtox** [comment]
This doesn't have to do anything with an email domain. :-)

In the past, Prestashop did not allow ordering as a guest once a registered customer was created on that shop.

I fixed that here - https://github.com/PrestaShop/PrestaShop/pull/25353, it will be available in the next 9.0.0 version that is coming.

If you want it now, apply the changes from this PR - https://github.com/PrestaShop/PrestaShop/pull/25353/files

**Comment by kpodemski** [comment]
I think we can close this issue, everything has been explained by @Hlavtox .
