### ISSUE TITLE
Logo Transplant a module button

### ISSUE THREAD

**Issue by paulnoelcholot** [PrestaShop/PrestaShop#36390]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The "transplant a module" button logo is not present on the "Position" page

![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/f96baf50-6c04-4910-a4ba-4a4d9d569574)

![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/13fea3da-5464-4afb-8484-e1123c915d67)

### Expected behavior

He should be present

### Steps to reproduce

1. go to Design > Position
2. See
3. Click to the button Transplant a module, or on pencil button of a hook.
4. See

### PrestaShop version(s) where the bug happened

8.1.x

**Comment by Hlavtox** [comment]
@paulnoelcholot Fixed on develop branch
