### ISSUE TITLE
develop - On category page, meta keywords helptext is duplicated

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#36401]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

<img width="804" alt="Screenshot 2024-06-21 at 10 42 09" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/414695e3-306b-4a1e-88fc-0658f7acd196">

### Expected behavior

Help text should not be doubled.

### Steps to reproduce

1. Go to BO > Categories > Edit any category
2. See Meta keywords help text `Invalid characters: <>;=#{}` is duplicated :x:

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

**Comment by paulnoelcholot** [comment]
Hello @florine2623,

I reproduce the issue with PrestaShop version develop, I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
