### ISSUE TITLE
Amount issue in Bankwire confirmation

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/PrestaShop#36409]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you set the group to show the prices as tax excluded, once your order with bankwire confirmation, you get the tax included price du to this use :         $totalToPaid = $params['order']->getOrdersTotalPaid() - $params['order']->getTotalPaid();

### Expected behavior

Having the right amount in the bankwire details.

### Steps to reproduce

1. Set the group to show excluded prices
2. Order with bankwire method
3. See the details of amount in the payments infos.

### PrestaShop version(s) where the bug happened

n/d

### PHP version(s) where the bug happened

n/d

### If your bug is related to a module, specify its name and its version

ps_bankwire

**Comment by kpodemski** [comment]
I think it's normal. The amount you must pay should include tax anyway, whether it's 0% or some other amount.

**Comment by paulnoelcholot** [comment]
FYI @PrestaShop/product-council

**Comment by kpodemski** [comment]
I couldn't find anything wrong.

Steps:

1. Shopping cart: https://capture.dropbox.com/qiglWGUZnyQ0zAjk
2. Bank wire confirmation: https://capture.dropbox.com/2ntxhTprcfJ9He5R

I am closing this issue, if you are sure @PrestaEdit that there is a bug somewhere, please do let me know more details.

**Comment by PrestaEdit** [comment]
It's seems there is something not followed there : Set the group to show excluded prices

You need to put your customer into a group that doesn't show the price with taxes.

**Comment by kpodemski** [comment]
@PrestaEdit I did, visible on the first screenshot.
