### ISSUE TITLE
Products - back office

### ISSUE THREAD

**Issue by Jaantox79** [PrestaShop/PrestaShop#36418]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Why do I have PrestaShop 8.1.6 old looking product addition. It was newer looking in the beginning, later it changed to the old style. How?

<img width="1408" alt="Näyttökuva 2024-06-25 kello 8 23 39" src="https://github.com/PrestaShop/PrestaShop/assets/173729239/982eefc4-1fd5-46ea-830a-b998dac8120f">

### Steps to reproduce

Why do I have PrestaShop 8.1.6 old looking product addition. It was newer looking in the beginning, later it changed to the old style. How?

<img width="1408" alt="Näyttökuva 2024-06-25 kello 8 23 39" src="https://github.com/PrestaShop/PrestaShop/assets/173729239/982eefc4-1fd5-46ea-830a-b998dac8120f">

### PrestaShop version(s) where the bug happened

8.1.6

### PHP version(s) where the bug happened

8.1.23

**Comment by Hlavtox** [comment]
@Jaantox79 You need to enable `new product page` in` new & experimental features` section.

**Comment by Jaantox79** [comment]
How?

**Comment by Hlavtox** [comment]
@Jaantox79 
- In the left menu, click on new & experimental features
- See new product page
- Click Enabled
- Click Save

**Comment by Jaantox79** [comment]
Found! Thanks a lot!
