### ISSUE TITLE
Deprecated in classes/controller/AdminController.php on line 987 and 988

### ISSUE THREAD

**Issue by tm8544** [PrestaShop/PrestaShop#36410]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Since `$action` in line 986 can have value `null`, PrestaShop 8.1.7 outputs following to error log
PHP Deprecated:  ucfirst(): Passing null to parameter #1 ($string) of type string is deprecated in \kauppa\classes\controller\AdminController.php on line 987
PHP Deprecated:  ucfirst(): Passing null to parameter #1 ($string) of type string is deprecated in \kauppa\classes\controller\AdminController.php on line 988

I changed line 986 
from: `if (!empty($action) && method_exists($this, 'ajaxProcess' . Tools::toCamelCase($action))) {`
to: `if (isset($action) && method_exists($this, 'ajaxProcess' . Tools::toCamelCase($action))) {`

### Steps to reproduce

Go to store admin

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.1.29

**Comment by paulnoelcholot** [comment]
Hello @tm8544,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by alkorotkovas** [comment]
Try this fix @tm8544 

if (isset($action) && $action !== null && method_exists($this, 'ajaxProcess' . Tools::toCamelCase($action))) {
    $this->{'ajaxProcess' . Tools::toCamelCase($action)}();
}

**Comment by tm8544** [comment]
I tried it, and it works as well as without `&& $action !== null `.
I think testing with isset() is enough, because isset() tests also for null values

**In PHP Manual:**
isset
(PHP 4, PHP 5, PHP 7, PHP 8)
isset — Determine if a variable is declared and is different than `null`
