### ISSUE TITLE
Deprecated in classes/controller/Tab.php line 389

### ISSUE THREAD

**Issue by tm8544** [PrestaShop/PrestaShop#36412]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Since `$className` in line 389 can have value `null`, PrestaShop 8.1.7 outputs the following to error log:
PHP Deprecated:  strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in \kauppa\classes\Tab.php on line 389

Change line 389
from: `return strtolower($className);`
to: `return (isset($className) ? strtolower($className) : null);`

### Steps to reproduce

Go to Shop admin

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.1.29

**Comment by paulnoelcholot** [comment]
Hello,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by tm8544** [comment]
This happens only before you login to admin page, that is when login screen is displayed.
Whatever calls `getClassName()` in Tab.php sets parameter `$className` to null at that point.

**Comment by tm8544** [comment]
I created the following test case:
1) I set PrestaShop to debug mode and then I added to line 389 in Tab.php `if (!is_string($className)) throw new Exception();`
2) I opened admin login screen and got the error message attached below
3) I think this leads to `AdminLoginControllerCore->initContent()` line 141 `$this->context->smarty->assign('redirect', $this->context->link->getAdminLink($tab->class_name));`, where `$tab->class_name` is NULL on login screen.
4) Solution? Tab.php line 36: `public $class_name;` changed to `public $class_name = 'DEFAULT'`; 

```
Exception
in [D:\HTTPS-SERVER-D-VHOSTS\kauppa\classes\Tab.php ](https://kauppa.ht23.dy.fi/admin_ht_23/index.php/_profiler/open?_token=4OVncau5JG2jVgBb4GCda7sb-mJCkQFiccHH1F2cNAA?file=classes\Tab.php&line=389#line389)(line 389)
        if (in_array($className, $legacyClassNames)) {            @trigger_error($className . ' is a deprecated tab since version 1.7.0 and "Default" will be removed in 1.7.1.. Upgrade module using the docs: http://build.prestashop.com/news/how-we-reorganized-main-menu-prestashop-1.7/.', E_USER_DEPRECATED);            $className = 'DEFAULT';        }        if (!is_string($className)) throw new Exception();        return strtolower($className);    }    /**     * Get collection from module name.
TabCore::getClassName()
in [D:\HTTPS-SERVER-D-VHOSTS\kauppa\classes\Tab.php ](https://kauppa.ht23.dy.fi/admin_ht_23/index.php/_profiler/open?_token=4OVncau5JG2jVgBb4GCda7sb-mJCkQFiccHH1F2cNAA?file=classes\Tab.php&line=355#line355)(line 355)
TabCore::getIdFromClassName()
in [D:\HTTPS-SERVER-D-VHOSTS\kauppa\classes\Tools.php ](https://kauppa.ht23.dy.fi/admin_ht_23/index.php/_profiler/open?_token=4OVncau5JG2jVgBb4GCda7sb-mJCkQFiccHH1F2cNAA?file=classes\Tools.php&line=1307#line1307)(line 1307)
ToolsCore::getAdminTokenLite()
in [D:\HTTPS-SERVER-D-VHOSTS\kauppa\classes\Link.php ](https://kauppa.ht23.dy.fi/admin_ht_23/index.php/_profiler/open?_token=4OVncau5JG2jVgBb4GCda7sb-mJCkQFiccHH1F2cNAA?file=classes\Link.php&line=739#line739)(line 739)
LinkCore->getAdminLink()
in [D:\HTTPS-SERVER-D-VHOSTS\kauppa\controllers\admin\AdminLoginController.php ](https://kauppa.ht23.dy.fi/admin_ht_23/index.php/_profiler/open?_token=4OVncau5JG2jVgBb4GCda7sb-mJCkQFiccHH1F2cNAA?file=controllers\admin\AdminLoginController.php&line=141#line141)(line 141)
AdminLoginControllerCore->initContent()
in [D:\HTTPS-SERVER-D-VHOSTS\kauppa\classes\controller\Controller.php ](https://kauppa.ht23.dy.fi/admin_ht_23/index.php/_profiler/open?_token=4OVncau5JG2jVgBb4GCda7sb-mJCkQFiccHH1F2cNAA?file=classes\controller\Controller.php&line=319#line319)(line 319)
ControllerCore->run()
in [D:\HTTPS-SERVER-D-VHOSTS\kauppa\classes\Dispatcher.php ](https://kauppa.ht23.dy.fi/admin_ht_23/index.php/_profiler/open?_token=4OVncau5JG2jVgBb4GCda7sb-mJCkQFiccHH1F2cNAA?file=classes\Dispatcher.php&line=510#line510)(line 510)
DispatcherCore->dispatch()
in [D:\HTTPS-SERVER-D-VHOSTS\kauppa\admin_ht_23\index.php ](https://kauppa.ht23.dy.fi/admin_ht_23/index.php/_profiler/open?_token=4OVncau5JG2jVgBb4GCda7sb-mJCkQFiccHH1F2cNAA?file=admin_ht_23\index.php&line=95#line95)(line 95)
```

**Comment by matks** [comment]
https://github.com/PrestaShop/PrestaShop/issues/36411#issuecomment-2200967862
