### ISSUE TITLE
Can't manage stock in new product page

### ISSUE THREAD

**Issue by jlores** [PrestaShop/PrestaShop#36415]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I try to update stock in new product page, the save button is disabled
![bug](https://github.com/PrestaShop/PrestaShop/assets/48771938/7f8eed26-278e-42b1-9819-56bfae5572e8)

### Expected behavior

Click in save button and exit

### Steps to reproduce

Modify stock in new product page, and try to save.

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

7.4.33 8.1.28

**Comment by paulnoelcholot** [comment]
Hello @jlores,

I try to reproduce your issue but as you can see, I can't : 

![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/bd20ced2-9137-4fc5-8c39-ab806e0fd8c5)

Did I miss something?

Thanks

**Comment by darekwaw** [comment]
I have the same problem on after update from 8.1.6 to 8.1.7
![Uploading 2024-06-27_17h23_52.png…]()

**Comment by jlores** [comment]
I closed the bug because I cannot provide information on why it fails.

In a new installation it may not fail, but in production it fails.

Not critical, you can return to the v1 product page

**Comment by jlores** [comment]
I have tried in Chrome and it works, with Mozilla it does not work.
