### ISSUE TITLE
Deprecated in classes/controller/Dispatcher.php line 973

### ISSUE THREAD

**Issue by tm8544** [PrestaShop/PrestaShop#36411]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Since `$route_id` in line 973 can have value `null`, PrestaShop 8.1.7 outputs the following to error log:
PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in \kauppa\classes\Dispatcher.php on line 973

Change line 950
from: `$route_id,`
to: `$route_id = '',`

### Steps to reproduce

Go to shop admin

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.1.29

**Comment by paulnoelcholot** [comment]
Hello,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by matks** [comment]
Hi @tm8544 thank you but a deprecation notice is not a bug 😉 

And
```
Change line 950
from: $route_id,
to: $route_id = '',
```

Is not a valid code change

If you are interested in improving this project, you need to do more 😉 clone the repository, fetch the code locally, submit the changes AND verify they break nothing.

I close this issue as this is not a bug report.
