### ISSUE TITLE
Deprecated in classes/controller/Dispatcher.php line 973

### ISSUE THREAD

**Issue by tm8544** [PrestaShop/PrestaShop#36413]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Since `$route_id` in line 973 can have value `null`, PrestaShop 8.1.7 outputs the following to error log:
PHP Deprecated: trim(): Passing null to parameter https://github.com/PrestaShop/PrestaShop/pull/1 ($string) of type string is deprecated in \kauppa\classes\Dispatcher.php on line 973

### Steps to reproduce

Go to shop admin 

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.1.29

**Comment by paulnoelcholot** [comment]
Hello,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by tm8544** [comment]
This happens only before you login to admin page, that is when login screen is displayed.
Whatever calls `createUrl()` in Dispatcher.php sets parameter `$route_id` to null at that point.

**Comment by matks** [comment]
Closed for similar reasons as https://github.com/PrestaShop/PrestaShop/issues/36411#issuecomment-2200967862
