### ISSUE TITLE
I can not edit products 

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#36427]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello
I get this error message when i try to edit any product from BO 

```
Type error: Argument 1 passed to PrestaShopBundle\Model\Product\AdminModelAdapter::__construct() must be an instance of PrestaShop\PrestaShop\Adapter\LegacyContext, instance of Product given, called in /home/xxxxxxx/xxxxxxxxxx.com/src/PrestaShopBundle/Controller/Admin/ProductController.php on line 1279

[Symfony\Component\Debug\Exception\FatalThrowableError 0]
```
I did not override any file or module

<html>
<body>

CRITICAL12:09:10 | php | Type error: Argument 1 passed to PrestaShopBundle\Model\Product\AdminModelAdapter::__construct() must be an instance of PrestaShop\PrestaShop\Adapter\LegacyContext, instance of Product given, called in /home/xxxxxxxxxxxxx/lllllll/src/PrestaShopBundle/Controller/Admin/ProductController.php on line 1279
-- | -- | --
CRITICAL12:09:10 | request | Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to PrestaShopBundle\Model\Product\AdminModelAdapter::__construct() must be an instance of PrestaShop\PrestaShop\Adapter\LegacyContext, instance of Product given, called in /home/llllllll/lllllll/src/PrestaShopBundle/Controller/Admin/ProductController.php on line 1279" at /home/llllllllll/llllll.l/src/PrestaShopBundle/Model/Product/AdminModelAdapter.php line 192

</body>
</html>
Regards

### Expected behavior

editing products

### Steps to reproduce

GO to Catalogue -->[Produits] edit any product

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

7.4.33

**Comment by kpodemski** [comment]
Hello @go-sudo 

It seems you need help from some developer. Two things you have to understand are:
1. Version 1.7.8.11 is no longer supported by regular bug fixes, so we don't check for new issues against this version.
2. Editing the product is something we test all over the place. It is impossible for this error to come from a clean installation.

I'm closing this issue.
