### ISSUE TITLE
Exception thrown when opening customer thread from notification center

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#36420]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I created a order manually from the BO and I click on the notification center opening the customer message, I have an exception.

`Call to a member function formatPrice() on null`

<img width="1074" alt="Screenshot 2024-06-25 at 11 15 17" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/f3b374c9-5baa-43d5-ae42-b9fb6f53b6c0">

Can't be reproduced in 8.1.x

### Expected behavior

No exception, the customer thread should be displayed

### Steps to reproduce

1. Go to BO > Order > Add new order > Choose John DOE > Add any product > Add to cart
2. Choose Payment method > Choose Order Status > Click Create order
3. Go to FO > Log into John DOE account > Go to Order History
4. Open Details of latest order created > Add a message > Send
5. Go to BO > Refresh > Click on notification center > Tab message > Open
6. See exception

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

**Comment by paulnoelcholot** [comment]
![image](https://github.com/PrestaShop/PrestaShop/assets/112863083/50edae36-303d-43c7-ad46-ea197fae27b2)
