### ISSUE TITLE
It's possible to create two customers with the same email address while transforming from guest

### ISSUE THREAD

**Issue by kociokwik** [PrestaShop/PrestaShop#36421]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

OrderConfirmationController and GuestTrackingController can transform guest into customer, but both don't check if provided email already exists during POST request, allowing for two customers to have same email address which leads to one account being unable to log in

### Expected behavior

OrderConfirmationController and GuestTrackingController need to check if customer with the same mail address exists during POST request. Adding first 'if' resolves the problem:

```php
//added in 'postProcess()'
if ($this->customer->is_guest == 1 && Customer::customerExists($this->customer->email)) {
    $this->errors[] = $this->trans(
        'An account was already registered with this email address',
        [],
        'Shop.Notifications.Error'
    );
} elseif ($this->customer->is_guest == 0) {
    $this->errors[] = $this->trans(
        'A customer account has already been created from this guest account. Please sign in.',
        [],
        'Shop.Notifications.Error'
    );
// Attempt to convert the customer
} elseif ($this->customer->transformToCustomer($this->context->language->id, $password)) {
    $this->success[] = $this->trans(
        'Your guest account has been successfully transformed into a customer account. You can now log in as a registered shopper.',
        [],
        'Shop.Notifications.Success'
    );
}
```

@Hlavtox I believe same thing happens in develop branch
[Original discussion](https://github.com/PrestaShop/PrestaShop/pull/25353#issuecomment-2186840234)

### Steps to reproduce

1. Create an order as a guest with email "abc@abc.com" and stay on the OrderConfirmation page
  > order_id: 1, customer_id: 1
2. In the second window make another guest order with the same email address and open GuestTracking for the that (second) order
  > order_id: 2, customer_id: 2
3. In window with GuestTracking, transform guest into customer with password "aaa"
4. In window with OrderConfirmation, transform guest into customer with password "zzz"
5. Only customer with id=1 can log into account, another is basically blocked

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment]
I see the issue, I created PR here - https://github.com/PrestaShop/PrestaShop/pull/36454

**Comment by florine2623** [comment]
Hello @kociokwik ,

I have reproduced your issue.
I'm encountering this message :
<img width="1139" alt="Screenshot 2024-07-01 at 16 53 11" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/c4c3ad9e-51d4-4d83-b3fe-604508551dc0">

Although I'm wondering if that's not the expected behavior to be able to log into your guest-to-customer account with only one password ? @PrestaShop/product-council

**Comment by Hlavtox** [comment]
@florine2623 Try to reproduce with my steps. There can be only one customer account and infinite amount of guest accounts  with the same email.

Once there is one customer account with given email, no other guest with this email can be transformed into a customer.
This is checked during displaying the conversion form, but not after it, during submitting the form.

### How to reproduce - guest tracking
- Create order as a guest. Let's say this is order and customer A.
- Create another order as a guest with the same email. Let's say this is order and customer B.
- Go to order tracking of order B. Check that you see the guest transformation box. Keep it open.
- In BO, transform the guest A a customer.
- Now, go back to order tracking of order B and transform the customer. It won't work with my PR, it will work without by PR.

### How to reproduce - order confirmation page
- Create order as a guest. Let's say this is order and customer C.
- Create another order as a guest with the same email. Let's say this is order and customer D. Keep the order confirmation open.
- In BO, transform the guest C a customer.
- Now, go back to confirmation of order D and transform the customer. It won't work with my PR, it will work without by PR.
