### ISSUE TITLE
Facet Search - Product lose ordering

### ISSUE THREAD

**Issue by supportA3WEB** [PrestaShop/PrestaShop#36429]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi, 

I have a problem that seems to have been resolved. 
After searching, I came across exits that were all closed and dated 2019/2020.

I have this problem on sub-category. 

### Steps to reproduce

Go to products
Filter by category
Click on "reorder"
Try to reorder but without using the icon in column position, just click on the line and move it
Click on saved and refresh

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

ps_searchfacet : 3.15.1

**Comment by paulnoelcholot** [comment]
Hello @supportA3WEB,

This problem has already been resolved, we invite you to migrate your shop to 8.1.6

Thanks
