### ISSUE TITLE
Cannot install Prestashop 8.1.7

### ISSUE THREAD

**Issue by musaffarpatel** [PrestaShop/PrestaShop#36436]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Fails with the following error:
PrestaShop accounts (ps_accounts) module is not installed, please install it.

### Steps to reproduce

1. Download Prestashop 8.1.7 from the official Prestashop site 
2. Run the installer

Fails with the following:
![screenshot](https://github.com/PrestaShop/PrestaShop/assets/5041037/e1060462-3411-428c-8ddd-5d486a10b052)

### PrestaShop version(s) where the bug happened

8.1.7

**Comment by kpodemski** [comment]
Hello @musaffarpatel 

Please provide more information since I remember you are a Windows user. Did you use Windows or a proper server to install your PrestaShop?

This place is not dedicated to supporting the installation of PrestaShop 8.1.7 Classic Edition, but if you provide more information, I can inform the Classic Edition team about your issue.

**Comment by matks** [comment]
I just installed PS 8.1.7 downloaded from prestashop.com and it works for me so at least on MacOSX it works 😄

**Comment by kpodemski** [comment]
Same for me, tested on MacOS and PHP 7.4.

**Comment by musaffarpatel** [comment]
My installation failed on Windows 11, php 8.1.8.  Although Prestashop 8.1.6 installs fine on the same setup

**Comment by kpodemski** [comment]
It's probably something specific to Windows. I'm sorry, but Windows is not an environment for PrestaShop to be run on in production. As I recommended multiple times, you have WSL, you have Docker, plenty of options.
