### ISSUE TITLE
Autoupgrade module does not suggest latest minor version available since PS 8

### ISSUE THREAD

**Issue by Quetzacoalt91** [PrestaShop/PrestaShop#36430]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Since PS 8, the major version is stored in number (in opoosition of PS 1.7 and below where the major version was in the format `X.Y`).
The upgrade module has not been modified to take this format in account when selecting the proper version to upgrade to.

As a workaround, the [channel.xml file](https://api.prestashop.com/xml/channel.xml) is providing information for minor branches.

At the moment this does not cause any issue, but it will the day we have PS 9 released. Merchants would be only able to choose between the last patch of their current minor, or the very last version of PrestaShop release. Updating to the last minor version would not be possible anymore.

Considering PrestaShop v9 is in stable and I'm running a shop on PS 8.0.0.

* Selecting the channel `minor` provides an upgrade from PS 8.0.0 to PS 8.0.5. (:warning: )
* Selecting the channel `major` provides an upgrade from PS 8.0.0 to PS 9.0.0.

 
![Capture d’écran du 2024-06-26 09-28-07](https://github.com/PrestaShop/PrestaShop/assets/6768917/da0e562b-a42f-4992-8916-eea1de80f0ac)

### Expected behavior

Considering PrestaShop v9 is in stable and I'm running a shop on PS 8.0.0.

* Selecting the channel `minor` should provide an upgrade from PS 8.0.0 to PS 8.1.7.
* Selecting the channel `major` should provide an upgrade from PS 8.0.0 to PS 9.0.0.

### Steps to reproduce

1. Start a shop on PS 8.0.x
2. Open the upgrade module and select the channel `minor`
3. The upgrade to 8.0.5 is shown, while 8.1.7 is expected

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

autoupgrade v5

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

**Comment by Quetzacoalt91** [comment]
Note: An additional pull request on the API repository has been opened to fix the version suggested.

**Comment by AureRita** [comment]
Hi @Quetzacoalt91 

as you corrected it from the API repository, as we can see here : 
![image](https://github.com/PrestaShop/PrestaShop/assets/100699445/6b7a2089-4f93-464e-82ba-7c7c28b892b1)

I'll close this issue,

Thank you for your correction
