### ISSUE TITLE
hummingbird - Product page : can't change the quantity via input, the quantity 1 is always displayed

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#36456]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I can't use the backspace key to erase the quantity.

https://github.com/PrestaShop/PrestaShop/assets/16019289/d93c625e-cd75-47c9-b42f-92bf06d083a6

Thanks @tblivet for the details :
Bug seems to have been introduced by : https://github.com/PrestaShop/PrestaShop/commit/4965d7ac4ae6b100c21411b2b29f8485d51c2b51
Line 1207 : `$product['cart_quantity'] = $this->context->cart->getProductQuantity($product['id_product'], $product['id_product_attribute'])['quantity'];`

['id_product'] should be replaced by ['id']  

FYI @boherm , maybe you can help on that topic ^^

Detected by TE @nesrineabdmouleh 

### Expected behavior

I should be able to use the backspace key to erase 1 and add any quantity I want.

### Steps to reproduce

1. Install hummingbird
2. Go to FO > Open any product page
3. Edit quantity via input > Try to use backspace to erase quantity 1 :x:

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

hummingbird v0.2.0

**Comment by boherm** [comment]
Oh ok! I will check that today 😉

**Comment by boherm** [comment]
@florine2623, @tblivet, after some tests on my side, isn't related to the core but only hummingbird implementation. (classic theme seems to work)

As we have an issue about `$product['cart_quantity']` in `front/ProductController`, this issue isn't related. (btw, I will fix that in a PR in the core today!).

This issue (`I should be able to use the backspace key to erase 1 and add any quantity I want.`) is related to the function `detectQuantityChange` in HB file `src/js/product.ts` and maybe this implementation are to strict. 🤔
