### ISSUE TITLE
Hardcoded Language ID in getAttributesName Call Leads to Incorrect Attribute Names

### ISSUE THREAD

**Issue by mouleeg** [PrestaShop/PrestaShop#36458]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Description of the Bug:

In the `AdminProductWrapper.php` file, while fetching the specific prices list for a product,  the method `getAttributesName` is called with a hardcoded parameter 1 for the language ID. 

https://github.com/PrestaShop/PrestaShop/blob/8.1.x/src/Adapter/Product/AdminProductWrapper.php#L481

This implementation assumes that language id 1 is always appropriate for fetching attribute names, which is not always the case. In scenarios where the application is being used in a multilingual context, or when the user's preferred language is different from the default language, this approach leads to incorrect attribute names being fetched and displayed. This can cause confusion for the users and potentially lead to incorrect data handling or display issues in the application. The bug essentially limits the application's flexibility and usability in multilingual environments.

### Expected behavior

When i change the language of the page, the name of the attribute should be displayed in the good language.

### Steps to reproduce

1. Go to Product (with declianison) page in BO
2. Click Price tab
3. In the specific price list, The name will not be displayed well if the default language was different one. because it always fetches the name with id lang 1.

### PrestaShop version(s) where the bug happened

8.1.x

**Comment by florine2623** [comment]
Hello @mouleeg ,

I can't reproduce your issue following your steps.

My shop default's language is in English. My BO is in English.
My combinations have different names if EN and in FR.
I opened any product with combinations > Add a specific price to a combination > It is displayed in English ✅ 
I change my shop's default language to French.
I go back to my product page in BO, in the Pricing Tab, the name of the combinations are well displayed in French ✅ 

Am I missing something ?
Waiting for your feedback.

**Comment by Hlavtox** [comment]
@florine2623 Can you check what your language IDs are?

Let's say that:
- English is ID 1
- French is ID 2

Let's say that the combinations have different names - `My combinations have different names if EN and in FR.` ✅ 

Now, when you change your employee's profile to ID 2 (french), then the combinations in specific price settings should be still in english.

Also, make sure to test on OLD product page.

**Comment by florine2623** [comment]
Thanks for the details !
I was testing on New product page and had no issue. The issue is raised only on Old product page.

https://github.com/PrestaShop/PrestaShop/assets/16019289/8cbc0dda-b4f2-4330-9c2b-068ecff2944f

I have seen the PR and will take a look at it !
