### ISSUE TITLE
PS9 - Error rendering "LoginHeadTag" component

### ISSUE THREAD

**Issue by aminvatandoust** [PrestaShop/PrestaShop#36459]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,

I built the PrestaShop 9 Alpha 1 zip file and installed it on the server with PHP 8.1. After the installation (which had no warning/error during the process), as I wanted to access the BO, I got this error (the login form didn't show up):

`Error rendering "LoginHeadTag" component: Template "@AdminNewTheme/public/preload.html.twig" is not defined in @PrestaShop/Admin/Component/LoginLayout/head_tag.html.twig at line 34.`

![Screenshot from 2024-06-28 23-06-39](https://github.com/PrestaShop/PrestaShop/assets/42088167/59f1c9a9-e71f-443f-ad3f-190158e312e7)
![Screenshot from 2024-06-28 23-23-03](https://github.com/PrestaShop/PrestaShop/assets/42088167/390ebf45-0a89-4c12-96b1-1f776d4e4093)

The FO is working fine, and there is no error. It's just the Admin panel that I can't access.
I got no error running the CreateRelease script, and the package was successfully created.

I tried clearing the var/cache folder, but that didn't help.
Did I miss something?

### Expected behavior

Show the back office login form

### Steps to reproduce

1. Build the PrestaShop 9 Alpha 1 Zip
2. Install it on a Server with PHP 8.1
3. After the Installation is over, go to BO login form

### PrestaShop version(s) where the bug happened

9.0.0

**Comment by florine2623** [comment]
Hello @aminvatandoust ,

I couldn't reproduce the exact same issue you had.

I had a 500 error, once I put debug mode ON, I had access to my BO.

<img width="659" alt="Screenshot 2024-07-01 at 11 54 32" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/abc1dc48-87ad-41ad-abe6-aa7b0341bab7">

**Comment by kpodemski** [comment]
Hello @aminvatandoust 

You probably used a Node version other than the recommended version 16, which caused an error with preload.html not being available. Try to create a package using Node v16.

**Comment by matks** [comment]
Hello @aminvatandoust to be sure I just built PS 9.0.0 alpha 1, and also the latest version of 9.0.0 on the `develop` branch. On both builds I do not reproduce the issue you have so I think like you might have not built it right, as mentioned by @kpodemski 

I close this ticket as "Cannot reproduce"

**Comment by mirivhbv** [comment]
Hi, I'm also getting the same error. Additionally, the main page's assets seem to be broken. 
Launched through docker-compose in VPS.
~~http://57.153.202.123/admin-dev~~

Note: The exact clone works fine on my machine. VPS OS is Ubuntu 22.04.

**Comment by jolelievre** [comment]
The `preload.html.twig` file is generated when the assets are built, so it's likely that you either did not build the assets or that the build failed

To build the assets locally you can use the `make assets` command in the PrestaShop root folder

**Comment by DoctorDred** [comment]
I have the same issue. Installed on Open Server Panel, make assets command is not working. Please any solutions....

In console:

> Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.
> Generating autoload files
> 139 packages you are using are looking for funding.
> Use the `composer fund` command to find out more!
> phpstan/extension-installer: Extensions installed
> > phpstan/phpstan-doctrine: installed
> > spaze/phpstan-disallowed-calls: installed

**Comment by jf-viguier** [comment]
No problem with node 16 (same error with node 18)

**Comment by kpodemski** [comment]
Hello @jf-viguier 

Could you try with Node 20? At the moment, v20 is the only supported version.

**Comment by jf-viguier** [comment]
Node 20 failed, tons of warning in npm run build and this in BO 
![image](https://github.com/user-attachments/assets/d650cf9a-5a2c-4702-97e3-c5dec926c406)

**Comment by kpodemski** [comment]
@jf-viguier this looks like an issue with composer packages not being correctly installed

what did you try to do? install `develop` on your local machine or install Alpha 1?

**Comment by jf-viguier** [comment]
@kpodemski install develop

**Comment by jf-viguier** [comment]
@kpodemski yes, it's ok now with a composer install, my vendor was too old

**Comment by JavierEB** [comment]
![Image](https://github.com/user-attachments/assets/8a5402fb-5a86-4d6f-8731-96cef9ae08ad)
Same problem, I can't access the backoffice

**Comment by kpodemski** [comment]
@JavierEB 

In the same solution, assets have to be compiled using Node 20 and NPM 10. Otherwise, there are issues with generating them and the preload.html.twig file 👍🏻
