### ISSUE TITLE
Importing product images from csv raises error.

### ISSUE THREAD

**Issue by sergey-belous** [PrestaShop/PrestaShop#36461]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I'm trying to import products from csv. All products are imported right, but with no images. I have no idea why is happen so. Maybe something wrong with the images path, and i'm not found a rule,
![2024-06-30_11-01-45](https://github.com/PrestaShop/PrestaShop/assets/163721200/43f80665-1a68-40bc-b9b6-8267a1a80fa3)
 how to specify it.

### Expected behavior

I've expected images specified in csv file shoud be imported and shown in products.

### Steps to reproduce

Admin -> Products -> Import

### PrestaShop version(s) where the bug happened

9

### PHP version(s) where the bug happened

8

**Comment by paulnoelcholot** [comment]
Hello @sergey-belous,

Can you give us the .csv you are using? 

Thanks!

**Comment by kpodemski** [comment]
@sergey-belous The screenshot you sent shows that URLs to images are malformed. They point to your WSL environment.

**Comment by sergey-belous** [comment]
Hi there!
There is mine .csv file
[products_import (2).csv](https://github.com/user-attachments/files/16080659/products_import.2.csv)
Only images, that are downloaded from web are importing.
@kpodemski Yes, i've tried all the variants i had, including full path with wsl (and relative path for server index file, and path with "localhost:8001"), but there still no result.
And thanx in advance.

**Comment by florine2623** [comment]
Hello @sergey-belous ,

Thanks for the csv file !

I tested importing product with your file. The first product with the image online works. But the other products with image in localhost do not work as I don't have them in my files.

<img width="1181" alt="Screenshot 2024-07-09 at 11 31 28" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/bfc7c6b0-e89d-4785-ac87-3225133cd8af">

Do you have access to your images via your website ? Maybe it's a rights permission issue.

**Comment by paulnoelcholot** [comment]
Hello @sergey-belous,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
