### ISSUE TITLE
Problem with Rebuild price index cron 

### ISSUE THREAD

**Issue by robProWeb** [PrestaShop/PrestaShop#36478]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The Rebuild price index cron stops at the first 100 products (.../module/ps_facetedsearch/cron?ajax=1&action=indexPrices&full=1&token=f6333...).

Instead, by launching the "Rebuild price index" from the interface, clicking on the button, the indexing is completed correctly, processing 100 products at a time.

By analyzing the code of the ps_facetedsearch.php file I found where perhaps the problem is at row 1581:

while (
            $cursor < $nbProducts
            && ....

By doing a print_r of the variables turns out: 

$cursor = 9756 
$nbProducts = 1721

But $cursor is returned by the indexPricesUnbreakable() function at row 1652 same file:

$lastIdProduct = $product['id_product'];  

So here's the problem, a "<" check is made between a product_id and a total number of products. 
So in my case it turns out to be false even if there are other products to process.

Thanks for your help!

![image](https://github.com/PrestaShop/PrestaShop/assets/82451318/8bdb3cef-f3ab-46c4-89f7-e4574a0531b1)

![image](https://github.com/PrestaShop/PrestaShop/assets/82451318/a4bb1de7-88ac-4bd7-9f78-2a428b5e778b)

![image](https://github.com/PrestaShop/PrestaShop/assets/82451318/1792e40c-8c72-42d4-bcc1-daea0c1ef528)

### Expected behavior

The cron should index all products and not stop at the first 100

### Steps to reproduce

1. Run Rebuild price index cron on browser

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

ps_facetedsearch v 3.16.1

**Comment by florine2623** [comment]
Hello @robProWeb ,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by florine2623** [comment]
I can't reproduce this issue on 9.0.X.

https://github.com/user-attachments/assets/73a904f2-e8c5-46a3-99a7-630e23389aec


So I will close it to avoid clogging the backlog.

Thanks.
