### ISSUE TITLE
sharebuttons - Replace Twitter logo by X

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/PrestaShop#36470]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Twitter is dead since almost 1 year replaced by X.
It would be nice to remove/rename/replace any trace of Twitter like in ps_sharebuttons module:
![twitter](https://github.com/PrestaShop/PrestaShop/assets/7419525/4122af5f-47b3-42a6-a365-8ce019cf5aa5)

Another issue is opened for _socialfollow_ : https://github.com/PrestaShop/PrestaShop/issues/35108
Mine is for _sharebuttons_.

### Expected behavior

Have a X logo in place of Twitter

A fast patch can be to replace "compiled" logos in Classic theme (or sub-theme) by attached files (designed from [official X branding resources](https://about.x.com/fr/who-we-are/brand-toolkit)) 

The 2 files to replace are in `themes/classic/assets/css/` folder:
https://lowly-box.demo.prestashop.com/themes/classic/assets/css/0ba57b3ea460c3d7d0c4.svg
https://lowly-box.demo.prestashop.com/themes/classic/assets/css/740f1557cae714dc4b18.svg

Overwrite them by following files:
![0ba57b3ea460c3d7d0c4](https://github.com/PrestaShop/PrestaShop/assets/7419525/ba1e6a7c-1b06-4cb3-90fa-0c31b5d21ffc)
![740f1557cae714dc4b18](https://github.com/PrestaShop/PrestaShop/assets/7419525/6adcb91e-8a79-4e1f-94e6-a6d723bf7c20)

And you will have a nice X logo in place of Twitter:

![X](https://github.com/PrestaShop/PrestaShop/assets/7419525/c2a92d13-cf76-4241-9561-0f1f9ac1f0eb)

### Steps to reproduce

Go to ps_sharebuttons configuration :
- Enable "Twitter" social network
- See Twitter logo on product page

### PrestaShop version(s) where the bug happened

1.7 to 9.x

### PHP version(s) where the bug happened

5.6 to 8.3

### If your bug is related to a module, specify its name and its version

ps_sharebuttons 2.1.2

**Comment by Retroallstars** [comment]
is there a new version release to correct this? Why is this issue "closed" "completed" ?
Prestashop v8.2.1 and module Social media share buttons v.2.1.2 doesnt have the good X icon. I use the classic theme v2.2.0
