### ISSUE TITLE
Email notification

### ISSUE THREAD

**Issue by Jaantox79** [PrestaShop/PrestaShop#36482]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Incoming orders will not be notified by e-mail.

### Steps to reproduce

New orders will not receive notifications

### PrestaShop version(s) where the bug happened

8.1.6

### PHP version(s) where the bug happened

8.0

**Comment by kpodemski** [comment]
Hello @Jaantox79 

You can use the `ps_emailalerts` module to receive notifications about new orders.
