### ISSUE TITLE
Missing currency context for new Admin API

### ISSUE THREAD

**Issue by clement-hvt** [PrestaShop/PrestaShop#36483]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Unable to use currency context with new API with API Platform
![image](https://github.com/PrestaShop/PrestaShop/assets/83085039/ccd7c748-e36b-4635-b484-98a7d217f418)

### Steps to reproduce

Create a new API ressource who need the currency context in its CQRSQuery, e.g.: GetOrderForViewing and call it.

### PrestaShop version(s) where the bug happened

9.0.0 alpha 1

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello @clement-hvt ,

Could you explicit the Steps to reproduce please ?

Waiting for your feedback.
Thanks!

**Comment by clement-hvt** [comment]
Hello @florine2623,

First, you need to add in a new APIPlatorm resources in a module (like [ps_apiresource](https://github.com/PrestaShop/ps_apiresources)) in the directory  `src/ApiPlatform/Resources`. Here is an example of a resource API:
```php
<?php

namespace PrestaShop\Module\APIResources\ApiPlatform\Resources\Order;
use ApiPlatform\Metadata\ApiProperty;
use ApiPlatform\Metadata\ApiResource;
use PrestaShop\PrestaShop\Core\Domain\Order\Query\GetOrderForViewing;
use PrestaShopBundle\ApiPlatform\Metadata\CQRSGet;

#[ApiResource(
    operations: [
        new CQRSGet(
            uriTemplate: '/order/{orderId}',
            CQRSQuery: GetOrderForViewing::class,
            scopes: [
                'order_read',
            ],
            CQRSQueryMapping: Order::QUERY_MAPPING,
        ),
    ]
)]
class Order
{
    public const QUERY_MAPPING = [
        '[_context][shopConstraint]' => '[shopConstraint]',
        '[_context][langId]' => '[displayLanguageId]',
        '[id]' => '[orderId]'
    ];
    #[ApiProperty(identifier: true)]
    public int $orderId;
}
```
Then, you can follow [this tutorial](https://build.prestashop-project.org/news/2024/meet-prestashop9-api/) to get your JWT and access the new API resource at `/admin-api/order/{orderId}`

I hope I was more explicit !

Thanks.

**Comment by florine2623** [comment]
Hello,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!
