### ISSUE TITLE
Cannot translate phrase inside the module using legacy translation method

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#36486]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I created a simple module to test another issue and it helped me discover another issue with translations and PrestaShop 9. If I have the main module file and translation, when I go to translate the module, it shows me a critical error. If I have the main module file and translatable phrase inside, it shows me a critical error when I try to translate the module.

Screenshot: https://capture.dropbox.com/1vYVFkI8GFX5I6Tt

### Expected behavior

I should be able to translate my module.

### Steps to reproduce

Install the attached test module, go to the configuration page, and then try translating it.

[kpissue36486.zip](https://github.com/user-attachments/files/16078929/kpissue36486.zip)

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello @kpodemski ,

I have reproduced your issue in V9, I'll add this to the backlog so it can be fixed : 

<img width="1059" alt="Screenshot 2024-07-03 at 10 10 00" src="https://github.com/PrestaShop/PrestaShop/assets/16019289/6a1717c2-fa07-4cb6-a42e-d659e16b7aa4">


Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by kpodemski** [comment]
Issue does not exist anymore.
