### ISSUE TITLE
error out of memory when doing sales and order statistics in presashop

### ISSUE THREAD

**Issue by quimSTM** [PrestaShop/PrestaShop#36491]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I want to see sales and order statistics for 1 year, an Out of memory error appears. It is an error that the web browser shows, I know, but it happens with Chrome, Edge, Firefox... and it happens with different versions of PrestaShop like ps 1.7.8 or ps 8.1.1, and it happens with various versions of php from 7.4 to 8.1. It also happens on websites installed on different hostings, I know this because I work in a company with various clients who use PrestaShop and who have different versions of PrestaShop, PHP and different hostings.
To reproduce the problem go to the Statistics menu > Sales and orders > 1 year 
It also happens with 3 months, 6 months...
![screen_error](https://github.com/PrestaShop/PrestaShop/assets/174600204/f458a7e7-36e3-499f-aa62-87b6189e80b8)

### Expected behavior

See the statistics for the period of 1 year, or the period you want without errors

### Steps to reproduce

1 - Go to Stats > Stats
2.- Go to Sales and Orders
3.- Click button "Year-1" and wait ...
4.- the browser shows an Out of memory error

### PrestaShop version(s) where the bug happened

ps 1.7.8 & ps 8.1.1

### PHP version(s) where the bug happened

php 7.4.33 & php 8

### Your company or customer's name goes here (if applicable).

Software Textil Maresme

**Comment by florine2623** [comment]
Hello @quimSTM ,

I can't reproduce your issue as you can see here :

https://github.com/PrestaShop/PrestaShop/assets/16019289/5c30e6a4-a0be-44e4-a1cd-37ce67f3af1c

Please check the system requirements for PS 1.7 here : https://devdocs.prestashop-project.org/1.7/basics/installation/system-requirements/

And PS 8 here : https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by quimSTM** [comment]
Please don't close the case so quickly!
That's because you're doing it without data. You must have data from 6 months or 1 year of operation of the web store.
Please test what I have said again using data from at least 1 year of operation, with your clients, products, sales...

**Comment by quimSTM** [comment]
Hello @florine2623,

I have tested it on various PrestaShop websites, with different versions of PrestaShop (from 1.7.8 to 8.1), with different PHP (from version 7.4 to 8.1), with different hostings, and all of them met the PrestaShop requirements. 
I opened this thread on Github after going to Prestashop support, they directed me here. I have consulted about the community forums and I haven't found anything about this case. If there is a solution I will be grateful to follow it.

Please test the problem I have found using a similar scenario, I mean, with data from at least 1 year of operation.

thanks for your time

> Hello @quimSTM ,
> 
> I can't reproduce your issue as you can see here :
> 
>  Screen.Recording.2024-07-03.at.15.31.17.mov 
> Please check the system requirements for PS 1.7 here : https://devdocs.prestashop-project.org/1.7/basics/installation/system-requirements/
> 
> And PS 8 here : https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/
> 
> We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).
> 
> Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).
> 
> Thank you



> [Get help with PrestaShop](https://www.prestashop-project.org/support/).
