### ISSUE TITLE
Problem uploading a image to a product The file "/tmp/phpTsWVhe" does not exist

### ISSUE THREAD

**Issue by FactoryBike** [PrestaShop/PrestaShop#36495]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, since yesterday, when i try to ad an image to a product it give us a error. If i activate DEBUG mode it shows to logs: 

I need help to solve that

### Steps to reproduce

In product edit i try to upload an image and give to me an error

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4.33

**Comment by florine2623** [comment]
Hello @FactoryBike ,

**Please change your Admin folder name for security reason. This is a public space.**

Another user had the same issue, please check their solution : https://www.prestashop.com/forums/topic/1082230-solved-upload-images-an-error-occurred-the-file-tmpphpkzxmd0-does-not-exist/

I can't reproduce your issue.
We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by simobenso** [comment]
Hello, I do actually have the very same issue on a production store with the same php version (7.4) and prestashop (1.7.8.9) : 


```
CRITICAL10:18:58 | php | Uncaught Exception: The file "/tmp/phpUmVOmD "does not exist
-- | -- | --
CRITICAL10:18:58 | request | Uncaught PHP Exception Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException: "The file "/tmp/phpUmVOmD "does not exist "at /home/*******/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/File/File.php line 37
```

I have tried : 
- Disabling overrides
- Disable all modules

Still having the same issue, even if : 
- The /tmp folder is writable
- upload_max_size is 200Mo

Please help !

**Comment by simobenso** [comment]
<img width="941" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/1257993/50632ae3-6db1-4266-b58f-2e99234baeb0">

<img width="1064" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/1257993/64c720cc-439e-439b-b448-d5c83801bf05">

**Comment by simobenso** [comment]
<img width="933" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/1257993/8aa4bfda-1c75-4f2c-bd3d-293b925e5e53">

<img width="839" alt="image" src="https://github.com/PrestaShop/PrestaShop/assets/1257993/f9752b73-33b5-43fa-8d5e-47b1a27c7a44">

**Comment by simobenso** [comment]
@florine2623 can you please take a look at this ?

**Comment by simobenso** [comment]
It seems to be caused by the last version of ps_eventbus. Image upload worked right after disabling the module.

**Comment by mtorromeo** [comment]
> It seems to be caused by the last version of ps_eventbus. Image upload worked right after disabling the module.

Same issue here, and also the same workaround seems to be working as well.

**Comment by kpodemski** [comment]
The event bus team is aware of the issue and they are investigating it

**Comment by mtorromeo** [comment]
Good to know, the fact that the issue is marked as Closed made it seem like this was not recognized as an active issue

**Comment by kpodemski** [comment]
@mtorromeo it is not related to PrestaShop core, it's been transferred to the team working on event bus module

**Comment by mtorromeo** [comment]
Right, sorry. Found the issue here https://github.com/PrestaShopCorp/ps_eventbus/issues/330

**Comment by FactoryBike** [comment]
I deactivated and reinitialized the module PrestaShop EventBus v3.0.13 and everything is back to normal.

**Comment by fox-john** [comment]
Hello ! 

We have release a new version of PsEventbus (3.0.14) can you try this release and check if your issue persist ?

**Comment by FactoryBike** [comment]
I solve it by deactivating and resetting the module. I´ve just update the module an my web crash......ahhhhggggg

**Comment by FactoryBike** [comment]
I had to rename the folder ps_eventbus and my web works again....¿Is that module important for the funcionality of my web?...Please solve it @fox-john

**Comment by FactoryBike** [comment]
Please, i need help @fox-john 

> I had to rename the folder ps_eventbus and my web works again....¿Is that module important for the funcionality of my web?...Please solve it @fox-john

**Comment by FactoryBike** [comment]
This is the error: Type error: Argument 1 passed to PrestaShop\Module\PsEventbus\Service\SynchronizationService::__construct() must be an instance of PrestaShop\Module\PsEventbus\Repository\EventbusSyncRepository, instance of Ps_eventbus given

[Symfony\Component\Debug\Exception\FatalThrowableError 0]

**Comment by FactoryBike** [comment]
I had to rename the folder to ps_eventbus_old and download the module from here https://github.com/PrestaShopCorp/ps_eventbus/releases/tag/v3.0.14 and upload to my prestashop and now works again.
"Thank´s ti @fox-john for your invaluable help to solve this problem"
