### ISSUE TITLE
After Google Analytics Uploaded, errors appeared

### ISSUE THREAD

**Issue by OZI-IZZO** [PrestaShop/PrestaShop#36494]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I HAVE UPLOADED THE FREE MODULE GOOGLE ANALYTICS IN MY PRESTASHOP
see below context
Versions du PHP 7.3
SQL 5.7 
Version Prestashop 1.7.8.5

A list of errors appeared and can't get anymore till the basket see attached
<img width="1439" alt="FREE MODULES LIST UPLOADED" src="https://github.com/PrestaShop/PrestaShop/assets/173680071/0fbdc9e7-ef63-4f70-8617-7c5fb1a59526">
<img width="675" alt="Capture d’écran 2024-06-20 à 16 58 02" src="https://github.com/PrestaShop/PrestaShop/assets/173680071/a565d941-1423-4fc2-a5e7-de6beb8135a6">
<img width="675" alt="Capture d’écran 2024-06-20 à 16 58 14" src="https://github.com/PrestaShop/PrestaShop/assets/173680071/df7c00d6-31a7-4f1f-b2b7-1384f1aefcf2">

### Expected behavior

Could you please solve the issue that i can make my website active again and solve the issues from my uploading

### Steps to reproduce

1. GO TO MY PRESTASHOP / MODULE/ MODULE MANAGER: uploading google analytics the first module on the top of the list see the attachment "free module list uploaded"
<img width="1439" alt="FREE MODULES LIST UPLOADED" src="https://github.com/PrestaShop/PrestaShop/assets/173680071/566d22fd-2e48-47f9-8cf6-a2e199b7eb7d">
2. SEE IN SCREEN SHOT ERRORS THE ERRORS WHICH APPEARS 5mn later
<img width="675" alt="errors 1" src="https://github.com/PrestaShop/PrestaShop/assets/173680071/869aa4b8-3e5a-4f51-9d52-0213898853d1">
<img width="675" alt="errors 2" src="https://github.com/PrestaShop/PrestaShop/assets/173680071/d6a65b84-8d0b-4f2c-b7af-d97e717c4bfb">

### PrestaShop version(s) where the bug happened

1.7.5.2

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

GOOGLE ANALYTICS v5.00

### Your company or customer's name goes here (if applicable).

IZZO

**Comment by florine2623** [comment]
Hello @OZI-IZZO ,

Please upload the latest version of google analytics : https://github.com/PrestaShop/ps_googleanalytics/releases -> v5.0.2.

On my side with v5.0.2, I can't reproduce your issue.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by OZI-IZZO** [comment]
How can i solve py issue regarding the impact on the basket. My customers can't order anymore!and pr'estashop ask me to contact github!Who can support me?

Très cordialement,
M. OZREN BABICDirecteur Généralmobile: +33 6 68 52 52 59 
1 rue Magnier Bédu95410 GroslayFranceOffice: +33 7 68 62 02 08



 

    Le jeudi 4 juillet 2024 à 08:57:31 UTC+2, florine2623 ***@***.***> a écrit :  
 
 


Hello @OZI-IZZO ,

Please upload the latest version of google analytics : https://github.com/PrestaShop/ps_googleanalytics/releases -> v5.0.2.

On my side with v5.0.2, I can't reproduce your issue.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: Get help with PrestaShop.

Alternatively, you can also ask for help in the community forums or in the public Slack channel.

Thank you

**Comment by matks** [comment]
Hello I did a quicksearch with the keyword "gaCrossDomain" I hope it helps https://github.com/search?q=org%3APrestaShop+gaCrossDomainEnabled&type=pullrequests

@OZI-IZZO To quickly fix your shop, remove the GA Analytics module.

For more support https://www.prestashop-project.org/support/

**Comment by OZI-IZZO** [comment]
many thanks!!!
Très cordialement,
M. OZREN BABICDirecteur Généralmobile: +33 6 68 52 52 59 
1 rue Magnier Bédu95410 GroslayFranceOffice: +33 7 68 62 02 08



 

    Le jeudi 4 juillet 2024 à 09:10:28 UTC+2, Mathieu Ferment ***@***.***> a écrit :  
 
 


Hello I did a quicksearch with the keyword "gaCrossDomain" I hope it helps https://github.com/search?q=org%3APrestaShop+gaCrossDomainEnabled&type=pullrequests

@OZI-IZZO To quickly fix your shop, remove the GA Analytics module.

For more support https://www.prestashop-project.org/support/
