### ISSUE TITLE
Autoupgrade : ps_linklist a Fatal error in FO when upgrade from 1.7.7.0 ~ 1.7.7.8 to 8.1.7 with php 7.2-7.3 

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#36498]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After an upgrade 1.7.7.0 to 8.1.7 the ps_linklist throw a fatal error in the FO

![Capture d’écran de 2024-07-04 10-38-44](https://github.com/PrestaShop/PrestaShop/assets/24647495/0732b7f7-fa5b-4149-b841-78f8445abd70)

### Expected behavior

NO error

### Steps to reproduce

1- Install 1.7.7.0 on php 7.2 (For example)
2- Upgrade to 8.1.7
3- Go to FO
See the error

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

autoupgrade

**Comment by Hlavtox** [comment]
Code inside `upgrade-5.0.0.php` did not run.

```
function upgrade_module_5_0_0()
{
    $result = true;
    $result &= Db::getInstance()->execute('ALTER TABLE `' . _DB_PREFIX_ . 'link_block_shop`  ADD COLUMN `position` int(10) unsigned NOT NULL DEFAULT 0');
    // Delete blockcms data that are not used in previous version of this module
    $result &= Db::getInstance()->execute('DELETE FROM `' . _DB_PREFIX_ . 'link_block_shop`');

    foreach (Shop::getShops(true, null, true) as $shopId) {
        $result &= Db::getInstance()->execute(
            'INSERT INTO `' . _DB_PREFIX_ . 'link_block_shop` (`id_link_block`, `position`, `id_shop`)
            SELECT `id_link_block`, `position`, ' . $shopId . ' FROM `' . _DB_PREFIX_ . 'link_block`
            '
        );
    }

    return (bool) $result;
}
```

**Comment by Quetzacoalt91** [comment]
With the incoming PR https://github.com/PrestaShop/autoupgrade/pull/850, the migration is now applied properly and the FO is working as expected.
