### ISSUE TITLE
Cannot Update Price in postman

### ISSUE THREAD

**Issue by walrusix** [PrestaShop/PrestaShop#36503]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello
as you can see in this screenshot i cant update product price via prestashop web service (using Patch method)
![Screenshot 2024-07-07 184126](https://github.com/PrestaShop/PrestaShop/assets/89637122/ac173e30-6133-4ae0-8fab-301c26a407fe)

PrestaVersion: 8

### Steps to reproduce

how can i update price by prestashop web service via postman?

### PrestaShop version(s) where the bug happened

8

**Comment by florine2623** [comment]
Hello @walrusix ,

Please refer to : https://github.com/PrestaShop/PrestaShop/issues/13950#issuecomment-495553117

It works as expected.

Thanks!

**Comment by walrusix** [comment]
> Hello @walrusix ,
> 
> Please refer to : [#13950 (comment)](https://github.com/PrestaShop/PrestaShop/issues/13950#issuecomment-495553117)
> 
> It works as expected.
> 
> Thanks!

Hello @florine2623 
I Tested this one
but it cant change price.

![Screenshot 2024-07-07 184126](https://github.com/PrestaShop/PrestaShop/assets/89637122/e9f9715e-9a80-4d7a-9a7a-345c9e0bada4)
