### ISSUE TITLE
Autoupgrade 1click Upgrade error 500 - Prestashop 8.1.3

### ISSUE THREAD

**Issue by Delvezio** [PrestaShop/PrestaShop#36500]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Good morning,
I can't update prestashop to the latest version with the "1-click upgrade" module. When I click it I am taken to a "500 Server Error" error page.

On the information page in "Advanced parameters -> Information" I have this alert message:

_List of changed files
Missing/changed files were detected.

Missing File (1)
adminXXXyyXyyy/**autoupgrade/index.php**_

![Screenshot 2024-07-04 alle 10 02 32](https://github.com/PrestaShop/PrestaShop/assets/20090246/bc8837be-3efd-41a6-a736-0be0a07f0e40)

![Screenshot 2024-07-03 alle 12 36 57](https://github.com/PrestaShop/PrestaShop/assets/20090246/a13657bc-edcb-4d58-943a-a9c1e9d8da9d)

![Screenshot 2024-07-03 alle 12 34 06](https://github.com/PrestaShop/PrestaShop/assets/20090246/c5448ae1-6439-4f66-b719-93ce8f9f5b9a)

### Expected behavior

by clicking the "1-Click Upgrade" button, prestashop will update to the latest version.

### Steps to reproduce

1. Put the store into maintenance mode
2. Click **1-click Upgrade**
3. 500 fatal Error

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

8.2.15 

### If your bug is related to a module, specify its name and its version

1-Click Upgrade / autoupgrade v5.0.3

**Comment by Hlavtox** [comment]
Hi @Delvezio, the message about missing file is non relevant.

Please enable debug mode in Performance settings and visit the module page again. What error does it throw?

**Comment by Delvezio** [comment]
Hi @Hlavtox,

this message appears:

![Screenshot 2024-07-04 alle 16 54 33](https://github.com/PrestaShop/PrestaShop/assets/20090246/5feb7f40-92bc-468e-9453-8d64d265838d)

**Comment by Hlavtox** [comment]
Server configuration problem, you can start searching: https://www.google.com/search?q=2006+mysql+server+has+gone+away :-)))

**Comment by Misty-94** [comment]
Hi,

PHP 8.2 is not supported, maximum 8.1 : https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/
