### ISSUE TITLE
TaxRulesGroup getIdByName deleted values

### ISSUE THREAD

**Issue by sandra2n** [PrestaShop/PrestaShop#36519]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,

When using the function TaxRulesGroup::getIdByName($name), it sometime return a deleted one (if it exists) as it return the first one found and if a deleted one as the same name than a not deleted one, there is good chance that it will be the one returned.

### Expected behavior

Allowing to get not deleted tax rules group ID when using that function (maybe adding a variable to choose if we want not deleted value only) or adding an other function to get not deleted tax rules group ID.

### Steps to reproduce

1. Delete a tax rules group
2. Create a new tax rules group with same name as the one deleted
3. Use the function TaxRulesGroup::getIdByName($name) with that name and see which ID you get

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello @sandra2n ,

Could you provide a module example so we can test out step 3 of your issue ?

Thanks!

**Comment by sandra2n** [comment]
Hello @florine2623 ,

There is no module example, sorry. We are using it in a CRON that import data. 
If it is just to see it, you can just do a 
dump(TaxRulesGroup::getIdByName($name)); 
die(); 
anywhere you want to display it, really. What matters is that the $name is the name of the taxe rules group you deleted.

To fix the issue, maybe something like that ?:

`public static function getIdByName($name, $enabled = false)
    {
        return (int) Db::getInstance()->getValue(
            'SELECT `id_tax_rules_group`
			FROM `' . _DB_PREFIX_ . 'tax_rules_group` rg
			WHERE `name` = \'' . pSQL($name) . '\''.($enabled ? ' AND `deleted` = 0' : '')
        );
    }`

Thank you

**Comment by Hlavtox** [comment]
This is already resolved on develop branch, it returns the active, non-deleted first.

```php
public static function getIdByName($name)
    {
        return (int) Db::getInstance()->getValue(
            'SELECT `id_tax_rules_group`
			FROM `' . _DB_PREFIX_ . 'tax_rules_group` rg
			WHERE `name` = \'' . pSQL($name) . '\'
            ORDER BY `active` DESC, `deleted` ASC'
        );
    }
```

**Comment by sandra2n** [comment]
That's great, thank you!
