### ISSUE TITLE
PrestaShop 8.1.7, les add-ons tournent en boucles, clic ugrade la dernière case de la liste et coché en rouge

### ISSUE THREAD

**Issue by DannyC52** [PrestaShop/PrestaShop#36515]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Lorsque je désire télécharger les modules, ceux-ci tournent en boucle sans jamais s'installer.
Dans le clic upgrade, la dernière case de la liste est coché en rouge depuis la mise à jour de PrestaShop 8.1.7.
Les module en upgrade affiche une boite d'erreur rouge.

### Expected behavior

J'ai dû actualiser la page pour arrêter la boucle.
J'ai tout essayé, rien ni fait. Comme je ne connais rien en programmation, pouvez-vous regarder s'il vous plait

### Steps to reproduce

![Capture d'écran 2024-07-08 113157](https://github.com/PrestaShop/PrestaShop/assets/175013160/508c73c4-9fc3-421e-a99d-a25a48c5446d)
![Capture d'écran 2024-07-08 112611](https://github.com/PrestaShop/PrestaShop/assets/175013160/e9b7ff55-0695-4eb9-a2c0-b83d03e1c0e8)

### PrestaShop version(s) where the bug happened

8.1.7.

### PHP version(s) where the bug happened

8.0

### If your bug is related to a module, specify its name and its version

tous les modues

### Your company or customer's name goes here (if applicable).

Miel Abeilles

**Comment by florine2623** [comment]
FYI @AureRita ^^

**Comment by paulnoelcholot** [comment]
Hello @DannyC52,

Please send your request in English. English is the norm on GitHub.

Thank you
