### ISSUE TITLE
Cannot Change Price In Postman

### ISSUE THREAD

**Issue by walrusix** [PrestaShop/PrestaShop#36513]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

![Screenshot 2024-07-07 184126](https://github.com/PrestaShop/PrestaShop/assets/89637122/5ef2b0c4-dd00-42de-b847-52c3f45e485c)

Hello 
Im using Postman to change price by Patch Method
my old issue closed! and i cant reopen that
https://github.com/PrestaShop/PrestaShop/issues/36503
i did changes as @florine2623  said in that old issue but still not working

### Steps to reproduce

Cant Update Price (web service)

### PrestaShop version(s) where the bug happened

8

**Comment by florine2623** [comment]
Hello again @walrusix ,

I have no issue changing the price using the patch method on Postman :

https://github.com/PrestaShop/PrestaShop/assets/16019289/50e8615d-b828-45dc-914c-7936751211e0

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
