### ISSUE TITLE
error out of memory when doing sales and order statistics in prestashop (again)

### ISSUE THREAD

**Issue by quimSTM** [PrestaShop/PrestaShop#36511]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I want to see sales and order statistics for 1 year, an Out of memory error appears. It is an error that the web browser shows, I know, but it happens with Chrome, Edge, Firefox... and it happens with different versions of PrestaShop like ps 1.7.8 or ps 8.1.1, and it happens with various versions of php from 7.1 to 8.1. It also happens on websites installed **on different hostings**, I know this because I work in a company with various clients who use PrestaShop and **who have different versions of PrestaShop, PHP and different hostings.**
To reproduce the problem go to the Statistics menu > Sales and orders > 1 year
It also happens with 3 months, 6 months...
![hot_to_get_stats_error](https://github.com/PrestaShop/PrestaShop/assets/174600204/aefc3930-d97f-4a56-a8e4-b3acc15e9a9a)

### Expected behavior

See the statistics for the period of 1 year, or the period you want without errors

### Steps to reproduce

1 - Go to Stats > Stats
2.- Go to Sales and Orders
3.- Click button "Year-1" and wait ...
4.- the browser shows an Out of memory error

### PrestaShop version(s) where the bug happened

from ps 1.7.8 to ps 8.1.1

### Your company or customer's name goes here (if applicable).

Software Textil Maresme

**Comment by quimSTM** [comment]
Please test the problem with a website with statistical sales data, preferably from 1 year, because without statistical data or with little data, the error does not occur.

**Comment by florine2623** [comment]
Hello @quimSTM ,

As I said on your other issue https://github.com/PrestaShop/PrestaShop/issues/36491, I cannot reproduce the problem on my side.
You must have an issue on your server.

For that I suggest contacting the support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

**Comment by quimSTM** [comment]
Hello @florine2623 ;

The error is not on the server. There is no error on the server because, as I said in the message, the error occurs on various tested websites that are hosted on different hostings. It happens with different versions of PrestaShop and with different versions of PHP. The error occurs when you have a large volume of sales data, above 700 orders in a year.

Please, if you test the problem, use the conditions I describe. If you use a website, without data you will not reproduce the error.

Please do not close the case again without testing it with the conditions that I detail.

thanks for your time
