### ISSUE TITLE
ps_wirepayment.php order confirm 500error!

### ISSUE THREAD

**Issue by Bakis89** [PrestaShop/PrestaShop#36518]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi guys, i have problem with ps wirepayment module! 

When its activated i cant open cart (500error) and cant make order (500error)

When disabling wirepayment, every thing works, but people can make order because there is no payment method!

Here is error! 

Any solutions?

PHP8.1

Module 2.2.0

Presta shop version 8.1.7
![Error](https://github.com/PrestaShop/PrestaShop/assets/175059676/960e0d4e-a818-41ec-8883-770b216b78f7)

### Steps to reproduce

Open tavagaisma.lv/en
Choose product:
Add to cart: 
Push on checkout

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_wirepayment 2.2.0

**Comment by florine2623** [comment]
Hello @Bakis89 ,

I tested on your shop, I can't access the cart. It seems like you have more issues than just the wirepayment throwing an error.

As I can't reproduce that error on a fresh install shop, I suggest contacting the support.

https://github.com/PrestaShop/PrestaShop/assets/16019289/4283015e-609a-427c-938d-9b3563257496

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
