### ISSUE TITLE
Service unavailable when upgrading to ps 8.1.7 with autoupgrade-5.0.3

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/PrestaShop#36535]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Already did few upgrades with module version 5.0.3 and never had such problems. Now it throws service unavailable

![obraz](https://github.com/PrestaShop/PrestaShop/assets/5007456/48dace6a-c954-4657-a953-689229aac4ef)

Server logs say:
> Error on sending request(POST /admin.../autoupgrade/ajax-upgradetab.php HTTP/2.0); uri(/admin.../autoupgrade/ajax-upgradetab.php) content-length(23004): ReceiveAckHdr: timeout 300 is exceeded, referer: mydomain.com/admin.../index.php?controller=AdminSelfUpgrade&token=bc02f0...

Looks like an issue with my server, but can't figure out what exactly is the cause and why it only started now. It worked before on the same server and same versions involved.

### Expected behavior

Completed upgrade

### Steps to reproduce

1. Install 1-click upgrade module
2. Try upgrading the shop to 8.1.7

### PrestaShop version(s) where the bug happened

FROM 8.1.5 TO 8.1.7

### PHP version(s) where the bug happened

8.1.25

### If your bug is related to a module, specify its name and its version

autoupgrade

**Comment by SharakPL** [comment]
Turns out the reason was a very limited transfer speed on the server

**Comment by florine2623** [comment]
FYI @AureRita if you ever encounter this issue
