### ISSUE TITLE
If no employee is assigned in the context, cart ID must be provided to this method.

### ISSUE THREAD

**Issue by LaqueP** [PrestaShop/PrestaShop#36549]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you change the language with a cart or log with user who default lang is not the same, frontoffice return the following error:

If no employee is assigned in the context, cart ID must be provided to this method.

The only way to the user can navigate again is removing the cart from the backoffice.

Fatal error: Uncaught PrestaShopException: If no employee is assigned in the context, cart ID must be provided to this method. in /home/admin/domains/entorno.nestdream.com/public_html/classes/Tools.php:1124 Stack trace: #0 /home/admin/domains/entorno.nestdream.com/public_html/classes/Product.php(3663): ToolsCore::displayError() #1 /home/admin/domains/entorno.nestdream.com/public_html/classes/Product.php(5688): ProductCore::getPriceStatic() #2 /home/admin/domains/entorno.nestdream.com/public_html/classes/Cart.php(824): ProductCore::getProductProperties() #3 /home/admin/domains/entorno.nestdream.com/public_html/modules/advancedvatmanager/advancedvatmanager.php(3362): CartCore->getProducts() #4 /home/admin/domains/entorno.nestdream.com/public_html/modules/advancedvatmanager/advancedvatmanager.php(3340): AdvancedVatManager->saveCartAndCustomerCookie() #5 /home/admin/domains/entorno.nestdream.com/public_html/classes/Hook.php(1077): AdvancedVatManager->hookActionCartSave() #6 /home/admin/domains/entorno.nestdream.com/public_html/override/classes/Hook.php(50): HookCore::coreCallHook() #7 /home/admin/domains/entorno.nestdream.com/public_html/classes/Hook.php(418): Hook::coreCallHook() #8 /home/admin/domains/entorno.nestdream.com/public_html/classes/Hook.php(983): HookCore::callHookOn() #9 /home/admin/domains/entorno.nestdream.com/public_html/classes/Cart.php(303): HookCore::exec() #10 /home/admin/domains/entorno.nestdream.com/public_html/classes/controller/FrontController.php(454): CartCore->update() #11 /home/admin/domains/entorno.nestdream.com/public_html/controllers/front/listing/CategoryController.php(81): FrontControllerCore->init() #12 /home/admin/domains/entorno.nestdream.com/public_html/classes/controller/Controller.php(300): CategoryControllerCore->init() #13 /home/admin/domains/entorno.nestdream.com/public_html/classes/Dispatcher.php(510): ControllerCore->run() #14 /home/admin/domains/entorno.nestdream.com/public_html/index.php(28): DispatcherCore->dispatch() #15 {main} Next PrestaShop\PrestaShop\Core\Exception\CoreException: If no employee is assigned in the context, cart ID must be provided to this method. in /home/admin/domains/entorno.nestdream.com/public_html/classes/Hook.php:431 Stack trace: #0 /home/admin/domains/entorno.nestdream.com/public_html/classes/Hook.php(983): HookCore::callHookOn() #1 /home/admin/domains/entorno.nestdream.com/public_html/classes/Cart.php(303): HookCore::exec() #2 /home/admin/domains/entorno.nestdream.com/public_html/classes/controller/FrontController.php(454): CartCore->update() #3 /home/admin/domains/entorno.nestdream.com/public_html/controllers/front/listing/CategoryController.php(81): FrontControllerCore->init() #4 /home/admin/domains/entorno.nestdream.com/public_html/classes/controller/Controller.php(300): CategoryControllerCore->init() #5 /home/admin/domains/entorno.nestdream.com/public_html/classes/Dispatcher.php(510): ControllerCore->run() #6 /home/admin/domains/entorno.nestdream.com/public_html/index.php(28): DispatcherCore->dispatch() #7 {main} thrown in /home/admin/domains/entorno.nestdream.com/public_html/classes/Hook.php on line 431

### Steps to reproduce

1. Add product to the cart.
2. Log with a user with a diferent lang configured (The website have Geolocalization)

Video:
https://www.loom.com/share/417672f13ac14a04a785f33ad8a126d5?sid=33d0f8b3-a92f-4268-a48d-cabfc3438bbd

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello @LaqueP ,

The problem comes from your module Advanced VAT manager.
Please disable it ans try again, you shouldn't have this issue anymore or contact the develop of the module directly.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by LaqueP** [comment]
@florine2623  Sorry, I din't see the part of vatmanager, very appreciate.

**Comment by SashokN** [comment]
Same bug on 8.1.7

When you change the language with a cart or log with user who default lang is not the same, frontoffice return the following error:

If no employee is assigned in the context, cart ID must be provided to this method.

https://yokotower.com/

How to fix?
​​​​​​​Thanks

P.S. This module did not use "Advanced Vat Manager"

**Comment by panariga** [comment]
Error message should be updated by adding: "Cart object has not been created in the current context during this execution cycle. Ensure the cart is present in the context or the cart ID is passed."

For example, calling hook actionCartSave is executed before $context->cart is created and leads to an error, which can cause significant debugging time for developers.
