### ISSUE TITLE
[Prestashop 9] RMA is not working as expected

### ISSUE THREAD

**Issue by addison74** [PrestaShop/PrestaShop#36544]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

RMA in the customer account is not listing anything

### Steps to reproduce

1. Enable RMA in the BO
2. Place an order in the FO
3. Go to the BO and process it
4. Go to the customer account RMA section. There are no order listed.
5. Return the items in the order from the BO
6. Go to the customer account RMA section. There are no information here.

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.3

**Comment by florine2623** [comment]
Hello @ADDISON74 ,

I cannot reproduce your issue.

I ask for a merchandise return :
<img width="1138" alt="Screenshot 2024-07-15 at 11 22 10" src="https://github.com/user-attachments/assets/076b03ba-9a3d-4f33-8bb1-3614d1b4f9f2">

I check the merchandise return section in my customer account :
<img width="1157" alt="Screenshot 2024-07-15 at 11 21 51" src="https://github.com/user-attachments/assets/e9017c17-40af-4301-9b9a-5f5c9d9908db">

**Comment by addison74** [comment]
@florine2623 - Let's not rush to close this report so fast. 

How did you make the merchandising request? From the customer's account?

**Comment by addison74** [comment]
@florine2623 - any updates to my request?
