### ISSUE TITLE
[Prestashop 9] Dropdown menu arrow in Orders 

### ISSUE THREAD

**Issue by addison74** [PrestaShop/PrestaShop#36542]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Please see the image bellow. The arrow needs a margin/padding to the right like the others used in the BO.

![Screenshot 2024-07-14 233028](https://github.com/user-attachments/assets/c1740e9d-6adf-4abd-8182-911ad5f3a3c0)

### Steps to reproduce

Go to the BO > Orders

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.3

**Comment by Hlavtox** [comment]
@tblivet This is probably resolved after the rebrand right? You can close it I think. :-)

**Comment by tblivet** [comment]
@Hlavtox Yes, this issue is resolved with the rebrand 👍 I close it !
