### ISSUE TITLE
 Automatic messages are not sent to customers about the status of their orders, although a sent message appears

### ISSUE THREAD

**Issue by Giovaprnew** [PrestaShop/PrestaShop#36547]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The automatic messages to customers about the status of their orders do not arrive even though the platform confirms the successful sending of the same, the other messages such as password change are arriving but in previous consultations with PrestaShop they have indicated to me that it may be a Blocking error in the hosting or configuration of the E-mail either automatically or through SMTP but this has already been reviewed and everything is correct.
![Captura de Pantalla 2024-07-06 a la(s) 2 07 30 p  m](https://github.com/user-attachments/assets/6d2fc25d-8579-415c-8b20-751c18021a8d)
![Captura de Pantalla 2024-07-13 a la(s) 8 53 15 a  m](https://github.com/user-attachments/assets/3866b56c-a558-4559-b405-24da9742d74e)

### Expected behavior

Order status messages arrive normally to customers' email accounts

### Steps to reproduce

1. Back office 2. Orders 3. See 4. forward email

### PrestaShop version(s) where the bug happened

1,7

### PHP version(s) where the bug happened

8.1.27

**Comment by Hlavtox** [comment]
If it doesn't throw any error, the email is either eaten somewhere in the system due to bad configuration, or thrown away by the receiver. Check your server config, mail logs, dkim settings, spf records etc.

**Comment by florine2623** [comment]
Hello,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
