### ISSUE TITLE
Mail alert dont send new_order

### ISSUE THREAD

**Issue by TobW5** [PrestaShop/PrestaShop#36566]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

I'm on prestashop 1.7.6.5 and the module email alerts dont send new order by email.
My SMTP configurations is ok I receive mail.
I use custom theme and worked yesterday and not today.

### Steps to reproduce

Validate command
and dont receive confirmation new_order

### PrestaShop version(s) where the bug happened

1.7.6.5

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

Email Alerts

**Comment by florine2623** [comment]
Hello,

I suggest contacting your hosting provider for that issue.
It is not related to PrestaShop itself. 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
