### ISSUE TITLE
Autoupgrade : ps_customtext A DataBase Exception in FO when upgrade from 1.7.0.6 to 1.7.8.11 in php 7.1 

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#36567]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After an upgrade 1.7.0.1 to 1.7.8.11 the ps_customtext throw an exception in FO
![Capture d’écran de 2024-07-17 15-36-33](https://github.com/user-attachments/assets/488bfcba-0be1-43fc-a6a7-a29af54818d9)

### Expected behavior

No error

### Steps to reproduce

1. Install PS 1.7.0.1 from the docker image 1.7.0.1-7.1-apache
2. Upgrade to 1.7.8.11
3. See the error in FO

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

autoupgrade

**Comment by nesrineabdmouleh** [comment]
I reproduce the issue also with : 
- PS 1.7.1.0 ~ 1.7.1.2 after upgrade to 1.7.8.11
- PS 1.7.2.0 ~ 1.7.2.3 after upgrade to 1.7.8.11
- PS 1.7.3.0 ~ 1.7.3.4 after upgrade to 1.7.8.11

**Comment by Quetzacoalt91** [comment]
FYI, I checked on the Marketplace and this module is properly distributed from 1.7.0.0 >> 8.1.7.

**Comment by Quetzacoalt91** [comment]
With the incoming PR https://github.com/PrestaShop/autoupgrade/pull/850, the migration is now applied properly and the FO is working as expected.

```
Checking updates of module ps_customtext...
Module ps_customtext update files (1.0.5 => 4.2.1) have been fetched from https://api.addons.prestashop.com/?id_module=22317&method=module&version=1.7.8.11.
Content of archive /var/www/html/**admin_folder**/autoupgrade/tmp/ps_customtext.zip is extracted
(1/1) Applying migration file install-3.0.0.php.
34 modules left to update.
```
