### ISSUE TITLE
PPV2 - If 2 Features have the same name, only one will be displayed

### ISSUE THREAD

**Issue by lferrerraventos** [PrestaShop/PrestaShop#36586]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If a Feature is duplicated, in the Product Detail page, only one feature will be displayed.
Same goes for a Feature value.

### Expected behavior

Both features/features values should be displayed.

A possible workaround would be:
https://github.com/PrestaShop/PrestaShop/blob/11ae6d7ce71888de4b911ebe745ce5d423d57004/src/Adapter/Form/ChoiceProvider/FeatureValuesChoiceProvider.php#L85

Line: 85
```
        foreach ($featureValues as $feature) {
            $this->cacheFeatureValueChoices[$cacheKey][$feature['id_feature_value']." - ".$feature['value']] = (int) $feature['id_feature_value'];
        }

```

### Steps to reproduce

1. Go to BO > Catalog > Attributes and Features > Features Tab
2. Add 2 **features** with the same name
3. Go to BO > Product page > Edit any product > Go to Details tab
4. Choose a Feature : See only one feature is displayed :x:
5. Go to BO > Catalog > Attributes and Features > Features Tab
6. Add 2 **features values** with the same name
7. Go to BO > Product page > Edit any product > Go to Details tab
8. Choose the feature where you have 2 identical feature values :
9. Choose a value : See only one feature value is displayed :x:

### PrestaShop version(s) where the bug happened

8.1.7, 9.0.0

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/36703
