### ISSUE TITLE
BO - Creation of an empty Pack Product

### ISSUE THREAD

**Issue by theodoroz** [PrestaShop/PrestaShop#36597]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I am able to create an empty Pack of Products, this pack is saved successfully even if there is no product in it.

https://github.com/user-attachments/assets/73f894c0-b7b2-4619-bbf3-c37a463fb351

### Expected behavior

I am not supposed to be able to create an empty Pack of Products, instead i have to receive the following messages after clicking the save button. 
"Unable to update settings".
"This pack is empty. You must add at least one product item." appears under the title

### Steps to reproduce

1. Go to BO > Catalog > Products 
2. Click Add new products > Choose Pack of products
3. Enter a name > Add quantity > Add price
4. Save 

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.1.13

**Comment by Hlavtox** [comment]
I don't think it's a problem and definitely not a major one. What if the merchant wants to prepare a pack and then assign the components?

Imagine you go to create the pack, fill all descriptions, images and then you realize you don't have one of the components you need. You should be able to save it.

Ping @kpodemski

**Comment by amine-O** [comment]
@florine2623 it's the same behavior than on 8.1.x so we don't consider it as an issue. We'll see if we have other feedbacks about it
I close the issue
