### ISSUE TITLE
Wire payment module error

### ISSUE THREAD

**Issue by NathanOpalook** [PrestaShop/PrestaShop#36592]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

I just finished configuring the checkout section of my website and encountered an issue with the wire payment module from Prestashop. For context, my website supports 17 languages, so I tested the checkout process in all of them. However, an error occurs when I select the following languages: Polish, Romanian, NL, and Japanese. The checkout works fine for the other languages. After investigating, I discovered that the wire payment module is the cause of the error. The error does not appear when the module is deactivated.

Have you encountered this error ?

Here is the main error : 
Fatal error: Uncaught ValueError: Unknown format specifier " " in /home/u508718575/domains/opalook.eu/public_html/modules/ps_wirepayment/ps_wirepayment.php:421 Stack trace: #20064 

You can check the error displayed in debug mode : !
![Capture d'écran 2024-07-23 100506](https://github.com/user-attachments/assets/2b82f137-ed41-47fa-8673-a72e9d080f27)

Deuxième partie de l'erreur
[Capture d'écran 2024-07-22 091946](https://github.com/user-attachments/assets/ff9a304d-cc5d-4123-931b-83cdb53ead38)

### Steps to reproduce

1 - go to the checkout part 
2 - check if the error is displayed or not in every language

### PrestaShop version(s) where the bug happened

Prestashop version : 8.1.1

### PHP version(s) where the bug happened

Version de PHP : 8.1.27 

### If your bug is related to a module, specify its name and its version

Wire payment module

### Your company or customer's name goes here (if applicable).

Opalook

**Comment by florine2623** [comment]
Hello @NathanOpalook ,

I can't reproduce your issue.

Please delete your cache, check if you have any overrides in ps_wirepayment. You can also try to reinstall the module.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
