### ISSUE TITLE
`blockwishlist` : Add a product (with specific combination) to favorite 

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#36593]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In branch dev, you can choose a product with combination on frontoffice and add to favorite but it's not the combination which is added to wishlist

### Steps to reproduce

1. Use `dev` branch for blockwishlist (`npm i && npm run build`)
2. Reset module
3. Go to FrontOffice
4. Connect as user
5. Go to "Hummingbird printed t-shirt"
6. Choose Size "M" & Color "Black"
7. Add to favorite
8. Check the wishlist in My Account Page
![image](https://github.com/user-attachments/assets/e1fcabb6-497b-40f7-bc64-0479057ca46b)

### PrestaShop version(s) where the bug happened

9.0.x

### PHP version(s) where the bug happened

9.1

### If your bug is related to a module, specify its name and its version

blockwishlist dev

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

**Comment by florine2623** [comment]
Related to https://github.com/PrestaShop/PrestaShop/issues/36453

**Comment by Progi1984** [comment]
Need release of the module.

**Comment by matks** [comment]
Release PR here https://github.com/PrestaShop/blockwishlist/pull/276

**Comment by matks** [comment]
Once the module has been released, we need to acknowledge the new version inside the Core, then update the UI Test which verifies it (it is skipped today)
