### ISSUE TITLE
The maintenance mode link in the header no longer appears.

### ISSUE THREAD

**Issue by tblivet** [PrestaShop/PrestaShop#36599]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When the shop is in maintenance mode, the link in the header no longer appears.

**v8.1.2** ✅
![image](https://github.com/user-attachments/assets/93c5d2f2-9eb8-4b0e-9218-d069c9b23720)
**develop** ❌
![image](https://github.com/user-attachments/assets/159c826a-ade6-4c1d-8e07-c1150ba836f5)

### Expected behavior

When the shop is in maintenance mode, the link in the header should appear.

![image](https://github.com/user-attachments/assets/93c5d2f2-9eb8-4b0e-9218-d069c9b23720)

### Steps to reproduce

In your PrestaShop BO "**Shop Parameters**" → "**General**" and tab "**Maintenance**" set `Enable store` to **No**.
A "**Maintenance mode**" link should appear in right part of the header.

### PrestaShop version(s) where the bug happened

develop

### Your company or customer's name goes here (if applicable).

PrestaShopCorp

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/36736
