### ISSUE TITLE
Vulnerability report 

### ISSUE THREAD

**Issue by Deepkachhadiya** [PrestaShop/PrestaShop#36608]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hii, my name is Deep. Recently I found vulnerability which is knowns as pre account takeover via Oauth misconfiguration in one of your components. which is smseagle.eu. 

### Expected behavior

Only one thing we need here and that is email address. Just by knowing that we can takeover victim's account so the impact here is quite high. Imagine email address is something you can even get if you ask so its not a hard task. But since the oauth does not authenticates the real user attackers can easily takeover the account.

### Steps to reproduce

1. Go to https://smseagle.eu/store/en/login?create_account=1 and signup using the unregistered victim’s account. 
2. After the sometime victim is going to signup using the OAuth method. 
3. What happens here is, now the victim can easily log in using the victim’s account which bypasses the verification methods. 

### PrestaShop version(s) where the bug happened

NO

**Comment by matks** [comment]
Hello @Deepkachhadiya are you sure you are posting in the right place? This repository is the PrestaShop project we have no links to smseagle.eu

**Comment by Deepkachhadiya** [comment]
See this

**Comment by paulnoelcholot** [comment]
Your message is empty. Thanks to reply with github please.

**Comment by BenTen** [comment]
I guess the website of the first post is using Prestashop with a template of Promokit developer, who got a lot of critical vulnerability report https://security.friendsofpresta.org/

Anyway, nothing related with the core here.

**Comment by matks** [comment]
Thanks for the informations, closing then
