### ISSUE TITLE
Localisation - Import pack Japan will change my Local units automatically to the Japanese ones

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#36601]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I import Japan Pack, my local units are modified automatically
It is the case for any country pack that has a different local units.
It will always take the latest local unit of the country pack.

<img width="1093" alt="Screenshot 2024-07-23 at 16 50 20" src="https://github.com/user-attachments/assets/b5745535-b528-4812-b3b9-136046a87592">

My default language is English and my default Country is France
<img width="1126" alt="Screenshot 2024-07-23 at 16 48 43" src="https://github.com/user-attachments/assets/730fdacf-0753-4619-aee8-0e407302258f">

### Expected behavior

The local unit should be modified only if I change my default country.

### Steps to reproduce

1. Go to BO > International > Localization >  Import a localization pack for Japan
2. See Local units are modified :x:

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.1

**Comment by BenTen** [comment]
- #11061 ?

**Comment by amine-O** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/11061
