### ISSUE TITLE
1 click upgrade

### ISSUE THREAD

**Issue by Emmanuelaviat** [PrestaShop/PrestaShop#36609]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi.
My upgrades don't work.
I use
Prestashop  1.7.8.7

Informations du serveur : Linux #1 SMP Wed Nov 30 08:49:06 UTC 2022 x86_64
Version du logiciel serveur : Apache
Version de PHP : 7.4.33
Limite de mémoire : 512M
Temps maximal d'exécution : 165
Taille max. pour envoi de fichiers : 128M

### Steps to reproduce

Let's upgrade to new version

Message : 
[Ajax / Server Error for action backupFiles] textStatus: "error " errorThrown:" " jqXHR: " undefined"
vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/Exception/NoSuchIndexException.php ajouté à l'archive. 40902 fichiers restants.

 Le paramètre PHP max_execution_time a une valeur élevée ou est complètement désactivé (valeur actuelle : 165 secondes) 

Erreur lors de la tentative d'ajout de /home/poirriz/www/index.html.ovh.old à l'archive index.html.ovh.old.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

1-Click Upgrade v6.0.0

### Your company or customer's name goes here (if applicable).

Poirriez

**Comment by venditdevs** [comment]
@Emmanuelaviat, please change the language to English. English is the norm on Github.

**Comment by kpodemski** [comment]
First, try to skip the backup process, do it manually, skip in the upgrade and try without it

**Comment by Emmanuelaviat** [comment]
I removed a file .old at first level with ftp and now it’s ok, i upgraded.
Regards.
