### ISSUE TITLE
Product in stock or out of stock

### ISSUE THREAD

**Issue by Jaantox79** [PrestaShop/PrestaShop#36605]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I don't understand why the theme developers don't. I think it is important that the product page should state whether the product is in stock. Difficult to click on the product page to check if it is in stock. Simple you can see in the product list. The theme developer said it's hard to add…

### Steps to reproduce

I don't understand why the theme developers don't. I think it is important that the product page should state whether the product is in stock. Difficult to click on the product page to check if it is in stock. Simple you can see in the product list. The theme developer said it's hard to add…

### PrestaShop version(s) where the bug happened

8.1.6

### PHP version(s) where the bug happened

8.0

**Comment by florine2623** [comment]
Hello @Jaantox79 ,

The product stock is displayed on the product list, on the product details page, on the stock management page.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
