### ISSUE TITLE
Module with conflicting override can still be installed

### ISSUE THREAD

**Issue by JohnPAfr** [PrestaShop/PrestaShop#36617]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When installing a module, if an error occurs during the process, the module is still uploaded into the shop and saved into the db. However, it is not installed. When you retry the installation of the same module, since it's present in the modules/ the install succeed without causing any errors.

### Expected behavior

If an error occurs during a module install, we shouldn't be able to install the exact same module.
Also if an error occurs during the process, the module shouldn't not be in the shop.
[screencast.webm](https://github.com/user-attachments/assets/d64983c6-7e70-47fe-b0d1-b17c9685315e)

### Steps to reproduce

1. Create or get two diffrent modules with the same override doing different actions,
2. Go to module manager and upload **one**,
3. After completion, install the **second** module,
4. An error should appear in the top right corner of your window (toaster notification),
5. You can check in db, module table, the second module should be there,
6. Try reuploading the **second** module,
7. The install should be successful.

The problems comes from the ```install()``` function in ```classes/module/Module.php```
The module is inserted into db but the override check is done after that.

### PrestaShop version(s) where the bug happened

8.1.x / 9

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

Prestashop SA

**Comment by ShaiMagal** [comment]
For me its not bug, but feature.

I already wrote my detailed opinion about this at PR #36639

**Comment by florine2623** [comment]
@PrestaShop/product-council ,

WDYT ? Can we have an opinion on this ?

**Comment by florine2623** [comment]
Fixed in https://github.com/PrestaShop/PrestaShop/pull/36639
