### ISSUE TITLE
 Cannot set specific price with currency filter 

### ISSUE THREAD

**Issue by nyupyu** [PrestaShop/PrestaShop#36629]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello everyone,
We have discovered a bug with the specific pricing feature that prevents us from setting different prices in non-default currencies for products. We want to set fixed prices for one of our manufacturers, but we can't due to the rate multiplier.

Even after setting a stiff specific price in a different currency, the price is still multiplied by the exchange rate.

For example, the normal price in EUR:
![image](https://github.com/user-attachments/assets/e1ee90da-8f1d-44fb-a511-b8c72ba3cded)

Here, it should be 10 USD, but it is multiplied by the exchange rate:
![image](https://github.com/user-attachments/assets/3c144799-69e8-41a0-9b4c-a305afecced4)

Currencies:
![image](https://github.com/user-attachments/assets/23f615a9-51d3-40dc-8e47-316981c92a39)

Product specific price:
![image](https://github.com/user-attachments/assets/b64b90ad-ea76-463b-9675-b396b822b813)

### Expected behavior

A fixed specific price should be as we set it, for example, 5 USD, not "5 USD * exchange rate". It works okay when you add a specific price in the default currency as it is supposed to be multiplied by the exchange rate.

### Steps to reproduce

Back Office:

1. Go to International > Localization > Currencies.
2. Set up an additional currency with an exchange rate, in my case x2.
3. Go to Products > Catalog > Add new product.
4. In the product "Pricing" tab, add a price (in my case it will be 5 EUR).
5. Scroll to the bottom > Specific prices > Add a Specific Price.
6. In "Apply to," choose the additional currency and then scroll to the bottom.
7. Turn on "Set specific price" and enter a value, in my case 10 USD

Front Office:

1. Go to the added product and check the price.
2. Verify the price.
3. Change the currency to the second one.
4. Check the price again.

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_currencyselector

**Comment by florine2623** [comment]
Hello @nyupyu ,

I followed your steps and I can't reproduce your issue.
Could you please give more details ?

My currency configuration :
<img width="1174" alt="Screenshot 2024-08-06 at 16 03 05" src="https://github.com/user-attachments/assets/90952078-c667-4ac2-a246-ea52ccadb297">

My base price :
<img width="786" alt="Screenshot 2024-08-06 at 16 02 28" src="https://github.com/user-attachments/assets/4de3191b-e3f2-4720-a0ae-464f10a53629">

My specific price :
<img width="1194" alt="Screenshot 2024-08-06 at 16 02 17" src="https://github.com/user-attachments/assets/c98e9bd3-594d-4ee9-94ce-db2f8fb5c2e6">

https://github.com/user-attachments/assets/0d46c7d2-9278-4f88-b164-801f47f77127

Waiting for your feedback, thanks!

**Comment by nyupyu** [comment]
I also made a video to clearly show you what's going on, but it was too big. Here is that video in lower quality (10 MB limit).
That's a fresh install of presta, in my opinion price should be $10, not $10 multiplied by exchange rate (x2 in this case that is 20$). 

We attempted to add one manufacturer with special prices in EUR and PLN, but we are unable to do so and that manufacturer is still in catalog mode.

https://github.com/user-attachments/assets/5b5b5c42-dc24-41fb-8611-1e00dd423957

**Comment by nyupyu** [comment]
I also made a video to clearly show you what's going on, but it was too big. Here is that video in lower quality (10 MB limit).
That's a fresh install of presta, in my opinion price should be $10, not $10 multiplied by exchange rate (in this case it is $10 x2).

We attempted to add one manufacturer with special prices in EUR and PLN, but we are unable to do so and that manufacturer is still in catalog mode.

https://github.com/user-attachments/assets/776ff96d-481d-4e77-b0d4-12a27bdaffd2

**Comment by nyupyu** [comment]
I found solution on classes/product.php

line 3896:
id_currency === $specific_price['id_currency']  => id_currency !== $specific_price['id_currency']

![image](https://github.com/user-attachments/assets/444efd09-f1b6-470f-8d62-c454d20c8bb5)

**Comment by nyupyu** [comment]
Here is solution I pulled 

https://github.com/PrestaShop/PrestaShop/pull/36737#issuecomment-2301459072

**Comment by kpodemski** [comment]
It seems that things are a bit more complicated because this has already been changed some time ago to fix another issue, here are the details:

https://github.com/PrestaShop/PrestaShop/issues/33285

**Comment by kpodemski** [comment]
Probably related:
https://github.com/PrestaShop/PrestaShop/issues/36836

and this: https://github.com/PrestaShop/PrestaShop/issues/36844

No need to change `===` to `!==` but it is important not to compare strictly or to cast variables.

**Comment by nyupyu** [comment]
When I'll back to "===" I have problem back. My specific prices are multuplying by currency rate. In my opinion it's critical bug, my client's clients wants to buy someting for 1000pln as they set, not 4200pln cause of bug. I'll wait for good solution, not that "solution" to fix antoher issue.

**Comment by kpodemski** [comment]
@nyupyu could you try to change from === to ==?

**Comment by nyupyu** [comment]
> @nyupyu could you try to change from === to ==?

It works! 

I did some tests and it works as it supposed to be.

**Comment by kpodemski** [comment]
Closed in favor of https://github.com/PrestaShop/PrestaShop/issues/36844
