### ISSUE TITLE
Payments preferences with Belgium

### ISSUE THREAD

**Issue by polaije** [PrestaShop/PrestaShop#36630]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Prestashop version 8.1.7
In module Payments/Countries
Belgium is selected for all payments methods.
When page is refeshed : Belgium is not selected.

When not selected, selections manually and write, page refeshed, Belgium is not selected.
After the try of Belgium selections and write, not payments method appeared in front office with Belgium address.
At the first stage with Belgium selected, the payments methods are displayed in front office.

Jean-Marie

### Expected behavior

Payments methods for Belgium has to be displayed on the FO 

### Steps to reproduce

Payments/Preferences
Belgium has to be selected 

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment]
Hello @polaije ,

I can't reproduce your issue on PS 8.1.7.

When the page is refreshed, all payments are still checked for Belgium country :

https://github.com/user-attachments/assets/854a95e8-44fb-4236-90b8-3e3b1918c8ec


I can make an order vi my FO :

https://github.com/user-attachments/assets/c0ffedb7-1eb1-4d6c-8556-cd7cb3b32ffb


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

Thanks!
