### ISSUE TITLE
PrestaShop error when manage over 90k products with a specific price set.

### ISSUE THREAD

**Issue by frater1998** [PrestaShop/PrestaShop#36631]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi, 
I add in bulk specific price for all my products ( I need to add a single discount for each product).

I manage over 90k product in the store.

When these discounts are applied the site got down and in logs there is an error like: "mysql has gone away".

### Steps to reproduce

In bulk via PHP script add specific price for each product.

Then go to home page and see the error

### PrestaShop version(s) where the bug happened

8.1.6

### PHP version(s) where the bug happened

8.1

**Comment by ShaiMagal** [comment]
What about to try catalog rules...?

This problem looks like for webhosting environment. Do you have high end hosting?

You got error message instantly or after any time? For example after 60 seconds?

When you add smaller amount of specific prices, I guess its working fine, true?

Share us your php script. We can try it on our environment for compare.

**Comment by frater1998** [comment]
Hi, 
We cannot use the catalog rules because each product has a different discount percentage.
We thought it was a hosting problem too, so we switched from VPS to a dedicated server.
Thus, by entering the specific prices for all products we get a long loading (about 40 seconds) and consequently an overload error. This only for the home page, browsing directly the product page does not happen.
Using a few specific prices everything works properly.
We don’t have a custom PHP script, but we use the simpleimportproduct module by passing it a csv.

**Comment by paulnoelcholot** [comment]
Hello @frater1998,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by kpodemski** [comment]
Hello @frater1998 

I'm afraid there is nothing to do on our side. You must optimize your homepage or store to work correctly with your needs. Suppose your homepage is unavailable because you have 90k products with discounts. In that case, it is not something with PrestaShop core but instead with some module, maybe a third-party module, that, for example, tries to get discounted products to show on the first page and does it incorrectly, or it is not optimized to handle this amount of products.
