### ISSUE TITLE
Unable to import theme on Prestashop 8.1.7, used on older version

### ISSUE THREAD

**Issue by dbrisson-passat** [PrestaShop/PrestaShop#36647]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello everyone, as part of the evolution we want to upgrade a prestashop 1.7.8.7 => 8.1.7 (at least an 8.x).

Except that when I put the zip of my theme on the BO of my Prestashop 8.1.7 store, this is the error I get "Please select a valid source for your theme import." 

![image](https://github.com/user-attachments/assets/443f5f92-fec5-4cd0-b72b-c504e83ca19e)

Yet when I look at the theme compatibility under /config/theme.yml I see compatibility from 1.7.2.0 to ~ (so all versions after this one?) :

![image](https://github.com/user-attachments/assets/1a9eeae8-0d7c-494a-a699-3c05cd364eda)

### Expected behavior

I thought the .zip theme would have loaded into my backoffice so I could use it.

### Steps to reproduce

1. Place the .zip template in the /template folder (theme functional under prestashop versions 1.7.8.7)
2. Go to “Design
3. Click on “Customization”.
4. At the bottom of the page, click on “Import theme” and choose “Import from FTP”.
5. Choose the archive corresponding to the .zip folder in /theme
6. Once on the “Do you want to display this page?” page, click on “Yes, I understand the risks.”
7. The bug occurs, making it impossible to install the theme.

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.1.26

**Comment by ShaiMagal** [comment]
I think, your theme isn't compatible with PS8. Ask developer of theme first.

There are differences beetween PS 1.7/PS8. Theme shouldn't be same for PS 1.7/PS8.

Before upgrade your store you need to download latest version of third party modules/themes for your new version to be sure, there will be everything working fine.

**Comment by dbrisson-passat** [comment]
I think so too, but I've tried installing another theme, for example the one currently under development that will replace the classic, the "hummingbird.zip" theme, but nothing works... I can't add a theme.

**Comment by ShaiMagal** [comment]
Sorry, not major problem of PrestaShop, I tested on clean install for PS 8.1.7 installing theme and no problem.

I don't know, why it's not working. I can't help more. Maybe someone else will.

**Comment by dbrisson-passat** [comment]
No problem, have you tried it with the Wamp server? I'm using PHP version 8.1.26 and Apache 2.4.58. I have 3 errors when installing the store, which I've managed to correct, but once the store is installed I keep getting this error message regardless of the theme. Which theme have you tried?

**Comment by florine2623** [comment]
Hello @dbrisson-passat ,

I can't reproduce your issue as you can see :

https://github.com/user-attachments/assets/4af8a865-6785-4b48-9c7b-3d053cadb086

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by dbrisson-passat** [comment]
I don't have this interface in my back office, it's normal ?

![image](https://github.com/user-attachments/assets/0a9fa64a-812e-4b8e-9d10-353293a5b1fd)


Thank you
