### ISSUE TITLE
Methods addJqueryPlugin / addJqueryUI are not available on migrated controllers when used in displayBackOfficeHeader/actionAdminControllerSetMedia hooks

### ISSUE THREAD

**Issue by prestamodule** [PrestaShop/PrestaShop#36649]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

I'm facing an exception when attempting to use the `addJqueryPlugin`/`addJqueryUI` methods in the `displayBackOfficeHeader`/`actionAdminControllerSetMedia` hooks on the new product page:

```Error rendering "HeadTag" component: Call to undefined method ContainerXXXXX\LegacyControllerContextProxyXXXXXX::addJqueryUI()```

It appears the methods are not defined in the `LegacyControllerContext` (src/Core/Context/LegacyControllerContext.php) unlike addJS/addCSS which are available and can be used without issue.

Copying the methods from the `Controller` class to the `LegacyControllerContext` class appears to solve the issue and the plugins are properly added.

I believe this should be kept in v9 as these methods are still used by module developers to import jQuery UI/plugins present in the root `/js` folder of PrestaShop, which remains more convenient than having modules ship their own scripts.

### Expected behavior

These method should remain available in order to allow module developers to include these native assets on the migrated controller pages.

### Steps to reproduce

- Register a module on either `actionAdminControllerSetMedia` or `displayBackOfficeHeader`
- Have said method call `$this->context->controller->addJqueryUI(['ui.slider'])` or `$this->context->controller->addJqueryPlugin('tablednd')`
- Enter a migrated controller like the new product edition page, and see the exception:
```Error rendering "HeadTag" component: Call to undefined method ContainerXXXX\LegacyControllerContextProxyXXXXX::addJqueryUI()```

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

PrestaModule

**Comment by Hlavtox** [comment]
Seems like a very major issue, jQuery UI must work. Ping @kpodemski @jolelievre

**Comment by jolelievre** [comment]
Indeed, @amine-O this should probably be added in the freeze kanban for stabilisation

**Comment by prestamodule** [comment]
Hello everyone,

Are there any updates on this? I just want to be sure that the issue isn't forgotten since this is pretty important for a lot of modules.

Thank you

**Comment by jolelievre** [comment]
Indeed this must be fixed before the V9 is released
@ibahloul-ps this should be prioritized in our stabilization kanban.

The `PrestaShop\PrestaShop\Core\Context\LegacyControllerContext` service is missing these two methods `addJqueryPlugin` and `addJqueryUI`
