### ISSUE TITLE
Cannot download / generate Invoices in bulk through Backoffie PS 8.1.6

### ISSUE THREAD

**Issue by Jonteep** [PrestaShop/PrestaShop#36651]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,

I am running Prestashop 8.1.6 and would like to download invoices in bulk through the Backoffice, one week at a time.

Unfortunately this is not working, when I go to Orders > Invoices > Create PDF file by date, it just refresh the page and nothing happens.

If I try to do the same with delivery slips, it works fine.

What could be causing this?

I also noticed it on my other websites running PS 8.1.7.

PHP version is 8.1.29.

Many thanks in advance.

Best regards,
Jonte

### Expected behavior

To be able to download invoices in bulk (PDF containing several invoices) through the admin interface.

### Steps to reproduce

Go to Orders > Invoices > Create PDF file by date, click the button after selecting date intervals.

### PrestaShop version(s) where the bug happened

8.1.6 and 8.1.7

### PHP version(s) where the bug happened

8.1.29

### If your bug is related to a module, specify its name and its version

No.

**Comment by ShaiMagal** [comment]
I tested it, PS 8.1.7 and PHP 8.1, I don't have this problem. (clean PS installation)

You should see error message something like "No invoices were found for the selected period" in red box.

**Comment by Jonteep** [comment]
Hi,

Many thanks for your reply.

I don't see any error message or anything in the logs. When I choose the date interval and click the button, it seems as if the invoices are generated, but the page just reload after a while.

I can download them separately on the orders page, and I can also download delivery slips in bulk.

Could this be related to some setting with the hosting company? I have read other forum threads regarding it: https://www.prestashop.com/forums/topic/1022386-bulk-invoice-generator-do-nothing/

Thanks in advance.

Best regards,
Jonte

**Comment by ShaiMagal** [comment]
@Jonteep yes, it can be related to hosting settings(caching). For example caching text/html content and similar can cause this problem.

**Comment by Jonteep** [comment]
Many thanks for your reply.

I have tested with PS 8.1.7, previous 8.0.X, 1.7.X etc. and the problem exists nevertherless which version I try.

Do you perhaps know which specific setting might be causing this? Since it works with delivery slips (bulk download), I find it somewhat strange. :(

Best regards,
Jonte

**Comment by ShaiMagal** [comment]
@Jonteep So, no PS problem. You should ask webhosting company, it can be more settings..
For example mod_expires (html/text)
or any bad cache settings (APC, opcache, xcache, ....)

You should ask webhosting company.

**Comment by florine2623** [comment]
Hello @Jonteep ,

I can't reproduce your issue in 9.0.x.

https://github.com/user-attachments/assets/1c2bd095-6d71-463c-9360-cb16c210f95b

Please contact your hosting provider ^^

**Comment by aykonsvk** [comment]
I got the same issue, no error in logs just clean redirect, tried debug same...

**Comment by beforcom** [comment]
hi
PrestaShop 1.7.6.1

I'm reopening this thread because I have the exact same problem.
It worked for years. No updates, no new modules, no changes to the hosting.

Generating PDF invoices in batches by date or status doesn't work. The page reloads, and the PDF isn't downloaded. No trace of an error. Even in debug mode.
The reload isn't instantaneous; if I take a single day, it's quick. If I take a week, it takes a few seconds longer, but there are no errors.

However, generating delivery slips in batches works very well.

Have you resolved your problem, which seems identical?

Regards

**Comment by aykonsvk** [comment]
Problem is still present cant do anything about it.
