### ISSUE TITLE
Error Wire Payments

### ISSUE THREAD

**Issue by vegaconsultores** [PrestaShop/PrestaShop#36658]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello!

I have a problem with the Wire Payments module. Every time my clients tried to pay with wire transfer it gives us the following error:
Fatal error: Uncaught TypeError: array_filter(): Argument #1 ($array) must be of type array, bool given in /homepages/1/d566845898/htdocs/clickandbuilds/moaremanualidades/modules/mbeshipping/mbeshipping.php:4125 Stack trace: #0 /homepages/1/d566845898/htdocs/clickandbuilds/moaremanualidades/modules/mbeshipping/mbeshipping.php(4125): array_filter() #1 /homepages/1/d566845898/htdocs/clickandbuilds/moaremanualidades/classes/Hook.php(1043): Mbeshipping->hookActionValidateOrder() #2 /homepages/1/d566845898/htdocs/clickandbuilds/moaremanualidades/classes/Hook.php(418): HookCore::coreCallHook() #3 /homepages/1/d566845898/htdocs/clickandbuilds/moaremanualidades/classes/Hook.php(981): HookCore::callHookOn() #4 /homepages/1/d566845898/htdocs/clickandbuilds/moaremanualidades/classes/PaymentModule.php(558): HookCore::exec() #5 /homepages/1/d566845898/htdocs/clickandbuilds/moaremanualidades/modules/ps_wirepayment/controllers/front/validation.php(63): PaymentModuleCore->validateOrder() #6 /homepages/1/d566845898/htdocs/clickandbuilds/moaremanualidades/classes/controller/Controller.php(308): Ps_WirepaymentValidationModuleFrontController->postProcess() #7 /homepages/1/d566845898/htdocs/clickandbuilds/moaremanualidades/classes/Dispatcher.php(510): ControllerCore->run() #8 /homepages/1/d566845898/htdocs/clickandbuilds/moaremanualidades/index.php(28): DispatcherCore->dispatch() #9 {main} thrown in /homepages/1/d566845898/htdocs/clickandbuilds/moaremanualidades/modules/mbeshipping/mbeshipping.php on line 4125

We tried to install and unninstall the module and still doesn't work. My Prestashop os version 8.1.5.

### Expected behavior

It should appear the option to pay by wire transfer and the bank account number or the bizum phone number.

### Steps to reproduce

1. Select a product https://moaremanualidades.com/es/
2. Add to cart
3. Follow the steps to pay the product
4. Choose wire transfer
5. Check the box below the text to accept the general conditions
6. Error happens and voila

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.129

### If your bug is related to a module, specify its name and its version

Wire Payments v2.2.0

### Your company or customer's name goes here (if applicable).

Moare Manualidades

**Comment by Hlavtox** [comment]
The problem is in high quality `mbeshipping` module. :-)

Ping @PrestaShop/prestashop-sa

@vegaconsultores Uninstall mbeshipping and your shop will work just fine. I suggest having a look into modules section and uninstalling everything you don't need. There is a lot of bundled useless modules with certain distributions of PrestaShop.

**Comment by vegaconsultores** [comment]
Thanks a lot! That was the problem! :)
