### ISSUE TITLE
Retail price (tax excl.) is not correct

### ISSUE THREAD

**Issue by aminvatandoust** [PrestaShop/PrestaShop#36666]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

https://github.com/user-attachments/assets/1a83aa29-e97c-4f4d-ab56-13d4c4791fce

As you can see in the attached video, In the Back office of PrestaShop 8.1 in the product edit page, If you fill in the "Retail price **(tax incl.)**" it will automatically calculate the "Retail price **(tax excl.)**" based on the Tax rule. but the number that is shown in the "tax excl" field is not correct.

For example, I have a tax rule of 10%. I put the Final Price as $100 and expected the tax-excluded price to be $90 (no need for any decimal) but it shows: $90.909091

I've tested this on the demo.prestashop.com to record the video.

### Expected behavior

Calculate the **Retail price (tax excl.)** correctly when user fills the tax incl field.

### Steps to reproduce

1. Go to PrestaShop BO > Catalog
2. Edit a standard Product
3. Go to Pricing tab
4. Select a Tax rule
5. Fill in the "Retail price **(tax incl.)**" field
6. Check the "Retail price **(tax excl.)**" field

### PrestaShop version(s) where the bug happened

8.1

**Comment by kpodemski** [comment]
Hello @aminvatandoust 

It's a normal behavior. We store prices in PrestaShop with 6 decimals. This field doesn't round value in back office.

**Comment by Hlavtox** [comment]
@aminvatandoust Hi, 100 / 1,1 is not 90. :-)))

**Comment by aminvatandoust** [comment]
yeah, my bad. I got conused that I needed the base price before tax. I was doing 10% of $100, which was wrong.
ty @kpodemski and @Hlavtox
