### ISSUE TITLE
Stock Updates for Product Packs on Order Cancellation / stock does not revert to the previous level before the order was made

### ISSUE THREAD

**Issue by samilmarekrygula** [PrestaShop/PrestaShop#36667]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I'm experiencing an issue with stock management in PrestaShop 1.7.2.0. When I cancel an order, the stock levels for products included in a pack are not correctly updated. Specifically, the stock does not revert to the previous level before the order was made.

This issue occurs when I set the order status to "canceled" either directly from the order page or through the bulk action feature. However, I noticed that if I manually remove a pack product from the order, the stock for the products in the pack returns to its previous level as expected.

### Expected behavior

When an order is canceled, I expect the stock levels for all products in a pack to automatically return to the quantities available prior to the order being placed.

### Steps to reproduce

1. Create a Product Pack:
- Add individual products to a pack in PrestaShop.
- Ensure that each product has an initial stock level set (for example 5 pieces)

2. Place an Order:
- Order the product pack through the online store (for example 1 piece)

3. Cancel the Order:
- Navigate to the order details page.
- Change the status of the order to "canceled" directly from the order page or use the bulk action feature to cancel multiple orders at once.

4. Check Stock Levels:
- Verify the stock levels of the individual products in the pack (each products in the pack should have 5 pieces, but have just 4 pieces)

### PrestaShop version(s) where the bug happened

1.7.2.0

### PHP version(s) where the bug happened

7.1.33

### Your company or customer's name goes here (if applicable).

ruby42

**Comment by paulnoelcholot** [comment]
Hello @samilmarekrygula,

I don't reproduce your issue on 8.1.5. I therefore invite you to upgrade your shop.

Thanks

**Comment by Caleydon** [comment]
One of my client is experiencig with the same issue on PrestaShop 8.1.7.

**Comment by samilmarekrygula** [comment]
> One of my client is experiencig with the same issue on PrestaShop 8.1.7.

I've installed PrestaShop 8.1.7 and I've done data migration from 1.7.2.0 and I don't have this issue anymore.

**Comment by samilmarekrygula** [comment]
Hi, I have this issue again on 8.1.7
