### ISSUE TITLE
Problem with the status of the clients

### ISSUE THREAD

**Issue by vegaconsultores** [PrestaShop/PrestaShop#36675]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello! 
When I tried to change the status of the clients when they realize a payment i get this error:
[ErrorException código 0]: Warning: Attempt to read property "id" on null
And also, I can't access or change the clients information and get this other error:
![Captura de pantalla 2024-08-06 084912](https://github.com/user-attachments/assets/5ab05fc5-81bf-4049-9bc5-ef064cdfd502)

I don't know if they are related or not with each other but i need help.

### Expected behavior

First, when i change the status of the clients i expected to o it. 
Second, i should be able to change the information of the cliente.

### Steps to reproduce

1. Go to orders
2. Try to change the order status
3. Get the error.

1. Go to a client name 
2. Try to change or edit the name
3. Get the error

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.1.29

### Your company or customer's name goes here (if applicable).

Moare Manualidades

**Comment by florine2623** [comment]
Hello @vegaconsultores ,

I followed your steps but I can't reproduce your issue.

https://github.com/user-attachments/assets/80c91627-b412-4ffa-a38e-0abfc1c9176d

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by vegaconsultores** [comment]
Hello, 

I add a video so you can see the issue I have.

https://github.com/user-attachments/assets/c26870e8-d257-4972-bc04-b3335245084d

Thank you for your help.
