### ISSUE TITLE
[ps_imageslider] Missing url hide slide in FO&BO and add in DB

### ISSUE THREAD

**Issue by Triloworld** [PrestaShop/PrestaShop#36671]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

This place in file check URL by default in template where isn't show up:
[/modules/ps_imageslider/views/templates/hook/slider.tpl](https://github.com/PrestaShop/ps_imageslider/blob/8f62edaeeb5084eac82343485ab343da057749b4/views/templates/hook/slider.tpl#L25)
> {if !empty($slide.url)}<a href="{$slide.url}">{/if}

This is where URL in backend isn't checked before loaded to array:
https://github.com/PrestaShop/ps_imageslider/blob/8f62edaeeb5084eac82343485ab343da057749b4/ps_imageslider.php#L551-L573

This place add slide even if URL is ommited:
https://github.com/PrestaShop/ps_imageslider/blob/8f62edaeeb5084eac82343485ab343da057749b4/ps_imageslider.php#L832-L883

### Expected behavior

No DB entry, not allowing saving slide if URL is empty OR don't check for url in template

### Steps to reproduce

1. Working shop, two different languages and no multistore mode enabled
2. Create slides in two different languages. Be sure it working correctly
3. Create another slide in steps:
- in default language add url and image
- set as "enabled"
- don't add any data (url, title etc) in second language
- save
4. Check visibility of slide in backend (it won't show up)
5. Check frontend - It won't show up
6. Check Database - there is

We use solution for different size in different browsers by dividing and this issue show up

### PrestaShop version(s) where the bug happened

1.7.7.2 - latest

### PHP version(s) where the bug happened

7.3.27-9+0~20210227.82+debian10~1.gbpa4a3d6

### If your bug is related to a module, specify its name and its version

ps_imageslider - latest

### Your company or customer's name goes here (if applicable).

Webo.agency

**Comment by Triloworld** [comment]
Field URL isn't "require" and thus issue: 
<img width="975" alt="Zrzut ekranu 2024-08-5 o 13 51 27" src="https://github.com/user-attachments/assets/56a50b04-fc1e-4e5a-a48b-b0951a19c685">

**Comment by florine2623** [comment]
Hello @Triloworld ,

I have reproduced your issue.

https://github.com/user-attachments/assets/918358af-edd8-431d-a6b7-52db1b76d6b4




I think it the same as : https://github.com/PrestaShop/PrestaShop/issues/33527

Could you confirm ?

**Comment by Triloworld** [comment]
Yes. Sorry for not finding it out. But yeah - this one tested for latest module version.

**Comment by florine2623** [comment]
Hello @Triloworld ,

Closing this issue as it is a duplicate ^^
Let's follow its progress directly on the original issue. Thanks for your PR, it will be reviewed by dev.

Thanks!
