### ISSUE TITLE
Problem with the orders status

### ISSUE THREAD

**Issue by vegaconsultores** [PrestaShop/PrestaShop#36678]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello!
When I tried to change the status of the clients when they realize a payment, I get this error:

[ErrorException código 0]: Warning: Attempt to read property "id" on null

https://github.com/user-attachments/assets/55c222fc-b996-4b4e-814f-a78a9110037f

I don't know where the error is and how to solve it, maybe it's a problem with a module or a bug from Prestashop 8.1.5.

### Expected behavior

I should be able to change the status of the orders.

### Steps to reproduce

1. Go to orders.
2. Try to change the order status.
3. Get an error.
![Captura de pantalla 2024-08-06 111206](https://github.com/user-attachments/assets/ac55f3fb-831b-4d83-b925-69b171d0e00d)

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.1.29

### If your bug is related to a module, specify its name and its version

Prestashop 8.1.5

### Your company or customer's name goes here (if applicable).

Moare Manualidades

**Comment by Hlavtox** [comment]
Already solved in https://github.com/PrestaShop/PrestaShop/pull/35698. Update to 8.1.7 to benefit from this fix, or apply the fix manually using the changes here - https://github.com/PrestaShop/PrestaShop/pull/35698/files.

This error is happening because your order has an invalid empty status.
