### ISSUE TITLE
Google mail less secure app

### ISSUE THREAD

**Issue by simulbeni** [PrestaShop/PrestaShop#36674]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Google will remove password based logins from 30th SEPT. We are using google mail for all our clients. is there any update in pipeline to use API based logins?

[https://support.google.com/accounts/answer/6010255?hl=en](https://support.google.com/accounts/answer/6010255?hl=en)

### Expected behavior

There must be some option or module to use google mail

### Steps to reproduce

Advanced Parameters -> Emails

### PrestaShop version(s) where the bug happened

8.17

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

Simul Digital

**Comment by florine2623** [comment]
ping @PrestaShop/tech-council and @PrestaShop/product-council ,

WDYT about that ?

**Comment by simulbeni** [comment]
@florine2623 We found solution ourself. We can generate different password and use it on the place of google account password.

[https://www.gmass.co/blog/gmail-smtp/](https://www.gmass.co/blog/gmail-smtp/)
