### ISSUE TITLE
Category export file is empty

### ISSUE THREAD

**Issue by luger95** [PrestaShop/PrestaShop#36680]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Lors de l'utilisation de la fonciton d'export des catégories, le fichier est vide

### Steps to reproduce

Use the export button on the page listing the categories

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

7.4

### Your company or customer's name goes here (if applicable).

LEXPROD SAS

**Comment by florine2623** [comment]
Hello @luger95 ,

I can't reproduce your issue :

https://github.com/user-attachments/assets/699949ef-61c3-4c68-bca8-b477ff9f487c

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
