### ISSUE TITLE
Customer Service email image issues

### ISSUE THREAD

**Issue by Noumie** [PrestaShop/PrestaShop#36682]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I am having some issues with the customer service emails images in PrestaShop 8.1.2.

Some attached images can't be open because they have special characters as '?' ou ')'. in their name. 
When clicked, the attachment url changes and lead to a 404 error page.

Maybe some Prestashop rules that changes special charcaters in urls on others charcaters to prevent security issues.
Attachment's name goes from **66a3bf2043970?.jpg** to **66a3bf2043970%3F.jpg**.

### Expected behavior

Prevent special caharcters in images names so that they can all be opened.

### Steps to reproduce

1 - Go to Customer Sevices > Customer Services
![image](https://github.com/user-attachments/assets/1b92e142-cd25-400c-812d-cbbb5d1354c0)

2 - Open a customer Issue then click on the attached image. If its name contains a special character it will lead to a 404 error page.
![image thumb png 7c875c83e97e558f1361e1825fcab170](https://github.com/user-attachments/assets/0fce90b5-0205-49d5-8098-58877d7d03a9)

The attachment's url in the BO :  
monsite/index.php?controller=AdminCustomerThreads&id_customer_thread=1012&viewcustomer_thread=&filename=**66a3bf2043970?.jpg**&show=1&token=55d2276b4158a897ec891a52ef21b716
![image thumb png 7765133cf9061302cf5f043385fc6507](https://github.com/user-attachments/assets/d064ef0e-9e37-4598-8ca6-348879a63a25)

But the url changes after click and the page is loading :
monsitemonsite /index.php?controller=AdminCustomerThreads&id_customer_thread=1012&viewcustomer_thread=&filename=**66a3bf2043970%3F.jpg**&show=1&token=55d2276b4158a897ec891a52ef21b716 
![image thumb png a7bc28c2060bd92d4c2c199fd113ee34](https://github.com/user-attachments/assets/1148427c-62ae-44a1-accc-ec2f88dc4f87)

You can see that the url as changed from 66a3bf2043970?.jpg to 66a3bf2043970%3F.jpg
On the FTP the image's name is 66a3bf2043970?.jpg as seen in the BO.

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

7.2

**Comment by florine2623** [comment]
Hello @Noumie ,

I have the same behavior as you do. 
In contact form, if the file sent by a customer contains a special character in its name, the file name seen in the FTP or the download URL will be extracted.

Let's ping @PrestaShop/tech-council and @PrestaShop/product-council ,
Could you specify the wanted behavior, please ?

**Comment by Noumie** [comment]
Hello @florine2623 ,

The attachment 's name 66a3bf2043970?.jpg seems not to be the original name. 
I have uploaded **blank_pdf.pdf** but his name in the BO is **669a752ef1248k.pdf**
![image](https://github.com/user-attachments/assets/d2c6e429-4afa-45fd-9172-c69a9fd81a83)

monsite/index.php?controller=AdminCustomerThreads&id_customer_thread=937&viewcustomer_thread=&filename=**669a752ef1248k.pdf**&show=1&token=55d2276b4158a897ec891a52ef21b716

Either way, it seems that Presatashop is renaming the attachments with, sometimes, special characters.

The wanted behavior :

To not let Prestashop rename attachments and make sure that there is no special charcter in it.

**Comment by Hlavtox** [comment]
Encoding the file name for the URL is correct behavior.

**66a3bf2043970?.jpg** cannot be in the URL, because it contains a question mark, which must be used ONLY to separate the query string. 

`/index.php?controller=AdminCustomerThreads&id_customer_thread=1012&viewcustomer_thread=&filename=66a3bf2043970%3F.jpg&show=1&token=55d2276b4158a897ec891a52ef21b716`

must serve **66a3bf2043970?.jpg**.

**Comment by florine2623** [comment]
Hello,

The renaming of uploaded files should not contains special characters, only letters and numbers.

I can't reproduce the issue.

I'm closing the issue. If you find some steps to reproduce the issue, you can reopen it.
