### ISSUE TITLE
Bug regarding backoffice marketplace and prestashop addons marketplace

### ISSUE THREAD

**Issue by Kullcord** [PrestaShop/PrestaShop#36691]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I am trying to install some addons for my Prestashop website. When I go to modules>marketplace, I get an error saying that This page can't be loaded, please reload" screen that only asks me to reload the page. Once I reloaded, I am told that the "prestashop marketplace for backoffice"  is not working and that I need to uninstall it from module>module manager, and then install the new version from the Prestashop Addons Marketplace. I did this, so I uninstalled the "Prestashop marketplace for backoffice", and I went to the Prestashop Addons Marketplace to install the module. When I arrive here, I am told that I need to sign in to install an addon. When I press the sign in button, I am taken to the "create an account" page, instead of the log in page, and I am unnable to log in, and install the module. So right now, whatever module I need for my website, I am unable to get it because of these two bugs. I am going to attach some images regarding the backoffice problem I have, but the text is in Romanian.
![image](https://github.com/user-attachments/assets/bfb797b7-0a58-45c2-af2c-afa66e094fc9)
![image](https://github.com/user-attachments/assets/61850166-d691-44d5-830a-7b54d542d0fb)
![image](https://github.com/user-attachments/assets/58e68fc7-2683-4b1e-92fb-b23936ccd29f)
![image](https://github.com/user-attachments/assets/e8e08577-3842-4d34-beb9-5d5fb357288a)

### Expected behavior

I expect to be able to, first of all, install the prestashop marketplace for your backoffice module so I can get any addon I want, and in order to do this, I expect to be able to be redirected to the log in page when I press on the log in button on prestashop addons marketplace.

### Steps to reproduce

1. Go to module>marketplace
2. Press reload
3. Go to Prestashop Addons Marketplace
4. Press on log in button

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1.25

### If your bug is related to a module, specify its name and its version

Prestashop Marketplace for your Backoffice - v4.11.4

### Your company or customer's name goes here (if applicable).

Future Energy Group SRL

**Comment by intraordinaire** [comment]
Hi @Kullcord,

Can you migrate/duplicate this issue to [ps_mbo](https://github.com/PrestaShopCorp/ps_mbo) please ?

This bug is related to the PS MBO module, so it will be the correct place to discuss about it :)

Thanks !

**Comment by paulnoelcholot** [comment]
Hello @Kullcord,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
