### ISSUE TITLE
Problems with installation new theme

### ISSUE THREAD

**Issue by mriberavlt** [PrestaShop/PrestaShop#36694]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

With the new theme I can't install it because when I upload it and choose it I get this message:
The productcomments module cannot be installed. Unfortunately, the module has not returned additional details.

### Expected behavior

Able to install the new theme

### Steps to reproduce

Modules > Theme

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

7.4

**Comment by paulnoelcholot** [comment]
Hello @mriberavlt,

I tested your issue on ps 8.1.6 and I can't reproduce as you can see : https://www.loom.com/share/7b1341316e15445f81d83230fdcf5964?sid=57b9b0db-293f-479f-aa48-a2de3af96ab2

Did I miss something?

Thanks in advance

**Comment by mriberavlt** [comment]
HI, but I have a new theme, and it's available in Prestshop 8*!!!


Salut!

Marc


Missatge de Paul-Noël ***@***.***> del dia dl., 19 d’ag. 2024
a les 9:22:

**Comment by ShaiMagal** [comment]
@mriberavlt 
Tested, no problems, PS 1.7.8.11 + PS 8.1.7.

It's theme problem, not PrestaShop, contact theme developer.

**Comment by paulnoelcholot** [comment]
Hello @mriberavlt,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you
