### ISSUE TITLE
 ps_emailalerts v3.0.0 stopped working 

### ISSUE THREAD

**Issue by Mach-8** [PrestaShop/PrestaShop#36692]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi everyone. Help please with the appeared problem!

Mail alerts v3.0.0 modul stopped working on PS 8.1.7. I understand that nothing happens by itself. But I haven't done anything to disrupt its operation. I just wanted to change my e-mail. After that, it stopped sending emails at all.

There's a connection to the database, emails are changing. Module reset does nothing: previously entered emails remain, notifications do not come anyway

Advanced Parameters>E-mail * Send a test email to - it's working, the emails are coming in. I made a test order and received all the emails too 

I checked for spam detection. I had previously added a second email from gmail everywhere. And nothing!

https://prnt.sc/eOojmt7xKvkx

Previously I used my own SMTP settings. But with or without these settings I receive test e-mail: https://prnt.sc/f1RKM-kUYmLS

### Steps to reproduce

Nothing to reproduce

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.1.29 

### If your bug is related to a module, specify its name and its version

 ps_emailalerts v3.0.0

**Comment by ShaiMagal** [comment]
Do you see mail sucesfully logged in PS mail log?
Advanced Parameters - Emails

Do you have "pl" translation folder in "mails" folder in module ps_emailalerts? (I guess your eshop language is PL)

**Comment by Mach-8** [comment]
"Do you see mail sucesfully logged in PS mail log?
Advanced Parameters - Emails"

Yes, from everyone registered.

"Do you have "pl" translation folder in "mails" folder in module ps_emailalerts? (I guess your eshop language is PL)"

No, it's absent! 
https://prnt.sc/SmvUy0e8Bp6z

**Comment by ShaiMagal** [comment]
@Mach-8 I mean folder "mails" in module "ps_emailalerts" folder, not "translations".

**Comment by Nasjo0328** [comment]
> ### Prerrequisitos
> * [x] Entiendo y acepto el [código de conducta](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md) del proyecto .
> * [x] Ya he [buscado problemas existentes](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) y no encontré ningún informe previo de este error.
> 
> ### Describe el error y agrega archivos adjuntos.
> Hola a todos. ¡Ayuda con el problema que me ha surgido!
> 
> El módulo de alertas de correo v3.0.0 dejó de funcionar en PS 8.1.7. Entiendo que no sucede nada por sí solo, pero no hice nada para interrumpir su funcionamiento. Solo quería cambiar mi correo electrónico. Después de eso, dejó de enviar correos electrónicos.
> 
> Hay una conexión a la base de datos, los correos electrónicos están cambiando. El restablecimiento del módulo no hace nada: los correos electrónicos ingresados ​​anteriormente permanecen, las notificaciones no llegan de todos modos
> 
> Parámetros avanzados > Correo electrónico * Enviar un correo electrónico de prueba a: funciona, los correos electrónicos están llegando. Hice un pedido de prueba y también recibí todos los correos electrónicos.
> 
> Revisé la detección de spam. Anteriormente había agregado un segundo correo electrónico de Gmail a todas partes. ¡Y nada!
> 
> https://prnt.sc/eOojmt7xKvkx
> 
> Anteriormente, utilizaba mi propia configuración SMTP. Pero, con o sin esta configuración, recibo un correo electrónico de prueba: https://prnt.sc/f1RKM-kUYmLS
> 
> ### Comportamiento esperado
> _Sin respuesta_
> 
> ### Pasos para reproducir
> Nada que reproducir
> 
> ### Versiones de PrestaShop donde ocurrió el error
> 8.1.7
> 
> ### Versiones de PHP donde ocurrió el error
> 8.1.29
> 
> ### Si su error está relacionado con un módulo, especifique su nombre y su versión
> Alertas de correo electrónico ps_v3.0.0
> 
> ### El nombre de su empresa o cliente va aquí (si corresponde).
> _Sin respuesta_

I confirm, I have tested with PrestaShop 8.1.7 and this module does not work.

**Comment by kpodemski** [comment]
Hello @Mach-8 

Please test the following:

1. Check if you have directory /modules/ps_emailalerts/mails/pl/ available.
2. If you have emails inside the logs inside `Advanced Parameters - Emails`, it means they were sent and the problem may be with your email server, not with the module itself. 

Unfortunately, I couldn't reproduce any errors with this module, it works as expected apart from some other already reported problems.

**Comment by Nasjo0328** [comment]
Hello @kpodemski 
In my case, I have validated what you mentioned, and everything is in order. The email log and advanced functions are working correctly and sending messages. However, the emails related to the mentioned module are not being sent (see attached screenshot).

![capture](https://github.com/user-attachments/assets/6a2b374a-4cd5-446b-91e5-3109e157427c)

Best regards

**Comment by kpodemski** [comment]
@Nasjo0328 

in your case emails should be inside "es" directory, because you have Spanish language, is that correct?

**Comment by Nasjo0328** [comment]
@kpodemski 
That's correct, I also have the files inside the es - en folders respectively.
PrestaShop 8.1.7
Version PHP: 8.1.29
Module v3.0.0 
Theme: Warehouse.
Capture attached
![capture-2](https://github.com/user-attachments/assets/56bb1931-8971-470f-b01a-d9e6c3c760b9)

Thanks for replying, Best regards!

**Comment by Mach-8** [comment]
I'm so sorry I've been away for so long.

Hello @ShaiMagal  
All I have in /modules/ps_emailalerts/mails/   - only EN folder 
https://prnt.sc/tQb6Y_NhIHJE

Hello @kpodemski 
> Check if you have directory /modules/ps_emailalerts/mails/pl/ available.

As I said above, there is only  EN folder 

> If you have emails inside the logs inside Advanced Parameters - Emails, it means they were sent and the problem may be with your email server, not with the module itself.

There are no logs. Save email logs is enabled

As I understand it, the problem is the absence of the PL folder?

**Comment by Mach-8** [comment]
Solved. 

 International / Translations, after Add / Update a language. All the missing folders appear

**Comment by Nasjo0328** [comment]
@Mach-8 Thank you very much, I have checked it and the solution has worked for me.
Best regards!
