### ISSUE TITLE
1-ClickUpgrade 1.7.8.11 to 8.1.7

### ISSUE THREAD

**Issue by michaelgawlik** [PrestaShop/PrestaShop#36700]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Dear Prestashop Folks,

I tried to update from 1.7.8.11 to the latest 8 version via 1-Click Upgrade.

What I have done so far:
- removed every thirdparty addon
- updated every other addon
- disabled cache
- removed cache (var/cache/...)
- switched to standard-theme
- the 1-Click Upgrade Module ist on it's latest version. (6.0)

So when I tried to run the update, it crashes after cleaning file cache with the following error:

```
Cleaning file cache
[SKIP] directory "/app/cache/" does not exist and cannot be emptied.
[CLEANING CACHE] File CACHEDIR.TAG removed
[CLEANING CACHE] File prod removed
Running opcache_reset
[INTERNAL] /home/.../vendor/prestashop/autoload/src/LegacyClassLoader.php line 175 - include(/home/.../var/cache/prod/class_index.php) [function.include.php]: failed to open stream: No such file or directory
[INTERNAL] /home/.../vendor/prestashop/autoload/src/LegacyClassLoader.php line 175 - include() [function.include.php]: Failed opening '/home/.../var/cache/prod/class_index.php' for inclusion (include_path='/home/.../vendor/pear/pear_exception:/home/.../vendor/pear/console_getopt:/home/.../vendor/pear/pear-core-minimal/src:/home/.../vendor/pear/archive_tar:.:/usr/local/share/pear')
```

So it clears the cache folder and then it want's to include the file class_index.php from there?

I don't understand that.

Does someone knows this behavior?

Thanks for your thoughts and help.

Cheers,
Michael

### Steps to reproduce

Followed the instructions on: https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/use-autoupgrade-module/

Status before upgrade:
<img width="830" alt="status_before_ugrade" src="https://github.com/user-attachments/assets/0d57e73c-dfd4-43da-b607-05ca49c781bb">

Expert-Mode-Infos:
<img width="814" alt="expert_mode" src="https://github.com/user-attachments/assets/cb8585a3-6798-484c-a0d4-b2cbf24e8883">

All Upgrade-Options are on 'yes' (green).

After all files are upgraded:
```
99 files left to upgrade.
All files upgraded. Now upgrading database...
```

```
All files upgraded. Now upgrading database...
=== Step upgradeDb
Cleaning file cache
[SKIP] directory "/app/cache/" does not exist and cannot be emptied.
[CLEANING CACHE] File CACHEDIR.TAG removed
[CLEANING CACHE] File prod removed
Running opcache_reset
[INTERNAL] /home/.../vendor/prestashop/autoload/src/LegacyClassLoader.php line 175 - include(/home/.../var/cache/prod/class_index.php) [function.include.php]: failed to open stream: No such file or directory
[INTERNAL] /home/.../vendor/prestashop/autoload/src/LegacyClassLoader.php line 175 - include() [function.include.php]: Failed opening '/home/.../var/cache/prod/class_index.php' for inclusion (include_path='/home/.../vendor/pear/pear_exception:/home/.../vendor/pear/console_getopt:/home/.../vendor/pear/pear-core-minimal/src:/home/.../vendor/pear/archive_tar:.:/usr/local/share/pear')
```

Error:
`[INTERNAL] /home/.../vendor/prestashop/autoload/src/LegacyClassLoader.php line 175 - TypeError: Return value of PrestaShop\Autoload\LegacyClassLoader::loadClassCache() must be of the type array, bool returned #0 /home/.../vendor/prestashop/autoload/src/PrestashopAutoload.php(36): PrestaShop\Autoload\LegacyClassLoader->loadClassCache() #1 /home/.../vendor/prestashop/autoload/src/Autoloader.php(77): PrestaShop\Autoload\PrestashopAutoload->PrestaShop\Autoload\{closure}() #2 [internal function]: PrestaShop\Autoload\Autoloader->load('Tools') #3 /home/.../config/config.inc.php(83): spl_autoload_call('Tools') #4 /home/.../modules/autoupgrade/classes/UpgradeContainer.php(645): require_once('/home/beamerla/...') #5 /home/.../modules/autoupgrade/classes/Task/AbstractTask.php(165): PrestaShop\Module\AutoUpgrade\UpgradeContainer->initPrestaShopCore() #6 /home/.../modules/autoupgrade/classes/Task/Upgrade/UpgradeDb.php(86): PrestaShop\Module\AutoUpgrade\Task\AbstractTask->init() #7 /home/.../modules/autoupgrade/classes/Task/Runner/ChainedTasks.php(59): PrestaShop\Module\AutoUpgrade\Task\Upgrade\UpgradeDb->init() #8 /home/.../***admin***/autoupgrade/ajax-upgradetab.php(54): PrestaShop\Module\AutoUpgrade\Task\Runner\ChainedTasks->run() #9 {main}`

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

7.4

**Comment by michaelgawlik** [comment]
disabling opcache solved this problem - thanks to: https://www.comonsoft.com (https://www.prestashop.com/forums/topic/1089602-update-17811-to-8x/#comment-3493934 -  could have figured it out myself)

disabled opcache.

**Comment by michaelgawlik** [comment]
that solved this particular problem.

**Comment by michaelgawlik** [comment]
don't wanna close this - mention it.

**Comment by Quetzacoalt91** [comment]
Running `opcache_cache` during the last call to UpgradeFiles may help.

**Comment by AureRita** [comment]
Hello @michaelgawlik 

Was the information provided by @Quetzacoalt91  useful ?

Waiting for feedback

**Comment by gericfo** [comment]
Hello @michaelgawlik  
Without any answer from you, we will close this ticket. 
Please feel free to reopen an issue if necessary.
Thank you
