### ISSUE TITLE
Error while upgrading from 1.7.3.1 to 1.7.8.11

### ISSUE THREAD

**Issue by acidlavaa** [PrestaShop/PrestaShop#36707]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When trying to upgrade from 1.7.3.1 to 1.7.8.11 with One Click Upgrade (PHP 7.1), I got the following issues as soon as the database upgrade begin :

```
[INTERNAL] /home/bfuymqx/www/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php line 168 - Symfony\Component\Config\Exception\FileLoaderLoadException: Expected to find class "PrestaShopBundle\Controller\index" in file "/home/bfuymqx/www/src/PrestaShopBundle/Controller/index.php" while importing services from resource "/home/bfuymqx/www/app/../src/PrestaShopBundle/Controller/*", but it was not found! Check the namespace prefix used with the resource in /home/bfuymqx/www/app/config/config.yml (which is being imported from "/home/bfuymqx/www/app/config/config_prod.yml"). 
#0 /home/bfuymqx/www/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(90): Symfony\Component\Config\Loader\FileLoader->doImport('/home/bfuymqx/w...', NULL, false, '/home/bfuymqx/w...') 
#1 /home/bfuymqx/www/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(195): Symfony\Component\Config\Loader\FileLoader->import('config.yml', NULL, false, '/home/bfuymqx/w...') 
#2 /home/bfuymqx/www/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(127): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseImports(Array, '/home/bfuymqx/w...') 
#3 /home/bfuymqx/www/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/DelegatingLoader.php(40): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('/home/bfuymqx/w...', NULL) 
#4 /home/bfuymqx/www/app/AppKernel.php(150): Symfony\Component\Config\Loader\DelegatingLoader->load('/home/bfuymqx/w...') 
#5 /home/bfuymqx/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(776): AppKernel->registerContainerConfiguration(Object(Symfony\Component\Config\Loader\DelegatingLoader)) 
#6 /home/bfuymqx/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(642): Symfony\Component\HttpKernel\Kernel->buildContainer() 
#7 /home/bfuymqx/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer() 
#8 /home/bfuymqx/www/modules/autoupgrade/classes/UpgradeTools/SymfonyAdapter.php(67): Symfony\Component\HttpKernel\Kernel->boot() 
#9 /home/bfuymqx/www/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(43): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->initKernel() 
#10 /home/bfuymqx/www/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(102): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->initConstants() 
#11 /home/bfuymqx/www/modules/autoupgrade/classes/Task/Upgrade/UpgradeDb.php(45): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() 
#12 /home/bfuymqx/www/modules/autoupgrade/classes/Task/Runner/ChainedTasks.php(61): PrestaShop\Module\AutoUpgrade\Task\Upgrade\UpgradeDb->run() 
#13 /home/bfuymqx/www/****/autoupgrade/ajax-upgradetab.php(54): PrestaShop\Module\AutoUpgrade\Task\Runner\ChainedTasks->run() 
#14 {main}
```

### Expected behavior

Expected to run the upgrade smoothly.

### Steps to reproduce

Go to Click Upgrade
Upgrade

### PrestaShop version(s) where the bug happened

1.7.3.1

### PHP version(s) where the bug happened

7.1

**Comment by Misty-94** [comment]
Hi acidlavaa, have you tried with php opcache disabled ?

**Comment by acidlavaa** [comment]
> Hi acidlavaa, have you tried with php opcache disabled ?

I can't disable it with OVH.

**Comment by Misty-94** [comment]
You can try with opcache.revalidate_freq set to 0 in your .htaccess file

php_value opcache.revalidate_freq 0

**Comment by Misty-94** [comment]
To disable opcache this one should work in .htaccess file : php_flag opcache.enable Off

**Comment by acidlavaa** [comment]
Hello,

when I apply php_flag opcache.enable Off in .htaccess, the site become unavailable : 

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at postmaster@contact.com to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Thanks.

**Comment by Misty-94** [comment]
Hi, try the other one that I use so I know it works :
php_value opcache.revalidate_freq 0

What version of module 1-clic upgrade do you use ?

**Comment by acidlavaa** [comment]
With php_value opcache.revalidate_freq 0 I got an Server Internal Error.

I use Click Upgrade v6.0.0

**Comment by Misty-94** [comment]
Maybe you can try the previous version v5.0.3 : https://github.com/PrestaShop/autoupgrade/releases

**Comment by acidlavaa** [comment]
I tried, same erreor during the upgrade. Also I noted that those are the last activities before the error : 

[SKIP] directory "/app/cache/" does not exist and cannot be emptied.
Cleaning file cache
[INTERNAL] /home/bfuymqx/www/modules/autoupgrade/classes/UpgradeContainer.php line 640 - Zend OPcache API is restricted by "restrict_api" configuration directive
Running opcache_reset

So I guess it could be related to opcache but your inputs don't work.

**Comment by Misty-94** [comment]
Yes same problem as https://github.com/PrestaShop/PrestaShop/issues/36700 reported some days ago.
Unfortunately with OVH shared hosting I think the best solution for you is to do the upgrade on your local development machine and then upload the result.

**Comment by acidlavaa** [comment]
Hello,

So I tried to migrate the website on another server and now I have the following error in Click Upgrade :

Version non modifiée de PrestaShop:
 Error: Unable to check md5 files
 
 It doesn't allow me to launch the upgrade... I tried to chmod the Click Upgrade files without sucess and tried almost everything. I don't understand, files and database are the same as on OVH... Feeling desperate about this upgrade.

**Comment by Quetzacoalt91** [comment]
> Version non modifiée de PrestaShop:
Error: Unable to check md5 files

There is an issue happening on the ajax requests checking the altered files on your shop. Checking the response of these requests or the server logs should provide more information.

Can you share the configuration of your initial environment about opcache? We can try to reproduce on our end and see if it impacts the update experience generally.

**Comment by paulnoelcholot** [comment]
Hello @acidlavaa,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
