### ISSUE TITLE
Finland default VAT changes from 24% -> 25.5% on 1.9.2024

### ISSUE THREAD

**Issue by tswfi** [PrestaShop/PrestaShop#36712]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The Finnish government has decided to up VAT from 24% to 25.5% on 1.9.2024. The default values in PrestaShop should reflect this change.

### Expected behavior

On new installation fetching the Finnish localization pack installs the correct VAT percent (25.5%) for general goods.

### Steps to reproduce

1. Install prestashop
2. Load Finnish localization pack
3. Check that finland general goods tax rate is 25.5%

### PrestaShop version(s) where the bug happened

-

### PHP version(s) where the bug happened

-

### If your bug is related to a module, specify its name and its version

-

**Comment by tswfi** [comment]
Official tax office announcement: https://www.vero.fi/en/businesses-and-corporations/taxes-and-charges/vat/rates-of-vat/new-vat-rate-from-1-september-2024--instructions-for-vat-reporting/

**Comment by paulnoelcholot** [comment]
FYI @PrestaShop/product-council

**Comment by ShaiMagal** [comment]
People loves rising tax :))) (irony)

Anyway, thank you for issue/PR and informing us!
