### ISSUE TITLE
Unzip wizard GIF animation too heavy

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#36711]
Following this [blog post](https://build.prestashop-project.org/news/2023/new-project-branding/), the prestashop project moves on.

This change was be implemented by 3 PRs:
1. https://github.com/PrestaShop/prestashop-ui-kit/pull/229
2. https://github.com/PrestaShop/PrestaShop/pull/36584
3. https://github.com/PrestaShop/PrestaShop/pull/36585

See https://github.com/PrestaShop/PrestaShop/issues/36615

In PR https://github.com/PrestaShop/PrestaShop/pull/36585 the image used is very big, which makes the downloadable Zip very big. The image used must be optimized.

**Comment by Hlavtox** [comment]
@tblivet 

The GIF can be compressed a lot - https://github.com/PrestaShop/PrestaShop/pull/36585#discussion_r1699718129.

Or you can make it simple like this - https://jsfiddle.net/n8wcgbad/

**Comment by tblivet** [comment]
Hi @Hlavtox, PrestaShop brand sent me this new GIF. It's way better in terms of weight. I think we can go with it?
PR: https://github.com/PrestaShop/PrestaShop/pull/36725

**Comment by Hlavtox** [comment]
@tblivet Yep much better. Can you ask them to remove the blue background? We could then reduce the color palette and do the background via css. :-)

**Comment by matks** [comment]
I merged https://github.com/PrestaShop/PrestaShop/pull/36725 but 

> Can you ask them to remove the blue background? We could then reduce the color palette and do the background via css. :-)

Can be done as an improvement
