### ISSUE TITLE
Document the changes introduced by the v9 new branding

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#36710]
Following this [blog post](https://build.prestashop-project.org/news/2023/new-project-branding/), the prestashop project moves on.

This change was be implemented by 3 PRs:
1. https://github.com/PrestaShop/prestashop-ui-kit/pull/229
2. https://github.com/PrestaShop/PrestaShop/pull/36584
3. https://github.com/PrestaShop/PrestaShop/pull/36585

See https://github.com/PrestaShop/PrestaShop/issues/36615

These PRs did introduce changes in the frontend code of PrestaShop, changes that might impact how module developers build modules for PrestaShop v9. They need to be documented.

**Comment by jolelievre** [comment]
Handled in https://github.com/PrestaShop/docs/pull/1856
