### ISSUE TITLE
Prestashop 8.1.7 Webservice issue whit LiteSpeed Cache for Prestashop module

### ISSUE THREAD

**Issue by Deltafox79** [PrestaShop/PrestaShop#36719]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After Enable Prestashop 8.1.7 webservices and create a key on first test I have this issue :

https://MY-KEY....@......com/api/

```
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<errors>
<error>
<code>
<![CDATA[ 15 ]]>
</code>
<message>
<![CDATA[ [PHP Unknown error #8192] Return type of LiteSpeedCacheEsiModConf::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice (/home/..../public_html/modules/litespeedcache/classes/EsiModConf.php, line 146) ]]>
</message>
</error>
<error>
<code>
<![CDATA[ 15 ]]>
</code>
<message>
<![CDATA[ [PHP Unknown error #8192] preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated (/home/...../public_html/modules/litespeedcache/classes/EsiModConf.php, line 250) ]]>
</message>
</error>
</errors>
</prestashop>
```

### Expected behavior

```
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <api shopName="Prestashop">
        <addresses xlink:href="http://....com/api/addresses" get="true" put="true" post="true" patch="true" delete="true" head="true">
            <description xlink:href="http://....com/api/addresses" get="true" put="true" post="true" patch="true" delete="true" head="true">
            The Customer, Brand and Customer addresses</description>
            <schema xlink:href="http://....com/api/addresses?schema=blank" type="blank"/>
            <schema xlink:href="http://....com/api/addresses?schema=synopsis" type="synopsis"/>
        </addresses>
    </api>
</prestashop>
```

### Steps to reproduce

Just go on https://MY-KEY....@......com/api/ whit LiteSpeed Cache for Prestashop enabled

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.1.29

### If your bug is related to a module, specify its name and its version

LiteSpeed Cache for Prestashop 1.4.1

**Comment by jlores** [comment]
https://github.com/litespeedtech/lscache_prestashop/issues

**Comment by Deltafox79** [comment]
https://github.com/litespeedtech/lscache_prestashop/issues/67

**Comment by jlores** [comment]
Hello,

They won't reply very quickly, if at all, Litespeed doesn't put much work into Prestashop.

From experience, PHP7.4 fails much less.

**Comment by Hlavtox** [comment]
Hi, this is not related to Prestashop software, issue must be resolved with authors of the module.
