### ISSUE TITLE
Problem on pack products on prestashop 8.1.5

### ISSUE THREAD

**Issue by PetryV** [PrestaShop/PrestaShop#36728]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have a problem when creating packages, it only finds the products that are in combination! and only with those I can create packages!Has anyone else encountered this problem? Thank you

### Steps to reproduce

1.BO
2.Catalog-Products-New product-pack of products-
3.On Search combination is emty if i put a products standars!

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

Petri

**Comment by kpodemski** [comment]
I can't reproduce this error on PrestaShop 8.1.7.

**Comment by ingridusta** [comment]
Hello @PetryV,

Hello,

Despite our efforts, we were not able to reproduce your issue with the provided information with Prestashop v9.0.x.

![Capture d’écran 2024-09-10 à 12 47 49](https://github.com/user-attachments/assets/313fc62c-6c8b-4004-92e5-b23d57fe192b)
![Capture d’écran 2024-09-10 à 12 49 19](https://github.com/user-attachments/assets/d3a5ea88-66ec-439a-9e3e-d6023912c2bc)
![Capture d’écran 2024-09-10 à 12 49 42](https://github.com/user-attachments/assets/f4c5e538-015e-4adc-9857-bf4225c1a9a8)

As you can see on the screenshots, when I am creating a new pack of products, standard products are found and displayed as I search for products to be added in the pack. 

Let's wait up to 20 days if there will be another contributor who encounter the same issue and can provide new informations to help us reproducing the issue.

Thank you!
