### ISSUE TITLE
Hook actionPDFInvoiceRender is missing from installation

### ISSUE THREAD

**Issue by laurain-adipso** [PrestaShop/PrestaShop#36741]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hook 'actionPDFInvoiceRender' is missing from the database in fresh PS installs.
It is, however, referenced multiple times in the core :
classes\order\OrderHistory.php
classes\PaymentModule.php
controllers\admin\AdminPdfController.php
controllers\front\PdfInvoiceController.php
src\Adapter\PDF\InvoicePdfGenerator.php
src\Adapter\PDF\OrderInvoicePdfGenerator.php

### Expected behavior

The hook should be installed in the ps_hook table so that modules can properly be attached to it.

### Steps to reproduce

1. Install a new instance of Prestashop
2. Search for actionPDFInvoiceRender in the ps_hook table

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.1.29

### Your company or customer's name goes here (if applicable).

Adipso

**Comment by kpodemski** [comment]
I confirm this issue.
