### ISSUE TITLE
Problem with Products

### ISSUE THREAD

**Issue by vegaconsultores** [PrestaShop/PrestaShop#36751]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, 

I have a problem with my Prestashop products. Every time a customer abroad (I ship from Spain) buys more than 14 products, he gets free shipping and I have configured the shipping cost. 

I don't know where the problem is or if the problem is that the shipping for more than 14 products is configured for free in some way and I can't remove it.

### Expected behavior

The clients must pay the shipping cost.

### Steps to reproduce

-

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.1.29

### Your company or customer's name goes here (if applicable).

Moare Manualidades

**Comment by ibahloul-ps** [comment]
Hello @vegaconsultores,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you & have a great day!
