### ISSUE TITLE
Statistiche

### ISSUE THREAD

**Issue by albertoart80** [PrestaShop/PrestaShop#36766]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Nel pannello di controllo del mio prestashop non riesco a visualizzare le statistiche.

https://prnt.sc/atjdSVvJhYQG

### Expected behavior

Tutti i report portano a zero,
anche se ricevo ordini, le statistiche non si aggiornano.

### Steps to reproduce

1.  Pannello di controllo 
2. visualizza statistiche

### PrestaShop version(s) where the bug happened

8.1.6

### PHP version(s) where the bug happened

PHP 8.0.30

### Your company or customer's name goes here (if applicable).

trade

**Comment by paulnoelcholot** [comment]
Hello,

Please send your request in English. English is the norm on GitHub.

Thank you
