### ISSUE TITLE
PrestaShop accounts (ps_accounts) module is not installed, please install it PS 8.1.7

### ISSUE THREAD

**Issue by msaustral** [PrestaShop/PrestaShop#36768]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On fresh installation of zip 8.1.7 and 8.1.6, during installation is showing 1: PrestaShop accounts (ps_accounts) module is not installed, please install it.

![image](https://github.com/user-attachments/assets/e1c7c4d3-c125-4039-8689-d01a392aeb1f)

### Expected behavior

Being able to install without errors

### Steps to reproduce

Download the zip from https://prestashop.es/versions/

Try to install it, get the error during installation

![image](https://github.com/user-attachments/assets/2810ed7c-96f9-4802-9fa6-2b7252653f23)

Plesk
PHP: 8.1.29
Nginx

![image](https://github.com/user-attachments/assets/e8115a18-1f6c-473f-8017-ace6f002dea3)

Then we try to install 8.1.0, we erase all file, database and start over, we manage to install it without any error.

Then we update to the last version 8.1.7

![image](https://github.com/user-attachments/assets/ceb240b1-07f7-48a7-b468-e1c8d903a690)

![image](https://github.com/user-attachments/assets/05781a13-bce3-470e-ac65-e9997b271911)

 After finish, we get many error on controllers (we erase cache, server and browser)

On login to the backoffice
![image](https://github.com/user-attachments/assets/7949eb1e-77c5-49ae-8071-7ae01301ac49)

stadistics
![image](https://github.com/user-attachments/assets/6746c1f7-8df5-4f1c-8afd-a1517b57106d)

Prestashop metric
![image](https://github.com/user-attachments/assets/0ef22ebd-22e3-4c87-8548-aea1b517bc38)

Module marketplace
![image](https://github.com/user-attachments/assets/e9a4e990-7876-47dc-90f2-13898b1a39d1)

design -> personalization
![image](https://github.com/user-attachments/assets/5d2bfc67-0b8c-4229-b7e0-9175b49b8beb)

design ->theme catalog
![image](https://github.com/user-attachments/assets/03b689bd-20ed-46df-8750-1a3e8515a9b3)

if we stay on PS 8.1.0 all these sections works 

we do not know if it has something to do with this issue but we set the country as México

### PrestaShop version(s) where the bug happened

8.1.6 / 8.1.7

### PHP version(s) where the bug happened

8.1.29

### Your company or customer's name goes here (if applicable).

Multiservicios Austral

**Comment by matks** [comment]
Seems similar to https://github.com/PrestaShop/PrestaShop/issues/36541

**Comment by msaustral** [comment]
Hi Mat, yes it is the same issue but it is not solved! the case was close so we had to open a new one, also the upgrade from 8.1.0 to any of the last versions, has big issues with controller.

**Comment by msaustral** [comment]
Hi we re try the test with the last file available and the error was corrected, thank you
