### ISSUE TITLE
Unable to complete the payment.

### ISSUE THREAD

**Issue by Monica35580** [PrestaShop/PrestaShop#36767]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

 I am unable to complete the purchase on my website. This is a test site, but this functionality needs to work.
![Capture d'écran 2024-08-27 120444](https://github.com/user-attachments/assets/c486b447-9ed4-40d5-8d9c-2eaf1758f796)

here are the captures when the debug is on
![Capture d'écran 2024-08-27 121105](https://github.com/user-attachments/assets/978254ec-6fb6-401d-b0be-cb1fee3ea97c)
![Capture d'écran 2024-08-27 121135](https://github.com/user-attachments/assets/abb1c887-fc83-4766-8b7c-6a278bf39729)

### Expected behavior

I don't have a precise idea, but it could be due to a file on the FTP or a module. I initially thought it was related to Packlink Pro, but the problem persists even when I disable it. Therefore, the error must be coming from elsewhere.

### Steps to reproduce

1. Go to the site: [https://3s426bkqef.preview.infomaniak.website/](https://3s426bkqef.preview.infomaniak.website/)
2. Select a product
3. Place an order
4. Enter personal information
5. Choose the shipping method
6. Select the payment method (bank transfer)

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.0

### Your company or customer's name goes here (if applicable).

Monica

**Comment by ingridusta** [comment]
Hello @Monica35580,

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Thank you
