### ISSUE TITLE
buildView problem with respecting empty array

### ISSUE THREAD

**Issue by Blaaszkovsky** [PrestaShop/PrestaShop#36770]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The problem started with a customer getting a 500 error on some products when entering a product edit. Some products had the correct edit view and some products were throwing the error. The error looks like this: https://i.imgur.com/LjOb8wl.png, so I started debugging the `buildView` function in the TypeaheadProductCollectionType.php file. 

I threw myself a `dump($view->vars['value']['data']);exit;` to see what was being sent, and I was surprised because the product that worked returns the correct IDs of the related products, and the one that didn't work returns an empty array:
1. working product: https://i.imgur.com/T7btKyv.png
2. non-working product: https://i.imgur.com/hL3zsO5.png

Even though `$view->vars['value']['data']` is empty the conditional statement in line 72 checks for empty and returns “false” it passes on which causes the problem because then `$view->vars['value']['data']` takes the value “1” and the product with that ID does not exist on store. 

Store does not have any overrides for editing products or modified files in this regard: https://i.imgur.com/u0RywXm.png

### Expected behavior

A temporary solution to this problem is to add the condition `if(empty($product->id)) break;` in the default in the switch before append `collection` array. Then the product card displays correctly without error.

### Steps to reproduce

I'm not sure how to reproduce it exactly, but maybe such a path will allow the error to be triggered:
1. Add 10 products.
2. In the product with ID 9, add related products with ID: 1,2,3. 
3. Remove products with identifier: 1,2,3. 
4. Try to edit product with ID: 9. 

### PrestaShop version(s) where the bug happened

8.0.5 (after upgrade from 1.7.5.1)

### PHP version(s) where the bug happened

8.1

**Comment by kpodemski** [comment]
Hello @Blaaszkovsky 

Thanks for reporting this issue. I think we can close it since it is related only to the legacy product page, and you know the solution. The file you mentioned doesn't exist on PrestaShop 9.

I'm pinging @ibahloul-ps so that he can decide.

**Comment by ibahloul-ps** [comment]
Hello @Blaaszkovsky,
We no longer maintain legacy product page.
Have a great day!
