### ISSUE TITLE
Category shop association

### ISSUE THREAD

**Issue by PululuK** [PrestaShop/PrestaShop#36780]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When creating a category through the Model object, the `id_shop_list` property is not taken into account during persistence. So even when specifying the list of associated shops, by default the category is associated with all shops.### 

### Expected behavior

when persisting a category, if the `id_shop_list` property is defined, it must be taken into account, i.e. the category must only be associated with the specified shops

### Steps to reproduce

- create a prestashop instance with multiple stores
- modify the code below by specifying the ids of the shops to which you want to associate the category (`id_shop_list`). For example, put only one shop
- check that despite the effect of having specified only a few stores, your new created category is associated with all stores

```php
<?php
$categoryObject = new Category();
$categoryObject->name = 'My category name';
$categoryObject->link_rewrite = 'my-category-link-rewrite';
$categoryObject->id_parent = (int) Configuration::get('PS_HOME_CATEGORY');
$categoryObject->id_shop_list = [1, 2]; // Set here related shops ids
$categoryObject->add();
```

### Workaround

```php
<?php
$categoryObject = new Category();
$categoryObject->name = 'My category name';
$categoryObject->link_rewrite = 'my-category-link-rewrite';
$categoryObject->id_parent = (int) Configuration::get('PS_HOME_CATEGORY');
$categoryObject->id_shop_list = [1, 2]; // Set here related shops ids

// put manually post data
$checkBoxShopAssoCategory = [];
foreach ($categoryObject->id_shop_list as $idAssociatedShop) {
    $checkBoxShopAssoCategory[$idAssociatedShop] = $idAssociatedShop;
}

$_POST['checkBoxShopAsso_category'] = $checkBoxShopAssoCategory;

$categoryObject->add();
```

### PrestaShop version(s) where the bug happened

`1.7.x` to `develop`

### PHP version(s) where the bug happened

N/A

### If your bug is related to a module, specify its name and its version

N/A

### Your company or customer's name goes here (if applicable).

Evolutive

**Comment by ingridusta** [comment]
Hello @PululuK, 

I understand that to test this issue I need to modify the id_shop_list but in which file can I do that, please ? 

Thanks.

**Comment by florine2623** [comment]
friendly reminder @PululuK :)

**Comment by paulnoelcholot** [comment]
Hello @PululuK ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you
