### ISSUE TITLE
Module autoupgrade stops with error

### ISSUE THREAD

**Issue by stefanogriggio** [PrestaShop/PrestaShop#36809]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Upgrading Prestashop from 8.1.4 to 8.1.7 using 1-click upgrade in Italian, the procedure stops with an internal error caused by an incorrect translation in file 

/modules/autoupgrade/translations/ModulesAutoupgradeAdmin.it.xlf

at line 615

<target state="final">L'hask MD% sarà confrontato con %s</target>

The error is related to "sprintf" function and caused by the first, unnecessary "%"

### Expected behavior

The translation should be

<target state="final">L'hask MD5 sarà confrontato con %s</target>

### Steps to reproduce

Upgrade Prestashop 8.1.4 in Italian

### PrestaShop version(s) where the bug happened

PS 8.1.4 

### PHP version(s) where the bug happened

8.1.29

### If your bug is related to a module, specify its name and its version

autoupgrade 6.0.0

**Comment by Quetzacoalt91** [comment]
Thank you @stefanogriggio, we have updated the translation and it will be sent in the next release.

**Comment by Quetzacoalt91** [comment]
Fixed with autoupgrade v6.2
