### ISSUE TITLE
Error occurs when navigating new admin controllers with empty quick access links

### ISSUE THREAD

**Issue by Codencode** [PrestaShop/PrestaShop#36801]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When the quick access links are emptied in the Prestashop back office, navigating to new admin controllers results in a system error. 

[screen-capture.webm](https://github.com/user-attachments/assets/1f8a0976-3f44-4067-8d6b-e4f6c80bbd54)

### Steps to reproduce

1. Go to the Prestashop back office.
2. Enable **Debug mode**.
3. Clear all entries from the "Quick Access" menu.
4. Attempt to navigate to a new admin controller (e.g., a product page).
5. Observe the error that appears.

### PrestaShop version(s) where the bug happened

8.1.7

### Your company or customer's name goes here (if applicable).

Codencode

**Comment by ibahloul-ps** [comment]
Hello @Codencode,

I reproduce the issue with PrestaShop version 8.1.7, I'll add this to the backlog so it can be fixed :)
Thank you for your contribution!

Error message :
<img width="638" alt="image" src="https://github.com/user-attachments/assets/2afecce9-5b8e-4e18-96f3-6982331700ea">

```
Unknown error on line 2583 in file /Applications/MAMP/htdocs/prestashop_8.1.7/classes/controller/AdminController.php
[8192] Creation of dynamic property HelperView::$actions is deprecated
```

**Comment by Codencode** [comment]
> I reproduce the issue with PrestaShop version 8.1.7, I'll add this to the backlog so it can be fixed :)
> Thank you for your contribution!

Hi @ibahloul-ps,
I created the PR #36802 to solve the problem

Thanks.

**Comment by florine2623** [comment]
Fixed in https://github.com/PrestaShop/PrestaShop/pull/36802
