### ISSUE TITLE
Response from webservice is not always XML !

### ISSUE THREAD

**Issue by jbjuge** [PrestaShop/PrestaShop#36815]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

**PrestaShop-webservice-lib**

executeRequest() initiates the body of the cURL response in $body, assuming this part is only XML.
Sadly, some modules also send Javascript code after the <prestashop></prestashop> tags in the response

### Expected behavior

executeRequest() should parse the response and isolate the XML between <prestashop></prestashop> tags.

$body should only contain the XML

### Steps to reproduce

1. Install Amazon Marketplace Extension : https://addons.prestashop.com/fr/marketplace/2501-amazon-market-place.html?ab=1
2. Try to edit a product via Webservice
3. Display the response, you should see code from the plugin hooks after the XML usual content

![image](https://github.com/user-attachments/assets/6e06fdf5-1434-49e7-b49a-fde7ad98081e)

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

amazon-market-place v5.3.36

### Your company or customer's name goes here (if applicable).

SAS ADD

**Comment by kpodemski** [comment]
Hello @jbjuge 

This space is for reporting bugs related to the PrestaSho core or modules bundled inside the software's default version. Amazon is a paid module that requires you to contact its author for support.
