### ISSUE TITLE
[Autoupgrade] it's impossible tu launch upgrade in command line in Windows

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#36810]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Lauch autoupgrade in command line, the error "The command line is too long" appears at first step.
![image](https://github.com/user-attachments/assets/42fc5423-6339-41d4-9d39-00673b831550)

### Expected behavior

launch the others steps like in linux.
The configuration is stored in the database and should not be passed encoded in base64

### Steps to reproduce

Lauch autoupgrade in command line under in windows

### PrestaShop version(s) where the bug happened

8

### PHP version(s) where the bug happened

all

### If your bug is related to a module, specify its name and its version

autoupgrade v6.0.0

### Your company or customer's name goes here (if applicable).

Creabilis.com

**Comment by kpodemski** [comment]
I'm not sure if we should take on this issue given that there's plenty of solutions to have a more production-like environment on Windows.

First of all, no one from the team use Windows, secondly, there are more issues which need addressing and which are not really issues if you use WSL2 or Docker.

I'll ping @gericfo, so that he is aware of this issue.

**Comment by jf-viguier** [comment]
@kpodemski I know all of this but it's a regression from previous version of autoupgrade. I've switched to wsl indeed.

**Comment by M0rgan01** [comment]
@jf-viguier this is now fix on the development branch, we no longer pass the state in a "data" option, it is now managed via files

**Comment by jf-viguier** [comment]
thanks @M0rgan01
