### ISSUE TITLE
[autoupgrade] upgrade log should be written in the log file on command line launch

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#36829]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After an upgrade in command line, the log file doen't contain upgrade data like in web launch.

### Expected behavior

a real log file

### Steps to reproduce

upgrade in command line
see the log in adminfolder/autoupgrade/tmp/log.txt

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

all

### If your bug is related to a module, specify its name and its version

autoupgrade V6.1

### Your company or customer's name goes here (if applicable).

Creabilis.com

**Comment by AureRita** [comment]
Hi @jf-viguier 

Thank you for your report, did the PR https://github.com/PrestaShop/autoupgrade/pull/923 is useful ? 

Waiting for feedback

**Comment by AureRita** [comment]
fixed by https://github.com/PrestaShop/autoupgrade/pull/923
