### ISSUE TITLE
Configuration confirmation not visible after rebranding

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#36838]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Confirmation after configuration of the module is not correctly displayed after rebranding.

![image](https://github.com/user-attachments/assets/87f11489-53a2-4d60-95fc-561fd30c1996)

### Expected behavior

I should see the confirmation, warning, etc.

### Steps to reproduce

1. Go to the configuration of the module like `ps_emailalerts` or `contactform`
2. Save the settings
3. See the error

### PrestaShop version(s) where the bug happened

9.0

### PHP version(s) where the bug happened

8.3

**Comment by Hlavtox** [comment]
There is some high quality CSS even before rebranding. But at least it's redesigned if it doesn't work. 😄

![header](https://github.com/user-attachments/assets/cc20b3d7-8c53-4473-bae4-d3fba3b623a7)

**Comment by ingridusta** [comment]
Hello @kpodemski,

I reproduce the issue with PrestaShop version 9.0.x, ps_emailalerts v3.0.0 and contactform v4.4.2 , I'll add this to the backlog so it can be fixed.

![Capture d’écran 2024-09-10 à 10 26 11](https://github.com/user-attachments/assets/57152849-d07f-4673-a567-b7fb350eb8ae)

![Capture d’écran 2024-09-10 à 10 26 42](https://github.com/user-attachments/assets/49e6c454-e6c9-44ac-825a-7e448c027bb5)

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by kpodemski** [comment]
It is fixed now.
