### ISSUE TITLE
PHP 8.3 deprecation warnings

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#36837]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

There are some deprecations in PrestaShop 9 on PHP 8.3.

### Expected behavior

No deprecations.

### Steps to reproduce

Place an order, during the process with profiler and debug mode enabled you will see this error:

```

Deprecated: Creation of dynamic property Address::$back is deprecated in /Users/kpodemski/code/prestashop9/classes/form/CustomerAddressForm.php on line 159

Deprecated: Creation of dynamic property Address::$token is deprecated in /Users/kpodemski/code/prestashop9/classes/form/CustomerAddressForm.php on line 159
```

### PrestaShop version(s) where the bug happened

9.0

### PHP version(s) where the bug happened

8.3

**Comment by Codencode** [comment]
Hi @kpodemski,

the issue occurs if there is no address and it's created directly during checkout, right?

If that's the case, it would be necessary to check if the Address object has those specific properties.

We could do it this way:

```php

        // file classes/form/CustomerAddressForm.php method "submit"
        
        foreach ($this->formFields as $formField) {
            if (property_exists($address, $formField->getName())) {// I'll check if the object has the property
                $address->{$formField->getName()} = $formField->getValue();
            }
        }
```

**Comment by kpodemski** [comment]
@Codencode 

> the issue occurs if there is no address and it's created directly during checkout, right?

Exactly :)

> If that's the case, it would be necessary to check if the Address object has those specific properties.

Yes, that or adding those properties could work. Adding the check may be more future-proof.

**Comment by Codencode** [comment]
@kpodemski,

Do I create a PR?

If I create the PR, it has to be done for the develop branch, right?

**Comment by kpodemski** [comment]
@Codencode 

If you are motivated to do it, feel free to create a PR. It would be very much appreciated!

And yes, it goes for the `develop` branch.

**Comment by Codencode** [comment]
PR created
#36866

**Comment by florine2623** [comment]
Hello @kpodemski ,

I reproduce the issue with PrestaShop version 9.0.x, I'll add this to the backlog so it can be fixed.


https://github.com/user-attachments/assets/b4f36609-30dd-47e9-a105-0c3b09f93764

<img width="1437" alt="Screenshot 2024-09-12 at 16 17 55" src="https://github.com/user-attachments/assets/58d0e3f4-4b58-4384-aca8-c0873de31266">


Thank you
