### ISSUE TITLE
Link Google Analytics with Prestashop Metrics : "No tags found"

### ISSUE THREAD

**Issue by zenplayx** [PrestaShop/PrestaShop#36879]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I am trying to link Google Analytics to Prestashop Metrics.
I can connect my Google Analytics account. No problem.
But when selecting a property, I get the message "No tags found".
However, the Google Analytics module is installed and configured on my Prestashop (with the correct GA4 tracking ID).

Prestashop 8.1.7
Module PrestaShop Metrics 4.0.5
Module Google Analytics 5.0.2
Google Analytics GA4

<img width="1000" alt="Capture d’écran 2024-09-08 à 11 03 41" src="https://github.com/user-attachments/assets/481b358a-b814-46de-a201-43de83d4e958">

### Steps to reproduce

Click on "Prestashop Metrics"
Link the Google Analytics account to Prestashop Metrics
Select a property in the dialog Box, but no properties appears
Error message "No tags found"

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.1.29

### If your bug is related to a module, specify its name and its version

PrestaShop Metrics 4.0.5

**Comment by DavidFortuneFactory** [comment]
Hi @zenplayx,

I have been taking a look about Prestashop Metrics, I have the same issue but not exactly your same BO config (I don't use Module Google Analytics, I work via GTM with premium google tag manager module).

As you can see below:
https://help-center.prestashop.com/en/articles/4956382904978-connect-an-account-google-analytics-to-prestashop-metrics

"Special case: no tag detected
PrestaShop Metrics automatically detects the presence of a Google Analytics tag on your site. If no tag has been detected, a banner appears, prompting you to implement your tag. This tag is essential for sending your visit data to Google Analytics.

To do this, you can use our Google Analyticsmodule. Please note: this module does not work with Google Analytics V4accounts. For more details on this step, please refer to the next paragraph."

Regards.
David.

**Comment by florine2623** [comment]
ping @fox-john
You might be interested ^^

**Comment by florine2623** [comment]
Hello,

I can't reproduce your issue on 8.1.x.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by keshvathakur47** [comment]
Very nice GA4 Google Analytics & GTM - Latest Prestashop https://modulesprestshop.com/prestashop-seo/ga4-google-analytics-gtm-latest-prestashop.html
