### ISSUE TITLE
Product Description Save/Update Failure

### ISSUE THREAD

**Issue by anita-coody** [PrestaShop/PrestaShop#36888]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

**Problem Description**

The client has reported an issue with the improper saving and updating of product descriptions in a PrestaShop-based store. Despite entering new content or editing existing descriptions, these changes are not always immediately visible on the product page. In some cases, multiple attempts to save the description are required, and sometimes the changes do not save at all, even though the content was added correctly.

**Actions Taken by the Client**

**1. Text Entry Method:** The client has tried various methods of entering content, including copying from notes and directly editing text within the PrestaShop editor.
**2. Text Formatting:** The content added to product descriptions was generated using various tools, such as ChatGPT, and then copied into the product editor.
**3. Attempts to Resolve the Issue:**
> - The client tried pasting content without formatting (using Ctrl + Shift + V).
> - Descriptions were also added directly in the editor, without copying content from external sources.
> - Despite these attempts, the problem persists – in some cases, products require multiple saves, and sometimes the descriptions do not save at all.

**Current Status**

The issue with updating descriptions has not yet been fully resolved. The client has noticed that some descriptions only update after several save attempts, while others do not save at all.

**Information**

1. PrestaShop Version: 8.1.3
2. PHP Version: 7.4.33
3. MySQL Version: 10.4.27-MariaDB-cll-lve

### Expected behavior

We need support in diagnosing and resolving the issue related to saving and updating product descriptions in PrestaShop to ensure that changes are saved and visible on the site without the need for multiple save attempts.

### Steps to reproduce

1. Go to the PrestaShop admin panel.
2. Navigate to Catalog and click on Products.
3. Select a product and click Edit.
4. Scroll down to the Description field.
5. Edit the product description or enter new content.
6. Click Save.

### PrestaShop version(s) where the bug happened

8.1.3

### PHP version(s) where the bug happened

7.4.33

**Comment by paulnoelcholot** [comment]
Hello @anita-coody 

I tested your issue but as you can see, I can't reproduce the problem : https://www.loom.com/share/4f4920b88c79421b9a42133320c8700c

Did I miss something?

Thanks!

**Comment by anita-coody** [comment]
Hello,

You haven't missed anything. I also tried to reproduce but failed. So why does the client have a problem with it?
I'd also like to add that I also verified the problem on the browser the client is using, ‘Google Chrome’, and still didn't hit the problem. Therefore, even more so, we have no idea what could be causing this.

Initially, the customer reported that the description update was not working at all, but after receiving instructions from us on how to paste the content correctly (without formatting), the problem disappeared and the descriptions were saved, but as I mentioned in the notification - this did not happen immediately, sometimes requiring several attempts to save. So a customer needs several attempts to update a product description.

pozdrawiam
Anita Mateja
+48 786 969 961
***@***.******@***.***>
***@***.***
coody.it
ul. Gdańska 43/19
83-300 Kartuzy
NIP 5891783726

**Comment by kpodemski** [comment]
@anita-coody 

I think you should check the database to see if the description is updated there. The problem may not be with the description not being saved but with the front office not serving the updated content.

The content should be saved to the database if there's no error message. I also suggest checking content (HTML generated) after each save in both the visual editor and in the database to see if it is the same.

**Comment by paulnoelcholot** [comment]
Hello @anita-coody,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you
