### ISSUE TITLE
Fatal error with demoextendtemplates module  when testing decoration on PS 9

### ISSUE THREAD

**Issue by bpato** [PrestaShop/PrestaShop#36887]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I installed the demoextendtemplates module to test decoration on OrderController with Prestashop 9.0.0 and I got this error.

![image](https://github.com/user-attachments/assets/3fd2b63c-0396-4166-9acb-207e871638c4)

I also test on PrestaShop 8.1.5 an the module works as expected.

### Expected behavior

OrderController is decorated and shows a custom flash message like the module`s README shows
https://github.com/PrestaShop/example-modules/tree/master/demoextendtemplates

### Steps to reproduce

1. Install the demoextendtemplates module from https://github.com/PrestaShop/example-modules/tree/master/demoextendtemplates
2. Go to Orders section in the backoffice

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.2.21

**Comment by kpodemski** [comment]
Hello @bpato 

Example modules need to be adjusted for PrestaShop 9. We haven't done that yet.

**Comment by bpato** [comment]
Hello @kpodemski, 

ok, i was unsure if that was related to the plugin or to the PS9. Can you point me to some documentation to see how to do a decoration for a controller for PrestaShop 9?

Thanks.

**Comment by florine2623** [comment]
Hello @bpato ,

I reproduce the issue with PrestaShop version 9.0.0, I'll add this to the backlog so it can be fixed.

<img width="1076" alt="Screenshot 2024-09-12 at 16 49 39" src="https://github.com/user-attachments/assets/445ba785-bc2e-4165-92f8-15ad1ef43e5d">


Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by florine2623** [comment]
Link to devdocs for PS 9.0.0 : https://devdocs.prestashop-project.org/9/basics/installation/system-requirements/

**Comment by kpodemski** [comment]
@florine2623 no need to do checks for demo modules, we know they have to be adapted for v9 👍🏻 thanks
