### ISSUE TITLE
404 Error - Downloadable font: Download failed - Prestashop 8.1.7 - Classic Theme

### ISSUE THREAD

**Issue by nathanduckett** [PrestaShop/PrestaShop#36898]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

 When looking at the Developer Tools in the browser I am getting the following errors (domain name removed):

downloadable font: download failed (font-family: "Manrope" style:normal weight:600 stretch:100 src index:0): status=2147746065 source: https://********************.co.uk/themes/classic/assets/css/c80d4fb11dcc2140b260.woff2

downloadable font: download failed (font-family: "Manrope" style:normal weight:400 stretch:100 src index:0): status=2147746065 source: https://********************.co.uk/themes/classic/assets/css/0f099f4e4d67aeb18ab6.woff2

downloadable font: download failed (font-family: "Material Icons" style:normal weight:400 stretch:100 src index:2): status=2147746065 source: https://********************.co.uk/themes/classic/assets/css/f2a0933406f783065152.woff2

downloadable font: download failed (font-family: "Manrope" style:normal weight:700 stretch:100 src index:0): status=2147746065 source: https://********************.co.uk/themes/classic/assets/css/de69cd9e672c81725abc.woff2

I have seen this error on 2 installs of prestashop  on two servers, installed manually.

Prestashop Version 8.1.7 using Classic Theme. 

I have found the problem and a possible Bug:

The stylesheet had somehow been modified and the file names for the fonts had been changed to the same as the .woff extension file name: 

![corrupted-stylesheet](https://github.com/user-attachments/assets/8b5c7b95-74a6-4372-ba7a-7ef2d7a49f34)

I downloaded a fresh copy of Prestashop and compared the 2 files (theme.css) here is the original: 

![original-stylesheet](https://github.com/user-attachments/assets/28179a57-f83a-46cf-8dc3-f03a700a137b)

I uploaded a fresh copy of the stylesheet to the server and this fixed the problem. 

I then went into the back office to "index.php/modules/improve/design/colors" and as soon as I changed the colours and hit save it modified the theme.css and changed the file names again??

### Steps to reproduce

On a clean install using the classic theme go into the back office to "index.php/modules/improve/design/colors".

Change the colours and hit save

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.1.29

### If your bug is related to a module, specify its name and its version

Classic Theme

**Comment by florine2623** [comment]
Hello @nathanduckett ,

I can't reproduce your issue. I am redirected to the Dashboard.

https://github.com/user-attachments/assets/fb15e99a-e271-41c3-8834-96ff0c2a722c

Am I missing something ? Could you send a screen record of your issue.
Thanks.

**Comment by nathanduckett** [comment]
Hello @florine2623,

Thanks for your reply please see screen capture. At the end I use CTRL + F5 to force refresh in the browser.

https://github.com/user-attachments/assets/cc7f9f8d-f46f-44b7-8b71-1552774440cb

**Comment by florine2623** [comment]
Hello @nathanduckett ,

We use GitHub issues only to discuss about bugs and new features in the **PrestaShop project** only.

You can contact the support directly via your back-office for this type of issues.

Thank you
