### ISSUE TITLE
FO - Warning error displayed when customizated product added to cart  

### ISSUE THREAD

**Issue by ingridusta** [PrestaShop/PrestaShop#36907]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

This error is displayed on the top of the page when a customized product is added to cart : 

**Warning: Undefined array key "isRewritable" in /Users/iUstaoglu/Sites/localhost/mercredi9.0.0/src/Adapter/Presenter/AbstractLazyArray.php on line 401**

![Capture d’écran 2024-09-13 à 15 05 23](https://github.com/user-attachments/assets/da695edd-70d6-44ab-a94b-92f9f8baa66b)

https://github.com/user-attachments/assets/a8fc03da-181a-475b-bde5-0d0b4192aac3

**Remark : 
The error is no more displayed when the product is deleted from the cart.**

### Expected behavior

No error should be displayed 

### Steps to reproduce

1. Go to BO
2. Enable the debug mode
3. Go on the FO 
4. Search for a customizable product
5. Click on the product
6. Type a text in the field 'Product customization'
7. Click on the CTA 'Save customization'
8. Click on the CTA 'Add to cart'
9. Ctrl + shift + r

### PrestaShop version(s) where the bug happened

develop, 9.0.x

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment]
@matthieu-rolland This is related to the latest changes in the lazy array, can you check?

**Comment by matthieu-rolland** [comment]
I take this 👍

**Comment by Hlavtox** [comment]
@matthieu-rolland Is this issue only 9.0.0? Didn't it get into 8.2.0?

**Comment by matthieu-rolland** [comment]
> @matthieu-rolland Is this issue only 9.0.0? Didn't it get into 8.2.0?

Nope, I checked before the release and couldn't reproduce it on 8.2.

I didn't have the time to check it out on develop yet

**Comment by Hlavtox** [comment]
@matthieu-rolland All good then. :-)

**Comment by florine2623** [comment]
I also have this error when I create a Pack of products without any product inside.

![Image](https://github.com/user-attachments/assets/f7fd3024-5d92-4190-94a4-d6a22881dbcb)

**Comment by matthieu-rolland** [comment]
@ingridusta the bug is fixed in this PR, it's waiting for QA: https://github.com/PrestaShop/PrestaShop/pull/37589
