### ISSUE TITLE
Produkt-Bilder werden nicht angezeigt

### ISSUE THREAD

**Issue by Tintenhaus** [PrestaShop/PrestaShop#36918]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The product images simply disappeared. But in the backend these are present in the article

### Expected behavior

View product images

### Steps to reproduce

shoping.das-tintenhaus.de

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

8,1

### If your bug is related to a module, specify its name and its version

nein

### Your company or customer's name goes here (if applicable).

Tintenhaus

**Comment by ingridusta** [comment]
Hello @Tintenhaus,

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Thank you
