### ISSUE TITLE
Not all features available on new template page

### ISSUE THREAD

**Issue by wswojtek** [PrestaShop/PrestaShop#36927]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I trying to create new or edit template for my category I can't choose features when it is use in product.
If I delete feature from product it's available to choose.

### Steps to reproduce

1. Go to features.
2. Add new.
3. Go to products
4. Add feature to product
5. Go to Faceted Search configuration
6. Create new/Edit exist

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

7.3.33

### If your bug is related to a module, specify its name and its version

Faceted Search v3.16.1

**Comment by ingridusta** [comment]
Hello @wswojtek,

I tried to reproduce your ticket, but with Prestashop 9.0.x and ps_facetedsearch v3.16.1 and I do not have the same problem. The feature is displayed on the Faceted search on the BO and the FO when it is applied on a product.

![Capture d’écran 2024-09-16 à 16 44 12](https://github.com/user-attachments/assets/796a0950-237b-4f9f-b9be-44bacf01b356)

![Capture d’écran 2024-09-16 à 16 44 30](https://github.com/user-attachments/assets/556301aa-9918-4cf5-8e1b-80b207e5bb96)

![Capture d’écran 2024-09-16 à 16 44 39](https://github.com/user-attachments/assets/c952cc62-fd9b-40db-9274-74c5a109affe)


We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Thank you
