### ISSUE TITLE
Property Order->total_paid_tax_excl is not valid when voucher code is exactly equal to the order total (free order)

### ISSUE THREAD

**Issue by OliverCG** [PrestaShop/PrestaShop#36926]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

We're introducing a manual order for a customer through the FrontOffice after a new agreement where we're going to replace a previous order. For that, we've generated a new voucher code so we can insert the order through the FrontOffice. During the process of inserting the order, the customer added some items to the cart where the new order total is equal to the voucher code generated previously. Despite the fact that the system seems to work, once we clic on the payment link, the system throws and 500 error where the total_paid_tax_excl seems to not be correct.

We've checked the system and there is no override for any of the classes as it's stated in the screenshot:

![Screenshot 2024-09-16 at 13-38-04 ](https://github.com/user-attachments/assets/bcc05d7e-e8c8-4ca1-8d8d-81d2e3d8d562)

I've found an issue that may be related: https://github.com/PrestaShop/PrestaShop/issues/28176

### Expected behavior

The expected behavior is to insert the order into the system with no problems and show the order confirmation page.

### Steps to reproduce

1. Generate voucher with amount equal to order total.
2. Insert desired product in cart.
3. Insert voucher code.
4. Select one of the free shipping carriers.
5. Clic on Place order after check all terms and conditions checkboxes (in order to enable the payment button).
6. ERROR 500.

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

7.4.33

**Comment by florine2623** [comment]
Hello @OliverCG ,

I can't reproduce your issue on PS 8.x.x :

https://github.com/user-attachments/assets/b4213ed8-80c3-4b45-aeb5-8c277c78b89f

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
