### ISSUE TITLE
Cannot add new feature to products using the new and experimental feature "product page"

### ISSUE THREAD

**Issue by Hokuto-shinken** [PrestaShop/PrestaShop#36948]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi Dear,

I did a fresh install of PS 8 (8.1.7) and migrated my products there (old PS version was 1.7.8.11).
Trying to add features on already existing products is not working anymore.
When I press the button "add feature" nothing happens.
As well, when I enter a product page in the backoffice, I am seeing javascript errors, that could be related.

Please could you kindly provide support and fix if you are able to reproduce this issue?

Thanks in advance.

-----

```

Vue app mount element or context not found [index.js:184:3058](https://unpkg.com/@prestashopcorp/smb-edition-homepage/dist/assets/index.js)
    VB https://unpkg.com/@prestashopcorp/smb-edition-homepage/dist/assets/index.js:184
    xv https://unpkg.com/@prestashopcorp/smb-edition-homepage/dist/assets/index.js:2
    <anonymous> https://unpkg.com/@prestashopcorp/smb-edition-homepage/dist/assets/index.js:1672
```

And as well

```
Uncaught TypeError: window.prestashop.component.EntitySearchInput is not a constructor
    Bw https://www.mydomain.com/myadmin/themes/new-theme/public/product_edit.bundle.js?8.1.7:1402
    <anonymous> https://www.mydomain.com/myadmin/themes/new-theme/public/product_edit.bundle.js?8.1.7:1848
    u https://www.mydomain.com/myadmin/themes/new-theme/public/main.bundle.js:660
    c https://www.mydomain.com/myadmin/themes/new-theme/public/main.bundle.js:660
    setTimeout handler*1629/755/</Deferred/then/o/< https://www.mydomain.com/myadmin/themes/new-theme/public/main.bundle.js:660
    l https://www.mydomain.com/myadmin/themes/new-theme/public/main.bundle.js:660
    fireWith https://www.mydomain.com/myadmin/themes/new-theme/public/main.bundle.js:660
    fire https://www.mydomain.com/myadmin/themes/new-theme/public/main.bundle.js:660
    l https://www.mydomain.com/myadmin/themes/new-theme/public/main.bundle.js:660
    fireWith https://www.mydomain.com/myadmin/themes/new-theme/public/main.bundle.js:660
    ready https://www.mydomain.com/myadmin/themes/new-theme/public/main.bundle.js:660
    q https://www.mydomain.com/myadmin/themes/new-theme/public/main.bundle.js:660
    755 https://www.mydomain.com/myadmin/themes/new-theme/public/main.bundle.js:660
    755 https://www.mydomain.com/myadmin/themes/new-theme/public/main.bundle.js:649
    755 https://www.mydomain.com/myadmin/themes/new-theme/public/main.bundle.js:649
    __nested_webpack_require_297893__ https://www.mydomain.com/myadmin/themes/new-theme/public/main.bundle.js:660
    893 https://www.mydomain.com/myadmin/themes/new-theme/public/main.bundle.js:600
    __nested_webpack_require_297893__ https://www.mydomain.com/myadmin/themes/new-theme/public/main.bundle.js:660
    759 https://www.mydomain.com/myadmin/themes/new-theme/public/main.bundle.js:571
    __nested_webpack_require_297893__ https://www.mydomain.com/myadmin/themes/new-theme/public/main.bundle.js:660
    1629 https://www.mydomain.com/myadmin/themes/new-theme/public/main.bundle.js:660
    1629 https://www.mydomain.com/myadmin/themes/new-theme/public/main.bundle.js:666
    1629 https://www.mydomain.com/myadmin/themes/new-theme/public/main.bundle.js:666
    __webpack_require__ https://www.mydomain.com/myadmin/themes/new-theme/public/main.bundle.js:672
    <anonymous> https://www.mydomain.com/myadmin/themes/new-theme/public/main.bundle.js:672
    <anonymous> https://www.mydomain.com/myadmin/themes/new-theme/public/main.bundle.js:2065
    <anonymous> https://www.mydomain.com/myadmin/themes/new-theme/public/main.bundle.js:2065
```

### Expected behavior

Expected behaviour is that clicking on add feature does its jobs.

### Steps to reproduce

Providing that you have the " New product page " enabled in the " New & Experimental Features " 
1. Go to BO > Catalog > Products
2. Click on any product
3. Go to the detail tab
4. Click on add feature button

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.1

**Comment by ingridusta** [comment]
Hello @Hokuto-shinken,

Despite our efforts, we were not able to reproduce your issue with the provided information.

![Capture d’écran 2024-09-18 à 16 19 36](https://github.com/user-attachments/assets/9138fed6-3797-4ce3-9c23-e13fd615bf3e)

https://github.com/user-attachments/assets/6104d0e1-160f-49cf-8407-82e127321dcd

Let's wait up to 20 days if there will be another contributor who encounter the same issue and can provide new informations to help us reproducing the issue.

Thank you!

**Comment by amini8208** [comment]
Hello, good time - I have the same problem - the product features do not work - when I click on the button, nothing happens - my prestashop version is 8.1.7
