### ISSUE TITLE
ps_emailsubscription actionNewsletterRegistrationBefore can't be registered from another module

### ISSUE THREAD

**Issue by ShaiMagal** [PrestaShop/PrestaShop#36945]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Module ps_emailsubscription have hook **actionNewsletterRegistrationBefore**, but this hook isn't possible to register. (but it's listed here -> https://devdocs.prestashop-project.org/8/modules/concepts/hooks/list-of-hooks/)
I am attaching test module for this purpose as well.
[shaim_test.zip](https://github.com/user-attachments/files/17032386/shaim_test.zip)
Error message:
"_Hook with the name actionNewsletterRegistrationBefore has been registered by shaim_test, but the corresponding method hookActionNewsletterRegistrationBefore has not been defined in the Module class._"

![image](https://github.com/user-attachments/assets/5b84fefb-4a3d-4a06-94e6-46173696f427)

### Expected behavior

Hook can be registered.

### Steps to reproduce

1. install module
2. you will see error message.

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.3

### If your bug is related to a module, specify its name and its version

ps_emailsubscription 2.8.2

### Your company or customer's name goes here (if applicable).

https://www.openservis.cz/

**Comment by Hlavtox** [comment]
@ShaiMagal shaim_test is missing `public function hookActionNewsletterRegistrationBefore` or `public function __call`, the error is quite self explanatory 😁

**Comment by ShaiMagal** [comment]
@Hlavtox True, overworked... :-D :'(
Because o lot of "specialists" make great prestashop eshop and I "must" repair their great job and safe customers from disaster.
So, very tired.

Closing :-D

**Comment by Hlavtox** [comment]
@ShaiMagal Official prestashop partners :DDDD

**Comment by ShaiMagal** [comment]
@Hlavtox Today it was someone else :-D
