### ISSUE TITLE
Stock management does not record movements well

### ISSUE THREAD

**Issue by luckylucciano69** [PrestaShop/PrestaShop#36952]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

We have a problem with stock management. Stock movements are not being recorded and we have it activated in the configuration. The "Activate stock management" option is checked. 
It is very strange because there are some records, but they are minimal. Yesterday, for example, there was no stock movement... today only 1...
On the product detail page in the catalogue, in the quantities tab, the last 5 stock movements of that product do not appear either...
I have investigated and searched online, they talk about selecting the advanced stock option, but that option does not appear to me, nor does adding warehouses or anything similar, just in case you ask about it.
![Captura de pantalla 2024-09-18 123734](https://github.com/user-attachments/assets/be857826-d242-43d9-a7cd-a9dd07ec46d5)
![Captura de pantalla 2024-09-18 123755](https://github.com/user-attachments/assets/8be02d8c-182f-4418-80b7-871f8d14652f)

### Expected behavior

We want to be able to see the complete record of all stock movements and in the product detail the latest movements of the selected product.

### Steps to reproduce

In the backend Go to Catalog - Stock management - Movements

### PrestaShop version(s) where the bug happened

8.1.6

### PHP version(s) where the bug happened

8.1

**Comment by kpodemski** [comment]
Having correct stock movements requires correct settings of your order statuses, as well as correct updating quantities in the shop. Do you use any external software to manage your stocks?

**Comment by luckylucciano69** [comment]
Yes. We have connected Prestashop to our physical warehouse management
system.
Product stock quantities are being updated and synchronized correctly, so
updating quantities in the shop are correct.
The settings of order statuses I think are correct. What is strange is that
it records stock movements but not all of them, without a fixed pattern.
Do you need me to provide you with any information or images to help us
solve this problem?
Thanks in advance

**Comment by kpodemski** [comment]
@luckylucciano69 

well, if you use external WMS, then integration with this WMS has to support PrestaShop movements and correctly trigger specific events in the system to make sure movements are recorded

it looks like some of the movements are manual, and they are recorded, and the automatic ones, the ones after changing statuses, etc., are not recorded which often is due to badly integrated external software

**Comment by luckylucciano69** [comment]
ok. Thanks
I will talk with the developers of the external system

**Comment by luckylucciano69** [comment]
The configuration I showed you in the images are correct? The stock
management option is active right?

**Comment by florine2623** [comment]
>The configuration I showed you in the images are correct? The stock
management option is active right?

Yes you have the right configuration of stock management.
You might have an issue with connecting your module to PrestaShop. The issue does not happen on the core. The stock movements are well taken into account whether I change it as a merchant or I make an order as a customer.

I will close this issue as it is not a known issue, but you can still discuss it with the community.

Thanks!

**Comment by luckylucciano69** [comment]
Understood. Thanks
