### ISSUE TITLE
Wrong Product name when using Duplicate function on multilanguage shop

### ISSUE THREAD

**Issue by bogdanpricop** [PrestaShop/PrestaShop#36960]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the Catalog -> Products Admin page, in the grid the Name is from first language of the shop even if that language is disabled.
When you Duplicate a product in the mentioned grid the Name will be "copy of ...." and the original name in the disabled language. There is no way to edit or display the correct name.

### Expected behavior

If a Language is disabled, the values for the fields to be loaded from the next active one so you can see the new correct information.

### Steps to reproduce

Fresh install
Add a second language to the shop - International -> Localization ->Languages
Add a product - Catalog ->Products ->New product
Disable the default language (ID=1 / English)
Duplicate the created product
Modify the Product Name for the duplicated product
Check the Product lists - Catalog ->Products 

### PrestaShop version(s) where the bug happened

8.0 - 8.1

### PHP version(s) where the bug happened

8.1.29

### Your company or customer's name goes here (if applicable).

Amondia.ro

**Comment by bogdanpricop** [comment]
I have written a small fix using a module. The problem remains in the original code.

[
[mymoduleupdateproductname.zip](https://github.com/user-attachments/files/17050296/mymoduleupdateproductname.zip)
](url)

**Comment by florine2623** [comment]
Hello @bogdanpricop ,

You need to change the name of the product for all languages, like so :

https://github.com/user-attachments/assets/d55feff1-a6f6-4946-9e5d-42b0855c7122

Thanks ^^

**Comment by bogdanpricop** [comment]
Dear @florine2623,

You didn't do the steps that will show the mentioned error:

1. Fresh install
2. Add a second language to the shop - International -> Localization ->Languages
3. Add a product - Catalog ->Products ->New product
4. Disable the default language (ID=1 / English)
5. Duplicate the created product
6. Modify the Product Name for the duplicated product
7. Check the Product lists - Catalog ->Products

Do the steps and you will see that I'm correct, you will face the error that I have logged.
