### ISSUE TITLE
[1.7.8.7] Could not perform action enable for module undefined

### ISSUE THREAD

**Issue by lionelJDN** [PrestaShop/PrestaShop#36970]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Prestashop version : 1.7.8.7
When i need to enable a module, i got the next error:  **Could not perform action enable for module undefined**
When i enable the debug mode, i can see this:
![image](https://github.com/user-attachments/assets/0e3c8277-8222-432c-8d9b-1fe78861d025)

### Steps to reproduce

1. Go to Modules / Module Manager
2. Upload a module
3. Module installed! but not enabled
4. I cliked on Enable
5. I got the next error:  **Could not perform action enable for module undefined**

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.2.34

**Comment by miguellords** [comment]
maybe this will help

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ

you may need to install the c compiler

**Comment by lionelJDN** [comment]
> maybe this will help
> 
> https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
> 
> you may need to install the c compiler

Thank you for your answer dear miguellords but what is it please?

**Comment by florine2623** [comment]
Hello @lionelJDN ,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
