### ISSUE TITLE
PrestaShop 8.1.7 : Child Theme Installation Issue

### ISSUE THREAD

**Issue by Serv598** [PrestaShop/PrestaShop#36989]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I recently purchased the Electron Mega Electronic Super Store theme from ThemeVolty on the PrestaShop marketplace and installed the parent theme without any issues. I’m using PrestaShop version 8.1.7.
After following the documentation provided to create and install a child theme based on this parent theme, the child theme appears in the PrestaShop back office. However, when I try to select and activate the child theme, I encounter the following error:

No route found for "POST /modules/improve/design/themes": Method Not Allowed (Allow: GET)
[SymfonyComponentHttpKernelExceptionMethodNotAllowedHttpException 0]

Thanks

### Expected behavior

The child theme should have load properly in the PrestaShop back office.

### Steps to reproduce

1-Go to back office
2-Use this theme
[error.pdf](https://github.com/user-attachments/files/17077132/error.pdf)

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

Electron Mega Electronic Super Store - v4.4.2 - Développé par ThemeVolty Team

### Your company or customer's name goes here (if applicable).

Solidur

**Comment by kpodemski** [comment]
Hello @Serv598 

This is not a good place to search for help with third-party themes or child themes created based on those. This error doesn't appear on the clean version of the PrestaShop. I suggest contacting theme author support.

**Comment by Oksydan** [comment]
Hi @kpodemski, 
On the other hand. There is something wrong in the error handling if this error occurs on the theme activation. There should be more readable error message instead 🤔 
If @Serv598 can provide reproduction steps with files we could fix just an error handing

**Comment by cabradb** [comment]
I have same problem with other theme. I've created a child directory this below:
/themes/PRS02047
/themes/PRS02047_child
  |--config
    |--|--theme.json

**theme.json content:**
name: PRS02047_child
display_name: "PRS02047_child"
version: 1.0.1
parent: PRS02047

assets:
  use_parent_assets: true_

**Comment by BDoryan** [comment]
I don't know if I have the same issue as you, but to fix my bug, I had to select a shop because I use PrestaShop with multiple shops.

In my case, the problem was that I couldn't click on the "Use this theme" button. I forced it with the "Inspector" tool and removed the "disabled" attribute, which allowed me to see the error message explaining why I couldn't choose this theme until I had selected a shop.

**Comment by florine2623** [comment]
Hello @Serv598 ,

I tested with bith classic and hummingbird themes, as they are the native theme for PrestaShop. It works as expected.

Classic : 

https://github.com/user-attachments/assets/4a2607e4-810f-456b-b904-92c0a44f4d0a


Hummingbird :


https://github.com/user-attachments/assets/dac1f75b-1a71-41f8-816d-706f4ba21ea1


You should contact the developer of the theme directly to fix this issue.

I'm closing the issue as this bug happens on specific themes.
Thanks!

**Comment by EddGreen** [comment]
Hi, I have the exact same problem but with "Classic" theme from Prestashop
I'm using Prestashop 8.2.0 and I installed a theme a few days ago; now I wanted to go back to Classic, but it's giving me the same error from the original message posted here. The error is with both "Classic" theme directly and also "Child Classic".

**"No route found for "POST /modules/improve/design/themes": Method Not Allowed (Allow: GET)"**
![Image](https://github.com/user-attachments/assets/0363d976-266f-4908-b896-a2e9c949f876)

I'm also unable to import any new themes, and I don't know if it's also related to the same problem. After selecting the .zip file from my computer, I click "import" and I'm sent to the following:
![Image](https://github.com/user-attachments/assets/c07cd827-eff9-47e6-a523-7613ce9e1d92)

"Please select the source for your theme import."

**Comment by Deltafox79** [comment]
I Have same issue..

On Prestashop 8.2.0 , new Installation ...

1) Import a New theme Compatible v8.2.0 and Working
2) I Try to return Classic Default Theme and I have this issue : 

![Image](https://github.com/user-attachments/assets/1b5c8d30-c9f9-4149-a264-199f0d8f2e52)

![Image](https://github.com/user-attachments/assets/33345d7d-83b4-4d66-836e-2842a045a3ef)

**Any Fix?**

**Comment by EddGreen** [comment]
I'm still stuck, unable to either go back to Classic Theme or install a new one.

**Comment by Sepremex** [comment]
Same issue, fresh install, the theme/template is a copy from the classic, I just changed the name, on Linux all works well, but on windows with wamp, ohh boy... after 2hr got it working, but the theme is a no go...

**Comment by EddGreen** [comment]
Has anyone been able to fix this? =/

**Comment by Sepremex** [comment]
> Has anyone been able to fix this? =/

I know is not a "solution" but, if you are on Windows, try using a WSL either ubuntu or Arch, I love Arch, so I have it on WSL Arch, had to manually install "LAMP" normal stuff, then again installing PrestaShop 8.2, not a flinch!, I'm using mariadb and php 8.3, no issues so far, all I can tell you is that on windows XAMP or WAMP is gonna be a headache, or you can try docker on windows.

**Comment by daniele-vigano** [comment]
Exact same problem here on my dev machine (Docker on Mac - php:8.1-apache) and online (hosting, php 8.1).

Any solution?

**Comment by Bruttocattivo** [comment]
try to edit
modules/psxdesign/config/routing/themes.yml
and change row 3 
from
methods: [ GET ]
to
methods: [ GET, POST ]

**Comment by daniele-vigano** [comment]
> try to edit modules/psxdesign/config/routing/themes.yml and change row 3 from methods: [ GET ] to methods: [ GET, POST ]

We have made progress: the exception is no longer thrown.
Unfortunately, though, the theme is not changed either, being stuck with the active theme.

**Comment by Bruttocattivo** [comment]
@daniele-vigano 
a very dirty solution:
edit src/PrestaShopBundle/Resources/views/Admin/Helpers/bootstrap_popup.html.twig
In <script> block at bottom append following code:

`$('#use_theme_modal').on('show.bs.modal', function (event) {
            const button = $(event.relatedTarget);
            const actionValue = button.data('action'); 
            $('#use_theme').attr('action', actionValue);
        });`

this worked for me, but repeat: is a very dirty solution

**Comment by daniele-vigano** [comment]
@Bruttocattivo I don't have experience in PS, so I didn't quite grasp what event you had me capture or how you're having me manage it, but it worked out great!

Not so "ugly" and "bad" after all! ;)

Thank you so much!

**Comment by JphenixB** [comment]
Prestashop 8.2.1
tested with PHP 8.2.21 and PHP 8.1.29
clean new installation

### Impossible to activate a child theme via the back-office

### Describe the bug
It is impossible to activate a valid child theme via the back-office. When clicking “Use this theme” on a child theme (with correct theme.yml and directory structure), the following error appears:

> Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException:
> No route found for "POST /modules/improve/design/themes": Method Not Allowed (Allow: GET)

This error is on “Appearance > Personalization” page.

### To Reproduce

Steps to reproduce the behavior:

1. Create a child theme with a proper theme.yml:

> name: mychildtheme
> display_name: MyChildTheme
> version: 1.0.0
> author: Anonymous
> parent: classic
> assets:
>   use_parent_assets: true

2. Place it in /themes/mychildtheme/, with a basic folder structure (config/theme.yml).
3. Go to Appearance > Personalization in the admin.
4. Click “Use this theme” on the child theme block.
5. The modal opens, and when confirming, you get the error.

### Workaround by  [Bruttocattivo](https://github.com/Bruttocattivo)

src/PrestaShopBundle/Resources/views/Admin/Helpers/bootstrap_popup.html.twig

and injecting the following JavaScript at the end:
```
<script>
$('#use_theme_modal').on('show.bs.modal', function (event) { const button = $(event.relatedTarget); 
const actionValue = button.data('action');  
$('#use_theme').attr('action', actionValue); });
</script>
```

edit file modules/psxdesign/config/routing/themes.yml:

change :

> admin_psxdesign_themes_index:
>   path: /themes
>   methods: [ GET]

by 

> admin_psxdesign_themes_index:
>   path: /themes
>   methods: [ GET, POST ]

**Comment by Bruttocattivo** [comment]
> Prestashop 8.2.1 PHP 8.2.21 clean new installation
> 
> ### Impossible to activate a child theme via the back-office
> ### Describe the bug
> It is impossible to activate a valid child theme via the back-office. When clicking “Use this theme” on a child theme (with correct theme.yml and directory structure), the following error appears:
> 
> > Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException:
> > No route found for "POST /modules/improve/design/themes": Method Not Allowed (Allow: GET)
> 
> This error is on “Appearance > Personalization” page.
> 
> ### To Reproduce
> Steps to reproduce the behavior:
> 
> 1. Create a child theme with a proper theme.yml:
> 
> > name: mychildtheme
> > display_name: MyChildTheme
> > version: 1.0.0
> > author: Anonymous
> > parent: classic
> > assets:
> > use_parent_assets: true
> 
> 2. Place it in /themes/mychildtheme/, with a basic folder structure (config/theme.yml).
> 3. Go to Appearance > Personalization in the admin.
> 4. Click “Use this theme” on the child theme block.
> 5. The modal opens, and when confirming, you get the error.
> 
> ### Workaround by [Bruttocattivo](https://github.com/Bruttocattivo)
> src/PrestaShopBundle/Resources/views/Admin/Helpers/bootstrap_popup.html.twig
> 
> and injecting the following JavaScript at the end:
> 
> ```
> <script>
> $('#use_theme_modal').on('show.bs.modal', function (event) { const button = $(event.relatedTarget); 
> const actionValue = button.data('action');  
> $('#use_theme').attr('action', actionValue); });
> </script>
> ```

Following step is needed too

https://github.com/PrestaShop/PrestaShop/issues/36989#issuecomment-2659675540
