### ISSUE TITLE
hook ActionProductGridQueryBuilderModifier causes back office crashes

### ISSUE THREAD

**Issue by musaffarpatel** [PrestaShop/PrestaShop#36992]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The hook "ActionProductGridQueryBuilderModifier" available in Prestashop 8 should allow modules to modify the Products Listing grid in the back office which is great.

However there is quite a serious problem with the hook, whenever any module implements it and modifies the query using $searchQueryBuilder, it not only affects the Product Grid but the modifies the Query for any other modules which also implements the Grid component consequently breaking them.

### Expected behavior

The hook should strictly only affect the Product Grid and not grids belonging to other modules.

### Steps to reproduce

Create a test module, one which implements the hookActionProductGridQueryBuilderModifier and modifies the Product Grid Query using the $searchQueryBuilder object.

Now a second test module which implements a very basic Prestashop / Symfony grid compoenent.  The data should come from any table except for the products table.

If the above is setup correctly, a error similar to the following should be thrown:

The given alias 'p' is not part of any FROM or JOIN clause table. The currently registered aliases are: bsp, pl.

This occurs module has modified the grid query of module 2.

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

7.1 or 8.0

**Comment by Oksydan** [comment]
Hi @musaffarpatel 

Are you able to provide code examples?

**Comment by Hlavtox** [comment]
This is not possible, the hooks modify only the product grid via `actionProductGridDefinitionModifier` and `actionProductGridQueryBuilderModifier`. Yes, one module can break product grid for other ones, but not other grids in the system.

**Comment by musaffarpatel** [comment]
@Hlavtox As described, ActionProductGridQueryBuilderModifier in one module which modifies the grid query breaks the grids in other modules.  This should not be happening, it should only be modifying the Product Grid and no other grid query at all.

**Comment by musaffarpatel** [comment]
@Hlavtox @Oksydan Attached is a zip containing two modules:

Test Module One
Test Module Two

Test Module One is a simple module which will display a list of suppliers in a Symfony grid using and uses The Grid Query Builder to fetch the suppliers from the DB.

After Installing Test Module One, configure it and you will be presented with the grid above.

Now install Test Module Two.

This module does not do anything other than implement the "actionProductGridQueryBuilderModifier" hook and modifies the query.

After installing Module Two, Module One will now throw the error:

"The given alias 'p' is not part of any FROM or JOIN clause table. The currently registered aliases are: s."

This happens because the query modification in "actionProductGridQueryBuilderModifier" is affecting the grid query in Module One.

Hope the above helps.

[testmodules.zip](https://github.com/user-attachments/files/17137352/testmodules.zip)

**Comment by Oksydan** [comment]
Hi @musaffarpatel,

there is an issue in your code 😉 
In file `modules/testmoduleone/config/services.yml` you declare a service with parameter of gridId `product`
```yml
  testmoduleone.grid.data_provider.test:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@testmoduleone.grid.query_builder.test'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'product'
```

In this case `PrestaShop\PrestaShop\Core\Grid\Data\Factory\DoctrineGridDataFactory` dispatch a hook:

```php
        $this->hookDispatcher->dispatchWithParameters('action' . Container::camelize($this->gridId) . 'GridQueryBuilderModifier', [
            'search_query_builder' => $searchQueryBuilder,
            'count_query_builder' => $countQueryBuilder,
            'search_criteria' => $searchCriteria,
        ]);
```
with `gridId` provided in your `testmoduleone.grid.data_provider.test` service definition. 

I think we can close this issue 😉

**Comment by paulnoelcholot** [comment]
Hello @musaffarpatel,

Despite our efforts, we were not able to reproduce your issue with the provided information. It seems that your issue is not a PrestaShop core bug but most likely a server configuration or customization problem.

We will close this issue.

Thank you
