### ISSUE TITLE
Remboursement standard impossible avec code défaut [Exception code 0]

### ISSUE THREAD

**Issue by GusA44** [PrestaShop/PrestaShop#37005]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Je souhaite générer un remboursement standard et rembourser mon client via SystemPay.
L'avoir ne se créé pas et le messag suivant apparaît : Une erreur inattendue s'est produite. [Exception code 0]
![Pièces détachées - 2024-09-23T161708 828](https://github.com/user-attachments/assets/62333dab-8e8c-40f1-8b12-fd76d9e0a43d)

### Steps to reproduce

1.Aller dans la commande
2.Cliquer sur "remboursement standard"
3.Sélectionner tous les articles à rembourser et vérifier le prix
4.Cocher "Rembourser l'acheteur par Web Services SystemPay"
5.Cliquer sur "Remboursement standard"

### PrestaShop version(s) where the bug happened

1.7.8.8

### If your bug is related to a module, specify its name and its version

SystemPay

**Comment by paulnoelcholot** [comment]
Hello,

Please send your request in English. English is the norm on GitHub.

Thank you

**Comment by GusA44** [comment]
Steps to follow to reproduce
1.go to order
2.click on “standard refund
3.select all items to be refunded and check price
4.check “Refund buyer via Web Services SystemPay” box
5.click on “Standard refund”.
![Sans titre](https://github.com/user-attachments/assets/ad94573f-2799-45c1-ab23-ecd97e527435)
