### ISSUE TITLE
Add missing `replyToName` parameter to `actionEmailSendBefore` hook

### ISSUE THREAD

**Issue by tups** [PrestaShop/PrestaShop#37008]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The `actionEmailSendBefore` hook is missing the `replyToName` parameter, which is present in the `Mail::send()` method. This parameter is necessary for modules that need to modify the reply-to name of outgoing emails.

### Expected behavior

The `actionEmailSendBefore` hook should include the `replyToName` parameter along with the other email-related parameters.

### Steps to reproduce

1. Create a module that hooks into `actionEmailSendBefore`.
2. Attempt to access the `replyToName` parameter within the hook.
3. Observe that the `replyToName` parameter is not available, while other parameters like `replyTo` are present.

### PrestaShop version(s) where the bug happened

This issue affects all versions of PrestaShop up to and including the latest development versions (1.7, 8.2).

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

Damien - Lord of Web

**Comment by florine2623** [comment]
Hello @tups ,

Could you send a module example please ?

Waiting for your feedback.
Thanks!

**Comment by tups** [comment]
Hello @florine2623 

Here is a module to illustrate my point. In my use case, I want to keep a history of certain emails to avoid losing them in case the SMTP doesn't work:
[lowlogemail.zip](https://github.com/user-attachments/files/17261574/lowlogemail.zip)

This hook allows you to modify or read the data before the email is sent.
All input data for the function is there except for: which is missing. So it's just to correct this missing point.

I have already prepared the Pull Request to fix this small issue.

Thanks

**Comment by kpodemski** [comment]
@florine2623 I can confirm this "issue" :)

**Comment by kpodemski** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/37009
