### ISSUE TITLE
It's possible to create new carrier without ranges and prices

### ISSUE THREAD

**Issue by paulnoelcholot** [PrestaShop/PrestaShop#37004]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

It's possible to create new carrier without ranges and prices. This should not be possible because this field is mandatory.

![image](https://github.com/user-attachments/assets/f1abbbc1-32c6-48ab-b7a6-b2ecbc6ec90c)

### Expected behavior

This should not be possible because this field is mandatory.

### Steps to reproduce

1. Go to BO > Shipping > Carriers > Add new carrier
2. Fill the page General settings
3. Add  a zone and tax
4. Save
5. Carrier is created without ranges and prices

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

**Comment by MateoChateau** [comment]
Hi @paulnoelcholot thanks for the heads up :) 
We will remove the red asterisk for ranges as they are not mandatory for saving a carrier (the user can like that save and then come later to finish his configuration)

**Comment by MateoChateau** [comment]
@Nakahiru can you please verify one thing, can you please make sure to remove all the red asterisks for all the elements that are not mandatory + the ones that are already prefilled by a default answer ? (like for example the toggles) 

thx
