### ISSUE TITLE
bug in mobile menu

### ISSUE THREAD

**Issue by LinkOfLight** [PrestaShop/PrestaShop#37021]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If you go to the backoffice with a mobile browser or the browser configured as a mobile, when you click on the menu, a black background is displayed over the menu, and the menu does not overlap, making it impossible to use

https://github.com/user-attachments/assets/51a25221-65f6-467c-b369-4c6ca449dca3

### Expected behavior

The menu overlaps and is usable

### Steps to reproduce

1. go to backoffice whit mobile
2. click in menu
3. cant click because have a black image

### PrestaShop version(s) where the bug happened

al 8 branch

### PHP version(s) where the bug happened

8.1.2

**Comment by LinkOfLight** [comment]
I see the z-index in 19999, is over all the backoffice

**Comment by florine2623** [comment]
Hello @LinkOfLight ,

I can't reproduce your issue.

Please report it to your support contact directly via your back-office. Or you can contact the support.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Also, please change your admin folder name for security reasons. This is a public space.

Thank you

**Comment by LinkOfLight** [comment]
> Hello @LinkOfLight ,
> 
> I can't reproduce your issue.
> 
> Please report it to your support contact directly via your back-office. Or you can contact the support.
> 
> We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).
> 
> Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).
> 
> Also, please change your admin folder name for security reasons. This is a public space.
> 
> Thank you
Hello @florine2623 ! Thanks for your answer, about what you tell me I have just updated another of the websites to 8.2, and the Z Index is again configured incorrectly, in 1999 so it "steps" on the rest of things, attached image
<img width="251" alt="image" src="https://github.com/user-attachments/assets/caaf2a65-b84a-4ca4-a61f-c0308a589e92">
<img width="326" alt="image" src="https://github.com/user-attachments/assets/3ddad31b-8a77-40b4-ae2b-8db6e00f01a4">
