### ISSUE TITLE
Upgrade via CLI from 1.7.8.11 to 8.1.7 not possible ("psaddonsconnect")

### ISSUE THREAD

**Issue by sebastian-marinescu** [PrestaShop/PrestaShop#37024]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I am trying to upgrade PrestaShop from 1.7.8.11 to 8.1.7 via CLI by following the [official upgrade-guide](https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/upgrade/).

The first attempts failed, then I noticed that my php-cli is using a different php-version than the website. 
But even with the same php-version, it fails. 

Any help/suggestion/idea/solution is highly appreciated, as our hosting-provider will soon disable php74.

### Expected behavior

I expected a smooth upgrade-process.

### Steps to reproduce

I am using this command: 

`/usr/local/php74/bin/php modules/autoupgrade/cli-upgrade.php --dir=admin_xyz --channel=private --action=upgradeDb`

When executing the command, I get the following log: 

```
INFO - === Step upgradeDb
INFO - Cleaning file cache
INFO - Running opcache_reset
INFO - Initializing required environment constants

WARNING - [INTERNAL] /pathtowww/modules/psaddonsconnect/vendor/composer/autoload_real.php line 41 - require(/pathtowww/modules/psaddonsconnect/vendor/composer/../react/promise/src/functions_include.php): failed to open stream: No such file or directory
PHP Fatal error:  require(): Failed opening required '/pathtowww/modules/psaddonsconnect/vendor/composer/../react/promise/src/functions_include.php' (include_path='/pathtowww/vendor/pear/pear_exception:/pathtowww/vendor/pear/console_getopt:/pathtowww/vendor/pear/pear-core-minimal/src:/pathtowww/vendor/pear/archive_tar:.:/usr/local/share/pear') in /pathtowww/modules/psaddonsconnect/vendor/composer/autoload_real.php on line 41
CRITICAL - [INTERNAL] /pathtowww/modules/psaddonsconnect/vendor/composer/autoload_real.php line 41 - require(): Failed opening required '/pathtowww/modules/psaddonsconnect/vendor/composer/../react/promise/src/functions_include.php' (include_path='/pathtowww/vendor/pear/pear_exception:/pathtowww/vendor/pear/console_getopt:/pathtowww/vendor/pear/pear-core-minimal/src:/pathtowww/vendor/pear/archive_tar:.:/usr/local/share/pear')
CRITICAL - [INTERNAL] /pathtowww/modules/psaddonsconnect/vendor/composer/autoload_real.php line 41 - require(): Failed opening required '/pathtowww/modules/psaddonsconnect/vendor/composer/../react/promise/src/functions_include.php' (include_path='/pathtowww/vendor/pear/pear_exception:/pathtowww/vendor/pear/console_getopt:/pathtowww/vendor/pear/pear-core-minimal/src:/pathtowww/vendor/pear/archive_tar:.:/usr/local/share/pear')
```

I also changed into the `psaddonsconnect` directory, downloaded composer.phar and tried installing its dependencies by executing `/usr/local/php74/bin/php composer.phar install --no-dev`, but it says "Nothing to install, update or remove".

### PrestaShop version(s) where the bug happened

1.7.8.11 / 8.1.7

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

psaddonsconnect 2.1.2

**Comment by Quetzacoalt91** [comment]
That's weird, can you share the contents of the module psaddonsconnect?

Then you can move this folder outside your `modules/` folder before retrying the update. This module is not compatible with PrestaShop 8, no need it to keep it.

**Comment by venditdevs** [comment]
You can just uninstall this module.

**Comment by Quetzacoalt91** [comment]
Closing as the solution is to uninstall this module that will be incompatible with the new version of PrestaShop.
