### ISSUE TITLE
Cart Rules discount with reduction percent applied to Selected products calculates wrong discount voucher value 

### ISSUE THREAD

**Issue by pelechano** [PrestaShop/PrestaShop#37035]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In Cart Rule.php when suming the price in $selected_products_reduction it takes into account the price_without_reduction so the value is greater than expected
```
// Discount (%) on the selection of products 
 if ((float) $this->reduction_percent && $this->reduction_product == -2) {
                $selected_products_reduction = 0;
                $selected_products = $this->checkProductRestrictionsFromCart($context->cart, true);
                if (is_array($selected_products)) {
                    foreach ($package_products as $product) {
                        if ((in_array($product['id_product'] . '-' . $product['id_product_attribute'], $selected_products)
                                || in_array($product['id_product'] . '-0', $selected_products))
                            && (($this->reduction_exclude_special && !$product['reduction_applies']) || !$this->reduction_exclude_special)) {
                            $price = $product['price'];
                            if ($use_tax) {
                                $price = $product['price_without_reduction'];
                            }

                            $selected_products_reduction += $price * $product['cart_quantity'];
                        }
                    }
                }
                $reduction_value += $selected_products_reduction * $this->reduction_percent / 100;
            }
```
![image](https://github.com/user-attachments/assets/c10ddceb-6294-4dee-a81c-e4befb07e1ce)

### Expected behavior

If you use  $price = $product['price_with_reduction'];  the sum is correct so the reduction percentage is calculated with respect the real price of the selected product/s

### Steps to reproduce

Create a discount (cart rule) with selection of products.
Use a Percentage discount and apply them to Selected products
Some of the Selected products have a specific price discount.
The discount is greater than expected because uses the price_without_reduction in the sum

### PrestaShop version(s) where the bug happened

1.7.8 and 8.1

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @pelechano ,

I can't reproduce your issue.

Could you share the whole configuration of the product, the discount and send a screenshot of the result you have in your cart ?

Waiting for your feedback.
Thanks!

**Comment by paulnoelcholot** [comment]
Hello @pelechano,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog. Please note that you can always create a new one if further information pops up.

Thank you

**Comment by pelechano** [comment]
I attach a video 
https://pelechano.es/videostmp/2025-01-23%2009%2046%2011.mp4
