### ISSUE TITLE
Deleting theme cause critical error

### ISSUE THREAD

**Issue by ash-f** [PrestaShop/PrestaShop#37043]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I click the delete button of a theme, a critical error occurs.
It says theme.yml does not exist.
But the theme.yml did exist before deleting the theme.
Theme deleted is not active. (not the current theme)

![theme-deletion-error](https://github.com/user-attachments/assets/1c4c4863-8b29-4b15-baa2-b64b61656729)

Deleted theme: Hummingbird 0.1.5

### Expected behavior

Theme will be deleted without an error.

### Steps to reproduce

1. Go to Design>Theme & Logo 
2. Click the delete button of a theme

### PrestaShop version(s) where the bug happened

8.2.0

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello @ash-f ,

I can't reproduce your issue as you can see from my screen record :

https://github.com/user-attachments/assets/3f2c8078-4761-4957-b79d-67ef110e546d

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by ash-f** [comment]
Try to add a child theme. I think that's the condition that error occurs.
(it doesn't need to be the current theme)

**Comment by ash-f** [comment]
Don't close it, this is a critical error.
Must be fixed.
