### ISSUE TITLE
Experimental new product page turned off unexpectedly

### ISSUE THREAD

**Issue by YanLieb** [PrestaShop/PrestaShop#37057]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello there!

I had the the product page turned on when starting working on my website, I tried to deactivate it to see the difference, reactivated it after, and since then the selector keeps turning itself off unexpectedly and randomly.
I'm on prestashop 8.1.7

<img width="1644" alt="image" src="https://github.com/user-attachments/assets/986ca71c-cad3-47d6-821b-dbbebbb2e2f1">

### Steps to reproduce

Go to 'Advanced Parameters' -> 'New and experimental features'
Toggle off the 'new product page' button
Check a product page
Go back to 'Advanced Parameters' -> 'New and experimental features'
Toggle on the 'new product page' button
Modify and save multiple times various product page.

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.1.29

**Comment by LinkOfLight** [comment]
i have this error too

**Comment by florine2623** [comment]
Hello @YanLieb and @LinkOfLight ,

I can't reproduce the issue.

If you need support please contact the support directly available on your BO.

Thanks!
