### ISSUE TITLE
vosfacturesapp2.4.15: send_invoice []: Module is configured incorrectly. During generate invoice after upgrading to 1.7.8.11

### ISSUE THREAD

**Issue by arikgreen** [PrestaShop/PrestaShop#37065]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Shop doesn't generate invoices after upgrade to 1.7.8.11.
Error log:
vosfacturesapp2.4.15: send_invoice [1251, XXXXXXXX]: Module is configured incorrectly. 

### Expected behavior

Generating invoice for order.

### Steps to reproduce

1. Enable Debug Mode (important)
2. Got to Orders -> Open order without invoice
3. Click Tab: Documents
4. Click Generate invoice
![image](https://github.com/user-attachments/assets/52c788ae-4ae7-470c-9856-f64229a5444a)

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

7.4.33

**Comment by florine2623** [comment]
Hello @arikgreen ,

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
