### ISSUE TITLE
Alert e-mail sent as soon as a product file without stock is modified

### ISSUE THREAD

**Issue by MHeode** [PrestaShop/PrestaShop#37061]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

as soon as we make a modification to a product sheet that's online and out of stock, as soon as we save it, the back-in-stock notification e-mail is sent to customers. Even though there is no stock. 
So we're forced to deactivate the function while we make our modifications. 
Will the latest module updates solve this problem? 

### Steps to reproduce

1. have the mail alert module activated
2. have a product out of stock and online 
3. make a modification to the product file
4. register

### PrestaShop version(s) where the bug happened

1.7.7.1

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

v2.3.3

**Comment by florine2623** [comment]
Hello @MHeode ,

I can't reproduce your issue on 8.2.0 and Mail alerts v3.0.0.

I suggest updating your module to latest version available or you can contact the support if needed.

Thanks!
