### ISSUE TITLE
Buy button lite bug with minimum quantity

### ISSUE THREAD

**Issue by itisco** [PrestaShop/PrestaShop#37077]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you have a product with a minimum quantity set up https://prnt.sc/lZviQDYprbwV and generate a link with the buy button lite module https://prnt.sc/Y1JY8MxNb2nJ the minimum quantity is not taken into consideration, so when you clik on the link generated by the module, the product is not added to the cart. indeed the quantity to be added in the module is hard coded as "1".

### Expected behavior

When the link of the module buy button lite is generated there should be either the possibility to add a quantity to add in the cart or the module should take into consideration the minimum quantity set up in the product.

### Steps to reproduce

1. create a product with a minimum quantity to buy (>1) (ex : https://prnt.sc/lZviQDYprbwV)
2. go in the module Buy button lite and generate the link to add this product in your cart (ex : https://prnt.sc/Y1JY8MxNb2nJ)
3. call the link generated in your browser
4. you'll see that the cart remains emppty and the product not added (ex after calling the URL https://prnt.sc/ar9TfsaN5MT9)

### PrestaShop version(s) where the bug happened

1.7.x

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

 Buy button lite v1.0.1 - par PrestaShop

**Comment by Hlavtox** [comment]
@itisco Hi, this [module is archived](https://github.com/PrestaShop/ps_buybuttonlite) and no longer supported. 👍

**Comment by itisco** [comment]
Hi!

Too bad, that was a great module.
Thanks for the reply.
