### ISSUE TITLE
No transaction ID

### ISSUE THREAD

**Issue by Mel-meel** [PrestaShop/PrestaShop#37084]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello dear dev staff,

I hope you could help me. In few orders, i see something strange. I have no transaction ID referred. The empty cell is the transaction ID. 'inconnu', unkwon in french just tell us the statistics tools didn't find any customer related :

![Capture d’écran 2024-10-04 103102](https://github.com/user-attachments/assets/91f4e25a-3a74-42c1-ad7e-1d8fab6c76d9)

And when i check in the dashboard, 0€ for the whole day and no orders declared for the 2024-09-29 :

![Capture d’écran 2024-10-04 103337](https://github.com/user-attachments/assets/490e04b2-fbde-455e-879b-06040020df96)

But, orders exists.

Best regards,

Mel

### Steps to reproduce

1. Pass an order
2. Go in back-office
3. Check the dashboard
4. Have troubles with the orders?

### PrestaShop version(s) where the bug happened

1.8.1.7

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

statsforecast

**Comment by florine2623** [comment]
Hello @Mel-meel ,

I can't reproduce your issue on my end :
<img width="1041" alt="Screenshot 2024-10-04 at 15 46 13" src="https://github.com/user-attachments/assets/2c8d3e51-ff0c-4a66-8329-3d1edf4436da">

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
