### ISSUE TITLE
Generate a Site Map NOT RESOLVED

### ISSUE THREAD

**Issue by Andreaaaaa345** [PrestaShop/PrestaShop#37085]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi everyone, I'm new and not very expert, I imported product categories from version 1.7.7.8 and right now I'm on version 8.1.7, when I try to generate a sitemap it gives me this error, I don't know what it is due; thanks to anyone who can give me a hand

is the problem identified in #36120; but I didn't find a solution

![Screenshot (40)](https://github.com/user-attachments/assets/c9c8cf42-4925-4597-8b32-8caca1ebfe8f)

### Steps to reproduce

1. Go to the module Google sitemap
2. Generate sitemap

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

7.2.34

### If your bug is related to a module, specify its name and its version

Google sitemap v4.4.0

**Comment by florine2623** [comment]
Hello @Andreaaaaa345 ,

How did you import your categories ?
Did you upgrade your shop from 1.7.7.8 to 8.1.x ? 

Waiting for your feedback.

**Comment by kpodemski** [comment]
Hello

You probably use a third-party module that doesn't work with sitemap generation. Before you generate a sitemap, you can choose which pages you don't want to include. I suggest trying to skip all those pages, and then try to select them one by one or by selecting more regular pages like "new products", "prices drops", etc. first. One of those pages listed there needs to be fixed.

**Comment by Andreaaaaa345** [comment]
Hi @florine2623, yes after an attack on my site I had to update, I switched to version 8.1.7 and imported the old database tables regarding the categories;

Hello @kpodemski, I have already tried removing all the fields but the error continues to exist;

Thank you both so much for your help

**Comment by Andreaaaaa345** [comment]
Is there anyone else with the same problem as me who has found a solution?

**Comment by kpodemski** [comment]
@Andreaaaaa345 The another problem might be some data inconsistency; you'd have to check what exactly the sitemap module tries to do, someone technical will know what to do...
