### ISSUE TITLE
Error During Prestashop Update via 1-Click Upgrade (v1.7.8.10 to v1.7.8.11)

### ISSUE THREAD

**Issue by xarly111** [PrestaShop/PrestaShop#37089]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have Prestashop version 1.7.10 and I want to upgrade to version 1.7.11. I have downloaded the 1clic upgrade module and it installs correctly. When I click on configure, the module starts the opening process, but it hangs at 80% of the module startup. I attach a screenshot.
The Php version is 7.4.33
memory_limit: 512
max_execution_time: 350
max_input_time: 350
post_max_size: 8

opcache.enable: on
![Captura](https://github.com/user-attachments/assets/82330ce9-37aa-4ad2-ac0c-4469da6ff367)

Folder and file permissions are correct. The rest of the modules work correctly, including those of Prestashop.

### Steps to reproduce

I want to run the installation to upgrade to 1.7.11

### PrestaShop version(s) where the bug happened

1.7.10

### PHP version(s) where the bug happened

7.4.33

**Comment by Quetzacoalt91** [comment]
This error is related to the ps_mbo module, responsible of the modules page. By any chance, do you see any error in the browser developer console about a failing request?
You should be able to reach the module with another way. There is a link to the update module in the sidebar of the backoffice.

**Comment by xarly111** [comment]
![Captura](https://github.com/user-attachments/assets/de33de7c-66a7-4925-ab85-3d7110358300)

Hello! I have tried to access the module from the module manager, but it also remains blocked. It is the only module that does not work correctly. I attach a screenshot of the console. Can you help me? I'll be waiting. Thanks

**Comment by M0rgan01** [comment]
@xarly111 

https://github.com/user-attachments/assets/d6be6cf9-938b-4841-a2a9-9564c84bc9f9

after a test on the version in question no problem accessing the module. If the module still poses a problem, you must uninstall and delete it, then do a clean installation. There may have been a problem during initial installation.

if the problem persists, you should send us a screenshot of the network tab, as in the video
