### ISSUE TITLE
Language selector installed but nothing displayed

### ISSUE THREAD

**Issue by cesar-lizurey** [PrestaShop/PrestaShop#37093]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have installed a dockerized Prestashop (https://devdocs.prestashop-project.org/8/basics/installation/environments/docker/), everything is working fine. I have clients from several countries, so I decided to install a language selector. But nothing shows in the menu.

### Expected behavior

I expect to have a sort of drop down menu with flags and language names at the top.

I also expect to have a "settings" options on the module but I can only deactivate, reinitialize or uninstall it.

### Steps to reproduce

Activate several languages in the admin panel.

Activate the language selector module in the admin panel.

Check the logs and see:

`Could not write into module folder: /var/www/html/app/../modules/ps_languageselector/vendor`

If I change the rights (setting to 777), I don't get this error, I have this info: `Protect vendor folder in module ps_languageselector` in the logs but still nothing appears.

### PrestaShop version(s) where the bug happened

8.2.0

### PHP version(s) where the bug happened

8.1.30

### If your bug is related to a module, specify its name and its version

ps_languageselector v2.1.3

**Comment by cesar-lizurey** [comment]
I'm using the theme: Classic Version 2.1.3

**Comment by cesar-lizurey** [comment]
When I go in the admin menu, I can select the module but nothing appears

![image](https://github.com/user-attachments/assets/559199b4-c6cd-45ae-9a18-5ebaaefa79d6)

I have to manually "greffe" the module here:

![image](https://github.com/user-attachments/assets/7f841103-266b-464a-aea9-c87f58160f2a)


Then it appears:

![image](https://github.com/user-attachments/assets/3ef27fbc-baf4-4a41-aabb-c552385157f1)

But without the flags...

**Comment by cesar-lizurey** [comment]
I have a lot of templates, maybe that's the problem:
```

sudo find / -name ps_languageselector.tpl
/var/lib/docker/overlay2/8b6f28e0e848a93ba19dee4370ff0645d980c19df0a0950e20137231d0304a77/merged/tmp/data-ps/prestashop/modules/ps_languageselector/ps_languageselector.tpl
/var/lib/docker/overlay2/8b6f28e0e848a93ba19dee4370ff0645d980c19df0a0950e20137231d0304a77/merged/tmp/data-ps/prestashop/themes/classic/modules/ps_languageselector/ps_languageselector.tpl
/var/lib/docker/overlay2/8b6f28e0e848a93ba19dee4370ff0645d980c19df0a0950e20137231d0304a77/merged/var/www/html/modules/ps_languageselector/ps_languageselector.tpl
/var/lib/docker/overlay2/8b6f28e0e848a93ba19dee4370ff0645d980c19df0a0950e20137231d0304a77/merged/var/www/html/themes/classic/modules/ps_languageselector/ps_languageselector.tpl
/var/lib/docker/overlay2/06ef601444cd777cb214d5b06b27ea43bd0e2e5b43c07fab3d79c459cc01429c/diff/tmp/data-ps/prestashop/modules/ps_languageselector/ps_languageselector.tpl
/var/lib/docker/overlay2/06ef601444cd777cb214d5b06b27ea43bd0e2e5b43c07fab3d79c459cc01429c/diff/tmp/data-ps/prestashop/themes/classic/modules/ps_languageselector/ps_languageselector.tpl
/var/lib/docker/overlay2/06ef601444cd777cb214d5b06b27ea43bd0e2e5b43c07fab3d79c459cc01429c/diff/var/www/html/modules/ps_languageselector/ps_languageselector.tpl
/var/lib/docker/overlay2/06ef601444cd777cb214d5b06b27ea43bd0e2e5b43c07fab3d79c459cc01429c/diff/var/www/html/themes/classic/modules/ps_languageselector/ps_languageselector.tpl
/var/lib/docker/volumes/prestashop_psdata/_data/modules/ps_languageselector/ps_languageselector.tpl
/var/lib/docker/volumes/prestashop_psdata/_data/themes/classic/modules/ps_languageselector/ps_languageselector.tpl
/home/tools/prestashop/modules/ps_languageselector/ps_languageselector.tpl
```

Maybe I shouldn't have installed the module as it already existed in the classic theme?

**Comment by florine2623** [comment]
Hello @cesar-lizurey ,

I have created a PS 8.2.0 using docker. 
The installation went well, when I check the FO, the language selector is well displayed. Module version is the same as you : Language selector block v2.1.3.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
