### ISSUE TITLE
Error when advanced stock management is enabled

### ISSUE THREAD

**Issue by alexandrebak42** [PrestaShop/PrestaShop#37100]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

There is a bug with products using advanced stock management.
In Checkout page if the cart contains a product with this option enabled there is a warning and the submit button in payment section throw a js error from core.js.

Here is the warning :
![image](https://github.com/user-attachments/assets/f16282a5-dae1-4d9b-a50c-1d3b8c28065b)

And here is the code responsible of this :
![image](https://github.com/user-attachments/assets/c0ab0dd3-1a5c-4372-a3af-418923c65c74)

The function Shop::getGroupFromShop($id_shop); return the id_group and not an array.

I will create a PR to fix this issue.

### Steps to reproduce

1. Enable stock management in BO Shop parameters > Products
2. Enable advanced stock management in a product configuration page (in combinations tab)
3. Add this product to the cart in FO
4. Continue in the checkout page and try to order the cart

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

Coquille

**Comment by alexandrebak42** [comment]
Here is the PR => #37102

**Comment by florine2623** [comment]
Hello @alexandrebak42 ,

Could you specify exactly what configuration should be done in step 2 ?

Waiting for your feedback.
Thanks!
