### ISSUE TITLE
Issue with XML loader during module installation

### ISSUE THREAD

**Issue by alainduchateau** [PrestaShop/PrestaShop#37106]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When our team try to update / install some modules, the file"XmlFileLoader.php".

![xmlError](https://github.com/user-attachments/assets/d4f9edae-ee88-48e7-8fc8-ef72f25f4ed4)

Sometimes it's produced on an 'system' xml file, sometimes on modules files..it's really strange.

In all cases, the stack trace is the same : 
[errorLog.txt](https://github.com/user-attachments/files/17290096/errorLog.txt)

To avoid the error, we have temporarly added a "return true" in the line 567.

To be complete, all the cache are flushed to avoid side effects.

### Expected behavior

Update or install a plugin seamlessly :-)

### Steps to reproduce

Install or update any modules of Prestashop

### PrestaShop version(s) where the bug happened

1.7.7.7

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment]
Hello,

PrestaShop 1.7 is no longer officially maintained, only for security issues.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
