### ISSUE TITLE
 SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'field list' 

### ISSUE THREAD

**Issue by uruk-hai-21** [PrestaShop/PrestaShop#37111]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In logs page I have this:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'field list'

what could it depend on?

### Steps to reproduce

Add a new address in frontend in order step

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.1.28

**Comment by florine2623** [comment]
Hello @uruk-hai-21  

Following your step, I couldn't reproduce your issue.
I followed an order creation process and added a new address in FO. Once the order confirmation is done, I searched in the log for the same error as you. The error is not present.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
