### ISSUE TITLE
Displaying codes ean13, isbn etc. in the product card (FO) for a given combination

### ISSUE THREAD

**Issue by Fera** [PrestaShop/PrestaShop#37110]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

It seems to me that there is a bug in displaying ean13, isbn etc. codes for products with combinations. There are no variables that would call these codes for individual combinations. You can only call the main code given in the Details tab. However, you cannot call codes entered in the Combinations tab (for a given combination) on FO. But maybe I am wrong.

### Expected behavior

When I enter the ean13 code in a given product combination (BO Combinations tab), this code will be displayed after selecting the product variant on FO

### Steps to reproduce

1. Create a product with combinations
2. Enter the EAN code in the Details tab
3. Enter different EAN codes in the combinations (one code for one combination)
4. Check on FO in the template that shows the EAN codes what code is displayed after selecting different combinations of a given product.

(The same one is always displayed - entered in the Details tab, not the one entered in the Combinations tab for a given product combination)

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.1

**Comment by florine2623** [comment]
Hello @Fera ,

Your issue is similar to https://github.com/PrestaShop/PrestaShop/issues/36443

I'm closing it, in order to avoir clogging the backlog.

Thanks!
