### ISSUE TITLE
Save Button and Related Products Suggestion Not Working After Upgrade from 8.1.5 to 8.2.0

### ISSUE THREAD

**Issue by EmmaPal** [PrestaShop/PrestaShop#37129]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After upgrading from PrestaShop 8.1.5 to 8.2.0, the "Save" button on the new product page in the back office no longer works. Additionally, the product suggestion feature (related products) also fails to function. Also tested with creating new product, and tested with all fields.
However, the site operates correctly in a local environment, and these issues only occur on the live server (!!!!??).
(I tried to enable Cloudflare Dev mode, with emptying all caches, with purging the CDN of ovh. and with different browsers but not result)
![Capture d'écran 2024-10-12 103913](https://github.com/user-attachments/assets/c1538d59-33b7-412e-9872-c3f9e712b716)

### Expected behavior

The "Save" button should work and save the product changes. The product suggestion feature should display related products.

### Steps to reproduce

1. Go to the back office product page.
2. Attempt to create or edit a product.
3. Click the "Save" button — no response.
4. Try to use the related product suggestion feature — it does not display any suggestions.

### PrestaShop version(s) where the bug happened

8.2.0

### PHP version(s) where the bug happened

8.1

**Comment by EmmaPal** [comment]
**Problem resolved: Emptying the cache of cloudflare resolves the problem**

**Comment by florine2623** [comment]
Thanks for letting us the the solution of your issue. That's a good news !
