### ISSUE TITLE
The PayPal module does not work with the recovery cart and causes other payment modules to malfunction

### ISSUE THREAD

**Issue by danbenoit** [PrestaShop/PrestaShop#37126]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When paypal is not working correcly other integrated payment method are not working. 

When the customer is login or paypal is working no problem 
![Capture d'écran 2024-10-11 214746](https://github.com/user-attachments/assets/8fdc5d3a-311b-4d31-baa4-4c53938f6d27)
But when paypal is not working or when the customer is not login with the recovery cart link paypal is not showing and it cause not working stripe module (integrated form not showing and not possible to validate the order) 
![Capture d'écran 2024-10-11 215005](https://github.com/user-attachments/assets/fbce53d6-3d59-4c24-93e0-a515ec84b421)
 
So to use paypal it's necessary to have a login customer? It's not possible to use the id of the recovery cart to use the customer session? 
And why other integrated module don't because of paypal malfunction? 

### Steps to reproduce

1/ create a cart 
2/ send the link to the customer (or use it to use this cart)
3/ if paypal and stripe are activated and the customer not login => not working 
4/ if the customer is login it's working 

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

7.4

**Comment by florine2623** [comment]
Hello @danbenoit ,

I have tested to reproduce your issue with PrestaShop native payment modules. But I can't, when I create an order and send the link to the customer, the payment methods are displayed in FO whether the customer is logged in or not.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Or you can contact the developer of the module directly.

Thank you
