### ISSUE TITLE
Create the v9 branch

### ISSUE THREAD

**Issue by ibahloul-ps** [PrestaShop/PrestaShop#37139]
We want to create the v9.0.x branch. After creating it, we need to acknowledge a new branch has been created, this means:
- we need to build a nightly docker image for 9.0.x
- we need to update some CI jobs to acknowledge 9.0.x -> see https://github.com/PrestaShop/PrestaShop/tree/develop/.github/workflows
- we need to update some github templates -> see https://github.com/PrestaShop/PrestaShop/tree/develop/.github
- kanbanbot must be updated -> see https://github.com/PrestaShop/kanbanbot/pull/54

Don't hesitate to ask around 😄 to complete this list

At the end, create a new page here https://www.prestashop-project.org/maintainers-guide/processes/ to document this process
-> code for this website is here https://github.com/PrestaShop/open-source/

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/open-source/pull/275/
