### ISSUE TITLE
Permission denied during installation under Windows

### ISSUE THREAD

**Issue by musicpanda** [PrestaShop/PrestaShop#37143]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When installing Prestashop under Windows it unpacks the files and then produces the error:
`Warning: rename(C:\xampp81\htdocs\index.php.temp,C:\xampp81\htdocs\index.php): Access denied (code: 5) in C:\xampp81\htdocs\index.php on line 1338
{"error":false,"numFiles":28610,"lastId":29000}`

The relevant code is
`    if ($lastId >= $numFiles) {
        unlink(getcwd() . '/index.php');
        unlink(getcwd() . '/prestashop.zip');
        rename(getcwd() . '/index.php.temp', getcwd() . '/index.php');
    }`

The problem happens during the rename. 

When you look in the file system index.php has been deleted. When you manually rename index.php.temp to index.php you can continue the installation.

This problem appeared somewhere during PS 8.1. As the relevant Prestashop code doesn't seem to have changed since version 7.6 it may be that Windows has changed its file handling.

I tried replacing 'rename' with 'copy' and inserting a sleep() command before the rename but these don't work. I suspect that Windows when renaming or overwriting the file that is running at the moment delays the actual deletion until the file is no longer in use.

### Expected behavior

a fluent installation

### Steps to reproduce

Install Prestashop under Windows

### PrestaShop version(s) where the bug happened

8.2.0

### PHP version(s) where the bug happened

8.1

**Comment by musicpanda** [comment]
Here a picture
![ps820](https://github.com/user-attachments/assets/9574e901-8a60-47fb-a67b-73959818072a)

**Comment by musicpanda** [comment]
I did a test. I renamed index.php as installer.php and reduced the code content of index.php to 
`header("Location: installer.php");`

That indeed solves the problem.

**Comment by florine2623** [comment]
Hello @musicpanda ,

Windows is not maintained actively anymore. As you have fixed your issue, I will close it to avoid clogging the backlog.
If anything else happens, feel free to open a new issue.

Thanks!

**Comment by musicpanda** [comment]
I beg to disagree. Renaming a file while it is being executed is just dirty programming. The fact that it works at the moment under Linux but not under Windows should not be an excuse not to fix this.
