### ISSUE TITLE
Old translation system for modules is causing error 500 (isUsingNewTranslationSystem = false)

### ISSUE THREAD

**Issue by ShaiMagal** [PrestaShop/PrestaShop#37144]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you try to translate module with isUsingNewTranslationSystem = false you got error 500. Check screenshot.
![Untitled](https://github.com/user-attachments/assets/35b83781-8933-41e8-aed2-8915d5af4f35)

### Expected behavior

It should work like expected (there should be compatiblity with old translation system - check source base, there is compatibility - `./classes/module/Module.php + ./controllers/admin/AdminTranslationsController.php + ./controllers/admin/AdminModulesController.php` ).

Or at least there should be "friendly" message, not 500. I prepare test module for this testing purpose.

### Steps to reproduce

0. enable debug mod
1. go to section modules
2. upload this module ([shaim_test_translation.zip](https://github.com/user-attachments/files/17367077/shaim_test_translation.zip))
3. go to module configuraiton
4. click on translate 
5. you will see 500 error

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.3

### Your company or customer's name goes here (if applicable).

https://www.openservis.cz/

**Comment by florine2623** [comment]
Hello @ShaiMagal ,

I have reproduced your issue !

Thanks for the report ^^

**Comment by kpodemski** [comment]
@florine2623 I think it's a Major one as there's no workaround and impacts most of the modules in the ecosystem

We have to consider what to do because the old translation system is no longer in place in PrestaShop 9, and developers have to migrate to the new one. It's just yet another BC Break coming from changes in PrestaShop 9.

**Comment by ShaiMagal** [comment]
Fixed by PR #37220
