### ISSUE TITLE
Feature flag Carrier page - Exception displayed when deleting a range for a specific zone

### ISSUE THREAD

**Issue by florine2623** [PrestaShop/PrestaShop#37151]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have an exception when I edit my carrier by deleting ranges for zones and Saving empty ranges.

https://github.com/user-attachments/assets/785e0921-f780-444a-974d-61b71329c3a4

<img width="1436" alt="Screenshot 2024-10-15 at 15 06 11" src="https://github.com/user-attachments/assets/f3f13774-40d1-4518-80c7-2e17bc11754e">

### Expected behavior

Exception should not be displayed

### Steps to reproduce

1. Go to BO > Shipping > Carriers
2. Add new carrier : add name, transit time, group access
3. Go to tab Shipping, location and costs
4. Add Zones : Africa, Asia
5. Choose any tax
6. Click on Manage ranges
7. Add a correct range (ex: 12 - 14) > Apply
8. Add a price on both Zones > Save
9. Successful creation
10. Click on Manage ranges > Click on Trash icon action button > Click Apply
11. Save > See exception `"" cannot be interpreted as a number` :x:

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.1

**Comment by ingridusta** [comment]
Hello @florine2623, 

I reproduce the issue with PrestaShop version 9.0.x, I'll add this to the backlog so it can be fixed.
![Capture d’écran 2024-10-16 à 14 51 12](https://github.com/user-attachments/assets/beffce3c-99e1-4d00-8eb5-59edbce49944)

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you
