### ISSUE TITLE
Experiment on hook contribution by following the documentation page then update it accordingly to fill in the gaps

### ISSUE THREAD

**Issue by ibahloul-ps** [PrestaShop/PrestaShop#37162]
We plan to perform a little experiment on hooks contribution. Before asking for contributions on this topic, we need to ensure that [this documentation](https://devdocs.prestashop-project.org/8/development/components/hook/register-new-hook/) allows any developer to independently contribute 💪 , without specific knowledge.

## We asked someone to attempt to add a hook following the doc, and here is the feedback we got

1. It is not clear that this page only works on a specific version of the Core
2. The link for the XML file update could be improved https://github.com/PrestaShop/PrestaShop/pull/34431/files#diff-83f4085b0cf6d3684a214fdffee7ec16b2f967d60a2674a7d4a536a2898eee26
3. Missing link from the doc to GitHub
4. Missing guidelines for naming the hook
5. Confusing how to install upgrade module

## Next step: update the documentation to make it better

**Comment by kpodemski** [comment]
better URL: https://devdocs.prestashop-project.org/8/contribute/contribute-pull-requests/add_hook/

those two pages are too similar, content should be more precise

**Comment by matks** [comment]
@kpodemski Argh :( yeah looks like a duplicate devdocs page

I will try merging them

**Comment by matks** [comment]
Fun fact: I tried to merge them yesterday and failed because of my laptop ran out of available disk space

Was not expecting this 😄

**Comment by matks** [comment]
Will be fixed by https://github.com/PrestaShop/docs/pull/1898/

**Comment by matks** [comment]
> better URL: https://devdocs.prestashop-project.org/8/contribute/contribute-pull-requests/add_hook/
> 
> those two pages are too similar, content should be more precise

Better late than sorry https://github.com/PrestaShop/docs/pull/1899 this is the PR to merge the two pages
