### ISSUE TITLE
impossible to create an order from backoffice : no name in the customer list while customer exists

### ISSUE THREAD

**Issue by MusikMachineMan** [PrestaShop/PrestaShop#37166]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello all,
Here is my problem :
When i try to create an order from backoffice i'm facing an issue as there is no list with customers after typing few characters, and even when typing the complete name...
on Debug mode, Console makes me understand that customers are well found but not shown.
It seems to be related with Symfony\Component\Serializer\Encoder but my knowledge reached its bounds !!

i tried to delete the cache, but there is no changes...

![bug_search_customer](https://github.com/user-attachments/assets/804b25dc-55dd-4de6-b710-1f8135c04127)
![bug_search_customer1](https://github.com/user-attachments/assets/50ed6543-df76-4126-b0a0-6e7d0a06c322)
![bug_search_customer2](https://github.com/user-attachments/assets/00688865-d1e2-4697-892e-8d206bca4fd2)
![bug_search_customer3](https://github.com/user-attachments/assets/2df45887-1d2c-421f-90c5-0b8e3d04eb78)

Help would be really appreciated if anyone could understand what's happening and help to solve it
Thanks in advance

### Expected behavior

i just want to find the customer i need so as i could create an order with

### Steps to reproduce

Go to Orders
Click on '+Create an Order'
Type 1st letters of the Customer name

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.3

**Comment by florine2623** [comment]
Hello,

I couldn't reproduce your issue with more recent version. 



https://github.com/user-attachments/assets/5e782871-50d0-41b0-b44f-4f8beed0427b





We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
