### ISSUE TITLE
Google analytics create error 502 bad getaway

### ISSUE THREAD

**Issue by Giorgiomezzo** [PrestaShop/PrestaShop#37170]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

when i add more of two products in the cart then in the last step of check out when ι should confirm the order i take white page with 502 error bad getaway .
when i disable the module "google analytics" from prestahsop then the error disapeared.
![ONE21](https://github.com/user-attachments/assets/00c78030-0038-49c6-b522-351055ed6eb9)

### Steps to reproduce

i enable the free module of prestashop "google analytics" then i refresh the settings then click "save" and i go in the front office to create a test order.
when i add more of two products in the cart and begin the steps for checkout  then in the last step that we click to confirm the order i take white page with error 502 bad getaway .
if i disable the google analytics then everything works fine .

### PrestaShop version(s) where the bug happened

8.2

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

prestashop google analytics v5.0.2

**Comment by florine2623** [comment]
Hello @Giorgiomezzo ,

I followed your steps to reproduce your issue but I can't.
This is most probable a server issue. I suggest contacting your hosting provider.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by Hlavtox** [comment]
@kpodemski @ShaiMagal 99% sure it's apache max header overflow due to cookie

**Comment by Giorgiomezzo** [comment]
> [@kpodemski](https://github.com/kpodemski) [@ShaiMagal](https://github.com/ShaiMagal)99% βέβαιο ότι πρόκειται για υπερχείλιση κεφαλίδας max apache λόγω cookie

thank you very much for your reply . please tell me if you know how to solved it ?
