### ISSUE TITLE
Missing/Incorrect CSS for div "carrier-extra-content" - hook "displayCarrierExtraContent"

### ISSUE THREAD

**Issue by ShaiMagal** [PrestaShop/PrestaShop#37194]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If any module add text to "carrier-extra-content" via hook "displayCarrierExtraContent", it's not stylled properly. Especially on mobile, it's broken. Check screenshot.
3 problems:
A) it's not aligned properly (because missing "margin: auto;" like for element "delivery-option")
B) unnecessary (not connected) dash to the right
C) it is not indented from the bottom, then it looks like part of the note.
![Untitled](https://github.com/user-attachments/assets/cbf12888-a71f-4f32-8483-8f9d4a516fda)

### Expected behavior

It must be aligned and working well. There is more options how to fix, but I am not front end developer.

Maybe @tblivet is a suitable candidate for fix (PR)? :)

### Steps to reproduce

1. open website https://demo.prestashop.com/#/en/front and click click click to order section "3" - shipping method
2. open JS konzole (F12)
3. fill there "$('.carrier-extra-content').text('Lorem ipsum dolor sit amet.');" and press enter
4. you will see results

You can make module for this purpose as well, but this is faster and easier.

### PrestaShop version(s) where the bug happened

8.2.0

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

https://www.openservis.cz/

**Comment by florine2623** [comment]
Hello @ShaiMagal ,

I have reproduced your issue with PS 8.2.0 and 9.0.x, I'll add this to the backlog so it can be fixed.

<img width="307" alt="Screenshot 2024-10-21 at 13 53 55" src="https://github.com/user-attachments/assets/8e12fdb4-d5c2-4f28-99b0-e0bdc1268018">

Please be aware that some issues might take a very long time to be resolved. If this one is important to you and you cannot wait for it to be fixed on the project’s own time, we strongly suggest you consider [contacting a professional](https://www.prestashop-project.org/support/) to help you. 

If you fix the issue on your end, please [contribute it back to the project](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/). Remember that the more people contribute, the better PrestaShop becomes for everyone.

Thank you

**Comment by ShaiMagal** [comment]
Fixed already by https://github.com/PrestaShop/classic-theme/pull/157, so closing :) Thanks @tblivet
