### ISSUE TITLE
garagetechpro.com

### ISSUE THREAD

**Issue by PBQPGB** [PrestaShop/PrestaShop#37207]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Impossible de ce connecter à la page de ce professionnel chez qui j'ai passé commande.

### Expected behavior

Ouverture de la page.

### Steps to reproduce

ERR_NAME_NOT_RESOLVED

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

8.0

### If your bug is related to a module, specify its name and its version

p

### Your company or customer's name goes here (if applicable).

GARAGETECHPRO.COM

**Comment by PBQPGB** [comment]
Voici le numéro de ma commande passée chez ce pro : XTIGVVLER

[#FA000490.pdf](https://github.com/user-attachments/files/17464297/FA000490.pdf)

**Comment by kpodemski** [comment]
Hello @PBQPGB 

Please use English to describe your problem, if the problem is not related to the PrestaShop core then it's better for you to search for an answer elsewhere, for example on the [official PrestaShop forum](https://www.prestashop.com/forums).
