### ISSUE TITLE
email

### ISSUE THREAD

**Issue by Eurovisionopticos** [PrestaShop/PrestaShop#37206]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When there is a new order, I do not receive the new order notification email. But I do receive notification of the stock and on both sites I have the email almacen@eurovisionopticos.com

### Steps to reproduce

![pedidos](https://github.com/user-attachments/assets/f9343b7a-441b-4478-b7c7-3af39c02a841)

### PrestaShop version(s) where the bug happened

8.1.4

### PHP version(s) where the bug happened

8.1.4

### If your bug is related to a module, specify its name and its version

Email Alerts v3.0.0 - de PrestaShop

### Your company or customer's name goes here (if applicable).

Eurovision Opticos

**Comment by Hlavtox** [comment]
Missing email templates in `modules/ps_emailalerts/mails/it`, regenerate it in backoffice.
