### ISSUE TITLE
 1-Click Upgrade in local directory not works

### ISSUE THREAD

**Issue by Loristop** [PrestaShop/PrestaShop#37213]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

 1-Click Upgrade in local directory not works (/admin/autoupgrade/latest/) not save impostation. 
![Schermata a 2024-10-22 10-07-38](https://github.com/user-attachments/assets/c6234c8e-77fd-403f-8c72-3c25438c4673)
![Schermata a 2024-10-22 10-07-49](https://github.com/user-attachments/assets/2461d3e2-b117-4f2a-bc9b-64948534df9c)

### Steps to reproduce

1) I uploaded the prestashop 8.1.0 version to the directory: /admin/autoupgrade/latest/
2) I made the shop eligible for the update
3) after a previous failed test I reinstalled the entire shop from scratch (database and files) and tried again but I still can't save the settings to proceed with the update to the next version of prestashop

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

1-click upgrade version 6.0.2

### Your company or customer's name goes here (if applicable).

Kolyne

**Comment by Quetzacoalt91** [comment]
If you want to upgrade to the version 8.1.0, I would recommend the `archive` channel instead.

Keep your zip file as-is and upload it in the folder `admin/autoupgrade/download`, then add this XML file in the same folder: https://api.prestashop-project.org/assets/prestashop/8.1.0/prestashop.xml

By configuring the XML file in the process, you will make sure the obsolete files are properly deleted.

PS: The `directory` option will be deleted from the v7 of the module.

**Comment by AureRita** [comment]
Hi @Loristop 

Did the answer of @Quetzacoalt91 help you in your issue ? 

Waiting for your feedback

**Comment by Quetzacoalt91** [comment]
In addition to my previous message, a bug preventing the use of "Local directory" is fixed with the release of the v6.3. Update the module and you should be good to go.
