### ISSUE TITLE
Autoupgrade - A 500 internal server error when confirm order in any shop upgraded from  1.7.7 or 1.7.6 to 1.7.8.11 and 8.2.0

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#37224]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,
A 500 internal server error when confirm order in any shop upgraded from  1.7.7 or 1.7.6 to 1.7.8.11 and 8.2.0
and an error when edit the quantity of product in order page

https://www.awesomescreenshot.com/video/32819214?key=5811fb59e19580dc6a5ca8f5b6d00537

![Image](https://github.com/user-attachments/assets/9e5469db-d62f-4ea0-9103-652b1faadef0)

![Image](https://github.com/user-attachments/assets/73e87fab-4bbd-4302-8bd3-00682555521a)

### Expected behavior

No error

### Steps to reproduce

1- Install 1.7.7.0
2- Upgrade to 8.2.0 or 1.7.8.11
3- Login and go to Orders page
4- Go to the first order and edit product quantity
5- See the error
6- Go to FO and create an order
7- See the error

### PrestaShop version(s) where the bug happened

8.2.0 or 1.7.8.11

### PHP version(s) where the bug happened

7.1 - 7.2 - 7.3

### If your bug is related to a module, specify its name and its version

autoupgrade

**Comment by AureRita** [comment]
Hi @nesrineabdmouleh ,

Thank you for your report, I reproduce the issue with PrestaShop version 1.7.7.5 as you can see : 


https://github.com/user-attachments/assets/0c3f1034-0cf0-4bbe-bf4a-89bb66e3cbef



Please be aware that some issues might take a very long time to be resolved.

Thanks

**Comment by Quetzacoalt91** [comment]
@nesrineabdmouleh What is the related PHP error in your server logs? Or when you enable the dev mode? It helps understanding what the error is immediately.

**Comment by Hlavtox** [comment]
@AureRita @nesrineabdmouleh :-)

> Avoid reporting "error 500" or "white page" errors - this is a universal error message that does not provide enough information to qualify the issue. Enable debug mode in the Performance section of PrestaShop or manually in /config/defines.inc.php and try again. You should get a proper error message.

**Comment by AureRita** [comment]
Hi @Quetzacoalt91 

First of all, we can see on the screenshot of @nesrineabdmouleh that we "could not update order invoice in database" 
and at the end of my video, we see : 
"Unknows column "note" in "field list"
At 1:12 

I expect that this type of rerror help you

**Comment by M0rgan01** [comment]
![Image](https://github.com/user-attachments/assets/c6f2d1ee-1d4a-47e5-97a8-800d28f03691)

**Comment by Quetzacoalt91** [comment]
> ![Image](https://github.com/user-attachments/assets/c6f2d1ee-1d4a-47e5-97a8-800d28f03691)

@AureRita this was the kind of details I was talking about. It helps us understanding in this case what's the culprit. I did not go this far in the video and it was visible in there, sorry.

**Comment by M0rgan01** [comment]
Lie !

![Image](https://github.com/user-attachments/assets/f4584375-1aca-46f7-8944-e9dc3c74a0b1)
