### ISSUE TITLE
Problem with the Activity Dashboard

### ISSUE THREAD

**Issue by nodjo0503** [PrestaShop/PrestaShop#37225]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

I have a problem with the Activity Dashboard module. I contacted PrestaShop because I couldn't see the number of visitors on my website. The advisor told me I needed to install Google Analytics, which I did, but I didn't feel like it was working. I called again, and now I'm being told that it's a problem with the Activity Dashboard module. Can you help me?

### Expected behavior

I want to be able to see the number of visitors on my site, and I need clear instructions on what to do.

### Steps to reproduce

I don't have steps

### PrestaShop version(s) where the bug happened

1.7.7.2

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

the Activity Dashboard v2.1.1

### Your company or customer's name goes here (if applicable).

NODJO ou NOEMIE THACE

**Comment by florine2623** [comment]
Hello @nodjo0503 ,

I can't reproduce your issue with Dashboard Activity v2.1.1 and PS 9.0.x.


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
