### ISSUE TITLE
Display voucher amount in cart

### ISSUE THREAD

**Issue by darch59** [PrestaShop/PrestaShop#37227]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello

I am having a problem with displaying the voucher amount in the basket when a product is already discounted.
The amount of the reduction that is displayed is calculated on the price of the non-discounted product.

![Image](https://github.com/user-attachments/assets/b7307051-7e3e-451d-bcf2-392adb620583)

Here is how the voucher is set up.

![Image](https://github.com/user-attachments/assets/cc290956-2f3a-498e-9556-97482d8a83a1)
![Image](https://github.com/user-attachments/assets/23623be4-eee2-4b72-bef4-93f7927ad8eb)
![Image](https://github.com/user-attachments/assets/897ba122-7fac-4d43-9f6b-ec8448c9f528)

It seems that the "Selected products" option is the problem.
Do you have any idea how to fix this please?

I tested on version 8.0.5 and 8.1.0.
The problem doesn't seem to occur on 1.7.

Thank you

### Steps to reproduce

1. Add a discounted product in the cart
2. Create a voucher applicable only to this product
3. Apply the voucher in the cart

### PrestaShop version(s) where the bug happened

8.0.5,8.1.0

### PHP version(s) where the bug happened

7.4.33

**Comment by florine2623** [comment]
Hello @darch59 ,

Your issue is the same as : https://github.com/PrestaShop/PrestaShop/issues/37148

So I'm closing it to avoid clogging the backlog.

Thanks!
