### ISSUE TITLE
Remove all assets loaded from external CDN sources, use the assets built in the module only

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#37237]
- [ ] Make sure the Vue app used is the one built in the module, not one from an outside source
- [ ] Make sure the module homepage works correctly, that all blocks are filled with their proper API and no error 404 is seen on the homepage
- [ ] Understand the `npm run dev` script and the Graphql endpoint
- [ ] Test the interface to see if it works

**Comment by Hlavtox** [comment]
@jolelievre Hello. Sorry, but this doesn't belong to the open source project.

This repository is intended to manage the **open source part of the project**, not **private activities of PrestaShop company**.

Please manage it in somewhere else. Thank you.

**Comment by jolelievre** [comment]
We don't have other tools to handle our project tasks, is it that bothersome for you honestly?

If it is you can simply ignore these issues, please don't close them It will only make us lose time, which in return will prevent us from investing time on topics that you are interested in
