### ISSUE TITLE
Integrate links in the installation footer

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#37245]
Thanks to the feature introduced with this improvement we can integrate some specific links in the footer for the classic edition https://github.com/PrestaShop/PrestaShop/pull/36726

The links to be added are these ones https://github.com/PrestaShopCorp/smb_edition_fork/blob/cd0ada06e8fc5f1a76261cd483861cb04770d0f8/install-dev/theme/views/footer.php 

The labels should rely on `trans` method instead of hard coded switch

**Comment by Hlavtox** [comment]
@jolelievre Hello. Sorry, but this doesn't belong to the open source project.

This repository is intended to manage the **open source part of the project**, not **private activities of PrestaShop company**.

Please manage it in somewhere else. Thank you.
