### ISSUE TITLE
Translating the settings in the wrong language

### ISSUE THREAD

**Issue by ewonta** [PrestaShop/PrestaShop#37254]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On the customer settings page, the setting "Re-display cart at login" is translated into Ukrainian. It is the only setting with an incorrect translation, which causes confusion for new customers when the admin panel interface is set to Russian, as all other settings are in Russian.

If it’s not possible to translate it into Russian, it would be better to leave it in English.

![Image](https://github.com/user-attachments/assets/c5436c25-a284-4f67-a3d2-e0923dd8fd14)

### Expected behavior

Translation into Russian, or the default language is English

### Steps to reproduce

1. Add Russian language  
2. Switch the admin to Russian  
3. Go to Shop Parameters -> Customer Settings

### PrestaShop version(s) where the bug happened

8.1.7

**Comment by florine2623** [comment]
Hello @ewonta ,

You can update the translation directly in the BO in International > Translation > Modify translation : Back-office translation and Russian. And edit it to the correct language.


Here's an example in English :
![Image](https://github.com/user-attachments/assets/3567eb18-3106-4b7a-9cf5-8e1358f51d16)


Or you can change it here so all the PrestaShop community can benefit from it : https://crowdin.com/project/prestashop-official
