### ISSUE TITLE
Modules Page is not up to date after disabling/enabling a module with API

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#37253]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

* I enable / disable a module with API
* The BO is not synced with modules states

### Expected behavior

* I enable / disable a module with API
* The BO is synced with modules states

### Steps to reproduce

1. Go to BO
2. Go to Modules
3. Check that `blockwishlist` is enabled
4. Create a API key (scope : `module_write`) 
5. Request an access_token
6. Request the endpoint for disabling the module (Response 🆗 )
![Image](https://github.com/user-attachments/assets/7965da15-90e3-4c1e-8c01-e062aeda3628)
![Image](https://github.com/user-attachments/assets/d6492221-0b8b-42c6-a8c9-868018e7e90f)

7. Refresh the BO
8. The module `blockwishlist` is always enabled

### PrestaShop version(s) where the bug happened

9.0.x

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

**Comment by Hlavtox** [comment]
@jolelievre This is the cache problem that I was complaining many times.

- You do anything with a module programatically, you can't see it in BO.
- You upload a new module manually to FTP, you can't see it in BO.
