### ISSUE TITLE
Categories Image - WebP images are not generated for each image type

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#37282]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After #30520, categories images thumbnail are well generated in **jpeg** (but not in **webp**).

### Expected behavior

Categories Image - WebP images are generated for each image type

### Steps to reproduce

1. login in BO
2. go to 'Design > Image Settings' page
3. enable WebP image format
4. go to 'Catalog > Categories' page
5. go to add new category page
6. create category
7. filter category by Name and fetch the ID (`idCategory`)
8. Images are present
    * 🟢  `img/c/idCategory.jpg` is present
    * 🟢  `img/c/idCategory_thumb.jpg` is present
    * for each image type categories (`imageTypeName`),
        *  🟢  `img/c/idCategory-imageTypeName.jpg` is present
        *  🔴  `img/c/idCategory-imageTypeName.jpg` is not present

### PrestaShop version(s) where the bug happened

9.0.x

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

**Comment by Hlavtox** [comment]
@Progi1984 This will fix the issue https://github.com/PrestaShop/PrestaShop/pull/37283

**Comment by Progi1984** [comment]
@Hlavtox 🤗
