### ISSUE TITLE
Refresh issue

### ISSUE THREAD

**Issue by Miestre** [PrestaShop/PrestaShop#37284]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I installed PrestaShop from scratch (version 8.2), but every time I refresh the page, it shows up and then disappears. Does anyone know why this is happening?

![Image](https://github.com/user-attachments/assets/2ed621e0-dc93-43c2-9a4c-658fc75cf07f)

### Steps to reproduce

refresh homepage in bowser and strge contet will show and disapear.

### PrestaShop version(s) where the bug happened

8.2

### PHP version(s) where the bug happened

8.2

**Comment by Miestre** [comment]
It’s the string of this icon that displays momentarily.

![Image](https://github.com/user-attachments/assets/b9763e1f-4d72-49d8-abb9-c7069456417f)

**Comment by florine2623** [comment]
Hello @Miestre ,

I can't reproduce this issue. 

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
