### ISSUE TITLE
PrestaShop 8.2.0 : Switch Theme Issue

### ISSUE THREAD

**Issue by Deltafox79** [PrestaShop/PrestaShop#37296]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I Have this issue..

On Prestashop 8.2.0 , new Installation ...

1) Import a New theme Compatible v8.2.0 and Working
2) I Try to return Classic Default Theme and I have this issue : 

![Image](https://github.com/user-attachments/assets/1b5c8d30-c9f9-4149-a264-199f0d8f2e52)

![Image](https://github.com/user-attachments/assets/33345d7d-83b4-4d66-836e-2842a045a3ef)

**Any Idea?**

### Steps to reproduce

1) fresh Installation of Prestashop 8.2.0
2) Install a New Theme v8.2.0 Compatible..
3) Try To Switch to Default Classic Theme

### PrestaShop version(s) where the bug happened

8.2.0

### PHP version(s) where the bug happened

8.1.30

**Comment by florine2623** [comment]
Hello @Deltafox79 ,

I uploaded 1 template compatible with 8.2.0 and 1 template that is obsolete. In both cases I did not have any issues nor exception displayed.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
