### ISSUE TITLE
Fix the onboarding component first step (association to account already checked) and check that the other steps work as expected

### ISSUE THREAD

**Issue by ibahloul-ps** [PrestaShop/PrestaShop#37290]
![Image](https://github.com/user-attachments/assets/288d6709-4f0b-4b79-82cf-9a889b317b36)

### Related PR
see https://github.com/PrestaShopCorp/ps_edition_basic/pull/10

**Comment by mattgoud** [comment]
PR in progress :
https://github.com/PrestaShopCorp/ps_edition_basic/pull/10
