### ISSUE TITLE
Bank Transfer Option Not Working in Shop

### ISSUE THREAD

**Issue by Andreyyuv** [PrestaShop/PrestaShop#37298]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Dear All![Image](https://github.com/user-attachments/assets/500d4521-c8d9-4d6d-b98a-a449bd8d9404)
![Image](https://github.com/user-attachments/assets/c4c899ed-681f-43e4-8519-de258b4edfc5)
,

We have an issue with the Bank Transfer module in our shop. Customers can't use it because the button doesn't work.

Please advise on a fix as soon as possible.

### Steps to reproduce

Navigate to the website: https://badmintonhandel.de/ .
Add items to the shopping cart.
Proceed to checkout.
Select 'Pay by Bank Transfer' as the payment method.

### PrestaShop version(s) where the bug happened

1.7.6.4

**Comment by florine2623** [comment]
Hello @Andreyyuv ,

I can't reproduce your issue with the module Bank transfer v2.2.0.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
