### ISSUE TITLE
probleme de téléchargement

### ISSUE THREAD

**Issue by prestoi** [PrestaShop/PrestaShop#37302]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Bonjour à tous,
Et bonne fêtes de tous les saints.
J'ai prestashop 1.7.8
j'ai ce message lorsque je veux télécharger un module :
Aïe... le chargement a échoué.
Que s'est-il passé ?
Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
Pouvez vous me dire si possible, s'il vous plait d’où cela provient ?
Bien cordialement

### Steps to reproduce

Bonjour à tous,
Et bonne fêtes de tous les saints.
J'ai prestashop 1.7.8
j'ai ce message lorsque je veux télécharger un module :
Aïe... le chargement a échoué.
Que s'est-il passé ?
Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
Pouvez vous me dire si possible, s'il vous plait d’où cela provient ?
Bien cordialement

### PrestaShop version(s) where the bug happened

1.7.8.0

**Comment by florine2623** [comment]
Hello @prestoi ,

This is a server issue.

Please contact your hosting provider and the support of the module to fix this issue.

I'm closing your issue. Thanks!
