### ISSUE TITLE
PS 8.1.7: catalog price rules disappear randomly

### ISSUE THREAD

**Issue by monak83** [PrestaShop/PrestaShop#37313]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi to all,
 I have a catalog price rules that add a 75% off discount to a user group called "customers B2B"  and I see discounts if I login with user assiciated at that group.
Sometimes (I think randomly) that discount disappears and I need to re-save rule to see on front office discounts
I'm on PS 8.1.7
Regards
Marco

### Expected behavior

discouts remains the same every day

### Steps to reproduce

1 . create a catalog price rule
2 . apply that rule to user group
3 . save rule
4 . discount appears on frontend
5 . discount disappear (randomly I think)

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

Marco

**Comment by florine2623** [comment]
Hello @monak83 ,

I can't reproduce your issue on my end. 
If I create a customer group, a catalog price rule linked to this customer group, I log into my customer who is in the customer group : the price displayed on the catalog in FO is correct. I always have the discount displayed.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by ComonSoft** [comment]
Hi, we also noticed this issue.

PS 8.1.7
PHP 7.2 / 7.3 / 7.4

**Steps to reproduce**

1. Rename default client group to B2B
2. Create customers assign to B2B group only and default B2B group
3. create a catalog price rule % reduction applied to B2B group
4. Connect as a customer
5. discount appears on frontend
6. Wait several days site working w/o any modifications
7. Connect as a customer
8. discount disappeared on frontend
9. Edit catalog rule, just save
10. discount appears on frontend

NB: very difficult to reproduce systematically, it looks like a cache rules issue may be. No errors in log files

**Comment by ComonSoft** [comment]
Please let it open, will try to give more context when it will happen again.
