### ISSUE TITLE
bug with wire payment

### ISSUE THREAD

**Issue by julie59850** [PrestaShop/PrestaShop#37321]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, I upgraded my prestashop from PS1.6 to 8.1, since then i have problem with the wire payment module. Instead of staying as 'pending payment" orders automatically go to 'remote payment accepted' and in the automatic mail sent to customers, there are no information concerning my bank account..
Does anyone know why ?
Thanks a lot

### Expected behavior

I expected the order to stay as "Pendind payment" as long as I did not receive the payment transfer

### Steps to reproduce

1. Client validate in order by choosing "wire payment"
2. The order is automatically accepted as "payment accepted"

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

7.2.34

### If your bug is related to a module, specify its name and its version

wire payment 2.2.0

### Your company or customer's name goes here (if applicable).

Hogen

**Comment by florine2623** [comment]
Hello @julie59850 ,

This is a public space. Please do not share your admin link to everyone. Please change it for security reasons.

Make sure that the option in `Shop parameters > Order Settings > Statuses` is unchecked like so :
![Image](https://github.com/user-attachments/assets/80e5d362-4ff7-4f90-8e3d-e5c6d4b530a9)


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

I'm closing your issue as it cannot be reproduced.
Thank you
