### ISSUE TITLE
Autoupgrade : A 500 internal servor error is displayed when rollback of 17811 to 1.7.3.1

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#37337]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, A 500 internal servor error is displayed when rollback of 17811 to 1.7.3.1 when debug mode is disabled and some worning when debug mode is enabled

https://github.com/user-attachments/assets/340e3794-f7da-42cf-b50a-b2a0023b273e

![Image](https://github.com/user-attachments/assets/a995c41a-a702-4834-b87d-8a58ee31febe)

### Expected behavior

No error after rollback

### Steps to reproduce

1. Install a docker image of ps 1.7.3.1
2. Upgrade to 1.7.8.11
3. Rollback
4. See the error

### PrestaShop version(s) where the bug happened

1.7.3.0-1.7.3.1-1.7.3.2-1.7.3.3-1.7.3.4

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

autoupgrade

**Comment by nesrineabdmouleh** [comment]
Hello, 
After the merge of this PR https://github.com/PrestaShop/autoupgrade/pull/997 we have a fatal error in the BO after rollback

![Image](https://github.com/user-attachments/assets/d283568d-9113-48c8-90d4-14cfcfac1f15)

**Comment by venditdevs** [comment]
A rollback of a backup through the one-click-upgrade never works correctly. For example, it does (or did) not delete added files. So, you're just creating more problems with a rollback.

I'm not sure if something has changed regarding the rollback, but due this problems we just create a full backup of the webshop on the server and in case of a critical error, we delete the content in /public_html and start a restore of the full backup on the server.

I hope that you made a full backup before...
