### ISSUE TITLE
Error when upgrading from 1.7.8.10 to 8.2.0 (and rollback)

### ISSUE THREAD

**Issue by gericfo** [PrestaShop/PrestaShop#37339]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

We encountered an error when updating the store from PrestaShop version 1.7.8.10 to version 8.2.0.
We used version 7.0.0 (currently under development of the Autoupgrade module). 
Store PHP: 7.4.33

Here is the error code: 
`[INTERNAL] /home/kinpresta82ywdwc/public_html/modules/autoupgrade/classes/PrestashopConfiguration.php line 96 - Exception: Can't find PrestaShop Version #0 /home/kinpresta82ywdwc/public_html/modules/autoupgrade/classes/UpgradeContainer.php(290): PrestaShop\Module\AutoUpgrade\PrestashopConfiguration->getPrestaShopVersion()
#1 /home/kinpresta82ywdwc/public_html/modules/autoupgrade/classes/UpgradeContainer.php(448): PrestaShop\Module\AutoUpgrade\UpgradeContainer->getProperty('version')
#2 /home/kinpresta82ywdwc/public_html/modules/autoupgrade/classes/Task/AbstractTask.php(196): PrestaShop\Module\AutoUpgrade\UpgradeContainer->getUpgrader()
#3 /home/kinpresta82ywdwc/public_html/modules/autoupgrade/classes/Task/Update/UpdateFiles.php(285): PrestaShop\Module\AutoUpgrade\Task\AbstractTask->setupEnvironment()
#4 /home/kinpresta82ywdwc/public_html/modules/autoupgrade/classes/Task/Runner/ChainedTasks.php(61): PrestaShop\Module\AutoUpgrade\Task\Update\UpdateFiles->init()
#5 /home/kinpresta82ywdwc/public_html/admin6933uuemv/autoupgrade/ajax-upgradetab.php(59): PrestaShop\Module\AutoUpgrade\Task\Runner\ChainedTasks->run()
#6 {main}`

An here is the error with the restore:
`[INTERNAL] /home/kinpresta82ywdwc/public_html/modules/autoupgrade/classes/PrestashopConfiguration.php line 96 - Exception: Can't find PrestaShop Version\n
#0 /home/kinpresta82ywdwc/public_html/modules/autoupgrade/classes/UpgradeContainer.php(290): PrestaShop\\Module\\AutoUpgrade\\PrestashopConfiguration->getPrestaShopVersion()\n
#1 /home/kinpresta82ywdwc/public_html/modules/autoupgrade/classes/UpgradeContainer.php(310): PrestaShop\\Module\\AutoUpgrade\\UpgradeContainer->getProperty('version')\n
#2 /home/kinpresta82ywdwc/public_html/modules/autoupgrade/classes/Task/AbstractTask.php(175): PrestaShop\\Module\\AutoUpgrade\\UpgradeContainer->getAnalytics()\n
#3 /home/kinpresta82ywdwc/public_html/modules/autoupgrade/classes/Task/Runner/ChainedTasks.php(66): PrestaShop\\Module\\AutoUpgrade\\Task\\AbstractTask->setErrorFlag()\n
#4 /home/kinpresta82ywdwc/public_html/admin6933uuemv/autoupgrade/ajax-upgradetab.php(59): PrestaShop\\Module\\AutoUpgrade\\Task\\Runner\\ChainedTasks->run()\n
#5 {main}`

![Image](https://github.com/user-attachments/assets/579d8cec-c8af-42c1-a61f-9aabad474cd3)

### Expected behavior

- A successful upgrade from version 1.7.8.10 to 8.2.0.
- A successful restore from version 8.2.0 to 1.7.8.10.

### Steps to reproduce

1. Download the Autoupgrade V7
2. Install it on a store with version 1.7.8.10
3. Launch an update with the Autoupgrade V7 (online channel to 8.2.0).

### PrestaShop version(s) where the bug happened

1.7.8.10 to 8.2.0

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

autoupgrade V7

**Comment by AureRita** [comment]
Hi @gericfo ,

Thank you for your report, I reproduce the issue with PrestaShop version 1.7.8.10, as you can see : 

https://github.com/user-attachments/assets/86258aff-fa76-4e38-984f-65f431bab9f3


I'll add this to the backlog so it can be fixed.

Please be aware that some issues might take a very long time to be resolved.

FYI : when I do another upgrade it works ... 

Thanks

**Comment by M0rgan01** [comment]
No longer present in the current state of the module (https://github.com/PrestaShop/autoupgrade/commit/40f932c6ac5b39a9ee297ead4ed545c525e25a18)
