### ISSUE TITLE
troublesome problem

### ISSUE THREAD

**Issue by patrykcode** [PrestaShop/PrestaShop#37346]
I think this line should have == instead of === , in CartRule object (minimum_amount_tax and minimum_amount_shipping) is integer not string and == false show by in line with '0', this same case is in  minimum_amount_shipping, after saving both selects do not have the correct value selected

https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/default/template/controllers/cart_rules/conditions.tpl#L100

```
<div class="col-lg-3">
	<select name="minimum_amount_tax">
		<option value="0" {if $currentTab->getFieldValue($currentObject, 'minimum_amount_tax') == '0' || $currentTab->getFieldValue($currentObject, 'minimum_amount_tax') === false}selected="selected"{/if}>{l s='Tax excluded' d='Admin.Global'}</option>
		<option value="1" {if $currentTab->getFieldValue($currentObject, 'minimum_amount_tax') == '1'}selected="selected"{/if}>{l s='Tax included' d='Admin.Global'}</option>
	</select>
</div>
<div class="col-lg-4">
	<select name="minimum_amount_shipping">
		<option value="0" {if $currentTab->getFieldValue($currentObject, 'minimum_amount_shipping') == '0'}selected="selected"{/if}>{l s='Shipping excluded' d='Admin.Catalog.Feature'}</option>
		<option value="1" {if $currentTab->getFieldValue($currentObject, 'minimum_amount_shipping') == '1'}selected="selected"{/if}>{l s='Shipping included' d='Admin.Catalog.Feature'}</option>
	</select>
</div>
```

**Comment by florine2623** [comment]
Hello,

Thank you for submitting this issue. Unfortunately, there is not enough information provided to reproduce it and work on it. *You must follow the template to submit a complete bug report*. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you can provide further information, we will be glad to investigate it. 

Thank you
