### ISSUE TITLE
Cart rule with Exclude discounted products - invoice error when order status is updated

### ISSUE THREAD

**Issue by alicedoe** [PrestaShop/PrestaShop#37341]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,

I'm experiencing an issue with orders that include at least one product with a specific price and a cart rule with the "Exclude discounted products" option. The cart amount and order total are initially correct, and the payment processes as expected. However, when I edit the shipping details of the order, it appears that the "Exclude discounted products" option is not taken into account. As a result, the amount is adjusted, causing the invoice to be incorrect (the amount paid by the customer differs from the total amount of the order).

Best regards, Alice

### Expected behavior

When the shipping details are edited, the total discount should respect the "Exclude discounted products" option.

### Steps to reproduce

- Create a cart rule with an order discount, activating the "Exclude discounted products" option.
- Place an order with at least one product having a specific price, then complete the payment.
- Update the shipping details: the total discount will change unexpectedly.

Here is a video on a clean PrestaShop instance showing the issue : https://www.awesomescreenshot.com/video/33371679?key=30019d3f8d87a6cab88ccd1a42780cc4

### PrestaShop version(s) where the bug happened

1.7.8.11

**Comment by florine2623** [comment]
Hello @alicedoe ,

I can't reproduce your issue on version 9.0.x of PS as you can see from my screen records :

With a Cart rule :

https://github.com/user-attachments/assets/074f72d3-8acd-4140-bc78-ecc6842576cf

https://github.com/user-attachments/assets/c78371ba-717f-4295-afc7-0d5901d17f91

With a discount created from the order page :

https://github.com/user-attachments/assets/18ac7d9a-205b-4d2e-a610-3fce464bd6d8

As the bug cannot be reproduce on newer version of PS, I suggest upgrading your store to benefit from this bug fix ^^

Thanks!
