### ISSUE TITLE
SQLstate error while trying to access 1-click upgrade page

### ISSUE THREAD

**Issue by Vbichigatsushi** [PrestaShop/PrestaShop#37345]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

we have an error when we are trying to access 1-click upgrade page, not running an upgrade, just display the page !

here is the error : SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
at line 151 in file classes/db/DbPDO.php!

[Image](https://github.com/user-attachments/assets/a79954e5-401d-4085-9bf8-8c757e363d33)

### Expected behavior

i just wanted to display the page, not to run the update

### Steps to reproduce

- we are using an o2switch server

to reproduce it, you just have to click on the 1-click upgrade menu on the left side menu in the back-office.
it's working on another of ours prestashop shops that is on the same server but is in 8.1.2 prestashop version.
the module is on the same version 6.2.0.

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

1-Click Upgrade v6.2.0

**Comment by gericfo** [comment]
Hello @Vbichigatsushi 
Thanks for your feedback. We've check the information you provided. 
The symptoms are related to the Autoupgrade module, but based on the stack trace the error seems related to the user profile image displayed on the top right of the Back Office which would happened anywhere (PrestaShop core). 
We do not reproduce this issue on our side on PrestaShop 8.1.7.
Can you check with other modules and check yout MySQL configuration? (especially max_allowed_packet)
Thanks.

**Comment by Joaq82** [comment]
Hi, I'm having the same error when activating the Facets module, and I don't know how to fix it! Any solutions?

Thanks.
