### ISSUE TITLE
1 click upgrade - From 1.7.7.1 to 8.2 - ps_mbo

### ISSUE THREAD

**Issue by bgarciaSDI** [PrestaShop/PrestaShop#37369]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

We have try to update PS from 1.7.7.1 to PS 8.2

We've done 2 tries ,
-> From 1.7.7.1 directly to 8.2
-> From 1.7.7.1 to 1.7.11 (Latest minor update) to 8.2
The update on minor was success.

The error we have seen is upgrading to 8.2 , on upgrading modules step
Before the upgrade , we don't have the module 'ps_mbo' , but as we can see , it is included on new PS version, it is trying to upgrade and give us this error:

`[INTERNAL] /var/www/vhost/dev.gocustom.sdi.es/home/html/modules/ps_mbo/ps_mbo.php line 288 - Error: Call to a member function get() on null #0 /var/www/vhost/dev.gocustom.sdi.es/home/html/modules/ps_mbo/ps_mbo.php(360): ps_mbo->get('doctrine.dbal.d...') #1 /var/www/vhost/dev.gocustom.sdi.es/home/html/modules/ps_mbo/src/Traits/HaveShopOnExternalService.php(77): ps_mbo->getAdminAuthenticationProvider() #2 /var/www/vhost/dev.gocustom.sdi.es/home/html/modules/ps_mbo/ps_mbo.php(271): ps_mbo->unregisterShop() #3 /var/www/vhost/dev.gocustom.sdi.es/home/html/modules/autoupgrade/classes/UpgradeTools/Module/ModuleMigration.php(128): ps_mbo->disable() #4 /var/www/vhost/dev.gocustom.sdi.es/home/html/modules/autoupgrade/classes/Task/Upgrade/UpgradeModules.php(108): PrestaShop\Module\AutoUpgrade\UpgradeTools\Module\ModuleMigration->runMigration(Object(PrestaShop\Module\AutoUpgrade\UpgradeTools\Module\ModuleMigrationContext)) #5 /var/www/vhost/dev.gocustom.sdi.es/home/html/modules/autoupgrade/classes/Task/Runner/ChainedTasks.php(61): PrestaShop\Module\AutoUpgrade\Task\Upgrade\UpgradeModules->run() #6 /var/www/vhost/dev.gocustom.sdi.es/home/html/sdipanel/autoupgrade/ajax-upgradetab.php(54): PrestaShop\Module\AutoUpgrade\Task\Runner\ChainedTasks->run() #7 {main}
`

### Expected behavior

Successfully upgrade

### Steps to reproduce

1. Have a 1.7.7.1 PS version
2. Install one click upgrade and try to upgrade to 8.2 (Major version)
3. Wait until the module upgrade step There you will see the error

### PrestaShop version(s) where the bug happened

1.7.7.1

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

autoupgrade - 6.2.0

**Comment by Codencode** [comment]
I believe this issue is the same as the one I reported here: https://github.com/PrestaShop/PrestaShop/issues/37445
@bgarciaSDI, can you confirm?
If it's the same problem, then you just need to delete the pd_mbo module folder before running the update.

This issue will be resolved in the new release of the autoupgrade module.

**Comment by borjagarciab** [comment]
> I believe this issue is the same as the one I reported here: [#37445](https://github.com/PrestaShop/PrestaShop/issues/37445) [@bgarciaSDI](https://github.com/bgarciaSDI), can you confirm? If it's the same problem, then you just need to delete the pd_mbo module folder before running the update.
> 
> This issue will be resolved in the new release of the autoupgrade module.

Yes is the same

Thanks!

**Comment by Quetzacoalt91** [comment]
Thanks @Codencode for updating this thread.
Hopefully this issue is fixed with the incoming v7 of the update module, we have closed the other issue as it is not reproduced on the dev branch. More testing will be done before the release.
