### ISSUE TITLE
Unstable UI testing on Webkit

### ISSUE THREAD

**Issue by kpodemski** [PrestaShop/PrestaShop#37364]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hundreds of UI tests have failed, not because of the changes introduced in the pull request, but _something else_. Most of the time, they fail on WebKit. You can see it here:
https://github.com/PrestaShop/PrestaShop/actions/workflows/sanity.yml?query=is%3Afailure

or some specific examples:
https://github.com/PrestaShop/PrestaShop/actions/runs/11774921107
https://github.com/PrestaShop/PrestaShop/actions/runs/11758673148
https://github.com/PrestaShop/PrestaShop/actions/runs/11703653048

cc @Progi1984 @Hlavtox 

### Expected behavior

The test suite should be stable and reliable without restarting it. It doesn't serve its purpose if I have to restart it X times to see it green randomly. If it fails because of a third party, then it should be marked as either not required for CI or temporarily held.

### Steps to reproduce

1. Contribute to PrestaShop.
2. See CI red even if you change a comment in PHP Docs.

### PrestaShop version(s) where the bug happened

n/a

### PHP version(s) where the bug happened

n/a

### If your bug is related to a module, specify its name and its version

n/a

### Your company or customer's name goes here (if applicable).

PrestaShop

**Comment by florine2623** [comment]
ping @Progi1984 ^^
