### ISSUE TITLE
Module productcomments : missing customer_name in database

### ISSUE THREAD

**Issue by CedricKiwik** [PrestaShop/PrestaShop#37366]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,
When a customer post a review on a product (module productcomments) : 
![Image](https://github.com/user-attachments/assets/7c840184-82c7-4bfe-9fba-6a196f05eae7)

When the review is post, the customer name is missing in the database, as you can see, there is no customer_name in DB in the table product_comment : 
![Image](https://github.com/user-attachments/assets/82699bf9-d4a2-41be-bca5-4fa1b489dd7a)

Here is a screenshot of the configuration of the module : 
![Image](https://github.com/user-attachments/assets/35b0e0c3-a804-4e83-91c9-a3d83cbbb5ab)

### Expected behavior

The customer_name should register in database.

### Steps to reproduce

1. Post a review
2. Go to database and check if customer_name appears in product_comment table

### PrestaShop version(s) where the bug happened

8.1.6

### PHP version(s) where the bug happened

8.1.30

### If your bug is related to a module, specify its name and its version

productcomments v7.0.0

### Your company or customer's name goes here (if applicable).

Kiwik

**Comment by Hlavtox** [comment]
@CedricKiwik customer_name is used only for logged in customers, check the inner workings of the module to see. 👍

If you need the name, you have id_customer there.
