### ISSUE TITLE
Uploaded module via FTP isn't updated correctly

### ISSUE THREAD

**Issue by ShaiMagal** [PrestaShop/PrestaShop#37380]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If you upload module via ZIP and there is folder "upgrade" with files upgrade-X-X-X.php, everything works well.
**BUT**
if you upload module via FTP, upgrade process from script content of upgrade-X-X-X.php isn't executed, so you can get to troubles.

Already discussed with @Hlavtox repeatedly.

"Funny" fact is PS 1.6 can handle this situation... But 1.7+ can't.

This situation can lead for example to error 500, if for example is there any change in mysql tables in this upgrade.

Situation:
module 2.1.0
After you updated module to 2.1.1 via FTP, you will get module version 2.1.1, but DB version 2.1.0! You must manually click to "upgrade", but it can be missed or in any cases you can't see it until you delete cache (/var/cache)

If there is for example any change in working with mysql tables in version 2.1.1 (new columns, ...) this can lead to error 500 for FO/BO.

We should handle this situation. 

@Hlavtox Can you possibly add the missing information?

### Expected behavior

There is more options:
A) make update DB automatically like in version 1.6 after uploading to FTP
B) if PS detect any inconsistency about file version and DB version (or simply solved, that the module simply does not have the necessary update), module should be disabled
C) suggest something...

### Steps to reproduce

If anyone is interested in solving this, I will provide an example module and show how to demonstrate the 500 error. Let me know.

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.3

### Your company or customer's name goes here (if applicable).

https://www.openservis.cz/

**Comment by Hlavtox** [comment]
@ShaiMagal You just have to update it via the Upgrade button. The problem is with that stupid cache, that doesn't show you that something changed on FTP. :-(

**Comment by ShaiMagal** [comment]
@Hlavtox in specific situation, you will get 500 error after uploading via ftp.
Its easy how to simulate this.

So maybe you will not be able to press button :D 

But ft uploading modules is very problematic. Its not proper way how to do this.

I thing we should communicate to tell customers, uploading zip is the only one possible option.

And maybe talk about possibility if there isnt better solution, for example, disable module when prestashop detect there is waiting upgrade...

Or something like that.

This must be discussed more in every case :)

**Comment by jf-viguier** [comment]
Sometimes, developer update modules with git, I's a main issue.
The cache issue is also new to 9 ou 8. Annoying.

**Comment by matks** [comment]
Hi guys,

From my point of view, "upload a module by FTP" is NOT a feature 😄 : it means you directly replace the files on the server, bypassing any validation or processing done by PrestaShop.

For me "upload a module by FTP" is similar to "upload data by phpMyAdmin" : you are doing manually a change that should be done by some code logic.

When you use the "Upload by ZIP" you perform an action that triggers some code logic that will perform multiple operations, such as file movements, some changes in the database, maybe some API calls? I don't know. But the most important thing is that you TRIGGER the code to execute. When you "upload by FTP" you trigger nothing, so we can't process things correctly.

Little detail: what you could do is "install by FTP" and by that I mean
- you bring a new module folder inside /modules
- then you go to backoffice page "module manager" and you click on "install"

But as you can see you always need 1 click, to trigger the code. You cannot expect proper behavior without a click.

> "Funny" fact is PS 1.6 can handle this situation... But 1.7+ can't.

I did verify but I highly doubt it. If you manually change files on a server without executing any code logic I don't see how it can work. I think it gives you the illusion it's working and you were lucky. But it does not "work" IMO.

**Comment by matks** [comment]
I verified in the documentation, we don't talk about "updating a module by FTP" 😉 so

> I thing we should communicate to tell customers, uploading zip is the only one possible option.

Yes "upload ZIP" is the only and viable solution it's designed this way 😉 

If however you need to install the same module in 20 different shops what you can do is
- upload module files by FTP
- then use the CLI to trigger the "install" process

And I also think you can use the CLI to perform the "upgrade" process, but it will go fetch the new module version on Addons. So it only works for modules on Addons.
