### ISSUE TITLE
The onboarding stop button does not work after upgrade of 1.7.1 to 1.7.8.11

### ISSUE THREAD

**Issue by nesrineabdmouleh** [PrestaShop/PrestaShop#37382]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

The onboarding stop button does not work after upgrade of 1.7.1 to 1.7.8.11

https://github.com/user-attachments/assets/c8e84004-dc16-4d25-8f6b-6cd8dada9814

### Expected behavior

The stop onboarding link should work.

### Steps to reproduce

1- Install docker image of PS 1.7.1.0
2- Upgrade to 1.7.8.11
3- Login
4- Close the onboarding modal
5- Click on Stop the onboarding link and see the error

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

autoupgrade

**Comment by Quetzacoalt91** [comment]
@nesrineabdmouleh did you have any error displayed on the browser console? A failing Ajax request?

**Comment by nesrineabdmouleh** [comment]
no :/ I can't find any errors when I click on stop the onboarding link

![Image](https://github.com/user-attachments/assets/a5dd149f-ba9c-4b21-9906-48ecd80d8eee)

**Comment by M0rgan01** [comment]
After checking, this problem does not come from the **autoupgrade** module, but from the update of the module itself. 

A migration file is missing to add a new tab, which appeared with 2.0.5 of the module (https://github.com/PrestaShop/welcome/commit/ec30f56ec58870fa77b264b96f3ac77f6da74292).

To resolve the problem, it would be necessary to patch 2.0 of the module, but it is archived.
