### ISSUE TITLE
in prestashop  8.2.0 in default theme not change a name of category

### ISSUE THREAD

**Issue by faustf** [PrestaShop/PrestaShop#37408]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

hi  after install a new language (italian), active them , go to catalog-->categories , try to modify a first category , change name and save but when i save it 
![Image](https://github.com/user-attachments/assets/772b35ee-a087-4be2-84d8-4b790a0ae873)

### Expected behavior

i suppose if i modify name of category it must change 

### Steps to reproduce

1.goto catalog-->categories  ,after install language , try to change name of category in default theme 

### PrestaShop version(s) where the bug happened

8.2.0

**Comment by Hlavtox** [comment]
@faustf Do you see the red error on the category description field? :-)

**Comment by faustf** [comment]
i find  a solution prestashop is not fully capable with firefox  fu.....   thanks at  all  with chrome now  work :D, i hope in future change  this problem thankssss
