### ISSUE TITLE
On upgrading all module, do not refresh page until done, regardless of "refresh_needed" in response

### ISSUE THREAD

**Issue by madsoliver** [PrestaShop/PrestaShop#37413]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When upgrading all modules, lets say 30 modules, then it will upgrade one-and-one. 
The module controller `src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php:467` determines if the page needs a reload to `true` if the module has tabs.
Thats OK, since links in the menu would possibly fail, if the merchant clicks links that no longer are valid.

However.. what it does, is that it actually reloads the page imidiately after that module has sent the ajax response.
 That means you need to click the upgrade all-button many times.

### Expected behavior

It would be better to wait until all modules are upgraded to see if ANY of the modules has `refresh_needed = true`, then refresh.

Actually, it would make sense to refresh anyway, since when you are done with upgrading all modules, it still says 30 modules needs upgrade and the `Upgrade all` button is still possible to click. A refresh would clean this up.

### Steps to reproduce

Make sure you have a lot of modules that needs update.
Make sure that some of them has tabs.
Upgrade all.

Observe that the page reloads after a while, and you need to click the button again to continue the upgrades.
Also when finished, observe that you get notifications that modules are updated, but the "Upgrade all" button is not gone, also not the counters (30 modules to upgrade) are not deducted or removed.

A tip if you want to test many times, dump the `ps_module` table before the upgrade, then resore it after to be able to upgrade again.
Also if you dont have any upgradable modules, simply edit the versions to a lover version in the same table to fake the need for an upgrade.

### PrestaShop version(s) where the bug happened

8.2.0

**Comment by Hlavtox** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/30953

**Comment by matks** [comment]
As said before, duplicate of https://github.com/PrestaShop/PrestaShop/issues/30953
