### ISSUE TITLE
Product Type Not Updated Correctly When Changing from 'Pack of Products' to 'Standard Product'

### ISSUE THREAD

**Issue by seederp2p** [PrestaShop/PrestaShop#37419]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When editing a product in PrestaShop from "Pack of Products" to "Standard Product", the change appears to take effect in the front office. However, in the back office, the selector remains on "Pack of Products", and in the database, the column product_type in the ps_product table retains the value "pack".

This discrepancy leads to inconsistencies between the front office, back office, and database.

I'm NOT using "New product page".

### Expected behavior

When changing the product type from "Pack of Products" to "Standard Product", the update should be correctly reflected:

In the back office selector.
In the product_type column in the ps_product table (set to "standard").

### Steps to reproduce

Create or edit a product and set its type to "Pack of Products" in the back office.
Save the product.
Re-edit the same product and change its type to "Standard Product".
Save the changes.
Observe:
The front office reflects the product as a "Standard Product".
The back office selector still shows "Pack of Products".
In the database (ps_product table), the product_type column retains the value "pack".

### PrestaShop version(s) where the bug happened

8.1.9

### PHP version(s) where the bug happened

7.4

**Comment by Hlavtox** [comment]
@seederp2p I did not test it, but I believe you.

However, these are the last days of product page v1, it's already removed in 9.0.0 that is coming soon. :-) I don't think there will be anyone willing to fix it. I think we even already closed all issues related to v1 product page.

**Comment by seederp2p** [comment]
> [@seederp2p](https://github.com/seederp2p) I did not test it, but I believe you.
> 
> However, these are the last days of product page v1, it's already removed in 9.0.0 that is coming soon. :-) I don't think there will be anyone willing to fix it. I think we even already closed all issues related to v1 product page.

I understand, and I appreciate the update. However, like many PrestaShop store owners or agencies, we tend to wait for a grace period before adopting new major versions. This allows time for the new versions to stabilize, plugins to become compatible, and the ecosystem to align.

So, perhaps the issue isn’t too challenging to resolve, and it might be worthwhile to produce a fix for those who continue to rely on the v1 product page during this transitional phase. It would certainly help many of us still on this version.

**Comment by florine2623** [comment]
Reproduced in PPV1, not in PPV2.

**Comment by ibahloul-ps** [comment]
Hello @seederp2p 
Like @Hlavtox said, we won't fix issue related to a legacy page!

Have a good one!
Bye
