### ISSUE TITLE
Some customers have been removed from their group. What can I do? PS 1.7.8.7

### ISSUE THREAD

**Issue by dbrisson-passat** [PrestaShop/PrestaShop#37426]
### Discussed in https://github.com/PrestaShop/PrestaShop/discussions/37425

<div type='discussions-op-text'>

<sup>Originally posted by **dbrisson-passat** November 21, 2024</sup>
Hello everyone I have a big bug on my stores, I have some of my customers who could not assigned groups, I tried to create an account at the creation is well assigned to the customer group, but I do not understand what happens that a customer is without a group and therefore could not access the categories and product.
The customer's id is simply deleted from the ps_customer_group table instead of having its id and group id...

![image](https://github.com/user-attachments/assets/febcbb79-8c13-404e-9019-f29060ff1431)

Has anyone ever had this problem, or knows how to fix it?</div>

**Comment by florine2623** [comment]
Hello,

I can't reproduce your issue.

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by dbrisson-passat** [comment]
Hello,

Yes, you can't reproduce this issue because I don't know how it happens. All I know is that when the account is created, it is assigned to the customer group, but that's all.
