### ISSUE TITLE
Product comments give an error in debug and js error

### ISSUE THREAD

**Issue by sickboards** [PrestaShop/PrestaShop#37438]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the product page it throws the following error:
```
Warning: Undefined array key "product" in /home/.../modules/productcomments/productcomments.php on line 1061

Warning: Trying to access array offset on value of type null in /home/.../modules/productcomments/productcomments.php on line 1062
```

In the console it shows:
```
core.js:37 Uncaught ReferenceError: productCommentMandatoryMessage is not defined
    at HTMLDocument.<anonymous> (post-comment.js:43:58)
    at u (core.js:37:30297)
    at l (core.js:37:30599)
```

### Expected behavior

A working module :)

### Steps to reproduce

Install product comments 
Go to the product page.

### PrestaShop version(s) where the bug happened

8.2

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

7.0.0

**Comment by florine2623** [comment]
Hello @sickboards ,

I can't reproduce your issue using PHP 8.1 and ps_productcomments v7.0.0.

https://github.com/user-attachments/assets/c1126bea-23cf-4101-8404-79804a233b1a


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by SharakPL** [comment]
@sickboards there may be an issue with your theme. I suspect it overrides a few `productcomments` module templates and thus is missing a new content. Just make sure the `<script>` section on top of
**themes\ [your_theme]\modules\productcomments\views\templates\hook\post-comment-modal.tpl**
looks like this:
```
<script type="text/javascript">
  var productCommentPostErrorMessage = '{l s='Sorry, your review cannot be posted.' d='Modules.Productcomments.Shop' js=1}';
  var productCommentMandatoryMessage = '{l s='Please choose a rating for your review.' d='Modules.Productcomments.Shop' js=1}';
  var ratingChosen = false;
</script>
```

https://github.com/PrestaShop/productcomments/blob/c0939687e39e306bb3b04c6929fec86927e9cbde/views/templates/hook/post-comment-modal.tpl#L26-L30
