### ISSUE TITLE
prestashop 8.2.0 searching not working

### ISSUE THREAD

**Issue by kobietakoduje** [PrestaShop/PrestaShop#37444]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I use classic theme, just add simple product, configure ps_facetedsearch and also performance & search - searching is not working. 

### Expected behavior

How to fix it?

### Steps to reproduce

Go to home page
Try search by word 
No search results

### PrestaShop version(s) where the bug happened

8.2.0

### PHP version(s) where the bug happened

7.4.27

### If your bug is related to a module, specify its name and its version

Shop search v2.0.2 

### Your company or customer's name goes here (if applicable).

https://new.soyero.com/

**Comment by florine2623** [comment]
Hello @kobietakoduje ,

I can't reproduce your issue as you can see from my screen record :

https://github.com/user-attachments/assets/06299dfd-9af4-4948-b88e-4217e89d11e1

We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by kobietakoduje** [comment]
Thx for your feedback, but i have fresh instalation without any customisations , i put only one my product and i have "No search results". I resolve this issue, product indexing was disabled.
