### ISSUE TITLE
SEO product Optimization : delete categorie name

### ISSUE THREAD

**Issue by jeckyl** [PrestaShop/PrestaShop#37465]
### Discussed in https://github.com/PrestaShop/PrestaShop/discussions/37437

<div type='discussions-op-text'>

<sup>Originally posted by **jeckyl** November 21, 2024</sup>
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,
PrestaShop has always had the bad practice of embedding category names in product URLs.
`{category:/}{id}{-:id_product_attribute}-{rewrite}.html`

### Expected behavior

It would be preferable, when installing PrestaShop, for the rewrite to be without the categories :
`{id}{-:id_product_attribute}-{rewrite}.html`

Provide a redirection line from URL anchors to new ones to avoid problems when updating.

### Steps to reproduce

SEO&URLs Tab

### PrestaShop version(s) where the bug happened

1.0.0 - 9.0.0

### Your company or customer's name goes here (if applicable).

Mediacom87</div>

**Comment by Hlavtox** [comment]
@jeckyl Why do you open a new issue, we already discuss this in here no? https://github.com/PrestaShop/PrestaShop/discussions/37437

**Comment by jeckyl** [comment]
To make a PR you need an Issue, but surely I've misunderstood something again.

**Comment by jeckyl** [comment]
In doing my PR I see that discussions can be linked, so this is a mistake on my part.
