### ISSUE TITLE
ps_facetedsearch - category can't be chosen

### ISSUE THREAD

**Issue by kkolcon** [PrestaShop/PrestaShop#37471]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,
I have PrestaShop 1.7.8.3 with AtMovic theme and module ps_facetedsearch v3.11.1 installed.

The module works fine except the category search.
When I choose any category, the page refreshes, but then the choice is lost.

### Expected behavior

Category choice should be kept after refresh - checkbox should be checked and chosen option should be displayed in header.

### Steps to reproduce

1. Install and configure ps_facetedsearch module to enable category filtering.
2. Go to any listing page.
3. Check any category's checkbox within the search list.
4. Page refreshes and the choice is lost.

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.2.34

### If your bug is related to a module, specify its name and its version

ps_facetedsearch v3.11.1

**Comment by Hlavtox** [comment]
Hi @kkolcon, versions of your software, php and faceted search module are long updated. Nothing like this happening on default theme, it works properly since 1.7.6.

I suggest contacting the developer of your theme. Thank you.
