### ISSUE TITLE
Prestashop out-of-stock cart issue

### ISSUE THREAD

**Issue by jesiiu** [PrestaShop/PrestaShop#37492]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi, i found bug in prestashop, version 8.2.0, i have enabled on store "Allow order products when out-of-stock" but it does not work and still cart checking quantity of the product and i got error
"You can only buy 0 "". Please adjust the quantity in your cart to continue.", because of this, I have a problem with the operation of modules related to marketplace like Ebay...

It tried bruteforce that in CartController setting variable $isAvailable = $this->areProductsAvailable(); to $isAvailable = true but it seems like presta does not creating cart in database and when i click Procees button i was just redirected back to previous page with cart.

Can someone explain me why it is caused?
![Image](https://github.com/user-attachments/assets/2d6b2b92-6264-4d33-9514-d71e04cd742f)

### Expected behavior

1. Prestashop allow to proceed cart even with product with stock 0

### Steps to reproduce

1. Enable in PS setting"Allow order products out of stock"
2. Enable Allow order when out of stock in specific product variant
3. Add product to cart
4. Got error

### PrestaShop version(s) where the bug happened

8.2.0

### PHP version(s) where the bug happened

8.1

**Comment by Hlavtox** [comment]
Check minimal order quantity of that product, it should be at least 1.
Also, you can further specify the out of stock behavior for each product. Check the out-of-stock behavior of the product itself.

**Comment by jesiiu** [comment]
![Image](https://github.com/user-attachments/assets/343e5a72-caa1-4d4c-a1ab-1eec33502be2)
![Image](https://github.com/user-attachments/assets/6cf2344b-b779-429b-a2e4-2b89b92c0717)
![Image](https://github.com/user-attachments/assets/5228aa9a-c136-451d-b80e-ec3b4b3d8139)
![Image](https://github.com/user-attachments/assets/a2e57451-8d2a-47ba-9c9d-1c3483147b72)


It is my current settings of prestashop, it is correct?

**Comment by jesiiu** [comment]
UPDATE
![Image](https://github.com/user-attachments/assets/20a43291-6272-4fbb-a094-a71b14c94e8d)

I dont know why but now this product is tagged with "Out of stock" label but presta should allow to order this product and set label "Out of stock order allow" as it is set below
![Image](https://github.com/user-attachments/assets/09ee0b98-8cda-46bf-b870-439ef1cd4778)

**Comment by Hlavtox** [comment]
@jesiiu That's just a hardcoded label. Turn it off in prestashop settings and use the text labels you have on the screenshot.

This is just a nonsense that somebody came up with and I had no chance to influence it...
![Image](https://github.com/user-attachments/assets/3a11eb68-db76-4f50-9ed6-c052f7c7057c)

**Comment by Hlavtox** [comment]
@kpodemski Can you check? Seems like a weird issue.

@jesiiu Is this a clean shop with 0 external modules and overrides?

**Comment by jesiiu** [comment]
@Hlavtox 
No it's not clean shop
![Image](https://github.com/user-attachments/assets/d5d8e5dc-0655-4cb3-8d16-e1532a2470fd)
That's all of overrides that i have

**Comment by jesiiu** [comment]
Any one? Any idea how to fix that issue? I looked at prestashop github repository and i can see that my cartcontroller file is different than from repo.. Can be that issue?

**Comment by Hlavtox** [comment]
Well, we have a cause then. :-) Revert your CartController modifications and it will work properly.

**Comment by jesiiu** [comment]
> Well, we have a cause then. :-) Revert your CartController modifications and it will work properly.

I dont think so... it does not work before any cartcontroller modifications and i have revert all of the modifications that i did

Can you send me working carctonroller code? Maybe when i copy and paste it will start work... i hope
