### ISSUE TITLE
In API : Undefined array key 1 in web service/dispatcher on line 44

### ISSUE THREAD

**Issue by FrankSt** [PrestaShop/PrestaShop#37502]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When doing a get: xxx/api/products?schema=blank from whatever table that return always adds 
-> Warning:  Undefined array key 1 in /home/xxxxxxx/domains/dev.xxxxxx.com/public_html/webservice/dispatcher.php on line 44 before de real XML doc. Json doesn't even work

This always happens for every get. Post will work, but returns the same error. So a post will create the product

### Expected behavior

Get a pure XML-doc or JSON doc

### Steps to reproduce

This works on my test-version, but stops working after moving to the main-server for production

### PrestaShop version(s) where the bug happened

8.2.0

### PHP version(s) where the bug happened

8.1.29

### If your bug is related to a module, specify its name and its version

Webservice/dispatcher.php

### Your company or customer's name goes here (if applicable).

FrankS

**Comment by florine2623** [comment]
Hello @FrankSt ,

Could you specify the steps to reproduce please ?

Please send the body of your request.

Waiting for your feedback.
Thanks!

**Comment by FrankSt** [comment]
Hello Florine,


Thank you for looking at this, but we couldn't wait for a fix, so we reinstalled a version from a copy where it was still working.
For the moment, everything is working fine, the error was very strange
