### ISSUE TITLE
PrestaShop 8.1.3 fails update

### ISSUE THREAD

**Issue by Peter4661** [PrestaShop/PrestaShop#37506]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

[1-click upgrade.pdf](https://github.com/user-attachments/files/17937141/1-click.upgrade.pdf)

### Steps to reproduce

[1-click upgrade.pdf](https://github.com/user-attachments/files/17937151/1-click.upgrade.pdf)
[table_ps_configuration.pdf](https://github.com/user-attachments/files/17937152/table_ps_configuration.pdf)
[server_information.pdf](https://github.com/user-attachments/files/17937150/server_information.pdf)

### PrestaShop version(s) where the bug happened

1.8.1.3 tot 1.8.2

### PHP version(s) where the bug happened

8.0.30

### If your bug is related to a module, specify its name and its version

1 click upgrade

**Comment by Peter4661** [comment]
Required parameters: Oké
Optionele parameters: Oké

Actions :
php modules/autoupgrade/cli-upgrade.php --dir=xxxxxxxx --channel=private --action=upgradeDb  : success
Execution log oké, modules updrage: success!

[Image](https://github.com/user-attachments/assets/d97fdc9f-971a-482b-a807-0d5575dcadbc)
![Image](https://github.com/user-attachments/assets/d389a469-d85e-4d3d-bd50-c0b82cca2c5c)

clear folders: /var/cache/ and /cache/.

No success!

**Comment by Peter4661** [comment]
Hope it will help

Error message Chrome console hold for upgrade

[screenshot_console_error_message_PS_1-Click_upgrade.pdf](https://github.com/user-attachments/files/17957393/screenshot_console_error_message_PS_1-Click_upgrade.pdf)

**Comment by gericfo** [comment]
Hello @Peter4661 
Thanks for your feedback.
After reading your ps_configuration.pdf file we can see that the property "PS_VERSION_DB" contains the version "8.2.0". It's probably the result of your upgrade attempt when you run the upgrade database without copying upgrade files.
And now it's normal that the requirement is red in the 1-click upgrade module Web Interface (store version in DB), preventing you to perform another update.

You should change the "PS_VERSION_DB" (currently "8.2.0") property in the ps_configuration table for "8.1.3". Then, you will be able to perform an update from the 1-click upgrade module Web Interface. 
This action should allow you to perform a full update (files + database).
Thanks.

**Comment by Peter4661** [comment]
Hallo GericFo,

Thank you for looking into our issue and your advice.
We followed your advice. Issue has been resolved.



Best regards,

Met vriendelijke groet,

Peter Derks
Derks wielersport
Ambachtsweg 8 d
4661WM Halsteren

telefoon +31 624 179 798

www.derks-wielersport.nl


Op ma 2 dec 2024 om 11:00 schreef GericFo ***@***.***>:
