### ISSUE TITLE
Build the V9 Classic Beta ZIP

### ISSUE THREAD

**Issue by tleon** [PrestaShop/PrestaShop#37501]
Configure the ps_edition_basic builder to be able to build a Beta build using the right versions of the modules MBO, Accounts...

See https://github.com/PrestaShopCorp/ps_edition_basic/issues/12

We need to create a new file [here](https://github.com/PrestaShopCorp/smb_edition_builder/blob/master/_dev/classic-config/fr-FR/)

We can based our new file on the [9.0.0](https://github.com/PrestaShopCorp/smb_edition_builder/blob/master/_dev/classic-config/fr-FR/config_classic_9.0.0.yml) variant. 

we need to modify it to target the correct branch for the beta build and determine what module we want to add to the zip.

We should also test build a zip so we can be sure the config file is correct. 

Don't change this attribut for the moment : 

``` 

config:
  draft: true

```

**Comment by jf-viguier** [comment]
@tleon can you move PrestaShopCorp's issues in PrestaShopCorp orga ?
