### ISSUE TITLE
Prestashop 8.2.0 installation : Error on post-installation scripts : 1. Array [type] 16384

### ISSUE THREAD

**Issue by fabofolies** [PrestaShop/PrestaShop#37539]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,

I'm trying to install PrestaShop 8.2 on an OVH PHP 8.1 server and MySQL 8.0 database and I am getting the following error :

Array
(
    [type] => 16384
    [message] => Not specifying the optional ShopConstraint parameter is deprecated since version 1.7.8.0
    [file] => /var/www/computercentrale/src/Adapter/Configuration.php
    [line] => 427
) 

So I opened the src/Adaptater/Configuration.php file and here is the offending line : 

```
* @return ShopConstraint
     */
    private function buildShopConstraintFromContext(): ShopConstraint
    {
        @trigger_error(
            'Not specifying the optional ShopConstraint parameter is deprecated since version 1.7.8.0',
            E_USER_DEPRECATED         :   This one
        );
```

![Image](https://github.com/user-attachments/assets/1b61487c-95b1-45b6-85cf-5c9514cc3f19)

### Expected behavior

I'm sorry because I have no coding knowledge, could you help me resolve this problem so that I can complete the installation of PrestaShop ?

### Steps to reproduce

1. Copy of prestashop_edition_basic_version_8.2.0 file content in the server root
2. Start installation
3. Getting this error on the last step

### PrestaShop version(s) where the bug happened

8.2.0

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

Fabofolie's.com

**Comment by florine2623** [comment]
Hello @fabofolies ,

Can you make sure you follow these system requirements : https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/ ?

Waiting for your feedback.
Thanks!

**Comment by fabofolies** [comment]
Hello florine2623,

Thank you for your reply, I tried to run phppsinfo.php but it continually asks me for the login and password (prestashop by default).
And I don't know how to do an override in order to avoid the identification step.
Prestashop replied me to try a new installation by downloading the file again without installing the test products, which I did and it didn't change anything.

Thank you for your time and support.

**Comment by paulnoelcholot** [comment]
Hello @fabofolies,

We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Thank you

**Comment by amichalu** [comment]
I confirm the bug, I verified nginx and apache, the same bug occurs during install:
- PS 8.2.0
- Ubuntu 24.10 x86_64 (OVH Cloud)
- apache 2.4.62-1ubuntu1
- nginx 1.26.0-2ubuntu3
- php PHP 8.3.11 (php-fpm: 2:8.3+93ubuntu2)

**Comment by amichalu** [comment]
The bug was caused that because I unzipped PS app (prestashop.zip) myself to http catalog /var/www and I started installing. Instead index.php should by run after unzipping release zip file (prestashop_8.2.0.zip) to http catalog like /var/www.

**Comment by masiorama** [comment]
> The bug was caused that because I unzipped PS app (prestashop.zip) myself to http catalog /var/www and I started installing. Instead index.php should by run after unzipping release zip file (prestashop_8.2.0.zip) to http catalog like /var/www.

Can you elaborate please? Experiencing the same issue but on 1.7.8.11 on recent local dev env deploy and I cannot solve this.

**Comment by amichalu** [comment]
I'm not sure what I exactly did few months ago :) I simply unzipped prestashop_8.2.0.zip to root dir of http server and called index.php in the browser, you should have configured index.php automatically will be called when you go to the url of the prestashop directory

**Comment by masiorama** [comment]
Mmm I guess it was a totally different issue though the error message is the same. Anyway, thanks for your reply!
