### ISSUE TITLE
On product listing "add to cart" is shown even if prices are not.

### ISSUE THREAD

**Issue by tswfi** [PrestaShop/PrestaShop#37532]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Initially found with hummingbird, but this affects all themes that show add to cart functionality in product listings. The initial issue has been closed in hummingbird repo for that reason: https://github.com/PrestaShop/hummingbird/issues/661

If customer group has the settting "Show prices: no" they will not see any prices and thus cannot buy the product. This works with the current default theme as it does not show add to cart button in product listing BUT hummingbird (and probably other themes) do show add to cart in the listing. The product quick preview works and product page work as expected.

![Image](https://github.com/user-attachments/assets/a0a5a4ef-87ed-494f-951d-cc0e234faedb)

### Expected behavior

If customer group does not see prices for products the add to cart buttons should also be hidden from product listing

### Steps to reproduce

1. Install humminbird theme from: https://github.com/PrestaShop/hummingbird/releases/tag/v0.2.0 (or some other theme that shows add to cart buttons in product listing)
2. set "guest" and "visitor" customer groups to "show prices: no"
3. check the shop frontpage, prices are hidden but add to cart is still shown (of course it does not work)

### PrestaShop version(s) where the bug happened

8.2.0 branch

### PHP version(s) where the bug happened

8.1 (using the docker-compose.yml from the 8.2.0 branch)

**Comment by Hlavtox** [comment]
Thank you @tswfi! :-) Approved that PR, nice catch!

**Comment by tswfi** [comment]
@Hlavtox thanks for pointing to correct place from my original hummingbird pr! I just copy pasted your comment to a PR :D

**Comment by florine2623** [comment]
This issue has been reproduced in PS 8.2.0, but not in PS 9.0.0 !

**Comment by florine2623** [comment]
Might be related to https://github.com/PrestaShop/PrestaShop/issues/37335

**Comment by Hlavtox** [comment]
@florine2623 It may be that in hummingbird, it's hardcoded on theme level. But @tswfi's PR is a proper long term solution. :-)
