### ISSUE TITLE
PHP deprecated in module "sekeywords"

### ISSUE THREAD

**Issue by Yakouaho** [PrestaShop/PrestaShop#37547]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,

I have upgrade from 1.7.7.8 to 1.7.8.11 then 8.2 and got message in the phperror log file :

PHP Deprecated: The hook "top" is deprecated, please use "displayTop" instead in module "sekeywords". in /............/public_html/classes/Hook.php on line 921

And the phperrorlog file increase until 2gb ... because of this error.

Thanks

Best regards

### Steps to reproduce

nothing special

error reported almost every second

### PrestaShop version(s) where the bug happened

8.2

### PHP version(s) where the bug happened

8.1.31

**Comment by Hlavtox** [comment]
@Yakouaho Hi! :-)

A) This module is no longer supported and no work will be done on it.
B) Prestashop 1.7.8 supports MAX PHP 7.4, that's why you get these errors.

**Comment by Yakouaho** [comment]
@Hlavtox 

Thanks for your answer.

I have this error with prestashop version 8.2

How to remove this module ?

regards

**Comment by Hlavtox** [comment]
@Yakouaho Ah, well, just uninstall it from module manager, then these errors will disappear. :-)

**Comment by Yakouaho** [comment]
@Hlavtox  This module is not visible in the module manager :(
