### ISSUE TITLE
Use kanban bot to automatically tag hook contributions

### ISSUE THREAD

**Issue by ibahloul-ps** [PrestaShop/PrestaShop#37553]
Enable the core team to identify hooks' contributions more quickly/easily among other issues 👍 
Define a new category (HO?) and update [the documentation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#type--category) and [the readme](https://github.com/PrestaShop/PrestaShop/blob/develop/.github/PULL_REQUEST_TEMPLATE.md) accordingly

GIVEN: the repo `Prestashop/Prestahsop`
WHEN: an issue is created with the `HO` category
THEN: the label `Hook Contribution` is automatically added by the kanban bot

**Comment by boherm** [comment]
After some discussion for this feature with @jolelievre and @ibahloul-ps, we have decide to avoid the use of new category `HO` to add the new `Hook Contribution` label on the PR.

But, kanbanbot need to check the PR diff and if he find `dispatchWithParameters`, `dispatchHookWithParameters` or `Hook::exec`, he add the `Hook Contribution` label automatically.

I will make a new PR to reflect this change in the kanbanbot repository.
