### ISSUE TITLE
BO > Search > Aliases : Search doesn't work

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#37551]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have this error : 

![Image](https://github.com/user-attachments/assets/6a76d097-3c21-4291-9b16-f3b0d513d6de)

### Expected behavior

No Error.

### Steps to reproduce

1. Go to BO > Search > Aliases
2. Search "a" in search term
3. Click on Search

### PrestaShop version(s) where the bug happened

9.0.x

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

**Comment by boherm** [comment]
I reproduce this issue, nice catch @Progi1984!
On it ;)

**Comment by boherm** [comment]
Fixed in https://github.com/PrestaShop/PrestaShop/pull/37470!

**Comment by florine2623** [comment]
Hello @Progi1984 ,

I can't reproduce your issue :
https://github.com/user-attachments/assets/1d511de0-20f7-4623-ab1d-c7330f373e18

I tested with Old and New Search page. In both cases I do not have an exception displayed.
