### ISSUE TITLE
gsitemap cron doesn't work

### ISSUE THREAD

**Issue by sirius82** [PrestaShop/PrestaShop#37613]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,
The gsitemap module, ver 4.4.0, installed on a PS 8.1.4. It works fine when I launch the url directly (https://my-domaine/gsitemap/cron?toke,n=xxxxxxx).
But it doesn't work as cron task, the server send me a mail error with "No such file or directory" and the sitemap is not created.
I have this issue on all my recent website.

DO you have an idea ? If I remember, it was possible to create a script to lanch the url and we have to add this script as cron. But I dont retrieve how to do.

THanks a lot

### Expected behavior

RTo renew the sitemap with the cron

### Steps to reproduce

Go to the server
Add a cron
Enter 0 0 * * * https://www.my_domain.com/module/gsitemap/cron?token=335b216e31&id_shop=1

When the task is launched manually by copy/paste the link in the browser, the sitemap is updated

### PrestaShop version(s) where the bug happened

8.1.4

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

gsitemap v.4.4.0

**Comment by paulnoelcholot** [comment]
Hello @sirius82,

Thanks for reporting this issue!
Ping @PrestaShop/prestashop-core-developers : Could someone please try to reproduce the issue, it's too technical!

Thanks in advance!

**Comment by nicosomb** [comment]
@sirius82 I didn't have a try but I can see that you have two different URL in your issue: the one you call via your browser and the other one you call via the cron. Maybe one of them is wrong?

**Comment by sirius82** [comment]
Hi,
Thanks to both of you, I finally found the solution: you have to write curl before the address: curl https://my_domaine.com/module/gsitemap/cron?token=335b216e31&id_shop=1
Now, it works.
Perhaps it should be necessary to add this information in Prestashop?

**Comment by nicosomb** [comment]
@sirius82 glad to see it's ok for you. Good idea about adding the information: it's an easy "todo" as a first contribution to our project.

**Comment by ECC64** [comment]
hello :)

Still the problem with the gsitemap URL for CRON
Already, the folder isn't module, but modules (with an S). The CRON file doesn't exist, and the GSITEMAP-CRON.PHP file doesn't work. An error appears: Notice: This file should no longer be used and will be removed in version 5.0.0 of this module. Please update your cron tasks to use the new URL available in module settings. in /htdocs/modules/gsitemap/gsitemap-cron.php on line 32
best regards
