### ISSUE TITLE
Market place problem - enventbus Required

### ISSUE THREAD

**Issue by lucie-def-dev** [PrestaShop/PrestaShop#37623]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I can't install enventbus, It prevents me from having access to the prestashop marketplace! 

![[Image](https://github.com/user-attachments/assets/3b402353-943e-4bbb-b0f0-85ce131c7cc4)](https://github.com/user-attachments/assets/3b402353-943e-4bbb-b0f0-85ce131c7cc4)

### Steps to reproduce

go to dashboard and module, marketplace

### PrestaShop version(s) where the bug happened

1.7.8.11

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

PrestaShop Marketplace in your Back Office v3.2.0

### Your company or customer's name goes here (if applicable).

chic3k

**Comment by paulnoelcholot** [comment]
Hello @lucie-def-dev,

I try to reproduce your issue but as you can see, I can't : ![Image](https://github.com/user-attachments/assets/bd043798-f4e4-4db3-bdc9-89130ee40635)

Did I miss something?

Thanks for your feedback

**Comment by lucie-def-dev** [comment]
The bug occurs when I want to update prestashop metric I have an error message like enventbus is necessary but when I try to install it it doesn't work.

**Comment by intraordinaire** [comment]
Hello @lucie-def-dev ,

Can you access the filesystem via SSH or FTP ?
Is the folder `ps_eventbus` present in the `modules` folder ?
Have you tried to clear the `cache` folder ? (delete everything under `var/cache/` or by clicking `Empty cache` button in the BO `Advanced Parameters > Performances`) ?

Also, can you tell us what version of modules you have for : `ps_metrics`, `ps_mbo` and, if present on your disk, `ps_eventbus` ?

Thanks

**Comment by lucie-def-dev** [comment]
Hello intraordinaire, 

I'm not expert enough to do this .. on the other hand here are the versions of ps-metrics : v4.0.9 et v3.2.0 pour ps_mbo

I checked that the ps_eventbus folder is present in the site files .. ![Image](https://github.com/user-attachments/assets/24043d58-ca94-4f4b-b736-a2c1a3897bdc)

**Comment by intraordinaire** [comment]
Do you have access to this page ? (Paramètres avancés > Performances)
Can you try to click the "Vider le cache" button ?
<img width="1768" alt="Image" src="https://github.com/user-attachments/assets/6f17dccf-705e-4d4a-b0cc-daa0be5fe38e" />

**Comment by lucie-def-dev** [comment]
Yes indeed I did this manipulation but it doesn't change :(

**Comment by Hlavtox** [comment]
Not related to the open source project. Contact the authors of this module - PrestaShop company department.
