### ISSUE TITLE
Error Saving Social Media URLs in Prestashop 8.2.0

### ISSUE THREAD

**Issue by MarketingFoco** [PrestaShop/PrestaShop#37674]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I am having an issue with the social media tabs: when I enter the URLs for my Facebook and Instagram links, an error code appears, preventing me from saving them. My Prestashop version is 8.2.0. 

![Image](https://github.com/user-attachments/assets/85ed52dc-9651-4905-92bb-b4a5d2276f10)
![Image](https://github.com/user-attachments/assets/ba1a6f4b-0036-49d8-af82-01b8d3ee212f)
![Image](https://github.com/user-attachments/assets/703ac756-3b0c-44d1-b6cf-eba53678ba42)

### Steps to reproduce

Open the back office, go to Customization > Modules. Click on Module Manager, then type "Social Media Follow Links" in the search bar. Click on Configure, remove the # symbols, and enter the URLs for the Facebook and Instagram links. Click on Save. An error message appears: 'Invalid URL : #'.

### PrestaShop version(s) where the bug happened

8.2.0

### If your bug is related to a module, specify its name and its version

Social Media Follow Links - v2.3.2 - by PrestaShop

### Your company or customer's name goes here (if applicable).

Focoflor Diffusion

**Comment by paulnoelcholot** [comment]
Hello @MarketingFoco,

I try to reproduce your issue but as you can see, I can't : 
![Image](https://github.com/user-attachments/assets/ae200fef-dc38-432c-89c3-4ca77c72c4a1)


We only use GitHub issues to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Thank you
