### ISSUE TITLE
Regeneration of category images, permanently deletes menu thumbnail images

### ISSUE THREAD

**Issue by vnt** [PrestaShop/PrestaShop#37688]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If you regenerate Categories images and chose of erase previous images > Yes,

The Category Thumbnails and Category cover image thumbnails are regenerated.

**Menu thumbnails are deleted instead of regenerated**

### Steps to reproduce

1. In the edit category, add an image to the thumbnail menu
2. Go to BO > Design > Image Settings > Regenerate thumbnails
Select an image > Categories
Select a format > All
Erase previous images > Yes

### PrestaShop version(s) where the bug happened

8.2

### PHP version(s) where the bug happened

8.1.31

### Your company or customer's name goes here (if applicable).

David

**Comment by Hlavtox** [comment]
Fixed in 9.0.0 that is coming soon. Both images are now independent and will work properly. :-)
