### ISSUE TITLE
robots.txt the string "Disallow: /*?q= " is missing

### ISSUE THREAD

**Issue by vnt** [PrestaShop/PrestaShop#37689]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi,

The SEO department has identified a significant issue that has started
to occur on Prestashop websites and could seriously harm the SEO
performance of the stores.

Essentially, in a short period of time, the number of canonical pages
has jumped from a few thousand to over 300k pages.

In category pages we have filters to narrow down products, which after an update add a parameter that before
was not managed.
https://nomesito.ext/it/38-prodcut-name?q=
Since each parameter can be chained in any order, it results in a potentially infinite number of combinations.
This problem is particularly dangerous for SEO becouse it increases exponentially the number of crawlable
pages of a website, and it already occurred on 3 different websites with PS 8 and PS 1.7.x

The problem is that suddenly in the span of 2 months the number of canonical pages went up from few
thousands to 300k+ pages.
This is due to the fact that was introduced a new filter in the category pages, whose parameter is q= and was
not disallowed from the robots.txt.
We already managed the robots.txt back then, adding the correct parameters to Disallow

What could be the solution?
Add in htaccess a rule such as that all the urls containing q= become 410. (so that Google drops such
urls from the index)
Change the parameter from q= to something different (filter_category=?)
disallow the new parameter in the robots.txt
1) 2) 3) This way:
1) 2) Google does not index the new filters because they are disallowed in the robots;
Google drops the list of URLS containing the parameter q= because they are not disallowed, Google
can scan then, and being a 410 they are soon dropped from the index, allowing the website to return to
a normal amount of indexed and crawlable pages.

### Expected behavior

We expect to have a clean serp

### Steps to reproduce

BO > Traffic & SEO > Robots file generation
the string "Disallow: /*?q= " is missing
aprire il file robots.txt

### PrestaShop version(s) where the bug happened

8.2, 1.7.8

**Comment by Hlavtox** [comment]
Hi, this issue is already fixed in this PR - https://github.com/PrestaShop/PrestaShop/pull/37066

Change is simple, you can backport it to your shop.
