### ISSUE TITLE
Combination dropdown title error

### ISSUE THREAD

**Issue by hoaglandjl** [PrestaShop/PrestaShop#37718]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When creating a combination of any product, I get a title of "SLP Key Chain" above the quantity dropdown that is always the same and is incorrect. I have shown the html markup area affected and the view of the error as seen on the web site. There is no current combination product of SLP Key Chain. I have cleared the cache. 

<img width="1025" alt="Image" src="https://github.com/user-attachments/assets/c3319b1c-8f5f-4ff0-9a1a-717c6ab4c5f9" />

### Expected behavior

Either, no title here or the correct title of the current product combination.

### Steps to reproduce

1. Search for product on site
2. Open
3. Error it there

### PrestaShop version(s) where the bug happened

8.2.0

### PHP version(s) where the bug happened

8.1.31

### Your company or customer's name goes here (if applicable).

Blue Tree Publishing, Inc.

**Comment by Hlavtox** [comment]
Related to third party theme, third party module or custom html caching module.
