### ISSUE TITLE
Paypal v6.4.2-paypal update issues

### ISSUE THREAD

**Issue by adamus007p** [PrestaShop/PrestaShop#37716]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello I would like to report few things. I was updating 1.7 to 8.2 whole presta and i faced some problems.

1st is in a bug in the code: v6.4.2-paypal, 

from
`        curl_setopt($curl, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_2);
`
to
`        curl_setopt($curl, CURLOPT_SSLVERSION, \CURL_SSLVERSION_TLSv1_2);
`

and add
`       if (defined('CURL_SSLVERSION_TLSv1_2') == false) {
            define('CURL_SSLVERSION_TLSv1_2', 6);
        }
`
services\Checker.php

2. Add option to disable of cheking a post code and states. There is only few states which require it. Sometime there was errors because it was bad formating in Prestashop and customer put the correct post code but the Paypal gives errors.

It give more possible errors then advantages.

I just comment
`            //'postal_code' => $address->postcode,
`
and
`        if(in_array($address->id_country,[17,21,1,14])){
            if($address->id_country==17) $addressArray['postal_code']='E151XH';
            else $addressArray['postal_code']='00000';
        }
        
`
services\Builder\OrderCreateBody.php

`        curl_setopt($curl, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_2);
`
to
`        curl_setopt($curl, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_2);
`

I add also
`       if (defined('CURL_SSLVERSION_TLSv1_2') == false) {
            define('CURL_SSLVERSION_TLSv1_2', 6);
        }

`
classes\Webhook\WebhookAvailability.php

I add it
`       if (defined('CURL_SSLVERSION_TLSv1_2') == false) {
            define('CURL_SSLVERSION_TLSv1_2', 6);
        }

`
classes\API\Client\HttpClient.php

Moreover I use cloudflare so I had to add Paypal IP
to firewall
https://www.paypal.com/us/cshelp/article/what-are-the-internet-protocol-ip-addresses-for-paypal-server-endpoints-ts1056

I would be great if you would add this info to the module and this link or ip

as it use Curl and cloudflare can block it.

The next thing is that when you upate the module it keep all old files in the module. I have checked it when i have click in report/diagnostics.
There were a number of changed files. When I delete and add a new module from scratch the number of changed files were much lower.

I think that this bevavior of keeping old files during the update it is a behaviour.

The last thing what I have noticed that update of new module change a currency to the customer. I had a main shop currency.
It should be no such change or info after install to check it, when you update it.

Improvement:
It would be nice if you could add an order like there is in Stripe module when customer will inciate an order not when only will confirm it.
I don't know why but the webhook is slow in Paypal compare to Stripe.

### Steps to reproduce

I wrote it above

### PrestaShop version(s) where the bug happened

8.2

### PHP version(s) where the bug happened

php 8.1

**Comment by Hlavtox** [comment]
Hi, you must contact the authors of the paypal module, so they ensure the compatibility.
