### ISSUE TITLE
Contact Form: Some messages arent saved in the backend and are only sent by email

### ISSUE THREAD

**Issue by OctoY** [PrestaShop/PrestaShop#37723]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Some of the messages sent via the contact form arent saved in the backend. I can't find them in the Customer Service page but they are properly sent by email.

### Expected behavior

All the messages should be saved in the backend not only some of them.

### Steps to reproduce

I tried to reproduce it but couldn't. I only observe that some messages sent by customers aren't there.

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

Contact form v4.4.2 - by PrestaShop

### Your company or customer's name goes here (if applicable).

Gestocigars SA

**Comment by florine2623** [comment]
Hello @OctoY ,

I tried to reproduce your issue, I couldn't.

<img width="1184" alt="Image" src="https://github.com/user-attachments/assets/d73f24a9-2763-4173-a86c-3dec4f11fb2e" />


We use GitHub issues only to discuss about bugs and new features in the PrestaShop project. If you need support, you can find resources to help you on this page: [Get help with PrestaShop](https://www.prestashop-project.org/support/).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you
