### ISSUE TITLE
Upgrade from 1.7.3.1 to 1.7.4.2

### ISSUE THREAD

**Issue by juraj1000** [PrestaShop/PrestaShop#9745]
Hi,
I've just upgraded from the release 1.7.3.1. to 1.7.4.2 with 1-click upgrade. The system has successfully finished the upgrade. After starting logon admin page there is something wrong: 

![image](https://user-images.githubusercontent.com/33311857/44475675-f218f700-a635-11e8-94d8-5f4e89f7cec5.png)

You can see that fonts and alignments are wrong. The similar situation is also with some pages for administration after logon. Some pages are OK, some are wrong.

Please could you send me info how to correct it?

Best Regards
Juraj

**Comment by Quetzacoalt91** [comment]
Hi,

This could be caused by the updated CSS / JS. You should force refresh the browser (by pressing ctrl + shift + R on Windows / Linux, CMD + R on Mac OS).

If this does not fix the issue, please check the assets (JS / CSS) are properly loaded by checking the network tab of your browser console.

**Comment by juraj1000** [comment]
Hi,
thanks, pressing Ctrl + Shift + R has helped.
Best Regards
Juraj
