### ISSUE TITLE
Migrate Improve > Design > Link Widgets

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#9746]
- [x] PR in Core
- [x] PR in module
- [x] release module

Migration to Symfony to the page located here: http://localhost/admin-dev/index.php?controller=AdminLinkWidget

[Migration doc](https://github.com/PrestaShop/prestafony-project/blob/master/docs/migration-guide.md)
[Morden controller doc](https://github.com/PrestaShop/prestafony-project/blob/master/docs/create-your-own-modern-controllers.md)

Linked to https://github.com/PrestaShop/prestafony-project/issues/25
Locked by https://github.com/PrestaShop/prestafony-project/issues/11

**Comment by jolelievre** [comment]
https://github.com/PrestaShop/ps_linklist/pull/48

**Comment by matks** [comment]
**Note to myself:** check it works I am not sure whether it got into `develop`
